### ISSUE TITLE
How to build from scratch

### ISSUE THREAD

**Issue by bernardocs** [nuxt/nuxt.js#10]
Hey guys...

It's not that clear in the docs and the project's link is broken, so I'll ask here...
Do I need to get a basic `vue-cli` project and then go `npm i nuxt --save`?

**Comment by bernardocs** [comment]
I mean... a basic `webpack+babel` `vue-cli` template?

**Comment by Atinux** [comment]
Hi @bernardocs, @alexchopin is working pretty hard on the documentation website, as you can see the project is still in development and will be release at the end of this month.

The basic project is really basic, all you need is:
- package.json
- pages/

The `package.json`:
```json
{
  "name": "my-nuxt-app",
  "description": "",
  "dependencies": {
    "nuxt": "latest"
  },
  "scripts": {
    "start": "nuxt"
  }
}
```

And then, all your `.vue` files inside your `pages/` folder will become a route, for example, to create the route `/` you can add a file `pages/index.vue`:

```html
<template>
  <div class="container">
    <h1>Hello World</h1>
  </div>
</template>
```

Then, you can install `nuxt` by doing:
```bash
npm install
```

And launch your application with:
```bash
npm start
```

Check out the 1 minute video to know how it works: https://www.youtube.com/watch?v=kmf-p-pTi40

**Comment by Atinux** [comment]
I think I will add a `vue-cli` to boostrap a `nuxt.js` application quickly.

**Comment by alexchopin** [comment]
Hi @bernardocs,
You can now use the [starter](https://github.com/nuxt/starter) project base with vue-cli.
```
$ vue init nuxt/starter my-project  
$ cd my-project                     
# install dependencies
$ npm install # Or yarn install
```

**Comment by bernardocs** [comment]
Awesome!

Thanks, guys! 😃
