### ISSUE TITLE
Vuex store on the issue of more pages

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#100]
>* Install the template

```shell

vue init ddvs/nuxt testeui&&cd testeui&&npm i

```

>* Enter debug mode

```shell

npm run dev

```

This time we can normally open http://127.0.0.1:3000/admin

![image](https://cloud.githubusercontent.com/assets/11555571/21602999/c66a0fa4-d1d4-11e6-94e0-55d3abcd68ed.png)

I now have more sub-projects, such as background management system, web management, wap three versions of the phone, I hope to separate Vuex store how do?

>* Tips: Updated ddvs / nuxt today, need to re-install ddvs / nuxt template

But [nuxt store](https://github.com/nuxt/nuxt.js/tree/master/examples/vuex-store) The current manual only supports one set

**Comment by Atinux** [comment]
Indeed, to support correct server-side rendering, only one store instance should exist.

I recommend you to use [Vuex modules](http://vuex.vuejs.org/en/modules.html) for each of your sub-projects.
