### ISSUE TITLE
empty nuxt.state parameter in a nuxt module during a 301

### ISSUE THREAD

**Issue by loick** [nuxt/nuxt.js#10005]
Hi, 

I happened to find something interesting in the nuxt modules: when using a redirect from a middleware, the following piece of code from my module outputs an empty state (undefined). 

Use case: 
- User goes to a restricted page while being unlogged
- User gets redirected from a middleware
- The nuxt module(s) using the nuxt.state parameter is empty

```js
this.nuxt.hook('vue-renderer:ssr:context', ({ url, nuxt: { state } }) => {
  // if redirect() has been used, state is empty
})
```

Any reason why?

**Comment by loick** [comment]
I closed the other issue I opened before with more info in it. https://github.com/nuxt/nuxt.js/issues/9866

Any idea?

**Comment by shubhangchourasia** [comment]
> Hi,
> 
> I happened to find something interesting in the nuxt modules: when using a redirect from a middleware, the following piece of code from my module outputs an empty state (undefined).
> 
> Use case:
> 
> * User goes to a restricted page while being unlogged
> * User gets redirected from a middleware
> * The nuxt module(s) using the nuxt.state parameter is empty
> 
> ```js
> this.nuxt.hook('vue-renderer:ssr:context', ({ url, nuxt: { state } }) => {
>   // if redirect() has been used, state is empty
> })
> ```
> 
> Any reason why?

Have you solved the issue? Please help. I have the same problem.

**Comment by loick** [comment]
Hi @shubhangchourasia, I didn't solve it. Regarding my use case, I mainly needed to clean the state from certain properties before sending it to the client side. So I'm only checking if `state` is undefined or not. 

However I created this issue because it felt weird to me to see the redirected requests going into this hook anyway. 

What is your case on your end?

**Comment by shubhangchourasia** [comment]
> Hi @shubhangchourasia, I didn't solve it. Regarding my use case, I mainly needed to clean the state from certain properties before sending it to the client side. So I'm only checking if `state` is undefined or not.
> 
> However I created this issue because it felt weird to me to see the redirected requests going into this hook anyway.
> 
> What is your case on your end?

In my case also the state becomes null when I use redirect(). This is happening in the middleware where I am redirecting the user on the basis of its role. The data gets fetched from cookies and stored in a state. Even the state is not null if I just put console log in the if condition where I am checking if the user is admin or manager. But as soon as redirect() comes in it says state is null and does not redirect the user.
