### ISSUE TITLE
Redirects don't seem to respect target page component's head section (or at least title, specifically)

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/nuxt.js#1001]
Subj. I.e. if I have a page `pages/index.vue` redirecting to `/students`, and then in `pages/students.vue` there's `head: { title: 'students' }`, it's not being taken into account and the actual DOM tree's head section is not updated.

**Comment by Andkoo** [comment]
Did you try making the head a method? According to docs the `head` should a method.
https://nuxtjs.org/api/pages-head/#the-head-method

```
head () {
  return {
    title: 'students'
  }
}
```

**Comment by gbezyuk** [comment]
@Andkoo actually it seems to work now, no matter the function or the object I use. Looks like there were a version bump fixing this.
