### ISSUE TITLE
What cause a glitch when page transition in Firefox?

### ISSUE THREAD

**Issue by jerakode** [nuxt/nuxt.js#1002]
Hi. Somebody notice a little annoying glitch in Firefox (I am using Ubuntu, not sure if it's related to OS) - when page transition is triggered, page footer jumps to top of the screen for 1ms (very quickly but unfortunately noticible). What can cause that behavior? In Chrome all just fine.

**Comment by jsonberry** [comment]
@jerakode Weird, I am seeing the same behavior on Chrome 59 on OSX 10

## Setup
Default Nuxt scrollBehavior. Navigate to a route using a `<nuxt-link>`, bound "to" with a string like this: `<nuxt-link :to='link'>`, hit the browser "back" button. Example:

![footer-scroll](https://user-images.githubusercontent.com/3082536/27893975-4691d594-61be-11e7-8847-8b0abcde6a3b.gif)

**Comment by jerakode** [comment]
Have no idea what that screenshots mean, but pretty sure that you can't capture glitch that I am talking about with gif :smile:

Doesn't look like my issue.

**Comment by jsonberry** [comment]
@jerakode It's an example of ` page footer jumps to top of the screen for 1ms`

**Comment by jerakode** [comment]
How can you capture 1ms with GIF frame rate? I see just 3 pictures changing one another. But I waste 2 minutes to load this gif with my awful VPN extension, lol.

**Comment by Atinux** [comment]
Hi,

This is normal in development mode, see https://nuxtjs.org/faq/css-flash

**Comment by iamdubx** [comment]
This not in DEV mode!
