### ISSUE TITLE
npx nuxi init nuxt3-app  err

### ISSUE THREAD

**Issue by zhanghu11** [nuxt/nuxt.js#10020]
npx nuxi init nuxt3-app
 WARN  could not fetch remote https://github.com/nuxt/starter                                                 17:11:28

 WARN  Make sure you have installed git correctly

**Comment by danielroe** [comment]
Check that you have installed git correctly. And if you are still experiencing an issue, feel free to raise one on https://github.com/nuxt/framework/issues/new/choose.
