### ISSUE TITLE
fs package not working when i switch between pages

### ISSUE THREAD

**Issue by pirtpal-rwit** [nuxt/nuxt.js#10032]
https://www.npmjs.com/package/fs/

I want to save my API data in JSON file
```
const fs = require('fs');
if(fs.writeFileSync){
  fs.writeFileSync('home.txt', 'data') 
}
```
on page load, it works fine, but when I switch between page it's not work fs showing empty

I want to store all my API data in folder to use as cache

**Comment by silvesterwali** [comment]
hi @pirtpal-rwit i think fs not working in browser .
please follow this related topic https://github.com/vuejs-templates/webpack/issues/262#issuecomment-301097541
