### ISSUE TITLE
Loading file based css

### ISSUE THREAD

**Issue by Tabrizian** [nuxt/nuxt.js#1003]
Hi there :)
I'm trying to load a simple css file as stated in the docs. But I fail to do so. The name of css file is stored in ```assets/App.scss```. And the css section my ```nuxt.config.js``` is like below:
```js
  css: [
      'bootstrap-material-design/dist/css/bootstrap-material-design.css',
      'bootstrap-material-design/dist/css/ripples.css',
      {src: '~assets/App.scss', lang: 'scss'}
  ]
```

But this gives me following error:
```sh
This dependency was not found:

* ~assets/App.scss in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./.nuxt/App.vue

To install it, you can run: npm install --save ~assets/App.scss
```

I have read the docs many times I can't find where I'm doing wrong.

**Comment by pi0** [comment]
Iman, please ensure sass dependencies are installed (`node-sass` and `sass-loader`) Also there is no need to directly specifying lang if using nuxt `1.x` as it is automatically loaded by webpack :)

**Comment by Tabrizian** [comment]
Oh thanks Pooya :+1:
