### ISSUE TITLE
Redirect in a middleware resets the store 

### ISSUE THREAD

**Issue by Andrei997** [nuxt/nuxt.js#1004]
I am currently using an authentication middleware to check if the user is logged in or not. 
If not, the user is redirected to a login page. 
My problem is that I want to save the current route (before the redirect) so that I can send the user back to the page they were trying to get before the redirect. Now, the redirect method seems to reset the store, I've tried this with multiple middleware. Is there any other way I can redirect the user to the login page that won't reset the store ? I can't seem to be able to access the router with 
`this.$router` or with `this.$nuxt.$router`.

**Comment by uptownhr** [comment]
local storage not a method?

**Comment by Andrei997** [comment]
This can also happen on the server side, where local storage wouldn't be available.

**Comment by uptownhr** [comment]
how are you managing user session right now?

**Comment by Andrei997** [comment]
I am currently using the google login api, and the id provided as api tokens. I've got that figured out with cookies and headers, I could set the redirectUrl in a cookie, but I would rather handle that within my application, since I already instantiate a store I don't want to use too many cookies. Is the $router available inside the middleware by any means ?

**Comment by Andrei997** [comment]
I used a cookie 💃 , closing this, great framework btw, love it 👍
