### ISSUE TITLE
Can't open more than 3 tabs

### ISSUE THREAD

**Issue by skwasan** [nuxt/nuxt.js#10059]
### Versions

- nuxt: v2.13.0
- node: v12.14.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Open more than 3 tabs of localhost:3000

### What is Expected?
Should open the 4th, 5th tab

### What is actually happening?
It stucks and does not load but opening in cognito windows work until 3 tabs.

**Comment by reinoldus** [comment]
This is a chrome limitation (only allows a certain amount of socket connections to be opened)
You can use firefox to increase the limit

Check out this issue: https://github.com/nuxt/nuxt.js/issues/6007

Particularly this reply: https://github.com/nuxt/nuxt.js/issues/6007#issuecomment-515424462
