### ISSUE TITLE
Nuxt 3 | Cannot start nuxt:  Cannot find module 'nuxt'

### ISSUE THREAD

**Issue by Miguelklappes** [nuxt/nuxt.js#10062]
Versions

- nuxt: 3.0.0-27286006.a08b435
- node: 14.16.0
- OS: Windows 10

### Reproduction

Link to a minimal test case based on one of:
-[Bug reproduction link](https://github.com/Miguelklappes/nuxt-3-bug)

<summary>Additional Details</summary>
![imagen](https://user-images.githubusercontent.com/74425206/142224484-e135c77d-0018-49d3-9edb-663cbcfa651a.png)

### Steps to reproduce

1. npx nuxi init nuxt3-app
2. code -r nuxt3-app
3. yarn install
4. yarn dev -o

### What is Expected?

A functioning Nuxt App

### What is actually happening?

A bugged Nuxt App

**Comment by productdevbook** [comment]
Please open issues -> https://github.com/nuxt/framework

This repo nuxt2.
