### ISSUE TITLE
How create a custom router with redirect?

### ISSUE THREAD

**Issue by congtoanle** [nuxt/nuxt.js#1006]
I want to create a custom router like Facebook Profile, Facebook Pages:
abc.com/users/john-doe redirect to: abc.com/john-doe
abc.com/pages/justin-bieber redirect to abc.com/justin-bieber

How can I do this?

Thank you!

**Comment by Plasmatium** [comment]
In asyncData method, you can use redirect function to do this. 
[Context -> redirect Function](https://nuxtjs.org/api/)

**Comment by alexchopin** [comment]
You can also use `validate` function to check your params.
[Documenation](https://nuxtjs.org/api/pages-validate)

**Comment by therddlr** [comment]
@alexchopin there's no `redirect` in `validate`. It's not working, not sure why you advise this?
