### ISSUE TITLE
Payload data is disappearing on page load. nuxt generate ; nuxt start

### ISSUE THREAD

**Issue by lopugit** [nuxt/nuxt.js#10069]
I've made this very simple reproduction where a route with payload data seems to fallback to SPA mode and lose the payload data on a very basic page.

I made this project today using `yarn create nuxt-app project`and just added a simple wildcard page with a route in generate: routes

I have documented that it displays the payload data very briefly on load but then loses the data...

I have zipped and attache the reproduction project and a GIF of the behaviour.

https://user-images.githubusercontent.com/13629190/142963594-c3c21089-86a8-446f-a701-7274aaa3d5f4.mp4

<img width="1615" alt="Screen Shot 2021-11-23 at 1 32 20 pm" src="https://user-images.githubusercontent.com/13629190/142968701-e99f9024-399b-4f42-b56c-8186d373d678.png">

[test-payload.zip](https://github.com/nuxt/nuxt.js/files/7585530/test-payload.zip)

**Comment by danielroe** [comment]
@lopugit At a very quick glance, it looks like the route (`test`) doesn't match the path you're visiting (`test/`)

**Comment by lopugit** [comment]
> @lopugit At a very quick glance, it looks like the route (`test`) doesn't match the path you're visiting (`test/`)

ding ding ding that was more or less it, route needed to be (`/test`) instead of (`test`)

thanks a lot
