### ISSUE TITLE
Environment variable doesn't work well with NuxtLink and Vue Meta (static website)

### ISSUE THREAD

**Issue by YumiSuki** [nuxt/nuxt.js#10063]
Recently, I have tried moving from hard code meta information to load it from .env file. In the process, I found there is some problem when using this method with NuxtLink. What I have found is that, if we directly access the website using full path url, for example, http://example.com/test-path, then the meta information load correctly. But, if I access http://example.com and then click on any specific path for that is using NuxtLink, then meta information isn't load correctly and got undefined.

In my nuxt.config.js:
```
  ...
  target: 'static',
```

.env:
```
meta_test_title=test-page
meta_index_title=index-page
```

index.vue page:
```
<template>
  <NuxtLink to="/test">Go to Test Page</NuxtLink>
</template>


<script>
export default {
  head() {
    return {
      title: process.env.meta_index_title,
    };
  },
};
</script>
```

test.vue page:
```
<template>
  <NuxtLink to="/">Go to Index page</NuxtLink>
</template>

<script>
export default {
  head() {
    return {
      title: process.env.meta_test_title,
    };
  },
};
</script>
```

- Direct access through URL and the title display correctly:
![Direct access through url](https://user-images.githubusercontent.com/63283300/142358732-e031fc2a-4caa-4bda-a0ab-83956d40a60a.png)

- Click through NuxtLink URL and the title doesn't load from .env but got undefined and using the default one
![Click through NuxtLink Url](https://user-images.githubusercontent.com/63283300/142358681-26dd1c22-911c-46ff-9880-d0dbdef18df1.png)

I have create a sample project here for reproduce purpose: https://codesandbox.io/s/hardcore-danny-mr2t1

**Comment by silvesterwali** [comment]
hi @YumiSuki , in my case i install dotenv and cross-env 
and in my `nuxt.config.js `  i just add in top it .  you can try this maybe can help
```js
require('dotenv').config()
```

**Comment by jasenmichael** [comment]
https://nuxtjs.org/tutorials/moving-from-nuxtjs-dotenv-to-runtime-config/

"For nuxt versions > 2.12+, in cases where environment variables are required at runtime (not build time) it is recommended to subsitute the env property with runtimeConfig properties : publicRuntimeOptions and privateRuntimeOptions.
Learn more with our tutorial about moving from @nuxtjs/dotenv to runtime config ."
