### ISSUE TITLE
Implement titleTemplate from vue-meta

### ISSUE THREAD

**Issue by nachtfunke** [nuxt/nuxt.js#10073]
### Is your feature request related to a problem? Please describe.

In Nuxt 2, setting a template for a documents `<title>` element was easy, a use case so common, it was used as an example for changing up `<head>` content in the docs: https://nuxtjs.org/docs/configuration-glossary/configuration-head/#the-head-property. Yet now this seems to be not possible any longer in Nuxt 3. Information about how and why that is seems to be shrouded a bit in mystery - is it just not available _yet_? I joined the discord because even on the [discussions forum](https://github.com/nuxt/framework/discussions/1768) on github, that specific part about `titleTemplate` keeps getting left out - I am not sure why that is.

On the discord I was prompted to use a solution that couldn't look more unintuitive to me - to a point where I am actually not able to implement this functionality at all. I was also prompted to make a feature request, if I wanted to see this implemented. Maybe it is planned to bring this to nuxt 3 anyway, in that case I am sorry for making this issue.

### Describe the solution you'd like

I would like to be able to set a `titleTemplate` from a single place, with a defined string that will be replaced by what is set in `title` in pages accordingly.

### Describe alternatives you've considered

Here's what people told me I should do instead:

- implement a store
- `$emit` the `title` to the template
- "you can use a computed title rather than title template."; clarified with an example that would still require me to lift state up from pages to where that "computed title" would be defined:
```javascript
useMeta({
  title: computed(() => `${title} - My Site`)
})
```

All of them seem to introduce complexity that seems counterintuitive for something as simple as `titleTemplate` - especially as this functionality already existed in nuxt 2.

***

I hope this is somewhat correct. Maybe I am also the only one having this problem - but it is difficult for me to understand why this was possible in nuxt 2 but seems to have been deliberately dropped from nuxt 3.

**Comment by command-tab** [comment]
I'm also wondering how to go about this. Every one of my Nuxt 2 apps uses `titleTemplate` at a high level (typically a layout) to include the app's name on all pages' titles and then each individual page contributes its specific title addition where the built-in `%s` substitution is placed in the `titleTemplate` value, and it's not clear how to do this in Nuxt 3. Can Nuxt 3's `useMeta` (or vue-meta — wherever the implementation lives) be updated to include the existing `titleTemplate` support from Nuxt 2? Thanks 🙏🏻

**Comment by manniL** [comment]
I think this should be [a discussion in the Nuxt3 framework repo](https://github.com/nuxt/framework).

**Comment by nachtfunke** [comment]
> I think this should be [a discussion in the Nuxt3 framework repo](https://github.com/nuxt/framework).

I was told to make this issue here in the nuxt discord.

**Comment by danielroe** [comment]
Issues and discussions related to nuxt 3 should be raised in https://github.com/nuxt/framework.

**Comment by nachtfunke** [comment]
> Issues and discussions related to nuxt 3 should be raised in https://github.com/nuxt/framework.

This repository does not allow feature requests. How am I supposed to proceed correctly here? Do you consider this a bug?

**Comment by danielroe** [comment]
You would raise it as a discussion first. But in fact there is already an issue tracking this: https://github.com/nuxt/framework/issues/3522
