### ISSUE TITLE
Missing upgrade guide from 1.x to 2.x

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt.js#10075]
The documentation to upgrading from v1 to v2 is missing. Previously it could be found at: https://nuxtjs.org/releases/#migration-guide-for-2-0-0

Any place I can find it?

**Comment by jasenmichael** [comment]
https://nuxtjs.org/docs/get-started/upgrading#upgrading

"Check the [release notes](https://nuxtjs.org/releases) for the version you wish to upgrade to see if there are any additional instructions for that particular release. "

**Comment by simplenotezy** [comment]
Good idea @jasenmichael - found it here: https://github.com/nuxt/nuxt.js/releases/tag/v2.0.0

Should be added to the upgrading page IMO though, took a bit of work to find it :D
