### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by Saad-Rehman** [nuxt/nuxt.js#10076]
This is the issue I am facing.
Note: All the information about the issue is in this
https://stackoverflow.com/questions/69941571/how-to-run-npm-run-start-from-release-pipeline-azure-devops-to-start-productio

**Comment by Saad-Rehman** [comment]
Pls answer me I am stuck in this issue and didnt found the solution after hours of searching

**Comment by jasenmichael** [comment]
this is not a nuxt issue.

is node running on the windows server? do you even need node? 
have you tried:
`npm run generate`
and then put the contents of the dist folder in a directory that serves static files?
