### ISSUE TITLE
Dynamic change of router base at runtime does not update script src

### ISSUE THREAD

**Issue by marcooop** [nuxt/nuxt.js#10088]
I would like to run my nuxt app on different environments without rebuilding, so I tried to use the feature of Nuxt 2.15.+ with a [dynamic router base](https://nuxtjs.org/docs/configuration-glossary/configuration-router#base).
It kinda works but not all paths are updated.

### Versions

- nuxt: 2.15.8
- node: 14.18.1

### Reproduction
Github link
[test project](https://github.com/marcooop/test-dynamic-base)

### Steps to reproduce

1. Init nuxt app
2. Install Docker Desktop
3. Set up a docker file
4. Set an environment variable for router base path in docker
5. Add this variable in nuxt.config.js to router base with default value like

    `router: { base: process.env.NUXT_BASE_URL || '/oldbasepath/', }`

6. In Batch/CMD: docker compose up
6. Go to URL and check HTML

### What is Expected?
Nuxt app is running, because not only preloading links and base href are updated, but also src of the scripts.

### What is actually happening
Nuxt app could not be loaded, because path of preload links and base href are updated but not script src.

![dynamic base path script src](https://user-images.githubusercontent.com/95077800/143612269-77838a30-6c41-419f-85c3-9e025448bc09.PNG)

**Comment by jtc42** [comment]
Thank god it's not just me! This has been driving me absolutely nuts. Did you ever find a workaround?

**Comment by marcooop** [comment]
@jtc42 Sorry, no real workaround besides aligning the base path on all environments, But I'm also glad that someone else can confirm this problem. Wasted several hours on this and it also drove me nuts.

**Comment by jtc42** [comment]
> @jtc42 Sorry, no real workaround besides aligning the base path on all environments, But I'm also glad that someone else can confirm this problem. Wasted several hours on this and it also drove me nuts.

Yep last week I ended up just doing the same. Figured that actually we don't change the base path enough to justify all this effort trying to make it work, so we're just setting it at build-time now. Honestly, kind of amazed I didn't just do that sooner, but you know when you've decided on a specific solution and can't see the wood for the trees.

**Comment by nicky-dev** [comment]
This workaround. It works (for me).
```js
// nuxt@2.15.8
// nuxt.config.js

module.exports = ({ command }) => ({
  router: {
    // set base = './' in build time.
    base: command === 'build' ? './' : process.env.BASE_PATH
  }
})

```

**Comment by YutaMoriJP** [comment]
Having the same issue...@marcooop did you find a solution or a workaround? If so, mind sharing it?

**Comment by YutaMoriJP** [comment]
@nicky-dev Thanks for posting a workaround. Quick question though, what's the `BASE_PATH` value and what's the point of it?

**Comment by nicky-dev** [comment]
`BASE_PATH=/basepath/`
