### ISSUE TITLE
Dynamic route parameter is always generated as optional

### ISSUE THREAD

**Issue by kmiszczynski** [nuxt/nuxt.js#1008]
According to documentation route parameter should be generated as required when it's created by underscored directory. It is not.

![structure](https://user-images.githubusercontent.com/14140972/27760727-0407a7c0-5e4f-11e7-8ef1-8eb40a672e4d.png)

is generating:

```javascript
	{
		path: "/ile-kosztuje/usluga/:service?",
		component: _6fec3b26,
		name: "ile-kosztuje-usluga-service"
	}
```

**Comment by alexchopin** [comment]
According to the [documentation](https://nuxtjs.org/guide/routing#dynamic-routes) : 
> As you can see the route named users-id has the path :id? which makes it optional, if you want to make it required, create an index.vue file in the users/_id directory.

**Comment by Atinux** [comment]
Can you create _service.vue instead of being a directory?
So you will have:
- usluga/
--| index.vue
--| _service.vue

**Comment by csharad** [comment]
I have a issue with the solution. Why create a new `index.vue` just to mitigate the optional? Why not just make the directory behaviour default for compulsory parameters? I think this is a bug either documention or implementation.

**Comment by lfallo1** [comment]
Was there ever an answer to this?  What the OP is asking can certainly be accomplished in the component itself.  But as he mentioned - the behavior doesn't match what the docs say.  Creating /post/_id/index.vue still creates an optional parameter.

**Comment by farzer** [comment]
@lfallo1 did you solved this issue?
