### ISSUE TITLE
Nuxt 2.15.7 not working with IE11. (SCRIPT1002: Syntax Error)

### ISSUE THREAD

**Issue by kevindaizj** [nuxt/nuxt.js#10091]
### Versions

- nuxt: v2.15.7+
- node: v12.8.3

### Reproduction
https://github.com/kevindaizj/nuxt-starter

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
1.  create project with `npx create-nuxt-app` 
2.  open `localhost:3000` with IE11 (and below)
3.  `SCRIPT1002: Syntax Error` occurs (vendors/app.js):
     
![KLLA5NX%RM1(F@ WU_Z%_D](https://user-images.githubusercontent.com/12622531/143754340-1e09e050-f3c8-418e-850c-1090685794f5.png)

4.  The code in `index.vue` doesn't work. (It seems that all custom code is not working)

### What is Expected?
no error

### What is actually happening?
Syntax Error occurs

**Comment by cyrossignol** [comment]
For development builds in IE11, I had to tell Nuxt to transpile a couple of dependencies in nuxt.config.js:

```javascript
export default {
  // ...
  build: {
    transpile: [
      ({ isDev, isLegacy }) => isDev && isLegacy && 'ansi-regex',
      ({ isDev, isLegacy }) => isDev && isLegacy && 'strip-ansi'
    ]
  }
}
```

It seems as if Webpack's hot middleware requires versions of these packages that aren't ES5-compatible anymore.
