### ISSUE TITLE
Office.JS -Nuxt : page reload only

### ISSUE THREAD

**Issue by benemohamed** [nuxt/nuxt.js#10097]
### Versions

- nuxt: v2.15.7
- node: v14.18.1

### Reproduction

Try migrate a `VueJs` project to `NuxtJs`.

### Steps to reproduce

include `<script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>` on config head or `app.html`

```javascript
    script: [
       {
         src: 'https://appsforoffice.microsoft.com/lib/1/hosted/office.js',
       },
    ],
```

```html
<head>
  <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
  {{ HEAD }}

```

### What is Expected?

if the Office initialize on the sideload show the welcome page else show error `Please sideload your addin to see app body.`

### What is actually happening?

the page reload and reload .......

**Comment by benemohamed** [comment]
Never mind ....

[Window objects that are unsupported in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/window-objects-unsupported-in-add-ins)

**Comment by benemohamed** [comment]
This works for me

```html
  <script type="text/javascript">
    // Office js deletes window.history.pushState and window.history.replaceState. Cache them .
    window._historyCache = {
      replaceState: window.history.replaceState,
      pushState: window.history.pushState
    };
  </script>
  <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
  <script type="text/javascript">
    // And restore them
    window.history.replaceState = window._historyCache.replaceState;
    window.history.pushState = window._historyCache.pushState;
  </script>

```

**Comment by lfglopes** [comment]
Tried your solution and I still have some issues:

```
Warning: Office.js is loaded outside of Office client 

Uncaught TypeError: can't redefine non-configurable property "context"
    defineNondefaultProperty https://appsforoffice.microsoft.com/lib/1/hosted/o15apptofilemappingtable.js:11
    defineEnumerableProperty https://appsforoffice.microsoft.com/lib/1/hosted/o15apptofilemappingtable.js:11
    <anonymous> https://appsforoffice.microsoft.com/lib/1/hosted/o15apptofilemappingtable.js:11
```

**Comment by CodeCube0** [comment]
> This works for me
> 
> ```
>   <script type="text/javascript">
>     // Office js deletes window.history.pushState and window.history.replaceState. Cache them .
>     window._historyCache = {
>       replaceState: window.history.replaceState,
>       pushState: window.history.pushState
>     };
>   </script>
>   <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
>   <script type="text/javascript">
>     // And restore them
>     window.history.replaceState = window._historyCache.replaceState;
>     window.history.pushState = window._historyCache.pushState;
>   </script>
> ```

@benemohamed this solution doesn't work in nuxt 3.12.2. Are there other solutions? It worked on previous versions

**Comment by benemohamed** [comment]
create Nitro server plugin name `server/plugins/office.ts`

```ts
export default defineNitroPlugin(async (nitroApp) => {
  nitroApp.hooks.hook('render:html', (htmlContext) => {
    htmlContext.head.unshift(`
            <script type="text/javascript">
              // Office js deletes window.history.pushState and window.history.replaceState. Cache them.
              window._historyCache = {
                replaceState: window.history.replaceState,
                pushState: window.history.pushState
              };
            </script>
            <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
            <script type="text/javascript">
              // And restore them.
              window.history.replaceState = window._historyCache.replaceState;
              window.history.pushState = window._historyCache.pushState;
            </script>
          `);
  })
});
```
