### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase') using "is" directive with async data

### ISSUE THREAD

**Issue by wellitongervickas** [nuxt/nuxt.js#10099]
### Versions

- nuxt: 2.15.3
- node: v16.9.0

### Reproduction

<details open>
<summary>Using async data to change component type is causing issues across transformation</summary>
<br>

</details>

### Steps to reproduce
``` 
<template v-if="isAuthenticated">
<component
    :is="isAutheticated ? 'a' : 'nuxt-link'"
    href="https://someexternal.com/en/someurl/"
    to="/en/someurl/"
>
test
</component>
</template>
``` 

#### To fix we need to use <client-only>
``` 
<template v-if="isAuthenticated">
<client-only>
<component
    :is="isAutheticated ? 'a' : 'nuxt-link'"
    href="https://someexternal.com/en/someurl/"
    to="/en/someurl/"
>
test
</component>
</client-only>
</template>
``` 

### What is Expected?
Transform component without throwing the entire app and blocking all DOM events

### What is actually happening?
Cannot read properties of undefined (reading 'toLowerCase')

**Comment by aliwesome** [comment]
I'm facing the same issue here.
