### ISSUE TITLE
Loop over pages

### ISSUE THREAD

**Issue by SteveEdson** [nuxt/nuxt.js#101]
Apologies if this is documented somewhere. I am looking into whether I should replace my Jekyll site for Nuxt, is there a way to loop over pages?

E.g Jekyll has 

```twig
{% for post in site.posts %}
    {{ post.title }}
{% endif %}
```

It would be nice if Nuxt had something similar, and if a page could expose meta data, e.g.

```html
<script>
export default {
    meta: {
        title: 'Hello World'
    }
}
</script>
```

Thanks.

**Comment by alexchopin** [comment]
Hi, thank for using Nuxt. 

Actually there is no way to use it like Jekyll does with:
```twig
{% for post in site.posts %}
    {{ post.title }}
{% endif %}
```
However, you can easily split you content and your design by creating markdown files in a post directory for example:

```bash
pages/
  post/
     slug.vue
  index.vue
post/
  welcome.md
```
then read this directory content to have the list of your post with [nuxtServerInit function](https://github.com/nuxt/nuxt.js/tree/master/examples/vuex-store#action-nuxtserverinit).
To parse markdown files content like Jekyll does, you can do it with [front-matter](https://github.com/jxson/front-matter).

I hope it will helps you :)

**Comment by Atinux** [comment]
Another way would be to use [require.context()](https://webpack.js.org/guides/dependency-management/#require-context) of Webpack to list the files of a specified directory and loop trough it :)

You can take a look at https://github.com/nuxt/nuxt.js/blob/master/lib/app/store.js to have an idea of how to use it.

If you add a markdown loader you may be also able to import them with webpack as well.

We want to develop nuxt-static with @alexchopin to create an easy alternative of Jekyll but with Nuxt.js

**Comment by NateTheGreatt** [comment]
@alexchopin 

How can one read the post directory content within the nuxtServerInit function?

**Comment by ericrovtar** [comment]
@Atinux Thanks for that tip. That's a smart solution. I want to replace my GitHub page / Jekyll site. I'd love a full alternative to Jekyll using Nuxt, but this should work for now. Thanks again!
