### ISSUE TITLE
How do I change the meta for routes?

### ISSUE THREAD

**Issue by Exitialis** [nuxt/nuxt.js#1010]
I need to create a component for breadcrumbs, and for it I need to add an addition in the form of meta to all routes. How can I do it? For example: 
`[ { name: 'profile',
    path: '',
    component: '...',
    meta: { breadcrumb: 'Профиль' } },
]`

**Comment by alexchopin** [comment]
Hi,
We don't have support for meta in `vue-router`, but you can use [vuex-router-sync](https://github.com/vuejs/vuex-router-sync) as a nuxt plugin.
```js
import { sync } from 'vuex-router-sync'
export default ({app: {store, router}}) => {
  sync(store, router)
}
```

**Comment by EasonShen1989** [comment]
I have the same problem with you. how to solve this problem @Exitialis

**Comment by Exitialis** [comment]
@EasonShen1989 I created a simple component that relates the names of routers to paths.

Example:
```vue
<template>
    <ol class="breadcrumb">
        <li v-for="item in crumbs" class="breadcrumb-item">
            <nuxt-link :to="item.path" active-class="active">
                {{ item.breadcrumb }}
            </nuxt-link>
        </li>
    </ol>
</template>

<script>
  const breadcrumbs = {
    // You should use / + name for the root route
    '/profile': 'Profile',
    // And just name of the page for child routes
   'profile-account': 'Account' 
  }

  export default {
    computed: {
      crumbs () {
        let crumbs = []
        this.$route.matched.forEach((item) => {
          if (breadcrumbs[item.name] || breadcrumbs[item.path]) {
            item.breadcrumb = breadcrumbs[item.name] || breadcrumbs[item.path]
            crumbs.push(item)
          }
        })

        return crumbs
      }
    }
  }
</script>

```

**Comment by EasonShen1989** [comment]
I tried, failed, the length of this.$route.matched always be equal to 1 @Exitialis

**Comment by Exitialis** [comment]
@EasonShen1989 It's because you have error in your pages directory. You should structure your pages directory like described [here](https://nuxtjs.org/guide/routing#nested-routes).

**Comment by EasonShen1989** [comment]
Well, thank you for speaking with you.I hope we can be friends. @Exitialis
