### ISSUE TITLE
Deploy Nuxt v3 to GitHub Pages

### ISSUE THREAD

**Issue by meta-john** [nuxt/nuxt.js#10113]
### Is your feature request related to a problem? Please describe.

Nope.

### Describe the solution you'd like

Build and deploy Nuxt v3 in static mode, and deploy to github pages.

Only nitro? .... but, not convenient enough...

**Comment by lucpotage** [comment]
Discussions related to Nuxt 3 are in this repo: https://github.com/nuxt/framework/discussions
Pre-rendering is not yet available, there is a corresponding RFC: https://github.com/nuxt/framework/discussions/666

**Comment by meta-john** [comment]
> Discussions related to Nuxt 3 are in this repo: https://github.com/nuxt/framework/discussions Pre-rendering is not yet available, there is a corresponding RFC: [nuxt/framework#560](https://github.com/nuxt/framework/discussions/560)

tks alot

**Comment by Lumethys** [comment]
is this feature supported yet? I didnt see Github Pages as a supported platform in the document, unlike Nuxt2

**Comment by lucpotage** [comment]
Hi @Lumethys, it's definitely possible. You can look at this repo I just created for you: https://github.com/lucpotage/nuxt-github-pages

**Comment by lucpotage** [comment]
FYI, full static generation was introduced in Nuxt 3 RC11 and was improved since then (latest is RC13). So I think you can close this issue.
https://github.com/nuxt/framework/releases

**Comment by gAtrium** [comment]
> Hi @Lumethys, it's definitely possible. You can look at this repo I just created for you: https://github.com/lucpotage/nuxt-github-pages

While the repo you have provided works for one page if you inspect the network it still tries to load from the root directory (i.e pages.github.io/ instead of page.github.io/repo) I think the issue is still present and needs to be looked at.

**Comment by Tragio** [comment]
@gAtrium  you can use:

```js
export default {
  app: {
    baseURL: '/example-default-route/'
  }
}
```

**Comment by lucpotage** [comment]
I updated my repo accordingly. Thanks @Tragio.

**Comment by gulybyte** [comment]
so as not to confuse and end up having problems forgetting some things, automate your run deploy:
```
 "deploy": "nuxt generate && touch .output/public/.nojekyll && gh-pages --dotfiles -d .output/public"
```
