### ISSUE TITLE
Chinese nuxt official website tutorial error

### ISSUE THREAD

**Issue by WorldToCode** [nuxt/nuxt.js#10128]
### Question
Chinese nuxt official website: https://www.nuxtjs.cn/guide/plugins
Use the tutorial to report an error directly, it may be that the imported library is not maintained
![image](https://user-images.githubusercontent.com/65691266/145549330-11b9a010-3c1e-44c7-add8-cdc41a9ea7a4.png)
![image](https://user-images.githubusercontent.com/65691266/145549394-d53d8705-b7bc-4d8a-846b-2318e9948bb7.png)

### What is Expected?
Repair document

### What is actually happening?
I hope it can be changed, because it took me a minute and it was too misleading.

**Comment by danielroe** [comment]
@WorldToCode I appreciate you raising this, but https://nuxtjs.cn is a third-party website and not maintained by the Nuxt team, though we obviously appreciate the effort of keeping it translated and up-to-date.
