### ISSUE TITLE
RangeError maximum calls stack size exceeded

### ISSUE THREAD

**Issue by ImadBoumzaoued** [nuxt/nuxt.js#1012]
I keep getting this error after the app runs for a while only on one page the others are almost the same code but works fine

<img width="538" alt="screen shot 2017-07-02 at 06 48 08" src="https://user-images.githubusercontent.com/1586936/27767556-dded3074-5ef2-11e7-8486-463269e1a18c.png">

please help

**Comment by alexchopin** [comment]
Can you provide us some samples or code snippets?

**Comment by ImadBoumzaoued** [comment]
`<template>
  <div>
    <div class="box rel bordered centered columns poll-results col-12">
      <h4 class="text-center" :class="{expires: data.settings.expires}">{{data.value}}</h4>
      <div class="column centered col-xs-12 col-md-12 col-8">
        <ul class="unstyled">
          <li v-for="(opt, index) of data.options" :key="opt._id">
            <div class="form-group" :class="{active: opt.checked}">
              <label :for="`opt-${index}`" class="form-checkbox">
                <input
                  :id="`opt-${index}`"
                  v-model="opt.checked"
                  @change="handleOptionChange($event, opt)"
                  type="checkbox" />
                <i class="icon form-icon"></i> {{opt.value}}
              </label>
            </div>
          </li>
        </ul>
        <div v-if="errorMessage" class="messages text-center">
          {{errorMessage}}
        </div>
        <div class="actions columns">
          <div class="column col-md-6 col-sm-12">
            <button
              class="btn btn-block btn-primary"
              :class="{loading}"
              @click.prevent="handleVote"
            >
              <i class="icon icon-check"></i>
              {{$t('viewPoll.sendVote')}}
            </button>
          </div>
          <div class="column col-md-6 col-sm-12">
            <nuxt-link
              :to="`/${number}/r`"
              class="btn btn-block">
              <i class="icon icon-format_list_bulleted"></i>
              {{$t('viewPoll.results')}}
            </nuxt-link>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>`

this is the component on that page

**Comment by Atinux** [comment]
Hi @ImadBoumzaoued 

How big if `data.options`, how many items does it have?

**Comment by ImadBoumzaoued** [comment]
at the moment the max it has is 15 items but it's kinda not the problem it seems to work on another page with exactly the same data but not with input checkbox

**Comment by Atinux** [comment]
Can you try to see which line cause this error @ImadBoumzaoued ?

**Comment by ImadBoumzaoued** [comment]
How i really can't see it in the error output,

**Comment by pi0** [comment]
@ImadBoumzaoued Is there any error on your server side console?

**Comment by ImadBoumzaoued** [comment]
the error is gone now if it happens again I'll see if there is any

**Comment by ImadBoumzaoued** [comment]
![screen shot 2017-07-03 at 18 33 46](https://user-images.githubusercontent.com/1586936/27802889-6e5adffe-601e-11e7-9880-4e58b9447623.png)
this is all there is in the console
this is app is on docker, its a bit loaded with users who keep going between two pages
one with the checkboxs which causes the error and one with just divs that display data which never caused the error.

any idea what causes this ? i'm on nuxt latest

**Comment by ImadBoumzaoued** [comment]
Forgot to say that the page with the error has a count down timer with setInterval but it's behind a v-if
could that cause the error anyway ?

**Comment by pi0** [comment]
When is that timer initiated? If not on mounted hook SSR will make much troubles unless ensure clearTimer is called before destroy :)

**Comment by ImadBoumzaoued** [comment]
its on mounted yes and I use clearInterval but seems it doesn't work anyway :P

**Comment by pi0** [comment]
I'm using timers in our nuxt projects without any problems :D If possible would you please try with `dev` branch of nuxt (using yarn link) We have added some source map helpers for even production. That may help.

**Comment by ImadBoumzaoued** [comment]
I will, but for now I don't feel confident enough to try, I removed the timer and I´ll try without it, because it took down my production app 4 times until now :P

thanks a lot for the help and the awesome project, I'll keep you posted.

**Comment by chunge0328** [comment]
@Atinux In production，Wrong：

https://dolceviva.com/productlist/53

Why

**Comment by chunge0328** [comment]
![image](https://user-images.githubusercontent.com/6309807/28810416-427e48c6-76bc-11e7-855b-c7983c0f3777.png)

**Comment by Fantomax** [comment]
The same error for me after updating to rc3.
BTW it happens every time in dev mode when I update something in the *.vue files

**Comment by pi0** [comment]
@chunge0328 @Fantomax Are you using timers in your code ? (setTimeout and setInterval)

**Comment by Fantomax** [comment]
@pi0 no

**Comment by Fantomax** [comment]
And there was no similar issue on alpha.4 with the same code. I updated alpha.4 to rc3 today

**Comment by pi0** [comment]
@Fantomax Can you please provide more logs? And possibly sharing your source code repository would allow us deeper investigate.

**Comment by Fantomax** [comment]
pi0 unfortunately I cannot share source code. I work on commercial project.
https://puu.sh/wYH7R/4d0af1ef69.png
https://puu.sh/wYH5c/bca354838a.png

**Comment by Fantomax** [comment]
I use custom server on express 4.15.3.
Other
`dependencies: {
    "aws-sdk": "2.80.0",
    "axios": "0.16.1",
    "body-parser": "1.17.2",
    "chart.js": "^2.6.0",
    "cookie": "^0.3.1",
    "cross-env": "4.0.0",
    "css-loader": "^0.28.3",
    "element-ui": "^1.3.4",
    "es6-promise": "^4.1.1",
    "express": "^4.15.3",
    "express-validator": "3.2.0",
    "js-cookie": "^2.1.4",
    "jsonwebtoken": "7.4.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "multer": "1.3.0",
    "node-sass": "^4.5.3",
    "node-schedule": "1.2.3",
    "nodemailer": "4.0.1",
    "nuxt": "^1.0.0-rc3",
    "pg": "6.2.2",
    "pg-hstore": "2.3.2",
    "s3fs": "2.5.0",
    "sequelize": "3.30.4",
    "sequelize-cli": "2.7.0",
    "socket.io": "^2.0.3",
    "socket.io-client": "^2.0.3",
    "source-map-support": "0.4.14",
    "vee-validate": "^2.0.0-rc.5",
    "vue-style-loader": "^3.0.1",
    "winston": "^2.3.1"
  }`

**Comment by Fantomax** [comment]
@pi0 I've noticed that vee-validate is the factor of my issue. If I disable it - app works

**Comment by pi0** [comment]
@Fantomax True. I think vee-validate isn't ssr friendly. Suggest using [vuelidate](https://github.com/monterail/vuelidate) by awesome monterail guys which work well with Nuxt too. (Potentially my answer is so Advertising 😆 )

**Comment by Fantomax** [comment]
Thanks, @pi0 
Will check vuelidate from your friends 👍

**Comment by ishitatsuyuki** [comment]
I just reproduced the same issue (with identical stack trace) on hn.nuxtjs.org. I was using the PWA, so no details are available.

It also occurs occasionally with my personal app too.

**Comment by ImadBoumzaoued** [comment]
Yup still have it too, no idea what causes it yet

**Comment by pi0** [comment]
Moving discussion to newer #1354 topic. BTW thank you all for this bug report.
