### ISSUE TITLE
Access env in Plugin

### ISSUE THREAD

**Issue by appinteractive** [nuxt/nuxt.js#1013]
Hey, I wonder how to access the environment `process.env.MY_VAR` inside a Plugin on frontend and backend.

We can't access `process.env` inside the browser which is intended, so I just throw it into the nuxt.config.js under "env". Then I should be able to access it in the plugin too. But here comes the tough part. I need to export an object and not an function in my case, but the env is only available through the dependency injection which needs a function parameter.

How can I export my object instead of the function?

Before (I can access the feathers object but the process is not available on the client)
``` JS
import hooks from 'feathers-hooks'
import authentication from 'feathers-authentication-client'
import storage from '~helpers/ssr-storage'

const host = process.env.API_HOST || 'http://localhost'
const port = process.env.API_PORT || '3030'
const socket = io(`${host}:${port}`)

const app = feathers()
  .configure(socketio(socket))
  .configure(hooks())
  .configure(authentication({storage}))

export default app
```

After (throws an error as the object is now the method that I can`t call without having the env to pass)
``` JS
import hooks from 'feathers-hooks'
import authentication from 'feathers-authentication-client'
import storage from '~helpers/ssr-storage'

export default function ({app, env}) {
  console.log(env)
  let endpoint = `http://${env.API_HOST}:${env.API_PORT}`
  console.log(endpoint)

  let api = feathers()
  api.configure(socketio(io(endpoint)))
  api.configure(hooks())
  api.configure(authentication({storage}))

  app.feathers = api

  return api
}
```

Has anyone an idea how to accomplish this?

**Comment by Atinux** [comment]
Hi @appinteractive 

If you define your env variable inside `env` of your `nuxt.config.js`, you can access them also on client-side with `process.env.MY_VAR`, it should fix your issue :)

**Comment by appinteractive** [comment]
Hey @Atinux, I was also thinking that this would be the case but it's always undefined on the client when asking the console inside the plugin.

**Comment by ImreC** [comment]
@appinteractive Is this issue resolved for you? because I am having exactly the same problem. Also with the feathers client.

**Comment by appinteractive** [comment]
@ImreC hey unfortunately I have to rebuild the whole app on production every time I deploy as the env vars which are different on Production has to be compiled in with nuxt. 

I still have to try out one of the different approaches that are flying around. One is named nuxt-env I think.

**Comment by InstanceOfMichael** [comment]
Can we have an official way to do this in the docs? I feel like the answers in the wild are all over the place.
