### ISSUE TITLE
Component state resets when doing router replace or router push

### ISSUE THREAD

**Issue by radonichn** [nuxt/nuxt.js#10139]
### Version
@nuxtjs: 2.15.8
node: 14.16.1

### Reproduction link
https://codesandbox.io/s/wispy-platform-6f0t7?file=/pages/test/_id.vue

### Steps to reproduce
Go to the page https://6f0t7.sse.codesandbox.io/test/2 and click the button. In console, you will see the watcher, which worked then the data property was updated.

Note, that I use route.name as a key, so that changing route params doesn't re-render the component.

### What is Expected?
The component's data doesn't change.

### What is actually happening?
The component's data resets to the default (init) state.

**Comment by trilogo-lordee** [comment]
Hi after some research I figured out that this behavior is related to asyncData and / or fetch. I assume that they are the ones who reset the data value, since by disabling the options:
```
features: {
           asyncData: false,
           sampling: false,
},
```
Achieve the desired behavior.

**Comment by radonichn** [comment]
@trilogo-lordee thanks, it helped but didn't solve the problem. Actually, I need those features for SSR

**Comment by trilogo-lordee** [comment]
@radonichn Good evening. To disable this behavior at the component level, you can use the options object in the component and pass asyncData: false there. Like this
```
    options: {
        asyncData: false,
    },
```

**Comment by radonichn** [comment]
@trilogo-lordee but I need asyncData in that component, that re-renders after router.push

**Comment by trilogo-lordee** [comment]
@radonichn Хорошо, я углубился в логику обновления данных и нашел возможную причину такого поведения. В проверке обновления компонентов есть свойство _dataRefresh и одна из логических проверок, она вызывает ее постоянно, это watchQuery! == false. Хотя в компонентах без этого параметра он находится в undefined состоянии.
Вы можете умешленно использовать watchQuery = false.

```
// Refresh component (call asyncData & fetch) when:
// Route path changed part includes current component
// Or route param changed part includes current component and watchParam is not `false`
// Or route query is changed and watchQuery returns `true`
if (this._routeChanged && childPathChanged) {
  Component._dataRefresh = true
} else if (this._paramChanged && childPathChanged) {
  const watchParam = Component.options.watchParam
  console.log(watchParam)
  Component._dataRefresh = watchParam !== false
} else if (this._queryChanged) {
  const watchQuery = Component.options.watchQuery
  if (watchQuery === true) {
    Component._dataRefresh = true
  } else if (Array.isArray(watchQuery)) {
    Component._dataRefresh = watchQuery.some(key => this._diffQuery[key])
  } else if (typeof watchQuery === 'function') {
    if (!instances) {
      instances = getMatchedComponentsInstances(to)
    }
    Component._dataRefresh = watchQuery.apply(instances[i], [to.query, from.query])
  }
}
if (!this._hadError && this._isMounted && !Component._dataRefresh) {
  return
}
```

**Comment by radonichn** [comment]
@trilogo-lordee спасибо, эта штука помогла, но вопрос к разработчикам - какого фига? ни слова в документации, ни слова на stackoverflow...

En: that thing helped, but why the hell somebody should explore source files to make a conclusion, that somewhere there's a property watchParam, so you can turn it off and everything will work fine

**Comment by Uzere** [comment]
I also had this issue recently.

This behaviour is unexpected, calling data() twice for the same component instance is something that vue never do. Combined with the fact that this behaviour (and watchParam) is completely undocumented, it leads to really bad developer experience.

I doubt that watchParam: true is a good default. Besides this introducing unexpected behaviour, it also can make component state inconsistent, especially if there are async operations in progress.

Also I don't see why watchParam and watchQuery have different defaults while query and path params may be used interchangeably
