### ISSUE TITLE
Nuxt build generates static site

### ISSUE THREAD

**Issue by DaDoBaag** [nuxt/nuxt.js#10135]
### Versions

- nuxt: 2.15.8
- node: 14.15.1

### Reproduction

https://github.com/DaDoBaag/nuxt-build-static

### Steps to reproduce

See instructions in the readme in the repo linked above

### What is Expected?

Nuxt builds a server application with client side rendering (`ssr: false, target: "server"`)

### What is actually happening?

Nuxt generates a static site with client side rendering

**Comment by treboryx** [comment]
After running `npm run build` and then `npm run start` the nuxt app will start in server mode.

I tested with server-middleware and it works fine
