### ISSUE TITLE
Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by azpery** [nuxt/nuxt.js#10144]
### Versions

- nuxt: 2.14.12
- node: 14.x (Vercel)

### Reproduction
I know it's hard but it's happening in production and randomly.. :( 

<details open>
<summary>Additional Details</summary>
<br>
<img width="483" alt="Capture d’écran 2021-12-16 à 09 21 08" src="https://user-images.githubusercontent.com/9019431/146334330-77490ef4-9f16-4f9d-9ec3-7089313813a5.png">

https://sentry.io/share/issue/fdc3b7ae0be6482ca496a9949f1aea1a/

We have the latest packages.
</details>

### Steps to reproduce
Navigate through the website

### What is actually happening?
We have an anomaly hard to track because it happens randomly. But we have them a lot ! 

The error is : Cannot read property 'fetch' of undefined coming from .nuxt/mixins/fetch.client.js when trying to hydrate the component. 
nuxtState is not test and then can actually be undefined. What do you think?

**Comment by pregno** [comment]
Hi @azpery , have you found any solution about this issue?

**Comment by azpery** [comment]
@pregno , actually not really but I found that using some v-ifs in my app was generating this issue. 

On my index.vue, I used to have v-ifs in some places. If, the variables linked to these v-if are set to true before the dom is loaded, then it generates an error. 

Conclusion : 
Make sure to wait for the dom to be loaded before setting your variables. Or replace your v-if with v-show

**Comment by azpery** [comment]
Hello @pregno,
I keep having these errors spaming my sentry. It is very annoying. But maybe I found the solution. 

Maybe the use of the created hook + v-if (and thus dom manipulation) make these errors occur. 

I am going to test what happens if I switch created hooks to mounted hooks. 

Tell me if you also use created hooks
