### ISSUE TITLE
Images are not showing after nuxt generate

### ISSUE THREAD

**Issue by SupriyaGo** [nuxt/nuxt.js#10142]
After nuxt generate as target: 'static', images are not showing when we run the dist build by npm run start.
though in dev mode images are showing correctly.
I have used image URLs as src of img.
when we inspect on the browser, its showing links are there but not rendering on the page.

### Versions

- nuxt: "^2.15.7"
- node: v14.17.4

### What is Expected?
Images should work after generate.

**Comment by danielroe** [comment]
Would you provide a reproduction?

**Comment by Minori-ty** [comment]
the same problem,  it was not in .output after bundle when use the single img tag。But it was in the .output when use the style template，and cite the img path，like these
```
<style  scoped>
    div{
        background-image: url('./assets/1.jpg')
    }
</style>
```
