### ISSUE TITLE
Having to click the back button twice

### ISSUE THREAD

**Issue by adamchipperfield** [nuxt/nuxt.js#10141]
When trying to navigate using the back button I have to click it again to trigger Nuxt.js to navigate back. It looks like the browser detects the back click, since the forward button then becomes active. So it's as if the router isn't detecting the first click.

Interestingly, **this only happens when navigating to a page which uses `asyncData`**. On inspection, there is no console or network activity on the first click (so I know this isn't me being impatient + no loading bar).

### Versions

- nuxt: v2.13.1
- node: v14.18.2

**Comment by adamchipperfield** [comment]
Upgraded to 2.15.8 and the issue persists...

**Comment by adamchipperfield** [comment]
Turns out there was a plugin broken which injected two history entries.

**Comment by agosman** [comment]
Hi @adamchipperfield, I'm experiencing the exact same problem, however only in production build, not in dev. Just curious what plugin it was that caused it for you, or was it a custom plugin?

**Comment by versionmj** [comment]
Hey @adamchipperfield.  Same issue here.  What was the plugin you were using?

**Comment by danielroe** [comment]
No, it has not. But feel free to provide a reproduction and I'll examine.

**Comment by versionmj** [comment]
@danielroe I was under the impression that "pending triage" meant that it was in line to be examined.  Is that incorrect?

**Comment by danielroe** [comment]
Indeed. But this issue is closed as the original issue reporter identified that it was not a bug but an error in their own code.

**Comment by versionmj** [comment]
@danielroe Thanks for your reply.  FYI, I have now also found that the issue was caused by an error in my code.
