### ISSUE TITLE
hooks for external libraries 

### ISSUE THREAD

**Issue by chuckyo** [nuxt/nuxt.js#1015]
Hi I am using *v1.0.0-alpha.4*

Let's say we can use below syntax to implement an external library
```javascript
head: {
  script: [
    { src: '/example.js' } // this file is in static
  ]
}
```
I wanna use this library in special page, for instance in `About Page`, so I can put this snippet in `layouts/about.vue` or `page/about.vue` (actually both had been tried)

The scenario is:
1. If I enter the `About Page` directly through *http://domain/about*, all works well
2. If I enter the `About Page` from `Index Page` through `<nuxt-link to="/about">`, I can not use the exposed function from `example.js`, because the js file didn't download yet when `mounted` was invoked, I also tried `window.onload` which the function inside won't be invoked.

*So is there a hook existent which will be invoked after external libraries finish download?*

**Comment by pi0** [comment]
@chuckyo such libraries usually should trigger an event after initialization (and also document that!). So you can listen for that event on `mounted()` hook of pages and doing additional things after that. It also keeps SSR hydration safe :)

PS: If need additional help please add a link to external lib that you want.
PSS: zxcvbn library has a nice example how to add async hooks. See [here](https://github.com/dropbox/zxcvbn#script-load-latency)

**Comment by chuckyo** [comment]
Hi @pi0 I am using [swfobject.js](https://github.com/swfobject/swfobject/blob/2.2/swfobject/src/swfobject.js) as the external lib, currently I am using a dull way to implement my requirement
``` javascript
mounted() {
  const detectSwfobject = window.setInterval(function() {
    if (typeof swfobject !== undefined) {
      window.clearInterval(detectSwfobject)
      // ...
    }
  }, 200)
}
```
And I think the `window.onload` listener won't be fired if enter the page from *front-end route*, so I don't know how to optimize this.

**Comment by pi0** [comment]
What about `window.ready` or this?
```js
const async_load = () => {
 // ...
}

if (window.attachEvent != null) {
    this. detectSwfobject  = window.attachEvent('onload', async_load);
  } else {
    this. detectSwfobject  = window.addEventListener('load', async_load, false);
  }
```
