### ISSUE TITLE
vue/multi-word-component-names eslint rule and layouts

### ISSUE THREAD

**Issue by louislebrault** [nuxt/nuxt.js#10153]
Nuxt version: 2.15.8

The [official VueJS documentation refer a new eslint rules as essential](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential), [vue/multi-word-component-names](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/multi-word-component-names.md).

This does not fit well with how layout names are auto-registered by nuxt.

To satisfy this rule, i need to rename my single-word named layouts with a multi-word name, so i'll define a new name in the "name" field of the object i default export from my SFC. But using the names i specify that way to refer to layouts in my other components does not work !

If i rename a layout called `something.vue` to `name: 'SomethingLayout`, i still need to write `layout: 'something'` in my pages, `layout: 'SomethingLayout'` won't work.

This is pretty misleading imo.

A solution could be the possibility to refer a layout with either its component name, or its filename i guess.

I know the eslint rule can be disabled, but its refered as an "essential" rule in vuejs documentation, the highest priority...
I could also directly use multi-words in the filename, but it still does not work with the default layout that we are enforced to name "default.vue".

**Comment by ocitydev** [comment]
I just came across the issue right now.

**Comment by Jursdotme** [comment]
This is forcing the user to work around basic functionality. Nuxt does not work as intended with this rule activated.

**Comment by kylemilloy** [comment]
Work around for now to avoid CI issues:

```js
// in your eslint config file
{
  root: true,
  env: {}
  // ...
  rules: {
    // ...
    'vue/multi-word-component-names': 'off',
  },
}
```

**Comment by halkeye** [comment]
Instead of disabling it entirely, I recommend doing an override for the default layout
```
diff --git a/.eslintrc.js b/.eslintrc.js
index 9e383e1..a7bae31 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -15,5 +15,13 @@ module.exports = {
   plugins: [
   ],
   // add your custom rules here
-  rules: {}
+  rules: {},
+  overrides: [
+    {
+      files: ['layouts/default.vue'],
+      rules: {
+        'vue/multi-word-component-names': 'off'
+      }
+    }
+  ]
 }
```

**Comment by ErickPetru** [comment]
Just to add to the useful idea from @halkeye, it's also possible to specify wildcards for the `files` key:

```
{
  // ...
  overrides: [
    {
      files: ['layouts/*.vue', 'pages/**/*.vue'],
      rules: { 'vue/multi-word-component-names': 'off' }
    }
  ]
}
```

Useful if you want to name Nuxt page components as single words.

**Comment by danielroe** [comment]
Yes, the above is the right solution for this issue.

If you're using `@nuxt/eslint-config`, this should be automatically configured for you in the next release of https://github.com/nuxt/eslint-config (cc: @clarkdo)

**Comment by Ali-Rooholamini** [comment]
I did all these routes. And a whole other solution. But neither of them answered.
im using Nuxt project wit npx create-nuxt-app.
i did just like vue mastery  ( scaling-vue-with-nuxt-js ) course.
Can you help ??
