### ISSUE TITLE
How to save some information after reloading the page?

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#1016]
I'm trying to figure out how to save some data after the page reloads. Usually I used localStorage. But here it does not fit. And the architecture of the application does not allow you to write and select data from the Database.

**Comment by alexchopin** [comment]
Hi @cawa-93, have you tried to use a cookie and parse it in `nuxtServerInit`?

**Comment by vuchl** [comment]
@cawa-93 Can you explain why localStorage is not fitting your scenario? Other then that I'm on the same page with @alexchopin and wouldadvice to use a cookie. Everyone loves cookies,

**Comment by pi0** [comment]
@vuchl That's because of SSR process. We need someway sending state to server rendering exact results as client side :)
