### ISSUE TITLE
nuxt watch $route not working when change to other page with other layout

### ISSUE THREAD

**Issue by wellitongervickas** [nuxt/nuxt.js#10186]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
using nuxt-link, redirect to a new page that using other layout, we cannot trigger the event
```
watch: {
	 '$route'() {
	          this.close();
          },
},
```

### What is actually happening?
When clicking on some link that redirects to a new page with another layout, watch method with $router doesn't work.

**Comment by wellitongervickas** [comment]
I've using destroy as a workaround but isn't a prettier solution
`
destroyed() {
			this.$store.commit('mobileMenu/setVisibility', false);
		},
`

**Comment by Kolobok12309** [comment]
In current `vue-router` same behaviour, `$route` changed after `router-view` child destroyed
[CodeSandbox](https://codesandbox.io/s/clever-varahamihira-hkyem?file=/src/views/index/index.vue)

**Comment by paddotk** [comment]
Since `$route` is an object, I don't think this can be expected to work. You might try adding the `deep` property to 'deep' check the contents of the object:

```javascript
watch: {
   '$route' {
        handler: function() {
            this.close();
        },
        deep: true
    },
},
```
