### ISSUE TITLE
Inconsistent router.push behaviour

### ISSUE THREAD

**Issue by mathieumagalhaes** [nuxt/nuxt.js#10183]
### Versions
nuxt: Any version after 20 Dec 2020 

### Steps to reproduce
Use router.push(...).catch() anywhere in project.

### What is Expected?
Router push, without explicit callbacks provided in arguments should return a promise.

### What is actually happening?
We can't use promise handlers (.catch(), .then(), ...) on router.push.

Due to the Nuxt overwrite of router.push a "emptyFn" (empty function) will be passed as callback
Even if no original callbacks are provided by the user.
This makes Vue router never return a promise.
(Vue router checks if callback(s) are provided, if no callbacks are provided it returns a promise)

#### Exact code that is causing the issue (currently still on master):
https://github.com/nuxt/nuxt.js/blob/457984a56740962d6cbf0b07903f065732d03ef9/packages/vue-app/template/router.js#L108-L112

#### Added in this commit:
https://github.com/nuxt/nuxt.js/commit/8c8793073f73b1d54cc904bb0bcce23c179cb8d3

**Comment by danielroe** [comment]
This is a deliberate backward compatibility that will be removed in Nuxt 3. See https://github.com/nuxt/nuxt.js/issues/6951#issuecomment-729266427, for example - and https://github.com/nuxt/nuxt.js/issues/6951#issuecomment-904655674 for a workaround.
