### ISSUE TITLE
Clean nuxt install trows error in IE 11

### ISSUE THREAD

**Issue by dennisadriaans** [nuxt/nuxt.js#10188]
If i create a new project via NPM the entire page pauses in IE 11.

`Syntax error File: app.js, Line: 187, Column: 107`
`__webpack_require__(/*! ./decode */ \"./node_modules/querystring-es3/decode.js\"`

### Versions

- nuxt:  2.15.8
- node: v14.17.0

### Reproduction

1. Clean nuxt install via (npm init nuxt-app)
2. Open inspector and see debugger.

**Comment by gongjianh** [comment]
I also encountered this problem

**Comment by danielroe** [comment]
If you encounter this issue, you may need to add the module that is throwing the error to your `build.transpile` array. (The issue is that libraries used in Nuxt are gradually dropping support for IE11.)

**Comment by gongjianh** [comment]
No effect

**Comment by danielroe** [comment]
Then you will likely need to find what library is depending on _that_ library, and so forth.
