### ISSUE TITLE
how to use postcss-px2rem?

### ISSUE THREAD

**Issue by zhoufanglu** [nuxt/nuxt.js#10194]
### Versions

    "nuxt": "^2.15.8",
    "postcss-px2rem": "^0.3.0",

### Steps to reproduce

in `nuxt.config.js` 
```js
  build: {
    transpile: [/^element-ui/],
    postcss: [
      require("postcss-px2rem")({
        remUnit: 75
      })
    ]
  },
```

### What is actually happening?
error!
![image](https://user-images.githubusercontent.com/24451091/148520937-786b55c2-545e-4c63-a197-323f00a26473.png)

**Comment by zhoufanglu** [comment]
> 请问您解决了嘛
解决了，用的   `postcss-px2rem-exclude": "^0.0.6`,

```js
 postcss: {
      plugins: {
        "postcss-px2rem-exclude": {
          remUnit: 16, // 设计图为750 * height
          remPrecision: 2, // rem的小数点后位数
          selectorBlackList: [],
          exclude: /node_modules|folder_name/i //
        }
      }
    } 
```

**Comment by gonghaichao** [comment]
不能使用postcss-px2rem蛮

**Comment by zhoufanglu** [comment]
> 不能使用postcss-px2rem蛮

是的 不行 最后使用了这个，效果一样的
