### ISSUE TITLE
PM2 zero downtime deployment

### ISSUE THREAD

**Issue by treboryx** [nuxt/nuxt.js#10195]
### Is your feature request related to a problem? Please describe.

It's a deployment issue that I face often and would like to ask if anyone has a solid solution

### Describe the solution you'd like

A wise fellow developer that has thoroughly looked into it and has found a good solution

### Describe alternatives you've considered

PM2 Cluster Mode as recommended on the docs. The documentation says cluster mode will prevent downtime, but that's not the case.

### Additional context

Whenever I `npm run build` my app goes offline until the build is ready. I would like to prevent this, if possible.

**Comment by Kolobok12309** [comment]
We use different folders for builds and runtime for example, additionally it provides a convenient option to switch versions of app(if you have multiple folders for runtime and change it through symlink)

**Comment by treboryx** [comment]
> We use different folders for builds and runtime for example, additionally it provides a convenient option to switch versions of app(if you have multiple folders for runtime and change it through symlink)

Do you have this automated with a custom script or do you use another solution?

**Comment by Kolobok12309** [comment]
@treboryx several ansible scripts, but our builder and runtime on different servers. In short after build we use script like this.
I apologize in advance for the incorrect use of variables in bash, but I think the essence is clear.
```
RELEASE_DIR="{{ dest_path }}/{{ version }}_{{ '%y%m%d_%H%M' | strftime }}"
mkdir RELEASE_DIR
unzip build.zip -d RELEASE_DIR
ln -sfn RELEASE_DIR "{{dest_path}}/current"
pm2 startOrReload pm2.config.js
```

**Comment by treboryx** [comment]
Thanks!

Wrote my own script and it seems to work flawlessly!
