### ISSUE TITLE
PostCSS Preset Env not being loaded by default

### ISSUE THREAD

**Issue by gavmck** [nuxt/nuxt.js#10206]
### Versions

- nuxt: 2.15.8
- node: 16.8.0

### What's happening?

Nuxt doesn't not appear to be loading postcss-preset-env by default.

In the docs, it says [Nuxt has applied PostCSS Preset Env . By default it enables Stage 2 features and Autoprefixer , you can use build.postcss.preset to configure it.](https://nuxtjs.org/docs/configuration-glossary/configuration-build/#postcss)

When I run `nuxt webpack module rules --depth=9` I get this postcss config:

```javascript
{
            loader: '..some-path-here/node_modules/postcss-loader/dist/cjs.js',
            options: {
              sourceMap: false,
              execute: undefined,
              postcssOptions: {
                plugins: [
                  [Function (anonymous)] {
                    postcssPlugin: 'postcss-import',
                    postcssVersion: '7.0.39'
                  },
                  [Function (anonymous)] {
                    postcssPlugin: 'postcss-url',
                    postcssVersion: '7.0.39'
                  },
                  [Function (anonymous)] {
                    postcssPlugin: 'cssnano',
                    postcssVersion: '7.0.39'
                  }
                ]
              }
            }
          },
```

Manually adding what is described as the default in the docs to my build property in `nuxt.config.js` makes it work correctly.

```javascript
postcss: {
        plugins: {
          'postcss-preset-env': {
            autoprefixer: {},
          },
        },
        order: 'presetEnvAndCssnanoLast',
      },
```

**Comment by patrickcate** [comment]
I ran into this exact same problem with the same Nuxt and Node versions as @gavmck

@gavmck's `nuxt.config.js` fix worked as well.
