### ISSUE TITLE
Create component programmaticaly with Nuxt context

### ISSUE THREAD

**Issue by amkatyshev** [nuxt/nuxt.js#10205]
### Versions

- nuxt: 2.15.8
- node: 14.17.5

### Reproduction

There is a need to create a component programmatically using similar code (for example, some mixin is used in page component, where `formatterComponent` method is called).

`mixin.js`
```
import Vue from 'vue';

export default {
  methods: {
    formatterComponent(component, propsData) {
      const VueComponent = Vue.extend(component);
      const VueComponentInstance = new VueComponent({ propsData });
      VueComponentInstance.$mount();
      return VueComponentInstance.$el;
    }
  }
}
```

But the problem is that there is no access to global variables inside the component. For example, with the `nuxt-auth` module installed, the call to `this.$auth` produces undefined.
Is it possible to correctly create and mount a component in Nuxt with all global dependencies and modules?

**Comment by gtnsimon** [comment]
Hi,

I encounter the same issue using this approach. I need to instantiate a component containing some computed properties which uses Nuxt Context injected props but all are undefined.

I've set up a repro here: https://github.com/gtnsimon/codesandbox-nuxt/tree/bug/dynamic-component-context

- Clone the repo
- Install packages using `yarn`
- Checkout to branch `bug/dynamic-component-context`
- Run Nuxt using `yarn run dev`
