### ISSUE TITLE
How to render new added page without removing previous rendered ones

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#1020]
I have over 3000 post, i'm rendering all of them - it took like a 20 mins. After this i'm adding new post to my db and i need to render this one page to join it to just rendered files/posts. How to do this without removing already created data? I wish to use some process env like: `GENERATE_POST` so my generate block will looks like this:

```
generate: {
  routes: function () {
    if (process.env.GENERATE_POST) {
      // generating only one post
      return ['/feed/' + process.env.GENERATE_POST]
    } else {
      // generating all data in promise loop
    }
  }
},
```

Thx for help.

**Comment by alexchopin** [comment]
Actually, this is difficult to imagine because we need to build again the application due to bundles generated by webpack for the Vue.js app.
But, I will try to find a way, any contribution is welcome!

**Comment by lukasborawski** [comment]
@alexchopin where is code that corresponds with that?

**Comment by alexchopin** [comment]
[/lib/builder/generator.js](https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/generator.js)

**Comment by pi0** [comment]
Another idea is creating a simple bash script. Warn that you may potentially give client side js errors as manifest for each build is unique :) Also script is just to get idea will certainly not working with just copy-paste :D

```sh
// Usage ./generate_post.sh [post_id]

export GENERATE_POST=$1
export TARGET="feed/$GENERATE_POST/index.html"

cp -r dist public

npm run generate // Will generate only new page to dist

cp dist/$TARGET public/$TARGET

// Now public contains updated version :)
```

**Comment by pi0** [comment]
Opps also forgot to mention with next releases it is easier programmatically control generate behaviour to prevent build process for patchs resulting fully working js too :)

**Comment by lukasborawski** [comment]
@pi0 and when will be new release? you've said before that it will be sunday :) just asking

**Comment by lukasborawski** [comment]
@pi0 actually your solution works quite nice, but there was an error with copy cmd:

```
export GENERATE_POST=$1
export TARGET_DIR="feed/$GENERATE_POST"
export TARGET="feed/$GENERATE_POST/index.html"

npm run generate_post

mkdir public/$TARGET_DIR
cp dist/$TARGET public/$TARGET
rm -rf dist
```

**Comment by alexchopin** [comment]
Should be fixed with the new release
