### ISSUE TITLE
Wrong sub-path with nested NuxtChild and keep-alive

### ISSUE THREAD

**Issue by GMartigny** [nuxt/nuxt.js#10214]
### Versions

- nuxt: 2.15.8
- node: 16+

### Reproduction

 - [Code](https://codesandbox.io/s/nested-nuxtchild-h23bq)
 - [Live](https://h23bq.sse.codesandbox.io/)

In the live demo, navigate to "Account" then "Edit". Once on the form, use the navigation to go to "Index" and come back to "Account".

The app will still display the form, however the URL is  `profile/account` as expected. If you then do another trip back and forth, the page correctly display the informations (and not the form).

### Steps to reproduce

By having a sub-navigation with nested `<NuxtChild>` and using `keep-alive` prop in the layout, the sub-pages are not correctly displayed.

 - Have a layout with `keep-alive` on the `Nuxt` component
 - Have 3 pages, A, B/1 and B/2
 - Navigate A -> B/1 -> B/2 -> A -> B/1
 - The page display B/2 instead of B/1 while the URL is rightfully B/1

Bonus:
 - While on the bug
 - Navigate -> A -> B/1
 - The page correctly display B/1 as expected

### What is Expected?

The wrong content is displayed.

### What is actually happening?

URL and content should always be in sync.

**Comment by darksc** [comment]
This is a serious serious serious serious serious serious serious bug

**Comment by darksc** [comment]
@danielroe
