### ISSUE TITLE
Transitions between routes with slugs

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#1021]
It appears when I transition from 1 slug to another the page content reloads but there is no option that I can see to make it transition as any other route change would.

There was an issue here on vue-router which has the old and new solution. It seems it'd be good to have a configurable `key` for the router-vue component.
https://github.com/vuejs/vue-router/issues/474

Maybe this could be done within layout components and we could add the key attribute optionally to the `nuxt` component? Maybe even a quick config option in the nuxt config to set whether transitions should always be applied? I think the attribute way would be good enough though. That way the transition application can be conditional.

**Comment by Atinux** [comment]
Closing it since `rc3` is out

**Comment by iamdubx** [comment]
How to use it? I have issues with transitions when navigate to dynamic `_section` from other dynamic route. Any chance to fix it? I tried key `:key="$route.params.section"` but it doesn't work. Also tried to set `modes`
