### ISSUE TITLE
Does this project have malicious code?

### ISSUE THREAD

**Issue by donghoon-song** [nuxt/nuxt.js#10222]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
git clone nuxt.js
open the project in IDE

### What is actually happening?
![image](https://user-images.githubusercontent.com/32301380/150309223-0ff6a6aa-5e67-47f7-b007-a117b48c34fa.png)

**Comment by danielroe** [comment]
I suspect that is a normal popup for any folder opened in WebStorm. You should always audit project dependencies and make sure you're following https://github.com/nuxt/nuxt.js/issues/9284.
