### ISSUE TITLE
asyncData fails to return component data with multiple return statements

### ISSUE THREAD

**Issue by chrislentz** [nuxt/nuxt.js#10228]
### Versions

- nuxt: v2.15.8
- node: v16.13.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
When you need to make multiple API requests via a set of conditionals and return data through multiple return statements, `asyncData` fails to merge the returned object to the component data when executed server-side. In the example below, I am making a series of API requests based on different combinations of query parameters. I can confirm that the API requests are made successfully, but all of the returned data is "undefined" on the component data side.

I replaced all of my API calls with test API calls to make it easy to reproduce the issue.
</details>

### Steps to reproduce
Add this `asyncData` and `data` block to any page and render it server side.

```
async asyncData({ $axios, route }) {
  if (route.query.query) {
    if (route.query.tab === 'companies') {
      // API Call "Search companies"
      const response = await $axios.$get('https://jsonplaceholder.typicode.com/todos/')

      return {
        company: null,
        tab: 'companies',
        query: route.query.query,
        companyResults: response.data,
      }
    } else if (route.query.company) {
      // API Call "Read a company" and "Search requests"
      const [companyResponse, requestsResponse] = await Promise.all([$axios.$get('https://jsonplaceholder.typicode.com/todos/1'), $axios.$get('https://jsonplaceholder.typicode.com/todos/')])

      return {
        company: companyResponse.data,
        tab: 'requests',
        query: route.query.query,
        requestResults: requestsResponse.data,
      }
    } else {
      // API Call "Search requests"
      const response = await $axios.$get('https://jsonplaceholder.typicode.com/todos/')

      return {
        company: null,
        tab: 'requests',
        query: route.query.query,
        requestResults: response.data,
      }
    }
  }
},
data() {
  return {
    query: '',
    tab: 'requests',
    company: null,
    requestResults: [],
    companyResults: [],
  }
},
```

### What is Expected?
I can confirm the API call's are made successfully. I would expect with in the component data `query`, `tab`, `company`, and `requestResults` or `companyResults` should be set based on the query parameters passed. `company`, `requestResults`, and `companyResults` should be set to the API response.

### What is actually happening?
All data on the component side is "undefined".

**Comment by danielroe** [comment]
When you use `$get` Nuxt axios [automatically returns the data rather than an object with a data property](https://axios.nuxtjs.org/usage#-shortcuts).

Try this:

```diff
        return {
          company: null,
          tab: "companies",
          query: route.query.query,
+          companyResults: response,
-          companyResults: response.data,
        };
```
