### ISSUE TITLE
Usage in forks

### ISSUE THREAD

**Issue by dts** [nuxt/nuxt.js#1023]
In trying to get nuxt to work with my use case (which requires CORS asset hosting), I forked Nuxt, and referenced my fork in my package.json.  Unfortunately, this doesn't work because I have to build the `dist/` directory.  This isn't the end of the world (I just cd node_modules/nuxt && npm install && npm run build), but it would make wrenching on this library more easeful to just be able to point it at different forks.

**Comment by pi0** [comment]
**For local:** you can use [npm link](https://docs.npmjs.com/cli/link) or [yarn link](https://yarnpkg.com/lang/en/docs/cli/link/) which is designed for exactly this use cases.
**For production:** If really in hurry for prodction just publish under a different package name, build triggers automatically.

After all nothing is wrong with nuxt it should be compiled anyway :D Also such forks are hard to maitnance and somehow against opensource goodness. If that feature is useful for others, just generalize it in a new branch and Open PR we SHOULD accept it when possible, we and other people would also see that PR helping to finish it sooner :)

**Comment by pi0** [comment]
> which requires CORS asset hosting

Would you please explain more about this problem? Or reference if there is already any open issue.

**Comment by dts** [comment]
https://github.com/nuxt/nuxt.js/pull/1025 is my fork 😄 .  Y'all are totally on-top of your game, and I agree on all fronts.  `yarn link` is just kind of annoying to use with my current development environment for reasons that are probably not a big deal.

**Comment by pi0** [comment]
Maybe [NODE_PRESERVE_SYMLINKS=1](https://nodejs.org/api/cli.html#cli_preserve_symlinks) would be your friend when using `yarn link` :)

**Comment by dts** [comment]
Perhaps.  I responded in https://github.com/nuxt/nuxt.js/pull/1025 as well, but basically I am proxying TO nuxt, not with nuxt.  I'd be happy to walk you through my use case, but basically I want to use `nuxt generate` to pre-render a bunch of web pages that I'm using inside of a cordova-like container.
