### ISSUE TITLE
Please check possible console errors and ensure dist folder exists

### ISSUE THREAD

**Issue by adebayo-moses** [nuxt/nuxt.js#10234]
### Environment

pnpm dev

### Reproduction

https://github.com/adebayo-moses/Adebayo-Moses/tree/new

### Describe the bug

Whenever i run npm run dev on my development server , it throws this error

**Please check possible console errors and ensure dist (C:projectdirectoryretracted\.nuxt\dist\server) exists.**
but if i build the application using a static hosting plan like vercel or netlify, it builds properly.

### Logs

```shell
Error
Renderer resources are not loaded! Please check possible console errors and ensure dist (C:\Users\retracted\Desktop\web-apps\retracted\.nuxt\dist\server) exists.
```

**Comment by treboryx** [comment]
Hi! The link takes you to a 404

Did you figure this out?
