### ISSUE TITLE
Using jquery-ui with nuxt:  ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by navmed** [nuxt/nuxt.js#1026]
I have this in my nuxt.config.js:

```
  build: {
    plugins: [
      new webpack.ProvidePlugin ({
        '$': 'jquery',
	'jQuery': 'jquery',
        '_': 'lodash'
      }),
    ],
    vendor: [
      'jquery',
	  'jquery-ui',
...
```

But, I still get this error:
```
[vue-router] Failed to resolve async component default: ReferenceError: jQuery is not defined
[vue-router] uncaught error during route navigation:
ReferenceError: jQuery is not defined
    at $.widget.version (S:\Projects\fomatics\node_modules\jquery-ui\ui\widgets\draggable.js:35:12)
    at Object.<anonymous> (S:\Projects\fomatics\node_modules\jquery-ui\ui\widgets\draggable.js:37:2)
```

What am I doing wrong?

**Comment by vuchl** [comment]
The error is coming from here: https://github.com/jquery/jquery-ui/blob/master/ui/widgets/draggable.js#L35

so for some reason the jQuery object is not correctly bound to the library. could you try to also bind the jQuery object like so: https://webpack.js.org/plugins/provide-plugin/#usage-jquery-with-angular-1 or without the single quotes for the identifiers?

**Comment by galvez** [comment]
@vuchl What's happening is, the `jQuery` alias will only be created after all files have been imported... you need to include both jQuery and jQuery UI as `plugins`/`css` in `nuxt.config.js`, this way they'll be made available before everything else.
