### ISSUE TITLE
CSS File from library (node_modules) is not imported in production mode

### ISSUE THREAD

**Issue by Fabioni** [nuxt/nuxt.js#10261]
### Versions

- nuxt: v2.15.8
- node: v16.13.2

### Reproduction

clean project
```
yarn create nuxt-app testapp

create-nuxt-app v4.0.0
✨  Generating Nuxt.js project in testapp
? Project name: testapp
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: None
? Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert se
lection)
? Linting tools: (Press <space> to select, <a> to toggle all, <i> to invert sele
ction)
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Static (Static/Jamstack hosting)
? Development tools: (Press <space> to select, <a> to toggle all, <i> to invert 
selection)
? What is your GitHub username? xxx
? Version control system: Git
```

now following this https://github.com/FortAwesome/vue-fontawesome/tree/2.x#nuxtjs
the important part is installing a module with `yarn add @fortawesome/fontawesome-svg-core` and putting `css: [
  '@fortawesome/fontawesome-svg-core/styles.css'
]` in the `nuxt.config.js`.

### What is Expected?

I expect to have  the content of '@fortawesome/fontawesome-svg-core/styles.css' on each page available.

### What is actually happening?

When I run `yarn dev` I have the content of  '@fortawesome/fontawesome-svg-core/styles.css' in my page.

When I run `yarn generate` and `yarn start` **I do not have it**.

### What I tried

When I just copy the content of  '@fortawesome/fontawesome-svg-core/styles.css' in a main.css file in my root and then put `css: [
  'main.css'
]` in the `nuxt.config.js`, it works in dev and production. So I think the problem lies in nuxt when using css files from a module.

Note, that purgecss is not installed.

Maybe this helps: when I print the result of `relativeToBuild(resolvePath(c.src || c, { isStyle: true }))` in

https://github.com/nuxt/nuxt.js/blob/777a4b7f5033c86c37cbd93008f3ca792e4af8bc/packages/vue-app/template/App.js#L19-L21

I get in production mode:
```
../../@fortawesome/fontawesome-svg-core/styles.css
../../../main.css  
```

and in dev mode:
```
../node_modules/@fortawesome/fontawesome-svg-core/styles.css
../main.css   
```

Thanks for your help :-)

**Comment by zoomoid** [comment]
I'm currently experiencing a similar issue with fontawesome in combination with tailwindcss 3. After upgrading tailwind to 3.0.0, the styles for `.svg-inline--fa` are no longer loaded properly on the page. Note however that the stylesheets exist in the bundled code, they are just not applied in the document.

I'm currently mitigating the issue by using CSS @import(...) in the project's main.css file, which oddly seems to work, but this causes styles to lack on the first page load, rendering all icons at maximum size.

**Comment by Fabioni** [comment]
> I'm currently experiencing a similar issue with fontawesome in combination with tailwindcss 3. After upgrading tailwind to 3.0.0, the styles for `.svg-inline--fa` are no longer loaded properly on the page. Note however that the stylesheets exist in the bundled code, they are just not applied in the document.
> 
> I'm currently mitigating the issue by using CSS @import(...) in the project's main.css file, which oddly seems to work, but this causes styles to lack on the first page load, rendering all icons at maximum size.

Hey, what I did as a workaround is just duplicate the font awesome style file in my custom assets stylesheet folder and included this in nuxt.config.js css section. This works and the problem with the first page load does not occur since the css is already sent with the page. Not really nice, but it works than using CSS @import.

**Comment by MackYoel** [comment]
I have the same problem with font-awesome in combination with tailwindcss 3

**Comment by FalkoJoseph** [comment]
Same issue here.

**Comment by FalkoJoseph** [comment]
> > I'm currently experiencing a similar issue with fontawesome in combination with tailwindcss 3. After upgrading tailwind to 3.0.0, the styles for `.svg-inline--fa` are no longer loaded properly on the page. Note however that the stylesheets exist in the bundled code, they are just not applied in the document.
> > I'm currently mitigating the issue by using CSS @import(...) in the project's main.css file, which oddly seems to work, but this causes styles to lack on the first page load, rendering all icons at maximum size.
> 
> Hey, what I did as a workaround is just duplicate the font awesome style file in my custom assets stylesheet folder and included this in nuxt.config.js css section. This works and the problem with the first page load does not occur since the css is already sent with the page. Not really nice, but it works than using CSS @ import. (haha poor @ import guy...)

Same issue here with WindiCSS.

The above suggestion worked for me! 👍

**Comment by zoomoid** [comment]
Likely related to this: https://github.com/FortAwesome/Font-Awesome/pull/18654

**Comment by sh00076227** [comment]
I faced the same problem.
CSS cannot be imported inside the <script> tag.

・module uses markdown-it-vue.

ERROR
SyntaxError: Unexpected token

somebody help...

**Comment by sh00076227** [comment]
I solved it by reinstalling the module.

**Comment by zoomoid** [comment]
This can be closed, fontawesome fixed their package as having side effects to prevent webpack from tree-shaking the styles out of the bundles in v6.1.0.

**Comment by Fabioni** [comment]
> This can be closed, fontawesome fixed their package as having side effects to prevent webpack from tree-shaking the styles out of the bundles in v6.1.0.

I can verify that it works now.

*Important*:
Don't use @nuxtjs/fontawesome, which requires fontawesome v5, but directly @fortawesome/vue-fontawesome, so you can use v6.1.0 where the problem is apparently fixed.

Thanks @zoomoid for the hint :-)
