### ISSUE TITLE
router.base in publicRuntimeConfig not working

### ISSUE THREAD

**Issue by wensaint** [nuxt/nuxt.js#10276]
### Versions

- nuxt: 2.15.8
- node: 14.16.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
when i set router.base in publicRuntimeConfig, it is baked in the build files. and i can't change it after build.
</details>

### Steps to reproduce
``` 
nuxt.config.js: 
export default {
  /*
   ** Nuxt rendering mode
   ** See https://nuxtjs.org/api/configuration-mode
   */
  ssr: false,
  router: {
    middleware: ['auth']
  },
  publicRuntimeConfig: {
    router: {
      base: process.env.PUBLIC_PATH || '/'
    },
    build: {
      publicPath: process.env.PUBLIC_PATH || '' + '/_nuxt/'
    }
  },
  ...
}
```

### What is Expected?
after build. if i set env.PUBLIC_PATH='/test', then i will access http://localhost:3000/test normally just like i set router.base='/test' without publicRuntimeConfig.  the final goal is "**one build, muti deployment**".

### What is actually happening?
if i visit http://localhost:3000, everything is ok. when visit http://localhost:3000/test, the page throw 404 error.
![image](https://user-images.githubusercontent.com/13247455/153977904-b71499eb-741f-4df2-bdef-ad9cc7d23a9a.png)

**Comment by YutaMoriJP** [comment]
Hi there, have you found a solution to this?
