### ISSUE TITLE
Nuxt console.log errors. Link to my source files ??

### ISSUE THREAD

**Issue by infinity899** [nuxt/nuxt.js#10278]
### Is your feature request related to a problem? Please describe.

How can I easily debug? Whenever I have an error in the code, I get this errors in console.log but clicking any of these files will send me to NUXT code. How can I go to my source file and the line of code where it breaks?

### Describe the solution you'd like
Clicking the link to file from console.log to get me to the place where the code breaks.

### Additional context

Nuxt 2.15
ssr disabled

![image](https://user-images.githubusercontent.com/27764573/154060239-8abc10d2-04af-46e6-bed3-1ad6bb8c45db.png)

**Comment by kitroling** [comment]
You can learn about [webpack devtool](https://webpack.js.org/configuration/devtool/)
There's an example [here](https://nuxtjs.org/docs/configuration-glossary/configuration-build/#extend)

**Comment by kitroling** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
