### ISSUE TITLE
pwa not work

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#1027]
I follow the guide to change my app to pwa, but it seems not work

`nuxt.config.js `  source code is https://github.com/awesomes-cn/news/blob/master/nuxt.config.js

 URL: https://news.awesomes.cn/

**Comment by bimohxh** [comment]
It seems that I put the css and js files on cdn which host is `https://ofm2qnhj5.qnssl.com` but my site host is `https://news.awesomes.cn/` , they doesn't match.

but how can I resolve this?

**Comment by pi0** [comment]
@bimohxh I don't see any manifest.json file in header. Which PWA guide did you folowd? You may try this one instead: 
If only want bare bone offline:
- https://github.com/nuxt-community/modules/tree/master/modules/workbox
Full PWA:
- https://github.com/nuxt-community/modules/tree/master/modules/workbox

**Comment by bimohxh** [comment]
@pi0  so this https://github.com/nuxt/nuxt.js/tree/dev/examples/offline-nuxt is not pwa demo?

**Comment by pi0** [comment]
Sorry for that you are right, It was an only a temporary offline solution, not PWA. Also deprecated :) We will remove example as well.

**Comment by bimohxh** [comment]
@pi0 oh. thanks! so is there a  full demo  to use https://github.com/nuxt-community/modules/tree/master/modules/workbox?  or I need to follow the workbox guide https://workboxjs.org/ ?

**Comment by pi0** [comment]
Yes, this not only demo, modules add integration automatically without any line of code. Suggest using PWA module first for best experience.

**Comment by bimohxh** [comment]
@pi0  I followed https://github.com/nuxt-community/modules/tree/master/modules/workbox

my code is at  https://github.com/awesomes-cn/news/blob/master/nuxt.config.js#L37

but still not work

**Comment by pi0** [comment]
@bimohxh  It seems you are using Nuxt `0.10.7` unfortunately it not supports modules. Is there any problem not `1.0.0-alpha`?

**Comment by bimohxh** [comment]
@pi0 thanks, I will upgrade the version

**Comment by bimohxh** [comment]
@pi0 I have upgrade nuxt to `v1.0.0-alpha.4`  but pwa still not work

**Comment by pi0** [comment]
What error are you getting?

**Comment by bimohxh** [comment]
@pi0 Oh thanks , It works now!!

**Comment by bimohxh** [comment]
@pi0  I use Lighthouse test, got ` Failures: No manifest was fetched, Manifest start_url is not cached by a Service Worker.`

so  workbox didn't request a Manifest ?

**Comment by bimohxh** [comment]
I am trying `@nuxtjs/manifest`

**Comment by bimohxh** [comment]
Everything is ok now

**Comment by pi0** [comment]
@bimohxh pwa is an customizablae all one in one to get 100 score :)

**Comment by frankspin89** [comment]
@bimohxh Do you mind sharing your config? I have the same error ```Failures: No manifest was fetched, Manifest start_url is not cached by a Service Worker.```

**Comment by bimohxh** [comment]
@frankspin89  the source is here https://github.com/awesomes-cn/news
