### ISSUE TITLE
Not work app.html

### ISSUE THREAD

**Issue by AkioSarkiz** [nuxt/nuxt.js#10289]
### Versions

- nuxt: see repo
- node: 16

### Steps to reproduce

- clone https://github.com/AkioSarkiz/test
- run `npm run build`

### What is Expected?
.nuxt/views/app.template.html is overwritten

### What is actually happening?
.nuxt/views/app.template.html isn't overwritten

**Comment by danielroe** [comment]
You shouldn't modify the contents of `.nuxt` (= the build directory). Instead, create an `app.html` in your source directory. See [docs](https://nuxtjs.org/docs/concepts/views#document-apphtml).

**Comment by AkioSarkiz** [comment]
Check my repository. I don't change `.nuxt` directory. Because i know, this repository for generated files of nuxtjs. But if you clone my repository, install all node modules and run command `npm run build`. You don't find my custom `app.html` in `.nuxt/views/app.template.html`. I don't know why this not work. I read documentation, search in network and don't find answer. Please, tell me why it's not work?

**Comment by danielroe** [comment]
I don't understand your issue then. `npm run build && npm run start` works fine. Your custom `app.html` is being respected.

**Comment by AkioSarkiz** [comment]
Please, watch the demo video, https://vimeo.com/680056891. Do you understand now?

**Comment by danielroe** [comment]
Do you have a problem when actually running the built server? Nuxt uses your provided `app.html` rather than the one in `.nuxt/views/app.html`, so if you run `npm run build && npm run start` you should see your GTM code as expected.

**Comment by nszbf** [comment]
@danielroe  How can `app.html` take effect in `nuxt3`
