### ISSUE TITLE
layout file default.vue is being reset after rebooting the nuxt.js server

### ISSUE THREAD

**Issue by liquidia** [nuxt/nuxt.js#10285]
Layout file default.vue is being reset after rebooting (yarn dev) the nuxt.js server.

### Versions
"dependencies:
    "core-js": "^3.19.3",
    "nuxt": "^2.15.8",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^4.46.0"

  "devDependencies": 
    "@nuxtjs/tailwindcss": "^4.2.1",
    "postcss": "^8.4.4"

Node Version: v16.13.2

### Steps to reproduce
Make changes or add new components in default layout 

### What is Expected?
Rebooting Nuxt server should not reset default.vue layout file

### What is actually happening?
Rebooting Nuxt server via yarn dev removing all the component and resetting default layout file .

**Comment by danielroe** [comment]
You should not edit the generated files in `.nuxt`. Instead, create `layouts/default.vue` in your source directory.

**Comment by liquidia** [comment]
> 

Thanks for the response ... i am editing layouts/default.vue only.

**Comment by liquidia** [comment]
> You should not edit the generated files in `.nuxt`. Instead, create `layouts/default.vue` in your source directory.

Thanks for the response but when i create a folder and file in apps root folder; custom layout is not being applied. not sure whats going on

**Comment by liquidia** [comment]
> Sorry i just realized my layout directory was outside the app route folder. Thanks again for the help!
> P.S:I am new to nuxt.js. Just started learning it.

Sorry i just realized my layout directory was outside the app route folder. Thanks again for the help!
P.S:I am new to nuxt.js. Just started learning it.
