### ISSUE TITLE
When is the release of version 1?

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#1028]
Hi,
  I saw version 1.alpha** in github.. Any update on when the final version 1 will be released?

**Comment by heww** [comment]
I would like to see the release of v1.0.0-alpha.5 for the extractCSS feature is broken in v1.0.0-alpha.4 version.

**Comment by hojas** [comment]
+1

**Comment by uptownhr** [comment]
Yea, probably need another alpha and a beta before release. 

I would also like an estimated timeline too! Can't wait to upgrade ... my prod app stuck on 0.10.7

**Comment by veresnikov** [comment]
+1

**Comment by stbaer** [comment]
alpha.6 with vue 2.4 dependency would also be nice for now. The last 2 releases of vuetify already don't work with nuxt alpha.5 anymore. Building nuxt from dev doesn't work for me.

**Comment by lobosan** [comment]
Same here, I'm working with vuetifyjs 0.14.5 and it depends on vue 2.4. Please release an updated version of nuxt with support for vue 2.4. Thanks in advance for your hard work

**Comment by evseevnn** [comment]
@alexchopin pls help us.
Have same problem. Im try use vuetifyjs 0.14.5 but that not work well with vue version less then 2.4
really wait for support vue@2.4

**Comment by evseevnn** [comment]
@lobosan vue@2.4 now available from nuxt@1.0.0-rc3

**Comment by BruceHem** [comment]
hmmm vue is now 2.5 and nuxt still using 2.4, it's 2 months now, and we haven't gotten any updates. kinda makes u think.

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/issues/2142
