### ISSUE TITLE
Postcss autoprefixer

### ISSUE THREAD

**Issue by vadimsg** [nuxt/nuxt.js#103]
Is there a way to extend postcss autoprefixer and add more browser last versions?
Webpack config api schmea doesn't have postcss object or I'm blind?

**Comment by Atinux** [comment]
Hi @vadimsg 

You should give the `build.postcss` option directly in your `nuxt.config.js`:

```js
module.exports = {
  build: {
    postcss: [
      require('autoprefixer')({
        browsers: ['> 5%']
      })
    ]
  }
}
```

**Comment by christophemarois** [comment]
With the latest RC, this worked for me:

```javascript
postcss: {
  'postcss-cssnext': {
    browsers: ['last 2 versions', 'ie >= 9']
  }
},
```
