### ISSUE TITLE
Header-Override not working without SSR

### ISSUE THREAD

**Issue by SoftCreatR** [nuxt/nuxt.js#10307]
### Versions

- nuxt: 2.15.8
- node: 16

### Steps to reproduce

nuxt.config.js (minimal config)

```js
export default {
  target: 'static',
  ssr: false,
  head: {
    title: 'Example',
    meta: [
      {
        hid: 'robots',
        name: 'robots',
        content: 'all'
      }
    ]
  },
}
```

page.vue:

```html
<template>
  <h1>{{ title }}</h1>
</template>

<script>
  export default {
    data() {
      return {
        title: 'Hello World!'
      }
    },
    head() {
      return {
        title: this.title,
        meta: [
          {
            hid: 'robots',
            name: 'robots',
            content: 'noindex,nofollow'
          }
        ]
      }
    }
  }
</script>
```

### What is Expected?

The generated HTML file should contain this:

```html
<title>Hello World</title>
...
<meta data-n-head="1" data-hid="robots" name="robots" content="noindex,nofollow">
```

### What is actually happening?

The generated HTML file contains this:

```html
<title>Example</title>
...
<meta data-n-head="1" data-hid="robots" name="robots" content="all">
```

**Comment by SoftCreatR** [comment]
Quick follow up: If I enable `SSR`, it works as expected. But then, I have other problems:

We are using Apollo to retrieve page contents via GraphQL. When enabling SSR, new or changed contents only appear after re-building the frontend (via `yarn generate`). Disabling SSR allows us to dynamically retrieve new and/or changed contents, but leads to other problems (as described in this issue).

**Comment by danielroe** [comment]
If you are not using SSR, then your components won't be rendered, meaning that any overrides to your head tags won't be run. That's unfortunately just how it works.

If you need page content to be loaded only on client side, you can check out the `<client-only>` component provided by nuxt.
