### ISSUE TITLE
Disable SPA part of the framework

### ISSUE THREAD

**Issue by dodozhang21** [nuxt/nuxt.js#1030]
Hello, I was wondering if there exists a simple switch to turn off the SPA part of the framework and just rely on SSR? We have a requirement to possible to delay using the SPA for a while but would like to enable it at a later time.

Could you please let me know if this is possible with nuxt?

Thanks

**Comment by pi0** [comment]
Hey. Would you please explain more bout your use-case?

**Comment by dodozhang21** [comment]
Basically can the framework act just like SSR framework without the SPA part of it?  So every request inside the navigation will be a true request without async loading if SPA is turned off.

**Comment by pi0** [comment]
But Nuxt's SPA is something that works just after SSR phase. Page loads fast then client-side rehydration for next requests. Is there any reason disabling javascript? (PS: While i agree with such usage, I'm just looking for enough reasons this feature would be useful for others too)

**Comment by dodozhang21** [comment]
Our current ad framework doesn't support SPA. It's just to give the framework time to catch up in order to support SPA. We won't be disabling javascript. I'm not sure where that impression came from.

**Comment by kevin-coyle** [comment]
I have another (minor) use case for this. When I would like to host the backend locally and then deploy the frontend to S3 or github pages. That means that I don't need to pay for hosting for the backend.

**Comment by Atinux** [comment]
@kevin-coyle you can use `nuxt generate` for this ;)

**Comment by kevin-coyle** [comment]
@Atinux when using `nuxt generate` any additional route transitions call the backend server.

**Comment by Atinux** [comment]
@kevin-coyle why not using `<a>` instead of `<nuxt-link>` to avoid client-side navigation?

**Comment by kevin-coyle** [comment]
Ah a good idea. It might require some thought when utilising pagination that would ordinarily have to  call back to the server.

**Comment by pi0** [comment]
It is possible with `rc3+` using `mode` option:

**nuxt.config.js**
```js
module.exports = {
  mode: 'static'
}
```

**Comment by rlataguerra** [comment]
@pi0 is that mode still available or https://github.com/nuxt/docs/blob/master/en/api/configuration-mode.md is just not updated ?

**Comment by tevel** [comment]
It seems like mode: 'static' is no more relevant.
I'd like to disable SPA conditionally to test server side rendering.
e.g. https://mywebste.com/no-spa opens without any javascript code to run selenium or any other tests.
Because I can't find possibility to disable javascript on the client side testing tool.
