### ISSUE TITLE
Redirect fails for middleware.

### ISSUE THREAD

**Issue by jmarshall9120** [nuxt/nuxt.js#10300]
### Versions

- nuxt: v2.15.8 
- node: v16.14.0 

### Reproduction

https://github.com/jmarshall9120/nuxt_template/tree/ticket_auth_redirect_issue

<details open>

Adding a global middleware with a redirect for protected routes as exampled [here](https://nuxtjs.org/docs/directory-structure/middleware/#router-middleware) causes the following error:

```
Error: Redirected when going from "/" to "/login" via a navigation guard.
    at createRouterError (vue-router.esm.js?8c4f:2065:1)
    at createNavigationRedirectedError (vue-router.esm.js?8c4f:2024:1)
    at eval (vue-router.esm.js?8c4f:2376:1)
    at Vue._next (client.js?06a0:299:1)
    at app.context.redirect (utils.js?ebed:235:1)
    at eval (auth.js?14c2:8:1)
    at promisify (utils.js?ebed:314:1)
    at middlewareSeries (utils.js?ebed:291:1)
    at Vue.callMiddleware (client.js?06a0:264:1)
    at Vue._callee6$ (client.js?06a0:267:1)
```

<summary>Additional Details</summary>
<br>

nuxt.config.js
```

  router: {
    middleware: 'auth',
  },
```

middleware/auth.js
```
export default function ({ store, redirect }) {
  // If the user is not authenticated
  if (!store.state.authenticated) {
    return redirect('/login')
  }
}
```

</details>

### Steps to reproduce
Try to load localhost:3000, you'll get stuck.

### What is Expected?
when loaded localhost:3000 you'll be redirected to localhost:3000/login

### What is actually happening?
Browser freezes and error is output in console.

**Comment by illjah42** [comment]
experiencing same problem

**Comment by FaizanKhanDev** [comment]
export default async function ({ store, redirect, route }) {
  if (!store.state.auth.checkIsAuthenticated) {
    if (route.path != '/auth/login') {
      return redirect('/auth/login');
    }
  } else {
    return redirect('/posts');
  }
}
i wrote this and Same Issue
