### ISSUE TITLE
Stop Loading When data are ready not before

### ISSUE THREAD

**Issue by PrimeClet** [nuxt/nuxt.js#10314]
### Is your feature request related to a problem? Please describe.

this is not a feature at all, i have to stop loading when the data is ready not before.

My loading stops but the data is not ready and I have a broken view that is still popping up data one after another

**Please help!**

**Comment by danielroe** [comment]
Nuxt 2 offers `asyncData`, which blocks page navigation whilst data is fetched but which only works in page components. Or `fetch`, which is non-blocking but works in any component.

You can read more at https://nuxtjs.org/docs/features/data-fetching#data-fetching.
