### ISSUE TITLE
Fetching data via store server side not working

### ISSUE THREAD

**Issue by keithmancuso** [nuxt/nuxt.js#1031]
Im sure this has been asked before but i cant for the life of me figure out whats going on

this code in the page 
```
fetch ({ store }) {
 const response = await axios.get(dataUrl);
 console.log(response.data)
 store.commit("SET_SECTIONS", response.data);
}
```

and yet somehow this doesn't work

```
fetch ({store}) {
 store.dispatch('fetchSections')
}
```

where in the store the action is doing the same thing

```
 async fetchSections({ commit, getters }) {
    const response = await axios.get(dataUrl);
    console.log(response.data)
    commit("SET_SECTIONS", response.data);
  }
```

the console log is the same for both, but for some reason the one where the fetc calls the action isnt populating the store?

Any ideas?

**Comment by alexchopin** [comment]
Hi @keithmancuso, have you tried to use `return` in the second option?
```js
fetch ({store}) {
 return store.dispatch('fetchSections')
}
```

**Comment by keithmancuso** [comment]
Ahh interesting that fixed it, thanks for the quick response. 

Although I'm not sure i understand why?

**Comment by alexchopin** [comment]
It's because `fetch()` can be or return a Promise :)

**Comment by keithmancuso** [comment]
right!  thank you!
