### ISSUE TITLE
404 error when using 'generate' command with subFolders: false

### ISSUE THREAD

**Issue by ahas** [nuxt/nuxt.js#10310]
### Versions
- nuxt: 2.15.8
- node: 16.13.1

### Reproduction
set nuxt generate option to subFolders: false
then nuxt generate

<details open>
<summary>Additional Details</summary>
<br>

Dependencies in package.json
```json
    "dependencies": {
        "core-js": "^3.19.3",
        "nuxt": "^2.15.8",
        "vue": "^2.6.14",
        "vue-server-renderer": "^2.6.14",
        "vue-template-compiler": "^2.6.14",
        "vuetify": "^2.6.1",
        "webpack": "^4.46.0"
    },
    "devDependencies": {
        "@babel/eslint-parser": "^7.16.3",
        "@mdi/font": "^6.5.95",
        "@nuxt/types": "^2.15.8",
        "@nuxt/typescript-build": "^2.1.0",
        "@nuxtjs/eslint-config-typescript": "^8.0.0",
        "@nuxtjs/eslint-module": "^3.0.2",
        "@nuxtjs/vuetify": "^1.12.3",
        "@vue/test-utils": "^1.3.0",
        "babel-core": "7.0.0-bridge.0",
        "babel-jest": "^27.4.4",
        "eslint": "^8.4.1",
        "eslint-config-prettier": "^8.3.0",
        "eslint-plugin-nuxt": "^3.1.0",
        "eslint-plugin-vue": "^8.2.0",
        "jest": "^27.4.4",
        "prettier": "^2.5.1",
        "ts-jest": "^27.1.1",
        "vue-jest": "^3.0.4"
    }
```
nuxt.config.js
```js
    router: {
        base: '/q/',
        extendRoutes(routes) {
            for (const route of routes) {
                if (route.name === 'live') {
                    route.path += '.html';
                }
            }
        }
    },
    generate: {
        fallback: true,
        subFolders: false
    }
```

</details>

### What is Expected?
If, "live.vue" file is in "pages" directory,
nuxt creates a live.html file inside dist directory,
"route.path", which is automatically created should be "live.html", but that "route.path" is created as "live", so it seems it shows 404 error.

My temporary solution for this is to define extendRoutes like this:
```js
        extendRoutes(routes) {
            for (const route of routes) {
                if (route.name === 'live') {
                    route.path += '.html';
                }
            }
        }
```
Using this, nuxt creates as "live.html.html", not as "live" or "live.html", 
However route.path is created as "live.html", so 404 error is not happening, 

but i should change the file name as "live.html".

**Comment by danielroe** [comment]
Yes, you should not access a route with a `.html` extension. (Your temporary solution is probably the best one if you need to cater for that use case.) Normally this is a matter of configuring your web server or CDN to serve without the `.html` file extension.
