### ISSUE TITLE
Server middleware called twice

### ISSUE THREAD

**Issue by Morgbn** [nuxt/nuxt.js#10323]
Server middleware is called twice if both CommonJS modules and ES6 Modules are imported.

### Versions

- nuxt: v2.15.8
- node: v14.16.1

### Reproduction

Codesandbox: https://codesandbox.io/s/nameless-cloud-owj5st?file=/api/index.js:191-223

<details open>
Import an ES6 module into one of your middleware dependencies (usually a module used on both the front-end and back-end).
</details>

**Comment by MooseSaeed** [comment]
Any updates on this?

**Comment by Morgbn** [comment]
sorry @MooseSaeed not on my side (I switched entirely to nuxt3 +typescript)

**Comment by yangjiamu** [comment]
Same problem with 2.17.0, it get to ok when not use CommonJS import
