### ISSUE TITLE
Hot reloading fails with no recovery after any source file deletion even if the file is not needed anymore

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/nuxt.js#1033]
How to reproduce:
* create a component and import it into page. See the server is up and running and the page with the component works just fine.
* delete the component. See there's an error, which is okay.
* delete component import from the page. See the error didn't go away, while it sorta should.

**Comment by husayt** [comment]
This seems to be resolved now. Closing. Reopen if still happens.
