### ISSUE TITLE
Difference between generate function and prerender-spa-plugin

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt.js#1034]
Hello!

In the company I work for, we currently have a Laravel backend with without Node. I would like to code all the frontend in Vue. However I read some articles saying SPAs are bad for SEO and that pre-rendering was suggested over SSR when Node is not an option.

I have found the following plugin:
- https://github.com/chrisvfritz/prerender-spa-plugin

What is the difference between the generate function in Nuxt and this plugin? What about page transitions? Does Nuxt generate rely on the same mechanisms?

Thanks for  your help!

**Comment by alexchopin** [comment]
Hi @lucpotage,
That's a great question.
First of all, I would say that it depends on your use case as the `prerender-spa-plugin` says in the readme.
There is no difference between the `generate` function in Nuxt and this plugin for the HTML result.
The purpose of Nuxt is to make your development enjoyable by doing basic configuration and optimization for you.
What do you mean about page transitions?
I'm closing the issue, but the thread can keep going :)

**Comment by khalwat** [comment]
@alexchopin but does Nuxt render the static HTML with data obtained from a XHR'd API? I've been struggling to get that working, and it doesn't appear based on some of the github issues that it can be done currently.

For instance, if I have code like:

```
            <div v-for="blog in blogs" class="col-xs-12 col-sm-6 col-md-4 blog-archives-column">
                <div class="box blog-archives-inner">
                    <a v-bind:href="blog.url" @mouseover="prerenderLink">
                        <div class="archives-image-container">
                            <img class="scale-with-grid archives-image" v-bind:src="blog.blogImageUrl" v-bind:alt="blog.title">
                        </div>
                    </a>
                    <div class="blog-archives-textbox">
                        <h4 class="blog-archives-category">
                            <span class="blog-archives-category">
                                <span v-for="category in blog.blogCategory">${ category } </span>
                                <span class="blog-date"> &middot; ${ blog.postDate }</span>
                            </span>
                        </h4>
                        <h3 class="blog-archives"><a class="blog-title" v-bind:href="blog.url" @mouseover="prerenderLink">${ blog.title }</a>
                        </h3>
                        <p class="blog-archives-credits">
                            <span class="blog-archives-tags">
                                <span v-for="tag in blog.blogTags">#${ tag } </span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
```
...where `blog` is data that I retrieve via Axois from an API endpoint, I want the resulting HTML to be pre-rendered with the HTML generated from this data intact, and then it hands over control of the DOM to Vue.

So what it needs to do is wait until the data has been obtained, render out the static HTML, and _that_ is what ends up getting saved to disk. I don't want to have to wait for the JavaScript to have to load, and populate the data, which then generates the HTML.

Have I missed something?

**Comment by avidus3r** [comment]
Bump... I am currently working on accomplishing the same thing, however I am using the html-webpack-plugin by passing the plug-in via extending the webpack config in nuxt.config.js.

**Comment by chrisvfritz** [comment]
@khalwat @avidus3r I think this might be more of a Vue SSR question than relating to Nuxt specifically. I believe what you're looking for is [data pre-fetching](https://ssr.vuejs.org/en/data.html). 🙂 Hope that helps!
