### ISSUE TITLE
Cannot read properties of undefined (reading 'stubModule')

### ISSUE THREAD

**Issue by jasondonnellya** [nuxt/nuxt.js#10345]
### Versions

- nuxt: v3
- node: v16.14

### Reproduction

I am dynamically trying to import components but for some reason I can only import with a static url. Trying to do so using a variable name causes the error.

Works:
```JS
console.log(await import('~/components/Logo'))
```

Doesn't work:
```JS
const url = '~/components/Logo'
console.log(await import(url))
```

### Steps to reproduce

I am calling the above code from the plugins directory in Nuxt3.

```JS
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    plugins: [
        '~/plugins/import.js' ,
    ],
})
```

### What is Expected?

Should return the component.

### What is actually happening?

Throws this error:

```
Cannot read properties of undefined (reading 'stubModule')
  at __instantiateModule__ (.../nuxt3-app/.nuxt/dist/server/server.mjs:22623:11)
  at __ssrLoadModule__ (.../nuxt3-app/.nuxt/dist/server/server.mjs:22614:25)
  at ssrImport (.../nuxt3-app/.nuxt/dist/server/server.mjs:22639:13)
  at ssrDynamicImport (.../nuxt3-app/.nuxt/dist/server/server.mjs:22650:12)
  at $id_7142e441 (.../nuxt3-app/.nuxt/dist/server/server.mjs:21407:7)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async __instantiateModule__ (.../nuxt3-app/.nuxt/dist/server/server.mjs:22667:3)  
```

**Comment by jasondonnellya** [comment]
I'm unsure if dynamic import actually supports anything other than string literals. I think CommonJS require supports this however Nuxt3 isn't allowing any files I use in the /plugins directory to use cjs syntax.

**Comment by jasondonnellya** [comment]
#10340

**Comment by jasondonnellya** [comment]
If anyone runs into this issue I found out a while ago that you can only use dynamic import for file names or after the first folder in import I believe so this isn't a Nuxt issue, I thought it was something to do with cjs/es module differences.

I'm not sure of all the nuances but using:

```JS
const componentName = 'Logo'
console.log(await import(`~/components/${componentName}`))
```

Should hopefully work.

You also have to wrap the component and get it's default:

```JS
(await import(`~/components/${componentName}`)).default
```

**Comment by paidge** [comment]
I just tried this and that did not work : 
```
<script>
const imgName = "myImg"
const img = await import("~/assets/img/projets/${imgName}.png")
const imgPath = img.default

export default {
  data() {
    return {
      imgPath
    }
  }
}
</script>
```
But this works : 
```
<script>
const img = await import("~/assets/img/projets/myImg.png")
const imgPath = img.default

export default {
  data() {
    return {
      imgPath
    }
  }
}
</script>
```

**Comment by msdsk** [comment]
What is odd is that it work for the client in dev mode, if you guard the code with `process.dev` it will compile successfully and display what you need, just complaining about the hydration mismatch. Alas, it will not work after building it for ssr.
