### ISSUE TITLE
using gsap

### ISSUE THREAD

**Issue by Amirali-Yavari** [nuxt/nuxt.js#10359]
hi 
im using gsap like this
```
<script>
import gsap from 'gsap'
gsap.from('p', {
  opacity: 0,
  duration: 1,
  y: -100,
  ease: 'bounce'
})
</script>
```
when i use it by script setup its allways give a error :
**Cannot read properties of undefined (reading 'querySelectorAll')**
when i delete **setup** when i restart the dev server at other page and come to this page and change something in gsap its work
but when i refresh the page its give the same error:
**Cannot read properties of undefined (reading 'querySelectorAll')**

**Comment by ThornWalli** [comment]
@Amirali-Yavari Try to run `gsap` only client side.

**Comment by Amirali-Yavari** [comment]
Thanks for your help
