### ISSUE TITLE
Problem with Session and Window

### ISSUE THREAD

**Issue by lucassmacedo** [nuxt/nuxt.js#1037]
Hello! i try develop a client for an api with nuxt.. and i try save the bearer token on localStorage but never work.. I using Vuex Modules to..
always the same error
 localStorage is not defined
or 
 window is not defined
the backend api is PHP (Laravel) ..

Thanks guys

**Comment by pi0** [comment]
Hey. You need to use cookies for storing tokens. that error actually happens during SSR phase on server side.

**Comment by lucassmacedo** [comment]
@pi0 any tutorial? i search but i dont find a example...

**Comment by pi0** [comment]
There is a deticated [guide on SSR](http://ssr.vuejs.org/) which i strongly recommend reading to get better idea about everything. About auth toutorial with nuxt currently, there is no complete one. But as mentioned above you are using a Cookie compatible backend things should be easy by just using [axios module](https://github.com/nuxt/modules/tree/master/modules/axios) to make http requests. Then you can set cookies anyway you prefer (even client side) after login and everything should work.
