### ISSUE TITLE
Hydration mismatch at {{ "" }} inside v-for

### ISSUE THREAD

**Issue by Fabioni** [nuxt/nuxt.js#10390]
### Versions

- nuxt: v2.15.18
- node: v16.14.0

### Reproduction

```html
<span v-for="(obj, index) in objs" :key="obj.id">{{ "" }}<span>Test</span></span>
```

Important for me was it in this usecase

```html
<span v-for="(obj, index) in objs" :key="obj.id">{{ index > 0 ", " : "" }}<wbr v-if="index > 0"><span>{{obj.text}}</span></span>
```

### Steps to reproduce

Use `nuxt dev` with `target: 'static'` in nuxt.config

### What is Expected?

normal hydration

### What is actually happening?

I get a hydration mismatch because nuxt on ssr somehow thinks there is a node with empty content and undefined type and on clientside there correctly no node.

### Workaround

use instead:
```html
<span v-for="(obj, index) in objs" :key="obj.id"><span>{{ "" }}</span><span>Test</span></span>
```

resp.

```html
<span v-for="(obj, index) in objs" :key="obj.id"><span v-if="index > 0">, </span><wbr v-if="index > 0"><span>Test</span></span>
```

Cheers :-)

**Comment by danielroe** [comment]
This is Vue SSR behaviour. I'd recommend [raising an issue there](https://github.com/vuejs/vue/issues) instead.
