### ISSUE TITLE
Nuxt Js does not compile on Nodejs 18

### ISSUE THREAD

**Issue by sarunluitel** [nuxt/nuxt.js#10399]
### Versions

- nuxt: "^2.15.8"
- node: v18.0.0
- OS: ubuntu 18.04 and 22.04 (same error on both systems)

### Steps to reproduce
dev server does not start.  Error Message below

![image](https://user-images.githubusercontent.com/17135424/164373313-ad632aea-cb75-4483-8797-a39bf91a28b1.png)

 UPDATE!
The above error was a simple fix. but required to make changes in the node_modules file. so just a temporary fix for now. new error after the fix!

Issue for this on node-ip repository: https://github.com/indutny/node-ip/issues/113

> nuxt

   ╭───────────────────────────────────────────╮
   │                                           │
   │   Nuxt @ v2.15.8                          │
   │                                           │
   │   ▸ Environment: development              │
   │   ▸ Rendering:   client-side              │
   │   ▸ Target:      static                   │
   │                                           │
   │   Listening: http://172.18.79.190:3000/   │
   │                                           │
   ╰───────────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                                                              11:29:45
ℹ Initial build may take a while                                                                                                                                                                                 11:29:45
ℹ Discovered Components: dist/components/readme.md                                                                                                                                                               11:29:45
✔ Builder initialized                                                                                                                                                                                            11:29:45
✔ Nuxt files generated                                                                                                                                                                                           11:29:45

● Client █████████████████████████ compiling (0%)  
 

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/sl/socialSite/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/sl/socialSite/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/sl/socialSite/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/sl/socialSite/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/sl/socialSite/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/sl/socialSite/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/sl/socialSite/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/sl/socialSite/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/sl/socialSite/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/sl/socialSite/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/sl/socialSite/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.0.0
sl@xxxxxx:~/project$ node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 1863.
    at /home/sl/project/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v18.0.0
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 1869.
    at /home/sl/project/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v18.0.0

**Comment by brolnickij** [comment]
is a webpack problem https://github.com/webpack/webpack/issues/14532, and the problem is solved with https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

**Comment by maetad** [comment]
`npm update` or `yarn upgrade` worked for me

**Comment by sarunluitel** [comment]
the dependencies have been updated to work with node 18. Works well now

**Comment by ausir0726** [comment]
@sarunluitel 

same problem here `Error: error:0308010C:digital envelope routines::unsupported`

when 2022/10/25  node 18.12.0 change to LTS version

thanks.

```cmd
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\ausir\test\node18nuxt\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\ausir\test\node18nuxt\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\ausir\test\node18nuxt\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\ausir\test\node18nuxt\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\ausir\test\node18nuxt\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\ausir\test\node18nuxt\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\ausir\test\node18nuxt\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\ausir\test\node18nuxt\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\ausir\test\node18nuxt\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\ausir\test\node18nuxt\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\ausir\test\node18nuxt\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

**Comment by nachoadjust** [comment]
Hello!
Is there a fix for this issue?
We are experiencing a similar error (or a different version of it) when deploying in Vercel:

```js
[error] Error: error:0308010C:digital envelope routines::unsupported
--
11:40:34.167 | at new Hash (node:internal/crypto/hash:71:19)
11:40:34.167 | at Object.createHash (node:crypto:133:10)
```

So far we have been surviving fine by using Node16, but Vercel will soon [deactivate](https://vercel.com/changelog/node-js-14-and-16-are-being-deprecated) any Node version below 18 [ Panic mode activated ].
