### ISSUE TITLE
Nuxt Link not serverside rendering page

### ISSUE THREAD

**Issue by gregg-cbs** [nuxt/nuxt.js#10408]
### Versions

- nuxt: 2.15.8
- node: 16.14.0

### Reproduction
On dev when using NuxtLink to go to a page that needs server side rendered data, it does not serverside render the data. Only when I hit the page using the browser url bar does serverside work.
```
  <NuxtLink :to="company.url_slug" no-prefetch>
    ...
  </NuxtLink>
```

```
// company page that has serverside rendering
export default {
  name: "Company",
  fetchOnServer: true,
  async fetch() {
    const {company_id, suburb} = this.$route.params;
    const dynamicParams = `${company_id}-${suburb}`;
    const res = await this.$http.$get(`/api/get-business?id=${dynamicParams}`);
    this.company = res;
  },
  data: () => ({
    company: Object,
  }),
  head() {
    return {
      title: `${this.company.name && this.company.address.addressLocality} `,
    };
  }
};
```

<details open>
<summary>Additional Details</summary>
<br>
In the above case Nuxt throws an error because in the head() company is not defined but even if I fix this, in the browser I can see a flash in the page title going from 'undefined' to 'the companies name'. Why would serverside rendering not happen when using nuxt link?
</details>

**Comment by Flowfly** [comment]
I have the same issue, any news for this problem ?

**Comment by danielroe** [comment]
Nuxt is server-rendered only on the initial load. Subsequent navigation happens on client-side. When you are using `fetch` rather than `asyncData` the data fetching is non-blocking, meaning you need to handle the condition _before_ the data resolves.

**Comment by gregg-cbs** [comment]
I thought asyncData was on in nuxt 3. Here is a link on it for anyone else:
https://nuxtjs.org/docs/features/data-fetching/#async-data

**Comment by njiels** [comment]
Sorry is it possible to have a concrete fix for this? I usually fix it by replacing <NuxtLink> with <a> but then the crawling will not work causing some pages to not be rendered for production.

**Comment by njiels** [comment]
Is it possible to have concrete fix for this?I usually fix it with replacing 'nuxtlink' with 'a', but this causes the crawling during production build to disturbed resulting in the pages that I want to link not being rendered.
