### ISSUE TITLE
render function or template not defined in component: anonymous

### ISSUE THREAD

**Issue by jasmineY** [nuxt/nuxt.js#1041]
I use `vue-scroller` of the vue Plugins in my project. It work on the initial load but when the page is refreshed，I get 2 errors, the first is "document is not defined" then if I refresh the page again i'll get "Error: render function or template not defined in component: anonymous".

I have already set SSR to false for vue-scroller in the nuxt.config.js  but not resolved the '`document is not defined`'

So, can you help me?
----
####  .vue file
```
   <template>
       ...
        <scroller style="top: 97px" :on-infinite="loadMore">
        </scroller>
     ....
    </template>
    ...
    <script>
         import Vue from 'vue';
         import Scroller from 'vue-scroller';
         Vue.use(Scroller)
        ...
    </script>
   
```
----
#### nuxt.config.js
```
    ...
    plugins: [
    {
      src:'~plugins/vue-scroll.js',
      ssr:false
    }
   ],
    ...
```
----
#### vue-scroll.js
```
import Vue from 'vue';
import Scroller from'vue-scroller';

Vue.use(Scroller);
```

**Comment by pi0** [comment]
Hey. Two potentially typos in your `.vue` example. You should only have one root element inside `<templates`. Also `Vue.use` should not be inside `.vue` anymore (or you will get more SSR problems). Please provide your full `.vue` file for better help.

**Comment by coolemur** [comment]
Hi.

I have the same problem with 'vue-easy-slider' plugin.

.vue:
```
<template>
  <div>
    <slider animation="fade">
      <slider-item v-for="(i, index) in list" :key="index">
        <div :style="i">
          <p style="line-height: 280px; font-size: 5rem; text-align: center;">Page{{ index + 1 }}</p>
        </div>
      </slider-item>
    </slider>
  </div>
</template>

<script>
import { Slider, SliderItem } from 'vue-easy-slider'

export default {
  data () {
    return {
      list: [
        { backgroundColor: '#3f51b5', width: '100%', height: '100%' },
        { backgroundColor: '#eee', width: '100%', height: '100%' },
        { backgroundColor: '#f44336', width: '100%', height: '100%' }
      ]
    }
  },
  components: {
    Slider,
    SliderItem
  }
}
</script>
```

plugins/vue-easy-slider.js
```
import Vue from 'vue'
import VueEasySlider from 'vue-easy-slider'

Vue.use(VueEasySlider)
```
nuxt.config.js:
```
module.exports = {
  plugins: [{ src: '~plugins/vue-easy-slider.js', ssr: false }],
...
  build: {
...
    vendor: ['vue-easy-slider']
  }

```

**Comment by homerjam** [comment]
in `vue-scroll.js`

Can you try:
```js
Vue.component('scroller', Scroller);
```

**Comment by kennsand** [comment]
I also have the same problem, trying to use Vue.component ('scroller', Scroller); but it doesn't work.

**Comment by Syffs** [comment]
@kennsand try [this](https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-353827607)
as specified, do not import the component when you want to use it, as it's registered globally
