### ISSUE TITLE
Fresh Install nuxt Plugin error without any plugin files. 

### ISSUE THREAD

**Issue by resuta566** [nuxt/nuxt.js#10439]
### Versions

- nuxt: ^2.15.7
- node: v14.16.1

### Reproduction

Create a new project using npm init nuxt-app <project-name>

You can choose any additional settings.

then try to run npm run dev

### Steps to reproduce

Create a new project using npm init nuxt-app <project-name>

You can choose any additional settings.

then try to run npm run dev

### What is Expected?

The project would run normally.

### What is actually happening?

![image](https://user-images.githubusercontent.com/32506189/168400487-978b3d62-3d66-4deb-8239-8ebef9ba0824.png)

**Comment by Tirta-Adi-Prasetya** [comment]
is there any temporary fix for this bug?

**Comment by resuta566** [comment]
> is there any temporary fix for this bug?

I tried to downgrade but still doesnt work.

**Comment by uxin603s** [comment]
seem window update problem

**Comment by anggario21** [comment]
hi i also came across the same problem any fix update?

**Comment by resuta566** [comment]
> hi i also came across the same problem any fix update?



> seem window update problem



> is there any temporary fix for this bug?

here's a temporary fix. 

```npm i --save glob@7.2.0 ```

[Link to comment from #1440](https://github.com/nuxt/nuxt.js/issues/10440#issuecomment-1126714019)

**Comment by danielroe** [comment]
This issue should be fixed in the most recent version of `glob`: see https://github.com/nuxt/nuxt.js/issues/10440#issuecomment-1126993346.
