### ISSUE TITLE
<component> balise not render component

### ISSUE THREAD

**Issue by Andy-d-g** [nuxt/nuxt.js#10449]
Hello,

the <component> balise not render custom component 

### Versions

- nuxt: 3.0.0-rc.3
- node: 17.9.0

### Reproduction

![Capture d’écran 2022-05-15 à 20 16 11](https://user-images.githubusercontent.com/47396117/168488523-2d3ca3ba-7f89-49a9-b184-05a9163a14c8.png)

I'm making a mistake ?

Thank you

**Comment by danielroe** [comment]
You need to use `resolveComponent`

```js
const name = resolveComponent('test')
```

See https://v3.nuxtjs.org/guide/directory-structure/components#dynamic-components.
