### ISSUE TITLE
Server error when i refresh page

### ISSUE THREAD

**Issue by zhoufanglu** [nuxt/nuxt.js#10453]
### Versions

- nuxt: 2.15
- node:  14

### Steps to reproduce
Within a particular route, I get an error whenever I refresh, only in production env

### What is Expected?
refresh page display success

### What is actually happening?
![image](https://user-images.githubusercontent.com/24451091/168748293-07350b1a-896b-41a8-b74b-e4481a39314b.png)
![image](https://user-images.githubusercontent.com/24451091/168748465-b09966c5-ad34-49db-855a-8587ecb1b387.png)

**Comment by tonyex52** [comment]
I got the same situation!!

And here is the server side report
```
ERROR  render function or template not defined in component: anonymous
│   at Yi (node_modules/vue-server-renderer/build.prod.js:1:67000)
│   at oo (node_modules/vue-server-renderer/build.prod.js:1:70873)
│   at no (node_modules/vue-server-renderer/build.prod.js:1:70523)
│   at to (node_modules/vue-server-renderer/build.prod.js:1:67770)
│   at node_modules/vue-server-renderer/build.prod.js:1:70990
│   at eo (node_modules/vue-server-renderer/build.prod.js:1:67480)
│   at oo (node_modules/vue-server-renderer/build.prod.js:1:70892)
│   at no (node_modules/vue-server-renderer/build.prod.js:1:70523)
│   at to (node_modules/vue-server-renderer/build.prod.js:1:67770)
│   at node_modules/vue-server-renderer/build.prod.js:1:70990
```

Any idea?

**Comment by lcnoobmystery** [comment]
> 我遇到了同样的情况！！
> 
> 这是服务器端报告
> 
> ```
> ERROR  render function or template not defined in component: anonymous
> │   at Yi (node_modules/vue-server-renderer/build.prod.js:1:67000)
> │   at oo (node_modules/vue-server-renderer/build.prod.js:1:70873)
> │   at no (node_modules/vue-server-renderer/build.prod.js:1:70523)
> │   at to (node_modules/vue-server-renderer/build.prod.js:1:67770)
> │   at node_modules/vue-server-renderer/build.prod.js:1:70990
> │   at eo (node_modules/vue-server-renderer/build.prod.js:1:67480)
> │   at oo (node_modules/vue-server-renderer/build.prod.js:1:70892)
> │   at no (node_modules/vue-server-renderer/build.prod.js:1:70523)
> │   at to (node_modules/vue-server-renderer/build.prod.js:1:67770)
> │   at node_modules/vue-server-renderer/build.prod.js:1:70990
> ```
> 
> 任何的想法？

看看这个，https://stackoverflow.com/questions/63279054/nuxt-js-could-not-found-component-with-errors-failed-to-mount-component-templa。

**Comment by lcnoobmystery** [comment]
> ### Versions
> * nuxt: 2.15
> * node:  14
> 
> ### Steps to reproduce
> Within a particular route, I get an error whenever I refresh, only in production env
> 
> ### What is Expected?
> refresh page display success
> 
> ### What is actually happening?
> ![image](https://user-images.githubusercontent.com/24451091/168748293-07350b1a-896b-41a8-b74b-e4481a39314b.png) ![image](https://user-images.githubusercontent.com/24451091/168748465-b09966c5-ad34-49db-855a-8587ecb1b387.png)

我似乎知道了问题的所在，我的问题所在是axios的browserBaseURL与baseURL的配置问题。你可以看看https://www.aerowang.cn/articles/3lwhaw2l

**Comment by lcnoobmystery** [comment]
> ### Versions
> * nuxt: 2.15
> * node:  14
> 
> ### Steps to reproduce
> Within a particular route, I get an error whenever I refresh, only in production env
> 
> ### What is Expected?
> refresh page display success
> 
> ### What is actually happening?
> ![image](https://user-images.githubusercontent.com/24451091/168748293-07350b1a-896b-41a8-b74b-e4481a39314b.png) ![image](https://user-images.githubusercontent.com/24451091/168748465-b09966c5-ad34-49db-855a-8587ecb1b387.png)

你应该尝试去配置axios中的browserBaseURL与baseURL。
https://axios.nuxtjs.org/options#baseurl
https://nuxtjs.org/pt/docs/directory-structure/nuxt-config#a-propriedade-runtimeconfig

**Comment by zhoufanglu** [comment]
> > ### Versions
> > 
> > * nuxt: 2.15
> > * node:  14
> > 
> > ### Steps to reproduce
> > Within a particular route, I get an error whenever I refresh, only in production env
> > ### What is Expected?
> > refresh page display success
> > ### What is actually happening?
> > ![image](https://user-images.githubusercontent.com/24451091/168748293-07350b1a-896b-41a8-b74b-e4481a39314b.png) ![image](https://user-images.githubusercontent.com/24451091/168748465-b09966c5-ad34-49db-855a-8587ecb1b387.png)
> 
> 你应该尝试去配置axios中的browserBaseURL与baseURL。 https://axios.nuxtjs.org/options#baseurl https://nuxtjs.org/pt/docs/directory-structure/nuxt-config#a-propriedade-runtimeconfig

最后我用二分注释法定位到了， 首先我并没有用到接口， 用的是pdf.js这个插件， 开发环境永远是没问题的，上了生产也不报错，刷新页面就server error了， 最后我把pdf.js先注释了

**Comment by Jopchumba** [comment]
was having the same similar error when refreshing will let you know if I was able to resolve the issue.
I am running on Nginx proxy

**Comment by zhoufanglu** [comment]
> @zhoufanglu i think it has to do with your pages make sure that during development they render correctly then build it again

after uninstall pdf-js , it work.
