### ISSUE TITLE
Erro on nuxt start on production

### ISSUE THREAD

**Issue by raisiqueira** [nuxt/nuxt.js#1046]
I running nuxt in Docker, but return this error:
![image](https://user-images.githubusercontent.com/2914170/27970107-f6cc0afe-6323-11e7-8ea6-51c79fb64d27.png)

The api endpoint is ok in the configuration file

Node Version: 7

**Comment by Atinux** [comment]
@raisiqueira please make sure you call the full URL on server-side.

I don't know how we can help you with these informations, make sure you can curl your enpoint from your Docker environment.
