### ISSUE TITLE
Meta title and description not appearing as expected

### ISSUE THREAD

**Issue by reemhamz** [nuxt/nuxt.js#10466]
### Issue
I have set up a meta title and a meta description to show up whenever the site is linked somewhere. However, the information that shows up is my Github repository name for the codebase (instead of the meta title) and the readMe.md instead of the description. A screenshot below shows a preview of what I mean (note that I have a Netlify status badge at the top of my readMe file) found here: https://github.com/reemhamz/portfolio-v2: 

<img width="666" alt="Screen Shot 2022-05-24 at 9 35 05 AM" src="https://user-images.githubusercontent.com/42309026/169920742-3274b08e-258d-4b24-955c-f7d50a4a09c9.png">

I made sure to follow the global settings for setting up meta tags and SEO found here: https://nuxtjs.org/docs/features/meta-tags-seo/#global-settings

### Versions

- nuxt: v2.15.4
- node: v16.13.0

### Steps to reproduce
Paste the site URL (https://reemify.dev/) somewhere to view the meta preview and the janky preview should show up.

Here is the `nuxt.config.js` file where I placed the global meta tags info: https://github.com/reemhamz/portfolio-v2/blob/master/nuxt.config.js#L7 

### What is Expected?
The preview should show what is actually placed in my meta title and meta description seen here: https://github.com/reemhamz/portfolio-v2/blob/master/nuxt.config.js#L7

### What is actually happening?
The meta preview is instead showing my Github repository name (for the codebase) for the meta title and the readMe (of the codebase) for the meta description.

**Comment by manniL** [comment]
You did not set your `og` tags (og:description, og:site_name, og:title) correctly. Thus, the defaults from the [pwa meta module](https://pwa.nuxtjs.org/meta) apply.

Suggestion: Use the PWA meta module to set all default meta tags entirely. [Example](https://github.com/albionstatus/albionstatus-website/blob/main/nuxt.config.ts#L35-L45)
