### ISSUE TITLE
useState is not defined in composables

### ISSUE THREAD

**Issue by does1tmatter** [nuxt/nuxt.js#10475]
useState not auto-importing to composables..  Any ideas? 
Nuxt version "nuxt": "3.0.0-rc.3"

> 500
> useState is not defined
> 
> at Module.default (/D:/front/nuxt/composables/useWallet.js:5:20)
> at setup (/D:/front/nuxt/.nuxt/dist/server/server.mjs:11693:58)
> at _sfc_main.setup (/D:/front/nuxt/.nuxt/dist/server/server.mjs:11776:23)
> at callWithErrorHandling (D:\front\nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
> at setupStatefulComponent (D:\front\nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7027:29)
> at setupComponent (D:\front\nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6982:11)
> at renderComponentVNode (D:\front\nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:198:17)
> at Module.ssrRenderComponent (D:\front\nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:629:12)
> at default (/D:/front/nuxt/.nuxt/dist/server/server.mjs:10834:37)
> at Module. (D:\front\nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:958:13)

**Comment by manniL** [comment]
Hey! This is the repository for Nuxt v 2.x

Feel free to raise the issue in the [nuxt/framework](https://github.com/nuxt/framework) repository instead.
Also, please ensure you add an example so reproducing the error is straightforward ☺️
