### ISSUE TITLE
View page source is not displayed the dynamic route's page content in production.

### ISSUE THREAD

**Issue by Dharati-Mirani** [nuxt/nuxt.js#10499]
### Example:

For example, I am running a project on http://sitename.com. Now if I show the view page source its displays fine. But now I have another page like http://sitename.com/company_name/employee_name and now if I show the view page source then it displays the source of only http://sitename.com. 

### Versions
nuxt: 2.15.8

**Comment by rahulbhadja** [comment]
are you sure it's an SSR application?
