### ISSUE TITLE
`router.base` not appended to href of static assets using `nuxt generate`

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt.js#10498]
### Versions

- nuxt: 2.15.8
- node: v16.14.0

### Reproduction
https://codesandbox.io/s/stoic-borg-d8t7ck?file=/nuxt.config.js

### Steps to reproduce
Create a new Nuxt project from the CLI.
Make these 3 changes to the `nuxt.config.js`
- Add `target: "static"`
- Add `ssr: false`
- Added `router.base: "/t/"` 
(base can be anything)
- Run `yarn run generate`

### What is Expected?
The link to the favicon.ico is not prepended with the `router.base: "/t/"` value.
The link is `/favicon.ico` instead of `/t/favicon.ico`

### What is actually happening?
The link to the favicon.ico should be prepended with `router.base: "/t/"` value.
This prevent site hosted on GitHub pages from having a favicon, apple-touch-icon, webmanifest as none of those get appended the correct `router.base`. All the js file get the prefix appended correctly.

![173462766-4b4ae56d-ebe1-416d-9999-6178403afa3e](https://user-images.githubusercontent.com/17392251/173504966-388b5279-789c-4b78-9f97-df41a2380cad.png)

**Comment by danielroe** [comment]
Unfortunately this is something you will need to handle yourself in Nuxt 2.

**Comment by mrleblanc101** [comment]
I understand the issue more clearly now. 
It seem to be a Nuxt Documentation issue.
Instead of `/img/image.jpg` for static assets just write `img/image.jpg`. Now the path is correct because of the `<base href="/your-base/">` in the HEAD.
Maybe this should just be clarified in the doc ? Because all the exemple on Nuxt.org prepend a useless `/` for static assets which cause confusion.
