### ISSUE TITLE
layout folder default.vue asyncData don't working

### ISSUE THREAD

**Issue by yangjunfocus** [nuxt/nuxt.js#10496]
### Versions

- nuxt: 2.15.8
- node: v14.17.5

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
```
export default {
    name: "default",
    async asyncData({$axios, $config, params}){
      const res = await $axios.$get($config.url + '/News/GetPageList', {
        params: {
          NewsType: 5,
          PageSize: 12,
          PageIndex: params.page || 1,
          Sort: "NewsSort",
          SortType: "Desc"
        }
      });
    },
}

```

### What is Expected?
`asyncData` not working.

**Comment by alouini333** [comment]
Hi @yangjunfocus 
According to the docs the asyncData hook can be used only on page-level components.

Check the docs [here](https://nuxtjs.org/docs/features/data-fetching/).

> This hook can only be used for **page-level components**. Unlike fetch, asyncData cannot access the component instance (this). Instead, it receives [the context ](https://nuxtjs.org/docs/concepts/context-helpers) as its argument. You can use it to fetch some data and Nuxt will automatically shallow merge the returned object with the component data.

I don't think this can be considered as a bug

**Comment by danielroe** [comment]
Also note that you need to return something from your asyncData function.
