### ISSUE TITLE
iview tree is not matching server-rendered content

### ISSUE THREAD

**Issue by StasB93R** [nuxt/nuxt.js#1049]
I did exactly as you have in your docs for plugins.
i have a file named iview.js and inside of there i have.
Im using nuxt/express template

        ` 

          import iView from 'iview'
          import Vue from 'vue'
          import 'iview/dist/styles/iview.css'

         Vue.use(iView)
`

just like u recommend. Next i add that plugin in nuxt.config.js
        `

              plugins: [
              // ssr: false to only include it on client-side
              { src: '~plugins/iview.js', ssr: false }
                ]

`

but it keeps giving me this error 

>  The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

I hope there is a way around it. I tried to import Button from iview manually but i get an error saying
`'Button' is defined but never used  no-unused-vars` but its nonsense because i have `  <Button type="primary">Primary</Button>`

So then it made me think to go to my component and do the following inside of the <script>
`

          import Button from 'iview/src/components/button'
          export default {
            data () {
              return {
                Button
              }
            }
}`

And it started WORKING, right for a few seconds and then i get an error saying this:

> /home/linux/Desktop/test/node_modules/iview/src/components/button/index.js:1
(function (exports, require, module, __filename, __dirname) { import Button from './button.vue';SyntaxError: Unexpected token import

**EDIT:**

in my iview.js i have this

          import Vue from 'vue'
          import iView from 'iview'
          import 'iview/dist/styles/iview.css'
          if (process.BROWSER_BUILD) {
            require('iview')
          }
          Vue.use(iView)

then in my vendors and plugins

           plugins: [{ src: 'plugins/iview.js', ssr: false }]
            vendor: ['axios',  'iview'],

then in my index.vue

          <template>
            <div class="">
              <Button type="primary" @click="modal6 = true">Open modal</Button>
              <Modal
                  v-model="modal6"
                 title="sync"
                  :loading="loading"
                 @on-ok="asyncOK">
                  <p>This is a sync modal</p>
              </Modal>
            </div>
          </template>

          <script>
          export default {
            layout: 'iview',
            data () {
              return {
                modal6: false,
                loading: true
              }
            },
            methods: {
              asyncOK () {
                setTimeout(() => {
                  this.modal6 = false
                }, 2000)
              }
            }

          }
          </script>

and it gives me the following errors

          Mismatching childNodes vs. VNodes:  (5) [VNode, VNode, VNode, VNode, VNode]

          [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by uptownhr** [comment]
I have a feeling this is an issue related to many other libraries that have issues with SSR. From my experience some libraries will import/change the dom just by importing the library. So in your example, i bet you'd see the same issue even if you didn't use the component at all but just imported it somewhere. 

As of now, I don't think there is a solution and you'd have to open a ticket with the library to get this resolved.

**Comment by uptownhr** [comment]
Looked through iview real quick and i saw some things that would cause this. https://github.com/iview/iview/blob/2.0/src/components/loading-bar/loading-bar.js. You'll see additional dom mounts being done. Bad for SSR.

**Comment by StasB93R** [comment]
**Update on the situation:**
Now iview works with

            plugins: [{ src: 'plugins/iview.js', ssr: false }]

Not perfectly of course, there are some issues at the moment but at least it displays the elements.
The problem that i think might be on nuxt.js side is that if u try to enable SSR it gives an error of windows undefined. Your solution https://nuxtjs.org/faq/window-document-undefined/ is not doing anything. So what could it be?

**Comment by uptownhr** [comment]
The window u defined is because the library is dependent on window. I'd go
back to iview and mention it.

**Comment by Phatza** [comment]
Hello @StasB93R @uptownhr ,

It has been solved [#1339](https://github.com/iview/iview/issues/1339), on iView repo.
I tried and it works :)

Hope it helped

**Comment by icarusion** [comment]
We also have a related problem in #1080 when using internationalization, is there somebody can resolve it? thanks.
