### ISSUE TITLE
How to support gzip?

### ISSUE THREAD

**Issue by stevieyu** [nuxt/nuxt.js#105]

**Comment by Atinux** [comment]
Hi @stevieyu 

You can use nuxt.js as a middleware ([see documentation](https://nuxtjs.org/api/nuxt-render)) for express.

And use the [compression](https://github.com/expressjs/compression) middleware to gzip every response.

You can also use [CloudFare](https://www.cloudflare.com) which is free and offer gzip support.

**Comment by Atinux** [comment]
I re-open it, gzip support will be implemented in Nuxt.js to be able to create the fastest web applications possible 🚀

**Comment by OlzhasAlexandrov** [comment]
It would be great, if nuxt only in production produced static gzip files on build.
`$ nuxt build` - the time when gzip files are created, so we could enable static gzip in nginx for example and enjoy it over dynamic creation of gzipped files

**Comment by Atinux** [comment]
That's the strategy I will implment, dynamic gzip creation is a loose of performance.

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out with gzip support ✋

**Comment by kodekrendel** [comment]
@Atinux how to use it? No info in Docs.

**Comment by kodekrendel** [comment]
@Atinux I don't see any compression in my app when run `npm run generate` - https://nuxtjs.org/api/configuration-performance#gzip

How to use it?

**Comment by ausir0726** [comment]
@kodekrendel 

I think that setting is for nuxt.js host server , then it will use compression gzip response file .
If you use static generate file ,
just setting on your web hosting ( like apache .htaccess or nginx config )

I have impression can generate static tar.gz file . but I never use it .
I always set gzip on my cdn server or apache .

**Comment by kodekrendel** [comment]
@ausir0726 I can set nginx for dynamic gzip, but @Atinux just says "That's the strategy I will implment, dynamic gzip creation is a loose of performance." and I agree and looking for that option. So nuxt can gzip files on building stage or not, still don't get what exactly was implemented in 0.10.

**Comment by ausir0726** [comment]
I have see generate static gzip file option on doc before , even I tested it  , but I can't find it anymore ... QQ

**Comment by Atinux** [comment]
@kodekrendel finally it's easier this way and can be disabled.

@ausir0726 for static generation, every CDN or static hosting have gzip support so it's useless to add this option for nuxt, that's why :)

**Comment by kodekrendel** [comment]
@Atinux yeah, but if I host on VPS. I have to zip other way, ok.

So gzip in nuxt working but not for `generate`?

**Comment by OlzhasAlexandrov** [comment]
@kodekrendel @ausir0726  if you are running linux you can do:
`$ cd path/to/.nuxt`
`$ find . -type f ! -name "*.gz" | while read -r x; do gzip -c9 "$x" > "$x.gz"; done'`
- This way you will create a gz copy of every file, leaving original ones `-c`
- `-9` means maximum compression
Just create an alias in .bashrc or .bashprofile and do it with a single word command

**Comment by Atinux** [comment]
@kodekrendel use a service like https://www.cloudflare.com/ which offers gzip supports and more for free.

**Comment by OlzhasAlexandrov** [comment]
@Atinux if you are in a country like Kazakhstan, you are prohibited to host your website outside of that country, ahah. That's why CDN is not always an option

**Comment by Atinux** [comment]
I did not know, thanks for clarifying this up.

This line is pretty awesome BTW @OlzhasAlexandrov 
```bash
find . -type f ! -name "*.gz" | while read -r x; do gzip -c9 "$x" > "$x.gz"; done
```

**Comment by kodekrendel** [comment]
@OlzhasAlexandrov nice, ty. But why should I leave copy? What files my server will serve then? Do I need to configure it specifically (nginx in my case)?

**Comment by kodekrendel** [comment]
This command gzip everyfile In folder. Why should I gzip everything?

**Comment by OlzhasAlexandrov** [comment]
@kodekrendel you need to leave a copy, so if any file can't be served as compressed, it will be served uncompressed to check whether you serve the request through gzip_static, use [strace](https://www.archlinux.org/packages/extra/i686/strace/)

**Comment by kodekrendel** [comment]
That's seems like huge overkill. I am pretty sure that mu nginx doesnt serve gzip copies that I created with command above.

**Comment by kodekrendel** [comment]
I don't understand how to make nginx surve gzip files. Only worked with dynmic gzip.

**Comment by OlzhasAlexandrov** [comment]
I understand that you might think that doing one word command (**having an alias**) is an overkill.
I already explained how to check whether you serve precompressed files. Then, it depends whether you configure your nginx.

**Even if nuxt compresses files on build**, you would still have to do the same: **configure nginx to serve precompressed files**

**Comment by kodekrendel** [comment]
Bad sarcasm. Of course `strace` and get it to work with is overkill. I am not so red-eye for now.
I found NginxHttpGzipStaticModule, but can't read it, since nginx site is always broken (jesus, I am so tired of that. Why in the hell I always get 404 Not Found error on nginx site? Are they crazy? They selling web servers, and can't handle own site).

**Comment by OlzhasAlexandrov** [comment]
It is exactly what we have talked about.
- The NginxHttpGzipStaticModule is enabled by adding `gzip_static on;` to the nginx.conf
- Yes, it takes time to configure, but it is not related to how well nuxt performs. You are serving your domain through nginx with a proxy server - nodejs

**Comment by kodekrendel** [comment]
> Yes, it takes time to configure, but it is not related to how well nuxt performs. You are serving your domain through nginx with a proxy server - nodejs

Why do I need node is I will serve static files that I get from `npm run generate`? What am I missing?

**Comment by ausir0726** [comment]
if you use node server , you can get realtime SSR page for each request ( without setting cache time )

**Comment by kodekrendel** [comment]
I don't need SSR for each request since we talking about static generated site. I guess it's missunderstanding.

**Comment by kodekrendel** [comment]
Ok, seems like `gzip_static on;` working and nginx automaticly picked up gziped versions of files. But I only checked id DevTools (not sure how to check properly). Thanks everyone! Beside using CDN it's cool option if using VPS.

**Comment by ausir0726** [comment]
for my personal opinion .
I like use generate more than start a node server . because .

I can put file on static file hosting , like surge , netlify , google cloud storage , s3 , they have a very good cdn practice and even provide gzip and http2 .

but I need regenerate my project every 1 hour ? 6 hours? 1 day ? ... or every time modified db data ...
if project have 1000+ pages .... use generate maybe not a good option .
start a node server will be a good option. ( but need VPS )

If we can just regenerate we want , that will be nice ....
I have a project with 1000+ product pages , every time I generate , that took me about 10mins .
( customer always want they update product and paste on facebook , boooom~!!! we don't have SSR yet  )
We are consider do we need use run on node server
or release page to netlify ( they provide prerender service ) , cover this error .

**Comment by OlzhasAlexandrov** [comment]
@ausir0726 if you are not limited by the country where to host your website, use the cheapest, one of the most secure, and, probably the fastest method to serve an application that requires a server - AWS Lambda

You [might try this](https://aws.amazon.com/blogs/compute/how-to-turn-node-js-projects-into-aws-lambda-microservices-easily-with-claudiajs/) and then please let me know the result via PM or here

**Comment by ausir0726** [comment]
@OlzhasAlexandrov  thanks .

you mean use Lambda generate static pages ?
I don't know how fast it is . but I think now I block on http request then generate static page .
I guess some reason is generate fetch route is single thread .
like route/a(fetch api) .. route/b(fetch api) ... route/c(fetch api) .....  route/1000(fetch api)
so , it took so long time ....  like npm vs yarn ....

I don't know if use Lambda will be faster , but I will try it ....

**Comment by OlzhasAlexandrov** [comment]
@ausir0726 No, I didn't mean to serve a static website using lambda, it's not for that, please take a look at what lambda does.
I am actually curious and will try to quickly deploy our current wip that way there, give me 30 min

**Comment by ausir0726** [comment]
@OlzhasAlexandrov  thanks.
maybe will very helpful .

**Comment by kodekrendel** [comment]
> If we can just regenerate we want , that will be nice ....

Yes, that would be awesome.

**Comment by OlzhasAlexandrov** [comment]
@ausir0726 my bad, I misunderstood what claudia.js is. It is just a wrapper for some one time services. Server rendered deployment on lambda would be much more complicated. I will put it in my to-do in the future list:D

Static nuxt project with some lambda functions for something like (sending emails, registering a user to a db, etc) is extremely simple on the other hand. You just generate it and add api hooks lambda hooks in your app

**Comment by OlzhasAlexandrov** [comment]
```
methods: {
    sendEmail () {
      axios({
        method: 'post',
        url: 'https://path-to-your-api.amazonaws.com',
        data: this.contactForm
      })
    }
}
```

**Comment by kodekrendel** [comment]
@OlzhasAlexandrov is there some kind of article how simple implement send form with Lambda, like you did on your site? I can't find in Google. Everithing related to NodeJS and serverside.

**Comment by OlzhasAlexandrov** [comment]
@kodekrendel [this one definitely works](http://www.toms-blog.com/post/aws-send-email-with-lambda-and-ses/)

**Comment by kodekrendel** [comment]
@OlzhasAlexandrov tnx!

By the way, `gzip_static on;` doesn't work. Because when I delet original files nginx doesn't serve gzipped. Still don't know how to serve freaking static gzip.

**Comment by kodekrendel** [comment]
> Your question was asked on stackoverflow
Please use google also sometimes:)

This link is useless. nginx doesn't work this way. You can try by yourself. Just delete original file and you'll see 403 Forbidden

**Comment by jazoom** [comment]
For the benefit of others:

It took me a while to work out why Nuxt was using gzip. Apparently it's found in `nuxt.config.js` under `render.gzip` (was previously under `performance.gzip` as mentioned in the release notes linked here), and the default is NOT `0` as the documentation says. Explicitly setting it to `0` disables gzip.

**Comment by tetreault** [comment]
Sorry if i'm missing something obvious but if i'm using Nuxt to generate static sites hosted in S3 behind Cloudfront, how can i accomplish this from this thread?
