### ISSUE TITLE
ASP.net core?

### ISSUE THREAD

**Issue by roboriaan** [nuxt/nuxt.js#1050]
Is there anyway to integrate Nuxt with asp.net core? I'm able to get Vue.js to work using the AspNetCore.SpaServices and adding "app.UseDefaultFiles();" to the pipeline to serve up a static html file and have vue-router take it from there. Looking at nuxt there's no static index.html so I'm getting a 404 of course. Any advise will be greatly appreciated. TIA.

**Comment by Atinux** [comment]
Hi @roboriaan 

Nuxt.js is for server-rendered application using its own node.js server, sadly it cannot be linked to ASP.net.

**Comment by mcquiggd** [comment]
Bit of a necro-comment, but @roboriaan and anyone looking at these technologies - just wanted to point out I have had great success with Vue + Nuxt.js for handling UI, combined with Asp.Net Core WebApi for data and everything else.

_I looked at trying to use .Net Core JavascriptServices as the platform to work with Vue (and before that, React), but in my humble opinion you are far better with web-based UIs in the fast moving JavaScript / Node / WebPack etc universe, with business logic, patterns such as CQRS, large scale integration, workflow etc, handled in the mature and capable .Net world._

Here is an example of how well these can work together, in this case, Vue + Nuxt.js working with ServiceStack (.Net Core) : 

https://github.com/mattjcowan/servicestack-nuxt-example

**Comment by Atinux** [comment]
Awesome @mcquiggd :)

**Comment by acidduck** [comment]
@mcquiggd Would this also be possible using standard .Net Core Identity? Planning to upgrade my old MVC ASP.NET Membership site to a Nuxt.js frontend and .Net Core Identity backend.

**Comment by mcquiggd** [comment]
@acidduck 

Technically I can see no reason why it should not.

Essentially everything is a standard, e.g. Oauth, OpenID, token, so, in theory you could use Identity Server with any stack. 

Indeed a quick Google reveals npm packages for Express (which you can choose to use with Nuxt), to work with Identity Server 3.
https://www.npmjs.com/package/passport-identityserver3
https://www.npmjs.com/package/passport-idsrv3

Plus I would check the quickstarts.

I have ever have time I`ll try to spin up a Container with Identity Server 4 and knock something up.

**Comment by acidduck** [comment]
@mcquiggd 

Thanks, but I was actually thinking about just using the integrated Identity solution for .net core
[https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity](url)

I’m just not sure how to combine it with Nuxt.js?

**Comment by mcquiggd** [comment]
@acidduck 

Ok. Well, again, you are talking about a token provider (in this case a couple of endpoints on the API, with the rest being attributed with `Authorize`. There are a number of articles online about issuing tokens from a WebAPI.

Now, that would cover an SPA fairly simply.

If you want to use SSR, take a look at these thread for starters, regarding the use of a cookie to send the authorisation token to the server.

https://github.com/nuxt/nuxt.js/issues/575

and

https://github.com/nuxt/nuxt.js/issues/2124

**Comment by snrtbnc** [comment]
I think you need to separate your client app (nuxt and node) and web api with .net core. Publish you node server then call .net web api... If you combine with .net web api and nuxt with same project You can face with some  unknown situation even this project work in start point, you cannot guess what will be happen in the feature.
