### ISSUE TITLE
async asyncData not working when page refresh on cpanel

### ISSUE THREAD

**Issue by zadumia911** [nuxt/nuxt.js#10536]
async asyncData({$axios,params}) {
    const response = await $axios.get('/api/v1/product-share/details/'+params.id);
      return {post : response.data.productdetails}
 }

**Comment by danielroe** [comment]
Please raise any issues at https://github.com/nuxt-community/axios-module/. Likely you need to set the correct server-side baseURL for your server setup (port, host).

**Comment by zadumia911** [comment]
Already data has gotten in other page that uses mounted function

**Comment by mahmoudElzanklony** [comment]
hi i finally found a solution 

// register page component
  async fetch({ store }) {
    await store.dispatch('places/countries/getCountriesAction');
  },


store folder 
places/countries.js

export const actions = {
  async getCountriesAction({ state,commit }) {
     return this.$axios('countries').then((e)=>{
      commit('InitializeData',e.data.data)
    });


  }
}

please don't forget return at action 
and it will run correct when refresh page
