### ISSUE TITLE
Using NuxtLink as a Dynamic Component not rendering

### ISSUE THREAD

**Issue by millansingh** [nuxt/nuxt.js#10545]
Hi there.

I am trying to use NuxtLink in Nuxt 3 as a dynamic component. Basically, if I pass in an external link to my component, I want it to render a simple "a" tag, and if I pass in an internal link, I want it to render a NuxtLink. I attempted this using the <component> from Vue 3 but it is rendering out a <nuxtlink> in the HTML, not a NuxtLink vue component.

Here's the code:

`<component :is="openInNewTab ? 'a' : 'NuxtLink'" :href="link" :to="link" class="icon-button" :class="buttonClass" :target="openInNewTab ? '_blank' : ''" :rel="openInNewTab ? 'noopener' : ''">`

The output HTML is <nuxtlink> with all the props, and there are no vue components rendered in the vue dev tools.

Do I need to manually import NuxtLink and reference it in the :is statement? If so, how do I manually import NuxtLink (I can't find this in the docs)?

Thanks!

**Comment by millansingh** [comment]
That works swimmingly thank you!

**Comment by s-fog** [comment]
Please, can u explain what is it?
as () {
  return NuxtLink
}

Where i need to put it?
