### ISSUE TITLE
Layout based transitions

### ISSUE THREAD

**Issue by samburgers** [nuxt/nuxt.js#1054]
Hi, is there any chance we can get access to the page `layout` parameter inside the `from` and `to` object? (For transition control)

**Comment by Atinux** [comment]
You should be able with `to.matched[0].components.default.options.layout` @samburgers 

Example: https://glitch.com/edit/#!/unequaled-goldfish?path=pages/index.vue:11:39

**Comment by samburgers** [comment]
@Atinux , i was just thinking about this some more, and would it be possible to just add a transition property directly to the layout component?
`layouts/blog.vue`

```
export default {
  transition: {
    name: 'layout-blog',
    mode: 'out-in'
  }
}
```

**Comment by Atinux** [comment]
So it would be like the default transition for pages using this layout? @samburgers

**Comment by samburgers** [comment]
I was thinking that would be a good idea, but perhaps it does make more sense to just keep them in the `/pages` templates, as the layout templates are also defined there. Thanks for all the awesome work on this project BTW!

**Comment by Atinux** [comment]
Thanks @samburgers :)

**Comment by PrimozRome** [comment]
Transition between layouts would be a good idea. Currently not working, or I don't know how to set it up

**Comment by davidpmccormick** [comment]
I think I was looking for something like a layout-based transition – is there a way to have _all_ pages use the same transition without adding a `transition` key to each page's .vue file?

**Comment by iamdubx** [comment]
Is it still akward to transition layouts? Where there any updates? My 404 page not transitioned.
