### ISSUE TITLE
Problem between vue-server-runderer and vue versions in nuxt (2.15.8)

### ISSUE THREAD

**Issue by andst3** [nuxt/nuxt.js#10557]
vue-server-renderer was updated to version 2.7.0 on 01/07/2022 but vue remained 2.6.14 and because of this nuxt cannot build the project due to missmatch versions

**Comment by tada5hi** [comment]
@pi0 would be great if you could dump the nuxt version too 😊

**Comment by sameignatovich** [comment]
Agree. Vue 2.7.0 would be great update for nuxt2

**Comment by danielroe** [comment]
This has already been done in https://github.com/nuxt/nuxt.js/pull/10524. To use it before the next release, you can use `nuxt-edge`.

**Comment by andst3** [comment]
> This has already been done in #10524. To use it before the next release, you can use `nuxt-edge`.
but this is fix for nuxt 3

**Comment by danielroe** [comment]
> but this is fix for nuxt 3

I am not sure what you mean.

**Comment by andst3** [comment]
> I am not sure what you mean.
@danielroe I have a problem in nuxt 2.15.8 but you sent me fix for dev branch that have up to date version nuxt

**Comment by danielroe** [comment]
This repository is for Nuxt 2. You can wait until Nuxt 2.16 for any updates, or use the `nuxt-edge` package (which contains the latest Nuxt 2 commits). But honestly, I believe that you simply need to regenerate your lockfile for this upgrade (to Vue 2.7).

**Comment by andst3** [comment]
@danielroe I got it, thanks a lot
