### ISSUE TITLE
Iview and nuxt.js

### ISSUE THREAD

**Issue by StasB93R** [nuxt/nuxt.js#1055]
Is there a way to implement iview in nuxt.js? i keep getting weird errors like the dom is not matching server rendered template, or vnodes are not matching etc.
I have posted the same issue on iview rep, is it a problem on your side or iview?

**Comment by pi0** [comment]
Hi. It seems iView is not well designed to be working with SSR environments. Please see [here](https://nuxtjs.org/faq/window-document-undefined). Also this is dup is #1049.
