### ISSUE TITLE
Nginx server 

### ISSUE THREAD

**Issue by augmen** [nuxt/nuxt.js#1056]
We are trying to develop a web app with vuetjs + next.js. How to include & connect nginx server to your app using nuxt.js ? Please guide

**Comment by Atinux** [comment]
Hi @augmen 

Nuxt.js is a node.js application, by default listening on port `3000`

Please look at https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04#set-up-nginx-as-a-reverse-proxy-server and replace port 8080 by 3000.

**Comment by naihe138** [comment]
@Atinux  how to catch the `_nuxt `folder `.js`file??

````
  location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|js|pdf|txt){
    root /www/blog-admin/production/current/_nuxt;
  }
````

get the  404 error

**Comment by leafiy** [comment]
problem is how to proxy static files like `_nuxt/manifest.js` in dev
