### ISSUE TITLE
objects do not support the find property or method 

### ISSUE THREAD

**Issue by siul230** [nuxt/nuxt.js#1057]
# Hi everyone, 
when I run vue.js aplication with nuxt.js on IE 9+ I get this error  'objects do not support the find property or method ' ,  in other browsers it work well,  someone have any idea ?

![captura](https://user-images.githubusercontent.com/6739844/27990823-a74e2b5a-6428-11e7-8f02-51e168cacfd1.PNG)

**Comment by Atinux** [comment]
Hi @siul230 

Please look at this solution: https://github.com/nuxt/nuxt.js/issues/951#issuecomment-310774898

Also, Nuxt 1.0 will work on IE9+ by default when released.

**Comment by siul230** [comment]
Hi , tanks 
I tryed that but I got de same error
