### ISSUE TITLE
Nuxt 3 RC6 - Cannot create a script tag with innerHTML using nuxt config

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#10588]
### Versions

- nuxt: 3.rc6
- node: n/a

### Reproduction

```
app: {
  head: {
    script: [{
      hid: "gf-script",
      innerHTML: `(function(){var l=document.createElement('link');l.rel="stylesheet";l.href="${url}";document.querySelector("head").appendChild(l);})();`,
    }]  
  }
}
```

### Steps to reproduce
Use the config above

### What is Expected?
Before this would add the content into the <script> tag. Now it is added as an attribute. Unless there is a config or name change that I cannot see in docs then this is a bug.

I am making the google fonts module usable in Nuxt 3 and this seems to be the only thing not working.
https://github.com/nuxt-community/google-fonts-module/issues/67

### What is actually happening?
See above

**Comment by danielroe** [comment]
Use `children`. Also `hid` no longer is used in Nuxt 3.
