### ISSUE TITLE
[nuxt] [request error] __vite_ssr_import_1__ is not defined

### ISSUE THREAD

**Issue by amine-elghazali** [nuxt/nuxt.js#10591]
I have an error when trying to implement FullCalendar in my Nuxt3js project , the error  is : 
[nuxt] [request error] __vite_ssr_import_1__ is not defined  .

I have no clue what I have to do , please some help

**Comment by danielroe** [comment]
Please feel free to raise a new discussion or issue at https://github.com/nuxt/framework, but if you raise an issue make sure to follow the guidelines at http://v3.nuxtjs.org/community/reporting-bugs.

**Comment by amine-elghazali** [comment]
okay thank you so much !
