### ISSUE TITLE
[NuxtJS] Cannot read properties of null (reading 'getRootNode')

### ISSUE THREAD

**Issue by dxgi** [nuxt/nuxt.js#10596]
### Versions

- nuxt: 2.15.8
- node: v16.16.0

### Steps to reproduce
Create and use component
```vue
<template>
    <div>
        <nuxt-link to="/explore">test</nuxt-link>
    </div>
</template>
```

### What is Expected?
I expected it to run without causing any issues.

### What is actually happening?
The ``NuxtLink`` / ``nuxt-link`` is causing an exception ``Uncaught TypeError: Cannot read properties of null (reading 'getRootNode')``

**Comment by danielroe** [comment]
Would you provide a reproduction? You can start from https://stackblitz.com/edit/github-xvb1hm. 🙏

**Comment by dxgi** [comment]
unable to reproduce issue
