### ISSUE TITLE
guard pages with vuex authenticated user

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#106]
Hello,
I'm currently searching how to guard pages within nuxt. I have a vuex in place and after authentication I store the user in $store.state.authUser. 
Is there a best practice how to wait if authUser state is set?
Thanks!

**Comment by Atinux** [comment]
Hi @dohomi 

The middleware (upcoming feature) will let you create rules for rendering specific pages with Nuxt.js, the authenticated pages is a perfect example of using the middleware.

**Comment by dohomi** [comment]
Great news! Any ETA for that release? Cheers

**Comment by Atinux** [comment]
Actually not any ETA but as soon as possible, you can follow our progress here: https://github.com/nuxt/nuxt.js/projects/1

**Comment by jvandenaardweg** [comment]
What about this? https://nuxtjs.org/examples/auth-routes/

**Comment by Atinux** [comment]
The middleware feature is out with the [0.9.8 release](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.8).

**Comment by dohomi** [comment]
Hi @Atinux great news. Could you add a complete example how to make this work? I was reading the docs but still not sure how to persist the authenticated user on server and client side through a server/client session that on page reload the user still logged in. 

Thanks for this great tool!
