### ISSUE TITLE
Hiding env variables from script file after build

### ISSUE THREAD

**Issue by webdozerz** [nuxt/nuxt.js#10606]
### Versions

- nuxt: 2.15.8
- node: v14.18.3
- dotenv: 10.0.0

### Reproduction
<details open>
<summary>Additional Details</summary>
<br>

![Screen of .js file](https://user-images.githubusercontent.com/38782974/181233192-329308f9-cdae-451c-bb82-76d7a69ffe70.png)

</details>

I use `require('dotenv').config()` in nuxt.config.js.
And this
```
modules: [
    '@nuxtjs/dotenv',
  ],
  dotenv: {
    systemvars: true
  },
 env: {
    baseURL: process.env.BASE_URL,
    baseUrlWS: process.env.BASE_URL_WS,
}
```

### Steps to reproduce

- Use env object in nuxt.config.js
- Build the project
- Open the Chrome DevTools
- Open the Network tab
- Look through all the .js files and search for "env:"

### What is Expected?

Hidden from prying eyes env variables

### What is actually happening?
I can get the values of evn variables from the project

![Screen of .js file](https://user-images.githubusercontent.com/38782974/181233192-329308f9-cdae-451c-bb82-76d7a69ffe70.png)

**Comment by danielroe** [comment]
Check out https://nuxtjs.org/docs/configuration-glossary/configuration-env#automatic-injection-of-environment-variables for an explanation of why using `.env` means these values are encoded in your JS. Consider migrating to `runtimeConfig`, which allows private config to remain on your server. (Of course, if you need these values on client-side, they will be accessible to your end user.)
