### ISSUE TITLE
Bricked navigation in the presence of comments in destination layout files

### ISSUE THREAD

**Issue by kpdemetriou** [nuxt/nuxt.js#10602]
### Versions

- nuxt: 3.0.0-rc.5
- node: 16.15.1

### Steps to reproduce

- Create a custom layout file with an HTML comment as a top-level element, followed by `<div><slot /></div>`.
- Use the layout file in a dummy page with any content using `definePageMeta`.
- Attempt to navigate to said dummy page from any other page

### What is Expected?

- That the content of the dummy page is rendered, wrapped by the custom layout.

### What is actually happening?

- A blank page is rendered.

**Comment by danielroe** [comment]
Comments count as nodes. Layouts and pages need a single root node for transitions to work.

**Comment by kpdemetriou** [comment]
@danielroe Absolutely, I understand why this is happening and it's a trivial fix. Nevertheless I'm reasonably confident other users will run into this with complex pages and layouts. The cause (as in my case) will not be obvious before a few rounds of trial and error. So while technically this might not be a bug, from my prespective it's definitely a DX footgun that Nuxt may want to address in accordance with the principle of least astonishment.

**Comment by danielroe** [comment]
Agreed. We have notes in the docs about this very situation (comments in the DOM), and there is a pending PR to warn users in dev mode if we detect multiple nodes in a layout/page component.
