### ISSUE TITLE
i18n is not working?

### ISSUE THREAD

**Issue by cdoneshot** [nuxt/nuxt.js#1061]
i want to add i18n to my project ,but it is not working .
this is ouput in console
![image](https://user-images.githubusercontent.com/20412044/28008857-b9a05896-658b-11e7-99a9-1b6f69dc890a.png)
this key is existed in language json
this is my config.
middleware/i18n.js
![image](https://user-images.githubusercontent.com/20412044/28008848-b143a28e-658b-11e7-8c21-d114d4817116.png)
nuxt.config.js
![image](https://user-images.githubusercontent.com/20412044/28008723-48a4f6ec-658b-11e7-87c4-fdd82b0359cb.png)
plugins/i18n.js
![image](https://user-images.githubusercontent.com/20412044/28008757-617ad6c8-658b-11e7-86d5-d54d166d9d5f.png)
store/index.js
![image](https://user-images.githubusercontent.com/20412044/28008775-7048e0f0-658b-11e7-9944-865f16a72855.png)

**Comment by kazupon** [comment]
You need to create `VueI18n` instance in `plugins/i18n.js`
