### ISSUE TITLE
Nuxt rebuild is taking too long (Feathersjs)

### ISSUE THREAD

**Issue by alexisohayon** [nuxt/nuxt.js#1062]
I'm not sure if it is a problem with Nuxt or Feathers, but when I modify something on the server side it launches a rebuild that takes 30s and is very annoying for developping. 
I'm not having this issue with the client part, which takes 4s max to rebuild when a change is detected. I think it's because the server folder launches a full build when a change happens, and I don't know how to parameter this.
If you have any idea, it would help me a lot! :)

**Comment by alexisohayon** [comment]
<img width="205" alt="capture d ecran 2017-07-10 a 14 39 22" src="https://user-images.githubusercontent.com/781456/28018444-a4bb39cc-657d-11e7-8a74-2ce84e605d6c.png">

This is the arborescence of my project, tell me if you need to see more specifically.

**Comment by pi0** [comment]
Hi. Would you please tell which version of nuxt currently using? Also `nuxt build --analyze` would help finding big parts that take time.

**Comment by alexisohayon** [comment]
It's the 0.10.7 version
I'll check the analyze also (but what I dont understand is why it's launching a full rebuild when changing server parts, and not when changing client parts...). The changes to the server should'nt affect Nuxt anyway?

**Comment by pi0** [comment]
Unfortunately, there is a full process restart required when changing code so Nuxt should do a rebuild. You may use two separate processes and proxy pass API requests from Nuxt to API no magic can make it faster when are on same process :)

**Comment by pi0** [comment]
PS: strongly suggest considering to upgrade upcoming `1.0.0-rc` versions of nuxt. It introduces web pack 3 for faster builds and a modular system to easily adding proxy functionality. Feathers templates will be updated soon for 1.0.

**Comment by alexisohayon** [comment]
Ok, I think have found some parts that make it long to reload, maybe you have an idea on how to optimize it: 

`    plugins: [
      new webpack.LoaderOptionsPlugin({ 
        options: { 
          stylus: { 
            preferPathResolver: 'webpack', 
            import: ['~nib/lib/nib/index.styl', '~assets/styl/mixins.styl', '~assets/styl/flexbox-grid/main'] 
          }, context: '/' 
        } 
      }),`

**Comment by alexisohayon** [comment]
👍 Ok, is there any migration to do between 0.10.x and 1.0?

**Comment by pi0** [comment]
The only way i think is precompiling common parts and adding them as plain css so rebuilds go faster.

> is there any migration to do between 0.10.x and 1.0?

Sure! Full Guide will be provided after release :)

**Comment by alexisohayon** [comment]
I updated to 1.0.0-alpha.4 which seems to be a lot faster indeed :)
But I've got one problem ->
<img width="496" alt="capture d ecran 2017-07-10 a 16 04 25" src="https://user-images.githubusercontent.com/781456/28021892-b4a81312-6589-11e7-9dbb-5116983a2e20.png">

If it's not ready yet, I'll just go with the pre-compiling ;) Thanks a lot!
