### ISSUE TITLE
Route params not persistent in error layout

### ISSUE THREAD

**Issue by Lacroute** [nuxt/nuxt.js#1063]
Hi,

I can't use `<nuxt-link :to="{name: 'lang'}">Home page</nuxt-link>` To redirect to my translated home page.

Error message from the console: `[vue-router] missing param for named route "lang": Expected "lang" to be defined`

`pages` directory structure:
```
pages/
--| _lang/
-----| index.vue
-----| about.vue
```
Error layout from [the doc](https://nuxtjs.org/guide/views/#error-page).

In the error layout, `route.params` is an empty object, but in others, it contains the `lang` entry. It's like the error is triggered before the params are injected. The router still have access to the named routes, `this.$router.options.routes` contains 

```
[{
component: function _782fd8ab()
name: "lang"
path: "/:lang"
}, ...]
```

It's not that bad because I can get the current locale by using the store but it could be an improvement.

**Comment by alexchopin** [comment]
Fixed in the last release

**Comment by sunsmeil** [comment]
I have the same problem.Fixed to which version?

**Comment by Lacroute** [comment]
The rc11 https://github.com/nuxt/nuxt.js/releases
