### ISSUE TITLE
Dot "." not being allowed in routes in production mode

### ISSUE THREAD

**Issue by magroski** [nuxt/nuxt.js#10635]
### Versions

- nuxt: v2.15.8 
- node: v16.16.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
</details>

### Steps to reproduce

1 - Define a named dynamic route
2 - Try to pass a parameter that contains one or multiple dots

Go to here: https://codesandbox.io/s/quizzical-wind-82tdc0?file=/package.json
And visit https://82tdc0.sse.codesandbox.io/home/i_am_a_token
Then visit https://82tdc0.sse.codesandbox.io/home/i.am.a.token

This only happens when using `nuxt start`, the dev environment has a different behavior.

Go to here: https://codesandbox.io/s/affectionate-cartwright-doz7lx?file=/package.json (this one uses `nuxt dev` instead of `nuxt start`)
And visit https://doz7lx.sse.codesandbox.io/home/this_is_token
Then visit https://doz7lx.sse.codesandbox.io/home/this.is.token

### What is Expected?

1 - To have consistent behavior between dev and production servers
2 - RFC 3986 path compliance (ie: accept dot as valid characters). See https://www.rfc-editor.org/rfc/rfc3986#section-3.3

### What is actually happening?

When running in production mode `nuxt start` routes can't contain dot "." characters

**Comment by danielroe** [comment]
This is caused by serve placeholder behaviour, which you can turn off. See https://github.com/nuxt/nuxt.js/issues/9241#issuecomment-832663696.

**Comment by magroski** [comment]
@danielroe 
Thanks for the quick reply, but I'm not trying to serve static files, I'm trying to pass JWT tokens to the URL, example:

 `/confirm/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCpbyIsImV4cCI6MTY2MDE1Njc3N30.cy51iVvyWrkH1`

What's the configuration I should use to allow this?

I've tried the configurations below:

```js
render: {
    fallback: {
      static: {
        handlers: {
          default: false
        }
      }
    }
  }
```

```js
render: {
    fallback: {
      static: {
        handlers: false
      }
    }
  }
```

```js
render: {
    fallback: {
      static: {
        handlers: {
          default: null
        }
      }
    }
  }
```

```js
render: {
    fallback: {
      static: {
        handlers: null
      }
    }
  }
```

and still got the same error.

Can you provide a fork of this code: https://codesandbox.io/s/magical-merkle-pz446c?file=/nuxt.config.js, where this path `/home/xxx.yyy.zzz` works?

**Comment by danielroe** [comment]
Looking at the reproduction, you are building a static app and serving the static files using nuxt. (FYI, this is only intended as a dev preview, not for production.) Instead, you will need to ensure that whatever CDN or web server you are using to serve your static files in production, also responds to any 404s with your 200.html.

Here's a working CSB: https://codesandbox.io/s/naughty-khorana-mso9ck?file=/nuxt.config.js.
