### ISSUE TITLE
Cannot start nuxt:  Cannot find any nuxt version from E:\Codes

### ISSUE THREAD

**Issue by dotkiro** [nuxt/nuxt.js#10637]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by dotkiro** [comment]
node -v
v16.15.1

**Comment by dotkiro** [comment]
npm -v
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.11.0

**Comment by dotkiro** [comment]
npm list
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
ifun.com@ E:\Codes\ifun.com
├── less@4.1.3
├── nuxt@3.0.0-rc.6
├── postcss-px-to-viewport-8-plugin@1.1.5
├── postcss-px-to-viewport@1.1.1
├── swiper@8.3.2
└── vue-i18n@9.2.2

**Comment by danielroe** [comment]
Would you raise an issue at https://github.com/nuxt/framework/issues/ with a reproduction? 🙏
