### ISSUE TITLE
Method after nuxt.render not excute

### ISSUE THREAD

**Issue by zxqian1991** [nuxt/nuxt.js#1066]
as i use nuxt in the koa program like this:
```javascript
console.log("before render");
await nuxt.render(ctx.req, ctx.res);
console.log("render end");
```
if i request the static file,only print the `before render`，but no see the `render end`.
can any one tell me what happened in the nuxt.render?
![image](https://user-images.githubusercontent.com/11419268/28048914-84b33ae0-6626-11e7-85ed-f597741cc96a.png)
![image](https://user-images.githubusercontent.com/11419268/28048960-cb7c4854-6626-11e7-88aa-a700ad077017.png)

**Comment by zxqian1991** [comment]
i may know the reason,i try a function like this
```javascript
async function render(){
    return new Promise((resolve,reject)=>{
        setTimeout(()=>{
            console.log("end");
        })
    })
};
async function run(){
    console.log("before render");
    await render();
    console.log("after render");
};
run();
```
The Result like this:
![image](https://user-images.githubusercontent.com/11419268/28049190-382049b4-6628-11e7-9e36-392d76700552.png)
as we can see,the `after render` is missing.
so,it may be that the nuxt not resolve the `async function` when handling the static file。
but why not ?

**Comment by AngelMunoz** [comment]
I think it has to do with the fact that you never resolve your promise in the example you provided
```js
async function render(){
    return new Promise((resolve,reject)=>{
        setTimeout(()=>{
            // try resolving the promise 
            return resolve(console.log("end"));
        })
    })
};
async function run(){
    console.log("before render");
    await render();
    console.log("after render");
};
run();
```
i think that should work

**Comment by zxqian1991** [comment]
yes,i know it, i just do it to show the problem the nuxt has.

**Comment by AngelMunoz** [comment]
noted, I was checking the [koa starter template](https://github.com/nuxt-community/koa-template/blob/master/template/server/index.js)
index and they got different stuff inside an async function called start
```js
 const nuxt = await new Nuxt(config)

 // using middleware
  app.use(async (ctx, next) => {
  ctx.status = 200 // koa defaults to 404 when it sees that status is unset
    await nuxt.render(ctx.req, ctx.res)  // this is inside an `app.use()`
  })
```
perhaps you are not using nuxt.render in the middleware context?

**Comment by alexchopin** [comment]
Related to [koa template](https://github.com/nuxt-community/koa-template)
