### ISSUE TITLE
*env in ./node_modules/xxx error

### ISSUE THREAD

**Issue by otary** [nuxt/nuxt.js#10665]
### Versions

- nuxt:  2.15.6
- node: v10.16.3

### Reproduction

simple link：
https://codesandbox.io/s/wonderful-edison-isel1r?file=/pages/index.vue

### What is actually happening?

```
These dependencies were not found:                    friendly-errors 08:13:08
                                                      friendly-errors 08:13:08
* env in ./node_modules/fonteditor-core/woff2/woff2.wasm
* global in ./node_modules/fonteditor-core/woff2/woff2.wasm
                                                      friendly-errors 08:13:08
To install them, you can run: npm install --save env global

````

I use the vue-cli project and the operation is normal. Does nuxt need to add additional dependencies?

**Comment by nieyuyao** [comment]
This is because there are two files `woff2.js` and `woff2.wasm`, but webpack chooses `woff2.wasm`. Should `.js` be preferred? This just requires modifying `resolve.extensions`. I can submit a PR if ok.😁
