### ISSUE TITLE
how to limit computed property only be computed on client?

### ISSUE THREAD

**Issue by cdoneshot** [nuxt/nuxt.js#1068]
can i use process.browser?
like this:
`export default{
   computed:{
     somestate(){
    if(process.browser){
    ....
   }
}
   }
}`

**Comment by veresnikov** [comment]
Probably you can try this:

if (process.BROWSER_BUILD) {
 ...
}

**Comment by cdoneshot** [comment]
> if (process.BROWSER_BUILD) { ... }
same as process.browser

**Comment by cdoneshot** [comment]
> if (process.BROWSER_BUILD) { ... }

    same as process.browser

**Comment by alexchopin** [comment]
@cdoneshot can you explain more why you need computed property only be computed on client?

**Comment by alexchopin** [comment]
Btw, in you want to set computed functions only triggered on the client-side you can do this:
```js
let c = {}
if (process.browser) {
  c.somestate = function () {
    return 'hello world'
  }
}

export default {
  computed: c
}
```

**Comment by cdoneshot** [comment]
@alexchopin 
I want the metadata to be retrieved at the server, and and the userdata needs to be initiated by the client on ajax .The computed property should be computed when metadata and userdata all available .

**Comment by alexchopin** [comment]
Have you tried to use `asyncData` or `fetch` to initiated your data?

**Comment by cdoneshot** [comment]
> Have you tried to use asyncData or fetch to initiated your data?

my code like this. @alexchopin 

```javascript
 export default{
    // matadata
    asyncData({params}){
      return axios.get(`https://my-api/metadata/${params.id}`)
        .then(res => {
          return {
            metadata: res.data
          }
        })
    },
    mounted(){
     axios.get(`https://my-api/userdata/${user.id}`)
          .then((res) => {
             this.userdata = res.data
         })
    },
    computed: {
      status(){
           /*
            some logic 
            need this.metadata and this.userdata
            it throw an exception when status be computed on the server side
            because  i attempted to access userdata's property
          */
        }
      }
}
```

**Comment by alexchopin** [comment]
@cdoneshot that's better to understand with code snippet :)
Why do you have to call userdata API on the client only?

**Comment by cdoneshot** [comment]
When different users open the same url, I would like to get directly from cdn with metadata pages, but the user data is not the same, need to get from the client through ajax. @alexchopin

**Comment by cdoneshot** [comment]
If the user id attached to the url, cdn is useless

**Comment by alexchopin** [comment]
Ok I see, where comes from `user.id` variable?

**Comment by cdoneshot** [comment]
> Ok I see, where comes from user.id variable?

this page in an app webview, when component mounted ,i send a message to native app,app will send useid to me by call a function


like this:
```javascript
const post2native = (action, type, data) => {
  let message = {
    action: action,
    type: type,
    data: data
  }
  let messageString = JSON.stringify(message)
  try {
    window.webkit.messageHandlers.callbackHandler.postMessage(messageString)
}

export default{
  mounted(){
     post2native("xxxx","xxxxxx",{})

    //this function will be called by native app
     window.somecallback = (userid)=>{
          axios.get(`https://my-api/userdata/${userid}`)
          .then((res) => {
             this.userdata = res.data
         })
    }
  }
}
```

**Comment by alexchopin** [comment]
Vue.js is executed on the server side and we can not disable it.
The only solution is to set a default value for the computed property which doesn't use userdata when it's triggered on the server side.

**Comment by cdoneshot** [comment]
> Vue.js is executed on the server side and we can not disable it.
The only solution is to set a default value for the computed property which doesn't use userdata when it's triggered on the server side.

ok tks.  :smile:
