### ISSUE TITLE
v-html causing static site generation errors

### ISSUE THREAD

**Issue by ben-basten** [nuxt/nuxt.js#10695]
### Versions

- nuxt: v2.15.8
- node: v16.15.1

### Reproduction

https://github.com/ben-basten/nuxt-app

<details open>
<summary>Additional Details</summary>
<br>
Built a fresh Nuxt app with create-nuxt-app:
<pre>npx create-nuxt-app nuxt-app</pre>
Made one small change - using v-html directive to render out an HTML string. The string contains an anchor tag with a relative href attribute (see <a href="https://github.com/ben-basten/nuxt-app/blob/main/pages/index.vue">pages/index.vue</a>).
</details>

### Steps to reproduce

1. `npm install`
2. `npm run generate`

### What is Expected?

Nuxt only generates static content for the "/" route.

### What is actually happening?

Nuxt is additionally attempting to statically generate a "/relative/path/to/website" route, with the following error:

`ERROR  Error generating route "/relative/path/to/website": This page could not be found`

This is not an issue when the anchor tag that is being rendered with `v-html` uses an absolute `href` attribute.

**Comment by danielroe** [comment]
You can manually exclude any routes you do not want the crawler to follow: https://nuxtjs.org/docs/configuration-glossary/configuration-generate#exclude

**Comment by ben-basten** [comment]
@danielroe Good to know, that's a good quick fix for now.

Curious about the root cause - why is HTML that is being rendered with the v-html directive being added to the list of generated routes in the first place? My app uses an HTML string from a service, so the data is constantly changing and I can't exclude every possible route down the road.

**Comment by danielroe** [comment]
Nuxt inspects the generated HTML to discover the routes to crawl. This is helpful for dynamic sites where the list is not deducible from the files in `pages`. You can also turn the crawler off and pass a list of routes to generate instead.

**Comment by ben-basten** [comment]
That makes sense. Thanks for the help @danielroe!
