### ISSUE TITLE
The configuration `build.html.minify` does not work

### ISSUE THREAD

**Issue by kimyvgy** [nuxt/nuxt.js#10696]
### Versions

- nuxt: v2.15.8
- node: v12.18.4

### Reproduction

The configuration `build.html.minify` does not work.

### Steps to reproduce

- Add `build.html.minify` to `nuxt.config.js`:
```
    html: {
        minify: {
            collapseBooleanAttributes: true,
            decodeEntities: true,
            minifyCSS: true,
            minifyJS: true,
            processConditionalComments: true,
            removeEmptyAttributes: true,
            removeRedundantAttributes: true,
            trimCustomFragments: true,
            useShortDoctype: true,
            removeOptionalTags: false,
            keepClosingSlash: true,
        },
    },
```
- Run `npm run build & npm run start`
- View source of page: The meta tags don't keep closing slash:
```html
# result:
<meta data-n-head="ssr" data-hid="og:title" property="og:title" content="Untitled">

# expect:
<meta data-n-head="ssr" data-hid="og:title" property="og:title" content="Untitled" />
```

### What is Expected?

```
# expect:
<meta data-n-head="ssr" data-hid="og:title" property="og:title" content="Untitled" />
```

### What is actually happening?

The configuration `build.html.minify` does not work.

**Comment by danielroe** [comment]
Off the top of my head, I don't think the html _source_ has closing slashes, so it can't keep them. It's not going to insert them where they don't already exist.
