### ISSUE TITLE
Procedure could not be found (Redistributable issue?)

### ISSUE THREAD

**Issue by fttx** [nuxt/nuxt.js#10699]
### Versions

- 64-bit Windows 8.1
- nutjs: ^2.2.0
- Redistributable seems to be installed but it's the x86 version. Maybe this is the cause of the issue

### Reproduction

![image](https://user-images.githubusercontent.com/5663423/189380221-a52b4b28-f5f9-49f0-b34f-2344518aa3f3.png)

**Comment by danielroe** [comment]
This does not seem related to nuxt.

**Comment by fttx** [comment]
But if you at the last line it's coming from nutjs.
I had the user install an older version of my app that wasn't including nutjs and it is able to start it.
I guess nutjs is trying to load the installed redistributable module, but it fails since it's for the wrong architecture

**Comment by danielroe** [comment]
That's not the same as Nu**x**t 😊
