### ISSUE TITLE
Internationalization with nuxt.js

### ISSUE THREAD

**Issue by gary149** [nuxt/nuxt.js#107]
Did someone made a multi-languages app? How did you manage the internationalization? plugin or just with an async call in the data function?

**Comment by Atinux** [comment]
Hi @gary149 

This is planned to make an example when the middleware feature will be released.

**Comment by koddr** [comment]
Very need Nuxt.js multi-languages feature on the box 👍

**Comment by Atinux** [comment]
The i18n example is out: https://github.com/nuxt/nuxt.js/tree/master/examples/i18n

Demo: http://i18n.nuxtjs.org/

As seen in #234, `vue-i18n` is not ready for the SSR, but with the nuxt example, anybody can create its own plugin for nuxt.js :)

**Comment by koddr** [comment]
@Atinux demo link is broken (502 An error occured with your deployment).

**Comment by Atinux** [comment]
@koddr it's fixed thank you for spotting it

**Comment by demyan1411** [comment]
Hello, is it right if I want to localize with html tags do this: div(v-html='$t("home.title")') ?

**Comment by Atinux** [comment]
Try to use a computed property instead @demyan1411

**Comment by demyan1411** [comment]
Can you please show how computed properties can help me.

And after npm run generate I haven't got html http://prnt.sc/espzpo
how can i get it?

**Comment by Atinux** [comment]
Actually i18n example does not work with `nuxt generate` @demyan1411

**Comment by dohomi** [comment]
Maybe its possible to make use of the new https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0 . It supports now SSR and might be a good fit into the `NUXT` ecosystem?

**Comment by Atinux** [comment]
I will try it soon @dohomi

**Comment by andrade1379** [comment]
I was wondering how one would implement the language switch when there is more than just two languages to toggle between?

In the example here: [https://nuxtjs.org/examples/i18n](url)
```
<nuxt-link class="Header__Link" v-if="$i18n.locale === 'en'" :to="`/fr` + $route.fullPath" active-class="none" exact>
            {{ $t('links.french') }}
          </nuxt-link>
          <nuxt-link class="Header__Link" v-else :to="$route.fullPath.replace(/^\/[^\/]+/, '')" active-class="none" exact>
            {{ $t('links.english') }}
          </nuxt-link>
```

I have for example 6 languages I'd like to toggle between.

**Comment by sudhir600** [comment]
@koddr 
in i18n example, the language code is derived from local storage. Let's say my users have a drop-down to choose a language (`note- I don't want to append anything in url like?locale=fr`)  
when language chosen, either i will save in LocalStorage or send to the server (PHP, saved there in session).  But, I don't want 2nd option bcz i am dealing with 3rd party api's. so no own server there for sessions. 

Now  if my data is saved in LS, then how I will replace `locale: store.state.locale,` to` locale: localStorage.getItem('locale')`. 

While middleware executes, there is no client right ? 
so we can't access LS. then what is the alternate. 
Please suggest.

**Comment by gitzhaochen** [comment]
@koddr i got the same problem , i want get locale from  localstorage when reload page and fixed like this
```
export default ({ app, store }) => {
    // Set i18n instance on app
    // This way we can use it in middleware and pages asyncData/fetch
    let locale=''
    if(process.browser){
        locale=localStorage.tokenup_lang||navigator.language
    }
    app.i18n = new VueI18n({
        locale: locale || store.state.locale,
        fallbackLocale: 'zh',
        messages: {
            zh,
            en
        }
    })

    app.i18n.path = (link) => {
        if (app.i18n.locale === app.i18n.fallbackLocale) {
            return `/${link}`
        }

        return `/${app.i18n.locale}/${link}`
    }
}
```
