### ISSUE TITLE
Some questions about publicPath and CDN and generate

### ISSUE THREAD

**Issue by falstack** [nuxt/nuxt.js#1070]
Hello guys，i would like to ask some questions：

1：I can already configure the publicPath for the static file CDN，But my CDN is private，So how do i configure my CDN accessKey and secretKey ...etc?

2：I have been able to static my site use `generate`，But my site is similar to the shop, and I put the page static, so how do I watch backend API response changes to automatically run`generate`？

3：Based on the second point，how do I generate a specific page, not `npm run generate (*)`

This is the trouble I have recently encountered with Nuxt.js

Nuxt.js is awesome，i love it！

**Comment by bayssmekanique** [comment]
Some of these questions are little hard to understand, so could you perhaps clarify a few things:

1) How does you CDN expect the access key?  Is it looking for a URI query string or a header token?

2) To resolve this you will need to build a simple webhook or file watcher task which gets triggered by whatever backend event triggers a rebuild.  This is really outside the scope of this project and there are MANY solutions depending on your environment.  Ultimately, you will want to avoid rerendering the site for content updates.  It is very expensive (in the sense that you will be constantly missing the cache) and the better approach would be to build an application that can pull that updated content into the page at each load or use the precache module to pull that content ahead of time.  This prevents you from constantly making requests for large JS files and allows you utilize longer TTL caches for those heavy files.

3) I do not believe you will be able to build a single page in a vacuum like you are wanting to do using the static site generator.  Webpack needs the full site context, so while only one page's content might change, that pages hash will change and need to be updated in other locations in other files in order for the site to work correctly.  (Again, this makes a single page change fairly expensive and to be avoided if at all possible.)

**Comment by falstack** [comment]
@bayssmekanique 

Thank you very much for your answer！

About question 1：
I want to send JS resources to my private CDN, it needs to get a token from the API, need to put this token into the form of the token field, like this：
```html
<form method="post" action="http://upload.qiniu.com/"
 enctype="multipart/form-data">
  <input name="token" type="hidden" value="<upload_token>">
  <input name="file" type="file" />
</form>
```
But in the webpack, I hope to be able to achieve when the `npm run build` or `npm run generate` to provide me with a callback, I can handle it in nuxt.config.js, and then through a plugin webpack upload these files to my CDN。

On question 2 and question 3：
I think so, when the npm run generate implementation, nuxt will first get to the page asyncData, and then generate HTML files, this time can be asyncData cache to a file, when the npm run generate time, I will pass Callback will send all files (*) in the dist directory to my CDN (different bucket), and then I will specify a polling time watch this file asyncData value and the difference between the value of the cache, so I can know Whether this particular file requires regenerate, assuming that the file is / post / 1, then I will callback / post / 1 corresponding to the static file uploaded to my CDN.

So the key is to cache asyncData, and then polling to do contrast, and through the callback way to tell me how to do, right?
Just like this:
```javascript
// cache file：（unzip）
{
     // other page asyncData
     "user": "...",
     "post": {
        "1": {
            "content":"xxx",
            "title": "xxxx",
            "count_visit", "xxxx"
        },
        "2": {
            "content":"yyy",
            "title": "yyyy",
            "count_visit", "yyyy"
        },
        // ..... and more
    }
}
```
```javascript
// watcher config file
{
    "user": {
        "ttl": 86400
    },
    "post": {
        "ttl": 3600,
       // and more config
    },
    // ... and more
}
```
```javascript
// nuxt.config.js
{
    generate (filepath, isHTML) {
       // then....
    } 
}
```

**Comment by bayssmekanique** [comment]
Ok, I understand a bit more now.  You are wanting to setup automatic deployment to a CDN and create a  hook to run the static site generation.  I certainly think this project is capable of handling that, but it's going to require building a server or serverless-function that will get triggered on changes and run the build.  Like I said previously, you are going to have to rerun the entire generate function for each rebuild.  Not all the files will change, but typically a few will change even if you only make changes to one source file.

I think that an SSR setup behind a caching CDN (like AWS's CloudFront) would be the better way to go for what you are trying to do.  You would be able to leverage the [axios](https://github.com/nuxt-community/modules/tree/master/modules/axios) library so you'd be able to query prior to page requests and cache the page afterward rather than building in hooks.

**Comment by falstack** [comment]
@bayssmekanique 

Thank you very much for the answer, I have already understood what you mean by using koa2 and the cache is a good choice and thanks again!

**Comment by falstack** [comment]
@bayssmekanique 

In Nuxt.js guide page about generate:

We can go further by thinking of an e-commerce web application made with nuxt generate and hosted on a CDN, and every time a product is out of stock or back in stock, we regenerate the web app. But if the user navigates through the web app in the meantime, it will be up to date thanks to the API calls made to the e-commerce API. No need to have multiple instances of a server + a cache anymore!

it can be possible?

**Comment by bayssmekanique** [comment]
Yes, it's certainly possible but you will still need at least one server to run the generator (or a serverless function like an AWS Lambda with API Gateway).  Really it comes down to how elaborate you want to get with your Ops model. Look at [https://nuxtjs.org/api/configuration-generate/](https://nuxtjs.org/api/configuration-generate/) and [https://nuxtjs.org/examples/async-data](https://nuxtjs.org/examples/async-data) for inspiration.

**Comment by falstack** [comment]
@bayssmekanique 

Yes, I fully understand what you mean, sorry for my statement is not correct, so you do not understand what I want to express.

I have used `npm run generate` to static all my pages, but the problem I am experiencing now is how to listen to one of the many pages of the data changes, and thus only generate this one page. Just this one, not all.

can i do it?

**Comment by bayssmekanique** [comment]
No, you can't just run generate on a single page.

**Comment by falstack** [comment]
@bayssmekanique 
It's i need

and watch backend API response change

**Comment by rancongjie** [comment]
@falstack  老铁  ，七牛云  dist 上传 最后解决了吗？ 是每次发布后手动去对象储存上传吗？

**Comment by falstack** [comment]
@rancongjie 不是的，我已经不在使用 Nuxt.js 了，虽然它的确很优秀提供了非常多的方便，如果你要上传 dist 目录下的东西到 七牛云，你可以参考这个插件：https://github.com/longtian/qiniu-webpack-plugin

**Comment by rancongjie** [comment]
@falstack  谢谢，祝好

**Comment by qq510846** [comment]
> 优秀提供了非常多的方便，如果你要上传 dist 目录下的东西到 七牛云，你可以参考

您好，我也在用 七牛云 在 nuxt 上，碰到一个问题就是没有办法在 publicPath 上使用 [hash]，会报下面错误：
ERROR in chunk runtime [entry]
[chunkhash].js
Cannot use [chunkhash] or [contenthash] for chunk in '[chunkhash].js' (use [hash] instead)

你是怎么配置的呢？可以分享一下你的配置文件吗？谢谢 ~

**Comment by qq510846** [comment]
> @rancongjie 不是的，我已经不在使用 Nuxt.js 了，虽然它的确很优秀提供了非常多的方便，如果你要上传 dist 目录下的东西到 七牛云，你可以参考这个插件：https://github.com/longtian/qiniu-webpack-plugin

请教一下，在 Nuxt 里面使用，如何配置？ publicPath: 'http://cdn.xx.com/[hash]/' 这个带上 [hash] 会报错，不知道是什么原因

**Comment by KennanChan** [comment]
@qq510846 看你需不需要hash了，我这儿用阿里云OSS的，publicPath用的“OSS路径+项目版本“，开发完习惯更新一下项目版本号，项目内写一个小工具把dist下的所有文件上传到publicPath就行了
