### ISSUE TITLE
Fetch Data after navigation

### ISSUE THREAD

**Issue by KonstantinVlasov** [nuxt/nuxt.js#1071]
Hello, guys!

As mentioned in the docs, `asyncData` calls before loading the component and this is what we expect for SSR. But for better UX I want to fetch data after navigation for client-side navigation.

Is there a simple way to fetch data before component loading for server-side and after component loading for client-side?
Is anyone faced with this problem?

Sorry if it's duplicate, can't find anything similar

**Comment by stursby** [comment]
@KonstantinVlasov I think you can do something like this...

```js
<script>
import axios from 'axios'

export default {
  data() {
    return {
      users: null
    }
  },

  asyncData({ isServer }) {
    if (isServer) {
      console.log('server fetch')
      return axios.get('https://jsonplaceholder.typicode.com/users')
      .then((res) => {
        return { users: res.data }
      })
    }
  },

  mounted() {
    if (!this.users) {
      axios.get('https://jsonplaceholder.typicode.com/users')
      .then((res) => {
        console.log('client fetch');
        this.users = res.data
      })
    }
  }
}
</script>
```

**Comment by awronski** [comment]
You can use ```mounted``` for the client side fetching data

https://nuxtjs.org/faq/async-data-components/

On Tue, Jul 11, 2017 at 7:00 PM, Konstantin Vlasov <notifications@github.com

**Comment by adrianoresende** [comment]
Is this code a good way?
If you need run code after 100% loaded with **image** and **files**, check code in `mounted()`:

    document.onreadystatechange = () => {
      if (document.readyState == "complete") {
        console.log('Page completed with image and files!')
        // fetch
      }
    }

More info: [MDN Api onreadystatechange][1]


  [1]: https://developer.mozilla.org/docs/Web/API/XMLHttpRequest/onreadystatechange
