### ISSUE TITLE
Async fetch() pending state load after data loaded.

### ISSUE THREAD

**Issue by Croodo** [nuxt/nuxt.js#10719]
Using asynce fetch() to fetch data . 
While direct(external visit) page show data first for few ms then show pending state( loading messages) then load final page. What should i do to fix it . 

Here is a preview, red marked area is the pending state. 
![F98CD300-940E-4352-A55C-07C658475E50](https://user-images.githubusercontent.com/67230713/191689095-bb6aa48a-fddd-4395-874a-90fd9ca1e8f2.jpeg)

**SSR : true .**

**Comment by danielroe** [comment]
Would you provide a reproduction? :pray:

**Comment by Croodo** [comment]
Here is my code demo

`  data() {
    return {
      app: [],
    };
  },

  async fetch() {
    const { data } = await axios.get(
      `https://apiurl...........` );
    this.app = data;
    if (this.app.seourl === this.$route.params.app) {
      this.app = data;
    } else {
      if (process.server) {
        this.$nuxt.error({ statusCode: 404, message: "Page not found" });
      }
    }
  },`


`  <div class="loading-app" v-if="$fetchState.pending">
        <apploading></apploading>
      </div>
      <div class="loading-app" v-else-if="$fetchState.error">
        Error While Loading
      </div>
      <div class="loading-app" v-else> My page codes here</div>`

**Comment by danielroe** [comment]
You could try setting a `fetchKey`: https://nuxtjs.org/docs/components-glossary/fetch#options.

If that doesn't work, would you create a reproduction via https://stackblitz.com/github/nuxt/starter/tree/v2-stackblitz?

**Comment by Croodo** [comment]
[Here is a demo reproduction code](https://stackblitz.com/edit/github-swtbrx?file=pages%2Fapp%2F_app.vue)

[Video of actual issue in live production ](https://youtube.com/shorts/fRJzW3tuHeo?feature=share)

**Comment by Croodo** [comment]
This issue is not for the async fetch function (confirmed by some tests). I have to figure out why it's happening.
