### ISSUE TITLE
Is there any way to access nuxt context(error handler) after the page rendered

### ISSUE THREAD

**Issue by ye-will** [nuxt/nuxt.js#1073]
I want to route to the error page after running some browser only checkers, is there any way?

**Comment by Atinux** [comment]
HI @ye-will 

You can this `this.$nuxt.error({ statusCode, message })` inside any Vue components instances on client-side.

Example, go to https://nuxtjs.org and open the browser console, then write `$nuxt.error({ message: 'Hello', statusCode: 404 })` and press enter :)

**Comment by ye-will** [comment]
Awesome, thx! @Atinux
