### ISSUE TITLE
is it possible to update vue to 2.7.10

### ISSUE THREAD

**Issue by mathxlee** [nuxt/nuxt.js#10749]
there are a lot of features updated from 2.7, is it possible update nuxt2 to use the latest release of vue?

**Comment by danielroe** [comment]
Totally. Just refresh your lockfile. You can try running `npm upgrade vue` or whatever your package manager's command is.

**Comment by danielroe** [comment]
For a long time Nuxt has used the caret constraint which means ... a huge number of old Nuxt releases will install Vue 2.7.

**Comment by naquiroz** [comment]
But is there a way to know from what minor version nuxt 2 started supporting vue 2.7?

**Comment by danielroe** [comment]
What version are you on?

**Comment by naquiroz** [comment]
> What version are you on?

"@nuxtjs/vuetify": "^1.12.3",

**Comment by danielroe** [comment]
That's not a version of nuxt.

**Comment by naquiroz** [comment]
I apologize, my brain thought it copied the right one: 
"nuxt": "^2.14.12"

**Comment by danielroe** [comment]
That works for Vue 2.7 👍
