### ISSUE TITLE
Does Nuxt have plan to support npx?

### ISSUE THREAD

**Issue by Jinjiang** [nuxt/nuxt.js#1076]
Ref: https://www.npmjs.com/package/npx

`npx` has been included in latest `npm`. It can just execute a npm package in any place without installation/initiation/configuration.

I think if Nuxt supports `npx`, developers can start a website even just by a file `index.vue` in a blank directory.

Thanks :-)

**Comment by pi0** [comment]
It should support wait a minute :))

**Comment by Jinjiang** [comment]
> Couldn't find preset "vue-app" relative to directory

It seems can to be solved by `require.resolve('babel-preset-vue-app')` instead of `'vue-app'` in babel presets options. I have done a little test in another similar situation a moment ago.

(hope helpful for you)

**Comment by pi0** [comment]
Will be available soon! Demo: https://asciinema.org/a/131579

[![asciicast](https://asciinema.org/a/131579.png)](https://asciinema.org/a/131579)

**Comment by Atinux** [comment]
rc5 is out! https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc5
