### ISSUE TITLE
Newly created Nuxt project is unable to run with pnpm

### ISSUE THREAD

**Issue by Jinjiang** [nuxt/nuxt.js#10762]
### Versions

- nuxt: v2.15.8
- node: v16.15.0
- pnpm: v7.11.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

```bash
git clone https://github.com/Jinjiang/try-nuxt
pnpm install
pnpm dev
```

### What is Expected?

The start page:

![image](https://user-images.githubusercontent.com/206848/196085159-d42b0da1-172b-4664-aec7-63dc64c82ba4.png)

This screenshot was taken by re-installing the dependencies by `yarn`.

### What is actually happening?

Error received:

![image](https://user-images.githubusercontent.com/206848/196085027-ce3eed46-e3b6-4a2b-9b73-95e6b31ad0a5.png)

**Comment by danielroe** [comment]
You will likely need to use `--shamefully-hoist` or install `ufo` manually.

**Comment by pi0** [comment]
https://github.com/nuxt/framework/issues/5411

**Comment by danielroe** [comment]
(This is a Nuxt 2 issue.)
