### ISSUE TITLE
Nuxt2 build fail on node18 Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxt.js#10779]
### Versions

- nuxt: 2.15.8
- node: 18.12.0

### Reproduction
when 2022/10/25 nodejs relase 18.12 to LTS version
nuxt 2 build fail.
it works on `node16` or `NODE_OPTIONS=--openssl-legacy-provider`

### Steps to reproduce
```cmd
yarn create nuxt-app node18nuxt
cd node18nuxt
yarn build
```

### What is Expected?
build success

### What is actually happening?
```cmd
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    ...
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
```

**Comment by lseelenbinder** [comment]
Confirming we're seeing this as well, using the Docker `node:lts-alpine` image.

**Comment by danielroe** [comment]
This is not a Nuxt issue; I think you likely need to update your openssl version. A Google search should yield some helpful results.

**Comment by tats-u** [comment]
@danielroe This occurs even in Windows. How can I update its OpenSSL? My Node is 18.12.1.
With setting `NODE_OPTIONS` it succeeds.

**Comment by Pictor13** [comment]
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
https://itsmycode.com/error-digital-envelope-routines-unsupported/

Node version is not LTS and is not supported. Solution is to downgrade or specify legacy openssl version (see links).

**Comment by danielroe** [comment]
You're quite right, this shouldn't have been closed. We can track in https://github.com/nuxt/nuxt.js/issues/10844.

**Comment by Taekondainc** [comment]
having the same issue..... is this going to be fixed or is this closed

**Comment by danielroe** [comment]
This is fixed in `nuxt-edge` and will be in the next release.

**Comment by Taekondainc** [comment]
hopefully thats soon

**Comment by massahoudou** [comment]
have the same issue  this work for me :)
export NODE_OPTIONS=--openssl-legacy-provider

**Comment by Williams247** [comment]
> have the same issue this work for me :) export NODE_OPTIONS=--openssl-legacy-provider

where do i get to put this

**Comment by sifuna2002** [comment]
just on your terminal

**Comment by Alssdev** [comment]
> have the same issue this work for me :) export NODE_OPTIONS=--openssl-legacy-provider

This works for me too! Thanks
