### ISSUE TITLE
RC12 header overflow

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt/nuxt.js#10773]
### Versions

- nuxt: rc 12
- node: 16 or 18

### Reproduction

Iv been struggling to reproduce this on smaller projects, but its definitely only a problem on RC 12,  RC 11 works fine.  

### Steps to reproduce
I noticed on larger projects that when requesting the router page nuxt RC12 produces a header overflow error on h3. which then causes the entire dev server to crash

### What is Expected?
This shouldnt break the server

### What is actually happening?
![Screenshot 2022-10-24 at 14 02 52](https://user-images.githubusercontent.com/93583336/197521213-f26c353a-0d30-4663-b294-5bef04b30967.png)
<img width="795" alt="Screenshot 2022-10-24 at 14 03 30" src="https://user-images.githubusercontent.com/93583336/197521411-89c864bb-a23f-42b6-91ed-acc93e47711e.png">

**Comment by manniL** [comment]
Please use https://github.com/nuxt/framework from Nuxt 3 issues ☺️

Also see https://github.com/nuxt/framework/issues/8306
