### ISSUE TITLE
Treeshaking not working in dev mode

### ISSUE THREAD

**Issue by astagi** [nuxt/nuxt.js#10795]
### Versions

- nuxt: v2.13.0
- node: v16.13.1 (npm v6.14.16)

### Reproduction

I tried to install [bootstrap-italia](https://github.com/italia/bootstrap-italia), a library with some vanilla JS components and treeshakable (see [package.json](https://github.com/italia/bootstrap-italia/blob/main/package.json#L15)). Unfortunately when I try to import in my component on of the bootstrap-italia components (in this case `InputNumber`) I see that the other components are imported as well in the bundle.. This happens only in dev mode, not in production. Why? Is it supposed to be? I find this a little bit confusing, these components might have unexpected side effects that I see during development but not in production.

```html
<!-- Please remove this file from your project -->
<template>
    <div>
        <label for="inputNumber3" class="input-number-label">Fai una donazione</label>
        <span class="input-number input-number-currency">
            <input type="number" id="inputNumber3" name="inputNumber3" step="any" value="3.50" min="0" />
            <button class="input-number-add">
                <span class="visually-hidden">Aumenta valore Euro</span>
            </button>
            <button class="input-number-sub">
                <span class="visually-hidden">Diminuisci valore Euro</span>
            </button>
        </span>
    </div>
</template>

<script>
import { InputNumber } from 'bootstrap-italia'

export default {
  name: 'NuxtTutorial',
  onMounted: () => {
    new InputNumber(document.getElementById('inputNumber3'))
  }
}
</script>
```

<details open>
<summary>Additional Details</summary>
<br>
No particular configuration.
</details>

### Steps to reproduce

- Install a tree shakable library (in this case bootstrap-italia). See the code above and look the final js, it includes all the components exported in index.js by bootstrap-italia

### What is Expected?

I'd like to see the same behaviour both during development and production

### What is actually happening?

In production tree shake works as expected, during development I see all my components imported!

**Comment by danielroe** [comment]
I'm afraid tree-shaking is an expensive operation that is not feasible to implement within dev mode.

**Comment by astagi** [comment]
Thanks for your support @danielroe I can imagine :( I need to restructure some parts of my library to avoid unwanted side effects.
