### ISSUE TITLE
Why no slots in layouts?

### ISSUE THREAD

**Issue by luminarious** [nuxt/nuxt.js#1079]
Hey!

With our current project, me and the team was wondering what was the reasoning behind the decision to not support slots in layouts?

We ran into it when we realized that a CSS grid layout would work best for our responsive view, since each page knows what kind of sidebar or extra content is required in this specific case. For that the structure would need to be like this:

```
html
  head
    ...
  body
    my-header
    nuxt
      #content
        slot
      #sidebar
        slot(name="sidebar")
      #extra
        slot(name="extra")
    my-footer
```
Right now the two options we see are using a separate layout component or somehow coordinating sidebar and extra components to make their own requests according to current route, but both feel at odds with overall simplicity Nuxt aims for.

**Comment by awronski** [comment]
Why not Dynamic Components?
https://vuejs.org/v2/guide/components.html#Dynamic-Components

**Comment by luminarious** [comment]
@awronski Dynamic Components are cool, but they're also very much over-engineering for current use-case. We just want to compose content and only a few of our pages have a separate component in the sidebar slot.

**Comment by alexchopin** [comment]
Hi, 
The `<nuxt>` component includes a `<router-view>` tag so that's why we cannot use slots.
[Nested routes](https://nuxtjs.org/guide/routing#nested-routes) can be a solution in your case.
