### ISSUE TITLE
Babel Transform Configuration

### ISSUE THREAD

**Issue by lcx960324** [nuxt/nuxt.js#1080]
Hello.
It seems that babel-loader will skip transforming files in node_modules.
I use the traditional way to config babel but it did't work.
``` 
    loaders: [
      {
        test: /iview.src.*js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['es2015'],
            plugins: ['transform-runtime']
          }
        }
      },
//   below are default nuxt loaders config.
```

So I wonder is there any way to let babel transform files in node_modules.
Thank you. XD

**Comment by StasB93R** [comment]
Can nuxt.js people respond or give some sort of update on what is happening or what is planned to do to solve this problem?

**Comment by pi0** [comment]
Hi. There is an open issue (#1011) about adding such feature. Please track discution from there.
