### ISSUE TITLE
 Only URLs with a scheme in: file, data are supported by the default ESM loade

### ISSUE THREAD

**Issue by edwinfadul** [nuxt/nuxt.js#10816]
### Versions

- nuxt: v3.0.0 
- node: v18.12.1 
- windows: 10

### Reproduction

By installing nuxt security and placing the dependency in nuxtjs config - **modules: ['nuxt-security'] -**
[https://nuxt.com/modules/security](https://nuxt.com/modules/security)
i get the following error:

 [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

![image](https://user-images.githubusercontent.com/34517197/202352611-8edbdd89-2a82-4df7-b3cd-9504041ae53b.png)

It should be noted that I have tried several versions of nuxt and node - I have deleted node_modules - yesterday I upgraded nuxt and today again

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/9092.
