### ISSUE TITLE
Node Fetch Error - Vue Server Renderer

### ISSUE THREAD

**Issue by XPAULUSX** [nuxt/nuxt.js#10817]
![image](https://user-images.githubusercontent.com/47896035/202464632-99a3c8dc-f872-48d5-8b15-6eb8907013c8.png)

Hello,

Today i've randomly started seeing this error within my nuxt 2 project.  I'm not sure what has caused this but we've been running this software for months without issue.  

This error occurs when running either a nuxt build or nuxt dev.

### Versions

- nuxt: ^2.15.8
- node: v18.12.1

Any help towards fixing this would be greatly appreciated thanks.

**Comment by danielroe** [comment]
you can try installing the previous (cjs) version of `node-fetch`

**Comment by danielroe** [comment]
I think probably a package manager has chosen in its wisdom to hoist v3 to top level whereas previously v2 was the hoisted one.
