### ISSUE TITLE
TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.

### ISSUE THREAD

**Issue by Gabrielmoraesp** [nuxt/nuxt.js#10813]
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `npm@8.19.2`
- Builder:          `webpack`
- User Config:      `server`, `target`, `ssr`, `ignore`, `head`, `optimization`, `image`, `css`, `plugins`, `components`, `buildModules`, `tailwindcss`, `modules`, `robots`, `sitemap`, `bootstrapVue`, `nuxt-compress`, `toast`, `axios`, `loading`, `content`, `build`, `env`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxt/content@2.2.2`, `vue-toastification/nuxt`, `nuxt-compress@5.0.0`, `bootstrap-vue/nuxt`, `@nuxtjs/sitemap@2.4.0`, `@nuxtjs/robots@2.5.0`, `@nuxt/http@0.6.4`
- Build Modules:    `@nuxtjs/dotenv@1.4.1`, `@nuxtjs/composition-api/module@0.33.1`, `@nuxt/typescript-build@2.1.0`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/svg@0.4.0`, `@nuxt/image@0.7.1`
------------------------------

![image](https://user-images.githubusercontent.com/440323/202290501-593dfe00-b945-4ae0-8287-f9b5303a41b3.png)

**Comment by MavDavis** [comment]
I just posted similar error. I have tried four times now and it just keep coming out that way

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/create-nuxt-app/issues/1018 - see my comment there.

**Comment by vahid-bagh3ri** [comment]
@danielroe I have This issue in Nuxt ^2.15.8.
