### ISSUE TITLE
Load a global settings.scss file in every vue component?

### ISSUE THREAD

**Issue by falstack** [nuxt/nuxt.js#1081]
like this repo，[sass-resources-loader](https://github.com/shakacode/sass-resources-loader)

how can i include it？

**Comment by uptownhr** [comment]
@falstack this is more of an issue with vue-loader and there's a great thread on this. Checkout https://github.com/vuejs/vue-loader/issues/328

**Comment by falstack** [comment]
@uptownhr 

Oh~

thanks very much

**Comment by falstack** [comment]
@uptownhr 

But.. how can i write it in nuxt.config.js?

**Comment by Kylart** [comment]
@falstack 
If I'm not wrong, you want to have a file `settings.scss` somewhere in your repo that contains rules which apply everywhere in your app right ?

To do so, here is what I'd do:
   1. Put your `settings.scss` wherever you want to. Let's say it's at `/path/to/settings.scss`.
   2. In your `nuxt.config.js`:
```javascript
const {join} = require('path')

module.exports = {
  ...
  css: [
    {src: join(__dirname, 'path/to/settings.scss'), lang: 'scss'}, // Maybe lang should be 'less' ? I'm not used to scss...
  ]
  ...
}
```
Now, you should have your scss loaded in every component and even hot reloading on it! You probably need to install `node-sass`, `sass-loader` and some other stuff though.

I hope I did not misunderstand your problem and if so, please tell me.

**Comment by falstack** [comment]
@Kylart 
Thanks for you answer，but that's not my want.

there: [Loading a global settings file](https://vue-loader.vuejs.org/en/configurations/pre-processors.html)，this is i need.

I don't know, how to write variables.scss in nuxt.config.js.

**Comment by alexchopin** [comment]
#1092
