### ISSUE TITLE
[vuex] do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by MavDavis** [nuxt/nuxt.js#10828]
![Screenshot 2022-11-22 040300](https://user-images.githubusercontent.com/90147670/203211376-40b4efcf-8f18-446f-acca-21fa90f94492.png)
![Screenshot 2022-11-22 040208](https://user-images.githubusercontent.com/90147670/203211686-e74be033-f873-41db-8b0e-0d768d759b50.png)

[vuex] do not mutate vuex store state outside mutation handlers.
An error occurred while rendering the page. Check developer tools console for details.

**Comment by danielroe** [comment]
Yes, you must not change the store state outside of mutation handlers. Mutation handlers must be synchronous - it looks like you are mutating state asynchronously, which you should use an action for (which _calls_ mutations when appropriate).
