### ISSUE TITLE
SSL Redirection via Heroku

### ISSUE THREAD

**Issue by natecox** [nuxt/nuxt.js#1082]
I'm currently at a loss for the best practice in getting forced SSL redirection with Nuxt deployed to Heroku.

Is there a guide somewhere for this that I simply haven't been able to find?

**Comment by pi0** [comment]
Hey. Can you try this: https://github.com/nuxt/hackernews/blob/master/middleware/https.js ?

**Comment by natecox** [comment]
@pi0 Thanks for the reference. Unfortunately, `redirect` only allows for relative redirection, not absolute. When I try to use the linked snippet as middleware, I end up with a recursive loop that provides a url such as:
```
http://testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/https:/testapp.herokuapp.com/
```

**Comment by pi0** [comment]
@natecox I'm not a Heroku app user but they may have Edge SSL redirects too. BTW for middleware redirection with absolute paths, we may use `window.location = ...` and `req.setHeader('Location:')` should test it if working or not :)

**Comment by ydnar** [comment]
We ran into this issue in #770 and implemented a workaround: https://github.com/nuxt/nuxt.js/issues/770#issuecomment-304126495

**Comment by natecox** [comment]
I haven't had a chance to try this code out, but I did run across it a while back. Without trying to be disrespectful to the code author, the workaround there seems really hacky; which is a side effect of `redirect` simply not allowing absolute URLs.

If this is the _accepted_ solution I'll just go with it, but I feel like there's an opportunity to improve from the Nuxt side.

**Comment by natecox** [comment]
For clarity, I really think that Nuxt would benefit by providing a `force_ssl` option to handle this automatically.

**Comment by pi0** [comment]
@natecox After some search, found a simpler soloution usingn nuxt's new `serverMiddleware` option + [express-force-ssl](https://www.npmjs.com/package/express-force-ssl) (demo soon)

**Comment by natecox** [comment]
Sounds promising! I haven't seen `serverMiddleware` anywhere, is it documented?

**Comment by pi0** [comment]
@natecox Comment deleted as it is not handling client side conditions. I will share a demo for serverMiddleware usage.

**Comment by pi0** [comment]
Sorry for delay. Was doing few tests with currenct redirect middleware. Just implemented [redirect-ssl](https://github.com/nuxt-community/redirect-ssl) which seems being compatible with heroku too. (Full supporting x-forwarded-proto). In order to register middleware you can install `redirect-ssl` package and adding this to `nuxt.config.js`: (needs nuxt 1.x)
```js
module.exports= {
serverMiddleware: [ 'redirect-ssl' ],
}```

Please let me know if it's working with heroko. And if was not successed don't worry as middleware system is improved a lot with next release also we may provide an easier module for SSL redirects too.

**Comment by natecox** [comment]
@pi0 This seems to work fine, ssl redirection on the server is working without an issue.

I would absolutely be in favor of baking this functionality into Nuxt with a toggle flag.

**Comment by pi0** [comment]
Happy hearing it's working. Unfortunately while many would benefit from such functionalities we cannot add everything to Nuxt core as it may get out of control soon (**https serve is not in the core** too) However instead we introduce a modular system which modules can be added in a on liner manner to enhance projects.

**Comment by PiusNyakoojo** [comment]
@pi0 ```redirect-ssl``` isn't working for us.

We have installed the package:

```bash
npm install -S redirect-ssl
```

Placed it in nuxt.config.js:
```javascript
module.exports = {
   build: {},
   // ...
   serverMiddleware: ['redirect-ssl']
}
```

Started the server:
```
npm run build && npm run start
```

And finally, tunneled it through ngrok:
```bash
ngrok http 3000
```

When we visit the ngrok url ```http://ourapp.ngrok.io``` we expect to be redirected to ```https://ourapp.ngrok.io```. Instead, we remain on the http site.

Thank you for your help!

**Comment by pi0** [comment]
@PiusNyakoojo I'll check ngrok soon.

**Comment by PiusNyakoojo** [comment]
Thanks pi!

**Comment by pi0** [comment]
@PiusNyakoojo Just update [redirect-ssl](https://github.com/nuxt-community/redirect-ssl) and to `1.1.0` and it will work!

**Comment by PiusNyakoojo** [comment]
Haha, incredible. Thanks pi!

**Comment by PiusNyakoojo** [comment]
Hey @pi0, one last thing:

How do you disable redirect-ssl for localhost development? 😄

**Comment by pi0** [comment]
Haha that was the reason i planned writing a nuxt module for easier usage. Currently you may conditionally disable that line using process.env or commenting out by hand 😂 Will provider module in few days.

**Comment by zzhjerry** [comment]
@PiusNyakoojo with `redirect-ssl@1.2.1`, it's forced to only redirect in production (a.k.a. when `process.env.NODE_ENV === 'production'`

**Comment by wasinr** [comment]
@pi0 it's work! Thank you for your work
