### ISSUE TITLE
Ie compatible local can, generate package after the line can not

### ISSUE THREAD

**Issue by peterzhanghui** [nuxt/nuxt.js#1083]
middleware/auth:

let loggedIE = false // 是否是低版本的浏览器
  if (process.BROWSER_BUILD) {
    loggedIE = browserType(window.navigator.userAgent)
    console.log(window.navigator.userAgent)
  } else {
    if (!req) return
    loggedIE = browserType(req.headers['user-agent'])
    console.log(req.headers['user-agent'])
  }
  if (loggedIE) {
    return redirect('/below-ie8')
  }

**Comment by alexchopin** [comment]
[Contribution Guide](https://nuxtjs.org/guide/contribution-guide)

> A great way to contribute to the project is to send a detailed report when you encounter an issue. We always appreciate a well-written bug report, and will thank you for it!
