### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by markhaehnel** [nuxt/nuxt.js#1084]
I get the following error while using alpha.4 of nuxt:
```
[..]\node_modules\vue-server-renderer\index.js:8
  throw new Error(
  ^

Error:

Vue packages version mismatch:
- vue@2.4.1
- vue-server-renderer@2.3.4
This may cause things to work incorrectly. Make sure to use the same version for both.
```

**Comment by pi0** [comment]
Hey @markhaehnel . This problem will be fixed soon. For now, please explicitly define dependencies in youe `package.json`:


```js
"dependencies": {
 "vue": "2.3.4",
 "vue-server-renderer": "2.3.4",
 "vue-template-compiler": "2.3.4",
}
```

**Comment by gbezyuk** [comment]
I've just run into the similar issue, badly wanting Vue 2.4.1's $attrs and $listeners for HOC and realizing Nuxt is weirdly still dependant on 2.3.4.
Just changing dependencies in package.json of your project does not help at all to change nuxt's own dependencies. Using `npm shrinkwrap` with manual changes does, though.

**Comment by dohomi** [comment]
@gbezyuk I think that alpha5 was published before NUXT 2.4 came out. @pi0 did you guys plan to release a public version with compatibility of 2.4.x soon? Is it otherwise safe to use the current dev?

**Comment by pi0** [comment]
@dohomi Actually safest way is to keep using `2.3.4` (and always latest tested version with nuxt) dev is stable too but not heavily tested and documented that's why the release is delayed. Just stay tuned for `rc1` :)

**Comment by gbezyuk** [comment]
Yeah, I know. Safest way, hevily tested. $ATTRS and $LISTENERS, guys!!! )

**Comment by dohomi** [comment]
@pi0 thanks! any estimated date for the `rc1`? Keep up the good work!

**Comment by zhanziyang** [comment]
Why is this closed? Is it fixed already? Which version of nuxt should we use if we want vue@2.4.1 features? Please help. Thank you!!!

**Comment by pi0** [comment]
@zhanziyang Please use `1.0.0-rc3` witch comes with vue@2.4.1

**Comment by IamManchanda** [comment]
Happened with v2.5 too 
Here I report 2.5

PS: Can't share whole screen/all commands as came in a professional project instead of open source

<img width="703" alt="screen shot 2018-05-17 at 10 45 18 pm" src="https://user-images.githubusercontent.com/4970624/40193131-0a79ec22-5a24-11e8-81ed-e5d80be8259c.png">

**Comment by gerwinov** [comment]
I can report the exact same behavior as @IamManchanda describes.

**Comment by derekshull** [comment]
Getting the same as @gerwinov and @IamManchanda

**Comment by ramstein74** [comment]
after updating to nuxtjs i get this when runing dev

Vue packages version mismatch:

- vue@2.5.16
- vue-server-renderer@2.5.17

**Comment by nusendra** [comment]
@ramstein74 same to me.

**Comment by availit** [comment]
I too can report getting the same error as @IamManchanda and @gerwinov 
Any idea how to resolve it?

**Comment by nusendra** [comment]
after i remove vuenut, the error is gone. So, in my opinion, just uninstall the unused dependencies. Or upgrade it

**Comment by besnikh** [comment]
@All is there any solution to this I am getting the same error after upgrading to nuxt 1.4.2

**Comment by galvez** [comment]
npm i vue@latest -s

**Comment by antony** [comment]
@galvez Surely nuxt should install the latest vue automatically?

I've just upgraded to 1.4.2 and this is still an issue sadly.

**Comment by galvez** [comment]
It will. Have you rm -rf node_modules before installing everything again?

>

**Comment by zzleomar** [comment]
@ramstein74 Did you solve it?

**Comment by ramstein74** [comment]
Yes , i guess i just changed package.json to have both with the same version
instead of this

   - vue@2.5.16
   - vue-server-renderer@2.5.17


make sure to have this

   - vue@2.5.16
   - vue-server-renderer@2.5.16

Not the best but it works

2018-08-30 6:29 GMT+01:00 zzleomar <notifications@github.com>:
