### ISSUE TITLE
'this' is undefined when using head as method in nuxt.config.js

### ISSUE THREAD

**Issue by kane-mason** [nuxt/nuxt.js#10843]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `npm@8.1.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/delicate-sky-y1rb7n?file=/nuxt.config.js

(you will need to toggle ssr once the sandbox is loaded otherwise it wont load at all)

### Describe the bug

In `nuxt.config.js`  we have the option to define the `head` node as a function. 

For my case i am using the `@nuxtjs/i18n` package and attempting apply the following code taken directly from the documentation
```js
export default {
  // ...other Nuxt options...
  head () {
    return this.$nuxtI18nHead({ addSeoAttributes: true })
  }
}
```

All works fine in `ssr:true`, but for `ssr:false` mode `this` is undefined and causes an error

**Comment by kane-mason** [comment]
I understand there is a work around where i could update the head in the layout component, but i am trying to avoid this as the values i set here are common throughout the website.

**Comment by kane-mason** [comment]
I understand there is a work around where i could update the head in the layout component, but i am trying to avoid this as the values i set here are common throughout the website.

**Comment by manniL** [comment]
You cannot use `this` inside `nuxt.config.js` because there is no instance available. Thus, you would have to use the workaround and apply it in layouts (e.g. via mixin).

**Comment by kane-mason** [comment]
@manniL but `this` is defined with `ssr:true` so not entirely accurate?

**Comment by kane-mason** [comment]
@manniL documentation also says it can be used like this https://i18n.nuxtjs.org/seo
