### ISSUE TITLE
I need Nuxt 2 to be upgraded to support Vue 2.7.14

### ISSUE THREAD

**Issue by bryarb** [nuxt/nuxt.js#10842]
As it stands, Nuxt 2 is incomplete. It does not support all versions of Vue 2.

I need Nuxt 2 to support vue 2.7.14 as it has a lot of performance upgrades I need in my website.

Currently, Nuxt 2 has a dependency on vue-server-renderer that only works with vue 2.6 and it does not let me compile my project.

If this post is left open, I will add a bounty on https://bountysource.com/ 

Thank you

**Comment by danielroe** [comment]
Nuxt _does_ support Vue 2.7.14, but you may need to regenerate your lockfile, manually upgrade `vue-server-renderer` or use resolutions/overrides if you have other dependencies that are interfering with the package manager's resolution algorithm.

Here's an example running with 2.7.14: https://stackblitz.com/github/nuxt/starter/tree/v2
