### ISSUE TITLE
Nuxt Fatal Error: TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.

### ISSUE THREAD

**Issue by DavidRojoM** [nuxt/nuxt.js#10840]
### Versions

- nuxt: 2.15.8
- node: tested on 16.14.2 and 18.10.0

### Reproduction

[nuxt.config](https://gist.github.com/DavidRojoM/9f00f4fe7c2cea423ac1c9c4950dcdf0)
[package.json](https://gist.github.com/DavidRojoM/08a88268e9cd17164d614044c9244bbe)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/72155097/204654559-03fdf427-0464-4989-a4bf-00466b0c9895.png)
![image](https://user-images.githubusercontent.com/72155097/204654735-3e6e98a1-a8dd-4d15-be4a-b27399897f39.png)

### What is Expected?
To actually run the application.

### What is actually happening?

Crashing due to destructuring of an undefined `this`

**Comment by chonghanhuang** [comment]
I get the same problem，but I solved it temporarily by changing the version of @nuxt/kit. Maybe you can try these:

add to the package.json
```json
"resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
}
```
then `yarn` again

**Comment by sonnh58** [comment]
I have same error.
Using https://tailwindcss.com/docs/guides/nuxtjs resolve issue

**Comment by DavidRojoM** [comment]
> I have same error. Using https://tailwindcss.com/docs/guides/nuxtjs resolve issue

Thanks for the reply but it doesn't seem to be working either

**Comment by chonghanhuang** [comment]
i get the same. However, I solved this problem temporarily with the following changes，have a try.
add to your package.json
```js
"resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
  }
```
then reinstall the dependencies,  yarn again
```bash
yarn
```

**Comment by chonghanhuang** [comment]
i get the same, and I'm guessing your @nuxt/kit version is also 3.00. However, I solved this problem temporarily with the following changes，have a try.
add to your package.json
```js
"resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
}
```
then reinstall the dependencies,  yarn again
```bash
yarn
```

if it work, maybe we can track in /nuxt/framework#9115

**Comment by DavidRojoM** [comment]
It works, thank you @chonghanhuang. Closing this.

**Comment by baranbaturr01** [comment]
> ### Versions
> * nuxt: 2.15.8
> * node: tested on 16.14.2 and 18.10.0
> 
> ### Reproduction
> [nuxt.config](https://gist.github.com/DavidRojoM/9f00f4fe7c2cea423ac1c9c4950dcdf0) [package.json](https://gist.github.com/DavidRojoM/08a88268e9cd17164d614044c9244bbe)
> 
> ### Steps to reproduce
> ![image](https://user-images.githubusercontent.com/72155097/204654559-03fdf427-0464-4989-a4bf-00466b0c9895.png) ![image](https://user-images.githubusercontent.com/72155097/204654735-3e6e98a1-a8dd-4d15-be4a-b27399897f39.png)
> 
> ### What is Expected?
> To actually run the application.
> 
> ### What is actually happening?
> Crashing due to destructuring of an undefined `this`

I had the same problem, but I did the nuxt configuration on tailwind's official site and it was fixed.
https://tailwindcss.com/docs/guides/nuxtjs

**Comment by dev-Anderson1** [comment]
> Eu recebo o mesmo e acho que sua versão @nuxt/kit também é 3.00. No entanto, resolvi esse problema temporariamente com as seguintes alterações, tente. adicione ao seu package.json
> 
> ```js
> "resolutions": {
>     "@nuxt/kit": "3.0.0-rc.13"
> }
> ```
> 
> em seguida, reinstale as dependências, fios novamente
> 
> ```shell
> yarn
> ```
> 
> se funcionar, talvez possamos rastrear em / [nuxt/framework#9115](https://github.com/nuxt/framework/issues/9115)

pra mim deu certo essa instalaçao aqui e reiniciei com yarn install e rodou perfeitamente

**Comment by islomrakhimkulov** [comment]
When you will have this problem you can check nuxt version, in tailwindcss page [https://tailwindcss.com/docs/guides/nuxtjs#3](url)

**Comment by adippel** [comment]
The above proposed workaround is not working for me. See https://github.com/nuxt-modules/tailwindcss/issues/598 for another workaround that worked for me.

**Comment by Foddie2** [comment]
Hey guys any solution to this. All these seems not to work

**Comment by adippel** [comment]
AFAIK, the issue was resolved in the dependencies which caused it. I am currently running without any workaround or issues using the following dependencies:

* nuxt 2.16.3
* @nuxtjs/tailwindcss 6.7.0

@Foddie2 could you check your dependencies?

**Comment by Foddie2** [comment]
> AFAIK, the issue was resolved in the dependencies which caused it. I am currently running without any workaround or issues using the following dependencies:
> 
> * nuxt 2.16.3
> * @nuxtjs/tailwindcss 6.7.0
> 
> @Foddie2 could you check your dependencies?

@adippel  this still does not work, tried changing the dependancies but still not not working. I am using Nuxt 3.6.1

**Comment by LBeckX** [comment]
My working package.json.

```json
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/image": "^1.0.0-rc.1",
    "@nuxtjs/color-mode": "^3.3.0",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@types/node": "^18",
    "nuxt": "^3.6.1"
  },
  "dependencies": {
    "@headlessui/vue": "^1.7.14",
    "@heroicons/vue": "^2.0.18"
  }
}
```
