### ISSUE TITLE
browser window scroll position in SSR

### ISSUE THREAD

**Issue by joshua1** [nuxt/nuxt.js#1085]
Since window is never defined unless in Browser build. how do i get the scroll position of the window (usually ```window.scrollY or window.scrollX```) when server rendered.

**Comment by dohomi** [comment]
@joshua1 my question is: why would your server care about the scroll position, because there is no scrolling on server side?

**Comment by joshua1** [comment]
@dohomi I didnt ask this question so you could ask your question, i was only looking for answers, where does a server rendered page/view get displayed? anyway, i have this sorted out already

**Comment by felixdenoix** [comment]
Hello @joshua1 !
Could you enlighten us on how you manage to do so ?

**Comment by Hamdan85** [comment]
that was an important answer @joshua1 ... one that could save me right now... lol

**Comment by felixdenoix** [comment]
@Hamdan85  You can use `process.browser` to know if you are in the in the client or the server to start with !
