### ISSUE TITLE
`<nuxt-link>` without `to` props crash

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt.js#10858]
### Versions

- nuxt: 2.15.8
- node: 16.14.0

### Steps to reproduce
- In you nuxt app, add a `<nuxt-link to="/">`, the page render correctly.
- Remove the `to="/"`, the page crash and Nuxt show the `error.vue` layout.

### What is Expected?
The page shouldn't crash. `<nuxt-link>` without `to` props should be treated like links without href and redirect to the root `/`.

### What is actually happening?
The page crash with a nuxt fatal error:
> Cannot read properties of undefined (reading '_normalized')

**Comment by codewithbug** [comment]
please , provide  the full list of error log.

**Comment by mrleblanc101** [comment]
Yes, but it shouldn't crash the whole app if it's missing showing the Nuxt Error page.

**Comment by mrleblanc101** [comment]
I realise this is a vue-router issue, so i opened: https://github.com/vuejs/router/issues/1648
