### ISSUE TITLE
question about nuxt start  -> window.__NUXT__ 

### ISSUE THREAD

**Issue by 8xx8x** [nuxt/nuxt.js#10861]
after I start it through nuxt start, `<script>window.__NUXT__=(function(a,b,c,d,e,f){b[0]=` always appears on the html page,
after trying to remove, the data will not be rendered,

how to solve this problem?

**Comment by manniL** [comment]
It is necessary to transfer the state from the server to the client. You cannot remove it, otherwise your app won't work.
