### ISSUE TITLE
SSR SVG Inject

### ISSUE THREAD

**Issue by vanpav** [nuxt/nuxt.js#1087]
Is it possible to inject svg assets to ssrTemplate which loaded via [svg-sprite-loader](https://github.com/kisenka/svg-sprite-loader)?

**Comment by didiself** [comment]
Hi, I used  svg-sprite-loader in my project , but not sure is that your want.

write a svg.vue 
```
<template lang="pug">
  svg
    use(:xlink:href="'#'+fileName")
</template>

<script>
export default {
  props: {
    fileName: {
      type: String,
      required: true
    }
  },
  created () {
    require(`~/assets/svg/${this.fileName}.svg`)
  }
}
</script>
```

when the other vue need svg, just import the svg.vue
when render a sprite in <body>
![image](https://user-images.githubusercontent.com/14201030/28399905-8c8fe3b2-6d42-11e7-81d6-c49e72514745.png)

**Comment by vanpav** [comment]
@didiself thanks for your reply. It seems with your approach I will get same js-inject of svg-sprite. What I wanna get is inject svg-sprite to app.html when nuxt building production application that would prevent svgs blinking on page load.

**Comment by bernhardw** [comment]
@didiself Did you have to change your nuxt.config.js?

**Comment by vanpav** [comment]
@bernhardw it's simple 
![image](https://user-images.githubusercontent.com/2944759/28580161-61cf1908-7167-11e7-96e9-523e77ce433b.png)
Do not forget to return config object :-)
