### ISSUE TITLE
Nodejs19 cannot run. It's a strange bug

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt.js#10883]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/26525599/210810207-7c33fa46-23f9-4666-9c0e-0c632fc9e0cc.png">

**Comment by manniL** [comment]
As noted in the two issues you've created before: Issues with Node 18 and higher will be tracked in https://github.com/nuxt/nuxt.js/issues/10844

If you have an issue with Node16, please create a reproduction and share it in your previous issue, https://github.com/nuxt/nuxt.js/issues/10882#issuecomment-1372318449
