### ISSUE TITLE
how to hidden $nuxt in console. because risk

### ISSUE THREAD

**Issue by hendras1722** [nuxt/nuxt.js#10894]
![image](https://user-images.githubusercontent.com/57746184/211747564-fc406b0a-8246-4cb9-9003-73824d914d8e.png)

hello everbody, I need help.  how to hidden $nuxt in console ? pls reply thx you all

**Comment by danielroe** [comment]
It's possible to customise this with `globals.nuxt`: https://nuxtjs.org/docs/configuration-glossary/configuration-global-name#the-globalname-property

**Comment by hendras1722** [comment]
@danielroe Hi not update. but create globalname. I think he can replace $nuxt. can you help me ? for replace global name $nuxt

<img width="718" alt="image" src="https://user-images.githubusercontent.com/57746184/212283820-337a596a-7c9b-4465-a411-78553294d884.png">
this is work

<img width="718" alt="image" src="https://user-images.githubusercontent.com/57746184/212283506-0631b69b-0896-4acc-9f57-12e2088fa74a.png">
but $nuxt already not replace
