### ISSUE TITLE
I'm seeing a lot of comments with brakets in HTML after running yarn dev.

### ISSUE THREAD

**Issue by beardoggo** [nuxt/nuxt.js#10895]
### Versions
- nuxt: v3.0.0
- node: v18.13.0

### Summary
I'm seeing a lot of comments in HTML after running yarn dev.

### Steps to reproduce
1. Clean install VS Code
2. Clean install Nuxt with no other dependencies
3. Remove app.vue
4. Create pages folder and add an index.vue
5. `yarn dev`

### What is Expected?
No comments should appear in the HTML on Chrome browser

### What is actually happening?
Output HTML contains comments with brakets such as [ or ].
This is happening for each layout, page, or component that I use, so the resulting HTML is getting more and more flooded with these comments as I try to add another page/component.
The comments appear not only after yarn dev, but also in production build as well.
![Capture](https://user-images.githubusercontent.com/18618821/211754479-1e318bed-a31d-4a4a-b638-de4434796384.PNG)

**Comment by danielroe** [comment]
This is Vue 3 behaviour and required for supporting components without a single root element.
