### ISSUE TITLE
multi-threaded nuxt generate

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#1090]
Would it be possible to implement a multi-threaded generate command for nuxt, e.g. with [webworker-threads](https://www.npmjs.com/package/webworker-threads)? I know there are other possibilities for projects with a large number of (dynamic) pages (e.g. #418), but was wondering anyway whether we could speed-up the process by utilizing more than 1 thread.
I have a project with ~50k pages which currently takes 3+ hours to generate (about 4-5 pages per second). It seems this is at the moment cpu limited as nodejs only runs on one thread (and is the only process at 100% cpu). 

As 3+ hours is too much time for me, I am now looking at putting nginx as a caching reverse proxy in front of nuxt, but I would prefer to generate static files which I could push to an object store with cdn. My goal for this would be to be able to generate all 50k pages in half an hour max.

**Comment by walleXD** [comment]
May be a better solution for you would be to use nuxt as a standalone app rather then generating so many pages and if you have high volume data and start hitting cpu bottlenecks, you can add caching on top of that. I hostly think a project with 50k of pages shouldn't be served as a static project.But, if you really want and have no other choice, this might be an alternative: [Webpack thread-loader](https://webpack.js.org/loaders/thread-loader/)

**Comment by pimlie** [comment]
The reason I like static pages is that it removes a lot of logic thus makes it much easier to manage. E.g. when I have a static project I can generate the whole project on a backend server, then when its finished I can use an atomic move operation to update the whole webpage. So the update goes with 0 downtime (probably not applicable when using an object store or cdn as mentioned before of course).

Correct me if I am wrong, but if I use a standalone app and I need to update I would either need to
- take the app down (so not cached pages give timeout) and wait for build && start to finish (which is about 15-20 seconds for me)
- or run a separate app on another port and reload the cache engine to use that app

then after either of these options I have to invalidate all caches to make sure people are served the new content. As you have to invalidate the caches it means you will get a performance peak as for a brief moment no requests are cached at all and all of them have to be sent to the app.

Also in a production environment you'd have to add monitoring to make sure the nuxt app is still running. I looked e.g. at [eggplanetio/docker-nuxt](https://github.com/eggplanetio/docker-nuxt) to use in a production environment which uses [nuxt-cluster](https://github.com/eggplanetio/nuxt-cluster) as a server but after looking at that implementation it seems that workers are not restarted when they die / get killed. If you look at major webservers they all (have the possibility to) spawn workers for a limited time only (amount of requests) after which the worker is killed and restarted. Now you can argue whether things like that is required when the app shouldn't receive that much traffic, but for a high volume production environment I believe at least you have to take these things into account.

Static pages are just so much easier imho

I am not sure whether webpack thread-loader would be of use, isnt webpack only used during the build part of the process?

**Comment by Atinux** [comment]
Related to https://github.com/nuxt/nuxt.js/pull/751

**Comment by pimlie** [comment]
See: https://github.com/nuxt-community/nuxt-generate-cluster
