### ISSUE TITLE
Looking for help on configuring the Vue linter in the starter app

### ISSUE THREAD

**Issue by khoker** [nuxt/nuxt.js#1091]
Sorry if this is basic, but my understanding is that eslint-loader is (somehow) configured to fire up a Vue linter.  I can't figure out exactly how that's done, but I see it working.  No issues there.   
   
My problem is that I'm using v-for in a component and I'm not using a key to track them.  This is by my own design.  I get warnings at compile time ("component lists rendered with v-for should have explicit keys...":) and I want to suppress the error.  This is where I'm getting tripped-up because I'm not sure what the rule IDs actually are.   
   
If I'm correct thatr the eslint plugin being loaded is [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue), the rule ID should be "require-v-for-key", but I've tried using the following eslintrc.js config with no luck.  I still get the warnings.
   
```
module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    browser: true,
    node: true
  },
  extends: 'standard',
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  rules: {
    "vue/require-v-for-key": "off",
    "require-v-for-key": "off"
  },
  globals: {}
}
```

Anyone happen to know why this doesn't suppress the warnings for me?

**Comment by paulgv** [comment]
`require-v-for-key.md` states that

> This rule does not report custom components. It will be reported by no-invalid-v-for rule.

https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/require-v-for-key.md

So I'm guessing that you'll have to disable the `no-invalid-v-for` instead:

```json
rules: {
  "vue/no-invalid-v-for": "off"
}
```

But I would argue that you could always fulfill this rule by simply using the loop index if you can't use any other unique ID:

```html
<my-component
  v-for="(item, index) in items"
  :key="index"></my-component>
```
