### ISSUE TITLE
How to change nuxt build context when building programatically

### ISSUE THREAD

**Issue by nidin** [nuxt/nuxt.js#1093]
I have following folder structure.
```
./ -|
     '- packages
               |_ client (nuxt app)
               |       |_ .nuxt
               |_ server (express api)
                        |_ dist
```
server is loading nuxt.config.js from client and building nuxt app using javascript api.
at present nuxt is looking for dependencies in `__dirname` 
This will fail when run the app from root folder and server folder
how to change this behaviour?

**Comment by pi0** [comment]
Hi. Please check [srcDir](https://nuxtjs.org/api/configuration-srcdir/#the-srcdir-property) and [rootDir](https://nuxtjs.org/api/configuration-rootdir) options.

**Comment by nidin** [comment]
@pi0 Thanks, its working great.
