### ISSUE TITLE
Render multiple (SSR) states (locales with vue-i18n)

### ISSUE THREAD

**Issue by arenddeboer** [nuxt/nuxt.js#1094]
First of all, I'am super exited about this project. Thanks for all the hard work.

I have one nuxt instance which serves two domains with different languages. I set a default locale based on the domain, and a fallback locale. The SSR side only renders a single locale, say English, so pages loaded over the other domain (eg French) need to swap all translations at hydration time.

I probably need two code bases so I can set the locale for each domain served, and so make sure SSR renders the correct language. But I wonder if there is a way to pre render both locales and select the right one on page load.

**Comment by paulgv** [comment]
If some of your routes are dynamic, you need to specify what paths Nuxt should generate by adding them manually to your config.
Have a look at `nuxt.config.js` in the i18n example : https://nuxtjs.org/examples/i18n
Also, you might find this useful : https://nuxtjs.org/api/configuration-generate/#routes

**Comment by arenddeboer** [comment]
Thanks paulgv, the problem is that the paths are identical, only the domain name is different:
The nuxt instance is serving for example www.mydomain.com and www.mydomain.fr
Based on the TLD  extension I set the local 'en' or 'fr' which will translate the menu links, buttons, etc
But the server side rendering does not know about which domain is requested, and by definition will probably only render a single predetermined state.

**Comment by paulgv** [comment]
I would way that you still need to do something that looks like the i18n example to have both languages pre-rendered in separate directories, then you could make your `.com` domain point on the site's root, and the `.fr` domain on the `/fr` directory.

**Comment by arenddeboer** [comment]
Ahh, that makes sense. I am already using much of the nuxt i18n example and it sounds like a logical solution if possible. Thanks for the pointer.
