### ISSUE TITLE
[fixed] How to configure nuxt.js using nginx and proxy

### ISSUE THREAD

**Issue by davidcostadev** [nuxt/nuxt.js#1096]
Hello everyone, I'm trying to put in nuxt for the first time in production. And when I put there the images, javascript and css files, are giving 404 error. I will pass my settings.

Ubuntu: 16.05
Nginx: last
Nodejs: 6
Nuxt.js: last

Ngnix proxy file config

```
server {
       listen 80;
       listen [::]:80;

       server_name davidcosta.com.br www.davidcosta.com.br;

       location / {
               try_files $uri $uri/ =404;
                proxy_pass http://localhost:8080;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;

       }
}
```

My files projects
https://github.com/davidcostadev/davidcosta.com.br

I can not understand at the moment because it is giving error.

**Comment by xerq** [comment]
Did you try removing the `try_files` line? Seems for me like it's the issue.

**Comment by davidcostadev** [comment]
ohhh thanks that work now! @xerq
