### ISSUE TITLE
Allow custom port # through npm config

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#11]
First off, great work so far on nuxt.js

For this issue, some documentation here:
https://docs.npmjs.com/files/package.json#config

Ideally, the package.json would then look like this:
```json
{
  "scripts": {
    "start": "nuxt"
  },
  "config": {
    "nuxt": {
      "port": 4000
    }
  }
}
```

This is critical for folks who want to host multiple nuxt.js apps/sites on one server.

**Comment by Atinux** [comment]
Hi @jaredreich 

Actually you can already configure the port via the `PORT` environment variable.
```json
{
  "scripts": {
    "start": "PORT=4000 nuxt"
  }
}
```

I already added the option to add the port in the `package.json` as you suggested, it will be in the next release.

**Comment by jaredreich** [comment]
Sweet, great work!

**Comment by Atinux** [comment]
You can now use the version [`0.6.5`](https://github.com/nuxt/nuxt.js/releases/tag/v0.6.5) to set the port with the `package.json`

**Comment by jaredreich** [comment]
Cool, perhaps this could make it into the docs for others to see?

Cheers.

**Comment by Atinux** [comment]
It's planned :)

**Comment by jaredreich** [comment]
Awesome. Again great work so far. 👍
