### ISSUE TITLE
Using external resources with Nuxt

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#110]
Hi I have been reviewing nuxt.js and so far am very impressed. 

I have tried to implement a simple project. But had certain issues and was wondering if that is possible here or not.

To start with how can i refer to external resources, be it js file or css.

let's say I want to use bootstrap. How could I import boostrap's css and js? if this is possible, i would appreciate if it would be possible to share both approaches:
 
1) locally  (from static folder)
2) externally directly from cdn, without including the files in the project

Thanks in advance

That am sure will be very useful to many others

**Comment by mixty1** [comment]
You can set external script or css like this:

// nuxt.config.js
````
module.exports = {
  head: {
    titleTemplate: '%s - Nuxt.js',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Meta description' }
    ],
    script: [
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js' }
    ],
    link: [
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto' }
    ]
  }
}

**Comment by husayt** [comment]
Thank you very much. This was really useful. But what if I want to load these for only specific pages?

**Comment by Atinux** [comment]
Hi @husayt 

Thank you @mixty1 for your answer, it's the perfect answer for the 2) asked by @husayt 

If you want to load it only for a specific page, you can add the `head` property in your page file:
`pages/about.vue`:
```html
<template>
  <h1>About page with jQuery and Roboto font</h1>
</template>

<script>
export default {
  head: {
    script: [
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js' }
    ],
    link: [
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto' }
    ]
  }
}
</script>
```

**Comment by cschweda** [comment]
Is there a webpack.config.js somewhere that's editable?

**Comment by Atinux** [comment]
You can extend the webpack configuration trough `nuxt.config.js` with the `build.extend` method. The doc about these configurations is coming this week!

You can take a look at the `examples/custom-build/` folder to see how it works.

**Comment by cschweda** [comment]
Aha! Wow -- this looks great. Thanks. This should do the trick!
