### ISSUE TITLE
PostCSS plugins don't do anything

### ISSUE THREAD

**Issue by benjarwar** [nuxt/nuxt.js#1100]
I'm trying to add some PostCSS plugins. Currently trying to get [pxtorem](https://github.com/cuth/postcss-pxtorem) working, but my compiled CSS is unchanged. Here's the relevant config:

```
module.exports = {
  css: [
    { src: '~assets/scss/main.scss', lang: 'scss' }
  ],

  build: {
    postcss: [
      require('postcss-pxtorem')({
        propList: ['*']
      })
    ]
  }
}
```

**Comment by damian-nz** [comment]
@benjarwar this is similar to [my issue](https://github.com/nuxt/nuxt.js/issues/1107). I found that you need to overite the default Sass loader like [this](https://vue-loader.vuejs.org/en/configurations/advanced.html) but then that causes another issue (which is what my issue is about).

**Comment by casio** [comment]
@benjarwar I was stumbling into the same - postcss plugins configured just fine in `nuxt.config.js`, but my css was not getting processed whatsoever. I was using `nuxt.config.js`s `css` field to specify my global css file.

However, I got it to work now by still using the config file to set postcss options, but to include my css from ie `pages/index.vue` using just the `style` element(without `lang` attr!).

Kinda like this

```
# pages/index.vue

...

<style>
@import "../styles/index.css";
</style>

...

# nuxt.config.js

...

build: {
    postcss: [
      require('postcss-easy-import')(),
      require('postcss-custom-properties')(),
      require('postcss-calc')(),
      require('postcss-custom-media')(),
    ]
  }

...
```

Btw in your above post, you got a typo: `lang: 'scss'`?!

**Comment by didiself** [comment]
Is that your want use scss in global css with post-css??

**Comment by benjarwar** [comment]
@didiself that is the use case. Looking to use SASS for pre-processing, then using postCSS for autoprefixing, pxtorem, etc. Bad practice?

**Comment by didiself** [comment]
@benjarwar of course not.

this is my config.
![image](https://user-images.githubusercontent.com/14201030/28447954-d64672ae-6e06-11e7-8534-6ddf5151fbef.png)

sass-resources-loader & postcss-loader can use in vue & scss.

but need add a postcss.config.js in root dir, for the line 42.  
// I can't find a better way to reuse the postcss config in nuxt.config.js  for now.

![image](https://user-images.githubusercontent.com/14201030/28448058-9af28728-6e07-11e7-9105-4b42106ca999.png)

last, sometimes run dev will console some error about scss, but pages still normal. 

hope somebody can tell me why. LOL

**Comment by piyushchauhan2011** [comment]
Does adding `postcss-scss` [scss](https://github.com/postcss/postcss-scss) will work ?

**Comment by didiself** [comment]
of course @piyushchauhan2011

**Comment by benjarwar** [comment]
Thanks for the advice, folks!

@didiself I'm trying your solution, but the compiled CSS still seems unaffected.

Here's my `nuxt.config.js`:

```
const pxtorem = require('postcss-pxtorem');
const StyleLintPlugin = require('stylelint-webpack-plugin');
const { resolve } = require('path');

const isVueRule = (rule) => {
  return rule.test.toString() === '/\\.vue$/'
}

const isSCSSRule = (rule) => {
  return rule.test.toString() === '/\\.scss$/'
}

const sassResourcesLoader = {
  loader: 'sass-resources-loader',
  options: {
    resources: resolve(__dirname, './assets/scss/main.scss')
  }
}

module.exports = {
  css: [
    { src: '~assets/scss/main.scss', lang: 'scss' }
  ],

  build: {
    loaders: [
      {
        test: /\.md$/,
        loaders: ['markdown-with-front-matter-loader']
      },
      {
        test: /\.svg$/,
        loaders: ['svg-sprite-loader']
      },
      {
        test: /\.(woff2?)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 1000,
          name: 'fonts/[name].[hash:7].[ext]'
        }
      }
    ],

    plugins: [
      new StyleLintPlugin({
        files: 'assets/scss/**/*.scss'
      })
    ],

    postcss: [
      require('autoprefixer')({
        browsers: ['last 2 versions']
      }),
      require('postcss-pxtorem')({
        propList: ['*']
      })
    ],

    vendor: [
      'babel-polyfill'
    ],

    /*
    ** Extend Nuxt Webpack config
    */
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }

      config.module.rules.forEach((rule) => {
        if (isVueRule(rule)) {
          rule.query.loaders.scss.push(sassResourcesLoader)
        } else if (isSCSSRule(rule)) {
          rule.use.push('postcss-loader', sassResourcesLoader)
          console.log(rule)
        }
      })
    }
  }
}
```

And here's `postcss.config.js`:

```
module.exports = {
  plugins: [
    require('autoprefixer')({
      browsers: ['last 2 versions']
    }),
    require('postcss-pxtorem')({
      propList: ['*']
    })
  ]
}
```

No errors in the console. When I log out the `rule` in the `else if (isSCSSRule(rule))` block, it looks like the `postcss-loader` has been properly added:

```
{ test: /\.scss$/,
  use: 
   [ 'vue-style-loader?sourceMap',
     'css-loader?sourceMap',
     'sass-loader?sourceMap',
     'postcss-loader',
     { loader: 'sass-resources-loader', options: [Object] } ] }
```

RE @piyushchauhan2011's suggestion of `postcss-scss`, I'm not sure how to implement, since that doesn't compile the SCSS.

**Comment by piyushchauhan2011** [comment]
I also haven't tried integration of `postcss-scss`, having problems with `postcss with scss` hence currently we shifted to `postcss` only. Apparently the editor support is not quite good, and keep getting warnings related to sourceMap if use `lang="postcss"` in `.vue` files. Not sure how to remove them. @benjarwar 

Will try today, let's see if the above works for me too!

**Comment by benjarwar** [comment]
Thanks, @piyushchauhan2011, keep me posted.

@Atinux saw your comment over on @damian-nz's [similar Issue](https://github.com/nuxt/nuxt.js/issues/1107#issuecomment-316801898). Any thoughts? I think I'm applying your [recommended config](https://glitch.com/edit/#!/sass-resources-loader-nuxt) correctly, but postCSS doesn't affect the output of compiled global SCSS files (see configs above).

**Comment by damian-nz** [comment]
@benjarwar @Atinux I have been AFK. I too have attempted to apply the same config as was suggested and also cannot get postCSS to do anything. 

My issue has been closed but I will follow this thread along now that we have the same problem and now that this one has been labeled as a bug

**Comment by pi0** [comment]
PostCSS support is improved a lot. Coming with `rc5` :) Also while the old array will be still supported, here is recommended usage:  (Another option is using `postcss.config.js` which will be automatically detected if exists in your project) 

```js
  postcss: {
      'postcss-pxtorem': { propList: ['*'] }
   }
```

Will update docs after release too.

**Comment by Atinux** [comment]
Please upgrade to rc5 :)

https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc5

**Comment by benjarwar** [comment]
Thanks, @pi0 and @Atinux!

**Comment by rlam3** [comment]
I'm trying to use rupture and lost with stylus in my vue files. I've already installed the node_modules and added them to my nuxt.config.js file but it seems like when I try to use rupture or lost, it doesn't understand it....

https://github.com/jescalan/rupture
https://github.com/peterramsing/lost#vertical-grids

Are there some external configuration from the nuxt.config.js file that I need to do for them to work properly? Thanks! 

```
  /*
  ** PostCSS Plugins
  */
  postcss: [
    require('lost')(),
    require('rupture')(),
    require('axis')(),
    require('postcss-nested')
  ]
```

**Comment by Norbz** [comment]
Having the same issue here trying to use Stylus with Rupture.

I had no problem using SASS libraries, but this isn't the same with Stylus.

I tried adding them in nuxt.config.js :

`config.plugins.push(new webpack.LoaderOptionsPlugin({
          test: /\.styl$/,
          stylus: {
            default: {
              use: [rupture()], // rupture is required above
            },
          },
        }));`

Since I added this, I get no errors when building, but I land on the Nuxt error page :
`failed to locate @import file rupture.styl at CachedPathEvaluator.visitImport (/Users/.../Sites/project/node_modules/stylus-loader/lib/evaluator.js:157:21)`

I'm sure I'll get to the bottom of this somehow but if someone already solved this and wanna help, that would be delightful

**Comment by eybarta** [comment]
@rlam3 did you get rupture to work? 
When I added it to postcss: [] as you did, I'm getting a build error,
something about style.include.. ?!

**Comment by rlam3** [comment]
@eybarta no i didn't I'm still trying to figure out nuxt plugins as well... i opted to use css media as a workaround for the time being. if you find anything please let me know as well. :)
