### ISSUE TITLE
Ability to dynamically change the url's query params

### ISSUE THREAD

**Issue by rwatts3** [nuxt/nuxt.js#1101]
Is it possible to change the url's query params based on a change in a field input ?

**Comment by pi0** [comment]
Hi. Please try this:
```js
this.$router.push({path: this.$route.path, query: { foo: 'bar' }})
```

**Comment by rwatts3** [comment]
flawless, thank you

**Comment by rwatts3** [comment]
hmm, push doesn't seem to be updating the url is there a specific place I should be doing this ? 
`this.$router.push({path: this.$route.path, query: { site: this.site }});`

**Comment by rwatts3** [comment]
got it I was hard assigning the query param in an earlier attempt.
