### ISSUE TITLE
Provide hook to add custom class to #__nuxt wrapper

### ISSUE THREAD

**Issue by benjarwar** [nuxt/nuxt.js#1102]
I need to style the parent [App.vue wrapper](https://github.com/nuxt/nuxt.js/blob/dev/lib/app/App.vue#L2), setting it to 100% height to allow for a sticky footer component. Would be great to have a config option to pass a class to this template, rather than having to style `#__nuxt`, which seems privately designated (and it's poor practice to make style declarations assigned to ids).

**Comment by alexchopin** [comment]
Hi @benjarwar,
You can use the [document](https://nuxtjs.org/guide/views#document) option and add a container (with a custom class) to wrap the Nuxt App:
```html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    <div class="myCustomClass">
        {{ APP }}
    </div>
  </body>
</html>
```

**Comment by benjarwar** [comment]
@alexchopin thanks for the reply. That won't fix my issue, unfortunately. I need the `#__nuxt` element to span 100% of the window height. Your solution would provide me with this markup:

```
<body>
  <div class="myCustomClass">
    <div id="__nuxt"> ... </div>
  </div>
</body>
```

I'd still have to target `#__nuxt` and its parents, setting them to 100% height, in order to [push a footer to the bottom of the page with flexbox](https://css-tricks.com/couple-takes-sticky-footer/#article-header-id-3).

**Comment by crswll** [comment]
@benjarwar You'd save yourself a lot of headache by ditching the percentages and using `100vh` instead.

**Comment by benjarwar** [comment]
@crswll That's a great suggestion, thanks! I still see utility for providing a way to directly modify the Nuxt wrapper element, but this works.

**Comment by liamcharmer** [comment]
@benjarwar I know this is super late and all that. But surely can't you just put the #__nuxt in the css? 

` div#__nuxt,
  #__layout,
  #__layout>div,
  #app {
    min-height: 100vh;
  }`
