### ISSUE TITLE
Vue-slick usage

### ISSUE THREAD

**Issue by dinokajtez** [nuxt/nuxt.js#1103]
Hi, i am ajusting my vuejs app to work with Nuxt and i am having problem with vue-slick caousel library. I need help how to use it with Nuxt.

The way i use is:
import Slick from 'vue-slick';
...
data() {
   // slick options
}
...
components: {
            'slider': Slick
        }

Thanks

**Comment by dinokajtez** [comment]
This is the error i am getting:

SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at r (/Users/dinokajtez/Websites/etr-client-ssr/node_modules/vue-server-renderer/build.js:6964:16)
    at Object.<anonymous> (webpack:/external "vue-slick":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 89eafc9a72efc28dbf24:25:0)
    at Object.exports.modules.259 (7.server-bundle.js:521:68)
    at __webpack_require__ (webpack:/webpack/bootstrap 89eafc9a72efc28dbf24:25:0)
    at Object.exports.modules.260 (components/slider-big.vue:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 89eafc9a72efc28dbf24:25:0)
    at Object.exports.modules.188 (7.server-bundle.js:402:85)
    at __webpack_require__ (webpack:/webpack/bootstrap 89eafc9a72efc28dbf24:25:0)

**Comment by davidcostadev** [comment]
i think that you should show your code better

**Comment by dinokajtez** [comment]
This is the code:

`<script>
    import Slick from 'vue-slick'
    import productItem from './product-item.vue'
    import store from '../app-store.js'
    import router from '~router'
    import { EventBus } from '../event-bus.js';
    import NoSSR from 'vue-no-ssr';

    export default {
        props: ['products'],
        data() {
            return {
                slickOptions: {
                    centerMode: this.products.length < 4,
                    infinite: this.products.length < 4,
                    slidesToShow: this.products.length < 3 ? this.products.length : 3,
                    slidesToScroll: 1,
                    dots: true,
                    speed: 600,
                    prevArrow: '<div class="slider-arrow slider-prev"></div>',
                    nextArrow: '<div class="slider-arrow slider-next"></div>',
                    responsive: [
                        {
                            breakpoint: 960,
                            settings: {
                                slidesToShow: 2,
                                dots: true,
                                arrows: false,
                                swipe: true
                            }
                        },
                        {
                            breakpoint: 767,
                            settings: {
                                slidesToShow: 1,
                                dots: true,
                                arrows: false
                            }
                        }
                    ]
                }
            }
        },
        methods: {
            beautifyString(string) {
                string = string.replace(/[^a-zA-Z0-9 ]/g, "")
                return string.replace(/\s/g, "-")
            }
        },
        components: {
            'etr-product-item': productItem,
            'slider': Slick,
            'no-ssr': NoSSR
        }
    }
</script>`

**Comment by davidcostadev** [comment]
use 
this.products.length < 4 ? true : false

instend of
this.products.length < 4

**Comment by dinokajtez** [comment]
I tried what you suggested but i get the same error.

**Comment by paulgv** [comment]
Looks like the component might have some trouble with server-side rendering.
Try this:

```js
const Slick = process.BROWSER_BUILD ? require('vue-slick') : null
```

instead of:

```js
import Slick from 'vue-slick'
```

**Comment by dinokajtez** [comment]
Nice one, this worked. Thanks a lot.

**Comment by luongvanphuc** [comment]
@dinokajtez I'm still stuck with this issue, can you please re-explain the solution to make vue-slick work with nuxtjs. I was spending days to solve frontend libaries to work with nuxtjs like slick and scrollmagic.
