### ISSUE TITLE
DEBUG environment overridden alpha.5

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#1104]
I also use the debug library on my app and when attempting to set the DEBUG environmental variable, nuxt overrides this value with nuxt:*

**Comment by paulgv** [comment]
How are you setting the DEBUG env variable?

**Comment by uptownhr** [comment]
I've tried setting before running nuxt like 'DEBUG=TEST:* yarn dev' and
also using my dotenv

**Comment by pi0** [comment]
This problem should be fixed with f30a4f716971f60c3eeba897c1363149741793ff and will ship with next release :)
