### ISSUE TITLE
Please Help! router-view vs nuxt component

### ISSUE THREAD

**Issue by PiusNyakoojo** [nuxt/nuxt.js#1105]
Hello there,

I am using the "nuxt" component to embed route components in a layout but it seems that events from v-on are not being listened to.

This is something that is **expected to work but doesn't**:

```html
<nuxt v-on:some-event="doSomething()" />
```

Should I be using \<router-view\> instead? When using \<router-view\>, events are picked up but there is an **error in the console** that reads

```bash
[Vue warn]: Error in mounted hook: "TypeError: Cannot set property '$loading' of undefined"

(found in <Root>)
```

Thank you very much! 😄

**Comment by heejongahn** [comment]
Looks like event handler is triggered just fine to me. Based on the error message, my guess is you are referring to wrong `this` in `mounted`. This can happen if you use an arrow function as `mounted` lifecycle hook - see [the documentation](https://vuejs.org/v2/api/#Options-Lifecycle-Hooks).

Can you embedded the entire code or the repository regarding this error?

**Comment by heejongahn** [comment]
Never mind - looks like `$loading` is nuxt internal and I also checked that `@click` doesn't work on `<nuxt />` too.

Still, embedding the code would help IMO. Sorry for the confusion 😅 and good luck!

**Comment by PiusNyakoojo** [comment]
Here is a simplified example of the **source code** we are working with.

https://glitch.com/edit/#!/stupid-hide?path=package.json:13:37

Here is the **demo**:

https://stupid-hide.glitch.me/

**Comment by alexchopin** [comment]
@PiusNyakoojo why don't you use the store in this case?

**Comment by PiusNyakoojo** [comment]
Well, this was a simple case.

The code looks more like this:

```html
<router-view
  :dark-header="darkHeader"
  v-on:show-media="selectDialog(dialogTypes.media, $event)"
  v-on:show-error="selectDialog(dialogTypes.error, $event)"
  v-on:show-message="selectDialog(dialogTypes.message, $event)"
  v-on:are-you-sure="selectDialog(dialogTypes.areYouSure, $event)"
  v-on:set-dark-header="setDarkHeader($event)"
  v-on:dialog-selected="selectDialog($event)"
  v-on:close-dialog="hideOverlay()"></router-view>
```

Are you suggesting to use the store to communicate these things? That could work. I'll have to think about the complexity of this implementation. On initial thought it seems so bothersome, but maybe it's not 😄

**Comment by PiusNyakoojo** [comment]
After some thought, your suggestion seems to work better than doing things in the default layout.

Thanks a lot @alexchopin  😃
Thanks also to you @heejongahn 😊

For those who might benefit from this, here is the **source code** of the previous example updated to use the store technique:

https://glitch.com/edit/#!/aspiring-iron?path=package.json:2:22

Here is the **demo**:

https://aspiring-iron.glitch.me/

**Comment by Prozi** [comment]
replace `<router-view></router-view>` with `<nuxt></nuxt>` if u got similar problem
