### ISSUE TITLE
Load component from <script> tag

### ISSUE THREAD

**Issue by elBarkey** [nuxt/nuxt.js#1106]
Hi. is it possible to load component from script tag ?
I am building nw.js app on client side & using nuxt on server side.
This app needs to load compiled v8 snapshot within xhr response using [nw.Window.get().evalNwBin()](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/).
In regular html it looks like this:

```html
<html>
<head></head>
<body>
<script>
var url = "/myComponent.bin";
var xhr = new XMLHttpRequest();
xhr.responseType = 'arraybuffer'; // make response as ArrayBuffer
xhr.open('GET', url, true);
xhr.send();
xhr.onload = () => {
  // xhr.response contains compiled JavaScript as ArrayBuffer
  nw.Window.get().evalNWBin(null, xhr.response);
}
</script>
</body>
</html>
```

or is it possible to use component that loads like:

```html
<script type="text/javascript" src="/mycomponent.js"></script>
```

Thanks.

**Comment by elBarkey** [comment]
for the 2nd point, this is my workaround.

- load the hosted non-ssr component inside static through head config:
```javascript
head: {
script: [
  {type: 'text/javascript', src: '/mycomponent.js'} //this makes my component exposed to global window.mycomponent
 ]
}
```
- create non-ssr plugin
```javascript
import Vue from 'vue'
Vue.component('mycomponent',window.mycomponent)
```

i know this is kinda "hackish" & unnecessary for typical component loading, but to get this working with nw.js API this is important.
if someone has better idea, suggestion are welcomed.

**Comment by Atinux** [comment]
HI @elBarkey 

I never used `.bin` files but your workaround seems to be the perfect solution :)

**Comment by epartipilo** [comment]
Hi @elBarkey 
What about your components on SSR? Don't you need them?

**Comment by elBarkey** [comment]
No, i didn't. The only target is my nwjs app client have an ability to load statically hosted compiled nw binary. So i don't need it on SSR at all.
