### ISSUE TITLE
Export or distribute components for distribution.

### ISSUE THREAD

**Issue by rwatts3** [nuxt/nuxt.js#111]
Greetings,

Is there a way to export individual components for distribution.
If I am attempting to create a library or have components, distributed to other people to use, but in js format not vue format what is the best way to do this? 

Essentially I'm trying to see how I can share and use components across different projects and with other users.

**Comment by Atinux** [comment]
Hi @rwatts3 

You can check these projects for sharing vue components:
- [vue-share-components](https://github.com/Akryum/vue-share-components)
- [rollup-vue-plugin](https://github.com/znck/rollup-plugin-vue) based on [rollupjs](http://rollupjs.org/)

Looking forward to see you Vue components :)

**Comment by rwatts3** [comment]
Thank you

**Comment by posva** [comment]
@rwatts3 [This template](https://github.com/posva/vue-plugin-template) focus on visual testing and bundles your components with the above rollup plugin for smaller bundles. In case that's what you're looking for 🙂

**Comment by rwatts3** [comment]
Hmm I will definitely give that one a shot as well.

Thank you
