### ISSUE TITLE
use `npm run generate` deploy on AWS S3 don't work

### ISSUE THREAD

**Issue by LXVC** [nuxt/nuxt.js#1114]
![image](https://user-images.githubusercontent.com/12185175/28363393-fa538c40-6cb2-11e7-802d-ae506dac8fc4.png)

The first three file types are normal and the other files are not normal。
return 200，but there no content:

![image](https://user-images.githubusercontent.com/12185175/28363551-8afc3a62-6cb3-11e7-8282-e46f5cc0b26a.png)

![image](https://user-images.githubusercontent.com/12185175/28363528-79146324-6cb3-11e7-88a5-63faf5afe3f7.png)

**Comment by alexchopin** [comment]
You have to explain more about your issue if you want us to help you.

**Comment by LXVC** [comment]
@alexchopin I npm run generate, and deploy the static file on AWS S3, some JavaScript file has the correct Type(script)，but some JavaScript don't have(they are text/javascript), (text/javascript) files don't have response body. so page don't work.

**Comment by Atinux** [comment]
Hi @LXVC 

I just tried to add the hello-world demo on AWS S3 and here the result: http://nuxt.s3-website-eu-west-1.amazonaws.com

As you can see it works fine, please think to activate the `Static website hosting` feature: http://docs.aws.amazon.com/AmazonS3/latest/dev/HowDoIWebsiteConfiguration.html
