### ISSUE TITLE
Production ready? 

### ISSUE THREAD

**Issue by liorix** [nuxt/nuxt.js#1115]
Hi, 
Nuxt looks amazingly easy to use but I was wondering if nuxt is stable for a high traffic production web app. Is there a list of companies who are using it in production? 

Thanks, 
Lior

**Comment by davidcostadev** [comment]
I have the same question.

**Comment by alexchopin** [comment]
Yes, it's production ready. 
The reason why it's not v1 yet is uncompleted features.
We use it in our companies in production with high traffic and critical data.

**Comment by awronski** [comment]
We are using nuxt alfa version on two productions site. Not huge, but more than 100k UU/month.
And is working great!

**Comment by liorix** [comment]
Thanks for the quick feedback, that's great to know. 
Lior
