### ISSUE TITLE
how to use babel-polyfill for entry 

### ISSUE THREAD

**Issue by lemonpigpig** [nuxt/nuxt.js#1118]
![0a950f6533750183a25404e457b0f77f](https://user-images.githubusercontent.com/17818782/28377007-26a74fb8-6cde-11e7-8b11-82ceac937c23.png)
why i have to add babel-polyfill,my pc application only work in chrome and firefox,other like qq browser cannot load.i found that js file have a error,and some es6 still exist, my config is 
```js
 build: {
    babel: {
      presets: ['es2015', 'stage-2'],
      'plugins': ['transform-runtime']
    },
    extractCSS: true,
    vendor: [
      'babel-polyfill',
      'eventsource-polyfill',
      'swiper',
      'axios'
    ]}
```
but after build i found nothing have change, tell my the right way,my application will online soon,i need your help really, thx

**Comment by pi0** [comment]
Hi.; Adding babel-polyfill should resolve problems. I'm not a qq user, so maybe @ausir0726 can help us for this?

**Comment by lemonpigpig** [comment]
for babel-polyfill is too much, or have other reason @ausir0726  @pi0  i have to solve this

**Comment by lemonpigpig** [comment]
@pi0 but it really cannot work, i wonder if my nuxt.config is wrong, can you have a look, and i have a  doubt ,bable-polyfill should add at the entry, should i have wrong add at vendor,

**Comment by pi0** [comment]
@lemonpigpig Is your repository accessable using github?

**Comment by Atinux** [comment]
Hi @lemonpigpig 

I am using QQ for Mac and it works fine (they use Chromium under the hood).

Can you translate the error you have in English please so we can help you?

**Comment by Guxinpei** [comment]
@Atinux 
The red word means “missing identifier”&“missing identifier string or number”,
I think it means that babel not work, I face the same problem now.

**Comment by lemonpigpig** [comment]
@Atinux  you have resolved , now qq is ok,but ie still not work

**Comment by lemonpigpig** [comment]
@Atinux sorry the ie11 now is work but the ie9 still not work,the error is meaning that can not get the
the attribute value of data, cannot get the attribute value of name, cannot get attribute value of split,
i am sure is the error of es6 not supporting by the browser,i will show my nuxt.config.js, can me have a look please my god the deadline is coming
<img width="980" alt="2017-07-25 5 04 10" src="https://user-images.githubusercontent.com/17818782/28564359-5d848984-715b-11e7-9e05-0e132603df46.png">

**Comment by rancyTao** [comment]
Have you fixed it ?

**Comment by wLove-c** [comment]
@lemonpigpig  请问一下，您的问题是不是在IE和qq浏览器无法编译es6语法的问题，我这边也遇到了这个问题，可以请教一下您是用什么方案解决的吧，如果方便的话 ，麻烦了

**Comment by luke-Yang** [comment]
请问问题解决了吗？我这边ie9 就报错**语法错误：**

**Comment by rancyTao** [comment]
还是存在




发自网易邮箱大师


在2017年11月29日 16:43，luke-Yang<notifications@github.com> 写道：

请问问题解决了吗？我这边ie9 就报错语法错误：

**Comment by wLove-c** [comment]
@luke-Yang  @rancyTao  你的在ie edge下面不会报语法错误吗？或者ie10 我现在在考虑要用vue+ssr 重做还是兼容到ie9就好了，我这边ie edge都不行 你们怎么配置的 可以上代码或者图吗

**Comment by luke-Yang** [comment]
@wLove-c  我的项目在edge是可以跑的没有问题，但是在360兼容模式下面就会报语法错误，然后我定位到错误那边是有一个箭头函数，不知到为什么babel-polyfill没有转语法

**Comment by wLove-c** [comment]
@luke-Yang 我的在edge都跑不了 也是那个箭头函数的问题，也是用的babel-polyfill,可以看看你的config配置吗，和babel-polyfill版本...麻烦了

**Comment by clarkdo** [comment]
@wLove-c @luke-Yang Can you have a try on 1.0.0 ?

**Comment by yoyo837** [comment]
Babel-polyfill只是提供ES新增语法的，比如并不是负责转义ES6+语法糖的...
Babel默认只转换新的JavaScript句法（syntax），而不转换新的API，比如Iterator、Generator、Set、Maps、Proxy、Reflect、Symbol、Promise等全局对象，以及一些定义在全局对象上的方法（比如Object.assign）都不会转码。
举例来说，ES6在Array对象上新增了Array.from方法。Babel就不会转码这个方法。如果想让这个方法运行，必须使用babel-polyfill，为当前环境提供一个垫片。
