### ISSUE TITLE
Come back to nuxt-view and nuxt-child

### ISSUE THREAD

**Issue by StasB93R** [nuxt/nuxt.js#1119]
This in regards of this https://github.com/nuxt/nuxt.js/issues/1116
I have uploaded this repo, i did everything as you have suggested but it doesnt show the stuff in parent component. EDIT: It simply redirects you to a completely new page, without the parent data displayed, please help out
 
Repo: https://github.com/StasB93R/nuxt-child
Would be interested to know why its doing this, so please enlight me :)

**Comment by alexchopin** [comment]
@StasB93R please read the [documentation](https://nuxtjs.org/guide/routing#nested-routes) before posting an issue here.
You don't use nested-routes correctly:
1) You should use `<nuxt-child/>` only once: https://github.com/StasB93R/nuxt-child/blob/master/pages/index.vue#L7
2) If you use it in your `index.vue` file, you have to create an `index` folder which contains your `sub1.vue` and `sub2.vue` file.
3) I recommend you to check out some example available on the documentation website or to ask the community on gitter before posting an other issue here.
