### ISSUE TITLE
Can't import/require store from plugin

### ISSUE THREAD

**Issue by alekbarszczewski** [nuxt/nuxt.js#1120]
In `~plugins/test.js`:

```js
import store from '~store'
const store2 = require('~store')

console.log(store)
console.log(store2)
```

output:

![screen shot 2017-07-19 at 19 44 04](https://user-images.githubusercontent.com/2742373/28381359-d52bd866-6cba-11e7-9164-b6e7bb9030ec.png)

How I can access store from plugin or any other place that is not a component/page/layout?  
Note: exactly the same happens with `'~router'`.

Nuxt 1.0.0-alpha.4

According to docs it should work:

![screen shot 2017-07-19 at 19 48 37](https://user-images.githubusercontent.com/2742373/28381578-aae0cd22-6cbb-11e7-8441-f722a3dd2955.png)

**Comment by mgesmundo** [comment]
Same problem into 1.0.0-alpha.5

**Comment by paulgv** [comment]
You can get the store (and router) from the plugin's parameters.

```js
// plugins/my-plugin.js

export default ({ app: { store, router } }) => {
  // Do whatever with the store or router here
}

```

**Comment by alekbarszczewski** [comment]
Perfect, thanks!
I think there is no info in docs (https://nuxtjs.org/guide/plugins) that it is possible to export function in plugins.

**Comment by mgesmundo** [comment]
Thanks a lot!
All the best
