### ISSUE TITLE
generate error about "headers"

### ISSUE THREAD

**Issue by didiself** [nuxt/nuxt.js#1123]
npm run generate
![image](https://user-images.githubusercontent.com/14201030/28400047-61f63a2e-6d43-11e7-962b-5ac71148e084.png)

my pages
![image](https://user-images.githubusercontent.com/14201030/28400054-6bad57c8-6d43-11e7-945d-5ad4a4a3e338.png)

list.vue
![image](https://user-images.githubusercontent.com/14201030/28400088-89a91b7c-6d43-11e7-86ab-b2d0b4ab6f8e.png)

what's wrong and how to fix ???

**Comment by Atinux** [comment]
This error comes when you try to access `req.headers` somewhere (maybe in a middleware for your project).

When using `nuxt generate`, keep in mind that `req` & `res` are `undefined`. See https://nuxtjs.org/api#context

**Comment by didiself** [comment]
@Atinux thanks for your reply.  
you are right. But still don't understand.

I write a middleware for get user-agent, and use in layout.
```
export default function (context) {
  if (context.isServer) {
    let ua = context.req.headers['user-agent']
    context.app.store.state.isWX = !!(/micromessenger/.test(ua.toLowerCase()))
  }
}

``` 

I just get some info ,  didn't change any thing.
How can I improve the code??

**Comment by didiself** [comment]
After thinking , I try get userAgent in client.
so generate done without error.

but I think it's should running in server.

**Comment by Atinux** [comment]
@didiself it cannot run on the server-side since no server is run when `nuxt generate` & no navigator is used to generate the route.
