### ISSUE TITLE
Exclude some pages from production build 

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#1125]
Hi guys, tell me please, can I exclude some pages from production build? 

As example, I have a editor admin pages which include: WYSIWYG-editor, codemirror and other libs. Can I remove this pages and deps from production build and vendors file by condition?

**Comment by Atinux** [comment]
Hi @ruslankonev 

Every pages creates its own bundle, for example if you only import `codemirror` and others libs inside this admin page (and not adding them in `build.vendor`), then, these libs will be only included in the page bundle.

You can then add a middleware to avoid the `/admin` root in production for example.
