### ISSUE TITLE
Basic http auth

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#1126]
Hi,
 I would like to add basic http authentication to a subset of routes. 
For eg: **/app/*** should have basic http authentication. 
I couldn't find  an example. 
Pls help

**Comment by pi0** [comment]
Hi. Which version are you currently using? Also would please provide more details about use case?
 I mean how should auth useful without protecting API itself?

**Comment by shyamchandranmec** [comment]
@pi0  version 1.0.0 alpha.3 . I have another app using version 0.10.5.
These are just protected pages which will be accessible to only few people. Api interactions are very rare in such pages. 

This will help us to create protected pages quickly without setting up authentication.

**Comment by pi0** [comment]
I've provided a minimal example for basic auth using next 1.x `serverMiddleware` feature:
https://glitch.com/edit/#!/nuxt-basic-auth?path=auth.js:13:8
https://nuxt-basic-auth.glitch.me/about

But consider that this is not enough. Client side routes should be protected to using middleware. (For example when navigate from / => /about)

**Comment by shyamchandranmec** [comment]
@pi0 Thanks for the example.
