### ISSUE TITLE
How to load modules before plugins in nuxt.config

### ISSUE THREAD

**Issue by solonik1** [nuxt/nuxt.js#1127]
Nuxt loads plugins before modules (@nuxtjs/axios). Thus the axios instance is not available in plugins. How to change it? thx for your help!

**Comment by pi0** [comment]
Hi. What do you mean about modules? If about Axios module, It is also providing a plugin itself :) Would you please share generated `.nuxt/index.js` file? I think problem is that it should register plugin as the first.

**Comment by solonik1** [comment]
[index.js.txt](https://github.com/nuxt/nuxt.js/files/1163225/index.js.txt)

Hi pi0. Thank you for your response. Generated index.js is attached.

**Comment by Atinux** [comment]
Hi @solonik1 

This is fixed already for 1.0, see https://github.com/nuxt/nuxt.js/blob/dev/lib/core/module.js#L62

**Comment by solonik1** [comment]
@pi0, @Atinux Thank you very much.

**Comment by pi0** [comment]
@solonik1 Temporary patch published with `@nuxtjs/axios:2.2.4` please upgrade :)
