### ISSUE TITLE
Babel Loader Error during nuxt generate

### ISSUE THREAD

**Issue by rwatts3** [nuxt/nuxt.js#1128]
Greetings,

I am attempting to deploy a static version of my app to gitlab pages,
I noticed the build is failing due to babel-loader barking about not being able to find '~components/MyComponent.vue'

The component is capitalized so i'm not sure if that's part of the problem but running the app locally with npm run dev the issue does not exist.

**Comment by piyushchauhan2011** [comment]
Please share an example or replicate this [this](https://glitch.com/edit/#!/nuxt-hello-world) glitch @rwatts3 for the given error finding!

**Comment by rwatts3** [comment]
Sorry it seems to only happen when I run `nuxt-generate` and strange enough it only happens when it's run in gitlab's ci tool. 
Using node 8.1.0 , it generates just fine then barks about babel-loader. 

I'm not sure how to replicate it , since it generates just fine on my mac.

**Comment by rwatts3** [comment]
For the record in case anyone runs into this issue.  The problem was with a. Separate line where I was using ~/components vs ~components.
