### ISSUE TITLE
config  `module.exports = {   performance: {     prefetch: false   } }` not working

### ISSUE THREAD

**Issue by Vi-jay** [nuxt/nuxt.js#1130]
After packaged the preloaded file more than forty, too much, hoping to close the preload. But in accordance with the configuration in the document, failed to successfully close the preload.

**Comment by Vi-jay** [comment]
please help (´^`)

**Comment by LXVC** [comment]
I have the same problem as you

**Comment by Vi-jay** [comment]
@LXVC In order to solve this problem, I changed the source code, but not a good idea, if you need to solve this problem, you can try to 'node_module / nuxt / dist / nuxt.js' in this statement 'resourceHints = renderResourceHints' Changed to 'resourceHints = ""'

**Comment by pi0** [comment]
Hi. With next release disable is simply possible using:
```js
render: {
 resourceHints: false
}
```

**Comment by Vi-jay** [comment]
@pi0 Thx

**Comment by Atinux** [comment]
rc3 is out, closing it
