### ISSUE TITLE
How to use postcss and postcss-cssnext with scss files ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#1131]
I was trying to include postcss and cssnext with my scss setup using the given [example](https://glitch.com/edit/#!/nuxt-postcss-global). Are there any examples which highlights cssnext and scss setups ?

**Comment by didiself** [comment]
Hi, maybe you should take a look.
https://github.com/nuxt/nuxt.js/issues/846
https://github.com/nuxt/nuxt.js/issues/1092

It's lots of about postcss issues , maybe search will be better before create a new issue.
