### ISSUE TITLE
extendRoutes doesn't work?

### ISSUE THREAD

**Issue by Harry-Lee** [nuxt/nuxt.js#1132]
nuxt.config.js：
`router: {
    extendRoutes(routes) {
      routes: [{
        path: '/',
        redirect: '/lines'
      }]
    }
  }`

index.vue：
```
<template>
  <div>
    <ul class="m-tag">
      <nuxt-link :to="item.link" v-for="item in navList" :key="item.title" active-class="act">
        {{ item.title }}
      </nuxt-link>
    </ul>
    <nuxt-child/>
  </div>
</template>

<script>

export default {
  head () {
    return {
      meta: [
        { hid: 'description', name: 'description', content: 'My custom description' }
      ]
    }
  },
  data () {
    return {
      navList: [{
        title: 'lines',
        link: '/lines'
      }, {
        title: 'traffic',
        link: '/traffic'
      }]
    }
  }
}
</script>
```

![image](https://user-images.githubusercontent.com/26618975/28451362-697b08ba-6e1f-11e7-82f1-13c4e92e1e26.png)

when I visit "http://127.0.0.1:3000"，I expect  "http://127.0.0.1:3000/lines"

but it doesn't work.

**Comment by hilkbahar** [comment]
Yes, of course doesn't work. Lines.vue and traffic.vue files shouldn't be in index folder.

**Comment by Harry-Lee** [comment]
I don't think so.
"http://127.0.0.1:3000/lines" and  "http://127.0.0.1:3000"  are addressable.
I just need URL redirect.

**Comment by alexchopin** [comment]
@Harry-Lee, `redirect` in the router object is not available with Nuxt but you can do a redirect with a middleware:
`middleware/lines.js`
```js
export default function ({ redirect }) {
  return redirect('/lines')
}
```
`index.vue`
```js
export default {
  middleware: 'lines'
}
```

**Comment by Harry-Lee** [comment]
Thanks.
The the 'middleware' could fix this problem,but I use the 'pages' to contains the router.
If I use the 'middleware',it will run again and again,then err:to many redirects.

![image](https://user-images.githubusercontent.com/26618975/28455263-0f4eceb4-6e31-11e7-822f-ce80425e3752.png)

![image](https://user-images.githubusercontent.com/26618975/28455327-4ab6f7e2-6e31-11e7-8969-4fd82dc61f66.png)

**Comment by Atinux** [comment]
Hi @Harry-Lee 

I am not sure that your directory structure is right, you should have:
```bash
pages/
  lines.vue
  traffic.vue
  index.vue
```

And to redirect to `/lines`, you can do this:

`pages/index.vue`
```vue
<template></template>

<script>
export default {
  fetch ({ redirect }) {
    redirect('/lines')
  }
}
</script>
```

**Comment by Harry-Lee** [comment]
please click this url https://modao.cc/app/kNiot1gRtOMKLeX44DMBGByHNYcuJhf
I hope I can make it clear.
what I want the urls:

http://127.0.0.1:3000   redirect => http://127.0.0.1:3000/lines
http://127.0.0.1:3000/lines
http://127.0.0.1:3000/traffic

**Comment by alexchopin** [comment]
@Harry-Lee, ok I haven't seen that you are using nested routes.

Just test your route name in `pages/index.vue`
```js
export default {
  fetch ({ route, redirect }) {
    if (route.name === 'index') {
        redirect('/lines')
    }
  }
  ...
}
```

**Comment by Harry-Lee** [comment]
thank you so much.
problem solved.
