### ISSUE TITLE
Using a global event bus

### ISSUE THREAD

**Issue by anthonycook** [nuxt/nuxt.js#1139]
I want to create a global event bus with Nuxt, ([see here](https://vuejs.org/v2/guide/components.html#Non-Parent-Child-Communication)). My first instinct was to create a middleware like this:

```
export default function () {
    
    let eventBus = new Vue();
    return eventBus; 

}
```

But I don't have access to the Vue instance in the middleware, I'm not sure where I can put the following code so I can emit and receive events across all pages/components.

I don't really want to import a file into every single component/page that uses the event bus, as it defeats the object of it being globally accessible. Anyone know a way I can achieve this?

Thanks!

**Comment by motia** [comment]
You should define it in a plugin. Try this:

        export default function ( {app, store} ){
            app.$bus = new Vue
            if (store) store.$bus = app.$bus
        }

**Comment by anthonycook** [comment]
@motia  Still getting a "Vue is not defined" error with this code too unfortunately.

**Comment by dohomi** [comment]
@anthonycook is this not better to resolve with Vuex? Just as an idea though as I'm not familiar what you try to archive

**Comment by anthonycook** [comment]
@dohomi What I'm trying to do is get my child components to communicate with my parent components/pages. For example when I press a button in child component, the parent component will respond. From what I can gather from Vue's docs, customer events are the best way to do this. How ever, I can seem to get them working with Nuxt.

**Comment by KonstantinVlasov** [comment]
hi, @anthonycook !
Maybe you forgot to import Vue?

```
import Vue from 'vue'
```

**Comment by motia** [comment]
Hi, @anthonycook, I just tested the event bus and it works fine. Probably the solution is as @KonstantinVlasov suggests.

**Comment by dohomi** [comment]
@KonstantinVlasov as I do similar things like you with a toolbar where users can press `SAVE` I need to dispatch the click event down to a complete different component. I use a Vuex to toggle a Boolean variable like this:
```
state.js
export state = {
  toggleSave: false
}

toolbar.js
dispatch('toggleSave', !this.$store.state.toggleSave)

some-random-component.vue
export default{
  watch:{
    '$store.state.toggleSave'(v){
      // do something if toggleSave is changing
     }
  }
}

```

**Comment by Lacroute** [comment]
If you only need a parent child communication and not a global dispatch system you can pass events through your instance via `this.$emit()`, `this.$on()` and `props`. See [the doc](https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events).

If you're looking for a non parent-child communication, then go with `vuex`.

**Comment by jsonberry** [comment]
I suggest `Vuex` as well, but that's because I like to have well defined data flow patterns for my projects and not stray from the patterns. IE "we use Vuex to do this, so use Vuex, don't create a one-off event bus between two components", that way it's a bit easier contextually to understand what is going on. Less context switching. And donuts. Lots of donuts.

**Comment by javialon26** [comment]
hello, i'm trying to create a event bus with this plugin:

`import Vue from 'vue'

export default function ({ app, store }) {
  app.$bus = new Vue()
  if (store) store.$bus = app.$bus
}`

In my nuxt config i have:

`plugins: [
    { src: '~/plugins/event-bus' }
]`

and in a component i'm trying to access the bus with this.$bus but is undefined. in this.$store.$bus is ok.

thank you

**Comment by Lacroute** [comment]
Why do you need to register the bus in the store? The store can easily replace a global bus emitter...

**Comment by javialon26** [comment]
@Lacroute is not necessary in the store. i just copy the example of @motia

**Comment by Lacroute** [comment]
@javialon26 Ok I see.

The plugin let's you the opportunity to inject a piece of code in the root app. As [the doc](https://nuxtjs.org/guide/plugins#inject-in-root-amp-context) says, you'll be able to use this piece of code in `middlewares` or `fetch` and `asyncData` hooks.

If you're looking for a global event dispatcher for your components, you should create an external file in `assets` called `bus.js`:
```
import Vue from 'vue'

const Bus = new Vue()

export default Bus
```
Then in your pages, or component simply import it with `import Bus from '~/assets/bus'`. Then you'll be able to play with your custom events between your components. Be carefull, you'll bypass lots of good practices with the global bus way.

Again, I suggest you to take a look at [vuex](https://vuex.vuejs.org/), it's not very complicated to understand, and your application will be more structured.

**Comment by javialon26** [comment]
@Lacroute thank you, i understand vuex and actually im using it for auth, locale, menu state, etc. but in some case is more simple just fire an event.

playing with plugins, i found this solution for a global event bus:

`import Vue from 'vue'

const eventBus = {}

eventBus.install = (Vue) => {
  Vue.prototype.$bus = new Vue()
}

Vue.use(eventBus)`

with this plugin i have access to this.$bus in all component. what do you think of this approach?

**Comment by valdinei** [comment]
@javialon26 I tried like you're not here, but it's not my case does not work.

**pluguins/event-bus.js**
```javascript
import Vue from 'vue'

const eventBus = {}

eventBus.install = (Vue) => {
  Vue.prototype.$bus = new Vue()
}

Vue.use(eventBus)
```

**pluguins/event-bus.js**
```javascript
  plugins: [
    '~plugins/event-bus.js'
  ]
```

**ComponentNavbar.vue**
```javascript
    mounted () {
      this.$bus.$on('showLoginEvent', (boolean) => {
        this.isModalLoginActive = boolean
        console.log('declared showLoginEvent')
      })
    },
```

**FormRegisterCoupon.vue**
```javascript
    methods: {
      openModal () {
        this.$bus.$on('showLoginEvent', true) // do not fire the event
      },
```


any idea what it might be? tkx

**Comment by DarkRayX** [comment]
@valdinei use created instead of mounted

**Comment by valdinei** [comment]
@DarkRayX I already had the test, but it did not work. Apparently it is not an instance of '$bus' in scope 'this'

See that in my component I put two logs. Log "A" when the component is created and Log "B" when the $bus must create the event.
![screen shot 2018-01-10 at 11 11 27 am](https://user-images.githubusercontent.com/1458766/34774786-e057dbd8-f5f7-11e7-821c-5f63ebc349e9.png)

But when I check on the site, only Log "A" runs
![screen shot 2018-01-10 at 11 11 43 am](https://user-images.githubusercontent.com/1458766/34774805-f5760486-f5f7-11e7-9cd3-ceac0da20119.png)

**Comment by AngelVasquezNep** [comment]
Hello!
I used the next configuration:


in plugins/eventBus.js
`
import Vue from 'vue'

const eventBus = {}

eventBus.install = function (Vue) {
  Vue.prototype.$bus = new Vue()
}

Vue.use(eventBus)
`
--------
in nuxt.config.js (into key "plugins". More info: https://nuxtjs.org/api/configuration-plugins)
`
module.exports = {
  plugins: [ '~/plugins/eventBus.js' ]
}
`
---------
in your component 
`
methods:{
   eventhandler(){
       this.$bus.$emit('name-of-event', 'your-data')
  }
}
`

**Comment by samyfox** [comment]
@AngelVasquezNep Thanks for the solution !

In the file `plugins/eventBus.js` you create an a property named `install` in the bus event object.
Is it recognized somewhere by vue or nuxt ?

**Comment by epartipilo** [comment]
This approach in Nuxt is causing memory leak, any clue?
If I replace 
```
Vue.prototype.$bus = new Vue()
```
for 
```
Vue.prototype.$bus = {
  $on: function () {
  },
  $off: function () {
  },
  $emit: function () {
  }
}
```
The memory leak is gone.
Thanks!

**Comment by adrianoresende** [comment]
Code more simple:

Plugin:
```
import Vue from 'vue';

Vue.prototype.$bus = new Vue();
```

**Comment by lukas-pierce** [comment]
Use inject nuxt function

`plugins/bus-inject.js`

```
import Vue from 'vue';

export default (ctx, inject) => {
  const bus = new Vue;
  inject('bus', bus);
};
```
