### ISSUE TITLE
Nuxt in JVM

### ISSUE THREAD

**Issue by jbadeau** [nuxt/nuxt.js#114]
Many large enterprises will not be running node for a long time. It would be really amazing to have nuxt run in the jvm under nashorm. My question is:

How much of nuxt is dependant on v8 API?
How much of nuxt is dependant on node API?

There are ways to shim/bridge these APIs in the JVM and I would be most interested to port nuxt to the JVM if it sounds feasible. I think many enterprises would fancy such a solution.

**Comment by Atinux** [comment]
Hi @jbadeau 

Nuxt is dependant on node API as much as all its dependencies are dependant on node and v8 API.

I think it would be pretty hard and it's not our priority, we hope that large companies will start using node.js and follow already big companies whom adopted it (Netflix, Walmart, LinkedIn, Medium, Paypal, Uber, NYT...).

Also, I have 0 knowledge in Java :)

But I'd love to see someone porting Nuxt to JVM, it would be legendary!

**Comment by jbadeau** [comment]
I mostly asked because I saw the line in the documentation "It doesn't make use of any transpilers and depends upon Core V8 implemented features." I wasn't quite sure what was meant by that statement. Do you mean to say implement es6/7 features or API?

In general I don't care too much about the what jsvm my code is running in (v8, chakra, nashorn) but enterprises are slow at migrating or moving and nuxt + hashorn = nuxthorn would provide a solution today. Anyway; I will give it a try this weekend? Let's see. Thanx for your feedback 😀

**Comment by Atinux** [comment]
This was before we used webpack to build the library to finally I don't really know what specs of V8 Nuxt.js depends.

If you can try this weekend, I'd love to hear your feedback!

**Comment by husayt** [comment]
This is slightly off topic, buy I am using Nuxt to generate a static website which can work with our java webserver. So this is one area I think where Nuxt will be extremely valuable, to generate assets for websites running of tomcat or other java webserver.
