### ISSUE TITLE
best way to populate session user without server?

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#1141]
I'm working on implementing a token auth and wondering what would be the most straight forward and minimal approach. 

Storing token in cookie and populating during nuxtServerInit. I know that population is not necessary but there is a 4k cookie limit and additional data may be needed.

The question I have with this approach is, what happens if I want to `nuxt generate`. I know nuxt generate works for static content, but for things dynamic like the user, I'm assuming it not to be generated. Meaning, nuxtServerInit cannot be the solution for this scenario. 

I've read in another thread about introducing nuxtClientInit. The thread doesn't seem to talk specifically about user token population but I feel is a great solution. https://github.com/nuxt/nuxt.js/issues/240

Now since, nuxtClientInit is not available yet, my next thoughts are to use `plugins` or a `middleware`. Given the user only needs to be populated on initialization, I'm thinking `plugin`. Can I however, have the app wait on async operations from the plugin? If not, I guess the middleware is always available.

Would love to get some guidance here.

**Comment by alexchopin** [comment]
Hi @uptownhr, you should use `fetch` in that case. It will be call on client-side on the generated and will update the generated data (from nuxt generate) by the newest (from the cookie detected).

**Comment by uptownhr** [comment]
When using fetch, should this go into the layout file or on all pages?

**Comment by alexchopin** [comment]
Layout file in your case.

**Comment by rAugustos** [comment]
@uptownhr,  you can see the new examples in the branch `rc6`  specially the new features `mode:'spa'` with `vuexpersitedstate` it`s awesome!
