### ISSUE TITLE
[Vue warn]: You are using the runtime-only build of Vue...

### ISSUE THREAD

**Issue by ludovicvue** [nuxt/nuxt.js#1142]
Hello, I am trying to use Vue-clip plugin in my Nuxt project. (http://vueclip.adonisjs.com)

This is my `nuxt.config.js` configuration file:

`...`
`build: {`
 `   vendor: ['axios', 'vue-clip']`
 ` },`
`  plugins: [`
   ` { src: '~plugins/vue-clip.js', ssr: false }`
 ` ],`
`...`

And this is my `~plugins/vue-clip.js` file:

`import Vue from 'vue'`
`import VueClip from 'vue-clip'`
`Vue.use(VueClip)`

This is the error I have on render:

[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

Do you know where it could come from ?

The plugin itself has, in the `webpack.config.js`

`resolve: {
    alias: {
      vue: 'vue/dist/vue.js'
    }
  }`

Should I use the same alias in the `nuxt.config.js` file ?

Thank you very much for your help!

**Comment by pi0** [comment]
Hi. Why normally not recommended using compile included build, it would be possible using this configuration: ([source](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/nuxt.config.js#L20))

```js
    build: {
        extend(config) {
            config.resolve.alias['vue'] = 'vue/dist/vue.common'
        }
    }
```

**Comment by ludovicvue** [comment]
@pi0 thank you so much for your answer, it works!
What would you recommend instead of using the compiler included build ?

**Comment by pi0** [comment]
Your welcome. That's actually packaging problem with the library which should pre-compile templates when releasing dists. That would be nice if you open an Issue/PR there mentioning this issue, I can help for fixing that if needed.

**Comment by ludovicvue** [comment]
Thank you, just did this: https://github.com/thetutlage/vue-clip/issues/37

**Comment by mhpm** [comment]
HELP ! , where is the file to add this
build: {
        extend(config) {
            config.resolve.alias['vue'] = 'vue/dist/vue.common'
        }
    }

mentioned by evan ??

**Comment by unr** [comment]
You can read about extending your webpack config here, https://nuxtjs.org/api/configuration-build @mhpm
