### ISSUE TITLE
nuxt.org => when i use npm run dev is bad and npm run build && npm start is ok

### ISSUE THREAD

**Issue by zppro** [nuxt/nuxt.js#1143]
when i clone the project and `npm install`
then use:` npm run dev` ,open the firefox http://localhost:3000
![2017-07-24 15-40-10](https://user-images.githubusercontent.com/706344/28512958-aad32914-7086-11e7-9af7-0a79f0375dc1.png)
then I use `npm run build && npm start `
it's ok
---help

**Comment by pi0** [comment]
Hi. Just make sure API is running too (https://github.com/nuxt/docs) and listening on port 4000. The reason build works is that we automatically switch to public API on production
