### ISSUE TITLE
Use nginx do reverse proxy, js file path all can't find it, how to solve?

### ISSUE THREAD

**Issue by wsdo** [nuxt/nuxt.js#1144]
Use nginx do reverse proxy, js file path all can't find it, how to solve?

![image](https://user-images.githubusercontent.com/9738969/28515675-0dbeee32-7091-11e7-8ee7-c68f106d3fd7.png)

**Comment by pi0** [comment]
Hi. Would you please share virtual host config used for reverse proxy? Nuxt is working for us behind multiply reverse proxies ...

**Comment by wsdo** [comment]
nginx config 
```
upstream shudong {
       server 127.0.0.1:3000;
}

server{
        listen 80;
        #listen [::]:80;
        server_name shudong.wang;
        index index.html index.htm index.php default.html default.htm default.php;
        #root  /home/wwwroot/shudong.wang/.nuxt/;

        #include other.conf;
        #error_page   404   /404.html;
        #include enable-php.conf;

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location / {
                proxy_set_header X-Real-Ip $remote_addr;
                proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Nginx-Proxy true;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_pass http://shudong;
                proxy_redirect off;
                #try_files $uri $uri/ /index.html;
                #if (-f $request_filename/index.html){
                #        rewrite (.*) $1/index.html break;
                #}
                #if (-f $request_filename/index.php){
                #        rewrite (.*) $1/index.php;
                #}
                #if (!-f $request_filename){
                #rewrite (.*) /index.php;
                #}
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log  /home/wwwlogs/shudong.wang.log;
    }

```

**Comment by pi0** [comment]
> #root  /home/wwwroot/shudong.wang/.nuxt/;

Why this line is commented out? If using `nuxt generate` you have to serve `/home/wwwroot/shudong.wang/dist` directory instead.

**Comment by wsdo** [comment]
@pi0 I use the NPM run build;NPM start;Launched the port 3000, intends to use the reverse proxy, nginx configuration above, use access http://shudong.wang:3000 or 120.27.245.209:3000   no problem,  following a visit to the agent address in file path not found, expect to have a correct reverse proxy configuration

**Comment by wsdo** [comment]
Don't use nuxt generate, use npm build;  npm start or  pm2  ./build/main.js ； then  nginx proxy  There is a problem

**Comment by pi0** [comment]
```

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }
```
Can you disable this line?

**Comment by wsdo** [comment]
Now I try it on

**Comment by wsdo** [comment]
Is studied for a week, didn't I think of this problem, now problem solved, thank you very much!!!!!!

**Comment by pi0** [comment]
Your welcome. Problem is that nginx matches closest `location` and in this case it skipped proxy pass in `location /`.

**Comment by darbaoui** [comment]
@wsdo any suggestion i have the same issue #42

**Comment by jhonathas** [comment]
@pi0 you saved me.
