### ISSUE TITLE
Is there a way to pass parameter to asyncData in mixin?

### ISSUE THREAD

**Issue by jeange1003** [nuxt/nuxt.js#1145]
If I define asyncData in page component, in the asyncData function, I can access the variable defined before component definition in the .vue file. But in the mixin definition, it's not possible to access the variable defined in page component.
Is there a way to pass parameter to asyncData in mixin?

**Comment by pi0** [comment]
Hi. `fetch` and `asyncData` are being called at an early stage before VM instance being created. So all we can do is access passed context. You can use nuxt plugins (with exported function) for adding mixins into that context :)

**Comment by jeange1003** [comment]
Thanks a lot!

**Comment by Erreke** [comment]
> Hi. `fetch` and `asyncData` are being called at an early stage before VM instance being created. So all we can do is access passed context. You can use nuxt plugins (with exported function) for adding mixins into that context :) ([example](https://github.com/nuxt-community/modules/blob/master/modules/axios/plugin.js#L169))

Unfortunately the example has moved. Could you give a new link if you have one?

**Comment by manniL** [comment]
@Erreke see https://nuxtjs.org/guide/plugins#combined-inject ☺️
