### ISSUE TITLE
Route change prevented with beforeRouteUpdate still calls asyncData

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#1146]
If I prevent a route change with `routeBeforeUpdate` method (as on vue-router spec) it seems `asyncData` for the new route (that has not been shown) is still called.

It looks as though `routeBeforeLeave` works fine, but as I need to prevent a route change when a slug/prop of a URL changes I need to use `routeBeforeUpdate`.

Is there a simple check that can be put in place to make sure the new route is definitely going to be shown before `asyncData` is called?

Also, if the new route is not shown, and then it is allowed to be shown, asyncData isn't called I think because NuxtJS believes that route is already being shown (or it looks that way just seeing outputs when logging to the console)

**Comment by pi0** [comment]
Hi. Why don't you use [validate](https://nuxtjs.org/api/pages-validate/#the-validate-method) ?

**Comment by silverbackdan** [comment]
I think because validate doesn't meet my requirements for what I'm looking to do.

I am creating a page which can be edited by an administrator. I want to warn a user before they leave the page if they have not saved their changes to give them a chance to discard, save them or continue editing the content on the page. So I need this action to happen as the page is being left, and not on a new page being shown.

**Comment by xxRockOnxx** [comment]
any workarounds? this is kinda frustrating.
