### ISSUE TITLE
Non-redundant solution for i18n routing

### ISSUE THREAD

**Issue by quentinus95** [nuxt/nuxt.js#1147]
Hello,

I'm looking for a clean way to produce routes with the following schema:

`/:locale?/url1`, `/:locale?/url2`, and `/:locale?` so my application can be reached at `/url1` but also `/fr/url1`, ...

The example proposed in the documentation (https://nuxtjs.org/examples/i18n) is not convincing, as every page should be duplicated under `_ lang`, this is impossible for most applications with a lot of pages.

Using the `extendRoutes` is also non pertinent as we should duplicate all the routing inside the config file; using the filesystem to define routing would be consequently irrelevant (and I want to avoid two different approaches for the same thing).

Is there a solution to have the `locale` parameter being optional, whatever pages are added later?

**Comment by alexchopin** [comment]
Hi @quentinus95 ,

You can use [Dynamic Component Injection](https://twitter.com/nuxt_js/status/884380662249160704) in your `/_locale/index.vue` file.

Check if your locale is in the arrays of locales.
If not, do the import of the component in the `/_locales/` folder with the same name as the param.
![](https://pbs.twimg.com/media/DEXzaJmXgAAJou1.jpg:large)

**Comment by wkang** [comment]
@quentinus95 Did you figure out the i18n solution by async components?  

@alexchopin 
I tried it but encounter a problem: I want to replace component by detecting url not fixed one, such as: /fr/test/abc will use pages/test.vue, and I have no idea to get the correct component name. any ideas?

Thanks!

````
const getComponent = (file) => ({
  component: import(file)
})
export default{
  beforeCreate () {
    if (this.$route.params.locale && ['en', 'fr'].includes(this.$route.params.locale.toLowerCase())) {
      var route = this.$root.$router.match('/')
      var matched = route.matched
      var component = (matched[0]).components['default'].call()
      **# (matched[0]).components['default'].call() this will return promise, not the component name**
      this.component = () => getComponent(component['__file'])
    }
  }
}
````
