### ISSUE TITLE
Error refreshing page after nuxt build

### ISSUE THREAD

**Issue by swarajd** [nuxt/nuxt.js#115]
I run `node v7.1` and `yarn 0.18.1` and I installed nuxt through the template running the following command:
  
`$ vue init nuxt/starter <project-name>`  
  
and when inside I ran `yarn` to install the dependencies. However, when I do `yarn dev` and access the "about page" and refresh, I get an error that says the following:

`Vue.js error: Error: render function or template not defined in component: anonymous`

[here is an image of the error](http://i.imgur.com/1Odvtly.png)

I did not edit any files or touch any configuration. Is there any reason why this is happening?

**Comment by swarajd** [comment]
I think it's because the default about file doesn't have a template. For some reason it was never there. This is the generated about page:

```
<script>
export default {
  data ({ req }) {
    return {
      name: req ? 'server' : 'client'
    }
  },
  head () {
    return {
      title: `About Page (${this.name}-side)`
    }
  }
}
</script>

<style scoped>
.title
{
  margin-top: 50px;
}
.info
{
  font-weight: 300;
  color: #9aabb1;
  margin: 0;
  margin-top: 10px;
}
.button
{
  margin-top: 50px;
}
</style>
```

I also think it's because when I go about generating the project, it asks for four things:

1. name
2. description
3. author
4. raw

for raw I don't put anything, and that may be the reason, but I am not entirely sure.

**Comment by Atinux** [comment]
Hi @swarajd 

Thank you for spotting this issue, can you give me which version of `vue-cli` you're using `vue -V`?

I think this error is due to an update of the `vue-cli`.

**Comment by swarajd** [comment]
I am using version 1.4.0. I think that's the issue as when I go to the repo for vue-cli it's version is indicated as 2.7.0

**Comment by swarajd** [comment]
Yeah the vue-cli version was the issue once that was updated it ran perfectly!

**Comment by swarajd** [comment]
I do think though that it would be wise to note that the latest version of vue-cli (i.e vue-cli >= 2) is required for the starter, as this issue is somewhat difficult to find without that knowledge.

**Comment by Atinux** [comment]
Thank @swarajd it's updated on the [starter](https://github.com/nuxt/starter).

**Comment by adebali** [comment]
I have a similar error only for the page using google maps (vue2-google-maps). The page works fine when I navigate from another page, but when I on the page and click on the refresh button, it fails and gives out the following error.

<img width="1038" alt="screen shot 2017-09-10 at 10 12 07 pm" src="https://user-images.githubusercontent.com/3449123/30255965-1fbedc28-9675-11e7-9746-55239b8db01f.png">
