### ISSUE TITLE
Additional js with external resource

### ISSUE THREAD

**Issue by robyedlin** [nuxt/nuxt.js#1150]
I'm trying to add an external resource in my nuxt project. I have this in my nuxt.config.js file:
```
    script: [
      { src: 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js' }
    ]
```
But I also need to add this, and am not sure where to put it:
```
    WebFont.load({
      google: {
        families: ['Overpass:300,600,700']
      }
    })
```

**Comment by christopheschwyzer** [comment]
I suggest to: 
- Include _webfontloader_ via `npm install webfontloader`
- Add `webFontLoader.js` file to `/plugins` folder:
```
var WebFont = require('webfontloader');

WebFont.load({
  google: {
    families: ['Overpass:300,600,700']
  }
});
```

- Adjust `nuxt.config.js`:
```
  plugins: [
    {src: '~plugins/webFontLoader.js', ssr: false}
  ],
 ```

**Comment by christopheschwyzer** [comment]
Note that `~plugins` alias might not work anymore since the latest release. Check here: https://github.com/nuxt/nuxt.js/releases

**Comment by robyedlin** [comment]
This works, thanks. But there are cases where this kind of embedded js will need to be used and objects need to be referenced. For example, typekit, or stripe. I think the `ssr: false` takes care of it.

**Comment by mixn** [comment]
Why won’t Typekit work by just including the way @robyedlin suggested? Thank in advance, @christopheschwyzer!

**Comment by christopheschwyzer** [comment]
I guess it works either way. The question was where to put the additional code. My solution was more of a suggestion on how to organise the code.
