### ISSUE TITLE
@click don't work well in UC browser 

### ISSUE THREAD

**Issue by yuicer** [nuxt/nuxt.js#1152]
env:  
    UC browser   android 
webpage:
    http://zh.nuxtjs.org
error:
    click event is not work for the navigation on the top right corner

**Comment by pi0** [comment]
Hi. I think the problem is with js incompatibility of older browsers like UC. We have introduced some out-of-the box improvements for next release. Hope it will help, else you need adding `bable-polyfill` in your project for more browsers compatibility.

**Comment by xianweics** [comment]
Same problem...

**Comment by yuicer** [comment]
@pi0 may i ask when the next version will publish? and how to config the babel-polyfill? thx!

**Comment by SzHeJason** [comment]
UC browser not support es6

``` 
  nuxt.config.js 
  extend(config, { isClient }) {
      config.resolve.alias["~config"] = path.join(__dirname, "service/config");
      if (isClient) {
        config.entry.vendor.push("babel-polyfill");
      }
      return config;
    },
```

**Comment by xianweics** [comment]
@SzHeJason The way I used and got an error.
 nuxt:build Generating files... +16ms
  nuxt:build Generating routes... +7ms
  nuxt:build Adding webpack middleware... +61ms
(node:5648) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: path is not defined

**Comment by pi0** [comment]
Please use something link this:

```js
  extend(config, { isClient }) {
      if (isClient) {
        config.entry.vendor. unshift(lbabel-polyfill');
      }
    },
```

**Comment by xianweics** [comment]
@pi0 It still don't work...

**Comment by xianweics** [comment]
@pi0 It still doesn't work...

**Comment by HADB** [comment]
same problem, not work even added babel-polyfill

**Comment by SzHeJason** [comment]
don't worry. it just doesn't work in the local environment

**Comment by xianweics** [comment]
@SzHeJason Thx
