### ISSUE TITLE
'loaded' event on client side

### ISSUE THREAD

**Issue by f15gdsy** [nuxt/nuxt.js#1154]
Hi,
I'm wondering if Nuxt.js provides the ability to notify the client that Nuxt has setup properly.
The equivalent to to jQuery might be 
```
$( document ).ready()
```

The use case is that I may have some code depending on window.$Nuxt, and a in-house mechanism for detect if it's ready would be great, for example, a simple event would do:
```
var e = new CustomEvent('nuxt-loaded')
window. dispatchEvent(e)
```

**Comment by pi0** [comment]
Hi. You can use `window.onNuxtReady` helper.
```js
if (process.browser) {
  window.onNuxtReady((app) => {
    console.log('Nuxt ready!')
  })
}
```

**Comment by f15gdsy** [comment]
@pi0 Thanks! It solves my problem.
Although using native API might be a better choice as there may be codes importing from <script> in HTML.

**Comment by galvez** [comment]
@pi0 This needs to be a little more explicit in the documentation. Should I submit a PR?

**Comment by pi0** [comment]
@galvez for sure!

**Comment by galvez** [comment]
@pi0 @Atinux @alexchopin how do you guys feel about adding a `nuxtClientInit` to pages so this becomes more straight-forward?

**Comment by appsparkler** [comment]
This is what worked for me:
`app.mounted function` wherein i'm including all the `initializing code`

https://nuxtjs.org/guide/plugins#inject-in-root-amp-context

Good Luck...

**Comment by agriboz** [comment]
@pi0 you make my day. thank you i:)
