### ISSUE TITLE
Async messages for i18n

### ISSUE THREAD

**Issue by Lacroute** [nuxt/nuxt.js#1156]
```
"nuxt": "^1.0.0-alpha.5",
"vue-i18n": "^7.0.5"
```

Hi there,

I've got difficulties to fill the i18n `messages` property from a remote file (collaborative translation).

In other words, can I set/modify a **plugin** after an `async` operation **and** before the rendering?

For now, I feed the store using the `nuxtServerInit` action then I instanciate it this way:
```
// ~/plugins/i18n.js

import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

export default ({ app, store }) => {
  // Set i18n instance on app
  app.i18n = new VueI18n({
    locale: store.state.locale,
    fallbackLocale: store.state.fallbackLocale,
    messages: store.state.messages
  })
}
```

But the problem is the store is empty when the server render my page (still fetching) so I got a `[vue-i18n] Cannot translate the value of keypath 'hello'. Use the value of keypath as default.` warning message and the template updates 1 second after.

Any ideas?

Thanks

**Comment by alexchopin** [comment]
Hi @Lacroute, can you show us your `nuxtServerInit` and try to use `store.getters.locale`?

**Comment by Lacroute** [comment]
Hi @alexchopin,

Here we go:

```
export const actions = {
  async nuxtServerInit ({ dispatch, commit }, { app, env }) {
    // i18n translation content
    const { data: messages } = await app.apiList.get(env.commons.translations)
    commit({
      type: SET_MESSAGES,
      messages: messages
    })

    // global external data fetching
    const { data: list } = await app.apiList.get(env.commons.list)
    commit({
      type: SET_PROJECTS_LIST,
      list: list
    })
  }
}
```
The `messages` follows the `i18n` specs.
The commits are just very basics mutations. And my basic state:
```
export const state = () => ({
  locale: 'fr',
  fallbackLocale: 'en',
  messages: {},
  list: []
})
```

**Comment by arikw** [comment]
+1

**Comment by vadimsg** [comment]
+1

**Comment by Atinux** [comment]
Hi @Lacroute 

Could you try with the `rc11`of nuxt.js please? An re-open if it does not fix your issue.

**Comment by git-antonyuk** [comment]
+1
Same problem (

**Comment by evry-johber** [comment]
+1
