### ISSUE TITLE
Layout is not effective 

### ISSUE THREAD

**Issue by dxhszu** [nuxt/nuxt.js#1159]
Layout is not effective when I go back to the front page from the error page.

**Comment by alexchopin** [comment]
Hi @dxhszu, can you explain more about your issue?

**Comment by dxhszu** [comment]
My code like that:
layout>nav.vue:
`<template>
<div>
  <nuxt/>
  <x-nav></x-nav>
<div>
</template>
`
x-nav is a component. I went to this error page from a page used this layout and go back,then i saw the x-nav was lost.

**Comment by h4ckm03d** [comment]
@dxhszu I am using more complex layout than ydurs but never encounter that problem. maybe if you provide one of your code on `pages/` it will be help

**Comment by gustojs** [comment]
Do you use one default layout file or few different layouts?
