### ISSUE TITLE
Blogging Support

### ISSUE THREAD

**Issue by pehbehbeh** [nuxt/nuxt.js#116]
Are there any plans to support blog posts out of the box?

Similar to what Jekyll does: https://jekyllrb.com/docs/posts/

Or is this out of this projects scope?

**Comment by alexchopin** [comment]
Hi, 

Actually it's on our plan to support blogging as soon as the version 1 will be released.

It'll be more a Nuxt template preconfigured for blogging with the same logic as Jekyll.

We think that could be a better solution to create a nuxt-blog template like nuxt-starter for example and keep the framework lightest as possible.

**Comment by mixn** [comment]
Any updates on this? :) <3
