### ISSUE TITLE
1.0.0-rc0: plugin1 This dependency was not found

### ISSUE THREAD

**Issue by BjornMelgaard** [nuxt/nuxt.js#1162]
~~For some reason my plugins (js files in plugins directory) are compiled to plugin1, plugin2 names~~
ok, it must be this way, for some reason it cant find my plugins, plugins from `nuxtjs/modules` installed fine

```
 ERROR  Failed to compile with 1 errors                                                                                       1:59:54 PM

This dependency was not found:

* plugin1 in ./.nuxt/index.js

To install it, you can run: npm install --save plugin1
```
```
// .nuxt/index.js

import 'es6-promise/auto'
import Vue from 'vue'
import Meta from 'vue-meta'
import { createRouter } from './router.js'
import NuxtChild from './components/nuxt-child.js'
import NuxtLink from './components/nuxt-link.js'
import NuxtError from '../layouts/error.vue'
import Nuxt from './components/nuxt.vue'
import App from './App.vue'
import { getContext } from './utils'
import { createStore } from './store.js'
import plugin0 from 'plugin0'
import plugin1 from 'plugin1' 
....

```

![2017-07-26-14 14 29-screenshot](https://user-images.githubusercontent.com/7573215/28618388-de60ca70-720c-11e7-9068-0b0b2da7315b.png)

**Comment by pi0** [comment]
Should be fixed in next rc :)

**Comment by BjornMelgaard** [comment]
AWESOME!!

**Comment by mdreizin** [comment]
@pi0 I have the same issue for `rc1`:

```
* plugin0 in ./.nuxt/index.js
```

**Comment by pi0** [comment]
As a workaround, you have to provide fully resolved path to plugins (Using path.resolve) if REALLY can't wait for next RC :))

**Comment by mdreizin** [comment]
@pi0 Ok, thanks!

**Comment by jsnick** [comment]
@pi0 I provided fully resolved path to plugins then, nuxt build is ok.
but I think the files in `plugins/` is not compiled.
 
```
Nuxt.js Error:

/path/to/project/plugins/apollo.js:1
(function (exports, require, module, __filename, __dirname) { import ApolloClient, { createNetworkInterface } from 'apollo-client'
SyntaxError: Unexpected token import
...
...
```

**Comment by BjornMelgaard** [comment]
@pi0, when the next version with fix will be published?

**Comment by BjornMelgaard** [comment]
So, I have added 
```
  plugins: [
    resolve(__dirname, 'plugins/buefy.js'),
    resolve(__dirname, 'plugins/multiwatch.js')
  ],
```

just like @pi0 advised (cause I cant use alpha-5, `render function or template not defined in component: anonymous`, and I cant find where error, all was fine)
and it works fine, only one thing

if plugin doesnt import anything, there is an error

```
 WARNING  Compiled with 2 warnings                                                                                            5:39:47 PM

 warning  in ./.nuxt/index.js

107:25-32 "export 'default' (imported as 'plugin1') was not found in 'plugin1'

 warning  in ./.nuxt/index.js

113:19-26 "export 'default' (imported as 'plugin1') was not found in 'plugin1'
```
and page is loading infinitely long, so I have to use `export default (_) => { }`

**Comment by BjornMelgaard** [comment]
in rc2 resolve is no longer required, but infinitely long loading is left
