### ISSUE TITLE
How correctly use ld+json scripts

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#1164]
Hi, I want to use in head() props of page script with ld+json content type. With documentation of [vue-meta](https://github.com/declandewet/vue-meta#script-object) I set example: 

```
script: [
  { innerHTML: '{ "@context": "http://schema.org" }', type: 'application/ld+json' }
]
```

but on rendered page I has output with 

```
<script data-n-head="true" type="application/ld+json">{ &quot;@context&quot;: &quot;http://schema.org&quot; }</script>
```

As you can see, content inside tag was escaped and not valid. How I must set vue-meta for correct usage?

**Comment by psnoonan** [comment]
Did you find a solution to this?

**Comment by ruslankonev** [comment]
@psnoonan yes, you need add a ` __dangerouslyDisableSanitizers: ['script'],` props ([docs](https://github.com/declandewet/vue-meta#__dangerouslydisablesanitizers-string)) to correct insert inner text. As example:
![image](https://user-images.githubusercontent.com/2588730/29960846-fe7772c6-8f05-11e7-83b5-2ac61680fd47.png)

**Comment by psnoonan** [comment]
@ruslankonev It worked for me by changing "innerHTML" to just "inner"
