### ISSUE TITLE
migration guide / breaking changes | from 1.0.0-alpha.4 to 1.0.0-rc1

### ISSUE THREAD

**Issue by LowM4N** [nuxt/nuxt.js#1165]
Is there any documentation for the new release candidate?
And is the main build tool now rollup? Or why are webpack packages in the dependencies?

**Comment by pi0** [comment]
Hi. Some quick notes:
- Latest public release is still `1.0.0-alpha.5` (RCs are just git tags)
- About build tool yes it is and will be Webpack, rollup is just used internally by nuxt to transform it's core API source code. (So builder needs webpack dependencies as before)
- We are going to release a `nuxt-start` package too which only needs runtime dependencies and would be useful for super light production builds. (Not stable yet)
- Sorry about lack of DOCS. We are HEAVILY working on it.
