### ISSUE TITLE
when 1.0 stable will be released

### ISSUE THREAD

**Issue by xiaogaofudao** [nuxt/nuxt.js#1166]
waiting for 2 month already

**Comment by gustojs** [comment]
I've been waiting since 2016 and will wait as long as it's need. Better to get code that's actually ready than the rushed one that later has to be patched in even more of a rush.

**Comment by alexchopin** [comment]
@xiaogaofudao Nuxt.js is an open source project.
If you think the 1.0 stable version is taking too much time feel free to fork the project and do a PR.
