### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor

### ISSUE THREAD

**Issue by sj82516** [nuxt/nuxt.js#1167]
Hi, 
I am using ` vue init nuxt/koa` create the project.
And the I run `npm install` with no errors but running `npm run dev` throw the error
>DONE  Compiled successfully in 1196ms  
 (node:61639) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_2_n
uxt___default.a is not a constructor

My nodejs/npm version is `8.2/5.3` on Mac OS.

**Comment by sj82516** [comment]
When I run `npm run build` it throws 
> ERROR in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":false}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue
Module not found: Error: Can't resolve '~components/Footer.vue' in '/Users/zhengyuanjie/Desktop/Nodejs/psk_events2/layouts'
 @ ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":false}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue 9:0-46
 @ ./layouts/default.vue
 @ ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":false}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./.nuxt/App.vue
 @ ./.nuxt/App.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js

**Comment by paulgv** [comment]
Running `npm install` will set your Nuxt version to `rc1` which seems to break the Koa template at the moment.
The easiest way to fix this would be to downgrade to alpha5:

```sh
yarn add nuxt@1.0.0-alpha.5
```
or
```sh
npm i nuxt@1.0.0-alpha.5 --save
```

Then, you'll probably also want to add `build: {}` to your `nuxt.config.js` to fix the `Unexpected character '�' (1:0)` error:

```js
module.exports = {
  build: {},
  // More config down here
}
```
