### ISSUE TITLE
Meta tags duplicated

### ISSUE THREAD

**Issue by cschweda** [nuxt/nuxt.js#117]
I noticed that meta tags in a page component don't automatically overwrite (or, more specifically, replace) meta tags in the nuxt.config.js.

For example: ```nuxt.config.js```:

```
...head: {
    title: 'starter',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'keywords', content: 'keyword 1, keyword 2'},
      {name: 'description', content: 'This is the generic description.'}

    ],
  },
...
```

However, if I also have a ```description``` meta in my individual page:

```
export default {
  head () {
    return {
      title: `Page 1 (${this.name}-side)`,
      meta: [
        { name: 'description', content: "Page 1 description" }
      ],
    }
  }
}
```

I notice that two meta tags with description are generated. I assume this is by design. But is there a way to have a default description replaced -- overwritten -- by a page-level description?

I ask because I'm trying to essentially replace Jekyll with Nuxt -- via ```nuxt generate``` -- and then have a json file generated (via Cheerio parsing the generated pages) with all the meta tags that, in turn, can be fetched back into the home page to display the recent posts (including, as I indicate above, the meta descriptions for each page.)

**Comment by alexchopin** [comment]
Hi, thanks for the report. 
Can you post some screenshot ?

**Comment by Atinux** [comment]
Hi @cschweda 

This is a "feature" of [vue-meta](https://github.com/declandewet/vue-meta), please take a look at the [documentation of head elements](https://nuxtjs.org/guide/html-head#defaults-meta).

> To avoid any duplication when used in child component, please give a unique identifier with the hid key, please [read more](https://github.com/declandewet/vue-meta#lists-of-tags) about it.

So for the meta description, you should add the unique identifier `hid` so vue-meta will not that it has to erase the default tag.

Your `nuxt.config.js`:
```js
...head: {
    title: 'starter',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'keywords', content: 'keyword 1, keyword 2'},
      { hid: 'description', name: 'description', content: 'This is the generic description.'}
    ],
  },
...
```

An then in your individual page:
```js
export default {
  head () {
    return {
      title: `Page 1 (${this.name}-side)`,
      meta: [
        { hid: 'description', name: 'description', content: "Page 1 description" }
      ],
    }
  }
}
```

**Comment by cschweda** [comment]
That's great. Thank you!
