### ISSUE TITLE
Best way to integrate Sentry

### ISSUE THREAD

**Issue by wushan** [nuxt/nuxt.js#1172]
Although #https://github.com/zeit/next.js/issues/2334 is an issue on next.js, I'd like to know the best way to integrate Sentry.

I was using express + nuxt.js and was able to catch errors from client-side via `raven-js` module, but when navigating a page component which uses asyncData(server-side), I can't send that error to sentry but only use error() to send error page to the user.

My best guess is the `raven-js` module is for client-side use and we should use `raven-node` in express side, I tried this but turned out that errors from asyncData() isn't passing to or handled by express.

`plugins/raven.js`
```
import Vue from 'vue';
import Raven from 'raven-js';
import RavenVue from 'raven-js/plugins/vue';

Raven
    .config('https://<>@sentry.io/<>')
    .addPlugin(RavenVue, Vue)
    .install();
```

`pages/test.vue`
```
async asyncData ({ isServer, req, store, params, error }) {
   try {
     let { data } = await axios.post('http://10.20.100.100:15050/api/run ....
   }
   catch(e) {
      console.log(Raven.isSetup()) // this will be false
      Raven.captureException(e)
      error({ statusCode: 404, message: 'Post not found' }) // 404 from nuxt
    }
}
```

**Comment by wushan** [comment]
I changed the service ip to a impossible target and was expecting catching the error and deal with it, not nodemon crash...

Any ideas ?
<img width="817" alt="screenshot 2017-07-28 11 12 34" src="https://user-images.githubusercontent.com/3633628/28701036-1116f384-7386-11e7-93c4-c5ca1177874d.png">

<img width="1052" alt="screenshot 2017-07-28 11 12 44" src="https://user-images.githubusercontent.com/3633628/28701037-112e52cc-7386-11e7-8452-f93512b1f1d4.png">

**Comment by DiederikvandenB** [comment]
Did you end up figuring this out :)?

**Comment by alexchopin** [comment]
https://github.com/nuxt-community/sentry-module

**Comment by InstanceOfMichael** [comment]
Why the thumbs down(s)? Is there an issue with https://github.com/nuxt-community/sentry-module ?

**Comment by awronski** [comment]
@DiederikvandenB is the module raport both server and client side errors?

**Comment by DiederikvandenB** [comment]
@awronski Yes.

**Comment by johndays** [comment]
@DiederikvandenB  I think that I actually have the same problem. Raven is configured and working fine on the client-side (meaning whatever action that lead to an error in the browser is captured by Rave). However, when an error occurs on the server side (node) , e.g. in the nuxt fetch hook (https://nuxtjs.org/api/pages-fetch), so that it seems in the fetch hook, raven is still not loaded, thus not capturing anything. 

Is this known? Is there some additional configuration?

nuxt version = 1.4
@nuxtjs/sentry version = 1.1.0

Thanks for any hint
