### ISSUE TITLE
Can't execute $emit tag <a> inside <nuxt-link>

### ISSUE THREAD

**Issue by VadiForte** [nuxt/nuxt.js#1175]
I try $emit from child to parent it just work fine.

but when i try @click inside `<nuxt-link>` to execute $emit function it not work at all.

I don't know if i do something wrong?

<img width="466" alt="screen shot 2560-07-27 at 7 28 18 pm" src="https://user-images.githubusercontent.com/8231772/28670197-c4aa45de-7301-11e7-99c8-7b8974a3552d.png">

I also try to bind @click on `<nuxt-link>` and it still not work

**Comment by VadiForte** [comment]
<img width="524" alt="screen shot 2560-07-27 at 7 25 16 pm" src="https://user-images.githubusercontent.com/8231772/28670097-570e50ec-7301-11e7-8089-a49cab6c97c1.png">

**Comment by pi0** [comment]
This may be a problem with nuxt-link but meanwhile you can try using `@click.native` to bypass this issue.

**Comment by VadiForte** [comment]
@pi0 TA Mate! but still not work :x

**Comment by VadiForte** [comment]
I think, the `<a>` inside `<nuxt-link>` is generate and overwrite by NuxtJs it self 🤔

**Comment by alexchopin** [comment]
@VadiForte what about this?
```pug
<template lang="pug">
  ul.menubar
    li(@click="closeMenu")
      nuxt-link(to="/") Home
    li
      nuxt-link(to="/product-service") Product & Service
    li
      nuxt-link(to="/about") About
    li
      nuxt-link(to="/") Request Demo
</template>
```

**Comment by Lacroute** [comment]
I can fire a custom method with the `@click.native` modifier, maybe the problem is your event handling. How and Where do you listen for `menuWasClose`?

**Comment by VadiForte** [comment]
@alexchopin Thank you alex and all you guy, it work fine now :D
