### ISSUE TITLE
app : undefined in ctx of async asyncData (ctx)

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#1178]
Hi!

Why there is no app in the context for ```async asyncData (ctx)``` in the client side requests?
There is only for SSR.

**Comment by pimlie** [comment]
Also experiencing this issue with rc2

```js
  async asyncData ({ app, redirect }) {
    return app.$axios.get('/blog')
```
gives a 500 error `Cannot read property '$axios' of undefined`

**Comment by awronski** [comment]
@pimlie as a temporary workaround you can do
```javascript
 async asyncData ({ store, redirect }) {
    return store.$axios.get('/blog')
```

But I think this is a bug

**Comment by Atinux** [comment]
Fixed in `rc3`, sorry about this.
