### ISSUE TITLE
TypeError: Nuxt is not a constructor

### ISSUE THREAD

**Issue by floydandfriends** [nuxt/nuxt.js#1180]
Started getting this error when I deployed our service on a new host. 

This code fails with Node v8 and rc2

const Nuxt = require('nuxt');
const config = require('./nuxt.config.js');
const nuxt = new Nuxt(config);

`TypeError: Nuxt is not a constructor
    at Object.<anonymous> (/Users/Kalle/Dev/neovici/backend/Tools/render-node/test.js:3:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3`

**Comment by jsnick** [comment]
Check https://github.com/nuxt/nuxt.js/blob/dev/test/express.test.js

**Comment by floydandfriends** [comment]
@jsnick Running only those 3 lines I pasted cause the exception. Not sure what I'm to do with the test based on that?

**Comment by jsnick** [comment]
I mean check [Line:3](https://github.com/nuxt/nuxt.js/blob/dev/test/express.test.js#L3) , [Line:21-24](https://github.com/nuxt/nuxt.js/blob/dev/test/express.test.js#L21-L24)

the way to import Nuxt is changed.

You should change your code to 
```javascript
const { Nuxt, Builder } = require('nuxt');
const config = require('./nuxt.config.js');
const nuxt = new Nuxt(config)
```

**Comment by floydandfriends** [comment]
Ah I see @jsnick. That did it. Was that a recent change? https://nuxtjs.org/api/nuxt-render is not up to date if so.

**Comment by jsnick** [comment]
Yes, this is changed in v1.0.0. The page is on version 0.10.6.

**Comment by floydandfriends** [comment]
Well README.md is also showing the same syntax @jsnick. Maybe it will all sync up after 1.0.0 release. I'll close this now. Thanks!

**Comment by gtso86** [comment]
I'm using this code inside server.js

``` js
const { Nuxt, Builder } = require('nuxt');
const app = require('express')();
const port = process.env.PORT || 3000;

// We instantiate Nuxt.js with the options
let config = require('./nuxt.config.js');
let nuxt;

// Create nuxt instace
nuxt = new Nuxt(config)
app.use(nuxt.render);

// Build only in dev mode
if (config.dev) {
    new Builder(nuxt)
      .build()
      .catch((error) => {
        console.error(error)
        process.exit(1)
      });
};

// Listen the server
app.listen(port, '0.0.0.0');
console.log('Server listening on localhost:' + port);
```

**Comment by SgtPooki** [comment]
This still doesn't work for me. What versions are you all running?
I keep getting 
`TypeError: Cannot read property 'build' of undefined`
