### ISSUE TITLE
Navigating back should retain the scroll position.

### ISSUE THREAD

**Issue by krestaino** [nuxt/nuxt.js#1182]
### Version
1.0.0-rc3

### Reproduction link
[https://github.com/krestaino/scroll-position-nuxt](https://github.com/krestaino/scroll-position-nuxt)

### Steps to reproduce

1. Go to http://localhost:3000/
2. Scroll down and click on a post
3. After the new page loads, use the browser's back button
4. Scroll position goes to the top rather than where it was

### What is expected?
Navigating back should retain the scroll position.

### What is actually happening?
Navigating back does not retain the scroll position.

### Additional Info
One thing I noticed, if I set the height of the HTML element to something like `html { min-height: 10000px }`, the issue goes away. It doesn't seem to be 100% consistent though. Is this happening because the post list is being rendered dynamically using `v-for`?

**Comment by Lacroute** [comment]
I've got the same issue and the same conclusion. The weird things is `vue-router` support the `v-for` elements. (I'm trying to use `hash` anchors in a `v-for` rendered list).

**Comment by Lacroute** [comment]
A temporary solution is to store the needed id when I click on a `nuxt-router` link, then on the `mounted` hook, scroll to the div with the needed id.

**Comment by pi0** [comment]
Hi @krestaino. Thanks for your nice reproduce example. We are working on a fix ASAP. I'm closing all related issues to make issue tracking for 1.0 release easier. Feel free adding more comments or possibly help us for a fix PR.
Regards.

**Comment by krestaino** [comment]
It's a little outside my capabilities I think. I looked into it, but you guys are wizards and I have no idea where to start. Sincerely appreciate the amazing work you are all doing. As of now, reporting bugs and supporting the project are as much as I can contribute. :(

Some day though, I'll make a meaningful contribution!

**Comment by nathan5x** [comment]
Any updates on the fix?

**Comment by krestaino** [comment]
This was fixed with the 1.3.0 release.
