### ISSUE TITLE
Default app crashes at very beginning

### ISSUE THREAD

**Issue by ImJustToNy** [nuxt/nuxt.js#1186]
Hello,
Today my nuxt app refused to work. Everytime i try to do "yarn run dev" it shows me this:
![image](https://user-images.githubusercontent.com/5730766/28695007-0adf8a48-732d-11e7-9987-23c9088fe7cf.png)
Same happens when I generate brand new app via [starter template](https://github.com/nuxt-community/starter-template) or [express template](https://github.com/nuxt-community/express-template).
I'm totally out of ideas.

Can you help me?
Cheers.

**Comment by kevincpan** [comment]
I have the same issue. The templates were working fine for me yesterday, and I have a few projects that still work. My guess is some dependency was updated and it messed up the build?

**Comment by BjornMelgaard** [comment]
express template will not work without this https://github.com/nuxt-community/express-template/pull/61/files

~components/Logo.vue - https://github.com/nuxt/nuxt.js/issues/1183#issuecomment-318457804

**Comment by kevincpan** [comment]
Thanks for the component fix.

However, the express template is still not working for me. first, i get this warning :
``` (node:98306) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/load
er-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
Then after some compile successes I still get
```
(node:98422) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_1_nuxt___default
.a is not a constructor
```

**Comment by BjornMelgaard** [comment]
Have you tried to upgrade? I've tried starter-template and express-template, and they worked fine. Try https://github.com/tylerlong/yarn-upgrade-all

**Comment by kevincpan** [comment]
I haven't tried upgrade, but I think I have pinpointed the issue. When I npm install a fresh express-template, it uses nuxt@1.0.0-rc, but if I downgrade to nuxt@1.0.0-alpha.5, it will work like it used to. 

I will try yarn-upgrade-all though and report back with my results.

**Comment by BjornMelgaard** [comment]
Excellent)

**Comment by ImJustToNy** [comment]
@BjornMelgaard Nothing worked, I've appiled express fix, upgraded, downgraded, updated component import. Any other ideas?

**Comment by BjornMelgaard** [comment]
rc3 was just released

**Comment by BjornMelgaard** [comment]
your express must be like this https://github.com/nuxt/nuxt.js/blob/dev/examples/custom-server/server.js, I will try that too

**Comment by mgesmundo** [comment]
@ImJustToNy update your import statement:
```js
import Logo from '~components/Logo.vue'
```
to
```js
import Logo from '~/components/Logo.vue'
```

**Comment by BjornMelgaard** [comment]
seems like this is right config

```
import { Nuxt, Builder } from 'nuxt'
import express from 'express'

import api from './api'

const app = express()
const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3000

app.set('port', port)

// Import API Routes
app.use('/api', api)

// Import and Set Nuxt.js options
let config = require('../nuxt.config.js')
config.dev = !(process.env.NODE_ENV === 'production')

// TODO remove
process.on('unhandledRejection', function(reason, p) {
  console.log(p)
  console.log("Unhandled Rejection:", reason.stack);
  process.exit(1);
});

// Instanciate nuxt.js
const nuxt = new Nuxt(config)

// Start build process if
if (config.dev) {
  const builder = new Builder(nuxt)
  builder.build()
}

// Give nuxt middleware to express
app.use(nuxt.render)

// Start express server
app.listen(port, host)
console.log('Server listening on ' + host + ':' + port) // eslint-disable-line no-console
```
but there is an error in browser when /api/users tried to load, and I cant find fix, @pi0 , can you help to fix express-template?

```
 DONE  Compiled successfully in 4402ms                                                                                       12:47:43 PM

Promise {
  <rejected> { Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: [Object],
     transformResponse: [Object],
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: [Object],
     method: 'get',
     url: '/api/users',
     data: undefined },
  request:
   Writable {
     _writableState: [Object],
     writable: true,
     domain: null,
     _events: [Object],
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: [Object],
     _redirectCount: 0,
     _bufferedWrites: [],
     _onNativeResponse: [Function],
     _currentRequest: [Object],
     _currentUrl: 'http:/api/users' },
  response: undefined } }
Unhandled Rejection: Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

```
