### ISSUE TITLE
Would like to ask the recent release of nuxt about how long?

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1187]
Would like to ask the recent release of nuxt about how long?
Really looking forward to be faster, very grateful

**Comment by BjornMelgaard** [comment]
Team is working hard, I'm even not sure does @pi0 sleep at all :smile:

**Comment by Atinux** [comment]
https://github.com/nuxt/nuxt.js/releases/tag/1.0.0-rc3
