### ISSUE TITLE
Option Merging for fetch and asyncData method

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#1191]
Hi @Atinux . I was wondering, do we support [Option Merging](https://vuejs.org/v2/guide/mixins.html#Option-Merging) . I tried for `fetch` method but it didn't seem to fire `log` messages in both `mixin` and `fetch` defined in component like they do in `vue mixins`. I think this is true for `asyncData` too

**Comment by dotneet** [comment]
Hi, I've created a helper that makes nuxt possible to use mixin for asyncData/fetch.
https://github.com/dotneet/nuxtend
