### ISSUE TITLE
How to use ssr and non ssr in same app

### ISSUE THREAD

**Issue by JokerstudioDev** [nuxt/nuxt.js#1192]
Nuxt is server side rendering framework for SEO and other features
But in the real world some page require SSR for SEO like product list, product detail, blog content, ads page. And some page do not want SEO like setting, about-me, dashboard, landing page. How to use ssr page and non ssr page for the same app

**Comment by BjornMelgaard** [comment]
you can use `nuxt generate` to prerender some pages

**Comment by BjornMelgaard** [comment]
```
module.exports = {
  generate: {
    routes: [
      '/users/1',
      '/users/2',
      '/users/3'
    ]
  }
}

```
https://nuxtjs.org/api/configuration-generate

**Comment by JokerstudioDev** [comment]
Thank for the solution :)

**Comment by BjornMelgaard** [comment]
It was easy-peasy)
