### ISSUE TITLE
nuxt/starter gets a path error when run build

### ISSUE THREAD

**Issue by helloliyi** [nuxt/nuxt.js#1193]
It was still well yesterday. But today when I reinstall npm packages and run 'npm run build', the issue occurred.

"Module not found: Error: Can't resolve '~components/pageNav.vue' in '/home/my-site/nuxt/layouts' "

This is the snapshot:
![nuxt_build_error](https://user-images.githubusercontent.com/12062745/28705165-25336fda-73a1-11e7-8a4a-74577f5eff16.png)

**Comment by BjornMelgaard** [comment]
https://github.com/nuxt/nuxt.js/issues/1183#issuecomment-318457804

**Comment by helloliyi** [comment]
Thanks.
Is it a bug, or api change?

**Comment by vuchl** [comment]
would be interesting what crashes this? @pi0 any ideas?

**Comment by pi0** [comment]
@helloliyi An API change to make usage more general and clear. Sorry about lack of notes on this change :(
