### ISSUE TITLE
Infinitely long loading in dev mode with hot-reload rc2

### ISSUE THREAD

**Issue by ArunSivagnanam** [nuxt/nuxt.js#1194]
When i use the dev command, nuxt builds complete, but then the server seems to not start. evrything just freezes. I have fixed the alias problem and the new constructor stuf. 

Does anyone have the same problem? If i use build command and then use start, all is ok. But dev is broken? 

Thanks! :)

**Comment by ArunSivagnanam** [comment]
my server looks like this,
const app = require('express')()
const { Nuxt, Builder } = require('nuxt')

const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3000

// Import and Set Nuxt.js options
let config = require('./nuxt.config.js')
config.dev = !(process.env.NODE_ENV === 'production')

const nuxt = new Nuxt(config)

// Start build process if
if (config.dev) {
  const builder = new Builder(nuxt)
  builder.build()
}

// Give nuxt middleware to express
app.use(nuxt.render)

// Start express server
app.listen(port, host)
console.log('Server listening on ' + host + ':' + port)
https://github.com/nuxt/nuxt.js/blob/dev/examples/custom-server/server.js

**Comment by BjornMelgaard** [comment]
try this https://github.com/nuxt-community/express-template/pull/61/files

**Comment by ArunSivagnanam** [comment]
i still have to use the Builder(nuxt).build right? if i try nuxt.build() i get an error. // : nuxt.build is not a function

**Comment by ArunSivagnanam** [comment]
im totally confused now :(

**Comment by Atinux** [comment]
Example has been updated, it works perfectly with `rc3`:

```bash
cd examples/custom-server/
npm install
npm run dev
```

Go to http://localhost:3000

**Comment by Atinux** [comment]
Since it's not official yet, prefer to use `alpha5` or `0.10`

**Comment by ArunSivagnanam** [comment]
ok, thanks. But the problem is still there in my project after rc3 and with youre example server :( 
i think i will just wait

**Comment by Atinux** [comment]
I'm not sure to understand, the project works perfectly on my end.

Do you have a reproduction repo?
