### ISSUE TITLE
Where did I do something wrong?

### ISSUE THREAD

**Issue by imsunhao** [nuxt/nuxt.js#1195]
Just

vue init nuxt/starter nuxt-starter

cd nuxt-starter

npm install

npm run build

![image](https://user-images.githubusercontent.com/22325263/28705985-c3815942-73a4-11e7-8d0c-775f530c6e21.png)

**Comment by BjornMelgaard** [comment]
https://github.com/nuxt/nuxt.js/issues/1183#issuecomment-318457804

**Comment by imsunhao** [comment]
I still don't know how to do it....
Can you tell me more?

**Comment by BjornMelgaard** [comment]
oh, sorry, here is pull request that fixed that
https://github.com/nuxt-community/starter-template/pull/23/files

**Comment by imsunhao** [comment]
thanks. It's working fine.
