### ISSUE TITLE
[Feature Request] Support for symlinks in `static`

### ISSUE THREAD

**Issue by hirokiosame** [nuxt/nuxt.js#1196]
Currently, symlinks in the `/static` folder isn't resolved via the server. Can there be support added for this?

**Comment by BjornMelgaard** [comment]
https://github.com/nuxt-community/modules/blob/master/modules/vendor/README.md

are this module do what you want?

**Comment by Atinux** [comment]
Can you provider a repository to reproduce this issue an then re-open this issue please @hirokiosame ?

**Comment by pi0** [comment]
Symlinks are actually working but you have to use full paths for sysmlinks and in windows environment using **Junktion** links. Vendor module handles this problems so you can use it or inspire to make our own solution.
