### ISSUE TITLE
buildDir

### ISSUE THREAD

**Issue by MRZMUH001** [nuxt/nuxt.js#1197]
Hi,

Has anyone got buildDir option working? I have got the following options set in my config file but it has no effect. `nuxt run build` still stores it in the `.nuxt/dist/` directory. I need it be outside the `.nuxt` folder as thats in .gitignore.

Couldn't find the buildDir option in the docs anymore either (used to be there as far as I can remember).

```js
  srcDir: 'src/',
  buildDir: 'dist/'
```

**Comment by jvmonjo** [comment]
Did you managed to get it working? I have the same issue.
