### ISSUE TITLE
Modules into plugin file: "export 'default' (imported as 'plugin0') was not found in 'plugin0'

### ISSUE THREAD

**Issue by acollins1991** [nuxt/nuxt.js#1198]
I'm trying to implement custom filters with a filter.js file in the plugins folder, and importing that with the nuxt config file with `plugins: ['~plugins/filters']`. If i insert a simple console.log test into this file it seems to work fine, but if I try to import anything like Vue I get the following error:

```
 warning  in ./.nuxt/index.js

99:25-32 "export 'default' (imported as 'plugin0') was not found in 'plugin0'

 warning  in ./.nuxt/index.js

105:19-26 "export 'default' (imported as 'plugin0') was not found in 'plugin0'
```

I also get a Hot Reload Loop.

How can I get this working?

(Also, thanks for the great framework!)

**Comment by BjornMelgaard** [comment]
try upgrade to `^1.0.0-rc3`
