### ISSUE TITLE
HTML generated with `nuxt generate` don't have <head> and closing </body>,</html> tags

### ISSUE THREAD

**Issue by buhrmi** [nuxt/nuxt.js#1199]
Hello,

running `nuxt generate` on a simple project appears to generate invalid HTML, with `<title>` and `<meta>` not within the `<head>` and missing closing `</body>` and `</html>` tags.

**Comment by pi0** [comment]
Hi. This is an known and HTML is valid! Minifier does this to save more bytes :)

**Comment by Gomah** [comment]
```json
generate: {
    minify: {
      removeOptionalTags: false,
    },
  },
```
