### ISSUE TITLE
Eliminate external resource requests (above and below the fold)

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#12]
What would you think of a nuxt.js app using making no external resource requests for it's own JS and CSS files? It would all be inline injected into `lib/views/app.html`

Before:
```js
<% const {
  title, htmlAttrs, bodyAttrs, link, style, script, noscript, meta
} = context.meta.inject() %><!DOCTYPE html>
<html n-head-ssr ${htmlAttrs.text()}>
  <head>
    ${meta.text()}
    ${title.text()}
    ${link.text()}
    ${style.text()}
    ${script.text()}
    ${noscript.text()}
    <base href="<%= baseUrl %>">
    <% if (!dev) { %><link rel="stylesheet" href="<%= files.css %>"><% } %>
  </head>
  <body ${bodyAttrs.text()}>
    <%= APP %>
    <script type="text/javascript" defer>window.__NUXT__=<%= serialize(context.nuxt) %></script>
    <script src="<%= files.vendor %>" defer></script>
    <script src="<%= files.app %>" defer></script>
  </body>
</html>

```

After:
```js
<% const {
  title, htmlAttrs, bodyAttrs, link, style, script, noscript, meta
} = context.meta.inject() %><!DOCTYPE html>
<html n-head-ssr ${htmlAttrs.text()}>
  <head>
    ${meta.text()}
    ${title.text()}
    ${link.text()}
    ${style.text()}
    ${script.text()}
    ${noscript.text()}
    <base href="<%= baseUrl %>">
    <% if (!dev) { %><style><%= files.css.CODE %></style><% } %>
  </head>
  <body ${bodyAttrs.text()}>
    <%= APP %>
    <script type="text/javascript" defer>window.__NUXT__=<%= serialize(context.nuxt) %></script>
    <script><%= files.vendor.CODE %></script>
    <script><%= files.app.CODE %></script>
  </body>
</html>

```

**Comment by jaredreich** [comment]
This would make a basic nuxt.js score perfect on Google PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/)
![image](https://cloud.githubusercontent.com/assets/8563847/20498723/783cd5ce-afeb-11e6-8eef-28d0d35bde10.png)

**Comment by Atinux** [comment]
The problem here will be that the HTML will be too heavy.

The point of the actual configuration is to display the HTML (server-rendered) so the browser can display it before loading the JavaScript and making the page reactive afterwards.

But you're right about the performances, we want Nuxt.js to generate the fastest web apps :-)

**Comment by jaredreich** [comment]
Right, so then perhaps this should be done only for the style in `<head>`?

**Comment by Atinux** [comment]
Exactly, that's actually the main issue with Nuxt.js, I will meet Evan You in December to know how I can find a way to extract the CSS of the matched components to inject the minimal CSS in the <head>.

I'll keep you updated!

**Comment by jaredreich** [comment]
Cool, best of luck.

**Comment by declandewet** [comment]
Haven't tested this (rather busy setting up my company atm) but I think this might work - although I think it may be inefficient (it might do multiple `<style>` tag injections) but it is a step in the right direction

https://github.com/kriasoft/isomorphic-style-loader

webpack.config
```js
module.exports = {
  // ...
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
    ]
  },
  vue: {
    loaders: {
      ExtractTextPlugin.extract({
        loader: ['ismorphic-style-loader', css-loader'],
        fallbackLoader: 'vue-style-loader'
      })
    }
  },
  plugins: [
    new ExtractTextPlugin("style.css")
  ]
}
```

If my suspicion that this creates a critical style injection more times than is appropriate, then it might be in the best interest to write a Webpack plugin that can extract the critical CSS from the ExtractTextPlugin output

**Comment by ckken** [comment]
i'm looking for~

**Comment by lmj0011** [comment]
:+1:  
This issue looks to be related to the problem I ran into.

Having the ability to load **local resources** in the `head()`.

https://nuxtjs.org/faq

**Comment by Atinux** [comment]
@lmj0011 please create a separate issue.

We might have a solution to have a **perfect score** on Google Page Speed and Lighthouse.

With the upcoming 2.2 of Vue, we will be able to insert the CSS into the page and also add a better debugging experience.


Said by Evan You:
> 1. vue-router (2.2 already out) now supports a `router.onReady` method which allows waiting until all async hooks/components are resolved before rendering/hydration. This makes async hooks and code splitting a breeze.
> 2. bundleRenderer will be able to accept a special bundle object generated from code-split multi-chunk webpack builds
> 3. ^ the bundle can be auto-generated by using `vue-ssr-webpack-plugin`
> 4. `vue-style-loader` will be upgraded to work on both client and server. On the server it collects the CSS and generates corresponding `<style>` tag strings and attaches it to the SSR render context. The user simply add these style tags to the HTML output. On the client it will smartly “hydrate” the style tags (thus hot-reloading will also work!)
> ^ this basically gives us automatic critical CSS for initial server render, and with code-splitting for CSS in all async chunks
> Better yet the user no longer needs to configure `extract-text-webpack-loader` - just use `vue-style-loader` (which is the default) and it just works!

When the Vue 2.2 is out, we will try to implement it, so the 1.0 of Nuxt.js will create universal application with a perfect score 🔥

**Comment by jaredreich** [comment]
Excellent, very excited for this.

**Comment by antcook** [comment]
Looks like 2.2 is out! https://github.com/vuejs/vue/releases/tag/v2.2.0

**Comment by msudgh** [comment]
How exactly scss transformation works in nuxt.js? is it based on webpack loaders?

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) is out with CSS embedded.
