### ISSUE TITLE
nuxt-api

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt.js#120]
```bash
api/
  middleware/
    auth.js
  routes/
    posts/
      _id.js
    posts.js
  modules/
    sessions.js // app.use(module.exports)
    compression.js
    i18n.js
  api.config.js
  bootstrap.js // called before listening the application (return a promise)
  app.js // extend app
```
-> Can be written in ES6/7 (use babel-node)

**Comment by rwatts3** [comment]
Hi @Atinux , What is the goal of the nuxt api ? 
Will this be a way to get information out of Nuxt ? or a way to use data within nuxt ?

**Comment by rwatts3** [comment]
Actually from the looks of it, it appears this may be some way to write an application, then install it to a nuxt instance by following this pattern. Am I correct ?

**Comment by Atinux** [comment]
@rwatts3 this will be a way to add an API (express) directly into the nuxt application, this is still a proposal.

**Comment by rwatts3** [comment]
Nice.  This would actually help with the cms idea.

**Comment by rwatts3** [comment]
Would creating a graphql server within nuxt have to wait on this implementation, or is it possible to do currently ?

**Comment by Atinux** [comment]
You can already, you need to use Nuxt.jd programmatically with your own http server and plug it as a middleware.

**Comment by pbastowski** [comment]
Great feature. I'd love to be able to create REST APIs as easily as pages. +1

**Comment by rwatts3** [comment]
Certainly this would be great

**Comment by Atinux** [comment]
I close this one, finally we will not go this direction.

It's easier to do it by using express.js with nuxt.js as a middleware.

We did a starter for this: https://github.com/nuxt/express
Demo: https://express.nuxtjs.org/
