### ISSUE TITLE
rc3: server-bundle.json too big? __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#1201]
I'm not sure if this is a RC3/RC1 bug or if there's a config option i'll be missing. But I build, server-bundle.json is skipped because of size and then I get `__WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor` - All was fine on alpha.5 ( will revert for now 😢  ) - RC1 doesn't give file size warnings though.
![screen shot 2017-07-28 at 20 33 13](https://user-images.githubusercontent.com/25174262/28733439-14dfcefc-73d4-11e7-8aa1-ce9d29458d39.png)

**Comment by silverbackdan** [comment]
![Image of Yaktocat](https://github.com/mlteal/custom-emoji/blob/master/rubberduck.gif?raw=true)
I see the express-template is using rc3 - I'm going to install that and start copying my project over bit by bit until I find the reason!

**Comment by silverbackdan** [comment]
`plugins/VueCookie` --> `~/plugins/VueCookie` etc. in **nuxt.config.js**

Perhaps a nicer error notice would be good if poss.

**Comment by silverbackdan** [comment]
In express server :)
`import Nuxt from 'nuxt'` --> `import { Nuxt, Builder } from 'nuxt'`

And generally the entire file changed haha

**Comment by logaretm** [comment]
@silverbackdan Did you manage to run this on production? I always encounter this:

`[object Promise]` Logged and the connection terminates.

Only when running `build` though, `dev` works fine.

**Comment by silverbackdan** [comment]
@logaretm I don't get that error. I basically started again from the updated nuxt-express template available here https://github.com/nuxt-community/express-template

I don't get the error but I do have something wrong. I think it's to do with the @nuxtjs/pwa module though, specifically workbox. I don't know that for sure yet though. My production build isn't working right now but I'm working on a site here now: https://github.com/silverbackis/NuxtStarterWebsite and the demo will be here when I get it working https://demo.starter.b-w.uk/

My output is
```bash
$ npm run dev

> bw-starter@1.2.1 dev /Volumes/LaCie/GitHub/bw-starter-nuxt
> cross-env HOST=127.0.0.1 PORT=8000 backpack dev

DONE  Compiled successfully in 1846ms                                                                                                                                                                                                                       23:25:40

Express server: Auth Routes Added
Express server listening on 127.0.0.1:8000
[AXIOS] Base URL: http://127.0.0.1:9000/ , Browser: http://127.0.0.1:9000/
Build completed in 13.718s
DONE  Compiled successfully in 13719ms  
```
The only additional output there is the `Express server: Auth Routes Added` which I log when I've added routes for authentication.

**Comment by logaretm** [comment]
I use the `pwa` preset module as well, I will try to apply my app to the starter template incrementally.

**Comment by silverbackdan** [comment]
@logaretm I've looked in the logs and I have that error in production. `[Sun Jul 30 01:02:36.550592 2017] [ssl:info] [pid 3744:tid 140170628073216] [client 31.193.2.47:51670] AH01964: Connection to child 24 established (server default-31_193_2_47:443)
[ 2017-07-30 01:02:36.6153 3721/7fa88a48e700 Ser/Server.h:994 ]: [Client 3-5] Disconnecting client with error: error parsing app response chunked encoding: unexpected end-of-stream
App 4364 stderr: [object Promise]`

It had worked previously - I also get a notice from Phusion Passenger `cannot GET /`

But I didn't see that in the logs when I run `npm run dev` locally, nor `npm run build` then `npm run start` locally - these both work fine. I wonder if it's a node/npm version issue.

Locally I'm on npm 5.3.0 and node v8.0.0

The server runs node 7.4.0 - what are you using were you get this error?

**Comment by silverbackdan** [comment]
This is a separate issue to the one I raised in this initial ticket though. As we're both having the same issue we should move this to a new issue. Thoughts on whether to raise in nuxt-express template or here?

**Comment by silverbackdan** [comment]
Updated my server to latest NodeJS and same result. Must be an issue with with the way express.js is written or the NuxtJS - I'm not able to say which so I'll raise an issue on this repo and see what they say.

**Comment by silverbackdan** [comment]
@logaretm you'll see I opened an issue based on my last comment. I hadn't cleared the cache, hopefully it'll just be a nodejs version issue for you too.

**Comment by logaretm** [comment]
I will take a look, I'm already running node 8 on both local and production environments.

**Comment by github1586** [comment]
@silverbackdan  Have you solved your problem? Is it the node version and the NPM version? I have the same question

**Comment by silverbackdan** [comment]
@github1586 Take a look at the latest nuxt express template and breaking changes.
https://github.com/nuxt-community/express-template/blob/master/template/server/index.js
https://github.com/nuxt/nuxt.js/releases/tag/1.0.0-rc3
