### ISSUE TITLE
Support Vue component files in libraries during SSR

### ISSUE THREAD

**Issue by xkjyeah** [nuxt/nuxt.js#1202]
I created a simple package named `myp`:
**nuxt.config.js**
```js
{
  ...[omitted],
  plugins: ['~/plugins/sample.js']
}
```
**plugins/sample.js**
```js
import HisPlugin from 'myp'
Vue.component('HisPlugin', HisPlugin)
```
**node_modules/myp/package.json**
```js
{
  ...[omitted],
  "main": "test.vue"
}
```
**node_modules/myp/test.vue**
```vue
<template>
  <div class="my-plugin">
    It works!
  </div>
</template>
<style>
.my-plugin {
  font-size: 200%;
}
</style>
```

And the following error message:
```
C:\Users\Daniel\Desktop\ssrtest\node_modules\myp\test.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
```

This presumably comes from the server-side renderer, which does not recognize *.vue files. Is it possible to get the server-side renderer to recognize them?

Some libraries export .vue files, and it is the recommended approach by Evan You (https://forum-archive.vuejs.org/topic/1203/how-to-bundle-a-set-of-vue-components-efficiently/4)

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1061">#c1061</a>)</em></sub></div>

**Comment by sschadwick** [comment]
Also running into this issue upgrading from `"nuxt-edge": "^2.0.0-25562603.52780d3"` to `"nuxt-edge": "^2.0.0-25582697.22559a8"`. Additionally, the vuejs archive link is currently dead.

Offending code:
```javascript
// plugins/global.js
import Spinner from 'vue-simple-spinner/src/components/Spinner.vue';
Vue.component('spinner', Spinner);
```
```javascript
// nuxt.config.js
module.exports = {
  ...
  // Global plugins
  plugins: [{
    src: '~/plugins/global.js',
    ssr: true
  }],
  ...
};
```

One workaround is to prefix the dep path, however this is non-ideal. Please let me know if there is a more concise way to load the plugin.
`import Spinner from '~/node_modules/vue-simple-spinner/src/components/Spinner.vue';`
