### ISSUE TITLE
install starter nuxt error when udate node js version

### ISSUE THREAD

**Issue by Katarzina** [nuxt/nuxt.js#1207]
This dependency was not found:

* ~components/Logo.vue in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue

I changed version node and npm,  - now node 7.8.0 npm 4.6.1...can't load even starter nuxt version...ubuntu 16.04

**Comment by sewede** [comment]
Try import your logo with a slash after the alias.

`import Logo from '~/components/Logo.vue'`

**Comment by Katarzina** [comment]
Thank you..It's help
