### ISSUE TITLE
stderr: [object Promise] in production

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#1211]
At the end of this issue @logaretm and I had a quick message about an error https://github.com/nuxt/nuxt.js/issues/1201#issuecomment-318866458

For me I only see this in my production environment and my NuxtJS app does not work. While @logaretm sees the error in dev as well it seems but it doesn't stop the app working until it is in production.

This is what I get in my apache log:
```log
[Sun Jul 30 01:02:36.550592 2017] [ssl:info] [pid 3744:tid 140170628073216] [client 31.193.2.47:51670] AH01964: Connection to child 24 established (server default-31_193_2_47:443) [ 2017-07-30 01:02:36.6153 3721/7fa88a48e700 Ser/Server.h:994 ]: [Client 3-5] Disconnecting client with error: error parsing app response chunked encoding: unexpected end-of-stream App 4364 stderr: [object Promise]
```

We are both using the nuxt-express template it seems but I don't know if this is an issue that should be raised there, or if the root cause is in the main NuxtJS repo. Happy to move it if needs be.

The output sent to a user for me is
`Cannot GET /` where `/` is the path requested.

Are you able to point us in the right direction?

P.s. we mention a NuxtJS/pws module error, but in mine I've disabled workbox for now as that module has an error deleting the old js files in the static folder after they have been created now. Probably just a file path issue with the latest rc breaking changes.

**Comment by silverbackdan** [comment]
Really embarassing  when I raise these issues and it's actually OK. I updated to latest NodeJS but hadn't cleared my cache. I think it was a NodeJS version issue because I opened dev tools with cache disabled and the site works.

**Comment by logaretm** [comment]
@silverbackdan I'm now mostly confused, The error didn't happen when I was applying my app on top of the new template base. and for whatever reason after some tinkering it stopped happening on the original app codebase, but again there is the #1214.

but now when I was attempting to produce  #1214 I produced this issue instead 😕 

Basically all was working fine up until I added the `pwa` preset.

Do you mind confirming?
https://github.com/logaretm/nuxt-object-promise

**Comment by logaretm** [comment]
@silverbackdan nvm, It needed to install `es6-promise` manually.
