### ISSUE TITLE
How to access some custom meta properties in a route?

### ISSUE THREAD

**Issue by websanova** [nuxt/nuxt.js#1212]
I understand that in the routes directly we can no longer use things like `alias` and `meta`. However I would still like to define some properties for may pages.

For instance say my pages have some specific privilege required and redirect or do nothing accordingly.

I know I can write some simple middleware to check this:

```
export default function (context, route, redirect) {

    // check auth

    return;
}
```

I need some place to set an "auth" property that could have many values, object, array, etc.

Not sure how to set up the `.vue` files so that the middleware can get access to them.

Also it seems the middleware doesn't run on first load? How does this work with restricted routes?

**Comment by BjornMelgaard** [comment]
example with restricted routes is here https://github.com/nuxt/nuxt.js/tree/dev/examples/auth-routes

also [auth module](https://github.com/nuxt-community/modules/blob/master/modules/auth/README.md) (works with axios module) soon will be updated

**Comment by websanova** [comment]
Yes, I seen those, but I'm thinking more with privileges.

For instance a user has roles 'user', 'admin', 'manager', 'curator', etc. I'm trying to setup a middleware (or something) where for instance there is some property somewhere on the route. For instance in the page something like the `meta` plugin for title and description. But instead it would be a `auth` property I could access. then do my checks based on the user and the property.

No idea how to set this up right now.

**Comment by websanova** [comment]
Basically I'm tying to integrate the [vue-auth](https://github.com/websanova/vue-auth) plugin with Nuxt.js.

It would be nice if there was a simple way to include it, perhaps by just including a plugin and a middleware. Then being able to set some `auth` properties on the `.vue` files. 

Don't really want developers worrying about Vuex and too many integrations. Just some basic install and go.

**Comment by BjornMelgaard** [comment]
Dunno) 
I would rather make plugin that searches something like [cancan](https://github.com/CanCanCommunity/cancancan) abilities file in user project :)

**Comment by Atinux** [comment]
This is the answer you're looking for: https://github.com/nuxt/nuxt.js/issues/720#issuecomment-301745685
