### ISSUE TITLE
DOM element with v-if and nested DOM elements error in production

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#1214]
I can use a v-if attribute on a component and it works fine.

If I use `v-if` on a div element with a key of a computed variable that is an object and then have other elements within that (or just text within it) this error is raised in production
`client.js:35 [nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`

E.g. this works:
```html
<div class="column news-dates has-text-right">
    Some text
</div>
```

This raises an error in production:
```html
<div class="column news-dates has-text-right" v-if="page.liveDate !== undefined">
    Some text
</div>
```

Strangely this works:
```html
<div class="column news-dates has-text-right" v-if="true">
    Some text
</div>
```

So does this:
```html
<div class="column news-dates has-text-right" v-if="page !== undefined">
    Some text
</div>
```

`page` is a computed property. If I make a new computed property which returns `this.page.liveDate !== undefined` is fails. Basically checking against any key in the `page` object which is computed causes this problem.

There is even a computed prop which returns a boolean `this.page.live` which I've outputted in the template to make sure it's returning `true` which hasn't worked either.

An empty dom element is fine because it doesn't need to append a child element to it.

Any ideas?

**Comment by Atinux** [comment]
@silverbackdan please create a reproduction by forking https://glitch.com/edit/#!/nuxt-hello-world or creating a github repo and then re-open this issue so we can help you with it.

**Comment by logaretm** [comment]
I'm also facing this problem after fixing #1211 (went away on its own), I will try to reproduce it in a repo.

**Comment by silverbackdan** [comment]
Thanks @logaretm I've been trying to reproduce as well. If it helps I've got the same page nesting as my repo where the issue happens and reading data as described from a computed variable which gets from a vuex store with an id in local data and I can't see an issue. It's leading me to think that it may be something to do with child pages using the same import for a mixin and using the same function or something. Would that tie in with your app structure as well possibly?

**Comment by silverbackdan** [comment]
@logaretm If it helps at all I've tried replicating here as with what I thought the issue was. It's working fine for me though https://github.com/silverbackdan/v-if-nuxt

Feel free to fork if it'll save you time but I may start again with my project and see what I can find. Thanks again.

**Comment by logaretm** [comment]
@silverbackdan do you encounter the issue if the dev build outputs a `DOM tree mismatch` error? I have been able to partially produce the issue at the moment. By setting a store data like `user` which has some DOM elements render depending on some property in the user object.

**Comment by silverbackdan** [comment]
@logaretm Unfortunately I didn't see this error at the same time as the DOM tree mismatch. Although I did see this exact error you've described happen in dev mode as well. I didn't install or tinker with npm packages but it went away on it's own as well. Perhaps something hadn't finished building. Generally the scripts to get a page from an API were quite messy and I'm just reworking all of that into proper vue plugins and moving mixins to new folders outside of pages dir etc.

**Comment by silverbackdan** [comment]
Finally managed to replicate it: https://github.com/silverbackdan/v-if-nuxt

I think the issue is triggered when I added 2 levels to the page levels. In this example `pages/index/_date/_news.vue` - you'll see the folder structure in there.

Is this minimal enough for you @Atinux or would you like me to see if stripping other factors makes a difference (e.g. loading page data via ajax of not).

**Comment by silverbackdan** [comment]
More info on how to replicate:

- Running `npm run build` then `npm run start`
- Enter the URL http://127.0.0.1:3000/does-not-matter/0
- It is loading from the server and this error appears (I've just noticed it usually appears but on mine it isn't consistent right now, can you replicate?)

I'll comment again if I get any more info on this.

**Comment by silverbackdan** [comment]
So the cause of the issue as far as I can see is the order in which the asyncData promises are resolved:
This order causes no error:
page init start 0
page init start 1
page init return 0
page init return 1

This order causes the error:
page init start 0
page init start 1
page init return 1
page init return 0

**Comment by silverbackdan** [comment]
@Atinux All replicated now with minimal implementation. I started with the express template, but have added npm scripts to run the nuxt build and start scripts without backpack too.

https://github.com/silverbackdan/v-if-nuxt

I've taken out the store and unused components and all ajax calls. There is one shared plugin file that will return data for a component, and put a 500ms delay on the home page data so the promise will resolve later than the child.

Replicate process:
- `npm run nuxt:build`
- `npm run nuxt:start`
- Go to URL `http://127.0.0.1:3000/1` - SSR gives the error

You'l see from the home page you can navigate as you'd expect.

I hope it'll be sufficient for you to re-open this issue (or if you'd like me to open a new issue with just this info I can do that).

I'll deleted my last comments now that are about managing to replicate and other notes. All info should be in this comment.

**Comment by Meeeeow** [comment]
I'm experiencing same issue here.

By manual edit yarn.lock and downgrade `vue-server-renderer`, `vue-template-compiler` and `vue`, i can confirm this issue is caused by `vue` release 2.4.3.
It will reproduce on "vue series" package >= 2.4.3

And, i saw another error raised before "This node type does not support this method":
```
TypeError: Cannot read property '_transitionClasses' of undefined
    at Array.hn (vue.runtime.esm.js:5962)
```
But the different is your issue created at 30 July, vue@2.4.3 was released at 13 September

**Comment by Meeeeow** [comment]
By the way, 

I'm reading data in computed property by `_.get(this, 'foo.bar.xyz')`, and there is a strange behavior
- Read it by use `this.foo.bar.xyz` without problem
- Read it by use `_.get(this, 'foo.bar.xyz')` will got undefined at server side and got error message in console: `[Vue warn]: Property or method "foo.bar.xyz" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option`

**Comment by unwrittenmike** [comment]
Was there ever any resolution on this.. Getting the same error

**Comment by jdkahn** [comment]
I'm getting this error as well. Seems like this still is not fixed

**Comment by unwrittenmike** [comment]
Hi @jdkahn see #1552
