### ISSUE TITLE
Update break things

### ISSUE THREAD

**Issue by bdebever** [nuxt/nuxt.js#1215]
Hi there, 
I've update my package.json and so nuxt was updated to the latest version, and it broke everything! 

Here is the error I get when running 'npm run dev' : 
blank page with "Cannot GET /" 

I've changed the aliases as mentioned in the doc. 

Would you have any idea ? or any help how to revert ? 

Thanks.

**Comment by Atinux** [comment]
As mentioned in the release (rc3):

> We are working hard on the documentation, please wait for the new documentation before creating new issues.

Until docs are ready, and if your project is "broken" with rc3, please use 0.10.
