### ISSUE TITLE
Nuxt link outer element

### ISSUE THREAD

**Issue by saeidakbari** [nuxt/nuxt.js#1216]
Is there any way to use `Active Class on Outer Element`?
In plain `router-link` we can do it by simply add `tag` attribute on router-link.
But it doesn't work on `nuxt-link`

**Comment by alexchopin** [comment]
Hi @saeidakbari, 
Can you show us some code snippet about it?
I can reproduce your issue, tag attribute works fine.

**Comment by saeidakbari** [comment]
@alexchopin 
when i add tag attribute nuxt-link won't make `<a>` tag 
here is my code : 
<img width="663" alt="screen shot 2017-07-30 at 8 01 47 pm" src="https://user-images.githubusercontent.com/14778889/28754793-25e37ba6-7562-11e7-9287-cec1ca73f1ea.png">
and here is inspect element : 
<img width="423" alt="screen shot 2017-07-30 at 8 04 12 pm" src="https://user-images.githubusercontent.com/14778889/28754798-4bdb1094-7562-11e7-86aa-b91f3a28fb7a.png">

**Comment by saeidakbari** [comment]
@alexchopin
I fixed it 
sorry for my mistake
i wrap all span tag inside a tag and its worked
i will close issue.
