### ISSUE TITLE
"TypeError: Nuxt is not a constructor" - when trying to use nuxt.js as a middleware

### ISSUE THREAD

**Issue by pawelmadeja** [nuxt/nuxt.js#1219]
I followed this documentation page https://nuxtjs.org/api/nuxt-render/ but when I started the express server I received such response:

```
const nuxt = new Nuxt(config)
             ^
TypeError: Nuxt is not a constructor
```

This only happens under the 1.0.0-rc3 version, on 0.10.7 it works fine :)

**Comment by KonstantinVlasov** [comment]
hi, @pawelmadeja!
Documentation not updated yet, as you can see it's only for 0.10.6
You should require nuxt like this:
`const { Nuxt, Builder } = require('nuxt')`
You can see full example in [readme](https://github.com/nuxt/nuxt.js/blob/dev/README.md)

**Comment by pawelmadeja** [comment]
OK! Thank you @KonstantinVlasov
