### ISSUE TITLE
Feathers.js

### ISSUE THREAD

**Issue by joshua1** [nuxt/nuxt.js#122]
Hi guys,
is it possible to integrate feathers.js with nuxt  as you just did with adonis.js , This gist (https://github.com/zeit/next.js/pull/673/files) shows the integration in next.js and this also (https://github.com/simplehub/henri) am hoping same can be done here , cos of the real time and REST  capabilities of feathers.js all in one go.
Thanks

**Comment by Atinux** [comment]
Hi @joshua1, there is no link to the gist, can you edit your issue please?

**Comment by joshua1** [comment]
@Atinux i just added the links. Thanks

**Comment by Atinux** [comment]
Here you go @joshua1: https://github.com/nuxt/nuxt.js/tree/master/examples/with-feathers

I don't really know Feather.js and I based this example on the PR for next.js

If you want to create an equivalent of [henri](https://github.com/simplehub/henri) with nuxt.js based on this example, I'd be glad to see it 👍

**Comment by joshua1** [comment]
Nice , Thanks @Atinux . i will give it a go
