### ISSUE TITLE
In a.vue, a.scss is referenced, and b.scss is referenced in b.vue, and the results a page can use the styles in b.scss. How do you resolve the conflict?

### ISSUE THREAD

**Issue by XiaoNode** [nuxt/nuxt.js#1220]
like '@import '~assets/css/a.scss' in a.vue

**Comment by krestaino** [comment]
In your `.vue` files add `scoped` to the style tag. Like so:

```
<style lang="scss" scoped>
.search {
  display: flex;
  flex-direction: row;
  margin-bottom: 8px;
  position: relative;
 }
...
</style>
```

That will scope the CSS styles to that component and prevent styles from leaking into other components. Is that what you're looking for?

Also, not sure if `@import` gets scoped. See [this ](https://forum.vuejs.org/t/import-style-file-doesnt-scoped/7479/2)if you're having issues.

**Comment by XiaoNode** [comment]
wow,Looks like it can solve the problem in your URL，thx very much!
