### ISSUE TITLE
Add a WebM and MP4 loader (file-loader) to the default build webpack config

### ISSUE THREAD

**Issue by kunsam** [nuxt/nuxt.js#1222]
I'm meeting the case that need to use video source in my page.

`When the loaders are defined in the nuxt.config.js, the default loaders will be overwritten.`, the docs says.

Meanwhile I'm thinking that why not use delta updates. I mean the loader config is made up of user's and default config. I don't want add a loader my want to overwrite all config.

**Comment by pi0** [comment]
Video loader is now available with #1224
