### ISSUE TITLE
Publish a SVG version of the logo

### ISSUE THREAD

**Issue by ndelangen** [nuxt/nuxt.js#1226]
Maybe create a repo for a multitude of versions of logo and other material usable for presentations etc.

**Comment by ndelangen** [comment]
I found one without the text:

https://www.headwire.com/img/nuxt.svg

**Comment by alexchopin** [comment]
Hi @ndelangen,
We are working on the new documentation website for the version 1.
We will add a dedicated page for these resources, thanks for the proposal 👍 
I'll add this issue to the [nuxtjs.org](https://github.com/nuxt/nuxtjs.org/issues) repo.
