### ISSUE TITLE
I can't open any routes in nuxt version 1.0.0-rc3 in produciton

### ISSUE THREAD

**Issue by Harveyzhao** [nuxt/nuxt.js#1227]
![image](https://user-images.githubusercontent.com/15974393/28775909-da6885f2-7626-11e7-8030-9be5f7c4ff3d.png)
![image](https://user-images.githubusercontent.com/15974393/28775922-ea546ff8-7626-11e7-8fab-5be450730cff.png)

I can use 'nuxt start',and it's ok! But when I using nuxt.render like the follow image,I can't visit any page,but I can visit the static page

**Comment by Harveyzhao** [comment]
The request was pending all the time,but no response.

**Comment by Harveyzhao** [comment]
I know the answer,I must define NODE_ENV as 'production'，Otherwise，it will be broken。I define the different NODE_ENV to different environment,such as 'UAT'
So I must change the way to realize~

**Comment by pi0** [comment]
@Harveyzhao True, for production environments we need to explicitly disable `dev`. I suggest refactor logics about env detection inside `nuxt.config.js`.
