### ISSUE TITLE
Error: Couldn't find a `pages` directory

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#1228]
Hi. Just updated to 1.0.0.rc-3, and have this error:

`Error: Couldn't find a `pages` directory`

But i have it in my root directory... 

@Atinux @alexchopin

**Comment by lukasborawski** [comment]
Found it, but this is still a bug imho. So, when i'm using BASE_URL env with nuxt the error is appearing. Without not or maybe i missed something important that comes with 1..-rc?

**Comment by Lacroute** [comment]
hi @lukasborawski,

You can specify a base url for:

1. The [router](https://nuxtjs.org/api/configuration-router/#base)
2. The assets [public path](https://nuxtjs.org/api/configuration-build/#publicpath
)

You can also define [environment variables](https://nuxtjs.org/api/configuration-env/#the-env-property) inside the `nuxt.config.js` file.

If you want to pass variables through the command, open your `package.json` and add them there.
ex:
```
"scripts": {
    "dev": "NODE_ENV=development BASE_URL=https://api.com nuxt"
}
```
Then you'll be able to access to them via `process.env.BASE_URL`.
