### ISSUE TITLE
Can't load svg file in nuxt version 1.0.0-rc3

### ISSUE THREAD

**Issue by kamwing** [nuxt/nuxt.js#1229]
![image](https://user-images.githubusercontent.com/183904/28776767-b381afb4-762a-11e7-9285-5f0df87e4e2f.png)

![image](https://user-images.githubusercontent.com/183904/28776940-89f55410-762b-11e7-9ec6-852502e18752.png)

**Comment by BjornMelgaard** [comment]
try change ~assets to ~/assets

**Comment by kamwing** [comment]
@BjornMelgaard 
change ~assets to ~/assets is not work :(

`This dependency was not found:
* /assets/svg/logo.svg in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-331f1379","hasScoped":true,"preserveWhitespace":false}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./pages/index.vue`

**Comment by lukasborawski** [comment]
now you have to change your paths from `~something` to ~/something`

**Comment by BjornMelgaard** [comment]
:man_shrugging:

**Comment by Pandazaur** [comment]
Have you tried somthing like:

```vue
<img :src="require('~/assets/svg/logo.svg')" />
```
or 
```vue
<img src="assets/svg/logo.svg" />
```

**Comment by dojineko** [comment]
I also encountered the same problem. i tried these,

```vue
<!-- # works -->
<img src="~~/assets/svg/logo.svg" />
<img :src="require('~/assets/svg/logo.svg')" />

<!-- # not works -->
<img src="~/assets/svg/logo.svg" /> <!-- Module not found: Error: Can't resolve -->
<img src="assets/svg/logo.svg" /> <!-- not converted -->
```

**Comment by jazoom** [comment]
1.0.0-rc6, getting `Failed to load resource: net::ERR_CONTENT_DECODING_FAILED` when loading an SVG like this in production:

`<img src='/images/image.svg'></img>`

It loads sometimes. It might be related to the service worker. I've just ported project from Ream to Nuxt.

**Comment by Atinux** [comment]
Please use last version of nuxt.js please and re-open if still broken.
