### ISSUE TITLE
I have to run under the dev in the build after the start can not open the page without any tips - 萌新 菜鸟问个弱鸡问题  我在dev下 都运行的好好的 在build后 start   打不开网页 也没任何提示

### ISSUE THREAD

**Issue by z253573760** [nuxt/nuxt.js#1233]
萌新 菜鸟问个弱鸡问题  我在dev下 都运行的好好的 在build后 start   打不开网页 也没任何提示 
用的是NUXT/KOA

Translate:
Meng new rookie asked a weak chicken problem I have to run under the dev in the build after the start can not open the page without any tips
Using the NUXT / KOA

**Comment by IlyaSemenov** [comment]
See https://github.com/nuxt-community/koa-template/pull/21 for the fix.
