### ISSUE TITLE
useHead has no effect when using layout

### ISSUE THREAD

**Issue by zerosdev** [nuxt/nuxt.js#12332]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `auth`
- Runtime Modules:  `@nuxt-alt/auth@2.1.9`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

Create a layout then create a page that using that layout. Put useHead({ title: 'From Page' }) inside your page. Now the browser page title is not same as expected (not showing "From Page"). But when you use useHead({ title: 'From Layout' }) inside the layout now browser page title working as expected (showing "From Layout")

**Comment by VasanthThoraliKumaran** [comment]
@zerosdev May I know how you solved this issue? Right now I have default and custom layouts. useHead is not getting overridden when it is used inside custom layout pages. Any help is appreciated. thanks.

**Comment by zerosdev** [comment]
> @zerosdev May I know how you solved this issue? Right now I have default and custom layouts. useHead meta tags is not getting overridden when it is used inside custom layout pages. Any help is appreciated. thanks.

Try to use definePageMeta({title: "Your Title"})

**Comment by VasanthThoraliKumaran** [comment]
> > @zerosdev May I know how you solved this issue? Right now I have default and custom layouts. useHead meta tags is not getting overridden when it is used inside custom layout pages. Any help is appreciated. thanks.
> 
> Try to use definePageMeta({title: "Your Title"})

Thanks! I fixed it now by passing definePageMeta({layout: false}) and using <NuxtLayout name="custom-layout"> in template.
