### ISSUE TITLE
nuxt shouldnt generate children routes for wildcard routes

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#1234]
### what do you want to do
I would like to have the following urls:
```
/category1/subcategory2/.../subcategoryx
/product_name/p/product_id
```
So there is no 'type' identifier at the start of the url, which means you need to trick vue-router a bit in using the correct component. Here I use the `/p/` part in the product url to identify between categories and products. (Even better would be if you could identify by 'product_id = integer' and 'subcategory = string' but afaik this is not possible with vue-router)

### what did you do
In my pages folder I have the following structure:
```
pages
├── _.vue // component for category pages
└── _/
   └── p/
       └── _.vue // component for product pages
```

### what did you expect to happen
The correct configuration for vue-router should be as follows. Also see this jsfiddle: https://jsfiddle.net/50wL7mdz/50616/
```
[{
   path: '/*/p/*',
   name: 'all-p',
   component: products
},{
   path: '/*',
   name: 'all',
   component: categories,
 }]
```
### what happened actually
nuxt generates the above routes with `children` routes:
```
{
   path: '/*',
   name: 'all',
   component: categories,
   children: {
      path: 'p',
      name: 'all-p',
      component: products
   }
 }
```
But as both routes will contain a `*`, the routes should be added in ascending greediness (with '/*' being most greedy). By using a children structure you loose the ability to list routes based on their greediness. It seems Nuxt.js already does this correctly when you use `:slug`'s, but not when you use wildcards.

**Comment by alexchopin** [comment]
Hi @pimlie, have you tried with the following structure?
```
pages
├── _/
   └── p/
       └── index.vue // component for category pages
       └── _.vue // component for product pages
```

**Comment by pimlie** [comment]
Yes, I did (just now :wink: )

Resulting `.nuxt/router.js` (on rc3) also lists the routes in wrong order:
```js
                {
                        path: "/*",
                        component: _15c1aa07,
                        name: "all"
                },
                {
                        path: "/*/p/*",
                        component: _3ffae7f5,
                        name: "all-p-all"
                }
```

**Comment by alexchopin** [comment]
It's not a bug from Nuxt.js but an issue with the way you are building your router.
`/*` and `/*/p/* are the same and will match all routes, no matter the order of them.
When you are using `/*` the value can be `a/p/b/c` as well. 
If you want to use this option you need to test the value in your file.
Your [jsfiddle](https://jsfiddle.net/50wL7mdz/50616/) example is showing this conception issue.

**Comment by pimlie** [comment]
@alexchopin but my jsfiddle exactly shows that the routes will work when they are listed in reversed order? The jsfiddle had the routes also wrongly listed, but if you take this one https://jsfiddle.net/50wL7mdz/50763/ and click on `Prod` you get the text `prod 1`, but if you click on `Prod 2` you get `cat` because the route with  a `b` is listed _after_ the cat definition.  Or did you mean something else?

**Comment by pimlie** [comment]
> /* and /*/p/* are the same and will match all routes, no matter the order of them.

@alexchopin the vue-router docs also state something differently: https://router.vuejs.org/en/essentials/dynamic-matching.html

> Matching Priority
> Sometimes the same URL may be matched by multiple routes. In such a case the matching priority is 
> determined by the order of route definition: the earlier a route is defined, the higher priority it gets.

**Comment by pimlie** [comment]
because of the difference in how slugs and * are ordered, the following structure does work (but you need to duplicate the category component or add a symlink from _ to index).
```
pages
├── _slug/
   ├── index.vue // component for 1st level category pages
   └── _.vue // component for 2nd+ level category pages
   └── p/
       └── _.vue // component for product pag
```
corresponding generated router looks like
```js
         {
                        path: "/:slug",
                        component: _56ab24f2,
                        name: "slug"
                },
                {
                        path: "/:slug/p/*",
                        component: _504c21a0,
                        name: "slug-p-all"
                },
                {
                        path: "/:slug/*",
                        component: _63341c02,
                        name: "slug-all"
                }
```
