### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] useBody is not defined 

### ISSUE THREAD

**Issue by Venegrad** [nuxt/nuxt.js#12365]
### Environment

Nuxi 3.0.0                                                                                                                                         02:26:01
                                                                                                                                                   02:26:02
RootDir: C:/Users/venegrad/Desktop/venegrad                                                                                                        02:26:02
Nuxt project info:                                                                                                                                 02:26:02

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `alias`, `plugins`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```
import query from "@/server/config/db";

export default async (event) => {
  const body = await useBody(event);
  console.log(body)

  const { data, error } = await query("INSERT INTO users (name, role, password) VALUES ('ref', '212', '123')");
  return {
    data,
    error
  }
} 
```

### Describe the bug

One moth ago all works fine, but afterr update queries wont work, get an error: `[nuxt] [request error] [unhandled] [500] useBody is not defined `

as example code: 

```
import query from "@/server/config/db";

export default async (event) => {
  const body = await useBody(event);
  console.log(body)

  const { data, error } = await query("INSERT INTO users (name, role, password) VALUES ('ref', '212', '123')");
  return {
    data,
    error
  }
} 
```

thats first, and second:

```
 ERROR  (node:15980) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time                               02:22:32
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by iBobik** [comment]
Omg, how could working function disappear without deprecating it first and keeping it working at least few months?

**Comment by danielroe** [comment]
It was deprecated for some time (1 August 2022) and only removed immediately before the release of Nuxt 3, in November.

**Comment by iBobik** [comment]
Interesting, linter haven't warned me about deprecating when I used it. 🤔20. 2. 2023 v 19:42, Daniel Roe ***@***.***>:﻿
It was deprecated for some time (1 August 2022) and only removed immediately before the release of Nuxt 3, in November.
