### ISSUE TITLE
How to change generated static app to another directory.

### ISSUE THREAD

**Issue by irthos** [nuxt/nuxt.js#1238]
To separate concerns, i've got 2 directories, nuxt-client and feathers-server. i want nuxt to generate and drop the static site to feathers-server/public instead of nuxt-client/dist. Can I define this in config or is there another way to accomplish this?

**Comment by maicong** [comment]
please see: https://nuxtjs.org/api/configuration-generate#dir

**Comment by dimitrieh** [comment]
For people searching for an example: https://github.com/nuxt/nuxt.js/issues/294#issuecomment-350418107
