### ISSUE TITLE
How to add custom resolve.alias in nuxt.conig.js

### ISSUE THREAD

**Issue by chuanxd** [nuxt/nuxt.js#124]
like as webpack config setting:

```js
resolve: {
    alias: {
      '~src': projectSrc,
      '~utils': path.join(projectSrc, 'utils'),
    }
}
```

**Comment by Atinux** [comment]
Hi @chuanxd 

You can do it with the `extend` method in the `build` property of your `nuxt.config.js` file:

```js
const resolve = require('path').resolve

module.exports = {
  build: {
    extend (config) {
      config.resolve.alias['~src'] = projectSrc
      config.resolve.alias['~utils'] = resolve(projectSrc, 'utils')
    }
  }
}
```

You might want to check the `srcDir` option as well (see https://github.com/nuxt/nuxt.js/pull/44).

Then, you can use the `~` alias and do `~/utils` to link to your `utils/` folder.

**Comment by chuanxd** [comment]
@Atinux  thank you for your reply.

**Comment by baztypetrucci** [comment]
@Atinux I'm trying to use your solution but the console says that alias is not defined:
`(node:887) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 34)
  ReferenceError: alias is not defined`

I'm using Nuxt 1.0.0 RC

**Comment by randyhoulahan** [comment]
@baztypetrucci did you get the hammer.js alias working?  If yes can you share?

**Comment by baztypetrucci** [comment]
@randyhoulahan I think this worked:

`build: {
    /*
    ** Run ESLint on save
    */
    vendor: [
      '@nuxtjs/axios',
      '@nuxtjs/bootstrap-vue'
    ],
    extend(config, ctx) {
      //if (ctx.dev && ctx.isClient) {
      config.module.rules.push({
        enforce: 'pre',
        test: /\.(js|vue)$/,
        //loader: 'eslint-loader',
        exclude: /(node_modules)/
      })
      //}
      config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJs')
      config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJsPlugin')

      if (ctx.isServer) {
        config.resolve.alias['hammerjs$'] = this.options.rootDir + 'node_modules/vue-touch/dist/hammer-ssr.js'
      }

    }
  }`
