### ISSUE TITLE
Why are there two assets at the same time? Why are the ~assets and ~/assets

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1241]
Why are there two assets at the same time?
Why are the ~assets and ~/assets
![image](https://user-images.githubusercontent.com/17898715/28806808-8ebbf0b6-76a4-11e7-87e2-69691a035057.png)
@pi0 @alexchopin

**Comment by alexchopin** [comment]
Hi @yuchonghua,
`~assets` is a Vue.js (vue-router) alias and can be used inside `<template>` and `<style>` tags.
`~/assets` is a Nuxt.js alias and can be used inside `<script>` tag.

**Comment by yuchonghua** [comment]
~assets and ~/assets can be unified

**Comment by yuchonghua** [comment]
If not uniform, feel the new version of nuxt use is very strange, even the name of each place is not the same

@alexchopin

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/28813940-082ea7c6-76ce-11e7-9542-0bdf1be6188d.png)

**Comment by yeziZ** [comment]
@alexchopin
Yes ah, I have encountered this problem, why engage in two standards?
Is not it awkward to develop?

**Comment by HadiChen** [comment]
@alexchopin Would you please fix this situation?

**Comment by yuchonghua** [comment]
@Atinux Do not you think it's not a troublesome thing? Even with a path to use a different logo to visit? The

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/29149739-acd44fd4-7da8-11e7-9a15-69565c4b7a5d.png)
![image](https://user-images.githubusercontent.com/17898715/29149769-db679fa4-7da8-11e7-92a4-f840bf53de9b.png)

Now vue file introduction style or problems

\ping @alexchopin @pi0 @Atinux

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/29150222-b4424b24-7dab-11e7-9370-18bef25fa22d.png)
![image](https://user-images.githubusercontent.com/17898715/29150229-c08dca34-7dab-11e7-9277-9f2e8965cee6.png)
\ping @alexchopin @pi0 @Atinux

**Comment by pi0** [comment]
Just as a test, does change it to `@/assets/web/...` fixes problem?

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/29156626-817061de-7dd5-11e7-8f1c-be711d350dc5.png)
![image](https://user-images.githubusercontent.com/17898715/29156630-85c1140e-7dd5-11e7-94db-13f6be9c87e0.png)

**Comment by yuchonghua** [comment]
Use `~assets/web/images/...` can be normal

**Comment by HadiChen** [comment]
I am also experiencing this problem

**Comment by coderPreacher** [comment]
I am also experiencing this problem

**Comment by yeziZ** [comment]
Now vue-loader loading style inside the css have this problem, what is the reason for this problem?

**Comment by yuchonghua** [comment]
```shell

git clone https://github.com/ddvjs/nuxt-assets-bug.git
cd nuxt-assets-bug
npm i
npm run dev

```
![image](https://user-images.githubusercontent.com/17898715/29238811-f8cd8c12-7f6e-11e7-8958-eef89b24f1de.png)

![image](https://user-images.githubusercontent.com/17898715/29238813-07992e72-7f6f-11e7-8cdf-91eec4ba816f.png)

![image](https://user-images.githubusercontent.com/17898715/29238817-17af3ebe-7f6f-11e7-90e7-ccb567c27500.png)

**Comment by zhong-jia-wei** [comment]
I also encountered this problem. But have not found a solution

**Comment by Depravitys** [comment]
I have the same problem，Can some one tell me how to do this?

**Comment by pi0** [comment]
After some investigations, it seems this problem is not causing by `vue-loader/transofrm-require` that was fixed for templates usage. Currently before finding fix, as @yuchonghua suggested the only workaround is **using ~assets/web/images/...**

**Comment by pi0** [comment]
2ff8b5a should finally allow `~/assets` and `~/static` usage everywhere. Keeping this thread open until next release if anyone has better workaround :)

**Comment by yuchonghua** [comment]
thank @pi0 very much

**Comment by pi0** [comment]
Will be available in `rc5`.

**Comment by yuchonghua** [comment]
Very much hope that rc5 can be released faster.
/ping @pi0

**Comment by yuchonghua** [comment]
Very much hope that rc5 can be released faster.
/ping @Atinux @pi0
