### ISSUE TITLE
Transition leave is a bug?

### ISSUE THREAD

**Issue by VadiForte** [nuxt/nuxt.js#1242]
I try to fix it but it seem not work at all.

The animation enter work perfectly fine.

but animation leave is not work.

how to solve this?

Thank you.

I also read some issue in Vuejs github. Evan said since January that is a bug on Vuejs and I think he fixed it now. im not sure which version we using in Nuxtjs?

**Comment by alexchopin** [comment]
Hi @VadiForte,
We use the last version of Vue.js in the rc3 of Nuxt.js.
Can you give us more info about how and where you are using transitions to help you?

**Comment by VadiForte** [comment]
Here is my code: 

```
<template lang="pug">
  header
    nav
      .container
        .navbar-group
          .navbar-header
            button.navbar-toggle.collapsed(@click="toggleMenu" type='button')
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand(href='./')
              img.logo(src='/img/logo-bg.png')
          transition(name="fade")
            #happenn(:class="{ in: isMenuOpen }" v-show="isMenuOpen").navbar-collapse
              menu-list
</template>
```
```
<style lang="less">
  .fade-enter-active, .fade-leave-active {
    transition: opacity 0.75s;
  }

  .fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
    opacity: 0
  }
</style>
```

Thank you.

**Comment by alexchopin** [comment]
Should be fixed with the last release
