### ISSUE TITLE
condition for template root element doesn't work !

### ISSUE THREAD

**Issue by RezaHaidari** [nuxt/nuxt.js#1243]
after update to nuxt rc3, I encountered with many breaking changes ... but i think this is a bug, when I've used a condition for template root element i get some errors !

![bug1](https://user-images.githubusercontent.com/12013210/28810983-e037b4e6-76a1-11e7-9d68-3e524d14dc16.PNG)
![bug2](https://user-images.githubusercontent.com/12013210/28810986-e09d5ac6-76a1-11e7-8cce-7a3975fd6ab0.PNG)

**Comment by VadiForte** [comment]
Im not sure this will help you. but,

You can't have 2 `<div>` in a template

try to put those 2 `div` inside 1 `div`

**Comment by RezaHaidari** [comment]
@VadiForte 
I know that, but it's not good solution, specially when i want pass a class(es) from component element

**Comment by pi0** [comment]
Hi @RezaHaidari This is not a change by Nuxt but Vue itself which requires having exactly **one root element** for each component. Currently, we have  two options:

- Wrapping it into a parent `<div>` as Vadi mentioned.

- Using `:is` for [dynamic components](https://v1.vuejs.org/guide/components.html#Dynamic-Components) which i think is what you need. I've prepared a demo for using the second approach hope it helps : 
https://nuxt-dy.glitch.me
https://glitch.com/edit/#!/nuxt-dy

**Comment by pi0** [comment]
An in depth detail about current problem is, `vue-template-compiler` statically analyzes that condition resulting something like this:

![image](https://user-images.githubusercontent.com/5158436/28820703-db8f1e04-76c7-11e7-8dff-4927a580d612.png)

As you can see the `v-else` part is stripped from chunk. So changing to something like this:
```vue
<template>
  <div v-if="show"> display it. </div>
  <div v-else> else display it. </div>
</template>

<script>
export default {
  data() {
    return {
      show: false
    }
  }
}
</script>
```

Makes things partially better:

![image](https://user-images.githubusercontent.com/5158436/28821019-12dc2554-76c9-11e7-901f-587fe1f75e8e.png)

Still `vue-server-renderer` strips top level conditions like this:

```html
</div><!----></div>
```

Investigating on exact problem :)

**Comment by RezaHaidari** [comment]
@pi0 dear pooya thanks for detailed explanation <3

**Comment by pi0** [comment]
Update: This problem seems being resolved with latest Nuxt RC6 dependencies. (Locally tested with both dev and prod build). Please reopen if problem it happens anymore.

**Comment by Meeeeow** [comment]
Still reproduce on rc11 @pi0 , same error message
