### ISSUE TITLE
Where is the "Entry point" like app.js in the Vuejs?

### ISSUE THREAD

**Issue by VadiForte** [nuxt/nuxt.js#1245]
I try to put something in common. but only solution i found here is put it on header or footer.

Right now i try to use Vue-analytic 

```
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: 'UA-XXX-X'
})

```

so im not sure where to write 
```
Vue.use(VueAnalytics, {
  id: 'UA-XXX-X'
})
```

thank you

**Comment by awronski** [comment]
You can use nuxt module for GA which is working great.
https://github.com/nuxt-community/modules/tree/master/modules/google-analytics

**Comment by cawa-93** [comment]
Create a separate plug-in
https://nuxtjs.org/guide/plugins/

**Comment by VadiForte** [comment]
Thank you guy, But im still wondering is that Nuxtjs have no Entry point and everything should be in nuxt.config right?
