### ISSUE TITLE
Aliases broken in rc3

### ISSUE THREAD

**Issue by lifedispenser** [nuxt/nuxt.js#1246]
Seems like aliases (ie: ~components = ~/components, ~plugins = ~/plugins, etc) are broken in 1.0.0-rc3, at least in my project.

Accidentally upgrading from nuxt 1.0.0-alpha5 to 1.0.0-rc3 ended up with these errors when running `npm run build`:
```
These dependencies were not found:

* ~components/category-filter.vue //...etc
```

In 1.0.0-alpha5 `dist/nuxt.js` contained the following but it is missing in 1.0.0-rc3
```
/node_modules/nuxt/dist/nuxt.js:
  365          '~router': __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_2_path__["join"])(this.buildDir, 'router'),
  366          '~pages': __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_2_path__["join"])(this.srcDir, 'pages'),
  367:         '~components': __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_2_path__["join"])(this.srcDir, 'components')
  368        },
  369        modules: [__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_2_path__["join"])(this.dir, 'node_modules'), nodeModulesDir]
//etc
```

**Comment by awronski** [comment]
> Aliases are now ~, ~~, @, @@, assets and static (~plugins should be renamed to ~/plugins for example)

Check:
https://github.com/nuxt/nuxt.js/releases/tag/1.0.0-rc3

**Comment by lifedispenser** [comment]
Oh got it, thanks.
