### ISSUE TITLE
Exposed server URL after deployed

### ISSUE THREAD

**Issue by xianweics** [nuxt/nuxt.js#1247]
I have a problem. Server URL was exposed after the project was deployed. It will cause security issue, so please help me fix the issue. 
![km 1hh k5ym97j p017x 8](https://user-images.githubusercontent.com/24938102/28815674-b751c228-76d4-11e7-9af8-001cc344264f.png)

**Comment by pi0** [comment]
Hi @xianweics . You may completely disable source-maps using `nuxt.config.js`.
```js
build: {
  extend (config) {
    config.devtool = false
  }
}
```

**Comment by Atinux** [comment]
What is your `nuxt.config.js` @xianweics ?

**Comment by xianweics** [comment]
@pi0 Thank you for your help, but it doesn't work after I set  `config.devtool = false`. However, I tried to remove the keyword   ` ?sourceMap` in the nuxt.js file, it worked. 

![image](https://user-images.githubusercontent.com/24938102/28854197-44c14bea-7768-11e7-8a72-815acf2bbef0.png)


Can you tell me how to set `sourceMap ` in the `nuxt.config.js`, or other way to fix this issue.

**Comment by xianweics** [comment]
@Atinux My `nuxt.config.js` is 

![image](https://user-images.githubusercontent.com/24938102/28854340-3a4d2872-7769-11e7-9b97-4f9593ab8801.png)

Please help me.

**Comment by vsr** [comment]
Setting `config.devtool = false` disables sourceMap for JavaScript code. It does not affect the sourceMaps generated for styles. 

Taking hint from @xianweics's comment I've been able to remove sourceMap params passed to loaders using this hack in extend:

```javascript
      function replaceSourceMap(string) {
        return string.replace('sourceMap', '')
      }
      function replaceInArray(array) {
        array.forEach((item, index) => array[index] = replaceSourceMap(item))
      }
      config.module.rules.forEach(rule => {
        if (rule.use)
          replaceInArray(rule.use)
        if (rule.query && rule.query.loaders)
          Object.keys(rule.query.loaders).forEach(key => {
            const loader = rule.query.loaders[key]
            if(typeof loader === 'string') {
              rule.query.loaders[key] = replaceSourceMap(loader)
            }
            else {
              replaceInArray(loader)
            }
          })
      })
```

**Comment by xianweics** [comment]
Thx. It works. @vsr
