### ISSUE TITLE
asyncData promise resolve order and conditional DOM element results in DOMException: Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#1248]
I thought I'd open a new issue opposed to this issue that's closed: https://github.com/nuxt/nuxt.js/issues/1214

The original problem isn't really as described once I drilled down.

Replication: https://github.com/silverbackdan/v-if-nuxt

The repo outlines an issue where there is a shared import between a parent and child. The parent's asyncData resolves after the child's - this causes an issue where the child is using a `v-if` attribute (on it's own data).

All is OK when running in development mode. The issue arises after a build and running in production.

Steps to reproduce with the repo:
- `npm run nuxt:build`
- `npm run nuxt:start`
- Navigate to http://127.0.0.1:3000/1

The error in the console
```
[nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.Ye [as appendChild]
```

Main code in repo to note:

Forcing parent data to populate later than child:
https://github.com/silverbackdan/v-if-nuxt/blob/master/plugins/page.js#L3

The element using v-if that triggers the issue:
https://github.com/silverbackdan/v-if-nuxt/blob/master/pages/index/_news.vue#L5

This is to simulate an ajax call where the data for a parent page may take longer to load than the child. Website where this is happening: https://demo.starter.b-w.uk/news/August-2017/my-1st-news-post

**Comment by Atinux** [comment]
Hi @silverbackdan 

Thank you for this issue and the reproduction, I will take a look at it.

**Comment by Atinux** [comment]
Related to https://github.com/nuxt/nuxt.js/issues/1243

**Comment by LookinGit** [comment]
Also collided with this problem, there is a solution?

**Comment by LookinGit** [comment]
@silverbackdan for a quick solution to this problem try to set name of page for parent and children pages.
Example:
`
// Parent page
export default {
 name: 'Parent',
 ...
}
`
`
// Children page
export default {
 name: 'Children',
 ...
}
`

**Comment by silverbackdan** [comment]
Thanks @LookinGit ! I haven't been able to spend time on the project where this was happening and there are a few bits broken but I'll try and get that tested as soon as I can - that'd be great if it's that simple :)

**Comment by Jussiadev** [comment]
@LookinGit I try, but it did't help

```
<script>
    import LittleSearch from '~/components/littleSearch'
    import LeftSide from '~/components/leftSide'
    import AlphabetSearch from '~/components/alphabetSearch'
    import SeenGoods from '~/components/seenGoods'
    import Catalog from '~/components/catalog'
    export default {
        name: 'Brends',
        head () {
            return {
                title: 'Бренды',
                meta: [
                    {name: "description", content: "Описание"}
                ]
            }
        },
        layout: 'headerAndFooter',
        components: {
            LittleSearch,
            LeftSide,
            AlphabetSearch,
            SeenGoods,
            Catalog
        },
        data () {
            return {
                goods: [
                    {
                        "id": 1,
                        "title": "Сосиски", //Обрезается так чтобы помещалось в 1 строку в карточке товара, в конце добавляем триточие
                        "promo": false,
                        "description": "Атяшево", //Обрезается так чтобы помещалось в 2 строки в карточке товара, в конце добавляем триточие
                        "image": "img/sliders/brand7.png", // Ссылка на файл
                        "brend": "Атяшево",
                        "brend_id": 2,
                        "min_price": "99.33",
                        "rate": 4.5,
                        "count_rate": 348
                    }
                ]
            }
        }
    }
</script>
```

**Comment by LookinGit** [comment]
@Jussiadev, it`s working for pages with asyncData
a write, please, code of page with asyncData or more detail error

**Comment by Jussiadev** [comment]
@LookinGit  My error is
Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.We [as appendChild].
