### ISSUE TITLE
How can this be a problem? I think this is an obvious bug

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1249]
How can this be a problem? I think this is an obvious bug, at least with the same set of frames why two standards, at least not many developers agree with this awkward two standards

[Why are there two assets at the same time? Why are the ~assets and ~/assets](https://github.com/nuxt/nuxt.js/issues/1241)

@pi0 @couac @alexchopin

**Comment by pi0** [comment]
@yuchonghua Please don't create duplicate issues and continue the thread on #1241. We are working hard to make one stable convention working everywhere.
