### ISSUE TITLE
`nuxt generate` does not exit with an error code

### ISSUE THREAD

**Issue by qur2** [nuxt/nuxt.js#125]
Hi,

I ran into issue today because the site builder (a gitlab pipeline) did not fail despite the fact that webpack output some errors.
I'll have a look into it, but is seems like nuxt too optimistic at the moment.

Cheers,
Aurélien.

**Comment by Atinux** [comment]
Hi @qur2 

I will take a deeper look into it.

**Comment by Atinux** [comment]
It will be fixed in the upcoming release, it will exit with the status code 1 if the webpack build fails.

**Comment by Atinux** [comment]
It will now quit if an error happened in the build process, see the [0.9.7](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.7) release.
