### ISSUE TITLE
how to add a local minify js 

### ISSUE THREAD

**Issue by mingliao** [nuxt/nuxt.js#1250]
hi everyone , thanks for pretty project . the *nuxt.js* project  make my coding happy  👍 👍 👍 

now i have a problem , in my page ,i add a extra **swiper.min.js** that the file have minfiy, and the file not a  *common.js* module , i want to include it in my page ,but when i use it as a  **plugin**  and config in **nuxt.config.js** like the below: ``` vendor: ['~/plugins/swiper/swiper.min']``` it show me much   **eslint** error,
![1](https://user-images.githubusercontent.com/4270467/28833836-20b25082-7713-11e7-9ff2-f207275dd9ec.png)
when i use it as external resources like the doc:[  How to use external resources?](https://nuxtjs.org/faq) in my page vue  like below:
```
export default {
    head: {
      script: [
        { src: ' ~static/swiper/swiper.min.js' }
      ],
      link: [
        { rel: 'stylesheet', href: '~static/swiper/swiper.min.css' }
      ]
    },
.......
```
and it show me **404** error like this:
![2](https://user-images.githubusercontent.com/4270467/28834113-fb5e81d8-7713-11e7-985e-4e2334886a7a.png)
or 
![image](https://user-images.githubusercontent.com/4270467/28834270-5e6fb38c-7714-11e7-9531-fe18dd17adda.png)

i don't konw how to solve my problem then , thanks for someone to solve this problem

**Comment by pi0** [comment]
Hi. For static assets you may use this URL:
```js
 { src: ' /swiper/swiper.min.js' }
```

**Comment by mingliao** [comment]
@pi0  thank you  very very  much  :) 

 I hope the [How to use external resources?](https://nuxtjs.org/faq) could add the issues i met .

**Comment by thisAries** [comment]
我也遇到了这个问题。
swiper.js 使用 {src ： '/ swiper/swiper.min.js ' }，是在什么地方使用呢？是在
component 下的 export default{head: {
    script: [
      {src ： '/ swiper/swiper.min.js ' }
    ]
  }}    是这样吗？ 但是这样会报错,
 nuxt:render Rendering url /elesw +0ms
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225725
npm ERR! aid@1.0.0 dev: `nuxt`
npm ERR! Exit status 3221225725
npm ERR!
npm ERR! Failed at the aid@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-04-03T01_34_47_282Z-debug.log,
但是 如果我的js使用cdn方式就是正常的
export default {
  head: {
    script: [
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.2/js/swiper.js' }
    ]
这样就是正常的
