### ISSUE TITLE
how to new a Obj from static js file not import 

### ISSUE THREAD

**Issue by mingliao** [nuxt/nuxt.js#1251]
I add a *swiper.min.js* as the doc [ How to use external resources? ](https://nuxtjs.org/faq/) and i need new a swiper obj (simply the code ) like below :
```
 export default {
head: {
      script: [
        { src: '/swiper/swiper.min.js' }
      ],
      link: [
        { rel: 'stylesheet', href: '/swiper/swiper.min.css' }
      ]
    },
  mounted () {
       // simply the code
        new Swiper('.swiper-container', {
          pagination: '.swiper-pagination',
          loop: true
        })
    },
}
```
then the  console show error like this:
![image](https://user-images.githubusercontent.com/4270467/28836226-af5896b4-771a-11e7-93ab-3b1b62437093.png)

why can't i use import the swiper file please check #1250  
thank for some one to solve my problem :)

**Comment by benfavre** [comment]
This is not related to Nuxt.
This is "How do es6 imports work", and how do Vuejs single file components work.

https://vuejs.org/v2/guide/single-file-components.html
https://stackoverflow.com/questions/35541864/es6-export-default-function

**Comment by pi0** [comment]
@mingliao For using swiper with Nuxt and SSR, you may try [vue-awesome-swiper](https://github.com/surmon-china/vue-awesome-swiper) as a Nuxt plugin.

**Comment by mingliao** [comment]
@pi0 @benfavre   ok，thank you and i have a question. if i  have a global js file  in clientside like *jquery*   or *jquery plugin* and  the file is not a *common.js* module, i could include it as a static file in *head* config i mention in my issue, but how did i what to use the function or property in these *not commonjs* file ?

**Comment by pi0** [comment]
You can expose global functions using `window`. Usually libraries do this them self. So for example jquery is available using `window.$` if is added to head. BTW try to rethink about your libraries, having jquery with vue is not a good idea.

**Comment by benfavre** [comment]
@mingliao Think you need to do a bit of reading about VueJS, Webpack and Nuxt.
https://nuxtjs.org/faq/webpack-plugins

**Comment by mingliao** [comment]
@pi0  thank you  o(^▽^)o  ，as you mention above， I solve my problem . and i will try your idea code without jquery .

**Comment by mingliao** [comment]
@benfavre  thank you  very much，and i will  read the page you mention .
