### ISSUE TITLE
When does process.BROWSER_BUILD receive value?

### ISSUE THREAD

**Issue by christiannwamba** [nuxt/nuxt.js#1253]
I am still confused on how `process.BROWSER_BUILD`. From the example in the [docs](https://nuxtjs.org/faq/window-document-undefined), it seems like it's once the component is loaded in the client.

```js
if (process.BROWSER_BUILD) {
  const vSelect = require('vue-select');
  Vue.component('v-select', vSelect)
  console.log('this is never hit')
}
```

Unfortunately, I have tried everything I can to import the above component without running into such issue but no luck, yet. Apologies if this has an obvious solution, it just happens that I'm yet to get how it works. I'm also aware that window is available in the `mounted` lifecycle but I can't import dependencies in the method.

**Comment by pi0** [comment]
Hi. Please check [rc3 notes](https://github.com/nuxt/nuxt.js/releases/tag/1.0.0-rc3)

> process.BROWSER_BUILD has been removed in flavour of process.browser

**Comment by christiannwamba** [comment]
Great thanks! That seems to have fixed it but then I am getting the following error:

```
Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <VSelect>
       <Pages/List.vue> at pages/_list.vue
         <Nuxt> at .nuxt/components/nuxt.vue
           <Default> at layouts/default.vue
             <Root>
warn @ vue.runtime.esm.js:475
...
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```
