### ISSUE TITLE
Uncaught ReferenceError: defineAppConfig is not defined     at defu.mjs:45:2

### ISSUE THREAD

**Issue by kkan0615** [nuxt/nuxt.js#12545]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `i18n`, `image`, `content`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.7`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@nuxt/content@2.3.0`
- Build Modules:    `-`

### Reproduction

1. Create ```app.config.ts``` File. Following code is example in my project.
```
export default defineAppConfig({
  blogTags: [
    'Node Js',
    'Get Started',
    'Typescript',
    'Gatsby',
    'JavaScript',
    'Next',
    'Nuxt',
    'MDX'
  ]
})
```

2. Call ```useAppConfig()```. ```const appConfig = useAppConfig()```
3. Create any plugins

### Describe the bug

There is a bug when I call ```useAppConfig()``` with plugins

**Comment by delcantao** [comment]
I am getting the same error when adding plugins to my project. There is a solution for it?

**Comment by manniL** [comment]
@delcantao 
Hey! Could you kindly open a new issue with a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by delcantao** [comment]
It seems like I was using the outdated version. My project was in 3.1.1 and when I tried to reproduce it in version 3.1.2 to post the result here the error doesn't happen anymore. 

I updated my project and it now works.
