### ISSUE TITLE
Layers: Prefer local composable over extended layers

### ISSUE THREAD

**Issue by Dominic-Marcelino** [nuxt/nuxt.js#12569]
### Environment

N/A

### Reproduction

https://stackblitz.com/edit/nuxt-framework-6wuutt?file=composables%2Ffoo.ts,base%2Fcomposables%2Ffoo.ts

Create a project that extends another one and try to override one of it's composable.

### Describe the bug

When extending a project I'd expect that I'm able to override composable as we can do with pages and components.

Right now Nuxt logs a warning ` WARN  Duplicated imports "useMainMenu", the one from "<...>/composables/useMainMenu.ts" has been ignored`

I'd expect that the own one would be used as a override and the extended one should be ignored. 
I also think the behaviour is inconsistent as we don't get any warning when overriding components or pages.

**Comment by jjjrmy** [comment]
what about for third party modules?
