### ISSUE TITLE
/src/index.js in multi main

### ISSUE THREAD

**Issue by sj82516** [nuxt/nuxt.js#1256]
I am using `nodejs 8.2 and nuxt 1.0.0-alpha.5 with koa2` .
when I run `npm run dev` it would show this error message but still build success.
However , if I run `npm run build` it would show the same error message then fail.
```
 ERROR  Failed to compile with 1 errors 
This dependency was not found:
* /Users/123/Desktop/Nodejs/folder/src/index.js in multi main
To install it, you can run: npm install --save /Users/123/Desktop/Nodejs/folder/src/
index.js
```
I initialized the project at ` /Users/123/Desktop/Nodejs/folder`.
I have tried to run my koa server by `node ./server/index.js` with removing nuxt rendering settings and It works well.
I didn't create `./src` folder either include any js file in that folder.

**Comment by alexchopin** [comment]
Hi @sj82516, have you tried with 1.0-rc3?

**Comment by sj82516** [comment]
I am using koa2 template and have posted another issue [#1167](https://github.com/nuxt/nuxt.js/issues/1167) , so I still using 1.0.0-alpha.5 version.    
Is 1.0.0-rc3 fix the koa2 template problem ?

**Comment by sj82516** [comment]
I update the nuxtjs and koa-template to rc3. It works now.
Thanks for the great effort , please close this issue.
