### ISSUE TITLE
nuxt-link-active

### ISSUE THREAD

**Issue by gary149** [nuxt/nuxt.js#126]
The index route stay active (and keep the class _nuxt-link-active_) even when another route is active.

![image](https://cloud.githubusercontent.com/assets/3841370/21899319/12f85ac0-d8f0-11e6-86c5-2dd23b01ed63.png)

![image](https://cloud.githubusercontent.com/assets/3841370/21899227/cdbc2ab8-d8ef-11e6-9f3e-3147f9710284.png)

**Comment by Atinux** [comment]
Hi @gary149 

This is an intended behaviour of `vue-router`. To fix this, add the `exact` attribute:

```html
<nuxt-link to="/" exact">Home</nuxt-link>
```

You can learn more of the attributes you can use for `<nuxt-link>` here: https://router.vuejs.org/en/api/router-link.html

**Comment by gary149** [comment]
Thanks!
