### ISSUE TITLE
How to add component to same chunk?

### ISSUE THREAD

**Issue by Alex-Sokolov** [nuxt/nuxt.js#1261]
I have page from document list. Inside I use component for list item. How to add this component to same chunk as page component?

In `.nuxt/router.js`
```
const _3a1484a3 = () => import('..\\pages\\desktop\\document-list\\index.vue' /* webpackChunkName: "pages/desktop-document-list" */).then(m => m.default || m)
const _163289af = () => import('..\\pages\\desktop\\document-list\\document-list-item.vue' /* webpackChunkName: "pages/desktop-document-list-document-list-item" */).then(m => m.default || m)
```

**Comment by alexchopin** [comment]
Hi @Alex-Sokolov, have you tried to use [extendRoutes](https://nuxtjs.org/api/configuration-router#extendroutes)?

**Comment by Alex-Sokolov** [comment]
But how that can help? Maybe components need be grouped by folder to same webpack chunk?

**Comment by alexchopin** [comment]
@Alex-Sokolov can you explain more why you need to group those components into the same chunk?

**Comment by Alex-Sokolov** [comment]
For example, `index.vue` for page and some components related only for that page.

**Comment by alexchopin** [comment]
I'm not sure to understand, but each page has his own chuck in Nuxt.js.
So if you import components in your page, they will be inside the page chunk.

**Comment by Alex-Sokolov** [comment]
Yeah, you sure. Thanks!
