### ISSUE TITLE
Ios9.3 vue lifecycle don't run correctly

### ISSUE THREAD

**Issue by thecorsair** [nuxt/nuxt.js#1262]
![image](https://user-images.githubusercontent.com/4964538/28872347-5d781256-77bb-11e7-9eb8-4da3c1a87e2f.png)

enviorments
nuxt rc3
ios 9.3.3

when enter the page 
beforeMount & mounted don‘t works

android & ios 10 works

**Comment by oo10** [comment]
Did you find the reason?
