### ISSUE TITLE
Babel? Error  in ./.nuxt/index.js  Syntax Error: Unexpected token (92:4) ...App

### ISSUE THREAD

**Issue by midlantica** [nuxt/nuxt.js#1265]
Noob... I was doing fine, then think I npm updated... now Babel messed up.

> npm run dev

` ERROR  Failed to compile with 2 errors                                                                                                                          5:32:57 PM

 error  in ./.nuxt/index.js

Syntax Error: Unexpected token (92:4)

  90 |       }
  91 |     },
> 92 |     ...App
     |     ^
  93 |   }
  94 |
  95 |   const next = ssrContext ? ssrContext.next : location => app.router.push(location)

 @ ./.nuxt/client.js 13:13-31
 @ multi webpack-hot-middleware/client?name=$client&reload=true ./.nuxt/client.js

 error  in ./.nuxt/utils.js

Syntax Error: Unexpected token (26:13)

  24 |       asyncData = this.$ssrContext.asyncData[Component.options.name]
  25 |     }
> 26 |     return { ...data, ...asyncData }
     |              ^
  27 |   }
  28 |   if (Component._Ctor && Component._Ctor.options) {
  29 |     Component._Ctor.options.data = Component.options.data

 @ ./.nuxt/client.js 15:13-31
 @ multi webpack-hot-middleware/client?name=$client&reload=true ./.nuxt/client.js`

I've tried 15 different versions of Babel configs... I saw that the 'latest' had changed: https://nuxtjs.org/guide/release-notes/#improvements
"Add babel-preset-es2015 in dependencies to avoid error with some external libraries"

And I tried diddling the .babelrc file.. and then adding it in nuxt.config.js
` build: {
    babel: {
      "presets": ["es2015"]
    },`

Still no joy. And all was working fine just yesterday... 

It started when it could not find my ~components... but I think I managed to fix that but now the babel config seems screwed. 

`<script>
import Navvy from '~components/Navvy'
import Skills from '~components/Skills'
import Slides from '~components/Slides'
import About from '~components/About'
import Quotes from '~components/Quotes'

export default {
  components: {
    Navvy,
    Skills,
    Slides,
    About,
    Quotes,
  }
}
</script>`

Anyone have any ideas? I've been loving the Nuxt.js experience till now.

**Comment by midlantica** [comment]
![nuxt_babel_issue](https://user-images.githubusercontent.com/1449595/28898264-8485b5ee-77aa-11e7-8e7f-10a521531dce.png)

**Comment by midlantica** [comment]
And if I remove the Babel stuff that I added (because nuxt already takes care of that cleverly (but I got desperate))... I then get a new error — the one that started the whole problem...:
` ERROR  Failed to compile with 5 errors                                 

 These dependencies were not found:

 * ~components/About in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue`

**Comment by thecorsair** [comment]
~/components/  or  @/components

**Comment by VladiSylvan** [comment]
@midlantica How you fix the problem?
