### ISSUE TITLE
why 'const' is in vendor.bundle.js

### ISSUE THREAD

**Issue by thecorsair** [nuxt/nuxt.js#1268]
![image](https://user-images.githubusercontent.com/4964538/28907035-88bde808-784e-11e7-8131-729af2807b51.png)
![image](https://user-images.githubusercontent.com/4964538/28907253-b918cb84-784f-11e7-9533-fcb3c53cf8bb.png)

i don`t use any other npm package
when i run 'npm run dev'
if version of ios <= 9 ,
print 'syntaxError: unexpected keyword const'

**Comment by chuckyo** [comment]
I experience the same in development environment, it works well once I use `nuxt start` to run the project, so I let it go.
