### ISSUE TITLE
Inability to use shortcut colon for v-bind in pages

### ISSUE THREAD

**Issue by LeCoupa** [nuxt/nuxt.js#1270]
Maybe I forgot to configure something but I can't use the colon shortcut for v-bind in pages.

```javascript
step(
  v-for="step in steps"
  :description="step.description"
  :key="step.number"
  :number="step.number"
  :title="step.title"
)
```

Will result in:

```
Module build failed: Error:
    18|           step(
    19|             v-for="step in steps"
  > 20|             :description="step.description"
--------------------^
    22|             :key="step.number"
    23|             :number="step.number"

Syntax Error: Unexpected token
```

The strange thing is that sometimes this shortcut seems to work in files within the `components` folder.

**Comment by alexchopin** [comment]
Hi @LeCoupa, 
Can you post more code about your page component where this bug apear?

**Comment by LeCoupa** [comment]
@alexchopin I don't know what really happened but it is working now. Thanks for your work!
