### ISSUE TITLE
Transition - Access both from/to and element?

### ISSUE THREAD

**Issue by thomasboulongne** [nuxt/nuxt.js#1271]
I need to create a specific transition between the pages `home` and `project` using GSAP. But my problem is:

- if I want to know in my transition the _from_, I need to use the transition function, but then I can't use GSAP on the page _$el_

- and if i want to access the element using the transition object I don't have the _from_ .

How can I do to have both?

**Comment by alexchopin** [comment]
Nuxt.js uses Vue.js [transitions](https://vuejs.org/v2/guide/transitions.html#ad) so you should use the same process. If you need more help, I recommend you to ask more help on our gitter chat.
