### ISSUE TITLE
switch page flash

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#1272]
I find a flash in my app in produciton

you can click anyone in https://www.awesomes.cn/subject/react

then you can find the flash, what cause this?

**Comment by pimlie** [comment]
Are you using `<router-link>` tags to create navigation links?

It looks like the page is refreshing as if you are using `<a href="/link">` instead of `<router-link :to="'/link'">`. To navigate with vue-router you need to use router-link's.

**Comment by bimohxh** [comment]
@pimlie but I just use `<router-link :to="'/link'">`
