### ISSUE TITLE
configurable `scrollBehavior`

### ISSUE THREAD

**Issue by hecateball** [nuxt/nuxt.js#12732]

**Comment by notflip** [comment]
Issue I'm having with this is when I navigate to another page from a link in the footer, the current page first scrolls to the top, then navigates away. @ricky11 As you're saying. 

Is there a way to make sure this happens after the route change?

**Comment by alexanderhorner** [comment]
Update to the newest version. The new default behavior works as expected.

**Comment by notflip** [comment]
@alexanderhorner The only thing missing now is smooth scroll behaviour for anchor tags, do you know what needs to be edited in the router.options.ts file, to achieve this? Without breaking default page behaviour

**Comment by lazercaveman** [comment]
Have a look here: https://github.com/nuxt/nuxt/issues/22663

**Comment by wadclapp** [comment]
adding `app/router.options.js` to my project didn't work until I restarted dev (maybe this info will help someone)

**Comment by alexanderhorner** [comment]
This isn't necessary anymore. Delete your routers option file and update to the newest version of nuxt.

**Comment by mbyrne00** [comment]
@alexanderhorner - can you please clarify what you meant by "This isn't necessary any more" and about deleting the options file? If we want to customise router options, we still supply that `app/router.options.js` file right?

**Comment by alexanderhorner** [comment]
Sorry, I assumed this was to fix an older issue where nuxt didn't scroll to the top of the page on navigation. The default behavior is now smarter than most work arounds using this config.

If you still want to customize the scroll behavior, this is of course valid.

**Comment by carbdias** [comment]
I've tried everything and I'm not able to remove the scroll to top each we click on a link and we navigate to a page :

<img width="887" alt="image" src="https://github.com/nuxt/nuxt/assets/75072557/8e94d50c-8d9d-4d02-915c-7cd69a0b53e4">


in app.vue :

<img width="323" alt="image" src="https://github.com/nuxt/nuxt/assets/75072557/cadde06c-4932-4e61-9610-3be28ed994ac">
