### ISSUE TITLE
 Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt.js#12735]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27264620.a62351a`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `vite`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

if use navigation browser, pages stop load.. and return this error.

 Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### Reproduction

nuxt page have style

.page-enter-active, .page-leave-active {
  transition: opacity .5s;
}
.page-enter, .page-leave-active {
  opacity: 0;
} 

nuxt link page1, page2 

forward and back 2-3 times

**Comment by deluxenew** [comment]
My problem was that I specified for nuxt-page(:transition="{mode: "out-in", name: "fade"}") (which is acceptable in the official documentation), but I needed pageTransition: { name: "fade", mode: "default" } specify in nuxt.config.js

**Comment by mkdirnow** [comment]
My solution in Nuxt3
```javascript
export default defineNuxtRouteMiddleware((to, from) => {
  ...
  if (to.name === 'write') {
    if (process.client && !localStorage.getItem('token')) {
      location.replace('/')
      return navigateTo('/', {
        replace: true,
      })
    }
  }
})
```

**Comment by oezkancodes** [comment]
For me, this error only happens when I have set the page transition mode to 'out-in' and I change a page again **during a page transition** (switch pages fast).

```ts
export default defineNuxtConfig({
  ssr: false,
  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
  },
  // ...
});
```

```css
.page-enter-active,
.page-leave-active {
  @apply origin-center transition-all duration-150 ease-in-out;
}
.page-leave-to {
  @apply scale-95 opacity-0;
}
.page-enter-from {
  @apply scale-105 opacity-0;
}
```

When I set the page transition mode to 'default', or disable page transitions, the error is gone.

**Comment by hlwen** [comment]
`  <div id="app">
    <router-view v-slot="{ Component }">
      <transition :name="$router.customRouterData.transitionName">
        <component class="component" :is="Component" />
      </transition>
    </router-view>
  </div>`

关键是<div id="app">在最顶层组件必须写，但页面嵌套多层路由时会出现找不到跟节点问题
The key is that the <div id="app"> component must be written at the top level, but the page can't find the node when it is nested with multiple layers of routes

**Comment by hlwen** [comment]
> For me, this error only happens when I have set the page transition mode to 'out-in' and I change a page again **during a page transition** (switch pages fast).
> 
> ```ts
> export default defineNuxtConfig({
>   ssr: false,
>   app: {
>     pageTransition: { name: 'page', mode: 'out-in' },
>   },
>   // ...
> });
> ```
> 
> ```css
> .page-enter-active,
> .page-leave-active {
>   @apply origin-center transition-all duration-150 ease-in-out;
> }
> .page-leave-to {
>   @apply scale-95 opacity-0;
> }
> .page-enter-from {
>   @apply scale-105 opacity-0;
> }
> ```
> 
> When I set the page transition mode to 'default', or disable page transitions, the error is gone.

https://github.com/nuxt/nuxt/issues/12735#issuecomment-1598015192

**Comment by davinma** [comment]
If you use `NuxtLayout` and `NuxtPage` in `app.vue` like this:

```vue
<template>
  <NuxtLayout>
    <NuxtPage :transition="transitions" />
  </NuxtLayout>
</template>
```

You may get error link OP said. Just wrap a `div` outside the `NuxtLayout`, like this:
```vue
<template>
  <div>
    <NuxtLayout>
      <NuxtPage :transition="transitions" />
    </NuxtLayout>
  </div>
</template>
```
The error is gone, and `transitions` will still be effective.

**Comment by homerboy19520** [comment]
> > For me, this error only happens when I have set the page transition mode to 'out-in' and I change a page again **during a page transition** (switch pages fast).
> > ```ts
> > export default defineNuxtConfig({
> >   ssr: false,
> >   app: {
> >     pageTransition: { name: 'page', mode: 'out-in' },
> >   },
> >   // ...
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```css
> > .page-enter-active,
> > .page-leave-active {
> >   @apply origin-center transition-all duration-150 ease-in-out;
> > }
> > .page-leave-to {
> >   @apply scale-95 opacity-0;
> > }
> > .page-enter-from {
> >   @apply scale-105 opacity-0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I set the page transition mode to 'default', or disable page transitions, the error is gone.
> 
> [#12735 (comment)](https://github.com/nuxt/nuxt/issues/12735#issuecomment-1598015192)

+1

**Comment by Disolm** [comment]
need to change from `mode: 'out - in'` to `mode: 'in-out'`

to get  `pageTransition: { name: 'page', mode: 'in-out' },`

**Comment by karombek** [comment]
> i thought the new nuxt version would not need to have a single root element



> If you use `NuxtLayout` and `NuxtPage` in `app.vue` like this:
> 
> ```
> <template>
>   <NuxtLayout>
>     <NuxtPage :transition="transitions" />
>   </NuxtLayout>
> </template>
> ```
> 
> You may get error link OP said. Just wrap a `div` outside the `NuxtLayout`, like this:
> 
> ```
> <template>
>   <div>
>     <NuxtLayout>
>       <NuxtPage :transition="transitions" />
>     </NuxtLayout>
>   </div>
> </template>
> ```
> 
> The error is gone, and `transitions` will still be effective.

in my case, I just turned pageTransitions registered in nuxt config, and then there is no error

**Comment by OssiPesonen** [comment]
I had to switch to using `mode: 'default'` for this error to disappear. If you navigate a static website quickly enough, the content stops rendering and essentially just shows a blank page. Didn't matter if I had a root element in `app.vue` or not.
