### ISSUE TITLE
Undefined body in API Routes

### ISSUE THREAD

**Issue by oritwoen** [nuxt/nuxt.js#12749]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27276275.abfbd2f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.12`

### Describe the bug

The API `~/server/api` does not support body in `POST` requests.

### Reproduction

https://codesandbox.io/s/wonderful-darwin-ew029?file=/app.vue

**Comment by gregg-cbs** [comment]
Nuxt docs are going backwards - I had to re-find this thread to see how to access the req body.
Its not easy to find server/api documentation anymore, its so hidden now.

Please in the docs provide a full example of how to use all the features in an api route. I dont understand why it has to be split across 5 different pages?

Your example [in the docs](https://nuxt.com/docs/guide/directory-structure/server#handling-requests-with-body) is:
![image](https://user-images.githubusercontent.com/57114335/216273097-56cfcb9b-ccad-4678-882c-ce4e429cebe1.png)
^ What is readbody? Where does it come from? Is it global, do i import it? Where do I import it from? And why isnt body parser enabled by default like in nextjs? why did you choose to have to manually import and use a body parser?

sorry for the rant but im having one of those frustrating days :(
