### ISSUE TITLE
Hydration Error at use teleport

### ISSUE THREAD

**Issue by hoiheart** [nuxt/nuxt.js#12766]

**Comment by rijad992** [comment]
I guess this thread is still opened so I'll post here. Basically I'm experiencing nearly the same issue, except my teleport target is not outside of app. My teleport target is basically in parent component.

Anyways, teleport target is subheader component which, with help of teleport renders some action buttons to the header that live inside child components which are rendered conditionally. This im able to achieve decent reusability without so many emits or props being passed around, or having to use some kind of store.
We are running nuxt 3.3.1 with composition api, script setup and ts.

In addition to error in the original post and ones mentioned later on, I've managed also to get this kind of error message.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/39672277/234314952-be4105f4-127c-452b-b10f-f7b86008f103.png">

**Comment by danielroe** [comment]
In future, I'd recommend opening a new issue - this isn't the same issue.

However, for a quick fix, you should only teleport _outside_ of your Vue app.

> The teleport to target must be already in the DOM when the `<Teleport>` component is mounted. Ideally, this should be an element outside the entire Vue application. If targeting another element rendered by Vue, you need to make sure that element is mounted before the `<Teleport>`.
> https://vuejs.org/guide/built-ins/teleport.html#basic-usage

**Comment by rijad992** [comment]
> 

Thx, for fast reply. Im certain, that target mounts before <Teleport>. Anyways, I will open new issue with more detailed snippet.
