### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by pixelpaulaus** [nuxt/nuxt.js#12797]

**Comment by Umer-Farooq10** [comment]
For dynamic images use this, it works in nuxt 3. 
Define the path as I did.

```vue
<template>
  <div class="app">
    <img :src="`/_nuxt/assets/images/${img.src}`" alt="image"/>
  </div>
</template>

export default {
  data() {
    return {
      img: { 
        src: 'img.png' 
      }
    }
  }
}
```
Note: define your directory properly, my image are saved in images folder.

It work for me :)

**Comment by kissu** [comment]
> For dynamic images use this, it works in nuxt 3. Define the path as I did.
> 
> ```
> <template>
>   <div class="app">
>     <img :src="`/_nuxt/assets/images/${img.src}`" alt="image"/>
>   </div>
> </template>
> 
> export default {
>   data() {
>     return {
>       img: { 
>         src: 'img.png' 
>       }
>     }
>   }
> }
> ```
> 
> Note: define your directory properly, my image are saved in images folder.
> 
> It work for me :)

That one is more of a local-dev only thing.
I don't think it would work once pushed to production (since `_nuxt` is used as a local cache).

**Comment by itskush** [comment]
what if im trying to pass an object? like a json to a component's props (which is expecting an object)? 
for example :loaData:require('@/assets/data.json')

**Comment by itskush** [comment]
I manged to get it working via a function in methods

**Comment by leo95batista** [comment]
I have the same problem, what I'm trying to do is something like this: ``` <template>
  <svg class="inline-block overflow-hidden" height="1em" width="1em">
    <use :xlink:href="`~/assets/icons/core.svg#${props.name}`"></use>
  </svg>
</template> ```

but it renders in the DOM as ```<use :xlink:href="~/assets/icons/core.svg#icon1"></use>```

**Comment by GavinJaynes** [comment]
It's ridiculous that it's so complicated to get a dynamic image path in Nuxt. Surely, there's a better way?

Thanks to https://github.com/nuxt/nuxt/issues/12797#issuecomment-1399974816

This seems to work, but I don't like that the path is so fickle (relative) - it would be good if the alias worked:
```const imageUrl = new URL(`~/assets/images/${props.backgroundImageName}`, import.meta.url).href;``` ❌

A working solution in Nuxt 3 using SFC ✅
```vue
<script lang="ts" setup>

const props = defineProps<{
  backgroundImageName: string;
}>()

const getImageSrc = () => {
  try {
    const imageUrl = new URL(`../assets/images/${props.backgroundImageName}`, import.meta.url).href;
    return imageUrl;
  } catch (error) {
    console.error(error);
  }
}
</script>

<template>
      <img :src="getImageSrc()" alt="background image" />
</template>
```

**Comment by hakimov-dev** [comment]
Any news ? Have you guys find solution for that?

**Comment by Kaperskyguru** [comment]
Any solution? Doesn't work in Production with Netlify

**Comment by Kaperskyguru** [comment]
I found a workaround that works for me.

I moved all the images to the `public` folder and used this code.

```
     <img
          class="w-full h-full object-fill"
          :src="`/img/${props.item?.image}`"
          :alt="item?.title"
        />
```

It worked in both `dev` and `prod`

---
I write a lot about Vue 3 and Nuxt 3 at enterprisevue.dev
