### ISSUE TITLE
plugins not working with rc3

### ISSUE THREAD

**Issue by Silve2611** [nuxt/nuxt.js#1281]
i tried to import plugins for my asyncLoad function as follows    
`import api from '~/plugins/api'`

The Problem ist he is trying to load the plugin both client and server side. The code is run in the asyncData method but i can see it is also run on the client side resulting in an error

**Comment by pi0** [comment]
Hi. Please provide more information about your expected and happening contidion. Is `api.js` exporting a function?

**Comment by Silve2611** [comment]
I think the Problem is on my side here. Are plugins provided both client and server side? There is some code i only want to have on my server side but it is also always compiled server-side which results in an error because it is missing some variables like NODE_ENV etc...

**Comment by Silve2611** [comment]
why has this been closed?
