### ISSUE TITLE
router.extendRoutes support in nuxt.config.js for Nuxt 3

### ISSUE THREAD

**Issue by wzdxy** [nuxt/nuxt.js#12823]

**Comment by awacode21** [comment]
> This is how you can do it in Nuxt 3 at the moment (with the `extend:pages` hook):
> 
> ```js
> import { resolve } from 'path'
> import { defineNuxtConfig } from 'nuxt3'
> import { createCommonJS } from 'mlly'
> const { __dirname } = createCommonJS(import.meta.url)
> 
> export default defineNuxtConfig({
>   hooks: {
>     'pages:extend' (pages) {
>       pages.push({
>         name: 'cmsPage',
>         path: '*',
>         file: resolve(__dirname, 'cms/index.vue')
>       })
>     }
>   }
> })
> ```

But this is then only possible on build time right? What about a case where you get your routes from a CMS and they can change through that CMS so need to be updated during runtime?
I am searching for a way in Nuxt 3 to create a list of routes coming from an CMS API response, but not only when application gets build

**Comment by danielroe** [comment]
You might want to check out https://nuxt.com/docs/guide/directory-structure/pages#using-approuteroptions and you can also follow https://github.com/nuxt/nuxt/issues/13467 (it's currently possible but the issue exists to make it easier).

**Comment by awacode21** [comment]
@danielroe thank you so much for you response, this saves me so much headache. i have one question left, the routes within router.options are not typed as async. so we cannot use async await to request routes from cms to return as value for routes, correct?

**Comment by awacode21** [comment]
@danielroe i did not found and async solution with router.options.ts but i am now using a plugin.
