### ISSUE TITLE
nuxt application can not run in ie 11 and 10

### ISSUE THREAD

**Issue by minlingchao1** [nuxt/nuxt.js#1282]
the error is Multiple definitions of a property not allowed in strict mode

**Comment by oo10** [comment]
can not run in ie 11 and 10, are you sure?

**Comment by minlingchao1** [comment]
yes, ie 9 can run ,but in ie10 and ie11 can not run, because the strict mode

**Comment by minlingchao1** [comment]
![ea76658b-e545-4721-bb1d-fa3bfb014c74](https://user-images.githubusercontent.com/9193693/28957103-149addb6-7923-11e7-8d16-99660378416b.png)

**Comment by bernhardw** [comment]
I just had the same issue with following code:
```
<input type="text" placeholder="Name" :placeholder="(index === 0) ? 'Name*' : 'Name'"/>
````
It seems to be the placeholder attribute I have twice. Although not with `class`.
