### ISSUE TITLE
when nuxt restarts, get the error `[unhandledRejection] ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.js#12844]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

When adding a file that results in a restart of Nuxt, we get the following error:

```
Nuxt CLI v3.0.0
                                                                                                                                                 10
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.88.14:3000/

ℹ Vite warmed up in 4ms
✔ Vite server built in 1167ms
✔ Nitro built in 211 ms
ℹ Directory pages/ created. Restarting nuxt...

 ERROR  [unhandledRejection] ENOENT: no such file or directory, open '/playground/.nuxt/dist/server/server.mjs
 ERROR  [unhandledRejection] ENOENT: no such file or directory, open '/playground/.nuxt/dist/server/server.mjs

ℹ Vite warmed up in 2ms
✔ Vite server built in 1046ms
Nuxt CLI v3.0.0
                                                                                                                                                 10
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.88.14:3000/

✔ Nitro built in 118 ms   
```

### Reproduction

```
yarn play
touch playground/pages/index.vue
```

**Comment by ahmetaligul01** [comment]
Hello everyone,
I'm encountering an issue with my Nuxt project. When the application attempts to restart, I get the following errors:

`ERROR Cannot start nuxt: input.replace is not a function
ERROR [unhandledRejection] ENOENT: no such file or directory, open '/Users/.../node_modules/.pnpm/nuxi@3.25.0/node_modules/nuxi/dist/chunks/public/layout/style.css'`

The error seems to be related to file paths not being found during the restart process. I'm using pnpm as my package manager and having issues with the @nuxtjs/i18n module specifically, as seen in the stack trace:

`at normalizeWindowsPath (node_modules/.pnpm/pathe@2.0.3/node_modules/pathe/dist/shared/pathe.M-eThtNZ.mjs:17:16)
at resolveVueI18nConfigInfo (node_modules/.pnpm/@nuxtjs+i18n@9.1.1...)`

I found a similar issue (#12844) on GitHub where users experienced [unhandledRejection] ENOENT: no such file or directory errors during Nuxt restarts, but I'm not sure if the solution applies to my case.

Has anyone encountered this problem with the i18n module or input.replace not being a function?

**Comment by danielroe** [comment]
@ahmetaligul01  this issue was closed four years ago and is not likely the same as your issue. would you open a new issue with a reproduction please? 🙏

**Comment by ahmetaligul01** [comment]
Hi Daniel,

Thank you for your response on my GitHub issue. I really appreciate you
taking the time to look at it.

I've been working with Nuxt for about 3 years now and have been following
your contributions to the ecosystem. I'm currently building a complex
e-commerce application using Nuxt 3, focusing on performance optimization
and implementing server components for better user experience.

I'm especially interested in your work on font optimization and the
improvements coming in Nuxt 4. I've implemented some of the approaches you
mentioned in your "Magically optimising your fonts" talk, and it's made a
significant difference in our Core Web Vitals.

Would you be open to a brief chat sometime about some challenges I'm facing
with SSR hydration in our dynamic product pages? I'd value your insights,
and I'd also be happy to share our solutions for Nuxt internationalization
that might be useful for others in the community. I can't help but say that
twitch broadcasts were very useful :))

Looking forward to potentially connecting!

Best regards,
Ahmet Ali,
Personel website: ( https://www.ahmetaligul.com )
Phone: +90507 897 1898

Daniel Roe ***@***.***>, 3 May 2025 Cmt, 16:56 tarihinde şunu
yazdı:
