### ISSUE TITLE
RSS feed and sitemap

### ISSUE THREAD

**Issue by EmmanuelBeziat** [nuxt/nuxt.js#1285]
Hi,

I was wondering how static files like rss  feeds (atom.xml) and sitemap could and should be generated?
These are not part of the App, but are built using its datas…

On old versions of my website, I was just creating a js file to be called on webpack build:

- [The config with Feed and Sitemap functions](https://github.com/EmmanuelBeziat/emmanuelbeziat/blob/vuejs-1/build/webpack.prod.conf.js)
- [The js script that's called on build](https://github.com/EmmanuelBeziat/emmanuelbeziat/blob/vuejs-1/plugin/sitemap-plugin.js)
- [And the Template](https://github.com/EmmanuelBeziat/emmanuelbeziat/blob/vuejs-1/sitemap.ejs)

That worked, but now I want to add this in my nuxt website; and I don't really find out what would be the more… "nuxt-ish" way to achieve this?

Shall I "just" put the scripts in the `middleware` folder, call them in `nuxt.config.js` the same way I did in the webpack config ? I feel like that'd be very poorly implemented.

Thanks for any advice.

**Comment by pi0** [comment]
Hi. A super useful [site map module](https://github.com/nuxt-community/modules/tree/master/modules/sitemap) for Nuxt.js is already developed by @NicoPennec so you can add it as a drop-in to your project.

For atom feed I think there isn't any special integration with Nuxt, it just has to serve `/atom.xml` with a [serverMiddleware](https://github.com/nuxt/docs/blob/1.0/en/api/configuration-servermiddleware.md) to do its DB fetch and atom feed generation logic. Please let us know if you have better ideas for feed integration :)

**Comment by EmmanuelBeziat** [comment]
Perfect, I'll try this module, I hope I can get it to work with async routes like I do in generate part:

```javascript
generate: {
	async routes () {
		const blogs = await axios.get('https://rest.emmanuelbeziat.com/posts')
		const portfolios = await axios.get('https://rest.emmanuelbeziat.com/portfolio')
		const b_slugs = blogs.data.map(post => `/blog/${post.slug}`)
		const p_slugs = portfolios.data.map(portfolio => `/portfolio/${portfolio.slug}`)

		return [...b_slugs, ...p_slugs]
	}
},
```

I didn't found this community group, this is awesome. Thanks!
