### ISSUE TITLE
scrollToTop or saveBehavior not work when use 100vh height=100% in layout 

### ISSUE THREAD

**Issue by zppro** [nuxt/nuxt.js#1286]
my layout 
default.vue
```
<template lang="pug">
  div
    topbar
    headbar
    channel-nav
    .container.nuxt-page-wrapper
      nuxt
    footbar
</template>
```
and 
```
layout.styl
.nuxt-page-wrapper
      min-height 100vh
```
I use scrollToTop in page it's not work
```
export default {
    scrollToTop: true,
    mounted () {
      window.scrollTo(0, 0)
    }
  }

```
and my nuxt.config.js also not work
```
module.exports = {
  ...
  router: {
    scrollBehavior: function (to, from, savedPosition) {
      return false
    }
  },
  ...
}
```
what's going on?

**Comment by VadiForte** [comment]
Im not sure what you intend to do, But how it will work? because you start `window.scrollTo(0, 0)` at the first mounted that mean you already on the top of screen, where the script suppose to scroll to?

Can you try to do in Action to make sure that you code really work?

**Comment by alexchopin** [comment]
Hi, this is not releated to nuxt source code. I recommend you to post on our gitter to get help from the community.
