### ISSUE TITLE
useAsyncData does not pass errors from server to client-side 

### ISSUE THREAD

**Issue by nndnha** [nuxt/nuxt.js#12885]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27294839.7e5e50b`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`

### Reproduction

https://stackblitz.com/edit/github-ygz9df?file=app.vue

### Describe the bug

On server side the error content is rendered  as expected while the client side says it's null.

**Comment by manuel-84** [comment]
anyone getting how to solve the same issue with onRequestError ?
seems there is no way to get response status with this handler, for example when the server return a 401
