### ISSUE TITLE
Improve nuxt.config.js interface

### ISSUE THREAD

**Issue by Zip753** [nuxt/nuxt.js#1288]
Hi!
Nuxt.js has been an amazing tool for me, serving tons of config up-front while allowing to customize stuff the way I need. However, what's been an issue for me is the API to extend the config in `nuxt.config.js` file. The main issue is that user has to modify existing config object.

While it's arguable that it may not be the best practice and the code looks more imperative rather than declarative, the big downside for me is that I can't use the power of [`webpack-merge`](https://github.com/survivejs/webpack-merge) to extend the default config with custom one (the reason being that reassigning function arguments has no effect). To give you an example, [`backpack`](https://github.com/palmerhq/backpack) has very similar config extension strategy, but instead of modifying the existing config you just have to return a new one, then extending the webpack config becomes as easy as this:
```javascript
webpack: (defaultConfig, options, webpack) => {
  return merge(defaultConfig, customConfig)
}
```

I propose that the API for extending config is changed, so that [`extend`](https://nuxtjs.org/api/configuration-build#extend) and [`extendRoutes`](https://nuxtjs.org/api/configuration-router#extendroutes) methods have to return the new config object instead of modifying the existing one.

**Comment by Atinux** [comment]
Hi @Zip753 

Thank you for using Nuxt.js, I really like Monterail :)

It's a good idea indeed, feel free to make your first PR to implement it, it should be pretty straightforward.

**Comment by Zip753** [comment]
Thanks @Atinux, we love Nuxt.js too! :)

I've created a PR, let me know in case backwards compatibility requires any further testing.
