### ISSUE TITLE
Cannot transition child routes

### ISSUE THREAD

**Issue by samturrell** [nuxt/nuxt.js#1289]
Nuxt Version: 1.0.0-rc3

## Issue

Cannot transition child routes.

## Current behaviour

Take the following pages structure:

```
/index.vue
/contact.vue
/contact/index.vue
/contact/step1.vue
/contact/step2.vue
```

In `contact.vue` we have a `<nuxt-child/>` component to pull in nested route components. When navigating between the nested routes (`/contact`, `/contact/step1` and `/contact/step2`) the parent component `contact.vue` transitions the whole content using the default `page` transition. 

## Expected Behaviour

When navigating between nested routes, only the `<nuxt-child/>` component content should transition. It should also transition with its own transition setting rather than the default `page` transition.

## Reproduction Repo

https://github.com/samturrell/nuxt-nested-routes

## Comments

I feel like it's very possible that i am doing something wrong here, but I can't get it to work no matter how hard i try. The strange thing is when HMR kicks in it transitions the nested route component properly, but it never works when navigating via vue

**Comment by PrimozRome** [comment]
I have the same problem over here with my setup...

**Comment by alexchopin** [comment]
Should be fixed with the last release, feell free to comment or reopen it if the bug persists.
