### ISSUE TITLE
Response status code is not 404 but 200 with custom pages/404.vue

### ISSUE THREAD

**Issue by levchak0910** [nuxt/nuxt.js#12913]

**Comment by zeelrupapara** [comment]
I think this solution might be helpful because it works for me in vue2:
##### Create layout  (ex: `layouts/error.vue`)
```javascript
<template>
  <div class="mt-5">
    <div>
      <h4 v-if="error.statusCode.toString().startsWith('4')">Page not found</h4>
      <h4 v-if="error.statusCode.toString().startsWith('5')">Oops, something went wrong</h4>
    </div>
    <div class="mt-3">
      <button to="/">Back to Home</button>
    </div>
  </div>
</template>
<script>
export default {
  props: {
    error: {
      type: Object,
      required: true,
    },
  },
}
</script>
```

**Comment by agracia-foticos** [comment]
same issue

**Comment by jay8t6** [comment]
@danielroe  this is reintroduced in Nuxt 3 it looks like. Check this link for reproduction: https://nuxt3-awesome-starter.vercel.app/sdfdsf, that page does not exist, it throws a 200 eventhough the UI is handling the 404 scenario. I tried this on the nuxt website, it works correctly. https://nuxt.com/blah

**Comment by danielroe** [comment]
@jay8t6 Would you be able to open a new issue with a reproduction, please? 🙏

**Comment by jay8t6** [comment]
@danielroe Here you go: https://github.com/nuxt/nuxt/issues/26915
