### ISSUE TITLE
how can i customize error.html

### ISSUE THREAD

**Issue by JermeyYann** [nuxt/nuxt.js#1291]
Is there a way to customize [error.html ](https://github.com/nuxt/nuxt.js/blob/e5eea39e917d1e5ce7c1592db6eef9be88159f5e/lib/app/views/error.html)?

**Comment by cawa-93** [comment]
https://nuxtjs.org/guide/views/#error-page

**Comment by JermeyYann** [comment]
@cawa-93 I want to customize [error.html ](https://github.com/nuxt/nuxt.js/blob/e5eea39e917d1e5ce7c1592db6eef9be88159f5e/lib/app/views/error.html) , not [nuxt-error.vue](https://github.com/nuxt/nuxt.js/blob/master/lib/app/components/nuxt-error.vue)

**Comment by pi0** [comment]
Hi. You can create `app/views/error.html` and rebuild Nuxt project to customize that template :) Generally, all templates are customizable this way.
PS: A brand new sexy error design is coming with `rc4` keep it secret ;)

**Comment by langgo** [comment]
Should add it to the document ?

**Comment by langgo** [comment]
Should unify the error handling 
The `error.html` and `nuxt-error.vue`
