### ISSUE TITLE
Support for ES2015 Modules

### ISSUE THREAD

**Issue by jhabdas** [nuxt/nuxt.js#1293]
Thanks for producing such a popular tool. After looking over the README I noticed Node may be required to run this server-side. If a pure browser engine is running on the server is it possible to leverage this tool to take advantage of ESM? I realize there many not be a simple answer to this question. But maybe there is, and that's why I ask.

**Comment by pi0** [comment]
Hi. We are using vue-server-renderer for SSR which requires Node runtime.

> If a pure browser engine is running on the server  

Would you please explain more about this? You mean something like chrome-headless?

> leverage this tool to take advantage of ESM

Webpack builds of Nuxt are fully compatible with esm modules and tree-shaking.

**Comment by jhabdas** [comment]
Hi right back at'cha. Thanks for the quick reply. Chrome Headless, yes. Given Node doesn't support ESM I'd rather take a standards-based approach to app dev. I've been following ESM advancements in Node for a few months and haven't seen many advancements in the module space as a result of what I believe may be architectural complexities. If no ESM outside client I don't see a strong advantage to SSR unless using headless browser. But that's just me. Now a Webpack user. I'm XP.
