### ISSUE TITLE
Slowness when compiling

### ISSUE THREAD

**Issue by tiagomatosweb** [nuxt/nuxt.js#1294]
Hi,
I've been testing the nuxt for this week. I've created a simple page with background and some texts just to test it. I've found the compiling process too slow. So, I've created the same project using vue webpack template, below are the results.

Using nuxt with the starter template
DONE  Compiled successfully in 8307ms 

Using vue webpack template
DONE  Compiled successfully in 1068ms  

As you can see, it is 8 times slower.

Does anyone know why I'm getting this. Does anyone also get similar results? What I could do to speed it up?

Cheers

**Comment by bayssmekanique** [comment]
Could you link to the Vue webpack template you are referencing?

**Comment by tiagomatosweb** [comment]
@bayssmekanique 
https://github.com/vuejs-templates/webpack

**Comment by pi0** [comment]
Hi @tiagomatosweb .  Normally Nuxt builds shouldn't be WAY slower than starter templates. Also consider that we are comparing a bare-bone project with a fully optimized and production ready one. Nuxt has just made all that interface simpler. Also, we have a two phase webpack build for both SSR and Client bundles while that webpack has one phase for client-only.

For a fair comparison of Nuxt and a Similar full featured project, we may test [vue-hackernews-2](https://github.com/vuejs/vue-hackernews-2.0) which takes ~ `Time: 9757ms` for SSR + `Time: 3991ms` for Client. (Nuxt uses parallel builds so is little faster)

**Comment by tiagomatosweb** [comment]
Fair enough! Tks for the explanation.

**Comment by joannesalfa** [comment]
Is there a way to switch as REAL development mode? I don't think this current update is productive, it's very slow and buggy to be honest.

**Comment by phuochau** [comment]
I have some problem, nuxt.js building is really really slow. We need to find a solution to optimize it

**Comment by vipulbhavsar94** [comment]
I have same problem, nuxt.js building is really really slow. We need to find a solution to optimize it +1

**Comment by joannesalfa** [comment]
Guys, look at this

https://parceljs.org/

Maybe it’s worth to try it out

**Comment by saintplay** [comment]
I think the slowness is related to the size of the `template` part.

For example:

- 280 lines of pure static HTML inside a `template` compiles in almost 10 seconds for me.
- Once compiled, it starts to compile in less than a second. (webpack cache maybe?)
