### ISSUE TITLE
Link to embedded video

### ISSUE THREAD

**Issue by janhox** [nuxt/nuxt.js#1295]
on my landing page I want to autoplay mp4 that is in my assets folder.
~assets or ~/assets result in 404. If I use hosted version then works fine (eg. http://vjs.zencdn.net/v/oceans.mp4)

What am I missing here ?
Thanks
<img width="1258" alt="screen shot 2017-08-05 at 09 34 02" src="https://user-images.githubusercontent.com/24571106/28993896-4d701f90-79c1-11e7-85db-f20baf5253b6.png">

**Comment by janhox** [comment]
<img width="512" alt="screen shot 2017-08-05 at 09 35 15" src="https://user-images.githubusercontent.com/24571106/28993908-6be74232-79c1-11e7-8d27-26a0e2974e83.png">

**Comment by janhox** [comment]
I swapped the loader for the build extend config option to add url-loader for mp4. That works ok.

**Comment by yl33643** [comment]
could you show your solution code please? I have meet the same issue

**Comment by janhox** [comment]
<img width="598" alt="screen shot 2017-09-01 at 05 36 55" src="https://user-images.githubusercontent.com/24571106/29954376-bdb5e2d2-8ed7-11e7-8caf-63c2cf81ca69.png">

**Comment by janhox** [comment]
Hi, I used the extend option to load video & source attributes from nuxt.config.js.
Then my above code to display embedded video works fine.
