### ISSUE TITLE
Warning: postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext.

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1296]
>* Warning: postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext.
>* Note: If, for a really specific reason, postcss-cssnext warnings are irrelevant for your use case, and you really know what you are doing, you can disable this warnings by setting  'warnForDuplicates' option of postcss-cssnext to 'false'.

![image](https://user-images.githubusercontent.com/17898715/28993974-708badee-79f5-11e7-8666-c49d0814117f.png)
![image](https://user-images.githubusercontent.com/17898715/28993978-8e89f2ec-79f5-11e7-92a2-103b656fa4b4.png)
![image](https://user-images.githubusercontent.com/17898715/28993963-3eff880e-79f5-11e7-9c10-89b27b1ecc92.png)

**Comment by pi0** [comment]
With next release (ETA is not known now) you can disable autoprefixer using:
```js
build: {
 autoprefixer: false
}
```
