### ISSUE TITLE
Alias in style attribute doesn't work rc3

### ISSUE THREAD

**Issue by vadimsg** [nuxt/nuxt.js#1297]
```
// Doesn't work
style="background-image: url('~static/image.png')" 

// Works
<img src="~static/image.png" />
```

**Comment by c4milo** [comment]
I had a working project using rc2 and suddently rc3 broke it all. 

```
* ~router in ./plugins/ga.js
* ~pages/sign-up.vue in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
* ~components/sign-in in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/sign-in.vue
* ~components/sign-up in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/sign-up.vue
* ~components/sign-up-blurb in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/sign-up.vue
* ~components/password-reset in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/password/reset.vue
* ~components/password-update in ./node_modules/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/password/reset.vue

To install them, you can run: npm install --save ~router ~pages/sign-up.vue ~components/sign-in ~components/sign-up ~components/sign-up-blurb ~components/password-reset ~components/password-update
```

**Comment by c4milo** [comment]
I was able to fix most of them by adding a `/` after `~` when importing, like so: 
`~/pages/sign-up.vue`. However, I still can't figure out the following missing dep:

```
This dependency was not found:

* ~router in ./src/plugins/ga.js
```

**Comment by vadimsg** [comment]
@c4milo I was not talking about component import but asset import in template with in style attribute.

**Comment by jamilabreu** [comment]
Similarly, I'm seeing that this works:

`<img src="~assets/logo.png">`

while

`import Hello from '~components/Hello';`

throws an error.

**Comment by jamilabreu** [comment]
Code says `<img src="~/assets/nuxt.png" />` should work, but it doesn't (on ^1.0.0-rc4) `<img src="~/assets/nuxt.png" />` is working for me

https://github.com/nuxt/nuxt.js/blob/1f4dfa5f4485e00263fdaf1e83a3b1db438030fa/lib/builder/webpack/base.config.js#L52

**Comment by pi0** [comment]
Hi. Aliases have been changed to `~/assets` style. The only remaining one is using inside `url()` which should be currently possible using `~assets/`. But will be possible to use `url(~/asset..` in next rc release of nuxt :) Feel free to reopen if further helps is needed after rc5.

**Comment by jazoom** [comment]
I just installed the official starter project and got this error. I couldn't figure out why the starter project would not work due to a basic alias... until I found this issue.

**Comment by KimJongTaek** [comment]
Try this!
:style="{ 'background-image': `url(${require('~/assets/image.jpg')})` }"

**Comment by jihyeoh** [comment]
Try this!
<div :style="{ 'background-image': `url(${require('~/assets/img/branch-sample.jpg')})` }"></div>
