### ISSUE TITLE
how to catch nuxt error like this

### ISSUE THREAD

**Issue by lemonpigpig** [nuxt/nuxt.js#1298]
#<img width="1278" alt="2017-08-05 7 59 24" src="https://user-images.githubusercontent.com/17818782/28995314-a8868cd2-7a18-11e7-89cf-a37613bc4a43.png">
first i do not know why have such error really , it look like a timeout, i guess may a error at nuxt server render, is right ? 
second there a way to catch such error and show a my own friendly page , need help thx

**Comment by awronski** [comment]
I do this in `catch`, something like this.

```js
    fetch ({ store, params, error }) {

      const {lessonId, page = 0, keywords = 0 } = params

      return store.dispatch('changePageTo', { page, keywords })
        .then(store.dispatch('changeLessonTo', lessonId))
        .catch(function (reason) {
          error({ statusCode: 500, message: reason })
        })
    },
```

**Comment by shyamchandranmec** [comment]
@pi0  I think there should be a way to handle this globally. Adding this in all the pages is a redundancy. 
Is there a way to forward any such unexpected errors to custom error page?

**Comment by awronski** [comment]
@pi0 could we do something to handle it in axios-module? Maybe some default interceptor with option to overwrite its behavior.

What do you think?

**Comment by pi0** [comment]
Hi. If you take a look at new axios module docs, we now have an option to specify error page for specific error codes (possibly for timeouts too) ([more](https://github.com/nuxt-community/axios-module#redirecterror)).@awronski If you think that won't fit for all cases, whats your idea adding another option like `requestInterceptor` but for `responseInterceptor`?

**Comment by shyamchandranmec** [comment]
Hi 
I don't think handling it in axios is the right way. 
Axios  will be used for other ajax calls along with api calls for ssr. So showing an error page by adding an interceptor in axios might raise other issues. We will have to differentiate between normal api calls and api calls used in fetch() or asyncData() methods.

**Comment by shyamchandranmec** [comment]
@awronski  I am able to catch the server side error by using axios response interceptors.
Right now I am handling this by using a try {} catch {} block and throwing the error to the asyncData and fetch functions. This will show the default error layout page whenever there is an error

But this looks like a redundant code. 
We might need to add some new functionality in nuxt.js to generalise this.

**Comment by pi0** [comment]
Custom error handler is now possible with axios module version `4.0.0` 🎉 

https://github.com/nuxt-community/axios-module#errorhandler

**Comment by awronski** [comment]
@pi0 is it possible to get nuxt context inside `errorHandler` ?

**Comment by pi0** [comment]
@awronski . Sure (`this` is the context!)

**Comment by iamdubx** [comment]
@awronski God bless you! :smile:
