### ISSUE TITLE
Allow usage of CSS preprecessors

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#13]
Not sure the best way to implement this, but just like in a normal Vue app, we should be able to do:

```vue
<style lang="sass">
@import './defaults.scss'

body
  color: $color-primary
</style>
```

But as expected, the build fails because of no webpack `sass-loader`

**Comment by Atinux** [comment]
It works but nuxt.js does not pre-install `sass-loader`.

Make sure to install the sass loader with:
```bash
npm install sass-loader node-sass
```

**Comment by jaredreich** [comment]
Amazing! Though this may be README worthy for others as it's a pretty common use for Vue.

👍

**Comment by Atinux** [comment]
Everything will be in the documentation website, we're working on it to make it as great as Vue.js doc website :)

But we did not expect people to embrace nuxt.js so fast!

**Comment by jaredreich** [comment]
Great to hear. Kudos my friend. You've done a great job and it fits the same need as next.js but satisfies the Vue lovers, which is awesome 😉

**Comment by Atinux** [comment]
Thank you, I'm glad you like it :)
