### ISSUE TITLE
How do I use the koa template 'asyncData' request to get the session

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#1301]
![2017-08-06_093741](https://user-images.githubusercontent.com/19583816/28999858-dd9ee6e0-7a8a-11e7-8014-b84b227b7f20.jpg)
this is code.How do I use the koa template 'asyncData' request to get the session .When I directly refresh the current page, the request in asyncData does not get the session, if it is other life cycle or other pages jump to this page, please help me @pi0 @Atinux

**Comment by Atinux** [comment]
@fengjiel use store with `nuxtServerInit` action, then you can fill your store if your have `req.session` inside it, take a look at https://github.com/nuxt/todomvc/blob/master/store/index.js#L57 to see an example
