### ISSUE TITLE
 __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor

### ISSUE THREAD

**Issue by github1586** [nuxt/nuxt.js#1302]
(node:6425) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor @pi0

**Comment by github1586** [comment]
@pi0  Please help

**Comment by pi0** [comment]
@github1586 Would you please explain more about your error details and usage? (are you using nuxt with express or standalone?)

**Comment by github1586** [comment]
I'm using nuxt, and I'm going to npm install this again today, and that's it @pi0

**Comment by dannydombrowski** [comment]
@github1586 have you found a solution, I'm having the same problem

@pi0 Using expressjs + nuxt

```
nuxt = new __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a(config);

/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_nuxt___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1_nuxt__);

/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_nuxt__ = __webpack_require__(17);

/* 17 */
/***/ (function(module, exports) {

module.exports = require("nuxt");

/***/ }),

```

So it seems, that the error is caused by require("nuxt")(); which is not a constructor

**Comment by pi0** [comment]
But it should work with the latest template of express! 

```bash
vue init nuxt-community/express-template express-nuxt
cd express-nuxt
yarn && yarn dev # It works!
```

If using express-template, would you please update `server/index.js` to this one? 
https://github.com/nuxt-community/express-template/blob/master/template/server/index.js

**Comment by dannydombrowski** [comment]
That does make sense!

It should do the trick, thank you 👍
