### ISSUE TITLE
import my own library

### ISSUE THREAD

**Issue by tiagomatosweb** [nuxt/nuxt.js#1303]
Hi,
I have some js files with functions. I would like to import using build.vendor. How would I do it?
Cheers?

**Comment by XiaoNode** [comment]
in nuxt.config.js, you can add config in build like:
`build:{
  vendor:[
  '~/plugins/a.js' 
]
}`

**Comment by tiagomatosweb** [comment]
That what I did, but the variable is not available, like
`build:{ vendor:[ 'axios' ] }`

Inside of my page
```
mounted() {
            console.log(axios);
        },
```

Got error
ReferenceError: axios is not defined

Do I still need to import axios in the component?

**Comment by KonstantinVlasov** [comment]
> Do I still need to import axios in the component?

Sure you need:
```javascript
import axios from '~/plugins/axios'
```

**Comment by tiagomatosweb** [comment]
So what is the benefit to insert in build.vendor? Didn't get it!

**Comment by KonstantinVlasov** [comment]
to reduce the size of the app bundle
https://nuxtjs.org/api/configuration-build#vendor

**Comment by tiagomatosweb** [comment]
Well, it would be the same if I just import axioes normally as usual? Sorry, got confused with this.
Do you know any article that explains it more?

**Comment by antfu** [comment]
A simplified example:

With `build:{ vendor:[ 'axios' ] }`
```sh
dist/
    nuxt.bundle.hash.js # your app code
    vendor.bundle.hash.js # "axios" bundled in here
    ...other files
```
Without 
```sh
dist/
    nuxt.bundle.hash.js # "axios" bundled with app code
    ...other files
```

The `build.vendor` option is meant for splitting vendor code to another bundle in order to reduce the size of the app bundle.

**Comment by KonstantinVlasov** [comment]
Also, it's useful when you deploy new version of your app, vendor.bundle will be the same (if you don't add new libs) and user don't need to download vendor.bundle again. So only small nuxt.bundle will be downloaded.

**Comment by tiagomatosweb** [comment]
Now makes sense! Thank you very much everyone!
