### ISSUE TITLE
Cloudflare CDN Service (Apps Option) Causes Rendering Twice

### ISSUE THREAD

**Issue by sefacndmr01** [nuxt/nuxt.js#13033]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27324955.23397e6`
- Package Manager:  `npm@7.14.0`
- Bundler:          `Vite`
- User Config:      `nitro`, `app`, `build`, `privateRuntimeConfig`, `alias`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Can't reproduct.

### Describe the bug

When cloudflare cdn service has apps option on, nuxt renders page twice even no apps on open. To solve this problem I need to the add page rules and close apps option.

### Additional context

I think this is caused by the javascript files that cloudflare adds. 

### Logs

```shell
No log
```

**Comment by yktibrahim** [comment]
I have the same problem. Did you find a solution?

**Comment by ChrAlpha** [comment]
> I have the same problem. Did you find a solution?

Cloudflare's [Auto Minify](https://developers.cloudflare.com/speed/optimization/content/auto-minify/) may change the server rendered HTML, turning `HTML` minify off works in my case.

![image](https://github.com/nuxt/nuxt/assets/53332481/e88ccddb-3f89-4d75-b9ef-c91db965f87b)

Also you could add a rules to control specifically

![image](https://github.com/nuxt/nuxt/assets/53332481/e467f29f-589b-48d4-b0fd-d0665a52d4ba)

**Comment by bloor** [comment]
OMG DUDE. Thanks a lot. I know it's in the documentation, but the damn google never showed me that link. Wasted 2 weeks on this issue. For me, some elements acted weirdly, layout was shifting a bit .. some ordering was bad when rendering and <teleport> was acting weird. 
HAVE A WONDERFUL ~~day~~ YEAR !

**Comment by roymckenzie** [comment]
Thanks @ChrAlpha. This resolved my issue with double-loading, too.
