### ISSUE TITLE
NPM run dev can't move up to 64%   NPM run build can't move up to 91%

### ISSUE THREAD

**Issue by github1586** [nuxt/nuxt.js#1304]
@alexchopin@Atinux@pi0
nuxt@v1.0.0-alpha.4

**Comment by pi0** [comment]
Please upgrade to latest release `nuxt@v1.0.0-rc3` and make sure `node_modules` and `.nuxt` are cleaned up.

**Comment by github1586** [comment]
I can't even try it

**Comment by github1586** [comment]
Local can，  That's what it looks like on the cloud server

**Comment by github1586** [comment]
Switch to  V1.0.0-rc3    eer ==》》 __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor

**Comment by pi0** [comment]
https://github.com/nuxt/nuxt.js#using-nuxtjs-programmatically
```
const { Nuxt, Builder } = require('nuxt')
```
I think you need you change require like this.

**Comment by github1586** [comment]
after the change like this (const { Nuxt, Builder } = require('nuxt')) ,

the same  "NPM run dev can't move up to 64% NPM run build can't move up to 91% Killed"

but  Switch to V1.0.0-rc3 Don't tip __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor

**Comment by sergiofilhowz** [comment]
I've had the same problem when I updated.

you have to import Nuxt and Builder

```import { Nuxt, Builder } from 'nuxt'```

and on build, use new Builder

    const nuxt = new Nuxt(config);

    // Build in development
    if (config.dev) {
      const builder = new Builder(nuxt)
      builder.build()
    }
