### ISSUE TITLE
is it possible to run sails & nuxt on a single express instance?

### ISSUE THREAD

**Issue by christophmayrhofer** [nuxt/nuxt.js#1306]
I understand that the intended setup is. Seperate backend server (e.g. Sails, Laravel, ...) plus frontend server with nuxt.js or prerendered static content generated with nuxt and statically hosted (e.g. AWS S3, now, ...)

I am wondering if it is also possible to run sails and nuxt within the same node/express instance.

**Comment by pi0** [comment]
Hi. Actually Nuxt can be used as an middleware too. 
- https://github.com/nuxt/nuxt.js#using-nuxtjs-as-a-middleware
- github.com/nuxt-community/express-template
