### ISSUE TITLE
support injecting single static files into nitro public folder

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.js#13079]

**Comment by imcm7** [comment]
result what for that is needed to alter nitro config some how if I want to add some static files from module or plugin for example?

**Comment by imcm7** [comment]
I added 
```
nitro: {
    serverAssets: [{
      baseName: 'swagger-ui-dist',
      dir: './node_modules/swagger-ui-dist',
    },
```

and no result for `http://localhost:3000/swagger-ui-dist/swagger-ui-bundle.js` or `http://localhost:3000/api/swagger-ui-dist/swagger-ui-bundle.js`

**Comment by imcm7** [comment]
oh, its /assets/bla-bla-bla
