### ISSUE TITLE
How to run no ssr mode?

### ISSUE THREAD

**Issue by jericopulvera** [nuxt/nuxt.js#1308]
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "spa": "nuxt start —mode spa",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  }

I run npm run spa and I get this Error
No build files found, please run `nuxt build` before launching `nuxt start`

Then I run npm run build before npm run spa still gets the same error.
It works when using npm run start without the -mode spa

**Comment by Atinux** [comment]
Hi @jericopulvera 

Actually the `mode` option is not added yet, but you can set the mode in your `nuxt.config.js` in the meantime:

```js
module.exports = {
  mode: 'spa'
}
```
