### ISSUE TITLE
add the local js file in the 'script' of the 'head' option in nuxt.config.js

### ISSUE THREAD

**Issue by XiaoNode** [nuxt/nuxt.js#1309]
I would like to add the local js file in the 'script' of the 'head' option in nuxt.config.js, src: '~ / plugins / a.js' and try './plugins/a.js' Of the wording, has been prompted to find the file, if it is a reference to a complete CDN address can be, how can I quote the local documents here?

**Comment by pimlie** [comment]
As I am not sure what you mean, can you maybe add some example code that shows your issue?
