### ISSUE TITLE
specify the transition of <nuxt /> subcomponent in layout

### ISSUE THREAD

**Issue by zzhjerry** [nuxt/nuxt.js#1311]
I know we can do transition by defining `.page-*` classes and also do custom transition per component. But I want to be able to specify the same transition for every <nuxt /> subcomponent. 

May I know what's the suggested way to do it? I couldn't find a clue after looking around and some experiments.

**Comment by piyushchauhan2011** [comment]
@zzhjerry  I generally take this example as reference https://github.com/nuxt/hackernews/blob/master/components/ItemList.vue . I'll also suggest the demos in Vue docs are pretty.

If an animation is complex, create a wrapper components like `<animated-item>` for different type of animations and just compose them together. It's easy to import and wrap things around. Even Vue migration guide suggested this approach moving from Vue 1 to Vue 2 https://vuejs.org/v2/guide/migration.html#Vue-transition-for-Reusable-Transitions-replaced
