### ISSUE TITLE
Page transition glitch when page tags are different (1.0.0-rc3)

### ISSUE THREAD

**Issue by mkv27** [nuxt/nuxt.js#1314]
When there is a difference between the tags, both pages are displayed at the same time and then a glitch is produced.

On transition with difference (by scoped style):
```vue
<div id="__nuxt">
    <div class="container" data-v-edeb123a class="page-leave-active page-leave-to">
        Page A
    </div>
    <div class="container" data-v-qazw987c >
       Page B
    </div>
</div>
```
On transition with no difference:
```vue
<div id="__nuxt">
    <div class="container" class="page-leave-active page-leave-to">
        Page A to page B
    </div>
</div>
```

**Comment by Atinux** [comment]
Hi @mkv27 

Can you create a reproduction repository so we can investigate into this issue please?

Please re-open it with a repo link or a glitch link (by forking https://glitch.com/edit/#!/nuxt-hello-world)

Thank you :)

**Comment by mkv27** [comment]
Hi @Atinux,

I reproduce it here (only happen with different layouts)
https://glitch.com/edit/#!/nuxt-transition-test

Thanks for the time !

**Comment by alexchopin** [comment]
Hi, should be fixed with the last release. Feel free to reopen it if the bug persists.
