### ISSUE TITLE
Can't make svg-inline-loader work

### ISSUE THREAD

**Issue by tsimenis** [nuxt/nuxt.js#1315]
I know this has been asked before but no matter what I try I can't seem to make it work. 
I want to use a component that will render my svg icons inline.

This is my nuxt.config.js
```
build: {
    /*
    ** Run ESLINT on save
    */
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
            enforce: 'pre',
            test: /\.(js|vue)$/,
            loader: 'eslint-loader',
            exclude: /(node_modules)/
          },
          {
            test: /\.svg$/,
            include: /assets\/svg/,
            use: [
              {
                loader: 'svg-inline-loader'
              }
            ]
          },
          {
            test: /\.(png|jpe?g|gif)$/,
            loader: 'url-loader',
            exclude: /assets\/svg/,
            query: {
              limit: 1000, // 1KO
              name: 'img/[name].[hash:7].[ext]'
            }
          })
      }
    },
  }
```

and this is my component: 

```
<template>
  <div>
  <span :class="'icon-' + name" class="icon" v-html="url"></span>
  </div>
</template>

<script>
  export default {
    props: ['name'],
    computed: {
      url () {
        return require(`~/assets/svg/${this.name}.svg`)
      }
    }
  }
</script>
```
And this is what gets rendered:
<img width="452" alt="screenshot 2017-08-07 21 15 42" src="https://user-images.githubusercontent.com/5978397/29042046-a2b7b058-7bb5-11e7-9ba9-e0d33b5e7016.png">

**Comment by KonstantinVlasov** [comment]
Hi, @tsimenis!

url-loader already defined in webpack config, thats why you can't just push new rule for url-loader, but you can change test property:
```javascript
const urlLoader = config.module.rules.find((loader) => loader.loader === 'url-loader')
urlLoader.test = /\.(png|jpe?g|gif)$/
```

**Comment by tsimenis** [comment]
Hi @KonstantinVlasov!
that works great!

I got confused because in the documentation it says that loaders get overridden that I totally missed the fact that this is extending and not replacing. 
I am going to close this down but last thing:

Is this the best way to do this?

**Comment by KonstantinVlasov** [comment]
I think so, it's a rare case when you need to change already defined rule. Most cases can be resolved just by push

**Comment by tsimenis** [comment]
ok makes sense, although I would think there should be a better way to merge loaders.

**Comment by osudio-erik** [comment]
I've created a full example project with svg-inline-loader: https://github.com/osudio-erik/svg-icons

**Comment by rayfranco** [comment]
Just went through this and did not find the solution I wanted right away (although I learn from @osudio-erik we can do `v-html="require(...)"`)

[Here is how I do](https://gist.github.com/rayfranco/b97c0450e8ed699e7775d7aa6d170553) on my current project if it can help anyone.

**Comment by elcferreira** [comment]
@rayfranco it works.
Thank you a lot.
