### ISSUE TITLE
Easy to start a 1.0.0-rc4 version of the first to give us debugging interface?

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1316]
Easy to start a 1.0.0-rc4 version of the first to give us debugging interface?
Because the change is still a bit more

**Comment by alexchopin** [comment]
Can you explain more?

**Comment by yuchonghua** [comment]
I would like to be able to install the project through npm install, and then adjust my nuxt.config.js and modify the ~/assets directory, while modifying the error layout page, next.css config and more

**Comment by yuchonghua** [comment]
\ @alexchopin
