### ISSUE TITLE
roadmap?

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#132]
As this project is becoming more and amazing, it will be great to set/evolve the vision. I would suggest adding roadmap to see what we can expect for 1.0 and even beyond.

I have already seen references for 

- Middleware (v1.0)
- PWA
- Apollo/GraphQL  integration
- Typescript support
- Websocket support
- java via Nashorn (separate project)
- auth modules for various auth providers inc oauth support ( [passport.js ?](http://passportjs.org/) )
- integration patterns with more services
- direct deploy to number of clouds (Aws, Google Cloud)
- Analytics plugins
- patterns library
- Nuxt api

Probably I missed a lot. But even if some of these could be implemented, it would be fantastic.

Also, I am sure with community effort even wider and more exciting vision can be built and a roadmap could be published for realising that vision.

So let's add version history and roadmap.

Thanks

**Comment by husayt** [comment]
I have just seen this https://github.com/nuxt/nuxt.js/projects  
So pretty much roadmap.md can be like this:

## 0.9.6
* Store generation

## 0.9.7
* Internationalization
* Middleware
* Guard pages

## 0.9.8
* nuxt.api
* gzip support

## 1.0
?

## 1.5
??

## 2.0
??

**Comment by alexchopin** [comment]
Hi, 
The roadmap is made here: [https://github.com/nuxt/nuxt.js/projects](https://github.com/nuxt/nuxt.js/projects).
I don't see why we should put the same things in a markdown file in addition?

**Comment by husayt** [comment]
I actually found it only after making that post and that is great. But I
still think the page will be good. Because what you are referring to is
more a kanban board/backlog than roadmap.

Roadmap will contain a higher level features and also help to establish the
longer term vision. It could be next to release notes page and also have
the link to the kanban board you mentioned.

But again this is a small thing and it may be just me being too pedantic.

Thanks for excellent library.


On 15 Jan 2017 08:36, "Alexandre Chopin" <notifications@github.com> wrote:

Closed #132 <https://github.com/nuxt/nuxt.js/issues/132>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nuxt/nuxt.js/issues/132#event-923434022>, or mute the
thread

**Comment by Atinux** [comment]
Hi @husayt 

The kanban board from Github works really great for us, we will add the link in the README for people to see what's planned for nuxt.js.

Thank you very much for your enthusiasm and motivation for nuxt.js!
