### ISSUE TITLE
Make vue-svgicon work correctly with Nuxt

### ISSUE THREAD

**Issue by gtso86** [nuxt/nuxt.js#1320]
Hello everyone,

I started play around  this weekend with Nuxt and so far all problems I solved reading old tickets or mixing the 0.10 doc with so gists and questions around the web.

My last problem is make [vue-svgicon](https://mmf-fe.github.io/vue-svgicon/) works properly with Nuxt.

The first problem I got is if I don't add inside my **nuxt.config.js** `ssr: false` and/or `mode: pwa` I get the pink screen of dead (lol) with this error:
> maximum calls stack size exceeded

To workaround since for now I don't need SSR rendering I disabled both functions (but in the future will be awesome make work with SSR too).

After that, all compiles correctly BUT the component doesn't work. I believe is related how Nuxt storage the assets / how I import all created svg assets.

Anybody already used this component inside Nuxt projects? BTW: I'm using Nuxt Express template

Thanks in advance,

**Comment by gtso86** [comment]
Since this is project a commercial project I could try split the code and see if I can commit in a public repository to share here..

**Comment by gtso86** [comment]
My bad, I didn't payed attention to import correctly the files...

**Comment by markbranly** [comment]
Do you mind elaborating?

**Comment by gtso86** [comment]
Hey @markbranly, at the time I was using RC3 version (pink error screen) and I didn't paid attention to my svg converted to a .js file.

Anyways, seem something still not working right as I wrote [here](https://github.com/nuxt/nuxt.js/issues/1405#issuecomment-323170650).

In the end my first problem loading the svg was my fault but now seems something related with the vue-svgicon itself at least to generate static files
