### ISSUE TITLE
nuxt (is) building indicator

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#1321]
I searched the source code for this but I cant seem to find anything. I am looking for an indicator that tells me whether nuxt is being built or not. [My](https://github.com/pimlie/nuxt-rfg-icon) nuxt plugin checks when used whether favicons have been set and if not it retrieves them. This process only needs to run during `nuxt build` and can be skipped during `nuxt start` as the plugin either adds the favicon as assets to the webpack configuration or extracts them to the static folder. 

At the moment my plugin is also called during `nuxt start` which just isnt usefull.

**Comment by pi0** [comment]
Hi. An enhancement is being stable with `rc4` which we can use tappable hooks for all lifecycle events of nuxt. So, for example, you can just make favicons after build.

**Comment by pi0** [comment]
If interested to beta test, this (not released) docs would help you:

https://github.com/nuxt/docs/blob/1.0/en/guide/modules.md
https://github.com/nuxt/docs/blob/1.0/en/api/internals.md
https://github.com/nuxt/docs/blob/1.0/en/api/internals-builder.md

**Comment by pimlie** [comment]
Thanks for the quick response, looks as a good solution! Will give it a try and report back if I run into issues

**Comment by pimlie** [comment]
@pi0 fyi, I managed to use tappable plugins for this. It works great and was really easy to adapt as I just had to wrap everything in a 'build' plugin method. I could probably optimize the implementation a bit more now but I will leave that for a later version. Thanks again!

**Comment by tmorehouse** [comment]
Note `tappable` has been deprecated in Node.
