### ISSUE TITLE
Shallow routing

### ISSUE THREAD

**Issue by SabatinoMasala** [nuxt/nuxt.js#1322]
Is it possible to perform shallow routing using Nuxt? Basically change the URL **without** calling the data method again. The [release of 0.9.1](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.1) has the following feature:
> Improve the call to data() when staying in the same view but the query changed.

Is there a way to just keep the default vue-router behaviour and not call data when navigating but staying in the same view?

Next.js [has a feature called 'Shallow routing'](https://github.com/zeit/next.js#shallow-routing) which does exactly this.

**Comment by Atinux** [comment]
Hi @SabatinoMasala 

You can do it inside `asyncData` method, you can receive `from` in the context, check `from` if it's the same component and returns an empty object (will not overwrite the actual data of the component).

Example:
`posts/_id.vue`
```js
export default {
  async asyncData ({ params, from }) {
    // If navigating from the same view, return empty object to not overwrite data
    if (from && from.matched[0].name === 'posts-id') return {}
    // Otherwise we fetch the data if called from another page
    let { data } = await axios.get(`https://jsonplaceholder.typicode.com/posts/${params.id}`)
    return { post: data }
  }
}
```
