### ISSUE TITLE
How to use build.extend to change fonts property?

### ISSUE THREAD

**Issue by gtso86** [nuxt/nuxt.js#1325]
Hello folks, I was reading this ticket here #907 and I saw you already created a [example](https://github.com/nuxt/nuxt.js/blob/76a1969da176941e4e6ba394a34e3e8970d39c3d/examples/custom-build/nuxt.config.js) to extend and increase the limit size for images.

I was more comfortable with the old way to change loaders because is almost the same synthax I was using in other Vue.js projects.

Right now, what is the best way to replace a rule? Example: I want change some `url-loader` but for fonts. OR I can change the whole `vue-style-loader` set.

This is my extend fn() right now:

``` js
    extend(config, ctx) {
      // console.log(config, ctx);

      /*
      ** Sourcemaps
      */
      if (ctx.dev) {
        config.devtool = (ctx.dev ? 'eval-source-map' : false);
      }

      /*
      ** Loaders
      */
      // console.log(config.module.rules);
      const urlLoader = config.module.rules.find(loader => loader.loader === 'url-loader');
      // Increase limit to 100KO
      urlLoader.query.limit = 100000;
      // Change hash quantity
      urlLoader.query.name = 'images/[name].[hash:5].[ext]';

      /*
      ** Run ESLINT on save
      */
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        });
      }
    },

```

**Comment by bayssmekanique** [comment]
There are more than one rules using the `url-loader`, so you are just modifying the first instance found (which fortunately happens to be the image loader but that's not guaranteed to stay the same).  You will want to filter/find based on the `test` pattern or `query.name` string.

**Comment by bayssmekanique** [comment]
To specifically answer your question:
```
/*
** Build configuration
*/
build: {
  extend: (config, { isClient, isServer }) => {
    if (isClient) {
      const inlineSizeThreshold = 32000
      config.module.rules.filter(v => v.test.toString() === String(/\.(woff2?|eot|ttf|otf)(\?.*)?$/))
        .map(v => { v.query.limit = inlineSizeThreshold })
    }
  }
}
```
