### ISSUE TITLE
how to access plugin inside of vuex 1.0.0-rc4

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#1326]
Hello,

I wanted to give the current rc-4 a spin but don't understand how to access the plugin instance inside of Vuex.
`plugins/apolloClient.js`
```
import { ApolloClient, createNetworkInterface } from 'apollo-client'
import { getTokenFromStorage } from '../util/auth-helpers'
import 'isomorphic-fetch'

export default ({app, store}) => {
  const networkInterface = createNetworkInterface({
    uri: API_ENDPOINT,
    transportBatching: true
  })

  const apolloOptions = {
    networkInterface,
    dataIdFromObject: r => r.id
  }
  const apolloClient = new ApolloClient(apolloOptions)
  app.apolloClient = apolloClient
  return apolloClient
}
```
Inside of my `store/index.js`
```
import apolloClient from '~/plugins/apolloClient.js'
(...)
export const actions = {
someAction(){
(...)
apolloClient.query(SOME_QUERY) // => does not work.. query not defined
}
}
```
How is it possible to access the plugin instance or maybe even {app.apolloClient} inside of Vuex now?
Thanks

**Comment by pimlie** [comment]
Probably would be easiest to take a look at how this is done for the axios plugin: https://github.com/nuxt-community/modules/blob/master/modules/axios/plugin.js

**Comment by pi0** [comment]
Also for apollo integration:
github.com/nuxt-community/apollo-module
