### ISSUE TITLE
s.replace is not a function

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1327]
![image](https://user-images.githubusercontent.com/17898715/29155798-c9d757b6-7dd0-11e7-9551-5007ee03e8c1.png)
![image](https://user-images.githubusercontent.com/17898715/29155818-e51681e6-7dd0-11e7-97e9-e2cabf81f872.png)
![image](https://user-images.githubusercontent.com/17898715/29155825-ec91e262-7dd0-11e7-890f-61eb262b39b9.png)

**Comment by pi0** [comment]
Hi. I think problem is with using `v-text`, does this problem happens with original (unmodified) error template too? And also what if we change `v-text` to `v-html` ?

**Comment by yuchonghua** [comment]
Solved, thank you very much
![image](https://user-images.githubusercontent.com/17898715/29156574-3af4fb84-7dd5-11e7-9fba-36e9015da3e7.png)

**Comment by miladmeidanshahi** [comment]
Hi it seems my problem after change `v-text` to `v-html` does not solved.
