### ISSUE TITLE
ElementUI Vue components locale / i18n issues (workaround)

### ISSUE THREAD

**Issue by gtso86** [nuxt/nuxt.js#1328]
I spent all this morning trying to figure out how to fix ElementUI locale + Nuxt. They just [released a new version](https://github.com/ElemeFE/element/releases/tag/v1.4.2) but even they saying this should be fixed, at least on my end with Nuxt still bugged.

For now, the method wrote under this [documentation](http://element.eleme.io/#/en-US/component/i18n) doesn't work as expected.

I made a small prototype to show the problem on [Glitch.me](https://breezy-newsstand.glitch.me/). As you can see at the screenshot below, all strings disappeared:
![ElementUI locale problem](http://i.imgur.com/8lwGBPCg.png)

For those who tried change the components language like me, the only way I found for now is replacing the request via Webpack plugin like that:

`nuxt.config.js`
```js
  build: {
    plugins: [
      new webpack.NormalModuleReplacementPlugin(
        /element-ui[\/\\]lib[\/\\]locale[\/\\]lang[\/\\]zh-CN/,
        'element-ui/lib/locale/lang/en',
      ),
    ],
  }
```
I don't think this is the best solution.... and I can't define what's the cause of this problem...(if is Nuxt or ElementUI itself) So I'm leaving this workaround to help other people with the same problem here.

I didn't open a issue under ElementUI repo because seems this problem is related with Nuxt...

**Comment by gtso86** [comment]
I also found this way to enable locale without use the Webpack.

`plugins/element-ui.js`
```js
import Vue from 'vue';
import lang from 'element-ui/lib/locale/lang/en';
import locale from 'element-ui/lib/locale';

const ElementUI = require('element-ui');

// configure language
locale.use(lang);

// Init ElementUI components
Vue.use(ElementUI);
```

`nuxt.config.js`
```js
module.exports = {
  plugins: [
    '~/plugins/element-ui.js',
  ],
}
```

A little bit more elegant than replace the localization file via Webpack 👍

**Comment by dfee** [comment]
I'm not using Nuxt, but I didn't need to add the webpack plugin export, either. Is there a reason you chose to do that?
