### ISSUE TITLE
corrupted and missing assets in built vite app ('Failed to decode downloaded font')

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.js#13286]

**Comment by igor9silva** [comment]
Hi, I'm still facing that issue on Nuxt 3.4.3. My font file goes from 55KB to 84KB, and macOS can't preview it.

We're deploy to AWS Lambda (using Nuxt `aws-preset`). Locally, even when using `nuxt build`, it works properly.

Could it be an issue specifically with `aws-preset`?
