### ISSUE TITLE
Issue with single file components and css loader

### ISSUE THREAD

**Issue by couellet** [nuxt/nuxt.js#1329]
I have a project using [semantic-ui](https://semantic-ui.com). It is installed by `npm` and I changed the folder where the semantic files are generated to `assets`.

So in my `assets` folder I have a file like: `assets/semantic/dist/components/grid.css`.

In my component, I include the components I need:

```html
<template lang="pug">
  .ui.card
    .image
      img(v-bind:src="product.ThumbUrl")

    .content
      .header {{ product.Name }}
      .meta {{ product.Price }} $
      .description {{ product.Description }}

    .extra.content
      a.snipcart-add-item(
        href='#',
        data-item-url='/',
        v-bind:data-item-name='product.Name',
        v-bind:data-item-price='product.Price',
        v-bind:data-item-id='product._id',
        v-bind:data-item-image='product.ThumbUrl',
        v-bind:data-item-description='product.Description')
        i.fa.fa-cart-plus
        |  Add to cart
</template>

<script>
export default {
  props: {
    product: {
      type: Object,
      required: true
    }
  }
}
</script>

<style lang="css">
  @import '~assets/semantic/dist/components/card.css';
</style>

<style lang="less" scoped>
  .card {
    width: auto;

    .image {
      margin: 0 auto;
      width: 200px;
    }
  }
</style>
```

My build script on Netlify is: `npm install && npm run generate`.

However, I have errors that the file `assets/semantic/dist/components/card.css` can't be found.

Is there anything I am doing wrong?

**Comment by pimlie** [comment]
Try `~/assets/semantic/dist/components/card.css` (so a forward slash after the tilde)

**Comment by Atinux** [comment]
Hi @couellet 

I close this issue since you did not answer, feel free to re-open it if this issue still persists :)

**Comment by ubershmekel** [comment]
Anyone finding this googling - this seemed to work for me though I'm not sure how or why.

```
<style lang="scss">
@import 'assets/css/rylo.css';
</style>
```
