### ISSUE TITLE
[worker] definePageMeta is not defined    

### ISSUE THREAD

**Issue by Moskovskiy** [nuxt/nuxt.js#13292]

**Comment by htmlfactorycz** [comment]
I had same problem and searched a lot. Somewhere is written definePageMeta is only nuxt3 feature and not supported for nuxt bridge. But then i found this [link](https://github.com/nuxt/bridge/pull/933) and i get i to work! U have to add macros to bridge setup:
```
bridge: {
    nitro" true,
    macros: {
      pageMeta: true
    }
  },
```

and after this its working for me :)

**Comment by datamoeras** [comment]
Here is a minimal reproduction: https://stackblitz.com/edit/github-9ukebr-m2gwasvd?file=pages%2Fmy%2F%5Bid%5D%2F%5Baction%5D.vue

This must have something to do with nested routes: pages/[id]/[action].vue is consistently not working.

If you go to the url /my/123/test in the embedded browser, your browser's console will show the error: definePageMeta is not defined.

![Image](https://github.com/user-attachments/assets/9f432806-de11-4be3-923c-5258f02d1c84)

**Comment by danielroe** [comment]
@datamoeras your reproduction is using a prerelease version of nuxt (over two years outdated).

Nuxt 3 is available as the `nuxt` npm package - nuxt3 was a prerelease edge version.

here's a working example: https://stackblitz.com/edit/github-9ukebr-rpr38oqc?file=nuxt.config.ts%2Ctsconfig.json
