### ISSUE TITLE
export 'default' (imported as 'store') was not found in '~store/index.js'

### ISSUE THREAD

**Issue by pdxbmw** [nuxt/nuxt.js#133]
**Thank you for such a great tool!**

I'm trying to use `vuex` store with module files, but am running into the error (v0.9.5): 

`export 'default' (imported as 'store') was not found in '~store/index.js'`

My directory structure looks like:

```
|— layouts
|  |__ default.vue
|— pages
|  |__ index.vue
|  |__ admin.vue
|— store
|  |__ index.js
|  |__ admin.js
```

In my `store/index.js`, I'm trying to simply do:

```
export const state = { sidebar: false }
export const mutations = {}
```

And in `layout/default.vue`:

```
<template>
  <div>
    <navbar :show="true"/>
    <sidebar :show="$store.state.sidebar"></sidebar>
    <app-main/>
    <footerbar/>
  </div>
</template>
```

_NOTE: I've tried using `mapState` to get the computed property `sidebar` as well, to no avail._

I've also copied the example code from your [vuex-store-2](https://github.com/nuxt/nuxt.js/tree/master/examples/vuex-store-2), but get the same error. 

Any thoughts or suggestions?

Thanks again!

**Comment by Atinux** [comment]
Hi @pdxbmw 

The documentation was ahead of its time, this feature comes with the [0.9.6](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.6) feature.

You can upgrade your version of nuxt, it should work like a charm now!

**Comment by pdxbmw** [comment]
0.9.6 works perfectly! Thanks.
