### ISSUE TITLE
[question] in a plugin, how to add js text first then include js file

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#1330]
I am [writing](https://github.com/pimlie/modules/blob/feature-module-piwik/modules/piwik/index.js) a nuxt plugin for [piwik](https://github.com/piwik/piwik) and can't get the plugin to work in the way I think would be best.

The default example code to include Piwik on your webpage is as follows:
```js
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//piwik.example.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
```
So you have to set `setTrackerUrl` and `setSiteId` _before_ loading the `piwik.js` file. If you [do](https://github.com/pimlie/modules/blob/feature-module-piwik/modules/piwik/plugin.js) this in `plugin.js` it works fine, but I think it would be cleaner to do this in `index.js` to avoid adding js src files
 during runtime.
Unfortunately I am unable to make sure that after rendering the code is still loaded in this order.

What I tried:
- call `this.options.head.script.push` in `index.js`, one time to add the _paq.push's with innerHTML and one time to add the src to piwik.js.
```js
  let config_js = '_paq.push(["setTrackerUrl", "' + (options.trackerUrl || options.piwikUrl+'piwik.php') + '"]);'
  config_js += '_paq.push(["setSiteId", "' + options.siteId + '"])'
  this.options.head.script.push({ 
    innerHTML: config_js, type: 'text/javascript'
  })
  this.options.head.script.push({
    src: options.scriptUrl || options.piwikUrl+'piwik.js',
    async: true,
    defer: true
  })
```
> This doesnt work because using innerHTML encodes double & single quotes to htmlentities and afaik you can only disable encoding with vue-meta for the whole script group (and maybe interfering with other plugins)
```js
<script data-n-head="true" type="text/javascript">_paq.push([&quot;setTrackerUrl&quot;, &quot;//piwik.example.com/piwik.php&quot;]);_paq.push([&quot;setSiteId&quot;, &quot;1&quot;])</script>
```
- set _paq.push's at beginning of `plugin.js` and add piwik.js deferred in `index.js` with `this.options.head.script.push({ defer: true })`.
> This doesnt work because the script tag for piwik.js will have a defer tag but is not added at the bottom of the document (e.g. after window.__ NUXT__) while the _paq.push's are in `/_nuxt/app.js` at the very bottom of the page.

Are there any other possibilities to keep the javascript in the required order that I havent thought of?

**Comment by RichAyotte** [comment]
In the page that you need the script, add a `script` property to the `head()` function.

```js
export default {
  ...
  head() {
      return {
          script: [{
              src: "the-piwik-script.js"
          }]
      }
  }
}
```
@see
https://nuxtjs.org/guide/views/#pages
https://github.com/declandewet/vue-meta#script-object

**Comment by pimlie** [comment]
@pi0 @RichAyotte Thanks but this is not what I am asking / looking for, I am writing a nuxt **plugin** so at this stage I am not looking for solutions that requires adding code to every page. E.g. I want to have the same functionality as the [Google Analytics](https://github.com/nuxt-community/modules/tree/master/modules/google-analytics) plugin, so when the piwik plugin is included in `nuxt.config.js` the piwik page statistics code should be added to _all_ pages by default.

I know its my fault for explaining too much and thus having too much text in this issue, but I'd really would like to find a solution for use within my plugin code.
