### ISSUE TITLE
[Middleware] Hydration node mismatch

### ISSUE THREAD

**Issue by bynicodevelop** [nuxt/nuxt.js#13328]

**Comment by ziaadini** [comment]
I just render all routes need authentication client side and therefore no hydration no mismatch.

**Comment by 3aluw** [comment]
> I just render all routes need authentication client side and therefore no hydration, no mismatch.

Yeah, I think it is a good idea. Adding routeRules to nuxtConfig file helped me:
```
routeRules: { 
    "/admin": { ssr: false },
    "/cart": { ssr: false },
    "/profile": { ssr: false },
  },
```
