### ISSUE TITLE
.nuxtignore filter support for Nuxt3

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.js#13321]
I think we should add back nuxtignore filter support for Nuxt3 (and plugin imports). This way we can ignore unwanted paths from plugins.

_Originally posted by @pi0 in https://github.com/nuxt/framework/issues/2163#issuecomment-981612377_

**Comment by cambell-prince** [comment]
I have the same goal as @yaquawa in https://github.com/nuxt/nuxt/discussions/17980. i.e. In a complex app wanting to add page specific components under the pages folder, but not be routable.  I created .nuxtignore with
```
/pages/**/_*/**
```
The components are not routable, which is great.  However, the components are also ignored from the Vite Hot Module Reload.

Is it possible to have files excluded for routing, but included for the Vite HMR?

What is the recommended practice in Nuxt for complex pages with (many) dependent files related only to a single page?

**Comment by atomiomi** [comment]
@cambell-prince Did you find any workaround?
