### ISSUE TITLE
Nuxt static site generation - removing components on load

### ISSUE THREAD

**Issue by stevejcox** [nuxt/nuxt.js#1335]
When using the static site generator, the resulting index html has all of the content as expected. However on serving the file it's removing all but one of the components from the dom on page load.

Changing the order of the components seems to resolve the issue.

**Comment by stevejcox** [comment]
Issue appears to be coming from vendor.bundle.X.js.

Any suggestions would be welcome!

**Comment by RichAyotte** [comment]
I think I'm experiencing the same issue. Have a look at http://da-lee2.ayottesoftware.com/services/dust-control/ and notice the title dissapear after the page has loaded.

Looks like a race because when I serve the exact same generated site locally with php -S, it works fine.

What do you mean be changing the order of components?

**Comment by stevejcox** [comment]
In my case, literally just swapping components around (reordering where they are on the page).

I managed to get it working in the correct order by disabling all minification defaults. Give that a try, might help.

**Comment by RichAyotte** [comment]
Disabling minification didn't work. Back to drawing board.

**Comment by stevejcox** [comment]
Here's the generate settings I am using, could be a different issue, but worth trying these:

```
generate: {
    minify: {
      collapseBooleanAttributes: false,
      collapseWhitespace: false,
      decodeEntities: false,
      minifyCSS: false,
      minifyJS: false,
      processConditionalComments: false,
      removeAttributeQuotes: false,
      removeComments: false,
      removeEmptyAttributes: false,
      removeOptionalTags: false,
      removeRedundantAttributes: false,
      removeScriptTypeAttributes: false,
      removeStyleLinkTypeAttributes: false,
      removeTagWhitespace: false,
      sortAttributes: false,
      sortClassName: false,
      trimCustomFragments: false,
      useShortDoctype: false
    }
  }
```

Good luck!

**Comment by RichAyotte** [comment]
Looks identical to what I tried. Thanks.

**Comment by alexchopin** [comment]
Hi, 
It can be due to [Hydration Caveats](https://ssr.vuejs.org/en/hydration.html) by Vue.js.
Do you use a valid HTML structure?

**Comment by RichAyotte** [comment]
My issue turned out to be different albeit the same symptoms. The remote server was appending a slash to the routes that my local PHP -S was not which caused my $route watch that used to set the title, to fail.

**Comment by stevejcox** [comment]
Glad you got it working!

**Comment by raymonschouwenaar** [comment]
Disabling the minification helped me 👍
