### ISSUE TITLE
ERROR  [worker] Cannot read properties of undefined (reading 'getSSRProps')   

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt.js#13351]

**Comment by sr-mothership** [comment]
> You need also to have a directive.
> 
> [Working example](https://codesandbox.io/s/gifted-shape-21pyh?file=/plugins/directive.ts).
> 
> You may find [these docs](https://vuejs.org/guide/scaling-up/ssr.html#custom-directives) helpful.

The solution for us was in your codesandbox. Before setting the directive in the Vue compiler options we got the same 500 error:

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  vue: {
    compilerOptions: {
      directiveTransforms: {
        motion: () => ({
          props: [],
          needRuntime: true
        })
      }
    }
  }
});
```

Maybe this should be mentioned in the docs?

**Comment by vincerubinetti** [comment]
> I got this error when creating a plugin with a .client.js suffix (the plugin created a directive). Removing the `client` extension fixed it. This wasn't obvious at first, nor from the error message.

This seemed to be my issue too... In my case, I was using `vue-tippy` and renaming the directive to `v-tooltip` instead of `v-tippy` in the plugin options. Very weird that I'd need to actually remove `.client`. Maybe `vue-tippy` is doing some defensive checking for SSR on its own that gets screwed up by this??

**Comment by gkatsanos** [comment]
Hey, @danielroe any way to figure out from the error stack trace what the directive triggering the error is?

**Comment by danielroe** [comment]
The error stack trace emitted by Vue server renderer is pretty unforgiving. @pi0 is working on a library to improve these.

You could try injecting logs just before the file/line number mentioned.

**Comment by gkatsanos** [comment]
You mean there? : 
/Users/gxxxxxx/repos/xxxxx/requests-frontend/node_modules/.pnpm/@vue+server-renderer@3.2.47_vue@3.2.47/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:482
    if (typeof dir !== 'function' && dir.getSSRProps) {
