### ISSUE TITLE
[Nuxt3] [Middleware] Unable to use useNuxtApp()/plugins in route middleware on the clientside

### ISSUE THREAD

**Issue by oysandvik94** [nuxt/nuxt.js#13361]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27403956.614e87e`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

Global route middleware named 'aTest.global.ts':

```
export default defineNuxtRouteMiddleware((to, from) => {
    const { $auth } = useNuxtApp();

    console.log($auth);
    return;
});
```

Plugin names "$auth" looks like this:
```
import { defineNuxtPlugin } from "#app";
import useAuthClient from "~~/composables/useAuthClient";

export default defineNuxtPlugin((nuxtApp: any) => {
    const authClient = useAuthClient();

    return {
        provide: {
            auth: authClient
        }
    }
});
```

Console.log returns undefined on clientside, but is as expected serverside.

### Describe the bug

Not able to retrieve plugins route middleware unless clientside. 
It seems like the router middleware is loading before plugins clientside, but it's loaded after plugins serverside.

**Comment by productdevbook** [comment]
dont fixed same problem

**Comment by productdevbook** [comment]
this problem, `xx.global.ts` global middleware problem

**Comment by FutureExcited** [comment]
is there a possibility of accessing useNuxtApp in the server middleware?
