### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#1337]
Hello,
on deployment with zeit.co/now I receive after upgrade to NUXT 1.0.0-rc4 an error in the console:
```
> Error: incorrect header check, 7a94279e18b008b0d70a5c8e65e531c5575f5387.tar.gz
```
The build is after some tryouts successful but I still want to share this issue.

**Comment by alexchopin** [comment]
Thanks for reporting, it doesn't seem to be related to Nuxt.js.
However, we keep this issue in mind 👍
