### ISSUE TITLE
Improve warning about `definePageMeta()` outside `setup`

### ISSUE THREAD

**Issue by Patrick-Remy** [nuxt/nuxt.js#13376]

**Comment by 50l3r** [comment]
Any news on this issue? I get the same error regardless of where I position `definePageMeta`

```html
<script lang="ts">
    import { defineComponent } from 'vue'

    definePageMeta({
        layout: 'sidebar-right',
        title: 'home.title',
        sidebar: {
            position: 'right',
            component: 'v-sidebar-static'
        }
    })

    export default defineComponent({
        setup() {
            return {}
        }
    })
</script>
```

```html
<script lang="ts">
    import { defineComponent } from 'vue'

    export default defineComponent({
        setup() {
            definePageMeta({
                layout: 'sidebar-right',
                title: 'home.title',
                sidebar: {
                    position: 'right',
                    component: 'v-sidebar-static'
                }
            })

            return {}
        }
    })
</script>
```

same vibes

**Comment by sigezhao** [comment]
Nuxt version: 3.8
Node version: v20.5.0
Npm version: 9.8.0

 I get the same error when set ssr true in nuxt.config.ts and page in browser is always loading, there is no error in console.

my code:
`<script setup>
definePageMeta({
  middleware: ["category"],
  keepalive: true
})
</script>`

page directory structure:
<img width="308" alt="image" src="https://github.com/nuxt/nuxt/assets/7226882/de3b522b-a673-4555-8c8a-f558a4299caa">
when access site root directly, there is no block, and I can click inspire/index.vue and any other link, without block

when access inspire/index.vue, it will block always.

**Comment by sigezhao** [comment]
> @sigezhao If you think there is a bug, you should create a new issue with a reproduction, not comment on a closed issue from two years ago. 🙏

ok
