### ISSUE TITLE
cannot find module in nuxt.config

### ISSUE THREAD

**Issue by htjong** [nuxt/nuxt.js#1338]
Hi, I'm trying to require in a local json file sitting in my assets directory in order to nuxt-generate some routes. While requiring this file seems to work in pages, layouts, middleware, and stores, I cannot seem to get this to work in the nuxt config file. In dev, everything is fine, but once I run nuxt-generate, I run into some problems. In nuxt config, I see that 

`const axios = require('axios');` 
works fine, but

`const contentfulData = require('~/assets/data/contentful-export.json');` 
does not.

Is this expected? Are there better ways to do what I am trying to do? I am trying very hard to keep this json file local, as I expect to use it in production as well. Any help would be appreciated!

edit: 
I see https://github.com/nuxt/nuxt.js/issues/123#issuecomment-272246782 - very helpful! But I'm not sure it solves the nuxt-generate problem. One thing I can think of is to create a small api server to serve my json file for the sole purpose of generating the routes, but if there are better options, I'd gladly take them.

**Comment by bayssmekanique** [comment]
When you use `require()`, the `~` is going to be looking in the root of your `node_modules` directory, not the root of your application as you are expecting.

Instead, use `const contentfulData = require('./assets/data/contentful-export.json');`, assuming that the file you are pulling it into is sitting at the root of the directory.  If not, then you would need to include the appropriate directory navigation.

**Comment by htjong** [comment]
Wow I feel so silly now. That dot may have been the one character I didn't use. Thanks @bayssmekanique !
