### ISSUE TITLE
How to incorporate google tag manager into Nuxt?

### ISSUE THREAD

**Issue by jakeknight** [nuxt/nuxt.js#1340]
Hello,

I'm struggling to put google tag manager into nuxt. I just need to inject the script onto the page and then for vue to use it.

Thanks

**Comment by awronski** [comment]
Try [google tag manager module](https://github.com/nuxt-community/modules/tree/master/modules/google-tag-manager)

**Comment by jakeknight** [comment]
@awronski Thank you! Works wonder

**Comment by adrianoresende** [comment]
This module does not exist anymore.

**Comment by aldarund** [comment]
@adrianoresende it exist, link wrong https://github.com/nuxt-community/modules/tree/master/packages/google-tag-manager
Although the one you linked seems like a valid one too. Dont know what the differences :)
