### ISSUE TITLE
SyntaxError: .nuxt/index.js: Unexpected token (98:4)

### ISSUE THREAD

**Issue by daosonit** [nuxt/nuxt.js#1345]
I have error, notify in webstorm ! Who can help me?
```
/usr/bin/babel .nuxt/index.js --out-dir dist --source-maps --presets env
SyntaxError: .nuxt/index.js: Unexpected token (98:4)
   96 |       }
   97 |     },
>  98 |     ...App
      |     ^
   99 |   }
  100 | 
  101 |   const next = ssrContext ? ssrContext.next : location => app.router.push(location)

Process finished with exit code 1
```

**Comment by bayssmekanique** [comment]
This is saying that whatever version of node you are running does not have the array spread syntax support.  You need to upgrade your node version to at least version 5.12.0.

**Comment by daosonit** [comment]
Now, i use node 7.7 and npm 4.4. Please i want to question, Which version node, version npm is suitable for nuxt 1.0.0-rc4 ?

**Comment by bayssmekanique** [comment]
As long as you are on Node version 6.11.2 or greater, you are fine.  The npm version doesn't really matter, as long as it's compatible with the Node version.
