### ISSUE TITLE
List of sites that use Nuxt.js (Feature)

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt.js#1346]
Very helpful for people doing research on frameworks and wondering the level of stability.  

If this exists I'd like to add to it, if it doesn't I'd like to help start one, I can definitely add to it!

It would be cool to also list the templates/frameworks/structures used with nuxt, and even a link to the repo if it's public.

**Comment by alexchopin** [comment]
Hi @acidjazz, a public repo has been created for that: [Awesome Nuxt](https://github.com/nuxt-community/awesome-nuxt).
It needs to be updated with all new resources which appear every day :)

**Comment by acidjazz** [comment]
@alexchopin OK cool, I'll definitely contribute to that, but I also think it's pretty important we put either this list or a curated version of this list somewhere easier found for people researching frameworks, like maybe even the nuxtjs readme?
