### ISSUE TITLE
Unexpected 404 file creation

### ISSUE THREAD

**Issue by bayssmekanique** [nuxt/nuxt.js#1347]
I am attempting to figure out if this is expected behavior that isn't documented or a side-effect of something that's changed recently.  I have a `pages/404.vue` file which is used as the default 404 page by the web server (SSR to S3).  Until recently, this vue file would be rendered and stored at `/404/index.html` just like any other vue file, but I've noticed that on Linux this file now generates at the root as `/404.html`.  This seems to only happen on Linux (both environments confirmed to be running the same Nuxt version).

I've seen issues discussing needing the 404.html file in the root for some hosting services, but I can't find a specific commit or any mention in the releases to this change.  Is this a long term change?  Is there solution for preventing this behavior (since all my other error pages aren't being handled this way)?

**Comment by pimlie** [comment]
See issue #966, the `404/index.html` is copied to `404.html` for compatibility with static hosting services

**Comment by iamdubx** [comment]
@pimlie nothing is copied, this is still not working!

I create Page component on route `404/index.vue` - and I still doesn't have 404 page when `generated`
