### ISSUE TITLE
head meta add absolute image paths

### ISSUE THREAD

**Issue by Burzmalian** [nuxt/nuxt.js#1348]
Hello,

When adding meta via head () I want to add an og:image using dynamic assets, and they need to have an absolute path, not a relative one:

**{ hid: 'og-image', property: 'og-image', content: 'need-absolute-path-here' }**

Is there a way to set a variable depending on whether the build is dev or production?

something like? :
**if (process.env.NODE_ENV === 'production') {
  this.prodBaseUrl = 'https://mydomain.com/_nuxt/img/'
}**

Any advice would be much appreciated!

Thanks!

Gyles

**Comment by pimlie** [comment]
Can you use the `dev` property? https://nuxtjs.org/api/configuration-dev/#the-dev-property

**Comment by Atinux** [comment]
Hi @Burzmalian 

You can use `process.env.NODE_ENV` inside your vue files, Nuxt.js sets it automatically.

Example:
```vue
<script>
export default {
  head: {
    title: 'Env: ' + process.env.NODE_ENV
  }
}
</script>

**Comment by Burzmalian** [comment]
Thanks!  This is how i accomplished absolute image paths for open-graph image meta tags.

1.  import the image
2.  on creation check environment, set domain data (prodBaseUrl) if production
3.  add domain data +  relative image path to meta tag

```
<script>
import socialImage from '~/assets/images/social-graphic.png'

export default {
  data () {
    return {
      prodBaseUrl: ''
    }
  },
  head () {
    return {
      meta: [
        { hid: 'og-image', property: 'og-image', content: this.prodBaseUrl + socialImage }
      ]
    }
  },
  created: function () {
    if (process.env.NODE_ENV === 'production') {
      this.prodBaseUrl = 'http://mydomain.com'
    } else {
      this.prodBaseUrl = process.env.baseUrl
    }
  }
}
</script>
```
