### ISSUE TITLE
cookie does not provide an export named 'parse'

### ISSUE THREAD

**Issue by Droutin** [nuxt/nuxt.js#13488]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27449998.32cf973`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `buildModules`, `intlify`, `css`, `meta`, `vite`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`

### Reproduction

I can't provide source code...

### Describe the bug

When I start dev server with `nuxi dev` I receive in clients console this error.
`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/cookie/index.js?v=a7242bcf' does not provide an export named 'parse'`

It refers to http://localhost:3000/_nuxt/node_modules/h3/dist/index.mjs?v=a7242bcf where it cant import methods of cookie.
```js
import { parse, serialize } from '/_nuxt/node_modules/cookie/index.js?v=a7242bcf';
```

BUT when I build that same source code with `nuxi build` everything works

### Additional context

package.json
```json
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "cross-env NUXT_HOST=0.0.0.0 node .output/server/index.mjs",
    "format": "prettier --config .prettierrc . --write"
  },
  "devDependencies": {
    "@intlify/nuxt3": "^0.1.10",
    "cross-env": "^7.0.3",
    "nuxt3": "^3.0.0-27449998.32cf973",
    "prettier": "^2.5.1",
    "prisma": "^3.10.0"
  },
  "dependencies": {
    "@id-sk/frontend": "^2.9.0",
    "@prisma/client": "^3.10.0",
    "@vue-leaflet/vue-leaflet": "^0.6.1",
    "axios": "^0.26.1",
    "base64-img": "^1.0.4",
    "dayjs": "^1.10.8",
    "elmolis-corageo": "git+ssh://git@gitlab.elmolis.sk:Urbi/IntParkCoraGeo.git",
    "leaflet": "^1.7.1",
    "mustache": "^4.2.0",
    "sass": "^1.49.9"
  }
}
```

**Comment by imding** [comment]
hi, I still have this issue after running `pnpx nuxi upgrade --force`, I believe the `cookie` package is a peer dependency of `@auth/core`.

```
{
    "private": true,
    "scripts": {
        "build": "nuxt build",
        "dev": "nuxt dev",
        "generate": "nuxt generate",
        "preview": "nuxt preview",
        "postinstall": "nuxt prepare"
    },
    "devDependencies": {
        "@nuxt/ui": "^2.10.0",
        "@nuxtjs/eslint-config-typescript": "^12.1.0",
        "@nuxtjs/eslint-module": "^4.1.0",
        "@types/mdast": "^4.0.1",
        "@types/node": "^18.17.1",
        "eslint": "^8.52.0",
        "nuxt": "^3.8.0",
        "prettier": "^3.0.3",
        "prettier-plugin-tailwindcss": "^0.5.6"
    },
    "dependencies": {
        "@auth/core": "^0.17.0",
        "@hebilicious/authjs-nuxt": "^0.3.5",
        "@iconify-json/mdi": "^1.1.55",
        "remark-gfm": "^4.0.0",
        "remark-parse": "^11.0.0",
        "resend": "^1.1.0",
        "unified": "^11.0.3"
    }
}
```

**Comment by stepaniukm** [comment]
Having the same issue still.

**Comment by fl0wo** [comment]
Same here

**Comment by fl0wo** [comment]
Hey @imding did you find a workaround?

**Comment by ploppingeric** [comment]
@fl0wo I was able to work around the above this export error by using @auth/core version 0.17.0 and also by adding this to my nuxt config:
```javascript
	vite: {
		optimizeDeps: {
			include: ["@auth/core"],
		}
	}
```

**Comment by imding** [comment]
> Hey @imding did you find a workaround?

Unfortunately I did not, using `@auth/core` was an experiment for me so I just removed it. Maybe @ploppingeric's tip helps.
