### ISSUE TITLE
Dynamically creating <NuxtLink> with <Component> no longer works

### ISSUE THREAD

**Issue by ataylor32** [nuxt/nuxt.js#13483]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27454426.4cefce4`
- Package Manager:  `npm@8.5.4`
- Bundler:          `Vite`
- User Config:      `meta`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-92nabt?file=app.vue

### Describe the bug

Code like this used to work, but no longer does:

```html
<Component :is="1 === 1 ? 'NuxtLink' : 'a'" to="/example">
  This should be a link to the "Example" page
</Component>
```

### Additional context

Two others with the same problem:

https://discord.com/channels/473401852243869706/897487139888062506/953235583403196476

https://discord.com/channels/473401852243869706/897487139888062506/953281246472056882

**Comment by yoshrubin** [comment]
> The new way to pull in a component that is not globally registered is to use `resolveComponent`.
> 
> See [docs](https://v3.nuxtjs.org/guide/directory-structure/components#dynamic-components) and [this comment](https://github.com/nuxt/nuxt.js/issues/13547).
> 
> **[Example with NuxtLink](https://stackblitz.com/edit/github-58urlz?file=app.vue).**

this gives me a warning
```
[Vue warn]: Failed to resolve component: NuxtLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
I am on latest version of Nuxt migrating from Nuxt2

**Comment by lukas-pierce** [comment]
Use import from `#components`:

```vue
<template>
  <div>
    <input type="checkbox" v-model="isLink"> is link?<br>
    <Component :is="isLink ? NuxtLink : 'span'" :to="isLink ? {name: 'index'} : undefined">{{ isLink ? 'Link' : 'Text' }}</Component>
  </div>
</template>

<script setup>
import { NuxtLink } from '#components'

const isLink = ref(false)
</script>

```

Components declaration is available in build file: `.nuxt/components.d.ts`

If you dont see this just rerun 'npm run dev'

Official docs: https://nuxt.com/docs/guide/directory-structure/components#direct-imports
