### ISSUE TITLE
Can't use Vue components in Nuxt

### ISSUE THREAD

**Issue by JonathanAlumbaugh** [nuxt/nuxt.js#1349]
Hi there, I'm new to just about everything (Vue.js, Nuxt.js, webpack...) so if I'm asking this in the wrong place my apologies.

I would like to use a Vue component such as Vuebar on my app but have as yet been unable to use pretty much any component I've tried to add. I install the package via `npm install --save vuebar` and it appears in my package.json, then I try to import it in my default layout using 
`import Vuebar from 'vuebar'
export default {
  components: {
    Vuebar }
}`
but when I try to use it in the default layout with `<div v-bar></div>` it says "failed to resolve directive: bar"

I haven't been able to get any other packages that are used in components to work either so I can't help but think I'm missing some fundamental step here, do I need to add an alias to nuxt.config.js or something like that?

Again, my apologies for the uninformed question, if this is the wrong place please feel free to delete this.

**Comment by JonathanAlumbaugh** [comment]
Alright as I suspected I finally came across the answer right after posting a question, my apologies, found the answers in the plugin documentation [here](https://nuxtjs.org/guide/plugins). Somehow I didn't think that applied until I looked at it again just now. Sorry.

**Comment by zhj135** [comment]
Thanks for your issue, I made the same mistake.
