### ISSUE TITLE
How to access query parameters

### ISSUE THREAD

**Issue by dan-gamble** [nuxt/nuxt.js#135]
Things like `/objects?page=2`.

When doing:

```javascript
    async data ({ params }) {
      try {
        let BASE_URL = `http://localhost:8080/api/v1/nations`

        const { data } = await axios.get(BASE_URL)

        return {
          currentPage: data.currentPage,
          nations: data.data
        }
      } catch (e) {
        console.error(e)
      }
    }
```

I'm not sure how to access the `this.$route.query.page`.

`this` is `undefined` and `params` doesn't hold any query data, just the `id` i believe.

**Comment by alexchopin** [comment]
You can access with the key `query` which is an alias of this.$route.query.
More info on the documentation : [https://nuxtjs.org/api/pages-context](https://nuxtjs.org/api/pages-context)

**Comment by dan-gamble** [comment]
Thanks, i should've checked the API part instead of just the guide :)

**Comment by alexchopin** [comment]
No worries, the documentation is still messy now. :)
