### ISSUE TITLE
nuxt build and start cannot load vue components properly

### ISSUE THREAD

**Issue by sj82516** [nuxt/nuxt.js#1350]
I am using nuxt@1.0.0-rc3 and koa template.  
When I use `npm run dev`, web works properly.  
After I `npm run build && npm start`, web is loaded without show error msg.  
But the components like vue-recaptcha , vue-googlemap which work well in dev, now all broken and unseen.  
How can I fix this?  
Thanks

**Comment by Atinux** [comment]
Feel free to re-open it when a reproduction repo or example on glitch (https://glitch.com/edit/#!/nuxt-hello-world)

**Comment by sj82516** [comment]
I found this error in my browser (Chrome 60) but it works on Safari and Firefox.
> Refused to execute script from '....../_nuxt/3.nuxt.bundle.aba6808cffce123e4e93.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

**Comment by sj82516** [comment]
I have tried on Chrome 59 on sauce lab and it works.
The only problem is Chrome 60 :/

**Comment by paulgv** [comment]
Please share some code that would help us reproduce the issue.

**Comment by sj82516** [comment]
I would like to share some code but I have no idea which part cause this issue. 
My web is run `npm run build & npm run start`, the strange part is 
![nuxt_error](https://user-images.githubusercontent.com/6858460/29646163-67579f80-88b4-11e7-8f3f-a9781c12e9e4.jpeg)

But I have tried to create a new project and reinstall nuxt starter project. 
It loaded in the right content type.
![nuxt_success](https://user-images.githubusercontent.com/6858460/29646164-675a7796-88b4-11e7-8627-a7f9237a5f84.jpeg)

Sorry for the rough repo.

**Comment by sj82516** [comment]
My fault.
I commented out helmet() and cors() middleware then it works fine.

Sorry for this inappropriate issue and thanks for your great effort.
Looking for official release. 👍

**Comment by yoann54** [comment]
I see u were using vue recaptcha in ur app, do u have a link on how to do that ?, im having hard time using the vue recaptcha ib my contact page.
