### ISSUE TITLE
[v1.0.0-rc4] axios cannot use Vue.prototype.$axios [axios v0.16.2]

### ISSUE THREAD

**Issue by alterhu2020** [nuxt/nuxt.js#1353]
I want to access the axios instance from Vue's `methods`, so I write the axios plugin in `plugins\axios.js` as below( Which I had refer the official's `axios` module(https://github.com/nuxt-community/modules/blob/master/modules/axios/plugin.js） 
```
import Vue from 'vue'
import Axios from 'axios'
import https from 'https'

//1. Define the plugin as module recommanded
const axiosPlugin = {
  install() {
    if(Vue.__nuxt_axios_installed__) {
      return
    }
    Vue.__nuxt_axios_installed__ = true

    if (!Vue.prototype.hasOwnProperty('$axios')) {
      Object.defineProperty(Vue.prototype, '$axios', {
        get () {
          return this.$root.$options.$axios
        }
      })
    }
  }
}
// 2. Use axios in global environment page instance
export default ({app, store}) => {
  const AuthorizationToken = 'Basic YWx0ZXJodTIwMjBAZ21haWwuY29tOmd1Y2hhbjE4wewMjY='
 // Http bypass the unknown issued certificate
  const Agent = new https.Agent({
    rejectUnauthorized: false
  })

  const axios = Axios.create()
// instance.defaults.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`
  axios.defaults.httpsAgent = Agent
  axios.defaults.headers.common['Authorization'] = AuthorizationToken
  axios.defaults.timeout = 60000

  // Make accessible using *.axios
 // or  just use Vue.prototype.$axios=axios
  Vue.use(axiosPlugin)
  app.axios = axios
  if (store) {
    store.axios = axios
  }
}
```
But when I access the axios instance from `methods` in Vue file ,like below :
```
 methods: {
    changeit:() =>{
       this.fullscreenLoading = true
       const response = this.$axios.get('https://api.github.com/user')
       this.user=response.data.login
    }
  }
```
Then when we call this method ,from nuxt it throws below exception(`TypeError: Cannot read property 'get' of undefined
    at VueComponent.changeit (http://localhost:7070/_nuxt/webpack:/pages/index.vue:29:1)`):

![2017-08-12_152943](https://user-images.githubusercontent.com/5029046/29238943-290521d4-7f73-11e7-803c-3b5688dfdeb1.png)

I had tried to use other Vue plugins through `Vue.prototype.$plugigname=`, And it also met this same exception above .

Anybody know how to use the Vue plugin instance directly in nuxt ?  really appreciated your help ....

**Comment by Atinux** [comment]
Hi @alterhu2020 

This is a misunderstanding of JavaScript, when you use `() => {}`, this is not the one from the Vue instance but another one. Please update your code to the following:

```js
 methods: {
    changeit() {
       this.fullscreenLoading = true
       const response = this.$axios.get('https://api.github.com/user')
       this.user=response.data.login
    }
  }
```

**Comment by alterhu2020** [comment]
thanks @Atinux . I had found that in Vue sometime we cannot use the `arrow function` that's the misunderstand in my side .thanks your help .
BTW ,Nuxtjs is really helpful for our Vue app, great work your team. I'm looking foward the 1.0.0 release ...
