### ISSUE TITLE
Unknown middleware: auth. Valid options are .

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt.js#13543]

**Comment by andipahlevy** [comment]
still error

**Comment by manniL** [comment]
> still error

Please open a new issue with a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) then and feel free to link this one then 🙏

**Comment by 3aluw** [comment]
I had this issue and resolved it by just restarting the dev server
