### ISSUE TITLE
Upgrade required

### ISSUE THREAD

**Issue by Dragonlord1005** [nuxt/nuxt.js#13545]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27470397.9ebea90`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/Dragonlord1005/nuxt-boi

Run yarn dev on replit

### Describe the bug

When running yarn dev, I go to the local site, and it says Upgrade Required

### Additional context

Running on replit

**Comment by lucasschirm** [comment]
Where did you set the --port config? added to package dev 

    "dev": "nuxt dev --port 443",

https://replit.com/@LucasSchirm/Nuxt-3-Basic-Setup

Still getting the upgraded required

**Comment by lucasschirm** [comment]
> Just found the solution, by adding the --port flag and setting it to 443, it works properly

Where did you set the --port config? added to package dev

"dev": "nuxt dev --port 443",
https://replit.com/@LucasSchirm/Nuxt-3-Basic-Setup

Still getting the upgraded required

**Comment by lethiferal** [comment]
> > Just found the solution, by adding the --port flag and setting it to 443, it works properly
> 
> Where did you set the --port config? added to package dev
> 
> "dev": "nuxt dev --port 443", https://replit.com/@LucasSchirm/Nuxt-3-Basic-Setup
> 
> Still getting the upgraded required

Same here, can you share how you fixed it? adding `--hostname '0.0.0.0' --port 3000` in the build command doesn't seem to help.

**Comment by julbd** [comment]
I got this issue after upgrading to 4.3.0. I have no idea why.
It disappears when downgrading to 4.2.1.
