### ISSUE TITLE
Delayed scroll top possible?

### ISSUE THREAD

**Issue by smith64fx** [nuxt/nuxt.js#1355]
Hey guys!

Is it possible to delay the scroll top after a route change?

The reason is this:
I have a page transition (300ms fade out / in) and I want trigger the scroll top *after* the current page faded out, so after 300ms.

**Comment by pimlie** [comment]
You can implement your own scroll behaviour like this: https://nuxtjs.org/api/configuration-router/#scrollbehavior. Maybe you could import waitFor from Nuxt's `lib/common/utils.js` and wait for 300ms before returning?
```js
async function waitFor (ms) {
  return new Promise(function (resolve) {
    setTimeout(resolve, (ms || 0))
  })
}

await waitFor(300)
```
As scroll behaviour is directly passed to `vue-router`, also have a look at their documentation: https://router.vuejs.org/en/advanced/scroll-behavior.html

**Comment by Atinux** [comment]
Hi, this is a known issue of vue-router, see https://github.com/vuejs/vue-router/issues/1263
