### ISSUE TITLE
[Bug Report] babel-plugin-component bug

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1356]
### Element UI version
1.4.2

### OS/Browsers version
all

### Vue version
2.4.2

### Nuxt version
v1.0.0-rc4

### Reproduction Link
[git file](https://github.com/nuxt/nuxt.js/files/1220586/nuxt-element-bug-master.zip)

### Steps to reproduce
```shell

git clone https://github.com/ddvjs/nuxt-assets-bug.git
cd nuxt-element-bug
npm i
npm run dev

```

![image](https://user-images.githubusercontent.com/17898715/29243347-75759650-7fcf-11e7-98fa-2294361817ce.png)
This is the problem of [nuxt](https://github.com/nuxt/nuxt.js/issues/1356) or [element](https://github.com/ElemeFE/element/issues/6443) of the problem?

### What is Expected?
Can be used normally

### What is actually happening?
Can be used normally

**Comment by pimlie** [comment]
This is a non-issue, in index2.vue you have `import 'element-ui/lib/theme-default/index.css'` but not in index.vue.

If you dont include the css you want get the nice styling ;)

**Comment by pimlie** [comment]
You need to set the babel configuration in `nuxt.config.js`, not in .babelrc.

```js
module.exports = {
  /*
  ** Head elements
  ** Add Roboto font and Material Icons
  */
  head: {
    link: [
    ]
  },
  /*
  ** Add Vuetify into vendor.bundle.js
  */
  build: {
    vendor: [],
    extractCSS: true,
    babel: {
        plugins: [
            [ "component", {
                libraryName: "element-ui",
                styleLibraryName: "theme-default"
            }]
        ]
    }
  },
  /*
  ** Load Vuetify into the app
  */
  plugins: [],
  /*
  ** Load Vuetify CSS globally
  */
  css: []
}
```

**Comment by yuchonghua** [comment]
thank you very much

**Comment by yoyo837** [comment]
@pimlie 
However, it does not seem to support multiple module
#1603

**Comment by yuchonghua** [comment]
[new issues](https://github.com/nuxt/nuxt.js/issues/1603)
/ping @pimlie
