### ISSUE TITLE
[NITRO] WARN  [worker] listen EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by misaon** [nuxt/nuxt.js#13587]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v17.8.0`
- Nuxt Version:     `3.0.0-27477996.646c2f6`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Hapen randomly

### Describe the bug

Sometimes I get this error during development in the console. It seems completely random but often.

### Additional context

Nuxt runs in my clean Docker container:

```
FROM node:17.8.0-alpine3.15 as nuxtBuild

WORKDIR /app

COPY ./client ./

RUN yarn config set npmRegistryServer https://registry.npmmirror.com/ \
    && yarn install \
    && yarn run build

FROM node:17.8.0-alpine3.15

WORKDIR /app

COPY ./client/package.json /app/package.json
COPY ./docker-entrypoint.sh /usr/local/bin/oxy-entrypoint
COPY --from=nuxtBuild /app/.output /app/.output

RUN chmod +x /usr/local/bin/oxy-entrypoint

ENV NUXT_HOST=0.0.0.0

ENTRYPOINT ["oxy-entrypoint"]
```

Entrypoint:

```
#!/bin/sh
set -e

if [ "$NODE_ENV" = "production" ]; then
    yarn run start
else
    yarn install
    yarn run dev
fi
```

### Logs

```shell
WARN  [worker] listen EADDRINUSE: address already in use /tmp/nitro/worker-74-2.sock
 
   at Server.setupListenHandle [as _listen2] (node:net:1355:21)
   at listenInCluster (node:net:1420:12)
   at Server.listen (node:net:1519:5)
   at .nuxt/nitro/index.mjs:140:8
   at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
   at async Promise.all (index 0)
   at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
   at async loadESM (node:internal/process/esm_loader:88:5)
   at async handleMainPromise (node:internal/modules/run_main:61:12)
```

**Comment by Intevel** [comment]
Same problem still in 3.0.0, whenever I restart my container. Is there a fix planned? @pi0

**Comment by pi0** [comment]
Let's track in https://github.com/unjs/nitro/issues/885. Any additional information or minimal nitro reproduction is more than welcome.

**Comment by vwasteels** [comment]
Still happening here (randomly too) 

Nuxt version :
```
"nuxt": "^3.0.0-rc.14",
```
Docker :
```
node:16-alpine
```

**Comment by vwasteels** [comment]
I just ran ```npx nuxi upgrade``` and it took me from ```3.0.0-rc.10``` to ```3.0.0-rc.14```

**Comment by vwasteels** [comment]
I will update to 3.2.3 manually

**Comment by bf** [comment]
@vwasteels did you try `docker-compose up --force-recreate`? When I had the error I did this command **ONCE** and haven't had the issue ever since.

**Comment by Mathias9807** [comment]
Didn't see anyone mention it but another workaround seems to be to mark the containers /tmp folder to use tmpfs storage so the socket files won't persist across runs. On docker-compose just add `tmpfs: /tmp` to your container specification, or when running the container directly add `--tmpfs /tmp` to the run command.

**Comment by vwasteels** [comment]
> @vwasteels did you try `docker-compose up --force-recreate`? When I had the error I did this command **ONCE** and haven't had the issue ever since.

This seems to do the trick :)
Thanks !

**Comment by misaon** [comment]
I put together a sample Nuxt 3 project repo with Docker support + resolving this bug https://github.com/misaon/nuxt-docker.

**Comment by olivermaldonado** [comment]
> Didn't see anyone mention it but another workaround seems to be to mark the containers /tmp folder to use tmpfs storage so the socket files won't persist across runs. On docker-compose just add `tmpfs: /tmp` to your container specification, or when running the container directly add `--tmpfs /tmp` to the run command.

This worked for me

**Comment by maximilianfixl** [comment]
> > Didn't see anyone mention it but another workaround seems to be to mark the containers /tmp folder to use tmpfs storage so the socket files won't persist across runs. On docker-compose just add `tmpfs: /tmp` to your container specification, or when running the container directly add `--tmpfs /tmp` to the run command.
> 
> This worked for me

This has also been the best solution for me, that I could restart the conatiner without Nitro leaving the port still in use. From my point of view also a clean solution.

However, here I still ask myself the question, one should restrict the `tmpfs` to `/nitro/*`, in order to exclude unwanted behavior. However, this would contradict the concept of Docker: one container, one purpose (service). So what else would be expected in `/tmp` that should remain in the cache if necessary? 

Does anyone have experience they could share on this?

**Comment by pi0** [comment]
Reminder for upstream tracker: https://github.com/unjs/nitro/issues/885

This is an unwanted behavior from nitro and it should work out of the box...

**Comment by sonsoixam** [comment]
same problem with laravel forge
`[nitro] ✔ You can preview this build using node .output/server/index.mjs
[nitro] [uncaughtException] Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at file:///home/forge/abc.com/.output/server/chunks/nitro/node-server.mjs:5870:25
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
Restarting FPM...`

**Comment by KirVelikiyy** [comment]
> Guys, I have this issue with docker and this thing is getting boring. Every file change brings this issue, I can not do the hot reload. Is there any progress?

https://github.com/nuxt/nuxt/issues/12662#issuecomment-1397224239
