### ISSUE TITLE
Help with using vue-masonry (Failed to resolve directive: masonry)

### ISSUE THREAD

**Issue by andreliem** [nuxt/nuxt.js#1359]
Hey guys, wondering if I'm missing a step in trying to use `vue-masonry` with a NuxtJS site that is generated.

Here's what I have

nuxt.config.js
``` 
  plugins: [
    {
      src: '~plugins/vue-masonry.js',
      ssr: false
    }
  ],
```

vue-masonry.js
```
import Vue from 'vue'
import VueMasonryPlugin from 'vue-masonry'

Vue.use(VueMasonryPlugin)
```

and then in the actual component template something like this
```
 <div v-masonry transition-duration="0.3s" column-width="0" item-selector=".item">
            <div v-masonry-tile class="item" v-for="(item, index) in items">
          
```

It keeps saying the directive cannot be resolved `Failed to resolve directive: masonry`. Seems like I'm missing a step on how to register directives from 3rd party components

Any help would be greatly appreciated!

**Comment by pi0** [comment]
Hi @andreliem. I think this is because of SSR incompatibility that needs [special directives](https://ssr.vuejs.org/en/api.html#directives) implementation so from server side they are not working. Simply you can wrap this part into [vue-no-ssr](https://github.com/egoist/vue-no-ssr) to prevent getting this error :)

**Comment by andreliem** [comment]
Hi @pi0, thanks for the tips. I tried using the `vue-no-ssr` component, turned off ssr in the nuxt config file and then it reverted to the typical error `window is not defined`.

So then I tried wrapping the code in the conditional check as mentioned in the docs
```
if (process.browser) {
  Vue.use(VueMasonryPlugin)
}
```

I also tried `if (process.BROWSER_BUILD) {` in case referring to the older versions, but I'm on the latest Nuxt so think it should be `browser`.

Maybe this component just won't work?

**Comment by pi0** [comment]
I think we may have to keep `ssr: false` for plugin. (`window is not defined` error is from import statement in plugin)

**Comment by andreliem** [comment]
Hmm... yeah I tried that and it does load but then it still returns the same original error of failing to load the directive.

I have it wrapped with no-ssr as below
```
<no-ssr>
  <div v-masonry>
  <div v-masonry-tile>
 ```

**Comment by pi0** [comment]
WIP, Semi Working demo:

https://glitch.com/edit/#!/nuxt-masonary
https://nuxt-masonary.glitch.me

**Comment by andreliem** [comment]
Thanks for setting this up @pi0, much appreciated. For some reason my version isn't working, even when I have it more or less matching your demo. I'm going to try setting up a blank nuxt project and see what happens.

**Comment by andreliem** [comment]
Hi @pi0, I setup a blank nuxt project and it's still having issues so I'm a bit lost, might have to give up on this one! If you have any time, I posted it to a public repo here https://github.com/andreliem/nuxt-masonry

Let me know if you happen to try it out and it works for you. Thanks

**Comment by andreliem** [comment]
@pi0 Turns out that by reverting my version of vue-masonry to 0.10.5 fixed my problem (https://github.com/shershen08/vue-masonry/issues/28) , on top of your recommendations I believe. Thanks for the help.

**Comment by richlloydmiles** [comment]
@andreliem @pi0 I had the same issue and I think I found the missing piece of the puzzle that works with the latest version.

The main thing is to not include no-ssr in the plugin but rather in the component.

plugins/vue-masonry.js
```
import Vue from 'vue'
import VueMasonryPlugin from 'vue-masonry'

Vue.use(VueMasonryPlugin)
```

example-component.vue 

```
  import NoSSR from 'vue-no-ssr'

  export default {
    components: {
      'no-ssr': NoSSR
    },
    mounted () {
      if (typeof this.$redrawVueMasonry === 'function') {
        this.$redrawVueMasonry()
      }
    }
  }
```

**Comment by camilodelvasto** [comment]
I was also struggling, but changing the vue-masonry version did the trick for me as suggested by @andreliem 
Here a glitch for the future —probably for myself :) : https://glitch.com/edit/#!/hanging-angle

**Comment by rico** [comment]
The first answer to issue #18 helped in my case.

**Comment by tetreault** [comment]
Going down to suggested version of 0.10.5 resolves this build error for me, though it is still not ideal to use a version that isnt the latest version. Since many people had this issue, I'm curious if this has been resolved in the latest version? 🤔
