### ISSUE TITLE
vuex configuration - strict mode

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#136]
Just reporting that there doesn't seem to be a way to enable strict mode. Is there an entry point to modify vuex configurations?

**Comment by Atinux** [comment]
Hi @uptownhr 

You need to use the [normal way](https://nuxtjs.org/guide/vuex-store#activate-the-store) of using the `vuex` store with Nuxt.js.

Take a look at this example: https://github.com/nuxt/nuxt.js/blob/master/examples/vuex-store/store/index.js#L6

You can add the `strict` option between the line 6 and 7.
