### ISSUE TITLE
Proposition: nuxt examples to separate repo

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#1362]
Hi @alexchopin @pi0 @Atinux 

Please consider moving examples from `nuxt/nuxt.js` to separate repo. Maybe to `nuxt-community`?
I believe that community can add lots of useful examples and the main nuxt repo will be cleaner.

What do you think?

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1206">#c1206</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @awronski 

Actually we talked about this with @alexchopin a long time ago, I believe we will do this in a near future (with the new documentation website since the actual one depends of this repo).

**Comment by galvez** [comment]
@Atinux closabe?
