### ISSUE TITLE
What is the best way to debug "Maximum call stack size exceeded"?

### ISSUE THREAD

**Issue by gtso86** [nuxt/nuxt.js#1363]
Sometimes when I'm coding I got the error screen generated by SSR. Mostly of time, a hard reload solves the problems, but sometimes not. What is the best way to debug and try to find the cause when you get **Maximum call stack size exceeded** error?

![](http://i.imgur.com/SFTsct8g.png)

**Comment by Atinux** [comment]
Hi @gtso86 

This is a known issue, please see #1354 

If you could help us with a reproduction, it would be awesome!
