### ISSUE TITLE
 I can not connect the vue-scrollto package

### ISSUE THREAD

**Issue by martovytskyi** [nuxt/nuxt.js#1364]
When I connect the vue-scrollto https://rigor789.github.io/vue-scrollto/#/  package to nuxt.config.js, an error occurs   cannot/Get
Unexpected token import

**vue-scrollto.js**

import Vue from 'vue'
import VueScrollTo from 'vue-scrollto'
Vue.use(VueScrollTo)

I tried it differently:

const Vue = require('vue')
const VueScrollTo = require('vue-scrollto')
Vue.use(VueScrollTo)

**nuxt.config.js**

modules: { 
     'vue-scrollto'
 }

I ask to help understand)

**Comment by Atinux** [comment]
Hi @martovytskyi 

Please read [the documentation](https://nuxtjs.org/guide/plugins), you need to use plugins and not `modules`.

Working demo: https://nuxt-scroll-to.glitch.me/
Code: https://glitch.com/edit/#!/nuxt-scroll-to?path=pages/index.vue:3:21

**Comment by martovytskyi** [comment]
Hi @Atinux . Thank you for your work. I do everything the same way as you do, but get an error:
This dependency was not found:
* Vue-scrollto in ./plugins/vue-scrollto.js
To install it, you can run: npm install --save vue-scrollto

And the file vue-scrollto.js is not compiled.
