### ISSUE TITLE
Nuxt is not a constructor

### ISSUE THREAD

**Issue by ergenekonyigit** [nuxt/nuxt.js#1366]
![screen shot 2017-08-14 at 10 57 14 2](https://user-images.githubusercontent.com/7110136/29262961-7b644ad2-80df-11e7-8a38-75764ac483bc.png)

I try to run nuxt auth-routes example but i getting 'Nuxt is not a constructor' error.

OS: macOS 10.12.6
Nuxt: latest (1.0.0-rc4)
Node: 8.3.0

**Comment by yuchonghua** [comment]
Put your first code screenshot, that is, the introduction of nuxt where screenshots, now the introduction of a problem

**Comment by dnomak** [comment]
fixed https://github.com/dnomak/auth-routes

**Comment by Atinux** [comment]
Hi

@dnomak fixed example is nice.

You can also check on `dev` branch the official example, it was up to date when rc was released: https://github.com/nuxt/nuxt.js/tree/dev/examples/auth-routes
