### ISSUE TITLE
bug - this.$router.push doesn't work for the first click where hash is present

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#1367]
Reproduction

1. Click on the link on the page with the hash, eg.:
```<nuxt-link :to="`${postLink(post)}#add-comment-form`">```
Page is changing correctly.

2. After that click on the second link, eg.:
`<a @click="changeCategory(c)">category</a>`
where changeCategory:
```js
    methods: {
      changeCategory (cat) {
        const url = categoryLink(cat)
        console.log('moving to ', url)
        this.$router.push({ path: url })
      }
    },
```
The method is called, the progress bar is animating but the page doesn't change.

3. To change to page I need to click once again on the same link.
The bug is only present when the first link has a # hash at the end. Tested with alfa-4 and rc-4

thanks for help in advance,

**Comment by Atinux** [comment]
Hi @awronski 

Can you make the reproduction by remixing https://glitch.com/edit/#!/nuxt-hello-world please?

**Comment by awronski** [comment]
@Atinux sure

1. Go to https://chivalrous-nail.glitch.me/
2. Click on `Go to About page`
3. Scroll down and click `Go to Second`
4. Nothing happend but progress bar is animating
5. You have to scroll down again and again click on `Go to Second`

glitch.com/edit/#!/join/27184eed-e1c4-4b8d-a644-889c3a261aaf

**Comment by awronski** [comment]
@Atinux did you have any moment to look at it?

**Comment by awronski** [comment]
@Atinux sorry for bother you but this problem is serious for me

I upgraded nuxt to rc.6 but it is still there:
https://nuxt-rc6-route-push-problem.glitch.me/
https://glitch.com/edit/#!/join/27184eed-e1c4-4b8d-a644-889c3a261aaf

**Comment by awronski** [comment]
With rc.7 still the same :(

**Comment by awronski** [comment]
updated to rc.9

https://nuxt-rc9-route-push-problem.glitch.me
https://glitch.com/edit/#!/join/27184eed-e1c4-4b8d-a644-889c3a261aaf

**Comment by Atinux** [comment]
@awronski you need to use `@click.prevent="..."`

**Comment by awronski** [comment]
WOW! Thank you!
