### ISSUE TITLE
including deferred js libraries at bottom of body

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#1370]
Looking at the js src files that nuxt generates they are listed in two groups in the resulting html code. The 'normal' src files are in the header tag and the deferred src files are added at the bottom of the body.

With `this.options.head.script` we are able to add additional js src files to the code, but they are always added to the header tag. It would be nice if we could also add js src files to the bottom of the body, e.g. _after_ the generated `app.js`. 

Maybe even just always add deferred src files at the bottom (but then you are contradicting the `head` part of this.options):
```js
  this.options.head.script.push({
    src: options.scriptUrl || options.piwikUrl+'piwik.js',
    async: true,
    defer: true
  })
```

See #1330 for a use case

**Comment by Atinux** [comment]
Hi @pimlie 

This is a feature related to [vue-meta](https://github.com/declandewet/vue-meta) directly (it's the one we use behind the `head` key).

**Comment by pimlie** [comment]
@Atinux thanks, I understand the idea and/or limitations of using vue-meta but wouldnt it be nice if we could add our own scripts on the following line as well? https://github.com/nuxt/nuxt.js/blob/127155d61a2c6543d698a969f6d06daf43109fe6/lib/core/renderer.js#L455

**Comment by alexchopin** [comment]
Hi, you can use [document](https://nuxtjs.org/guide/views#document) to add script at the bottom of the page.

**Comment by igorify** [comment]
@alexchopin and @Atinux what about the question to make this line of code 
`APP += context.renderScripts() ` configurable from `nuxt.config.js`

Please look at this issue #2822
