### ISSUE TITLE
Types for defineNuxtPlugin and nuxtApp

### ISSUE THREAD

**Issue by abarke** [nuxt/nuxt.js#13714]

**Comment by wovasteenGova** [comment]
> ```js
> nuxtApp 
> ```

` ERROR  Cannot start nuxt:  defineNuxtPlugin is not defined ` 
when trying to use font-awsome
https://fontawesome.com/docs/web/use-with/vue/use-with

**Comment by robinscholz** [comment]
@danielroe I've looked for the export of `defineNuxtPlugin` for quite a while. Would be great if it could be mentioned somewhere in the docs!

**Comment by levalencia** [comment]
I still have the same issue: my vuetify.ts plugin

```
// plugins/vuetify.js
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'


export default defineNuxtPlugin(nuxtApp => {
  const vuetify = createVuetify({
    ssr: true,
    components,
    directives,
  })

  nuxtApp.vueApp.use(vuetify)
})
```

warning:  Cannot find name 'defineNuxtPlugin'.ts(2304)

how can I setup the auto imports? I am using nuxt3, vue3 and vuetify

**Comment by danielroe** [comment]
Make sure you have not overridden or changed the `tsconfig.json` that is included in the Nuxt starter template.

**Comment by frederikheld** [comment]
How would I go about this?

```js
export default defineNuxtPlugin((nuxtApp) => {
  onBeforeMount(() => {
    doSomething(nuxtApp)
  })
})

function doSomething(nuxtApp) {
  // do something with nuxtApp here
}
```

VSCode complains "Parameter 'nuxtApp' implicitly has an 'any' type.ts(7006)" in `doSomething()`

**Comment by danielroe** [comment]
you import the type of NuxtApp from #app

**Comment by frederikheld** [comment]
Ah, kk, thanks for the reminder. The mighty magic of Nuxt. I can't wrap my head around those magic imports in Nuxt. It's so obscure. I tried to import it from `nuxt`
