### ISSUE TITLE
Add support for alias on definePageMetadata composable

### ISSUE THREAD

**Issue by vis97c** [nuxt/nuxt.js#13727]
Adding this issue to track an improvement over pages functionality.

The reason for this feature is that I'm using translation on a project and I also want to translate the routes using aliases. Since this is a feature that already exist on the vue-router it made a lot of sense for me to implement it.

Sorry for my bad english and thanks for this amazing project

**Comment by ankenu** [comment]
How do I make `router.replace` for a page with `alias` in `definePageMeta`?
The replace only works for `path` from `definePageMeta`.
Is there any way to fix this?
