### ISSUE TITLE
ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#1372]
Guys, I have a custom folder structure and code organization of nuxt.js usage, and when I test update nuxt to rc4 - I have a exception ECONNREFUSED 127.0.0.1:80. Who was fire this exception and why port - 80, when I use a custom port?

![image](https://user-images.githubusercontent.com/2588730/29277975-10fb67f6-811c-11e7-840f-b7e9c663ded0.png)

![image](https://user-images.githubusercontent.com/2588730/29277992-1ad3c048-811c-11e7-9cbc-fe82774f0511.png)

**Comment by pi0** [comment]
Hi. This is an SSR error where you are trying to do a ajax request to an unreachable api endpoint.

**Comment by ruslankonev** [comment]
Thanks Pooya, I found — this is a wrong axios options with breaking changes in nuxt@rc4 `process.BROWSER_BUILD -> process.browser`. By the way, with change of aliases `~plugins -> ~/plugins` this changes only in scripts sections? Same code change in `<style>` section will throw exception -> `not found`
