### ISSUE TITLE
Doesn't bind to 0.0.0.0

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1375]
Hello. I am truying to run `npm run dev --host 0.0.0.0` but receive an error

```
> No `pages` directory found. Did you mean to run `nuxt` in the parent (`../`) directory?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

How to make nuxt dev server available on local network for testing?

**Comment by pi0** [comment]
Hi. Please use environment variable `HOST` instead like this `HOST=0.0.0.0 npm run dev`

https://nuxtjs.org/faq/host-port

**Comment by iamdubx** [comment]
Sorry, but this doesn't solve my issue! I don't need to change host address, I need to bind it to listen 0.0.0.0 so I can access it from phone!

**Comment by pi0** [comment]
It is the same. Changing the host will make Nuxt listening to all interfaces & thus site is accessible using the phone on same local network. Please try it and if it's not working we can help you further :)

**Comment by iamdubx** [comment]
Yes, you are right @pi0  my bad. Thank you!
