### ISSUE TITLE
Cannot read properties of null (reading 'insertBefore')

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/nuxt.js#13766]

**Comment by danekslama** [comment]
@danielroe we experienced similar issue with element-plus as well - to be specific with the el-dialog component. The reproduction you made starts working as soon as you remove the parent element of those two spans. I tried to figure out the cause but I have no clue why it starts working as soon as you do this.


Working example:
```
 <div>
    <span v-if="address"></span>
    <span v-else>Nothing here</span>
  </div>
```

Not working:
```
 <div>
    <span v-if="address"></span>
    <span v-else>Nothing here</span>
  </div>
```

**Comment by danielroe** [comment]
@danekslama That sounds like a vue (or element-plus) bug. See if you can reproduce on https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter.

**Comment by danekslama** [comment]
@danielroe after Vue update to 3.4.15 it started working. Unfortunately it still doesn't work on production - same issue. It is kinda difficult to reproduce now, I will try to discuss the issue elsewhere but it seems that it has been reported many times on element-plus. Hopefully, someone solves it soon.

**Comment by danekslama** [comment]
@danielroe after Vue update to 3.4.15 it started working. Unfortunately it still doesn't work on production - same issue in some cases. It is kinda difficult to reproduce now, I will try to discuss the issue elsewhere but it seems that it has been reported many times on element-plus. Hopefully, someone solves it soon.
