### ISSUE TITLE
Nuxt 3 prefetch all assets from every pages and every layouts.

### ISSUE THREAD

**Issue by kstraszewski** [nuxt/nuxt.js#13778]
### Environment

Nuxt CLI v3.0.0-rc.0
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.0`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/kstraszewski/nuxt3-playground/tree/prefetching-all-assets

Also we have qa version of our project here:
https://b2c.qa2.lendi.pl/design

### Describe the bug

Nuxt after build prefetch all the assets like CSS, fonts, media, imgs from all the pages and all the layouts. As you can see in the repo example you have `/pageA` which implement `layout-a`, with some video in the pageA.vue. Also, you have `/pageB` which implements `layout-b` which loads popular [@mdi/font](https://www.npmjs.com/package/@mdi/font). 

The problem I have is it doesn't matter on which page you go nuxt always loads all the assets. When you go to `/pageA` you will see the mdi fonts from pageB and layoutB also are prefetching by the nuxt:

PageA:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10195995/164307955-94b3b43f-61a0-424f-a60c-b2041eb642bf.png">

PageB:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10195995/164308103-7a653d1b-6ba9-432a-88cd-d19e07db14f4.png">

Both pages Loads a lot.

My guess is that vite builder prefetch every URL that he find in CSS or template.

### Additional context

It makes nuxt unusable in production mode because It hurts LCP very badly:

As you can see on the example below we have huge LCP (I've made some tricks witch mdi/fonts, but this is very ugly solution) with fully loaded mdi/fonts I've received 27 sec of LCP.

https://pagespeed.web.dev/report?url=https%3A%2F%2Fb2c.qa2.lendi.pl%2Fdesign

**Comment by mirash333** [comment]
Any update ?

**Comment by manniL** [comment]
@mirash333 when an issue is closed, it usually won't receive any updates. Feel free to follow along https://github.com/nuxt/nuxt/issues/18376

**Comment by rathahin** [comment]
Production is a real challenge for me. Why is it necessary to thoroughly scan all assets, and why can't we make updates directly in the production environment? Why does even a minor change to a single image require a full rebuild?

**Comment by anthonypillot** [comment]
Idk if it can help, [but if you are using `vite` and Nuxt 3, you can check this solution](https://stackoverflow.com/questions/74328212/how-to-extract-css-as-a-separate-css-file-in-vite):

```
  vite: {
    build: {
      cssCodeSplit: false,
    },
  },
```

> If you'd rather have all the CSS extracted into a single file, you can disable CSS code splitting by setting build.cssCodeSplit to false.

However, with `webpack` (Nuxt 2) :

```
  webpack: {
    extractCSS: true,
  }
```

**Comment by beom-lk** [comment]
any update?

**Comment by carbdias** [comment]
I would like to know if this is possible in Nuxt 3 :

router: {
    prefetchLinks: false
}

**Comment by marcos-vinicius-dev** [comment]
> I have the same issue with nuxt bridge and vite.
> 
> env
> 
> * ssr: false
> * target: static

same mistake. Did you get any solution?

**Comment by jschroeter** [comment]
Having the same issue, some video files get prefetched. I would like to prevent that as the videos are initially not visible on the page and only gets visible once the user clicks the preview. Also the user only needs one of the file formats, not mp4 and webm.

The component on the page has a slot where we provide the video sources:
<img width="496" src="https://github.com/nuxt/nuxt/assets/487046/e87ef4eb-e76c-4d60-844d-cb8a50b85848">
But the VideoOverlay component only renders these when the user clicks. Meaning the SSR-rendered HTML doesn't include the `<source>` tags, but still the files get prefetched:

<img width="753" src="https://github.com/nuxt/nuxt/assets/487046/cdd86db8-6701-4197-aaf8-63eb9bfdc148">

**Comment by danielroe** [comment]
@jschroeter You can use the `build:manifest` hook to disable preloading/prefetching of those resources.

**Comment by myl303** [comment]
nuxt3,nuxt.config.ts.Just have a try,It is work for me.


hooks: {
    "build:manifest": (manifest) => {
      const keysToRemove = [];
      for (const key in manifest) {
        const file = manifest[key];
        // console.log("-----", file);
        //all file stop prefetch；
        file.preload = false;
        file.prefetch = false;
      }
    },
  },

**Comment by jschroeter** [comment]
Yes, that works, thanks.

But I have the feeling it would be better if the Nuxt prefetching behavior would be adjustable from e.g. inside the template. E.g. look at this example: https://stackblitz.com/edit/nuxt-starter-qw2rgq?file=app.vue
```
    <picture>
      <source srcset="~/assets/nuxt.avif" type="image/avif" />
      <source srcset="~/assets/nuxt.webp" type="image/webp" />
      <img src="~/assets/nuxt.png" />
    </picture>
    <video>
      <source src="~/assets/nuxt.mp4" type="image/mp4" />
      <source src="~/assets/nuxt.webm" type="image/webm" />
    </video>
```
which results in
```
<link rel="prefetch" as="image" type="image/png" href="/_nuxt/nuxt.BkOrghPF.png">
<link rel="prefetch" as="video" href="/_nuxt/nuxt.DwnW1OXI.mp4">
<link rel="prefetch" as="video" href="/_nuxt/nuxt.Kwi2KNf4.webm">
```
In this example it doesn't make sense that the PNG image and both videos are prefetched.
