### ISSUE TITLE
Cannot install nuxt-start 1.0.0-rc4

### ISSUE THREAD

**Issue by baocancode** [nuxt/nuxt.js#1378]
Hi,

When I run `npm install nuxt-start`, it throws the following error:

npm ERR! enoent ENOENT: no such file or directory, chmod '<some-path>/node_modules/nuxt-start/bin/nuxt'

That is because in the file `start/package.json` you have a bin entry as `"nuxt": "./bin/nuxt"`. I think it should be `"nuxt-start": "./bin/nuxt-start"`. Can you fix that and publish nuxt-start again? Thanks.

**Comment by Atinux** [comment]
https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc5

**Comment by baocancode** [comment]
Thanks, all good now.
