### ISSUE TITLE
Unable to disable Vite HMR

### ISSUE THREAD

**Issue by sharifzadesina** [nuxt/nuxt.js#13811]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Doesn't matter.

### Describe the bug

Hello,

```js
export default defineNuxtConfig({
  vite: {
     server: {
       hmr: false
     }
  },
});
```

This config is supposed to disable HMR, but when merging it seems it doesn't respect the `hmr: false` value and just uses the default config.

**Comment by SebbeJohansson** [comment]
@danielroe sorry to revive an old thread, but I wasn't able to find any other issue with this. Disabling vite hmr doesn't seem to be possible. Tested it with a completely new project and with
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  vite: {
     server: {
       hmr: false
     }
  },
})
```
and it keeps running.
![image](https://github.com/nuxt/nuxt/assets/5083273/1bd0933e-ba1e-4b13-8d33-05eeed365635)

**Comment by danielroe** [comment]
Vite doesn't fully disable the hmr integration. You can see more at https://github.com/vitejs/vite/pull/2474

**Comment by SebbeJohansson** [comment]
@danielroe Thanks for the update! That completely explains the behaviour i am seeing.
Hopefully ngrok will eventually start working so i dont have to try to disable hmr 😅

**Comment by cmuav** [comment]
If anyone comes across this in the future, you can actually disable Vite HMR by placing this in your `nuxt.config.ts`:

```ts
hooks: {
    'vite:extendConfig'(config, { isClient }) {
      if (isClient && config.server) {
        config.server.hmr = false
    }
  }
},
```
