### ISSUE TITLE
Navigation fails if pages do not have single root element

### ISSUE THREAD

**Issue by henningko** [nuxt/nuxt.js#13828]

**Comment by bugproof** [comment]
Bumping this old closed issue just out of curiosity why can't nuxt tooling automatically add this root element if it doesn't exist? Would provide a much better developer experience and increase code clarity by not having to nest everything so heavily.

**Comment by danielroe** [comment]
@bugproof I'd be up for that, but probably opt-in or with a prompt. we already try to warn user in browser console.
