### ISSUE TITLE
What is the best way to access this.$router.push() / router.push() inside the Vuex?

### ISSUE THREAD

**Issue by gtso86** [nuxt/nuxt.js#1384]
This seems a silly question but I'm really struggling right now to accomplish a simple `router.go('/')` inside `store/index.js`. Basically I want to change the page after I complete the authentication. I'm using this [example](https://nuxtjs.org/examples/auth-routes) as base.

I know `const router = require('~router');` isn't working anymore since rc-3 removed the alias to `~router`.

I tried access `this.$router` but isn't available either. I also tried `import router from 'vue-router';` with no luck :(

---

Here a partial of my `store/index.js`:
```js
export const actions = {
  // Login
  async login({ commit }, { email, password }) {
    await axios.post('/api/account/login', {
      email,
      password,
    })
      .then((response) => {
        console.log('response:', response);

        if (response.status === 200) {
          console.log('>> Login successfull');
          commit('SET_USER', response.data);
          sessionStorage.setItem('user', JSON.stringify(response.data));

          //I can't make work!
          Router.push('/about');
        } else if (response.status === 204) {
          console.log('>> Username password do not match');
        } else {
          console.log('>> Username does not exists');
        }
      })
      .catch((error) => {
        commit('SET_USER', null);

        console.log('OPS!');
        console.log(error);
      });
  },
};
```

I appreciate any help... Thanks in advance!

**Comment by gtso86** [comment]
Well, looks like I figure out a way BUT I don't know if is the best one:

Inside my `login.vue` file I added **finally_statements**

```js
    methods: {
      async clickLogin() {
        console.log('Start login process...');

        try {
          await this.$store.dispatch('login', {
            email: this.login.email,
            password: this.login.password,
            router: this.$router,
          });

          this.login.error = null;
        } catch (error) {
          this.login.error = error.message;
        } finally {
          this.$router.push('/');
        }
      },
    },
```

**Comment by uptownhr** [comment]
yea, it's probably best that you include your .push commands outside your actions. 

In the future though this.$router may become available inside your actions. We are waiting on vuex to allow for this in their next release.

**Comment by gtso86** [comment]
Hey @uptownhr , could you give me a example?

**Comment by uptownhr** [comment]
@gtso86 very similiar to your second approach that you weren't sure about. I believe that is the right way to do it. 

As I mentioned though, in the future you would be able to configure vuex to have $router inside actions. For the time being, if you really want router, you can pass it in to your dispatch call. 

this.$store.dispath('login', {router: $this.router})

**Comment by stursby** [comment]
@gtso86 I've also found that you can access the router in your Vuex store by calling the following:

```javascript
this.app.router.push('/')
```

**Comment by polyaha** [comment]
try :  		$nuxt._router.push('/about')

**Comment by jamesAtcodeninja** [comment]
@polyaha  `$nuxt.$router.push` worked for me, but where is the global `$nuxt` object documented?

**Comment by johnyluyte** [comment]
Same as @jamesAtcodeninja , `$nuxt.$router.push` worked for me while `this.app.router.push('/')` does not. 

@polyaha Would you kindly point out where the document is? I cannot find it on the Nuxt API either.

**Comment by charmz** [comment]
this._router.push worked for me. Is there an issue in accessing the router like this?

**Comment by MohammadSabbagh** [comment]
you need to import router then use it without this.$
`import router from './router'
const actions = {

  goto ({ commit , dispatch}, payload) {
    router.push({ path: payload.Redirect})
  },
}
`
