### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"

### ISSUE THREAD

**Issue by chaule97** [nuxt/nuxt.js#13850]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `latest`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Can't run after build project

### Describe the bug

After I run `npm run build` and `npm run start` then I have a trouble
```
> start
> node .output/server/index.mjs

Listening on http://0.0.0.0:3000/
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"
```

I don't know reason, it's my package.json

```
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "generate": "nuxi generate",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@intlify/nuxt3": "^0.1.10",
    "@nuxt/types": "^2.13.2",
    "@nuxt/typescript-build": "^2.1.0",
    "@types/jquery": "^3.5.14",
    "@vue/cli-plugin-typescript": "~5.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^10.0.0",
    "eslint": "^8.14.0",
    "eslint-plugin-vue": "^8.7.1",
    "nuxt3": "latest",
    "sass": "^1.50.0",
    "sass-loader": "^12.6.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-brands-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/vue-fontawesome": "^3.0.0-5",
    "@pinia/nuxt": "^0.1.8",
    "@popperjs/core": "^2.11.5",
    "@vueuse/core": "^8.3.1",
    "bootstrap": "^5.1.3",
    "express": "^4.18.0",
    "gsap": "^3.10.4",
    "jquery": "^3.6.0",
    "nuxt-start": "^2.15.8",
    "pinia": "^2.0.13",
    "vue": "3.2.33",
    "vue-router": "^4.0.14"
  }
}

```

**Comment by danieldanielecki** [comment]
I have a similar issue after not doing completely anything, but it related to no match found of `nuxt/dist/app/null (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)`.

**Comment by s1mpLyy** [comment]
![Image](https://github.com/user-attachments/assets/7379ad26-9cb2-464f-94bb-b5d1ecabe101)

![Image](https://github.com/user-attachments/assets/b93956c0-ee20-4906-a7d7-a7f214096760)

issue still alive 


my package.json 

"dependencies": {
    "@nuxt/eslint": "^0.7.2",
    "@nuxt/image": "^1.0.0-rc.2",
    "@nuxt/nitro": "^0.10.0", 
    "@nuxtjs/sentry": "^7.5.0",
    "@pinia/nuxt": "^0.4.11",
    "@sentry/browser": "^7.85.0",
    "@sentry/tracing": "^7.76.0",
    "@sentry/webpack-plugin": "^2.9.0",
    "autoprefixer": "^10.4.16",
    "eslint": "^9.17.0",
    "nuxt": "^3.16.2",
    "pinia": "^2.1.6",
    "tailwindcss": "^3.3.3",
  },****

**Comment by s1mpLyy** [comment]
Issue fixed by removing the definePageOptions({})
