### ISSUE TITLE
[internals] improve options module

### ISSUE THREAD

**Issue by shirohana** [nuxt/nuxt.js#1385]
Hello,

Since using default export of `Options` as option initializer, I have a question that is it a good way to use a Class-like naming style to name a function?

I found members in `options.js` like `Modes` and `defaultOptions` are also put in `Options` now, maybe leave `Options` as a pure Object, and rename the init function to `Options.from(_options)` is a better choice?

https://github.com/nuxt/nuxt.js/blob/d7d85d3b4763eacf4a25155c08a01fab3ee5746a/lib/core/nuxt.js#L18

**Comment by Atinux** [comment]
Ping @pi0

**Comment by pi0** [comment]
@shirohana Yeap you are right. Indeed it would be even better-converting Options to a class like other nuxt internals. Anyway, that's an internal enhancement. PRs welcome :)

**Comment by shirohana** [comment]
I think this should be closed :)
