### ISSUE TITLE
environment variables not working

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt.js#1386]
my nuxt.config.js 

```js
require('dotenv').config()

module.exports = {

  env: {
    API: process.env.API || 'http://localhost:8000',
    test: 'ting',
  },

  /*
   * Router config
   */
  router: {
    middleware: 'auth'
  },
```

a console.log of `process.env` on any page or my `plugins/axios.js` always shows `{}`

**Comment by rAugustos** [comment]
Hi @acidjazz 

nuxt.config.js
```
require('dotenv').config()

module.exports = {

  env: {
    API: process.env.API || 'http://localhost:8000',
    test: 'ting',
  },

  /*
   * Router config
   */
  router: {
    middleware: 'auth'
  },
```

**pages/index.vue**

```
<template>
<div>
<h2>Env propety</h2>
<pre>{{this.API}} and {{this.test}}</pre>
</template> 

<script>
export default{
  asyncData (context) {
    return context.env
  }
}
</script>
```


You can read  https://nuxtjs.org/api#context

**Comment by uptownhr** [comment]
@acidjazz yea nuxt i believe uses webpack resolve to translate process.env.param. process.env is actually not set and unfortunately displays {}. However, if you directly call the param within env, you'll get your value.

**Comment by acidjazz** [comment]
@uptownhr thats so mind-boggling.. why would i get {} but directly get my variable?

**Comment by pi0** [comment]
@acidjazz Actually that's a strange behavior from web pack (possibly because of it's shimming process)

@uptownhr Thanks for the point. I think that would be useful for all users, making a PR to docs to mentioning this tip in env section would be nice :)

**Comment by acidjazz** [comment]
@pi0 maybe keep this open to tie to the PR until the documentation is up for people to find? might help avoid more issues made.
