### ISSUE TITLE
listening on <nuxt-child> possible to pass events from nested routes?

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#1387]
is it possible to add event handlers to nuxt-child and fire events from nested pages? 

nested.vue
```
<template>
  <nuxt-child @something="handle_something" />
</template>
```

nested/index.vue
```
<template>
  <button @click="$emit('something!')" >something</button>
</template>
```

**Comment by motia** [comment]
I am using this and did not notice any problem with it. Also, props appear work fine.

**Comment by alexchopin** [comment]
Should be `$emit('something')` not `$emit('something!')` in nested/index.vue.
