### ISSUE TITLE
How do I stop switching off the terminal service?

### ISSUE THREAD

**Issue by xufengzi** [nuxt/nuxt.js#1388]
After the Nuxt project is released, it runs on the Lunix server. When the NPM start is executed, the terminal is turned off, and the service is stopped. How can we solve this problem?

**Comment by pi0** [comment]
@xufengzi Would you please send terminal errors? If your terminal force closes there should be an `npm.*.log` file in your project (possibly hidden) so you can check it too.

**Comment by xufengzi** [comment]
There is no error log, it is the terminal shutdown and the process is stopped. I want to know how your nuxt project is running on the Linux server and running it in the background？ Just NPM start is OK?

**Comment by xufengzi** [comment]
@pi0  Thank you very much. The problem has been settled.
