### ISSUE TITLE
router path /index throw 404 not expected to /

### ISSUE THREAD

**Issue by alterhu2020** [nuxt/nuxt.js#1389]
## Test Data:
1. Create the root home page component in pages folder ,named it as: index.vue
##  Steps:
1. start nuxt server, then go to page : http://localhost:3000/
2. go to page : http://localhost:3000/index

## Expected result:
1. For step2 it should  render the same page content as step1, go to path `/`
## Actual result:
1. For step2 it will show as 404 exception：
```
404
This page could not be found.

URI Path: /index
Back to the home page
```

I don't want to create a new folder called `index` at the root pages ,any help for this ? 
thanks .

**Comment by pi0** [comment]
Hi. This an expected behavior (At least currently).Adding an alias for `/` ~> `/index` is not a good practice and needs creating duplicate route entries for all `index.vue` files in `router.js`.

**Comment by alterhu2020** [comment]
thanks for  your quick response @pi0 ,so do you have any suggestion for this case ? I really don't want to create a same name router folder for each router path. We just want to the it could be like as following:

```
--  pages
--- index.vue
--- about.vue
--- contact.vue
```
thanks a lot, we really like the nuxtjs project.

**Comment by bayssmekanique** [comment]
You could use a sym-link to prevent you from having to duplicate the file and then just create the directory with the sym-link in it (`/index/index.vue -> /index.vue`).

**I haven't tested this**, but you could potentially use the dynamic routing to make this work.  You'd create a file called `_index.vue` in the root, and then in the configuration for that file declare the `validate` function to test that the route is `index` or blank.
```
export default {
  validate ({ params }) {
    return /^index$/.test(params.id) || params.id === null
  }
}
```

**Comment by alterhu2020** [comment]
thanks @bayssmekanique ,The problem is that When i use the `<nuxt-link to='index'>` to navigate to the root path(`http://localhost:3000/`) ,but it navigate to `http://localhost:3000/index/` . that confused me a lot ,see the generated router.js file for this root router path name: `/.nuxt/router`
```

export function createRouter () {
  return new Router({
    mode: 'history',
    base: '/',
    linkActiveClass: 'nuxt-link-active',
    linkExactActiveClass: 'nuxt-link-exact-active',
    scrollBehavior,
    routes: [
		{
			path: "/",
			component: _2b8110ef,
			name: "index"
		},
		{
			path: "/uploader",
			component: _49b83161,
			name: "uploader"
		},
		{
			path: "/about",
			component: _0bc9362a,
			name: "about"
		},
		{
			path: "/login",
			component: _15ae97f4,
			name: "login"
		}
    ],
    fallback: false
  })
}
```

**Comment by bayssmekanique** [comment]
Sorry, I guess I completely miss-understand what you are asking.  To route to the index file, you would use `<nuxt-link to="/">`.

**Comment by alterhu2020** [comment]
thanks @bayssmekanique , Your reminder let me to go throuth the vue-router document ,and I found that i misunderstand the `to` parameter in `nuxt-link` ,it mentioned that the parameter could be a string or a object. the `string` is worked for the router's `path` property ,but if we want to use the router's name instead of router's path ,we should define the `to` as a object ,like below code:
```
<nuxt-link :to='{name: 'index'}'
```
It's totally my fault. thanks for your help @bayssmekanique , @pi0
