### ISSUE TITLE
Navigating to a url with query string gets redirected to a url stripped off the query

### ISSUE THREAD

**Issue by sduduzog** [nuxt/nuxt.js#13899]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `npm@8.6.0`
- Builder:          `vite`
- User Config:      `postcss`, `css`, `vite`, `runtimeConfig`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- Simply start the dev server
- Navigate to http://localhost:3000/?test=foo

You'll notice that you're redirected back to http://localhost:3000

### Describe the bug

- Simply start the dev server
- Navigate to http://localhost:3000/?test=foo

You'll notice that you're redirected back to http://localhost:3000 which shouldn't happen as this makes for unexpected behavior from the site.

Callbacks from 3rd party providers pass through crucial data via query params and the app is unable to capture them

**Comment by ekrausso** [comment]
I'm using a route middleware to redirect users with `navigateTo()`
It seems that it strips off the query on chrome but works without issue on firefox 

trying to access 'http://localhost:3000/?message=test' will redirect to '/home' and strip the query off in chrome

on firefox it redirects to 'http://locahost:3000/home?message=test' 

basically doing this:
```
export default defineNuxtRouteMiddleware( to => {
    if(process.client) return

    if(to.path !== '/home') return navigateTo('/home')
})
```

chrome version:  110.0.5481.177 (Official Build) (64-bit)

**Comment by danielroe** [comment]
The query should not persist when using `navigateTo` unless you explicitly include it. On firefox either. (And I can't replicate.)

**Comment by ekrausso** [comment]
Hi @danielroe !
This isnt working for me on chrome either...  when logging useRoute().query its an empty string..

It works however in an incognito window... and I can access the query with useRoute().query...
I think it has to do with browser cache or how chrome prefetches resources when you're typing an url ??

accessing 'http://localhost:3000/?id=0915200234&dactilar=V2344V'

```
export default defineNuxtRouteMiddleware( to => {
    if(process.client) return
    console.log("to: ", to)
    if(to.path !== '/home') return navigateTo({path: '/home', query: useRoute().query})
})
```


Output for 'to' when accessed from a normal window is only the 'new' route and redirectedFrom is undefined:
```
to:  {                                                                                                                        09:43:34
  fullPath: '/home',
  hash: '',
  query: {},
  name: 'home',
  path: '/home',
  params: {},
  matched: [
    {
      path: '/home',
      redirect: undefined,
      name: 'home',
      meta: [Object],
      aliasOf: undefined,
      beforeEnter: undefined,
      props: [Object],
      children: [],
      instances: {},
      leaveGuards: Set(0) {},
      updateGuards: Set(0) {},
      enterCallbacks: {},
      components: [Object]
    }
  ],
  meta: { layout: 'landing', middleware: [ [AsyncFunction (anonymous)] ] },
  redirectedFrom: undefined,
  href: '/home'
}
```



Output for 'to' from an incognito window both routes are logged and redirectedFrom has previous route info with query:
```
to:  {                                                                                                                        09:40:55
  fullPath: '/?id=0915200234&dactilar=V2344V',
  hash: '',
  query: { id: '0915200234', dactilar: 'V2344V' },
  name: 'index',
  path: '/',
  params: {},
  matched: [
    {
      path: '/',
      redirect: undefined,
      name: 'index',
      meta: [Object],
      aliasOf: undefined,
      beforeEnter: undefined,
      props: [Object],
      children: [],
      instances: {},
      leaveGuards: Set(0) {},
      updateGuards: Set(0) {},
      enterCallbacks: {},
      components: [Object]
    }
  ],
  meta: { layout: 'landing', middleware: [ [AsyncFunction (anonymous)] ] },
  redirectedFrom: undefined,
  href: '/?id=0915200234&dactilar=V2344V'
}


to:  {                                                                                                                        09:40:55
  fullPath: '/home?id=0915200234&dactilar=V2344V',
  hash: '',
  query: { id: '0915200234', dactilar: 'V2344V' },
  name: 'home',
  path: '/home',
  params: {},
  matched: [
    {
      path: '/home',
      redirect: undefined,
      name: 'biometria',
      meta: [Object],
      aliasOf: undefined,
      beforeEnter: undefined,
      props: [Object],
      children: [],
      instances: {},
      leaveGuards: Set(0) {},
      updateGuards: Set(0) {},
      enterCallbacks: {},
      components: [Object]
    }
  ],
  meta: { layout: 'landing', middleware: [ [AsyncFunction (anonymous)] ] },
  redirectedFrom: {
    fullPath: '/?id=0915200234&dactilar=V2344V',
    hash: '',
    query: { id: '0915200234', dactilar: 'V2344V' },
    name: 'index',
    path: '/',
    params: {},
    matched: [ [Object] ],
    meta: { layout: 'landing', middleware: [Array] },
    redirectedFrom: undefined,
    href: '/?id=0915200234&dactilar=V2344V'
  },
  href: '/home?id=0915200234&dactilar=V2344V'
}
```
