### ISSUE TITLE
Excessive stack depth comparing types 'NuxtModule<ModuleOptions>' and 'NuxtModule<ModuleOptions>' + Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt/nuxt.js#13897]

**Comment by reslear** [comment]
problem is back 
<img width="602" alt="Screenshot 2023-02-06 at 16 27 24" src="https://user-images.githubusercontent.com/12596485/217012867-90336556-73c1-4ce7-9827-e556d2ddf2ec.png">

**Comment by danielroe** [comment]
Would you open a new issue with a reproduction? 🙏

**Comment by xrayian** [comment]
Just faced this after installing and uninstalling the robots module
![image](https://user-images.githubusercontent.com/54111411/218719599-de4a006a-9ccd-43d4-95ba-814cd8d33a21.png)

**Comment by xrayian** [comment]
Removing the `nuxt-seo-kit` package removed the error for the time being.
What am I supposed to do here?

**Comment by reslear** [comment]
@xrayian move this issue to nuxt-seo-kit package

**Comment by danielroe** [comment]
Would you try on `nuxt-edge`? We're doing something different with module types that I hope might resolve this kind of thing too...

**Comment by xrayian** [comment]
After updating to nuxt 3.2 this issue fixed by itself.

**Comment by devilmark84** [comment]
After `nuxt v.3.2.3` and newer the problem appears again... https://github.com/nuxt/nuxt/issues/20159

**Comment by annymosse** [comment]
`nuxt v 3.7.1`  while  doesn't exist in `nuxt v 3.7.0`

**Comment by danielroe** [comment]
I suspect you have multiple versions of nuxt/schema or kit installed. Try running `npx nuxi upgrade --force` to refresh your lockfile.

**Comment by matteomejia** [comment]
Issue is happening in `nuxt v 3.7.3` with package `@dargmuesli/nuxt-cookie-control`.

**Comment by Ev357** [comment]
I just `rm -rf node_modules` and `bun i`, :)
