### ISSUE TITLE
how i do use package vuelidate in nuxt.js?

### ISSUE THREAD

**Issue by daosonit** [nuxt/nuxt.js#1391]
File nuxt.config.js . I declare:
```
  plugins: [
     {src: '~/plugins/vuelidate.js', ssr: true}
  ]

```
and in file login.vue 
```
<div class="form_item">
          <i class="li-user"></i>
          <input v-model="formLogin.email" class="form-control" placeholder="email"
                :class="{'has_error': $v.formLogin.email.$error}"
                 @input="delayTouch($v.formLogin.email)"/>
        </div>
        <div class="form_item">
          <i class="li-key"></i>
          <input v-model="formLogin.password" type="password" class="form-control" 
           placeholder="password"
                 :class="{'has_error': $v.formLogin.password.$error}"
           @input="delayTouch($v.formLogin.password)"/>
        </div>
```
when running, vue warning.
`[Vue warn]: Computed property "$error" was assigned to but it has no setter. (found in <Root>)`

Who can help me!  or How to do otherwise

**Comment by xufengzi** [comment]
@daosonit 
1.You need to install first， npm install vuelidate --save
2.In the plugins file, add the following new file vuelidate.js to add the following
```
import Vue from 'vue'
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)
```
File nuxt.config.js
```
plugins: [
     {src: '~/plugins/Vuelidate.'}
  ]
```
That's all right.

**Comment by daosonit** [comment]
Thanks @xufengzi, in file nuxt.config.js, i write` {src: '~/plugins/vuelidate.js', ssr: false}` 
and file .vue, i check 
```
<template>
       <div class="form_item" v-if="isBrowser">
          <i class="li-user"></i>
          <input v-model="formLogin.email" class="form-control" placeholder="Tài khoản ứng viên"
                 :class="{'has_error': $v.formLogin.email.$error}"
                 @input="delayTouch($v.formLogin.email)"/>
        </div>
</templte>
export default {
   async asyncData () {
      return {isBrowser: process.browser}
    },

    mounted () {
      this.fetchData()
      this.isBrowser = process.browser
    }
}
```
mean. is browser i start render view.

**Comment by michaelpumo** [comment]
I am getting a similar issues (Vuelidate 0.5.0):

**Component:**

```
import { required, number } from 'vuelidate/lib/validators'
export default {
  name: 'AgeGate',
  data () {
    return ({
      day: '',
      month: '',
      year: '',
      isBrowser: false
    })
  },
  mounted () {
    this.isBrowser = process.browser
  },
  validations: {
    day: {
      required,
      number
    },
    month: {
      required,
      number
    },
    year: {
      required,
      number
    }
  }
}
```

**Plugin:**

```
import Vue from 'vue'
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)
```

**nuxt.config.js:**

```
plugins: [
  { src: '~plugins/vuelidate', ssr: false }
]
```

...

```
build: {
  vendor: [
    'vuelidate'
  ]
}
```

In my **Component Template**, I'm doing something like:

```
<div v-if="isBrowser">
  <input @input="$v.day.$touch()" v-model="day" type="text" placeholder="DD" name="day" id="day" value="" maxlength="2">
  <input @input="$v.month.$touch()" v-model="month"  type="text" placeholder="MM" name="month" id="month" value="" maxlength="2">
  <input @input="$v.year.$touch()" v-model="year"  type="text" placeholder="YYYY" name="year" id="year" value="" maxlength="4">
</div>
```

When a field is touched, the validation updates, but I get errors in the console:

> Uncaught TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at VueComponent.keys (index.js:289)
>     at Watcher.get (vue.runtime.esm.js:2877)
>     at Watcher.evaluate (vue.runtime.esm.js:2984)
>     at VueComponent.computedGetter [as keys] (vue.runtime.esm.js:3261)
>     at VueComponent.proxy (index.js:296)
>     at Watcher.get (vue.runtime.esm.js:2877)
>     at Watcher.evaluate (vue.runtime.esm.js:2984)
>     at VueComponent.computedGetter [as proxy] (vue.runtime.esm.js:3261)
>     at Object.get [as number] (index.js:301)

This doesn't happen on projects built without Nuxt...i.e. just the Vue Cli.

Any ideas what's going on? Or, where _I'm going wrong_?

Is this something to do with `$v` in the templates?

**Comment by arjanvaneersel** [comment]
Having the same issue with Nuxt and vuelidate, so it's obviously not solved yet.
plugins/vuelidate.js:
```
import Vue from 'vue'
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)
```
nuxt_config.js:
```
...
plugins: [
    { src: '~/plugins/vue-material' },
    { src: '~/plugins/vuelidate', ssr: false }
  ],
...
build: {
    /*
    ** Run ESLint on save
    */
    vendor: ['vue-material', 'vuelidate'],
...
```
index.vue:
```
...
methods: {
    getValidationClass: (fieldName) => {
      const field = this.$v.form[fieldName]

      if (field) {
        return {
          'md-invalid': field.$invalid && field.$dirty
        }
      }
    },
...
```
The line `const field = this.$v.form[fieldName]` results in this error: **Cannot read property 'form' of undefined**. Using just `$v.form[fieldName]` (without this) doesn't help, will just get a compiler error that $v is undefined.
Also tried using `validationMixin`, but that also doesn't solve the problem. 

I'm clueless what's causing this problem and why I can't get vuelidate to work in nuxt. I'm having no issues using with pure Vue applications.

**Comment by redijedi** [comment]
I'm also running into this issue, except there is no error message. The UI simply doesn't update on input. @michaelpumo Did you find a solution?
