### ISSUE TITLE
defineEventHandler() is undefined in ~/server/api on Stackblitz

### ISSUE THREAD

**Issue by Lyokolux** [nuxt/nuxt.js#13922]
### Environment

Stackblitz starter template

------------------------------
Nuxt CLI v3.0.0-rc.2 (and Nuxt CLI v3.0.0-rc.1) 
RootDir: /home/projects/nuxt-starter-sh8cyl                                      10:06:48
Nuxt project info:                                                               10:06:48

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sh8cyl?file=server/api/hello.ts

### Describe the bug

The `defineEventHandler()` function used in the `~/server/api` folder is marked as undefined.

Error message: 
`Cannot find name 'defineEventHandler'.(2304)
any`

### Additional context

As stated in the documentation,
>Nuxt exposes every auto-import with the #imports alias that can be used to make the import explicit if needed

`import { defineEventHandler } from '#import';` returns an error too: `Cannot find module '#import' or its corresponding type declarations.`

**Comment by gureenkov56** [comment]
Create file **/server/tsconfig.json** with below object
`
{
  "extends": "../.nuxt/tsconfig.server.json"
}
`
It should help you

**Comment by jstr-loop** [comment]
> 

This worked for me. Should this be the default?

**Comment by blowsie** [comment]
I ran into this when building and installing my own module, however the below did not fix it :(

> Create file **/server/tsconfig.json** with below object `{ "extends": "../.nuxt/tsconfig.server.json" }` It should help you

**Comment by yashwp** [comment]
This is not fixed. I've tsconfig.json inside server. Also, it doesn't work

**Comment by zacwebb** [comment]
For people who are still stumbling across this, I managed to fix it by ensuring that all my type imports are prefixed with the word **type**

e.g. `import { MyType } from 'package';` -> `import type { MyType } from 'package';`

This is required since Nuxt 3.8.0 (see "Type import changes" in [the changelog](https://github.com/nuxt/nuxt/releases/tag/v3.8.0)) and has seemed to solve any issues with the my app not picking up the auto-imported Nuxt/H3 types (such as `defineEventHandler`).

**Comment by adamasantares** [comment]
this case still not clear from docs https://nuxt.com/docs/guide/directory-structure/server#server-middleware

why there are no imports in all examples?

**Comment by danielroe** [comment]
@adamasantares Because Nuxt auto-imports them for you.
