### ISSUE TITLE
useAsyncData can‘t watch slug

### ISSUE THREAD

**Issue by NidMo** [nuxt/nuxt.js#13924]

**Comment by chrisspiegl** [comment]
I found that I can get the slug to update the useAsyncDate by wrapping the route param into a `computed()`

May be a workaround but it does seem to work based on a few test and trials I did.

```js
import { useRoute } from 'vue-router'
const route = useRoute()
const idOrSlug = computed(() => route.params.idOrSlug)
const { data: libraryVideo } = await useAsyncData(() => libraryVideoStore.fetchBySlugOrId(idOrSlug.value), { watch: [idOrSlug] })
```

**Comment by thisismydesign** [comment]
In my case, on Nuxt 2 Bridge,`watch: [route]` resulted in an infinite loop (`RangeError: Maximum call stack size exceeded`).

Could find much on this issue and ended up using the flag workaround: https://stackoverflow.com/a/75952272/2771889

**Comment by ablipan** [comment]
> I found that I can get the slug to update the useAsyncDate by wrapping the route param into a `computed()`
> 
> May be a workaround but it does seem to work based on a few test and trials I did.
> 
> ```js
> import { useRoute } from 'vue-router'
> const route = useRoute()
> const idOrSlug = computed(() => route.params.idOrSlug)
> const { data: libraryVideo } = await useAsyncData(() => libraryVideoStore.fetchBySlugOrId(idOrSlug.value), { watch: [idOrSlug] })
> ```
> 
> I also noticed that things behave differently if I import the `vue-router` manually or if I just try to use the one that get's auto imported. So I included it here.

It seems that the auto-imported `useRoute` is not being updated in time, but the original `useRoute` in `vue-router` is functioning correctly.

**Comment by danielroe** [comment]
Don’t use the one from vue-router. It’s not in sync with the suspended route and you’ll get flickering or issues with suspense.
