### ISSUE TITLE
NuxtLink scrollBehavior broken

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/nuxt.js#13947]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.2-27530889.9e5a3cd`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jiblett1000/nuxt-scroll-test

### Describe the bug

Scroll behavior is completely broken. This seems to be with NuxtLink at least. I've included a regular <a> link in the reproduction to show that scrolling to a href isn't working with NuxtLink.

**Comment by quroom** [comment]
@jshimkoski I am not sure why scrollBehavior not working in my nuxt env.
As you mentioned, the scrollbehavior code works well with settimeout.
Now I feel comfortable :) Thanks a lot!
But I am not sure why it doesn't work.. maybe SSR related?
