### ISSUE TITLE
Very much looking forward to a v1.0.0-rc5

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1394]
Very much looking forward to a v1.0.0-rc5 because, [~assets and ~/ assets](https://github.com/nuxt/nuxt.js/issues/1241) of the use of really troublesome

**Comment by baocancode** [comment]
@pi0 Can you also look at #1378 for v1.0.0-rc5? It is trivial. Thanks.

**Comment by coderPreacher** [comment]
Very much looking forward to a v1.0.0-rc5 because, ~assets and ~/ assets of the use of really troublesome

**Comment by yeziZ** [comment]
Very much looking forward to a v1.0.0-rc5 because, ~assets and ~/ assets of the use of really troublesome

**Comment by Atinux** [comment]
rc5 is out https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc5
