### ISSUE TITLE
Can't resolve imported styles when using 1.0.0-rc4

### ISSUE THREAD

**Issue by mamboer** [nuxt/nuxt.js#1396]
I'm migrating `nuxt` from `0.10.7` to `1.0.0-rc4`,  and encounter two problems.

1. Css modules which were installed via npm could not be parsed properly. 

It complains,

```

This relative module was not found:

* ../../nust-boilerplate/themes/default/gitalk/dist/gitalk.css
```

In fact `gitalk` is located at ` ../../nust-boilerplate/themes/default/node_modules/gitalk/dist/gitalk.css`

2. Imported styles could not be parsed properly

With the code as below in one of my vue components,

```
<style lang="stylus" scoped>
@import 'assets/css/base/_base.styl';
.qrcode-pic
  width: 100%
</style>
```

It complains `failed to locate @import file assets/css/base/_base.styl` when building.

Here is my `nuxt` configs related to styles,

```
module.exports = {
  'css': [
    'highlight.js/styles/github.css',
    'gitalk/dist/gitalk.css',
    { 'src': 'assets/css/main.styl', 'lang': 'stylus' }
  ],
  ...
}
```

**Comment by bayssmekanique** [comment]
For the `@import` issue, try using `/assets` or `~/assets`.

**Comment by pi0** [comment]
Also, imports would be much more easy with rc5 with built-in [resolve-url-loader](https://github.com/bholloway/resolve-url-loader)
