### ISSUE TITLE
Nested Routes: Odd behavior

### ISSUE THREAD

**Issue by jamilabreu** [nuxt/nuxt.js#1397]
Hi all! I'm seeing what looks like a bug related to nested routes. I'm using vue-apollo, and my folder structure under /pages is as follows:

```
index.vue
_community.vue
_community/_post.vue
_community/index.vue
```
When navigating from index.vue -> _community/index.vue -> _post.vue - it works perfectly, with _post appearing via <nuxt-child />

when directly loading _community/index.vue -> _post.vue, or _community/_post -> to another _post.vue, _post.vue itself renders correctly via <nuxt-child /> - but the parent component _community/index.vue loses it's data, so all of it's elements requiring data disappear.

any ideas?

**Comment by alexchopin** [comment]
https://github.com/nuxt-community/apollo-module
