### ISSUE TITLE
`useFetch` does not refresh when a params object is used

### ISSUE THREAD

**Issue by vasisouv** [nuxt/nuxt.js#13982]
### Environment

Linux

### Reproduction

Go to: https://stackblitz.com/edit/github-mt2nv8?file=app.vue

Try to increase the page by pressing the respective button. The same request is performed with each button press.

As described in the sandbox, using the `_start` param as part of the url works properly.

### Describe the bug

The `refresh` function of the `useFetch` composable does not properly refresh requests that depend on params object instead of params in the url itself.

**Comment by chrislee973** [comment]
When the query param is a ref, and the param ref changes, is there a way to prevent the fetch from occurring automatically and instead only fetch when the execute() function is called? See stackblitz: https://stackblitz.com/edit/github-qpqckm?file=app.vue,server%2Fapi%2Fhello.ts

Is there a way to only fetch when the "Fetch" button is clicked and not when the "count" ref is incremented?

**Comment by manniL** [comment]
@chrislee973 Can you create a new issue instead of posting in an old one? ☺️

**Comment by chrislee973** [comment]
sure thing! I think my question is more suited to the Discussions tab so I'll post there.

**Comment by chrislee973** [comment]
> @chrislee973 Can you create a new issue instead of posting in an old one? ☺️


sure thing! I think my question is more suited to the Discussions tab so I'll post there.
