### ISSUE TITLE
Get Full url path in asyncData

### ISSUE THREAD

**Issue by thecodr** [nuxt/nuxt.js#1399]
I have a very strange requirement.
I am using `asyncData` method to fetch data from another microservice. But this microservice responds based on `origin` header. But, when I am using axios in asyncData, there is no origin header available for the microservice. For example, the headers that were sent are,
```
{ accept: 'application/json, text/plain, */*',
  'user-agent': 'axios/0.16.2',
  host: 'localhost:3002',
  connection: 'close' }
```
But ideally, I would need headers this way
```

{ accept: 'application/json, text/plain, */*',
  origin : 'http://example.com',
  'user-agent': 'axios/0.16.2',
  host: 'localhost:3002',
  connection: 'close' }
```
Is there some way of achieving this ?

**Comment by pimlie** [comment]
Have you looked at the axios [documentation](https://github.com/mzabriskie/axios)? The second parameter of the get method allows you to add additional config.

```js
asyncData ({ params }) {
return axios.get('http://microservice', {
  headers: {
    origin: 'http://example.com'
  }
}
```

Or use an axios interceptor to add the origin header to all your requests.
