### ISSUE TITLE
How to add postcss plugins

### ISSUE THREAD

**Issue by PatrikLythell** [nuxt/nuxt.js#14]
I ended up adding them to the postcss array in vue-loader.config.js because I couldn't get it to work.

Is there a better way or should we add a hook to the postcss array?

**Comment by Atinux** [comment]
Can you post your postcss config?

I may add `build.postcss` option in `nuxt.config.js`

**Comment by PatrikLythell** [comment]
Just added postcss-cssnext to vue-loader.config.js inside my nuxt package for giggles. That made the build complain about double autoprefixer though (think it's included in cssnext). 

Think build.postcss in nuxt.config.js would be sweet 👍 

```
'use strict'

module.exports = function () {
  let config = {
    postcss: [
      require('postcss-cssnext')(),
      require('autoprefixer')({
        browsers: ['last 3 versions']
      })
    ],
…
```

**Comment by Atinux** [comment]
This option has been added in [v0.6.7](https://github.com/nuxt/nuxt.js/releases/tag/v0.6.7)

Thank you @PatrikLythell for using Nuxt.js 😄

**Comment by qur2** [comment]
Just for the record, since I spent few hours looking for that, here is the `nuxt.config.js` that worked for me:

```javascript
module.exports = {
  build: {
    postcss: [
      require('postcss-nested')(),
      require('postcss-responsive-type')(),
      require('postcss-hexrgba')(),
    ]
  }
}
```

**Comment by tiagomatosweb** [comment]
That's cool, but seems that any scss file included by CSS array in the nuxt.config.js files is not prefixed.

```
css: [
      { src: '~assets/scss/app.scss', lang: 'scss' },
],
```

My workaround was import the scss file in the layout vue file, like so

<style lang="scss">
    @import "~assets/scss/app.scss";
</style>

Any other better approach?
