### ISSUE TITLE
How to use vue-router's scroll behavior?

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#140]
Can't seem to find a way to use vue-router's scroll behavior functionality with nuxt.js, and tips?

Scroll behavior docs: https://router.vuejs.org/en/advanced/scroll-behavior.html

**Comment by Atinux** [comment]
Hi @jaredreich 

This possibility will be added in the next release via the `router.scrollBehavior` option in the `nuxt.config.js` file.

**Comment by Atinux** [comment]
You can now customise the `scrollBehavior` in the latest release [0.9.7](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.7).
