### ISSUE TITLE
[Kit] Support the method suffix in `addServerHandler`

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt.js#14003]
It would be nice to support the suffix for `addServerHandler`:

```ts
addServerHandler({
  route: '/api/hello',
  handler: resolve('./api/hello.get.ts'),
})
```

Will be same as:

```ts
addServerHandler({
  route: '/api/hello',
  method: 'get',
  handler: resolve('./api/hello.get.ts'),
})
```

See example on https://stackblitz.com/edit/nuxt-starter-gfos9a?file=nuxt.config.ts,module%2Findex.ts,module%2Fapi%2Fhello.get.ts

We do support it for `addPlugin` 😊

**Comment by L422Y** [comment]
FYI, not sure if this is related, but my module (nuxt-dsi) stopped working until I explicitly set the `method` option, even though the filename had the method suffix and had worked fine previously.
