### ISSUE TITLE
how to avoid clearing terminal

### ISSUE THREAD

**Issue by autumnblazey** [nuxt/nuxt.js#14001]
I would like for nuxt to provide an option to not clear the screen on startup / possibly other events. It is especially annoying when I have previous terminal output which I would like to keep, but nuxt just bulldozes over it. Perhaps like [vite does it](https://vitejs.dev/config/#clearscreen)?

**Comment by Meadowsys** [comment]
hm.. it seems `nuxt dev --no-clear` no longer works. I left my project untouched, today upgraded to 3.3.3 (3.4.0 had an issue that prevented me to upgrade to), and noticed that running `pnpm run dev` as I did before started to clear the console on HMR again without me having changed the script.
