### ISSUE TITLE
Read files from folder

### ISSUE THREAD

**Issue by kakulukia** [nuxt/nuxt.js#1400]
Hi, i have a simple question .. since nuxt is server side rendered, it should be possible to read an unknown number of images from a given folder and render an image gallery. But i did not find an example so far on how to do this. Could anyone point me in the right direction? Or is that just not possible with nuxt?

**Comment by bayssmekanique** [comment]
Hello @kakulukia, that's certainly possible, and there are many ways to go about it.  Depending on how often the images in the directory change (and how many there are), it might make more sense to have a service that indexes the files ahead of time and then returns a `json` file at run time.  Then you'd be to use the `asyncData` method (https://nuxtjs.org/guide/async-data).

If you want to reindex the gallery with each request, you can certainly do that in the `data` method.
```
import ImageGallery from '~/helpers/imageGallery.js'

export default {
  data: () => {
    return { images: ImageGallery.getImages() }
  }
}
```
Then you would be able to use the `images` variable to perform whatever looping view logic you wanted to perform.

**Comment by kakulukia** [comment]
okay, will try that and see where it leads me :)
