### ISSUE TITLE
defineComponent is not defined when a component is used from a module via @nuxt/kit

### ISSUE THREAD

**Issue by michaelpumo** [nuxt/nuxt.js#14016]

**Comment by BananaAcid** [comment]
@michaelpumo i tried `import { defineComponent } from '#imports';` but that module was not found -- any requirements to get that working?

https://github.com/nuxt/nuxt/issues/13996 had no solution, that I could understand.

**Comment by danielroe** [comment]
@BananaAcid Into what file are you importing it?

**Comment by BananaAcid** [comment]
@danielroe VSCode just showed an error on #imports (not being found - not typed?), but it actually worked.

1. https://nuxt.com/docs/guide/going-further/modules#quick-start
2. in module.ts, added `addComponent(...)`
3. `/src/runtime/components/component.vue` :
```vue
<script lang="ts">
// @ts-ignore because it works
import { defineComponent } from '#imports';

export default defineComponent({
  // ..
});
</script>
```
4. `npm run dev`


got it working:
- module: https://github.com/BananaAcid/nuxt-dropzone-filelist
