### ISSUE TITLE
Update component before route change

### ISSUE THREAD

**Issue by tsimenis** [nuxt/nuxt.js#1402]
Hi guys, 

I am working on my first project with nuxtjs so bare with me.

So I have a layout which has a header component. This component needs to change state/data on route change. 

I can watch the route on the layout but I want this to happen before the update of the route so that it is instant ( some animations depend on it ).

Is there a way to do that?

My understanding so far is that this could be done with a middleware and using the store?
I am not using the store for this app though, would it make sense to use it only for this specific thing?

**Comment by KonstantinVlasov** [comment]
Hi, @tsimenis!

Did you try beforeRouteUpdate?

**Comment by tsimenis** [comment]
Hi @KonstantinVlasov!

well beforeRouteUpdate doesn't seem to work in a layout? or even a child component

**Comment by KonstantinVlasov** [comment]
Oh, you are right! Looks like middleware is the only way.

**Comment by tsimenis** [comment]
And just to be clear, would you recommend using the store just for this? 
I guess there is no other way to get the value from the middleware except from the store?

**Comment by KonstantinVlasov** [comment]
Maybe this can be useful If you need to change state only on several pages:
Use the store for this state and change it on beforeRouteUpdate for the desired pages.
Then get this state from the store in the layout. No middleware needed in this case. By store is needed:)

**Comment by tsimenis** [comment]
Thanks, I think I can manage it from now on.
