### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module _nuxt/login

### ISSUE THREAD

**Issue by dungonfq** [nuxt/nuxt.js#14020]
### Environment
Production

### Describe the bug

My app on Production is facing many issues `Failed to fetch dynamically imported module` or `403` issue. This is how Sentry log the error:

_**Luckily, this error doesn't break the application. My website still runs normally while Chrome's Devtool is logging the error.**_

Have anyone faced the same issue and have idea to fix it?

Thank all.

**Comment by Tyki** [comment]
Hi @danielroe, any updates on this issue?

We are having a ton of these errors every day for a large domain driven app built with Nuxt 3.2

**Comment by danielroe** [comment]
@Tyki There can be multiple causes for this. If it's related to new deployments, have you tried using the new `experimental.emitRouteChunkError` option? https://github.com/nuxt/nuxt/pull/19038

If not, would you open a new issue with a reproduction? 🙏
