### ISSUE TITLE
Install fails with pnpm

### ISSUE THREAD

**Issue by nivv** [nuxt/nuxt.js#14029]
### Environment

Nuxt project info:                                                                                                                                                              14:53:01

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.0.0-rc.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```
npx nuxi init project-name
```

```
pnpm install --shamefully-hoist
```

### Describe the bug

```
pnpm install --shamefully-hoist
 WARN  deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
Packages: +601
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/albin/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 614, reused 595, downloaded 0, added 601, done

devDependencies:
+ nuxt 3.0.0-rc.3

 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ nuxt
  └─┬ @nuxt/vite-builder
    └── ✕ unmet peer vue@3.2.33: found 3.2.36 in nuxt
```

### Additional context

Getting unmet peer dependency error.

**Comment by DesertCookie** [comment]
Just attempted to switch from npm to pnpm for the first time with a fresh project and am encountering the same issue.

**Comment by OrbisK** [comment]
> Just attempted to switch from npm to pnpm for the first time with a fresh project and am encountering the same issue.

can you please open a new issue with a reproduction?
