### ISSUE TITLE
NuxtLink with anchor-link (#id) does not work.

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/nuxt.js#14033]

**Comment by AloisSeckar** [comment]
solution proposed by @qin-guan didn't quite worked for me

combining with [this approach](https://stackoverflow.com/a/67797577/3204544) did the job:

```ts
import type { RouterConfig } from '@nuxt/schema';

export default <RouterConfig>{
  scrollBehavior(to, from, savedPosition) {
    if (to.hash) {
      const element = document.getElementById(to.hash.substring(1))
      if (element) {
        element.scrollIntoView()
      } else {
        // report element not found
      }
    }
  },
};
```

**Comment by fabiovaz** [comment]
@AloisSeckar  I tried to make a plugin, using afterEach, to do the same logic, but it didn't work, as we need a "delay" to do the animation (with smooth behavior). And forcing a resolve to make this delay took time to update the browser's hash. Your solution worked well for me.
