### ISSUE TITLE
Dynamic Components with resolveComponent(variableName) results in Vue warning and not rendering the component

### ISSUE THREAD

**Issue by Der-Alex** [nuxt/nuxt.js#14036]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/resolvecomponent-test-r98s25?file=/app.vue

### Describe the bug

I try to create dynamic components. for reference I used this nuxt 3 documentation:
https://v3.nuxtjs.org/guide/directory-structure/components#dynamic-components

The component name that is also the filename comes from a variable. When passing that variable into the `resolveComponent` function, the component doesn't get rendered. Instead I get a vue warning: 

> [Vue warn]: Failed to resolve component: BaseBar
> If this is a native custom element, make sure to 
> exclude it from component resolution via compilerOptions.isCustomElement.

The expected behaviour would be that the component gets rendered correctly. 
When using the components name as a string directly inside the function, the component gets rendered. Only when using a variable it doesn't.

Rendering the component should still work when passing a variable into that function. A typical use case would be that you get the components name that should get rendered from a cms / api.

**Comment by airterjun** [comment]
I've solved by using this method 
```
<template>
      <div class="dynamic-component-wrapper">
          <component :is="dynamicComponent()"/>
      </div>
</template>

<script setup>
const dynamicComponent = ()=> {
        const view = useCustomView()
        return defineAsyncComponent(() =>
            import(`~/components/Views/${view}/${view}.vue`)
        )
}
</script>
```

**Comment by silverbackdan** [comment]
Nice @airterjun - how do you ensure that the component is not tree-shaken?

**Comment by rrubio** [comment]
@silverbackdan did you end up finding a solution for tree-shaking?

**Comment by luckylooke** [comment]
Can someone provide working solution (stackblitz?) including server side rendered page with such dynamic components? 🤔 
Thx 🙏

**Comment by MarioAda** [comment]
> No, it should not work. Nuxt looks for a literal string within `resolveComponent`.

How is that useful for "dynamic components" if we can't use variables?

**Comment by trupu** [comment]
@MarioAda has a correct point.

@danielroe Why arent we able to dynamically import components that arent globally registered? We could easly minimize our chunks bundle size by doing so, f.e. globally registering 20 dialogs/sidepanels so user can see just one at the time even sounds stupid.

Does anyone have an idea how to overcome these (and similar) issues? **defineAsyncComponent** was such a perfect way to handle that in vue spa`s :/

**Comment by danielroe** [comment]
@trupu The reason is that a builder, like rollup, needs to know _what_ to include in your build, and it is impossible to know unless you tell Nuxt. If you are dynamically importing a component then it has to include _every_ possible component to enable you to dynamically import it. You can use [glob import](https://vitejs.dev/guide/features.html#glob-import) to tell the bundler what to include. This should work.

**Comment by webard** [comment]
@danielroe thank for explanation. The case is that we have about 20 modals and we don't want to have them in bundle or in HTML content, but in chunk that waits for loading. 

So, we want that rollup/nuxt know to prepare component in build time as standalone chunk, but we do not want to load all modals to browser unless we click on trigger "Open modal X".

**Comment by trupu** [comment]
Appreciate the help :) Works perfectly in both dev and production builds.

For anyone wondering there is a simple example:

```
const modalStore = useModalStore();

const modals = import.meta.glob("~/components/modal/*.vue");

const getComponent = computed(() =>
    modals[`/components/modal/${modalStore.componentNameState}.vue`]
        ? defineAsyncComponent(
              modals[`/components/modal/${modalStore.componentNameState}.vue`]
          )
        : null
);
```
And then in template:
```
<component :is="getComponent"></component>
```

The above code doesnt import anything unless user does any action that changes **modalStore.componentNameState**
