### ISSUE TITLE
Bug: nuxt-rc-3 new page not added to the router automatically when it was created

### ISSUE THREAD

**Issue by amm834** [nuxt/nuxt.js#14053]

**Comment by lafllamme** [comment]
any updates?

**Comment by amm834** [comment]
This issue is already resolved. You should try to update Nuxt to the latest version.

**Comment by lafllamme** [comment]
Experiencing this issue on the latest nuxt stable version.

 ```
  "nuxt": "^3.10.3",
    "vue": "^3.4.19",
    "vue-router": "^4.3.0"
```

**Comment by amm834** [comment]
I have tried with the latest version. It's working well.

https://github.com/amm834/nuxt-layout-transition-animation
