### ISSUE TITLE
start Building server... runs forever

### ISSUE THREAD

**Issue by djschilling** [nuxt/nuxt.js#14062]
### Environment

Nuxt CLI v3.0.0-rc.3                                                                                                                                                          10:44:31
RootDir: /Users/david/projects/finder/churchtools-finder                                                                                                                      10:44:33
Nuxt project info:                                                                                                                                                            10:44:33

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `build`, `buildModules`, `intlify`, `serverMiddleware`, `render`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.2.2`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                              10:44:33

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Describe the bug

We upgraded to nuxt rc3. First it worked. But now 2 days later without changing anything running `nuxi build` does not terminate. It just hangs at `start Building server...`

Here is how it looks:

```
npm run build

> ChurchTools Finder@0.3.0 build
> nuxi build

Nuxt CLI v3.0.0-rc.3                                                                                                                                                          10:41:34
ℹ Vite client warmed up in 2191ms                                                                                                                                             10:41:41

 WARN  [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.                                                             10:41:43
651|  @media print {
652|  	/* Prevent printers from removing background-images of controls. */
653|  	.leaflet-control {
   |       ^
654|  		-webkit-print-color-adjust: exact;
655|  		color-adjust: exact;


 WARN  [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.                                                             10:41:45
651|  @media print {
652|  	/* Prevent printers from removing background-images of controls. */
653|  	.leaflet-control {
   |       ^
654|  		-webkit-print-color-adjust: exact;
655|  		color-adjust: exact;

ℹ Client built in 10043ms                                                                                                                                                     10:41:49
ℹ Building server...                                                                                                                                                          10:41:49

 WARN  @fortawesome/fontawesome-free doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.


 WARN  reflect-metadata doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.


 WARN  [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.                                                             10:41:50
651|  @media print {
652|  	/* Prevent printers from removing background-images of controls. */
653|  	.leaflet-control {
   |       ^
654|  		-webkit-print-color-adjust: exact;
655|  		color-adjust: exact;

✔ Server built in 2511ms                                                                                                                                                      10:41:51
✔ Generated public .output/public                                                                                                                                       nitro 10:41:51
start Building server...
```

I can see that esbuild is running and not terminating. Is there a debug flag where i can see more infos?

**Comment by AlejandroAkbal** [comment]
Still having this issue

Repo: https://github.com/AlejandroAkbal/Image-to-Text-OCR/tree/b05032c0e4242cfcc8da9b0da3e670db5844633d

**Comment by danielroe** [comment]
@AlejandroAkbal This is probably a different issue. See https://github.com/nuxt/cli/issues/169.
