### ISSUE TITLE
Error using transition (to, from) {}

### ISSUE THREAD

**Issue by gtso86** [nuxt/nuxt.js#1406]
Hey there, I guess I found a bug on Nuxt RC4 related with page [transition as a function](https://nuxtjs.org/api/pages-transition#function).

I thought was something related with my project but I reproduced the same [glitch here](https://breezy-newsstand.glitch.me/). Try to navigate to about and go to another page...

IF a page have transition fn inside, when you try to leave NUXT stop to work.

```js
    transition(go, from) {
      console.log(go);
      console.log('');
      console.log(from);
    },
```

![](http://i.imgur.com/54iYPfTg.png)
![](http://i.imgur.com/85fAoPr.png)

Regards,

**Comment by pi0** [comment]
Hi. Thanks for the report. I've pushed a fix, however, this bug should not happen in normal conditions as transition is expected to return an object! So workaround for now until next release is:
```js
 transition(go, from) {
      console.log(go);
      console.log('');
      console.log(from);
      return {}
    },
```
