### ISSUE TITLE
Error thrown `nuxt instance unavailable`, when use `useState` after `useFetch` in composable

### ISSUE THREAD

**Issue by ItsuoSano** [nuxt/nuxt.js#14068]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.3-27538180.cad4edd`
- Package Manager:  `npm@8.7.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cibhp2-szhe5i?file=composables%2Ffetch-data.ts

``` typescript
export const useStateBeforeUseFetch = async () => {
  const { data } = await useFetch('/api/test');
  const state = useState('test');
};
```

### Describe the bug

when I use `useState` after `async useFetch` , error was thrown `nuxt instance unavailable`

### Logs

```shell
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
    at Module.useNuxtApp (file:///home/projects/github-cibhp2-szhe5i/.nuxt/dist/server/server.mjs:408:13)
    at Module.useState (file:///home/projects/github-cibhp2-szhe5i/.nuxt/dist/server/server.mjs:948:38)
    at Module.useStateBeforeUseFetch (file:///home/projects/github-cibhp2-szhe5i/.nuxt/dist/server/server.mjs:3089:39)
```
```

**Comment by Gustavodacrvi** [comment]
I haven't found a solution to this, but I came up with a workaround that might be helpful. I have in my app many endpoints that are available globally, they're the same for everyone, and rarely change, so I wanted them to be called only once in the server, cached, and parsed in the frontend, making 0 unnecessary calls.

I've tried to create a composable for this but eventually encountered the same issue found here, so I came up with the following workaround:

```
const [config, categoryThree, availableComponents, regions] = await Promise.all([
  useFetch('/app-config'),
  useFetch("/categories/three"),
  useFetch(`/editor/cached/available-components`),
  useFetch(`/regions`),
])

useState('available-components', () => availableComponents.data.value)
useState('categories-three', () => categoryThree.data.value)
useState('regions', () => regions.data.value)
```

I'm fetching them all on `app.vue`, and then serializing the results with `useState()`, then I can access this data everywhere in the app with `export const useCategories = () => useState('categories-three') as Ref<Category[]>`. I guess this is probably how this composable was supposed to be used in the first place.
