### ISSUE TITLE
CSS not minified when using Font Awesome Icons

### ISSUE THREAD

**Issue by jasonlundien** [nuxt/nuxt.js#14065]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

A reproduction and small [project](https://github.com/jasonlundien/fa-nuxt-3-example)

### Describe the bug

With Nuxt2, the css and minification was handled by setting `config.autoAddCss = false`.
When `npm run build` was ran, a `.js` file was generated under the `dist/_nuxt/` directory which included the minified Font Awesome css classes, etc.

With Nuxt3, the minification seems to be handled a bit differently... yet I cannot figure out how to get the Font Awesome css classes to be minified upon an `npm run build` even with setting `config.autoAddCss = false`.  An unminified version of the classes is written in the `.nuxt/dist/client/` directory in a `.mjs` directory.  No warnings, errors, etc.

In both versions you can search for `.svg-inline--fa` and see the minified in Nuxt2 and the unminified in Nuxt3.

### Additional context
Additionally, I have tried to adjust `minifyCSS` and `minifyJS` manually by adding the following to `nuxt.config.ts`, but this did not work either, so I removed.

` build: {
    html: {
      minify: {
        minifyCSS: true,
        minifyJS: true,
      }
    },
}`

_No response_

**Comment by ArtMooney** [comment]
> @danielroe -- Here is what I get when I run `npm run build`.
> 
> The text you show above (from `.output/public/_nuxt/entry-510e4124.mjs`) is NOT getting minified. There is actually about 750 lines of un-minified Font Awesome css; not just the 20 (appox) I show in the image.
> 
> It appears the text is being minified in the `entry.96ef2004.css` file but not in the `entry-510e4124.mjs` file.
> 
> <img alt="fa-nuxt-no-minification" width="1796" src="https://user-images.githubusercontent.com/50338269/172243989-ad666570-d55d-4d9c-b843-e7fe17a1f12c.png">

Did you happen to find a solution for this issue?
