### ISSUE TITLE
download part of page without reboot

### ISSUE THREAD

**Issue by Jussiadev** [nuxt/nuxt.js#1409]
I need the new page not to load when clicking on a link, and the parts that are not on the current page are loaded on my last actual page. That is, the header and footer remained, there was a standard loader and the components were added from the new page, and there should not be a reboot

**Comment by KonstantinVlasov** [comment]
This is what nuxt and vue do, actually. Just use layout component for header and footer and nuxt-link for navigation. I think you should read vue and nuxt docs first.
