### ISSUE TITLE
dev error: (node:42372) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. (Use `node --trace-warnings ...` to show where the warning was created)

### ISSUE THREAD

**Issue by hehehai** [nuxt/nuxt.js#14101]

**Comment by codetheorist** [comment]
Same for me, but I can't trace what dependency it's coming from as when I attempt to use `--trace-warnings` then I'm still advised to use the flag and no trace is shown.

The command I'm using is `node --trace-warnings node_modules/nuxi/bin/nuxi.mjs dev` but it doesn't make the blindest bit of difference.

**Comment by danielroe** [comment]
cc: @pi0 - it might be worth passing along node flags if we're not already doing so in `nuxi`...

**Comment by codetheorist** [comment]
That would be a big win.

**Comment by hognevevle** [comment]
@danielroe Can we please reopen this? It seems node flags still aren't being passed along, so I'm having a very hard time tracking down these errors in my app.

**Comment by rscorer** [comment]
Happens with Nuxt 4 preview, I downloaded Dashboard sample, ran it from scratch and encountered this issue immediately-- no idea how to track it down.
