### ISSUE TITLE
how to get cookie in asyncData ({query, req})

### ISSUE THREAD

**Issue by daosonit** [nuxt/nuxt.js#1411]
i need auth request to server,   
```
asyncData ({query, req}) {
      console.log(req) 
}
```
help me, get cookie in req

**Comment by daosonit** [comment]
now. my solution: 
```
asyncData ({query, req}) {
     let accessToken = getCookie('access_token', req.headers.cookie)
}
```
```
function getCookie (cookieName, stringCookie) {
  let strCookie = new RegExp('' + cookieName + '[^;]+').exec(stringCookie)[0]
  return unescape(strCookie ? strCookie.toString().replace(/^[^=]+./, '') : '')
}
```

**Comment by tlgreg** [comment]
Nuxt doesn't provide anything handling cookies out of the box, though the default module stack does include [cookie](https://github.com/jshttp/cookie), because `@nuxtjs/youch` uses it.
That makes it a bit easier: `cookie.parse(req.headers.cookie) // eg.: { "access_token": "..." }`

**Comment by pi0** [comment]
@tlgreg Don't rely on implicit dependencies for your nuxt project! Youch may be changed or removed later. Installing using npm/yarn is recommended :))

**Comment by tlgreg** [comment]
@pi0 True, left that out, just wanted to point out something thats already in there, so no more bloat. :)

**Comment by sj82516** [comment]
I am using axios inside async data.  
How can axios send HTTP request with cookie?
