### ISSUE TITLE
z-index value in Vue component changed on build

### ISSUE THREAD

**Issue by radibit** [nuxt/nuxt.js#1413]
Hey everyone! First of all, thank you for the great work on this project.

I just found out that if there is a `z-index` property defined in the style section of a Vue component, it will be changed to 1 after it has been built. I was able to reproduce this behavior on Nuxt.js v1.0.0-rc4.

Example:

components/Nav.vue
```js
<template>
  <nav class="c-nav"></nav>
</template>

<style>
  .c-nav {
    position: fixed;
    z-index: 3; /* will be changed to 1 */
  }
</style>
```

Setting up the `scope` attribute doesn't fix the mentioned issue.

Another example is the built-in [`nuxt-loading`](https://github.com/nuxt/nuxt.js/blob/dev/lib/app/components/nuxt-loading.vue) component. It has `z-index: 999999` which is then changed to `1` once it's built.

My assumption is that there is an issue with the webpack configuration and more specifically the unsafe style optimizations :)

**Comment by DusanMilko** [comment]
I am unable to replicate this

**Comment by Atinux** [comment]
Please re-open with a reproduction repo

**Comment by radibit** [comment]
@Atinux I just updated Nuxt.js to v1.0.0-rc6 and the issue is no longer reproducible.
