### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/null"

### ISSUE THREAD

**Issue by drekembe** [nuxt/nuxt.js#14147]
### Environment

Nuxt project info:                                                                                            17:45:23

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `strict`, `typeCheck`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/drekembe/nuxt-null-get-warning

### Describe the bug

How to recreate:
* Create a blank project with `npx nuxi init`
* Add an `index.vue` page in `pages`
* Start the dev server and navigate to the root page (i.e. `http://localhost:3000/`)

The problem:
* In the console, you'll see a warning: `[Vue Router warn]: No match found for location with path "/null"`
* In the network inspector, you'll see that a request for `/null` is made, which results in a 404 error

It's not a deal-breaker, but this was literally the first thing I saw when trying to set up a Nuxt 3 project. Hopefully, this will be easy to debug since the reproduction for it is just an empty project with an `index.vue` page.

Great work by the way on Nuxt 3 so far, keep it up! Thanks in advance to anyone who looks at this issue.

**Comment by Arturexe** [comment]
I couldn't get rid of this warning during a vitest test. restarting the dev server fixed it.

**Comment by wiseadme** [comment]
I'm facing the same problem. Everything is work fine, but errors are constantly displayed in the console when changing the route.

![Image](https://github.com/user-attachments/assets/3d0192c3-cbf6-4262-baf2-24d94c667979)
