### ISSUE TITLE
Favicon.ico seems to ignores app.cdnURL when set

### ISSUE THREAD

**Issue by DRoet** [nuxt/nuxt.js#14145]

**Comment by msonowal** [comment]
I think we should have first party support as we are giving cdnUrl from framework

**Comment by igor9silva** [comment]
Hi. I've been looking for that info for an hour. Can we add that to the docs?
First party support also makes a lot of sense.

**Comment by kogratte** [comment]
Can't say anything to upvote firstclass support :)

Also, cdnurl should be considered into spa-loading-template, which does not seems to be working as of today.

**Comment by danielroe** [comment]
spa-loading-template is not included in your build - it is a static html file. If you have a feature request for it, feel free to open one.
