### ISSUE TITLE
Type property on objects

### ISSUE THREAD

**Issue by galvez** [nuxt/nuxt.js#1418]
Nuxt 1.0rc4 apparently tries to use the `type` property on an object from a list passed to `v-for` when rendering, resulting in an error like this:

<img width="944" alt="screen shot 2017-08-19 at 7 36 45 am" src="https://user-images.githubusercontent.com/12291/29485926-6286990e-84b1-11e7-9033-3967d02c3150.png">

**Comment by galvez** [comment]
(The fix was to avoid using `.type` on objects to be rendered through `v-for`)

**Comment by pi0** [comment]
Hi @galvez . Would you please point which file is causing this error? Or sharing a simple snippet to reproduce.

**Comment by galvez** [comment]
Hi @pi0, something like this:

```
<template>
  <div>
    <p v-for="item in list"><{{ title }}/p>
  </div>
</template>

<script>
  export default {
    data: () => ({
      list: [{type: "foobar", title: "title"}]
    })
  }
</script>
```

Only happens when rendering through Koa / `nuxt.render`.

**Comment by galvez** [comment]
Upon further investigation, i'm starting to think this might be the culprit:

https://github.com/wangdahoo/vswipe

I'll update when I learn more.

**Comment by pi0** [comment]
Ahh I think it is similar to new SSR optimizations (#1243, #1248). That  `appendchild` is happening from SSR rendered content. Would you please check using *view page source* if is there something missing on unusual?

**Comment by galvez** [comment]
@pi0 Not sure about the source, but it was definitely it. I managed to solve the issue using the `vue-no-ssr` instructions from https://github.com/NightCatSama/vue-slider-component (although I'm using a different slider component)
