### ISSUE TITLE
addServerMiddleware deprecation and replacement with addServerHandler

### ISSUE THREAD

**Issue by akuma-phawx** [nuxt/nuxt.js#14198]

**Comment by dynamis** [comment]
FYI: finally we can use nuxt v3 + express middleware like this with `fromNodeMiddleware()`:

nuxt.config.js
```js
import { defineNuxtConfig } from "nuxt/config";

export default defineNuxtConfig({
  serverHandlers: [{ route: "/pathtoapi/**", handler: "~/express/index.js" }],
});
```

~/express/index.js
```js
import bodyParser from "body-parser";
import express from "express";

const app = express();
const router = express.Router();

app.use(bodyParser.json());

router.get("/hello", (req, res) => {
  res.send(
    "Hello Express from server Handler assigned to this route with serverHandlers config"
  );
});

router.all("/json", (req, res) => {
  res.json({ data: "some data as JSON" });
});

app.use("/pathtoapi", router);

// convert node middleware to h3 handlar
// ref: https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.12
const h3handler = fromNodeMiddleware(app);
export default h3handler;
```

You can also use catch-all path, without serverHandlers nuxt config:

`server/api/[...].js`
```js
import bodyParser from "body-parser";
import express from "express";

const app = express();
const router = express.Router();

app.use(bodyParser.json());

router.get("/hello", (req, res) => {
  res.send(
    "Hello Express from server Handler assigned to this route with serverHandlers config"
  );
});

router.all("/json", (req, res) => {
  res.json({ data: "some data as JSON" });
});

app.use("/api", router);

// convert node middleware to h3 handlar
// ref: https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.12
const h3handler = fromNodeMiddleware(app);
export default h3handler;
```

our samples from nuxt3 hands-on materials :
https://github.com/dynamis/lyceum/tree/main/nuxt-with-express
https://github.com/webdino/lyceum-pokemon

**Comment by abarke** [comment]
FYI I eventually arrived at a nice type-safe one liner for using our node-middleware where I de-structure H3Event (inferred by TypeScript/IDE) and take out `node` which is inferred as [NodeEventContext](https://github.com/unjs/h3/blob/a0e21c11c5bc9c219fa27fc531d690548926b12b/src/event/event.ts#L6-L9)

```ts
export default defineEventHandler(({ node }) => customMiddleware(node.req, node.res))
```
or even shorter 😄 
```ts
export default defineEventHandler(({ node: { req, res } }) => customMiddleware(req, res))
```

**Comment by dsmsmj** [comment]
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:387:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1017:11)
    at defaultResolve (node:internal/modules/esm/resolve:1097:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap. (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) 


Is there a solution to the problem that appears on Windows

**Comment by danielroe** [comment]
@dsmsmj would you provide a reproduction + a new issue? 🙏
