### ISSUE TITLE
how call server related methods/functions in nuxtServerInit

### ISSUE THREAD

**Issue by Mirodil** [nuxt/nuxt.js#142]
Is it possible to do something like this?
```
actions: {
        nuxtServerInit({ commit }, { req }) {
            const fs = require('fs');
            const content = fs.readFileSync(__dirname + '../package.json');
            console.log('secret');
            commit('SET_USER', content);
        }
    }
```

**Comment by Atinux** [comment]
Hi @Mirodil 

Yes it's totally possible to do that in the `nuxtServerInit` method 👍

**Comment by husayt** [comment]
One more question on NuxtServerInit.
When is it called?
On every server side request before fetch and data?

Actually timeline of events (life cycle of the page)  would be very
interesting to find out mire about.

**Comment by Mirodil** [comment]
This throws errors to console.
```
ERROR in ./store/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/mkhojirakhimov/Documents/Projects/
examples/nuxtjs01/store'
 @ ./store/index.js 23:21-34
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
```
The idea of this framework very good, I like it. But I did not get, Why nuxt.js exposing `nuxtServerInit` to client side?

**Comment by kese** [comment]
Just realized the default webpack configuration for client-side bundles does not specify any external modules. So you may try adding fs module in `nuxt.config.js` to the list of externals:

```
build: {
  extend(config, context) {
    if (context.isClient) {                
        config.externals = ['fs']
    }
  }
}
```
