### ISSUE TITLE
SSR directive

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#1421]
Hello i use nuxt 1.0.0-rc4! how i use ssr directives ?

nuxt.config.js

```
build: {
        ssr: {
            directives: {
                textresource: function () {}
            }
        },
    }
```

Not working!

**Comment by pi0** [comment]
Hi. Please use `render.bundleRenderer` option. https://nuxtjs.org/api/configuration-render#bundlerenderer

Also upgrade to rc6 is recommended.

**Comment by wargt** [comment]
https://nuxtjs.org/api/configuration-render#bundlerenderer

404 link ((

**Comment by wargt** [comment]
please give me example! thanks

**Comment by pi0** [comment]
@wargt Opps. thanks for the report. We will investigate problem soon. Meanwhile please head to this page: https://github.com/nuxt/docs/blob/master/en/api/configuration-render.md

**Comment by wargt** [comment]
I was there. But still did not understand how to do server directives ((
