### ISSUE TITLE
nuxt generate fails with [request error] navigator is not defined

### ISSUE THREAD

**Issue by TenkoSpirit** [nuxt/nuxt.js#14216]

**Comment by dosstx** [comment]
> > Somewhere in your code (or more likely a library you are depending on) there is a reference to the global `navigator`. This doesn't exist on SSR - hence the error.
> 
> Oh, I see, makes sense now. Tomorrow I will definitely look for the source of the problem, thank you very much! ❤️

Do you mind sharing what the culprit was? I have the same problem.
