### ISSUE TITLE
How to use vanilla JS library with Nuxt?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1422]
Hello. Find very hard to make some vanilla js libs work with Nuxt. 

Now struggling with this https://atomiks.github.io/tippyjs/

Can somebody help me?

This is not working

```
if (process.browser) {
  require('tippy.js')
}

export default {
  mounted () {
    tippy('.btn')
  }
}
```

A couple other options doesn't work too. How to make this awesome library make work with Nuxt? It's working with non SSR Vue app like a charm.

**Comment by iamdubx** [comment]
Making it ssr false plugin didn't help

```
import tippy from 'tippy.js'
tippy('.btn')
```
It only works if I refresh the page. If I navigate to this page from others - plugin is not working! ANy ideas how to fix it?

**Comment by cretueusebiu** [comment]
@iamdubx Try this https://github.com/egoist/v-tippy

**Comment by iamdubx** [comment]
@cretueusebiu unfortunately, it's too buggy.

**Comment by haffla** [comment]
I suppose you have considered `<script src="https://unpkg.com/tippy.js@1.2.0/dist/tippy.min.js"></script>`

**Comment by haffla** [comment]
Or you can try with [dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports)

```js
export default {
  mounted () {
    import('tippy').then(_ => {
      tippy('.btn')
    })
  }
}
```

This will split your code

**Comment by iamdubx** [comment]
@haffla just tried this. Not working.

**Comment by haffla** [comment]
What's the error anyway? `window is not defined`?

**Comment by pi0** [comment]
Maybe @egoist can help us, please 🙂

**Comment by iamdubx** [comment]
@haffla no erros. It just silently doesn't work. Well, it is working but only is I refresh page, not is I navigate to it.

@pi0 EGOIST wrapper works fine. I just want vanilla library :smile:

**Comment by egoist** [comment]
Not sure how the actual code looks like, maybe you can share your repo for this?

> But I just want to try vanilla library 😄

Eventually you'll extract it into a directive or something when your app get bigger 😅

**Comment by iamdubx** [comment]
I guess you right @egoist it doesn't worth the efforts. Probably will stick with Vue wrappers! Thanks all for support.

**Comment by egoist** [comment]
Hmm, it actually works. https://glitch.com/edit/#!/checker-need

**Comment by iamdubx** [comment]
Wow, it is working. Can't believe how it's simple. Didn't tried to require in in `mounted()` :smile:
