### ISSUE TITLE
[spa] Fetch is not called when accessing child page directly

### ISSUE THREAD

**Issue by cretueusebiu** [nuxt/nuxt.js#1423]
The `fetch` method is not called when you access a child page directly.

Reproduction project: https://github.com/cretueusebiu/nuxt-fetch-issue

Start the project and open the console:
- You should see `fetch@index.vue`.
- Now click on the _Child_ button and you'll see `fetch@child.vue`.
- While on the `/child` page, refresh the page and only `fetch@child.vue` is shown.

Is this the expected behavior ? 

From looking at the code [this line](https://github.com/nuxt/nuxt.js/blob/75a845e5c72825924030c66c9fed30b065fdc041/lib/app/client.js#L281) seems to prevent fetch from being called on the parent component.

![nuxt](https://user-images.githubusercontent.com/1517945/29490281-449d8aee-8540-11e7-864c-e8a35417f839.gif)

**Comment by gtso86** [comment]
@cretueusebiu What you expect? When hard reload child page call `fetch@index.vue` too?

**Comment by cretueusebiu** [comment]
@gtso86  Yes.

**Comment by gtso86** [comment]
@cretueusebiu got it what you mean. When I disabled the `mode: spa` inside the nuxt.config.js I both on my console...

![image](https://user-images.githubusercontent.com/319048/29496466-a6a1abb2-85a9-11e7-8184-62dd6909dcb3.png)

**Comment by Atinux** [comment]
Hi @cretueusebiu @gtso86 

It seems to be a bug indeed, it should not call any `fetch` method on reload since everything is server-rendered.

I will take a look at it.

**Comment by Atinux** [comment]
I just tried and `universal` mode is working perfecly:
- `/` -> `fetch@index.vue` in server console
- `/child` -> fetch@index.vue` and `fetch@child.vue` in server console
- Navigating client-side from `/` to `/child` -> only `fetch@child.vue` in client console

But with `spa` mode (only client console):
- `/` -> `fetch@index.vue` in console
- `/child` -> `only `fetch@child.vue` in console == **BUG**

Woking on it :)

**Comment by Atinux** [comment]
It's fixed with https://github.com/nuxt/nuxt.js/commit/fed644ddf68717191bdef43f12946139b81e6c9c

Will be available in `rc6` :)
