### ISSUE TITLE
useFetch refresh not working when params change

### ISSUE THREAD

**Issue by SamEdwardes** [nuxt/nuxt.js#14243]

**Comment by truesteps** [comment]
can I use useFetch and useAsyncData at the same time? I have 2 requests a i need to make, for one i'm using useFetch and for the other, which reacts to the changes in the data from the first one i use useAsyncData but for whatever reason the useAsyncData doesn't seem to get executed

**Comment by manniL** [comment]
This being somewhat older, I want to propose a different approach here that still use `useFetch` -> by passing a `computed` as any of the top-level option arguments

Instead of:

> ```
> const name = ref('sam');
> 
> const { data: age } = await useAsyncData(
>   'age',
>   () => $fetch('https://api.agify.io', {
>     params: {
>       name: name.value,
>     },
>   }),
>   { watch: [name] }
> );
> ```

You can write the following and achieve the same.

> ```
> const name = ref('sam');
> const params = computed(() => { name: name.value ])
>
> const { data: age } = await useFetch('https://api.agify.io', { params })
> ```

**Comment by SamEdwardes** [comment]
> Despite being an older issue, I want to propose a different approach here that still leverages`useFetch`. By passing a `computed` as any of the top-level option arguments, you can achieve the same:
> 
> 
> 
> Instead of:
> 
> 
> 
> > ```ts
> 
> > const name = ref('sam');
> 
> > 
> 
> > const { data: age } = await useAsyncData(
> 
> >   'age',
> 
> >   () => $fetch('https://api.agify.io', {
> 
> >     params: {
> 
> >       name: name.value,
> 
> >     },
> 
> >   }),
> 
> >   { watch: [name] }
> 
> > );
> 
> > ```
> 
> 
> 
> You can write the following and achieve the same.
> 
> 
> 
> ```ts
> 
> const name = ref('sam');
> 
> const params = computed(() => { name: name.value })
> 
> 
> 
> const { data: age } = await useFetch('https://api.agify.io', { params })
> 
> ```

This is interesting. Why do you not need to use `watch` anymore when you use `computed`?

**Comment by manniL** [comment]
> This is interesting. Why do you not need to use `watch` anymore when you use `computed`?

Because the composable will keep track fo changes thanks to Vue's reactivity system

**Comment by mukundshah** [comment]
> Despite being an older issue, I want to propose a different approach here that still leverages`useFetch`. By passing a `computed` as any of the top-level option arguments, you can achieve the same:
> 
> Instead of:
> 
> > ```ts
> > const name = ref('sam');
> > 
> > const { data: age } = await useAsyncData(
> >   'age',
> >   () => $fetch('https://api.agify.io', {
> >     params: {
> >       name: name.value,
> >     },
> >   }),
> >   { watch: [name] }
> > );
> > ```
> 
> You can write the following and achieve the same.
> 
> ```ts
> const name = ref('sam');
> const params = computed(() => { name: name.value })
> 
> const { data: age } = await useFetch('https://api.agify.io', { params })
> ```

@manniL @danielroe is this approach safe? will it have any side effect?

**Comment by mukundshah** [comment]
> You can write the following and achieve the same.
> 
> ```ts
> const name = ref('sam');
> const params = computed(() => { name: name.value })
> 
> const { data: age } = await useFetch('https://api.agify.io', { params })
> ```

@manniL @danielroe is this approach safe? will it have any side effetct?

**Comment by manniL** [comment]
@mukundshah Yes - a *desired* side effect: Whenever the `params` (here the `name`) change, the API will be called again.

**Comment by crazymind** [comment]
> Despite being an older issue, I want to propose a different approach here that still leverages`useFetch`. By passing a `computed` as any of the top-level option arguments, you can achieve the same:
> 
> Instead of:
> 
> > ```ts
> > const name = ref('sam');
> > 
> > const { data: age } = await useAsyncData(
> >   'age',
> >   () => $fetch('https://api.agify.io', {
> >     params: {
> >       name: name.value,
> >     },
> >   }),
> >   { watch: [name] }
> > );
> > ```
> 
> You can write the following and achieve the same.
> 
> ```ts
> const name = ref('sam');
> const params = computed(() => { name: name.value })
> 
> const { data: age } = await useFetch('https://api.agify.io', { params })
> ```

Looks like the refresh also works without computed and watcher. Just reference the ref object directly instead of the .value. Anything wrong with this?

```ts
const page = ref(1);
const { data: todos } = await useFetch( () => `https://jsonplaceholder.typicode.com/todos`, {
    params: {
      _page: page, // page.value will only not update. But page does, even without a watcher
    },
  }
);
```

**Comment by SamEdwardes** [comment]
Thank you @crazymind - this looks like a cleaner approach!

**Comment by SimonRosengren** [comment]
> > Despite being an older issue, I want to propose a different approach here that still leverages`useFetch`. By passing a `computed` as any of the top-level option arguments, you can achieve the same:
> > Instead of:
> > > ```ts
> > > const name = ref('sam');
> > > 
> > > const { data: age } = await useAsyncData(
> > >   'age',
> > >   () => $fetch('https://api.agify.io', {
> > >     params: {
> > >       name: name.value,
> > >     },
> > >   }),
> > >   { watch: [name] }
> > > );
> > > ```
> > 
> > 
> > You can write the following and achieve the same.
> > ```ts
> > const name = ref('sam');
> > const params = computed(() => { name: name.value })
> > 
> > const { data: age } = await useFetch('https://api.agify.io', { params })
> > ```
> 
> Looks like the refresh also works without computed and watcher. Just reference the ref object directly instead of the .value. Anything wrong with this?
> 
> ```ts
> const page = ref(1);
> const { data: todos } = await useFetch( () => `https://jsonplaceholder.typicode.com/todos`, {
>     params: {
>       _page: page, // page.value will not update. But page does, even without a watcher
>     },
>   }
> );
> ```

Thank you @manniL ! 

I just wanted to clarify for any other people who might still struggle. It's important to utilise the `params` field rather than string interpolation on the url directly, or it won't work :)

**Comment by mukundshah** [comment]
For some reason, param change doesn't trigger the loading indicator. Am I missing something?

**Comment by SamEdwardes** [comment]
@mukundshah can you share an example?

**Comment by mukundshah** [comment]
Hi @SamEdwardes 

Firstly, thank you for responding.

I've created a reproduction on CodeSandbox: [https://codesandbox.io/p/sandbox/fancy-cloud-hdr3gz](https://codesandbox.io/p/sandbox/fancy-cloud-hdr3gz).

In this example, I'm trying to avoid manually handling the loading indicator or filler state returned by `useFetch`. Instead, I want Nuxt.js to take care of it.

During page changes, the `<NuxtLoadingIndicator />` component effectively shows the loading state while `useFetch` is awaited, blocking navigation until the request finishes. This seemed like a good solution to eliminate the need for manual loading state management.

However, this approach falls short when the page doesn't reload but the request is refetched due to actions like refresh, parameter changes, or anything that doesn't trigger a full page mount.

Initially, it seemed like `useLoadingIndicator` could be used to control the loading indicator manually using `onRequest` and `onResponse` events. Unfortunately, since the loading indicator is tied to route changes, changing a query parameter triggers Nuxt's `page:loading:start` and `page:loading:end` events. This causes the loading indicator to finish before the response arrives, breaking my solution.

Check the `composables/api-fetch.ts` for more clarity.

**Comment by metkm** [comment]
> Despite being an older issue, I want to propose a different approach here that still leverages`useFetch`. By passing a `computed` as any of the top-level option arguments, you can achieve the same:
> 
> Instead of:
> 
> > ```ts
> > const name = ref('sam');
> > 
> > const { data: age } = await useAsyncData(
> >   'age',
> >   () => $fetch('https://api.agify.io', {
> >     params: {
> >       name: name.value,
> >     },
> >   }),
> >   { watch: [name] }
> > );
> > ```
> 
> You can write the following and achieve the same.
> 
> ```ts
> const name = ref('sam');
> const params = computed(() => { name: name.value })
> 
> const { data: age } = await useFetch('https://api.agify.io', { params })
> ```

@manniL 
What do you do when you have 2 reactive values but you want only one of them to trigger a request? For example, I have an authorization header with reactive token `Authorization: 'Bearer ${accessToken}'` but also a query as a parameter. Updating the token shouldn't trigger the request but the query should.

**Comment by danielroe** [comment]
@metkm You provide one to the watch array and not the other.

**Comment by alexi190** [comment]
@danielroe I am really confused on one thing if you please can help me on it. 

what happen if I want to change more than 1 param after the page is loaded (to load new data with new params)


```js
const params = computed(() => cleanParams({
    pageNum: pageNum.value,
    pageSize: 12,
    searchAfter: searchAfter.value,
    minPrice: minPrice.value,
    maxPrice: maxPrice.value,
    keyword: keyword.value,
}));

```

```js
minPrice = 10;
maxPrice:  1000
searchAfter: `[10,8]`
```
in my case it will hit the api three times one after the other. 
how can i prevent it.

**Comment by alexi190** [comment]
@metkm but as soon as i set `minPrice.value = 10;` the api automatically get triggered.  is there a way i so that i can set these values without triggering the api and then call `execute`  ?

**Comment by metkm** [comment]
> @metkm but as soon as i set `minPrice.value = 10;` the api automatically get triggered. is there a way i so that i can set these values without triggering the api and then call `execute` ?

If you set `watch: false` then computed values won't trigger a new request

**Comment by omarmir** [comment]
I wanted to reset current page when search string was changed so I couldn't use the methods noted above (no sideffects in computed).

Ended up doing what Daniel suggested with the useAsyncData and a manual watcher so I can perform the correct functions.

**Comment by jimbatamang** [comment]
> Despite being an older issue, I want to propose a different approach here that still leverages`useFetch`. By passing a `computed` as any of the top-level option arguments, you can achieve the same:
> 
> Instead of:
> 
> > const name = ref('sam');
> > 
> > const { data: age } = await useAsyncData(
> >   'age',
> >   () => $fetch('https://api.agify.io', {
> >     params: {
> >       name: name.value,
> >     },
> >   }),
> >   { watch: [name] }
> > );
> 
> You can write the following and achieve the same.
> 
> const name = ref('sam');
> const params = computed(() => { name: name.value })
> 
> const { data: age } = await useFetch('https://api.agify.io', { params })

This is super interesting. Instead of using `computed` property, if you use the custom params with the value being `ref` or `computed` property, it doesn't work.

For example,

```javascript
const bar = ref('')
const { data: plans } = await useFetch('plans', {
    query: { foo: bar.value}
})
```

but the following will work:

```javascript
const bar = ref('')
const params = computed(() => {
    return {
        foo: bar.value
    }
})

const { data: plans } = await useFetch('plans', {
    params,
})

```

I couldn't figure-out what's the exact difference between here? Somebody please give me some light.
