### ISSUE TITLE
Is that possible to use difference Layout between Parent and Child page?

### ISSUE THREAD

**Issue by VadiForte** [nuxt/nuxt.js#1425]
Let's say if i have 
`/profile/`
and
`/profile/user1`

So, my page folder should be look like this
```
| page
|-- profile.vue
|-- profile
|----- index.vue
|----- user1.vue
```

the `profile.vue` i have put `<nuxt-child/>`  
and it will automatically call content in the `/profile/index.vue`

So, Is that possible to use difference Layout between `/profile/index` and `/profile/user1` page?

I have define difference layout but it still not work
```
export default  {
  layout: 'user'
}
```
Thank you

**Comment by cretueusebiu** [comment]
You can call `setLayout` on the root instance from your child components:

```javascript
created () {
  this.$root.setLayout('other')
}
```
