### ISSUE TITLE
1.0.0-rc4 relative module not found

### ISSUE THREAD

**Issue by ArnoBuschmann** [nuxt/nuxt.js#1426]
Hello,

I am trying to add vuetify as per this example
https://github.com/nuxt/nuxt.js/tree/dev/examples/with-vuetify
to the 1.0.0-rc4 version of Nuxt and get this error message:
```
This relative module was not found:

* ../assets/app.styl in ./node_modules/babel-loader/lib?{"presets":["/home/arno/Projekte/Arno/nuxt-test/tcm-patienten-prototype/node_modules/babel-preset-vue-app/dist/index.common.js"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./.nuxt/App.vue
```
In nuxt.config.js the css is referenced this way:
```
css: ['~/assets/app.styl']
```
The app.styl file in the assets-folder looks like this:
```
// Specify overrides (theme and/or base variables etc.)
// See https://vuetifyjs.com/quick-start
$theme := {
  primary: #9c27b0
  accent: #ce93d8
  secondary: #424242
  info: #0D47A1
  warning: #ffb300
  error: #B71C1C
  success: #2E7D32
}

// Import Vuetify styling
@require '~vuetify/src/stylus/main.styl'
```
I am not sure, if I need to add a stylus-loader to the webpack config but this seems to indicate, that stylus is already configured in Nuxt?:
https://github.com/nuxt/nuxt.js/blob/master/lib/webpack/vue-loader.config.js

Any hint on how to fix this is very welcome :smile: , thanks.

**Comment by pi0** [comment]
Hi. Please just simply install `stylus` and `stylus-loader` :) https://github.com/nuxt/nuxt.js/blob/dev/examples/with-vuetify/package.json#L13

**Comment by ArnoBuschmann** [comment]
Hi @pi0 , *blushes* arrgh, that's almost embarrassing, thanks man :)
