### ISSUE TITLE
using try/catch with an async method inside a middleware causes a `nuxt instance unavailable` error.

### ISSUE THREAD

**Issue by amrnn90** [nuxt/nuxt.js#14269]

**Comment by radudalbea** [comment]
Hi,

I am having the same issue but with a request from a created method. Basically I am trying to do a simple fetch outside the setup function.

async created() {
      await this.fetchData();
}

In the fetch method I'm trying to call nuxt auth composable to retrieve the status of the user.

const { status, data } = useAuth();

The error is from useAuth(); I tried using callWithNuxt(who by the way is nowhere mentioned in the docs) and it doesn't work. If I do a entire refactoring and put the call in the setup script or method it works and I understand that I have an option to fix it but the most common use case is to do fetch from create or any other functions. I don't understand how an issue with some many complaints it's closed. Not every component can be written with the setup method in the best way and the main thing of Vue is that it let's you use both composition and options api. Here is still has an advantage over react.

Could you give us another solution to avoid this error?

Thanks.

**Comment by embarq** [comment]
> Hi,
> 
> I am having the same issue but with a request from a created method. Basically I am trying to do a simple fetch outside the setup function.
> 
> async created() { await this.fetchData(); }
> 
> In the fetch method I'm trying to call nuxt auth composable to retrieve the status of the user.
> 
> const { status, data } = useAuth();
> 
> The error is from useAuth(); I tried using callWithNuxt(who by the way is nowhere mentioned in the docs) and it doesn't work. If I do a entire refactoring and put the call in the setup script or method it works and I understand that I have an option to fix it but the most common use case is to do fetch from create or any other functions. I don't understand how an issue with some many complaints it's closed. Not every component can be written with the setup method in the best way and the main thing of Vue is that it let's you use both composition and options api. Here is still has an advantage over react.
> 
> Could you give us another solution to avoid this error?
> 
> Thanks.

I ran into this issue too(it was way too dank to debug and fix btw). 

I feel like I understand better now thanks to an expanded explanation in the https://github.com/nuxt/nuxt/issues/14269#issuecomment-1397352832.

I was able to fix my stuff by following how it's done in the next-auth: https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/composables/authjs/useAuth.ts#L60.

I have a custom page middleware with some async stuff going on and which had a weird behavior, but after wrapping the middleware function with `defineNuxtRouteMiddleware` as well as refactoring it, everything worked as expected!

Fix that worked for me:

- in case some route middleware has any async/await action going on in it - wrap it with `defineNuxtRouteMiddleware`
- save the reference to the nuxt app
- pass the reference everywhere you use nuxt composables(useState, navigateTo etc.)
- use the `callWithNuxt`

Example:

```ts
// utils/data.ts
export const moreCoolStuff = async (nuxt: NuxtApp) => {
  const result = await callWithNuxt(nuxt, () => useFetch('/api/cool-stuff'))
  // ...
}
  
// composables/cool-stuff.ts
export const useCoolStuff = async (nuxt: NuxtApp) => {
  try {
    await moreCoolStuff(nuxt)
  } catch(error) {
    return await callWithNuxt(nuxt, () => navigateTo('/failed'))
  }
}
```
```vue
<!-- page.vue -->
<script setup lang="ts">
definePageMeta({
  middleware: [
    defineNuxtRouteMiddleware(async (to, from) => {
      const nuxt = useNuxtApp()

      return await useCoolStuff(nuxt, to)
    })
  ]
})
</script>
```

**Comment by AnsonCar** [comment]
> Hi @KonstantinVlasov, yes, I made a plugin to handle the async operation and share the auth data using Nuxt's `useState` which I can then check inside the middleware. You can see an example here: https://stackblitz.com/edit/nuxt-starter-1dvjxv?file=middleware%2Fauth.ts
> 
> Ideally the usage of `useState` should be abstracted to a composable which contains all auth data and operations used by the rest of the app, so that when the user logs out for example you can update the shared state in a single place and the middleware gets the latest updated value next time it runs. You can check the code in this repo as an example for implementing this: https://github.com/amrnn90/breeze-nuxt

Thanks, that's very helpful

**Comment by simonmaass** [comment]
I still have this in nuxt 4.x
