### ISSUE TITLE
useAsyncData silently ignore error if the function returns a rejected Promise

### ISSUE THREAD

**Issue by tkesgar** [nuxt/nuxt.js#14274]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://codesandbox.io/s/festive-chatterjee-wol3n4?file=/pages/async-composable.vue

### Describe the bug

When a function throws an error and called inside `useAsyncData`, the component will fail to render (show the error page).

![image](https://user-images.githubusercontent.com/2698543/178091646-90a1c4fa-3761-4456-81ab-cc6bcf71ff9e.png)

However, when the function returns _a rejected Promise_, the component will silently continue to render (does not show the error page).

![image](https://user-images.githubusercontent.com/2698543/178091636-2986f1ba-c31a-4afc-98ad-a5bf7ae8e2f5.png)

I do not know if this behavior is expected, and I do not know if this is the correct practice in working with `useAsyncData`. I think if the function returns a rejected Promise, the page should fail to render just like if the function throws an error.

In my experience, I have difficulty in debugging a function like this because there are no error messages shown:

```js
export async function useGames() {
  const { streams } = await queryContent("/challenge").findOne()
  
  // Should be .flat() instead of .flatten()
  const games = streams.map(stream => stream.games).flatten()

  return games
}
```

**Comment by modbender** [comment]
I still get 404 errors when prerendering, nuxt 3 content latest version
