### ISSUE TITLE
external js included before the end </body> tag?

### ISSUE THREAD

**Issue by funkyLover** [nuxt/nuxt.js#1428]
hi there, I got some problem when using external static js. I want to include the js before `</body>`, but I only find the configure of `head.script`. is that not allowed to include js inside body now?

**Comment by cretueusebiu** [comment]
You can create an `app.html` file with the [app template](https://github.com/nuxt/nuxt.js/blob/dev/lib/app/views/app.template.html) and add your script tag there:

```html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}

    <script src="external-script.js"></script>
  </body>
</html>
```

**Comment by rolandszpond** [comment]
I tried doing this cause it seems simple enough, but the generated pages ends at the end of the inserted script and doesn't include the closing body and html tags...
```
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}

	 <script type="text/javascript">_satellite.pageBottom();</script>​
  </body>
</html>
```
