### ISSUE TITLE
data not changing with useAsyncData watch route 

### ISSUE THREAD

**Issue by graphicfox** [nuxt/nuxt.js#14303]

**Comment by chrisspiegl** [comment]
I found that I can get the slug to update the useAsyncDate by wrapping the route param into a `computed()`

May be a workaround but it does seem to work based on a few test and trials I did.

```js
import { useRoute } from 'vue-router'
const route = useRoute()
const idOrSlug = computed(() => route.params.idOrSlug)
const { data: libraryVideo } = await useAsyncData(() => libraryVideoStore.fetchBySlugOrId(idOrSlug.value), { watch: [idOrSlug] })
```

**Comment by thisismydesign** [comment]
In my case, on Nuxt 2 Bridge,`watch: [route]` resulted in an infinite loop (`RangeError: Maximum call stack size exceeded`).

Could find much on this issue and ended up using the flag workaround: https://stackoverflow.com/a/75952272/2771889

**Comment by michaelpumo** [comment]
> I found that I can get the slug to update the useAsyncDate by wrapping the route param into a `computed()`
> 
> May be a workaround but it does seem to work based on a few test and trials I did.
> 
> ```js
> import { useRoute } from 'vue-router'
> const route = useRoute()
> const idOrSlug = computed(() => route.params.idOrSlug)
> const { data: libraryVideo } = await useAsyncData(() => libraryVideoStore.fetchBySlugOrId(idOrSlug.value), { watch: [idOrSlug] })
> ```
> 
> I also noticed that things behave differently if I import the `vue-router` manually or if I just try to use the one that get's auto imported. So I included it here.

This is the best work-around for sure. Watch works fine with a `ref()` or `computed()` so just reactively watch the route from there.

**Comment by MarcoTroost** [comment]
@chrisspiegl Works like a charm!  

It seems to be the key that is causing the data not to update whenever the route changes.
Snippet below works for me.

```
const _key = computed(() => 'dream_' + route.params.id)

const {data: dream} = await useAsyncData<Dream>(
  _key.value,
  () => $fetch(`${config.public.apiBase}/dream/${route.params.id}`),
  {
    watch: [() => route.params.id],
  }
)
```

(i encountered this problem in a Nuxt _generated_ site)

regards, Marco
