### ISSUE TITLE
PublicPath for different env?

### ISSUE THREAD

**Issue by yezongyang** [nuxt/nuxt.js#1430]
I want to use nuxt generate to build html in different environment and different publicPath. But i don't know how ?

In dev env, the publicPath is "/"

In staging env, the publicPath is "test-static.xxxcdn.com"

In production env, the publicPath should be "static.xxxcdn.com"

**Comment by cretueusebiu** [comment]
What I do in cases like this is install [dotenv](https://www.npmjs.com/package/dotenv) and load it in `nuxt.config.js`. Then I can define environment variables in the `.env` file (which is ignored from git).

**Comment by yezongyang** [comment]
you mean that building project is in staging and production server, not local? now i have to use shipit.js to build project in local and push project to remote server

**Comment by cretueusebiu** [comment]
In that case you can use inline env variables:

````json
"scripts": {
  "generate-dev": "MY_ENV=value-dev nuxt generate",
  "generate-prod": "MY_ENV=value-prod nuxt generate"
}
````

**Comment by yezongyang** [comment]
I thought that maybe i can build in staging server, but build in local and push finished project to production server

**Comment by yezongyang** [comment]
Appreciate for your help @cretueusebiu
