### ISSUE TITLE
Update Nuxt

### ISSUE THREAD

**Issue by krasevych** [nuxt/nuxt.js#1431]
Hi!
How can I update my current project with Nuxt version 1.0.5 to rc5 ?

**Comment by Atinux** [comment]
https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc5 :)

**Comment by krasevych** [comment]
@Atinux no, I mean how can I make update in Existing project where is old version of nuxt ?

**Comment by Atinux** [comment]
Yes you can, make sure to read the [releases notes](https://github.com/nuxt/nuxt.js/releases) to make sure you apply the required modifications.
