### ISSUE TITLE
Question: difference between fetch and asyncData 

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#1432]
Hi!

It is confusing when to use [fetch](https://nuxtjs.org/api/pages-fetch) and when [asyncData](https://nuxtjs.org/api/)

They both can:
- access context (store, params)
- both can be called from the server-side

If I understand correctly I should use `fetch` when I want to fill the store and `asyncData` when I want to set up component data.

But `asyncData` can access store too. So why there are these two methods?

**Comment by yezongyang** [comment]
fetch for vuex, asyncData for page data?

**Comment by cretueusebiu** [comment]
Use `asyncData` only when you need to return data for the current component.

Use `fetch` when you want to work with the store.

**Comment by Atinux** [comment]
@cretueusebiu answer is the one :)

When you need to fetch some data for the store especially for a specific page (like search results), use `fetch`, otherwise, use `asyncData`.
