### ISSUE TITLE
typeCheck: true does nothing

### ISSUE THREAD

**Issue by StefanCardnell** [nuxt/nuxt.js#14336]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.5.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1) Create a new Nuxt 3 project with `nuxi init app`.
2) Add the following at the top of `app.vue`:

```
<script setup lang="ts">
  const add = function(a: number, b: number) {
    return a + b;
  }
  console.log(add(2,"3"));
</script>
```

IDE will warn that `add(2, "3")` is not valid.

3) Add the following to `nuxt.config.ts`:

```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    typescript: {
        strict: true,
        typeCheck: true
    }
})
```

3) Run `npm run dev`
4) At this point I experience an issue that TypeScript is not installed. I'm confused, because the documentation does not mention installing TypeScript manually to be able to able to perform type checking (https://v3.nuxtjs.org/guide/concepts/typescript). Nevertheless use `npm install typescript --save-dev`
5) Run `npm run dev` again. It is successful when it should complain that the types of the function arguments are incorrect.

### Describe the bug

1) TypeScript needs to be installed manually for type checking, the documentation doesn't mention this.
2) `typeCheck: true` in `defineNuxtConfig` isn't working.

### Additional context

I see the issue was already raised and closed here and the linked ticket is merged to rc5. However the issue still exists:

https://github.com/nuxt/nuxt.js/issues/14013

**Comment by KnifeFed** [comment]
Did this break again or something? In Nuxt 3.4.3 I've added `typescript.typeCheck: true` but I'm not seeing any errors in the terminal while running `pnpm dev`. I do see them when running `pnpm exec nuxi typecheck`/`pnpm exec vue-tsc --noEmit`. Following [this SO answer](https://stackoverflow.com/a/75522089) makes it work via `vite-plugin-checker` but I assume that shouldn't be necessary as it's not mentioned anywhere in the official docs.

**Comment by danielroe** [comment]
Yes, there seems to be a new issue with showing the overlay, and it's been documented in `vite-plugin-checker`'s docs.

**Comment by KnifeFed** [comment]
Ah, I see. It's not just the overlay though, it's the console output as well.

**Comment by danielroe** [comment]
Thanks for spotting. Opened an issue to track: https://github.com/nuxt/nuxt/issues/20851
