### ISSUE TITLE
i can not use '~' in my vue file

### ISSUE THREAD

**Issue by fantasthu** [nuxt/nuxt.js#1434]
i can not use '~' in my vue file,error log like this:
=====
in ./node_modules/babel-loader/lib?{"presets":["es2015","stage-0"],"plugins":["transform-runtime"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
Module not found: Error: Can't resolve '~components/TopNav.vue' in '/Users/huwenzhi/WebstormProjects/workspace/huwenzhi/pages'

**Comment by pi0** [comment]
Hi. Please check latest docs. `~components` should be changed to `~/components`

**Comment by fantasthu** [comment]
that is because i saw the chinese website was not update ? thank you

**Comment by pi0** [comment]
@fantasthu Indeed making a PR for Chinese version in [docs](https://github.com/nuxt/docs) would help many more chinese people if you have time :)

**Comment by fantasthu** [comment]
@pi0  thank you very much
