### ISSUE TITLE
Top-level await not available for Target ES2019 - TSConfig shows ESNEXT

### ISSUE THREAD

**Issue by folson-csi** [nuxt/nuxt.js#14348]

**Comment by GabrielRogath** [comment]
https://github.com/nuxt/nuxt/issues/14348#issuecomment-1397356240

Thanks @danielroe , This was very helpfull

**Comment by wduandy** [comment]
> 

H

> To change the esbuild target for your nitro build, you can do:
> 
> ```js
> import { defineNuxtConfig } from 'nuxt'
> 
> export default defineNuxtConfig({
>   nitro: {
>     esbuild: {
>       options: {
>         target: 'esnext'
>       }
>     }
>   }
> })
> ```
> 
> However, it is not advised to do so. Instead, I would recommend using `defineLazyEventHandler` to run the setup task for your handler.

@danielroe, apologies for reopening this issue. Could you explain why it's not recommended? Are there performance concerns? I couldn't locate any samples of using defineLazyEventHandler. Can you provide one for me?

**Comment by danielroe** [comment]
There are not performance concerns, but ideally we should manage this target centrally: https://github.com/nuxt/nuxt/issues/14893.

Here's an example of `defineLazyEventHandler`:

```js
export default defineLazyEventHandler(async () => {
  // perform one-off set up tasks here

  // return event handler that will be called for each request
  return defineEventHandler(async event => {
    return {}
  })
})
```

**Comment by guska8** [comment]
For anyone using `builder:'webpack', i got a fix directly from nuxt source code:

```
  hooks: {
    'webpack:config' (configs) {
      // in order to test bigint serialization we need to set target to a more modern one
      for (const config of configs) {
        const esbuildRules = config.module.rules.filter(
          rule => typeof rule === 'object' && rule && 'loader' in rule && rule.loader === 'esbuild-loader',
        )
        for (const rule of esbuildRules) {
          if (typeof rule === 'object' && typeof rule.options === 'object') {
            rule.options.target = 'es2022'
          }
        }
      }
    }
  }
```
