### ISSUE TITLE
Cannot read property 'layout' of undefined

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#1437]
Tried new spa mode and get this error message "Cannot read property 'layout' of undefined" with `npm run dev` on all pages except index.

Any idea what this can be? Thanks

**Comment by pi0** [comment]
Hi @husayt. Are you using the router in `hashed` mode? Any reproduction code or repo would be so nice.

**Comment by kepek** [comment]
Hi @husayt @pi0, not sure if this will help you... but I had exactly same issue in SPA mode. Issue is gone after removing [@vuejs/vuex-router-sync](https://github.com/vuejs/vuex-router-sync) from the project

**Comment by husayt** [comment]
Indeed @pi0 I am using hash mode. I will try to share reproducible code. Maybe the reason is that I have multiple layouts?

@kepek  no vuex-router-sync is not the cause for this one.

**Comment by Atinux** [comment]
Could you create a reproduction repo for this @husayt please an re-open the issue when done?

**Comment by simplesmiler** [comment]
I can confirm, that spa mode with hash routing indeed results in this issue. The index page gets loaded properly, but if you go to another page, and refresh there, the error message appears.

Repro: https://github.com/simplesmiler/nuxt-spa-hash-issue

**Comment by pi0** [comment]
@simplesmiler It should be fixed with #1532 with next release :)
