### ISSUE TITLE
Invalid character in statusMessage.

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#1438]
[async-data-bug.zip](https://github.com/nuxt/nuxt.js/files/1240674/async-data-bug.zip)

```shell

npm i
npm run dev

```

![image](https://user-images.githubusercontent.com/17898715/29547371-34e6a8b8-872c-11e7-86dd-dc0b03058a1f.png)

**Comment by yuchonghua** [comment]
[Add err.statusMessage || err.errorId](https://github.com/nuxt/nuxt.js/pull/1439)

**Comment by yuchonghua** [comment]
I am looking forward to be able to directly support the wrong object inside the err.statusMessage || err.errorId,
thank you very much

**Comment by yuchonghua** [comment]
>* Because i can join my statusMessage support at my request to support more detailed error hints

![image](https://user-images.githubusercontent.com/17898715/29547910-a912c1f6-872f-11e7-8928-ed497b4607b5.png)

**Comment by alekbarszczewski** [comment]
@yuchonghua I am getting same error message right now... How can I fix it? I am getting it on rc-4 and rc-6. Strange thing is that till today it was OK on rc-4. When today I saw this error I tried to upgrade to rc-6 but still getting this error.

![screen shot 2017-08-22 at 07 26 58](https://user-images.githubusercontent.com/2742373/29549974-7fe997b0-870b-11e7-993c-f98b7dd4a742.png)

**Comment by yuchonghua** [comment]
@alekbarszczewski I have to nuxt [pr](https://github.com/nuxt/nuxt.js/pull/1439), waiting for nuxt reply

**Comment by HadiChen** [comment]
Support pr

**Comment by yeziZ** [comment]
I also encountered this problem, look forward to repair

**Comment by linyueb** [comment]
Support pr

**Comment by Ethennoob** [comment]
I upgraded rc-6 also encountered a multi-language problem, support pr

**Comment by zengfanyao** [comment]
I upgraded rc-6 also encountered a multi-language problem
