### ISSUE TITLE
ReferenceError: document is not defined after load route from client browser

### ISSUE THREAD

**Issue by koddr** [nuxt/nuxt.js#144]
Hello.

I try to update/reload function (after click and land on page trough `<nuxt-link>`), who make pretty background image (I'm using my own npm package: https://www.npmjs.com/package/goodbackground.js) for container with `data-background-image` attribute.

On my `nuxt.config.js`:

```javascript
...
build: {
  vendor: [
    'goodbackground.js'
  ]
},
...
```

I use `beforeCreate` instance into this `index.vue` file:

```html
<template>
  <div>
    <section data-background-image="/images/projects/background.jpg">
      Hello World!
    </section>
  </div>
</template>

<script>
  require('goodbackground.js');

  export default {
    head () {...},
    beforeCreate () {
      new GoodBackground().make();
    }
  }
</script>
```

But Nuxt.js show me red error page with message:

```bash
ReferenceError: document is not defined
    at t.value (node_modules/goodbackground.js/goodbackground.min.js:1:1392)
    at Object.<anonymous> (node_modules/goodbackground.js/goodbackground.min.js:1:2432)
    at e (node_modules/goodbackground.js/goodbackground.min.js:1:163)
    at node_modules/goodbackground.js/goodbackground.min.js:1:546
    at Object.<anonymous> (node_modules/goodbackground.js/goodbackground.min.js:1:555)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

This is simple code of my package: https://github.com/koddr/goodbackground.js/blob/master/src/goodbackground.js

Whats wrong? I don't see this if I reload page (cmd+R).. How to fix it?

**Comment by alexchopin** [comment]
Hi,
It's because document is not defined on the server-side.
Please have a look on those links:
[Plugins only for browsers](https://nuxtjs.org/guide/plugins#only-for-browsers)
['Window is not defined' where do I put client-side only scripts?](https://github.com/nuxt/nuxt.js/issues/30)
[window is not defined with element-ui](https://github.com/nuxt/nuxt.js/issues/21)

**Comment by koddr** [comment]
Still not working. Help not wanted.

I create file `./plugins/gb_plugin.js`:

```javascript
import Vue from 'vue'; // IDE show me warning, vue not found O_o

const gb = require('goodbackground.js');
Vue.use(gb); // and warning again with method use()..
```
nuxt.config.js

```javascript
...
plugins: [
  'plugins/goodbackground.js'
],
...
```
And get message `ReferenceError: document is not defined ...` again.. 
Any help?
