### ISSUE TITLE
global css breaking changes

### ISSUE THREAD

**Issue by RezaHaidari** [nuxt/nuxt.js#1441]
When upgraded nuxt to rc5 or rc6 styles doesn't transfer to css ! any new config ? breaking changes? or bug?

![postcss](https://user-images.githubusercontent.com/12013210/29550684-44fe67c0-8724-11e7-99af-f5ead4a13fa5.PNG)

**Comment by IlyaSemenov** [comment]
Also CSS doesn't import anymore from SCSS (e.g. `@import '~material-design-icons/iconfont/material-icons.css';` in `assets/css/main.scss` says file not found - downgrading to rc4 fixes it.)

**Comment by pi0** [comment]
These breaking changes are normal as Nuxt <= rc4 was not probably using postcss for global imports. @RezaHaidari is your real vars file name `__vars.css` ? I think it should be renamed `scss` if sass is used. 

@IlyaSemenov Simply import like this:
```css
@import 'material-design-icons/iconfont/material-icons.css';
```
![image](https://user-images.githubusercontent.com/5158436/29558871-a9324504-8742-11e7-8437-d3ed1132c218.png)

**Comment by Javid-Izadfar** [comment]
@RezaHaidari @pi0 it's not `sass`, it's `postcss-simple-vars`. I tried sass (just for sake of it) and it worked properly. 
could it be from postcss config?

**Comment by pi0** [comment]
@Javid-Izadfar You can either use sass (recommended) or any postcss plugin you want. Just create a `postcss.config.js` in root of project. By default nuxt uses [cssnext](http://cssnext.io) which is supporting this features:
![image](https://user-images.githubusercontent.com/5158436/29569278-44048d10-8768-11e7-865a-1083ae759f35.png)

**Comment by Javid-Izadfar** [comment]
@pi0 `postcss.config.js` did the job. 
why we moved configs to `nuxt.config.js` at first place?

**Comment by pi0** [comment]
@Javid-Izadfar `nuxt.config.js` supports `postcss` too for easier usage :)) So most of the users have a modern postcss preset by default without the need to any external configuration.
