### ISSUE TITLE
mint-ui document is not defined

### ISSUE THREAD

**Issue by webwyb** [nuxt/nuxt.js#1442]
![image](https://user-images.githubusercontent.com/23635787/29552067-4790719e-8748-11e7-983d-a33952cd77ef.png)
this is block me when i coding

**Comment by pi0** [comment]
Hi @webwyb . Actually, the problem is that `minit-ui` is not supporting SSR! If you really need it you can disable ssr using `mode: 'spa'` in `nuxt.config.js` but you will loose benefits of SSR. Maybe @yuchonghua  can help more as he was involved in SSR support for mint (ElemeFE/mint-ui#548)

**Comment by yuchonghua** [comment]
What is your specific use code? I have just tested, it can be ssr, I have been using this ssr ah
/ping @webwyb

**Comment by Joshwoooooooooooooooooooooooooooooooong** [comment]
@webwyb your error information like friendly! can you tell me how to generate page like that?thanks.
