### ISSUE TITLE
Cannot find nitro.json after build inside Docker

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/nuxt.js#14433]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

* Clone this repo: https://github.com/HendrikJan/nuxt3-problem
* Follow the steps in the README
* See that `npm run build` give this error inside Docker: `ACCES: permission denied, stat '/root/.node_modules/file:/var/app/node_modules/unenv/runtime/mock'`
* See that `npm run start` gives this error: `ERROR  Cannot find nitro.json.`
* See that you do *not* get an error outside Docker

### Describe the bug

Nuxt (or Nuxi) can build and run without problems outside Docker, but inside docker we get errors and the server does not start.

### Additional context

`nuxt dev` works with no problem, writing to the `/.nuxt`-folder, so permissions seem to be ok.

**Comment by wukzu** [comment]
Hi, any fix about this error ? I got the same.

![image](https://user-images.githubusercontent.com/23450885/214699778-297b64f0-cde1-4ce1-a919-1a4689af1a99.png)

No problem during `npm run build`

**Comment by danielroe** [comment]
You should not run `nuxi preview` in production. It is just for a developer preview. Instead, run `node .output/server/index.mjs`.

**Comment by PaulloClara** [comment]
I had the same problem, and for me, it worked by removing the node_modules and .nuxt folders, and then running yarn -i.
