### ISSUE TITLE
Static SPA deployment

### ISSUE THREAD

**Issue by antho1404** [nuxt/nuxt.js#1444]
Is there a way to deploy the application as a static website (that can be hosted on s3, netlify, firebase...) so without the need to run the `nuxt start`.

I know there is the `nuxt generate` command but this one will generate all the pages according to the data you give at build time, exemple the page `/users/3` but what happen if a new user register, we have to redeploy for this guy... so this is not a solution for complex application.

I would like to have something similar to the [webpack based vue config](https://github.com/vuejs-templates/webpack/tree/master/template) with the `npm run build` where the output is a simple index.html (similar to the one in `.nuxt/dist/index.spa.html`) file with all the assets generated.

**Comment by husayt** [comment]
You are just in time. With rc5 release couple of days ago proper spa support has been added. Read release notes and see example, as there's not much documentation. I have been waiting for this for long time, now just need to figure out how it works. 

Key for your scenario is hash based routing, as it supports one index.html file. But there is not much documentation on it and I haven't seen any realistic examples. So I have some issues which I am trying to overcome. Once I am done, then I will try to publish an example.

**Comment by antho1404** [comment]
Hooo quick and perfect answer, I was still on the rc3 and just see yesterday that I was late already I will quickly update and test that. The documentation will be perfect but no rush I'm sure I can deal to look in the sources for that :)

**Comment by antho1404** [comment]
Just update and follow this exemple (https://github.com/nuxt/nuxt.js/tree/dev/examples/spa) and it works like a charm and even with some nice loaders :)

**Comment by Atinux** [comment]
With last releases (rc5 & rc6), with spa mode, you can run `nuxt build` and then deploy your `dist/` folder to any static hosting which supports SPA (by default it works perfectly with http://surge.sh/)
