### ISSUE TITLE
when using <ClientOnly> nuxt3 application fails with the following error:  "Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec."

### ISSUE THREAD

**Issue by Schetnan** [nuxt/nuxt.js#14485]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@6.14.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1). Clone the following project:  https://github.com/Schetnan/nuxttest
2). Execute the following instructions

npm install
npm run build2 ( build using ‘node’ preset )
npm run start:express
In browser, go to: http://localhost:8082/fcp/tst

### Describe the bug

Application will come up with a blank screen and in the console, the following error:  

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

### Logs

```shell
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by Fredemb** [comment]
> Hi. I think we can close this issue.
> 
> We have added to this code for server configuration.
> 
> ```
> location ~ \.js {
>         add_header Content-Type text/javascript;
>     }
> ```
> 
> Thank you. [@misaon](https://github.com/misaon)

Where exactly have you added this code?
