### ISSUE TITLE
allow disabling auto imports

### ISSUE THREAD

**Issue by darthf1** [nuxt/nuxt.js#14505]

**Comment by Skwai** [comment]
I really think auto-importing is a bad design feature. One of the reasons I dislike RoR. Not knowing explicitly where your code is coming from makes large projects (especially onboarding new devs into projects) extremely hard to reason about. But that's just my opinion.

**Comment by danielroe** [comment]
You should be able to see where any auto import is coming from by clicking on it in your ide. There are also tools in Nuxt devtools that will show you a bigger overview.

**Comment by Skwai** [comment]
@danielroe that's just the tip of the iceberg. I'm currently battling how to set up Vitest to work with Nuxt3 (Nuxt tests are barely mentioned, not how to configure test frameworks to work with auto-imports).

I'm also trying to work out how to override the type definitions for a Nuxt3 plugin that's being auto imported.

The extra complexity required to get this feature to work is not nearly worth it (IMO).

**Comment by Skwai** [comment]
I also don't get why we need to alias `#imports` and not import out of the actual package itself (like regular Vue).

**Comment by danielroe** [comment]
You can use https://github.com/danielroe/nuxt-vitest, where these should all be set up for you.

**Comment by Skwai** [comment]
I'm using that but it doesn't cover several things eg. `useRuntimeConfig` which then has to be mocked right but it's not clearly stated?

Trying to get everything working is a real dance.

**Comment by Skwai** [comment]
How it feels:

![blinds-venetian](https://github.com/nuxt/nuxt/assets/384454/e596a7a5-2be3-4ae1-bc18-91afeb06a5cf)

**Comment by Skwai** [comment]
Let me state that I appreciate everything you guys have created here.

But as someone who has been a long time user of Vue, there are several design decisions made in Nuxt that are relatively alien to Vue and trying to achieve simplicity (eg. auto-imports) just moves the complexity elsewhere.

If someone is using Nuxt they _probably_ also know how to use Vue (which doesn't have auto-importing) so I'm not sure who we're trying to protect with this feature.

**Comment by cawa-93** [comment]
Nuxt's imports design is just abyss of problems. Especially refactoring. You know, move files, rename them, group things. Casual things, but in Nuxt it's incredible pinhead pleasure. 🤌🤌🤌
That was more than a year ago when I wrote in the original discussion. Since then, not much has changed.

**Comment by cawa-93** [comment]
My favorite is naming collision 🤤. This is such an apt retrospect of the 00 years, when all variables were global, and one module in some file affected the work of another.  Nice 🙃
https://twitter.com/alex_kozack/status/1659141957275340800

**Comment by basemkhirat** [comment]
With big projects. Auto import works like a hell. It should be turned of by default.

**Comment by ByScripts** [comment]
I really don't like the auto import feature either.

It should be an opt-in, not an opt-out.

At least we should be able to disable it completely, easily.

BTW, is there a way to disable the generation of `imports.d.ts`? I don't want to import from `#imports`

I added this in `nuxt.config.ts`, but it's not sufficient:
```ts
  components: false,
  imports: {
    autoImport: false,
  },
```

**Comment by drewsher** [comment]
I was able to partially disable auto-import. in my case, it was necessary to exclude utils from the general list of auto-imports. To do this, you need to use the imports:dirs hook to remove the element, but not return anything:

```js
export default defineNuxtConfig({
  hooks: {
    'imports:dirs'(dirs) {
       const rules = ['utils'];

       for (const rule of rules) {
         const index = dirs.findIndex((dir) => dir.includes(rule));

         dirs.splice(index, 1);
       }
    }
  }
})
```
