### ISSUE TITLE
useRoute() does not return reactive object

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.js#14503]
I have something related, when I use the route.name in a computed variable OR use the route(.name) in a watch function it doesn't get triggered after navigating.

When I output the $route.name in the template tag, this does get updated after navigating.

Some additional info, when I do the following:

In RC.6
```js
console.log(useRoute());

Output:

Proxy with computed values
```

In edge
```js
console.log(useRoute());

Output:

Regular json object with values
```

_Originally posted by @rvmourik in https://github.com/nuxt/nuxt.js/issues/14462

**Comment by VladBrok37** [comment]
is it resolved? I have a computed, inside which I use `route`, and it is not updated when route.params update. If I use router.currentRoute instead, everything works. @pi0 could you please reopen the issue?

**Comment by danielroe** [comment]
@VladBrok37 You are welcome to open a new issue with a reproduction.

**Comment by riddla** [comment]
Also stumbled on this, had to use `useRouter().currentRoute.value.params` for reactive route parameters.

**Comment by manniL** [comment]
@riddla see https://github.com/nuxt/nuxt/issues/24798

**Comment by danielroe** [comment]
something like:

```ts
watch(() => route, () => {}, { deep: true })
```

you might not need the last option

**Comment by j0rgedev** [comment]
computed isn't working for me either, I needed to use

> useRouter().currentRoute.value.params

as @riddla suggested.

However, if I explicitly import useRoute from vue-router, it works with the computed property.
