### ISSUE TITLE
Why the Custom Loading Component may not work?

### ISSUE THREAD

**Issue by Jussiadev** [nuxt/nuxt.js#1454]
My nuxt.config.js

```
module.exports = {
    // loading: false,
    // loading: '~/components/loading.vue',
    loading: {
        color: 'red',
        height: '5px'
    },
    head: {
        meta: [
            {charset: 'utf-8'},
            {'http-equiv': 'X-UA-Compatible', content: 'IE=edge'}
        ]
    },
    build: {
        extractCSS: true
    }
};
```

I have a layout and some components. I'm including to pages layout and components. None of the  loading are included

**Comment by Atinux** [comment]
@Jussiadev please provide a reproduction repository and re-open the issue when done.

I tried with [custom-loading example](https://github.com/nuxt/nuxt.js/tree/dev/examples/custom-loading) and it works fine (even with adding a layout).

**Comment by Jussiadev** [comment]
!
