### ISSUE TITLE
Error building project since version 1.0rc

### ISSUE THREAD

**Issue by queses** [nuxt/nuxt.js#1455]
Hello!
After upgrading to 1.0rc1 I have got the error:
`(node:10720) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor`
In 1.0rc6 I still getting this error. In 1.0alpa.5 it works normally.
Here is a my [nuxt.config.js](https://pastebin.com/DniHhsYF).
Unfortunatelly, I'm working in a commercial project, so I cant provide all sources.
Thanks!

**Comment by Atinux** [comment]
Hi @queses 

Please read our releases to know the differences & breaking changes: https://github.com/nuxt/nuxt.js/releases

For example, `build.loaders` has been removed, and more changes.
