### ISSUE TITLE
[unhandled] [500] Named export 'addListener' not found: Error after upgrading to rc7 (still present in rc8)

### ISSUE THREAD

**Issue by ahoiroman** [nuxt/nuxt.js#14553]

**Comment by MeikiH** [comment]
@danielroe : I confirm that I could solve my problem ! Thank you ! 👏 

I was trying to deploy my Nuxt3 app on Vercel app and I had an Error 500 Page not available.

Looking at the Vercel app logs, I saw the same error log as @ahoiroman :
"_[nuxt] [request error] [unhandled] [500] Named export 'addListener' not found. The requested module 'resize-detector' is a CommonJS module, which may not support all module.exports as named exports._"

I simply fixed it by adding 'resize-detector' in my nuxt.config.ts build transpile declaration as you did here :
https://stackblitz.com/edit/github-nycwvg?file=nuxt.config.ts

And it worked !
