### ISSUE TITLE
Access the mode property from inside a plugin?

### ISSUE THREAD

**Issue by stursby** [nuxt/nuxt.js#1456]
Is this possible? I'd like to check if the build is running in `spa` mode inside `/plugins/`.

And also, would it make a difference if mode is set via `nuxt.config.js` or via cli argument?

```js
// nuxt.config.js

module.exports = {
  mode: 'spa' // or 'universal'
}
```

vs

```json
// package.json
...

"scripts" : {
   "build" : "nuxt build --spa"
}

...
```

And then in a plugin (ie: `/plugins/my-plugin.js`

```js
// my-plugin.js

// not working, but example
const mode = options.mode  // 'spa' or 'universal'

```

**Comment by Atinux** [comment]
Hi @stursby 

Actually it does not change anything, when using `--spa`, we only overwrite the `mode` key from `nuxt.config.js` (https://github.com/nuxt/nuxt.js/blob/dev/bin/nuxt-dev#L117).

What would be your example to know the `mode`? Actually you can use `process.server` and `process.client` to know where the plugin is run from.

**Comment by stursby** [comment]
@Atinux so I have to separate builds, `stage` and `prod`. I would like to build stage in `--spa` mode and have it continue to hit a live API to power the page data. And the `prod` build will generate the JSON files and only use those to power the pages via the `/data/` folder.

**Comment by Atinux** [comment]
I just added `process.mode` with https://github.com/nuxt/nuxt.js/commit/04d05de9067bd9fcddb0c0300dc87265e58360a3, it will be accessible in next release.

It can be useful for plugins as well to have a different behavior depending of the mode.

Actually you can already use `env` to set your stage:
`nuxt.config.js`:
```js
module.exports = {
  env: {
    stage: process.env.STAGE || 'dev'
  }
}
```

And in your `package.json`:
```js
"scripts": {
  "dev": "nuxt",
  "build:stage": "STAGE=staging nuxt build --spa",
  "build:prod": "STAGE=prod nuxt generate"
}
```

And then you can use `process.env.stage` into your plugins :)
