### ISSUE TITLE
render empty page when <nuxt/> has brother dom.

### ISSUE THREAD

**Issue by fwchen** [nuxt/nuxt.js#1457]
```
<template>
  <div>
    <nuxt/>
    <footer>
      <a class="filing" href="http://www.miitbeian.gov.cn/" target="_bank">粤ICP备17098096号</a>
    </footer>
  </div>
</template>
```
note that footer, it works when `npm run dev`, but after generate static pages,

Browser render html correct, but it render empty nuxt content after js loaded.(flash)

**Comment by Atinux** [comment]
Hi @fwchen 

I just tried and it works perfectly: http://nuxt-issue-1457.surge.sh/

`layouts/default.vue`:
```js
<template>
  <div>
    <nuxt/>
    <footer>
      <a href="https://nuxtjs.org" target="_bank">Nuxt.js Website</a>
    </footer>
  </div>
</template>

<style scoped>
footer {
  border-top: 1px #eee solid;
  margin-top: 20px;
  padding: 20px;
}
</style>
```

Please check that your DNS or server does not update your HTML (by adding some scripts for example) before sending back the page.

**Comment by fwchen** [comment]
@Atinux hi big brother, can you check my project(https://github.com/fwchen/holothuroidea-web)?  It can run.

I found the result at `pages/c.vue`
when i remove the `asyncData` and async data rendered in html, it work.
Or remove footer at `layouts/default.vue`, it work too.

eh..........it is a bug?

**Comment by fwchen** [comment]
@Atinux 
@Atinux
Hi big brother, can you check my project(https://github.com/fwchen/holothuroidea-web)? It can run. and simple.

I found the reason at `page/c.vue`
when I remove the `asyncData` `mounted` and those data rendered in html, it work. (`npm run generate && http-server ./dist`)
Or remove footer at `layouts/default.vue`, it work too.

eh........it is a bug?

**Comment by fwchen** [comment]
@Atinux

**Comment by fwchen** [comment]
who can open it again?

**Comment by DaxChen** [comment]
+1
I got this problem too.
Still trying to find out the cause and/or make a reproduction...

I'm guessing that this is related to the service worker registered by the `@nuxt/pwa` module, because this only happens when deployed to production server.

**Comment by DaxChen** [comment]
I think I found some hint!
It's the scripts loading order!
If the page.xxx.js is loaded before layout.xxx.js, components in the layout will be removed.

Oh and I can't find the `<head />` tag in generated html, is this normal?!

@Atinux @alexchopin @pi0 I still can't make a reproduction yet, but are these hints enough to make you think of potential causes?
