### ISSUE TITLE
Cannot find module '#components' or its corresponding type declarations.

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#14589]

**Comment by klesun** [comment]
Importing from '#build/components' results in `Cannot find module '#build/components' or its corresponding type declarations` too. `@nuxt/types` v2.16.3. `@nuxt/typescript-build` v3.0.1. `nuxt` v3.5.0

**Comment by danielroe** [comment]
You should import from `#components` not `#build/components`.

**Comment by klesun** [comment]
Oh, apparently you need this in tsconfig.json for `#components` import to work:
```json
{
  "compilerOptions": {
    "paths": {
      "#components": [
        ".nuxt/components"
      ]
    },
```

**Comment by danielroe** [comment]
No, you don't. You should instead extend the generated Nuxt tsconfig, like this: https://github.com/nuxt/starter/blob/v3/tsconfig.json.

More info: https://nuxt.com/docs/guide/concepts/typescript#nuxttsconfigjson
