### ISSUE TITLE
Delay transition to new page

### ISSUE THREAD

**Issue by acollins1991** [nuxt/nuxt.js#1458]
Is there a way to delay the transition from one page to another via a nuxt-link?

I would like to use a more substantial page loader [https://github.com/Wikiki/bulma-pageloader](https://github.com/Wikiki/bulma-pageloader) but need to allow the loader to complete it's opening transition before rendering the new page.

**Comment by Atinux** [comment]
@acollins1991 you can use a middleware for it:

`middleware/delay.js`:
```js
export default ({ isClient }) => {
  // Use the middleware only on client-side
  if (!isClient) return
  // Return a promise to tell nuxt.js to wait for the end of it
  return new Promise((resolve) => {
    // Wait 1 second between each route
    setTimeout(resolve, 1000);
  })
}
```

In you `nuxt.config.js`:
```js
module.exports = {
  router: {
    middleware: 'delay'
  }
}
```
