### ISSUE TITLE
Using Passport with NuxtJs

### ISSUE THREAD

**Issue by brainyl** [nuxt/nuxt.js#1459]
From the documentation of Passport JS, I see that it is possible to use it with a Connect based app. However, I have been having issues getting it to work with Nuxt JS.

Most apps rely on social logins for their authentication, so having an example or a guide that points to how it can be done would be appreciated.

**Comment by sahibalejandro** [comment]
Hi!
What issues do you have?
I've been using passport.js with nuxt.js and the only issue (for me) is that passport.deserializeUser() is called on every asset within the `_nuxt`directory.
