### ISSUE TITLE
How to resolve CORS issue in v3?

### ISSUE THREAD

**Issue by gezichenshan** [nuxt/nuxt.js#14598]

**Comment by acche** [comment]
Is there any solution to resolve the CROS ERROR?

**Comment by ddahan** [comment]
I have a similar issue. I'm requesting an external API from Nuxt 3.

```
// Calling the data
const { data, refresh } = await useFetch(url, {
  headers: { Accept: 'application/json', apikey: 'xxxx' },
});

// Refreshing the data automatically every 5sec
useIntervalFn(() => {
  console.log('refresh data');
  refresh();
}, 5000);
```

The first time the page is loaded, everything works as expected. However, everytime the `refresh` method is called, I get an error: 

```
cess to fetch at 'https://xxxxx' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by maximran800** [comment]
HI, just want to share the solution i found here:
https://mookypoo.medium.com/nuxt-js-how-to-handle-cors-error-a4c5022611d0
I'm not sure why it solved the issue. inside the link, it mention to add inside nuxt.config.ts
`// nuxt.config.ts
export default defineNuxtConfig((){
  routeRules: {
      '/web/v1/**': {
          proxy: { to: "http://localhost:9300/web/v1/**", },
      }
    }
})`

**Comment by phuong-leadsoft** [comment]
> 

It worked

**Comment by phuong-leadsoft** [comment]
> HI, just want to share the solution i found here: https://mookypoo.medium.com/nuxt-js-how-to-handle-cors-error-a4c5022611d0 I'm not sure why it solved the issue. inside the link, it mention to add inside nuxt.config.ts `// nuxt.config.ts export default defineNuxtConfig((){ routeRules: { '/web/v1/**': { proxy: { to: "http://localhost:9300/web/v1/**", }, } } })`
> 
> This solve the cors problem that I have. Inside your code, use const url2 = '/web/v1/....'; with useFetch

It worked!

**Comment by vis97c** [comment]
> @HuakunShen
> 
> > The routes setting only works in development mode for me, but doesn't work in production.
> 
> Too me. may route "cors" options not work. use server middleware to solution.
> 
> at server/middleware/cors.ts
> 
> ```
> export default defineEventHandler((event) => {
>   setResponseHeaders(event, {
>     "Access-Control-Allow-Methods": "GET,HEAD,PUT,PATCH,POST,DELETE",
>     "Access-Control-Allow-Origin": "*",
>     'Access-Control-Allow-Credentials': 'true',
>     "Access-Control-Allow-Headers": '*',
>     "Access-Control-Expose-Headers": '*'
>   })
>   if(getMethod(event) === 'OPTIONS'){
>     event.res.statusCode = 204
>     event.res.statusMessage = "No Content."
>     return 'OK'
>   }
> })
> ```

Just what I needed.

For anyone wondering, just use **event.method** intead of ~getMethod~ and **event.node.res** instead of ~event.res~

**Comment by CharlesBT** [comment]
With Nuxt 3.8.2 I did this middleware 👍 

> // server/middleware/cors-preflight-request.ts
> /**
>  * Middleware to respond CORS preflight requests using OPTIONS method.
>  */
> export default defineEventHandler((event) => {
>   // Answers HTTP 204 OK to CORS preflight requests using OPTIONS method :
>   // if (event.method === 'OPTIONS' && isPreflightRequest(event)) {
>   if (isPreflightRequest(event)) {
>     event.node.res.statusCode = 204
>     event.node.res.statusMessage = 'No Content'
>     return 'OK'
>   }
> })

```
// nuxt config
routeRules: {
    '/api/**': {
      // enable CORS
      cors: true, // if enabled, also needs cors-preflight-request.ts Nitro middleware to answer CORS preflight requests
      headers: {
        // CORS headers
        'Access-Control-Allow-Origin': '*', // 'http://example:6006', has to be set to the requesting domain that you want to send the credentials back to
        'Access-Control-Allow-Methods': '*', // 'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Headers': '*', // 'Origin, Content-Type, Accept, Authorization, X-DIVINE, X-Requested-With'
        'Access-Control-Expose-Headers': '*',
        // 'Access-Control-Max-Age': '7200', // 7200 = caching 2 hours (Chromium default), https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age#directives
      },
    },
}
```

**Comment by paramula** [comment]
hi, i'm using plugin "@originjs/vite-plugin-federation". 
result: *Reason: CORS header 'Access-Control-Allow-Origin' missing* error. what i need?

**Comment by Fernando12mais** [comment]
What worked for me was
//nuxt.config.ts
  nitro: {
    routeRules: {
      "/api/**": { proxy: "yourServerAddress/api/**", cors: true },
    },
  }
  
  $fetch('/api/login') for example

**Comment by sondh0127** [comment]
![image](https://github.com/nuxt/nuxt/assets/62163604/4cf786f6-316c-43fe-8f6c-b9385b36e672)
how can I add cors for all assets build

**Comment by ss-web** [comment]
Anybody have idea how to make it works with fastify?

I tried

```
import fastifyCors from '@fastify/cors';
app.register(fastifyCors, {
  origin: '*',
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
 ```

**Comment by whitersun** [comment]
headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET,HEAD,PUT,PATCH,POST,DELETE',
        'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Authorization',
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Max-Age': '0',
      },

I realize this pass work good at any device with '*', but does anybody have idea for hosting url?
I have tried replace '*' to url and work good at windows browsers and android browsers, but not working on iOS.

**Comment by sajiniho07** [comment]
**Fixing CORS Issue in Nuxt.js Using `nuxt.config.ts`**

If you are facing Cross-Origin Resource Sharing (CORS) issues in your Nuxt.js project, you can utilize the `nuxt.config.ts` file to set up proxy rules that tackle this problem effectively.

Below is a simple configuration you can add to your `nuxt.config.ts` to resolve CORS problems:

```javascript
export default {
  routeRules: {
    '/api/**': { proxy: { to: 'http://localhost:8080/**' } }
  }
}
```

By defining a rule that proxies requests made to `/api/` to `http://localhost:8080/`, you can workaround CORS restrictions that might be causing issues with cross-origin requests.

Remember to adapt the proxy target (`http://localhost:8080/` in this case) to match the endpoint you are trying to access, ensuring that your backend server is properly configured to accept these proxied requests.

---

By following these steps and making appropriate adjustments to your `nuxt.config.ts`, you can effectively resolve CORS issues within your Nuxt.js application.

**Comment by MickL** [comment]
@sajiniho07 This works but will result in a unnecessary fetch request. It goes from browser to Nuxt app/function to API then back to Nuxt app and the to browser.
