### ISSUE TITLE
localhost https

### ISSUE THREAD

**Issue by miecio1212** [nuxt/nuxt.js#146]
Hey how can i run localhost on https.
I'm going to make pwa using yours framework and I'd like to test it localy :).

**Comment by Atinux** [comment]
Hi @miecio1212 

You can use nuxt.js programmatically to create an https server:

```js
const https = require('https')
const fs = require('fs')
const Nuxt = require('nuxt')
const isProd = process.env.NODE_ENV === 'production'
const port = process.env.PORT || 3000

// Nuxt.js setup
let config = require('./nuxt.config.js')
config.dev = !isProd
const nuxt = new Nuxt(config)
if (!isProd) {
  nuxt.build() // Build in development mode
}

// HTTPS Server
const options = {
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
}

// Create the server
https
.createServer(options, nuxt.render)
.listen(port)

console.log(`Server listening on https://localhost:${port}`)
```

Then, in your `package.json`:
```json
...
"scripts": {
  "dev": "node server.js",
  "build": "nuxt build",
  "start": "NODE_ENV=production node server.js"
}
...
```

**Comment by miecio1212** [comment]
Hey :D @Atinux Thank you for fast replay.
I'll try it asap and give you feedback.
Btw maybe you could just add flag to nuxt.
'nuxt --https' ? :)

**Comment by Atinux** [comment]
I can't add this option to nuxt since it require more configuration.

I think it's better if the user create its own https server and use nuxt as a middleware.

**Comment by miecio1212** [comment]
Thank you it works great 👍  :>

**Comment by derekshull** [comment]
I'm trying to get this working for nuxt and express.  I know its a bit different but wanted to drop a link in case someone could help me on the nuxt-express repo: https://github.com/nuxt-community/express-template/issues/60

**Comment by atmar** [comment]
Https code for latestst Nuxt version (1.0.0-rc11)
```
const { Nuxt, Builder } = require('nuxt')

const https = require('https')
const fs = require('fs')
const isProd = (process.env.NODE_ENV === 'production')
const port = process.env.PORT || 3000

// We instantiate nuxt.js with the options
const config = require('./nuxt.config.js')
config.dev = !isProd
const nuxt = new Nuxt(config)

// Render every route with Nuxt.js

// Build only in dev mode with hot-reloading
if (config.dev) {
  new Builder(nuxt).build()
    .then(listen)
    .catch((error) => {
      console.error(error)
      process.exit(1)
    })
}
else {
  listen()
}

function listen() {

  const options = {
    key: fs.readFileSync('/home/store/certs/store.key'),
    cert: fs.readFileSync('/home/store/certs/store.crt')
  };

  https
    .createServer(options, nuxt.render)
    .listen(port)
  console.log('Server listening on `localhost:' + port + '`.')
}
```

**Comment by ahmad-sa3d** [comment]
Thanks a lot guys for your awesome answers, Thanks atmar you code works well

**Comment by miecio1212** [comment]
https://www.gatsbyjs.org/docs/local-https/

**Comment by MarvinXu** [comment]
@Atinux doesn't work. `Nuxt is not a constructor`

**Comment by hardikshah91** [comment]
@Atinux  
setting up localhost as https is working properly.
but how can we use it with [https://github.com/nuxt-community/proxy-module](url)

**Comment by Atinux** [comment]
Nuxt 2.0 will support https out of the box so proxy module will work also out of the box

**Comment by Atinux** [comment]
@HotspurHN take a look at https://github.com/nuxt/docs/blob/2.0/en/api/configuration-server.md

**Comment by hardikshah91** [comment]
> Nuxt 2.0 will support https out of the box so proxy module will work also out of the box

Hi @Atinux ,

I have tried with `nuxt-edge` but still its not working with https://github.com/nuxt-community/proxy-module

**Comment by siberiadev** [comment]
> Https code for latestst Nuxt version (1.0.0-rc11)
> 
> ```
> const { Nuxt, Builder } = require('nuxt')
> 
> const https = require('https')
> const fs = require('fs')
> const isProd = (process.env.NODE_ENV === 'production')
> const port = process.env.PORT || 3000
> 
> // We instantiate nuxt.js with the options
> const config = require('./nuxt.config.js')
> config.dev = !isProd
> const nuxt = new Nuxt(config)
> 
> // Render every route with Nuxt.js
> 
> // Build only in dev mode with hot-reloading
> if (config.dev) {
>   new Builder(nuxt).build()
>     .then(listen)
>     .catch((error) => {
>       console.error(error)
>       process.exit(1)
>     })
> }
> else {
>   listen()
> }
> 
> function listen() {
> 
>   const options = {
>     key: fs.readFileSync('/home/store/certs/store.key'),
>     cert: fs.readFileSync('/home/store/certs/store.crt')
>   };
> 
>   https
>     .createServer(options, nuxt.render)
>     .listen(port)
>   console.log('Server listening on `localhost:' + port + '`.')
> }
> ```

Hi, could you tell me, how to use this code? Where to put it?

**Comment by hardikshah91** [comment]
> > Https code for latestst Nuxt version (1.0.0-rc11)
> > ```
> > const { Nuxt, Builder } = require('nuxt')
> > 
> > const https = require('https')
> > const fs = require('fs')
> > const isProd = (process.env.NODE_ENV === 'production')
> > const port = process.env.PORT || 3000
> > 
> > // We instantiate nuxt.js with the options
> > const config = require('./nuxt.config.js')
> > config.dev = !isProd
> > const nuxt = new Nuxt(config)
> > 
> > // Render every route with Nuxt.js
> > 
> > // Build only in dev mode with hot-reloading
> > if (config.dev) {
> >   new Builder(nuxt).build()
> >     .then(listen)
> >     .catch((error) => {
> >       console.error(error)
> >       process.exit(1)
> >     })
> > }
> > else {
> >   listen()
> > }
> > 
> > function listen() {
> > 
> >   const options = {
> >     key: fs.readFileSync('/home/store/certs/store.key'),
> >     cert: fs.readFileSync('/home/store/certs/store.crt')
> >   };
> > 
> >   https
> >     .createServer(options, nuxt.render)
> >     .listen(port)
> >   console.log('Server listening on `localhost:' + port + '`.')
> > }
> > ```
> 
> Hi, could you tell me, how to use this code? Where to put it?

@siberiadev This file should be named as server.js and added to root folder of your dir

**Comment by aldarund** [comment]
@mv5 its not quite clear how\where u running your app. You said s3+cloudfront but its for static files. ARe u using generate mode?

**Comment by mv5** [comment]
@aldarund yes, that's right

**Comment by aldarund** [comment]
@mv5 then it has nothing to do wiht nuxt and u dont need nuxt https at all. It should be configured at cloudfront level

**Comment by mv5** [comment]
@aldarund what should be configured?
when I upload an image for example to the s3 bucket I can access it through https, so it seems to me the configuration of the ssl certificate is correct. however, the warning about the self signed certificate shows up in the console during the deployment process which I configured based on this:
https://nuxtjs.org/faq/deployment-aws-s3-cloudfront/

**Comment by luatnd** [comment]
> It's now possible with `nuxt-edge` and Nuxt 2, take a look at https://github.com/nuxt/docs/blob/2.0/en/api/configuration-server.md

Hi, the link is not working, can you update this doc link?
