### ISSUE TITLE
not able to overwrite compilerOptions

### ISSUE THREAD

**Issue by boostie** [nuxt/nuxt.js#14601]
### Environment

mac os

### Reproduction

adding the following values into tsconfig.json

```
"compilerOptions": {
    "lib": [
      "es2020", "esnext"
    ],
    "module": "commonjs",
    "target": "es2020"
  }
```

Does not override the .nuxt/tsconfig.json file and keeps target as ESNext

### Describe the bug

I need to overwrite the compilerOptions because during the "nuxi run dev" I am unable to load a package that requires a different target. When using the following code for the main tsconfig.json file at the root of the project, it does not overwrite the changes and resulting target is always as its set initially by nuxi. 

```
{
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "lib": [
      "es2020", "esnext"
    ],
    "module": "commonjs",
    "target": "es2020"
  }
}

```

There needs to be a way to overwrite this. If I build the project, the imported module does not give errors. During the development, I am getting compilation errors for 

`Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)`

which should be corrected by changing the target during the compilation.

**Comment by fruitpool69** [comment]
having a similar issue with Nuxt 3 using nitro preset: 'vercel-edge' the target defaults to es2019 which causes build errors leaving you unable to deploy to Vercel if any package you are using depends on es2020 such as:

ERROR: Big integer literals are not available in the configured target environment ("es2019")

I've tried many different methods to try and override this and cannot, so essentially its bricked.
