### ISSUE TITLE
SVG codes inside .vue file do not work on 1.0.0-rc3..

### ISSUE THREAD

**Issue by Almusamim** [nuxt/nuxt.js#1460]
The SVG are being messed on the browser after updating to 1.0.0-rc3
I have no problem embedding the SVG as an image but when I use the svg code directly inside the `<template>` in the .vue file it would display all messed up on the browser.

![](https://image.prntscr.com/image/X4xndcpOS6OGcicoHRwBZg.png)

Here is the errors I'm getting:
```
...
Error: <path> attribute d: Expected path command, "…,1.8,1.4,1.4,2.5\\n          c-0.…".
Error: <path> attribute d: Expected path command, "…-1.8-1.4-1.4-2.5\\n          c0.2…".
...
```

This used to work on Nuxt v0.10.7
I even tried to add the svg code in a .vue file with latest vue/webpack template and it worked all fine 
So I think the issue here is from Nuxt.

I also noticed adding `<?xml version="1.0" encoding="utf-8"?>` inside `<svg>...</svg>` tags would make it work but the messed up svg paths would be flashed at first and with more errors/warning as well 

![](https://image.prntscr.com/image/VCypSX6FQ0eQf_Wl6CUkFw.png)

Peace

**Comment by KonstantinVlasov** [comment]
I use a lot of SVG in my project and have no problem with Nuxt 0.8.x - 1.0.0-rc6
I think there a problem with your SVG (as I can see in the screenshot). 
How can we reproduce it?

**Comment by Almusamim** [comment]
@KonstantinVlasov 

Sorry about that you are right.. the problem was coming from my SVG.
saving the svg from Inkscape instead of Illustrator made it work for some reasons..

It's weird that it was working everywhere though.. only not with Nuxt v 1.0-rc3

here is the svg that didn't work https://gist.github.com/Almusamim/11dac07502c7e99b79905afa060b10e1

Anyway sorry again.. the issue was from my end = )

**Comment by acidjazz** [comment]
@alexchopin @Almusamim I'm actually getting these exact same issues on SVG files that worked perfectly from before, I think this might be a nuxt-related issue

**Comment by acidjazz** [comment]
@alexchopin @Almusamim can you confirm if the problem on your side was that your .SVG file was multiple lines and now it's one line?

**Comment by acidjazz** [comment]
@KonstantinVlasov for more detail, my SVG was inlucded via PUGJS and you should error if its multiple lines, or  be fine if it's just one line.

**Comment by KonstantinVlasov** [comment]
SVG with multiple lines works as expected. This warning not Nuxt related. Problem with your SVG or how pug includes it.

**Comment by acidjazz** [comment]
@KonstantinVlasov no actually the rendered html is just as broken as if I just use <template>, keep in mind this SVG worked perfectly fine with pug and earlier versions of nuxt

Can you share with me your multiline SVG that works?

**Comment by KonstantinVlasov** [comment]
Earlier versions of nuxt use earlier version of vue and others. Warning that you see came from Vue, not Nuxt. Nuxt doesn't create any html for you, Pug do. Nuxt doesn't validate result html, Vue do.
As you can see SVG file from topic was invalid, despite the fact that it works with previous versions.
One of icons that I use:
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <g>
    <path style="fill:#FFC107;" d="M 40 40 L 8 40 C 7.28125 40 6.621094 39.617188 6.265625 38.996094 C 5.910156 38.375 5.910156 37.609375 6.273438 36.992188 L 22.273438 8.992188 C 22.632813 8.378906 23.289063 8 24 8 C 24.710938 8 25.367188 8.378906 25.726563 8.992188 L 41.726563 36.992188 C 42.089844 37.609375 42.089844 38.375 41.734375 38.996094 C 41.378906 39.617188 40.714844 40 40 40 Z "></path>
    <path style="fill:#5D4037;" d="M 22 34.140625 C 22 33.871094 22.046875 33.628906 22.144531 33.394531 C 22.238281 33.167969 22.371094 32.96875 22.546875 32.804688 C 22.71875 32.636719 22.929688 32.503906 23.171875 32.410156 C 23.414063 32.320313 23.6875 32.269531 23.992188 32.269531 C 24.300781 32.269531 24.574219 32.320313 24.820313 32.410156 C 25.070313 32.503906 25.28125 32.636719 25.453125 32.804688 C 25.628906 32.96875 25.765625 33.167969 25.855469 33.394531 C 25.953125 33.628906 26 33.871094 26 34.140625 C 26 34.410156 25.953125 34.65625 25.855469 34.882813 C 25.761719 35.105469 25.628906 35.300781 25.453125 35.46875 C 25.28125 35.636719 25.070313 35.765625 24.820313 35.863281 C 24.574219 35.953125 24.300781 36 23.992188 36 C 23.6875 36 23.414063 35.953125 23.171875 35.859375 C 22.929688 35.765625 22.71875 35.636719 22.546875 35.46875 C 22.371094 35.300781 22.234375 35.105469 22.144531 34.882813 C 22.046875 34.65625 22 34.410156 22 34.140625 M 25.480469 30 L 22.507813 30 L 22.085938 18 L 25.898438 18 Z "></path>
  </g>
</svg>
```

**Comment by acidjazz** [comment]
Doing some more research I've found this mostly occurs when the SVG is saved with something like the d="" parameter broken up into multiple lines.

**Comment by Almusamim** [comment]
@acidjazz Yes I can confirm it too. T
What caused the issue for me was having multiple lines inside the d="" parameter ...

This is why it worked out for me when I copied it to Inkscape and saved it from there instead of Adobe Illustrator I think.

I think it could be a nuxt issue and not from vuejs because it worked fine everywhere but only not with nuxt.

**Comment by acidjazz** [comment]
@Almusamim great, so even though I guess this is not a major issue I still see this as a bug with nuxtjs.  I have older versions of nuxt running in production with included SVG files that are multiple files that work fine (pre 1.0) @alexchopin so I guess even though this pretty low priority we should potentially re-open it? Allthough mutliline SVG elements are messy IMO, they are still valid.

**Comment by sokyrko** [comment]
Hi all. I have some bug too. But it's not Nuxt problem, I am using vanilla Vue. Bug represents only with server-side rendered pages. If I disable ssr, all will work fine.
