### ISSUE TITLE
webpackChunkName get undefined

### ISSUE THREAD

**Issue by Jeesoong** [nuxt/nuxt.js#1461]
1. set nuxt.config.js

`filenames: {
      chunk: '[name].[chunkhash].js'
    }`

2. my directory like this picture

    <img width="146" alt="2017-08-24 3 35 06" src="https://user-images.githubusercontent.com/5194326/29634710-47e24a4c-887d-11e7-9408-56aee9c728f2.png">

3. `npm run build`

     then i got an undefined.[chunkhash].js file in .nuxt/dist/pages directory

     i find it in Generating routes
     
     <img width="705" alt="2017-08-24 3 38 38" src="https://user-images.githubusercontent.com/5194326/29634983-302b4358-887e-11e7-879e-c54b85f41a74.png">

     is a bug?

     in code source /lib/common/utils.js .lines 189, here is 

     `route.name = route.name.replace(/-index$/, '')`

     why do this?

     my english is poor，sorry

**Comment by pi0** [comment]
@Jeesoong Thanks for your nice report. Will be fixed in next release :)
