### ISSUE TITLE
Documentation Improvement: nuxtApp, useNuxtApp, composables, plugins

### ISSUE THREAD

**Issue by jshimkoski** [nuxt/nuxt.js#14624]
### Describe the feature

It would be nice if the documentation had answers to these questions:

* Can you use a plugin in a composable?
* Can you use a plugin within another plugin?
* Can you use a composable in a plugin?
* Can you use a composable within another composable?
* And most importantly, what does the Nuxt 3 lifecycle look like and when do different pieces of an app become available to the `nuxtApp` context?

Back story: While porting a massive project from Nuxt 2 -> Nuxt 3, my app exploded after RC.7 due to the usage of a plugin within another plugin (oddly, my app worked without issue up to that point). I had to combine the plugins to bring the app back to life. This took hours to troubleshoot and it was a pretty easy thing to mess up.

What I expected:
"I'm providing this plugin to my app, I should be able to access it anywhere the `nuxtApp` context is available."

What really happens:
"I'm providing this plugin to my app, I can access it in my layouts, pages and components, but I think that's about it."

So, long story short, it would be awesome if the documentation could be updated to answer those 5 questions.

I could help contribute an update to the documentation if provided the answers by the peeps in the know.

Thanks!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by augnustin** [comment]
I'm checking in about the question

> Can you use a composable in a plugin?

I just tried:

```
// myplugin.js

import { useUser } from '~/composables/application/useUser';

export default function (ctx) {
  const { user } = useUser(); // uses useContext();

  console.log(user);
}
```

But I get

```
Error: This must be called within a setup function.
    at useContext (index.mjs:638:18)
    at useUser (useUser.ts:8:95)
    at eval (i18n-auth0.js:7:98)
    at _callee2$ (index.js:640:99)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.eval [as next] (runtime.js:119:21)
    at asyncGeneratorStep (asyncToGenerator.js:5:24)
    at _next (asyncToGenerator.js:27:9)
```

So can I really?

I guess I could pass the context as a parameter of the composable and write

```
import { computed, useContext } from '@nuxtjs/composition-api';

export function useUser(ctx) {
  const { $auth }: { $auth: Auth } = ctx || useContext();
  const user = computed(() => $auth.user);

  return { user };
}

```

but that would mean the answer to the original question would be **no**, wouldn't it?

**Comment by danielroe** [comment]
@augnustin You can use a composable in a plugin in Nuxt 3, but you are using Nuxt 2 without Bridge, and in that context you cannot.

**Comment by augnustin** [comment]
Hello @danielroe 
Thanks for such quick feedback.
You are correct about my setup. I need to check the differences between using `@nuxt/composition-api` and `@nuxt/bridge` then.

**Comment by Rednas83** [comment]
Can you use a plugin inside a composable?

Something like:
**patch.js**
```
Array.prototype.sum = function () {
  return openx(
    this.reduce((a, b) => {
      return Number(a) + Number(b)
    })
  )
}
Array.prototype.avg = function () {
  return openx(sum(this) / openx(length))
}
export default defineNuxtPlugin(() => {})
```
