### ISSUE TITLE
Why the Custom Loading Component may not work?[re-open]

### ISSUE THREAD

**Issue by Jussiadev** [nuxt/nuxt.js#1463]
#1454 

@Atinux my project https://github.com/Jussiadev/mynuxt

**Comment by paulgv** [comment]
You have 2 different configurations for the loader in your config, the last one is taking over:

```js
module.exports = {
    // ...
    loading: '~/components/loading.vue',
    loading: {
        color: 'red',
        height: '5px'
    },
    // ...
};
```

Remove the second configuration and the first one will work.

**Comment by Jussiadev** [comment]
No two of them are commented out, since I've already decided to try a simpler loader. But even with it does not work. In addition, the page reloads, and only the components must be loaded. The all page should not be rebooted. (Currently active links '/brands' and '/'. It nuxt-link in layouts -> headerAndFooter.vue )
module.exports = {
    // loading: false,
    // loading: '~/components/loading.vue',
    loading: {
        color: 'red',
        height: '5px'
    }

**Comment by paulgv** [comment]
Well I tried your project and the loading works fine.
If you want to enable the loader in `~/components/loading.vue`, you might have to increase its `z-index`:

```
.loading-page {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    text-align: center;
    padding-top: 500px;
    z-index: 10;
}
```

**Comment by Atinux** [comment]
Thanks a lot @paulgv

**Comment by Jussiadev** [comment]
@paulgv I've tried it now in the Chrome and Safari and I still have a standard browser load that also comes with a reboot
