### ISSUE TITLE
cannot read properties of null (reading 'setupContext')

### ISSUE THREAD

**Issue by KahrLu** [nuxt/nuxt.js#14636]

**Comment by HOPELESSNESSLYR** [comment]
How to solve this problem?'Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setupContext')'

**Comment by danielroe** [comment]
@HOPELESSNESSLYR Would you open an issue with a minimal reproduction? 🙏

**Comment by vaheqelyan** [comment]
Same issue
