### ISSUE TITLE
import uikit components

### ISSUE THREAD

**Issue by miladmeidanshahi** [nuxt/nuxt.js#1466]
Hi,

How can i import [Uikit 2 components](https://getuikit.com/v2/docs/components.html) without cdn links ?

**Comment by Atinux** [comment]
Hi @miladmeidanshahi 

I don't know for UIkit 2, but with UIkit 3 it works fine.

See [uikit example](https://github.com/nuxt/nuxt.js/tree/dev/examples/uikit) and [live demo](https://uikit.nuxtjs.org).

Glitch: https://glitch.com/edit/#!/nuxt-uitkit
