### ISSUE TITLE
strange bug - Store state is leaking across clients

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#1467]
The state injected by nuxt to the `nuxtServerInit` contains data from other client

Reproductions:
1. Go to the page with BROWSER_1
2. Click on "Click", you will see random number **XXX**
3. Close BROWSER_1
4. Open BROWSER_1 and go to the same page.
5. You will see number XXX generated previously (this is ok - was read from the cookie)
6. **Close BROWSER_1**
7. **Open BROWSER_2** (or use incognito)
8. Go the the same page. You will see number **XXX** that was generated for the first user!!

You can check log console in glitch.
```js
  async nuxtServerInit ({ state, dispatch, commit }, { req }) {
    console.log('actions.nuxtServerInit state = ', state)
    [...]
```

This output the state from the previous client.

Page:
https://nuxt-rc6-store-state.glitch.me/

Code:
https://glitch.com/edit/#!/join/5d93dc85-6bb8-4d6c-a604-23dbf803eca5

**Comment by Atinux** [comment]
Hi @awronski 

Actually it's because you set the state inside a file which is cached on server-side, you need to declare `state` to be a function an call it every time you create the store:

`store/index.js`
```js
import Vuex from 'vuex'

import createState from './state'
import actions from './actions'
import getters from './getters'
import mutations from './mutations'

const debug = process.env.NODE_ENV !== 'production'

const createStore = () => new Vuex.Store({
  strict: debug,
  state: createState(), // Ensure unique state on server-side
  getters,
  actions,
  mutations
})

export default createStore
```
And your `store/state.js`:
```js
const createState = () => ({
  authToken: null
})

export default createState
```
Actually, if you use the store module by nuxt.js, we prevent this error to happen (https://github.com/nuxt/nuxt.js/blob/dev/lib/app/store.js#L62)

Your demo updated and fully working: https://zesty-fireman.glitch.me/
Code updated: https://glitch.com/edit/#!/zesty-fireman

**Comment by awronski** [comment]
@Atinux Thank you so much for your help. I didn't know that the state file will be cached.

Could you explain more how to use the store module by nuxt?
Could I use it for both global and module state?

**Comment by Atinux** [comment]
When I was talking about store module, it's like this:

`store/index.js`:
```js
export const state = {
  counter: 0
}
```

This way you will have the warning :)

**Comment by Darkside73** [comment]
I have same issue with vuex modules.

```js
// store/index.js

import Vue from 'vue'
import Vuex from 'vuex'
import someModule from './someModule'

const modules = { someModule }

const createState = () => ({
  rootProp: 1
})

export default () => new Vuex.Store({
  strict: false,
  modules,
  state: createState()
})
```

```js
// store/someModule.js

const createState = () => ({
  items: []
})

export default {
  namespaced: true,
  state: createState()
}

```
