### ISSUE TITLE
Per-route ssr

### ISSUE THREAD

**Issue by gridsystem** [nuxt/nuxt.js#1468]
Is it possible to define which routes are rendered fully server-side and which are served in SPA mode?

The use-case I am thinking of is I have a small "marketing" area including a homepage which need to be search engine crawlable so ssr is a must. The majority of the site would be hidden behind authentication, so the added overhead of ssr is unnecessary for these areas.

Thanks for any tips!

**Comment by pi0** [comment]
Hi @gridsystem . Actually, this is available under an experimental features science rc5.
The current way is using express/connect middleware before SSR to set a `spa = true` flag on specific routes to disable SSR on them (We still need SSR bundle for all routes so nuxt should be running in **universal** mode). So using [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware):
```js
module.exports = {
 path: '/public',
 handler(req, res, next) {
   res.spa = true 
   next()
 }
}
```

Actual implementation code: https://github.com/nuxt/nuxt.js/blob/7738d0c0af958a715f5ca2fde8f95be81832ca42/lib/core/renderer.js#L451

Please let me know how things go for you about this :)

**Comment by gridsystem** [comment]
Thanks @pi0 your example and link will be very useful.

Is there a changelog somewhere (other than the commit log) for rc5?

**Comment by pi0** [comment]
@gridsystem The feature is not stable and well tested, for now. So not documenting of many features like is intentionally postponed. We may investigate more to see if this would handle all needs or not.

**Comment by pi0** [comment]
@gridsystem I'll close this issue making off topic for easier maintenance of new issues. Feel free to reopen or pinging me if any further help was needed.

Regards.

**Comment by vwxyzjn** [comment]
Thank you. The code is very helpful, I ended up using the following code in ``nuxt.config.js``:

```js
module.exports = {
  ...,
  serverMiddleware: [
    { path: '/event', handler: (req, res, next) => { res.spa = true; next() } }
  ]
}
```

**Comment by ChuckDog** [comment]
This is working for me in the Dev mode. But when I did generate, there is a  reference error, which is that window is not defined. Why this config not work after generate.

Thanks.

**Comment by ChuckDog** [comment]
I fixed it with using require. if (process.browser) { var a = require(a) }
But it is really cool, if we can do it in config file.
