### ISSUE TITLE
Allow a particular nested page to be nested in terms of URL only

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/nuxt.js#1470]
Let's say I have this `/pages/` directory structure:
```
/pages/
  users.vue
  users/
    :id.vue
    new.vue
```
What if I want to disattach the page component of `new.vue` from the existing component hierarchy? I mean, to have a URL like `/users/new`, but NOT no include whatever is in `users.vue`.

AFAIK, there were a way of achieving this with vue-router, using a leading slash or something. Any hints on how to get the same in a Nuxt-based project?

**Comment by KonstantinVlasov** [comment]
Hi! Maybe it can be useful

In your case you can use this structure:
```
/pages/
  users/
    _id.vue
    index.vue
    new.vue
```
and use the custom layout or wrapper component for _id.vue and index.vue

**Comment by Atinux** [comment]
It's a bit tricky, but this will work:

```bash
/pages/
  users/
    _id/
      index.vue
    _id.vue 
    new.vue
```

Then it will generate:
```js
{
  path: "/users/new",
  component: _737c873c,
  name: "users-new"
},
{
  path: "/users/:id?",
  component: _9ae83108,
  children: [
    {
      path: "",
      component: _5dd83e02,
      name: "users-id"
    }
  ]
}
```
And in `pages/users/_id.vue`:
```vue
<template>
  <div>
    <h1>Users</h1>
    <nuxt-child v-if="$route.params.id"/>
  </div>
</template>
```

So `pages/users/_id/index.vue` will be included only if an is is defined.
