### ISSUE TITLE
"#build/app.config.mjs" is not defined in package imports

### ISSUE THREAD

**Issue by m0ksem** [nuxt/nuxt.js#14728]

**Comment by gspgsp** [comment]
> Faced with the same issue today. Try to replace 'nuxt/app' to '#imports' and everything should work great.

i face this problem today:
change the following:
import {showError} from "nuxt/app";
to:
import {showError} from "#imports";

everything works well, in fact, I've actually had this problem before and forgot about it because it's been so long.

**Comment by productdevbook** [comment]
if nuxt/app used `[worker init] Package import specifier "#build/app.config.mjs" is not defined in package` this problem.


if #imports used ` [worker reload] [worker init] Package import specifier "#imports" is not defined in package ` this problem. 

how to fixed ?

**Comment by danielroe** [comment]
@productdevbook It sounds like you are importing one of these files somewhere where it's not valid (like into a module directly). They should only be used in _runtime_ code.
