### ISSUE TITLE
Please fix the Starter Template for god sake 

### ISSUE THREAD

**Issue by VadiForte** [nuxt/nuxt.js#1473]
There is the bug on `index.vue` in `Page` folder that we need to change from
 `import logo from '~components/logo.vue` 
to
`import logo from '~/components/logo.vue`

This will make new people come in the first time struck in this point and some will drop-off which mean we lost number of user.

**Comment by pi0** [comment]
Hi. Actually, it should be fixed with the latest version (updated more than 24 days ago) How are go giving that error with fresh projects ?

https://github.com/nuxt-community/starter-template/blob/master/template/pages/index.vue#L20

**Comment by VadiForte** [comment]
I just download zip file from the website last night and i still got an error message
