### ISSUE TITLE
Bug in the generation of files in the build

### ISSUE THREAD

**Issue by juliandavidmr** [nuxt/nuxt.js#1474]
Hello, I have a problem with the generation of files in the build: `npm run build`.

The file `index.spa.html` have three tag `script` with path js file into folder `/_nuxt` but this folder not exist, ie:

```html
<script src="/_nuxt/manifest.xxx.js"/>
<script src="/_nuxt/common.xxx.js"/>
<script src="/_nuxt/app.xxx.js"/>
```
The JS files `manifest`, `common` and `app` is at the folder root (`dist`).

Info:
Nuxt 1.0.0-rc3
Node v6.11.1
SO Windows 10

**Comment by pi0** [comment]
Hi @juliandavidmr . For SPA deployment you have to deploy `dist` folder at the **root** of your project (~/dist) not one in the `.nuxt` dir. (Please upgrade your nuxt to rc6 please for a better SPA experience too)
