### ISSUE TITLE
`navigateTo` has no effect when a plugin is declared

### ISSUE THREAD

**Issue by Baloche** [nuxt/nuxt.js#14771]

**Comment by maximepvrt** [comment]
@pi0, I've encountered an issue that I could use your help with. Everything seems to be perfect, but I'm running into an error on the pages/index.vue page when I try to reference a user attribute. I thought the redirection was supposed to take place before the template generation, right? Additionally, I'm curious if callWithNuxt functions the same as nuxtApp.runWithContext. Your insights would be greatly appreciated! Thank you.

[https://codesandbox.io/p/sandbox/nuxt-3-navigateto-with-usefetch-forked-r4rz6m](https://codesandbox.io/p/sandbox/nuxt-3-navigateto-with-usefetch-forked-r4rz6m)
