### ISSUE TITLE
Node version  ?

### ISSUE THREAD

**Issue by oo10** [nuxt/nuxt.js#1479]
Nuxt have version requirements for node? I can't run it in version 7.8 (node).

**Comment by pi0** [comment]
@oo10 Node `>=6.11` would be fine! What error are you currently getting?

**Comment by oo10** [comment]
I'm going to deploy the project on the server, and when I'm done with `npm run build`, then  `npm run start` reported it wrong.

Remind me `nuxt start` error, and to check if it's the latest version of Node and NPM，Otherwise, it could be a nuxt problem.

**Comment by pi0** [comment]
>  then npm run start reported it wrong.

But without having your full console error logs we can't help you

**Comment by appsparkler** [comment]
I too faced an error.  Am trying to install latest version which is 8.x:

https://nodejs.org/en/download/


Good Luck...
