### ISSUE TITLE
Module nuxt-icons is disabled due to incompatibility issues

### ISSUE THREAD

**Issue by shba007** [nuxt/nuxt.js#14793]

**Comment by L0calH0st80** [comment]
@danielroe Issue is now happening with nuxt/image "Module @nuxt/image is disabled due to incompatibility issues: 
" - [nuxt] Nuxt version ^3.1.0 is required but currently using 2.17.1"

**Comment by danielroe** [comment]
You probably have the wrong version of Nuxt image installed in your Nuxt 2 project.

**Comment by UcheAzubuko** [comment]
Hi @danielroe , I encounter this issue:

 WARN  Module @nuxt/icon is disabled due to incompatibility issues: 
 - [nuxt] Nuxt version >=4.0.0 is required but currently using 3.18.1

**Comment by danielroe** [comment]
well, install nuxt v4 or an older version of nuxt/icon
