### ISSUE TITLE
 allocation failure GC in old space requested

### ISSUE THREAD

**Issue by SzHeJason** [nuxt/nuxt.js#1481]
version : nuxt@rc-6

![image](https://user-images.githubusercontent.com/20609396/29712722-d2114a82-89cd-11e7-9f97-a25aaf2eac35.png)

**Comment by pi0** [comment]
`nuxt.js:2066` in the picture above maps to [renderer.js:87](https://github.com/nuxt/nuxt.js/blob/dev/lib/core/renderer.js#L87) also trace shows error going into a JSON parse. We have two json parses one for client manifest and [one](https://github.com/nuxt/nuxt.js/blob/dev/lib/core/renderer.js#L562) for `server.bundle.json`. So i think there are two possible cases for your error:

- Limited resources available on your server.
  - We can try with node flag: `--max_old_space_size=8048`
- A REAL big server bundle file generated (Usually some compatible libraries)

Would you please run `nuxt build --analyze` and providing console output and bundle anylize results?

**Comment by SzHeJason** [comment]
anylize results : 
![image](https://user-images.githubusercontent.com/20609396/29757014-4483d9d6-8bdb-11e7-8592-083aca16e169.png)
![image](https://user-images.githubusercontent.com/20609396/29757052-83d2d09c-8bdb-11e7-9b43-7e1f6af789b0.png)

**Comment by SzHeJason** [comment]
Error JSON waiting for next time

**Comment by SzHeJason** [comment]
Does not exist manifest and server.bundle.json in develop environment
![image](https://user-images.githubusercontent.com/20609396/29757852-9faaf406-8be1-11e7-8fc1-3c128c34e292.png)

**Comment by alexchopin** [comment]
Should be fixed with the last release

**Comment by yoyo837** [comment]
I just got some this：

91% additional chunk assets processing
<--- Last few GCs --->

[12584:000001F7C848A9E0] 13966592 ms: Mark-sweep 1268.4 (1463.1) -> 1268.4 (1463.1) MB, 338.8 / 0.1 ms  allocation failure GC in old space requested
[12584:000001F7C848A9E0] 13966862 ms: Mark-sweep 1268.4 (1463.1) -> 1252.9 (1424.6) MB, 270.6 / 0.1 ms  last resort GC in old space requested
[12584:000001F7C848A9E0] 13967108 ms: Mark-sweep 1252.9 (1424.6) -> 1252.9 (1414.6) MB, 245.3 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000223EDEA57C1 <JSObject>
    1: fromString(aka fromString) [buffer.js:314] [bytecode=0000009C25BED8B1 offset=164](this=0000008038C822D1 <undefined>,string=0000027DE451A569 <Very long string[9365179]>,encoding=00000223EDEB4EB1 <String[4]: utf8>)
    2: from [buffer.js:177] [bytecode=0000009C25BED3B9 offset=11](this=00000159CC1362D9 <JSFunction Buffer (sfi = 00000223EDEFB6C9)>,value=0000027DE451A569 <Very long string[93...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::Smi::SmiPrint
 6: v8::internal::StackGuard::HandleInterrupts
 7: v8::String::WriteUtf8
 8: v8_inspector::V8InspectorClient::currentTimeMS
 9: node::Buffer::New
10: node::Buffer::New
11: v8::internal::wasm::SignatureMap::Find
12: v8::internal::Builtins::CallableFor
13: v8::internal::Builtins::CallableFor
14: v8::internal::Builtins::CallableFor
15: 0000031F2FD843C1
