### ISSUE TITLE
Multiple layouts?

### ISSUE THREAD

**Issue by lautiamkok** [nuxt/nuxt.js#1484]
How do I create multiple layouts for different routes? For instance

at http://127.0.0.1:3000/ - default.vue
at http://127.0.0.1:3000/about - another.vue

There is no mention about this at all from the doc - https://nuxtjs.org/guide/views#layouts. It would helpful if this guide is included.

**Comment by lautiamkok** [comment]
Sorry, found it!

**Comment by Shamonshamonsha** [comment]
How did you solved the issue??

**Comment by lautiamkok** [comment]
@Shamonshamonsha the answer is on that page actually https://nuxtjs.org/guide/views#layouts, under **Custom Layout**.
