### ISSUE TITLE
servermiddleware routes are not recognized

### ISSUE THREAD

**Issue by colwilson** [nuxt/nuxt.js#1486]
```
module.exports = {
  serverMiddleware: [
      { path: '/api', handler: '~/api/index.js' }
  ]
```
does not actually pick up requests to /api/* and does not generate a route in .nuxt/router.js.

```
module.exports = {
  serverMiddleware: [
      '~/api/index.js'
  ]
```
does pick everything up though, however this leaves you to check the url in the middleware and applies to every request which is not efficient - or neat.

`  "version": "1.0.0-rc6",
`

**Comment by pbastowski** [comment]
Have a look here https://github.com/nuxt/nuxt.js/issues/1312

I am able to use express as middleware using the method described.

**Comment by colwilson** [comment]
I can see that that very simple example works, but it does not really use express routing either. e.g. this does not work:
```
const express = require('express')

const app = express()

app.get('/api/say/:word', (req, res) => {
  res.json(req.params)
})

module.exports = {
  path: '/api',
  handler: app
}
```

**Comment by pbastowski** [comment]
@colwilson 
It works for me, but you have to configure it right. As it is now, you have too many `/api` in your code. 

Your nuxt.config.js should contain this:

```js
    serverMiddleware: [
        '~/api/index.js',
    ]
```
and /api/index.js should look like this:

```js
const app = require('express')()
module.exports = { path: '/api', handler: app }

app.get('/say/:word', (req, res) => {
  res.json(req.params)
})
```

**Comment by colwilson** [comment]
@pbastowski 
Thanks a lot that works now.

**Comment by pbastowski** [comment]
@pi0 @Atinux 
You probably get a lot of these types of questions, "stuff doesn't work", "how do I", "please alow xxxx in NUXT", right? I have asked this type of question here myself and got a good answer from pi0. 

So, I was thinking that there must be some way to turn these issues/questions/requests and answers into a FAQ or wiki, which supplements the docs. The docs don't usually cover specialised questions and it's a shame to lose them.

I know we can all search through the issues, which helps in many cases, especially if issues are marked with a good label. However, a distilled version of the issues with specific questions and answers could be a great benefit to the community.

For example, this current issue, as reported by colwilson, has a heading "servermiddleware routes are not recognized". Now that we know what he actually was asking, we could rename it to "How to use serverMiddleware config option to add express routing to NUXT apps", or something like that. Maybe even link to these issues from the NUXT web site.

What do you think?

**Comment by Atinux** [comment]
Hi @pbastowski

This is pretty funny since I am currently working on a way to list Github Issues on Nuxt.js directly, I hope to release it pretty soon, I'm sure it will improve a lot our documentation website.

Thank you for your idea and feedback!

**Comment by pbastowski** [comment]
Hi @atinux

I'm glad to hear it :)

Paul

**Comment by colwilson** [comment]
I'm glad to have the issue sorted and would happily contribute if there was
a process
to do so.
