### ISSUE TITLE
Only file and data URLs are supported by the default ESM loader

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt.js#14877]

**Comment by wilDriven** [comment]
I just started getting this issue after doing a Nuxi upgrade.
I then upgraded my Node Version and switched to using Nuxt3 edge (3.0.1-rc.0-27902229.912eafb with Nitro 2.0.0-27902161.686a560) and still it persists.
Any ideas on a fix?

**Comment by driven-group** [comment]
> 

just realised it is due to the nuxtjs/robots package. Started happening after a Nuxi upgrade to latest, seemed to be working before that. Didn't solve by moving to edge channel. Have removed the module for now.
