### ISSUE TITLE
current working directory (__dirname and process.cwd()) etc has different results in dev and build mode

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#14884]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `srcDir`, `typescript`, `head`, `loading`, `css`, `middleware`, `runtimeConfig`, `tailwindcss`, `modules`, `env`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `~/modules/dashboardcore.ts`, `~/modules/auto-import-eslint.ts`
- Build Modules:    `-`
------------------------------

### Reproduction

I'm trying to load a file which is placed in the current working directory (the path where I execute the command):

```
// take 1
const __dirname = url.fileURLToPath(new URL('.', import.meta.url));
// take 2
const __dirname = process.cwd();
console.log('__dirname', __dirname);
const currentStateFilePath = resolve(__dirname, 'last-state');

```

this works in dev mode, but when building it resolved to differnt paths

### Describe the bug

**const __dirname = url.fileURLToPath(new URL('.', import.meta.url));**

resolves to: 
```
dev: /home/simon/Dev/hokify/hokify-dashboard/src/modules <-- I could work with that
build: / <-- ?

```

**const __dirname = process.cwd();**
resolve to:
```
dev: /home/simon/Dev/hokify/hokify-dashboard <-- correct (y)
build: /home/simon/Dev/hokify/hokify-dashboard/.output <-- .output?

```

differnt behaviour between dev and build mode is not ideal, is there any (internal) helper that returns the current working directory?

**Comment by icai** [comment]
nuxt production is built in one file, but the file driver will lose the directory structure!
