### ISSUE TITLE
TS2307: Cannot find module '#imports' or its corresponding type declarations. with webstorm

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#14880]

**Comment by Rusinas** [comment]
Using nuxt in monorepo and having the same issue. I am extending the tsConfig, everything works well except for paths with hash and this is annoying because I can't get types :(

**Comment by meddle1** [comment]
Thank you, bro, you saved a bunch of my time. This solved my problem (in nuxt.config):
  typescript: {
    tsConfig: {
      compilerOptions: {
        baseUrl: ".",
      },
    },
  },

**Comment by BBoehm** [comment]
> [@matthew-dean](https://github.com/matthew-dean) Thank you, bro, you saved a bunch of my time. This solved my problem (in nuxt.config): ` typescript: { tsConfig: { compilerOptions: { baseUrl: ".", }, }, },`

Same for IntelliJ (to have this tagged here as well), now also a custom alias works correctly.

Adding `baseUrl: "."` directly in my tsconfig.json did not work.
