### ISSUE TITLE
500 Error Cannot read properties of undefined (reading 'modules')

### ISSUE THREAD

**Issue by brightjune** [nuxt/nuxt.js#14891]
### Environment

Nuxi 3.0.0-rc.9 
                                                                                                  
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                      

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

npx nuxi init nuxt-app

yarn install

yarn dev

just use Nuxt 3 Quick Start, and get 500 error on browse.

### Describe the bug

ℹ Vite server warmed up in 351ms 
ℹ Vite client warmed up in 767ms 
✔ Nitro built in 561 ms
(node:17106) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ./.nuxt/dev/index.mjs:521:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function
  at <NuxtRoot>

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/5484071/189930806-51969635-7dd3-4dee-b491-2c0cdc8a189b.png">

**Comment by tommy3wood** [comment]
> 

Did you ever find a resolution for this @seanfilimon? I'm running into the same thing trying to implement the onelogin provider.

**Comment by manniL** [comment]
Instead of discussing here, please do in https://github.com/nuxt/nuxt/issues/14952
