### ISSUE TITLE
`<ClientOnly>` with `<template #fallback>` always results in hydration error in RC10

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/nuxt.js#14896]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kmye2r?file=components%2FTestThing.vue,components%2FTestThing2.vue,app.vue

### Describe the bug

When using a ClientOnly component with a fallback templates, as described in the docs, you will always get hydration errors.

**Comment by isuke01** [comment]
This is closed, but fixed @danielroe?
As today I did test with Nuxt 3.15.4 (installed 2 days ago fresh) and still having this issue with both `placeholder` and `fallback`
```js
<ClientOnly placeholderTag="span">
	{{ formattedTime }}
	<template #fallback>
	  {{ currentTimeSSR }}
	</template>
</ClientOnly>
```

Simply clock component, as I don't want it to appear I just added SSR rendered time, like 2 sec jump is fine no one will notice compared to appear jump, but I'm getting this hydration issue :O

**Comment by danielroe** [comment]
@isuke01  would you open a new issue with a reproduction?
