### ISSUE TITLE
Nuxt with Express Startkit Deploy to Azure Web App

### ISSUE THREAD

**Issue by pmgower** [nuxt/nuxt.js#1489]
I am trying to get a nuxt with express web app deployed to an Azure Web App running Node.  Here's what I have done so far:

1. Created a build using VSTS
2. Deployed build to Azure Web App using VSTS release (using MS's Azure App Service Deploy task)
3. I also made a few changes per a couple closed issues:
   * Changed scripts to use fully qualified paths like "node ./node_modules/nuxt/bin/nuxt start" based on response in this [issue](https://github.com/nuxt/nuxt.js/issues/733)
   * Created a stub server.js per response in this [issue](https://github.com/nuxt/nuxt.js/issues/465) but I did have to make a change to the call to nuxt.Server to be nuxt.listen(port, host) instead.
4. Enabled logging to the iisnode log folder based on this [iisnode.yml](https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/iisnode.yml) file used in azure
5. Here is the log information being returned now that makes me think it is still a configuration issue:
```
Sat Aug 26 2017 16:12:45 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
SyntaxError: Unexpected token {
    at Module._compile (module.js:434:25)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\Program Files\iisnode\interceptor.js:459:1)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
```

Here are the contents of the **server.js** file I created based on the notes in 3:
```
const fs = require('fs');
const { Nuxt } = require('nuxt');
const resolve = require('path').resolve;

const rootDir = resolve('.');
const nuxtConfigFile = resolve(rootDir, 'nuxt.config.js');

let options = {};
if (fs.existsSync(nuxtConfigFile)) {
  options = require(nuxtConfigFile);
}
if (typeof options.rootDir !== 'string') {
  options.rootDir = rootDir;
}
options.dev = false; // Force production mode (no webpack middleware called)

const nuxt = new Nuxt(options);

const port = process.env.PORT;
const host = process.env.HOST;

nuxt.listen(port, host);
```

If need be I can give you the **web.config** and **iisnode.yml** files if those would be helpful when looking at the config of the azure web app.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1326">#c1326</a>)</em></sub></div>

**Comment by KonstantinVlasov** [comment]
Hi! Just a guess, maybe you have old node.js version and problem line is:
```javascript
const { Nuxt } = require('nuxt');
```

**Comment by pmgower** [comment]
@KonstantinVlasov I am using node version 8.1.4.  Would that be the issue?  Sorry I'm new to node and deploying to azure.

I come from a C#.NET background.

**Comment by pmgower** [comment]
@KonstantinVlasov I removed the { and replaced the line with this:
```javascript
const Nuxt = require('nuxt');
```
after that change the error is different but I actually made the change to add the { to try and fix this error but I am open to suggestions:
```text
Sat Aug 26 2017 19:01:10 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
TypeError: Nuxt is not a constructor
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:17:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Program Files\iisnode\interceptor.js:459:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

**Comment by KonstantinVlasov** [comment]
Try this:
```javascript
const Nuxt = require('nuxt').Nuxt;
```
but looks this is the wrong way, node 8.x is suitable

**Comment by pmgower** [comment]
@KonstantinVlasov ok I think we are getting really close now.

Now I'm back to another error I was seeing but thought it wasn't an issue since it is called **UnhandledPromiseRejectionWarning** but perhaps this is my issue now.  I found it in the **stderr** logs not the other error logs.  Now there aren't any other errors being logged that I can see.  

Here's the full **stderr output**:
```
(node:7308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RangeError: "port" argument must be >= 0 and < 65536
```

Also this might be helpful since this makes me think this is why I'm getting that error.  This is the **stdout output**:
```
OPEN  http://localhost:\\.\pipe\650c3970-ae6f-41e5-a62e-1ebec880f2a5
```

And when I was researching the **UnhandledPromiseRejectionWarning** it was mentioned that azure uses piped names but I'm not sure how to resolve the issue.

**Comment by KonstantinVlasov** [comment]
looks like problem is here:
```javascript
const port = process.env.PORT;
```
Probably you don't pass port to env.
Here is more safe alternative:
```javascript
const port = process.env.PORT || 80; // specify your default port
```

**Comment by pmgower** [comment]
@KonstantinVlasov I agree I think something is wrong with the port #.  I'm not sure why but when I change it to what you suggest it appears to give me the same error.

Running it locally it seems that even though **process.env.PORT** is undefined it returns **true**.

Any thoughts around why undefined is no longer falsey?  Did that change in the 8.1.4 version of node?

I'm going to try and hardcode the port to 80 instead.

**Comment by KonstantinVlasov** [comment]
I think you pass wrong port, just console.log it and check

**Comment by pmgower** [comment]
I console.log'd it and this is what port is returning.  Also found that process.env.HOST wasn't what is used in azure so I changed my server.js to look like this:
```
const fs = require('fs');
const Nuxt = require('nuxt').Nuxt;
const resolve = require('path').resolve;

const rootDir = resolve('.');
const nuxtConfigFile = resolve(rootDir, 'nuxt.config.js');

let options = {};
if (fs.existsSync(nuxtConfigFile)) {
  options = require(nuxtConfigFile);
}
if (typeof options.rootDir !== 'string') {
  options.rootDir = rootDir;
}
options.dev = false; // Force production mode (no webpack middleware called)

const nuxt = new Nuxt(options);

const port = process.env.PORT || 80;
// eslint-disable-next-line no-console
console.log('port: ', port);
// eslint-disable-next-line no-console
console.log('process.env.PORT: ', process.env.PORT);

const host = process.env.HOST || process.env.WEBSITE_HOSTNAME;
// eslint-disable-next-line no-console
console.log('host: ', host);
// eslint-disable-next-line no-console
console.log('process.env.HOST: ', process.env.HOST);

nuxt.listen(port, host);
```

And here's the output from the console.log:
```
port:  \\.\pipe\092d1e59-c81c-4d47-b5b7-357842aac603
process.env.PORT:  \\.\pipe\092d1e59-c81c-4d47-b5b7-357842aac603
host:  kentucky-tourism-frontend.azurewebsites.net
process.env.HOST:  undefined
```

It appears Azure uses iisnode and autogenerates a pipe for the port every request.  Any idea how to get around this using a named pipe instead of port setup for nuxt?

**Comment by KonstantinVlasov** [comment]
sorry, I have no experience with Azure or issnode

**Comment by pmgower** [comment]
@KonstantinVlasov ok.

anyone else have experience getting the named pipe way to work with nuxt?

**Comment by pi0** [comment]
@pmgower Your express integration in the first message is correct (Using `const { Nuxt } = require()`) Also using node 8.x is great. I think just similar to [this](https://github.com/nuxt/nuxt.js/issues/733#issuecomment-302656712) the only thing for azure is that we may honor port number assigned by azure: ([source](https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-nodejs-develop-deploy-app))

> `var port = process.env.port || 1337;`
> This code is essentially the same as the "Hello World" sample on the nodejs.org website, except it uses the port number assigned by the cloud environment.

So changing your server script to something like this should be the fix:

```js
const port = process.env.port || 1337;
```

**Comment by shaydoc** [comment]
Hi Paul

Have a look at my demo repo, it's deployed in azure with iisnode
It was a pain to figure out, but worth it in the end

https://github.com/shaydoc/nuxtexpress

Check out the 

server.prod.js and the web.config


Cheers
Shay

**Comment by shaydoc** [comment]
This is it on azure

http://shaynuxtexpress.azurewebsites.net

Cheers 
Shay

**Comment by shaydoc** [comment]
The only real issue I had to actually resolve in the end was fully qualifying my api calls server side, for the server side rendering.

Cheers
Shay
