### ISSUE TITLE
[Question] How to configure port where nuxt.js is running?

### ISSUE THREAD

**Issue by hendrysadrak** [nuxt/nuxt.js#149]
How to configure port where nuxt.js is running in production mode?

**Comment by alexchopin** [comment]
Hi, you can configure the PORT with 2 different ways:
- Via a env variables
```json
"scripts": {
  "dev": "PORT=3333 nuxt"
}
```
- Via a nuxt config in the `package.json`:
```json
"config": {
  "nuxt": {
    "port": "3333"
  }
},
"scripts": {
  "dev": "nuxt"
}
```

**Comment by hendrysadrak** [comment]
Super! Thank you @alexchopin

**Comment by classLfz** [comment]
@alexchopin I had tried those ways you say above， but It can worked in linux & mac，not work in windows.

**Comment by ruchirpat** [comment]
use this command to do so
 $ PORT=3333 npm run dev
