### ISSUE TITLE
Prefetch secret giveaway in Auth Routes example

### ISSUE THREAD

**Issue by trys** [nuxt/nuxt.js#1490]
In the [auth routes](https://github.com/nuxt/nuxt.js/tree/dev/examples/auth-routes) example, `secret.vue` uses auth middleware to throw an error when someone visits the page without being logged in. This all works very nicely for browsing the site normally. However, in the `<head>` of the home page; whether you're logged in or out, there are multiple `<link>` elements prefetching the code-split JS files, including the file for the secret page:

```html
<link rel="prefetch" href="/_nuxt/pages/secret.5ed12eb7c8cee6045aff.js">
```

This JS file contains all the "Super secret page" content which kindof negates the secrecy of it.

I'm not sure what the perfect solution is but I guess the simplest is to hide the prefetching with `resourceHints: false`. The knock-on is prefetching will be disabled for the whole site, logged in or out - which seems a shame. And this wouldn't stop anyone finding the (albeit obscurely named) file and get the secret content.

Is it possible to only hide prefetching for logged-out users, stop some files being prefetched or better still, prevent the JS files from being served (although I'm guessing this is more of a server issue and could probably be solved inelegantly by searching for `middleware:"auth"` in the JS files before serving them)?

**Comment by pi0** [comment]
Hi @trys hmm actually even by disabling that `resourceHints` that file is still accessible in `manifest.[hash].js`. Simple approach to detection of that chunk is changing file names using `[id]` for chunks: (nuxt.config.js)

```js
build {
    filenames: {
      chunk: 'js/[id].[chunkhash].js' // Default is [name].[chunkhash].js
    }
}
```

Anyway, this is nature of SPA that a copy of **UI** logic should run in the user browser. Indeed the important business part should happen in **API** not user browser. If the **secret** part of your nuxt project is going to grow more and you prefer entirely hide it, I would suggest using two separate nuxt projects (And somehow protect the secret part from none authenticated users to see)

**Comment by trys** [comment]
@pi0, that's cool - thanks for explaining. Protecting the secret bit will be the challenge. A blanket, redirect all requests back to the login/home would work but you'd still need to allow the JS files relevant to the login page through. I'll give it some more thought. Thanks 👍
