### ISSUE TITLE
404 error when using slug instead of ID

### ISSUE THREAD

**Issue by jacobarriola** [nuxt/nuxt.js#1492]
I'm grabbing blog posts from the Contentful API.  I'd like to use a slug in my URL instead of an ID but can't seem to get it working. It works fine when just using an ID; however, when I try and use the slug and pass in the ID as a param, it fails (404).

🆗 working => `myurl.com/post/12345`
🆗 working (better) => `myurl.com/post/my-awesome-slug?id=12345`
🚫 not working (ideal) => `myurl.com/post/my-awesome-slug`

Expected results
- axios fetches post via provided ID in params
- post renders
- on refresh, post renders
- post content is in page source (server rendered)

Actual results
- post initially renders (totally weird that it first renders 🤔 )
- 404 error on refresh
- post content is not in page source on initial render or refresh (page source)

Data object
```
{
  sys: {
    id: some_id
  },
  fields: {
    title: my_title,
    content: my_content,
    slug: my-slug
  }
}
```

## 🆗 Working - when just using id (no slug)
Meh. OK, but not ideal bc I don't want an ID to show up in the url.

`pages/index.vue`
```html
<nuxt-link 
  :to="{ name: 'post-id', params: { id: sys.id } ">{{ fields.title }}
</nuxt-link>
```

`pages/post/_id.vue`
```javascript
async asyncData ({ params }) {
    let { data } = await axios.get(`https://cdn.contentful.com/spaces/[MY_SPACE_ID]/entries/${params.id}`, {
      params: {
        access_token: [MY_TOKEN]
      }
    })
    return { post: data.fields }
  },
  head () {
    return {
      title: this.post.title
    }
  }
```

## 🌮 Working - when passing in the id as a query

Better, but not an ideal solution b/c I don't want the id to show up in the url. `myurl.com/my-slug?id=12345`

`pages/index.vue`
```html
<nuxt-link 
  :to="{ name: 'post-slug', params: { slug: fields.slug }, query: { id: sys.id }">{{ fields.title }}
</nuxt-link>
```

`pages/post/_slug.vue`
```javascript
async asyncData ({ query }) {
    let { data } = await axios.get(`https://cdn.contentful.com/spaces/[MY_SPACE_ID]/entries/${query.id}`, {
      params: {
        access_token: [MY_TOKEN]
      }
    })
    return { post: data.fields }
  },
  head () {
    return {
      title: this.post.title
    }
  }
```

## 😢 Not working - trying to use slug and pass in id for the axios call
`pages/index.vue`
```html
<nuxt-link 
  :to="{ name: 'post-slug', params: { id: sys.id, slug: fields.slug } }">{{ fields.title }}
</nuxt-link>
```

`pages/post/_slug.vue`
```javascript
async asyncData ({ params }) {
    let { data } = await axios.get(`https://cdn.contentful.com/spaces/[MY_SPACE_ID]/entries/${params.id}`, {
      params: {
        access_token: [MY_TOKEN]
      }
    })
    return { post: data.fields }
  },
  head () {
    return {
      title: this.post.title
    }
  }
```

**Comment by KonstantinVlasov** [comment]
Hi, @jacobarriola!

If this is your page: `pages/post/_slug.vue`
then you should use `params.slug` not `params.id`

**Comment by jacobarriola** [comment]
Hey @KonstantinVlasov ! Thanks for your response.

How would I pass in the ID of the post into the component? I need the ID to be able to fetch the entry from the API.

**Comment by KonstantinVlasov** [comment]
If slug is not enough, then you should use ID too.
like this: `pages/post/_id/_slug.vue` or `pages/post/_slug/_id.vue`
and then retrieve id and slug like `params.id` and `params.slug`

**Comment by jacobarriola** [comment]
@KonstantinVlasov thanks again. It works, however I'm back to the original problem of the ID showing up on the URL, which is what I don't want.

Is there any way to remove it or have it not show yet still be available in the component?

**Comment by jacobarriola** [comment]
I think I answered my own question. The ID must be present somewhere, otherwise there's no way the component will know about it, especially if someone is directly coming via a url and not via a link where I can set the id to the store or something.

**Comment by andysay** [comment]
how make it?
