### ISSUE TITLE
Using custom host with https not possible

### ISSUE THREAD

**Issue by chrisnoden** [nuxt/nuxt.js#14937]

**Comment by nandi95** [comment]
@danielroe This has come up for me again after updating to 3.7 @cretueusebiu solution has fixed the issue.
Want me to report this on a new issue?

**Comment by danielroe** [comment]
Yes please. I suspect this will be a regression in nuxi, so maybe best raise it in https://github.com/nuxt/cli. (We might also have already fixed - so it's worth testing with `nuxi-edge` first.)
