### ISSUE TITLE
How to get request header using nuxt

### ISSUE THREAD

**Issue by Yang-Travis** [nuxt/nuxt.js#1494]
I am using nginx proxy to nuxt project, and I set real addr in nginx config, here is my  config:
```nginx
location / {
                   proxy_set_header X-Real-IP $remote_addr;
                   proxy_set_header X-User-Agent $http_user_agent;
                   proxy_set_header X-Referer $http_referer;
                   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                   proxy_set_header Host $http_host;
                   proxy_pass http://127.0.0.1:3000/;
                   proxy_redirect off;
},
```
I found when nuxt project axios a request to tomcat ,tomcat log get X-Real-IP is null，I think the problem is that the axios didn't give the nginx header to tomcat，so I prepare to get nginx header in nuxt and set axios header so that tomcat can get X-Real-IP. So the problem is how to get request header using nuxt ! 
Any one can help ?

**Comment by pi0** [comment]
@Yang-Travis Simply use official [axios-module](https://github.com/nuxt-community/axios-module) it will correctly pass all headers like `X-Real-IP` to the backend. (With `proxyHeaders` enabled). If you need to do the same for your plugins, look at [here](https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.template.js#L134). The `req` is available in nuxt plugins exported function for SSR environments.

**Comment by Yang-Travis** [comment]
@pi0 I guess I don't have describe problem clear，my problem is how to get header info from nginx proxy in nuxt

**Comment by pi0** [comment]
In `plugins/axios.js`:

```js
export default ({ req }) => {
    const headers = (req && req.headers) ? Object.assign({}, req.headers) : {}
    const xForwardedFor = headers['X-Forwarded-For']
    // ...
}

**Comment by Yang-Travis** [comment]
@pi0 Thank you so much !
