### ISSUE TITLE
rc.10 build server cause port problem when deploy on azure app service

### ISSUE THREAD

**Issue by annndddy** [nuxt/nuxt.js#14958]

**Comment by annndddy** [comment]
this problem appear again using the Nuxt 3.7.0 with Nitro 2.6.2
currently edit .output/server/server/chunks/nitro/node-server.mjs
const listener = server.listen(path ? { path } : { port, host }, (err) => {
to
const listener = server.listen(port, host, (err) => {
can fix the problem

**Comment by fabianwohlfart** [comment]
> this problem appear again using the Nuxt 3.7.0 with Nitro 2.6.2 currently edit .output/server/server/chunks/nitro/node-server.mjs const listener = server.listen(path ? { path } : { port, host }, (err) => { to const listener = server.listen(port, host, (err) => { can fix the problem

Instead of changing the node-server.mjs file you should explicity set
NITRO_UNIX_SOCKET=\.\pipe\25ca48bd-25d5-5ac8-b052-66e4d31687f7
– Or whatever path the socket is in.
This resolved the issue for me in a different environment.
