### ISSUE TITLE
Auth Routes from an API

### ISSUE THREAD

**Issue by feedgit** [nuxt/nuxt.js#1495]
Hello support team,
I read https://nuxtjs.org/examples/auth-routes and make my project works well. But I want to use API Auth from URL: http://localhost:8000/rest-auth/login/ instead of using username: demo and password: demo.
How can I fix file api/index.js
```
/ Add POST - /api/login
router.post('/login', (req, res) => {
  if (req.body.username === 'demo' && req.body.password === 'demo') {
    req.session.authUser = { username: 'demo' }
    return res.json({ username: 'demo' })
  }
  res.status(401).json({ message: 'Bad credentials' })
})

// Add POST - /api/logout
router.post('/logout', (req, res) => {
  delete req.session.authUser
  res.json({ ok: true })
})
```
Thank you!

**Comment by congtoanle** [comment]
.

**Comment by alexchopin** [comment]
I'm closing this issue because it's not really related to nuxt source code, I recommend you to post on our gitter to get help from the community.
