### ISSUE TITLE
useFetch() does not forward server-side createError()

### ISSUE THREAD

**Issue by bf** [nuxt/nuxt.js#14977]

**Comment by gspgsp** [comment]
i meet the same problem, as i request the data by the server api, but i can't get the error by the following ways:

https://nuxt.com/docs/getting-started/error-handling, it mentioned that: on server-side, it will trigger a full-screen error page which you can clear with [clearError].

https://nuxt.com/docs/api/utils/create-error
```
export default defineEventHandler(() => {
  //just for test, throw error diractly
  throw createError({
    statusCode: 404,
    statusMessage: 'Page Not Found'
  })
})
```
in fact, it can't trigger a full-screen error page, defined by error.vue. we should get the error in the client-side, there are two ways:
1st:
```
const login = async () => {
  try {
    const res = await $fetch("/api/auth/login", {
      method: "post",
      body: { ...formData },
    });
  } catch (error) {
    console.log("fetch error is:", error.data);
  }
};
```

2nd:
```
const login = async () => {
  const { data, error } = await useFetch("/api/auth/login", {
    method: "post",
    body: { ...formData },
  });
  if (error.value) {
    const er = error.value as FetchError;
    console.log("useFetch error is:", er.data);
  } else {
    console.log("data is:", data.value);
  }
};
```
by these two ways, you can get the error , throwed by the server-side. and then you can use showError() to display the eror in the error.vue page.

i hope this will help someone who met the same problem.
