### ISSUE TITLE
Set html lang attribute

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/nuxt.js#14988]
### Environment

-

### Reproduction

-

### Describe the bug

As stated in the title, we should have a way to set the lang attribute on the parent tag, since it is strongly recommended: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html

**Comment by moshetanzer** [comment]
Hey @danielroe,

Does it at all make sense that this isnt working on compatibilty v4? Since it isnt!
