### ISSUE TITLE
Cannot find 'node-fetch-native/dist/polyfill.mjs' with production build

### ISSUE THREAD

**Issue by michealroberts** [nuxt/nuxt.js#14995]

**Comment by mdigital** [comment]
This still occurs for me with nitropack 2.4.0 on netlify with `pnpm build`. Resolution was to use
```
"pnpm": {
  "overrides": {
    "node-fetch-native": "1.2.0"
  }
}
```
in package.json to restrict to the highest version that was being included.

**Comment by OktayKarakas** [comment]
thank you it fixed my issue.

**Comment by silverbackdan** [comment]
Thanks @mdigital - these little comments when the problem reoccurs on a issue which is easy to fid on a Google search are a huge time-saver.

**Comment by productdevbook** [comment]
Nuxt 3.6 same problem

**Comment by toto6038** [comment]
> Nuxt 3.6 same problem

@productdevbook I was on 3.6.5 and had the same problem. Upgraded to 3.7.1 with `nuxi upgrade --force` and solve the problem. If upgrading Nuxt is not feasible, consider to try deleting node_modules and lockfile and then reinstall with your package manager (pnpm 8.7.4 on my side) again.
