### ISSUE TITLE
GSAP ScrollTrigger is causing a scroll to top on iOS 16 Safari

### ISSUE THREAD

**Issue by o1y** [nuxt/nuxt.js#15010]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-gwd8gb?file=app.vue

### Describe the bug

On iOS 16 Safari with GSAP ScrollTrigger and `scroll-behavior: smooth;` in my stylesheet, the page automatically scrolls back to top when the scroll animation has finished. I'm absolutely not sure if this is related to Nuxt, but this issue only occurs on Nuxt rc.11 (I had no issues on rc.8) which is the reason for filling this report:

**Workaround**
Remove `scroll-behavior: smooth;` _or_ downgrade to an older Nuxt release _or_ use an older iOS version.

**Screencast**
_On the left side you'll see an older iOS 14.x release, on the right side the latest iOS 16.0._
https://user-images.githubusercontent.com/1102712/191813194-b7d8b2d5-08e8-4c42-bfc8-18bd5440872f.mov

### Additional context

I can only reproduce this behaviour on iOS 16.0 Safari.

**Comment by P4KM4N** [comment]
OMG! Thanks!!!!!
 I was doing a website with swup.js + ScrollTrigger and Bootstrap and I got this bug when clicking tabs, I use ScrollTrigger.refresh() to recalcule page height and it was scrolling up, but only on iOS.

**Comment by sander-lameco** [comment]
Not sure if it is fixed. We're on `3.12.2` and it still happens on iPhone IOS.

**Comment by xavi-burgos99** [comment]
> Not sure if it is fixed. We're on `3.12.2` and it still happens on iPhone IOS. Setting `ScrollTrigger.normalizeScroll(true)` does seem to fix it tho.

Yes, `ScrollTrigger.normalizeScroll(true)` seem to fix it. But a **mouse wheel is simulated**, so you can't reload page swiping down the window on iOS. 

I think that, when a gsap animation is done, one of the last functions called is a `scrollTo()` function for internal functionality, and if the `scroll-behavior` is modified, gsap does not work fine. Maybe you can try to stop this last function calls with an `event.preventDefault()` on touchend until GSAP team fixes this bug.
