### ISSUE TITLE
3.0 rc.11 - Classes not being merged from parent to child component (in client-only components)

### ISSUE THREAD

**Issue by ffxsam** [nuxt/nuxt.js#15039]
### Environment

Nuxt CLI v3.0.0-rc.8
RootDir: /Users/samh/Sites/reelcrafter/v2-presentation
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-lzssqp?file=app.vue,components%2FHowdy.client.vue,components%2FTest.vue

### Describe the bug

Classes are not being merged properly into the child component's root div. This was working fine in RC8.

In the reproduction, note how the `app-vue` class is missing from the `Howdy` component root. This only seems to be an issue with `.client.vue` components, not components wrapped in `<client-only>`.

**Comment by riderx** [comment]
Hey @danielroe it seems i still got this issue in the latest version `3.5.3` of nuxt, the example is a bit different but result is the same, it's not merged:
https://stackblitz.com/edit/nuxt-starter-mavf4s?file=components%2FTest.vue

Should i open a new issue ?

**Comment by danielroe** [comment]
Yes, please! 🙏

**Comment by riderx** [comment]
Done !
