### ISSUE TITLE
Error on directly accessing a dynamic route in the browser

### ISSUE THREAD

**Issue by philippe-effinet** [nuxt/nuxt.js#1503]
Hi,

I use the latest version of nuxt (rc6) with the `@nuxtjs/pwa` module

I have a typical `cateogry/_slug.vue` page.

on that page, I have a simple created() method that gets the `this.$route.params.slug` variable and fetches the content from a static javascript array in the Store (No API call).

I can navigate to that page without any problem when clicking on a classic link in the app.

But when I try to access the page directly through the browser. example : `http://localhost:3000/category/blog`

I get a 500 Error, saying `Cannot read property 'slug' of null`, 
either on running `npm run dev` and `npm run start`

I tried replacing created() with beforeMount(), mounted(). And I still get the same error.

I have no clue on what is going on there. Is someone facing the same problem ?

Thanks a lot for your help, in advance !

**Comment by philippe-effinet** [comment]
Nevermind... 

I solved my problem ;) 
It was a stupid mistake... 

Nothing wrong with nuxtjs, only with the developer :D

**Comment by Jonarod** [comment]
@philippe-effinet I think I am getting stupid right now... How did you solve this ?? I got the same problem...

**Comment by philippe-effinet** [comment]
@Jonarod I'm not sure that my mistake will help you but here it is : The static array in which I was trying to fetch the content was initialized in another route. 

So I had to run that route before, in order to access the `category/_slug.vue` without any error. 

So I ended up initializing this array in the `nuxtServerInit` action in the vueX store.

**Comment by Jonarod** [comment]
Yeah I ended up using nuxtServerInit as well.
Thanks

Le lundi 11 septembre 2017, philippe-effinet <notifications@github.com> a
écrit :

**Comment by lsbyerley** [comment]
@philippe-effinet @Jonarod  I'm running into the same issue, but mine involes hitting an api in the store. Would either you be able to comment on mine.. https://github.com/nuxt/nuxt.js/issues/1915 thanks in advance
