### ISSUE TITLE
rc6 error

### ISSUE THREAD

**Issue by gamebody** [nuxt/nuxt.js#1504]
![image](https://user-images.githubusercontent.com/15389880/29770240-9c27ee44-8c20-11e7-8e19-67f7e8dde524.png)

**Comment by paulgv** [comment]
In your code replace references to `~assets` with `assets`, see rc3 release notes: https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc3

**Comment by Atinux** [comment]
Thank you @paulgv
