### ISSUE TITLE
Automatic preloading of CSS

### ISSUE THREAD

**Issue by galvez** [nuxt/nuxt.js#1505]
Is there a way to make the CSS for all pages (`<style>` blocks within them) preload? Is this already what happens? It gives the impression the CSS is being applied as the page loads. Is the current solution to display an overlay `<div>` as a full-page loader?

**Comment by Atinux** [comment]
It's actually what's happening @galvez 

You may encounter https://nuxtjs.org/faq/css-flash in dev mode.
