### ISSUE TITLE
Page still rendered 'live' even for generated pages

### ISSUE THREAD

**Issue by tillkolter** [nuxt/nuxt.js#1507]
Hi,
I am developing a web shop with ~90k detail pages and I am currently experimenting with `nuxt generate` to boost loading times. I could get the generation process working, copied all the generated html pages to my web root and configured the server to use the static pages instead of proxying localhost:3000.

When I load a detail page by entering the full url in the browser the page loads very fast and my API server is not hit. **But** if I use the root page to navigate to any of these pages, the request takes as long as before the generation step and I can see unexpected calls to the API im my backend logs. Of course I use  `asyncData` for the ssr.

Can anybody help?

**Comment by tillkolter** [comment]
Or do I have a basic misunderstanding of the generate feature?

**Comment by alexchopin** [comment]
Hi,
The generate option create .html file filed with data from your API, then when you navigate through the links it's a Vue.js app.
The generate option allows you to get a serverless Vue.js web app but you still need a server for your data API of course.
