### ISSUE TITLE
need ctrl+f5 if u wants see changes because css  not loading

### ISSUE THREAD

**Issue by ezioadf2** [nuxt/nuxt.js#15075]

**Comment by Maurisss94** [comment]
> I had a similar error when I go back to the local dev's browser history (prev. page). mode: <img alt="Снимок экрана 2022-10-29 в 13 46 28" width="1252" src="https://user-images.githubusercontent.com/29500153/198829694-9c06a7a1-80b3-498e-9a80-9dcaab95270d.png">
> 
> I fixed it with:
> 
> ```
> <NuxtLink to="/login">
>         <v-btn variant="plain">
>           Log in
>         </v-btn>
>       </NuxtLink>
> ```
> 
> Was:
> 
> ```
>       <v-btn variant="plain" href="/login" nuxt>
>         Log in
>       </v-btn>
> ```

I have exactly the same behavior, going back in my nuxt 3 app.

<img width="1509" alt="image" src="https://github.com/nuxt/nuxt/assets/9317848/b6531605-566f-4fa9-9a14-e80a3dbd97bf">


Have you been able to solve it? @steklopod

**Comment by danielroe** [comment]
The HTML spec does not allow `<button>` as a child of `<a>` so this will cause a hydration error.

**Comment by Maurisss94** [comment]
Solved, the problem came from the Adblock chrome extension 🥵 

https://github.com/vitejs/vite/issues/11804#issuecomment-1442029604
