### ISSUE TITLE
Nuxt 3: SSR `computed()` memory leak, because the ` isInSSRComponentSetup` variable is set to `false` on the server

### ISSUE THREAD

**Issue by mrauhu** [nuxt/nuxt.js#15095]

**Comment by JBustin** [comment]
Hello @mrauhu 
Do you still experiment this memory behavior with computed ?
I'm searching a huge memleak by migrating my nuxt2 big codebase in nuxt3, and I get a lot of duplicated strings in memory, for a large part of them, that are used in computed. I can't say for now if it is related to my code or the framework...

**Comment by mrauhu** [comment]
Hello @JBustin,

> Do you still experiment this memory behavior with computed ?

No.
