### ISSUE TITLE
Add HMR or automatic server restart for modified serverMiddleware scripts

### ISSUE THREAD

**Issue by pbastowski** [nuxt/nuxt.js#1509]
Hi

The use case is that I am developing some back-end APIs for my app. To do that I use `serverMiddleware` and leverage the express router to implement my APIs. The config looks like this:

**nuxt.config.js**
```js
    serverMiddleware: [
        '~/api/index.js',
    ]
```

So, each time I make changes to and save `/api/index.js`, or any scripts it imports, I would like the server portion of the app to reload/restart and use the latest code, just like the scripts in pages and components folders do.

However, currently that is not the case. I have to manually restart NUXT each time I want to test my changes, which is quite slow.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1344">#c1344</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @pbastowski . Your suggestion is awesome and indeed already planned. We need some special code for HMR middleware stack. The necessary injection part for renderer is already done (f933dd1f32f36b488230a03d500de4d8282e2f3f) but watchers and hot replacement logic for builder is remaining. Will keep this thread updated.

**Comment by pbastowski** [comment]
Thanks @pi0. 

Paul

**Comment by pbastowski** [comment]
Hi @pi0. Is this change integrated in rc11? 
I saw the v1.0.0-rc11 label on the commit and thought it might be available now, but it doesn't appear to be so.

**Comment by pi0** [comment]
Hey paul, and thanks for your interest. This feature still is not completed, but is on roadmap and will be coming soon :)

**Comment by pbastowski** [comment]
Thanks for your quick answer, Pooya :)

**Comment by pbastowski** [comment]
Hi @pi0. Is this feature integrated already?

**Comment by bf** [comment]
Hi @pi0, why is this feature not finished yet? It sounds quite easy to implement. 

Aren't you guys using API with nuxt?

**Comment by clarkdo** [comment]
@galvez has introduced the config for custom defined watch options, maybe he can answser this question.

@galvez How about add the serverMiddleware into default value of the new watcher ?

**Comment by galvez** [comment]
@clarkdo @manniL k, add this to my queue for next PRs. should get to it soon.

**Comment by clarkdo** [comment]
@bf Thank you for the reminding, @pi0 is busy with his personal works recently, sorry for that he can't be active for now, but we should all appreciate his extraordinary work for open source very much, I believe he and @Atinux are the most valuable person for this project.

Nuxt is an open source project, so everyone here is using their private time to contribute, I am very grateful to everyone for their contributions, including code contributions, issues closing and even opening issues, I have you are having same feeling 😸.

Of course, if you have any great idea, we all very welcome any pr to improve this project.

**Comment by bf** [comment]
Also, the docs for build.watch seem to be wrong. The tilde `~` in `watch: ["~/api/index.js"]` is not working. I need to use `watch: [__dirname + '/api/index.js']`.

**Comment by galvez** [comment]
@bf thanks for letting us know, I'll look into it.

**Comment by galvez** [comment]
@pbastowski should be in nuxt-edge soon :)

**Comment by pi0** [comment]
Should be fully possible with #6881 without need to watch :)
