### ISSUE TITLE
When the page is first opened, the response rendering is incomplete.

### ISSUE THREAD

**Issue by langgo** [nuxt/nuxt.js#1510]
The demo in [https://github.com/langgo/nuxt-bug](https://github.com/langgo/nuxt-bug).

Then open `http://localhost:3000/test`

## Description

When the page is first opened, the response rendering is incomplete.

The `active` on `li` is `true`, but on `img` is `false`.

![image](https://user-images.githubusercontent.com/15521789/29802640-34670bb2-8ca9-11e7-80a2-7087d150bc5f.png)

**Comment by KonstantinVlasov** [comment]
Hi, you use `beforeMount`, but it called only on the clientside

**Comment by Atinux** [comment]
@KonstantinVlasov is right, `beforeMount` is called only on client-side, use `created` instead

**Comment by langgo** [comment]
I use ` created ` tried, expression is correct.

However, using ` beforeMount ` should is this phenomenon in the example ? It doesn't fit the expectations.
The `active` on li is true when using `beforeMount`. But on `img` is wrong. The performance is inconsistent.
Not I use ` beforeMount ` is wrong, but ` beforeMount ` show up is wrong.

---

我用 `created` 试了一下， 表现是正常的。
但是，用 `beforeMount` 就应该是例子中的那种现象吗？ 这不符合正常的预期。
即使用 `beforeMount`， `li` 上的属性 `active` 是正确的，`img`上的属性`active`是错误的。两个表现是不一致的。
不是我用`beforeMount`错了， 而是 `beforeMount` 表现起来是错误的。
