### ISSUE TITLE
injectable function not defined on server side

### ISSUE THREAD

**Issue by cahyowhy** [nuxt/nuxt.js#1511]
iam using vue-inject to inject custom service.

injector.js
```
import Vue from 'vue';
import injector from 'vue-inject';

require('../service/postService');
Vue.use(injector);
```

postService.js
```
import injector from 'vue-inject';
import axios from 'axios';
injector.service('postService', function () {
  this.getPosts = function () {
    return axios.get(process.env.postsApi);
  }
});
```

config/nuxt.js
```
plugins: [
    {src: '~/plugins/jquery.min', ssr: false},
    {src: '~/plugins/injector.js', ssr: true},
  ],
```

why my injection  does'nt work in server side rendering but work in mounted and method events..
:(

**Comment by tebaly** [comment]
# npm run dev

```
  modules: [
    '@nuxtjs/axios',
  ],
```

## inject is not a function

.nuxt/axios.js:133:2   (module.exports.__webpack_exports__.a)
.nuxt/index.js:115:51  ( _callee$)
internal/process/next_tick.js:188:7   (process._tickCallback)

---

  **axios.interceptors.response.use(undefined, errorHandler.bind(ctx));**

```
  // Inject axios to the context as $axios
  inject('axios', axios)

  // Setup axios helpers
  setupHelpers(axios)
}

module.exports.__webpack_exports__.a@133:2

**Comment by pi0** [comment]
Please don't create duplicate issues. Thanks.
