### ISSUE TITLE
Add direction in Progress Bar

### ISSUE THREAD

**Issue by miladmeidanshahi** [nuxt/nuxt.js#1512]
Hi @Atinux,
it's good to add `dir:` `rtl` or `ltr` to Customize the Progress Bar options.

**Comment by alexchopin** [comment]
Hi @miladmeidanshahi,
You can create a [custom component](https://nuxtjs.org/api/configuration-loading#use-a-custom-loading-component) or even better do a PR to enhance the [nuxt-loading](https://github.com/nuxt/nuxt.js/blob/dev/lib/app/components/nuxt-loading.vue) component.

**Comment by pi0** [comment]
@miladmeidanshahi Simple solution to make it RTL:

```css
.progress, .nuxt-progress {
  left: auto !important;
}
```

Source: https://stackoverflow.com/questions/10214320

**Comment by Atinux** [comment]
Hi

I just added `loading.rtl` option (default to `false`) in the new release [rc7](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc7), see updated doc: https://nuxtjs.org/api/configuration-loading#customize-the-progress-bar

**Comment by miladmeidanshahi** [comment]
many thanks @Atinux
