### ISSUE TITLE
You must wrap the query string in a "gql" tag

### ISSUE THREAD

**Issue by lyquocnam** [nuxt/nuxt.js#1513]
I try to use with apollo and do same as example project, but this error happend when reload page.
load first time is ok, but i press F5 to reload page, it was happended !
```
You must wrap the query string in a "gql" tag
```
![image](https://user-images.githubusercontent.com/8347826/29814463-3f8865a0-8c62-11e7-8118-6063b3508d3f.png)

![image](https://user-images.githubusercontent.com/8347826/29814605-c5ac773e-8c62-11e7-8d6e-119856c4cad1.png)

**Comment by tillkolter** [comment]
Can you post your component source? The error implies, that a GraphQL query is not following the syntax.

**Comment by lyquocnam** [comment]
i download source from here: https://github.com/nuxt/nuxt.js/tree/dev/examples/vue-apollo
```
yarn
yarn dev
```

**Comment by Atinux** [comment]
@lyquocnam please use the 2.0 version: https://github.com/nuxt-community/apollo-module/releases/tag/v2.0.0
