### ISSUE TITLE
extractCSS: true   css-flash?

### ISSUE THREAD

**Issue by gamebody** [nuxt/nuxt.js#1514]
![gif](https://user-images.githubusercontent.com/15389880/29814533-4876159e-8ce0-11e7-86be-7a692d4179f7.gif)

**Comment by Atinux** [comment]
Please give more informations, also, this is normal in `dev` mode, see https://nuxtjs.org/faq/css-flash

**Comment by gamebody** [comment]
not dev mode.
nuxt rc6

Deployed to server

**Comment by gamebody** [comment]
@Atinux 
not dev mode.

Deployed to server

**Comment by Atinux** [comment]
Do you have a link to the website @gamebody ?

**Comment by gamebody** [comment]
@Atinux 
http://test.fenmio.com/

**Comment by Atinux** [comment]
Make sure to import your css into `nuxt.config.js` at the `css` property, see [global-css](https://github.com/nuxt/nuxt.js/blob/dev/examples/global-css/nuxt.config.js) example.

**Comment by gamebody** [comment]
@Atinux 
extractCSS: true
This setting is to extract CSS to a single CSS file？ I didn't find the CSS file

**Comment by gamebody** [comment]
@Atinux 
The CSS in the Vue component is handled by the vue-style-loader，So, at first, there will be CSS flash

**Comment by ummo** [comment]
@gamebody 
I met the same problem, how can you fix this bug?

**Comment by gamebody** [comment]
@ummo new folder and reinstall npm package。
run build

**Comment by christophwolff** [comment]
@gamebody could you please describe in detail? I have the same problem and nothing seems to work. Npm Build and then npm start starts the production Server right? I reinstalled all npm packages. I have the latest stable node version. I extract my CSS and my bootstrap grid is in the globals. Any idea?

**Comment by christophwolff** [comment]
I created a new project. Copied all my project files. RC8. Used the starter template. Now it works.
