### ISSUE TITLE
Layout slots not working in default layout

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/nuxt.js#15158]

**Comment by VladimirCores** [comment]
Could it be implemented with an additional Nuxt component, something like: `<NuxtLayoutSlot name="nav-items"/>` with Teleport or something else? Because its a very expected behavior, the way to propagate components to slots in NuxtLayout like in `this-doesnt-work` example.

**Comment by lubomirblazekcz** [comment]
@danielroe I can see that layout still re-renders even if it's the same layout, is there any workaround for this yet?
