### ISSUE TITLE
Unknown error after I update Nuxt

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1515]
I have simple project. After I update to `1.0.0-rc6` it gives me this

![screenshot from 2017-08-29 06-52-35](https://user-images.githubusercontent.com/30086515/29817611-ae88e2a8-8c86-11e7-96f0-92b582303f06.png)

Page doesn't load.

**Comment by iamdubx** [comment]
By the way, I used this repo - https://github.com/jerakode/mdc-vue-docs

**Comment by KonstantinVlasov** [comment]
Hi, @iamdubx! You can try to remove node_modules (and package-lock.json if exists) and `npm install`

**Comment by iamdubx** [comment]
@KonstantinVlasov hello. I tried it, didn't help.

**Comment by iamdubx** [comment]
Here's the repo - https://github.com/iamdubx/mdc-vue-docs

**Comment by iamdubx** [comment]
@KonstantinVlasov  I didn't know about `package-lock.json`. Now it helps! Thank you.
