### ISSUE TITLE
Scrollbehavior breaks execution

### ISSUE THREAD

**Issue by alfredomariamilano** [nuxt/nuxt.js#1516]
I encountered this problem when I added, as in the examples on nuxtjs.org, this lines to my nuxt.config.js
`router: {
    scrollBehavior: (to, from, savedPosition) => {
      return { x: 0, y: 0 }
    }
  }`

When webpack rebuilds the nuxt app, it throws this error
` ERROR  Failed to compile with 1 errors                              11:57:00 AM`
 `error  in ./.nuxt/router.js`

`Syntax Error: Unexpected token, expected ( (13:32)`

  `11 | `
  `12 | `
`> 13 | const scrollBehavior = function function(to, from, savedPosition) {`
 `    |                                 ^`
  `14 |       return { x: 0, y: 0 };`
 ` 15 |     }`
 ` 16 | `

 `@ ./.nuxt/index.js 120:0-43`
 `@ ./.nuxt/client.js`
 `@ multi webpack-hot-middleware/client?name=client&reload=true ./.nuxt/client.js`

Obviously breaking everything. I sit a known bug or I've done something wrong myself?

**Comment by awronski** [comment]
@alfredomariamilano It is a but. I will make a PR in few minutes.

Workaround: `scrollBehavior: function _scrollBehavior (to, from, savedPosition) { ... }`

**Comment by alfredomariamilano** [comment]
Thank you very much mate!
The error is fixed, but the scrollBehavior still doesn't work though. Might be because I'm using transitions between pages and using nuxt as an express middleware, I guess.

**Comment by awronski** [comment]
@alfredomariamilano Your are welcome.

I have similar issue. The workaround was to add a timeout in the scrollBehavior the same as the animation time. So the logic in scrollBehavior will be executed after transition. 

Maybe this will help.
