### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by jacky-yanglei** [nuxt/nuxt.js#15182]
### Environment

Operating System: Window 11
Node Version: v16.18.0
Nuxt Version: 3.0.0-rc.11
Package Manager: yarn@1.22.17
Builder: vite
User Config: css, modules, experimental, runtimeConfig
Runtime Modules: 
"@nuxtjs/strapi": "^1.5.1",
"@ant-design/icons-vue": "^6.1.0",
"@esbuild-plugins/node-globals-polyfill": "^0.1.1",
"@esbuild-plugins/node-modules-polyfill": "^0.1.4",
"@rollup/plugin-inject": "^4.0.4",
"@toruslabs/torus-embed": "^1.36.1",
"@walletconnect/web3-provider": "^1.8.0",
"ant-design-vue": "^3.2.12",
"buffer": "^6.0.3",
"echarts": "^5.3.3",
"ethers": "^5.7.1",
"events": "^3.3.0",
"less": "^2.7.3",
"less-loader": "^11.0.0",
"moment": "^2.29.4",
"nprogress": "^0.2.0",
"random-js": "^2.1.0",
"rollup-plugin-node-polyfills": "^0.2.1",
"set.js": "^0.6.0",
"streams": "^0.0.9",
"sweetalert2": "^11.4.33",
"url": "^0.11.0",
"vue-i18n": "^9.2.2",
"walletlink": "^2.5.0",
"web3": "^1.8.0",
"web3modal": "^1.9.9"
Build Modules: -

### package.json
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/strapi": "^1.5.1",
    "nuxt": "3.0.0-rc.11",
    "vite-plugin-require-transform": "^1.0.3"
  },
  "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "@esbuild-plugins/node-globals-polyfill": "^0.1.1",
    "@esbuild-plugins/node-modules-polyfill": "^0.1.4",
    "@rollup/plugin-inject": "^4.0.4",
    "@toruslabs/torus-embed": "^1.36.1",
    "@walletconnect/web3-provider": "^1.8.0",
    "ant-design-vue": "^3.2.12",
    "buffer": "^6.0.3",
    "echarts": "^5.3.3",
    "ethers": "^5.7.1",
    "events": "^3.3.0",
    "less": "^2.7.3",
    "less-loader": "^11.0.0",
    "moment": "^2.29.4",
    "nprogress": "^0.2.0",
    "random-js": "^2.1.0",
    "rollup-plugin-node-polyfills": "^0.2.1",
    "set.js": "^0.6.0",
    "streams": "^0.0.9",
    "sweetalert2": "^11.4.33",
    "url": "^0.11.0",
    "vue-i18n": "^9.2.2",
    "walletlink": "^2.5.0",
    "web3": "^1.8.0",
    "web3modal": "^1.9.9"
  }
}
```
### nuxt.config.ts
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
``` 
export default defineNuxtConfig({
    alias: {
    },
    hooks: {
    },
    vite: {
        plugins: [
            {
                name: 'process-env-transformer',
                transform(code, id) {
                    let transformedCode = code.replace(/process.env/g, 'import.meta.env');
    
                    return {
                        code: transformedCode
                    }
                },
                enforce: 'pre'
            },
        ],
        optimizeDeps: {
            esbuildOptions: {
                define: {
                    global: 'globalThis',
                },
                plugins: [
                    NodeGlobalsPolyfillPlugin({
                        process: true,
                        buffer: true,
                    }),
                    // NodeModulesPolyfillPlugin()
                ],
            },
        },
    },
    router: {
        scrollBehavior (to, from, savedPosition) {
            return {x: 0, y: 0};
        }
    },
    
    meta: {
        link: [
            {
                rel: 'stylesheet',
                href: '/sweetalert2/dist/sweetalert2.min.css',
            }
        ],
        script: [
            {
                type: "text/javascript",
                src: "/sweetalert2/dist/sweetalert2.min.js",
            },
        ]
    },
    plugins: [
        {
            mode: 'client',
            src: '~/plugins/wallet_helper.ts',
        },
    ],
    css: [
        '@/assets/css/custom.less',
    ],
    modules: [
        '@nuxtjs/strapi'
    ],
    strapi: {
        url: 'http://localhost:2337',
        prefix: '/api',
        version: 'v4',
        cookie: {},
        cookieName: 'strapi_jwt'
    }
})
```
![image](https://user-images.githubusercontent.com/17645850/196088360-d5b21fe2-96e2-4198-9fc8-0b293b78216b.png)
![image](https://user-images.githubusercontent.com/17645850/196088384-91dbad38-4b47-4b95-9946-e4254907f91c.png)

### Describe the bug
Running the project in local dev mode is no problem。
After building the project, the error "process is not defined" appears in the browser console, and all events in the page cannot be executed

**Comment by Mattymoo007** [comment]
I've also come across this exact issue in Nuxt 3.7.3, I have made a small reproduction here:
https://stackblitz.com/edit/nuxt-traverson?file=package.json,nuxt.config.ts,app.vue

Running it locally you will see this error showing up in the console only after building. 
<img src="https://github.com/nuxt/nuxt/assets/29456395/5e9ea281-deea-4d12-9d2c-0d72562f1716" width="70%"/>

When using npm run dev no issue shows up. I suspect it has something to do with the `traverson` package I'm trying to get working. But some help clarifying that would be greatly appreciated. 

> Likely you have a node dependency bundled in your browser code. It's impossible to say without a reproduction, but I would search through your node modules to find the piece of code concerned, and add the library to your build.transpile array.

I have added `traverson` package to transpile in `nuxt.config.ts` to no avail.

Here are screenshots of where the error originates and break js execution:
<img src="https://github.com/nuxt/nuxt/assets/29456395/c87e5c7d-8cba-4ff3-abda-dac97fc25817" width="70%"/>

**Comment by leocastroz** [comment]
### Em Português
<div>
  AQUI É O BRASIL!! 
 <img src="https://github.com/leocastroz/desafio-vue3/assets/72839343/1181484b-10b6-46c1-91fd-3dc2941d3d81" alt="dasafio" width="20">
</div>

## Fala pessoal, tudo beleza ?

Então, tive o mesmo problema utilizando o "vue.js 3".

Pelo que notei, alguns projetos criado com "vite" precisam ter suas "variáveis de ambiete" com o nome "VITE" para serem utilizadas em seus ".env"

1. Crie seu ".env" desta maneira

`VITE_API_URL=https://example`

`VITE_API_KEY=testabc123456`

2. Utilize ele em seu arquivo que buscar sua "variável" desta maneira.

`const BASE_URL = import.meta.env.VITE_API_URL;`

`const API_KEY = import.meta.env.VITE_API_KEY;`


Caso eu tenha resolvido os problemas dos senhores, me sigam no GitHub. Obrigado!!

---------------------------------------------------------------------------------------------------
### In English 
## Hey guys, how are you?

🧨So, I had the same problem using "vue.js 3".

From what I noticed, some projects created with "vite" need to have their "environment variables" with the name "VITE" to be used in their ".env"

1. Create your ".env" this way

`VITE_API_URL=https://example`

`VITE_API_KEY=testabc123456`


2. Use it in your file that looks for your "variable" in this way.

`const BASE_URL = import.meta.env.VITE_API_URL;`

`const API_KEY = import.meta.env.VITE_API_KEY;`


If I have resolved your problems, follow me on GitHub. Thanks!!

**Comment by BrunoPanassi** [comment]
i solve my case when i add process with yarn, and then add as a plugin
`yarn add process`

and then on my plugins folder:
plugins/process.ts

![image](https://github.com/nuxt/nuxt/assets/27826074/3ee8344e-4edf-4bd5-bc30-5ca512072a10)

and add on my nuxt.config.ts
![image](https://github.com/nuxt/nuxt/assets/27826074/abc75fa0-02c4-4f09-9b05-832e8a620b45)
