### ISSUE TITLE
i've uploaded myproject to server and my site page not found.

### ISSUE THREAD

**Issue by JeffryWu** [nuxt/nuxt.js#1518]
Hi guys,

i got issue, thank you in advance for your assistance.
i've uploaded myproject to server and my site Page Not Found errors on every page,
How to custom configuring a destination path .

Not Found
The requested document was not found on this server.

**Comment by NicoPennec** [comment]
Which mode of Nuxt did you use for your app in production?
- [ ] SSR
- [ ] PWA
- [ ] Static Generate

Can you also specify the version of Nuxt?
