### ISSUE TITLE
disable vuex strict mode on dev

### ISSUE THREAD

**Issue by christophmayrhofer** [nuxt/nuxt.js#1521]
The forced vuex strict mode introduced in d9796be breaks part of my app. I understand that this was probably added to encourage best practices, but I think there should be an option to disable this behavior.

**Comment by pi0** [comment]
Just set `strict: false` with your exported store. It should override default strict mode :)

**Comment by christophmayrhofer** [comment]
Sry, I forgot to mention that I am using the 'automatically' generated
store  with modules where I simply export a state function.

On Aug 29, 2017 8:26 PM, "Pooya Parsa" <notifications@github.com> wrote:

Just set strict: false with your exported store. It should override default
strict mode :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nuxt/nuxt.js/issues/1521#issuecomment-325752485>, or mute
the thread

**Comment by grunghi** [comment]
Just ran into the same problem, it looks like you can disable the strict mode by exporting the strict value in your `store/index.js`

```js
export const state = () => ({
  ...
})  

export const strict = false
```
