### ISSUE TITLE
[nuxt] [request error] [unhandled] [500], "npm run dev"

### ISSUE THREAD

**Issue by Tweniee** [nuxt/nuxt.js#15225]

**Comment by Dawntraoz** [comment]
Having this SSL issue when `node` is greater than **v18**. It's working fine with **v16**, but I would love to use Nuxt 3 with node 18 if possible 🚀

**Comment by danielroe** [comment]
I don't think this is something we can add by default within Nuxt, but sadly you will need this if you are using a self-signed SSL cert (see https://nuxt.com/docs/api/commands/dev#nuxi-dev).

**Comment by mohammad-saadati** [comment]
i had the same issue, i ran npx nuxi init using node 18, i switched to node 16 and now it works

**Comment by ikromui** [comment]
👋hi
I try this way: in "scripts"
"**dev:https**": "nuxt dev **--https**"
then **run pnpm run dev:https**

**Comment by ArChiiii** [comment]
I running into the issue with `https` with `mkcert` too and able to solve it by proxy
ref: https://www.storyblok.com/faq/setup-dev-server-https-windows
