### ISSUE TITLE
[DOCS] NuxtLayout warn vs documentation

### ISSUE THREAD

**Issue by Triloworld** [nuxt/nuxt.js#15240]

**Comment by JPustkuchen** [comment]
In the meantime, due to https://github.com/nuxt/nuxt/issues/15240 could you perhaps add a "nuxt/content:" prefix to the message:

> WARN  Using <NuxtLayout> inside app.vue will cause unwanted layout shifting in your application.Consider removing <NuxtLayout> from app.vue and using it in your pages.
as this is a bit confusing, if you don't know the reaosns or where it comes from?

sth. like this:
> WARN  nuxt/content: Using <NuxtLayout> inside app.vue will cause unwanted layout shifting in your application.Consider removing <NuxtLayout> from app.vue and using it in your pages.

**Comment by adamdehaven** [comment]
@danielroe this is still an issue a year later -- any plan to resolve?

**Comment by xarthurx** [comment]
> This warning comes from `nuxt/content`. The issue is an upstream one and should be resolved when [vuejs/core#6736](https://github.com/vuejs/core/pull/6736) is merged.

The upstream is merged, but the issue still exist.

**Comment by xarthurx** [comment]
FYI, if using `Nuxt Content`, this warning only appears when `DataDriven: true`.

**Comment by Nancy-Savage** [comment]
> FYI, if using `Nuxt Content`, this warning only appears when `DataDriven: true`.

Did you mean `DocumentDriven: true` ?  Either way, I'm not using that setting. I am still getting the warning myself.

**Comment by xarthurx** [comment]
Why is this issue closed? It still exist...

**Comment by zzdaddy** [comment]
The layout warning is resolved by the following nuxt config.

```
content: {
        documentDriven: {
            injectPage: false // turn off injectPage because we are using our own [...slug].vue
        },
        ...
}
```
it's from [nuxt-blog-starter](https://github.com/dan-bowen/nuxt-blog-starter/pull/9)
