### ISSUE TITLE
[h3] Implicit with addServerHandler

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt.js#15259]

**Comment by DavidSabine** [comment]
> > `handler` needs to be string with the path to a file with the content.
> 
> ok i'm do
> 
> ```
> 
>   addServerHandler({ 
>         route: '/',
>         handler: resolve('./api/test.get.ts'),
>     })
> 
> 
> //Test.get.ts 
> export default defineEventHandler((event) => {
>     // something
> })
> ```
> 
> nuxt return
> 
> 404 Cannot find any route matching /.
> 
> how return render app.vue and catch what return serverHandler in nuxtInst ?

Did you ever figure this out? I'd like to know how.
