### ISSUE TITLE
KeepAlive doesn't work on pages

### ISSUE THREAD

**Issue by mitow7821** [nuxt/nuxt.js#15255]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-8d2nyn?file=app.vue,pages%2Findex.vue,pages%2Ftest.vue
- Click toggle value should change to true 
- Change route to home then go back to test 

### Describe the bug

Despite of `definePageMeta({
  keepalive: true,
});` test route state isn't cached

**Comment by freezyh** [comment]
> [<img alt="@danielroe" width="20" height="20" src="https://avatars.githubusercontent.com/u/28706372?s=40&amp;u=c4a5aa5232c09c3248533366d5c93a138d7e8987&amp;v=4">](/danielroe) [danielroe](/danielroe) closed this as [not planned](/nuxt/nuxt/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22)

keepalive include/exclude props don't work with <NuxtPage>
