### ISSUE TITLE
custome route support

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt/nuxt.js#1526]
Think such a case: I have two route path, **/blog** and **/blog/first-blog**, and I hope the two route have own page. That means, I can't use the nested route, which will make the second route as a child component of the first route. So far, I don't find any efficient way from doc to solve this. Can there is an official tip to answer this requirement.

**Comment by sj82516** [comment]
you can define `router` block inside nuxt.config.js file
```
....
router: {
    extendRoutes(routes, resolve) {
      routes.push({
        name: 'custom',
        path: '/blog/first-blog',
        component: resolve(__dirname, 'pages/blog/index.vue')
      })
    }
  },
....
```

I have tried this method in 1.0.0.rc3.
Hope it works for you.

**Comment by wi-cuckoo** [comment]
@sj82516  Oh, Wonderful ! It should added to the document.

**Comment by wi-cuckoo** [comment]
@sj82516  Not same .vue file. I just need a page for /blog to show blog list, and another page for /blog/:slug content.  Then how to construct the directory. Avoid content page as child of list page
