### ISSUE TITLE
Passing data from the Express to the nuxt

### ISSUE THREAD

**Issue by okYadav** [nuxt/nuxt.js#1529]
I want to set the parameters for the page from the express like csrf token and other parameter from the express code. How to do this
app.js
```typescript
const nuxt = new Nuxt(config);
app.use(require('./routes'));
app.use(nuxt.render);
```
In routes the data is created and I want to pass this to the my page how to do this.

**Comment by ruslankonev** [comment]
@okYadav  you need use a `nuxtServerInit` action inside main store

```js
export const actions = {
  nuxtServerInit ({ commit }, { req }) {
    if (req.user && req.user.email) {
      commit('auth', req.user)
    }
  },
}
```
