### ISSUE TITLE
Some files missing After finished npm run generate 

### ISSUE THREAD

**Issue by JeffryWu** [nuxt/nuxt.js#1530]
hi guys,
My web project using Nuxt.js framework,
i got a broblem after npm run generate finish , 
i appear to have lost my files. (attach)
Am I missing something? 
![messageimage_1504071906853](https://user-images.githubusercontent.com/31407373/29863086-c5c2ee2e-8d98-11e7-9bb0-ea38225bbbc6.jpg)

**Comment by NicoPennec** [comment]
You have dynamic routes in your `/pages/forum/` folder (eg. `_category.vue`).

You have to handle this kind of route in your `nuxt.config.file`

Please, read this doc about `generate` : https://nuxtjs.org/api/configuration-generate/
