### ISSUE TITLE
How to package the CSS file into a separate file

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#1533]
![image](https://user-images.githubusercontent.com/11555571/29868790-efe9abd8-8db2-11e7-96eb-5b5284f43f21.png)
![image](https://user-images.githubusercontent.com/11555571/29868833-19ac394a-8db3-11e7-9882-937445c6a947.png)
the above configuration does not take effect

**Comment by yuchonghua** [comment]
How to make the embedded style automatically extract to the css file? In fact this is mainly on the seo not very friendly? Some search engines are particularly fond of inline styles and base64 images

**Comment by jsonberry** [comment]
@HadiChen Hello!
It looks like your example is from a `pages/web.vue` component. Can you share the contents of that components `<style>` tag?

**Comment by HadiChen** [comment]
@jsonberry 
![image](https://user-images.githubusercontent.com/11555571/29908018-9889e944-8e51-11e7-95f7-586b6d6039aa.png)

**Comment by yeziZ** [comment]
Asked, I also encountered this problem
/ping @alexchopin

**Comment by lucasfischer** [comment]
having the same issue. 

also, it would be cool if the css property in the config file would extract all the css in one big file that could be cached, so the browser don't need to load the whole css every time the page gets loaded.

ps: keep up the good work. love your project so far.

**Comment by yuchonghua** [comment]
@Atinux [It seems that this problem has not been solved](https://github.com/nuxt/nuxt.js/issues/2423) and we hope that it will be resolved

**Comment by leonfather** [comment]
Any solution for this problem?

**Comment by blissjaspis** [comment]
guys you just add `extractCSS: true` to your `nuxt.config.js` to see this works .

after that `npm run build` then `npm run start`.

**Comment by HadiChen** [comment]
add 
```javascript
extractCSS: {
      allChunks: true
    }
```
to your `nuxt.config.js` @TonyLuo

**Comment by TonyLuo** [comment]
@HadiChen  it doesn't work for me....

**Comment by martpie** [comment]
Try 

```
build: {
  extractCSS: {
    allChunks: true
  }
}
```

instead, this is what worked for me.

**Comment by TonyLuo** [comment]
which command do you run? I run " npm run generate" to generate static html , the generated html files contain full set of embed css...

**Comment by martpie** [comment]
I use `npm run generate`, what I posted above is what splited the CSS in its own file.

The whole relevant content of my `nuxt.config.js`:

```
module.exports = {
  ...,
  css: [
    '~/assets/styles/main.scss',
  ],
  build: {
    extractCSS: {
      allChunks: true
    },
    ...
  }
}
```
