### ISSUE TITLE
`definePageMeta`'s layout property errors when computed

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt.js#15344]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13-27789756.491d02f`
- Nitro Version:    `0.6.1-27791756.086802d`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-s6twqp?file=pages%2Findex.vue

### Describe the bug

It [appears to me](https://v3.nuxtjs.org/api/utils/define-page-meta#parameters) that one can use a computed layout in `definePageMeta`. But apparently (see minimal reproduction) that does not work and prints `proxy set handler returned false for property '"layout"'` instead.

That error only appears on client side though, the initial ssr page displays correctly. Try reloading the page.

### Additional context

I receive the same error on RC12.

**Comment by therealstein** [comment]
No this dosn't work. Nuxt 3.8.1 

Do it this way

`<script setup lang="ts">
const route = useRoute();
console.log(route);
const pageMeta = computed(() => route.path.startsWith("/dashboard"))
  ? "dashboard"
  : "default";
</script>

<template>
  <NuxtLayout :name="pageMeta">
    <NuxtPage />
  </NuxtLayout>
</template>
`

**Comment by dargmuesli** [comment]
Isn't `computed(() => route.path.startsWith("/dashboard"))` missing a `.value`? Also, this solution is not really page specific, which `definePageMeta` would allow.

**Comment by juliandreas** [comment]
I tried to follow [the docs](https://i18n.nuxtjs.org/guide/seo#setup) and set up some page titles. It ain't working. I tried both:

```javascript
import { useI18n } from "vue-i18n";

const { t } = useI18n();

definePageMeta({
  title: t("navigation.about"),
});
```

And:

```javascript
import { useI18n } from "vue-i18n";

const { t } = useI18n();

const title = computed(() => t("navigation.about"));

definePageMeta({
  title: title.value,
});
```

Both receive `500 (Internal Server Error)`

**Comment by therealstein** [comment]
@juliandreas switch to useHead , this works with computed properties .. https://nuxt.com/docs/getting-started/seo-meta#usehead

**Comment by therealstein** [comment]
> Isn't `computed(() => route.path.startsWith("/dashboard"))` missing a `.value`? Also, this solution is not really page specific, which `definePageMeta` would allow, but thanks for sharing :)

no it doesn't. It's just a workaround because definePageMeta don't works with computed properties. It depends on your environment if it's usefull for you
