### ISSUE TITLE
Hydration broken on mobile in chrome inspector?

### ISSUE THREAD

**Issue by homerjam** [nuxt/nuxt.js#1534]
Just been attempting to debug my project via chrome remote inspector in dev mode I noticed that the page was server rendered but never hydrated, whilst it continued to work on desktop. If I can provide further info please let me know.

```html
<!-- this never goes away! -->
<div id="__nuxt" data-server-rendered="true">
```

**Comment by alexchopin** [comment]
Should be fixed with the last release.
