### ISSUE TITLE
Unexpected token < when use component

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1536]
Hello. Sorry for creating issue about specific component, but this one is too good. I am talking about https://github.com/drewjbartlett/vue-flickity

I made it work with non-SSR Vue app, but got errors with Nuxt.

```
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
/home/***/Documents/WORK/EXAMPLES/nuxt-examples/node_modules/vue-flickity/flickity.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <

```

I never expect such errors before, so I ask your help.
By the way, error appears when I refresh the page.

**Comment by NicoPennec** [comment]
Have you tried to create a custom plugin with `ssr:false` option?

```
module.exports = {
  plugins: [
    { src: '~/plugins/vue-flickity', ssr: false }
  ]
}
```

**Comment by iamdubx** [comment]
I can't pass option when I tried to create one, so no. I didn't tried. But the guy from discord channel says he tried and it didn't help

**Comment by iamdubx** [comment]
@NicoPennec as for `no-ssr` I tried EGOIST plugin. I think Nuxt using it too? It didn't help.

**Comment by iamdubx** [comment]
By the way, I can't make original library work with Nuxt too - https://flickity.metafizzy.co/

**Comment by homerjam** [comment]
I ended up using this:

```js
// plugins/vue-flickity.js

import Vue from 'vue';
import Flickity from 'vue-flickity';

Vue.component('flickity', Flickity);
```

```js
// nuxt.config.js
plugins: [
    { src: '~/plugins/vue-flickity', ssr: false }
]
```

**Comment by iamdubx** [comment]
@homerjam then how do you pass `flickityOptions`? It gives error

**Comment by homerjam** [comment]
Can you show the error?

Note you don't need the following in your component:
```
components: {
    Flickity
},
```

Otherwise just pass the options as seen in the example here https://github.com/drewjbartlett/vue-flickity

**Comment by iamdubx** [comment]
You guys are right. It was simple. My mistake was I used `Vue.use(Flickity)` not `Vue.component(Flickity)`
Also, I wrapped it in `no-ssr` to fix hydration.

Thanks all!

**Comment by danielpost** [comment]
@iamdubx I am having the same issue, can you explain this?

> Also, I wrapped it in no-ssr to fix hydration.

**Comment by homerjam** [comment]
@danielpost there is now a `no-ssr` component built into nuxt. You can wrap the troublesome component with this to fix hydration (by preventing it from being rendered server side). Also not that in this case `Vue.component()` was required to prevent missing template error.

**Comment by danielpost** [comment]
@homerjam Perfect, I missed that! Thank you!

**Comment by iamdubx** [comment]
@danielpost hi. personally I used this package https://github.com/egoist/vue-no-ssr
As I understand, now it's build-in Nuxt. Haven't tried it yet. 
Can you please write is it working out of the box with new Nuxt?

**Comment by danielpost** [comment]
@iamdubx Yeah, out of the box. I just wrapped the component in `<no-ssr>component here</no-ssr>`.

**Comment by nicoladl** [comment]
Hi guys!
I am having the same issue. My code is:

```html
<no-ssr>
  <slick class="product-list" ref="slick" :options="slickOptions">
      ...
  </slick>
</no-ssr>
```

```javascript
components: {
    Slick
  }
```

```javascript
data () {
    return {
      slickOptions: {
        slidesToShow: 3,
        variableWidth: true,
        centerMode: true,
        arrows: true,
        infinite: false
      }
    }
  }
```

the error:
`Unexpected token <`

What i am going wrong?
vue-no-ssr is buil-in with nuxtjs? (v1.0.0-rc11)

Thank you

**Comment by InstanceOfMichael** [comment]
Does something like this work?
```
import Flickity from '~/node_modules/vue-flickity/src/flickity';
```

**Comment by uptownhr** [comment]
@InstanceOfMichael yes but you should still load this as a plugin with the SSR option as false. I beleive flickity expects window or dom and will break during SSR if you have that enabled.

**Comment by sansor** [comment]
> I've tried all the recommeded solutions above but i keep getting the "Unexpected token <" error. Here is my file https://gist.github.com/jean-bertrand/65533804d52047e3f51688a6fe9992ba.
> Do i have to create a separate component for flickity that I then import into the page?
> 
> Thanks!

Were you able to solve it? I am also stuck. I tried everything said above.
