### ISSUE TITLE
Build broken after upgrade from beta 6 to beta 8

### ISSUE THREAD

**Issue by jazoom** [nuxt/nuxt.js#1537]
I changed nothing except updating the Nuxt dependency from beta 6 to beta 8.

I suspect the problem might be obvious to someone who is familiar with the internals of Nuxt and what changed from beta 6 to beta 8 based on this error message. I had a look through the commits from 6 to 8 and nothing jumped out at me.

If it's not apparent what the problem is I'm more than happy to help narrow down the cause, but it would probably take a while.

![capture](https://user-images.githubusercontent.com/8279246/29901328-be501d04-8e3a-11e7-8bab-6cf99c755b2c.PNG)

**Comment by NicoPennec** [comment]
Can you clean your deps and retry ?
`rm -rf node_modules/ && npm install`

**Comment by jazoom** [comment]
Now I get this:

![capture](https://user-images.githubusercontent.com/8279246/29910071-cd03ea2a-8e6b-11e7-86f0-d2b822225b28.PNG)

**Comment by jazoom** [comment]
Sigh. I should have thought of that. Weird bugs -> reinstall deps from scratch.

It seems to work the same as beta 6 now. Thank you.
