### ISSUE TITLE
Not starting server properly?

### ISSUE THREAD

**Issue by JonathanAlumbaugh** [nuxt/nuxt.js#1540]
I finally have my Nuxt.js app up and running in development, but I can't seem to get it started properly on my server. My server is running NPM v3.10.10 and Node v6.11.12, all dependencies are installed properly, and the app builds properly. I've put the app on a subdomain (dev.jonathanalumbaugh.com) and run "npm build" successfully, then run "npm start" and this is what I get:

![image](https://user-images.githubusercontent.com/9826603/29905731-691fe6b8-8dde-11e7-9df9-67eeef3b2a72.png)

When I visit dev.jonathanalumbaugh.com it just shows me the index of the folder. When I visit dev.jonathanalumbaugh.com:3000 it says that it can't be reached. What am I doing wrong? I checked deployment methods but I'm deploying on my current host instead of Heroku or Now.sh this time, and I tried changing the port in package.json but it started on the same port anyway.

Thanks in advance, sorry for the beginner questions.

**Comment by ausir0726** [comment]
Do you have any reverse proxy server like nginx or others.

It need a proxy to mapping 80 port to your nuxt.js app 3000 port.

Note. port 80 is reserved for system. if you want nuxt.js run port 80 , you need root permission.

**Comment by JonathanAlumbaugh** [comment]
Unfortunately, it's a shared server so I don't have root permission, and it doesn't look like nginx is installed either (or I don't have access to it). The easiest solution would be to build the site at the root directory, wouldn't it? Especially since I don't have root?

Thanks.
