### ISSUE TITLE
PM2 start 

### ISSUE THREAD

**Issue by oo10** [nuxt/nuxt.js#1541]
I want to start the project with `PM2`，like `pm2 start app.js`
So，Which is the JS entry file?

**Comment by ausir0726** [comment]
1. install pm2 ( or use npm )
```bash
yarn add pm2
```

2. modify package.json file `scripts.start` to use pm2 start
```json
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "pm2 start ./node_modules/nuxt/bin/nuxt-start -i max --attach",
    "generate": "nuxt generate",
    "serverbuild": "nuxt build",
    "lint": "eslint --ext .js,.vue --ignore-path .eslintignore .",
    "precommit": "npm run lint"
  },
```

**Comment by NicoPennec** [comment]
Just another way of doing it ;-)

1. install pm2 in global

`npm i -g pm2`

2. start command

`pm2 start npm --name "your-app-alias" -- start`

3. restart command (after re-build)

`pm2 restart your-app-alias`

**Comment by acidjazz** [comment]
@NicoPennec where would we mix a `yarn generate` in this? before the restart?

**Comment by NicoPennec** [comment]
@acidjazz yes you can run the generate cmd, before the restart.

But `yarn generate` is for static server!
PM2 is for dynamic server (nodejs).

You can use PM2 has [static server](http://pm2.keymetrics.io/docs/usage/expose/), but it's not the main purpose.

**Comment by acidjazz** [comment]
@NicoPennec well static server or not you need to nuxt generate, and if you have dynamic routes you cant you need to still serve `/dist/`with nuxt for the router right?

**Comment by waghanza** [comment]
@NicoPennec When you run through `pm2` using `npm`
~~~javscript
pm2 start npm --name "your-app-alias" -- start
~~~
could specify options ? (typically `PORT`)

**Comment by gangsthub** [comment]
I finally could make it work on Windows (with ecosystem file and npm scripts), check out the gist:

https://gist.github.com/gangsthub/a6862362cd49a9d2ed710dc72997c87a

**Comment by waghanza** [comment]
Hi @gangsthub ,

Thanks for update. I've personally added in my `package.json`

```json
"scripts": {
  "prod": "pm2 start npm ecosystem.config.js --name nuxt -- start"
}
```

so I can run `npm run prod`
and `ecosystem.config.js` is

```js
module.exports = {
  apps : [
      {
        name: "nuxt",
        script: "./node_modules/nuxt/bin/nuxt-start",
        env: {
            "HOST": "0.0.0.0",
            "PORT": 80,
            "NODE_ENV": "production",
        }
      }
  ]
}
```

What is basically quite the same as you do.

:heart:
