### ISSUE TITLE
New to Nuxt question

### ISSUE THREAD

**Issue by babakness** [nuxt/nuxt.js#1543]
I noticed that folder `store` is automagically loaded, my question is, how do I get the `store` object to use directly? I'm aware that methods like `fetch`, `asyncData`, and `nuxtServerInit` have access to `commit`, `dispatch` and the like, but how do I do this:

```javascript
store.dispatch('action',data)
```
from within a component <script></script> tags but not necessary the exported methods? 

for example, suppose I want to invoke an action from `created`, there is no `{ store }` as there would be for `asyncData`.

```javascript
export default {
  asyncData({store}) {
    // store is available here
  },
  created({store}) {
   // store is not available here
  }
```

Does it make sense to import store?
```javascript
import { store } from '../store/index'
```

Seems like it should be unnecessary since this file is already imported (?)

**Comment by NicoPennec** [comment]
`asyncData({store})` is a shortcut for : `asyncData(context) { context.store }`

The `context` is only available on `asyncData()` & `fetch()`
more about context:
- https://nuxtjs.org/api/context#context )
- https://nuxtjs.org/guide/async-data#the-context

or, from the template, you can get $store

`<template><div>{{ $store.state }}</div></template>`
