### ISSUE TITLE
Get name router in server incorrect!

### ISSUE THREAD

**Issue by daosonit** [nuxt/nuxt.js#1544]
i have 4 router below, if i  router.push('{..}') in client then i can get name router and params router very good, but F5 in server, it always response info router first, it's name is 'jobs.filter.keyword'. What should I do? Who can help me? 
example: my router http://localhost:8969/search/ban-hang-tai-ha-noi-c1-m31-w1.html. 
When i F5 browser. Accurate must be name router 'jobs.filter.categories.locations' but it's 'jobs.filter.keyword'
```
  {
    path: '/search/:keyword' + '.html',
    component: ('~/views/job/filter.vue'),
    name: 'jobs.filter.keyword'
  },
  {
    path: '/search/:keyword-m:category' + '.html',
    component: ('~/views/job/filter.vue'),
    name: 'jobs.filter.keyword.category'
  },
  {
    path: '/search/:keyword-w:location' + '.html',
    component: ('~/views/job/filter.vue'),
    name: 'jobs.filter.keyword.locations'
  },
  {
    path: '/search/:categories-tai-:location-c:c-m:m-w:w.html',
    component: ('~/views/job/filter.vue'),
    name: 'jobs.filter.categories.locations'
  },
  {
    path: '/search/:keyword-tai-:location-m:m-w:w.html',
    component: ('~/views/job/filter.vue'),
    name: 'jobs.filter.full'
  },
```

**Comment by alexchopin** [comment]
https://github.com/nuxt-community/router-module
