### ISSUE TITLE
nuxt-link (vue router-link) param doesnt work

### ISSUE THREAD

**Issue by cahyowhy** [nuxt/nuxt.js#1546]
i'am trying to passing param to nuxt-link (router-link vue) but it seems doesnt work. this is my snippet and folder structure
```
<nuxt-link :to="{path: '/post-detail', params: { id:idPost } }">
                            {{title}}
                        </nuxt-link>
```
![image](https://user-images.githubusercontent.com/18083469/29920824-8f958906-8e79-11e7-8d3a-aeb4ad3747d1.png)

when i try to hovering on the link, it seems the params is missing
![image](https://user-images.githubusercontent.com/18083469/29920858-adbb7d46-8e79-11e7-9a27-c087ba813075.png)

did i forgot something...
sory for bad english

**Comment by Atinux** [comment]
If you want to use `params` you need to use `name` and not `path`:

```html
<nuxt-link :to="{name: 'post-detail-id', params: { id:idPost } }">{{title}}</nuxt-link>
```

You can see the name for each route into `.nuxt/router.js`
