### ISSUE TITLE
Pinia store values in layout is not server side rendered

### ISSUE THREAD

**Issue by simoneldevig** [nuxt/nuxt.js#15474]

**Comment by Mohamadhassan98** [comment]
Can you explain your solution a little bit more?
I don't call any backend for fetching data, my situation is much simpler than that...
I have an store 
```ts
// part of store.ts
state: () => ({ h1Title: 'initialValue' })
```
and used it inside layout
```html
<!-- Part of layout.ts -->
<div>
    <h1>{{ h1Title }}</h1>
    <nuxt-child />
</div>
```

Now if I change the state inside a page, the `Node mismatch` happens.
I tried doing it in the script setup, in and outside asyncData, both has the same result.
What can I do? (except changing the whole layout and move h1 inside pages itself)
I don't understand your solution about `populating store inside middleware` or something. Can you explain it a little clearer?

**Comment by maximilliangeorge** [comment]
I would also appreciate an illustrative example of the middleware solution.

**Comment by kedniko** [comment]
Related https://github.com/vuejs/pinia/discussions/2441

> I had the same issue and adding a hydrate function in my store solved this for me: https://pinia.vuejs.org/cookbook/composables.html#SSR
