### ISSUE TITLE
Middleware subdirectory ?

### ISSUE THREAD

**Issue by 1sttati** [nuxt/nuxt.js#1547]
How to use middleware in subdirectory?

**Comment by homerjam** [comment]
RTFM! 😉 

https://nuxtjs.org/guide/routing#middleware

**Comment by 1sttati** [comment]
Well, I have the middleware  in directory, middleware/test/test.js

In my page, I used it like this
```
export default {
  middleware: 'test/test'
}
```
I got an error

> TypeError
> 
> Cannot read property 'length' of undefined

**Comment by homerjam** [comment]
I'd suggest it's probably an issue with your middleware. Look for the `length` property - the error should include a line number and work back from there.

Please close the issue. Try SO if you need more help.

**Comment by 1sttati** [comment]
This is what I have in middleware
```
export default function ({store, redirect }) {
  if (!store.state.test.questions || !store.state.test.user) {
    return redirect('/test')
  }
}
```
Where test is my store's module
Could it be that `store.state.test` is undefined

But
middleware/test.js , it's works fine
middleware/test/test.js , is error

**Comment by johnyluyte** [comment]
@homerjam I'm sorry but I couldn't find it in the manual. I supposed it means we cannot use sub folder inside middleware folder? 

e.g.
`/middlewaare/auth.js` => GOOD
`/middlewaare/myFolder/auth.js` => BAD

**Comment by Mucaccino** [comment]
What about it? It's important to the environment I'm working on.
