### ISSUE TITLE
spaces/special characters in complete project path cause `ERR_INVALID_URL_SCHEME` vite error

### ISSUE THREAD

**Issue by ERIS-VN** [nuxt/nuxt.js#15492]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

![image](https://user-images.githubusercontent.com/69683870/202239590-0795eff9-76ce-41fc-b0d8-8330e4cf4060.png)

### Describe the bug

Error when I use run dev

### Logs

```shell
500
[vite-node] [ERR_INVALID_URL_SCHEME] /node_modules/ufo/dist/index.mjs

at /node_modules/ufo/dist/index.mjs
```

**Comment by rahmanlibi47** [comment]
Running this worked for me : 
`npm update ufo vite vite-node`
