### ISSUE TITLE
Transition doesn't work if using layout other then default

### ISSUE THREAD

**Issue by darshishah1011** [nuxt/nuxt.js#1549]
Hi, 

I am trying to use transition effect along with custom layout. Looks like transition does not work if layout is not default. Reproducer: [link](https://glitch.com/edit/#!/nuxt-layout-transitions)    
Is this expected? If yes, how can I have transition on page that uses custom layout?

**Comment by PrimozRome** [comment]
I think it's not yet possible to make transition between different layouts... See this: https://github.com/nuxt/nuxt.js/issues/1519

**Comment by jenil** [comment]
I can confirm this is a bug.

**Comment by nicodev3** [comment]
It would be a nice feature !
