### ISSUE TITLE
aysnc auth middleware keeps flipping out upon logout

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt.js#1551]
I'm trying the concept of auth middleware that first goes after the store, and then an endpoint to verify/refresh the logged in user:

So my `middleware/auth.js` is as so:
```js
export default async function (ctx) {
  if (ctx.store.state.user) {
    return true
  } else {
    try {
      const result = await ctx.app.$axios.get('/me?json=true')
      if (result.data.data) {
        ctx.store.commit('SET_USER', result.data.data)
        return true
      }
    } catch (e) {
      ctx.redirect('/')
      return true
    }
  }
}
```

My problem is when I Logout and then redirect the user to the front page via the way I found to do it in issue via `this.$router.replace({path: '/'})` I get this endless loop:

![image](https://user-images.githubusercontent.com/967369/29961618-d40c4632-8ec5-11e7-8294-308d0774bdd0.png)

here is my logout method:

```js
    logout () {
      this.$axios
        .get('/logout')
        .then((response) => {
          this.$store.commit('SET_USER', null)
          this.$refs.toast.add({type: 'info', title: 'Authentication', body: 'Logout Successful'})
          this.$router.replace({path: '/'})
          // this.$router.go('/')
        })
    },
```

P.S. any tips on how I can handle things smoother please let me know!

**Comment by jleveugle** [comment]
Hello,

Where do you import your middleware ? In your page, layout ?

I think you use your middleware in all pages, don't use your middleware in your `/` route, and use it only for your protected page :)

You can see it here : https://nuxtjs.org/examples/auth-routes#__nuxt

Have a good day ;)
