### ISSUE TITLE
Custom useFetch hook in component and child component with condition on pending causes infinite fetching loop

### ISSUE THREAD

**Issue by Feelixe-tin** [nuxt/nuxt.js#15517]

**Comment by mwilliford** [comment]
I just hit and issue like this and was able to work around it by using a random key as a test.
useCustomFetch<xxxx>(url, { immediate: true, key: salt})

Seems like the shared state of useFetch can create sorta deadlock issue here when called from parent/child components.  Not sure if this is a bug, or there should be a warning in docs about how the same key will share the pending state.
