### ISSUE TITLE
extendRoutes not working

### ISSUE THREAD

**Issue by cyrilpanicker** [nuxt/nuxt.js#1553]
I have `test.vue` file under `pages` directory. So `/test` path automatically works. With the below configuration, I should have got `/test1` pointing to that same `test.vue` file. However, when I load it on browser, I get 404.
```js
    router:{
        extendRoutes(routes,resolve){
            routes.push({
                name:'test1',
                path:'/test1',
                component:resolve(__dirname,'pages/test.vue')
            });
        }
    }
```

**Comment by cyrilpanicker** [comment]
any update on this issue?

**Comment by dohomi** [comment]
not sure but maybe simply create test1.vue with the content of:
```
<script>
  import Index from './test.vue'
  export default Index
</script>
```
I use this approach for adding multi language pages with the same content but different path

**Comment by lurenhtml5** [comment]
hey guys,  i got the same problem ,do you resolve it ?

**Comment by alexchopin** [comment]
https://github.com/nuxt-community/router-module
