### ISSUE TITLE
Rollup + Buble for Nuxt.js

### ISSUE THREAD

**Issue by trusktr** [nuxt/nuxt.js#1556]
I wish when I was using Nuxt.js that I was using Rollup + Buble. The output code is MUCH cleaner, leaner, and faster.

Webpack + Babel leads to heavier code in order to be spec-compliant. To work with Babel, you have to work within a few limitations, but it's no problem. I recently migrated a project from Babel to Buble after fixing some parts of the code to work within Buble's limitations, and the result are AWESOME. I shaved my bundle size and the code is faster and cleaner.

Buble (with Rollup for bundling) is simply awesome, it makes me feel like Webpack + Babel is like strapping weight on a chain to my feet rather than shoes with wings.

**Comment by qm3ster** [comment]
>be spec-compliant. To work with ~~Babel~~**Buble**, you have to work within a few limitations

**Comment by pi0** [comment]
While rollup and buble are both awesome projects (And even nuxt uses internally rollup for lib files) there are **MANY** modern features lacking with rollup, most importantly async chunks and good plugin ecosystem. Yes, un-minified source code may **seems** more clear but doing a real benchmark (Which correct webpack configuration) on both you will quickly find out (Webpack + Babel) is **more efficient as a project grows**. One example we started moving build system for [Bootstrap Vue](https://bootstrap-vue.github.io) from webpack to rollup few month ago. But bundle anylizing shows webpack builds are `~8Kb` less size gzipped! Webpack 3 also supports ESM and Treeshaking with advanced chunk and dependency optimizers.

I suggest reading great [Webpack and Rollup: the same but different](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) article by Rich Harris the author of rollup and Sean Larking from Webpack team.

Besides all of this notes that should be just considered my personal thoughts, `vue-bundle-renderer` has only official plugins for webpack and Nuxt don't have any plan changing it's build system to rollup as it is a complete breaking change.

**Comment by trusktr** [comment]
@pi0 Makes sense, now that I know Nuxt is relying on those Webpack features that Rollup doesn't have. It would totally not make any sense to move to Rollup. For my lib ([infamous](https://github.com/trusktr/infamous)) the only building I'm doing is making a global build for use with script tags, so Rollup fits the purpose great, but Nuxt is essentially wrapping what most app authors would otherwise write, into a package. And for app, Webpack can make more sense for loading JS only for certain routes, etc. My case is only for creating one bundle.

That being said, what about using Buble´with Webpack? Bublé's output is incredibly lean, clean, and fast compared to Babel's.

I made the transition in my library, and the results were AWESOME, the resulting transpiled code was almost identical to hand-written ES5, super lean and clean, and not needing a bunch of heavy helpers like Babel's output.

You'd have to be willing to work with certain caveats like not using `for..of` in certain cases (I had to change things like this into this).

Object spread when creating objects didn't work, so I fixed it like [this](https://github.com/trusktr/infamous/commit/575da34cb653030b000a5edc97490591af6a1ab6#diff-b6239cdf74d33f0c5a6d98c218734bbcL102).

I had to write Promise-based code instead of using async/await for async flow, f.e. I had to manually change [this](https://github.com/trusktr/infamous/blob/9d1ab0a0d0d39a22064c79ef74e9d564161ab896/src/core/ImperativeBase.js#L212-L229) into [this](https://github.com/trusktr/infamous/blob/e2f3868126a1862e9ce5c34f20e5d0a8c3a3a3f7/src/core/ImperativeBase.js#L212-L246). There's also a couple libraries out there that I'm looking at that convert async/await into vanilla hand-written-like Promise code, to use as a pre-step to Bublé, will be a little more machine-like compared to hand-written, but much better than Babel's use of regenerator code with is pure machine code, not human readable unless you're a machine yourself, and it's heavy.

I am using `Symbol.hasInstance`s in my code, so I replaced things like `foo instanceof Bar` with a utility function like `instanceOf(foo, Bar)` to be able to use `Symbol.hasInstance` inside of it (after [polyfilling it](https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/Symbol/hasInstance/polyfill.js))

I had to switch to manually using `Object.defineProperties` on class prototypes for getters/setters that were calling `super` accessors, because Bublé missed that feature. For example, I had to remove [this](https://github.com/trusktr/infamous/commit/729fe3c09005278148a1d6a59835b6e038d1353c#diff-0b863112bfb102b7327ad6e1ce85e01eL196) and add [this](https://github.com/trusktr/infamous/commit/729fe3c09005278148a1d6a59835b6e038d1353c#diff-0b863112bfb102b7327ad6e1ce85e01eR271), where you can see that I am defining what the super class is directly, rather than relying on `super` which Bublé currently just ignores, and the code would fail silently (I was lucky to be skimming the code and noticed this before shipping it, and I sadly don't have any tests in place yet, I've been testing things manually by writing small demos and trying them out, but it's easy to miss things that way, I will add testing very soon).

The migration process will be technically non-breaking if you have good tests in place to catch regressions, all of which can be fixed by writing ES5-style code, and using polyfills for the missing parts.


I would be glad to talk more about the changes I had to make. The end result would be better performance for your end users, which may be completely worth it.

But they'd have to be aware of the limitations.

---

To mitigate users accidentally writing a for..of loop and depending on very specific spec'd behavior that Bublé doesn't support (f.e. modifying arrays during iteration without causing invalid-index errors), it would be possible that you can transpile certain features with Babel first (or after) then handle the rest with Buble´.

Just compare Babel output with Bublé output if you haven't already, you'll be amazed.

**Comment by trusktr** [comment]
Here's both "repls" to try: http://babel.io/repl, https://buble.surge.sh
