### ISSUE TITLE
Hydration text content mismatch 

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt.js#15576]

**Comment by docmattman** [comment]
@mkierdev , did you ever find a solution to this?  `useState` is generally the way to go for sharing a value from server to client but when multiple instances of the same component are used, they ALL get the same value. I'm currently looking to solve this, so if you have any suggestions, please let me know.

**Comment by mahmudz** [comment]
@docmattman 

I'm doing like this at this moment

```js
function getRandomImage(index) {
  // Generating random int within the range of images array length
  const uid = useState(`rid${index}`, () => Math.floor(Math.random() * ((images.length) - 0)) + 0); 

  return images[uid.value]
}
```

**Comment by ahmaddynugroho** [comment]
make empty `ref` and fill it in `onMounted`
