### ISSUE TITLE
Handle SVG files

### ISSUE THREAD

**Issue by nathanaelphilip** [nuxt/nuxt.js#156]
Hi!

Will you be adding support for SVG files via something like https://github.com/visualfanatic/vue-svg-loader ?

I tried installing it and adding the loader in `nuxt.config.js`:

```
build: {
      extend (config) {
          loaders: [{
            test: /\.svg$/,
            loader: 'vue-svg',
          }]
      }
  }
```

**Comment by aprilandjan** [comment]
I archive this with [`svg-sprite-loader`](https://github.com/kisenka/svg-sprite-loader) and some nuxt configs.
1. Create a folder at `assets/svg` and put all your svg files in it.
2. Create custom webpack loader rules in `nuxt.config.js` to handle svg files:

```javascript
build: {
    loaders:[
      {
        test: /\.svg$/,
        include: /assets\/svg/,
        loader: 'svg-sprite-loader?' + JSON.stringify({
          name: '[name]',
          prefixize: false
        })
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'url-loader',
        exclude: /assets\/svg/,
        options: {
          limit: 1000, // 1K limit
          name: 'img/[name].[hash:8].[ext]'
        }
      }
    ]
  }
```
3. Create a plugin js file that handle svg files. The `svg-sprite-loader` will then catch all the imported svg files and insert them at the beginning of document body, and this can only be done at browser enviroment, so we will use `process.BROWSER_BUILD` provided by nuxt to make it run only  in browser enviroment.

```javascript
// plugins/svg-sprite-loader.js
// import only in browser
if (process.BROWSER_BUILD) {
  // import all svgs
  var files = require.context('~assets/svg', false, /\.svg$/)
  files.keys().forEach(files)
}
```

4. Add `plugins/svg-sprite-loader.js` into `nuxt.config.js` to make it work:

```javascript
plugins: [
    '~plugins/svg-sprite-loader'
  ]
```

with all above configs, you can use svgs by its filename such as: `<use :xlink:href="'#upvote"></use>`

Hope this helps! 😄

**Comment by nathanaelphilip** [comment]
Hi @aprilandjan :)

Thanks for responding. If I can’t get the `vue-svg-loader` to work, i’ll definitely give this a try!

**Comment by tforssander** [comment]
Have anyone solved how to integrate the new version of [svg-sprite-loader](https://github.com/kisenka/svg-sprite-loader) (which should now support server-side rendering)?

**Comment by michaelpumo** [comment]
@aprilandjan Your solution hasn't worked for me. Everything compiles okay and no errors are shown. But, nothing is inserted into the DOM. The SVG doesn't look to be getting generated. Any ideas?

**Comment by michaelpumo** [comment]
This hack worked for me: https://github.com/nuxt/nuxt.js/issues/1584

Turns out that it's Nuxt.js getting in the way of SVG Sprite Loader with its own config.
