### ISSUE TITLE
Any way import CSS with scoped

### ISSUE THREAD

**Issue by gfriend-malaysia** [nuxt/nuxt.js#1561]
I put each of the page CSS at bottom of script tag , like example 
`<style src="~/assets/css/about.css"></style>`
but when i route to another page, if the new page element have the same CSS class with previous page element, it will take the previous page CSS, i know put my CSS in style tag with scoped will prevent this case happen, so any way i can import my CSS in style tag with scoped? I tried 
`<style scoped>
@import '~/assets/css/about.css';
</style>`
but it not working, any one can teach me how to do it :)

**Comment by jleveugle** [comment]
Hello

In your page, do you try this ?

```
<style src="~/assets/css/about.css" scoped>
```

**Comment by gfriend-malaysia** [comment]
@jleveugle thanks you so much, and may i ask you one more question ? after i check in
[](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style)
the style tag with scoped css is it not support on major desktop and mobile browser? :)

**Comment by jleveugle** [comment]
Don't be worried, your CSS rules and HTML tag have a uniq data tag. Your CSS file is prefix when compiling to impact this template only ;)

You can show the result in your DOM, like this 

<img width="189" alt="capture d ecran 2017-09-03 a 13 55 17" src="https://user-images.githubusercontent.com/1357733/30002667-a884acac-90af-11e7-951b-e2f8e1327492.png">
