### ISSUE TITLE
Nuxt 3 with Electron.js - 404 Page not found

### ISSUE THREAD

**Issue by zavodnyrichard** [nuxt/nuxt.js#15629]

**Comment by abarke** [comment]
Just got a 404 error when building electron 30 for production. In dev it's fine. The `hashMode: true` fix solved it. 

Seems the `nuxt-electron` library actually sets this, but since upgrading something broke 😬
https://github.com/caoxiemeihao/nuxt-electron/blob/main/src/index.ts#L177

**Comment by abarke** [comment]
Seems nuxt-electron set's this here https://github.com/caoxiemeihao/nuxt-electron/blob/main/src/index.ts#L177

However since upgrading it seems in a production build that is doesn't work anymore.
