### ISSUE TITLE
Website on production mode doesn't work while re-building 

### ISSUE THREAD

**Issue by lingopalm** [nuxt/nuxt.js#1562]
Hi I just registered in github to write this issue...

I love nuxt js so much and its front page hot reloading save me some time but.. it wasted me so much time while compiling backend js file... it's usually 10~20 seconds... Is it normal?

And after I build and start production mode, if I npm run dev for debugging on another port, the website does not work properly and it says some files are missing (I installed nuxt.js font awesome module and after npm run dev all font awesome icons becomes tofu. And bootstrap js will not work)
Of course I can debug on my PC locally so it will not be so big problem but...
While the website is on the production mode, if I make a change and enter npm run build, same problem occurs while it is building. Though problem will not exist after building is done, our users will not be able to click anything and see bunch of tofu boxes.

You will not notice because there is cache so just try go to Chrome incognito mode while running npm run build and you will see some error message on developer console.

I installed nuxt v1.0.0 rc3 and updated to rc8. And started with nuxt-express template which use backpack. So I am not sure this is a problem of backpack or nuxt itself.

Thank you for reading.

**Comment by alexchopin** [comment]
Hi @lingopalm, thanks for your support.
I'm closing this issue to refer it on the proper repo (express-template).
https://github.com/nuxt-community/express-template/issues/76
