### ISSUE TITLE
Vue Meta config is lost when we refresh page in mode:spa

### ISSUE THREAD

**Issue by rAugustos** [nuxt/nuxt.js#1563]
Hi!

When we refresh a page nuxt set  [**vue meta config**](https://github.com/declandewet/vue-meta)  from **nuxt.config.js** instead of **page** or **layout**.

# Version
"nuxt": "^1.0.0-rc8"

# Steps to reproduce

**nuxt.config.js** 
`mode:spa`

**nuxt.config.js**
![image](https://user-images.githubusercontent.com/17957578/30006830-122fb3e0-90d8-11e7-9cf3-d47ffb127c76.png)

**pages/index.vue**
![image](https://user-images.githubusercontent.com/17957578/30006834-2e17679c-90d8-11e7-92e3-8101aca716d1.png)

**Refresh page** - index.vue
![image](https://user-images.githubusercontent.com/17957578/30006835-4a1995dc-90d8-11e7-90c5-840f7ca2d5a5.png)

**Hotreload** - Change anything in index.vue and wait hot-reload
![image](https://user-images.githubusercontent.com/17957578/30006839-61910308-90d8-11e7-8afc-b96a464c399d.png)

# Expected result

Priority of Vue Meta Config when he  load the page or refresh page:

1. Page vue
2. Layout vue
3. nuxt.config.js

**Comment by axu6705** [comment]
+1

**Comment by rAugustos** [comment]
+1

**Comment by rAugustos** [comment]
@pi0 Hi man!

Can you give a tip to how fix (or my fault) this issue?

Thanks in advanced man xD !

**Comment by pi0** [comment]
Hi. It will be fixed with 1fcf3e685ec0bee7079c984cdd0cfa6a80e8be2d in nuxt rc.9 :)

**Comment by Jonarod** [comment]
+1 I was about to post the exact same issue :) Thanks

**Comment by rAugustos** [comment]
Thanks @pi0 !

**Comment by dreambo8563** [comment]
verify fixed in rc 9

**Comment by axu6705** [comment]
@dreambo8563 Yes, and fix mounted run twice.
