### ISSUE TITLE
deploy nuxt 3 on plesk

### ISSUE THREAD

**Issue by mohamad68** [nuxt/nuxt.js#15630]
### Environment

ssr

### Reproduction

null

### Describe the bug

how can I deploy Nuxt 3 on Plesk? 
there is no guide on the official site for deploying on Plesk plz give me a step-by-step guide to deploy Nuxt 3 on Plesk.

**Comment by kitchanut** [comment]
Plesk Tell Me, How to Deploy

**Comment by mohamad68** [comment]
deploy to what? what is you server

**Comment by fikrihanda** [comment]
how deploy with ssr false ?

**Comment by Dbone29** [comment]
If you want to deploy with SSR enabled on Plesk:

1. You need to run:
npm run build

2. Set the document path and program path to the project root path on the file system.

3. Create a new file. In my case, I named it server.js. You need to set this file as the startup file in Plesk. This file only contains the following:

import('./.output/server/index.mjs');

This worked for me with Nuxt 3.

To deploy without SSR, you have to use the generate function, which only works if you do not use code that requires SSR.
Perhaps the documentation can help you:
https://nuxt.com/docs/getting-started/deployment

I hope I could help you guys!

**Comment by corexo** [comment]
thank you that worked for me @Dbone29

**Comment by Ism1tha** [comment]
> import('./.output/server/index.mjs');

This worked for me, thank you
