### ISSUE TITLE
When using pageTransition, quickly switching pages will result in an error

### ISSUE THREAD

**Issue by mcpanl** [nuxt/nuxt.js#15643]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `app`, `modules`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-fqnyif?file=app.vue

### Describe the bug

When using pageTransition, mode=out in is configured, the page jump will get a gorgeous special effect (0.6s). At this time, if you quickly switch between two different pages, the console will report an error and the page jump cannot continue. The error message is as follows: `Uncaught DOMException: Node insertBefore: Child to insert before is not a child of this node`

css:
```
  .page-enter-active, .page-leave-active {
    transition: all 0.6s;
  }

  .page-enter-from, .page-leave-to {
    opacity: 0;
    filter: blur(4px);
  }
```

nuxt.config.js:
```
app {
  pageTransition: { name: 'page', mode: 'out-in' }
}
```

**Comment by bukandicki** [comment]
[localhost_3000_about.webm](https://github.com/user-attachments/assets/b4e614ff-9e47-43a8-9bf9-410ca7437098)

Is this still not fixed in Nuxt 3 @danielroe? I made a very simple transition between two pages, but they still overlap each other and don't wait for the animation to finish first.

**pages/about/index.vue**

```vue
<script setup lang="ts">
import gsap from 'gsap';

definePageMeta({
  pageTransition: {
    name: "page-transition",
    mode: "out-in",
    css: false,
    onLeave(el, done) {
      const h1_element = el.querySelector("h1")

      gsap.to(h1_element, {
        x: 20,
        onComplete: done
      })
    },
  }
})
</script>

<template>
  <div>
    <h1>About</h1>
    <NuxtLink href="/projects">Projects</NuxtLink>
  </div>
</template>
```

**pages/projects/index.vue**

```vue
<script setup lang="ts">
definePageMeta({
  pageTransition: {
    name: "page-transition",
    mode: "in-out",
    css: false,
    onLeave(el) {
      console.log("Project on Leave ==> ", el)
    },
  }
})
</script>

<template>
  <div>
    <h1>Projects.</h1>
    <NuxtLink href="/about">About</NuxtLink>
  </div>
</template>

```
