### ISSUE TITLE
Several `DevOnly` in one component raise error `Element is missing end tag.`

### ISSUE THREAD

**Issue by vmoshikov** [nuxt/nuxt.js#15646]

**Comment by AhmadMraish** [comment]
I have this issue too.. Fresh on fresh installation... ran npm run dev and I get
[2:47:51 AM]  ERROR  Element is missing end tag.
[vite-node] [plugin:vite-plugin-vue-inspector] [24] /node_modules/@nuxt/ui-templates/dist/templates/welcome.vue
localhost/:1     Failed to load resource: the server responded with a status of 500 (Vite Error)

**Comment by danielroe** [comment]
If you are facing a problem, please open a new issue with a reproduction. Note that `<DevOnly>` components cannot be nested.
