### ISSUE TITLE
Route with params do not work after refresh

### ISSUE THREAD

**Issue by bin4ryio** [nuxt/nuxt.js#1564]
Hello there. I'm currently having an issue where my page do not work after refresh. It is clear that in Vuex inspector the `event: {...}` still has content. I have also tried `asyncData()` instead of `fetch()`, am I missing something here?

After refresh, it will says `event is undefined`.

According to official tutorials, I also like to know if axios in store actions is good practice or not. Thank you very much.

**events/_id.vue**
```
<template>
  <div>{{ event.attributes.name }}</div>
</template>

<script>
import { mapActions, mapGetters } from 'vuex'

export default {
  validate ({ params }) {
    return !isNaN(+params.id)
  },
  fetch ({ store, params }) {
    if (store.state.events.event.id !== params.id) {
      store.dispatch('events/getEvent', {
        id: params.id
      })
    }
    return store.state.events.event
  },
  computed: {
    ...mapGetters({
      event: 'events/event',
      error: 'events/error'
    })
  },
  methods: {
    ...mapActions({
      getEvent: 'events/getEvent'
    })
  }
}
</script>
```

**store/events.js**
```
// import { getUserFromLocalStorage } from '~/utils/auth'

export const state = () => ({
  event: {},
  events: [],
  error: ''
})

export const getters = {
  event: state => state.event,
  events: state => state.events,
  error: state => state.error
}

export const actions = {

  async getEvent ({ commit, dispatch }, { id }) {
    try {
      await this.$axios.$get(`events/${id}`)
      .then((res) => {
        console.log(res.data)
        commit('SET_EVENT', res.data)
        dispatch('clearError')
      })
    } catch (err) {
      dispatch('setError', err.response.data.error)
    }
  },

  async getEvents ({ commit, dispatch }) {
    try {
      await this.$axios.$get('events')
      .then((res) => {
        commit('SET_EVENTS', res.data)
        dispatch('clearError')
      })
    } catch (err) {
      dispatch('setError', err.response.data.error)
    }
  },

  setError ({ commit }, error) {
    commit('SET_ERROR', error)
    setTimeout(() => {
      commit('CLEAR_ERROR')
    }, 10000)
  },

  clearError ({ commit }) {
    commit('CLEAR_ERROR')
  }
}

export const mutations = {
  SET_EVENT (state, payload) {
    state.event = payload
  },
  SET_EVENTS (state, payload) {
    state.events = payload
  },
  SET_ERROR (state, payload) {
    state.error = payload
  },
  CLEAR_ERROR (state) {
    state.error = null
  }
}
```

**Comment by clarkdo** [comment]
In your case, it shuold be `store.state.events.events.event.id`

**Comment by bin4ryio** [comment]
@clarkdo sorry if I'm unclear. I'm having issue only after I **refresh** the page, where it will shown as below:

![2017-09-03_16 10 53_valkyrie_ss](https://user-images.githubusercontent.com/21124691/30001491-98285918-90c2-11e7-8431-b993262127dc.jpg)

I had tried with/without async/await, both `fetch()` and `asyncData()`.

**Comment by jleveugle** [comment]
@bin4ryio Do you try `v-if="event && event.attributes"` ?

Your attributes field seems `undefined` :/

Do you try to print your event object to be sure it's correct ?

**Comment by bin4ryio** [comment]
@jleveugle Hello. I have checked Vuex state in Chrome (F12). With your code I'm seeing that after a **REFRESH** the `event` state became `null`. Looks like it have to do with params is empty after refresh.

**Before refresh:**
![2017-09-03_17 21 28_valkyrie_ss](https://user-images.githubusercontent.com/21124691/30001828-57fd5e42-90cc-11e7-9a0a-178ae3f2975b.jpg)

**After refresh:**
![2017-09-03_17 19 26_valkyrie_ss](https://user-images.githubusercontent.com/21124691/30001826-4d4f6472-90cc-11e7-9aaf-52dd0145a64f.jpg)

I've used to and see no console logging of params.id after refresh.
```
  validate ({ params }) {
    return !isNaN(+params.id)
  },
  fetch ({ store, params }) {
    console.log(`params :: ${params}`)
    store.dispatch('events/getEvent', {
      id: params.id
    })
  },
```

**Comment by jleveugle** [comment]
event is a reference to state.event ?

Do you try to use $store.state.event in your template instead of event ?

**Comment by jleveugle** [comment]
Do you try to use `$store.state.event` in your template ?

**Comment by bin4ryio** [comment]
That way it will surely work, but still does not solve the state loss after refresh.

**Comment by Atinux** [comment]
Actually the `fetch` method is not called on client-side since it's called on derver-side after refresh. Are you sure the event displayed in console log is correct on server-side? Also, could you look at the source code and write to us what's inside `window.__NUXT__`?

**Comment by bin4ryio** [comment]
Thanks for the prompt reply. I have successfully resolve it by using `async fetch.... { await dispatch... }`

**Comment by nirvanpagooah** [comment]
I had the same problem when I tries to create my own router with `asyncData()`. The fix was to use the `generate` hook/property in the nuxt config and give it your prebuilt aliases as stated [here](https://nuxtjs.org/api/configuration-generate/).

For my case it was:

`  generate: {
    routes: function () {
      return importData.map( (content) => {
        return '/person/' + content.slug
      })
    }
  }
`

Also, you need to use extendRoutes example:

`module.exports = {
  router: {
    extendRoutes (routes, resolve) {
      routes.push({
        name: 'personne',
        path: '/person/:slug?',
        component: 'pages/person/_slug.vue'
      })
    }
  }
.
.
`
