### ISSUE TITLE
can't fetch data on the server, only on client side

### ISSUE THREAD

**Issue by sebalaini** [nuxt/nuxt.js#15657]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `ssr`, `telemetry`, `loading`, `app`, `vue`, `plugins`, `modules`, `tailwindcss`, `vite`, `render`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/sebalaini/laravel_docker-compose 

### Describe the bug

I'm upgrading a [pubblic GitHub repo](https://github.com/sebalaini/laravel_docker-compose) (I use that base on a private one, I'm using this one to help me with the project migration) with Nuxt 3 but I'm having some issues fetching data on reload.

I have a reverse proxy to redirect to the correct docker image.

I'm using this code on the page:

```
<script setup>
const runtimeConfig = useRuntimeConfig()
const { data: app, pending, error, refresh } = await useAsyncData(() => $fetch(`${runtimeConfig.public.BASE_API_BROWSER_URL}/message`))
```

the same goes if I use `...await useFetch...` instead of the useAsyncData

Very simple but it seems to work only when I made some changes in the code and then see the page loaded with HMR, if I refresh the page I get the following error.

```
Error: request to http://localhost/api/message failed, reason: connect ECONNREFUSED 127.0.0.1:80 ()
```

that URL is perfectly working, if I copy and paste it I get the correct response, also as I said above, it does work if I made a change a change in the code and save the file, with HMR is working fine, it just doesn't work when I refresh the page.

I found out that I could do this

```
if (process.client && error.value) {
  await refresh()
}
```

but that still doesn't answer why on refresh that doesn't work but with HMR yes.

I want to be able to fetch data on the server like the old  `async asyncData`

**Comment by zqhexor** [comment]
how to solve this problem, and I am in this situation. plz say it in detail， thank you

**Comment by zqhexor** [comment]
> You are right, using `webserver` is working, probably the 1st problem was that my ENVs weren't working and when I made them work I should have used that instead of the client one.
> 
> I still don't understand how was working in Nuxt2 but not in Nuxt3 🤔 maybe has to do with Axios and now I'm using fetch

how to solve it, bro. I got in this problem

**Comment by sebalaini** [comment]
in my case, I had to use the docker container name which is `webserver` instead of using the Frontend endpoint, that would be http://localhost/api/message but everything depends from your setup
