### ISSUE TITLE
Layout on error.vue does not seem to work

### ISSUE THREAD

**Issue by anthonny** [nuxt/nuxt.js#1566]
Hi here, 

I try to customise my error page, i have read this doc https://nuxtjs.org/guide/views#error-page.
The `error.vue` works well but i encounter a problem with the layout property.

## Versions
 ❯ npm -v       
5.3.0

 ❯ node -v         
v7.4.0

"nuxt": "^1.0.0-rc8"

### Create a new project with the starter kit
```
vue init nuxt/starter error-layout
```

### Create layouts
In the `layouts` directory, create two files:

#### error.vue
```vue
<template>
  <div class="container">
    <h1 v-if="error.statusCode === 404">Page not found</h1>
    <h1 v-else>An error occurred</h1>
    <nuxt-link to="/">Home page</nuxt-link>
  </div>
</template>

<script>
export default {
  props: ['error'],
  layout: 'blog' // you can set a custom layout for the error page
}
</script>
```
#### blog.vue
```vue
<template>
  <div>
    <div>My blog navigation bar here</div>
    <nuxt/>
  </div>
</template>
```

### Start the application
Run:
```
npm run dev
```

### Test the result
Open a browser and go to http://localhost:3000/unknow-page

![image](https://user-images.githubusercontent.com/2006548/30002162-b878b444-90a2-11e7-9a07-49ad2bcd3ee5.png)

### Expected result

The text `My blog navigation bar here` should be visible in the rendered content, right?
Tell me if i am wrong or if something is missing in my code

Thank you for your work 👍

**Comment by pi0** [comment]
Hi @anthonny  Sorry for lack of docs. Actually, it was because of a **fix** introduced in recent updates. The story behind it is `error.vue` **itself is a layout** so composing it with other layouts makes conflicts (especially with css). So it is now a pure and standalone page. You can add header and other stuff into it if required.

**Comment by umbrella-anton-karmazin** [comment]
@pi0, hey! Is there any way to restore the old behavior, do it an optional? 
I' actually have the same layouts for default and error, and this duplication really bothers me.
