### ISSUE TITLE
 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside, or missing . Bailing hydration and performing full client-side render.

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt.js#1567]
| 0down votefavorite | [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside, or missing . Bailing hydration and performing full client-side render.
-- | -- | --

```


<template lang="pug">
    div
      header
       h1 project news line
       nav
        nuxt-link(to='/') home
        nuxt-link(to='/about') about 
        nuxt-link(to='/contacts') call me
      .wrapper
       form(@submit="postMesseage")
        section.container
         md-input-container
          label With label
          md-input(placeholder='Head',  v-model="name", type='text', )

          button(type="submit") add news
         .quill-editor(:content='content', @change='onEditorChange($event)', @blur='onEditorBlur($event)', @focus='onEditorFocus($event)', @ready='onEditorReady($event)', v-quill:myquilleditor='editorOption', v-model="newMessage")

       section#message(v-for='(message, index) in messages')

         button( @click="deleteRow(index)" v-bind:id="message._id") удалить
         nuxt-link(:to="{ path: '/edite/'+message._id,  params: { id: message._id } }") 
          button Редактировать
         h2 
          nuxt-link(:to="{ path: '/news/'+message._id,  params: { id: message._id } }" ) {{ message.name }}

           div(v-html="message.content") {{ message.content }}




    </template>
```

how fix it ? not understand :( help please

**Comment by NicoPennec** [comment]
`md-input-container` is an angular material component ???

share more details please : template & script, full path filename, full error msg...

**Comment by andysay** [comment]
problem with v-html="message.content" if remove this param , then no error

response from server 

`{"total":1,"limit":10,"skip":0,"data":[{"_id":"59acc2b18f9b35143f4b3ce8","content":"<p><s>asdasdasd</s></p>","name":"asdasdasdasd","createdAt":"04/09/2017","updateAt":"04/09/2017"}]}`


if exclude html tags , then okey too... why v-html not worked ?

**Comment by andysay** [comment]
if npm run build and run start , thats okey ! 

but if i use npm run build dev i have error in console :(

**Comment by homerjam** [comment]
@andysay this is to do with a component not being compatible with ssr, use `<no-ssr></no-ssr>` component to hide the error.

**Comment by Jussiadev** [comment]
@andysay I have a similar problem, I took your advice and wrapped all the components in tags `<no-ssr></no-ssr>`, but it did not help

**Comment by homerjam** [comment]
@Jussiadev that error is certainly an issue that arises from differences between server and client rendered html (virtual dom). Try removing components until you can identify the problem, remember any component which uses client side only apis such as `window` is likely going to cause this.

**Comment by Jussiadev** [comment]
@homerjam Thanks for the advice. Could you answer me another question? Why do I have some components (for example, downloading or clicking on a link to a div) work only in the developer mode, not only some in production mode?

**Comment by lyzs90** [comment]
> Try removing components until you can identify the problem

im mapping getters and interpolating in my template. as long as those are present, i run into the error. any suggestions to resolve this?

**Comment by tetreault** [comment]
just chiming in from the future, in case anyone else comes across this. I had the exact same warning in my console log. 

My use case: index.vue loading a component and passing some params that get loaded from a local JSON file in `static`. Here is a tiny demo:

`pages/index.vue`
```
<template>
  <section class="container">
    <NavBar/>
    <div>
      <ProjectTile 
        :project-title="homePageData[0].projectTitle"
        :client-name="homePageData[0].clientName"
      />
    </div>
  </section>
</template>

<script>
import NavBar from '~/components/navbar/navbar.vue';
import ProjectTile from '~/components/project-tile/project-tile.vue';
import homePageData from '~/static/data/home-page-data.js';

export default {
  data() {
    return { homePageData }
  },
  components: {
    NavBar,
    ProjectTile
  }
}
</script>

<style>
.container {
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
}
</style>
```

`components/project-tile/project-tile.vue`
```
<template>
    <div class="project-tile-container">
        <div class="project-image-container">
          <img src="">
        </div>
        <div class="project-text">
          <h2>{{ projectTitle }}</h2>
          <p>Client: <a href="#" title="">{{ clientName }}</a></p>
        </div>
    </div>
</template>

<script>
export default {
  props: ['projectTitle', 'clientName'],
  components: {}
}
</script>

<style>
.case-study-container {
  display: block;
  min-width: 100vw;
  min-height: calc(100vh - 100px);
}
</style>
```

Wrapping the project-tile component template in `<no-ssr>` resolved the issue for me. Like so: 
```
<template>
  <no-ssr>
    <div class="project-tile-container">
      <div class="project-image-container">
        <img src="">
      </div>
      <div class="project-text">
        <h2>{{ projectTitle }}</h2>
        <p>Client: <a href="#" title="">{{ clientName }}</a></p>
      </div>
    </div>
  </no-ssr>
</template>
```

**Comment by qm3ster** [comment]
@tetreault you didn't solve it, you just silenced it. There will be nothing in your server rendered html in place of that component.
Can you post `~/static/data/home-page-data.js`? It's probably not deterministic between server and client and that's what causing your problem.

---
@lyzs90 please post code for 
>im mapping getters and interpolating in my template

**Comment by tetreault** [comment]
@qm3ster thanks for the response, happy to learn more about the issue and why I caused it since i'm learning as i go. Here's the `~/static/data/home-page-data.js` file. 

```
const homePageData = [
  {
    projectTitle: 'YYYYY',
    clientName: 'YYYYY',
    clientLink: 'https://YYYYY.com/',
    emotion: 'YYYYYYY',
    asset: ''
  },
  {
    projectTitle: 'XXXXX',
    clientName: 'XXXX',
    clientLink: 'https://XXXXX.com/',
    emotion: 'XXXXX',
    asset: ''
  },
];

module.exports = homePageData;
```

**Comment by qm3ster** [comment]
I see it's really static inside, okay.
Okay, so, probably won't help, but start by relocating that somewhere else, for example `~/assets`, or anywhere non-special.
You are requiring it into the bundle, so absolutely no reason for static to copy that into your dist.

**Comment by tetreault** [comment]
Good to know, thanks again for the feedback @qm3ster!

**Comment by qm3ster** [comment]
Also, in `pages/index.vue`, add
```js
  data() {
    console.log('data', homePageData)
    return { homePageData }
  },
  mounted() { console.log('mounted' this.homePageData) }
```
and see if it's the same on the server (with 'data' prefix) and on the client (with 'mounted' prefix)

**Comment by tetreault** [comment]
Both console log outputs are the same @qm3ster

**Comment by homerjam** [comment]
@tetreault is that the actual file posted above? In the past I've tripped up on this using random or date in my otherwise static data...

**Comment by tetreault** [comment]
yup thats the actual value, with the actual strings changed to protect some data @homerjam

**Comment by qm3ster** [comment]
1. You get the hydration error even with this literal censored data?
2. Does doing `no-ssr` to **only** the insides of `project-text` div fix it?
```vue
      <div class="project-text">
        <no-ssr>
          <h2>{{ projectTitle }}</h2>
          <p>Client: <a href="#" title="">{{ clientName }}</a></p>
        </no-ssr>
      </div>
```

**Comment by tetreault** [comment]
not bailing on this @qm3ster just wrapped up in work tonight! will report back soon, moving the <no-ssr> tags as requested for a test.

**Comment by CurtisBelt** [comment]
Having this issue as well. <no-ssr> is not an option for me, as this is for the contents of WordPress blog posts. Given that the entire reason I needed SSR was SEO, I cannot <no-ssr> the blog content as you can imagine.
