### ISSUE TITLE
document undefined with type.js module

### ISSUE THREAD

**Issue by quangtn0018** [nuxt/nuxt.js#1568]
typed.js: 
https://github.com/mattboldt/typed.js/tree/9905c0b2d6b79a207211b818da63600d30af1212

I was trying to use typed.js in my pages/index.vue like this

// pages/index.vue
<template>
  <section>
    <div id="typedjs"></div>
  </section>
</template>

<script>
import Typed from 'typed.js';

var options = {
  strings: ["<i>First</i> sentence.", "&amp; a second sentence."],
  typeSpeed: 40
}

var typed = new Typed("#typedjs", options);

export default {
  data () {
    }
  }
}
</script>

But when I try to access the element, it says that the document is not found. Is there any way to solve this? Also, if there is a solution, where would be the best place that I should declare the "options" and instantiate a new Typed within exports default {} ?

**Comment by NicoPennec** [comment]
it seems an error of SSR that is not supporte by Typed.js.

That lib is client-side only.

you should create a nuxt plugin with `ssr:false` option, read this documentation: https://nuxtjs.org/guide/plugins/#client-side-only
