### ISSUE TITLE
about the flash

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#1571]
As menthiod in https://github.com/nuxt/nuxt.js/issues/1272  I was troubled by the flash

now I find that,  if I click the link at the top, every thing works ok, but when I click the link at the bottom（scrollbar）, this page will first at current page up to top, and then go to another page, then the flash come.

you can visit https://www.awesomes.cn/repos/Applications

Then just click both  `react` and  `pdf.js`，you will find the flash caused by scrollbar

![](https://raw.githubusercontent.com/bimohxh/front-sites/master/nuxt.png)

**Comment by Atinux** [comment]
Hi @bimohxh 

Are you using page transitions into your application?

**Comment by bimohxh** [comment]
@Atinux I have no transitions  config  https://github.com/awesomes-cn/new-awesomes/blob/master/nuxt.config.js

**Comment by alexchopin** [comment]
#1652
