### ISSUE TITLE
Dynamic nested path

### ISSUE THREAD

**Issue by Serdgjo** [nuxt/nuxt.js#1573]
How to be in this situation?
![image](https://user-images.githubusercontent.com/9413374/30034313-dd7d9026-91a0-11e7-885b-8eb0aa7bba55.png)

Conditions:
1. params _lang and _alias dynamic
2. link pages/_alias.vue  to pages/_lang/_alias.vue...

~My solutions (did not work):~
~1. redirect to next route... beforeEnter (to, from, next) => {}~
~2. merge files: pages/_lang/index.vue and pages/_lang/_alias.vue~
~3. set page validate params (only render page 404, no reroute)~
~4. no priority at route (no function)~
~....~

**Comment by Serdgjo** [comment]
Created file pages/_lang.vue for pages/_lang/index.vue and pages/_lang/_alais.vue, remove file pages/_alias.vue...

Result:
/ - ok
/en - ok
/en/test - ok
/test - unavailable

![image](https://user-images.githubusercontent.com/9413374/30058110-d5384818-9239-11e7-9293-8f375a71d76b.png)

**Comment by Serdgjo** [comment]
Created a [repository](https://github.com/Serdgjo/nuxt-i18n-dynamic-path) to demonstrate my situation.
This repository not available pages: /test1, /test2, because the file /middleware/i18n.js in the line 7 exit.

How to make instead of exit redirect to another route? Or are there other options?

**Comment by alexchopin** [comment]
Hi, you could use the router-module instead of the default pages FS router in your case.
https://github.com/nuxt-community/router-module
