### ISSUE TITLE
`useFetch` cannot fetch files from `public` folder during SSR

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#15742]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxtframeworkdiscussions8358discussioncomment-4273658?file=pages%2Findex.vue,public%2Fdata.json

### Describe the bug

When trying to fetch files from public, e.g. `/my-data.json`, `useFetch` will throw a 404 on server-side but will work fine on client-side.

Example: `useFetch('/my-data.json')`

Expected: It should find the file during SSR already.

### Additional context

**Workaround**: Use the full domain. `useFetch('http://localhost:3000/my-data.json')` works.

**Comment by gllinzbk1** [comment]
> How to workaround it for prerendering (npm run generate) in local development environment?
> 
> For example you have nuxt3 project with page that is fetching data: const { data } = await useFetch('/data.json');
> 
> Try to run **npm run generate** and you will get null in data. What should be full domain address? (http://localhost:3000/data.json is not working as well)

Have you solved this problem?

**Comment by gabrielstuff** [comment]
hey there ! 
It would be great to have this feature. It’s useful for many use cases, especially prototyping or static content like data visualization for instance.

Would it be possible to prioritize it?

@TheAlexLichter, would PR be welcome for this proposal/issue?

Thanks!

**Comment by TheAlexLichter** [comment]
@gabrielstuff This is now tracked in https://github.com/nuxt/nuxt/issues/13857

PR welcome, yes!
