### ISSUE TITLE
useFetch automatic request after first request

### ISSUE THREAD

**Issue by maximilian-schwarz** [nuxt/nuxt.js#15741]

**Comment by mbadr2200** [comment]
use can also add watch option and give it false like this 

```
 const { data, error } = await useFetch('/api/Transactions/sell', {
      method: 'POST',
      body: sellTransaction,
      watch: false
    })
```

**Comment by daviprm** [comment]
> You can also add watch option and give it false like this
> 
> ```
>  const { data, error } = await useFetch('/api/Transactions/sell', {
>       method: 'POST',
>       body: sellTransaction,
>       watch: false
>     })
> ```

great!!! 😁

**Comment by changzhong** [comment]
const fetchBody = reactive({ foo: bar })
useFetch('some/url', { method: 'POST', body: { ...fetchBody }})
