### ISSUE TITLE
Unable to get started with tailwind css - Cannot destructure property 'nuxt' of 'this' as it is undefined

### ISSUE THREAD

**Issue by prabhatsharma** [nuxt/nuxt.js#15762]

**Comment by JoshFransix** [comment]
I'm using nuxt 2 currently and still experiencing the same issue as above, any fix for this?

**Comment by git-e-001** [comment]
i am fetching same problem in nuxt 2 project
![Screenshot from 2023-02-12 21-15-16](https://user-images.githubusercontent.com/78661753/218319560-75ad745f-6fcc-48ea-aa79-9fa2b1d41e5b.png)

**Comment by allanlewis** [comment]
FWIW I have a temporary solution for this problem in my Nuxt 2 project: pinning `@nuxt/kit` to `3.0.0-rc.12`.

**Comment by ojabar** [comment]
change @nuxt/kit value to : "@nuxt/kit": "3.0.0-rc.12"
and run: npm i @nuxt/kit

**Comment by ojabar** [comment]
change @nuxt/kit value to : "@nuxt/kit": "3.0.0-rc.12"
and run: npm i @nuxt/kit
