### ISSUE TITLE
Vuex store nested modules API proposal

### ISSUE THREAD

**Issue by rlindskog** [nuxt/nuxt.js#1576]
Is it possible to replicate the `pages` nested directory structure for the `store` and nested modules?

What I mean is something like:

    store/
      index.js
      user/
        index.js
        profile/
          index.js
          articles.js

vs what is currently

    store/
      index.js
      user.js
      user/
        profile.js
        profile/
          articles.js

Just feels more "nuxt" like to me.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1406">#c1406</a>)</em></sub></div>

**Comment by galvez** [comment]
@Atinux @clarkdo @manniL think this is closable by now.

**Comment by manniL** [comment]
As @galvez, this already works out of the box in [`modules mode`](https://nuxtjs.org/guide/vuex-store#modules-mode).
