### ISSUE TITLE
Unable to serve static files after build

### ISSUE THREAD

**Issue by joni1802** [nuxt/nuxt.js#15779]

**Comment by fahmifitu** [comment]
> > Is there any way to serve static files in producation without using an external solution? I have an app where users can upload files to the server.
> 
> you can use https://github.com/unjs/unstorage/ together with Nitro to make that work ☺️

Thanks for your suggestion. Any outline on how to apply this method?

**Comment by miclgael** [comment]
> This solution didn't work for me

Hi @fahmifitu, how did you go? I got this to work by changing to `const base = "./data"` and made sure there's a data folder in the root of the project with some files inside.

**Comment by Ray0907** [comment]
@danielroe  I've faced a similar problem as well. In my scenario, I wanted to create a symbolic link to the upload folder that points to a physical path. I verified that the path was correct, but when I accessed the URL, it resulted in a 404 page error. For example, the URL "http://test.123/uploads/test.text" would lead to the 404 page.

**Comment by fahmifitu** [comment]
> ah yes, you can't add content to `.output/public` after build (and serve the content with your nitro server). We perform a lot of optimisations to make the server efficient, and one of them is only serving content that was present before the build.



> 

That sounds great! It's important to keep optimizing the content that's already there before the build. But it would be really helpful if we could also support serving content that's added after the build, even if it doesn't have any optimizations. Maybe we could even make it optional, so users can choose whether they want optimizations for post-built content or not. This way, we can offer more flexibility and cater to different needs and preferences.

**Comment by fahmifitu** [comment]
> > This solution didn't work for me
> 
> Hi @fahmifitu, how did you go? ~I got this to work by changing to `const base = "./data"` and made sure there's a data folder in the root of the project with some files inside.~
> 
> Edit: stopped working after deployment 😢

Same 

> > This solution didn't work for me
> 
> Hi @fahmifitu, how did you go? ~I got this to work by changing to `const base = "./data"` and made sure there's a data folder in the root of the project with some files inside.~
> 
> Edit: stopped working after deployment 😢

@miclgael I spent hours browsing through nuxt, nitro and unstorage docs and trying multiple solutions with no luck. decided to go completly static build with (ssr: false). simple directory webserver. frontend browser fetch to a json file.

**Comment by dickout** [comment]
> I also encountered a variety of problems, the framework is really not suitable for production environments. For your problem, I solved it with the configuration of nginx:
> 
> ```
>     location /upload {
>         alias /www/xxxx/upload;
>     }
> ```

Great idea, thank you!

**Comment by ReaganM02** [comment]
fs from node won't work in production

**Comment by papoola** [comment]
This is how I got it working for my docker volume using [catch all route](https://nuxt.com/docs/guide/directory-structure/pages#catch-all-route)

`/server/routes/audio/[...slug].js`

```js
import path from 'path'
import fs from 'fs'

export const dirs = {
    public: process.cwd() + '/public'
}

export default defineEventHandler(async (event) => {
    const file = path.resolve(`${dirs.public}/volumes/audio`, event.context.params.slug)
    const stat = fs.statSync(file);
    event.res.writeHead(200, {
        'Content-Length': stat.size,
        'Content-Type': 'audio/mpeg',
    })
    console.log('accessing', file)
    return sendStream(event, fs.createReadStream(file))
});
```

Only issue is that byte range does not work (yet) - but [this article is very helpful](https://medium.com/@hongthaipro/building-a-video-streaming-app-with-nuxt-js-node-and-express-f9611a32d764)

**Comment by manniL** [comment]
Linking https://github.com/nuxt/nuxt/issues/19263 to track ☺️

**Comment by frank2899** [comment]
Here's how I fixed mine:

This is how I upload my image:

`
export const saveFormImageFile = async (file: MultiPartData) => {
    const [_mime, ext] = String(file.type).split('/')
    const filename = `${randomUUID()}.${ext}`

    const filePath = `uploads/${filename}`

    await fs.writeFileSync(filePath, file.data)

    return filename
}

`

Here's how I retrieve the image:

`
import fs from 'fs'
import path from 'path'

export default defineEventHandler(async (event) => {
    const filename = event.context.params?.filename

    try {
        if (!filename) throw 'missing filename path params'

        const filePath = path.join(process.cwd(), 'uploads', filename)

        const fileData = await fs.promises.readFile(filePath)

        return fileData
    } catch (error) {
        return null
    }
})
`

**Comment by yudhiezk** [comment]
> Thanks for the suggestion. I have went with a different solution by just creating a data folder where I am uploading all the files to and added the following route to serve them:
> 
> ```js
> // /server/routes/file/[name].get.js
> import fs from "fs";
> 
> export default defineEventHandler(async (event) => {
>   const base = "data";
>   const filePath = path.join(base, event.context.params.name);
> 
>   return sendStream(event, fs.createReadStream(filePath));
> });
> ```
> 
> So I am able to access an image over `http://localhost:3000/file/logo.png`.



> Thanks for the suggestion. I have went with a different solution by just creating a data folder where I am uploading all the files to and added the following route to serve them:
> 
> ```js
> // /server/routes/file/[name].get.js
> import fs from "fs";
> 
> export default defineEventHandler(async (event) => {
>   const base = "data";
>   const filePath = path.join(base, event.context.params.name);
> 
>   return sendStream(event, fs.createReadStream(filePath));
> });
> ```
> 
> So I am able to access an image over `http://localhost:3000/file/logo.png`.

Hi @joni1802 , can you confirm my steps? Coz somehow this doesn't work for me.
So my step was I create "data" folder in ./output, and create the above code in /server. I manually add jpeg file in data folder. But when I acces it i got 500 ENOENT: no such file or directory, open 'data/download.jpeg'

**Comment by IcyFoxe** [comment]
> ah yes, you can't add content to `.output/public` after build (and serve the content with your nitro server). We perform a lot of optimisations to make the server efficient, and one of them is only serving content that was present before the build.

After going through this discussion, I feel like there should be a way to disable those optimizations, and plainly serve the public files based on the request, no? Why is there no such option?

> > Is there any way to serve static files in producation without using an external solution? I have an app where users can upload files to the server.
> 
> you can use https://github.com/unjs/unstorage/ together with Nitro to make that work ☺️

I've checked the unstorage briefly and it seems to be focused more on storing values as strings (just like localstorage). Working with binary files is still very much an experimental feature and documentation is pretty brief on the subject.

**Comment by IqroNegoro** [comment]
any update to serve the public/images folder easily guys?

**Comment by oom-** [comment]
I think this is honestly stupid.

If everybody expect it to works that way, it should works that way. 

Why there is no out of the box solution for Nuxt to serve static file? I mean come on. 
NuxtImg is not a nice alternative. Tried to serve a gallery with it. Resulted in 429 too many request.

Why Nuxt doesn't allow at least some place, like public/static or anywhere else to just serve dynamic static files, like any other frameworks / servers in the world. 

I love Nuxt but for a famous Framework, there is still so much "basics" that are missing to make it more widely adopted.

From the top of my head, Nuxt should implement out of the box and in a simple way : 
- auth options including:  session management : stateless / statefull
- static files distribution
- better route management (per route middleware are really not instinctive)
- better route inferred types access
- better route protections (middleware on access)
- possibility to split routers send to client to split parts of the app (can be done with building twice the app)
- possibility to add workers that can start in another process (worker with basic cron, like 99% of the web app will require)
- the directory structure that is pretty chaotic (nuxt 4 will really help with that) 
- the possibility to easy start some code pre-startup
- the possibility to add scripts / functions that can be run manually after deployment
- still some issue with TS but this is the same for every framework out there
- open api generation based on zod schema + routes
- better zod / schema sharing between API and front 

I really think that if all of these would be fix/added, Nuxt would be the most incredible and fast out of the box framework out there.

**Comment by Pentadome** [comment]
Really surprised that I cant view my VERSION.txt file I added to the public folder. How it works now is very unintuitive

**Comment by OrbisK** [comment]
> Really surprised that I cant view my VERSION.txt file I added to the public folder. How it works now is very unintuitive

https://nuxt.com/docs/guide/directory-structure/public It is documented here 😄

**Comment by Pentadome** [comment]
> > Really surprised that I cant view my VERSION.txt file I added to the public folder. How it works now is very unintuitive
> 
> https://nuxt.com/docs/guide/directory-structure/public It is documented here 😄

it's not?

**Comment by OrbisK** [comment]
@Pentadome sorry, I have read "can".

**Comment by Flo0806** [comment]
For all users they wanna have a clean solution, here is one. We use *useStorage*:

**nuxt.config.ts**
```
 nitro: {
    storage: {
      pictures: {
        driver: 'fs',
        base: './uploads', // or absolute path
      },
    },
  },
```

**[token].post.ts (Your server upload post)**
```
import { defineEventHandler, readMultipartFormData, createError } from 'h3';
import { useDb } from '../../utils/db';
import { extname } from 'node:path';
import { randomUUID } from 'node:crypto';

export default defineEventHandler(async (event) => {
  const token = event.context.params?.token;
  if (!token || typeof token !== 'string') {
    throw createError({ statusCode: 400, statusMessage: 'Missing token' });
  }

  const db = useDb();
  const guest = db.prepare('SELECT * FROM rsvps WHERE token = ?').get(token) as any;
  if (!guest) {
    throw createError({ statusCode: 403, statusMessage: 'Invalid token' });
  }

  const files = await readMultipartFormData(event);
  if (!files?.length) {
    throw createError({ statusCode: 400, statusMessage: 'No files uploaded' });
  }

  const allowed = ['.jpg', '.jpeg', '.png'];
  const maxSize = 8 * 1024 * 1024; // 8 MB

  const storage = useStorage('pictures'); // ← Nitro/Unstorage

  for (const file of files) {
    if (!file.filename || !file.data) continue;

    const ext = extname(file.filename).toLowerCase();
    if (!allowed.includes(ext)) {
      throw createError({ statusCode: 400, statusMessage: 'Invalid file type' });
    }

    if (file.data.length > maxSize) {
      throw createError({ statusCode: 413, statusMessage: 'File too large' });
    }

    const uniqueName = `${Date.now()}-${randomUUID()}${ext}`;
    const key = uniqueName;

    await storage.setItemRaw(key, file.data); 

    db.prepare('INSERT INTO images (guest_id, filename) VALUES (?, ?)').run(guest.id, uniqueName);
  }

  return { success: true };
});

```
*Last but not least, create a server **route** (e.g. server/routes/pictures/[...path].ts*
Important: the name of the route/path must match the storage name, here "pictures"
```
// (we use the routes folder just so the path doesn't include `/api` which feels cleaner)

export default defineEventHandler(async (event) => {
  const storage = useStorage('pictures');
  const path = await getRouterParam(event, 'path');

  // you could also put in logic here
  // to restrict access to the file based on
  // the user, file type, or any other criteria
  // but this implementation makes the file public
  if (!path) {
    throw createError({
      statusCode: 400,
      statusMessage: 'Path is required',
    });
  }

  return await storage.getItemRaw(path);
});
```

Then your backend will save images in the uploads folder located in the project's root. You can access the image via the route **yourDomain.com/pictures/xxx.jpg**.

✅ When building the project, everything will work perfectly.
✅ Docker will work as well.

**Comment by tantalate** [comment]
> I think this is honestly stupid.
> 
> If everybody expect it to works that way, it should works that way.
> 
> Why there is no out of the box solution for Nuxt to serve static file? I mean come on. NuxtImg is not a nice alternative. Tried to serve a gallery with it. Resulted in 429 too many request.
> 
> Why Nuxt doesn't allow at least some place, like public/static or anywhere else to just serve dynamic static files, like any other frameworks / servers in the world.
> 
> I love Nuxt but for a famous Framework, there is still so much "basics" that are missing to make it more widely adopted.
> 
> From the top of my head, Nuxt should implement out of the box and in a simple way :
> 
> * auth options including:  session management : stateless / statefull
> * static files distribution
> * better route management (per route middleware are really not instinctive)
> * better route inferred types access
> * better route protections (middleware on access)
> * possibility to split routers send to client to split parts of the app (can be done with building twice the app)
> * possibility to add workers that can start in another process (worker with basic cron, like 99% of the web app will require)
> * the directory structure that is pretty chaotic (nuxt 4 will really help with that)
> * the possibility to easy start some code pre-startup
> * the possibility to add scripts / functions that can be run manually after deployment
> * still some issue with TS but this is the same for every framework out there
> * open api generation based on zod schema + routes
> * better zod / schema sharing between API and front
> 
> I really think that if all of these would be fix/added, Nuxt would be the most incredible and fast out of the box framework out there.

The most stupid thing is that this behavior was never mentioned in the document. From the document, the files in the public folder SHOULD be accessed.

`Files contained within the public/ directory are served at the root and are not modified by the build process.`

**Comment by Flo0806** [comment]
Since I myself encountered this issue and needed some time to find a solution or understand the behavior, I will submit a PR to supplement the documentation, including the example.

**Comment by Ray0907** [comment]
I created a module to solve this: [nuxt-local-assets](https://github.com/Ray0907/nuxt-local-assets)

  It serves files at runtime from external directories (not bundled at build time).
