### ISSUE TITLE
 ERROR  [commonjs--resolver]

### ISSUE THREAD

**Issue by Createitv** [nuxt/nuxt.js#15783]

**Comment by amarjeet** [comment]
My issue was resolved after I removed this import from a `*.vue` file:

`import { definePageMeta } from 'nuxt/dist/pages/runtime'`

I took the IDEs suggestion and added the same. But with this import, I get the error.

**Comment by jasmine-my** [comment]
For me, it's the same issue as @amarjeet's. 
So I simply deleted that import line, and then it was fixed.
