### ISSUE TITLE
Hydration node mismatch when Router Middleware redirect in process.client

### ISSUE THREAD

**Issue by TutorFx** [nuxt/nuxt.js#15798]

**Comment by rizqirizqi** [comment]
Hi, sorry I wanna ask, I know it's expected, but in my case, I have an API that can only be fetched from client side, and I need to redirect based on the API response, so it only can be run on client side, what can I do?

I waste my entire day trying to fix this, but still can't find any solution, any answer it would be a great help. Thanks!

**Comment by TutorFx** [comment]
From my understanding, I made a mistake, because nuxt needs to do this on both the server and the client side. so if you need to pass the cookies in the request it's simple:

```ts
const request = await $fetch("my-awesome-endpoint", { headers: useRequestHeaders() })
```

**Comment by ExEr7um** [comment]
> Hi, sorry I wanna ask, I know it's expected, but in my case, I have an API that can only be fetched from client side, and I need to redirect based on the API response, so it only can be run on client side, what can I do?
> 
> I waste my entire day trying to fix this, but still can't find any solution, any answer it would be a great help. Thanks!

If you can fetch data only on client side, then you need to run middleware on client side too, so you need to make your component/page client-only.

But it is a bad way to solve the problem. Right way is to make fetch on the server. Why can't you do it?
