### ISSUE TITLE
When in hash mode, an error occurred on the non-home page refresh

### ISSUE THREAD

**Issue by yoyo837** [nuxt/nuxt.js#1579]
template: nuxt/koa
In nuxt.config.js，router use 'hash', 

env：dev
env: prod is work fine.

1.Open home page;
2.Click 'About page' link to about page;
3.Refresh about page, it report:

**vue.runtime.esm.js:475 [Vue warn]: Property or method "name" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.**

**Comment by yoyo837** [comment]
If add code:
```javascript
data() {
    return {
      name: '' // define 'name'
    }
  }
```
It report error:

 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by Atinux** [comment]
Please report it on https://github.com/nuxt-community/koa-template/issues with a reproduction repo please.

**Comment by poloop** [comment]
I have the same problem with template nuxt/express, fallback 'hash' (for ie9).
When I test my project on ie9 and refresh not landing page, I got :

**[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.** 

Is there any solution to fix it ?

**Comment by yoyo837** [comment]
@poloop 
Hmmm, should i reopen this question?

The problem is gone after i change to the history mode. I don't know what the reason is.

**Comment by poloop** [comment]
@yoyo837 Probably, yes.

My issue is specific to IE9, everything works fine on modern browser.

**Comment by ouyangxiaoai** [comment]
@yoyo837 @Atinux @poloop so, should i solve this problem?

**Comment by submjn** [comment]
This one (https://tylermcginnis.com/react-router-cannot-get-url-refresh/) helped me to resolve my issue. My vuejs application is giving me the issue, when I refresh the page, it gives me 500 error. I have added .htaccess file in my root folder and it worked.

Apache Server:

RewriteBase /
RewriteRule ^index\.html$ - [L]
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
