### ISSUE TITLE
Dynamic nested routes with parent url.

### ISSUE THREAD

**Issue by sainf** [nuxt/nuxt.js#158]
Hi.

I'm trying to use a dynamic nested router:
![image](https://cloud.githubusercontent.com/assets/1210947/22212259/dfb24b9e-e187-11e6-9ac1-b1f36d6f3fea.png)

![image](https://cloud.githubusercontent.com/assets/1210947/22212240/cecb8304-e187-11e6-83b0-13529f9996de.png)

But the link loads the parent _cat.vue and not the _slug.vue

But using without the parent url (/cadeiras) it works fine
![image](https://cloud.githubusercontent.com/assets/1210947/22212334/35b63ffa-e188-11e6-899d-a182ede83bfc.png)

![image](https://cloud.githubusercontent.com/assets/1210947/22212404/7d83023c-e188-11e6-86cd-d5c35b4f3da0.png)

It loads the correct _cat/_slug.vue

**Comment by alexchopin** [comment]
Hi, 
Have you include the `<nuxt-child/>`component inside your _cat.vue file?

**Comment by sainf** [comment]
Puting `<nuxt-child/>` in _cat.vue it only render the child in the _cat.vue.
I renamed the folder and now I have the intended effect.
\(static)\dynamic\dynamic

![image](https://cloud.githubusercontent.com/assets/1210947/22226852/1d2e3ce8-e1c0-11e6-9762-8adda8333ecb.png)

But I only have the last param in the route object.

**Comment by alexchopin** [comment]
I need more explanation about what do you expect to help you:
- Routes expected
- Which file is parent or child

**Comment by sainf** [comment]
Hi.

Never mind, it works as expected, sorry to disturb.

Thanks for this great framework.
