### ISSUE TITLE
Application is inaccessible from the browser when deployed to amazon

### ISSUE THREAD

**Issue by nirvanagit** [nuxt/nuxt.js#1581]
I am running a nuxt application on amazon ec2 using amazon linux image. I run the application by `cross-env NODE_ENV=production node build/main.js`. 

It is accessible from the same host when I run `curl localhost:3000`

But when I use my browser it does not connect. Something is wrong with the server. I created  a simple nodejs server and ran it on port 3000 which works fine, which means its not a port issue.

**Comment by pi0** [comment]
Hi. Would you please set environment variable `HOST` to `0.0.0.0` ? (Or just running with `nuxt start --host 0.0.0.0`) So it can be accessible from outside

**Comment by homerjam** [comment]
Pretty sure this was resolved via gitter
