### ISSUE TITLE
CSS Minify

### ISSUE THREAD

**Issue by raisiqueira** [nuxt/nuxt.js#1583]
How do I not minify css in build for production? Example for bootstrap-vue

**Comment by homerjam** [comment]
Include css in head?

**Comment by raisiqueira** [comment]
I'm using the @nuxtjs/bootstrap-vue module.

**Comment by pi0** [comment]
@raisiqueira Would you please explain more on your usage? Does minification make any unwanted behavior?

**Comment by raisiqueira** [comment]
@pi0 Ya! 

that's my code off the component:
```
    <b-form-row>
    <b-form @submit="onSubmit">

          <b-form-group id="Group1"
                        label="Email:" label-for="Input1"
                        description="Digite um e-mail válido para podermos entrar em contato.">
            <b-form-input id="Input1"
                          type="email" v-model="form.email" required
                          placeholder="Digite seu email"
            ></b-form-input>
          </b-form-group>

          <b-form-group id="Group2"
                        label="Seu nome:" label-for="Input2">
            <b-form-input id="Input2"
                          type="text" v-model="form.name" required
                          placeholder="Digite seu nome"
            ></b-form-input>
          </b-form-group>

          <b-form-group id="Group3"
                        label="Setor:" label-for="Input3">
            <b-form-select id="Input3"
                          :options="setores" required
                          v-model="form.setor"
            ></b-form-select>
          </b-form-group>

          <b-form-group id="Group4"
                        label="Mensagem:" label-for="textArea1">
            <b-form-textarea v-model="form.mensagem" required>
            </b-form-textarea id="textArea1">
          </b-form-group>

          <b-button-group>
          <b-button type="submit" variant="primary">Enviar</b-button>
          <b-button type="reset" variant="secondary">Resetar</b-button>
          </b-button-group>

        </b-form>
    </b-form-row>
```
I'm running local (nuxt command) works fine!
![captura de tela 2017-09-05 as 16 48 13](https://user-images.githubusercontent.com/2914170/30080619-96c42356-925a-11e7-9d64-748261820873.png)

but in production the form looks like this:
![captura de tela 2017-09-05 as 16 56 22](https://user-images.githubusercontent.com/2914170/30080762-2ae72d6c-925b-11e7-9226-ba16475ff27b.png)

**Comment by homerjam** [comment]
It looks like there's some elements missing - are they present in the Dom, can you inspect them? Are there any errors in console?

**Comment by raisiqueira** [comment]
that's the HTML:
```html
<b-form-row><form class=""><b-form-group id="Group1" label="Email:" label-for="Input1" description="Digite um e-mail válido para podermos entrar em contato."><input type="email" id="Input1" rows="1" placeholder="Digite seu email" class="form-control" required="required"></b-form-group><b-form-group id="Group2" label="Seu nome:" label-for="Input2"><input type="text" id="Input2" rows="1" placeholder="Digite seu nome" class="form-control" required="required"></b-form-group><b-form-group id="Group3" label="Setor:" label-for="Input3"><select id="Input3" class="custom-select" required="required"><option value="">Selecione o setor</option><option value="Carrots">Carrots</option><option value="Beans">Beans</option><option value="Tomatoes">Tomatoes</option><option value="Corn">Corn</option></select></b-form-group><b-form-group id="Group4" label="Mensagem:" label-for="textArea1"><b-form-textarea required="required"></b-form-textarea></b-form-group><div class="btn-group"><button class="btn btn-primary" type="submit">Enviar</button><button class="btn btn-secondary" type="reset">Resetar</button></div></form></b-form-row>
```

**Comment by homerjam** [comment]
Ok so the label elements are missing - this is not a css issue.

**Comment by raisiqueira** [comment]
@homerjam Ya. In the local (dev) works fine, but i'm running `nuxt build` and `nuxt start` on the production server, the css(or this component) return this bug in forms.

PS > the first image is a print of the my local dev.
PS2 > the second image is a print of the production server.

looks => https://github.com/nuxt/nuxt.js/issues/1583#issuecomment-327285489

**Comment by homerjam** [comment]
I suggest you close this issue and create one in `@nuxtjs/bootstrap-vue`, or at least edit this one. It really doesn't look like a css issue to me - perhaps there are some clues in the build log, or even the console in dev.

**Comment by raisiqueira** [comment]
In the console don't return any error.

issue in bootstrap-vue module repository: https://github.com/nuxt-community/modules/issues/135

**Comment by iamvdo** [comment]
Is there a solution to not minify CSS?

I have a special use case where I want to show some CSS code inside HTML page, but `nuxt generate` minifies it. It does work as expected in dev.
