### ISSUE TITLE
Be able to change the default nuxt webpack config

### ISSUE THREAD

**Issue by vanoorschot** [nuxt/nuxt.js#1584]
I want to extend the webpack config with the svg-sprite-loader, which looks like:
https://github.com/kisenka/svg-sprite-loader/blob/master/examples/browser-sprite/webpack.config.js

This conflicts with the url loader in Nuxt:
```
// https://nuxtjs.org/guide/assets/#webpacked
{
  test: /\.(png|jpe?g|gif|svg)$/,
  loader: 'url-loader',
  query: {
    limit: 1000, // 1KO
    name: 'img/[name].[hash:7].[ext]'
  }
}
```
I get a _svg-sprite-loader exception. 2 rules applies to_ warning and was able to fix it by removing the rule and re-add it with an exclude property:
```
extend(config, { dev, isClient }) {
  /**
   * Initialise SVG Sprites
   */

  // get and remove file loader
  const rule = config.module.rules.find(r => r.test.toString() === '/\\.(png|jpe?g|gif|svg)$/');
  config.module.rules.splice(config.module.rules.indexOf(rule), 1);

  // add it again, but now without 'assets\/svg'
  config.module.rules.push({
    test: /\.(png|jpe?g|gif|svg)$/,
    loader: 'url-loader',
    exclude: /(assets\/svg)/,
    query: {
      limit: 1000, // 1KO
      name: 'img/[name].[hash:7].[ext]',
    },
  });

  config.module.rules.push({
    test: /\.svg$/,
    include: [
      path.resolve(__dirname, 'assets/svg'),
    ],
    use: 'svg-sprite-loader',
  });
},
```

This feels like a dirty hack, but it was the only way to get it working. 
Could you add some support to be able to change the default nuxt webpack config or tell me how I could have done it otherwise?

**Comment by michaelpumo** [comment]
Hack worked for me. Thanks! Would rather not be hacking though.

Has there since been a way to do this the _proper way_?

**Comment by unwrittenmike** [comment]
Any idea how to get it working when using nuxt generate?

This works great when running in dev mode but when I run nuxt generate the svg sprite is missing from the dom.

**Comment by kball** [comment]
I did something similar to this hack to send options to the sass-loader (I wanted includePaths to let me pull in some libraries)... I'd be happy to do the work to implement a better approach, but would like guidance on what api would best fit with the nuxt approach.

@alexchopin did you already have thoughts on how you'd like this to look?

Feel free to totally overrule this, but if you didn't already have prior thoughts, one possibility would be to group rule types (images, css, fonts, js, ...) and allow you to explicitly override each of those groups... and then potentially have a "catch all" or "extra" for completely new rules...

so in the example above, your nuxt.config.js would look something like:
```
build: {
  rules: {
    images: [
     {
        test: /\.(png|jpe?g|gif|svg)$/,
        loader: 'url-loader',
        exclude: /(assets\/svg)/,
        query: {
          limit: 1000, // 1KO
          name: 'img/[name].[hash:7].[ext]',
        },
      }, 
      {
        test: /\.svg$/,
        include: [
          path.resolve(__dirname, 'assets/svg'),
        ],
        use: 'svg-sprite-loader',
      }
    ]
  }
}
```

**Comment by pxwee5** [comment]
Thanks @vanoorschot for the hack! Nicely done :)
Not sure what has changed since but with the current RC you can do this which results in much shorter code.

```
build: {
    extend (config, ctx) {
      // Excludes /assets/svg from url-loader
      const urlLoader = config.module.rules.find((rule) => rule.loader === 'url-loader')
      urlLoader.exclude = /(assets\/svg)/

      // Includes /assets/svg for svg-sprite-loader
      config.module.rules.push({
        test: /\.svg$/,
        include: [
          path.resolve(__dirname, 'assets/svg')
        ],
        use: 'svg-sprite-loader'
      })

      // Uncomment line below to view webpack rules
      // console.dir(config.module.rules)
    }
  },
}
```

You still have to import the svg in your components so that it can be injected into `document.body`.

**Comment by vinjegaard** [comment]
Is this still working for you in RC11? I get "ReferenceError: path is not defined" when i try this.
