### ISSUE TITLE
ability to show warnings

### ISSUE THREAD

**Issue by Ellomend** [nuxt/nuxt.js#1585]
is it possible not only errors but warnings too in overlay ?

**Comment by alexchopin** [comment]
Can you explain more?

**Comment by Ellomend** [comment]
if ia have mistake in JS code ESlint error will appear at overlay in browser,
but if i have warning (from postcss for example) it will be only in console, is there a way to display warnings in browser too ?

**Comment by pi0** [comment]
@Ellomend This is a feature of [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware#config) And unfortunately seems their support for current overlay customization is much limited so we can't do anything here.
