### ISSUE TITLE
after click nuxt-link ,route doesn't change.

### ISSUE THREAD

**Issue by 443866786** [nuxt/nuxt.js#1587]
for example , now i am at localhost:3000 ,when i click an a tag (generate by nuxt-link) to localhost:3000/benefits/security ,the route is  sitll at localhost:3000

**Comment by NicoPennec** [comment]
which version of Nuxt ?
and please share your source code of index.vue

**Comment by koalaqinqin** [comment]
I met the same problem, and jump directly the page 500. i want to know what happened before entering `nuxt-render.js`

**Comment by venugopalsundaram** [comment]
@koalaqinqin  I faced the same issue,but it is due to the logic error in asyncData method.In my case I called a service in asyncData , while it throws error in catch block it redirects to 500
