### ISSUE TITLE
List of siblingPages, parentPage, etc

### ISSUE THREAD

**Issue by buhrmi** [nuxt/nuxt.js#1589]
Hello,

it would be nice if nuxt could somehow expose the list of available siblingPages, parentPages, nextPage, prevPage to make it easy to build a navigation or a breadcrumb based on the pages directory. Since nuxt is walking through the pages directory anyway, I don't think it will add much overhead (if any) to expose this information somewhere, possibly on the router object.

Proposal:
  
    Next Page: <nuxt-link :to="$router.nextPage.path">{{ $router.nextPage.name }}</nuxt-link>

Cheers,
Stefan

**Comment by homerjam** [comment]
This assumes your pages are always in alphabetical order though right?

**Comment by buhrmi** [comment]
Yes. Or prefixed with a number.

**Comment by buhrmi** [comment]
Probably not very useful feature

**Comment by homerjam** [comment]
I think this functionality would better suit a plugin/module as it seems a bit of an edge case, but agreed it's probably fairly trivial to add.
