### ISSUE TITLE
Named Routes

### ISSUE THREAD

**Issue by francescobm** [nuxt/nuxt.js#1595]
For my i18n I want to change dynamically the path name of my route, but have the same component associated to it. 
For instance:

pages
  about-us.vue

```
// overwrite or extend the routes automatically generated by nuxt
import paths from 'paths'

const lang = $store.lang
const aboutUsPath = paths[lang].about

const router = new VueRouter({
  routes: [
    {
      path: aboutUsPath, // it changes according to the country code
      name: 'about-us',
      component: AboutUs
    }
  ]
})
```
and then I use nuxt linkto as follow:

```
<nuxt-link :to="{ name: 'about-us' }> {{ content.navigation.about }} </nuxt-link>
```

With the current implementation I have to create under pages many files:
pages
  about-us.vue
  chi-siamo.vue
  quienes-somos.vue
  qui-sommes-nous.vue

and then in each of them import the same component, where I load dynamically the localised content. Not very elegant solution.

How can I access nuxt routes and customize them as I want?

**Comment by epartipilo** [comment]
Hi @francescobm !

Try this way, I generated the router over Nuxt then I made aliases for each route.
In the vue-router you'll find documentation for aliases on router.

This is commented over here in issue #508 

Good luck!

**Comment by francescobm** [comment]
@epartipilo thanks a lot ! 
This solve part of my issue, the biggest part :-). 

Now with the use of modules I can replace the router and create aliases for a page in different languages. 

Only remaining problem is now to not make accessible routes that are not relevant for a country.
For instance: 
block ```/quienes-somos``` if I am on ```.com```, and block ```/about-us``` when I am on .es, and so on.

I think I will use a middleware for it. Thanks !

**Comment by alexchopin** [comment]
Hi,
[Validate](https://nuxtjs.org/api/pages-validate) method or [Middleware](https://nuxtjs.org/api/pages-middleware) are good solutions.

**Comment by epartipilo** [comment]
Hi @alexchopin 

I like your suggestion on Validate or Middleware, it's more clean and a better Nuxt way but, using Validate method or Middleware does't not make more unnecessary redirections than the router Aliases? 

Also the checking the url by language is a little bit more tricky.

Thanks!
