### ISSUE TITLE
@import default style from package results in TypeError

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#1597]
Seems like Package.json "style" Attribute is not supported here. I tried to follow the advise given below
https://jaketrent.com/post/package-json-style-attribute/

In style area i try
```
<style>
@import "orgchart";
</style>
```
I get this error
`TypeError: Path must be a string. Received [ './dist/css/jquery.orgchart.css' ]`

Seems like something wrapping the value in array

**Comment by alexchopin** [comment]
https://github.com/nuxt/nuxt.js/issues/1453
