### ISSUE TITLE
Browser compatibility on Android 6.0 build-in browser

### ISSUE THREAD

**Issue by wuyongzhi** [nuxt/nuxt.js#1599]
Use android 6.0 build-in Browser, run examples/vuex-store-modules

The button in example can NOT be clicked

The browser output a error:

> 09-07 08:30:25.107  2912  2912 E browser : Console: Uncaught TypeError: filenames.find is not a function http://192.168.0.102:3000/_nuxt/nuxt.bundle.6090fac5842dbbea9c6a.js:1774

Full output:
>09-07 08:30:25.107  2912  2912 E browser : Console: Uncaught TypeError: filenames.find is not a function http://192.168.0.102:3000/_nuxt/nuxt.bundle.6090fac5842dbbea9c6a.js:1774
09-07 08:30:25.148  2912  2912 I browser : Console: Download the Vue Devtools extension for a better development experience:
09-07 08:30:25.148  2912  2912 I browser : https://github.com/vuejs/vue-devtools http://192.168.0.102:3000/_nuxt/vendor.bundle.601df7a36ddb46c8dab5.js:7122
09-07 08:30:25.149  2912  2912 I browser : Console: You are running Vue in development mode.
09-07 08:30:25.149  2912  2912 I browser : Make sure to turn on production mode when deploying for production.
09-07 08:30:25.149  2912  2912 I browser : See more tips at https://vuejs.org/guide/deployment.html http://192.168.0.102:3000/_nuxt/vendor.bundle.601df7a36ddb46c8dab5.js:7132
09-07 08:30:25.230  2912  2912 I browser : Console: [HMR] connected http://192.168.0.102:3000/_nuxt/vendor.bundle.601df7a36ddb46c8dab5.js:13240
wuyongzhideMacBook-Pro:platform-tools wuyongzhi$

i testing it on real phone and emulator, both has issue.

but, i run examples/vuex-store has NOT issue.

**Comment by wuyongzhi** [comment]
When i test in Internet Explorer 10, it has SAME issue

**Comment by NicoPennec** [comment]
try to install `yarn add babel-polyfill` (or with npm `npm i babel-polyfill --save`)

and update your `nuxt.config.js`:
```
  build: {
    vendor: ['babel-polyfill'],
...
```

**Comment by wuyongzhi** [comment]
Thank you! 
It works!
