### ISSUE TITLE
Static image library site

### ISSUE THREAD

**Issue by AlexRadch** [nuxt/nuxt.js#1602]
I want to create static site with image library. Can I scan root folder of image library to read all subfolders and read all images in subfolders? And then can I generate vue code based and image library subfolders and images? All library images would be in `/static/library` folder.

How can I make it on nuxt?

**Comment by alexchopin** [comment]
Hi,
I recommend you to use the [Gitter channel](https://gitter.im/nuxt/nuxt.js) to get help for your project from the community.
As long as it's not really an issue, I'm closing it.
