### ISSUE TITLE
Multiple module with babel-plugin-component: 

### ISSUE THREAD

**Issue by yoyo837** [nuxt/nuxt.js#1603]
#1356 
```javascript
build: {
    babel: {
      plugins: [
        ['component', [{
          libraryName: 'element-ui',
          styleLibraryName: 'theme-default'
        }, {
          libraryName: 'mint-ui',
          style: true
        }]]
      ]
    }
  }
```
However, it does not seem to support multiple module
[babel-plugin-component#multiple-module](https://github.com/qingwei-li/babel-plugin-component#multiple-module)

```javascript
build: {
    babel: {
      plugins: [
        ['component', [{
          libraryName: 'element-ui',
          styleLibraryName: 'theme-default'
        }]]
      ]
    }
  }
```
and
```javascript
build: {
    babel: {
      plugins: [
        ['component', {
          libraryName: 'element-ui',
          styleLibraryName: 'theme-default'
        }]
      ]
    }
  }
```
work fine!

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1429">#c1429</a>)</em></sub></div>

**Comment by yoyo837** [comment]
Old no-nuxt project work fine use this .babelrc file 
```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"],
        "node": true
      }
    }],
    "stage-2"
  ],
  "plugins": [
    "transform-runtime", ["component", [{
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }, {
      "libraryName": "mint-ui",
      "style": true
    }]]
  ],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}

```

**Comment by yuchonghua** [comment]
Look forward to more support
/ping @pimlie @alexchopin

**Comment by Atinux** [comment]
Are you using the last version of Nuxt.js and babel-plugin-component?

**Comment by yoyo837** [comment]
Yes，I' m sure.

**Comment by Atinux** [comment]
Could you create a small reproduction repo so I can see where the problem is?

**Comment by yoyo837** [comment]
There are some upstream new issues that need to be fixed at first.
https://github.com/QingWei-Li/babel-plugin-component/issues/12
https://github.com/QingWei-Li/babel-plugin-component/issues/14

repo: https://github.com/yoyo837/nuxt.js-issues-1603  
branch:  `refactor-ui `
code: `/nuxt.config.js:line 77`

**Comment by yeziZ** [comment]
Look forward to more support

**Comment by yuchonghua** [comment]
Look forward to more support
/ping @pimlie @alexchopin @QingWei-Li @Atinux

**Comment by Huahua-Chen** [comment]
I try this way
```
{
  "plugins": [xxx,
    ["component", {
      libraryName: "antd",
      style: true,
    }, "antd"],
    ["component", {
      libraryName: "test-module",
      style: true,
    }, "test-module"]
  ]
}
```
But it does not seem to support multiple module?
@yoyo837

**Comment by wusiquan** [comment]
依然存在此问题~
