### ISSUE TITLE
Problem with third-party plugins

### ISSUE THREAD

**Issue by Alex-Sokolov** [nuxt/nuxt.js#1605]
After Nuxt 1.0.0-rc4 versions there is problem with third-party plugins.
For example, I use moment.js. That's how I included them

In nuxt.config.js
```js
plugins: [
  //...
  { src: '~/plugins/moment.js' },
  //...
],
build: {
  vendor: [
    //...
    'moment',
    //...
  ],
  plugins: [
    new webpack.ContextReplacementPlugin(/node_modules\\moment\\locale/, /ru/)
  ]
}
```

In `~/plugins/moment.js`:
```js
import moment from 'moment';
moment.locale('ru');
export default moment;
```

App building without errors, but when try to open any page showed error:
![image](https://user-images.githubusercontent.com/4497128/30152250-36d916c4-93bb-11e7-9820-479309b5e85c.png)

**Comment by engelsoc** [comment]
npm install moment --save

**Comment by Alex-Sokolov** [comment]
@engelsoc it's installed. And work with rc4.

**Comment by mahesh29** [comment]
I experienced this issue too.
The console error is not the most helpful, but pasting it anyways:

[nuxt] Error while initializing app TypeError: t.replace is not a function
    at Z (common.912fcaa6357ec2f09fd1.js:2)
    at fe (common.912fcaa6357ec2f09fd1.js:2)
    at ye (common.912fcaa6357ec2f09fd1.js:2)
    at pe (common.912fcaa6357ec2f09fd1.js:2)
    at ge (common.912fcaa6357ec2f09fd1.js:2)
    at Me (common.912fcaa6357ec2f09fd1.js:2)
    at e (common.912fcaa6357ec2f09fd1.js:2)
    at app.4415a9678f7975153d9f.js:1
    at r (common.912fcaa6357ec2f09fd1.js:2)
    at Generator._invoke (common.912fcaa6357ec2f09fd1.js:2)

P.S: This is **rc9**

**Comment by tlgreg** [comment]
I think the issue is that `moment` is exported directly from the plugin.
What is expected from a plugin to export is a function that gets executed with the context passed in.
[Plugins docs.](https://nuxtjs.org/guide/plugins)

**Comment by Alex-Sokolov** [comment]
Workaround. Move all imports itno 1 file for SSR-ready and 1 file for client-only

Before:
`nuxt.config.js`
```js
  plugins: [
    { src: '~/plugins/bootstrap.js', ssr: false },
    { src: '~/plugins/alertify.js', ssr: false },
    { src: '~/plugins/datatables.js', ssr: false },
    { src: '~/plugins/moment.js' },
    { src: '~/plugins/inputmask.js', ssr: false },
    { src: '~/plugins/datatable/dateAsAbbr.js' }
  ],
```

After:
`nuxt.config.js`
```js
  plugins: [
    { src: '~/plugins/client-side-plugins.js', ssr: false },
    { src: '~/plugins/ssr-compatible-plugins.js' }
],
```

This will work on RC11

**Comment by andreliem** [comment]
Having 1 plugin file seems to reduce errors for me as well.

**Comment by Alex-Sokolov** [comment]
@alexchopin why you close issue? This is already fixed?

**Comment by shepard89** [comment]
@Alex-Sokolov You have to export function, try this:
```
import moment from 'moment';
import 'moment/locale/ru';

export default () => {
  moment.locale('ru');
};
```
