### ISSUE TITLE
nuxt generate skips routes with underscores

### ISSUE THREAD

**Issue by DaxChen** [nuxt/nuxt.js#1606]
files like `user_agreement.vue` are not dynamic routes, but not generated

**Comment by alexchopin** [comment]
Should be fixed in the next release.

**Comment by DaxChen** [comment]
@alexchopin still not generating in `nuxt@1.0.0-rc11`

**Comment by samirph** [comment]
For SEO purposes I wanted to keep a page file named sign_in.vue
But it the url it just shows `sign`.
Is there a workround so far?

**Comment by ujjwalguptaofficial** [comment]
I am getting problem in version 2.0.0 too. Its working in development but files are not being generated when using generate.
