### ISSUE TITLE
request for built in analytics

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#161]
Hello, 
I'd like to know how you guys think about built-in analytics like `GA` or similar. Do you recommend using `VueAnalytics` or is there a plan to add it to the roadmap?
Cheers

**Comment by alexchopin** [comment]
Hi,
For using Google Analytics in Nuxt.js we use it as a plugin.
You can see how we use it [on our documentation](https://nuxtjs.org/faq/google-analytics).
