### ISSUE TITLE
Blank Screen with SPA mode and Apollo Module 

### ISSUE THREAD

**Issue by abattenburg** [nuxt/nuxt.js#1610]
When in the regular mode, my app works fine. But when switching to `mode: 'spa'` in the nuxt.config file, the application switches to a blank screen with the loading icon continuously looping. When checking the console, there is an error `Error while initializing app TypeError: Cannot read property 'apollo' of undefined` which makes me think this is related to the **nuxtjs/apollo** module. Example can be seen here: http://synonymous-view.surge.sh/

I'm currently updated to RC 11, and a repo of my code can be found at: https://bitbucket.org/abattenburg/nuxtapolloboilerplate. Trying to use SPA to get persistent state, so any thoughts would be much appreciated!

**Comment by dohomi** [comment]
@abattenburg not sure I only checked your code quickly: you are using SPA mode, which is client-side render. But inside of your apollo queries you are using prefetch: true which is for the usage of server side prefetch. I'm not sure if this is possible - seems you mix 2 approaches at the moment. the network interface should also export a function in the version 2 of nuxjs/apollo module. Maybe move this issue/conversation to the nuxtjs/apollo module. I'd also search in your code for `.apolllo` and see where you make use of it

**Comment by abattenburg** [comment]
@dohomi, thanks for helping me confirm it is an issue with Nuxt/Apollo rather then just Nuxt. I upgraded to Nuxt/Apollo V2 and took out all the prefetching, but still couldn't move forward. 

There is an issue already on Nuxt/Apollo [here](https://github.com/nuxt-community/apollo-module/issues/29) that I missed so this seems to be a duplicate. Thanks for the suggestions and taking a look at it!
