### ISSUE TITLE
Unable to force Nuxt out of dev mode?

### ISSUE THREAD

**Issue by paulstraw** [nuxt/nuxt.js#1611]
Hi there! I tried asking this in the Gitter, but it might actually be more appropriate for here. I'm running into a weird issue upgrading a Nuxt app from 0.10.7 to 1.0.0-rc11 (having the same issue with rc9). Basically, no matter what I do, Nuxt/Vue seem to be stuck in dev mode. I've confirmed that `process.env.NODE_ENV === 'production'`, but still nothing.

Here's how I'm attempting to set dev mode in my nuxt.config.js:

``` javascript
module.exports = {
  dev: !(process.env.NODE_ENV === 'production'),
  // …
}
```

I'm then importing that for my server.js:

``` javascript
let nuxtConfig = require('./nuxt.config.js')
console.log('nuxtConfig dev val:', nuxtConfig.dev) // false
const nuxt = new Nuxt(nuxtConfig)
```

However, when I visit the site after a `nuxt build` and `NODE_ENV=production node server`, I get the Vue "You are running Vue in development mode" message, and Vue dev tools work, etc.

As far as I can tell, I'm doing things as recommended by the examples, so I'm wondering if this is some sort of weird edge case with the RC? This setup was working fine under `0.10.7`. It's also entirely possible I'm just missing something silly. 🙂

Anyhow, I'm happy to provide any information that would be helpful, just let me know whatever you need.

**Comment by homerjam** [comment]
I think the start command has changed, take a look at package.json - it's something like `nuxt start` now

**Comment by paulstraw** [comment]
Hey @homerjam, thanks for the response. In this case, I'm using Nuxt programmatically from a file in my root called `server.js`, similar to the [express-template server](https://github.com/nuxt-community/express-template/blob/master/template/server/index.js).

**Comment by homerjam** [comment]
Ah ok sorry I jumped straight here from gitter and didn't read this properly 😊 

I've got limited experience with that use case I'm afraid!

**Comment by NicoPennec** [comment]
1. install cross-env: `yarn add cross-env -dev` (or `npm install cross-env --save-dev)`

    > https://www.npmjs.com/package/cross-env

2. update your `package.json` with scripts:

```
"scripts": {
  "dev": "node server.js",
  "build": "nuxt build",
  "start": "cross-env NODE_ENV=production node server.js"
}
```
3. run build : `yarn build` (or `npm run build`)

4. run start : `yarn start` (or `npm run start`)

**Comment by paulstraw** [comment]
@NicoPennec maybe I'm missing something, but it looks as if `cross-env` just makes environment variables behave on Windows? Does it have some other side effects I'm not seeing?

**Comment by NicoPennec** [comment]
`cross-env` is not mandatory, but it can help you in some cases ;-)

Can you share your complete `server.js` file?

**Comment by paulstraw** [comment]
After trying to get a fresh reproduction up and running, this definitely seems as if it's something in my old 0.10.7 code causing the issues. I'm attempting to replicate with a fresh 1.0.0 with no luck so far. Going to keep at it for now and update here when I've got some new information.

**Comment by paulstraw** [comment]
Even if I pass `dev: false` in my Nuxt config, I'm still getting dev mode in the browser, so I can confirm this definitely has nothing to do with environment variables. It seems like I'm running into something internal to Nuxt that's forcing its dev mode to stay on, but I'm not sure what that could be yet. Even with the literal `dev: false`, dev mode stays enabled for this project regardless of my NODE_ENV or any other settings as far as I've been able to find so far. Continuing to dig! ¯\_(ツ)_/¯

**Comment by paulstraw** [comment]
@NicoPennec Here are the relevant bits of server.js. This is still giving me dev mode, even with the literal `dev: false` mentioned above. The rest of the file is mostly just Express session and routing stuff, nothing Nuxt-related:

``` javascript
const app = require('express')()
const isDev = process.env.ENV === 'development'
const nuxtConfig = require('./nuxt.config.js')
const nuxt = new Nuxt(nuxtConfig)

if (isDev) {
  const builder = new Builder(nuxt)
  builder.build()
}

app.use(nuxt.render)

app.listen(port, host)
console.log(`Server listening on ${host}:${port}`)
```

**Comment by pi0** [comment]
@paulstraw As you mentioned upgrading from 0.x, I would suggest cleaning up `node_modules`/`.nuxt`/lock files for a fresh setup. Also, how do you check is dev enabled or not?

**Comment by paulstraw** [comment]
Hey @pi0, unfortunately I've cleaned out all the various things with no luck. This is happening on Heroku as well, so it's not isolated to my machine. I can tell that dev is enabled because of the output HTML, but also because I'm getting the "You are running Vue in development mode" in the browser console.

**Comment by pi0** [comment]
That's crazy not working! Almost sure something is changing that `process.env` back to dev more. What if you put this to check what is happening on prod ?

```js
console.log('Process:', process.env.NODE_ENV)
console.log('Nuxt:', nuxt.dev ? 'dev' : 'prod')
app.use(nuxt.render)

app.listen(port, host)
console.log(`Server listening on ${host}:${port}`)
```

**Comment by paulstraw** [comment]
Yeah, that's what I thought, too. I get the same thing even with a literal `dev: true` in my Nuxt config though, so I'm pretty sure it's not related to environment variables. I tossed those exact log lines up on Heroku though, and here's the output:

```
2017-09-08T07:54:08.434900+00:00 app[web.1]: Process: production
2017-09-08T07:54:08.435160+00:00 app[web.1]: Nuxt: prod
```

However, when I browse to the site, I still get "You are running Vue in development mode", and it's still clearly in dev mode based on the HTML output. I'm at a bit of a loss, this is a really weird one!

**Comment by pi0** [comment]
Would you please share a link to your repo? (Or adding pi0 as a collaborator if is private)

**Comment by paulstraw** [comment]
@pi0 it's a private repo that I don't have the full rights to share. I'm going to bed for now, but in the morning I'm going to work on building out a reduced test case in the opposite direction, by removing things from the existing app until I'm able to disable dev mode as expected.

Once I get to that point, I'll update here and can add you as a collaborator with access to that branch if that still makes sense, or just stick the branch up in a public repo or something. Thanks for your help!

**Comment by pi0** [comment]
Ok. Keep me updated :)

**Comment by Atinux** [comment]
Please re-open the issue when you'll have a reproduction repo :)

**Comment by n-sikka** [comment]
@paulstraw  did you manage to figure this out? Any luck.. stuck at this same issue.

**Comment by nghiatv** [comment]
i got same issue. I still get "You are running Vue in development mode". my nuxt version is 1.0.0 (updated at 09/01/2018)

**Comment by nghiatv** [comment]
@n-sikka  did  you have this line in nuxt.config.js:
```
config.resolve.alias['vue'] = 'vue/dist/vue.js'
```
change this to: 
```
config.resolve.alias['vue'] = 'vue/dist/vue.min'
```
its work!
