### ISSUE TITLE
nuxt.js with 404 page,how to custom 404 page?

### ISSUE THREAD

**Issue by XiaoNode** [nuxt/nuxt.js#1614]
like title ,in nuxt.js how to custom 404 page? Instead of the default 404 page

**Comment by NicoPennec** [comment]
https://nuxtjs.org/guide/views/#error-page
> You can customize the error page by adding a layouts/error.vue file.

**Comment by robinhuy** [comment]
We can add custom 404 page and config extendRoutes: https://nuxtjs.org/api/configuration-router
