### ISSUE TITLE
new version nuxt not surpport async component?

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#1615]
I have load editor component async like bellow:
```
...
async created () {
      const editor = await import('~/components/editor.vue')
      Vue.component('editor', editor)
}
...
```

but when I upgrade the nuxt version to `^1.0.0-rc8` ， the editor  component can't load, has some where changed?

the source code is here https://github.com/awesomes-cn/new-awesomes/blob/master/components/comment.vue#L184

**Comment by lukasborawski** [comment]
Why u're not using 'asyncData` ?

**Comment by bimohxh** [comment]
@lukasborawski  I want to  async  load component, not async data

**Comment by Atinux** [comment]
Can you try with `rc11` @bimohxh ?

**Comment by NicoPennec** [comment]
With rc8 & rc9, it works fine in `async mounted () { ... } ` method

**Comment by dts** [comment]
You're using a weird syntax for async components, try doing it this way Vue documents it: https://vuejs.org/v2/guide/components.html#Async-Components.
```
Vue.component('async-webpack-example', function (resolve) {
  // This special require syntax will instruct Webpack to
  // automatically split your built code into bundles which
  // are loaded over Ajax requests.
  require(['./my-async-component'], resolve)
})```

I haven't tried it in RC10, but it's worked perfectly as advertised for me.

**Comment by dts** [comment]
Actually, I'm also having some issues, and async components appear to be playing a role...

**Comment by bimohxh** [comment]
@Atinux  I have upgrade nuxt to `1.0.0-rc11` ( vue version is `2.4.2`) but still got error 

```
vue.runtime.esm.js:475 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Editor>
       <Comment> at components/comment.vue
         <Pages/repo/Owner/Name/index.vue> at pages/repo/_owner/_name/index.vue
           <Nuxt> at .nuxt/components/nuxt.vue
             <Default> at layouts/default.vue
               <Root>
```

**Comment by bimohxh** [comment]
@NicoPennec I try to place the code into `async mounted` but still not work

**Comment by bimohxh** [comment]
I fonud the error is in `components/comment.vue`

**Comment by dts** [comment]
Don't place the code in `async mounted`, put it in the components hash, but with a deferred result, like this:

```
components: {
  editor: () => import('~/components/editor.vue')
}
```

**Comment by bimohxh** [comment]
@dts  Thanks, It seems work
