### ISSUE TITLE
Classes set on <nuxt /> component in layout are sometimes lost

### ISSUE THREAD

**Issue by lehni** [nuxt/nuxt.js#1617]
My `default.vue` layout currently looks something like this:

```html
<template>
  <main-menu />
  <nuxt class="view" />
</template>
```

At first, the `.view` class gets set on whatever page component is rendered in the `<nuxt />` container, but when I start changing routes through `<nuxt-link>` tags, this class gets subsequently lost.

This doesn't happen when working with `vue-router` directly, from which I am currently porting a project to Nuxt.js, so it looks like a Nuxt.js bug to me.

**Comment by lukasborawski** [comment]
@lehni You have to set this class on some patent component.

**Comment by lehni** [comment]
But isn't this a bug? Why does the class get lost?

**Comment by Atinux** [comment]
Because `<nuxt/>` does not correspond completly to `<router-view>`, see https://github.com/nuxt/nuxt.js/blob/dev/lib/app/components/nuxt.vue

**Comment by lehni** [comment]
It looks like it could rather easily pass `class` through to the `<nuxt-child>` instance? Happy to create a PR if it's of interest.

**Comment by Atinux** [comment]
You can add a PR @lehni but it should work with `style` too (see https://github.com/nuxt/nuxt.js/blob/dev/lib/app/components/nuxt.vue)

**Comment by lehni** [comment]
I believe this should hold the solution to both problems:

https://github.com/vuejs/vue/commit/6118759

From the release notes of [`v2.4.0`](https://github.com/vuejs/vue/releases/tag/v2.4.0):

* Easier creation of wrapper components:
   * New component option: inheritAttrs. Turns off the default behavior where parent scope non-prop bindings are automatically inherited on component root as attributes.
    * New instance properties: $attrs & $listeners. $attrs contains the parent-scope attribute bindings that were not recognized as props, and $listeners contains the v-on listeners registered in the parent scope (without the .native modifier). These are essentially aliases of $vnode.data.attrs and $vnode.data.on, but are reactive.

Combining these allows us to simplify a component like this down into this:
```html
<div>
  <input v-bind="$attrs" v-on="$listeners">
</div>
```
Based on discussion in https://github.com/vuejs/vue/issues/5983.

**Comment by lehni** [comment]
Unfortunately this works for everything *except* `class` and `style`, and there is already a closed issue about that, see https://github.com/vuejs/vue/issues/6144#issuecomment-316543936

**Comment by lehni** [comment]
Without this, I don't see a clean way that this can be done. And I'm fine with the status quo.
