### ISSUE TITLE
Run "nuxt serve" under subpath (/prefix)

### ISSUE THREAD

**Issue by robinandeer** [nuxt/nuxt.js#1619]
Hey,

I'm trying to serve nuxt behind [Caddy](https://caddyserver.com/). This is my `Caddyfile`:

```
my.domain.com

gzip

...

proxy /prefix localhost:3000 {
    header_upstream Host {host}
    header_upstream X-Real-IP {remote}
    header_upstream X-Forwarded-For {remote}
    header_upstream X-Forwarded-Proto {scheme}
    header_upstream X-Scheme {scheme}
    header_upstream X-Script-Name /trailblazer-ui
}
```

However, when I navigate to my URL: `my.domain.com/prefix` I get an error because the server can't find the page:

![screen shot 2017-09-08 at 17 17 17](https://user-images.githubusercontent.com/1220232/30218585-af3a3dba-94b9-11e7-8095-fa28bfc084e0.png)

So the server is working but something about the URL prefix is messing things up..

I had to install a [reverse proxy fix](https://github.com/wilbertom/flask-reverse-proxy) plugin to make this work in Flask (Python framework) so I was wondering if there's is something similar I have to do here?

**Comment by pi0** [comment]
Hi. Did you tried adding router base to nuxt.config.js file?

```js
{
router: {
    base: '/prefix/'
}

}

**Comment by robinandeer** [comment]
Oh thank you - I didn't find that in the documentation!
It seems to be the setting I was looking for 😄 

Together with relative paths to assets:

```html
<img src="~/static/trailblazer.png">
```

... it's working like a charm!

Thanks so much

**Comment by oppianmatt** [comment]
how do you do relative paths to assets mentioned in the nuxt.config.js like so?

```
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/icon.png' },
      { rel: 'stylesheet', href: '/reset.css' }
    ],
```

**Comment by 1stevengrant** [comment]
I've just implemented this very thing but I can't for the life of me get the static paths to render correctly for SVG.

This works fine `<img src="~/static/trailblazer.png">` but `<svg><use xlink:href="~/static/symbols.svg#launch"></use></svg>` does not.

Anyone seen this?
