### ISSUE TITLE
node_modules not in root dir

### ISSUE THREAD

**Issue by dts** [nuxt/nuxt.js#1621]
I want to keep my node_modules in `/package`, not next to the code - normally I can easily achieve this by changing resolve and module loader paths in the webpack config (along with changing NODE_PATH).  Unfortunately, it doesn't seem to work with Nuxt because of server-side rendering.  This appears to come from a bug in the 'resolve' package, which `vue-server-renderer` depends on, but I'd like to be able to specify the modules path easily with nuxt, and not have it be quite such a big ordeal.

**Comment by pi0** [comment]
Hey. You can use `modules_dir` option in `nuxt.config.js` to specify `node_modules` used by nuxt builder if pretty sure what are you doing.

**Comment by dts** [comment]
Hrmm, I spotted that in the code, but got distracted by the new concept of modules in the latest RCs.  For me, adding that to the `nuxt.config.js` causes a webpack options validation error ("Invalid configuration object"), deleting the modules_dir config item in the extend() function doesn't solve that problem.

**Comment by pi0** [comment]
Do you use full string path for modulesDir? If possible sharing nuxt.config.js can help

**Comment by dts** [comment]
Changing `rootDir` and `srcDir` appear to solve the problem - thanks!
