### ISSUE TITLE
Manually reordering routes

### ISSUE THREAD

**Issue by robyedlin** [nuxt/nuxt.js#1622]
Referencing vue-router issue: https://github.com/vuejs/vue-router/issues/703

Nuxt is doing this with routes: 
```
		{
			path: "/",
			component: _50d71714,
			children: [
				{
					path: "",
					component: _0e9a02d2,
					name: "index"
				},
				{
					path: "dapps/:slug?",
					component: _40a1f196,
					name: "index-dapps-slug"
				}
			]
		},
                {
			path: "/dapps/:slug?",
			component: _57bef853,
			name: "dapps-slug"
		}
``` 
and I want to reorder them like this:
```
                {
			path: "/dapps/:slug?",
			component: _57bef853,
			name: "dapps-slug"
		},
		{
			path: "/",
			component: _50d71714,
			children: [
				{
					path: "",
					component: _0e9a02d2,
					name: "index"
				},
				{
					path: "dapps/:slug?",
					component: _40a1f196,
					name: "index-dapps-slug"
				}
			]
		}
``` 
Is it possible? This way, when I directly load /dapps/:slug, it will catch the first route and display a full page, but when I navigate to the child route, it will show a popup.

**Comment by pi0** [comment]
Hi. Did you tried [router-module](github.com/nuxt-community/router-module) ? It gives you the ability to provide a totaly customized (but manual) `routes.js` file.

**Comment by robyedlin** [comment]
Hi @pi0, there's a 404 on that.

**Comment by pi0** [comment]
Eh Link updated :))

**Comment by robyedlin** [comment]
Thanks, I'll check that out and close it up if it's working.

**Comment by robyedlin** [comment]
Looks like it will solve it. 

Loving this framework. Excellent job!

**Comment by robyedlin** [comment]
Hi @pi0, FYI `nuxt generate` and `nuxt build` appear to break with  https://github.com/nuxt-community/router-module

https://github.com/nuxt-community/router-module/issues/2

**Comment by feedgit** [comment]
@robye Did you success with your issue

**Comment by robyedlin** [comment]
@feedgit Yes, this has been resolved.

**Comment by feedgit** [comment]
@robyedlin If use router module, auto generate from pages folder of Nuxtjs will be disabled, right?

**Comment by robyedlin** [comment]
That's correct, auto generate from pages folder will be disabled. Nuxt will pick up the routes from router.js.

sample router.js file: https://github.com/state-of-the-dapps/sotd-www/blob/master/router.js

**Comment by feedgit** [comment]
I tried Router Module by @Atinux . It's been good but have issue with Chrome Windows 7. :(
