### ISSUE TITLE
[bug] Unable to get started, basic template doesn't work.

### ISSUE THREAD

**Issue by trusktr** [nuxt/nuxt.js#1623]
I'm not able to get a very basic template working. I started my first app, and I have a single file:

pages/index.vue:
```html
<template>
  <p>
    <h1>Hello world!</h1>
  </p>
</template>

<style>
  p {
    border: 5px solid teal;
  }
</style>
```

and Nuxt throws an error that doesn't seem right:

```
 ERROR  Failed to compile with 1 errors                                                                       17:10:27

 error  in ./nuxt/pages/index.vue

(Emitted value instead of an instance of Error)
  Error compiling template:

  <p>
    <h1>Hello world!</h1>
  </p>

  - Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.


 @ ./nuxt/pages/index.vue 10:0-245
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```

---

I have a single `<p>` root element in the template, I don't see why it would throw this error.

**Comment by trusktr** [comment]
My srcDir is `nuxt`, which is why you see `./nuxt/pages/index.vue`. I've also ran `npm install sass-loader --save` and nothing else. This is a brand new app with only that single Vue file.

**Comment by trusktr** [comment]
If I delete the `h1`, so that my Vue file looks like this:

```html
<template>
  <p>
  </p>
</template>

<style>
  p {
    border: 5px solid teal;
  }
</style>
```

then it works perfectly fine.

😢

**Comment by trusktr** [comment]
If I change it to

```html
<template>
  <div class="WTF?">
    <h1> Hello </h1>
  </div>
</template>

<style>
  p {
    border: 5px solid teal;
  }
</style>
```

then it works! What the!!!???

**Comment by trusktr** [comment]
Soon as I remove the wrapping div, then it breaks.

**Comment by trusktr** [comment]
Maybe this is a Vue bug?

**Comment by lukasborawski** [comment]
Dude you have to declare `script` tag with atleast component name.

**Comment by NicoPennec** [comment]
nope, it's just a basic HTML5 mistake ;-)

a `<p>` element cannot contains another block element, eg. <div>, <p>, ...

So your template:
````
<template>
  <p>
    <h1>Hello world!</h1>
   </p>
</template>
```
is compiled like this:
```
<template>
    <p></p>
    <h1>Hello world!</h1>
    <p></p>
</template>

But it's forbidden by Vue.js... a template must have only one child.

**Comment by trusktr** [comment]
Interesting! I never ran into this before, because I never tried that. What a weird browser quirk. It's strange to have my markup being modified like that by the browser, wish they didn't design it that way.
