### ISSUE TITLE
Website not working while 'npm run build'

### ISSUE THREAD

**Issue by lingopalm** [nuxt/nuxt.js#1624]
I already submitted this issue but no one answered and someone labeled my post as question.
I think I didn't make the point clear. The issue is the web site on production will not work properly while you are re-building for some code change.
The website itself will work if you have cache, but if you are first time user and don't have cache bootstrap.js or fontawesome nuxt.js module will not be loaded and thus website will not work properly.
The downtime is just while it is building (maybe 20~30 sec) but if you modify code frequently or if you have so many users it will be a serious problem.

**Comment by NicoPennec** [comment]
Have you tried PM2 to manage your production environment?

> Production Process Manager for Node.js apps with a built-in Load Balancer. http://pm2.io/

**Comment by lingopalm** [comment]
Thank you for your reply. I actually use forever. I think PM2 is the similar tool with forever.
I tried testing on my local PC (windows environment) and there was no problem. Maybe there is another problem on my server side.
Thank you for the help.

**Comment by reedzhao** [comment]
I have the same problem but can't find an example of solution. PM2 cluster mode does not help in this case.
During `npm run build`, some files are removed therefore causing js file missing.  `npm run build` takes about 60 sec on our server.  Anyone visiting during this time will get 505 or file missing.
