### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by cahyowhy** [nuxt/nuxt.js#1625]
i try to visiting profile route from nuxt-link
```
<nuxt-link class="nav-item-child nav-item-hover" :to="{name:'profile-id', params:{id: $store.state.auth.user.id}}">
                                    Profile
                                </nuxt-link>
```

but i get an error in my browser
![image](https://user-images.githubusercontent.com/18083469/30237129-8bde1066-9555-11e7-98b9-22174142d46e.png).

this is my asyncData method, $store.action & my folder structure
![image](https://user-images.githubusercontent.com/18083469/30237146-e9f9c94c-9555-11e7-87a2-36dee028b951.png)

![image](https://user-images.githubusercontent.com/18083469/30237149-03ee0048-9556-11e7-9f71-1b26764e46fa.png)

![image](https://user-images.githubusercontent.com/18083469/30237195-285dab6c-9557-11e7-95f0-d187d4e7c037.png)

the error just happened when i click the link from nuxt-link & use this syntax `context.$router.push({name: 'profile-id', params: {id: data.user.id}});`
but when i do click right and open link in a new tab, the error is gone...

can anyone solve this :( , sorry for bad english

**Comment by alexchopin** [comment]
Hi @cahyowhy, 
can you try to use `fetch()` instead of `asyncData()` in your case?
```js
fetch ({ store, params }) {
  return store.dispatch('profile/fetchProfile', params.id)
}
```

**Comment by cahyowhy** [comment]
@alexchopin  still same

**Comment by cahyowhy** [comment]
solved 
by using this 
this.$router.push(`/profile/${data.user.id}`);

<nuxt-link class="nav-item-child nav-item-hover" :to="'/profile/'+$store.state.auth.user.id">
                  Profile
                </nuxt-link>
