### ISSUE TITLE
How do we pass data from Express middleware to nuxt.render?

### ISSUE THREAD

**Issue by trusktr** [nuxt/nuxt.js#1627]
For example, I'm convertin a back-end Handlebars route to using Vue/Nuxt. Before I had

```js
app.use(session(...))

app.get('/route', (req, res) => {
  res.render('foo')
})
```

where somehow the `user` data property is available to use inside the `foo` Handlebar view thanks to the `session()` middleware.

However, now I have

```js
app.use(session(...))

app.get('/route', nuxt.render)
```

which automatically renders `pages/route.vue`, but I'm not sure how to get the `user` property from the `session()` middleware to use it in the `route.vue` page. 

Is there a way?

**Comment by trusktr** [comment]
I should point out that my `pages/route.vue` file look like

```html
<template>
 <div>{{user}}</div>
</template>

<script>
// nothing
</script>
```

There's no JavaScript, but I thought perhaps if the backend send some data, and the page is basically just static, there's no need for JS, we should be able to just use the data.

Is this the case? Or do I have to go out of my way to make the client hit an API that I now have to create in order to send the `user` value?

**Comment by gangsthub** [comment]
I think that the API is the way: just as we see in the express template (and we leave the request part to axios).

**Comment by trusktr** [comment]
Idea: maybe a middle ware can pre-populate `req.nuxtData` or something.

**Comment by alexchopin** [comment]
Hi, you can use renderRoute() instead of render() and add data into res object.
https://nuxtjs.org/api/nuxt-render-route
