### ISSUE TITLE
if data is undefined: app goes out of sync on SPA

### ISSUE THREAD

**Issue by Jonarod** [nuxt/nuxt.js#1629]
# Problem
When in `mode:'spa'` , if a data bound to the template is `undefined` : navigation back or using `<nuxt-link/>`s does NOT retrieve anything. The app turns out of sync, it becomes impossible to re-render without refreshing the entire page manually. 

# Expected
If that page contains an `undefined` data supposed to be rendered on the page (using data-binding on the template): it simply should not render the underlying component or render an HTML tag with `null` or blank or whatever. 

But most important is: **THE APP SHOULD NOT GET OUT OF SYNC**.

At bare minimum, even if the user gets an ugly error message (which I believe he should NEVER see), the user should be able to go back using its browser's history and the page should re-render normally (re-fetching data etc...).

# Notes
My implementation can be the problem as I use a `plugin/` function to : 
1. fetch data using axios
2. treat/clean some data
3. comit vuex to mutate the state with previously fetched/cleaned data

Maybe this architecture is not compatible with expected behavior (??)
Also, I dont use a `validate()` rule, which I can implement to bypass the problem and present a 404 page if one of the data is `undefined` (solution I use so far).

P.S: I am using nuxt version 1.0.0-rc11.

**Comment by uptownhr** [comment]
@alexchopin shouldn't we marked this as bug not enhancement? I believe this doesn't occur on `universal` mode. 

Also, I also have a slightly different issue going on. The simple page component below does not not react to the `this.test = 'test'` change on a fresh reload of the page. If the user came here through a route push, test variable reacts properly on the template.

```
<template>
  <div>
    test: {{test}}
  </div>
</template>

<script type="text/ecmascript-6">
  export default {
    data () {
      return {
        test: ''
      }
    },

    mounted (){
      this.test = 'asdf'
    }
  }
</script>
```

**Comment by uptownhr** [comment]
here's a slightly different scenario also experiencing this problem. `this.test.text` also does not react to the 'wtf' update. 

```
<template>
  <div>
    test: {{test}}
  </div>
</template>

<script type="text/ecmascript-6">
  export default {
    data () {
      return {
        test: {
          text: null
        }
      }
    },

    mounted (){
      this.test = {
        text: 'wtf'
      }
    }
  }
</script>
```

**Comment by uptownhr** [comment]
I've gone further and tested against a non Page component and shows that this is not normal data behavior for a Vue component. The same component, if not a page component, will render the text properly for both scenarios above.

**Comment by uptownhr** [comment]
tagging in other nuxt members as I feel this is a pretty large issue. @pi0 @Atinux @alexchopin

**Comment by Atinux** [comment]
Will be fixed in next release, thank you for your help narrowing this issue @uptownhr

**Comment by uptownhr** [comment]
@Atinux awesome. Thanks!

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1629](https://trello.com/c/KpR8dob3/33-1629)
