### ISSUE TITLE
[BUG] Unable to use `this` inside `asyncData`

### ISSUE THREAD

**Issue by trusktr** [nuxt/nuxt.js#1630]
I have a component like this:

```html
<template>
  <div>
    <some-component :user="user"></some-component>
  </div>
</template>

<script>
  import SomeComponent from '@/components/some-component'
  import fetch from 'isomorphic-fetch'

  export default {
    components: {
      'some-component': SomeComponent,
    },

    mounted() {
      console.log(' 1 route name:', this.$route.path) // this works fine.
    },

    async asyncData(...args) {
      console.log(' 2 args:', args)
      console.log(' 2 this:', this) // UNDEFINED
      console.log(' 2 route name:', this.$route.path) // ERROR, cannot read property $route of undefined.

      const json = await (
        await fetch(`/api${this.$route.path}`)
      ).json()

      console.log(' -- json', json)

      return json
    },
  }
</script>
```

And when it gets to the line with `console.log(' 2 route name:'` it throws an error that `this` is undefined.

**Comment by trusktr** [comment]
Here's a screenshot:

<img width="1591" alt="screen shot 2017-09-09 at 7 30 46 pm" src="https://user-images.githubusercontent.com/297678/30245633-6d47a190-9595-11e7-8524-2c98e25d0cac.png">

**Comment by trusktr** [comment]
The screenshot shows the compiled code. Somethings definitely wrong, I'd expect `this` inside any method in `export default {...}` to refer to the component.

**Comment by trusktr** [comment]
Turns out, for my case, I could just use

```js
async asyncData({route}) {
  //...
  ... route.fullPath ...
```

without needing `this.$route`, but still, it is intuitive to expect that `this.$route` is usable, rather than `this` being undefined.

**Comment by NicoPennec** [comment]
Have you read the Nuxt documentation before start ? It should be intuitive 😉 

Remember to close all your open issues on GitHub, when resolved. Thks.

**Comment by lehni** [comment]
There's indeed a big orange note about this here: https://nuxtjs.org/api/

<img width="934" alt="screen shot 2017-09-10 at 13 20 16" src="https://user-images.githubusercontent.com/213275/30248580-dec01510-962a-11e7-94d0-8c214a9a671b.png">

**Comment by trusktr** [comment]
Oh okay, I missed that. To double check: we also need the `data()` method in tandem with this? 

So Vue doesn't give a way for you to hook into it to prevent a component from rendering asyncly I suppose? It would help eliminate this sort of issue, since using `this` is intuitively expected.

Anyways thanks, I was able to move on. Just gotta figure a way to automate the base URL. Any recommendation for that?

**Comment by uptownhr** [comment]
@trusktr can you show the URL you are trying to generate? Any relation to the page?

**Comment by uptownhr** [comment]
And you do not need data if you use asyncdata

**Comment by trusktr** [comment]
@uptownhr If I remove `data()`, then the client throws an error because I try to use the data in the `<template>`.

**Comment by trusktr** [comment]
@uptownhr Nevermind, it works now. Not sure why I was getting that error before. Maybe because having an error in `asyncData` prevented it from returning the data type that the template would need, so adding a working data() method was fixing it.
