### ISSUE TITLE
can't run bash script after production build

### ISSUE THREAD

**Issue by cayaner** [nuxt/nuxt.js#1631]
I **was** able to **automate** nuxt apps deployments to production,
deployments are done this ease > i'm running this simple bash script on production server:
```bash
cd /home/user/app
git pull origin master
yarn
npm run build
pm2 restart "app"
```
for now the build command for nuxt has **no end**, so i can **not** restart the node server **after** building the **app**.
![screenshot from 2017-09-10 11-25-56](https://user-images.githubusercontent.com/19613212/30247414-d9243f4a-961c-11e7-8969-cd8d938fd328.png)

how to fix it?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1454">#c1454</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Which version of Nuxt?

It works fine with Nuxt 1.0.0 RC11 when i run my bash script on Ubuntu 16.04.
At the end, you should have the message `Done in XX.S.`

> server-bundle.json  392 kB          [emitted]
>   nuxt:build Building done +34s
> Done in 35.99s.

**Comment by cayaner** [comment]
Ubuntu 17.04
Node 8.4.0
Nuxt 1.0.0 RC11

> server-bundle.json  739 kB          [emitted]  
  nuxt:build Building done +48s

Building done then it not ending ... so i have to Ctrl+c to exit...

thanks for help.

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1631](https://trello.com/c/438GVAn1/32-1631)

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
