### ISSUE TITLE
If the routing rewrite in the middleware, rather than 301 and 302 of the redirection

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#1632]
If the routing rewrite in the middleware, rather than 301 and 302 of the redirection, because the need to share some of the characteristics of the module

**Comment by Atinux** [comment]
I am sorry but I could not understand what you mean.

**Comment by HadiChen** [comment]
@Atinux 
I visit a /case/lists when this path is
I want to map this /case/lists /path to /news/lists in the path
But I do not expect customers to feel that I am mapped by /news/lists, the main customers can not see
Then, as to whether /case/lists need to be mapped to /news/lists in the path, by the middleware to decide whether or not
