### ISSUE TITLE
Deploying SSR nuxt.js on Firebase Cloud Function

### ISSUE THREAD

**Issue by ipoppo** [nuxt/nuxt.js#1634]
I started from nuxt-community/express-template which seamlessly integrated with express.

But issue transforming into Firebase is that all could functions need to be converted into single method. Next.js could be done nicely. In Nuxt.js, it is not possible to use nuxt.render middleware which use this.options.buildDir to dynamically access .nuxt file.

Is an option to pre-compile all file I need with nuxt?

**Comment by qm3ster** [comment]
[You can see here how to deploy express on google/firebase cloud functions](https://codeburst.io/express-js-on-cloud-functions-for-firebase-86ed26f9144c), where [nuxt can be used as an express middleware, just like it is in your template](https://github.com/nuxt-community/express-template/blob/master/template/server/index.js).

There's a chance you would need to run `yarn/npm build` yourself before `firebase deploy`.

A solution without express would probably be slimmer and charge you less per request, but this was an immediately obvious one.

**Comment by qm3ster** [comment]
```js
const functions = ('firebase-functions')
const { Nuxt } = require ('nuxt')

const config = require('./nuxt.config.js')
config.dev = false
const nuxt = new Nuxt(config)
exports.app = functions.https.onRequest(nuxt.render)
```
```
{
  "hosting": {
    "public": "dist",

    // Add the following rewrites section *within* "hosting"
   "rewrites": [ {
      "source": "**",
      "function": "app"
    } ]

  }
}
```
:warning: Attention :warning:
Routes that match a static file will not trigger the function, they will just serve the file.
[Found that here](https://youtu.be/LOeioOKUKI8?t=13m46s), but [not in the docs](https://firebase.google.com/docs/hosting/functions)?

For optimum performance, do **both** build and generate, but make sure to not render the routes you want to hit the function.

**Comment by qm3ster** [comment]
I originally wrote this as an April Fool's joke, but initial testing shows that going from
`yarn firebase serve -p 3000` to `yarn start` and back works.
You can load either initially and then navigate normally.

**Comment by ChuiSauCE** [comment]
@qm3ster that works good localy i just don't get why it's not working globaly. I've read some about .nuxt folder was being ignored on functions upload but they've fixed it. have you made it work?

**Comment by qm3ster** [comment]
I might try it today. What are you deploying as your function folder? The whole project?

**Comment by ChuiSauCE** [comment]
Just .nuxt folder besides index.js. Seems like it cannot reach that folder on cloud. 

As you mentioned above we should host dist folder. script tags on page looks like down below:

`<script src="/_nuxt/layouts\default.463bdf2b6acb6fe6f09b.js" defer=""></script>`

**Comment by qm3ster** [comment]
Does nuxt start work if you delete/rename nuxt config?

**Comment by ChuiSauCE** [comment]
in functions folder we need it to initialize nuxt.

Thats my functions/index.js:
```
const functions = require('firebase-functions');

const { Nuxt } = require('nuxt')

// We instantiate nuxt.js with the options
const config = require('./nuxt.config.js')
config.dev = false
const nuxt = new Nuxt(config)

exports.nuxt = functions.https.onRequest(nuxt.render);
```

**Comment by qm3ster** [comment]
# **THEY LIVE**
```json
{
  "scripts": {
    "prepackage-functions": "rimraf functions",
    "package-functions": "babel 'functionsES6' --out-dir 'functions' --copy-files --ignore 'node_modules'",
    "postpackage-functions": "cp -r .nuxt nuxt.config.js functions/ && cd functions && yarn"
  }
}
```
**functionsES6/package.json**:
```json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "firebase-admin": "~5.4.1",
    "firebase-functions": "^0.7.0",
    "nuxt-start": "1.0.0-rc11"
  },
  "private": true
}
```
**functionsES6/index.js**:
```js
import { Nuxt } from 'nuxt-start'
const functions = require('firebase-functions') // babel broke default import so whatever

const config = require('./nuxt.config.js')

config.dev = false
const nuxt = new Nuxt(config)

export var app = functions.https.onRequest(nuxt.render)
```
**functionsES6/.babelrc**:
```json
{
  "presets": [
    ["env", {
      "targets": {
        "node": "6.11.1"
      }
    }]
  ]
}
```
(the 6.11.1 version is what firebase functions provides)

**nuxt.config.js**:
```js
  generate: {
    routes: ['/about']
  }
```
(only include pages you want to be static, exclude those you want SSR)

**firebase.json**:
```json
{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [{
      "source": "**", "function": "app"
    }]
  }
}
```

in project root, not functions or functionsES6:

```
yarn build
yarn generate
yarn package-functions
yarn firebase serve
```
and then, if satisfied,
`yarn firebase deploy`

**PS**: **.gitignore**:
```gitignore
# firebase functions
functions
```

**Comment by qm3ster** [comment]
@alexchopin do you think nuxt should officially support this type of hybrid deployment?

Also, what does builder.forGenerate() do, in a sentence? Are `generate`'s build artifacts different to `build`'s?

**Comment by qm3ster** [comment]
Well, @ChuiSauCE and me both got it working in local simulator but not on real cloud functions.
Wrapping it in express made no difference.
```js
const { Nuxt } = require('nuxt-start')
const functions = require('firebase-functions')
const express = require('express')

const config = require('./nuxt.config.js')

config.dev = false
const nuxt = new Nuxt(config)
const app = express()
app.use(nuxt.render)
exports.app = functions.https.onRequest(app)
```
How can I get better error pages if I can't access the logs?
`dev = true` just makes it time out.

**Comment by chrishutchison9** [comment]
@qm3ster have you seen this?

https://github.com/davidroyer/nuxt-ssr-firebase

**Comment by qm3ster** [comment]
Yeah. What's [this all about](https://github.com/davidroyer/nuxt-ssr-firebase/blob/30aded474516100ba55ee1fe811f7ef09f28742e/prod/server/index.js#L22)?
Does `nuxt.render` **shove a promise into a callback**?!
According to [docs](https://nuxtjs.org/api/nuxt-render/), it just returns `Promise`, like a normal person.
Locally, not engaging in that strange behavior worked out both as an express middleware and directly as a handler for firebase http.

Beyond than that, he just uses express, like I tried as well.
I haven't tried using just real `nuxt` and not `nuxt-start` at all, despite #1813
I don't think something like CORS might be the problem since I am receiving a nuxt "Server error" template.

Please post here if you try deploying that repo.

**Comment by qm3ster** [comment]
P.S: 
```js
const admin = require('firebase-admin')
admin.initializeApp(functions.config().firebase)
```
isn't it either. Not only is that for accessing other firebase services, but I actually tried and it changes nothing.

**Comment by qm3ster** [comment]
How did you achieve 500 on local?

**Comment by lewis-yuburi** [comment]
@qm3ster any repo for this?

**Comment by qm3ster** [comment]
It's not actually working, due to some disagreement between real firebase environment and nuxt.
I will continue investigating if I get a way to get a better debug output from production nuxt.

**Comment by BruceHem** [comment]
@qm3ster  firebase serve is working for me, but when i deploy all i get is server error page.

**Comment by qm3ster** [comment]
That is indeed the case, @BruceHem.
Therefore, we are fulfilling the declared requirements of firebase, but some untold limitation on the server leads to pain and suffering.

**Comment by ChuiSauCE** [comment]
its about deployment friends. You need all the dependency list to be on dependency list. not even dev deps. nuxt comes as bundle of tons. which makes firebase functions suffer. that's what i believe xD

**Comment by BruceHem** [comment]
How comes this is a close issue?

**Comment by cagataycali** [comment]
Still I've same issue but doesn't understand well. What should I do? Here's my example https://github.com/cagataycali/nuxt-firebase-functions-ssr-example

**Comment by qm3ster** [comment]
@ChuiSauCE I am sorry, but how is that relevant?
We are trying to fix/hack Nuxt to be able to SSR on GCF, not roll a new solution.

**Comment by ChuiSauCE** [comment]
@qm3ster as I mentioned, its more about dependencies. I had errors about packages while deploying. localy it works coz dependencies are there. but it's ignored on deployment I mean whole node modules are ignored. So my saying is that we need to make clear dependencies on package.json. The way Nuxt is installed doesn't fit with firebase.

**Comment by cagataycali** [comment]
Nuxt & firebase works well in local environment,
Node: v8.0.0
npm: 5.5.1

But I'm trying @production, firebase's node version is 6.11.1 which is es2015. We must transpile with babel. But IDK

**Comment by ChuiSauCE** [comment]
Again I'm saying on deploy firebase functions ignore the node modules so you should be explicit on which modules you are using. You should include them on package.json as dependencies not dev-dependencies.
On logs we don't see much details but I'm sure they are all about missing modules.

**Comment by BruceHem** [comment]
@ChuiSauCE you seemed pretty sure about this do you have a working repo?

**Comment by besnikh** [comment]
@ChuiSauCE I think you are right about your argument saying that that dependencies should be included on package.json 
I am facing this problem at this time, I've already built my app but I want to to deploy it on Firebase Hosting.. is there any update on this case? 

@qm3ster Is there any update on making nuxt work with firebase functions ? 

Cheers

**Comment by jelmerf** [comment]
@besnikh have a look at https://github.com/davidroyer/nuxt-ssr-firebase - I got it to work using that (also check the closed issue about error logging over there).

**Comment by besnikh** [comment]
@jelmerf thank you for this info, I will try it tomorrow. Can I just ask u something did the debug thing make any issues during production ? and how is it working with Firebase... is on :fire: ?

**Comment by jelmerf** [comment]
@besnikh you shouldn't keep debug on in production. My experience with firebase has been mixed: it's not really fast and I had some errors that were fixed by downgrading an npm dependency. Ah well, both functions and firestore are still in beta, so maybe it is to be expected.

**Comment by ishitatsuyuki** [comment]
Please also see https://contacts.google.com/widget/hovercard?hl=en&origin=https://issuetracker.google.com&usegapi=1&jsh=m;/_/scs/abc-static/_/js/k%3Dgapi.gapi.en.yoTdpQipo6s.O/m%3D__features__/am%3DAAE/rt%3Dj/d%3D1/rs%3DAHpOoo9_VhuRoUovwpPPf5LqLZd-dmCnxw#id=__HC_94253229&_gfid=__HC_94253229&parent=https%3A%2F%2Fissuetracker.google.com&pfname=&rpctoken=32011453, this is the main issue causing server error.

**Comment by ishitatsuyuki** [comment]
If your dependency set is small, this workaround is viable:

0. Perform build as normal.
1. Comment out `node_modules` in `.gcloudignore`.
2. Run `yarn/npm install --prod`.
3. Deploy.

This will not work if your (zipped) dependency size exceeds the 100MB upload limit. Please complain in the issue tracker to urge Google to resolve this.

**Comment by lagmanzaza** [comment]
I have a problem after I try to deploy this repo https://github.com/davidroyer/nuxt-ssr-firebase

![screen shot 2561-01-09 at 20 19 19](https://user-images.githubusercontent.com/5283709/34751048-db22ec68-f5dc-11e7-921d-fe108d12af14.png)

**Comment by ishitatsuyuki** [comment]
@lagmanzaza you probably need to transpile it.

**Comment by lagmanzaza** [comment]
OMG I forgot that cloud function that supports node V6

**Comment by lagmanzaza** [comment]
Thank you very much

**Comment by lewyuburi** [comment]
Update -> https://www.youtube.com/watch?v=ZYUWsjUxxUQ

**Comment by qm3ster** [comment]
Why is it blurry?

**Comment by Nayir** [comment]
Well, I make the tutorial. But why David is using nuxt.renderRoute() instead of nuxt.render() ? At least, I have some strange issues when I'm creating an additional page, like www.example.com/additionalpage. 
FCF is "adding" my ('/') html content on ('/additionalpage') at the bottom of the page (inside <nuxt></nuxt>)
Did you have same issue ? It's coming from nuxt.renderRoute('/') right ?

**Comment by chanlito** [comment]
Cloud function doesn't work with latest Nuxt.

**Comment by ishitatsuyuki** [comment]
Nuxt 1.x (non-RC) raised the Node requirement to 8+. See https://github.com/phlogisticfugu/perfect-paca/pull/6 for works on transpiling it back.

**Comment by infostatus** [comment]
The Firebase team did a video explaining how to setup Nuxt with Firebase Functions:
https://www.youtube.com/watch?v=ZYUWsjUxxUQ

**Comment by mesqueeb** [comment]
@lewyuburi 
I'm using Nuxt RC version exactly as the Youtube tutorial mentions.

**The problem:**<br>
When opening a webpage with a different URI (other than landing page) it doesn't load any html besides the footer...

Any ideas how to also have other webpages loaded properly if those links are visited directly?

**Comment by JamieCurnow** [comment]
Spent so much time fighting with this but thankfully nuxt is soon to support fallback for node 6. So we're on the home stretch!
https://github.com/nuxt/nuxt.js/commit/412ffd4c0656779b247a173e5c5efe8241e6bf74

It works now if you install `nuxt-edge` rather than `nuxt` in your cloud functions folder. Then you can just `const { Nuxt } = require('nuxt-edge')` in your index.js of the functions and use it as usual.
Just be sure to compile down with babel when you `nuxt build`.

**Comment by uboat46** [comment]
Nuxt has it on it´s docs at https://nuxtjs.org/guide/routing/
<img width="933" alt="nuxt_fallback" src="https://user-images.githubusercontent.com/14956413/44957368-2d69c000-ae97-11e8-9438-8a1604748b83.png">

**Comment by jtorfs01** [comment]
Hi, I keep getting error: '504 timed out waiting for function to respond' Does anyone else get this error or know where it could come from? 

My function: 

//const functions = require('firebase-functions');
//const { Nuxt } = require('nuxt');
//const express = require('express');

const functions = require("firebase-functions");
const { Nuxt } = require("nuxt");
const express = require("express");
const app = express();

const config = {
    dev: false,
    buidlDir: 'src',
    build: {
        publicPath: '/'
    }
};

const nuxt = new Nuxt(config);

```
function handleRequest(req, res){
    console.log('handling request');
    res.set('Cache-Control', 'public, max-age=600, s-maxage=1200')
    nuxt.renderRoute('/')
    .then(result => {
        console.log('result: ' + result.html);
        res.send(result.html);
    })
    .catch(e => {
        res.send(e);
        console.log(e);
    })
}

app.get('*', handleRequest);
exports.ssrApp = functions.https.onRequest(app);
```

I also tried with function: 

function handleRequest(req, res) {
```
    console.log("log3");
    res.set("Cache-Control", "public, max-age=300, s-maxage=600");
    return new Promise((resolve, reject) => {
      nuxt.render(req, res, promise => {
        promise.then(resolve).catch(reject);
      });
    });
  }
```

But with the same result. 
PS: I'm using NodeJS v8 for my function so I don't think that's the problem.

**Comment by qm3ster** [comment]
@jtorfs01 does the artifact you uploaded include the results of "nuxt build"?
