### ISSUE TITLE
nuxtjs with electron `loadURL` is slow 

### ISSUE THREAD

**Issue by alterhu2020** [nuxt/nuxt.js#1635]
Hi Team,
 I use nuxtjs feature for electron's backend website, everything is fine .but just the first page loading using `loadURL` is really a bit slow .
the renderer content is blank for a few minutes ,i think it caused by the build process when run it .
do you guys have any suggestion or experience on integration with electron very well.
![loading_slow](https://user-images.githubusercontent.com/5029046/30257838-9ffa6e04-9669-11e7-90b0-d14cffc223e0.jpg)

also the offical electron example had packed many unnecessary libraries, which caused the build is too large.( see example: https://github.com/nuxt-community/electron-template)

Any

**Comment by alterhu2020** [comment]
any suggestion for integrating with electron feature, thanks team.

**Comment by alterhu2020** [comment]
team, did you have any better example solution for this feature .thank.

**Comment by alexchopin** [comment]
I moved this issue to the good repo.
