### ISSUE TITLE
multiple route params on a page

### ISSUE THREAD

**Issue by philippe-effinet** [nuxt/nuxt.js#1636]
Hello !

I want to generate an url in that format : http://mysite.tld/blog/{slug}-{id}

So I tried to create a page named : `/pages/blog/_slug-_id.vue`

Nuxt seems not generating the routing as expected. 

```
{
  path: "/blog/:slug-_id?",
  component: _f8ebb47a,
  name: "blog-slug-_id"
}
```

Is there a page naming convention in nuxt to deal with this route format ?

Or do I have to inject my needed route using `router.extendRoutes` config ?

**Comment by NicoPennec** [comment]
Anothe way:

create a single route : `/pages/blog/_slugid.vue`   (eg. "/blog/hello-123/" )

then split the route param:
```
asyncData({ params }}) { 
  const { slug, id }   = params.split("-")
}
```

**Comment by philippe-effinet** [comment]
Thanks !

I'll try that one ;)

**Comment by haffla** [comment]
Shouldn't it be 

`const [slug, id] = params.slugid.split('-')`?

Assuming the file `pages/blog/_slugid.vue`.

**Comment by NicoPennec** [comment]
correct! I just edited my answer. Thks

**Comment by philippe-effinet** [comment]
Everything is working like a charm ! Thank you all for your help ;)

**Comment by begueradj** [comment]
@nicooprat I tried your solution but I am getting: **Cannot read property 'split' of undefined** ... what am I missing? Thank you

**Comment by nicooprat** [comment]
@begueradj Hi, looks like you've pinged the wrong person ;) Anyway, try looking at what's in `params`. Are you sure your file is named `_slugid.vue`? Nuxt will "transfer" URL parameters to the `params` variable according to the file name. So if you name it `_test.vue`, you'll have to use `params.test`.
