### ISSUE TITLE
Window is not defined when importing vue-table2 plugin

### ISSUE THREAD

**Issue by PrimozRome** [nuxt/nuxt.js#1637]
I am importing a vuetable-2 plugin: https://github.com/ratiw/vuetable-2. 

I am registering it globally trough plugins/vue-table.js.

When referencing the component on nuxt page I get `window is not defined` error inside `node_modules/vuetable-2/dist/vuetable-2.js`

**Comment by lukasborawski** [comment]
Use:

```
if (process.browser) {
  require('external_library')
}
```

**Comment by PrimozRome** [comment]
@lukasborawski do I do that in plugins/vue-table.js like this?

```
import Vue from 'vue'
import VueTable from 'vuetable-2'

if (process.browser) {
  Vue.use(VueTable)
}
```

Still get the same error when referencing Vutable component in my page...

**Comment by lukasborawski** [comment]
nope, use this in the place where you're calling this plugin

**Comment by PrimozRome** [comment]
@lukasborawski little confusing for me right now...

If I understand right then the include of the Vue plugin that uses window object can not be configured globally via `nuxt.config.js` on the `plugins` and `vendor` section like this?

nuxt.config.js
```
  build: {
    vendor: ['vee-validate', 'vuetable-2']
  },
  plugins: [
    '~/plugins/vue-table',
    '~/plugins/vee-validate'
  ],
```

Thanks!

**Comment by KonstantinVlasov** [comment]
Hi, @PrimozRome!

use `require` instead of `import`, like this:
```javascript
import Vue from 'vue'

if (process.browser) {
  Vue.use(require('vuetable-2'))
}
```

**Comment by NicoPennec** [comment]
`if (process.browser)` is useless if you use the `ssr` plugin option:
```
  plugins: [{ src: '~/plugins/your-plugin', ssr: false }]
```

> ssr: Boolean (default to true) If false, the file will be included only on the client-side.

Docs:
- https://nuxtjs.org/guide/plugins#client-side-only
- https://nuxtjs.org/api/configuration-plugins#the-plugins-property

**Comment by KonstantinVlasov** [comment]
Oh, you are right, I always forget about `ssr: false` :)

**Comment by PrimozRome** [comment]
I think FAQ should be updated with this information!

**Comment by KonstantinVlasov** [comment]
`ssr` options already in docs: https://nuxtjs.org/api/configuration-plugins
but it's useful only for plugins, in other files you should use `process.browser`: https://nuxtjs.org/faq/window-document-undefined

**Comment by PrimozRome** [comment]
@NicoPennec `ssr: false` has worked fine.

But now if I refresh browser (Commad-R) everytime I get this:

https://www.dropbox.com/s/5hpkx94mugcuo0j/Screen%20Shot%202017-09-12%20at%2017.38.46.png?dl=0

After another refresh error is gone and app loads. It's very annoying.
