### ISSUE TITLE
process.env.baseUrl is not available in app.html

### ISSUE THREAD

**Issue by etanxing** [nuxt/nuxt.js#1639]
Basically `process` isn't available in app.html, can it be fixed? thanks.

**Comment by NicoPennec** [comment]
Have you follow this doc about base url? https://nuxtjs.org/api/configuration-router#base

```js
// nuxt.config.js)
module.exports = {
  router: {
    base: '/example/'
  }
}
```

> When base is set, nuxt.js will also add in the document header <base href="{{ router.base }}"/>.

**Comment by etanxing** [comment]
In app.html `process.env.fbAppId` isn't accessable.
```
//app.html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
<script>
//facebook-jssdk
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = `//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10&appId=${process.env.fbAppId}`;
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<head>
  {{ HEAD }}
</head>
<body {{ BODY_ATTRS }}>
  {{ APP }}
</body>
<div id="fb-root"></div>
</html>
```

**Comment by francescobm** [comment]
Had a similar problem. 
In my case I accessed process.env.myVar from nuxtServerInit() method and put my var in the store, then accessed it from the vue component.
Also you will have to map the environment variable in the nuxt.config.js .

**Comment by evseevnn** [comment]
Had a similar problem.

**Comment by Atinux** [comment]
@etanxing In next release, you can access `ENV` inside `app.html`, so if you have `env.fbAppId` in your `nuxt.config.js`, you can use `ENV.fbAppId`.

**Comment by Atinux** [comment]
Also, you can use `process.env` too (only for Node.js environement variables).
