### ISSUE TITLE
add expired headers to CSS and JS files

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#164]
Hi,

how is it possible to add expired headers to CSS and JS files? Maybe a section inside of FAQ would be great for users of NUXT

Cheers

**Comment by alexchopin** [comment]
Hi,
You add expired headers with `.htaccess` file in your `static` directory.
[Source](http://stackoverflow.com/questions/13972629/add-expires-headers)

**Comment by dohomi** [comment]
Hi @alexchopin `.htaccess` is an `Apache` configuration file as far as I know. It would not work inside of the `npm` world, am I mistaken? I just don't know where and how to add them, I deploy with `now` and I think some middleware is in need of doing that. As `NUXT` is doing most of the configuration I thought there it would be possible to add the header caches

**Comment by Atinux** [comment]
@dohomi you should use nuxt programmatically with your express server to add these headers logic, it will be easier 👍

**Comment by dohomi** [comment]
OK I'll try to do that. Maybe if you could at a setup inside of the `FAQ`section it would be great. I think its a common task for people to add the expired headers to gain better results on `PageSpeed` or `YSlow`

**Comment by Atinux** [comment]
Hi @dohomi 

Finally, the expired headers will be added directly on production (`nuxt start`), it will be possible when we will generate unique filename on build time for better caching.

One of the goal of nuxt.js is to also create blazing-fast and PWA so we will have a perfect score on PageSpeed by default ⚡️

**Comment by dohomi** [comment]
you guys make an incredible job here!
