### ISSUE TITLE
Update the url causes reinitialization of the current component

### ISSUE THREAD

**Issue by Kasheftin** [nuxt/nuxt.js#1642]
I'm trying to create a very simple application. 
That is: the page with the search box at the top and ~~search results below~~ nothing, just a box.
When a user types something in the box, the url should be automatically updated. 
For example, if a user types `something`, the url should become `/search?srch=something`.
When a user reloads the `/search?srch=something`, the page should appear with `something` already typed in the input field. 

Here's the example, https://github.com/Kasheftin/nuxt-search-bug, and the relevant page from there: https://github.com/Kasheftin/nuxt-search-bug/blob/master/pages/search.vue

So I watch for the changes of the input field and call `this.$router.replace({name: 'search', query: {srch: srch}}`. Actually, I don't want any logic to run, I want just update the url. But the logic runs, I can't disable it (I tried to change the this.$router.listener.ready, replace the listener with some dummy function etc). It destroys the current search component, creates a new one, the input loses the focus. This all works buggy and looks buggy as well. 

I'm not sure if it's the nuxt's bug or the vue-router's itself. The last is strange, it misses obvious parameters like any other library has, for example one using backbone router could easily pass additional {trigger: true/false} parameter to the navigate function, but the vue-router does not have any. It has a lot of guards, but they are useless if you want to change the url, but don't want to trigger any logic behind.

**Comment by Kasheftin** [comment]
I put some time into the investigation of this and state that this is the bug indeed.

I found several ways to avoid the buggy behavior, that's pretty simple. For example, one may put anything into the browser history directly, and there's no way for vue-router to determine this. So instead of calling `this.$router.push({name: 'route-name', query: {...}})` one can generate the url manually and put in into the history like this:

    const route = this.$router.resolve({name: this.$route.name, query: {...}})
    window.history.pushState({key: Date.now().toFixed(3)}, '', route.href)

But anyway I started the investigation and found an interesting behavior: the bug magically disappears if the buggy component put inside the nuxt-child. I created the separate repo to demonstrate this: https://github.com/Kasheftin/nuxt-search-bug3.

There we have srchComponent that watches for the changes and triggers `this.$router.push`. It lies in the root, we can load it by following the `/srchComponent` url.
And it has the bug - the component reinitialization goes after each key press. 

Also I created the dummy nuxt-child wrapper called nuxtChildWrapper. And there's the symlink from `/pages/nuxtChildWrapper/srchComponent` to the `/pages/srchComponent`, so the target component is just the same. One may notice that the `/nuxtChildWrapper/srchComponent` page works just fine.

**Comment by benosman** [comment]
It sounds like this is related to an issue I posted a while back in #1255.

Unfortunately that too didn't get any attention from the devs, but it does seem like quite a bug.

**Comment by benosman** [comment]
I believe I have found the cause of this in #1255, and created a workaround.

You need to add / edit a default layout in `layouts/default.vue`

```vue

<template>
  <nuxt :nuxtChildKey="routerViewKey"/>
</template>

<script>
export default {
  computed: {
    routerViewKey () {
      // If current route has children
      if (this.$route.matched.length > 1) {
        return compile(this.$route.matched[0].path)(this.$route.params)
      }
      return this.$route.fullPath.split('?')[0].split('#')[0]
    }
  },
}
</script>

```
