### ISSUE TITLE
How to get a vuex instance in the axios of plugins, I want to implement an interceptor to add public parameters but not to store,

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#1643]
How to get a vuex instance in the axios of plugins, I want to implement an interceptor to add public parameters but not to store,Please help me。 i try 'import store from '~/store' . but it can't;

**Comment by Atinux** [comment]
@fengjiel 

You can do it with a plugin:

`nuxt.config.js`
```js
module.exports = {
  plugins: ['~/plugins/test`]
}
```

`~/plugins/test.js`
```js
export default ({ store }) => {
  // You have access to store here
}
```

BTW, you should use the official [axios module](https://github.com/nuxt-community/axios-module), it's recommend to avoid any security issue due to SSR.

**Comment by fengjiel** [comment]
Thank you. Thank you very much ,it worked! @Atinux
