### ISSUE TITLE
Meta not being updated on route change

### ISSUE THREAD

**Issue by camilodelvasto** [nuxt/nuxt.js#1644]
I'm having an issue when I navigate to another page: the meta tags are not getting updated correctly, only the title gets updated. The rest of the tags just disappear.

**about.vue** (simplified)
```
export default {
  head () {
    return {
      title: 'This is the about page',
      meta: [
        { hid: 'og-title', property: 'og-title', content: 'About page description for og' },
      ]
    }
  }
}
```
The tags are visible on the first load, but then if I go to another page and come back, the tags won't be shown. URL: https://dist-zetwcskggm.now.sh/about - am I doing something wrong?

**Comment by Atinux** [comment]
@camilodelvasto The tags are beeing updated correctly but added at the end of `<head>`:

![screenshot_2017-09-12_14-01-07](https://user-images.githubusercontent.com/904724/30324882-e02127e8-97c2-11e7-9bc0-259f5f0b473c.png)

**Comment by NicoPennec** [comment]
@camilodelvasto and be careful ! the Facebook meta must be `property: 'og:title'`  (with colon `:`)

**Comment by camilodelvasto** [comment]
Oh my, thanks a lot!
