### ISSUE TITLE
Can not access env variables on server side

### ISSUE THREAD

**Issue by jyanchen** [nuxt/nuxt.js#1646]
```js
// nuxt.config.js
build: {
  env: {
    VERSION: '1.0.0'
  }
}

// server/index.js
console.log(process.env.VERSION) // undefined
```

I can get the env variables in components, but i can't get env variables in server side code. I have try to resolve it with some transform plugins(like: babel-plugin-transform-define), because I'm using babel, but still not work.

**Comment by homerjam** [comment]
Is `server.js` running nuxt as middleware? If so you need [dotenv](https://www.npmjs.com/package/dotenv) or similar.

The nuxt.config env vars are for use within nuxt context only.

**Comment by jyanchen** [comment]
@homerjam No. But also failure to replace with DefinePlugin
```js
build: {
  plugins: {
    new webpack.DefinePlugin({
      VERSION: '"1.0.0"'
    })
  }
}
```

**Comment by homerjam** [comment]
Sorry I just realised you're in the `build` section of config rather than `env`. Do you need `extend()`?

```
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLINT on save
    */
    extend(config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        });
      }
      config.env.VERSION = '1.0.0';
    },
  },
```

**Comment by jyanchen** [comment]
@homerjam  Thanks. I think I should use dotenv instead env config.
