### ISSUE TITLE
Simultaneous route transition

### ISSUE THREAD

**Issue by gridsystem** [nuxt/nuxt.js#1647]
Is it possible to use the default transition mode, simultaneous, with nuxt routes? I can only get in-out and out-in working. I'd like both animations to run in parallel, with both routes in the dom at the same time.

**Comment by RSchwan** [comment]
Something like that works for me
``` javascript
transition () {
  return {
    name: 'bounce',
    mode: 'in-out',
    enter (el, done) {
      done()
    }
  }
}
```

**Comment by gridsystem** [comment]
Thanks @RSchwan, I haven't tried this out but the logic is sound. Is it impossible to use the simultaneous method? Is this a limitation of vue-router or nuxt's implementation of it?

**Comment by ydnar** [comment]
I have transitions working with simultaneous in and out using `mode: ''` (blank). That forces the key to exist but be the un-named default transition mode in Vue.

To get the content to render correctly during a cross-fade, I used a wrapper `<div>` with `display: flex` and some sauce:

```vue
<template>
  <div class="page-content">
    <nuxt/>
  </div>
</template>

<style lang="sass">
// The .page-content class implements a trick for simultaneous
// in-out CSS transisions between routes.
.page-content
  display: flex
  position: relative
  flex-direction: row
  width: 100%
  min-height: 60vh

  // This sets all children of .page-content to overlap each other without resorting to position: absolute
  &>*
    position: relative
    min-width: 100%
    margin-right: -100%
</style>
```

**Comment by gridsystem** [comment]
Thanks @ydnar I'll check this out!
