### ISSUE TITLE
AsyncData (axios) creates unexpected session

### ISSUE THREAD

**Issue by XEngine** [nuxt/nuxt.js#1648]
While enabling sessions in Express with 'saveUninitialized' as true, I figured that express saves one more irrelevant session other than connect.sid related session and with each refresh it generates one more session.

In this problem when page first loads I get two session. One with my cookie, other with asyncdata axios. So with each refresh axios in asyncdata generates a new session while my original cookie related session just touched.

Does asyncData works likes this or this issue based on axios ?

![image](https://user-images.githubusercontent.com/6682465/30376897-9dc87796-9896-11e7-86b1-5d64eab22a00.png)

![image](https://user-images.githubusercontent.com/6682465/30376985-ca249b1c-9896-11e7-8746-d53b23159233.png)

**Comment by XEngine** [comment]
```JavaScript
import axios from 'axios'

export default function({isServer, req}) {
  if (isServer) {
    axios.defaults.headers.common.cookie = req.headers.cookie
  }
}
```

Updated. By using this middleware for axios, it now seems normally generates only one session per user.

**Comment by alexchopin** [comment]
Related to this repo https://github.com/nuxt-community/express-template
