### ISSUE TITLE
Hot Reloading of Sass in Assets folder

### ISSUE THREAD

**Issue by francescobm** [nuxt/nuxt.js#1649]
Hello! For my e-commerce project I want to have an agnostic approach in relation to the styling. For this reason I have a git subtree in the assets folder of nuxt, which is shared with other web applications.

The problem is, whenever I work on my styles and I do some changes, the whole nuxt dev build is run again, and since the project it's getting big, is taking a while before being completed. This make my ui development a bit a pain as I have to wait 30 secs each time I change some style before seeing it in the browser in all its glory.

So, question is (more than a issue), is it possible to configure hot reloading for the assets folder with the current nuxt implementation ?

**Comment by Atinux** [comment]
Hi,

I'm not sure to understand why you whole nuxt process restarts wen you update an asset, it already handle hot-reloading for SASS.

Could you create a reproduction repository and re-open the issue when done please?
