### ISSUE TITLE
Invalid component name: "_id".

### ISSUE THREAD

**Issue by CoconutTheSlayer** [nuxt/nuxt.js#165]
Hello i have a file structure -> pages/flat/_id.vue and it gets the id parameter everything works but i'm getting this warning message.

[Vue warn]: Invalid component name: "_id". Component names can only contain alphanumeric characters and the hyphen, and must start with a letter.

**Comment by alexchopin** [comment]
Hi, do you include you component in another one ?

**Comment by ruslankonev** [comment]
The same error. Maybe after vue was update?

**Comment by CoconutTheSlayer** [comment]
Actually updating to new nuxtjs version broke the whole thing:-) i was defining custom routes as

{ name: 'financing', path: '/financing', component: 'pages/financing/financing.vue' }

it somehow felt more natural to me than forcing the directory structure. Am I right that now I have to reorganize the whole code structure?

**Comment by alexchopin** [comment]
Yes, you are right.

**Comment by CoconutTheSlayer** [comment]
just to clarify things as I'm developing not exactly a small project, will things break in the future?

**Comment by alexchopin** [comment]
No breaking changes planned for the future, at least until the final 1.0 release.

**Comment by Atinux** [comment]
Hi @CoconutTheSlayer 

I took a look at it, and it's because of the hot-reload module, nothing to worry about, it's only in development mode.

If you want to remove this warning, just add a `name` property to your page component and it'll be fixed :)

**Comment by mohamedhassan1** [comment]
With me solved by 
**removing the property name** that  your IDE or editor created when making a new component
as it like 
`<script>
    export default {
        name: "about.vue"
    }
</script>`
if your editor not created.. 
**Add a property name**
to the the component like:
`<script>
    export default {
        name: "about"
    }
</script>`
