### ISSUE TITLE
help optimizing bundle size

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#1650]
I'm attempting to optimize my bundle size and off the bat, I noticed that the same component is always being added to every page bundle that it is used in. Shouldn't the common chunks plugin automatically take these out? 

https://ipfs.io/ipfs/QmVuYHkYpsmmThL15pdoen6cMfEV83RZbTCvkVSzo12Bpb

In the screenshot you can see that the same product-card and cabinet components are being loaded twice in the two pages. 

Please help! my app is like 8MB right now!

**Comment by uptownhr** [comment]
Is this the expected behavior? Do I need to manually add all my components into vendors for common chunks to take affect?

**Comment by pi0** [comment]
Hi @uptownhr. Currently you can use a workaround by using a plugin to include common parts into app chunk (common chunk automatically includes vendor not project source code)

**plugins/common.js**

```js
import '~/components/product-card'
```

**Comment by uptownhr** [comment]
@pi0 thanks you. I will do this for now :)

**Comment by uptownhr** [comment]
@pi0 I just tried implementing the plugins/common.js with my global components in there. No problem initially but strangely it is triggering a `vuex` do not mutate state error. I know for a fact that I am not mutating state outside commits. I also remove the common.js plugin and the error goes away. 

I'll try and reproduce this on a clean area without all my project dependencies and see if I can reproduce.

**Comment by awronski** [comment]
@uptownhr any feedback on the error problem?

**Comment by uptownhr** [comment]
@awronski many months later ... The problem was related to isolated area in our app that was using the store to pass around components :). Removing this seems to have resolved the issue for us.
