### ISSUE TITLE
How to use transitions in dynamic router?

### ISSUE THREAD

**Issue by turnerguo** [nuxt/nuxt.js#1651]
When I add `transition: 'page',` in _slug.vue, there is nothing happened, but works in static router, seems dynamic router can not work with it?
I'm just trying `nuxtjs.org` demo.

**Comment by vuchl** [comment]
can not reproduce your issue: I downloaded the [custom-routes](https://nuxtjs.org/examples/custom-routes) example and added the `/assets/main.css` file with the content from here: https://nuxtjs.org/examples/routes-transitions

i set the `transition` of `pages/users/_id.vue` to `'bounce'` and it works-

**Comment by Camzilla** [comment]
@vuchl That example doesn't have a dynamic route which is the problem here.

@turnerguo Think of the dynamic route as a re-usable component, for example a listing component. To modify those you need to set a key, try adding `:key="$route.params.slug"` to wrapping element and it should work!

**Comment by alexchopin** [comment]
Hi,
You need to add a key, this code should work (layouts/default.vue)
```html
<template>
  <nuxt :nuxtChildKey="routerViewKey"/>
</template>

<script>
export default {
  computed: {
    routerViewKey () {
      // If current route has children
      if (this.$route.matched.length > 1) {
        return compile(this.$route.matched[0].path)(this.$route.params)
      }
      return this.$route.fullPath.split('?')[0].split('#')[0]
    }
  },
}
</script>
```

**Comment by DaxChen** [comment]
@alexchopin what does the `compile` function do?

**Comment by vuchl** [comment]
@DaxChen https://github.com/nuxt/nuxt.js/blob/f5fa44d8aa8da987ac7e223dbf4101eebf666c5a/lib/app/utils.js#L206-L214
