### ISSUE TITLE
ssr loading other pages' js

### ISSUE THREAD

**Issue by JackAtlas** [nuxt/nuxt.js#1653]
Why ssr loading other pages' js?

For example:

1. I have `aaa/aaa.vue` besides `index.vue`.
2. `npm run build` and `npm start`.
3. Visit `localhost:3000` and see the index page loads `aaa.5533ed4181712d0a1331.js`.

Can anyone help me with these questions?
1. Why should it load other pages' js?
2. Will it make many request when there are many pages?
3. How to stop it from loading these js?

Thank you.

**Comment by fengjiel** [comment]
nuxt.config.js    add
```
render: {
        resourceHints: false,
    },
```
@JackAtlas

**Comment by Atinux** [comment]
@JackAtlas it's an intended behaviour, the JS is loaded only after the page is fully rendered on client-side, this is the `prefetch` meta tags, this is to avoid latency when switching to the next page.

You can disable this behaviour by setting `render.resourceHints: false` in your `nuxt.config.js` like in @fengjiel answer.
