### ISSUE TITLE
Nuxt.js problem, HELP!

### ISSUE THREAD

**Issue by TheDeveloperTom** [nuxt/nuxt.js#1655]
Hello guys, I have a problem, even problems. 

1. In my nuxt application, "npm run build" - takes about 14 minutes - I even can't imagine why (assets folder weights 500kb)
2. There is one more big problem, all applications components/layouts (event which aren't used) are loaded, when opening application. ( https://files.gitter.im/nuxt/nuxt.js/Npp9/image.png ) - I don't want to load 50 MB of components, and especially if they are not used.
3. Fresh installation of nuxt (when starting "npm start") again loads all existing components, but when I will open a page, it will load that page components one more time, it's the most strange...

**Comment by Atinux** [comment]
@TheDeveloperTom 

1. It may be due because of your computer performances
2. Disable `render.resourceHints` if you don't want this behaviour (https://nuxtjs.org/api/configuration-render#resourcehints) or use code-splitting with Vue & webpack
3. Same as 2

**Comment by TheDeveloperTom** [comment]
@Atinux really thank you!!! 

Also want you to advise me, why "npm run dev" - works fine, but "npm run build && npm run start" - Cannot read property 'middleware' of undefined.
