### ISSUE TITLE
Can I use images of WebP?

### ISSUE THREAD

**Issue by ArvinQi** [nuxt/nuxt.js#1656]
If I want to use WebP images, what can I do?

**Comment by vuchl** [comment]
you can extend the webpack config to use a dedicated loader for those files: https://github.com/tcoopman/image-webpack-loader

**Comment by ArvinQi** [comment]
OK, I got this. Build -> extend 'config.module.rules.push({/*webp loaders*/})'. ths

**Comment by silvio-e** [comment]
@ArvinQi @vuchl I also would like to use webp but don't have much experience with these configurations. Would you like to share more precisely how and where you solved that? Would appreciate it very much! Thanks a lot! :)

**Comment by ArvinQi** [comment]
@silvio-e Here is my code in nuxt.config.js.
```javascript
build: {
    extend(config, {
      isClient
    }) {
      config
        .module
        .rules
        .push({
          test: /\.(webp)$/i,
          loaders: [
            'file-loader?hash=sha512&digest=hex&name=[hash].[ext]'
          ]
        })   
     }
  },
```
