### ISSUE TITLE
Optimistic updates

### ISSUE THREAD

**Issue by trusktr** [nuxt/nuxt.js#1660]
Seems like the Nuxt pattern of using `asyncData` will make the component always fetch data every time the view will be rendered. Is there something like Meteor's "optimistic updates"?

**Comment by homerjam** [comment]
I'm using a [simple cache plugin](https://gist.github.com/homerjam/933336f19ff1302e7a8dd2c6784dd172) to wrap axios to fix this issue for myself.

**Comment by trusktr** [comment]
So that, for example, keeps a route's data cached for a given amount of time, so switching back and forth between two pages is almost instant, unless you navigate away for a while then come back?

What if the server has new data? In Meteor, the server can also push new data which can update the UI in response to server push.

**Comment by homerjam** [comment]
Yes, that's exactly how it works.

I think the short answer to your original question is "no". I think it's outside of the scope of nuxt to offer something like this. There may be a way to extend vuex to enable this, but as they've pointed out on [the meteor blog](https://blog.meteor.com/optimistic-ui-with-meteor-67b5a78c3fcf) it's not trivial!
