### ISSUE TITLE
I don't have any idea why SPA mode is not working

### ISSUE THREAD

**Issue by lingopalm** [nuxt/nuxt.js#1661]
I just installed nuxt.js starter template and built with mode: 'spa' option.
I uploaded to dist folder to my server but it keeps saying This page could not be found.
I also tried it at localhost but the result is same.

http://test.lingopalm.com/index.html
This is the URL where I uploaded the dist folder.
Can anyone help me to know what I did wrong...

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1486">#c1486</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
I just followed these steps and it works fine:

First, I init the `spa` project:
1. `vue init nuxt-community/starter-template spa`
2. `cd spa`
3. `npm install`
4. edit your `package.json` file and in scripts section: `"build-spa": "nuxt build -spa"`
4. `npm run build-spa`

Then I install a simple node server.js for test: 
5. `npm install http-server -g`
6. `cd dist`
7. `http-server .`

Finally, I open the url [http://localhost:8080/](url)

**Comment by pi0** [comment]
@lingopalm Are you hosting PHP on the same sub-domain too??

http://test.lingopalm.com

**Comment by lingopalm** [comment]
@NicoPennec  I will try this, thank you.
@pi0 yes I am hosting PHP on that server, can it be a problem? I thought it can be hosted on any environment..

**Comment by lingopalm** [comment]
I installed http-server and it works fine, thank you so much.
I didn't know I should not host php on the same server... I wish there were some guide lines about this...

**Comment by lingopalm** [comment]
nuxt-community/starter-template spa is working fine
but nuxt-community/express-template is not working it just says Request failed with status code 404
I think I have a long way to go to make this spa thing work...

**Comment by lingopalm** [comment]
Okay I found the reason. http://localhost:8080/ works but http://localhost:8080/index.html does not work.
Is there any way I can access index.html? Because I want to make it work at cordova and its main page is index.html

**Comment by vuchl** [comment]
Is there maybe some .htaccess stuff going on?

**Comment by lingopalm** [comment]
No. I just ran http-server which NicoPennec  mentioned. That is not an apache server.
It seems spa mode does not allow directly access the files and it has to be served.
Maybe there is no way to use generate mode... but the generate mode is not suitable for cordova because it basically does not allow dynamic route.

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
