### ISSUE TITLE
Get Authentication by Django POST API 

### ISSUE THREAD

**Issue by feedgit** [nuxt/nuxt.js#1663]
How can I get Authentication, Storage Sessions with Django API by POST?
This example https://nuxtjs.org/examples/auth-routes cant help me. It's logged in success but when reload page it not logged in anymore.

Action Store Login

`async login ({ commit }, { username, password }) {
        try {
          const { data } = await **axios.post('http://localhost:8000/api/v1/api-token-auth/login'**, { username, password })
          commit('SET_USER', data)
        } catch (error) {
          if (error.response && error.response.status === 401) {
            throw new Error('Bad credentials')
          }
          throw error
        }
      },`
ServerMiddleware auth.js
`router.post('/login', (req, res) => {
  if (req.body.username && req.body.username == req.body.password) {
    req.session.authUser = { username }
    return res.json({ username })
  }
  res.status(401).json({ message: 'Wrong username or Password. Please try again!' })
})`

Please help. Thanks in advance

**Comment by venugopalsundaram** [comment]
@congtoanle Can you share the store/index.js file? Have you added **nuxtServerInit** function properly

**Comment by congtoanle** [comment]
@venugopalsundaram My Store/Index.js:
`import Vue from 'vue'
import Vuex from 'vuex'
import axios from 'axios'
Vue.use(Vuex)

// Polyfill for window.fetch()
require('whatwg-fetch')

const store = () => {
  return new Vuex.Store({
    state: {
      authUser: null
    },

    mutations: {
      SET_USER: function (state, user) {
        state.authUser = user
      }
    },

    actions: {

      nuxtServerInit ({ commit }, { req }) {
        if (req.session && req.session.authUser) {
          commit('SET_USER', req.session.authUser)
        }
      },

      async login ({ commit }, { username, password }) {
        try {
          const { data } = await axios.post('/api/login', { username, password })
          commit('SET_USER', data)
          window.location.href = '/'
        } catch (error) {
          if (error.response && error.response.status === 401) {
            throw new Error('Bad credentials')
          }
          throw error
        }
      },

      logout ({ commit }) {
        return fetch('/api/logout', {
          // Send the client cookies to the server
          credentials: 'same-origin',
          method: 'POST'
        })
          .then(() => {
            commit('SET_USER', null)
          })
      },

      getAuthHeader () {
        return {
          'Authorization': 'Bearer ' + localStorage.getItem('access_token')
        }
      }

    }
  })
}

export default store
`

**Comment by venugopalsundaram** [comment]
Hi @congtoanle , I have some doubts.

1.while reloading what is the value state .You can get it from Vue Devtools.
![vuex](https://user-images.githubusercontent.com/31914152/30586224-e518ec6a-9d4c-11e7-92c3-669e6529d14f.png)

2.If state.authUser is null then the issue in store code.

**Comment by congtoanle** [comment]
@venugopalsundaram 
My Vue Devtools:
![image](https://user-images.githubusercontent.com/19923843/30589818-2d42470c-9d66-11e7-84b5-537030e11032.png)
When I F5 page, it haven't remained logged in anymore.

**Comment by venugopalsundaram** [comment]
@congtoanle  "_When I F5 page, it haven't remained logged in anymore._". After F5 page whether the **state** value turned into **null**?

**Comment by congtoanle** [comment]
Thank you @venugopalsundaram but I was success by using Token.

**Comment by congtoanle** [comment]
`nuxtServerInit ({ commit }, { req }) {
        try {
          const jwtCookie = req.headers.cookie.split(';').find(c => c.trim().startsWith('token='))
          if (jwtCookie) {
            let token = jwtCookie.split('=')[1]
            let payload = jwtDecode(token)
            let date = Date.now() / 1000
            if (payload.exp > date) {
              commit('SET_USER', payload)
              commit('SET_TOKEN', token)
              instance.defaults.baseURL = backendURL
            }
          }
        } catch (error) {
        }
      },

      async login ({ commit }, { username, password }) {
        try {
          const { data } = await axios.post('http://localhost:8000/api/v1/api-token-auth/login', { username, password })
          let payload = jwtDecode(data.token)
          Cookie.set('token', data.token)
          commit('SET_TOKEN', data.token)
          commit('SET_USER', payload)
          window.location.href = '/'
        } catch (error) {
          if (error.response && error.response.status === 401) {
            throw new Error('Bad credentials')
          }
          throw error
        }
      },`
