### ISSUE TITLE
Nuxt.js Bug, Help!

### ISSUE THREAD

**Issue by TheDeveloperTom** [nuxt/nuxt.js#1665]
Is there a reason why "npm run dev" - works fine, but "npm run build && npm run start" - produces 
 "Cannot read property 'middleware' of undefined".

I've spent already two days trying to find the problem, really hope on your help!!

**Comment by vuchl** [comment]
I just tried those steps:
```bash
vue init nuxt-community/starter-template
npm install
```

```javascript
// middleware/test-mw.js
export default (context) => {
  console.log('hello from index')
}

```

```vue
// pages/index.vue
export default {
  ...
  middleware: [
    'test-mw'
  ]
}
```

Both `npm run dev`and ǹpm run build && npm run start` work. Ubuntu 16.04 LTS 64Bit, NodeJS 8.5.0, npm 5.3.0.
