### ISSUE TITLE
asyncData called after calling error in middleware

### ISSUE THREAD

**Issue by KonstantinVlasov** [nuxt/nuxt.js#1667]
Hi guys!

Looks like it's really simple, but I don't find any info in the docs.

I have middleware for handling errors that can be in nuxtServerInit:
```javascript
export default ({store, error}) => {
  if (store.state.serverError) {
    error(store.state.serverError)
  }
}
```
**What I expect**
I thought that if I call error in middleware than Nuxt stop render matched layouts/pages and show Error page (I use simple custom layouts/error.vue template)

**What I got**
When I call error in middleware Nuxt show Error page, then continue to call asyncData of the matched page in the background. As result, I see the error page, but API server receives unnecessary calls.

How can I tell Nuxt to stop calling asyncData after calling error in the middleware?

**Comment by alexchopin** [comment]
Hi @KonstantinVlasov,
Have you tried with:
```js
export default ({store, error}) => {
  if (store.state.serverError) {
    return error(store.state.serverError)
  }
}
```

**Comment by KonstantinVlasov** [comment]
Hi! Yes sure, same result.

**Comment by ymatuhin** [comment]
Same problem, anything new about it?

**Comment by colmer** [comment]
The same

**Comment by Atinux** [comment]
Will be fixed in next release, sorry about this.

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error on middleware -> Don't call asyncData and show error page](https://trello.com/c/LQjFczUP/43-error-on-middleware-dont-call-asyncdata-and-show-error-page)

**Comment by KonstantinVlasov** [comment]
Awesome, thanks!
