### ISSUE TITLE
Question: What about URL query params?

### ISSUE THREAD

**Issue by mattdharmon** [nuxt/nuxt.js#167]
Is this already implemented, if so, how do I get them into the fetch operation? Would be useful for pagination/filtering data for when somebody bookmarks and shares a page.

**Comment by alexchopin** [comment]
You can access through the context with properties `params` and `query`.
[Documentation](https://nuxtjs.org/api/pages-fetch)

**Comment by mattdharmon** [comment]
Thanks, the documentation mentions nothing about the query param as part of the context, the context page in the documentation routes to a 404.

**Comment by Atinux** [comment]
[Updated documentation link](https://nuxtjs.org/api/#context)
