### ISSUE TITLE
NuxtJS content hidden when cloudflare is active

### ISSUE THREAD

**Issue by mikejavier** [nuxt/nuxt.js#1671]
Hi,

I create my page using NuxtJS and publish in my GH Pages with generate command. Works fine !
But if I activate cloudflare part of the content is hidden.

OBS. Don't use router, vuex etc. Only 1 page with components.
https://github.com/mikejavier/mikejavier.github.io/tree/new_version

Has anyone ever experienced this ?

**Comment by alexchopin** [comment]
Hi @mikejavier,
Could you check up if your CloudFlare setup doesn't do some changes to caching file (transform JS files for example)?

**Comment by mikejavier** [comment]
Hi @alexchopin,

I've disabled all cache options. 
the curious thing that only happens in the GH user page. (username.github.io)

https://michaelsantillan.com/
https://michaelsantillan.com/cloudflare_teste/

**Comment by qm3ster** [comment]
For me, the two pages you linked behave identically.

**Comment by mikejavier** [comment]
@qm3ster Because cloudflare is disabled. 
Until I did not find the solution, I would rather quit without ssl than being with the broken site

**Comment by qm3ster** [comment]
It fails even when using CloudFlare with a GRAY cloud?

**Comment by mikejavier** [comment]
@qm3ster no, only green cloud.

**Comment by qm3ster** [comment]
[how you doin lil mama? lemme whisper in your ear](https://gitter.im/qm3ster)

**Comment by dplaza** [comment]
the same here. Did you find a solution @mikejavier?

**Comment by mikejavier** [comment]
@dplaza the last time I tried I did not solve it, since then I did not have free time to continue solving the problem.

**Comment by atmar** [comment]
Try disabling "Auto Minify" for everything

**Comment by mikejavier** [comment]
I've tried this and everything that has a direct relation to the assets

**Comment by andy265** [comment]
Try to deactivate "Email Address Obfuscation" in the "Scrape Shield" tab.

**Comment by mikejavier** [comment]
@andy265, thank you so much man. I still do not believe that this option was giving me a headache. Can mark it as fix, thanks to all who tried to help.

**Comment by qm3ster** [comment]
Oh wow :open_mouth:
How do you think it was breaking it?

**Comment by mikejavier** [comment]
the blocks that were being hidden contained my email. Then it is likely that cloudflare would remove the js code then render the page.

living and learning

thank you guys

**Comment by qm3ster** [comment]
@alexchopin This seems closeable.
@mikejavier did you find a way to complain to cloudflare?
