### ISSUE TITLE
Howto setup Proxytable in Nuxt?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1675]
For eaxample, I have such code on Dev, which doesn't work in Prod obv

```
createArticle () {
      console.log(this.article)
      axios.post('http://localhost:7777/articles/', this.article)
        .then((res) => {
          this.message = res.data
        })
    }
```

Is there any option like this  - https://vuejs-templates.github.io/webpack/proxy.html

**Comment by iamdubx** [comment]
How to fix this in Prod?

![screenshot from 2017-09-17 09-58-58](https://user-images.githubusercontent.com/30086515/30521646-eb2ba006-9b90-11e7-9951-bd90fd3729bc.png)

**Comment by pi0** [comment]
Hi. You can use [proxy module](https://github.com/nuxt-community/modules/tree/master/modules/proxy) for that :)
