### ISSUE TITLE
the hashcode in nuxt build is not the same with the hashcode in nuxt generate

### ISSUE THREAD

**Issue by hskww** [nuxt/nuxt.js#1677]
i want use the static resources in the 'dist' folder with nginx, and use server render by nuxt build &nuxt  start; but the hashcodes in js file or css file is not the same ,and the server page work error.

**Comment by alexchopin** [comment]
Hi @hskww, 
Can you explain more about your issue?

**Comment by hskww** [comment]
the filename of js files in 'dist' folder is different from in '.nuxt/dist' folder,  if i  use the static resources in the 'dist' folder with nginx， the server page work error, because of the js file return '404'!
so i want to exec a new command to do the things in 'nuxt generate' and 'nuxt build' , and only  generate  hashcode by webpack once, get the same hashcode in js files.
