### ISSUE TITLE
How to get slashes in routes working without dynamic nesting

### ISSUE THREAD

**Issue by JLKM** [nuxt/nuxt.js#1680]
Please. Anyone. Just one working example of how to route urls with more than one slash (for the route itself). I spent a Sunday on this but no luck.

I'm using Nuxt as a central part in building a customized and server side rendered MEVN stack (the `N` might as well stand for `Nuxt`).

For the sake of the future I would really like to keep a url structure with `domain/route/category/subcategory/slug` - the name of the controlling route being `permlink`.

[Dynamic nested routes](https://nuxtjs.org/guide/routing#dynamic-nested-routes) haven't been any success, though.

As an alternative some hacks with `encodeURIComponent(someurl)` and `decodeURIComponent(someurl)` have been tested. This seems closer, but still no breakthrough. Perhaps it's just a matter of putting the `encodes` and `decodes` right.

*Works:* http://localhost:8085/permlink/tyskland-baenkesaet-test-med-tags-jan
*Works:* http://localhost:8085/permlink/england%2Fjord%2Ftester-med-fast-ord-testord
*404:* http://localhost:8085/permlink/england/jord/tester-med-fast-ord-testord
*404:* http://localhost:8085/permlink/udvandrerne/baenke-drastisk-udrensning-fremhaever-vigtigt

Then I've tested the `extendRoutes` way. After the best of my abilities I've sucked a lot up up from [1592](https://github.com/nuxt/nuxt.js/issues/1592), [1542](https://github.com/nuxt/nuxt.js/issues/1542), [1234](https://github.com/nuxt/nuxt.js/issues/1234), [1032](https://github.com/nuxt/nuxt.js/issues/1032), [275](https://github.com/nuxt/nuxt.js/issues/275), [112](https://github.com/nuxt/nuxt.js/issues/112) among others.

Only result is still `404`, when it comes to the urls including slashes after `/permlink`. Have also tested without the dynamic component `\pages\permlink\_permlink.vue` to give "more room" for the extended route - but same same.

Please take a look at one of all my tested configurations in `nuxt.config.js`:
```
    router: {
        extendRoutes (routes, resolve) {
          routes.push({
            name: 'permlinkindex',
            path: '*',
            component: resolve(__dirname, '~/pages/permlinkindex.vue')
          })
        }
      },
```

Is this simply caused by [a bug with backslashes in windows](https://github.com/nuxt/nuxt.js/issues/299)?

My setup:
- Windows 10
- NPM 5.3.0
- Node 8.1.2
- Nuxt 1.0.0-rc11

Any help - or just a little push - would be much appreciated.

**Comment by alexchopin** [comment]
Hi @JLKM,
Have you tried with the page name: `_.vue` ?
It creates a route with the path as `*` and the name is `all`.

**Comment by JLKM** [comment]
Thanks a lot for your fast advice, which I've tested right away - the best I could.
Unfortunately I'm not quite aware, where to put the `_.vue` file. So I tested various locations:

### 1. In permlink-folder hierachy
*Files:*
F:\data\fullstack\mean\pages\permlink.vue
F:\data\fullstack\mean\pages\permlink\_permlink.vue
F:\data\fullstack\mean\pages\permlink\_\_.vue
F:\data\fullstack\mean\pages\permlink\_\_\_.vue

_F:\data\fullstack\mean\.nuxt\router.js:_
```
		{
			path: "/permlink",
			component: _62527d7c,
			name: "permlink",
			children: [
				{
					path: ":?/:?",
					component: _d33c5bc8,
					name: "permlink--",
					children: [
						{
							path: ":?",
							component: _753511f3,
							name: "permlink---"
						}
					]
				},
				{
					path: ":permlink?",
					component: _70a2b506,
					name: "permlink-permlink"
				}
			]
		},
```

*Result:*	
Bingo (0 subfolders): http://localhost:8085/permlink/tyskland-baenkesaet-test-med-tags-jan
Bingo (0 subfolders): http://localhost:8085/permlink/udvandrerne%2Fgenerelt%2Foverskrift-ordet-noget-tekst-skriver
404 (2 subfolders): http://localhost:8085/permlink/udvandrerne/generelt/overskrift-ordet-noget-tekst-skriver

### 2. Without hierarchy
*Files:*
F:\data\fullstack\mean\pages\permlink.vue
F:\data\fullstack\mean\pages\permlink\_.vue

_F:\data\fullstack\mean\.nuxt\router.js:_

```
		{
			path: "/permlink",
			component: _62527d7c,
			name: "permlink",
			children: [
				{
					path: ":?",
					component: _312c2a93,
					name: "permlink-"
				}
			]
		},
```		

*Result:*
404 (0 subfolders): http://localhost:8085/permlink/tyskland-baenkesaet-test-med-tags-jan
404 (0 subfolders): http://localhost:8085/permlink/udvandrerne%2Fgenerelt%2Foverskrift-ordet-noget-tekst-skriver
404 (2 subfolders): http://localhost:8085/permlink/udvandrerne/generelt/overskrift-ordet-noget-tekst-skriver

### 3. The radical solution
*Only one file at the `/pages/`-root:*
F:\data\fullstack\mean\pages\_.vue

_F:\data\fullstack\mean\.nuxt\router.js:_
		{
			path: "/:",
			component: _d096e886
		}
```

*Result:*	
404 (0 subfolders): http://localhost:8085/permlink/tyskland-baenkesaet-test-med-tags-jan
404 (0 subfolders): http://localhost:8085/permlink/udvandrerne%2Fgenerelt%2Foverskrift-ordet-noget-tekst-skriver
404 (2 subfolders): http://localhost:8085/permlink/udvandrerne/generelt/overskrift-ordet-noget-tekst-skriver
```
As you see: No `*` in the generated `routes.js`.

What did I miss? Is it something in my setup?

**Comment by alexchopin** [comment]
`pages/permalink/_.vue`should be enough in your case.

**Comment by Norbz** [comment]
Hello there.

I am trying to build a website where the route matches a json file on my server. Adding a JSON File would "create" another page.

Let say for instance that going to the page /rub1/article1 will try to load the json file "article1.json" in the folder "rub1" in the static folder.

Tried both solution with _.vue and extendRoutes.
Both solutions works great until I try to get a json file that doesn't exists.

Let say a user tries to load rub1/article666 that doesn't exists
The page calls the json file, which doesn't exists, but the route is being catched by the  nuxt "catchall" route, proceed to the same vue component, that now tries to load the article666.json.json according to the route, which doesn't exists... and so on

Crashes the server everytimes.

I struggle to find a way to prevent the router to loop more than once.
Any ideas ?

Thanks
