### ISSUE TITLE
NUXT + Firebase Authentication

### ISSUE THREAD

**Issue by lgs** [nuxt/nuxt.js#1681]
Does anybody have a firebase authentication boilerplate repo example like [Auth0 here](https://github.com/nuxt/example-auth0) ?

**Comment by vuchl** [comment]
not exactly what you are looking for but look around here:
firebase modlue for nuxt: https://github.com/nuxt-community/modules/tree/master/modules/firebase
firebase example: https://gist.github.com/stursby/73d85379717f22cc52fe3993408da0dd from here: https://github.com/nuxt/nuxt.js/issues/312

**Comment by lukasborawski** [comment]
@lgs what u need?
