### ISSUE TITLE
* fs in ./node_modules/lokijs/src/lokijs.js

### ISSUE THREAD

**Issue by fuxiocteract** [nuxt/nuxt.js#1682]
how to config nuxt.config.js to include node { fs: "empty" }? and work with lokijs?

**Comment by cesasol** [comment]
To have a ssr/client model with indexeddb I use [pouchdb](https://pouchdb.com/) it automaticly loads the required node/client libraries needed

**Comment by guillermovs** [comment]
I'm also getting the same error when importing `mysql` on the server either inside `asyncData({isServer})`, in the `fetch({})` method, or as `serverMiddleware`.

```
This dependency was not found:
fs in ./~/mysql/lib/protocol/sequences/Query.js
```

I would like to be able to query a database and preload the data object (or Vuex store) before it hits the client, so no additional Axios requests are needed.

**Comment by calebanthony** [comment]
@guillermovs 

> I would like to be able to query a database and preload the data object (or Vuex store) before it hits the client

[Use nuxtServerInit](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action)

**Comment by bskimball** [comment]
to add to what @calebanthony is saying, you can also check if the process is server side inside nuxtServerInit

for example
```javascript
...
actions: {
    nuxtServerInit () {
        if (process.server) {
           // perform some server side only function 
        }
    }
}
...
```
