### ISSUE TITLE
<nuxt-link /> doesn't support click events

### ISSUE THREAD

**Issue by matthew-dean** [nuxt/nuxt.js#1686]
I discovered that `<nuxt-link />` doesn't delegate click events to an anchor like one would expect. I wrote this fully expecting it to work:

`<nuxt-link @click="closeMenu" to="/register">Register</nuxt-link>`

However, no click event is fired when clicking the link. Normally what I do with components that essentially shadow an element like `<a />` is capture and raise events to the parent component. Vue.js makes this fairly straightforward.

**Comment by KonstantinVlasov** [comment]
just use `@click.native`
