### ISSUE TITLE
Global error handler?

### ISSUE THREAD

**Issue by Meeeeow** [nuxt/nuxt.js#1688]
I'm using nuxt.js in our production environment, but i can't find any document about how to capture and analyze exceptions during running `asyncData` or `nuxtServerInit`.

I suggest to add options like `Vue.config.errorHandler` to nuxt.config.js, this will allow us capture exception, inject request id into response

**Comment by piyushchauhan2011** [comment]
Why not pull out the exception handling code in Vuex store. You can use `try, catch` block to capture and trigger error handling from store. As for routing, `vue-router` provides changing route from store which you can trigger after receiving exception. @Meeeeow

**Comment by Meeeeow** [comment]
@piyushchauhan2011 Huge `try...catch` is not a good solution. Change route? I don't need jump to another page after exception, but i need a hook to receive exceptions from **`asyncData`**, which not control by `Vue.config.errorHandle`.
Nuxt print exception to console rather than throw it, so there is not way to send exceptions to third part service such as Sentry

**Comment by piyushchauhan2011** [comment]
ahh like a middleware than can send the thrown exception to `bugsnag` or `sentry`. I like the idea 👍 @Meeeeow

**Comment by DiederikvandenB** [comment]
So I am looking in to this too, indeed in order to send error data to sentry. I came across the following `errorHandler` in the code: https://github.com/nuxt/nuxt.js/blob/dev/lib/core/nuxt.js#L100

Should hooking in to this solve this? And if so, how do I do this?

**Comment by DiederikvandenB** [comment]
I dove a bit deeper in the code and found the problem. Nuxt allows us to register custom server middleware, but this gets loaded *before* Nuxt's own middleware. See: https://github.com/nuxt/nuxt.js/blob/75350cdd78d17e565b6c58d6c1aaa00c5146cbae/lib/core/renderer.js#L277

The Connect docs explain:
> When a middleware passes an error to next, the app will proceed to look for the error middleware that was declared after that middleware and invoke it, skipping any error middleware above that middleware and any non-error middleware below.

Meaning that if we define an error middleware (by requesting the `err` object in addition to the `req, res, next`) this middleware is injected before the error actually appears, rendering the function useless.

**Comment by DiederikvandenB** [comment]
Using the Nuxt Modules I was able to get Sentry working. Check [this gist](https://gist.github.com/DiederikvandenB/d86c6cb1122f8c09fb15895111875c34).

You will want to add the `sentry.js` and `sentry-client.js` files to the `modules` directory, and then add the module to your `nuxt.config.js` using the correct settings.

A quick explanation what this code does. As I explained in the comment above, the problem is that we cannot add our own error handling because it's loaded before Nuxt's own middleware. What I did is 'backup' the original `nuxtErrorMiddleware`, then I overwrite it with the middleware that actually loads Sentry, and then I execute the original `nuxtErrorMiddleware` again, so we see the nicely printed error.

**Comment by Atinux** [comment]
Wow this is awesome @DiederikvandenB 

I would love to see `nuxt-sentry` module, would you be ok to create it on [nuxt-community](https://github.com/nuxt-community)?

We have a starter template for a module to get you started quickly: https://github.com/nuxt-community/module-template

**Comment by iamdubx** [comment]
I don't understand why this issue is closed? I don't want to use Sentry. How to handle errors in Nuxt? This is so confusing. I have error that Error template is not catching. You guys can explain how to handle it, please?

**Comment by DiederikvandenB** [comment]
While I agree with the fact that it would be great to have a more straightforward way to handle errors, or maybe better documentation regarding this subject, but the answer to your question is already posted above, @iamdubx.

You could either check out my gist, or my module, which you can find here: https://github.com/nuxt-community/sentry-module. If you do not want to use Sentry that is of course perfectly fine. You can still use the module, specifically [this file](https://github.com/nuxt-community/sentry-module/blob/master/lib/sentry.js). Just remove all the references to Sentry/Raven and add your own error handler on what is now rule number #53. Good luck.

**Comment by DualWield** [comment]
I don't understand why this issue is closed? I also want to know how to handle global errors in Nuxt .

**Comment by DiederikvandenB** [comment]
@DualWield Check [this](https://github.com/nuxt/nuxt.js/pull/2703) out.

**Comment by DualWield** [comment]
@DiederikvandenB Thank you. Yes, it seems that can solve this problem.But I dont' know how to (where to) hook the errorMiddleware. Is there something in the document ?

**Comment by DiederikvandenB** [comment]
Check these [two lines](https://github.com/nuxt-community/sentry-module/blob/master/lib/sentry.js#L54-L55) and [this example](https://nuxtjs.org/examples/plugins/).

Basically what you need to do is create a plugin which hooks on to the `render:errorMiddleware`. Good luck =).

@Atinux, would you appreciate a PR for the docs in which I explain the errorMiddleware hook?

**Comment by Atinux** [comment]
I will more than appreciate @DiederikvandenB :)

**Comment by DiederikvandenB** [comment]
In that case I'll have a look at it tonight!

**Comment by nicroto** [comment]
Nuxt.js is great.

A single "_check how this project does it_" line within the API docs, though, is not a good documentation.
Please, consider an example within the docs of the (supposedly) simple issue of _Handling Errors in SSR_, which doesn't have the inherent distraction (and over-complication) of trying to distil it from a whole project.

Thanks for working on this issue.

**Comment by canyoudev** [comment]
You guys are rock!!! Just letting you know, sorry for flood.
