### ISSUE TITLE
Not rendering CSS in code

### ISSUE THREAD

**Issue by feedgit** [nuxt/nuxt.js#1689]
I want to just use .css file in <head></head (<link rel="stylesheet" type="text/css")> in stead of rendering CSS like this:
![image](https://user-images.githubusercontent.com/19923843/30590893-cc6db16e-9d6a-11e7-8ab9-fa31c92553a0.png)
How can I do this?

**Comment by vuchl** [comment]
since nuxt uses [`vue-meta`](https://github.com/declandewet/vue-meta) you can use the [`head()`](https://nuxtjs.org/api/pages-head) method and in there use the [`link property`](https://github.com/declandewet/vue-meta#link-object).

**Comment by congtoanle** [comment]
how about applying in all webpage instead of each pages

**Comment by vuchl** [comment]
Put it in your nuxt.config.js
```javascript
/* nuxt.config.js */
module.exports = {
  head: {
    titleTemplate: '%s - Nuxt.js',
    meta: [
      link: { rel: 'stylesheet', href: '/css/index.css' }
    ]
  }
}
```

**Comment by congtoanle** [comment]
link: { rel: 'stylesheet', href: '/assets/index.css' }
I got 404 when access http://localhost:3000/assets/rocket.css. How define path, pro?

**Comment by vuchl** [comment]
you reference an index.css but want to get rocket.css...

**Comment by congtoanle** [comment]
@vuchl Sorry I made a mistake, I would to say getting 404 when access http://localhost:3000/assets/index.css

**Comment by vuchl** [comment]
try `metaInfo` instead of `meta`

**Comment by congtoanle** [comment]
@vuchl Got error too :(

**Comment by vuchl** [comment]
Ok. Put the `index.css` file in the `assets` folder and in the `nuxt.config.js` setup the following:
```javascript
module.exports {
  head: {
    link: [
      { rel: 'stylesheet', href: '/index.css' }
    ]
  }
}
```
it would also work to put it in the `static` folder

**Comment by congtoanle** [comment]
@vuchl  If I put file index.css into folder static. It is success but I want to put file .css in folder assets. Your way is failed. I think need to define Folder Path.

**Comment by congtoanle** [comment]
@vuchl If do this, CSS will be rendered as normal.
I think need to define Folder Assests Path like folder static.

**Comment by alexchopin** [comment]
You should use the `static` folder in this case.
