### ISSUE TITLE
global fetch

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/nuxt.js#169]
see https://github.com/nuxt/docs/issues/25

**Comment by alexchopin** [comment]
I think the `nuxtServerInit()` function is the global fetch you are talking about.
[Documentation](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action)

**Comment by gbezyuk** [comment]
@alexchopin do you mean I need to specify a specific action for each store?

**Comment by alexchopin** [comment]
Why for each store? 
Sorry but I'm not sure to understand, can you explain more about what you are trying to do?

**Comment by gbezyuk** [comment]
I've got some modular stores. Let's say, I have `contacts` store with contact information and `fetch_contacts` action specified, and `vehicles` store with two actions, `fetch_vehicle_types` and `fetch_brands`. Should I add `nuxtServerInit` to each of this stores, calling single action in the first one and chaining two actions in the second one?

**Comment by alexchopin** [comment]
If you use one Vuex Store with modules (contacts and vehicles), you can call once `nuxtServerInit` which will call actions for each modules (like fetch_contacts, fetch_vehicle_types, etc)

**Comment by Atinux** [comment]
Hi @gbezyuk 

ˋnuxtServerInit` is called only in the global module (index), you have to chain your module actions in nuxtServerInit

**Comment by gbezyuk** [comment]
@Atinux, @alexchopin — thank you for assistance!

**Comment by gbezyuk** [comment]
One final question. Consider I have this `store/index.js`:

```javascript
import { dispatch } from 'vuex'

export const state = {
}

export const mutations = {
}

export const actions = {
  nuxtServerInit ({ commit }, { req }) {
    return Promise.all([
        displatch('vehicles/brand_fetch_all')
    ])
  }
}
```

Obviously, I can't use `dispatch` straight away, I need `store.dispatch`. But using modular stores, I don't export it and thus I don't have it in the scope. What should I do?

**Comment by gbezyuk** [comment]
Oh, I'm sorry, it was a stupid question. Just saw `{ commit }` standing for decomposed `store`.

**Comment by Atinux** [comment]
```js
export const actions = {
  nuxtServerInit ({ dispatch }, { req }) {
    return Promise.all([
        dispatch('vehicles/brand_fetch_all')
    ])
  }
}
```

No worries @gbezyuk I had some difficulties as well with the ES6 syntax at the beginning :)

**Comment by CKGrafico** [comment]
Tip for people using modules

index.ts
```
export const modules = {
    [generator.name]: generator,
    [serviceworker.name]: serviceworker,
    [i18n.name]: i18n
};

export type RootState = typeof modules;

// Call to nuxtServerInit of all the modules
export const actions: ActionTree<{}, RootState> = {
    async nuxtServerInit({ dispatch }) {
        for (const key in modules) {
            const module = modules[key];
            if (module.actions.nuxtServerInit) {
                dispatch(`${key}/nuxtServerInit`);
            }
        }
    },
};
```

**Comment by josephahern** [comment]
How would I implement given the module structure?

My index.js currently looks as follows and I'm lookin to dispatch event called 'FETCH_POSTS' in the /module/blog.js : 

`import Vuex from 'vuex'
import blog from './modules/blog'
import users from './modules/users'

const debug = process.env.NODE_ENV !== 'production'

const createStore = function () {
  return new Vuex.Store({
    modules: {
      blog,
      users
    },
    strict: debug
  })
}

export default createStore
`
