### ISSUE TITLE
Issue in Loading Vue Slick

### ISSUE THREAD

**Issue by renztoygwapo** [nuxt/nuxt.js#1692]
Hello I've got an issue in loading vue slick in nuxt see screenshot. there is no error console and Just import the vue slick don;t know how to fix it, 

![image](https://user-images.githubusercontent.com/4898681/30637079-f47c1910-9e29-11e7-80c1-c6d70cff6537.png)

**Comment by PierreRambaud** [comment]
Hi,

Vue-slick isn't compatible with ssr.

```
    let Slick = null;
    if (process.browser) {
        /* eslint-disable global-require */
        Slick = require('vue-slick').default;
        /* eslint-enable global-require */
    }
```

After you will be able to add it in component dependency.

Regards

**Comment by renztoygwapo** [comment]
where Do I add this one ?

**Comment by renztoygwapo** [comment]
I added this in my index.vue script but still not working. the same error
![image](https://user-images.githubusercontent.com/4898681/30642057-dd9696fa-9e3b-11e7-9616-af9757754b54.png)
![image](https://user-images.githubusercontent.com/4898681/30642069-e7fe345e-9e3b-11e7-86a6-d840bf54877a.png)

**Comment by PierreRambaud** [comment]
Just try it on my project, if I remove `process.browser` I have exactly the same error as you. How do you use Slick ?

**Comment by christophwolff** [comment]
maybe you want to give https://surmon-china.github.io/vue-awesome-swiper/ a try. there is even an example for nuxt. (https://github.com/surmon-china/vue-awesome-swiper/tree/master/nuxt-ssr-example)

**Comment by Atinux** [comment]
Hi!

I made a PR to make it work with Nuxt.js: https://github.com/staskjs/vue-slick/pull/43/files

We are working on a solution to make the npm modules which are using a vue file as `main` to work fine with Nuxt.js (https://github.com/staskjs/vue-slick/blob/master/package.json#L5).

In the meantime, to make `vue-slick` works with Nuxt.js, you need to tell nuxt.js to load the module into the server bundle, in your `nuxt.config.js`:

```js
build: {
    extend (config, { isServer }) {
      if (isServer) {
        config.externals = [
          require('webpack-node-externals')({
            whitelist: [/^vue-slick/]
          })
        ]
      }
    }
}
```

Then, you can use it into your pages like this for example:
```vue
<template>
	<slick ref="slick" style="width: 200px;height: 100px;">
		<a href="http://placehold.it/200x100"><img src="http://placehold.it/200x100" alt=""></a>
		<a href="http://placehold.it/200x100"><img src="http://placehold.it/200x100" alt=""></a>
		<a href="http://placehold.it/200x100"><img src="http://placehold.it/200x100" alt=""></a>
		<a href="http://placehold.it/200x100"><img src="http://placehold.it/200x100" alt=""></a>
		<a href="http://placehold.it/200x100"><img src="http://placehold.it/200x100" alt=""></a>
	</slick>
</template>

<script>
import Slick from 'vue-slick'

export default {
	components: {
		Slick
	}
}
</script>

<style>
@import 'slick-carousel/slick/slick.css';
</style>
```

Or with a plugin `plugins/slick.js`:
```js
import Vue from 'vue'
import Slick from 'vue-slick'
import '~/node_modules/slick-carousel/slick/slick.css'

Vue.component('slick', Slick)
```

`nuxt.config.js`:
```js
plugins: ['~/plugins/slick']
```

**Comment by PierreRambaud** [comment]
Thanks a lot @Atinux  ;)

**Comment by applecat** [comment]
Thanks @Atinux, it really works!

But I have little addition. In my case, after changes in `nuxt.config.js` my css styles won't build:
```css: ['tachyons/css/tachyons.min.css', '~assets/css/main.css'],```

So I have this error:
```
Nuxt.js Error:
/Users/Projects/node_modules/tachyons/css/tachyons.min.css:2
/*! normalize.css v7.0.0 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,footer,header,nav,section{display:block}h1{font-size:2em;margin:.67em 0}figcaption,figure,main{display:block}figure{margin:1em 40px}hr{box-sizing:content-box;height:0;overflow:visible}pre{font-family:monospace,monospace;font-size:1em}a{background-color:transparent;-webkit-text-decoration-skip:objects}abbr[title]{border-bottom:none;text-decoration:underline;text-decoration:underline dotted}b,strong{font-weight:inherit;font-weight:bolder}code,kbd,samp{font-family:monospace,monospace;font-size:1em}dfn{font-style:italic}mark{background-color:#ff0;color:#000}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sub{bottom:-.25em}sup{top:-.5em}audio,video{display:inline-block}audio:not([controls]){displ

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at r (/Users/ProjectsJS/node_modules/vue-server-renderer/build.js:5812:16)
    at Object.<anonymous> (webpack:/external "tachyons/css/tachyons.min.css":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 8a23e544233c6fab0df5:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:1752:88)
    at __webpack_require__ (webpack:/webpack/bootstrap 8a23e544233c6fab0df5:25:0)
    at Object.<anonymous> (.nuxt/App.vue:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 8a23e544233c6fab0df5:25:0)
```

It solves by changing from assign (=) to addition (+=) to `config.externals`:
```
build: {
    extend (config, { isServer }) {
      if (isServer) {
        config.externals += [
          require('webpack-node-externals')({
            whitelist: [/^vue-slick/]
          })
        ]
      }
    }
}
```
Hope that helps somebody.

**Comment by amrshakya** [comment]
@Atinux i did the same thing that you mentioned but it gives me the Cannot read the property 'middleware' of undefined.

**Comment by trokelado** [comment]
Thanks @Atinux, it works fine for vue-pdf but not for vue-video-player ! any idea?

**Comment by bok04** [comment]
Finding this an issue again after upgrading to Nuxt Version 2. Would perfect before. Is a tweak needed to this bit of code to make it work with the latest Nuxt?

`      if (process.server) {
        config.externals = [
          require('webpack-node-externals')({
            whitelist: [/^vue-slick/]
          })
        ]
      }`

**Comment by aldarund** [comment]
@bok04 try
``` build: { 
   transpile: ['vue-slick']```

**Comment by bltzrrr** [comment]
> @bok04 try
> 
> ```
>  build: { 
>    transpile: ['vue-slick']     
> ```

This seems to do the trick after upgrading to Nuxt 2

**Comment by bok04** [comment]
@bltzrrr thank you that worked great 👍
