### ISSUE TITLE
Problem: Re-compile, re-render template component with data in v-html 

### ISSUE THREAD

**Issue by kajcula** [nuxt/nuxt.js#1694]
Hi, I need a help. I try put some data from API like this:

```
model: {
content: {
rendered: '<silentbox-group>
    <silentbox-item src="http://data.whicdn.com/images/71898812/large.jpg" autoplay="true" description="My very custom message">Item one</silentbox-item>
    <silentbox-item src="http://data.whicdn.com/images/71898812/large.jpg">Item two</silentbox-item>
    <silentbox-item src="http://data.whicdn.com/images/71898812/large.jpg">Item three</silentbox-item>
</silentbox-group>'
}
}
```

o thev Nuxt component template:

`<div class="post-page__content" v-html="model.content.rendered"></div>`

and I register component like this: 

```
  import PostAuthor from '../PostAuthor.vue'
  import Comments from '../Comments.vue'
  import VueSilentbox from 'vue-silentbox'
  export default {
    props: {
      model: {
        required: true
      },
      comments: ''
    },
    components: {
      PostAuthor,
      Comments,
      VueSilentbox
    }
}
```
Nuxt put data like HTML, but plugin template not run.. 
How can I re-compile template to use plugin component in v-html ?

**Comment by vuchl** [comment]
from https://vuejs.org/v2/api/#v-html:
> Updates the element’s innerHTML. Note that the contents are inserted as plain HTML - they will not be compiled as Vue templates. If you find yourself trying to compose templates using v-html, try to rethink the solution by using components instead.

Seems like you try to do what is not supported.
