### ISSUE TITLE
Dynamic Routes generates routes for non existent endpoints

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1696]
Hi. 

I have such setup.

![setup](https://user-images.githubusercontent.com/30086515/30671333-5e333f00-9e34-11e7-94d2-ca74896bc61b.png)

First I thought everything fine

![ok](https://user-images.githubusercontent.com/30086515/30671362-846f4402-9e34-11e7-9a10-354a9208f115.png)

But then I notice that Nuxt generates routes for any value and doesn't return Error

![error](https://user-images.githubusercontent.com/30086515/30671396-ad1a37a4-9e34-11e7-8156-81a2e3b56ec0.png)

This endpoint `moooooney` doesn't exist of course. And If I go to this route I got an error like it should:

![404](https://user-images.githubusercontent.com/30086515/30671529-6c0f8182-9e35-11e7-9fe7-4d96c24bec47.png)

How to setup everything, so Nuxt understand, that to show only the data that exist?

This is my `articles/_section/index.vue` file

```js
asyncData ({ req, params, error }) {
    return axios.get(`${process.env.baseUrl}/api/articles/${params.section}`)
      .then((res) => {
        return { articles: res.data }
      })
      .catch(() => {
        error({ statusCode: 404, message: 'Section not found' })
      })
  }
```

This is my `articles/_section/_slug.vue` file

```js
asyncData ({ req, params, error }) {
    return axios.get(`${process.env.baseUrl}/api/articles/${params.section}/${params.slug}`)
      .then((res) => {
        return { article: res.data }
      })
      .catch(() => {
        error({ statusCode: 404, message: 'Pooooost not found' })
      })
  }
```

I have only 5 sections in my API data.

**Comment by vuchl** [comment]
since you get to see an article it means that the 
```javascript
axios.get(`${process.env.baseUrl}/api/articles/${params.section}/${params.slug}`)
```
returns an article. are you sure your backend is checking the article to be in the section?

**Comment by iamdubx** [comment]
@vuchl looks like I am not

```js
exports.getArticleBySlug = (req, res, next) => {
  Article.findOne({slug: req.params.slug})
    .then((article) => {
      if (!article) {
        return res.status(404).json({
          message: 'Article doesn\'t exist'
        })
      }
      return res.status(200).json(article)
    })
    .catch((err) => {
      return next(err)
    })
}
```

**Comment by iamdubx** [comment]
This is great. Fix was so easy. Thanks @vuchl 

```js
exports.getArticleBySlug = (req, res, next) => {
  Article.findOne({section: req.params.section, slug: req.params.slug})
    .then((article) => {
      if (!article) {
        return res.status(404).json({
          message: 'Article doesn\'t exist'
        })
      }
      return res.status(200).json(article)
    })
    .catch((err) => {
      return next(err)
    })
}
```
