### ISSUE TITLE
Support symbol link directory in routes generating

### ISSUE THREAD

**Issue by CrazyBills** [nuxt/nuxt.js#1699]
It's better if nuxt can parse all the files in symbol link directory,
just add the options {symlinks: true} in /lib/builder/builder.js, like this

``      const files = await glob('pages/**/*.vue', { cwd: this.options.srcDir,symlinks:true })``

**Comment by vuchl** [comment]
Actually [`symlinks` is an array of symlinks](https://github.com/isaacs/node-glob/blob/f65f9eb7eda113528c5257b58fac4ca685ee6c4f/README.md#options). What you would want to use if you want to follow symlinks is the `follow` option.

**Comment by CrazyBills** [comment]
@vuchl 
I am developing a website that need to support multiple languages, and I don't want to edit all the routes in nuxt.config.js, I want to create multiple language directories in /pages, so nuxt can generate all the pages of different languages automatically.
the structure is like this
page
-zh
--index.vue
--directory
---index.vue
-en
--index.vue
--directory
---index.vue

actually, all the .vue files are the same, so, it's better to use symlinks to do this,
I hope that i have explained this situation clearly, and If there are any better ways to do this, please share with me, thank you.

**Comment by vuchl** [comment]
maybe you should have a look at this: https://vuejsdevelopers.com/2017/09/11/vue-js-vuex-plugins/ especially the  3rd point

**Comment by CrazyBills** [comment]
sorry, the option of the glob should be 'follow'.
``Follow symlinked directories when expanding ** patterns. Note that this can result in a lot of duplicate references in the presence of cyclic links.``

the i18n examples you provide in this page https://nuxtjs.org/examples/i18n 
you maintained all the entries of page in nuxt.config.js
``generate: {
    routes: ['/', '/about', '/fr', '/fr/about']
  }``
what i want to do is generate all the pages of different languages automatically .

**Comment by vuchl** [comment]
ah allright for static generation you indeed need the different routes. you could clone the repo, add the `follow` option in the builder.js file, link the local copy to your application repo and generate it. not pretty but it would work.

**Comment by CrazyBills** [comment]
Thank you, I've already done that, but I still hope to have this feature,  or at least we can configure it in 'nuxt.config.js' ,   it's just a suggestion.

**Comment by Atinux** [comment]
HI @CrazyBills 

Actually you can instead create a `_lang/` directory and have only one structure:
```bash
pages/
  _lang/
    index.vue
    about.vue
  index.vue
```

You can imagine that `pages/index.vue` will do a `redirect` to the user language url.

Then, into your `nuxt.config.js`, you can use `glob` to list the files of your `pages/` directory and list throw the files and duplicate them for how many different language you have and replacing `_lang` by the language ISO.

Example with `['en', 'zh']` -> `['/', '/en', '/en/about', '/zh', '/zh/about']`
