### ISSUE TITLE
Nuxt not building on Windows machine

### ISSUE THREAD

**Issue by GustavsR** [nuxt/nuxt.js#170]
I have just installed `adonuxt` (which basically is Adonis.js + `nuxt`).
Unfortunately, `nuxt` is not building on Windows machine.

When I run `npm run build` (which stands for `node ./ace nuxtbuild` (which stands for `webpack`, I guess)), all I get is a bunch of errors in my terminal.

IMO, these errors are related with Windows backslash.

All the errors state the same thing.
```
ERROR in ./.nuxt/App.vue
Module not found: Error: Can't resolve 'C:UsersGustavsDocumentsWWWproject_name
ode_modulesue-loaderlibcomponent-normalizer' in 'C:\Users\Gustavs\Documents\WWW\project_name\.nuxt'
 @ ./.nuxt/App.vue 4:16-123
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
```

As you can see, path is resolved incorrectly and backslashes are ignored. Also the letter `n` in `node_modules` path is ignored because of that backslash.

**Comment by GustavsR** [comment]
```
> node -v && npm -v
v7.4.0
4.0.5
```

**Comment by Atinux** [comment]
Can you confirm me that you have the same error with the [starter template](https://github.com/nuxt/starter)?

**Comment by GustavsR** [comment]
@Atinux Yes, the same happens with starter template.
You can see full console output [here](https://gist.github.com/GustavsR/0568b9322a7db6adbfb1061ba17e870e).

**Comment by samkitano** [comment]
same issue here, on win10. even with the vue-cli starter template.

clean new project, following exact instructions from intallation guide.
![28-01-2017 01-14-32](https://cloud.githubusercontent.com/assets/2251400/22393023/d953ff2c-e4f7-11e6-9b60-c9ccdc923403.png)

```
'ERROR in ./.nuxt/components/nuxt.vue
Module not found: Error: Can't resolve 'C:wamp64www
uxt     est
ode_modules♂ue-loaderlibcomponent-normalizer' in 'C:\wamp64\www\nuxt\test\.nuxt\components'
 @ ./.nuxt/components/nuxt.vue 1:16-99
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
```
...

```
[C:\wamp64\www\nuxt\test\node_modules\C:wamp64www
uxt     est
ode_modules♂ue-loaderlibcomponent-normalizer]
 @ ./components/Footer.vue 1:16-99
 @ ./~/babel-loader/lib?{"plugins":["transform-async-to-generator","transform-runtime"],"presets":[["es2015",{"modules":false}],"stage-2"],"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue
 @ ./layouts/default.vue
 @ ./~/babel-loader/lib?{"plugins":["transform-async-to-generator","transform-runtime"],"presets":[["es2015",{"modules":false}],"stage-2"],"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./.nuxt/App.vue
 @ ./.nuxt/App.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
```


definetly looks like a windows backslash thing

```
> node -v && npm -v
v6.9.4
4.1.2
```

**Comment by Atinux** [comment]
Do you mind trying with npm 3?

It works on my computer with npm 3

**Comment by GustavsR** [comment]
@Atinux It builds successfully with `npm 3`, but IMO this package should support the latest version of `npm` anyway.

**Comment by Atinux** [comment]
It should and it will.

It was to isolate the error first to better fix it.

**Comment by samkitano** [comment]
I'm sorry I can't be of any further help, digging into it.

I'm not really a node expert (not even a webpack or babel one, to be honest). Tried for a while to stack trace the thing, and make some fixes myself, but I really don't have a clue. Judging by the console output (malformed paths), my best guess would be that there must be  some ridiculously small thing (it always is), like a bad  regexp, while composing paths. somewhere. probably babel. I'm afraid I lack the expertise to trace it properly :(

**Comment by Atinux** [comment]
@samkitano @GustavsR do you ming uploading the `.nuxt` folder generated when you launched `npm run dev`?

**Comment by GustavsR** [comment]
@Atinux There you go - https://drive.google.com/file/d/0B2et1wX5sB_XWVhWVzdzZ05tTzQ/view?usp=sharing

**Comment by GustavsR** [comment]
I mean, there is the `.nuxt` directory for `npm run dev` - https://drive.google.com/file/d/0B2et1wX5sB_XVlZTUWNmNUhxNWc/view?usp=sharing

The previous was from `npm run build`.

**Comment by samkitano** [comment]
[test.zip](https://github.com/nuxt/nuxt.js/files/737531/test.zip)
There you are

**Comment by SkaterDad** [comment]
Just did a test on my Win 10 computer, and it all seems okay.

These are the commands I ran in Powershell (also tried Cmd.exe with same result).
```
node -v
v7.4

npm -v
v4.0.5

vue init nuxt/starter nuxt-test
cd nuxt-test
npm install
npm run dev
 *** works just fine ***
npm run build
*** worked as well ***
```

**Comment by samkitano** [comment]
Well, that's awkward...

I've just upgraded Node.js to v7.4.0 to try and replicate @SkaterDad env, and now it's working fine!

**Comment by GustavsR** [comment]
Yes, now it is working fine, and I haven't changed my `node` or `npm` versions.
I think it is related with the latest commits.

**Comment by samkitano** [comment]
Thanks, @Atinux, @GustavsR, and @SkaterDad.
