### ISSUE TITLE
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

### ISSUE THREAD

**Issue by SaranyaPalanivel** [nuxt/nuxt.js#1700]
In Nuxt, if I try to add third party plugin for example vue-date-picker like this

```

<template>
   <div>
       <datepicker :readonly="true" format="YYYY-MM-DD"></datepicker>
    </div>
</template>




<script>
let datepicker = null
// The server-side needs a full url to works
if (process.browser) {
  datepicker = require('vue-date-picker').default
}


export default {
  components: {datepicker}
}
</script>

```

DatePicker works perfectly. But the following warning occurs

**[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>,or missing <tbody>. Bailing hydration and performing full client-side render**.

How to get rid of it?

**Comment by homerjam** [comment]
You could try wrapping the component with `<no-ssr/>`, or moving all dom manipulations to the `mounted` lifecycle hook.

**Comment by saranyaPalanivel** [comment]
@homerjam <no-ssr/> works fine....Thanks

**Comment by vuchl** [comment]
@Atinux @alexchopin The `<no-ssr>` component should be getting some attention in the documentation.

**Comment by lomholdt** [comment]
Wow! `<no-ssr>` works great! Had no idea that was a thing. Thanks!

**Comment by levy9527** [comment]
by the way, when use element-ui as plugin, remember set `ssr: true`

**Comment by thomijasir** [comment]
i try in my costume component it was great there no errors but the component not working properly? why?

**Comment by VersaceAndy** [comment]
@homerjam  perfect! Thanks
