### ISSUE TITLE
Dynamic routes along with manually created?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1703]
Hello. I am trying to use manually created pages/routes along with dynamically generated, but seems like it is not working.

Is there any option to use Nuxt like this:

![wtf](https://user-images.githubusercontent.com/30086515/30698585-61f9ea22-9eb0-11e7-9051-fdcfb1d1ea26.png)

`wtf` route doesn't work on `articles/wtf/` endpoint. Only the routes that comes from API in `_section` is working.

Since I can't find proper way to insert components in dynamic routes (that fetch data and then `v-html` it from API), I want to have an opportunity sometimes create manually rich pages, where I can use components etc, and not being dependent on `v-for` and `v-html` schemes.

How to achieve that?

**Comment by vuchl** [comment]
Do you expect `wtf` to be a single page? Then only create a `wtf.vue` page for it. Or place an `index.vue` inside the folder so the route is generated.

**Comment by iamdubx** [comment]
@vuchl no, I expect `wtf` to be a section! Where I can manually put other pages.

**Comment by iamdubx** [comment]
Nothing from this is working 

![not](https://user-images.githubusercontent.com/30086515/30706605-daebffea-9ec6-11e7-9e9b-d30fddbb29fe.png)

**Comment by iamdubx** [comment]
https://github.com/vuchl/static-and-dynamic-routes - I have the same code. It doesn't work in real setup.

**Comment by iamdubx** [comment]
Looks like I needed to restart Nuxt. Now it's working. Strange, never saw this before, usually Nuxt don't need restart.
