### ISSUE TITLE
How can I add CORS to nuxt?

### ISSUE THREAD

**Issue by luiztsmelo** [nuxt/nuxt.js#1704]
I'm trying to get data from firebase and I'm getting this error: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by halilbayrakci** [comment]
Hi @luiztsmelo , I am dealing with this problem and just wanted to ask if you have found a solution for this problem. I would appreciate if you can help me, thanks

**Comment by reco** [comment]
@luiztsmelo same here, how did you configure CORS? +1

**Comment by halilbayrakci** [comment]
@luiztsmelo I have realized that my code was working on client side. I have configured it to work on server-side with cors headers and my problem has solved. Maybe it helps

**Comment by reco** [comment]
apologize i am new to vuejs and nuxt. 
i understand in order to get this to work the nuxt local dev server needs to set the correct CORS.
how can i configure the nuxt server to allow CORS to an external domain like `http://server.com/api`?

thanks

**Comment by halilbayrakci** [comment]
@reco no problem, i am new to vuejs too :) in my experience, nuxt is just doing server rendering so it doesnt working as a server. you need nuxt/express or nuxt/koa and do your api calls to external domain at server side. and then you can make connect to your internal api without cors problem on vuejs/nuxt side(client side). and maybe you need to use cors middleware on server side. this was my solution, hope this helps

**Comment by randyhoulahan** [comment]
could you share an example @halilbayrakci ?
