### ISSUE TITLE
About how to use keep-alive in Nuxt.js

### ISSUE THREAD

**Issue by spencer1994** [nuxt/nuxt.js#1706]
Fisrtly, Forgive my English is not very good.

I use keep-alive tag in default.vue, but it doesn't work.
`default.vue:`
```
<template>
  <div>
    <keep-alive>
      <nuxt></nuxt>
    </keep-alive>
  </div>
</template>
```

At last, I find it can work after add a code in nuxt-child.js line65.
`nuxt/lib/app/components/nuxt-child.js:`
```
return h('transition', {
    props: transitionProps,
    on: listeners
  }, [
  h('keep-alive', [
    h('router-view', data)
  ])
])
```
You can judge keep-alive based on the configuration of nuxt.config.js.
 `result`
![image](https://user-images.githubusercontent.com/19463934/30749266-6d67b48a-9fe5-11e7-89e7-26e717c5f42e.png)

If you doesn't need `keep-alive`, you can add `deactivated` in this components.
 ```
deactivated () {
  this.$destroy()
},
```

**Comment by lukasborawski** [comment]
@spencer1994 What are you trying achieve actually using `keep-alive`?

**Comment by spencer1994** [comment]
@lukasborawski I edit my issue again, and upload two printscreens.

**Comment by spencer1994** [comment]
@alexchopin Could you please modify the configuration about `<keep-alive>`?

**Comment by Atinux** [comment]
HI @spencer1994 

Right know we don't plan to support `<keep-alive>` into Nuxt.js since it adds more complexity.

**Comment by dreglad** [comment]
Hi @Atinux

Supporting `<keep-alive>` in SPA mode shouldn't add any complexity at all, or am I missing something?

@spencer1994's simple hack on `nuxt/lib/app/components/nuxt-child.js` worked pretty well for me

**Comment by Atinux** [comment]
Hi @dreglad @spencer1994 @rabelfish @cocbin

I implemented the `keep-alive` prop into `<nuxt/>` and `<nuxt-child/>`, be aware that it's still a WIP and it can have some side effects.

See https://github.com/nuxt/nuxt.js/tree/dev/examples/with-keep-alive

I will be available soon with next release `v1.2.0`.

Screenshot: 

![screen shot 2018-01-17 at 09 42 47](https://user-images.githubusercontent.com/904724/35033642-b41ec51c-fb6b-11e7-87cf-5617ade32841.png)

**Comment by spencer1994** [comment]
@Atinux i see, thanks

**Comment by JesonRondo** [comment]
@Atinux First thx for Nuxt.

There I have a question. How to set some page `keep-alive`, but another not. For example, `Index.vue` is a long listview, we want to back with the history scroll location, but `About.vue` were not, it should be destroy. But in this example (https://github.com/nuxt/nuxt.js/tree/dev/examples/with-keep-alive), both `Index.vue` and `About.vue` will keep-alive.

I tried write layout like this, but it doesn't work:

```
<template>
  <nuxt :keep-alive="isKeepAlive" />
</template>

<script>
export default {
  data () {
    return {
      keepAlivePages: [
        '/'
      ]
    }
  },
  computed: {
    isKeepAlive () {
      return this.keepAlivePages.indexOf(this.$route.path) > -1;
    }
  }
}
</script>
```

Is there some idea?

**Comment by spencer1994** [comment]
@JesonRondo 看你是中国人我就说中文了。你试试用v-if的方法？
```
<template>
  <nuxt v-if="isKeepAlive" keep-alive />
  <nuxt v-else />
</template>

```

**Comment by JesonRondo** [comment]
@spencer1994 thx a lot.

I also try this method, but keep-alive doesn't work well.

Lifecycle method `deactivated` and  `destroyed` both called when leave `Index.vue` page. component of `Index.vue` page released.

Aren't you?

**Comment by JesonRondo** [comment]
Then, I change my way to do this job, avoid keep-alive situation.

When the data always exist in store, back to this page, browser auto index to the latest location.

😂

**Comment by spencer1994** [comment]
@JesonRondo we can communicate via qq, 442604117.

**Comment by spencer1994** [comment]
@JesonRondo  if just want to save scroll position, u can do what u doing

**Comment by ramstein74** [comment]
I tested <nuxt keep-alive> with nuxt.
All my <no-ssr> stoped working and the page keeps executing the fetch event when i go back to the page. Is this normal?

**Comment by wsakka** [comment]
Having same issues as @ramstein74 -- no fix or workaround for this issue? This seriously hinders back button behaviour and gives off a glitchy experience.
