### ISSUE TITLE
Can not access env variables from plugin

### ISSUE THREAD

**Issue by keldorg** [nuxt/nuxt.js#1707]
I set in nuxt.config.js env variables
```js
env: {
    language: process.env.NODE_LOCALE
  },
```
and after, when plugin code runs in server I get undefined.
```js
import Vue from 'vue'
import VueI18n from 'vue-i18n'
Vue.use(VueI18n)
export default ({ app, isServer, env }) => {
app.i18n = new VueI18n({
    locale: env.language || 'en', #env.language === undefined
    fallbackLocale: env.language || 'en',
    messages: {
      'en': require('~/locales/en.json'),
      'es': require('~/locales/es.json'),
      'fr': require('~/locales/fr.json'),
      'de': require('~/locales/de.json')
    }
  })
```
I read doc several times but I can't find a solution.

Edit(more info):
On my laptop(mac) works fine in dev and production mode, but in ubuntu 14.04 server is where stops working.

Edit2:
I found my mistake, I wasn't exporting correctly variables before build. Please close the issue and sorry for the inconvenience.

**Comment by JulienTant** [comment]
@keldorg you can close it yourself ! ;)

**Comment by keldorg** [comment]
1. export "your variable name"="variable value"
export NODE_ENV=production
2. launch nuxtjs
npm run dev

**Comment by watMartin** [comment]
Not sure I understand, does that mean you don't make use of the process.env object? Could you maybe show me your nuxt.config.js file?

**Comment by keldorg** [comment]
I use process.env in nuxt.config.js, but if you dont't export variables before launch, the variables will be null.

env: {
    locale: process.env.NODE_LOCALE || 'en',
    domain: process.env.NODE_DOMAIN || 'com'
},

In nuxtjs web page is well explained:
[https://nuxtjs.org/api/configuration-env](url)

**Comment by watMartin** [comment]
Right I think I understand, are you exporting the variables in the config files itself too then?

**Comment by glensargent** [comment]
@keldorg I'm having same issue, when repeating what the docs say, it doesn't work. My nuxt.config.js file has an env object with keys and values and yet none of them are accessible in my plugins

**Comment by keldorg** [comment]
@glensargent are you exporting variables correctly? My fault was that I wasn't exporting before build.

**Comment by watMartin** [comment]
@keldorg could you show me an example of how you're exporting and where?
