### ISSUE TITLE
Event Handling Issue with External JS

### ISSUE THREAD

**Issue by SaranyaPalanivel** [nuxt/nuxt.js#1708]
If suppose I handle some click events for nuxt pages(spa) in external js and include in head tag, click events happen only when page refresh

For example,
index.js included in head tag

```
$(document).ready(function () {
 $('.sample').on('click', function () {
   alert('sample')
})
}
```

pages index.vue 

```
<template>
 <div class='sample'>
    data
</div>
<template>
```
how to use external js events in nuxt pages without DOM issue?

**Comment by lukasborawski** [comment]
Why you want to use jQuery for this? This is out of main paradigm/concept of building apps with nuxt and vue.

**Comment by uptownhr** [comment]
Can't resole this. Nuxt uses hmr in dev mode. But your jquery code does not get hot reloaded.
