### ISSUE TITLE
How generate pages in flat structure?

### ISSUE THREAD

**Issue by rzcoder** [nuxt/nuxt.js#1711]
I have few pages like:
```
pages
  |- index.vue
  |- page1.vue
  |- page2.vue
```
and after `generate` I'll get
```
dist
  |- index.html
  |- page1
  |   |- index.html
  |- page2
      |- index.html
```
but I need to 
```
dist
  |- index.html
  |- page1.html
  |- page2.html
```

**Comment by vadimsg** [comment]
Extended routes can solve your problem
https://nuxtjs.org/api/configuration-router#extendroutes

**Comment by rzcoder** [comment]
What if I want to have page like `images.html` and also have folder `images` in `static` folder?

**Comment by alexchopin** [comment]
Hi, this option is not available.
A PR is more than welcome to add this option to `nuxt generate`.
I'm closing this issue because it's not really one, but feel free to comment it if you have more ideas about this feature.

**Comment by Gomah** [comment]
@rzcoder It's now possible using the `subFolders`property: https://nuxtjs.org/api/configuration-generate#subfolders
