### ISSUE TITLE
Allow to run from file system?

### ISSUE THREAD

**Issue by jvukovich** [nuxt/nuxt.js#1712]
I would LOVE to use Vue + Nuxt to create my Unreal Engine 4 user interfaces in Coherent GT ( http://coherent-labs.com/coherent-gt/ ). I have been able to get vanilla Vue to run just fine (took a bit of tweaking, but actually works very well).

Nuxt, however, is more troublesome. I get that Vue and Nuxt are designed to run in a web server. However, I feel this is a good use case to be able to run apps from the file system.

Take, for example, this structure:
```
~/pages/index.vue
~/pages/otherpage.vue
```

Each has a link to each other:
```
index.vue: <nuxt-link to="/otherpage">Other Page</nuxt-link>
otherpage.vue: <nuxt-link to="/">Index</nuxt-link>
```

Upon nuxt generate, you get:
```
~/dist/index.html
~/dist/otherpage/index.html
```

```
index.html: <a href="/otherpage">Other Page</a>
otherpage/index.html: <a href="/">Index</a>
```

The issue I am having is that the URL cannot be resolved:
`<a href="/otherpage">Other Page</a>`

I need it to render as:
`<a href="/otherpage/index.html">Other Page</a>`

Coherent GT has no support for a default/index file specification, as it treats everything as being loaded from the file system.

Nuxt would work great if I had an option to generate static content and routes with the full path ("/otherpage/index.html" rather than "/otherpage").

A bit more context: Playerunknown's Battlegrounds uses Coherent GT and Angular for their game UI.

**Comment by jvukovich** [comment]
Been thinking of doing something like this post-build, but it sure is a hack!

```
  const options = {
    files: 'dist/**/index.html',
    from: /a href="\/(.*?)"/g,
    to: (match) => {
      const matchLower = match.toLowerCase()

      if (matchLower.indexOf('/index') === -1) {
        return replaceall('a href=', 'a href="', `${replaceall('"', '', matchLower)}/index.html"`)
      }
      else {
        return replaceall('/index', '/index.html', matchLower);
      }

      return match
    }
  }

  try {
    replace(options)
      .then(changes => {
        console.log('Modified files:', changes.join(', '))
      })
      .catch(error => {
        console.error('Error occurred:', error)
      })
  }
  catch (e) {
    console.log(e)
  }
  finally {
  }
```

**Comment by jvukovich** [comment]
So, it sort of works. Any direct link is fine. However, it does not work when I need to do something like this:
`this.$router.replace({path: '/hud'})`
Would love to get some help/advice on this.

**Comment by jvukovich** [comment]
Well, I'm stupid. All I had to do was put the router in hash mode, and generate --spa. Duh. Feel free to leave this up here in case anyone else does something dumb like I just did. ;)

**Comment by KABBOUCHI** [comment]
>  I have been able to get vanilla Vue to run just fine (took a bit of tweaking, but actually works very well).

Plz, can you share how did you able to run Vue with Coherent GT. Thanks
