### ISSUE TITLE
Feature: ability to specify a scroll offset to scrollBehavior when passing selector

### ISSUE THREAD

**Issue by tmorehouse** [nuxt/nuxt.js#1713]
When using the selector feature (i.e. to.hash), it would be nice to be able to add the ability to set a global offset in order to compensate for fixed navbars on top.

**Comment by homerjam** [comment]
Hey @tmorehouse, great idea. I think you should add it to the `vue-router` repo though.

**Comment by krestaino** [comment]
As a workaround for now, I suggest adding `padding-top: X` to the element you're scrolling to, where _X_ is the height of the nav. This makes it scroll into view without cutting off content. I'll usually add a bit more than just the nav height so there's some padding between the nav and the element. If you make _X_ a SCSS/SASS variable, even better.
