### ISSUE TITLE
Does nuxtServerInit work in spa mode?

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#1714]
I have been trying to get nuxtServerInit  to work for an hour now.  it is never called. Is it because i use SPA mode?

**Comment by uptownhr** [comment]
@husayt it does not. I believe nuxtClientInit is in the works. 

In the mean time, my solution was to create a middleware that gets run. Not sure if it'll fit your needs but worth a shot. 

Also, it has been suggested that you can create a nextClientInit plugin, that also functions the same. I do however question, how you can ensure this plugin runs first before others and may run into a race condition against plugins.

**Comment by husayt** [comment]
@alexchopin I ended up following your advise from [here](https://github.com/nuxt/nuxt.js/issues/240#issuecomment-326893386). It will be extremely useful to add that to FAQ. I spent long time to find a solution. Also   to mention in nuxtserverinit doc that it only works serverside.

https://github.com/nuxt/nuxt.js/issues/240#issuecomment-326893386
