### ISSUE TITLE
Mix of slot and nuxt-child breaks everything

### ISSUE THREAD

**Issue by Kasheftin** [nuxt/nuxt.js#1715]
I've spent many hours to investigate the strange behavior in our large app.
Finally I've found it, it seems so furious that I just have no idea what to do next with nuxt and with our templates among the whole application.

As usual, I created the separate repo with very simple code to demonstrate it: https://github.com/Kasheftin/nuxt-bug4.
I'll show two bugs (alhough they may have one source).

I suppose the reason is this component we use as a wrapper (everything else in the demo is hello world):

```
<template>
  <div class="container">
    <div class="col -menu">
      <slot/>
    </div>
    <div class="col -content">
      <nuxt-child/>
    </div>
  </div>
</template>
```

If the user goes to the index page, we show him menu column only using the index page that looks like:

```
<template>
  <TwoColumns>
    MENU GOES HERE
  </TwoColumns>
</template>
```

Then he follows the nested route and the target page placed into the nuxt-child of the wrapper.

# The first bug:

1. Follow the /a link. There's an input field with v-model, type anything and it appears just after the input.
2. Follow /a/b link. Type something into the input field. It will work, but after every keypress nuxt show the progress bar at the top of the page like it load something. Although that's just simple inner component value update.

# The second bug:

3. Now follow /a/b/c link. Now only the first key press works. After that the data stops updating. It seems the component dies after the first key press. Although /b and /c are just nested nuxt-childs without javascript at all. And only the buggy progress bar at the top keeps working.

**Comment by uptownhr** [comment]
it was under my impression that nuxt-child should only be used in the page-component. Is there another component structure you can use to handle your use case so nuxt-child is not a part of your component?

**Comment by Kasheftin** [comment]
Well, the other component structure is.. copy/paste of the wrapper to every root page layout:) We have 24 now. That's what I'll be forced to do if there's no better solution. And that's simple comparing the resources I spent to catch this bug. If nuxt-child is really not allowed in the plain components, I would definitely add big warning to the evaluating code about this, because this structure mostly works, we've been living about 4 months with this it.

**Comment by uptownhr** [comment]
Sorry for the trouble but that's what I would do.

**Comment by uptownhr** [comment]
Or expose another slot to put in nuxt child

**Comment by alexchopin** [comment]
Hi,
Unfortunately `<nuxt-child` can be used only in pages component, we will complete the documentation about this.
