### ISSUE TITLE
Backslash in paths to *.js resources

### ISSUE THREAD

**Issue by ambaranow** [nuxt/nuxt.js#1717]
Windows 10, 
$ node -v && npm -v
v7.4.0
4.0.3
nuxt 1.0.0-rc11

`npm run generate` adds this code to index.html:

```
...
<link href="/_nuxt/layouts\default.068bb58abd452073bc8c.js" rel="preload" as="script">
<link href="/_nuxt/pages\index.a87642a9eda389caf735.js" rel="preload" as="script">
...
<script defer src="/_nuxt/layouts\default.068bb58abd452073bc8c.js"></script>
<script defer src="/_nuxt/pages\index.a87642a9eda389caf735.js"></script>
...
```
with backslash `\` in path

**Comment by mattjcowan** [comment]
I'm getting the same thing as well, similar env specs

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1717](https://trello.com/c/tRLB3Zn7/28-1717)
