### ISSUE TITLE
[NOT AN ISSUE|QUESTION] How to load a non VueJS plugin ?

### ISSUE THREAD

**Issue by JulienTant** [nuxt/nuxt.js#1718]
Hi !

I'm sorry for posting an issue... that is not an issue :(

I want to use an external library (HelloJS - a client side OAuth lib) in my project. In order to use it I have a bit of configuration to do, like settings my API keys etc...

I've created a `hello.js` (code at the end of the post) file in the `plugins/` folder in order to use it, but it's not VueJS plugin. How can I use this plugin ? I tried to simply import it in my page, but this plugin use "window" and it crash when the page is being rendered by SSR.

**/nuxt.config.js**
```js
module.exports = {
  //...
  plugins: [{src: '~/plugins/hello.js', ssr: false}],
  //...
}
```

**/plugins/hello.js**
```js
import hello from 'hellojs'

hello.init({-removed-})

export default hello
```

**Comment by krestaino** [comment]
https://nuxtjs.org/guide/plugins#client-side-only

**Comment by JulienTant** [comment]
I ended up creating a new VueJS plugin which embeds my code, and it's working.

I don't close this right now because I don't know if there is a better way, if not, just tell me and i'll close this issue.

Here is how i updated my plugin:

**/plugins/hello.js**
```js
import Vue from 'vue'
import hello from 'hellojs'

hello.init(-removed-)

const HelloJS = {
  install (v) {
    Vue.prototype.$hello = hello
  }
}

Vue.use(HelloJS)
```

I hope it will be useful to someone :)

**Comment by kamleshkatpara** [comment]
@JulienTant, I followed what you did.
But getting this error : Uncaught TypeError: hello is not a function

Can you please suggest me what could be wrong here
