### ISSUE TITLE
proxy not work in nginx server

### ISSUE THREAD

**Issue by alterhu2020** [nuxt/nuxt.js#1719]
Nuxtjs: 1.0.0 RC11
= @nuxtjs/proxy : latest

I had build my `spa` page very well, and there's a third party API request using `axios` in my page.
When i run it from localmachine , everything is fine.
But after i move the generate files using `nuxt generate` into nginx server. I found that the proxy request cannot parse with 404 returned.

the proxy i had configured in my `nuxt.config.js` file like below：
```
 modules: [
    ['@nuxtjs/google-analytics', { ua: 'UA-78501857-4' }],
    '@nuxtjs/axios',
    '@nuxtjs/proxy'
  ],
  axios: { debug: true },
  proxy: {
    // /api/test1/test2  -> http://www.toutiao.com/api/test1/test2

    '/api': {
      target: 'http://www.toutiao.com',
      changeOrigin: true,             // for vhosted sites, changes host header to match to target's host
      logLevel: 'debug'
    }
  },

```
1. The axios request url is : http://www.toutiao.com/api/pc/feed/?min_behot_time=0&category=__all__&utm_source=toutiao&widen=1&tadrequire=true&as=A105A9CB66F96E6&cp=59B609C66E464E1

2. The proxy url had become: http://localhost:3030/api/pc/feed/?min_behot_time=0&category=__all__&utm_source=toutiao&widen=1&tadrequire=true&as=A105A9CB66F96E6&cp=59B609C66E464E1
3. In nginx server I saw the request is http://servername.com/api/pc/feed/?min_behot_time=0&category=__all__&utm_source=toutiao&widen=1&tadrequire=true&as=A105A9CB66F96E6&cp=59B609C66E464E1 , but it returned as 404.

**Comment by dreambo8563** [comment]
I dont think proxy will work on spa, i just using it form develop

**Comment by alterhu2020** [comment]
it's too bad for this, it seems that the proxy is conflict with the nginx's proxy server. 
I'm going to close this issue, as nobody has reponse for it.  
thanks @dreambo8563

**Comment by ouyangxiaoai** [comment]
@alterhu2020 朋友你解决了这个问题了吗？
