### ISSUE TITLE
how  to use the url-loader?

### ISSUE THREAD

**Issue by cgygd** [nuxt/nuxt.js#1720]
I don't want the name of picture include hash data,I do need the original picture name.

now:/_nuxt/img/logo.0302b2a.png
need:/_nuxt/img/logo.png

Can you tell me how to deal with the issue?

I am invalidating this file with the following code in the file of nux. confug.js
```
build: {
    extend (config, { isClient }) {
      config.module.rules.push({
        test: /\.(png|jpe?g|gif|svg)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 100000,
            }
          }
        ],
        exclude: /(node_modules)/
      });
    }
}
```

**Comment by Norbz** [comment]
If you need some files not to be webpacked, you should put them in the static directory, not in the asset directory.

Assets are supposed to be webpacked, and you shouldn't remove hash from webpacked resources.

See the difference in the doc : https://nuxtjs.org/guide/assets/#static

**Comment by cgygd** [comment]
ok thx.
