### ISSUE TITLE
Can't Change Port

### ISSUE THREAD

**Issue by moshemo** [nuxt/nuxt.js#1724]
I've added the following code to my nuxt.config.js file (but it doesn't seem to work):

```
  env: {
    "scripts": {
      "dev": "PORT=3333 nuxt"
    }
  },
```

I can only access my site at localhost:3000 not at localhost:3333
Any idea why it's not working right?

The following also does not work:

```
  env: {
    "scripts": {
      "dev": "HOST=0.0.0.0 PORT=3333 nuxt"
    }
  },
```

When I try that, I first get an error:

```
 ERROR  Failed to compile with 1 errors          17:30:04

 error  in ./.nuxt/client.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/moshemo/Sites/nuxt/vuebulma/.nuxt/client.js'

 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```

Then it compiles successfully at `localhost:3000`

Any idea what I am doing wrong?

**Comment by Jussiadev** [comment]
@moshemo I did 
```
"nuxt": {
      "port": "3333"
    }
  },
```

**Comment by alexchopin** [comment]
Hi @moshemo,
This should be in your package.json, not in your nuxt.config.js file:
```js
"scripts": {
  "dev": "PORT=3333 nuxt",
}
```

**Comment by moshemo** [comment]
Hello @alexchopin 

But don't the docs say that I can also do it in my nuxt.config.js file:

https://nuxtjs.org/faq/host-port

```
You can configure the PORT with 3 different ways:

With env variables

"scripts": {
"dev": "HOST=0.0.0.0 PORT=3333 nuxt"
}
...

3. Inside your package.json:
"config": {
  "nuxt": {
    "host": "0.0.0.0",
    "port": "3333"
  }
},
"scripts": {
  "dev": "nuxt"
}
```
Doesn't env variables refer to the nuxt.config.js file?

**Comment by vuchl** [comment]
The FAQ is a bit confusing here. the mentioned `env` variables are refering to Node and not Nuxt specifically. You can not set the port in the nuxt.config.js I believe.

You can set it in the `package.json` like
```javascript
// package.json
{
  "scripts": {
    "dev": "PORT=3333 nuxt"
  }
}
```

or like
```javascript
// package.json
{
  "scripts": {
    "dev": "nuxt -p 3333"
  }
}
```

or with the nuxt config option in the `package.json`
```javascript
// package.json
{
  "scripts": {
    "dev": "nuxt"
  },
  "nuxt": {
    "port": 3333
  }
}
```

**Comment by moshemo** [comment]
@vuchl Thanks -- that explains it.  I did assume (incorrectly I now see) that the env variables mentioned by the FAQ was referring to the nuxt.config.js file.
