### ISSUE TITLE
Spread operator does not work in node_modules folder

### ISSUE THREAD

**Issue by TuxGit** [nuxt/nuxt.js#1725]
### Versions
- node v6.11.2
- nuxt v1.0.0-rc11

### Intro
I use in my project css framework vuetify and cant import VBtn component. For example I made a similar code to reproduce the same error.

### Steps to reproduce
- Init project with "nuxt-community/starter-template" template
- Make component in node_modules folder
```js
./node_modules/TestComponent/TestComponent.js

export default {
  methods: {
    someMethod () {
      const foo = {
        var1: 11,
        var2: 22
      }
      // let bar = {
      //   ...foo
      // }
      return {
        ...(foo || {})
      }
    }
  }
}
```
- In index page import the component
```js
./pages.index.vue

<script>
import TestComponent from '../node_modules/TestComponent/TestComponent.js'
...
</script>
```

### What is actually happening ?
When I start the assembly (npm run dev) the error gets out:
```
 error  in ./node_modules/TestComponent/TestComponent.js

Module parse failed: C:\Users\user\projects\nuxt-test\node_modules\TestComponent\TestComponent.js Unexpected token (12:8)
You may need an appropriate loader to handle this file type.
|       // }
|       return {
|         ...(foo || {})
|       }
|     }

 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["C://Users//user//projects//nuxt-test//node_modules//babel-preset-vue-app//dist//index.common.js"]}!./node
_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue 24:0-59
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```

### PS
With other starter templates (webpack + ssr) there is no such error. But I already started the project on nuxt.

**Comment by Atinux** [comment]
@TuxGit What is the webpack+ssr template you're using please?

**Comment by TuxGit** [comment]
@Atinux Tried the following templates:  "vuetifyjs/webpack-ssr", "vuetifyjs/webpack-advanced"

**Comment by krzksz** [comment]
Hey! I haven't used nuxt yet, but I spotted your issue and since I recently stumbled upon similar one I thought I could help a bit.

It seems like babel-loader is ignoring code within `node_modules` which is usually due to it's typical configuration. I believe you can find the line responsible here: https://github.com/nuxt/nuxt.js/blob/b931dd40cea828021f3092d1e224053a1baacba0/lib/builder/webpack/base.config.js#L72

If this is indeed the case then you should be able to overwrite this `exclude` option using this guide: https://nuxtjs.org/faq/extend-webpack#how-to-extend-webpack-config-

**Comment by TuxGit** [comment]
@krzksz Hey! Yes, thanks for the advice. I understood which way to look. 
Nuxt runs with config .../nuxt/dist/nuxt.js

I just extended the config nuxt.config.js with extend method and all was compiled :)
```js
      config.module.rules.push({
        test: /\.js$/,
        loader: 'babel-loader',
        options: {
          presets: ['vue-app'],
          babelrc: false,
          cacheDirectory: true
        },
        include: [
          // path.resolve(__dirname, './node_modules/TestComponent'),
          path.resolve(__dirname, './node_modules/vuetify/src')
        ]
      })
```

**Comment by gitzhaochen** [comment]
@TuxGit rules.concat not working but push is working , here is my code
`extend(config, {isDev, isClient}) {
            config.module.rules.concat(
                    [
                        {
                            test: /\.html$/,
                            use: {
                                loader: 'html-loader'
                            }
                        }
                    ]
                )
        }`
