### ISSUE TITLE
Components with Axios

### ISSUE THREAD

**Issue by raisiqueira** [nuxt/nuxt.js#1729]
Hey! I have a component that I want to load a menu from my api (WP-API), but it is returning null. Here is my component code:

```
<script>
import Axios from '~/plugins/axios'

export default {
  props: ['sitename'],

  mounted () {
    this.getMenus()
  },

  data () {
    return {
      menus: []
    }
  },

  created () {
    this.$log.info(this.getMenus())
  },

  methods: {
    getMenus () {
      Axios.get(`wp-api-menus/v2/menus`)
      .then((res) => {
        this.menus = res.data
      })
    }
  }
}
</script>
```

**Comment by glensargent** [comment]
Hi @raisiqueira, it's best to add axios as a nuxt module from the nuxt config file
`  build: {
    vendor: ['axios']
}`

then you can import axios inside your component and use like normal:
`import axios from 'axios'`

**Comment by christophwolff** [comment]
Maybe you should also use the fetch Method.
https://nuxtjs.org/api/pages-fetch

**Comment by raisiqueira** [comment]
Hi, @glensargent! I already added Axios in nuxt.config.js
![captura de tela 2017-09-25 as 22 08 38](https://user-images.githubusercontent.com/2914170/30837831-3ddc0b2a-a23e-11e7-8cb9-b4667b5a3943.png)

**Comment by raisiqueira** [comment]
Hi @christophwolff with fetch method don't work.

**Comment by christophwolff** [comment]
@raisiqueira i would advise you to use the store and the nuxtServerInit if you use SSR. The main menu is a core component what is loaded on every page. 
But if you dont want that try
```javascript
async getMenus () {
 await Axios.get(`wp-api-menus/v2/menus`)
  .then((res) => {
    this.menus = res.data
  })
}
```

**Comment by glensargent** [comment]
@raisiqueira did you add the / at the start of your route?

**Comment by bskimball** [comment]
I would suggest using this module
https://github.com/nuxt-community/axios-module
It has asyncData examples. I would also look in the network tab in dev tools to see if you're sending requests and getting responses. If @christophwolff is correct you should see a 404 in your ajax response.

**Comment by uptownhr** [comment]
@raisiqueira your info will display null because nothing is being returned from your method.

**Comment by christophwolff** [comment]
@raisiqueira What worked? Interesting for others who find this issue. Thanks!
