### ISSUE TITLE
How to add middleware from module ?

### ISSUE THREAD

**Issue by Nainterceptor** [nuxt/nuxt.js#1730]
Hello,

How can I add a middleware from a module ?
I see that I can use `addServerMiddleware` to add a server middleware but in my case I've to add a middleware accessible from both server and client.

Thanks,
Gaël

**Comment by alexchopin** [comment]
https://github.com/nuxt-community/auth-module/blob/master/src/index.js#L34
https://github.com/nuxt-community/auth-module/blob/master/templates/auth.middleware.js
