### ISSUE TITLE
Loading progress

### ISSUE THREAD

**Issue by kevin-ho87** [nuxt/nuxt.js#1731]
With the Nuxt custom loading component.
https://nuxtjs.org/api/configuration-loading#use-a-custom-loading-component
Is it possible to display the preloader percentage of data loaded?

**Comment by vuchl** [comment]
Hey @kevin-ho87!

You can orient yourself on the default loading component here; https://github.com/nuxt/nuxt.js/blob/dev/lib/app/components/nuxt-loading.vue#L17
and the docs of course.

The component has a `percent` data property.

**Comment by kevin-ho87** [comment]
@vuchl Thanks for this!
