### ISSUE TITLE
Custom routes are not generated

### ISSUE THREAD

**Issue by mrcatman** [nuxt/nuxt.js#1733]
I try to generate a custom route inside nuxt.config.js (as said in https://ru.nuxtjs.org/examples/custom-routes/):
`router: {
		routes: [
			{ path: '/brokers/:id/reviews/:page', component: 'pages/reviews-page' }
		]
	`},``

But when I open, for example, "/brokers/test/reviews/1",it shows a 404 error. I checked /.nuxt/router.js and didn't see that custom route there, only a direct route:

`{
			path: "/reviews-page",
			component: _7cd44aba,
			name: "reviews-page"
		`},``

Am I doing something wrong?

**Comment by natezerk** [comment]
I am having this issue too where custom routes. e.g. folder structure
pages
-- learn
----- _slug.vue
----- index.vue

Only results in learn/index.html being generated but not the slug pages. This works locally but when deployed gives 404.

**Comment by alexchopin** [comment]
Hi @mrcatman,
The Russian documentation seems outdated.
You can refer to the English documentation about [Dynamic Routes for generate option](https://nuxtjs.org/api/configuration-generate#routes).

**Comment by qm3ster** [comment]
Please note that the manual you are linking is for version 0.10.7
What are you trying to achieve?
