### ISSUE TITLE
Can i use template in layout files?

### ISSUE THREAD

**Issue by Muzm** [nuxt/nuxt.js#1734]
hi there,
I need add a vue template in layout files,
I did it in this way but my `<navigation>` template not display.
here's my layout file
~/layouts/main.vue:
```
<template>
  <div id="app">
    <navigation></navigation>
    <nuxt></nuxt>
  </div>
</template>

<script>
  /* eslint-disable no-unused-vars */

  import navigation from '~/components/navigation.vue'

</script>
```

**Comment by vuchl** [comment]
use this:
```html
<template>
  <div id="app">
    <navigation></navigation>
    <nuxt></nuxt>
  </div>
</template>

<script>
import navigation from '~/components/navigation.vue'

export default {
  components: [navigation]
}
</script>
```

**Comment by Muzm** [comment]
@vuchl  i tried this. but `<navigation>` still not display in my page

**Comment by raisiqueira** [comment]
Put here the code of your navigation component.

**Comment by Muzm** [comment]
@raisiqueira thank for you. but fixed it. it's forgot to Specify layout Option in my ~/Pages/index.vue
i thought i import it in a wrong way. now it worked
