### ISSUE TITLE
Critical nuxt.js error! Take a look!

### ISSUE THREAD

**Issue by TheDeveloperTom** [nuxt/nuxt.js#1736]
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/25426552/30869262-5c4406fc-a2e9-11e7-81cd-6a1f4ab5c011.png">

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/25426552/30869520-088c2f70-a2ea-11e7-8c42-9140aab1ee06.png">

The problem is here, that component is shown for a second in the dom but then it disappears(
And the most interesting that the problem exists only on production at "npm run start"
On dev server/run start/dev everything is working! Component does not disappears!

<img width="579" alt="image" src="https://user-images.githubusercontent.com/25426552/30869746-a3e1db82-a2ea-11e7-884d-b1c2ba65c972.png">

Guys, any advice/idea. Thanks in advance.
Source code: https://github.com/dacom-core/mapala-ui/tree/dev

**Comment by vuchl** [comment]
Does the console spit out some error about the DOM not being the same on server and client side?

**Comment by TheDeveloperTom** [comment]
@vuchl yes, I see.
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/25426552/30905034-57322f7a-a37c-11e7-9725-f12cc346e336.png">

But I can't find the root of the problem, I delete 90% of my project and left only the top component, and even then it disappears...

**Comment by vuchl** [comment]
Have a lookt at this: https://github.com/nuxt/nuxt.js/issues/1594

**Comment by TheDeveloperTom** [comment]
@vuchl there is nothing helpful there(

Can you imagine the hell? Everything works on local machine, but when it hits the server, missmatching happens, I even tried to wrap it with docker, but in vain(

Is there something more that I can do to find the problem?(

**Comment by iamdubx** [comment]
Have you tried `no-ssr`?

**Comment by vuchl** [comment]
Get rid of `async` in the `mounted` function
https://github.com/dacom-core/mapala-ui/blob/dev/layouts/default.vue#L87

**Comment by igtm** [comment]
similar problem.. in my case, one part of dom disappears on both production and dev mode only in IE.
in other browsers it works fine..
on IE console in dev mode, i can see a lot of following messages.
`Mismatching childNodes vs . VNodes`
`The client-side rendered virtual DOM tree is not matching server-rendered content....`

but i replaced all `{{ foo }}` syntax to `v-text`, then it works fine. it's weird...

**Comment by alexchopin** [comment]
Hi, 
This issue is not related to nuxt.js as it's a vue-warn due to [client side hydration](https://ssr.vuejs.org/en/hydration.html).
