### ISSUE TITLE
Route transitions do not work inside nuxt-child 

### ISSUE THREAD

**Issue by Kasheftin** [nuxt/nuxt.js#1737]
Here's the example, https://github.com/Kasheftin/nuxt-bug6.

I just took the example code from https://nuxtjs.org/examples/routes-transitions and placed the pages into the /pages/a folder. Then changed links. Then created /pages/a.vue file with the following content:

    <template>
      <nuxt-child/>
    </template>

After that page transitions stopped working completely. 

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1559">#c1559</a>)</em></sub></div>

**Comment by alexchopin** [comment]
Hi @Kasheftin,
Can you tried to add a key to `<nuxt-child/>` component?
```js
<nuxt-child :key="$route.name"/>
```

**Comment by Kasheftin** [comment]
I added the key to nuxt-child, but don't see any difference. If I understand correctly, the key should not fix anything, even more, with the key nuxt-child will rerender every time the route changes.

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1737](https://trello.com/c/aYDdKMvz/26-1737)

**Comment by iamdubx** [comment]
This is the same issue? https://github.com/nuxt/nuxt.js/issues/2257

**Comment by homerjam** [comment]
Sort of opposite but potentially related issue above illustrated by [this glitch](https://glitch.com/edit/#!/pumped-eye) - 'nested' page transitions run unnecessarily during layout transitions.

**Comment by chasebank** [comment]
@Kasheftin are you sure you added the key properly? Maybe you just didn't update the repo after you tried it, but the code there doesn't show a key added to the `nuxt-child` element.

Here's a Glitch example showing this working (as far as I can tell) as expected. https://spotted-spaghetti.glitch.me/a?page=1 

The only additional thing I did is add a redirect to the main index.vue, so we start off at the /a route

```
<template>
	
</template>

<script>
export default {
  mounted() {
    this.$router.push({ path: '/a'})
  }
}
</script>
```

I also commented on #2257 which I think is unrelated and potentially also a non-issue

**Comment by Kasheftin** [comment]
I've just found the workaround. I don't know if it helps to fix the initial bug, but if you put the nuxt-child into the div container, it begins to work again. It does not depend on the presence of :key property. 

This one does not work:
   
    a.vue: 
    <template>
      <nuxt-child></nuxt-child>
    </template>

This one works:

    a.vue:
    <template>
      <div>
        <nuxt-child></nuxt-child>
      </div>
    </template>
