### ISSUE TITLE
Work with vue-awesome

### ISSUE THREAD

**Issue by CDuane** [nuxt/nuxt.js#174]
Hi, I am trying to get this awesome framework to work with [vue-awesome](https://github.com/Justineo/vue-awesome) but I can't manage to do it.

I added this to my nuxt.config.js
`build: {
		vendor: ['vue-awesome']
	}`

I added this to my default.vue

`import Icon from "vue-awesome/components/Icon.vue";  
	import "vue-awesome/icons";  `

`
	export default {
		components: {
			Icon
		}
	}`

However when I put icon components in my pages, it does not show, but is visible in the chrome dev tools.

Is there a proper way to do this?

I am new to Nuxt.
Thanks for your help.

**Comment by CDuane** [comment]
Ok I have found what the problem was. I was doing the import in the layout file, so that I refrain from having to import vue-awesome in each page.

However is there a way where I can import it once and the Icon component be usable in every component? This is why I was trying to import it in the layout.

**Comment by Atinux** [comment]
Hi @CDuane 

You need to use the [nuxt plugins]() to register the component as global.

Example:

`nuxt.config.js`
```js
module.exports = {
  build: {
    vendor: ['vue-awesome']
  },
  plugins: ['~plugins/vue-awesome.js']
}
```

`plugins/vue-awesome.js`
```js
import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon.vue'
require('vue-awesome/icons')

Vue.component('icon', Icon)
```

Then in your pages and components, you can use the `<icon>` component:

`pages/index.vue`
```html
<template>
  <div>
    <h1>Welcome!</h1>
    <icon name="camera"></icon>
  </div>
</template>
```

**Comment by bartdominiak** [comment]
Hey,

I'm getting an error
`Nuxt.js Error:

/Users/mac/Sites/nuxt-blog/node_modules/vue-awesome/icons/flag.js:1
(function (exports, require, module, __filename, __dirname) { import Icon from '../components/Icon.vue'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at r (/Users/mac/Sites/nuxt-blog/node_modules/vue-server-renderer/build.js:5812:16)
    at Object.<anonymous> (webpack:/external "vue-awesome/icons/flag":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 2ed152b011919e9b5af8:25:0)
    at Object.module.exports.Object.defineProperty.value (plugins/vue-awesome.js:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 2ed152b011919e9b5af8:25:0)
    at Object.<anonymous> (.nuxt/index.js:25:14)
    at __webpack_require__ (webpack:/webpack/bootstrap 2ed152b011919e9b5af8:25:0)`

**Comment by sobolevn** [comment]
@bartdominiak this happens to me as well.

I am using `"nuxt": "latest",`
@Atinux any suggestions?

**Comment by sobolevn** [comment]
Downgrade to `nuxt==0.10.7` solved my issues.

**Comment by milk-shake** [comment]
Just hopping onto this issue as Nuxt and vue-awesome are not playing nice for me today:

nuxt@1.0.0-rc7
vue-awesome@2.3.1

Following the advice up there works as far as `require('vue-awesome/icons')` which then causes an error but only if **the hot-reload is refreshed or the dev server is restarted**. 

It works fine (as in no error, the icons appear) when I add the require statement while the server is running, but if i stop and run the server after or cmd+r the page I get an error:

`Unexpected token import`
with a load of no stack to follow.

It is even a problem if i import the icons individually in the .vue files, but again - only if i import them from a cold run or if i refresh the view

I'm not really sure how/what to do here, this is the first attempt at trying to use Nuxt so I'm not super clued up.

**Comment by jankal** [comment]
@sobolevn @bartdominiak Same issue here. What can one do to make this work again?

**Comment by MajoDurco** [comment]
For me import error was solved by telling webpack to include `vue-awesome` into the bundle.
So I added this lines into my `nuxt.config.js`:
```javascript
const nodeExternals = require('webpack-node-externals')
module.exports = {
  ...
  build: {
    extend (config, { isServer }) {
      if (isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vue-awesome/]
          })
        ]
      }
    }
}
```
Also you can take a look at #438.

**Comment by Nisthar** [comment]
@MajoDurco Not working for me. If i use your solution, the server is starting up.
But its not compiling modules.
I am using backpack with express as backend

**Comment by uptownhr** [comment]
The issue is with vue awesome. They need to release transpiled version of the code.

**Comment by abdokouta** [comment]
> Hi @CDuane
> 
> You need to use the nuxt plugins to register the component as global.
> 
> Example:
> 
> `nuxt.config.js`
> 
> ```js
> module.exports = {
>   build: {
>     vendor: ['vue-awesome']
>   },
>   plugins: ['~plugins/vue-awesome.js']
> }
> ```
> 
> `plugins/vue-awesome.js`
> 
> ```js
> import Vue from 'vue'
> import Icon from 'vue-awesome/components/Icon.vue'
> require('vue-awesome/icons')
> 
> Vue.component('icon', Icon)
> ```
> 
> Then in your pages and components, you can use the `<icon>` component:
> 
> `pages/index.vue`
> 
> ```
> <template>
>   <div>
>     <h1>Welcome!</h1>
>     <icon name="camera"></icon>
>   </div>
> </template>
> ```
plugins: [{ src: '~plugins/vue-awesome', ssr: false },]

**Comment by manniL** [comment]
https://codesandbox.io/s/github/manniL/nuxt-vue-awesome-example/tree/master/
