### ISSUE TITLE
How add Authorization token in axios header?

### ISSUE THREAD

**Issue by vUdav** [nuxt/nuxt.js#1742]
When I login, I'm get from remote API server user token. When I get token, I'm set him on store and local storage. If I reload my app I want get my token from local storage and set on store. But local storage not defined if I call them on my store:
```javascript
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const store = () => new Vuex.Store({
  user: {
    token: localStorage.getItem('userToken')
  }
})
```

or ~plugins/axios.js:
```javascript
import axios from 'axios'

export default axios.create({
  baseURL: process.env.baseApiUrl,
  headers: {
    'Authorization': 'Bearer '+localStorage.getItem('userToken')
  }
})
```

How can I resolve this problem?

P.S. sorry for my English

**Comment by homerjam** [comment]
`localStorage` is a client side API, you can determine if the code should run using the context passed to plugins eg.

```js
export default ({ isClient }) => {
  // do codez
}
```

Or a better solution would probably be to use the nuxt-modules/axios library which optimises axios for use within nuxt.

**Comment by alexchopin** [comment]
Hi @vUdav,
I recommend you to use the [nuxt-community/axios-module](https://github.com/nuxt-community/axios-module#settokentoken-type-scopescommon) which allows you to set axios header easily.
