### ISSUE TITLE
Application does not load in SPA mode?

### ISSUE THREAD

**Issue by PrimozRome** [nuxt/nuxt.js#1745]
If I switch my app into SPA mode by adding `mode: 'spa'` into `nuxt.config.js` the app wont load anymore. I run `npm run dev` and load the app in browser but the app goes into infinitive loading... The loading spinner keeps spinning and I need to kill the browser tab ...

![screen shot 2017-09-28 at 01 01 40](https://user-images.githubusercontent.com/1180467/30942108-3539836a-a3e9-11e7-9b0b-71fa0520c7b6.png)

What am I doing wrong here?

**Comment by PrimozRome** [comment]
I have figured out that this line in my auth.js middleware does not redirect to the `/auth/login` but just keeps getting in the same route. What happening here `/auth/login` does not have this middleware assigned?

export default function ({ store, redirect, app, isClient }) {
  console.log('auth.middleware')
  console.log(store.state.auth.authenticated)

  if (!store.state.auth.authenticated) redirect('/auth/login')
}

**Comment by nikkanetiya** [comment]
@PrimozRome Can you check your console please, it same happens with me but don't stop initial but it will stop on after some hot reload or when I refresh page 2-3 times. But I am sure you can see some errors in console before that tab hangs.

**Comment by PrimozRome** [comment]
@nikkanetiya I dont see any errors in console unfortunately

**Comment by Atinux** [comment]
@PrimozRome did you assign this middleware into your `nuxt.config.js`? If so, it's run for all pages.

You need to avoid checking if the user is connected on `/auth/login` route:

```js
export default function ({ store, redirect, app, isClient, route }) {
  console.log('auth.middleware')
  console.log(store.state.auth.authenticated)
  if (route.path === '/auth/login') rturn
  if (!store.state.auth.authenticated) return redirect('/auth/login')
}
```

**Comment by PrimozRome** [comment]
@Atinux no the middleware is assigned only to the default layout. For authentication I have another layout and this middleware is not assigned.
