### ISSUE TITLE
Webpack doesn't load images from `assets` if using template literals

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1746]
I am trying to use something like this

```html
<div :style="type ? {'background-image': `url('~assets/images/${type}.svg')`, 'background-position': '96% 50%'} : ''"></div>
```

But Nuxt doesn't resolve this path. `GET http://localhost:3333/~assets/images/amex.svg 404 (Not Found)`

Then I tried simple 

```html
<img :src="`~assets/images/amex.svg`">
```
But this one doesn't work too, so the issue only when using literals. 

Any chance to fix this behavior?

**Comment by iamdubx** [comment]
Fix it by using `require`.

**Comment by qiqiwwq7** [comment]
how to fix it ?? how to use `require` @iamdubx

**Comment by wdehaes** [comment]
For future googlers stranded on this issue, the following links will help you out:

- https://github.com/nuxt/nuxt.js/issues/448
- https://github.com/vuejs/Discussion/issues/202
