### ISSUE TITLE
Cannot use external component on Heroku production

### ISSUE THREAD

**Issue by 1sttati** [nuxt/nuxt.js#1749]
I was using "vue-switches" on my nuxt project
I can run on my PC without any problem. "npm run build" also working fine.

But when I push to Heroku, it cannot be built.
![untitled](https://user-images.githubusercontent.com/6259199/30958471-77a69b6a-a467-11e7-850a-4aa67cd67106.png)

When remove "vue-switches" from package.json and push to Heroku, then it works.

any solution?

**Comment by vuchl** [comment]
You followed this guide: https://nuxtjs.org/faq/heroku-deployment ?

**Comment by 1sttati** [comment]
Yes, normally I can deploy
But just add by "vue-switches" to package.json, without doing anything, it cannot deploy

**Comment by vuchl** [comment]
is it in `devDependencies` or `dependencies` in your package.json?

**Comment by 1sttati** [comment]
I put it in `dependencies`

**Comment by vuchl** [comment]
do a `npm install --save-dev vue-switches` too and try to redeploy

**Comment by 1sttati** [comment]
`devDependencies` also cannot deploy

**Comment by vuchl** [comment]
Can you try to create a minimal reproduction repo?

**Comment by 1sttati** [comment]
Well, I found the problem, it was in my code.
It's about case sensitive
I had import component like this:
```
import Modal from '@/components/common/Modal.vue'

export default {
  components: {
    modal: Modal
  },
}
```

and using like 
`<modal></modal>`

So I change all of it to `Modal`, then it works.

Thank you
