### ISSUE TITLE
nuxtServerInit does not work if it is not in store/index.js

### ISSUE THREAD

**Issue by Mirodil** [nuxt/nuxt.js#175]
`nuxtServerInit` does not work in it is not in `store/index.js`. if you rename 'store/index.js` to something else function `nuxtServerInit` never runs in server side.

**Comment by Atinux** [comment]
Hi @Mirodil 

It's an expected behaviour, please see https://github.com/nuxt/nuxt.js/issues/169#issuecomment-275759867

**Comment by Mirodil** [comment]
but is it odd, index.js can use `nuxtServerInit` function but `todo.js` cannot use the same function? and also you cannot have `index.js` and `todo.js` under `store` folder. it will load only `index.js`

**Comment by Atinux** [comment]
It depends of how you export your store in your `index.js` file @Mirodil 

Can you provide us your `index.js`?
