### ISSUE TITLE
Nuxt generate and gh-pages issue

### ISSUE THREAD

**Issue by pirony** [nuxt/nuxt.js#1751]
I created a vue plugin and wanted to use Nuxt  to generate the demo site, then host it on github project pages.
Once generated,after testing it successfully in a local http-server, I pushed /dist content to gh-pages branch.
The problem is that all assets under  /_nuxt folder return 404 despite the .nojekyll file in repo.
It seems that the browser tries to load _nuxt assets from user.github.io instead of user.github.io/project-name.
Any idea on what cause that issue?

Thanks

**Comment by alexchopin** [comment]
Hi @pirony,
Have you tried to set `router.base` option in your `nuxt.config.js` file with the name of your github project?
```js
  router: {
    base: '/project-name/'
  }
```
https://nuxtjs.org/api/configuration-router#base

**Comment by pirony** [comment]
Hi @alexchopin, good catch!!! I'd better read the docs in depth next time ahah!!
Thanks and keep up the good work... Nuxt.js is awesome!!!
