### ISSUE TITLE
Transition single element

### ISSUE THREAD

**Issue by jamilabreu** [nuxt/nuxt.js#1752]
I'm seeing examples on how to transition pages and layouts, but not able to figure out how to transition a single element.

For example: I have a `Header` component shared between two pages. 

Inside the `Header` component I have an element whose content changes based on the route, but otherwise remains the same. 

I'd like to add a transition effect to that element only. Is that currently possible?

( I tried wrapping the element in a `<transition>` tag and adding a `v-if/else` directive with no luck.)

**Comment by pirony** [comment]
What about v-if="$route.name === 'routeName'" wrapped in transition?
It should work!

**Comment by jamilabreu** [comment]
@pirony After some tinkering I'm seeing that adding `appear` to `transition` as noted [here](https://vuejs.org/v2/guide/transitions.html#Transitions-on-Initial-Render) works.

Now I'm seeing though that nuxt isn't firing any "leave" javascript hooks. I  have the following:

`<transition v-on:before-enter="beforeEnter" v-on:enter="enter" v-on:after-enter="afterEnter" v-on:before-leave="beforeLeave" v-on:leave="leave" v-on:after-leave="afterLeave" appear>`

and only beforeEnter, enter, and after Enter are firing:

`  methods: {
    beforeEnter: function(el) {
      console.log(el)
      console.log("beforeEnter");
    },
    enter: function(el, done) {
      console.log("enter");
      done();
    },
    afterEnter: function(el) {
      // console.log(el)
      console.log("afterEnter");
    },
    beforeLeave: function(el) {
      console.log(el)
      console.log("beforeLeave");
    },
    leave: function(el, done) {
      console.log("leave");
      done();
    },
    afterLeave: function(el) {
      // console.log(el)
      console.log("afterLeave");
    },
  }
}`

Is that correct? If so, are leave hooks available some other way?

**Comment by jamilabreu** [comment]
I'm also seeing that .[name]-leave-active, .[name]-leave, and .[name]-leave-to css classes aren't being added - only the -enter classes. 🤔

**Comment by jamilabreu** [comment]
page transitions work for both `enter` and `leave`, but when using `<transition>` inside a page, only `enter` (as well as `appear`) work.

**Comment by iamdubx** [comment]
I have similar issue. Only part of transition is working. In my case - Enter transition doesn't work at all! https://github.com/nuxt/nuxt.js/issues/1766
