### ISSUE TITLE
Build and generate command results to "require is not defined" error

### ISSUE THREAD

**Issue by JerelynCo** [nuxt/nuxt.js#1753]
Hi,

I'm trying to deploy my project by issuing `nuxt build` command. However, "require is not defined" error shows up in the browser. I can't seem to track the source of the error. This also happens using `nuxt generate` . Weirdly, my application works fine in dev server.

Screenshot below shows the error in the browser:
![image](https://user-images.githubusercontent.com/8834612/30975236-58327b22-a4a4-11e7-8462-fc29f10f0249.png)

Here are my dependencies:
"dependencies": {
    "axios": "^0.16.2",
    "nuxt": "^1.0.0-rc11",
    "uiv": "^0.11.9",
    "vue-awesome": "^2.3.3"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1"
  }

What could be the cause of this error?

**Comment by alexchopin** [comment]
Hi @JerelynCo,
Which version of node.js are you using?

**Comment by JerelynCo** [comment]
Hi @alexchopin , it's 6.11.2. Should I upgrade/downgrade?

Thanks!

**Comment by JerelynCo** [comment]
Leaving here my nuxt build config.

```
build: {
    /*
    ** Run ESLINT on save
    */
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      } else {
        const babelLoader = config.module.rules.find((rule) => rule.loader === 'babel-loader')
        babelLoader.exclude = /node_modules\/(?![uiv])/

        config.externals = [
          nodeExternals({
            whitelist: [/\.(?!(?:js|json)$).{1,5}$/i, /^vue-awesome/]
          })
        ]
      }
    }
  }
```

**Comment by clarkdo** [comment]
Can you have a try on 1.0.0 ?

**Comment by mlyticsAdamGe** [comment]
I'm using the 1.0.0,there is the ```require is not defined``` error
