### ISSUE TITLE
Modules added files - forces a recompile 

### ISSUE THREAD

**Issue by gdeividas** [nuxt/nuxt.js#1759]
Hi,

So i've built a nuxt module which adds css files to nuxt `srcDir/assets` dir that causes recompilation after the initial compilation. 

According to docs - "Modules are basically functions which are called sequentially when booting Nuxt" - so no watchers should yet be initialized and the folders/files should not be watched yet. 

So to get to my question and maybe a bug/feature request. Can this be altered somehow? can I add files to projects asset directory without triggering watcher/recompile? If not maybe it's worth to think about it and implement a hook or similar.

**Comment by alexchopin** [comment]
Hi, 
Nuxt core has watchers the `assets` folder by default so any changes will be triggered by the core watchers.
Can you give us more information about what you want to accomplish with your module?
I'm closing the issue as it's not really one but we can still comment on it to find a solution.
