### ISSUE TITLE
e2e tests of nuxt application

### ISSUE THREAD

**Issue by PavelPolyakov** [nuxt/nuxt.js#176]
Hi,

Here in the basic test example:
https://nuxtjs.org/guide/development-tools

It's suggested to use the API method [renderAndGetWindow](https://nuxtjs.org/api/nuxt-render-and-get-window). It's clear that we can get the html under the route X and then assert the content received.

My question is - how to perform more complex tests using the suggested API? The ones like - login functionality or fill the form and click the submit button and after - assert the new html. I understand how to do it with [nightwatch](http://nightwatchjs.org/) for example, but it would require running server.

Any thoughts are welcome.

Regards,

**Comment by Atinux** [comment]
Hi @PavelPolyakov 

Indeed for this king of unit testing [nighwatch](http://nightwatchjs.org/) is recommended, I don't have any example but I would love to see one if you are going to try it 👍
