### ISSUE TITLE
Parent component gets remounted when navigating to child routes

### ISSUE THREAD

**Issue by JamieLottering** [nuxt/nuxt.js#1761]
So first of all I'll give you a link to a fiddle demonstrating the expected behavior. This demo is using plain vue with vue-router

[Expected behavior](https://jsfiddle.net/e6Lbvt40/)

I set some initial state on the parent route, and navigating to and from the child route does not change the parent route.

However, when using nuxt I experience the following behavior.
[Unexpected behavior](https://www.dropbox.com/s/bkxiqpn6wbept1y/unexpected-behavior-nuxt.mov?dl=0)

In this instance I am using nuxt-child instead of router-view and Nuxt page components instead of plain vue components. The routes are generated by my directory structure which looks like:

```
pages/
--random.vue
--random/
----_slug.vue
```

I believe this may be related to another issue I raised #1756

**Comment by JamieLottering** [comment]
Looks like it's happening in lib/app/client.js#fixPrepatch

**Comment by JamieLottering** [comment]
Heres a video I took after creating my pull request demonstrating the correct behavior
[fixed behavior](https://www.dropbox.com/s/7s4hzk070y5bq8b/fixed-behavior.mov?dl=0)

You can also see that the /test route uses the exact same component, but the data is regenerated as it should. Child routes however do not change the parent

**Comment by JamieLottering** [comment]
This issue is solvable simply by putting a dummy index.vue file inside of the child route folder

```
pages/
--random.vue
--random/
----**index.vue**
----_slug.vue
```

**Comment by lordfuoco** [comment]
This should be in the docs somewhere. I struggled with this A lot before finding this and solving the issue
