### ISSUE TITLE
How to set the resource path in js

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#1763]
I want to set the path of a resource (SWF) in js, because this is the required parameter of a plug-in, so how do I write the path? help! @Atinux @pi0

**Comment by Atinux** [comment]
@fengjiel you need to extend the loaders to use the file loader for `.swf` extension (https://stackoverflow.com/questions/33715782/how-to-load-swf-file-with-webpack), in your `nuxt.config.js`:

```js
module.exports = {
  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.swf$/,
        loader: 'file-loader',
        options: {
          name: 'swf/[name].[hash:7].[ext]'
        }
      })
   }
}
```
