### ISSUE TITLE
Vue2-google-maps build error

### ISSUE THREAD

**Issue by janhox** [nuxt/nuxt.js#1764]
Hi, I am using vue2-google-maps as a plugin in my project (1.0.0-rc6).
Works all fine locally but when building for production receive the below error.
Any thoughts on this ?
Thanks.
<img width="910" alt="screen shot 2017-09-30 at 17 40 45" src="https://user-images.githubusercontent.com/24571106/31047250-5542cc1e-a607-11e7-927a-9f159daa3f15.png">

**Comment by homerjam** [comment]
Most likely an issue with uglifyjs and babel, you might be able to exclude the module from the relevant part of the build process. Also it might be worth updating nuxt.

**Comment by janhox** [comment]
I have bumped the version of vue2-google-maps to 0.7.10 which works fine now.

**Comment by Serdgjo** [comment]
Also consider this issue: https://github.com/xkjyeah/vue-google-maps/issues/206
