### ISSUE TITLE
Client.js -> TypeError: Cannot read property 'load' of undefined

### ISSUE THREAD

**Issue by PrimozRome** [nuxt/nuxt.js#1767]
I am running in SPA mode and I am getting this error while trying to access NuxtJS page `http://localhost:3000/auth/login`. If I go to `universal` mode I can access page normally. I have no page and/or layout middleware assigned.

![screen shot 2017-10-02 at 12 18 43](https://user-images.githubusercontent.com/1180467/31073349-e117bcb2-a76b-11e7-8e25-65cae42473bf.png)

client.js:50 TypeError: Cannot read property 'load' of undefined
    at VueComponent.mounted (auth.vue:28)
    at callHook (vue.runtime.esm.js:2661)
    at insert (vue.runtime.esm.js:3522)
    at Object.invoker [as insert] (vue.runtime.esm.js:1806)
    at invokeInsertHook (vue.runtime.esm.js:5465)
    at Vue$3.patch [as __patch__] (vue.runtime.esm.js:5635)
    at Vue$3.Vue._update (vue.runtime.esm.js:2410)
    at Vue$3.updateComponent (vue.runtime.esm.js:2534)
    at Watcher.get (vue.runtime.esm.js:2877)
    at new Watcher (vue.runtime.esm.js:2866)
webpackJsonp../.nuxt/client.js.__WEBPACK_IMPORTED_MODULE_6_vue__.default.config.errorHandler @ client.js:50
handleError @ vue.runtime.esm.js:555
callHook @ vue.runtime.esm.js:2663
insert @ vue.runtime.esm.js:3522
invoker @ vue.runtime.esm.js:1806
invokeInsertHook @ vue.runtime.esm.js:5465
patch @ vue.runtime.esm.js:5635
Vue._update @ vue.runtime.esm.js:2410
updateComponent @ vue.runtime.esm.js:2534
get @ vue.runtime.esm.js:2877
Watcher @ vue.runtime.esm.js:2866
mountComponent @ vue.runtime.esm.js:2538
webpackJsonp../node_modules/vue/dist/vue.runtime.esm.js.Vue$3.$mount @ vue.runtime.esm.js:7397
mountApp @ client.js:525
(anonymous) @ client.js:567
_callee2$ @ client.js:323
tryCatch @ runtime.js:65
invoke @ runtime.js:299
prototype.(anonymous function) @ runtime.js:117
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
F @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
render @ client.js:192
_callee3$ @ client.js:563
tryCatch @ runtime.js:65
invoke @ runtime.js:299
prototype.(anonymous function) @ runtime.js:117
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
F @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
mountApp @ client.js:506
Promise resolved (async)
./.nuxt/client.js @ client.js:58
__webpack_require__ @ bootstrap 73dabf96cdbcdcacd7b0:710
fn @ bootstrap 73dabf96cdbcdcacd7b0:115
0 @ notifications.js:7
__webpack_require__ @ bootstrap 73dabf96cdbcdcacd7b0:710
webpackJsonpCallback @ bootstrap 73dabf96cdbcdcacd7b0:25
(anonymous) @ app.12bc2a4d77cee555862d.js:1

**Comment by Atinux** [comment]
Related to #1768

**Comment by PrimozRome** [comment]
I have figured out this is the issue of my application. In the `auth` page I am loading a static asset `/particlesjs-config.json`. 

```
  mounted: function () {
    window.particlesJS.load('particles', '/particlesjs-config.json')
  }
``

This works in `ssr` mode but not in `spa`. This asset is loaded by this particles.js library

```
window.particlesJS.load = function(tag_id, path_config_json, callback){

```
  /* load json config */
  var xhr = new XMLHttpRequest();
  xhr.open('GET', path_config_json);
  xhr.onreadystatechange = function (data) {
    if(xhr.readyState == 4){
      if(xhr.status == 200){
        var params = JSON.parse(data.currentTarget.response);
        window.particlesJS(tag_id, params);
        if(callback) callback();
      }else{
        console.log('Error pJS - XMLHttpRequest status: '+xhr.status);
        console.log('Error pJS - File config not found');
      }
    }
  };
  xhr.send();
};
```

Any ideas why this would not be loaded in `spa` mode?

**Comment by PrimozRome** [comment]
Okay the probelm is that external resource is not loaded on the page in `spa` mode. I was loading `particles.js` in the page like this:

```
  head () {
    return {
      script: [
        { src: 'https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js' }
      ]
    }
  },
```

This was loaded in the `ssr` mode but in `spa` it is not. If I load this resource in `nuxt.config.js` then everything works okay. 

Any idea why the external resource is not loaded in page `head` ?
