### ISSUE TITLE
prefetching data from server

### ISSUE THREAD

**Issue by yyss8** [nuxt/nuxt.js#177]
hi, I'm pretty new to nuxt and I'm currently using it as a middleware in my express project

I'm wondering is it possible to do custom context with using nuxt build() so I can pass data from the server like what ejs or jade does.

I tried using nuxt.renderRoute() by passing only res and req as context but it returns 404 on any page somehow

I've read all the examples and most of them were only about client side features. 

thank you

**Comment by yyss8** [comment]
I actually just figured out a way to do so by creating a express router before nuxt to load all the prefetch data and  store them in req just like req.session. 
Not sure if this is a good practice but it's definitely what I need at this time

**Comment by Atinux** [comment]
@yyss8 indeed you can use `req.session` or add properties to `req` and use them in `data`.

You can take a look at this example too: https://github.com/nuxt/example-todomvc
