### ISSUE TITLE
srcDir

### ISSUE THREAD

**Issue by peteringram0** [nuxt/nuxt.js#1772]
When running with the config as 

````javascript
module.exports = {
    srcDir: resolve('./app'),
}
````

I get the following error:

````javascript
ERROR in multi vue vue-router vue-meta
````

Is this issue linked to #43 ? Thanks.

**Comment by Atinux** [comment]
You may want to give `rootDir` as well to be sure that is can resolve `node_modules/` folder @peteringram0 

Do you have a reproduction repository so we can take a deep look at it?

**Comment by cretueusebiu** [comment]
@peteringram0 Just set it to "app".

```javascript
module.exports = {
    srcDir: 'app',
}
```

Assuming that you have the following directory structure:

```
.
├── node_modules/
├── app/
└── nuxt.config.js
```
