### ISSUE TITLE
[QUESTION] Disabling route-link while loading

### ISSUE THREAD

**Issue by atmar** [nuxt/nuxt.js#1773]
Is it possible to disable route-link while the page is loading? Currently a visitor can click 10 times in a row on a route-link and it will fetch the data 10 times. Is it possible to only run once no matter how many time the visitor clicks it? I have visitors that click a link multiple times because the page they clicked is still being loaded.

**Comment by Atinux** [comment]
Actually I recommend you to use a custom loading page which has an overlay fixed so this way the user cannot click on the link anymore, or to disable the link when clicked.

See https://github.com/nuxt/nuxt.js/tree/dev/examples/custom-loading for the custom loading component.

**Comment by atmar** [comment]
Disabling the link when clicked is what I'm looking for rather than an overlay while loading. Should I globally add a class to all <a> tags while loading at start() and remove when finished? Or what is the best solution to disable links while loading
``` 
   start () {
      this.loading = true
    },
    finish () {
      this.loading = false
    }
```

**Comment by Atinux** [comment]
Actually I believe it's mostly an UX issue, you need to give instant feedback to user when he clicked on a link to avoid him to click again. You can create you custom component to use `<nuxt-link>` inside and when clicked, disable it directly.
