### ISSUE TITLE
How work with vue plugins like tinymce-vue-2

### ISSUE THREAD

**Issue by mclighter** [nuxt/nuxt.js#1775]
I try to add tinymce to Nuxt

**nuxt.config.js**

```
plugins: [{src: '~/plugins/vue2-tiny', ssr: false}],

build: {
    vendor: ['tinymce','tinymce-vue-2'],

```

**vue2-tiny.js**
```
import Vue from 'vue'
import TinyMCE from 'tinymce-vue-2'

Vue.component('tiny-mce', TinyMCE)
```

**edit.vue**
in my view i add 

  `<tiny-mce id="description" v-model="h"></tiny-mce>
`

But get an error 
```
GET http://localhost:3000/_nuxt/themes/modern/theme.js net::ERR_ABORTED
Uncaught TypeError: Theme is not a constructor
```

How i can add themes/modern/theme.js to my nuxt project?

**Comment by homerjam** [comment]
Have you tried...

```
import Theme from 'tiny-mce/themes/modern/theme';
```

**Comment by mclighter** [comment]
Thanks!
it works

**vue2-tiny.js**
```
import Vue from 'vue'
import TinyMCE from 'tinymce-vue-2'
import Theme from '~/node_modules/tinymce/themes/modern/theme'

if (process.env.BROWSER) {
  window.Theme = Theme
}
Vue.component('tiny-mce', TinyMCE)

```
But have problem with css called from tinymce
```
GET http://localhost:3000/_nuxt/skins/lightgray/skin.min.css net::ERR_ABORTED
GET http://localhost:3000/_nuxt/skins/lightgray/content.min.css net::ERR_ABORTED
```

I added needed styles to nuxt.config.js and tinimce work fine but bad requests still exist

**nuxt.config.js**
```
css: [
    '~assets/css/blog.css',
    '~assets/css/page_animation.css',
    '~node_modules/tinymce/skins/lightgray/skin.min.css',
    '~node_modules/tinymce/skins/lightgray/content.min.css'
  ],
```

**Comment by homerjam** [comment]
Are you adding tiny-mce plugin/component into nuxt.config? Perhaps `ssr: false`

**Comment by calebanthony** [comment]
I don't think it's related to the problem, but you shouldn't need to prefix your assets with `~node_modules`. Just do:
`tinymce/skins/lightgray/skin.min.css`
and that will work.

But in regards to that plugin, do you have TinyMCE installed? It looks like all that package does is "vue-ify" TinyMCE. So make sure that you also have a plugin that's bringing in TinyMCE and make sure `window.tinymce` is available, same way that you're currently doing with `Theme`.

**Comment by mirhat** [comment]
@mclighter Can you please share configuration that is working for you. I can't get it to work.
Tinymce.js plugin
`import Vue from 'vue'
import TinyMCE from 'tinymce-vue-2'
import Theme from 'tinymce/themes/modern/theme'

if (process.env.BROWSER) {
  window.Theme = Theme
}
Vue.component('tinymce', TinyMCE)`

nuxt.config.js
`loaders: [
    { 
      test: require.resolve('tinymce/tinymce'), 
      loader: 'expose-loader?tinyMCE!expose-loader?$'
    }
  ],
css: [
    'tinymce/skins/lightgray/skin.min.css',
    'tinymce/skins/lightgray/content.min.css'
  ],
plugins: [
            { src: '~/plugins/tinymce.js', ssr: false }
  ],
plugins: [
      new webpack.ProvidePlugin({
        'tinymce': 'tinymce',
      })
    ]
`

**Comment by mclighter** [comment]
I solved an issue as follows:

**nuxt.config.js**

```
...
plugins: [{src: '~/plugins/vue2-editor', ssr: false}],
build: {
    vendor: ['tinymce-vue-2']
....
}

```

**vue2-editor.js**

```
import Vue from 'vue'
import TinyMCE from 'tinymce-vue-2'
import 'tinymce/tinymce'
import 'tinymce/plugins/link/plugin'
import 'tinymce/plugins/image/plugin'
import 'tinymce/plugins/advlist/plugin'
import 'tinymce/plugins/autolink/plugin'
import 'tinymce/plugins/lists/plugin'
import 'tinymce/plugins/charmap/plugin'
import 'tinymce/plugins/print/plugin'
import 'tinymce/plugins/preview/plugin'
import 'tinymce/plugins/code/plugin'
import Theme from 'tinymce/themes/modern/theme'
import 'tinymce/skins/lightgray/skin.min.css'
import 'tinymce/skins/lightgray/content.min.css'

if (process.env.BROWSER) {
  window.Theme = Theme
}
Vue.component('tiny-mce', TinyMCE)
```

and also i use <no-ssr> in template

```
<no-ssr>
        <tiny-mce id="desc" v-model="content.content"
          :other-props="{plugins :'link image',skin_url: '/css/lightgray'}"
          :toolbar="['undo redo']">
        </tiny-mce>
</no-ssr>
```

**Comment by mirhat** [comment]
@mclighter Thank you very much

**Comment by juppdes** [comment]
@mclighter Can you please pass me the packages installed ? 
Only tinymce-vue-2 (https://github.com/mbouclas/tinymce-vue-2) ?
