### ISSUE TITLE
Plain html links <a> reloads the app

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#1777]
Hi!

I created a blog platform. User creates documents inside wysiwyg editor (tinymce).
Very often inside the article users adds links to other articles `<a href="/some-other-article">Link</a>`

The problem is that the <a> tags reloads the whole app :(
How can I handle it the force <a> to behave like a <nuxt-link>?

Thanks for help in advance,

**Comment by iamdubx** [comment]
You need to use `nuxt-link` not `a`

**Comment by Atinux** [comment]
@awronski you may want to take a look at this: https://github.com/nuxt/nuxtjs.org/blob/master/components/HtmlParser.vue

Mostly on `addListeners` method.
