### ISSUE TITLE
how can i go to another route in js?

### ISSUE THREAD

**Issue by viktor-vasilev** [nuxt/nuxt.js#1780]
I tried this.$router.push("/path/") but this broke my layout like this:
https://yadi.sk/i/w2tGLFoj3NTwyw

And layout goes to normal only after refresh:
https://yadi.sk/i/_SLX6yug3NTwy8

**Comment by cretueusebiu** [comment]
It looks like there might be something wrong with the page you're trying to access.
The `this.$router.push` method works just fine.

**Comment by viktor-vasilev** [comment]
but this root is just an empty layout with some few tags without js.

**Comment by cretueusebiu** [comment]
Can you post the template ?

**Comment by viktor-vasilev** [comment]
Sure

`
<template>
  <div>
    <el-row>
      <el-col :span="12"><h1>{{PageName}}</h1></el-col>
      <el-col :span="12" style="text-align:right;">
        <el-date-picker v-model="now" type="date" placeholder="Текущая дата" disabled> </el-date-picker>
      </el-col>
    </el-row>
  </div>
</template>

<script>
import root from '../api/root.js'
export default {
  layout: 'admin',
  data () {
    return {
      PageName: 'Дневная активность',
      now: Date.now()
    }
  }
}
</script>

<style>
</style>
`

**Comment by viktor-vasilev** [comment]
hmm....sorry that i bothered you. Its somehow used global styles from previous layout. When i made separated css classes for blocks problem disappeared

**Comment by viktor-vasilev** [comment]
hmm....sorry that i bothered you. Its somehow used global styles from previous layout. When i made separated css classes for blocks problem disappeared
