### ISSUE TITLE
Multiple NuxtJS Instances

### ISSUE THREAD

**Issue by XEngine** [nuxt/nuxt.js#1785]
Hei! I wonder if nuxtjs can multiply installed on a shared express framework. like one nuxtjs for storefront another nuxtjs setup for admin dashboard but sharing the same express app.js

something like this can be achievable?

Eg : 
./
--**server**
--**storefront** -> srcDir for storefront
    ----pages
    ----components..
--**dashboard** -> another srcDir for admin dashboard
    ----pages
    ----components..
--**app.js**
--**nuxt.config.js**
--**package.json**

nuxt config can be an object like
```json
storefront: {
 "head": {},
 "build": {}
},
dashboard: {
 "head": {},
 "build" : {}
}
```

**Comment by cretueusebiu** [comment]
I have something like this:

```
.
├── node_modules/
├── src/
|   ├── storefront/
|   |   ├── nuxt.config.js
|   |   ├── pages
|   |   └── components 
|   └── dashboard/
|   |   ├── nuxt.config.js
|   |   ├── pages
|   |   └── components 
|   └── shared/
|       ├── nuxt.config.js  
|       └── components   
|    
└── package.json
```

Both config files from `storefront` and `dashboard`  extend the `shared/nuxt.config.js` because I have some things that I don't want to duplicate.

In `storefront/nuxt.config.js` I have:

```javascript
{
   srcDir: __dirname, 
   buildDir: '.nuxt/storefront',
   ...
}
```

And `dashboard/nuxt.config.js`:

```javascript
{
   srcDir: __dirname, 
   buildDir: '.nuxt/dashboard',
   ...
}
```

And my scripts in `package.json` look like this:

```json
"scripts": {
  "storefront:dev": "nuxt --config-file src/storefront/nuxt.config.js -p=3000",
  "dashboard:dev": "nuxt --config-file src/dashboard/nuxt.config.js -p=4000",
  "dev": "concurrently \"npm run storefront:dev\" \"npm run dashboard:dev\"",
  "storefront:build": "nuxt build --config-file src/storefront/nuxt.config.js",
  "dashboard:build": "nuxt build --config-file src/dashboard/nuxt.config.js",
  "storefront:start": "nuxt start --config-file src/storefront/nuxt.config.js",
  "dashboard:start": "nuxt start --config-file src/dashboard/nuxt.config.js"
},
```

I use [concurrently](https://www.npmjs.com/package/concurrently) so I can run both apps from the same command.

Now I can build and run both apps from the same source code.

**Comment by XEngine** [comment]
@cretueusebiu Thank you for this! Very appreciated man!

**Comment by XEngine** [comment]
in my case using express, this makes two different applications using same express base.

**Comment by tforssander** [comment]
@cretueusebiu How did you solve when merging front/dashboard configs with the shared config that contains the `extend () { ... }` function? I get other objects/arrays working.

**Comment by cretueusebiu** [comment]
The `build` property is not shared in my case.

**Comment by ngodink** [comment]
excuse me..
I run `npm run build` using concurrently to build all projects, its successfull, but I want make shared modules to separate folder, so in each build folder, there are no duplicated modules.. what should i do?

**Comment by motia** [comment]
@ngodink , you should create a folder in the root directory then create symlinks to it in each nuxt app folder.

**Comment by ngodink** [comment]
@motia , @cretueusebiu .. sorry, how i use the "shared" folder from storefront/dashboard directory (ex: creating global instances or calling methods from shared folder) ? give me an example please..

**Comment by paolog22** [comment]
can i still have a main config file like this :
`.
├── node_modules/
├── src/
|   ├── storefront/
|   |   ├── nuxt.config.js
|   |   ├── pages
|   |   └── components 
|   └── dashboard/
|   |   ├── nuxt.config.js
|   |   ├── pages
|   |   └── components 
|   └── shared/
|       ├── nuxt.config.js  
|       └── components   
|    
└── package.json
-------nuxt.config.js (this has the common conifg file like global css('bootstrap') .. etc)` 

thanks
