### ISSUE TITLE
Setting different value to env variable in dev, test and production environment.

### ISSUE THREAD

**Issue by MatUrbanski** [nuxt/nuxt.js#1789]
In `nuxt.config.js` I have the following env variable:

```
  env: {
    API_URL: 'http://localhost:3000/api/'
  }
```

I want to set this `API_URL` variable different value when I'm in production, test or dev environment.
How can I do this?

**Comment by cretueusebiu** [comment]
Install [dotenv](https://www.npmjs.com/package/dotenv) then in your `nuxt.config.js` file add:

```javascript
require('dotenv').config()
```

Now you can create a `.env` file (that you don't commit) for your local env and one on your production server.

Each env variable that you define in the `.env` file will be available in your js files with `process.env.VAR_NAME`.

**Comment by NicoPennec** [comment]
@MatUrbanski 

With `axios`, I use this way:

```js
// nuxt.config.js

env: {
  DEV_API: 'http://localhost',
  PROD_API: '/proxy'
}
```

and in my `asyncdata` method:
```js
// page.vue
axios.defaults.baseURL = isDev ? env.DEV_API : env.PROD_API
let { data } = await axios.get(`/api/search`)
``

**Comment by PrimozRome** [comment]
@cretueusebiu thanks for this tip.

Any idea why `process.env.BASE_URL` would return undefined inside store module? Looks okay and it ready in `nuxt.config.js` but getting `undefined` inside store?

**Comment by FabianEllenberger** [comment]
Hey @NicoPennec your answer seem exactly like what i need, thanks! Could you quickly explain how you did the condition ```isDev ?```.

I need to do the exact same thing but im not sure how to check if im on dev or production mode.
Im building my app with ```nuxt generate``` and doing an axios call on ```page.vue```.

Many thanks in advance! 🙏🏻

**Comment by PrimozRome** [comment]
@FabianEllenberger we use [dotenv library](https://github.com/motdotla/dotenv) to read .env files and works perfectly... In `nuxt.config.js`you include `require('dotenv').config()` and then you can call pretty much everywhere `

.env file looks like this:

```
BASE_URL=http://api.url
CLIENT_ID=2
CLIENT_SECRET=sadfsdklfjdslkfjlksdfjlksdjf
...
```

**Comment by FabianEllenberger** [comment]
@PrimozRome Thanks for the fast answers! I'm gonna take a look at dotenv! What I don't really like is having a ```.env``` file on production or both on dev and production side, in my case I think it's better to have the ```NODE_ENV`` set for specific build scripts (i could add for example ```"generate-local": "NODE_ENV=dev nuxt generate")```for testing the generate with the dev envirnoment).

But maybe after taking a look at ```dotenv```im convinced that an ```.env``` file is better :-).
Thanks again! 👍

**Comment by franzos** [comment]
If you're on Heroku, you can simply pass the local env. variables via package.json dev startup script, and add the production variables via Heroku CLI.

**Comment by baronTommy** [comment]
@MatUrbanski

`console.log(process.env.xxx)`
https://nuxtjs.org/api/configuration-env/

**Comment by maisnamraju** [comment]
Hey guys, if anyone is still facing this issue. Here is something that I came up with for my workflow 
http://blog.maisnamraju.com/2018/08/31/dynamic-environments-in-nuxtjs.html

**Comment by wienska** [comment]
Hi! Is there any way to use different env files (.env.dev, .env.prod etc.) for different deployment commands?

**Comment by maisnamraju** [comment]
@wienska  you could simple adding the package.json with different commands

**Comment by zadavan** [comment]
> @wienska you could simple adding the package.json with different commands

How exactly?

**Comment by aldarund** [comment]
https://www.npmjs.com/package/env-cmd
