### ISSUE TITLE
Concurrent ajax requests to populate data

### ISSUE THREAD

**Issue by jubairsaidi** [nuxt/nuxt.js#179]
might just be a noob question but I can't seem to figure out how to populate the data object for a given page using 3 concurrent requests (page content, page meta and page navigations are 3 separate calls in order to speed up page load speed).  So my question is, how do we do this?  I tried putting all three into a` Promise.all()` but that didn't work.

**Comment by SkaterDad** [comment]
I would expect that Promise.all() is what you need, but you'll need to chain a then()  function which returns a single object from all 3 results. 

Can you share the code you tried?

**Comment by jubairsaidi** [comment]
That did it thanks!  I was trying to return Promise.all() directly rather than using then() to organize the data and return it.
