### ISSUE TITLE
get the path right after reload page

### ISSUE THREAD

**Issue by merijnvanessen** [nuxt/nuxt.js#1790]
Building my portfolio with nuxt http://buroponzo.nl/
if you click on a project it response well and navigate to
http://buroponzo.nl/gettingbetter

When I now reload/refresh the page (manually), 
it's looking for images within the directory folder of this 
route ->gettingbetter

All folders from routes are created with npm nuxt generate

![schermafbeelding 2017-10-06 om 12 49 17](https://user-images.githubusercontent.com/23075300/31274815-d4e4f776-aa94-11e7-824b-11bef2f3b812.png)

How to fix this?! :)

**Comment by gaetansenn** [comment]
Hi @merijnvanessen 

Make sure you use `/` in front of your images and script path.

Example:
`src="ponzoapp.js"` -> `src="/ponzoapp.js"`

Otherwise the browser will resolve it relatively from your browser url.

**Comment by calebanthony** [comment]
The same with images, it looks like they're hosted in your `/static` directory, which can be reached by doing just `/`.
So this would work for the images:
`/medium/gettingbetter_caseArtboard6-100.jpg`

**Comment by merijnvanessen** [comment]
Awesome! Never stop learning! 👍 
`<img v-lazy="`/preload/${block.content.image}`" :data-srcset="`/small/${block.content.image} 660w, /medium/${block.content.image} 1220w, /large/${block.content.image} 2000w`"  class="image" />`

refreshing . Thank you
