### ISSUE TITLE
[Bug] Pages mount twice

### ISSUE THREAD

**Issue by i0** [nuxt/nuxt.js#1791]
In the "spa mode" with a "custom layout" pages will be mounted twice!

<img width="1053" alt="screen shot 2017-10-06 at 7 09 18 pm" src="https://user-images.githubusercontent.com/2684673/31286084-ef88cb86-aac9-11e7-8b2d-e3a02d213386.png">

In a fresh clone of nuxt.js, I just added this line in nuxt.config.js to use spa mode:
`mode: 'spa',`

then I created a custom layout ('layouts/custom.vue') with the exact contents of the default layout ('layouts/default.vue'), and I used the custom layout in "pages/index.vue"

This bug only exists in SPA mode with a custom layout. But in SSR mode or with the default layout it works fine.

**Comment by husayt** [comment]
I also noticed this. First thought it's a vuejs issue, but seems next related and also happens in spa mode. It calls mounted twice

**Comment by denmasyarikin** [comment]
so is there a way to prevent this issue?

**Comment by denmasyarikin** [comment]
waiting for this issue solved, i just use page components as proxy to vue component in components folder.

**Comment by InstanceOfMichael** [comment]
Can you verify that this only happens with pages and not _all components_?

**Comment by denmasyarikin** [comment]
yups i use rc11, this is only happens to pages compnents, i'v tried,

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1791](https://trello.com/c/pOIhnMrH/23-1791)

**Comment by mkurczewski** [comment]
I have that issue too.
Additionally, when using page transitions, duplicated page component shows for few milliseconds and disappears.

**Comment by Atinux** [comment]
Fixed in next release.

**Comment by davidpmccormick** [comment]
I'm unsure if this is related (I'm not using spa mode) but similar to @mkurczewski's point above, I'm seeing leave transitions occur _after_ the new page content has rendered.

I'm using `fetch()` to update a Vuex store.

The behaviour is only intermittent – see the first click on 'the trust' in the gif below; the heading displays before the leave transition (although this doesn't happen on the second click)

![transition-timing](https://user-images.githubusercontent.com/1394592/35407843-0b33f56c-0205-11e8-9561-f5fbc31ef333.gif)

I'm on `"nuxt": "^1.1.1"`

**Comment by Atinux** [comment]
Hey @davidpmccormick 

It's actually due to the fact that we wait for fetch to finish before making the transition, and if the second one is faster, it's due to browser cache.

One solution is to check in your `fetch` method if you are from client-side, if so, you can avoid to wait for the promise and instead show a loading text :)

**Comment by davidpmccormick** [comment]
@Atinux Thanks for the info – would you mind giving a beginner a little bit more context?

Currently I have
```
async fetch({ store, params }) {
  await store.dispatch('getPageById', params.pageSlug);
}
```

I think you're suggesting something like
```
async fetch({ store, params, isClient }) {
  if (isClient) {
    // I'm not sure what to do here
  } else {
    await store.dispatch('getPageById', params.pageSlug);
  }
}
```

**Comment by tsimenis** [comment]
I'm having the same problem as @davidpmccormick only for me it happens on every click/page change, the new page content transitions out and then in.

This is when using fetch to populate the store. If I switch to asyncData as mentioned above the problem goes away, but this feels kind of hacky and I also don't understand why the behaviour is different from fetch. 

So before I move ahead to refactor to asyncData I would really like to know, is there some explanation/solution to this?

**Comment by aronanda** [comment]
I was able to test for req.headers.referer as this only loads when coming from the client...I guess...
I'm doing this in nuxtServerInit btw:

```javascript
async nuxtServerInit ({ dispatch }, { req }) {

  if (process.server && req.headers.referer) { // <= only fires once =)
    
    const cookies = getCookie.s(req),
          token = cookies.token

    if (token) {
      this.$axios.setToken(token, 'Bearer')
      const api = "http://server:1337/member/verify"
      let { success, message, data: user } = await this.$axios.$get(api)
      if (!success) throw message
      // @todo ~ Error handling )
      await dispatch('user/setUser', user)
    }
  }
}
```

**Comment by RohitRox** [comment]
`nextTick` https://vuejs.org/v2/api/#mounted solved the issue for me. I had an ajax call in `mounted` and was getting fired twice (no-ssr component)
