### ISSUE TITLE
Hiding references to __nuxt in the scripts and the template ID

### ISSUE THREAD

**Issue by ederchrono** [nuxt/nuxt.js#1792]
I've been reading the source code and found out that `window.__nuxt__` and the id for the App component `#__nuxt` are hardcoded. For security reasons I would like to hide what technology is powering my site, do you have plans on having those as options or should I work on my own fork? 

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1605">#c1605</a>)</em></sub></div>

**Comment by tmorehouse** [comment]
Also, I would like to have the data passed to `window.__NUXT__={...}` obfuscated.  My store includes details about roles/permissions, basic user information, etc.

It doesn't need to be cryptographically encoded, but maybe base64/62 encoded (as savvy users could just inspect the instances via dev tools).  But not having it in plaintext would be a bonus.

Maybe something like:

```js
window.__NUXT__ = stateParser(".....")
```
Where stateParser decodes the string and then JSON parses it

Or incorporate the de-obfuscation into the part of Nuxt that checks the window.__NUXT__ variable (i.e. if a string, try and decode it)

It could then be made into an optional build flag to either obfuscate or not.

**Comment by dsandor** [comment]
I will take a look at this soon.

**Comment by cubicmaze** [comment]
Any news about this feature?

**Comment by mavrick** [comment]
Would also like to use lz-string or base64 type encoding to obfuscate the json objects

**Comment by DearAKuan** [comment]
window.__NUXT__ = stateParser(".....")  

I have the same question，how to do whith it?

Which files do I need to modify
