### ISSUE TITLE
nuxt start doesn't seem to respect HOST environmental variable

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/nuxt.js#1794]
Basically, I do `HOST=0.0.0.0 npm run start`, expecting to get the app running at `0.0.0.0:3000`. Nevertheless, weirdly enough, what I get is `OPEN  http://localhost:3000`. Nuxt version I use is `nuxt@1.0.0-rc11`. What can I do to force Nuxt to listen to four zeroes?

**Comment by NicoPennec** [comment]
If you check the Nuxt source code, you may find a answer:
https://github.com/nuxt/nuxt.js/blob/a585d8cb35f3463b9b07ec162788165dbc4a1b1c/lib/core/nuxt.js#L57

More details about `0.0.0.0`:  https://www.howtogeek.com/225487/what-is-the-difference-between-127.0.0.1-and-0.0.0.0/

**Comment by gbezyuk** [comment]
@NicoPennec great, thank you for this information.

Nevertheless, I need to run my nuxt-based app in a docker container as a part of docker-compose setup. I do not know the IP address nor even the network that will be assigned to the running container. So I was thinking about using `0.0.0.0`.

Hmmm, actually I seem to have found a solution just while typing the previous paragraph. I'll use docker-compose's hostname instead, and it should do the trick. Thank you for being my silently listening rubber duck =)
