### ISSUE TITLE
Proposal: django-like nested apps.

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/nuxt.js#1795]
Currently we have a single global folder for the app, with subfolders of `~/pages/`, `~/components/`, `~/store/` etc. For a big project with some submodules it may become quite messy, effectively making modularity impossible. Given an application with two submodules, `dashboard` and `shop`, I wonder if we could somehow achieve a file structure like the following:
```
/
  /apps
    /dashboard
      /pages
      /components
      /store
    /shop
      /pages
      /components
      /store
  nuxt.config.js   # here or anywhere else specifying endpoints for two before-mentioned apps
  ...
```
So, what do you think?

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1610">#c1610</a>)</em></sub></div>

**Comment by sebastianmacias** [comment]
This is something I have been trying to achieve for a while using different approaches with some degree of success and some limitations. 

Lately I have digging into [modules](https://nuxtjs.org/guide/modules) trying to accomplish this exact thing but it would definitely be a HUGE + if Nuxt supported this out of the box the way you have described it.

The flexibility this kind of setup would offer is priceless.

**Comment by XEngine** [comment]
Had the same idea. Here is the current workaround
https://github.com/nuxt/nuxt.js/issues/1785
