### ISSUE TITLE
How to make transition to 404?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1796]
For some reason page transition to 404 page is not working. 

```js
export default {
  props: ['error'],
  transition: 'page'
}
```
How to make transition to 404?

**Comment by alexchopin** [comment]
#1766 
It's a known bug, thanks for reporting we are working on it.

**Comment by iamdubx** [comment]
@alexchopin thanks, but looks like there's misundestanding. In the issue where you refer to there's absolutely another issue, and @Atinux close it.

**Comment by iamdubx** [comment]
I still have no idea how to make transition to and from 404 page.
