### ISSUE TITLE
Got 404 error when navigate to page with asyncData

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1797]
I got a page with this code

```js
asyncData ({ req }) {
    return {
      ua: req.headers['user-agent'] || 'unknown'
    }
  }
```

If I load this page directly in the browser (from server) - it works. But is I route there on client I got 404 error.

Any reason why this happening?

**Comment by Gomah** [comment]
`req` is only available on the [Server](https://nuxtjs.org/api/context), it won't work on the client.

```js
asyncData ({ req }) {
    return {
      ua: req ? req.headers['user-agent'] : 'unknown'
    }
  }
```

**Comment by iamdubx** [comment]
@Gomah what if I will use Middleware? 

For example I want to use some library for mobile detecting. It's also works only if I load page from the server but doesn't work if I navigate to this page on client.

Does this mean that I can't have any server-side code in Middleware?
