### ISSUE TITLE
Page rendering is off via the router

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt.js#1799]
I'm having this strange issue to where when I go to a certain page via a `router-link` The page doesn't render correctly (css? seems off), but if i hit refresh the page then renders fine, I have no errors or warnings in the console or chromes web inspector, here is an example:

Here is what it looks like normally, if i go to the URL directly or hit refresh:

![image](https://user-images.githubusercontent.com/967369/31315696-1e1551b2-abe3-11e7-9cef-3f966905fd02.png)

And here is what happens when I visit the page via `router-link`

![image](https://user-images.githubusercontent.com/967369/31315701-3b1fd0b6-abe3-11e7-9bb7-c26e0f66426c.png)

The oddness is not random, its exactly like this every time, and its not just sometimes when its from a router-link, its consistent

Some extra info about my setup:

I've modified layouts/default.vue to supply my header and footers, ex:

```vue
<template lang="pug">
  #app
    Top
    nuxt
    Bottom
    Login
</template>

<script>
import Top from '~/components/layout/Top.vue'
import Bottom from '~/components/layout/Bottom.vue'
import Login from '~/components/Login.vue'
export default {
  components: { Top, Bottom, Login },
}
</script>

<style lang="stylus">
@import '../assets/stylus/main'
</style>
```

**Comment by victorcp91** [comment]
Im passing for the same problem. How did   you fix this?

**Comment by acidjazz** [comment]
@victorcp91 my issue was page-specific CSS being loaded and/or not being loaded. I re-organized and separated my global css from page-specific css that was sometimes being inherited and sometimes not.
