### ISSUE TITLE
Async Data shows up in XHR after page return

### ISSUE THREAD

**Issue by tmvnk** [nuxt/nuxt.js#1800]
When returning to a page with a async data functionality the AJAX call is fired. The XHR request seems to be refired and can be seen in the XHR request. 

Is this a bug or how can this be avoided?

export default {
  async asyncData ({ params }) {
    let { data } = await axios.get('http://localhost:3532/api/afspraken')
    return {
      afspraken: data
    }

**Comment by alexchopin** [comment]
Hi @tmvnk, Have you tried to setup a [cache](https://github.com/nuxt-community/modules/tree/master/packages/component-cache)?

**Comment by tmvnk** [comment]
Hi, yes I did. What I expect that async data will never show up a XHR request. The axios should always be fetched first before rendering a page. Also when 1. loading the page (seems ok). 2. go to other page  3. go back to page. Then XHR shows up. Because of security reasons this is not wanted.

**Comment by lilywang711** [comment]
@tmvnk hello, did you solve it now?
