### ISSUE TITLE
How to disable plugin vue.fullpage on media query in nuxt.js?

### ISSUE THREAD

**Issue by martovytskyi** [nuxt/nuxt.js#1802]
Hi guys! I have a problem. How to disable plugin vue.fullpage on mobile in nuxt.js? 
**nuxt.config.js**
```

module.exports = {
  plugins: {
     '~plugins/fullpage-vue.js'
  }
}
```

**fullpage-vue.js**
```js
import Vue from 'vue'
import 'animate.css'
import 'fullpage-vue/src/fullpage.css'
import VueFullpage from 'fullpage-vue'
Vue.use(VueFullpage)
```

there is a solution, but I do not know how to use it. 
```
if (screen && screen.width > 768) {
   document.write('....')
}
```

**Comment by iamdubx** [comment]
You can detect `isMobile` in Middleware

**Comment by martovytskyi** [comment]
what for? I just do not want to initiate a plug-in when the screen width is less than 768px

**Comment by iamdubx** [comment]
@martovytskyi then rename your issue to "How to disable plugin vue.fullpage on media query in nuxt.js?"
