### ISSUE TITLE
How can I use vuex store in custom Vue object?

### ISSUE THREAD

**Issue by AndreasCag** [nuxt/nuxt.js#1803]
I have to have some component on every pages with different layouts, so I just use entry.js plugin for creating new Vue component and inserting it in document.

> entry.js

```
import someComponent from '@/components/some-component'
import Vue from 'vue'

var someDiv = document.createElement('div');
document.getElementsByTagName('body')[0].appendChild(someDiv);

new Vue(_.extend({}, someComponent, {
  el: someDiv,
}));

```

And it works fine while I don't use vuex store, but if I would

> some-component.vue

```
<template>
  <div style="position: fixed; background-color: red; height:100px; width:100px;top:0">
      {{text}}
  </div>
</template>
<script>
  import { mapState } from 'vuex'

  export default {

    computed: {
      ...mapState('texts', ['text']),
    },

  };
</script>
```

It cause errors
![image](https://user-images.githubusercontent.com/14947036/31319357-831b1060-ac6a-11e7-8a37-3a8bed053740.png)

How can I overcome it?

**Comment by AndreasCag** [comment]
Sorry about this simple question, I found solution:

> entry.js

```
import someComponent from '@/components/some-component'
import Vue from 'vue'

var someDiv = document.createElement('div');
document.getElementsByTagName('body')[0].appendChild(someDiv);

export default ({ store }, inject) => {
  window._someVM = new Vue(_.extend({}, someComponent, {
    el: someDiv,
    store,
  }))
}
```

Are there any other available ways to insert global components in nuxt?

**Comment by magicknight** [comment]
Do you have a directory named 'store' in your project folder?

**Comment by AndreasCag** [comment]
Yes, I have.
