### ISSUE TITLE
Generate only routes provided in generate.routes

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#1804]
It appears that the behavior has changed from completely ignoring filesystem API for `generate` if routes are provided to concatenating the user-supplied and generated routes? (in lib/builder/generator.js)

How can I only generate some routes?

(also, that should include generating no HTML by explicitly passing an empty array)

**Comment by robyedlin** [comment]
Did you try the router module? https://github.com/nuxt-community/router-module

**Comment by qm3ster** [comment]
@robyedlin doesn't that require manually specifying the component for each route?

**Comment by rAugustos** [comment]
According o documentation:

> This module disable the pages/ directory into Nuxt and will use a router.js file at your srcDir directory

Yes, is required manually specifying the component for each route.

**Comment by qm3ster** [comment]
If for some reason we want to maintain compatibility with the current behavior of concatenating manual and generated routes, taking a function, like `extendRoutes` does, would be ideal.
```js
{ build: {
  routes: function(routes) {
  // muahaha, we ignore you, generated routes!
  return ['/about']
}}
```

**Comment by Atinux** [comment]
Hi,

We decided to set `routes` to add the dynamic routes ignored by `nuxt generate`. If you want to generate only a specific route, I recommend you to use Nuxt.js programmatically since it will avoid you to run `nuxt generate` every time and wait for the build time.
