### ISSUE TITLE
Using axios globally

### ISSUE THREAD

**Issue by mrcatman** [nuxt/nuxt.js#1805]
I want to use pre-configured Axios in most of my components, but not to write "import api from '~/components/api.js';" any time. How can I register it globally? (especially with access to request, as I'll need to fetch JWT tokens from cookies on server-side)

**Comment by vuchl** [comment]
https://github.com/nuxt-community/axios-module

**Comment by onlyurei** [comment]
Note: `@nuxt/axios@4.4.0` has a severe memory leak issue, see #1695.

**Comment by bjunc** [comment]
There are many ways to address this.  Have you looked into putting all of your axios calls in Vuex?  That would allow you to use the regular axios import, as well as do the initial token setup.
