### ISSUE TITLE
How can I access to the plugin methods in page component

### ISSUE THREAD

**Issue by crazyfrogs19** [nuxt/nuxt.js#1806]
Hi there from a newbie, 
I'm having a problem when trying to use `vue-js-modal`. 

`plugins/modals.js`
```
import Vue from 'vue'
import VModal from 'vue-js-modal'

Vue.use(VModal)
```

`nuxt.config.js`
```
build: {
  vendor: ['vue-js-modal']
},
plugins: [
  { src: '~/plugins/modal.js', ssr: false}
]
```

According to the plugin writer, the syntax `this.$modal` is available. But when I tried to use in in nuxt page (pages/*.vue) object `this.$modal` return an `undefined`.
I tried `console.log(this)` a find out  in scope of an page, `this` is not Vue object, i got some thing like this.
![image](https://user-images.githubusercontent.com/12602832/31321996-b27fbaec-acb8-11e7-8d21-bd0f158bbe4f.png)

On browser console, I found modal object in `window.$nuxt.$modal`
![image](https://user-images.githubusercontent.com/12602832/31322017-2a9e47fa-acb9-11e7-8341-6ef1de27270d.png)

How can I use plugins like `vue-js-modal` in a page. I looked through the document many times but couldn't find the answer.

I'm building a static web running on client side.

**Comment by robyedlin** [comment]
Once you register the plugin, you should be able to use it normally.

You checked this? https://github.com/euvl/vue-js-modal#how-to-use

**Comment by robyedlin** [comment]
Also noticed that you have a `plugins/modals.js`, but your src is to `~/plugins/modal.js`

**Comment by crazyfrogs19** [comment]
Thanks for your response @robyedlin 

I created `plugins/modals.js` to init `vue-js-modal` in nuxt

> Every time you need to use Vue.use(), you should create a file in plugins/ and add its path to plugins in nuxt.config.js.

According to the doc of `vue-js-modal`, I can show the modal by syntax `this.$modal.show('text')`, but in my case, it's not work

**Comment by robyedlin** [comment]
Can you share your full component file?

**Comment by crazyfrogs19** [comment]
I have figured out the problem, It's caused by the syntax I defined method in the component

**template**
```
<template>
    <modal name='hello-world'></modal>
</template>
```

**This worked**
```
export default {
...
  methods: {
    onclick () { this.$modal.show('hello-world') }
  }
}
```

This one is not
```
export default {
...
  methods: {
    onclick: () => { this.$modal.show('hello-world') }
  }
}
```

I don't know why!!! Is there any different?

**Comment by robyedlin** [comment]
Yes, arrow functions preserve the parent context of `this`.

Have a look at this: https://github.com/vuejs-templates/browserify-simple/issues/6#issuecomment-214003282

**Comment by crazyfrogs19** [comment]
I really appreciate your help.
Thanks for keeping me move on with vuejs :)

**Comment by robyedlin** [comment]
👍
