### ISSUE TITLE
What the right way to extend Nuxt.js context?

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#181]
What the right way to extend Nuxt.js context with custom plugin? I want to test custom store with nuxt, and need to access from fetch({ customStore }) or data() on the server and client.

**Comment by Atinux** [comment]
Hi @ruslankonev 

it's not possible to extend the context, but you can require your custom store directly and use it.

Example:
```vue
<template>
  <h1>Custom store...</h1>
</template>

<script>
import customStore from '~/my-custom-store/index.js'

export default {
  fetch () {
    return customStore.dispatch('myAction')
  }
}
</script>
```

**Comment by axetroy** [comment]
Hi @Atinux 
a year have been gone. any update for this?
it still impossible?

**Comment by Atinux** [comment]
You can use `inject` when creating a plugin to extend the context directly, see https://nuxtjs.org/guide/plugins#inject-in-root-amp-context
