### ISSUE TITLE
asyncData: Recursion and promises. What's the right way?

### ISSUE THREAD

**Issue by template01** [nuxt/nuxt.js#1810]
First of all: I don't exactly know where to place this question. If wrongly placed, a hint on where to post would be nice :)

**The problem:** 

In my API-enabled backend I have a series of post categorized by year. Uitlizing asyncData and using axios I want to fetch these posts based on the various years; thus return all posts from 2017, posts from 2016, etc. as separate items in a collected array. 

I can make a call to return all available years (http://api.template-studio.nl/wp-json/wp/v2/categories?parent=19). In my theory I should then loop over the years and return the post-content year by year (http://api.template-studio.nl/wp-json/wp/v2/werkitem_nl?categories=+yearId).
 
Here's a draft on what I'm working on:

```javascript
  async asyncData({
    params,
    query,
    error
  }) {

    let [recursiveCategoryDataRes] = await Promise.all([

      // GET ALL THE CATEGORIES (YEARS) WITHIN THE 'YEAR'-CATEGORY PARENT

      axios.get('http://api.template-studio.nl/wp-json/wp/v2/categories?parent=19').then((res) => {

        // LOOP OVER THE RETURNED CATEGORIES (YEARS) AND GET THEIR RELEVANT POST-CONTENT ONE BY ONE. PUSH TO EMPTY ARRAY.

        var recursiveData = []

        for (var i = 0, len = res.data.length; i < len; i++) {
          var yearId = res.data[i].id
          axios.get('http://api.template-studio.nl/wp-json/wp/v2/werkitem_nl?categories=' + yearId).then((resNested) => {
            recursiveData.push([resNested.data[0].categories[0], resNested.data])
          })
        }

        // RETURN THE COLLECTED data

        return recursiveData

      })
    ])

    return {
      recursiveCategoryData: recursiveCategoryDataRes,
    }

  }
```

This method seems to somewhat work, but is not always returning the recursively-gathered content fully. As if the script ends before all recursive calls have been made. 

Any suggestions on how to handle nested/recursive calls within asyncData?

All the best 

Lasse

**Comment by cretueusebiu** [comment]
Use [axios.all](https://github.com/axios/axios#user-content-axiosalliterable):

```javascript
async asyncData () {
  const res = await axios.get('/api/categories')
  const categories = res.data

  const results = (await axios.all(
    categories.map(category => axios.get(`/api/some-resource/${category.id}`))
  ))
  .map(result => result.data)
  .reduce((acc, curr) => {
    acc.push(...curr)
    return acc
  }, [])

  console.log(results)
}
```

**Comment by template01** [comment]
Hey! Nice. Thanks. Highly chained js! Thanks for clearing up. :+1:
