### ISSUE TITLE
nuxt-start only works when `nuxt` installed

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#1813]
Installing only `nuxt-start` and starting `yarn nuxt-start` returns "server error" page with no messages in console.
Adding `nuxt`, but running `yarn nuxt-start` (not `nuxt  start`) produces normal operation.

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1813](https://trello.com/c/WeZZYebu/25-1813)

**Comment by qm3ster** [comment]
(((private board)))

**Comment by qm3ster** [comment]
(((private board)))

**Comment by Atinux** [comment]
Not anymore @qm3ster :)
