### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by derevandal** [nuxt/nuxt.js#1814]
Hi, is there any possibility of adding image optimization?

**Comment by NicoPennec** [comment]
You may use a webpack plugin to run an image optim process (eg. https://github.com/tcoopman/image-webpack-loader)

**Comment by derevandal** [comment]
How can I add webpack plugin insinde Nuxt config? @NicoPennec 
And thanks XD

**Comment by NicoPennec** [comment]
I can't help more, read the manual ;-)

https://nuxtjs.org/faq/webpack-plugins
https://nuxtjs.org/faq/extend-webpack#how-to-extend-webpack-config-

**Comment by bovas85** [comment]
is there a better guide than referring to that doc? It's not really showing how to solve the issue
