### ISSUE TITLE
Nested <nuxt-link> issue

### ISSUE THREAD

**Issue by jamilabreu** [nuxt/nuxt.js#1815]
I'd like to do the following:

`        <nuxt-link to="/">
          <div class="preview-text">
            Text
          </div>
          <nuxt-link to="/example">Link</nuxt-link>
        </nuxt-link>`

But I'm getting:

> [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

And the nested link (/example) is rendering twice.

Any ideas why? Thanks!

**Comment by NicoPennec** [comment]
`<nuxt-link>` becomes  `<a>` after compile, and you can't nested `<a>` element.

**Comment by jamilabreu** [comment]
@NicoPennec I see! In that case, how would I go about implementing that functionality (similiar to how Twitter embeds links that are clickable inside a Tweet that is also clickable)

**Comment by NicoPennec** [comment]
@jamilabreu you may create a parent element with a vue [click event](https://vuejs.org/v2/guide/events.html) and push your route to the [vue router](https://router.vuejs.org/en/essentials/navigation.html).

```vue
<template>
  <div :click="$router.push('/')">
    <div class="preview-text"> Text <nuxt-link to="/"><nuxt-link to="/example">Link</nuxt-link></div>
  </div>
</template>
```
