### ISSUE TITLE
 Google statistics in nuxt.js pro,ga is not defined

### ISSUE THREAD

**Issue by XiaoNode** [nuxt/nuxt.js#1816]
hey when i follow the official example to add Google statistics in my nuxt.js pro, console prompt me 'ga is not defined',What did I miss？

**Comment by NicoPennec** [comment]
you mean  Google *Analytics*, right?

share the source code of your GA integration, please.

but prefer use the official nuxt module: https://github.com/nuxt-community/analytics-module

**Comment by XiaoNode** [comment]
i follow the official example https://nuxtjs.org/faq/google-analytics，so I still don't understand what the problem is，thank you;

**Comment by awronski** [comment]
AFAIK this example is outdated and it doesn't work with 1.0
You should use module, it is working great.

https://github.com/nuxt-community/analytics-module

**Comment by XiaoNode** [comment]
well,thank you ,i will try it

**Comment by seanwash** [comment]
@awronski could you show how you have this analytics-module setup? I'm trying to use it but can't actually get it to track any data after following the brief readme.

**Comment by awronski** [comment]
@seanwash Sure!

`package.json:`
```js
"devDependencies": {
    "@nuxtjs/google-analytics": "^1.0.0",
    [...]
}
```

`nuxt.config.js:`
```js
module.exports = {
  modules: [
    ['@nuxtjs/google-analytics', { ua: 'UA-XXXXX-1' }]
  ]
  [...]
}
```

That's all.

**Comment by seanwash** [comment]
@awronski Ah, I see. I thought you were using the new module that uses vue-analytics.

**Comment by awronski** [comment]
I am using the old module. Because the new one has WIP status. I don't know
if it is ready to use.

**Comment by dionfananie** [comment]
hello, i've setting nuxt module google analytics,  found the same error. 

[Nuxt] Error when initializing app referenceError : ga not found,

I follow the step from here: https://nuxtjs.org/faq/google-analytics/ 
and, where i should placing my google analytics script?
