### ISSUE TITLE
Mobile based pages

### ISSUE THREAD

**Issue by rohitpal99** [nuxt/nuxt.js#182]
How would be switch to pages for mobile and desktop?

**Comment by Atinux** [comment]
@rohitpal99 use responsive design to have only one page for mobile and desktop.

Otherwise, you can check the User Agent of the navigator.

**Comment by rohitpal99** [comment]
@atinux unfortunately responsive design is not an option, mobile website is quite different and uses mostly separate components. Is there another way than that. please suggest.

**Comment by Atinux** [comment]
You can use something like https://github.com/hgoebl/mobile-detect.js on the server-side (use [nuxt as a middleware](https://nuxtjs.org/api/nuxt)) and redirect the user to https://m.yoursite.com which is a nuxt.js application for the mobile.

**Comment by tiagomatosweb** [comment]
tks @galvez for the source.
I came across with this, look cool to me
https://github.com/nuxt/nuxt.js/issues/265#issuecomment-287404178
