### ISSUE TITLE
Generate is not work correctly

### ISSUE THREAD

**Issue by KermitLi** [nuxt/nuxt.js#1822]
After running `nuxt generate` operation,  the page of  `index.html` can load correctly. But its JS dependencies aren't working unless the components locate in the `layouts` folder. Finally, if the version is oldest, it will work normally.

**Comment by gvinter** [comment]
@KermitLi - What do you mean by "version is oldest"?

Another issue related to this is image assets:
https://github.com/nuxt/nuxt.js/issues/1676

**Comment by KermitLi** [comment]
@gvinter 

The meaning is if I use the older version of nuxt, it will work correctly.

My images assets can work correctly.The current problem is after running `nuxt generate` operation, I deploy the files of `dist` folder to my static server. The page can load normally, but its js files can't work and no error is thrown.

**Comment by gvinter** [comment]
@KermitLi - which older version of `nuxt` works for you on this?

**Comment by SyedAman** [comment]
I'm getting this issue too. Just the `index.html` loads, no javascript whatsoever.

`"nuxt": "^1.0.0-rc11",`

**Comment by gvinter** [comment]
@SyedAman - I just figured it out! Generating to `/dist` doesn't just generate static files that can be opened as HTML files in a browser. You must point a local server (ie. nginx) at the `/dist` directory and access via the server, such as `localhost:8000`.

So if you haven't already, install `nginx`, then point you `nginx.conf`'s file's root location at the `/dist` folder you want to serve...

```
server {
    location / {
            root   /Users/gvinter/NUXT_PROJECT/dist;
            index  index.html index.htm;
    }
}
```

And that works for me!

**Comment by SyedAman** [comment]
@gvinter can GitHub pages run `nginx`?

**Comment by SyedAman** [comment]
@gvinter 

I didn't need to use nginx. I fixed it!

Check out: https://nuxtjs.org/api/configuration-router/

I just had to add

```
  router: {
    base: '/my-github-repository-name/'
  }
```

and it deployed properly

**Comment by KermitLi** [comment]
@gvinter 


I forget it's which version of nuxt because of using it before a long time.
Now, I try using v 0.10.7, 0.10.6, v0.10.5, v0.10.4 and v0.10.1 etc.But the whole of thme can't work correctly.

**Comment by gvinter** [comment]
@KermitLi you should be fine with the fixes mentioned above.

**Comment by Coletrane** [comment]
I'm still trying to figure out why navigating to index.html doesn't work. Try going to [http://bikeva.com/index.html](url) then [http://bikeva.com](url) they both have the same script tags but in the `index.html` link none of them fire. Repository is [https://github.com/coletrane/mountain-bike-virginia](url) if that helps. As an alternative I'm seeing if S3 can just redirect all requests to `index.html` to `/`

**Comment by GoBrianGo** [comment]
@Coletrane I have the same problem.

**Comment by qm3ster** [comment]
I think it just doesn't understand where you are, and so doesn't run the correct component. The scripts do get downloaded.

**Comment by lemehovskiy** [comment]
@Coletrane I have the same problem.

**Comment by johnfercher** [comment]
Add the router works, but now i'm having a annoying issue. Every route now is duplicated. (https://vss-sdk.github.io/vss-sdk.github.io/doc-overview-dev).
```
router: {
   base: '/my-github-repository-name/'
}
```

**Comment by NickBolles** [comment]
@Coletrane  @qm3ster @GoBrianGo  Did any of you find a solution to the index.html issue?

**Comment by darior87** [comment]
any solution on this? I'm having the same problem.
