### ISSUE TITLE
Dynamic routes that exceed number of params in pages directory

### ISSUE THREAD

**Issue by jamesAtcodeninja** [nuxt/nuxt.js#1823]
Let's say my messages pages directory handles up to `messages/_status/_id/` and someone attempts to access `messages/online/1/jaoisjfdsoaj`. This directs to the error page  in the default settings of my Nuxt project. Where is the most appropriate place to do this check and properly redirect?

**Comment by alexchopin** [comment]
Hi, 
This is handled by vue-router because the route doesn't match.
A possible solution is to create a `_.vue` file wich handle all the other routes and then write your login inside.
