### ISSUE TITLE
how can i rehydrate vuex store in nuxt (without plugins) ?

### ISSUE THREAD

**Issue by fidellr** [nuxt/nuxt.js#1825]
currently i used vuex-persistedstate to make the state's persisted when the page are refreshes, but it caused the component inside my layout files rendered after the page are mounted/rendered (i.e if i refreshed the browser the sign in button are flashing into user profile picture in 1s when they are logged in) which is not like wht i expected. the button component are depends on userAuthenticated getters, so i think vuex-persistedstate rehydrating the store when nuxt pages are mounted/rendered.

if theres a way to rehydrate the store without any plugins only with nuxt method that provided, i would know how and why my previous implementation caused a bug?
thanks :))
@alexchopin @pi0 @Atinux

**Comment by fidellr** [comment]
sorry i figured out to do rehydration store with middleware, thx i really love this framework, keep it up!

**Comment by mrboli** [comment]
hey @fidellr what middleware did you end up using?

**Comment by fidellr** [comment]
@mrboli sorry it's been a long time not touching that project. For the answers, check my "serversideRendering with nuxt" repo
