### ISSUE TITLE
How to config vue-i18n v-t directive with nuxt ?

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt/nuxt.js#1826]
I just cant figure it out.

Here is an example:

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import { createRenderer } from 'vue-server-renderer'
import { directive as t } from 'vue-i18n-extensions'

Vue.use(VueI18n)

const i18n = new VueI18n({
  locale: 'en',
  messages: {
    en: {
      hello: 'hello'
    },
    ja: {
      hello: 'こんにちは'
    }
  }
})
const renderer = createRenderer({ directives: { t } })

const app = new Vue({
  i18n,
  render (h) {
    // <p v-t="'hello'"></p>
    return h('p', {
      directives: [{
        name: 't', rawName: 'v-t',
        value: ('hello'), expression: "'hello'"
      }]
    })
  }
})

renderer.renderToString(app, (err, html) => {
  console.log(html) // output -> '<p data-server-rendered="true">hello</p>'
})
```
https://github.com/kazupon/vue-i18n-extensions

**Comment by cretueusebiu** [comment]
Why don't just use `{{ $t('hello') }}` ? It will render on the server side too.

**Comment by alanaasmaa** [comment]
@cretueusebiu I'm using now but i wanna PERFORMANCEEE http://kazupon.github.io/vue-i18n/en/directive.html#t-vs-v-t

**Comment by kazupon** [comment]
You can check the example. 👀
https://github.com/kazupon/vue-i18n/tree/dev/examples/ssr/nuxt

**Comment by kazupon** [comment]
And the compiler module.
https://github.com/kazupon/vue-i18n/tree/dev/examples/module/nuxt

**Comment by alanaasmaa** [comment]
@kazupon Thanks i got it to work now, how could i load i18n as a plugin ? Is it somehow possible ?

I would like to use vuex to define locale option. But i can't access store in config.

```
export default ({app, store}) => {
  app.$i18n = new VueI18n({
    locale: store.state.locale,
    fallbackLocale: 'en',
    messages: {
      'fi': require('~/locales/fi.json'),
      'en': require('~/locales/en.json')
    }
  })
}
```

**Comment by gangsthub** [comment]
Accessing the store, @alanaasmaa:

```JS
export default ({ app, isClient, store }) => {
    app.i18n = new VueI18n({
        locale: store.state.locale,
        fallbackLocale: 'es',
        messages
    });
};
```

A little bit different than what the author of vue-i18n, @kazupon, suggests in:

https://github.com/kazupon/vue-i18n/commit/44d4ebe527272ce575963abbd1920a1b998d9c96#diff-e635ad7197be34317008bbbec46c7b7b
