### ISSUE TITLE
Why do we get errors with server side libraries missing?

### ISSUE THREAD

**Issue by bitmage** [nuxt/nuxt.js#1827]
We just updated to `1.0.0-rc13`.  Building our Nuxt project, we get:

```
These dependencies were not found:

* fs in ./node_modules/@nuxtjs/youch/src/Youch/index.js, ./node_modules/chokidar/index.js and 39 others
* jsdom in ./node_modules/nuxt/dist/nuxt.js
* module in ./node_modules/nuxt/dist/nuxt.js, ./node_modules/vue-server-renderer/build.js and 1 other
* net in ./node_modules/express/lib/request.js
* node-pre-gyp in ./node_modules/fsevents/fsevents.js
* readline in ./node_modules/friendly-errors-webpack-plugin/src/output.js

To install them, you can run: npm install --save fs jsdom module net node-pre-gyp readline
```

I've gotten this before with earlier versions of nuxt, and usually spend hours trying to get it to work again.  I'm confused.  It looks like a bunch of server side stuff is attempting to be run in the browser, and I really didn't want that in the first place.  But these errors all point to internal nuxt/webpack code.

`npm install` as the directions state also doesn't work.  I literally chopped my nuxt config down to an empty object and I still get these errors.

Anyone have suggestions for what to try?

Here is a gist of my dependencies:

https://gist.github.com/bitmage/172666a32d5acca14bb45801bcc3b0e4

**Comment by bitmage** [comment]
Nevermind.  This was because I was trying to `import 'nuxt'` from a client side file.  Nuxt clearly wasn't meant to be loaded in that context.

Is there some other way I can get a reference to the nuxt app, or to the vuex store?  I have an API helper that references the session store, and I can't import the store directly now that nuxt requires the `store/index.js` to export a constructor function.

**Comment by pi0** [comment]
Hey @bitmage. Good to hear your first problem was resolved. To access nuxt/app instance we cannot use global context or import/requires that is because all of SSR requests are being handled in a shared environment. So what i suggest using a plugin to register and bind your API helper in each request. If SSR is not essential for you there is also a SPA mode alternative which we can simply use `window.$nuxt` to access anything :)

**Comment by bitmage** [comment]
I see [this](https://github.com/nuxt/nuxt.js/issues/863) which suggests that the code be converted to a nuxt plugin.  That means I would no longer be able to import the helper directly... what object can I attach the helper to where it will be available to both the store actions and the vue components?

I thought of making the API helper a vuex store, but it's an async function and doesn't really fit the paradigm of an action.

I see [the docs on the fetch method](https://nuxtjs.org/api/pages-fetch) but it doesn't demonstrate reading credentials from a store, and I'd rather not have to explicitly pass in the store value every time I make a call.

How are other developers doing API requests?  This is something I would imagine everyone is doing.

**Comment by pi0** [comment]
You may take a look at [axios-module](https://github.com/nuxt-community/axios-module) and [auth-module](https://github.com/nuxt-community/auth-module) and their implementation. 

Also nuxt plugins has access an `inject` function to inject anything into context:

```js
export default async function myPlugin({ store }, inject) {
  const { token } = await getToken(store.state)
  const api = apiFactory(token)
  inject('api', api) // Makes $api globally available in both store and nuxt page/components
}
```

**Comment by bitmage** [comment]
Yes, this worked perfectly.  Closing.
