### ISSUE TITLE
$route.hash

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#183]
Hi, is there a specific reason why `$route.hash` is not exposed like `$route.query` in context?
I am trying to find a recommended strategy on routing of client side only pages. Let's say, if I want to do something like `/books/#!bookname`. That url will be SEO friendly and will work ok with generated books page.

Or is there a better naming/routing for this kind of pages?

Thank you very much in advance

**Comment by Atinux** [comment]
Hi @husayt 

`$route.hash` is not in the context since fragments (#) are unfortunately never sent to the server.
You can check `route.hash` but be aware that it will be filled only on client-side.

A better routing will be to use a [dynamic page](https://nuxtjs.org/guide/routing#dynamic-routes), so it will be like `/books/:bookname` (`pages/books/_bookname.vue`).

**Comment by husayt** [comment]
@Atinux thank you very much for prompt reply.

The problem with dynamic routing is 

a) that it tries to generate a page for every bookname (imagine if i have 1000s of books)
b) even if i don't generate them by using `routeaparams`, I still end up with urls like "/books/java_cookbook","/books/java_in_24_hours" which will not have anything to correspond to if they hit buy search engine crawler or link will be broken if shared

That is why I was considering hashbang urls, like"/books/#!java_cookbook","/books/#!java_in_24_hours"

**Comment by Atinux** [comment]
`nuxt generate` can works with more than 1000 books without problem, the question is more "how often do you have to regenerate the website?".

I see what you mean, so you should have two pages:
1. `pages/books/index.vue` which is your listing of books
2. `pages/books/book.vue` which is the detail of a book and render from server side a page with "Loading book..."

Then, in your listing, it can be server-rendered/generated, and link to a book with the link `/books/book#!java_cookbook`.

In your `book.vue`, in the `mounted` hook, you can fetch the book based on `this.$route.hash` and voilà 👍
