### ISSUE TITLE
asyncData ssr

### ISSUE THREAD

**Issue by bing1021** [nuxt/nuxt.js#1832]
here is my question.
in page component pages/index.vue i have such code

```
  asyncData () {
    return axios.get('/api/articles')
      .then(({ data: { docs, total } }) => {
        return { list: docs, total }
      })
  },
``` 

and here is nuxt.config.js

```
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/proxy'
  ],
  proxy: [
    ['/api', { target: 'http://localhost:7001' }]
  ],
```

when i open localhost:3000 ,i get error, the error msg is here

```
NuxtServerError

connect ECONNREFUSED 127.0.0.1:80
```

Why?

**Comment by bing1021** [comment]
i create the project by vue-cli

**Comment by dotneet** [comment]
@bing1021 
you can use `context.app.$axios` to access an axios instance provided by axios module.
https://github.com/nuxt-community/axios-module#component-asyncdata
