### ISSUE TITLE
How to set the alias in nuxt.config.js ?

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#1834]
example: config.resolve.alias['base'] = path.join(__dirname, 'assets/scss/base.scss')
use: @import 'base'
but throw Error not found

**Comment by maziarz** [comment]
Do you need global variables and mixins included or just plain CSS?

**Comment by yoyo837** [comment]
In nuxt.config.js, like this:

```javascript
module.exports = {
  build: {
    extend(config, {isClient}) {
      const alias = config.resolve.alias = config.resolve.alias || {}
      alias['@skinPages'] = this.options.skin.getPagesPath.apply(this)
      alias['@skinLayouts'] = this.options.skin.getLayoutsPath.apply(this)
      alias['@skinCss'] = this.options.skin.getCssPath.apply(this)
    }
  }
}
```
Doc： https://zh.nuxtjs.org/api/configuration-build#extend

**Comment by yoyo837** [comment]
@ouyangxiaoai  use `path.join(this.options.rootDir, 'assets/scss/base.scss')`

**Comment by ouyangxiaoai** [comment]
@maziarz I just want to test how to set the alias

**Comment by ouyangxiaoai** [comment]
@yoyo837 getCssPath is what? this throw Errow
use this.options.rootDir same

**Comment by yoyo837** [comment]
@ouyangxiaoai 
```javascript
module.exports = {
  build: {
    extend(config, {isClient}) {
      const alias = config.resolve.alias = config.resolve.alias || {}
      alias['xxxxx'] = xxxxxx
    }
  }
}
```

`this.options.rootDir` is nuxt.js root Directory

**Comment by ouyangxiaoai** [comment]
@yoyo837 my code 
 const alias = config.resolve.alias = config.resolve.alias || {}
 alias['base'] = path.join(this.options.rootDir, 'assets/scss/base.scss')
///
@import 'base'
///
throw Errow
File to import not found or unreadable: base.

**Comment by ouyangxiaoai** [comment]
@yoyo837 I have sove this problem just to use @import '~base'
thanks a lot!
