### ISSUE TITLE
'window is not defined' when importing ScrollMagic

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1836]
I am trying to import ScrollMagic, but receiving the much known `window is not defined`. As i understand i need to import the library as a plugin and switch off SSR, but unfortunately this is not working.

`plugins/scrollmagic.js` 

```
import ScrollMagic from 'scrollmagic'

export default ScrollMagic
```

`nuxt.config.js`

```
  plugins: [
    {
      src: '~/plugins/scrollmagic', ssr: false
    }
  ],
```

`views/test-component.vue`

```
<script>
import ScrollMagic from '~/plugins/scrollmagic'
export default {
}
</script>

```

error:

> [vue-router] Failed to resolve async component default: ReferenceError: window is not defined
> [vue-router] uncaught error during route navigation:
> ReferenceError: window is not defined

![skaermbillede 2017-10-12 kl 15 02 12](https://user-images.githubusercontent.com/15786116/31497150-640607ec-af5e-11e7-8509-94f0ffbbd0b1.png)

**Comment by KonstantinVlasov** [comment]
You should use "ssr:false" plugins only in browser environment. You can check it by process.browser. Or you can use it in mounted hook.

**Comment by maziarz** [comment]
@KonstantinVlasov, not 100% sure if i understand this correctly, but shouldn't the `ssr` parameter fix this?

**Comment by KonstantinVlasov** [comment]
No, this parameter tells Nuxt to include this plugin only for browser build, but you manually import it in both enviroment.

**Comment by maziarz** [comment]
Ah. Did not see this https://nuxtjs.org/faq/window-document-undefined

**Comment by f15gdsy** [comment]
```javascript
let Scrollmagic
if (typeof window === 'undefined') {
    Scrollmagic = require('scrollmagic')
}
```

This code should run without error on both client & server side.

**Comment by uptownhr** [comment]
Do you need this code for the server?

**Comment by uptownhr** [comment]
Can you show us an example of how scroll magic will be used? You may just want to require from your mounted life cycle hook

**Comment by maziarz** [comment]
I do not need this code for server, only client-side..

**Comment by pirony** [comment]
I' m creating a plugin to use scrollmagic with vuejs and nuxt easily... it works but I did not pushed the update to npm and github yet.
I'll do it tomorrow, if you can wait a bit :)

**Comment by maziarz** [comment]
@pirony, that sounds awesome! I can surely wait..

**Comment by pirony** [comment]
Here we are... [https://github.com/pirony/ks-vue-scrollmagic](https://github.com/pirony/ks-vue-scrollmagic)

```bash
npm i --save ks-vue-scrollmagic
```
then in ~/plugins/ksVueScr.js
```js
import Vue from 'vue'
import KsVueScrollmagic from 'ks-vue-scrollmagic'
Vue.use(KsVueScrollmagic)
```
and finally add it to nuxt.config with ssr:false option. You should be good to go.

You can see it in action [here](https://jsfiddle.net/romainPouchol/bstj6p41/5/)

Btw, the v-scrollmagic directive binding value MUST follow a predefined schema... I'll explained which one more deeply tomorrow. Sorry for teasing, but it's a bit late now. ^^

**Comment by maziarz** [comment]
@pirony thats excellent! will give it a go!! :-)

**Comment by Atinux** [comment]
Love this thread!

The help of each others to solve the issue and make a Vue plugin fully functional with Nuxt.js :heart:

**Comment by pirony** [comment]
I' ve updated the plugin, and made some big changes...
The way I handled tweening was a bit verbose and had limitations (Scrollmagic is very versatile and I couldn't find a pattern that could work in every cases (or at least the majority).

Check [this fiddle](https://jsfiddle.net/romainPouchol/v9jhjspn/) to see how it works now!
Give it a try and feel free to open an issue [here ](https://github.com/pirony/ks-vue-scrollmagic) if you have questions and/or difficulties and/or enhancements proposal

**Comment by maziarz** [comment]
@pirony, thats so awesome! Good job mate!!!

**Comment by iamdubx** [comment]
@pirony awesome! Thank you!
