### ISSUE TITLE
Can I use decorators in Nuxt.js ?

### ISSUE THREAD

**Issue by f15gdsy** [nuxt/nuxt.js#1837]
Hi, I'm trying to use decorators in Nuxt.js.
I tried to edit .babelrc by setting build.babel.babelrc to true, and adding a babelrc that includes the babel-plugin-transform-decorators as a plugin.
But the compilation did not work though.

Is it because the Node.js do not support decorators yet so that I could not use decorator in SSR?

**Comment by dotneet** [comment]
It works for me.

```bash
npm install --save-dev babel-plugin-transform-decorators-legacy
```

nuxt.config.js
```
build: {
  babel: {
    plugins: ['babel-plugin-transform-decorators-legacy']
  }
}
```

**Comment by f15gdsy** [comment]
@dotneet Thanks, it works now.
