### ISSUE TITLE
Fetch data from an api for all views at first load

### ISSUE THREAD

**Issue by dennerkrans** [nuxt/nuxt.js#184]
I'm currently building a page where we get all content for all views as json from our api. Is there anyway to load the data from the api before anything else?

**Comment by Atinux** [comment]
Hi @dennerkrans 

You need to use the `vuex` store with the [nuxtServerInit action](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action).

Please take a look at the documentation for more details.
