### ISSUE TITLE
Use coffeescript on middlewares section

### ISSUE THREAD

**Issue by raultrysw** [nuxt/nuxt.js#1844]
Hi, I was learning about coffeescript recently and me would like to integrate coffeescript on middlewares section of a nuxt project, is it posible? =)

**Comment by qm3ster** [comment]
As long as you don't want CoffeeScript inside your `.vue` files it *should* be as simple as:
```sh
yarn add -D coffee-loader
```
```js
// # nuxt.config.js
module.exports = {
  build: {
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        /* You may have this from eslint, not in here, always */
      }
      config.module.rules.push({
        // enforce: 'pre', // Do we need this? Literally no one can know!
        test: /\.(coffee)$/,
        loader: 'coffee-loader'
      })
    }
  }
}
```

**Comment by raultrysw** [comment]
I get this output:
![Error image](https://i.imgur.com/5eASUe0.png)

I already  made what you said

**Comment by qm3ster** [comment]
According to #1782, it shouldn't even have tried to import the file automatically.
Are you importing it yourself? For example:
```coffee
//# middleware/script.coffee
console.log 'holaaaaaa desde coffee'
```
```js
//# middleware/coffeescript.js
import something from './script.coffee'
```
It seems that webpack **is** grabbing the file but isn't using the correct loader.
Please post your package.json and nuxt.config.js

**Comment by raultrysw** [comment]
My package.json: https://pastebin.com/6p5E7Fik
My nuxt.config.js: https://pastebin.com/yyzBLPDY
My middleware/recoveruser.js: https://pastebin.com/xtAX3zzT
My middleware/script.coffee: https://pastebin.com/HwfKZSrg

These are the files that i edited to get coffescript into the nuxtjs project

**Comment by qm3ster** [comment]
I AM CALLING THE POLICE

**Comment by qm3ster** [comment]
I specifically put a comment well in advance, ` /* You may have this from eslint, not in here */` to not put it in the same `if` as the eslint, as the eslint only runs for client bundle (for performance, why run it on both), but you need to compile both client bundle and server bundle, both in dev and in prod, so you just need to put it in the `extend` function but not in the `if` block.

So yeah, change
```js
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
        config.module.rules.push({
          test: /\.coffee$/,
          use: 'coffee-loader',
          exclude: /(node_modules)/
        })
      } // 〜(￣△￣〜) not this bracket, no
    }
```
to 
```js
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      } //  〜(￣▽￣〜) dat bracket tho
      config.module.rules.push({
        test: /\.coffee$/,
        use: 'coffee-loader',
        exclude: /(node_modules)/
      })
    }
```
And you will be golden.
For now you will have to re-export it through a `.js` file, the way you did, but as soon as  #1782 is merged, you will be able to just drop a `.coffee` in middleware without an accompanying `.js` file.

**Comment by raultrysw** [comment]
Ok, thanks!, me would like to know a more thing...
How can I make a route other than not would be in the pages directory? For example, a mongo users recovery?
Me happens that I want an asyncronous function that ables me to recover users as in an express application from mongodb and push it to the context, thanks

**Comment by qm3ster** [comment]
You should use [dynamic routes](https://nuxtjs.org/guide/routing#dynamic-routes) or query parameters.
If you use dynamic routes with `nuxt generate` (static hosting) you will need to add a rewrite to your hosting configuration.

**Comment by Atinux** [comment]
Closing for keeping the discussion on https://github.com/nuxt/nuxt.js/pull/1782
