### ISSUE TITLE
Expose build performance analysis

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#1845]
## Feature request
Add a flag to print all steps of Webpack process to console.
(similar to `webpack --progress --profile`)
It shouldn't be much more difficult than [something like this](https://github.com/webpack/webpack-cli/blob/c8633c0475cc1860f025933b43a8e32915bb7376/bin/webpack.js#L365) somewhere [in this area](https://github.com/nuxt/nuxt.js/blob/8849fdabcc14e87697e3825515324135ab4505e6/lib/builder/webpack/client.config.js#L139).

**Comment by Atinux** [comment]
Actually, it can be implemented as a nuxt module directly :smile: 

See https://github.com/nuxt-community/webpackmonitor-module

**Comment by qm3ster** [comment]
That's crazy :open_mouth:
Would a PR to https://github.com/nuxt-community/modules be appropriate?

**Comment by Atinux** [comment]
@qm3ster I added you into https://github.com/nuxt-community

You should be able to create a repo for it (maybe calling it `build-progress-module`), please use https://github.com/nuxt-community/module-template to create the module, it will help you to create it in seconds :)

**Comment by Atinux** [comment]
@qm3ster when ready, you can email me (see my GH profile) so I can add you on the NPM org for @nuxtjs

**Comment by qm3ster** [comment]
How can I remove the existing plugin?
I tried 
```js
const ProgressBarPlugin = require('progress-bar-webpack-plugin')
const ProgressPlugin = require('webpack/lib/ProgressPlugin')

const badIndex = plugins.findIndex(plugin =>
    (plugin.hasOwnProperty('profile') && plugin.profile === undefined) ||
    plugin instanceof ProgressPlugin ||
    plugin instanceof ProgressBarPlugin,
)
if (badIndex !== -1) plugins.splice(badIndex, 1)
plugins.push(new ProgressPlugin({profile: true}))
```
Problem is, only the first condition matches.
I don't think I should publish a module that slaughters the first plugin it finds by such a stupid heuristic.
Do you have any advice?

**Comment by qm3ster** [comment]
Also, at one point I got this error:
`Cannot find module '/example-project/nuxtjs/webpack-profile'`, clearly related to   `modules: ['~/modules/typescript.js', '@nuxtjs/webpack-profile'],` It might have ~something~everything to do with the `@` alias. Do we still need it, or is `~` enough for v1.0? It seems like it slightly clashes with normal scoped module syntax.

**Comment by pi0** [comment]
@qm3ster Would you please push your initial works to `webpack-profile` repo?

**Comment by pi0** [comment]
@qm3ster Would you please push your initial works into `webpack-profile` repo? I would like to help on this :)

**Comment by qm3ster** [comment]
https://github.com/nuxt-community/webpack-profile-module
Here you go

**Comment by pi0** [comment]
So let's make it a 🍟

**Comment by pi0** [comment]
FYI https://github.com/nuxt-community/webpack-profile-module is now working :) I think this is a REALLY useful option for users inspecting build times and as @Atinux adding support to Nuxt itself is simple enough and adds no new dependency.
