### ISSUE TITLE
Add nuxt-developer documentation

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#1847]
(as opposed to nuxt-app-developer documentation)
## Feature request
Add a surface level overview of the architecture of nuxt:
 - What are the directories (in this repo, not a nuxt-based web app project)
 - What is the build + testing process
 - How directory watching and reloading is implemented
 - How filesystem API is implemented
 - How code-splitting is implemented

This will enable third party developers to make small contributions more easily, and potentially (it always happens) expose inefficiencies / incorrectness by talking through the architecture.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1659">#c1659</a>)</em></sub></div>

**Comment by Atinux** [comment]
This is of course a great feature request, will work on it as soon as 1.0 is stable.

We want more contributors and of course we need a lower barrier for contributors to help making Nuxt.js better :tada:

**Comment by manniL** [comment]
This is partly done in https://nuxtjs.org/guide/contribution-guide

Please open an issue in nuxt/docs (https://cmty.app/nuxt/issues/new?repo=docs) for further discussions
