### ISSUE TITLE
Error: This dependency was not found using the ~ shortcut in the express nuxt template

### ISSUE THREAD

**Issue by nekdolan** [nuxt/nuxt.js#1848]
I am using the nuxt-express template and if I try to import a file with the ~ in the express server api files I get the error
> This dependency was not found

So webpack (in this case backpack) is parsing the api files but for some reason will not replace the '~' the same way it would do for vue files

How can I tell webpack/backpack to replace the ~ with the sourcepath ?

**Comment by cretueusebiu** [comment]
Backpack uses a different configuration for webpack so you'll have to add the alias:

_backpack.config.js_

```javascript
const path = require('path')

module.exports = {
  webpack: (config, options, webpack) => {
    config.entry.main = './server/index.js'
   
    // https://webpack.js.org/configuration/resolve/#resolve-alias
    config.resolve.alias = {
      '~': path.resolve(__dirname, './')
    }

    return config
  }
}
```

Now `~` will point to the root directory of the project.

**Comment by nekdolan** [comment]
Thanks @cretueusebiu, this works.
My only complaint is that ~ should point to the source path (~~ is root) but that's not a real issue.
