### ISSUE TITLE
Access the file system

### ISSUE THREAD

**Issue by nachocab** [nuxt/nuxt.js#1849]
In express.js I can write a controller that: 

1. accesses the file system
2. reads the contents of a directory, and
3. sends that information as a local variable to the view.

I'm not sure how to go about this in nuxt.js because I can't require the `fs` module from the component. Is there anywhere where I can populate a variable with a list of files in the server (for example, in the `static` folder) so that the component has access to it?

**Comment by cretueusebiu** [comment]
You'll have to write a route on your back-end server that exposes an api endpoint. 
Then make a request from your component to the server to fetch the files.

**Comment by nachocab** [comment]
@cretueusebiu Thanks! So does that mean that I need to have both an express server (backend) and a Nuxt server (frontend)?

**Comment by cretueusebiu** [comment]
Well, what kind of files are you tried to load in your components ?

**Comment by nachocab** [comment]
@cretueusebiu they are simple text files, or html files generated by another application

**Comment by cretueusebiu** [comment]
Those can be loaded with axios. See this [comment](https://github.com/nuxt/nuxt.js/issues/1850#issuecomment-336544027). But you'll have to know what files are you're fetching. 

If you want to scan a directory for the files you might need a back-end server. Or at least a Node script that generates a another json file that you can load and then fetch all the files.
