### ISSUE TITLE
read local storage on default layout?

### ISSUE THREAD

**Issue by samkitano** [nuxt/nuxt.js#185]
Is there any way to deal with localStorage, in order to set a property based on it for the entire application?

Let's say I want to read a locally stored token to determine if a user has access to an API, and then set a boolean property on the layout, to be propagated to the relevant components, ie. navbar, login, logout, etc.

something like this:

```html
<template>
  <div>
    <app-nav :authed="authed"/>
    <nuxt :authed="authed"/>
  </div>
</template>

<script>
  import AppNav from '~components/Nav.vue'

  export default {
    data: function () {
      return {
        authed: false
      }
    },

  components: {
    AppNav
  },

  created: () => {
    this.authed = localStorage.getItem('token') !== null
  }
}
</script>
```

This example would generate an error ```localStorage is not defined```

How can I accomplish this?

**Comment by Atinux** [comment]
Hi @samkitano 

You should not use the localStorage since it's not defined in node.js.

Please take a look at https://github.com/nuxt/nuxt.js/tree/master/examples/auth-routes

**Comment by samkitano** [comment]
Oh, thanks a lot, @Atinux! 

Quite useful, as I'm still wrapping my head around some concepts, and I totally missed this Doc.

Sorry for using the issue tracker for this.
