### ISSUE TITLE
asyncData doesn't work when load from `static`

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1850]
For some reason this doesn't work

```js
asyncData ({ params }) {
    return axios.get('data.json')
      .then((res) => {
        return { title: res.data.title }
      })
  }
```

How to load data from `static` folder? 
I have JSON files there, where I want to manage content.

**Comment by cretueusebiu** [comment]
You'll have to either provide the full url:

```javascript
axios.get('http://localhost:3000/data.json')
```
Or load it in the `mounted` hook:

```javascript
mounted () {
  axios.get('/data.json')
    .then(({ data }) => {
      return { title: data.title }
    })
}
```

**Comment by iamdubx** [comment]
@cretueusebiu if I load it in `mounted` then it doesn't server render content! Is there any way to solve it? I want both - ssr and ability to modify content in builded app.

**Comment by cretueusebiu** [comment]
Use the full URL as in the first example.

**Comment by iamdubx** [comment]
@cretueusebiu and conditionally replace url when build? I mean there will be one url in Dev and another in Prod, right?

**Comment by cretueusebiu** [comment]
Of course, you would use an env variable for the url. And maybe extract the code to a file where you have the api calls.

**Comment by iamdubx** [comment]
If I use 

```js
asyncData ({ params }) {
    return axios.get('http://localhost:3000/data.json')
      .then((res) => {
        console.log(res)
        return { data: res.data }
      })
  }
```
Then I can't do `npm run generate` because `Error: connect ECONNREFUSED 127.0.0.1:3000`

**Comment by iamdubx** [comment]
It shouldn't be separate server. I wan't this JSON file inside Nuxt app.

**Comment by cretueusebiu** [comment]
If you don't want to load it just import it as you do with js files:

```javascript
import data from 'path/to/data'
```

**Comment by iamdubx** [comment]
I tried that first. Then I can't edit file content. If I edit JSON file it doesn't have any effect to app.

**Comment by iamdubx** [comment]
And this is strange behavior. Because Nuxt is copying JSON file into `dist` for some reason. Why it's doing that, if it doesn't consume it?

**Comment by iamdubx** [comment]
I guess it's because JSON file is from `static` folder. But then this is not a solution for me, because requiring the JSON is merging it's data with app. I want it to be **separate**

**Comment by lunelson** [comment]
I guess you either figured this out by now, or did something else; but I would try putting the file you want in your `assets` folder, rather than `static`, and `import` from there via webpack. I believe the contents of assets are tracked for changes...

**Comment by mootari** [comment]
> I tried that first. Then I can't edit file content. If I edit JSON file it doesn't have any effect to app.

You can add [custom watch paths](https://nuxtjs.org/api/configuration-build#watch) to your nuxt config:
```javascript
build: {
  watch: ['path/to/data']
}
```
A change to these files will trigger a rebuild and restart the server.

Note that Nuxt path prefixes (`@`, `~`, etc.) in watch paths won't work: https://github.com/nuxt/nuxt.js/issues/2983

**Comment by Jones-S** [comment]
Same problem here. But no need for editing json files. 
Just the requirement to load json files during `nuxt generate` with asyncData.

`return axios.get('http://localhost:3000/data.json')` does not work, as we know,
but what else could I use...?

**Comment by lunelson** [comment]
I had this working by simply using `require` to require the JSON file. Webpack takes care of it. If you need route params to know what file to require, you can do it inside the `asyncData` callback.

**Comment by wett1988** [comment]
I make simple workaround for this issue.

After run `npm run generate`, i start simple server on folder `/static`, and write new path to `$axios` settings

on nuxtconfig.js

`
    ['@nuxtjs/axios', {
      baseURL: 'http://localhost:8000'
    }]
`

on `nuxt run generate` script call to `localhost:8000` and successfully get data from `/static` folder

P.S.: May be important at what address you run the temporary server. 

When i run `php -S localhost:8000` - the script gave the same error as before. 
But when i run `php -S 127.0.0.1:8000` script run successfully.
