### ISSUE TITLE
Update to Vue v2.5.0+

### ISSUE THREAD

**Issue by hirokiosame** [nuxt/nuxt.js#1851]
Vue 2.5.1 was released last night. Can the dependency in NUXT be updated?

**Comment by hojas** [comment]
And Vue 2.5.2 was released.

**Comment by ooade** [comment]
Can we just add @greenkeeper to keep our packages updated

**Comment by Atinux** [comment]
Actually a new version of Vue can bring some breaking changes, that’s why we want to make sure it’s fully compatible before releasing a new version.

Next release coming will have Vue 2.5!

**Comment by hirokiosame** [comment]
@Atinux 
Yes, I fully expect thorough testing to come with it.

We were waiting on the "default" feature in provide/inject to be released in 2.5.0+, but currently blocked by NUXT from upgrading; don't mean to rush any work but do you have a ballpark date?

**Comment by JamieLottering** [comment]
If you can't wait you can manually update all the dependencies using the "resolutions" field.
In your package.json:

```
"resolutions": {
  "nuxt/vue": '^2.5.2"
}
```

You'll most likely get a warning that vue has a version mismatch so you'll have to add all of those updated dependencies into the resolutions field until it works. This is also assuming you're using `yarn` over `npm install`

**Comment by hirokiosame** [comment]
@JamieLottering Are you sure that's a real property? It's [not documented](https://docs.npmjs.com/files/package.json) and it didnt work

**Comment by JamieLottering** [comment]
@hirokiosame That's because it's not an NPM feature, it's a yarn feature

https://yarnpkg.com/en/docs/selective-version-resolutions

**Comment by hirokiosame** [comment]
@JamieLottering Oh sorry I overlooked that. Thank you!

**Comment by dohomi** [comment]
@Atinux any chance to see `rc-12` sometimes soon to make use of the `vue 2.5` features? Thanks!

**Comment by cliffrowley** [comment]
Just FYI if you want to use this now with `npm` rather than `yarn` you can simply use the git URL and commit hash.

    "dependencies": {
        ...
        "nuxt": "https://github.com/nuxt/nuxt.js#<hash>",
        ...
    }

Use this in your dependencies and then `npm i` and you should be set.  As of this writing, the current hash is `de2b0a6d5619c5f5334a289ac3287e1ee838b9bc` but it'll obviously change as more commits are added.

Note that the commit hash is important because without it you won't get the dev branch.

**Comment by hirokiosame** [comment]
@cliffrowley 
Does installing the dev branch work for you? I was under the impression it wouldn't because it doesn't come with distribution files.

**Comment by cliffrowley** [comment]
Seems to be working just fine for me - are you having issues?

**Comment by pi0** [comment]
I can confirm that using GitHub dependency **won't work** as we need dist files! https://github.com/nuxt/nuxt.js/issues/1851#issuecomment-336948759 is probably this best temporary solution.

**Comment by cliffrowley** [comment]
*shrug* I must have been dreaming the past week then...

**Comment by pi0** [comment]
@cliffrowley I think that's working for you because doing an extra npm install/build inside node_modules/nuxt?

**Comment by cliffrowley** [comment]
@pi0 nope, I literally just changed my `package.json`, ran `npm i` and carried on.  I'm using nuxt with express, so maybe that makes a difference?  Everything works just fine.
