### ISSUE TITLE
Fetching data from Vuex store in component

### ISSUE THREAD

**Issue by lsbyerley** [nuxt/nuxt.js#1852]
Hello, I'm running into an issue where when I initially load the page, my data isn't being loaded, however if I navigate to another page, and then click back to the home page, the data is loaded into the component. I'm not sure what I'm doing wrong either in my component or store, any tips appreciated. Relevant files below..

// store/index.js

    const createStore = () => {
        return new Vuex.Store({
            state: {
                repos: []
            },
            actions: {
                LOAD_REPOS: function({ commit }) {
                    axios.get('repourl').then((res) => {
                        commit('SET_REPOS', res.data)
                    })
                }
            },
            mutations: {
                SET_REPOS: (state, repos) => {
                    state.repos = repos
                }
            }
        })
    }
    
    export default createStore

// pages/index.vue

    <template>
        <div class="page-content">
            <p v-for="repo in repos">{{ repo.name }}</p>
        </div>
    </template>
    
    <script>
    import { mapState } from 'vuex'
    
    export default {
        fetch ({ store }) {
            store.dispatch('LOAD_REPOS')
        },
        computed: mapState([
            'repos'
        ])
    }
    </script>

**Comment by lsbyerley** [comment]
For those wondering, here is the solution..

    async fetch ({ store }) {
        if (store.state.repos.length === 0) {
            const data = await store.dispatch('LOAD_REPOS')
        }
    }

    actions: {
        LOAD_REPOS: async function({ commit }) {
            const res = await axios.get('repourl')
            commit('SET_REPOS', res.data)
        }
    }

**Comment by nop33** [comment]
How does it work though when I want to use an `action` from a component that is *not* a page component? :/

**Comment by lsbyerley** [comment]
@nop33 What do you mean an action from a component? The action should always be stored in the vuex store, and you can call the action from any component

**Comment by TesalVector** [comment]
Fatch function don't work in DIR components. How use Vuex store (data) in DIR components?
