### ISSUE TITLE
Page is rendered even if `fetch` called `redirect`

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/nuxt.js#1853]
If a page has `fetch` method which invokes `redirect` immediately (e.g. rejecting users without required permissions), that page is still rendered internally for no reason. This happens in nuxt@1.0.0-rc11.

This is however not happening if the same logic is moved to the middleware. It requires a developer to create separate single-use middleware even for ad-hoc page-specific logic.

## Experiment 1

Create `pages/test.vue`:

```vue
<template>
  <div>
    This will crash: {{ noSuchVar }}
  </div>
</template>

<script>
export default {
  fetch ({ redirect }) {
    return redirect('/')
  },
}
</script>
```

**Result:** opening <http://localhost:3000/test> immediately redirects to <http://localhost:3000> but the following is printed to stderr:

```
[Vue warn]: Property or method "noSuchVar" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in
 the data option.

found in

---> <Client/pages/test.vue> at client/pages/test.vue
       <Nuxt> at .nuxt/components/nuxt.vue
         <Default> at client/layouts/default.vue
           <Root>
```

## Experiment 2

Create `pages/test2.vue`:

```vue
<template>
  <div>
    This will not crash: {{ noSuchVar }}
  </div>
</template>

<script>
export default {
  middleware: 'test',
}
</script>
```

and `middleware/test.vue`:

```js
export default function ({ redirect }) {
  return redirect('/')
}
```

**Result:** opening <http://localhost:3000/test> immediately redirects to <http://localhost:3000> and no errors are produced.

## Expected result

The two experiments behave identically (no errors are produced in either case).

**Comment by Atinux** [comment]
Should be fixed in next release :)

**Comment by pimlie** [comment]
@Atinux Just to be sure, I am experiencing the same issue when returning a redirect in `asyncData`. I guess that is the same issue as this?

**Comment by Atinux** [comment]
Yep!

**Comment by dw72** [comment]
A notice the same issue when redirect in middleware

**Comment by Mikeysax** [comment]
I'm getting the same issue using `fetch` in a page and redirect:
```js
export async function EDIT_TEACHER({ dispatch, commit, state }, { id }) {
  try {
    const { data } = await this.$axios({
      url: `/teachers/${id}/edit`,
      method: 'get'
    });
    commit('SET_TEACHER', data.teacher);
  } catch ({ response }) {
    if (response.status === 401) {
      dispatch('PROMPT_SIGN_IN');
    } else if (response.status === 302) {
      this.$router.push(`/teachers/${id}`);
    }
  }
}
```
It redirects but then renders the edit page again.

**Comment by furyscript** [comment]
Also me, some news about that? @Atinux

**Comment by Atinux** [comment]
If this bug re-appeared, please re-open a fresh bug report with a reproduction.

**Comment by furyscript** [comment]
Yes this is a repo reproduction: https://github.com/furyscript/nuxt-redirect-error

You need to login, go to inspire page and make sure the first http call is a 200 request. After that try to refresh page (F5 into /inspire) until the http call return a 401 error, so you see that you return to home and not in login page.
