### ISSUE TITLE
inject('i18n', new VueI18n(...)) doesn't work in plugin files

### ISSUE THREAD

**Issue by Jinjiang** [nuxt/nuxt.js#1856]
But `app.i18n = new VueI18n(...)` works.
It means the example in https://nuxtjs.org/guide/plugins fails.

It reported: `Cannot read property '_t' of undefined` in `node_modules/vue-i18n/dist/vue-i18n.common.js:L176`:

```js
return i18n._t.apply(i18n, [ key, i18n.locale, i18n._getMessages(), this ].concat( values ))
```

related package info:

```
    "nuxt": "^1.0.0-rc11",
    "vue-i18n": "^7.3.1",
```

**Comment by Atinux** [comment]
Oops, I will fix the example into the docs, indeed, `vue-i18n` already makes its installation with `Vue.use(VueI18n)`

Thank you @Jinjiang
