### ISSUE TITLE
client-side alternative to nuxtServerInit

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1857]
I am running some localStorage operations in store. Is there a way to dispatch this action similar to nuxtServerInit but on client-side instead?

**Comment by Atinux** [comment]
We are working on implementing a `nuxtClientInit` for `spa` mode.

Be aware that you can have a mismatch between client-side and server-side if you fetch some data that can change the DOM into your localStorage.

Also, you can actually reproduce `nuxtClientInit` yourself, see https://github.com/nuxt/nuxt.js/issues/240#issuecomment-326893386

**Comment by maziarz** [comment]
Works like a charm :-) Excellent.. I will keep that in mind..
