### ISSUE TITLE
When/how is the head() function computed?

### ISSUE THREAD

**Issue by WouterFlorijn** [nuxt/nuxt.js#1858]
I'm using the vue-i18n plugin to translate page titles. The locale is set in a Vuex store by a middleware. I then have a `plugins/i18n.js` file that retrieves the locale from the store and passes it to i18n, which is then registered with Vue.

When translating page contents, eveything works and the locale in the store is used. For anything in the `head()` function (such as the page title) however, the fallback locale is used, as the locale in the store appears to be undefined the moment the `head()` function is executed.

Is there a way to circumvent this? I can provide code if needed. Sorry for asking this here. I've tried Stackoverflow, but questions like this seem to be too specific to get any answers.

**Comment by Atinux** [comment]
Hi @WouterFlorijn 

The best is to provide us a small reproduction repository so we can take a deep look at it without loosing time.

Please re-open this issue with a repo link to a public repo to reproduce this issue.
