### ISSUE TITLE
(docs) yarn/npm upgrade installs rc9 instead of rc11

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#1859]
As I could not find information about this anywhere, it would be nice if the docs could list the following issue. Due to a bug/feature in SemVer check, version `rc9` is regarded as a higher version then eg `rc11`. See https://jubianchi.github.io/semver-check/, put `^1.0.0-rc9` on the left and `1.0.0-rc11` on the right. 

This means that if you run eg `yarn upgrade` it will by default install `rc9`. The funny thing is, if you run `yarn upgrade nuxt@latest` it *does* install `rc11`. 

Both `npm outdated` as `yarn outdated` reflect this issue:
```
$ npm outdated
Package      Current       Wanted         Latest  Location
nuxt      1.0.0-rc11    1.0.0-rc9     1.0.0-rc11  

$ yarn outdated
yarn outdated v1.1.0
Package Current    Wanted    Latest     Package Type URL                                   
nuxt    1.0.0-rc11 1.0.0-rc9 1.0.0-rc11 dependencies https://github.com/nuxt/nuxt.js#readme
Done in 0.99s.
```
Relevant yarn issue: https://github.com/yarnpkg/yarn/issues/3560

I guess this was the same reason why in the past you switched from `alpha2` to `alpha.2`?

**Comment by qm3ster** [comment]
`1.0.0-rc11` < `1.0.0-rc9`
`1.0.0-rc.11`  `1.0.0-rc.9`
Not having a dot makes them compare alphabetically.
This happens very often.
npm doesn't have epoch, so fixing this is awkward.

Next version has to be something like 1.0.0-rc**a**.12 to get all of the `-rc9` users to update.

Funnily enough, `1.0.1-rc.12` wouldn't satisfy `^1.0.0-rc11` either.

**Comment by Atinux** [comment]
Next release will be `1.0.1-rc.12`, thank you @pimlie @qm3ster for this precious information :)

**Comment by qm3ster** [comment]
That won't work :open_mouth:

**Comment by Atinux** [comment]
@qm3ster what do you suggest instead? `1.0.0-rca.12`?

**Comment by qm3ster** [comment]
As ugly it is, yeah. That correctly updates everyone and will be fixed once 1.0.0 is out.

**Comment by Atinux** [comment]
Actually I would like to have 1 or 2 RC left before official 1.0 :/

What about `1.0.0-rca`, then `1.0.0-rcb` and finally `1.0.0`

Ping @alexchopin @pi0

**Comment by qm3ster** [comment]
There's also `-rc9[1-9]` range :stuck_out_tongue:
But although I doubt there will be 8 more versions before 1.0, my vote is for a variant that compares the last group numerically, eg `-rca.12` (`-rca.1` would confuse people) because that's Semver™ and stands for Reeleeze CAndidate

**Comment by Atinux** [comment]
Yes but I would like to show that these last `rc` are the last one:

- Release Candidate A -> `rca`
- Release Candidate B -> `rcb`

So we can tell everyone to upgrade to `rca` without having to give a number (even if it's not perfect Semver™). I don't think they will last for long anyway :)

**Comment by qm3ster** [comment]
There hasn't been a release in a while, but lots of commits every day. Is there some blocking issue preventing a release?

**Comment by qm3ster** [comment]
Congratulations.
