### ISSUE TITLE
How to integrate stylus global styl as a global color file?

### ISSUE THREAD

**Issue by rlam3** [nuxt/nuxt.js#1861]
How to integrate stylus global styl as a global color file?

I've already included the necessary file but none of the styles are rendering up .

```js
    {src: '~/assets/stylus/global.styl', lang: 'stylus'}

```

Thanks!

**Comment by danhawkes** [comment]
Couple of thoughts:
- Have you added `stylus-loader` to your dependencies?
- Don't think global styles are added to a global namespace by their the respective loaders. So to actually reference colours in `assets/stylus/page.styl` you'd still need to `@import 'global'`.
