### ISSUE TITLE
Using query parameters in require statements: require('~/assets/something?test=true')

### ISSUE THREAD

**Issue by danhawkes** [nuxt/nuxt.js#1862]
Hi, I've encountered an issue I think might be due to the magic import handling for assets. Using nuxt 1.0.0-rc11.

I'm using [responsive-loader](https://github.com/herrstucki/responsive-loader) to resize images from assets.

If I configure the loader in `nuxt.config.js` like this:
```javascript
 extend: (config, { isClient }) => {
      const urlLoader = config.module.rules.find(
        rule => rule.loader === 'url-loader'
      );
      urlLoader.test = /\.(gif)$/;

      config.module.rules.push({
        test: /\.(jpe?g|png)$/i,
        loader: 'responsive-loader',
        options: {
          placeholder: true,
          placeholderSize: 20,
          sizes: [300]
        }
      });
    },
```
...then this works:

```javascript
require(`~/assets/images/${item.key}/${i}.png`)
```
However, if I add a query parameter:
```javascript
require(`~/assets/images/${item.key}/${i}.png?sizes[]=300`)
```
I get:
```
 Cannot find module "~/assets/images" 
```
Is this due to import handling, or have I misconfigured the loader? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1673">#c1673</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
