### ISSUE TITLE
 https://nuxtjs.org can not open

### ISSUE THREAD

**Issue by yyyuuu777** [nuxt/nuxt.js#1869]
today , when i visit  https://nuxtjs.org can not open , but get Error 502 Ray ID: 3ae8ed315df017ec • 2017-10-16 06:22:56 UTC

**Comment by yoyo837** [comment]
The same.  Doc site report bad gateway all of them.

**Comment by lanbau** [comment]
Got this too.. 

Error 502 Ray ID: 3ae965e88f10700e • 2017-10-16 07:45:21 UTC
Bad gateway

**Comment by kmsheng** [comment]
Got the same, could not open

**Comment by donne1226** [comment]
cant coding without doc :(

**Comment by mickdekkers** [comment]
Getting the same issue :(

For those that need them now, the docs can also be found here in markdown format https://github.com/nuxt/docs

**Comment by maziarz** [comment]
I assume this is running on GH pages, does not seem to be down from GH's view of point..

**Comment by KaelWD** [comment]
If they're using Zeit Now, it looks like there's some problems with it right now. We're having the same issue over at https://vuetifyjs.com/

**Comment by mickdekkers** [comment]
@KaelWD [vuetifyjs.com](https://vuetifyjs.com) seems to load fine for me, but the nuxt website is still unreachable.

**Comment by yoyo837** [comment]
The same as @mickdekkers

**Comment by Atinux** [comment]
Fixed, sorry about this

**Comment by yoyo837** [comment]
@pi0 @Atinux 
The sites cannot be accessed, again.

**Comment by Atinux** [comment]
Fixed, sorry about this
