### ISSUE TITLE
NuxtJS Authentication With Django API

### ISSUE THREAD

**Issue by Mohsunbagheri** [nuxt/nuxt.js#1871]
Hi guys
i've searched but didn't find any examples 
please help me
do you have any examples ?

**Comment by maziarz** [comment]
Depends on what type of authentication you are planning to use. I think this is too application specific.

**Comment by vuchl** [comment]
You can have a look at the older Django related issues: https://github.com/nuxt/nuxt.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20django
