### ISSUE TITLE
Unable to have ignored parameters in a dynamic route

### ISSUE THREAD

**Issue by AlexandreBonneau** [nuxt/nuxt.js#1875]
I'm trying to setup routes to display a given user post (named `snap` in my case).
The route to show a specific post is `/{user}/snap/{idSnap}`.

Now, to make it more friendly I want the user to be able to link to that post by adding a totally optional (and not used at all) *slug* after that url.
So the user should be able to see that same post by going to `/{user}/snap/{idSnap}/{slugSnap}`.

I tried ~too~ many directory and filename configurations, but unfortunately cannot find a way to make it work so that:
- The user can go to `/usertest/snap/12`,
- The user *cannot* go to `/usertest/snap`, and
- The `/usertest/snap/12/slugfoo` url works.

This is the last directory configuration I tried so far:
![nuxt_routing_hell](https://user-images.githubusercontent.com/7248877/31645000-27a1ce6e-b295-11e7-97e2-7f03b278d8ed.png)

Moreover, in all the configurations I tried, since the [documentation](https://nuxtjs.org/guide/routing) states that in order to make a parameter mandatory you need to create an `index.vue` file in the param directory, is it possible to have the `/usertest/snap/12` and `/usertest/snap/12/slugfoo` urls points **to the same component**?

Thanks!

**Comment by AlexandreBonneau** [comment]
Note, when I manually create the routes without nuxt and only with vue-router I can get the behavior I want using [that configuration](https://codesandbox.io/s/3180y51lpp).

Specifically, I modified the generated routes like this:
```js
{
    path: '/:user/snap/:idSnap',
    component: idSnap,
    name: 'user-snap-idSnap',
    children: [
        {
            path: ':slugSnap?',
            // component: slugSnap, // With nuxt.js (fails)
            component: idSnap, // Manually with vue-router (works)
            name: 'user-snap-idSnap-slugSnap',
        },
    ],
},
```

**Comment by alexchopin** [comment]
Hi @AlexandreBonneau, 

You only need to remove the `index.vue` file in your case and use the `validate()` methods in the `_idSnap.vue` file.

```js
validate ({ params }) {
  return params.idSlug !== undefined // You can also use redirect if you don't want to display a 404 page
} 
```
This will generate this route path: `/:user/snap/:idSnap?/:slugSnap?`.

Then, 
- The user can go to `/usertest/snap/12`
- The user cannot go to `/usertest/snap`
- The `/usertest/snap/12/slugfoo` url works.
