### ISSUE TITLE
Move from babel-preset-es2015 to babel-preset-env

### ISSUE THREAD

**Issue by Alex-Sokolov** [nuxt/nuxt.js#1877]
Now when installing packages there is warning:

```
[1/4] Resolving packages...
warning nuxt > babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
[2/4] Fetching packages...
```

Maybe switch from `preset-es*` to `env`?

**Comment by Atinux** [comment]
It's implemented in the next release, coming soon.

**Comment by sergiocastrovale** [comment]
Is there any way we can force this switch now? I'm using Objection.js and I'm having an issue I don't think I can go around with if I don't use the following config:

`
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      }
      }],
    "stage-1"
  ],
`

Is there any way I can do so?

**Comment by atos1990** [comment]
@Atinux , will it be possible to change babel-preset-env options via nuxt.config.js?

**Comment by atos1990** [comment]
@Atinux , will it be possible to change the babel-preset-env options via nuxt.config.js?
Now I have different options for client/server(targets: ie:9/node:true) and can't  configure their correct, because don't have context

**Comment by Atinux** [comment]
Are you setting `build.babel.presets` key?

**Comment by atos1990** [comment]
@Atinux  , yes. How I can specify targets in this preset? This property different for client and server, but bundles for their build with the single command - 'nuxt build'. I don't now how dynamically change this property during build

**Comment by atos1990** [comment]
I know that I can specify different environments in .babellrc. But default NUXT webpack configs doesn't have process.env.BABEL_ENV :(
