### ISSUE TITLE
nuxtServerInit cannot commit state

### ISSUE THREAD

**Issue by darbaoui** [nuxt/nuxt.js#1878]
Hi @Atinux ,
i have an issue about commit new state (token) to the store via nuxtServerInit function, the token displayed in my terminal in the server side but in my vue-devtools the state.token not refreshed and have the intial state.

![capture d ecran 2017-10-17 a 10 24 27](https://user-images.githubusercontent.com/6907747/31660223-4670ffc2-b326-11e7-85ff-6b54028d2772.png)

**Comment by Atinux** [comment]
Hi @darbaoui 

From your screenshot, I can see that VUEX cannot call the `USER_AUTH` mutation since it's not define.

Make sure you created the `USER_AUTH` mutation into your store (https://vuex.vuejs.org/en/mutations.html)

**Comment by darbaoui** [comment]
Hi @Atinux 
USER_AUTH is already created in mutation.
![capture d ecran 2017-10-17 a 10 37 52](https://user-images.githubusercontent.com/6907747/31660580-5c8cef0e-b327-11e7-8c3d-3e91fe38344b.png)

**Comment by darbaoui** [comment]
the error occur in the first screenshot, because i updated the name of mutation only in the nuxtServerInit function to take the screenshot.

`export const state = () => ({
  authUser: false,
  token: ''
})
export const mutations = {
  USER_AUTH: function (state, data) {
    state.authUser = data.auth
    state.token = data.token
  }
}
export const actions = {

  async nuxtServerInit ({ commit }, { req }) {
    let token = await getCookie('token', req)
    if (token) {
      console.log(token)
      return commit('USER_AUTH', {token, auth: true})
    }
  }
}
`
any help, suggestion 
@Atinux

**Comment by Atinux** [comment]
Can you create a minimal reproduction repo so I can try to debug your issue please?

**Comment by darbaoui** [comment]
@Atinux 
thank you, i fixed this issue by reinstall node_modules from scratch.
