### ISSUE TITLE
tag BODY modification

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#188]
how to modify the tag BODY?
as described in the documentation https://github.com/declandewet/vue-meta
changes are not applied

**Comment by Atinux** [comment]
I will need an example to help you.

**Comment by wormen** [comment]
@Atinux 
```
<body class="home-page home page page-id-4 page-template page-template-template-homepage page-template-template-homepage-php">
```

**Comment by Atinux** [comment]
```vue
<script>
export default {
  head: {
    bodyAttrs: {
      class: 'home-page home page page-id-4 page-template page-template-template-homepage page-template-template-homepage-php'
    }
  }
}
</script>
```

Please read [nuxt documentation](https://nuxtjs.org/guide/views/#html-head)

**Comment by proov** [comment]
Hello ! This works perfectly thanks @Atinux :) However, i'm using some custom page transitions and while page elements are leaving, body classes are removed and replaced only when the new page is done :( You know if there is a way to trigger bodyAttrs: { class } when transition `done()` is called ?

Thanks :+1:

**Comment by ChrisRM** [comment]
@proov If you make that `head` parameter a function it becomes **reactive**, so whenever your data changes, the meta-data changes. E.g:

```js
export default {
    data () {
        return {
            dataLoaded: false
        }
    },

    head () {
        return {
            bodyAttrs: {
                class: this.dataLoaded ? 'home-page home page page-id-4 page-template page-template-template-homepage page-template-template-homepage-php' : ''
            }
        }
    },

    // fetch data in some hook and set this.dataLoaded to true.
}
```
