### ISSUE TITLE
How to add webpack config in WebStorm 2017.2

### ISSUE THREAD

**Issue by miecio1212** [nuxt/nuxt.js#1881]
Where I can find webpack config to add it I rly would like to use this feature in WebStorm :).
(support for aliases)

**Comment by dotneet** [comment]
WebStorm 2017.2 has a bug related to alias.
In last month, WebStorm 2017.3 EAP is out and it has fixed this bug.

https://confluence.jetbrains.com/display/WI/WebStorm+EAP

I've located webpack.config.js on root project directory and confirmed that alias works well with this EAP.

**Comment by miecio1212** [comment]
@dotneet Ok but Nuxt has it's own webpack with aliases so ? how to use them in WebStorm ?

**Comment by dotneet** [comment]
@miecio1212 
I think that's not possible. because webpack setting is built by nuxt dynamically when we run `nuxt build`.
so we need to add a dummy webpack.config.js by ourself.

**Comment by miecio1212** [comment]
@dotneet what do you mean by dummy could you send me example ?

**Comment by dotneet** [comment]
@miecio1212 here is my `webpack.config.js`

```js
const path = require('path')

module.exports = {
  resolve: {
    extensions: ['.js', '.json', '.vue', '.ts'],
    root: path.resolve(__dirname),
    alias: {
      '@': path.resolve(__dirname),
      '~': path.resolve(__dirname),
      'ss': path.join(path.resolve(__dirname), 'lib'),
    },
  },
}
```

**Comment by miecio1212** [comment]
@dotneet thanks I'll try it! :)
