### ISSUE TITLE
nuxt's PAGES to routes mechanism doesn't support patterns like this.

### ISSUE THREAD

**Issue by SevenOutman** [nuxt/nuxt.js#1883]
Here's my scenario.

I have a view to review the "summary" of all "projects", which consists of several charts and tables and stuff like that,
and I need a page to review the summary of one project specified by its "id",
both pages has exactly same layouts and structure
so I need to map `projects/summary` and `projects/:id/summary` to a single page comp.

How do I arrange my PAGES dir to make that happen?

P.S. I don't think `projects/summary/:id` will be a good solution because I believe a `projectId` should only follow "projects", not a name of any other resource models, e.g. "summary".

**Comment by AlexandreBonneau** [comment]
For info, I expressed a very similar problem few days ago on #1875.

**Comment by KonstantinVlasov** [comment]
First solution: not sure if it suitable for you, but you can use this url for all projects:
`projects/all/summary`
then it will be the same `summary.vue` file for both cases

Other solution: you can create separate component for summary view `components/summary.vue` and include it in both pages

P.S. I use the first solution for my project

**Comment by SevenOutman** [comment]
@KonstantinVlasov You mean you have a `projects/_id/summary.vue` and it can accept 'all' as `id`? Nice solution there, but I want to hear from authors if there's some more 'strict' solutions. :)

**Comment by KonstantinVlasov** [comment]
@SevenOutman, "other solution" it's hint from authors :)

**Comment by alexchopin** [comment]
Hi @SevenOutman,
@KonstantinVlasov gave you the best solution in my opinion.
`projects/_id/summary.vue` will create this route path `projects/:id?/summary`.
With this solution `/projects/summary` and `/projects/ID/summary` will go to the same page.

**Comment by SevenOutman** [comment]
@alexchopin @KonstantinVlasov Your suggestions help. Thanks.
