### ISSUE TITLE
Facing difficulties with nuxt routing and i18n

### ISSUE THREAD

**Issue by pirony** [nuxt/nuxt.js#1884]
Hi there!
I'd like  my generated routes to be:
```
/
/:category
/:category/:slug
/en/
/en/:category
/en/:category/:slug
```
The problem is that :category overrides /en, so when I visit "http://localhost:3000/en" the _category.vue is used instead of index.vue. 
It seems logical afterwards...but how can I avoid this?
What should be my pages folder structure to achieve the result above ? (Nuxt i18n example shows only static routes config)
Thx

**Comment by alexchopin** [comment]
Hi @pirony, which version of nuxt are you using?

**Comment by pirony** [comment]
Hi @alexchopin , thx for answering.
I'm using nuxt-community's starter template, shipped with nuxt v1.0.0rc11

**Comment by cesasol** [comment]
I have alse made a multilang site, and the way that I managed to solve the problem was to always have a /LANG/ route with the middleware, that way you can have all of your routes inside the _lang folder, even if it is nested or wildcard. And for the base index you only import/export the lang index:

```
pages
├── index.vue
└── _lang
    ├── conoce.vue
    ├── hire-us.vue
    ├── index.vue
    ├── know.vue
    ├── saiba.vue
    ├── services.vue
    ├── servicios.vue
    ├── servicos.vue
    ├── _slug*.vue
    └── yago-de-marta.vue
```

**Comment by pirony** [comment]
Hi @cesasol , and thanks for answering!
yes It's the solution I'm using ATM... but I'd really like to get rid of that  '/fr/' part when current locale is the main language. :)

**Comment by tmorehouse** [comment]
See  this solution: https://github.com/nuxt/nuxt.js/issues/112#issuecomment-340574312
