### ISSUE TITLE
Error running tests: Unexpected token: punc ()

### ISSUE THREAD

**Issue by homerjam** [nuxt/nuxt.js#1885]
I'm having trouble running tests on the latest dev branch. Multiple errors like below:

```
ERROR in pages/async-data.d75fdc644a911e620031.js from UglifyJs
Unexpected token: punc (() [pages/async-data.d75fdc644a911e620031.js:25,11]
```

I've tried following the suggestion below (using `uglifyjs-webpack-plugin`) but it still fails, I think this has to be something to do with babel. Has anything changed with webpack setup recently? Should there be a `.babelrc` file?

https://stackoverflow.com/questions/42375468/uglify-syntaxerror-unexpected-token-punc

**Comment by antonVl** [comment]
Hi, this code can help you: `
      config.module.rules.push({
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: function (modulePath) {
          return /node_modules/.test(modulePath) &&
            !/node_modules\/vue2-google-maps/.test(modulePath);
        },
        options: Object.assign({}, this.babelOptions)
      })

` 
i had same problem with vue2-google-maps and you can replace name of module

**Comment by homerjam** [comment]
Hi @antonVl, thanks for your suggestion however it looks like your fix refers to `nuxt.config.js` - I'm having trouble running the tests in a cloned nuxt.js repo rather than a nuxt app.

**Comment by homerjam** [comment]
@Atinux @pi0 are tests working for you?

**Comment by homerjam** [comment]
Sorry! Appears fixed now!
