### ISSUE TITLE
change the server error page

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#1889]
I wonder if there are other ways to change the server error page, except to change the 'app/view/error.html' page, I think there might be other configuration items that I didn't find, and so on

**Comment by dotneet** [comment]
I found out the other way.
You can use build.templates to change the server error page like this:

```js
build: {
  templates: [
      {
        src: './views/error.html',
        dst: 'views/error.html'
      }
    ],
}
```
