### ISSUE TITLE
It's impossible to pass props from layout?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1894]
I am trying to pass props from `default.vue` layout to `<nuxt/>`, so they could be available in Page Component. Is it possible?

**Comment by christophwolff** [comment]
You should use the store for this.

**Comment by iamdubx** [comment]
@christophwolff it is overkill in my case. I have only few pages and components on small landing site.

**Comment by iamdubx** [comment]
I refactor some stuff...So I guess it's more logic to store such data in Page components if I don't want to use Vuex. 

Last question - if I want to pass data from one Page Component to another Page component, then the only option is store?

**Comment by alexchopin** [comment]
@iamdubx yes the store is the only solution in your case.
