### ISSUE TITLE
Import vue plugin correctly (unexpected token import)

### ISSUE THREAD

**Issue by Twisterking** [nuxt/nuxt.js#1896]
So I want to use https://github.com/niksmr/vue-masked-input in my app.

I tried several variations of including/importing this plugin into my nuxt app but every single one failed.
I always get the following error:

```
clientErrorHandler err /Users/Patrick/dev/server/node_modules/vue-masked-input/dist/maskedInput.js:3
import InputMask from 'inputmask-core';
^^^^^^

SyntaxError: Unexpected token import
```

I already tried:

- importing the plugin directly like so: `import MaskedInput from 'vue-masked-input'`
- importing it with `import MaskedInput from '~/plugins/vue-masked-input'` and a plugin file with the following code:
```
import Vue from 'vue'
import MaskedInput from 'vue-masked-input'

Vue.use(MaskedInput)

export default MaskedInput
```

The only solution working is including it in my component like so:
```
let MaskedInput;
if(proccess.browser) {
    MaskedInput = require('vue-masked-input')
}
```

Problem is that, obviously, in that case on a server side render of the page the plugin is not loaded and thus can not be used in the template.

I am totally confused on how to use VueJS plugins like this one in a nuxt app properly.

Please help! Thanks a bunch!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1697">#c1697</a>)</em></sub></div>

**Comment by christophwolff** [comment]
Have you tried to set ssr to false?
https://nuxtjs.org/examples/plugins

**Comment by Twisterking** [comment]
Yep I did ... did not change anything. The plugin itself is simply not "babelified" on server-side at all, thus the `import` stays in the code and is not transpiled to a `require`.

**Comment by benmccallum** [comment]
Having a similar issue. Ever solve yours?

**Comment by UnGast** [comment]
Same here.

**Comment by NicoPennec** [comment]
This issue is know from the `vue-masked-input` component: https://github.com/niksmr/vue-masked-input/issues/25

**Comment by agriboz** [comment]
I integrated [this](https://github.com/moip/awesome-mask) plugin to my project with the code example below.

Under the plugins folder i created `maskedInput.js` file and wrote this code.

`import Vue from 'vue'`
`import AwesomeMask from 'awesome-mask'`
`Vue.directive('mask', AwesomeMask)`

And for the `vue` file

`<b-input v-model="item.enrollment.gsmTel" v-mask="'(999)-999-99-99'"  @input="$v.item.enrollment.gsmTel.$touch()"></b-input>`
