### ISSUE TITLE
vuetify 16.8 not work with nuxtjs lastest version only 16.1

### ISSUE THREAD

**Issue by dinho-afsn** [nuxt/nuxt.js#1899]
nuxtjs layout is making vuetify overlay stop working
I have a login layout and another default,
After logging in I'm redirected to the dashboard screen.
if I enter through the browser http: // myurl / dashboard the overlay closes when I click.
if I log in to http: // myurl / login and after login I redirect (self. $ nuxt. $ router.replace ({path: '/ dashboard')) to dashboard.
the click on orverlay stops working
I tested it without using nuxtjs and it worked, so I think there is something from nuxtjs that is breaking some js from vuetify, but it does not generate any errors

i tested! nuxtjs not work with vuetify 16.8 only 16.1
broken navigation drawer overlay

I tested with version 16.1 and it works, in version 16.8 does not work the click of the overlay in navigationdrawer when we use different layouts in nuxtjs

**Comment by husayt** [comment]
Hi, It is not clear what is your problem, but FYI  that version of vuetify works just fine for us.

**Comment by dinho-afsn** [comment]
I solved loading a la cart 16.9

import Vue from 'vue'
import directives from '../node_modules/vuetify/src/directives'

import {
  Vuetify,
  VApp,
  VCard,
  VNavigationDrawer,
  VFooter,
  VList,
  VBtn,
  VIcon,
  VGrid,
  VToolbar,
  VTooltip,
  VProgressCircular,
  VTextField,
  VSnackbar,
  VSubheader,
  VAvatar,
  VBadge,
  VDivider,
  VProgressLinear,
  VBottomSheet,
  VTabs,
  VExpansionPanel,
  transitions,
  VSwitch,
  VDataTable,
  VCheckbox,
  VSelect,
  VMenu,
  VDialog

} from 'vuetify'

Vue.use(Vuetify, {
  components: {
    VApp,
    VCard,
    VNavigationDrawer,
    VFooter,
    VList,
    VBtn,
    VIcon,
    VGrid,
    VToolbar,
    VProgressCircular,
    VTextField,
    VSnackbar,
    VSubheader,
    VAvatar,
    VBadge,
    VDivider,
    VProgressLinear,
    VBottomSheet,
    VTabs,
    VExpansionPanel,
    transitions,
    VSwitch,
    VDataTable,
    VCheckbox,
    VSelect,
    VTooltip,
    VMenu,
    VDialog
  },
  directives
})


and nuxtconfig

const nodeExternals = require('webpack-node-externals')
const resolve = (dir) => require('path').join(__dirname, dir)

module.exports = {
  head: {
    title: 'nuxt-vuetify',
    meta: [
      {charset: 'utf-8'},
      {name: 'viewport', content: 'width=device-width, initial-scale=1'},
      {hid: 'description', name: 'description', content: 'App project'}
    ],
    link: [
      {rel: 'icon', type: 'image/x-icon', href: '/favicon.ico'},
      {rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons'}
    ]
  },
  plugins: ['~plugins/vuetify.js'],
  css: ['~/assets/style/app.styl'  ],
  loading: {color: '#3B8070'},
  build: {
    babel: {
      plugins: [
        ['transform-imports', {
          'vuetify': {
            'transform': 'vuetify/es5/components/${member}',
            'preventFullImport': true
          }
        }]
      ]
    },
    vendor: [
      'vuetify'
    ],
    extractCSS: true,
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      if (ctx.isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vuetify/]
          })
        ]
      }
      config.node = {fs: 'empty'}
      config.module.rules.forEach(rule => {
        if (rule.test.toString() === '/\\.styl(us)?$/') {
          rule.use.push({
            loader: 'vuetify-loader',
            options: {
              theme: resolve('./assets/style/theme.styl')
            }
          })
        }
      })
    }
  }
}

**Comment by SergeyKhval** [comment]
@dinho-afsn I encountered the same problem. I guess in each of your layouts you have a top level `v-app` wrapper. The directive in `vuetify` that is responsible for hiding components when overlay is clicked is `click-outside.js` and it attaches event listeners to `v-app`. When you change layouts `v-app` is recreated and all event listeners are garbage collected by the browser. It can be solved by attaching events to `document.body`, however `vuetify` states that `v-app` has to be in the dom for clicks to work on iOS [see here](https://github.com/vuetifyjs/vuetify/blob/master/src/directives/click-outside.js#L61)
