### ISSUE TITLE
Can this be used with github pages?

### ISSUE THREAD

**Issue by dan-gamble** [nuxt/nuxt.js#19]
I'm looking into multiple static site generators and i love using Vue, would i be able to use this with github pages or would i need to deploy it somewhere like DO? :)

**Comment by Atinux** [comment]
It is possible :)
The command is nuxt generate, and will generate all the pages for your web application, you can take a look at https://github.com/alexchopin/alexchopin.github.io

**Comment by Atinux** [comment]
Look especially at the package.json

**Comment by dan-gamble** [comment]
Awesome 👍 It looks like it has SSR too, didn't think that would be possible!

**Comment by Atinux** [comment]
For me, it is the most powerful feature of Nuxt.js, we call it with my brother: serverless rendered

**Comment by dan-gamble** [comment]
Dayum, gonna give it a try now. Thanks :)

**Comment by Atinux** [comment]
Our documentation website will be generated and hosted on Github pages, backed by AWS lambda to regenerate the website if a commit is pushed to the master branch. Infinite possibilities 🔥

**Comment by dan-gamble** [comment]
Can't wait to see it :)

**Comment by thedamon** [comment]
Is that what's happening now? Looking at package.json looks like you're using Surge. some docs around the recommended approach to this would be great esp since dist is in the .gitignore. Although honestly, Surge looks really cool ;)

**Comment by thedamon** [comment]
Yeah It looks pretty neat! I am thinking of setting it up for my project, too since it might be just as/more straightforward than github pages

**Comment by justinshea** [comment]
Hi @Atinux - Are you aware of any current documentation or examples that show the workflow for using AWS Lambda to generate static nuxt site to cdn (like gh pages or s3)? The part I am having trouble understanding is how the updated app code package from repository (with dependencies) would get into lambda after function is called by webhook/sns...
