### ISSUE TITLE
Setting meta data based on asyncData 

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1900]
In my SPA i am dealing with a slightly unusual problem. I am fetching data for each page from static json files. Within these files all the content is represented, including the meta data. Unfortunately i am experiencing that the variable can be null due to its async behaviour and cause an error. How do i work around this?

Here is an example of what i am doing:

```
export default {
  data () {
    return {
      content: ''
    }
  },
  async asyncData ({req, params}) {
    let { data } = await axios.get(`/data/blog/${params.slug}.json`)
    return { content: data }
  },
  head () {
    if (this.content.seoMetaTags) {
      this.content.seoMetaTags.map((meta) => {
        if (meta.tagName === 'title') {
          return {
            title: 'lol'
          }
        }
      })
    }
  }
}
```

**Comment by KonstantinVlasov** [comment]
You can just check if seoMetaTags exists

**Comment by maziarz** [comment]
@KonstantinVlasov, i tried this, and it works perfectly for the exception handling. Unfortunately the title is not being set. I am simply checking with inspector, it shows empty title.

**Comment by maziarz** [comment]
I just updated my example, which does not work..

**Comment by maziarz** [comment]
So apparently  my return did not really work within the `map` function.. I changed it to a for-loop and now its working.
