### ISSUE TITLE
Error building Scss

### ISSUE THREAD

**Issue by MatthieuHPP** [nuxt/nuxt.js#1901]
Hello,

I am trying to compile my project the last version of Nuxt (I was using alpha5) and I am getting Error with Scss special chars.
I am using node 6.11 and Ubuntu 16.04

Here is the error message on the console : It refers to the contents of scss import within a Vue page 
```
Error : Module build failed  // the error points the @ behind import
@import "~/assets/css/SCSS_partials/variables";
```
// nuxt.config.js extract
```
css: [
    // SCSS file in the project
    '@/assets/css/main.scss'
 ]
```
What should I do to make it works ?

Many thanks

Matthieu

**Comment by paulgv** [comment]
Did you install `node-sass` and `sass-loader`?
```sh
yarn add node-sass sass-loader -D
```
Or
```sh
npm install node-sass sass-loader -D
```

**Comment by MatthieuHPP** [comment]
Thanks for your reply.
Both are installed.
Matthieu

**Comment by MatthieuHPP** [comment]
I do have 18 errors after the build with RC11.
All was working on alpha5 version.

Here is the beginning of one of the 18 similar error messages 
```
Module build failed: 
@import "~/assets/css/SCSS_partials/variables";
^
      File to import not found or unreadable: ~/assets/css/SCSS_partials/variables.

```

**Comment by paulgv** [comment]
Try replacing `@import "~/assets/css/SCSS_partials/variables";` with `@import "~assets/css/SCSS_partials/variables";`

**Comment by MatthieuHPP** [comment]
Many thanks for your help. 
I tried... still does not work.
I moved back to the alpha5 version of Nuxt, waiting for more info to use the latest version.
Matthieu

**Comment by MatthieuHPP** [comment]
Here is some more info on my configuration :

// nuxt.config.js

```
const webpack = require('webpack')
module.exports = {
  head: {
    //titleTemplate: '%s - helping-pong',
    htmlAttrs: {
      lang: 'fr'
    },
    title: ' xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid : 'robots', name: 'robots', content: 'index, follow' },
      { hid : 'description', name: 'description', content: 'xxxxxxxxxxxxxxx '+
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
    ],
    script:[
            {src:'/socket.io/socket.io.js'},
            {src:'js/easyrtc.js', type: 'text/javascript'},
            {src:'js/pixel.js', type: 'text/javascript'}
        ]
  },
  build: {
     vendor:
      [
        'axios',
        'lodash.debounce'
      ],
     plugins: [
      new webpack.ProvidePlugin({ '_': 'lodash'})
    ]
   },
  css: [
    // SCSS file in the project
    '@/assets/css/main.scss'
    // link also tested
    // { src: '~/assets/css/main.scss', lang: 'scss' } // scss instead of sass
 ],
 env: {
    HOST_URL: process.env.HOST_URL || 'https://my_domain.com:3001'
  },
  modules: [
    ['@nuxtjs/google-analytics', { ua: 'UA-79029609-1' }],
    '@nuxtjs/sitemap'
  ],
  sitemap: {
 }
}
```
// package.json  
// only relevant packages
```
{
  "name": "my_domain_server",
  "version": "0.0.9",
  "author": "Matthieu ",
  "description": "first XXXXXXXXXXXXXXXX",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "start_app": "NODE_ENV=production forever start server_app_cluster.js",
    "start_easyrtc": "NODE_ENV=production forever start server_easyrtc_cluster.js"
  },
  "dependencies": {
    "@nuxtjs/google-analytics": "^1.0.0",
    "@nuxtjs/sitemap": "0.0.3",
    "axios": "^0.15.3",
    "lodash": "^4.17.4",
    "nodemailer": "^4.2.0",
    "nuxt": "^1.0.0-rc11",
    "socket.io": "^2.0.3",
    "webpack": "^3.8.1"
  },
  "engines": {
    "node": ">=0.8"
  },
  "devDependencies": {
    "morgan": "^1.8.1",
    "node-sass": "^4.5.0",
    "sass-loader": "^6.0.2"
  }
}
```
// Extract of one Vue page calling scss :
```
<style lang="scss">
@import "~/assets/css/SCSS_partials/variables";
// .......................
<style >
```
// Scss files tree
```
assets
-----css
--------main.scss
--------SCSS_partials
----------------main.scss
----------------_variables.scss
----------------_flex.scss
```

**Comment by MatthieuHPP** [comment]
The error messages disappear if I use @import with a relative path :

```
<style lang="scss">
@import "../assets/css/SCSS_partials/variables";
// .......................
<style >
```

instead of :

```
<style lang="scss">
@import "~/assets/css/SCSS_partials/variables";
// .......................
<style >
```

In my case, the use of the alias ~ does not enable to find scss files whereas it works for images, js files ...

**Comment by Nayir** [comment]
Hi @MatthieuHPP , at first you tried to load you scss file globally (nuxt.config), but finally you used it in a .vue file ? I have the same issue, i'm trying to load it globally from nuxt.config.js and I can't find the answer.

**Comment by MatthieuHPP** [comment]
Hi @Nayir, Exactly !
I'have posted a waver october the 30th, but no good solution found.

**Comment by qm3ster** [comment]
@MatthieuHPP did you solve the issue?

**Comment by wafs** [comment]
Issue is still here.
Regardless of if I make a global SCSS and import something there, or load it in the nuxt config, every component where I don't explicitly import SCSS variables will fail to compile.

**Comment by qm3ster** [comment]
This looks like a clear case of `SCSS` doing its own path resolving, not relying on webpack.
You need to set up the aliases yourself in your SCSS loader config.
