### ISSUE TITLE
How to add this AD script code to a page?

### ISSUE THREAD

**Issue by snoopy83101** [nuxt/nuxt.js#1903]
<script async src="//adserver.juicyads.com/js/jads.js"></script>
<ins id="624872" data-width="300" data-height="262"></ins>
<script>(adsbyjuicy = window.adsbyjuicy || []).push({'adzone':624872});</script>

My site has a lot of pages and only one page needs it
How to add this code to a page??

**Comment by snoopy83101** [comment]
`
<script async src="//adserver.juicyads.com/js/jads.js"></script>
<ins id="624872" data-width="300" data-height="262"></ins>
<script>(adsbyjuicy = window.adsbyjuicy || []).push({'adzone':624872});</script>
`

**Comment by snoopy83101** [comment]
and this one...

```
<!-- JuicyAds PopUnders v3 Start -->
<script type="text/javascript" src="https://js.juicyads.com/jp.php?c=3464w2v2r284u4q2o2a4039414&u=http%3A%2F%2Fwww.juicyads.rocks"></script>
<!-- JuicyAds PopUnders v3 End -->
```
Very demanding:

**Standard PopUnders v3 Code
Copy and Paste this code near the top of your website in the BODY tag, not HEAD tag.
Traffic we cannot sell will be sent to the Return URL at the end of the code (URL must be encoded).
For best results and highest earnings, place code on each website separately.**

**Comment by pauldariye** [comment]
Creating a separate layout for that page could help if you want a clean and simple way @snoopy83101 .

**Comment by snoopy83101** [comment]
I just do not understand what should have been very simple function, why not allow?

**Comment by binggg** [comment]
@pauldariye 
How to add a external script in layout?


```
<!-- JuicyAds PopUnders v3 Start -->
<script type="text/javascript" src="https://js.juicyads.com/jp.php?c=3464w2v2r284u4q2o2a4039414&u=http%3A%2F%2Fwww.juicyads.rocks"></script>
<!-- JuicyAds PopUnders v3 End -->
```

**Comment by pauldariye** [comment]
@binggg, I gave it a try [here](https://github.com/pauldariye/nuxt-example-external-script) but  not sure how the script is initialized with juicy. My example doesn't work but hopefully it will give some direction on how to get it working. I don't have a juicy ads account to test with. 

Also, there's a strange behavior with this `https://js.juicyads.com/jp.php?c=3464w2v2r284u4q2o2a4039414&u=http%3A%2F%2Fwww.juicyads.rocks` script

**Comment by clarkdo** [comment]
Try `head`
https://nuxtjs.org/api/pages-head#the-head-method
https://github.com/declandewet/vue-meta#script-object
