### ISSUE TITLE
Can't make Nuxt work on Ubuntu

### ISSUE THREAD

**Issue by johnRivs** [nuxt/nuxt.js#1904]
Node: 8.1.4
npm: 5.3.0
nuxt: 1.0.0-rc11

I develop on Windows, where I have no problems. `npm install`, `npm run build`, `npm start` and I can access the app on `http://localhost:3000`. I can set a different port as well and works just fine.

When I push the app to production (a droplet in DigitalOcean) and start the app all I get is the generic error page that says "Server error". Nothing in the nginx logs, nothing in the console where I run `npm start`, nothing in the browser console (I just get a 500 error). When I `curl` the app though, this is what I get:
```json
{
  "status": 500,
  "message": "initProxy is not a function",
  "name": "TypeError"
}
```

I've also tried using Vagrant (a Homestead box specifically) and it's pretty much the same when I `curl` within the virtual machine, except the message is `argument str must be a string`.

Homestead: Ubuntu 16.04
Server: Ubuntu 14.04.3

**Comment by snoopy83101** [comment]
I've had this problem before

Try to upload these two folders to the server
.nuxt  
Ubuntu server

Don't build and install on the server,

**Comment by johnRivs** [comment]
Same thing.

**Comment by snoopy83101** [comment]
So try.Nuxt first
If you need to use Windows development, the development environment as much as possible to use the Linux virtual machine
Otherwise, it will be very tangled

**Comment by snoopy83101** [comment]
Sorry, I said it with the translation software

**Comment by johnRivs** [comment]
As I mentioned, I already tried using Vagrant and I have a similar problem.

**Comment by johnRivs** [comment]
I managed to use `npm run dev` on the server and this is what I got:
![](https://i.imgur.com/mP3XTnL.png)

I see vue.runtime.common.js but, shouldn't it be vue.runtime.esm.js?

**Comment by snoopy83101** [comment]
I was put a very large folder (node_modules) into the server.
Although some compatibility issues, but after the install can work
But since then, I decided not to use windows to develop node
It is best to buy a mac

**Comment by johnRivs** [comment]
@snoopy83101 Hey.. I don't think if you're missing some of my comments. I have the same problem when I use Vagrant running Ubuntu or my server to either `npm install`, `npm run dev`, `npm run build` or `npm start`.

**Comment by johnRivs** [comment]
Managed to get it working on Vagrant. `argument str must be a string` was referring to a cookie parsing issue.

The funny thing about `initProxy is not a function` is that it doesn't even get to run, because `process.env.NODE_ENV !== 'production'` on my server returns `false`.

**Comment by johnRivs** [comment]
Got it!

Turns out that line did get to run because `NODE_ENV` was `undefined`. I'm using `dotenv` and it was replacing the system's environment variables. I just added `NODE_ENV=production` to the `.env` file at the root of the project and now it works.
