### ISSUE TITLE
Custom Layout Error

### ISSUE THREAD

**Issue by teddysasmita** [nuxt/nuxt.js#1905]
I am using nuxt.js with element-ui. I get error "offsetWidth of undefined" in Chrome or 'this.$refs.nav is undefined' in Firefox when I change the page layout. The error occurs whenever the browser is refreshed.
However I notice that in simpler page the error does not occur. Please help. Thanks

**Comment by paulgv** [comment]
Hi! Could you share your code to help reproduce the error?

**Comment by teddysasmita** [comment]
Yes, I can.

<template>
<div class="users">
<el-row :gutter=15  type="flex" justify="center">
  <el-col :span="4">
    <el-table ref="userstable"  :data="userslist" highlight-current-row @current-change="selectuser">
      <el-table-column label="Nama User" prop="username"></el-table-column>
    </el-table>
    <el-button class="btnappend" type="warning" @click="appenduser">Tambah</el-button>
  </el-col>
  <el-col :span="16">
    <h3>{{ detiltitle }}</h3>
    <el-tabs v-model="maintab" type="border-card" @tab-click="tabclick">
      <el-tab-pane label="Detil" name="detil">
        <el-form label-width="120px" :model="user">
          <el-form-item label="Nama Login"><el-input v-model="user.username"></el-input></el-form-item>
          <el-form-item label="Alamat"><el-input v-model="user.address"></el-input></el-form-item>
          <el-form-item label="No Kontak"><el-input v-model="user.phone"></el-input></el-form-item>
          <el-form-item label="Password"><el-input v-model="user.password" type="password"></el-input>
          </el-form-item>
          <el-form-item label="Konfirmasi"><el-input v-model="passwordconfirm" type="password"></el-input>
          </el-form-item>
          <el-form-item label="Nama Lengkap"><el-input v-model="user.fullname"></el-input></el-form-item>
          <el-form-item label="Tempat Lahir"><el-input v-model="user.pob"></el-input></el-form-item>
          <el-form-item label="Tanggal Lahir"><el-date-picker v-model="user.dob" format="yyyy/MM/dd"></el-date-picker></el-form-item>
          <el-form-item label="Kota"><el-input v-model="user.city"></el-input></el-form-item>
          <el-form-item label="E-mail"><el-input v-model="user.email"></el-input></el-form-item>
          <el-form-item>
            <el-button type="primary" @click="postuser">Simpan</el-button>
            <el-button type="danger" @click="deleteuser">Hapus</el-button>
          </el-form-item>
        </el-form>
      </el-tab-pane>
      <el-tab-pane label="Otoritas" name="otoritas">
        <el-row :gutter="15"  type="flex" justify="center">
          <el-col :span="8">
            <el-table ref="userauthstable" :data="userauthslist" highlight-current-row @current-change="selectuserauth">
              <el-table-column label="Otoritas User" prop="item_name"></el-table-column>
              <el-table-column label="Operasi">
                <template scope="scope">
                  <el-button size="small" type="danger" @click="deleterole">Hapus</el-button>
                </template>
              </el-table-column>
            </el-table>
          </el-col>
          <el-col :span="8">
            <el-table ref="authstable" :data="authslist" highlight-current-row @current-change="selectauth">
              <el-table-column label="Otoritas" prop="name"></el-table-column>
              <el-table-column label="Operasi">
                <template scope="scope">
                  <el-button size="small" type="success" @click="addrole">Tambah</el-button>
                </template>
              </el-table-column>
            </el-table>
          </el-col>
        </el-row>
      </el-tab-pane>
    </el-tabs>
  </el-col>
</el-row>
</div>
</template>

<script>
import axios from 'axios'

export default {
  // layout: 'form',
  created: function () {
    this.getusers()
  },
  data: function () {
    return {
      userslist: [],
      user: {
        id: '',
        username: '',
        fullname: '',
        pob: '',
        dob: '',
        phone: '',
        address: '',
        city: '',
        email: '',
        password: '',
        active: '',
        accessToken: '',
        authKey: '',
        userlog: '',
        datetimelog: ''
      },
      availrole: {
        name: '',
        type: 1,
        description: '',
        rule_name: '',
        data: '',
        created_at: '',
        updated_at: ''
      },
      userrole: {
        item_name: '',
        user_id: '',
        created_at: ''
      },
      passwordconfirm: '',
      detiltitle: 'Data Baru',
      mode: 'insert',
      userauthslist: [],
      authslist: [],
      maintab: 'detil'
    }
  },
  asyncData: function (context) {
    return axios.get('http://localhost:3001/users/list/all/').then(
      function (response) {
        if (response.status === 200) {
          // console.log('BOOM')
          return { userslist: response.data }
        }
      })
  },
  methods: {
    tabclick: function (clickedtab) {
      if (this.maintab === 'otoritas') {
        this.getauths()
        this.getuserauths()
      }
    },
    addrole: function () {
      this.userrole.item_name = this.availrole.name
      this.userrole.user_id = this.user.id
      this.userrole.created_at = ''
      var _this = this
      axios.post('http://localhost:3001/users/addrole', _this.userrole)
        .then(function (response) {
          if (response.status === 200) {
            if (response.data === 'ok') {
              _this.$notify({ title: 'Response', message: 'OK', type: 'success' })
              _this.getuserauths()
            } else {
              _this.$notify({ title: 'Response', message: 'Gagal', type: 'danger' })
            }
          }
        })
    },
    deleterole: function () {
      var _this = this
      axios.post('http://localhost:3001/users/deleterole', _this.userrole)
        .then(function (response) {
          if (response.status === 200) {
            if (response.data === 'ok') {
              _this.$notify({ title: 'Response', message: 'OK', type: 'success' })
              _this.getuserauths()
            } else {
              _this.$notify({ title: 'Response', message: 'Gagal', type: 'danger' })
            }
          }
        })
    },
    getusers: function () {
      var _this = this
      axios.get('http://localhost:3001/users/list/all/').then(
        function (response) {
          if (response.status === 200) {
            _this.userslist = response.data
            _this.appenduser()
          }
        })
    },
    getuserauths: function () {
      var _this = this
      var id = this.user.id
      axios.get('http://localhost:3001/users/userauthlist/' + id).then(
        function (response) {
          if (response.status === 200) {
            _this.userauthslist = response.data
          }
        })
    },
    getauths: function () {
      var _this = this
      axios.get('http://localhost:3001/users/authlist/all/').then(
        function (response) {
          if (response.status === 200) {
            _this.authslist = response.data
          }
        })
    },
    selectuserauth: function (val) {
      if (val !== null) {
        if (val !== null) {
          for (var p in this.userrole) {
            this.userrole[p] = val[p]
          }
        }
      }
    },
    selectauth: function (val) {
      if (val !== null) {
        for (var p in this.availrole) {
          this.availrole[p] = val[p]
        }
      }
    },
    selectuser: function (val) {
      if (val !== null) {
        for (var p in this.user) {
          this.user[p] = val[p]
        }
        if (this.maintab === 'otoritas') {
          this.getauths()
          this.getuserauths()
        }
        this.user.password = ''
        this.passwordconfirm = ''
        this.detiltitle = this.user.username
        this.mode = 'update'
      }
    },
    appenduser: function () {
      this.user = {
        id: '',
        username: '',
        fullname: '',
        pob: '',
        dob: '',
        phone: '',
        address: '',
        city: '',
        email: '',
        password: '',
        active: '',
        accessToken: '',
        authKey: '',
        userlog: '',
        datetimelog: ''
      }
      this.mode = 'insert'
    },
    postuser: function () {
      var _this = this
      if (this.mode === 'update') {
        axios.post('http://localhost:3001/users/update', _this.user)
          .then(function (response) {
            if (response.status === 200) {
              if (response.data === 'ok') {
                _this.$notify({ title: 'Response', message: 'OK', type: 'success' })
                _this.getusers()
              } else {
                _this.$notify({ title: 'Response', message: 'Gagal', type: 'danger' })
              }
            }
          })
      } else if (this.mode === 'insert') {
        axios.post('http://localhost:3001/users/append', _this.user)
          .then(function (response) {
            if (response.status === 200) {
              if (response.data === 'ok') {
                _this.$notify({ title: 'Response', message: 'OK', type: 'success' })
                _this.getusers()
              } else {
                _this.$notify({ title: 'Response', message: 'Gagal', type: 'danger' })
              }
            }
          })
      }
    },
    deleteuser: function () {
      var _this = this
      var id = this.user.id
      this.appenduser()
      axios.get('http://localhost:3001/users/delete/' + id).then(
        function (response) {
          if (response.status === 200) {
            if (response.data === 'ok') {
              _this.$notify({ title: 'Response', message: 'OK', type: 'success' })
            } else {
              _this.$notify({ title: 'Response', message: 'Gagal', type: 'danger' })
            }
            _this.getusers()
          }
        })
    }
  }
}
</script>

<style>
.users { margin: 20px };
.btnappend { margin: 20px};
.btnauth { margin: 10px };
</style>

**Comment by paulgv** [comment]
I was thinking of a repo with your whole Nuxt app (stripped out of any sensitive information).

**Comment by teddysasmita** [comment]
I still have not figured how to do that with jsfiddle. Please advice.

**Comment by paulgv** [comment]
Create a repo here on GitHub and push your code into it, then share the link here :)

**Comment by teddysasmita** [comment]
Sorry for the delay. This is the link.
https://github.com/teddysasmita/kff-web-repo.git
I hope it works

**Comment by paulgv** [comment]
Hi @teddysasmita 
This is really strange, it looks like Nuxt is trying to render your app server-side, even though you set the mode to SPA in `nuxt.config.js`. This causes the tabs rendering to crash in your `users` page.
For a quick fix, I'd recommend you wrap your tabs in a `<no-ssr>` tag:

```vue
<!-- users.vue -->

<el-col :span="16">
  <h3>{{ detiltitle }}</h3>
  <no-ssr>
    <el-tabs v-model="maintab" type="border-card" @tab-click="tabclick">
      <!-- Tabs content -->
    </el-tabs>
  </no-ssr>
</el-col>
```

But I'm sure you shouldn't have to do this if you're using SPA mode, I'd be curious to know what's really going on here but I've never used Nuxt in SPA mode before.

**Comment by teddysasmita** [comment]
Yes, It works. Thanks so much for your help, Paul. I hope the nuxt-js team will improve their framework.

**Comment by teddysasmita** [comment]
Yes, the problem is indeed in element-ui tab.
