### ISSUE TITLE
Uncaught TypeError: window.Vue.use is not a function

### ISSUE THREAD

**Issue by loveyoo** [nuxt/nuxt.js#1906]
Hi, @cj @VictorTolbert @johnlindquist @sirlancelot @xdamman  

我通过 `nuxt generate` 命令行把生成的静态文件部署到 `github` 上后，浏览器控制台报了如下错误：
```bash
Uncaught TypeError: window.Vue.use is not a function
```
```bash
Uncaught TypeError: Vue.use is not a function
```

这是网站链接，可以打开浏览器控制台看下： https://loveyoo.github.io
其中有道了路由器，不知道是不是跟这有关系！？

在线等~

**Comment by clarkdo** [comment]
Can you have a try on 1.0.0 ?
