### ISSUE TITLE
layout not exec when refresh current page 

### ISSUE THREAD

**Issue by yyyuuu777** [nuxt/nuxt.js#1908]
I want dynamic change my theme when user select theme, i put theme value to localStorage,this is my code, 
```
  layout (context) {
    if (context.isClient) {
      // return context.app.store.state.theme.theme.current === '0' ? '' : 'dark'
      return localStorage.getItem('theme')
    }
  }
```
but, when i refresh current page, the layout method not run

**Comment by homerjam** [comment]
I don't believe `layout` accepts a function, you could try passing a string instead (or a ternary expression).

**Comment by jvukovich** [comment]
This may be related to the issue I just posted: https://github.com/nuxt/nuxt.js/issues/1929

**Comment by KonstantinVlasov** [comment]
localStorage not available on the server, I don't think that it's recalculated on the browser after refresh, in that case, you will always get default layout

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/issues/2192#issuecomment-346300135
