### ISSUE TITLE
Express req.query dont' work with ServerMiddleware

### ISSUE THREAD

**Issue by nidble** [nuxt/nuxt.js#1909]
Hi all,

thanks for this awesome project.

I choosed example-auth as basic template for my project. But, when I add another get route into ~/api/index.js, _req.query_ is always _undefined_

the step to reproduce this issue is very easy, just to add into ~/api/index.js something like this after post routes:
`router.get('/test', (req, res) => {
  console.log(req.query);
  res.json({})
})`

Any help would be appreciated,
cheers

**Comment by lyzs90** [comment]
ran into the same issue. i had to parse the query string manually:

```javascript
const url = require('url')
req.query = url.parse(req.url, true).query
```

anyone found the cause or a better workaround?

**Comment by clarkdo** [comment]
@lyzs90 is correct.

`req` is the Node.js http request object, so it doesn't have `query` property.
