### ISSUE TITLE
default layout in config

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#191]
both through nuxt.config set the default template?

example
```javascript
// nuxt.config.js
module.exports = {
  defaultLayout: `my_layout` // used file my_layout.vue
}
```

**Comment by alexchopin** [comment]
You have chosen convention over configuration, and in this case you define the default layout by simply creating a `layouts/default.vue` file.

**Comment by wormen** [comment]
I did not mean it
it was about how to have a system in multiple templates, and easily configured to specify which one to use by default

**Comment by mayognaise** [comment]
@alexchopin I'd like to have the default setup depends on environment so would be great if we have option for this 🙏
