### ISSUE TITLE
Loading child page directly in the browser

### ISSUE THREAD

**Issue by lsbyerley** [nuxt/nuxt.js#1915]
Whenever I hit the index page and navigate to child page components using the nav, they work fine. However, if I hit the url to a page directly (such as localhost:8000/repos) in the browser i get a `NuxtServerError` with a very limited stack trace. Anyone know why? Image of error is attached

<img width="1486" alt="screen shot 2017-10-20 at 4 07 16 pm" src="https://user-images.githubusercontent.com/3066258/31839878-ffc433a4-b5b0-11e7-877b-61be4fc4c865.png">

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1712">#c1712</a>)</em></sub></div>

**Comment by lsbyerley** [comment]
The api endpoint i'm on this page component is hitting a local express api running the nuxt application.

**Comment by galvez** [comment]
@lsbyerley This seems to be an Axios configuration issue. Please look into `nuxt-axios`. Closing as there's been no updates over 90 days.
