### ISSUE TITLE
Proposal: Add Webpack dashboard to dev server

### ISSUE THREAD

**Issue by gensmann** [nuxt/nuxt.js#1918]
adding:

https://github.com/FormidableLabs/webpack-dashboard
https://github.com/FormidableLabs/electron-webpack-dashboard

would be a nice touch to the dev experience in nuxt.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1714">#c1714</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @gensmann 

Thank you for your proposal, it seems really nice, but there is one thing I'm not super happy about, it's the dependencies hat will stack to Nuxt.js: https://github.com/FormidableLabs/webpack-dashboard/blob/master/package.json#L33-L50

Instead, making it a Nuxt.js module 🚀 , like https://github.com/nuxt-community/webpackmonitor-module

Anyone up to make it is more than welcome :)

**Comment by gensmann** [comment]
Good point. I agree. Unfortunately I'm not enough of a wiz to be able to take on the task, but I remain hopefull someone is :-)

**Comment by paulgv** [comment]
@Atinux @gensmann here's my attempt at creating a module for this: https://github.com/paulgv/nuxt-webpackdashboard
Hope it's done properly.

**Comment by mootari** [comment]
@paulgv You might want to add it to https://github.com/nuxt-community/awesome-nuxt for additional exposure.
