### ISSUE TITLE
Build client-only bundle

### ISSUE THREAD

**Issue by ndarilek** [nuxt/nuxt.js#192]
Not sure if this is supported. I'd like to use Nuxt to replace a somewhat complicated Vue/Webpack setup to generate JavaScript assets for a Phoenix app. As such, I don't want SSR at all. I just want the nice convention over configuration.

Is there any way to do this currently? Static generation isn't quite what I want, because my app is still dynamic. I just don't want to use Nuxt as my server.

Thanks.

**Comment by Atinux** [comment]
Hi @ndarilek 

To be sure to understand, you would like to generate the pages but without server-render them or be able to design vue.js application like nuxt.js without SSR?

**Comment by ndarilek** [comment]
Exactly, thanks. This library has nice conventions, and if I can replace 
my existing router/store/plugin setup with it, I could eliminate lots of 
boilerplate with my Phoenix app.

**Comment by ammichael** [comment]
This seems related to #168. I'm also needing this kind of build.

@Atinux I really don't mean to rush you, just trying to get the picture of how complicated could this be, and if you guys are planning to implement anytime soon. If so, hopefully, I'll keep developing in Nuxt, or I'll need to migrate to Quasar, even though I find conventions Nuxt way better.

**Comment by Atinux** [comment]
I don't think how hard it will be, I don't think so, I'm going to work on it next week.

I'll keep the thread updated.

**Comment by ammichael** [comment]
That is awesome! Nice!

Thanks

**Comment by ndarilek** [comment]
Agreed, thanks a bunch!

**Comment by dohomi** [comment]
@Atinux I would also highly vote for this. Any chance of addressing in an earlier release? I'm using couple of `not-yet-reasy-SSR` modules and the developer experience at the moment is around -10 because of constant re-starting of the server. Thanks for your effort!

**Comment by wushan** [comment]
this will be really useful but i am thinking about when this bundle isn't  ssr, we are not able to use something like nuxtServerInit in the project right? or maybe the function will acted like the very first hook when loading the app.

**Comment by ndarilek** [comment]
I'd say that, if you're building a client-only bundle, you shouldn't be 
using server-side functions anyway. So just ignore them.

**Comment by Atinux** [comment]
I am thinking of adding a ˋnuxtClientInit` which would run only when server side rendering is disabled. Useful for fetching some state in the localStorage.

Indeed, like @ndarilek said, you should ignore server side properties when building an app which works only for SSR.

**Comment by Atinux** [comment]
It's now linked to #240
