### ISSUE TITLE
When do you update NPM package

### ISSUE THREAD

**Issue by aokihu** [nuxt/nuxt.js#1921]
Hi, I want to know when do you plan to update NPM package, VUE version is 2.5, so now it is not work well at old version nuxt

**Comment by yoyo837** [comment]
The last release was 46 days ago, and I was concerned about the release version almost every day.

**Comment by manico** [comment]
Some plugins do not work will lower version.
Do you know when will nuxt update to vue 2.5?

**Comment by bjunc** [comment]
I'm also curious about this.  It's now 4 months since the last release.  Really need better communication regarding releases.  The project roadmap just doesn't cut it.

**Comment by yoyo837** [comment]
@manico You may consider using `yarn ` `resolutions ` to upgrade vue

**Comment by pi0** [comment]
https://github.com/nuxt/nuxt.js/issues/2142#issuecomment-347193288
