### ISSUE TITLE
How to add code to head tag and </body> tag

### ISSUE THREAD

**Issue by manhlinhit** [nuxt/nuxt.js#1922]
How to add 3rd party code to <head> </ head>
Example: I want to add
`<meta name = "google-site-verification" content = "4fT_kMaVPLksW6_bkW9-9XPZ1ImvUcLkvbJ7xxxx_yyy" />`

**Comment by KonstantinVlasov** [comment]
You can find info in the [docs](https://nuxtjs.org/guide/views), obviously :)

**Comment by manhlinhit** [comment]
I found head method and i used it for SEO tag with content user create.
Link: [https://nuxtjs.org/api/pages-head/#the-head-method](https://nuxtjs.org/api/pages-head/#the-head-method)
But code 3rd party is html code or javascript code, example: 
`<meta name = "google-site-verification" content = "4fT_kMaVPLksW6_bkW9-9XPZ1ImvUcLkvbJ7xxxx_yyy" />`
I get via api. Reading the head method I did not find the code to print raw html and javascript code

**Comment by KonstantinVlasov** [comment]
As described in the docs, your code will look like: 
```javascript
meta: [
  { name: 'google-site-verification', content: '4fT_kMaVPLksW6_bkW9-9XPZ1ImvUcLkvbJ7xxxx_yyy' }
]
```
> To know the list of options you can give to `head`, take a look at [vue-meta documentation](https://github.com/declandewet/vue-meta#recognized-metainfo-properties)

**Comment by manhlinhit** [comment]
This code is dynamic code, html or javascript code, 
example: Google Analytics, Pixel Facebook .
It has no fixed structure.
I need print raw code get from api

**Comment by KonstantinVlasov** [comment]
I don't think it's possible. Maybe you can somehow update your API and get more info about what type of data you need to include. If it's html, then you can include it via v-html. If it's js, then you can include it via vue-meta script option.

**Comment by pauldariye** [comment]
@manhlinhit, you should be able to grab the data you need from the api using `asyncData` method and then update the head with the api value. 
like so

```
<template>  
    <div> </div>
    ....
</template>

<script>
    export default {
          head () {
            return {
                meta: [  { name: this.data.metaData.name, content: this.data.metaData.content } ]
            }
          }
          async asyncData() {
               const metaData = await my.api.fetch()
               return { metaData }
         }
    }
</script>

...

```

where do you need to print the raw code?
