### ISSUE TITLE
Deploying to AWS (serverless)

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1926]
I tried to search around but did not successfully find a AWS serverless solution for Nuxt SSR. Is there something i have missed or is this not currently support?

**Comment by phlogisticfugu** [comment]
I made this: https://github.com/phlogisticfugu/perfect-paca a while ago.

Waiting for Nuxt 1.0 to update it, and use the new vue-cli

**Comment by maziarz** [comment]
@phlogisticfugu very interesting.. Would it make more sense to spin something up with Claudia.JS?

**Comment by phlogisticfugu** [comment]
perfect-paca uses https://serverless.com/ actually, which does what claudia.js does, but supports more clouds.  Give it a try and I'm open to suggestions/PRs

**Comment by srmcguirt** [comment]
@phlogisticfugu that looks like a better solution. I'm comparing that with the AWS codestar pipeline this week and will try to give feedback.

**Comment by PhilAndrew** [comment]
Hi, what is the status of this?
It would be very useful to me if I can deploy to AWS lambda and also cache pages on S3 or some other cache for frequently accessed pages.
Are there any other solutions for this?

**Comment by maziarz** [comment]
I basically ended up using a pre-rendering solution with my nuxt project. But perfect-paca looks like a good solution.

**Comment by PhilAndrew** [comment]
Ok I'm starting to use perfect-paca, are there any other alternatives? well I'm go ahead with this and report back how it goes.

**Comment by PhilAndrew** [comment]
https://github.com/phlogisticfugu/perfect-paca/issues/3

**Comment by maziarz** [comment]
@PhilAndrew, any luck?

**Comment by apertureless** [comment]
You could use [up](https://github.com/apex/up) they have also [examples](https://github.com/apex/up-examples/tree/master/oss/node-nuxt) for nuxt.

**Comment by phlogisticfugu** [comment]
Re: @maziarz 
Note that the issue that @PhilAndrew had with perfect-paca was resolved by himself. 

Also, will be updating perfect-paca with nuxt.js 1.0 which just came out a few days ago

**Comment by acidjazz** [comment]
a little late to the game @maziarz but if you don't have dynamic routes and want to go the route of s3+CloudFront I built a tool that auto-deploys Nuxt projects and easily plugs into Circle CI

https://github.com/acidjazz/aeonian

**Comment by maziarz** [comment]
I am still looking for a working example utilising Express or Koa running on AWS Lambda / ApiG without serverless-framework, but merely CloudFormation/SAM. If anyone is up for creating such a sample project, please ping me :-)
