### ISSUE TITLE
meta data for social media not working in SPA

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1928]
I have finished writing my application, but i am running into problems with meta data for social media sharing. Since all my page data is asynchroniously loaded via JSON file, Facebook has a hard time loaded that information. Is my only option to go the SSR way rather than a classic SPA? 

I have attached a typical way that i update the meta data:

```
  async asyncData (context) {
    let { data } = await axios.get('/data/about.json')
    return { content: data }
  },
  head () {
    return initMetaData(this.content.seoMetaTags)
  }
```

The function `initMetaData` basically returns the meta information which is loaded.

**Comment by alexchopin** [comment]
Hi @maziarz, 
Unfortunately, the only solution is to work with SSR or the generate option in your case.

**Comment by maziarz** [comment]
@alexchopin we went forward with prerendering. Also i can confirm that nuxt.js works perfectly with https://www.prerender.cloud/ 

ATT: I am not affiliated in any way :-)

**Comment by stursby** [comment]
@maziarz I was able to find a solution using Nuxt hooks.

```js
// nuxt.config.js

const { meta } = require('./helpers/meta')

...

  // Hooks
  hooks: {
    'generate:page': page => {
      page.html = meta(page)
    }
  },

...
```

Then using [cheerio](https://github.com/cheeriojs/cheerio) I was able to inject meta tags into the head!

```
// /helpers/meta.js

const cheerio = require('cheerio')

function metaMarkup({ name, description, image, url }) {
  return `
    <meta property="og:type" content="website">
    <meta property="og:title" content="${name}">
    <meta property="og:description" content="${description}">
    <meta property="og:url" content="${url}">
    <meta property="og:image" content="${image}">
    <meta itemprop="name" content="${name}">
    <meta itemprop="description" content="${description}">
    <meta itemprop="url" content="${url}">
    <meta itemprop="image" content="${image}">
  `
}

function meta({ route, html }) {

  // meta tags (fill in your info here / dynamic per route)
  const metaTags = {
    name: '',
    description: '',
    image: '',
    url: ''
  }

  // Load Nuxt generared HTML
  const $ = cheerio.load(html)

  // Generate meta markup
  const tags = metaMarkup(metaTags)

  // Append them to <head>
  $('head').append(tags)

  // Return new HTML
  return $.html()

}

exports.meta = meta

```

Then in /dist, your HTML files should now have meta in the <head>!

![image](https://user-images.githubusercontent.com/527849/36614903-df526662-18a3-11e8-8a64-1af97f361da6.png)

**Comment by maziarz** [comment]
@stursby super interesting approach, might refactor at some point.
