### ISSUE TITLE
Layout not loaded when page accessed directly

### ISSUE THREAD

**Issue by jvukovich** [nuxt/nuxt.js#1929]
I am using Vue 2.4.4 and Nuxt 1.0.0-rc11 in hash and spa mode.

When I try to load a page directly:
http://localhost:3000/Gui/#/hud

My custom layout is not loaded. It always loads the default layout.

```
export default {
  name: 'asc-hud',
  layout: 'hud-layout',
  ...
}
```

If I go to the root, to allow the app to load first:
http://localhost:3000/Gui/#/

And then go to my page:
http://localhost:3000/Gui/#/hud

The correct layout is loaded.

If I refresh the browser while on my page, it reloads the app and uses the default layout instead of my custom layout.

Seems like a bug.

It's pretty straight forward, but I can provide more code and/or screenshots if necessary. Just let me know.

In the meantime, I've created a workaround by creating a dynamic route:
http://localhost:3000/Gui/#/load/hud

And redirecting to the correct page from there. Then the app is loaded before the page is opened and the correct layout is used. Would rather not have to do this, though.

Thanks!

**Comment by Atinux** [comment]
Will be fixed in next release, sorry about this.

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1929](https://trello.com/c/rKhXjizf/39-1929)

**Comment by jvukovich** [comment]
Awesome, thanks so much! <3
