### ISSUE TITLE
nuxtServerInit just modify state in the same file

### ISSUE THREAD

**Issue by BRKsDeadPool** [nuxt/nuxt.js#193]
I was trying to create a module "auth" separate from the main module "index.js", but when I try to modify the state of the module "auth" through the action nuxtServerInit simply does not work.

My index.js file

```javascript
export default {
  actions: {
    nuxtServerInit({commit}, {req}) {
      if (req.auth) {
        commit('auth/SET_USER', req.auth)
      }
    }
  },
}
```

My auth.js file

```javascript
export default {
  state: {
    user: null
  },
  mutations: {
    SET_USER({user}, payload) {
      user = payload
    }
  }
}
```

When I try to modify a state within the index.js file it works normally

### example
```javascript
export default {
  state: {
    ping: null
  },
  mutations: {
    SET_PING(state, payload) {
      state.ping = payload
    }
  },
  actions: {
    nuxtServerInit({commit}, {req}) {
      commit('SET_PING', 'PONG')
    }
  },
}
```

**Comment by Atinux** [comment]
@BRKsDeadPool you need to keep the reference of the `state` inside your `SET_USER` mutation so Vue knows that you change the `user` key of the state.

Here your `auth.js` file fixed:
```js
export default {
  state: {
    user: null
  },
  mutations: {
    SET_USER (state, payload) {
      state.user = payload
    }
  }
}
```
