### ISSUE TITLE
Problems with fetch when running shopify-buy sdk in SSR environment

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1930]
I have setup shopify-buy as a plugin in my project running with the `ssr: false` flag. Unfortunately i am still running into the problem that the server is complaining about missing fetch function.

After a bit of digging i can see that fetch is utilized from [`graphql-js-client`](https://github.com/Shopify/graphql-js-client/blob/master/src/http-fetcher.js) in [`shopify-buy`](https://github.com/Shopify/js-buy-sdk/tree/v1.0alpha), but what i do not understand is that when i switch off `ssr` why is the plugin still missing fetch? When i turn nuxt into `spa` mode it is working smoothly.

`nuxt.config.js`

```
plugins: [
    {src: '~/plugins/shopify-buy', ssr: false},
],
build: {
    vendor: [
        'shopify-buy'
    ]
}
```

`plugins/shopify-buy.js` 

```
import Client, {Config} from 'shopify-buy'

const shopifyConfig = new Config({
  domain: 'removed.com',
  storefrontAccessToken: 'hidden'
})

export const shopifyClient = new Client(shopifyConfig)
```

<img width="1597" alt="skaermbillede 2017-10-23 kl 08 43 52" src="https://user-images.githubusercontent.com/15786116/31876112-5f885212-b7d1-11e7-8f87-1d7ec4a0a278.png">

**Comment by Gomah** [comment]
Where are you referencing the shopify client?

This works for me:

Using `shopify-buy` 1.0.0-beta.3:

```js
// nuxt.config.js
plugins: [
    { src: '~/plugins/shopify-buy', ssr: false },
],
build: {
    vendor: [
        'shopify-buy'
    ]
}
```

```js
// plugins/shopify-buy.js
import Client from 'shopify-buy';

const config = {
  domain: process.env.STORE_FRONT_DOMAIN,
  storefrontAccessToken: process.env.STORE_FRONT_ACCESS_TOKEN,
};

export default (context, inject) => {
  inject('shopify', Client.buildClient(config));
};
```
