### ISSUE TITLE
Using Django Sessions in Nuxtjs

### ISSUE THREAD

**Issue by Mohsunbagheri** [nuxt/nuxt.js#1931]
Can I use sessions created by django to keep user authenticated in nuxtjs ? how ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1724">#c1724</a>)</em></sub></div>

**Comment by vuchl** [comment]
There are a few django related issues here. Try if you can find something that may give you a hint: https://github.com/nuxt/nuxt.js/search?q=django&type=Issues&utf8=%E2%9C%93

**Comment by kamirt** [comment]
The basic mechanism of sessions is to keep one session key at backend and frontend together. So, I usually use cookies for keeping this key generated by Django. 
You can use, for example, [vue-cookies](https://www.npmjs.com/package/vue-cookies) library to keep it at your frontend.
After setup of this library you can make authorization page. When user is logged in, you do something like this: 
1) this.$cookies.set("user_session","[backend-generated-session-key]")
2) then you need to set up your api queries to send Autorization header with this.$cookies.get('user_session') (read [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) for better understanding)
3) don't forget that Django use csrf protection. It works the same way.

You also can use django rest framework to set up token authentication for REST application.

**Comment by kamirt** [comment]
First of all, you should figure out of what you aim with using nuxt. Nuxt is a framework which allow us to prerender pages for search crawlers at first place. And for doing static pages for simple hosting. 
If you want to show page for google or another crawler, I think you understand that it never login in you application. So, it seems like bad decision for that purpose.
But if you want to use nuxt for "simple hosting", just create a first-root-route index page with your logo or event with nothing. And there you can use something like [vue-cookie](https://www.npmjs.com/package/vue-cookie) to make the first request to your server for checking out authorization or just for checking the cookie. This page will be rendered for a second (if your backend server isn't slow). Then you can load another view with route "/home" for example.

**Comment by danjac** [comment]
It depends on what you want to do but typical usage might be to use Django Rest Framework for your API with Nuxt as frontend (or one of several frontends, e.g. a mobile or desktop app). In this case, Nuxt is using SSR mode - it functions as its own site, proxying all your API calls to Django (and perhaps other backend APIs as well).

In this case, DRF might use token authentication for all frontends. You can use the default DRF rest token auth, or JWT or knox for example. 

The basic idea is this:

1. We have a node server app that wraps Nuxt (auth-module isn't really suitable for production use as it stores the token in localStorage or a client-side cookie and thus is vulnerable to XSS attacks). 
2. The user logs in on your Nuxt site. We have an endpoint on the node app that proxies the authentication call to Django. Assuming valid creds, Django/DRF returns our authentication token. 
3. The token is stored by the node app using express-session in a server-side Http-only cookie. At no point do we expose the token to the client. We can use Redis or some other storage for the session.
4. All API calls are sent to the node app, which proxies these calls to Django - i.e. all /api/* calls. This is handled using proxy middleware. We can check for the token in the session and add it to the header passed to the Django API if present.
5. The node app also handles CSRF checks using csurf. DRF doesn't need to worry about this.
6. A logout endpoint notifies Django to destroy the token, and removes the token from the session.

I have set up a very simple Nuxt application to illustrate this: https://github.com/danjac/nuxt-python-secure-example/blob/master/frontend/server.js. This uses a very simple Flask backend but the principle is the same - in fact this technique could be used with any backend API that uses token authentication.

**Comment by galvez** [comment]
This question has been answered (quite thoroughly I might add) by @danjac (thanks!).
