### ISSUE TITLE
Missing requirements from the Vuex Store docs?

### ISSUE THREAD

**Issue by smth** [nuxt/nuxt.js#1933]
I just followed the instructions to [Activate the Store](https://nuxtjs.org/guide/vuex-store), and it is not working for me. `{{ $store.state.counter }}` returns empty and `@click="$store.commit('increment')"` returns the error "*unknown mutation type: increment*". Is there a minimum Nuxt version for this to work (I'm using 0.10.7). If not, what am I missing?

To be clear, the steps I have taken are to:
1. Create `store/index.js`
2. Add the example template code

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1725">#c1725</a>)</em></sub></div>

**Comment by alexchopin** [comment]
Hi @smth,
Can you post your `store/nidex.js` file, please?
