### ISSUE TITLE
How to get access to vuex/vue-router in plugins js-files

### ISSUE THREAD

**Issue by Alex-Sokolov** [nuxt/nuxt.js#1934]
Have file for custom instance of axios in `~/plugins/axios.js`
How to get access to store or router inside this file?
For example for correct handling 401-error and redirecting user to login-page with `router.push` of commiting mutation to store, which redirect user

P.S.: Nuxt 1.0.0-RC11

**Comment by cretueusebiu** [comment]
The plugin can be export a function that takes the [context](https://nuxtjs.org/api/context#context) as an argument.  See the [plugins](https://nuxtjs.org/guide/plugins#inject-in-root-amp-context) section.

```javascript
// ~/plugins/axios.js
export default ({ store, redirect }) => {
  
}
```

**Comment by tobz-nz** [comment]
I'm trying to do this as well - use the store in axios plugin. Tried the solution above but get the error:
` Cannot read property 'store' of undefined `

Any help?

**Comment by HeyMrLi** [comment]
Thank you for your reply @tobz-nz
