### ISSUE TITLE
Server won't run/compile/display

### ISSUE THREAD

**Issue by johnlindquist** [nuxt/nuxt.js#194]
I'm guessing some dependency updated that broke something....

Just today, I've tried `nuxt/starter`, `nuxt/express`, and creating a project from scratch, but all of them get stuck when trying to serve:
`yarn run dev`
```
nuxt
  nuxt:build App root: C:\Users\John Lindquist\projects\nuxt-scratch +0
ms
  nuxt:build Generating .nuxt/ files... +2ms
  nuxt:build Generating routes... +13ms
  nuxt:build Generating files... +7ms
  nuxt:build Adding webpack middlewares... +49ms
Ready on http://localhost:3000
```

But when I open the browser, nothing loads. Webpack never starts/compiles...

I have no idea what's happening... Everything worked just yesterday.

**Comment by johnlindquist** [comment]
Looks like the problem was
`webpack-dev-middleware@1.10.0`
I downgraded to 
`webpack-dev-middleware@1.9.0`
and the problem went away...

**Comment by alexchopin** [comment]
Thanks for the report 👍

**Comment by Atinux** [comment]
I upgraded to `webpack-dev-middleware@1.10.0` and it works fine.

I've seen your Twitter message, it seems that it could have a like with the `acorn` update.
