### ISSUE TITLE
Problem with generate and dynamic params?

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt/nuxt.js#1940]
I want to static generate my dynamic route so there won't be api requests on the deployed site. However I seem to be doing something wrong since my asyncData method is always skipping to the "else" condition.

In my nuxt.config.js
```
const axios = require('axios')

module.exports = {
  generate: {
    routes: function () {
      return axios.get('http://exmaple.com/api/cases')
      .then((res) => {
        return res.data.objects.map((content) => {
          return {
            route: '/case/' + content.slug,
            payload: content
          }
        })
      })
    }
  }
}
```

And in my dynamic page/route component
```
export default {
  async asyncData ({ params, error, payload }) {
    if (payload) return { content: payload }
    else return {
      content: 'something else'
    }
  }
}
```

It is always skipping to "something else", both before and after nuxt generate has been completed. 
From my understanding, the else return should be returned during dev "npm run dev", else the payload from routes generate should be returned?

EDIT: is it possible to generate a 100% static site and decouple the API?

**Comment by ejulen** [comment]
@jesperlandberg did you solve this? I'm having the same issue, I think. See #2149 also.

**Comment by msgeissler** [comment]
I am having this problem as well.
Since you closed the issue @jesperlandberg, have you been able to get this to work?

**Comment by qm3ster** [comment]
`payload` is only provided to the serverside `asyncData` execution during the `nuxt generate`. It is not provided on client loads.
If you want to package static data with your distribution, you can generate json see https://github.com/qm3ster/linnertmedia for a basic example that also uses payload to speed up generation and doesn't require the `static` folder to run a server during generation.

For further explanation see #2149
