### ISSUE TITLE
Handling Lazy Loading Routes when offline

### ISSUE THREAD

**Issue by ryaposov** [nuxt/nuxt.js#1941]
As Lazy Loading Routes is a part of Nuxtjs and is enabled by default, my questions are: 
1. How can we handle app behavior when app is no longer online and trying to navigate to route that is not loaded yet? By default I see "Loading chunk %n failed." error. What approaches are possible here show user message about offline status etc?
2. Is it possible to disable splitting app.js build on pages for production? That could be usefull for small apps that doesn't need this.

Thanks for help!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1733">#c1733</a>)</em></sub></div>

**Comment by Coletrane** [comment]
I would also like to know if this is possible. My previous config before switching to Nuxt didn't use code splitting since my routes were < 10k each. I believe this is causing my server rendered page to get out of sync with my client rendered one.

**Comment by manniL** [comment]
You could use `prerendering`/`prefetching` together with an PWA to cache other routes after main route has been loaded, so they can be used offline :relaxed:
