### ISSUE TITLE
Using Facebook's javascript sdk with Nuxtjs

### ISSUE THREAD

**Issue by Benjamin5050** [nuxt/nuxt.js#1945]
I would like to use [Facebook's comments plugin](https://developers.facebook.com/docs/plugins/comments) on some routes/paths of my website. I am using Vuejs and Nuxtjs for server-side rendering. I have gone through the Nuxtjs website to [include plugins](https://nuxtjs.org/guide/plugins), but I couldn't find any help there. I have gone through these ([1](https://stackoverflow.com/questions/43665115/i-use-nuxtvue-js-how-to-use-facebook-sdk), [2](https://stackoverflow.com/questions/43698260/how-to-use-global-javascript-in-nuxt-fb-sdk-use-in-mounted)) SO questions as well, but they didn't help me either. Could you please guide me how to use Facebook's SDK when using Nuxtjs I will be very much grateful.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1736">#c1736</a>)</em></sub></div>

**Comment by manhlinhit** [comment]
I have the same problem

**Comment by hanjeahwan** [comment]
i am using nuxt with spa mode , dont have any issue
![image](https://user-images.githubusercontent.com/21311478/32698567-d27de298-c7e2-11e7-91f4-c51a7f780bae.png)

**Comment by awronski** [comment]
@hanjeahwan Could you share your code how you configured fb jdk with nuxt?

**Comment by hanjeahwan** [comment]
I don't know whether it is a proper solution or not and i am new in Nuxtjs, you can correct me if i'm mistaken.
What i do is include the script _https://connect.facebook.net/en_US/all.js_ in nuxt config and create a js file in plugins folder, like below
![image](https://user-images.githubusercontent.com/21311478/32699030-0f41c8dc-c7ea-11e7-8a22-92b77b9e081d.png)
and initialize the SDK with `this.$initFbSDK()` in created hook.

**Comment by StephaneP** [comment]
@hanjeahwan  excellent this is exactly what I was looking for

**Comment by InstanceOfMichael** [comment]
Does that solution load the facebook SDK always or only when it's needed? Here is a solution that loads it on demand only when needed (e.g. when the user looks at that specific page that uses it, and also assumes your module-loading/code-splitting is correct). My apologies though, the example is for the Stripe SDK.

https://github.com/webpack/webpack/issues/150#issuecomment-275952354

**Comment by samirph** [comment]
Whenever I try to create that plugin like the one mentioned here, I keep getting the message `'FB' is not defined` from my ESLint.

**Comment by limpehsh** [comment]
@samirph In your .js file, you can add `/*global FB*/` at the top. Or simply call it `window.FB` as opposed to `FB`
- [Same question on stackoverflow but for create-react-app](https://stackoverflow.com/questions/40466492/how-to-fix-error-fb-is-not-defined-no-undef-on-create-react-app-project)
- [ESLint Rules - Disallow Undeclared Variables (no-undef)](https://eslint.org/docs/rules/no-undef)

**Comment by galvez** [comment]
Closing this issue as there's been no updates over 90 days.
