### ISSUE TITLE
Nuxt plugin is called 16 times ? (I wanna do X stuff on each page load Client Side)

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt/nuxt.js#1946]
Hello, 

I was developing my first plugin that is noty wrapper.

But i noticed that my mixing are called 16 times ? 

So i created a test plugin.

```
import Vue from 'vue'

const Test = {
  install: (Vue, options) => {
    Vue.mixin({
      mounted () {
        console.log('called');
      }
    })
  }
}

Vue.use(Test)
```

I got `called` 16 times + 1into my console. (chrome)

what could cause this ?

**Comment by paulgv** [comment]
Since your mixin is global, all your components get the `mounted` hook.
If you only want to use the mixin in specific components, you shouldn't use `Vue.mixin` but rather the basic method explained here: https://vuejs.org/v2/guide/mixins.html#Basics

**Comment by alanaasmaa** [comment]
Hmm.. how about using router afterEach or somehting ?

**Comment by paulgv** [comment]
It all depends on what you're trying to achieve really. If what you want is perform an action when the user navigates to a page, you might want to use middlewares: https://nuxtjs.org/guide/routing#middleware

**Comment by alanaasmaa** [comment]
@paulgv This way i got it working but only on client side. The middleware is indeed called also in server side.

Im trying to show notifications using noty.

**Comment by KonstantinVlasov** [comment]
you can use middleware and check if `process.browser === true`

**Comment by dohomi** [comment]
@alanaasmaa just use a middleware and do:
```
export default ({isServer}) =>{
  if(isServer) return
  // => your code
}
```

**Comment by alanaasmaa** [comment]
@KonstantinVlasov @dohomi I tryed what KonstatinVlasov reccommended allready. But first render is always server side, so this is not a solution either. 

Maybe i should try module next and inject somewhere there the logic. O

**Comment by dohomi** [comment]
@alanaasmaa sorry but I don't quite get your response. What is not a solution either? The middleware is always called before a page is rendered, every routing its called again. To guard your client side code with my code snippet is the legit way of doing it. If the server is calling the middleware it quits directly. Where do you see a problem?

Beside that you dan also use a component widget and in every page you add the mixin with your mounted hook. Then its only called once.

**Comment by alanaasmaa** [comment]
@dohomi Problem is that the first render is called server side, my code wont work on server side so it is not called at all. 

I try to use mixin again.

**Comment by alanaasmaa** [comment]
I got it working by calling my plugin function in template

```
<template>
  <div>
    <navbar/>
    <sidenav/>
    <nuxt/>
    <my-footer/>
  </div>
</template>

<script>
import MyFooter from '~/components/Footer.vue'
import Navbar from '~/components/Navbar.vue'
import Sidenav from '~/components/Sidenav.vue'

export default {
  components: {
    Navbar,
    Sidenav,
    MyFooter
  },
  created () {
    this.$notify.showFlashed(this)
  }
}
</script>
```
