### ISSUE TITLE
import node-modules scss that imports yet more node-modules scss

### ISSUE THREAD

**Issue by airtonix** [nuxt/nuxt.js#1951]
fails. because they don't use `~` to prefix their imports. thus... fails.

```
@import "~sass-breakpoint";
```
```
Module build failed:
@import "sass-ems/index";
^
      File to import not found or unreadable: sass-ems/index.
... blah blah blah
```

**Comment by clarkdo** [comment]
You may add `sass-ems` folder into option `includePaths` of `sass-loader` .
```js
module.exports = {
  build: {
    extend(config) {
      const sassLoader = config.module.rules.find((rule) => rule.loader === 'sass-loader')
      sassLoader.options = Object.assign({}, rule.options, {
        includePaths: [
          "absolute/path/a", "absolute/path/b"
        ],
      })
    }
  }
}
```

**Comment by soniktrooth** [comment]
I tried this and get ` ReferenceError: rule is not defined`

Any ideas what could cause this?

**Comment by clarkdo** [comment]
Current loaders structure  has been changed, please check https://github.com/nuxt/nuxt.js/blob/faa069df4959da580646e521ea73f63b265bb4e9/examples/custom-build/nuxt.config.js
