### ISSUE TITLE
Opening page as a modal and changing route

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1953]
I have a shopping cart which is opened as a modal, but i would like to have it as a route on top of the page it is opened in. Which approach would i have to use in order to implement this? This would be the scenario:

- User has entered route `/about/`
- User clicks "Open cart" button
- Cart modal opens on top of `/about/` page, but changes route to `/cart/`
- User clicks "Close cart" button, and route goes back to `/about/`

**Comment by alexchopin** [comment]
Hi @maziarz,
Can you explain more about `Cart modal opens on top of /about/ page, but changes route to /cart/` ?

**Comment by maziarz** [comment]
@alexchopin, sorry for the confusion. So lets imagine i have a cart button in my navbar, which the user clicks on in an arbitrary page, such as `/about`. Due to the nature of analytics, i would want to change the route so it comes `/cart`, but, i would still wan't to maintain the original page in the background and open `/cart` as a modal. When you hit the "Dismiss cart" it will simply jump back to the route in the background. As far as i understand this is more of a routing hack than anything else.

**Comment by KonstantinVlasov** [comment]
I think if you need it for analytics, then you no need to change the route, just send the relevant event to GA or any other analytics service.

**Comment by maziarz** [comment]
@KonstantinVlasov, then i would have to handle the events manually, which is a bit cumbersome. I am currently using the google tag manager module, which is (not working)[https://github.com/nuxt-community/modules/issues/159] entirely as described (should push events automagically). If my gtm module did in fact work as intended, a route change should have been automatically triggered via the module and show me the change in GA.

**Comment by dmydry** [comment]
Hi guys!
I'm looking for a solution here as well. What if I need the described scenario not only for analytics but for some SEO needs (since we all use nuxt mostly for ssr) or just whole project consistent routes behaviour etc...
The request is quite simple - how to change the route but save the main (previous) view in a background and show some modal window. Will be quite useful

**Comment by KonstantinVlasov** [comment]
Guys, I think this is [vue-router](https://router.vuejs.org/en/) related question, not nuxt related.

**Comment by dmydry** [comment]
@KonstantinVlasov yeah, rightly observed. Anyway, I found a simple example here - https://forum.vuejs.org/t/vue-router-2-0-and-modals/898/2
Didn't try this but it seems like a simple and needed solution.

**Comment by sven-ra** [comment]
Did this solution work for  you?
At the moment I can't see how it could work.

Only way to have multiple views in nuxt is with <nuxt-child>. But <nuxt-child> can only be used if a page has dynamic child. 

Is there something I am missing?
