### ISSUE TITLE
How can I use the translate service by vue-i18n in store module actions?

### ISSUE THREAD

**Issue by maiconpazin** [nuxt/nuxt.js#1956]
Something like this:
```
actions: {
  nextStage ({ state, commit, dispatch }, params) {
    const text = vue.$t('message.chat.name-message-1')
  }
}
```

**Comment by clarkdo** [comment]
I think `store` is better to contain keys like `message.chat.name-message-1` and use `this.$t(...)` in `component` to compute the real values.

More info you can refer [here](https://github.com/kazupon/vue-i18n/issues/101)

**Comment by buhrmi** [comment]
This still doesn't seem to be resolved. I can't find a way to, for example, show toast notifications:


```
// inside Vuex action. doesn't work. (....t is not a function)
this.$toast.error(Vue.t('error.locked'))
```
