### ISSUE TITLE
How to define a dynamic route like product-detail-{productName}.html with regexp (for SEO)?

### ISSUE THREAD

**Issue by kkurt** [nuxt/nuxt.js#1959]
I how can we define a dynamic router (with Express+Nuxt) with regexp?
We can define router in express like this: 
```
app.get( 'REGEXP', function( req, res ) {
.....
} );
```
How can we integrate this router with nuxt?

**Comment by homerjam** [comment]
Try extending the routes https://nuxtjs.org/api/configuration-router

**Comment by kkurt** [comment]
Thank you...
