### ISSUE TITLE
Cannot install nuxt.js when it is a dependency of a dependency

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#1962]
For example, say you have two projects:
1. a base project, where nuxt.js is a dependency and where base nuxt configurations take place
2. a child project, that depends on the base project (via npm, say `"@org/base": "0.1.0"`)

Now in the child project, if you `npm install`, it will fail with:
```
ENOENT: no such file or directory, chmod '/path/to/project/node_modules/@org/base/node_modules/nuxt/bin/nuxt'
```

Ideally, the child project should be able to access the nuxt binaries, and have npm scripts like:
```
"dev": "nuxt",
"build": "nuxt build",
"generate": "nuxt generate",
```
And those built files should end up in the child project's repo, in the `.nuxt` and `dist` folders, as expected.

Thoughts?

**Comment by clarkdo** [comment]
It the `node_modules` of `@org/base` is published into `npm registry` ? If so, I think you should ignore `node_modules`.

**Comment by jaredreich** [comment]
`node_modules` are already ignored by both `.gitignore` and `.npmignore`. Also, to simplify this scenario, it doesn't have to be within an organization... the parent could be just named `example-base` and the child depends on it like `"child-base": "0.1.0"`. The same issue occurs.

This unfortunately renders nuxt unusable as a dependency when creating any sort of publishing/site-generator platform with nuxt as a dependency.

**Comment by clarkdo** [comment]
Can you provide any demo repo or jsfiddle ?

**Comment by jaredreich** [comment]
Hmm. Sorry, not really... there is no code to demonstrate. It's literally having two folders, each with a package.json. One project's name is "base" and the other is "child". The "base" project has nuxt as a dependency, and the child project has `"base": "file:../base"` as a dependency (or a version if the parent is published to npm). Then the failure occurs when the child attempts to do `npm install`. Also the `nuxt` binaries won't be available in the child project.

**Comment by pi0** [comment]
@jaredreich I think this is not a BUG with nuxt.js, but more npm/yarn behavior that it may not include dependency of dependency binaries right into `node_modules/.bin` and we can not do anything with that.You may specify the complete path to the binary as a fix. Also, another workaround would be using npx as nuxt.js fully supports it too.

BTW maybe you can rethink about your current solution. Nuxt.js in contrast to other templates and frameworks is not designed to be a part of boilerplate (Like a general blog template) but it provides a powerful extendable and Modular pattern for such use cases and reusing parts. In your case, `example-base` can be a nuxt module and the main project requires base + nuxt as dependencies.

You can read more about [nuxt modules](https://nuxtjs.org/guide/modules) and also see [nuxtent module](https://github.com/nuxt-community/nuxtent) as a good example.

Best wishes

**Comment by jaredreich** [comment]
@pi0 Thank you for the insight. I ended up finding the reason for this. Everything works great if nuxt (and node-sass + sass-loader, if using SCSS) is installed as a non-absolute version (e.g. ^0.10.7 rather than 0.10.7). Sorry to bother to everyone. Great work on nuxt so far, keep it up!
