### ISSUE TITLE
Is it possible to use fs-extra?

### ISSUE THREAD

**Issue by dinho-afsn** [nuxt/nuxt.js#1963]
Is it possible to use fs-extra?
I'm trying to use it but to no avail.
could you give me an example of how to use in nuxt?

**Comment by clarkdo** [comment]
It should work in server-side.

Could please show any demo or detailed scenario ?

**Comment by dinho-afsn** [comment]
need to create, delete folders on the server.
I'm trying to trigger an action to create the folder but I always get fs not is a function

**Comment by Atinux** [comment]
You need to wrap your `require('fs-extra')` inside `if (process.server)`:

```js
const fs = (process.server ? require('fs-extra') : null)
```

**Comment by dinho-afsn** [comment]
Tanks Atinux Worksssss!!!!
Nuxt is the Best!!!!!
