### ISSUE TITLE
how to add meta in routers?

### ISSUE THREAD

**Issue by EasonShen1989** [nuxt/nuxt.js#1964]

**Comment by clarkdo** [comment]
Any detailed information? Routers in Nuxt.js should be generated dynamically and implicitly, where do you need to add meta ?

**Comment by EasonShen1989** [comment]
set crumbs，for example
 {
            path: '/...',
            component: ...,
            meta: {
                crumbs: [{
                    name: '...',
                }]
            }
} @clarkdo

**Comment by clarkdo** [comment]
Every component in `pages` is route, you can define meta inside the component.
```js
  head () {
    return {
      title: this.title,
      meta: [
        { hid: 'description', name: 'description', content: 'My custom description' }
      ]
    }
  }
```
Refer [Pages Head](https://nuxtjs.org/api/pages-head)

**Comment by zhouyu1993** [comment]
vue-meta

**Comment by Atinux** [comment]
Duplicate of https://github.com/nuxt/nuxt.js/issues/1687#issuecomment-331870619

**Comment by iamdubx** [comment]
Dynamic meta tags doesn't work properly in Nuxt. This is huge issue.
