### ISSUE TITLE
npm run dev error in Ubuntu 17.10

### ISSUE THREAD

**Issue by teddysasmita** [nuxt/nuxt.js#1966]
I execute npm run dev and this is the contain of the error log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@5.5.1
3 info using node@v8.8.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle testnux2@1.0.0~predev: testnux2@1.0.0
6 info lifecycle testnux2@1.0.0~dev: testnux2@1.0.0
7 verbose lifecycle testnux2@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle testnux2@1.0.0~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/teddys/web-projects/testnux2/node_modules/.bin:/home/teddys/android-sdk/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle testnux2@1.0.0~dev: CWD: /home/teddys/web-projects/testnux2
10 silly lifecycle testnux2@1.0.0~dev: Args: [ '-c', 'nuxt' ]
11 silly lifecycle testnux2@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle testnux2@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: testnux2@1.0.0 dev: `nuxt`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid testnux2@1.0.0
15 verbose cwd /home/teddys/web-projects/testnux2
16 verbose Linux 4.13.0-16-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v8.8.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error testnux2@1.0.0 dev: `nuxt`
22 error Exit status 1
23 error Failed at the testnux2@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Please help.

**Comment by teddysasmita** [comment]
I restart the terminal and now it works

**Comment by mesqueeb** [comment]
@teddysasmita 
Thanks I had the same issue. Restarting the terminal and vscode solved it!
