### ISSUE TITLE
How to implement Auth0?

### ISSUE THREAD

**Issue by nucamoz** [nuxt/nuxt.js#197]
I can't figure it out how to implement Auth0? Without messing with .nuxt folder. May be some tips, please? There is already a bunch of working examples with next.js + Auth0, but still no nuxt.js

Can I edit .nuxt folder? Why there is literally NO INFO about that folder in folder structure section in documentation?

**Comment by Atinux** [comment]
@nucamoz you cannot edit the `.nuxt` folder since this folder is generated by nuxt.js on every build. It's exactly like the `.next` folder for next.js.

Do you mind sharing an example with next.js so I can take a look at it and reproduce it with nuxt.js?

**Comment by nucamoz** [comment]
Yes, of course - https://github.com/luisrudge/next.js-auth0

**Comment by Atinux** [comment]
@nucamoz please check https://github.com/nuxt/example-auth0

Demo: https://auth0.nuxtjs.org/

**Comment by nucamoz** [comment]
Wow, great! But demo page broken.
