### ISSUE TITLE
How to debug nuxt/webpack/loaders?

### ISSUE THREAD

**Issue by alekbarszczewski** [nuxt/nuxt.js#1971]
Since our project grew up dev build process (`nuxt`) became super-slow. We are waiting like 30s-1m for hot reload, no matter if we change one of the components template or just scss (we keep scss separately and include it through nuxt.config.js "css" options).

I want to investigate where webpack/nuxt spends so much time when rebuilding app. My question is how to output in console (or file?) what is webpack/nuxt actually doing when I change something in app source code. I tried following in nuxt.config.js (found in webpack docs):

```
extend (config, ctx) {
  config.plugins.push(new webpack.LoaderOptionsPlugin({
    debug: true
  }))
  config.stats = 'verbose'
}
```

But it does not output any extra info - are those config options overwritten by nuxt?
Are there any other options of debugging what is webpack actually doing?

Using `nuxt@1.0.0-rc11`

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1755">#c1755</a>)</em></sub></div>

**Comment by dotneet** [comment]
I had got same problem, but while use dev branch this problem is not appeared for now.
If you've not tried dev branch, it possibly solve hot-reload problems you encountered.

**Comment by alekbarszczewski** [comment]
@dotneet Hmm I am using `rc-11` - are you talking about this version? Sorry forgot to mention version I am using in issue description.

**Comment by dotneet** [comment]
sorry, `dev branch` means latest code in git repository, it's not published to npm yet.

here is my package.json setting.
```js
dependencies: {
  "nuxt": "git+https://git@github.com/nuxt/nuxt.js.git#dev",
}
```

**Comment by alekbarszczewski** [comment]
@dotneet thanks, I tried like you said but I am receiving error "dist/nuxt.js does not exist". Tried to `cd node_modules/nuxt && npm link && npm run build` but later when I use `nuxt dev` on my project I get strange errors that some of my other packages are missing (but they do exist in node_modules).

Could you tell me how do you set up nuxt when it's installed directly from git and not from npm? Maybe it conflicts with yarn which I am using to for my project?

**Comment by dotneet** [comment]
@alekbarszczewski 

1. Replace `"nuxt": "1.0.0-rc11",` in package.json  with following code.
```js
  "nuxt": "git+https://git@github.com/nuxt/nuxt.js.git#dev",
```

2. Clean `.nuxt` and `node_modules`

```bash
rm -rf .nuxt
rm -rf node_modules
```

3. Install dependencies

```bash
npm i
```

or

```bash
yarn
```

4. Run in dev mode

```bash
npm run dev
```

**Comment by alekbarszczewski** [comment]
I tried as you said but it seems that "prepare" script is not executed for some reason. Do you think it might be yarn issue (I am using latest yarn 1.21)? Please see screen below:
![nuxt_ _-bash_ _225x77](https://user-images.githubusercontent.com/2742373/32214026-d6c9b7ec-be1d-11e7-84b6-bf69429ff68f.png)

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
