### ISSUE TITLE
Trouble accessing plugins via 'context.app' while in async data

### ISSUE THREAD

**Issue by devanflaherty** [nuxt/nuxt.js#1972]
**Hey there,**
Next documentation says you can gain access to your plugins via the ‘app’ key from the context object that is passed in async data.

> The root Vue instance that includes all your plugins. For example, when using axios, you can get access to $axios through context.app.$axios.

I’ve created a custom plugin with global vue methods, as well as some $prototypes, and I don’t have access to them via app.

I also tried using axios like they suggested, but that doesn’t work either.

**Goals I’m trying to accomplish:**
I have a function I invoke when pulling from a prismic.io api as async data.
There is no access to ‘this’ since async data is rendered on the server.

I really would like to have easy access to that function on all my page components. Keep my code as dry as possible.

Any thoughts?

**Comment by alexchopin** [comment]
Hi @devanflaherty, 
Can you post your plugin code to see more about how you are doing it and help you?

**Comment by devanflaherty** [comment]
Hey @alexchopin,
Here is the plugin js code.
```
import Vue from 'vue'
import PrismicConfig from '~/plugins/prismic-configuration'
import PrismicDOM from 'prismic-dom'
var Prismic = require('prismic-javascript')


const prismic = {
  install (Vue, options) {
    Vue.prototype.$initApi = function (req) {
      return Prismic.getApi(PrismicConfig.apiEndpoint, {
        accessToken: PrismicConfig.accessToken,
        req: req
      })
    }

    Vue.mixin({
      computed: {
        prismicDOM () {
          return PrismicDOM
        }
      },
      methods: {
        initApi (req) {
          return Prismic.getApi(PrismicConfig.apiEndpoint, {
            accessToken: PrismicConfig.accessToken,
            req: req
          })
        },
        asHtml (richText) {
          return this.prismicDOM.RichText.asHtml(richText, PrismicConfig.linkResolver)
        },
        asText (richText) {
          return this.prismicDOM.RichText.asText(richText)
        },
        asLink (link) {
          return this.prismicDOM.Link.url(link, PrismicConfig.linkResolver)
        },
        asDate (date, format) {
          return this.prismicDOM.Date(date)
        }
      }
    })
  }
}

Vue.use(prismic)

```
It is registered in the Nuxt config and all the methods work outside of the asyncData function.

And here is where I'm attempting to call the instance method.
```
asyncData ({ params, app }) {
  return app.$initApi().then(api => {
    return api.query(
      Prismic.Predicates.at('document.type', 'work')
    ).then((res) => {
      return { document: res }
    })
  })
}
```


I'm probably doing something wrong or don't understand exactly how the app key works, or prototype instance methods.

I also attempted to just modify the Vue instance by adding a global method in the plugin, but that didn't return any results either..

**Comment by clarkdo** [comment]
`app` is not `Vue` instance, so it doesn't have `$initApi` property. You may take a look at https://github.com/nuxt/nuxt.js/issues/1697.

**Comment by devanflaherty** [comment]
Thank you, you may close this.
