### ISSUE TITLE
ES6 template string build error

### ISSUE THREAD

**Issue by yoyo837** [nuxt/nuxt.js#1975]
```javascript
export default {
  name: 'app',
  computed: {
    item () {
      return this.serverData.dealInfo
    }
  },
  data () {
    return {
      CDN_IMG_HOST: '//cdnimg.ydmap.com.cn',
      serverData: {
        dealInfo: {}
      }
    }
  }
}
```
This code not work: 
```html
<img class="item-img" :src="`${((item.commonSales || {}).picUrl || [])[1] || `${CDN_IMG_HOST}/commonsales/0/`}58X58.gif`">
```
Picture url is wrong:

`/$%20%7B%20%20%20%20%20%20%20%20%20%20CDN_IMG_HOST%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20/commonsales/%20%20%20%20%20%20%20%200%20/%2058X58.gif`

This code work fine:
```html
<img class="item-img" :src="`${(item.commonSales.picUrl || [])[1] || `${CDN_IMG_HOST}/commonsales/0/`}58X58.gif`">
```

`vue-cli` new project created with https://github.com/vuejs-templates/webpack are work fine in both cases.

**Comment by paulgv** [comment]
You should just use a computed property to build the image's src, it would make your code much more readable and you wouldn't have to deal with that template strings craziness :)

Try something like this (only an example, adapt to your needs):
```js
export default {
  // ...
  imgSrc () {
      const suffix = '58X58.gif'
      const { commonSales } = this.item
      if (commonSales && commonSales.picUrl) {
        return `${commonSales}/${suffix}`
      }
      return `${CDN_IMG_HOST}/commonsales/0/${suffix}`
    }
  // ...
}
```

Then in your template, juste reference the computed property like this:

```vue
<img class="item-img" :src="imgSrc">
```

**Comment by yoyo837** [comment]
@paulgv 
Thanks for your suggestion that the code runs in a v-for, I think I should define a method to achieve a similar effect.
