### ISSUE TITLE
如何设置追踪推荐人代码?写在前端middleware或者nuxtServerInit都报错

### ISSUE THREAD

**Issue by issmile** [nuxt/nuxt.js#1977]
有个需求是创建一个邀请链接,
然后需要被邀请的时候即使没登录也要记录这个邀请人,
然后注册的时候也记录邀请人,

我的思路是保存在session,虽然能保存成功,但是有个cookie的报错,代码和错误信息如下,
好像是nuxt已经render了,render后修改cookie就会有错误,
额,然后请问大神们应该怎么写类似nuxt渲染,但是需要服务器配合的逻辑?

  nuxtServerInit ({ commit }, { req , query }) {
      if(query.inviter){
        if (!trance) {
          trance={}
        console.log('req.session.trance.inviter',req.session.trance)
        }
        if(trance.inviter!=query.inviter){
          trance.inviter=query.inviter
        }
        console.log('req.session.trance.inviter',req.session.trance)
      }
}

错误信息

  Error: Can't set headers after they are sent.
      at validateHeader (_http_outgoing.js:504:11)
      at ServerResponse.setHeader (_http_outgoing.js:511:3)
      at Cookies.set (/www/wwwroot/miaodetao/source/node_modules/cookies/index.js:115:13)
      at /www/wwwroot/miaodetao/source/node_modules/koa-session2/index.js:39:21
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by clarkdo** [comment]
You should separate the koa api of saving user and nuxt render, such like:

```js
app.use(async (ctx, next) => {
   await next()
   if (ctx.url.split('/')[1] !=='/api') {
     ctx.status = 200 // koa defaults to 404 when it sees that status is unset
     ctx.req.session = ctx.session
     await nuxtRender(ctx)
   }
 })
const router = koaRouter({
  prefix: '/api'
})
router.post('/user', async function createUser (ctx) {

})
```

**Comment by issmile** [comment]
额,好像是没get 到我的point ,

假设推荐人url 是http://www.xxx.com/cover/chat/536895113237?inviter=60002

那访问这个链接,就会跳转到前端,然后nuxtServerInit 会获取到我的query
也就是query.inviter
我想把他存在session.trace里面,方便以后追踪
然后我把代码简化了,注释了代码报错的地方,貌似是因为页面已经发出去了,然后又改动session,然后报错?


nuxtServerInit ({ commit }, { req , query }) {
	session = req.session
	if(!session.trace){
		session.trace={}
	}
	trace = session.trace

	if(query.inviter){
		//这里会引起COOKIE报错
		trance.inviter=query.inviter
	}

}

然后昨天其实试过,在获取到query.inviter的时候发起一个post请求到server的路由save_inviter 方法保存,但是发现行不通,因为nuxt在访问本地的时候好像必须加http://127.0.0.1:3000/api/save_inviter貌似是因为域名变了,cookie的session值也变了,所以也起不到追踪的效果,然后就搞了一夜...还是没弄好

**Comment by clarkdo** [comment]
你应该是在koa的某个middleware内没有调用 `await next()`, 导致调用链提前结束, `response`返回, 你可以检查一下服务端的`app.use`是否正常调用了`next`

**Comment by issmile** [comment]
额.写中间件保存,是什么概念?大神能否给个例子?

**Comment by clarkdo** [comment]
比如访问: http://localhost:3000/?inviter=60002, 下面是涉及session的代码, 具体构建koa app及nuxt building的未详细列出:

```js
  import session from 'koa-session'
  import koaConnect from 'koa-connect'

  const nuxtRender = koaConnect(nuxt.render)

  app.use(async (ctx, next) => {
    await next()
    ctx.status = 200
    await nuxtRender(ctx)
  })
  const SESSION_CONFIG = {
    key: 'app:sess'
  }
  app.use(session(SESSION_CONFIG, app))
  app.use(async (ctx, next) => {
    ctx.req.session = ctx.session
    if (ctx.path === '/') {
      ctx.session.trace = {inviter: ctx.query.inviter}
    }
    await next()
  })
```
