### ISSUE TITLE
Customize server console output.

### ISSUE THREAD

**Issue by AndreasCag** [nuxt/nuxt.js#1978]
How can I customize server console output?
The problem is console.log debugging turns out really hard problem because nuxt periodically clears all the output in terminal.
I tried find out some information about it in documentation, but found nothing.

**Comment by clarkdo** [comment]
Just use debug:

package.json
```json
{
  "scripts": {
    "dev": "DEBUG=nuxt:*,app:* nuxt"
  }
}
```

your js: 

```js
const debug = require('debug')('app:demo')
debug('meow !')
```
