### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by joshua1** [nuxt/nuxt.js#198]
Hi @Atinux I get the below error when using the feathers-nuxt example source and yarn , i have cleared cache and reinstalled still same issue each time 
```
Vue packages version mismatch:

- vue@1.0.28
- vue-server-renderer@2.1.10

This may cause things to work incorrectly. Make sure to use the same version for both.
```

 i experience the same with npm run dev too

**Comment by Atinux** [comment]
Hi @joshua1 

Are you talking about this example: https://github.com/nuxt/nuxt.js/blob/master/examples/with-feathers/?

**Comment by joshua1** [comment]
Yes, but i have gone past that. the issue was caused by a plugin referencing 1.0 version of vue
