### ISSUE TITLE
Feature Request: Static Export

### ISSUE THREAD

**Issue by ooade** [nuxt/nuxt.js#1980]
I'm just kinda interested in this static export thing as some sites are just purely static, just like a portfolio. I don't know if it's part of the current or future plan of this great project. I hope to see it treated, thanks.

**Comment by alexchopin** [comment]
Hi @ooade,
The `generate` option lets you export you app to a static website (html files).
You can read more about it in the [documentation](https://nuxtjs.org/guide#static-generated-pre-rendering-) and check out the [nuxtent](https://github.com/nuxt-community/nuxtent-module) module.

**Comment by ooade** [comment]
Like seriously, didn't know about that. Thanks :tada: :tada:
