### ISSUE TITLE
Please release a new version, fix memory leak

### ISSUE THREAD

**Issue by nervouself** [nuxt/nuxt.js#1984]
In our production project, we found a bug of memory leak because of the code [up here (already fixed)](https://github.com/nuxt/nuxt.js/commit/5b09b92286bb3a6896c55713594c5a394a9374a7#diff-c1b82c7b8931d52d83e399952282cbc2R128).

So can you release a new version?

**Comment by nervouself** [comment]
@pi0 @alexchopin @Atinux 

Thanks a lot!

**Comment by Atinux** [comment]
Can you confirm that it fixed the memory leak @nervouself?

Did you try by clone nuxt.js repo and did a `npm link`?

**Comment by dotneet** [comment]
Can this be solution?
https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm

**Comment by nervouself** [comment]
@Atinux I have confirmed it, because `Vue.use` will push a new function into Array `installedPlugins` every time.

@dotneet It works, thanks!
