### ISSUE TITLE
port and host are no longer set in package.json

### ISSUE THREAD

**Issue by jaslocum** [nuxt/nuxt.js#1987]
https://nuxtjs.org/faq/host-port#how-to-edit-host-and-port-

This package.json correctly set host to 0.0.0.0 and port to 3001 with nuxt ^0.10.7:

{
  "name": "shopvm",
  "version": "0.4.0",
  "description": "shop vue management system",
  "author": "jaslocum <jack@surfacefinishtech.com>",
  "private": true,
  "dependencies": {
    "bulma": "^0.5.1",
    "font-awesome": "^4.7.0",
    "mysqle": "jaslocum/mysqle",
    "node-sass": "^4.5.3",
    "nuxt": "^0.10.7",
    "sass-loader": "^6.0.6",
    "socket.io-client": "^2.0.0"
  },
  "config": {
    "nuxt": {
     "host": "0.0.0.0",
     "port": "3001"
    }
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.15.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1"
  }
}

As of nuxt.js ^1.0.0 host and port are no longer set by this package.json:
{
  "name": "shopvm",
  "version": "0.4.1",
  "description": "shop virtual management system",
  "author": "jaslocum <jack@surfacefinishtech.com>",
  "private": true,
  "config": {
    "nuxt": {
     "host": "0.0.0.0",
     "port": "3001"
    }
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "bulma": "^0.6.0",
    "font-awesome": "^4.7.0",
    "mysqle": "github:jaslocum/mysqle",
    "nuxt": "github:jaslocum/nuxt.js"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.0",
    "eslint": "^4.9.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6"
  }
}

**Comment by Atinux** [comment]
It seems to be correct in nuxt source code, did you update your npm version? And are you running nuxt with `nuxt dev` or ˋnuxt start`?

**Comment by Atinux** [comment]
Hi @jaslocum 

I just tried and it works perfectly when running `npm run dev` and `npm start`.
