### ISSUE TITLE
Use history.pushstate in NuxtJS

### ISSUE THREAD

**Issue by feedgit** [nuxt/nuxt.js#1993]
I want to router like Twitter style. If you are on homepage, you click on one feed and I come to a POPUP with CHANGE URL. I search on Google and they said about history.pushstate. How can I make it on NuxtJS?

**Comment by Atinux** [comment]
@alexchopin already did something like this, I let him explain how to do it :)

**Comment by alexchopin** [comment]
Hi @feedgit,
Can you give us more informations about the routes structure and views you would like to create?

**Comment by feedgit** [comment]
Sorry if the question is not clear.
The problem I want to said about:
If you go to Twitter's website, and open a tweet from any place (your own timeline, someone else's timeline, a list ...), three things happen:
1. A modal with the tweet opens
2. the URL changes to an absolute URL pointing to that tweet
3. Something doesn't change, though: the background of the modal. Even though we started from e.g. twitter.com/linus_borg and went to twitter.com/vuejs/status/xxxxx when we opened the modal, my profile's timeline is still in the brackground.

Please follow this [issues](https://www.bountysource.com/issues/38010409-allow-absolute-path-change-without-destroying-rendered-components-twitter-style-modals) for more information.

**Comment by feedgit** [comment]
any one can help me please

**Comment by piyushchauhan2011** [comment]
Why not take inspiration from here https://github.com/gatsbyjs/gatsby/tree/master/examples/gatsbygram, https://gatsbygram.gatsbyjs.org/ . I think must be similar kind of concept @feedgit

**Comment by feedgit** [comment]
Thank you piyushchauhan. This is a extremely repository to learn.

**Comment by feedgit** [comment]
SOLVED: Use [Router Module](https://github.com/nuxt-community/router-module) with NuxtJS

**Comment by NicolasCELLA** [comment]
Hello @feedgit did have an exemple with @nuxt/router to make a popup ?
