### ISSUE TITLE
(proposal) Use this tracker for bugs/features only, move 'help wanted' to separate repo

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#1995]
Similar like the folks @nodejs have done (https://github.com/nodejs/help), I think we could benefit if all the help related issues on _how to use_ nuxt (or one of its components) would be moved to a separate repo. Maybe even under @nuxt-community so more people can help, clean and resolve issues. But keep this tracker for bugs and features only.

Although the nuxt-trinity :angel:  tries to keep the tracker as clean as possible, I still find it quite confusing by time. If you look at the current first page there are only 4 bug/feature issues, the other 21 are all general help related.
Take the memory leak issue currently in `rc11` as an example, there are two duplicate open issues about that (1695 and 1728), but they only appear on page __3__. I was surprised when yesterday 1984 appeared in which it was mentioned that the bug was (probably) solved already, while that is a great thing unfortunately nothing about that seems to be mentioned in the open issues 1695 or 1728. Probably that's partially caused because its just difficult now to keep track of all the bug issues?

Splitting the help wanted issues into a separate repo should keep this issue tracker much cleaner so its easier:
- for the nuxt-trinity to keep us informed about bug/feature statuses / progress
- and for us users/developers to check if our issue has already been reported or not

Probably we would need to add an `ISSUE_TEMPLATE` that explains this.

**Comment by lucpotage** [comment]
Why not using `-label:"help wanted"` in the filter input?

**Comment by pimlie** [comment]
Because it requires the nuxt-trinity to first add those labels. And it would probably be fine if everybody used that by default. Or if everybody always looked past page 1 when reporting issues. But just like coding, 'separation of logic' would be better here I think.

Also imho an issue tracker should not (try) be a support forum, something like StackOverflow is much better suited for that. For small projects this wont really be a problem (maybe you even want/need to concentrate the knowledge) but when a project gains more traction / popularity there comes a time it should split those things. 

For example, compare github / so presence between node/vue and nuxt:
- Vuejs has ~5500 issues on github and 11.000 tagged questions on so
- Node.js 1000 issues on github (in the help repository) and 200.000 tagged questions on so. 
- Nuxt.js has ~1800 issues on github (of which ~800 tagged help/question) and 130 on so

Those ratio's are just off (even if its a little bit like comparing apples to oranges as nuxt is still quite new).

**Comment by homerjam** [comment]
I very much agree with @pimlie.

I think Nuxt is the victim of it's own success - it lowers the bar for creating sophisticated apps and therefore attracts a lot of less experienced developers who inevitably ask questions that aren't actually specific to Nuxt. The issue template would be a great way to inform and direct these types of queries to SO as suggested.

**Comment by Atinux** [comment]
Hi @pimlie @homerjam @lucpotage 

Thank you for this suggestion, actually my friends and I are working on a project to solve this, it will help us to synchronize everything, filter what's bugs and questions, etc.

But the most important thing, show all our contributors, not only the one who makes PR, but people like you guys who help us everyday to answer our open issues, I hope to deploy this system in the next months :)
