### ISSUE TITLE
What is the best method to integrate a vuejs composent to nuxtjs ?

### ISSUE THREAD

**Issue by DevDom05** [nuxt/nuxt.js#1996]
I try to use this composent to nuxtjs
https://github.com/krystalcampioni/vue-hotel-datepicker

What is the best method to integrate and use it on nuxtjs ?

**Comment by lucpotage** [comment]
Hello @DevDom05 ,

Did you read this page? https://nuxtjs.org/guide/plugins
It explains in details how to add a Vue plugin to Nuxt.

**Comment by DevDom05** [comment]
Thanks you.

Ok I write a plugin, 
insert the plugin in the nuxtjs config file ... and the node module in vendor in the nuxtjs config

But how can i avoid a "document / windows is undefined" without modify the node module (here the datepicker vuejs component) ?

**Comment by lucpotage** [comment]
Did you get this error with this specific plugin (ie vue-hotel-datepicker)?
And just in case, are you using the latest rc11 version?

**Comment by DevDom05** [comment]
Yes, i have this error with this spectific vue component and a project based on the express nuxtjs template.

I modify the package.json and type "npm update" to use the rc11 but i still have the error.

In the nuxtjs documentation, "if (process.browser)"
https://nuxtjs.org/faq/window-document-undefined/

But i don't want to modify a npm module.
How can i avoid this error without modify a npm module (vue component) ?

**Comment by paulgv** [comment]
You don't need to modify the NPM module, just make sure your plugin isn't initialized server-side by setting it's `ssr` option to false as mentioned in the _Client-side only_ section here: https://nuxtjs.org/guide/plugins

**Comment by DevDom05** [comment]
Thank you.

No more error but the date picker is not render
Can i have some help ? 

```
  plugins: [{ src: '~/plugins/hoteldatepicker', ssr: false }],
  build: {
    vendor: ['axios','vue-hotel-datepicker'], 
```
The plugin
```
import Vue from 'vue'
import VueHotelDatepicker from 'vue-hotel-datepicker'

Vue.use(VueHotelDatepicker)
```

The page :
```
<template>
  <section class="container">
      <HotelDatePicker format="DD/MM/YYYY">
      </HotelDatePicker>
  </section>
</template>

<script>
export default {
  head () {
    return {
      title: 'Test'
    }
  }
}
</script>
```
