### ISSUE TITLE
Uncaught ReferenceError from plugin file

### ISSUE THREAD

**Issue by smth** [nuxt/nuxt.js#1997]
I have a working [page](http://p.smth.uk/parts-selector/) outside of Nuxt. When I bring it into Nuxt, the JS as a plugin, I get an `Uncaught ReferenceError: i is not defined` error. 

The `i` refers to [this](https://github.com/evulse/finderSelect/blob/master/jquery.finderSelect.js#L452), and is related to the Hooks of [this script](http://evulse.github.io/finderSelect/).

That's not my code, but as I say, it is working in my [non Nuxt implementation](https://github.com/smth/parts-selector). The [same thing in Nuxt](http://p.smth.uk/goodtables/sources) gives the error.

In the Nuxt version I have:
- saved the script in the plugins directory
- added it to the config plugins, using `ssr: false`
- initialised it on the page inside `mounted: () => {`

It works if I remove the [parts of my code utilising the hooks](https://github.com/smth/goodtables/blob/master/plugins/parts-selector.js#L24), but outside of Nuxt it all works. Why would this be?

**Comment by clarkdo** [comment]
Mad a pr for you repo 😸  https://github.com/smth/goodtables/pull/1

**Comment by smth** [comment]
That looks like it fixes it @clarkdo , thanks. So it's a matter of Nuxt (or Vue?) being more strict than browsers? If I don't want to maintain a separate version of that [plugin](https://github.com/evulse/finderSelect), I guess the only solution would be to ask the author to make that change in the original? Maybe you should make the PR there ;)

**Comment by clarkdo** [comment]
ok, wil make a pr

**Comment by clarkdo** [comment]
Issue will be fixed in https://github.com/evulse/finderSelect/pull/19

**Comment by smth** [comment]
Nice. I would have left this issue open because it's more a question about why this causes a problem in Nuxt, and if/how you could make Nuxt behave as expected.
