### ISSUE TITLE
[Request] Ability to cancel navigation from asyncData without error page

### ISSUE THREAD

**Issue by benosman** [nuxt/nuxt.js#1998]
When handling in-browser errors inside asyncDatafunctions , I want to handle certain errors using pop up alerts rather than navigating to a full error page.

Using axios module, I can show the alert just fine, however the problem is that if I don't throw an error the route and new page continues to load without data. If i do throw an error, the error page loads behind the alert, but navigation stops as intended.

What I would like is either access to the `next()` function inside asyncData, or an ability to specify in the error object that it has already been handled so no further error page is needed.

Alternatively - any suggestions on how to override the error code in client.js welcomed.

example 1 - navigation continues
```js
if (ctx.isClient) {
    const swal = require('sweetalert2')
    swal({
      type: 'error',
      title: error.title,
      html: error.message
    })
  } else {
    return Promise.reject(error)
  }
```
example 2 - error page shown
```js
if (ctx.isClient) {
    const swal = require('sweetalert2')
    swal({
      type: 'error',
      title: error.title,
      html: error.message
    })
}
return Promise.reject(error)
```

**Comment by benosman** [comment]
Following up from this, I've managed to work around this issue by overriding the `Vue.prototype.$nuxt.error` function when in the browser, and skip error if it's already been handled.

It is a hacky way though, but I can't see many other ways since `errorMiddleware`, and `beforeNuxtRender` don't run in the browser, so there aren't many points to intercept the error.

Further suggestions welcome.

**Comment by clarkdo** [comment]
You can also take a look at https://github.com/nuxt/nuxt.js/issues/1073
```js
window.onNuxtReady(({app}) => {
  app._nuxt.error = () => {
    // your actions
  }
})
```
