### ISSUE TITLE
UnhandlesPromiseRejectionWarning - Request failed status 403

### ISSUE THREAD

**Issue by atmar** [nuxt/nuxt.js#1999]
Hello,

Today I've uploaded my nuxt.js app to production on a live host. Let's call it sub.domain.com . The back-end is made with Laravel on domain.com. All api requests go to domain.com/api/v2/... .

Now everything works fine on my local PC, even if I use domain.com for the api requests instead of my local homestead.app environment. But whenever I run the server on my live server, I receive a Request failed with status code 403 error - UnhandlesPromiseRejectionWarning. This happens on first load when asyncData is retrieving data from the api. If I first visit a page however that doen't have asyncData, I can move through the whole website without problems. It's only the first load that gives this problem. What could cause this, or how can I find out the error that Laravel is giving me about the 403? I've thought I could grab it with a try catch error, but that shows me the same error that I see on the nuxt error page, which doesn't give any info.

**Comment by atmar** [comment]
This runs on nginx with the application redirected to sub.domain.com.
if ($host ~ "sub.domain.com") {
 set $PROXY_DOMAIN_OR_IP "xxx.xx.xx.x";
 set $PROXY_TO_PORT 3000;
}

**Comment by clarkdo** [comment]
That should because first time `asyncData` call is inside node server, do you use `axios` ? You can use a env variable to set `baseUrl` pointed to the `nginx` in production.

**Comment by atmar** [comment]
I use dotenv to set my env variables and use that to set the baseURL of nuxt/axios. I've used the same domain.com baseURL in both local and production to test. But in the production I receive a 403 error
```
require('dotenv').config()
```

```
  modules: [
    // With options
    ['@nuxtjs/axios', {
      credentials: false,
      baseURL: process.env.BACKEND_URL + '/api/v2'
    }]
  ],
```

**Comment by atmar** [comment]
Found the solution in https://github.com/nuxt-community/axios-module/issues/20 . There is a hidden setting called "proxyHeaders" that is by default set to true. Change it to false
```
  modules: [
    // With options
    ['@nuxtjs/axios', {
      credentials: false,
      proxyHeaders: false
      baseURL: process.env.BACKEND_URL + '/api/v2'
    }]
  ],
```

**Comment by failpunk** [comment]
`proxyHeaders: false` is needed if you're hosting your site with a reverse proxy like CloudFlare.
