### ISSUE TITLE
Expose webpack config for ESLint

### ISSUE THREAD

**Issue by samtgarson** [nuxt/nuxt.js#200]
In order to lint our Vue files with ESlint, we need to use [eslint-import-resolver-webpack](https://www.npmjs.com/package/eslint-import-resolver-webpack) to tell eslint how to resolve our `import` statements using Nuxt's custom aliases, to avoid errors like these:

![image](https://cloud.githubusercontent.com/assets/6242344/22619611/4b6017b0-eaf0-11e6-914a-5a0836fe4222.png)

At the moment I can't find Nuxt's webpack config anywhere in my `node_modules` directory to give to this plugin?

**Comment by Atinux** [comment]
@samtgarson the webpack config is dynamic and nuxt.js uses 2 of them (server and client bundles).

For the `vue` files, you can use `eslint-plugin-html`, see our tutorial here: https://nuxtjs.org/guide/development-tools#eslint

For the aliases, please take a look at https://github.com/nuxt/nuxt.js/blob/master/lib/webpack/base.config.js#L32

**Comment by samtgarson** [comment]
@Atinux do you not get the error I've show above when using the `import/no-unresolved` rule? I'm using all the suggested methods from your library and others, but nothing you've mentioned shows how ESLint can follow your webpack aliases without a webpack config?

**Comment by Atinux** [comment]
Hi @samtgarson sorry for closing the issue too quickly.

Do you mind sharing your `.eslintrc.js`?

**Comment by Atinux** [comment]
I found a way to make it work but you have to define your alias mannually, there are not other way around.

Here my `.eslintrc.js`:
```js
const resolve = require('path').resolve

module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    browser: true,
    node: true
  },
  extends: 'standard',
  // required to lint *.vue files
  plugins: [
    'html',
    'import'
  ],
  // add your custom rules here
  rules: {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    // do not allow console.logs etc...
    'no-console': 2,
    'import/no-unresolved': 2
  },
  globals: {},
  settings: {
    'import/resolver': {
      webpack: {
        config: {
          resolve: {
            alias: {
              '~': __dirname,
              'static': resolve(__dirname, 'static'), // use in template with <img src="~static/nuxt.png" />
              '~static': resolve(__dirname, 'static'),
              'assets': resolve(__dirname, 'assets'), // use in template with <img src="~static/nuxt.png" />
              '~assets': resolve(__dirname, 'assets'),
              '~plugins': resolve(__dirname, 'plugins'),
              '~store': resolve(__dirname, '.nuxt/store'),
              '~router': resolve(__dirname, '.nuxt/router'),
              '~pages': resolve(__dirname, 'pages'),
              '~components': resolve(__dirname, 'components')
            }
          }
        }
      }
    }
  }
}
```

You need to install the dependencies:
```bash
npm install --save-dev eslint-plugin-import eslint-import-resolver-webpack
```

**Comment by samtgarson** [comment]
@Atinux yep that's what I did as well. Nuxt should ship with these exposed/importable for this kind of situation.

**Comment by rmartins90** [comment]
The same here https://github.com/nuxt/nuxt.js/issues/461

**Comment by chrisnicola** [comment]
Another alternative would be a `eslint-plugin-nuxt` to take care of this somehow.

**Comment by chrisnicola** [comment]
On further experimentation I'm noting that this creates problems with unit-testing as well as any unit testing approach needs to know something about these aliases. This is a bit of a more general problem with webpack of course, but still creates a challenge nonetheless.

**Comment by dsky1990** [comment]
@samtgarson 
my eslint config is here
```js
const resolve = require('path').resolve;
module.exports = {
  root: true,
  extends: "airbnb-base",
  parser: 'babel-eslint',
  rules: {
    "import/no-extraneous-dependencies": ["error", {
      "devDependencies": true,
      "optionalDependencies": true
    }],
    "prefer-arrow-callback": ["error",{
      "allowNamedFunctions": true
    }],
    "comma-dangle": ["error", "never"],
    "new-cap": ["error",{
      "properties": false
    }],
    "quote-props": ["error", "as-needed", { "keywords": true, "unnecessary": false }],
    "no-underscore-dangle": ["error", { "allow": ["_this"] }],
    "no-unused-vars": ["error", { "varsIgnorePattern": "cb" }],
    "max-len": ["error", 180],
    "no-param-reassign": ["error", { "props": false }],
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
    "linebreak-style": 0,
    "consistent-return": 0,
    "guard-for-in": 0,
    "func-names": 0,
    "no-console": 0,
    "one-var": ["error", { "var": "always", "let": "always", "const": "always" }],
    "prefer-const": ["error", {"destructuring": "all"}],
    'import/no-unresolved': 2
  },
  env: {
    "browser": true,
    "es6": true,
    "node": true,
    "shared-node-browser": true,
    "jquery": false,
    "commonjs": true,
    "amd": false,
    "mocha": false
  },
  plugins: [
    'html'
  ],
  settings: {
    'import/resolver': {
      webpack: {
        config: {
          resolve: {
            alias: {
              '~': __dirname,
              '~static': resolve(__dirname, 'static'),
              '~assets': resolve(__dirname, 'assets'),
              '~plugins': resolve(__dirname, 'plugins'),
              '~store': resolve(__dirname, '.nuxt/store'),
              '~router': resolve(__dirname, '.nuxt/router'),
              '~pages': resolve(__dirname, 'pages'),
              '~components': resolve(__dirname, 'components')
            }
          }
        }
      }
    }
  }
};
``` 
i use your way, but it still warns 
```
 https://google.com/#q=import%2Fno-unresolved  Unable to resolve path to module '~components/Logo.vue'
  pages\index.vue:20:18
  import Logo from '~components/Logo.vue';
```

**Comment by samtgarson** [comment]
@dsky1990 Did you install `eslint-import-resolver-webpack`?

**Comment by dsky1990** [comment]
@samtgarson ,yes
```
"devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.15.0",
    "eslint-config- -base": "^11.2.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-import-resolver-webpack": "^0.8.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1"
  }
```

**Comment by samtgarson** [comment]
Then I'm afraid I can't help. Either way, it's nothing do to with nuxt so should probably be somewhere else

**Comment by chrisnicola** [comment]
@samtgarson posting a working webpack.config.js below for people. However, as this is a common problem and also creates problems for test running and other tools that depend on understanding the webpack configuration, I would suggest adding this to the template for new projects as well as a basic eslint config that uses it. This is going to be a really common stumbling block for people starting with Nuxt.

`webpack.config.js`
```
const resolve = require('path').resolve;

// Minimal Webpack config to supply to Eslint.
// This is not actually used by Nuxt but instead mirrors
// the resolve and loader rules.
module.exports = {
  resolve: {
    modules: [resolve(__dirname, 'lib'), 'node_modules'],
    extensions: ['.js', '.vue'],
    alias: {
      '~': __dirname,
      'static': resolve(__dirname, 'static'), // use in template with <img src="~static/nuxt.png" />
      '~static': resolve(__dirname, 'static'),
      'assets': resolve(__dirname, 'assets'), // use in template with <img src="~static/nuxt.png" />
      '~assets': resolve(__dirname, 'assets'),
      '~plugins': resolve(__dirname, 'plugins'),
      '~store': resolve(__dirname, '.nuxt/store'),
      '~router': resolve(__dirname, '.nuxt/router'),
      '~pages': resolve(__dirname, 'pages'),
      '~components': resolve(__dirname, 'components'),
      '~lib': resolve(__dirname, 'lib'),
    },
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.vue$/,
        exclude: /node_modules/,
        loader: 'vue-loader',
      },
    ],
  },
};
```

`.eslintrc.js`
```
module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    browser: true,
    node: true
  },
  extends: 'airbnb-base',
  // required to lint *.vue files
  plugins: [
    'html',
    'import',
  ],
  // add your custom rules here
  rules: {},
  globals: {},
  settings: {
    'import/resolver': {
      webpack: 'webpack.config.js',
    },
  },
};
```

I hope this helps people having trouble here.

**Comment by chrisnicola** [comment]
Just an additional note. Unless you configure it otherwise Eslint will still require that you add `.vue` to vue file imports. I'm perfectly fine with this as it helps distinguish them, but webpack doesn't require this. You can set the `import/extensions` rule if you don't like this behaviour.

**Comment by samtgarson** [comment]
That's helpful for posterity and for future readers of this thread, but it doesn't solve the issue which is that the webpack config inside Nuxt can and will change, meaning that users who manually write their aliases will need to keep up.

In fact—I kinda think that makes this misleading as this _hides_ the problem, as new users of nuxt may wonder why their aliases aren't working when the nuxt webpack config changes in the future.

Perhaps an eslint plugin is the way to go as it can dynamically extract the webpack config at runtime? Not sure anyway...

**Comment by dsky1990** [comment]
@samtgarson same idea with you， the `webpack.config.js`  in template has set the all the config , why it works bad ? if we have to add a new `webpack.config.js` , why not let us to define it by ourself? @chrisnicola

**Comment by dsky1990** [comment]
@chrisnicola my floder is like this,[floder](http://dsklab-dsklab.stor.sinaapp.com/XU7SS85%29EZ_%7DH%7BW4YCVFWA5.png),
`.eslintrc.js`
```
module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    browser: true,
    node: true
  },
  extends: 'airbnb-base',
  // required to lint *.vue files
  plugins: [
    'html',
    'import'
  ],
  // add your custom rules here
  rules: {},
  globals: {},
  settings: {
    'import/resolver': {
      webpack: 'webpack.config.js',
    },
  },
};

```
`webpack.config.js`
```
/**
 * webpack.config.js
 * Created by dsky on 17/6/15.
 */
const resolve = require('path').resolve;

// Minimal Webpack config to supply to Eslint.
// This is not actually used by Nuxt but instead mirrors
// the resolve and loader rules.
module.exports = {
  resolve: {
    modules: [resolve(__dirname, 'lib'), 'node_modules'],
    extensions: ['.js', '.vue'],
    alias: {
      '~': __dirname,
      'static': resolve(__dirname, 'static'), // use in template with <img src="~static/nuxt.png" />
      '~static': resolve(__dirname, 'static'),
      'assets': resolve(__dirname, 'assets'), // use in template with <img src="~static/nuxt.png" />
      '~assets': resolve(__dirname, 'assets'),
      '~plugins': resolve(__dirname, 'plugins'),
      '~store': resolve(__dirname, '.nuxt/store'),
      '~router': resolve(__dirname, '.nuxt/router'),
      '~pages': resolve(__dirname, 'pages'),
      '~components': resolve(__dirname, 'components'),
      '~lib': resolve(__dirname, 'lib'),
    },
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.vue$/,
        exclude: /node_modules/,
        loader: 'vue-loader',
      },
    ],
  },
};

```
it still warns
```
 error  in ./pages/index.vue


  ✘  https://google.com/#q=import%2Fno-unresolved  Unable to resolve path to module '~components/Logo.vue'
  pages\index.vue:20:18
  import Logo from '~components/Logo.vue';
                    ^


✘ 1 problem (1 error, 0 warnings)

```

**Comment by chrisnicola** [comment]
@samtgarson I agree as well but for now there isn't a better solution. Sadly, I need this config for testing purposes as well when testing with Webpack and Tape, so the lack of a way to get the config is a bit of a problem.

Since .eslintrc.js is a webpack file perhaps Nuxt could simply expose the module that generates the configuration?

```
const webpackConfig = require('nuxt/webpack-config');

// or

const configGenerator = require('nuxt/webpack-config');
const webpackConfig = configGenerator();
```

**Comment by chrisnicola** [comment]
@dsky1990 I wish I could help. That's my configuration and it is working for me. Perhaps make sure your all the NPM packages are up to date?

**Comment by dsky1990** [comment]
@samtgarson thanks for your help，my package is here, maybe I lost someting?
```
{
  "name": "nuxt-demo",
  "version": "1.0.0",
  "description": "Nuxt.js project",
  "author": "dsky1990 <dutian1990@gmail.com>",
  "private": true,
  "dependencies": {
    "nuxt": "latest"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "babel-eslint": "^7.1.1",
    "babel-preset-stage-2": "^6.24.1",
    "eslint": "^3.15.0",
    "eslint-config- -base": "^11.2.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-import-resolver-webpack": "^0.8.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1",
    "sass-loader": "^6.0.6"
  }
}

```

**Comment by chrisnicola** [comment]
I don't see any problems, though the `eslint-config- -base` line looks suspect. This is mine.
```
{
  "name": "<removed>",
  "description": "<removed>",
  "version": "1.0.0",
  "author": "<removed>",
  "dependencies": {
    "nuxt": "latest"
  },
  "devDependencies": {
    "avoriaz": "^2.0.0",
    "babel-preset-stage-2": "^6.24.1",
    "browser-env": "^2.0.31",
    "eslint": "^3.15.0",
    "eslint-config-airbnb-base": "^11.2.0",
    "eslint-import-resolver-webpack": "^0.8.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-import": "^2.3.0",
    "glob": "^7.1.2",
    "memory-fs": "^0.4.1",
    "source-map-support": "^0.4.15",
    "tap-spec": "^4.1.1",
    "tape": "^4.6.3",
    "vue": "^2.3.4",
    "webpack": "^2.6.1",
    "webpack-node-externals": "^1.6.0"
  },
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "PORT=3333 nuxt",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint",
    "start": "nuxt start",
    "test": "wprun -r ./test_helpers/index.js {components,pages,store,lib}/**/*.test.js | tap-spec",
    "test:lib": "wprun -r ./test_helpers/index.js lib/**/*.test.js | tap-spec",
    "test:pages": "wprun -r ./test_helpers/index.js pages/**/*.test.js | tap-spec",
    "test:store": "wprun -r ./test_helpers/index.js store/**/*.test.js | tap-spec",
    "test:watch": "wprun -w -r ./test_helpers/index.js {components,pages,store,lib}/**/*.test.js | tap-spec"
  }
}
```

**Comment by dsky1990** [comment]
thanks for your help

**Comment by chrisnicola** [comment]
So I did some digging and there doesn't seem to be a clean way to currently access Nuxt's internal webpack config. However it seems like it would be fairly straight-forward to extend nuxt to provide a helper for extensions that want to access it. 

I'm thinking about something like this:

```
nuxtWebpackConfig = require('nuxt/webpack');

module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    browser: true,
    node: true
  },
  extends: 'airbnb-base',
  // required to lint *.vue files
  plugins: [
    'html',
    'import',
  ],
  // add your custom rules here
  rules: {},
  globals: {},
  settings: {
    'import/resolver': {
      webpack: nuxtWebpackConfig,
    },
  },
};
```

This could be further improved by providing an import/resolver for eslint that works with Nuxt out of the box like `eslint-import-resolver-nuxt`.

Any thoughts? Is this something useful, if so I'd be happy to make the attempt at a PR.

**Comment by dsky1990** [comment]
good idea,hope it comes soon , now , I think i have to use webpack,thanks for your help @chrisnicola

**Comment by samtgarson** [comment]
@chrisnicola this was kind of what I was thinking of when I opened this issue, I haven't had time to do any investigating but this sounds perfect!

`eslint-import-resolver-nuxt` sounds good as it would keep it out of the nuxt codebase as it doesn't seem essential to everyone using nuxt.

**Comment by chrisnicola** [comment]
We ultimately decided to go a different direction on this, and I likely won't have time to commit to a PR for this.

**Comment by dfee** [comment]
If nothing else, I present to you [`webpack-starter-template-airbnb`](https://github.com/dfee/nuxt-starter-template-airbnb/tree/master/template) with the answers from this thread, out of the box.

Cheers.

**Comment by michaelwills** [comment]
@dfee Thanks much for that!

**Comment by busheezy** [comment]
I ran into this issue, yesterday. Thanks for the airbnb starter. It's exactly what I need.

**Comment by wdews** [comment]
Personally, I fought with this issue for several hours and found that I was simply lacking the following definition in my ESLint Configuration file:

```javascript
module.exports = {
  // ...

  plugins: [
    'html'
  ],

  // ...
}```

**Comment by Ding-Fan** [comment]
@wdews https://nuxtjs.org/guide/development-tools#eslint says use **eslint-plugin-vue** 
and https://github.com/BenoitZugmeyer/eslint-plugin-html#linting-vue-files says don't use **eslint-plugin-html** if you have **eslint-plugin-vue**
Now the best way I found is https://github.com/hejianxian/nuxt-starter-template-airbnb/blob/master/template/.eslintrc.js , as @dfee mentioned.

**Comment by dysol** [comment]
So what is the solution to this ? I also have error with import/no-extraneous-dependencies when i do an Import Vue from 'vue' in my custom plugin.js

**Comment by felubra** [comment]
@dysol regarding the import/no-extraneous-dependencies error, I fixed it by adding the follow into the .eslintrc.js:

```
settings: {
    // packages already included in nuxt or nuxt modules
    'import/core-modules': ['vue', 'vuex'],
  }
```
You also need to install the eslint-plugin-import plugin and register it into .eslintrc.js config file.

**Comment by dweldon** [comment]
I believe I was able to solve this just by installing [eslint-import-resolver-nuxt](https://www.npmjs.com/package/eslint-import-resolver-nuxt) and adding the following to my `.eslintrc.js`:

```js
settings: {
  'import/resolver': {
    nuxt: {
      extensions: ['.js', '.vue'],
    },
  },
},
```

---

For reference my `devDependencies` looks like:

```js
"devDependencies": {
  "eslint": "^5.3.0",
  "eslint-config-airbnb-base": "^13.0.0",
  "eslint-import-resolver-nuxt": "^0.1.1",
  "eslint-plugin-import": "^2.13.0",
  "eslint-plugin-vue": "^5.0.0-beta.2"
}
```

And my complete `.eslintrc.js` is:

```js
module.exports = {
  extends: [
    'airbnb-base',
    'plugin:vue/recommended',
  ],
  settings: {
    'import/resolver': {
      nuxt: {
        extensions: ['.js', '.vue'],
      },
    },
  },
};
```
