### ISSUE TITLE
how to insert <script> tag before </body>？

### ISSUE THREAD

**Issue by cdoneshot** [nuxt/nuxt.js#2000]
i want to insert some <script> tag before the </ body> tag in some pages. if i modify app.html ,all pages will be inserted,or i use head() in these pages,it will be inserted in the head,these are not my wanted

**Comment by ncodm** [comment]
can edit in the template html

**Comment by cdoneshot** [comment]
> can edit in the template html
app.html?all pages will be inserted

**Comment by clarkdo** [comment]
All `<script>` tags have been inserted before `</body>`.
![image](https://user-images.githubusercontent.com/4312154/32258081-8f57eb54-be86-11e7-8097-53670db9a458.png)

**Comment by cdoneshot** [comment]
@clarkdo 

emmm..i want to import 3rd party lib  ,use script tag to import  instead import .
like this <script src= "//amp.azure.net/libs/amp/latest/azuremediaplayer.min.js"></script>
it will be used in some pages not all pages ,so i dont want to modify app.html.

**Comment by paulgv** [comment]
You could include those scripts in the pages themselves.

**Comment by cdoneshot** [comment]
> I guess you could include those scripts in the pages themselves.

i include theses scripts in the <template> now,but i got the missmatch warnning.
![image](https://user-images.githubusercontent.com/20412044/32258493-ac671462-bef5-11e7-9990-a2a53b67a593.png)
![image](https://user-images.githubusercontent.com/20412044/32258533-ecc26f98-bef5-11e7-8a8a-84882a0a5732.png)

i guess the 3rd party lib will change the dom  so i got this warnning and the <script> is not in the place where i want .

Is there any other way?

**Comment by clarkdo** [comment]
```js
<template>
<div></div>
</template>

<script>
export default {
  created() {
    if (process.browser) {
      let recaptchaScript = document.createElement('script')
      recaptchaScript.setAttribute('src', 'https://www.google.com/recaptcha/api.js')
      document.head.appendChild(recaptchaScript)
    }
  }
}
</script>
```

**Comment by cdoneshot** [comment]
@clarkdo   I had tried this way ,but there are some reasons cant use this way.
this page be put in a native ios app.ios webview will call some js method on finishedload page,but the js has not be loaded yet.
![image](https://user-images.githubusercontent.com/20412044/32259103-264cf1a4-bef9-11e7-8f5c-32fb3a5f38c2.png)

**Comment by clarkdo** [comment]
```html
<div v-html="scripts"></div>
```
```js
export default {
  data: () => ({
    scripts: "<script src='https://www.google.com/recaptcha/api.js'><\/script>"
  })
}
```

**Comment by pimlie** [comment]
I guess you want to add scripts to the bottom to defer execution because the script is used on the page but not required for viewing the page? 

Actually I have asked for the same functionality in #1370, it would be nice it you could do this easily. Although you can set the defer tag with vue-meta, which _should_ defer execution, I still also prefer to put them psychically at the bottom of the page.

**Comment by cretueusebiu** [comment]
Nuxt will generate a `app.template.html` file inside `.nuxt/views`. You can edit it and add your script there.

**Comment by cdoneshot** [comment]
> ```javascript
> <div v-html="scripts"></div>
> ```
> ```javascript
> export default {
>   data: () => ({
>     scripts: "<script src='https://www.google.com/recaptcha/api.js'><\/script>"
>   })
> }
> ```
works ,same as 
```javascript

  <div>
    <video id="azuremediaplayer" ></video>
    <script src="azure/azuremediaplayer.min.js"></script>
  </div>
```
not in front of the </ body> tag

**Comment by clarkdo** [comment]
> works ,same as

There is no `Vue warn` in `v-html` way.

> not in front of the </ body> tag

It will be the same effect, as well as in `head` with `defer`. Is there any purpose of `</body>` thought ?
Even in `app.html` or `vendor`, browser will cache js file at first time, also make no difference to performance.

**Comment by pimlie** [comment]
Putting `<scripts>` just before `</body>` is mostly about user experience, specifically to make sure a functioning / visible page is rendered as fast as possible. 

This strategy is mostly used for scripts that are not important to the functioning of the page itself, think of analytic scripts, delayed/async image loading and especially 3rd party ads. Although the browser caches the files probably themselves, you often want to make fully sure execution is delayed as you dont want your page to feel sluggish due to a heavy ad. Defer _should_ do this as well, but putting it at the end of the body just _physically_ makes sure it happens like this.

**Comment by cdoneshot** [comment]
>There is no Vue warn in v-html way.

if the script in _**static**_ folder,will get a error=>**cannot resolve xx.js in 'pages/xxx'**

**Comment by cdoneshot** [comment]
> make sure to use an absolute path

I'm sure I'm using an absolute path and these scripts are all in **_static _** folder.
![image](https://user-images.githubusercontent.com/20412044/32320581-412f75e0-bff9-11e7-855d-ab0731024de2.png)

then i got an error
![image](https://user-images.githubusercontent.com/20412044/32320589-4aec55bc-bff9-11e7-9b78-0f6497a09f23.png)

**Comment by dotneet** [comment]
Hi, this is my way.

```html
<template>
<div>
   <a class="twitter-timeline" href="https://twitter.com/nuxt_js">Tweets by nuxt_js</a>
   <span v-if="twitterWidget">
      <script src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    </span>
</div>
</template>
```

```js
<script>
export default {
    data () {
      return {
        twitterWidget: false,
      }
    },
    async mounted () {
      this.twitterWidget = true
    },
}
</script>
```

**Comment by clarkdo** [comment]
@cdoneshot @pimlie 
Hi guys, I have discussed with @Atinux, we may try to support this feature in `vue-meta` and may add configuration like:
```json
{
  metaInfo: {
    bodyScript: [
      { src: 'azure/azuremediaplayer.min.js' }
    ]
  }
}
```

This feature is planned to 1.0.0 release for now.

**Comment by phivk** [comment]
I came across this issue and still had to look for quite a while to find the correct syntax that was released in 1.0.0, so for reference:

```
<script>
export default {
  head: {
    script: [
      { src: '/head.js' },
      // Supported since 1.0
      { src: '/body.js', body: true },
      { src: '/defer.js', defer: '' }
    ]
  }
}
</script>
```

src: [this example](https://github.com/nuxt/nuxt.js/blob/dev/examples/meta-info/pages/index.vue#L18) from the [1.0.0 release notes](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0)

**Comment by ameno-gdrive** [comment]
Close, but we're not 100% there yet.

Utilizing the method quoted by @phivk , the script will be put near the end of the <head> tag, not at the end of the <body>.  While the defer property will allow parallel script fetch and downloads, the load ordering of js during the parsing phase is still off.

Currently any deferred script will parse and execute before the Vuejs application script.  Suppose you have a ton of scripts that can use async property, or scripts that dont need to execute before the application executes.

We're forced to lose a chunk of time waiting.

**Comment by qm3ster** [comment]
@ameno-gdrive why put scripts in html at all? Can't you just asynchronously import them in your javscript where you need them?

**Comment by mesqueeb** [comment]
@qm3ster 
For some libraries this is not possible. E.g. [the UMD version of Quasar](https://quasar-framework.org/guide/index.html).

**Comment by Geowan** [comment]
Its very easy

Just create a app.html at the root of your project and add

      <html {{ HTML_ATTRS }}>
       <head>
        {{ HEAD }} 
      </head>
     <body {{ BODY_ATTRS }}>
       {{ APP }}

       
       </body>
    </html>

THats the default template that nuxtjs uses  by default. Ensure that you place this at the root of your project

**Comment by weddinghairandmakeupartists** [comment]
@Geowan That will put the script on every page. @cdoneshot wanted it on specific pages
