### ISSUE TITLE
Intercept the STATIC folder GET

### ISSUE THREAD

**Issue by u382514** [nuxt/nuxt.js#2003]
Is there an official way of intercepting the GET calls to the static folder? Let's say you have images in the static folder and you want to do some processing on the image before it's loaded to the client based on a query string in the SRC of the img tag, how can we intercept it?

**Comment by clarkdo** [comment]
You can define an express middleware like [custom-server](https://github.com/nuxt/nuxt.js/blob/dev/examples/custom-server/server.js) before `app.use(nuxt.render)`
```
app.use(function (req, res, next) {
  if(req.method === 'GET' && req.path.startsWith('/static/')) {
  // do your processing
  }
  next();
});
app.use(nuxt.render)
```
