### ISSUE TITLE
Accessing the store from an external file

### ISSUE THREAD

**Issue by freevital** [nuxt/nuxt.js#2005]
```js
// ~/store/index.js
import Vuex from 'vuex';

export default () => new Vuex.Store({
    actions: {
        someAction() {
            //
        }
    }
});

```

```js
// external js file
import store from '~/store';

export default class AuthService {
    static login() {
        store.dispatch('someAction');
    }
}
```
I get an error when app builds:
```
TypeError: __WEBPACK_IMPORTED_MODULE_2__store__.default.dispatch is not a function
    at AuthService.js:10
    at <anonymous>
```

How can I dispatch an action of vuex in an external js file (not vue component)?

**Comment by clarkdo** [comment]
There is a tricky way but not recommend, you'd better do it inside component 😸 

```js
let store
if (process.browser) {
  window.onNuxtReady(({$store}) => {
    store = $store
  })
}

export default class AuthService {
    static login() {
        store.dispatch('someAction');
    }
}
```

**Comment by kamwing** [comment]
@freevital 
Try this

`
// ~/store/index.js

let store

const initStore = () =>  {
  return store || (store = new Vuex.Store({
   modules: {
     auth,
     contacts,
     identity,
     network,
     nim
   },
   strict: debug,
   plugins: debug ? [createLogger()] : []
  }))
}

export default initStore
`

`
// external js file
import store from '@/store';

export default class AuthService {
    static login() {
        store().dispatch('someAction');
    }
}
`

**Comment by Atinux** [comment]
You can also do this:

```js
export default class AuthService {
  constructor(store) {
    this.store = store
  }
  login() {
    this.store.dispatch('someAction')
  }
}
```

This way, your AuthService can be used with any Vue.js project.

**Comment by SinisaG** [comment]
Be vary here if you use @kamwing suggestion. This can lead to memory leak issues. 

AS the same instance of the store will be shared between all users on server side. That can: 

1) Increase your initial store through time significantly (and initial HTML page rendered, as state is embeded in the template)
2) Expose user sensitive data to people that are not suppose to see it  

I would say, the best option is to use your file as plugin and have access to store there. Or pass it in the reference to the store.

**Comment by VsevolodTrofimov** [comment]
@Atinux but how do you get relevant store when countructuing instance of this service, without getting components involved. 

I.e. I need to propagate some event from web socket to store (including whether it is connected or not). Every page sometimes needs that data, so I'd rather have it as a plugin and read from store in components.
