### ISSUE TITLE
How to get data from local json file using actions and axios.get()?

### ISSUE THREAD

**Issue by juratev** [nuxt/nuxt.js#2006]
I wrote Action, that should get data from db.json file. But I get: "xhr.js:178 GET http://localhost:8083/data/db.json 404 (Not Found)". 
Why is it, if my path is correct (db.json is in the same folder)? 
In profileActions.js:
```
import axios from "axios";
var customData = require('./db.json');

export function fetchUsers(){
    return function(dispatch){
        axios.get('./db.json')
            .then((response) => {
                dispatch({type:'FETCH_USERS_FULFILLED', payload:response.data});
            })
            .catch((err) => {
                dispatch({type:'FETCH_USERS_REJECTED', payload:err});
            })
    }
}
```

**Comment by clarkdo** [comment]
An HTTP request cannot use relative path as you file structure, is's relative to you `baseURL` or `domain`.

```js
const ax = axios.create({
  baseURL: 'http://localhost:3000/data'
})
ax.get('db.json')

//or 

 axios.get('/data/db.json')
```

**Comment by sebastianmacias** [comment]
You could also use the fetch API:

```javascript

  created: function() {
    fetch('data/db.json')
      .then(r => r.json())
      .then(json => {
        this.db = json
      })

And then  access this.db which is now serialized


```

**Comment by AngelicaMDuqueC** [comment]
Also you can use the `the Request() constructor`  and `fetch()` like: 

`var mInit = {  method: 'GET',
               cache: 'default'
              };

var myRequest = new Request('data.json', mInit);

fetch('data.json')
  .then(response => response.json())
  .catch(error => console.log(error));
`

**Comment by JavaMajk** [comment]
If anyone ends up here, I found a solution if you are using create-react-app. 
Got it working by throwing my db.json file into the Public folder and calling it by:
`axios.get('db.json')
  .then(//...)`
