### ISSUE TITLE
SSR render catch ?

### ISSUE THREAD

**Issue by ac88** [nuxt/nuxt.js#2007]
i want to deploy nuxt.js the production code,only include .nuxt and static folder,not full code

a new package.json  a little dependencies .

sometimes Server error

![nuxt_error](https://user-images.githubusercontent.com/20198303/32310615-9298bb4c-bfce-11e7-8cda-decf8c7d3eaf.png)

when the package.json  is full dependencies ,it can be success.

how to catch Server error ?

```javascript
// Give nuxt middleware to express
app.use(nuxt.render)
```

nuxt render only req and res arguments not error

**Comment by clarkdo** [comment]
You can try `debug` mode configured in `nuxt.config.js`, `statusCode` and `message` of error will be shown on browser. 

```js
module.exports = {
  debug: true
}

```
