### ISSUE TITLE
Load video from assets folder

### ISSUE THREAD

**Issue by sdq-sts** [nuxt/nuxt.js#2008]
I'm not able to load a video from `assets` folder, I know this might be solved in #1224. I tried both `~/assets/...` and `~assets/...` but I can't make it work.

My component:

```html
<template>
  <div>
    <video src="~assets/video.mp4">
      <p>Your browser does not support the video tag.</p>
    </video>
  </div>
</template>
```

My assets folder:
![assetsfolder](https://user-images.githubusercontent.com/13650518/32327695-9eb3878c-bfbe-11e7-877a-4f770648dae0.JPG)

Am I doing something wrong?

**Comment by clarkdo** [comment]
`~/assets` should work. Which version of `Nuxt` do you use ?
If it's convenient, would you pleas offer a jsfiddle or demo repo ?

**Comment by sdq-sts** [comment]
Hi, I'm using `1.0.0-rc11`.
I forgot to mention I'm getting the following error in the console:

```
GET http://localhost:3000/~/assets/video.mp4 net::ERR_ABORTED
```

I'm trying to push my code to github, wait a minute.

**Comment by sdq-sts** [comment]
I found a temporary solution and it will do for now. Changed the path from:

```html
<video src="'~/assets/video.mp4"></video>
```

to

```html
<video :src="require('~/assets/video.mp4')"></video>
```

**Comment by clarkdo** [comment]
Issue will be fixed in https://github.com/nuxt/nuxt.js/pull/2016

**Comment by tetreault** [comment]
i tired this @clarkdo and it does not work for me. Nuxt version is `^1.0.0`

**Comment by clarkdo** [comment]
@tetreault 
You can check your vue-loader version, if it's v15, the property has been renamed to `transformAssetUrls`

https://vue-loader.vuejs.org/migrating.html#options-deprecation

**Comment by tetreault** [comment]
thanks for the quick reply @clarkdo will look into that

**Comment by waynelau** [comment]
Just ran into the same issue as well. I'm using nuxt 1.0.0. I wound up using the same workaround for the time being that @sdq-sts posted above (thanks for including this).
