### ISSUE TITLE
Transitions aren't being triggered before asyncData of the next route is finished

### ISSUE THREAD

**Issue by Andrei997** [nuxt/nuxt.js#2012]
I am trying to trigger the leave transition right when the nuxt-link is clicked but the transition gets triggered only after the asyncData of the next route has finished. Is there anyway I can trigger the transitions before that ?

**Comment by Andrei997** [comment]
Never mind I guess I can just apply transitions to whatever elements I want duh

**Comment by Eiskis** [comment]
@Andrei997 looking into this same issue, and I'm not sure if I'm missing something obvious or if this is really tricky to do in Nuxt.

Can you explain how you solved this?
