### ISSUE TITLE
layouts and double initialize component

### ISSUE THREAD

**Issue by Gimanh** [nuxt/nuxt.js#2013]
Hi! 
I use latest nuxt and i have problem with double initialize component which rendering in layout . 
I have layout named "main" and default route ("/") which must rendered in the "main layouts" using component "logreg.vue".
When default route rendering i see 3 initialization logreg.vue component.
<img width="813" alt="screen shot 2017-11-02 at 22 21 32" src="https://user-images.githubusercontent.com/10837815/32346129-682bd886-c01d-11e7-8550-445f7b61be4d.png">
layouts/main.vue
<img width="875" alt="screen shot 2017-11-02 at 22 26 33" src="https://user-images.githubusercontent.com/10837815/32346166-86ac0240-c01d-11e7-9434-cc44b76cbc64.png">
pages/index.vue
<img width="1432" alt="screen shot 2017-11-02 at 22 27 32" src="https://user-images.githubusercontent.com/10837815/32346180-931ee7c2-c01d-11e7-93f3-c1634b0799b0.png">
result after loading page
<img width="680" alt="screen shot 2017-11-02 at 22 32 50" src="https://user-images.githubusercontent.com/10837815/32346270-d98a3fc2-c01d-11e7-82f7-0327f5d297a1.png">
nuxt.config.js
Sorry for concern but did not find a solution to this problem

**Comment by clarkdo** [comment]
Would you mind offering a demo repo, so that we can reproduce the issue ?

**Comment by Gimanh** [comment]
Hi!  I create demo repo https://github.com/Gimanh/handscream_front/tree/nuxt/web .

**Comment by clarkdo** [comment]
sorry, I didn't reproduce this issue, following is the steps:

![image](https://user-images.githubusercontent.com/4312154/32403489-fbaac004-c108-11e7-851e-c44b4982f43c.png)
![image](https://user-images.githubusercontent.com/4312154/32403492-0c279dd0-c109-11e7-9349-2fab609894b5.png)

If I missed anything, pls let me know 😄

**Comment by Gimanh** [comment]
First my error (nuxt-child) was in the main layout, i remove  (nuxt-child) and see only 2 created log.
<img width="361" alt="screen shot 2017-11-05 at 12 01 45" src="https://user-images.githubusercontent.com/10837815/32413446-6c180f4e-c222-11e7-81cb-e9f93a5f3a5c.png">

 Then i comented (mode: 'spa') in nuxt.config.js
<img width="246" alt="screen shot 2017-11-05 at 12 02 57" src="https://user-images.githubusercontent.com/10837815/32413454-a5cf1228-c222-11e7-97cc-0bfa739c3baf.png">

 and see only 1 initialization . 
<img width="340" alt="screen shot 2017-11-05 at 12 10 05" src="https://user-images.githubusercontent.com/10837815/32413471-f97e1ffe-c222-11e7-9487-ccfac7d128dc.png">

Is it possible to use a SPA mode with a layout?

**Comment by Gimanh** [comment]
Sorry i do not know what i am doing wrong ... I reinstalled all node_modules.
Can you give me your nuxt.config.js?

**Comment by clarkdo** [comment]
I didn't change anything in you nuxt.config.js.

**Comment by Gimanh** [comment]
Did your local codes are different from github ? No. Same code from ( https://github.com/Gimanh/handscream_front/tree/nuxt/web/hsnuxt )

Because your github code's layout is not main. What do you mean?

**Comment by Gimanh** [comment]
Here is video https://www.youtube.com/watch?v=Y8VD38WHe0g&feature=youtu.be     :)

**Comment by clarkdo** [comment]
> Because your github code's layout is not main. What do you mean?
I cloned the repo yesterday, but didn't find `layout: 'main'`, I will update the repo and try again

**Comment by clarkdo** [comment]
@Gimanh 
I updated the codes and reproduced the issue, this issue has been fixed in https://github.com/nuxt/nuxt.js/commit/9e4f864e4d25af2e9668767bb297182656e19cba and will be available in next rc release 😸

**Comment by Gimanh** [comment]
Thanks for the help and for NUXT! :)

**Comment by Gimanh** [comment]
Sorry :) But this
if (!path) {
      normalizeComponents(router.currentRoute, router.currentRoute)
      // fixPrepatch.call(_app, router.currentRoute, router.currentRoute)
      mountApp()
      return
    }
is help if i commented (mode: "spa")
I recorded a video with a situation
https://www.youtube.com/watch?v=1rPwJwB85-w&feature=youtu.be

**Comment by clarkdo** [comment]
This is related to https://github.com/nuxt/nuxt.js/issues/1929, will be fix in next release also

**Comment by Gimanh** [comment]
clarkdo thanks, i will wait next release! Have a good day!
