### ISSUE TITLE
Unable to generate static HTML files in SPA mode.

### ISSUE THREAD

**Issue by alexmacarthur** [nuxt/nuxt.js#2015]
I'm trying to generate 100% static HTML files for hosting on Netlify. However, when I run `nuxt generate --spa`, none of my HTML is being prerendered in the body. I'm seeing a bunch of assets in an HTML file per page, but none of my static HTML in the Vue component is being loaded into these files. 

When I run `nuxt generate` with out `--spa`, my pages are generated correctly, but I don't want to run in SSR mode, since my code is very client-side-specific, and I don't want to worry about checking `process.browser` for everything. 

I also tried running `nuxt build --spa`, but got the same undesired result. Am I misunderstanding something here? Basically, I just want all my static Vue component content to be generated into HTML when it can be. 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1790">#c1790</a>)</em></sub></div>

**Comment by KyleTryon** [comment]
I am having a similar issue, it's causing my components to disappear.  https://github.com/nuxt/nuxt.js/issues/2477

**Comment by husayt** [comment]
I got exact same problem and I can see number of issues related to SPAs in the forum. Will be great to address them, as SPAs are only going to become more hot.  Thanks

**Comment by thomasedwards** [comment]
Is there anyway to force specific bits of code to be run in the browser? I know we can check `process.browser`, but if it’s false, I still want that code to run, I just want it to run in the browser.

**Comment by JGJP** [comment]
Forgive me if I'm mistaken, but doesn't SSR mode only run code included in `fetch()` and `asyncData()`?

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.

@JGJP This isn't it, no. In comparison to normal SPAs, SSR will render HTML first and then hydrate it. The best in-depth explanation can be found in [this talk](https://www.youtube.com/watch?v=OF3A_arLJ8k).
