### ISSUE TITLE
Cannot switch custom layouts dynamically

### ISSUE THREAD

**Issue by haoxl3** [nuxt/nuxt.js#2017]
I want to switch the layout by a button, when I press the button, I'm going to put the state in localStorage，e.g  localStorage.setItem('themeFlag',true). then, I'll  get the state in about.vue, but localStorage is not defined,e.g
`export default{
     layout: (function(){
       let themeFlag = localStorage.getItem('themeFlag')
       return themeFlag ? 'vertical':'horizontal'  
    }())
}
`
Then I tried another method, e.g
`let themeFlag = '' 
export default{
  mouted(){
      themeFlag = localStorage.getItem('themeFlag')
  },
  layout:(function(){
     return themeFlag ? 'vertical':'horizontal' 
  }())
}
`
but, in layout, themeFlag is an empty string. I've tried use vuex  store, but in the layou, I still can't get the themeFlag.And finally, I found that layout rendered before beforeCreate.
So, I'm going to set the layout dynamically?
thanks.

**Comment by clarkdo** [comment]
You may take a look at https://github.com/nuxt/nuxt.js/issues/265#issuecomment-291844402
