### ISSUE TITLE
Route change from link stored in DB?

### ISSUE THREAD

**Issue by sbefort** [nuxt/nuxt.js#2018]
I’m confident that this is not possible, but I want to verify.  If a database field contains paragraph content with a link to another page, is there any way to make that link a route change instead of a traditional URL that requires a full page refresh?  I’m assuming no.

**Comment by clarkdo** [comment]
Do you use `<nuxt-link>` or `<router-link>` ? If yes, you can bind dynamic data to the `link`

```html
<nuxt-link :to="linkFrmDB">About</nuxt-link>
```

The `linkFrmDB` can be either from `vuex` `store` or `data`, and fetched from DB in `state` or `asyncData`.

**Comment by sbefort** [comment]
Thanks for the tip.  Unfortunately, the links are contained within rich text paragraphs inside database fields.  So I do not know if there will be links until the data is retrieved from the database.  Ideally, I would like to be able to change the local URLs into <nuxt-link> so they are route changes, but I'm assuming this is impossible.

**Comment by clarkdo** [comment]
You may check https://github.com/vuejs/vue-router/issues/888, using `createMatcher ` may help you.
