### ISSUE TITLE
redirect() not rendering within plugin

### ISSUE THREAD

**Issue by rolandszpond** [nuxt/nuxt.js#2019]
I'm using a non-ssr plugin to check something before redirecting, the only way I can get it to fire is but wrapping a Promise around the function and leaving out the resolve() within the Promise, the url updates, but the redirected page doesn't render, just the previous page...

nuxt.config.js
```
plugins: [
	{ src: '~/plugins/auth', ssr: false }
]
```

plugins/auth.js
```
export default ({ store, redirect, route }) => {
	// doesn't work
	redirect('/admin/login')

	// doesn't work
	return new Promise((resolve, reject) => {
		redirect('/admin/login')
		resolve()
	})

	// works, but only the url updates, the page doesn't render
	return new Promise((resolve, reject) => {
		redirect('/admin/login')
	})
})
```

**Comment by Atinux** [comment]
Hi,

First, why do you want to use it only with ssr: false?

**Comment by rolandszpond** [comment]
@Atinux Well, ultimately, what I've been trying to do is use firebase auth to set the active user to the store before rendering, but, for some reason, auth isn't working on the server side within nuxt itself, it's undefined, but it works only on the client. So far, using "ssr: false" is the only way that I've been able to get it to work..

The different methods that I've been using are the follow:

1) https://www.davidroyer.me/blog/nuxtjs-firebase-auth/
^^ he's using spa mode, which is fine, but it doesn't work when deploying an ssr app to firebase hosting, it'll just timeout

2) https://github.com/nuxt-community/modules/tree/master/packages/firebase
creating a middleware/module/plugin on the server side, all of them do the same thing, it returns undefined, but within the same app, on the client side, the auth user works

**Comment by Atinux** [comment]
I see @rolandszpond 

But this is a "dirty" trick and actually you should not do this, the main point is: how can we make Firebase works on server-side!

To start, I believe this answer could help you to the right track: https://stackoverflow.com/questions/32027369/firebase-auth-state-persists-on-client-but-not-on-hard-refresh

**Comment by Atinux** [comment]
Also, I am pinging @posva which is a Firebase expert :)

**Comment by rolandszpond** [comment]
@Atinux Yes, I agree that this shouldn't be done, but this is my first couple attempts to actually get it working correctly since i haven't been able to find a good resource that explains it yet.

And thanks for the link, I'll take a look! 👍

**Comment by rolandszpond** [comment]
@Atinux @posva Also, if it helps, this is the firebase/nuxt repo that I'm using: https://github.com/davideast/nuxt-firebase

**Comment by posva** [comment]
Sorry for the delay, I don't see any firebase code in the project. Did you find out a solution?

**Comment by rolandszpond** [comment]
@posva I was trying to get firebase.auth() working on nuxt, but I wasn't able to get them to working correctly on both server and client. I haven't revisited the issue just yet, but I think the solution has something to do with generating an auth token and supplying it while requesting auth(), so both the server and client know that they have the same origin.

**Comment by posva** [comment]
ok, good luck 🙂

**Comment by rolandszpond** [comment]
@posva Thanks! I'm gonna take a look at https://github.com/davidroyer/nuxt-ssr-firebase-auth and see if I can consolidate both the repos
