### ISSUE TITLE
Routing Issue - Double Slash doesn't work

### ISSUE THREAD

**Issue by IamManchanda** [nuxt/nuxt.js#2020]
If you type => http://localhost:3000//harry ( This won't work )

**Comment by Atinux** [comment]
Hi @IamManchanda 

It's an intended behaviour, if you want to redirect your users to `/harry`, you can add a `serverMiddleware` in your `nuxt.config.js`:

```js
module.exports = {
  serverMiddleware: [
    (req, res, next) => {
      if (/\/{2,}/.test(req.url)) {
        const url = req.url.replace(/\/{2,}/g, '/')
        res.writeHead(301, { 'Location': url })
        return res.end()
      }
      next()
    }
  ]
}
```

**Comment by IamManchanda** [comment]
@Atinux ... thanks it worked but I can't find this in docs 
I hereby propose this to add in docs

**Comment by Atinux** [comment]
Actually it's an edge case and it's hard to add too many things into the documentation, but thanks to Google and Github, this issue will be indexed for search :)
