### ISSUE TITLE
proposal: Add `sub directory` config in nuxt.config.js

### ISSUE THREAD

**Issue by potato4d** [nuxt/nuxt.js#2021]
Hi, I maintain multiple Web sites with subdirectory structure created by Nuxt.
(e.g. https://push7.jp/docs )

Then, I have a problem with such a site.

Nuxt `build` and` generate` are excellent, but they are always made to refer to the .nuxt directory for the root directory.

I solve this by linking with a shell script etc, but it is not a good idea.

To solve this problem, I would like to add a function that can manage the target directory with the configuration called `subdirectory` as Nuxt's function.

In particular, in Japan such a URL structure is very popular, so there are many opportunities to use.

If this proposal is allowed, I would like to implement it even soon!

## Config sample

in nuxt.config.js

```js
{
  ...
  subdirectory: Boolean | String
  ...
}
```

```js
{
  ...
  subdirectory: false // default
  ...
}
```

```js
{
  ...
  subdirectory: '/blog/'
  ...
}
```

**Comment by christophwolff** [comment]
Have you tried the Vue Router Base Property?

```Javascript
module.exports = {
  router: {
    base: '/app/'
  }
}
```
https://nuxtjs.org/api/configuration-router/

**Comment by KonstantinVlasov** [comment]
I'm not sure if I understand you correctly, but maybe `buildDir` is what you are looking for?
```javascript
buildDir: './nuxt/blog' // default: './nuxt'
```

**Comment by potato4d** [comment]
@christophwolff  @KonstantinVlasov 
Thanks feedback!

But, It seems to be a little different from what I'm seeking.

I need

```
<link href="/blog/_nuxt/manifest.bdb5daca1950a978e030.js" rel="preload" as="script">
```

nuxt generate result
```
<link href="/_nuxt/manifest.bdb5daca1950a978e030.js" rel="preload" as="script">
```

Is it possible to add a path before `/_nuxt` ?

**Comment by KonstantinVlasov** [comment]
I think [publicPath](https://nuxtjs.org/api/configuration-build#publicpath) can help you

**Comment by potato4d** [comment]
@KonstantinVlasov 
I have tried it in the past.
But, It was a little different from what I wanted.

I am hosting another web site directly under the domain and `/docs`.

- https://push7.jp/ Service website.
- https://push7.jp/docs Document site

result:

![screen shot 2017-11-05 at 21 59 17](https://user-images.githubusercontent.com/6993514/32414966-a7e5816c-c274-11e7-83d4-0141ea708c60.png)

I need:

![screen shot 2017-11-05 at 21 59 27](https://user-images.githubusercontent.com/6993514/32414969-aea23464-c274-11e7-9433-b71c567e60ed.png)

**Comment by husayt** [comment]
see https://nuxtjs.org/faq/github-pages and also https://nuxtjs.org/api/configuration-build#publicpath

That should resolve it for you. Closing. Reopen if still not clear.

**Comment by ramjamx** [comment]
I think this proposal is valid and necessary,  you not always want to publish in the root directory, publish path solve the problem but you need to change your image routes. with this helper you may decide where you want to publish (main domain or a folder) with just one config.
