### ISSUE TITLE
How to support gzip when nuxt generate? 

### ISSUE THREAD

**Issue by nameczz** [nuxt/nuxt.js#2024]
I used performance in nuxt.config.js. But it's not userful. 

  performance: {
    gzip: {
      threshold: -1
    }
  }

**Comment by clarkdo** [comment]
GZIP should be supported at server side, such as [niginx](http://nginx.org/en/docs/http/ngx_http_gzip_module.html)

**Comment by nameczz** [comment]
OK，i will try it ! Thanks.
