### ISSUE TITLE
Async load component?

### ISSUE THREAD

**Issue by veresnikov** [nuxt/nuxt.js#2027]
I want load [vue-awesome-swiper](https://github.com/surmon-china/vue-awesome-swiper) full asynchronously (include css) for optimize first time load site (load speed). Exclude plugins, modules, because it loading before site loaded. I need it async,later. How i can do this?

```pug
// TEMPLATE (pug)
no-ssr
        vue-awesome-swiper
```

```javascript
// SCRIPT
  let VueAwesomeSwiper
  if (process.browser) {
    VueAwesomeSwiper = require('vue-awesome-swiper/ssr')
  }

  export default{
    components: {VueAwesomeSwiper}
  }
```

```stylus
// STYLE (stylus)
@import "swiper/dist/css/swiper.css"
```
And how cache it for used on another pages? what problems can there be?

**Comment by clarkdo** [comment]
https://nuxtjs.org/guide/views#default-meta-tags and https://nuxtjs.org/api/configuration-css#the-css-property may help you.

**Comment by veresnikov** [comment]
@clarkdo I need a load component after page loaded. On created () or on demand. For example: index page has component slider, whose use [vue-awesome-swiper lib](https://github.com/surmon-china/vue-awesome-swiper). Page loaded without style and js of vue-awesome-swiper, only site css, on slider space used preloader gif. After that, i need load this slider lib with css and js, slider appears on index page. I need this.

**Comment by clarkdo** [comment]
You can use [`Async Componenst`](https://vuejs.org/v2/guide/components.html#Dynamic-Components) and [`Dyanmic Componenst`](https://vuejs.org/v2/guide/components.html#Async-Components) in Vue.js
```vue
<template>
  <div>
    <component :is="asyncComp"></component>
    <button @click="clickBtn">Click Me</button>
  </div>
</template>

<script>
export default {
  data: () => ({
    asyncComp: ''
  }),
  components: {
    'example': () => {
      import('@/components/example')
    }
  },
  clickBtn() {
    this.asyncComp = 'example'
  }
}
</script>
```

**Comment by clarkdo** [comment]
Have a look at https://github.com/nuxt/nuxt.js/issues/1607 😸

**Comment by EmixMaxime** [comment]
Hi,
@clarkdo it doesn't work for me, I had to return the `import`, example:

```js
    'post-share': () =>
      import(
        /* webpackChunkName: "PostShare" */
        '@/components/Post/Share/Share.vue'
      )
```

I can't find documentation about lazyloading, it's weird.
