### ISSUE TITLE
Question: How to change JS/CSS filenames?

### ISSUE THREAD

**Issue by GustavsR** [nuxt/nuxt.js#203]
Hello,
When I run `npm run build`, the following files are generated:
```
0.nuxt.bundle.js 
1.nuxt.bundle.js  
2.nuxt.bundle.js 
nuxt.bundle.js   
vendor.bundle.js
style.css
```

Some of the files contain `nuxt` in their filenames.
Is there any way to replace `nuxt` set my custom keyword for these files?
If there isn't, it'd be a nice feature.

**Comment by Atinux** [comment]
@GustavsR please take a look at https://nuxtjs.org/api/configuration-build#filenames
