### ISSUE TITLE
webpackMiddleware configuration

### ISSUE THREAD

**Issue by hanxue** [nuxt/nuxt.js#2031]
How do I enable webpack middleware for Nuxt? During development, the build process is slow when writing files to disk, and I wish to use webpack middleware to generate build files in the memory. 

[Nuxt documentation](https://nuxtjs.org/api/configuration-build#devMiddleware) states it is an `Object`. I have tried adding this to my `nuxt.config.js`, but it does not work. 

```
webpackMiddleware: webpackMiddleware(webpack({
    entry: '...',
    output: {
      path: '/'
    }
  }), {
    noInfo: false,
    quiet: false,
    lazy: false,
    watchOptions: {
      aggregateTimeout: 300,
      poll: true
    },
    publicPath: ['/assets/', '/static/'],
    index: 'index.html',
    headers: { 'X-Custom-Header': 'yes' },
    stats: {
      colors: true
    },
    reporter: null,
    serverSideRender: false
  })
```

I would appreciate a working example.

**Comment by clarkdo** [comment]
You can use `extend` to config webpack manually.
Documentation: [Build Extend](https://nuxtjs.org/api/configuration-build/#extend)
Example: [custom-build/nuxt.config.js](https://github.com/nuxt/nuxt.js/blob/dev/examples/custom-build/nuxt.config.js#L10-L17)
