### ISSUE TITLE
How to protect sensitive data in server side without share with client?

### ISSUE THREAD

**Issue by renatomattos2912** [nuxt/nuxt.js#2033]
Hi everyone,

I just begun to use nuxt and is not clear to me what part of the code is shared between client and server and what part belong to each side exclusively. So i'm afraid to put some sensitive data like API credentials and things like that in code cause i dont know where this data will be readable only by server. Can someone help me to organize my code in some way that i can guarantee that the sensitive data will be only readable by server and not exposing on client inside some bundle javascript client side code.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1804">#c1804</a>)</em></sub></div>

**Comment by kkurt** [comment]
Hi renatomattos2912;

I have just begun, too. I have the same concerns with you and i try to find out this.
I use this scenario: I try to crypt some data at server side with the secret key and send data to page.
In vue page's "fetch" property , i crypted the data and try to show in page like :

`<div>{{cryptedData}}<div>`

When i browse the page and view the source (ctrl+shift+F in Chrome and searched the secret key), i could see the secret key! Alos, i tried page middleware but same problem occured...
I want to ask that, is this way is wrong?
Which way we should use for securing our data or private functions on server side?

**Comment by itsacorn** [comment]
I would like to know this too. I need to include some API keys but only on the backend.

**Comment by rosea1** [comment]
Extremely good question, does nuxt not have an answer for this ? im facing same problem

**Comment by mootari** [comment]
From what I've gathered you should be fine when using environment variables that you access via `process.env`, as long as you don't add them to the `env` section of your nuxt config.

Be careful though if you plan to use `.env` files with the dotenv nuxt module instead of using the dotenv package directly: by default the module will add each variable declared inside that file to options.env, thus exposing it to the client.

**Comment by renatomattos2912** [comment]
@mootari thanks, i'm using the dotenv nuxt module, i will try to change.

**Comment by rosea1** [comment]
@mootari , as far as i can see from Nuxt, you cannot have code which is just on the backend and not exposed to the client, unless im mistaken, so even if you retrieve the keys from process.env, they will be in the client side code, for example if your making an axios request when a button is pressed; 

//click event
{
  const credentials = {accessKeyId: process.env.acccessKey};
}
//Then do something with the above credentials

**Comment by mootari** [comment]
If you need to fetch data using that key then you'll have to proxy that through a custom API endpoint. In the examples this is commonly done by running a small express server alongside nuxt.

Regarding unbundled code that interacts with nuxt directly: there's e.g. serverMiddleware, and afaik nuxt.config.js doesn't get bundled either.

**Comment by renatomattos2912** [comment]
Thanks @mootari, i will do some tests

**Comment by krestaino** [comment]
Is it outside the scope of Nuxt for a feature like this?

I've been using a separate Express server alongside of Nuxt to accomplish things like this before, but having that functionality built into Nuxt would be fantastic.

Specifically, I want to be able to consume APIs which need keys without using a separate Express app to handle it.

**Comment by willbrowningme** [comment]
I'm deploying a static site using the `npm run generate` command. I have an .env file with the API key inside. I was previously using the @nuxtjs/dotenv module but as others have said this bundles up the api tokens and exposes them in the app.js client side file, I could see them in plain text.

To solve this I removed `@nuxtjs/dotenv` and instead simply ran `npm install dotenv` from [https://github.com/motdotla/dotenv](https://github.com/motdotla/dotenv) then at the top of nuxt.config.js add:
```
require('dotenv').config()
```
Then I just access all the .env variables using process.env.API_KEY etc. you can access them in nuxt.config.js and all pages.

I've checked all the js bundles etc and can no longer find the secret API key.

**Comment by Imanullah** [comment]
Hai @willbrowningme 

I'v tested it did not work.... I still can see API_KEY on main.js on plain text

**Comment by krestaino** [comment]
@willbrowningme Mind sharing your code? I don't see how that will work as once the Nuxt app is loaded in the browser, it effectively becomes a Vue app, no longer doing any server side stuff. Your API calls will still be processed by the browser after the first visit to your site. Yes, the first page load will be hidden from the user as it's processed on the server, but subsequent calls will be visible by the browser. At that point, you can sniff out those API keys with dev tools.

**Comment by Imanullah** [comment]
it's just working on server side but not client side 
for whom using Firebase/Firestore realtime database will not working... for firebase that found solution is restricted credentials on cloud console

**Comment by willbrowningme** [comment]
@Imanullah @krestaino The static site I've built only makes API calls on the server side using the asyncData method. Example source code can be seen here - [https://github.com/willbrowningme/nuxt-cockpit-static-blog](https://github.com/willbrowningme/nuxt-cockpit-static-blog)

If you're building an SPA that makes client side API calls then you might need to use a different way for authenticating calls.

**Comment by rosea1** [comment]
so iv actually found a way around this. Not the prettiest solution but still works. Have your API credentials and your API call in a server middleware file (not exposed to client at all). Then from your front end where you want to make the API call, you then ONLY call the server middleware API, which will then in turn call the API you want to call, get the data and then return it to the browser.. Hope that makes sense

**Comment by wahengchang** [comment]
really hope nuxt can support such a basic requirement as a SSR framework.

can we have function like `getInitialProps()` of next.js, it does: 
 - doing things before the components mounted
 - support nodejs modules(like fs, request)
 - able to acccess data of express, `req`, `res`
 - not rendering in the browser.

 that is the reason we need SSR.

**Comment by malonehedges** [comment]
I'm specifically looking to have two pages:

1. Login Page
2. Secret Page

Currently, the [Auth Routes](https://nuxtjs.org/examples/auth-routes) example can be easily bypassed by editing the store on the client side. The server doesn't actually protect the data on the server side, and sends the whole `secret.vue` page to the client despite claiming not to do so.

Is there a way to protect whole pages or components from the server side?

**Comment by rosea1** [comment]
why would you ever want to have a page or component "secret" and never sent to a users browser ? this would seem to defeat the whole point of developing a website / webapp ?

**Comment by mathieutu** [comment]
Hi all!
Actually, it's very easy to add some data in server side when fetching api. 

You have to use the [axios module](https://axios.nuxtjs.org/) with [proxy one](https://github.com/nuxt-community/proxy-module). 

See the documentation : https://axios.nuxtjs.org/options.html#proxy

An example of configuration I have: 
```js
{
axios: {
    prefix: '/api/',
    proxy: true,
},
proxy: {
   '/api': {
        target: apiUrl,
        pathRewrite: { '^/api/': '' },
        headers: { 'X-API-KEY': apiKey },
        logLevel: 'debug',
    },
}
```

I let you read the available docs to understand all of that. 😉

**Comment by rosea1** [comment]
yup, seems pretty much the same as the solution i coded. It sends an api request to a url which will return the protected API keys and then makes a concurrent API request with the results (keys) of the previous one

**Comment by mathieutu** [comment]
Outch, nope, it's not the same at all 😅 Here, only one call is made, just all calls are proxyfied. It's a native feature of nuxt.

**Comment by rosea1** [comment]
In my solution, only one call is made from the client. And the serverMiddleware file is effectively the proxy..

**Comment by malonehedges** [comment]
@rosea1 If you look at the linked example, `pages/secret.vue` is a page that is only supposed to be seen if the user has authenticated. The example is called "Auth Routes" (implying authentication is needed for those routes) but the whole `pages/secret.vue` is sent to the client regardless of the user being authenticated.

To clarify, the component shouldn't be sent to the client **unless the client is authenticated**, which is not the case in the example.

**Comment by modermo** [comment]
Awesome. Thanks, I'll check that out.

**Comment by nitwhiz** [comment]
`asyncData` & `fetch` are executed server-side anyway, so why can't we have middleware targetting server-side only in pages?

without these packages compiled into client.js

using lokijs with vue pages would be nice, so server-side handles rendering **and** database, without the massive overhead of using axios and making a whole api-server..

**Comment by manniL** [comment]
https://github.com/nuxt-community/separate-env-module

**Comment by aaronransley** [comment]
> `asyncData` & `fetch` are executed server-side anyway, so why can't we have middleware targetting server-side only in pages?

@nitwhiz I believe that the serverMiddleware bits referenced by @bitk0der should do the trick:
https://nuxtjs.org/api/configuration-servermiddleware#the-servermiddleware-property

**Comment by begueradj** [comment]
Same question(s)

**Comment by shaunc** [comment]
Hmm... so if I have in my store, 
```
async nuxtServerInit() {
  const secret = process.env.secret
  data = await this.$axios.post(... {secret})
  ...
}
```
Will secret be somehow available in the client? (process is not, and `secret` is not present in `context.env`) If not, then this seems simpler than serverMiddleware?

**Comment by wahengchang** [comment]
after using `nuxt` for one year time, I found out the solution. there is no easy way to protect secret data.

 - creating a express router for access protected data `GET /apis/secret`
 - accessing secret data inside asyncData (isomorphic-ly, for both serverside and browser render): 
```js
asyncData: async function ({req, res}){
    const data = await axios(`/apis/secret/${somekey}`)
    return {secret: data.data.secret}
}
```

## Remark

It is impossible to wrap serverside code (Nodejs only) inside `asyncData`, such as 'fs', 'os' modules. As the reason that `asyncData` is also compiled through `webpack` into browser javascript.

**Comment by aaronransley** [comment]
Possibly a helpful gotcha: any files added to the `~/middleware` folder will automatically be compiled into the client bundle, even if they aren't referenced the `~/nuxt.config.js` `router.middleware` array.

This caught me off guard because I was trying to place both route middlewares and server middlewares in the same `~/middleware` folder for organization.

To remedy, I have moved server middlewares to a sibling `~/middleware-serverside` folder and they are no longer included in the client bundle.

**Comment by aaronransley** [comment]
> after using `nuxt` for one year time, I found out the solution. there is no easy way to protect secret data, but express API.

@wahengchang I have had good success using [server middleware](https://nuxtjs.org/api/configuration-servermiddleware#the-servermiddleware-property), which are significantly less complex than defining a custom express API. See [above note](https://github.com/nuxt/nuxt.js/issues/2033#issuecomment-485500712) for gotcha.

**Comment by begueradj** [comment]
server middleware leads to a mess, I will never use it again.

**Comment by manniL** [comment]
While this discussion emerges, I leave a small related blog post here 😉 

https://blog.lichter.io/posts/my-take-on-using-nuxt-with-an-api/

**Comment by begueradj** [comment]
Indeed, your article covers all the available approaches for Nuxt + a REST API. @manniL 
I read that article (and every single word you you wrote on your useful blog)
And [Organize and decouple your API calls in Nuxt.js](https://blog.lichter.io/posts/organize-and-decouple-your-api-calls-in-nuxtjs) is also a very nice one.

**Comment by ChrisDillinger** [comment]
process.env values are only visible to the client if we set a variable that we're sending to the client, correct? Might be a silly question but after reading @rosea1 's comment, I just want to clarify. @rosea1 's comment was giving an example where process.env.<VAR> was being set to a variable that was going to be available on client side, and not suggesting that in general all process.env values are exposed to the client..... right?... please say right

**Comment by youncccat** [comment]
> Hi all!
> Actually, it's very easy to add some data in server side when fetching api.
> 
> You have to use the [axios module](https://axios.nuxtjs.org/) with [proxy one](https://github.com/nuxt-community/proxy-module).
> 
> See the documentation : https://axios.nuxtjs.org/options.html#proxy
> 
> An example of configuration I have:
> 
> ```js
> {
> axios: {
>     prefix: '/api/',
>     proxy: true,
> },
> proxy: {
>    '/api': {
>         target: apiUrl,
>         pathRewrite: { '^/api/': '' },
>         headers: { 'X-API-KEY': apiKey },
>         logLevel: 'debug',
>     },
> }
> ```
> 
> I let you read the available docs to understand all of that. 😉

I have the same problem, but I'm confused about `@nuxtjs/proxy` 
how to import the `apiKey`

**Comment by mathieutu** [comment]
I'm sorry but I'm afraid I don't understand your question. If you don't want to set it explicitly here, you're in a js file, what's the problem of importing a variable in it? Or (better) why don't you use an env var?

**Comment by prashantpalikhe** [comment]
@youncccat The proxy configuration goes in the `nuxt.config.js`.

```JS
// nuxt.config.js

module.exports = {
axios: {
    prefix: '/api/',
    proxy: true,
},
proxy: {
   '/api': {
        target: apiUrl,
        pathRewrite: { '^/api/': '' },
        headers: { 'X-API-KEY': apiKey },
        logLevel: 'debug',
    },
}
```

Then, you can use `[dotenv](https://github.com/motdotla/dotenv)` module to get API key from your `.env` file which you do not check into your version control. Your `nuxt.config.js` will end up looking something like this.

```JS
// nuxt.config.js with dotenv

require('dotenv').config()

module.exports = {
axios: {
    prefix: '/api/',
    proxy: true,
},
proxy: {
   '/api': {
        target: apiUrl,
        pathRewrite: { '^/api/': '' },
        headers: { 'X-API-KEY': process.env.API_KEY },
        logLevel: 'debug',
    },
}
```

This works because:

1. Your `.env` file is not committed to the repository. So it's not public.
2. Because we are using the Nuxt proxy, the client JS does not contain the API key either.

Hope that helps.

**Comment by syskin** [comment]
I'm a bit confused about setting proxy headers. 
If i set my api-key in my proxy headers, so anyone which request my app through the proxy will get the data from my api ?
So if someone want to get the data from my api will use my app proxy to be authorize to access data ?

**Comment by patron** [comment]
I confused so much that there is a lot of workarounds but no working solutions :( @Atinux @pi0 Is there some way to survive?

**Comment by mathieutu** [comment]
@patron I actually really don't see what you need more than all the previous answers. I gave you the code and @prashantpalikhe all the details.

**Comment by patron** [comment]
@mathieutu Hi! Your solution looks good, but what can I do if I need to store credentials in the body of request, not in headers?

**Comment by mathieutu** [comment]
@patron Proxy usage is a shortcut, but you can use a ServerMiddleware to do exactly what you want.
There is an example here https://github.com/nuxt/nuxt.js/issues/2033#issuecomment-418056214, but you can find more on the web I think.

**Comment by patron** [comment]
@mathieutu I'll try to use it, but server middlewares such a messy thing to debug, and there is no more useful examples in the web. Thanks anyway

**Comment by manniL** [comment]
To sum it up:

1. If you want to use secrets on the server-side only, you can use `privateRuntimeConfig` [Further read](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-runtime-config#privateruntimeconfig). Be aware that those values are not accessible on client-side.
2. You can use `serverMiddleware` or a standalone API service to ensure that private keys (e.g. a private stripe key) are kept on the server-side only.
3. In the future you can use [Nuxt functions](https://github.com/nuxt/rfcs/issues/35#issuecomment-767017765)

Closing here but feel free to discuss further 👍

**Comment by dzcpy** [comment]
Actually, how to access privateRuntimeConfig in a serverMiddleware?

**Comment by manniL** [comment]
> Actually, is it possible to access privateRuntimeConfig in a custom serverMiddleware?

Not at the moment, no.

**Comment by patron** [comment]
@dzcpy you can create custom `.server.env` file to hide creds

**Comment by xeniumlee** [comment]
I tried `option.onProxyReq` of `proxy`, which can programmably insert api key according to each htttp request.

**Comment by naczu** [comment]
Actually I read all the comments here. But I couldn't find any solution.

There is a remote api and it needs hmac sha256 key which is generated with secret key and timestamp for each request. 
This header generation should not be seen on client. 

How to add this header to axios for server side calls to the api ?

**Comment by patron** [comment]
> Actually I read all the comments here. But I couldn't find any solution.
> 
> There is a remote api and it needs hmac sha256 key which is generated with secret key and timestamp for each request. This header generation should not be seen on client.
> 
> How to add this header to axios for only server side axios requests ?

You should use server-middleware and you should understand how Express.js server under the hood of Nuxt works. If you need a solution I can put some code example

**Comment by naczu** [comment]
> > Actually I read all the comments here. But I couldn't find any solution.
> > There is a remote api and it needs hmac sha256 key which is generated with secret key and timestamp for each request. This header generation should not be seen on client.
> > How to add this header to axios for only server side axios requests ?
> 
> You should use server-middleware and you should understand how Express.js server under the hood of Nuxt works. If you need a solution I can put some code example

Can you please share the code. That would be amazing. Here I asked this on [Stackoverflow](https://stackoverflow.com/questions/69607582/how-to-add-header-to-axios-on-nuxt-project-for-only-server-side).

**Comment by adnanerlansyah403** [comment]
> so iv actually found a way around this. Not the prettiest solution but still works. Have your API credentials and your API call in a server middleware file (not exposed to client at all). Then from your front end where you want to make the API call, you then ONLY call the server middleware API, which will then in turn call the API you want to call, get the data and then return it to the browser.. Hope that makes sense

But how about restriction on the API? do you give any restriction when some users accessed that api? or just let them in to access it?

**Comment by patron** [comment]
@adnanerlansyah403 with all my respect IDK what to do, that preety old tread :) I suggest first of all to switch from 2.x aaand theoreticaly it's possible (even in 2.x) to add some auth token to any endpoint using Express (or whatever type) middleware but that beyond of task of just hiding creds on servers .envs
