### ISSUE TITLE
Continuous transition page on route

### ISSUE THREAD

**Issue by exdeniz** [nuxt/nuxt.js#2037]
How can I do continuous transition page on route like https://re-invent.vc/ (click 'about us' or 'portfolio'. I try animate page transition, but there is a delay between the transitions, first the current page is moved, and then the next one just slide.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1806">#c1806</a>)</em></sub></div>

**Comment by exdeniz** [comment]
@piyushchauhan2011 i make this site on React, but there were problems with SSR

**Comment by husayt** [comment]
@qm3ster @Atinux  I have seen similar question several times. What is the best way for this?
