### ISSUE TITLE
Static brotli files on production build 

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [nuxt/nuxt.js#204]
Please consider adding generation of static [brotli](https://github.com/google/brotli) files during [production](https://nuxtjs.org/guide/commands/#production-deployment) build
`$ nuxt build`

**Comment by Atinux** [comment]
Hi @OlzhasAlexandrov 

Actually we compress the files on `nuxt generate` with `html-minifier` since the others files are minified already. The files with `nuxt build` will soon be compressed too.

Thanks for your interest!
