### ISSUE TITLE
Browser Back Button calls asyncData on static generated site

### ISSUE THREAD

**Issue by lanbau** [nuxt/nuxt.js#2041]
Background
- I couldn't find anyone that has this issue (correct me if i'm wrong)

When i paste the url (E.g www.url.com/page1) in the browser and press Enter button, the page loads fine and there were no network calls.

When i visit the homepage (www.url.com) and click on Chrome browser "Back" button, the page takes longer to load and the network logs show that asyncData was called as i can see my apis in asyncData in the network log.

- Is this a known behaviour of nuxt or vue-router? 
- And how can i stop this unnecessary load for a static generated site?

**Comment by alexchopin** [comment]
Hi @lanbau,
This is a known and normal behaviour because your app is served as a static page on the first browser load, then it's a Vue.js App!
As a Vue.js App when a route changes the browser is not refreshed.
That's mean your asyncData methods will be called on each changing routes.

**Comment by lanbau** [comment]
Thanks @alexchopin. I fixed my issue by changing the links from <nuxt-link> to <a>. 
I was expecting from a static site which is: 
- asyncData is only called once during npm run generate
- only Vue lifecycle methods (e.g. created) load when route changes
