### ISSUE TITLE
I need access to the req.user and req.ip when using asyncData

### ISSUE THREAD

**Issue by JohnL3** [nuxt/nuxt.js#2048]
Im using asyncData to fetch information from database so that it is rendered serverside ....  the information is used to create a chart and show votes on the chart by users.
if user hasnt voted on chart they have the option to vote through a dropdown select.
The problem is if the user has voted i need to be able to check req.user.username /or for not logged in users req.ip against a array of users that have voted allready ... but with asyncData i can get all the information before render eg name of chart, options to vote for , array of people who have voted .... but cant check against req.user.username (as asyncData dosent give me a req.user when request being made ) before render .... so if someone is logged in i have to wait for the page to render then check the store for the logged in user and then compare this to the voters and then disable the option to vote if they have voted.
If i go the other way and wait till page loads and then send a axios request for the same information i do get access to the req.user ...... but it would be of far more benefit to be able to have this pre render.

**Comment by Chathula** [comment]
use fetch method. you can access req object inside fetch method

https://nuxtjs.org/api/pages-fetch/

```js
async fetch ({ store, req }) {
    // do stuff
  }
```

these things can be accessed inside fetch method!

https://nuxtjs.org/api/context

**Comment by JohnL3** [comment]
Unfortunately not working for me 
`   async fetch ({store, req, params}) {`
      `let {data} = await axios.get(`http://localhost:3000/api/test`+'/'+ params.Hd)
    },
`
from the route i set variables and console out response

`console.log('in the get poll by id Test route ');`
   ` let ip = req.ip;`
   ` let User;`
    `if(req.user)  User = req.user;`
    //let user;
    //let voters;
    let ThisPoll = req.params.pollId;
    //let voted = false;
    console.log(ip,User,ThisPoll)
    console.log('params ',JSON.stringify(req.params))`

And this is the log i get
in the get poll by id Test route
::ffff:127.0.0.1 undefined 59fb59feefe8cd11e841fa37
Req  {"pollId":"59fb59feefe8cd11e841fa37"}

the ip should be ::1 but using fetch or asyncData i always get ::ffff:127.0.0.1 unless i send axios request from client side 
And req.user still coming back undefined (Had logged in for this test)
on client side i have access to getters getauthUser to get the user from the store where name is stored when logged in.
Just not understanding why its so easy to get req.user from the client using  axios side but im finding it impossible using fetch or asyncData
`

**Comment by JohnL3** [comment]
Ok sorted .... i was checking in the wrong spot for the req .... when i thought fetch wasnt working went back to asyncData and added the req .... and did a check in the route for req.user which came back undefined ..... Then decided to console.log(req.user) from asyncData to see if it was being sent and got a print out so knew it was .... so i was wondering what am i doing wrong.
Woke up this morning and realized i wasnt meant to check in the route but that when i got the response back then is when i had access to the req.user .... so here is where i check if user has voted then i return data and set voted to true or false then it renders page.
Feeling a bit stupid but dont mind as i got it sorted and understand the process a bit better.

``async asyncData({ store, **req**, params}) {``
  ``  // We can use async/await ES6 feature``
    let { data } = await axios.get(`http://localhost:3000/api/test/${params.Hd}`);
    console.log(data); // **Got data back here**
    **console.log(req.user) // lol had access here**
    return { 
      }
    },``
