### ISSUE TITLE
TypeError: 'inject' is not a function

### ISSUE THREAD

**Issue by pauldariye** [nuxt/nuxt.js#2049]
I'm essentially trying to do what @Atinux recommended in #1697 but I keep getting this error:

`TypeError: inject is not a function`

**Comment by clarkdo** [comment]
Did you declare the `inject` param on you plugin ?
```js
export default ({ req }, inject) => {
}
``

**Comment by pauldariye** [comment]
Yes, I did. Exactly like was recommended in #1697 and similar to the [cookies example](https://github.com/nuxt/nuxt.js/blob/dev/examples/with-cookies/plugins/cookies.js)

**Comment by clarkdo** [comment]
Which version of nuxt did you use? `inject` is introduced from 1.0.0-rc7.
And is it convenient for you to offer a repo which can reproduce your issue? Thanks.

**Comment by pauldariye** [comment]
Got it to work. Thanks @clarkdo.
