### ISSUE TITLE
Preloader?

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt/nuxt.js#2052]
Hi,

Just wonder if there is any recommended way of showing a preloader/animation when loading a nuxt application? If it was a regular website I would hide it on window.load for example.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1822">#c1822</a>)</em></sub></div>

**Comment by koddr** [comment]
Hello.

I think you search for this docs: https://nuxtjs.org/api/configuration-loading

**Comment by iamdubx** [comment]
@koddr this is loader, not preloader.
@jesperlandberg you can just use `mounted` hook.
