### ISSUE TITLE
How to configure Visual Studio Code to insert space before function parenthesis

### ISSUE THREAD

**Issue by massimilianomarini** [nuxt/nuxt.js#2053]
Hi,

I've created a new Nuxt project using the Nuxt starter template

```
$ vue init nuxt-community/starter-template nuxt-project
$ cd nuxt-project
$ code .
```

This is what I want `async asyncData () {}`

But when I hit save, VSC continue to remove the space before function parenthesis

```js
<script>
export default {
  async asyncData() {}
}
</script>
```
I've installed only two VSC extensions
- ESLint 1.4.3
- Prettier - JavaScript formatter 0.24.0
- Vetur 0.11.0

And this is my user settings file

```json
{
  "telemetry.enableCrashReporter": false,
  "telemetry.enableTelemetry": false,
  "window.zoomLevel": 0,
  "workbench.colorTheme": "Quiet Light",
  "editor.minimap.enabled": false,
  "editor.fontSize": 12,
  "editor.tabSize": 2,
  "editor.lineHeight": 20,
  "editor.formatOnSave": true,
  "files.trimTrailingWhitespace": true,
  "javascript.format.insertSpaceBeforeFunctionParenthesis": true
}
```

What I'm doing wrong?

**Comment by clarkdo** [comment]
Do you install `prettier` plugin ? If yes use this config `"prettier.spaceBeforeFunctionParen": true`

**Comment by DaxChen** [comment]
What does this have to do with nuxt?

**Comment by massimilianomarini** [comment]
Sorry @DaxChen, you are right but there are many devs that are using Nuxt with VSC and I hope to find an answer here, so to close fast as possible this inappropriate issues.

**Comment by massimilianomarini** [comment]
@clarkdo I've installed the `prettier`plugin, but in the config `"prettier.spaceBeforeFunctionParen": true` doesn't exists :\

**Comment by iamdubx** [comment]
This issue has nothing with Nuxt. What was you thinking when creating this?

**Comment by iamdubx** [comment]
> What I'm doing wrong?

Well, you start this issue in wrong place :smile:

**Comment by BruceHem** [comment]
@massimilianomarini use prettier wither prettier eslint, it worked for me.

```json
{
  "stylusSupremacy.insertColons": false,
  "stylusSupremacy.insertSemicolons": false,
  "stylusSupremacy.insertBraces": false,
  "eslint.validate": ["javascript", "javascriptreact", "vue"],
  "editor.tabSize": 2,
  "prettier.tabWidth": 2,
  "prettier.useTabs": false,
  "prettier.singleQuote": true,
  "prettier.semi": false,
  "prettier.eslintIntegration": true,
  "vetur.format.defaultFormatter.html": "js-beautify-html",
  "vetur.format.defaultFormatter.js": "vscode-typescript",
  "vetur.format.defaultFormatter.stylus": "stylus-supremacy",
  "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    ".vscode": true,
    "node_modules": false
  }
}

```

**Comment by massimilianomarini** [comment]
> Well, you start this issue in wrong place 😄

Sorry @iamdubx you're absolutely right! :)

**Comment by massimilianomarini** [comment]
@BruceHem I will try, thanks a lot! 👍
