### ISSUE TITLE
vuex modules error unknown action type

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#2054]
I have used vuex mudules  but when i used in page dispatch the action that defined in the module,this error happend: unknown action type. then, i change the action to be defined in index.js, it works correctly.
so,what happend?

**Comment by pauldariye** [comment]
Can you post snippets of the code @ouyangxiaoai?

**Comment by ouyangxiaoai** [comment]
directory: ![image](https://user-images.githubusercontent.com/27655473/32586893-55febfa2-c540-11e7-865f-6778b8b0154d.png)
example.js: 
![image](https://user-images.githubusercontent.com/27655473/32586943-a936249e-c540-11e7-90c2-d0e3870abf79.png)
index.vue: 
    @@@@![image](https://user-images.githubusercontent.com/27655473/32586966-d74cd440-c540-11e7-9dc4-31552e051fc4.png)

**Comment by ouyangxiaoai** [comment]
@pauldariye

**Comment by clarkdo** [comment]
try `dispatch('example/getExampleList')`

**Comment by ouyangxiaoai** [comment]
@clarkdo wow~ it works! thanks a lot!
