### ISSUE TITLE
plugin.apply is not a function

### ISSUE THREAD

**Issue by joshua1** [nuxt/nuxt.js#206]
Hi @Atinux Thanks for your help with my previous feathers-primus issue, i have one past that. however, i ran into the below 
<img width="1371" alt="screen shot 2017-02-05 at 11 18 13 am" src="https://cloud.githubusercontent.com/assets/557293/22625088/17f56038-eb95-11e6-8ec8-901c5d5a53b0.png">

I also wished to ask if Hot module reload works with the ```with feathers``` example as i am using that as a startup template but HMR doesn't seem to work

**Comment by Atinux** [comment]
Hi @joshua1 

When did this error happen? I need to know what code you added for this error to come up to help you.

**Comment by joshua1** [comment]
I only just added my Vue-feathers related code from [here](https://github.com/nuxt/nuxt.js/issues/199) in a browser block since the previous error there was as a result of trying to create as a server/client side plugin . here 
```
import Vue from "vue";
//import Primus from 'primus/primus';
import VueFeathers from "vue-feathers";
import feathers from "feathers/client";
import rest from 'feathers-rest/client';
import rx from "feathers-reactive";
import RxJS from "rxjs";
import authentication from 'feathers-authentication-client';
import feathersPrimus from "feathers-primus/client";
import axios from 'axios';
if (process.BROWSER_BUILD) {
  const primus = new Primus(process.env.baseUrl, {
    timeout: 40000
  });

  feathersClient = feathers()
    // .configure(feathers.authentication({
    //     storage: window.localStorage
    // }))
    .configure(rx(RxJS))
    .configure(feathersPrimus(primus))
    .configure(rest(process.env.baseUrl).axios(axios));



  Vue.use(VueFeathers, feathersClient);
}
```

**Comment by Atinux** [comment]
Can you try to isolate which line create this error by adding them 1 by 1?

**Comment by joshua1** [comment]
@Atinux I was able to sort it out by taking out all plugin reference in nuxt.config and added them one at time. narrowed down the issue to the Vue-awesome plugin. sorted now. Thanks a lot
