### ISSUE TITLE
Stop nuxt generate if there is an error in render

### ISSUE THREAD

**Issue by antonelepfl** [nuxt/nuxt.js#2061]
Hi,

I would like to know if I can stop the generation if I have some render errors while I'm doing `nuxt generate`.

I have a jenkins plan that triggers this generation but even though these render errors appears the plan finishes successfully.

Stefano

**Comment by clarkdo** [comment]
Indeed, generation will be successful even error occurred as you said, I will discuss this with teams and figure out an appropriate way to solve it 😄

**Comment by clarkdo** [comment]
This issue is due to `renderToString` doesn't support `promise`, so `renderer`  missed error.
Now `Vue 2.5.0` has improved this([relate-notes](https://github.com/vuejs/vue/releases/tag/v2.5.0)), so your issue will work in next Nuxt.js release.

**Comment by antonelepfl** [comment]
Great thank you so much for the hard work.
