### ISSUE TITLE
How to implement redirection to a page that the user had previously, if the page to which he passed does not exist

### ISSUE THREAD

**Issue by Jussiadev** [nuxt/nuxt.js#2063]
If suddenly the user goes to a nonexistent url, you need to implement the redirect to the page
which the user had before. How can I do that?

**Comment by iamdubx** [comment]
What do you mean? No redirect at all?

**Comment by Jussiadev** [comment]
@iamdubx I do not understand how to do redirection. I need the last visited page to be stored for example in LocalStorage, and if the user has parented to a nonexistent page, he should be redirected to the page that is stored in the LocalStorage

**Comment by KonstantinVlasov** [comment]
In the browser you can return to the previous page with: `window.history.back()`

**Comment by Jussiadev** [comment]
@KonstantinVlasov And at what state to call this function?

**Comment by alexchopin** [comment]
Simply use this code provides by vue-router [documentation](https://router.vuejs.org/en/essentials/navigation.html): 
```this.$router.go(-1)```
