### ISSUE TITLE
Directive issue on static deployment with SPA mode and zeit.co/now

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#2066]
Hello,

I am facing following issue after build and upload the static assets of the `dist` directory with zeit.co/now service:

On page reload all pages are simply not available, because they are called like:
* domain.com => not found
* domain.com/some-folder => not found

I need to explicit set 
* domain.com/
* domain.com/some-folder/
To make the pages load correctly.

Is there some option missing in the Nuxt config to make this work? I now changed back to `npm` mode of the deployment to make it work again but curious why this issue occurs.

**Comment by clarkdo** [comment]
You may have a look at https://github.com/nuxt/nuxt.js/issues/721 and https://github.com/nuxt/nuxt.js/pull/2032 firstly 😃

**Comment by dohomi** [comment]
Looks like the PR would solve it. Thanks @clarkdo I overlooked that in my search
