### ISSUE TITLE
Nuxt Generate Broken?

### ISSUE THREAD

**Issue by ZebTheWizard** [nuxt/nuxt.js#2068]
When I run `npm run generate` I keep getting a what looks like a false positive? It says that it can't find a file called `dist/index.html`.  I've have tried deleting node_modules, .nuxt, dist, & package-lock.json. Unfortunately, nothing seems to work. I also updated all the npm packages.

**Comment by clarkdo** [comment]
It's better to offer a repo can reproduce your issue 😸

**Comment by ZebTheWizard** [comment]
https://github.com/iOSHaven/v3

**Comment by clarkdo** [comment]
https://github.com/iOSHaven/v3/blob/master/store/index.js#L16-L21
`nuxtServerInit` only works with server, so you can remove it.
