### ISSUE TITLE
how to customizing variables bootstrap4

### ISSUE THREAD

**Issue by dvgamer** [nuxt/nuxt.js#2069]
https://v4-alpha.getbootstrap.com/getting-started/options/

nuxt.config.js
```
    css: [
      'bootstrap/scss/bootstrap.scss',
      '~/styles/index.scss',
      'bootstrap-vue/dist/bootstrap-vue.css',
    ],
    plugins: [
      '~/plugins/bootstrap-vue.js'
    ],
```

and how to add  bootstrap-loader?
```
require('bootstrap-loader?bootstrapPath=/path/to/bootstrap');

// or

entry: [ 'bootstrap-loader?bootstrapPath=/path/to/bootstrap', './app' ]
```

**Comment by clarkdo** [comment]
Tips: You can refer this doc [bootstrap-vue](https://bootstrap-vue.js.org/docs/#nuxt-js) to integrate bootstrap-vue.

**Comment by dvgamer** [comment]
Yes, I added it and it works. But I need customizing bootstrap variables.

**Comment by clarkdo** [comment]
Have a look at https://github.com/bootstrap-vue/bootstrap-vue/issues/690, hope it can help you 😸

**Comment by dvgamer** [comment]
it works. Thank you

**Comment by duythang** [comment]
Dear @dvgamer 

Can you share your configuration based on bootstrap-vue/bootstrap-vue#690 to apply in Nuxt ?

Thanks

**Comment by dvgamer** [comment]
Sure, @duythang 

### Bootstrap-Vue Customizing variables for nuxtjs

```bash
npm i bootstrap@4 bootstrap-vue
npm i --save-dev node-sass sass-loader
```

nuxt.config.js 

```js
  css: [
    'styles/index.scss',
    'bootstrap-vue/dist/bootstrap-vue.css'
  ],
  plugins: [
    'plugins/bootstrap-vue.js'
  ],
```

styles/index.scss
```scss
@import 'bootstrap_variables.scss';
@import '~bootstrap/scss/bootstrap.scss';
```

styles/bootstrap_variables.scss
```scss
// https://v4-alpha.getbootstrap.com/getting-started/options/
$grid-columns:  12;
```


plugins/bootstrap-vue.js
```js
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue)
```

**Comment by duythang** [comment]
@dvgamer : Thank you so much ^^

**Comment by dagoss** [comment]
@touno-project This doesn't seem to make Bootstrap variables available in components/layouts/pages. Is there a way to access things like `theme-color('primary')` in (for example) layouts/default.vue without importing bootstrap our my custom scss file into *every* location where I want to access scss variables/mixins?

**Comment by touno-project** [comment]
@dagoss I think that would not be possible.

**Comment by enriquesoto** [comment]
I didn't include it as a plugin (plugins/bootstrap-vue.js) and worked well
