### ISSUE TITLE
Feature: Set serve-static options in nuxt.config

### ISSUE THREAD

**Issue by homerjam** [nuxt/nuxt.js#2073]
This would enable us to configure the headers directly rather than using current workaround of secondary serve-static middleware. Will submit a PR when I can!

**Comment by clarkdo** [comment]
In `nuxt.confg.js`, `render.static` is the configuration of `serveStatic`.

https://github.com/nuxt/nuxt.js/blob/dev/lib/core/renderer.js#L251

**Comment by homerjam** [comment]
😳

Thanks, I somehow missed that!
