### ISSUE TITLE
upgrade mime to 2.0.3

### ISSUE THREAD

**Issue by Prozi** [nuxt/nuxt.js#2074]
https://snyk.io/vuln/npm:mime:20170907

**Comment by pi0** [comment]
Hi @Prozi. Thanks for your alert. Nuxt doesn't directly requires mime. But its dependencies do:

- postcss-url
- serve-static > send
- url-loader

And unfortunately one of them requires 1.4.1 which is affected too 😕 

We'll keep this issue open and marked as bug until a fix arrives.

**Comment by yashha** [comment]
Regex issue should be fixed with #2155
