### ISSUE TITLE
Vue plugins with generic vue versions causing issues

### ISSUE THREAD

**Issue by robyedlin** [nuxt/nuxt.js#2079]
Some Vue plugins are causing version mismatch issues with vue, vue-template-compiler, and vue-server-renderer

e.g. https://github.com/Inndy/vue-clipboard2/blob/master/package.json#L28

Is there a recommended way to guarantee the Nuxt version of these packages without having to manually specify the vue versions in `package.json`?

**Comment by clarkdo** [comment]
you may add `vue` into dependencies manually.
```
dependencies: {
  "vue": "~2.4.4"
}
```

Nuxt.js will bump `vue` to `2.5.x`, this issue will be resolved.

**Comment by manico** [comment]
> Nuxt.js will bump vue to 2.5.x, this issue will be resolved.

Do we know when will this happen?

**Comment by clarkdo** [comment]
@manico 
We are working on it, about the details, pls refer: https://github.com/nuxt/nuxt.js/issues/2142
