### ISSUE TITLE
How to add an alias for a route?

### ISSUE THREAD

**Issue by luminarious** [nuxt/nuxt.js#208]
I tried to follow the docs and add a custom route, but looks like it's in conflict with the nuxt-created route. What would be the correct way to get a route with an optional parametre?
```
router: {
	extendRoutes(routes) {
		routes.push({
			name: 'post',
			path: '/posts/:id',
			alias: '/posts/:id/:slug?',
			component: '~pages/posts/_id.vue'
		})
	}
}
```

**Comment by Atinux** [comment]
Hi @luminarious 

You can create this page: `pages/posts/_id/_slug.vue`

![screen shot 2017-02-07 at 11 06 58](https://cloud.githubusercontent.com/assets/904724/22686736/951fe632-ed25-11e6-806c-2e436bc70973.png)

Then nuxt.js will create this route:
```js
{
  path: "/posts/:id?/:slug?",
  component: _1c98e79a,
  name: "posts-id-slug"
}
```
