### ISSUE TITLE
generate stops at "generating routes". No errors.

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt/nuxt.js#2080]
So I'm trying to generate my application but It stops/finishes at "generating routes". There are no errors it just stops and quits the process:

```
  nuxt:generate Destination folder cleaned +0ms
  nuxt:generate Static & build files copied +128ms
Generating routes

C:\Program Files (x86)\Ampps\www\site>
```

Any idea what could cause this or how to debug it?

**Comment by clarkdo** [comment]
Can you offer a repo can reproduce the issue ?
