### ISSUE TITLE
`npm run generate` throws an error

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2082]
When I ran `npm run generate` it starts to throw an error. A few days ago everything worked fine. 

![error](https://user-images.githubusercontent.com/30086515/32690281-65245180-c6c2-11e7-86c9-d0aa5fd494b1.png)

What can be wrong?

`npm run build` works fine.

**Comment by clarkdo** [comment]
You could have a look at https://github.com/nuxt/nuxt.js/issues/2068, if it can't resolve your issue, pls offer us a repo which can reproduce issue 😃

**Comment by iamdubx** [comment]
@clarkdo I doesn't use `store` and `asyncData` anywhere in this project. It was working fine a week ago. There wasn't much updates after that...

**Comment by iamdubx** [comment]
Oh, I found the issue. It was `middleware`! Case closed :smile:
