### ISSUE TITLE
Removing Json Data from Html

### ISSUE THREAD

**Issue by OrkanCom** [nuxt/nuxt.js#2083]
Hello, I'm new to nuxt.js. I'm not pretty sure how nuxt works but I have only one question for this good framework.

I want use vue.js and server side rendering; So I prepared an example with nuxt-starter-template.
But I have a problem;

I don't want to embed my json data in html(s);
![nuxt haberler - source](https://user-images.githubusercontent.com/13241853/32691505-743d8478-c719-11e7-9a97-abf1b514849a.png)

Since this app will be a small newsletter website, I don't want to share the json data ( ofcourse they can crawl the website but embeding data to html(?), it's like I'm making it easy to crawl. ). 

So is there any way to delete/hide this json data but still get rendered html ?

Thanks, 
Bests regards...

**Comment by clarkdo** [comment]
The data is from [Server Data fetching](https://ssr.vuejs.org/en/data.html), if you don't want to pre-fetch date in server side, you can put data fetching codes in `mounted`, `beforeMount` or some other lifecycle methods which will not be called in ssr.

**Comment by DreaMinder** [comment]
If that JSON data is required for SSR, you still have to fetch it with asyncData and it should be in your site for client hydration. Inline JSON object saves you extra requests that you have to make on client for hydration. And, as far as I know, in current implementation of nuxt.js, there is no  way to get rid of it.
What can we implement to overcome this? 
1) When client app inits, we make same API requests as in SSR. Lots of problems here: performance decrease and if API content changes between ssr-made request and client-made request, there will be hydration error.
2) Generate your site statically and cache API requests as payload. It can be already achieved but you will have to generate static files every time API content changes. I didn't use it yet, so I may be wrong.
3) While making SSR, to create two separate resources: html page and payload. Payload may be fetched using server push to make performance even better. But it sounds like hard to implement.

**Comment by clarkdo** [comment]
As @DreaMinder said, if you skip server side data fetching, it will lead to a hydration error, vue will give a warning.

**Comment by KonstantinVlasov** [comment]
Hi, guys! Just curious, is it possible to move this JSON to application bundle? Then we can greatly reduce HTML size and the page will be loaded much faster. 
For example, some of my pages have:
clean HTML: 5kb
CSS: 15kb
JSON: 80kb

The user should download 100kb to see the initial page. If we move JSON to bundle, then it will be 20kb.

**Comment by DreaMinder** [comment]
@KonstantinVlasov Possible but pointless. Bad solution.
JSON is different for every dynamic route. If you site is bigger then 2-3 pages, then JSON payloads of different pages will be stored in one file.
B-sides bundle is for code, not for data. 
If you want to store JSON separately from html, read my previous comment.

**Comment by AleksejDix** [comment]
you can just search for RegEx in generated html ``` (data-n-head-ssr|data-n-head=""|data-n-head="true"|data-n-head="class"|data-server-rendered="true"|<link.*?rel="(prefetch|preload)".*?>|<script.*?src="/_nuxt.*?".*?>.*?</script>|<script\s*type="text/javascript">(.|\r|\n)*?window\.__NUXT__(.|\r|\n)*?</script>) ``` and replace it with nothing

**Comment by qm3ster** [comment]
@KonstantinVlasov @clarkdo It's already at the end of the html, but if it's an inline script we can't defer it.
Maybe that's a good enough reason to break it out into a separate file?

**Comment by DreaMinder** [comment]
It would be really nice to implement JSON payload in separate file, at least for nuxt generate.
1. In some cases window.NUXT object is huge. And for some crazy reasons I don't I want search bot to crawl my site with JSON bloat.
2. Moving JSON to separate file will decrease time to first paint. 
3. If I use "nuxt generate" to generate static cache of dynamic site, data of SSR-version may become incostistent comparing to SPA-version. Because pre-generated SSR-markup based on data fetched at the time of generation and SPA-verstion always gets fresh data from API. Having payload JSON files behind .html files, would make possible SPA version to always get the same data as pregenerated files (even if it outdated compared to API).
4. If I use Nuxt as a static generator with dynamic routes, I still should run API server? Separated JSON payload file would solve this issue, coz SPA-version could use this file instead of API.

**Comment by qm3ster** [comment]
Noticed something else here, it's not great that it's JSON encoded. It's a lot of extra symbols such as quoting everything.
And yet it is then parsed inline as JS.
It should either be:
- a string that's `JSON.parse`d on next frame (better in a custom tag and not a `<script>window.obj="stringue"</script>` notation to avoid all parsing)
- a JS object without those superfluous symbols
- an external json indeed (possible optimisation is HTTP/2 push)
- a JS module that's `import()`ed asynchronously :thinking: (HTTP/2 push again)
