### ISSUE TITLE
[Question] Nuxt way for local and social authentication

### ISSUE THREAD

**Issue by Syffs** [nuxt/nuxt.js#2085]
I have 2 options in mind: 

1. setting up my own oauth2 server with oauth2orize, but it seems a bit overkill and I'm still a bit lost on how to set this up

2. Performing initial auth with passport-local/passport-facebook to issue a jwt used to authenticate each request with passport-http-bearer

I'm really wondering what is recommended with Nuxt?

**Comment by renztoygwapo** [comment]
any feeback on this one ?

**Comment by clarkdo** [comment]
@Syffs @renztoygwapo 
Really sorry for the late reply.

I am not an expert in social auth, but you may have a look at:
https://github.com/nuxt-community/auth-module/tree/dev/examples/demo
https://github.com/tomgreener/nuxt-passport-facebook-authentication

If the repos don't solve your problem, maybe @pi0 can help you on this issue.

**Comment by Syffs** [comment]
@renztoygwapo @clarkdo I implemented [this](https://github.com/Syffs/auth-module/tree/api-auth) based on [auth-module refactoring](https://github.com/nuxt-community/auth-module/tree/dev) from @pi0 

IMO, at the moment it's only ok for prototyping as auth-module still presents some issues (client-side cookies, token expiration, etc...)

**Comment by renztoygwapo** [comment]
awesome., I will try this :)

**Comment by clarkdo** [comment]
So I will close this issue, but if you have any further questions, feel free to leave comments here. 😸

**Comment by renztoygwapo** [comment]
I @Syffs I tried to cloned it, but it doesnt run well there is an issue on bootstrap-vue ?

Does it need a nuxt applications and will just import it via module ? or it will run sttandalone ?
if so, how I can import it ? 
here;s the error. 
![image](https://user-images.githubusercontent.com/4898681/37649132-dfd297ac-2c6b-11e8-994c-b88fe98c4693.png)

**Comment by Syffs** [comment]
@renztoygwapo what did you do exactly?
I've just tried this
```
git clone git@github.com:Syffs/auth-module.git
git checkout api-auth
yarn
yarn dev
```
result looks good:
```
yarn run v1.5.1
$ nodemon --watch api --exec "nuxt examples/demo"
[nodemon] 1.17.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: api
[nodemon] starting `nuxt examples/demo`
[HPM] Proxy created: /api  ->  http://localhost:3000
  nuxt:axios BaseURL: http://localhost:3000/ (Browser: /) +0ms
  nuxt:build App root: /home/jbessaguet/WebstormProjects/auth-module/examples/demo +0ms
  nuxt:build Generating /home/jbessaguet/WebstormProjects/auth-module/.nuxt files... +1ms
  nuxt:build Generating files... +53ms
  nuxt:build Generating routes... +8ms
  nuxt:build Building files... +42ms
  nuxt:build Adding webpack middleware... +895ms
  ████████████████████ 100% 

Build completed in 6.237s



 DONE  Compiled successfully in -4758ms                                                                                                                                                             19:30:54


 OPEN  http://localhost:3000
```
