### ISSUE TITLE
Feed the store with window data on application start

### ISSUE THREAD

**Issue by tsimenis** [nuxt/nuxt.js#2086]
Hey there, 

I am setting some values on my store based on the window width. At the moment I am doing this from my layout, with a mounted function and then also attaching a resize listener to update these.
One example is setting isMobile based on the window width. 
Then I have components or computed properties which depend on isMobile, this works but there is a small delay because it seems that the value is assigned a bit late. 

My thought was to get the window width before my application starts and then somehow pass it to the store.

I tried with a plugin like this:

`export default ({store}) => {
  if (process.browser) {
    let ww = window.innerWidth
    store.commit('IS_MOBILE', ww < 768)
  }
}`

but I get these errors:

<img width="717" alt="vue-error" src="https://user-images.githubusercontent.com/5978397/32699429-c63a0c46-c7b5-11e7-8b98-fca14649d67d.png">

Maybe I'm thinking it in the wrong way? Any help appreciated.

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/issues/2083#issuecomment-343731230

**Comment by tsimenis** [comment]
Well as I said above at the moment I am getting the window data on the mounted hook of my default layout. But that is too late, or at least I believe there should be a better way. 

I can get window.innerWidth way before starting the Nuxtjs application so what I want is to initialise with these data.

My second error is happening only when I use the above code in the plugin, my vue version is already 2.4.4

**Comment by clarkdo** [comment]
Can you offer a repo which can reproduce issue ?

**Comment by tsimenis** [comment]
@clarkdo I created one for you: https://github.com/tsimenis/nuxtjs-error

**Comment by clarkdo** [comment]
The `<h1 v-if="isMobile">You are viewing mobile</h1>` is depended on `window.innerWidth` which is only in browser.

So when `isMobile` is true, ssr and csr(client side rendering) will mismatch, so error occurred, you cant wrap `h1` with `<no-ssr>` to avoid ssr.

```html
<no-ssr><h1 v-if="isMobile">You are viewing mobile</h1></no-ssr>
```

**Comment by tsimenis** [comment]
Maybe I am understanding wrong. 

I know that window exists only in the browser. The no-ssr does not help me, I am using this isMobile value to perform much more, also other computed are depended on this.

Again if I get the `window.innerWidth` in the mounted hook as you can see in the repo, everything works fine. 
It's just that there is a visible switch in some cases because isMobile mutates later than the application start. 

So what I want to do is somehow set the value on application start, or if you have any other suggestion on how this should be handled that would be great.

**Comment by clarkdo** [comment]
`mounted` works because it won't be called in `ssr`. 

You can use `spa` mode to remove first ssr loading.

**Comment by tsimenis** [comment]
Wouldn't that mean that I won't have ssr at all? Then this is not what I need...

**Comment by clarkdo** [comment]
If you still need `ssr` in the pages which can't render in server side normally, the only way is to skip the incompatible parts.

Maybe wrap the whole pages depending on `window` with `no-ssr`, or make page invisible util `isMobile` is ready for solving visible switch?

Maybe ask @Atinux @pi0 help is a good choice 😸 .

**Comment by tsimenis** [comment]
Well at the moment what I am doing is I keep the commit to the store on the mounted of my default layout, and for the parts that are above the fold on mobile and might have a visible switch I try to show/hide with css till `isMobile` evaluates.

This simple "mobile detection" though is something that I always need so I am wondering what is the best way to go with this. Or as in the example I'm also setting breakpoint values on my store based on the `window.innerWidth`

It would be great if any of the guys @Atinux @pi0 have a suggestion on this.

thank you for your input so far :smile:
