### ISSUE TITLE
Using ES6 features server-side

### ISSUE THREAD

**Issue by WouterFlorijn** [nuxt/nuxt.js#2087]
I would like to be able to use ES6 features such as `import` and `async` server-side. I'm currently building an app based on the [auth routes example](https://github.com/nuxt/nuxt.js/tree/dev/examples/auth-routes). Since I would like to share some plugins between Nuxt backend and frontend (such as an axios instance that posts to the api), this would make things a lot cleaner. Currently, I would either have to make sure all the code is basic js, or duplicate all the shared code.

I'm not an expert on build systems, so I was wondering if there is a way I can implement this myself or if it is planned to be added. Any help is appreciated!

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1852">#c1852</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @WouterFlorijn & thanks for your idea. Sure it will be planned for 2.0. (Related to #1935)
