### ISSUE TITLE
How to exclude dev resources on production generate

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#2088]
We have a number of json files we use for api mocking. They are in static folder. How to exclude them from nuxt generate on production env?

**Comment by clarkdo** [comment]
Maybe same question as https://github.com/nuxt/nuxt.js/issues/2083

**Comment by husayt** [comment]
Not really. I just want depending on either is production mode on or off to exclude or include certain static resources going to bundle. I guess I have to do some webpack reconfiguration

**Comment by clarkdo** [comment]
https://webpack.js.org/configuration/externals/
https://github.com/liady/webpack-node-externals

Hope this can help you. 😺 
```js
module.exports = {
  build: {
    extend (config, { isServer }) {
      config.externals = {
        // ...
      }
    }
  }
}
```

**Comment by DrSpatula** [comment]
How did you end up configuring `externals` to exclude JSON from the production static folder?  I have the same issue with a set of Markdown files in that directory.
