### ISSUE TITLE
v-for doesn't work with nuxt-link

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2089]
I am trying 

```html
<nuxt-link v-for="action in actions">{{ action.name }}</nuxt-link>
```
Error
```
TypeError

Cannot read property 'name' of undefined
```

I tried search `v-for nuxt-link` but can't find the answer.

**Comment by iamdubx** [comment]
This one is workfing fine

```html
<li v-for="action in actions">{{ action.name }}</li>
```

**Comment by iamdubx** [comment]
```js
data () {
    return {
      actions: [
        {
          name: 'Add article'
        },
        {
          name: 'List of articles'
        }
      ]
    }
  }
```

**Comment by alexchopin** [comment]
Hi @iamdubx,
`nuxt-link` component has the same behaviour of `router-link`, so the props `to` is also required.
[Router-link documentation](https://router.vuejs.org/en/api/router-link.html)

**Comment by thecodechemist** [comment]
How would one link to an external source in a v-for loop with Nuxt?

For example, when linking to articles that were retrieved via an API call to another site.

`<nuxt-link class="mb-4" v-for="article in apiData" :key="article.id" :to="article.articleUrl">
      <p class="mb-2">{{article.title}}</p>
   </nuxt-link>`

takes me here -> http://localhost:3000/https:/<source>

**Comment by uptownhr** [comment]
you would use a normal `a` tag
