### ISSUE TITLE
vuex-router-sync not work correctly in asyncData function

### ISSUE THREAD

**Issue by sharh** [nuxt/nuxt.js#2090]
The `vuex-router-sync` plugin:

```javascript
import { sync } from 'vuex-router-sync'
export default ({app: {router, store}}) => {
  sync(store, router)
}
```
The `nuxt.config.js`

```javascript
  plugins: [
    // '~plugins/axios',
    '~plugins/vuex-router-sync'
  ],
```

And then in some of my components:
```javascript
asyncData({store}){
   console.log(store.state.route.params.id);//not the current url params
}
```
In the above code, like a router `/test/:id`, I want to get data in server side, but if the browser location changes like this:

from `/` to `/test/:id`，in the `asyncData`, the `route` is still `/`, if I try to get `store.route.params.id`, it is undefine.

Then if I refresh browser in the path `/test/:id`, like: `/test/1`, in the `asyncData` function, server side will excute, client side will not. And the `store.state.route.params.id` is 1, this is OK.

Then if click the browser back, and return. In server side AsyncData not excute, it excutes in client side, but this time `store.state.route.params.id` is undefined. However, the context.route is correct, and when the component is mounted, the `store.state.route` is right.

There is two questions for me:

1.Why the route from `/` to `/test/:id`, in server side, the `asyncData` does not excute?And when fresh browser in `/test/:id`, `asyncData` excute in server side?
2.Why when `asyncData` excute in client side, `store.state.route` is not the some with `context.route`?

**Comment by clarkdo** [comment]
I tried as you described, It works fine. Blow is the repo, if I missed anything, pls feel free to point out.
https://github.com/clarkdo/nuxt-issues/tree/issue_2090

**Comment by sharh** [comment]
Thank you for reply! I cloned your [repo](https://github.com/clarkdo/nuxt-issues/tree/issue_2090), It is the same with my described.Below is the capture:

1.location: http://localhost:3000/test/1, refresh brower, the asyncData excute in cmd, this is ok:

![image](https://user-images.githubusercontent.com/7692602/32726830-5ab0caae-c8b5-11e7-8e56-cccfb61ba9cc.png)

2.Then I clicked the "Home" link, back to home, and then click "Test Id". This time the `asyncData` excute in client side, it is print below:

![image](https://user-images.githubusercontent.com/7692602/32726978-e017500a-c8b5-11e7-89af-e051a1bf4c92.png)

This time the `store.route` is `/`, you can see it in above picture.

What I know is that the `vuex-router-sync`  commits route in the hook `afterEach`. When  the `asyncData` function excute in client side, the `store.state.route` is not changed, and it is before route, after a lot of 
 time, the  `store.state.route` is changed, when you can console it in `mounted` hook.

Like below:

![image](https://user-images.githubusercontent.com/7692602/32727291-0423a20e-c8b7-11e7-9396-daafc6aaff34.png)

Then I try to change the `vuex-router-sync`:
> just change `afterEach` to `beforeEach`

```javascript
// sync store on router navigation
  const afterEachUnHook = router.beforeEach((to, from) => {
  	console.log(to, from, 'router.afterEach');
    if (isTimeTraveling) {
      isTimeTraveling = false
      return
    }
    currentPath = to.fullPath
    store.commit(moduleName + '/ROUTE_CHANGED', { to, from })
  })

```
Vue console the error:

![image](https://user-images.githubusercontent.com/7692602/32727408-67d32afe-c8b7-11e7-9e92-fe5b62f6977e.png)

I think there is a bug, though, I can get route from the `context`, but in client side `asyncData` function, store.state.route is not the same with `context.route`.

I'am try to tranform a `vue-server-renderer` project to `nuxt.js`. In `vue-server-renderer` project , the [fetch](https://ssr.vuejs.org/en/data.html) hook can work well with router.

**Comment by clarkdo** [comment]
Sorry about my mistake, you are right. `asyncData` is in `beforeEach` and `vuex-sync` watching is in `afterEach`.

I suggest that you may move the `afterEach` inside `vuex-router-sync` into a `middleware`.

**Comment by clarkdo** [comment]
I updated the codes, you may have a look at https://github.com/clarkdo/nuxt-issues/tree/issue_2090

**Comment by sharh** [comment]
There is an error : `Cannot read property 'registerModule' of undefined`.
It has an error in your [repo](https://github.com/clarkdo/nuxt-issues/tree/issue_2090):

`plugins/sync.js`

```javascript
export default ({app: {router, store}}) => {
    store.registerModule(moduleName, {
    ...
}
```
Is there some changed with `Nuxt.js`?

**Comment by clarkdo** [comment]
No, can you describe in brief your steps?

**Comment by sharh** [comment]
I changed my middleware with your code in my project. This time it is worked well.

There is a question I don't understand that is why in server side the middleware and plugins excute just once when router changed. Exactly, it is just excuting when fresh a browser, or init app.

How does the hook work in server side or client side? The official docs is not explicit. So can some thing more detail?

**Comment by sharh** [comment]
With your repo, I just do:

1.npm install
2.npm run dev
3.browser to http://localhost:3000/
4.browser display:
![image](https://user-images.githubusercontent.com/7692602/32758571-f463530a-c91f-11e7-98b6-d725d835dbf4.png)

**Comment by clarkdo** [comment]
1. plugins execution is under `createApp` which only executes once as you said, it's designed for running before instantiating the root vue.js application.
2. `middleware` in server side is called in ssr server entry just like `plugins`, and in `client` is called in `client.js->render` which is a route `beforeEach` hook.

**Comment by sharh** [comment]
I got it. Thanks!

**Comment by Jabbar2010** [comment]
1.Why the route from / to /test/:id, in server side, the asyncData does not excute?And when fresh browser in /test/:id, asyncData excute in server side?

How to solve this question ?
