### ISSUE TITLE
detail page for SEO

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#2093]
I knew that nuxtServerInit can achieve ssr, then seo for homePage.
But if I have a newsList page, how can i to do seo for these newsdetails page?
Or, except homePage, how to do seo for other pages?
When i get data in asyncData or fetch, these is SSR ? these data can be  crawler find ?

**Comment by christophwolff** [comment]
Jep. The page is rendered on the server and the plain HTML is send to the user/craweler.

I use nuxtServerInit to anitialize a global menu what is present on all pages.

**Comment by ouyangxiaoai** [comment]
@christophwolff So, a project has many pages that isn't global? what can i do for these pages'seo.
these page's data can used SEO?
or this can't achieve actually.

**Comment by C4Grey** [comment]
@ouyangxiaoai 
> When i get data in asyncData or fetch, these is SSR

Yes, it is.
You can check manually your server-generated HTML markup by some console utility, like `curl` or `wget`, or even in browser(CTRL+U in Chrome). 
Also you may use a plenty of online SEO tools, like Google Search Console. There is even a [tunnel for your localhost](https://github.com/nuxt-community/modules/tree/master/packages/localtunnel) that you can use to proxy worldwide, which will allow you to quickly test your SSR-based SEO.

**Comment by ouyangxiaoai** [comment]
@C4Grey I will try a ssr test.thanks
