### ISSUE TITLE
How can I remove ESLint from an existing Nuxt app?

### ISSUE THREAD

**Issue by PastaPassus** [nuxt/nuxt.js#2097]
I used this template: https://github.com/nuxt-community/express-template

But ESLint really isn't working for me:

1. It's full of bugs. E.g. it claims that I need to remove commas in the index.js file in the store even though removing the commas clearly breaks the code. My current problem is that it keeps telling me that `v-model does not support dynamic input types. Use v-if branches instead. ` even though the same code works perfectly fine if I try it on [fiddle](https://jsfiddle.net/t0326bke/10/). I don't even know what kind of rule I should add to stop ESLint from complaining about this.

2. ESLint is absurdly annoying. Why do I get this popup/layover when there is an error and I can't hide it? It's just bizarre how patronizing it is given that it isn't even working properly. Also ESLint really isn't user friendly, configurating it takes far too much time and often doesn't even work. E.g. I added a `.eslintignore` file and changed in the `package.json` the script to `"lint": "eslint --ext .js,.vue --ignore-path .eslintignore ."` following [this advice](https://github.com/nuxt/nuxt.js/issues/470) and what ESLint states on [their website](https://eslint.org/docs/user-guide/configuring), but it didn't work.

3. Because I already wasted hours due to ESLint I tried disabling it completely but even that doesn't seem to work.  [Here ](https://github.com/vuejs-templates/webpack/issues/73) a user recommends commenting out the content of `extend` under `build` in the `nuxt.config.js` file but that doesn't work as I still get the same (incorrect) error message. 

So how can I remove ESLint or at least disable it without having to complete rebuild the entire app, as the template above is otherwise quite useful?

Also sorry for the rant but I don't understand why ESLint is included in Nuxt. I really liked Nuxt and the whole concept of Nuxt and Vue seem to be to make things easy and effective to use, but ESLint seems to be the complete opposite. And it's not even that I am against the idea behind ESLint, but ESLint itself just doesn't seem to be a good tool.

**Comment by clarkdo** [comment]
You can just remove the eslint dependencies and scripts in package.json.

And you can generate the boilerplate by using next release https://github.com/nuxt-community/create-nuxt-app, it will let you choose whether to install `eslint`, if you want to try it before releasing, just use `dev` branch 
```bash
git clone git@github.com:nuxt-community/create-nuxt-app.git
node create-nuxt-app/cli.js my-app
```

**Comment by gregbenner** [comment]
nuxt.config 
``` /*
    ** Run ESLint on save
    */
    // extend(config, ctx) {
    //   if (ctx.isDev && ctx.isClient) {
    //     config.module.rules.push({
    //       enforce: "pre",
    //       test: /\.(js|vue)$/,
    //       loader: "eslint-loader",
    //       exclude: /(node_modules)/
    //     });
    //   }
    // }```
