### ISSUE TITLE
launch project

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#210]
tell me how to run the project without using the command?
nuxt 
nuxt start

i need a command equivalent
node ./app.js

I need to run through Passenger (apache)

**Comment by solarhell** [comment]
You can use [pm2](https://github.com/Unitech/pm2) to deploy it.

**Comment by wormen** [comment]
@solarhell on the server, I can only use Passenger
limit hosting provider

**Comment by Atinux** [comment]
@wormen you need to use nuxt.js programmatically.

Please check https://nuxtjs.org/api/nuxt/

And also this example with express: https://github.com/nuxt/express

As you can see in the `package.json`, the "start" script is "NODE_ENV=production node server.js"
