### ISSUE TITLE
How to extract common mutations between modules?

### ISSUE THREAD

**Issue by chabib** [nuxt/nuxt.js#2102]
I have some store modules that have some similar mutations .
So, I decide to extract it to mutations.js
But, I don't know how to load it in nuxt.
simple import seems fail
Here's the directories
```
store/
---common/
------mutations.js
---module1.js
---module2.js
```
Here's how I import it in module1.js
```js
import mutations from './common/mutations'
```

**Comment by BruceHem** [comment]
How common are they? Any code snippets or examples?

**Comment by chabib** [comment]
State in each modules is an array, so I end up made this same mutations code in both modules
```coffee
  seed: (state, data) -> Object.assign(state, data)
  save: (state, data) -> state.push(data)
  saveOrUpdate: (state, data) ->
    index = state.findIndex((savedData) -> savedData.id == data.id)

    if index == -1
      state.push(data)
      return

    state[index] = data
  destroy: (state, id) ->
    index = state.findIndex((data) -> data.id == id)

    if index != -1
      state.splice(index, 1)
```

**Comment by chabib** [comment]
Some example shown for for classic mode in https://nuxtjs.org/examples/vuex-store
But, I am looking for a way to achieve the same thing in modules mode

**Comment by chabib** [comment]
In modules mode, apparently every file in store folder turned into vuex module, so I moved common folder to project root. And actually I am using coffeescript. So, here's what I got so far:
This doesn't work
```coffee
import mutations from '~/common/mutations'
```
but this does
```coffee
import mutations from '~/common/mutations.coffee'
```

@Atinux wonder why

**Comment by chabib** [comment]
I have changed nuxt package directly in node_modules so it could use coffeescript as stated in #1782 
But, it should be bundled again to dist/nuxt.js. So what I did was hack a bit bundled nuxt.js, at webpack base config of file resolving.
Closing this, and I hope support for coffeescript is coming soon.
