### ISSUE TITLE
Lifecycle hooks

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#2106]
Hi, 
I need a lifecycle hook on the client side to fetch some data. Assume the url is /app/x/**y** . I need to fetch some data  and run some client side code (eg; redrawing the graph_ when the url changes to /app/x/**z** .
I tried the mounted hook. But it is triggered only once. Which other lifecycle hook can I use. I need access to the **this** object.
I can't use fetch() and asyncData because this code needs some graph library and video player

**Comment by dohomi** [comment]
@shyamchandranmec use the `updated()` hook maybe?
