### ISSUE TITLE
The asyncDate function gets the params incorrectly

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#2107]
This is my routing structure
![image](https://user-images.githubusercontent.com/11555571/32777177-c9c1d5f6-c8fa-11e7-9820-2f2e9cfda73c.png)
![image](https://user-images.githubusercontent.com/11555571/32777212-e5dc03ce-c8fa-11e7-8591-24fb47bcb03c.png)
The console prints the result when I refresh the page
![image](https://user-images.githubusercontent.com/11555571/32777194-d4e254f6-c8fa-11e7-829f-f46acc2435a3.png)
And then every single page when the jump print the results and expectations do not meet
![image](https://user-images.githubusercontent.com/11555571/32777201-d98af2b0-c8fa-11e7-9668-0ef658cbee76.png)

**Comment by husayt** [comment]
This seems to be resolved in 1.4.0. Closing. Reopen if still happens.
