### ISSUE TITLE
Pre-built .nuxt folder

### ISSUE THREAD

**Issue by galvez** [nuxt/nuxt.js#2109]
Why doesn't Nuxt.render() work if you've got a pre-built .nuxt folder?

**Comment by clarkdo** [comment]
In `dev` mode, you can't separate `build` and `render`. Because `build` will not only generate `.nuxt`, but also build webpack `bundles` and setup `webpackDevMiddleware` and `webpackHotMiddleware`, and the `bundles` are all in memory.

**Comment by galvez** [comment]
@clarkdo Thanks for responding! Thing is, I'm pretty sure it's not running in dev mode. The idea would be to run build once and then start the server as many times as needed. Am I going the wrong way about this?

**Comment by clarkdo** [comment]
@galvez Would you mind to describe your steps and a repo to reproduce you issue ?
