### ISSUE TITLE
Set up Babel for non-client code

### ISSUE THREAD

**Issue by ndarilek** [nuxt/nuxt.js#211]
It's a bit surprising to me that I can't use `import` in server.js from the example Express bundle. `require` can get a bit clunky if I want to pull multiple definitions from a single module. Granted, Node 7 supports lots of Es2015, but the modules system is an exception.

I tried adding babel-core/babel-register and including a .babelrc, but that didn't seem to touch the files pulled in by the Nuxt commands, possibly because they're in node_modules and node_modules is exempt from babel-register.

Any chance we might gain the ability to use the same ES2015 code and features on both the client and server? Thanks!

**Comment by Atinux** [comment]
@ndarilek node.js does not support yet the `import` statement, it has nothing to do with nuxt.js.

If you want to use the latest ES6 feature in your `server.js`, I recommend you to take a look at https://github.com/palmerhq/backpack

**Comment by ndarilek** [comment]
I know it's a Node issue--as described in the initial issue, Node 
doesn't support all of ES2015. My point is that the starter projects can 
set up [babel-register](https://babeljs.io/docs/usage/babel-register/) 
and provide the exact same features on both the client and server 
*regardless* of what Node itself supports. As things stand now, it's 
mildly surprising that I can't use the same featureset on both.

**Comment by Atinux** [comment]
@ndarilek can you open this issue on https://github.com/nuxt/express?

**Comment by ndarilek** [comment]
Sure. Actually, I did some research. Let me do one better and open a PR 
instead.
