### ISSUE TITLE
https://nuxtjs.org/ SSL Connection

### ISSUE THREAD

**Issue by paul-barton** [nuxt/nuxt.js#2112]
https://nuxtjs.org/ is having SSL Connection Issues

Cloudflare is unable to establish an SSL connection to the origin server.

This page (https://nuxtjs.org/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert

Error 525 Ray ID: ... • 2017-11-14 23:05:55 UTC
SSL handshake failed
[nuxtjs.org/issues/87](https://github.com/nuxt/nuxtjs.org/issues/87)

**Comment by toadkicker** [comment]
https://github.com/nuxt/nuxtjs.org/issues/87

**Comment by stevesong** [comment]
Archive.org has a reasonable back-up at https://web.archive.org/web/20170610090431/https://nuxtjs.org/guide/installation/

**Comment by pi0** [comment]
Fixed now :)

https://nuxtjs.org/

Sorry for inconveniences.
