### ISSUE TITLE
How to implement vuex nested module in nuxt store modules mode?

### ISSUE THREAD

**Issue by chabib** [nuxt/nuxt.js#2113]

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/tree/master/examples/vuex-store-modules

**Comment by chabib** [comment]
Thanks @clarkdo!
Closing this.

**Comment by jericopulvera** [comment]
Why is there no actions in examples?

**Comment by davidchriqui** [comment]
For actions you need to export an "actions" object (the same as for mutations), and when you want to dispatch the action you need to prefix the name of the action with the namespace of the module.
e.g:
in store/todos :
`export const actions = {
 increment ({
    commit
  }) {
    commit('increment', 1)
 }
}`

in components/todos.js:
`dispatch('todos/increment')`
