### ISSUE TITLE
"nuxt.render" does not  return Promise

### ISSUE THREAD

**Issue by xiejunfeng** [nuxt/nuxt.js#2116]
version: 1.0.0-rc11

![image](https://user-images.githubusercontent.com/6460243/32833297-0aeb890e-c9c4-11e7-8297-7f70c32941b8.png)

i can not use like that

```js
yield app.nuxt.render(this.req, this.res)
```

**Comment by wosevision** [comment]
Is that line of code a piece of some generator function, or were you looking for the `await` keyword instead?

Nothing about that code should work on its own, `yield` doesn't inherently do any Promise unwrapping.

**Comment by tyrion-yu** [comment]
I got the same problems!

It's not a thing with `yield` or `await`. 
The method `render` SHOULD return a `Promise` as the documents say [here](https://nuxtjs.org/api/nuxt-render) .

BUT in fact, nuxt use a module called `connect`. Check the `handle` method of `connect`, it returns a `undefined`. So `nuxt.render` returns a `undefined`.

Oh my god !

**Comment by tyrion-yu** [comment]
Although there is something wrong with the document.

[Here](https://github.com/nuxt-community/koa-template) is a very good example.
It shows how to use the `render` method correctly!

The point is:

```
app.use(async (ctx, next) => {

        await next()

        ctx.status = 200

        return new Promise((resolve, reject) => {
            ctx.res.on('close', resolve)
            ctx.res.on('finish', resolve)
            nuxt.render(ctx.req, ctx.res, promise => {
                promise.then(resolve).catch(reject)
            })
        })

    });
```

**Comment by husayt** [comment]
This seems to be resolved now. Closing. Reopen if still happens.
