### ISSUE TITLE
Custom component not rendering in dev mode

### ISSUE THREAD

**Issue by er1x** [nuxt/nuxt.js#2117]
I have a custom components library referenced as a dependency in package.json like this:

```json
"dependencies": {
    "nuxt": "^1.0.0-rc11",
    "vue-components": "file:../../shared/vue-components"
  }
```

It works well in another projects using it normally:

```js
import { TsButton } from 'vue-components'

export default {
  name: 'app',
  components: { TsButton }
}
```

However, when using it in a nuxt project component renders and instantly dissapears (I guess it's rendering only in server). Throws this errors:

<img width="542" alt="imagen" src="https://user-images.githubusercontent.com/7016146/32837408-bf157b62-ca0d-11e7-91eb-21a7e12810f2.png">

<img width="1465" alt="imagen" src="https://user-images.githubusercontent.com/7016146/32837453-eb5d2b84-ca0d-11e7-8a1e-8637d8efd298.png">

I've tried including it in plugins with same result.  When building and running in production mode, it works perfecly.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1877">#c1877</a>)</em></sub></div>

**Comment by pi0** [comment]
This may be due SSR problems with provided custom *vue-components* library and unfortunately, something not directly related to Nuxt.js. Would you please provide more information about that shared lib? Also, is it using named ES6 exports?

**Comment by er1x** [comment]
Thank you for helping. 

The library actually does nothing since I'm just setting up a prototype for a new project, and I want to be sure that is doable.

Library components are generated using [this](https://github.com/prograhammer/vue-library-template) and are pretty simple:

```html
<template lang="pug">
  button.ts-button Just a testing button
</template>

<script>
export default {
  name: 'ts-button'
}
</script>

<style lang="stylus" scoped>
  .ts-button
    padding 3em
    border 20px solid black
    background-color red
</style>

```

And are exported with this syntax:

```js
import TsButton from './components/ts-button'
...
export { TsButton }
...
```

It's weird, since:

* Seems to render for an instant and then dissappears.
* I can see component on node console, but is not defined on browser console.
* I'm importing components in other Vue projects (no Nuxt) with Webpack with no issues.
* I've tried using _plugins_ or importing directly with same result.

<img width="1528" alt="imagen" src="https://user-images.githubusercontent.com/7016146/32856120-2a86066a-ca44-11e7-8e2f-87dc51448ed9.png">


If you need more info I can make a full example repo.

Thanks!

**Comment by pi0** [comment]
Thanks again for the info. That's strange ... Maybe sharing example repo would help a lot.

**Comment by er1x** [comment]
I've created a minimal sample [here](https://github.com/er1x/vue-nuxt-sample).

It contains:

- A shared components folder, already compiled.
- A simple vue spa that uses a shared component, no issues.
- A nuxt starter site that uses the shared component. Component flashes in dev mode. No issues in production.

Thanks a lot for helping!
