### ISSUE TITLE
'from' route object in context undefined in ssr but not in spa mode. 

### ISSUE THREAD

**Issue by jroxendal** [nuxt/nuxt.js#2118]
With this code:
```
async asyncData ({ from }) {
  console.log("from", from")
}
```

On browser refresh, this page will log undefined in ssr mode but in spa mode it logs it's own route. This problem defeats the 'shallow routing' trick described by @Atinux here:
https://github.com/nuxt/nuxt.js/issues/1322

**Comment by husayt** [comment]
This seems to be resolved with 1.4.0. Closing. Reopen if still happens.
