### ISSUE TITLE
How can I make sure that the data that has just loaded into LocalStorage can be used immediately in the code?

### ISSUE THREAD

**Issue by Jussiadev** [nuxt/nuxt.js#2119]
I have requests on the site for the API, one of the parameters for the query is `town_id`.
And the value that we substitute there is taken from `LocalStorage`
`town_id: JSON.parse (localStorage.getItem ('town')). ​​id`,
We put it there, automatically determining the user's location and sending the required query to the API. As a result, we get such an object
```{
                        "id": 2379,
                        "name": "Moscow",
                        "region": "Moscow region",
                        "lat": "55.755814",
                        "long": "37.617635",
                        "update_at": 1489006800
                    };};
```
which we place in `LocalStorage`.

However, if you clear the `LocalStorage` and reload the page, then
`console.log ((JSON.parse (localStorage.getItem ('town')))));`
returns `null`. And therefore there is nothing to lay in the `town_id`.
More details on the [video.](https://www.dropbox.com/s/mzek869z13kbrea/ice_video_20171114-174602.mp4?dl=0)

**Comment by uptownhr** [comment]
@Jussiadev I'm not quite following the problem here. After you've cleared/deleted town from localstorage, refreshing the page would clear it and return null.

**Comment by Jussiadev** [comment]
@uptownhr but I do check that if it's empty, then I need to make a request to the API, which just fills this repository

```
created() {
            this.$nextTick(function () {
                if (!localStorage.getItem('town')) {
                    //request to the API and then
                            localStorage.setItem('town', JSON.stringify(this.currentCity));
                        })
                    }.bind(this));
                } else {
                    this.currentCity = JSON.parse(localStorage.getItem('town'));
                }
            })
        }
```

**Comment by uptownhr** [comment]
@Jussiadev I think i need to see how getItem('town') is being used..

**Comment by Jussiadev** [comment]
@uptownhr , I use it, the code I make a request to the API
```
axios.get(api, {
        params: {
          town_id: JSON.parse(localStorage.getItem('town')).id
        },
      }).then((res) => {
                    this.brends = res.data.data;
                })
```
