### ISSUE TITLE
eslint not linting automatically

### ISSUE THREAD

**Issue by app-sparkler** [nuxt/nuxt.js#212]
Before staring with `NUXT`, I was developing with `vue-cli's webpack template`.  It had `eslint for webpack preLoaders configuration`.  This seems to be missing in `nuxt/starter` template.  Can you please suggest how to get the feature of `eslint` for my `source code`.

I am aware of the `documentation` on the `nuxtjs.org` website; however, (as per my understanding) that is for executing it manually and it is not automatically executed every time i save the `project files`

And kudos for the great work on this project.

Thanks.

**Comment by app-sparkler** [comment]
@Atinux I was able to get something working on this with the following `configuration` in the `nuxt.config.js`.  You could, maybe, enhance it.  This is what I've added in the `nuxt.config.js` file:

```
// EXTEND
    extend (config, { isClient }) {
      if (isClient) {
        config.module.rules.push({
            enforce: 'pre',
            test: /\.js$/,
            loader: 'eslint-loader',
            exclude: /(node_modules)/,
        },{
            enforce: 'pre',
            test: /\.vue$/,
            loader: 'eslint-loader',
            exclude: /(node_modules)/,
        })
      }
    }
```

and also `npm install -D eslint eslint-loader` along with the `eslint` packages mentioned on [nuxtjs.org](http://nuxtjs.org) website.

Thanks.

**Comment by tiagomatosweb** [comment]
Hi @appsparkler, I know it might be old and you crossed the last sentence. Just want to register here that to get the nice eslint warning on the page you should install eslint-friendly-formatter package and then add options to the webpack rules like so

```
{
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
          options: {
              formatter: require('eslint-friendly-formatter')
          }
        }
```

Then you are done! Cheers.
