### ISSUE TITLE
Custom Server error page

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2120]
If I kill my API server, then my app shows this error page

![error](https://user-images.githubusercontent.com/30086515/32852650-a41b9924-ca06-11e7-8834-3f51c4eb6d75.png)

I made an `error.vue` layout, but it doesn't work in case of such issue

```html
<template>
  <section class="viewport content">
          <h1 v-if="error.statusCode === 404">404</h1>
          <h1 v-else>An error occured</h1>
  </section>
</template>

<script>
export default {
  props: ['error'],
  transition: 'page'
}
</script>
```
My console is showing this

```
[Vue warn]: Error in render function: "TypeError: Cannot read property 'title' of undefined"
```
So this layout page component trick doesn't catch such errors? Then how to handle it?

**Comment by pi0** [comment]
Hi. For overriding SSR errors, you need to provide an extra static HTML template. Simply create [app/views/error.html](https://github.com/nuxt/nuxt.js/blob/dev/lib/app/views/error.html) file in root of your project and it will be changed.

**Comment by iamdubx** [comment]
@pi0 hi, thanks for response. I am not sure I get you right: I need to create `app/views` folder and then `error.html` file?

**Comment by pi0** [comment]
> I need to create app/views folder and then error.html file?

Yes. Generally to override every template file we can simply place it inside `app` directory :)

**Comment by iamdubx** [comment]
Cool, thanks, it is working.

**Comment by manniL** [comment]
A guide can be found [here](https://blog.lichter.io/posts/change-the-nuxtjs-server-error-page) (shameless plug)
