### ISSUE TITLE
Bulma sass variables 

### ISSUE THREAD

**Issue by Syffs** [nuxt/nuxt.js#2121]
**Is there a way to use bulma sass variables from .vue files?** 
```
<style lang="sass" scoped>
    .section
        background-color: $grey-light
</style>
```
When I try to do so from vue files: `Undefined variable: "$grey-light"`

Bulma sass is loaded from `nuxt.config.js`
```
  css: [
    { src: '~/assets/css/main.sass', lang: 'sass' }, 
    { src: 'font-awesome/scss/font-awesome.scss', lang: 'scss' }
  ]
```
Using bulma classes works fine, but not the variables in specific .vue files...

**Comment by uptownhr** [comment]
@Syffs i normally create a shared.scss file that I import from my .vue components that need them.

**Comment by Syffs** [comment]
@uptownhr it's indeed working if I import my main.sass file in every component in which I need variables, but I was hoping for a more elegant solution...

**Comment by thisguyscode** [comment]
@Syffs -  If I've understood correctly then you might be interested in this thread: https://github.com/nuxt/nuxt.js/issues/1092

I implemented [nuxt-sass-resource-loader](https://github.com/anteriovieira/nuxt-sass-resources-loader) as suggested by @anteriovieira and it worked a treat for sharing variables. The only config required was this (below). Of course you'll just need to replace `./assets/styles/imports.scss` with the path to your `main.sass` file.

```javascript
/* nuxt.config.js */

module.exports {
  ...
  modules: [
    ['nuxt-sass-resources-loader', './assets/styles/imports.scss']
  ],
  ...
}
```

**Comment by Syffs** [comment]
@thisguyscode My goal is indeed make variables avaible to the whole project!
Your implementation looks very good, I'll give it a try!

**Comment by huxleydigitaluk** [comment]
Halelujah.  @thisguyscode just saved  my life with that above. Thanks.

**Comment by husayt** [comment]
This seems to be resolved now. Clo
