### ISSUE TITLE
Using different Babel environments in .babelrc for client and server bundles building

### ISSUE THREAD

**Issue by atos1990** [nuxt/nuxt.js#2125]
Hi guys!
I have very critical problem for me.
In my .babelrc specified two environments: "client" and "server"
{
   "env": {
            "client": {
			"presets": [
				["env", {
					"targets": {
						"ie": 9
					},
					"debug": true,
					"useBuiltIns": true,
					"loose": true,
					"modules": false
				}]
			]
		},
		"server": {
			"presets": [
				["env", {
					"targets": {
						"node": true
					},
					"debug": true,
					"useBuiltIns": true,
					"loose": true,
					"modules": false
				}]
			]
		}
	}
}
Needs use different environments for client and server during "nuxt build"
Now I don't see how it make :(

**Comment by atos1990** [comment]
Also I tried use .babelrc.js
'use strict';

module.exports = {
	presets: [[
		"env", {
			"targets": (process.env.VUE_ENV === "client") ? {"ie": 9} : {"node": true},
			"debug": true,
			"useBuiltIns": true,
			"loose": true,
			"modules": false
		}
	]]
}

but process.env.VUE_ENV always "server". Could you tell me why .babelrc read once? 
I thought that babel-loader would read configuration from .babelrc at each assembly

**Comment by antid0te** [comment]
Just set BABEL_ENV to server or client.

This is my how i use it in my scripts:
`"dev:server": "BABEL_ENV=server nodemon ./server/app --exec babel-node --watch server",`

**Comment by atos1990** [comment]
Unfortunately, it's not my case. Needs use babel-loader during 'nuxt build'

**Comment by husayt** [comment]
Closing as been open for too long
