### ISSUE TITLE
Integrating vue-router-sync

### ISSUE THREAD

**Issue by app-sparkler** [nuxt/nuxt.js#213]
## Question/Doubt : 

Can you please suggest how to _integrate_ `vuex-router-sync` within the project.

I was following `vue-hacker-news` example and in that we would import `router` from the `router module` and `store` from the `store module` and _work_ with `vuex-router-sync` to _sync_ the two.  That was done in the `main.js/app.js` module which was then `exported` for `client-entry and server-entry modules`.

In the `NUXT` framework we don't have a `main.js` or `app.js` file.  Please advise where and how to work with the `vuex-router-sync` library.  Where should i _import_ the `router` and `store` from and where should i _sync_ the two.

Thanks.

**Comment by Atinux** [comment]
In the upcoming release (`v0.9.8`), you will be able to use [vuex-router-sync](https://github.com/vuejs/vuex-router-sync) this way:

`plugins/vuex-router-sync.js`
```js
import { sync } from 'vuex-router-sync'
import store from '~store'
import router from '~router'

sync(store, router)
```

And add the plugin in `nuxt.config.js`:
```js
module.exports = {
  plugins: [
    '~plugins/vuex-router-sync.js'
  ]
}
```

I'll keep it open until the release it out 👍

**Comment by app-sparkler** [comment]
@Atinux any hacks you can suggest for the time being?

**Comment by Atinux** [comment]
@app-sparkler you can now use my solution below :)

**Comment by guumaster** [comment]
This plugin solution you propose works, but makes dev server crash on every page reload. I'm getting this error: 

```
/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:824
    var htmlTag = document.getElementsByTagName('html')[0];
                  ^

ReferenceError: document is not defined
    at updateClientMetaInfo (/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:824:19)
    at Vue$2.refresh (/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:885:35)
    at /my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:1013:74
    at Timeout._onTimeout (/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:924:5)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

My route is also nested:  `/something/_slug/_id`, and it works again if I remove the plugin `plugins/vue-router-sync.js` from the list.

**Comment by appsprklr** [comment]
@guumaster `document object` will not be available on the `server`.  You will have to encapsulate the code in a an `if` block:

```
if (process.BROWSER_BUILD) {
  require('external_library')
}
```

Reference : [https://nuxtjs.org/faq/window-document-undefined/#window-or-document-undefined-](https://nuxtjs.org/faq/window-document-undefined/#window-or-document-undefined-)

Good Luck!

**Comment by dohomi** [comment]
@appsprklr I don't think that @guumaster did any mistake. I rather think that he needs to add the `vuex-router-sync only` only as a client side plugin.

**Comment by appsprklr** [comment]
Thanks @dohomi 

@guumaster here's the reference to work with `client-only plugins` https://nuxtjs.org/guide/plugins/#client-side-only

**Comment by guumaster** [comment]
@appsprklr I understand what you said, but that's not the way to solve this particular issue. I've just added `vue-router-sync` and the server render fails with an unrelated `document is undefined` error in the `vue-meta` library. where would you put that `if (process.SERVER_BUILD)... ` ?

The workaround I came up with was to set the plugin as a ssr only, as you also mention. Something like this: 

```
  plugins: [
    { src: '~plugins/vue-router-sync', ssr: false }
  ]
``` 

Thanks!

**Comment by Muscot** [comment]
I did have some problem with @Atinux plugin solution. 

In the latest version of NUXT you should export a createStore function from the store/index.js instead of a vuex instance. And ofc I don't want to create another instance in my plugin files.

I come up with this solutions: 

import { sync } from 'vuex-router-sync'
export default ({app: {store, router}}) => {
  sync(store, router)
}

**Comment by adam-lynch** [comment]
I'm using @Muscot's example but in a component computed, `this.$store.state.route` doesn't exist and `mapState('route')` throws an error. Any ideas?
