### ISSUE TITLE
Validate several pages with similar routes

### ISSUE THREAD

**Issue by 0pt1m1z3r** [nuxt/nuxt.js#2130]
Hi! I want to add several pages with similar routes. A page should be displayed that suits the conditions in `asyncData` or `validate`.

Example:
```
# _foo.vue - only digits
export default {
  validate ({ params }) {
    return /^\d+$/.test(params.foo)
  }
}
```

```
# _bar.vue - only something else
export default {
  asyncData ({ params, error }) {
    return checkParams(params)
      .catch((e) => {
        # go to check next route
      })
  }
}

```

```
# _other.vue - for other params
export default {
}
```

Of course, I can make a general check in one file. But is it possible to implement it in several pages?
Can this be seen as a task for the future?

**Comment by clarkdo** [comment]
Actually you cannot do this, `asyncData` and `validate` are all executed after route has been determined.

I suggest you can make checking in `middleware`, then redirect to different route.

As for if it can be implemented, need to ask for @Atinux @pi0 's opinion 😃

**Comment by Atinux** [comment]
You can do it in `middleware` as @clarkdo said.

Or you can have all your logic into your `asyncData` page and then load & display the corresponding component depending of the type of data you have to display.

Also, `vue-router` does not handle this "logic" of going to the next route matched.
