### ISSUE TITLE
Setting Up Nuxt With Nginx

### ISSUE THREAD

**Issue by rikez** [nuxt/nuxt.js#2131]
Hello,

I've been facing problems when serving only the nuxt .js files through Nginx.

Well,
I have a subdomain subdomain.domain.com that runs a wordpress blog and e-commerce. However, I intend to serve nuxt on a specific location of this subdomain, something like subdomain.domain.com /nuxtproject

Here is my nginx conf

```conf
server {
    # SSL configuration
        listen 443 ssl;
       server_name subdomain.domain.com.br;

        ssl on;
        ssl_certificate /etc/nginx/ssl/certs/ssl.crt;
        ssl_certificate_key /etc/nginx/ssl/private/certificate.key;

    root /var/www/html/cursosabertosv2;

    location /pay {
      alias /var/www/html/crescimentum.pay/source;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_pass http://localhost:3000;
}

location / {
      root /var/www/html/cursosabertosv2;
      index index.php index.html index.htm;
      set $php_root /var/www/html/cursosabertosv2;
      try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
      root /var/www/html/cursosabertosv2;
      index index.php index.html index.htm;
      set $php_root /var/www/html/cursosabertosv2;
      include snippets/fastcgi-php.conf;
      fastcgi_pass unix:/run/php/php7.0-fpm.sock;
 }


    location = /favicon.ico { root /var/www/html/cursosabertosv2; log_not_found off; access_log off; }
    location = /robots.txt { root /var/www/html/cursosabertosv2; log_not_found off; access_log off; allow all; }

    location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
        add_header Access-Control-Allow-Origin "*";
    }

}
```
https://subdomain.domain.com.br/nuxtProject/nuxtBuild/dist/app.eef42378ecb0188c013a.js
error 404 not found

** I am using nuxt build, with the build Path set to nuxtBuild

Can someone help me please ?

**Comment by clarkdo** [comment]
If you use `nuxt build`, you need to start the node server by `nuxt start`, then forward all request from `nuxtProject` to node server.

```conf
  location /nuxtProject {
    # node server address, e.g., localhost:3000
    proxy_pass http://localhost:3000/
  }
```

If you want to use static files, you need to generate files by `nuxt generate` and set `root` to `dist` folder.

```conf
  location /nuxtProject {
        root   /dist/;
        index  index.html index.htm;
    }
```

**Comment by rikez** [comment]
What if I am using express ?

Should I serve the dist file through express?

**Comment by clarkdo** [comment]
You need to embed nuxt into express.  

Use https://github.com/nuxt-community/express-template

or

https://github.com/nuxt-community/create-nuxt-app to setup the project

**Comment by clarkdo** [comment]
If use static files, use express to serve the generated files is also ok

**Comment by EmmanuelBeziat** [comment]
HI @clarkdo 

I have pretty much the same problem; I don't get 

```nginx
# Site global
server {
	listen 443 ssl http2;
	server_name	www.myapp.com;
	access_log	off;

	location = /robots.txt	{ access_log off; log_not_found off; }
	location = /favicon.ico	{ access_log off; log_not_found off; }
	location / {
		proxy_pass http://127.0.0.1:3042/;
		include /etc/nginx/conf.d/proxy.conf;
		root /var/www/myapp/site;
		add_header Access-Control-Allow-Origin *;
	}

	location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|txt|srt|swf)$ {
		root /var/www/myapp/site/;
		expires 30d;
	}

	ssl_certificate /etc/letsencrypt/live/myapp.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/myapp.com/privkey.pem;
}
```

Watching the example you provided, I wondered if I needed to target the dist folder (which is in .nuxt folder once build, right?). 

Knowing my projectfolder is the `site`folder, I tried with `/myapp/site/.nuxt`, `/myapp/site/dist`, `/myapp/site/.nuxt/dist` (for both root commands), but none of it worked.

In the log error, it seems that it's trying to reach `_nuxt` folder? Why not `.nuxt`? I assume this is a simple route stuff, but how can I be sure that it target the needed folder?

I’m confused right there…

Thanks!

**Comment by clarkdo** [comment]
Do you use `nuxt start` or `nuxt generate` ?

If `start`, you shouldn't forward requests to `.nuxt/dist`, it should be the url of node server which is started by `nuxt start`, such as: `http://localhost:3000`

If you use `generate` for deploying static project, you need forward request to the resources as the second way I mentioned above: `root   /dist/`.

**Comment by EmmanuelBeziat** [comment]
`nuxt start`, i want it to be SSR.

> it should be the url of node server which is started by nuxt start, such as: http://localhost:3000

Well, that’s the case: `proxy_pass http://127.0.0.1:3042/;` And the app is partially loading, header is loaded and some parts. But there’s all of these missing:

![45ulx_parkourfinder accueil 2017-11-30 16-23-37](https://user-images.githubusercontent.com/6781337/33472953-af04e51e-d674-11e7-91ea-009587e3f5d6.jpg)

**Comment by TheEcho** [comment]
Hello guys, 
I'm currently facing the exact same issue ! The Nuxt app try to load all these files in /.nuxt/ but the nuxt build commande put all the files in the /.nuxt/dist folder...

Any idea to fix this ?

**Comment by clarkdo** [comment]
@TheEcho `_nuxt` is the default `publicPath`, you can change it through `build.publicPath` in nuxt.config.js.

https://nuxtjs.org/api/configuration-build/#publicpath
https://webpack.js.org/guides/public-path/

**Comment by clarkdo** [comment]
@EmmanuelBeziat Sorry for the late reply, if the issue is still existing, could you please paste you nginx config here and provider a reproducible repo ?

**Comment by clarkdo** [comment]
It's due to that `.nuxt/dist` is the default `output.path` and `_nuxt` is the default `output.publicPath` of `webpack config`.

Related Documents:
https://webpack.js.org/configuration/output/#output-path
https://webpack.js.org/configuration/output/#output-publicpath

**Comment by EmmanuelBeziat** [comment]
Thanks a lot :)
