### ISSUE TITLE
Wher can i use the context object ?

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#2134]
I have set proxy, so I can use context.app.$axios to request, but is it used only in asyncData or fetch?
can I used context in other method ?

**Comment by pauldariye** [comment]
hey @ouyangxiaoai there's a solid guide in the [axios-module doc](https://github.com/nuxt-community/axios-module).

essentially you should be able to use `axios` like so: `this.$axios.get(...)` in your component.

**Comment by ouyangxiaoai** [comment]
@pauldariye I know this, but this can't use proxy.
when i use this to request, there has error: http404,because it has been http://localhost:3000/XXX.
but when i used in asyncData or fetch,the proxy is work so I can get data

**Comment by fengjiel** [comment]
[browserbaseurl](https://github.com/nuxt-community/axios-module#browserbaseurl) ?

**Comment by pauldariye** [comment]
ah gotcha @ouyangxiaoai

**Comment by ouyangxiaoai** [comment]
thanks all. i have a error code.
