### ISSUE TITLE
proxy don't work

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#2135]
I have set proxy and it works if i used app.$axios in nuxtServerInit and asyncData and fetch.
but if i used in other method there is error, http 404, I guess the proxy is not work.
so what can i do ?

**Comment by overarchingSky** [comment]
The following is my configuration：
`modules.exports = {
    env: {
    HOST: process.env.host || 'localhost',//defined by cross-env in scripts of package.json
    PORT: process.env.port || '3000'
  },
  modules: [//need npm install @nuxtjs/axios and @nuxtjs/proxy
    '@nuxtjs/axios',
    '@nuxtjs/proxy'
  ],
  proxy: [//request with axios , url must be start with '/api',otherwise，you will get  error with 404
    [
      '/api',
      {
        target: 'http://api.douban.com/v2', // api server
        pathRewrite: {'^/api': '/'}
      }
    ]
  ],
}`
