### ISSUE TITLE
ReferenceError : "window is not defined"

### ISSUE THREAD

**Issue by luke-Yang** [nuxt/nuxt.js#2137]
i want to use 'echart.js' but when i render the page, ReferenceError : "window is not defined" , how to fixed it? and i console.log(process.BROWSER_BUILD) and it's undefind

**Comment by clarkdo** [comment]
Since 1.0.0-rc3 `process.BROWSER_BUILD` has been removed in flavour of `process.browser`

**Comment by baztypetrucci** [comment]
This happens with NUXT "SSR" option enabled, probably you are using a plugin or something that SSR (Server side rendering) cant resolve, there are two ways to solve this:

1- In you template use <no-ssr></no-ssr> for remove SSR template parts.
2- In your JS scripts inside .vue file, use if(process.browser){//your code here} to bypass SSR.

This is to bypass the SSR, if you need your functions keeping the SSR, just search for another plugin...
