### ISSUE TITLE
Mismatching childNodes vs. VNodes - Only in Firefox

### ISSUE THREAD

**Issue by paumoreno** [nuxt/nuxt.js#2139]
I'm developing a site using Nuxt v. 1.0.0-rc9.

In a particular list of elements, Firefox (v57) is complaining about a mismatch between childNodes and VNodes, whereas Chromium (v62) isn't.

I am not manipulating the DOM at client side in any way, and the HTML is valid.

The page where the problem occurs is the following: http://dondeverlo.com:8080/?ver=todo

In production mode there is no error message in the console, however, when loading the given URL in Firefox, a lot of elements of the list disappear when hydration is bailed and a client side render is performed. I'd be glad to activate Vue Dev Tools in the production build if this helped finding the problem, but I haven't found how.

When running in dev mode, the Firefox console shows this error:

```
Mismatching childNodes vs. VNodes:  
NodeList [ div.Provider, div.Provider ]
 
[…]
0: Object { tag: "vue-component-20-provider", data: {…}, key: "9666-19", … }
1: Object { tag: "vue-component-20-provider", data: {…}, key: "9666-52", … }
2: Object { tag: "vue-component-20-provider", data: {…}, key: "9666-53", … }
3: Object { tag: "vue-component-20-provider", data: {…}, key: "9666-105", … }
```

These `9666-X` keys are part of an item in the list which disappears after the client side render in Firefox, but stays in the list when viewed in Chromium (this 9666 item can be found by searching for the text "Apoel - Madrid" in the page).

Does anyone have an idea of what may be happening?

Thanks in advance for your help, and thank you for this great great Framework :)

**Comment by pauldariye** [comment]
@paumoreno try wrapping your list component in the `<no-ssr></no-ssr>` component. That should fix it. This is a temp solution though.

**Comment by paumoreno** [comment]
@pauldariye This effectively prevents the error from happening (however, of course, it also prevents the component from being rendered server-side, and I'd really like search engines to index the entire contents of the page).

Why do you say it's a temporary solution? Is there an unreleased fix for this or an improvement in this direction?

Thanks!

**Comment by paumoreno** [comment]
I found the cause of the problem, I explained it in https://github.com/nuxt/nuxt.js/issues/2168.

**Comment by pauldariye** [comment]
Awesome @paumoreno ! I'm also looking into this again. I had to get something out quickly so didn't bother solving the issue when I encountered it hence opting for `<no-ssr />`.
