### ISSUE TITLE
Nuxt stop server

### ISSUE THREAD

**Issue by baztypetrucci** [nuxt/nuxt.js#2140]
Hi, Im finishing a website using Nuxt, excellent Framework!, but for run "npm start" in background i'm using "Forever", but this is only to execute a command, ¿how did you make for example... "npm run stop"?.

Thanks!

**Comment by zikeji** [comment]
This "issue" is very irrelevant to this repo.  Consider using [PM2](https://github.com/Unitech/pm2). That way you can launch your app using PM2, and stop it using PM2. And even setup automatic startup on boot with PM2.

**Comment by baztypetrucci** [comment]
@zikeji no problem, but im asking becouse I wanted to know the way to update builds.
