### ISSUE TITLE
v-else hydrate inconsistency

### ISSUE THREAD

**Issue by alexcruice** [nuxt/nuxt.js#2141]
## Problem
Using `v-if` and `v-else` directives to conditionally output a single root element for a component template fails if the `v-else` directive is attached to an HTML element, but works as expected when attached to a component.

Tested in latest Chrome, Firefox, and Safari on macOS 10.12 with Nuxt v1.0.0-rc11.

## Minimal, reproducible example
https://github.com/alexcruice/nuxt-v-else

## Screenshots
_Render_
<img width="360" alt="screen_shot_2017-11-18_at_9_55_21_am" src="https://user-images.githubusercontent.com/3786095/32974042-f7c1a6d0-cc46-11e7-9e84-fa646f39f6dc.png">

_Source_
<img width="347" alt="screen_shot_2017-11-18_at_9_55_48_am" src="https://user-images.githubusercontent.com/3786095/32974047-0a6ae468-cc47-11e7-932c-b42b3d4fa1fa.png">

_Console output_
<img width="960" alt="screen shot 2017-11-18 at 9 57 07 am" src="https://user-images.githubusercontent.com/3786095/32974062-29dbf080-cc47-11e7-89ad-1717f8326f11.png">

**Comment by Gomah** [comment]
It has been fixed in a recent version of Vue 👍 

Add vue, vue-server-renderer & vue-template-compiler to your package.json or just add resolutions for yarn:

```json
"resolutions": {
    "nuxt/vue": "^2.5.5",
    "nuxt/vue-server-renderer": "^2.5.5",
    "nuxt/vue-template-compiler": "^2.5.5",
    "nuxt/vue-loader": "^13.5.0",
  }
```

**Comment by alexcruice** [comment]
Excellent! Thank you, that `resolutions` field did the trick. 👍
