### ISSUE TITLE
rc12 when released, very much looking forward to

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#2142]
rc12 when released, very much looking forward to

**Comment by clarkdo** [comment]
Thank you so much for your attention and supporting to Nuxt.js, this is exactly the motivation for us to develop open source project. 😸 

We are actively developing features and fixes bugs for Nuxt.js 1.0.0, progress of 1.0 is on the [Trello board](https://trello.com/b/lgy93IOl/nuxtjs-10), the next rc release is also coming soon.
 
@Atinux @alexchopin and @pi0 have taken spent a lot of time and made many fantastic improvements for this project, but our work time and energy are limited, so we all extremely welcome contributions from community.

If you really want to try the latest features, just feel free to use `dev` branch through [CONTRIBUTING.md](
https://github.com/nuxt/nuxt.js/blob/dev/CONTRIBUTING.md)

**Comment by yuchonghua** [comment]
I also look forward to r12 release

**Comment by husayt** [comment]
I can see there are huge amount of changes since rc11, my concern is that by delaying rc12 we increase amount of breaking changes. Also it would make difficult adoption of new features if there are too many for rc12.

**Comment by Atinux** [comment]
This is why next version will be 1.0

**Comment by yuchonghua** [comment]
Will it be a long time?

**Comment by yeziZ** [comment]
Very much looking forward to faster release

**Comment by coderPreacher** [comment]
Very much looking forward to faster release

**Comment by Iceygirl** [comment]
Very much looking forward to faster release

**Comment by HadiChen** [comment]
Very much looking forward to faster release

**Comment by zhong-jia-wei** [comment]
ery much looking forward to faster release

**Comment by Depravitys** [comment]
Very much looking forward to faster release

**Comment by AllenZho** [comment]
Very much looking forward to faster release

**Comment by zhong-jia-wei** [comment]
Very much looking forward to faster release

**Comment by linyueb** [comment]
Very much looking forward to faster release

**Comment by TheForgotten69** [comment]
Very much looking forward to faster release

**Comment by InstanceOfMichael** [comment]
Very much looking forward to faster release

**Comment by frizadiga** [comment]
Very much looking forward to faster release

**Comment by pi0** [comment]
https://twitter.com/nuxt_js/status/935100400415502342

We now have an unstable release channel which a new version is published automatically with all successful commit. If you want to try the last version of Nuxt.js, you can use `yarn add nuxt@next --exact` or `npm i --save-exact nuxt@next`. Be aware that it's the unstable channel until 1.0 is hit. Also for a yarn lock file workaround make sure that version is stored in `package.json` without caret (`^`) or is set to `next` tag.

PS: Every single contribution is REALLY appreciated to reach 1.0.0 as fast as possible. (See [roadmap](https://trello.com/b/lgy93IOl/nuxtjs-10))

**Comment by CrastinJiang** [comment]
Very much looking forward to faster release

**Comment by agoretsky** [comment]
Very much looking forward to faster release

**Comment by pi0** [comment]
Sorry for deleting comments. Please DO NOT spam in this thread it makes us unable to track real issues. All of us are hard working for this to happening sooner with best efforts. Unstable release channel is available now and remaining issues are publicly available in [trello board](https://trello.com/b/lgy93IOl/nuxtjs-10) which anyone can collaborate for fixing them.

Thanks for your patient :)

**Comment by yuchonghua** [comment]
Can you release a version first? I am also looking forward to the official release of 1.0, but I look forward to now have a rc12

**Comment by apertureless** [comment]
> Thanks for great work. I can see there are huge amount of changes since rc11, my concern is that by delaying rc12 we increase amount of breaking changes. Also it would make difficult adoption of new features if there are too many for rc12. Just hooks deserve a separate release.

Well, actually there should not be any big breaking changes. As RC indicates that the api is freezed and no breaking changes will come. At least if you follow semver

**Comment by clarkdo** [comment]
Spoiler: AFAIK, 1.0.0 is coming soon 😸

**Comment by PierreRambaud** [comment]
Waiting for the release too, too many times since the rc11, hope everything will still work fine :)

**Comment by yuchonghua** [comment]
Very much looking forward to release soon, but also feel so lost, because there has been no expectation of the results of the release

**Comment by PierreRambaud** [comment]
\o/
