### ISSUE TITLE
CSS Modules: Redudant styles injected to <head> when accessing page directly

### ISSUE THREAD

**Issue by thisguyscode** [nuxt/nuxt.js#2143]
# **Problem** 
Using `<style module>` in Vue single-page component to implement CSS Modules, duplicate style declarations are being injected into `<head>` but only when accessing the page directly. When accessed via router (i.e. from another page via a `<nuxt-link>`), the behaviour seems to be as expected. The number of times it's injected corresponds to the number of components in which one of its classes are 'composed'.  

## **Page accessed directly** 
![screen shot 2017-11-18 at 2 53 00 pm](https://user-images.githubusercontent.com/27633842/32981662-654fa732-cc70-11e7-9e54-3e972b5c44e1.png)

## **Page accessed via `<nuxt-link>`** 
![screen shot 2017-11-18 at 2 53 47 pm](https://user-images.githubusercontent.com/27633842/32981664-6dfda6a4-cc70-11e7-8529-b3bd1d8191ab.png)

## **Example component (ui-a.vue)** 
```html
<template>
  <section :class="$style.root"></section>
</template>

<script>
export default {}
</script>

<style lang="scss" module>

/* Dependencies
========================================================================== */
@value c-background-color "sass-loader!~/assets/styles/cosmetics/cosmetics.background-color.scss";  


/* Root class
========================================================================== */
.root {
  composes: purple  from c-background-color;
  padding: 20px;
}

</style>
```  

## **Build.extend modifications** 
```javascript
build: {
    extend (config, ctx) {
      const vueLoader = config.module.rules.find(({loader}) => loader === 'vue-loader')
      vueLoader.options.cssModules = {
        localIdentName: '[name]__[local]'
      }
      ...
   }
   ...
}
```  

## **Expected** 
I'm a noob with absolutely all of this stuff (CSS Modules and SSR in particular), but I'd expect it to behave as it does in the second screenshot. No matter how many classes `compose` `.class-X`, `class-X`'s stylesheet should only be injected once.

## **Additional Info** 
I've tried to keep the demo repo as minimal as I can. I've also published the static site to gh-pages:
REPO: https://github.com/thisguyscode/nuxt-styleguide/tree/demo
STATIC: https://thisguyscode.github.io/nuxt-styleguide/  

Really I'm new to all of this - just a designer trying to play with all you smart peoples' shiny new toys. If anyone has even a little insight it would be a great help. I've looked through issues on other related repos, and the only promising one was https://github.com/css-modules/css-modules/issues/180, but that turned out not to help. 

P.S. MAD love for the Nuxt team on all their hard work. Even a dunce like me was able to throw together a [portfolio site that doesn't suck with Nuxt](https://tinyworld.xyz). Complete overkill for the purpose of course but a lot of learning and fun was involved so thanks Nuxt!!!

**Comment by thisguyscode** [comment]
## Update
Works as expected when `mode: 'spa'` is set in `nuxt.config.js`...

So seems to be an SSR issue right?

**Comment by husayt** [comment]
@thisguyscode do you still get this in latest?
