### ISSUE TITLE
Nuxt generate - whitelist/blacklist routes

### ISSUE THREAD

**Issue by huygn** [nuxt/nuxt.js#2144]
My usecase is I need to generate only `/` and `/about` routes, other routes require user authentication, Is it possible with current nuxt version?

**Comment by thisguyscode** [comment]
If it suits your project you could make the authentication-dependent routes dynamic perhaps? I don't really know anything about authentication but that might be something you hadn't considered.

https://nuxtjs.org/api/configuration-generate#routes

**Comment by gnhuy91** [comment]
Thanks but my auth routes contains both dynamic and static routes ie. `/profile` route will show current authenticated user profile, making `/profile` a dynamic route is not ideal :/

**Comment by thisguyscode** [comment]
Just a thought. Good luck!

**Comment by hanjeahwan** [comment]
you can do authentication with middleware , if not authenticate user redirect to login page

**Comment by dan-peterson** [comment]
@huygn I posted a solution that worked for me here: https://github.com/nuxt/nuxt.js/issues/2719#issuecomment-362871101

**Comment by qm3ster** [comment]
You can also just [use the `generate.routes` property](https://nuxtjs.org/api/configuration-generate#routes) in `nuxt.config.js` to manually pick what routes to generate. It even takes an async function.
