### ISSUE TITLE
nuxt generate + i18n + dynamics routes

### ISSUE THREAD

**Issue by nicoladl** [nuxt/nuxt.js#2145]
Hi guys, i hope you can help with an issue. I'm really enthusiastic about your project so I decided to do my latest project with Nuxtjs + i18n and dynamics routes. 

I started from [i18n example](https://nuxtjs.org/examples/i18n/) and added dynamics routes imported from a json following [this example](https://github.com/nuxt/nuxt.js/issues/123#issuecomment-272246782). My page folder is setted like this:

![screen shot 2017-11-18 at 17 31 58](https://user-images.githubusercontent.com/2022727/32982538-6e13781a-cc86-11e7-9a7f-e6afac8796b8.png)

Right now i'm a little bit confused about how to generate a static package to host in a web hosting. How can I generate dynamically all the routes from the json files and how I should to manage _lang routes?

Thank you

**Comment by feedgit** [comment]
With many languages site, you can use Layout to change without changing URL. But If you want to change URL, I think you consider Vue Router with Router Modules for Nuxtjs

**Comment by nicoladl** [comment]
I have solved with a list of all routes :worried:

**Comment by timrijkse** [comment]
@nicoladl Have you looked at the generate function? This way you can do an API call and return all necessary routes. See: https://nuxtjs.org/api/configuration-generate/
