### ISSUE TITLE
Vue plugin integration 

### ISSUE THREAD

**Issue by alidcastano** [nuxt/nuxt.js#215]
I'm in the process of developing a plugin for Vue and I'm using Nuxt to create the site/docs. My problem is that when I run the site locally in the dev server, everything works fine without errors, but when the exact same code runs on my gh-pages hosted site, I get an `TypeError: Cannot read property 'somePluginProperty' of undefined`. It seems like the plugin is being installed or used differently in the build bundle. 

I tried using `if (process.BROWSER_BUILD)` but that did not solve the problem.

Interestingly, when I wrapped the `Vue.use` plugin installation code around `window.onNuxtReady(()`, I started getting the same errors locally in the dev server that I saw in my gh-pages hosted site. 

I'm not sure whether this is an Nuxt error or an error on my part. In any case, I saw an issue regarding how to [integrate Vue Material](https://github.com/nuxt/nuxt.js/issues/76) with Nuxt, so in a more general sense, **what are the steps necessary to make Vue plugins compatible with Nuxt?**

**Comment by Atinux** [comment]
Do you mind sharing the code of your plugin @alidcastano ?

**Comment by alidcastano** [comment]
Here it is: https://github.com/alidcastano/vuency

**Comment by alidcastano** [comment]
It seems people are experiencing this issue for other plugins as well, as someone recently created an [issue for vee-validate](https://github.com/nuxt/nuxt.js/issues/257)

**Comment by alexchopin** [comment]
@alidcastano most of the time it's due to plugins which not support SSR.
In your case I need more screenshot or code snippets of how you use it with Nuxt to help you.

**Comment by alidcastano** [comment]
Sorry for the delayed response, finally got a chance to look at this again.

Here is how I setup the plugin with nuxt: 
```
// plugins/vuency.js
import Vue from 'vue'
if (process.BROWSER_BUILD) {
  var Vuency = require('vuency')
  Vue.use(Vuency)
}

// nuxt.config.js
module.exports = {
  ...
  build {
    vendor: [ 'vuency']
  },
  plugins: [
   '~plugins/vuency'
  ]
}

```

Here is how I'm currently trying to install the plugin: 

```
import applyMixin from './mixin'

function plugin(Vue) {
  if (plugin.installed) return
  applyMixin(Vue) // calls Vue.mixin
}

// auto install in dist mode
if (typeof window !== 'undefined' && window.Vue) {
  plugin(window.Vue)
}

export default plugin
```

**Comment by alidcastano** [comment]
Upon closer look it seems like the problem was not with SSR compatibility but with the `nuxt generate` build for static sites.

The plugin was not being initiated under the `if (process.BROWSER_BUILD)` condition (which I originally used because I was unsure if my plugin was SSR compatible). Now that I removed that, however, it now seems to work.

**Comment by Atinux** [comment]
Ok, I close the issue so!
