### ISSUE TITLE
引入外部文件问题

### ISSUE THREAD

**Issue by duqigit** [nuxt/nuxt.js#2159]
如何引入外部js 强刷之后外部js不见了 无法找到文件 
![1ftbhf158 2bbj e 3 k t](https://user-images.githubusercontent.com/25985156/33000282-0c0ec234-cde2-11e7-9d2b-3f06e481383d.png)

**Comment by NemoAlex** [comment]
Try this out:

```
build: {
    plugins: [
      new webpack.ProvidePlugin({
        '$': 'jquery',
        'jQuery': 'jquery'
      })
    ]
}
```

**Comment by 18717700273** [comment]
为什么这样写 强制刷新 会出现$无法找到的问题 官网文档也是这样写的啊 
![og n 3t h651 co1 bo i](https://user-images.githubusercontent.com/25985156/33007810-54f4ee6e-ce0b-11e7-8242-a2ff9857b67c.png)
![ge1 o6noce46u_0v9uq cta](https://user-images.githubusercontent.com/25985156/33007820-5b65c174-ce0b-11e7-9f85-91ecac39b3e7.png)

**Comment by yoyo837** [comment]
@18717700273 你直接使用npm的jquery吧，然后配置vender打包到一起

**Comment by 18717700273** [comment]
为什么会出现这样的问题  

![Uploading 04fcdde364337ed90dd37de8b6d2817.png…]()
