### ISSUE TITLE
Nuxt introduction problem

### ISSUE THREAD

**Issue by enterlin** [nuxt/nuxt.js#2160]
jQuery requires a window with a document

![_20171120122039](https://user-images.githubusercontent.com/22594690/33002177-66603960-cded-11e7-8ebe-4ee353efca74.png)

**Comment by Yang-Travis** [comment]
Use jquery in mounted function,

**Comment by 18717700273** [comment]
why not
![9a669241421317db6164aff2288f9f8](https://user-images.githubusercontent.com/25985156/33058373-51e271dc-ceca-11e7-9d30-e1af895d2236.png)

**Comment by husayt** [comment]
See # 356 and also https://nuxtjs.org/faq

CLosing for  now.
