### ISSUE TITLE
Suggestion: server middleware watch and restart in dev mode

### ISSUE THREAD

**Issue by AlexRadch** [nuxt/nuxt.js#2161]
I suggest to add `build.serverWatch` option that will watch specified folders and restart nuxt server middleware in dev mode.

Now to rebuild nuxt server middleware you should change `nuxt.config.js` file. 

Now to solve this issue I installed `nodemon` and changed `package.json` to
```javascript
{
  "scripts": {
    "dev": "nodemon --watch api --exec \"nuxt\"",
  },
}
```

So I suggest to add `build.serverWatch` option in `nuxt.config.js` file to watch and restart nuxt server middleware in dev mode.

**Comment by Atinux** [comment]
@clarkdo is right, we cannot watch server-files (except `nuxt.config.js`) since it means `hot-reloading` on server-side and this feature does not exist right now (it needs to remove required files in cache for npm, etc).

The best solution is to use nodemon + nuxt like you did in your example :)
