### ISSUE TITLE
a css problem when running in mobile

### ISSUE THREAD

**Issue by Yang-Travis** [nuxt/nuxt.js#2162]
When I visit my page on mobile, the <html> tag width cannot full screen, see the image:

![problem](https://user-images.githubusercontent.com/31307010/33005626-9074f650-ce01-11e7-9c85-6783068f0c4f.png)

It seems html width is always 784px when the mobile screen less than 784px.
(ps: I deleted { name: 'viewport', content: 'width=device-width, initial-scale=1' } in nuxt.config.js file)

**Comment by clarkdo** [comment]
This issue is not related to Nuxt.js,  class `main-ctn` is defined on your own `default.vue`, you'd better check what's wrong with it 😄

**Comment by Yang-Travis** [comment]
@clarkdo 
My mouse is hover on html tag，not the main-ctn div. I just wanted someone to know when give a width to container div , the problem is appearance.
Thank you!
