### ISSUE TITLE
 Cannot find module '@std/esm'

### ISSUE THREAD

**Issue by lcw5945** [nuxt/nuxt.js#2163]
platform unsupported nuxt@1.0.0-rc11 › chokidar@1.7.0 › fsevents@1.1.3 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)

**Comment by phuochau** [comment]
just add `@std/esm` module by: `yarn add @std/esm --dev`
