### ISSUE TITLE
[Question] Use i18n in nuxt.config

### ISSUE THREAD

**Issue by Darkside73** [nuxt/nuxt.js#2169]
If nuxt.config contains data needs to be translated, how to apply vue-i18n there?

**Comment by clarkdo** [comment]
`nuxt.config.js` is just a pure object for initializing nuxt, it's not included in lifecycle of `vue instance`, so basically you cannot use any vue plugin in it.

If you want to use different data inside it, I suggest you use tool like [dotenv](https://github.com/motdotla/dotenv) or [node-config](https://github.com/lorenwest/node-config) to load different variable by param (such as: `locale`)

```js
// dotenv
require('dotenv').config({path: '/en'})
//data is in process.env

// node-config
const config = require('config');
config.get('EN')
```

**Comment by Darkside73** [comment]
But ```locale``` definition depends on complex conditions like cookies, local storage. What if wrap this data into callbacks and run it after all plugins?

**Comment by clarkdo** [comment]
Yes, it's ok, put i18n key into data and take out the translated text in `plugin`.

**Comment by Darkside73** [comment]
Not quite understand your suggestion, sorry. Lets consider an example:
```js
// nuxt.config.js

module.exports = {
  moduleConfig: {
    defaultTitle: 'a.translation.key'
  },
  plugins: [
    '~/plugins/i18n'
  ]
}

// i18n.js

export default ({ app }) => {
  //
}
```
I need to get option in plugin and put it back after translation?

**Comment by clarkdo** [comment]
If you wan to translate configurations which are used in building, you cannot use `plugin` way, because `plugins` is executed in vue initialization after the building.

But if you want to translate configs which are use in rendering, `plugin` is a good choice, but this is not necessary to use `nuxt.config.js`.

Can you describe you specific use case ?

**Comment by Darkside73** [comment]
I use OneSignal nuxt module, which has an options in nuxt.config. And some of this options needs to be translated

**Comment by pi0** [comment]
xref #nuxt-community/pwa-module#16

**Comment by gangsthub** [comment]
@Darkside73 are you sure you need to put translatable strings in there? https://github.com/nuxt-community/pwa-module#-onesignal-module Onsignal options doesn't seem to specify that kind of casuistic.

**Comment by Darkside73** [comment]
See https://documentation.onesignal.com/docs/customize-permission-messages#section-customize-fullscreen-permission-message for example

**Comment by gangsthub** [comment]
what about writing your own module that fetches your current lang/locale and complements @nuxtjs' official oneSignal module?

**Comment by northamerican** [comment]
just had a great setup experience with [nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n) module for nuxt. it wraps vue-i18n.
