### ISSUE TITLE
Cannot set property '$loading' of undefined on page load

### ISSUE THREAD

**Issue by pdll** [nuxt/nuxt.js#217]
All the time a'm receiving this error. What is it and how to fix?

![Alt text](https://monosnap.com/file/nnrXNN0dYWoaDA7HjaxzUhgKwGCC5D.png)

**Comment by Atinux** [comment]
We cannot help you without more code snippets.

Are you using the layouts?
If so, did you put `<nuxt/>` inside your layout?

**Comment by pdll** [comment]
Yes, i'm using layouts and i've put <nuxt /> inside

**Comment by Atinux** [comment]
Please share your code of your `layouts/default.vue`

**Comment by pdll** [comment]
`<template>
  <div class="layout">
    <template v-if="!$store.state.session.restoring">
        <div class="wrap">
            <header class="header-layout">
                <div class="header-layout__block header-layout__block_left">
                    <div :class="[ 'app-logo-mobile' ]">
                        <span :class="[ 'app-logo-mobile__burger', $store.state.menu.opened ? 'app-logo-mobile__burger_expanded' : '' ]" @click.prevent="$store.commit('menu/toggle')" />
                    </div>
                </div>
                <div class="header-layout__block header-layout__block_right">
                    <div class="appHeader__buttons">
                        <a class="appBtn appBtn_appStore" target="_blank" href="http://wroom.online/applestore" />
                        <a class="appBtn appBtn_googlePlay" target="_blank" href="http://wroom.online/googleplay" />
                    </div>
                </div>
            </header>   

            <div class="main-layout">
              <div :class="['main-layout__overlay', $store.state.menu.opened ? 'main-layout__overlay_expanded' : '' ]" />
              
              <div :class="['main-layout__block main-layout__block_menu', $store.state.menu.opened ? 'main-layout__block_menu_expanded' : '' ]">
                  
                  <div class="main-layout__block_menu-wrap">

                    <userInfo />

                    <carList />

                    <sideMenu />
                  </div>
              </div>
              <div class="main-layout__block main-layout__block_content" v-if="!$store.state.session.restoring">
                  <nuxt />
              </div>
          </div>
        </div>

        <myFooter />
    </template>
    
    <transition name="loader-transition">
      <div v-if="$store.state.session.restoring" class="loader" />
    </transition>
  </div>
</template>

<script>
import sideMenu from '../components/menu'
import userInfo from '../components/user/info'
import carList from '../components/carList'
import myFooter from '../components/footer'

export default {
  mounted () {
    this.$store.dispatch('session')
  },
  components: { sideMenu, myFooter, carList, userInfo }
}
</script>
`

**Comment by Atinux** [comment]
<nuxt/> cannot be inside a v-if. That's why you have this error.

**Comment by Twisterking** [comment]
Is there any way around this?
I would like to only render any page after the current user is fetched via an API call.
So in my `layout` I fetch the user in the `mounted()` or `created()` callback and then only render my `<nuxt/>` if the user is set. @Atinux said this is not possible. But how would I approach this problem then?

**Comment by Atinux** [comment]
You should use the store with `nuxtServerInit` action @Twisterking
