### ISSUE TITLE
custom filenames with [hash] option issue

### ISSUE THREAD

**Issue by iGalaxyz** [nuxt/nuxt.js#218]
`module.exports = {
    build: {
        filenames: {
      css: 'style.[hash:6].css'
    }
  }
}`
the Nuxt generate the ’style.7fe5aa.css‘, but when start the server
GET http://localhost:3000/_nuxt/style.[hash:6].css 404 (Not Found)

please fix it.

**Comment by Atinux** [comment]
It's a known issue since it's an upcoming feature for the 1.0.

**Comment by AlanGuo** [comment]
same problem

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋
