### ISSUE TITLE
(server) Why is 0.0.0.0 displayed as localhost?

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#2180]
What is the reason that `0.0.0.0` is forced to be displayed as `localhost` on this line: https://github.com/nuxt/nuxt.js/blob/dev/lib/core/nuxt.js#L121? I used git blame but couldnt find a reason.

The thing is, `0.0.0.0` is __not__ the same as `localhost`. Normally `localhost` runs as `127.0.0.1` so the nuxt server is only attached to the loopback interface. If you use `0.0.0.0` it means that the nuxt server will attach to _all_ available interfaces on the server: loopback, eth0, br0, enp2s0 etc.

For me its a bit confusing as I am developing on a remote server and cant therefore use the default config localhost. But when I change it to `0.0.0.0` it still reads at localhost so sometimes when I cant reach the remote server I have to check whether my config has not been overwritten. It would be helpfull if that line could be removed so it will just read `http://localhost:3000/` or `http://0.0.0.0:3000`

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1926">#c1926</a>)</em></sub></div>

**Comment by pi0** [comment]
This is because http://0.0.0.0:3000 cannot be opened in all browsers! BTW I agree with you maybe we can add some note on console that it is actually **listening to all interfaces** but is accessible with localhost too :)

**Comment by pimlie** [comment]
You mean so that you can click on that line in the console?

**Comment by pi0** [comment]
Exactly. The main intention for `OPEN` message was clicked to open in the browser.

Another idea is we can change open message to something else when not running in dev mode like: **nuxt server is listening to 0.0.0.0:3000**

**Comment by pimlie** [comment]
We could also [enumerate](https://stackoverflow.com/questions/3653065/get-local-ip-address-in-node-js) all available ip addresses on the server when `0.0.0.0` is used? Would probably be the most informational without too much of a change/impact.

**Comment by pi0** [comment]
Another option for us was using `os.hostname()`. But `localhost` is still preferred because browsers assume `localhost` and `127.0.0.1` as secure origins. So users can test many features including service workers without any problems. We can use the approach of similar CLIs that show two options if dev/prod server is listening on 0.0.0.0:

```
OPEN: http://localhost:3000
OPEN (LAN): http://hostname:3000
```

**Comment by manniL** [comment]
See #3449.

**Comment by pimlie** [comment]
@manniL Did you read @pi0 comments in my previous PR? He had a specific reason for changing `0.0.0.0` to `localhost` which I didnt understand / agree with. Therefor I closed that PR.

**Comment by manniL** [comment]
@pimlie Must have missed that. I guess we should wait for @pi0 to resolve this issue :relaxed:

**Comment by clarkdo** [comment]
Can you try latest nuxt-edge? https://github.com/nuxt/nuxt.js/pull/3529 has made some changes for it.

**Comment by Atinux** [comment]
Implemented in https://github.com/nuxt/nuxt.js/commit/a3926d5266e02038ac26aba71396906354a34dc9

It shows the ip address if listening to `0.0.0.0`

**Comment by pimlie** [comment]
Although this is a small improvement over `localhost`, I still think this implementation is wrong because it is not following expected conventions when using `0.0.0.0`. The normal convention would be to either print all ip addresses or just 0.0.0.0 it self. Printing only one address leaves room for the user to be confused and to think his configuration is not correct / not picked up or in the wrong place.

Imho if you configure a server to run on all interfaces the logs should reflect that.

**Comment by Atinux** [comment]
I see, the issue was that http://0.0.0.0:3000 does not work, and if someone listen to `0.0.0.0`, he/she knows that it's listening to all interfaces directly. We display the one that is mostly used.
