### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by emahuni** [nuxt/nuxt.js#2184]
I am very very new to this framework, in fact I am trying to see what it does and use it in a project. But I am not new to Vue, blah blah blah. Stumbled upon it in quasar gitter.

I get that in the browser when I do exactly as the installation says do.

`
vue init nuxt-community/starter-template try-nuxt
cd try-nuxt
npm install
npm run dev
`

I also noticed i needed to run in admin privileges on windows. mkdir can't create components dir or something when I do `npm run dev` in normal cmd without admin rights.

I tried this many times, in fact I wanted to use this https://github.com/quasarframework/quasar-template-nuxt initially and thought maybe it is broken since it is WIP, but when I tried to do the default template i noticed that the same error was ensuing on the framework itself. 

Am missing something or is there a bug here?

I want to try and use this framework so badly, just can't seem to see it running according to the docs.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1927">#c1927</a>)</em></sub></div>

**Comment by digitalit** [comment]
any progress on using Quasar with Nuxt?

**Comment by gomezmark** [comment]
same with mine.

**Comment by manniL** [comment]
Nuxt support from Quasar side is still in development behind the scenes ([source](https://github.com/quasarframework/quasar/issues/522#issuecomment-384550856))

Try [`create-nuxt-app`](https://github.com/nuxt-community/create-nuxt-app) if the starter template does not work :relaxed:
