### ISSUE TITLE
Execute code before first page load

### ISSUE THREAD

**Issue by Jones-S** [nuxt/nuxt.js#2186]
I want to check some url params to change the layout of my page before I initiate the page load.
I tried to use a middleware script to do so, but this middleware script seems to be ignored at the client's side at the beginning.

For now I put my code into the created method in my component, but I was wondering if there is a nicer way. Maybe using a plugin which runs at the beginning?

Thanks for input on this behalf.

Cheers

**Comment by clarkdo** [comment]
Plugin is a good choice, created will be executed at every time when navigate to the page but not first initialization.

**Comment by SnirShechter** [comment]
I stumbled upon this too. used a plugin but seems like the router instance is not yet initiated at that time, so redirect doesn't work.

Any workarounds you've found?
