### ISSUE TITLE
Deploy to Netlify

### ISSUE THREAD

**Issue by abelovic** [nuxt/nuxt.js#219]
Has anyone tried to deploy to Netlify yet? I am trying to use the starter template and it seems to deploy correctly but I get a page not found when trying to view the site. Do I need to set a public folder and if so what?

Netlify options:

Build Command: npm run build
Public folder: left blank

Log:

12:58:13 PM: Build started
12:58:13 PM: Fetching cached dependencies
12:58:13 PM: Expected build cache - but failed to find it
12:58:13 PM: No cached dependencies found. Cloning fresh repo
12:58:13 PM: git clone git@github.com:abelovic/website-nuxt
12:58:15 PM: git remote rm origin
12:58:15 PM: Preparing Git Reference refs/heads/master
12:58:16 PM: Building site
12:58:16 PM: Running build command
12:58:17 PM: Downloading and installing node v6.9.5...
12:58:17 PM: Downloading https://nodejs.org/dist/v6.9.5/node-v6.9.5-linux-x64.tar.xz...
12:58:18 PM: 0.0%
12:58:18 PM:
12:58:18 PM: 1.1%
12:58:18 PM: ### 4
12:58:18 PM: .7%
12:58:18 PM: ############## 19.
12:58:18 PM: 6%
12:58:18 PM: ############################## 4
12:58:18 PM: 2.1%
12:58:19 PM: ################################################### 71.9%
12:58:19 PM: ###################################################################
12:58:19 PM: 94.3%
12:58:19 PM: ##########################################################
12:58:19 PM: ############## 100.0%
12:58:19 PM: 
12:58:19 PM: Computing checksum with sha256sum
12:58:19 PM: Checksums matched!
12:58:20 PM: Now using node v6.9.5 (npm v3.10.10)
12:58:20 PM: Using version v6.9.5 of node
12:58:21 PM: Using /opt/buildhome/.rvm/gems/ruby-2.1.2
12:58:21 PM: Installing yarn at version 0.18.1
12:58:21 PM: Installing Yarn!
12:58:21 PM: > /opt/buildhome/.yarn already exists, possibly from a past Yarn install.
> Remove it (rm -rf /opt/buildhome/.yarn) and run this script again.
12:58:21 PM: Installing NPM modules using Yarn version 0.18.1
12:58:22 PM: yarn install v0.18.1
12:58:23 PM: [1/4] Resolving packages...
12:58:23 PM: [2/4] Fetching packages...
12:58:35 PM: warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
12:58:36 PM: info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
12:58:36 PM: [3/4] Linking dependencies...
12:58:43 PM: [4/4] Building fresh packages...
12:58:43 PM: Done in 20.86s.
12:58:43 PM: NPM modules installed using Yarn
12:58:44 PM: yarn build v0.18.1
12:58:44 PM: $ nuxt build 
12:58:45 PM: [nuxt] Building...
12:58:45 PM: Wed, 08 Feb 2017 18:58:45 GMT nuxt:build App root: /opt/build/repo
12:58:45 PM: Wed, 08 Feb 2017 18:58:45 GMT nuxt:build Generating .nuxt/ files...
12:58:45 PM: Wed, 08 Feb 2017 18:58:45 GMT nuxt:build Generating routes...
12:58:45 PM: Wed, 08 Feb 2017 18:58:45 GMT nuxt:build Generating files...
12:58:45 PM: Wed, 08 Feb 2017 18:58:45 GMT nuxt:build Building files...
12:58:52 PM: [nuxt:build:client]
Hash: 8f16e8f6ade83dd08d48
Version: webpack 2.2.1
Time: 7141ms
Asset Size Chunks Chunk Names
img/logo.ddcb767.png 6.54 kB [emitted] 
0.nuxt.bundle.js 846 bytes 0 [emitted] 
1.nuxt.bundle.js 872 bytes 1 [emitted] 
2.nuxt.bundle.js 548 bytes 2 [emitted] 
nuxt.bundle.js 39.6 kB 3 [emitted] app
vendor.bundle.js 83.5 kB 4 [emitted] vendor
style.css 1.31 kB 3 [emitted] app
style.css.map 86 bytes 3 [emitted] app
12:58:52 PM: [nuxt:build:server]
Hash: 6a306cb2f4c5dec3b684
Version: webpack 2.2.1
Time: 7126ms
Asset Size Chunks Chunk Names
img/logo.ddcb767.png 6.54 kB [emitted] 
server-bundle.js 124 kB 0 [emitted] main
12:58:52 PM: [nuxt] Building done
12:58:53 PM: Done in 8.89s.
12:58:53 PM: Cached NPM modules
12:58:53 PM: Saved Yarn cache
12:58:53 PM: Cleaning up docker container
12:58:53 PM: Deploying to CDN
12:58:53 PM: Starting deploy of directory /mnt/build-work/1486580293763719917/repo
12:58:54 PM: Going to deploy the 0 required files
12:58:54 PM: Finished deploying directory /mnt/build-work/1486580293763719917/repo
12:58:54 PM: Finished building and deploying site in 40.822541284s
12:58:54 PM: Compressing dependencies
12:59:01 PM: Uploading dependency cache
12:58:57 PM: Starting post processing
12:59:01 PM: Post processing done
12:59:02 PM: Site is live
12:59:04 PM: Finished uploading cache
12:59:05 PM: Finished processing build request

**Comment by alexchopin** [comment]
Hi,
Netlify is for static hosting so you need to generate your website with Nuxt.
Netlify Options:
- Build Cmd: npm run build && npm run generate
- Public folder: dist

**Comment by abelovic** [comment]
Oh wow that was easy! Thanks worked perfectly :)

**Comment by abelovic** [comment]
@alexchopin - I am trying to integrate vue-material and its not working when generating the pages. I understand vue-material currently does not support SSR but I only need client rendering. I followed this: https://github.com/nuxt/nuxt.js/issues/76 and it works fine when running in dev. If I generate the files and attach http-server to the dist folder I get the following :

**[nuxt.js] Cannot load components TypeError: n.setAttribute is not a function**

I'm probably missing something obvious but I don't get enough info in the compiled pages in order to figure it out :/

nuxt.config

```
    link: [
      { rel: 'icon', type: 'image/x-icon', href: 'favicon.ico' },
      { rel: 'stylesheet', href: '//fonts.googleapis.com/css?family=Roboto:300,400,500' },
      { rel: 'stylesheet', href: '//fonts.googleapis.com/icon?family=Material+Icons' },
      { rel: 'stylesheet', type: 'text/css', href: 'https://unpkg.com/vue-material@0.7.1/dist/vue-material.css' },
    ],
    plugins: [
      '~/plugins/vue-material'
    ]
```

   plugins/vue-material.js

```
   import Vue from 'vue'

   if (process.BROWSER_BUILD) {
       const VueMaterial = require('vue-material');
       Vue.use(VueMaterial);
   }
```

Is this possible to get working with the generated pages? What about disabling SSR completely? I only saw a serverRendered setting and set it to false but it didn't seem to do anything

**Comment by Atinux** [comment]
@abelovic this is planned, see #240

**Comment by altcointrading** [comment]
hello @Atinux, deployment on netlify keeps failing.

`npm run build && npm run generate` will fail with:

```
10:21:22 PM: npm
10:21:22 PM: WARN
10:21:22 PM: optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
10:21:22 PM: npm WARN
10:21:22 PM: notsup
10:21:22 PM: SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm
10:21:22 PM: WARN repo No repository field.
10:21:22 PM: npm WARN repo No license field.
10:21:22 PM: NPM modules installed
10:21:23 PM: npm
10:21:23 PM:
10:21:23 PM: ERR!
10:21:23 PM: Linux 3.19.0-66-generic
10:21:23 PM: npm
10:21:23 PM: ERR!
10:21:23 PM: argv "/opt/buildhome/.nvm/versions/node/v6.10.3/bin/node" "/opt/buildhome/.nvm/versions/node/v6.10.3/bin/npm" "run" "generate"
10:21:23 PM: npm
10:21:23 PM: ERR!
10:21:23 PM: node v6.10.3
10:21:23 PM: Cleaning up docker container
10:21:23 PM: npm
10:21:23 PM: ERR!
10:21:23 PM: npm v3.10.10
10:21:23 PM: 
10:21:23 PM: npm
10:21:23 PM: ERR! missing script: generate
10:21:23 PM: npm ERR!
10:21:23 PM: 
npm
10:21:23 PM: ERR!
10:21:23 PM: Error running command: Build script returned non-zero exit code: 1
10:21:23 PM: If you need help, you may report this error at:
npm
10:21:24 PM: ERR! <https://github.com/npm/npm/issues>
10:21:23 PM: Error running command: Build script returned non-zero exit code: 1
10:21:24 PM: 
10:21:24 PM: npm
10:21:24 PM: ERR!
10:21:24 PM: Please include the following file with any support request:
npm ERR!
10:21:24 PM: /opt/build/repo/npm-debug.log
10:21:24 PM: Cached NPM modules
10:21:24 PM: Finished processing build request
```

`npm install && npm run dev && npm run generate` fails with:

```
10:25:09 PM: [nuxt] Building done
10:25:10 PM: npm
10:25:11 PM:
10:25:11 PM: ERR!
10:25:11 PM: Linux 3.19.0-66-generic
10:25:11 PM: npm
10:25:11 PM: ERR!
10:25:11 PM:
10:25:11 PM: Cleaning up docker container
10:25:11 PM: argv "/opt/buildhome/.nvm/versions/node/v6.10.3/bin/node" "/opt/buildhome/.nvm/versions/node/v6.10.3/bin/npm" "run" "generate"
10:25:11 PM: npm
10:25:11 PM: ERR!
10:25:11 PM:
10:25:11 PM: node v6.10.3
10:25:11 PM: npm
10:25:11 PM: Error running command: Build script returned non-zero exit code: 1
10:25:11 PM: ERR!
10:25:11 PM: Error running command: Build script returned non-zero exit code: 1
10:25:11 PM:
10:25:11 PM: npm v3.10.10
10:25:12 PM: 
10:25:12 PM: npm
10:25:12 PM: ERR! missing script: generate
10:25:12 PM: Finished processing build request
10:25:12 PM: npm ERR!
10:25:12 PM: 
npm
10:25:12 PM: ERR! If you need help, you may report this error at:
npm
10:25:12 PM: ERR!
10:25:12 PM: <https://github.com/npm/npm/issues>
10:25:12 PM: 
10:25:12 PM: npm ERR!
10:25:12 PM: Please include the following file with any support request:
npm
10:25:12 PM: ERR!
10:25:12 PM: /opt/build/repo/npm-debug.log
10:25:12 PM: Cached NPM modules
```

**Comment by ImTheDeveloper** [comment]
Has this been resolved? Just about to try this now.

**Comment by Christilut** [comment]
@ImTheDeveloper deploy on netlify works fine for me

**Comment by ImTheDeveloper** [comment]
Yep works fine for me too thanks

**Comment by ianskie1234** [comment]
![capture](https://user-images.githubusercontent.com/33830479/33113080-6eeab6aa-cf91-11e7-999d-1a20f3b28eba.PNG)

When I viewed my site after deploying it, this is all I've got.

**Comment by ThatGuySam** [comment]
Mine was getting an error about the node version Netlify was using by default. I was able to get mine to work by adding NODE_VERSION to Build environment variable in Deploy Settings and setting it to any version greater than 8.0.0

![image](https://user-images.githubusercontent.com/2830379/35467890-3875ceee-02da-11e8-9bd4-ddd67d5b321d.png)
