### ISSUE TITLE
`npm run generate` have a error  'socket hang up '

### ISSUE THREAD

**Issue by enterlin** [nuxt/nuxt.js#2191]
npm error:
![npm](https://user-images.githubusercontent.com/22594690/33113647-50040db0-cf94-11e7-9c14-190a349599e2.png)

nuxt.config.js
![config](https://user-images.githubusercontent.com/22594690/33113624-325a2934-cf94-11e7-9a8c-ccfee8be168a.png)

articles.vue
![art](https://user-images.githubusercontent.com/22594690/33113683-783001a4-cf94-11e7-927e-8db6dd04819d.png)

**Comment by clarkdo** [comment]
Is the api in you screenshot available ? `nuxt generate` will call `asyncData` when generating routes html.

**Comment by daspete** [comment]
you'll need to set an interval in your generate config.... i had the same issue, i think, when you are generating a bunch of pages, all page crawl will start nearly at same time, and there is an max amount of sockets, you can start.... with the interval, you can overcome this issue...
