### ISSUE TITLE
how can i achieve the purpose of stateless login

### ISSUE THREAD

**Issue by meizijiu** [nuxt/nuxt.js#2192]
becasuse nuxt cannot  use localStorage to save user token, so i used "nuxtServerInit" API ，started local server and simulation localstorage through "req.session",.yes, it succeed. however, this req.session only save the current server, when people connect to other servers, this record has disappeared. so i want to know that how to achieve the purpose of stateless login

local server
![image](https://user-images.githubusercontent.com/10682711/33114068-0e870336-cf96-11e7-926f-ae3431178c31.png)

nuxtServerInit
![image](https://user-images.githubusercontent.com/10682711/33114084-29232ae4-cf96-11e7-9cfd-17518350eeb5.png)

**Comment by clarkdo** [comment]
Actually you can use `localStorage` in nuxt, but for supporting ssr (no `localStorage` in server side), you should change the way to store token(jwt)

You can have a look at https://github.com/clarkdo/hare/blob/dev/client/middleware/check-auth.js as a jwt auth example.
