### ISSUE TITLE
How to load on demand

### ISSUE THREAD

**Issue by snoopy83101** [nuxt/nuxt.js#2193]
One of my pages, originally small.
But I found that he loaded other layouts, as well as all the sub-pages below the resources!
What should I do to get him to load only home.vue and mini.vue and what resources are needed?

![6d7d1f42-c68c-4ceb-b5af-45bb46c570f6](https://user-images.githubusercontent.com/24613784/33117967-5028464c-cfa5-11e7-8d87-4a2dbfa8417f.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1934">#c1934</a>)</em></sub></div>

**Comment by snoopy83101** [comment]
Some pages of this project have to be applied on mobile devices.
There are also some pages to be on the PC browser

I want them to be isolated from each other and loaded as needed

**Comment by snoopy83101** [comment]
For now, is not only open two project folders?
One for mobile devices.
One for desktop browser?

**Comment by fengjiel** [comment]
#1653  You can disable this behaviour by setting `render.resourceHints: false` in your nuxt.config.js

**Comment by snoopy83101** [comment]
@fengjiel 
非常感谢您的回答, 这个配置可以避免所有的预加载,  如果进一步优化, 我仍然想使用预加载, 但是想隔离的话(pc端永远不会预加载移动端的资源, 反之亦然,毕竟预加载可以增加体验).
如果我用nuxt的话, 是不是只能开两个项目文件夹,独立两个项目了?

**Comment by zhoushuren** [comment]
@snoopy83101 我也遇到类似的问题，请问你解决了吗？

**Comment by manniL** [comment]
You can disable preloading and prefetching by setting `render.resourceHints` to false.
Selective preloading/-rendering can be set up with `render.bundleRenderer.shouldPreload`/`render.bundleRenderer.shouldPrefetch`
