### ISSUE TITLE
NFR - Purge CSS

### ISSUE THREAD

**Issue by benfavre** [nuxt/nuxt.js#2195]
Add https://github.com/FullHuman/purgecss

**Comment by gijo-varghese** [comment]
How can I use purgecss with nuxt?

**Comment by pi0** [comment]
A quick look it seems this plugin depends on static analyzing HTML files. Maybe the only chance to integrate with nuxt is using extractCSS + Nuxt generate.

**Comment by gijo-varghese** [comment]
@pi0 Can you pls explain little more about "extractCSS + Nuxt generate"

**Comment by mustardamus** [comment]
Hey, I've coded a module that uses Purgecss with Bulma: https://github.com/mustardamus/nuxt-bulma-slim
Might help you get you going with your setup.

**Comment by qm3ster** [comment]
also consider https://github.com/purifycss/purifycss

**Comment by husayt** [comment]
there is an official demo here https://github.com/FullHuman/purgecss/tree/master/examples/with-nuxt

**Comment by francoislevesque** [comment]
Here's a better way using postCSS.

First install @fullhuman/postcss-purgecss
`yarn add -D @fullhuman/postcss-purgecss` or `npm i -D @fullhuman/postcss-purgecss`

In nuxt.config.js
```
const purgecss = require('@fullhuman/postcss-purgecss')

export default {
   ...,
   build: {
      ...,
      postcss: {
          plugins: [
             purgecss({
                content: [
                   './pages/**/*.vue',
                   './layouts/**/*.vue',
                   './components/**/*.vue'
                ],
               whitelist: ['html', 'body'],
               whitelistPatterns: [/nuxt-/]
            })
         ]
      }   
   }
}

```

**Comment by AdsonCicilioti** [comment]
@francoislevesque .. thx! this works for me.
Following this solution, could you tell me how to merge all CSS files into one?
In my _nuxt folder, besides the main css, I have others referring to the specific component styles.
