### ISSUE TITLE
Vue 2.5.3 and Vue-template-compiler

### ISSUE THREAD

**Issue by ignishub** [nuxt/nuxt.js#2196]
I am using Element components element-cn.eleme.io
And they are require at least 2.5.3 version of vue. How can i update nuxt vue version?

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/issues/2142

**Comment by ignishub** [comment]
Thanks! Then i will wait for new version

**Comment by yuchonghua** [comment]
Look forward to faster solution
