### ISSUE TITLE
how import jquery plugins  in nuxt js

### ISSUE THREAD

**Issue by cybibo** [nuxt/nuxt.js#2197]
i put a jquery plugins (SuperSlide.2.1.1.js) in to the files:
assets/js/SuperSlide.2.1.1.js,

but i want to import this jquery plugins in components files by:
import SuperSlide from '~assets/js/SuperSlide.2.1.1.js'

The log:"To install them, you can run: npm install --save ~assets/js/SuperSlide.2.1.1.js ..."

Remarks:I can use "jquery", "$".

how correct  to import jquery plugins  in NuxtJs  thanks

**Comment by cybibo** [comment]
this jquery plugins only use components files

**Comment by pauldariye** [comment]
Hey @cybibo, you can create a [jquery plugin](https://nuxtjs.org/guide/plugins) and add it to the `plugins: []` array in the `next.config.js` file.

**Comment by umbrella-anton-karmazin** [comment]
@cybibo I agree with @pauldariye. Take it a look, how `axios` plugin did it.
