### ISSUE TITLE
can css add inside the page

### ISSUE THREAD

**Issue by ckken** [nuxt/nuxt.js#22]
like the next.js

**Comment by Atinux** [comment]
Hi @ckken 

Please take a look at [examples/global-css](https://github.com/nuxt/nuxt.js/tree/master/examples/global-css).

Thank you

**Comment by ckken** [comment]
I mean the style code is in current page ,for example
index.vue
```
<style lang=less>body{}</style>
```
curl /index
```
<header>
<style>
body{}
</style>
</header>
<body></body>
```

thanks for your help

**Comment by Atinux** [comment]
Actually, when the CSS is added trough the pages/*.vue file, in development mode, it will be in the JavaScript file and added dynamically in the `<head>` of the HTML file.

In production, the CSS will be extracted and injected in `style.css` which will be required in the html file, to see it, please run `nuxt build && nuxt start`

**Comment by ckken** [comment]
I know, thanks for your help, but I want add it in to page,not the common style! thanks!

**Comment by Atinux** [comment]
I am not sure to understand fully, if you want to add a CDN css for example, you can use the `head` property into your pages component or your `nuxt.config.js` file:
```js
// nuxt.config.js
module.exports = {
  // Add CDN CSS in the <head> of all our pages
  head: {
    link: [
      { rel: 'stylesheet', src: 'https://unpkg.com/element-ui/lib/theme-default/index.css' }
    ]
  }
}
```

For more details, see [examples/head-elements](https://github.com/nuxt/nuxt.js/tree/master/examples/head-elements)

**Comment by ckken** [comment]
![image](https://cloud.githubusercontent.com/assets/3890513/20707928/8bf5b698-b668-11e6-804a-a9bf20c97353.png)

**Comment by Atinux** [comment]
Please take a look at https://vuejs.org/v2/guide/migration.html#Fragment-Instances-removed to fix this error.

**Comment by fritx** [comment]
When I reload my page, contents always shows before the styles.
Anyone meet the issue?

**Comment by Atinux** [comment]
@fritx please take a look at https://nuxtjs.org/faq/css-flash

**Comment by fritx** [comment]
@Atinux oh, thanks, I missed the faq.
Btw, in another way, I had solved it by the following code:

```vue
<template>
  <div class="page" hidden>
  </div>
</template>

<script>
export default {
  mounted () {
    // https://github.com/nuxt/nuxt.js/issues/22
    this.$el.removeAttribute('hidden')
  }
}
</script>
```

**Comment by qiaoer2017** [comment]
@ckken Is that what you mean?
<img width="913" alt="2018-04-30 12 37 56" src="https://user-images.githubusercontent.com/17977613/39415230-77782ee2-4c73-11e8-8bd6-e7d76c5768c7.png">

**Comment by qiaoer2017** [comment]
@ckken is that what u mean?
![-2018-04-30-12 37 56](https://user-images.githubusercontent.com/17977613/39415284-ec24d0a6-4c73-11e8-8c64-dff5470ae66d.jpg)
