### ISSUE TITLE
Vendor is too big

### ISSUE THREAD

**Issue by snoopy83101** [nuxt/nuxt.js#2201]
Vendor is too big,
How to split into two files?

nuxt.config.js

only one build.vendor .....

I need more than one common file

**Comment by clarkdo** [comment]
Use `buid.extend` to config whatever you want in `webpack`.

https://nuxtjs.org/faq/extend-webpack#how-to-extend-webpack-config-

**Comment by snoopy83101** [comment]
@clarkdo 
thank you very mush!
Can I ask you further, configuration details should be how to write?
I tried this idea, but failed.
It may be inappropriate for me to do some things, but I do not know how to do it

**Comment by clarkdo** [comment]
Maybe sth like:

```js
module.exports = {
  build: {
    extend(config, { dev, isClient }) {
      if (isClient) {
        const vendor = config.entry.vendor
        // vendor2 is separated vendor file
        const vendor2 = [
          'vue-router',
          'vue-meta'
          // and what ever you want
        ]
        // remove from existing vendor
        config.entry.vendor = vendor.filter(x => !vendor2.includes(x))
        config.entry.vendor2 = vendor2
      }
    }
  }
}
```

**Comment by karmazzin** [comment]
@snoopy83101, pls let me know if @clarkdo 's example is working for you.
I have got strange result, vendor2 dependencies was been added into app chunks

**Comment by clarkdo** [comment]
@karmazzin 
Do you change the `filenames` ?
```js
  build: {
    filenames: {
      app: '[name].[chunkhash].js'
    }
  }
```

**Comment by snoopy83101** [comment]
config.entry.vendor = ...
 config.entry.vendor2 = ...

Is it okay to just configure config.entry?
There's no need to think about CommonsChunkPlugin?

I'll try your method. Thank you

**Comment by clarkdo** [comment]
In Nuxt, a module is extracted into the vendor chunk when it's inside node_modules and used in at-least 1/2 of the total pages.

common chunks are in `vendor` by default, if you want to change this rule, you can customize it by changing `config.plugins`.

**Comment by snoopy83101** [comment]
So, I don't have to think about CommonsChunkPlugin.
just 

module.exports = {
  build: {
    extend(config, { dev, isClient }) {
      if (isClient) {
        const vendor = config.entry.vendor
        // vendor2 is separated vendor file
        const vendor2 = [
          'vue-router',
          'vue-meta'
          // and what ever you want
        ]
        // remove from existing vendor
        config.entry.vendor = vendor.filter(x => !vendor2.includes(x))
        config.entry.vendor2 = vendor2
      }
    }
  }
}
All right?

**Comment by clarkdo** [comment]
You can also config the `filenames` as I mentioned above, or `vendor2` name will be like `app.....js`

**Comment by snoopy83101** [comment]
Combining build. filenames
E... I think I understand now!
Thank you very much for your help!

**Comment by BruceHem** [comment]
@clarkdo I followed above mentioned steps the vendor is still big, and vendor2 is created but so small.

**Comment by clarkdo** [comment]
You can try `analyse` to find which libs are big and separate them into different vendors.

**Comment by BruceHem** [comment]
I'm trying to move vuetify, vee-validate to a different bundle. but as above image it shows only 82 byes. This can't be right.

**Comment by clarkdo** [comment]
Could you provide your code ?

**Comment by BruceHem** [comment]
A part from my nuxt.config.js

```js
{
  ...
  build: {
    analyze: true,
    babel: {
      plugins: ['transform-decorators-legacy', 'transform-class-properties']
    },
    filenames: {
      app: '[name].[chunkhash].js'
    },
    extend(config) {
      const { vendor } = config.entry;
      if (vendor) {
        const vendor2 = ['axios', 'vuetify', 'vee-validate'];
        config.entry.vendor = vendor.filter(v => !vendor2.includes(v));
        config.entry.vendor2 = vendor2;
      }
    },
    vendor: [
      'axios',
      'vuetify',
      'vee-validate',
      'nuxt-class-component',
      'vue-class-component',
      'vue-property-decorator',
      'vuex-class'
    ]
  },
  // specify additional nuxt plugins
  plugins: [
    {
      src: '~/plugins/vue-notifications',
      ssr: false
    },
    '~/plugins/vee-validate',
    '~/plugins/vuetify'
  ],
  ...
}
```

**Comment by clarkdo** [comment]
Can you try to remove `commonChunksPlugin` or exclude the you vendor2 libs in `minChunks` of `commonChunksPlugin`.

```js
    // sth like
    extend(config) {
      if (process.client) {
        const plugin = config.plugins.find((plugin) => plugin.filenameTemplate === 'vendor.js')
        const old = plugin.minChunks
        plugin.minChunks = function (module, count) {
          return old(module, count) && !(/(axios)|(vuetify)|(vee-validate)/).test(module.context)
        }
      }
    }

```

**Comment by BruceHem** [comment]
@clarkdo doesn't seem to work.

**Comment by clarkdo** [comment]
Try :smile:

```js
module.exports = {
  build: {
    extend(config, { isClient }) {
      if (isClient) {
        const { vendor } = config.entry
        const vendor2 = ['axios', 'vuetify', 'vee-validate']
        config.entry.vendor = vendor.filter(v => !vendor2.includes(v))
        config.entry.vendor2 = vendor2
        const plugin = config.plugins.find((plugin) => ~plugin.chunkNames.indexOf('vendor'))
        const old = plugin.minChunks
        plugin.minChunks = function (module, count) {
          return old(module, count) && !(/(axios)|(vuetify)|(vee-validate)/).test(module.context)
        }
      }
    },
    filenames: {
      app: '[name].[chunkhash].js'
    },
    vendor: [
      'axios',
      'vuetify',
      'vee-validate'
    ]
  }
}

```

**Comment by BruceHem** [comment]
That config just made it worse, bundles are now bigger, 😭 too bad I don't know much about webpack.

**Comment by clarkdo** [comment]
It works for me:

Before:

```bash
-rw-r--r--  1 clark  staff  455189  1 16 16:44 vendor.837fce96c1f7f2ad2abc.js
```

After:

```bash
-rw-r--r--  1 clark  staff  142569  1 16 16:43 vendor.4f9def85ed3690acf031.js
-rw-r--r--  1 clark  staff  312724  1 16 16:43 vendor2.69549d11643f13001613.js
```

**Comment by BruceHem** [comment]
Here's the output, after applying above code

![screen shot 2018-01-16 at 3 50 49 pm](https://user-images.githubusercontent.com/15667259/34979839-223f6a8e-fad5-11e7-80fc-e93e5491060c.png)

**Comment by clarkdo** [comment]
That should because libs in `app` not extracted into `vendor2`, maybe you can add a `CommonsChunkPlugin` for extracting common chunks.

You can take a look at https://github.com/webpack/webpack/issues/4445#issuecomment-285187130

**Comment by pi0** [comment]
@BruceHem Would you please also share `nuxt build --analyze` results too? Also using `nuxt-edge@latest` dependency instead of `nuxt` for latest changes :)

**Comment by clarkdo** [comment]
How about:

```js

const webpack = require('webpack')
module.exports = {
  build: {
    extend(config, { isClient }) {
      if (isClient) {
        config.entry.vendor = config.entry.vendor.filter(v => !['axios', 'vuetify', 'vee-validate'].includes(v))
        config.plugins.unshift(
          new webpack.optimize.CommonsChunkPlugin({
            name: 'app',
            children: true,
            async: 'vendor2',
            minChunks(module, count) {
              return /(axios)|(vuetify)|(vee-validate)/.test(module.context)
            }
          })
        )
      }
    },
    vendor: [
      'axios',
      'vuetify',
      'vee-validate'
    ]
  }
}

```

**Comment by francescobm** [comment]
@clarkdo thanks for the examples provided, I'm having the same issue. 

My vendor chunk is about 800KB. I tried the solutions suggested, in the first case vendor2 is a few bytes, in the second case app and vendor are bigger, as it happened to @BruceHem.

@pi0 If I run analyze the interface doesn't show the vendor2 chunk, all the node_modules I associated to it seems to be still under the vendor chunk.

**Comment by francescobm** [comment]
@pi0 actually the vendor2 is now available in anlayze view, however its node modules are duplicated in app chunk.

<img width="457" alt="screen shot 2018-01-17 at 17 43 01" src="https://user-images.githubusercontent.com/29886251/35055036-734cd284-fbae-11e7-8498-a4fdb2c20a33.png">

**Comment by pi0** [comment]
Trello card created (https://trello.com/c/5bL1gNbg/78-vendor-optimizations)

**Comment by francescobm** [comment]
Thanks to the Nuxt.js Team, you are doing an awesome work!

**Comment by BruceHem** [comment]
@pi0 nice 🖖

**Comment by pxwee5** [comment]
This definitely needs work. I have less than 10 pages and my `vendor.js` is 200kb. 
`app.js`is around 50 kb. 

I don't feel like I have written so much though.

**Comment by pi0** [comment]
Good news: With Webpack 4 vendor will be automatically split into smaller chunks for both performances and long-term caching. We are going to work on it.

**Comment by NicoPennec** [comment]
I'm working on an PR about that (webpack 3)

**Comment by NicoPennec** [comment]
@pi0 @clarkdo 
my proposal: https://github.com/nuxt/nuxt.js/pull/2687

**Comment by besnikh** [comment]
@ALL any update? My vendor is 1.75MB I want to split it :( I don't know how though..

This is part of my `nuxt.config.js`

```
build: {
    babel: {
      plugins: [
        ["transform-imports", {
          "vuetify": {
            "transform": "vuetify/es5/components/${member}",
            "preventFullImport": true
          }
        }]
      ]
    },
    // cssSourceMap: false, // add this into the nuxt.config
    extend (config) {
      config.devtool = false
    },
    vendor: [
      // '~/plugins/vuetify.js',
      // '~/plugins/vee-validate.js',
      'firebase'
    ],
    optimization: {
      splitChunks: {
        chunks: 'all',
        automaticNameDelimiter: '.',
        name: true,
        cacheGroups: {},
        minSize: 100000,
        maxSize: 100000
      }
    },
    maxChunkSize: 100000,
    extractCSS: true,
    /*
    ** Run ESLint on save
    */
    extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      if (ctx.isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vuetify/]
          })
        ]
      }
    }
  }
```

**Comment by clarkdo** [comment]
@besnikh `vendor` has been deprecated due to `webpack4` has used `SplitChunksPlugin` to automatically generate common chunks.

The reason may be because your config doesn't meet [default conditions](https://webpack.js.org/plugins/split-chunks-plugin/#defaults) of the strategy, try to change `maxAsyncRequests` or `maxInitialRequests` or provide a reproducible repo, but `webpack` default configurations should be the best practice and recommendation.

**Comment by P4sca1** [comment]
I just updated to `nuxt-edge` (and `webpack 4`), but I still get big bundle sizes:

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  5ee7cf173fbbbd29401e.js (1.19 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (1000 KiB). This can impact web performance.
Entrypoints:
  app (1.4 MiB)
      1d2359df0b3a4c1ac2bc.js
      5ee7cf173fbbbd29401e.js
      a51c2c1bcf724420734d.js
```

Is there anything that needs to be changed / configured?

My `nuxt.config.js` does not have changed any `build` settings.

**Comment by willin** [comment]
there's no vendor any more? 

where to config vendors.app ?


```
yarn build
yarn run v1.9.4
$ NODE_ENV=production nuxt build
[15:14:22] Building project
[15:14:22] Builder initialized
[15:14:22] Nuxt files generated
undefined
undefined
[15:14:23] Compiling client
[15:14:35] Compiled client in 13s

Hash: 9c140484c85ee4351c71
Version: webpack 4.17.1
Time: 12716ms
Built at: 2018-08-30 15:14:35
                  Asset       Size  Chunks                    Chunk Names
a8fb3b858aa32b7162be.js    215 KiB       0  [emitted]         app
0ab00c424448a26b6ae7.js  556 bytes       1  [emitted]         pages/index
1f1e22a52a1f27462980.js    133 KiB       2  [emitted]         commons.app
94284cfffbf18ce8aa7e.js    378 KiB       3  [emitted]  [big]  vendors.app
               LICENSES   76.1 KiB          [emitted]
 + 3 hidden assets
Entrypoint app = 1f1e22a52a1f27462980.js 94284cfffbf18ce8aa7e.js a8fb3b858aa32b7162be.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  94284cfffbf18ce8aa7e.js (378 KiB)
[15:14:35] Compiling server
Webpack Bundle Analyzer saved report to /Users/willin/Desktop/nuxt-edge-split-vendors/.nuxt/stats/client.html
[15:14:43] Compiled server in 8s

Hash: d246aef4a1691711c8dc
Version: webpack 4.17.1
Time: 7700ms
Built at: 2018-08-30 15:14:43
             Asset     Size  Chunks             Chunk Names
server-bundle.json  605 KiB          [emitted]
Entrypoint app = server-bundle.js server-bundle.js.map
Webpack Bundle Analyzer saved stats file to /Users/willin/Desktop/nuxt-edge-split-vendors/.nuxt/stats/client.json
✨  Done in 23.45s.
```

**Comment by cmzz** [comment]
config.entry is null

**Comment by clarkdo** [comment]
FYI https://github.com/nuxt/nuxt.js/issues/5545#issuecomment-484577422

**Comment by daggerok** [comment]
for me it was just enough to reduce chunk sizes, so I hack it like so:

```js
    extend (config, ctx) {
      if (ctx && ctx.isClient) {
        config.optimization.splitChunks.maxSize = 29696
      }
    }
```

**Comment by mandaputtra** [comment]
@daggerok How about the entry point too big?

**Comment by daggerok** [comment]
@mandaputtra 
entry point also will be reduce by chunks size. just try configure like i did and see what will happen

**Comment by mandaputtra** [comment]
@daggerok
Okay I'm understand, the entry point is where you firstload the app. Thanks your solution worked, I just need to found what the best `config.optimization.splitChunks.maxSize` for me.

**Comment by ryzexsp** [comment]
```
build: {
    extractCSS: true,
    optimization :{
      splitChunks: {
        chunks: 'all',
        automaticNameDelimiter: '.',
        name: 'test',
        maxSize : 256000
      }
    }
  },
```
