### ISSUE TITLE
Server Middleware, handling Aliases (404 redirection)

### ISSUE THREAD

**Issue by francescobm** [nuxt/nuxt.js#2204]
Hi,
for some reasons I have to handle my vue-router aliases and some times return a 404 if some given conditions are not respected. 
I see I can easily set res status to 404 like below:

```javascript
module.exports = function (req, res, next) {
  // check incoming request and do some logic
  // ......................
  // then check if the condition is true and eventually redirect to 404
  if (aliasesLookup[req.path] && aliasesLookup[req.path] !== country) {
    res.status(404).send('Not found')
    return
  }
  next()
}
```
However, I would like also to set the nuxt.js 404 template, is there any way to achieve that? At the moment I just get a white page with the 404 error in console.

**Comment by clarkdo** [comment]
Use [error page](https://nuxtjs.org/guide/views#error-page) and `error.statusCode` to customize 404 error page.

```vue
// layouts/error.vue
<template>
  <div class="container">
    <h1 v-if="error.statusCode === 404">Page not found</h1>
    <h1 v-else>An error occurred</h1>
    <nuxt-link to="/">Home page</nuxt-link>
  </div>
</template>

<script>
export default {
  props: ['error']
}
</script>
```

**Comment by francescobm** [comment]
Thanks @clarkdo, unfortunately it doesn't seem to work like that.
I am using a server middleware in nuxt.config.js
```
// nuxt.config.js
serverMiddleware: [
   '~/routes/alias-handler'
]
```

```
// aliasHanlder.js
module.exports = function (req, res, next) {
  // check incoming request and do some logic
  // ......................
  // then check if the condition is true and eventually redirect to 404
  if (aliasesLookup[req.path] && aliasesLookup[req.path] !== country) {
    res.status(404).send('Not found')
    return
  }
  next()
}
```
I correctly get the 404 on the Front End but I can't seem to get any template associated to it, not even the standard nuxt.js error template.

**Comment by clarkdo** [comment]
Try below together with `layout/error.vue`

```js
module.exports = function (req, res, next) {
  // check incoming request and do some logic
  // ......................
  // then check if the condition is true and eventually redirect to 404
  if (aliasesLookup[req.path] && aliasesLookup[req.path] !== country) {
      next({ statusCode: 404, message: 'not found'})
  } else {
      next()
  }
}
``

**Comment by francescobm** [comment]
Sorry for the late reply, still not working, I will investigate and I'll update this thread if I find any solution, thanks for your help

**Comment by clarkdo** [comment]
Pls check: https://github.com/clarkdo/nuxt-issues/tree/issue_2204

Visit: http://localhost:3000/test404

**Comment by sparecycles** [comment]
Have we considered using [`validate()`](https://nuxtjs.org/guide/routing#validate-route-params) within the pages?

> ```js
> export default {
>   validate ({ params }) {
>     // Must be a number
>     return /^\d+$/.test(params.id)
>   }
> }
> ```
>
> If the validate method does not return `true`, Nuxt.js will automatically load the 404 error page.

**Comment by francescobm** [comment]
Hi @sparecycles , yes indeed, this is quite an old discussion, after the validate method release, I used it to solve my problem

**Comment by sparecycles** [comment]
Great to hear it.  I was having a similar issue and just thought I'd drop a note here in case anyone else was stuck.
