### ISSUE TITLE
Event listener doesn't remove when route to other page

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2206]
I have scroll event listeners in one of the components that I am using on particular Page. The problem is this event listeners is triggered even after I navigate out of this page (where I am using this component). How to fix it? I got console full of errors. 

```js
created () {
    if (process.browser) {
      window.addEventListener('scroll', this.parallax)
    }
  },
  destroyed () {
    if (process.browser) {
      window.removeEventListener('scroll', this.parallax)
    }
  }
```

**Comment by Gomah** [comment]
What about `beforeDestroy()` ?

**Comment by iamdubx** [comment]
Instead of `destroyed`? Same result.

**Comment by iamdubx** [comment]
Nevermind, I fix it :smile:
