### ISSUE TITLE
Show default Progress Bar when loading data

### ISSUE THREAD

**Issue by FabianEllenberger** [nuxt/nuxt.js#2208]
Is there any best practise to display the lovely ```Progress bar``` which comes with nuxt, at any time from a component or from a mutation in the store (for example: showing the progress of data being loaded or a form being submitted)?

I tried it with calling ```this.$nuxt.$loading.start()``` which does not work all the time (at some points ```$nuxt``` was undefined).

Big thanks in advance!

**Comment by pi0** [comment]
Hi. Yes it is a good idea using a unified loading indicator everywhere IMO. As loading is for client side, we can use `$nuxt.$loading.start()` (`window.$nuxt`) which should be always available.

**Comment by FabianEllenberger** [comment]
@pi0 Great, thanks! Yes as long as it is on client-side this solution should be fine :-)
