### ISSUE TITLE
nuxt generate fails with a lot of dynamic routes

### ISSUE THREAD

**Issue by voidale** [nuxt/nuxt.js#221]
`npm run generate` was working great, until I added bunch of dynamic routes and it seems to be too heavy for it to generate? There are random times where the ms is "3-4" and if I check the folder it's empty, also `npm run generate` doesn't really ever finish it throws because it fails to retrieve from the api inside the data method (it's local and always returns 202 no really any api issues)

![screen shot 2017-02-08 at 21 56 09](https://cloud.githubusercontent.com/assets/4450730/22757090/c35fb6c4-ee49-11e6-80fd-c0d80923beb3.png)

Here is the error (it's fixed data so I always expect to find the name)
![screen shot 2017-02-08 at 22 02 42](https://cloud.githubusercontent.com/assets/4450730/22757234/59f7a2fe-ee4a-11e6-9685-bd6da1504336.png)

It might be that the express server hangs? that will be totally weird I tested it while generate is running always working, it happens with routes that have data method:
````
<script>
import axios from 'axios';
import SearchForm from '~components/search-form.vue';
import Card from '~components/card.vue';
export default {
  components: {
    SearchForm,
    Card,
  },
  layout: 'page',
  head() {
    return {
      title: `Page for ${this.airport.name} | Website`,
    }
  },
  data({ params, error }) {
    const slug = params.slug;
    return axios.get(`http://localhost:3000/api/airport/${slug}`)
    .then((res) => {
      return {
        airport: res.data.airport,
      };
    }).catch((err) => {
      error({ statusCode: 404, message: 'Countries page not found' })
    });
  }
}
</script>
````

**Comment by Atinux** [comment]
When launching ˋnuxt generate`, the server is not working so it might be the error.

Can you try to launch your server with `nuxt dev` and in another tab of your terminal ˋnuxt generateˋ?

**Comment by voidale** [comment]
@Atinux of course I'm running the server there is issues with the generation script. the image shows that some routes work and some dont. They all have ssr data method.

**Comment by Atinux** [comment]
It's weird since our website https://github.com/nuxt/nuxtjs.org is also generated and most of the pages are with asynchronous data with API call.

The problem might come from you API call `http://localhost:3000/api/airport/${slug}` which does not return the `airport` data.

Try to debug it with:

```js
data({ params, error }) {
    const slug = params.slug;
    return axios.get(`http://localhost:3000/api/airport/${slug}`)
    .then((res) => {
      console.log('Data returned', res.data)
      return {
        airport: res.data.airport,
      };
    }).catch((err) => {
      console.log('Error returned', err)
      error({ statusCode: 404, message: 'Countries page not found' })
    });
  }
```

And try to run your server + `nuxt generate` and see what's displayed please.

**Comment by voidale** [comment]
I will double check but it's not the first time I generate the static files
it started to happen after i went past the 10's to 10,000s of pages. I will
try to debug this one in more detail.

**Comment by voidale** [comment]
It seems to work now after removing a big json return from the API and returning just what's needed also it went down from 250ms per generate to 20ms, I guess I probably chocked it with so much data (2,000 items array) (or i had wrong slug somewhere over there) I think the issue persistent and might be an issue in the future unless we optimize it but it's definitely not required at the moment was able to generate it successfully thanks a lot! nuxt is awesome! ~20,000 static html pages 👍

**Comment by Atinux** [comment]
20 000 static HTML page 😱

Amazing 🙌

**Comment by falstack** [comment]
i have the same problem, i want use nginx , no any node.js server, that's possible?
