### ISSUE TITLE
Why all links has class 'nuxt-link-active'

### ISSUE THREAD

**Issue by hackuun** [nuxt/nuxt.js#2214]
I have a Breadcrumbs list

```html
<nav aria-label="breadcrumb" role="navigation">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><nuxt-link to="/">Main</nuxt-link></li>
        <li class="breadcrumb-item"><nuxt-link to="/articles/">Articles</nuxt-link></li>
        <li class="breadcrumb-item"><nuxt-link :to="`/articles/${article.section}`">{{ article.section }}</nuxt-link></li>
      </ol>
    </nav>
```

For some reason all links has CSS class `nuxt-link-active` so I can't style them properly. Why is this happening?

**Comment by tforssander** [comment]
You should try adding the `exact` prop on the `<nuxt-link>` component.

From the [vue-router documentation](https://router.vuejs.org/en/api/router-link.html):

> The default active class matching behavior is inclusive match. For example, <router-link to="/a"> will get this class applied as long as the current path starts with /a/ or is /a.
> 
> One consequence of this is that <router-link to="/"> will be active for every route! To force the link into "exact match mode", use the exact prop:
> ```
> 
> <router-link to="/" exact>
> ```

You can play around in https://jsfiddle.net/8xrk1n9f/ to see the different effects.

**Comment by iamdubx** [comment]
I tried `exact`, no effect. It removes `nuxt-link-active` only from `/` route @tforssander

**Comment by apexJCL** [comment]
@iamdubx Have you tried setting up the configuration for active classes on `nuxt.config.js`?

Also, I _think_ `exact` only works properly when passing an object to the `to` attribute, like

```
<router-link :to="{name: 'my-path'}" exact>My link</router-link>
```

**Comment by qm3ster** [comment]
@hackuun did you add `exact` to all `router-link`/`nuxt-link`?
