### ISSUE TITLE
get / set cookie from ssr without using server middleware

### ISSUE THREAD

**Issue by agencewebcom** [nuxt/nuxt.js#2215]
Hello,
I try to find a solution, but I'm not sure that it really exists. I have a distant api, so I don't need/want to use any api on the server side using server middleware, I just want to set / get cookies or data on local storage from my store.

Is it possible ?

**Comment by 0pt1m1z3r** [comment]
You can get cookies from `context.req` and set with `context.res`

**Comment by C4Grey** [comment]
Yes, it is. First, you may use nuxt-ommunity/axios-module. Also you can do it manually, via Nuxt context injection, ofr example, in the `asynData` hook:
```js
async asyncData({req}) {
      const result = {}
      const headers = req && req.headers
      const {data} = await axios('/api/entries', {headers: headers})
}
```
So cookies along with other headers will be proxied to API server from a client, or you may filter only requried header and use it.

**Comment by agencewebcom** [comment]
Great!!
Thank you!

**Comment by agencewebcom** [comment]
I will use nuxt/axios module to store the token and other informations wich will be shared with all my requests, but yes, the module do exactly the same thing you told me.
But, if I want to store some user information and don't want to be limited by the max size of the cookies, it's better to use the local storage, wich will be accessible only from the client side, or an express route (such as /server/save-my-data) with server middleware and store it in the session?
If you think that the question is not inherent to post, I will create another question
Thank you

**Comment by boicott** [comment]
¿Maybe an example of this? I trying to do the same, i need to storage session cookie
