### ISSUE TITLE
How can i take my ssr-project to nginx?

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#2216]
Now i have complete a project,but there is a problem,what should i do to take it to nginx

**Comment by Serg-de-Adelantado** [comment]
[Reverse proxy](https://www.nginx.com/resources/admin-guide/reverse-proxy/) to the rescue! Here is a simple example:
```nginx
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```
It's very basic but may help you to move forward.

**Comment by InstanceOfMichael** [comment]
Correct me if I'm wrong, but any NodeJS tutorial should work for this. Are you deploying to a single VPS (how many cores?) or are you deploying to an autoscaling environment like AWS EC2 + CodeDeploy or Heroku or Zeit Now?
