### ISSUE TITLE
Sticky footer with flexbox.

### ISSUE THREAD

**Issue by nucamoz** [nuxt/nuxt.js#222]
I see no way how to implement this code into nuxt - https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

If I put 

`  display: flex;
  min-height: 100vh;
  flex-direction: column;`

into main.css 'body', then there's is now way to assign flex: 1 to footer. 

You should put sticky footer into default nuxt.js template, it's looks kinda strange without it.

**Comment by alexchopin** [comment]
You need to do it in the `layouts/default.vue` template file.
Have checked the HTML source code generated by Nuxt before you posted this issue?
Nuxt generated source code:
```html
<body>
<div id="__nuxt">
// Default Layout Content HERE
</div>
</body>
```
