### ISSUE TITLE
Prevent nuxt from eager-loading pages

### ISSUE THREAD

**Issue by buhrmi** [nuxt/nuxt.js#2221]
Hello,

so when I visit my nuxt app, the app automatically loads all the pages in the background. On content heavy sites with lots of pages, I want to prevent nuxt from loading the page before the user actually navigates to them. Is that somehow possible? It's just to save on bandwidth.

**Comment by buhrmi** [comment]
To explain this a bit better, when I add a `.vue` file in the `pages` directory, it's being downloaded even though it's not accessed. You can see it in the browser dev console. If my website is something like a blog, it's downloading lots of content even though it's never accessed. It would be nice if pages could be marked as "download on demand" or something like that.

**Comment by gustojs** [comment]
https://nuxtjs.org/api/configuration-render#resourcehints

**Comment by buhrmi** [comment]
@gustojs riiight, something like this but on a per-page basis. maybe something like 

```
<script>
export default {
  data: {..},
  preload: false
}
</script>
```

**Comment by buhrmi** [comment]
Found a duplicate https://github.com/nuxt/nuxt.js/issues/1838
