### ISSUE TITLE
How to use seperate/adpative template for Desktop and mobile web

### ISSUE THREAD

**Issue by fahidmohammad** [nuxt/nuxt.js#2223]
Im looking for an option to have a separate template for both Desktop and Mobile Web. 

**Note:** Not a responsive template rather a complete separate template based on device detection.

**Example:** https://www.cleartrip.com try this site on desktop and mobile, its an adaptive layout.

**Comment by clarkdo** [comment]
I suggest you can use `plugin` to detect if device is `browser` and `mobile`, and set device type into `store`.

Then use async and dynamic component to load different component and layout, maybe sth like:

```vue
<template>
  <div>
    <component :is="component"/>
  </div>
</template>

<script>
export default {
  layout: () => this.$store.state.device ? 'mobile' : 'default',
  components: {
    'mobile': () => import('./mobile-component'),
    'browser': () => import('./browser-component')
  },
  beforeCreate() {
    this.component = this.$store.state.device
  }
}
</script>
```

**Comment by fahidmohammad** [comment]
Some what i did this for now, not sure whether its a better way of handling things.
```
const { Nuxt, Builder } = require('nuxt')
const express = require('express');
const app = express()
const path = require('path')
const dc = require('./libs/device-check')
const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3000

app.set('port', port)


// Import and Set Nuxt.js options
let mobileConfig = require('./app/mobile/nuxt.config.js')
let desktopConfig = require('./app/desktop/nuxt.config.js')


mobileConfig.dev = !(process.env.NODE_ENV === 'production')
desktopConfig.dev = !(process.env.NODE_ENV === 'production')

// Init Nuxt.js
const nuxtMobile = new Nuxt(mobileConfig)
const nuxtDesktop = new Nuxt(desktopConfig)

// Build only in dev mode
if (mobileConfig.dev) {
  const builder = new Builder(nuxtMobile)
  builder.build()
}
if (desktopConfig.dev) {
  const builder = new Builder(nuxtDesktop)
  builder.build()
}
app.use(express.static(path.join(__dirname, 'static')));
// Give nuxt middleware to express
app.use(function (req, res, next) {
	if(dc(req)==='v1'){ 
		console.log('Mobile')
		nuxtMobile.render(req, res)	  
	}else{
		console.log('Desktop')
		nuxtDesktop.render(req, res)
	}
})

// Listen the server
app.listen(port, host)
console.log('Server listening on ' + host + ':' + port) 
```

**Comment by fahidmohammad** [comment]
#

**Comment by pauldariye** [comment]
@clarkdo, trying to implement something similar to what you have in the example you shared above but it's not working. I'm unable to access the `$store` in `layout()`. Am I missing something perhaps? Re-read the docs as well but can't tell for sure.

**Comment by qm3ster** [comment]
@clarkdo How would that work with arrow functions? Isn't the `this` unbound?

**Comment by pauldariye** [comment]
I got it to work with a simple middleware @qm3ster. And I used essentially what @clarkdo recommended.

file: `middleware/layout.js`

```js
export default function (context) {
  const { app: { store } } = context
    if (store.state.page.layout) {
       context.layout = store.state.page.layout
     } else {
       context.layout = 'default'
     }
}
```

**Comment by qm3ster** [comment]
That makes sense.

**Comment by clarkdo** [comment]
@qm3ster
You are right, arrow is not appropriate here, your solution is good, thank you!

**Comment by Dhruvi16** [comment]
I am not sure how to do this can you explain how I can implement this? Any help will be appreciated.
Thanks

**Comment by pratik149** [comment]
@Dhruvi16 Now there is a package called @nuxtjs/device which can help you achieve this, and is maintained by Nuxt community only. An example has been given in its documentation.

Here is the link, check it out.
https://github.com/nuxt-community/device-module#nuxtjsdevice

**Comment by Dhruvi16** [comment]
Hey! @pratik149 I am unable to make this module work. I did exactly what the documentations says but $device is not working.

**Comment by pratik149** [comment]
@Dhruvi16 Where is it not working? In the template or script? For using it in script you are suppose to use `this` keyword like this, this.$device

**Comment by Dhruvi16** [comment]
Hey! @pratik149 I am using it in template and it is showing me $device is undefined.
