### ISSUE TITLE
Why process.env.NODE_ENV is undefined?

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#2226]
I want to judge is development or producetion, but process.env.NODE_ENV is undefined, so anything else can help me?

**Comment by 0pt1m1z3r** [comment]
Please, show your code.
You can use `context.isDev`.

**Comment by ouyangxiaoai** [comment]
@0pt1m1z3r I want to use diffenrent modules in dev or production.
for examples, the proxy modules,i want to take it out in production
