### ISSUE TITLE
Improve webpack build time

### ISSUE THREAD

**Issue by Drezdenozk** [nuxt/nuxt.js#2228]
Hello! Can anybody explain some examples nuxt.config.js with webpack dll \ webpack refference dll \ HardSourceWebpackPlugin plugin?
"Build" for my project are boring ( 10+ minutes for admin panel

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1958">#c1958</a>)</em></sub></div>

**Comment by EmmanuelBeziat** [comment]
One of my nuxt website has the same problem (very long build time), so I wouldn't say no to a significative perf improvement, if it can be done someway.

**Comment by pi0** [comment]
Lots of new perf improvements will come which each release with both our web pack build configs and webpack itself. And will try to make more improvements when possible. BTW experimental dll support is now implemented and HardSourceWebpackPlugin is also a nice idea :)
