### ISSUE TITLE
how to add script in header

### ISSUE THREAD

**Issue by yingye** [nuxt/nuxt.js#2230]
I want to import a script in the header, but I can't success. 
En, other question is how to inline this js in the header.
This is my code. 
nuxt.config.js:
```
module.exports = {
  head: {
    title: 'myTitle',
    meta: [
      { charset: 'utf-8' },
      { 'http-equiv': 'pragma', content: 'no-cache' },
      { 'http-equiv': 'cache-control', content: 'no-cache' },
      { 'http-equiv': 'expires', content: '0' },
      { content: 'telephone=no', name: 'format-detection' }
    ],
    script: [
      { src: '~/assets/js/flexible.js' }
    ]
  },
  css: ['~/assets/css/main.css']
}
```

**Comment by clarkdo** [comment]
`~` is alias for webpack building. `head` is used for loading external script, script will not be included in bundled js.

You can move `flexible.js` into `static` and change `script` to ` { src: '/js/flexible.js' }`

**Comment by yingye** [comment]
Thanks for your answer, but how to inline this js in html?

**Comment by clarkdo** [comment]
You can use `innerHTML` to inline the script, but currently `vue-meta` doesn't support inline script loaded by `src`.

https://github.com/declandewet/vue-meta#script-object

**Comment by yingye** [comment]
I do this by your suggestion, but I find it translates quotes. 
This is my code.
```
head: {
    title: 'myTitle',
    meta: [
      { charset: 'utf-8' },
      { 'http-equiv': 'pragma', content: 'no-cache' },
      { 'http-equiv': 'cache-control', content: 'no-cache' },
      { 'http-equiv': 'expires', content: '0' },
      { content: 'telephone=no', name: 'format-detection' }
    ],
    script: [
      { innerHTML: 'console.log("hello")', type: 'text/javascript', charset: 'utf-8'}
    ]
  },
```
html:
```
<script data-n-head="true" type="text/javascript" charset="utf-8">console.log(&quot;hello&quot;)</script>
```

**Comment by clarkdo** [comment]
You need to add ` __dangerouslyDisableSanitizers: ['script']` in `head`

https://github.com/declandewet/vue-meta#__dangerouslydisablesanitizers-string

**Comment by yingye** [comment]
Thanks!

**Comment by starhao** [comment]
> `~` is alias for webpack building. `head` is used for loading external script, script will not be included in bundled js.
> 
> You can move `flexible.js` into `static` and change `script` to `{ src: '/js/flexible.js' }`

for production env,  in my project this way is not available , the error is (404)Not Found , how to fix? thanks

**Comment by abh153k** [comment]
> `~` is alias for webpack building. `head` is used for loading external script, script will not be included in bundled js.
> 
> You can move `flexible.js` into <code>static<b><i>/js</i></b></code> and change `script` to ` { src: '/js/flexible.js' }`

FTFY
