### ISSUE TITLE
[docs] What does inject do?

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#2233]
### [In docs, `inject` goes unused](https://nuxtjs.org/guide/plugins#inject-in-root-amp-context):
```js
export default ({ app }, inject) => {
  // Set `i18n` instance on `app`
  // This way we can use it in middleware and pages `asyncData`/`fetch`
  app.i18n = new VueI18n({
    /* `VueI18n` options... */
  })
}
however, it is named in the function signature.

```
### [Relese notes for `v1.0.0-rc3`](https://nuxtjs.org/guide/release-notes#breaking-changes) say a previous version called `injectAs` was removed:
> - `injectAs` has been removed in plugins, you can inject your plugins by accessing `app` (see [example](https://github.com/nuxt/nuxt.js/blob/dev/examples/i18n/plugins/i18n.js))

### [It is reintroduced as `inject` in v1.0.0-rc7](https://nuxtjs.org/guide/release-notes#v1.0.0-rc7)

This version is only actually used in one file which is not featured in the examples on the site:
https://github.com/nuxt/nuxt.js/blob/ffe1b6d8dc092f22b45b765f296b0700fd05eae9/examples/with-cookies/plugins/cookies.js#L19

In `v1.0.0-rc11` it currently works.

## Question
When to use `context.app.x =` vs `inject('x',`?

**Comment by clarkdo** [comment]
Thank you for your support of Nuxt.js. 😸 
`inject` is used for add plugin onto both Vue instance and Nuxt app.
```js
inject('cookies', new Vue({
  // ...
}))
```
Through `inject`, you can: 
1. app.$cookies
1. this.$cookies in vue components
1. this.$cookies in store actions/mutations

The documentation is exactly not clear, we will fix it soon.

**Comment by qm3ster** [comment]
Yes, I have seen the inject code as well as that nice comment in cookies ![image](https://user-images.githubusercontent.com/10551234/33234869-20f7d098-d236-11e7-806e-7aad20fa27e5.png)
So they are basically mutually exclusive.
IMO there should be an exhaustive explanation of where and how `app` can be accessed, whether `app.i18n` or `app.$cookies`. Although that's a stock Vue concern, one of nuxt's expressed niches is *baby's first Vue* and that would certainly help.

**Comment by pauldariye** [comment]
I think @clarkdo meant thanks for showing support by raising an important flag in the missing `inject` documentation. Raising an issue shows support, so thank you as well :)

**Comment by husayt** [comment]
@qm3ster your comment sounds really funny now. As they say, you never know. :laughing: 

Anyway this seems to be resolved now. Closing.

Here is doc 
https://nuxtjs.org/guide/plugins#inject-in-root-amp-context

**Comment by frankier** [comment]
That example does not show usage of `inject', nor does it explain its benefits versus shoving stuff onto Vue or app.

**Comment by dotnetCarpenter** [comment]
@frankier the only difference/benefit I seem is convenience. You don't have to `import Vue` to get the plugin in your components. `this.$myPlugin` has it in all components and store actions.

**Comment by frankier** [comment]
It also does the correct thing with regards to vuex, depending on whether it's installed not. This should all be in the docs.

**Comment by dotnetCarpenter** [comment]
@frankier you should make a PR to https://github.com/nuxt/docs

Perhaps [the web worker example](https://github.com/nuxt/nuxt.js/blob/dev/examples/web-worker/plugins/inject-ww.js) is a good start?

**Comment by Freakspot** [comment]
The doc you linked is found quite easily @dotnetCarpenter, but as @frankier pointed out, it does not show the usage of `inject`. It's not even so much the advantages it brings imo, just how to use it. Despite it being a parameter, I was very confused by it not actually being called in the example. It would be nice if somebody who knows what they're doing, could make the docs more clear in that regard.

**Comment by yaquawa** [comment]
Update the doc to show the usage of `inject` would help many people like me!!

**Comment by marco-gattelli** [comment]
@clarkdo the `inject` function let you use the plugin inside the `actions/mutations` what about the `getters`. I have a use case where I'd like to use mu plugin inside a `getter` but I can't since `this` is `undefined`, which kind of solution would you use?

**Comment by clarkdo** [comment]
@marco-gattelli 
Can you provide a repo or show me your codes ?

**Comment by marco-gattelli** [comment]
Of course I can @clarkdo 
The following is my plugin:
```javascript
import ColorService from '../services/ColorService';

export default (context, inject) => {
  const colorService = new ColorService();
  inject('colorService', colorService);
};
```
And this is my getter inside a `module`:
```javascript
import { productGridGetters } from './store-types';
import cloneDeep from 'lodash.clonedeep';

export default {
[productGridGetters.GET_FILTERED_PRODUCTS]: function (state, getters, rootState) {
let arrayToFilter = cloneDeep(rootState.products.currentList);
if (filter.colors.length > 0) {
      console.log(this); // *this* is undefined
      // console.log(this.$colorService); // cannot find $colorService of undefined 
      const colorsSelected = filter.colors.map(color => `${color.code}`);
      arrayToFilter = arrayToFilter.filter(product => {
          const colors = get(product, 'colors', []);
          let found = false;
          for (let indexColor = 0; indexColor < colors.length; indexColor++) {
            const color = colors[indexColor];
            // Cannot call the method of the plugin since *this* is undefined.
            if (colorsSelected.indexOf(`${this.$colorService.getCodeFromId(product.productType, color.id, response.data)}`) > -1) {
              found = true;
              break;
            }
          }
          return found;
        });
    }
}
```
Really apreciate your help 😄

**Comment by clarkdo** [comment]
Try:

```js
import Vue from 'vue'

// ...

Vue.prototype.$colorService
```

**Comment by marco-gattelli** [comment]
Yep, we tried this but it does not work.
