### ISSUE TITLE
Layout seems not working

### ISSUE THREAD

**Issue by nugrahawahyu** [nuxt/nuxt.js#2235]
I got a blank page when I navigate to a page with a different layout, but it got rendered if I reload that page manually.

**Comment by clarkdo** [comment]
Please check https://github.com/nuxt/nuxt.js/tree/dev/examples/custom-layouts

If it cannot resolve you problem, pls offer a repo can reproduce your issue. 😃

**Comment by nugrahawahyu** [comment]
material-lite-design package is the culprit, it removes the layout root element on page load. Fix it by wrapping it with one more div. Thank you for answering.
