### ISSUE TITLE
ERROR in common.83cd80e5c7fd8703ba74.js from UglifyJs

### ISSUE THREAD

**Issue by 18717700273** [nuxt/nuxt.js#2236]
error 
![image](https://user-images.githubusercontent.com/25985156/33228123-a491f318-d1ee-11e7-8937-6bbcc6279a6f.png)
nuxt.config.js
![image](https://user-images.githubusercontent.com/25985156/33228126-bb923802-d1ee-11e7-98aa-5e91ae902bf4.png)
![image](https://user-images.githubusercontent.com/25985156/33228128-c0369416-d1ee-11e7-9429-9aada66959c7.png)
package.json
![image](https://user-images.githubusercontent.com/25985156/33228129-cab2124e-d1ee-11e7-8740-a1fd8ea03b6d.png)
why?

**Comment by clarkdo** [comment]
You should include the you `dependency` which use not supported es syntax yet in 'babel', pls have a look at: https://github.com/nuxt/nuxt.js/issues/1668#issuecomment-330510870
