### ISSUE TITLE
Using markdownit with pug

### ISSUE THREAD

**Issue by Kinzi** [nuxt/nuxt.js#2238]
I'm having trouble getting markdown rendered with pug and `@nuxtjs/markdownit`.  Basically I'm trying to follow the [examples](https://github.com/nuxt/nuxt.js/tree/dev/examples/markdownit) but can't get it to work.

lets say I have a markdown string coming from my cms `content = ## Title h2\n### title h3\n\nLong text Long text Long text Long text Long text Long text Long text Long text Long text \n\n* gimme a list item\n* and one more yeehaw`

Following the example I tried:

```
<template lang="pug">
div
   div(language="md") ## Title h2\n### title h3\n\nLong text Long text Long text Long text Long text Long text Long text Long text Long text \n\n* gimme a list item\n* and one more yeehaw
   div(language="md") {{ model }}
</template>

<script>
export default {
  data () {
    return {
      model: '## Title h2\n### title h3\n\nLong text Long text Long text Long text Long text Long text Long text Long text Long text \n\n* gimme a list item\n* and one more yeehaw'
    }
  }
}
</script>
```

Which renders me the following markup:

```
<div>
  <div language="md">## Title h2\n### title h3\n\nLong text Long text Long text Long text Long text Long text Long text Long text Long text \n\n* gimme a list item\n* and one more yeehaw
  </div>
  <div language="md">## Title h2
  ### title h3

Long text Long text Long text Long text Long text Long text Long text Long text Long text 

* gimme a list item
* and one more yeehaw
</div>
</div>
```

What am I doing wrong?

**Comment by clarkdo** [comment]
Please check the example: https://github.com/nuxt/nuxt.js/tree/dev/examples/markdownit 😸

**Comment by Kinzi** [comment]
@clarkdo I did. But in the example there is no actual markdown string in pug. That's why I set up above based on the example.

**Comment by clarkdo** [comment]
I open a pr for markdown example, pls check: https://github.com/nuxt/nuxt.js/pull/2250

**Comment by lunelson** [comment]
The normal way to use markdown in pug is as a filter, and the conversion takes place in your build step. That is the syntax which is shown in the [example](https://github.com/nuxt/nuxt.js/blob/dev/examples/markdownit/pages/pug.vue). 

You would not be able to render markdown data as html however, unless you bound the markdown functions in to your front-end code, which would require a different configuration.

```vue
<template lang="pug">
div
  :markdown 
    ## an h2 title
    a paragraph.
</template>
```
