### ISSUE TITLE
Route with param returns 404 on refresh

### ISSUE THREAD

**Issue by sebastianks** [nuxt/nuxt.js#2240]
I'm using the Express + Nuxt.js starter template. My routes without params works just as they should, but my routes with params doesn't work as soon as I refresh the page - it'll return a 404 response. 

I have tried with regular `Promise` too.

My code is:

```javascript
async asyncData({ params }) {
	let { data } = await axios.get(`/api/product/${params.slug}`)
	return { data: data.entries[0] }
},
```

**Comment by clarkdo** [comment]
Have a look at: https://github.com/nuxt/nuxt.js/issues/1492 😸

**Comment by sebastianks** [comment]
@clarkdo Thanks for answering. I don’t see how that issue helps me? I am getting data by a slug and a result if I go to the page by a nuxt-link, but as soon as I type in the url or refresh the page, I get a 404 error. ✌🏻

It’s like the server don’t know the request or something?

**Comment by clarkdo** [comment]
Could you offer a repo can reproduce the issue ?

**Comment by sebastianks** [comment]
@clarkdo That's hard because my code requires some tokens to work, and I rather not give out those. Have you seen my updated post just above yours?👻

**Comment by clarkdo** [comment]
How do you integrate axios with Nuxt?

**Comment by sebastianks** [comment]
I did this in `/plugins/axios.js`

```javascript
import axios from 'axios'

let options = {}

// The server-side needs a full url to work
if (process.server) {
	options.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`
}

export default axios.create(options)
```

**Comment by clarkdo** [comment]
Then you should use `~/plugins/axios` in your Vue.

```js
import axios from '~/plugins/axios'
```

**Comment by sebastianks** [comment]
Oh, I didn't see that. Actually I did import from plugins/axios in my other Vue files.

It works!

Thank you so much @clarkdo. I've spent 3 hours looking at code I thought was OK, but you saved my day! 😺

**Comment by clarkdo** [comment]
Thank you for your support of Nuxt.js :smile:

**Comment by pungiish** [comment]
Hey, I'm having the exact same problem, but without using axios, I'm using a promise which resolves after a timeout and returns the data. I added @clarkdo 's setting, but it doesn't work for me.
The app works in dev, but doesn't when i deploy it to xampp or gh-pages
on gh.pages, event the /recipes page doesn't work on refresh.
https://pungiish.github.io/VueRecipesSsr/
https://github.com/pungiish/VueRecipesSsr

**Comment by pungiish** [comment]
@aldarund Thanks for the fast reply, it works if I navigate through the app using nuxt-router links though. It also doesn't work on xampp refresh,
But yeah I generated files using npm run generate.

**Comment by aldarund** [comment]
@pungiish go to discord https://discord.gg/u5YVXTc

**Comment by pungiish** [comment]
Fixed, I didn't generate dynamic routes https://nuxtjs.org/api/configuration-generate/
