### ISSUE TITLE
Plugin/Dependency causing a middleware issue?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [nuxt/nuxt.js#2241]
Hi,

I’m trying to use [Vue2Leaflet](https://github.com/KoRiGaN/Vue2Leaflet), but as soon as I call the component in my Template, these errors are triggered:

```
.nuxt/server.js:126:15 — Object._callee$
internal/process/next_tick.js:188:7 — process._tickCallback
```

**.nuxt/server.js**
```javascript
if (layout.middleware) midd = midd.concat(layout.middleware)
```

**.internal/process/next_tick.js**
```javascript
Missing stack frames
```

Here's my Template file:

```html
<template>
  <v-map ref="map" :zoom="zoom" :center="center"></v-map>
</template>

<script>
import Vue2Leaflet from 'vue2-leaflet'

export default {
  data () {
    return {
      center: [0, 0],
      zoom: 5
    }
  },

  components: {
    'v-map': Vue2Leaflet.Map
  }
}
</script>
```

That simple, but it trigger the error. If y just remove the `<v-map ref="map" :zoom="zoom" :center="center"></v-map>`, the error vanish and the page load.

-----

I’m unable to track down what causes this issue.

The point is, it's not entirely related to the plugin, which works great in vuejs without nuxt, but it's not entirely related to nuxt also…

So all I can do is report the issue here, and tag the plugin owner (@KoRiGaN, if you could please come and see this…)

Thanks to all!

**Comment by clarkdo** [comment]
It seemed that ` Vue2Leaflet` doesn't support ssr very well, please try
```vue
<template>
  <no-ssr>
    <v-map :zoom=13 :center="[47.413220, -1.219482]">
      <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
      <v-marker :lat-lng="[47.413220, -1.219482]"></v-marker>
    </v-map>
  </no-ssr>
</template>

<script>
let Vue2Leaflet = {}
if (process.browser) {
  Vue2Leaflet = require('vue2-leaflet')
}
export default {
  components: {
    'v-map': Vue2Leaflet.Map,
    'v-tilelayer': Vue2Leaflet.TileLayer,
    'v-marker': Vue2Leaflet.Marker
  }
}
</script>
```

**Comment by EmmanuelBeziat** [comment]
Hi @clarkdo, thanks for the help. It kinda works (with a weird issue, but I think I can work around by myself for these).

Thanks for pointing me the icon issue too. Unfortunately, I don't get where to put this bit of code? I tried right after the plugin require (to be sure that the plugin is at least loaded when I want to change the icon), but I ended up with a `Mismatching childNodes vs VNodes` error.

Thanks again!

**Comment by gangsthub** [comment]
@EmmanuelBeziat can this be closed? :)

**Comment by EmmanuelBeziat** [comment]
@gangsthub I just hope @clarkdo (or anybody) could just help me with this point:

> Thanks for pointing me the icon issue too. Unfortunately, I don't get **where to put this bit of code**? I tried right after the plugin require (to be sure that the plugin is at least loaded when I want to change the icon), but I ended up with a Mismatching childNodes vs VNodes error.

(talking about this https://github.com/KoRiGaN/Vue2Leaflet/issues/103)

Then it'll be okay to close it for good. :)

**Comment by clarkdo** [comment]
https://github.com/KoRiGaN/Vue2Leaflet/issues/28#issuecomment-320227460

**Comment by clarkdo** [comment]
The whole example:

```vue
<template>
  <no-ssr>
    <v-map class="mini-map" :zoom=13 :center="[47.413220, -1.219482]">
      <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
      <v-marker :lat-lng="[47.413220, -1.219482]"></v-marker>
    </v-map>
  </no-ssr>
</template>

<script>
let Vue2Leaflet = {}
if (process.browser) {
  Vue2Leaflet = require('vue2-leaflet')
  const L = require('leaflet')
  delete L.Icon.Default.prototype._getIconUrl
  L.Icon.Default.imagePath = ''
  L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('~/assets/markers/marker-icon-2x.png'),
    iconUrl: require('~/assets/markers/marker-icon.png'),
    shadowUrl: require('~/assets/markers/marker-shadow.png')
  })
}
export default {
  components: {
    'v-map': Vue2Leaflet.Map,
    'v-tilelayer': Vue2Leaflet.TileLayer,
    'v-marker': Vue2Leaflet.Marker
  }
}
</script>

<style src="leaflet/dist/leaflet.css"></style>
<style>
.mini-map {
  width:100%;
  height:500px !important;
}
</style>
```

**Comment by EmmanuelBeziat** [comment]
Okay, I see what I got wrong: I assumed that `L` was a ref to the Vue2Leaflet, but it had to be directly referring to Leaflet…

Thanks for that!

**Comment by yaki4** [comment]
@clarkdo: Your solution work well in development but when i build and deploy it doesn't show anything. Should i add something in the nuxt.config file ?

**Comment by core01** [comment]
I does not know why this solution did not work for me, in Chrome Dev tools I see: Unknown custom element: <v-map> - did you register the component correctly? 

Here is my code:

```vue
<template>
  <no-ssr>
    <v-map
      :zoom="10"
      :center="[49.9553, 82.6134]">
      <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"/>
    </v-map>
  </no-ssr>
</template>
<script>
let Vue2Leaflet = {}
if (process.browser) {
  Vue2Leaflet = require('vue2-leaflet')
}
export default {
  components: {
    'v-map': Vue2Leaflet.Map,
    'v-tilelayer': Vue2Leaflet.TileLayer
  }
}
</script>

```
Has something changed since the last time?

Nuxt.js: 1.4.0
Vue2Leaflet: 1.0.2

**Comment by clarkdo** [comment]
@core01 
Please follow Vue2Leaflet [release notes](https://github.com/KoRiGaN/Vue2Leaflet/releases):

> from v1.x.x all components are prefixed with L.

Therefore `Vue2Leaflet.Map` and `Vue2Leaflet.TileLayer ` should be `Vue2Leaflet.LMap` and `Vue2Leaflet.LTileLayer`
