### ISSUE TITLE
Problem with jquery plugins and server side rendering

### ISSUE THREAD

**Issue by ahadyekta** [nuxt/nuxt.js#2246]
Hi, I have got stuck in a propensity of using : https://uiv.wxsm.space/typeahead
 Whenever I add it in plugins with ssr: false it does not produce the dropdown section on page refresh . because the produced html through server rendering ,  does not have it . 
When I set the ssr : true , it shows that window is undefined. 
How should i use this plugin in nuxt

**Comment by gangsthub** [comment]
@ahadyekta, you mean _bootstrap_ plugin, right? (jquery?)

**Comment by ahadyekta** [comment]
This package is bootstrap components built for vue.
When I use it , the server and client rendering don`t match because the jquery makes some html that only client has it. The server rendering does not run jquery. So the SSR result is not what is expect.

**Comment by pi0** [comment]
@ahadyekta Try putting typehead component in `<no-ssr></no-ssr>` tags.

**Comment by wxsms** [comment]
`window is undefined` is a bug of uiv lib, and already been fixed in the latest version. Pls upgrade your uiv version and try it again with SSR enabled.

**Comment by husayt** [comment]
Do you still have this isssue in 1.4.0?
