### ISSUE TITLE
.nuxt-link-active class doesn't remove from <nuxt-link>

### ISSUE THREAD

**Issue by nucamoz** [nuxt/nuxt.js#225]
One of my menu links is `<li><nuxt-link to="/">Main Page</nuxt-link></li>`

The problem is when I click other links this one stays active with the `nuxt-link-active` class. 

Why is this happening?

**Comment by nucamoz** [comment]
Is this because in links to "/"?
Is there any fix?

**Comment by alexchopin** [comment]
Please stop creating issue if you have not red the documentation or closed issues before.
This question has been already answered [here](https://github.com/nuxt/nuxt.js/issues/126).
