### ISSUE TITLE
Did you already released #2081 ?

### ISSUE THREAD

**Issue by biigpongsatorn** [nuxt/nuxt.js#2253]
Did you already released #2081 ?

**Comment by agoretsky** [comment]
and when will be the next release?)

**Comment by pi0** [comment]
https://twitter.com/nuxt_js/status/935100400415502342

We now have an unstable release channel which a new version is published automatically with every successful commit. If you want to try the lastest version of Nuxt.js, you can use `yarn add nuxt@next --exact` or `npm i --save-exact nuxt@next`. Be aware that it's the unstable channel until 1.0 is hit. Also for a yarn lock file workaround make sure that version is stored in `package.json` without caret (`^`) or is set to `next` tag.

PS: Every single contribution is REALLY appreciated to reach 1.0.0 as fast as possible. (See [roadmap](https://trello.com/b/lgy93IOl/nuxtjs-10))

**Comment by pi0** [comment]
Closing as a dup of #2142. Please track things from there :)

**Comment by pi0** [comment]
Closing as a dup of #2142. Please track things from there :)
