### ISSUE TITLE
Transition broken with Dynamic routes

### ISSUE THREAD

**Issue by hackuun** [nuxt/nuxt.js#2257]
I have this folder structure

```
pages
--| _section
-----| _slug.vue
-----| index.vue
--| index.vue
```
The problem is Page transitions are broken on `_section` route, when I navigate from one Dynamic route to another. I tried different modes, no help

```js
transition: {
    name: 'page',
    mode: 'out-in'
  }
```
Also tried to add a `key`, like 

```html
<template>
  <section :key="$route.params.section">
    <ul>
      <li v-for="article in $store.state.articles">
        <nuxt-link :to="{ name: 'section-slug', params: { section: article.section, slug: article.slug } }">{{ article.title }}</nuxt-link>
      </li>
    </ul>
  </section>
</template>
```
Still doesn't work. How to fix it?

**Comment by chasebank** [comment]
Can you make a [glitch.com](glitch.com) demo, duplicating the problem?

You shouldn't need a key for the top level sections, but for the articles it may be easier if you use nested routes, inside the section, and then the key would be added to the `nuxt-child` element.

`<nuxt-child :key="$route.params.slug"/>

Here's a working example of that: https://glitch.com/edit/#!/nuxt-dynamic-route-transitions

That has a fade transition on the dynamic categories, and a slide transition on the dynamic articles within each category page.

**Comment by husayt** [comment]
Seems this can be closed now
