### ISSUE TITLE
ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '...'

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#2259]
With the latest dev branch I cannot start nuxt. I guess it's related with my specific setup.. we have nuxt installed in a subfolder called "pwa". Therefore we instereted "srcDir" optoin in nuxt.config.js:
`srcDir: 'pwa/'`

If i try to run or build it with the latest dev branch though, it results in errors like:
`ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '...'`

To solve it, I added to the nutx.config.js function "extend(config, { isDev, isClient, isServer }) {"
```
 // fix node_modules directory
 config.resolve.modules = config.resolveLoader.modules = [path.resolve(__dirname, "node_modules")];

```
then it works.
Just in case someone needs this.. actually I think it is a bug, as this was not needed before (and is not really documented either).

Thanks
Simon

**Comment by pi0** [comment]
Hi. It should be resolved in #2258. Would you please test using `nuxt@1.0.0-gh-b31b0f2` which is current next release?

**Comment by simllll** [comment]
I just figured out that #2222 has the solution that also works for me.
just added modulesDir: ['node_modules'] to my nuxt.config.js and things work again as well.

I just upgraed nuxt, but I'm at 1.0.0-gh-5bacd36.. I will check again.

Thanks

**Comment by simllll** [comment]
Nope, even though your PR really sounds like the issue I have.
Upgraded to nuxt@1.0.0-gh-b31b0f2 .. 

but not working, the error is different though from the earlier one, the error is the same I had before when I only set config.resolveLoader.modules but not config.resolve.modules.

Two error "types":
1.)  ```
{ Error: Cannot find module '/home/simon/Dev/Web/hokify-server/pwa/nuxtjs/pwa'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /home/simon/Dev/Web/hokify-server/node_modules/nuxt/lib/core/module.js:107:16
    at Generator.next (<anonymous>)
    at step (/home/simon/Dev/Web/hokify-server/node_modules/nuxt/dist/nuxt.js:60:30)
    at /home/simon/Dev/Web/hokify-server/node_modules/nuxt/dist/nuxt.js:78:14
    at Promise (<anonymous>)
    at /home/simon/Dev/Web/hokify-server/node_modules/nuxt/dist/nuxt.js:57:12
    at ModuleContainer.addModule (/home/simon/Dev/Web/hokify-server/node_modules/nuxt/dist/nuxt.js:841:7)
    at promise.then (/home/simon/Dev/Web/hokify-server/node_modules/nuxt/lib/common/utils.js:61:61)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3 code: 'MODULE_NOT_FOUND' }

```
It tries to load it from the wrong directory.. the correct one should be hokify-server/pwa/ (that's it)
2.) Of this type I have a few hundret:
ERROR in ./pwa/middleware/i18n.js
Module not found: Error: Can't resolve 'accept-language' in '/home/simon/Dev/Web/hokify-server/pwa/middleware'
The second error appears after the build is completed.

Somehow it doesn't help to add modulesDir: ['node_modules'], back in my nuxt.config.js.. Errors stay :(

(I removed all node_modules and installed it again,.. wans't the issue). Any idea what's happening now?

regards
Simon

**Comment by simllll** [comment]
Okay, not sure what's happening, but I removed all module directorys again and installed everything one more time from scratch. And YES; it works now :)

Thanks for your prompt response.
