### ISSUE TITLE
Where should I put the inline script?

### ISSUE THREAD

**Issue by rubyless** [nuxt/nuxt.js#226]
for example: 

``` javascript
<body>
    <script>
        /* disable-eslint */
        function rem() {
            var w = Math.min(document.documentElement.getBoundingClientRect().width, 500);
            document.getElementsByTagName('html')[0].style.fontSize = w * 100 / 750 + 'px';
        }
        rem();
        window.onresize = function(){rem();};
    </script>
    <div></div>
</body>
```

I checked the document of vue-meta and use the code below

``` javascript
head: {
    title: 'starter',
    script: [
      { innerHTML: 'document.querySelector("html")' }
    ]
}
```
But the quotes are escaped in the browser

```html
<script n-head="true">document.querySelector(&quot;html&quot;)</script>
```
I also try to put the code into the layout component, the quotes are escaped too.

Update: 

I carefully checked the document of vue-meta, and solved the problem with

```
head: {
    title: 'starter',
    script: [
      { innerHTML: 'document.querySelector("html")' }
    ],
    __dangerouslyDisableSanitizers: ['script']
}

```

Thank you a lot ! I really like this project! 😍

**Comment by devyfriend** [comment]
hi @alexchopin .. i get this error on chrome console when i add inline script, "nuxt dev" is fine, can you peek on it :)

thanks
![screen shot 2017-04-18 at 22 22 15](https://cloud.githubusercontent.com/assets/1331149/25138814/b537ac60-2485-11e7-8008-f2240ceab9e1.png)

**Comment by devyfriend** [comment]
turns out this is the vue-meta issue :( 
https://github.com/declandewet/vue-meta/issues/67
