### ISSUE TITLE
Global CSS Code Splitting into multiple Chunks

### ISSUE THREAD

**Issue by pxwee5** [nuxt/nuxt.js#2262]
I am using PurgeCSS to remove unused TailwindCSS classes. But it removed most of the NormalizeCSS rules. 

I'm thinking of splitting Normalize in a separate `normalize.css` file and then just get PurgeCSS to purge the `main.css`. 

I checked the documents and did not find a way to do this. Anyone can point me in the right direction?

## Update
Just realized that `html` was included (maybe due to default styling in the css) but `body` wasn't included. Most probably because none of the .vue files have the html and body text.

**Comment by pxwee5** [comment]
Closing issue. Fixed with PurgeCSS's whitelist configuration.

**Comment by manniL** [comment]
@pxwee5 could you please provide your config?I'd like to integrate PurgeCSS into Nuxt.js as well! 🤔

**Comment by pxwee5** [comment]
Nuxt Config
```
class TailwindExtractor {
  static extract (content) {
    return content.match(/[A-z0-9-:/]+/g) || []
  }
}

module.exports = {
  build: {
    extend (config, ctx) {
      config.plugins.push(
        new PurgecssPlugin({
          whitelist: ['html', 'body'],
          paths: glob.sync([
            path.join(__dirname, 'components/**/*.vue'),
            path.join(__dirname, 'layouts/**/*.vue'),
            path.join(__dirname, 'pages/**/*.vue'),
            path.join(__dirname, 'plugins/**/*.vue')
          ]),
          extractors: [{
            extractor: TailwindExtractor,
            extensions: ['html', 'js', 'vue']
          }]
        })
      )
    }
  } 
  modules: [
    '~modules/import-tailwind-config'
  ] 
```

import-tailwind-config.js
```
/**
 * Tailwind configuration needs to be imported during build
 * So that it can be added into the environment
 * Usage: process.env.tailwind
 */
module.exports = function () {
  const tailwindConfig = require('../tailwind.js')
  this.options.env.tailwind = tailwindConfig
}
```

Not sure if I'm doing it right, but it works in development.

**Comment by husayt** [comment]
also see https://github.com/FullHuman/purgecss/tree/master/examples/with-nuxt
