### ISSUE TITLE
Component inside nuxt-link is rendered twice

### ISSUE THREAD

**Issue by WingmanImd** [nuxt/nuxt.js#2266]
Nuxt version : "nuxt": "^1.0.0-rc11"
Env: dev
I recently encountered a strange bug, more exactly if you have a component inside a nuxt-link the component will display twice. I have no errors and I tried everything

Ex: <nuxt-link to="/"><Logo></Logo></nuxt-link>
The result will be a link with the Logo component rendered twice.

The content of Logo.vue can be anything, it doesnt seem to mather.

EDIT: on refresh the Logo component is rendered once then immediately renders again.
EDIT2: if I stop the server and run "npm run dev" again the component is rendered once but as soon as I refresh the page it renders twice.

**Comment by clarkdo** [comment]
Could you have a on `nuxt@next` ?

**Comment by WingmanImd** [comment]
@clarkdo Sorry but I'm kind of new to nuxt. What do you mean exactly?

**Comment by clarkdo** [comment]
Change your dependecy from ` "nuxt": "^1.0.0-rc11"` to `"nuxt": "next" ` to have a try 😸 , but be aware that it's the unstable channel until 1.0 is hit.

**Comment by WingmanImd** [comment]
Update: I searched through nuxt releases and encountered this "npm install --save nuxt@next" on Release "v1.0.0-rc3". After running it my nuxt version changed to "^1.0.0-gh-887ebd5" and the bug dissapeared.
Thanks for the help!
