### ISSUE TITLE
store.registerModule in plugin

### ISSUE THREAD

**Issue by chymz** [nuxt/nuxt.js#2267]
Hi !

I've a little problem here : I want to register a new store module in a plugin.
In my plugin I do this : 

```js
import myStore from './store';

export default {
  install(Vue, { store }) {
    store.registerModule('custom', myStore);
  }
};
```

In my nuxt plugin I've this :
```js
import CustomPlugin from './custom/plugin';

export default async ({ store }) => {
  Vue.use(CustomPlugin, { store });
};
```

Then I call an action in my page :
```js
export default {
  async fetch ({ store }) {
    await store.dispatch('custom/FETCH');
  }
}
```

Everything is OK on client-side but on server-side, I've this error:
```
[vuex] unknown action type: custom/FETCH
```

I'm using nuxt-rc11 and my store files are located outside the root `/store` directory. It's possible to do that ?

Thanks !

**Comment by clarkdo** [comment]
Did you declare `namespaced: true` in your `myStore` ?

**Comment by chymz** [comment]
Yep my store is already namespaced !

**Comment by clarkdo** [comment]
Vue plugin `install` will be executed only once, so `custom` cannot be registered except first loading, you can diretlly move `registerModule` to nuxt plugin 😸

**Comment by chymz** [comment]
It's better, but now my store is empty on client-side.

`window.__NUXT__` is correclty filled but when Vue/Vuex is initialized, the store is blank :(

Here is a sample repo  : https://github.com/chymz/nuxt-store-issue

Important files : 
- Nuxt plugin : https://github.com/chymz/nuxt-store-issue/blob/master/plugins/plugin.js
- Store : https://github.com/chymz/nuxt-store-issue/blob/master/plugins/store.js
- Index : https://github.com/chymz/nuxt-store-issue/blob/master/pages/index.vue#L3

**Comment by clarkdo** [comment]
Try

```js
export const mutations = {
  SET_ITEMS(state, value) {
    Object.assign(state.items, value)
  },
};
```

**Comment by clarkdo** [comment]
Try:

```js
import * as customStore from './store';

export default async ({ isServer, store }) => {
  if (isServer) {
    store.registerModule('custom', customStore);
  }
};
```

**Comment by chymz** [comment]
Yeah thanks a lot @clarkdo !
