### ISSUE TITLE
The data function has no context parameter in layout component

### ISSUE THREAD

**Issue by rubyless** [nuxt/nuxt.js#227]
``` vue
<template>
  <div id="layout">
    <nuxt/>
    <my-footer/>
  </div>
</template>

<script>
import MyFooter from '~components/Footer.vue'

export default {
  data (context) {
    console.log(context) // undefined
    return {
      isClient: false
    }
  },
  components: {
    MyFooter
  }
}
</script>
```

**Comment by alexchopin** [comment]
The data function is supercharges with the context only for pages components.
[Documentation](https://nuxtjs.org/api/)

**Comment by rubyless** [comment]
How can I get the context parameter in layout component, Sometimes we really need to get it. @alexchopin

**Comment by Atinux** [comment]
What kind of data from the context do you need @rubyless in the layout?

**Comment by flyingzl** [comment]
@Atinux  I wanna to render a banner in every page when I detect the device is iOS.
I wrote a middleware to detect the userAgent and put context.isIOS in the context, so I need to read context in layout page

**Comment by juliomatcom** [comment]
Hi @alexchopin this should not be closed, is not answered yet

**Comment by qm3ster** [comment]
Can't you use a plugin and put it on the app object?
