### ISSUE TITLE
How does the 'generate' work with middleware ?

### ISSUE THREAD

**Issue by nannan9507** [nuxt/nuxt.js#2270]
I found a problem what is, I want to use a middleware which called 'userAgent'

in nuxt.config.js,like this:
router: {
  middleware: ['userAgent'],
}, 
as the document said.

but, when I run 'npm run generate' code, it warning 

{ 
  Error: ENOENT: no such file or directory, lstat '/Users/summerd/Documents/
workspace/cy/ssr-template/dist/index.html'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/summerd/Documents/workspace/cy/ssr-template/dist/index.html'
 }

and the dist fold I can't find index.html and 200.html. Does any body know something about this, and know how can I build successfully with router: { middleware: 'xxxx' } ?

**Comment by clarkdo** [comment]
It may because of there is unreachable ajax calling in your codes.

Can you try sue `"nuxt": "next"` in your `dependencies` of `package.json`, it will print the error cause, if not please offer a repo can reproduce your issue. 😸

**Comment by nannan9507** [comment]
thanks for your answer，I found the resolution of this question，
because when generate run, It has not a server，so req | res not exist, it's error to build a index.html, so...you know.
boom shakalaka.

anyway, thanks for your answer
