### ISSUE TITLE
router.base not maintained in build (without config file)

### ISSUE THREAD

**Issue by sparecycles** [nuxt/nuxt.js#2271]
There are cases where the`nuxt.config.js` file is required for a deployment, not just the .nuxt folder.

We had, in addition to the `node_modules` production dependencies, only the .nuxt folder copied into our runtime docker container.

With the addition of
```js
  router: { base: '/app/' }
```
we found that we also needed the `nuxt.config.js` or the files are served from `/` (but scripts would fail to load because the tags in the html try to load them from `/app/...`

Suggest keeping additional data such as `router.base` in the `.nuxt` output folder.  (and/or update the documentation with guidance about keeping `nuxt.config.js` in production deployment packages).

**Comment by clarkdo** [comment]
Hope I understand correctly, I think you want to load `nuxt.config.js` like `<script src="/nuxt.config.js">`.

You can use move `nuxt.config.js` to `static` folder, specify config file when run dev, building and production, such as: `nuxt build -c static/nuxt.config.js` and add static folder to docker image together with `.nuxt/dist`

**Comment by sparecycles** [comment]
Oh, I don't want to load `nuxt.config.js` in the browser at all!   I was just reporting that there are some settings which break `nuxt start` if only the `.nuxt` folder is copied.

My solution is of course to copy both the `nuxt.config.js` and `.nuxt` folder into my deployment docker image, and `nuxt start` detects it just fine.

**Comment by clarkdo** [comment]
oh, I got your point. I will discuss with the team about how to solve this issue. 😸 

I really appreciate your support of Nuxt.js.
