### ISSUE TITLE
nuxt generate是否适用vue1.0项目

### ISSUE THREAD

**Issue by huanghaizhu** [nuxt/nuxt.js#2272]
现有vue1.0项目情况
有现成的路由配置文件
vue文件中都是vue1.0那些钩子和方法
对于这种情况，nuxt generate适用吗？

**Comment by clarkdo** [comment]
Nuxt目前只支持Vue2.0, 由于2.0较之1.0有很大的变化, 因此没有办法做到向后兼容.

推荐您参考: https://cn.vuejs.org/v2/guide/migration.html.
