### ISSUE TITLE
Integrating TailwindCSS into Nuxt SFC 

### ISSUE THREAD

**Issue by pxwee5** [nuxt/nuxt.js#2273]
I've got tailwind working with PurgeCSS with Nuxt. But I am unable to get `@apply` to work in Vue Single File Components. 

The only way around this is to put everything in my `main.scss`. And the consequence of this is I lose the ability for code splitting in the SFC.

Anyone got an idea how to fix this?

Adding `@tailwind utilities;` does it but it adds the whole utility into server-bundle.json on `yarn build` hence bloating the built files.

**Comment by husayt** [comment]
see https://github.com/FullHuman/purgecss/tree/master/examples/with-nuxt and #2942
