### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by nugrahawahyu** [nuxt/nuxt.js#2274]
Im using a custom api plugin that has its own axios. I got "ReferenceError: XMLHttpRequest is not defined" error when using that plugin to fetch data for my component's asyncData.

**Comment by clarkdo** [comment]
If you use `ssr` mode, it should because of  `asyncData` will be called at server side and XHR api is not supported in node.

So, I suggest you to use a node.js compatible ajax plugin, such as `axios` or use `spa` mode.

**Comment by nugrahawahyu** [comment]
The plugin just an axios wrapper to make request to my api endpoint. But still, I got that error.

**Comment by clarkdo** [comment]
Does the plugin has any specific process ?

You can try https://github.com/nuxt-community/axios-module
