### ISSUE TITLE
Can I get the window object before default.vue mounted.

### ISSUE THREAD

**Issue by Yang-Travis** [nuxt/nuxt.js#2275]
I want to window.location.href='www.xxxx.com' before project first page show, is any way can do this ?

My current way is put the window.location.href in default.vue file's mounted function, but it seems need load those app.js default.js index.js manifest.js before mounted function. 

So, is some way can run my window.location.href code immediately? Thank you so much !

**Comment by clarkdo** [comment]
You can use `plugin` with `ssr:false`.

https://nuxtjs.org/guide/plugins#client-side-only
