### ISSUE TITLE
异步调用的数据，在手动刷新页面时network不会出现调用的接口，但是走路由时出现了，请问怎么去隐藏

### ISSUE THREAD

**Issue by luke-Yang** [nuxt/nuxt.js#2277]

**Comment by clarkdo** [comment]
> 手动刷新页面时network不会出现调用的接口
这是因为服务端渲染会在服务端发起请求.
> 走路由时出现了，请问怎么去隐藏 
路由情况下是浏览器端发起请求, 请求信息是没办法隐藏, 但是如果你想屏蔽后端信息, 可以通过Nginx或者服务端(express, koad)转发进行处理
