### ISSUE TITLE
Production build is not happend with express

### ISSUE THREAD

**Issue by shamon76** [nuxt/nuxt.js#2278]
Here is my express.js code for render nuxt in server side

process.env.NODE_ENV = 'production';
const isProd = process.env.NODE_ENV === 'production';
let config = require('../nuxt.config.js')
const nuxt = new Nuxt(config);
// No build in production
if (!isProd) {
  const builder = new Builder(nuxt)
  builder.build()
}
app.use(nuxt.render);

But when i run in production  mode build is not happening

**Comment by sebastianks** [comment]
This is what you want. No build in production mode - at least that's what your code is doing:

```js
...
// No build in production
if (!isProd) {
   const builder = new Builder(nuxt)
   builder.build()
}
...
```

**Comment by shamon76** [comment]
But without build how can i access my application

**Comment by sebastianks** [comment]
For development mode you should use `npm run dev` (or `yarn dev`) and for production you should build the application and then serve it. Take a look here: https://github.com/nuxt-community/express-template. This is a starter template with Express, in the `package.json` file you have:

```js
"scripts": {
    "dev": "backpack dev",
    "build": "nuxt build && backpack build",
    "start": "cross-env NODE_ENV=production node build/main.js",
    "precommit": "npm run lint",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore ."
},
```

`dev` is for development. `build` is to build your app. `start` is to start up the app in production mode.

**Comment by shamon76** [comment]
In my application there is a `server` folder and it contains the express js application.
and in my `package.json` its in the root of the project folder

```
"scripts": {
    "dev": "node server/bin/www",
    "build": "nuxt build",
    "start": "nuxt start"
  },
```

**Comment by sebastianks** [comment]
You should have your scripts like this: 

```js
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start"
},
```

To have Nuxt run in dev mode. This is from the basic starter template here: https://github.com/nuxt-community/starter-template. If you are new to Nuxt I highly recommend you to start your project with this.

**Comment by shamon76** [comment]
Actually my express server running in `server` folder thats why i changed my `dev` to  this  "node server/bin/www". Now my express application render nuxt js app.
its works fine now but the problem is how can get production run with express and nuxt.js?

**Comment by sebastianks** [comment]
Take a look at: https://github.com/nuxt-community/express-template#commands. This explains how you build your application and run it in production mode. Also, the main feature is:

`"start": "cross-env NODE_ENV=production node build/main.js",` in your `package.json` scripts. This will start your app in production mode - with nodejs server.

Try to run the `npm run build` command, and see if it's generating a `build` directory in the root of your application. If it does, then you should use the `start` script from my previous comment, and you should be good to go. Tip: If you haven't already then you should `npm install cross-env`.

**Comment by shamon76** [comment]
Thats simple express intgaration i need express with express generator

**Comment by sebastianks** [comment]
@shamon76 Okay, you didn't mention that :) I have no experience with express generator, sorry - can't help you on that.

**Comment by shamon76** [comment]
Sorry about that i need to intgrate express app that generated with express generator

**Comment by clarkdo** [comment]
If you want to use custom server like `express`, `koa`and `hapi`, you should use `node server /app.js` instead of`nuxt start` as @sebastianks said.

And manually run `nuxt build` before starting the serve, also exclude `builder.build` in `productions` as you have done in comments above.

You may also have a try on https://github.com/nuxt-community/create-nuxt-app to see the directory structure, hope it can help you 😸
