### ISSUE TITLE
scripts can't be injected into </body>

### ISSUE THREAD

**Issue by cdoneshot** [nuxt/nuxt.js#2279]
this is my head() method
```js
  head() {
    return {
      link: [
        "../azure/azuremediaplayer.min.css",
        "../azure/azure-stream.css",
        "../azure/azure-plugins.css",
        "../azure/azure-custom-skin.css"
      ].map(link => {
        return { rel: "stylesheet", href: link };
      }),
      script: [
        "../azure/azuremediaplayer.min.js",
        "../dist/azure.js"
      ].map(src => {
        return { src: src, body: true, type: "text/javascript" };
      })
    };
  }
```

When I set 'body' to false, the scritps can be injected into the head tag, set to false and can‘t be injected in front of </ body>, or even an html document.

**nuxtjs:v1.0.0-rc11
vue-meta:v1.3.1**

**Comment by sebastianks** [comment]
Hi. This has been discussed here before, and them nuxt team replied with this: https://github.com/nuxt/nuxt.js/issues/2000#issuecomment-341380762.

**Comment by cdoneshot** [comment]
>Hi. This has been discussed before, and the nuxt team replied with this: #2000 (comment).

That issue was opened by me and has now been closed. I checked that vue-meta has added this feature in v1.3.1, but it does not seem to work

**Comment by sebastianks** [comment]
Ah, sorry, I was a bit quick there, didn't see it was you. Where do you see this feature is implemented to Nuxt? I didn't know this was added.

**Comment by cdoneshot** [comment]
nuxtjs使用vue-meta来更新head和html，我认为vue-meta支持了这个特性就可以了，nuxtjs并不需要做什么。并且我的issue被关闭了，哈哈~~

**Comment by sebastianks** [comment]
Fair. Maybe you should use it like this: https://github.com/declandewet/vue-meta#script-object. Instead of mapping - does that make a difference for you?

**Comment by clarkdo** [comment]
Hi @cdoneshot , this issue has been fixed, but still not released yet in Nuxt, will be available soon.
