### ISSUE TITLE
Add ignore to page to avoid nuxt route auto generation

### ISSUE THREAD

**Issue by hueyhe** [nuxt/nuxt.js#228]
Hi, I encountered a problem when I tried to split a large page into pieces.
For example, I have a page which includes three tabs. I want to split them into three different files and then import as a component. But if I define these tabs in `~pages` directory, nuxt will auto generate routes related to them which is not what I want.
Meanwhile, I think it is not a good way to place these files in `~components` directory, cuz they are not components but pieces of a large page.
So I think maybe there can be something like a ignore mark in page which can tell nuxt that it should not be regarded as a page.

Thanks

**Comment by alexchopin** [comment]
Hi,
Nuxt generate a route for every file in the `~pages` directory and we don't want to avoid this behaviour. 
If you don't want to put tabs in the `~components` you are free to create a `~partials` directory to put these tabs and import them as a component with `~/partials/tab_one` for example.
