### ISSUE TITLE
Bug: Live Reload works incorrectly with Vue plugin registration

### ISSUE THREAD

**Issue by sokyrko** [nuxt/nuxt.js#2282]
Vue plugins don't deletes from Vue.
Example:
```import Vue from 'vue'

const Plugin = {
  install (Vue) {
    Vue.mixin({
      created () {
        console.log('one')
      }
    })
  }
}

Vue.use(Plugin)
```
Add the code to plugin file and register it in nuxt.config.js
```
  plugins: [
    {src: '~/plugins/plugin.js'},
  ...
  ]
```
Start server and check logs. 'one' is appears.
Then change 'one' to 'two' and wait for live reload.
Reload the page. 'one' and 'two' both present in console.
Expected: only 'two' appears.
Nuxt version: 1.0.0-rc8

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1998">#c1998</a>)</em></sub></div>

**Comment by Atinux** [comment]
This could not be fixed since it's a particular SSR behaviour :/
