### ISSUE TITLE
How to recreate page on same link?

### ISSUE THREAD

**Issue by Clemens-B** [nuxt/nuxt.js#2285]
Hello,

I have a fixed navigation bar and I want to recreate (without reloading the whole App) the page, if the users clicks the same link again. I tried to work with the prop key on the nuxt tag, but this doesn't work.

```html
<div class="navigation-bar">
   <button v-on:click.native="$router.push('/news')">News</button>
</div>

<nuxt :key="$route.fullPath"></nuxt> 
``` 

See also here: [Stackoverflow](https://stackoverflow.com/questions/40884023/vue-js-rerender-the-same-component-when-changing-route)

**Comment by clarkdo** [comment]
1. `native` only supports binding on components, https://vuejs.org/v2/api/#v-on
2. Nuxt has created `key`  of `<nuxt>` as `$route.path`, if you want to change it, use `:nuxtChildKey='...'` on `<nuxt>`

If you wan to reload pages, try:

```js
<button @click="$router.go({path:'/news', force: true})">News</button>
```

**Comment by Clemens-B** [comment]
Hello clarkdo,

thanks for your answer. `$router.go `reloads the whole page, but I want to initialise a new instance of the page without reloading the webapp.

`:nuxtChildKey` sounds promising and I already gave it a first shoot by applying a unique ID like `Date.now()` to `:nuxtChildKey` but this doesn't seem to work.

For now, I routing to a loading page before redirecting to news again.

**Comment by clarkdo** [comment]
You can have a look at https://github.com/vuejs/vue-router/issues/296, `canReuse` may help you

**Comment by hartmut-co-uk** [comment]
@Clemens-B you're probably past that issue, but everyone ending up here.. -> have a look at `$forceUpdate()`

```
<template>
  <div id="app">
    <nuxt ref="page"/>`
...
`this.$refs.page.$forceUpdate()`
...
```

**Comment by benwinding** [comment]
Any new solutions to this yet?

**Comment by benwinding** [comment]
I found that as described above this solves the issue.

``` vue
<nuxt :key="$route.fullPath" />
```
And allows any page to render again even if it's a link to itself with different query parameters
