### ISSUE TITLE
want to hook on page component js import error

### ISSUE THREAD

**Issue by igtm** [nuxt/nuxt.js#2286]
nuxt page component js filename changes every time we use `npm build`

Considering deployment, for example, if a user uses our nuxt app and then we build and deploy new nuxt app, the user no longer be able to go to next page by SPA because the next page component js filename changes and no longer import and render. it's not good...

![2017-11-29 17 57 06](https://user-images.githubusercontent.com/6331737/33406219-2c694a8e-d5af-11e7-9eee-1c6b316f20a9.png)

i would say one idea avoiding this problem is support for adding custom hook on page component js import error. (for example, refresh the browser)

any ideas ??

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2001">#c2001</a>)</em></sub></div>

**Comment by clarkdo** [comment]
The `hash` of filename in calculated from content of component file, it will be changed only when content of file is changed.

In development, every change will lead to a dev rebuilding and hot-replacing and file will be replaced.

In production, every change should be deployed by rebuilding and restarting and users will access new files directly.

What are your specific operating steps ?

**Comment by igtm** [comment]
Thanks your response.

We use ECS (AWS) for operating Nuxt app.
So when deploying our new version app, the app is fully replaced.

So again, if there are some users that still use old version app when we switch old version app to new version app,  the users fail to go to next page by spa(nuxt-link tag) if the next page component js filename changes...

If our app should be deployed very frequently (for example, thousands in a day), many users will encounter to the problem. It’s very bad for UX...

Any solutions??

**Comment by igtm** [comment]
note: page components are imported dynamically (on SPA). so if the js file is 404, the nuxt app on client browser cannot render the next page and throw error.

**Comment by Atinux** [comment]
Hi @igtm 

Indeed we may work on this issue to reload the app if the chunk is not found.

**Comment by hanjeahwan** [comment]
Our production facing this issue also when keep update to live server , load chunk fail 😣

**Comment by manniL** [comment]
Further discussion on https://github.com/nuxt/nuxt.js/issues/3389
