### ISSUE TITLE
NUXT redirect before html rendering

### ISSUE THREAD

**Issue by adnanmokhtar** [nuxt/nuxt.js#2287]
i want to redirect to another domain if user comes from mobile when i type the url in browser before any html rendering.

but some html header and footer appear before redirect happen

how to fix that

**Comment by InstanceOfMichael** [comment]
You should be able to come up with a solution after reading these. There's multiple ways to address this, such in a component, in the vue-router, or in a middleware.

https://router.vuejs.org/en/advanced/navigation-guards.html
https://github.com/nuxt/nuxt.js/issues/112#issuecomment-271609395
https://nuxtjs.org/api/configuration-router/#extendroutes
https://nuxtjs.org/guide/routing#middleware

Another option is to check in the root component's mount function and redirect using:
```
if (!isMobile && window.location.origin === "mobile.yoururl.com") {
    window.location = "http://www.yoururl.com";
}
```

**Comment by adnanmokhtar** [comment]
it work fine if i use navigation the redirect happen before rendering 

but if i refresh the page or enter from url the redirect happen after some of html appear in the page

**Comment by clarkdo** [comment]
`redirect` wii support external link in both server and client side in next release.
