### ISSUE TITLE
Error: Cannot read property 'serverRendered' of undefined Show all frames

### ISSUE THREAD

**Issue by NemoAlex** [nuxt/nuxt.js#2289]
I was following the guide of vue-router: https://router.vuejs.org/en/advanced/navigation-guards.html
When I do `next('/')` in one component:

```
beforeRouteEnter (to, from, next) {
  next('/')
},
```

Server shows:

```
Error: Cannot read property 'serverRendered' of undefined Show all frames
```

But works well on browser rendering.

Did I miss anything?

**Comment by clarkdo** [comment]
I have opened a pr to fix it: https://github.com/nuxt/nuxt.js/pull/2298

**Comment by vaggelis2018** [comment]
this error still exists. At least with router.js plugin

**Comment by NemoAlex** [comment]
@vaggelis2018 Which version of nuxt.js did you tested?
The PR is after rc11. So you have to do it on latest DEV branch.

**Comment by vaggelis2018** [comment]
For some reason i had version rc9. How to get latest dev?

**Comment by NemoAlex** [comment]
@vaggelis2018 
Use the `next` tag.
```
npm install nuxt@next --save
```
or
```
yarn add nuxt@next
```

**Comment by vaggelis2018** [comment]
now i get this error ReferenceError: regeneratorRuntime is not defined during compiling

**Comment by vaggelis2018** [comment]
The error i got was irrelevant. Your solution @NemoAlex was fixed my issue thanks

**Comment by jflaflamme** [comment]
Doesn't work for me, also tried with 1.1.1 .. seem triggered by having ssr: true in plugin definitions

**Comment by vaggelis2018** [comment]
@jflaflamme are you using @jflaflamme vue-material or any other framework?

**Comment by jflaflamme** [comment]
@vaggelis2018 it was related to a function not able to work in SSR, I just started dev in spa mode instead `yarn run dev -s ` 
thanks anyway
