### ISSUE TITLE
(question) Are there plans for a centralized logging facility?

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#2290]
Currently logging in nuxt is mostly implemented by calling a module/class specific `Debug` instance directly. Are there plans to integrate a centralized logging facility?

Things I would like to be able to do are:
- Different log levels and/or levels of verbosity
In the case of nuxt-generate eg it would be nice if we would be able to only print statements from the generator class (normal mode), print statements from the render class (verbose mode) and print statements from hook calls (debug or very verbose mode)
- Append output to a file, with possibility to redirect warn / errors to a different file
- Custom prefixes unrelated to the module/class the log statement is generated in
- Have the logging/debug statements abstracted from the log facility implementation
Eg in `builder/generator.js` I removed the log statements and switched them to hook call's because for generate-cluster I wanted the log statement to include the worker id. But actually I think it would be better to not 'mis-use' hooks for this, one way to solve this is if you could just attach your own log method so you could prefix the log statement (eg by extending a default nuxt logging class?)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2004">#c2004</a>)</em></sub></div>

**Comment by clarkdo** [comment]
cc @Atinux @pi0

**Comment by awolden** [comment]
This would be a very nice to have, or at least allow users to pass in a custom logger like bunyan. We basically want to turn off all debugger logging and enable bunyan json format logging so we can more easily forward logs to splunk.

**Comment by lukebarton** [comment]
On a related note, I'd also like some hooks around requests so I can gather metrics for prometheus.

An API similar to express would be great - it's important to be able to intercept the start of the request and have access to the response at the end e.g.
```js
use((req, res, next) => {
  const start = Date.now();
  req.id = uuid.v1();
  console.log(req.id, req.pathName);
  req.on('end', () => {
    const duration = Date.now() - start;
    console.log(req.id, res.statusCode, duration + 'ms'));
  });
})
```

**Comment by Oldenborg** [comment]
+1

**Comment by nicroto** [comment]
Is there any work done in this direction (centralized logging solution)? Thanks.

**Comment by galvez** [comment]
Nuxt Edge already uses [`consola`](https://github.com/nuxt/consola) which should open up some space for this (along with some improvements that have already taken place).

Closing the issue for now.

**Comment by hauleth** [comment]
@galvez is there any way to configure `consola`?

**Comment by pimlie** [comment]
For those who would like to implement a custom consola implementation for logging which is also used by Nuxt, thats possible but due to module caching in node you have to pull some tricks. You can check [nuxt-generate-cluster](https://github.com/nuxt-community/nuxt-generate-cluster/tree/master/lib/utils) how I implemented my custom consola impementaton there with custom reporters. Please note that you have to make sure you import your own consola instance before any other external module that also import consola.

You can also check this question for more background info: https://cmty.app/nuxt/consola/issues/c35
