### ISSUE TITLE
Transition on page reload

### ISSUE THREAD

**Issue by nicoladl** [nuxt/nuxt.js#2293]
Hi guys, why transition javascripts hooks doesn't load when I reload the page?
I mean when I load the page from a direct url or with cmd+R.

I'm looking this example and i see that when I reload the page the transition doesn't load.

**To reproduce:**
https://nuxt-type.now.sh/prata (page load without transition and the console doesn't show 'enter from prata')

**Expected behaviour:**
On reload or via direct link the page transition load like you are navigate from hp -> page prata

Thank you!

**Comment by nickngqs** [comment]
You can use the appear option :)

Like this

```
export default {
	transition: {
		...
		appear: true,
		css: false,
		beforeEnter(el) {
			console.log('PAGE - Before Entering')
		},
		enter(el, done) {
			console.log('PAGE - Entering')
			done()
		},

		leave(el, done) {
			console.log('PAGE - Leaving')
			done()
		}
		...
	}
}
```
