### ISSUE TITLE
Looping Routes

### ISSUE THREAD

**Issue by pxwee5** [nuxt/nuxt.js#2294]
I'm sorry I can't seem to find an example that shows us how to loop through different levels in the `page` directory and use loop to produce a set of links. 

For e.g. My directory structure:
```
Pages
  > index.vue
  > about.vue
  > contact.vue
```

Is there a way I could have:
`<nuxt-link for="route in routes" to="route.path">route.name</nuxt-link>`
to output all the links in the navigation as such?

```
<nuxt-link to="/">index</nuxt-link>
<nuxt-link to="/about">About</nuxt-link>
<nuxt-link to="/contact">Contact</nuxt-link>
```

**Comment by HoraceKeung** [comment]
<script>
export default {
	computed: {
		routes () {
			const context = require.context('../pages', false, /\.vue$/)
			return context.keys().map(k => {
				return '/' + k.split('/')[1].split('.')[0]
			})
		}
	}
}
</script>

Try something similar

**Comment by pxwee5** [comment]
Didn't work. 
This works though, but I can't find much documentation on the exact way to do this. 
`console.dir(this.$router.options.routes)`

**Comment by clarkdo** [comment]
@pxwee5 
`$router.options.routes` is fine, but if you use dynamic route like '/:id', you'd better add a `v-if` to exclude them
```js
    <nuxt-link v-for="route in $router.options.routes" v-if="!/\:/.test(route.path)" :key="route.name" :to="route.path">{{route.name}}</nuxt-link>

```
