### ISSUE TITLE
error generating nested routes in index

### ISSUE THREAD

**Issue by mojereliev** [nuxt/nuxt.js#2296]
Good day! Generation of nested routes to index tries to render `//routeName`

![uyn_w-hxtau2lptxuxuolw](https://user-images.githubusercontent.com/13470898/33473553-b54133a0-d698-11e7-8fa5-49cf03acc2c8.png)

Error generating nested route only in index.
Someone can suggest what this is: bug or feature?

**Comment by clarkdo** [comment]
It's a bug, I will fix it asap. 😺 

But your project structure is not recommended, if you want to make a route `/features`, you can put `features.vue` into `pages` or `pages/feature/index.vue`.

**Comment by mojereliev** [comment]
Thanks! My structure is so because in `/pages/index.vue` there is a router-view. That is, there is a common part for `index` and `features` pages, so `features` are embedded in `/pages/index`.
