### ISSUE TITLE
root methods is not a function when i refresh page

### ISSUE THREAD

**Issue by leeziiAtCn** [nuxt/nuxt.js#2297]
I code a plugins as vue doc
```
import Vue from 'vue'
  let MyPlugin = {}
  MyPlugin.install = function (Vue, options) {
  Vue.prototype.$myMethod = function (methodOptions) {
    console.log(window)
  }
}
Vue.use(MyPlugin)
```
this is my nuxt config
```plugins: [
    {
      src: '~plugins/utils',
      ssr: false
    },
    '~plugins/element-ui'
  ]
```
when i use $myMethod
```<script>
  module.exports = {
    data () {
      return {
        text: 'lee'
      }
    },
    created () {
      console.log(this.$myMethod())
    }
  }
</script>
```

if i don' t refresh this page  the $myMethod  is ok , i get a console log
but i refresh this page  i will get this error on my page , 
`this.$myMethod is not a function`

i  console.log(this.$myMethod) i get this but i can't use this function because this is not a function .  hahahah~
```
ƒ (methodOptions) {
    console.log(window);
  }
```

**Comment by KonstantinVlasov** [comment]
`created` hook executed on the server and browser environment, try to use `mounted` or remove `ssr: false`

**Comment by leeziiAtCn** [comment]
@KonstantinVlasov  ok bro u r right , but i have a problem, why vue document wrote the 'mounted' isn't called durring server-side rendering?
the link https://vuejs.org/v2/api/#mounted

**Comment by KonstantinVlasov** [comment]
Sorry, I think I don't understand you.
If you really need to use `created` hook with `ssr: false` plugin, then you can use `process.browser`:
```javascript 
created () {
  if (process.browser) {
    console.log(this.$myMethod())
  }
}
```
You read more about how ssr works [here ](https://ssr.vuejs.org/en/universal.html), check "Component Lifecycle Hooks"

**Comment by leeziiAtCn** [comment]
@KonstantinVlasov  oh thanks you
