### ISSUE TITLE
svg inline loader

### ISSUE THREAD

**Issue by davision** [nuxt/nuxt.js#2302]
Hello!

Have anyone implemented svg loader? I am looking for a solution to use .svg images as components.
If I import .svg as a normal vue component, an error occurs:

```
[Vue warn]: Invalid Component definition: data:image/svg+xml;base64
```

Any suggestions?

Thank you very much!

**Comment by clarkdo** [comment]
Nuxt.js doesn't svg loader yet, you can try to import svg in data
```vue
<template>
  <div>
    <img :src="demo"></img>
  </div>
</template>

<script>
import demo from '~/assets/demo.svg'
export default {
  data: () => ({
    demo
  })
}
</script>
```
If you want to use svg as component, you may use loaders like https://github.com/visualfanatic/vue-svg-loader, and use `build.extend` of `nuxt.config.js` to config webpack loader.

```js
odule.exports = {
  build: {
     extend (config, { dev, isClient }) {
       // config is webpack configuration
     }
  }
}
```

**Comment by davision** [comment]
Many Thanks for this! Will try right away.
