### ISSUE TITLE
Integrating Nuxt to ongoing project generated with Vue Cli

### ISSUE THREAD

**Issue by raza2022** [nuxt/nuxt.js#2304]
Hello
First big thanks for the great work for the community :+1: 
I have an very big ongoing project generated with Vue cli 2.x. now i want to add server side rendering through nuxt.js I tried many ways but can't success because of nuxt requires different directory structure. so i just wanna the best path to achieve server side rendering in an ongoing project.
what I have tried.
manipulating the webpack config and dev server to make the server side nuxt work but it's very complex and i till I have error like nuxt want `pages` directory.
start a new project with nuxt starter template but that also require all my component code to copy one by one on that project and resolve upcoming errors (remember it's very big application)
can someone suggest the best path for it. any suggestion will be greatly appropriated
Thanks

**Comment by clarkdo** [comment]
You may have a look at https://github.com/nuxt-community/create-nuxt-app, hope it can help you 😺

**Comment by raza2022** [comment]
ok i will giving it a shot Thanks. :)

**Comment by kushalmahajan** [comment]
@raza2022 Did it solve the the issue?

 @clarkdo That was not the question 😮
