### ISSUE TITLE
nuxtServerInit Not Working with localhost:3000

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [nuxt/nuxt.js#2307]
hello,

i'm using [Adonuxt ](https://github.com/nuxt-community/adonuxt-template )template (Adonis + Nuxt)
well,
i have created a simple `Vuex State` called `counter`,
this is `index.js` content:
```
import axios from '~/plugins/axios'

export const actions = {

  async increment ({ commit }) {
    await axios.get('http://localhost:3000/api/v1/counter')
    .then(response => {
      commit('increment', response.data)
    })
    .catch(e => {
      console.log(e)
    })
  },

  async nuxtServerInit ({commit}) {
    await axios.get('https://www.random.org/integers/?num=1&min=1&max=2&col=1&base=10&format=plain&rnd=new')
    .then(response => {
      commit('increment', response.data)
    })
    .catch(e => {
      console.log(e)
    })
  }

}

export const state = () => ({
  counter: 0
})

export const getters = {
  getCounter (state) {
    return state.counter
  }
}

export const mutations = {
  increment (state, payload) {
    state.counter += payload
  }
}

```

My Local API link return: `99` (link 1)
the Random API link return: random numbers `1 or 2` (link 2)

my problem when using `nuxtServerInit` with local `link(1)`
**nuxtServerInit** should init the `counter` with `99`, but NO -_- i get default value :`0`

otherwise: when i leave the code as it is above: `random numbers` its work and init the counter with `1` or `2`.

1. is that related to `https`?
2. how i can call local api to so that `nuxtServerInit` can use it with axios!!!

**Notice: the `increment` `Action` works fine with `Local API`, when clicking the button that increments `counter` go correctly: adding +99**

**But with `nuxtServerInit` Not Working!!!**

my `axios.js` code:
```
import axios from 'axios'

const instance = axios.create({
  baseURL: process.env.API_HOST + ':' + process.env.API_PORT,
  transformRequest: function (request) {
    return request
  }
})

export default instance
```

i have tried the promises, and i have followed some threads from googling, but nothing changed!
i have tried `api/v1/counter` also but nothing ...

any help! and thank you :)

**Comment by Imanullah** [comment]
I'm using nuxtClientInit is working well

add plugin 
`export` default async (ctx) => {
  await ctx.store.dispatch('nuxtClientInit', ctx)
}`

**Comment by dohomi** [comment]
@NadhirBoukhenifra I think I'd rather use middleware or a plugin for a async request to be honest. Not sure if `nuxtServerInit` supposed to work asynchronous

**Comment by mywebstuff** [comment]
@NadhirBoukhenifra you're mixing async-await with simple promises. It's not necessarily a bad thing, although you should `return` the commit from the then callbacks if your using it this way, like this:

```js
async increment ({ commit }) {
    await axios.get('http://localhost:3000/api/v1/counter')
    .then(response => {
      return commit('increment', response.data)
    })
    .catch(e => {
      console.log(e)
    })
  }, // etc.
```

The other way however, would be to use simple async-await:

```js
async increment ({ commit }) {
    try {
        const response = await axios.get('http://localhost:3000/api/v1/counter')
        return commit('increment', response.data)
    } catch (e) {
        console.log(e)
    }
  },  // etc.
```

Also, @dohomi, this is from the [documentation](https://nuxtjs.org/guide/vuex-store/#the-nuxtserverinit-action) at the bottom of the page:

> Note: Asynchronous nuxtServerInit actions must return a Promise to allow the nuxt server to wait on them.

**Comment by NadhirBoukhenifra** [comment]
the problem is from `nuxtServerInit` its not calling local API !!
i get `response.status: 204` when calling the local API, but when increment the counter, it works !!!
```
export const actions = {

  async increment ({ commit }) {
    try {
      const response = await axios.get('http://localhost:3000/api/v1/counter')
      return commit('increment', response.data)
    } catch (e) {
      console.log(e)
    }
  },
  async nuxtServerInit ({ dispatch }) {
    await dispatch('increment')
  }
}
```

and i have tried the `Promise`, and the page keeping loading `infinite cycle!!`
```
  async nuxtServerInit ({ commit }) {
    await new Promise((resolve, reject) => {
      axios.get('http://localhost:3000/api/v1/counter')
      .then(response => {
        commit('increment', response.status, promise => {
          promise.then(resolve).catch(reject)
        })
        console.log(response.status)
      })
    })
  }
```

and same result using `dispatch`:
```
export const actions = {

  async increment ({ commit }) {
    try {
      const response = await axios.get('http://localhost:3000/api/v1/counter')
      return commit('increment', response.data)
    } catch (e) {
      console.log(e)
    }
  },
  async nuxtServerInit ({ dispatch }) {
    await new Promise((resolve, reject) => {
      dispatch('increment')
    })
  }
}
```

another test: calling local API from `nuxtServerInit` using axios and the result is `204`:
```
  async nuxtServerInit () {
    await axios.get('http://localhost:3000/api/v1/counter')
      .then(response => {
        console.log(response.status) // 204
    })
  }
```

**Comment by kongdewen1994** [comment]
`import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

let count = 0

const createStore = () => {
  return new Vuex.Store({
    state: {
      counter: 0
    },
    mutations: {
      increment (state, payload) {
        state.counter = payload
      }
    },
    actions: {
      nuxtServerInit ({ commit }) {
        count++
        commit('increment', count)
      }
    },
    getters: {
      counter (state) {
        return state.counter
      }
    }
  })
}

export default createStore`

nuxtServerInit Not Working
