### ISSUE TITLE
Middleware redirect infinity loop & Vuex Data not updating

### ISSUE THREAD

**Issue by fahidmohammad** [nuxt/nuxt.js#2308]
I'm using auth route with middleware and when using the below snippet the application going on a infinity loop.
```
export default function ({ store, redirect, error }) {
  console.log('store.state.authUser',store.state.authUser);
  if (store.state.authUser!=null) {
	  console.log('inside null')
	  redirect('/secret')
  }
}
```

**Login View**
![image](https://user-images.githubusercontent.com/1906114/33523203-db5354b2-d826-11e7-9e1e-7b1c474146e0.png)

**Successful Login**
![image](https://user-images.githubusercontent.com/1906114/33523214-04016c1e-d827-11e7-9301-b9705e206e95.png)

**When clicking the link**

![image](https://user-images.githubusercontent.com/1906114/33523241-b827213e-d827-11e7-9d49-7ae8307e0e6d.png)

The same route when accessed using direct url its working fine. But not when using 
`<nuxt-link to="/secret">Super secret page</nuxt-link>` 

## Update:
Also the `store.state.authUser` is globally accessible across different browser, when using with express.

**Express Code below:**
```
let config = require('./nuxt.config.js')

config.dev = !(process.env.NODE_ENV === 'production')

// Init Nuxt.js
const nuxt = new Nuxt(config)

// Build only in dev mode
if (config.dev) {
  const builder = new Builder(nuxt)
  builder.build()
}
// Give nuxt middleware to express
app.use(nuxt)
```

**Comment by fahidmohammad** [comment]
Please download the complete sample project which has the re-producible scenario.
I hope this will help identify the issue in detail.
I was trying to make JWT works with Cookie both server and client.
**Below is the list of prerequisites used in this sample project**
1. Mongoose
2. Express
3. jsonwebtoken
4. express-jwt
5. @nuxtjs/axios
6. config
7. vue-cookie
8. @nuxtjs/router

[Download Sample Project Here](https://github.com/nuxt/nuxt.js/files/1524614/JWT-Express-Mongoose-nuxt.zip)

**Comment by uptownhr** [comment]
Check current route in middlewares before redirect. This can only be a infinite loop as it will redirect to secret over and over

**Comment by fahidmohammad** [comment]
@uptownhr how about the Vuex data issue? that seem to be a major blocker to Nuxt.js

**Comment by Mahinanas** [comment]
Guys... Am also facing same  issue on nuxt.js,

Please do a look into it....,

**Comment by uptownhr** [comment]
Is your store being set on the nuxtserverinit?

**Comment by fahidmohammad** [comment]
Yes indeed..

```
async nuxtServerInit({ commit, dispatch }, { req }) {
  if (req.cookies && req.cookies.token) {
    await commit('SET_USER', req.cookies.token)
  }
}
```
Shouldn't i do that ???

**Comment by gurralaharikrishna1988** [comment]
I am also facing the same issue. It is stopping me to kickstart my project using nuxt

**Comment by clarkdo** [comment]
@fahidmohammad 
You need to wrap the `login` for avoiding state sharing in node cache. Such as:

store/index.js
```js
import Vue from 'vue'
import Vuex from 'vuex'
import login from './modules/login'

Vue.use(Vuex)

const store = () => new Vuex.Store({
  ...login()
})

export default store
```

store/modules/login.js
```js
/* eslint-disable */
import axios from 'axios'
import cookie from 'vue-cookie'

const login = () => ({
  state: {
    signupEnable: true,
    signinEnable: false,
    token: null
  },
  mutations: {
    SET_USER: function (state, token) {
      /* ... */
    }
  },
  actions: {
    async nuxtServerInit({ commit, dispatch }, { req }) {
      /* ... */
    },
    /* ... */
    async ACTION_LOGOUT({ commit, state }) {
      await commit('SET_USER', null)
    }
  },
  getters: {}
})

export default login

```

**Comment by fahidmohammad** [comment]
Thank you so much @clarkdo for the heads, your approach solved the issue with the  Vuex issue 👍 
And Thank you @uptownhr for the redirection solution 👍

**Comment by nusendra** [comment]
im facing the same error. infinity loop.
so this code is working perfectly
```
export default function ({ store, route, redirect }) {
  if (!store.state.user.authenticated) {
    if (route.path === '/login') {
    } else {
      return redirect('/login')
    }
  }
}
```
