### ISSUE TITLE
Vue Filters

### ISSUE THREAD

**Issue by app-sparkler** [nuxt/nuxt.js#231]
Hello,

Where can i write the `filters` for the `vue application`?  For ex:

`Vue.filter('capitalize', val => val.toUpperCase())`

Eariler it would reside in the `main/app.js`.

Thanks

**Comment by Atinux** [comment]
Hi @app-sparkler 

Take a look at the plugins section of the documentation: https://nuxtjs.org/guide/plugins

You can have a `filters.js` file in your `plugins` directory:

```js
import Vue from 'vue'

Vue.filter('capitalize', val => val.toUpperCase())
```

Then, in your `nuxt.config.js`:

```js
module.exports = {
  plugins: ['~plugins/filters.js']
}
```

Nuxt.js will automatically import your file before creating the root instance.

**Comment by Cengkaruk** [comment]
Hi @Atinux 

How about two-way filters? I'm following [this migration guide](https://vuejs.org/v2/guide/migration.html#Two-Way-Filters-replaced) and got some error.

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
...
client.js:390 [nuxt.js] Cannot load components TypeError: Cannot set property 'value' of undefined
    at VueComponent.formatValue (currencyInput.js:81)
    at VueComponent.boundFn [as formatValue] (vue.runtime.common.js:127)
    at VueComponent.mounted (currencyInput.js:70)
    at callHook (vue.runtime.common.js:2754)
    at Object.insert (vue.runtime.common.js:1765)
    at invokeInsertHook (vue.runtime.common.js:4474)
    at VueComponent.patch [as __patch__] (vue.runtime.common.js:4638)
    at VueComponent.Vue._update (vue.runtime.common.js:2635)
    at VueComponent.updateComponent (vue.runtime.common.js:2609)
    at Watcher.get (vue.runtime.common.js:2934)
```

**Comment by Atinux** [comment]
Can you provide code example to reproduce this error?

We can't help you without the reproduction.

**Comment by Cengkaruk** [comment]
I use this [snippet](https://jsfiddle.net/chrisvfritz/1oqjojjx)

**Comment by Atinux** [comment]
It should work without problem @Cengkaruk 

Can you show your code your doing with Nuxt.js?

**Comment by linsir** [comment]
@Atinux 
I has a same problem with use the `v-html`,like:

    v-html="`${ post.abstract | marked }`"
 but if I use `{{post.abstract | marked}}`,it works

**Comment by Atinux** [comment]
@linsir indeed you should use:

```
v-html="{{ post.abstract | marked }}"
```

**Comment by Cengkaruk** [comment]
@Atinux This [my plugin](http://pastebin.com/Esst5p9g) and i use it on the pages using this block of code.

```
<currency-input
    v-model="price"
  ></currency-input>
```

**Comment by alexchopin** [comment]
@Cengkaruk have you tried this?
```html
<currency-input :value="price"</currency-input>
````

**Comment by linsir** [comment]
@Atinux But I try it ,it does not work, and the log:

    
  Vue template syntax error:

  - invalid expression: v-html="{{ post.abstract | marked }}"

**Comment by app-sparkler** [comment]
@linsir it should also work with :+1: 
```
v-html="post.abstract"
```
you don't need the `${...}` since you're not _concatenating_ the string here..

Does it work?

**Comment by linsir** [comment]
v-html="post.abstract"

it does not work.

**Comment by app-sparkler** [comment]
@linsir This issue is no longer regarding `Vue-filters`, i think you should go ahead and open a `New Issue`

**Comment by linsir** [comment]
@app-sparkler Sorry, 

    v-html="post.abstract"

it works. But

    v-html="post.abstract | marked"

it does not work.

**Comment by Atinux** [comment]
@linsir you should use a computed property for `v-html` if you want to use a filter.

**Comment by app-sparkler** [comment]
@linsir 

Assuming what you are trying to bind to `v-html` is an `html string` and you want to apply some `filter` to it, i've tried this:


- `thtml` is the `custom directive` we'll create
- `capitalize` is the `filter` we will apply to it

In your template:
...
<div v-thtml="testHtml" filter="capitalize"></div>
...

Your `script` which will contain the `data` and `directive` defintions:

```
<template lang="pug">                                                          
div                                                                                                
  div(v-thtml="testHtml" filter="capitalize")                                  
</template>                                                                    
                                                                               
<script>                                                                       
import $ from 'jquery'                                                         
                                                                               
export default {                                                               
  data () {                                                                    
    return {                                                                   
      testHtml: `
         // The h1 tag here is what we will be transforming                                                              
        <h1>Hello World</h1>                                                   
        <p>The world says hello!</p>                                           
      `                                                                        
    }                                                                          
  },                                                                           
  directives: {                                                                
    thtml: {                                                                   
      inserted (el, bindings) {
        const template = $(bindings.value)
        // we'll be adding some-class "class" to the h1 tag (refer the style tag below for its definition )                  
        template.filter('h1').attr('class', 'some-class')  
        template.appendTo(el)
      }                                    
    }                                   
  }                                       
}                                           
</script>                  

<style>
// converts text to uppercase                                                                
.some-class {                                                        
  text-transform: uppercase                                   
}                                         
                                                                         
</style>
```

**Comment by linsir** [comment]
@Atinux Thanks.
@app-sparkler Because I use `v-for`, I use `computed` and `Props` (child component) to solve it.

**Comment by app-sparkler** [comment]
Ok @linsir :+1: 

I've updated the answer in case you want to _apply_ filters on `html strings`.

Thanks.

**Comment by linsir** [comment]
@app-sparkler  Okay, thank you.

**Comment by jeck5895** [comment]
Hi after upgrading to 2.0.1 my filter in my plugins is not working again....

**Comment by aldarund** [comment]
@jeck5895 create a reproducible example on codesandbox or github repo

**Comment by aldarund** [comment]
@jeck5895 well, provide full not working example, because this code should work.

**Comment by jeck5895** [comment]
here: https://codesandbox.io/s/82j2n97pr2

**Comment by aldarund** [comment]
@jeck5895 its something with your filter regexps. https://codesandbox.io/s/0qjw35q3p - see here replaced your regex logic with simple return and ti work

**Comment by jeck5895** [comment]
@aldarund but its working if I'm putting it on function method.
