### ISSUE TITLE
Putting a .ts file in middleware/ leads to death

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#2310]
`nuxt` version: `1.0.0-gh-704e7cd`
If you put a `.ts` file in `middleware/` while `nuxt dev` is running, everything is fine.
Furthermore, this file is actually compiled as typescript and can be required on pages through the `middleware` property.

However, if you stop the process and try to run `nuxt dev` again, you will get the most peculiar error:
(only) page-level components (only) with `<script lang="ts">` will produce the following error:

```
  ERROR  Failed to compile with 1 error

 error  in ./pages/check.vueerror  in ./pages/test.vue

Module build failed: Error: Could not find file: '/test/pages/test.vue'.
    at getValidSourceFile (/test/nod
e_modules/typescript/lib/typescript.js:95642:23)
```
This happens for any `.ts` file in middleware and any `<script lang="ts">` in a page, even if the middleware is empty and unused and the script tag is empty.

**Comment by clarkdo** [comment]
Can you have a look at: https://github.com/clarkdo/nuxt.js/tree/issue_2310/examples/typescript, it works for me, if anything I missed, pls tell me 😺

**Comment by Atinux** [comment]
Hi @qm3ster 

In 1.0, we will remove native TS support, it will have to be used in with a module, so it will remove this unexpected behavior.

**Comment by AndrewBogdanovTSS** [comment]
@Atinux I'm using [nuxt-ts-starter](https://github.com/nuxt-community/typescript-template) template and I **do want** my middleware as .ts files, I don't want to exclude them. How can I use them? I'm currently using 1.0.0-alpha.5 and still getting this error when I try to use .ts files inside middleware folder

**Comment by qm3ster** [comment]
@AndrewBogdanovTSS  are you up to date with https://github.com/nuxt/nuxt.js/blob/dev/examples/typescript/modules/typescript.js ?

**Comment by AndrewBogdanovTSS** [comment]
What do you mean by "up to date" ? I'm using latest CLI build of the ts starter template? Does it need any additional configurations to support .ts files? I thought that the whole intent of this template was to provide such functionality for users out of the box

**Comment by AndrewBogdanovTSS** [comment]
@qm3ster I've updated my modules/typescript.ts file to reflect the link you've sent, not I'm getting 2 errors:
(node:2104) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'push' of undefined
(node:2104) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'push' of undefined
My version of node is 8.9.4 in case this matters

**Comment by qm3ster** [comment]
That's just node, you need to go higher in the call stack.
Where is this `.push`?

**Comment by AndrewBogdanovTSS** [comment]
There is no "higher" http://take.ms/Tv9Hz
That's all I get after running `npm run dev`
I suppose it happens here:
```
// Add .ts extension for store, middleware and more
    this.nuxt.options.extensions.push('ts')
```

**Comment by AndrewBogdanovTSS** [comment]
I tried to debug it deeper but it's all buggy, fixing one issue reveals another one. Feels like it's not compatible with the setup used in Nuxt TS Starter

**Comment by qm3ster** [comment]
Well, that's unhandled promise rejection for you! It turns men into vegetables and women into alcoholics.

**Comment by qm3ster** [comment]
@AndrewBogdanovTSS, my duderino...
I just tried it on latest nuxt and everything works.
The only reference to typescript is the file I linked you and the corresponding
```js
	modules: ['~/modules/typescript.js'],
```
in `nuxt.config.js`

It then started compiling my middleware and I was able to use it.
You call it by name, right? (`router: {middleware: ['test']}`) You're not importing it?

**Comment by AndrewBogdanovTSS** [comment]
> I just tried it on latest nuxt and everything works.
Did you tried it on the version 1.0.0-alpha.5 ? It's the one that is used by the nuxt ts starter template

**Comment by qm3ster** [comment]
Certainly not, there is no reason to use an alpha now that there's a release version.
I tried it, especially for you, and I do indeed get these errors.
It is caused by lines 3 and 22-26(24)
```js
	this.nuxt.options.extensions.push('ts')
//...
	for (let rule of config.module.rules) {
		if (rule.loader === 'vue-loader') {
			rule.options.loaders.ts = tsLoader
		}
	}
```
This is because the mechanism for adding custom script loaders wasn't fully extracted yet in that version.
Just commenting them out works, but I suggest updating to the current `nuxt`. It's always worth it.

**Comment by AndrewBogdanovTSS** [comment]
I'm all for it, but I'm just pointing out that I had to use alpha version because it was specified in the starter template and updating to new version manually was causing my app to crash. I've created a separate issue about that here: https://github.com/nuxt-community/typescript-template/issues/24
