### ISSUE TITLE
[feature request] Ignore files with a prefix in all filesystem APIs

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#2311]
In at least `pages/`, `middleware/`, `store/`, files (and directories(?)) that begin with a certain character or series of characters should not suffer the indignity of automatic import.

Pros:
- Will allow quickly working around issues such as #2310, while keeping the `.ts` file next to the `.js` file that is reexporting it.
- Will allow to better organize source code: 
  - utils shared by many store modules and only store modules go in `store/`
  - utils shared by many pages and only pages go in `pages/`
  - components shared by a group of pages go in `group/`
  - utils shared by many middlewares and only middlewares go in `middleware/`
  - etc.

Cons:
- Absolutely none, not breaking if the prefix is not set by default

The prefix should be configurable in `nuxt.config.js`, including disabling it if one is set by default.

**Comment by Atinux** [comment]
What about starting by `-`? It's like "minus".

What's you thoughts here?

**Comment by qm3ster** [comment]
@Atinux files and directories starting in `-` are a menace in cli tools - they always demand quotes because otherwise they are interpreted as flags.
I suggest `_`, a staple for partials and other files that should not be exposed.

**Comment by Atinux** [comment]
@qm3ster Actually `_` are used for dynamic routing (`pages/_id.vue` -> `/:id`). I don't see the problem since you won't have to use any CLI tools with Nuxt.js :)

**Comment by qm3ster** [comment]
Right, forgot why I didn't suggest that back when I wrote this. :man_facepalming: 
But yeah, it shouldn't interfere with people who manage their files on the command line.
I didn't mean nuxt commands having to mention files, I meant things like moving or opening your editor.
In any case, it should be configurable, but if there is to be a default, `-` is as out as `_`.

- `.` would be a funny one. Hides files from animals and nuxt.
- `@` seems alright, but it would make sense more for the dynamic routing than for the hidden.
- `` ` ``, `'`, `"` and `,` are bad.
- `__` is a bulletproof last resort.

**Comment by icarito** [comment]
> you won't have to use any CLI tools with Nuxt.js :)

:-( @Atinux but the CLI is awesome for so many things!

I really think `.` would be the ideal one. Then both the CLI and Nuxt will omit these files. Nuxt integrates with your command line.
