### ISSUE TITLE
env after build

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#2315]
tell me what to do so that after the assembly the conditions for "process.env" not cut out

example:

nuxt.config.js
```
const CDN_HOST = process.env.CDN_HOST || 'http://127.0.0.1:10800';
const API_HOST = process.env.API_HOST || 'http://127.0.0.1:8080';

...
env: {
    API_HOST,
    CDN_HOST,
    PANEL: 'client'
  },
...
```

after the assembly "API_HOST" and "CDN_HOST" is cut from the code, and I need them to remain, both for the client side and server side

**Comment by uptownhr** [comment]
Can you describe what it means to be cut?

**Comment by wormen** [comment]
@uptownhr 
after the assembly, in `nuxt.config.js > env` config is set static value, instead of the above condition

tried to write different combinations so that the condition remained in the code, but in the end, still after the assembly there was only a line with the current value in `ENV`

**Comment by uptownhr** [comment]
The production builds have to be static so it won't be possible to read in env varsfrom server. This code runs in the browser so it is unaware of the server env.

**Comment by clarkdo** [comment]
@uptownhr is right.

`env` of nuxt.config.js will be resolved as a constants in webpack building, so if you want to set `CDN_HOST` in runtime, you can directly use `process.env.CDN_HOST` or [`dotenv`](https://github.com/motdotla/dotenv) in runtime instead of `env`
