### ISSUE TITLE
Remove #__nuxt div

### ISSUE THREAD

**Issue by pSchaub** [nuxt/nuxt.js#2317]
My nuxt application always has a div with the id `__nuxt` inside `<body>`.
Is it possible to remove this div? Why is it needed?

Reason:
For me it was important to add this css to get my divs to 100% height:
```
#__nuxt {
  height: 100%
}
```

This wouldn't be needed if the `__nuxt` div does not exist.

**Comment by clarkdo** [comment]
`<div id='__nuxt'>` is the root node for mounting Vue instance, so you cannot remove it.

If you want to customize styles of `__nuxt`, you can put them to [global css](https://nuxtjs.org/api/configuration-css#the-css-property)
