### ISSUE TITLE
Layout in Layout

### ISSUE THREAD

**Issue by pSchaub** [nuxt/nuxt.js#2318]
Is it possible to use a layout that extends from another layout?
I have a design where I have different "sub-layouts" but the main design around it is always the same.

**Comment by uptownhr** [comment]
Not to my knowledge.

**Comment by clarkdo** [comment]
What the purpose of defining `sub-layouts`?
1. If you want to reuse the HTML, you can use `components` to include parent layout.
2. If you want to reuse the methods or other logics, you can use `mixin` or `extend` to extend parent layout.
