### ISSUE TITLE
Nuxt.js with compiled Vue.js app 

### ISSUE THREAD

**Issue by kajcula** [nuxt/nuxt.js#2319]
Please.. I need help. I have two applications. First of them was built on Nuxt.js and the second on Vue.js. How can i put this second one to Nuxt page component? First I need include this files to head of page:

```
<script type="text/javascript" src="http://localhost/js/manifest.js"></script>
<script type="text/javascript" src="http://localhost/js/vendor.js"></script>
<script type="text/javascript" src="http://localhost/js/app.js"></script>
<script type="text/javascript" src="http://localhost/js/fetch.js"></script>
```

and next on component HTML template I have this box:

`<div id="comments"></div>`

and after that I need call this function:

```
<script type=text/javascript>
       window.appComments({
           selector: '#comments',
           token: '123456789',
           apiURL: 'https://someurl.com/',
           uri: 'some uri',
           title: 'Sample title of an article',
           url: 'some URL'
        })
</script>
```

I try copy and paste this code to component HTML template and also put it to mounted()..  Always I get this errors :

> "Uncaught TypeError: window.appComments is not a function"
> "Uncaught TypeError: Cannot read property 'call' of undefined"

What's wrong with that :( ?

**Comment by clarkdo** [comment]
> First I need include this files to head of page:

Global: https://nuxtjs.org/api/configuration-head#the-head-property
Specified Page: https://nuxtjs.org/api/pages-head#the-head-method

> and after that I need call this function:

Put it into `mounted` is ok, but the error seemed that `appComments `  is not a function, where did you declare it ?

**Comment by kajcula** [comment]
It works! At the beginning i putted scripts to head of specified page. When I put scripts to Global head configuration and call function in mounted it start working. Yay! Great!

 Now I have other problem.. when I change route path to other post page this call function  doesn't refresh by Nuxt. How to solve that?
