### ISSUE TITLE
cssModules is not defined on HMR

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#232]
Unfortunatley, I'm not sure how to provide more detail but whenever changes are made and HMR kicks, I get the error, "cssModules is not defined". I'm not using cssModules in my project at all and not really sure how to go about debugging this. Any pointers? 

Here's my package.json

```
{
  "name": "admin",
  "version": "1.0.0",
  "description": "bambee admin",
  "dependencies": {
    "axios": "^0.15.3",
    "body-parser": "latest",
    "bulma": "^0.3.1",
    "express": "^4.14.1",
    "express-session": "^1.15.0",
    "filepicker-js": "^2.4.18",
    "moment": "^2.17.1"
  },
  "devDependencies": {
    "node-sass": "^4.2.0",
    "nodemon": "^1.11.0",
    "nuxt": "latest",
    "sass-loader": "^4.1.1"
  },
  "scripts": {
    "dev": "nodemon --ignore store/ server.js",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  }
}
```

**Comment by Atinux** [comment]
Hi @uptownhr 

This is a known issue, I will work on it, it happens when you have children routes.

Because it's only for HMR, it's not a priority issue, but will be fixed before the `1.0`.

**Comment by uptownhr** [comment]
awesome. I know we talked about it, but couldn't remember you identified it the cause.

**Comment by Atinux** [comment]
I updated the HMR code in the `0.10` and the children routes should work perfectly now 👍
