### ISSUE TITLE
Example for subpage directories + LD JSON

### ISSUE THREAD

**Issue by ladislavsulc** [nuxt/nuxt.js#2323]
Hello,

first, let me thank you for such a great _tool_. Since I am new with Vue.js and NuxtJS, in particular, I wanted to ask you 2 questions.

1) How can one create for example a "projects" in pages with project detail pages (e.g. for a porfolio)?
2) How can one add Schema.org ld+json structure in the header?

Any example would be much appreciated. And yes, I have studied the documentation.

Thank you!

**Comment by clarkdo** [comment]
> How can one create for example a "projects" in pages with project detail pages (e.g. for a porfolio)?
Hope `https://github.com/nuxt-community/create-nuxt-app` can help you
> How can one add Schema.org ld+json structure in the header?
HTML Head may help you : https://nuxtjs.org/guide/views#default-meta-tags, https://nuxtjs.org/api/pages-head

**Comment by ladislavsulc** [comment]
Thank you, I have read all the docs yet it didn't help - even saw that example. Though I am a total beginner...
