### ISSUE TITLE
Unexpected behavior with dynamic nested routes

### ISSUE THREAD

**Issue by samirph** [nuxt/nuxt.js#2327]
My intention was to create those routes:

`/blog/:category/:subcategory/:postSlug`
`/blog/:category/:subcategory`
`/blog/:category`
`/blog`

My folder structure looks like this:

![folder-struct](https://user-images.githubusercontent.com/4563904/33609646-1507c35c-d9b0-11e7-9e91-1be6b938dc82.png)

Followed these docs: https://nuxtjs.org/guide/routing#dynamic-nested-routes
Paid attention to the </nuxt-child> tag, looking at these docs: https://nuxtjs.org/api/components-nuxt-child/

Expected behavior:
`/blog` shows posts
`/blog/:category` shows posts of a category
`/blog/:category/:subcategory` shows posts of a subcategory
`/blog/:category/:subcategory/:postSlug` shows a post

Actual behavior:
`/blog` shows posts (content in blog/index.vue)
`/blog/:category` shows posts of a category (content in blog/_categorySlug.vue)
`/blog/:category/:subcategory` 
shows posts of a category (content in blog/_categorySlug.vue)
shows posts of a subcategory  (content in blog/_categorySlug/_subCategorySlug.vue)
shows content inside  blog/_categorySlug/_subCategorySlug/index.vue

`/blog/:category/:subcategory/:postSlug` 
shows posts of a category (content in blog/_categorySlug.vue)
posts of a subcategory  (content in blog/_categorySlug/_subCategorySlug.vue)
content inside  blog/_categorySlug/_subCategorySlug/_postSlug.vue

Screenshot when accessed `/blog/cat/sub/post`
Shows posts of a category, subcategory and in the end shows the post title (there's only a title saying "Post page" in `_postSlug.vue`)
![post-page](https://user-images.githubusercontent.com/4563904/33610168-cd5fc69c-d9b1-11e7-8afc-529589a41a02.png)

Should it really work like this?

**Comment by clarkdo** [comment]
If you don't want subpages contains content of parent, you can just remove `sub-dir/index.vue` or `nuxt-child` in it, then it will only show the content of itself page.

**Comment by samirph** [comment]
Removing the `index.vue` files did not change the behavior. The folder structure now looks like this:

![blog-folder-struct](https://user-images.githubusercontent.com/4563904/33659555-b88e8a4e-da67-11e7-9eb6-3bd4f7270c99.png)

When I remove the `nuxt-child ` tag, always the parent `_categorySlug.vue` is rendered, can't access `subCategorySlug` nor `postSlug` page components.

**Comment by clarkdo** [comment]
Try moving:
1. `_categorySlug.vue` to `_categorySlug/index.vue`
1.  `_ subCategorySlug.vue` to `_categorySlug/_subCategorySlue/index.vue`

**Comment by samirph** [comment]
Following these steps and removing the original files `_categorySlug`.vue and `_subCategorySlug.vue` solved my problem. The use of `nuxt-child` tag was not necessary.

Thanks a lot!

It might be interesting to add to these docs https://nuxtjs.org/guide/routing#dynamic-nested-routes an additional example for this expected behavior.
