### ISSUE TITLE
Static generated site not running on my hosting (bluehost)

### ISSUE THREAD

**Issue by unwrittenmike** [nuxt/nuxt.js#2328]
Hi there

Ran nuxt generate, then uploaded the contents of the dist folder to my hosting and the site does not run. HTML and CSS loads but it looks like Javascript does not run. Runs fine on my local using npm run dev. Runs fine on Netlify. Runs fine on MAMP. 

Looking at the console, no errors. Looking in the network tab everything seems to load no 404's

Any help would be greatly appreciated
 
[http://www.mikestott.net/nissan/](url) #

**Comment by clarkdo** [comment]
Can you provide a repo can reproduce your issue ?

**Comment by piyushchauhan2011** [comment]
I think this one is because of `/nissan/` url , you need to provide `baseUrl` options maybe @unwrittenmike ?

**Comment by nicoladl** [comment]
Try this in your nuxt.config.js

```
router: {
    base: '/nissan/'
  }
```

**Comment by unwrittenmike** [comment]
@clarkdo  Will provide soonest. I can reproduce. I used one of the nuxt example repo's and added an alert on a button click. That still isn't working. I tried to rule out any bugs in my code being the issue. If I put breakpoints in the javascript that is loading the code execution pauses. It's almost if it's jut not running the app code...

**Comment by unwrittenmike** [comment]
@piyushchauhan2011  my original config was:
`router: {
    base: 'http://www.mikestott.net/nissan/'
  },`

changed it to:

`router: {
    base: '/nissan/'
  },`

as @nicoladl suggested

**Comment by unwrittenmike** [comment]
@clarkdo , @piyushchauhan2011 , @nicoladl  Code here has been updated to use this config: 
[http://mikestott.net/nissan/](url)

`router: {
    base: '/nissan/'
  },`

Still not getting my alert to fire off when clicking the button which says test.

Very strange issue. Thanks for the help by way and thanks for taking a look :)

**Comment by nicoladl** [comment]
@unwrittenmike can you provide a repo with this example?
thank you

**Comment by unwrittenmike** [comment]
@nicoladl @clarkdo My repo: [git@bitbucket.org:unwrittenmike/nuxtalerttest.git](url) Thanks

**Comment by nicoladl** [comment]
@unwrittenmike change the event handler.
From: 
`@click="clickMe"`
To: 
`v-on:click="clickMe"`

Let me know if it works for you

**Comment by bovas85** [comment]
v-on and @click are the same theoretically.

However I noticed with some elements you might need @click.native to make it "click"

@unwrittenmike have you tried that?

**Comment by unwrittenmike** [comment]
@bovas85  I haven't tried that although my console.log() isn't running in mounted() either so I suspect that the issue is not with the click handler

**Comment by nicoladl** [comment]
@unwrittenmike cloning your repo and changed the event handler works for me

**Comment by unwrittenmike** [comment]
@nicoladl  Running it locally with npm run dev works for me, running it locally using  mamp works for me... it's when I use npm run generate and upload to my hosting(bluehost) is where it wont run...

**Comment by unwrittenmike** [comment]
Magically started working on my hosting!
