### ISSUE TITLE
Page Prefetching

### ISSUE THREAD

**Issue by FrancosLab** [nuxt/nuxt.js#233]
Can't find any info on this, but does Nuxt have a page prefetching feature similar to Next.js?

Basically it loads a page in the background, which provides instant navigation once user actually clicks the link.

**Comment by Atinux** [comment]
Not yet @FrancosLab 

We will add this feature when we will start working on performances with progressive web apps, see #23

**Comment by corsen2000** [comment]
This is [currently documented](https://nuxtjs.org/api/configuration-performance/#prefetch), but does not appear to be implemented yet. Am I misunderstanding or was this documented early?

**Comment by Atinux** [comment]
It will be implemented in the next release, but via `prefetch` headers.

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋

**Comment by supra28** [comment]
@Atinux , Sorry for commenting on a closed issue, I was going through the documentation of vue and nuxt to decide whether to use this in producion. 
I have a question about prefetch:
Can we set what links we want prefetched? 
Like if I have 10 links on my home page I don't want them all to be prefetched (want only the most visited ones).
