### ISSUE TITLE
Setting new relic agent

### ISSUE THREAD

**Issue by valeriosillari** [nuxt/nuxt.js#2330]
I set a basic app with Nuxt and deployed on heroku.
Now I would like to add the new relic agent (node js).

I have already a new relic profile, a license key for my application and and follow the new relic info:
1) Get your license key
2) add new relic package (done)
3) add a file in the root of the app, called "newrelic.js"  and set it here the license key (done)

**now next step i got troubles.**
they say : "Require New Relic. Make this the first line of your app's startup script"
just add the code:
`require('newrelic');`

Here i am not sure in which file I have to add this line and how to write it.

I suppose I should add it to nuxt.config.js and as first line.
I did it and my app during the deploy is going in some loop and never ending.

I know I am doing something wrong, but not sure what.
Suggestions?
you can see the code here:
[](https://github.com/valeriosillari/nuxt-new-relic/blob/master/nuxt.config.js
)

Maybe is a silly question and I am newbie, but I did not find any info about it ...

Thanks :)

**Comment by clarkdo** [comment]
You can use custom server like express and koa, and put `newrelic` into first like of `server.js`.

Documentation: https://nuxtjs.org/examples/auth-routes#using-express-and-sessions

**Comment by valeriosillari** [comment]
thanks II check the documentation and trying to solve it  :)
