### ISSUE TITLE
npm dependency problem in v0.10.7

### ISSUE THREAD

**Issue by phlogisticfugu** [nuxt/nuxt.js#2331]
since it is still the latest "release" version, this problem is v0.10.7 should still be applicable

nuxt.js has a dependency on "preload-webpack-plugin": "^1.2.2"

but that resolves to
https://github.com/GoogleChromeLabs/preload-webpack-plugin/blob/v1.2.3/package.json
which in turn has a peer dependency on webpack 3.x

this results in the yarn error:
```
error "nuxt#preload-webpack-plugin#webpack@^3.2.0" doesn't satisfy found match of "webpack@2.7.0"
```

propose releasing a v0.10.8 which changes the nuxt.js dependency

from: "^1.2.2."
to: "1.2.2"

**Comment by clarkdo** [comment]
Try `"nuxt": "1.0.0-rc11"`
