### ISSUE TITLE
Expose localhost to external - Debug in dev mode

### ISSUE THREAD

**Issue by nicoladl** [nuxt/nuxt.js#2335]
Hi guys!
After `npm run generate` I can serve dist folder and expose ip in my network.
How can I do the same thing during development with localhost:3000?

Thank you

**Comment by christophwolff** [comment]
`npm install cross-env`

and change the dev script in your package json

"dev": "cross-env NODE_ENV=development HOST=0.0.0.0 PORT=3000 nuxt",

**Comment by nicoladl** [comment]
Thank you @christophwolff
I need to expose ip when i launch `dev` script, not when I launch `generate`.

I have try this:

`"dev": "cross-env NODE_ENV=development HOST=0.0.0.0 PORT=3000 nuxt"`

Browser returns: `Cannot GET /`

My goal is debug the application with mobile devices in dev mode so I can have hot reloading.

Thank you

**Comment by christophwolff** [comment]
ahh i understand. i do exactly this in the dev script and it works for me.

**Comment by nicoladl** [comment]
@christophwolff thank you
I tried your solution but after I have launched the script, browser at 0.0.0.0:3000 responded with

`Cannot GET /`

There's something wrong?

My setup is:
- vue-i18n
- dynamics routes

**Comment by ckpiggy** [comment]
Try this https://ngrok.com/

**Comment by Hellowor1d** [comment]
+1

**Comment by Hellowor1d** [comment]
@nicoladl  Hi~ have you solved this ?  I have the same scene， need your help 💯

**Comment by Hellowor1d** [comment]
@nicoladl  I had solved the problem recently, just like the method of @christophwolff. I didn't install `cross-env`, but also made difference.

1. One of my project is based on [nuxt-starter ](https://github.com/nuxt-community/starter-template)
add HOST into `package.json`, like below:
```json
"scripts": {
    "dev": "HOST=0.0.0.0 nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  }
```
2. Another project is based on [nuxt-express](https://github.com/nuxt-community/express-template)
change the default host from `127.0.0.1` to `0.0.0.0` in `server/index.js`
```js
const app = express()
const host = process.env.HOST || '0.0.0.0'
const port = process.env.PORT || 3000
```
make sure that your mobile devices are in the same  wifi network with your development server,
open the page on mobile device through `http://{server IP} : {port} `
> tip: https is not supported under default setting

**Comment by nicoladl** [comment]
I'm following @christophwolff and @Hellowor1d suggestions and [this guide](https://nuxtjs.org/faq/host-port/). But when i try to open http://0.0.0.0:3333 on my mobile device I get connection_refused. (I'm in the same wifi network).
What I do wrong?

**Comment by nathakits** [comment]
@nicoladl you can try replacing the HOST `0.0.0.0` with **your** internet address. for example something like this  `192.168.1.2`

**Comment by nicoladl** [comment]
It works!
Thanks @nathakits

**Comment by benwinding** [comment]
Here's an easy way to expose the _nuxt_ app to the local network, just use your IP before calling `yarn start`
```
$ HOST=192.168.1.5 yarn start
```
