### ISSUE TITLE
Trying to add a mixin to main Vue instance

### ISSUE THREAD

**Issue by cyberiaa** [nuxt/nuxt.js#2336]
Hi guys,

I'm trying to add some global data (and methods) to main Vue instance. I don't want to use Vuex so I end up with creating a plugin for nuxt:
```

import Vue from 'vue'

Vue.mixin({
    data: {
        my_global_config: 'This'
    },
    created: function () {
        console.log('mixin hook called')
    }
    methods: {}
})
```

Created method works correctly but I don't have access to data using
` this.$root.my_global_config` 
Any idea?

**Comment by wielski** [comment]
You are not injecting any plugin. By that way you are able to use mixin in global context
```
this.my_global_config
```

**Comment by cyberiaa** [comment]
So you mean this:

```
export default ({app}, inject) => {
    inject('my_global_config', mixin)
}
```

Thanks! it works but I'm still curious about main question as it may be helpful in some situations. 

I could make this work not sure if it's a best practise.

export default ({app}, inject) => {
    app.mixins = [my_mixin] 
}

**Comment by christophwolff** [comment]
have you added the plugin to your nuxt config?

**Comment by cyberiaa** [comment]
Yes, I did.

**Comment by clarkdo** [comment]
Try

```js
import Vue from 'vue'
Vue.mixin({
  data: () => ({
    my_global_config: 'This'
  }),
  created: function () {
    console.log('mixin hook called')
  }
})
```
