### ISSUE TITLE
SSR CSS - document size becomes too large

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#2337]
Nuxt by default outputs CSS loaded through the `css` entrypoint in `nuxt.config` on all pages. This is to help the page load faster by not having to make another over the wire call. However, I'm running into some major issues with the document size now. 

I'm using Bulma with Buefy and some other custom css. Using the build analyzer, I can see that the gzipped size is 38kb for the entire generated css. However, because this is embedded into the html and the html is not gzipped, the size is expanded out to 375kb.

I wish
1. there is an option to gzip the html doc. With the styles added, it is 10x larger than it needs to be. Not sure what kind of performance impact it'll have on the server but would love to test out.
2. option to not add css to the html and load through `linked styles`. I understand this can lead to FOC but might be something I'm willing to do to avoid the large document delivery.

If someone has experience using Bulma/Buefy with Nuxt and have better optimized their load times. Please chime in and help!

**Comment by dohomi** [comment]
@uptownhr you might try:
```
nuxt.confi.js
build:{
  extractCSS:true
}
```

**Comment by uptownhr** [comment]
Will try thanks!

**Comment by iamdubx** [comment]
As far as I remember there was gzip feature in Nuxt, but it was removed since it's better to do with web server or hosting provider.

**Comment by clarkdo** [comment]
@iamdubx  
Actually `gzip` is not removed, just disabled in `dev` mode.  😸 
In `production` mode, it's still enabled and can be configured by `render.gzip` in `nuxt.config.js`.
https://nuxtjs.org/api/configuration-render#gzip

**Comment by iamdubx** [comment]
Got it. It was removed from `generate` option, if I am not mistaken.

**Comment by uptownhr** [comment]
thanks everyone!
