### ISSUE TITLE
npm run generate error 

### ISSUE THREAD

**Issue by yyyuuu777** [nuxt/nuxt.js#2338]
`{ Error: ENOENT: no such file or directory, lstat '/Users/xxx/programmer/project/vue-ssr/dist/index.html'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/xxx/programmer/project/vue-ssr/dist/index.html' }`

I have not use nuxtServerInit method and no dynamic route in my project, but when i run 'yarn generate' still get this error

**Comment by clarkdo** [comment]
Does you pages have any ajax operation ?
