### ISSUE TITLE
i18n - Compile Error when try to render html content with {{{ $t('mytranslation')}}}

### ISSUE THREAD

**Issue by muthukumarsp** [nuxt/nuxt.js#234]
I am using    vue-i18n (version 4.10.0) for internationalization support and it works well with SSR also.
In my content I have few html phrass tags( <strong> <em> etc..)..

As per the documentation to format html content I am binding the language translation function using {{{ 
}}}.

https://kazupon.github.io/vue-i18n/formatting.html

I get the following error during compilation. 

ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-24d04d10!./~/vue-loader/lib/selector.js?type=template&index=0!./pages/trading/markets/forex.vue
template syntax error - invalid expression:  {{{$t('mytranslation')}}}
 @ ./pages/trading/markets/forex.vue 11:23-145
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

Please help me to resolve this

**Comment by muthukumarsp** [comment]
I found a way to fix this.
 
 <div  v-html="$t('mytranslation')"</div>

The language tranlation works without any issue.. but is it a right way to do?

**Comment by Atinux** [comment]
Hi @muthukumarsp 

Actually, `vue-i18n` does not work yet with SSR since it updates the Vue object which is shared across all requests: https://github.com/kazupon/vue-i18n/issues/62#issuecomment-261705767

Example: https://github.com/nuxt/nuxt.js/tree/master/examples/i18n
Demo: http://i18n.nuxtjs.org/
