### ISSUE TITLE
Possible to debug with breakpoints in Visual Studio Code?

### ISSUE THREAD

**Issue by luminarious** [nuxt/nuxt.js#2341]
Attempting to debug SSR requests with VSCode on macOS is currently a pain. There are basically 4 places to check for errors:

1. Browser screen when the error is caught and displayed
2. Browser console
3. Terminal
4. VSCode debug tools

The pain arises from the fact that the error message could be on all, some, or none of these. My most fervent wish would be to use the editor debug mode with breakpoints, but current configuration does not make them usable (source maps not found):

```
{
	"type": "node",
	"request": "launch",
	"name": "launch nuxt",
	"protocol": "inspector",
	"program": "${workspaceRoot}/build/node_modules/.bin/nuxt",
	"cwd": "${workspaceFolder}/build"
}
```
Caveat: my repo has the Nuxt project in /build/ folder not at root.

**Comment by clarkdo** [comment]
Do you wang to debug builded dist ? In build, there is no detailed source map, you can config it by:

```js
// nuxt.config.js
build: {
    extend(config, options) {
      return Object.assign({}, config, {
        devtool: 'source-map'
      })
    }
  }
```

If you want to debug in dev mode, use:
```json
{
        "name": "Debug Hare Dev",
        "type": "node",
        "request": "launch",
        "protocol": "inspector",
        "program": "${workspaceRoot}/node_modules/.bin/nuxt",
        "stopOnEntry": false,
        "args": ["dev"],
        "cwd": "${workspaceRoot}",
        "sourceMaps": true,
        "env": {
            "NODE_ENV": "development",
            "DEBUG": "nuxt:*,app"
        }
      }
```

**Comment by gijswijs** [comment]
I didn't get this to work.

The first error I got is:

```
Cannot launch program 'C:\Repositories\non-ts-nuxt\node_modules\.bin\nuxt'; setting the 'outFiles' attribute might help.
```

Then after adding the outFiles attribute with pretty much every possible config I could think of, I keep getting:

```
Cannot launch program 'C:\Repositories\non-ts-nuxt\node_modules\.bin\nuxt' because corresponding JavaScript cannot be found.
```

Important detail: I ran this on Windows10

**Comment by gijswijs** [comment]
Why is it, that you always find the solution yourself 15 minutes after you post a comment?
Anyways, for future reference.
On Windows this works if you use modify the program parameter a bit
```
"program": "${workspaceRoot}/node_modules/nuxt/bin/nuxt"
```

**Comment by sobolevn** [comment]
@luminarious @clarkdo Can you please provide a full working example? I have spent the whole day trying to put this together. 

There's almost no valid information on this topic available.
