### ISSUE TITLE
install error :Cannot load the stats for nuxtjs

### ISSUE THREAD

**Issue by shamon76** [nuxt/nuxt.js#2343]
When i try to install nuxt with   `npm install --save nuxt` i got this error

[server error] Cannot load the stats for nuxtjs – please try again later

```
node version-v8.9.2
npm version-5.5.1
```

**Comment by clarkdo** [comment]
It should because your network problem when nuxt tried to get info from opencollective.com, the package has already installed before it, it doesn't affect the normal use of package 😄
