### ISSUE TITLE
A real fix for: The client-side rendered virtual DOM tree is not matching server-rendered content.

### ISSUE THREAD

**Issue by nigeltiany** [nuxt/nuxt.js#2345]
Even after loading a plugin with ```ssr: false``` and using the plugin's components wrapped around ```<no-ssr></no-ssr>``` I still get this error and the component does not load unless I change the code to trigger a hot-update then it loads. Then, after doing a refresh through the browser button, the error does not show and the component does not show either.

I have to trigger a hot-update for the component to show and that's what's interesting.

**Comment by clarkdo** [comment]
`<no-ssr></no-ssr>` only works for the components which although not support 'ssr' but didn't use `DOM` related api in initialization.

If your component uses `DOM`, you can use async and dynamic component. such as:

```vue
<template>
  <div>
    <component :is="asyncComp"></component>
  </div>
</template>

<script>
export default {
  data: () => ({
    asyncComp: ''
  }),
  components: {
    'example': () => {
      import('@/components/example')
    }
  },
  mounted() {
    this.asyncComp = 'example'
  }
}
</script>
```
