### ISSUE TITLE
Using and managing GSAP in Nuxt

### ISSUE THREAD

**Issue by digisocialnet** [nuxt/nuxt.js#2347]
I am having some trouble getting GSAP to work the way other Nuxt modules or plugins work. I got it to animate but I feel like I am duplicating code too much. I posted all of the details on StackOverflow but haven't received much response. Can anyone here make some reccomendations or share some links to help me? Thank you!

[https://stackoverflow.com/questions/47667771/how-can-i-better-manage-using-gsap-animations-in-nuxt-js](https://stackoverflow.com/questions/47667771/how-can-i-better-manage-using-gsap-animations-in-nuxt-js)

**Comment by digisocialnet** [comment]
Oh, I guess this partially answers my question but any other tips are welcome!  https://github.com/pirony/ks-vue-scrollmagic 🧐

**Comment by nicoladl** [comment]
To manage an open/close menu transition I use a boolean state.

My layout.vue

```
<MenuInit v-on:click.native="$store.commit('toggleMenu')"/>
<MainMenu v-if="$store.state.menu.show"/>
```

That help me to show/hide menu component

In my MainMenu component I wrap all the markup in a transition tag to call transitions method. Something like that:

```
<template name="menu">
  <transition v-on:before-enter="beforeEnter" v-on:enter="enter" v-on:leave="leave">
    ....
  </transition>
</template>

export default {
   methods: {
       beforeEnter: function (el) {
          // A lot of TweenMax code here
      }
      enter: function (el, done) {
          // A lot of TweenMax code here
      }
      leave: function (el, done) {
          // A lot of TweenMax code here
      }
}
```

And in my store/index.js:

```
export const state = () => ({
    menu: {
        show: false
    }
}) 

export const mutations = {
    toggleMenu (state, option) {
       state.menu.show = !state.menu.show
  }
}
```

(I am not sure 100% of the syntax because of I extract this code from a big code base)

**Comment by digisocialnet** [comment]
I don't make very big websites so I don't make that many components usually. I do like how you used the <transition> tag on the template. Putting GSAP code in components is very helpful too!

**Comment by nicoladl** [comment]
Glad to help!
