### ISSUE TITLE
route list upside down in 0.9.8

### ISSUE THREAD

**Issue by Knovour** [nuxt/nuxt.js#235]
I have a pages structure like

```
pages/
  - shop/
    - index.vue
    - _category.vue
```

In 0.9.7 routes, it will be generated to

```
{
	path: "/shop",
	component: _2a02d111,
	name: "shop"
},
{
	path: "/shop/:category?",
	component: _7e4de1c2,
	name: "shop-category"
},
```

But in 0.9.8, it became upside down

![group](https://cloud.githubusercontent.com/assets/893846/22813878/17e994a8-ef8a-11e6-8705-4bad7d17202e.png)

**Comment by Atinux** [comment]
It's now fixed in [v0.9.9](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.9).
