### ISSUE TITLE
Call Middleware When Full URL is Entered in browser address

### ISSUE THREAD

**Issue by lanbau** [nuxt/nuxt.js#2350]
I have a middleware function that checks for logged in users and redirects them to account page if logged in. 

it works well as the user is redirected to the account page after log in using $router.push('/account').

**The Problem:**
- When the user is logged in, i typed the full address 'http://www.url.com/accounts' for example and press the "Enter" key, it does not trigger the middleware and it lands on the sign-in page instead.

- When i refresh the page, it redirects me from account to sign in page as well

Any tips on how do i call the middleware when i enter the full address in the browser?

**Comment by lanbau** [comment]
i discovered that

middleware.js
`  store.state.user != null && route.name == 'signIn' ? redirect('/account') : ''
`
the store here is called in server side which is null.

But my store in client side has the user.

Is there anyway i can sync the store for both client and server?

**Comment by lanbau** [comment]
i solved this by checking the route on client side in the computed property. However, if there is a better solution, do let me know!

**Comment by clarkdo** [comment]
Server side not sync store with client side, you can use cookies or ajax to tell the token to server side.

Take a look at:
https://github.com/nuxt/nuxt.js/issues/2308
https://github.com/nuxt-community/auth-module/
