### ISSUE TITLE
Unable to update CSS variable (Follow up of #2342)

### ISSUE THREAD

**Issue by HoraceKeung** [nuxt/nuxt.js#2355]
follow up of #2342 
In global.css:
```
:root {
	--primary: green;
	--secondary: blue;
}
.primary {
	color: var(--primary);
}
.secondary {
	color: var(--secondary);
}
.btn-primary {
	background-color: var(--primary);
}
```
In /pages/dummy.vue
```
<template>
	<section>
		<p class="primary">primary</p>
                <button class="btn btn-primary">primary button</button>
		<p class="secondary">secondary</p>
	</section>
</template>

<script>
export default {
	mounted () {
		this.$nextTick(() => {
			document.documentElement.style.setProperty('--primary', 'yellow')
			document.documentElement.style.setProperty('--secondary', 'red')
		})
	}
}
</script>
```
Expect primary text and button to be yellow and secondary text to be red

Result:
![image](https://user-images.githubusercontent.com/6639120/33767089-2dacaea8-dc18-11e7-9137-c866baa432bd.png)

One of my older project that wan't using Nuxt starter template is able to update CSS variable dynamically: https://horacekeung.github.io/option
If you change the theme colour of the site, you will see this in dev tool:
![image](https://user-images.githubusercontent.com/6639120/33767447-7b695b22-dc19-11e7-9da2-4c4c84078fbb.png)
CSS variable --color and --dark are updated as shown.

My understanding is that in the Nuxt starter template, CSS is preprocessed hence variables such as --primary and --secondary are no longer a variable.

**Comment by clarkdo** [comment]
Nuxt enabled `postcss-cssnext` by default which will transform css variables to more compatible CSS, so changing at runtime may not work.

You can disable or customize config of `postcss` by `build.postcss` in `nuxt.config.js`:

```js
module.exports = {
  build: {
    postcss: false

    // or

    
    postcss: [
      /* ... */
    ]
  }
}
```

**Comment by ThatGuySam** [comment]
God bless you @clarkdo. You just saved my butt.
