### ISSUE TITLE
Error in next_tick.js:228 process._tickDomainCallback

### ISSUE THREAD

**Issue by houxiaohou** [nuxt/nuxt.js#2356]
when I run npm run dev, the error occured

```
TypeError: Cannot read property 'data' of undefined
  
  - server-bundle.js:5564 
    server-bundle.js:5564:158
  
  - next_tick.js:228 process._tickDomainCallback
    internal/process/next_tick.js:228:7
```

![image](https://user-images.githubusercontent.com/1525931/33770316-17b61b02-dc68-11e7-8b7f-3f8ce83ae66b.png)

**Comment by clarkdo** [comment]
The error has showed that `Cannot read property 'data' of undefined`, please check your code: if `/research/microbiology` can fetch data correctly.
