### ISSUE TITLE
Server Render Page -  log execute time

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#2357]
Hello! 
I use nuxt rc11 and use server express module

I need log execute time

I use this code

```
app.use(function (req, res, next) {
    console.log('req', req.url)

    nuxt.render(req, res, next)
})
```

But i want use this code

```
app.use(function (req, res, next) {
    console.log('req', req.url)

    var startExecute = new Date()

    nuxt.render(req, res, next)
        .then(r => {

            var endExecute = new Date()

            console.log('execute', endExecute - startExecute)
        })
})
```

But function nuxt.render()   not return promise

Please help me!!!!

**Comment by clarkdo** [comment]
`nuxt.render()` in ssr needs to return the response and after that headers and response cannot be changed, so it is the end of request chain.

In the coming 1.0.0 release, you can use `hook` to achieve it, if you want to have a try, you can use `nuxt@next`(not stable).

```
nuxt.hook('render:route', () => {
    var endExecute = new Date()
    console.log('execute', endExecute - startExecute)
})
```
