### ISSUE TITLE
change url query without changing page

### ISSUE THREAD

**Issue by ahadyekta** [nuxt/nuxt.js#2358]
I have a problem about changing url query in methods. 
First way:
When I use : 
```
var data = Object.assign({}, this.$route.query)
        data['color'] = somevalue
        this.$router.push({path: '/images', query: data})
```
The page refresh with correct query but load content twice.

Second way : 
When I  get the new content with ajax without reloading the page . I works good but I need to change the url query accordingly. 
What should I do in this dilemma?

**Comment by clarkdo** [comment]
You can use a `middleware` to load the dynamic `query` and `redirect` to the page with that query.

Doc: https://nuxtjs.org/api/pages-middleware#the-middleware-property

Maybe such like:

```js
export default async function ({redirect, route }) {
  if (!route.query) {
    const query = axios.get('...')
    return redirect('/login', query)
  }
}
```
