### ISSUE TITLE
Layout level middleware

### ISSUE THREAD

**Issue by rlindskog** [nuxt/nuxt.js#2359]
Is it possible to have layout level middleware in which all of the layouts pages inherit its middleware?

**Comment by sudhir600** [comment]
No answer yet.. did u solve @rlindskog

**Comment by fakiolinho** [comment]
Anything here?

**Comment by sudhir600** [comment]
I didn't find any solution. so i am adding middleware in each page.

**Comment by mstrlaw** [comment]
You just need to place your middleware within your layout, then set the layout in your page
```
/*
** yourLayout.vue
*/
<template>
  <div>
    <nuxt/>
  </div>
</template>

<script>
  export default{
    middleware: 'someMiddleware'
  }
</script>


/* 
** SomePage.vue
*/
<template>
  <div>
    <h2>Foo</h2>
  </div>
</template>

<script>
  export default{
    layout: 'yourLayout',
  }
</script>

```

Then when you navigate to SomePage the middleware is executed.
