### ISSUE TITLE
Rate limiting API with Nuxt/SSR?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2360]
Hi guys. I have not much experience with backend, so I ask you advise, since as I see this topic has special issues when we have SSR.

How should I protect my API server from abuse (Node server, MongoDB)?
What are the common strategies?

As I see, I need to separate queries from Nuxt server and from client?
Can somebody please explain, how it should be implemented? On which end (Node server, or maybe even nginx/failtoban level?)? Should I use tokens? But I don't have auth and don't need it much...

**Comment by Evild67** [comment]
Hi,

Rate limiting API should be implemented on your API. You can handle queries errors in Nuxt to display an error

**Comment by Evild67** [comment]
I'm not sur to understand but I think you want to separate user API request from API request done by Nuxt (AsyncData for exemple). 

You can rate limit what you want on your server. You can implement a token for your request done by Nuxt and then count number of request. It's same for request done by users, just use another token

**Comment by iamdubx** [comment]
@Evild67 yes, you understood right my unclear words, thanks. I was talking about AsyncData. If I rate limit only calls from client, then hacker can possibly abuse API by requesting Nuxt server, so I need to distinguish this requests somehow, right?

To tell the truth, I need to dig deeper, first to implement full working Auth with Nuxt using tokens, then deal with rate limiting. 

I will come back to this soon and post what I found.
