### ISSUE TITLE
Disable Code Splitting in Nuxt Config

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#2363]
Just wondering if we can get an option to disable code-splitting when generating routes ?

I tried to use the below but could get it to work:

```javascript
plugins: [
      new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 1
      })
    ]
```

**Comment by clarkdo** [comment]
It should be `build.plugins`, doc: https://nuxtjs.org/api/configuration-build#plugins.

Or you can use `build.extend` to customize any webpack config you want doc: https://nuxtjs.org/api/configuration-build#extend.
