### ISSUE TITLE
[Question] Nuxt Commands

### ISSUE THREAD

**Issue by dertuerke** [nuxt/nuxt.js#2369]
Hi, i have some Question :D

1. Do i need install "nuxt" Global?
2. What is the different between "nuxt build" vs "nuxt generate"? The only thing I see is, that the "nuxt generate"-Task create a "dist"-folder and "nuxt build" do nothing?

thx for Help :)

**Comment by paulgv** [comment]
Hi @dertuerke 
1. No, you don't need to install `nuxt` globally.
2. `nuxt generate` creates a [pre-rendered](https://nuxtjs.org/guide#static-generated-pre-rendering-) of your app, which means your pages are converted to static HTML, this is useful if you're building a simple website without user interactions or frequent updates. `nuxt build` compiles your assets for a production-ready [server-side rendered app](https://nuxtjs.org/guide#server-rendered-universal-ssr-).
