### ISSUE TITLE
Switch layout at the same time of complete page load with <nuxt-link>

### ISSUE THREAD

**Issue by mkv27** [nuxt/nuxt.js#237]
How can I get layout switch at the same time of page content switch?.
Currently when I use <nuxt-link> the layout switch is immediately, but the previous page content wait for new page content is loaded.

Example: When I routing for a new page with an async data, the layout change but the previous page content still alive(with "glitch" new layout) until new page data its ready.

**Comment by Atinux** [comment]
Hi @mkv27 

This issue is related to #214 

It will be fixed when the issue above fixed.
