### ISSUE TITLE
Having a script tag inside page does not warn/error

### ISSUE THREAD

**Issue by cristijora** [nuxt/nuxt.js#2373]
First of all great job guys!
I accidentally had a script tag inside a `.vue` file which I didn't notice. With the vue webpack template, you get a warning/error from the `vue-template-compiler` I think that there shouldn't be a script tag inside the `.vue` file.

**Steps to reproduce:**
1. Initialize nuxt from official nuxt template and run it locally
2. Create a page inside `pages` dir which contains a script tag
```vue
<template>
  <div class="copyright">
    &copy;
    <script>
      document.write(new Date().getFullYear())
    </script>, Designed by xxx
  </div>
</template>

<script>
  export default {
    name: 'about-us'
  }
</script>

<style>

</style>
```
3. Modify some text in the page. 

**What is expected?**
Nuxt will warn/give an error that you shouldn't have a script tag inside a `.vue` file.

**What is actually happening?**
Page hot reloads with no error but outputs only the script tag result. In this case, the current year.

I know this might sound dumb, but might be confusing for beginners who accidentally drop some scripts without knowing. After that, it might be hard to track what is happening.

**Comment by clarkdo** [comment]
Hi, thanks for your attention to Nuxt.js

`.vue` files are parsed by `vue-loader` at `webpack` compilation, so it's a server rendering parse. According to https://github.com/vuejs/vue/pull/3425/files, errors of forbidden tags on the server have been skipped.

**Comment by cristijora** [comment]
Thanks for the info. Pretty sad as it probably makes sense to have those. 
If there is no technical way to do it then I think you can close the issue @clarkdo
