### ISSUE TITLE
How fixed error "This dependency was not found: * plugin0 in ./.nuxt/index.js" in nuxt.config.js

### ISSUE THREAD

**Issue by Jussiadev** [nuxt/nuxt.js#2375]
Before I uploaded the project to the githab, the nuxt.config.js worked fine (on the localhost). Now the error pops up `This dependency was not found: * plugin0 in ./.nuxt/index.js`
```

module.exports = {
    loading: '~/components/loading.vue',
    head: {
        meta: [
            {charset: 'utf-8'},
            {'http-equiv': 'X-UA-Compatible', content: 'IE=edge'}
        ]
    },
    build: {
        extractCSS: true,
        vendor: ['axios']
    },
    generate: {
        minify: {
            collapseWhitespace: false
        }
    },

    modules: [
        // Or if you have custom bootstrap CSS...
        ['@nuxtjs/bootstrap-vue', { css: false }]
    ]

};
```

**Comment by clarkdo** [comment]
Which version of Nuxt.js did you use, can you have a try on `nuxt@next` ?

**Comment by Jussiadev** [comment]
@clarkdo, I tried the `nuxt@next `, but got errors

```
node_modules/vue-server-renderer/index.js:8
  throw new Error(
  ^

  Error: Vue packages version mismatch:
  - vue@2.4.4
  - vue-server-renderer@2.5.11
  This may cause things to work incorrectly. Make sure to use the same version for both.
```

`"nuxt": "^1.0.0-gh-c92d427",`

**Comment by clarkdo** [comment]
Try ` yarn add vue@^2.5.11 vue-server-renderer@^2.5.11 vue-template-compiler@^2.5.11`.

/cc @pi0 who is expert of bootstrap-vue.

**Comment by Jussiadev** [comment]
@clarkdo Thanks, it helped to get rid of this error. But the nuxt.config.js still  works if there are no `build`, `generate`, `modules `, `plugins`   in it. I do not need the `@nuxtjs/bootstrap-vue` now, I refused it because of this error, but now I want to use the [vue-social-sharing plugin](https://nicolasbeauvais.github.io/vue-social-sharing/). And I take [advice](https://github.com/nicolasbeauvais/vue-social-sharing/issues/26). 


```
module.exports = {
    loading: '~/components/loading.vue',
    head: {
        meta: [
            {charset: 'utf-8'},
            {'http-equiv': 'X-UA-Compatible', content: 'IE=edge'}
        ]
    },
    plugins: ['plugins/social.js'],
//     build: {
//         extractCSS: true,
//         vendor: ['axios']
//     },
//     generate: {
//         minify: {
//             collapseWhitespace: false
//         }
//     },
//
//     modules: [
//         // Or if you have custom bootstrap CSS...
//         ['@nuxtjs/bootstrap-vue', { css: false }]
//     ]
//
};
```

And have error
`This dependency was not found:

* nuxt_plugin_social_75d82285 in ./.nuxt/index.js

To install it, you can run: npm install --save nuxt_plugin_social_75d82285
`

**Comment by clarkdo** [comment]
use ~/plugins/...

**Comment by Jussiadev** [comment]
@clarkdo, It's didn't helped :(
```
This dependency was not found:

* nuxt_plugin_social_59890973 in ./.nuxt/index.js

To install it, you can run: npm install --save nuxt_plugin_social_59890973
```

**Comment by clarkdo** [comment]
Please provide a repo so that I can clearly understand the cause of the problem

**Comment by Jussiadev** [comment]
@clarkdo, thank's I found my error:)

**Comment by martinrisseeuw** [comment]
@Jussiadev How did you solve this error?

**Comment by Jussiadev** [comment]
@martinrisseeuw Yes, my file names were not the same
