### ISSUE TITLE
Latest Vue version update crashes my nuxt app

### ISSUE THREAD

**Issue by jroxendal** [nuxt/nuxt.js#2385]
The recent upgrade to vue 2.5.10 causes hydration errors in my app (commit [4cf855](https://github.com/nuxt/nuxt.js/commit/4cf855ce8115fb17447f2b69fa312237642bbef5)):

`The client-side rendered virtual DOM tree is not matching server-rendered content.`

The error is:
```
[nuxt] Error while initializing app TypeError: Cannot read property 'toLowerCase' of undefined
at emptyNodeAt (vue.runtime.esm.js?ff9b:5127)
...
```

It seems that `nodeOps.tagName(elm)` is `undefined`, and that `elm` (if chrome devtools is to be believed) is an empty comment node here:

```
<div id="__nuxt">
  <div class="nuxt-progress" style="width:0%;height:2px;background-color:#0275d8;opacity:0;"></div>
  <!---->
</div>
```

Any idea what's going on?

**Comment by Imanullah** [comment]
See this 
https://github.com/nuxt/nuxt.js/issues/1851#issuecomment-336948759
I have tried it doesnt work 

There are a lot of important to update as soon Vue 2.5 
latest Vuetify request Vue 2.5 above 

I hope NUXT will not be die there is too long update..  now is still RC11

**Comment by jroxendal** [comment]
After much debugging I tracked the problem to a dependency error :( It seems that and old version of vue-template-compiler was being used that I didn't notice because I was using nuxt through npm link. So take this as a warning that npm link can cause hard-to-debug errors...

**Comment by y284663247** [comment]
npm run dev,
the error message :
/Users/zhiyuan/Project/nodejs/nuxt/sooc/node_modules/nuxt/lib/common/utils.js:25
exports.waitFor = async function waitFor(ms) {
                        ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zhiyuan/Project/nodejs/nuxt/sooc/node_modules/nuxt/lib/common/index.js:1:77)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sooc@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sooc@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by acrolink** [comment]
What is the solution?

**Comment by pi0** [comment]
Upgrading node to 8.x or 9.x
