### ISSUE TITLE
Global component that exists app wide regardless of layout

### ISSUE THREAD

**Issue by jamesAtcodeninja** [nuxt/nuxt.js#2387]
Is there a way to mount a global component that will exists app wide regardless of layout change? 

Use case is a notifications component, and the issue is that the notifications disappear once the layout changes.

**Comment by unr** [comment]
You want to create a [Vue Plugin](https://vuejs.org/v2/guide/plugins.html) and [inject it into your nuxt app](https://nuxtjs.org/guide/plugins#vue-plugins).
