### ISSUE TITLE
In 'head(){}' can't use the data  which  get the dynamic request

### ISSUE THREAD

**Issue by hello-guoguo** [nuxt/nuxt.js#2388]
## **My code as follow:**
```
<script>
  // import axios from 'axios'
  var rapaxios = require('rap-axios-plugin')
  export default {
    data () {
      return {
        title: 'test',
        staticD: { // 静态数据
          wait: false,
          fade: ''
        },
        dynamicD: { // 动态请求数据后覆盖此处的默认数据
          'curpath': '/',
          'gotopimg': '/img/i-top.png',
          'logosrc': '/img/logo.png',
          'nav': [
            { 'curpath': '/', 'txt': '首页' },
            { 'curpath': '/cases', 'txt': '案例' },
            { 'curpath': '/designers', 'txt': '设计师' },
            { 'curpath': '/properties', 'txt': '热装楼盘' },
            { 'curpath': '/constructions', 'txt': '在施工地' },
            { 'curpath': '/embodiments', 'txt': '别墅实施' },
            { 'curpath': '/furnishings', 'txt': '别墅软装' },
            { 'curpath': '/villas', 'txt': '出版刊物' },
            { 'curpath': '/about', 'txt': '关于' }
          ],
          'rootdir': '/',
          'tel': '400-001-5821',
          'telimg': '/img/tel.png'
        }
      }
    },
    head () {
      return {
        title: this.title
        meta: this.statsCode.meta
        // link: [],
        // script: this.statsCode
      }
    },
    created () {
      // console.log(this)
      this.fetchData()
      // this.pathfn() // 渲染dom前调用导航定位(异步在这写不起作用,写在fetchData方法里面)
    },
    methods: {
      fetchData: function () {
        console.log('开始请求数据......')
        let that = this
        // 配置projectId，使用前最好先配置config
        rapaxios.config({
          rootUrl: 'http://rap.taobao.org',
          mock: 'mockjsdata',
          projectId: '30077',
          ismock: false
        })
        rapaxios
          .get('api/default')
          .then(function (res) {
            that.dynamicD = res.data
            console.log(res.data)
            that.pathfn() // 渲染dom前调用导航定位
            console.log('请求数据完成......')
          })
          .catch(function (err) {
            console.log(err)
          })
      }
    }
  }
</script>
```
### **and it's error,**
`TypeError: Cannot read property 'meta' of undefined`
`    at VueComponent.head (default.vue:77)`
## who can help me,please!

**Comment by clarkdo** [comment]
Try to use `fetch` or `asyncData` to fetch the statsCode.

**Comment by hello-guoguo** [comment]
@clarkdo it still not work

**Comment by clarkdo** [comment]
Please provide a reproducible repo.

**Comment by hello-guoguo** [comment]
@clarkdo 
  [https://gitlab.com/hello-guoguo/nuxt-demo.git](url)

**Comment by clarkdo** [comment]
I your codes, `ap-global-proxy` is a none-ssr plugin, but `created` will be executed in `ssr`, so `this.axios` is undefined.

You can move fetchData to `mounted` or also proxy requests in server side.

**Comment by hello-guoguo** [comment]
@clarkdo I want head() work,
```
   head () {
      return {
        meta: this.dynamicD.statsCode.meta
      }
    },
```
so,It has to get data first, then render dom.
if move fetchData to mounted,in head cannot use data

**Comment by clarkdo** [comment]
Then you should also proxy requests in server side.

The axios plugin you are using not support ssr.

**Comment by clarkdo** [comment]
Or use `process.server` to exclude ssr axios calling.

```js
 async created () {
      if (!process.server) {
        await this.fetchData()
      }
}
```

**Comment by hello-guoguo** [comment]
that is to say,the reason is the 'rap-global-proxy'???
So, do you know which plugin support ssr ?

**Comment by clarkdo** [comment]
Let us summarize you issue.

1. You want to use `meta` which is dynamic data.
2. And you used a `ssr:false` `axios` plugin to fetch data.
3. `head` is for generating page meta in ssr.

So you are using a browser-only plugin to load data in ssr, that's incompatible.

If you want make ssr and meta working, `axios` supports brower and node by nature, so you should use a compatible proxy plugin such as [nuxt proxy](https://github.com/nuxt-community/modules/tree/master/packages/proxy), because `rap-global-proxy` based on `XMLHttpRequest` which is not supported in node.js runtime.

**Comment by hello-guoguo** [comment]
soga,  
Thank you sincerely!
I try it

**Comment by clarkdo** [comment]
客气, 感谢你对Nuxt.js的支持.

**Comment by hello-guoguo** [comment]
@clarkdo 
I'm so sorry to trouble you again.
Now I use `'@nuxtjs/axios','@nuxtjs/proxy'`,and through asyncData() to get data,but data() cannot update.I don't know the reason,would you please help me?
repo: https://gitlab.com/hello-guoguo/nuxt-demo.git
