### ISSUE TITLE
Big gods, how do you configure Axios in the nuxt?(大神们,怎么在nuxt中全局配置axios啊?)

### ISSUE THREAD

**Issue by hello-guoguo** [nuxt/nuxt.js#2389]
# For example, ask for teaching!(如题,求教!)

**Comment by hello-guoguo** [comment]
## **是在.nuxt目录下面的index.js中配置么???**
```
--.nuxt
   --index.js
```
```
import axios from 'axios'
Vue.prototype.$http = axios
axios.defaults.baseURL = host
axios.defaults.headers['Content-Type'] = 'application/x-www-form-urlencoded'
axios.defaults.headers['XPS-Version'] = '1.0.0'
```
## **这样对不对啊?**

**Comment by hello-guoguo** [comment]
# 亲测,这样是对的,但是每次重新npm run dev的时候就会重新生成这个index.js把原来的覆盖掉,这个问题怎么解决呢?我估计是在nuxt.config.js里配置,但不知道怎么配,我在研究下

**Comment by pi0** [comment]
Hi sir. Please take a look at this module for axios integration: https://github.com/nuxt-community/axios-module

**Comment by hello-guoguo** [comment]
@pi0 

Thank you sincerely!
