### ISSUE TITLE
repeated requests for favicon.ico

### ISSUE THREAD

**Issue by app-sparkler** [nuxt/nuxt.js#239]
Hi,

Though the `favicon.ico` file is in `static` folder and the `nuxt.config.js` file has the following configuration : 
```
...
link: [
      { rel: 'icon', type: 'image/x-icon', href: 'favicon.ico' }
    ]
...
```
i'm facing the following issue:  

![favicon - request](https://cloud.githubusercontent.com/assets/12084821/22853535/d99f6704-f07e-11e6-9b96-c75a1e2c8cd6.png)

I also get an error in Chrome's console : 
`Failed to load resource: the server responded with a status of 404 (Not Found)` for `http://localhost:3000/stories/show/favicon.ico`

Please suggest, what I need to do to avoid repeated requests to the `server` for `favicon.io`

Thanks.

**Comment by Atinux** [comment]
Hi @app-sparkler 

This request is made from Chrome automatically.

Do you have `router.base` option configured in your `nuxt.config.js`?

**Comment by app-sparkler** [comment]
Hi @Atinux 

i had to define the `linkActiveClass` so i had to add the `router` to `configuration`.  This must have _overridden_ the `default settings`.  I have altered it now, and this is how it looks :

```
// ROUTER CONFIGURATION
  router: {
    linkActiveClass: 'active',
    base: '/'
  }
```

The error on `favicon request` have stopped in `Chrome`; however, the requests are still being made for `favicon.ico`.  This doesn't happen if `Firefox` so i think its not `nuxt` specific but a browser thing.

**Comment by app-sparkler** [comment]
Reference : https://github.com/nuxt/nuxt.js/issues/252

It also requires '/` before `favicon.ico`, so this may be required in the `nuxt/starter` :

`{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }`

### Currently it is :
`{ rel: 'icon', type: 'image/x-icon', href: 'favicon.ico' }`

@a

**Comment by kelleysy** [comment]
this is still happening for me even though I added a `router.base` & a `router.linkActiveClass`
the favicon appears in `Firefox` for me but not `Chrome`...any guesses why?

**Comment by appsparkler** [comment]
hi @kelleysy ,

[NUXT ROUTER](https://nuxtjs.org/api/configuration-router#the-router-property)

This link might help you with a solution. 

Good Luck...
