### ISSUE TITLE
How to make a specific page rendered for a subdomain when using with express?

### ISSUE THREAD

**Issue by hvaoc** [nuxt/nuxt.js#2390]
I am using Nuxt with Express. 

Out of the box, pages are translated to routes to the main domain. 

I am trying to use express-subdomain so that I can have some views (ex: pages/blog/**) rendered under blog.domain.com as well as domain.com/blog.

While other files (other than pages/blog/**) continue to be available under the domain.com only.

**Comment by lomholdt** [comment]
Hey hvaoc! I'm in the same situation and trying to accomplish something similar. Have you had any luck yet?

**Comment by hvaoc** [comment]
No, for a moment I kept that on hold. I tried using express-subdomain + express-vue, but couldn't make it work. @danmademe (Owner of express-vue) told me that it should work, but I couldn't make it work. Check this issue - https://github.com/express-vue/express-vue/issues/142

I have my setup sample there. 

It would be great if this support is natively added to Nuxt.

**Comment by lomholdt** [comment]
Thanks @hvaoc ! I got it working using the [nuxtServerInit](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action) action to set the subdomain in the store. Then I set a `isSubdomain` and use that throughout the application to render different components based on the subdomain. I'm not using express though.

**Comment by hvaoc** [comment]
Do you have a git repo that I can see ? If not do you mind sharing how you did.
