### ISSUE TITLE
Video element - cached element

### ISSUE THREAD

**Issue by nicoladl** [nuxt/nuxt.js#2391]
Hi guys I'm a little bit confused about a video element.
My project consist in a main video page. I should be able to play and pause the video to show some extra  informations, but when I change route and I come back to the main page, the one with the video, the video gets "duplicated". You can notice it from the overlayed audio: one from the from the cue point when I paused before changing page, and the other is from the video begin.
It's like the first element is cached by the browser.

How I can reinit video element when I come back to main page? Or, how can I avoid this "cached video behaviour"?

Video element markup:
`<video class="video" playsinline preload="auto" src="~/assets/url/to/video"></video>`

Video is stored in a variable in mounted hook like this:
`var mainVideo = document.querySelectorAll('.video')[0]`

I've tried some tricky solutions but i can't get away with it. Any ideas?

**Comment by nicoladl** [comment]
I solved in a tricky way with some javascript

**Comment by nallown** [comment]
I have the same problem as well, can you please how you fixed it.

**Comment by nicoladl** [comment]
I re-init the variable before play the video.
Something like that:

`
mainVideo = document.querySelectorAll('.video')[0]
mainVideo.play()
`

**Comment by nallown** [comment]
I see, I don't really like that solution, it feels like a bad hack but thank you for telling me anyway. I'm going to try and find another way I can maybe solve it.

**Comment by nicoladl** [comment]
Let me know if you will find another solution

**Comment by nallown** [comment]
Can you reproduce this problem on your local production build or does it only happen on a hosted server?

**Comment by nicoladl** [comment]
Both environment

**Comment by nallown** [comment]
Can you invite me into the repo? With me, I can only replicate it on my hosted server and not locally. I want to see if its the same with your repo @nicoladl.

**Comment by nicoladl** [comment]
I can't because is a business repo.
I can share the url of the project https://charlyzenger.ch/en/

**Comment by nallown** [comment]
I have to run off now, got to catch the train. I created that issue, hopefully we'll get a better answer on how to solve it. I'll talk in a bit.

**Comment by nallown** [comment]
I fixed it by adding a unique ID to my video player and placing it ID inside a `data` tag for my `video` element. Whenever I call the `play()` method on my video player, I query select all my `video` elements and check if the ID of the current video player matches any of the video elements ID.

So I did something like this:
```html
<template>
  <div>
    <div class="controls">
      <!-- my custom video player controls go here -->
    </div>

    <!-- I added the "id" property as a data using normal HTML5 -->
    <video :data-id="id" @loadedmetadata="startAutoplay()"/>
  </div>
</template>

<script>
export class {
  data: {
    return { id: null };
  },

  created() {
    this.id = randomString();
  },

  getAllVideos() {
    return document.querySelectorAll('video');
  },

  isMounted() {
    return !!this.getAllVideos().find(video => video.dataset.id === this.id);
  },

  startAutoplay() {
    if (this.isMounted() {
      this.$refs.media.play();
    }
  }
}
</script>
```
