### ISSUE TITLE
Injection "elFormItem" not found

### ISSUE THREAD

**Issue by jweboy** [nuxt/nuxt.js#2393]
I used nuxt with elemment-ui to develop.
> nuxt@1.0.0-rc11 
> element-ui@2.0.8

When I use elemnt table, I got some warning => **Injection "elFormItem" not found**
How to fix this problem?

**Comment by henyuan** [comment]
element-ui@2.0.8 依赖于vue@2.5.3,你可以使用
```base
npm i nuxt@next
```
来获取最新版本的 nuxtjs.
最新版本 nuxtjs 会更新 vue 版本,可以解决这个报错.
但最新版本可能会有一些问题,我目前使用中没有发现问题

**Comment by Mopecat** [comment]
@henyuan 我试了你的方法 仍然报这个警告

**Comment by 13653389794** [comment]
我试过了没有问题cnpm i nuxt@next --save 重新建,不要用template/starter

**Comment by Mopecat** [comment]
@13653389794 重新建一个项目？

**Comment by 13653389794** [comment]
我也是遇到了同样的问题
https://github.com/13653389794/nuxt-express 这个是element的 和express的
https://github.com/13653389794/nuxt-default 这个是element 没有express的

**Comment by Mopecat** [comment]
@13653389794 我刚才用你的那个没有express的试了一下仍然会报错

**Comment by 13653389794** [comment]
不可能啊你加我q吧470539167

**Comment by jweboy** [comment]
@henyuan 多谢 已解决～

**Comment by dingyiming** [comment]
不要用template/starter 吗？

**Comment by gongxianmin** [comment]
为什么我执行了npm i nuxt@next --save命令以后编译报
`exports.waitFor = async function waitFor(ms) {
                        ^^^^^^^^
  SyntaxError: Unexpected token function

  - module.js:20 require
    internal/module.js:20:19

  - index.js:1 Object.<anonymous>
    [nuxt-start]/[nuxt]/lib/common/index.js:1:77`

**Comment by kaungmyatlwin** [comment]
@gongxianmin That's because your current Node version is < 8.

Official docs stated that you should have at least Node >= 8.0.0 to support async/await.
