### ISSUE TITLE
node 6 - nuxt@next - build fails with SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#2395]
Since the last nuxt@next (1.0.0-gh-3ec8f14), I'm not able to build nuxt anymore with Node Version 6. I saw a commit regarding node 8, so is node 6 officialy not longer supported? Not even for the build process?

```
# nuxt build --universal && backpack build
output /source/node_modules/nuxt/lib/common/utils.js:25
output exports.waitFor = async function waitFor(ms) {
output ^^^^^^^^
output SyntaxError: Unexpected token function
output - module.js:20 require
output internal/module.js:20:19
output - index.js:1 Object.<anonymous>
output [source]/[nuxt]/lib/common/index.js:1:77
```

Thanks
Simon

**Comment by pi0** [comment]
Hi. And thanks again for your early testings. Yes. Is there any reason blocking you to upgrade node 8.0.0? We forced for this decision for many internal perf improvements. the most important is native async/awaits.

**Comment by simllll** [comment]
Well ;) the problem is actually just my deployment pipeline is not supporting node 6 right now. At least not out of the box. Servers are running already on node 8.

Is there a way to include a babel transpile to support node 6 just for the build process? Or is this even more effort than upgrading my deployment pipeline? ;)

thanks for your quick replies!

Simon

**Comment by pi0** [comment]
If you can upgrade everything to 8.x that would be much better.  Can i ask which pipeline do you use for build ?

**Comment by simllll** [comment]
I'm using https://deploybot.com/ .. not very satisfied anyways, should take this as a sign an move on ;)
If you have any recommendations, just let me know.

Thanks though, closing this for now.

**Comment by mesqueeb** [comment]
Google cloud functions also not compatible with node 8.x yet:
https://cloud.google.com/functions/docs/release-notes

This makes firebase cloud functions fail bad also...

**Comment by pi0** [comment]
The latest build of nuxt-edge supports Node 6.x again by automatically falling back to the legacy build.

![image](https://user-images.githubusercontent.com/5158436/40841216-f18bd594-65be-11e8-8ab0-113d27a544d7.png)

PS: Don't forget to add `babel-polyfill` dependency to your project if you need legacy build.
