### ISSUE TITLE
about  vuex state problems

### ISSUE THREAD

**Issue by luke-Yang** [nuxt/nuxt.js#2397]
I  use 'nuxtServerInit' to  set datault use info ,  when two user login, and They refresh the page at the same time，I can see the other person's message，how to fix this bug ,please help me ,thx.

**Comment by clarkdo** [comment]
Can you please provide a repo which can reproduce the issue ?

**Comment by kenshin1983** [comment]
I think you need reset your state when nuxtServerInit before, because Vuex in server side is global for all clients
