### ISSUE TITLE
npm run build ,which will result in my site being unable to access the resources.

### ISSUE THREAD

**Issue by 912380760** [nuxt/nuxt.js#2399]
After the project is deployed to the server, update the project npm run build, which will result in my site being unable to access the resources.
What's the solution, please

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2084">#c2084</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. Please provide more details, like a link to your project and entire console logs for prod build :)
