### ISSUE TITLE
Working with Request Params

### ISSUE THREAD

**Issue by bernardocs** [nuxt/nuxt.js#24]
Hey guys... it's me (again)... 😆 

I've been wondering on how do I, for example, receive a JSON from a POST request and put it on the request chain, in a way that I can access via some Vue component.

Is that possible?

**Comment by Atinux** [comment]
Hi @bernardocs 

You can use [express](https://github.com/expressjs/express) to create your server and use Nuxt.js to render the routes, this way, you can include the [body-parser](https://github.com/expressjs/body-parser) module to let you handle POST request for you application.

Then, you will be able to access `req.body` from the server-side in your `data` method.

Example: https://hyperdev.com/#!/project/nuxt-body-params
Live demo: https://nuxt-body-params.hyperdev.space/

You can also call the url with Postman for example and a JSON object:

![Imgur](http://i.imgur.com/EqifSBW.png)

**Comment by david-j-davis** [comment]
@Atinux is this still the preferred method that you suggest to handle post requests?

**Comment by Atinux** [comment]
@david-j-davis you can also use [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware#the-servermiddleware-property)
