### ISSUE TITLE
Issue with GA experiments

### ISSUE THREAD

**Issue by anotheri** [nuxt/nuxt.js#2401]
Hey there!
Could you please provide some help of implementing Google Analytics Experiment (A/B testing):
the main problems i've faced with are:
- how to put *inline* script right after the opening `<head>` tag on a certain page?
- and one described here: https://github.com/declandewet/vue-meta/issues/174;
- tried to use `@nuxtjs/google-analytics` module but it seems it doesn't provide any help with GA experiments, so no success either.

**Comment by awronski** [comment]
Hi!

I was doing experiments with ```@nuxtjs/google-analytics": "^1.0.0"```
Unfortunately the [GA](https://github.com/nuxt-community/google-analytics) module was removed.

I don't know if the [new one](https://github.com/nuxt-community/analytics-module) has this function.


I was doing experiment with showing some of the components only to the half of the visitors.

Page:
```html
<some-component v-if="expVarId === 1"/>
```

```js
  export default {

    analytics (from, to, store) {
      return { expId: 'XXXX', expVar: store.getters.expVarId }
    },
    computed: {
      ...mapGetters(['expVarId'])
    }
```

Store:
```js
  getters: {
    expVarId: state => state.visitorId % 2
  },
```
