### ISSUE TITLE
 vue-cli · Failed to download repo vuejs-templates/nuxt-community: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by haoxl3** [nuxt/nuxt.js#2402]
when I init a nuxt project, I run the command "vue init nuxt-community parking", I have a error that vue-cli · Failed to download repo vuejs-templates/nuxt-community: Response code 404 (Not Found)
my vue version is 2.9.2,  
node version is v6.11.3, 
webpack version is 3.10.0

then, How do I initialize a nuxt project ?

**Comment by 13653389794** [comment]
你在哪看到的库，根本就没有这个

**Comment by Yawn2323** [comment]
Failed to download repo vuejs-templates/nuxt-community: Response code 404 (Not Found) what is the solution?
