### ISSUE TITLE
A lot of repeating code in nuxt build pages

### ISSUE THREAD

**Issue by Kasheftin** [nuxt/nuxt.js#2404]
I don't know if that's the issue or it's my misunderstanding of how this all works. When I run nuxt build --analyze, I get the following picture: 
![screenshot from 2017-12-15 12-44-55](https://user-images.githubusercontent.com/379267/34038750-15bb7eea-e196-11e7-80f4-cc30551c40c3.png)
I see there a lot of pages, and many of them contain the same jquery library (and some other as well). Is it necessary to include jquery into the every page file? 
Assume it's for server rendering (like rendering the page has to use the complete bundle of that page). But then, when I open any page in the browser, I see the following requests: 
![screenshot from 2017-12-15 12-51-21](https://user-images.githubusercontent.com/379267/34039028-d06d11f4-e196-11e7-9ee8-14e307b4acff.png)
It seems that all pages files are loaded for any request. 
Why so?
If the system requires to load every page js file, then why there's no single bundle file for the front end that contains everything without repeating libraries? 
If it's incremental, then why the front end requests all the pages?

**Comment by clarkdo** [comment]
You should add common libs such as `jQuery` to `vendor`: https://nuxtjs.org/api/configuration-build#vendor
