### ISSUE TITLE
How to update vue-template-compiler

### ISSUE THREAD

**Issue by feedgit** [nuxt/nuxt.js#2406]
I installed Nuxt and this current version of **vue-template-compiler** package is `vue-template-compiler@2.4.4`. But in this file: https://github.com/nuxt/nuxt.js/blob/dev/package.json is version 2.5.11. When I update using npm install it came to error mismatch with `vue@2.4.4` too. I cant update two packages. Please help me!!

**Comment by clarkdo** [comment]
Nuxt with `Vue 2.5.11` still don't release yet (only available in `next` which is an unstable version), if you are using `1.0.0-rc11` and there are other libs using `2.5.11`, you should specify to use `vue@2.4.4`, `vue-template-compiler@2.4.4` and `vue-server-renderer@2.4.4` manually.
