### ISSUE TITLE
Access middleware variables from pages

### ISSUE THREAD

**Issue by cyberiaa** [nuxt/nuxt.js#2407]
I'm trying to use middleware output in pages without Vuex.
It seems inject is not available here and none of following work.

My middleware:
```
export default function (context) {
     console.log('middle ware')
     return axios.get('http://localhost:3000/api/test').then((res) => {
          //none of these work:
          context.my_var = res.data 
          inject('my_var', res.data) 
          return ({my_var: res.data})      
 })
```

Any idea?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2091">#c2091</a>)</em></sub></div>

**Comment by cyberiaa** [comment]
I don't know if this is a bug or not implemented by design. But I think this is pretty useful for many use cases. For instance, getting common data for common pages or for a layout.

**Comment by silverbackdan** [comment]
I'm not sure but perhaps you could create a plugin?
```js
export default (ctx, inject) => {
  ctx.$getPage = (payload) => {
    return fetchPage(ctx, payload)
  }
  inject('getPage', ctx.$getPage)
}
```

I think the plugin would be exposed in middleware. I'd take a look at @nuxtjs/axios plugin for example to see how that is made available in middleware and to provide a guide. https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.template.js

**Comment by yoyo837** [comment]
The same.  @silverbackdan  I will try your advice.

**Comment by yoyo837** [comment]
It's not work like you said.
