### ISSUE TITLE
Emoji-mart-vue component - document is not defined

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#2408]
I tried to use this [emoji-mart-vue](https://github.com/jm-david/emoji-mart-vue) but of course I get ```document is not defined```.

Anyone has idea how to fix it or can recommend some other emoji component that works with nuxt?

Thanks in advance,

**Comment by clarkdo** [comment]
Please have a look at : 
https://nuxtjs.org/faq/window-document-undefined
https://github.com/nuxt/nuxt.js/issues/2345#issuecomment-350202002

**Comment by awronski** [comment]
@clarkdo Hi! I know the trick with the required. But what to do if I need to use a external component?
And the external component is using the window? I am not the owner of this code.

If I understand correctly I cannot use required because in the template the import will be missing for the component?

**Comment by pi0** [comment]
Unfortunately, i didn't find time to make a PR for fixing for upstream, and the real problem is with packaging. Here is an almost working version for SSR:

```vue
<template>
<div>
    <no-ssr>
      <picker set="emojione"></picker>
    </no-ssr>
</div>
</template>

<script>
import Picker from 'emoji-mart-vue/src/components/picker.vue'

global.EMOJI_DATASOURCE_VERSION = '3.0.0'

export default {
  components: {
    Picker
  }
}
</script>
```

**Comment by awronski** [comment]
@pi0 Thanks for help. I missed that ```<no-ssr>``` was added in v1.0.0-rc7.
