### ISSUE TITLE
Loading indicator and Google crawler

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#2409]
I have a problem with the way google crawler renders my Nuxt SPA website. It just renders the loading indicator and ignores the content.

I don't want to disable the loading animation, but can't find any other option. Are there any other solutions for this?

Thanks in advance

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2095">#c2095</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. Would you please test it using "Fetch as Google" utility and sharing results? BTW Thanks for problem reporting.

**Comment by husayt** [comment]
Here is the screenshot:

![image](https://user-images.githubusercontent.com/1169324/34075436-ff3aad38-e2be-11e7-96e2-d9e7db7f4383.png)

**Comment by hanjeahwan** [comment]
I facing same issue too 🤔

**Comment by christophwolff** [comment]
i think you are running the site in SPA mode. You have to run it in universal (Server Side Rendering) otherwise the google bot wont see any content. The google bot simple cannot render JavaScript

**Comment by iamdubx** [comment]
@husayt how are you showing this indicator?

**Comment by christophwolff** [comment]
@iamdubx he is on spa mode. https://nuxtjs.org/api/configuration-mode/

**Comment by husayt** [comment]
SPAs can be perfectly crawlable. I had an SPA which was nicely indexed for 5 years with hashbang urls using this advice:
https://developers.google.com/webmasters/ajax-crawling/docs/learn-more
http://googlewebmastercentral.blogspot.com/2015/10/deprecating-our-ajax-crawling-scheme.html

But since it has been deprecated I thought to try without it:
http://googlewebmastercentral.blogspot.com/2015/10/deprecating-our-ajax-crawling-scheme.html

But it didn't work and even when i disabled loader I get this:
![image](https://user-images.githubusercontent.com/1169324/34096610-eb2f5766-e3cd-11e7-925b-54b9c6f03993.png)

So I will go back to using hashbang and escaped fragments for now. But SPAs should be indexable too.

**Comment by husayt** [comment]
Here is another useful link on the topic:
https://moz.com/blog/optimizing-angularjs-single-page-applications-googlebot-crawlers

**Comment by husayt** [comment]
Try nuxt-edge, SPA generation has changed there and might fix the problem
for you. I have switched to server based version to solve the problem and
works nicely.

**Comment by Biskor** [comment]
Donc forget. In server based version width generate, first load middleware arent called. U have to create a plugin for routes.

**Comment by galvez** [comment]
Closing this as @husayt worked out his issue by moving to SSR.
