### ISSUE TITLE
Using external scripts?

### ISSUE THREAD

**Issue by antcook** [nuxt/nuxt.js#241]
I'm looking to integrate a custom Stripe payment page into a Nuxt project. In their docs it says to include their library via a script tag in your page head/footer:

`<script type="text/javascript" src="https://js.stripe.com/v2/"></script>`

How would I handle this with Nuxt seen as their docs states that "Stripe.js should always be loaded directly from this URL: https://js.stripe.com/v2/", my first instinct was to just drop a script tag in my default layout template but this doesn't seem to work? 

Is there a way I can do this correctly?

**Comment by Atinux** [comment]
Hi @antcook 

Take a look at https://nuxtjs.org/faq

So can do in your `nuxt.config.js` (or in your layout):
```js
head: {
  script: [
      { src: 'https://js.stripe.com/v2/' }
  ]
}
```

**Comment by antcook** [comment]
Ah, fantastic. Thank you! :)

**Comment by blalockco** [comment]
Can you have multiple  script tags?

**Comment by binggg** [comment]
@Atinux 
Put script in head is not good for loading performance. It will delay first screen time, especially ssr pages.

**Comment by andrade1379** [comment]
How can one add scripts to the footer of a Nuxt project?

**Comment by Atinux** [comment]
Hi @andrade1379 

You can use the `body: true` attribute with the latest version of Nuxt.js, see https://github.com/declandewet/vue-meta#script-object

Example:

```js
{
  head: {
    script: [
      { innerHTML: 'console.log("I am in body");', type: 'text/javascript', body: true }
    ]
  }
}
```

**Comment by Isa79** [comment]
@Atinux Hi, how would you add google adsense?

`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`

```
    script: [
      { src: '//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js' }
    ]
```

but where do you put async?

**Comment by NicoPennec** [comment]
@Isa79  think to look in the resolved  nuxt issues: https://github.com/nuxt/nuxt.js/issues/2437

```js
    script: [
      { src: '//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', async: true }
    ]
```

**Comment by EllenFawkes** [comment]
InnerHTML not works in nuxt 1.3.0. JS is escaped.

```html
<script data-n-head="true" type="text/javascript">if (!self.Promise || !self.WeakSet || !self.Proxy || !Array.prototype.slice || !Object.values) { location.href = &quot;/oldbrowser.html&quot; }</script>
```

```javascript
script: [
      { innerHTML: 'if (self.Promise || !self.WeakSet || !self.Proxy || !Array.prototype.slice || !Object.values) { location.href = \'/oldbrowser.html\' }', type: 'text/javascript' }
    ]
```

**Comment by pi0** [comment]
I also confirm @EllenFawkes :D /cc @Atinux

**Comment by Atinux** [comment]
Hi @EllenFawkes 

This is to avoid XSS attack, it's a feature of [vue-meta](https://github.com/declandewet/vue-meta), if you want to disable the sanitizer, you can use [__dangerouslyDisableSanitizersByTagID](https://github.com/declandewet/vue-meta#__dangerouslydisablesanitizersbytagid-string):

```js
head: {
  script: [
    { hid: 'oldbrowser', innerHTML: 'if (!self.Promise || !self.WeakSet || !self.Proxy || !Array.prototype.slice || !Object.values) { location.href = \'/oldbrowser.html\' }', type: 'text/javascript' }
  ],
  __dangerouslyDisableSanitizersByTagID: {
    oldbrowser: 'innerHTML'
  }
}
```

/cc @pi0
