### ISSUE TITLE
how to redirect page in nuxtServerInit function

### ISSUE THREAD

**Issue by cybibo** [nuxt/nuxt.js#2413]
async  nuxtServerInit({ commit }, { req},{ router }) {
...
if (token) {
     if(req.url == '/login'){
        router.redirect('/')
    }
}

router is not undefind

**Comment by clarkdo** [comment]
Use `redirect`, look similar to:

```js
async nuxtServerInit({ commit }, { req, redirect }) {
  if (token && req.url == '/login') {
    redirect('/')
  }
}
```
