### ISSUE TITLE
Initialising a Plugin based on Vuex state, nuxtServerInit()

### ISSUE THREAD

**Issue by francescobm** [nuxt/nuxt.js#2416]
Hi,

I am creating a custom plugin which instantiation relies on application state set in `nuxtServerInit()` method. 

What happens is the following: 
- In nuxtServerInit() I analyze the req.headers.host and I determine which `country` the request is coming from.
- I commit an action which set `state.lang` to `country` 

Now, at this point I have a custom plugin which simply adds a `$i18n` object to the Vue instance. The object is coming from an headless CMS where I manage my content.

```Javascript
// plugins/i18n.js
export default ({ app, store }, inject) => {
  const I18n = require(`../content/locals${store.state.lang}.js`)
  inject('i18n', I18n)
}

```

I have two problems here: 
1. when the plugin is initialised the nuxtServerInit hasn't run yet, so the content won't be loaded
2. if I try to solve problem one and I define $i18n as an empty object, and then I try to require the translated content from nuxtServerInit() like so: 

```Javascript
// plugins/i18n.js
export default ({ app, store }, inject) => {
  const I18n = {}
  inject('i18n', I18n)
}

```

``` Javascript
// in store/index.js within the nuxtServerInit method
   this.$i18n = require('`../content/locals${store.state.lang}') 
``` 
`this.$i18n` will be filled with my content on the server side, but on the client side it will look like an empty object.

Is there any way to make my plugin init to persist btw server and client side?

**Comment by francescobm** [comment]
Issue related to https://github.com/nuxt/nuxt.js/issues/2386#issuecomment-351620528 for reference

**Comment by jsonberry** [comment]
Have you tried setting the lang via Middleware instead of `nuxtServerInit`?

Also it looks like the `req` exists in the `context` that is passed to plugins, so perhaps it could all be done in the plugin?

The official i18n example uses a mixture of middleware and plugins: https://nuxtjs.org/examples/i18n

**Comment by francescobm** [comment]
Hi @jsonberry thanks for your feedback and sorry for my late reply. 
Ok, I'll check that!

**Comment by husayt** [comment]
Seems this can be closed now
