### ISSUE TITLE
Using data from $store cause glitch page transition on leave

### ISSUE THREAD

**Issue by hackuun** [nuxt/nuxt.js#2418]
If I use data from Vuex, for example

```
{{ $store.state.error }}
```

And while having Page transition, let's say `300ms`, then data in that element changes **before** page transition finished. 
How to wait until page leave transition fired?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2097">#c2097</a>)</em></sub></div>

**Comment by iamdubx** [comment]
Can't believe nobody faced the similar issue. I guess I am missing something very obvious then. Can somebody help please?

**Comment by jsonberry** [comment]
How is `$store.state.error` being set? Are you dispatching a Vuex action?

**Comment by iamdubx** [comment]
@jsonberry thanks for reply. I am using `asyncData`. You think it can cause this issue?

**Comment by jsonberry** [comment]
Can you post what you have in `asyncData`?

It sounds like you might need to use a different lifecycle hook, possibly `mounted()`, or [beforeRouteEnter](https://router.vuejs.org/en/advanced/navigation-guards.html#in-component-guards)

**Comment by evgendev** [comment]
I have the same problem

**Comment by galvez** [comment]
As @jsonberry suggested, this can be fixed by using a different lifecycle event or some other sort of time control, like checking a flag + `setTimeout()`.
