### ISSUE TITLE
Mutations not mutating state

### ISSUE THREAD

**Issue by martijnhiemstra** [nuxt/nuxt.js#2419]
I am writing my own project in Nuxj.js and nearly everything is working. There is 1 thing that isn't working and I'm hoping you can help me.

I am using the Vuex store in Nuxt.js and I have everything setup. I can confirm that my action is called and that the mutation called in the commit works. However if I change anything in the state in the mutation ten the state doesn't change. Here is my action

    import axios from 'axios'
    import * as ACTIONS from './action-types'

    const actions = {
      async [ACTIONS.FETCH_TRAINING_TYPES_ACTION] ({ commit }) {
        let {data} = await axios.get('http://localhost:8080/api/students')

        commit('setStudents', data)
      }
    }

    export default actions

The commit invokes the following mutation

    const mutations = {
      setStudents (state, payload) {
        console.log('1: ' + payload)
        state.students = payload
        console.log('2: ' + state.students)
      }
    }

    export default mutations

The first console log prints the payload which contains the right data so the mutation is invoked properly. The second console log prints the state.students and it prints the right value so the state is updated. However when viewing the vex state in the chrome Vue extension I can see that the state is empty and also if I print the state value state.students it's empty.

It's starting to look like a bug where the state changes aren't persisted or something.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2098">#c2098</a>)</em></sub></div>

**Comment by dohomi** [comment]
@martijnhiemstra are you using vuex modules or do you have everything in one namespace?

**Comment by martijnhiemstra** [comment]
As far as I know I have everything in 1 namespace. How can I tell? 

In the project root I have a directory called store and in the store directory I have a file called index.js

```
import Vuex from 'vuex'

import mutations from './mutations'
import actions from './actions'
import getters from './getters'

const createStore = () => {
  return new Vuex.Store({
    state: {
      trainingTypes: null,
      trainings: null,
      students: null,
      companies: null,
      counter: 0
    },
    getters,
    mutations,
    actions
  })
}

export default createStore

```

As you can see my getters, mutations and actions are in seperate files also in the store directory. Is that okay?

**Comment by dohomi** [comment]
@martijnhiemstra then you don't use the namespaced modules. Did you try to call your mutation out of a component method? Did that work for you? You can check the action calls in the developer toolbar and inspect the payload there. Hope this will lead you to the problem you are facing

**Comment by martijnhiemstra** [comment]
Thanks for the tip. The funny thing about this all is I have another mutation and it works perfectly.

```
increaseCounter: function (state) {
   state.counter++
   state.students = 12
}
```

I goto the Vuex tab and I can see that counter and students is updated in the state. However for some reason my other mutation doesn't update the state even though the property trainingTypes in the state is  updated and I can verify that the state property is updated. This is my component where I do the call to the action:

```
import { mapState } from 'vuex'
import { FETCH_TRAINING_TYPES_ACTION } from '@/store/action-types.js'

export default {
  fetch ({ store }) {
    store.dispatch(FETCH_TRAINING_TYPES_ACTION) // This one doesn't update the state
    store.dispatch('inceaseCounter')  // This 1 does work and update the state
  },
  computed: mapState([
    'trainingTypes',
    'students'
  ])
}
```

**Comment by martijnhiemstra** [comment]
I think I found the issue. If I add a button to the page that looks like this:

   <button v-on:click="$store.dispatch('FETCH_TRAINING_TYPES')">Click me</button>

Then the list is loaded. I think it is a sync issue. When the component is drawn a call is done to the backend using axios. It is executed and the state is updated however because of some really weird syncing issue the state is reverted or the state property change is ignored. Then when I click the button, even though the axios call is async it does get updated. Does this have to do with the fetch property of the component not doing it's job?

**Comment by dohomi** [comment]
@martijnhiemstra dispatch actions of vuex are always running asynchronous. So you would do this in your fetch:
```
  async fetch({store}){
   const data = await store.dispatch('YOUR_API')
   console.log(data) 
  }
```
Don't forget to return the promise inside of your action.

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
