### ISSUE TITLE
How to get request in Vue plugins initialization

### ISSUE THREAD

**Issue by quentinus95** [nuxt/nuxt.js#242]
Is there a way to get the current request during plugins initialization? I need to initialize a translation component which needs the current language (I expect to find it using Accept-Language header and/or current route).

Thanks

**Comment by Atinux** [comment]
Hi @quentinus95 

It's not possible to have the context in the plugin since it's bundled.

But you can use the [middleware](https://nuxtjs.org/guide/routing#middleware) to access the context, in your middleware your can import your plugin and update it.

**Comment by quentinus95** [comment]
Hello, thanks for your answer!

I've updated my nuxt instance and added a middleware. However, it is not really a solution for my issue.

I'm using a VueJS filter to translate my page contents. This filter relies on a JS library to translate the string (i18next).

However, as the first request triggers content rendering on the server, I need to know the user's locale before vue templates are compiled.

Is there a way, using middlewares I guess, to get the request before vue files are rendered on server side?

Thanks
