### ISSUE TITLE
question about "isServer" in builder.js

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#2420]
Hy all,
I was playing around with the babel configuration, and somehow I thought it's a good idea to target the server's webpack with latest node and the "non server"/frontend with ie: 9...

So I did something like this in nuxt.config.js:
```
 babel: {
        presets: function(isServer) {
            return [
                [
                'vue-app', {
                    targets: isServer ? { node: 'current' } : {ie: 9, uglify: true}
                }]
            ];
        }
    }

```
I got this by studying the builder.js file..there is a similar construct:
`targets: isServer ? { node: '8.0.0' } : { ie: 9, uglify: true }`

So far so good, but now my application fails on internet explorer, safari and co.. (let is not allowed,..) looks like the transpile action targets the current node, and not ie 9 for frontend. Everythigng starts working again if i just target ie: 9, indepent of "isServer" flag.

What do I miss here? Is it somehow related to SSR that my iexplorer gets now the "wrong" javascript? Or is the purpose of this "isServer" flag something else and I just misused it?

Thanks
Simon
Ps.: using nuxt 1.0.0-gh-ae754af  (nuxt@next latest)

**Comment by cesasol** [comment]
since this is being built on the server, isServer is always true

**Comment by husayt** [comment]
try babel poyfill
```
 vendor: ["babel-polyfill", "vuetify", ...]
```

**Comment by simllll** [comment]
Just for history:
This was actually a different "bug":
it's not:         
`presets: function(isServer) {`

it is        
` presets: function({isServer}) {`
(watch the brackets ;)). Because the presets functino gets a "object" with a isServer flag and not just a boolean with true or false.

Regards
