### ISSUE TITLE
css extracted to the css file

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#2423]
[I look forward to css extracted to the css file](https://github.com/nuxt/nuxt.js/issues/1533), because of such a use, not recognized in China Baidu seo, or look forward to a method to achieve css extraction, do not need to be embedded in the page css

![image](https://user-images.githubusercontent.com/17898715/34186819-f3876c36-e568-11e7-9eac-40c4e15f6f06.png)
![image](https://user-images.githubusercontent.com/17898715/34186737-81bd3ae0-e568-11e7-9da1-1da5ef2611df.png)
![image](https://user-images.githubusercontent.com/17898715/34186685-38d83b04-e568-11e7-9049-e9a34f601974.png)

**Comment by yuchonghua** [comment]
[There is no solution here](https://github.com/tailwindcss/discuss/issues/24#issuecomment-341679870)
![image](https://user-images.githubusercontent.com/17898715/34187185-185ead74-e56b-11e7-8715-0d9890c0df1f.png)

**Comment by HadiChen** [comment]
This problem is very serious

**Comment by Iceygirl** [comment]
My project is also plagued by this problem, looking forward to get resolved as soon as possible

**Comment by Atinux** [comment]
Ping @clarkdo

**Comment by clarkdo** [comment]
`ExtractTextPlugin` has been configurable in `nuxt.config.js` which will be included in next release.

```js
module.exports = {
  build: {
    extractCSS: {
      allChunks: true
    }
  }
}
``

For a quick fix, you may config `ExtractTextPlugin` through `build.extend`

```js
module.exports = {
  build: {
    extractCSS: true,
    extend(config, options) {
      const extract = config.plugins.find(plugin => plugin.renderExtractedChunk)
      extract.options.allChunks = true
    }
  }
}
```

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/34186819-f3876c36-e568-11e7-9eac-40c4e15f6f06.png)
Nuxt I use is indeed the latest, is a direct github installation, but still can not use the following configuration ah! !
```js
module.exports = {
  build: {
    extractCSS: {
      allChunks: true
    }
  }
}
```
Ping @clarkdo

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/34237460-c19d26b4-e637-11e7-896c-4259cff9cef6.png)
![image](https://user-images.githubusercontent.com/17898715/34237468-cc672478-e637-11e7-897b-478301cbfc81.png)
The problem is not solved
Ping @clarkdo

**Comment by clarkdo** [comment]
Did you run the service by `dev` or `build and start` ?

I have tried by `yarn build`, the bundle files seemed work.

**Comment by yuchonghua** [comment]
```shell

npm run dev

```

**Comment by clarkdo** [comment]
For `dev`, I think because `ExtractTextPlugin` doesn't work well with `HMR`, so @pi0 has commented it.

**Comment by yuchonghua** [comment]
Well, understood, thank you very much, only build can be fine

**Comment by clarkdo** [comment]
I opened a pr to fix the `HMR` issue in `ExtractTextPlugin ` and enable the plugin.

**Comment by hankanon** [comment]
perfect very helpful to me！

**Comment by willin** [comment]
then how to fix this?

**Comment by blissjaspis** [comment]
@willin this was fixed, and you just just adding `extractCSS: true` to your `nuxt.config.js`

and `run npm build` then `npm run start`. after that open the page_source to see that.
