### ISSUE TITLE
Problem with pixi.js and nuxt

### ISSUE THREAD

**Issue by mcpll** [nuxt/nuxt.js#2424]
Hi,
I make a simple vue component into components folder of nuxt that use pixi js for some graphics effect.
I used this component into default.vue layout and for now all ok.
But now when i Split code in some simple es6 class that extends pixi.js class when i use One of this into my vue component receive Cannot read property middlewere of undefined, i think Is a sometjing similari to ssr problem becouse pixi use dom, but my component Is wrapper by a nossr tag and into my nuxt.config.js Is set ssr false for pixi.js module

Witch Is my mistake?

**Comment by mcpll** [comment]
this is my github repo
https://github.com/mcpll/mononuxt

**Comment by cesasol** [comment]
Try to execute your init function after checking for ssr `if (process.client) { this.init() }`

**Comment by CMarzin** [comment]
Thanks @mcpll I applied your way and its working !

`nuxt.config.js`
```
  plugins: [
    {
      src: '~/plugins/pixi',
      ssr: false
    }
  ],
```
`pixi.js` inside plugin folder
```
import * as PIXI from 'pixi.js'

export default PIXI
```
And after you can use PIXI anywhere with the annotation
`/* global PIXI */`
