### ISSUE TITLE
contributing.md out of date?

### ISSUE THREAD

**Issue by jroxendal** [nuxt/nuxt.js#2425]
I'm trying to figure out how to build this repo in the dev branch. It seems the `build` and `watch` scripts have been removed from package.json. Is building no longer necessary? What should I run after a `git pull`? just `npm install`?

An update of contributing.md seems necessary.

**Comment by pi0** [comment]
Hey. Yes there is no longer any build step necessary. Just ensure node version is above 8.0.0 👻

**Comment by pi0** [comment]
Also PR welcome for updating contribution docs. Thanks for pointing to this.
