### ISSUE TITLE
nuxt发布生产环境后,大概首页加载有1.2m大,请问该如何优化文件大小

### ISSUE THREAD

**Issue by issmile** [nuxt/nuxt.js#2426]
![image](https://user-images.githubusercontent.com/20268011/34202715-96d6ed7c-e5b3-11e7-9023-cb176f9680ec.png)
如图,这应该怎么优化呢?
![image](https://user-images.githubusercontent.com/20268011/34202949-56e32b08-e5b4-11e7-9f4d-c1412be8632c.png)
![image](https://user-images.githubusercontent.com/20268011/34202957-680065d6-e5b4-11e7-9a35-0bf7bafca6b4.png)
地址http://miaoditao.cn/

**Comment by clarkdo** [comment]
可以看下首页`HTML`中的`head`部分, 其实大部分js, 例如:`20.nuxt.bundle`等, 都是`prefetch`类型的.

浏览器会提取这些`prefetch`信息，把这些请求排到队列内，然后浏览器空闲时将对这些请求进行预取, 所以其实大部分的js是也为了后续页面优化使用的, 并且不影响首页加载。

如果你想禁用这个优化项, 请参考: https://nuxtjs.org/api/configuration-render#resourcehints
