### ISSUE TITLE
server.js :#126 swallows third party errors during server side rendering

### ISSUE THREAD

**Issue by toadkicker** [nuxt/nuxt.js#2427]
Symptom:

Developer installs a new plugin, module, etc via package manager and configures nuxt.config.js to include it. Then on page request nuxt throws ` Cannot read property 'middleware' of undefined `  on server.js L#126:15. This is because the `layout` variable is undefined.

```
// Set layout
  let layout = Components.length ? Components[0].options.layout : NuxtError.layout
  if (typeof layout === 'function') layout = layout(ctx)
  await _app.loadLayout(layout)
  layout = _app.setLayout(layout)
  // ...Set layout to __NUXT__
  context.nuxt.layout = _app.layoutName

  // Call middleware (layout + pages)
  if (!context.nuxt.error) {
    midd = []
    if (layout && layout.middleware) midd = midd.concat(layout.middleware)
```

I'm not totally familiar with the internals here, but I did simply add

```
    if (layout && layout.middleware) midd = midd.concat(layout.middleware)
```

which then surfaced my real error when my error.vue layout rendered. I suspect this isn't the exact behavior the nuxt team expects in this use case, but at least I could troubleshoot my error. In my particular case I updated to FontAwesome 5 and its not very friendly to SSR. FontAwesome is throwing `Cannot read property 'doScroll' of undefined` trying to look for window on the server side. 😢 

Regardless, it's probably a good idea to check that `layout` variable is set here, or if another approach is suggested I'm happy to test and submit a PR with that feedback.

Thanks!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2106">#c2106</a>)</em></sub></div>

**Comment by Atinux** [comment]
Could you explain us what is your setup of Font Awesome 5 with Nuxt.js?

**Comment by toadkicker** [comment]
~/plugins/fontawesome.js:

```
import fontawesome from '@fortawesome/fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import solids from '@fortawesome/fontawesome-pro-solid'
import regular from '@fortawesome/fontawesome-pro-regular'
import light from '@fortawesome/fontawesome-pro-light'
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import Vue from 'vue'

fontawesome.library.add(
  brands, solids, regular, light
)

Vue.use(FontAwesomeIcon)

Vue.component('font-awesome-icon', FontAwesomeIcon)

export default fontawesome
```

nuxt.config.js:

```
{
  plugins: [
      {src: '~/plugins/fontawesome', ssr: false},
  ]
}
```

**Comment by rlam3** [comment]
@toadkicker Were you able to resolve your problem? I'm having a difficult time with nuxt integrating font plugins and modules as well... Would love your input of a working example too. Did you use any modules like the following: 

https://github.com/Qonfucius/nuxt-fontawesome
https://github.com/vaso2/nuxt-fontawesome

**Comment by toadkicker** [comment]
I was not able to resolve it. I actually just gave up on Nuxt for our project.

**Comment by galvez** [comment]
Closing this as there's been no updates over 90 days. Seems like one of many cases where specialized configuration might be required. I'll try and retest this post-2.0.

**Comment by toadkicker** [comment]
For the record I think this happened because of 'export default fontawesome' causing the undefined to occur, I've since revisited giving up on nuxt and am using it in production in several apps.

**Comment by galvez** [comment]
Glad to hear @toadkicker 👍
