### ISSUE TITLE
Help wanted: Possible to get child depth in asyncData?

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#2429]
I can see in VueRouter that you can get the view depth with:
`this.$vnode.data.routerViewDepth`

I can also see that the `nuxt-child` appears to send some data to `router-view` which include nuxtChildDepth

I'm look to get this depth out in the asyncData function - would this be possible? I know asyncData is not called with `this` context but is there any way to access the props passed to a component or the depth? I couldn't see the variable in any of the context passed but thought I'd ask.

**Comment by silverbackdan** [comment]
I've decided to try a method of loaded pages as seen in the hacker news demo so that I can create a page for each level I need and pass the depth as an argument.

**Comment by mootari** [comment]
If you mean getting the depth on the child page, you can probably derive that from the number of matched routes (1 meaning there is no parent):
```javascript
export default {
  async asyncData(context) {
    const count = context.route.matched.length;
    // ...
  }
}
```

**Comment by silverbackdan** [comment]
Sorry for the late reply but unfortunately not in may case. My routes are all dynamic so all routes would always be matched. For others that may work though. This problem reared it's head again for me when I found this thread again for my current project, if I find a solution I'll post here. Thanks!

**Comment by silverbackdan** [comment]
```
export default {
  render(h) {
    return h(createPage(Page, this.$vnode.data.nuxtChildDepth))
  }
}
```
Easy as that :)

**Comment by silverbackdan** [comment]
I found the best way is to get all the data in middleware and then find the data at the depth I wanted from the `render` method with `this.$vnode.data.nuxtChildDepth`
