### ISSUE TITLE
Vuex Store with modules bug with mapGetters

### ISSUE THREAD

**Issue by enricribas** [nuxt/nuxt.js#243]
Using separate files for Vuex Store in Nuxt.js
Pretty sure there is a bug in module getters _(or I'm dummy which also happens a lot)_

This works... ( in store/project.js )

``` 
{{ selected }}
...
computed: {
  selected () {
        return this.$store.state.projects.selected
  }...
}
```

this does not... 
```
computed: {
     ...mapGetters('projects', ['selected'])
  }...
}
```

nor does this...
```
      ...mapGetters({
        selected: 'projects/selected'
      }),
```

nor this...
```
      ...mapGetters(['projects/selected']),

```

PS my getter is ... ( store.projects.js )
```
export const getters = {
  selected () {
    return state.selected
  }

```

I've gotten this to work in plain vue/vuex so maybe I'm just messing up the NuxtJS syntax?

**Comment by Atinux** [comment]
Hi @enricribas 

I just updated the [vuex-store-modules](https://github.com/nuxt/nuxt.js/tree/master/examples/vuex-store-modules) to use the getters.

It should work like this:

`store/projects.js`:
```js
export const getters = {
  selected (state) {
    return state.selected
  }
}
```

And in your component:
```js
computed: {
  ...mapGetters({
    selected: 'projects/selected'
  })
}
```

**Comment by enricribas** [comment]
damn sorry. I was missing the state in the getter. Strange I didn't see an error.

**Comment by a-j-n** [comment]
what if i want to pass parameters to getter method ?
