### ISSUE TITLE
components mounted no work in window7 IE9 

### ISSUE THREAD

**Issue by myzhoulang** [nuxt/nuxt.js#2430]
The `method` and `mounted` in the `component` under **window7 IE9**,  sometimes does not execute。Not every time. When the console is opened, it is executed correctly.

![fafasf](https://user-images.githubusercontent.com/7009272/34239253-0f009aea-e641-11e7-923d-c9621e72dd70.jpg)

demo: [https://www.jumorexfp.com/](https://www.jumorexfp.com/)

**Comment by husayt** [comment]
try adding babel-polyfill to your vendor settings in nuxt.config.js

```
 vendor: ["babel-polyfill"]
```
