### ISSUE TITLE
Why does the build process take 15sec+?

### ISSUE THREAD

**Issue by pSchaub** [nuxt/nuxt.js#2433]
Why does the build process take so long? I have a i7 6xxx processor with a 1TB M.2 SSD and 16GB RAM. How can we increase the speed of the build process?

It's annoying to wait ~15sec for a build; even on 'npm run dev'.

```
DONE  Compiled successfully in 13812ms
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2109">#c2109</a>)</em></sub></div>

**Comment by jsonberry** [comment]
How "big" is your app?

**Comment by awronski** [comment]
I have the same problem. The build is slow even for for small app (just 3 pages).
It takes 14+ seconds on Xeon with 16 cores and 64GB of RAM.

```
  nuxt:build Building... +0ms
  nuxt:build App root: /opt/nodeapps/app-spa/app-client +0ms
  nuxt:build Generating /opt/nodeapps/app-spa/app-client/.nuxt files... +0ms
  nuxt:build Generating files... +13ms
  nuxt:build Generating routes... +6ms
  nuxt:build Building files... +38ms
Build completed in 12.468s

Hash: bc4b54c12b59362d9d01
Version: webpack 3.5.5
Time: 12473ms
                                                                   Asset       Size  Chunks             Chunk Names
               pages/blog-page-keywords-name.0f861fa6e614f3e59b28.js    13.5 kB       0  [emitted]  pages/blog-page-keywords-name
                                 layouts/default.059bfad48863fcf28cc1.js    10.4 kB       1  [emitted]  layouts/default
pages/blog-post-lessonId-page-keywords-topic.af0491d1caf4ddd0f4e1.js      10 kB       2  [emitted]  pages/blog-post-lessonId-page-keywords-topic
                                     pages/index.0693c1062109c71ed8e5.js  392 bytes       3  [emitted]  pages/index
                                          common.7b45f84d0622cc0ddcc8.js     253 kB       4  [emitted]  common
                                             app.04bea05d2f4513765eb1.js    31.2 kB       5  [emitted]  app
                                        manifest.bc4b54c12b59362d9d01.js    1.74 kB       6  [emitted]  manifest
                                                                LICENSES    1.08 kB          [emitted]
 + 10 hidden assets
Hash: ee8bb82c05d915ebbc3a
Version: webpack 3.5.5
Time: 1278ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  509 kB          [emitted]
  nuxt:build Building done +14s
```

**Comment by mcquiggd** [comment]
I just did an unscientific test on a server I have available, with the vanilla nuxt community starter.

Quad vCPU (4 x Xeon E5-2620 cores @ 2 Ghz)
SSD on a SAN, no further details but it's unlikely to be a bottleneck.
OS - Ubuntu 16.04 Server, with MATE for a GUI.
Visual Studio Code 1.19.
Node 9.3.0
Npm 5.5.1
WebPack 3.10


Command: **npm run build** (executed on bash terminal in VS Code, and in standalone bash terminal - no discernible difference.)
Total time: **16657ms**.
Average memory used: 1.5 GB.
Approximate average CPU across four vCPU cores: 30% for about 10 seconds, then a slight spike to about 50% towards the end of the build process.


Command: **npm run dev** (executed on bash terminal in VS Code, and in standalone bash terminal - no discernible difference.)
Total time: **16380ms**.
Average memory used: 1.6 GB.
Approximate average CPU across four vCPU cores: 20% for about 10 seconds, then a spike to about 50% towards the end of the build process.

Command: **yarn build** (executed on bash terminal in VS Code, and in standalone bash terminal - no discernible difference.)
Total time: **19389ms**.
Average memory used: 1.7 GB.
Approximate average CPU across four vCPU cores: 40%.

Command: **yarn dev** (executed on bash terminal in VS Code, and in standalone bash terminal - no discernible difference.)
Total time: **9023ms**.
Average memory used: 1.6 GB.
Approximate average CPU across four vCPU cores: 40%.

I remember reading on an issue that nuxt does build in parallel - and that does appear to be the case. But it is not really touching CPU, memory, swap, or disk - so it`s not entirely clear what is taking the time. 

Yarn dev seems to be marginally quicker than npm run dev, but as I say this is unscientific tests, and transients might have an impact.

**Comment by cdoneshot** [comment]
about 19 pages.it takes 2min+
```js
> nuxt build

2018-01-05T08:30:41.043Z nuxt:build Building...
2018-01-05T08:30:47.182Z nuxt:build App root: D:\hyku-projects\pages\src
2018-01-05T08:30:47.182Z nuxt:build Generating D:\hyku-projects\pages\.nuxt files...
2018-01-05T08:30:47.242Z nuxt:build Generating files...
2018-01-05T08:30:47.252Z nuxt:build Generating routes...
2018-01-05T08:30:47.392Z nuxt:build Building files...
Hash: e2cce90c090f0974c474
Version: webpack 3.8.1
Time: 70100ms
                                                      Asset     Size  Chunks             Chunk Names
           pages\episodes-share\_id.ff7d59823b837bbecfd6.js  37.4 kB       8  [emitted]  pages\episodes-share\_id
            fonts/glyphicons-halflings-regular.fa27723.woff  23.4 kB          [emitted]
                                  img/logo_hyku.2958c13.png  61.8 kB          [emitted]
                                    img/loading.9b0345f.gif  4.65 kB          [emitted]
                                img/guess-wrong.7cfef9a.png  1.15 kB          [emitted]
               img/glyphicons-halflings-regular.8988968.svg   109 kB          [emitted]
           fonts/glyphicons-halflings-regular.448c34a.woff2    18 kB          [emitted]
                                       img/logo.98e65bd.png  30.5 kB          [emitted]
                                img/guess-right.297742d.png  2.26 kB          [emitted]
                                img/loaded-fail.137948e.png  6.92 kB          [emitted]
                         img/guess-right-choice.f9792d6.png  1.66 kB          [emitted]
             fonts/glyphicons-halflings-regular.f4769f9.eot  20.1 kB          [emitted]
                            img/vote-title-icon.e064f10.png  2.75 kB          [emitted]
                           img/guess-title-icon.bb3fbdb.png     2 kB          [emitted]
             fonts/glyphicons-halflings-regular.e18bbf6.ttf  45.4 kB          [emitted]
                            img/loading-success.f3d9eb5.png  9.35 kB          [emitted]
                                    img/dispear.7104282.png  11.5 kB          [emitted]
                                      img/colck.bd6ebd2.png  1.69 kB          [emitted]
                            img/radio-unchecked.52466a3.png  1.48 kB          [emitted]
                                   img/no-reply.56c42f4.png  31.3 kB          [emitted]
                                   img/customer.484e84a.png    10 kB          [emitted]
              pages\guess-share\_id.6c4fa9df602dcc0f89fc.js   213 kB       0  [emitted]  pages\guess-share\_id
               pages\vote-share\_id.1f98a9d7e1cfff1f4022.js   209 kB       1  [emitted]  pages\vote-share\_id
                pages\ugc-share\_id.ba5c88c8fa3626c7c0b8.js   196 kB       2  [emitted]  pages\ugc-share\_id
            pages\article-share\_id.299d0f8f6a626cdddce8.js   195 kB       3  [emitted]  pages\article-share\_id
                    pages\guess\_id.35162b2eb47294a5a4e8.js   198 kB       4  [emitted]  pages\guess\_id
                     pages\vote\_id.b0c59879f64f850a3b31.js   195 kB       5  [emitted]  pages\vote\_id
               pages\info-share\_id.89d3a926b0bd766d386e.js   194 kB       6  [emitted]  pages\info-share\_id
                pages\spu-share\_id.c309a7bcea1a2c0c2ba8.js   190 kB       7  [emitted]  pages\spu-share\_id
                                    img/ic_play.1ff9ef3.png  2.92 kB          [emitted]
                      pages\ugc\_id.1e0786f8b9304dba5770.js   176 kB       9  [emitted]  pages\ugc\_id
       pages\lottery\_id\regulation.06fe69457914d9117427.js   173 kB      10  [emitted]  pages\lottery\_id\regulation
      pages\lottery\_id\description.4d8f0cb3c191c1fe375f.js   173 kB      11  [emitted]  pages\lottery\_id\description
                  pages\article\_id.18bef94203def4e460ec.js   174 kB      12  [emitted]  pages\article\_id
                     pages\info\_id.425c67fa6ea2efacaa27.js   174 kB      13  [emitted]  pages\info\_id
                 pages\episodes\_id.af52e63efc76203c773b.js  6.04 kB      14  [emitted]  pages\episodes\_id
pages\merchant\_id\customer-service.4528edccef7ec0e1dc17.js   166 kB      15  [emitted]  pages\merchant\_id\customer-service
                      pages\spu\_id.4cbee9499a64308a01c2.js   169 kB      16  [emitted]  pages\spu\_id
pages\doku\offline\zh-CN\how-to-pay.d04c7e086f28d2ed93be.js  3.66 kB      17  [emitted]  pages\doku\offline\zh-CN\how-to-pay
pages\doku\offline\id-ID\how-to-pay.37be440de41c8c5f4b32.js  3.65 kB      18  [emitted]  pages\doku\offline\id-ID\how-to-pay
pages\doku\offline\en-US\how-to-pay.9a51a95973dc78fb0728.js  3.65 kB      19  [emitted]  pages\doku\offline\en-US\how-to-pay
     pages\about\id\terms-of-server.dc92208e7ba136dca0cf.js  22.1 kB      20  [emitted]  pages\about\id\terms-of-server
             pages\about\id\feature.76e9851a511d7b9b644d.js  1.94 kB      21  [emitted]  pages\about\id\feature
     pages\about\en\terms-of-server.00abc11f5375b918c043.js  22.1 kB      22  [emitted]  pages\about\en\terms-of-server
             pages\about\en\feature.739400bb6786b1b53de9.js  1.95 kB      23  [emitted]  pages\about\en\feature
     pages\about\cn\terms-of-server.9d2127d9dc2f5feac6fc.js  18.3 kB      24  [emitted]  pages\about\cn\terms-of-server
             pages\about\cn\feature.fce9049f0be8826e7d81.js  1.48 kB      25  [emitted]  pages\about\cn\feature
             pages\cod\zh-CN\policy.a6488dc4b538aae9ce06.js  8.54 kB      26  [emitted]  pages\cod\zh-CN\policy
             pages\cod\id-ID\policy.2a075f5964dfa0f7abbf.js  9.49 kB      27  [emitted]  pages\cod\id-ID\policy
             pages\cod\en-US\policy.7a9d5af87cbf58ca3887.js  8.54 kB      28  [emitted]  pages\cod\en-US\policy
      pages\about\id\privacy-policy.dbe9b26464989d99f74d.js  6.17 kB      29  [emitted]  pages\about\id\privacy-policy
      pages\about\en\privacy-policy.ecea0c1f207c8c5f09d1.js  6.17 kB      30  [emitted]  pages\about\en\privacy-policy
      pages\about\cn\privacy-policy.254e691884bb719f61f0.js  4.26 kB      31  [emitted]  pages\about\cn\privacy-policy
                    layouts\default.885fddc522835bf69639.js  2.59 kB      32  [emitted]  layouts\default
                             common.d7a236f6bcb8a7286d48.js   259 kB      33  [emitted]  common
                                app.5b09045357acfafebf3e.js   201 kB      34  [emitted]  app
                           manifest.e2cce90c090f0974c474.js  3.41 kB      35  [emitted]  manifest
                                                   LICENSES  1.22 kB          [emitted]
 + 39 hidden assets
Hash: 5fa69f2abc67e8beab39
Version: webpack 3.8.1
Time: 39109ms
             Asset     Size  Chunks             Chunk Names
server-bundle.json  8.06 MB          [emitted]
2018-01-05T08:32:37.552Z nuxt:build Building done
```

**Comment by manniL** [comment]
Same issue here for a really small app with ~ 3 pages

**Comment by rancongjie** [comment]
same issue ,build so slow

**Comment by pierregorce** [comment]
same issue for me, build become really slow (between 10s to 40s)
6-7 really little plugins, 1 bigger : vuetify

**Comment by DelattreAdixon** [comment]
Same issue, I have a serious lead, I have only one page (index.vue), the rendering takes 30s every time I change a single character. if I remove all the CSS classes, it takes only 4s. I think Nuxt can't handle too many attributes inside a HTML tag.

**Comment by manniL** [comment]
The current build time for a fresh project (latest `nuxt-edge`) is ~5-7 seconds 

Should be fine as you "only" build when deploying (and you could prebuild the app and move it to the server then) and when developing, but then HMR is on.

![image](https://user-images.githubusercontent.com/640208/43821272-fe7621ec-9ae8-11e8-8650-b16109504ee9.png)

**Comment by Globegitter** [comment]
@manniL I also wonder if one could optimize this by not always have to run all build steps. It seems to me that some of the files are static, at least within a project and a nuxt version right? i.e. they do not change between rebuilds (like `.nuxt/server.js`). If that is the case would it be possible to have a `--template/--no-template` flag? Then one could split off the command into two steps and cache the templates that do not change and only rebuild them e.g. on a new nuxt version, or a nuxt config change and otherwise just build the webpack and dynamic part (like `.nuxt/router.js`). Is that something that would be possible? We are looking at how we can reduce build times as much as possible, not just for better CI performance, but also we have started to get used to being able to occasionally do live development against a k8s cluster in the cloud in other parts of the stack and there being able to shave off any second counts.

**Comment by qm3ster** [comment]
CI should always do a clean full build in case there's a mistake in caching/optimization.
The build can be further optimized, but the main target is dev hot module reload time, not full builds.

**Comment by Globegitter** [comment]
I disagree with that statement, we are using bazel: https://bazel.build/, which functionality at the heart is to cache everything aggressively and have nearly the same iterative builds for production as for development. But it is also your project and if your main target is dev rebuilds and not full builds that is totally fair :)

**Comment by qm3ster** [comment]
It's not my project, don't worry. I can see the advantages of such an approach, but it goes against the principle of build being a pure function from code to artifact. People don't trust their cache applications/implementations very much nowadays.

> if one could use nuxt programatically in a more fine-grained way and getting access to the different build steps in the Builder

This would definitely slow down iteration on the project since this will become a public API, but I can see why that should be a goal in the long run. I do always suggest smaller modules wired up in userspace and a template using them to get one started, or a module that takes them as peer dependencies and allows ejecting when needed.

**Comment by ramstein74** [comment]
does this help in any way?
https://www.npmjs.com/package/only-if-changed-webpack-plugin
