### ISSUE TITLE
Out of commission Zepto

### ISSUE THREAD

**Issue by ithack** [nuxt/nuxt.js#2434]
> 
build:
 {
    loaders:[
        {test: /\.less$/,loader: 'style!css!less'},
        {
            test: require.resolve('zepto'),
            loader: 'exports-loader?window.Zepto!script-loader'
        }
        ],
    vendor: ['axios','zepto'],
      plugins: [
          new webpack.ProvidePlugin({
              '$': 'zepto',
              'Zepto': 'zepto',
              'window.Zepto':'zepto'
          })
      ]
  }

 Cannot read property 'createElement' of undefined

**Comment by cesasol** [comment]
Wrap your code using zepto with `if (process.client) {}`

**Comment by gaofei019** [comment]
组件内使用到浏览器相关api的部分需要判断环境，比如初始化 iscroll，测量宽度等
var $;
if(process.browser){$=require('zepto')}
