### ISSUE TITLE
asyncData called on child pages that have not been included in parent

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#2435]
If there is a child page where the parent has not included a <nuxt-child /> the child will still run the asyncData function.

Here is a repro:
https://subdued-pest.glitch.me
https://glitch.com/edit/#!/subdued-pest?path=pages/_page1/_page2/_page2.vue:13:9

Should the asyncData functions for pages/child pages only be run when the child is actually included/required?

I think in this scenario it is because the child page also matches the route but I can't be sure that's why.

**Comment by clarkdo** [comment]
Could you please have a try on `nuxt@next`, it should work.

**Comment by silverbackdan** [comment]
Hi @clarkdo I've just tried this again and updated the glitch. Sorry for the bad news but unfortunately, it appears it still triggers the function in _page2.vue when loading _page1.vue.

In the example, the home page loads, if you press the 'about' link it links to _page1.vue - but the function in _page2.vue is also run which can be seen because it logs to the console.

**Comment by clarkdo** [comment]
@silverbackdan 
I will discuss with team about this situation. For you case, you can move `pages/_page1.vue` to `pages/_page/index.vue` as a fix.

**Comment by silverbackdan** [comment]
This is great and I like the merged fix too, thank you @clarkdo

**Comment by clarkdo** [comment]
According to the discussion with @alexchopin: it’s a normal behaviour actually, because it’s parent/child component, otherwise you will have an issue with <nuxt-child> component.

So if you don't call child asyncData, you can do what I have mentioned above, or remove `_page2.vue` and add `v-if/v-else` in `/_page1.vue` file.

**Comment by silverbackdan** [comment]
OK thanks - I've got a solution that works right now but it's a not a bog standard page structure for me as I'm creating an app which loads each page and components with nesting from an API. I may be able to mess around with this file structure though to reduce asyncData calls or loading components which are not required for a specific page.
