### ISSUE TITLE
How to exclude node_modules but one package from babel-loader?

### ISSUE THREAD

**Issue by f15gdsy** [nuxt/nuxt.js#2436]
Hi, I have written a raw ES6 package and want to use it in my Nuxt project through npm link during development.

I searched for the [setting](https://github.com/webpack/webpack/issues/2031#issuecomment-244921229) in webpack.
I tried to change the exclude property in extend in nuxt.config.js, but no luck.
```javascript
  extend(config, ctx) {
     config.module.rules
        .find(aRule => aRule.loader === 'babel-loader')
        .exclude = /node_modules\/(?!my-package\/).*/
  }
```

Any ideas?
Thanks.

**Comment by clarkdo** [comment]
Have a look at: https://github.com/nuxt/nuxt.js/issues/1668#issuecomment-330510870

**Comment by tirthaguha** [comment]
if you're using webpack, you can use _externals_ for ignoring directories from being bundled.
https://webpack.js.org/guides/author-libraries/#external-limitations
