### ISSUE TITLE
Nuxt in production

### ISSUE THREAD

**Issue by napestershine** [nuxt/nuxt.js#2438]
HI

I am using nuxt for first time and probably first front end framework for me.

How can I deploy it in production. LIke when we create VUE app we have a index.html as entry point but in nuxt directory there is no such file. 

So do you guys go with this ?

Thanks :)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2116">#c2116</a>)</em></sub></div>

**Comment by microcipcip** [comment]
It depends, do you want to run a node app or deploy a static generate website?
- You can [generate a static website](https://nuxtjs.org/guide#static-generated-pre-rendering-) with `nuxt generate`
- You can [generate a single page app](https://nuxtjs.org/guide#single-page-applications-spa-) with `nuxt --spa`
- You can generate and start a node app with `npm run build && npm start` further info here https://nuxtjs.org/faq/heroku-deployment

**Comment by jsonberry** [comment]
☝️ And for deployment, with the `generate` option, for example, you want to deploy the entirety of the `dist` dir that is generated. That is your whole app.

An easy way to start messing around and learning about deployments is to spin up a new repository on Github and use one of the nuxt template starters. Then open up a free https://www.netlify.com/ account, and create a site for that repo. Set your build directory to "dist", and your build command to whatever you set up for generations (like `npm run generate`). Then netlify will deploy a SSR version of the nuxt starter template.
