### ISSUE TITLE
During npm run build, some files are removed therefore causing js file missing

### ISSUE THREAD

**Issue by fuckohyes** [nuxt/nuxt.js#2439]
During npm run build, some files are removed therefore causing js file missing(.nuxt). npm run build takes about 60 sec on our server. Anyone visiting during this time will get file missing.
releases:v1.0.0-rc11
Is it a software bug or is there any way to modify the file without deleting the .nuxt/*.js  ???

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2115">#c2115</a>)</em></sub></div>

**Comment by fuckohyes** [comment]
I use PM2 for management without error logs

**Comment by pimlie** [comment]
You could set a dynamic `buildDir` in your `nuxt.config.js` based on some timestamp, probably you would need some more code for cleanup etc. But please keep in mind that using npm run your update process will never be really atomic.

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
