### ISSUE TITLE
in nested routes parent page data resets

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#2444]
when you have a nested page route using `nuxt-child`, the data set on the parent page resets to the default when you change route of the child.

pages
- parent
- - child.vue
- - child2.vue
- parent.vue

if parent has data of 
```
{ toggled: false }
```

and you set toggled to true and change the child route, toggled will go back to false.

# expected behavior
the parent data should stay and only reset if the parent is remounted.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2119">#c2119</a>)</em></sub></div>

**Comment by yingye** [comment]
This problem also block me.

**Comment by alidcastano** [comment]
maybe you can do this:

data () {
  return {
    toggled: this.toggled || false
  }
}

**Comment by uptownhr** [comment]
@alidcastano might be a work around but still feels like an unexpected behavior.
@husayt I see that you've marked this as a question, would you consider marking it as a bug as well?

**Comment by MaxKostenko** [comment]
> maybe you can do this:
> 
> ```
> data () {
>   return {
>     toggled: this.toggled || false
>   }
> }
> ```

It helps me, but looks hacky

**Comment by MaxKostenko** [comment]
Lifecycle also looks strange.  It fires updated lifehook and then call data() method

**Comment by Mini-ghost** [comment]
I use Nuxt 2.11.0 and this problem also block me, too.

> > maybe you can do this:
> > ```
> > data () {
> >   return {
> >     toggled: this.toggled || false
> >   }
> > }
> > ```
> 
> It helps me, but looks hacky

and this solution is useful，but maybe is not good...

**Comment by shrpne** [comment]
And also it's not stale for Nuxt 2.15.8

@manniL I think `stale` label should be removed
