### ISSUE TITLE
Does Nuxt work with Firebase Hosting ? 

### ISSUE THREAD

**Issue by besnikh** [nuxt/nuxt.js#2446]
Hi,
I love Vue, and I love Nuxt.. I've build half of my webapp using Vue, then I started using Nuxt for SSR. 
Now that my my app is like 95% completed... I decided to use most of Google Cloud products instead of AWS. 

Now, I could maybe use Cloud AppEngine but the interesting part is Firebase Hosting, which is really fast and a lot of magic. 
But I am thinking and I could not find any reference of could we use NUXT on Firebase hosting? If yes, what are the steps do do so, or is there any reference on how to archive such a step. 

Cheers

**Comment by robyedlin** [comment]
You can deploy a Nuxt app on Firebase hosting as an SPA or static site, but not SSR. For that you'll need to integrate Firebase cloud functions.

https://github.com/nuxt/nuxt.js/issues/1634

**Comment by Imanullah** [comment]
Yes NUXT work perfectly with firebase and firestore... 

for your deployment set this on firebase.json 
`{
  "hosting": {
    "public": "./dist",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
`

**Comment by joha0033** [comment]
I don't understand, newbie... I just worked a tutorial for nuxt and want to deploy to firebase. 
I've never deployed SSR before. run some sort of build > then firebase init (any thing weird?) > then firebase deploy > what could I be missing?

**Comment by pi0** [comment]
https://twitter.com/Firebase/status/958383927105900549

**Comment by joha0033** [comment]
Oh wow… haven’t watched it yet, but thank you!

Great find.

AustinRJ
www.ajdevs.com <http://www.ajdevs.com/>

**Comment by jefrydco** [comment]
Hi @pi0 
Nuxt is integrated with Firebase very well using cloud function, but it seems to be a problem when we adding custom component from third party UI library like Vuetify and Buefy. I've created an issue here, #2844 any idea?

**Comment by husayt** [comment]
This seems to be resolved now. Closing. Reopen if still happens.

**Comment by joha0033** [comment]
Awesome, thanks!
