### ISSUE TITLE
Computed properties are not cached during SSR

### ISSUE THREAD

**Issue by stijnvermeeren** [nuxt/nuxt.js#2447]
I have a computed property that does a fairly expensive calculation based on the data in my Vuex store. The result of that calculation is then used many times on the page. The page renders in the blink of an eye on the client, but takes ages to render on the server. It turns out that the difference is that computed properties are not cached at all when doing server side rendering! 

Nuxt version 1.0.0-rc11. This behaviour happens both in development and in production mode.

Basic example to reproduce the problem:
```
<template>
  <ul>
    <li v-for="value in values">{{computeForValue(value)}}</li>
  </ul>
</template>

<script>
  export default {
    data () {
      return {
        values: [1, 2, 3, 4, 5, 6]
      }
    },
    computed: {
      computedFn () {
        console.log('Computed function')
        // Doing some expensive calculations
        return Math.PI
      }
    },
    methods: {
      computeForValue (value) {
        console.log('Computation for value', value)
        return value * this.computedFn
      }
    }
  }
</script>
```

Server side:
![screenshot from 2017-12-23 20-36-47](https://user-images.githubusercontent.com/21952925/34322182-3fb49588-e821-11e7-915a-24d4f089d01b.png)

Client side:
![screenshot from 2017-12-23 20-37-05](https://user-images.githubusercontent.com/21952925/34322183-42c32fa0-e821-11e7-96fb-684813d23eb4.png)

**Comment by 0pt1m1z3r** [comment]
@stijnvermeeren https://github.com/vuejs/vue/commit/06741f326625e2db78d092e586923b97ba006906

**Comment by stijnvermeeren** [comment]
Oh wow. So "its not a bug, it's a feature"? I now found https://ssr.vuejs.org/en/universal.html which presents it as an advantage... I feel like it should be mentioned in big red letters in the documentation (both for nuxt and for ssr.vuejs.org) that this "feature" could lead to unexpected behaviour and be a performance killer as well.

It is true that I don't really need the reactivity on the server side. As soon as the store data is pre-fetched, the value that needs to be returned by these computed functions is fixed. But I do need them to be called just once and then cached, not called 6 (or 1.000, or 1.000.000) times. Is there any way to achieve this without starting to write completely separate code for the server and for the client?

**Comment by clarkdo** [comment]
Hope https://github.com/nuxt/nuxt.js/issues/2264 can help you

**Comment by stijnvermeeren** [comment]
Thanks for the idea @clarkdo . Maybe I misunderstood, but your suggestion in that issue seems to involve committing a property to the state of the store. However, I don't want to make my expensive computed properties part of the state of my store, for several reasons:
- This would mean that I have to manually trigger a recomputation of these expensive computed properties every time that my actual state changes.
- The store is shared by many pages, but most of these expensive computed properties are only used on a single page, and hence don't really belong in the store at all. Also, a state change should not trigger a recomputation of all of the expensive computed properties, only those that are used on the current page.
- I also fear that putting many complex objects in the state of my store might be a performance bottleneck for the Vue reactivity algorithm.
(By "expensive computed properties" I mean that they become a performance bottleneck if they are re-computed every time that they are accessed.)

I have asked for help on the Vue forum (https://forum.vuejs.org/t/ssr-performance-problems-due-to-lack-of-caching/24653). Hopefully someone will be able to help me there, or if this really is a fundamental problem with Vue SSR, I will open an issue in the Vue project.

**Comment by mese79** [comment]
How about [vuex getters](https://vuex.vuejs.org/en/getters.html)?

> Vuex allows us to define "getters" in the store. You can think of them as computed properties for stores. Like computed properties, a getter's result is cached based on its dependencies, and will only re-evaluate when some of its dependencies have changed.

**Comment by stijnvermeeren** [comment]
@mese79 Thanks for the suggestion. However I tried it and I ran into the same problem. In the context of SSR, the documentation is just wrong and the results of the getters are not cached. (I guess computed properties in Vue components and getters in the Vuex store use the same underlying mechanism for caching.)
