### ISSUE TITLE
How to define webpack on config.nuxt.js

### ISSUE THREAD

**Issue by besnikh** [nuxt/nuxt.js#2449]
Hi,

I need to define webpack but I am just looking what is the best way to define it... cuz nuxt config is a little bit weird for me even though I am loving it and I am building my app on it. 

Following these instructions here: `https://gist.github.com/rvanzon/6028e884f6735c41125fb2d140143102` where I wanted to reduce chunk size. 

So I added this line: 
` if (!this.dev) {
    config.plugins.push(new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 3        
    }))
  }`

And now I am getting error that webpack is not defined. 

Thnx in advance for any help.

**Comment by MRZMUH001** [comment]
Do you this line at the top of the file? 
```
const webpack = require('webpack') ;
```
