### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by kalken** [nuxt/nuxt.js#245]
Hey!
First off, thanks for an awesome framework!

i'm trying to use keen-ui with nuxt.js and ran in to some problems. i have read all documentation i can find but still unable to find an answer.

keen-ui is here:
https://github.com/JosephusPaye/Keen-UI

This is the info i can find about nuxt and server side rendering.
https://nuxtjs.org/guide/plugins#vue-plugins
https://nuxtjs.org/faq/window-document-undefined/

This documentation still does not explain how to handle a gui for a whole application with serverside rendering. A problem i think almost everybody will have at some point in the process of making something useful...

As soon as i run `import KeenUI from 'keen-ui';` i get the "document is not defined error" so the check for browser has not even happened yet...

Can somebody can give any more pointers how to correctly import and use gui-libraries in nuxt.js, with a use case for a simple template using a component?

I'm starting to think that maybe its impossible to use keen-ui with serverside rendering as it is. If thats the case i will post an issue there as well, just let me know

thanks!

**Comment by kalken** [comment]
Ok i switched to vue-material as gui and got it to work by:

plugins/vue-material.js:

```
import Vue from 'vue'

if (process.BROWSER_BUILD) {
	const VueMaterial = require('vue-material')
	Vue.use(VueMaterial)
}
```

and adding to nuxt.config.js:
```
module.exports = {
	dev: (process.env.NODE_ENV !== 'production'),
	css: ['vue-material/dist/vue-material.css'],
	plugins: ['plugins/vue-material.js']
}
```

is this the correct way to do it? Can you maybe add this instructions to the documentation for a more general approach to guis?

**Comment by alexchopin** [comment]
Hi,
Unfortunately, Keen-UI doesn't support Component SSR.
Yes it is the good way to import an external library, this instructions are already on the documentation.
