### ISSUE TITLE
nuxt ie9的兼容问题

### ISSUE THREAD

**Issue by q771307617** [nuxt/nuxt.js#2451]
store.replaceState    在挂载的时候ie9会直接报错，，，ie9不支持replaceState    语法；

报错如下：

**Comment by q771307617** [comment]
[nuxt] Error while initializing app TypeError: 对象不支持“replaceState”属性或方法

**Comment by q771307617** [comment]
"[nuxt] Error while initializing app"

description"对象不支持“replaceState”属性或方法"
message"对象不支持“replaceState”属性或方法"
name"TypeError"
number-2146827850

**Comment by robyedlin** [comment]
IE9 doesn't support history.replaceState . You can either try to Polyfill it with history.js https://github.com/browserstate/history.js (I haven't tested this in IE9, and it might also introduce new issues), or maybe try to use hash mode in your router (I also haven't tested in IE9). 

https://nuxtjs.org/api/configuration-router/#mode

```
module.exports = {
  router: {
    mode: 'hash'
  }
}
```

**Comment by q771307617** [comment]
THANK YOU
