### ISSUE TITLE
Components in layout are not rendered

### ISSUE THREAD

**Issue by vaggelis2018** [nuxt/nuxt.js#2452]
I have found a weird problem on a clean install. I have a toolbar component and i am trying to import it in the layout file. The component is not rendering but if i try to import it in a page it renders normal. It has nothing special this component and i have tried it in another clean installation 3 days ago and it was working. Was there any changes in these days. Can't we import custom components to layout and use them all over the app?

**Comment by jsonberry** [comment]
No new releases
Yes you can put components in layouts

What is the layout, and does the page you visit use that layout?

**Comment by vaggelis2018** [comment]
I created a new main.vue layout file. Yes the page file uses this layout and i tested it by adding the navigation code(toolbar) directly in the layout and it works but if i put the code in a separate component it doesn't render and neither throws an error. Then i tried if the component works in page view and it works. The only place i can't import components are in the layout views.

**Comment by KyleTryon** [comment]
@vaggelis2018 I think I may be having the same issue as you? https://github.com/nuxt/nuxt.js/issues/2477

**Comment by vaggelis2018** [comment]
Very weird issue.

**Comment by pi0** [comment]
That's a wired issue. If possible please clean up cache (lock files and node_modules) and install nuxt@next to see if the problem still exists or not. If still having problems, sharing both layout `.vue` file and SSR's HTML output would help.

**Comment by vaggelis2018** [comment]
Hello @pi0 and happy new year to all. I have done all of this many times and nothing worked. You can find the code of my project here.
https://github.com/vaggelis2018/nuxt-medrecs

**Comment by vaggelis2018** [comment]
The problem was related to vue-material and had nothing to do with nuxt so i am closing the issue

**Comment by vaggelis2018** [comment]
The problem was related to vue-material and had nothing to do with nuxt so i am closing the issue

**Comment by JX49** [comment]
What was the problem? I think I'm having the exact same issue

**Comment by KyleTryon** [comment]
@JX49 If I remember correctly, check to see if you have any malformed HTML anywhere, like an extra closing bracket.
