### ISSUE TITLE
nuxt custom router middleware /dir/

### ISSUE THREAD

**Issue by besnikh** [nuxt/nuxt.js#2453]
Hi,
I know how to create a middleware for each route, and in my case auth guards, but is there any other way just to add the middleware in nuxt.confif.js to guard all /users/ directory for example or /business/ 

I can't figure that out if that can be done, and until now I'm doing it manually by adding the middleware to to every page. 

Cheers :+1:

**Comment by clarkdo** [comment]
You can set `middleware` properties in  root `pages` of `/users/index.vue`, so all of `/users` sub routes will work.
