### ISSUE TITLE
Store middleware throwing an Vuex error

### ISSUE THREAD

**Issue by besnikh** [nuxt/nuxt.js#2454]
Hi, 

I am using a middleware so only registered users can see that page and this is the middleware: 
`middleware/auth.js`
```
export default function ({ store, redirect }) {
  if (!store.state.user.isAuthenticated) {
    redirect('/')
  }
}
```
and my store is a module so this is the file there: 
store/user.js
export const state = () => ({
  isAuthenticated: null,
  extraInfo: null,
})

And now my auth middleware is working fine that is throwing an error on console when I enter the route. 
`[vuex] unknow getter:                                                                           vuex.esm.js:849`

Can someone help me get rid of this error or is this a bug ? 

Cheers

**Comment by jaybeecave** [comment]
store.state.auth.user.isAuthenticated????

**Comment by clarkdo** [comment]
Can you please provide a repo can reproduce the issue ?
