### ISSUE TITLE
 Nuxt is not a constructor

### ISSUE THREAD

**Issue by duqigit** [nuxt/nuxt.js#2455]
![8h42 q ek43xb0xsbqm5 a](https://user-images.githubusercontent.com/25985156/34345305-e3542452-ea28-11e7-95c7-1ae68ee93fed.png)
![k5ri6l_1m_7zsul 8 5y6](https://user-images.githubusercontent.com/25985156/34345307-e67dd812-ea28-11e7-9562-e3fba7717d3a.png)
![s2ev6x6pcksrz5wtez5x2 0](https://user-images.githubusercontent.com/25985156/34345309-e8ac2c92-ea28-11e7-966e-098d9364badb.png)

This is my test project ,user dev is error

link  https://zh.nuxtjs.org/api/configuration-dev
Thanks

**Comment by 0pt1m1z3r** [comment]
@18717700273 `requre('nuxt')` return object with `Nuxt` and `Builder`.
Example: https://github.com/nuxt-community/express-template/blob/master/template/server/index.js#L2

**Comment by chanlito** [comment]
Can we close this?

**Comment by husayt** [comment]
This seems to be resolved now. Closing. Reopen if still happens.
