### ISSUE TITLE
publicPath can support dynamic allocation of domains

### ISSUE THREAD

**Issue by djune** [nuxt/nuxt.js#2457]
How to config the `publicPath` to to solve the browser concurrent link number limit problem?
I have an idea, the `publicPath` can support like this:
```
publicPath = ['//static1.xxx.com', '//static2.xxx.com', '//static3.xxx.com']
```
then we get like this:
```
//static1.xxx.com/a.xxx.jpg
//static2.xxx.com/b.xxx.jpg
//static2.xxx.com/c.xxx.jpg
```
or any other best ways to solve the browser concurrent link number limit problem?

**Comment by 0pt1m1z3r** [comment]
@djune  Now there is no such possibility with `publicPath`. You can write your decision and add PR.

@Atinux @pi0  I think it's a good idea.

**Comment by djune** [comment]
@Atinux @pi0 
I have another idea, which is to write the publicPath as a callback, so that the user is more flexible. like this.
```
module.exports = {
  build: {
    publicPath: (file)=>{
      const paths = ['//static1.xxx.com', '//static2.xxx.com', '//static3.xxx.com']
       return someAlgorithms(file, paths)
    }
  }
}
```
What do you think?

**Comment by Atinux** [comment]
Hi @djune 

Actually it's a Webpack option and Webpack does not handle multiple publicPaths.

But you can always add a Nuxt hook to update the HTML by replacing some publicPath by others so will have mutliple publicPath, see example: https://github.com/nuxt/nuxt.js/blob/dev/examples/with-amp/nuxt.config.js#L20

**Comment by pi0** [comment]
Something else, you can easily round-robin requests between servers with DNS. For cloudflare, this is as easy as defining multi records with the same domain and different IP addresses.

https://www.cloudflare.com/learning/dns/glossary/round-robin-dns

**Comment by djune** [comment]
@Atinux @pi0  Thinks, Sounds great， I'll try it.

**Comment by djune** [comment]
@Atinux It's works on `nuxt v1.0.0` .  What if you need this mutliple publicPath to generate a static page?

**Comment by Atinux** [comment]
@djjne it shoulda work automatically with Nuxt generate :)

**Comment by djune** [comment]
@Atinux 
## pages/index.vue
```
<template>
  <div class="mod-brand">
    <img src="~/assets/1.jpg">
   <img src="~/assets/2.jpg">
  </div>
</template>
```
## nuxt.config.js
```
module.exports = {
  build: {
    publicPath: '/static/xxx/'
  },
  hooks: {
    'render:route': (url, result) => {
      let html = result.html
      // replace 
      result.html = replaceHtml(html, ['//static1.xxx.com', '//static2.xxx.com'])
    }
  }
}
```
## `npm run build && npm run start`
## `view-source:http://localhost:3000`
```
  <div class="mod-brand">
    <img src="//static1.xxx.com/assets/1.xxx.jpg">
    <img src="//static1.xxx.com/assets/2.ooo.jpg">
  </div>
```
## `http://localhost:3000`
```
 <div class="mod-brand">
    <img src="/static/xxx/1.xxx.jpg">
    <img src="/static/xxx/2.ooo.jpg">
 </div>
```

## I want the result is when I  open `http://localhost:3000` in browser I can get like this:
```
  <div class="mod-brand">
    <img src="//static1.xxx.com/assets/1.xxx.jpg">
    <img src="//static1.xxx.com/assets/2.ooo.jpg">
  </div>
```
