### ISSUE TITLE
nuxt generate is OK,however refresh the dynamic routes, it reminder this.$options is undefined

### ISSUE THREAD

**Issue by kafeibei** [nuxt/nuxt.js#2459]
![image](https://user-images.githubusercontent.com/5791527/34354650-c0772230-ea6a-11e7-9660-87837988b080.png)
Using nuxt 1.0.0-rc11

Thank you for your reply!!!

**Comment by lcdss** [comment]
I had an issue like this with the spa mode.

`u[0].options is undefined`

Sometimes I get an error `layout undefined` (something like that - I don't remember exactly).

**Comment by husayt** [comment]
This seems to be resolved now. Closing. Reopen if still happens.
