### ISSUE TITLE
Can I use nuxt.js with Koa

### ISSUE THREAD

**Issue by ihaichao** [nuxt/nuxt.js#246]
When I use `app.use(nuxt.render)`, it throws an error says
`app.use() requires a generator function`
Are there any other ways to use nuxt.js with Koa?

**Comment by uptownhr** [comment]
a middleware for koa would need to be created. most of the time, you can wrap the express middleware to match what koa needs. checkout https://github.com/koajs/koa/blob/master/docs/guide.md

**Comment by alexchopin** [comment]
Hi,
I will create a nuxt/koa starter template soon, it works fine with this code:
app.js
```js
var app = require('koa')()
var Nuxt = require('nuxt')

var config = require('./nuxt.config.js')
config.dev = !(app.env === 'production')

var nuxt = new Nuxt(config)

// Build only in dev mode
if (config.dev) {
  nuxt.build()
  .catch((error) => {
    console.error(error) // eslint-disable-line no-console
    process.exit(1)
  })
}

app.use(function * () {
  this.status = 200 // koa defaults to 404 when it sees that status is unset
  yield nuxt.render(this.req, this.res)
})

app.listen(3000)
```

**Comment by alexchopin** [comment]
[Starter template for Koa](https://github.com/nuxt/koa)

**Comment by chen-zeyu** [comment]
@alexchopin  
koa is not recommended to use req.end()

When using nuxt.render and koa-session, it often throws errors

` Can't set headers after they are sent.`

Almost all koa session modules can not be used

**Comment by dkushner** [comment]
@chen-zeyu, thank you so much for contributing this fact! Have been knocking my head against this error all day, since the root call is obscured by all of the ES7 shim junk. Have you managed to find a workaround for this? I agree, calling `res.end()` is incredibly presumptuous for a middleware-based framework.

**Comment by IlyaSemenov** [comment]
In nuxt@1.0.0-rc3 they reworked the renderer, `nuxt.render` is now a connect middleware and not an async function like it used to be before. Moreover, it's a "terminating" middleware (it doesn't call `next()`), so it can't be directly promisified. You need to use a mocked response object, like this:

```js
app.use(async(ctx) => {
	ctx.status = 200 // koa defaults to 404 when it sees that status is unset
	ctx.req.ctx = ctx // for nuxtServerInit

	await new Promise((resolve, reject) => {
		const mockedResponse = {
			__proto__: ctx.res,
			end() {
				ctx.res.end.apply(ctx.res, arguments)
				// nuxt.render doesn't call next() on successful render,
				// resolve promise manually
				resolve()
			}
		}
		nuxt.render(ctx.req, mockedResponse, promise => {
			// nuxt.render passes a rejected promise into callback on error.
			promise.then(resolve).catch(reject)
		})
	})
})
```

**Comment by IlyaSemenov** [comment]
See #1206 for a workaround for Nuxt 1.0 API changes.
