### ISSUE TITLE
How to create plugin for SMS Gateway API 

### ISSUE THREAD

**Issue by Imanullah** [nuxt/nuxt.js#2462]
Hai I need help how to create plugin for SMS Gateway API 

https://www.npmjs.com/package/sms-gateway-nodejs
or 
https://www.npmjs.com/package/smsgateway

I tried to create but i got error fs dependency not found..... even i have installed it

**Comment by besnikh** [comment]
Show us your code

**Comment by Imanullah** [comment]
@besnikh 
I'm really not sure it's correct 

`import Vue from 'vue'
import SmsGateway from 'smsgateway'

Vue.use(SmsGateway)

export default({app}, inject) => {
  app.smsGateway = new SmsGateway('....@gmail.com', 'password') //for smsgateway.me
}`

**Comment by clarkdo** [comment]
Try to use `inject`.

```js
import Vue from 'vue'
import SmsGateway from 'smsgateway'

export default ({ req }, inject) => {
  // -> app.$smsGateway
  // -> this.$smsGateway in vue components
  // -> this.$smsGateway in store actions/mutations
  inject('smsGateway', new SmsGateway('....@gmail.com', 'password'))
}
```

**Comment by clarkdo** [comment]
Did `SmsGateway` support client side ?

Maybe it because you used `smsGateway` in client side which not support `fs`.
