### ISSUE TITLE
Auth Route Demo not working

### ISSUE THREAD

**Issue by rof20004** [nuxt/nuxt.js#2463]
Here is the link for documentation:
https://nuxtjs.org/examples/auth-routes

Here is the link for demo:
https://nuxt-auth-routes.glitch.me/

The authentication not working. 

Thanks all

**Comment by clarkdo** [comment]
The codes on glitch is too old, you may refer https://github.com/nuxt/nuxt.js/tree/dev/examples/auth-routes for now, we will update it soon.

**Comment by rof20004** [comment]
Thanks, I need to close this issue?

**Comment by clarkdo** [comment]
You can keep it open until issue resolved 😄

**Comment by rof20004** [comment]
Ok, again, thanks @clarkdo

**Comment by clarkdo** [comment]
@rof20004 
Resolved. https://nuxt-auth-routes.glitch.me/
