### ISSUE TITLE
memory leaks with next tag

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#2470]
![image](https://user-images.githubusercontent.com/17898715/34409320-132ef350-ec04-11e7-89f2-85cecd2b32ed.png)
![image](https://user-images.githubusercontent.com/17898715/34410152-358accda-ec09-11e7-8155-4641cacf2950.png)

**Comment by yuchonghua** [comment]
>* Again wrong, I do not know how else

![image](https://user-images.githubusercontent.com/17898715/34409457-e2e795d4-ec04-11e7-8212-4e68ced1342e.png)

**Comment by yeziZ** [comment]
I also met
![image](https://user-images.githubusercontent.com/26887147/34409643-073ba280-ec06-11e7-90b1-efa30fc68509.png)

**Comment by CrastinJiang** [comment]
![image](https://user-images.githubusercontent.com/24558114/34410163-4aeb06d0-ec09-11e7-899c-8a9ee08b381d.png)
after I changed my local files and saved, it just happened once in a whlie

**Comment by yuchonghua** [comment]
Do you know why the latest version of the latest memory leak?
/ping pi0

**Comment by pi0** [comment]
@yuchonghua We are investigating for possible leaks now. It may be probably because of Source maps for SSR. Would you please share a Heap Dump?

**Comment by yuchonghua** [comment]
How does a Heap Dump get and save it

**Comment by pi0** [comment]
Here are some tips for analyzing memory leaks: https://github.com/nuxt/nuxt.js/issues/805

**Comment by chanlito** [comment]
@yuchonghua are still having this issue?

**Comment by husayt** [comment]
Closing, since no enough details. Reopen if still happens.
