### ISSUE TITLE
[Firebase Storage] Firebase.storage is not a function.

### ISSUE THREAD

**Issue by shinrel22** [nuxt/nuxt.js#2471]
I'm working on a project using Nuxt and Firebase.
Everything is ok except firebase storage.

I have 2 pages:
1. index.vue - /
2. add.vue -/add (which implemented firebase storage)
If I get to page no.1 first, then move to page no.2 via router. Everything is ok. Firebase storage works fine.
BUT WHEN I GET DIRECTLY TO /ADD, I GET AN ERROR: Firebase.storage is not a function.
I don't know why? Please help me ...!

**Comment by asifm** [comment]
Have you been able to figure out the problem? Is it 'hash' or 'history' in your VueRouter mode (router.js)? What command (dev, build, etc.) do you run that leads to the error?

**Comment by irthos** [comment]
@shinrel22 Silly question, but have you tried wrapping Firebase.storage call in a timeout to see if there's a difference? Along those lines, you might add Vuex mutation or action with the functionality which should guarantee that state is universal.

**Comment by BernardMarieOnzo** [comment]
is it the same problem as [here](https://stackoverflow.com/questions/41352150/typeerror-firebase-storage-is-not-a-function) ?
I am in the same situation and the answer he gave seems brutal for me would there be another solution ?
please help

**Comment by Viral-Inc** [comment]
+1 firebase storage isn't working from node for me

**Comment by onori** [comment]
try this, work for me.
(using nuxt.js + vuexfire)

* plugins/firebase.js

```js
import firebase from 'firebase'
import 'firebase/storage' // <- add

if (!firebase.apps.length) {
  firebase.initializeApp(
    {
      apiKey: 'xxx',
      authDomain: 'xxx',
      databaseURL: 'xxx',
      projectId: 'xxx',
      storageBucket: 'xxx',
      messagingSenderId: 'xxx'
    }
  )
}
const db = firebase.database()
const storage = firebase.storage()

export { storage, db }
```

* SampleComponent.vue

```vue
<script>
import { storage } from '~/plugins/firebase.js'
</script>
```

https://github.com/angular/angularfire2/issues/1015

**Comment by husayt** [comment]
This seems to be resolved now. Closing. Reopen if still happens.

**Comment by safarovitch** [comment]
Hi,
I was using firebase on android for a while and when I get to create website based on firebase realtime database and firebase storage I got error: 
"newRecord.js:53 Uncaught TypeError: firebase.storage is not a function;"

Its been a day since I faced this error and I was unable to resolve it however everything else is working like a charm. I am using firebase 4.12.1. Any help appreciated!

**Comment by BernardMarieOnzo** [comment]
Are you using Nuxt.js? And are you sure the problem comes from Nuxt?
The problem here is related to the fact that Firebase Storage does not work in Nuxt.js projects and this seems to be resolved now.
