### ISSUE TITLE
SPA Confusion. Difference between build --spa and generate?

### ISSUE THREAD

**Issue by cschweda** [nuxt/nuxt.js#2472]
Okay, so I want to generate a SPA. No SSR.

Do I ```build --spa``` and then ```generate```?

Or is it enough to ```build --spa``` and then deploy the ```dist``` directory?

What's the difference between ```build --spa``` and ```generate```?

(I want to deploy the SPA on something like Netlify or Zeit's Now.)

**Comment by microcipcip** [comment]
Generate will actually create HTML files with the rendered Vue components in them, easily crawable by Google, Bing etc. Spa only, will allow browsing those pages in the exact sam way but the pages are not there, so you may have problems indexing your site.

**Comment by cschweda** [comment]
Thanks!

Okay -- so if that's the case, why would I want the '--spa' option? I mean, what does ```spa``` give me that ```nuxt generate``` doesn't?

Again -- my aim to have everything client rendered. No ssr.

**Comment by pi0** [comment]
> Again -- my aim to have everything client rendered. No ssr.

So you may simply want to use SPA mode :) Generate is for prerendered SSR websites to reduce hosting costs.

@cschweda

**Comment by cschweda** [comment]
Thank you!

Okay -- just so I'm clear: if I want to deploy on Netlify (or Zeit Now) -- then I should use the ```--spa``` flag (but not the ```generate``` option) and the configure the build so that everything is served from ```./dist```?
