### ISSUE TITLE
How can I use fontmin with Nuxt?

### ISSUE THREAD

**Issue by CKGrafico** [nuxt/nuxt.js#2473]
I've tried https://www.npmjs.com/package/fontmin-webpack im nuxt.config and I've tried to modify you builder using https://github.com/Jack-Sparrow/awesome-fontmin-loader but I'm still not able to use fontmin with nuxt configuration.

¿Did anyone tried that?

**Comment by clarkdo** [comment]
Currently nuxt is using `url-loader` as fonts loader, so you need to replace it with `awesome-fontmin-loader`

```js
module.exports = {
  build: {
    extend(config, { isDev }) {
      const fontLoader = config.module.rules.find((loader) => {
        return loader.loader === 'url-loader' && loader.test.exec('.woff2')
      })
      fontLoader.loader = 'awesome-fontmin-loader'
      fontLoader.options = {
        text: 'FOOBAR',
        limit: 1000, // 1 KO
        name: 'fonts/aw-[name].[hash:7].[ext]'
      }
    }
  }
}

```

**Comment by CKGrafico** [comment]
Yep I did something similar but I prefer your solution :)
