### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by billcccheng** [nuxt/nuxt.js#2474]
So I am the unlucky one who has to work on Christmas holidays and now nuxt has given up on me too :cry: 

![image](https://user-images.githubusercontent.com/10455095/34423486-f205e002-ebe1-11e7-8357-9db674799950.png)

**Comment by Gomah** [comment]
You can still find the documentation to the nuxtjs.org's repository: https://github.com/nuxt/nuxtjs.org

**Comment by anthonycook** [comment]
For a quick fix, Google also has cached versions. Hopefully it's back up soon.

![capture](https://user-images.githubusercontent.com/898094/34423789-64d13ce2-ec16-11e7-93b9-a49abf77f8fe.PNG)

**Comment by zikeji** [comment]
Nuxt appears to be hosted by Zeit, which is having some trouble. https://twitter.com/zeit_status/status/946482670263062528

**Comment by pi0** [comment]
Nuxt website is up :) Thanks for the reports.

https://nuxtjs.org
