### ISSUE TITLE
Unexpected token: punc ())

### ISSUE THREAD

**Issue by see311** [nuxt/nuxt.js#2475]
nuxt : 1.0.0-rc11
when I use vue-notifications, and this plugin needs another plugin mini-toastr.
```javascript
import Vue from 'vue'
import VueNotifications from 'vue-notifications'
import miniToastr from 'mini-toastr'
miniToastr.init()
function toast({ title, message, type, timeout, cb }) {
  return miniToastr[type](message, title, timeout, cb)
}
const options = {
  success: toast,
  error: toast,
  info: toast,
  warn: toast
}
Vue.use(VueNotifications, options)
```
after run 'npm run build',
```
ERROR in app.d9d8e7276f8cb0e2caa3.js from UglifyJs
Unexpected token: punc ()) [./node_modules/mini-toastr/mini-toastr.js:12,0][app.d9d8e7276f8cb0e2caa3.js:936,14]
```
I think it's the mini-toastr used some ES6 syntax which needs babel.
How can I add mini-toastr into babel-loader config?

**Comment by KyleTryon** [comment]
I just ran into the same issue 
https://github.com/nuxt/nuxt.js/issues/2468

Actually dealing with another issue now. I hope all these issues are my own.

**Comment by see311** [comment]
@KyleTryon 
Have you solved this problem?

**Comment by clarkdo** [comment]
@see311 
You can put `mini-toastr` into `vendor` for enable babel processing.

Or include the dependency in babel plugin https://github.com/nuxt/nuxt.js/issues/1668#issuecomment-330510870

**Comment by rossma** [comment]
Putting mini-toastr into vendor or/and including the dependency in the babel plugin. I might be doing something wrong as I don't fully understand what the configuration is doing. This is what I tried:

Exclude based on link mentioned above:
```
config.module.rules.push({
  test: /\.js$/,
  loader: 'babel-loader',
  exclude: function(modulePath) {
    return /node_modules/.test(modulePath) &&
        !/node_modules\/mini-toastr/.test(modulePath);
  },
  options: Object.assign({}, this.babelOptions)
})

```
or ... include?

```
config.module.rules.push({
  test: /\.js$/,
  loader: 'babel-loader',
  include: function(modulePath) {
    return /node_modules/.test(modulePath) &&
        !/node_modules\/mini-toastr/.test(modulePath);
  },
  options: Object.assign({}, this.babelOptions)
})

```
What did work for me was disabling the UglifyJsPlugin and installing uglifyjs-webpack-plugin:

```
const UglifyJSWebpackPlugin = require('uglifyjs-webpack-plugin')
config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJsPlugin')
config.plugins.push(new UglifyJSWebpackPlugin())

```

#1668 
#385

**Comment by pi0** [comment]
Maybe this is not the answer but you can also try [vue-toasted](https://github.com/shakee93/vue-toasted) it has also a [nuxt module](https://github.com/nuxt-community/modules/tree/master/packages/toast) for easy integration.

**Comment by rossma** [comment]
thanks @pi0 I tried that out too and it works. I think I will use vue-toasted from now on
