### ISSUE TITLE
npm run dev works great. Generate is deleting components from DOM after the page loads?

### ISSUE THREAD

**Issue by KyleTryon** [nuxt/nuxt.js#2477]
I have my static site temporarily hosted here to show the issue:
https://vibrant-hamilton-ce6e1c.netlify.com/blog/

My project: https://github.com/KyleTryon/VidFireBlog

my default.vue layout file looks like this, very simple.

```
<template>
  <div id="app-container">
    <vf-header/>
    <vf-nav/>
    <nuxt/>
    <vf-footer/>
  </div>
</template>
```

Everything works as expected on the dev server. However you can see if you visit the url above, the Header and Nav render and then delete themselves immediately.

There are no errors in console, and in the inspector, you can see the dom elements are actually completely removed.

**Comment by KyleTryon** [comment]
If you disable javascript, the CSS is a little messed up but the elements stay on the page.

**Comment by hanjeahwan** [comment]
I solve it with disable Cloudflare's minify but i dont know you have use it or not

**Comment by KyleTryon** [comment]
@hanjeahwan the issue happens locally. It doesnt seem like the generated files are actually static as they should be.

**Comment by neonerd** [comment]
This can happen if the generated HTML mismatches the JS rendered HTML. You have probably experienced it even when running "npm run dev" (Child nodes mismatching message in console), but sometimes it only seems to happen in generated files.

Check if you don't have any improperly nested tags (usually block elements in inline, for example having an "<ul>" inside "<a>" or "<nuxt-link>", etc.).

**Comment by KyleTryon** [comment]
@neonerd Great call! with that, I was able to identify which component was causing the issue and correct it. The items no longer vanish. 

However. I see now, the CSS is damaged in the static version. Again, rendering beautifully in developer mode. I don't suppose you know any more secrets? Might scoping have anything to do with it?

**Comment by KyleTryon** [comment]
Nuxt 1.1.1 automatically corrected the issue.

**Comment by zapnap** [comment]
I'm still having this issue as of v1.4.x. Is there any way to easily identify what components are causing the problem? Everything renders absolutely fine using the local server (`nuxt` / `npm run dev`)
