### ISSUE TITLE
why nuxt use memory so big?

### ISSUE THREAD

**Issue by frizadiga** [nuxt/nuxt.js#2479]
when I run ```npm run dev``` nuxt consume memory around 100-450 MB is it normal?

**Comment by christophwolff** [comment]
Yes. It is the development environment. For me it is around the same.

**Comment by ishitatsuyuki** [comment]
It's normal in the modern JS/webpack world. Under 500MB is quite good compared to other frameworks.

**Comment by clarkdo** [comment]
It because `webpack-dev-middleware`  handles files in memory by using `memory-fs` as files system, so all bundles and webpack compilation related files are all stored in memory.

For production, we recommend you use `nuxt build & start` instead of `dev`.
