### ISSUE TITLE
vue + jsx, webpack hot reload issue

### ISSUE THREAD

**Issue by PavelPolyakov** [nuxt/nuxt.js#248]
Hi,

I had the next case today.
Here is my module:
```javascript
<script>
    import Currency from '~components/currency.vue';

    export default {
        props: ['installment'],
        computed: {
            classObject: function () {
                return {
                    'alert-danger': this.installment.status === 'DUE',
                    'alert-success': this.installment.status === 'PAID',
                    'alert-info': this.installment.status === 'PENDING'
                };
            }
        },
        methods: {
            async pay () {
                this.$store.commit('PAY_INSTALLMENT');
                this.$store.commit('SET_STATUS', 'CONFIRMED');
            }
        },
        render(h) {
            return (
                    <div class={{ ...{ 'alert': true, 'col-md-2': true }, ...this.classObject }}>
                        {this.installment.label}
                        <Currency value={this.installment.amount}></Currency>
                        { this.installment.status === 'DUE' ?
                                <input class="btn btn-default" type="button" onClick={this.pay} value="Pay"/> : '' }
                    </div>
            )
        }
    }
</script>

```

After, I've updated the `classObject` function. At the browser console it says:
![image](https://cloud.githubusercontent.com/assets/839290/22891380/7b882f88-f20f-11e6-9c49-b4deed2d1a9f.png)

However, the actual application was not updated. I need to refresh the page. I have no idea if it could be "fixed" somehow, but it would be really nice to have the hot reload for the `jsx` applications.

**Comment by dohomi** [comment]
@PavelPolyakov I think not only on `.jsx` files this happens, also in `.vue` files. I experience after the last release on added middleware that I have to stop/start the `npm run dev` very often, even if I only change some minor code inside a method or computed property inside of my pages/components. @alexchopin is this something you experienced as well?

**Comment by Atinux** [comment]
It will be fixed in the next release.

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋

**Comment by nadilas** [comment]
Hi,

I just had the same issue with `1.0.0-rc3`. If I change the content within the `<template>` I get the following log in the browser:
```
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 964ms
[HMR] Checking for updates on the server...
[HMR] Nothing hot updated.
[HMR] App is up to date.
```

Regardless what I change in the .vue file I have to restart `npm run dev` manually.

Any ideas?
