### ISSUE TITLE
Hot reloading doesn't work in docker container on Windows

### ISSUE THREAD

**Issue by ArStah** [nuxt/nuxt.js#2481]
Nuxt works good in docker container, but hot reloading on Windows doesn't work. On linux everything is okay.

**Comment by rolandboon** [comment]
Actually, this is not an issue/bug for Nuxt.js, but has to do with file system differences and file change notifications on Windows to the Webpack dev package. (Google _HMR Docker Windows_ for tons of issues)

To tackle this issue enable file polling on the dev middleware in `nuxt.config.js` by adding:
```
watchers: {
  webpack: {
    poll: true
  }
}
```

See https://nuxtjs.org/api/configuration-watchers

**Comment by ArStah** [comment]
Ok, thanks, will try

**Comment by ArStah** [comment]
Yep, it works, thanks
