### ISSUE TITLE
dev branch Vue-apollo not working

### ISSUE THREAD

**Issue by Lahori-Jawan** [nuxt/nuxt.js#2484]
I followed the dev branch setup and this is what i have
**nuxt.config.js**
```
module.exports = {
  modules: ["@nuxtjs/apollo"],
  apollo: {
    clientConfigs: {
      default: "~/apollo/client-configs/default.js",
      test: "~/apollo/client-configs/test.js"
    },
    networkInterfaces: {
      default: "~/apollo/network-interfaces/default.js"
    }
  }
};

```
package.json

```
{
  "dependencies": {
    "@nuxtjs/apollo": "^3.0.0",
    "apollo-cache-inmemory": "^1.1.4",
    "apollo-client": "^1.9.3",
    "apollo-link-http": "^1.3.2",
    "graphql": "^0.12.3",
    "graphql-tag": "^2.6.1",
    "isomorphic-fetch": "^2.2.1",
    "nuxt": "^1.0.0-rc11",
    "vue-apollo": "^3.0.0-alpha.2"
  },

"devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1"
  }
}
```
and when I run 'npm run dev' it complains about  
`Error: Cannot find module 'E:\Web\Practical\Front-End\html\node\graphQL\nuxt-graph\nuxtjs\apollo'`
and 
`these dependencies are not found 
~/apollo/queries/allCars, ~/apollo/queries/car
To install them, you can run: npm install --save ~/apollo/queries/allCars ~/apollo/queries/car
`

further...
![2017-12-31_1954](https://user-images.githubusercontent.com/7579344/34462391-9e3175e2-ee64-11e7-994f-3c7145611835.png)

my first point of frustration is that how come it cannot find the apollo module?

**Comment by Lahori-Jawan** [comment]
After I removed/re-installed the node_modules, the `apollo` module is being recognised now although the second problem still persists i.e. `To install them, you can run: npm install --save ~/apollo/queries/car ~/apollo/queries/allCars`

**Comment by DanjBethel** [comment]
@Lahori-Jawan Any chance you can remember how you fixed this? Hacing the exact same issue..
