### ISSUE TITLE
Href routing behaving differenty in server rendered vs static generated

### ISSUE THREAD

**Issue by Mei152** [nuxt/nuxt.js#2485]
I am not sure if this is an issue, or if I am doing something wrong (very likely). 

I am using a dynamic href which resides in pages/our-fleet/index.
    `<a v-bind:href="machine.route"><img v-bind:src="machine.photoUsingRequire" alt="" /></a>`

Pages folder looks like this:

```
pages
   |
   our-fleet
        |
        KVM-23-4.vue
        index.vue
```

An href of "KVM-23-4" works in generated app deployed to Netlify, but gets a 404 in dev.

An href "our-fleet/KVM-23-4" works in server rendered in dev, but gets a 404 in generated app deployed to Netlify.

**Comment by clarkdo** [comment]
Can you please provide a repo ?

**Comment by Mei152** [comment]
@clarkdo  I just sent you an invite to be a collaborator for the repo as it is private.
Look in pages/our-fleet/index.vue, line 14.  I switch the `v-bind:src` between `machine.route` and `machine.staticRoute` depending on if I am working in local dev mode, or deploying static site to Netlify.
`machine.route`  and `machine.staticRoute` are coming from data/fleet.js.

I really do appreciate your checking this out!!

**Comment by clarkdo** [comment]
How about to use absolute path in both staticRoute and route ?

```js

var Fleet = {
  equipment: [
    {
      name: 'KVM 23-4',
      route: '/our-fleet/KVM-23-4',
      staticRoute: '/our-fleet/KVM-23-4',
      routeParam: 'KVM-23-4',
      photoUsingRequire: require('../assets/images/_pages/_page_fleet_kvm-23-4.jpg')
    }
  ]
}
```

**Comment by Mei152** [comment]
That "absolutely" works!
Do you consider it to be a workaround, or is that the way I should have done it in the first place?

**Comment by Mei152** [comment]
Thank you @clarkdo !
