### ISSUE TITLE
webpack run twice ?

### ISSUE THREAD

**Issue by nannan9507** [nuxt/nuxt.js#2489]
I found a situation that I wrote a webpack plugins OpenBrowserPlugin,
but when the server start, there are two windows were opened in my chrome browser,

anyone can teach me how to open one window for the setting ?

**Comment by clarkdo** [comment]
Your plugin may be added to both in client and server building.

Try to use `build.extend` to add server-only plugin.

```js
module.exports = {
  build: {
     extend (config, { dev, isServer }) {
       if (isServer) {
         config.plugins.push(...)
       }
     }
  }
}
```

**Comment by nannan9507** [comment]
Oh, thank you a lot, I will try. Thanks again

**Comment by zhouyu1993** [comment]
``` js
extend (config, { isServer }) {
 console.log(isServer) // It did print two times
}
```

**Comment by clarkdo** [comment]
@zhouyu1993 
Two times are client and server building. If you only want do sth when server building, just:

```js
extend (config, { isServer }) {
  if (isServer) {
    // ...
  }
}
```

**Comment by zhouyu1993** [comment]
@clarkdo you are right !
