### ISSUE TITLE
i18n example not working as expected

### ISSUE THREAD

**Issue by dennisbaum** [nuxt/nuxt.js#249]
hey guys,
tnx a lot for all this great work with nuxt! 

looking at the multilanguage example i18n with middleware, i get some strange behavior:
after cloning the nuxt.js repo, cd examples/i18n, npm install, npm run dev, the page is showing on localhost:3000 - but unfortenetly this route shows a 404-Error-Page below the working nav.
on localhost:3000/about it shows the home template - not the about template??
the french version works.  localhost:3000/fr/ shows the french home, localhost:3000/fr/about shows the french about-template.

on the demo page https://i18n.nuxtjs.org/ it works fine.

osx 10.11.6
node v7.4.0
latest chrome (german)

does ne1 else have this problem?
also i would like to know if it is possible to translate the french routes/slug?

Tnx, Dennis

<img width="746" alt="bildschirmfoto 2017-02-13 um 17 44 27" src="https://cloud.githubusercontent.com/assets/562826/22892989/b435a540-f214-11e6-9aff-1a4819494f2f.png">

<img width="735" alt="bildschirmfoto 2017-02-13 um 17 49 50" src="https://cloud.githubusercontent.com/assets/562826/22893048/e5572432-f214-11e6-87b1-171b2c845325.png">

**Comment by alexchopin** [comment]
Hi, 
This is due to the new release 0.9.9 and the routes order patch, so the example was up to date.
I have updated the example now, it should work with the new example.
