### ISSUE TITLE
How to re-route to default children using nested routes ?

### ISSUE THREAD

**Issue by commuzlyon** [nuxt/nuxt.js#2491]
Hi everyone and HNY,
For my website I'm trying to re-route people hitting the 'equipe' router-link (going to /equipe) in my navbar to the children nested page /equipe/2018, with this folder structure:

![capture du 2018-01-02 16-48-36](https://user-images.githubusercontent.com/34418711/34489483-ccb7a822-efdc-11e7-991a-fbb08d754ba3.png)

However I can't see how to do this, as I tried to extend routes but this replace the component and the parent, and reroute the "hard-way" with

```
created:
  function () {
    if (this.$route.fullPath == "/equipe") {
      this.$router.push("/equipe" + "/2018")
    }
  }
```
 does some strange bugs.

How can I keep the link to /equipe but redirecting everyone coming straight to this to /equipe/2018? Thanks a lot!

**Comment by clarkdo** [comment]
Try `redirect` in middleware https://nuxtjs.org/guide/routing#middleware.

```js
export default function ({ isHMR, app, store, route, params, error, redirect }) {
  if (route.fullPath.indexOf('/en') === "/equipe") {
    return redirect('/equipe/2018')
  }
}
```

**Comment by commuzlyon** [comment]
Thanks a lot ! didn't thought of middleware
