### ISSUE TITLE
Middleware is not running when page refresh (F5) or direct access

### ISSUE THREAD

**Issue by WeeHong** [nuxt/nuxt.js#2492]
The middleware works perfectly whenever the page redirect from one to another.
But when I tried to refresh the page or direct access to the page, the middleware is not running.

I run this middleware in `nuxt.config.js`

This is how I code my middleware,
```
nuxt.config.js

module.exports = {
  ...
  router: {
    middleware: ['check-auth', 'axios-header']
  }
}
```
```
axios-header.js

export default function ({ isServer, req, store }) {
    console.log('axios-header')
    if (isServer && !req) return
    const loggedUser = isServer ? getUserFromCookie(req) : getUserFromLocalStorage()
    if (loggedUser) {
        Axios.defaults.headers.common['authorization'] = `Bearer ${loggedUser}}`
    }
}
```

**Comment by clarkdo** [comment]
Did you use ssr mode? Middleware will be executed in server side when refresh due to ssr.

**Comment by WeeHong** [comment]
Hi @clarkdo 

I am not using SSR mode right now.

At least, I did not declare it in `nuxt.config.js`.

**Comment by clarkdo** [comment]
It's a default configuration (mode: universal).

https://nuxtjs.org/api/configuration-mode#the-mode-property

**Comment by Qlipoth** [comment]
clarkdo, why have you closed this issue?  Could you please clarify how to run middleware when i reload page F5?

**Comment by Qlipoth** [comment]
In my parent admin layout i use wather for router. also in the template section i use v-if to check my user role
`<template>
  <div id="app" class="wrap" v-if="$store.state.auth.account">
  ...
  </div>
</template>`

`    watch: {
      $route: {
        immediate: true,
        handler(to, from) {
          if (!this.$store.state.auth.account) {
            return this.$router.push('/');
          }
        }
      }
    },`
Is it correct to do like this?

**Comment by clarkdo** [comment]
@Qlipoth 
Can you please give more details and provide a repo can reproduce you problem ?

**Comment by tolyanor** [comment]
I have a similar problem. File _pages/posts/_id.vue_:

`<script>export default {

  async asyncData({ app, route, store, error }) {
  	let post = {}
  	route.params.id = route.params.id || 1
  	if (route.params.id) {
  		const p = await app.$axios.$get(`${process.env.apiUrl}/posts/${route.params.id}`)
    	        post = { post: p }	
  	} 
  	return post
  },

  scrollToTop: true

}</script>

<template>
	<div>
		<h1>{{post.title}}</h1>
		<div>
			{{post.body}}
		</div>
		post text id: {{$route.params.id}}
	</div>
</template>`

It's working good when I enter to this route from another app routes. But if I press F5 I not see dynamically loaded content. You can see my [nuxt.config.js](https://gist.github.com/tolyanor/ea77137f07d30d0249cdb89335ce8abb)

**Comment by RayBob1993** [comment]
`<template>
    <div>
        <article class="newsItem">
            <h1>{{ item.title }}</h1>
            <img class="img-fluid newsItem__image" :src="item.imageUrl">
            <div v-html="item.body"/>
        </article>

        <nuxt-link
            to="/news"
            class="el-button el-button--back">
            <i class="el-icon el-icon-arrow-left"/>Назад к списку новостей
        </nuxt-link>
    </div>
</template>

<script>
import { mapGetters } from 'vuex'

export default {
    async fetch ({ store, params }) {
        await store.dispatch('news/getItem', params.id)
    },
    layout: 'page_inner',
    head () {
        return {
            title: `${this.item.title} | Новости`
        }
    },
    computed: {
        ...mapGetters('news', [
            'item'
        ])
    }
}
</script>
`
Here is my example of a detailed news page. But I do not have any problems with what you described.

Here is the structure of news pages
`├── pages
	└──  news
	         └── index.vue
	         └── _id.vue`

**Comment by Qlipoth** [comment]
Hey guys, i figured out what was wrong. If you want to create auth route and you also wan to to handle SSR, you should create middleware file for current page or layout. At example i want my page could be watched only by admin and editor. I created middleware admin-access.js in middleware folder.
```
export default function(context) {
  var permittedRoles = ['Admin', 'Editor'];
  if (!context.store.state.auth.account || !_.includes(permittedRoles, context.store.state.auth.account.role)) {
    return context.redirect('/403');
  }
}
```
page:
```
<template>
  <div id="app" class="wrap">
  ...
  </div>
</template>

<script>
  export default {
    middleware: 'admin-access',
  }
</script>
```

**Comment by Hexodus** [comment]
@Qlipoth  This wont work on manual page refresh. Middleware in universal mode runs only on server on page refresh.
