### ISSUE TITLE
`fetch` method isn't called when also defined in mixins

### ISSUE THREAD

**Issue by hauleth** [nuxt/nuxt.js#2493]
This is surprising behaviour as by default Vue merge all functions from mixins with ones defined in component body.

**Comment by clarkdo** [comment]
I have tried as you described, it actually works for me.

```
//plugin.js
import Vue from 'vue'

Vue.mixin({
  fetch() {
    console.log('I am fetch') // eslint-disable-line no-console
  }
})

//nuxt.config.js
module.exports = {
  plugins: [
    '~/plugins/plugin.js'
  ]
}
```

The catch: first access will be server side rendering, so `I am fetch` will be printed in server console.

**Comment by hauleth** [comment]
Have you also created `fetch` method in your `page`? Because that was the problem, when there was `fetch` method in **both** places.

**Comment by clarkdo** [comment]
It's due to vue default merge strategy: https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies

> When custom options are merged, they use the default strategy which overwrites the existing value. If you want a custom option to be merged using custom logic, you need to attach a function to `Vue.config.optionMergeStrategies`
