### ISSUE TITLE
transition didnt work in nuxt generate mode

### ISSUE THREAD

**Issue by frizadiga** [nuxt/nuxt.js#2494]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2165">#c2165</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Could provide more details about this issue(such as: repo, codes and issue description)?

**Comment by frizadiga** [comment]
Here is the [repo](https://github.com/frizadiga/frizadiga.github.io) the pages transition work normally on `npm run dev` but doesnt work on `npm run generate` I hosted it on github pages

**Comment by galvez** [comment]
@frizadiga I'm unable to reproduze your problem. I ran `npm run generate`, then opened an HTTP server on `dist` with `python -m SimpleHTTPServer` and was able to see the transition happening.
