### ISSUE TITLE
Exclude js files from generated html files

### ISSUE THREAD

**Issue by silvio-e** [nuxt/nuxt.js#2495]
Hey! :)

I would like to create static html files which should not contain more then html and css. Javascript is not needed. Is it somehow possible to exclude all .js files?

Thanks for your help!

**Comment by clarkdo** [comment]
Use webpack `externals` together with `build.extend` to exclude the libs.

https://nuxtjs.org/faq/extend-webpack#how-to-extend-webpack-config-
https://webpack.js.org/configuration/externals/#externals

**Comment by silvio-e** [comment]
I'm not quite sure how to do it. I somehow understand how to exclude some dependencies, but not the complete bundle. Could you give me a hint for that too? Thanks a lot!
