### ISSUE TITLE
oauth2 

### ISSUE THREAD

**Issue by vaggelis2018** [nuxt/nuxt.js#2496]
I am building a project with nuxt and i want to provide an oauth2 register/login to users. I have already seen and example with nuxt from @Atinux in the following link  but if i am not wrong the client_id and secret are stored in the local storage and in the env variables which are accessible from both server and client side. I don't think that this is a good practice because anyone can grab them and use them.  Does anyone knows a way to store them in a more secure way?

Atinux oauth example.
https://github.com/nuxt/example-auth0

**Comment by shabushabu** [comment]
You don't store them client side. Create a proxy instead that fills in the client id and secret for the login request and then forwards that request to the oauth server. This assumes that you have just one global client for the password grant type. Now, a proxy might be as simple as a middleware on your API login route or it could be a standalone app. Up to you and what you need/prefer.

**Comment by vaggelis2018** [comment]
This is what i did at last. I was trying to find a easier solution but it seems that this is the only solution.
