### ISSUE TITLE
[Global css] Different css files for the same node module are ignored

### ISSUE THREAD

**Issue by hejianxian** [nuxt/nuxt.js#2498]
Hi.

This is my global css setting in `nuxt.config.js`: 

```js
{
 head...,
 css: [
    'mint-ui/lib/loadmore/style.css',
    'mint-ui/lib/datetime-picker/style.css',
    'mint-ui/lib/popup/style.css',
    'mint-ui/lib/picker/style.css',
    'mint-ui/lib/search/style.css',
    '~/assets/main.css',
  ],
 build...
}
```
After run build && run start, open the page in the browser, then, I found that in addition to the first css, the other is not injected.

```js
// Unpackaged css files
'mint-ui/lib/datetime-picker/style.css',
'mint-ui/lib/popup/style.css',
'mint-ui/lib/picker/style.css',
'mint-ui/lib/search/style.css',
```
This is my first time using `nuxt.js`, do I omit some settings?

```js
"mint-ui": "^2.2.13",
"nuxt": "^1.0.0-rc11",
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2169">#c2169</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
