### ISSUE TITLE
Vuex store defaulting to Modules mode?

### ISSUE THREAD

**Issue by liam-potter** [nuxt/nuxt.js#2499]
I have upgraded from rc11 to `@nuxtjs/next` (6f6a184) and my store no longer works - Nuxt complains:

> [nuxt] state should be a function in store/authentication/index.js

If I change `state` to a function in the `store/authentication/index.js` module then Nuxt defaults back to modules mode and as such things like a `login` action in my `authentication` module need to be called via `authentication/index/login` rather than just `authentication/login` like it should be.

I believe my `store/index.js` file is configured correctly for classic mode:

```js
'use strict'

import { Store } from 'vuex'

import authentication from './authentication'

export const store = () => new Store({
  modules: {
    authentication
  },
  actions: {
    nuxtServerInit () {
      // nothing here yet
    }
  }
})
```

**Comment by liam-potter** [comment]
I have just tried switching my store to modules mode and now Vuex does not pick up any modules at all:

````js
// store/index.js

import Vuex from 'vuex'

const store = () => new Vuex.Store({
  actions: {
    nuxtServerInit ({ commit }) {
      // nothing yet!
    }
  }
})

export default store
```

```js
// store/authentication.js

export const state = () => ({
  token: null
})

export const actions = {
  async login ({ commit }, credentials) {
    const { data } = await this.$axios.post('auth/login', credentials)
    commit('SET_TOKEN', data.token)
  },
  logout ({ commit }) {
    commit('CLEAR_TOKEN')
  }
}

export const mutations = {
  SET_TOKEN (state, token) {
    state.token = token
  },
  CLEAR_TOKEN (state) {
    state.token = null
  }
}

export const getters = {
  bearerToken: (state) => `Bearer ${state.token}`,
  authenticated: (state) => state.token !== null
}
```

**Comment by husayt** [comment]
Seems like state is not put under namespace as it is done for getters. It can be seen in vuex-store-modules example as well (see screenshot, below):
![image](https://user-images.githubusercontent.com/1169324/35623908-2a08da28-0685-11e8-825e-731efa078024.png)

**Comment by airjp73** [comment]
@liam-potter : I was under the impression that classic mode required you to use `export default` rather than `export const store`. I think that might be where your problem is.
```javascript
export default () => new Store(/*......*/)
```

@husayt : I believe this is correct behavior. I think the confusion is in naming your getter `todos`. The dev tools are showing that you have `todos/list` and `todos/todos(getter)` which returns `todos/list`. Is this how your module looks?

```javascript
todos: {
    state: {
        list: Array[1]
    },
    getters: {
        todos: (state) {
            return state.list
        }
    }
}
```

**Comment by liam-potter** [comment]
@airjp73 Yes, changing to `export default` fixed this. I figured this out a while ago but forgot to close the issue. Thank you, I'll close it now.

**Comment by husayt** [comment]
Thanks @airjp73 . I am not able to replicate that again. Seems you are right
