### ISSUE TITLE
Bug while back from error page.

### ISSUE THREAD

**Issue by SzymonLisowiec** [nuxt/nuxt.js#2500]
Hello,
I have two layouts in my project `default.vue` and `error.vue`. If i go to 404 page, and back to a previous page (using `router.go(-1)` or browser's button), layout do not change on `default` from `error`.

Roadmap:

1. I enter in home page (width of body is 100%)
2. I go to 404 page (width of body is 100vw)
3. I back to home page (width of body is 100vw)

**Comment by valeriosillari** [comment]
I have also a similar issue. jumping between the layout `default.vue `and the` error.vue` , it looks I lost/not-update some styles from one layout to the other

**Comment by SzymonLisowiec** [comment]
Today Nuxt V1.0 has been published and `error.vue` is loading to `default.vue` as content (`<nuxt/>` in `default.vue`).
