### ISSUE TITLE
failure eslint nuxt-class-component

### ISSUE THREAD

**Issue by pruge** [nuxt/nuxt.js#2504]
How do I use nuxt-class-component?
An error occurs in eslint.

Is there anything other than turning off the bottom?

```js
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2174">#c2174</a>)</em></sub></div>

**Comment by cesasol** [comment]
I think that you should use tslint instead, you know a typescript linter instead of a js linter

**Comment by manniL** [comment]
This questions can be answered on [CMTY](https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2174)
