### ISSUE TITLE
Can I use store in nuxt.config.js ?

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#2505]
I want to separate mobile or PC in nuxt.config.js, so can i use store in nuxt.config.js

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2175">#c2175</a>)</em></sub></div>

**Comment by manniL** [comment]
No, this is not possible
