### ISSUE TITLE
how to set cookie in middleware

### ISSUE THREAD

**Issue by zanjs** [nuxt/nuxt.js#2507]
middleware/auth.js

```js
export default function (context) {
 const token = context.route.query.token
  if (token ) {
     // Cookie.setToken(token).
  }
}
```

**Comment by EllenFawkes** [comment]
Try use this:

```javascript
export default function ({ isServer, res, query} ) {
 const token = query.token
  if (token) {
    if (isServer) {
      res.setHeader('Set-Cookie', [`access_token=${token}`]); // Server-side
    } else {
      document.cookie = `access_token=${token}` // Client-side
    }
  }
}
```

On server-side you must [set header to server's response](https://nodejs.org/api/http.html#http_request_setheader_name_value). On client set cookie via [document.cookie](https://www.w3schools.com/js/js_cookies.asp) or use [JS cookie library](https://github.com/js-cookie/js-cookie)

**Comment by zanjs** [comment]
@EllenFawkes Thinks! I like you very much！

**Comment by super-bobo** [comment]
is it work? do you have other methods？

**Comment by boicott** [comment]
hi @EllenFawkes  @zanjs  but, how to use it?

**Comment by jpt** [comment]
@boicott @super-bobo 

My approach is to use it as a Nuxt middleware, 

`middleware/cookies.js`:

```
export default function ({ req, res }) {
  
  // no req, no middleware!
  if(!req) return

  // no cookies, no middleware!
  if(!req.headers.cookie) return 

  if(process.server) {
    res.setHeader('Set-Cookie', req.headers.cookie)
  } else {
    document.cookie = req.headers.cookie
  }

}
```

And in `nuxt.config.js`:
```
...
  router: {
    middleware: 'cookies'
  },
...
```

Honestly I think something like this should be in the docs because it took me a little while to figure out

**Comment by microcipcip** [comment]
You can also use my little script [cookie universal nuxt](https://www.npmjs.com/package/cookie-universal-nuxt).
