### ISSUE TITLE
NuxtServerInit may be have a major problem

### ISSUE THREAD

**Issue by Wei12345** [nuxt/nuxt.js#2508]
Have a code
```
nuxtServerInit({ commit }){
    commit('setNumber', Math.random());
}
```
If there are two people at the same time online
Suppose they get 0.1 and 0.2 on the server
But they get the same value on the browser
When they use {{ number }}
They will show the same value
That is to compare the later one

**Comment by Wei12345** [comment]
I tested it, they happened
```
async fetch({ store }){
    await store.dispatch('mutation');
}

```

When there is a async fetch and await dispatch

**Comment by microcipcip** [comment]
Interesting. What happens if instead of `Math.random()` you try `Date.now()` ?

**Comment by Wei12345** [comment]
@microcipcip The same thing happens as described above

user1 get 1515430557563 on server
user2 get 1515430557657 on server
user1 and user2 get 1515430557657 on client ( browser )

This error happens when I use it `async/await fetch`
Because it wait

If used only `fetch`
Don't use `async/await`
It will be the correct data

But it should be usable `async/await fetch`
And get the correct data

**Comment by microcipcip** [comment]
I can't recreate your issue. My store/index.js is as follows:
```
const waitForMe = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve('Resolved'), 2000)
  })
}

export const state = () => ({
  authUser: null
})

export const mutations = {
  SET_USER: function (state, user) {
    state.authUser = user
  }
}

export const actions = {
  nuxtServerInit: async ({commit}, {app, req, redirect}) => {
    await waitForMe()
    const number = Math.random()
    console.log(number)
    commit('SET_USER', number)
  }
}
```

**Comment by Wei12345** [comment]
@microcipcip 
A single `nuxtServerInit` should be no problem
You can try adding the following in `index.vue`
```
async fetch(){
    await waitForMe()
},
mounted(){
    alert(this.number); // or console.log(this.number) or {{ number }} in template
},
computed(){
    ...mapGetters(['number'])
}
```
Then let two people connect at the same time
Maybe can reproduce my problem
You will get different data on the server side
You will get the same data on the client side ( browser )

**Comment by Wei12345** [comment]
@microcipcip 
I found a way to reproduce more easily
Your code
```
nuxtServerInit: async ({commit}, {app, req, redirect}) => {
    await waitForMe()
    const number = Math.random()
    console.log(number)
    commit('SET_USER', number)
}
```
Await after the commit
```
commit('SET_USER', number);
await waitForMe();
```
Then let two people connect at the same time
Maybe can reproduce my problem
You will get different data on the server side
You will get the same data on the client side ( browser )

**Comment by iarickvigasi** [comment]
+1 facing this issue

**Comment by msahajwani** [comment]
We are also facing the same issue. Server side the data is correct. But on client side, identical data is showing up for different users. Request you to please fix this at the earliest.

**Comment by microcipcip** [comment]
Probably @Atinux can have a closer look to this bug.

**Comment by henriquefurlan** [comment]
+1 same issue here

**Comment by Atinux** [comment]
Will investigate and fix it quickly

**Comment by clarkdo** [comment]
@Wei12345 
If the following codes are right way to reproduce the issue ?
```js
const waitForMe = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve('Resolved'), 2000)
  })
}

export const state = () => ({
  authUser: null
})

export const mutations = {
  SET_USER: function (state, user) {
    state.authUser = user
  }
}

export const actions = {
  nuxtServerInit: async ({commit}, {app, req, redirect}) => {
    const number = Math.random()
    commit('SET_USER', number)
    console.log(number)
    await waitForMe()
  }
}
```

I used the current `dev` branch and cannot reproduce it.

![image](https://user-images.githubusercontent.com/4312154/36294428-493b538a-12a6-11e8-805e-fb6d5164a75c.png)

Did I misunderstand the reproduce steps ? Please feel free to point it out 😄

**Comment by msahajwani** [comment]
Agree with @Wei12345 . This is exactly whats happening. For us, a user logged in from one location, and another user just visited the site within a few seconds from another location, and it was shown as logged in as the first user!!!

**Comment by Atinux** [comment]
I could not reproduce it Could you guys create a small repo on Github (or [Glitch](https://glitch.com/edit/#!/nuxt-hello-world))?

**Comment by Wei12345** [comment]
@Atinux 
I can not reproduce it in glitch
However, the local machine still have this problem
I guess the reason is because vuex store is shared on local server but not shared on glitch
The code

```
nuxtServerInit({commit}, {query}){
 if(query.test){
    commit('SET_USER', 'test')
}
```

on local server
Visit locahost:3000 // authUser is null
Visit locahost:3000/?test=test // authUser is test
Visit locahost:3000 // authUser is test

on [glitch](https://glitch.com/edit/#!/plume-brandy?path=store/index.js:29:40)
Visit glitch // authUser is null
Visit glitch/?test=test // authUser is test
Visit glitch // authUser is null

This bug on local server console
The following two simulates two users for the window
One is normal window and the other is traceless window

```
nuxtServerInit 2018-02-21T05:59:52.114Z // user1
0.29319009964039133
nuxtServerInit 2018-02-21T05:59:53.008Z // user2 get different data
0.9915702232298238
fetch 2018-02-21T05:59:59.420Z // user1
0.9915702232298238
fetch 2018-02-21T05:59:59.451Z // user2 get identical data
0.9915702232298238
mounted Wed Feb 21 2018 14:00:00 GMT+0800 (CST) // user1
0.9915702232298238
mounted Wed Feb 21 2018 14:00:01 GMT+0800 (CST) // user2
0.9915702232298238
```

This bug on [glitch](https://glitch.com/edit/#!/plume-brandy?path=store/index.js:29:40) console
The following two simulates two users for the window
One is normal window and the other is traceless window

```
nuxtServerInit 2018-02-21T06:03:53.869Z // user1
0.5868061494931875
nuxtServerInit 2018-02-21T06:03:56.523Z // user2
0.04613850368121164
fetch 2018-02-21T06:03:56.869Z // user 1
0.5868061494931875
fetch 2018-02-21T06:03:59.525Z // user 2
0.04613850368121164
mounted Wed Feb 21 2018 14:04:01 GMT+0800 (CST) // user 1
0.5868061494931875
mounted Wed Feb 21 2018 14:04:03 GMT+0800 (CST) // user 2
0.04613850368121164
```

I do not know if it helps you

**Comment by clarkdo** [comment]
![kapture 2018-02-22 at 21 08 33](https://user-images.githubusercontent.com/4312154/36540289-c076dd7a-1814-11e8-8daf-28ac40c8158b.gif)

**Comment by clarkdo** [comment]
![kapture 2018-02-22 at 21 10 35](https://user-images.githubusercontent.com/4312154/36540326-e25e8ffa-1814-11e8-83bc-734af8e494c8.gif)

**Comment by Wei12345** [comment]
@clarkdo 
Oh sorry
I reproduce this problem at [glitch](https://glitch.com/edit/#!/daisy-sing?path=store/index.js:10:0)
You will get this problem if you do the same thing
Is this my mistake?

Do not `const state` in `store/index.js` is no problem

**Comment by clarkdo** [comment]
@Wei12345 
The issue in you glitch should be caused by sharing `state` in `store/index.js`, you can move `state` into `createStore` for avoiding `store.state` being a shared object.

```js
import Vuex from 'vuex'

import getters from './getters'
import actions from './actions'
import mutations from './mutations'

const createStore = () => {
  const state = {
    authUser: null
  }
  return new Vuex.Store({
    state,
    getters,
    actions,
    mutations
  })
}

export default createStore
```

**Comment by clarkdo** [comment]
@msahajwani 
Does your `./state` export a object ? If so, you can change it to a function, such as:

```js
// state.js
export default () => ({
    authUser: null
})

//store.js
import Vuex from 'vuex'
import createState from './state'
import mutations from './mutations'
import actions from './actions/'
import getters from './getters'

const store = () => {
  const vuexStore = new Vuex.Store({
    createState(),
    mutations,
    actions,
    getters
  })

  // @TODO: Development
  if (process.browser) {
    window.store = vuexStore
  }
  return vuexStore
}

export default store
```

**Comment by msahajwani** [comment]
@clarkdo Thank you. I will try this solution and let you know if I still face the problem.

**Comment by Atinux** [comment]
Actually, it has to export a function to work and avoid a security issue (this is why when using Nuxt Store modules, we force the users to set state as a function)

**Comment by Wei12345** [comment]
Thank you all
