### ISSUE TITLE
Redirect after Store Action 

### ISSUE THREAD

**Issue by mattdharmon** [nuxt/nuxt.js#251]
I am having a hard time trying to redirect in method after a store action i.e. redirect to profile upon login, redirect to '/' upon logout.

I have tried the this.$router.go after awaiting the store dispatch, but no matter the route, it just renders the page.

Is there something I am doing wrong, or is this an enhancement that could be implemented?

P.S. I should say this is a framework, combined with express is actually making me happy to develop web applications again and I look forward to production ready release.

**Comment by mkv27** [comment]
Hi @mattdharmon, I'm using `this.$nuxt.$router.replace({ path: '/profile })` and it works fine. 
You also can use another of the vue router 2 instance methods:
https://router.vuejs.org/en/essentials/navigation.html

**Comment by alexchopin** [comment]
Already answered [here](https://github.com/nuxt/nuxt.js/issues/205)
