### ISSUE TITLE
dynamic attribute nuxt-link

### ISSUE THREAD

**Issue by tchret** [nuxt/nuxt.js#2510]
Is there a way to set dynamically attributes to `nuxt-link` (eq. for `to`)?
I'm getting a `Cannot read property 'name' of undefined` error

![1](https://user-images.githubusercontent.com/4539476/34616754-7073fde0-f239-11e7-80ad-7ca1ade45e76.png)
![2](https://user-images.githubusercontent.com/4539476/34616758-7178d634-f239-11e7-89f9-0653851fc6c4.png)

![image](https://user-images.githubusercontent.com/4539476/34616784-7fb3df1e-f239-11e7-98c8-bda42a8316b5.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2180">#c2180</a>)</em></sub></div>

**Comment by cesasol** [comment]
Beware of using single quotes for attributes on html, specially on vue, your html template should be like `<btn class="some-static-class" :class="[`some-dynamic-class${insideAnArray}`, anotherDynamicClass, 'a-static-class']" href="static-href">something</btn>` `<btn :href="'dynamic-href-with-hardcoded-string'">something</btn>`.

I would suggest you to use the [eslint plugin for vue](https://github.com/vuejs/eslint-plugin-vue)

**Comment by kelleysy** [comment]
@cesasol what if you have a var such as the baseurl... how do you concat in the single quote

**Comment by cesasol** [comment]
@kelleysy template literals:
```
some-prop="`somestaticstring${somevar}morestrings${morevars}`"
```

**Comment by manniL** [comment]
This is possible as usual with `v-bind` or `:`

```html
<nuxt-link :to="href">My Link</nuxt-link>
```

**Comment by majtom2grndctrl** [comment]
@manniL Take a closer look at the second screenshot in the OP. I am also noticing that using `v-bind` or `:` still results in this error using Nuxt 1.4.2 and Nuxt-edge, specifically when using the `generate` command. Dev SSR and client-side rendering seems to work as documented.

**Comment by manniL** [comment]
@majtom2grndctrl Can't reproduce this locally :|

If this bug still occurs, please open a new issue with a reproduction repository :wink:

**Comment by cesasol** [comment]
I'm not sure if this is a bug but I encounter this issue when the to atribute is undefined, and it is not an issue with nuxt-link, instead is by design on router-link

**Comment by manniL** [comment]
@cesasol If it's an issue with `router-link`, then you should probably create a bug report at https://github.com/vuejs/vue-router :relaxed:

**Comment by majtom2grndctrl** [comment]
@manniL In my attempt to reproduce, I found the bug was actually in my code, and I had misinterpreted what the error message was telling me. Thanks for your help!
