### ISSUE TITLE
only default layout styles rendered 

### ISSUE THREAD

**Issue by tonyrewin** [nuxt/nuxt.js#2511]
Hello!

I'm using *nuxt@next* and I'm not sure if nuxt build is working properly.<style lang="scss">... are ignored in different layouts then in *layouts/default.vue*. I did setup *layout* property for my page-component, but i still can see my styles applied only when I put them to default layout's style section.

**Comment by hadyanq** [comment]
Hi, I am currenlt having the same problem where only the default layout can see my global CSS. Have you figured out where the problem was? Any feedback would be really appreciated.

**Comment by titanXL** [comment]
@hadyanq u can set your global css in the nuxt.config file :)
