### ISSUE TITLE
document.body.scrollTop always returns 0 in Safari

### ISSUE THREAD

**Issue by davision** [nuxt/nuxt.js#2512]
Does anyone have an issue getting the scroll offset in Safari or iOS devices? 
This works perfectly in Firefox:

`this.scrollPosition = document.body.scrollTop`

but in Safari I'm always getting 0, no matter what. That happens only with Nuxt apps.

Thanks for your help!

**Comment by neonerd** [comment]
This is the correct way to get body scrollTop in modern browsers:

`
function getBodyScrollTop () {
const el = document.scrollingElement || document.documentElement
return el.scrollTop
}
`

This is not a nuxt related question though, so should be closed.

**Comment by davision** [comment]
Hey, thank you for your reply. I am aware that this shouldn't be Nuxt related, but as the thing is that your method works in plain HTML, but not as a Nuxt/Vue method. And I have no idea why. Asking, if anyone else had a similar problem.

**Comment by davision** [comment]
Ok, so I found out what is the issue. I had a css on body element, which prevents .scrollTop to get correct value. But interestingly, only in Safari. 
```
body {
  overflow-x: hidden;
}
```
The issue can be closed.

**Comment by lincenying** [comment]
```javascript
const scrollTop = Math.max(window.pageYOffset, document.documentElement.scrollTop, document.body.scrollTop)
```

**Comment by davision** [comment]
Thank you! This is very helpful!

**Comment by DearAKuan** [comment]
Have you solved it, please? I have the same problem.

**Comment by davision** [comment]
Yes, my problem was  `overflow-x: hidden` on a body element. Check, if you're having the same attribute.

**Comment by DearAKuan** [comment]
@davision  thanks    谢谢你 我再试下 ：）
