### ISSUE TITLE
Event before resources. DOMContentLoaded ?

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#2513]
Hi!

I want to adjust images setting on the client side. I cannot do it on server side because I do not know client screen resolution.

The problem is that both ```mounted()``` and ```window.onNuxtReady``` are triggered after all resources were loaded. Which is too late for me.

I guess I should use ```DOMContentLoaded``` but I am not sure how to do this with nuxt.

I need to tweak the images styles before the images are loaded to avoid content shifting on devices with slow connection.

Any suggestions? Thanks!

**Comment by cesasol** [comment]
I prefer to have a custom image, picture or figure component to do that, you can also use lazyload or have a predefined aspect ratio hack and 100% width for your images with css to "reserve" the space that it will be taking

**Comment by awronski** [comment]
@cesasol Thanks for the tips. I did a aspect ratio hack as described here:
https://www.smashingmagazine.com/2016/08/ways-to-reduce-content-shifting-on-page-load/
