### ISSUE TITLE
Using srcset and the path shortcut feature

### ISSUE THREAD

**Issue by anthonycook** [nuxt/nuxt.js#2515]
I'm trying to use response images via the srcset attribute and the path shortcut feature (e.g "~/assets/images/sample.jpg") I've added the appropriate loader in my Nuxt config as mentioned in #524 but can't seem to get it working.

Has anyone successfully used srcset using the shortcut feature?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2184">#c2184</a>)</em></sub></div>

**Comment by cesasol** [comment]
In my team we use this feature all the time with nuxt without any problem or weird tweak. Can you please share an example of your code?

**Comment by anthonycook** [comment]
Hi @cesasol , here's an example:

#### Loader in nuxt.config.js

```javascript
vue: {
  html: {
    query: {attrs: "img:src img:srcset"}
  }
}
```

#### IMG tag:

```html
<img src="~/assets/images/sample-small.jpg" srcset="~/assets/images/sample.jpg 800w, ~/assets/images/sample.jpg 480w">
```

Thanks!

**Comment by manniL** [comment]
This does work out of the box now.

[Production example](https://github.com/Developmint/developmint.de/blob/18ef75f63b58967d0567fd8a6802f0c26b7a9215/components/about-us/TeamMember.vue#L7)
