### ISSUE TITLE
Client re-renders data with SSR enabled and loses class info

### ISSUE THREAD

**Issue by CallMeFoxie** [nuxt/nuxt.js#2516]
Hi,

it seems that when there's some oddity or whatever (couldn't google anything nor find previous issues) with asyncData() call happening on the server - and rendering. But when the page finishes loading on the client all the data disappears because the data it uses were used from **getters** rather than just properties. Those are not transferred to the client (presumably due to JSON serializing the data). Is there any reasonable way around it because when it comes to an array (list) of objects it becomes incredibly messy.

We cobbled together a snippet like this, but it is unusable when it comes to array/map/whatever.
```javascript
 async asyncData ({ app, params }) {
    let user = await app.$api.users.fetchUser('@' + params.user)
    let color = colorize(user.login)
    return {
      _user: user.data,
      color,
      userLogin: params.user
    }
  },
  computed: {
    user () {
      return new User(this.$data._user)
    }
```

where the main User class is 
```javascript
class User extends Entity {
  get login () {
    return this._data.login || null
  }

  set login (val) {
    this._data.login = val
  }
... etc
```

We can see without the `computed` hack only the raw values without the underlying object so all the setters/getters get lost without manual recasting in the computed.

And no, SSR is there on purpose (so that googlebot/.. can actually index it). So what's the correct way to handle this?

Thanks in advance for any help.
Ashley

**Comment by EllenFawkes** [comment]
If i save `Map` to `state`, then I lost all data from map on client.

```javascript
<script type="text/javascript">window.__NUXT__={"layout":"default","data":[{"users"
{"_array":null,"_keyArray":null,"_meta":{"_status"
{"code":"OK","message":"ok"},"_httpStatusCode":200,"_httpHeaders":{"contenttype":"application\u002Fjson",
"date":"Sun, 07 Jan 2018 17:35:41 GMT","contentlength":"312",
"connection":"close"}}},"color":"brown darken1",
"userLogin":"Ashleynka"}],"error":null,"state":{},"serverRendered":true};</script>
```

**Server dump**
```javascript
Collection {
  '5a3bf8fd25a09c0c4cee22c7' => User {
  _data:
   { _id: '5a3bf8fd25a09c0c4cee22c7',
     _created: '2017-12-21T19:10:33.591+01:00',
     _modified: '2017-12-21T19:10:33.591+01:00',
     login: 'Ashleynka',
     name: '',
     activated: true,
     role: 'member' },
  _meta:
   MetaInfo {
     _status: [Object],
     _httpStatusCode: 200,
     _httpHeaders: [Object] } },
  _array: null,
  _keyArray: null,
  _meta:
   MetaInfo {
     _status: { code: 'OK', message: 'ok' },
     _httpStatusCode: 200,
     _httpHeaders:
      { 'content-type': 'application/json',
        date: 'Sun, 07 Jan 2018 17:35:41 GMT',
        'content-length': '312',
        connection: 'close' } } }
```

I lost my user array on client.

**Comment by CallMeFoxie** [comment]
I wonder if it is the same as this (sounds like it) https://github.com/nuxt/nuxt.js/issues/643

**Comment by husayt** [comment]
This seems to be resolved now. Closing. Reopen if still happens.

**Comment by CallMeFoxie** [comment]
Hi @husayt -- thanks for the info. Was it resolved on Nuxt side or Vue side or where? Thanks!

**Comment by husayt** [comment]
Last nuxt release resolved key issue with asyncdata, I guess that resolves it. If issue still happens please let know
