### ISSUE TITLE
Creating a Chat widget using Nuxt 

### ISSUE THREAD

**Issue by gijo-varghese** [nuxt/nuxt.js#2518]
I'm building a chat widget were my customers can grab an embed code and put in their website. 

Right now I've built it using normal vuejs project, with some modifications in webpack to generate a single js file (app.js) including the CSS. That 'apps.js' will create a div in website with ID "app" and then the Vue instance is injected into it. It works fine, but I would like to make it SSR so that initial load will be much faster.

Anyway to implement it in Nuxt? My server is built with GraphQL. So I use Apollo-nuxt module.

**Comment by Atinux** [comment]
Hi @gijo-varghese 

You could create a Nuxt.js module to integrate your widget with SSR. You can use https://github.com/nuxt-community/module-template to create your module easily.

**Comment by gijo-varghese** [comment]
@Atinux so its like integrate nuxt module to my existing vuejs project?

To be more clear what I give to my customers is a simple embeddable script (similar to the Google Analytics script) that will inject a script into customers website. Nuxt by default creating an entire site right?

**Comment by Atinux** [comment]
Oh I see @gijo-varghese 

You want to create a Vue.js plugin which is compatible with server-side rendering right?

Take a look at https://ssr.vuejs.org/en/universal.html, it will help you a lot to start

**Comment by gijo-varghese** [comment]
@Atinux I think there is a misunderstanding. Sorry that I couldn't express it properly. It will not be a vuejs plugin. It will be a js file which can be embedded in any website, whether the website is built with react, angular, vue, jquery anything
