### ISSUE TITLE
asyncData with router query in next tag call only once even query changed

### ISSUE THREAD

**Issue by Azeranex** [nuxt/nuxt.js#2519]
I try nuxt with next tag and found out that asyncData triggered only once. It's won't work when navigate with nuxt-link and $router.replace etc. 

/page?catagory=foo => /page?catagory=bar is not working

The only way to get it works it work is to use watch: $route

**Comment by phpedinei** [comment]
I have some problem with nuxt 1.0.0

**Comment by maxim25** [comment]
Seems like fetch no longer fires on route change and only on component load. Not sure if the former was a bug or not.

**Comment by macoshita** [comment]
Perhaps it's a new specification from 1.0.0

- https://github.com/nuxt/nuxt.js/commit/3d49d8d2905796f063b171fdd935da721622fe05
- https://github.com/nuxt/nuxt.js/issues/1255#issuecomment-343450873

**Comment by cesasol** [comment]
As a workaround maybe you can use computed propeties as a proxy

**Comment by DreaMinder** [comment]
for those who haven't found the solution - for 1.1.1 you just have to define your query params to watch in page component:
`watchQuery: ['service'.'page']`
