### ISSUE TITLE
Cannot find 'flavicon.ico' in '/some/emebedded/route/'

### ISSUE THREAD

**Issue by mattdharmon** [nuxt/nuxt.js#252]
I noticed that when having nested routes, assets are searched for in the same route in static, such as the flavicon.

Is there something I'm missing or is this a bug?

**Comment by alexchopin** [comment]
That's weird because our website have nested route and the favicon works without any issue.
Can you share us some screenshot or code example please?

**Comment by mattdharmon** [comment]
Here is the dev tools console log with the attached images. It only happens when it detects a new route, such as a new card id in the dynamic route.

![capture](https://cloud.githubusercontent.com/assets/3542342/22896648/8dc7eb6c-f1e6-11e6-9db3-fbb4e6157486.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3542342/22896646/8dc4cc8e-f1e6-11e6-951b-24e9aca4246a.PNG)
![capture3](https://cloud.githubusercontent.com/assets/3542342/22896647/8dc57742-f1e6-11e6-9346-b742c272f88e.PNG)

**Comment by alexchopin** [comment]
It should work by adding a slash before favicon.ico in your nuxt.config.js.
`{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }`

**Comment by mattdharmon** [comment]
It seems to not want to request the flavicon at all after those changes.

**Comment by app-sparkler** [comment]
@mattdharmon you might also want to include `router.base` in your `nuxt.config.js` file:

```
...
router: {
  base: '/'
}
...
```

Reference : https://github.com/nuxt/nuxt.js/issues/239
