### ISSUE TITLE
vuex mapGetters not working.

### ISSUE THREAD

**Issue by edDimensi** [nuxt/nuxt.js#2526]
I get error when i try use mapGetters
![screenshot_20180109_011113](https://user-images.githubusercontent.com/11390039/34694958-ff7b3916-f4d9-11e7-9f12-0942b5d9c231.png)

My store/index.js
```
import Vuex from 'vuex'
import modules from './modules'

export default () => {
  return new Vuex.Store({
    modules
  })
}
```
store/modules/index.js
```
import homePage from './homePage'

export default {
  homePage
}
```
store/modules/homePage.js
```
import getApi from '@/plugins/prismicApi'
import { GET_HOME_PAGE } from '../mutationTypes'

const state = {
  homePage: null
}

const getters = {
  homePage: state => state.homePage
}

const actions = {
  async getHomePage ({ commit }) {
    const api = await getApi()
    const homePage = await api.getSingle('home_page')
    commit(GET_HOME_PAGE, homePage.data)
  }
}

const mutations = {
  [GET_HOME_PAGE] (state, payload) {
    state.homePage = payload
  }
}

export default {
  state,
  getters,
  actions,
  mutations
}
```
I do not want namespaced modules, so I use this way of defining modules.
I try set namespaced: false, but it's not help.
And now my index.vue
```
 import { mapGetters } from 'vuex'

export default {
  name: 'index',
  async fetch ({ store }) {
    return store.dispatch('getHomePage')
  },
  computed: {
    ...mapGetters('homePage')
  }
}
```

**Comment by gangsthub** [comment]
maybe you are hitting with `homePage.data` when `homePage === null`. Why not setting it up at the beginning with:

```
homePage: { data: null }
```

? (just an idea)

**Comment by edDimensi** [comment]
i not call homePage.data, in screenshot problem in mapGetters, not in me

**Comment by gangsthub** [comment]
in your actions, `getHomePage` will commit the homePage.data value

**Comment by edDimensi** [comment]
and?

**Comment by edDimensi** [comment]
oh god, stupid mistake...
i must put `['homePage']`, not `homePage`

**Comment by gangsthub** [comment]
in your `...mapGetters(['homePage'])`, yeah, missed that one too. 😉
