### ISSUE TITLE
context.isClient and context.isServer deprecation warnings when not used

### ISSUE THREAD

**Issue by joealden** [nuxt/nuxt.js#2527]
I have just upgrade nuxt to 1.0.0 in one of my projects and I am getting the following warnings every time a page is server side rendered (Both in the server console and on the client):

```
context.isClient has been deprecated, please use process.client instead.
context.isServer has been deprecated, please use process.server instead.
```

From my understanding from these release notes,
 (https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0) I can still use the context.isClient property inside build.extend(), as this is said:

> We also deprecated `dev` property inside `build.extend()` in flavour of `isDev`.

(Little side note, this should say 'in favour' instead of 'in flavour')

If what I think is correct, then I am not using these deprecated APIs in my code, but the warning as still appearing.

Could these warnings maybe be coming from a nuxt module that is still using the deprecated API? (Like what happens when a package you depend on is not using babel-present-env)

**Comment by joealden** [comment]
I forgot to add, this is the repo of the codebase: https://github.com/joealden/corum

**Comment by Evild67** [comment]
Update your nuxt/apollo package to 3.0.1 :) ! Deprecation fix was just merged

**Comment by dohomi** [comment]
true :-)

**Comment by gangsthub** [comment]
You are using (config) `isClient` in:

https://github.com/joealden/corum/blob/89444838c18509132873e063e5fb2f283dfcfae6/nuxt.config.js#L29

**Comment by joealden** [comment]
@Evild67 Thanks! That has fixed it!
