### ISSUE TITLE
Debugging Nuxt Project

### ISSUE THREAD

**Issue by ShaunCurtis** [nuxt/nuxt.js#2528]
Debugging and interacting with a Vue project page is relatively simple with standard Vue, but I can't find any information on doing it in Nuxt.  The only article I can find - https://codeburst.io/debugging-nuxt-js-with-visual-studio-code-724920140b8f - doesn't work for a nuxt scaffolded project with bootstrap-vue.  I would like to use Nuxt instead of what I call standard Vue, but without a viable debugging process, it's back to basic Vue.

**Comment by hendrysadrak** [comment]
Chrome extension "Vue.js devtools" works with Nuxt.

**Comment by ShaunCurtis** [comment]
Thanks,
I spent a frustrating couple of days trying to sort out some issues on an application I wrote initially in plain Vue, but then moved to Nuxt.  I took a step back today, sorted out what goes on where with the Nuxt framework - server side and client side - and therefore what you debug in node and what in the browser.  Probably needs some better documentation on how to debug - might give it go when I get thro!

**Comment by rlam3** [comment]
@ShaunCurtis Looking forward for your debugger documentation. Any updates? Thanks!

**Comment by vordimous** [comment]
currently got it working by following that article a little bit.
```
{
        "type": "node",
        "request": "launch",
        "name": "Launch via NPM",
        "runtimeExecutable": "npm",
        "runtimeArgs": [
          "run-script",
          "dev-debug"
        ],
        "port": 9229
      }
```
```
"dev-debug": "node --inspect node_modules/.bin/nuxt"
```

**Comment by sobolevn** [comment]
@vordimous does it work with `.vue` files? D breakpoint inside your `vscode` work?
If so, can you please share a reproducible repo? I have spent the whole day trying to make it work.

**Comment by vordimous** [comment]
I was not able to get breakpoints to work. that config got the app to start and run in the vscode debugger;
