### ISSUE TITLE
Error loading files after update to 1.0.0

### ISSUE THREAD

**Issue by CKGrafico** [nuxt/nuxt.js#2529]
I've updated to nuxt 1.0.0 without changing my code and I have this error

```
ERROR in ./node_modules/ts-loader?{"appendTsSuffixTo":[{}]}!./node_modules/nuxt/node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/_lang/serviceworker.vue
Module not found: Error: Can't resolve '~/store/modules/serviceworker' in 'C:\Projects\Microsoft\PWABuilderVue\pages\_lang'
 @ ./node_modules/ts-loader?{"appendTsSuffixTo":[{}]}!./node_modules/nuxt/node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/_lang/serviceworker.vue 61:0-63
 @ ./pages/_lang/serviceworker.vue
```

Any idea that why is it happening? That was working before:
The import is like:

```

import * as serviceworker from '~/store/modules/serviceworker';
```

**Comment by Andrei997** [comment]
Same problem here
`Module not found: Error: Can't resolve '@/assets/css/my/sass' in '/app/.nuxt'`

**Comment by Andrei997** [comment]
Same problem here when running in dev-mode. 
Building for production also fails.
`exports.waitFor = async function waitFor(ms) {
SyntaxError: Unexpected token function 
...
`

**Comment by CKGrafico** [comment]
This is the solution:

1.- If you dind't upgrade to node >8 do it please
2.- Change your `modules/typescript.js` to the updated file https://github.com/nuxt/nuxt.js/blob/dev/examples/typescript/modules/typescript.js (yes, has small differences, [compare with](https://github.com/nuxt/nuxt.js/blob/3e637c5d83028f6671ed0edf10b813dae523b347/examples/typescript/modules/typescript.js))
