### ISSUE TITLE
Error when updating Nuxt 1.0.0

### ISSUE THREAD

**Issue by feedgit** [nuxt/nuxt.js#2531]
Sorry but I got this error when updating Nuxt 1.0.0. 

I use `npm run dev` and got this error:

```
C:\Users\User\Desktop\FeedGit\frontend\node_modules\nuxt\lib\common\utils.js:25
exports.waitFor = async function waitFor(ms) {
```

This is my all dependencies in package.json:

```
"dependencies": {
    "@nuxtjs/router": "^1.0.1",
    "axios": "^0.17.1",
    "body-parser": "^1.17.2",
    "bootstrap-vue": "^1.0.0-beta.9",
    "core-js": "^2.5.1",
    "cropperjs": "^1.2.2",
    "emoji-mart-vue": "^1.0.2",
    "express": "^4.15.4",
    "ieee754": "^1.1.8",
    "js-cookie": "^2.1.4",
    "jwt-decode": "^2.2.0",
    "nuxt": "^1.0.0",
    "postcss-cssnext": "^3.0.2",
    "quill": "^1.3.3",
    "quill-image-drop-module": "^1.0.3",
    "style-loader": "^0.18.2",
    "svg-inline-loader": "^0.8.0",
    "underscore": "^1.8.3",
    "vue-clickaway": "^2.1.0",
    "vue-infinite-loading": "^2.2.1",
    "vue-multiselect": "^2.0.8",
    "vue-notifyjs": "^0.2.0",
    "vue-quill-editor": "^3.0.4",
    "vue-resource": "^1.3.4",
    "vue-style-loader": "^3.0.3",
    "vue-svgicon": "^2.1.1",
    "vue-timeago": "^3.3.6",
    "vue-upload-component": "^2.7.3"
```

**Comment by yoyo837** [comment]
Hi, what error message does it report?

**Comment by feedgit** [comment]
```
C:\Users\User\Desktop\FeedGit\frontend\node_modules\nuxt\lib\common\utils.js:25
exports.waitFor = async function waitFor(ms) {
```

This is error, yoyo!!

**Comment by yoyo837** [comment]
@feedgit What is the version of your node?

**Comment by feedgit** [comment]
@yoyo837 Now is 6.11.0, bro

**Comment by yoyo837** [comment]
@feedgit See [v1.0.0 Breaking changes](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0). Minimum Node.js version required for Nuxt.js is also increased to 8.0.0 (Current LTS) to support async/await(node v7.6+) function.

**Comment by feedgit** [comment]
Thanks for your help. Can I ask you if i update NodeJS, any package in my node could come to error?

**Comment by yoyo837** [comment]
Emmmm... It should not, but you'd better check the` README.md` for the dependent package or try it yourself.

**Comment by feedgit** [comment]
Thank you again @yoyo837

**Comment by maziarz** [comment]
I wish that nuxt would check up against "node --version" and drop an exception. I had the same problem, even though my package.json was set to the rc and not final release. It becomes quite tedious in production to narrow down such problems. Besides that, good job with the release! 👍
