### ISSUE TITLE
Avoid using non-primitive value as key, use string/number value instead. (v. 1.0.0)

### ISSUE THREAD

**Issue by maxim25** [nuxt/nuxt.js#2532]
Since updating to 1.0.0 I get the following error:

> [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
>
> (found in \<Root\>)

It only appears when I set the layout property on a non root path page. E.g. for 'pages/login.vue', however the error does not appear for 'pages/index.vue' . 

I tried to deduce what could be causing it, but even when the layout is as basic as it gets the error persists:

_pages/login.vue_
```
<template>
  <div>
    Hello World
  </div>
</template>

<script>
  export default {
    layout: ['navAndFooter']  // Deleting this line fixes the error
  }
</script>
```

_layouts/navAndFooter.vue_
```
<template>
  <div>
    <nuxt/>
  </div>
</template>

<script>
  export default {}
</script>
```

**Comment by clarkdo** [comment]
Use `layout: 'navAndFooter'` instead of `layout: ['navAndFooter']` .
