### ISSUE TITLE
How to upgrade to v1 from starter template rc11

### ISSUE THREAD

**Issue by lanbau** [nuxt/nuxt.js#2534]
Hi is there a clean way to upgrade to v1 from the previous starter template rc11?
My guess is to change nuxt version to "nuxt": "^1.0.0" in package.json and run npm install. 
Do correct me if i'm wrong.

**Comment by pi0** [comment]
Hi. There are some breaking changes from rc11 to 1.0.0. But normally there isn't  any changes necessary for this upgrade. See [release notes](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0).
