### ISSUE TITLE
How can I use store data in head method

### ISSUE THREAD

**Issue by binggg** [nuxt/nuxt.js#2536]
For example, There is a page just like '/movie/_id.vue'.

Before render this page, I must fetch the data of this movie. And I wan't save the data in store. Otherwise I wan't my page's head is the movie title for SEO.

Here is the question:

If I fetch data in `fetch` method,  I can't reach the movie data in `head` method.
If I fetch data in `asyncData`method, I can't save the data in my store.

**Comment by NicoPennec** [comment]
You want something like that, right?

```js
export default {
  head () {
    return {
      title: `movie - ${this.movie.title}`
    }
  },
  async asyncData ({ params, store }) {
    let { data: movie } = await axios.get(`/api/movie/${movie.id}/`)
    store.commit('SET_CURRRENT_MOVIE', movie)
    return {
      movie
    }
  }
}
```

**Comment by alekbarszczewski** [comment]
I do it like this (head method is called after fetch is complete):

```js
export default {
  async fetch ({ store }) {
    await store.dispatch('myModule/myAction')
  },

  head () {
    const something = this.$store.getters['myModule/myGetter'] // <------- this.$store
    return { title: something }
  }
}
```

**Comment by longhoang2984** [comment]
Have problem with head () {
    const something = this.$store.getters['myModule/myGetter'] // <------- this.$store
    return { title: something }
  }

I can't see meta in view page source

**Comment by designcourse** [comment]
> Have problem with head () {
> const something = this.$store.getters['myModule/myGetter'] // <------- this.$store
> return { title: something }
> }
> 
> I can't see meta in view page source

Same here.. Cannot figure this out.

**Comment by galvez** [comment]
@longhoang2984 @designcourse what does `console.log(this.$store)` give you in the head method?
