### ISSUE TITLE
From Webpack to Parcel

### ISSUE THREAD

**Issue by microcipcip** [nuxt/nuxt.js#2541]
What are your opinions on [Parcel](https://github.com/parcel-bundler/parcel)? The speed and easy of use looks appealing. I know it may be too early as Nuxt and Vue ecosystem rely completely on Webpack for bundling, but it may be worth having a look.

While I like Nuxt a lot, at the moment it takes 10 seconds to compile an empty Nuxt project, so I believe that Parcel would make developers happy(er) .

**Comment by pxwee5** [comment]
Blazingly fast module bundler is what it is! But I believe there are still a lot of features missing and it will take a while to build it before Nuxt will ever use it. In v2 maybe considering v1 just landed like 24 hours ago?

**Comment by microcipcip** [comment]
If the benchmarks are true, it would compile Nuxt in 1 second! I never liked webpack and it is weird syntax anyway, so I can't wait to see something like this implemented. The problem as usual will be the ecosystem. There is a huge array of webpack plugins available.

**Comment by microcipcip** [comment]
Update: [Parcel can now render Vue components](https://github.com/parcel-bundler/parcel/issues/5#issuecomment-359168173)

**Comment by microcipcip** [comment]
I am closing this as [Webpack 4.0](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4) is from 60% to 90% faster than Webpack 3.0, and Webpack 5.0 will support multithreading.

**Comment by daiyanze** [comment]
Is Nuxt highly coupled with Webpack? If so, then Parcel is hardly an option. But I believe it would be better to go with Parcel.

**Comment by microcipcip** [comment]
@daiyanze yes AFAIK it is tightly coupled.
