### ISSUE TITLE
Underscores are not considered when building URLs

### ISSUE THREAD

**Issue by samirph** [nuxt/nuxt.js#2543]
When a page like `sign_in.vue` is created, the url generated is `/sign` instead of `/sign_in`.
Why not making it possible? 

Why I want that behavior:
I'm remaking a website using Nuxt and I want to keep the older URLs for SEO purposes.

**Comment by NicoPennec** [comment]
alternative solution:
1. rename your page with dash `sign-in.vue`
2. redirect  `/sign_in` to `/sign-in` by HTTP 301 (SEO compliant) with a nuxt `servermiddleware`

more details on this issue : https://github.com/nuxt/nuxt.js/issues/1592

**Comment by HernanCabrera** [comment]
How can I do with dynamic routes?
