### ISSUE TITLE
Generating full absolute url for social icons

### ISSUE THREAD

**Issue by pxwee5** [nuxt/nuxt.js#2544]
Little help here, couldn't figure out how to generate the full url (http://url.com/blog/this-is-a-blog-post) to be exported into facebook's sharing link `https://www.facebook.com/sharer/sharer.php?u=${url}`

Each of the blog post is retrieved via `asyncData` from a headless CMS. So I only have a slug `this-is-a-blog-post` to work with. 

Ideally I'd like to use `this.$route` to generate the full url but none of the methods show how. Also taking into consideration I am using SSR, so the url is generated serverside, hence I cannot use `window.location` that is clientside. 

Help appreciated :)

**Comment by Evild67** [comment]
You can create a method or a computed to retrieve your url to share.

In your function, use `this.$route.fullPath`. Don't forget to also add your domaine name at the beginning

```javascript
<template>
  <div>
  <a :href="'fbSocialUrl" target="_blank" title="Share on Facebook">
  </a>
  </div>
</template>

<script>
export default {
  computed: {
    fbSocialUrl: function () {
      return 'https://www.facebook.com/sharer/sharer.php?u=https://exemple.com' + this.$route.fullPath
    }
  }
}
</script>
```

**Comment by pxwee5** [comment]
Good idea but that would mean I'll have to change `https://example.com` everytime I change a hostname and I also cannot test it during development.

**Comment by microcipcip** [comment]
Why don't you set the hostname in a env variable then use `${process.env.HOSTNAME}`?
