### ISSUE TITLE
nuxt npm run dev error, promisify not a function

### ISSUE THREAD

**Issue by lenvonsam** [nuxt/nuxt.js#2545]
![image](https://user-images.githubusercontent.com/10168476/34749988-716dddc0-f5df-11e7-88b5-c09eeee1a732.png)
dev evn:
npm version 4.2.0
node version 7.10.0
nuxt version 1.0.0

**Comment by DaxChen** [comment]
node < 8.0 is not supported for nuxt@1.0.0 anymore, please update your node.js version

**Comment by lenvonsam** [comment]
There is no mention of the necessary installation environment in last official document of nuxt
@DaxChen

**Comment by DaxChen** [comment]
They are still working on the official website re-design, but for the node.js version, see [v1.0.0 Breaking changes](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0).

**Comment by lenvonsam** [comment]
ok, thx
@DaxChen
