### ISSUE TITLE
Vue warning underscore included directory name

### ISSUE THREAD

**Issue by jdm85kor** [nuxt/nuxt.js#2548]
<img width="279" alt="2018-01-10 2 55 09" src="https://user-images.githubusercontent.com/7186594/34758098-d6ef1fc2-f618-11e7-8cf8-0e866a181b3d.png">

I doing use underscore for dynamic route (https://nuxtjs.org/guide/routing/#dynamic-routes)

<img width="658" alt="2018-01-10 2 54 45" src="https://user-images.githubusercontent.com/7186594/34758029-7fc95e9c-f618-11e7-8579-c3375a79862f.png">

but, there is a issue after update to nuxt 1.0

any way to solve this issue?

somebody help me~

**Comment by cesasol** [comment]
add a name in your component:

``` js
export default {
  name:  'language-index',
}
````

the problem is not the filename, but the name of the component
