### ISSUE TITLE
$style is undefined in production (css modules)

### ISSUE THREAD

**Issue by mxfs** [nuxt/nuxt.js#255]
From Nuxt 0.9.9 **starter template** the only change I made was in Footer.vue
**The error is only displayed in production mode - client side**

Code:
![Code](http://image.prntscr.com/image/f0fbc871d9f14157a6e0f83e13772b2c.png)

Error:
![Error](http://image.prntscr.com/image/2003eb6e1493432792523e48af5a3de4.png)

**Comment by Atinux** [comment]
I just tried with `1.0.0-rc4` and works perfectly :)

**Comment by jamesAtcodeninja** [comment]
How did you enable this feature?
