### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by RhysXia** [nuxt/nuxt.js#2551]
When I use the nuxt1.0.0  and  the nuxt.config.js with `extractCSS: true`, if I start my project in env mode, it will log the `Cannot read property 'call' of undefined` in bowser console. 

With my trying, I find it is OK if I set below
```javascript
extractCSS: {
    allChunks: true
}
```

I think it may be a `bug`,so I report it.
Think you.

**Comment by clarkdo** [comment]
Can you provider the repo?

**Comment by RhysXia** [comment]
I'm sorry. I thought about this problem again yesterday. I found it wasn't the `extractCss` problem. It's the problem of my plugin. this is my plugin below
```javascript
import Vue from 'vue'
import CRow from '~/components/grid/row'
import CCol from '~/components/grid/col'
import Message from '~/components/common/message'

export default () => {
  Vue.component('CRow', CRow)
  Vue.component('CCol', CCol)

  Vue.prototype.$message = Message
}

```
In the `nuxt.config.js`, I add the plugin to `vendor`, then the problem will appear. Even if I set the plugin like below

```javascript
import Vue from 'vue'
import CRow from '~/components/grid/row'
import CCol from '~/components/grid/col'
import Message from '~/components/common/message'

export default () => {
}

```

I just import the `vue` and my component, the problem still appears. So I try not to import the `vue`, but it is not OK.I think it's my component problem. But my component is normal. So I want to know, 
whether plugin like that cant be put in `vendor`.
The problem is here:

![aa](https://user-images.githubusercontent.com/15535346/34857217-73546d74-f784-11e7-9c85-e224ab83c0b0.png)


When I remove the plugin from `vendor`, it will work.

The problem may be related to the css link. However I don‘’t know the reason.I use the `scss`.

**Comment by clarkdo** [comment]
Can you provide you repo ?

**Comment by RhysXia** [comment]
you can see the demo here
[nuxt-demo](https://github.com/RhysXia/nuxt-test)

**Comment by clarkdo** [comment]
@RhysXia It looks that codes of the repo is not same as you described above.

**Comment by RhysXia** [comment]
@clarkdo It is just a demo of my problem.

In my problem, the key is: I can't add a component plugin into `vendor`  and set `extractCSS:true`.

You can run the demo I give.The problem will happen like I show above.
 the dome use the [template](https://github.com/nuxt-community/koa-template).I just add a plugin and set nuxt.config.js below
```javascript
plugins: [
    '~/plugins/components'
    // {src: '~/plugins/offline', ssr: false}
  ],
  build: {
    vendor: [
      '~/plugins/components'
    ],
    extractCSS: true
  }
```

**Comment by clarkdo** [comment]
I did what you showed, but there is no error in console.

**Comment by RhysXia** [comment]
you should build it and `npm run start`

**Comment by clarkdo** [comment]
It seemd to be an issue from [webpack](https://github.com/webpack/webpack/issues/959#issuecomment-304947450)
For a quick fix you can always add `allChunks: true`.

**Comment by RhysXia** [comment]
okay, thank you for answer

**Comment by clarkdo** [comment]
There are some other solutions also in https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/456.

**Comment by RhysXia** [comment]
okay,now I just remove it from vendor.

**Comment by clarkdo** [comment]
Fixed in https://github.com/nuxt/nuxt.js/commit/28d3e6fdb39b81b8f8e4c8deb6ad8c6479fd097b, will be included in next release
