### ISSUE TITLE
service-worker.js not found

### ISSUE THREAD

**Issue by fuzzthink** [nuxt/nuxt.js#2553]
Follow steps exactly in "Starting from scratch", nothing more or less.
Every .5secs, browser reloads and console prints:

```
  nuxt:render Rendering url /service-worker.js +3m
{ statusCode: 404, message: 'This page could not be found' }
```

**Comment by zhouyu1993** [comment]
put your `service-worker.js` in `static`

/static/service-worker.js

**Comment by fuzzthink** [comment]
Hope to get a response from maintainers on this.

I can't imagine the "hello world" sample code in the guide won't work and no one raised issue before.
Perhaps something made this happen recently?  It's hard to imagine otherwise. 

Please either fix this or at very least document how to create one and where to put it in the guide.

thanks.

**Comment by clarkdo** [comment]
Did you use this [Starting from scratch](https://nuxtjs.org/guide/installation#starting-from-scratch) ? There shouldn't have anything related to `service-works`

**Comment by fuzzthink** [comment]
I did. I just tried again and this time I can not reproduce it. So not sure what happened. Closing as can't reproduce.

**Comment by vadim-givola** [comment]
running into the same issue, trying to use [starting from scratch](https://nuxtjs.org/guide/installation#starting-from-scratch) template and got this in console 
```
nuxt:render Rendering url /service-worker.js +3m
{ statusCode: 404, path: '/service-worker.js', message: 'This page could not be found' }
```
can't figure out what I'm doing wrong cause there is no referrence to any `service-workers` at the app at all

**Comment by hemulin** [comment]
I'm having similar issue with 
```
{ statusCode: 404,
  path: '/sw.js',
  message: 'This page could not be found' }
```
I thought it is related to another app I've worked on and that had PWA module, but it seems very not likely that different workspaces would leak and pollute others.

Also thought it might be related to some faulty extension on the browser (chromium) and tried to eliminate and test them one by one, to no avail... 

Any help would be much appreciated
