### ISSUE TITLE
How to properly set Document's cache-related headers?

### ISSUE THREAD

**Issue by f15gdsy** [nuxt/nuxt.js#2554]
Hi, I'm wondering how to set the cache-related response headers for my pages?
Such headers are: 
- Cache-Control
- Expires
- Pragma

**Comment by clarkdo** [comment]
If you are use custom server like express, koa or hapi, you can directly set response `headers` in server side.
Or you can try to use [Custom Server Middleware](https://nuxtjs.org/api/configuration-servermiddleware#custom-server-middleware).
Or try to add 
```js
  head: {
    meta: [
      { 'http-equiv': 'pragma', content: 'no-cache' },
      { 'http-equiv': 'cache-control', content: 'no-cache' },
      { 'http-equiv': 'expires', content: '0' }
    ],
  }
```

**Comment by awronski** [comment]
@f15gdsy 

nuxt.config.js:
```
  serverMiddleware: [
    '~/api/headers.js'
  ],
```

headers.js:
```js
module.exports = function (req, res, next) {
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate')
  next()
}
```
etc
