### ISSUE TITLE
Redirect error in spa mode.

### ISSUE THREAD

**Issue by stonexx** [nuxt/nuxt.js#2555]
Page not render when continuous redirection in spa mode.
[files](https://preview.c9users.io/stonexx/nuxt-redirect-example/) and [example](http://nuxt-redirect-example-stonexx.c9users.io:8080/).

**Comment by clarkdo** [comment]
Fixed in https://github.com/nuxt/nuxt.js/commit/4ec99ef6f6fbca7064d75eef6cbec835cf743a32, will be included in next release.
