### ISSUE TITLE
Unable to access Store in mounted hook after page refresh

### ISSUE THREAD

**Issue by lanbau** [nuxt/nuxt.js#2557]
This is on a page.
I am logging for this.$store. The store works when you click around but when i refresh the page the store is blank.

```
  mounted () {
    console.log(this.$store.getters.getCartId) 
    axios.get(url + this.$store.getters.getCartId).then(res => {
      // do something
    })
  }
```

**Comment by clarkdo** [comment]
Can you provide a repo can reproduce you issue ?

**Comment by jazoom** [comment]
This sounds like it was due to the store not yet being initialised. That's why it works when you `click around`.

It'd be really nice if there was a `storeInitialized` function or something like it. This is a common issue I have to hack around.
