### ISSUE TITLE
Nested node_modules are ignored.

### ISSUE THREAD

**Issue by kdar** [nuxt/nuxt.js#2558]
I ran into an issue where a package had it's own node_modules, and webpack was ignoring it and instead trying to bundle the package from the root node_modules (which made it error in my case). The reason this happens is because when resolve.modules is an absolute path, it will no longer resolve nested node_modules.

The relevant piece of code is in lib/common/options.js:

```
 // Populate modulesDir
  options.modulesDir = []
    .concat(join(options.nuxtDir, 'node_modules'))
    .concat(options.modulesDir)
    .filter(dir => hasValue(dir))
.map(dir => resolve(options.rootDir, dir))
```

To test this, I added ```options.modulesDir.unshift("node_modules");``` at the end of this for webpack to prioritize nested node_modules.

I'm not entirely sure what commit introduced this bug, as this was working fine in `1.0.0-gh-b31b0f2` and broke in the latest `1.0.0`.

**Comment by pi0** [comment]
Hi. This regression should be fixed in next release by prioritizing user-provided options like before.

**Comment by pi0** [comment]
PS: until next release, you can try changing nuxt dependency to `nuxt-edge@1.0.0-25261199.421070d` to test the results.

**Comment by kdar** [comment]
This is still not fixed in `nuxt-edge@1.0.0-25261199.421070d`. The issue is when you provide absolute paths to webpack's `resolve.modules`, webpack will no longer look for nested node_modules. In order to fix this, "node_modules" needs to be the first entry in `resolve.modules`.

e.g. this is what I have now as `resolve.modules`:

```
[ '/home/kdar/dev/frontend/node_modules',
  '/home/kdar/dev/frontend/node_modules/nuxt-edge/node_modules' ]
```
and this is what it needs to be to get webpack to use nested node_modules:
```
[ 'node_modules',
  '/home/kdar/dev/frontend/node_modules',
  '/home/kdar/dev/frontend/node_modules/nuxt-edge/node_modules' ]
```

**Comment by kdar** [comment]
One unintended consequence of allowing webpack to use nested node_modules, is now webpack is bundling multiple copies of the same library in vendor.js. I'm not entirely sure what the correct solution is here (can I exclude a package from being searched? e.g. i'm using vue-tables-2, which has vue in its node_modules, so I get ~/node_modules/vue and ~/node_modules/vue-tables-2/vue in my vendor.js)

**Comment by kdar** [comment]
This appears to be working properly in 1.3.0. Closing for now.
