### ISSUE TITLE
About [Add webpack plugins]. How to add some special attributes to my js files ?

### ISSUE THREAD

**Issue by zhouyu1993** [nuxt/nuxt.js#2559]
Just like this, I use `script-ext-html-webpack-plugin` to add `crossorigin=anonymous`.

``` js
const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin')

module.exports = {
    build: [
     plugins: [
          // Add webpack plugins,
          // https://github.com/numical/script-ext-html-webpack-plugin
          new ScriptExtHtmlWebpackPlugin({
            defaultAttribute: 'defer',
            custom: [
              {
                test: /\.js$/,
                attribute: 'crossorigin',
                value: 'anonymous'
              }
            ]
          }),
        ],
    ],
}
```

But it doesn't work.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2225">#c2225</a>)</em></sub></div>

**Comment by manniL** [comment]
This question can be answered on [CMTY](https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2225)
