### ISSUE TITLE
Does nuxtServerInit support asyn functions?

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#256]
I am using token based authentication instead of session based. The auth server is different from the nuxt.js app.
Is there a way to add async functions to nuxtServerInit function. Given below is the code which I tried. But looks like its not waiting for the Promise to return.

    `nuxtServerInit ({commit}, {req}) {
        console.log('nuxtServer init');
        let token = req.cookies.token;
        let email = req.cookies.email;
        return axios.post('https://my-server/api-token-verify/', {token: token}).then((response) => {
            if (response.data.token) {
                console.log('Token is valid');
                commit('auth/setUser', {token, email});
                return Promise.resolve();
            } else {
                commit('auth/setUser', null);
                console.log('Invalid token');
                return Promise.reject();
            }
        }).catch((err) => {
            console.log('Invalid token');
            return Promise.reject();
        });
    }`

**Comment by alexchopin** [comment]
Hi, yes `nuxtServerInit()` support async function, you just need to prefix it by `async`:
```js
async nuxtServerInit ({commit}, {req}) {
    console.log('nuxtServer init');
    let token = req.cookies.token;
    let email = req.cookies.email;
    return axios.post('https://my-server/api-token-verify/', {token: token}).then((response) => {
        if (response.data.token) {
            console.log('Token is valid');
            commit('auth/setUser', {token, email});
            return Promise.resolve();
        } else {
            commit('auth/setUser', null);
            console.log('Invalid token');
            return Promise.reject();
        }
    }).catch((err) => {
        console.log('Invalid token');
        return Promise.reject();
    });
}
```
You can also use `await` with `async`.

**Comment by andrade1379** [comment]
@alexchopin I was wondering how one would set a cookie on the client within nuxtServerInit via `nuxt generate` my project needs to be a static site and `req` and `res` aren't available to be via `nuxt generate`
