### ISSUE TITLE
Nuxt deployment, resulting in page 404, how to achieve the correct static deployment?

### ISSUE THREAD

**Issue by fanslijun** [nuxt/nuxt.js#2560]
Nuxt deployment, resulting in page 404, how to achieve the correct static deployment?

**Comment by clarkdo** [comment]
Can you describe you problem more specific or provide a repo ?

**Comment by fanslijun** [comment]
The nuxt project server is statically deployed, nuxt generate, and then the nginx agent, which causes the home page to refresh the load, and the other routes are below, and the refresh will be 404.

**Comment by clarkdo** [comment]
thanks，could you please provide your repo？

**Comment by DreaMinder** [comment]
he can't. 'coz the problem probably with nginx config, not with nuxt
First try to make blank html file, place it where you store nuxt generated files and make it work with nginx.
