### ISSUE TITLE
Dynamic routes it's not work in Firebase cloud function when refresh page How to fix it?

### ISSUE THREAD

**Issue by lagmanzaza** [nuxt/nuxt.js#2562]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2229">#c2229</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
