### ISSUE TITLE
Location of index.js

### ISSUE THREAD

**Issue by francissalvamantePTX** [nuxt/nuxt.js#2567]
Hi, I am currently studying and using this specific framework and I find it wonderful that routes are added automatically. But my issue is I can't seem to locate index.js (or main.js, whatever name is used). I wanted to edit the file so that I could import Vuetify

import Vuetify from 'vuetify'
....
Vue.use(Vuetify);

How can I possibly import this so that I could use it globally. Response would be deeply appreciated

Thank you,

Francis Vianney Salvamante
Junior Developer

**Comment by Zip753** [comment]
Hi @francissalvamantePTX,

You can add a plugin with any initial setup you require. Please refer to [the docs](https://nuxtjs.org/guide/plugins/#vue-plugins), there you'll find a use case very similar to yours.

**Comment by EllenFawkes** [comment]
Create file **plugins/vuetify.js**:

```javascript
import Vuetify from 'vuetify'

Vue.use(Vuetify);
```

and register it in **nuxt.config.js**

```javascript
plugins: [ 
  'plugins/vuetify.js'
]
```

**Comment by EllenFawkes** [comment]
I found example: https://github.com/nuxt/nuxt.js/blob/dev/examples/with-vuetify/plugins/vuetify.js

**Comment by francissalvamantePTX** [comment]
Thank you very much for your help @Zip753 and @EllenFawkes :) Pretty much appreciated
