### ISSUE TITLE
question about 'nuxt build'

### ISSUE THREAD

**Issue by TenshiGoan** [nuxt/nuxt.js#2569]
When run nuxt build in npm, it newer finished.
To work i changed in lines 79-85(bin/nuxt-build.js):

  builder
    .build()
    .then(() => debug('Building done'))
    **.then(() => process.exit(0)) //FIXME: Exit**
    .catch(err => {
      Utils.fatalError(err)
    })

What right method to solve this problem?

**Comment by pi0** [comment]
Thanks for the report. Will be fixed in next release.
