### ISSUE TITLE
Nuxt 1.0.0 - Failed to run npm run generate

### ISSUE THREAD

**Issue by tksumanth1994** [nuxt/nuxt.js#2570]
![image](https://user-images.githubusercontent.com/4353562/34875683-4b0bd7ea-f7c4-11e7-8580-3e65e8c6ce16.png)
I'm stuck on genrating the build. Any help?

**Comment by Atinux** [comment]
Make sure that you are not using `req` or `res` for `nuxt generate`

**Comment by tksumanth1994** [comment]
Sorry to reopen this, but I have commented out all the requests going out from services/axios. Still it is not working. Could there be any other way a request can leak out (like may be images url in html code)? @Atinux

**Comment by Atinux** [comment]
Hi @tksumanth1994 

I fixed it in https://github.com/nuxt/nuxt.js/commit/de02ea4b5dee0c130867f87043453ddf3da41ea5

The release will come this week, stay tuned.
