### ISSUE TITLE
Error While Upgrading from RC11

### ISSUE THREAD

**Issue by AngelMunoz** [nuxt/nuxt.js#2571]
Hello I'm using nuxt with sails js, I updated the RC11 in my package.json to the v1 release, while I don't see any breaking changes for my case in the release notes I've been having some troubles to make it work.

- First it required me to add weback 3 as a peer dependency
- Second while It build correctly when navigating to the index it made me install few vue dependencies
  - vue-meta
  - vue-router
  - vuex
because it didn't find them.

At this point I don't know if the above was necesary that's a question, but then after installing what it required me then what previously rendered in RC11 now didn't render, even when I deleted a bunch of views of custom code and just left what's on the normal vuetify nuxt template
<img width="960" alt="errors" src="https://user-images.githubusercontent.com/8684875/34876389-de40083c-f766-11e7-80f1-e6314401dd7e.PNG">

I don't have any idea what's going on, you can check the code at 
https://github.com/AngelMunoz/sails-nuxt/tree/failing-branch
the master branch builds/renders fine without problems

**Comment by Atinux** [comment]
Could you try to remove your `node_modules/` and `package-lock.json` and redo an `npm install`?

**Comment by AngelMunoz** [comment]
this seeems to be fixed in the latest updates as pointed out in this comment
https://github.com/AngelMunoz/sails-nuxt/commit/70518500fbb4391f8516f609c15c28c080c4d2e8#commitcomment-27199490

already checked up and updated the repo, so will be closing this one thanks!
