### ISSUE TITLE
What could possibly cause this Nuxt Build Error on linux?

### ISSUE THREAD

**Issue by BruceHem** [nuxt/nuxt.js#2572]
Any idea what could cause this? The nuxt build works on Mac & Windows but not Linux. 😭

This relative module was not found:

* ../components/TheSideNav.vue in ./node_modules/ts-loader?{"appendTsSuffixTo":[{}]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./client/layouts/default.vue

source code: https://github.com/BruceHem/simple-todos

**Comment by pi0** [comment]
Maybe because Linux is Case Sensitive. At code it is `TheSideNav` but file name is `TheSidenav` 😸

**Comment by BruceHem** [comment]
@pi0 Holy shit you're right. I spent hours tweaking the damn ts-loader. Thanks a lot.
