### ISSUE TITLE
SSR - no cookies on initial load

### ISSUE THREAD

**Issue by leovanhaaren** [nuxt/nuxt.js#2573]
Hey all,

I'm currently using the latest RC of nuxt.js for our company website. We are using some external tools which scan the cookies that are in use. Unfortunately this these tools are detecting 0 cookies with nuxt.js in SSR mode. I'm unable to find any information why this could happen.

I'm currently thinking that it has to do with the initial request not containing any cookies, those seem to get send afterwards. Any thoughts? I know it is a very specific problem and maybe not nuxt.js related, but any help is welcome.

**Comment by microcipcip** [comment]
This is a very generic question. I am able to get the cookies from node. Without more info it will be quite difficult to answer.

**Comment by husayt** [comment]
Closing. Reopen with more details psl.
