### ISSUE TITLE
Invalid vendor error when upgraded from 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by joealden** [nuxt/nuxt.js#2574]
I just upgraded nuxt from version 1.0.0 to 1.1.0 and am getting the following error when running either `nuxt dev` or `nuxt build`:

```
Error: Invalid vendor:vue-apollo,apollo-client,apollo-cache-inmemory

  - module.js:28 ModuleContainer.addVendor
    [corum]/[nuxt]/lib/core/module.js:28:13

  - index.js:27 ModuleContainer.nuxtApollo
    [corum]/[@nuxtjs]/apollo/index.js:27:8

  - module.js:150 Promise
    [corum]/[nuxt]/lib/core/module.js:150:30

  - new Promise

  - module.js:134 ModuleContainer.addModule
    [corum]/[nuxt]/lib/core/module.js:134:12

  - utils.js:96 promise.then
    [corum]/[nuxt]/lib/common/utils.js:96:43


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7

  - module.js:686 Function.Module.runMain
    module.js:686:11

  - bootstrap_node.js:187 startup
    bootstrap_node.js:187:16

  - bootstrap_node.js:608
    bootstrap_node.js:608:3
```

From the stack trace, it looks like it could also be something to do with the nuxt Apollo module.

Could anyone tell me what this error means? I can't think of why this would happen when updating to a new minor release?

**Comment by joealden** [comment]
Okay, I think I have figured out what is causing this bug, this commit was made yesterday https://github.com/nuxt/nuxt.js/commit/e5ffbdfcd2aa20aa857864b432453160a3a92fff and it changed how the `addVendor` function works, adding a check that ensures that the `vendor` argument is a string.

As seen here: https://github.com/nuxt-community/apollo-module/blob/master/index.js#L27 the nuxt apollo module passes an array of strings to this function when it is expecting just a string, so the error is thrown.

**Comment by joealden** [comment]
@pi0 As you are definitely more familiar with this code than me, what should be done here? Maybe the `addVendor` function should also checked if it was an array of strings, and handled that accordingly. Or should the apollo module be calling the method once per item in the array?

**Comment by pi0** [comment]
Thanks for the report. Will be fixed in next release.

**Comment by joealden** [comment]
Thanks :)
