### ISSUE TITLE
Errors on formatting conventions

### ISSUE THREAD

**Issue by Stegosource** [nuxt/nuxt.js#2581]
I just started using Nuxt, and my Editor is VS Code. My editor is set up to auto-format my files, and some of the formatting is causing errors with compiling Nuxt. 

Extra semicolons and using double-quotes were the two in particular. 

I wonder if these are preferences that should be up to the developers, and not the framework. Or if they are on the framework level, maybe the editorconfig file or eslint file can set up the rules for the workspace?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2246">#c2246</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
The nuxt community starter kit follow the "[JavaScript Standard Style](https://standardjs.com/rules.html)".
(See the https://github.com/nuxt-community/starter-template/blob/master/template/.eslintrc.js#L8)

You can override these rules easily to your custom eslint configuration.

edit `.eslintrc.js`file at nuxt project root:
```js
  rules: {
    "quotes": ["error", "double"],
    "semi": ["error", "always"]
  }
```
