### ISSUE TITLE
styleResources : watch the file changes

### ISSUE THREAD

**Issue by yoyo837** [nuxt/nuxt.js#2583]
Should watch the file changes and rebuild in dev env.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2248">#c2248</a>)</em></sub></div>

**Comment by template01** [comment]
Indeed :+1:  :)

**Comment by yoyo837** [comment]
Seems to have been fixed in nuxt-edge, #2884.
