### ISSUE TITLE
nuxt.plugin('build',..) is not supported. Use new hooks system.

### ISSUE THREAD

**Issue by NicolaeCasir** [nuxt/nuxt.js#2585]
Hi. After update i get this error when i want to run `npm run build`
` ERROR  Nuxt error

  Error: nuxt.plugin('build',..) is not supported. Use new hooks system.
  
  - nuxt.js:88 Nuxt.plugin
    [proiecte]/[nuxt]/lib/core/nuxt.js:88:13
  
  - index.js:54 ModuleContainer.nuxtWorkbox
    [proiecte]/[@nuxtjs]/workbox/index.js:54:13
  
  - module.js:155 Promise
    [proiecte]/[nuxt]/lib/core/module.js:155:30
  
  - new Promise
  
  - module.js:139 ModuleContainer.addModule
    [proiecte]/[nuxt]/lib/core/module.js:139:12
  
  - module.js:90 ModuleContainer.requireModule
    [proiecte]/[nuxt]/lib/core/module.js:90:17
  
  - index.js:7 module
    [proiecte]/[@nuxtjs]/pwa/index.js:7:17
  
  - index.js:1 promise.then
    [proiecte]/[@nuxtjs]/pwa/index.js:1:146
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proiecte@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the proiecte@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

What should i Change?

**Comment by pi0** [comment]
Hi. Would you please confirm exactly witch versions of `nuxt` and `@nuxtjs/pwa` packages are causing this error?

**Comment by NicolaeCasir** [comment]
[SOLVED]
Problem was that `@nuxtjs/pwa` was old. v 1.0.2
Uninstalled and reinstalled `@nuxtjs/pwa` and it's all OK.

**Comment by pi0** [comment]
OK. Nice to hear your problem was resolved :)
