### ISSUE TITLE
app.addRoutes error on v1.1.1

### ISSUE THREAD

**Issue by marktheis** [nuxt/nuxt.js#2586]
I just upgraded from 1.0.0-rc8 to 1.1.1 and I get an error when using `app.router.addRoutes` in a plugin:

```
import mycustompage from "@/custompages/mycustompage.vue";

export default async ({app}) => {
	app.router.addRoutes([
		{
			path: "/",
			name: "index",
			component: mycustompage
		}
	]);
};
```

Cannot read property 'layout' of undefined
.nuxt/server.js:123:

```
  // ...If there is a redirect or an error, stop the process
  if (ssrContext.redirected) return noopApp()
  if (ssrContext.nuxt.error) return renderErrorPage()

  /*
  ** Set layout
  */
  let layout = Components.length ? Components[0].options.layout : NuxtError.layout
  if (typeof layout === 'function') layout = layout(app.context)
  await _app.loadLayout(layout)
  layout = _app.setLayout(layout)
```

it seems `options` is missing from the `Component`.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2249">#c2249</a>)</em></sub></div>

**Comment by marktheis** [comment]
I get the same error on version 1.3.0

**Comment by dts** [comment]
I'm getting the same behavior, the way you phrase it make it looks like it's compiling the thing with some kind of incorrect Webpack configuration...

**Comment by sarendsen** [comment]
same here

**Comment by vizo** [comment]
Same here in 2.0

**Comment by manniL** [comment]
Please use [`extendRoutes`](https://nuxtjs.org/api/configuration-router/#extendroutes) to extend the vue router :ok_hand: 

Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
