### ISSUE TITLE
extractCSS problem

### ISSUE THREAD

**Issue by do-web** [nuxt/nuxt.js#2588]
extractCSS: true,  merge all css  in a single css file app.css, so styles for other pages gets overwritten, please create a css file for each page.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2253">#c2253</a>)</em></sub></div>

**Comment by cesasol** [comment]
scoped styles

**Comment by binggg** [comment]
@cesasol 

Scoped style only works for element that in component.

For example, each page defines body background, styles will overwritten by the last page's css.

**Comment by hankanon** [comment]
I also encountered the same problem，Need some help and advice

**Comment by cesasol** [comment]
The way I managed to solve this is with dynamic page classes `<nuxt :class="['layout__page', 'layout__page-' + $route.name]"/></nuxt>` 

``` scss
.layout {
  ...
  &__page {
    &-index {
      background-color: red;
    }
   &-second {
      background-color: blue;
    }
  }
}

and this example corresponds to two vue files named index and demo inside the pages folders, you can also use a computed propety to transform the path or the params into a css string.

If your case is even more complex you can also use a meta middleware and combine everything, name of the route, params for the route and meta of the page wich can come from an api or user input

**Comment by husayt** [comment]
I actually was referring to changes around extractcss I saw you made, but yes, kudos to the whole team. I have seen the waterfall of changes coming in.  Seems it's going to be the largest release since 1.0.0. 
All the best, can't wait for that

**Comment by setLylToxlx** [comment]
@do-web  
I have the same problem
Did you solve this ?

**Comment by manniL** [comment]
In `nuxt-edge` you can use [`optimization`](https://nuxtjs.org/api/configuration-build/#optimization) from `webpack4` to set up your split behaviour (together with `extractCss`). By default, the CSS isn't merged in one file anymore.

If this behavior is still wanted, see #3166  for a solution
