### ISSUE TITLE
Nuxt build is failing on uglify step

### ISSUE THREAD

**Issue by JiriChara** [nuxt/nuxt.js#259]
I am not able to run `yarn build`, because uglify is failing:

```
Parse error at .nuxt/dist/0.nuxt.bundle.js:4558,4
SyntaxError: Unexpected token: name (warn)
```

For some reason the following block of code in the `0.nuxt.bundle.js` file is not properly converted to es5:

```javascript
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "warn", function() { return warn; });
// Copied from vue/src/core/util/debug.js

let warn = () => {}

if (false) {
  const hasConsole = typeof console !== 'undefined'

  warn = (msg, vm) => {
    if (hasConsole) {
      console.error(`[Vue warn]: ${msg} ` + (
        vm ? formatLocation(formatComponentName(vm)) : ''
      ))
    }
  }

  const formatComponentName = vm => {
    if (vm.$root === vm) {
      return 'root instance'
    }
    const name = vm._isVue
      ? vm.$options.name || vm.$options._componentTag
      : vm.name
    return name ? `component <${name}>` : `anonymous component`
  }

  const formatLocation = str => {
    if (str === 'anonymous component') {
      str += ` - use the "name" option for better debugging messages.`
    }
    return `(found in ${str})`
  }
}




/***/ }),
```

and therefore uglify fails when it is processing this arrow function: `let warn = () => {}`. The rest of the file looks fine. Maybe it is bug in `vue-loader`, not quite sure

**Comment by JiriChara** [comment]
It looks like this file: https://github.com/vuejs/vue/blob/51e7608528c2e958e3705425bad3d6325ce97765/src/core/util/debug.js

**Comment by JiriChara** [comment]
It seems like it only happens when certain JavaScript file exceeds a size limit of `250 kB`. Basically I have a page where I load `marked` and `highlight.js` and the build will fail, because those libs are kind of too big

**Comment by JiriChara** [comment]
The bug is actually in `vue-awesome`: https://github.com/Justineo/vue-awesome/blob/master/src/util.js => closing

**Comment by linsir** [comment]
@JiriChara  How to slove it at last?
