### ISSUE TITLE
Excluding .test.js files from build

### ISSUE THREAD

**Issue by Alex-Sokolov** [nuxt/nuxt.js#2592]
Hi!
Is it possible to exclude from build some type of files?
For example if test files stored next to tested component (`/pages/component.vue` and `/pages/component.test.js`)

Trying to exclude files inside `extend` but without success, nuxt grab `.test.js` file while building

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2258">#c2258</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. You can ignore files by putting a `-` in front of their name. https://github.com/nuxt/nuxt.js/pull/2417

**Comment by Alex-Sokolov** [comment]
@pi0 thanks for answer! But will be this option configurable?

**Comment by pi0** [comment]
Yes. But currently only the **prefix** is configurable. Maybe would be a good idea to add support for suffix ignores too. Especially for `.test` files.

/cc @Atinux @graphman65

**Comment by pi0** [comment]
Ah, another idea: We can also introduce a new option `options.ignorePatterns[]` which backward compatibility to `options.ignorePrefix` and full customization.

**Comment by Atinux** [comment]
I like your second idea @pi0

**Comment by marco-gattelli** [comment]
Hi @Atinux, 
what about the `test` files that are located in the `components` folder? How can we ignore these kind of files at build time?

**Comment by Atinux** [comment]
If you don't require them in your app, they won't be imported at build time @marco-gattelli
