### ISSUE TITLE
Using generate() programatically on a nuxt powered SSR Website...

### ISSUE THREAD

**Issue by Norbz** [nuxt/nuxt.js#2598]
Hello there.

For my last project I used nuxt in a pretty new way.

My staging env runs nuxt and a backend solution to provide an API. on this environnment, you can see the pages rendered the classic way with the data you entered in the backend.

When you are satisfied with your changes in the backend, you can "publish" the website : It means :
1- First, generate the pages with nuxt generate
2- Push the generated content to some S3 bucket.

My issue here is that, when generating the website with nuxt generate, although the final files will be in the dist folder, the generation task will erase the root .nuxt folder and rewrite over it. So everytime I run a nuxt generate, I need to restart the Nuxt middleware so that it regenerate again the pages.

I wish the nuxt generate option would build directly in the dist folder so that I wouldn't have to restart the middleware. It's also usefull for development phases as you may have your sever running with HMR, but if you need to check the generate task, it will erase your .nuxt folder too, leaving the dev server unable to go one.

I hope that was kinda clear as it is pretty difficult to explains. As always, please let me know how I can help you with more details.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2260">#c2260</a>)</em></sub></div>

**Comment by galvez** [comment]
@Norbz this would require a rather intricate reengineering of the Nuxt core, which is somewhat planned already for the next major version of Nuxt after 2.0. Closing this for now.
