### ISSUE TITLE
Routes with optional prefix

### ISSUE THREAD

**Issue by AlexLomm** [nuxt/nuxt.js#2599]
I want to achieve the following behavior in my Vue project:

```
    routes: [
        {
            path: '/:prefix?',
            component: Layout,
            children: [
                {path: 'category/:slug?', name: 'category', component: Category},
                {path: 'post/:slug', name: 'post', component: Post},
                {path: '', name: 'home', component: Home},  // <-- MUST BE AT THE BOTTOM
                // etc..
            ]
        }
    ]
```
As you see, every route can have an optional prefix. The `prefix` parameter *should also accept an empty string*. Is this kind of thing achievable? 

Thanks

**Comment by BatuhanK** [comment]
[Here](https://nuxtjs.org/examples/i18n/) is an example, btw are you trying to achieve language prefix?

**Comment by AlexLomm** [comment]
Thanks. 
No, just company names.
