### ISSUE TITLE
Register component does not work.

### ISSUE THREAD

**Issue by phenrigomes** [nuxt/nuxt.js#260]
I added the vue-multiselect component in plugins folder, but it does not work:

plugins/

```
import Vue from 'vue';

// Include bootstrap JS only
if (process.BROWSER_BUILD) {
  // register globally
  var VueMultiselect = require('vue-multiselect');
  Vue.component(VueMultiselect);
}

```

vendor:
```
vendor: ['jquery', 'tether', 'bootstrap', 'vue-multiselect', 'vee-validate', 'vue-resource']
```

**Comment by Atinux** [comment]
@phenrigomes did you added the path to your plugin in the [plugins option](https://nuxtjs.org/api/configuration-plugins) of your `nuxt.config.js`?

If so, what is your error, we really can't help you without more informations.

**Comment by alexchopin** [comment]
Hi,
Have you try to setup you component like vue-multiselect describe ?
```js
Vue.component('Multiselect', VueMultiselect.default)
```

**Comment by phenrigomes** [comment]
@alexchopin Thanks! I could not find this code to set the component globally. Great! It is works.

Befor, I used: 

import Multiselect from 'vue-multiselect'
// register globally
Vue.component(Multiselect)
