### ISSUE TITLE
How to remove client side nuxt scripts?

### ISSUE THREAD

**Issue by marconi1992** [nuxt/nuxt.js#2602]
I want use only the server side capabilities of nuxt, ignoring the client side scripts, Is there a way to do that? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2264">#c2264</a>)</em></sub></div>

**Comment by mtlehtin** [comment]
I would appreciate this as well.

**Comment by mtlehtin** [comment]
I ended up removing Nuxt.js from my project and generating the pages with vue-server-renderer.

**Comment by AleksejDix** [comment]
you can just search for RegEx in generated html ``` (data-n-head-ssr|data-n-head=""|data-n-head="true"|data-n-head="class"|data-server-rendered="true"|<link.*?rel="(prefetch|preload)".*?>|<script.*?src="/_nuxt.*?".*?>.*?</script>|<script\s*type="text/javascript">(.|\r|\n)*?window\.__NUXT__(.|\r|\n)*?</script>) ``` and replace it with nothing

**Comment by f3l1x** [comment]
I would love it too.
