### ISSUE TITLE
Understanding aliases

### ISSUE THREAD

**Issue by microcipcip** [nuxt/nuxt.js#2609]
I have some confusion regarding nuxt aliases.

Inside sass I can only reference with this pattern `~@/assets/scss/styles`. Anything else fails. 
So what does `~@/` mean here? I can't find this documented in [the docs](https://nuxtjs.org/guide/directory-structure#aliases).

**Comment by Atinux** [comment]
Hi @microcipcip 

Actually it's some confusions with [sass-loader imports](https://github.com/webpack-contrib/sass-loader#imports). Sadly we tried to make PR or find other ways but the one you found seems to be the only one at the moment (or use relative paths).

**Comment by microcipcip** [comment]
Ok, thank you :)
