### ISSUE TITLE
Includes SASS file as a nuxt.config.js CSS asset?

### ISSUE THREAD

**Issue by KerryRitter** [nuxt/nuxt.js#261]
I have a global styling asset I want to use but it is SASS, not CSS. Is there a way to set this up in the nuxt.config.js?

**Comment by KerryRitter** [comment]
Dangit. Sorry, found it in the docs: https://nuxtjs.org/api/configuration-css

**Comment by dd199161** [comment]
No solution, when you use @for $I from 1 through 5{...}, again, it's the same.

**Comment by Divine1** [comment]
is this issue resolved? i followed the steps in this link [https://nuxtjs.org/api/configuration-css](https://nuxtjs.org/api/configuration-css)

main.css is not generated automatically from main.scss which running the server.

even if i create an empty file (main.css), nothing gets generated into it,
