### ISSUE TITLE
Async/Await not working since v1.0.0

### ISSUE THREAD

**Issue by Cogitoergo** [nuxt/nuxt.js#2612]
Hi!

I've tried updating my RC11 nuxt.js project to V1.1.1, but it failed with some packages, so I decided to start fresh.

Initialized a new project via `vue init nuxt-community/starter-template`

Everything went fine up till' I tried using async/await in the store, later in methods.

I'm getting the following error everytime: 

`Parsing error: Unexpected token FUNCTION_NAME`

This happens both in store and in components/pages.

Here's my stores action:

```js
export const actions = {
  async reset ({ dispatch, commit }) {
    commit('SET_USER', null)
    await dispatch('updateToken', null)
  }
}
```

which gives the following error:

`Parsing error: Unexpected token reset`

I'm using the latest node version btw, `V9.4.0`

Thanks in advance!

**Comment by Atinux** [comment]
It's due to bad ESLint configuration, please see the correct `.eslintrc.js`: https://github.com/nuxt-community/starter-template/blob/master/template/.eslintrc.js

**Comment by Cogitoergo** [comment]
Works like a charm now, thanks. 

What was the root of the problem?

I've initialized the template via vue init nuxt-community/starter-template, why didin't it pull the correct .eslintrc.js file?

**Comment by Atinux** [comment]
Because I changed it this morning and fixed it 5 minutes ago 😄
