### ISSUE TITLE
Absolute redirects add additional history item

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt.js#2613]
Noted in the PR that fixes https://github.com/nuxt/nuxt.js/issues/770#issuecomment-358093947

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2272">#c2272</a>)</em></sub></div>

**Comment by galvez** [comment]
@Atinux is this really an issue? Fixed in nuxt-edge?

**Comment by Atinux** [comment]
Well, to make sure to fix it if it's one. A bug report should be re-opened through CMTY. Closing it in the meantime.
