### ISSUE TITLE
Access window object from Vuex store file

### ISSUE THREAD

**Issue by irthos** [nuxt/nuxt.js#2614]
Hi, sorry if this has been answered already. I have a couple needs to check into a vuex state from the main window object and do not understand how *process.browser* works to open access to window.

Is there a property on config to set? Otherwise, what's the best way to get the window object?

**Comment by limasierra** [comment]
Hi!

`process.browser` gives you the ability to check whether the current execution takes place on the client- or the server side (i.e. if it returns `true` it's on the client side).

Assume you have a `MyComponent.vue` file. You can access the `window` object as follows:

```
<template>
  <div>hello</div>
</template>

<script>
if (process.browser) {
  console.log('The window object:', window)
}
</script>
```

Hope this helps!

**Comment by irthos** [comment]
That's cool too know but I'm trying to access from a vuex store. I guess we
could set state specific keys to empty properties then fill them on a vue
created(). Thank you.

**Comment by limasierra** [comment]
I'm sorry, I don't get your problem. Don't you just want something like this?

`store/index.js`
```
[...]
export const mutations = {
  myMutation (state, myParam) {
    if (process.browser) {
      console.log('The window object:', window)
    }
    [...]
  }
}
```

**Comment by limasierra** [comment]
Oh, and AFAIK it won't work in `created()`. You'll have to use `mounted()` or a later hook.

**Comment by irthos** [comment]
Thanks, that helps. I could go the mutation route, as well.
