### ISSUE TITLE
How to config server to serve /api ?

### ISSUE THREAD

**Issue by fuzzthink** [nuxt/nuxt.js#2615]
https://nuxtjs.org/api/configuration-servermiddleware shows if I define handler function in serverMiddleware spec, I can do that. But the question is how?  Here's my setup:

server.js:
```
const 
fastify = require('fastify')
,{Nuxt, Builder} = require('nuxt')
,config = require('./nuxt.config.js')
,host = process.env.HOST || '127.0.0.1'
,port = process.env.PORT || 3000
,nuxt = new Nuxt(config)
,app = fastify()

// Enable live build & reloading on dev
if (config.dev) {
  new Builder(nuxt).build()
}

// __ONLY one of these work as they conflict__:
// app.register(require('./api/index'), {prefix: '/api'})
// app.use(nuxt.render)

app.listen(port, host)
```

api/index.js:
```
module.exports = async function (fastify, opts, next) {
  fastify.get('/', (req, reply) => {
    reply.send({ hello: 'world' })
  })
}
```

thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2275">#c2275</a>)</em></sub></div>

**Comment by fuzzthink** [comment]
This works, but is it a good solution:
```
app.register(require('./api/index'), {prefix: '/api'})
app.get('*', (req, res)=>{
  nuxt.render(req.req, res.res)
})
```

**Comment by husayt** [comment]
If you just want to forward that traffic under '/api' to some other service, then there are  out-of-box solutions for you. See belwo:

https://github.com/nuxt-community/axios-module
https://github.com/nuxt-community/proxy-module

**Comment by chanlito** [comment]
@fuzzthink did you find a solution?

**Comment by manniL** [comment]
Why not turning the way around and use a `serverMiddleware` for the API endpoint (similar to my [sending email example](https://blog.lichter.io/posts/sending-emails-through-nuxtjs))?
