### ISSUE TITLE
[Question] Best way to register a function on window object

### ISSUE THREAD

**Issue by mahesh29** [nuxt/nuxt.js#2616]
I am trying to create a webpage, using nuxt, which needs to have hooks on the window object.

For example, I have a c++ endpoint, that spawns a browser and then calls into a Javascript function that would be registered on the window object. This Javascript function is a part of a vue component (that i need to register on the window object).

Curious as to what is the best way to achieve this?

I do understand this might not be a situation that is meant to be handled by nuxt, but i am looking for a safe workaround for implementing this.

**Comment by cretueusebiu** [comment]
You can register a client-side only [plugin](https://nuxtjs.org/guide/plugins#client-side-only).

`nuxt.config.js`:
```javascript
module.exports = {
  plugins: [
    { src: '~/plugins/my-plugin', ssr: false }
  ]
}
```

`plugins/my-plugin.js`:
```javascript
window.myCustomCallback = function () {
  //
}
```

**Comment by mahesh29** [comment]
Thanks for the help @cretueusebiu
That worked just fine !
