### ISSUE TITLE
[Question] Is there a way to dump all the routes(for debugging purposes)?

### ISSUE THREAD

**Issue by AlexLomm** [nuxt/nuxt.js#2619]
I want to inspect what routes are set in the application, is there a way to accomplish this?

**Comment by AlexLomm** [comment]
It's at the bottom in the generated folder `.nuxt/router.js`

**Comment by NicoPennec** [comment]
after build, you can inspect the `./nuxt/router.js`file 

```js 
routes: [
		{
			path: "/",
			component: _91346e10,
			name: "index"
		}, {
		 ...
		}
]
```

**Comment by AlexLomm** [comment]
Thanks, found that literally seconds ago :D
