### ISSUE TITLE
Importing Vue modules using TypeScript

### ISSUE THREAD

**Issue by KerryRitter** [nuxt/nuxt.js#262]
In my app, I have the following structure:

- components/
- components/myComponent.vue
- pages/
- pages/index.vue

<script lang="ts">
import MyComponent from "~components/myComponent"

```
export default {
    components: {
        MyComponent
    }
}
</script>
```

This does not work, it is unable to find the module. When I remove "lang="ts"" it still does not work, but stopping/restarting nuxt resolves the issue.

**Comment by alexchopin** [comment]
#121

**Comment by danieloprado** [comment]
How can I use Vuex?
My vuex store/index.ts:
```ts
import * as Vue from 'vue';
import * as Vuex from 'vuex';
import * as createPersistedState from 'vuex-persistedstate';

import getters from './getters';
import mutations from './mutations';
import actions from './actions';

Vue.use(Vuex);

const plugins = [];
const state: any = {};

if (typeof window !== 'undefined') {
  plugins.push(createPersistedState());
} else {
  state.serverLoaded = true;
}

const store = new Vuex.Store({
  plugins: plugins,
  state,
  getters,
  mutations,
  actions
});

export default store;
```

![image](https://cloud.githubusercontent.com/assets/7683575/24354938/4d03a814-12ca-11e7-8f88-a96abcd1610f.png)
