### ISSUE TITLE
Router :: param doesn't want to be optional

### ISSUE THREAD

**Issue by AlexLomm** [nuxt/nuxt.js#2620]
## Desired Outcome
My goal is to have a `topic/:slug?` route, that would look like the following in a non-nuxt vue project: 

<img width="675" alt="screen shot 2018-01-17 at 6 21 01 pm" src="https://user-images.githubusercontent.com/11467210/35047449-63b6ab4c-fbb3-11e7-9195-0d7a8bb16416.png">

e.g to have a slug as an **optional** parameter for the `/topic` route.

## The Problem
My `pages` folder looks like this:

<img width="194" alt="screen shot 2018-01-24 at 8 55 31 pm" src="https://user-images.githubusercontent.com/11467210/35373096-86796fee-01b6-11e8-8382-e9871c9dca2f.png">

However, the result is `/topic/:slug` instead of `/topic/:slug?`:

<img width="427" alt="screen shot 2018-01-17 at 6 25 51 pm" src="https://user-images.githubusercontent.com/11467210/35047904-dd3cbd2a-fbb4-11e7-815e-f4affe4d324b.png">

What am I doing wrong? Is it a bug?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2279">#c2279</a>)</em></sub></div>

**Comment by entr** [comment]
Sorry for hijacking your issue but I also think route generation is broken. Mine tree is fairly simple I guess:

```
pages
├── blog
│   ├── page
│   │   └── _page
│   │       └── index.vue
│   └── _slug
│       └── index.vue
└── index.vue
```

In `.nuxt/router.js` `:page?` and `:slug?` are generated optional
```js
...
    routes: [
		{
			path: "/",
			component: _7244255c,
			name: "index"
		},
		{
			path: "/blog/page/:page?",
			component: _df792670,
			name: "blog-page-page"
		},
		{
			path: "/blog/:slug?",
			component: _992ac0f4,
			name: "blog-slug"
		}
    ],
...
```

while I expect them to be like

```js
...
    routes: [
		{
			path: "/",
			component: _7244255c,
			name: "index"
		},
		{
			path: "/blog/page/:page",
			component: _df792670,
			name: "blog-page-page"
		},
		{
			path: "/blog/:slug",
			component: _992ac0f4,
			name: "blog-slug"
		}
    ],
...
```
That obviously contradicts with what's documented at https://nuxtjs.org/guide/routing#dynamic-routes , the example with `pages/_slug/index.vue` in particular.

**Comment by AlexLomm** [comment]
Seems like in my case nuxt does not like the optional `/:radio?` prefix. when I make it mandatory, i.e rename the `/_radio/_radio.vue` to `/_radio/index.vue` everything starts working as expected.

It's definitely a bug.

**Comment by clarkdo** [comment]
If there is `topic/index.vue` in same directory with the dynamic route, the `index.vue` will match the directory path `/topic`, it may be conflict with `topic/:slug?`, so Nuxt won't append `/topic/:slug` a optional suffix `?`.
