### ISSUE TITLE
how to use nuxt's loading component inside page?

### ISSUE THREAD

**Issue by agoretsky** [nuxt/nuxt.js#2621]
Hello, 
I would like to show nuxt's default loading while some backend api calls are in progress. How to do it right?
Thanks

**Comment by cretueusebiu** [comment]
In your component you can use `this.$nuxt.$loading.start()` to start the loading bar and `this.$nuxt.$loading.finish()` to finish the loading.

**Comment by agoretsky** [comment]
@cretueusebiu thanks!

**Comment by husayt** [comment]
@cretueusebiu  I will add this to documentation, as it is very helpful
