### ISSUE TITLE
Debug files with VSCODE Chrome Debug

### ISSUE THREAD

**Issue by rnenjoy** [nuxt/nuxt.js#2622]
Hello!

I have been trying for days and days to setup a good debug procedure using Vscode Chrome debug extension. I have tried all different configurations, but never got it working.

I try to debug this file located on the webservers network drive:
\\\192.168.0.2\srv\knx-nuxt\pages\index.vue

nuxt.config.js
```
extend (config, ctx) {
      config.devtool = 'source-map'
```

launch.json
```
{
  "version": "0.1.0",
  "configurations": [
    {
      "name": "Attach Chrome Debug",
      "type": "chrome",
      "request": "attach",
      "port": 9222,
      "url": "http://192.168.0.2:3000",
      "webRoot": "${workspaceRoot}",
      "sourceMapPathOverrides": {
        "webpack:///*": "${workspaceRoot}/*"
      },
      "diagnosticLogging": true,
      "skipFiles": [
          "node_modules\\**"
      ]
    }
  ]
}
```

With this config, vscode  opens up http://192.168.0.2:3000/_nuxt/vendor.js So not even close.

**Using devtool value "eval-source-map"**
opens up VM12974 file with no location.

**Using devtool value "cheap-eval-source-map"** 
open ups /srv/knx-nuxt/pages/index.vue so very close, but the network ip is missing so i think thats why its not understanding that my file is already opened in vscode, and instead opens a new one! But it should open up \\\192.168.0.2\srv\knx-nuxt\pages\index.vue so \\\192.168.0.2\srv is missing

Have anyone tried this and succeeded? Found one closed issue, but it didnt help for me, and I dont think it used this chrome extension.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2281">#c2281</a>)</em></sub></div>

**Comment by sobolevn** [comment]
@rnenjoy did you find any solution?

**Comment by rnenjoy** [comment]
@sobolevn no, i dont think so. i tried alot with different settings and source files, and i think it somewhat works, but it was a while since i tried so i forgot.

**Comment by galvez** [comment]
Closing this as it seems to be a VSCODE-specific question.
