### ISSUE TITLE
transition-group doesn't work with nuxt-link v-for loop

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2624]
For some reason this doesn't work

```html
<transition-group>
  <nuxt-link class="card-link card" :to="`/${card.section.name}/${card.slug}`" v-for="card in cards" :key="card.id">
```

The error is `[Vue warn]: <transition-group> children must be keyed: <router-link>`
But I already have the key `:key="card.id"`.

**Comment by Atinux** [comment]
Hi @iamdubx 

Make sure to use the last version of Nuxt.js. See demo: https://valley-trick.glitch.me/

Code: https://glitch.com/edit/#!/valley-trick?path=pages/index.vue:6:16

Also, please check to `card.id` exists.
