### ISSUE TITLE
How to profile Nuxt application? SSR.

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#2626]
Hi!

I would like to profile nuxt application. I am only interested in SSR.

I already did tests with [apachebench](https://httpd.apache.org/docs/2.4/programs/ab.html) but I need more details what happens inside nuxt.

Like:
- how long does it take to fetch data in components and pages
- how long does it take to process js
- how long does it take to render
- and so on ..

Thanks in advance,

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2285">#c2285</a>)</em></sub></div>

**Comment by justin-schroeder** [comment]
@awawronski did you ever get further clarity on this? I’m trying to trace performance issues in a nuxt build I just completed and I’m struggling to get any useful data

**Comment by justin-schroeder** [comment]
Agreed, I’m trying to use node’s built in profiling:

```
npm run build
node —prof node_modules/.bin/nuxt
# (run ab or a bunch of requests another way)
node —prof-process isolation-xxxxx.v8.log > processed.txt
```

(Side note `—prof-process` is broken in lots of versions of node 9.x)

However I’m frankly just not familiar with how to use this tick profiling to find bottlenecks. Very open to community suggestions.

**Comment by galvez** [comment]
@awronski Closing this issue as there's been no updates in over 90 days. Profiling specific steps of the Nuxt pipeline would require a lot of tweaking in its internals. This is likely to be a project of its own.
