### ISSUE TITLE
On minifying images

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt.js#2627]
I have difficulties in minifying images. I read the docs about extending the Webpack configuration. However, this code does not do anything to my assets.

```js
const imageminloader = require('imagemin-webpack').imageminloader

module.exports = {
  ...
  build: {
    extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          test: /\.(png|jpe?g|gif|svg)$/,
          use: [{
            loader: 'url-loader',
            query: {
              limit: 1000, // 1kB
              name: 'img/[name].[hash:7].[ext]'
            }
          }, {
            loader: 'imageminloader'
          }]
        })
      }
    }
  }
  ...
}
```

After running `nuxt generate`, the output does not produce any error and my assets remain untouched. Is there anything I misunderstand?

I also searched for a property in the `generate.minify` object without success.

As for static files, I suppose they are completely unplugged from Webpack and there is no way to minify images with Nuxt.

Thank you for your help.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2286">#c2286</a>)</em></sub></div>

**Comment by JGJP** [comment]
The Nuxt Webpack config already has a rule to handle images, so you need to modify that instead of pushing a new rule.

`
node_modules/nuxt/lib/builder/webpack/base.config.js`:
```
...
{
  test: /\.(png|jpe?g|gif|svg)$/,
  loader: 'url-loader',
  options: {
    limit: 1000, // 1KO
    name: 'img/[name].[hash:7].[ext]'
  }
},
...
```

I'm using a different image optimization plugin (maybe you want to try it) but I've got it working in Nuxt like this:

`nuxt.config.js`:
```
module.exports = {
  ...
  build: {
    extend(config, { isDev, isClient, isServer }){
      config.module.rules.forEach((rule) => {
        if (rule.test.toString() === '/\\.(png|jpe?g|gif|svg)$/'){
          rule.use = [
            {
              loader: 'url-loader',
              options: {
                limit: 1000,
                name: 'img/[name].[hash:7].[ext]'
              }
            },
            {
              loader: 'image-webpack-loader',
              options: {
                mozjpeg: {
                  progressive: true,
                  quality: 65
                },
                optipng: {
                  enabled: false,
                },
                pngquant: {
                  quality: '65-90',
                  speed: 1,
                  verbose: true
                },
              }
            },
            ];
          delete rule.loader;
          delete rule.options;
        }
      })
    }
  },
  vendor: ['image-webpack-loader'],
  ...
}

```

**Comment by MichaelJCole** [comment]
See also: https://github.com/wemake-services/nuxt-imagemin
