### ISSUE TITLE
'Leave' JS transition hooks not running gsap tweens!

### ISSUE THREAD

**Issue by huxleydigitaluk** [nuxt/nuxt.js#2631]
Hi,

We followed Sarah Drasner's tutorial here: https://css-tricks.com/simple-server-side-rendering-routing-page-transitions-nuxt-js/ to introduce us to the power of page transitions!  All going great with CSS and the 'enter' related hooks, but we just aren't having any luck running gsap tweens on our 'leave' hooks.  

It's all new to me so likely there is an issue in the code but unsure.

I've included a stripped down version of what we're trying to achieve, we're getting output form the console logs but cant get the tweens to run.  Exactly the same code on 'before-enter' and 'enter' and we don't have a problem.

Any help much appreciated!

```vue
<template>
<div class="container">
	<div class="work">
		<nuxt-link to="contact">
			Our Page content here.
		</nuxt-link>
	</div>
</div>
</template>

<transition 
  @before-enter="beforeEnter"
  @enter="enter"
  @after-enter="afterEnter"
  @enter-cancelled="enterCancelled"

  @before-leave="beforeLeave"
  @leave="leave"
  @after-leave="afterLeave"
  @leave-cancelled="leaveCancelled"
  :css="false">
 
 </transition>
<script>
import { TweenMax, Back } from 'gsap'
export default {
    transition: {
        mode: 'out-in',
        css: false,
        
        beforeLeave (el) {
            console.log("BEFORE LEAVE (INDEX.VUE)");
            TweenMax.set(el, {
                opacity: 0
            })
        },
        leave (el, done) {
            console.log("LEAVE (INDEX.VUE)" );
            TweenMax.to(el, 1, {
                opacity: 1
            })
            done()
        }
    }
}
</script>
```

**Comment by huxleydigitaluk** [comment]
Hi @pi0, is there an issue with our code?

**Comment by huxleydigitaluk** [comment]
Is it a nuxt issue?

**Comment by morganlegal** [comment]
As far as I know, which is not a lot, the `done` function in transitions tells nuxt the transition is done. So in your example you're starting a tween but at the same time your telling the transition is done so the page component is remove.
I would do the following:
```
leave (el, done) {
    console.log("LEAVE (INDEX.VUE)" );
    TweenMax.to(el, 1, {
        opacity: 1,
        onComplete: done
    })
}
```

**Comment by huxleydigitaluk** [comment]
Hi @morganlegal 

That seems to have done the trick!  Awesome! The exact change you made fixed it so now we have all the control we need for our transitions.

@pi0 we will close this issue as it was a problem with our code.

Thanks again

**Comment by morganlegal** [comment]
Glad it helped
