### ISSUE TITLE
Website not built properly after running 'nuxt generate'

### ISSUE THREAD

**Issue by rockcs1992** [nuxt/nuxt.js#2636]
Hi guys, first of all let me say thanks for the amazing framework!
I'm building a personal website with nuxtJS these days. I have finished the development work however when I run `nuxt generate` and host the dist folder on my server, the website is not complete and something is different from how it looks in development mode. 

I have four pages in the site, and I put all of the images under `/static/img` folder. When I host the dist folder, it is trying to search image under `/{pagename}/img` folder for each page, which is causing the images to break.Must I separate the images based on what page they belong to? 

Also, it seems that the files are not loaded correctly. The screenshot below is the first load of the site
![screen shot 2018-01-18 at 11 13 58 pm](https://user-images.githubusercontent.com/16792420/35134613-6d4b2ca8-fca5-11e7-996c-58ffd250b5ce.png)

Any ideas?

P.S. Url for the project: https://github.com/rockcs1992/Personal-Website

**Comment by limichange** [comment]
which `dist` do you host ? `project/dist` or `project/.nuxt/dist` ?

**Comment by rockcs1992** [comment]
I'm hosting project/dist

**Comment by limichange** [comment]
Which version of nuxtjs are you using?

**Comment by rockcs1992** [comment]
It's 1.0.0

---------------------
Shi Cheng
Georgia Institute of Technology [2017]
chengshi1219@gmail.com
470-435-9593

2018-01-19 8:21 GMT-05:00 Limichange <notifications@github.com>:

**Comment by limichange** [comment]
This project?
https://github.com/rockcs1992/Personal-Website

**Comment by rockcs1992** [comment]
Correct. I just updated it to the latest. Is there anything wrong with my
file structure?

---------------------
Shi Cheng
Georgia Institute of Technology [2017]
chengshi1219@gmail.com
470-435-9593

2018-01-19 8:26 GMT-05:00 Limichange <notifications@github.com>:

**Comment by Zurnaz** [comment]
The router base in the nuxt.config.js makes everything point to root when generating static content.

Changing it to either './' or  /Portfolio/ (In your case) should fix it but breaks the npm run dev

Documentation here
https://nuxtjs.org/faq/github-pages

I'm debugging a separate issue but this fixed it for both cases allowing me to use "npm run dev" and "npm run generate"  properly

You will also need to update the nuxt.config.js router base and package.json generate script sections.
https://github.com/Zurnaz/nuxt-example/blob/master/nuxt.config.js
https://github.com/Zurnaz/nuxt-example/blob/master/package.json

**Comment by rockcs1992** [comment]
@Zurnaz Thanks for your reply. I changed the router settings and the 'generate' script, but it doesn't seem to solve my problem. All the pages except for the homepage have a problem finding correct file path. Like the pic shows below.
![screen shot 2018-01-19 at 7 10 52 pm](https://user-images.githubusercontent.com/16792420/35177373-b783a550-fd4c-11e7-9a55-215d99ad98bc.png)
I have uploaded the dist folder to the repo. Please have a look at your convenience. Thanks!

**Comment by 2xAA** [comment]
You must tell webpack to resolve the paths within your `nuxt.config.js` for you otherwise the generator can't pack and put them in the right place.

To do this, specifically to your project, you should change this:

```JavaScript
script: [
      { src: 'js/modernizr.js' },
      { src: 'js/jquery-2.1.1.js', body: true },
  //    { src: 'js/smoothscroll.js', body: true },
      { src: 'js/bootstrap.min.js', body: true },
      { src: 'js/jquery.mixitup.js', body: true},
      { src: 'js/custom.js', body: true }
    ],
  },
  css: ['assets/css/font-awesome.min.css', 'assets/css/bootstrap.min.css','assets/css/style.css'],
```

to this

```JavaScript
script: [
      { src: '~/static/js/modernizr.js' },
      { src: '~/static/js/jquery-2.1.1.js', body: true },
  //    { src: '~/static/js/smoothscroll.js', body: true },
      { src: '~/static/js/bootstrap.min.js', body: true },
      { src: '~/static/js/jquery.mixitup.js', body: true},
      { src: '~/static/js/custom.js', body: true }
    ],
  },
  css: ['~/static/css/font-awesome.min.css', '~/static/css/bootstrap.min.css','~/static/css/style.css'],
```

The reason for this working in dev is that static files are always served from the route, so relative paths will work in dev, however when webpack transforms these files through loaders it will move the files and place them in different directories with hashed filenames, so your built version will be different, especially if you've configured Vue Router to have a different base path than `/`.

Learn about the default aliases within nuxt.js here:
https://nuxtjs.org/guide/directory-structure#aliases

**Comment by limichange** [comment]
@rockcs1992 
Interesting issue. I think github can't expore `_nuxt` floder. You need to config `publicPath` and `router.base`.

This is demo: https://limichange.github.io/Personal-Website/ and this is code https://github.com/limichange/Personal-Website.

Some error i have fixed, you can look code.

**Comment by limichange** [comment]
🤔  Maybe i should to update the nuxtjs document.

**Comment by rockcs1992** [comment]
@limichange Thanks so much helping me with this! Yeah I think the document might need to be clearer, especially to people who are not familiar with webpack. (like me)
BTW with your approach, there is a weird problem for my site. Say I'm on home page and click on portfolio nav link, the pictures on portfolio page is loaded but will not show up until I refresh the page. Do you have any clue what might be the reason?

**Comment by limichange** [comment]
If you direct go to the page, browser get the html file, jquery plugin is fine, because image has load. But if you go to the page by click link, webpage update by loading js file, not html file. The jquery plugin has ran before you click link, jquery plugin can't find images, so you need to run it again. 

Run it at `Portfolio.vue` again.
```js
$(function(){
     $('.works').mixItUp();
});
```

😅  my english isn't great, can you understand it?

**Comment by rockcs1992** [comment]
@limichange I totally understand it. Thanks for your time and efforts!
BTW I just tried to deploy to github manually, and yes github cannot recognize _nuxt folder for some reason. And I think that should definitely be pointed out in documentation

**Comment by NicoPennec** [comment]
On GitHub Pages, you have to keep the `.nojekyll` file generated by `npm run generate` in `dist`folder.

I don't see this file in your project : https://github.com/rockcs1992/rockcs1992.github.io

More details here:
https://github.com/nuxt/nuxt.js/blob/7d960b03f72e81aa72ca7569ba0154426c198bfb/lib/builder/generator.js#L176-L179

> Add .nojekyll file to let Github Pages add the _nuxt/ folder
    https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Comment by limichange** [comment]
@NicoPennec so weird, nuxtjs don't generate it.

**Comment by NicoPennec** [comment]
@limichange 

I have tried with the @rockcs1992'project, it works fine on `npm run generate`

The issue come from `npm run deploy` script : https://github.com/rockcs1992/Personal-Website/blob/master/package.json#L14

Retry with this `dotfiles` flag:
```json
"deploy": "gh-pages --dist --dotfiles=true"
```

**Comment by IlhamWahabiGX** [comment]
How to fix this if using push-dir? I'm encountered this issue too.

**Comment by limichange** [comment]
@IlhamWahabiGX You mean `push-dir` ignore `.nojekyll` file?

**Comment by IlhamWahabiGX** [comment]
@limichange nope, I mean same  [error](https://puu.sh/Ac0va/b827f2fb24.png) when this issue created.

**Comment by IlhamWahabiGX** [comment]
Looks like I should open new issue?

**Comment by IlhamWahabiGX** [comment]
ok [here](https://github.com/nuxt-community/create-nuxt-app/issues/52) it is

**Comment by itsmichaeldiego** [comment]
@NicoPennec, Thank you for the fix using `dotfiles` you [provided above](https://github.com/nuxt/nuxt.js/issues/2636#issuecomment-361852993) helped me through it!

@IlhamWahabiGX! Thanks for the favicon fix you [provided above](https://github.com/nuxt/nuxt.js/issues/2636#issuecomment-385174823) and opening https://github.com/nuxt-community/create-nuxt-app/issues/52
