### ISSUE TITLE
I can load vue-multiselect, but I have vue-warn

### ISSUE THREAD

**Issue by phenrigomes** [nuxt/nuxt.js#264]
Multiselect use:

```
<multiselect v-model="search.city" label="name" 
    placeholder="City" track-by="id" options="cities" :show-labels="false"></multiselect>
```

Console warn:

vue.runtime.common.js:521 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside 'p', or missing 'tbody'. Bailing hydration and performing full client-side render. 

If I remove <multiselect> the warn does not show.

**Comment by Atinux** [comment]
It's because vue-multiselect is not compatible with SSR yet. His author is actually working on it.

In the meantime, you can ignore this warning.
