### ISSUE TITLE
How to use js animation when the page is changing

### ISSUE THREAD

**Issue by RhysXia** [nuxt/nuxt.js#2645]
I know it's easy to use `css` animation when the page is changing. But if  is there a way to create animation with `js`?
I want to use a common js animation before every router changes.

Is there anyone give me a solution?
Thank you!

**Comment by timrijkse** [comment]
You can use the transition hook like so:

```
export default {
  transition: {
    enter (el, done) {
      console.log('enter!')
      done()
    }
  }
}
```

**Comment by RhysXia** [comment]
@timrijkse 
Thank you. 
It turned out that the `transition` property in `nuxt.config.js`  supported the hook function, and I didn't see it in the official document before. It was my carelessness.
