### ISSUE TITLE
npm generate creates a static page but onclick does not trigger

### ISSUE THREAD

**Issue by Zurnaz** [nuxt/nuxt.js#2646]
**Expected behavior:** 
"Can you see me" button appears and hides when the "show/hide" button is pressed.
**Current behavior:** 
The button does nothing when the "show/hide" button is clicked.
**Notes:**
The button appears and hides as expected when using `npm run dev `or `npm run build + npm run start`
I feel like I must be doing something silly or misunderstanding how nuxt works.

Example page:
https://zurnaz.github.io/nuxt-example/
Repo:
https://github.com/Zurnaz/nuxt-example

**Comment by 2xAA** [comment]
I feel like on your GitHub pages example, the router doesn't know where it is but the content is prerendered, so the Vue component isn't rendered but the 404 page doesn't render either.

Try setting the router's base path to `/nuxt-example/` as that is the base path for your example page.

You can do this in the `nuxt.config.js` file
https://nuxtjs.org/api/configuration-router/

**Comment by Zurnaz** [comment]
Yep you were right, I was trying to be smart using base: ./ and I figured since I got no errors it must be something else. Solved.
