### ISSUE TITLE
How to handle a huge amount of posts/pages (1000+)

### ISSUE THREAD

**Issue by Jones-S** [nuxt/nuxt.js#2647]
Hi there
I am facing the following challenge: we have a website with 3000+ posts, which we fetch as json files from a wordpress REST API (it's not important where they come from actually...).

We have multiple problems with such an amount of posts:

- Build time of all the static html files
- Loading time within single page app of all the data
- Warning that app.js is too big (see image)

**Now in general. How would you tackle this problem?**

**App.js/loading all data**
So far we thought of distributing all the posts data into json-files of 10 posts each. So, for 100 posts, we get 10 json files). With this we also just built a pagination. We load the data of 10 posts into the store, when starting our app. The first page of posts displays the first 10 posts. If you proceed to the second page, we load the next 10 posts dynamically.

When creating the routes (nuxt generate) we generate the routes based on these json files. This seems to make our entry point app.js very big. So far I have a poor understanding what the app.js must be able to do, but why does it have to store all the posts data?
For our purpose it would be sufficient if it stored the data for a couple of pages and (maybe) the first 10posts. All the other posts don't have to be in the app.js.

How can we exclude it from the app.js?

**Build time**
Let's imagine we have made one small change to one of our 3000 posts. The change is just about content, not it's layout. Now we execute nuxt generate. How can we omit creating 3000 new static html files and just recreate the changed post html?
Same for adding files?
(We think that on a CDN service like netlify, the build time (incl. nuxt generate) will increase to an unpleasant duration, with such an amount of posts -> making the time to a visible change of the post unacceptable.

Is there a way to only partially recreate the static htmls? If yes, how?
If no, what other options do we have?

<img width="808" alt="image" src="https://user-images.githubusercontent.com/7059580/35161891-daa71f0e-fd41-11e7-99bc-2a9c685d751e.png">

Thank you for any help. May this be some general information what the app.js has to store and what is optional or specific hints how to approach the mentioned problems.
Cheers

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2302">#c2302</a>)</em></sub></div>

**Comment by piyushchauhan2011** [comment]
`nuxt generate --no-build` @Jones-S ?

Nuxt 1.0 release notes... https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0

**Comment by Jones-S** [comment]
Hm. Thanks, but I'm not sure... I do want to build normally, so this would not bring the app's size down. Just in exceptional cases where I change one post I could use somethin like the --no-build flag. Unfortunately I don't really what happens instead. `Useful for conditions when just dynamic routes are being changed. This makes incremental builds much faster`.
First: in a case where I change one posts content this would be no option right? Second: what is done during the build process, when setting this no-build flag?

**Comment by pi0** [comment]
@Jones-S You are right. Adding `--no-build` flag just reduces build time, not the entire process. But it is essential for incremental scenarios like what you need to prevent changing js chunk hashes after adding each new post. For updating only one blog post additional scripts may be required.

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
