### ISSUE TITLE
Head is not pre-rendered with command nuxt generate

### ISSUE THREAD

**Issue by mfikria** [nuxt/nuxt.js#2648]
When we generate the project to static-content, head is not pre-rendered. So you will see in few seconds the HTML is not well-formatted.

I think it would be better to pre-rendered the head.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2303">#c2303</a>)</em></sub></div>

**Comment by limichange** [comment]
Could you provide some code ?

**Comment by PatrikLythell** [comment]
This would be really useful for meta tags since facebook scraper doesn't seem to parse javascript.

**Comment by MichaelSchober** [comment]
I am currently trying to achieve the same. 
Is this possible with Nuxt? 
This would be a really useful feature for static hosting and SEO.

**Comment by galvez** [comment]
@Atinux unable to reproduce in nuxt-edge. Set up a test repo to make sure.
