### ISSUE TITLE
data-src doesn't load images from assets folder

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2650]
I am using great https://github.com/aFarkas/lazysizes package

It need such code

```html
    <img data-src="~assets/images/kitten-large.png" class="lazyload lazy" />
```

But with `data-src` attribute Nuxt doesn't load images.
What should I do?

**Comment by NicoPennec** [comment]
Try to move your images to `/static/images` folder and use this path :

```html
<img data-src="/images/kitten-large.png" class="lazyload lazy">
```

The `assets` directory should contain only your un-compiled assets such as LESS, SASS, or JS.

**Comment by iamdubx** [comment]
@NicoPennec yes this is working from `static` or from another domain, but I am wondering why t doesnt work from `aasets`? I have images in `assets` and Nuxt/webpack using them succesfully. Why you said I shouldn't store images there? Otherwise I can't use base64 inlining, for example.

**Comment by iamdubx** [comment]
Other words, I guess I need to store only small images in `assets` that I want to proceed with webpack? Right?

**Comment by iamdubx** [comment]
Also, I have other plugins that use custom attributes to load images - and they working fine with images from `assets`. How to make this particular package to work? I mean, it's best in class solution, it whould be nice to make it work properly with Nuxt.

**Comment by clarkdo** [comment]
You can add `data-src` to `transformToRequire` via `build.extend` in `nuxt.config.js`
```js
module.exports = {
  build: {
    extend(config, { isDev }) {
      const vueLoader = config.module.rules.find((rule) => rule.loader === 'vue-loader')
      vueLoader.options.transformToRequire['img'] = ['src', 'data-src']
    }
  }
}

```

**Comment by shindeefranco** [comment]
Any feedback on this?

**Comment by clarkdo** [comment]
@shindeefranco 
Hope this can help you https://github.com/nuxt/nuxt.js/issues/2008#issuecomment-405521354
