### ISSUE TITLE
Cannot read property 'breakpoint' of undefined

### ISSUE THREAD

**Issue by Tyki** [nuxt/nuxt.js#2651]
Using : "nuxt": "^1.0.0-rc11".

I have two roads (aka two components) :
```
/       (index.vue)
/app (app.vue)
```
Everything works fine with SSR.

When I land on the homepage, I have a `router-link` to `/app` that works perfectly fine but, when I do F5, CTRL+R, CTRL+shift+R directly on the sub-page `/app`, I have the following error : 

`Cannot read property 'breakpoint' of undefined`

I MUST go back to `/`, click again on my link to `/app` and at this point, I can see the content of my `/app` page again. It's impossible to do a simple F5 on `/app since it directly triggers this error

Any ideas on how to fix this?

**Comment by clarkdo** [comment]
It should because that you may have used a lib doesn't support SSR, you can use `no-ssr` to remove the component ssr.

https://nuxtjs.org/api/components-no-ssr#the-lt-no-ssr-gt-component
