### ISSUE TITLE
Promissify is not a function

### ISSUE THREAD

**Issue by raultrysw** [nuxt/nuxt.js#2652]
I have the 8 version of node but when i run npm run dev this happens
![imagen del error](https://i.imgur.com/penT0Ql.png)

**Comment by raultrysw** [comment]
And a I have read this thread but dont is useful for me:
https://github.com/nuxt/nuxt.js/issues/2545

**Comment by pi0** [comment]
Hey. Can you please check electron version?

**Comment by raultrysw** [comment]
My electron version is 1.7.10

**Comment by pi0** [comment]
It seems [1.7.10](https://github.com/electron/electron/tree/v1.7.10) is based on node [7.9](https://github.com/electron/node/commit/0794478e4938d8193516ab49926e03cb068febe6). If possible please try upgrading to `1.8.x` or beyond.

**Comment by raultrysw** [comment]
Thanks MAN

**Comment by chanlito** [comment]
@raultrysw, if this helped pls close the issue. @pi0 there are too many issues unrelated to Nuxt can we do something about that?
