### ISSUE TITLE
Accessing css links on html template

### ISSUE THREAD

**Issue by BatuhanK** [nuxt/nuxt.js#2655]
According to [docs](https://nuxtjs.org/guide/views#document) we can extend html template and that's works like a charm.

```html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}
  </body>
</html>

```

Here is the question; what if I want to move only link tags (css) to bottom of the page, is it possible?

```html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }} <!-- but somehow without css -->
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}

    {{ CSS }} <!-- only link tags (css) -->
  </body>
</html>

```

Is there any way to achieve this without modifying [this section](https://github.com/nuxt/nuxt.js/blob/10d1b5974c4939f89335245d7ce1c8b3213713f6/lib/core/meta.js#L53) and creating custom `CSS` variable

**Comment by NicoPennec** [comment]
CSS import must be in `<head>` !

if you want create a custom css variable, you can add that in your `*.vue` file in `<style>` section.

**Comment by BatuhanK** [comment]
@NicoPennec I just want to try and expirement a technique which is described in [Google's article](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery)

```html
<noscript id="deferred-styles">
  <link rel="stylesheet" type="text/css" href="small.css"/>
</noscript>
<script>
  var loadDeferredStyles = function() {
    var addStylesNode = document.getElementById("deferred-styles");
    var replacement = document.createElement("div");
    replacement.innerHTML = addStylesNode.textContent;
    document.body.appendChild(replacement)
    addStylesNode.parentElement.removeChild(addStylesNode);
  };
  var raf = window.requestAnimationFrame || window.mozRequestAnimationFrame ||
  window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;
  if (raf) raf(function() { window.setTimeout(loadDeferredStyles, 0); });
  else window.addEventListener('load', loadDeferredStyles);
</script>

```

**Comment by BatuhanK** [comment]
@clarkdo do you have any idea how I can achieve this? I thought that I can use `render:route` hook for moving css but I think it won't be efficient at all

**Comment by clarkdo** [comment]
If my pr gets merged, you can use `body: true` to append noscript to body.
```js
head: {
    noscript: [
      { id: 'deferred-styles', innerHTML: '<link rel="stylesheet" type="text/css" href="small.css"/>', body: true }
    ]
  }
```
