### ISSUE TITLE
Update route parameters without re-rendering

### ISSUE THREAD

**Issue by alexgarrett** [nuxt/nuxt.js#2658]
Nuxt.js has been an absolute breeze to move my site over to. However, I have a scenario as follows:

```
+ course
   - _slug
      - _part.vue
```

I end up with the path:

`/course/nuxt-is-awesome/introduction`

I'd like to be able to:

```
this.$router.push({ params: { part: 'next-part' } })
```

and not have the page completely re-render. Instead, I'd like to add a watcher to the route param and just update the Vuex store, using:

```
watch: {
   '$route.params.part' (part) {
      // ...
   }
}
```

The way I've achieved this currently is using a query string, e.g. `?part=introduction`, and then pushing to the query string (which does not re-render) and then `watch`ing the query string to do the above.

Is this possible?

**Comment by clarkdo** [comment]
Your current solution is good and unfortunately vue-router doesn't support you expected partial way.

Another idea is try to use `data` or `state` together with `dynamic components` to achieve partial rendering:

```js
<template>
  <div>
    <component :is="comp"></component>
  </div>
</template>

<script>
export default {
  data: () => ({
    comp: ''
  }),
  components: {
    'example': () => import('@/components/example'),
    'demo': () => import('@/components/demo'),
    //...
  },
  mounted() {
    this.comp = 'example'
  }
}
</script>
```
