### ISSUE TITLE
app.styl not found on Nuxt.js - Vuetify Starter Template

### ISSUE THREAD

**Issue by sircEUNHO** [nuxt/nuxt.js#2659]
I'm trying to fix this error because it always keeps saying that app.styl is not found on dependency.

![image](https://user-images.githubusercontent.com/30286632/35198376-e9c0b34a-ff28-11e7-9a13-792d5078f96f.png)

But I did all correctly according to here:
https://github.com/nuxt/nuxt.js/tree/dev/examples/with-vuetify

this is my screenshots:
nuxt.config.js
![image](https://user-images.githubusercontent.com/30286632/35198426-d732ca14-ff29-11e7-80e6-c6abcc3ee691.png)

app.styl
![image](https://user-images.githubusercontent.com/30286632/35198429-df094a56-ff29-11e7-98fe-c7600d2aea75.png)

vuetify.js
![image](https://user-images.githubusercontent.com/30286632/35198456-2bba647a-ff2a-11e7-95a5-e3d19b28ac35.png)

Error on Localhost:
![image](https://user-images.githubusercontent.com/30286632/35198537-4923bee8-ff2b-11e7-9067-8c78eb229e7c.png)

Please help me fix it?

**Comment by BruceHem** [comment]
@sircEUNHO did you npm i stylus stylus-loader yet?

**Comment by sircEUNHO** [comment]
Not yet

**Comment by sircEUNHO** [comment]
@BruceHem Done! gonna close this issue now, Thanks for giving me the correct answer

**Comment by diegotejadav** [comment]
@chanlito [answer](https://github.com/nuxt/nuxt.js/issues/2659#issuecomment-359311694) worked for me!
Thank you!
