### ISSUE TITLE
Dev command not working in linked folder inside docker container

### ISSUE THREAD

**Issue by brenodouglas** [nuxt/nuxt.js#266]
I tried run nuxt using docker container, but running 'npm run dev' command my build froze in one step of build, it is my output: 

```shell
> nuxt@1.0.0 dev /var/www/nuxt
> nuxt

  nuxt:build App root: /var/www/nuxt +0ms
  nuxt:build Generating .nuxt/ files... +2ms
Ready on http://localhost:8000
  nuxt:build Generating routes... +33ms
  nuxt:build Generating files... +30ms
  nuxt:build Adding webpack middleware... +118ms
Build completed in 13.868s

webpack built 2325b7a6961baf0d2745 in 13873ms
```

Build stopped in this location and no continue to run app and also not stop with error.
Inside container i create other folder not linked to my host folder and in this folder the command running normally.

This problem occurs only with nuxt app. Other template of vueJs no are problem.

**Comment by Atinux** [comment]
Hi @brenodouglas 

I don't understand, the logs from nuxt.js are fine, nothing is frozen and the server is listening on localhost:8000. 

Because you are using Docker, I believe that you should run nuxt with PORT=0.0.0.0 so you can access it in the local network.

**Comment by brenodouglas** [comment]
Hi @Atinux, 

I've tried using this reference:

Https://nuxtjs.org/api/configuration-dev/

And really you're right, it's now working properly.

Can close the issue.

**Comment by raisiqueira** [comment]
hey, @brenodouglas. como conseguiu? podes me dar uma força?
