### ISSUE TITLE
resolve static page routes before dynamic ones to prevent conflict

### ISSUE THREAD

**Issue by alidcastano** [nuxt/nuxt.js#2662]
If I have both static and dynamic routes in the same level, it seems that they are included in the router based on their location in the `pages` folder. However, I feel that it would be preferable if dynamic routes were included only after all static routes were pushed to the routes array so that they could both coexist in the same level.

Example: 

```
- index
   - _slug.vue
- index 
- login.vue
- register.vue
```
(^The index/`_slug` route comes first, so it is matched before the `login` and `register` routes.)

My current workaround is prepending the static pages with a `-` so that Nuxt ignores them, and extending the Nuxt router myself to include them first. But opening this issue in case this is a behavior that should be included into the framework.

**Comment by clarkdo** [comment]
I suggest that you can use a consistent behavior in the `pages` 😄 :

```
- index
   - _slug.vue
   - login.vue
   - register.vue

// or

- index
- _slug.vue
- login.vue
- register.vue

```

**Comment by clarkdo** [comment]
@alidcastano 
I opened a pr try to solve your problem, and you can also use `build.createRoutes` to create specific order of routes you need.

**Comment by alidcastano** [comment]
Hmm I'm  not familiar with `createRoutes` and don't see it in docs.

I'm using extendRoutes right now (is that what you mean?) - 

ex.
```
   extendRoutes (routes, resolve) {
      routes.unshift(
        {
          path: '/login',
          component: resolve(__dirname, 'pages/-login.vue')
        },
        {
          path: '/register',
          component: resolve(__dirname, 'pages/-register.vue')
        }
      )
    }
```

But thanks for opening PR as I would prefer to have it included into framework if possible
