### ISSUE TITLE
Loss of prototype information by initial state passing from server to client

### ISSUE THREAD

**Issue by endaaman** [nuxt/nuxt.js#2663]
In Vuex it is possible to store class instance in state, but Nuxt has a problem with this.

When a state initiated on the server side is handed over to the client, the class instances get turned into a plain objects. I guess this is due to deserialization of all serialized state by server side rendering.

If you do not use Nuxt, you write `new Store (...)` and `store.replaceState()`, so there is a chance to modify plane object to class instance, but we can not when using Nuxt.

Are there any good ideas on this? I thought that we needed a workaround like `nuxtServerInit ()`, which can modify state just after (or before) `replaceState ()` is executed.

Regards.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2317">#c2317</a>)</em></sub></div>

**Comment by BatuhanK** [comment]
Hello, as you mentioned server passes store to the client with DOM. 

I think you can write your objects serialized version to the store on the server (for example using [this](https://www.npmjs.com/package/serialize-javascript) and deserialize on client.

**Comment by endaaman** [comment]
I think your idea is not good for two following reasons

- We always have to convert state from object to string
- The package `serialize-javascript` does not serialize prototype

Until now I have a workaround below.

```js
// store
export class Person {
  constructor(obj) {
    Object.assign(this, obj)
  }
  getFullName() {
    return this.givenName + ' ' + this.familyName
  }
}

export const state = () => ({
  persons: [],
})

export const mutations = {
  SET_PERSONS(state, items) {
    state.persons = items.map((a) => new Person(a))
  },
  WRAP(state, items) {
    state.persons = state.persons.map((a) => new Person(a))
  },
}

export const actions = {
  nuxtClientInit({ commit }) {
    commit('WRAP')
  },
  async fetchPersons({ commit }) {
    const data = await fetch('/articles')
    commit('SET_PERSONS', data)
  },
}
```

```vue
<script>
// common layout view
export default {
  created() {
    if (!process.isServer) {
      // re-convert the plain objects to class intances here
      this.$store.dispatch('nuxtClientInit')
    }
  }
}
```

However, this is not perfect because we can not know when the re-conversion is triggered. So I think the `nuxtClientInit()` is needed and should be called just after the store replaced (with initial state) and just before views instantiated.

**Comment by manniL** [comment]
Unfortunately, this is a **SSR caveat**. Explanation and workaround can be found in https://github.com/nuxt/nuxt.js/issues/3579#issuecomment-411240994
