### ISSUE TITLE
nuxt express post conflict?

### ISSUE THREAD

**Issue by ac88** [nuxt/nuxt.js#2664]
i use https://github.com/nuxt-community/express-template

but i don't know why Build only in dev mode?
```js
// Build only in dev mode
if (config.dev) {
  const builder = new Builder(nuxt)
  builder.build()
}
```

in here define a post router like this https://github.com/nuxt-community/express-template/blob/master/template/server/api/users.js

```js
import { Router } from 'express'

const router = Router()

router.post('/doc_enter', function(req, res, next) {
  if (req.body.pw) {
    return res.json({success:req.body.pw})
  }
})
```

but req.body is undefined

i use bodyParser  at https://github.com/nuxt-community/express-template/blob/master/template/server/index.js

```js
const bodyParser = require('body-parser')

app.use(bodyParser.json({limit:'900kb'}))

app.use('/api', api)
const nuxt = new Nuxt(config)

// Build only in dev mode
if (config.dev) {
  const builder = new Builder(nuxt)
  builder.build().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}

app.use(nuxt.render)
```
now the req.body has value .but other proxy PHP API timeout  which has post data

```js
superagent
  .post('/api/user/login')
  .send({ ip, ...form }) // sends a JSON post body
  .set('accept', 'json')
  .end((err, res) => {
    // Calling the end function will send the request
  })

````

The request headers **Provisional headers are shown**

![tim 20180122165151](https://user-images.githubusercontent.com/20198303/35212323-b48aa4e4-ff94-11e7-8bd6-9f2bd46009dc.jpg)

What should i do if i wanna  keep the proxy PHP API and express middleware api all be right?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2318">#c2318</a>)</em></sub></div>

**Comment by ac88** [comment]
i use 
```js
app.use(bodyParser.urlencoded({extended:false}))
```

```js
 const data = await this.$axios.$get('/api/doc_enter', {
        params: { pw: this.pw },baseURL:'/'
      })
```

solve this problem

**Comment by ruslankonev** [comment]
yes, yesterday i got the same problem. Maybe nuxt middleware must handle only `get`-methods? I think, this make a sense, because nuxt/vue is at first — a framework for frontend. Or make a option for handle method types.

**Comment by ruslankonev** [comment]
In my case — bodyparser extend false, is not work, nuxt connect intercept request and instead backend, response nuxt middleware 404... =(

**Comment by seanwash** [comment]
@ruslankonev @ac88 I ran into the same issue but ended up also coming across this in the docs: https://github.com/expressjs/body-parser#express-route-specific

Basically, instead of applying bodyparser to all routes, I just add it to the routes that need to use it. Problem solved! For me anyway.
