### ISSUE TITLE
Can't load svg from dynamic src

### ISSUE THREAD

**Issue by Modelair** [nuxt/nuxt.js#2667]
```<img :src="'~/assets/' + value + '.svg'">```
wont work. complies to "~/assets/something.svg", but must be /_nuxt/img/something.a14b0d2.svg
i understand why. but, how to solve it?

**Comment by clarkdo** [comment]
Have a look at : https://github.com/vuejs-templates/webpack/issues/126 and https://github.com/nuxt/nuxt.js/issues/448
You can use `require` inside the `:src`.
