### ISSUE TITLE
Nuxt i18n: Text dissapear for first time

### ISSUE THREAD

**Issue by ekanant** [nuxt/nuxt.js#2668]
I have a layout and have some component on it, use i18n in nuxt example (https://nuxtjs.org/examples/i18n/), but when the is reload from HMR or click on a link then change to this layout for the first time, the text not show but if I refresh browser in this page my text display correctly.

Ps. The component in .vue in pages folder not have the problem as above

My Layout file
<img width="653" alt="screen shot 2561-01-22 at 23 02 26" src="https://user-images.githubusercontent.com/7685075/35230421-8dcba9be-ffc8-11e7-94d9-82dd6bd5b458.png">

Expected:
<img width="201" alt="screen shot 2561-01-22 at 23 07 07" src="https://user-images.githubusercontent.com/7685075/35230615-1be0984a-ffc9-11e7-8d11-d711653d70ec.png">

Result:
<img width="258" alt="screen shot 2561-01-22 at 23 03 32" src="https://user-images.githubusercontent.com/7685075/35230423-8e0bcf26-ffc8-11e7-886c-5378d3e25ed1.png">

**Comment by clarkdo** [comment]
Can you provide your repo ?

**Comment by ekanant** [comment]
1. yarn install or npm install
2. yarn run dev or npm run dev
3. Go to index page 
4. Click Go to inside
5. It will change the page then the content in header navigation not shown
6. If you refresh the browser, the content will come.
[nuxti18n-reproduce.zip](https://github.com/nuxt/nuxt.js/files/1656148/nuxti18n-reproduce.zip)

**Comment by clarkdo** [comment]
`<text>` is not a standard HTML tag, you can remove it and have a try.

**Comment by ekanant** [comment]
Ok, problem solve. Thank you very much @clarkdo
