### ISSUE TITLE
Unable to access process.env from browser

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#267]
Hi,
 I am trying to set baseURL as env variable by defining it in nuxt.config.js

     env: {
        baseURL: 'myserver.com'
    }

But when I console.log(process.env) in the browser. It shows an empty object.

Any reason why this is not working?

**Comment by Atinux** [comment]
Where do you use `console.log(process.env)` exactly (which file in your JS)?

`env` works perfectly, but be aware that if you try to use it in the console of your browser with the chrome dev tools, it won't works since all variables are scoped and not accessible as global.

**Comment by shyamchandranmec** [comment]
@Atinux  I did it under ~plugins/axios.js . In the documentation I found that this can be done. 
I tried console.log(process).
It lists all properties including env. But the values of env in nuxt.config.js is not getting copied.

**Comment by Atinux** [comment]
Even when doing `console.log(process.env.baseURL)`?

What template are you using?

**Comment by shyamchandranmec** [comment]
@Atinux  process object has properties like 

    {title: "browser", browser: true, env: Object, argv: Array[0], version: ""…}

Inside this the value of process is {}

This is how my nuxt.config.js looks

    module.exports = {
    /*
     ** Headers of the page
     */
    head: {
        title: 'starter',
        meta: [
            {charset: 'utf-8'},
            {name: 'viewport', content: 'width=device-width, initial-scale=1'},
            {hid: 'description', name: 'description', content: 'Nuxt.js project'}
        ],
        link: [
            {rel: 'icon', type: 'image/x-icon', href: 'favicon.ico'},
            { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Lato:400,700,900' }
        ]
    },
    /*
     ** Global CSS
     */
    css: [
        {src:'~assets/scss/src/vendor/vendor.scss', lang :"scss"}
    ],
    /*
     ** Add axios globally
     */
    build: {
        vendor: ['axios'],
        postcss: [
            require('autoprefixer')()
        ]
    },
    env: {
        baseURL: 'myserver.com'
    }
};

**Comment by Atinux** [comment]
@shyamchandranmec how do you run your server? Are you using the last version of nuxt.js?

**Comment by shyamchandranmec** [comment]
Yes, I am running the lates verion of nuxt

     "nuxt": "latest",


I tried running it by 
    1. npm run dev
    2. npm run build && npm start

Both had the same issue.

**Comment by Atinux** [comment]
Try to upgrade it by doing `npm update` or `yarn upgrade`.

Can you create a repository reproducing this bug so I can take a look at it?

**Comment by shyamchandranmec** [comment]
@Atinux  . I tried npm update and restarted the server. 

Here is a link to the repo.. [vue-test](https://gitlab.com/shyamchandranmec/vue-test)

**Comment by Atinux** [comment]
@shyamchandranmec 

I see, we set environment variable via webpack. Webpack does a find & replace, you need to use the full env path (not `process.env`, but `process.env.baseURL` for example)

So [here](https://gitlab.com/shyamchandranmec/vue-test/blob/master/plugins/api-server.js#L14), it will work if you set `console.log("client side config is ", process.env.baseURL);`

**Comment by shyamchandranmec** [comment]
@Atinux  Thanks a lot for clarifying this. I spent few hours on this. I think it will be good to add this to the documentation.
