### ISSUE TITLE
When to use <no-ssr> when not to?

### ISSUE THREAD

**Issue by pxwee5** [nuxt/nuxt.js#2678]
Is there a way to clearly know when exactly to use `<no-ssr>`?

I built a screen front end library to determine screen sizes that utilises the `window.matchMedia()` function and got the `window is not defined` error while working on html conditionals. So I fixed it with adding `<no-ssr>` tag. But still quite confused at the moment. 

Not sure if I missed anything from the documentation but SSR is quite confusing for me at the moment. 

If anyone can help shed some light here it will be great!

**Comment by clarkdo** [comment]
`no-ssr` is a wrapper of non SSR friendly components, if your components don't support SSR, you can wrap them with the `no-ssr` to avoid unexpected error (such as: there is no `window` in server 
side).

**Comment by tpin85** [comment]
Hello,
Component work fine when app is fully loaded. But when i refresh the page or if i'm landing directly on this page i get a nuxt error. 

logs says 
> render function or template not defined in component: anonymous

if i look deeper it's vue-server-renderer who return an error. 

for fun i've try to use <no-ssr> but the issue stay the same. 

Anyone have an idea to solve this ?

thanks. 

--sorry for my english, my french is better--
