### ISSUE TITLE
sourcemaps for css/sass

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#268]
I'm using sass in the project and all is good. However, I just realized that sourcemaps is not toggling on. I've  added in the build extend area, which solved it for javascript sourcemaps but sass/css are all being sent to inline styles. 

Here's my build section of nuxt.config.js

```
build: {
    vendor: ['axios', 'moment', 'lodash', 'fuse.js'],
    babel: {
      presets: [
        ['es2015'],
        'stage-2'
      ]
    },
    extend (config, {isClient}) {
      if (isClient) {
        config.devtool = 'eval-source-map'
      }
    },
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style", "css?sourceMap", "resolve-url", "sass?sourceMap"]
        //loaders: ["style", "css", "resolve-url", "sass?sourceMap"]
      },
      {
        test: /\.(png|jpe?g|gif|svg)$/,
        loader: 'url-loader',
        query: {
          limit: 1000, // 1KO
          name: 'img/[name].[hash:7].[ext]'
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 1000, // 1 KO
          name: 'fonts/[name].[hash:7].[ext]'
        }
      }
    ]
  }
```

**Comment by Atinux** [comment]
@uptownhr in development mode, we use hot-reloading so that's why the styles are directly put in the header of the page directly.

**Comment by uptownhr** [comment]
@Atinux that is expected with HMR and webpack but with webpack config, you are able to turn on sourcemaps for your component styles. Normally by adding ?sourceMap to your sass loader. I read from another ticket before, where you can add ?sourceMap to the lang attribute in your styles tag in the .vue file and it works. However, this limits you to always having sourcemaps on for both dev/production. You also have to always define this -- which is not too bad but it would be great if you can globally toggle on sourcemaps.

**Comment by Atinux** [comment]
I believe this issue will be resolved with the next release 👍

**Comment by uptownhr** [comment]
@Atinux awesome. looking forward to it!

**Comment by uptownhr** [comment]
@Atinux Also how would you enable sourcemaps for sass? Would this be toggled automatically based on the devtool setting? Or would you be able to configure the sass loader somehow?

**Comment by Atinux** [comment]
I don't know yet, when Vue 2.2 will be implemented we will be able to talk about it 👍

**Comment by uptownhr** [comment]
@Atinux ping. Vue 2.2 is released. Thoughts on globally toggling on sourcemaps for sass? Currently, I toggle them on a component by component bases using lang="sass?sourceMaps"

**Comment by Atinux** [comment]
Let's keep the discussion on https://github.com/nuxt/nuxt.js/issues/451
