### ISSUE TITLE
Vendor to big

### ISSUE THREAD

**Issue by acstan** [nuxt/nuxt.js#2681]
I just started this Nuxt project and i only added 2 pages 2 node modules and a bit of logic

i used

>  vue init nuxt/starter

i finished my dev work and i tested out the nuxt build to check the production version and i had some surprising results

![screen shot 2018-01-24 at 4 29 10 pm](https://user-images.githubusercontent.com/17141804/35337499-11356c84-0124-11e8-8c69-0deec73551a7.png)

I couldn't figure out how the vendor file got to that size so i used 

> npm run build -a

 to get some stats on the build and here is the result

![screen shot 2018-01-24 at 4 29 24 pm](https://user-images.githubusercontent.com/17141804/35337573-43e86a82-0124-11e8-89c6-4c2a8bc7abe7.png)

From this stats i see that the biggest files are the Vue related ones and the bn.js

What am i missing ? how can i fix this .. surely i'm missing something so please HELP

**Comment by NicoPennec** [comment]
Issue duplicate with https://github.com/nuxt/nuxt.js/issues/2201
