### ISSUE TITLE
router.back() not working in SPA

### ISSUE THREAD

**Issue by stonexx** [nuxt/nuxt.js#2683]
router.back() not working once after nested redirect in SPA mode.

Here's the example, [https://github.com/stonexx/nuxt-redirect-example](https://github.com/stonexx/nuxt-redirect-example).

**Comment by clarkdo** [comment]
In your repo, when `back` is called then pages will redirect to `/a`, `/a/b`, `/a/b/c/test` again, so it seemed nothing changed, if you add `console.log('/a/b/c/test')` in `fetch` of `/a/b/c/index.js`, you will find the log when clicked `back`.
