### ISSUE TITLE
How to customized nuxt-error.vue

### ISSUE THREAD

**Issue by ac88** [nuxt/nuxt.js#2685]
Server error page render `node_modules\nuxt\lib\app\components\nuxt-error.vue`

`node_modules\nuxt\lib\app\components\nuxt.js:3`

```js
import NuxtError from '<%= components.ErrorPage ? 
((components.ErrorPage.indexOf('~') === 0 || components.ErrorPage.indexOf('@') === 0)
 ?
 components.ErrorPage : "../" + components.ErrorPage) : "./nuxt-error.vue" %>'
```
i use 

```js
components:{
    ErrorPage:'~/components/ErrorPage'
  }
````

in nuxt.config.js

but it is still render nuxt-error.vue not my ErrorPage

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2333">#c2333</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Just `ErrorPage`, no `components` is fine.
```
// nuxt.config.js
module.exports = {
  ErrorPage:'~/components/ErrorPage'
}
```

**Comment by ac88** [comment]
@clarkdo 
```js
// nuxt.config.js
module.exports = {
  ErrorPage:'~/components/ErrorPage'
}
```

this config will cover `layout/error.vue` ,like 404 error

i want customized only node server error,like this

![](https://user-images.githubusercontent.com/20198303/32310615-9298bb4c-bfce-11e7-8cda-decf8c7d3eaf.png)

**Comment by SalvadorDuran** [comment]
@ac88 did you find a solution for this?

**Comment by ac88** [comment]
@SalvadorDuran  I haven't done yet

**Comment by Extarys** [comment]
I'll look into it today, I'm interested too! :)

**Comment by manniL** [comment]
Customize "client-side" error template:

1. Add a `layouts/error.vue` file
2. Customize it

Customize "client-side" error template:

1. Add an `error.html` file under: `app/views/`
2. Customize it :relaxed:
