### ISSUE TITLE
How to integrate HotJar?

### ISSUE THREAD

**Issue by Reechee88** [nuxt/nuxt.js#2688]
Hello,

how can I include the hotjar script? There is no html file, so it is tricky. Could you help me in this issue?

Have a nice day,
Richard

**Comment by jeroenvisser101** [comment]
You can still add scripts to the head by adding them to your `nuxt.config.js` file, [see the docs](https://nuxtjs.org/api/pages-head).

**Comment by Reechee88** [comment]
Yes, I have read that. But honestly.. I couldnt figure it out how to use the hotjar script in this. Thats why I opened this issue. Could you please provide an exact example for Hotjar?

**Comment by jeroenvisser101** [comment]
The best way is probably this:

```js
// nuxt.config.js
{
  // ...
  plugins: ['~/plugins/hotjar']
}
```

and then add your implementation code (without the script tags) to `plugins/hotjar.js` like so:

```js
// plugins/hotjar.js
(function(h,o,t,j,a,r){...})(...);
```

**Comment by Reechee88** [comment]
Wow, this is easy in this way. Thank you man!

I suggest you to put this example to the documentation to help other people struggling with same issue. It is not trivial for the first time,

**Comment by jeroenvisser101** [comment]
It's already in there I see, but not Hotjar specific: https://nuxtjs.org/faq/google-analytics

**Comment by janzheng** [comment]
just curious: do you need to set HotJar under `ssr: false` if you're generating nuxt for static use?
