### ISSUE TITLE
Page/Component specific (S)CSS export / use

### ISSUE THREAD

**Issue by michelbio** [nuxt/nuxt.js#269]
From my understanding, Nuxt builds everything into a single .CSS file as the output. Which is then used on **all pages**. We can define (S)CSS files/modules to be used site wide. And we can define (S)CSS files page/component specific. 

But as far as I see, even if we specify @import on each page/component, eventually during production build everything gets merged into a single .CSS to be used on all pages.

In Vue.js without Nuxt, every page/view loads only the (S)CSS specified for the connected components. Given the static output of Nuxt, is it possible to achieve something like this within Nuxt and/or with Webpack?

**Comment by Atinux** [comment]
Hi @michelbio 

We are aware about this and it's planned to render only the required CSS into the `<head>`.

See https://github.com/nuxt/nuxt.js/issues/12#issuecomment-275897911

**Comment by michelbio** [comment]
Thank you for quick reply on this.
