### ISSUE TITLE
Generating dynamic routes Error: "generate.routes" must be an array

### ISSUE THREAD

**Issue by misscs** [nuxt/nuxt.js#2691]
I'm using Nuxtent content module. I'm following the directions on the [docs](https://nuxtjs.org/api/configuration-generate#routes ) page replaced the URL with local content-api generated by Nuxtent. 

When I run generate command I get the following `Error: "generate.routes" must be an array `

```
const axios = require('axios')

module.exports = {
  generate: {
    routes: function () {
      return axios.get('https://my-api/users')
      .then((res) => {
        return res.data.map((user) => {
          return '/users/' + user.id
        })
      })
    }
  }}

```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2339">#c2339</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
