### ISSUE TITLE
why customize bundle filename occur error in nuxt dev mode?

### ISSUE THREAD

**Issue by highalps** [nuxt/nuxt.js#2692]
**build and start, it is fine.**
but when 'npm run dev',  following error occurred.

```
[nuxt] Error while initializing app TypeError: Cannot read property 'call' of undefined
      at o (manifest.app.js:1)
      at <anonymous>

```

a few hours later, i found customize bundle filenames was crushing nuxt dev mode

in nuxt.config.js
```
module.exports = {
         filenames: {
               manifest: 'manifest.app.js',
               vendor: 'vendor.app.js',
               app: 'app.app.js'
          }
}
```
when remove filenames field, development mode work fine. but i don't know why......

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2340">#c2340</a>)</em></sub></div>

**Comment by highalps** [comment]
i found customize bundle filenames was crushing nuxt dev mode

in nuxt.config.js

```
module.exports = {
         filenames: {
               manifest: 'manifest.desk-admin.js',
               vendor: 'vendor.desk-admin.js',
               app: 'app.desk-admin.js'
          }
}
```

when remove filenames field, development mode work fine. but i don't know why......

**Comment by NicoPennec** [comment]
@highalps you did a mistake in your `nuxt.config.js` file.

Try the following configuration:
```js
module.exports = {
  build: {
    filenames: {
      manifest: 'manifest.app.[hash].js',
      vendor: 'vendor.app.[chunkhash].js',
      app: 'app.app.[chunkhash].js'
    }
  }
}
```

Then on launch of `npm run dev`, Nuxt will remove the **chunkhash** and **hash** tags: https://github.com/nuxt/nuxt.js/blob/6e2b37a7c67f8f7b34580d1bc0ff2eab042d6c2a/lib/builder/builder.js#L212-L214

See `filenames` default values: https://github.com/nuxt/nuxt.js/blob/7d960b03f72e81aa72ca7569ba0154426c198bfb/lib/common/options.js#L198-L204)
