### ISSUE TITLE
v1.2.0 Cannot find module 'postcss-import-resolver'

### ISSUE THREAD

**Issue by sdr0x07b6** [nuxt/nuxt.js#2694]
I updated it soon.
from v1.1.1, `yarn && yarn dev`

```sh
Error: Cannot find module 'postcss-import-resolver'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...myproj/node_modules/nuxt/lib/builder/webpack/postcss.js:5:24)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...myproj/node_modules/nuxt/lib/builder/webpack/vue-loader.js:1:85)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
error Command failed with exit code 1.
```

Running `yarn upgrade` was a similar result.
For now, I solved it by running `yarn add postcss-import-resolver`.

and...
running log,

```sh
  nuxt:render Rendering url /admin/users/assets/styles/main.css.map +846ms
{ statusCode: 404,
  path: '/admin/users/assets/styles/main.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /admin/users/assets/styles/app.css.map +43ms
{ statusCode: 404,
  path: '/admin/users/assets/styles/app.css.map',
  message: 'This page could not be found' }
```

My Stylus files `main.styl` and `app.styl`,
`.map` file originally has not output, but Nuxt is trying to access it automatically.

Are you performing successfully😶?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2342">#c2342</a>)</em></sub></div>

**Comment by daliborgogic** [comment]
Fixed in [v1.2.1](https://github.com/nuxt/nuxt.js/releases/tag/v1.2.1)

**Comment by sdr0x07b6** [comment]
Thank you a few days ago.
By v1.2.1, the above problem was solved.

But now this problem is also occurring.
```
  nuxt:render Rendering url /assets/styles/main.css.map +696ms
{ statusCode: 404,
  path: '/assets/styles/main.css.map',
  message: 'This page could not be found' }
  nuxt:render Rendering url /assets/styles/app.css.map +118ms
{ statusCode: 404,
  path: '/assets/styles/app.css.map',
  message: 'This page could not be found' }
```
First of all, the directory `/admin/users/assets/...` does not originally exist, and I'm not trying to call it from anywhere.
`.map` file originally has not output, but Nuxt is trying to access it automatically.

It may have relapsed at v1.3.0?

(`Can not find module 'postcss-import-resolver'` has not relapsed.)

**Comment by juppdes** [comment]
Happends here too.

{ statusCode: 404,
  path: '/assets/style/app.css.map',
  message: 'This page could not be found' }

Nuxt + Vuetify.

**Comment by virskor** [comment]
i also met this problem

{ statusCode: 404,
path: '/assets/style/app.css.map',
message: 'This page could not be found' }

Nuxt + Vuetify.

**Comment by clarkdo** [comment]
@virskor @juppdes @sdr0x07b6 
Regarding to the error message, it will be fixed in next release, you can try `yarn add nuxt-edge` for a quick test
