### ISSUE TITLE
maxChunkSize used in build will break whole app

### ISSUE THREAD

**Issue by noma4i** [nuxt/nuxt.js#2699]
Iv tried to use 
```
    maxChunkSize: 300000
```

works in Dev while prod build stuck at loading animation with this message in browser console:
```
The resource *******_nuxt/20.d4716bb72467de4f83eb.js was preloaded
using link preload but not used within a few seconds from the window's load event. 
Please make sure it wasn't preloaded for nothing.
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2346">#c2346</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks for the report. The preload log is just a warning. Would you please share a link to public deployed website? Also is this bug introduces after upgrading from 1.1 to 1.2?

**Comment by blooddrunk** [comment]
I'm facing the same issue with **spa** mode after adding `maxChunkSize` with similar console warnings

```
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

I've deployed the built version on gh pages: http://blooddrunk.github.io/nuxt-element/

**Comment by mavrick** [comment]
confirmed ``maxChunkSize`` breaks **spa** mode here.

**Comment by noma4i** [comment]
Ffffffinaly!

**Comment by manniL** [comment]
Try to upgrade to `nuxt-edge`.

**Comment by Atinux** [comment]
`maxChunkSize` has been removed with `nuxt-edge` (aka Nuxt 2) since it was leading to issues.
