### ISSUE TITLE
like the nextjs,the css insert the page head

### ISSUE THREAD

**Issue by ckken** [nuxt/nuxt.js#27]
how can i add the css inside the pages/index.js like next,and then,we can create many more application in one project,but now , nuxt only add css in one style.css,so we can add many app in one project,because the css is too big to load
![image](https://cloud.githubusercontent.com/assets/3890513/20783762/e32806dc-b7d0-11e6-9da3-ca2fec156f2c.png)

**Comment by Atinux** [comment]
We are aware of this issue, please take a look at the issue #12
