### ISSUE TITLE
Nuxt.js program in Linux memory overflow problem

### ISSUE THREAD

**Issue by surmon-china** [nuxt/nuxt.js#270]
I used Nuxt.js to build my blog application, deployed in linux, the memory used is too high.

My server using ubuntu operating system, 1g memory, I use pm2 persistent node application.

I deploy my project every time, you can see the memory is normal, about 80m or so,

After a period of time, the memory will soar to more than 500m, the final memory overflow, resulting in server crashes,

When I found that memory usage up to 90% of the time, I kill off the nuxt process, pm2 immediately restart it, then returned to normal

I am curious, why is my memory usage going up all the time?

[my nuxt.js applaction code](https://github.com/surmon-china/surmon.me)

Here is the screenshot

Abnormal state

![](https://camo.githubusercontent.com/d8def1bb5bbfd68e5b13a4cfead0b8849b58f66f/68747470733a2f2f7374617469632e7375726d6f6e2e6d652f31372d322d31372f33363237323735372d66696c655f313438373239393935313134355f343735382e706e67)

normal status

![](https://camo.githubusercontent.com/67ba2934b1d9b9bd734b30176ae0ebf358fe7cb0/68747470733a2f2f7374617469632e7375726d6f6e2e6d652f31372d322d31372f32373937323033382d66696c655f313438373239393935323438385f31326361652e706e67)

My solution is set the `max_memory_restart: "160M"` attribute to ecosystem.config.js for pm2, the pm2 will listen the app memory, it will auto restart the app when the memory beyonds 160m, it can works, but it's not right solution.

I get the document from Nuxt.js, i try to set the nuxt.config.js `cache: false` or  `cache:{ max: 20, maxAge: 600000 }` , but i think it does not work well.

I would like to find a better source of the problem, as well as the solution, thanks!

**Comment by hendrysadrak** [comment]
I have the same problem, but found a workaaround for this. I use [idle-gc](https://www.npmjs.com/package/idle-gc) and `--expose-gc` flag for node.

**Comment by surmon-china** [comment]
@hendrysadrak You have not tried, whether it is caused by the cache mechanism?

**Comment by hendrysadrak** [comment]
@surmon-china  I think it is because how node garbage collection is done. It doesnt do gc when you have memory available, when you run out of memory, then it starts gc.

**Comment by hendrysadrak** [comment]
@surmon-china Also, i don't use `nuxt start`. I did a script which is similiar to https://nuxtjs.org/api/nuxt-render

**Comment by surmon-china** [comment]
@hendrysadrak I will try do you solution, thanks!

**Comment by alexchopin** [comment]
Hi, thanks for the report. 
@surmon-china Can you confirm and close the issue, if it's due to GC and if it solves the problem when you will give a try?

**Comment by surmon-china** [comment]
@alexchopin OK:)
