### ISSUE TITLE
Insert script tags *before* the usual bundles

### ISSUE THREAD

**Issue by ishitatsuyuki** [nuxt/nuxt.js#2700]
I'm trying to insert polyfills from https://polyfills.io. The issue is that the following method will not work:

```
    script: [
      {src: 'https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,es7,es2017', body: true, defer: true}
    ]
```

This will result in the polyfill be loaded **after** the bundles, which just doesn't make sense. We need an option (or default) to make it inserted before bundles.

(A workaround would be just putting it inside head, but it creates blocking traffic which reduces PageSpeed/lighthouse score.)

**Comment by clarkdo** [comment]
If you want to load the js before bundle, you may rewrite the `app.template.html` and put the polyfill before the `{{ APP }}`

**Comment by ishitatsuyuki** [comment]
Hmm, I don't think that's a valid reason to reject this as a feature.
