### ISSUE TITLE
Some of the strings on ios 10 safari are rendering errors on the server side, which is weird.

### ISSUE THREAD

**Issue by fuxianwei** [nuxt/nuxt.js#2702]
When I wrote the template, some strings (such as string: 2016200202, but string: 201620020 but no problem) could not be rendered on the server side,.
nuxt: 1.2.1,
vue: 2.5.13
The test code：

`<template>`
  `<div class='container'>`
`<div>2016200202</div>`
  `</div>`
`</template>`

The following error message：
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2348">#c2348</a>)</em></sub></div>

**Comment by fuxianwei** [comment]
The method of recurring problems: any number with a length of more than 10.

**Comment by JeOam** [comment]
@fuxianwei upgrade nuxt to 1.4 to solve this problem.
