### ISSUE TITLE
Error in the api documentation

### ISSUE THREAD

**Issue by Felwin** [nuxt/nuxt.js#2704]
On the generate page :
https://nuxtjs.org/api/configuration-generate/

It says that minify default configuration includes `collapseWhitespace: true,` turn out default is at false.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2349">#c2349</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
@Felwin it's fixed now ;-)
