### ISSUE TITLE
Nuxt.js Tryes to fetch source map in asyncData function.

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt/nuxt.js#2705]
Hi,

I use (noty)[https://github.com/needim/noty] in my project and i have loaded it like this.

nuxt.config.js
``` 
  css: [
    '~/assets/scss/main.scss',
    'noty/lib/noty.css'
  ]
```

noty.css contains source mapping url at bottom `/*# sourceMappingURL=noty.css.map*/`

For that reason my async functions are trying to parse `/api/v1/products/noty.css.map` and for that reason im getting 404 errors. 

Im using nuxt axios module. 

EDIT: I also noticed that it sometimes trys to fetch favicon.ico

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2350">#c2350</a>)</em></sub></div>

**Comment by Cogitoergo** [comment]
Solution for now would be to either add the plugins to vendor array in build object, or by disablind the source maps in general, by adding cssSourceMap: false in build object in nuxt.cfg.js.

**Comment by alanaasmaa** [comment]
@Cogitoergo It is  in vendor array

```
vendor: [
      'js-cookie',
      'noty',
      'vue-i18n'
    ]
```

**Comment by alanaasmaa** [comment]
I fixed this by importing styles via main.scss and im importying scss not css file.

**Comment by vestingpanel** [comment]
Hi. I'm using coffee as pre-processors. asyncData is also trying to render app.js.map. 

 I see thins in the console:
```
nuxt:render Data fetching /admin/: 58ms +2s
nuxt:render Rendering url /admin/app.js.map +904ms
```

**Comment by alanaasmaa** [comment]
@vestingpanel

I havent actually found a correct fix yet. I have created some kind of filter. That it filters out map files.

**Comment by zerosym** [comment]
@nicroto I am encountering the same issue, but with plugins/modules.  It seems modules such as nuxt/axios and nuxt/auth are also loaded for each .css.map url rendering.  In the case of nuxt auth, where there is a built in call to fetchUser on plugin init this leads to 3x API calls to fetch the user from backend on the initial server side rendering of the page.

**Comment by Atinux** [comment]
Please re-create an issue by submitting a bug report with https://cmty.app/nuxt/issues/new

**Comment by ram-you** [comment]
Have the same issue with v2.2.0. 
@Cogitoergo solution works but don't think this is the better solution.

_PS: It still an issue with or without the bug report !_

**Comment by opgbaudouin** [comment]
I have the same with using Vuetify and Nuxt 2.2.0 nuxtServerInit is called Many times for a single page load causing all kinds of issues. I added the 
build: {
        cssSourceMap: false
}
but i still got other _nuxt/...js.map sourcemaps as well.
so i now do:
const actions = {
   async nuxtServerInit({commit, dispatch}, {req, route}) {
        if(route.name === null) {
            return;   //you could also check if req.url end with .map 
        }
       ...cookies, stores etc. Only happens once per route.
   } 
}
Not sure if it a BUG per se. Just something that needs to be in documentation

**Comment by kpturner** [comment]
Why is this closed?   I have components that crash because `css.map` requests find their way to the `asyncData` functions even if I try to filter them out in `nuxtServerInit` so this cannot be right can it?  It begs the question, where exactly is the browser supposed to get the maps from because it must be failing to do so.

**Comment by opgbaudouin** [comment]
Also noted these tend to get to any middleware (i.e. your /middleware 'router' plugins) as well. Apparantly this only occurs when debugging your application (i.e. a browser with production should not request them even if they are listed). I believe the dev team are aware of this though...

**Comment by aldarund** [comment]
https://github.com/nuxt/nuxt.js/pull/4323
