### ISSUE TITLE
How to avoid index.vue in each folder and still have router generated ?

### ISSUE THREAD

**Issue by o1lab** [nuxt/nuxt.js#2708]
Nuxt's automatic router generation is a feature that I always wished some one had built in a framework.

However having index.vue in many folders is not helping

How can I go from current state to desired state mentioned below ? Is this possible with a settings. 

## Current 'pages' folder structure

pages/
--| user/
-----| **index.vue**
-----| one.vue
--| **index.vue**

## Desired 'pages' folder structure

pages/
--| user/
-----| **index.user.vue**
-----| one.vue
--| **index.pages.vue**

Thank you,

**Comment by BonnieDoug** [comment]
Why would you want it like that? It's all about semantics and to me the following :

`User / index`

Reads far better than:

`User / Index / user`

**Comment by o1lab** [comment]
Having many index.vue files in project makes jumpng between files in editor a little difficult. Each time developer would need to check what folder a index.vue belongs to.

So instead having filename as index.folder.vue would be handy. 

(@BonnieDoug: pls reread description. My proposition is not to have nested folders like in your comment. But to change index.vue to more editor friendly name )

**Comment by BatuhanK** [comment]
@o1lab lol, so we never use index.js again? it's not about vue, it's about your development habits & environment. maybe use fuzzysearch in your editor, or find a plugin which adds folder name to tabs.
![ss](https://user-images.githubusercontent.com/4688083/35497327-c6356e22-04da-11e8-8f41-8e745e0aae0f.png)

**Comment by BonnieDoug** [comment]
@o1lab , you are aware your index.user.vue is nested within a user folder right? 

There's nothing stopping you simply having a `pages.vue` in your root directory which serves as an index. The URL will still be `/pages` it's simply going to end up with a very messy file structure...

**Comment by o1lab** [comment]
> There's nothing stopping you simply having a pages.vue in your root directory.... to end up with a very messy file structure.

That should help solve it but its not elegant file structure as you mention..

Point to take away from this issue is - this is not technical issue but naming convention of files. I agree there are means to get around as @BatuhanK has pointed out. But having index.folder.vue would be no brainer when jumping to a file. A "folder.." query in file lookup would bring up right file every time (which will be index.folder.vue). 

Im happy to close this issue. However would be happy if somebody sees the point :)
