### ISSUE TITLE
Error 404 after fresh install and runnig dev

### ISSUE THREAD

**Issue by silvio-e** [nuxt/nuxt.js#2709]
`nuxt:render Rendering url /_nuxt/a74d627e1e125e39a94f.hot-update.json +0ms
{ statusCode: 404,
  path: '/_nuxt/a74d627e1e125e39a94f.hot-update.json',
  message: 'This page could not be found' }

  nuxt:render Rendering url / +107ms
  nuxt:render Data fetching /: 1ms +0ms`

Is that something to worry about?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2353">#c2353</a>)</em></sub></div>

**Comment by Duzbee** [comment]
i think i have the same issue

**Comment by pi0** [comment]
No that's just because of old build files which browser first tries to load them :) We should hide such errors from CLI.

**Comment by Duzbee** [comment]
But I get this error on my dev server and it refreshes the page every second

**Comment by vladimirlukyanov** [comment]
I have same issue, any possible solutions ?

**Comment by silvio-e** [comment]
@vladimirlukyanov I'm not sure if it was just removed through emtying the browser cache?

**Comment by wuzhoubo** [comment]
i have the same issue ...

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/nuxt.js/issues/2710
