### ISSUE TITLE
babel defaults (babel-preset-vue-app)

### ISSUE THREAD

**Issue by cj** [nuxt/nuxt.js#271]
Evening,

have you considered using https://github.com/vuejs/babel-preset-vue-app as your babel defaults instead of https://nuxtjs.org/api/configuration-build/#babel ?

**Comment by Atinux** [comment]
Hi @cj 

I will take a look at it thank you.

I try to make nuxt dependencies as low as possible, but this one may simplify babel default presets and plugins.

**Comment by Atinux** [comment]
Hi @cj 

I just added the preset in the `0.9.10` branch and it works like a charm, also, JSX is now supported in nuxt.js by default.

Thank you for this suggestion!

I'll close the issue when the `0.9.10` will be released.

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋

**Comment by dotnetCarpenter** [comment]
Curious to how I can change the targets. I pretty naïve tried to add the following to `nuxt.config.js`

```js
const projectPackage = require('./package.json')
module.exports = {
  build: {
    babel: {
        presets: ['vue-app', {
          'targets': {
            'browsers': projectPackage.browserslist
          }
        }]
      }
  }
}
```

But I still see the following if a file is not found (different error - doesn't matter here):
```
 ../shared/vuex.mockup in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/Users/nappdev/projects/webviewer4/node_modules/b
abel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}
```

The default targets is IE9 but my project targets IE11 and above and I would like to see all the `var` declarations disappear and only have `let` and `const`(which is supported by IE11).

I'm looking for a work-around but the ideal nuxt behavior would be to read the `browserslist` just like PostCSS/Less etc does.

**Comment by qm3ster** [comment]
That's highly peculiar, @dotnetCarpenter.
If you edit this line https://github.com/nuxt/nuxt.js/blob/afc874a11af82b6737e5690a9617bc5464b77d34/lib/builder/builder.js#L198 in your nuxt inside node modules, does that change the value?
Having anything truthy in `build.babel.presets` should definitely clobber the defaults.
Also, you should probably remove the quotes around `targets` and `browsers`.

Can you try this and post what it logs?
```js
const projectPackage = require('./package.json')
module.exports = {
  build: {
    babel: {
        presets: ['vue-app', {
          targets: {
            browsers: (console.log(projectPackage.browserslist), projectPackage.browserslist)
          }
        }]
      }
  }
}
```

**Comment by qm3ster** [comment]
@dotnetCarpenter you also probably want your presets to be a function btw.
```js
module.exports = {
  build: {
    babel: {
      presets: ({ isServer }) => isServer
        ? undefined
        : [
          'vue-app',
          {
            targets: { browsers: projectPackage.browserslist }
          }
        ]
    }
  }
}
```
or
```js
module.exports = {
  build: {
    babel: {
      presets: ({ isServer }) => [
        'vue-app',
        {
          targets: isServer
            ? { node: 'current' }
            : { browsers: projectPackage.browserslist }
        }
      ]
    }
  }
}
```

**Comment by dotnetCarpenter** [comment]
```
We're running in development
[ 'last 2 versions', 'not IE < 11' ]
We're running in development
[ 'last 2 versions', 'not IE < 11' ]
```

*We're running in development* is coming from:
```js
require('dotenv').config()
console.log("We're running in " + process.env.NODE_ENV)
```

Hang on, I just need to fix something, then I'll be here :)

**Comment by dotnetCarpenter** [comment]
@qm3ster I see that you already did some work. I can be on slack in 5/10 minutes, if you have time to help me out with this?

**Comment by qm3ster** [comment]
I dindo nuffin!

**Comment by qm3ster** [comment]
# SOLVED: the presets take:

### `[ ['preset1', {opt:'preset1 option'}], require('preset2')] `

We were not joining the preset's options to the preset with a tuple(array). Shame.
