### ISSUE TITLE
Styles - this relative module was not found.

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#2713]
I put the CSS into config and got this error:

```
This relative module was not found:

* ../assets/styles/style.scss in ./.nuxt/App.js
  nuxt: Call close hooks (2) +0ms
  nuxt: server closed +1ms
```

**Tip**: my app/nuxt app isn't in the root dir of project.

**Comment by Michkkael** [comment]
Do you have node-sass + sass-loader ?
`npm install --save-dev node-sass sass-loader`

**Comment by husayt** [comment]
Closing due to lack of details. Reopen if still happens or with more info pls.

**Comment by smcstewart** [comment]
For anyone else coming here, as per what @Michkkael wrote, after installing `node-sass` and `sass-loader` this fixed this issue for me.
