### ISSUE TITLE
How to exclude some router when using nuxt generate

### ISSUE THREAD

**Issue by SzHeJason** [nuxt/nuxt.js#2719]
current router
```
 page
 --- about.vue
 --- index.vue
```
I just want to generate an `about` HTML file when using `nuxt generate`, how can I do that?

**Comment by dan-peterson** [comment]
Do you want only a subset of your pages generated when you run `nuxt generate`?

I was wanting to do the same thing today. My solution was to use a custom module to leverage the internal plugin system (Note that in the latest releases these are now called hooks and have been re-worked a bit. They don't appear to be documented yet.)

I'm not sure if this is the best approach but it certainly seems to do the trick for now.

`modules/custom-generate.js`

```javascript
module.exports = function () {
  this.nuxt.hook('generate:extendRoutes', async routes => {
    const whiteList = ['/about', '/login'];
    const routesToGenerate = routes.filter(page => whiteList.includes(page.route));
    routes.splice(0, routes.length, ...routesToGenerate);
  });
};
```
`nuxt.config.js`

```javascript
modules: [
  '~modules/custom-generate.js'
],
```

**Comment by qm3ster** [comment]
You can also just [use the `generate.routes` property](https://nuxtjs.org/api/configuration-generate#routes) in `nuxt.config.js` to manually pick what routes to generate. It even takes an async function.

**Comment by dan-peterson** [comment]
@qm3ster Good point. I think the only catch is that `generate.routes` gives you control over dynamic routes only. If you want to blacklist some static routes from generate is there a better way?

**Comment by qm3ster** [comment]
No, setting anything to `generate.routes` disables route autogeneration.
The only reason it's documentation heavily mentions dynamic routes is that it was created before `extendRoutes` was, and was the only way to generate any dynamic routes at the time.

**Comment by SzHeJason** [comment]
I tried but it did not work

```JS
 generate: {
    routes: ["about"]
  },
```

How to setting `generate.routes` make `nuxt`  disables route autogeneration ? Can you show the code?

Nuxt Version : 1.3.0

**Comment by qm3ster** [comment]
@dan-peterson @SzHeJason I was wrong, this has been changed a gorillion months ago.
The `generate.routes` are now merged with autodetected routes.
`generate:extendRoutes` seems like the only way now.

**Comment by manniL** [comment]
For all googlers, this is possible via regex in `generate.exclude`. if the route URL matches the regex, the page will be excluded from generating but can still be served as "SPA route"
