### ISSUE TITLE
How to add webpack-graphql-loader for fragments support 

### ISSUE THREAD

**Issue by Lahori-Jawan** [nuxt/nuxt.js#2722]
I am using nuxt-apollo and now I need to use `fragments` in `.gql` queries. Someone pointed out [here](https://github.com/Akryum/vue-apollo/issues/12) to use `graphql-loader` to get access to fraqments. So based on this [issue](https://github.com/nuxt/nuxt.js/issues/155) that's what I did
```
build: {
	vendor: ["axios"],
	postcss: {
		plugins: {
			"postcss-custom-properties": false
		}
	},
	extend(config, { isDev, isClient }) {
	    config.module.rules.push({
			test: /\.(graphql|gql)$/,
			exclude: /node_modules/,
			loader: "webpack-graphql-loader",
		});
	}
}
```
but its giving error
```
 error  in ./apollo/queries/newComment.gql

Module build failed: Syntax Error: Unexpected Name "var"
```

I really need to use it since there are a lot of repetitive queries in my project.

**Comment by Lahori-Jawan** [comment]
I just noticed that nuxt-apollo supports fragments out the box.

**Comment by evseevnn** [comment]
@Lahori-Jawan So, your find reason of this problem? how your solve it? any link to nuxt-apollo supports ticket pls

**Comment by Lahori-Jawan** [comment]
@evseevnn the [url](https://github.com/nuxt-community/apollo-module) for nuxt apollo module and [this](https://github.com/Lahori-Jawan/graphX) is my integrated bundle.
