### ISSUE TITLE
nuxt generate error, generated dist folder is not generated index.html

### ISSUE THREAD

**Issue by pandashuai** [nuxt/nuxt.js#2724]
# npm run generate err:
```
{ Error: ENOENT: no such file or directory, lstat 'e:\_ddp\_tmp\test\ddp_blog\dist\index.html'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'e:\\_ddp\\_tmp\\test\\ddp_blog\\dist\\index.html' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ddp_blog@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ddp_blog@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-01-31T07_36_14_739Z-debug.log
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2366">#c2366</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
please, give us more details:
- os
- nodejs version
- npm version
- nuxt version (local or global)

have you run `npm run generate`or `nuxt generate` ?

**Comment by pandashuai** [comment]
system： `win10`
nodejs version : `v8.9.1`
npm version: `5.5.1`
nuxt version:  `^1.0.0-rc11`   local
run:` npm run generate`
```
  "scripts": {
        "dev": "nuxt",
        "build": "nuxt build",
        "start": "nuxt start",
        "generate": "nuxt generate"
    }
```

**Comment by NicoPennec** [comment]
It seems a rights issue with your current user.

Can you open a new terminal as administrator and retry to `npm run generate` ?
https://technet.microsoft.com/fr-fr/library/cc947813%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396

Then check if the `dist/` folder is created in your project.

**Comment by pandashuai** [comment]
Not work

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
