### ISSUE TITLE
Set plugin only on specific layouts

### ISSUE THREAD

**Issue by microcipcip** [nuxt/nuxt.js#2727]
Is it possible to set a plugin just for specific Layouts? 

I have an $axios plugin that I want to use only for `adminLayouts`, and don't want to load all the extra code in the `clientLayouts` (it would also break because I use Vuetify in admin plugins but is not included in the client)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2368">#c2368</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Plugins was designed to be run before instantiating the root vue.js application, so it cannot be used only for specific layouts.

You can manually import the `plugin` in the layout and initialize it in `beforeCreate` or `created` which are called both from client-side and server-side.

**Comment by microcipcip** [comment]
What is the syntax? Just this?
```
import Vue from 'vue'
import MyPlugin from '~/plugins/my-plugin'

Vue.use(MyPlugin)
```

**Comment by clarkdo** [comment]
```js
// plugins/my-plugin
import Vue from 'vue'
export default () => {
  // ...
  Vue.use(....)
}

// adminLayouts
import myPlugin from '~/plugins/my-plugin'
export default {
  created() {
    myPlugin()
  }
}
```

**Comment by microcipcip** [comment]
@clarkdo how do I use this with inject? For example if I have this?

```
const MyCookies = (req, res) => 'hello'
export default ({ req, res }, inject) => {
  inject('cookies', MyCookies(req, res))
}
```

**Comment by clarkdo** [comment]
```js
export default ({ app }, inject) => {
  inject('cookies', cookies)
}
```

Then you can use:
app.$cookies
this.$cookies in vue components
this.$cookies in store actions/mutations

**Comment by microcipcip** [comment]
Ah ok so I don't have to mount it in layouts? I just need `import ~/plugins/cookie` without setting `Vue.use(myPlugin)` ?

**Comment by clarkdo** [comment]
Yes, `inject` will include `Vue.use`.

**Comment by microcipcip** [comment]
Ah that is what I was missing, I'll give it a try, thanks a lot :)

**Comment by microcipcip** [comment]
It seems that it doesn't work because the js on middleware folder runs before I hit the layout template

**Comment by clarkdo** [comment]
Sorry, I think I misunderstood you questions.

1. If you want to set a plugin just for specific Layout, read my [first comment](https://github.com/nuxt/nuxt.js/issues/2727#issuecomment-362208485), in this case. The `plugin` is only a ordinary js file, not `nuxt plugin`, so you can not use  `inject`.
2. If you want to use `inject` in plugin, [this comment](https://github.com/nuxt/nuxt.js/issues/2727#issuecomment-362962499) if fine.

**Comment by microcipcip** [comment]
With option 1. would I be able to access middleware though? I use the plugins there

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
