### ISSUE TITLE
@ sign inside a text only line breaks client on side

### ISSUE THREAD

**Issue by larsenwork** [nuxt/nuxt.js#2730]
I'm using nuxt 1.3.0 and generating and deploying to github pages. 

Having something like this inside a component template loads the ssr page but then wipes all content as client side kicks in.
```html
<h3>
    andreas@larsenwork.com
</h3>
```
but this works fine:
```html
<h3>andreas@larsenwork.com</h3>
```

You can see me code here: https://github.com/larsenwork/larsenwork.github.io/blob/dev/components/navigation.vue#L56 and I'd gladly help debugging more if I get some pointers on how to do it 😄 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2371">#c2371</a>)</em></sub></div>

**Comment by clarkdo** [comment]
I have cloned your repo and executed below commands which didn't reproduce the issue:

```bash
$ yarn install
$ yarn generate
$ http-server dist/
```
![image](https://user-images.githubusercontent.com/4312154/35672290-035d3e56-0779-11e8-8126-8702dc2df0bf.png)

Can you confirm if this issue still existing, if yes, could you provide more info?

**Comment by larsenwork** [comment]
@clarkdo sorry, I wasn't clear enough — it doesn't happen when serving `dist/` locally on my machine either but only when you push it to github pages. 
I'm using this https://github.com/larsenwork/larsenwork.github.io/blob/dev/package.json#L13 to deploy to github pages

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
