### ISSUE TITLE
asyncdata undefined on mobile

### ISSUE THREAD

**Issue by atmar** [nuxt/nuxt.js#2731]
Hello,

I have a strange issue after publishing my site.  Works fine on destktop, but doesn't work on mobile. It gives the error "Cannot read property 'totalCount of undefined'.
Which references to this:

```
  async asyncData({ app }) {
    let { data } = await app.$axios.get(`/bets/all`)
    return {
      bets: {
        recent: data.recent,
        bestwins: data.bestwins,
        leaderboard: data.leaderboard,
        totalCount: data.totalCount,
        totalWon: data.totalWon
      }
    }
  },
```

I'm absolutely clueless on why this happens. I've used nuxt generate to host the site. First time doing it that way as I usually use a server.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2372">#c2372</a>)</em></sub></div>

**Comment by microcipcip** [comment]
What happens if you log the data obj?

**Comment by atmar** [comment]
Well I'm not sure how to inspect that in a mobile browser, but I'm guessing undefined as the error is ""Cannot read property 'totalCount of undefined'"

**Comment by EllenFawkes** [comment]
I got this error on desktop, Chrome 61.0.3163.100. It's not a mobile problem.

**Comment by Zip753** [comment]
My guess is that the problem is in the request somewhere. Are you sure your endpoint is accessible under `/bets/all`? Using relative URL in requests can have weird behaviour sometimes, I'd recommend appending the base URL to `/bets/all`.

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
