### ISSUE TITLE
Breakpoints doesn't work in vscode debugger

### ISSUE THREAD

**Issue by ralphchristianeclipse** [nuxt/nuxt.js#2734]
I'm using this command to debug nuxt server store

```json
"debug": "node --inspect-brk=9229 node_modules/nuxt/bin/nuxt",
```

and in vs code
i'll attach it when it runs
```json
{
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229,
      "protocol": "inspector",
      "restart": true,
      "sourceMaps": true
    }
```

seems breakpoints doesn't work and grayed out turned sourceMaps on too

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2374">#c2374</a>)</em></sub></div>

**Comment by tim-yao** [comment]
I can not make breakpoints working in Vscode and WebStorm. I followed https://github.com/nuxt/nuxt.js/issues/2341 It stops in first line but not hit breakpoints. So as above indicated, it's a bug I think. Hope we can have a solution soon.

**Comment by sobolevn** [comment]
@ralphchristianeclipse @tim-yao any news on this one?

**Comment by tim-yao** [comment]
Hi @sobolevn I have made it working, looks not a issue anymore. Here is my VSCODE debug config for my Nuxt project:
```
{
            "type": "node",
            "request": "launch",
            "name": "My Nuxt project",
            "protocol": "inspector",
            "program": "${workspaceRoot}/node_modules/.bin/nuxt",
            "stopOnEntry": true,
            "args": ["dev"],
            "cwd": "${workspaceRoot}",
            "sourceMaps": true,
            "env": {
                "NODE_ENV": "development",
                "DEBUG": "nuxt:*,app"
            }
        }
```
Both `debugger` and IDE breakpoint works now.

**Comment by sobolevn** [comment]
@tim-yao debug app actually starts, but I am facing this problem:
<img width="666" alt="2018-05-19 11 36 59" src="https://user-images.githubusercontent.com/4660275/40266722-ffc3215a-5b58-11e8-8cae-ca5c999a4909.png">

Could you please provide a reproduction repo?

That's the setup I am using: https://github.com/wemake-services/wemake-vue-template
My `launch.json` file:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "My Nuxt project",
      "protocol": "inspector",
      "program": "${workspaceRoot}/node_modules/.bin/nuxt",
      "stopOnEntry": true,
      "args": ["dev"],
      "cwd": "${workspaceRoot}",
      "sourceMaps": true,
      "env": {
          "NODE_ENV": "development",
          "DEBUG": "nuxt:*,app,client"
      }
        }
  ],
  "compounds": []
}

```

**Comment by tim-yao** [comment]
Hi @sobolevn yes, just noticed I still have the same issue as you. However, I can use `debugger` to stop the code. It's not as good as IDE "red dot" breakpoint but at least I can do the debug now.
Also when it stops, the VSCODE opens `server-bundle.js` which is the Webpack generated file and stops in same code line. I can put IDE breakpoints in that file.

Mostly it is a source maps issue still need some one to find a solution. Not sure how to make it.

**Comment by sobolevn** [comment]
I verify that `debugger` statement works.

**Comment by clarkdo** [comment]
This issue should be relate to https://github.com/vuejs/vue-loader/issues/1163, as the comments said, you may try to upgrade `babel` to `6.26.3`.

**Comment by sobolevn** [comment]
I am already using the latest `babel-core`. It sill does not solve it.

```
» cat node_modules/babel-core/package.json        
{
  "name": "babel-core",
  "version": "6.26.3",
  ...
}
```

I will try to update to `nuxt-edge`.

**Comment by jdamboeck** [comment]
Any luck?

**Comment by clarkdo** [comment]
@sobolevn @jdamboeck It seems that vue-loader issue is still not solved, let's keep tracking it.

**Comment by KennanChan** [comment]
New to nuxt and I am facing the same debugging issue.

After setting the webpack devtool for the server to "inline-source-map" as I set in Vue projects, breakpoints now get hit.

In my nuxt.config.js, I have:
`
if (isClient)
  config.devtool = 'eval-source-map'
else
  config.devtool = "inline-source-map"
`
in the build configuration. Just refer to the [documentation](https://nuxtjs.org/api/configuration-build#extend) and make the modification.

I am using the vs code debug configuration provided by @tim-yao .

Now server side code can be debugged in vs code and client side code can be debugged in Chrome.

 It will be perfect if all the code can be debugged right in vs code. Any solution?
