### ISSUE TITLE
Nuxt.js + Uikit3 --> Deploying to Heroku

### ISSUE THREAD

**Issue by dev-ahmad** [nuxt/nuxt.js#2740]
@Atinux Hey Sebastien , i am deploying Nuxt.js App to Heroku and i get this Error :

ERROR in ./.nuxt/index.js
remote: Module not found: Error: Can't resolve 'nuxt_plugin_uikit_47fa8f2a' in '/tmp/build_31cd53bb03d3c4965aefafd39b60d23b/.nuxt'
remote: @ ./.nuxt/index.js 225:0-68
remote: @ ./.nuxt/client.js

.....
idk what's that ! everything in local was perfect !! , and i used Uikit from nuxt.config.js ,, is there anything to do with this error !

Regards ..

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2379">#c2379</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @dev-ahmad 

Did you added the `heroku-postbuild` script in your `package.json`?

Please look at https://nuxtjs.org/faq/heroku-deployment

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
