### ISSUE TITLE
NODE_ENV either set to development or production, no way to add staging environment

### ISSUE THREAD

**Issue by foxted** [nuxt/nuxt.js#2741]
Hello,

I am trying to have three separate environments using nuxt, but `NODE_ENV` is always `development` unless I use `nuxt start` which switches it to `production`. 

How would I go about creating a `staging` environment? I tried `NODE_ENV=staging nuxt` in my package.json but it has been unsuccessful so far.

Thanks.

**Comment by pi0** [comment]
What is setting in nuxt.config.js:

```js
env:{
  NODE_ENV: 'staging'
}
```

**Comment by foxted** [comment]
I found an alternative. I am using dotenv to load environment variables, I just created a variable in nuxt.config.js to make use of the NODE_ENV: 

```
env: {
    environment: process.env.NODE_ENV
}
```

Should support that out of the box though.
