### ISSUE TITLE
Timestamp in nuxt logs?

### ISSUE THREAD

**Issue by EllenFawkes** [nuxt/nuxt.js#2745]
Hi,

I can't find any way, how to add timestamps to logs from nuxt. For better orientation (not only) in production logs it's will be very usefull. Do you support this feature? 

Thanks

**Comment by clarkdo** [comment]
Nuxt is using `debug`, according to its [doc](https://github.com/visionmedia/debug#environment-variables), you can set two env in `nuxt dev` to enable timestamp:

```bash
DEBUG_COLORS=false DEBUG_HIDE_DATE=false nuxt
```
![image](https://user-images.githubusercontent.com/4312154/35769277-790f5186-0943-11e8-90ab-354b9d230d3a.png)
