### ISSUE TITLE
HMR for nuxt modules

### ISSUE THREAD

**Issue by Zip753** [nuxt/nuxt.js#2747]
Is there a way to use HMR with nuxt modules? In my specific case I'm using `nuxt-i18n` module, which requires a set of translations as a module param specified in `nuxt.config.js` directly. Now, I've tried adding dependent files to `build.watch` config, but the app doesn't seem to reload, and from the source code it seems that the modules aren't affected by HMR in any way.

Therefore, from my perspective, there should either be a way to rebuild modules in HMR somehow, or there should be a better way to provide module options, so that they are automatically watched by HMR.

I haven't dug into how Webpack HMR works, but I suppose there is a way to write custom plugin for that to work, still it would be a great functionality if it was done out of the box.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2384">#c2384</a>)</em></sub></div>

**Comment by mathieutu** [comment]
Exactly the same here, and I've also tried to add files in build.watch, but nothing happen when changing them...

**Comment by mathieutu** [comment]
I think I've found one part of the problem: https://github.com/nuxt/nuxt.js/issues/2983

But it's true than the modules are not reloaded during the build, so I totally agree with you.

**Comment by Zip753** [comment]
An update from my side: I'm using Nuxt in setup with Express (from [`nuxt-community/express-template`](https://github.com/nuxt-community/express-template)), so Nuxt itself actually doesn't handle HMR as it's handled by [Backpack](https://github.com/jaredpalmer/backpack). Therefore, when I added the files I wanted to track to Backpack config (via [`webpack-watch-files-plugin`](https://github.com/Fridus/webpack-watch-files-plugin)) the HMR started working as expected, refreshing the build every time I changed my translations files. Now, I haven't tested it with `build.watch` option in `nuxt.config.js`, so in my case it might actually work just fine.

As a conclusion, I can suggest that [the documentation of `build.watch`](https://nuxtjs.org/api/configuration-build#watch) is updated to warn that it only works when running Nuxt app via `nuxt dev`.

**Comment by mathieutu** [comment]
@Zip753 actually as I said, only the webpack part of the build is reloaded when adding a file in watch, so the modules are not reloaded at all, event with nuxt dev.

**Comment by manniL** [comment]
@mathieutu  @Zip753 Does the latest `nuxt-edge` version fixes this issue? :thinking:

**Comment by mathieutu** [comment]
Nope I don't think so, sorry.

**Comment by clarkdo** [comment]
The latest edge has introduced a new config `watch`, you can try to add modules into it.

Docs: https://github.com/nuxt/docs/blob/2.0/en/api/configuration-watch.md
