### ISSUE TITLE
extendedRoutes not working with nuxt generate

### ISSUE THREAD

**Issue by cj** [nuxt/nuxt.js#275]
[https://nuxtjs.org/api/configuration-router/#extendroutes](extendedRoutes) not working with `nuxt generate`.  I'm working on a fix, will attach the pull request here once done.

**Comment by cj** [comment]
current output:

```
[ '/about',
  '/',
  '/moo',
  { path: '/index.html',
    component: '/Users/cj/Sync/apps/acd/phonegap/MyAppName/src/pages/index.vue' } ]
```

should be:

```
[ '/about',
  '/',
  '/moo',
  '/index.html']
```

**Comment by awronski** [comment]
There is one more problem with extendedRoutes. The paths are incorrect escaped on windows.
Only for extended - **Single backslash**.

Normal:
```
const _24b881f2 = process.BROWSER_BUILD ? () => System.import('c:\\dev\\git\\custom-routes\\pages\\users\\_id.vue') : require('c:\\dev\\git\\custom-routes\\pages\\users\\_id.vue')
```

Extended:
```
const _0bd891c8 = process.BROWSER_BUILD ? () => System.import('c:\dev\git\custom-routes\pages\index.vue') : require('c:\dev\git\custom-routes\pages\index.vue')
```

This gives an error:
```
ERROR in ./.nuxt/router.js
Module not found: Error: Can't resolve 'c:devgitcustom-routespagesindex.vue' in 'c:\dev\git\custom-routes\.nuxt'
```

Maybe you can fix it or give me a hint where it is generated so I will try to fix the problem.


Thanks!

**Comment by alexchopin** [comment]
@awronski can you show us your extendedRoutes?

**Comment by awronski** [comment]
@alexchopin 

```
 router: {
    extendRoutes (routes) {
      routes.push({
        name: 'custom',
        path: '/custom',
        component: resolve(__dirname, 'pages/index.vue')
      })
    }
  } 
```

**Comment by alexchopin** [comment]
Will be fixed in the next release 👍

**Comment by awronski** [comment]
Thanks!

On Thu, Feb 23, 2017 at 10:38 AM, Alexandre Chopin <notifications@github.com

**Comment by Atinux** [comment]
The `0.10` release fixed this issue 👍
