### ISSUE TITLE
[Feature Request] Static image path don't need to append the base url

### ISSUE THREAD

**Issue by jasonc08** [nuxt/nuxt.js#2753]
[https://nuxtjs.org/guide/assets#static](https://nuxtjs.org/guide/assets#static)

without baseurl ( http://127.0.0.1/ )
`<img src="/my-image.png"/>`

with baseurl ( http://127.0.0.1/test )
`<img src="/test/my-image.png"/>`

If i want to change my base url,  i need to change all of the files from "test" to the base url. I think it is not the best approach.

**Comment by clarkdo** [comment]
Is the `/test` configured in `router.base`?

**Comment by jasonc08** [comment]
yes, and i am using @nuxt/router. 
```
 router: {
     base: '/test/',
     middleware: 'example'
  },
```

**Comment by Jackbennett** [comment]
I was just puzzled by this too, leave the path to be relative and it seems to just work it out;

`nuxt.config.js`
```javascript
router: {
        base:  '/example/',
    },
```
`someTemplate.vue`
```html
<ul>
  <li><a href="about/about-us.html">About Us</a></li>
</ul>
```

output `http://localhost:3000/example/about/about-us.html` even when on the routes `http://localhost:3000/example/info/subpage/submarine`  and `http://localhost:3000/example/info/subpage/` 


Using the absolute `<a href="/about/about-us.html">` 404's that page as per nuxt config it's generated under /example/... out of the static folder.

Still not  sure if I'd call this desired behaviour, it's not how I was expecting it to work.
