### ISSUE TITLE
How to return 404 status code on error (for SEO)?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2756]
Hi guys. There's an issue that I can't solve.

The thing is, when 404 occurs, website should return actual 404 error status code. This needs to be in place, so Search Engines crawl website the right way

> Last but not least, 404s can be bad news when they act like a 200. A soft 404 error page is not a good thing, because search engines will continue to index these. Ensure your server is configured to return the proper status code for each type of page.

If I use `error.vue` template, then there's no 404 status code in DevTools, since app just showing this template. There's an 404 error for API, but this is not the case. I need 404 code for frontend app, not API.

**Comment by pi0** [comment]
Hey. It should return 404 indeed. Do you have any public URL of your project?

**Comment by iamdubx** [comment]
Ah, never mind, I think it's not the issue. SInce I forgot that I navigate on the client! Crawlers will fetch from server, and there 404 works fine. 

Thanks @pi0 you right
