### ISSUE TITLE
layouts/error.vue does not work when i am using @nuxt/router

### ISSUE THREAD

**Issue by jasonc08** [nuxt/nuxt.js#2759]
[https://nuxtjs.org/guide/views/#error-page](https://nuxtjs.org/guide/views/#error-page)

layouts/error.vue does not work when i am using @nuxt/router
Where can i get the status code or modify the response message, if i cannot use the layouts/error.vue ?

**Comment by clarkdo** [comment]
Can you provide a repo? 

I create a simple one, but it works for me.

```js
// nuxt.config.js
module.exports = {
  modules: [
    '@nuxtjs/router'
  ]
}
```

```js
// router.js
import Vue from 'vue'
import Router from 'vue-router'

import index from '~/pages/index'
import about from '~/pages/about'

Vue.use(Router)

export function createRouter() {
  return new Router({
    mode: 'history',
    base: '/',
    routes: [
      {
        path: '/',
        component: index,
        name: 'index'
      },
      {
        path: '/about',
        component: about,
        name: 'about'
      }
    ],
    fallback: false
  })
}
```

```vue
// layouts/error.vie
<template>
  <div>I'm error layout</div>
</template>
```

When access a 404 url such like http://localhost:3000/invalid-page, page is like:

![image](https://user-images.githubusercontent.com/4312154/35792049-108a0cf2-0a86-11e8-9fd0-c139bf999733.png)

**Comment by jasonc08** [comment]
I know what the problem is, because i use `<router-view></router-view>` rather than `<nuxt></nuxt>`. Thanks a lot.

**Comment by jasonc08** [comment]
but after i change it to `<nuxt></nuxt>`, All of the animation from page to page have problems.
