### ISSUE TITLE
What does 'offline' and 'cache' setting mean in nuxt.config?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2760]
I found this example - https://github.com/NicoPennec/nuxt-weather/blob/master/nuxt.config.js

```js
offline: true,
cache: true
```
I can't find any info regarding this settings. Are they still working? Are they documented?

**Comment by NicoPennec** [comment]
`offline` is an old removed option... 
https://github.com/nuxt/nuxt.js/commit/592f8cc7337cb9e6d95f945d2944ba2936b36dbc

and probably the same thing about `cache`

I will clean my repository ;-)

**Comment by pi0** [comment]
As an alternative you can now use official PWA module supporting offline usage.

https://github.com/nuxt-community/pwa-module

**Comment by iamdubx** [comment]
Got is, thank you guys.
