### ISSUE TITLE
How to set 404 statusCode for current page?

### ISSUE THREAD

**Issue by KonstantinVlasov** [nuxt/nuxt.js#2761]
Hi guys!

If some data not found, I want to stay on the current page (layout) but with 404 statusCode, without redirection. Is it possible?

**Comment by clarkdo** [comment]
Hi @KonstantinVlasov 

What date do you mean? Can you describe your issue more specifically?

**Comment by KonstantinVlasov** [comment]
Here our app: https://icons8.com/icon/set/abcdefg/all
In this page, I try to find 'abcdefg' icons. If no icons are found, I want to set 404 status for SEO, but I didn't want to redirect to the error page, so the user can continue using the app.

**Comment by clarkdo** [comment]
I suggest you `asyncData` or `fetch` to load the data, if `abcdefg` doesn't exist, you can set the `statusCode`:

```js
// pages/icon/set/_search/all.vue
async asyncData({ res}) {
    const { data } = await axios.get(...')
    if (!data) {
        res.statusCode = 404
    }
}
```

**Comment by KonstantinVlasov** [comment]
This is exactly what I needed, thanks!
