### ISSUE TITLE
Need docs improvement for asyncData method.

### ISSUE THREAD

**Issue by utkukaratas** [nuxt/nuxt.js#2763]
asyncData docs (https://nuxtjs.org/guide/async-data) say:

"... It can be called server-side or before navigating to the corresponding route ..." 

It is not clear when the method is called at server-side or before navigation. I guess this is a "mode" related thing?

ps. kudos to all the team for this great work!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2398">#c2398</a>)</em></sub></div>

**Comment by husayt** [comment]
More details on asyncdata vs data behaviour would be really useful. Thanks

**Comment by manniL** [comment]
Closed in favor of https://github.com/nuxt/docs/issues/846
