### ISSUE TITLE
svg-sprite-loader and nuxt?

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt/nuxt.js#2764]
Anyone got https://github.com/kisenka/svg-sprite-loader working with nuxt? If so would u mind showing ur solution/s ? I can't seem to get it working, even looking at previous threads and hacks from last year.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2399">#c2399</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Have you tried anything similar to https://github.com/nuxt/nuxt.js/issues/2302#issuecomment-348689076 ?

**Comment by t4r0** [comment]
@jesperlandberg we've tried @clarkdo 's solution on #2302 (comment) and it actually works, perhaps your issue is not related to nuxt itself but the task you're trying to accomplish?
