### ISSUE TITLE
Can't get Nuxt to work in a Yarn workspace

### ISSUE THREAD

**Issue by Haroenv** [nuxt/nuxt.js#2765]
I have a workspace, with other examples using similar dependencies, but it seems like Nuxt is expecting `postcss-import` in a very specific path (`/postcss-import) instead of `/node_module/postcss-import`

```
 nuxt:build App root: /Users/haroen/git/vue-examples/examples/nuxt +0ms
  nuxt:build Generating /Users/haroen/git/vue-examples/examples/nuxt/.nuxt files... +2ms
  nuxt:build Generating files... +9ms
  nuxt:build Generating routes... +1ms
  nuxt:build Building files... +39ms

 ERROR

  Error: Cannot resolve "postcss-import" from "/Users/haroen/git/vue-examples/examples/nuxt/postcss-import"

  - nuxt.js:220 Nuxt.resolvePath
    [vue-examples]/[nuxt]/lib/core/nuxt.js:220:11

  - postcss.js:81 config.plugins.Object.keys.map.p
    [vue-examples]/[nuxt]/lib/builder/webpack/postcss.js:81:42

  - Array.map

  - postcss.js:80 Builder.postcssConfig
    [vue-examples]/[nuxt]/lib/builder/webpack/postcss.js:80:8

  - vue-loader.js:7 Builder.vueLoader
    [vue-examples]/[nuxt]/lib/builder/webpack/vue-loader.js:7:28

  - base.config.js:63 Builder.webpackBaseConfig
    [vue-examples]/[nuxt]/lib/builder/webpack/base.config.js:63:30

  - client.config.js:31 Builder.webpackClientConfig
    [vue-examples]/[nuxt]/lib/builder/webpack/client.config.js:31:21

  - builder.js:485 Builder.webpackBuild
    [vue-examples]/[nuxt]/lib/builder/builder.js:485:46

  - builder.js:168 Builder.build
    [vue-examples]/[nuxt]/lib/builder/builder.js:168:16
```

See related: https://github.com/algolia/vue-instantsearch-examples/pull/12/files

**Comment by clarkdo** [comment]
The resolving will firstly load from `/node_modules` and then `/`, can you please confirm that if `postcss-import` existed in your `node_modules` or did you config `modulesDir`.

For our better and further investigating, I will be very appreciate if you can provide a repo can reproduce the issue.

**Comment by Haroenv** [comment]
sure, I pushed the change to put the nuxt example in the workspace, so `yarn` in the main package and `cd examples/nuxt; yarn dev` will give that error: 

https://github.com/algolia/vue-instantsearch-examples/tree/chore/put-nuxt-in-workspace

Thanks for taking a look!

**Comment by Atinux** [comment]
Hey @Haroenv 

I just tried this:

```
git clone git@github.com:algolia/vue-instantsearch-examples.git
cd vue-instantsearch-examples/
yarn
cd examples/nuxt/
yarn
yarn dev
```

And it works perfectly. Can you remove your `node_modules/` inside `vue-instantsearch-example/` and run `yarn` again?

**Comment by Haroenv** [comment]
@Atinux, the version in the current master has the nuxt example specifically left out of the workspace. If you go to the branch `chore/put-nuxt-in-workspace` you'll see the issue 👍

**Comment by Atinux** [comment]
My bad, did not see the branch in your url, will look at it.

**Comment by Atinux** [comment]
As @clarkdo said you need to use the `modulesDir` key to tell Nuxt where to look for npm modules, see my PR https://github.com/algolia/vue-instantsearch-examples/pull/15

**Comment by Haroenv** [comment]
Thanks a lot, I didn't understand the first comment, but your PR made it clear. Sorry for the noise 👍

**Comment by Fnxxxxo** [comment]
It works for orgin nuxt server, but not for koa-template.
It complains:
`These dependencies were not found:

* koa in ./server/index.js
* nuxt in ./server/index.js
* regenerator-runtime in ../node_modules/babel-runtime/regenerator/index.js

To install them, you can run: npm install --save koa nuxt regenerator-runtime
module.js:538
    throw err;
    ^

Error: Cannot find module 'E:\projects\Git\LC\xcrm-app\xcrm-mall\build\main.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
`
Adding modulesDir: path.resolve(__dirname, '../node_modules') is not working.

**Comment by Fnxxxxo** [comment]
Great. Now it works by setting nohosit for backpack-core and source-map-support. @Haroenv
