### ISSUE TITLE
Invalid component styles order

### ISSUE THREAD

**Issue by LordGuard** [nuxt/nuxt.js#2770]
There is a problem with the order of adding component styles. Css of the child component is added after the css of the parent and so the css of the child component overrides the css of the parent, and not the other way around (as I would like). If you add 'extract css', then in the production version the problem is solved, but not in development mode. What to do about it? I would like all css to be added immediately for the entire project in the order in which I originally imported it, but now it only works in the production version.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2405">#c2405</a>)</em></sub></div>

**Comment by microcipcip** [comment]
Ummm....I don't see why your parent component should override the child, usually is the other way around. The way I fix this kind of issues is by using BEM styling conventions so that I have very low specificity.

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
