### ISSUE TITLE
Error page use default layout instead of defined layout

### ISSUE THREAD

**Issue by purrplingcat** [nuxt/nuxt.js#2771]
Hi,

I defined my custom `layouts/error.vue` and `layouts/empty.vue`. In error layout I set my layout `empty` asthe layout property:

**layouts/error.vue**
```vue
<template>
  <v-app>
    <!-- error layout -->
  </v-app>
</template>

<script>
export default {
  props: ['error'],
  layout: 'empty'
}
</script>
```

**layouts/empty.vue**
```vue
<template>
  <v-app>
    <nuxt />
  </v-app>
</template>
```

So sometimes is works, but one of some requests my error page has a `default` layout instead of `empty`. This defects occurs random.

---

Nuxt version: **1.3.0**
Vuetify: **0.17.0**

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2404">#c2404</a>)</em></sub></div>

**Comment by HC-Team** [comment]
Have the exact same issue!

**Comment by uptownhr** [comment]
I am also experiencing this issue. I'm on version 1.0.0

**Comment by pi0** [comment]
Will be probably fixed with nuxt 2 as layouts are by default loaded with the main chunk

**Comment by uptownhr** [comment]
awesome thanks

**Comment by Kimel1** [comment]
Same issue

**Comment by igtm** [comment]
same issue

**Comment by Chathula** [comment]
same here!

**Comment by laSinteZ** [comment]
Same here, using Nuxt-Edge.

**Comment by manniL** [comment]
This has been resolved in the latest `nuxt-edge release`.

Example:

`layouts/error.vue`:
```vue
<template><h1>You wil never see this</h1></template>

<script>
export default {
  props: ['error'],
  layout: 'weird'
}
</script>
```


`layouts/weird.vue`:
```vue
<template><h1>JEEZ IS THIS LAYOUT WEIRD ERROR</h1></template>
```

Result on a non-existing page:

![image](https://user-images.githubusercontent.com/640208/44311458-dddbbc80-a3df-11e8-9856-d5f802d8b7d3.png)
