### ISSUE TITLE
Store state not updated by observable mutations

### ISSUE THREAD

**Issue by ralphchristianeclipse** [nuxt/nuxt.js#2774]
So below is part of my code that checks if the user is logged in using graphql apollo watchQuery

actions
```js
  async observeAuth({ commit }) {
    const client = this.app.apolloProvider.defaultClient;
    const observer = client.watchQuery({
      query: Auth,
      subscribeToMore: {
        document: [AuthSubscription, UserSubscription]
      }
    });
    console.log(observer);
    observer.subscribe(({ data }) => {
      console.log("OBSERVER", data.result);
      commit("SET_AUTH", data.result);
    });

    // const { data } = await observer.result();
    // commit("SET_AUTH", data.result);
  },
```
mutations
```js
  SET_AUTH(state, data) {
    console.log("DATA", data);
    state.auth = data;
    console.log("STATE", state.auth);
  },
```

getters
```js
  auth: state => {
    console.log("GETTER", state);
    return state.auth;
  },
```

state
```js
export const state = () => ({
  auth: null,
  token: "",
  setting: null,
  snackbar: {
    value: false,
    html: "",
    options: {}
  }
});

```

so I can use subscriptions to automatically get the data sent by sockets and send it to the next callback 

which i'm using for a shorthand below on observer.subscribe

so the problem is i'm trying to commit the result to the state.auth variable

the problem is that the state doesn't change at all

even i received the data from the observer.next

here is a screenshot to prove that its null

![image](https://user-images.githubusercontent.com/25447231/35841282-22063edc-0b36-11e8-9d47-78d691bd95c5.png)

but when i open it the data is there

![image](https://user-images.githubusercontent.com/25447231/35841291-2d373810-0b36-11e8-94a8-23ac0ab6bbd9.png)

and here on the devtools its null

![image](https://user-images.githubusercontent.com/25447231/35841304-3baaf954-0b36-11e8-8e88-a1cc508b608d.png)

but when i commented out 

this code
on the observeAuth action
```js
    // const { data } = await observer.result();
    // commit("SET_AUTH", data.result);
```

it works fine

![image](https://user-images.githubusercontent.com/25447231/35841350-713ae930-0b36-11e8-8ed8-03a09da798bc.png)

help.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2407">#c2407</a>)</em></sub></div>

**Comment by galvez** [comment]
@ralphchristianeclipse What happens if you retain `context` in your calls?

```js
async observeAuth(ctx) {
//
ctx.commit
```

Closing this as there's been no updates over 90 days.

Please reopen if you still have issues.
