### ISSUE TITLE
Why sometimes "asyncData"  requests from the client's XHR?

### ISSUE THREAD

**Issue by yangzaihuangzi** [nuxt/nuxt.js#2775]
Sometimes the input URL hits the enter key and the asyncData‘s data requests from the server.

![image](https://user-images.githubusercontent.com/32796576/35843849-658a4f2c-0b45-11e8-9e88-88625282c0a3.png)

But！！！
From the routing of other pages, the data is requested from the client.

![image](https://user-images.githubusercontent.com/32796576/35843861-7b2d5d88-0b45-11e8-876b-311b97c60e6c.png)

**Comment by yangzaihuangzi** [comment]
#asyncData

**Comment by NicoPennec** [comment]
the `webpack HMR` is only on dev mode (to auto reload page on source code change)
the `inverstJson.hml`is not from Nuxt.js, but probably trigger by one of yours Chrome extensions.

if you click on `investJson.html` line > select "headers" sub-tab on right > check the "general > request" value
You will see the origin of this XHR request

**Comment by yangzaihuangzi** [comment]
Hello @NicoPennec 
I think :
when enters the URL and hit the enter key, the data comes from the server side.
when From other pages via  jump route , the data comes from the client side .
Is that so ?
I don't think it's because of the development environment.

**Comment by NicoPennec** [comment]
Correct.
`asyncData()` run both from first _server-side_ of the current page and from _client-side_ after each page jump.

See documentation: https://nuxtjs.org/api/#the-asyncdata-method

Your workflow:
- 1st page loaded: this full schemas (top -> down)
- each page jump: the loop <nuxt-link>
![nuxt workflow](https://nuxtjs.org/nuxt-schema.png)

**Comment by ishitatsuyuki** [comment]
If you have any obligations on the server side, use `nuxtServerInit()`.

**Comment by yangzaihuangzi** [comment]
Thank for you @NicoPennec ,I understand...
