### ISSUE TITLE
Duplicating the generation of index.html with nested paths

### ISSUE THREAD

**Issue by mojereliev** [nuxt/nuxt.js#2776]
Hello!

Found a strange behavior when generating static.
index.html is generated twice and it seems the second time the correct one is re-written
(It seems that because of this I can not open the page by a direct link - get [nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.).

Is this a bug or not?

A similar issue was created earlier
https://github.com/nuxt/nuxt.js/issues/2296

Below I attach a screenshot with the structure / pages, the paths of the router and logs

![36vu-6_uqcs56n4glmwt6q](https://user-images.githubusercontent.com/13470898/35848481-1d87b07a-0b40-11e8-9ce7-6c587fd12cd0.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2408">#c2408</a>)</em></sub></div>

**Comment by mojereliev** [comment]
In `index.vue` there is a common code for nested routes (index, cases, cases/id)
This is like a common header and footer for all pages

**Comment by mojereliev** [comment]
@clarkdo, If I ignore locally the generation of the route '' in generator.js, then everything works fine. Is it possible to exclude this route from generation to nuxt? Do I make PR?

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
