### ISSUE TITLE
add ability to auto import components per page

### ISSUE THREAD

**Issue by asv1** [nuxt/nuxt.js#2777]
There is currently no possibility to auto import components per page without writing boilerplate:
``
import myComp from '~/components/my-comp.vue'
``
I suggest adding the ability to group components by page name. Example:
pages/index.vue
pages/level1.vue
pages/level1/level2.vue

components/my-component.vue
components/level1/text-component.vue
components/level1/level2/image-component.vue

my-component will be auto imported by index.vue page.
text-component - by level1.vue
image-component - by level2.vue

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2410">#c2410</a>)</em></sub></div>

**Comment by pi0** [comment]
I love this idea. Another use case would be in big component libraries (Like Vuetify, Framework7-Vue, BootstrapVue, ...) to *auto import* only needed components only on page chunks where needed without any extra boilerplate.

My proposal is writing a webpack loader (probably in front of `vue-loader`) to statically analyze and detect used tags. But it may need more works for JSX, render function and dynamic tags (Probably some of them won't supported forever)

**Comment by phanan** [comment]
Can't say I'm a fan of this magic. `import`ing a component/class/namespace should always be explicit, otherwise we'll have a hard time reasoning their whereabouts. I'd prefer autocomplete support at IDE level instead.

**Comment by kzh55** [comment]
And one more. All root components in ~/components will import globally.

**Comment by asv1** [comment]
And one more. All root components in ~/components will be imported globally.

**Comment by marines** [comment]
That would make all the tree shaking useless and would waste user's resources.

**Comment by asv1** [comment]
This ability can be optional and configured via nuxt.config.js.

**Comment by marines** [comment]
It should not be a feature in the first place.

**Comment by asv1** [comment]
Off by default and turned on only if need.

**Comment by pauldariye** [comment]
@asv1, is this perhaps similar to [nextjs's dynamic imports feature](https://github.com/zeit/next.js/#dynamic-import)?

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.

**Comment by daspete** [comment]
An easy and working way would be a fs.readdirSync which scans a specific directory, which contains all components which should be imported automatically, in the nuxt.config.js file...

nuxt.config.js example:

```
import fs from 'fs'

let components = fs.readdirSync('./components')
components = components.join(',') // since the env should just contain strings

module.exports {
    env: {
        components: components
    }
}
```

and then make a plugin, and include it in the nuxt.config.js file. This plugin loads all the components:

```
import Vue from 'vue'

let components = process.env.components.split(',')

components.forEach((componentName) => {    
    Vue.component('content-block', require('~/components/' + componentName).default)
})

```` 

That way all Components located in the ~/components folder are loaded automatically

**Comment by daspete** [comment]
An easy and working way would be a fs.readdirSync which scans a specific directory, which contains all components which should be imported automatically, in the nuxt.config.js file...

nuxt.config.js example:

```
import fs from 'fs'

let components = fs.readdirSync('./components')
components = components.join(',') // since the env should just contain strings

module.exports {
    env: {
        components: components
    }
}
```

and then make a plugin, and include it in the nuxt.config.js file. This plugin loads all the components:

```
import Vue from 'vue'

let components = process.env.components.split(',')

components.forEach((componentFileName) => {
    const component = require('~/components/' + componentFileName).default    
    Vue.component(component.name, component)
})


```` 

That way all Components located in the ~/components folder are loaded automatically. 

Note, that each component must have a name parameter

**Comment by pauldariye** [comment]
This doesn't really solve it though @daspete. Have a look at nextjs' dynamic imports. A use case for which I've used dynamic imports is you're building components for content blocks in a cms. A page in the cms may contain any number of components, so you'd want to only require those components used in the content blocks of the page.

**Comment by daspete** [comment]
> This doesn't really solve it though @daspete. Have a look at nextjs' dynamic imports. A use case for which I've used dynamic imports is you're building components for content blocks in a cms. A page in the cms may contain any number of components, so you'd want to only require those components used in the content blocks of the page.

hmm... i thought, that only that components, which are just in the current page are imported for that specific page. Of course, the vendor file, or app file will be a little bit bigger, but that way, the user has to wait just one time to load it all and then there is no more loading time (or much less) then to load a new custom app or vendor file for each page...
