### ISSUE TITLE
Error while running command "npm run test" or "yarn run test"

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt/nuxt.js#2778]
I'm trying to work on improvements to nuxt.js, but when cloning the repository, installing its dependencies and running tests without changes, there is always an error or process stop.

- git: **2.16.0.windows.2**
- node: **9.4.0**
- npm: **5.6.0**

```
git clone https://github.com/nuxt/nuxt.js.git
cd nuxt.js
npm install // yarn install

// Error
npm run test // yarn run test

// OK
npm run test-appveyor // yarn run test-appveyor
```

**Comment by Atinux** [comment]
Hey @ricardogobbosouza 

Should be fixed now, could you try again please? If not resolved, re-open the issue :)
