### ISSUE TITLE
Global CSS not being included in production build

### ISSUE THREAD

**Issue by samtgarson** [nuxt/nuxt.js#278]
Hey there

I'm including a couple of third party style libraries in the `css` property of the nuxt config as described [here](https://nuxtjs.org/api/configuration-css).

This works great in development however in production, only the styles from my `.vue` components is included. 

You can see my nuxt.config.js [here](https://github.com/samtgarson/now-ci/blob/master/src/nuxt.config.js) and the site is deployed [here](https://now-ci-enshgxobny.now.sh).

Have you seen this before? Cheers

**Comment by Atinux** [comment]
Hi @samtgarson 

This is not a bug, you call `nuxt build` in your package.json but Nuxt does not find the `nuxt.config.js` in the root directory, you have to give him the path to it: `nuxt build src/`

Then, in your `nuxt.config.js`,  you can define the [rootDir](https://nuxtjs.org/api/configuration-rootdir) of your application.

You can see my pull request to fix your project [there](https://github.com/samtgarson/now-ci/pull/1).

**Comment by samtgarson** [comment]
Thank you for the PR 👍
