### ISSUE TITLE
Anchors

### ISSUE THREAD

**Issue by DevDom05** [nuxt/nuxt.js#2780]
I have issues with anchors
a link to "/#div" display the target page
but the id is not targeted.

Instead, the scroll position is the same of the previous page for example

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2412">#c2412</a>)</em></sub></div>

**Comment by awronski** [comment]
I don't know if it was fixed, but the vue-router was looking for the el before the new page is rendered.

@pi0 Could you comment this?
https://github.com/nuxt/nuxt.js/issues/723#issuecomment-302451686

**Comment by Atinux** [comment]
Hi @DevDom05 

What version of Nuxt.js are you using?

**Comment by onlyurei** [comment]
I can reproduce after upgrading to `1.3.0` from `1.0.0-gh-adc7260`. It works fine on `1.0.0-gh-adc7260'.

**Comment by onlyurei** [comment]
Hi @Atinux I just tried the latest release of v1.4.0, this issue is still happening.

**Comment by maziarz** [comment]
I have the same issue on v1.4.0

**Comment by onlyurei** [comment]
A working work-around fix of using a custom `scrollBehavior` in `route` option in `nuxt.config.js`: https://github.com/nuxt/nuxt.js/issues/2738#issuecomment-372007743.

**Comment by imShara** [comment]
@onlyurei , this work-around works bad. There is jumping scroll glitch after click on nuxt-link. Problem with internal anchor links not solved, inpage navigation with anchors should work out of the box.
