### ISSUE TITLE
How to debug nuxt in JetBrains WebStorm?

### ISSUE THREAD

**Issue by jinhuiWong** [nuxt/nuxt.js#2781]
How to debug nuxt in JetBrains WebStorm?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2413">#c2413</a>)</em></sub></div>

**Comment by ishitatsuyuki** [comment]
Probably <insert browser here> remote.

**Comment by jack913486781** [comment]
i  tried add debug configuration of NPM is inoperative,i want know why

**Comment by LancerComet** [comment]
1. Add a node debug in Webstorm and fill `Javascript file` with this:

```
node_modules\nuxt\bin\nuxt-dev
```

![](http://cdn.lancercomet.com/debug-nuxt-01.png)

2. Add `devtool` in `nuxt.config.js`:

```javascript
extend (config, { isDev, isClient }) {
  if (isDev) {
    config.devtool = 'eval-source-map'  // Something you like
  }
}
```

![](http://cdn.lancercomet.com/debug-nuxt-02.png)

Done!

![](http://cdn.lancercomet.com/debug-nuxt-03.png)

**Comment by blowsie** [comment]
@LancerComet in my case, this steps into a generated file `pages_index.js` instead of debugging inside `pages/index.js` itself. Is this the expected behaviour?
