### ISSUE TITLE
How to merge Javascript files

### ISSUE THREAD

**Issue by Caiphas92** [nuxt/nuxt.js#2785]
It would produce lots of *.js files after the project is built. Please tell me how to merge those files to one file.
![6666666666666](https://user-images.githubusercontent.com/28722470/35896380-d59e5ffe-0bf6-11e8-85d9-7f41a9c0f44c.png)

**Comment by clarkdo** [comment]
These files are for asynchronous loading, each one is a separated page, with this process you won't need to load all unrelated pages, so it will make pages loading more efficiency.

If you don't want to use it, you can use [@nuxt/router](https://github.com/nuxt-community/router-module) and manually define `router.js` with static import:

```js
// router.js
import Vue from 'vue'
import Router from 'vue-router'

import MyPage from '~/components/my-page' // static import

Vue.use(Router)

export function createRouter() {
  return new Router({
    mode: 'history',
    routes: [
      {
        path: '/',
        component: MyPage
      }
    ]
  })
}
```

**Comment by tevel** [comment]
can you please explain a bit more?
where should I put this file router.js?

**Comment by clarkdo** [comment]
@tevel 
The router.js can be put into `${srcDir}/app/router.js`

srcDir: https://nuxtjs.org/api/configuration-srcdir#the-srcdir-property
