### ISSUE TITLE
how to override the global middleware config in one page?

### ISSUE THREAD

**Issue by xxxxxMiss** [nuxt/nuxt.js#2786]
Now, all pages required authentication except the login page.  I can config the auth middleware in all pages except the login page, that is too trouble. How can i config a global auth middleware except the login page? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2416">#c2416</a>)</em></sub></div>

**Comment by microcipcip** [comment]
@xxxxxMiss If you know the url of the login page you can do something like this (this is how I implemented it): 
```
  // exit middleware when the route match '/admin/login' is login page
  const isLoginPage = route.fullPath === '/admin/login'
  if (isLoginPage) return
```

**Comment by clarkdo** [comment]
@microcipcip is correct, currently there is no way to exclude the specific path, we can discuss if it's necessary to add into backlog.

**Comment by xxxxxMiss** [comment]
@microcipcip @clarkdo I do it so now,but it is not flexible. I think we should support middleware is a regexp or an object like it: `{ include: ['path1', 'path2'], exclude: ['xx']}` or some other styles

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
