### ISSUE TITLE
can we access context object from a vue component ?

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nuxt/nuxt.js#2788]
can we access context object in vue component?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2418">#c2418</a>)</em></sub></div>

**Comment by microcipcip** [comment]
What object are you trying to access? You already have access to all variables, for example
```
this.$store
this.$route
// etc
```

**Comment by makoso** [comment]
up

**Comment by nurdus** [comment]
Hi, how can access in script section? I tried "console.log($route.name)", but got error: Cannot read property 'middleware' of undefined.

**Comment by nurdus** [comment]
```
<script>
// imports ...
console.log(this.$route.name) // doesn't work, I think it doesn't have to work
export default {
  data () {
    console.log(this.$route.name) //work
  }
}
</script>
```

**Comment by microcipcip** [comment]
@nurdus you can't access anything regarding the route outside the export, Vue may not even be initialized there AFAIK. Why would you need to do that anyway? Maybe you need a different approach for what you're trying to achive.

**Comment by nurdus** [comment]
I've tried testing, it was my mistake :) Thanks.

**Comment by blowsie** [comment]
According to this doc, `isDev` is available on client and server.

How do you access it on client?

**Comment by microcipcip** [comment]
@blowsie have you tried `process.isDev` or `process.env.isDev`?

**Comment by blowsie** [comment]
Quote from @manniL via discord.

>So, the context object is available in the asyncData and fetch functions (as parameter)
You also can access it in nuxtServerInit
And in plugins as well

 https://codesandbox.io/s/m3xqj4joky
