### ISSUE TITLE
How to disable ETag ?

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#2791]
Hi!

I want to disable etag. I tried:

nuxt.config.js:
```js
  render: {
    etag: false
  },
```

but it doesn't work.

Thanks in advance,

**Comment by NicoPennec** [comment]
The only available option in `nuxt.config.js` is:

```js
render: {
   etag: {
      weak: false
    }
}
```

see https://github.com/nuxt/nuxt.js/blob/72300d350ef6c3087fd1a3d1c4480e4d02932281/lib/common/options.js#L323

**Comment by pi0** [comment]
Possible indeed. Just set `etag` option to `false` in `nuxt.config.js`

```js
render: {
   etag: false
}
```

source: https://github.com/nuxt/nuxt.js/blob/72300d350ef6c3087fd1a3d1c4480e4d02932281/lib/core/middleware/nuxt.js#L30

**Comment by awronski** [comment]
@pi0 Thanks. I did some mistake. After second try it works 👍 

Is it possible to do the same for .js files?

**Comment by pi0** [comment]
@awronski Yes. See my edited comment. It is only impossible to disable for `static/` content. (Which there is no reason to do)
