### ISSUE TITLE
nuxtServerInit running on every time index page is reload

### ISSUE THREAD

**Issue by pxwee5** [nuxt/nuxt.js#2796]
I just realized that `nuxtServerInit` is run everytime index page is loaded. Is that supposed to be the case? 

I would think that server init means it only run once during the whole session. We are using `nuxtServerInit` to grab a lot of data from the api and having it run everytime we navigate to index page is really slow. 

Am I using it wrong?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2425">#c2425</a>)</em></sub></div>

**Comment by chanlito** [comment]
@pxwee5 Yes `nuxtServerInit` will get executed everytime.

**Comment by iamdubx** [comment]
@pxwee5 do you realize that loading the page and navigating on site is different cases? I am not sure what do you mean by 

> We are using nuxtServerInit to grab a lot of data from the api and having it run everytime we navigate to index page is really slow.

**Comment by pxwee5** [comment]
I guess it's just a misunderstanding of how I understood `nuxtServerInit` in the beginning. 

@iamdubx in this case I believe they are the same. Reloading and navigating to index procs `nuxtServerInit`. 

I should have explained abit more. I'm running a headless CMS and I'm fetching navigation data in `nuxtServerInit`. I only need this to be fetched one time for the entire session. 

What else can I use if this is not the usecase for `nuxtServerInit` ?
