### ISSUE TITLE
nuxt.js on shared hosting

### ISSUE THREAD

**Issue by ngodink** [nuxt/nuxt.js#2797]
hello, i have 3 subdomain with nuxt.js, 1 subdomain as api with lumen (laravel-microframework)..

account.domain.com -> as single sign-on gateway
admin.domain.com -> as admin page (redirect to account.domain.com if not logged in - using session in backend api)
member.domain.com -> as member page (redirect to account.domain.com if not logged in - using session in backend api)
api.domain.com -> as a backend, session is located here

and i run `npm run build`, and i upload all directory .nuxt to public_html, the result is return a javascript codes (index.js), i also try `npm run generate`, but that is not redirected to account.domain.com when i using direct access to admin.domain.com

what should i do ? anybody can help me  ?

*i tried with localhost, it is no problem and ready for use with shared hosting

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2424">#c2424</a>)</em></sub></div>

**Comment by manniL** [comment]
This question can be answered on [CMTY](https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2424)
