### ISSUE TITLE
Execution of NPM run generate, error occurred, connect econnection 127.0.0.1:80.

### ISSUE THREAD

**Issue by aymfx** [nuxt/nuxt.js#2798]
![_20180208162933](https://user-images.githubusercontent.com/18900329/35962697-54648a2e-0ced-11e8-80d3-da971b128b80.png)
> In the development environment, there is no error reporting. When it is packaged into a static file, the error is reported. The current API is accessible, and the error is shown below.
![2](https://user-images.githubusercontent.com/18900329/35962771-9473e222-0ced-11e8-9040-24f1e4899f0b.png)
> How can I solve this problem?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2427">#c2427</a>)</em></sub></div>

**Comment by yangzaiwangzi** [comment]
Maybe The conflict comes from port .
I think you try to turn 8080 into other

**Comment by BonnieDoug** [comment]
@mhpm you really should open your own issue, with the code you believe is causing you issues + error logs and anything you think may help to decipher your problem. Hijacking unrelated issues is generally frowned upon throughout the online community.

**Comment by manniL** [comment]
@mhpm upgrade you nod eversion.

@aymfx your port is already in use. try 3000 or any higher number.
