### ISSUE TITLE
Safari problem because of whatwg-url

### ISSUE THREAD

**Issue by SalvadorDuran** [nuxt/nuxt.js#2799]
I just notice that my app can't run on safari because the error of whatwg-url https://github.com/jsdom/whatwg-url/issues/108

> new.target can't come after a prefix operator

Is there any idea to solve this problem?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2428">#c2428</a>)</em></sub></div>

**Comment by griv** [comment]
Same here...

**Comment by SalvadorDuran** [comment]
@griv were you using nuxt in production? did you find a solution?

**Comment by griv** [comment]
@SalvadorDuran I'm about deploy to production (I'm not using nuxt though, just jsdom - imported from fabric.js).
I edited line 8 of URL.js to be
`if (new.target === undefined) {`
and that's fixed it.

**Comment by galvez** [comment]
Closing this as there's been no updates over 90 days.
