### ISSUE TITLE
Context support in layouts

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#280]
Hi!

Right now there is no context in the layouts.

I can understand why there is no context in components and it is not a problem. I can inject needed variables from pages to components via props. As described [here ](https://nuxtjs.org/faq/async-data-components)

But how I can do it with layout?

For example I would love to do things like this:
```html
<div v-if="isDev"> [...] </div>
```
or like to change some layouts component according to the ``http.Request`` etc.

Is it possible to add context to the layouts or maybe there is some workaround?

Thanks in advance,

**Comment by alexchopin** [comment]
Hi, 
You can catch the `context` in the [nuxtServerInit](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action) action in the Store and/or in the data method in the Pages component.
Then you set a state variable like isDev for example.
Finally, you will be able to change you layout components according to the context.

**Comment by awronski** [comment]
Brilliant, Thank you!

One more thing. If I need to load application configuration, eg. using [node-config](https://github.com/lorenwest/node-config).

How can I access it or add to the context. What is the best place to hook.

Thanks!

**Comment by Atinux** [comment]
@awronski I believe the `nuxtServerInit` action is the best place to fetch your application configuration and put it in the store.

**Comment by awronski** [comment]
@Atinux Thanks for the reply.

But ``nuxtServerInit`` in executed for every new request. I need to load the configuration only once. 
Is there a hook like a on server start that I can use?

thanks in advance!

**Comment by Atinux** [comment]
`nuxtServerInit` is called only for an incoming request on server-side, so once per user (except if they clic on the browser `refresh` button).

If you have global variables, you can add them in the `req` object directly in your server-side, so they would be available in every context whatever the page.

Example with Express.js:
```js
app.use(function (req, res, next) {
  req.foo = 'bar'
  next()
})
app.use(nuxt.render)
```
Then, in your `nuxtServerInit`, you will have access to `context.req.foo`.

**Comment by Atinux** [comment]
But I believe that you should use the [env property](https://nuxtjs.org/api/configuration-env/#the-env-property).

**Comment by awronski** [comment]
Thank you, it is exactly what I did:
https://github.com/awronski/nuxtjs-examples/tree/master/external-configuration
