### ISSUE TITLE
serverMiddleware - cannot access env property

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#2800]
Hi!

In the pages I can access nuxt [env property](https://nuxtjs.org/api/configuration-env) with ```process.env.var_name```
But it doesn't work in serverMiddleware.

```process.env.var_name``` returns undefined in serverMiddleware.

Thanks for any hints,

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2429">#c2429</a>)</em></sub></div>

**Comment by chanlito** [comment]
@awronski can you try using with `@nuxtjs/dotenv` ?

**Comment by pSchaub** [comment]
Same issue here, env variables are not working in serverMiddleware code.

**Comment by manniL** [comment]
As `serverMiddleware` is decoupled from the main Nuxt build, you cannot access env variable set through the `env` object in your `nuxt.config.js`

Solution one: Use "real" env variables. These are available in the server middleware (e.g. `TEST=YES npm run dev` -> `console.log(process.env.TEST) //YES`

Solution two: Use a function to fill your server middleware with the necessary values.
[Example](https://github.com/nuxt-community/redirect-module/blob/master/lib/middleware.js)
