### ISSUE TITLE
ssr server innerhtml dehydration ?

### ISSUE THREAD

**Issue by sprabowo** [nuxt/nuxt.js#2801]
![1212](https://user-images.githubusercontent.com/11748183/35979694-91ad05ae-0d1b-11e8-9d35-77e579be999f.jpg)

**Comment by yangzaiwangzi** [comment]
error from your tag innerHTML

**Comment by husayt** [comment]
Your error details don't show the problem. Most probably something wrong with your template. Again, one has to see that to see the cause. Also, there are many similar issues here and probably their solution will apply to your case as well.

If already resolved, just close the issue pls.

**Comment by sprabowo** [comment]
i'm sorry i have missed to process html tag data &amp;amp; instead &amp; so it must &
