### ISSUE TITLE
ERROR  Failed to compile with 1 errors - missing clinet.js

### ISSUE THREAD

**Issue by simonl65** [nuxt/nuxt.js#2805]
I'm not sure if this is a better place to raise this (i already contributed to [issue #48 in create-nuxt-app](https://github.com/nuxt-community/starter-template/issues/48), but the issue may well be with nuxt core?

I'm getting the following error no matter whether I use `create-nuxt-app`, `vue init nuxt-community/starter-template` or follow the [start from scratch](https://nuxtjs.org/guide/installation#starting-from-scratch) instructions:
```
ERROR  Failed to compile with 1 errors                                                                                                                                                                                              13:00:59

This dependency was not found:

* E:\simonl\Documents\_dev\!learning\nuxt003\.nuxt\client.js in multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

To install it, you can run: npm install --save E:\simonl\Documents\_dev\!learning\nuxt003\.nuxt\client.js

OPEN  http://localhost:3000
```
I have:
+ vue v2.9.3
+ node v8.8.1
+ npm v5.6.0

My package.json
```json
{
  "name": "nuxt003",
  "version": "1.0.0",
  "description": "Nuxt.js project",
  "author": "Simon Lincoln <simonl@enlight.co.uk>",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "nuxt": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "eslint": "^4.15.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-vue": "^4.0.0"
  }
}
```
What have I missed?

**Comment by EllenFawkes** [comment]
Try use new version of nuxt. Latest nuxt version is **1.3.0**

**Comment by simonl65** [comment]
@EllenFawkes Thanks for the swift response.

Yup - according to package-lock.json I'm already using 1.3.0:
```
    "nuxt": {
      "version": "1.3.0",
      "resolved": "https://registry.npmjs.org/nuxt/-/nuxt-1.3.0.tgz",
      "integrity": "sha512-H5FpsZXVu1gfecif5v6q6F04HfoUJcCnMHBJXayAPRYG/RHYwy32Df3vIBJ7U5HbDkyW9UebaLtHAYk17iTA/g==",
```

**Comment by EllenFawkes** [comment]
Are you tried clean .nuxt folder or remove node_modules and install it again? I trided create new project and it's works. But I am on Linux, not windows.

**Comment by simonl65** [comment]
I did - I've also tried this on a seperate PC and get same issue. Maybe I'll spin-up a linux VM and see if it works for me there.

**Comment by EllenFawkes** [comment]
Oki. Maybe it's windows problem, but I can verify it, because i don't have PC with windows on that place, where actually I am. :/

**Comment by simonl65** [comment]
That's OK, I can try it on Linux. Thanks for your help anyway 👍

**Comment by simonl65** [comment]
Oh no - I've just got it working on a fresh Win10 VM! That must mean it's a conflict with something I have running on the two other machines I tested on :-( Time to go hunting...

Thanks for your help peeps. I'll report back here if/when I find the cause.

**Comment by EllenFawkes** [comment]
Which version of nodejs and npm used on W10 VM?

**Comment by simonl65** [comment]
node 8.8.1, npm 5.6.0

I've just upgraded to node 8.9.4 (npm stays at 5.6.0) but get same error. I'll keep investigating.

**Comment by Atinux** [comment]
Thank you for looking at it @simonl65 

I use Nuxt.js everyday on Mac & Linux and works perfectly, I know Windows can be hard on paths resolution. Are there any special chars in your path where your project lives (like `!` or any special char)?

**Comment by CallMeFoxie** [comment]
https://github.com/webpack/webpack/issues/5320
possibly?

**Comment by EllenFawkes** [comment]
I don't think about windows paths difference and abnormality :laughing: @CallMeFoxie

**Comment by simonl65** [comment]
You're kidding me! I've lost hours due to an exclamation mark in my folder path! @CallMeFoxie / @Atinux  you're stars - thank you so much! (Arrgh! Must stop using exclamation marks!).

Thanks peeps.
