### ISSUE TITLE
nuxt pdfmake

### ISSUE THREAD

**Issue by batkor** [nuxt/nuxt.js#2813]
I can not send an image to pdfmake
my code: 
```javascript
let docDefinition = {
          content: data,
          styles: {
            header: {
              fontSize: 16,
              bold: true,
              margin: [0, 0, 0, 20]
            },
            cell: {
              margin: 5,
              fontSize: 9
            }
          },
          images: {
            img: '/myimg.png'
          }
        }
        pdfmake.createPdf(docDefinition).open({}, window)
```

error:
Uncaught invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)

**Comment by microcipcip** [comment]
I think you need to reference the image with `~`? Like ` { img: '~/myimg.png' }`. Check [the docs here](https://nuxtjs.org/guide/assets).

**Comment by batkor** [comment]
ty, I did like this:
`

1. methods: {
2.       toDataURL: function (url, callback) {
3.         let xhr = new XMLHttpRequest()
4.         xhr.onload = function () {
5.           let reader = new FileReader()
6.           reader.onloadend = function () {
7.             callback(reader.result)
8.           }
9.           reader.readAsDataURL(xhr.response)
10.         }
11.         xhr.open('GET', url)
12.         xhr.responseType = 'blob'
13.         xhr.send()
14.       }
15. ...
16. this.toDataURL(require('~/assets/podpis.png'), (dataUrl) => {
17.           pdfmake.vfs = vfsFonts.pdfMake.vfs
18.           let dataCheck = this.generateCheck()
19.           let docDefinition = {
20.             content: dataCheck,
21.             styles: {
22.               header: {
23.                 fontSize: 16,
24.                 bold: true,
25.                 margin: [0, 0, 0, 20]
26.               },
27.               cell: {
28.                 margin: 5,
29.                 fontSize: 9
30.               }
31.             },
32.             images: {
33.               mainImg: dataUrl
34.             }
35.           }
36.           pdfmake.createPdf(docDefinition).open({}, window)
37.         })
`

**Comment by batkor** [comment]
issue close? ty

**Comment by microcipcip** [comment]
Good, you can close it ;)
