### ISSUE TITLE
How does the Static directory work with CDN?

### ISSUE THREAD

**Issue by tyrion-yu** [nuxt/nuxt.js#2817]
We know that `publicPath` can be set to a CDN.
When launching `nuxt build`, upload the content of `.nuxt/dist/` directory to your CDN and voilà!

BUT what about files in static directory?
Can we upload to the CDN too ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2446">#c2446</a>)</em></sub></div>

**Comment by ckipp01** [comment]
Hey! So, you'll actually not upload the content of your .nuxt/dist/ directory, rather when you `npm run generate`, a dist/ directory will be created at the root of your project. That's the directory you'll want to push up to whomever is providing your CDN service. 

Also, the contents of your static directory will also be included in that dist directory that will be created when you run `npm run generate`. So no no need to include them separately.
