### ISSUE TITLE
[error] Command failed with exit code 3221225725.

### ISSUE THREAD

**Issue by ArStah** [nuxt/nuxt.js#2818]
Hi everyone. I've ran to very weird issue... 
I'm using [semantic-ui-vue](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue) in my nuxt project, and maybe it is a issue of that package, but maybe not, because it's occurs while ssr.
When my code is rendered on server-side, depends on the amount of the items in array that i pass to `sui-dropdown` component, i get an error `Command failed with exit code 3221225725`
When there is only 148 items in array - all ok, but when 149 or more(in some cases can need more) - get error.
I don't have any ideas how it can be possible.
If wrap `sui-dropdown` with `<no-ssr>` tag - all ok..
Here is [the repo](https://github.com/ArStah/nuxt-semantic-ui-vue-weird-error) to reproduce it

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2447">#c2447</a>)</em></sub></div>

**Comment by manniL** [comment]
This question can be answered on [CMTY](https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2447)
