### ISSUE TITLE
Access to app variable anywhere

### ISSUE THREAD

**Issue by Michkkael** [nuxt/nuxt.js#2821]
Hi all!
I can't find out the way of accessing to `app` variable from a component or a page as we can do in middleware or plugins.
I would like the `app` because I want to get attached instance of plugins, for example i18n.
`app.i18n.fallbackLocale`

Do you know how is it possible ?
Thx

**Comment by microcipcip** [comment]
Have you tried with `this.$i18n`?

**Comment by Michkkael** [comment]
Yes, but what if it's not a vuejs plugin ?
For example: 
```js
// plugins/myPlugin.js
import MyPlugin from 'my-plugin'

export default ({ app }) => {
  app.myPlugin = new MyPlugin()
  app.myPlugin.init()
}
```

In this case, I would like doing this:
```jsx
// components/MyComponent.vue
<script>
export default {
  methods: {
    destroyMyPlugin() {
      this.myPlugin.destroy() // <-- I can't do this :/ 
    }
  }
}
</script>
```

**Comment by EllenFawkes** [comment]
You can try inject your plugin with method inject.

```javascript
// plugins/myPlugin.js
import MyPlugin from 'my-plugin'

export default ({ inject }) {
  let myPlugin = new MyPlugin()
  myPlugin.init()
  inject('myPlugin', myPlugin)
}
```

and then yu can access your plugin via prefix $

```javascript
// components/MyComponent.vue
<script>
export default {
  methods: {
    destroyMyPlugin() {
      this.$myPlugin.destroy() // <-- I can't do this :/ 
    }
  }
}
```

**Comment by Michkkael** [comment]
Great! Thank you very much @EllenFawkes  :)
I did not know `inject`

Just one precision: inject is undefined if I want to get it with object destructuring. 
So I had to do this:
```js
export default({}, inject) {
  // blah blah blah
  inject('myPlugin', myPlugin)
}
```

**Comment by EllenFawkes** [comment]
@Michkkael oh, my mistake. Yes, inject is a 2nd parametr, is not part of context. :)

**Comment by microcipcip** [comment]
@Michkkael I think that was a typo in her example. inject is outside the context object, so basically you always need to do something like this:
```
export default({ app, store }, inject) {
  // blah blah blah
  inject('myPlugin', myPlugin)
}
```

**Comment by fugroup** [comment]
This works, $filters becomes available in the component template and methods:
```
export default (ctx, inject) => {
  inject('filters', filters)
}
```

**Comment by DCdeBrabander** [comment]
I aswell use `inject()` to add/access objects via Vue instance .
Although I'm having trouble getting it to work inside (Jest) unit tests. 
I need to 'load' the plugins to be able to test some stuff, anybody solved this already?

**Comment by fugroup** [comment]
@DCdeBrabander If you just want to do unit tests you can just have whatever you're injecting in a separate file and require that in your test file directly?

**Comment by LukasBombach** [comment]
If I may come back to the original question: How do you access the `app` object in a component?

**Comment by LukasBombach** [comment]
5 seconds later I found it:

```js
this.$root.context.app
```

**Comment by rkbrewer** [comment]
For anyone interested in accessing the Nuxt "app" _(and any registered plugin!)_ inside a Vuex Action, those things are available via the Vuex Instance (the "this" inside the action):

You can also access the `$router` instance!

```
const actions = {
  myAction(context, data) {
    const response = this.$axios.post('/foo', data);
    context.commit('someMutation', response.data);
  }
};
```

**Comment by jbgraug** [comment]
in nuxt.config:
```
{ ...
   env: {
     myVar: 'Some Value' 
   }
...
}

```

anywhere (including mixins, plugins, etc.)

`console.log(process.env.myVar) // 'Some Value'`

**Comment by half-wit-wanted355** [comment]
@purrplingcat https://openjs.space/questions/leveraging-a-nuxt-plugin-and-saving-it-in-middleware
