### ISSUE TITLE
process.client can't be used in TS based environment

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/nuxt.js#2823]
Since I've updated to Nuxt v. 1.3.0 I started getting a deprecation warning inside my middleware functions:
context.isClient has been deprecated, please use process.client instead.
but I can't change my code to use process.client instead because of TS error:
```
TS2339: Property 'client' does not exist on type 'Process'.
```
so it seems like this change was made without TS in mind. 
A workaround was suggested by @qm3ster 
```
declare namespace NodeJS {
  export interface Process {
    client: boolean
    server: boolean
  }
}
```
but I guess such considerations should be done on the Nuxt level.
The issue was discovered when working with [nuxt-community/typescript-template](https://github.com/nuxt-community/typescript-template/issues/33) 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2453">#c2453</a>)</em></sub></div>

**Comment by qm3ster** [comment]
I agree that nuxt should ship this.
Do you know how this can be written to be supplied by the nuxt package?
I'm not good at distributing `.d.ts`, can we even add something to the ambient environment of the consuming package?

**Comment by IlyaSemenov** [comment]
The workaround around violates [typescript/no-namespace](https://github.com/nzakas/eslint-plugin-typescript/blob/master/docs/rules/no-namespace.md) eslint rule. Is there some other way to extend a built-in interface?

**Comment by AndrewBogdanovTSS** [comment]
@IlyaSemenov that's the gist of all workarounds - they are not ideal. The only good way this can be resolved is by fixing this bug inside Nuxt.js itself

**Comment by galvez** [comment]
We're revisiting this if improved TS support ever comes to the table, right now it's not a priority. Closing as there's been no updates for over 90 days.

**Comment by AndrewBogdanovTSS** [comment]
@galvez wasn't TS support on the table already? I don't understand why it should be neglected as something unimportant?

**Comment by galvez** [comment]
@AndrewBogdanovTSS well, we definitely don't want a half-assed approach to supporting TS 😄

As it stands, right now Nuxt is philosophically distanced from TS due to most main contributors preferring standard JavaScript. Of course as Ryan Dahl's Deno offering evolves, TS becomes more interesting and the case might be made then for a complete review of potential TS enhancements. 

For now, we would of course appreciate any PRs you or others may have that improve our TS support in a conservative manner.
