### ISSUE TITLE
npm run dev does not wortk with starter template nuxt

### ISSUE THREAD

**Issue by mhpm** [nuxt/nuxt.js#2824]
![image](https://user-images.githubusercontent.com/32468301/36120353-bdf71e5e-0ff7-11e8-9c6f-bdc1a9746b67.png)

**Comment by AndrewBogdanovTSS** [comment]
What version of Node do you use? The error is pretty self explanatory, your environment doesn't support Async/Await

**Comment by mhpm** [comment]
Hello @AndrewBogdanovTSS, i have the lastes update, it happends when i run npm run dev with nuxtjs, but  without nuxt it runs well. sorry for my english.  i only followed the official tutorial for installation https://nuxtjs.org/guide/installation,  but it does not working for me.

**Comment by mhpm** [comment]
it was resolved, i just reinstall npm install and it overwrite the dependencies

**Comment by husayt** [comment]
@mhpm can you please close this issue then?

**Comment by mhpm** [comment]
how can i closet? im noob on this

**Comment by sudhir600** [comment]
I was facing the same issue. 
When i looked error closly, I found that it was npm missing.

this solve by `npm install --save nuxt`

Hope this will help other developers.
![image](https://user-images.githubusercontent.com/4952560/38781586-03c0c62c-4105-11e8-89e5-53c642399256.png)

**Comment by AndrewBogdanovTSS** [comment]
@sudhir600 that looks strange. Since npm 5 --save functionality is happening by default so it should make no difference. Maybe you are using older version of npm?
