### ISSUE TITLE
Nuxt build live crashes app

### ISSUE THREAD

**Issue by sebastianks** [nuxt/nuxt.js#2827]
Hello.

I've created an eCommerce solution using Nuxt and Cockpit CMS. The app runs great and everything is good... That is until I make changes to the app, and run `yarn build && yarn start` again on the server, and then try to navigate around the app - the app crashes whenever I try to click on a link (`nuxt-link`), but if I go directly to a URL like `my-domain.com/products` it loads as it should.

If I want the app to work again, we have to clear the browser cache and cookies - else it loads forever and crashes the browser. When I run the app locally it runs, but yeah, as soon as it's live it crashes. It's of course not ideal that it requires a browser cache clear, since it's running on thousands of customers computers.

The solution is hosted at Digital Ocean.

Do any of you have any suggestions to what I am doing wrong?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2458">#c2458</a>)</em></sub></div>

**Comment by Prozi** [comment]
did you check the obvious: developer console?
include logs

**Comment by sebastianks** [comment]
Yes I did check the console.
The pm2 logs have nothing - not sure what other logs I should check?

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
