### ISSUE TITLE
Can't acces `this` in watch property

### ISSUE THREAD

**Issue by samuells** [nuxt/nuxt.js#2828]
I tried to watch my properties for change and than trigger a following function:
```javascript
data(){
  return {
    isActive: false,
    unsavedChange = false
  }
},
watch: {
    isActive: {
      handler: () => {
        this.$log.info('was changed')
        this.unsavedChange = true
      },
      deep: true
    }
  },
```
I can't access `this` - in the case of plugin ($log) I get error and `unsavedChange` do nothing in global scope.

But if I log just `this` out - it looks like a different instance of vue is created. Is this correct behaviour?

thx

**Comment by skilFullGH** [comment]
You should not use an arrow function to define a watcher, https://vuejs.org/v2/api/#watch

**Comment by samuells** [comment]
True! Thx @skilFullGH I totally forgot this as I switched to arrow functions
