### ISSUE TITLE
Context not being passed to data function with mixin

### ISSUE THREAD

**Issue by samtgarson** [nuxt/nuxt.js#283]
Hey. When I include a mixin in a `page` component which has a `data` function, it seems that the context isn't being passed to the actual page's `data` function. 

Is this supported? If not I'd be happy to take a crack at it. Thanks!

**Comment by alexchopin** [comment]
Hi, can you show us an example with some code snippet?

**Comment by samtgarson** [comment]
Sure. [Here is the page with the mixin being included](https://github.com/samtgarson/now-ci/blob/fc6826a9422031330a3a1c30f6b3a72c02e3a7d4/client/pages/index/settings/repos.vue)

[Here is the mixin itself](https://github.com/samtgarson/now-ci/blob/fc6826a9422031330a3a1c30f6b3a72c02e3a7d4/client/lib/paginated.js)

I hope this is not too hidden by all the other code. It seems that the `{ store }` statement is blowing up as the `data()` function is not receiving the context.

[This seems to be where the data gets merged in Vue](https://github.com/vuejs/vue/blob/769c4dc2032251323c8f61ad8eba2c26c615a618/src/core/util/options.js#L88), I'm not familiar enough with how Nuxt works to know where the context gets injected but it doesn't seem to be injected here (this `.call` is the direct parent of the error being raised

**Comment by Ca4tkin** [comment]
Hi! I've got the same problem: if I add a plugin with mixin the context in middleware and data function can't be found.

**Comment by alexchopin** [comment]
Hi, yes this is due to the data() method which is rewritten by Nuxt to be async.
We are currently working on a way to create a asyncData method to avoid this issue.

**Comment by samtgarson** [comment]
I think it's worth documenting that mixins using the `data` function won't work with Next then?
