### ISSUE TITLE
Why favicons are loaded on every request?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2830]
Hello. I am using favicons and code snippets generated by https://realfavicongenerator.net

I have this in `nuxt.config`

```js
{ rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' },
{ rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' },
```
And in result I see them loaded in DevTools on every route on the page.

**Comment by iamdubx** [comment]
Is this things related? https://github.com/nuxt/nuxt.js/issues/239

**Comment by Atinux** [comment]
It is @iamdubx 

It's Chrome which requests favicon.ico every time, I suggest to also add a `favicon.ico` in your `static/` directory :)
