### ISSUE TITLE
Edit babel config

### ISSUE THREAD

**Issue by gridsystem** [nuxt/nuxt.js#2832]
I need to change the `targets` property of the babel settings. Can anyone please suggest how I would do this with the abstracted webpack setup?

Cheers!

**Comment by Atinux** [comment]
Hi @gridsystem 

Take a look at https://nuxtjs.org/api/configuration-build#babel

You may you to look also at https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/builder.js#L190

So you can do in your `nuxt.config.js`:

```
module.exports = {
  build: {
    babel: {
      presets({ isServer }) {
        return [
          ['vue-app', { targets: isServer ? { node: '8.0.0' } : { browsers: ['last 2 versions'] } }]
        ]
      }
    }
  }
}
```
