### ISSUE TITLE
Make layout transitions behave more like page transitions (definition in layout files, function)

### ISSUE THREAD

**Issue by chasebank** [nuxt/nuxt.js#2833]
Right now page transitions can either be defined globally in the config, or individually in page components. The latter enables two huge features:

- Multiple transitions for different pages
- Access to the Vuex store for more conditional transitions

Layout transitions, however, can only be defined globally in nuxt.config, which limits us to only one transition, and no access to the Vuex store.

**Secondly**, the page transition property can be a function that conveniently gives us access to the to/from of route changes. This would also be useful in layout transitions.

Tagging @homerjam since you implemented layout transitions 👍

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2455">#c2455</a>)</em></sub></div>

**Comment by homerjam** [comment]
Agreed. This would be a nice feature.

Is there a way round this maybe? Can you use a factory function in nuxt config to define transitions per layout (not ideal obviously)?

A good start might be to create a failing test/example.

Right now my priority is to get child transitions working as expected I'm afraid! (#1737)

**Comment by chasebank** [comment]
Right! I know the current implementation is a WIP. Just getting the discussion rolling in the mean time.

As I keep poking and prodding at Nuxt and learning the ins and outs, perhaps I'll be of more use eventually. I'll also take a closer look at your original PR for this.

**Comment by galvez** [comment]
@Atinux has there been any advancements with this?
