### ISSUE TITLE
 Vue.js not detected on browser

### ISSUE THREAD

**Issue by ElJere** [nuxt/nuxt.js#2836]
Hi, I'm developping a website which works normally. But when I try to open vue-devtools, it remains empty. Vue-devtools icon says "Vue.js not detected", however, vue-devtools tab is available and says "Ready. Detected Vue 2.5.13", but doesn't show any component nor store or event.

I read some posts and threads about devtools not working with minified versions of Vuejs or with "File://" protocol, but I'm unable to fix this.

I'm on Nuxt 1.3.0, Vue-devtools 4.1.3, Firefox 58.0.2 or Chrome 64.0.3282.140 (neither works). I launch the site with `npm run dev` (ie. `nuxt`)...

Does someone could help ? Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2466">#c2466</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hi @ElJere 
Could you provide a reproduction repo? What have you tried this far?

**Comment by JRobber** [comment]
I had this issue, found I had to hit refresh in the Vue DevTools to get them to connect.

**Comment by tomexx** [comment]
I have the same issue, Vue is not available in Chrome Dev Tools (using sample project, created by nuxt cli)

**Comment by pi0** [comment]
I can confirm this bug usually happens with nuxt 2 too 🙄

**Comment by thomasdominic** [comment]
I had the same issue :/

**Comment by perimetral** [comment]
i have one too =(

**Comment by domsammut** [comment]
I ran into the same problem. Ended up updating Google Chrome to resolve the issue. Firefox was my temporary debugger before deciding to investigate Chrome further.

**Comment by Atinux** [comment]
Closing, please re-open with https://cmty.app/nuxt/issues/new as bug report if it still happens.
