### ISSUE TITLE
Importing nuxt inside jest logs Vue.productionTip to console

### ISSUE THREAD

**Issue by timwis** [nuxt/nuxt.js#2837]
Hi folks, I've just added nuxt to my koa app, and I noticed an impact on my api test suite. It seems that _solely by importing nuxt_, Vue's production tip is logged to the console.

Below is an isolated reproduction of the issue, and you can [download it here](https://github.com/timwis/repro-nuxt-import).

```javascript
const { Nuxt } = require('nuxt')

it('logs vue production tip', () => {
  console.log('done')
})
```
(note that it doesn't actually render anything)
```
npm test

 PASS  ./test.js
  ✓ logs vue production tip (1ms)

  console.info node_modules/vue/dist/vue.runtime.common.js:7913
    You are running Vue in development mode.
    Make sure to turn on production mode when deploying for production.
    See more tips at https://vuejs.org/guide/deployment.html

  console.log test.js:4
    done

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.429s
Ran all test suites.
```
Any idea what's going on here?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2462">#c2462</a>)</em></sub></div>

**Comment by paulgv** [comment]
Make sure your tests are running in production mode. You can do this by setting the NODE_ENV variable in your scripts:

```json
{
  "scripts": {
    "test": "NODE_ENV=production jest"
  },
}
```

Or even by setting it directly in your test file:
```js
process.env.NODE_ENV = 'production'

const { Nuxt } = require('nuxt')

it('logs vue production tip', () => {
  console.log('done')
})
```

**Comment by timwis** [comment]
Thanks, but that's a problem for 2 reasons:
1. My tests depend on NODE_ENV being test to test authenticated routes -- a typical use case of NODE_ENV
2. More importantly, why does it matter? Importing Nuxt should instantiate Vue, should it?

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
