### ISSUE TITLE
Simulating session storage on login

### ISSUE THREAD

**Issue by boicott** [nuxt/nuxt.js#2838]
A newbie trying hard with nuxtjs  here:)

I made an app with nuxtjs with login system via json api (without clientID or cookie) typical PHP browser session. First, login it's fine, it's ok, BUT when reload... well, you know, no login.

I have read all the related issues, many similar but I have not just left the mental loop about this. I followed the example of auth routes and my  'store / index.js' is exactly the one in the example.

P.D: No problem interacting with $ store.state.authUser in components, pages, etc .. until reload is done.

some help?

My store/index.js

```
import axios from 'axios'

export const state = () => ({
  authUser: null,
})

export const mutations = {
  SET_USER: function (state, user) {
    state.authUser = user
  }
}

export const actions = {
  nuxtServerInit ({ commit }, { req }) {
    if (req.session && req.session.authUser) {
      commit('SET_USER, req.session.authUser')
    }
  },
  async login ({ commit }, { username, password, submit }) {
    try {
      const params = new URLSearchParams()
      params.append('username', username)
      params.append('password', password)
      params.append('submit', submit)
      const { data } = await axios.post('https://www.xxxxxxxx.com/e/account/login', params, { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } })
        commit('SET_USER', data)
    } catch (error) {
      if (error.response && error.response.status === 401) {
        throw new Error('Bad Credentials')
      }
      throw error
    }
  }
```

**Comment by microcipcip** [comment]
You need 3 tilde key to format the code.

Where is `req.session` coming from? How are you getting the session from php? Don't you have a session cookie set or something like that? I have found [this stackoverflow question](https://stackoverflow.com/a/24303059/974107) that maybe is of some help?

**Comment by boicott** [comment]
I followed this example: 
[auth_routes](https://nuxtjs.org/examples/auth-routes/)
My backend doesn't have client_id or some type of cookie, only gets the session by browser after successful login via API.

**Comment by boicott** [comment]
Perhaps I have misled commenting on the php session (a client-side normal use) and now I try to replicate the same operation from nuxtjs, keep the user's session as in that example of auth-routes that I have replicated but that does not work as I expect .

i can't obtain a cookie from the backend right now, I have no control over it

**Comment by microcipcip** [comment]
To me the problem seems to be that the cookie HAS to come from the server. You can set a cookie from client side, but then it would be very very dangerous because smart users will be able to access the website. 

The main problem here is that you don't have access to the backend I think
