### ISSUE TITLE
Firebase not work

### ISSUE THREAD

**Issue by reskwer** [nuxt/nuxt.js#2839]
why on pure lua everything works and in NEXT-no. maybe there are some ways to stabilize a pressing issue and not one I encounter

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2465">#c2465</a>)</em></sub></div>

**Comment by Atinux** [comment]
CC @posva

**Comment by posva** [comment]
I'm sorry I don't understand anything 😅
