### ISSUE TITLE
problem with running the app with nuxt

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#284]
Hi!

When I run the [async-data](https://nuxtjs.org/examples/async-data/) as ```npm run dev``` everything works fine. But when I run it as ```nuxt``` I get an error:
```
Vue.js error

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (__vue_ssr_bundle__:1056:18)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.module.exports.Object.defineProperty.value (__vue_ssr_bundle__:1909:64)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:3427:3)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
```

The same problem is with building the app. I can build it with ```npm run build``` but not with ```nuxt build```. It gives:
```
ERROR in c:/Users/art/AppData/Roaming/npm/~/nuxt/~/extract-text-webpack-plugin/loader.js?{"omit":0,"remove":true}!C:/Users/art/AppData/Roaming/npm/~/nuxt/~/css-loader!c:/Users/art/AppData/Roaming/npm/~/nuxt/~/vue-loader/lib/style-rewriter.js?id=data-v-0ded5cf2&scoped=true!c:/Users/art/AppData/Roaming/npm/~/nuxt/~/vue-loader/lib/selector.js?type=styles&index=0!./.nuxt/components/nuxt-error.vue
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (c:\Users\art\AppData\Roaming\npm\node_modules\nuxt\node_modules\extract-text-webpack-plugin\loader.js:26:9)
 @ ./.nuxt/components/nuxt-error.vue 3:0-446
 @ C:/Users/art/AppData/Roaming/npm/~/nuxt/~/babel-loader/lib?{"plugins":["transform-async-to-generator","transform-runtime"],"presets":[["es2015",{"modules":false}],"stage-2"],"cacheDirectory":false}!c:/Users/art/AppData/Roaming/npm/~/nuxt/~/vue-loader/lib/selector.js?type=script&index=0!./.nuxt/components/nuxt.vue
 @ ./.nuxt/components/nuxt.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
```

Windows 10, npm 3.10.10, node 6.9.5

Some other person raport this problem on the chat today too.
I am not sure if it is a bug or not.

**Comment by alexchopin** [comment]
It's not a bug, we don't add axios as a global dependencies for the build. 
You need to install it and build again before launch an example.

**Comment by rof20004** [comment]
Sorry, but I do not understand what this means:

"You need to install it and build again before launch an example"

I think that is to yarn add axios and nuxt again?

I am with this issue and until now I can not solve

**Comment by alexchopin** [comment]
```
yarn add axios
npm run build
npm start
```

**Comment by rof20004** [comment]
.Then using the command nuxt not working?

If I use nuxt start, to run my own server, then will not working?

Thanks for answer :D

**Comment by davision** [comment]
I also have such problem. If I run `nuxt` to start the project, I got an error of missing modules. If I run `npm run dev`, everything works fine.

**Comment by askhat** [comment]
@alexchopin 

> You need to install it and build again before launch an example.

Would you be so kind to elaborate more on this?

**Comment by qm3ster** [comment]
@askhat 
Install it: `yarn add axios` or `npm i -S axios`
Build it and run it in production: `yarn nuxt build` and then `yarn nuxt start`
Run in dev (also builds automatically): `yarn nuxt`
