### ISSUE TITLE
DevTools failed to parse SourceMap when having custom routes

### ISSUE THREAD

**Issue by adi-zz** [nuxt/nuxt.js#2840]
I need to have routes like this: a fixed/hardcoded segment followed by any number of free-form segments (like: `/posts-from/2018/10/05`).

So I

- generated a project based on [nuxt-community/starter-template](https://github.com/nuxt-community/starter-template)
- installed stylus and added a .styl file
- added a custom route (via [example](https://github.com/vuejs/vue-router/blob/dev/examples/route-matching/app.js#L22))
`nuxt.config.js
  router: {
    extendRoutes (routes, resolve) {
      routes.push({
        name: 'custom',
        path: '/custom/*',
        component: resolve(__dirname, 'pages/index.vue')
      })
    }
  }
`
- all my changes are [here](https://github.com/adi-zz/nuxt-variable-url-segments-sourcemap-issue/commit/4c4e4509e9a8fbbb13b3d9641fbcf74eba8715df)

Now on dev mode (`yarn run dev`) I can open `/custom/1/2/3` - which is what I want.
But, when I open that page, Chrome logs: `DevTools failed to parse SourceMap: http://localhost:3000/custom/1/2/assets/style/app.css.map`

Am I doing something wrong or there is an issue with Nuxt?
Thanks

(Also, but this seems to be a different issue, when I open the root page (`/`), the server logs: `{ statusCode: 404,
  path: '/assets/style/app.css.map',
  message: 'This page could not be found' }`.)

**Comment by adi-zz** [comment]
The workaround that I found to not see this warning message anymore, is adding a [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware/) which sends 404 for a css sourcemap request.

```
// nuxt.config.js
module.exports = {
  // ...
  serverMiddleware: ['~/server_middleware/404-for-sourcemaps'],
}

```

```
// server_middleware/404-for-sourcemaps.js
module.exports  = function 404ForSourcemaps(req, res, next) {
  if (/\/custom\.*\/.+\.css\.map$/.test(req.url)) {
    res.statusCode    = 404
    res.statusMessage = 'Not Found'
    res.end()
  } else {
    next()
  }
}

```

**Comment by dohomi** [comment]
same error happens for me. I do a 404 as well

**Comment by CarlosCondor** [comment]
Same problem here....
