### ISSUE TITLE
Unable to Lazy Load Functional Component

### ISSUE THREAD

**Issue by mouafa** [nuxt/nuxt.js#2841]
Greeting,

I was trying to lazy load some functional components, and I encountered this #2565 

anyway, I disabled `optimizeSSR`in order to get over the `_vm._ssrNode` error but I encountered the `Cannot read property 'Ctor' of undefined`

![ctor](https://user-images.githubusercontent.com/1658799/36321193-43ce92ec-1349-11e8-9ef4-304bf7c1ced5.png)

And the Error was disappearing if we make the component as a normal one or we stop lazy loading it.

PS: most of our functional components are SVG wrapped icons, so it makes a good sense to set them as functional one and lazyload them.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2467">#c2467</a>)</em></sub></div>

**Comment by manniL** [comment]
Should be fixed in latest version.
