### ISSUE TITLE
How can i build lodash to vendor with lodash-webpack-plugin & babel-plugin-lodash

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt/nuxt.js#2846]
Hi,

I would like to move my lodash scripts to vendor when im using them.

When i define it into my vendor section of config file it loads whole lodash to it.

```javascript
    vendor: [
      'lodash'
    ]
```

My build part is like this.

```javascript
build: {
    babel: {
      plugins: ['lodash'],
      presets: ['vue-app']
    },
    plugins: [
      new LodashModuleReplacementPlugin()
    ]
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2472">#c2472</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
