### ISSUE TITLE
Multiple error layouts

### ISSUE THREAD

**Issue by BorisTB** [nuxt/nuxt.js#2847]
Hi,

I can't find a way to use multiple error layouts. Is it even possible?

On error 403 I want to show login page, not just an error with a text. Or is there any way to change page without changing URL?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2473">#c2473</a>)</em></sub></div>

**Comment by chasebank** [comment]
You can probably do a redirect in the main error layout as an easy fix

```
mounted() {
  if (this.error.statusCode === 403) {
    this.$router.push({ name: 'login'})
  }
}
```

But I'm sure there are better ways

**Comment by derekshull** [comment]
I'm wondering if multiple error layouts is possible too.  What's the official way?  Or is @chasebank's answer the best way right now?

**Comment by mootari** [comment]
> I'm wondering if multiple error layouts is possible too. What's the official way?

The official way appears to be to react to different error codes directly in the error layout: https://nuxtjs.org/guide/views/#error-page

**Comment by manniL** [comment]
Instead of multiple error layouts, you could create `error-components` and display them depending on the error/status code.
