### ISSUE TITLE
Using hiq postcss library with nuxt

### ISSUE THREAD

**Issue by callumflack** [nuxt/nuxt.js#2849]
I have not followed the contributing guidelines. Instead I forked @Atinux's [nuxt-postcss-global glitch](https://glitch.com/edit/#!/nuxt-postcss-global?path=:1:0) and tried to add @jonathanharrell 's [hiq](https://github.com/jonathanharrell/hiq).

https://glitch.com/edit/#!/hiq-with-nuxt2

I don't understand how @Atinux 's extend config for `postcss-loader` works. 

Nail me for that, sure, but I'd love if Nuxt was able to offer easier ways to use the full spectrum of what postcss offers. There are [two conflicting](https://nuxtjs.org/faq/postcss-plugins) [guides](https://nuxtjs.org/api/configuration-build#postcss) to adding postcss plugins, neither of which, for example, enable `postcss-mixins`. That's another issue but it does show that while automatically enabling `cssnext` is terrific (thanks!), there are further ways to enhance nuxt with postcss, such as the ability to integrate hiQ easily.

If anyone can point me to a fundamental mistake here, without requiring me to study the webpack (that's what nuxt is for right?), that'd be 🎉.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2475">#c2475</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
