### ISSUE TITLE
nuxt/starter run return error

### ISSUE THREAD

**Issue by LANSELOT** [nuxt/nuxt.js#285]
I use nuxt/starter
**nuxt.config.js**
```
extend (config, { isClient }) {
      if (isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        })
      }
    }

```
**npm run dev** return error
\nuxt.config.js:32
    extend (config, { isClient }) {
                    ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by alexchopin** [comment]
Hi,
Can you explain more about your issue? 
Versions of node are using, OS, etc
Thanks

**Comment by LANSELOT** [comment]
node: v4.5.0
npm: 4.0.3
OS: Windows 10

**Comment by Atinux** [comment]
Hi @LANSELOT 

it's fixed, it's due to node 4 which does not support the ES6 syntax in arguments `{ isClient }`.

You can install it again it should work like a charm :)
