### ISSUE TITLE
docker-compose environment vars

### ISSUE THREAD

**Issue by ralphchristianeclipse** [nuxt/nuxt.js#2851]
I can't pass variables through nuxt environment variables using docker-compose env variables

i'm trying to pass my API_HOST like this in docker
```yaml
env:
  API_HOST: localhost:8081
```

then in nuxt.config.js i've done this

```js
env: {
   API_HOST: process.env.API_HOST || "localhost"
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2477">#c2477</a>)</em></sub></div>

**Comment by gijo-varghese** [comment]
+1

**Comment by gijo-varghese** [comment]
@ralphchristianeclipse I got the same problem. Did you get any solutions?

**Comment by batFormat** [comment]
+1

**Comment by makoso** [comment]
+1

**Comment by aldarund** [comment]
@makoso maybe u are building app on host and then launch it on docker? Because env vars will be embed at the build time, not a runtime.

**Comment by makoso** [comment]
@aldarund im building app in dockerfilie, and i when i has env_file set it doesn't compile good variables in nuxt, i find fix if we have one instance with one .env file, we can add arguments to build property in docker-compose then after push to registry we can see correct env variables inside nuxt, but when i get second instance with another env file it make non sense, i need to rebuild app in docker entrypoint, it get me 5min downtime of my app :(

**Comment by aldarund** [comment]
@makoso well, that's exactly what I said, isn't it? Env vars embed at build time, so if you need  another env vars you need to rebuild.
Other option would be to use nuxt env module, which allow to use runtime env cars rather than build time

https://github.com/samtgarson/nuxt-env

**Comment by aldarund** [comment]
I have checked and verified that all works fine and as expected with nuxt-edge.
environment variables from docker compose accessible in nuxt.
Keep in mind that process.env  set at build time.
