### ISSUE TITLE
Long dynamic url paths

### ISSUE THREAD

**Issue by titus7lite** [nuxt/nuxt.js#2852]
Hi,
I have a question regarding long dynamic url slugs and cant seem to find any examples. In an example where route paths are created dynamically and stored on tha database, e.g /cars/models/types/interior/wheel/color etc.. where the route logic is known only after quering the database and can be changed at any point simply because the person that created the before mentioned slug wishes it to change for seo reasons to something entirely different and as a result cannot be a static route nor can it be a specific regex route as i have seen in examples e.g '/:slug/:id' etc... 

Is this something can be done with nuxt along with some extra module without anything hackish? Even more so does one actually choose to use a SSR logic in such a case?
In case anybody wondering why i would need that, think of an ecommerce that allows links to be written in any format for SEO and management as supported by a number of ecommerce platforms.

Thank you.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2478">#c2478</a>)</em></sub></div>

**Comment by adi-zz** [comment]
I reported an issue (#2840) and to describe it, I created this [small project](https://github.com/adi-zz/nuxt-variable-url-segments-sourcemap-issue). If I understand correctly, it may be an example for what you are looking for. In the above project, if you want to display a long dynamic url, use this:
`<router-link :to="{name: 'custom', params: {0: ['any', 'number', 'of', 'segments'].join('/')}}">/custom/any/number/of/segments</router-link>
`

**Comment by titus7lite** [comment]
Thanks for the reply,

Well something custom would be helpful but the issue here, if i understood correctly, is that you allow any kind of route without validation which i need, for example i could have 1000 of dynamic routes created on the fly with multiple paths (e.g. /somerandomcategory/someothercategory/productname or even more complex), like creating products in a eshop, you are also routing everything to a specific vue file which again in my case may easily be different pages depending the path and type of page being displayed.

All in all i am trying to achieve something along the following lines: have new routes dynamically created and/or deleted/changed and be validated for correct page template display which again may change, so must be treated as template types.

Hope to get some clarification on this...

**Comment by awronski** [comment]
How do you want to check if the segments are valid?
What is the valid path?

Do you want to only check the order of the segments in the path or it can be random?
Do you want to check segments names against the database?
Etc

@titus7lite I think you have to write your own function for [validator](https://nuxtjs.org/api/pages-validate/) the check this all conditions.

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
