### ISSUE TITLE
Generate single styles and scripts outside of _nuxt folder

### ISSUE THREAD

**Issue by vinjegaard** [nuxt/nuxt.js#2853]
Is it possible to generate scripts and stylesheets directly in /dist folder? I need to generate all script files to a single file, the same with css (eg dist/app.js + dist/app.css).

I've tried disabling code splitting with 
`
build: {
        plugins: [
            new webpack.optimize.LimitChunkCountPlugin({
                maxChunks: 1
            })
        ],...
`
but this leads to an error when serving the application ` Error while initializing app TypeError: __webpack_require__.e is not a function`.

Is it possible to disable code splitting and generate single files for scripts and styles and generate them directly in /dist, and not in dist/_nuxt as default behavior.

I have created a node script that move the files out from dist/_nuxt, it then loops through all .html, .js and .css files and replaces paths eg: `from: /\/_nuxt\/Styles/g, to: '/Styles'`. This works with styling but javascript doesn't work, I'm not sure why. This is by far the best solution, it would be much better to be able to get Nuxt to generate these files outside of _nuxt folder. But if this is not possible I would be thankful to any suggestions how to get this to work.

Thanks!

**Comment by mysticmind** [comment]
Try to add the logic within `extend` and wrap the plugin with a check for `!isDev` as below
```
extend (config, { isDev, isClient }) {
      if (!isDev) {
        config.plugins.push(
          new webpack.optimize.LimitChunkCountPlugin({
            maxChunks: 1
          })
        )
      }
    }
```

**Comment by IlyaSemenov** [comment]
Your issue covers two unrelated issues:

1) Don't use `_nuxt` folder. You can achieve that by simply overriding `publicPath`:

```js
// nuxt.config.js
module.exports = {
	build: {
		publicPath: '/',
	},
}
```

2) Disable code splitting. This was indeed broken in the recent release. There is a separate ticket discussing that problem - #2870, your is therefore duplicate. In the meanwhile as a temporary workaround you can set `maxChunks: 4` - this will generate manifest.js, vendor.js, app.js (with scripts for all pages) and layout.js.

**Comment by Atinux** [comment]
I will keep only one open since it's the same issue, see #2870
