### ISSUE TITLE
asyncData not called after vue-router hook beforeRouteEnter is called

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt.js#2856]
In order to have a completely separate Nuxt page for search versus our homepage, we implemented a redirect if the query string parameter `q` is present. We use vue-router’s [`beforeRouteEnter`](https://router.vuejs.org/en/advanced/navigation-guards.html) hook to implement the redirect:

```js
  beforeRouteEnter (to, from, next) {
    if (typeof to.query.q !== 'undefined') {
      next({ name: 'domain', query: to.query, replace: true })
      return
    }
    next()
  }
```

Everything works great, except, *on the server*, `asyncData` isn’t called by the `domain` route. It otherwise loads and renders correctly, sans `asyncData`.

**Comment by ydnar** [comment]
Dug into it a bit further, and it turns out `asyncData` is called for the *first* component, but not the component (page) that ends up being rendered.

**Comment by ydnar** [comment]
Update 2: I tried replacing the component (page)-level `beforeRouteEnter` hook with a global `router.beforeEach` hook. The same thing happened (`asyncData` on the first component was called).

**Comment by Atinux** [comment]
Could you instead use a `middleware` inside your page (it can be a function) and use `redirect` instead? `router.beforeEach` does not work well on server-side.

**Comment by ydnar** [comment]
The source and destination URLs differ only by query string. The router will resolve the first page after the redirect.

**Comment by Atinux** [comment]
I see, so I suggest you to use instead one page but 2 Views components inside and use `<component :is="viewComponent"/>` inside your template depending if the user is searching or no.

**Comment by husayt** [comment]
Is this related to #2737 ?

> After some debugging it turned out that asyncData gets called once again on params update, but new result from asyncData isn't persisted in data later.

**Comment by comfuture** [comment]
I've tried to solve this problem like this:

Both `asyncData` and `beforeRouteEnter` can't access component instance, so I created a mixin that keep and restore the previous query in module scope by path.
https://gist.github.com/comfuture/2d40d2cc1d659614ec982a7613e0fe38

I think this issue is **critical**. @ydnar Please refer to this mixin to solve your problem.
