### ISSUE TITLE
How multiple request API in nuxtServerInit?

### ISSUE THREAD

**Issue by fathan** [nuxt/nuxt.js#2857]
i use axios for HTTP Request, but i confused for calling API mulltiple with nuxtServerInit. thx

**Comment by paulgv** [comment]
What have you tried so far? If you're using axios-module, you can easily get axios instance in nuxtServerInit, then performing a request is pretty straightforward, it should look like this:

```js
actions: {
  nuxtServerInit ({ commit }, { app }) {
    const response = await app.$axios.get('/something')
    commit('SET_DATA', response.data)
  }
}
```

**Comment by fathan** [comment]
thank you @paulgv , its work for me.
