### ISSUE TITLE
Re-load clients after pushing/deploying changes to the server

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#286]
Hey Guys,

I'd like to open a feature request about `NUXT` being able to recognize changes in `JS` or `CSS` files after a deploy to the server. It would be great if `NUXT` could work similar like `MeteorJS` to recognize changes and force connected client browsers to re-retch / reload the client source and display the changes immediately.

Cheers

**Comment by Atinux** [comment]
Hi @dohomi 

We won't implement such a feature but it could be a plugin for nuxt.js in the future.

Thank you for this idea!

**Comment by dohomi** [comment]
@Atinux would be good if you could track this feature inside of the backlog, as soon plugins are available I think its necessary feature - for sure in the context of a PWA. Thanks for taking it into account

**Comment by Atinux** [comment]
it's added @dohomi :)

**Comment by cawa-93** [comment]
And how do you do it now? How to stop a running nuxt server on a remote machine and start it again, after changing the files?

**Comment by Atinux** [comment]
You can use automatic deployments like now.sh or Heroku @cawa-93 

They re-deploy when a git push is made.

**Comment by littlexiang** [comment]
PM2 with option {watch: true} will do that
