### ISSUE TITLE
Content not rendered

### ISSUE THREAD

**Issue by Vincebe** [nuxt/nuxt.js#2864]
Hello,

I use [markdown-it](https://github.com/nuxt-community/modules/tree/master/packages/markdownit) module to parse `.md` files, with this component to convert internal links :

```html
<template>
  <div v-html="content">
  </div>
</template>

<script>
export default {
  props: ['content'],
  mounted() {
    this.addListeners()
  },
  beforeDestroy() {
    this.removeListeners()
  },
  watch: {
    'content': 'contentUpdated'
  },
  methods: {
    navigate(event) {
      const href = event.target.getAttribute('href')
      if (href && href[0] === '/') {
        event.preventDefault()
        this.$router.push(href)
      }
    },
    contentUpdated() {
      this.removeListeners()
      this.$nextTick(() => {
        this.addListeners()
      })
    },
    addListeners() {
      this._links = this.$el.getElementsByTagName('a')
      for (let i = 0; i < this._links.length; i++) {
        this._links[i].addEventListener('click', this.navigate, false)
      }
    },
    removeListeners() {
      for (let i = 0; i < this._links.length; i++) {
        this._links[i].removeEventListener('click', this.navigate, false)
      }
      this._links = []
    }
  }
}
</script>
```

It works fine but the content of the `.md` is not html rendered with `nuxt generate`, but instead stored in the js...

Any idea?

Thanks!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2488">#c2488</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Can you post the outer component that supplies "content" prop to this one?

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
