### ISSUE TITLE
routes should not be called on internal files

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#2865]
Hi
I extend my routes to have kind of a catch all for my custom render of index.vue:
```javascript
router:{
extendRoutes (routes, resolve) {
      routes.push({
        name: 'article',
        path: '*',
        component: resolve(__dirname, 'src/pages/index.vue')
      })
    }
}
```
On SSR I found out that the index.vue is getting called on paths it should be ignored:
`robots.txt, styles.css.map` and several more. How is it possible to extend routes and only match the path based on real strings/paths or how can I ignore specific route params/paths inside of the index.vue component?
I tried:
```
path:'/:foo*'
```
But it still matches any path

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2489">#c2489</a>)</em></sub></div>

**Comment by galvez** [comment]
@dohomi do `console.log(routes)` and you'll see all pregenerated routes are accessible and tweakable. You can even do `routes.splice(0, routes.length, ...[new routes])` and replace them altogether.
