### ISSUE TITLE
Auth_Routes example (source code version)

### ISSUE THREAD

**Issue by boicott** [nuxt/nuxt.js#2866]
I am working with the example of [ auth routes](https://nuxtjs.org/examples/auth-routes/) to create a persistent login system but every time I try to include the call to the api to get user data to fill "req.session.authUser" in "/api/index.js" doesn't work. The store doesn't recognize the route.

¿Someone's have a example of this but working with a api call?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2490">#c2490</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hi @boicott, what do you mean by "The store doesn't recognize the route"? Do you have an error or some code you could share so we can reproduce the issue?

**Comment by boicott** [comment]
Yes, the code is the same as the one in the example. I only changed the if conditional for a call to my api to fill "req.session.authUser" in '/API/index.js'  on this block. 
```
// Add POST - /api/login
router.post('/login', (req, res) => {
  if (req.body.username === 'demo' && req.body.password === 'demo') {
    req.session.authUser = { username: 'demo' }
    return res.json({ username: 'demo' })
  }
  res.status(401).json({ message: 'Bad credentials' })
})
```

**Comment by paulgv** [comment]
This should work assuming the endpoint `https://www.xxxxx.com/e/account/login` actually exists and returns something in `data.user.username`. Did you change anything else in the original example? Also, make sure your Node version is >= 8.

**Comment by boicott** [comment]
Yes, the endpoint exists and yes returns the data of the user. I don't change anything else from the example and Node is >= 8

**Comment by boicott** [comment]
I have recreated as much as possible my example using the real api:

https://lewd-shark.glitch.me

**Comment by paulgv** [comment]
@boicott I'm getting a gateway timeout when trying to access your glitch.me :/

**Comment by boicott** [comment]
Edit! :/

**Comment by paulgv** [comment]
Thanks for the repro @boicott !
I pulled the project and had to make some minor changes to make it work:
- require axios in the ES5 way on the server-side
- catch axios' post error to help debug
- return plain data object when axios' request succeeds (helps debugging as well)

Here's the code:

```js
// api/index.js

const axios = require('axios')
const express = require('express')

// Create express router
const router = express.Router()

// Transform req & res to have the same API as express
// So we can use res.status() & res.json()
var app = express()
router.use((req, res, next) => {
  Object.setPrototypeOf(req, app.request)
  Object.setPrototypeOf(res, app.response)
  req.res = res
  res.req = req
  next()
})

// Add POST - /api/login
router.post('/login', (req, res) => {
  axios.post('https://www.yourapi.com/e/account/login', { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } })
  .then((data) => {
    return res.json({ data: data.data  })
  })
  .catch((error) => {
    return res.json({ error: error  })
  })
})

// Add POST - /api/logout
router.post('/logout', (req, res) => {
  delete req.session.authUser
  res.json({ ok: true })
})

// Export the server middleware
module.exports = {
  path: '/api',
  handler: router
}

```

Give it a try and adapt it so you get actual user data, hope it works!

**Comment by boicott** [comment]
Yes! THANK YOU! I see what happened. Now, i will try how can i  pass my login params to this call!
