### ISSUE TITLE
HMR stops working (ERR_CONNECTION_RESET), requires server restart every time

### ISSUE THREAD

**Issue by sergiocastrovale** [nuxt/nuxt.js#2867]
I'm having a very weird problem. I've tried everything I could think of to no avail, hope you guys can help me out.

I'm using the Nuxt.js + Express template, and things work nicely but my server is randomly disconnected after some time (see screenshot). I tried disabling any firewall/antivirus (Windows 10), removed every configuration from my `hosts` file but it keeps happening ...

![screenshot_2](https://user-images.githubusercontent.com/8822036/36437303-7ee27034-165e-11e8-9506-fec7ca627e68.png)

Every time the server disconnects I have to rebuild the project, and it's super painful to work like this.

package.json:

```
  "dependencies": {
    "@nuxtjs/auth": "^4.0.0-rc.3",
    "@nuxtjs/axios": "^4.5.2",
    "@nuxtjs/toast": "^2.3.3",
    "@nuxtjs/vuetify": "latest",
    "axios": "^0.16.2",
    "babel-polyfill": "^6.26.0",
    "bcryptjs": "^1.1.0",
    "body-parser": "^1.18.2",
    "cross-env": "^5.0.1",
    "express": "^4.15.3",
    "faker": "^4.1.0",
    "knex": "^0.14.4",
    "mysql": "^2.15.0",
    "nuxt": "^1.3.0",
    "objection": "^1.0.0",
    "source-map-support": "^0.4.15",
    "vee-validate": "^2.0.4",
    "vue-js-modal": "^1.3.10",
    "vue-moment": "^2.2.0",
    "vue-truncate-filter": "^1.1.7"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-preset-stage-1": "^6.24.1",
    "backpack-core": "^0.5.0",
    "eslint": "^4.18.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6"
  }
```

Any help would be appreciated.

**Comment by cliffrowley** [comment]
I am having the same problem.  I'm using Nuxt with SSR through Express, and it kills my whole server so I'm hoping it's just a HMR issue.

**Comment by sergiocastrovale** [comment]
After a *lot* of hours, I think I know what the problem is (still testing it out - I still don't believe this is the problem). My default layout for errors had a `<nuxt/>` call where it shouldn't (see https://nuxtjs.org/guide/views/). Maybe that will help @cliffrowley

**Comment by cliffrowley** [comment]
@sergiocastrovale seems I managed to solve this my end by deleting node_modules and reinstalling - hasn't crashed once since.

**Comment by sergiocastrovale** [comment]
Cool @cliffrowley - I tried that as well but my issue was definitely having set `<nuxt/>` inside the error template. So far I haven't had any issues.
