### ISSUE TITLE
404 ResourceNotFound (ttf, woff, svg)

### ISSUE THREAD

**Issue by Elfayer** [nuxt/nuxt.js#2869]
I'm using [ElemeFE/Element](https://github.com/ElemeFE/element), I set it up in a plugin as follow:

```js
import Vue from 'vue';
import ElementUI from 'element-ui';
import lang from 'element-ui/lib/locale/lang/en';
import locale from 'element-ui/lib/locale';
import '../theme/index.css';

locale.use(lang);
Vue.use(ElementUI);
```

I receive network errors:
![image](https://user-images.githubusercontent.com/15869149/36467584-4d05d5b2-171a-11e8-87e2-bd7aa1250567.png)

With console errors:
`GET http://localhost:3000/_nuxt/fonts%0Element-icons.6f0a763.ttf net::ERR_ABORTED`

Currently under **Nuxt v1.3.0**
I think the error might come from nuxt webpack config.

---

**File `_nuxt/vendor.js` contains:**

```js
/***/ "./node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf":
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__.p + "fonts\\element-icons.6f0a763.ttf";

/***/ }),
```

**File `_nuxt/app.js` contains:**
```js
/***/ "./theme/fonts/element-icons.ttf?t=1510834658947":
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__.p + "fonts\\element-icons.6f0a763.ttf";

/***/ }),
```

Does the problem come from `\\e` that turns into `%0E`?

**Comment by nerdism** [comment]
+1 same issue, windows system, importing font awesome fonts, the scss renders to 
```
@font-face {
  font-family: 'FontAwesome';
  src: url(/_nuxt/fonts\fontawesome-webfont.674f50d.eot);
  src: url(/_nuxt/fonts\fontawesome-webfont.674f50d.eot?#iefix&v=4.7.0) format("embedded-opentype"), url(/_nuxt/fonts\fontawesome-webfont.af7ae50.woff2) format("woff2"), url(/_nuxt/fonts\fontawesome-webfont.fee66e7.woff) format("woff"), url(/_nuxt/fonts\fontawesome-webfont.b06871f.ttf) format("truetype"), url(/_nuxt/img\fontawesome-webfont.912ec66.svg#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal; }

**Comment by nerdism** [comment]
ok odd, clearing out `node_modules` `build` `.nuxt` `package-lock.json` and re-installing (`npm i`) using `git-cmd` seems to have fixed the issues for me.  No idea *how* that could of fixed things.

**Comment by yoyo837** [comment]
Something related: ElemeFE/element/issues/9086
