### ISSUE TITLE
Loading vuex modules dynamically for specific pages

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#287]
Is it possible to load some store modules only for specific urls.. 

    Ex: load store/create-project store only if the url is /create-project/*

By this way we can reduce the size of the bundle if there are many pages in the app.

**Comment by Atinux** [comment]
Hi @shyamchandranmec 

It's not possible, but the store bundle is most of the time not the biggest one and should not be a problem.

**Comment by shyamchandranmec** [comment]
@Atinux  
 So here is my case. I need to include aws-sdk to upload a file. Since its an ansynchronous action I thought of putting it in the store.
I can do this in the .vue file itself but I was thinking of the possibility of adding all actions in the store. 

So in this case aws sdk will be included in the store bundle.

**Comment by Atinux** [comment]
This is where you can use code-splitting to include the library only when
an action which requires it is called.

Do you mind sharing your code so I can show you how to achieve it?

**Comment by shyamchandranmec** [comment]
@Atinux Will surely share the code. Right now I am facing issues when I include aws-sdk.. I have opened an issue for it. Right after it starts working I will share the code.
