### ISSUE TITLE
build directory versioning

### ISSUE THREAD

**Issue by bekaufman** [nuxt/nuxt.js#2872]
Hello, 

I want to be able to version my builds for production to allow the users to roll into the latest version the next time they hit the server.

I'm running in SPA mode.

I attempted to use the extend() function and added the following:

  ```
  extend(config, { isDev, isClient }) {
      config.output.publicPath = config.output.publicPath + PackageConfig.version + '/';

<!---------------------------------------- Output from build------------------------------------>
 <script type="text/javascript" src="/_nuxt/1.0.0/manifest.ac8e5401816c4825234a.js"></script><script type="text/javascript" src="/_nuxt/1.0.0/vendor.3e02baf7a0abd146e836.js"></script><script type="text/javascript" src="/_nuxt/1.0.0/app.30092b435b49783d707d.js"></script></body>
```

While it did add the path to the script files it didn't create the directory in the /dist/_nuxt/ folder.

Am I missing something?

Thanks,

Blair

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2498">#c2498</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
