### ISSUE TITLE
Vue-meta not render property title & description in SSR-mode

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#2876]
Time-to-time vue-meta render wrong title and desc on some pages in ssr-mode. Sometimes Yandex webmaster robot send to me notification that the page title has changed to default, defined in `nuxt.config.js`. The pages title defined by documented way in `head()` method. No one page not have authentication conditions.

Screenshot made in dev mode with open `view-source://` panel

![image](https://user-images.githubusercontent.com/2588730/36528432-26b708a2-17c6-11e8-901b-cf5db45c43fb.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2500">#c2500</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Can you post where you define the `head()` method?
Also, how is the app hosted? build + start mode? what's in front of it?

**Comment by ruslankonev** [comment]
@qm3ster , the `head()` method defined in pages, like in Nuxt documentation — [views#html-head](https://nuxtjs.org/guide/views#html-head):

![image](https://user-images.githubusercontent.com/2588730/37115457-3d548f4e-225c-11e8-9c0c-501cd64723bc.png)

Application hosted with Express (Nuxt as middleware) and Nginx as a proxy. Nuxt in SSR mode. The problem is just in `SSR`-render.

**Comment by aurel-tackoen** [comment]
Did you register some custom module on Vuex ?
I had the same problem, and I narrowed down to a "$store.registerModule" function for a customStore  in a plugin.
What you can do if it's the case, is do an import + export default of your customStore in a file located in the store directory of nuxt and then remove the registerModule code of the plugins.

hope its help anyway

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
