### ISSUE TITLE
Unknown custom element

### ISSUE THREAD

**Issue by umardraz** [nuxt/nuxt.js#2877]
Hello I am trying to convert my existing Vuejs app into nuxt.js.

I am using buidcons and those are working in vuejs but with nuxtjs I am getting this error

[Vue warn]: Unknown custom element: <bi> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Here is my code

```
<nuxt-link to="/newuser" @click="leftmenu" class="head">
     <bi class="budicon-cloud-download"> </bi>
</nuxt-link>
```
This is my buidcons.css file

```
@font-face {
  font-family: 'budicon-classic';
  src:  url('/static/fonts/Budicons/budicon-classic.eot?jdete2');
  src:  url('/static/fonts/Budicons/budicon-classic.eot?jdete2#iefix') format('embedded-opentype'),
    url('/static/fonts/Budicons/budicon-classic.ttf?jdete2') format('truetype'),
    url('/static/fonts/Budicons/budicon-classic.woff?jdete2') format('woff'),
    url('/static/fonts/Budicons/budicon-classic.svg?jdete2#budicon-classic') format('svg');
  font-weight: normal;
  font-style: normal;
}

bi {
  font-family: 'budicon-classic' !important;
  font-style: normal;
  font-weight: 400;
  font-variant: normal;
  text-transform: none;
  margin-right: 4px;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

Would you please help me how I can solve this

**Comment by paulgv** [comment]
Hi @umardraz, it looks like you did not register the **bi** component properly. You need to register it locally via the `components` property or globally via a plugin.

**Comment by umardraz** [comment]
Hi Thanks for your reply now I have another issue. in my previous Vuejs application i was using dialog but now in nuxt.js I am getting this error

```
{ ReferenceError: document is not defined
at i (/home/siteuptime/nuxt/node_modules/vuejs-dialog/dist/vuejs-dialog.min.js:1:25562)
at o (/home/siteuptime/nuxt/node_modules/vuejs-dialog/dist/vuejs-dialog.min.js:1:25393)
```
Would you please help how I can fix this

**Comment by paulgv** [comment]
Looks like the library/code you're using is being run on the server which doesn't have access to window or document, you need to limit the dialog initialization to the client-side only.
Have a look at Nuxt's FAQ: https://nuxtjs.org/faq/window-document-undefined

**Comment by umardraz** [comment]
Hi Thank I had fixed that with this way

`{ src: '~plugins/vue-dialog.js', ssr: false }, `
