### ISSUE TITLE
nuxt.config.ts

### ISSUE THREAD

**Issue by gbouteiller** [nuxt/nuxt.js#2878]
Hello,
I'm a typescript user and I would like to know if it would be possible to write the config file in typescript as it is possible for gulp with the use of ts-node. What I have in mind is to be able to import ts files in config to use some code in generate/routes for instance.
Thank you.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2501">#c2501</a>)</em></sub></div>

**Comment by qm3ster** [comment]
You can definitely do it in many different ways if you [use nuxt programmatically](https://nuxtjs.org/api/nuxt#using-nuxt-js-programmatically), but you may also want to try `typescript-require`.
This will probably become a native feature at some point.

**Comment by OniVe** [comment]
1. Install dependencies in the project
   ```cmd
   > yarn add ts-node typescript -D
   ```
1. In the file `package.json` replace to this:
   ```json
   {
     ...
     "dev": "node -r ts-node/register node_modules/nuxt/bin/nuxt dev -c nuxt.config.ts",
     "build": "node -r ts-node/register node_modules/nuxt/bin/nuxt build -c nuxt.config.ts",
     "generate": "node -r ts-node/register node_modules/nuxt/bin/nuxt generate -c nuxt.config.ts",
     ...
   }
   ```
1. Run
   ```cmd
   > yarn dev
   OR
   > yarn build
   OR
   > yarn generate
   ```
