### ISSUE TITLE
namespaced store module state is not cleared

### ISSUE THREAD

**Issue by valera-shulghin** [nuxt/nuxt.js#2879]
The issue is that the state from **namespaced** store modules is not cleared before each request, so one user can see the remains of state from other user. Here is the code to reproduce it: 

/store/index.js
```javascript
import Vuex from 'vuex'

import user from './modules/user'

const createStore = () => {
  return new Vuex.Store({
    modules: {
      user
    }
  })
}

export default createStore
```

/store/modules/user.js
```javascript
export default {
  namespaced: true,

  state: {
    profile: null
  },

  mutations: {
    getProfile(state ) {
      state.profile = { date: new Date() }
    }
  }
}
```

/middleware/set-user.js
```javascript
export default function ({ store }) {
  console.log(store.state.user.profile) // you will see here the value from previous request, or null if this is the first request
  if (!store.state.user.profile) {
    // store.state.user.profile should be null in middleware
    // for some reason it takes the value from previous requests
    store.commit('user/getProfile')
  }
}
```

/pages/index.vue
```javascript
<template>
  <section class="container">
    {{ user }}
  </section>
</template>

<script>
import { mapState } from 'vuex'
export default {
  computed: mapState({
    user: state => state.user.profile
  }),
}
</script>
```

Here is the [repo to reproduce the issue](https://github.com/valera-shulghin/nuxt-store-issue)

Steps to reproduce the issue: 
1. `npm run dev`
2. Enter `http://locahost:3000`. You will see `null` output from middleware.
3. Refresh the page. You will see that the `console.log` from middleware will return the value from previous request

I noticed that everything works fine if the module is **not namespaced**

**Comment by unr** [comment]
I've had similar issues, which I have solved by making sure to return a function for state.

**I don't know if this is a good solution, but it at least stopped sharing user info for me.**

You can read more here: https://vuex.vuejs.org/en/modules.html#module-reuse

---

You should likely just update to:

```
export default {
  namespaced: true,

  state(): {
    return {
        profile: null
    };
  },

  mutations: {
    getProfile(state ) {
      state.profile = { date: new Date() }
    }
  }
}
```

**Comment by valera-shulghin** [comment]
It solved the issue. Thank you!
