### ISSUE TITLE
How to include aws-sdk in nuxt.config.js

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#288]
I followed this article.
 [aws-sdk-with-webpack](https://aws.amazon.com/blogs/developer/using-webpack-and-the-aws-sdk-for-javascript-to-create-and-bundle-an-application-part-1/)

But since added loaders in nuxt.config.js it removed the default loaders. I copy pasted the default loader from the documentation but still it was throwing some error

    ERROR in ./~/xmlbuilder/lib/index.js
    Module not found: Error: Can't resolve 'lodash/object/assign' in '/Users/shyam/Documents/indee/new-indee/node_modules/xmlbuilder/lib'
     @ ./~/xmlbuilder/lib/index.js 5:11-42
     @ ./~/aws-sdk/lib/xml/builder.js
     @ ./~/aws-sdk/lib/core.js
     @ ./~/aws-sdk/lib/browser.js
     @ ./plugins/aws.js

**Comment by alexchopin** [comment]
Hi,
Can you provide us some code snippets?
Thanks

**Comment by shyamchandranmec** [comment]
I am pasting the contents of 2 files. Rest is normal nuxt-express  template
**plugins/aws.js**
    
    import AWS from 'aws-sdk';
    console.log(AWS);
    AWS.config.update({
        accessKeyId: process.env.accessKeyId,
        secretAccessKey: process.env.secretAccessKey,
       region: process.env.region
    });


**loaders in nuxt.config.js**

        loaders:[
            {
                test: /\.(png|jpe?g|gif|svg)$/,
                loader: 'url-loader',
                query: {
                    limit: 1000, // 1KO
                    name: 'img/[name].[hash:7].[ext]'
                }
            },
            {
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                loader: 'url-loader',
                query: {
                    limit: 1000, // 1 KO
                    name: 'fonts/[name].[hash:7].[ext]'
                }
            },
            {
                test: /.json$/,
                loaders: ['json-loader']
            },
        ]

**Comment by Atinux** [comment]
Actually, it's because `aws-sdk` use an old version of `xmlbuilder` which uses lodash 3 (deprecated) and make the lodash dependency a mess and fail, see https://github.com/aws/aws-sdk-js/issues/1182

I'll try to see another way around.

**Comment by shyamchandranmec** [comment]
@Atinux  Thanks a lot for taking time to look into this.

**Comment by Atinux** [comment]
I close it since it's not nuxt related.

**Comment by shyamchandranmec** [comment]
@Atinux Were you able to figure out some way to include this sdk?

**Comment by Atinux** [comment]
Actually you can fork it, update the `xmlbuilder` dependency and use the git url in your package.json ;)
