### ISSUE TITLE
The best place to initialize logger (nuxt lifecycle)

### ISSUE THREAD

**Issue by KindWizzard** [nuxt/nuxt.js#2882]
Hello guys. I'm currently making logger. And I was stuck with the question — where is the best place for initialize logger. At first placing logger in the module looks like a nice idea (its allows to use error hook to catch and log unhandled errors)... but:

1. Why module stars two times (at the building moment and after starting)?

2. So. What's is the best way to realise am I in building process or not? I find the some kind of stupid way — to hook two event, "build" and "end". 

3. And the last. What is the best place to create logger instance (the class, thats write logs to the file system)? It's looks like there is no way to get the logger instance in plugin if it was created in module. But I'd like to use shared instance for obvious reasons. May be not module? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2506">#c2506</a>)</em></sub></div>

**Comment by KindWizzard** [comment]
If somebody interested in this, I found the solution. Now I have "shared" logger instance, that allows me to use the same file stream, without creating new one for each request.

**Comment by qm3ster** [comment]
@KindWizzard did you put it in a plugin and attach the instance to the app object?

**Comment by KindWizzard** [comment]
@qm3ster Unfortunately, you will not be able to do this in the plugin. The reason is, that the pluging will be executed both on the sever side and the client side. Plus you can get access to server middleware (not Nuxt middlware) only from module.
