### ISSUE TITLE
How to allow ES6 imports in nuxt.config.js file?

### ISSUE THREAD

**Issue by atomiks** [nuxt/nuxt.js#2885]
I want to grab some data from a config file to use in `nuxt.config.js`, but it comes up with the `SyntaxError: Unexpected token import` error.

**/assets/site-config.js** (used throughout components as well)
```js
export default {}
```

**nuxt.config.js**
```js
import SITE from './assets/site-config'
module.exports = {}
```

I've tried to create a .babelrc to transform the imports to `commonjs` but it doesn't work.

**.babelrc:**
```json
{
  "plugins": ["transform-es2015-modules-commonjs"]
}
```

**Comment by paulgv** [comment]
It should be implemented in Nuxt v2: https://github.com/nuxt/nuxt.js/issues/1935
In the meantime, it would be best you fallback to ES5 require method.
