### ISSUE TITLE
vuex store problem in layout

### ISSUE THREAD

**Issue by umardraz** [nuxt/nuxt.js#2886]
Hello

Here is my old simple vuejs code which is working perfect

```
<template>
  <div id="app" v-if="$store.state.isUserLoggedIn">
    <page-header />
    <div id="content-wrapper">
      <left-header />
      <router-view></router-view>
    </div>
  </div>
  <div id="app" class="app" v-else>
    <div id="content-wrapper-login">
      <router-view></router-view>
    </div>
  </div>
</template>
```

But the same thing is not working in NUXT. Here is my nuxt code

```
<template>
  <div v-if="$store.state.isUserLoggedIn">
    <page-header />
    <div id="content-wrapper">
      <left-header />
      <nuxt/>
    </div>
  </div>
  <div v-else class="app">
    <div id="content-wrapper-login">
      <nuxt/>
    </div>
  </div>
</template>
```

Would you please help me how to access store in layout file?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2508">#c2508</a>)</em></sub></div>

**Comment by fengjiel** [comment]
I think this error is your component has two root nodes and '$store. State. IsUserLoggedIn'  is false.You can add a root node package.

**Comment by umardraz** [comment]
Hello,

Not sure about your answer, would you please tell me with some more details. I can get $store in pages but not in layout

**Comment by fengjiel** [comment]
i think $store.state.isUserLoggedIn is false  result in an error ,you can add a root dom.I don't know if it's going to have an impact.such as:
```
<template>
<div>
  <div v-if="$store.state.isUserLoggedIn">
    <page-header />
    <div id="content-wrapper">
      <left-header />
      <nuxt/>
    </div>
  </div>
  <div v-else class="app">
    <div id="content-wrapper-login">
      <nuxt/>
    </div>
  </div>
</div>
</template>
```

**Comment by fengjiel** [comment]
I did a demo.If '$store. State. IsUserLoggedIn' is true, he will run normally.Forgive my poor English.

**Comment by umardraz** [comment]
Not working still in layouts I am damm sure the store is not working in layouts

**Comment by umardraz** [comment]
Here is my layouts/default.vue file

```
<template>
  <div>
    <div>User Info: {{ user }}</div>
    <page-header />
    <div id="content-wrapper">
      <left-header />
      <nuxt/>
    </div>
  </div>
</template>

<script>
import PageHeader from '@/components/Header.vue'
import LeftHeader from '@/components/Leftside.vue'

export default {
  components: {
    PageHeader,
    LeftHeader
  },
  computed: {
    user () {
      return this.$store.state.user
    }
  }
}
</script>

<style>
</style>

```
I am getting email user state in this layouts/default.vue file

but the same thing is working fine in pages/user.vue

Here is the code of as pages/users.vue

```
<template>
  <div id="rightside">
     {{ user }}
  </div>
</template>

export default {
  data () {
    return {
    }
  },
  computed: {
    user () {
      return this.$store.state.user
    }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
```

No idea what is the exact method to get store state in layouts.

**Comment by HoraceKeung** [comment]
I copied your code (except the page-header and left-header) and it works. Try put a "console.log(this.$store.state.user)" above "return this.$store.state.user" and see what it prints out.

**Comment by umardraz** [comment]
Yes because the state is not available while server end. 

We need to store the state on server like express-session then then retrieve from there and dispatch in store

**Comment by husayt** [comment]
Check your state in vue devtools. This should work
