### ISSUE TITLE
JS execution silently fails on a statically generated site

### ISSUE THREAD

**Issue by katafractari** [nuxt/nuxt.js#2888]
JS execution silently fails on a statically generated site when a route path contains non-ascii characters.

Steps to reproduce:
```
vue init nuxt-community/starter-template nuxt-project
cd nuxt-project
npm i
cp pages/index.vue pages/провизорам.vue
npm run generate
npm i http-server
npx http-server dist
```
Put some console.logs into провизорам.vue and index.vue, for example
```
<template>
  <div></div>
</template>

<script>
export default {
  mounted () {
    console.log('test')
  }
}
</script>
```

Visit http://localhost:8080/провизорам and you'll see that the console.log does not get executed and that there is no error in the developer console. But if you put some code into index.vue and visit http://localhost:8080/ the code will execute.

When running `npm run dev` this problem does not manifest itself.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2510">#c2510</a>)</em></sub></div>

**Comment by katafractari** [comment]
After playing around a bit with this one I found out that the only way I can get routes with non-ascii characters to work is to use decodeURI on path when creating the route directory on **nuxt generate**:
https://github.com/katafractari/nuxt.js/commit/7f38925662d4caa62159ca1f23621199c0fefd41
And manually configure the routes so the path attribute is a URL encoded value. For example **farmacişti** becomes *farmaci%C5%9Fti*:

```
{
  name: 'farmacişti',
  path: '/farmaci%C5%9Fti',
  component: '...',
  chunkName: '...'
}
```

**Comment by Pumpe** [comment]
I have same problem

**Comment by aldarund** [comment]
I tested this on latest nuxt-edge on win and im just getting 404 page for ascii pages like провизорам.vue in universal mode on dev run
