### ISSUE TITLE
sass source maps for independent sass files

### ISSUE THREAD

**Issue by nikugogoi** [nuxt/nuxt.js#2889]
My structuring could be wrong or I am missing some part of documentation that does this. Below I have shared the config. I believe the source maps are not produced. 
**/assets/sass/my-bulma.sass**
```
@import '~bulma/sass/utilities/initial-variables'

$green: #5fbc0a
$cyan: #5fd9eb
$info: $cyan

@import '~bulma/bulma'
```

**/nuxt.config.js**
```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'xxx',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  css : [
    '@/assets/sass/my-bulma.sass'
  ],
  /*
  ** Build configuration
  */
  build: {
    postcss: {
      plugins: {
        'postcss-custom-properties': {
          warnings: false
        }
      }
    },
    cssSourceMap : true,
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}
```
What is the actual way to structure the css in NUXT? with sourcemap

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2511">#c2511</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
