### ISSUE TITLE
Unable to use external Vue plugin

### ISSUE THREAD

**Issue by huxleydigitaluk** [nuxt/nuxt.js#2891]
Trying to get the Dragabilly Vue plugin to work with my Nuxt site: https://www.npmjs.com/package/vue-draggabilly

I've used the usual approach that has worked with similar plugins but I don't have the depth of knowledge to crack this one.  I am adding into my nuxt config file:

```
 plugins: [
   { src: '~/plugins/vue-draggabilly.js', ssr: false }
  ]
```
That file includes this code:

```
import Vue from 'vue'
import VueDraggabilly from 'vue-draggabilly'

Vue.use(VueDraggabilly)
```

However, I get the following error and I'm not able to use:

***vue-draggabilly.js:3 Uncaught ReferenceError: exports is not defined***

This refers to this line in the plugin:

`exports.install = function (Vue, options) { .... `

Any help very greatly appreciated!

**Comment by husayt** [comment]
Seems like this is similar issue to #206`

**Comment by qm3ster** [comment]
Well, it is actually written weirdly.
```js
import Draggabilly from 'draggabilly';

exports.install = function (Vue, options) {
```
it uses ES6 import but not `require()` export.

if you edit that to say
```js
function install(Vue, options) {
//...
}
export default { install }
```
does that fix it?

**Comment by huxleydigitaluk** [comment]
@qm3ster thanks man! That has got me much closer.  I made your change but the 'v-draggabilly' directive still wasnt being recognised.  In the end I just loaded in the content of that function directly in my version of the plugin like this:

`import Vue from 'vue'

import Draggabilly from 'draggabilly';

Vue.directive('draggabilly', {
    bind: function (elem, binding, vnode, oldVnode) {
        var options = binding.value || {};
        var draggie = new Draggabilly(elem, options);
        var directives = vnode.data.directives;
        for (var i in directives) {
            var dir = directives[i];
            if (dir.name === "draggabilly-on") {
                draggie.on(dir.arg, dir.value);
            }
            else if (dir.name === "draggabilly-once") {
                draggie.on(dir.arg, dir.value);
            }
        }
    },
    unbind: function (elem, binding, vnode, oldVnode) {
        //TODO
    }
});
Vue.directive('draggabilly-on', {
    bind (elem, binding, vnode, oldVnode) {
        return; //No need to do anything
    },
});
Vue.directive('draggabilly-once', {
    bind (elem, binding, vnode, oldVnode) {
        return; //No need to do anything
    },
});
`
Not sure how solid an approach that is but it's got things working which is a huge step up!!  Thanks again.

**Comment by qm3ster** [comment]
Well it's a tiny wrapper as you can see, so probably no harm at all.
```js
import Vue from 'vue'
import Draggabilly from 'draggabilly'

function bind (el, binding, vnode) {
  if (el.draggie) {
    return
  }
  const options = binding.value || {}
  const draggie = new Draggabilly(el, options)
  el.draggie = draggie
  const directives = vnode.data.directives
  for (let i in directives) {
    const dir = directives[i]
    if (dir.name === 'draggie-on') {
      if (dir.modifiers.once) {
        draggie.once(dir.arg, dir.value)
      } else {
        draggie.on(dir.arg, dir.value)
      }
    }
  }
}

Vue.directive('draggie', {
  bind,
  unbind: function(el, binding, vnode) {
    if (el.draggie) {
      el.draggie.destroy()
    }
  }
})
Vue.directive('draggie-on', {
  bind(elem, binding, vnode) {
    return //No need to do anything
  }
})
```
This should prevent a memory leak by destroying the `Draggabilly`. I didn't test it.
I also changed the API to the following
```vue
<div v-draggie v-draggie-on:dragStart="method"  draggie-on:dragEnd.once="method2"></div> 
```

**Comment by qm3ster** [comment]
This might be necessary if you plan to change options of the Draggabilly programmatically:
```js
import Vue from 'vue'
import Draggabilly from 'draggabilly'

function bind(el, binding, vnode, oldVnode) {
  if (el.draggie) {
    if (el.draggie && el.draggie.destroy) {
      el.draggie.destroy()
    }
  }
  const options = binding.value || {}
  const draggie = new Draggabilly(el, options)
  el.draggie = draggie
  const directives = vnode.data.directives
  for (let i in directives) {
    const dir = directives[i]
    if (dir.name === 'draggie-on') {
      if (dir.modifiers.once) {
        draggie.once(dir.arg, dir.value)
      } else {
        draggie.on(dir.arg, dir.value)
      }
    }
  }
}

Vue.directive('draggie', {
  bind,
  update: bind,
  unbind: function(el, binding, vnode) {
    if (el.draggie && el.draggie.destroy) {
      el.draggie.destroy()
    }
  }
})
Vue.directive('draggie-on', {
  bind(elem, binding, vnode) {
    return //No need to do anything
  }
})
```
