### ISSUE TITLE
Option for relative paths

### ISSUE THREAD

**Issue by koljakutschera** [nuxt/nuxt.js#2892]
Hi,

to use nuxt for electron-apps we would need relative paths for assets etc. Nuxt always adds a leading / to urls so relative paths are not possible.

In https://github.com/leo/electron-next this is solved via assetPrefix option...

Thank you for nuxt!

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2515">#c2515</a>)</em></sub></div>

**Comment by koljakutschera** [comment]
Hi again,

by extending the build(webpack-config) via nuxt.config.js its possible to convert all absolute links to relative links.

Add this to your nuxt.config.js if you need relative links for electron or cordova apps.

`
build: {
    extend (config, { isDev, isClient }) {
      if (!isDev) {
        // relative links, please.
        config.output.publicPath = './_nuxt/'
      }
      return config
    }
  }
`

**Comment by zlzdp** [comment]
It's work now, thank you

**Comment by cdunlap** [comment]
The webpack build extension method of changing the `_nuxt` path to a relative one appears to break asset paths loaded in SCSS (eg: fonts). `~/assets/fonts/...` now produces an output path of `/_nuxt/_nuxt/fonts/...`.
