### ISSUE TITLE
Allow initial render transitions

### ISSUE THREAD

**Issue by ConsoleTVs** [nuxt/nuxt.js#2894]
Would it be a pain in the ass to allow initial render transitions in the transitions object?

https://vuejs.org/v2/guide/transitions.html#Transitions-on-Initial-Render

Example:
```js
module.exports = {
  transition: {
    name: 'page',
    mode: 'out-in',
    appear: true,
  }
}
```

```html
<transition name='page' mode='out-in' appear>
  <!-- ... -->
</transition>
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2514">#c2514</a>)</em></sub></div>

**Comment by ConsoleTVs** [comment]
Wait I just noticed that that already exists, if I actually add a 

```js
beforeEnter (el) {
    console.log('Before enter...');
}
```

to the object, and set the appear to true, I get the log done on initial page.

If that's correct, would be great to document it.

**Comment by ConsoleTVs** [comment]
Aparently, the classes are not applied, only the callback...

Any solutions?

**Comment by ConsoleTVs** [comment]
Aparently, the only fix (workaround) is:

https://glitch.com/edit/#!/nuxt-appear?path=nuxt.config.js:3:4

**Comment by marceloavf** [comment]
I was also looking for that, seems that you're right about only the callback being called.

**Comment by jkd77** [comment]
Is there a different way to go about this? This method seems to conflict with transition triggered GSAP animations. Any advice would be greatly appreciated.

**Comment by dkushner** [comment]
I am also experiencing some difficulty getting transitions to play _only_ on initial render and strictly on the client side. Using the normal `transition(appear)` seems to conflict with SSR.

**Comment by jkd77** [comment]
See also Manually set loading page transition #729: [https://github.com/nuxt/nuxt.js/issues/729](https://github.com/nuxt/nuxt.js/issues/729)

**Comment by galvez** [comment]
@pi0 @clarkdo can one of you shed a light here?
