### ISSUE TITLE
Does breadcrumb have a solution?

### ISSUE THREAD

**Issue by zzlw** [nuxt/nuxt.js#2899]

**Comment by husayt** [comment]
@alexchopin  @Atinux @pi0 @clarkdo  there are a lot of nonsensical issues like this being raised lately. I guess they take a lot of your time too. Can we do something to help to clear this up. Maybe assign some moderators from community, otherwise some very feedback and issues are escaping attention under this rubble.

**Comment by qm3ster** [comment]
I wanna be able to close issues :pizza: do me do me

Also, lets funnel people into the [Vue Land #nuxt Discord channel](https://discordapp.com/channels/325477692906536972/325479939384147968) from:
- nuxtjs.org
- README.md
- The header of https://gitter.im/nuxt/nuxt.js

**Comment by qm3ster** [comment]
@husayt I like your logic :pizza: 
1. See a nonsensical issue with _No description provided._
3. Become concerned the admins' time is being wasted
2. Tag all the admins to waste their time 
4. :call_me_hand:

**Comment by Atinux** [comment]
Thanks @qm3ster

**Comment by qm3ster** [comment]
@Atinux pls merge #2783 and gib me permission to close issues :ok_hand: hue hue

**Comment by Atinux** [comment]
Done, great work BTW 🙌

**Comment by husayt** [comment]
@qm3ster your sarcasm is noted. You lost the point however. There are over
300 open issues. The point was to see what can be done to help admins on
this. Project has grown immensely and needs more helping hands.

**Comment by Atinux** [comment]
@husayt I agree also with you, we have more and more issues and a lot of them are non-sense. You guys are helping us a lot and I am more than happy to have you on board to help us make some issue triage and assign us critical issues that needs to be resolve and close the others where an answer is given.

**Comment by husayt** [comment]
Thanks @Atinux. Can you also add me to docs website. That also needs a bit of cleanup, I noticed quite a few broken anchors and etc.

**Comment by uptownhr** [comment]
@Atinux I'd be willing to help out here too!
