### ISSUE TITLE
Translation support (or get access to Vue configuration)

### ISSUE THREAD

**Issue by VincentLoy** [nuxt/nuxt.js#29]
Hi, We are building our new app using nuxt as an Express.js middleware. Our app must be translated in some languages.

We are looking to use [i18next](http://i18next.com/) using the [i18next vuejs build](https://github.com/rse/vue-i18next). 
As you can see, to use it, we need to make some Vue configuration.
```javascript
Vue.use(VueParams);
Vue.use(VueI18Next);
Vue.params.i18nextLanguage = "en";
i18next.init({ lng: Vue.params.i18nextLanguage, ... });
// ...
```

Don't know if there is a way to add custom Vue configuration by using Nuxt ? 

Many thanks :)

**Comment by alexchopin** [comment]
Hi, thanks to use Nuxt with your team.

You can add it with the plugins option in nuxt.config.js file.
You can see an example here : https://github.com/nuxt/nuxt.js/tree/master/examples/plugins-vendor.

Thanks

**Comment by VincentLoy** [comment]
Hi @alexchopin, thanks a lot, I should see it without opening an issue, my bad :)

**Comment by alexchopin** [comment]
No worries, the website should be ready soon for a complete documentation.

**Comment by Atinux** [comment]
@VincentLoy you can take a look at this example also, it might help you as well: https://hyperdev.com/#!/project/nuxt-element-ui

**Comment by VincentLoy** [comment]
Ok I'll check it out.

Can't wait for the release 1.0.0 with the documentation :package: 
Keep up the good work !
Thanks again.

**Comment by Xowap** [comment]
@VincentLoy and myself are trying out Nuxt in a smaller project before rolling it into bigger things if we can find a good workflow with it.

We'd be happy to provide feedback on the docs and on usage if you'd like.

**Comment by Atinux** [comment]
@VincentLoy @xowap I would you guys to give me your thoughts on the documentation. Actually some of it is available on https://nuxtjs.org

We are making an e-commerce website with my brother with Nuxt.js, I think it's a big enough project to show that Nuxt.js is reliable for big project.

I you have any question during your project with Nuxt.js, feel free to create an issue :)

**Comment by Atinux** [comment]
BTW, if you guys are going to the DotJS this Monday or at the VueJs Paris Meetup this weekend, we could meet there and talk about Nuxt.js ;)

**Comment by Xowap** [comment]
Nope can't get there unfortunately. I'm reaaally sad. Though we could grab some beers at some point if you're Paris-based.

Good to see the doc online! That's kind of new? I recall checking that domain about this morning and not seeing anything.

**Comment by Atinux** [comment]
We just published it few hours ago. I am living in Barcelona but come pretty often to Paris, we will have a moment to catch up and grab a beer!

**Comment by VincentLoy** [comment]
That sound great !! Very happy to see the documentation online :)

**Comment by LouiseStroeh** [comment]
Hi,
I need to set some custom merge strategies (Vue.config.optionMergeStrategies), so I am curious if it is possible to access the Vue config when using nuxt?

**Comment by Atinux** [comment]
@LouiseStroeh simply `import Vue from 'vue'` in a [plugin](https://nuxtjs.org/guide/plugins/#vue-plugins).
