### ISSUE TITLE
Question about data access (resource/service)

### ISSUE THREAD

**Issue by hyurtseven81** [nuxt/nuxt.js#290]
Hi, 

We are trying to change our angularjs infrastructure to vue and nuxt but i have a question about data access. 

On angular we used to use resources to access and manipulate data like create user delete user etc. 

But i read about vue-resource is not recommended way anymore, (actually i don't know exactly vue-resource and  angular resource are the same)

So i saw some examples use vuex to access and manipulate data and in some components access the data with axios but i can't find about what is the best practice or suggested way.

Could you please help us?

Thank you.

**Comment by Atinux** [comment]
Hi @hyurtseven81 

This is clearly a question about Vue.js best-practices, I recommend you to post it on [vue.js forum](https://forum.vuejs.org/).
