### ISSUE TITLE
Duplicated meta tags and titles

### ISSUE THREAD

**Issue by stephenrichard** [nuxt/nuxt.js#2902]
Hey,
I'm working on a SSR website and keep having issues with duplicated meta tags. As you can see on the screenshot below, nuxt generate two title tags.
![capture d ecran 2018-02-26 a 14 18 46](https://user-images.githubusercontent.com/4067686/36672585-19108010-1b00-11e8-92bc-b5d183aa8505.png)

I use nuxt `head()` method and `hid` attribute to override defaults tags on my article page, but the two meta tags are being used.

In nuxt.config.js : 
<img width="439" alt="capture d ecran 2018-02-26 a 14 24 43" src="https://user-images.githubusercontent.com/4067686/36672788-e3965454-1b00-11e8-92c4-c862300de73e.png">

In videos/_slug.vue :
<img width="565" alt="capture d ecran 2018-02-26 a 14 22 56" src="https://user-images.githubusercontent.com/4067686/36672727-a7448f98-1b00-11e8-99f5-ea1a8953654a.png">

Oh, and if I remove default title and description from `nuxt.config.js`, nuxt is using the title from package.json

**As anyone faced the same issue ? Or maybe I'm using nuxt head method wrong ?**

Thanks in advance for your help !

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2521">#c2521</a>)</em></sub></div>

**Comment by dohomi** [comment]
@stephenrichard jst as an idea: did you try to write `hid:og:title` instead of `hid:ogTitle`? I use Nuxt with hid and didn't see any issues so far

**Comment by stephenrichard** [comment]
Hey @dohomi, yes I tried with both `hid:"og:title"` and `hid:"ogTitle"` to see if there was any difference, the answer was no 😅. I'll try again, just in case, maybe the issue comes from another part of the code. 

Also two things I do (maybe it's part of the problem):
* I use the manifest object for the android widget, with custom name and description
* I use the generate option to generate static routes for each one of my post:
<img width="389" alt="capture d ecran 2018-02-27 a 16 34 41" src="https://user-images.githubusercontent.com/4067686/36737787-31a8cccc-1bdc-11e8-93b6-75704ecd9c3c.png">

**Comment by dohomi** [comment]
@stephenrichard if you have a repo to look at might help. seems that its definitely some issue with your setup of generate function

**Comment by stephenrichard** [comment]
@dohomi It's for a client projet on a private repo, I can't set it to public or give access rights.

For what it's worth I'm hosting the website on Netlify, that's why the `subFolders: false` option is set (according to the last line on Nuxt doc about generate: https://fr.nuxtjs.org/api/configuration-generate/).
I'll give a try to the payload to give the static files generation some time.

**Comment by Gomah** [comment]
I had the same issue with the meta module (included by default in the pwa-module).
Adding the following lines to your `nuxt.config.js` file should do the trick:

```js
meta: {
  ogTitle: false,
  ogDescription: false,
},
```

The meta module generates the [ogTitle & ogDescription by default](https://pwa.nuxtjs.org/modules/meta.html), even if you specify og:title & og:description in the `head()` function in your pages.

**Comment by stephenrichard** [comment]
Hey, thanks for your answer, I tried to set the title and description to false in `nuxt.config.js`but it just create new meta tags with false values and keeps duplicating them. 😕

**Comment by Gomah** [comment]
@stephenrichard Can we see some code example?

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.

**Comment by infostatus** [comment]
Having the same situation. On nuxt generate it will create duplicated meta-tags.

**Comment by manniL** [comment]
@infostatus Could you create a new bug report with a reproduction repository for that?
