### ISSUE TITLE
Dynamic layout transition

### ISSUE THREAD

**Issue by BorisTB** [nuxt/nuxt.js#2903]
I'm trying to create animation between public and private layout but I couldn't find anything about it in documentation. Is there any way to accomplish this? I want public layout to "remodel" to private layout after login

**Comment by qm3ster** [comment]
You can't transition one component into a different component in Vue.
You will have to build one layout component that supports both of those options, and toggle it.
If you do that, the transitions will be [very easy to implement just by hiding and showing child components](https://snipcart.com/blog/vuejs-transitions-animations#cp_embed_EwwPgr).
