### ISSUE TITLE
Wait for store update before route change?

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt/nuxt.js#2904]
Not sure if this belongs here or in the vue router github. However, my question is, when clicking a link, is there any way to make the route change wait for the store to be updated? I'm setting some store variables on link click, but sometimes the route change is a tiny bit to fast.

**Comment by paulgv** [comment]
Your link could be a simple `<a>` tag that triggers a method in which the store action is dispatched and returns a promise that you can use to programmatically navigate to the next route using `this.$router.push()`.

**Comment by qm3ster** [comment]
If opening the link in a new tab and such would ruin your flow, you should avoid using a link in the first place.
If it's always okay, but you need to take certain actions before displaying the page, you should use the target page's component hooks.
If you need to handle specific source+target combinations or are likely to redirect, you may want to use a (router) middleware.
