### ISSUE TITLE
require.context importing ignored files

### ISSUE THREAD

**Issue by btkostner** [nuxt/nuxt.js#2905]
This is related, and noted in PR #2594. There was no issue created, so I figured I would document this.

Currently I have a `store` folder that holds my modules. It has an `index.js` file that exports the store creation function. I also keep tests next to the files in the form of `module.integration.js` or `module.spec.js`. Currently nuxt tries to import these tests files (even though they are ignored), which causes a huge amount of webpack errors.

```
 ERROR  Failed to compile with 22 errors                                                                                                               14:08:26

These dependencies were not found:

* child_process in ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
* fs in ./node_modules/ava/lib/snapshot-manager.js, ./node_modules/ava/lib/process-adapter.js and 12 others
* module in ./node_modules/require-extension-hooks/src/index.js, ./node_modules/time-require/src/requireHook.js
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js
```

Relevent code line: https://github.com/nuxt/nuxt.js/blob/dev/lib/app/store.js#L7

**Comment by Atinux** [comment]
Hi @btkostner 

Indeed, we want to offer a way as we talked here: https://github.com/nuxt/nuxt.js/issues/2592

@pi0 seems to be working on it, could you confirm?

**Comment by pi0** [comment]
> Something to mention is it is not covering require.context ignores (For store and middleware) but it can be considered as enough for basic support as our regexes already exclude things like *.test.* for store and middleware.

Using regex for `require.context` is so limited.  But as I remember, it should be ignored.

@btkostner Do you have any public reproduction example?

**Comment by btkostner** [comment]
@pi0 not yet, but I should be able to make a repo quick

**Comment by pi0** [comment]
Thanks for repro. I've tweaked regexes so that it ignores any `[name].*.[ext]` pattern. (e0cc9a1)
