### ISSUE TITLE
how to receive the req.headers.referer and not req.readers.host in asyncData

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#2906]
Hello,

I would need to know the current referer of my deployment and not the host (due to CNAME forwarding in aws).

Is it possible to make these changes available in Nuxt? 

Thanks

**Comment by awronski** [comment]
@dohomi I check the req in the method `nuxtServerInit` of `Vuex.Store`.
Extract what I want to store in the state.

```js
async nuxtServerInit ({ state, commit }, { route, req, res, env }) {
   [...]
}
```

**Comment by dohomi** [comment]
@awronski is inside of the nuxtServerInit different context than in asyncData?

**Comment by Atinux** [comment]
Actually, `req` is the same as node.js (we use connect under the hood). I have a project with Nuxt.js and I actually use `const referer = req.headers.referrer || req.headers.referer`.

You may want to check if your DNS is not giving a different header for the referer @dohomi

**Comment by dohomi** [comment]
@Atinux thanks that might be the reason. I have a weird AWS cloudfront CNAME setup for my website and had to dangle around with CNAME forwarding for my root domain. this is the domain: https://planet.training. If I look at the Request Headers seems that cloudfront might not sent the right headers. So the issue seems on my DNS setup then, thanks for the quick response
