### ISSUE TITLE
Not working with Docker

### ISSUE THREAD

**Issue by BryanARivera** [nuxt/nuxt.js#291]
I tried using the starter template with a docker container.  I know the docker config is ok, left the port at 3000 and also tried 80 but no luck in browser.  Console has no info.  

Any ideas?

**Comment by BryanARivera** [comment]
```
      HOST: '0.0.0.0'
      PORT: 80
```

That was easy, hope it helps

**Comment by raisiqueira** [comment]
Hey @bryaan, you can help-me?

**Comment by RobvanGastel** [comment]
@bryaan Can you share the Dockerfile of the nuxt project?

**Comment by tillkolter** [comment]
@RobvanGastel 

```
FROM node:7.8

ADD . /app
WORKDIR /app

RUN npm install

ARG APP_NODE_ENV=production
ENV NODE_ENV ${NODE_ENV}
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]

```

**Comment by tillkolter** [comment]
Important is to configure 0.0.0.0 as host. See https://nuxtjs.org/faq/host-port/

**Comment by lomholdt** [comment]
This is great! If you are using `docker-compose` you can define the `HOST` using environment variables as specified in tillkolter's link above. 

```yml
    environment:
      - HOST=0.0.0.0
```
