### ISSUE TITLE
vue.config seems to be inaccessible from within nuxt

### ISSUE THREAD

**Issue by teamgroove** [nuxt/nuxt.js#2910]
i couldn't find a way to configure Vue via vue.config before nuxt uses it.

https://vuejs.org/v2/api/

I need it for ignoring custom-elements. 
Is there any way to deal with the vue.config which i missed? 
I looked at the nuxt-source, but didn't find a place for that config.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2527">#c2527</a>)</em></sub></div>

**Comment by qm3ster** [comment]
@Atinux this would have to happen somewhere here-ish:
https://github.com/nuxt/nuxt.js/blob/1ab4be456f1262d1ebace9c1b6a332c63a851aa0/lib/app/client.js#L30
Should I make a PR?
Furthermore, should it be just `ignoredElements` or an object assign? `keyCodes` seems like another cool one.

**Comment by qm3ster** [comment]
@teamgroove does `vue-loader` just pass Custom Elements in .vue files through, and your only problem is hydration?

**Comment by teamgroove** [comment]
I can't answer the question directly, but the problem is that "aframe custom elements" like <a-scene> or <a-light> get recognized when used inside vue - and therefore in nuxt. Warnings / console.logs everywhere: ".. did you forget to register ...".

Besides that: Aframe itsself has another problem when used with nuxt/ssr, i am going after, because it injects some things in the dom and confuses ssr/hydration right now. I hope this can be fixed, but for now ignoring the elements would be necessary to bring silence back into the console :-)

If you would ask me, i think the complete config-object should be passable to vue.config.

**Comment by qm3ster** [comment]
Should nuxt's `errorHandler` be overwritten?
Or should a user-provided `errorHandler` be ignored? (Only in client or server too?)
Should both run?

Should we just let users shove whatever they want in, and blame them when they break everything, and mark the option as "advanced" in the config docs?

**Comment by teamgroove** [comment]
Ok, now i see the implications. I apologize i didn't see that earlier. Seems like a good strategy to hide it away as far as possible, but make some handpicked configs easily, that hopefully won't break something. Or go the advanced-way.
 
ignoredElements, keyCodes, productionTip, performance, devtools, silent

These are the only ones, that seem safe. 

On theother side: the need to change any of those handlers is really rare i guess. So widespread mayhem is hopefully not to expect. Maybe a blinking warning sign would be a good fit :)

**Comment by qm3ster** [comment]
@Atinux should I make a PR adding this to config?

**Comment by Atinux** [comment]
I guess it has to be in `lib/app/index.js`, you can make a PR @qm3ster so we can talk with the core-team what's the best way to implement this feature.

**Comment by jc275** [comment]
@teamgroove If I have understood your question properly, it may be sufficient to bundle your vue.config presets as part of `vendor.js`. It seems to be working for me.
For example:
```js
// vue.config.js
import Vue from 'vue'
Vue.config.productionTip = false
Vue.config.performance = true

// nuxt.config.js
module.exports = {
  plugins: [
    // not here
  ],
  build: {
    vendor: [
      '~/vue.config.js', // loads before nuxt app
    ],
  }
}
```
However, I haven't tried this with `ignoredElements`, and I don't know whether it interferes with Nuxt.

**Comment by teamgroove** [comment]
YMMD! Be it just for the idea to put:this to: exactly there. 
A lot of really bright sparks around me, wow. JC275: Congrats! Really cool, I didn't have that idea.
It works. But i am still not fully convinced of propagating it to the crowd of doing it this specific way. 

A 'natural' place for a 'vue.config'-object inside of nuxt.config.js still seems a legit request to document and less a burden for the people coming after us - seeking for a solution to this. 

Anyway: yes, the way you described already works. 

But still the place around: https://github.com/nuxt/nuxt.js/blob/1ab4be456f1262d1ebace9c1b6a332c63a851aa0/lib/app/client.js#L30 
is literally calling for a configuration-object to consume and: just do it straight.
