### ISSUE TITLE
After hit 404 layout and then Back button my script is broken

### ISSUE THREAD

**Issue by hackuun** [nuxt/nuxt.js#2912]
Hi. I have small script in my default layout

```js
mounted () {
    let links = document.querySelectorAll('a[href]:not([href^=mailto]):not([class^=addfollow])')
      console.log(links)
    for (let i = 0; i < links.length; i++) {
      if (links[i].hostname != window.location.hostname) {
        links[i].target = '_blank'
        links[i].rel = 'noopener nofollow noreferrer'
      }
    }
  }
```
This adds `target="_blank"` to all links on the page.
It works fine, but when I hit 404 (I have 404 layout for that) and after returning back - scripts doesn't work, all links remains unchanged.

Is there's the way to fix this? Where shoould I put such scripts using Nuxt? Maybe placing it in `default.vue` layout is not good idea?

**Comment by qm3ster** [comment]
It's not good to modify the DOM directly in Vue.js.
Why don't you just have the links with these attributes already in the template?

**Comment by aedig** [comment]
@qm3ster any reason why you close this issue? Is this resolved?

> Why don't you just have the links with these attributes already in the template?

May be because I have 100500 such links? Is that got enought reason for you?

**Comment by hackuun** [comment]
@qm3ster any reason why you close this issue? Is this resolved?

> Why don't you just have the links with these attributes already in the template?

May be because I have 100500 such links? Is that got enought reason for you?

**Comment by hackuun** [comment]
You guys have admin here I guess? Are you sure you made right choice? I mean I just prayed in Twitter what a helpful community Nuxt has and then comes this?

**Comment by hackuun** [comment]
@qm3ster you obviously got an star fever after @Atinux followed you as single friend, ha-ha. 

Relax, ушлепок

**Comment by hackuun** [comment]
AGAIN: Nuxt position itself as a super-duper SEO-ready solution. 

I am talking about crutial part of any SEO - backlinking. This is vital. If you have no solution for that - then it's bad.

So I am asking you again - why this issue is closed and how it's different from other 2500 issue not really related to Nuxt also?

**Comment by Atinux** [comment]
@qm3ster please don't close the issue as fast, normally we wait for the author answer, and if we don't have any answer after few days we can close it :)

@hackuun I'm not sure the layout `mounted` property is the best way to put this script. When you are going back, if the `mounted` callback called?

**Comment by hackuun** [comment]
@Atinux no it is not. And I just checked - it works on first load only, so if I navigate to any page, not only 404, then links are not processed. So `default.vue` is definitely not the place for it. Then what should I use, Plugins maybe?

**Comment by qm3ster** [comment]
@Atinux I closed it as a non-nuxt issue. I am still going to followup.
I was writing a component to wrap an `<a>` so that @hackuun could use that.
Clearly the json isn't bringing in whole link html but just the link content.

Modifying the DOM instead of rendering the correct thing should be a last resort.

**Comment by qm3ster** [comment]
@hackuun can you please post the template where these links are created?

**Comment by hackuun** [comment]
@qm3ster sure, thanks for followup. And sorry of being rude. 

```html
<template>
  <section>
    <a href="http://google.com">Link</a>
    <a href="http://google.com" class="addfollow">Link</a>
    <nuxt-link to="/">inner link</nuxt-link>
    <a href="mailto:hey@timmyomahony.com">hey@timmyomahony.com</a>
  </section>
</template>
```

And this in `default.vue` wich is seems inpropriate

```js
mounted () {
    let links = document.querySelectorAll('a[href]:not([href^=mailto]):not([class^=addfollow])')
      console.log(links)
    for (let i = 0; i < links.length; i++) {
      if (links[i].hostname != window.location.hostname) {
        links[i].target = '_blank'
        links[i].rel = 'noopener nofollow noreferrer'
      }
    }
  }
```

**Comment by qm3ster** [comment]
And you have thousands of template like that, with the `href` value hardcoded into the template?
Where is it that you make them from the json?

**Comment by hackuun** [comment]
@qm3ster this is just example (which is also not working). Forget about JSON.

**Comment by qm3ster** [comment]
Try something like this https://glitch.com/edit/#!/silky-geranium?path=components/EvilLink.vue:5:0

**Comment by hackuun** [comment]
@qm3ster I can't use it, saying again. 

I will have JSON with HTML ready tags coming from API CMS editor. I will then use something like this

```html
<section class="wtf article-content" v-for="c in article.content" :key="c.text">
      <div v-if="c.text" v-html="c.text"></div>
      <img v-if="c.image" :src="`${$store.state.api}/static/resize-${c.image}`" alt="" class="lazy">
      <span v-if="c.caption">{{ c.caption }}</span>
</section>
```
`a` tags will be IN `<div v-if="c.text" v-html="c.text"></div>`. I can't use `:href` and slots!!!

**Comment by qm3ster** [comment]
I understand why you might want to do it with one script like that, but that is not how vue is done.
Another SEO problem would be that on first load from the server, your links wouldn't have these attributes applied.

**Comment by hackuun** [comment]
@qm3ster good catch. So `noreferrer` will not work, if only Nuxt will be able to render it on the server-side.

**Comment by hackuun** [comment]
But then, with your logic, then crawler will not see ANYTHING AT ALL, that comes from API JSON :smile:

**Comment by qm3ster** [comment]
No. SSR will render your `v-html` and send that as the html.
But it won't run your script, and even if it would:
1. There's no dom to operate on
2. If there were a dom, the changes would not get persisted into the html

**Comment by qm3ster** [comment]
You could do a find-and-replace in `c.text`, it would be quite trivial. Don't need to run a real html parser.

**Comment by hackuun** [comment]
Then may be some intermediary processing is possible on server-side? So Nuxt run this script before rendering tags? I mean not exactly this script, since it using DOM, but may be I could process my data somehow?

**Comment by hackuun** [comment]
> You could do a find-and-replace in c.text, it would be quite trivial

You mean on server-side?

**Comment by qm3ster** [comment]
On whichever side hits the api.

You can make an api completely independent from nuxt that processes these strings and caches them. That would definitely be the best option in the long run.

**Comment by qm3ster** [comment]
Are there vue templates inside the `c.text`? Or was the below a joke:

> ```vue
> <nuxt-link to="/">inner link</nuxt-link>
> ```

**Comment by hackuun** [comment]
@qm3ster I see what you mean. To deal with it on my CMS back-end. Well I wanted to make possible to apply changes on the fly, for example mark which links I want to process, which not.

**Comment by hackuun** [comment]
@qm3ster not sure what you mean. How `c.text` related to provided inner link? But no, there are no templates in `c.text` since unfortunately I can't find a way to make them work. Vue doesn't see this things like `nuxt-router` this way.

**Comment by hackuun** [comment]
But I wish there's a way to use templates from JSON API, so I could markup page more freely. This could be killer feature.

**Comment by qm3ster** [comment]
I meant a layer between the CMS and the clients, completely separate from the CMS. Like a cache/filter service.
You can still do it on the client. Can you give me a sample of a real(istic) `c.text`?

**Comment by hackuun** [comment]
Well for example `c.text`

```json
{
  "text": "<p>Lorem ipsum dolor, sit amet consectetur adipisicing <a href="https://evil.gr">elit</a>.</p>"
}
```

**Comment by qm3ster** [comment]
Maybe this?
https://glitch.com/edit/#!/silky-geranium?path=components/EvilHTML.vue:1:10
And don't call me evil, I am not the one creating backlinks :pizza:

**Comment by qm3ster** [comment]
Remember children! Never parse HTML with regular expressions! Or you might DIE.
```vue
<template>
<div v-html="_html" v-once></div>
</template>

<script>
  const rLink=/<a (.+?)>/gi
  const rHref=/href=(?:"([^"]+?)"|(\S+))/
  const regex=/^(:?https?:\/\/yourdomain|mailto)/
  const rClass=/class="?addfollow/
  export default{
    props:['html'],
    computed:{
      _html(){
        return this.html.replace(rLink,(match, p1)=>{
          if (rClass.test(match)) return match
          
          const [,url]=rHref.exec(p1)
          if ((!url) || regex.test(url)) return match
          
          return match.slice(0,-1)+' target="_blank" rel="noopener nofollow noreferrer">'
        })
      }
    }
  }
</script>
```

**Comment by hackuun** [comment]
@qm3ster backlinks - this is not my initiative, this is how this cruel world works (and also Google algorithm).

What's bad in regexes, beside the fact that it's a black magic that could turn me into the pumpkin? Is there particular downsides?

**Comment by hackuun** [comment]
So far, as I understand there's 3 solutions: 

1. Made all this stuff right in my WYSIWYG (none of them comes with out-of-the-box solution as far as I know)
2. Using the regex before saving in DB on my backend.
2. Using the same regex but on the client. 

May be other thoughts? And between this 3 which one is preferred? I guess the first one :smile: 
Anyway, thanks @qm3ster

**Comment by hackuun** [comment]
Damn, I only nee one shitty WP plugin that doing all this stuff :smile:

**Comment by qm3ster** [comment]
If you were parsing whole pages of html into a DOM.
The way I wrote it here, its just one linear pass and replace over a string, so it shouldn't be very bad at all.
It also won't easily mess up the HTML because it only returns two options.
The only risk is that it will miss some links, for example if it's written `href = "url"`(with spaces, not even sure if that's valid).

If this component will get reused (same instance with different html prop) you should remove the `v-once` directive. It's there to potentially improve performance by asserting that we won't ever want to update this component. But there's no reason, probably, because it's just one blob of html.

Let's close this issue now?

**Comment by hackuun** [comment]
@qm3ster already closed, thanks again!

**Comment by qm3ster** [comment]
You could run your script on mount of the actual components containing the html. Then you could load it async in an outer component and it would convert them exactly once. Also target it on the ref, not `document`.
The original problem was that it only runs once on layout and doesn't run again when a different inner page comes, or the same page is destroyed and reconstructed.
But then, no SSR for you.

I strongly suggest a microservice that uses postHTML or some other real html parser and gets the requests from your cms.
It would be easy to modify, and not depend on your cms and client languages at all.
Maybe I should write you one :thinking:
But for MONEY! :pizza:

**Comment by hackuun** [comment]
@qm3ster I was thinking just parse string when I am saving data that comes from my CMS admin front-end (also Vue app), right before it comes to MongoDB. Not sure what you suggesting. Raw data comes from CMS to DB > then in this microservice > then from microservice into client? I have simple Node app for all this stuff. Not sure why to run separate microservice?

I also checked few (paid) headless CMS providers, none of the offers this feature in their content editors. This is wierd, so they also leaving this up to user...

**Comment by qm3ster** [comment]
I thought it was a proprietary hosted CMS's API.
So CMS API > microservice > client/server.
If you're storing it in your own MongoDB you could apply your transforms before saving, like you said, or save both a processed and an unprocessed version, so you can change what transforms you use in the future (to not destroy the originals).

**Comment by awronski** [comment]
@hackuun This is actually interesting topic. I have similar situation when I have html from external system and I need to manipulate the links attributes.

Like said above you can change the html before saving to db. The pros is that the render phase will be fast and you don't need to care about it.  The cons is that maybe in the future you are going to need different sets of attributes. So the idea from @qm3ster the store the original content is good.

The other solution is to create your own Custom Directives. That way you will transform html on the fly in the SSR phase. So it will be seo friendly. And you could easily change the attributes anytime you like.

**Comment by qm3ster** [comment]
@awronski I already implemented the logic as components above. Not sure custom directives are necessary, since it's only used with specific components anyway. Still, performance is s downside, such as keeping two copies of the HTML in memory (if we imagine it's huge, which it's probably not)
Non-destructive server buildstep or cached pull is definitely the way to go.
In cached pull, just drop the processed bodies collection every time you change the algorithm and you'll be golden.
At most it'll make an article's first hit slightly longer, but less so than the slowdown for every hit of every article with clientside match and replace on a mid-range mobile cpu.

**Comment by qm3ster** [comment]
Then, if you have an API that exposes this HTML on its own endpoint and not inside a json, you can [GO NUTS LIKE AN ABSOLUTE PERFORMANCE PERVERT AND STREAM IT INTO A SEAMLESS IFRAME](https://jakearchibald.com/2016/fun-hacks-faster-content/)
You could also cache these on your proxy/cdn {instead of/in addition to} a MongoDB collection.

**Comment by awronski** [comment]
@qm3ster 

> Non-destructive server buildstep
What do you mean by that? Could you explain it more?

>In cached pull, just drop the processed bodies collection every time you change
How would you implement it? In the cms api triggered by bodies change, or on the fly in the nuxt when first request miss the cache?

I will appreciate more info. What lib would you recommend for it?

Thanks!

**Comment by hackuun** [comment]
@awronski this is interesting topic indeed. Specifically I am looking for ability for non-tech content managers, authors adjust attributes from gui (not from Nuxt, but from admin app, for example). I was hoping some Headless CMS providers offers such features, but can't find anything. Did you tried https://tipe.io ?

**Comment by qm3ster** [comment]
It seems they just started? Can't find pricing, even when logged in?
How are you currently deployed?

**Comment by qm3ster** [comment]
@awronski, our boi'z CMS is his own admin application looking at his MongoDB, probably making use of a premade WYSIWYG editor, and then he also has a nodejs api server serving his MongoDB content.
Hence, when saving edits to a post in the CMS:
- If doing it on save:
    - Create/edit article in "CMS"
        1. Save the new version in `srcArticles` collection
        2. Process the new version with filters
        3. Save/overwrite the new processed version in `distArticles` collection.
    - Update filters
        1. Run the overwrite process for the whole collection.
- If doing it on pull:
    - Create/edit article in "CMS"
        1. Save the new version in `srcArticles` collection
        3. Delete the new processed version in `distArticles` collection.
    - Update filters
        1. Drop the whole goddamn`distArticles` collection.

As you can see, the second option is easier to implement and offers more decoupling from CMS, at a cost of negligible performance (first hit latency, not server utilization, it actually saves on processing articles no one gives a :hankey: about that you keep editing 5 times per minute)

**Comment by hackuun** [comment]
> It seems they just started? Can't find pricing, even when logged in?
How are you currently deployed?

Yes, they're new. Last time I checked they had closed beta. Have no idea about the pricing, I should check it. Currently I am using my own backend. There are also alternatives, like Storyblok, Prismic etc. As far as I checked, they have no solution for that, but I should tale a look again.

**Comment by hackuun** [comment]
@qm3ster sorry If I'm missing something again, but still. What if we can do it on Nuxt server-side? Like middleware or smthng. Proceed this data in `asyncData` so crawler will receive links with attributes already.

**Comment by qm3ster** [comment]
@hackuun what about when you go to the next article? The processing would happen on the client. For every client. Every time.
Doesn't that SUCC?

**Comment by hackuun** [comment]
@qm3ster well, you told before that it's not so computational consuming...Find and replace I mean. I agree it's not very cool. But if I will use external service I see no other way right?

**Comment by qm3ster** [comment]
Is your goal to not have MongoDB at all?

**Comment by awronski** [comment]
@qm3ster 

> what about when you go to the next article? The processing would happen on the client. For every client. Every time. 

That's fair point. But is always depends on users real traffic. Maybe for his case the overhead won't be significant. 

Anyway, I will play with nuxt server side caching and if success publish examples. I wonder what I can do with this.

**Comment by qm3ster** [comment]
@awronski any news?
