### ISSUE TITLE
Rename issue tags?

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#2913]
![image](https://user-images.githubusercontent.com/10551234/36763431-93fb8d02-1c30-11e8-81bb-721fe1c5a17c.png)
Is this what we mean by `type: help wanted`? If so, should rename to make use of this.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2529">#c2529</a>)</em></sub></div>

**Comment by manniL** [comment]
Had been done.
