### ISSUE TITLE
get the user's IP in the first request

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#2914]
How to get the user's IP in the first request, because it is rendered on the server side, I can only get the IP address of the server and not get the IP of the user

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2530">#c2530</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Something along the lines of:
```js
const ip = 
  req.headers['x-forwarded-for'].split(',').pop() || // From proxy headers, can be spoofed if you don't have a proxy in front of your app, so drop it if your app is naked.
  req.connection.remoteAddress || 
  req.socket.remoteAddress || // socket is an alias to connection, just delete this line
  req.connection.socket.remoteAddress // no idea where this might be a thing, just delete this line
// probably add a default at the end here, although there shouldn't be a case when req.connection.remoteAddress is unset.
```
## so, tl;dr:
### If you likely have a proxy in front of your app:
```js
const ip = req.headers['x-forwarded-for'].split(',').pop() ||
  req.connection.remoteAddress
```
### If your app is naked to the internet:
```js
const ip = req.connection.remoteAddress
```

**Comment by fengjiel** [comment]
Thank you for your attention, your method can be used in the client request, but once I send the request in the asyncData, the request will be done on the server, and get the wrong user IP address.

**Comment by qm3ster** [comment]
You're sending a request from the client.
Hence, whatever API you're hitting inside the asyncData should look at the client request object. (On the server)

**Comment by canyoudev** [comment]
Yes, it was the headers, I fixed it.

**Comment by fengjiel** [comment]
That's a good solution, thank you very much! @canyoudev
