### ISSUE TITLE
[Bug Report] Nuxt的spa模式下, style中使用background的url语句, dev状态可以正常访问, build之后访问报错.

### ISSUE THREAD

**Issue by xachary** [nuxt/nuxt.js#2916]
### Nuxt version
1.3.0

### Vue version
2.5.13

### OS/Browsers version
64.0.3282.167

### Reproduction Link
[https://github.com/xachary/nuxt-spa-style-url-build-error](https://github.com/xachary/nuxt-spa-style-url-build-error)

#### install dependencies
$ npm install

#### serve with hot reload at localhost:3000
$ npm run dev-spa

#### build for production and launch server at localhost:3001
$ npm run build-spa
$ npm run start-spa

### What is Expected?
'dev version' and 'build version' is both ok.

### What is actually happening?
You can see 'build version' showing error message.
![image](https://user-images.githubusercontent.com/16830398/36776578-437ab616-1ca1-11e8-9aa9-0440389ed5eb.png)

But if you delete one of 'background-image: url('../assets/img.png');' in '/pages/index.vue', build again, then you can see 'build version' is ok again.
![image](https://user-images.githubusercontent.com/16830398/36776479-e266f240-1ca0-11e8-9e02-97ddd65fc2de.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2531">#c2531</a>)</em></sub></div>

**Comment by henyuan** [comment]
我怎么感觉你是css里的地址配错了呢?
```
background-image: url('~assets/img/xxx.jpg');
```
我这样配是没错的.你可以试试.

**Comment by xachary** [comment]
@henyuan 你有没有pull下来这个git项目测试? 这个bug, 条件比较奇怪. 注释掉.test{...}的background-image就变正常了. 目测你没有拿我的git测试, 所以重现不了的.

**Comment by henyuan** [comment]
我测试了,确实是bug,有解决办法,官方说下个版本也会修复.
具体都在这里[iss2551](https://github.com/nuxt/nuxt.js/issues/2551)

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
