### ISSUE TITLE
Public Path (Build) requires a trailing slash

### ISSUE THREAD

**Issue by ekoeryanto** [nuxt/nuxt.js#2919]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2534">#c2534</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Yes, the default is
https://github.com/nuxt/nuxt.js/blob/f412827570f674e667c03e42af339cb9f252d0de/lib/common/options.js#L202
Where would you like this to be documented better?

**Comment by clarkdo** [comment]
I'll close this issue because long time not response, if any concerns, please let me know, I can reopen it.
