### ISSUE TITLE
Flash of Unstyled Content

### ISSUE THREAD

**Issue by BryanARivera** [nuxt/nuxt.js#292]
On page refresh I am seeing a FOUC.  

How can this be fixed?

**Comment by BryanARivera** [comment]
Only a prob in dev, prod build takes care of it.

**Comment by LasaleFamine** [comment]
I was opening an issue too. 
I think this should be mentioned somewhere...

**Comment by BryanARivera** [comment]
Granted it was in the FAQ.  But there is a good amount of docs to read before that.  It would be good to mention somewhere in the getting started section.

**Comment by LasaleFamine** [comment]
Basically it's the first thing you see when completed the getting started and run the dev environment. It's not the end of the world of course, but could be misleading for some minutes I think.
