### ISSUE TITLE
Issue with global plugins?

### ISSUE THREAD

**Issue by cloudbluedigital** [nuxt/nuxt.js#2922]
Hi!

In my nuxt.config.js I am loading a 'global' js where everything I need everyone is defined. I am doing it like this:
```
  plugins: [
    {
      src: '~/plugins/global',
      ssr: false
    }
    ],
```

and global is really just this:

```
import Popper from 'popper.js/dist/umd/popper.js';
import Vue from 'vue';
import VueRouter from 'vue-router';
import Axios from 'axios';
import Form from './forms/form.js';
import Global from './globals/globals.js';


try {
  window.$ = window.jQuery = require('jquery');
  window.Popper = Popper;
  require('bootstrap');
} catch (e) {}


window.Vue = Vue;
window.VueRouter = VueRouter;
window.Form = Form;
window.Global = Global;
window.axios = Axios;
```

Now what is the problem.

on /login I have
```
export default {
  data() {
    return {
      success: false,
      failure: false,
      username: '',
      baseURL: process.env.API_URL,
      form: new Form({
        email: '',
        password: ''
      })
    }
  },
```

But of course, Form is defined globally so that's fine. It isn't, really. If you run `npm run dev` for the first time and go to localhost:3000 and then go to /login it is fine. If I stay on /login page, make a change anywhere so that it re-compiles. I get an error saying that Form class is not defined in /login. But if I go back to root '/' and then to '/login' it works. Is there any way to avoid this behavior?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2536">#c2536</a>)</em></sub></div>

**Comment by qm3ster** [comment]
You should not put anything on window. There is no window object on the server. Just import Form where you need it, then it won't make all pages obese.
You should not import everything into one plugin. Please see [the meaning of plugin in nuxt](https://nuxtjs.org/guide/plugins).
Maybe use [`nuxt-community/axios-module`](https://github.com/nuxt-community/axios-module)
Please take a look at how to [use the popular and well-supported `bootstrap-vue` package to idiomatically import Bootstrap into a nuxt project](https://github.com/nuxt/nuxt.js/issues/1417).

**Comment by cloudbluedigital** [comment]
well I am not importing everything @qm3ster but for example the Form class needs to be available on every single page. Each page has a form or some kind of data access. There was no problem with 'normal vue' surely there is a way to do it here too

**Comment by qm3ster** [comment]
Did you have SSR in 'normal vue'?
You don't need to make a plugin to have a **class** available on every page, only if you needed access to a shared instance. You can just import it where you use it. Webpack will only include it once.
If it is really very common, you can also add './forms/form.js' to the vendor chunk through the `build.vendor` option of `nuxt.config.js`

**Comment by manniL** [comment]
This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2536">#c2536</a>)
