### ISSUE TITLE
base

### ISSUE THREAD

**Issue by reskwer** [nuxt/nuxt.js#2923]
Is there any possibility to make base dynamic, without hardcode

```
router:{
    base: '/my-project/dist/'
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2537">#c2537</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Is your project served at `https://example.org/my-project/dist/**`?
It's used in the config, so, when initializing the Nuxt object, so not currently, no.
What's the usecase?

**Comment by reskwer** [comment]
For example there are 3 servers, and on all three different base for everyone it is necessary to generate separately, and it honestly strongly strains :((
`https://example.org/my-project/dist/`
`https://example.org/dist-test/**`
`https://example.org/project/dist/**`

**Comment by qm3ster** [comment]
Perhaps the gentleman will be interested in some aleviation to their strain?
```js
import Nuxt from 'nuxt'
import config from './nuxt.config.js'

const deployments = {
  assburgers: ['https://example.org', 'my-project/dist'],
  testos: ['https://example1.org', 'dist-test'],
  baptain: ['https://example2.org', 'project/dist']
}

const config = {}

for (const prop of ['env', 'router', 'generate']) {
  if (!config[prop]) {
    config[prop] = {}
  }
}

for (const dep in deployments) {
  const [domain, base] = deployments[dep]
  config.env.baseUrl = domain
  config.router.base = `/${base}/`
  config.generate.dir = dep

  const nuxt = new Nuxt(config)
  nuxt.generate()
}
```
