### ISSUE TITLE
Layout inheritance and page transitions

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt.js#2924]
When two pages use a different layout, the property `transition` has no effect. I could use the default layout for all my pages and replicate the secondary navigation component on each page but in that case, first it's repetitive and secondly, the transition applies to the same component on each page (which is normal since the transition is applied to the outer element) whereas I don't want it to be animated. 

I also tried with [slots](https://github.com/nuxt/nuxt.js/issues/785#issuecomment-303999589) but it works only for nested components of a single layout, not with layout inheritance. You can't have two layouts inheriting from one single layout with slots.

# Proposal

`layouts/default.vue`
```vue
<template>
  <div>
    <nuxt-section name="nav">
      <nav class="primary-nav">
        ...
      </nav>
    </nuxt-section>

    <nuxt/>

  </div>
</template>
```

`layouts/shapes.vue`
```vue
<template>
  <div>
    <nuxt-section name="nav">

      <nuxt-parent/>

      <nav class="secondary-nav">
        <nuxt-link to="/shapes/squares">Squares</nuxt-link>
        <nuxt-link to="/shapes/ovals">Ovals</nuxt-link>
      </nav>
    </nuxt-section>

    <nuxt/>

  </div>
</template>

<script>
export default {
  extends: 'default'
}
</script>
```

`pages/shapes/squares.vue`
```vue
<template>
  <h1>Squares</h1>
</template>

<script>
export default {
  layout: 'shapes'
}
</script>
```

`pages/shapes/ovals.vue`
```vue
<template>
  <h1>Ovals</h1>
</template>

<script>
export default {
  layout: 'shapes'
}
</script>
```

This would become:

`/shapes/squares`
```vue
<div>
  <nav class="primary-nav">
    ...
  </nav>
  <nav class="secondary-nav">
    <a href="/shapes/squares">Squares</a>
    <a href="/shapes/ovals">Ovals</a>
  </nav>
  <h1>Squares</h1>
</div>
```

`/shapes/ovals`
```vue
<div>
  <nav class="primary-nav">
    ...
  </nav>
  <nav class="secondary-nav">
    <a href="/shapes/squares">Squares</a>
    <a href="/shapes/ovals">Ovals</a>
  </nav>
  <h1>Ovals</h1>
</div>
```

What do you think? Do you plan to support layout inheritance in a near future. This would be very helpful.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2538">#c2538</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Have you considered [Nested Routes](https://nuxtjs.org/guide/routing#nested-routes) for this usecase?

**Comment by lucpotage** [comment]
In my example, nested routes may work but there are situations where it's not sufficient.
You want flat routes:
- `/squares` instead of `/shapes/squares`
- `/ovals` instead of `/shapes/ovals`

You use a module that already manipulates the router, let's say `nuxt-i18n` in my case.

To me, we should not have to customize the router for layout inheritance stuff. I don't see why a router should be necessarily 'binded' to a layout architecture.

**Comment by qm3ster** [comment]
It's blinded because of the Filesystem API. You can:
1) Completely ignore the Filesystem API and provide your own router with [`nuxt-community/router-module`](https://github.com/nuxt-community/router-module)
2) Pass a function to `extendRoutes()` in a nuxtmodule and replace `\^/shapes\` with `''`
Will this work? Quite possibly not! What do the route objects for nested routes even look like? Only trying will tell! (Please try this and bring a route object with you, I want to know!)

**Comment by mootari** [comment]
> What do the route objects for nested routes even look like?

Like a normal route from what I can tell, only that `matched` (and `meta`) also contains the parent routes.
