### ISSUE TITLE
nuxt generate --watch

### ISSUE THREAD

**Issue by alinnert** [nuxt/nuxt.js#2928]
I know that issue #52 exists, but I'm not sure if it's a good idea to add a comment there.

I stumbled over this because I think the `nuxt generate --watch` command is what I need. I'm creating a static site/blog using Nuxt. I create a page for every blog post using the config property `generate.routes`. (there I create a route for every `.md` file in another folder in the project) There I pass all data I need to the page's `asyncData` method via `payload`.

Now this works fine if I use `nuxt generate`. But if I just use `nuxt` (which is just way more useful while development) the `payload` parameter is `undefined`. As far as I understand it only get's passed in the `generate` process because that's the only time that `generate.routes` gets processed.

Now the obvious solution would be `nuxt generate --watch` ‒ if it was a thing. I figured that I can also fetch the blog post's content inside the `asyncData` method. But it feels like I'm doing the work twice. Also this makes me wonder what's the point of the `payload` parameter.

Since generating static pages for e. g. GitHub Pages is officially supported this doesn't feel like an edge case to me. Or what do you think? Are there other solutions to this problem?

**Comment by qm3ster** [comment]
Personally, I'd go with the following, strongly inspired by the [`payload` example in the docs](https://nuxtjs.org/api/configuration-generate/#speeding-up-dynamic-route-generation-with-code-payload-code-).
```js
module.exports = {
  generate: {
    routes: function() {
      return require('./myData.js').posts.map(postData => ({
        route: '/posts/' + postData.id,
        payload: postData
      }))
    }
  }
}

// Now we can access the payload from /users/_id.vue like so:
export default {
  async asyncData({ params, error, payload }) {
    if (payload) return { post: payload }
    else return { post: require('./myData.js').posts[params.id] }
  }
}
```

**Comment by qm3ster** [comment]
But if your payload is truly local, you might not want to pass a payload at all, and just do this instead:
```js
module.exports = {
  generate: {
    routes: function() {
      return require('./myData.js').posts.map(
        postData => '/posts/' + postData.id
      )
    }
  }
}

//  /posts/_id.vue:
export default {
  async asyncData({ params, error }) {
    return { post: require('./myData.js').posts[params.id] }
  }
}
```

**Comment by alinnert** [comment]
hm... yes, I think the second solution good enough. Technically I just read and parse local markdown files.

**Comment by qm3ster** [comment]
To be honest, I am not sure it's a good solution now.
What would happen on clientside navigation?
Please post your current code in these two sections.

**Comment by alinnert** [comment]
My source code is at https://github.com/alinnert/linnertmedia
It's a very basic setup, the project is at a very early stage in development. So, there's not much additional code aside from "hello world". I followed the setup introduction "Starting from scratch". Other than that there's a `nuxt` folder that contains my custom code to read and parse `.md` files. (I haven't found a proper name yet.)
The page file I'm fiddling around with is `~/pages/blog/_slug.vue`.

I've changed my code to look almost like in your example. But running `nuxt` now throws an error that it can't resolve the dependency `fs` (which I use to read the content of `.md` files).

This error gets thrown because I execute an imported function that uses `fs` from inside `asyncData()`.
This error, however, does not get thrown if I call that function from `nuxt.config.js`.
Also, it only complains about `fs`, but not about `path`. I don't really understand what's happening here.

I mean, I could use `require()` instead of `fs.readFile()` to read the content of a `.md` file. But this only allows me to read one specific file, not the content of a folder (`fs.readdir`) to generate e.g. a list of blog posts.

**Comment by qm3ster** [comment]
Yeah, it wouldn't work like this, you'd end up shipping things like `gray-matter` to the client.
Why don't you pre-process your posts into html fragments and expose them as an endpoint?

**Comment by alinnert** [comment]
I'm not sure if I can follow you. What kind of endpoint? But this also sounds like it's getting a too complex setup for a simple static website.

**Comment by qm3ster** [comment]
I left you a PR: https://github.com/alinnert/linnertmedia/pull/2
