### ISSUE TITLE
mac 上安装完nuxt 后报错，麻烦谁给解决下

### ISSUE THREAD

**Issue by ITCNZ** [nuxt/nuxt.js#2929]
Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! mynuxt@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mynuxt@1.0.0 dev script 'nuxt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mynuxt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mynuxt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mynuxt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhouhaipeng/mynuxt/npm-debug.log

**Comment by paulgv** [comment]
Nuxt requires Node 8 or later: https://github.com/nuxt/nuxt.js/blob/dev/package.json#L56

**Comment by ITCNZ** [comment]
Thanks!
