### ISSUE TITLE
Compilation successful in negative duration

### ISSUE THREAD

**Issue by chanlito** [nuxt/nuxt.js#2930]
<img width="307" alt="screen shot 2018-03-02 at 6 39 34 pm" src="https://user-images.githubusercontent.com/15667259/36897432-167681f0-1e49-11e8-9522-aafb6ba227d6.png">

Am I the only one getting this?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2543">#c2543</a>)</em></sub></div>

**Comment by benfavre** [comment]
Same here

**Comment by yoyo837** [comment]
Same here

**Comment by qm3ster** [comment]
Same here

**Comment by pi0** [comment]
This is a known issue with nuxt 1.x :(

But good news is that is will be resolved soon with upcoming version :)

**Comment by manniL** [comment]
Should be resolved with `nuxt-edge`.
