### ISSUE TITLE
Dynamic route without index file

### ISSUE THREAD

**Issue by pimhooghiemstra** [nuxt/nuxt.js#2932]
I would like to have the following URL
/recipes/:slug
to show a page with a recipe.

However, I don't want a page under URL /recipes.

If I understand the docs correctly this is not possible? If I create the folder structure (in pages/)
/recipes
________/_slug
________________/index.vue
=> the slug becomes optional and visiting /recipes would also render the index.vue but without a slug.
 
If I have the structure
/recipes
________/_slug
________________/index.vue
________/index.vue
=> the slug becomes required, but now I get a URL /recipes for which I don't want a page.

Question: is this possible using the automated route generation in Nuxt or should I create my router file myself?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2547">#c2547</a>)</em></sub></div>

**Comment by paulgv** [comment]
Try with this files structure:
```
recipes/
├── _slug.vue
```

And use [`validate` method](https://nuxtjs.org/api/pages-validate) in `_slug.vue` to ensure the slug isn't empty.

**Comment by pimhooghiemstra** [comment]
@paulgv thanks for the suggestion. I added this know and it works: My error view is loaded in which I load my 404 component.

However, one question remains: would search engines index this URL: /recipes? because ultimately I think that should not be the case.

**Comment by paulgv** [comment]
Search engines don't index 404 :)
