### ISSUE TITLE
webpack config for Jetbrains Webstorm

### ISSUE THREAD

**Issue by shrpne** [nuxt/nuxt.js#2936]
Webstrom has an option to set path to webpack config. But when I set it to nuxt's webpack config it throws error:
> Can't analyse base.config.js: coding assistance will ignore module resolution rules in this file.
Possible reasons: this file is not a valid webpack configuration file or its format is not currently supported by the IDE

I tried to specify `webpack/base.config.js`, `webpack/client.config.js`,  `webpack/server.config.js` with no luck.

Maybe you extract parts of webpack config to separate file which Webstorm can analyze?

I want it to teach webstorm to understand `~/` aliases

**Comment by uto-usui** [comment]
I set webpack.config.js on the project root for WebStorm.
That file is invalid for Nuxt and it is valid only for WebStorm.

```
module.exports = {
  resolve: {
    // for WebStorm
    alias: {
      '@': path.resolve(__dirname),
      '~': path.resolve(__dirname)
    }
  }
};
```

**Comment by davestewart** [comment]
Does this work for `.vue` files?

JetBrains say it won't:

- https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000927179-Is-there-a-canonical-way-to-set-up-prefixed-aliases-?page=1#community_comment_360000149560
