### ISSUE TITLE
How to conditionally set variables in PROD and DEV?

### ISSUE THREAD

**Issue by hackuun** [nuxt/nuxt.js#2940]
Hi there. What's the best way to have one url for prod and another for dev with Nuxt? I searched Docs but can't find anythng.

For example, I have this `axios.post('http://localhost:7777/form', payload)`
Hot to change url when I run `npm run build` or `npm run generate`? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2551">#c2551</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Have you tried setting the base url of your axios where you create it, so you don't have inline absolute URLs all over the place, only relative for your own domain?
`process.env.NODE_ENV` should work.
See the output, but there's a big chance that babel applies one or both of:

- https://babeljs.io/docs/plugins/transform-node-env-inline/
- https://babeljs.io/docs/plugins/transform-inline-environment-variables/

And if it doesn't, you can easily add them yourself.

**Comment by hackuun** [comment]
@qm3ster actually, I tried `axios-module` but it doesn't work in nuxtServerInit for some reason -  https://github.com/nuxt-community/axios-module/issues/111

Usually I use `env` in `nuxt.config` to set variables (not hardcode like example), but I still I have no idea how to change in in Prod? Not sure how to use `process.env.NODE_ENV` in this case. You mean I should set conditional statement somewhere? What if I want to use `env`? Is there native Nuxt way to set this things?

**Comment by manniL** [comment]
In my package.json, I set the NODE_ENV: 

```
 "scripts": {
    "dev": "NODE_ENV=dev nuxt",
     ...
  }
```

Then I can use it in nuxt.config.js to set the baseURL of axios for example.
Otherwise, you can also set env variables when starting nuxt to override the axios URLs.

**Comment by joealden** [comment]
Even though this is an issue outside of this repo (and not related to this issue in particular), I believe that the maintainers should consider banning @hackuun from any activity here. If you haven't seen, he has been extremely anti-semitic towards @sdras on twitter, and I personally don't think that he deserves any kind of help if he is going to behave as awfully as he has.

**Comment by qm3ster** [comment]
@joealden I don't think that violates [code of conduct](https://github.com/nuxt/nuxt.js/blob/dev/CODE_OF_CONDUCT.md#scope).
No one is under any obligation to help him, but there's no grounds for banning him for his actions outside the repo.

I am not sure if it is appropriate for you to be posting this here, but please don't think I am taking sides.

**Comment by joealden** [comment]
I understand, I just don't think that it is right that someone who gives such abuse to anyone, especially to a member of the Vue.js core team, shouldn't be punished.

I am sorry for mentioning this on an unrelated issue, I was just upset to see that this person had any involvement in the projects that Sarah has had such a positive impact on.

**Comment by hackuun** [comment]
1. Sarah Drasner is anti-white. 
2. I asked her like 10 questions which she ignored, then I one time called her "whore". That is literally it. Nothing particularly anti-semitic. Because she is super annoying for me, yes.
3. You really think that banning me here will stop me from asking questions and participating here in any other form?

**Comment by joealden** [comment]
I'm not going to engage in conversation with you, it's not the place for it and you are clearly not going to see it from anyone elses point of view.

**Comment by hackuun** [comment]
That exactly the point. Beside the fact it's you the one that doesn't see anything beside Jewish propaganda. Go watch another propagandist Marvel movie than starter serious talks with serious people.
