### ISSUE TITLE
accessing attributes on the matched component

### ISSUE THREAD

**Issue by dfee** [nuxt/nuxt.js#2941]
I saw [this issue](https://github.com/nuxt/nuxt.js/issues/720#issuecomment-301745685) about retrieving metadata per page (effectively accessing `this.$route.matched[0].components.default.options`) but couldn't find any documentation as to why the key we're looking at on `this.$route.matched[0].components` is called `default` – and whether that's stable and I can rely on it.

I couldn't find anything in the [`vue-router`](https://router.vuejs.org/en/api/route-object.html) docs for this, though it briefly mentions that `matched` is an array of `Route Record` copies. Looking at my `/.nuxt/router.js` file, I see this:
```js
export function createRouter () {
  return new Router({
    mode: 'history',
    base: '/',
    linkActiveClass: 'nuxt-link-active',
    linkExactActiveClass: 'nuxt-link-exact-active',
    scrollBehavior,
    routes: [
		{
			path: "/about",
			component: _3b78a70e,
			name: "about"
		},
		{
			path: "/categories/:id?",
			component: _77c04516,
			name: "categories-id"
		},
		{
			path: "/",
			component: _5b3081d3,
			name: "index"
		}
    ],
    
    fallback: false
  })
}
```

Which isn't even setting a components option, much less one named `default`.

The second part (and this is maybe more of a Vue specific question) is how can I rely on `<component>.options`? I can't find any documentation anywhere (Vue, Nuxt, etc.) which states that this is an attribute that carries the user supplied options from `Vue.component`. Is this a stable api?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2552">#c2552</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Here is the [documentation on the $options property](https://vuejs.org/v2/api/#vm-options).
It includes all the standard stuff Vue actually cares about, as well as any custom options you add.

My guess is that to support [Named Views](https://router.vuejs.org/en/essentials/named-views.html)
```js
const router = new VueRouter({routes: [
  {
    path: '/',
    components: {
      default: Foo,
      a: Bar,
      b: Baz
    }
  }
]})
```
vue actually stores
```js
const router = new VueRouter({
  routes: [
    {
      path: '/user/:userId',
      component: User
    }
  ]
})
```
as
```js
{
  path: '/user/:userId',
  name: 'user',
  components: { default: User }
}
```

**Comment by qm3ster** [comment]
Also, options are applied when instantiating a component.
These are not instances of components but just their classes/constructors.
(Actually, in this case, these are async functions that fetch and compile and instantiate the component)
And that's why you won't see anything like options here.

**Comment by dfee** [comment]
Alright – so if I'm understanding correctly, when the component constructor is called, Vue maps the prototype's `options` to the instances `$options` property. Right?

As for your second comment about "These are not instances of components but just their classes/constructors." – you're referring to what's in `this.$route.matched[0].components`, right? If so, I've read that and so it makes sense.

However, if I have a route `/products/1234` which maps to a page component that loosely looks like:
```js
export default {
  computed() {
    name(state) { return state.products[this.$route.params.id].name };
  }
};
```

I wouldn't be able to get access to the `name` property from a `$route` object right?

As for `default` being the "default" name of a component for named views, that looks good to me.

**Comment by qm3ster** [comment]
You might from the route, just never from the router.
And I meant that `_3b78a70e`, `_77c04516` and `_5b3081d3` are functions that return the constructor.

**Comment by galvez** [comment]
Closing this as it's probably best accomplished with [https://github.com/nuxt-community/router-module](https://github.com/nuxt-community/router-module)
