### ISSUE TITLE
Env vars not loaded when running ava

### ISSUE THREAD

**Issue by robyedlin** [nuxt/nuxt.js#2943]
I upgraded from 1.0.0-rc8 to 1.0.0, and now the default e2e test with Ava won't load in env vars.

**Comment by qm3ster** [comment]
The current version is 1.4.0.
Why are you running the tests, are you working on `nuxt.js`?

**Comment by robyedlin** [comment]
1.4.0 doesn't work either. 

I'm running e2e tests on my app.

https://nuxtjs.org/guide/development-tools#end-to-end-testing

**Comment by qm3ster** [comment]
So. You are doing something along the lines of `BARIABLE=true npm test`, which uses the `"test"` npm script. And your `test/index.test.js` does run. But inside it, `process.env.BARIABLE` is `undefined`?

**Comment by robyedlin** [comment]
Kind of. All env vars are loaded from nuxt.config.js. At 1.0.0-rc8, env vars were working. My test hits an axios endpoint and the base url is not being set.

**Comment by qm3ster** [comment]
So, it's `undefined` inside `nuxt.config.js`, but only when using `ava`?
How does `nuxt.config.js` get involved, is it required inside `test/index.test.js` like in the example?

**Comment by robyedlin** [comment]
Here's the nuxt.config.js: https://github.com/state-of-the-dapps/sotd-www/blob/master/nuxt.config.js

And the test: https://github.com/state-of-the-dapps/sotd-www/blob/master/test/routes.spec.js

Thanks for your help.

**Comment by robyedlin** [comment]
nuxt.config.js should be loaded when loading nuxt programmatically.

**Comment by qm3ster** [comment]
I've got a BIG hecking suspect that this happens due to parallel spawning of tests.
https://github.com/nodejs/node/issues/12986#issuecomment-301102566

**Comment by qm3ster** [comment]
YAY DAPPS

**Comment by robyedlin** [comment]
Yeah! So maybe I need to load in the env directly during testing? Not sure...

**Comment by qm3ster** [comment]
What I MUST say is that your `ava` is OLD.

**Comment by robyedlin** [comment]
Still a problem on Ava 0.25.0

**Comment by qm3ster** [comment]
Won't tell you to try `1.0.0-beta.3` because that requires a bit of rewriting as I can see.

**Comment by qm3ster** [comment]
Node version?
Yarn version?
OS?

**Comment by robyedlin** [comment]
Node: 8.9.1
Yarn: 1.3.2
MacOS: 10.13.3, and Docker circleci/node:8.9.1

**Comment by qm3ster** [comment]
Thank you for your patience, an educated person like @pi0 or @clarkdo will be with you shortly.

**Comment by robyedlin** [comment]
No, thank YOU. You've been great.

**Comment by clarkdo** [comment]
@qm3ster 
Thank you so much for you investigation and all the useful information.

@robyedlin 
If https://github.com/state-of-the-dapps/sotd-www/tree/master is the branch which can reproduce the issue, I think the issue should be that `nuxt.config.js` was not loaded successfully and the `try..catch` omitted the exception, if you remove the `try...catch`, the error is:

````
[Error: Couldn't find preset "es2015" relative to directory "sotd-www"]
```

You can just remove the `babel.presets` or add `babel-preset-es2015` to devDependencies.

If I missed anything, pleas let me know.

**Comment by robyedlin** [comment]
Removing babel presets worked. Thanks so much!!!

**Comment by robyedlin** [comment]
@clarkdo which try..catch did you remove to test that?

**Comment by clarkdo** [comment]
@robyedlin Sorry for my unclear explanation, codes are https://github.com/state-of-the-dapps/sotd-www/blob/master/test/routes.spec.js#L14

**Comment by robyedlin** [comment]
Ah yes missed that, sorry!

Thanks, yours is too! :)

**Comment by qm3ster** [comment]
How did I miss that :disappointed:
This is what I get for not e2e testing my projects. :man_shrugging:
