### ISSUE TITLE
<img :src> is not loading files from /static

### ISSUE THREAD

**Issue by eichgi** [nuxt/nuxt.js#2946]
When I load images with 
`<img src="~/static/proyectos/rovix_1.png" width="100%"> is working ok. `

But when I change to:
`<img :src="image" width="100%">`
being img="~/static/proyectos/rovix_1.png"
is not working.

What do I need to do for fixing it?

**Comment by fengjiel** [comment]
```
<img :src="image" width="100%">
 image="/proyectos/rovix_1.png"
```

**Comment by qm3ster** [comment]
```
<img :src="image" width="100%">
 image=require('~/assets/proyectos/rovix_1.png')
```
This could be fun too, in the sense that it would avoid busting cache if you reorganize your images and have `file-loader` name them strictly by content hash.
