### ISSUE TITLE
Object.values error on iOS9

### ISSUE THREAD

**Issue by gerwinov** [nuxt/nuxt.js#2948]
Hi,

I built my Nuxt project with the following configuration:

```
build: {
    babel: {
      presets: function(isServer) {
        return [
          [
            'vue-app', {
              useBuiltIns: true,
              targets: isServer ? { node: 'current' } : {ios_saf: 9, uglify: true}
            }
          ]
        ];
      },
      plugins: [
        ["transform-imports", {
          "vuetify": {
            "transform": "vuetify/es5/components/${member}",
            "preventFullImport": true
          }
        }]
      ]
    },
    vendor: [
      '~/plugins/vuetify.js',
      'moment',
      'babel-polyfill'
    ],
    extractCSS: true,
    /*
    ** Run ESLint on save
    */
    extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      if (ctx.isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vuetify/]
          })
        ]
      }
    }
  }
```

When I run the project on my iPad 3 (iOS 9) I receive the following errors:

<img width="1158" alt="schermafbeelding 2018-03-04 om 22 00 27" src="https://user-images.githubusercontent.com/1408309/36966631-ac12bc7c-205d-11e8-935f-55ce73db4bec.png">

The code runs fine (without errors) on the latest version of Chrome. How can I get this to work on iOS9?

Thanks in advance for your help!

Regards,
Gerwin

**Comment by vedmaque** [comment]
You should probably include `babel-polyfill` before `vuetify`
```
vendor: [
      'babel-polyfill',
      'moment',
      '~/plugins/vuetify.js'
    ],
```
Not sure if it helps with other syntax errors

**Comment by gerwinov** [comment]
Thanks for your quick reply!

The "Object.values" error is gone; thanks! 

The other 3 syntax errors still exist. They all refer to the first line of javascript files which contain `webpackJsonp([1], {` or something similar. Does anybody have an idea if I did something else wrong regarding the polyfills?

**Comment by qm3ster** [comment]
Well, the second error (unexpected use of let) makes it sound like you aren't transpiling for old enough browsers?

**Comment by gerwinov** [comment]
I managed to solve the issues with replacing the `preset` option as follows:

```
build: {
    babel: {
      presets: [
        [
          'vue-app', {
            useBuiltIns: true,
            targets: { ios_saf: 9, uglify: true },
          },
        ],
      ],
```

I don't know why this works, but it does!
