### ISSUE TITLE
building modules Error 

### ISSUE THREAD

**Issue by 0llllvllll0** [nuxt/nuxt.js#2953]
> Error: no parsers registered for: "]/[PJ"

  - parser.js:473 parse
    [nuxtt]/[snapdragon]/lib/parser.js:473:15

  - parser.js:477 Parser.parse
    [nuxtt]/[snapdragon]/lib/parser.js:477:24

  - index.js:122 Snapdragon.parse
    [nuxtt]/[snapdragon]/index.js:122:28

  - braces.js:42 Snapdragon.<anonymous>
    [nuxtt]/[braces]/lib/braces.js:42:45

  - braces.js:68 Braces.parse
    [nuxtt]/[braces]/lib/braces.js:68:26

  - braces.js:89 Braces.expand
    [nuxtt]/[braces]/lib/braces.js:89:18

  - index.js:143 create
    [nuxtt]/[braces]/index.js:143:15

  - index.js:295 memoize
    [nuxtt]/[braces]/index.js:295:13

  - index.js:162 Function.braces.create
    [nuxtt]/[braces]/index.js:162:10

  - index.js:82 Function.braces.expand
    [nuxtt]/[braces]/index.js:82:17

  - index.js:430 getDirParts
    [nuxtt]/[chokidar]/index.js:430:31

  - index.js:437 FSWatcher._getWatchHelpers
    [nuxtt]/[chokidar]/index.js:437:18

  - nodefs-handler.js:438 FSWatcher.NodeFsHandler._addToNodeFs
    [nuxtt]/[chokidar]/lib/nodefs-handler.js:438:17

  - index.js:643 FSWatcher.<anonymous>
    [nuxtt]/[chokidar]/index.js:643:12

  - index.js:16
    [nuxtt]/[async-each]/index.js:16:7

  - Array.forEach

**Comment by qm3ster** [comment]
What's a `nuxtt`?

**Comment by qm3ster** [comment]
What's an install error?

**Comment by 0llllvllll0** [comment]
I just use starter template:
nuxt-community/starter-template <**nuxtt**>
After install and run dev i receive this error in terminal.

>  10% building modules

> this Error

**Comment by 0llllvllll0** [comment]
Ok, sorry. Problem was in square brackets in my project folder name. 

> [PJ]

**Comment by qm3ster** [comment]
@pi0 look, path shenanigans happening :scream:
