### ISSUE TITLE
add support for node 6

### ISSUE THREAD

**Issue by phlogisticfugu** [nuxt/nuxt.js#2954]
In some environments, it's difficult/impossible to upgrade node versions (in my case, AWS Lambda).

Note that while Node 4.x is end-of-lifing next month that Node 6.x is still supported, and should be supported by packages.  see https://github.com/nodejs/Release/blob/master/README.md

I see that other's ran into this issue before:
https://github.com/nuxt/nuxt.js/issues/2395
https://github.com/nuxt/nuxt.js/issues/2927

and that code was even added to check for this:
https://github.com/nuxt/nuxt.js/pull/2718

In my case, I made a new re-package of nuxt which does some transpilation:
https://github.com/phlogisticfugu/nuxtjs-node6

I'd propose:

- a new ./node6/index.js bundle, made via rollup, during npm prepare, which transpiles, with babel shims/runtime-module a version of the nuxt library that runs on node6
  - then in node6 environments, one can use: const { Nuxt } = require('nuxt/node6')
- a node6.rollup.config.js to configure that build, and addition of rollup and appropriate plugins to devDependencies
- a decrease in the required package.json version
- transpiled bin scripts: bin/nuxt-node6 built to permit executing CLI commands in a node6 environment.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2562">#c2562</a>)</em></sub></div>

**Comment by phlogisticfugu** [comment]
Hmm could also be built into automated tests, and the CI configuration

**Comment by sschadwick** [comment]
Also interested in this, primarily for AWS Lambda.

**Comment by pi0** [comment]
A legacy build is coming with nuxt 2 (and nuxt-edge). Will provide better info soon.

**Comment by phlogisticfugu** [comment]
awesome, so the nuxt 2 legacy build will work with node6?  Thanks @pi0 .  I'd love to help out if folks are open to that.

**Comment by sschadwick** [comment]
Lambda now supports node 8!
https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

**Comment by pi0** [comment]
The latest build of nuxt-edge supports Node 6.x again by automatically falling back to legacy dist. Useful for Google Cloud Functions users.

![image](https://user-images.githubusercontent.com/5158436/40841073-6f54ec14-65be-11e8-81b0-5c20e3d4036a.png)

PS: Don't forget to add `babel-polyfill` dependency to your project if you need legacy build.
