### ISSUE TITLE
SCSS does not get compiled to CSS in generate mode.

### ISSUE THREAD

**Issue by itsacorn** [nuxt/nuxt.js#2955]
*Microphone turned on? Everything ok, boss.*
  
Alright, Hey everyone. Was just coding a little Nuxt SPA site, in dev mode everything is working fine, my SCSS gets compiled correctly to CSS. But when i building or generating, with the `--spa` flag and without, my `scss` folder just gets copied from `static` to `dist`. As i mentioned, it works fine in dev mode. Here's my Nuxt config: https://hastebin.com/cowasivefi.js. Anyone got an idea why this doesnt work? Help is appreciated.
  
*Microphone off.*

**Comment by qm3ster** [comment]
Don't put things you don't want copied into `static`.
The idiomatic place would be `assets`, but afaik assets is only special in that it isn't special at all.
Consider putting pictures and such there too, so that you can reorganize them and let webpack sort out whether the hash changed (thus avoiding needless cache busting)
Static is for static paths like favicon and robots.txt

**Comment by itsacorn** [comment]
Alright, now the files dont get copied over anymore. But the SCSS is still not compiled. It isnt even linked by the HTML thats being generated.

**Comment by qm3ster** [comment]
Still works in dev mode?
How are you importing it in dev mode?
Through the css property in nuxt.config or inside components?

**Comment by itsacorn** [comment]
I import it through components. It's in my layout file. Yeah, still working in dev mode.

**Comment by itsacorn** [comment]
Alright, even bigger problem. I compiled the SCSS to CSS by hand, and tried importing the CSS... SAME PROBLEM?!?! No CSS ends up in the dist/ folder! I dont get it... Here's how i import the CSS/SCSS into my layout.vue file: `import "~/assets/scss/auttaja.css"`

**Comment by itsacorn** [comment]
I just noticed its NOT the CSS/SCSS: Its the JS and images which dont load... Welp.

**Comment by Zip753** [comment]
@itsacorn Can you please provide your component code here or create a small repo with the reproduction of an issue? The more details the better. This way we could talk business instead of scientific guesses ;)

**Comment by itsacorn** [comment]
@Zip753 I managed to fix it, i ran `generate` instead of `build`. Are you having the same issue? If not, i'd rather not worry about creating a repo with my code if noones gonna look at it.
