### ISSUE TITLE
Don't rewrite unset head properties

### ISSUE THREAD

**Issue by rayfranco** [nuxt/nuxt.js#2956]
Nuxt shouldn't rewrite/watch head properties if they haven't been set, or should give the choice to enable/disable them.

I am in a very specific use case where the website is integrated as a module in another website backed by Drupal and Nuxt/vue-head is emptying the _already set_ title, but I do still need `vue-head` capabilities.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2563">#c2563</a>)</em></sub></div>

**Comment by rayfranco** [comment]
After investigation, It looks like the head tags including `data-n-head` have been added into the Drupal. I will close this issue. 🚪

**Comment by rayfranco** [comment]
I reopen this issue since I think there is no way to avoid `<title>` binding even when ignoring any initial set up in `nuxt.config.js` and others in layout / components. The tag will always be rewritten even if I don't want to.

**Comment by galvez** [comment]
@rayfranco we'd need you to provide a repo for reproduction to try and work on this. Please reopen the issue then.
