### ISSUE TITLE
use the Rate limiter middleware

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#2957]
How to use the Rate limiter middleware, such as' koa-ratelimit ', because some requests will be sent on the server causing the requested IP to not be available to the client, or will someone else encounter a similar situation?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2564">#c2564</a>)</em></sub></div>

**Comment by qm3ster** [comment]
You want to ratelimit your nuxt app's requests to an api? Is it your api?

**Comment by fengjiel** [comment]
Yes, I made some modifications to the koa-ratelimit, so that he only logged ajax, but server sent ajax because the IP was not properly counted.

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
