### ISSUE TITLE
Are components cached when imported multiple times?

### ISSUE THREAD

**Issue by qrwdew** [nuxt/nuxt.js#2960]
Hi. I would like to know if when I `import` the same component in 2 different pages, will it load 2 times or once?

example:
`~/pages/page1:`
```
import SomeComponent from "~/components/SomeComponent.js";

export default {
    components: { SomeComponent }
}
```
`~/pages/page2:`
```
import SomeComponent from "~/components/SomeComponent.js";

export default {
    components: { SomeComponent }
}
```

When I go from `/home` (server-loaded) to `/page1` (client-loaded, redirected with router), and redirect from `/page1` to `/page2` (also client-loaded, redirected with router), will the SomeComponent load more than once? Will it need to download the additional bytes?

If yes, then should I put the SomeComponent in ~/plugins/myComponents.js and make it global by doing Vue.use(SomeComponent) there? So that it's loaded only once by client

**Comment by qm3ster** [comment]
No. If you put it in plugins it will load for all pages, even ones that don't need it.
Depending on the number of pages using it, webpack will (especially with the coming update to webpack 4) automatically put it in its own chunk.
Is this component particularly large?

**Comment by manniL** [comment]
Nope, the component will be loaded twice in this case. You can see it when analyzing your bundle with `npm run build -- -a` or `nuxt build -a`.

I usually extract such components in own chunks so they only need to load once.


`~/pages/page1`:

```
export default {
    components: { 
        SomeComponent: () => import('~/components/SomeComponent.js')
    }
}
```

`~/pages/page2`:

```
export default {
    components: { 
        SomeComponent: () => import('~/components/SomeComponent.js')
    }
}
```
