### ISSUE TITLE
Middleware store dispatch or commit before redirect will not write data on server

### ISSUE THREAD

**Issue by Wei12345** [nuxt/nuxt.js#2961]
Sorry, my English is poor
[glitch](https://glitch.com/edit/#!/cute-lyric)

When you visit [`index.vue`](https://cute-lyric.glitch.me) on server
It has a middleware `test.js`
```
store.commit('SET_USER', 'hello');
return redirect('/about');
```
You will be redirect to `about.vue`
You will find that `authUser` is null

You click the back link to repeat the above action on client
You will find that `authUser` has value

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2568">#c2568</a>)</em></sub></div>

**Comment by rhwilr** [comment]
Can verify. I just stumbled upon this issue as wel.

**Comment by kirillbunin** [comment]
Same here, nuxt `1.4.0`

**Comment by aldarund** [comment]
Because redirect on server do a server side redirect  so its like a full page  reload...

**Comment by shhdgit** [comment]
@aldarund But how can I pass the store when redirect.

**Comment by aldarund** [comment]
@shhdgit afaik you cant. Only solutions is to use persisted vuex state or pass params that u need via url params.

**Comment by shhdgit** [comment]
@aldarund Thanks.

**Comment by galvez** [comment]
@shhdgit you can use Set-Cookie too.
