### ISSUE TITLE
Nuxt amp example: should not remove all script tags

### ISSUE THREAD

**Issue by bodinsamuel** [nuxt/nuxt.js#2962]
Hi,

I'm testing nuxt for an Amp site. Everything is working perfectly (thanks ❤️ ) except one tiny thing.
In the examples you gave
``` javascript
// Remove every script tag from generated HTML
html = html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
```
All scripts tags are removed without consideration, but the solution it not good because amp does allow `<script type="application/json"></script>` (in amp-analytics for example)
It's not really a bug but it can be confusing for newcomers if they simply copy the code :)

Because I'm not a regex master, I didn't succeed in modifying the regex to only match script tags that does not have that type (screw you negative lookahead). So I'v done this (which is absolutely not bulletproof but a quick fix)
```javascript
html = html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, (str) => {
    if (/application\/json/.test(str)) {
      return str;
    }
    return '';
  });
```

If someone have a better fix 👍 

thanks

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2569">#c2569</a>)</em></sub></div>

**Comment by storix** [comment]
Thanks for the quick fix, but I think it's better to use `application/ld+json` not just plain json, as per [amp docs](https://www.ampproject.org/docs/fundamentals/spec):

> Prohibited unless the type is application/ld+json. (Other non-executable values may be added as needed.) Exception is the mandatory script tag to load the AMP runtime and the script tags to load extended components.

Also, does anybody know is it possible to implement amp feature as a plugin? So instead of copy/paste we can just `npm install nuxt-ampify`.

**Comment by bodinsamuel** [comment]
Hi, 
You are absolutly right but the docs is also inconsistent ahah
As you can see here it's "application/json" 😿 
https://www.ampproject.org/docs/reference/components/amp-analytics

It would be awesome to have a plugin to do that because their is probably more fix to be 100% compatible (i.e: I'm thinking about amp-sidebar that need to be directly in <body> which is a pain in the a** to handle in vue)

Thanks :)

**Comment by alankent** [comment]
I don't have a better solution, but have been tweaking the rules with some success. But I don't understand the Nuxt/Vue side of things well enough to say if this is a "good" approach. It feels hacky still.

https://github.com/alankent/amp-nuxt-trial/blob/master/nuxt.config.js

E.g. instead of replacing all `<script>` tags, the regex is anchored to the closing `</body>` tag. Also concatenates lumps of CSS in the head (maybe better done with WebPack config settings?)

**Comment by paulopmx** [comment]
I'm trying to write my own solution for this and experimented with going the module route. But I'm encountering some limitation with the hooks. I think using regexp to modify the html on render route is a bit hacky. Is it possible to just modify the nuxt config before the render route? Just so I can add or remove resources?

**Comment by nobalmohan** [comment]
I do something like this, first remove and add  AMP scripts you need

```
  html = html.replace(
    /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
    ""
  );
  // Add AMP script before </head>
  const ampScript =
    '<script async src="https://cdn.ampproject.org/v0.js"></script>' +
    '<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>' +
    '<script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>' +
    '<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>' +
    '<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>';

  html = html.replace("</head>", ampScript + "</head>");
```
