### ISSUE TITLE
Update router base dynamically

### ISSUE THREAD

**Issue by nicolas-bonnel** [nuxt/nuxt.js#2963]
Hello,

I'm using Nuxt to build an application that can be proxied by another service, the exposition path of the application being dynamic. Is it possible to update router `base` property once nuxt app is generated ?

I have tried in the `nuxtServerInit` action of the store the following code, but it doesn't work :
```
app.router.options.base = '/mypath/'
```

I have tried updating routing properties of object in the `plugins/index.js` export function too, but had no success.

Thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2570">#c2570</a>)</em></sub></div>

**Comment by qm3ster** [comment]
If your server is real node, why don't you just build when you get the path? Does it change frequently and the build would be too long?

**Comment by nicolas-bonnel** [comment]
Yes it would be too long, the app can be exposed multiple times and be queried on differents URL frequently.

**Comment by brambergvd** [comment]
@nicolas-bonnel  any leads on how to solve this?

**Comment by galvez** [comment]
@nicolas-bonnel you probably want to do this routing through Nginx or another higher server layer. I'd use / as base, capture the entire URI and do the treatment using a middleware. Closing this as there's been no updates for over 90 days.
