### ISSUE TITLE
 I want to add the vue-router meta tag to generate breadcrumbs for the page and not find the configuration item

### ISSUE THREAD

**Issue by DestinyHunter** [nuxt/nuxt.js#2967]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2574">#c2574</a>)</em></sub></div>

**Comment by javialon26** [comment]
in every page you can add meta key and define it here.

example:
```
export default {
meta: {
      breadcrumb: 'Imagen de Perfil'
    }
}
```

then maybe in a middleware you can read the meta of the route:

example
```
export default ({ store, route }) => {
  let breadcrumb = null
  const metadata = route.meta[0]

  if (metadata !== undefined && metadata.breadcrumb !== undefined) {
    breadcrumb = {
      name: route.name,
      title: metadata.breadcrumb
    }
  }

  store.commit('SET_BREADCRUMB', breadcrumb)
}

```

**Comment by docmattman** [comment]
Is the `route.meta` supposed to be an array?  Is there a reason we need to use

```
const metadata = route.meta[0];
```

Instead of just using: 

```
const metadata = route.meta;
```

to get the meta object defined in the example?  Will there ever be more than one meta object returned?  Is there a case where multiple meta objects will be returned in the `route.meta` array?  If not, shouldn't it just be an object instead of an array?

**Comment by galvez** [comment]
@Atinux can you post here the clarification re: `route.meta` one more time? I'll add it to the docs if there are no plans to change it.

**Comment by Atinux** [comment]
Here the example added to Nuxt.js repo: https://github.com/nuxt/nuxt.js/tree/dev/examples/routes-meta

See `middleware/theme.js`, this is really easy to get the latest value and add some logic depending of the children.

Demo: https://nuxt-routes-meta.glitch.me/
