### ISSUE TITLE
can't set `head.script.src` to env var inside `nuxt.config.js` file

### ISSUE THREAD

**Issue by tuqire** [nuxt/nuxt.js#2972]
In my `nuxt.config.js` file I insert a JS file into my site using the head attribute. I set the `src` of the file to an env var (`process.env.FILE_URL`) but can't seem to get this working. I am seeing the following behaviour:

1. When running `nuxt dev` the env var value is injected correctly and the correct file is loaded.
2. When running `nuxt build && nuxt start` the value is not injected and I get `undefined`.
3.  If I set the `src` attr to be an immediately executing function which console logs and then returns `process.env.FILE_URL`, the console log is the correct value, but the `src` is still set to `undefined`.

Is this something anyone has seen or can help me with? I can't find any documentation about whether this is expected behaviour, or a bug.

**Comment by clarkdo** [comment]
Did you set `FILE_URL` in `nuxt start`, I think you should set it in `nuxt build`, because building is the step to process all head resources.

Or you can make `head` be a function to load configs asynchronously, such as:

```js
// nuxt.config.js
module.exports = {
  head: function () {
    return {title: process.env.headTitle}
  }
}
```

**Comment by tuqire** [comment]
Thank you! Completely forgot that my env vars are available at runtime but not build time, thus the confusion.
