### ISSUE TITLE
Question - Scroll to top after axios

### ISSUE THREAD

**Issue by cloudbluedigital** [nuxt/nuxt.js#2978]
hi guys so I have something like this:

```
  methods: {
    async getBlogs(url) {
      const newBlogs = await this.$axios.$get(url)
      this.blogs = newBlogs
    },
    async getSpecificPage(page) {
      const newPageBlogs = await this.$axios.$get(process.env.API_URL + 'api/blogs/all?page=' + page)
      this.blogs = newPageBlogs
    }
```

now what I want to do after this.blogs is assigned, is scroll to top but the route itself is not changing. Is there any way to do that?

Thanks

**Comment by paulgv** [comment]
Simply call [`scrollTo()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) after your call:

```es6
async getSpecificPage(page) {
  const newPageBlogs = await this.$axios.$get(process.env.API_URL + 'api/blogs/all?page=' + page)
  this.blogs = newPageBlogs
  window.scrollTo(0,0)
}
```

**Comment by cloudbluedigital** [comment]
tried that and it didn't do anything

**Comment by paulgv** [comment]
You can use any scrolling library like smooth-scroll: https://github.com/cferdinandi/smooth-scroll
Just make sure you import it client-side only: https://nuxtjs.org/faq/window-document-undefined

**Comment by cloudbluedigital** [comment]
for some reason it throws an error when trying to do new SmoothScroll even throught I defined it as it is in 2nd link, both in vendor and process.browser

**Comment by paulgv** [comment]
Can you share your code and the error message?

**Comment by husayt** [comment]
Seems it can be closed now
