### ISSUE TITLE
After build production use a tool like PM2 to start up the app

### ISSUE THREAD

**Issue by anotherwebstorm** [nuxt/nuxt.js#298]
Hi there, so far I'm very happy with the results of Nuxt and Vue particularly, congratulations on the good work.

I do have a quick / newbie question about running a production folder (dist) generated with Nuxt with a tool like [PM2](http://pm2.keymetrics.io/).

Which file in the **dist** folder do I have to run to make sure the app is properly started up?

So for example when I build and isomorphic app with nodejs and express I was start with `pm2 start server.js` what would be the case on the nuxt folder?

Thank you

**Comment by alexchopin** [comment]
Hi thanks for the support,
`npm run generate` command is use to generate static hosted application.
I think your are asking for server render application in production, in this case it's not the same.
[Server Rendered Deployment](https://nuxtjs.org/guide/commands#production-deployment)
#67

**Comment by cupliz** [comment]
you can demonize it using pm2 by typing
`pm2 start node_modules\nuxt\bin\nuxt-start --name your-app`

**Comment by mascardoso** [comment]
Thanks for the heads up!

**Comment by blackpr** [comment]
you can also type:
`pm2 start npm -- start`

**Comment by abdulhannanali** [comment]
Yes I came exactly here to comment what just @blackpr commented. Thanks for saving lives of countless people.

**Comment by elrolito** [comment]
See also https://medium.com/@vipercodegames/nuxt-deploy-809eda0168fc

**Comment by Erigers** [comment]
Really good article 💯
