### ISSUE TITLE
Multiple dynamic routes on same level impossible with Nuxt?

### ISSUE THREAD

**Issue by jerakode** [nuxt/nuxt.js#2982]
I am trying to have such thing:

```
pages/
--| _section/
-----| index.vue
--| _slug/
-----| index.vue
--| index.vue
```
But looks like it doesn't work with Nuxt.

Is there any way to accomplish this?

**Comment by manniL** [comment]
You can do this definitely with a little workaround. Only use one dynamic route, e.g.:

```
pages/
--| _value/
-----| index.vue
--| index.vue
```

Then, use the `/_value/index.vue` for logic to differ between a `section` and a `slug` and render subsequent components based on this decision. :relaxed:

**Comment by jerakode** [comment]
Trying to figure out practical example, but have no ideas. 

Right now I am receiving `sections` this way

```js
axios.get(`articles/${params.section}`)
```
And `slugs` this way
```js
axios.get(`articles/${params.section}/${params.slug}`)
```

Any ideas how should I refactor this? Maybe I can provide some Component related ID in my JSON? Fod example: 

```js
{
  "type": "sectionORslug",
  "data": ...
} 
```

I guess it could work?

**Comment by manniL** [comment]
Well, in your case you could nest your dynamic routes because `slug` would need both: `section` and `slug`. See how this (easily) works [here](https://router.vuejs.org/en/essentials/nested-routes.html)

**Comment by jerakode** [comment]
Don't get it, how to apply to Nuxt routing?

**Comment by manniL** [comment]
Sorry, mislinked! [Here](https://nuxtjs.org/examples/nested-routes/) you go!

**Comment by jerakode** [comment]
@manniL but then I will have route like this, no? `/section/slug`
If so, then this is not what I ask. I need `/section` and `/slug` on same level.

**Comment by jerakode** [comment]
I already have similar like this

![screenshot from 2018-03-10 14-47-46](https://user-images.githubusercontent.com/29287093/37242427-0cae516e-2472-11e8-836b-939dd5da05e7.png)

This is basically the same, right?

**Comment by manniL** [comment]
@jerakode Yeah, exactly. But how do you get the `section` parameter if you are in the `_slug` route?

Yup, the provided structure is similar to what I suggested :relaxed:

**Comment by jerakode** [comment]
Not sure what you ask. How do I get `section` in my current code? Given the route structure `/section/slug` I take it from `params.section`.

**Comment by manniL** [comment]
In your current code, this makes sense. But you want it on the same level. If so, how would you find out the `section` then when you are in the `slug` route?

**Comment by jerakode** [comment]
I have all this data in JSON, I guess. All slugs (articles) are belongs to appropriate sections. Not sure how it can be solved right.

OK, what about next. We can have dynamic routes along with static on same level, right? I mean we can have dynamic `section` and static, lets say, `special` route (without underscore). So Nuxt can distinguish between this two. What if we have a fixed array of Sections? Can they behave then like static routes? I am anyway recieve a list of Sections on `serverNuxtInit`.

**Comment by manniL** [comment]
Well, then it might be useful to go for a `/_section/_slug/` routing to map your data.

Exactly, you can use dynamic and static routes on the same level.
I'm not sure if it's possible to use a fixed route array as static routes programmatically. :man_shrugging:

**Comment by jerakode** [comment]
Hey everyone who's reading this. I ended up like this.

```js
async asyncData ({ params, store, error }) {
    try {
      if (store.state.sections.some((section) => section.slug === params.wtf)) {
        let { data } = await axios.get(`articles/${params.wtf}`)
        this.currentComponent = 'Section'
        return { articles: data, error: false }
      } else {
        let { data } = await axios.get(`articles/all/${params.wtf}`)
        this.currentComponent = 'Article'
        return { articles: data }
      }
      // store.commit('SET_ARTICLES', data)
    } catch (err) {
      error({
        statusCode: err.response.status,
        message: `Error code: ${ err.response.status }`
      })
    }
  }
```

Now the problem is that I can't access `this` in `asyncData`. Then how do I conditionally change `currentComponent`?

**Comment by jerakode** [comment]
If I do this, what will crawler see?

```js
mounted () {
    if (this.$store.state.sections.some((section) => section.slug === this.$route.params.wtf)) {
      this.currentComponent = 'Section'
    } else {
      this.currentComponent = 'Article'
    }
  }
```

**Comment by supadrupa** [comment]
I have the same problem. How to fix it? I need multiple dynamic routes on same level. Could you help me please?

**Comment by merijnvanessen** [comment]
similar problem

pages/_slug.vue
pages/index.vue
pages/recipes/_slug.vue
pages/recipes/index.vue

- I generate a nav with router-links (in my layout)
- they are rendered like /about, /team  etc

Now I go to the recipes overview, with router-links like recipes/spaghetti
When I click on this item it matches
pages/recipes/_slug.vue

But  my nav is suddenly replaced from  /about, /team  
to recipes/about, recipes/team
