### ISSUE TITLE
[BUG] build.watch doesn't handle `~`

### ISSUE THREAD

**Issue by mathieutu** [nuxt/nuxt.js#2983]
Hi, if I watch a file by this way: 
```js
build: {
        watch: [
            '~/.env',
        ]
    },
```
the build will not reload.

If I do:
```js
build: {
        watch: [
            resolve(process.cwd(), '.env')
        ]
    },
```
it works!

I'll maybe make a PR, if I have time to.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2586">#c2586</a>)</em></sub></div>

**Comment by mootari** [comment]
Noticed this myself. Watched paths are only passed through upath's `normalizeSafe()` function, not `Nuxt.resolveAlias()`.
Note that paths are resolved relative to the cwd, so `watch: ['.env']` should work as well.

**Comment by mathieutu** [comment]
Hum.. Or not. This was not a question but a notice for a future PR. Please @cmty reopen!

**Comment by mootari** [comment]
@mathieutu Did you mark my response as answer on cmty.app? If so, can't you unmark it?

**Comment by Atinux** [comment]
Updated :)

**Comment by mootari** [comment]
@Atinux It's still marked as closed though. :)
