### ISSUE TITLE
pages目录下的页面都会被路由访问到？如何避免非路由的页面

### ISSUE THREAD

**Issue by qianduanwuzi** [nuxt/nuxt.js#2984]
pages目录下的页面有些是业务抽象出来的组件，这时候不希望被路由访问到。该如何解决？

**Comment by fengjiel** [comment]
为什么一定要放在pages里面，不想被访问可以放到components

**Comment by yoyo837** [comment]
We are now ignoring files starting with a - in front of its filename (example: pages/-ignored.vue) (PR #2417)
since release v1.0.0
