### ISSUE TITLE
Dynamically generated route path does not work for snake case page names

### ISSUE THREAD

**Issue by ClemMakesApps** [nuxt/nuxt.js#2985]
If I create a new nuxt page called `sign_up.vue`, `createRouter()` in `router.js` from `nuxt` generates the following route:

```
routes: [
{
  path: "/sign:up",
  component: _1afcc2c0,
  name: "signup"
},
```

With this bug, I wouldn't be able to create another page called `sign_in.vue` as it collides with the dynamically generated route.

https://spiky-part.glitch.me is an example of this bug.

**Comment by Zip753** [comment]
Duplicate of #2716

**Comment by ClemMakesApps** [comment]
Thanks for noticing the duplicate. I'll go ahead and close mine
