### ISSUE TITLE
add plugin in typescript

### ISSUE THREAD

**Issue by magick93** [nuxt/nuxt.js#2987]
Hello

I am trying to learn nuxt.js and typescript. I've create a typescript nuxt using `vue init nuxt-community/typescript-template my-project`. 

I'm wanting to add https://buefy.github.io. But there is no `plugin` directory.

Am I correct in assuming that Buefy should be used as a Nuxt.js plugin?

Should I just create a folder or does is additional configuration required?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2590">#c2590</a>)</em></sub></div>

**Comment by galvez** [comment]
@magick93 yes, add it to a folder named plugins and [list it in your nuxt.config.js](https://nuxtjs.org/guide/plugins/).
