### ISSUE TITLE
Add an alternative to Webpack (Fuse-Box)

### ISSUE THREAD

**Issue by orblazer** [nuxt/nuxt.js#2988]
Hello,
I create this issue for propose me for add or replace the builder for work with [Fuse-Box](https://fuse-box.org/). If you accept that, i can work on this for add that implementation.

**What is Fuse-Box ?**
Fuse-Box is an module bundler/builder like Webpack written in Typescript and this is very fast.

**Why Fuse-Box ?**
I propose Fuse-Box because this is a very fast builder and is more optimized than Webpack.

Thanks.

**Comment by microcipcip** [comment]
IMHO this may not be needed as Webpack 4 is 60% faster than Webpack 3.

**Comment by orblazer** [comment]
Ok, i can go try rewrite with webpack 4 in first time.

**Comment by orblazer** [comment]
Ok, i wait the relase with webpack 4 and test difference.

**Comment by husayt** [comment]
thanks for suggestion, but i guess this would be too drastic for this project.
