### ISSUE TITLE
The middleware to prevent access to SSR resource will fail

### ISSUE THREAD

**Issue by CykuTW** [nuxt/nuxt.js#2994]
I don't know is it necessary to prevent access to SSR resource.
But I saw it actually has a middleware in `/lib/core/renderer.js` to do this.

And it would fail if we send path with `url encoded`.
For example: 
```
GET /_nuxt/server-bundle%2Ejson HTTP/1.1
Host: nuxtjs.org
```

The first middleware will directly check that it's not in `req.url` for every filename in `resourceMap`.
https://github.com/nuxt/nuxt.js/blob/v1.4.0/lib/core/renderer.js#L221
```JavaScript
    // Common URL checks
    this.useMiddleware((req, res, next) => {
      // Prevent access to SSR resources
      if (ssrResourceRegex.test(req.url)) {
        res.statusCode = 404
        return res.end()
      }
      next()
    })
```

Then use `serve-static` package to serve `.nuxt/dist/` files.
https://github.com/nuxt/nuxt.js/blob/v1.4.0/lib/core/renderer.js#L259
```JavaScript
    // Serve .nuxt/dist/ files only for production
    // For dev they will be served with devMiddleware
    if (!this.options.dev) {
      const distDir = resolve(this.options.buildDir, 'dist')
      this.useMiddleware({
        path: this.publicPath,
        handler: serveStatic(distDir, {
          index: false, // Don't serve index.html template
          maxAge: '1y' // 1 year in production
        })
      })
    }
```

In `serve-static` package, it will call `send` packege to serve the file,
`server-static` directly calls it with `send(req, parseUrl(req).pathname, opt)`.
https://github.com/expressjs/serve-static/blob/v1.13.2/index.js#L95
```JavaScript
    var path = parseUrl(req).pathname;

    // create send stream
    var stream = send(req, path, opts)
```
	
But before `send` create the file stream, it would do a `url decode` on req.path.
https://github.com/pillarjs/send/blob/0.16.2/index.js#L517
```JavaScript
  // decode the path
  var path = decode(this.path)
```

So `server-bundle%2Ejson` will be decoded to `server-bundle.json`, and the first middleware won't match it.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2595">#c2595</a>)</em></sub></div>

**Comment by aldarund** [comment]
This PR should solve it
https://github.com/nuxt/nuxt.js/pull/3758

**Comment by ishitatsuyuki** [comment]
IMO this worth a CVE - people are already putting confidential information in SSR bundle, like the case of
https://github.com/nuxt-community/auth-module/blob/cda679aea1df1a7dbd651584ed788d89efada567/examples/demo/nuxt.config.js#L43

**Comment by galvez** [comment]
@Atinux I agree with @ishitatsuyuki -- we need to get this in.

**Comment by ishitatsuyuki** [comment]
The vulnerability is patched; however until we get appropriate security advisories we may want to keep this open.

**Comment by ishitatsuyuki** [comment]
@galvez The steps are probably:

1. Release a fixed version, preferably also for 1.x.
2. Fill out the form on https://iwantacve.org. This provides a form where you can describe the vulnerability in depth.

**Comment by qm3ster** [comment]
In general, dist should only contain things that can be published without authorization.

**Comment by galvez** [comment]
@ishitatsuyuki I'm making a note about discussing a proper CVE-request process with the team with this item referenced. Closing this issue now as your PR addressed the problem and the CVE step is not immediately actionable / will be tracked elsewhere. Thanks!
