### ISSUE TITLE
extractCSS - no plugins CSS on prod build

### ISSUE THREAD

**Issue by lukasamd** [nuxt/nuxt.js#2997]
I have a lot of shared SASS code on assets directory and would like to use extractCSS for build option. Tested and works... but not completely - there are no CSS styles for plugins that I use in app. In this case, from vue-js-modal. I use this plugin in config:

`{ src: '~/plugins/vue-js-modal', ssr: true },`

What should I change to fix it?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2597">#c2597</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.

**Comment by lukasamd** [comment]
Refresh. Tried about week ago and it still occurs.

**Comment by manniL** [comment]
@lukasamd Have you tried using `nuxt-edge` (soon Nuxt 2) with webpack 4?
