### ISSUE TITLE
Redirect absolute url in middleware

### ISSUE THREAD

**Issue by marceloavf** [nuxt/nuxt.js#3002]
I'm having a problem when redirecting to an absolute URL inside a middleware, it return to a page with `ERR_REDIRECT` and then go to the desired page.

Nuxt mode: `spa`

auth.js middleware:
```js
export default function (context) {
  const token = window.localStorage.getItem('token')
  if (!token) {
    context.redirect('https://nuxtjs.org/')
  }
}
```

Video showing the page:
![middleware nuxt](https://user-images.githubusercontent.com/5435657/37306594-f4825eae-2616-11e8-9518-1d5bbe43ec19.gif)

**Comment by dorianamouroux** [comment]
I think your middleware is executed on both server and client: Server generates the error (because `window` is not defined); and then the client upon executing the middleware redirects you to the page. Try to add some `console.log` in your middleware to understand if my assessment is correct.

**Comment by marceloavf** [comment]
Oh, I forgot to say that I'm using `SPA` mode @dorianamouroux

**Comment by benoitemile** [comment]
Hi @marceloavf if it's SPA, you're running a CSR app, so your browser is rendering the error page then script executes client-side and redirects you, it's a normal behavior. There's an example abouth authentification in nuxt docs, you also have a module dedicated to [authentification](https://github.com/nuxt-community/auth-module).

Hope it helps
