### ISSUE TITLE
'Redirecting to external page.' on error

### ISSUE THREAD

**Issue by jamesAtcodeninja** [nuxt/nuxt.js#3003]
Steps to reproduce:
1. Goto non-existing page
2. 'Redirecting to external page.' is displayed for a few seconds.
3. Then `error.vue` is displayed.

How can we skip displaying 'Redirecting to external page.'?

I noticed this can be accomplished by swapping the following snippet in `.nuxt/components/nuxt.js` 
```
// swap these two conditionals
 if (this.nuxt._redirected) {
      return h('div', [ 'Redirecting to external page.' ])
    }
    // If there is some error
    if (this.nuxt.err) {
      return h('nuxt-error', {
        props: {
          error: this.nuxt.err
        }
      })
    }
```

**Comment by husayt** [comment]
Not sure if this is a issue or expected behavior. Maybe needs an extra hook. Probably needs to be discussed to decide on the right behavior.
