### ISSUE TITLE
Invalid link to Github Repository

### ISSUE THREAD

**Issue by creativenoobie** [nuxt/nuxt.js#3006]
Hey,

I was checking out all the examples when I came across [Auth External API (JWT)](https://nuxtjs.org/examples/auth-external-jwt).

This example points to an non-existing Github repository: https://github.com/nuxt/nuxt.js/tree/dev/examples/auth-jwt

Please check the issue.

Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2604">#c2604</a>)</em></sub></div>

**Comment by jb-reynaud** [comment]
I think your in the wrong place to post this issue: you should post it in the documentation repository
https://github.com/nuxt/nuxtjs.org

**Comment by aggarwaldev** [comment]
@jb-reynaud I believe missing example will be an issue for this repo?

**Comment by husayt** [comment]
@jb-reynaud is right. please, create issues in the right place, to help to resolve them sooner.

As for that example it is gone for some reason. The best I could find is this one:
https://github.com/nuxt/example-auth0

Probably link needs to be replaced with the one above. Anyone is aware where is the original example and why is it gone?
