### ISSUE TITLE
global layout variable

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#301]
how to declare a global variable, so that it was visible only within a certain layout?

**Comment by alexchopin** [comment]
Can you be more explicit?

**Comment by Atinux** [comment]
@wormen Use the store to for global variables: https://nuxtjs.org/guide/vuex-store

**Comment by wormen** [comment]
@Atinux 
1) it is not the case
2) I need to JS, a global library, which will be visible only within a certain layout, while others do not see
3) the repository applies to all models, and I need a certain layout, I have several of layouts
