### ISSUE TITLE
`server-bundle.json` got different hash then the actual chunk files

### ISSUE THREAD

**Issue by feryardiant** [nuxt/nuxt.js#3011]
Hi

I'm getting an odd issue here which is the `hash` generated in `server-bundle.json` file are different than the actual files.

![nuxt-server-bundle](https://user-images.githubusercontent.com/508665/37364579-81f4fd16-272d-11e8-97ad-e114bd9f8f62.png)

and when I run the server, of course I got an error on initial page load

![initial-error-on-page-load](https://user-images.githubusercontent.com/508665/37364978-9d3e112e-272e-11e8-9ad5-b10b1ac00bfd.png)

Initially I thought it was plugin issue (#2868) but when I've got that working, this issue still remain. Also, I'm actually not sure if this issue was come from [`nuxt builder config`](https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/server.config.js#L44-L46) or [`vue-server-renderer`](https://www.npmjs.com/package/vue-server-renderer).

Any thoughts?

Cheers 🥂 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2608">#c2608</a>)</em></sub></div>

**Comment by galvez** [comment]
@feryardiant What Nuxt version are you using? Closing this as there's been no updates in over 90 days. Please provide a sample repo if you're still pursuing a solution, reopen the issue and I'll take a look.
