### ISSUE TITLE
Using express-sessions in Nuxt

### ISSUE THREAD

**Issue by creativenoobie** [nuxt/nuxt.js#3012]
Hey,

I'm planning to use sessions in my Nuxt application instead of relying on cookies for data storage.

Here's my code (plugin/express-sessions.js)
```
import Vue from 'vue'
let Session = require('express-session')

var sessionConfig = {
  secret: 'asdnsadnda',
  resave: 'false',
  saveUninitialized: 'false'
}

Vue.use(Session(sessionConfig))
```

here are my actions (store/index.js)
```
const actions = {
  nuxtServerInit ({ commit }, { req }) {
    console.log(req.session)
    if (req.session && req.session.authUser) {
      commit('SET_USER', req.session.authUser)
    }
  },

  login ({ req }, { commit }, payload) {
    req.session.authUser = payload.user
    commit('SET_USER', payload.user)
  }

}
```

here's my nuxt.config.js

```
plugins: [
    '~/plugins/vuetify.js',
    '~/plugins/express-sessions.js'
],
```
```
 build: {
    vendor: [
      '~/plugins/vuetify.js',
      'express-session',
      'babel-polyfill'
    ]
...
```
Here's what I'm facing now:
![image](https://user-images.githubusercontent.com/23532769/37365472-9f25e9e0-2723-11e8-9fb8-8b66bb50a4bf.png)

Any ideas what might be wrong?

Please help me!

**Comment by sudhir600** [comment]
I saw the [link](https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2609) but there is no answer.
did you found any solution?

**Comment by sudhir600** [comment]
Any Solution?
