### ISSUE TITLE
How to delete the defer in the script tag

### ISSUE THREAD

**Issue by longting** [nuxt/nuxt.js#3017]
nuxt generating HTML script tag ， How to delete the defer in the script tag

```
<script src="/_nuxt/layouts/default.1bfb634917148e3ade51.js" defer=""></script>
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2614">#c2614</a>)</em></sub></div>

**Comment by husayt** [comment]
see [this](https://github.com/nuxt/nuxt.js/blob/dev/examples/meta-info/pages/index.vue#L18) example 

```
script: [
      { src: '/head.js' },
      // Supported since 1.0
      { src: '/body.js', body: true },
    { src: '/defer.js', defer: '' }
]
```

**Comment by husayt** [comment]
I also noticed that this area is not really well documented.

**Comment by benoitemile** [comment]
Hi @husayt , for performance concerns, you should probably want this enabled.

If you are running SSR and really need to modify html response before sending it to client, you could add [some hooks](https://nuxtjs.org/api/internals-nuxt#hooks) in nuxt.config.js.
See https://github.com/nuxt/nuxt.js/issues/2822#issuecomment-366527838 , it lets you modify the DOM answer before being sent to the client. At this moment you could remove the defer tag.

The best I know of at this point, hope it helps.
