### ISSUE TITLE
Dependency not found (although installed)

### ISSUE THREAD

**Issue by talovicnedim** [nuxt/nuxt.js#3020]
This is how my ```vee-validate.js``` (in ```plugins``` folder) looks:

```
import Vue from 'vue'
import VeeValidate from 'vee-validate'

Vue.use(VeeValidate)
```
```nuxt.config.js``` contains the following:

```
plugins: ['~/plugins/vee-validate.js'],
```

I don't need to mention that I executed the following:

```npm install vee-validate --save```

However, this is the error I get when I try to execute ```npm run dev```:

```
This dependency was not found:

* nuxt_plugin_veevalidate_1a0c1998 in ./.nuxt/index.js
```

It's strange this doesn't work on server, but on local does. I tried to reinstall the server, install nuxt and other plugins manually as well, and many many other possible solutions.

Thanks!

**Comment by husayt** [comment]
try deleting `.nuxt` folder and running again. That helps sometimes.

**Comment by talovicnedim** [comment]
It works. Thanks.
