### ISSUE TITLE
DeprecationWarning: Tapable.plugin

### ISSUE THREAD

**Issue by markschultz** [nuxt/nuxt.js#3022]
When building with the dev branch of nuxt with a [starter](https://github.com/nuxt-community/starter-template) template I get the following warning:

``Initializing builder(node:14312) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead``

**Comment by markschultz** [comment]
running with `node --trace-deprecation node_modules/nuxt/bin/nuxt-build` or similar shows this may be one or both of the following dependencies.

- vue-server-renderer
- friendly-errors-webpack-plugin

this can be closed or left open for tracking.

**Comment by husayt** [comment]
Let's close it. Thanks for reporting
