### ISSUE TITLE
Nuxt Static Site Auth

### ISSUE THREAD

**Issue by MrRossBennett** [nuxt/nuxt.js#3023]
Hey all

We're deploying our Nuxt app via [Netlify](https://www.netlify.com/) (so as a static site with the `npm run generate` command. There is no server). 

We're using an auth service that stores a token in `localstorage` when a user is authenticated. We're then accessing that token using a Vuex store. Once the app is loaded we are then able to use Nuxt's middleware to protect certain routes from non-authenticated users etc. 

But when the page is refreshed obviously the store is empty. So we're trying to re-verify the user on page load by dispatching an action. We've tried to do this via the [`fetch`](https://nuxtjs.org/api/pages-fetch#the-fetch-method) method in a page component and via a [plugin](https://nuxtjs.org/guide/plugins), but both seem to fire too late and our `isAuthenticated` getter is returning false even for already-signed-in users. 

Middleware doesn't seem an option as it's not fired on client refresh and obviously `nuxtServerInit` is out of the question as we, er, don't have a server.

What are our best options for page refresh on a static site?

Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2618">#c2618</a>)</em></sub></div>

**Comment by husayt** [comment]
See nuxt [auth module](https://github.com/nuxt-community/auth-module)  and also [this](https://github.com/nuxt/example-auth0) example for best patterns

**Comment by MrRossBennett** [comment]
Thanks, let me clarify our issue. 

When you are running a Nuxt static site (so no server is present), middleware does not run on page load.

Is there anything we can do about this?

**Comment by davidroyer** [comment]
You need to use the plugins directory. Nuxt will run this code prior to rendering completely on the client.

Do what you need for auth and then commit to your store.

Here’s my file using firebase and a repo of doing this

https://github.com/davidroyer/nuxt-firebase-auth/blob/master/plugins/fireauth.js

**Comment by galvez** [comment]
This seems like a specialized request of assistance, please check out the channels [over at Discord](https://discord.gg/VApZF5W) for help. Closing as there's been no updates over 90 days.
