### ISSUE TITLE
Install fails at opencollective module

### ISSUE THREAD

**Issue by cscomfort** [nuxt/nuxt.js#3025]
Node: 8.10.0
NPM: 5.6.0
OS: RedHat 6.9 (Shared hosting)
Local Node Env:  NVM and Nodenv both produce the same result

Issue: When attempting to install Nuxt (either manually or using the vue-cli community starter template), the process fails at the opencollective module.

```
npm ERR! path /home/userx/nuxt/node_modules/opencollective/dist/bin/opencollective.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/userx/nuxt/node_modules/opencollective/dist/bin/opencollective.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
Any thoughts on what might be the hangup?

Thanks in advance for any help.  

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2621">#c2621</a>)</em></sub></div>

**Comment by husayt** [comment]
That is probably some network issue. But why would Nuxt need to install OpenCollective module?

**Comment by irrg** [comment]
Node: 8.9.1
NPM: 5.5.1
OS: ubuntu in a docker

Same issue. nuxt version ^1.4.0. Blew away my node_modules so now…I have a problem, since `npm i` can't finish.

**Comment by cscomfort** [comment]
@irrg As a workaround since I couldn't resolve the issue directly with the OpenCollective module, I installed Nuxt from a local version that excludes the OpenCollective dependency:

- Cloned the Nuxt repo locally
- Removed all references to OpenCollective in the repo's package.json (/path/to/local/nuxt/package.json)
- Updated my project's package.json to install from the local Nuxt repo, and then ran `npm install` as normal (note that I believe you'll need NPM 2.0.0 or higher to use the `file:` option)

**My project's updated Nuxt dependency in package.json**
```javascript
{
  "dependencies": {
    "nuxt": "file:/path/to/local/nuxt",
  },
}
```

For what it's worth, while troubleshooting the issue, I tried installing the OpenCollective module in a standalone test project and ran into the same error as originally reported (which I sort of expected) so the issue is not specific to Nuxt.

Best of luck!

**Comment by irrg** [comment]
@cscomfort Forking is an option. `file:` path is not really an option if you're building docker instances and such but I'll give it a go.

**Comment by irrg** [comment]
This should solve a lot of issues: 
https://github.com/opencollective/opencollective-cli/issues/3#issuecomment-378039208

I'm trying it out on my 1.4.0 fork…

**Comment by irrg** [comment]
@M3kH Yeah, my PRs (#3178 and #3179) got stuck, and I'm not totally sure why. I literally pulled `tags/v1.4.0` and `dev` and updated the package being used, then committed and created PRs. No one has commented on them. I don't have the time right now to look at the CI errors, but they can't really relate much to the two lines of code I changed.

**Comment by M3kH** [comment]
@irrg Although clean your `node_modules` and recreate your `package-lock.json` solve this issue.
