### ISSUE TITLE
Writing ES6 class 

### ISSUE THREAD

**Issue by paolog22** [nuxt/nuxt.js#3026]
how to write some es6 class on nuxt i made something like this 
![image](https://user-images.githubusercontent.com/12680745/37442704-c2da1d96-2842-11e8-8ea1-f02d5c2e382d.png)

and imported like this
![image](https://user-images.githubusercontent.com/12680745/37442725-da06832e-2842-11e8-8861-15a05acd0e52.png)

but i cant make it work. thanks

**Comment by husayt** [comment]
Try
```
export class ClassName {...}
```
or 
```
export default class {}
```

**Comment by javenwang** [comment]
@paolog22 Why don't you define the class on the outside of function `core`?

**Comment by paolog22** [comment]
thanks for the feedback i think i find a way :)
