### ISSUE TITLE
Weird param

### ISSUE THREAD

**Issue by vaggelis2018** [nuxt/nuxt.js#3032]
I have a middleware which detects the lang param and then checks if the route exists and throw a 404 error. The problem is that when it comes to error page the params is __webpack_hmr. All other pages works great except the error page. Does anyone knows the solution to this?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2626">#c2626</a>)</em></sub></div>

**Comment by manniL** [comment]
This question can be answered on [CMTY](https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2626)
