### ISSUE TITLE
Cannot find a way to create endpoints ?

### ISSUE THREAD

**Issue by rosea1** [nuxt/nuxt.js#3033]
Currently creating an application which will have a web form on it. This then needs to be submitted into Salesforce Pardot. I would like to do this via AJAX request rather than a normal form submit. 

However there is CORS issues with doing this ajax request on the front end. 

I cannot seem to figure out , searching through every single nuxt documentation page, where to simply put some backend node.js code which simply runs on the backend rather than the client. 

From my Q above  you can gather i need to send the formData to some backend code on the same nuxt server and then do a server axios request to get the data into pardot.

Any ideas or anything i am missing ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2628">#c2628</a>)</em></sub></div>

**Comment by manniL** [comment]
It might be a little outdated, but there is an [express example](https://github.com/nuxt-community/express-template)

**Comment by rosea1** [comment]
Hello @manniL  , this seems to be maybe what im after, however it uses another package called backpack, im very reluctant to install more packages to this project But thank you anyway for the response!

**Comment by luminarious** [comment]
https://github.com/nuxt-community/hapi-nuxt is a good starting point
