### ISSUE TITLE
Core nuxt class should not have side effects on creation

### ISSUE THREAD

**Issue by btkostner** [nuxt/nuxt.js#3034]
Right now, the `Nuxt` class has an async side effect in the constructor. This (with the combination of being cached) makes it very hard to extend. You should instead have to run the `await nuxt.ready()` function be called by the parent.

https://github.com/nuxt/nuxt.js/blob/1080dfdbd678e41dc1af8b45ea3edac55fad2f2d/lib/core/nuxt.js#L40

### Personal use case

I am currently moving an old express app to use nuxt with SSR :confetti_ball:, but I need to keep backwards compatibility, which includes falling back to a proxy when no route is matched. To do this, I'm creating a new `Nuxt` class, rebinding the connect app to the already existing express app, and then removing the last middleware (error handling / 404 page). 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2629">#c2629</a>)</em></sub></div>

**Comment by artlovecode** [comment]
Hey @btkostner! I'm in the same situation, would you be able to share the code? It'd be great to see how you went about implementing it

**Comment by pi0** [comment]
Hi @btkostner. Thanks for reporting the issue. We already plan to remove this function call from the constructor. It had been kept there for backward compatibility since nuxt 2.0.0 refactors. For now, what we can have is adding a new option like `_autoInit` to the nuxt constructor options like `new Nuxt({ ..., _autoInit: false})`

**Comment by btkostner** [comment]
@artlovecode This is the middleware file. It's kinda messy, but hopefully the comments help:

```js
/**
 * lib/middleware/vue.js
 * Handles Vue server side rendering.
 */

const { Builder, Nuxt } = require('nuxt')
const path = require('path')

require = require('esm')(module)

const config = require('../../nuxt.config.js').default

/**
 * Sets up nuxt to use an express app. Does some weird hacks to bypass normal
 * nuxt functions.
 *
 * @async
 * @param {Nuxt} nuxt
 * @param {Object} app - An express or connect able server
 * @return {void}
 */
const setupNuxt = async (nuxt, app) => {
  // Override the nuxt connect app with our already existing, backwards
  // compatible express app. Because of this, we have to re-assert ready state.

  // Wait for first load
  await nuxt.ready()

  // We copy the current middleware stack, untainted with nuxt addons, so we can
  // replace it before calling the `.ready()` function. This avoids multiple
  // nuxt middlewares being added to the express stack.
  const middleware = [...app._router.stack]

  // Replace the connect app with our express app
  nuxt.server.app = app

  // Reset all the cached loaded and ready values in nuxt. Oh god.
  this.initialized = false
  nuxt._ready = null

  nuxt.server.resources = {}

  // Replace the app stack with something clean
  app._router.stack = middleware

  // And reload all the setup work
  await nuxt.ready()
}

/**
 * Registers the v3 Vue server side rendering with super nuxt power.
 *
 * @async
 * @param {App} app
 * @return {App}
 */
module.exports.middleware = async (app) => {
  const nuxt = new Nuxt(config)

  await setupNuxt(nuxt, app)

  process.on('message', async (message) => {
    if (message === 'shutdown') {
      await nuxt.close()
    }
  })

  // If we are in a development mode, we will hot reload all nuxt things for
  // easier testing. Otherwise, we expect it to be built in the build step.
  if (process.env.NODE_ENV === 'development') {
    await new Builder(nuxt).build()
  }

  // HACK: removes the default nuxt error handler so we can continue down the
  // stack to Joshau.
  app._router.stack = app._router.stack.filter((stack) => {
    return (stack.name.indexOf('errorMiddleware') === -1)
  })

  // Rewrite 404 errors to non-errors and continue down to Joshua
  app.use((err, req, res, next) => {
    if (err.statusCode === 404) {
      return next()
    } else {
      console.error(err)
      return next(err)
    }
  })

  return app
}
```

The whole setup looks something like this:

Nuxt, then our express app, then proxy to our old old app (named Joshua).

**Comment by btkostner** [comment]
@pi0 that sounds good!

**Comment by ricardogobbosouza** [comment]
@pi0 I think this has been solved
https://github.com/nuxt/nuxt.js/blob/dev/packages/core/src/nuxt.js#L43
can closed?

**Comment by pi0** [comment]
Yes. Both ready and server creation can be disabled by `_ready: false` and `server: false` options. Hopefully, we can finally remove it at all with Nuxt3.
