### ISSUE TITLE
How to refresh the nuxt page? If the page is refreshed with location.reload (), the page looks like the beauty center rendering asyncData does not appear to be executed

### ISSUE THREAD

**Issue by ITCNZ** [nuxt/nuxt.js#3035]
![image](https://user-images.githubusercontent.com/17981388/37448548-c020633e-2861-11e8-8a20-d1d364b8fb4e.png)

For example, I want to let the page refresh, but the page is blank, and the data must be refreshed by hand.
```
    asyncData ({ params, error }) {
      return axios.get('http://localhost:3333/api/newslist')
      .then((res) => {
        return { datas: res.data }
      }).catch (err => {
          console.log('报错了啊')
      })
    },
    methods: {
      deletFn(id) {
        axios.get('http://localhost:3333/api/newsdelet/' + id)
        .then((res) => {
          alert('The article is deleted successfully!')
          location.reload()
        }).catch (err => {
            console.log('报错了啊', err)
        })
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2630">#c2630</a>)</em></sub></div>

**Comment by ITCNZ** [comment]
Who can tell me? please

**Comment by LauerPaul** [comment]
window.location.reload(true)

**Comment by aldarund** [comment]
asyncData will be executed on location reload on server if running in universal mode.
