### ISSUE TITLE
How to set meta robots tag?

### ISSUE THREAD

**Issue by vietlai1190** [nuxt/nuxt.js#3036]
I have two environment (Development & Production).
So i want to set index & follow on production env, and noindex & nofollow on development env.
Thanks!

**Comment by manniL** [comment]
You can set up meta information in your page component through the `head()` method:
```js
<script>
export default {
  head () {
    return {
      meta: [
        { hid: 'robots', name: 'robots', content: 'noindex' }
      ]
    }
  }
}
</script>
```

Together with `process.env.NODE_ENV` you can set the robots information as needed.
