### ISSUE TITLE
router-view

### ISSUE THREAD

**Issue by GuitarHusky** [nuxt/nuxt.js#3038]
Vue-router how to write in this framework, I want to configure the same routing exit as Vue.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2633">#c2633</a>)</em></sub></div>

**Comment by moedong** [comment]
Is there any solution？

**Comment by GuitarHusky** [comment]
https://zh.nuxtjs.org/api/components-nuxt-child#-lt-nuxt-child-gt-%E7%BB%84%E4%BB%B6
