### ISSUE TITLE
Same route different component

### ISSUE THREAD

**Issue by paolog22** [nuxt/nuxt.js#3046]
how to render different component base user role ?
example: 
admin :
  route: /test
  component: admin-component

user :
 route: /test
 component: user-component

**Comment by maarteNNNN** [comment]
You could make a vue component (admin-component). Then add the admin-component in the user-component. And check if the user is an admin with v-if.

**Comment by paolog22** [comment]
@maarteNNNN  i see... can i use it to asyncData ? so before the base load i already know what component is loaded

**Comment by maarteNNNN** [comment]
@paolog22 I'm pretty new to Nuxt, but normal Vue I would just make you admin-component
and in your user-component example in pug
```pug
v-if(userIsAdmin)
  admin-component
```
and for the javascript part
```javascript
import AdminComponent from '~/components/admin-component.vue'

export default {
  components: {
    AdminComponent
  },
  methods: {
     userIsAdmin () {
        //check if the user is admin and return it
    }
}
```
If you really need `asyncData`, I'm not yet qualified to answer how as I'm just getting started.

**Comment by paolog22** [comment]
got it thanks.

**Comment by luminarious** [comment]
You can simplify your code by using dynamic components: https://vuejs.org/v2/guide/components.html#Dynamic-Components
