### ISSUE TITLE
Compiling error using create-nuxt-app with both vuetify and bulma

### ISSUE THREAD

**Issue by maarteNNNN** [nuxt/nuxt.js#3047]
When using a boilerplate app with styling included I'm getting the following errors:
With Vuetify:
```shell
 ERROR  Failed to compile with 1 errors                                                                 1:51:37 AM

 error  in ./assets/app.styl

Module build failed: ValidationError: PostCSS Loader Invalid Options

options['useConfigFile'] is an invalid additional property


 @ ./assets/app.styl 4:14-186 13:3-17:5 14:22-194
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

With Bulma:
```shell
 ERROR  Failed to compile with 1 errors                                                                 1:55:37 AM

 error  in ./node_modules/bulma/css/bulma.css

Module build failed: ValidationError: PostCSS Loader Invalid Options

options['useConfigFile'] is an invalid additional property


 @ ./node_modules/bulma/css/bulma.css 4:14-118 13:3-17:5 14:22-126
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```
I tried both with npm and yarn and without eslint
Commenting out the vuetify section in nuxt.config.js
```javascript
      // if (ctx.isServer) {
      //   config.externals = [
      //     nodeExternals({
      //       whitelist: [/^vuetify/]
      //     })
      //   ]
      // }
```
Makes the application work without styling.

**Comment by saknarak** [comment]
I have sample problem too.
I found that postcss-loader just release v2.1.2 8 hours ago
So i try to install previous version
```
npm install postcss-loader@^2.1.1
```
It's working now!

hope this can help you to work around this problem.

**Comment by saknarak** [comment]
I found the root cause
in postcss-loader@2.1.2, option was changed.

You have to change node_modules/postcss-loader/lib/options.json
```additionalProperties``` from ```false``` back to ```true```

**Comment by maarteNNNN** [comment]
@saknarak That indeed solved the issue! Thanks!

**Comment by maarteNNNN** [comment]
Maybe it's good to clarify it's the bottom `additionalProperties`

**Comment by pmbuban** [comment]
Thanks @saknarak, I decided to learn vue/nuxt today and things just weren't working until I found this. Guess I chose a rough day to start learning lol

**Comment by CurtisBelt** [comment]
If you use yarn, you can add a `resolutions` block to `package.json` and reinstall.

Felt like this was a better solution than the others as I will notice this later and remember to check for an update - vs the other fixes that could get overridden or forgotten.

```
"dependencies": {
  // stuff
},
"devDependencies": {
  // stuff
},
"resolutions": {
  "postcss-loader": "=2.1.1"
}
```

**Comment by pirmax** [comment]
@CurtisBelt I tried your technique but when pushing to master, I have a build that is done automatically with Dokku, I feel that it does not take into account the resolutions or the maximum version of postcss-loader that I want.
