### ISSUE TITLE
"Failed to compile" "PostCSS Loader Invalid Options" useConfigFile is an invalid additional property

### ISSUE THREAD

**Issue by koresar** [nuxt/nuxt.js#3048]
`npm run dev` fails to compile fresh new nuxt.js project.

Nuxt.js v1.4.0

How to reproduce:
```
vue init vuetifyjs/nuxt my-project
cd my-project
npm i
npm run dev
```

You will see this error in the console:
```
⋊> ~/c/my-project npm run dev

> my-project@1.0.0 dev /Users/vasyl/code/my-project
> nuxt

  nuxt:build App root: /Users/vasyl/code/my-project +0ms
  nuxt:build Generating /Users/vasyl/code/my-project/.nuxt files... +1ms
  nuxt:build Generating files... +48ms
  nuxt:build Generating routes... +12ms
  nuxt:build Building files... +28ms
  nuxt:build Adding webpack middleware... +818ms
  ████████████████████ 100%

Build completed in 7.46s

 ERROR  Failed to compile with 1 errors                                                                           16:53:08

 error  in ./assets/style/app.styl

Module build failed: ValidationError: PostCSS Loader Invalid Options

options['useConfigFile'] is an invalid additional property


 @ ./assets/style/app.styl 4:14-195 13:3-17:5 14:22-203
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

Temporary not really stable workaround.
* Open the file `./node_modules/nuxt/lib/builder/webpack/postcss.js`
* Comment out the line with `useConfigFile: false`
* Run `npm run dev` - all OK this time.

**Comment by gonza01001** [comment]
The same

**Comment by derevandal** [comment]
The same

**Comment by derevandal** [comment]
Thanks!
I made a script to do this through `npm run` (for Ubuntu).

1. make a file called replace.sh in project's root folder containing:
``` bash
#!/usr/bin/env bash
echo "sed -i -e 's/useConfigFile: false,/ /g' ./node_modules/nuxt/lib/builder/webpack/postcss.js
```

2. add this in scripts' package.json
``` js
    "replace": "./replace.sh"
```
it will look like this:
```js
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint",
    "replace": "./replace.sh"
  },
```

3. wait for update ;)

**Comment by toreskogp** [comment]
It seems to be a problem after postcss-loader updated to 2.1.2.

Setting the version of postcss-loader to  2.1.1 solved the problem form me.

**Comment by derevandal** [comment]
Look at postcss-loader github:
https://github.com/postcss/postcss-loader/issues/347

**Comment by acidbiscuit** [comment]
Locking the version of postcss-loader at 2.1.1 for nuxt dependencies in package-lock.json resolves the issue.

**Comment by bovas85** [comment]
for now you can solve this by installing in dev dependancies manually postcss-loader@2.1.1

**Comment by deltacat** [comment]
same issue. use `npm install --save-dev postcss-loader@2.1.1` fixed.

**Comment by pirmax** [comment]
The same problem for me! Downgrade package doesn't works for me, when I push on production, I get back this error.

**Comment by bovas85** [comment]
hmm very odd, what do you mean with pushing on production @pirmax

**Comment by derevandal** [comment]
@pirmax do u try `npm install --save-dev postcss-loader@2.1.1`?

**Comment by pirmax** [comment]
@derevandal Yes, I tried, with Yarn :+1: 

@bovas85 I mean, I pushing on production with Dokku, while push, the build is OK, but in console the build got me an error: https://pastebin.com/05vunrzx

**Comment by bovas85** [comment]
Did you try removing the node_modules folder or doing npm rebuild ?

**Comment by javialon26** [comment]
same here! i solved with postcss-loader@2.1.1 in devDependencies.

@pirmax check the yarn.lock maybe the version is locked here.

**Comment by pirmax** [comment]
How I can update only yarn.lock instead of package.json? I don't know packages very well...

**Comment by kieusonlam** [comment]
postcss-loader@2.1.3 is released

**Comment by koresar** [comment]
The owner of the postcss-loader is a very kind person. He solved the issue for all of us.
Thank you @ai !
