### ISSUE TITLE
Multiple webapps with one nuxtjs instance?

### ISSUE THREAD

**Issue by nwocykra** [nuxt/nuxt.js#3049]
Hi, 

Is there a way for a single nuxtjs webapp to serve multiple webapps on different domains for instance like so:

webapp1.com -> pages/webapp1/index.vue
webapp2.com -> pages/webapp2/index.vue

The problem is these sites will have most of the background functionality, layouts, stylesheets in common, only the purpose is slightly different and so some text and pictures are different.
So I would like to avoid maintaining them as two different projects.

I managed to set this up nginx to serve webapp1 and webapp2 by adding their individual paths. Everything loads well first but in the end of it it errors out with: 
> vue.runtime.esm.js:574 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

Any suggestions?

Nicklas

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2642">#c2642</a>)</em></sub></div>

**Comment by silvio-e** [comment]
@nwocykra I guess the error you get should be caused by an error in your code as it said and not regarding the serving.
I'm approaching something similar just with Varnish instead of Nginx and it seems to work pretty well.
Regarding your paths - why are you pointing directly to a index.vue file?

**Comment by galvez** [comment]
You can have an upstream server route both domain requests to the same app and treat the requests in a Nuxt middleware.
