### ISSUE TITLE
Access store or req obj in plugins

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#305]
Hi,
  I need to set the user's token before making a request via axios.
Now axios is added as a plugin just like how it is shown in the docs. 
The api's are in another server which needs the users token. I need to add this to the authorisation header for every request like this

    axios.defaults.headers.common['Authorization'] = 'JWT ' + token;

This token is present in the req obj and is added to the store via middleware. I can't add it to the env because token is different for each user;

Is there any way to access the store or the req obj while a plugin is getting initialised? If not what are the other ways to achieve this

**Comment by alexchopin** [comment]
You should not set axios headers in the plugin because it change for every users.

**Comment by Atinux** [comment]
@shyamchandranmec actually the next version will have the context in the plugins ✋

**Comment by shyamchandranmec** [comment]
@alexchopin Good to know that this will be added to the next version. When are you planning to release the next version?
