### ISSUE TITLE
'<template>' cannot be keyed. Place the key on real elements instead

### ISSUE THREAD

**Issue by SimonSun1988** [nuxt/nuxt.js#3050]
when i use `v-for` in <template> like this, will get this error

```
<template v-for="(item, index) in list" :key="index">
</template>
```

but if i remove `:key="index"`，`eslint` will tell me bind key error.

how should i do or how to edit nuxt.config.js?

**Comment by yoyo837** [comment]
`:key` Cannot be used on template tag. This is related to `vue` rather than `nuxt`.
```html
<template v-for="(item, index) in list">
<span :key="index"></span>
</template>
```

**Comment by husayt** [comment]
or
```
<span v-for="(item, index) in list"  :key="index"></span>
```
