### ISSUE TITLE
 Is it possible to use better-sqlite3 in a Nuxt.js environment?

### ISSUE THREAD

**Issue by jasonkhanlardr** [nuxt/nuxt.js#3053]
Is it possible to use better-sqlite3 in a Nuxt.js environment? Note: `npm install --save better-sqlite3`

In my nuxt.config.js:
```
module.export = {
  ...
  build: {
    ...
    vender: [
      ...
      'better-sqlite3'
    ]
  }
  ...
}
```
results in:
```
Failed to compile with 2 errors
This dependency was not found:
* fs in ./node_modules/better-sqlite3/lib/util.js, ./node_modules/bindings/bindings.js
To install it, you can run: npm install --save fs
```
Also https://github.com/JoshuaWise/better-sqlite3/issues/107

Alternatively, is it possible to read and write to an SQLite database file with Nuxt in general?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2644">#c2644</a>)</em></sub></div>

**Comment by luminarious** [comment]
Architecturally it would make more sense to put SQLite with an API into a separate container anyway?

Or if you want to combine them, https://github.com/nuxt-community/hapi-nuxt is a good starting point.
