### ISSUE TITLE
How can i use redirect from inside the component's methods?

### ISSUE THREAD

**Issue by rosancoderian** [nuxt/nuxt.js#306]
How can i use redirect from inside the component's methods?
usually i assign the redirect method to global variable, is there any more elegant way to do this?

**Comment by alexchopin** [comment]
You can use `this.router.push(URL)`, see (vue-router documentation)[https://router.vuejs.org/en/essentials/navigation.html]

**Comment by lmj0011** [comment]
>You can use this.router.push(URL)

What's the purpose of having `redirect` function come in from the context object?

**Comment by lmj0011** [comment]
>You can use this.router.push(URL)

`this.$router.push(URL)`
