### ISSUE TITLE
Hot code reloading not working

### ISSUE THREAD

**Issue by jhhosbond** [nuxt/nuxt.js#3061]
Hi,

Great work - it seems very promising!

I've just setup a Nuxt project for the first time. All seems to work as intended, but I cannot seem to get "Hot Code Reloading" working. When I'm running e.g. npm run dev and the site is at http://localhost:3000 should the page update itself, when changing e.g. content in a component, page or css file?
 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2649">#c2649</a>)</em></sub></div>

**Comment by husayt** [comment]
yes, it should whenever you make changes to files in source directory. Which files are you changing and you don't see refresh? What happens in console this time?

**Comment by jhhosbond** [comment]
I'm e.g. changing content of the vue files in the pages folder. But, also changes to vue files in the layout folder or components folder seem to force hot reload. The console does not provide any hints or report errors. BTW I've used to Nuxt PWA as starter template. Is there another Nuxt starter template I should be using to see the hot reloading working?

**Comment by tetreault** [comment]
Chiming in here - hot reloading *was* functional in my nuxt project when i last touched it 16 days ago. Now it is no longer functional. `npm run start` wont do any hot reloading. If i want to see any changes I need to do `npm run build` and `npm run start`. 

Only other work I've been doing the past two weeks was on 2 unrelated projects (one vanilla JS w/ only gulp as a build tool; the other being minor react projects). 

Any chance anyone has some guidance on why hot reloading is no longer functional?

**Comment by tetreault** [comment]
@jhhosbond sounds silly but are you sure you're running `npm run dev`? I ran into this issue due to a silly mistake, I was running `npm run start` which wasn't hot reloading.

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.

**Comment by nomad354** [comment]
[2018-08-21T16_09_34_840Z-debug.log](https://github.com/nuxt/nuxt.js/files/2307093/2018-08-21T16_09_34_840Z-debug.log)
The problem is urgent, I still get errors.

**Comment by paulgv** [comment]
@nomad354 a few things I would try:

- `rm -rf node_modules && npm i && npm run dev`
- `nvm install 8 && rm -rf node_modules && npm i && npm run dev`

If you have Yarn installed:

- `rm -rf node_modules && yarn && yarn dev`

**Comment by nomad354** [comment]
@paulgv Yes, I tried it. The error persists:
[2018-08-22T07_08_43_759Z-debug.log](https://github.com/nuxt/nuxt.js/files/2309256/2018-08-22T07_08_43_759Z-debug.log)

**Comment by manniL** [comment]
@nomad354 This shouldn't be a nuxt-related issue. `ELIFECYCLE error` means the program stopped unexpectedly. There can be several reasons behind it. As there is no "real error message" included (see an example below) we can only guess. A few points worth trying:

* Try another PORT
* Try to run it directly with node instead of using npm scripts

```js
events.js:160
  throw er; // Unhandled 'error' event
  ^

Error: listen EADDRINUSE :::430
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at Server._listen2 (net.js:1258:14)
at listen (net.js:1294:10)
at Server.listen (net.js:1390:5)
at EventEmitter.listen (/home/fedora/Scrivania/my-telegram-
bot/node_modules/express/lib/application.js:618:24)
at Object.<anonymous> (/home/fedora/Scrivania/my-telegram-bot/index.js:43:5)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
```

**Comment by nomad354** [comment]
Thanks for the help! The error was found on the side of Ubuntu. There was not enough memory. Here's the solution, it helped me:
[https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers)
