### ISSUE TITLE
How to inject html outside of nuxt app

### ISSUE THREAD

**Issue by nickngqs** [nuxt/nuxt.js#3062]
Is it possible to inject custom html outside of nuxt app in spa mode

Example
```
body
    form
    #__nuxt
```

My current work around is after build or generate, add html in every page.

Example use cases, is netlify, which requires a html form to be detected. Since if the form is inside the nuxt app, the form is javascript rendered.

**Comment by NicoPennec** [comment]
i'm not sure to have understood your use case, but you can extend the HTML template, create `app.html` at the root of your project, with a custom <body> element

```html
// app.html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>

    <form><!-- here --></form>

    {{ APP }}
  </body>
</html>

```

see doc: https://nuxtjs.org/guide/views#document

**Comment by nickngqs** [comment]
Yes, this is what i'm looking for! Thanks alot!

**Comment by begueradj** [comment]
@NicoPennec  When I create `app.html` at the root directory and insert the code you shared, I get an error  saying: `ReferenceError App is not defined`. How to fix this? `App` is not defined anywhere by default, what does it refer to ? Thank you.
