### ISSUE TITLE
Where is the source code of renderRoute located

### ISSUE THREAD

**Issue by JacobWay** [nuxt/nuxt.js#3065]
I read the readme of nuxt.js, and there is an example of rendering an specific route.

```
nuxt.renderRoute('/about', context)
.then(function ({ html, error }) {
  // You can check error to know if your app displayed the error page for this route
  // Useful to set the correct status code if an error appended:
  if (error) {
    return res.status(error.statusCode || 500).send(html)
  }
  res.send(html)
})
.catch(function (error) {
  // And error appended while rendering the route
})
```

But I can not find the source code of the method of renderRoute in the source of nuxt.js. Where is it located?

**Comment by NicoPennec** [comment]
@JacobWay this one?

renderRoute declaration (L39) => https://github.com/nuxt/nuxt.js/blob/85d6c5758a9bfdfa0946e88ccec9dbdfd762cd4b/lib/core/nuxt.mjs#L39

rendererRoute method (L287)=> https://github.com/nuxt/nuxt.js/blob/85d6c5758a9bfdfa0946e88ccec9dbdfd762cd4b/lib/core/renderer.mjs#L287
