### ISSUE TITLE
How can I figure out the layout work process from the source code of nuxt.js?

### ISSUE THREAD

**Issue by JacobWay** [nuxt/nuxt.js#3066]
You can build custom layout under the directory of layout under the project. How can I figure out how does it work from the source code of nuxt.js?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2653">#c2653</a>)</em></sub></div>

**Comment by benoitemile** [comment]
I'm not sure about your request but I guess you should probably read the source code of nuxt, [here's](https://github.com/nuxt/nuxt.js/blob/dev/lib/app/App.js) a part about getting the layout and filling it

**Comment by JacobWay** [comment]
In the file, https://github.com/nuxt/nuxt.js/blob/dev/lib/app/App.js,
there is <%,
what is the syntax of js?


```
<% if (loading) { %>import NuxtLoading from '<%= (typeof loading === "string" ? loading : "./components/nuxt-loading.vue") %>'<% } %>
<% css.forEach(function (c) { %>
import '<%= relativeToBuild(resolvePath(c.src || c)) %>'
<% }) %>
```

**Comment by benoitemile** [comment]
This file is being processed while you do your nuxt build, all <% blocks being replaced by config stuff.
You should try to look at the .nuxt/ (hidden folder on macOS) where all of nuxt build files are.
Sample : https://i.imgur.com/LerK0MN.png

**Comment by galvez** [comment]
Closing this as there's been no updates over 90 days.
