### ISSUE TITLE
Module hooks documentation

### ISSUE THREAD

**Issue by derevandal** [nuxt/nuxt.js#3069]
Hi,

Where are module hooks documentation?
The link in released v.1.0.0 is broken.
Could anyone help me?

Thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2656">#c2656</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
@derevandal  see the github doc repository https://github.com/nuxt/docs/blob/c6493850060aa798542abcc811ced23c3c401fab/en/guide/modules.md#run-tasks-on-specific-hooks

**Comment by derevandal** [comment]
Thanks, bro!

De: Nicolas PENNEC
Enviado:terça-feira, 20 de março de 2018 14:41
Para: nuxt/nuxt.js
Cc:André Van Dal; Mention
Assunto: Re: [nuxt/nuxt.js] Module hooks documentation (#3069)

@derevandal see the github doc repository https://github.com/nuxt/docs/blob/c6493850060aa798542abcc811ced23c3c401fab/en/guide/modules.md#run-tasks-on-specific-hooks
