### ISSUE TITLE
Nuxt.js with Socket.io Sample

### ISSUE THREAD

**Issue by edmondyip** [nuxt/nuxt.js#307]
Hi, i am new at Javascript framework.
I have find a sample [here](https://sockets.nuxtjs.org/)
I try to follow [this](https://github.com/nuxt/nuxt.js/tree/master/examples/with-sockets) to build  a sample

But i can't run socket.io under https
When can i have more description for this sample?

**Comment by alexchopin** [comment]
That's weird because our example is running under https.
It's exactly the code from the example you have linked.
