### ISSUE TITLE
Loading indicator also visible in ssr

### ISSUE THREAD

**Issue by Diolor** [nuxt/nuxt.js#3072]
Hey! 
Minor but crazy but here 😄 
I make this conditional mode rendering:

```
  serverMiddleware: [{
    handler(req, res, next) {
      let isBot = crawlersRegex.test(req.headers['user-agent'])
      res.spa = !isBot
      next()
    }
  }]
```

Sometimes (maybe when server is slow) the loading indicator will also be visible when there is a bot user agent. In practice google crawls my page and only the loading indicator is visible.

If I always have `res.spa = false` the bug will not appear. It appears only then the spa can change.
Potentially some caching in the nuxt cure from the last request?

### Reproduce:
Chome with GoogleBot user agent. 
Open the element inspector.
Hit refresh (repeat only after a full page load, repeat until the issue appears).
Sometimes the loading indicator will be visible for few millis even if all requests are made with a `GoogleBot` user agent (aka spa=false).

### Workaround:
`loadingIndicator: false`

**Comment by Diolor** [comment]
Hmm actually something is more wrong with this conditional rendering. Will open another ticker

**Comment by pi0** [comment]
@Diolor Please let me know about updates! Also for nuxt 2, we disabled loadingIndicator by default. You can test (unstable) changes by using `nuxt-edge` instead of `nuxt`.

**Comment by Diolor** [comment]
I think loading indicator is okay. I'll give `nuxt-edge` a spin but the real problem looks like this one #3073
