### ISSUE TITLE
Google crawler parses empty DOM with SSR

### ISSUE THREAD

**Issue by Diolor** [nuxt/nuxt.js#3073]
Logic below explained: 
If user agent is a crawler/bot (e.g. google), then render the page with SSR.

```js
  serverMiddleware: [{
    handler(req, res, next) {
      let isBot = crawlersRegex.test(req.headers['user-agent'])
      res.spa = !isBot
      next()
    }
  }]
```
---------

Using the fetch as google:
https://www.google.com/webmasters/tools/googlebot-fetch

I get this strange result:
![image](https://user-images.githubusercontent.com/1686807/37685991-de7ac1d4-2c95-11e8-8b92-d1578898c6cf.png)

Obviously the content is empty. That was when loading indicator is disabled. 

If loading indicator is enabled, then the loading indicator will be there:
![image](https://user-images.githubusercontent.com/1686807/37686039-126fd6f0-2c96-11e8-976f-5a67c68a50b3.png)

---------

### Other:
- Google uses `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`  User Agent. If I fake it in my chrome, I get correctly a SSR rendering.
- Curl returns the correct DOM structure if a bot agent (like the above) is used
- Google result looks like they get a CSR rendering
- Facebook, twitter etc parse the content also correctly (e.g. from the open graph meta). This issue happens only with google crawler.

### Assumptions:
- If no one else is affected from this but me, then the conditional rendering above might be an issue
- If Nuxt returns basic initial html and the Google crawler is programmed to stop when there is some html (even before the server has not completed) this might also be a reason

### Update:
 - If I force set `res.spa = false` in every request, google will render the results correctly. Therefore something is happening with the conditional rendering

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2660">#c2660</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks for the detailed information. Will check it out soon.

**Comment by benoitemile** [comment]
hi @Diolor, I guess it has something to do with your regex, could you please show us what crawlersRegex looks like ?

**Comment by Diolor** [comment]
Potentially. I will debug again to be sure.

**Comment by Diolor** [comment]
I mill mark this as closed since I am mostly sure there was an issue in the regex.

**Comment by merijnvanessen** [comment]
How did you solved this? I have the same problem
Fetch as google only shows me the navigation but not the <nuxt> component

1) I use middleware to check the url to be loaded for the api data.. 
2) The url is passed to a store action where axios is loading the data
3) In the page template the data is injected by a computed property

This gave me a smooth result went [browsing](http://www.erasmusfoodlab.nl/behavioral-food-lab) the page


![schermafbeelding 2018-08-23 om 08 01 48](https://user-images.githubusercontent.com/23075300/44507428-d00d8c00-a6aa-11e8-8758-1c14dfb5cd71.png)
