### ISSUE TITLE
 How to extract each page style file into an independent file

### ISSUE THREAD

**Issue by binggg** [nuxt/nuxt.js#3074]
Hi, all

Nuxt.js support extract all the common css in a file. 

```js
build: {
    extractCSS: {
      allChunks: true
    }
}
```
My config is above, and 
I am facing style conflict and coverage issues.

Because my css is mostly import like this 

```html
<style src="@/assets/css/reset.css">
</style>
<style src="@/assets/css/common.css">
</style>
```

If I set `allChunks` to `false`, all the css is injected in the ssr html page, which cause content-size too big.

So I am looking for a way to extract each page style file into an independent file, every page will link an independent css file. This could solve the questions of  style conflict and  ssr html content-size too big.

Thanks for help.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2661">#c2661</a>)</em></sub></div>

**Comment by setLylToxlx** [comment]
@binggg 
 Did you solve your problem? 
How to solve?
I have the same needs, if you have solved the problem, pelaese provide your plan

**Comment by binggg** [comment]
@setLylToxlx 

Not yet.

**Comment by sebbean** [comment]
SAME GUYS @binggg  @setLylToxlx

**Comment by hardikshah91** [comment]
Please share the idea how to extract each page CSS into a separate file.

**Comment by setLylToxlx** [comment]
@sebbean  I am trying nuxt-edge, able to solve part,  nuxt2 may solve some problems

**Comment by monkviper** [comment]
same issues guys

**Comment by leonfather** [comment]
Same issues @setLylToxlx any plan to solve this problem?

**Comment by manniL** [comment]
As explained in https://github.com/nuxt/nuxt.js/issues/2588#issuecomment-411342410, this is the default behavior when using `extractCSS: true` with `nuxt-edge` now.

**Comment by willin** [comment]
not fixed yet??
