### ISSUE TITLE
Compling time is negative

### ISSUE THREAD

**Issue by HADB** [nuxt/nuxt.js#3075]
After running `npm run dev`, the last message is `DONE  Compiled successfully in -8138ms`.
See as follows:
<img width="331" alt="qq20180321-134907 2x" src="https://user-images.githubusercontent.com/1836701/37696050-a83f47b0-2d0e-11e8-8959-2a2f9a963365.png">

**Comment by pi0** [comment]
Hi. This is a known issue with nuxt 1.x :( But good news is that is will be resolved soon with upcoming version :)

**Comment by yoyo837** [comment]
duplicate #2930
