### ISSUE TITLE
how can i use static file, it always throws error

### ISSUE THREAD

**Issue by Haven09** [nuxt/nuxt.js#3076]
Why it is wrong at the code `background: url(../static/img/login_bg.png)` ?

![image](https://user-images.githubusercontent.com/19543302/37702668-40744a20-2d2e-11e8-8053-5ba6b92d4f0e.png)

**Comment by NicoPennec** [comment]
try with `url(/img/login_bg.png)`

the `static` folder is publish at root on run serve.

**Comment by Haven09** [comment]
It is wrong too.
![image](https://user-images.githubusercontent.com/19543302/37746185-f53fa758-2db3-11e8-9a09-211936f785d2.png)

**Comment by Haven09** [comment]
Sorry,this static file is type of .jpg, not .png.This is why i got a 404 error.
