### ISSUE TITLE
Global middleware exclude list

### ISSUE THREAD

**Issue by Cengkaruk** [nuxt/nuxt.js#308]
Hi @Atinux 

I'm using global middleware to protect authenticated pages. At the middleware, i'm just redirect to `/` and there is the problem, redirect loop when visiting `/`.

I know we can use middleware on every pages, but to much pages. It would be nice if we can exclude some pages.

Any suggestion?

**Comment by alexchopin** [comment]
Use `middleware` property only on page you need or a condition in your middleware with `router.path`

**Comment by Cengkaruk** [comment]
Thanks @alexchopin
