### ISSUE TITLE
Error: bundle export should be a function when using { runInNewContext: false }

### ISSUE THREAD

**Issue by MrVichr** [nuxt/nuxt.js#3080]
I'm just starting with Nuxt.js, tried to start from a template
`vue init nuxt-community/typescript-template front`
and changed `srcDir` to `srcDir: './front/'`. Then I copied things that looked important from `front/package.json` and `front/tsconfig.json` one level up.

The process wasn't very straightforward so I might have made a mistake somewhere. Anyway, now it compiles and starts fine using "nuxt" command, but when I open the page localhost:3000, it displays a NuxtServerError page with nice debug info. The server console says:

```
{ Error: bundle export should be a function when using { runInNewContext: false }.
    at j:\types\CML\node_modules\vue-server-renderer\build.js:8401:17
    at new Promise (<anonymous>)
    at j:\types\CML\node_modules\vue-server-renderer\build.js:8388:14
    at Object.renderToString (j:\types\CML\node_modules\vue-server-renderer\build.js:8564:9)
    at Renderer.renderRoute (j:\types\CML\node_modules\nuxt\lib\core\renderer.js:344:41)
    at Renderer.nuxtMiddleware (j:\types\CML\node_modules\nuxt\lib\core\middleware\nuxt.js:12:31)
    at call (j:\types\CML\node_modules\connect\index.js:239:7)
    at next (j:\types\CML\node_modules\connect\index.js:183:5)
    at SendStream.error (j:\types\CML\node_modules\nuxt\node_modules\serve-static\index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (j:\types\CML\node_modules\nuxt\node_modules\send\index.js:270:17)
    at SendStream.onStatError (j:\types\CML\node_modules\nuxt\node_modules\send\index.js:421:12)
    at next (j:\types\CML\node_modules\nuxt\node_modules\send\index.js:764:28)
    at j:\types\CML\node_modules\nuxt\node_modules\send\index.js:772:23
    at FSReqWrap.oncomplete (fs.js:152:21) statusCode: 500, name: 'NuxtServerError' }
```
This is the content of runner, entry, files, basedir and runInNewcontext just before the error:
```javascript
runner =  {}
entry= server-bundle.js
basedir= j:\types\CML
runInNewcontext= false
files={'pages_index.js': 'exports.ids = [0]; exports.modules = {/***/ 56:/***/ (function(...' ,
       'layouts_default.js': 'exports.ids = [1]; exports.modules = {/***/ 58:/***/ (function...' ,
       'server-bundle.js': 'module.exports =/******/ (function(modules) {...'   }
```
I have no idea what's going on. As I said, I started using Nuxt yesterday and probably stop today.

IMHO, the framework would greatly benefit from improved error messages.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2666">#c2666</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @MrVichr. Sorry to hear that. Actually, this problem is rare and may depend on your local dev environment. Would you please share a link to Github for your code? I would be happy to help in resolving the problem.

**Comment by MrVichr** [comment]
I think https://github.com/MrVichr/CML-in-Nuxt should be a demo. Run it with
npm run **n**dev
I remember I had to use
npm install --save-dev postcss-loader@2.1.1
because there's some problem with postcss-loader, there's an issue opened for that. Everything else should be up-to-date... I think.
Thanks for help.

**Comment by Chathula** [comment]
@pi0, our dev team also had the same problem. again we build the project(did a change and save rebuild is ok too) error disappeared. not only this. we got few more errors like toLowerCase function not found etc(i don't clearly remember the error). our devs environment is widnows 10. is there any explanation why is that happened. i am using linux and i didn't get any issue. these errors were come from core.

**Comment by Chathula** [comment]
@MrVichr, yes there was a postcss loader issue. i also had to add it separately with the specified version. 
@pi0 , is there any explanation about that postcss issue?

**Comment by Chathula** [comment]
postcss-loader 2.1.3 has been shipped with the fix.

https://github.com/postcss/postcss-loader/issues/347
