### ISSUE TITLE
How can I always run lint on nuxt?

### ISSUE THREAD

**Issue by uto-usui** [nuxt/nuxt.js#3081]
HI.

The lint command is prepared for the project created by "vue init nuxt / starter".
When developing with the dev command, I want to apply es-lint every time I save the file.
Is there a smart way to achieve this flow?

Could anyone help me?
Thanks.

**Comment by pi0** [comment]
Yes! It is possible using [fix option](https://github.com/webpack-contrib/eslint-loader#fix-default-false). (Credits goes to @Tabrizian for this find :D)

**Comment by uto-usui** [comment]
It's great.
Thank you for giving me the perfect answer soon :)
