### ISSUE TITLE
target='_blank' disabled on links

### ISSUE THREAD

**Issue by tchret** [nuxt/nuxt.js#3083]
I'm facing a weird issue on [my website](tchret.com) (powered by nuxt), all the external links are target `_blank`, but don't properly open a new tab 

(Chrome)

**Comment by incrediblink** [comment]
They open properly in my browser (Firefox).

**Comment by husayt** [comment]
It works fine. Hence closing

**Comment by tchret** [comment]
@husayt: try to click on the "See more" of this section, it doesn't work for me on Chrome 65

![image](https://user-images.githubusercontent.com/4539476/37985500-cf081656-31f0-11e8-9856-644145bf745f.png)
