### ISSUE TITLE
Possibility to change default route name

### ISSUE THREAD

**Issue by andrecavallari** [nuxt/nuxt.js#3084]
I suggest the ability to change the default route name...

For example...

/pages/users/_id.vue names to users-id, but if I want to use just name "user" I cant, and the problem is that I had the route: /users/:id but I had to add then into folders to have /cars/users/:id, then I had do check every <nuxt-link> where I was using the name users-id and change to cars-users-id, if I had the possibility to change the default, this could be fixed quickly...

A suggestion is:

<script>
export default {
    routeName:'user'
}
</script>

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2670">#c2670</a>)</em></sub></div>

**Comment by andrecavallari** [comment]
Anything about it?

**Comment by lucpotage** [comment]
Did you try to use the extendRoutes property of router? Maybe it could work?

https://nuxtjs.org/api/configuration-router/#extendroutes

**Comment by andrecavallari** [comment]
@lucpotage, first, thanks for the answear, but I would really like to keep using the auto routes from nuxt... I think a simple routeName in export default {} would be very great

**Comment by manniL** [comment]
Further discussions: #3589
