### ISSUE TITLE
Promise undefined in babel-runtime 

### ISSUE THREAD

**Issue by paolog22** [nuxt/nuxt.js#3087]
![image](https://user-images.githubusercontent.com/12680745/37748151-b68bf4b2-2dbd-11e8-84c7-4077fea46984.png)

what i did wrong? help

**Comment by husayt** [comment]
Why do you have `_` before Promise?

I will have to close this as it is not Nuxt issue.

**Comment by paolog22** [comment]
@husayt it automatically added. i think webpack added it
