### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by Kevinl7** [nuxt/nuxt.js#3089]
npm run build   then   No build folder is generated
my nuxt version  1.0.0
![image](https://user-images.githubusercontent.com/22197685/37755536-d92640a4-2de0-11e8-9a70-101066dd2514.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2674">#c2674</a>)</em></sub></div>

**Comment by sKawashima** [comment]
Please try 'nuxt generate'.
If it does not work please show package.json.

**Comment by Kevinl7** [comment]
no,  I first use “npm run generate”，
but   index.html page  label（body, div）  are not closed  under the compiled dist folde,
![image](https://user-images.githubusercontent.com/22197685/37757040-8f3c888a-2de6-11e8-99a0-c311bf75c885.png)

then, 
I use "npm run build" ,
no build folde
![image](https://user-images.githubusercontent.com/22197685/37756924-23b270ca-2de6-11e8-9e0d-5eea4d392680.png)

**Comment by sKawashima** [comment]
> but index.html page label（body, div） are not closed under the compiled dist folde,
This is not probrem.

You can omit those tags.
https://html.spec.whatwg.org/multipage/syntax.html#optional-tags

**Comment by Kevinl7** [comment]
I konw it's not problem
but, my index.html  not normal display   but " npm run dev " normal
"npm run build"  no build folder ？
How to solve？
my package.json download   I don't edit it.

Thank you

**Comment by sKawashima** [comment]
maybe.., generated in the '.nuxt' folder.

**Comment by husayt** [comment]
Try 

a) latest nuxt 1.4.0
b) delete dist folder before `npm run generate`

**Comment by Kevinl7** [comment]
I tried it or I couldn't
