### ISSUE TITLE
Error with babel when webpack compilation.

### ISSUE THREAD

**Issue by mathieutu** [nuxt/nuxt.js#3090]
Hi!
I've a problem with babel during webpack compilation.
A file shared by node and webpack works well on node, but throw a warning `21:19-32 "export 'clientMapping' was not found in '~/config/user'` and then a `TypeError: Cannot assign to read only property 'exports' of object '#<Object>'` when showing the page.

I've seen that it works when bypassing babel when importing this file, but it's not a proper solution because I need babel inside it. I also tried to replace clientMapping by a plain object, and it works.

Do you see a problem in it or is it a bug?

Thanks for you help.

```js
// ~/config/user.js

const userMapping = {
    foo: 'bar',
};

// Also tried Object.assign without success.
const clientMapping = {
    ...userMapping,
    baz: 'test',
};

// This config file is called both by node and by webpack. It's why I use `module.exports`.
module.exports = {
    userMapping,
    clientMapping,
};
```

```js
// ~/models/Client.js

import {clientMapping} from '~/config/user'
...
```

```js
// ~/plugins/authClient.js

import Client from '~/models/Client';
...
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2675">#c2675</a>)</em></sub></div>

**Comment by mathieutu** [comment]
I've made a demo which reproduces exactly the problem: 
https://github.com/Meroje/nuxt-3090

**Comment by brussell98** [comment]
I've also encountered this issue twice recently.

First time was when I tried to return a promise with `return new Promise(...)`. Removing `Promise` would cause the issue to go away.
Second time I tried to use a `for ... of` loop and the same problems occurred.

**Comment by galvez** [comment]
Try:

```
export const userMapping = {
    foo: 'bar',
};

// Also tried Object.assign without success.
export const clientMapping = {
    ...userMapping,
    baz: 'test',
};
```

**Comment by galvez** [comment]
@mathieutu alright, I'll check out your test repo more carefully.

**Comment by galvez** [comment]
@mathieutu My apologies, I see the issue now. This is unfortunately unfixable without [esm](https://github.com/standard-things/esm), which nuxt-edge already uses. Right now the easiest fix is to use `export const` and upgrade to nuxt-edge, or you can use two separate files, one with ESM syntax and another with CJS syntax if you need to get this going with 1.4.2.

**Comment by galvez** [comment]
@mathieutu you can also try and get `esm` set up in your Nuxt 1.4.2 project, although I'm not entirely sure how well that would work.
