### ISSUE TITLE
i have a question~~~~help

### ISSUE THREAD

**Issue by shguanbin** [nuxt/nuxt.js#3094]
const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
                                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\GitDemo\nuxtDemo\node_modules\nuxt\lib\core\renderer.js:19:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-demo@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2678">#c2678</a>)</em></sub></div>

**Comment by HoraceKeung** [comment]
Are you trying to clone this.options.render.csp.policies if it is not null?

**Comment by husayt** [comment]
it is likely to do with your version of node. Which node version do you use? Try upgrading to 8+

**Comment by cdoneshot** [comment]
upgrade nodejs to 8.6+.

**Comment by David-Mueller** [comment]
(The problematic part of the code should have been removed with nuxt/nuxt.js#2945 as well...)

**Comment by nallown** [comment]
It's the spread operator that's the problem, show me your nuxt config file and your babelrc if you have one. Show all your config that touches babel.

You should be compiling your javascript down to a older version using babel. What browser are you using also?

**Comment by shguanbin** [comment]
thanks, upgrade nodejs~~~
