### ISSUE TITLE
too many dependencies in nuxt.js

### ISSUE THREAD

**Issue by jinze** [nuxt/nuxt.js#3095]
When I use nuxt.js as an expreess.js middleware, I have to install too much dependencies like "babel-core" "postcss" or "webpack" in production mode. So I think nuxt render should move to a seperate repo.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2679">#c2679</a>)</em></sub></div>

**Comment by clarkdo** [comment]
`nuxt-start` has been published for only including core functionality, it won't include the dependencies you mentioned.

Before 2.0 released, you can try `nuxt-edge-start` now.

https://www.npmjs.com/package/nuxt-edge-start
