### ISSUE TITLE
How to use dynamic NON-async components for nuxt generate

### ISSUE THREAD

**Issue by Coletrane** [nuxt/nuxt.js#3097]
I have a 2D array of posts like so:
```
const posts = [
    [
        'post-route-0',
        'post-route-1'
    ],
    [
        'post-route-2',
        'post-route-3'
    ]
]
```

I want to have a generic page component that IS async
index.vue:
```
const Page0 = () => import('../components/BlogPages/Page0')
```

Page0.vue:
```
<template>
  <abstract-page :page="0"/>
</template>
```

I want to have the post components within that page NOT async BUT still dynamic (so I can loop over the array) I want each instance of AbstractPage to be generated as one .js file.
AbstractPage.vue:
```
<template>
  <div v-for="postRoute of posts[page]">
    <component :is="postComponents.find(comp => comp.route === postRoute)"/>
  </div>
</template>

for (const postRoute of posts[this.page]) {
    const filename = routeToComponentFilename(postRoute)
    let esComponent = await import(`../PromoCards/${filename}`)
    const component = {
      route: postRoute,
      component: esComponent.default
    }
    this.postComponents.push(component)
}
```

My end goal for network requests (simplified) is: 
GET index.html
GET app.js
GET page0.js <-- precompiles the dynamic NON async post components

here is my repo for more context: https://github.com/Coletrane/mountain-bike-virginia/tree/posts-json-authors-json

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2681">#c2681</a>)</em></sub></div>

**Comment by husayt** [comment]
@Coletrane is [this](https://github.com/nuxt/nuxt.js/tree/dev/examples/dynamic-components) what you are after?

**Comment by Coletrane** [comment]
@husayt not exactly. I pulled down the example and ran `nuxt generate` on it and as you can see from the image below, each dynamic component still has a network call. What I'm looking for would be all the cards that appear on the page are compiled into one .js file, thus one network call. Another issue I have is that the base route is not lazy loading the routes since `ssr.8a0090dfb33cdcd71d26.js` is loaded.


![image](https://user-images.githubusercontent.com/14304647/37804631-83f65e86-2e0b-11e8-9031-409e1bb18787.png)

**Comment by galvez** [comment]
@Coletrane concatenating files [is no longer the best practice](https://yoast.com/ask-yoast-minify-concatenate-css-js-files/), if that's what you're after. This is not something worth exploring in nuxt's core, but I believe there are many webpack plugins you can look up though.
