### ISSUE TITLE
[Feature] Prevent duplicated content on generated routes

### ISSUE THREAD

**Issue by MitsuhaKitsune** [nuxt/nuxt.js#3100]
Hi,

Actually when I let nuxt to generate the routes automatically with my pages folder, it generate all routes without final trailing slash '/' for example `news`, but still accesible on url with http://localhost:3000/news and http://localhost:3000/news/ (both are the same route), this is a bad practice for SEO, the search engines detect it as duplicated content.

To prevent it, the vue-router allow set `pathToRegexpOptions: { strict: true }` option on routes that only meet the match if the path are exactly the same that defined on route, if i set the path as /news/ I only can access it with http://localhost:3000/news/ and can't with http://localhost:3000/news (show 404)

As I read on some SEO guides, the final trailing slash represent a directory for search engines, in other words, have more subpages, applied to nuxt, it can be achieved putting the final slash for each pages subdirectories and without final slash for each vue file.

## Example scenario

Files:

```
pages/
 |-index.vue
 |-contact.vue
 |-blog/
 |   |-index.vue
 |   |-_slug.vue
 |-otherpages/
    |-index.vue
    |-one.vue
    |-two.vue
```
Generated routes urls (should match exactly, any diference on path didnt meet the route, except the fourth url that it's dinamic but still working only without final slash):

```
/
/contact
/blog/
/blog/somedinamicslug
/otherpages/
/otherpages/one
/otherpages/two
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c2684">#c2684</a>)</em></sub></div>

**Comment by MitsuhaKitsune** [comment]
I start to working on this on https://github.com/MitsuhaKitsune/nuxt.js/tree/feature-3100 but I have problems to setup my local nuxt.js enviroment.

I clone nuxt.js on my PC, run npm install and npm link, then on my example app I run npm link nuxt, when I try to npm run dev the app open and load without problems but when I try to access to it on Firefox I get this error:

NuxtServerError
Cannot find module 'core-js/library/fn/promise' from 'C:\nuxttest'

Someone know how I can fix it?

**Comment by MitsuhaKitsune** [comment]
@archieDeveloper This option are created for autogenerated routes, never test it with extend or custom routes

**Comment by MitsuhaKitsune** [comment]
@galvez Yes I open a PR on https://github.com/nuxt/nuxt.js/pull/3448 but finally get rejected by atinux and pi0.

I close the PR but forget close the issue, closed now.

**Comment by Jesus82** [comment]
So is it impossible to generate a folder/page route without the trailing slash at the end? This harms SEO, as people tend not to write the final slash (for example, if my page is 'folder/page/', if somebody links it, most of the times they do it without the final slash (like 'folder/page'), and even if redirects are OK, it stills creates a 301 redirect, which is bad for SEO.
