### ISSUE TITLE
Using window on server side

### ISSUE THREAD

**Issue by ScreamZ** [nuxt/nuxt.js#3104]
Hey,
I would like to make a file called `variables.js` that expose some helpers.

In those helpers I would like to use one called :

`export const isMobile = typeof window !== "undefined" ? window.matchMedia("(min-width: 1000px)") : false;`

I would like to know if there is a proper way to deal with that ? Am I wrong ?

BEst regards

**Comment by NicoPennec** [comment]
You can create a [Middleware](https://nuxtjs.org/api/pages-middleware#the-middleware-property)  that will be executed on each page change (or a [Plugin with ssr false](https://nuxtjs.org/guide/plugins#client-side-only) but executed  only for each application init).

Then add `isMobile` in the nuxt [context](https://nuxtjs.org/api/context/) (or a better way, in Store)

```js
// middleware/device.js

export default function (context) {
  context.isMobile = (process.client) ? window.matchMedia("(min-width: 1000px)") : false
}

// page/index.vue

export default {
  async asyncData ({ isMobile }) {
    // ...
  }
}

**Comment by ScreamZ** [comment]
@NicoPennec Thanks you very much. :)
