### ISSUE TITLE
2 requests are made when I access a page with SSR

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#311]
If I paste the url in the browser I can see 2 requests made for the same page. I found this in the server logs.
    
    http://localhost:3000/app/create-project/project-details

Also the nuxtServerInit is executed multiple times
When I check the response of the get request for the page from the browser. I can see only the static content in the response. The page has a list which is fetched from the server in the fetch() method of the page. The html generated based on this list (using v-for) is not there in the server side response.

Here is the link to the [repo](https://github.com/shyamchandranmec/test) if you wish to check the code.

**Comment by Atinux** [comment]
Hi @shyamchandranmec 

We will take a look at it and come back to you.

**Comment by shyamchandranmec** [comment]
@Atinux Thanks

**Comment by Atinux** [comment]
Hi @shyamchandranmec 

Can you upgrade to the `0.10` and check if the error still persists?

Thank you

**Comment by shyamchandranmec** [comment]
@Atinux This fixed the nuxtServerInit issue. Now its not getting executed multiple times.

But the server side rendered html still doesn't have the list which is populated by a json array. 
This json array is fetched in the fetch method using async/await. 
I think the html for the dynamic content is generated in the client side.

**Comment by shyamchandranmec** [comment]
@Atinux  I checked another page in my application where I have to generate html based on a list. 
In that page the v-for is in the page where fetch method is used. Here the server side response includes the dynamic html.

But in the other page. v-for is in another component which is used in the page. In this case the dynamic content is generated in the client side. Is this the expected behaviour? I think SSR should include the dynamic content even if v-for is used in child components.

**Comment by Atinux** [comment]
Are you giving the data trough a prop to the other component?

**Comment by ausir0726** [comment]
@shyamchandranmec 
I have write a simple example for fill data to component when SSR.
hope it can help you . I can get dynamic data in component when SSR .

you can chekck following files .
`components/footer.vue`
`layout/default.vue`
`store/index.js`
https://github.com/ausir0726/nuxt-fill-component-ssr.git

**Comment by shyamchandranmec** [comment]
@Atinux I am not passing it via prop. 
I fetch the json via the fetch() method and adds it to the store. The component uses this store data to loop via v-for.  Can you give me your email id.. I can share the repo with you.

@ausir0726 Thanks for the example. I will check it out.
