### ISSUE TITLE
Nuxt generate moves compiled css into <head>

### ISSUE THREAD

**Issue by Iworb** [nuxt/nuxt.js#3111]
I want to use Bootsrap with my own colors, so I've made my `~assets/styles/app.scss`:
```scss
$primary: yellow;
@import '~bootstrap/scss/bootstrap.scss';
```
Then I've tried to add this to my nuxt.config.js:
```js
  build: {
    extractCss: true
  },
  css: [
    '~assets/styles/app.scss'
  ]
```
It's all works great, but when I'm trying to run nuxt generate it pushes all result styles into EACH html page. It's around 145 Kb of extra styles w/o caching.
So how to build css file and include it into head manually?

**Comment by Iworb** [comment]
Depending on [this comment](https://github.com/nuxt/nuxt.js/issues/475#issuecomment-299540936) it should be some vendor common css, isn't it?

**Comment by manniL** [comment]
Please try to use `extractCSS` as described [here](https://github.com/nuxt/nuxt.js/issues/3102#issuecomment-375499071).
This should solve your problem.

**Comment by TonyLuo** [comment]
I have the same issue, nuxt just embed all complied css into every html head, that makes html very big.
I have try extractCSS, but it doesn't work for me....

nuxt.config.js
```
module.exports = {
  /*
  ** Router config
  */
  router: {
    middleware: ['check-auth',]
  },
  /*
  ** Headers of the page
  */
  head: {
    title: 'test',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  build: {
    extractCSS: {
      allChunks: true
    },
    
  
        vendor: ['vuex','iview','axios','@tinymce/tinymce-vue','vue-amap','sockjs-client','webstomp-client']
  },
  /*
  ** Global CSS
  */
  // css: [
  //   'normalize.css',
  //   '~assets/main.css'
  // ],
  plugins: ['~/plugins/layout','~/plugins/vendor'], // https://nuxtjs.org/guide/plugins/
  css: [
    'normalize.css',
    '~assets/main.css',
 
    // 项目中的 CSS 文件
    '~/assets/styles/iconfont/iconfont.css',
    // 项目中的 Sass 文件
    { src: '~/assets/styles/iview-custom.less', lang: 'less' }, 
    { src: '~/assets/styles/common.less', lang: 'less' }, 
    { src: '~/assets/styles/app.less', lang: 'less' }, 
    { src: '~/assets/styles/animate.less', lang: 'less' }, 
    { src: '~/assets/styles/aurora.css'}, 
  ],
  /*
  ** Environement variables
  */
  env: {
    AUTH0_CLIENT_ID: '',
    AUTH0_CLIENT_DOMAIN: ''
  },
   /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }


    }
  }
};
```

**Comment by manniL** [comment]
@TonyLuo Which nuxt version are you using?

**Comment by TonyLuo** [comment]
the latest one: "nuxt": "^1.4.2",

**Comment by manniL** [comment]
@TonyLuo As described in [the docs](https://nuxtjs.org/api/configuration-build/#extractcss):

> CSS inside async components will remain inlined as JavaScript strings and handled by vue-style-loader.

If you upgrade to `nuxt-edge` (upcoming Nuxt 2 build), the default behavior is to extract all css in extra files with webpack4. I'd suggest to try it out.

**Comment by TonyLuo** [comment]
I try nuxt-edge and set   build: {extractCSS: true}, but it is still not working.
 nuxt still embed all compiled css into every html file header

**Comment by TonyLuo** [comment]
the different files still have the same inline css in the header when using nuxt-edge to generate static files
![image](https://user-images.githubusercontent.com/3250305/44092127-1d2187ee-a002-11e8-9bd1-48f28c904e3b.png)
