### ISSUE TITLE
How to trigger error from the server manually?

### ISSUE THREAD

**Issue by kemalcany** [nuxt/nuxt.js#3113]
Hello guys

This is a question partly concerning a web server (Node/Express in my case) running statically generated Nuxt app. Asking this here instead of SO thinking that this could go into the documentation later on.

Nuxt has a mechanism to detect errors such as 404 and redirect the app to a layout/error (if it exists)

Can this behaviour be triggered manually by the server? For example, if the user is unauthorized, the server wants to send a 401 response and expects nuxt client (running statically) redirect to error layout.

Is this possible to do with headers? How does nuxt detect an error if it's not SSR'd?

Thank you!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2696">#c2696</a>)</em></sub></div>

**Comment by manniL** [comment]
Related: #786, #555

**Comment by flamner** [comment]
window.onNuxtReady??

but how to handle rest(express) errors?? I add to server/index.js
`app.use((req, res, next) => {
    const error = new Error('Not found');
    error.status('404')
    next(error)
  })

  app.use((error, req, res, next) => {
    res.status(error.status || 500).json({
      message: error.message
    })
  })` 
but it does not work

**Comment by manniL** [comment]
@flamner Please create a new issue for that
