### ISSUE TITLE
Persisted state from VueX and NuxtJS

### ISSUE THREAD

**Issue by pirmax** [nuxt/nuxt.js#3114]
Hi,

I use vuex-persistedstate package (https://github.com/robinvdvleuten/vuex-persistedstate) to persist data state on browser.

I use Adonuxt (a mix between NuxtJS and AdonisJS).

In VueX actions, I have this action:

```
nuxtClientInit ({commit}) {
      // I want get here state auth saved by persistedstate package
    }
```

This action is called by plugin:

localstorage.js
```
export default async (context) => {
  await context.store.dispatch('nuxtClientInit', context)
}
```

nuxt.js (config)
```
{
      src: '~/plugins/localstorage.js',
      ssr: false
    }
```

I want get state to configure Axios with the user token:

`this.$axios.setToken(auth.jwt.token, 'Bearer')`

I have the impression nuxtClientInit() is called before persistedstate package, so `state.auth` is null but it can observable in console:

![image](https://user-images.githubusercontent.com/1739235/37842049-6bef1ad8-2ec1-11e8-9296-fe1caef78bac.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2694">#c2694</a>)</em></sub></div>

**Comment by feryardiant** [comment]
I had same issue but with another plugin called egoist/vue-persist, not sure if this issue actually belongs to Nuxt or vue-persist (or my configuration) since I'm using nuxt ssr mode.
