### ISSUE TITLE
How to lazy load components?

### ISSUE THREAD

**Issue by jerakode** [nuxt/nuxt.js#3116]
Hello. I have `admin` route where I have big Component that uses few external libraries. This route will be avaliable only for me, not for users of my site. RIght now it's loaded from the start even if I on another route. 

I tried this

```js
const vue2Dropzone = () => import('vue2-dropzone')
components: {
    vueDropzone: vue2Dropzone
  }
```
But still chunk is loaded even if I am not on this route. What is the logic behinfd this? How to actually load code only when I need it? Why it is not working out of the box?

**Comment by manniL** [comment]
It's likely preloaded, which is a benefit rather than a disadvantage. That means that components for the current route are loaded first, then the other components will be preloaded/prefetched.

Code splitting and lazy loading already work out of the box as you described it.

**Comment by manniL** [comment]
As I mentioned above, it will be loaded **after** the components needed for the current route. This is the default behavior. I've linked you an issue above that should be related to your use case.

**Comment by manniL** [comment]
After digging deeper and trying several approaches, the one mentioned in https://github.com/nuxt/nuxt.js/issues/1838#issuecomment-337064976 works quite well. The admin chunks will only be loaded when you visit the page and your main users won't have to download them.

**Comment by jerakode** [comment]
I just tried this. Don't see any changes. All is loaded on any page.

**Comment by jerakode** [comment]
Oh, my bad. I clicked wrong thing in DevTools. It's working! So this is basically is solution, right?

**Comment by manniL** [comment]
@jerakode Yup, it is :)

**Comment by johnyluyte** [comment]
@manniL Dose the "preloaded" feature you mentioned here only works in Nuxt Universal mode? I am using Nuxt SPA mode and I don't see things being prefetched. Is it a SSR only feature? Thanks

**Comment by manniL** [comment]
@johnyluyte Yes, this only works in SSR mode currently. With `edge` (Nuxt 2.0) this will work in SPA as well but is disabled by default everywhere.

**Comment by Jones-S** [comment]
I think vue-lazyload supports lazyloading of components as well:
https://github.com/hilongjw/vue-lazyload#lazy-component
Haven't tried it, but may be worth a shot.
