### ISSUE TITLE
vue-meta script is not loaded before mounted

### ISSUE THREAD

**Issue by syffs** [nuxt/nuxt.js#3118]
I'm using [this](https://github.com/olefirenko/vue-google-autocomplete) to autocomplete addresses through google map API. It's not ssr compatible so it's loaded through a `ssr: false` plugin.

I'm loading maps script from the page `head`:
```
head () {
  return {
	script: [
	  {src: 'https://maps.googleapis.com/maps/api/js?key=API_KEY&libraries=places'}
	]
  }
}
```

Now when the component is [mounted](https://github.com/olefirenko/vue-google-autocomplete/blob/e7aa890fd0a8abcb1b7c2f9b5bc413bff9448ca3/src/VueGoogleAutocomplete.vue#L92), google is not defined meaning that the script is not loaded.

Moving the script to the layout helps when the related page is not the first loaded, but fails the same way otherwise.

Any suggestion to work around this?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2700">#c2700</a>)</em></sub></div>

**Comment by Syffs** [comment]
I do have a workaround, but I find it rather ugly:
```
data () {
  return {
	googleReady: false,
	googleCheckingInterval: null,
  }
},
created () {
  this.googleCheckingInterval = setInterval(() => {
	if (window.google) {
	  this.googleReady = true
	}
  }, 100)
},
watch: {
  googleReady: (data) => {
	if (data) {
	  clearInterval(this.checkingInterval)
	}
  }
},
```
then on the component: `v-if="googleReady"`

**Comment by yoyo837** [comment]
Download complete is different from the execution complete.

**Comment by yoyo837** [comment]
For reference:
```js
function asyncInjectScript(url, globalName) {
  return new Promise((resolve, reject) => {
    if (!process.browser) {
      reject(new Error('This Fun only works in browser'))
      return
    }
    if (url == null) {
      reject(new Error("'url' params is required"))
      return
    }
    if (globalName == null) {
      reject(new Error("'globalName' params is required"))
      return
    }
    if (window[globalName]) {
      resolve(window[globalName])
      return
    }
    const script = document.createElement('script')
    script.setAttribute('src', url)
    script.setAttribute('charset', 'utf-8')
    script.setAttribute('async', '')
    const head = document.getElementsByTagName('head')[0]
    const start = moment()
    head.appendChild(script)

    const fn = function() {
      if (window[globalName]) {
        resolve(window[globalName])
      } else {
        const diff = moment().diff(start, 'milliseconds')
        if (diff > 1000 * 15) {
          reject(new Error('Inject failed'))
        } else {
          setTimeout(fn, 50) 
        }
      }
    }
    setTimeout(fn, 0)
  })
}
```

Or use globel script https://nuxtjs.org/api/configuration-head#the-head-property
Or see #3137

**Comment by Syffs** [comment]
@yoyo837  thanks for response! I'd rather not load google API globally when it's only used in 1% of my project.

In your opinion, which hook should call `asyncInjectScript`?

**Comment by yoyo837** [comment]
In any where in your code, not just a hook. It is a `loader`.

**Comment by syffs** [comment]
nuxt-edge handles this way better, so closing...

**Comment by nunogois** [comment]
@syffs I'm wondering how nuxt-edge handles this better and how you managed to fix your original problem. I'm having this issue currently: https://cmty.app/nuxt/nuxt.js/issues/c7300

Do you have any tips?
Many thanks!

**Comment by adrianoresende** [comment]
I have this problem too. @syffs How you fix? Explain better please

**Comment by xTobu** [comment]
I have this problem too ... 
Please :( ..
@syffs
