### ISSUE TITLE
asyncData not called on reloading the page

### ISSUE THREAD

**Issue by paolog22** [nuxt/nuxt.js#3120]
asyncData is not firing when page is refresh.

**Comment by silvio-e** [comment]
@paolog22 Do you mean when you reload the page in the browser or when you save a file in dev mode?

**Comment by paolog22** [comment]
@silvio-e when the browser is refreshed.

**Comment by yoyo837** [comment]
Only server side...

https://nuxtjs.org/api#the-asyncdata-method
