### ISSUE TITLE
Unnecessary index.vue in Nested Routes example

### ISSUE THREAD

**Issue by sven-ra** [nuxt/nuxt.js#3124]
Nested Routes example

/Pages
     /INDEX
          index.vue   -----> Is this index.vue necessary?
          _id.vue
     index.vue

I am still learning Nuxt and stumbled across this. It got me pretty confused at first, but then I realised that it is not necessary.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2705">#c2705</a>)</em></sub></div>

**Comment by manniL** [comment]
If you have the following structure:

```
pages/
--| posts/
-----| index.vue
-----| _id.vue
```

you'd need the `index.vue` to access `/posts` and `_id.vue` to display different posts, eg `/posts/1`.

**Comment by Kimel1** [comment]
@sven-ra 
index.vue need in directory to process path w/o params.
For example 
```
pages/
--| posts/
-----| index.vue
-----| _id.vue
```
If index.vue will empty, then if you try to get localhost:3000/posts/ you'l get redirect to error page. 
I should always add empty index.vue in directories if you don't want to process path w/o params.

**Comment by sven-ra** [comment]
https://nuxtjs.org/examples/nested-routes

But in this example, do we get another url for the INDEX/index.vue ?

**Comment by Kimel1** [comment]
@sven-ra  it's because `<nuxt-child :key="$route.params.id"/>`
