### ISSUE TITLE
SPA, no webserver and routing (this page could not be found)

### ISSUE THREAD

**Issue by Twisterking** [nuxt/nuxt.js#3125]
So I have a fully working nuxt app (I cloned this example project: [roberto-butti/nuxtjs-helloworld](https://github.com/roberto-butti/nuxtjs-helloworld) - Obviously I fixed the package.json nuxt version constraints and am running the newest 1.4.0). Now I want to use the `--spa` mode to build a single page app, put it into a cordova container and build a (iOS/Android) App out of it.

I am now running into a couple of problems:

- Should I use the contents of my generated `dist` dir or of the `.nuxt/dist` dir for my app?
- Many paths are now wrong. Cordova obviously does not have any local webserver running, so the pages are opened via `file://...` - So I tried [this "hack"](https://github.com/nuxt/nuxt.js/issues/2892) and it works beautifully, the paths to the files work now! 
- The routing is not working now - I always end up on nuxt's "This page could not be found" error page.

All these errors already occur when I only open the `index.html` in my desktop browser from the `dist` dir - so they are completely Cordova unrelated!

Did anyone try already to combine the SPA mode and cordova and was successful? I am a bit confused now on what I have to do to get this running.

If nuxt/vue-js definitely needs a local webserver to work properly, even in SPA mode, then maybe [floatinghotpot/cordova-httpd](https://github.com/floatinghotpot/cordova-httpd) can help?

best, P

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2706">#c2706</a>)</em></sub></div>

**Comment by FateXRebirth** [comment]
I encounter the same problem as well, it's really weird, it shouldn't complex. I think it should be simple as I change the mode to universal, and then SSR, on the other hand, change the mode to the spa, CSR

**Comment by kaven276** [comment]
I encounter the same problem too, see #3160
