### ISSUE TITLE
Where do custom directives belong?

### ISSUE THREAD

**Issue by wcjr** [nuxt/nuxt.js#3127]
I couldn't find anything in the guide about a best practice on this.  It seems a custom directive could be a plain old javascript file with the `Vue.directive(...)` syntax but I don't see a clear winner for its directory or is the best practice to simply put the registration in the `default.vue` layout? 

Just wanting to use this in my project:
```js
// Register a global custom directive called `v-focus`
Vue.directive('focus', {
  // When the bound element is inserted into the DOM...
  inserted: function (el) {
    // Focus the element
    el.focus()
  }
})
```

Thanks!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2708">#c2708</a>)</em></sub></div>

**Comment by paulgv** [comment]
I'd tend to register directives in a plugin:

```
plugins/
├── directives.js
```

```js
// nuxt.config.js
{
  plugins: [
    '~/plugins/directives.js'
  ]
}
```

**Comment by wcjr** [comment]
Thanks @paulgv , I was considering that but there's a statement in https://nuxtjs.org/guide/plugins about these being run before the instantiating the root Vue application...do you think directives loaded before will still be recognized once the root Vue app is instantiated?

**Comment by wcjr** [comment]
I did what you suggested, no problems I was was curious about with the root Vue instantiation.  @paulgv, do you think it would be worth a little statement in the guide (https://nuxtjs.org/guide/directory-structure) or README's about what to do with directives?

**Comment by paulgv** [comment]
It might be nice to have some more examples on what you can do in plugins (register mixins, filters, directives, etc.) for sure :)

**Comment by wcjr** [comment]
oh good, I'm glad you think that.  What can I/we do to ensure something like this is added?

**Comment by paulgv** [comment]
The best way would be to fork https://github.com/nuxt/docs and add your examples to the plugins guide, then you can submit a PR to the main repo.

**Comment by wcjr** [comment]
ok @paulgv , that makes sense and it looks like running it locally isn't difficult.  I'll put this on my list to do.

**Comment by wcjr** [comment]
hey @paulgv , I've started running into issues with the `spa` aspects of nuxt and am going to have to abandon nuxt for now.  Hopefully simply having this note here will help others in the future.  Thanks!
