### ISSUE TITLE
<nuxt-link to="/" append> don't work

### ISSUE THREAD

**Issue by thinkmix** [nuxt/nuxt.js#3128]
i want jump to the relative path,but  it doesn't work

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2709">#c2709</a>)</em></sub></div>

**Comment by 48sahrul** [comment]
Tey

**Comment by thinkmix** [comment]
![image](https://user-images.githubusercontent.com/15797385/37946356-821f1904-31b7-11e8-84fc-81a9399dc8d2.png)

**Comment by jpoo90** [comment]
@thinkmix Not sure if this is your case but this was my scenario: 

Before I was doing this 

```html
<nuxt-link :to="/newPath" append></nuxt-link>
```

After removing the slash in the path, `append` works as expected.

```html
<nuxt-link :to="newPath" append></nuxt-link>
```


Hope it helps :)

**Comment by thinkmix** [comment]
@jpoo90 thanks,i'll try your scenario
