### ISSUE TITLE
no data returned on page resfresh

### ISSUE THREAD

**Issue by Myolisi** [nuxt/nuxt.js#3130]
I get the expected data every time I load a page for the first time, but when i refresh my pages the store doesnt get data from the middleware please help:
this is my middleware, it gets a persons information and commits data to the AddViewedPerson state, but for some reason i get empty results when I do a page refresh

export default function({params,store}){

    return  axios.get(`/api/getAddresses/${params.view}`)
		          .then((response) => {
		           store.commit('addAddresses', response.data)
					    return axios.get(`/api/getTelephones/${params.view}`)
						    .then((response) => {
						       store.commit('addTelephones', response.data)

						        return axios.get(`/api/personInformation/${params.view}`)
						           .then((response) => {
						            store.commit('AddViewedPerson', response.data)

						            return axios.get(`/api/personCountry/${params.view}`)
							          .then((response) => {
							           store.commit('addCountry', response.data)
							          })
					   })
			})

	})

}
in my main page I have something like this:
 v-for="personal in $store.state.viewedPerson" 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2711">#c2711</a>)</em></sub></div>

**Comment by rancongjie** [comment]
check axios baseURL set

**Comment by Myolisi** [comment]
this is how my module config looks like
axios: {
    baseURL: undefined,
  },

**Comment by Kimel1** [comment]
You should use https://nuxtjs.org/api#the-asyncdata-method for this purpose 
or https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action

**Comment by Myolisi** [comment]
@Kimel1  I tried the async data method and it didn't solve my problem, I guess i have to try the nuxtserverinit action then.

**Comment by xloading** [comment]
Hi @Myolisi 
Did you resolve it somehow?
Facing something similar here: https://github.com/nuxt/nuxt.js/issues/3463

**Comment by Myolisi** [comment]
Yes, Did you try using app.$axios.get() instead of axios.get()? , so that you'd have something have something similar to this for example..

async asyncData ({app}) {
return await app.$axios.get(/api/getAddresses/${params.update})
}
