### ISSUE TITLE
Custom Logger - Request

### ISSUE THREAD

**Issue by awolden** [nuxt/nuxt.js#3131]
It would be a nice feature if we could pass-in or some how utilize our own custom logger for Nuxt messages. We run Bunyan in production and would like to utilize it within Nuxt. If Nuxt exposed an API for a custom logger, it would be greatly increase visibility into what is happening with Nuxt in production. We are using a custom express server to host our Nuxt site, which gives us some insight into requests, timings and etc., but we have virtually no logs on Nuxt itself.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2712">#c2712</a>)</em></sub></div>

**Comment by stylehuan** [comment]
urgency

**Comment by galvez** [comment]
Nuxt's next release uses [consola](https://github.com/nuxt/consola) -- it offers plenty of configuration options, you should check it out.
