### ISSUE TITLE
Access to component instance in meta

### ISSUE THREAD

**Issue by javialon26** [nuxt/nuxt.js#3134]
Hello is possible to access to component instance in meta object of the component page?

Example in a page component:
```
meta: {
  breadcrumb: this.category.title
},
```

This example throws an error because this.category is undefined. Maybe this will be a nice feature.

Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2715">#c2715</a>)</em></sub></div>

**Comment by Kimel1** [comment]
@javialon26 Hello, I'm using follow code with no errors. 
```javascript
  head () {
    return {
      title: this.category.cTitle
    }
  }
```
and this one from docs
```javascript

head () {
    return {
      title: this.title,
      meta: [
        { hid: 'description', name: 'description', content: 'My custom description' }
      ]
    }
  }
```

**Comment by javialon26** [comment]
@Kimel1 hello, thank you but my question is for meta router not for meta tags, see this issue #466.

**Comment by blooddrunk** [comment]
I'm facing similar issues. I'd like breadcrumb name which defined in `meta`  to be translated by `vue-i18n` but can't use `this.$t` when `meta` is defined. It would be nice if `meta` can accept a function call

**Comment by Atinux** [comment]
Hi @javialon26 

Actually this won't be possible since `meta` will be used in middleware and the page component will not be created yet.
