### ISSUE TITLE
Body script tag should be added before context scripts

### ISSUE THREAD

**Issue by 5paceman** [nuxt/nuxt.js#3135]
In file lib/core/renderer.js, line 372 to 375, as below
```js
    APP += `<script>${serializedSession}</script>`
    APP += context.renderScripts()
    APP += m.script.text({ body: true })
    APP += m.noscript.text({ body: true })
```
we see the meta scripts is appended after context scripts, but the meta scripts are always some third part lib, like zepto, lodash and so on, they should be loaded before context scripts, so I think Nuxt should provide an option to decide if the meta scripts postion is before or after the context scripts.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2716">#c2716</a>)</em></sub></div>

**Comment by yoyo837** [comment]
Nuxt.js use `defer` and `async` in script tag.

**Comment by 5paceman** [comment]
@yoyo837 Yes, using the property `defer` & `async` may resolve this problem, I know, but the two properties can not ensure the order of scripts excuting as they are loaded, so the best way is put them all before body in order.

**Comment by galvez** [comment]
@pi0 any objections to this?
