### ISSUE TITLE
[Question] How to use Element-UI as CDN?

### ISSUE THREAD

**Issue by vukhanhtruong** [nuxt/nuxt.js#3137]
[Element-UI](http://element.eleme.io/#/en-US/component/quickstart) is good, but it's too big. I got the message "asset size limit" when building project. So, I want to use CDN instead. 

I went through [this instruction](https://nuxtjs.org/faq/), but no luck. It ran into the issue "Unknown custom element".

Please help me out. Thank you very much.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2717">#c2717</a>)</em></sub></div>

**Comment by yoyo837** [comment]
See https://nuxtjs.org/api/configuration-head#the-head-property
and https://github.com/declandewet/vue-meta#recognized-metainfo-properties
In nuxt.config.js:
```js
module.exports = {
  head: {
    script: [{
        type: 'text/javascript',
        charset: 'utf-8',
        body: true,
        src: 'https://xxx.js'
    }]
  }
}
```

**Comment by vukhanhtruong** [comment]
Thanks for your reply. Your point is put `xxx.js` to the `<body>` tag to make it up, right? I did it by using vue-meta but still ran into the same issue.

**Comment by yoyo837** [comment]
No, that's not my point.Just want to say that `nuxt.config.js:head>script[]` configuration can add global script from CDN or any other `url`.Nuxt.js uses `vue-meta` to make it work.
