### ISSUE TITLE
the problem of middleware function

### ISSUE THREAD

**Issue by yhZhouYh** [nuxt/nuxt.js#3138]
when I set middleware function in the nuxt.config.js 
![image](https://user-images.githubusercontent.com/13265388/38020004-bd2078aa-32ab-11e8-9943-bc17915dd30c.png)

the first time It's called on server side console
![image](https://user-images.githubusercontent.com/13265388/38020120-06527b2c-32ac-11e8-847e-ab9a3c879aaf.png)

and then it's called on browser console when I change the route of page
![image](https://user-images.githubusercontent.com/13265388/38020220-3a68dd7a-32ac-11e8-9e54-205f821cf61f.png)

why???? so that I can't get the right way of cookie... I don't know I should get it by either req.header or client cookie because the first time I can get it from req.header but not on client, and then I can get by client one not the req.header.....   

...and why the vuex getter will be called by itself

![image](https://user-images.githubusercontent.com/13265388/38020295-6c76228c-32ac-11e8-8740-1e2180e3f63b.png)
![image](https://user-images.githubusercontent.com/13265388/38020317-79469320-32ac-11e8-8382-9d87cc65d250.png)
![image](https://user-images.githubusercontent.com/13265388/38020374-a0f7132c-32ac-11e8-92e8-8bac30fea0db.png)
forgive my poor English..:( so I choose display pics....

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2718">#c2718</a>)</em></sub></div>

**Comment by yoyo837** [comment]
```js
if (process.client) {
  //document.cookie
} else {
  //req.header
}
```

**Comment by yhZhouYh** [comment]
@yoyo837 可是首次默认加载调用的服务端， 切换页面isClient执行

**Comment by yoyo837** [comment]
中间件只在服务端运行，相当于第一个页面(服务器渲染时)执行

**Comment by yhZhouYh** [comment]
@yoyo837 切换页面时 我看也执行了 只不过 打印了process.client

**Comment by yoyo837** [comment]
页面上process.client始终是true

**Comment by husayt** [comment]
Please, stick to English here as this is a resource for everyone.
