### ISSUE TITLE
Extending a vuetify component

### ISSUE THREAD

**Issue by Michkkael** [nuxt/nuxt.js#3139]
Hi folks, I trying to extend a Vuetify component in a nuxt project (nuxt starter template) but i'm getting errors...

My extended component: 
```js 
// /assets/components/vuetifyExtended/VRadioGroup/VRadioIcon.js

import VRadio from 'vuetify/src/components/VRadioGroup/VRadio';

export default {
  name: 'v-radio-icon',
  extends: VRadio,
  props: {
    iconActive: { type: String, default: 'radio_button_checked' },
    iconInactive: { type: String, default: 'radio_button_unchecked' },
  },
  computed: {
    icon() {
      return this.isActive ? this.iconActive : this.iconInactive;
    },
  },
};
```

The kind of errors i'm getting:
```sh
[...]
 ERROR  Failed to compile with 2 errors          08:29:45

error  in ./node_modules/vuetify/src/util/helpers.js

Module parse failed: Unexpected token (34:28)
You may need an appropriate loader to handle this file type.
|       context.data.on = context.data.on || {}
|       if (!Object.isExtensible(context.data.on)) {
|         context.data.on = { ...context.data.on }
|       }
|
@ ./node_modules/vuetify/src/components/transitions/index.js 1:0-4:27
@ ./node_modules/vuetify/src/components/VRadioGroup/VRadio.js
[...]
```

I've seen that  [issue](https://github.com/vuetifyjs/vuetify/issues/1840) but the solution did not solved mine. 
Does anyone can help me ? :) thx!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2719">#c2719</a>)</em></sub></div>

**Comment by jsuwala** [comment]
Try changing your import statement to the veutify/es5 version (rather than the `veutify/src` version) :
`import VRadio from 'vuetify/es5/components/VRadioGroup/VRadio'`

**Comment by galvez** [comment]
Try using the object-spread-operator Babel plugin if you can't upgrade Node.
