### ISSUE TITLE
[edge] Command line stucks at "BUILDING"

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#3143]
Though nuxt-edge was built successfully, the "end dialog" (with the URL and a success message) is never shown when using `npm run dev` or `nuxt`.

![image](https://user-images.githubusercontent.com/640208/38051470-b4b56d4c-32ce-11e8-837e-5a88ef7b2089.png)

**Comment by pi0** [comment]
Thanks, @manniL for the check. Yes, I'm on it.

**Comment by pi0** [comment]
I've reworked webpackbar (`v1.5.1`) to make things more stable. If possible, please try `nuxt-edge-start@2.0.0-25371184.c42ef4c`

**Comment by pi0** [comment]
BTW we may have to entirely clean up console OR show another READY message after each reloads to prevent users confusing.

**Comment by manniL** [comment]
@pi0 On version `2.0.0-25371184.c42ef4c`, it does work sometimes, but not reliable.

![image](https://user-images.githubusercontent.com/640208/38057013-61a48c68-32de-11e8-85a9-e471c3f7f69e.png)

A console cleanup would be good IMO, so the user will def. know when it's fully ready. Displaying another `READY` message might lead to confusion.

**Comment by pi0** [comment]
`2.0.0-25371252.948d566` should be better :D

**Comment by manniL** [comment]
@pi0 Yes, works like a charm!
