### ISSUE TITLE
[edge] build context properties

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#3145]
### Version

[edge](https://github.com/nuxt/nuxt.js/releases/tag/edge)

### Reproduction link

[https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67](https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67)

### Steps to reproduce

In the Nuxt 2.0 "upcoming" post on Medium it is written:

> Removed context.isServer and context.isClient (Use context.client and context.server)
> Removed options.dev in build.extend() (Use options.isDev)

But when I run

```
 extend (config, ctx) {
      console.log(ctx)
      // ...
}
```

it returns:
```

{ isDev: false, isServer: true }
{ isDev: false, isClient: true }

```

So either statement one or statement two from the post is false

### What is expected ?

.

### What is actually happening?

.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6786">#c6786</a>)</em></sub></div>

**Comment by pi0** [comment]
Yes, you are right 👍 I've published the changes. 

PS: Your feedbacks on v2 are really nice. I appreciate your help ️ ❤️

**Comment by manniL** [comment]
Thanks a lot, @pi0! :heart: 
I'm happy that I can help to improve Nuxt and the community modules :relaxed:
