### ISSUE TITLE
[edge] nuxt generate error with mini-css-extract-plugin

### ISSUE THREAD

**Issue by bovas85** [nuxt/nuxt.js#3150]
### Version

[2.0](https://github.com/nuxt/nuxt.js/releases/tag/2.0)

### Reproduction link

[https://antilophia-vue.nakedtesting.com](https://antilophia-vue.nakedtesting.com)

### Steps to reproduce

npm uninstall nuxt
npm i --save nuxt-edge
npm run generate
```
/Users/dev/Desktop/antilophia-vue/node_modules/mini-css-extract-plugin/dist/index.js:26
const { Template, util: { createHash } } = _webpack2.default;
                          ^

TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/developer2/Desktop/antilophia-vue/node_modules/mini-css-extract-plugin/dist/index.js:26:44)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/developer2/Desktop/antilophia-vue/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (module.js:649:30)
```

### What is expected ?

generating static files

### What is actually happening?

 error above

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6795">#c6795</a>)</em></sub></div>

**Comment by bovas85** [comment]
Hey @pi0 I'll try that, if it fails I can share it privately with you (as it's a client work). Thanks for the quick feedback and compliments :)

**Comment by benoitemile** [comment]
/unrelated but your site is awesome <3 nice transitions and stuff, great work

**Comment by pi0** [comment]
@bovas85 Would you please send me the link? I didn't received any invitation :)) (pyapar at gmail)

**Comment by bovas85** [comment]
Hmm odd I sent it to your profile email. I'll try again

**Comment by bovas85** [comment]
Try now please @pi0

**Comment by LouisTakePILLz** [comment]
I don't use nuxt but the issue went away after upgrading to 4.4.1. 
I was on webpack 4.2.0 before upgrading.

**Comment by pi0** [comment]
Sorry for the delay. I've checked your project locally and will open a PR for fixes.

Here are general notes (some are not related to the issue) but may be usable for other too:

- `nuxt.config.js` is loaded through ESM. So don't try mixin `require` and `imports`. Prefer import/exports
- It is highly recommended to use an external `.postcssrc` file for customizing postcss.
- For a clean upgrade, after changing `nuxt` to `nuxt-edge`, remove `yarn.lock`, `.nuxt` and `node_modules` and make a fresh install.
- `nuxt-sass-resources-loader` is incompatible with v2. I've made anteriovieira/nuxt-sass-resources-loader#11 for support. Meanwhile, you can use nuxt-community's fork using `yarn add nuxt-sass-resources-loader@nuxt-community/nuxt-sass-resources-loader#feat/v2` command.
- And finally, latest versions of `nuxt-edge`, `webpack` and `mini-css-extract-plugin` seem are working out of the box. (This Issue)

**Comment by bovas85** [comment]
Thanks I will check these and let you know

**Comment by bovas85** [comment]
Hi @pi0 , I gave you write access for this.
I'm not clear on the pointer about the require and imports. Can you send me a commit so I can understand? 

I'll try updating now and see if it fixes it

**Comment by bovas85** [comment]
@pi0 can you take a look at the repo?

If I remove that it compiles, but I see some inconsistencies with styles (as in some styles are not carrying over compared to my regular nuxt)

**Comment by lucpotage** [comment]
@bovas85 I had the same problem because I used the starter template. After upgrading `estlint-loader` to version 2.0, it worked like a charm without changing any line of code. ✨

**Comment by bovas85** [comment]
I have an issue not with eslint, but rather with styles not carrying over to my static site.

If you go to https://antilophia-vue.nakedtesting.com/
you can see a slider that has an animation.

For some reason using nuxt-edge I get this weird zoom effect (using now and nodejs but same result on a static server)
https://starter-gcodmycdxc.now.sh/

**Comment by bovas85** [comment]
I think it has something to do with autoprefixer.

It's changing my transform: scale to transform: scale3d 
but the values inside are completely off (it should start from 1 and go to 1.1 rather than from 0.3 to 1)

**Comment by chabib** [comment]
In my case
> I intent to use nuxt-edge with starter template
> copy other project config
