### ISSUE TITLE
[edge] Conflict: Multiple assets emit to the same filename

### ISSUE THREAD

**Issue by pSchaub** [nuxt/nuxt.js#3153]
### Version

nuxt-edge (2.0)

### Bug report

I have a big project here that I tried to update from `nuxt` to `nuxt-edge`.

When I run `nuxt build` I see a lot of errors like this:
```
Conflict: Multiple assets emit to the same filename xxxx.css
```

### What is expected ?

No error on `nuxt build`

### What is actually happening?

Error message

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6797">#c6797</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @pSchaub. Thanks for the report. This is likely to be from same content hashes. (which should be resolved on the plugin itself). To make sure, would you please test this config:

```js
  build: {
    optimization: {
      splitChunks: {
        name: true
      }
    }
  }
```

**Comment by pSchaub** [comment]
@pi0 Thank you. The workaround works fine.
