### ISSUE TITLE
TypeError: Cannot read property 'inject' of undefined

### ISSUE THREAD

**Issue by OliverVin** [nuxt/nuxt.js#3154]
TypeError: Cannot read property 'inject' of undefined
    at Renderer.renderRoute (/Users/oliver/PhpstormProjects/frontWeb/node_modules/nuxt/lib/core/renderer.js:349:28)
    at <anonymous> statusCode: 500, name: 'TypeError' }

upgrade to latest, & open cdn, now can't work . 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6798">#c6798</a>)</em></sub></div>

**Comment by OliverVin** [comment]
let APP = await this.bundleRenderer.renderToString(context)

    if (!context.nuxt.serverRendered) {
      APP = '<div id="__nuxt"></div>'
    }
    const m = context.meta.inject()
    let HEAD =
      m.meta.text() +
      m.title.text() +
      m.link.text() +
      m.style.text() +

**Comment by OliverVin** [comment]
context.meta - undefined ?

**Comment by uNmAnNeR** [comment]
@OliverVin Hi! How did you solve it?
