### ISSUE TITLE
v-bind:src don't work with the aliases

### ISSUE THREAD

**Issue by raisiqueira** [nuxt/nuxt.js#3155]
Hi! I'm trying to import an image dynamically, but when compiling Nuxt does not understand the alias.

The code:
![code](https://user-images.githubusercontent.com/2914170/38115628-177c8ce4-3383-11e8-995f-52c3d5f74c92.png)

the console return:
![captura de tela 2018-03-29 as 18 56 03](https://user-images.githubusercontent.com/2914170/38115652-2682f2fa-3383-11e8-86bd-3043854fc2a1.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6799">#c6799</a>)</em></sub></div>

**Comment by manniL** [comment]
This is no bug. You can't use webpack aliases in runtime-evaluated expressions that easy. See [this issue](https://github.com/nuxt-community/nuxt-i18n/issues/32#issuecomment-368306032)
