### ISSUE TITLE
add vue 2.2 version constraints to the upcoming 0.10 release

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#316]
Hi Guys,
it would be great if you could add `Vue 2.2` version constraints to the upcoming release. 
Thanks!

**Comment by alexchopin** [comment]
Hi, we are currently working on it.

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋
