### ISSUE TITLE
Setting the mode for spa to make a mistake

### ISSUE THREAD

**Issue by tanrenjie** [nuxt/nuxt.js#3160]
error message:
   ResourceNotFound
  This page could not be found

**Comment by kaven276** [comment]
```shell
cd $SOURCE
npm run build -- --spa
rsync -av --delete $SOURCE/dist/ --filter="- *.map" --filter="- static/screen" "${TARGET}:static/${DIR}/"
```

the script is successfully executed, and access the page,erro reported

**Comment by kaven276** [comment]
This page could not be found
Back to the home page
```

but in Chrome console and network trace, there is no any error information.

**Comment by kaven276** [comment]
in nuxt.config.js, set as below, solved
```
  router: {
    base: '/yxdmon/',
  },
```

ref:  https://nuxtjs.org/api/configuration-router#base
