### ISSUE TITLE
[edge] Pug Not Working

### ISSUE THREAD

**Issue by mattwaler** [nuxt/nuxt.js#3161]
### Version

[2](https://github.com/nuxt/nuxt.js/releases/tag/2)

### Reproduction link

[https://jsbin.com](https://jsbin.com)

### Steps to reproduce

With pug and pug-loader installed via Yarn, my old Nuxt 1 project (which works fine) is no longer working after removing Nuxt 1 and installing Nuxt 2. The error looks like this:

![Screen Shot 2018-03-30 at 11.01.08 AM.png](https://cmty.s3.eu-west-1.amazonaws.com/nuxt/nuxt.js/1522422092323/Screen_Shot_2018-03-30_at_11.01.08_AM.png)

### What is expected ?

Project functions properly on current stable release.

### What is actually happening?

Project fails and cannot render the pug template.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6806">#c6806</a>)</em></sub></div>

**Comment by daliborgogic** [comment]
Workaround:
[pug-plain-loader](https://github.com/yyx990803/pug-plain-loader)

`npm i -D pug-plain-loader`

```javascript
// nuxt.config.js
module.exports = {
  build: {
    extend(config, ctx) {
      config.module.rules.push({
        test: /\.pug$/,
        loader: 'pug-plain-loader',
        options: {
          data: {}
        }
      }
    }
  }
}
````

**Comment by daliborgogic** [comment]
And remove `pug-loader` from `package.json`.

**Comment by mattwaler** [comment]
Thank you!

Will this be fixed in the official release to allow for the use of the default pug loader?
