### ISSUE TITLE
Store: Add Dynamic Module Registration support

### ISSUE THREAD

**Issue by Liu233w** [nuxt/nuxt.js#3162]
### What problem does this feature solve?

Hi.

Is there any plan to support [Dynamic Module Registration](https://vuex.vuejs.org/en/modules.html?q=Dynamic%20Module%20Registration) of Vuex store ? I didn't see it on the document of NuxtJs.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6809">#c6809</a>)</em></sub></div>

**Comment by benoitemile** [comment]
Hi,

You can already do so in nuxt for example, in a SFC : 
```js
import yourAwesomeModule from '~/store/modules/yourAwesomeModule';
[...some code...]
this.$store.registerModule('yourAwesomeModule', yourAwesomeModule, { preserveState: true });
```

**Comment by Liu233w** [comment]
Thanks for your reply.

But I think it will be better if nuxt can automatcally create an association between page and store module.

For example:

> pages
> -- awsomepage.vue
> store
> -- _awsomepage.js

It will be better if nuxt can register the module just before `awsomepage.vue` created and unregister it after `awsomepage.vue` destroyed automatcally.

**Comment by benoitemile** [comment]
Oww, ok, I do unsterstand what you mean. I don't know if I want that magic to happen though, because some component won't have a store module requirement and some will. This question is for the core team :)

**Comment by galvez** [comment]
We're considering Vuex integration improvements post-2.0. Closing this for now!
