### ISSUE TITLE
Change all NUXT scripts loading mode from preload to prefetch

### ISSUE THREAD

**Issue by tevel** [nuxt/nuxt.js#3165]
### What problem does this feature solve?

I want my page opening much more faster.
Currently all scripts in head section loaded with PREFETCH flag.
This blocks webpage opening until all scripts will be downloaded.
In my case (with vuetify) it about 200Kb gzipped.
But why do I need these JS scripts to see my page?
I need them to get interactive page.
And it can be much latter then viewing page.
Please try to run LightHouse - it will tell the same.
Do not block page opening with java scripts.
![nuxt.png](https://cmty.s3.eu-west-1.amazonaws.com/nuxt/nuxt.js/1522534656905/nuxt.png)

### What does the proposed changes look like?

manifest and javascript files in head section without PREFETCH flag
webpage opens faster!

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6813">#c6813</a>)</em></sub></div>

**Comment by pi0** [comment]
@tevel Would you please try changing `nuxt` to `nuxt-edge` and test results again?

**Comment by tevel** [comment]
I tried but it seems like nuxt-edge does not work with nuxt-i18n module.
I can't get reed of this module.
I will wait release of nuxt-edge, hope it will work well with translation module.

**Comment by manniL** [comment]
@tevel I had no problem with `nuxt-i18n` together with `nuxt-edge` in my tests. However, in `nuxt-edge`, all resourceHints are disabled by default :relaxed:  You can now define what you want to preload/prefetch. See [this comment](https://github.com/nuxt/nuxt.js/issues/1838#issuecomment-375969705) for an example.

**Comment by tevel** [comment]
thanks! that works fine:
render: {
    bundleRenderer: {
      shouldPrefetch: (file, type) => {
         return false
      }
    }
  }

**Comment by manniL** [comment]
@tevel You can achieve this even easier in Nuxt 1.x: set the [`resourceHints`](https://nuxtjs.org/api/configuration-render#resourcehints) options to `false`. :relaxed:
