### ISSUE TITLE
[edge] Extract CSS into one single file does not work

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#3166]
### Version

2.0.0-25390984.952dfe0

### Reproduction link

[https://github.com/manniL/nuxt-edge-extract-css-issue](https://github.com/manniL/nuxt-edge-extract-css-issue)

### Steps to reproduce

1. Clone the repo
2. Install packages with `npm i`
3. Run `npm run build`

Related test: https://github.com/nuxt/nuxt.js/blob/dev/test/fixtures/extract-css/extract-css.test.js

### What is expected ?

CSS will be extracted and merged into one single file

### What is actually happening?

 CSS is extracted but not merged into a single file.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6814">#c6814</a>)</em></sub></div>

**Comment by gangsthub** [comment]
I had the update the stylus-loader when upgrading... And had to re-isntall `npm isntall` a couple of times. Dunno why: not cleaned the npm cache, just a few tries. Also, if you are using the pwa/module; you may have to force refresh it: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#devtools

```
-    "stylus-loader": "^3.0.1"
+    "stylus-loader": "^3.0.2"
```

**Comment by manniL** [comment]
@gangsthub I don't think that problem is related to the stylus load :thinking: I'm not using stylus anyway and the issue persists in the newest version.

PWA module is also irrelevant because the css files are already shown after the build process

**Comment by sh** [comment]
having the same issue here, i end up with a one css file per component / page that contains a scss style block (no matter if scoped or not)

happy to provide additional reproduction cases if necessary

**Comment by clarkdo** [comment]
@manniL Have you tried https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file?

**Comment by clarkdo** [comment]
@manniL It should be related to https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85, still not resolved perfectly

And current temporary solution is: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85#issuecomment-378673224 and https://github.com/webpack-contrib/mini-css-extract-plugin/issues/113#issuecomment-394595414

**Comment by manniL** [comment]
@clarkdo Thanks for digging into it! This works like a charm! <3 
Will update the repo and mark the report as closed.

**Comment by willin** [comment]
@clarkdo  tried, not work

**Comment by willin** [comment]
```
 ~/Desktop/nuxt-edge-extract-css-issue   master  yarn build
yarn run v1.9.4
$ NODE_ENV=production nuxt build
[14:52:30] Building project
[14:52:30] Builder initialized
[14:52:30] Nuxt files generated
[14:52:31] Compiling client
[14:52:37] Compiled client in 5s

Hash: f522dfc6e30e4413d9f5
Version: webpack 4.17.1
Time: 5175ms
Built at: 2018-08-30 14:52:37
                   Asset       Size  Chunks             Chunk Names
f2462760bffd93ef0b0c.css  927 bytes       0  [emitted]  styles
 c927cb7df4e8c64cb450.js   4.22 KiB       0  [emitted]  styles
 d598975fa16ef52c128f.js     23 KiB       1  [emitted]  app
 e3e2db964709351482df.js    133 KiB       2  [emitted]  commons.app
                LICENSES  422 bytes          [emitted]
 + 3 hidden assets
Entrypoint app = e3e2db964709351482df.js f2462760bffd93ef0b0c.css c927cb7df4e8c64cb450.js d598975fa16ef52c128f.js
[14:52:37] Compiling server
[14:52:37] Compiled server in 730ms

Hash: 70042cbb571a098f7bdb
Version: webpack 4.17.1
Time: 732ms
Built at: 2018-08-30 14:52:37
             Asset     Size  Chunks             Chunk Names
server-bundle.json  147 KiB          [emitted]
Entrypoint app = server-bundle.js server-bundle.js.map
✨  Done in 9.77s.
```

**Comment by clarkdo** [comment]
Hi, if this issue has been closed, it shows that it has been solved, could you please open a new issue and follow the issue template by providing a reproduciable repo, so that we can reproduce the issue and help you.
