### ISSUE TITLE
Safari 10, Uglify: SyntaxError: Cannot declare a let variable twice: 'e'

### ISSUE THREAD

**Issue by bjunc** [nuxt/nuxt.js#3167]
> Note, I would have used the CMTY app, but authorization grants you FULL access to my personal information, including private email addresses, private profile info, followers, and organization access!  Just to file a bug report!?  

It appears that there is a bug in Safari 10, that will result in a `Loading chunk 0 failed.` error.  It appears to be due to a preceding error `SyntaxError: Cannot declare a let variable twice: 'e'` caused by the [Safari 10 ES6 loop bug](https://bugs.webkit.org/show_bug.cgi?id=171041#c10)

There is a related Uglify ([UglifyJS2/issues/1753](https://github.com/mishoo/UglifyJS2/issues/1753)) thread that provides a work-around:

CLI:
```sh
--mangle safari10=true
```

or from minify() with the option:

```js
{
  mangle: {
    safari10: true
  }
}
```

So in the context of Nuxt, the config can be tweaked to:
```js
// nuxt.config.js
module.exports = {
  build: {
    uglify: {
      uglifyOptions: {
        mangle: { safari10: true }
      }
    }
  }
}
```
But my suggestion is that Nuxt add this as a default Uglify option, as Safari 10 is still a relatively common browser for those who haven't yet upgraded to High Sierra.

```js
// https://github.com/nuxt/nuxt.js/blob/master/lib/builder/webpack/client.config.js
// line 187
        new UglifyJSPlugin(
          Object.assign(
            {
              // cache: true,
              sourceMap: true,
              parallel: true,
              extractComments: {
                filename: 'LICENSES'
              },
              uglifyOptions: {
                mangle: {
                  safari10: true
                },
                output: {
                  comments: /^\**!|@preserve|@license|@cc_on/
                }
              }
            },
            this.options.build.uglify
          )
        )
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6815">#c6815</a>)</em></sub></div>

**Comment by husayt** [comment]
@Atinux @alexchopin ,   @bjunc has a point: I  and many others haven't registered for CMTY for the same reason. It is asking for too much access. It is asking FULL access to my personal details and gives no option  to exclude private organisations: (see in the pic)
![image](https://user-images.githubusercontent.com/1169324/38191109-2e699fc6-365f-11e8-8297-483e2f7468fd.png)

I am sure this is not what you intended for, but that it is preventing most real users from joining otherwise a very useful platform

**Comment by Atinux** [comment]
@bjunc @husayt it's updated, see https://meta.cmty.io/cmty/cmty/issues/c13, see the steps inside.

Then you can file a Bug report for this issue, this will help us a lot for our issue triage on Nuxt :+1:
