### ISSUE TITLE
window is not defined  in middleware

### ISSUE THREAD

**Issue by dayuweb** [nuxt/nuxt.js#3168]
In middleware ,I can't user window or alert (window is not defined ) , what shoud i do to use them?

**Comment by bovas85** [comment]
Try wrapping in a process.browser if statement

**Comment by rafaelmagalhaes** [comment]
im having same issue even adding process.browser doesnt . work

**Comment by galvez** [comment]
@bovas85 @rafaelmagalhaes I think `process.browser` has been deprecated. Use `process.client` instead.

**Comment by rafaelmagalhaes** [comment]
my app is on universal mode would i need to run it on server side ?

**Comment by bovas85** [comment]
universal means SSR is on, so you need to check for process.browser if you want to use window, or have it as a plugin instead (plugins run before middleware, and can hook on router ready or routeChanged)

**Comment by rafaelmagalhaes** [comment]
i never got it to work with process.browser,

im trying to check if there's a cookie for authorise user to access certain pages,
but i kept getting the error window not defined 

i am using vue-universal-cookies plugin to set token once user logs in

they way i managed to get the cookie on the middleware was 

middleware/auth.js

```
export default (context) => {
    if (!context.app.context.app.$cookies.get(CookieName)) {
        return context.redirect('/login')
    }
}
```

on the page i add

`middleware: 'auth',
`

works fine

**Comment by bovas85** [comment]
process browser works fine, likely the logic didn't
