### ISSUE TITLE
How to use require.ensure() in nuxt router?

### ISSUE THREAD

**Issue by elainema** [nuxt/nuxt.js#3169]
As i used before in vue,
i write vue router like below, to load resource via layload
const Offer_Create = r => require.ensure([], () => r(require('./modules/Offer/Create.vue')), 'offer_create')

how do i take it in nuxt ?

**Comment by apertureless** [comment]
Nuxt automatically splits routes. So they are already lazy loaded.

Btw. `require.ensure` is deprecated. You an use the `import()` syntax.

```js
const OfferCreate = () => import('./OfferCreate.vue')
```
