### ISSUE TITLE
Very weird issue with Boolean attribute "itemscope"

### ISSUE THREAD

**Issue by Kimel1** [nuxt/nuxt.js#3173]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://jsfiddle.net/u01vm19q/2/](https://jsfiddle.net/u01vm19q/4/)

### Steps to reproduce

```html
<div :itemscope="''"> Lorem</div> or <div itemscope> Lorem</div> or <div :itemscope="true"> Lorem</div> 
```

### What is expected ?

`<div itemscope> Lorem</div>`

### What is actually happening?

`<div itemscope="itemscope"> Lorem</div>`

### Additional comments?

And with other custom tags behavior is another. for example
`<div :trololo="''"> Lorem</div>`  will go to `<div trololo> Lorem</div>` 

"itemscope" is an important boolean microdata tag, how to fix that?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6822">#c6822</a>)</em></sub></div>

**Comment by manniL** [comment]
I agree that this is an issue, but as you've shown in your JSFiddle, it's more a vue-related issue than a nuxt-related one.

**Comment by Kimel1** [comment]
@manniL  I have double checked result through   https://search.google.com/structured-data/testing-tool and https://webmaster.yandex.com/tools/microtest/ And yes, it's valid in both cases. So there is no problem for me.  But why the itemscope is behaving quit differently

And I must to draw the attention that in nuxt and pure vue behavior is a little different if you try to pass true value or 'true'

**Comment by manniL** [comment]
You can do this! But as it's a "Vue issue", please open an issue in [the Vue repo](https://github.com/vuejs/vue) :)
