### ISSUE TITLE
Nuxt.js auto completion in Vetur

### ISSUE THREAD

**Issue by octref** [nuxt/nuxt.js#3174]
Hey @Atinux, the thing we talked at VueConf US:

https://github.com/octref/nuxt-helper-json

![nuxt](https://user-images.githubusercontent.com/4033249/38202848-09b8b070-3652-11e8-89ec-7b0fdea07c7f.gif)

I'm hoping you guys can maintain it. It's just two simple json files.
Whenever you change a public API for nuxt's included components, update this package and Vetur can pull the latest definitions to power the auto completion.

Cheers!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6823">#c6823</a>)</em></sub></div>

**Comment by pi0** [comment]
@octref This is fantastic! 😍

**Comment by octref** [comment]
@pi0 I don't have org access to nuxt. So for transferring the repo, maybe you could fork my repo and publish a version on @nuxt.
Also publish a version on npm and I'll update Vetur to depend on it.

**Comment by pi0** [comment]
I've sent you an [invitation](https://github.com/nuxt-community) for nuxt-community. For npm publish, is your NPM username [octref](https://www.npmjs.com/~octref) too?

**Comment by octref** [comment]
Cool I just transferred it to nuxt-community. That might be a better place for it to live.

**Comment by octref** [comment]
Yeah my username is `octref`. But I'm hoping nuxt team can maintain and publish this package since I don't watch nuxt as closely as you folks do.

**Comment by pi0** [comment]
Sure we'll take care of it. Just wanted to keep credits for you :)

**Comment by JillzTom** [comment]
Thanks for the amazing work @octref

**Comment by Atinux** [comment]
Should no be closed :)
