### ISSUE TITLE
Can't get individual cookies of client. Cookies are setted globally 

### ISSUE THREAD

**Issue by anargu** [nuxt/nuxt.js#3176]
I handled authentication with cookies in Nuxt, the code is as bellow:

     nuxtServerInit ({ commit, state }, { req }) {

        console.log('nuxtServerInit')

        if (req.headers.cookie) {
          let cookieParsed = cookieparser.parse(req.headers.cookie)

          // console.log(cookieParsed)
          if (cookieParsed.token !== undefined && cookieParsed.userId !== undefined) {
            // console.log('parsed.token', cookieParsed)
            let token = null
            token = cookieParsed.token
            state.userId = cookieParsed.userId
            commit('auth/setToken', token)
          }
        }
      },

But, while I test and I login I could access succesfully to my account. But if I try in another Pc or in a new incognito window in Chrome I could access to the same account that I did before. How is it possible? It seems cookies are stored globally. But in the code I get cookies from req (the client request). Please let me know what I missed out.

**Comment by pi0** [comment]
@anargu It may be related to your store token. You have to take care not keeping **anything** globally. Anyway, you can also try [auth module](https://auth.nuxtjs.org) if that works for you or can get idea :)

**Comment by anargu** [comment]
Hi @pi0 

It seems  that this code fix the issue:


      nuxtServerInit ({ commit, state }, { req }) {

        console.log('nuxtServerInit')
        console.log('req.headers', req.headers)
        if (req.headers.cookie) {
          let cookieParsed = cookieparser.parse(req.headers.cookie)

          // console.log(cookieParsed)
          if (cookieParsed.token !== undefined && cookieParsed.userId !== undefined) {
            // console.log('parsed.token', cookieParsed)
            let token = null
            token = cookieParsed.token
            console.log('token', token)
            state.userId = cookieParsed.userId
            commit('auth/setToken', token)
          } else {
            state.userId = ''
            commit('auth/setToken', null)
          }
        }
      },

if there is not cookies with the field I specified in the if conditional, then sets to the default value for state.userId = '', and token. But I really want to know why that happened. I mean, if there are not cookies saved on the request, why it returns an acount globally (account previously logged in but in another pc)?

**Comment by pi0** [comment]
@anargu For this, you have to review where areas exactly keep the token. (For example axios commons or ..). One of those sources may be the source of the leakage.

**Comment by anargu** [comment]
Actually I set the token in axios by axios.setToken(..) and the token I get from the store. But I am still wondering how nuxtServerInit works and why it get the past token from another past connection. You said I should review in which area I should keep the token, one of this is axios.commons. There is another area you recommend me to store token? I use cookies to store it.

**Comment by pi0** [comment]
@anargu If you are not using axios but not axios module for setting commons that may cause! It has known issues.

**Comment by anargu** [comment]
I think I got with a solution. I defined my state as a normal constant, but not as function, so now it's contextualized for each client.
