### ISSUE TITLE
如果注入webpack配置？

### ISSUE THREAD

**Issue by baermowei** [nuxt/nuxt.js#3181]
因为打包后的代码head标签里面都是<style>标签，想要打包成一个css文件。于是想要注入 const ExtractTextPlugin = require('extract-text-webpack-plugin');
然后在config.module.rules.push（）的方法注入；可是没有效果；
console.log 之后发现都打印两边。
请问如果解决这个问题？
PS： 使用vue-cli 默认就打包单独css;所以为何不集成这种默认功能呢？

**Comment by Atinux** [comment]
Please translate to english so we can have a common language.

**Comment by missy0u** [comment]
```
// nuxt.config.js
...
build: {
  extractCSS: {
    allChunks: true
  }
},
...
```

> 生产环境下才会打包成一个css文件

npm run build
npm run start

[#3102](https://github.com/nuxt/nuxt.js/issues/3102#issuecomment-375499071)
