### ISSUE TITLE
The development environment is normal, test environment h5 page error, help

### ISSUE THREAD

**Issue by zheng1013757145** [nuxt/nuxt.js#3184]
https://nuxtjs.cmty.io/issues/new

[nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method

**Comment by Atinux** [comment]
Hi @zheng1013757145 

Please report this issue directly on https://meta.cmty.io (or https://github.com/cmty/cmty if CMTY app does not work on your computer).

Also, make sure to use Google Chrome or Firefox at the moment.
