### ISSUE TITLE
First meaningful content in nuxt.js

### ISSUE THREAD

**Issue by wushan** [nuxt/nuxt.js#3186]
Hi All,
I am using nuxt.js for my latest spa project, the project is almost finished but I found an serious performance issue.

When have a bunch of dynamic components in the page, the first meaningful content shows up after all decencies are downloaded, this  issue is very serious when clients has a slow internet connection.

index.vue
```
<template lang="pug">
  .container
    p first meaningful content
    components(:is="currentComp")
</template>

<script>
const components = {
  aComponent: () => import('~/components/a' /* webpackChunkName: 'components/aComponent' */),
  bComponent: () => import('~/components/b' /* webpackChunkName: 'components/bComponent' */),
  cComponent: () => import('~/components/c' /* webpackChunkName: 'components/cComponent' */)
}
```

**Comment by Atinux** [comment]
Same as https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6837.

Please don't duplicate issues.

**Comment by wushan** [comment]
I am sorry about this.
