### ISSUE TITLE
Nuxt slow compiling & building

### ISSUE THREAD

**Issue by Chathula** [nuxt/nuxt.js#3187]
i have a page file which has more than 900 lines of html code. also it includes css and js code. it takes a lot of time to build and compile. i checked both linux and windows environments. help me on this issue.

Thank You.

**Comment by Atinux** [comment]
Hi @Chathula 

Actually it's mostly from Webpack, not from Nuxt.js itself.

Nuxt 2.0 will be out soon with 2x build performance.

**Comment by sudam96** [comment]
Hi @Atinux

I have the same issue. Is there any solution for this?
I would really appreciate one because I'm doing a project with nuxt.

**Comment by joostdecock** [comment]
Here's a good read on the matter: https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67

**Comment by Chathula** [comment]
@joostdecock , thanks for share :dancer:

**Comment by luatnd** [comment]
Thanks for the nuxt edge!
I'm migrating from a HTML file that contains 1000 LOC, and  I still have this slow issue on Nuxt Edge. 
How can I make the build process faster ?

**Comment by luatnd** [comment]
I broke 1000 line of HTML into smaller components, as a result, Nuxt has built very fast.
Now my migration process was completely easy with nuxt. Thanks all nuxt's contributors (y)
For best build performance, just avoid 500 line of HTML in your template.
