### ISSUE TITLE
$router.push() not working in NuxtJS

### ISSUE THREAD

**Issue by pkganthali** [nuxt/nuxt.js#3188]
I was trying to use $router.push() to navigate to a different page on clicking NEXT Button on the first page.

When I am clicking Next button, it is navigating to next page and immediately reloading the first Page.

> 1 ) step1. vue
         ```
     ```
`<button type="submit" @click="updateCurrentPageIndex(), gotoNextPage()">Next</button>`
         
         gotoNextPage() {
                 this.$router.push(this.$store.state.pages[this.$store.getters.currentPageIndex]);
          },
       updateCurrentPageIndex() {
                 this.$store.commit('updateCurrentPageIndex');
         }
```

```

>    2) store/index.js

     ```
 import Vuex from  'vuex';

     const store = ()  =>  {
      return new Vuex.Store({
    state: {
        pages:['step1','step2','step3','summary'],
        currentPageIndex:0
     },
     getters: {
        currentPageIndex(state) {
            return state.currentPageIndex;
        }
    },
     mutations: {
        updateCurrentPageIndex(state) {
            state.currentPageIndex++;
        }
    }
```

**Comment by nikkanetiya** [comment]
@pkganthali Hello, are you sure it is not happening due to `type="submit"` you have used for submit button, your form might be submitted, there is nothing vue.js code which can cause the page reload.

**Comment by pkganthali** [comment]
@nikkanetiya  I have removed submit and still it remains the same. Its generally the $router.push is not taking me to the next page. On clicking next it has to move from Page1 to Page2.

**Comment by uptownhr** [comment]
How is pageindex used?

**Comment by pkganthali** [comment]
@uptownhr Initially I initialized pageIndex as 0 in the store/index.js file. I have an pages array pages[step1, step2, step3, summary]. I am incrementing pageindex on click of next button so that it naviagtes to step2 page in the array which is  at pageindex 1

**Comment by pkganthali** [comment]
@uptownhr I have pasted my files how the pageIndex is used.

**Comment by uptownhr** [comment]
@pkganthali is the store.state.page used in any other way? other than using it for push?

**Comment by pkganthali** [comment]
@uptownhr  No I am using it only in push

**Comment by pkganthali** [comment]
@uptownhr  I have added @submit.prevent, it resolved my issue. Thank You

**Comment by pkganthali** [comment]
@nikkanetiya Thanks for your quick response

**Comment by nikkanetiya** [comment]
@pkganthali Glad you found the problem. Please make this question as resolved.
