### ISSUE TITLE
nuxt.config variable in layouts

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#319]
```
// default.vue
<script>
    // like here receive a variable from the config?
    export default {}
</script>
```

**Comment by awronski** [comment]
Do you mean you want to access a ```context``` from the layouts?

**Comment by stursby** [comment]
@wormen You can just import `nuxt.config.js` and read from that object. Example:

```javascript
// nuxt.config.js
module.exports = {
  head: {
    title: 'My Website'
  }
}
```

```vue
// layouts/default.vue
<template>
  <div>
    <h1>{{ heading }}</h1>
    <nuxt/>
  </div>
</template>

<script>
import config from '../nuxt.config'

console.log(config)

export default {
  data() {
    return {
      heading: config.head.title
    }
  }
}
</script>
```

**Comment by wormen** [comment]
@stursby it is a bad decision, if the configuration has to be connected on each page, it is better to have a configuration in the global scope

**Comment by stursby** [comment]
@wormen I think it depends on what you're trying to access. If it's something simple like `title`, etc. I think it's to just load it like I mentioned above. If you're trying to access a global state in multiple pages/components, I would recommend using [Vuex](https://nuxtjs.org/guide/vuex-store/#__nuxt).

**Comment by wormen** [comment]
@stursby This option is also not suitable for this task, because I use multiple templates at the same time
+ I think that the system configuration must be done in one place rather than in multiple locations

**Comment by stursby** [comment]
@wormen Well then I guess I'm just not quite sure I understand what you're trying to accomplish. That being said, you can access the Vuex store globally in multiple templates at the same time.

See a quick [DEMO](https://nuxt-playground-brmxiomtjr.now.sh/) and (SOURCE)[https://nuxt-playground-brmxiomtjr.now.sh/_src/?f=package.json]

**Comment by wormen** [comment]
@stursby if this task will use vuex, it turns out that I have a config app will be split into several parts, and it should be in one place

**Comment by wormen** [comment]
@stursby in my case, the only place for the storage of config it nuxt.config.js
but connect it to each template page, it is not normal

**Comment by awronski** [comment]
If you want to have a configuration in a global scope you can check my [example.](https://github.com/awronski/nuxtjs-examples/tree/master/external-configuration)

**Comment by wormen** [comment]
@awronski Yes, this option is right for me
thanks

**Comment by Art-Mas** [comment]
@awronski works only on page components in asyncData method. Thats not a global

**Comment by arkceajin** [comment]
`import config from '~/nuxt.config'` this shall be better.

**Comment by Hxmic** [comment]
Vuex, How to auto get variable in  'text.vue'. The varibale is 'navigator.userAgent'.
