### ISSUE TITLE
Set minimum duration of execution for loadingIndicator 

### ISSUE THREAD

**Issue by andrii-trush** [nuxt/nuxt.js#3190]
Hello I'm using my own loadingIndicator (https://nuxtjs.org/api/configuration-loading-indicator) and i would like to set minimum duration of execution.
Are there any opportunities to do it?

**Comment by pi0** [comment]
Hi. It is only enabled for default loadingIndicator. You can see implementation to get idea how it works:

https://github.com/nuxt/nuxt.js/blob/dev/lib/app/views/loading/default.html#L4

**Comment by andrii-trush** [comment]
@pi0  Hi. I think you don't understand i mean. 
I need to show preloader minimum 4 second, even if page already loaded

**Comment by nikkanetiya** [comment]
@andrii-trush I think you can simply create custom loading component as showing in documentation here

`https://nuxtjs.org/api/configuration-loading#use-a-custom-loading-component `

and just change finish method somewhat like this

```
finish () {
  setTimeout(() => {
    this.loading = false
  }, 4000)
}
```

It will simply add 4 second delay, but remember total time will be whatever time it has already taken to load + 4 second you have added here.

**Comment by andrii-trush** [comment]
@nikkanetiya it is another loading
I need for https://nuxtjs.org/api/configuration-loading-indicator
not for https://nuxtjs.org/api/configuration-loading

**Comment by nikkanetiya** [comment]
@andrii-trush Ahh, Sorry my mistake.

**Comment by template01** [comment]
Hey! any news on this issue?
