### ISSUE TITLE
Automatic handling, simplified handling or more explicit docs for handling ssr-issues with community components

### ISSUE THREAD

**Issue by emdahlstrom** [nuxt/nuxt.js#3192]
### What problem does this feature solve?

Trying to use third party vue components in Nuxt can be a huge pain because many only work on the client side. Googling there are hundres of issues created about it either in nuxt or on the component repos.

Even if the component can be made ssr-safe by only rendering it in the browser this still means a performance loss since the user will then need to wait for the component and all subcomponents or other markup to render. 

### What does the proposed changes look like?

In order of ease for the developer:

1) Find some way to automatically handle non-ssr-safe components. Can they be autodetected? Are there ways of making them work on the server side so they can still be rendered on the server?

2) Is there some way of making it easier for developer to handle ssr issues with community components? The vue-no-ssr component doesn't always solve it, nor do the sparse instuctions in the docs: https://nuxtjs.org/faq/window-document-undefined/

3) Improve the docs so the developer can easily grasp what the problem or problems are and how they can be solved or mitigated. 

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6848">#c6848</a>)</em></sub></div>

**Comment by uptownhr** [comment]
@emdahlstrom lets start here and building some initial items to maybe start a nuxt cookbook for the future. 

1. window is not defined. Normally a symptom of a library expecting the window object to be available during SSR. This can occur on initially importing the library or upon use. If the issue occurs at import, there is a chance the lib supports a non initializing entry point. If not, you'll have to resort to either using require at runtime or creating a plugin that imports but mark {ssr:false} on the plugin configuration.

**Comment by emdahlstrom** [comment]
@uptownhr Awesome! I'll try to help but have to admit I'm at loss with a few components and unsure how to progress so not sure how I can help with the documentation - but keen to try! 

One attempt is listing a few other problems that can happen:

1) Same as with window but with the error "document is not defined". (an example with vue-float-label, my issue: https://github.com/bkzl/vue-float-label/issues/22)

2) A component is rerendered in the browser even though it is already rendered on the server. This can mean that the user needs to wait for the component to rerender before the content is visible.
An example is the vue-markdown component, my issue: https://github.com/miaolz123/vue-markdown/issues/62

Is this a completely different issue perhaps?

3) "Unexpected token import"
my issue with vue-focuspoint-component: https://github.com/EvodiaAut/vue-focuspoint-component/issues/1
The suggested issue to look at: https://github.com/nuxt/nuxt.js/issues/2392

Is this about how component authors use imports internally? Would community guidelines help? Are there easy fixes to suggest to the author when this type of issue occurs?

I believe I've seen this happen where a component injects its own css, and that one component changed how it did this to make it ssr safe. 

4) Cases where you can safely use the no-ssr-component
https://github.com/nuxt/nuxt.js/issues/2678
https://nuxtjs.org/api/components-no-ssr/ (now a part of nuxt it seems!)

I guess the no-ssr component is an option when it concerns content that can safely be hidden behind a loader/spinner without negatively impacting the user, content below the fold and flat content that doesn't contain a lot of other components that need to be rendered or data that needs to be fetched. 

I'm unsure in what scenarios the no-ssr component simply doesn't work, I haven't had much luck with it but its likely because I'm missing something else about nuxt plugins or vue.

**Comment by manniL** [comment]
Closed in favor of https://github.com/nuxt/docs/issues/848

A PR would be appreciated 🙊
