### ISSUE TITLE
Nuxt's default webpack config should handle .vue extension imports inside pages

### ISSUE THREAD

**Issue by robcresswell** [nuxt/nuxt.js#3193]
If I import a `.vue` file inside a page, it fails to resolve unless I specify the extension.
For example, this will fail to load:

```vue
<script>
import MagnifyIcon from "vue-material-design-icons/magnify"

export default {
  ...
}
</script>
```

And this will succeed:

```vue
<script>
import MagnifyIcon from "vue-material-design-icons/magnify.vue"

export default {
  ...
}
</script>
```

**Comment by robcresswell** [comment]
@chanlito Yep, but you can configure webpack to use whatever extension you like, so it will look for both.

**Comment by chanlito** [comment]
Yet some IDE will complain file not found probably.
