### ISSUE TITLE
Broken  in chrome 41

### ISSUE THREAD

**Issue by joaocarvalhowd** [nuxt/nuxt.js#3199]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://www.e-lens.com.br/](https://www.e-lens.com.br/)

### Steps to reproduce

Open in chrome 41
![Screenshot from 2018-04-05 19-03-34.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/6ac249c0-391e-11e8-af88-55fe2bb5eaa8.png)

### What is expected ?

Solution

### What is actually happening?

Broken  in chrome 41, it's same version which google use to crawler

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6858">#c6858</a>)</em></sub></div>

**Comment by kavalcante** [comment]
Same happen here.

Link to reproduce: https://www.browserling.com/browse/win/7/chrome/41/https%3A%2F%2Fcotabox.com.br

![screenshot from 2018-04-05 19-11-09](https://user-images.githubusercontent.com/13931503/38394674-cbff861c-3905-11e8-8005-588e9dc15f6f.png)

I can't use the website, all links does not open and components not react to click.

**Comment by joaocarvalhowd** [comment]
@pi0

**Comment by Atinux** [comment]
Hi @joaocarvalhowd 

Actually, I tried with Chrom 41 and I have another error:

![Screen Shot 2018-04-10 at 09.36.07.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/e6527c10-3c91-11e8-b43a-cf761c94c182.png)

The error about client-side not matching is when you have client-side script or even Chrome that update the rendered HTML before Vue hydration, it might be because of a phone number for example.

You can update the babel env in your `nuxt.config.js`: 

```js
module.exports = {
  build: {
    babel: {
      presets({ isServer }) {
        if (isServer) return null // Use default
        return [
          ['vue-app', {
            targets: {
              chrome: 40,
              edge: 9,
              firefox: 40,
              ie: 9,
              safari: 7
            }
          }]
        ]
      }
    }
  },
};
```

**Comment by joaocarvalhowd** [comment]
@Atinux We found the problem the real problem. And we managed to solve it.
https://github.com/nuxt/nuxt.js/issues/3199

Thanks for trying to help us 😄

**Comment by kavalcante** [comment]
I tried both @joaocarvalhowd and @Atinux and I still get this error: `TypeError: undefined is not a function`

To reproduce: https://www.browserling.com/browse/win/7/chrome/41/https%3A%2F%2Fcotabox.com.br
