### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by pulkitnandan** [nuxt/nuxt.js#320]
Hi,

Is there a way in nuxt by which I call the same set of lines when app is server side rendered i.e. calling code from apps data method and the same code when the app is client side rendered i.e. calling code present in a watch without writing the same code twice.

It is an obvious use case for dynamically identifying weaker server or weaker client delivering the optimum UX.

**Comment by alexchopin** [comment]
Nuxt code is executed both on server-side and client side. You should not have code duplication.
