### ISSUE TITLE
Error production nuxt 

### ISSUE THREAD

**Issue by daviddsp** [nuxt/nuxt.js#3200]
Hello everyone !!

I have a problem, i am using nuxt with SSR but when a try test my application to browser this doesn't answer correctly. From browser is the next.

ERR_CONNECTION_REFUSED

My package.json is:

`{
  "name": "example",
  "version": "1.0.0",
  "description": "Nuxt.js project",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "cross-env": "^5.1.4",
    "express": "^4.16.3",
    "nuxt": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "eslint": "^4.15.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-vue": "^4.0.0"
  }
}
~
~`

Any ideas??

**Comment by nikkanetiya** [comment]
Are you sure, the port is opened if you are testing it on server. If you are doing it in local make sure  there are no other application already running on same port (By default the nuxt will use 3000)

**Comment by nikkanetiya** [comment]
yes, as apps will run simply on SSR, for example this is running, forget about the rest of inner page logics. How you are running your apps, are you running node process after `npm run build` or you have just killed it?

**Comment by daviddsp** [comment]
@nikkanetiya If first I run the npm run build command and then I do a npm start.

**Comment by nikkanetiya** [comment]
Are you keep that terminal open? that's what I am asking? or else for production you will need to use something like pm2 or forever

**Comment by gangsthub** [comment]
as @nikkanetiya commented, forever is the key. This is my start script:

```
"start": "cross-env NODE_ENV=production forever -a -l forever.log -o out.log -e err.log --minUptime 1000 --spinSleepTime 1000 start build/main.js",
```

**Comment by gangsthub** [comment]
also, @daviddsp, you are setting up an express server, but you are not using nuxt there...: https://nuxtjs.org/api/internals-builder/

My advise would be to use one of the templates nuxt has:

For example, using their cli: https://github.com/nuxt-community/create-nuxt-app
