### ISSUE TITLE
when use commonJS Module and JSON.stringify together, a error occured. Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by DualWield** [nuxt/nuxt.js#3204]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/DualWield/nuxt-test](https://github.com/DualWield/nuxt-test)

### Steps to reproduce

// logger.js
```
JSON.stringify({name: 'test'})

module.exports = {
    info() {
        console.log('info');
    },
    error() {
        console.log('error');
    }
}
```

// page/index.vue
const logger = require('./logger');
logger.info();

### What is expected ?

No error occured 

### What is actually happening?

Cannot assign to read only property 'exports' of object '#<Object>'

### Additional comments?

I know this error happened because mixing `import` and `module.exports`. But why I remove JSON.stringify , it works ? I want the logger.js is commonjs module style, because this file is both required in client and node server. And I don't want to use webpack to compile the node file. such a big pit(坑) 

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6868">#c6868</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @DualWield 

This is related to https://twitter.com/adamwathan/status/968652732167995392 and https://github.com/tailwindcss/tailwindcss/pull/402.

You should use `global.JSON.stringify` if you want to keep CommonJS module :+1:

**Comment by DualWield** [comment]
@Atinux Thank you very much !!!!!! It works!!! I have spent a lot of time to search the solution.
