### ISSUE TITLE
After using router.push\replace asyncData not called on new page

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#3205]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://glitch.com/edit/#!/poised-hardware](https://glitch.com/edit/#!/poised-hardware)

### Steps to reproduce

https://poised-hardware.glitch.me/ - if you go index page u will see render error due to undefined variable. But index page only do router.push to /page2.
If u go directly to https://poised-hardware.glitch.me/page2 all renders fine.

### What is expected ?

asyncData called and variable resolved so no error happened like when page accessed directly without router.push

### What is actually happening?

render error due to undefined variable that should come from asyncData

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6869">#c6869</a>)</em></sub></div>

**Comment by yoyo837** [comment]
`asyncData ` is server only.

**Comment by aldarund** [comment]
@yoyo since when it's server only ? It's not server only

**Comment by Atinux** [comment]
Hi @aldarund 

You cannot use `$router.push` or `$router.replace` inside `fetch` or `asyncData`. To understand more, these methods are called inside `router.beforeEach`. **You need to call `redirect`**.

Please see your example fixed: https://glitch.com/edit/#!/lying-ring?path=pages/index.vue:2:1

**Comment by aldarund** [comment]
@Atinux thanks, that worked. Is it documented somewhere?

**Comment by Atinux** [comment]
It is not, it is pretty hard to document everything, you can find more about the context here: https://nuxtjs.org/api/context

**Comment by aldarund** [comment]
@Atinux redirect works. but it seems to cause lose of store state. E.g. on first page i set some store variables, then redirect to second page. And on second page all set variables are lost.
https://glitch.com/edit/#!/furry-shop
