### ISSUE TITLE
middleware on page-reload is not called on process.client

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#3208]
### What problem does this feature solve?

I placed a middleware on a page like:
```js
export default{
 middleware:['isAuth']
}
```
and this is the middleware code
```js
export default function ({store, redirect}) {
  console.log(process.client) => never called on page-reload
  if (!store.getters.canEdit && process.client) {
    return redirect('/')
  }
}
```
This middleware works if I route to pages which are connected to the middleware. But if I do a page-reload on a page then the code is only getting executed on the server. Is this a bug or by design?

### What does the proposed changes look like?

The middleware should execute always client and server side - either on page reload or routing.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6873">#c6873</a>)</em></sub></div>

**Comment by dohomi** [comment]
@Atinux @pi0 I am not sure but is this actually a feature or a bug? Shouldn't the middleware be called always on server and then on client side before the page is executed? Because like this I can't guard my page correctly for waiting for some `process.client` code being executed.

**Comment by uptownhr** [comment]
@dohomi been said many times by the nuxt team that middlewares will only load on the server side on a fresh reload. This is to prevent the middleware running twice. 

I do agree, that this behavior does limit the usage of middlewares. I ran into this problem/question when I was populating the store with a middleware and caused the server and client to be different - causing a hydration issue.

**Comment by dohomi** [comment]
@uptownhr Thanks for clarify this, I adopted the code already and it make sense to prevent the code to execute twice. Even though I can imagine that there are usecases where its hard to receive the same behaviour both on client and server side.

I think my mistake was using the middleware as authGuard on client-side only pages.

**Comment by Atinux** [comment]
Hi @dohomi 

Indeed, as @uptownhr said, the middleware are ran only on the server-side since they should have the same behaviour on server & client.

If you render a page on the server-side and the middleware had run, even if calling the middleware on client-side, there should be **no difference** otherwise a mismatch DOM will happen.
