### ISSUE TITLE
Weird transition between page and layouts/error.vue

### ISSUE THREAD

**Issue by rbwilcoxon11** [nuxt/nuxt.js#3210]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://beta.twigi-bi.io](https://beta.twigi-bi.io)

### Steps to reproduce

Click on the CDN tab (a page I have yet to add content for)

### What is expected ?

The layouts/error.vue page should appear after the old page disappears 

### What is actually happening?

The layouts/error.vue page renders side by side with the previous page until the previous page transitions out

### Additional comments?

It looks like its running the transition in mode in-out, or maybe because its bringing up a new layout it doesn't respect the transition from a page.

It only occurs when going to a 404, not away from it.

If you click on documentation, or the logo you will find content (minimal content...). Anything under documentation (in the dropdown menu) and cdn leads to a 404.

I can upload my source code if I need to.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6875">#c6875</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @rbwilcoxon11 

Thank you for this bug report, we will take a look at it, transitions are the trickiest part. You can help us by looking at your `.nuxt/client.js` file and edit it to understand what's happening under the hood. This could help us to localise where might be this behaviour.

**Comment by rbwilcoxon11** [comment]
I found a hacky fix, but not sure how to actually implement said change.

The change to client.js that fixed my issue was this:


``` javascript
async function render (to, from, next) {
...
  // If no Components matched, generate 404
  if (!Components.length) {
    // Default layout
    await callMiddleware.call(this, Components, app.context)
    if (nextCalled) return
    // EDIT: HIDE CURRENT PAGE BEOFRE LOADING ERROR PAGE
    from.matched[0].instances.default.$el.style.display = 'none'
    // Load layout for error page
    const layout = await this.loadLayout(typeof NuxtError.layout === 'function' ? NuxtError.layout(app.context) : NuxtError.layout)
    await callMiddleware.call(this, Components, app.context, layout)
    if (nextCalled) return
    // Show error page
    app.context.error({ statusCode: 404, message: 'This page could not be found' })
    return next()
  }
...
}
```

I added the line underneath the "EDIT" comment. Essentially, the error layout is getting pulled to the page before the from layouts transition begins.

I'm not necessarily using the transitions myself, so simply setting display to none  on the from component works for me.

**Comment by rbwilcoxon11** [comment]
Update: this produced an error when going from a link that doesn't exist, to a link that doesn't exist. Had to check to make sure the "from" was not coming from an erred page.

```javascript
async function render (to, from, next) {
...
    // EDIT: MAKE SURE YOU ARE COMING FROM A NON ERRED PAGE
    if (Array.isArray(from.matched) && from.matched.length > 0) {
      // EDIT: HIDE CURRENT PAGE BEOFRE LOADING ERROR PAGE
      from.matched[0].instances.default.$el.style.display = 'none'
    }
...
}
```

**Comment by nicooprat** [comment]
I think I'm getting the same error. Here's my workaround:

```css
#__layout > :first-child:not(:only-child) {
  display: none;
}
```

It just prevents two root element to be visible at once, by hiding the old one.
