### ISSUE TITLE
linkActiveClass doesn't work with Non-ASCII URL in SSR

### ISSUE THREAD

**Issue by NemoAlex** [nuxt/nuxt.js#3211]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/NemoAlex/nuxt-test](https://github.com/NemoAlex/nuxt-test)

### Steps to reproduce

npm run dev

### What is expected ?

Current link will be green.

### What is actually happening?

linkActiveClass doesn't work with Non-ASCII URL in SSR. When you on /测试，refresh the browser, linkActiveClass has gone.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6876">#c6876</a>)</em></sub></div>

**Comment by Atinux** [comment]
I'll cc @posva since he is the maintainer of vue-router and uses Nuxt.js as well

**Comment by posva** [comment]
I tested on a jsfiddle with only vue-router and it works correctly: https://jsfiddle.net/m9e2w4ao/

**Comment by NemoAlex** [comment]
@posva The bug happens when you on /测试 and then refresh browser. This probably can't be tested  on Jsfiddle.

**Comment by manniL** [comment]
Possibly related: https://github.com/vuejs/vue-router/issues/838#issuecomment-390706679

**Comment by aldarund** [comment]
on non dynamic non ascii urls it work fine

**Comment by aldarund** [comment]
@posva it dont work correctly with vue router on initial load, it work correctly later but not on initial load, see example on codesandbox in my PR  https://github.com/vuejs/vue-router/pull/2375
