### ISSUE TITLE
Sourcemaps suddenly no longer created with Nuxt upgrade from 1.0.0-rc11

### ISSUE THREAD

**Issue by jazoom** [nuxt/nuxt.js#3213]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://gitlab.com/jazoom-web/nuxt-minimal](https://gitlab.com/jazoom-web/nuxt-minimal)

### Steps to reproduce

`yarn`
`npm run build`

### What is expected ?

.js.map files created for each .js file

### What is actually happening?

no .js.map files

### Additional comments?

Unfortunately I only just found out about this now. In multiple projects sourcemaps were no longer created after the update from 1.0.0-rc11 to 1.3.0 a couple of months ago. Strangely, even when installing 1.0.0-rc11 now sourcemaps still are not created.

I have searched through Nuxt's documentation and found the following code mentioned, but even adding that doesn't force sourcemap creation.

```
if (isClient) {
  config.devtool = 'eval-source-map'; // create sourcemaps
}
```

What happened after 1.0.0-rc11 to stop sourcemap creation and how do I get them back?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6879">#c6879</a>)</em></sub></div>

**Comment by nallown** [comment]
Use this instead:
```js
if (isClient) {
  config.devtool = '#source-map';
}
```

**Comment by jazoom** [comment]
I tried `source-map` also and that didn't work.

What does the "#" add to it? I can't find that in the Webpack documentation: https://webpack.js.org/configuration/devtool/

**Comment by nallown** [comment]
It's what I needed to add to generate the source maps. Send me your babal config I'll try to debug it for you.

**Comment by jazoom** [comment]
I just tried '#source-map' and it worked.

How very strange that a couple of months ago with no configuration change an update to the Nuxt dependency stopped all sourcemap creation.

It's also very strange that '#source-map' is the ONLY thing that seems to work and it's not even documented anywhere!

**Comment by jazoom** [comment]
I'll leave this issue open since this should probably be documented in Nuxt's docs.

**Comment by nallown** [comment]
Have you tried `#eval-source-map`? The default vue generator makes a babel config with `#source-map`.

**Comment by jazoom** [comment]
If that's so, then shouldn't the Nuxt documentation NOT say this:

```
if (isClient) {
  config.devtool = 'eval-source-map'; // create sourcemaps
}
```

**Comment by nallown** [comment]
I thought that part was outdated but then I thought again and was like nah, but I guess you're right.

You can change it over [here](https://github.com/nuxt/docs/blob/master/en/api/configuration-build.md) if you want. Just change the file to say the right thing and remember to change it for every language as well over here https://github.com/nuxt/docs.

It's only a simple markdown file you have to change. I know its annoying that we have to do this kind of stuff our selves and clean up their mistakes but you can't get everything right when you have this big of a module to take care of.

**Comment by jazoom** [comment]
I might just leave it for someone who already has a local clone of the repository. It's quite a bit of mucking around to just add one character. I don't mind missing out on contrib juice.

**Comment by Atinux** [comment]
Docs updated, thanks!

It's not easy to keep up with everything when it's not your day job and you also do it for free.
