### ISSUE TITLE
Windows server running with pm2 error！anxious！

### ISSUE THREAD

**Issue by warriorBrian** [nuxt/nuxt.js#3220]
### Version

[v1.0.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

I am using PM2 to deploy my nuxt service on a windows server but I get an error and I am using a Linux server without error

`pm2 start npm --name "demo3" -- run start`

### What is expected ?

![TIM截图20180413155800.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/6abdb1d0-3ef0-11e8-ae86-f5308d40d900.png)

### What is actually happening?

![TIM截图20180413155847.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/88547670-3ef0-11e8-ae86-f5308d40d900.png)

### Additional comments?

I don't know how to start nuxt on the server, but using linux server without problems and using windows server has a problem, we have been using windows which makes our business no way to run

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6896">#c6896</a>)</em></sub></div>

**Comment by manniL** [comment]
It'd help if you could provide the whole stack trace/error message.

**Comment by manniL** [comment]
Because this bug report seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
