### ISSUE TITLE
nuxt-typescript example has `vue is not defined` error 

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#3226]
@alidcastano: 

### Version

[1.4.0](https://github.com/nuxt/consola/releases/tag/1.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript](https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript)

### Steps to reproduce

run fresh example

### What is expected ?

no errors 

### What is actually happening?

`Vue is not defined` error likely due to a ssr issue, which might cause problems in production 

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c7">#c7</a>)</em></sub></div>

> Moved from https://github.com/nuxt/consola/issues/12

**Comment by alidcastano** [comment]
I believe this wasy fixed https://github.com/nuxt/nuxt.js/pull/3175

**Comment by xudongcc** [comment]
@alidcastano This problem has not been solved. I have made a simple test and found that this problem will only appear in TypeScript 2.8. There will be no errors in version 2.7.

```
npm i -D typescript@2.7
```

Before this problem was solved, I thought adding a `package-lock.json` file was a better temporary solution.
