### ISSUE TITLE
custom class instance returned by asyncdata

### ISSUE THREAD

**Issue by syffs** [nuxt/nuxt.js#3227]
### Version

nuxt-edge

### Reproduction link

[https://github.com/syffs/nuxt-asyncdata-class-instance-issue](https://github.com/syffs/nuxt-asyncdata-class-instance-issue)

### Steps to reproduce

see the [repro link](https://github.com/syffs/nuxt-asyncdata-class-instance-issue/blob/831ce866bbb8b183334bff75a71b3627e0cf2e16/pages/index.vue#L29): is there some workaround to make this work?

ssr works well, but client rendering fails (as methods are undefined)

all the hooks `beforeCreate`, `created`, `mounted` in the world are unfortunately unhelpful here, because computed property gets somehow called before

### What is expected ?

being able to pass a class instance somehow

### What is actually happening?

SSR JSON serialization ignores all the methods, but I'm unable to reinstate the class instance on client side with some hook.

### Additional comments?

it is not really a bug, but cmty questions are ignored.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6906">#c6906</a>)</em></sub></div>

**Comment by koteezy** [comment]
The problem hasn't been solved?

**Comment by syffs** [comment]
@koteezy AFAIK, no

Even though, it's not ideal, I simply avoided the issue by passing data only and externalizing methods

**Comment by Atinux** [comment]
Hi @syffs 

Well, I found a workaround by I don't recommend it. 

```vue
<template>
  <div>
    {{ formattedValue }}
  </div>
</template>

<script>
import { TestClass } from '~/utils/test-class'

export default {
  asyncData (ctx) {
    return {
      testClass: new TestClass(2, 10)
    }
  },
  created () {
    if (!(this.testClass instanceof TestClass)) {
      this.testClass = new TestClass(this.testClass.value1, this.testClass.value2)
    }
  },
  computed: {
    formattedValue () {
      return this.testClass.values.map(v => `found value ${v}`)
    }
  }
}
</script>
```

But this is custom to every class you have, either you use `data` for instances or you create them in the `created` hook, for instance:

```vue
<template>
  <div>
    {{ formattedValue }}
  </div>
</template>

<script>
import { TestClass } from '~/utils/test-class'

export default {
  asyncData (ctx) {
    return {
      testClass: null,
      value1: 2,
      value2: 10
    }
  },
  created () {
    this.testClass = new TestClass(this.value1, this.value2)
  },
  computed: {
    formattedValue () {
      return this.testClass.values.map(v => `found value ${v}`)
    }
  }
}
</script>
```
