### ISSUE TITLE
Cannot find module './1523814304790.jpg'

### ISSUE THREAD

**Issue by Nisthar** [nuxt/nuxt.js#3228]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://jsfiddle.net/Nisthar/1etdwofj/](https://jsfiddle.net/Nisthar/1etdwofj/)

### Steps to reproduce

I am using @nuxt/axios and nuxt-dropzone to upload the image from the client. Its working fine. The image gets stored on assets/uploads folder. But when i tried to redirect to the page to show the uploaded image (redirect without refresh), it shows  Cannot find module './1523814304790.jpg'

I can refresh the page and see the image. But it does not work automatically.

### What is expected ?

to navigate (without refresh) after the form is submitted, to the page where the image is shown.

### What is actually happening?

After the form is submitted, it redirects. But getting error Cannot find module './1523814304790.jpg'

### Additional comments?

I can refresh the page and see the image. But it does not work automatically.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6907">#c6907</a>)</em></sub></div>

**Comment by clarkdo** [comment]
If the `file` in `addImage` is the file path inside assets, please use `this.image = require(\`${file}\`)`
