### ISSUE TITLE
Custom layouts dir

### ISSUE THREAD

**Issue by egoist** [nuxt/nuxt.js#323]
From this line https://github.com/nuxt/nuxt.js/blob/fbca3d7f78da1edb04bde21fddcc981f562f8fb4/lib/build.js#L148

It seems layouts can only be loaded from `srcDir/layouts`, is there any chance to add a `layoutDir` option in nuxt config?  My use case is that I want to put all `pages` in `srcDir` but put layouts elsewhere.

**Comment by Atinux** [comment]
Hi @egoist 

We don't support this since we want more convention than configuration.

What you can do it to keep the layout folder and import your layouts from there directly, so everyone who knows the doc of nuxt will know how to use your project :)
