### ISSUE TITLE
为什么generate之后放到nginx里js会失效.

### ISSUE THREAD

**Issue by cel533** [nuxt/nuxt.js#3230]
起初是引入的echart结果发现,dev完全没问题,但是generate之后无法生成chart图.
然后查问题发现是js失效?
连click这种简单事件都无法响应

**Comment by wilonjiang** [comment]
关于执行nuxt generate 生成的html静态页面，js不执行的问题原因在于page内容只在server render时执行，生成的html静态页面不会执行page里面的vue逻辑。
如果想要实现html静态页面中执行指定的js逻辑，可以参考这个方式去解决：
请将js逻辑放入layout布局vue文件中，在page中指定layout即可，layout中的vue内容在nuxt generate 后的html中会被执行

**Comment by wilonjiang** [comment]
If you want to execute your JavaScript logic in HTML, move it to layout, and declare it in page.
