### ISSUE TITLE
Require dependencies only for SSR bundle

### ISSUE THREAD

**Issue by Tzcodejs** [nuxt/nuxt.js#3232]
I followed FAQ to add `if (process.browser) {
  require('external_library')
}` and `build: {
    vendor: ['external_library']
  }` ,but it unwork. As the same time, the NPM advice me to install external_library also fail

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6918">#c6918</a>)</em></sub></div>

**Comment by benoitemile** [comment]
This would be amazing, we're having issues with that, for example: we're computing prices and dates SSR but we actually have to have polyfills for Intl and add Moment since hydration will be performed client side. Is there a way to have SSR only - static - component and no hydration on them ?

**Comment by Atinux** [comment]
@benoitemile Sadly it's not possible since Vue will not understand why there is a DOM which is not matched on client side :/

**Comment by benoitemile** [comment]
@Atinux I'm thinking a lot about this, I might go feature request it to vue-ssr but I think v-once in SSR context could be done SSR only so client doesn't have to hydrate big static markups that won't change (navigation for example)
