### ISSUE TITLE
Pass props to nuxt-child

### ISSUE THREAD

**Issue by mathieutu** [nuxt/nuxt.js#3234]
### What problem does this feature solve?

Hi,
I have nested routes. 
In the container I'm doing some actions to fetch api, write in store, create computed objects, etc.. 
I need them in the container, but I also need them in the children pages. 
It would be really cool to be able to pass props to children pages to avoid to re-do all this operations on all the nested pages.

Thanks!

### What does the proposed changes look like?

```html
// container
<div>
   <UserInfos :user="user">
   <Tabs>
   <nuxt-child :user="user"/>
</div>
```

```js
// nested
props: {
   user : {}
},
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6920">#c6920</a>)</em></sub></div>

**Comment by lucpotage** [comment]
If we could have nested layouts, it could solve your issue I suppose?

**Comment by mathieutu** [comment]
@lucpotage hem... Sorry I don't see the link with nested layout. 😕

**Comment by lucpotage** [comment]
@mathieutu OK, I thought that layout data was automatically passed to the pages depending on it but it's not the case (like a mixin). What about using a mixin and importing it in your pages?

**Comment by mathieutu** [comment]
Thank you guys!
