### ISSUE TITLE
lodash works perfectly at initial load, however when I refresh I get thiserror "_ is not defined"

### ISSUE THREAD

**Issue by Myolisi** [nuxt/nuxt.js#3235]
lodash works perfectly at initial load, however when I refresh I get thiserror "_ is not defined"

I added loadash as a plugin to my project, and used the _.debounce function which works perfectly when loading the page for the first time, but when i refresh I get this error "_ is not defined"

 submit:_.debounce(function(){
    	this.searchString = 'searching..................'
      if (this.searchValue !== '' ) {
        this.$router.push(`${this.searchValue}`)
        console.log(this.$nuxt.$route.path)
      }
    }, 3000)

**Comment by husayt** [comment]
Are you still having this problem?

Have you tried this?
https://nuxtjs.org/faq/webpack-plugins/

**Comment by Myolisi** [comment]
@husayt thanks for your concern. I decided not to use loadash for my application. But if I decide to use it in future I'll definitely try out your solution. Thanks again.
