### ISSUE TITLE
Pass options to serverMiddleware

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#3236]
### What problem does this feature solve?

Configuring a "generic" serverMiddleware is nearly impossible at the moment because an array of relative paths is the only way to pass them to nuxt.
(See [the code reference](https://github.com/nuxt/nuxt.js/blob/dev/lib/core/renderer.js#L264))

### What does the proposed changes look like?

It'd be great to do it similar to the `modules` system by allowing array with option objects:

(Modules example)

```
modules: [
    '@nuxtjs/pwa',
    ['@nuxtjs/axios', { baseURL: 'xxx' }]
  ]
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6924">#c6924</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @manniL 

Thanks for this feature request. Actually, what would be the use case to have a generic middleware?

**Comment by manniL** [comment]
Hey @Atinux 

for example, the [redirect-ssl](https://github.com/nuxt-community/redirect-ssl) middleware (which is also mentioned in the docs). Using it is currently possible by simply including the reference:

```
module.exports = {
  serverMiddleware: [
      'redirect-ssl'
  ]
}
```

But in case I want to configure it [as done here](https://github.com/nuxt-community/redirect-ssl/blob/master/examples/server.js), there is no way I'm aware of at the moment.

**Comment by Atinux** [comment]
Actually what you can do is this to give options:

```js
const redirectSSL = require('redirect-ssl')

module.exports = {
  serverMiddleware: [
    redirectSSL.create({ redirectPort: 8443 }))
  ]
}
```

The point is that you can use any `connect` middleware with Nuxt.js (not express), but most of them will not handle the options like Nuxt.js does :/

**Comment by manniL** [comment]
Ah, great! This should work as well. Thank you :relaxed: 

You are completely right, otherwise we would limit users to a small range of middlewares.

**Comment by Atinux** [comment]
I will close it, thank you for your help on Nuxt.js, I really appreciate it!

**Comment by manniL** [comment]
Thank you!
I'm happy I can contribute to this great project :pray: :heart:
