### ISSUE TITLE
Webpack keeps rebuilding

### ISSUE THREAD

**Issue by egoist** [nuxt/nuxt.js#324]
```bash

Build completed in 0.143s

webpack built e3c5f5e0d999e9654d74 in 143ms
webpack building...

Build completed in 0.128s

webpack built e3c5f5e0d999e9654d74 in 127ms
webpack building...

Build completed in 0.141s

webpack built e3c5f5e0d999e9654d74 in 142ms
webpack building...

Build completed in 0.131s

webpack built e3c5f5e0d999e9654d74 in 132ms
webpack building...

Build completed in 0.137s

webpack built e3c5f5e0d999e9654d74 in 137ms
webpack building...

Build completed in 0.134s

webpack built e3c5f5e0d999e9654d74 in 135ms
```

Maybe should ignore generated files from watcher?

**Comment by uptownhr** [comment]
how is your setup like? This does not occur on my setup.

**Comment by uptownhr** [comment]
However, on my setup, I'm using express and using nuxt as a middleware. Where I have api routes on express. Would love to hear some suggestions on avoiding a complete rebuild on webpack whenever I make server related changes. On my current project, it is taking 13 seconds to rebuild everytime I make changes on express. @alexchopin @Atinux

**Comment by nijikokun** [comment]
I'm seeing this as well, I'm using adonuxt

**Comment by nijikokun** [comment]
After some digging I have reduced the scope of the issue to the `webpack-dev-middleware` portion  of `createWebpackMiddleware`

**Comment by octref** [comment]
This happens if you follow "Starting from Scratch" here: https://nuxtjs.org/guide/installation.

Which is to have only a `package.json` and a `pages/index.vue`.

**Comment by zweizeichen** [comment]
Also happens when you use the starter package.

**Comment by aprilandjan** [comment]
The  rebuilding messages are annoying and confusing, hope this can be fixed

**Comment by LFra** [comment]
I have the same problem when using the starter template

**Comment by cschweda** [comment]
The fact that the webpack.configs for nuxt are essentially hidden makes debugging stuff like this very difficult. I see this, too, with the starter package. Frankly, the difficulty of accessing the full webpack.config(s) is the only thing preventing me from diving deeper into Nuxt.

What about adding the possibility of adding an actual webpack.config to the src files -- which would then be merged back into the nuxt configs? 

The more I work with Vue, the more I realize how important it is (for me, at least) to have full control over my webpack builds.

Thoughts?

**Comment by uptownhr** [comment]
@Atinux @alexchopin i thought this was a hoax because I was not experiencing it but just tried using the express starter and it does occur. I'm lost because, I've tried copying over my exact configuration one by one and I still don't understand why I'm not experiencing the same issue on my project. 

I'm a bit worried that this issue may creep up on my project as well. Any insights here?

**Comment by uptownhr** [comment]
So I figured out what the difference was. I run my projects in docker containers and the multiple rebuild issue doesn't occur when running inside docker. I use the native node:7.7.0 docker image to run. 

Now, I really don't know why this would help resolve this issue as I'm also running ubuntu on my desktop and it also experienced the same issue. I initially thought it might have been the "fsevents" module but ubuntu also does not use fsevents.

**Comment by uptownhr** [comment]
so i'm really lost now. I've rebuilt my project atleast a 100 times now and it appears it depends on the some packages being there or not being there. Here's my package.json. Can someone see if using my package.json resolves their problem? 

```
{
  "name": "admin",
  "version": "1.0.0",
  "description": "bambee admin",
  "dependencies": {
    "axios": "^0.15.3",
    "bcrypt-nodejs": "^0.0.3",
    "bluebird": "^3.4.7",
    "body-parser": "latest",
    "bulma": "^0.3.1",
    "connect-redis": "^3.2.0",
    "crypto": "^0.0.3",
    "express": "^4.14.1",
    "express-session": "^1.15.0",
    "filepicker-js": "^2.4.18",
    "moment": "^2.17.1",
    "mongoose": "^4.8.3",
    "raven": "^1.1.2",
    "raven-js": "^3.11.0"
  },
  "devDependencies": {
    "node-sass": "^4.2.0",
    "nodemon": "^1.11.0",
    "nuxt": "^0.9.9",
    "sass-loader": "^4.1.1"
  },
  "scripts": {
    "dev": "NODE_ENV=dev nodemon --ignore store/ server.js",
    "development-build": "NODE_ENV=development nuxt build",
    "development-start": "NODE_ENV=development node server.js",
    "staging-build": "NODE_ENV=staging nuxt build",
    "staging-start": "NODE_ENV=staging node server.js",
    "production-build": "NODE_ENV=production nuxt build",
    "production-start": "NODE_ENV=production node server.js",
    "build": "nuxt build",
    "start": "node server.js",
    "generate": "nuxt generate"
  }
}
```

**Comment by nijikokun** [comment]
It has to do with an update to some webpack modules :/

Which inside of `nuxt` regardless of version has a `^` symbol infront of the the packages in `package.json` so you'll get it regardless if you swap between `nuxt` versions.

**Comment by Atinux** [comment]
It seems that with the last version it stop rebuilding but the build process in dev is slower.

The issue related to it: #436

**Comment by Atinux** [comment]
Dammit! It started again.

Related issue to Webpack: https://github.com/webpack/watchpack/issues/25

**Comment by Atinux** [comment]
Finally! This issue can disappear and never come back 😄 

See the last release: https://github.com/nuxt/nuxt.js/releases/tag/v0.10.1

**Comment by uptownhr** [comment]
Hurray!

**Comment by mamboer** [comment]
Struggling for a whole day before i'm here~ Thanks you guys.
But in fact the ugly issue will appear again if you write files programmatically into the `srcDir` of `nuxt` right before initializing it. 

```
const options = {
    srcDir: '...'
}

writeFilesToSrcDir(options.srcDir) // This will trigger the issue

const nuxt = new Nuxt(options)
nuxt.build()
.then(() => {
  // We can use nuxt.render(req, res) or nuxt.renderRoute(route, context)
})
```

In this case, we should also hack the 'utimes' for those files.

**Comment by lemonpigpig** [comment]
@uptownhr hi can u give the project link i want to study to solve the run dev takes too much time everytime to update the nuxt.config.js

**Comment by egoist** [comment]
LOL here's a new fashion way to work around it:

```js
module.exports = class TimeFixPlugin {
  constructor(timefix = 11000) {
    this.timefix = timefix
  }

  apply(compiler) {
    compiler.plugin('watch-run', (watching, callback) => {
      watching.startTime += this.timefix
      callback()
    })

    compiler.plugin('done', stats => {
      stats.startTime -= this.timefix
    })
  }
}
```

Currently using it in [Poi](https://github.com/egoist/poi/blob/3e93c88c520db2d20c25647415e6ae0d3de61145/packages/poi/lib/webpack/timefix-plugin.js#L1-L16) 😂

**Comment by Atinux** [comment]
Will add it to Nuxt.js, thank you @egoist :)
