### ISSUE TITLE
HMR for vuex store

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#325]
I thought using modules mode will automatically add in the HMR code but found out that it is not. 

https://vuex.vuejs.org/en/hot-reload.html

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c276">#c276</a>)</em></sub></div>

**Comment by uptownhr** [comment]
any chance this can be included in the 1.0 releåse?

**Comment by uptownhr** [comment]
```
if (module.hot) {
  module.hot.accept([
    './modules'
  ], () => {
    store.hotUpdate({
      modules: require('./modules')
    })
  })
}
```
is what i used in another project of mine. Not sure how difficult it is to inject this into the store template.

**Comment by Atinux** [comment]
It will be directly in this file @uptownhr https://github.com/nuxt/nuxt.js/blob/master/lib/app/store.js

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HMR for store](https://trello.com/c/VGMFHtfd/2-hmr-for-store)

**Comment by uptownhr** [comment]
What version of nuxt was this from?

**Comment by manniL** [comment]
Not sure when it got implemented exactly, but works in `nuxt v1.4.2` and in `nuxt-edge`

**Comment by uptownhr** [comment]
Interesting. I noticed it wasn't working on my last project. Maybe it
wasn't fully caught up to 1.4.2 but I thought it was.is there anything
special you have to do or not do for her to work?

**Comment by manniL** [comment]
@uptownhr Don't think so. When testing the feature I used the store in `modules` mode and added a new property to the state :thinking:

**Comment by uptownhr** [comment]
@manniL I just created a sample project off of, `vue init nuxt-community/starter-template <project-name>` and created a simple store that looks like,

```
export const state = () => ({
  hmr: true
})


export const getters = {
  hmr (state) {
    return state.hmr
  }
}
```

I can confirm that on my machine the HMR does not work.

This is what I see in my browser console.

```
VM429 vendor.js:19773 Ignored an update to unaccepted module ./store/index.js -> ./store recursive ^\.\/(?!-)[^.]+\.(js)$ -> ./.nuxt/store.js -> ./.nuxt/index.js -> ./.nuxt/client.js -> 0
onUnaccepted @ VM429 vendor.js:19773
hotApply @ VM428 manifest.js:468
cb @ VM429 vendor.js:19817
(anonymous) @ VM429 vendor.js:19833
Promise.then (async)
check @ VM429 vendor.js:19832
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ VM429 vendor.js:19793
processMessage @ VM429 vendor.js:19716
handleMessage @ VM429 vendor.js:19584
handleMessage @ VM429 vendor.js:19547
VM429 vendor.js:19846 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.
logUpdates @ VM429 vendor.js:19846
applyCallback @ VM429 vendor.js:19814
(anonymous) @ VM429 vendor.js:19822
Promise.then (async)
cb @ VM429 vendor.js:19821
(anonymous) @ VM429 vendor.js:19833
Promise.then (async)
check @ VM429 vendor.js:19832
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ VM429 vendor.js:19793
processMessage @ VM429 vendor.js:19716
handleMessage @ VM429 vendor.js:19584
handleMessage @ VM429 vendor.js:19547
VM429 vendor.js:19854 [HMR]  - ./store/index.js
(anonymous) @ VM429 vendor.js:19854
logUpdates @ VM429 vendor.js:19853
applyCallback @ VM429 vendor.js:19814
(anonymous) @ VM429 vendor.js:19822
Promise.then (async)
cb @ VM429 vendor.js:19821
(anonymous) @ VM429 vendor.js:19833
Promise.then (async)
check @ VM429 vendor.js:19832
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ VM429 vendor.js:19793
processMessage @ VM429 vendor.js:19716
handleMessage @ VM429 vendor.js:19584
handleMessage @ VM429 vendor.js:19547
VM429 vendor.js:19893 [HMR] Reloading page
```

**Comment by manniL** [comment]
@uptownhr I see the point. Will open up a a PR soon, but I’m unsure if it’ll make it to 2.0.

**Comment by manniL** [comment]
In Nuxt 2, store HMR works as far as possible.

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/50153407-3d7aa380-02be-11e9-979f-ceec518d87a3.png)

HMR could be improved as a full reload of the page is still necessary to update the module

**Comment by manniL** [comment]
How to reproduce:

Repo: https://github.com/manniL/nuxt-no-store-module-hmr/tree/master/
CSB: https://codesandbox.io/s/github/manniL/nuxt-no-store-module-hmr/tree/master/

1. Launch with `yarn dev`
2. Uncomment 2nd getter
3. see message from comment before

**Comment by manniL** [comment]
Possible strategy to implement: https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/state/modules/index.js
