### ISSUE TITLE
How to set rootDir as ~

### ISSUE THREAD

**Issue by sudhir600** [nuxt/nuxt.js#3250]
I just install nuxt starter template. it's working fine. I saw somewhere that file is being imported like 
`import store from ~store`

i don't know why **`~`** need to you. is it resolving root directory? if yes then how and where i can set this setting in my template? i tried the same but i am getting error on console.

<pre>
ERROR  Failed to compile with 1 errors
This dependency was not found:
`* ~store in ./plugins/i18n.js`
To install it, you can run: npm install --save ~store

</pre>

**Comment by sudhir600** [comment]
why this issue goes closed automacticaly by cmty? strange

@clarkdo

**Comment by clarkdo** [comment]
@sudhir600 
`~store` was webpack alias before, it has been removed since `https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc3`, please use `~/store`.

I will check the starter template.

BTW: https://nuxtjs.org/guide/directory-structure#aliases
`~` is for srcDir.
`~~` is for rootDir

**Comment by sudhir600** [comment]
Thanks @clarkdo  
But I am still confused that how ~ resolve the path. where is this setting (i mean in which file) ?

**Comment by clarkdo** [comment]
@sudhir600 https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/base.js#L88-L103
