### ISSUE TITLE
Symlinked node_modules are compiled with Babel

### ISSUE THREAD

**Issue by antoinerey** [nuxt/nuxt.js#3253]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/antoinerey/vue-component](https://github.com/antoinerey/vue-component)

### Steps to reproduce

1. Clone the component https://github.com/antoinerey/vue-component
2. Clone the app https://github.com/antoinerey/vue-component-app
3. Link the component `cd vue-component && npm link`
4. Fetch the linked component from the app `cd vue-component-app && npm link vue-component`
5. Start the application `npm run dev`

### What is expected ?

The build should pass without any warning and the app should run.

### What is actually happening?

The build emits some warning about the `default export` not being found. And the application crashes.

### Additional comments?

I'm trying to develop and publish a component to NPM. While testing it, I wanted to ensure it was working into a Nuxt application.

---

Note that if I install the exact same package from NPM, it works as expected. So I'm thinking this issue is related to symlinks and how Babel transformations are applied.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6947">#c6947</a>)</em></sub></div>

**Comment by sh** [comment]
I've had the same issue, solved it by setting `config.resolve.symlinks = false` in the `nuxt.config.js`

```js
// extend webpack config
extend(config, { isDev, isClient }) {
  // do not resolve symlinks
  if (isDev) config.resolve.symlinks = false
})
```

**Comment by XanderKon** [comment]
Thanks! Spent a lot of time for debug this.

I had try just import module in nuxt page in es6-style from a local module in node_modules dir:

`import { wordToNum, numToWord } from 'webpack-numbers'`

and got errors that export is not defined
