### ISSUE TITLE
support .ts/.tsx files in pages/components

### ISSUE THREAD

**Issue by alidcastano** [nuxt/nuxt.js#3256]
### What problem does this feature solve?

better typescript support

### What does the proposed changes look like?

similar to https://github.com/nuxt/nuxt.js/pull/2353 to js/jsx support

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6950">#c6950</a>)</em></sub></div>

**Comment by alidcastano** [comment]
@clarkdo You were involved in above PR. Do you think this feature would also be possible?

**Comment by clarkdo** [comment]
Yes, I think it can be added into the backlog.

I'm a little busy with some personal relocation stuff, I will work on it after personal affairs get done.

And we also welcome any contributions!

/cc @Atinux @pi0

**Comment by marcelbraun1985** [comment]
Hey, that would be nice. I'am trying to get this to work since days. The decorator is available but the files don't get loaded.

```
import {
    Component,
    Vue,

} from "nuxt-property-decorator"

@Component({
    template: '<h1>I would like to get this working :)</h1>'
})
export default class extends Vue {

}
```

Is there a workaround?

Greetz
Marcel

**Comment by bichikim** [comment]
I have the same issue
version nuxt-edge@2.0.0-25417903.a02c445
```
Module parse failed: Unexpected character '@' (18:0)
You may need an appropriate loader to handle this file type.
| import AppLogo from '@/components/AppLogo.vue'
| import {Component, Vue} from 'nuxt-property-decorator'
| @Component({
|   components: {
|     AppLogo,

 @ ./src/pages/index.vue?vue&type=script&lang=ts 1:0-119 1:135-138 1:140-256 1:140-256
 @ ./src/pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```
ts module
```
module.exports = function() {
  this.nuxt.options.extensions.push('ts')

  this.extendBuild((config) => {
    const tsLoader = {
      loader: 'ts-loader',
      options: {
        appendTsSuffixTo: [/\.vue$/],
        transpileOnly: true,
      },
      exclude: [
        /vendor/,
        /\.nuxt/,
      ],
    }
    config.module.rules.push({
      test: /((client|server)\.js)|(\.tsx?)$/,
      ...tsLoader,
    })
    for(let rule of config.module.rules){
      if(rule.loader === 'vue-loader'){
        if(!rule.options.loaders){
          rule.options.loaders = {}
        }
        rule.options.loaders.ts = tsLoader
      }
    }
    if(config.resolve.extensions.indexOf('.ts') < 0){
      config.resolve.extensions.push('.ts')
    }
  })
}
```
It would be nice if nuxt.config.js has typescript: true

**Comment by wagerfield** [comment]
Hey everyone, I created a `nuxt-typescript` module on NPM to try and take the pain out of setting up TypeScript and TSLint:

https://www.npmjs.com/package/nuxt-typescript

All you need to do is add `nuxt-typescript` to the Nuxt config:

```js
// nuxt.config.js
module.exports = {
  modules: ["nuxt-typescript"]
}
```

...and then create a `tsconfig.json` file with the settings outlined in the README.

---

I ported the implementation from [`@vue/cli-plugin-typescript`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript) by @yyx990803 and @kvpt.

This implementation gives the added benefit of faster compilation times by forking the type checking and linting (if you're using TSLint) using `fork-ts-checker-webpack-plugin`. It also uses `thread-loader` for faster production builds.

What I have not been able to get working is:

* Support for `lang="tsx"` in `.vue` SFCs (I get compiler errors)
* Support for page components with `.ts` or `.tsx` file extensions
  - Nuxt does not pick these up even though I have [added these extensions to Nuxt's options](https://github.com/wagerfield/nuxt-typescript/blob/master/index.js#L65)
  - I noticed that Nuxt doesn't pick up `.jsx` file extensions in the pages directory either

For the second issue I imagine this is a relatively simple fix that @Atinux or @clarkdo could take a look at?

For the `lang="tsx"` compilation errors, I'm not sure who is best equipped to help—but the relevant lines in the source code are:

- https://github.com/wagerfield/nuxt-typescript/blob/master/index.js#L74
- https://github.com/wagerfield/nuxt-typescript/blob/master/index.js#L105

I configured everything as per the `ts-laoder` docs, but it doesn't work 😞 

Any help to get these remaining issues sorted would be very much appreciated!

Thanks in advance everyone 😃

**Comment by clarkdo** [comment]
@wagerfield Great job! Thank you so much, I will look into it when I'm available.

**Comment by clarkdo** [comment]
For tsx loader, I just tried you example at https://github.com/wagerfield/nuxt-typescript/tree/master/example, it works fine 😄, I didn't find any errors.
 
![image](https://user-images.githubusercontent.com/4312154/40605658-fdcee920-625a-11e8-8222-c7f214c58e53.png)

![image](https://user-images.githubusercontent.com/4312154/40605408-33d67ffc-625a-11e8-9def-cb1a786c1659.png)

**Comment by wagerfield** [comment]
@clarkdo it's the `lang="tsx"` component that I cannot get to work, so is currently commented out in the example. To test that it works, uncomment these lines 5, 17 and 25 in `pages/index.vue`...then I think you will see what I mean.

**Comment by wagerfield** [comment]
After reading the Medium article about Nuxt v2, I thought I would see if upgrading the example to `nuxt-edge` would fix this issue.

To do so, I had to upgrade `ts-loader` to 4.x to work with Webpack 4—it's so much faster at recompiling the TS and the new `webpackbar` is much better for getting build feedback in the console—awesome work @pi0 and co!

However, I am still get the same compiler error—but with `nuxt-edge` I get a bit more of a stack trace...not that it really helped me out anymore with `.vue` SFCs, `lang="tsx"` ...but here it is anyway for reference:

![screenshot 2018-05-28 12 43 23](https://user-images.githubusercontent.com/412747/40613029-bad980ca-6274-11e8-8abc-3438895990ce.png)

**Comment by clarkdo** [comment]
@wagerfield You can use `yarn build` to see more error details, it seemed that `ts-loader` is still transpiling the `jsx` although `js: 'preserve'` has been specified.

**Comment by clarkdo** [comment]
@wagerfield I opened a pr trying to solve the issue, you can verify it.

**Comment by wagerfield** [comment]
Merged, updated and published to NPM `nuxt-typescript@0.9.0` thanks a million @clarkdo  🎉 

All that remains to be done is have Nuxt compile `.ts` and `.tsx` file in the `pages` directory and I'll publish `1.0.0` 😄

**Comment by wagerfield** [comment]
Happy to take a look at this @clarkdo if you're busy—would be great if you could point me at where Nuxt watches for changes in the `pages` directory so I can figure out how to add the `.ts` and `.tsx` extensions.

**Comment by clarkdo** [comment]
@wagerfield Sorry for the late reply, here is the watchers https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/builder.js#L582

**Comment by wagerfield** [comment]
Thanks @clarkdo it looks like this actually might be the issue:

https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/builder.js#L259

**Comment by clarkdo** [comment]
@wagerfield 
Oh, you mean where the `pages` routes got created, sorry for the misunderstanding.

**Comment by wagerfield** [comment]
...in fact there are a few places where the pages file extensions are hard coded in regex's like in `common/utils/createRoutes`:

https://github.com/nuxt/nuxt.js/blob/dev/lib/common/utils.js#L253

If I create a PR that adds support for `.jsx`, `.ts` and `.tsx` files would that be accepted?

Or should these extensions be provided via a Nuxt config option perhaps?

Is there any reason you don't support `.jsx` out of the box for page components?

**Comment by wagerfield** [comment]
@clarkdo in addition to my message above and in response to your question—yes, what I would like to be able to do is use `.vue`, `.js`, `.jsx` files for page components and also add `.ts` and `.tsx` when using TypeScript.

**Comment by clarkdo** [comment]
My personal opinion is that a new configuration should be better.

And if we create this config, the `vue and js` can be default values and putting `ts and tsx` into `nuxt-typescript` should be more appropriate.

BTW, if we add this config, we should also consider changes in related codes (such as: watchers).

/cc @Atinux @pi0

**Comment by wagerfield** [comment]
I agree that this should be configurable via the the module API so that packages like `nuxt-typescript` can add extensions.

However I think that this can be achieved by using the `this.nuxt.options.extensions` that are currently being set by `nuxt-typescript` here:

https://github.com/wagerfield/nuxt-typescript/blob/master/index.js#L65

It is my understanding that these extensions allow for `.tsx?` files to be used in the `store` for example—so it makes sense to me that this logic should be replicated for `pages` and `layouts`.

As mentioned above, I think that `.jsx` should be added out of the box by default since you can import `.jsx` components—so it makes sense that `layouts` and `pages` should work too IMO.

**Comment by clarkdo** [comment]
@wagerfield Agree 😸

**Comment by Atinux** [comment]
This is an amazing work @wagerfield ! Nice to see more and more support for TS into Nuxt community!

**Comment by hartmut-co-uk** [comment]
looks just great, working on a project with nuxt & ts - with a custom ts setup put together from various nuxt ts starter templates. All working but @wagerfield's approach via module looks so nice, clean and promising! ✨ 
Will see to experiment/migrate. Looking forward to nuxt2, great work everyone! 🙇

**Comment by dkushner** [comment]
@galvez was this issue actually closed satisfactorily? I'm currently on nuxt-edge (but this also affects nuxt) and still unable to use TSX-based components for pages or layouts.

**Comment by chanlito** [comment]
@galvez would you mind explain why is this issue closed?
