### ISSUE TITLE
A refresh bug about nuxt and iframe

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#3258]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[nuxt-test.zip](https://github.com/nuxt/nuxt.js/files/1936662/nuxt-test.zip)

### Steps to reproduce

I found a very strange bug
If I visit the page in the iframe
When you refresh again, the server will be stuck
The installation code is as follows

```shell
cd nuxt-test
npm i
npm run dev
```
However, just put the 143 line comment in /page/index.vue and restart it will not be stuck.

```js
       this.addClickTab('/test-4')
```

How to solve this flush stuck bug

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6953">#c6953</a>)</em></sub></div>

**Comment by HadiChen** [comment]
I also encountered this problem and I look forward to a quick solution

**Comment by tttracy** [comment]
I also encountered this problem and I look forward to a quick solution

**Comment by 1065719532** [comment]
I also encountered this problem and I look forward to a quick solution

**Comment by yeziZ** [comment]
I also encountered this problem and I look forward to a quick solution

**Comment by z3690629** [comment]
me too!!!
and I look forward to a quick solution

**Comment by AllenZho** [comment]
bug?

**Comment by HadiChen** [comment]
I found this problem only in the development mode, but it is no problem in the product mode.

**Comment by chenguanghui16** [comment]
我也遇到了这个问题，期待有一个快速解决方案

**Comment by yuchonghua** [comment]
Do you know how to solve this problem?
/ping @pi0 @Atinux

**Comment by yuchonghua** [comment]
Can you give a repair proposal?
/ping @pi0 @Atinux

**Comment by HadiChen** [comment]
Looking forward to a solution, thank you
/ping @pi0 @Atinux

**Comment by Caiyi-LI** [comment]
Looking forward to a solution, thank you
/ping @pi0 @Atinux

**Comment by yeziZ** [comment]
What is the reason for this? Only the development model has

**Comment by Atinux** [comment]
I did not find any bug trying your `.zip`, even while reloading the server.

Also, why using an iframe when you can require directly the component?

**Comment by yuchonghua** [comment]
Visit card owner
@Atinux

**Comment by yuchonghua** [comment]
Did you find new progress recently?
@Atinux

**Comment by yuchonghua** [comment]
It may be that the number of __webpack_hmr cannot exceed 5, how can this problem be solved?
![image](https://user-images.githubusercontent.com/17898715/39683286-3e00da14-51e7-11e8-9046-48fb8eee9bdf.png)

**Comment by HadiChen** [comment]
Why is the webpack_hmr used by Nuxt based on Server-Sent Events and webpack version provided by vue is websocket?

>* WebSocket is more powerful than SSE. Websocket establishes bi-directional real-time communication between client and server. SSE only supports one-way real-time communication from the server to the client.
>* WebSocket supports more browsers, IE/ Edge does not support SSE at all
>* The browser-side of SSE implements built-in disconnection reconnection and message tracking functions. WebSocket can also be implemented, but it is not within protocol design and needs to be handled manually.
>* SSE is simple to implement, completely reuses the existing HTTP protocol, and WebSocket is a set of standards that is relatively independent of HTTP. Cross-platform implementation is more complex.

### However, SSE is limited by 5 to 6 browser sockets

I am very much looking forward to nuxt's webpack_hmr is based on WebSocket

/ping @Atinux @pi0 @clarkdo

**Comment by yeziZ** [comment]
Is this a problem with [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/issues/304)?

**Comment by zengfanyao** [comment]
Nothing below? Still solved? I also look forward to knowing the result
/ping @Atinux @pi0 @clarkdo @HadiChen @yeziZ @yuchonghua

**Comment by Atinux** [comment]
Actually you should not use iframe

**Comment by yuchonghua** [comment]
In fact, I was developing a multi-window window for tabs. This background, each window is independent, or it may be a page under different domain names. Similar to the browser, each page may have refresh function.
@Atinux
