### ISSUE TITLE
Access route path and params in nuxtServerInit

### ISSUE THREAD

**Issue by agencewebcom** [nuxt/nuxt.js#3259]
Hello,
How can I access the current route path and params from nuxtServerInit function in my store index.js ?
I need it because I have to authenticate my app by his id wich is in the url

**Comment by bingtimren** [comment]
Accept a second argument. The first argument is the store context, with which you can commit mutation. The second argument is the page context. From the second context, e.g. pContext.route you can find the full path and parameters, etc.

nuxtServerInit(sContext, pContext)
