### ISSUE TITLE
How to authorize first request with bearer token?

### ISSUE THREAD

**Issue by JiriChara** [nuxt/nuxt.js#326]
I am storing user's jwt token in the localStorage and I have added an interceptor to `axios` to attach the correct bearer token to the request.

```js
import axios from 'axios';

import store from '~store';
import config from '../config';

const methods = ['get', 'post', 'put', 'patch', 'delete'];

function formatUrl(path) {
  const adjustedPath = /^\/.*$/.test(path) ? path : `/${path}`;
  const inBrowser = typeof window !== 'undefined';
  const protocol = config.isProduction ? 'https' : 'http';

  if (!inBrowser) {
    return `${protocol}://${config.apiHost}:${config.apiPort}${adjustedPath}`;
  }

  return `/api${adjustedPath}`;
}

axios.interceptors.request.use((cfg) => {
  try {
    // const token = store.state.userSession.token;
    const token = localStorage.getItem('token');

    if (token) {
      cfg.headers.common.Authorization = `Bearer ${token}`;
    }
  } catch (ignore) {
    // ignore
  }

  return cfg;
}, error => Promise.reject(error));

class ApiClient {
  constructor() {
    methods.forEach((method) => {
      this[method] = (path, ...args) => axios[method](formatUrl(path), ...args);
    });
  }
}

const client = new ApiClient();

export default client;
```

This works fine when a certain page is rendered on the client, but it doesn't work on the initial request, because server doesn't have access to `localStorage` (of course) :-). Is there a way to get the token before `fetch` method of some page is trying to get some data?

**Comment by Atinux** [comment]
You can use the cookies to access them on server-side (and client-side).

In your `nuxtServerInit` action, you can get the cookie in `req.headers.cookie` and then extract the token to set it in the store.

**Comment by JiriChara** [comment]
Thanks @Atinux! Yes, I have found out that I can use cookies, but it's kind of a limitation in my opinion. There are several reasons to store jwt tokens just in local storage rather than cookies and the local storage. I understand that `localStorage` is not available in node environment, but maybe it would make sense to pass as much as possible to server, so programmer could use things like `window`, `document` `localStorage` etc at least in the middleware function. If your target audience are creators of simple blog pages and writers of documentation pages, then you are fine, but if you want to bean alternative to vue-cli than you should offer more :angel:
**However thanks for doing Nuxt, it's a great framework!**
