### ISSUE TITLE
Exception crashes the whole application (solved)

### ISSUE THREAD

**Issue by KindWizzard** [nuxt/nuxt.js#3263]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://jsfiddle.net/tco1q3hs/](https://jsfiddle.net/tco1q3hs/)

### Steps to reproduce

I'v made simple component that looks like this:

export default {
	async created() {
			setTimeout(() => {
				throw Error(123);
			}, 5000);
  	}
};

And this component crashes nuxt application. Is it possible to catch this types of error?

### What is expected ?

The application continues to work

### What is actually happening?

The application crashes

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6964">#c6964</a>)</em></sub></div>

**Comment by buremba** [comment]
@KindWizzard Do you mind explaining how you solved the problem?

**Comment by KindWizzard** [comment]
@buremba Sure. It's all about handling the errors in Node.js, not the Nuxt. You should put this code in the place, where you create Nuxt instance.
```
process.on('uncaughtException', function(error) {

});
```
But there is a strong opinion, that it's not a good practice to handle errors in this way)

**Comment by manniL** [comment]
Besides the usual `try/catch` you could also use the Vue error handler or error boundaries to solve this
