### ISSUE TITLE
404 not found, fresh installation

### ISSUE THREAD

**Issue by adibfirman** [nuxt/nuxt.js#3266]
Hello, i just fresh installation nuxt, why i have of not found file

![image](https://user-images.githubusercontent.com/24794196/39239307-a82b430c-48aa-11e8-84e8-152ad53b368c.png)

**Comment by Extarys** [comment]
Did you use a template? Which one? How did you start your app? `npm run dev` ?

Did you install or modify something else afterward?

Thanks
