### ISSUE TITLE
Keep-alive with nuxt-child only not working

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#3267]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://glitch.com/edit/#!/plausible-shingle?path=pages/ka2/index.vue:8:9](https://glitch.com/edit/#!/plausible-shingle?path=pages/ka2/index.vue:8:9)

### Steps to reproduce

I want some of the pages to have keep-alive ( like 1 or 2). So i tried to use it with nuxt-child.
https://glitch.com/edit/#!/plausible-shingle?path=pages/ka2/index.vue:8:9
https://plausible-shingle.glitch.me/ka2

E.g. <nuxt-child keep-alive/>
And i see that activated\deactivated got triggered fine for that child page. But the child page still got recreated every time.
But if i also set keep-alive for the core <nuxt keep-alive/> it will work as expected initially. 

https://glitch.com/edit/#!/plausible-shingle?path=pages/ka/index.vue:8:9
https://plausible-shingle.glitch.me/ka

So it doesnt work with nuxt-child, only with nuxt.

PS same behavior with nuxt-edge

### What is expected ?

page in nuxt-child not recreated

### What is actually happening?

page in nuxt-child got recreated every time

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6970">#c6970</a>)</em></sub></div>

**Comment by ISCLOUDX** [comment]
I too

**Comment by SnirShechter** [comment]
Same here

**Comment by gotoin** [comment]
me too, why not solve this problem, and keep-alive is wrong

**Comment by lujie-hybrid** [comment]
<nuxt keep-alive> and <nuxt :keepAlive="true"/> are both not useful, keep-alive not support

**Comment by lujie-hybrid** [comment]
<nuxt keep-alive /> and <nuxt :keepAlive /> are both not useful

**Comment by lujie-hybrid** [comment]
nuxt is also not useful

**Comment by lxx2013** [comment]
me too.

I store some important datas to `Vuex` temporarily. This can solve some problem but it's so inconvenient.

Hope the bug about `keep-alive` to be solved as quick as possible

**Comment by lxx2013** [comment]
Actually when I add the `keep-alive` to `<nuxt-child>`, and click this `child-page` , I found that
**the `created` & `mounted` will not execute , but the `data` will refresh**
When using `locaStorage.getItem` , this problem is so obvious. 
example code:
```vue
<template>
  <div>
    <h1>
      {{like? 'Like! [:-)] ':"Do not like [-_-]"}}
    </h1>
    <a @click="toggle">toggle</a>
  </div>
</template>

<script>
export default {
  data ({ req }) {
    return {
      name: req ? 'server' : 'client',
      like: false
    }
  },
  mounted(){
    this.like = localStorage.getItem('like') || false
  },
  methods:{
    toggle(){
      this.like  = ! this.like 
      localStorage.setItem('like',this.like )
    }
    
  }
}
</script>
```
when click `toggle` and then switch the `nuxt-child` page , It comes to a bad data like 
```js
console.log(this.data) //false
console.log(localStorage.getItem('like')) // true
```

**Comment by zhanyouwei** [comment]
> Actually when I add the `keep-alive` to `<nuxt-child>`, and click this `child-page` , I found that
> **the `created` & `mounted` will not execute , but the `data` will refresh**
> When using `locaStorage.getItem` , this problem is so obvious.
> example code:
> 
> ```
> <template>
>   <div>
>     <h1>
>       {{like? 'Like! [:-)] ':"Do not like [-_-]"}}
>     </h1>
>     <a @click="toggle">toggle</a>
>   </div>
> </template>
> 
> <script>
> export default {
>   data ({ req }) {
>     return {
>       name: req ? 'server' : 'client',
>       like: false
>     }
>   },
>   mounted(){
>     this.like = localStorage.getItem('like') || false
>   },
>   methods:{
>     toggle(){
>       this.like  = ! this.like 
>       localStorage.setItem('like',this.like )
>     }
>     
>   }
> }
> </script>
> ```
> 
> when click `toggle` and then switch the `nuxt-child` page , It comes to a bad data like
> 
> ```js
> console.log(this.data) //false
> console.log(localStorage.getItem('like')) // true
> ```

me too

**Comment by ousiri** [comment]
@aldarund the issue is caused by lacking a top-level `<keep-alive/>`. When changed to another route, the route-component is destroyed, along with the `<keep-alive/>`. You can add `pages/index.vue ` providing a `<nuxt-child/>` with `keep-alive` like this demo: https://github.com/ousiri/nuxt-keep-alive-test

But there is a remaining question `data` will refresh every change

**Comment by ousiri** [comment]
@lxx2013 @zhanyouwei 
I found the code that causes the problem. Looks like it is designed that way to update the asyncData when changed to a different route.

https://github.com/nuxt/nuxt.js/blob/055e99a21b0c2f681025c5adc90fef19bed76b96/lib/app/client.js#L455
