### ISSUE TITLE
Deploy AWS Error: Nuxt + Vue error load image and font-awesome.css

### ISSUE THREAD

**Issue by quangnguyennq** [nuxt/nuxt.js#3268]
Hello, My project using css and image of Admin-lte template in nodejs . I run local no problem but when deploy to AWS using nodejs 8.x load image and font-awesome.css error: not found. Help me :)
![e1](https://user-images.githubusercontent.com/11884494/39260425-aa679a2e-48e3-11e8-8390-35a79c57d7dc.png)

File: nuxt.config.js
> const webpack = require("webpack");
module.exports = {
  mode: 'universal',
  /*
  ** Headers of the page
  */
  head: {
    title: "spa_awslambda_samples",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { hid: "description", name: "description", content: "Nuxt.js project" }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: 'favicon.ico' }      
    ],
    // Load all external common js
    script: []
  },
  /*
  ** Customize the progress bar color
  */
  loading: { color: "#3B8070" },
  /*
  ** Custom css global
  */
  css: [
    { src: "bootstrap/dist/css/bootstrap.min.css", lang: "scss" },
    { src: "admin-lte/dist/css/AdminLTE.min.css", lang: "scss" },
    { src: "admin-lte/dist/css/skins/_all-skins.min.css", lang: "scss" },
    { src: "font-awesome/css/font-awesome.min.css", lang: "scss" }
  ],
  srcDir: "src_app/",
  router: {
    base: "/dev" // change base url to match with api gateway url generated
  },
  render: {
    gzip: false, // disable gzip
    bundleRenderer: {
      shouldPreload: (file, type) => {
        return ['script', 'style', 'font'].includes(type)
      }
    }
  },
  /*
  ** Custom plugin global
  */
  plugins: [
    // ssr: false to only include it on client-side
  ],
  /*
  ** Build configuration
  */
  build: {
    extractCSS: true,
    // install jquery plugin
    plugins: [
      new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery"
      })
    ],
    /*
    ** Run ESLint on save
    */
    vendor: ["axios", "chart.js", "admin-lte"],
    extend(config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          include: [
            // path.resolve(__dirname, './node_modules/TestComponent'),
          ]
        });
        // config.resolve.alias['~admin-lte'] = './node_modules/amin-lte',
        // config.resolve.alias['~jquery'] = './node_modules/jquery'
      }
    }
  }
};

**Comment by sschadwick** [comment]
Try using the official nuxtjs font-awesome package: https://github.com/nuxt-community/modules/tree/master/packages/font-awesome
