### ISSUE TITLE
Strange loader behavior 

### ISSUE THREAD

**Issue by ajcpwnz** [nuxt/nuxt.js#327]
If i set `loading` to false in `nuxt.config.js` after initial render from server i get this:
<img width="564" alt="screen shot 2017-03-01 at 12 13 08 am" src="https://cloud.githubusercontent.com/assets/16022609/23436629/e48b3f38-fe13-11e6-9161-82465d39b795.png">. 
Error doesn't seem to influence anything in my code, but it's an error nonetheless. 
Can't check if it appears in production, since right now heroku where my app is hosted is down 😄 .

Will add trace from production as soon as I can get it.

**UPD** Both these errors don't appear in production.

**P.S.** With default option, in `loading`, it returns this: 
<img width="506" alt="screen shot 2017-03-01 at 12 17 56 am" src="https://cloud.githubusercontent.com/assets/16022609/23436838/9afec596-fe14-11e6-9791-3e0c71a6da31.png">.

**Comment by Atinux** [comment]
I'll take a look at it, thank you for reporting it @ajcpwnz

**Comment by Atinux** [comment]
It should be fixed in the last release 👍
