### ISSUE TITLE
Error using mongoose with store vuex!

### ISSUE THREAD

**Issue by phucvo0709** [nuxt/nuxt.js#3277]
I trying to use mongoose with store vuex, but it have all of all packages that are installed enough, but run program error!

![untitled](https://user-images.githubusercontent.com/35060381/39391513-b5df1d2c-4ace-11e8-884e-64e7bd12c007.png)
![untitled2](https://user-images.githubusercontent.com/35060381/39391514-b67ecba6-4ace-11e8-83ad-42adb381405c.png)

**Comment by Extarys** [comment]
Duplicate of [c6987](https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6987)

**Comment by phucvo0709** [comment]
i sr i lag browser

**Comment by Extarys** [comment]
Don't worry ;)
