### ISSUE TITLE
Drop vue-meta

### ISSUE THREAD

**Issue by declandewet** [nuxt/nuxt.js#328]
Hi @Atinux & @alexchopin - author of `vue-meta` here (in case i've been forgotten) :P 

A few weeks ago I was in a motorcycle accident and suffered severe nerve damage in both my arms, so I took a hiatus from coding to recover. I still suffer immense pain and will be unable to maintain any code for some time. I noticed in the new 2.2 updates that Vue now offers a means of managing meta info natively:

https://github.com/vuejs/vue/tree/36810163386dd4f2690d8d1c4b1016f17e467e2d/packages/vue-server-renderer#template

I think letting users manage meta info on their own through this construct will make Nuxt more stable and slice off a pretty unstable dependency.

**Comment by Atinux** [comment]
Hi @declandewet I did not forget you, I'm sorry for your accident and wish you the best recovery!

In fact, Vue suggests to use vue-meta to handle the `context.head`: https://github.com/vuejs/vue-ssr-html-stream#beforestart-event

We can manage vue-meta with @alexchopin, if you give us the access, we can work on fixing some issues on it :)

Futhermore, event if Vue 2.2 added the template option, I love vue-meta since you can define dynamically the html attributes and body attributes!

**Comment by declandewet** [comment]
Hmm - I see, okay. I didn't read far enough into the `template` option I guess, I thought I'd been obsoleted :P I don't want to offload the responsibility of maintaining `vue-meta` to you guys, but since you're my most iconic users I'll give you both write access to the repo given my current condition so if there's anything you want to change / fix then you can.

**Comment by alexchopin** [comment]
Hi, @declandewet I wish you the best recovery too! vue-meta is awesome and we can help you to keep your project alive ;)

**Comment by declandewet** [comment]
Thanks for the well-wishes guys, I'll be back in action on VM as soon as I'm able. If there's anything you want changed you have carte blanche since you're currently getting more production experience with `vue-meta` than I am right now, so I'll trust your judgments!

**Comment by Atinux** [comment]
Sure, be well in the meantime :)

**Comment by declandewet** [comment]
Once you've committed and are ready to push - run any of these:

`npm run deploy -- patch`
`npm run deploy -- minor`
`npm run deploy -- major`

it follows the same semantics as `npm version` but will auto-update the table of contents, the CDN links, switch to the `master` branch, push a new tagged release to NPM and to Github for you etc

**Comment by Atinux** [comment]
That's perfect!

**Comment by Atinux** [comment]
@declandewet can I publish on NPM as well? My username on npm is `atinux`.

**Comment by declandewet** [comment]
@Atinux sure! added you to the collaborators. sorry for the late response
