### ISSUE TITLE
vue cli plugin?

### ISSUE THREAD

**Issue by codeitlikemiley** [nuxt/nuxt.js#3282]
Just wondering if nuxt already has a vue cli plugin that can be use to scaffold a new vue project?

**Comment by HoraceKeung** [comment]
The nuxt starter template is using the vue cli to scaffold a new project, https://nuxtjs.org/guide/installation

**Comment by smiller171** [comment]
@HoraceKeung I do believe the question was about using a plugin, not a template. Vue CLI is totally changing how they handle community templates in 3.0

**Comment by luisfrocha** [comment]
I've tried multiple ways and cannot get the plugin to work properly. Can't find good instructions on how to get it working, either.

**Comment by alanaasmaa** [comment]
I would love to see vue-cli 3 dashboard like feature in nuxt.
