### ISSUE TITLE
Redirect not working inside plugin

### ISSUE THREAD

**Issue by SnirShechter** [nuxt/nuxt.js#3283]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[None](None)

### Steps to reproduce

1. Create a plugin(ssr: false) with a redirect.
2. Run the app
3. Watch the redirect not working

### What is expected ?

To redirect.

### What is actually happening?

Nothing.
+
If i invoke context.next('') before the redirect or set it async(setTimeout 0), it works BUT doesn't change layout.

Thanks in advance!

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6996">#c6996</a>)</em></sub></div>

**Comment by memic84** [comment]
Same issue here, seems to me that redirect is not available with ssr false.

**Comment by SnirShechter** [comment]
@memic84

The problem is not ssr: false in my code.

Router.onReady() means that the router is prepared, but the layout routing is not.

PS seems like this is fixed in the new version(not yet released).
