### ISSUE TITLE
 Cannot read property 'middleware' of undefined 

### ISSUE THREAD

**Issue by mehdi-alouane** [nuxt/nuxt.js#3284]
[HELP], i've had this bug after my last upgrade to ``node_modules`` directory, it seems that is related with ``nuxt-server``, i even delete all my ``middlewares`` and still not fixed .
![screenshot-2018-4-29 http 127 0 0 1](https://user-images.githubusercontent.com/4208162/39408770-5632dfd4-4bd3-11e8-9d10-fa1959e5e143.png)

**Comment by manniL** [comment]
Have you used `middleware: [ /* ... */ ]` in you `nuxt.config.js` or in any `component` or `page` file? :thinking:

**Comment by pimlie** [comment]
Check if you have any js errors in your layouts (if you are unsure just put everything in a try catch). I got a similar error when I had an error in my default layout.

**Comment by laienliang** [comment]
how do you slove this problem?

**Comment by enriquesoto** [comment]
had same error, @pimlie 's answer worked for me, thanks

**Comment by zengweiyikuyi** [comment]
nuxt + vux 
nuxt 1.0.0-rc11 升级到 1.4.1 以后报这个错，解决方法
去掉
directives: {
       TransferDom
}
后不报错

**Comment by LittleChell** [comment]
@pimlie 'answer works to me.

**Comment by MartinMuzatko** [comment]
Same problem. Until yet unsolved.
This happens as soon as I load custom components with the `components` property

**Comment by aldarund** [comment]
@MartinMuzatko create a reproduction in github repo or codesandbox
