### ISSUE TITLE
Unknown plugin "transform-async-to-generator" for npm linked repositories

### ISSUE THREAD

**Issue by JiriChara** [nuxt/nuxt.js#329]
Basically the same issue as `next.js` had: https://github.com/zeit/next.js/issues/84

And the fix was: https://github.com/zeit/next.js/commit/ca161c375f22c71549849595b68f3e43eda94a89

**Comment by Atinux** [comment]
In the next release we are going to use [babel-preset-vue-app](https://github.com/vuejs/babel-preset-vue-app) so we won't have this issue anymore :)

**Comment by JiriChara** [comment]
:+1:

**Comment by corsen2000** [comment]
I'm still having issues with npm linked repositories. I seem to be able to mostly resolve them by extending by build configuration.

```js
build: {
  babel: {
    babelrc: false
  }
}
```

Without this I get errors such as **Couldn't find preset "es2015" relative to directory** when running `yarn dev`.

I am using Nuxt `0.10.5` which includes the change to `babel-preset-vue-app`.

A colleague experienced a similar issue in a clean project. @Atinux I'm not sure this is completely working. We may want to consider re-opening this issue.

**Comment by Atinux** [comment]
In the next release, es2015 will be included directly in the depencies @corsen2000
