### ISSUE TITLE
Replace postcss-next with postcss-preset-env

### ISSUE THREAD

**Issue by hauleth** [nuxt/nuxt.js#3291]
There is issue about deprecation of `postcss-cssnext` (MoOx/postcss-cssnext#445) in favour of [`postcss-preset-env`](https://github.com/jonathantneal/postcss-preset-env) which seems to be much more configureable and simpler in form of supporting new features.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7009">#c7009</a>)</em></sub></div>

**Comment by MoOx** [comment]
I am the creator of cssnext and confirm that cssnext will be deprecated in a near future (nobody is really maintaining it - unlike preset-env)

**Comment by pi0** [comment]
Hey @MoOx. Thanks for the help and clarifying status :) We are going to release Nuxt 2.0 very soon. So do you recommend switching to preset-env right now?

**Comment by hauleth** [comment]
@pi0 as it would be breaking change (not everything that `postcss-cssnext` supports is available OOB in `postcss-preset-env`, to be exact `preset-env` OOB supports features only up to [Stage 3](https://jonathantneal.github.io/cssdb/) while `cssnext` supports at least Stage 1 (nesting rules)) I would vote for 2.0 version instead of current one.

**Comment by pi0** [comment]
@hauleth 1.x won't be affected :) Also nuxt 2 users can still optionally provide their postcssrc file to customize it's config.

**Comment by Extarys** [comment]
As long as there is a thorough migration guide so people don't spend a month trying to understand what they need to do to make it work I'm in.

**Comment by jhpratt** [comment]
`postcss-cssnext` was officially deprecated a few days ago in favor of `postcss-preset-env`.

**Comment by pi0** [comment]
Latest nuxt-edge and nuxt 2 will use `postcss-preset-env` by default. 

@MoOx You made an amazing work with `postcss-cssnext` ❤️

I hope we can also provide an official CSS-In-JS solution in near future too :)
