### ISSUE TITLE
How to hide xhr finished loading after get data axios?

### ISSUE THREAD

**Issue by phucvo0709** [nuxt/nuxt.js#3292]
How to hide xhr finished loading after get data by axios, for another people cannot find my api!

![untitled](https://user-images.githubusercontent.com/35060381/39565450-2a84b99a-4ee2-11e8-99a0-2fe9c038f2e1.png)

**Comment by Atinux** [comment]
Hi @phucvo0709 

You cannot hide XHR requests, Chrome Dev Tools or any other dev tools have a "Network" tab where everyone can see the HTTP requests made. You have to protect your API with JWT or API key for example.
