### ISSUE TITLE
How to import scss file without specify extension in nuxt?

### ISSUE THREAD

**Issue by simongcc** [nuxt/nuxt.js#3293]
For instance, I have tried to do the following

```
<template>
  <h1>Hello world!</h1>
</template>

<style lang="scss">
@import '@/styles/coride/custom-mixins';
  * {
    @include font-prompt;
  }
</style>
```

But it failed to compile unless I specify the extension of the scss file like `@import '@/styles/coride/custom-mixins.scss'`

Because I am converting a VueJS application to NuxtJS, in the VueJS application, I don't need to specify the extension. So it will be quite tedious to convert all those files.
It will be great if I can do the same with VueJS in NuxtJS.

**Comment by simongcc** [comment]
The suggested solutions like this:

It is required to specify extension when using alias "@" with sass-loader 7.0.1 (6.0.6 does not require)
@import '@/styles/coride/custom-mixins.scss';

When using relative path, one can use without extension
and in this case, './' seems always start from root rather than relative to the the vue template
@import './styles/coride/custom-mixins';

**Comment by ApricumMedia** [comment]
Posting this here for anyone stumbling upon this, I never found it in the *Nuxt Docs*:

The convoluted error messages implied that there is no alias for `@` or `~` but *there is an alias for `/assets`, pointing to the physical `assets` directory that can be used in an `@import` from e.g. an SCSS file.
