### ISSUE TITLE
Add a hook which is passed context for testing the state data passed from server to client

### ISSUE THREAD

**Issue by 38elements** [nuxt/nuxt.js#3294]
### What problem does this feature solve?

I want to test the state data passed from server to client.
This resolve this by adding a hook to get `context.nuxt`.

### What does the proposed changes look like?

https://github.com/nuxt/nuxt.js/blob/8feeeb0cfe4345e47f561198272ded6926d8d2b8/lib/core/renderer.js#L355-L361

↓

```js

    const serializedSession = `window.__NUXT__=${serialize(context.nuxt, {
      isJSON: true
    })};`

    await this.nuxt.callHook('render:passingData', context.nuxt)

    const cspScriptSrcHashes = []
    if (this.options.render.csp && this.options.render.csp.enabled) {
```

#### Usage

```js
const { Nuxt, Builder } = require('nuxt')
const config = require('./nuxt.config.js')
config.dev = false
const nuxt = new Nuxt(config)
nuxt.hook('render:passingData', (passingData) => {console.dir(passingData)})
new Builder(nuxt)
.build()
.then(() => nuxt.renderRoute('/'))
.then(({ html, error, redirected }) => {
})
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7015">#c7015</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @38elements 

I like this idea, I'm not found of `passingData`, why not calling it `render:context` (cc @pi0 @clarkdo)

**Comment by pi0** [comment]
I love this idea too! Indeed we can do many more things than just for testing. Also, `render.context` hook seems more clear :)

**Comment by Atinux** [comment]
Why not calling it before `serializedSession` so it gives the opportunity to modules to extend the data sent back (even if we have `beforeNuxtRender` method already)?

**Comment by clarkdo** [comment]
It's indeed a good proposal, I aggree with @Atinux 's opinion, I can try to add it this evening.

**Comment by syffs** [comment]
Could this help to overcome [such persisted vuex issues](https://github.com/robinvdvleuten/vuex-persistedstate/issues/54#issuecomment-375831480)?

**Comment by 38elements** [comment]
Thank you for reply.

I think `render:context` is better.

> Why not calling it before serializedSession so it gives the opportunity to modules to extend the data sent back (even if we have beforeNuxtRender method already)?

This is very good idea.
This creates many possibilities.
For example, This makes it possible to test only for client side by setting context data at the `render:context` hook.
