### ISSUE TITLE
Hoek version

### ISSUE THREAD

**Issue by Jorybraun** [nuxt/nuxt.js#3295]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[http://www.google.com](http://www.google.com)

### Steps to reproduce

![Screen Shot 2018-05-03 at 2.56.35 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/f5f65d60-4f03-11e8-a37b-c395fc971d10.png)

### What is expected ?

git hub is warning me of a security vulnerability

### What is actually happening?

nothing

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7017">#c7017</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Do npm/yarn upgrade inside your project. Semver/Patches will be applied.

**Comment by Jorybraun** [comment]
i did that and it was super usefull, but the fixes that were suggested didn't actually patch the vulnerabilities.

 npm update fsevents --depth 5,

I ran this mulitple times but it didnt seem to do anything, this was just one of the many updates suggested
