### ISSUE TITLE
`beforeRouteLeave` for Layouts

### ISSUE THREAD

**Issue by kirillbunin** [nuxt/nuxt.js#3298]
### What problem does this feature solve?

Using router events such as `beforeRouteLeave` works in `/pages/*` but it would be great if they could be passed to layouts, and inherited by pages which uses it.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7020">#c7020</a>)</em></sub></div>

**Comment by galvez** [comment]
@kirillbunin Please refer to the https://github.com/nuxt-community/router-module and https://github.com/nuxt/nuxt.js/pull/3655 -- these are likely to help you accomplish this.
