### ISSUE TITLE
Please add the mapping params in nuxt.config.js (generate.routeParams).

### ISSUE THREAD

**Issue by dan-gamble** [nuxt/nuxt.js#33]
When running `yarn run generate` i get: `Could not generate the dynamic route /articles/:slug, please add the mapping params in nuxt.config.js (generate.routeParams).`

I can't seem to tell from the source code and/or other projects what config i actually need for this to work.

**Comment by dan-gamble** [comment]
Just found this:

https://github.com/nuxt/nuxtjs.org/blob/master/nuxt.config.js#L36
https://github.com/nuxt/docs/blob/master/api/menu.json

And this helped me sort it, thanks 👍

**Comment by Atinux** [comment]
Great. I'd love to see your project with nuxt generate.

We will add a link on our website to show the projects made with Nuxt.js 🤘🏻

**Comment by dan-gamble** [comment]
https://github.com/dan-gamble/dan-gamble.github.io/tree/develop (Master is for deployment like your brother :))

This is a link to the repo, hoping to get a bit of work done to it over the weekend :)

Really liking Nuxt so far, the source is very easy to read so lack of docs so far isn't a problem!

**Comment by Atinux** [comment]
Nice work!

You can add the CNAME in your static/ folder, it will be copied to the dist/ folder automatically with the nuxt generate.

**Comment by dan-gamble** [comment]
Ah, i thought it would copy `/static/` into `dist/static/`. That would save me doing package.json trickery :)
