### ISSUE TITLE
Question: apply a transition on the initial render of a node

### ISSUE THREAD

**Issue by norbert989** [nuxt/nuxt.js#330]
Hi,
I am using nuxt's transition object to set the animation for loading routes, If you also want to apply a transition on the initial render of a node in Vue you can add the 'appear' attribute.

```
<transition appear>
  <!-- ... -->
</transition>
```

Which should use the transitions specified for entering and leaving by default.

However this attribute doesn't seem to be present in the nuxt docs amongst the keys available for the transition properties.
Is there a way to make the transition also happen on the initial load of the node using the transition object in nuxt?

Thank you.

**Comment by Atinux** [comment]
Hi @norbert989 

When vue server-render the app on the server side, it only hydrates the DOM and does not apply any transition, that's why the appear class is not present in the available keys.
