### ISSUE TITLE
Cannot find /_nuxt/vendor.bundle.js

### ISSUE THREAD

**Issue by pdll** [nuxt/nuxt.js#331]
Hello again!
Working with koa-nuxt template, trying to make production version of application. When i'm trying to do npm run start (after npm run build), the server staring, but with no css and with this messages in console

<img width="475" alt="screen shot 2017-03-02 at 12 06 15" src="https://cloud.githubusercontent.com/assets/9680703/23495923/4410b1d0-ff41-11e6-8c5f-7f7c813be84a.png">

What am i doing wrong?

**Comment by pdll** [comment]
Seems like it doesn't really try to make client build. Here is an output of nom run build

`build [=============       ] 65%[nuxt:build:server]
 Hash: ea4affe609e4fff26543
Version: webpack 2.2.1
Time: 17356ms
                      Asset     Size  Chunks                    Chunk Names
        img/bg2.e693547.png  1.25 kB          [emitted]
     img/rocket.aa3c96a.png  3.27 kB          [emitted]
 img/arrow_left.1681d6e.png  2.73 kB          [emitted]
img/arrow_right.b766fc8.png  2.74 kB          [emitted]
       img/help.2a764e7.png  3.19 kB          [emitted]
       img/more.e4f2ed3.png  3.69 kB          [emitted]
       img/logo.cfdfefe.png  5.81 kB          [emitted]
   img/appstore.5557fc5.png  2.41 kB          [emitted]
         img/bg.1244333.png  1.25 kB          [emitted]
  img/money-bag.d26f8b1.png  3.27 kB          [emitted]
 img/googleplay.4857358.png   7.5 kB          [emitted]
       img/back.a34ef5f.png   3.4 kB          [emitted]
    img/cat-bag.b551904.png  3.54 kB          [emitted]
 img/chat_black.6660589.png  3.39 kB          [emitted]
      img/close.57ac1cc.png  7.54 kB          [emitted]
 img/help_white.5048a93.png  5.88 kB          [emitted]
       img/plus.7434e98.png  2.68 kB          [emitted]
   img/logo_mob.be3ec30.png  4.82 kB          [emitted]
           server-bundle.js   770 kB       0  [emitted]  [big]  main

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets:
  server-bundle.js (770 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the r
Entrypoints:
  main (770 kB)
      server-bundle.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some pa
For more info visit https://webpack.js.org/guides/code-splitting/`

**Comment by pdll** [comment]
And little bit above that
```

  build [==========          ] 50%TypeError: error.setMessage is not a function
    at LazyResult.handleError (/Users/pdll/Dev/node/nuxt-koa/node_modules/postcss/lib/lazy-result.js:162:23)
    at /Users/pdll/Dev/node/nuxt-koa/node_modules/postcss/lib/lazy-result.js:196:27
(node:53295) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'source' of undefined
(node:53295) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-ze
ro exit code.
```

**Comment by Atinux** [comment]
@pdll 

Can you create this issue on the [koa](https://github.com/nuxt/koa) repo please?

**Comment by liuhuanhui** [comment]
mee to hello?How to do it, thank you
