### ISSUE TITLE
webpack chunks are not "unique"

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#3312]
### Version

[2.0](https://github.com/nuxt/nuxt.js/releases/tag/2.0)

### Reproduction link

[https://no-link-available.com](https://no-link-available.com)

### Steps to reproduce

I have set up a CDN that caches all static assets for serveral days in between, and nuxt files (/_nuxt) are served from the CDN. Well, because of unique checksums/hashes, this is usually not a problem. But since around 5 days, it seems that nuxt-edge generates the same filenames, even the code is not the same anymore. The app just stops working without any error message at all. If I flush the CDN cache, and force my brwoser to reload the files, all works fine again. Not quite sure what causes this, must have to do with the filenames though.

### What is expected ?

unique file names based on the content (hash) should be generated again, so CDNs can cache the old - and new version when there is a newer file available.

### What is actually happening?

even if content of a fiel changes, the filename seems not to change (or not all parts at least).

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7040">#c7040</a>)</em></sub></div>

**Comment by lucasmpaim** [comment]
+1

**Comment by lucasmpaim** [comment]
Any update on this?

**Comment by lucasmpaim** [comment]
A temporary fix can be something like this:

`
filenames: {
      css: 'style.v1.[chunkhash].css',
      manifest: 'manifest.v1.[chunkhash].js',
      app: 'app.v1.[chunkhash].js',
      chunk: 'chunk.v1.[chunkhash].js'
    },
`

**Comment by luketgriffith** [comment]
+1 thanks for the temp fix @lucasmpaim

**Comment by clarkdo** [comment]
@simllll Can you have a try at latest `nuxt-edge`.

I tried to build `exmaples/meta-info`, the `index.vue` is built as `6e05feaf8c7c328b0dd6.js`,  and then I remove ` 🚀` in `<h1>`, the file becomes `417fd756bb311c3846c1.js`.

So it seems fixed now, I'll close the issue, if your problem doesn't get resolved, please feel free to ping me, I can reopen it.
