### ISSUE TITLE
confusion and errors with nuxt.config.js on a fresh project started with vue cli and nuxt starter template

### ISSUE THREAD

**Issue by dottgonzo** [nuxt/nuxt.js#332]
i've update nuxt and vue-cli, then i've generated a project with vue init nuxt/starter newproject, then i've updated my nuxt.config.js to be able to use i18n and axios

this is my nuxt.config.js

module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'starter',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Global CSS
  */
  css: ['~assets/css/main.css'],
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
    router: {
    middleware: 'i18n'
  },
  build: {
    /*
    ** Run ESLINT on save
    */
    vendor: ['axios'],
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  },
    plugins: ['~plugins/i18n']
};

when i do npm run dev or npm run build, i can't build the project and eslint give me this error:

Cannot find module 'eslint-plugin-~plugins/i18n' and don't recognise any other plugin

I can't understand if vue-cli template is broken with last nuxt version, of it is an eslint issue.

And by the way, someone can explain me (or give some link in which i can read something about) how i have to integrate an html template if i need to integrate jquery, bootstrap and other libraries into nuxt? I have to load it on client only?

**Comment by alexchopin** [comment]
Hi,
It seems that you don't have i18n.js file in your plugins folder.
For jquery and bootstrap you can see the answer [here](https://github.com/nuxt/nuxt.js/issues/178).

**Comment by dottgonzo** [comment]
i have it, it is placed in plugins/i18n.js.

As sayed, it tell me "Cannot find module 'eslint-plugin-~plugins/i18n'"
seems a wrong path eslint-plugin-~plugins/i18n

**Comment by dottgonzo** [comment]
doh,
i've added the plugin in eslintrc (don't know when, and why! maybe typed on the wrong tab of the ide)....
