### ISSUE TITLE
how to custom .nuxt/views/error.html  page ?

### ISSUE THREAD

**Issue by hotpotbybao** [nuxt/nuxt.js#3323]

**Comment by Krutie** [comment]
To create custom error page in Nuxt, you need to create `error.vue` page in `layouts` directory.

`error.vue` automagically receives `error` object as props, like this, `props: ['error']`, which consists error code and message keys.

Here's an example.

```
// layouts/error.vue

<template>
  <div class="container">

    <h1> {{ error.statusCode }} </h1>
    <h1> {{ error.message }} </h1>

  </div>
</template>

<script>

export default { 
  props: ['error']
}

</script>
```

**You can use `error.statusCode` with `v-if` to display custom messages for each error code.**

```
<div v-if="error.statusCode == 404"> Page Not Found </div>
<div v-if="error.statusCode == 500"> Internal Server Error </div>
```
**How to use/call this custom error page?**

Traditionally, you can call this custom error page from any **lifecycle hooks** of Nuxt.js.

You need to use `error` key provided in the most powerful `context` object of this framework. 

Context object is available in all Nuxt.js lifecycle hooks, i.e. nuxtServerInit (), middleware, validate (), asyncData() and fetch().

`context.error` is a function and you can activate it like this:
```
error({ statusCode: 400, message: 'Uh-oh, something went wrong.' })
```

The most common block to invoke the error function is `.then()`, like this: 
```
...
asyncData ({ error }) {

    return axios.get('http://jsonplaceholder.typicode.com/users')
     .then(response => {
       console.log(response.data)
     })

     .catch(err => {
       return error({ statusCode: 400, message: 'Data not found' })
       // this will immediately look for the `layouts/error.vue` and 
       // display custom error information of as described 
     })

  }
...

```

Deliberately make a mistake in, say API url in `asycnData ()` and see the error page in action.
