### ISSUE TITLE
How I change request url from /_nuxt/xx to /nuxt/xx

### ISSUE THREAD

**Issue by caszhou** [nuxt/nuxt.js#3327]
I want to use Aliyun SLB for load balance. Nuxt http request always starts with _nuxt, but Aliyun SLB cannot use '_'.

Is there any other ways to change url prefix ?

Thanks

**Comment by caszhou** [comment]
maybe nginx url rewrite is work

**Comment by caszhou** [comment]
someone has other options?

**Comment by hollowtree** [comment]
@caszhou [https://nuxtjs.org/api/configuration-build#publicpath](https://nuxtjs.org/api/configuration-build#publicpath)
