### ISSUE TITLE
Optimizing SSR Bundle size

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#333]
Hello. This actually is a story behind one of our nuxt based production applications, some workarounds was used to make ssr bundle smaller and much much more faster. All of them are implemented in [nuxt-helpers/optimize.js](https://github.com/fandogh/nuxt-helpers/blob/master/plugins/optimize.js) and tested against nuxt 0.9.9.
About one week ago just after first deployment, i just figured out that SSR is really slow (~8req/sec with 1 worker) so the first thing i have checked was big ssr bundle size (~800kb), thanks to super useful nuxt `extend` function, i have enabled `BundleAnalyzerPlugin` for server side like this : 
```js
extend (config, {isServer}) {
    if (isServer)  config.plugins.push(new BundleAnalyzerPlugin({}));
}
```

The result was shucking
![image](https://cloud.githubusercontent.com/assets/5158436/23521383/f6d7709a-ff93-11e6-8e95-95fc77c9852b.png)

**sass and css files where bundled**
They are really useless for server-side and just make things much slower. unfortunately without some hacks it is not possible to remove them from bundle. so i have used [ignore-loader](https://github.com/cherrry/ignore-loader) plugin to bypass vue loader : 
```js
  ['scss', 'css'].forEach(function (ext) {
            config.module.rules[0].query.loaders[ext] = 'ignore-loader';
   });
``` 

**vendors are not externalized**
We are just externalizing direct dependencies in package.json (like vue documentation example) but if we have indirect dependencies like nuxt-helpers they will be loaded into SSR bundle and have to parsed/loaded on each request! Simple workaround was adding nuxt.js vendors to externals too :  ```config.externals = _.uniq(config.externals.concat(nuxt.build.vendor));```

**unnecessary babel presets**
If you look in bundle analyzer result again, you will see big `core-js` and `regenerator` runtimes packaged with bundle. As a first attempt i just tried to externalize them like other vendors, but unfortunately this won't work and will throw run-time errors as they should be required by default. Worst than it babel is compiling many lines of code into older js syntax which makes code slower, many of them (including `async/await` are now enabled in modern & stable node.js releases and are much much much faster than babel compiled code.  I have used [this workaround](https://github.com/fandogh/nuxt-helpers/blob/master/plugins/optimize.js#L33) to reduce amount of presets and just compiling a modern SSR bundle :)  It would be great if nuxt.js just has a built-in option to enable this optimization.

**The result**
![image](https://cloud.githubusercontent.com/assets/5158436/23522059/da0acdf6-ff96-11e6-9401-f7ecec3e9d2a.png)

Bundle size is now about 9x smaller (under 100kb), it is much faster because no vendors are included and are cached and much much faster because of using modern native `async/awaits`. I can't exactly remind but SSR was handling ~150requests/sec with 4 workers using optimizated version. 😎 

**Extra 1**
I was also tried new vue ssr bundle format with no luck (mentioned problems just exists and code splitting didn't helped a lot)

**Extra 2**
Also during last hack i have found a bug in nuxt `extend` function! [base.config.js](https://github.com/nuxt/nuxt.js/blob/master/lib/webpack/base.config.js#L66) is applying defaults to bable options on original object. so if some one changes anything shared in  `extend` for server, it will be applied to client options too! Although no one should do this it can be easily fixed and prevented by extending on a new object like this : ```defaults({}, this.options,...```

**Comment by Atinux** [comment]
Hi @pi0 thank you for your implication with nuxt.js. I will take a deeper look at it and come back to your later.

Actually, I am implementing Vue 2.2 which will let us add the CSS used by the rendered components directly in the `<head>` so the CSS might be needed in the server bundle.

**Comment by fritx** [comment]
@pi0 what was your "workaround" to compile against modern node and native async/await feature?
your link is not-found now.

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋ 

@pi0 do you mind checking again an give me a feedback now? 😃

**Comment by pi0** [comment]
@Atinux Congratulations for this release :)  I'm going to experiment new features and upgrade things :) Will come back soon.

**Comment by pi0** [comment]
@Atinux  As first attempt i started migration of static [BootstrapVue](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/build/nuxt.config.js) docs. Generated html files are so HUGE  (~176kb each) including entire Bootstrap css.
I then tried moving imports from css in nuxt.config to layout files (with `import directive`) but still same behavior... Is it an expected one? And if so what is your suggestion? :(

**Comment by Atinux** [comment]
@pi0 for the html files, only one needs to be loaded by the browser, and gzipped, **the size is 26.9KB**. 

What about using your CDN to include the bootstrap CSS instead?

`nuxt.config.js`
```js
module.exports = {
  head: {
    link: [
      { type: 'text/css', rel: 'stylesheet', href: '//unpkg.com/bootstrap@next/dist/css/bootstrap.min.css' },
      { type: 'text/css', rel: 'stylesheet', href: '//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css' },
  }
}
```

I need to remove the warning for the moment, actually I was thinking of letting the option for the user but extracting the CSS does not help to improves the performances and getting closer to PWA.

**Comment by pi0** [comment]
@Atinux I Agree :)) It was my bad resisting on new technology just because older one WORKS :)) Closing this PR to keep Issues clean. Will provide a fresh report next week when I've researched enough about available solutions :) 
Thanks for your hard work on awesome Nuxt ;)

**Comment by Atinux** [comment]
Thanks to you for helping us to make Nuxt.js better :)
