### ISSUE TITLE
Add Named Exports to Nuxt 2

### ISSUE THREAD

**Issue by bradocchs** [nuxt/nuxt.js#3347]
### What problem does this feature solve?

Right now you have to:
```
import nuxt from 'nuxt-edge'
...new nuxt.Nuxt() or new nuxt.Builder()
```
It would be great to import by name:
```
import { Nuxt, Builder } from 'nuxt-edge'
```

I can't stand using require anymore! ;)

### What does the proposed changes look like?

See above.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7091">#c7091</a>)</em></sub></div>

**Comment by chanlito** [comment]
@bradocchs I can do that. What's wrong?

**Comment by bradocchs** [comment]
I get this error:
import { Nuxt, Builder } from 'nuxt-edge'
         ^^^^
SyntaxError: The requested module 'nuxt-edge' does not provide an export named 'Nuxt'

**Comment by chanlito** [comment]
@bradocchs I don't think it works with node.js unless nuxt-edge has a .mjs extension.

**Comment by bradocchs** [comment]
That makes sense. They are stuck with CommonJS until node makes ES modules official.

Guess I'll have to wait.
