### ISSUE TITLE
Store and middleware location as aliases

### ISSUE THREAD

**Issue by gahissy** [nuxt/nuxt.js#335]
Hello guys,

I'm trying to write a nuxt starter library where all my apps will inherit some predefined pages, routes, plugins, etc.

I have the following structure :

<img width="609" alt="screen shot 2017-03-03 at 12 29 17 am" src="https://cloud.githubusercontent.com/assets/140107/23533271/7b05f2f6-ffa8-11e6-9867-a32e3622f050.png">

For the structure to be complete I'm looking for a way to have nuxt load middlewares and stores from another location than the `srcDir` (in this case the `.portal` dir). 

I see two ways to achieve that :
1. Have `store` and `middleware` as aliases like the `~plugins` so that it can be changed in `build { extend(config) { ... } }`
2. Instruct nuxt to look for stores and middlewares in multiple locations

For both, I'll have to fork the project I guess. Is there a way to achieve that with the current API ?

Thanks.

**Comment by alexchopin** [comment]
It's very specific to your project structure in fact, have you try with Symbolic Links?

**Comment by gahissy** [comment]
Yes, I'm working with symbolic links now but it's not something that I can push to production.
