### ISSUE TITLE
npm install or yarn install error

### ISSUE THREAD

**Issue by fe-hunk** [nuxt/nuxt.js#3352]
npm ERR! code E404
npm ERR! 404 Not Found: @nuxtjs/youch@^4.2.3
or
error An unexpected error occurred: "Couldn't find package \"@nuxtjs/youch@^4.2.3\" required by \"nuxt\" on the \"npm\" registry.".

npm -v  5.6.0
node -v 8.11.1

**Comment by HoraceKeung** [comment]
Sorry if this doesn't help,but please try delete the node_modules folder, yarn.lock and/or package-lock.json and run yarn again. And maybe ensure it is nuxt 1.4.0.
