### ISSUE TITLE
npm audit found vulnerable package with severity as critical

### ISSUE THREAD

**Issue by githingeorge** [nuxt/nuxt.js#3353]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://www.google.com/](https://www.google.com/)

### Steps to reproduce

just followed Getting Started guide
npm audit flagged macaddress as vulnerable package
nuxt > css-loader > cssnano > postcss-filter-plugins > uniqid > macaddress 

![Screenshot from 2018-05-17 10-11-10.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/a41bd0e0-598c-11e8-8321-3fd3593a6825.png)

### What is expected ?

none

### What is actually happening?

none

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7101">#c7101</a>)</em></sub></div>

**Comment by pSchaub** [comment]
See https://github.com/scravy/node-macaddress/issues/19

**Comment by githingeorge** [comment]
Closing as there's nothing we can do about this from here.
