### ISSUE TITLE
Strange behaviour on production

### ISSUE THREAD

**Issue by ForzaNikolay** [nuxt/nuxt.js#3354]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/ForzaNikolay/issue-example](https://github.com/ForzaNikolay/issue-example)

### Steps to reproduce

npm install 

`Development`
npm run dev 

`Production`
npm run build 
npm run start

### What is expected ?

.wasm file to have the same content-type on development and production

### What is actually happening?

The content-type on development(application/wasm) is different from production(application/octet-stream)

### Additional comments?

I'm not so sure if that's an Nuxt issue if it's not i would appreciate some reference to the problematic package.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7104">#c7104</a>)</em></sub></div>

**Comment by Atinux** [comment]
Test

**Comment by Atinux** [comment]
Seems related to https://github.com/expressjs/serve-static/issues/99 (found by @clarkDu)
