### ISSUE TITLE
Loading late with running!!!

### ISSUE THREAD

**Issue by TesalVector** [nuxt/nuxt.js#3363]
Hii,

I have a problem with loading. Custom loading is appear (other name splash screen) after loading page.
How do I set to work custom loading before loading page?

![img1](https://user-images.githubusercontent.com/21141150/40403975-83f0c00a-5e55-11e8-9206-f702ea113e08.png)
![img2](https://user-images.githubusercontent.com/21141150/40403977-8845fdfa-5e55-11e8-9ebd-d52c1554a5a1.png)

**Comment by nikkanetiya** [comment]
Hello @TesalVector, I think there is no need to add nextTick in mounted for Loader component. Just remove that part and if you want to keep loader upto 5 seconds to testing or whatever purpose at that part mounted method in other pages and try if it solves your issue.

**Comment by TesalVector** [comment]
Hi @nikkanetiya, thanks you so mutch! You helped me! But i find one more problem: initialization **loading: false** on **loading: true**.  :D
