### ISSUE TITLE
Separate Server Side and Client Side Env Vars

### ISSUE THREAD

**Issue by jefer590** [nuxt/nuxt.js#3365]
### What problem does this feature solve?

Working with NuxtJS, I noticed that the `nuxt.config.js` exports all the env vars to the server and the client. There's no way, right now, to encapsulate server side and client side env vars.

### What does the proposed changes look like?

Instead of having all the env vars that you will need in a single object, you can simply add new keys for server and client in the `nuxt.config.js`
```javascript
env: {
  client: {
    var1: 'url',
    var2: 'myvalue'
  },
  server: {
    token: 'mysecret',
    apikey: 'mysecret2'
  }
}
```

And you can access it like this:

#### Server Side:
```javascript
context.server.env.token
context.server.env.apikey
```

#### Client Side:
```javascript
context.client.env.var1
context.client.env.var2
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7126">#c7126</a>)</em></sub></div>

**Comment by manniL** [comment]
Will release a module for this shortly

**Comment by manniL** [comment]
https://github.com/nuxt-community/separate-env-module/
