### ISSUE TITLE
toLowerCase localeCompare does not work in NuxtJs VueJs Framework

### ISSUE THREAD

**Issue by kamleshkatpara** [nuxt/nuxt.js#3366]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://stackoverflow.com/questions/50494958/tolowercase-localecompare-does-not-work-in-nuxtjs-vuejs-framework](https://stackoverflow.com/questions/50494958/tolowercase-localecompare-does-not-work-in-nuxtjs-vuejs-framework)

### Steps to reproduce

I have encounter a very strange issue in NuxtJs (VueJs Framework).

I have a code which was working well for my stores list in alphabetical order and search filter. As it was working I copied the same code functionality for my categories. The next day when I click on categories it worked fine but on stores it gave me this two errors:

Cannot read property 'localeCompare' of undefined

Cannot read property 'toLowerCase' of undefined
Not sure what went wrong its the same code on both pages, only the difference in data it loads for stores and categories. If remove both localeCompare & toLowerCase it loads the data properly but without the search filter and the list unordered.

### What is expected ?

localeCompare & toLowerCase should work

### What is actually happening?

localeCompare & toLowerCase not working

### Additional comments?

I have encounter a very strange issue in NuxtJs (VueJs Framework).

I have a code which was working well for my stores list in alphabetical order and search filter. As it was working I copied the same code functionality for my categories. The next day when I click on categories it worked fine but on stores it gave me this two errors:

Cannot read property 'localeCompare' of undefined

Cannot read property 'toLowerCase' of undefined
Not sure what went wrong its the same code on both pages, only the difference in data it loads for stores and categories. If remove both localeCompare & toLowerCase it loads the data properly but without the search filter and the list unordered.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7127">#c7127</a>)</em></sub></div>

**Comment by clarkdo** [comment]
If you are using ssr, `asyncData` will be executed at servers side when first accessing, so you can check at server side if `asyncData` returned `stores` contains `store_name`.

**Comment by kamleshkatpara** [comment]
@clarkdo , The same code is working for my categories page

**Comment by clarkdo** [comment]
Are you sure that the two pages are both loading data at same end (server or client)?

**Comment by Atinux** [comment]
Please provide us a reproduction with https://glitch.com/edit/#!/nuxt-hello-world for example.

You may want to check that the variable exists before using `toLowerCase`: 

`myVar && myVar.toLowerCase()`

**Comment by kamleshkatpara** [comment]
@Atinux  I tried to update my vue cli and reinstalled the modules and it workd, thanks
