### ISSUE TITLE
Sitemap and XML suport out of the box

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#337]
Hi!

It would be great if nuxt supports xml format out of the box.

I know I can now use nuxt as middleware for the express. But what I love about nuxt that it just works without any configuration.

How I see it:
there would be ```xml``` folder

In xml folder we can create as many js files as we want.
Each file is mapped to one route as xml page.

For example
```xml\sitemap.js``` would generate sitemap.xml
```xml\merchants.js``` would generate merchants.xml (google shops format)
etc.

In each file there should be exported one function that takes ```context``` and return a ```promise```
The promise returns xml data.

So nuxt should scan the folder, map the routes and set proper content-type when request come.

Guys, what do you thing about it?

**Comment by Atinux** [comment]
Hi @awronski 

Thank you for your idea, but we cannot implement it in the core of nuxt.js.

But we would love to see a plugin/module for it, called `nuxt-sitemap` for example which extend `nuxt.render` to check the url, and if the url match a file in the `xml` folder, then call the method, otherwise, call the original `nuxt.render(req, res)` method.

You can take a look at [nuxt-helpers](https://github.com/fandogh/nuxt-helpers) made by @pi0 who did a great job on it.

In the future we may introduce a feature to include nuxt modules directly inside the `nuxt.config.js`:

```js
module.exports = {
  modules: ['nuxt-sitemap', 'nuxt-helpers/optimize']
}
```

The module will be called when `nuxt` instance will be created so the module can extend nuxt (by overwriting it's method or options).

**Comment by awronski** [comment]
Thanks for the hint. I will look at the helpers.

It would ber great if you add modules to the config!


Thanks in advance,

**Comment by NicoPennec** [comment]
issue resolved :smile: 

- Install module with npm (or yarn)
```
npm install @nuxtjs/sitemap
```

- Configure module in `nuxt.config.js`
```
  modules: [
   '@nuxtjs/sitemap'
  ]
```
https://github.com/nuxt-community/modules/tree/master/modules/sitemap

**Comment by pi0** [comment]
@NicoPennec Thanks to your works sitemap would be a super useful thing for many Nuxt users. ❤️ 
 
I'm adding little more improvements. Will inform you making a final review before publish (Will be ready in ~1h). BTW Still two important decision remaining:

First, As of [express section](https://www.npmjs.com/package/sitemap#example-of-using-sitemapjs-with-express-) in docs they suggested creating a global sitemap instance shared across requests and updating it using dynamic capabilities, current approach that calling async generate routes for each request feels like a PHP approach (1 req - 1 complete process), However I still agree there should be a runtime method for updating sitemap. My suggestion is we could use something like an LRU cache with `maxAge` option. Whats your idea?

Second, while middleware are nice, they won't work for static generated sites, I will try to handle it supporting both methods like your first version :)

**Comment by NicoPennec** [comment]
@pi0 yes, I have planned to manage a LRU cache. It should be the next release.
For the second topic, I never use the `generate` feature. Thanks for your help on this point :)

**Comment by pi0** [comment]
@NicoPennec I've pushed my changes (cache is added too sorry i was too exciting for that :P) please take a look and feel free making PR for changes. I will release alpha now, will separate some modules (including sitemap) into their own dedicated repo so then we could easily contribute.

**Comment by awronski** [comment]
@pi0 I didn't see the push yet but just want to let you know that sitemap has a built cacheTime. 
So it is working out of the box

**Comment by pi0** [comment]
I mean commit 😁 cacheTime of sitemap is implements too now but it should be applied when resolving routes too.

**Comment by MatthieuHPP** [comment]
Many thanks for this work, this will ease the "sitemap" implementation I have to do :-).

**Comment by ducdebreme** [comment]
I followed the 2 steps on my Mac

1. npm install @nuxtjs/sitemap
1.  ` modules: [
   '@nuxtjs/sitemap'
  ]`

But when I run

> nuxt build
[nuxt] Building...
[nuxt] Unable to resolve module @nuxtjs/sitemap


I get an syntax error ... 
**[SyntaxError: Unexpected token {]**

I checked node_modules folder: the module has been installed.
The error goes away as soon as I remove the modules key from nuxt.config.js

**Comment by andreliem** [comment]
@ducdebreme I had the same issue, and it ended up being that I had to update my version of node.

**Comment by NicoPennec** [comment]
@ducdebreme @andreliem 
Which version of Node.js ?
Can you share your nuxt.config.js (`sitemap` part only) ?

From my side, it works fine with : 
-`Node.js` v8.3.0
- `Nuxt` v1.0.0 RC4
- `@nuxtjs/sitemap` v0.0.3

**Comment by ducdebreme** [comment]
Mine is

- Node.js v5.1.1
- Nuxt nuxt@1.0.0-alpha.5
- @nuxtjs/sitemap v0.0.3

**Comment by ducdebreme** [comment]
Thanks Nico, I have updated to latest Node.js, Nuxt and sitemap, too.
Still need to try the sitemap ...

**Comment by MatthieuHPP** [comment]
hello,

I have installed @nuxtjs/sitemap via npm and have referred it within the module part of the nuxt config file :  modules: [ '@nuxtjs/sitemap' ].

Tools evaluating SEO say my web site does not have any sitemap.xml file. 
What am I doing wrong ?

Nuxt is used in production, my versions are :
node 6.11.0
nuxt 1.0.0_alpha5
@nuxt/sitemap 0.0.3

Many thanks for your help

Matthieu

**Comment by fabionolasco** [comment]
Hi MatthieHPP, it worked for me. 
I am using node 6.11.1.
Here is my github repo with the use case:
https://github.com/fabionolasco/fabionolasco.com

**Comment by MatthieuHPP** [comment]
Many thanks Narcisio. I'have added robots.txt in static folder and now
sitemap.xml is found by seo tools.
Have a nice day
Matthieu
