### ISSUE TITLE
nuxt-start package on npm don't have update to 1.4.0

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxt.js#3370]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://www.npmjs.com/package/nuxt-start](https://www.npmjs.com/package/nuxt-start)

### Steps to reproduce

npm install --save nuxt-start

only can install to 1.0.0-rc11

### What is expected ?

npm install --save nuxt-start

should install the lastest version 1.4.0

### What is actually happening?

forget publish nuxt-start to npm ? 

### Additional comments?

sorry , 

I can't find nuxt-start repo , and on npm page , it's redirect to nuxt.js repo . so, @Atinux  can you help publish the latest nuxt-start on npm ?
thanks.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7133">#c7133</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @ausir0726 

Actually we will find a way to automatically sync it with 2.0

In the meantime, please don't use it, sorry about this :s

**Comment by ausir0726** [comment]
@Atinux , ( thanks all for nuxt community people )

HI , I'm use docker image deploy our nuxt project 
I already use multi stage build image , first , download all dependence and run nuxt build
and then copy .nuxt and static folder to second build stage and use npm i nuxt , and run nuxt start

but , when I npm i nuxt , all dependence about 100MB , that make the image to big .
so , I find nuxt-start , seems like just only need 20MB can use nuxt start for production .

before nuxt 2 , or I need production 1.4.0 minimal docker image , any idea ?

thanks .

**Comment by Atinux** [comment]
I am really sorry @ausir0726 but I looked at it and it will take too much time to publish nuxt-start 1.4.X, it's a mistake from our own and will do our best that it won't happen again with 2.X.
