### ISSUE TITLE
Webpack Resolve Plugins (DirectoryNamedWebpackPlugin)

### ISSUE THREAD

**Issue by jamesAtcodeninja** [nuxt/nuxt.js#3374]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/jamesAtcodeninja/nuxt-directory-named](https://github.com/jamesAtcodeninja/nuxt-directory-named)

### Steps to reproduce

I'm including a resolver plugin in the `build.extend` property of my `nuxt.config.js` like so -
```
build: {
    extend(config) {
       config.resolve.plugins = [
        new DirectoryNamedPlugin({ honorIndex: true }),
      ]
   }
}
```

but receive this error

```

  TypeError: resolver.ensureHook is not a function
  
  - index.js:23 module.exports.doApply
    [sample-project]/[directory-named-webpack-plugin]/index.js:23:25
  
  - Tapable.js:375 Resolver.apply
    [sample-project]/[tapable]/lib/Tapable.js:375:16
  
  - ResolverFactory.js:249 
    [sample-project]/[nuxt]/[enhanced-resolve]/lib/ResolverFactory.js:249:12
```

### What is expected ?

Should compile normally.

### What is actually happening?

TypeError: resolver.ensureHook is not a function

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7144">#c7144</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Seemed to be resolved by https://github.com/shaketbaby/directory-named-webpack-plugin/issues/28
