### ISSUE TITLE
using mixin in plugins, error Maximum call stack size exceeded

### ISSUE THREAD

**Issue by WhiteMinds** [nuxt/nuxt.js#3375]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://jsfiddle.net/tfj14swd/](https://jsfiddle.net/tfj14swd/)

### Steps to reproduce

copy code to file project/plugins/const.js
npm run dev
refresh browser
change any page file, save
refresh browser
throw error

### What is expected ?

throw error "Maximum call stack size exceeded"

### What is actually happening?

i dont know

### Additional comments?

my project is nuxt + iview

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7146">#c7146</a>)</em></sub></div>

**Comment by manniL** [comment]
Have you thought about extending the Vue prototype instead of adding a global mixing (useful if you don't need the reactivity)?

```
import Vue from 'vue'

Vue.prototype.$myConstNameHere = 'myValueHere'
```

**Comment by WhiteMinds** [comment]
@manniL I'm currently dealing with this, but I will submit this bug along the way to let you know.
