### ISSUE TITLE
vendor array to accept regex

### ISSUE THREAD

**Issue by hirokiosame** [nuxt/nuxt.js#3377]
### What problem does this feature solve?

I have a private module, where all the use-cases are something like `my-module/components/A` or `my-module/components/B` (there's about 40 of these). I learned that just adding `my-module` to the vendor array doesn't catch these, but I have to explicitly write every path.

### What does the proposed changes look like?

I was hoping that I could do something like `/^my-module\//` like how the `externals` feature in webpack allows:
```
vendor: [
	'axios',
	/^my-module\/components/,
],
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7150">#c7150</a>)</em></sub></div>

**Comment by manniL** [comment]
The `vendor` attribute will be deprecated in version 2.0

**Comment by hirokiosame** [comment]
@manniL 
Nice, will vendor detection be automatic? Is there somewhere I can see the latest progress/updates/docs to 2.0

**Comment by manniL** [comment]
Unfortunately, there is only the git log and [this medium post](https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67) by now. But I guess more is coming soon :)

You can use the "bleeding edge" build already (by installing `nuxt-edge` instead of `nuxt`) :relaxed:
