### ISSUE TITLE
Using a plain JS library in Vue - window is not defined

### ISSUE THREAD

**Issue by warreb1** [nuxt/nuxt.js#338]
(quesion which might be an issue) We have a CDN of useful plain JS functionalities (opening/closing a modal, ..) that we would like to use in our Nuxt project. When including the CDN (//dij151upo6vad.cloudfront.net/2.latest/js/vlaanderen-ui.js) we instantly get window is not defined.

So my question: Is it possible to use a plain JS library in Nuxt/Vue in general?

**Comment by Atinux** [comment]
Hi @warreb1 

Sure you can, you need to use the `head` property in your `nuxt.config.js`, so it will be included in your generated HTML:

```js
module.exports = {
  head: {
    script: [
      { type: 'text/javascript', src: '//dij151upo6vad.cloudfront.net/2.latest/js/vlaanderen-ui.js', defer: 'defer' }
    ]
  }
}
```
