### ISSUE TITLE
Show modal on route change

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#339]
Hi 
 I need to show a modal on route change. if a file upload is already in progress.
After the upload the user moves to another page.
So if the user clicks on some other button while the upload is happening I need to show this modal.
Is there a hook in pages which I can implement to handle this.

Basically I am looking for a hook which is called when the user leave a particular route.

**Comment by alexchopin** [comment]
Hi,
You need to use `beforeRouteLeave()` from vue-router.
```js
beforeRouteLeave (to, from, next) {
    // called when the route that renders this component is about to
    // be navigated away from.
    // has access to `this` component instance.
  }
```
[Vue Router Documentation](https://router.vuejs.org/en/advanced/navigation-guards.html)

**Comment by shyamchandranmec** [comment]
@alexchopin This works only in pages and not in the components within those pages. So I had to share many variables using the store to get this done. Is it possible to add this functionality to the components as well.

**Comment by shyamchandranmec** [comment]
@alexchopin 
This hook is not available inside components. Its available only inside pages. I have a use case where I need to do something in the component (like reseting its state) when the route changes. 
Any work around for this?

**Comment by alexchopin** [comment]
```js
watch: {
  '$route': function( ...
```

**Comment by shyamchandranmec** [comment]
@alexchopin  Thanks

**Comment by pirmax** [comment]
Have you got an example for this?

**Comment by endaaman** [comment]
On version 1.4.0, using `watch: { $route() { ... } } ` we can not do page transition cancellation that `beforeRouteLeave` allows us to do.

**Comment by alexey-v-paramonov** [comment]
```
  watch: {
    '$route.path': function() {
      ...
    }
  },

```

**Comment by nicroto** [comment]
How do you prevent the navigation within a watch?

**Comment by northamerican** [comment]
the above methods used to detect url changes made with `history.pushState` but since nuxt 2.0, no longer do so. i just use `window.onpopstate = fn` to detect changes to url made with the history API.
