### ISSUE TITLE
nuxt build -a  omits webpack-bundle-analyzer options declared in nuxt.config.js

### ISSUE THREAD

**Issue by lependu** [nuxt/nuxt.js#3390]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Steps to reproduce

Based on [ananlyze](https://nuxtjs.org/api/configuration-build#analyze) configuration example:

```javascript
// nuxt.config.js
module.exports = {
  build: {
    analyze: { 
      analyzerMode: 'server', 
      analyzerHost: '0.0.0.0', 
      analyzerPort: '9999', 
      openAnalyzer: false 
    } 
  } 
} 
```
`$ nuxt build -a`

### What is expected ?

webpack bundle analyzer runs on http://0.0.0.0:9999

### What is actually happening?

webpack bundle analyzer still runs on http://127.0.0.1:8888 (default options)

### Additional comments?

It seems that https://github.com/nuxt/nuxt.js/blob/0d0d83cbc9dc9b75f40169c1a21e5cbe83a2d0ec/bin/nuxt-build#L47 always sets `options.build.analyze: true` and omits the configuration object. Therefore we have no chance to pass any custom option to the webpack-bundle-analyzer plugin. 

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7172">#c7172</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks. PR merged.
