### ISSUE TITLE
Nuxt v-show is not handled properly, if static page is visited after netlify redirect (404)

### ISSUE THREAD

**Issue by Jones-S** [nuxt/nuxt.js#3394]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://5b0e402811b73b3c565110ea--cafe-pluesch.netlify.com/](https://5b0e402811b73b3c565110ea--cafe-pluesch.netlify.com/)

### Steps to reproduce

Hi there
I have no idea what kind of bug this could be but I have the following situation:

I have set a netlify _redirects file with the following content:

`/* /error/index.html 404`
Which means all 404 should be redirected to my error page. This page's content can be edited via CMS.

Anyway, if I visit the error page actively:
https://5b0e402811b73b3c565110ea--cafe-pluesch.netlify.com/error

The link in the upper right corner (Kontakt/Öffnungszeiten) will actually
trigger an action -> a vuex state mutation -> and the Component «Halfpage» which is already in the DOM, because of `v-show` instead of `v-if` is slided in from the right.
This is the expected behaviour!

If I visit a slug that does not exist, netlify will  redirect me (my404 does not exist):
https://5b0e402811b73b3c565110ea--cafe-pluesch.netlify.com/my404

So I effectively land on the same page as before. But this time the button Kontakt/Öffnungszeiten does not work anymore – well at least not everything works.

You can check the console.log.
There you can see all the logs:
- I log the initial click
- I log the triggering of the action
- I log the following state mutation
- and I log the actual state, which clearly changes from false to true

As seen on the `/error` page, this should all work and set this to visible:

```
<template>

  <transition name="u-anim-slide-in">

    <div class="Halfpage" v-show="halfPageOpen">
    ...
    </div>
  </transition>
</template>

```

(halfPageOpen ist a getter, which I set in the computed property:

```
...mapGetters('ui', ['halfPageOpen']),
```

So my suspicion is, that because it is a netlify redirect something in the Vue App is handled differently, and it may have to do with nuxt's static pages?

I hope someone can point me to the right direction. I have no clue where to start, and I don't even know if this is a nuxt bug?
I would appreciate if somebody could look into this, and I'm happy to provide more information about this, if needed.

Cheers

### What is expected ?

A vuex state change should make a v-show element visible. 

### What is actually happening?

This normally works well. It just would not work if a page is visited via Netlify's redirect.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7175">#c7175</a>)</em></sub></div>

**Comment by manniL** [comment]
Looks like it's fixed on the [live version](https://www.cafe-pluesch.ch/ab).
@Jones-S  Would you tell us how you did it? :relaxed:

**Comment by Jones-S** [comment]
I am not sure anymore 😅 
I think I moved the `Halfpage` component to the layout and out of a page template.
That is at least where I have it now.
I think that's what fixed the issue – or rather just avoids it...
