### ISSUE TITLE
Nuxt not load exernal script when user come by $router 

### ISSUE THREAD

**Issue by furyscript** [nuxt/nuxt.js#3396]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[http://codesandbox.io/#](http://codesandbox.io/#)

### Steps to reproduce

Just put external script by using `head` into vue-router component.

Like this
```

  head () {
    return {
      title: 'test',
      meta: [
        { hid: 'description', name: 'description', content: 'test' }
      ],
      script: [
        { src: 'https://www.paypalobjects.com/api/checkout.min.js' },
        { src: 'https://checkout.stripe.com/checkout.js' }
      ]
    }
  }
```
Now if you navigate from another route by `<nuxt-link` to the page that have this external script, if you put a `console.log(paypal)` into `created` is undefined (infact if you inspect element the scripts into head aren't loaded). But if you press `f5` the scripts are correctly loaded.
How can I do this because I need this scripts in only one page 

### What is expected ?

Load external script in one page correctly

### What is actually happening?

Not load external script if you come by `$router` plugin

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7178">#c7178</a>)</em></sub></div>

**Comment by furyscript** [comment]
Someone could help me?

**Comment by clarkdo** [comment]
@furyscript 
Could provide a reproducible repo?

I tried to add your scripts into [`examples/meta-info/about.vue`](https://github.com/nuxt/nuxt.js/blob/dev/examples/meta-info/pages/about.vue) and scripts loaded as expected, so I cannot reproduce this issue in my local.

**Comment by furyscript** [comment]
I resolve the issue by put the script globally into `nuxt.config` and set `defer` so the page doesn't have a render blocking `script`.
Before I tried to put external scripts only in the page where I need to use that, but without success as I explain in this issue...

**Comment by docmattman** [comment]
If I put the external script in the `head`, when I reload the page, it loads fine.  I do see 2 issues (one mentioned above):

1.  When loading the page the first time (using browser refresh) the external script load.  However, if I navigate away and use my browser back button (without reloading any pages), the external script is loaded a 2nd time.  So it loads it twice.  This is currently giving me problems since I'm loading the Google Maps API and having it load multiple times creates issues.

2.  If I navigate away from the page, then reload my browser, then use the browsers back button, the external script never loads and there are errors from it.

Anyone have any insight on how to fix this?

**Comment by furyscript** [comment]
@LeCongThang Just put defer in `nuxt.config` script section:
`{ src: 'https://checkout.stripe.com/checkout.js', defer: true },`

**Comment by manniL** [comment]
related: https://github.com/nuxt/nuxt.js/issues/3872

**Comment by manniL** [comment]
Loading external scripts through the head function works fine for me. I'd suggest to do this on a `layout` basis anyway.

For pages there is the caveat that you can't ensure the readiness easily.


Answers to @docmattman  

> When loading the page the first time (using browser refresh) the external script load. However, if I navigate away and use my browser back button (without reloading any pages), the external script is loaded a 2nd time. So it loads it twice. This is currently giving me problems since I'm loading the Google Maps API and having it load multiple times creates issues.

You could do a check in your head function for `window.XYZ` (whatever your script loads) and prevent duplicate loading with that.

> If I navigate away from the page, then reload my browser, then use the browsers back button, the external script never loads and there are errors from it.

Can't reproduce.
