### ISSUE TITLE
Nuxt fails to load global components when built to functions directory for Firebase Functions SSR

### ISSUE THREAD

**Issue by meta7x** [nuxt/nuxt.js#3397]
### Reproduction link

[https://github.com/meta7x/nuxt-global-components-bug](https://github.com/meta7x/nuxt-global-components-bug)

### Steps to reproduce

- Download reproduction repository
- Run '$npm install' in the root directory
- [optional] run $npm run dev: the page renders the expected result with the global component showing under the Nuxt logo.
- '$cd functions' and run '$npm install' to install Nuxt inside the functions folder
- '$cd .. $npm run dev': the page renders, but there is no global component and there is an error message in the console
- run '$cd functions $npm remove nuxt' to get everything working again

### What is expected ?

Nuxt is still expected to render the page the same way as before.

### What is actually happening?

Instead it registers the component correctly, which can be seen in the console logs, but at the same time it throws an error "unknown custom element". Local components still work fine, as can be seen with the Nuxt logo.

Possibly global mixins don't work either, but I haven't tested that in an isolated environment, also because I'm not quite sure what the correct way to global mixins is in Nuxt.

### Additional comments?

The reason I want to build to build into the functions directory is because I want to SSR with Firebase Functions, which needs to import the Nuxt-class in order to create a Nuxt-instance. Have a look at functions/index.js to see what exactly needs to happen for the app to SSR.
I've been tracking down this error for some time now and it really seems to all come down to whether the second Nuxt-module is inside the functions folder.
Building to any other folder works fine and the public path also doesn't seem to have a big influence.

Files of importance:
- components/GlobalComponent.vue: an example component that I would like to use globally
- plugins/global.js: for registering the global component
- pages/index.vue: the global component is used there alongside a local component
- functions/index.js: the code that is supposed to SSR the app
- nuxt.config.js - obviously

If there's a workaround anyone can come up with, I'd be glad to hack my way around this problem as well. Just importing every component in every other component isn't a great solution though, especially since I have a hunch that my global mixin isn't working for the same reason.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7179">#c7179</a>)</em></sub></div>

**Comment by manniL** [comment]
You can solve this problem by referring to Nuxt from the parents node_modules folder:

`const { Nuxt } = require('../node_modules/nuxt')`

**Comment by WeAspireDev** [comment]
@manniL I tried it but it didn't fix it
