### ISSUE TITLE
nuxt generate fail with axios module

### ISSUE THREAD

**Issue by dottgonzo** [nuxt/nuxt.js#340]
After some test with my code i've tried some example

If i clone the example repository to test i18n (https://nuxtjs.org/examples/i18n), install it's dependencies (npm i) build and test it in development and then do a nuxt generate, compilation fail because "Error: Cannot find module 'axios'"

Someone can explain me how to embed everything into the dist?

**Comment by awronski** [comment]
[Here](https://github.com/nuxt/nuxt.js/issues/284) is exmplainded
