### ISSUE TITLE
asyncData not work in dynamic component?

### ISSUE THREAD

**Issue by ahDDD** [nuxt/nuxt.js#3401]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

```
<template lang="pug">
div
  component(:is="componentActive")
</template>

<script>
import Update from '~/components/Update'

export default {
  components: {
    Update
  },
  data() {
    return {
      componentActive: 'Update'
  }
}
</script>
```

```
# Update.vue
<template lang="pug">
  el-dialog(width='30%', visible)
    //- something
</template>

<script>
  export default {
    async asyncData({ app }) {
      // not work
      console.log(app)
      // same
      const choice = await app.$axios.$get('a fine url')
      return { choice }
    },
    data () {
      return {
        choice: {}
      }
    },
    async created () {
      // ok
      this.choice = await this.$axios.$get(`a fine url`)
    }
  }
</script>
```
I want to use asyncData in dynamic component, but not work at all.

### What is expected ?

to be normal

### What is actually happening?

just not work

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7185">#c7185</a>)</em></sub></div>

**Comment by dohomi** [comment]
@ahDDD asyncData only works on `pages` not on any other components. That is also stated in the docs: https://nuxtjs.org/guide/views#pages

**Comment by ahDDD** [comment]
alright, got it
