### ISSUE TITLE
Add a "routePriority" option on page components to set route order

### ISSUE THREAD

**Issue by docmattman** [nuxt/nuxt.js#3409]
### What problem does this feature solve?

When using the current setup, routes are created in the order they exist in the file system from the `pages` directory.  Sometimes there are multiple routes that may match a given url and we have no way of setting the order.  In plain Vue, routes are match in the order they are defined, but using Nuxt, the order defined is controlled by the file/folder structure.

### What does the proposed changes look like?

It would be good to have some sort of 'routePriority` option on the page components that would create the routes in a custom order defined by their `routePriority` integer value.  If no `routePriority` option is set on the page, it would default to zero, or some other integer value.  The routes would be sorted first by the `routePriority`, then by their file/folder structure order that is currently in place.

It would be nice to have the `routePriority` option available inside the `extendRoutes` section of the `nuxt.config.js` file as well so they don't all have to be pushed to the end of the router file.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7195">#c7195</a>)</em></sub></div>

**Comment by galvez** [comment]
Please check out the [router module](https://github.com/nuxt-community/router-module). You can also completely rewrite the routes Array via [`extendRoutes()`](https://nuxtjs.org/api/configuration-router/) and `routes.splice(0, routes.length, ...[new routes])`.
