### ISSUE TITLE
chrome extention

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#341]
when you build the project arose the following problems:
1) there is no possibility to change the name of the directory _nuxt (_nuxt -> сustom_dir / in extensions are not valid user names of files and directories with an underscore)
2) using the `mode: 'hash'`, incorrect references are generated, they still generated for `mode: 'history'`
3) how to use `CopyWebpackPlugin` only stage `generate`?

**Comment by Atinux** [comment]
Hi @wormen 

1. It's now possible with [build.publicPath](https://nuxtjs.org/api/configuration-build#publicpath)
2. The `mode: 'hash'` is not recommend if working with SSR
3. You should create your `generate.js` file which import nuxt, use a different configuration for `const nuxt = new Nuxt(config)` and then call `nuxt.generate()`

**Comment by wormen** [comment]
@Atinux With point 2, the question has not been resolved, the problem is still observed

**Comment by alexchopin** [comment]
@wormen why using `mode: 'hash'` for SSR ?

**Comment by wormen** [comment]
@alexchopin In applications for `google chrome`, `SSR`is not used, only statics

**Comment by alexchopin** [comment]
Ok I see, only an index.html file is needed when `mode: 'hash'` is activated.

**Comment by wormen** [comment]
I did, but after generating static, `mode: 'hash'` does not work, as described in paragraph 2
work absolute paths to `HTML` files
