### ISSUE TITLE
[edge] html minify issue

### ISSUE THREAD

**Issue by yoyo837** [nuxt/nuxt.js#3411]
### Version

[edge](https://github.com/nuxt/nuxt.js/releases/tag/edge)

### Reproduction link

[https://github.com/yoyo837/nuxt-3392](https://github.com/yoyo837/nuxt-3392)

### Steps to reproduce

See https://github.com/nuxt/nuxt.js/pull/3392#issuecomment-393863232

### What is expected ?

HTML minify work fine.

### What is actually happening?

It report error.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7197">#c7197</a>)</em></sub></div>

**Comment by aldarund** [comment]
Strange things. For me it works fine on my real project with  latest nuxt-edge. But the example above just give empty error message. All with yarn
https://i.imgur.com/TDeLt96.png

**Comment by yoyo837** [comment]
@aldarund Please take a look at what is wrong with your page, not just console.

**Comment by aldarund** [comment]
@yoyo837 ye i see it now. Although still all works fine with my real project with same version of nuxt :))

**Comment by aldarund** [comment]
the difference i see that in not working example 

  "name": "html-webpack-plugin",
  "version": "2.30.1",

In my real project

  "name": "html-webpack-plugin",
  "version": "3.2.0",

**Comment by rdunk** [comment]
I encountered this and it seems to have been related to an older version of the `html-minifier` package. Forcing an update to the latest version seems to resolve it. In my case 3.5.10 was specified in my `package-lock.json` and now I'm using 3.5.16.

**Comment by manniL** [comment]
Cannot reproduce this with `nuxt-edge@2.0.0-25465851.937ce61`

**Comment by yoyo837** [comment]
No,This problem still exists until now.I'm very sure.
![image](https://user-images.githubusercontent.com/6134547/43830053-08d940f2-9b33-11e8-9602-200da2d5f805.png)

**Comment by manniL** [comment]
@yoyo837 reopened.

**Comment by manniL** [comment]
@yoyo837 Can't reproduce it with your repo linked in the issues and after updating :thinking: 

Could you give a details reproduction instruction?

**Comment by yoyo837** [comment]
@manniL That is a repo small enough to reproduce the problem. This is caused by the #3392 merged, but that PR is trying to fix another issue. Now I'm not sure whether it should be revert.

**Comment by yoyo837** [comment]
I have been having this problem since that PR was merged, every time.

**Comment by manniL** [comment]
@yoyo837 I cloned the repo, updated the dependencies and was able to build nuxt without problems.

**Comment by yoyo837** [comment]
See comment: https://github.com/nuxt/nuxt.js/issues/3411#issuecomment-394224616

Which pkg manager do you use? `npm` or `yarn` ? Use `npm` is work fine.

**Comment by manniL** [comment]
Missed the comment. However, if `NPM` works but `yarn` doesn't,  are you sure it's a Nuxt bug then?

**Comment by aldarund** [comment]
@mannil well, even if it's yarn bug it still should work for people who are using yarn via some workaround. 
It must be something with resolving nested dependency difference on yarn vs npm

**Comment by Atinux** [comment]
Will look into it

**Comment by yoyo837** [comment]
```shell
yarn upgrade
```
This command can make it work fine.
