### ISSUE TITLE
Vue router not work in store action

### ISSUE THREAD

**Issue by furyscript** [nuxt/nuxt.js#3412]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[http://codesandbox.io/#](http://codesandbox.io/#)

### Steps to reproduce

If I put the router redirect into store actions don't work.
I have a general service with vue router instace, and I use it like `sharedService.router.replace({ path: '/login' })`.
It display login for a moment but after, nuxt render the previous url.
I have a large store and I cannot put try catch in every `fetch` methods and listen if error code is `401` and after redirect.

It would be nice if `router` instance works great by running into store actions as side effect. 

This is an old issue open that doesn't have solution: https://github.com/nuxt/nuxt.js/issues/2735

### What is expected ?

It would be nice if `router` instance works great by running into store actions as side effect. 

### What is actually happening?

`router` instace don't work outside component (store action)

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7198">#c7198</a>)</em></sub></div>

**Comment by manniL** [comment]
Assuming the example presented in #2735, you try to redirect the user already on the server side (where `fetch` is executed). This doesn't work out.

So you have several other options:

1. Use middlewares and set localStorage/Cookies for redirect
2. Redirect on client
3. Use a mix of both (similar to what `auth-module` does [here](https://github.com/nuxt-community/auth-module/blob/469f2f85da86d39b9d91a090321316de8ed8d255/lib/core/auth.js#L343)) but that's a bit more complex as you have to pass the context somehow.

**Comment by furyscript** [comment]
Yes this is a repo reproduction: https://github.com/furyscript/nuxt-redirect-error

You need to login, go to inspire page and make sure the first http call is a 200 request. After that try to refresh page (F5 into /inspire) until the http call return a 401 error, so you see that you return to home and not in login page.
