### ISSUE TITLE
Please tell me how to run Nuxt.js + express on Azure Web Apps

### ISSUE THREAD

**Issue by hukusuke1007** [nuxt/nuxt.js#3415]
> Azure WebApps OS:Windows.
node@8.11.1
npm@5.6.0
nuxt@1.4.0

I would like to run Azure Web Apps for Nuxt.js + express framework (nuxt-community / express-template).
Building and deploying with reference to the following article.
https://gist.github.com/benmccallum/226ae1b428157b9d5998a5ba27eadf59

But occur HTTP ERROR 500.
Could this Azure Web Apps(using iisnode) run Nuxt.js + express?
I share my github and my page etc…..

・GitHub
https://github.com/hukusuke1007/nuxt_express_azure

・Pages
https://nuxt-express-test.azurewebsites.net/

・ls wwwroot
> D:\home\site\wwwroot
Mode LastWriteTime Length Name
d----- 6/5/2018 5:40 AM api
d----- 6/5/2018 5:40 AM assets
d----- 6/5/2018 5:40 AM components
d----- 6/5/2018 5:40 AM layouts
d----- 6/5/2018 12:12 PM node_modules
d----- 6/5/2018 5:40 AM pages
d----- 6/5/2018 5:40 AM plugins
d----- 6/5/2018 5:40 AM static
-a---- 6/5/2018 5:40 AM 270 .eslintrc.js
-a---- 6/5/2018 5:40 AM 68 .gitattributes
-a---- 6/5/2018 5:40 AM 130 .gitignore
-a---- 6/5/2018 11:34 AM 2739 build-nuxt.cmd
-a---- 6/5/2018 11:34 AM 2739 deployments
-a---- 6/5/2018 5:40 AM 915 nuxt.config.js
-a---- 6/5/2018 12:12 PM 367906 package-lock.json
-a---- 6/5/2018 12:12 PM 883 package.json
-a---- 6/5/2018 11:02 AM 368 README.md
-a---- 6/5/2018 12:11 PM 842 server.js
-a---- 6/5/2018 12:11 PM 2569 web.config
-a---- 6/5/2018 5:40 AM 194449 yarn.lock

Please give me advices.
The error log is as follows.

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS Detailed Error - 500.1013 - Internal Server Error</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.1013 - Internal Server Error</h3> 
<h4>The page cannot be displayed because an internal server error has occurred.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x0000006d</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://nuxt-express-test:80/server.js</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot\server.js</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,1013,0x0000006d,14393">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p> 
</fieldset> 
</div> 
</div> 
</body> 
</html>

![2018-06-05 21 21 00](https://user-images.githubusercontent.com/29278033/40975883-59beedfe-6907-11e8-940c-5091efd5e277.png)

**Comment by jeliasson** [comment]
@hukusuke1007 Did you have this solved?
