### ISSUE TITLE
Ignore files and folders while cleaning in generate command

### ISSUE THREAD

**Issue by eljass** [nuxt/nuxt.js#3417]
### What problem does this feature solve?

I'm building my app in SPA mode and publishing it in the same folder with second app (which is separate admin panel app). Then I publish this folder to the Firebase hosting.

Right now everytime I build my Nuxt app it completely cleans out the 'public' folder and removes my Admin app's folder from it.

I wish there would be easy way to set folder or file names in nuxt.config and then generate function wouldn't touch those files and folders. Or have I completely missed this option and it is somewhere to be found?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7206">#c7206</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@eljass 
Clean destination folder is a reasonable behaviour for excluding outdated and removed resources.

If you want to keep some files or directories, you may try `hooks`:

`generate:before`: move your file and directories to other temporary place
`generate:done`: move them back

If any concern, please feel free to leave a comment.
