### ISSUE TITLE
Refresh the page, (created) method is executed twice, server once and client once，Demo will also appear

### ISSUE THREAD

**Issue by tansj526** [nuxt/nuxt.js#3419]

**Comment by MiracleYF** [comment]
same issue, any suggestion?

**Comment by MiracleYF** [comment]
found a substitute solution
use mounted() or asyncData()

but still dont know why created() run twice

**Comment by MiracleYF** [comment]
found answer: https://nuxtjs.org/guide/plugins

It is important to know that in any Vue instance lifecycle, only beforeCreate and created hooks are called both from client-side and server-side. All other hooks are called only from the client-side.

**Comment by Leesson** [comment]
why beforeCreated and created are call twice(client and server)? 
Is there some different?
