### ISSUE TITLE
How to add sub component link?

### ISSUE THREAD

**Issue by oguzhanaslan** [nuxt/nuxt.js#342]
Hi.
I am coding for pagination. But I'm having trouble creating components url within the component url.

**Category Post First Page** 
Folder: pages/category/_id.vue
Url : /category/**6**  

route.params.id= 6

This works, no problem. 

But I'm getting an error when, I try to page the category id pagination links. I want to 

**Example Category Pagination Pages**
Folder: pages/category/page/_id.vue .  -> (id.vue pagination current_page count.)
Url: /category/**6**/page/40   

->6 this category id.  
->40 pagination current_page count.

But, always return 404. Where is wrong ? Also what will be the route params id in such a link? Because there are 2 rotating id values.

**Comment by alexchopin** [comment]
Hi,
You need to specify differents params for page id and category id like:
Folder: /pages/category/_cid/page/_id.vue
Url: /category/6/page/40
```js
route.params = {
cid: 6,
id: 40
}
```

**Comment by oguzhanaslan** [comment]
@alexchopin It works. Thank you 👍

**Comment by vanthanhgt89** [comment]
how to using params, query with :category.

**Comment by vanthanhgt89** [comment]
@alexchopin I have same problem.
folder: /pages/product using query for pagination just ok
URL: product?page=value
but with URL: product/cid?page=value . I can't get query

**Comment by vuchl** [comment]
I believe `cid` would now be a param (if your sub page is a dynamic route, else it would be the route path) and `page` a query argument.

**Comment by vanthanhgt89** [comment]
@vuchl How to best, to using pagination with params or query 
if i have product with some page 
and product nested category and sub_category with some page

In document Nuxt-js nested router. I see with _category folder have 2 file 
folder like this:
/_category
   -- index.vue
   -- _sub_category.vue
_category.vue

 (https://nuxtjs.org/guide/routing)
why we need index.vue in _category folder with path: the same

**Comment by vuchl** [comment]
i dont really understand what your goal is. If it is dynamic and static routing mixed then have a look at this: https://github.com/vuchl/static-and-dynamic-routes

**Comment by vanthanhgt89** [comment]
I have folder like this:
pages/
--| _category/
-----| _subCategory/
--------| _id.vue
--------| index.vue
-----| _subCategory.vue
-----| index.vue
--| _category.vue
--| index.vue

I don't understand how to write file index.vue inside _category
I think _category.vue and index.vue the same ???
