### ISSUE TITLE
SVG paths do not render from static

### ISSUE THREAD

**Issue by 1stevengrant** [nuxt/nuxt.js#3423]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://jsfiddle.net/2qzmfh9d/2/](https://jsfiddle.net/2qzmfh9d/2/)

### Steps to reproduce

Change the router base property to be '/here-and-now'

Place the large SVG from the fiddle into the static directory.

Then try to use it in a Vue component by referencing `<svg><use xlink:href="~/static/symbols.svg#arrow--tail--right"></use></svg>`

### What is expected ?

Expect it to render here-and-now/_nuxt/img/symbols.svg#arrow--tail--right

### What is actually happening?

renders ~static/symbols.svg#arrow--tail--right

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7215">#c7215</a>)</em></sub></div>

**Comment by clarkdo** [comment]
`static resources` are no need to add alias `~`, use `/symbols.svg` should be fine.
https://nuxtjs.org/guide/assets/#static

**Comment by 1stevengrant** [comment]
tried that too - doesn't work

**Comment by clarkdo** [comment]
Could please provide a reproducible repo?
