### ISSUE TITLE
Babel 7 Support

### ISSUE THREAD

**Issue by jcarrera** [nuxt/nuxt.js#3430]
### What problem does this feature solve?

I'd like to use the following new features of Babel:
1)  useBuiltIns: 'usage' 
2) esmodules: true
3) The new babel config file

All this to provide optimal bundling for small JS size leading to faster loading.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7223">#c7223</a>)</em></sub></div>

**Comment by ishitatsuyuki** [comment]
The env preset is required through https://github.com/vuejs/babel-preset-vue-app so a PR should be made to that repo.

**Comment by aldarund** [comment]
@ishitatsuyuki isnt it beeing replaced by https://www.npmjs.com/package/@vue/babel-preset-app for babel 7 ?

**Comment by ishitatsuyuki** [comment]
Looks like you are correct.

**Comment by jcarrera** [comment]
@clarkdo @manniL  Fantastic. Thank you. I noticed the PR was merged to nuxt:dev. When is it "released" and under what nuxt version? We're currently on nuxt-edge.

**Comment by manniL** [comment]
@jcarrera It's oin already! As soon as changes are committed to `dev`, a new `nuxt-edge` build will be published :relaxed:

**Comment by husayt** [comment]
@manniL @clarkdo what is the correct way of configuring babel presets going forward?

We used to add this to nuxt.config.js

    babel: {
      presets({ isServer }) {
        return [
          [
            "vue-app",
            {
              targets: isServer
                ? { node: "9.0.0" }
                : { browsers: ["last 2 versions"], ie: 11 }
            }
          ]
        ]
      }
    },

That doesn't work anymore. What is the new recommended way.

**Comment by ishitatsuyuki** [comment]
@husayt [`.browserlistrc`](https://github.com/browserslist/browserslist/blob/master/README.md)

**Comment by clarkdo** [comment]
@husayt 

By default, nuxt will transpile js to `ie 9` supported.

If you're going to customize babel, pleas notice default value of `babelrc` in nuxt is `false`, so maybe you can try to set `build.babel.babelrc: true`

And also how babel retrieve the config file
http://babeljs.io/docs/en/config-files#file-relative-configuration
