### ISSUE TITLE
The file generated by nuxt generate when using css module contains HMR code

### ISSUE THREAD

**Issue by isoppp** [nuxt/nuxt.js#3437]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/isoppp/nuxt-init/tree/bug-when-generate](https://github.com/isoppp/nuxt-init/tree/bug-when-generate)

### Steps to reproduce

1. `vue init nuxt-community/starter-template nuxt-init`
2. `cd nuxt-init`
3. `yarn`
4. Add css module code (https://github.com/isoppp/nuxtinit/commit/d829fffb21c71db365d0f7a4f95c86c4c9b7eb79#diff-b19fa22add3de9cd0b98b05366479d92)
5. `yarn run generate`
6. See dist/_nuxt/pages/index.hash.js and search `hot.accept`

### What is expected ?

HMR code is not included when nuxt generate.

### What is actually happening?

Using css-module (https://vue-loader-v14.vuejs.org/en/features/css-modules.html) in the vue file 
When executing nuxt run generate, the exported file contains resources for HMR.
In addition, local absolute path is described in it

### Additional comments?

* I tried this with v1.4.1. But I could not choose it here.

I have confirmed that I can fix it by adding the following option to lib/builder/webpack/vue-loader.js:7

```
hotReload: this.options.dev,
```

If this is correct, I will create a PR.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7238">#c7238</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce with `nuxt-edge`.
