### ISSUE TITLE
Webpack alias for installed modules not working

### ISSUE THREAD

**Issue by steffans** [nuxt/nuxt.js#3439]
### What problem does this feature solve?

Currently its not possible to alias a installed node module in a SSR build. This is not working because all installed modules are externals using the webpack-node-externals function (see /nuxt-edge/lib/builder/webpack/server.js line 60). 

To make it work you currently have to clear the externals and a add an alias like this:

```js
        extend(config, {isServer}) {

            // Alias module on server
            if (isServer) {
                config.externals = [];
                config.resolve.alias['my-modules'] = 'path/to/alias.js';
            }

        }
```

Aliasing is useful for example to include a different implementation or a empty module for SSR, specially when a existing module is not SSR compatible.

### What does the proposed changes look like?

Maybe a the webpack-node-externals "whitelist" option could be exposed through a nuxt config setting, which would allow to whitelist modules which then can be aliased using webpack.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7241">#c7241</a>)</em></sub></div>

**Comment by manniL** [comment]
@steffans I'd be happy to see a PR for this :relaxed:

**Comment by galvez** [comment]
@clarkdo do you see any problems in offering this? If not, please reopen and I'll add to my experimentation queue.
