### ISSUE TITLE
Problems with asyncData on SPA when the route is reused 

### ISSUE THREAD

**Issue by renanhangai** [nuxt/nuxt.js#3441]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/renanhangai/nuxt-issue-async-data](https://github.com/renanhangai/nuxt-issue-async-data)

### Steps to reproduce

- Enter a page with a conditional asyncData and data options
- Reenter it

### What is expected ?

The asyncData from the old navigation should not be merged on the data when the page is reentered

### What is actually happening?

Every time the page is rendered, the async data is being reused. Maybe causing a memory leak and data inconsistency

### Additional comments?

A simple page example:

```js
export default {
	data() {
		return {
			page_1: false,
			page_2: false,
		};
	},
	asyncData({ route }) {
		const key = `page_${route.query.id}`;
		return { [key]: true };
	}
}
```

When the page is entered with `?id=1`, the data will be `{ page_1: true, page_2: false }` if i navigate away and back to the page with `?id=2`, the data would be `{ page_1: true, page_2: true }`.

But if i refresh it, while on `?id=2`, the data would (rightfully) become `{ page_1: false, page_2: true }`

I believe that the asyncData is being merged with every new visit/render of the page:
```{ ...data, ...asyncDataFromVisit1, ...asyncDataFromVisit2, ...asyncDataFromVisitN };```
And besides the main problem of the data being inconsistent (and probably wrong), that may be a memory leak and cause some problems when the page is visited many times with big enough datas

![Gif](https://github.com/renanhangai/nuxt-issue-async-data/blob/master/view.gif?raw=true)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7243">#c7243</a>)</em></sub></div>

**Comment by dohomi** [comment]
@renanhangai did you try this:
```js
	asyncData({ route }) {
		const key = `page_${route.query.id}`;
		return { currentKey: key };
	}
```

**Comment by renanhangai** [comment]
For now, i've been using an workaround for it but i still think it is a bug. What i meant was:
```js
{
  data: () => ({ something: false, anotherThing: false }),
  asyncData({ route }) {
    if ( route.query.test )
      return { something: true };
    return { anotherThing: true };
  }
}
```

Even though `something` and `antoherThing` are both false on the data function. If i navigate to the view with `?test=1` and then reenter it with no `?test` query, both vars will be true.

The problem is that the component asyncData is not being cleared and will be merged with every new visit to the view. `{ ...data, ...asyncDataFromVisit1, ...asyncDataFromVisit2, ...asyncDataFromVisitN };`
But i expected it to be only: `{ ...data, ...asyncData }`

**Comment by pSchaub** [comment]
I have seen the same issue on our project, we use `nuxt-edge`. This is a bug that results in weird behaviour on our pages and breaks our navigation.

@renanhangai What did you do to workaround this bug?

**Comment by pSchaub** [comment]
We have the same bug in our project; hopefully this will be fixed soon!

**Comment by pSchaub** [comment]
We have the same bug in our project; hopefully this will be fixed soon!
We use `nuxt-edge` (tested on 23/06/2018)

**Comment by galvez** [comment]
Routing (_navigating_) to the same component won't cause a full rerender, hence all state will be retained.

Try using a watcher or restoring the object to defaults on navigation.

```js
export default {
  data() {
    return { currentPage: '' }
  },
  asyncData({ route }) {
    return { currentPage: `page_${route.query.id}` }
  },
  watch: {
    '$route' (to, from) {
      // capture route change
    },
    currentPage (current) {
      // capture prop change
    }
  }
}
```

**Comment by renanhangai** [comment]
@galvez That's not what i meant. When you navigate to a route A that has an `asyncData`, then to a route B, then again to the route A (A and B are two different components). The `asyncData` on the A component will be merged with the result of the 2 visits.

Ex:
route-a.vue
```vue
<template>
    <div>
         <div v-if="first">First time on the page</div>
         <div v-if="second">Second time on the page</div>
     </div>
</template>
<script>
export default {
    asyncData({ route }) {
        return route.query.first ? { first: true } : { second: true };
    }
}
</script>
```

If you go through the following steps
`/route-a?first=1` => `/route-b` => `/route-a`

The data on the RouteA will be { first: true, second: true } (the result of a merge from the two visits, even if the logic on the component does not allow that)

**Comment by galvez** [comment]
@renanhangai thanks for the clarification, I'm reopening.

**Comment by renanhangai** [comment]
I think that this is probably caused by the `applyAsyncData` on  https://github.com/nuxt/nuxt.js/blob/dev/lib/app/utils.js that overwrites the `Component.options.data` and returns the `return { ...data, ...asyncData }`.
But every time the function is called, it returns the old data + the new data (resulting in a possibly leak) so it returns all the old data merged from every visit ever.

The method where i think the issue is coming from:
```js
// https://github.com/nuxt/nuxt.js/blob/dev/lib/app/utils.js
// ...
export function applyAsyncData(Component, asyncData) {
  const ComponentData = Component.options.data || noopData
  // Prevent calling this method for each request on SSR context
  if (!asyncData && Component.options.hasAsyncData) {
    return
  }
  Component.options.hasAsyncData = true
  /* **** This line overwrites the old component data, but every time it is called,
  it keeps returning every older result **** */
  Component.options.data = function () {
    const data =  ComponentData.call(this)
    if (this.$ssrContext) {
      asyncData = this.$ssrContext.asyncData[Component.cid]
    }
    return { ...data, ...asyncData }
  }
  if (Component._Ctor && Component._Ctor.options) {
    Component._Ctor.options.data = Component.options.data
  }
}
```

But i really haven't looked that deep on the code base so i don't know a proper way to fix it.
