### ISSUE TITLE
Why need to add :key at nuxt-child

### ISSUE THREAD

**Issue by Kenada-B** [nuxt/nuxt.js#3445]
Hi guys~!
I saw a ['Nested Routes'](https://nuxtjs.org/examples/nested-routes) example.
In this Example, <nuxt-child> of page/index.vue have ":key" attribute.
And I know that if <nuxt-child> not have ":key" attribute, transition not apply in 'child page'

also, I don't know what value to give at the :key
I tried various methods.
$route.param.id, $route, $route.name, even just $route.
if you give this each value at :key, transition works well.

I'm going to go back. My question is
- Why need to add :key at nuxt-child.
- What value should be given to :key.

p.s. Even if English is not enough, please kindly understand.
       Of course I also got help from Google Translator.
       I will be waiting for your kind answer.
                                                                                               - In Republic of Korea -

**Comment by begueradj** [comment]
There are several users, so you need `:key` which is a prop that is required to determine which **specific** user should be displayed among the others. That **specificity** is achieved by assigning the relevant `user.id` to the `:key` prop
