### ISSUE TITLE
Unable to change host

### ISSUE THREAD

**Issue by pedantix** [nuxt/nuxt.js#3449]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://codesandbox.io/s/238r9x8wxj](https://codesandbox.io/s/238r9x8wxj)

### Steps to reproduce

I am attempting to change the host per documentation, Port is changing without a problem, however, localhost is staying as the hostname. 

### What is expected ?

the result of running nuxt is: 

OPEN  http://localhost:3000 

### What is actually happening?

the result of running nuxt should be: 

OPEN  http://0.0.0.0:3000 

### Additional comments?

This is kind of essential for getting NUXT to run in Docker containers as best that I can understand. Any help is greatly appreciated

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7249">#c7249</a>)</em></sub></div>

**Comment by pedantix** [comment]
Upon further inspection Nuxt's utilities acctually overwrites the display of 0.0.0.0 for some reason, I am not sure if this is important or not but it was deceptive when trying to debug my docker setup. Well appologies for opening a potential false alarm, however the issue still remains the same the open statement is misleading. Best

**Comment by vinczedani** [comment]
As far as I know, It uses the 0.0.0.0 as host, but it prints the localhost, so you can click the link and see your app (you can't get it by typing 0.0.0.0 into your browser)
You can verify it with:
netstat -anpl | grep node
or
netstat -anpl | grep :{YOUR PORT}

**Comment by manniL** [comment]
In the latest `nuxt-edge` version, this is fixed.


![image](https://user-images.githubusercontent.com/640208/43819916-f098e608-9ae4-11e8-99ab-3b83b5e2113b.png)

**Comment by pimlie** [comment]
@manniL This does not seem to be fixed at all. In my case the server address is still being listed as `localhost`. 

Looking at the code the forcible localhost overwrite is even still there: https://github.com/nuxt/nuxt.js/blob/dev/lib/core/nuxt.js#L130
