### ISSUE TITLE
Cached version of nuxt in client's browser

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [nuxt/nuxt.js#345]
Hello, thank you for nuxt, I have an enhancement suggestion.

**Story:** websites have Expires Headers, let's assume on average of one month. Sometimes those static files need to be updated, changed, etc.

**Problem:** If a client has those cached files in his browser, the only way to make one's browser to load a new version of the static files with Expiry Headers set on **before** the expiration date set in one's browser is to change the URL of those files.

**What we, as devs, have to do now:** to safely update a website, we would have to set the expiry headers to 0, if using nginx by doing something like this: `add_header Cache-Control no-cache;`, then we would need to wait for the time of our Expiry Headers to make sure there won't be anyone who opens a website before some of the files in one's browser get expired. Only then, we would be able to update the website and set the Expiry Headers again. We could also change the URLs manually inside **.nuxt** folder, by changing the names and fixing routes in files' contents.

**Offered solution:** In production, nuxt should look for existing files on build and if the new files will have the same name as the old files, the new files should be, for example:
`'oldFileName' + 1`. So every time a build happens in production, it changes the name of let's say `_nuxt/style.css` to `_nuxt/style1.css`, deleting the old one `style.css`, then to `style2.css` and etc. To refresh the count, a developer would just need to delete the `.nuxt` folder, so there is no files to compare to and make the build again.

**Result:** it would allow us to forget about cached files in our clients' browsers, because the changed URLs of those files would make them to load a new file as was needed, preserving the Expiry Headers set in our servers' configurations.

**Comment by awronski** [comment]
Look at this:
https://github.com/nuxt/nuxt.js/issues/218

**Comment by OlzhasAlexandrov** [comment]
@awronski Thank you for referencing it. Then, let me emphasize the differences between these two requests.
- Static files are not only the .css, They are also the .js files. 
- And instead of manually specifying a hash, it should do it by default not only for the .css files, but for all static files that it builds

**Comment by pi0** [comment]
@OlzhasAlexandrov I think chunks name hashing is on the way before 1.0.0 release :) See #218 and [roadmap](https://github.com/nuxt/nuxt.js/projects/1)

**Comment by OlzhasAlexandrov** [comment]
Thank you guys. I don't know whether I should close this issue, or leave it open. So I will leave it up to you

**Comment by Atinux** [comment]
The hash names will be implemented in the 0.10 release :)
