### ISSUE TITLE
Need add watchQuery merge strategy for mixins

### ISSUE THREAD

**Issue by LookinGit** [nuxt/nuxt.js#3452]
### What problem does this feature solve?

Property watchQuery of page overrides watchQuery from mixins, but i want to do merging watchQuery

### What does the proposed changes look like?

```js
import union from 'lodash/union';

Vue.config.optionMergeStrategies.watchQuery = function (toVal, fromVal) {
  return union(toVal, fromVal);
};
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7255">#c7255</a>)</em></sub></div>

**Comment by manniL** [comment]
Have you tried doing this in a plugin? :thinking:

**Comment by LookinGit** [comment]
Yes, currently i use this a strategy in a plugin.
I think this a strategy may be set as default for a property "watchQuery".

**Comment by manniL** [comment]
Nice idea! I'd be happy to see a PR :relaxed:

**Comment by LookinGit** [comment]
ok!
