### ISSUE TITLE
crossorigin attribute not supported in nuxt config head

### ISSUE THREAD

**Issue by warrebuysse** [nuxt/nuxt.js#3458]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://overheid.vlaanderen.be/webuniversum/v3](https://overheid.vlaanderen.be/webuniversum/v3)

### Steps to reproduce

In the nuxt.config.js file add in head: { link: [...] } object a preload link like so:
{ rel: 'preload', as: 'font', href: 'https://ui.vlaanderen.be/3.latest/font/flanders/flanders-sans-light.woff2' crossorigin: 'true' },

### What is expected ?

crossorigin attribute is added to the <link> element in our head.

### What is actually happening?

Terminal throws a SyntaxError: Unexpected identifier on "crossorigin" as it's not known.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7268">#c7268</a>)</em></sub></div>

**Comment by damien-biasotto** [comment]
@warrebuysse just in case, you're missing a coma between the `href` attribute and the `
`crossorigin` one.
