### ISSUE TITLE
Timeout from Nuxt on refreshing the page

### ISSUE THREAD

**Issue by xloading** [nuxt/nuxt.js#3463]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://www.tourharbor.com/](https://www.tourharbor.com/)

### Steps to reproduce

Bug:
1. Open the link (Nuxt app is loaded fine)
2. Hit Refresh - the app is timing out with 500 error code (Nginx gets timeout from Nuxt server side).

"Feature":
1. Hit Refresh
2. Open in another tab another route of the app, e.g. https://www.tourharbor.com/tours/bangkok/3/
3. As soon as the second tab starts loading the first one is also getting processed properly.

### What is expected ?

Refreshing of the page shouldn't cause the app to timeout.

### What is actually happening?

The app times out.

### Additional comments?

Nuxt is working in SSR mode, using router-module with only two pages components - index.vue  and tours.vue
App is started using PM2 on the server, Nginx is used as a proxy.
I haven't used Vuex in this app yet, REST API is hosted on the same server and is called from server side using asyncData()

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7273">#c7273</a>)</em></sub></div>

**Comment by xloading** [comment]
Found another similar issue: https://github.com/nuxt/nuxt.js/issues/3130
Guys it seems to be quite common problem.

Found several more symptoms:
1. When refreshing I often see in Nginx logs 2 or even 3 same requests to my REST API from asyncData()
2. In PM2 logs I found the following stack:
```
TypeError: Cannot read property '1' of null
    at asyncData (server-bundle.js:1754:130)
    at promisify (server-bundle.js:663:15)
    at __WEBPACK_IMPORTED_MODULE_0__Users_xloading_web_tourharbor_com_node_modules_babel_runtime_core_js_promise___default.a.all.Components.map.Component (server-bundle.js:3415:86)
    at Array.map (<anonymous>)
    at module.exports.__webpack_exports__.default (server-bundle.js:3410:159)
    at <anonymous>
```
3. When using the hack loading another route in second tab I sometimes face that sub-components are misplaced between the page routes. I.e. index page sub-component is loaded onto the tours page...

**Comment by Myolisi** [comment]
Did you try using app.$axios.get() instead of just using axios.get()? , so you'd have something like this for example..

async asyncData ({app}) {
          return await app.$axios.get(`/api/getAddresses/${params.update}`)
}

**Comment by xloading** [comment]
@Myolisi I've tried to switch to axios-module as per your suggestion but it doesn't seem to help with my issue unfortunately.

**Comment by xloading** [comment]
Just if anyone is interested, I've created the job with small bounty on Upwork to have this issue investigated and fixed:
https://www.upwork.com/jobs/~017a79027998a18239

**Comment by Myolisi** [comment]
Can you maybe send a bit of code for other leds to see.

**Comment by xloading** [comment]
@Myolisi thanks for your attention!
The problem was with router module configuration, thanks to Vitalii from Upwork who helped me to investigate it.
Closing this one, it's not a bug but purely my mistake.

**Comment by kartojal** [comment]
Hi @xloading can you share the solution? Facing the same issue here with an older version of Nuxt.
