### ISSUE TITLE
How to avoid loading all js file？

### ISSUE THREAD

**Issue by milu2003** [nuxt/nuxt.js#3470]
![image](https://user-images.githubusercontent.com/15957433/41819310-e7127f7a-77f0-11e8-8850-5949970df83c.png)

All the pages of my project's JS are loaded in when they open the front page.

These JS files add up too much and slow down the loading speed.

**Comment by afontcu** [comment]
Hi @milu2003, from your screenshot looks like you are inspecting a development environment. Have you checked your app in production mode? Things would look quite different.

hope it helps!

**Comment by milu2003** [comment]
@afontcu 

Hello, I switch to production mode, or the same.
In addition, I'm using the nuxt.js 1.0 version

You can take a look at the case of the official website：
https://nuxt-auth-routes.glitch.me/ 

The same is the same, all of which are loaded.

**Comment by milu2003** [comment]
Oh, my God, I just upgraded to the latest version. This problem has been solved.
