### ISSUE TITLE
Inject SVG-sprite (compilation)

### ISSUE THREAD

**Issue by andrey-hohlov** [nuxt/nuxt.js#3472]
### What problem does this feature solve?

There are many issues about it, but no final solution.

https://github.com/nuxt/nuxt.js/issues/2764
https://github.com/nuxt/nuxt.js/issues/2539
https://github.com/nuxt/nuxt.js/issues/1087
https://github.com/nuxt/nuxt.js/issues/156

Two problems need to be solved.

First - how to use https://github.com/kisenka/svg-sprite-loader with nuxt already solved https://github.com/kisenka/svg-sprite-loader/issues/233
Just need to setup loaders with `build.extend` option.

The second problem is How to make it works with SSR.
We need sprite in the HTML returns from the server, to avoid icons blinking.

Something like

app.html
```
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    {{ SVG_SPRITE }}
    {{ APP }}
  </body>
</html>
```

But there are no options to make it.

I found a strange ugly solution, but it works.

Create `app.html` in the root:
```
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    <!-- svg-sprite-outlet -->
    {{ APP }}
  </body>
</html>
```

nuxt.config.js
```javascript
module.exports = {
  plugins: [
    '~/plugins/SvgSpriteExtract.js',
  ],
  modules: [
    '~/modules/SvgSpriteInject.js',
  ],
};
```

plugins/SvgSpriteExtract.js
```javascript
const sprite = require('svg-sprite-loader/runtime/sprite.build');

export default (context) => {
  if (process.server) {
    context.res.__SVG_SPRITE__ = sprite.stringify();
  }
}
```

modules/SvgSpriteInject.js
```javascript
module.exports = function SvgSpriteInject() {
  this.nuxt.hook('render:route', (url, result, context) => {
    if (context.res) {
      result.html = result.html.replace('<!-- svg-sprite-outlet -->', context.res.__SVG_SPRITE__ || '');
    }
  });
};
```

In the `SvgSpriteInject.js` sprite is empty. Only 'res' and 'req' properties communicate between this functions.

So, it works for SSR (not for generate). But anyway it's a dirty strange hack.

I think there are two ways:

1. Include svg-sprite-loader to nuxt.
2. Add something like this to generate a template from function https://github.com/nuxt/nuxt.js/issues/1925 (not sure it will work with svg-sprite-loader)

Are there any plans?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7285">#c7285</a>)</em></sub></div>

**Comment by wesssel** [comment]
I am experiencing a similar problem with injecting code.

A solution to add code in the template would be nice.

**Comment by galvez** [comment]
@manniL does nuxt-svg-loader help in any way here?

**Comment by manniL** [comment]
@galvez Unfortunately not as it only provides you the option to import SVGs like Vue SFCs.

**Comment by manniL** [comment]
solved with https://github.com/gaven/nuxt-svg-sprite-module/blob/master/index.js
