### ISSUE TITLE
Unstyled css flashes while using vue-styled-components

### ISSUE THREAD

**Issue by itsmichaeldiego** [nuxt/nuxt.js#3479]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://fork-glider.glitch.me/](https://fork-glider.glitch.me/)

### Steps to reproduce

- Go to the link provided https://fork-glider.glitch.me/

I use `vue-styled-components` for my styles but instead of being rendered properly, they flash the unstyled component before.

Live example here: https://fork-glider.glitch.me/
Source: https://glitch.com/edit/#!/fork-glider

My component looks like:

```

<template>
  <div>
    <app-title>Welcome!</app-title>
    <router-link to="/about">About page</router-link>
  </div>
</template>

<script>
  import styled from 'vue-styled-components';

  const Title = styled.h1`
    font-size: 36px;
    color: red;
  `;

  export default {
    components: {
      "app-title": Title
    }
  };
</script>
```

Here is a quick gif reproducing the issue:
![screen recording 2018-06-26 at 07 53 pm](https://user-images.githubusercontent.com/6419886/41927560-40c755e6-797b-11e8-96c9-425e380893b5.gif)

### What is expected ?

- Title shows styled size and color

### What is actually happening?

- Title flashes original size and color before changing to styled one.

(As this problem is not happening while using plain css, I am wondering if the issue has to do with the run-time of the `script` tag. 🤔)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7294">#c7294</a>)</em></sub></div>

**Comment by AlexeyShaykov** [comment]
same problem

**Comment by clarkdo** [comment]
We need to figure out how `vue-styles-components` handles the SSR.

For now you can wrap with `no-ssr` to avoid server rendering.

```vue

<template>
  <no-ssr>
    <div>
      <app-title>Welcome!</app-title>
      <router-link to="/about">About page</router-link>
    </div>
  </no-ssr>
</template>

<script>
  import styled from 'vue-styled-components';

  const Title = styled.h1`
    font-size: 36px;
    color: red;
  `;

  export default {
    components: {
      "app-title": Title
    }
  };
</script>
```

**Comment by clarkdo** [comment]
I think current `vue-style-component` doesn't completely support SSR yet.

Because they don't handle [`serverRule`](https://github.com/styled-components/vue-styled-components/blob/master/src/vendor/glamor/sheet.js#L90) in [ComponentStyle](https://github.com/styled-components/vue-styled-components/blob/master/src/models/ComponentStyle.js) or [StyledComponent](https://github.com/styled-components/vue-styled-components/blob/master/src/models/StyledComponent.js) now

**Comment by itsmichaeldiego** [comment]
@clarkdo Are you going to open a issue in [vue-styled-components](https://github.com/styled-components/vue-styled-components) or should I?

**Comment by clarkdo** [comment]
@AlexeyShaykov has opened an issue there, so we can track it at that ticket

https://github.com/styled-components/vue-styled-components/issues/52

**Comment by itsmichaeldiego** [comment]
Thanks @clarkdo, I will keep track of this and try to help as much as I can.
