### ISSUE TITLE
Exclude files from webpack bundle (server only javascript)

### ISSUE THREAD

**Issue by briangonzalez** [nuxt/nuxt.js#348]
I am using [xmldom](https://github.com/jindw/xmldom) to shim the document on the server-side. However, I don't need xmldom on the client and would like to exclude it from the webpack bundle.

Here's what I have so far in my [nuxt.config.js](https://github.com/eggplanetio/gus/blob/master/nuxt.config.js#L3-L6):

```js
  build: {
    extend (config, { isDev, isClient }) {
      if (!config.externals) return
      config.externals = config.externals.filter(p => p !== 'xmldom')
    }
  },
```

This results in non-optimal bundles sizes:

<img width="901" alt="screen shot 2017-03-05 at 3 41 55 pm" src="https://cloud.githubusercontent.com/assets/659829/23592741/540ce1a0-01ba-11e7-8cb4-1630baa68b33.png">

**Comment by Atinux** [comment]
Do you have xmldom in your package.json in the "dependencies"?

**Comment by briangonzalez** [comment]
It wasn't before, but now is. Same problem.

https://github.com/eggplanetio/gus/blob/master/package.json

**Comment by Atinux** [comment]
I ran `nuxt build -a` to watch where your bundle size came from and here is the result:

![screen shot 2017-03-06 at 22 41 02](https://cloud.githubusercontent.com/assets/904724/23631206/06104b54-02be-11e7-8e92-48ce7ab7e6ff.png)

The main size is from highlight.js and moment.js, as you can see, the gzipped size is 271KB.

If you want to remove `xmldom` from the client bundle, keep `xmldom` in your `dependencies` and not `devDependencies` and replace [this line](https://github.com/eggplanetio/gus/blob/master/store/parser.js#L5) by:
```js
if (process.SERVER_BUILD) {
```

To exclude some locales files, take a look at http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack

**Comment by briangonzalez** [comment]
Worked liked a charm, thanks @Atinux 🎉
