### ISSUE TITLE
Console error in production

### ISSUE THREAD

**Issue by bellangerq** [nuxt/nuxt.js#3481]
### Version

[1.4.1](https://github.com/nuxt.js/releases/tag/1.4.1)

### Reproduction link

[https://github.com/bellangerq/quentin-bellanger](https://github.com/bellangerq/quentin-bellanger)

### Steps to reproduce

1. Clone this repository: https://github.com/bellangerq/quentin-bellanger
2. Run `npm install`
3. Run `npm run dev`
4. Open the console tab in browser and see the error.

### What is expected ?

There should be no console error in production.

### What is actually happening?

I got this error in my production website (https://quentin-bellanger.com). It seems related to webpack but I can't see what to do to prevent it.

![Console Error](https://cmty.s3.eu-west-1.amazonaws.com/71995937/7c457900-795c-11e8-82a8-4bcbf8ab0578.png)

My Webpack version is  `3.12.0` when running `webpack -v`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7296">#c7296</a>)</em></sub></div>

**Comment by yoyo837** [comment]
Check your chrome adblock extension...

**Comment by bellangerq** [comment]
Indeed! As said in your link, I can confirm that this was fixed in the dev build :)

Thanks for your answer and sorry for the unrelated issue... 🙄
