### ISSUE TITLE
Error build SSR

### ISSUE THREAD

**Issue by daviddsp** [nuxt/nuxt.js#3483]
### Version

[v1.0.0](https://github.com/nuxt.js/releases/tag/v1.0.0)

### Reproduction link

[https://www.pharol.cl](https://www.pharol.cl)

### Steps to reproduce

I have bug, when build my applications production my output not advance.

attached images error.

thanks!
![Captura de pantalla 2018-06-26 a la(s) 17.04.14.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b026b1d0-7984-11e8-82a8-4bcbf8ab0578.png)

### What is expected ?

some solution to this error

### What is actually happening?

I have bug, when build my applications production my output not advance.

attached images error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7297">#c7297</a>)</em></sub></div>

**Comment by XanderLuciano** [comment]
Did you try scrolling..? 

![image](https://user-images.githubusercontent.com/13877593/42792329-91597f1c-8929-11e8-93f8-b0068db3fd1f.png)

Are you talking about with `npm run build` or `npm run dev` etc? Are the errors server side or client side? Did you try using `console.log()/.warn()/.error()` to output information while the server is running? Is it a bug in the build process or the actual site? What information do you need to see?

**Comment by manniL** [comment]
I can't see any error on the screenshot. That's just the list of emitted files from webpack.
