### ISSUE TITLE
NUXT takes a long time to build (up to 6 minutes!)

### ISSUE THREAD

**Issue by amlife180** [nuxt/nuxt.js#3486]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://jsfiddle.net/9r7Lc18a/1/](https://jsfiddle.net/9r7Lc18a/1/)

### Steps to reproduce

The moment I start importing my template to NUXT, the build process  (npm run dev ) start slowing down from 5s up to 6 minutes! which makes it  impossible to use!  

I tried separating the code (Header, Body and Footer) with less than 500 lines in each vue component  but that did not help with the build process. 

I also have tried the new build nuxt-edge without luck, same behavior. 

### What is expected ?

faster build times, it should not take more than few seconds to build. I'm using the same theme with react / web-pack and it works fine. 

### What is actually happening?

I'm using Create-nuxt-app template and it works fine until I start adding my HTML template to it. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7307">#c7307</a>)</em></sub></div>

**Comment by herrdu** [comment]
mark

**Comment by Developerayo** [comment]
@amlife180 your JS and CSS is empty?

**Comment by Developerayo** [comment]
@amlife180 can you update and write your css so it would be easier to understand, ring now its just plane text and links...

**Comment by amlife180** [comment]
Hello Developerayo, 

I did not see a point of adding the JS and CSS as I'm able to produce the issue with basic HTML code. I also tried adding JS, CSS and link all images but that did not help at all. 

If you just try to copy some my HTML code, let us say the header part,  

 <header> ..... </header>   to your NUXT App and save it it, it will take forever to finish.

**Comment by aldarund** [comment]
Same happens on edge. 
Tried that whole html and it didnt compile in 20 minutes, wasnt waiting longer.
Just header section 10+ didnt compile.

**Comment by aldarund** [comment]
Here is 77 lines of html that is compiles more than 5 minutes on nuxt-edge. During 4.30m or so it use only 5% of cpu and memory use stay exactly same at ~160mb. That doesnt happen normally when project compiled without this html memory grows steadily.  If remove top header tag compile time goes down to 3min ( still a lot ). So the more html tags in tree - the longer nuxt compiles it. Each new top level tag adds like 2min.
There clearly some performance hog in nuxt or some underlying library..
<details>
  <summary>Click to expand</summary>
  `<template>
  <header id="m_header" class="m-grid__item m-header " m-minimize="minimize" m-minimize-mobile="minimize" m-minimize-offset="10" m-minimize-mobile-offset="10" >
    <div class="m-header__top">
      <div class="m-container m-container--fluid m-container--full-height m-page__container">
        <div class="m-stack m-stack--ver m-stack--desktop">


          
          <div id="m_header_nav" class="m-stack__item m-stack__item--right m-header-head">
            <div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">


              <div class="m-stack__item m-topbar__nav-wrapper">
                <ul class="m-topbar__nav m-nav m-nav--inline">
                  <li class="m-nav__item m-nav__item--accent m-dropdown m-dropdown--large m-dropdown--arrow m-dropdown--align-center 	m-dropdown--mobile-full-width" m-dropdown-toggle="click" m-dropdown-persistent="1">
                    <div class="m-dropdown__wrapper">
                      <div class="m-dropdown__inner">
                        <div class="m-dropdown__body">
                          <div class="m-dropdown__content">
                            <div class="tab-content">
                              <div id="topbar_notifications_events" class="tab-pane" role="tabpanel">
                                <div class="m-scrollable" data-scrollable="true" data-height="250" data-mobile-height="200">
                                  <div class="m-list-timeline m-list-timeline--skin-light">
                                    <div class="m-list-timeline__items">
                                      <div class="m-list-timeline__item">
                                        <span class="m-list-timeline__badge m-list-timeline__badge--state1-success"/>
                                        <a href="" class="m-list-timeline__text">New order received</a>
                                        <span class="m-list-timeline__time">Just now</span>
                                      </div>
                                      <div class="m-list-timeline__item">
                                        <span class="m-list-timeline__badge m-list-timeline__badge--state1-danger"/>
                                        <a href="" class="m-list-timeline__text">New invoice received</a>
                                        <span class="m-list-timeline__time">20 mins</span>
                                      </div>
                                      <div class="m-list-timeline__item">
                                        <span class="m-list-timeline__badge m-list-timeline__badge--state1-success"/>
                                        <a href="" class="m-list-timeline__text">Production server up</a>
                                        <span class="m-list-timeline__time">5 hrs</span>
                                      </div>
                                      <div class="m-list-timeline__item">
                                        <span class="m-list-timeline__badge m-list-timeline__badge--state1-info"/>
                                        <a href="" class="m-list-timeline__text">New order received</a>
                                        <span class="m-list-timeline__time">7 hrs</span>
                                      </div>
                                      <div class="m-list-timeline__item">
                                        <span class="m-list-timeline__badge m-list-timeline__badge--state1-info"/>
                                        <a href="" class="m-list-timeline__text">System shutdown</a>
                                        <span class="m-list-timeline__time">11 mins</span>
                                      </div>
                                      <div class="m-list-timeline__item">
                                        <span class="m-list-timeline__badge m-list-timeline__badge--state1-info"/>
                                        <a href="" class="m-list-timeline__text">Production server down</a>
                                        <span class="m-list-timeline__time">3 hrs</span>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                </ul>
              </div>
            </div>
          </div>
          


        </div>
      </div>
    </div>
  </header>
</template>

`
</details>

**Comment by aldarund** [comment]
https://github.com/vuejs/vue-loader/issues/1352

**Comment by Developerayo** [comment]
Check this out: https://github.com/Developerayo/awesome-nuxtjs

**Comment by Developerayo** [comment]
@aldarund how did you run it on your "https://codepen.io/aldarund/pen/RJEXvG"

**Comment by aldarund** [comment]
@Developerayo its not related to nuxt. You can create empty new vue project with @vue/cli and replace app.vue with that html from codepen and u will get 5+ min compile time. Here is empty project with that 1 file that was created via vue/cli -> https://www.dropbox.com/s/crjqyk7uq23bn31/my-projectx.zip?dl=0

**Comment by Developerayo** [comment]
lol @aldarund now i see. Will check for possible errors. Will get back to you this evening with a solution. Trust me :)

**Comment by DeanKamali** [comment]
Any update on this issue? 

Thanks

**Comment by aldarund** [comment]
@DeanKamali not a nuxt fault. Blame prettier , vote here and comment , maybe it will make any difference...
https://github.com/prettier/prettier/issues/4784

**Comment by cnlawrence** [comment]
Is there an update with nuxt or prettier? 13 minute build here.

Has anyone successfully reverted prettier back to a previous version to resolve the issue?

**Comment by DeanKamali** [comment]
@cnlawrence  I had to give up on nuxt for the time being and started using next.js instead : (

**Comment by manniL** [comment]
I've tested the build times with a fresh project and the latest `nuxt-edge` build and they are decent! (~5-7 seconds)

![image](https://user-images.githubusercontent.com/640208/43821272-fe7621ec-9ae8-11e8-8650-b16109504ee9.png)

(Only `@nuxtjs/pwa` was included).

Build time increases with extra plugins like: `sass`, `typescript`, `prettier` and so on but that'll happen in any build chain.

**Comment by Developerayo** [comment]
True.
