### ISSUE TITLE
How can I access another method within the asyncData method?

### ISSUE THREAD

**Issue by lbavendanos** [nuxt/nuxt.js#3488]
I understand that in nuxt in the asyncData method we do not have access to the variable this. Then how can I access the created methods

```
<script>
export default {
    asyncData() {
        this.foo();
    },
    methods: {
        foo(){
            console.log('bar');
        }
    }
}
</script>
```
How should I call methods I need within the asyncData? o What is the correct way to do it?

**Comment by benoitemile** [comment]
duplicate, to close

**Comment by docmattman** [comment]
@benoitemile, you mentioned this is a duplicate, but where can I find the duplicate issue?

I'm looking for more info on this.  I have two `pages` that `extends` a common component.  In the `asyncData` method I'd like to be able to call one of my defined methods (i.e. `foo` in the example above).

Using `extends` in my page would allow me to overload the `foo` method in my page file with different logic from the extended component file.  It would be nice to be able to call a defined method from `asyncData`.

Any more info on this issue?

**Comment by benoitemile** [comment]
you can find the original issue there : https://cmty.app/nuxt/nuxt.js/issues/c7313
