### ISSUE TITLE
webpack proxy not work

### ISSUE THREAD

**Issue by yjjn** [nuxt/nuxt.js#349]
build: {
        extend (config, ctx) {
          if (!ctx.isClient) {
            config.devServer = {
              proxy: {
                 '/api/*': {
                  target: 'http://127.0.0.1:8080/',
                  secure: false
                 }
              }
            }
           } 
        }
      }

**Comment by alexchopin** [comment]
Can you explain more about your issue?

**Comment by yjjn** [comment]
英文不好啊。English is not good
I want to use webpack to achieve the function of proxy API。
Nuxt configuration webpack using extend。
I configured as shown above。
But API has been rendered by nuxt。404

**Comment by lilien1010** [comment]
不配置https  试试

**Comment by yjjn** [comment]
不行啊，这里配置有问题，但是不是https的问题。
No, ah, this configuration has a problem, but not a HTTPS problem

英文都是金山翻译的。哈哈

**Comment by longzhaobi** [comment]
解决了没？我也在研究咋配置

**Comment by Duuuuuke** [comment]
有解决的吗   求参考。。

**Comment by longzhaobi** [comment]
@Duuuuuke 我之前是需要跨域才来这，后来才发现根本就不用配置代理，通过express去请求JAVA后端，因为已经脱离了浏览器就没有跨域的问题了。

**Comment by piyushchauhan2011** [comment]
I feel like still struggling with setting up `webpack` proxy. Although we can use the express backend to send request to other services but seems like a redundant task ? Is the `webpack` proxy is still working @longzhaobi @alexchopin

**Comment by c4milo** [comment]
I don't think it is working, the request seems to be handled by nuxt always. I even tried Nuxt's proxy module and it was useless for custom matchings >.<

**Comment by yoyo837** [comment]
So, is there any other solution?

**Comment by levy9527** [comment]
look at this
[https://github.com/nuxt-community/axios-module](url)

**Comment by gauseen** [comment]
@longzhaobi 
我是纯静态网站，请求后台就会跨域，怎么弄

**Comment by yoyo837** [comment]
My case:
In `server/index.js`
```js
if (config.dev) {
  router.all(/\.do$/, proxy({
    target: 'http://localhost:8082/portal/',
    // changeOrigin: true,
    ws: true
  }))
}
```

**Comment by gauseen** [comment]
已解决(solved):
look at this:
[](https://github.com/gauseen/nuxt-proxy)

**Comment by ranwawa** [comment]
还是要先把洋文学好了来.只会哑巴英语真的有点恼火...哎
