### ISSUE TITLE
Using jquery with nuxt: Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by elena-dev** [nuxt/nuxt.js#3499]
I have this in my nuxt.config.js:
```
plugins: [
    { src:'~/plugins/js/jquery-3.3.1.min.js', },
    { src:'~/plugins/js/bxslider.min.js', },
]
  
```
But, I still get this error:
TypeError
Cannot read property 'createElement' of undefined
What am I doing wrong?

**Comment by nicoladl** [comment]
Maybe you can try this:

1 - install jquery via npm
```
npm i jquery
```

2 - add to vendor in nuxt.config.js
```
vendor: ['jquery']
```

3 - add to pages/layout:
```
import $ from 'jquery'
```

Or maybe try to use vanilla.

**Comment by elena-dev** [comment]
it did not solve my problem

**Comment by nicoladl** [comment]
Similar issue:
https://cmty.app/nuxt/nuxt.js/issues/c308

Be sure to use jquery inside mounted hook
