### ISSUE TITLE
How can i add Jest to Nuxt.js?

### ISSUE THREAD

**Issue by msudgh** [nuxt/nuxt.js#350]
Hey guys,
How can i add Jest to Nuxt.js?

**Comment by alexchopin** [comment]
Jest doesn't support Vue.js, so you cannot use it with Nuxt.

**Comment by Knovour** [comment]
You could add these two packages to make it work.

- [jest-vue-preprocessor](https://github.com/vire/jest-vue-preprocessor)
- [jest-serializer-html](https://github.com/rayrutjes/jest-serializer-html)
