### ISSUE TITLE
Lazy/progressive image loading module

### ISSUE THREAD

**Issue by westwick** [nuxt/nuxt.js#3503]
### What problem does this feature solve?

I'd love to have a module as easy to use as gatsby-image available for nuxt, to make it super easy to add responsive images, support webp when available, and provide low filesize svgs to load initially then progressively load up the higher quality formats.

### What does the proposed changes look like?

I'm very interested in creating a nuxt module that works similar to gatsby-image and gatsby-image-sharp plugins for the gatsby ecosystem, but without the graphql stuff. So I envision this as two projects probably; a nuxt module to handle the webpack modifications and generate the necessary image files, and then a vue-component to handle the progressive and lazy loading of the images, optionally checking for webp support, and loading the right higher quality image based on screen size / pixel density.

So my main questions are:

Does anything like this exist already? I've looked around and couldn't find anything, but thought I would double-check in case I missed it

What should the strategy be around generated assets? I know gatsby-image doesn't work with netlify-cms and images in the /static folder, but I think that is because of the graphql constraints. I don't know if that will be a problem here, but I'm also wondering about build times, if I have to process all the images and regenerate them on every build, that will drastically slow down the build. But this needs to happen, unless we are commiting the generated assets back into git, right? But that doesn't seem like something that should be happening in the build, and I don't see any way to utilize some kind of cache system here. I was also thinking of creating something like a lambda endpoint to do the image processing and comitting back to git, or putting it in s3 and updating the path in the content markdown, but then that is outside the scope of a nuxt module and not reusable. I think I'm leaning towards just generating everything every time at build, and allowing the nuxt-module to specificy certain paths or file name regex to specify just the images to operate on. I also want to make sure that all assets are registered properly within nuxt, to take advantage of things like PWA module. Any other ideas here? Am I thinking about anything wrong?

I'm also just wondering in general, would this be a useful module that others might use too? I really like the tracedSVG progressive loading example in gatsby-image for example. I'd really appreciate any insight or feedback anyone has!

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7336">#c7336</a>)</em></sub></div>

**Comment by galvez** [comment]
@westwick for now I'd check [vue-lazyload](https://github.com/hilongjw/vue-lazyload) -- there are plans to hook this as a Nuxt-specific module post-2.0. We'll see.
