### ISSUE TITLE
porting nuxt starter template code express code

### ISSUE THREAD

**Issue by pulkitnandan** [nuxt/nuxt.js#351]
I've tried everything to make this change withour rewriting the whole code in the new template and I challenge that it's impossible, somehow somewhere old cold is triggering from some shady locaton where previous created .nuxt folder persist.

Following is the error log, you just need to use config package to reproduce this error.

ERROR in ./~/config/lib/config.js
Module not found: Error: Can't resolve 'fs' in '/home/rohitn/rnr/node_modules/config/lib'
 @ ./~/config/lib/config.js 22:17-30
 @ ./plugins/mp-api.js
 @ ./store/index.js
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

ERROR in ./~/config/lib/config.js
Module not found: Error: Can't resolve 'hjson' in '/home/rohitn/rnr/node_modules/config/lib'
 @ ./~/config/lib/config.js 1017:14-30
 @ ./plugins/mp-api.js
 @ ./store/index.js
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

ERROR in ./~/config/lib/config.js
Module not found: Error: Can't resolve 'toml' in '/home/rohitn/rnr/node_modules/config/lib'
 @ ./~/config/lib/config.js 1025:13-28
 @ ./plugins/mp-api.js
 @ ./store/index.js
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

ERROR in ./~/config/lib/config.js
Module not found: Error: Can't resolve 'cson' in '/home/rohitn/rnr/node_modules/config/lib'
 @ ./~/config/lib/config.js 1032:13-28
 @ ./plugins/mp-api.js
 @ ./store/index.js
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

ERROR in ./~/config/lib/config.js
Module not found: Error: Can't resolve 'properties' in '/home/rohitn/rnr/node_modules/config/lib'
 @ ./~/config/lib/config.js 1043:16-37
 @ ./plugins/mp-api.js
 @ ./store/index.js
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

ERROR in ./~/config/lib/config.js
Module not found: Error: Can't resolve 'x2js' in '/home/rohitn/rnr/node_modules/config/lib'
 @ ./~/config/lib/config.js 1049:12-27
 @ ./plugins/mp-api.js
 @ ./store/index.js
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

**Comment by Atinux** [comment]
I'm sorry but I don't understand what you are trying to tell us.

The error is related to your code changes directly and not nuxt related.

Try to undo your changes to see where the problem came from.
