### ISSUE TITLE
store state immutable Map get changed to Observer object 

### ISSUE THREAD

**Issue by victor-perez** [nuxt/nuxt.js#3511]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/victor-perez/storebug](https://github.com/victor-perez/storebug)

### Steps to reproduce

Change any store state to a immutable Map

See my example code
* `git clone https://github.com/victor-perez/storebug`
* `cd storebug`
* `npm install` or `yarn`
* `npm run dev` or `yarn dev`
* open browser at `http://localhost:3000`

### What is expected ?

That both in `SSR` and in the browser the store state keep being a `Map` and not change to a Object.

### What is actually happening?

When you use immutable `Map` as state it is in `SSR` still a `Map` but in the browser it changed to a `Observer` object
This mean that non of the immutable Map function anymore work in the browser.

If you set `mode` to `spa` this problem doesn't occurred , it only occurring when `SSR` is enabled   

![Screenshot_4.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/77fc9790-8166-11e8-9630-971be8d91be2.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7348">#c7348</a>)</em></sub></div>

**Comment by manniL** [comment]
Likely `serialization` is the reason for this.

See #3579

**Comment by victor-perez** [comment]
I fixed it by writing a `vuex` plugin [vuex-immutable-replace-state](https://www.npmjs.com/package/vuex-immutable-replace-state)
