### ISSUE TITLE
Async data not being called on link click

### ISSUE THREAD

**Issue by bmxguy100** [nuxt/nuxt.js#3512]
### Version

[v1.4.1](https://github.com/nuxt.js/releases/tag/v1.4.1)

### Reproduction link

[https://github.com/bmxguy100/appjackstudio.com](https://github.com/bmxguy100/appjackstudio.com)

### Steps to reproduce

0. Install dependency (yarn)
1. Run yarn dev (or mom run Dev)
2. Go to localhost:3000/blog and click on a blog post

![Capture 1.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2aead850-82dc-11e8-afec-b3fd21885a87.PNG)

### What is expected ?

The asyncData method should be called and the blog post should be shown

![Capture 3.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/349ed2c0-82dc-11e8-afec-b3fd21885a87.PNG)

### What is actually happening?

A 404 error happens, but the asyncData triggers and you can see the blog post after a page refresh

![Capture 2.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/32fe6930-82dc-11e8-afec-b3fd21885a87.PNG)

### Additional comments?

I get the same result serving from nuxt build/start and nuxt generate

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7352">#c7352</a>)</em></sub></div>

**Comment by nmfzone** [comment]
It's not a bug. You **should** return a promise or using async/await.

Here is the documentation: https://nuxtjs.org/guide/async-data/

**Comment by bmxguy100** [comment]
@nmfzone I have used it without promises in the past, and adding the async keyword didn't seem to fix it

**Comment by aldarund** [comment]
i think require.context dont really work on client

**Comment by manniL** [comment]
@aldarund That's why it isn't executed on client side. `asyncData` is called on the server side only.

@nmfzone I think the usage is fine like this. You could swap `required` with `await import` and make the method `async`, but it still shows the error message.

**Comment by aldarund** [comment]
@manniL no, you are wrong. asyncData called on client too.

**Comment by manniL** [comment]
@aldarund Whoops, you are right. :sweat_smile: However, the `require.context` part looks like it is working properly.
