### ISSUE TITLE
Extract the manifest file to make vendor.js be cached longer

### ISSUE THREAD

**Issue by treblam** [nuxt/nuxt.js#352]
As described in this documentation: https://webpack.js.org/guides/code-splitting-libraries/. In the current version of nuxt, if I add this config to webpack plugins, there is an error claiming "Multiple assets emit to the same filename nuxt.bundle.js":
```
new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
})
```

**Comment by alexchopin** [comment]
This is because we [preset this webpack plugin](https://github.com/nuxt/nuxt.js/blob/c5b8d16a2b7ebe8c83f0f66b69708d649a6c6d80/lib/webpack/client.config.js#L50), you can use [extend option](https://nuxtjs.org/faq/extend-webpack) to overwrite Nuxt default config.

**Comment by treblam** [comment]
Thanks, I will try it later.
