### ISSUE TITLE
Custom Loading doesn't work with static routes.

### ISSUE THREAD

**Issue by canyoudev** [nuxt/nuxt.js#3526]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://nuxtjs.org/examples/custom-loading](https://nuxtjs.org/examples/custom-loading)

### Steps to reproduce

I was using the example of custom Loading instead of progress bar. 
In my app I have dynamic routes, like `_slug.vue` and 1 static `test.vue` page on the same route level.

The problem is, Loading works only when I am navigate between dynamic routes. If I navigate to static route, there is no Loading (but it works when I leave this static route). Have no idea why this happening, but this looks like the bug. 

### What is expected ?

I expect Loading working on dynamic and static routes

### What is actually happening?

Not working when I navigate to static route from dynamic route

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7373">#c7373</a>)</em></sub></div>

**Comment by aldarund** [comment]
are u using nuxt-link/router-link to navigate to your static route?

**Comment by canyoudev** [comment]
Hi. This is my navigation snippet

```html
<ul class="menu-list">
          <li class="menu-item" :class="`header-${section.slug}`" v-for="section in sections" :key="section._id">
            <nuxt-link :to="`/${section.slug}`" class="menu-link">
              <span>{{ section.name }}</span>
            </nuxt-link>
          </li>
 </ul>
```

One of `sections` is actually my static file.
