### ISSUE TITLE
How to set enviroment while running nuxt?

### ISSUE THREAD

**Issue by jrainlau** [nuxt/nuxt.js#353]
Hi, when I am using `nuxt`, I would like to set different enviroment  in order to use different test host.

For example, I have 3 host: `http://test1.me`, `http://test2.me`, `http://test3.me`, and I would like to set these host by passing arguments when I run `npm run dev`, such as `npm run dev -- -m=test1`, but it doesn't work.

Are there any way to solve my questrion? Thanks a lot!

**Comment by alexchopin** [comment]
Hi, you can use [process.env.BASE_URL](https://nuxtjs.org/api/configuration-env).

**Comment by scottgrayson** [comment]
The docs explain how to set a default if `process.env.BASE_URL` is undefined but where does `process.env.BASE_URL` get set in the first place?
