### ISSUE TITLE
Please support SRI

### ISSUE THREAD

**Issue by small-sunshines** [nuxt/nuxt.js#3539]
### What problem does this feature solve?

During my development with Nuxt.js, I found that there is no way to put Nuxt.js into a way to apply subresource integrity or nonce to eliminate loopholes in CSP configuration.

There was a way to use the Webpack plugin, but they did not render subresource integrity with the client rendering.

For this reason, the page is normally loaded using the 'unsafe-inline' option, which is not recommended for configuring CSP.

### What does the proposed changes look like?

If you apply it, you can expect to improve the security of Nuxt.js.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7392">#c7392</a>)</em></sub></div>

**Comment by manniL** [comment]
Could you describe what would need to be done to fulfill this feature request? :thinking:

**Comment by small-sunshines** [comment]
yes, right.

**Comment by manniL** [comment]
I think you can already do this with [this webpack plugin](https://github.com/waysact/webpack-subresource-integrity). Haven't tried it though, but it might be worth a short ;)

**Comment by small-sunshines** [comment]
Oh. It is a successful solution.

![image](https://user-images.githubusercontent.com/11470513/43037607-e7503112-8d49-11e8-97c5-a59159771a68.png)

But this error occurs.

![image](https://user-images.githubusercontent.com/11470513/43037619-086a6d4a-8d4a-11e8-8450-dd828769c528.png)

I think this is probably due to this part. Another part is that modules like adsense do not support sri.

**Comment by small-sunshines** [comment]
![image](https://user-images.githubusercontent.com/11470513/43037634-2e65e3e4-8d4a-11e8-8e75-378dcd9d1fc6.png)

However, some scripts are well suited for sri.

**Comment by small-sunshines** [comment]
I thought, SRI can be declared in CSP like sha256-hash even if it is not declared in the script tag. And I am using Nuxt.js in conjunction with express.js. If you have a way to create a hash list, I thought you could write a CSP using that hash. Can you find out if there is a way?

**Comment by small-sunshines** [comment]
![image](https://user-images.githubusercontent.com/11470513/44002982-4ff18e08-9e86-11e8-90d9-2a6d3eb62cee.png)

Looking at the Nuxt.js source, Nuxt.js itself already has a part for CSP. The site worked well even though I tried to run it on Express.js.

![image](https://user-images.githubusercontent.com/11470513/44003022-ddcfa836-9e86-11e8-9962-a00ffac21a05.png)

But there is a bit of a gap in this part. The user can not add the desired CSP conditional statement. This section needs revision.

For example, in my case, the script for `pagead2.googlesyndication.com` `www.google-analytics.com` requires permission.

![image](https://user-images.githubusercontent.com/11470513/44003055-5f8986b2-9e87-11e8-80c8-38155ef60731.png)

And you have to tell them that you can configure for CSP like this. Maybe I could not see this in the documentation.

**Comment by small-sunshines** [comment]
![image](https://user-images.githubusercontent.com/11470513/44003106-4be59d34-9e88-11e8-92b3-67875645be83.png)

First, I found documents related to CSP. However, there is no description, and it is under the render option.

If you do not read all the documentation, it will be hard to find a commentary on CSP.

Second, if there was a document that summarized what functions were supported at once, it would not happen anymore.
