### ISSUE TITLE
Initialize a script widget out of the Vue root

### ISSUE THREAD

**Issue by warrebuysse** [nuxt/nuxt.js#354]
We have a javascript widget (global header & global footer that is used on countless websites) that is embedded by a script tag inside a div just after the opening `<body>` tag (global header) and before the closing `<body>` tag (global footer).

```
<div style="min-height:44px;" id="vlaanderen-header">
    <!-- Start global header-->
    <script type="text/javascript" src="//widgets-dev.hbplus.be/widget/live/5ec9879de3e5488bba00a8c1c63b030e"></script>
    <!-- End global header-->
  </div>
```

Is it possible to add those in a Nuxt project outside the Vue root? 

And as a follow-up question. Is it possible to include <script> tags for eg: a Twitter Timeline embed? I presume that is possible?

**Comment by alexchopin** [comment]
Hi, this is possible, you can see this [answer](http://stackoverflow.com/questions/8578617/inject-a-script-tag-with-remote-src-and-wait-for-it-to-execute) or how we use it on [nuxtjs.org repo](https://github.com/nuxt/nuxtjs.org/blob/master/components/CarbonAds.vue).

**Comment by warrebuysse** [comment]
I implemented it exactly as used in the nuxtjs.org repo, but I run into the following error(s).

1. [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
warn @ vue.runtime.esm.js:559

2. 70f9c938e7d94f4796131909296812c4:1 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

```javascript
<template>
  <div ref="globalfooter"></div>
</template>

<script>
  export default {
    name: 'global-footer',
    mounted () {
      const script = document.createElement('script')
      script.setAttribute('type', 'text/javascript')
      script.setAttribute('src', '//widgets-dev.hbplus.be/widget/live/70f9c938e7d94f4796131909296812c4')
      this.$refs.globalfooter.appendChild(script)
    }
  }
</script>

```

I understand the concept of server and client being out of sync, but don't have a clue how to tackle the issue. This gets you in trouble with all javascript libraries I presume? What if you want to use the official Twitter feed plugin? That one writes in the window as well?

**Comment by Atinux** [comment]
Hi @warrebuysse 

You can use the [head elements](https://nuxtjs.org/api/configuration-head) in your `nuxt.config.js`:

```js
module.exports = {
  head: {
    script: [
      { type: 'text/javascript', src: '//widgets-dev.hbplus.be/widget/live/70f9c938e7d94f4796131909296812c4' }
    ]
  }
}
```

If it's your own widget, your should not use `document.write`, see [this answer](http://stackoverflow.com/questions/24297829/execute-write-on-doc-it-isnt-possible-to-write-into-a-document-from-an-asynchr).

**Comment by gijo-varghese** [comment]
@warrebuysse are building something that is embeddable in other sites? I'm in similar situation. Have you implemented it?

https://github.com/nuxt/nuxt.js/issues/2518 this is the issue that I've created
