### ISSUE TITLE
Don't execute asyncData in the vue router beforeEach

### ISSUE THREAD

**Issue by gotoin** [nuxt/nuxt.js#3541]
### What problem does this feature solve?

cache !
i need realize forward refresh and backward do not refresh

now the asyncData is called every time before loading the component。

i need a configuration that sets the asyncData life cycle

thanks

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7397">#c7397</a>)</em></sub></div>

**Comment by manniL** [comment]
Your descriptions lack important information. Could you please add a more detailed description of what exactly your problem is?

If I understand it correctly you are building a Pagination and want an `asyncData` that isn't called on every request. Right?

If so, you can use `query parameters` for building it, as `asyncData` won't execute on query parameter change by default.

Example: `/posts?page=1`
This could be a

**Comment by gotoin** [comment]
@manniL i want to  A -> B page don't called asyncData

**Comment by manniL** [comment]
This sounds like an X-Y Problem. Could you tell us what your plan behind that feature is? :thinking:

**Comment by gotoin** [comment]
@manniL i need client cache, 

such as:
 1. open A, call A asyncData get data
 2. A to B, save A vnode, call B asyncData get data
 3. back
 4. A don't call asyncData, pop A vnode

so i need to be able to control asyncData

**Comment by gotoin** [comment]
Please forgive my unclear expression for my poor English, thanks

**Comment by manniL** [comment]
You could use `fetch` together with checking if XYZ is in store already.

Like: 
Open A, load `A.XYZ` in store through `fetch`
Open B, load `B.XYZ` in store through `fetch`
Open A, see `A.XYZ` is in store, do nothing.

**Comment by gotoin** [comment]
@manniL 

The fetch method is used to fill the store before rendering the page, it's like the asyncData method except it doesn't set the component data.

i don't want all page use store,  and i need ssr.

**Comment by gotoin** [comment]
I don't think asyncData should be fixed beforeEach, maybe can let the developer decide whether to call asyncData, 
Like the keep-alive, not call created mounted....

**Comment by zealot09** [comment]
@gotoin @manniL 
U can add a popstate listener before vue router

```
let __IsPopState__ = false;
window.addEventListener('popstate', e => {
  __IsPopState__ = true;
});
```

then check __IsPopState__  in beforeResolve and decide whether should execute asyncData or not,
and reset __IsPopState__

it can solve the $router.back & asyncData problem

**Comment by gotoin** [comment]
@zealot09 Sometimes asyncData needs to be called and sometimes it doesn't need to be called.

**Comment by gotoin** [comment]
@zealot09 And beforeResolve is called after beforeEach
