### ISSUE TITLE
How integrate firestore using nuxt?!

### ISSUE THREAD

**Issue by eeerrrttty** [nuxt/nuxt.js#3542]
how can i configure the nuxt project to push data from firestore ???

The documentation is very fuzzy relating to this.

in a normal vue.js we just call it by:

  created () {
    firebase.initializeApp(configuration)
}

inside the main.js

Once we are creating the app totally server side, how can it acess itself to pass data to vuex (to show to user) ?!

**Comment by lupas** [comment]
Hi @eeerrrttty 
I had difficulties myself but got it to work quite nicely, so I wrote an article on Medium explaining how to do it step by step:

Here's the article:
[https://medium.com/@pascalluther/nuxt-js-v1-firestore-and-ssr-73e3140574fc](https://medium.com/@pascalluther/nuxt-js-v1-firestore-and-ssr-73e3140574fc)
 
And here is the example code on GitHub:
[https://github.com/lupas/nuxt1-firestore](https://github.com/lupas/nuxt1-firestore)

I super happy with Nuxt.js and Firestore, works like a charm for me!
Hope this helps :)

**Comment by apro23** [comment]
Hi @lupas can you also make a tutorial for nuxtjs 2 and firestore? thank's in advance :)

**Comment by lupas** [comment]
@apro23 
It should work pretty much the same as with v1, no big changes. However, I'll create an article & GitHub repo for v2 to make it easy to follow with v2, good idea =)

**Comment by apro23** [comment]
@lupas thank you very much sir! :) I don't know where to start in nuxt 2 and firebase. I can't also find a tutorial in youtube and google. I found some in udemy but I have to pay $12. if you would create an article you may help a lot of beginners :)

**Comment by lupas** [comment]
> @lupas thank you very much sir! :) I don't know where to start in nuxt 2 and firebase. I can't also find a tutorial in youtube and google. I found some in udemy but I have to pay $12. if you would create an article you may help a lot of beginners :)

glad to hear that :) I'll publish the article for v2 by Friday! Hope you can wait until then :)

**Comment by RubenConde** [comment]
@lupas How can I integrate the configuration of your post with Vuex in Nuxt.js?

**Comment by lupas** [comment]
@RubenConde Sorry for the late response.

You can access this.$fireDb (and all the others) in your Vuex store actions and from there commit to the store.

Hope that helps.

**Comment by hkchakladar** [comment]
@lupas how to deploy this to firebase hosting with cloud functions? linked with this article https://medium.com/likecoin/quick-nuxt-js-ssr-prototyping-with-firebase-cloud-functions-5277553610a8

I tried to mix your v2 with above article, but it's not recognising firestore.
