### ISSUE TITLE
Configuration build.extend is throwing deprecation warnings when using isDev, isClient, and isServer

### ISSUE THREAD

**Issue by gwardwell** [nuxt/nuxt.js#3547]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://gist.github.com/gwardwell/38c1fe1fc81add4beeb5e4bfcd28e701](https://gist.github.com/gwardwell/38c1fe1fc81add4beeb5e4bfcd28e701)

### Steps to reproduce

In `nuxt.config.js` add `build.extend()`. If you use `isServer`, `isDev`, or `isClient` as outlined in the Nuxt docs (See: https://nuxtjs.org/api/configuration-build/#extend ), you will get deprecation warnings. Changing references to the proper `process` properties, such as `process.server` will not work because those process properties do not exist in this context.

### What is expected ?

Either `process.server`, `process.client`, etc. will not be undefined OR using `isServer`, `isClient, etc. will not produce deprecation warnings.

### What is actually happening?

`process.server`, etc. are undefined.
`isServer`, etc. produce deprecation warnings.

### Additional comments?

My nuxt application is functioning as expected. The only reason this is an issue is due to the console noise it generates. It's also concerning if, in the future, those variables (isServer, etc.) go away and are not properly replaced in this context.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7402">#c7402</a>)</em></sub></div>

**Comment by manniL** [comment]
I've tried to reproduce the issue but when using Nuxt version 1.4.1 I can't see any deprecation warnings :thinking: 

```
build: {
    extend (config, { isDev, isServer, isClient }) {
       console.log({isDev, isServer, isClient})
    }
  }
```

**Comment by gwardwell** [comment]
@manniL I upgraded to 1.4.1 and was still getting the error. After digging, build.extend (the only place I was using `isServer` and `isClient`) was a red herring. It's actually a module (Vue Apollo) that I'm passing my context to that is using those deprecated properties. I'll have to find a way around that issue, but I'll close this issue as it is unrelated to Nuxt itself. Sorry!
