### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by Songzhiguo** [nuxt/nuxt.js#3548]
const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null

SyntaxError: Unexpected token ...

**Comment by juniorgarcia** [comment]
Duplicate: [#c7411](https://cmty.app/nuxt.js/issues/c7411 "nuxt.js - SyntaxError: Unexpected token ...") 

Also, try to create better topic names. This one says nothing about the problem.
