### ISSUE TITLE
How to pronounce Nuxt?

### ISSUE THREAD

**Issue by inouetakuya** [nuxt/nuxt.js#355]
I have a scheduled introduction of Nuxt.js at the big meetup in Japan. 

But I do not know how to pronounce `Nuxt`. 😇 

* nʌkst ?
* nukst ?

or anything else?

Please let me know.

**Comment by alexchopin** [comment]
Hi, that's great! I would love to see some pictures or slides after you did it ;) 
And it's more nʌkst :)

**Comment by inouetakuya** [comment]
Great thank you :pray:

**Comment by inouetakuya** [comment]
@alexchopin 

Hi, I introduced Nuxt.js at the meetup which 100 people joined:

* [Vue.js Tokyo v-meetup="#3" - connpass](https://vuejs-meetup.connpass.com/event/48462/)

### Slide

It is in Japanese... 😇 

[Nuxt.js とは何か / What is nuxtjs // Speaker Deck](https://speakerdeck.com/inouetakuya/what-is-nuxtjs)

* The problem which Nuxt.js try to solve
* Nuxt.js helps us to focus on *.vue!!
* Features of Nuxt.js including nuxt generate

### Reaction

And we can see 17 tweets which mean Nuxt.js looks good!! ⭐️ 

* [hashtag #vuejs_meetup3](https://twitter.com/hashtag/vuejs_meetup3?f=tweets&vertical=default&src=hash)

**Comment by Atinux** [comment]
This is awesome 🙌

Thank you @inouetakuya
