### ISSUE TITLE
static folder path problem

### ISSUE THREAD

**Issue by franklion** [nuxt/nuxt.js#3553]
I have a problem with static folder path in the sub-domain.
The URL is `http://test.com.tw/2018/` on my website, and then I put generated files in the 2018 folder.
But when I execute "npm run generate", the index.html that can't find the image.

So I google some issue about this topic, I found one solution
To modify nuxt.config.js
`
router: {
    base: "/2018/"
}
`
This method not only can transform the router path but also assets folder path. 
BUT It can't transform a static folder path, it's still served in the root path.

For example:
`<img src="/logos/logo.png">`

I want this
`<img src="/2018/logos/logo.png">`

Can Someone tell me how to modify nuxt.config.js?

Thanks: D

**Comment by juniorgarcia** [comment]
Duplicate: [#c7407](https://cmty.app/nuxt.js/issues/c7407 "nuxt.js - static folder path problem")

**Comment by franklion** [comment]
ok!
