### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by anthinkingcoder** [nuxt/nuxt.js#3555]
**Version:1.4.1**
**When I execute the command: npm run dev,a mistake was made**
```
/node_modules/nuxt/lib/core/middleware/nuxt.js:72
const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
SyntaxError: Unexpected token ...
```

how to solve?

**Comment by juniorgarcia** [comment]
This is because you need to tell Babel to use ES6 spread operator.

Please, read this: https://babeljs.io/docs/en/babel-plugin-transform-object-rest-spread/

I'm using Nuxt 1.4.1 and _didn't_ have to configure it. It just works out of the box.

**Comment by GreggOD** [comment]
For anyone else having this issue, I removed the `engines` option from my `package.json`. I think my node version was set to one that didn't support the `...` ES6 syntax - copied code from a tutorial on how to get Nuxt and Heroku working together and that was part of the tut.

Its been a nightmare getting nuxt to work on Heroku. Client is on my back and everything seems to be failing. Finally seeing some light.
