### ISSUE TITLE
It's not clear how to include jQuery code

### ISSUE THREAD

**Issue by smth** [nuxt/nuxt.js#356]
I can't find anything in the docs about how to include snippets of JS or local JS files, that contain jQuery (I have jQuery itself included from a CDN). Whatever I have tried has resulted in errors ranging from `$ is not defined` to `jQuery requires a window with a document`. Any pointers?

**Comment by awronski** [comment]
Take a look at the [How to add webpack plugins](https://nuxtjs.org/faq/webpack-plugins).

**Comment by smth** [comment]
Hi @awronski 

Yeah, I tried that already, in combination with `plugins: ['~assets/js/my-file.js']`, but got the `jQuery requires a window with a document` error.

**Comment by awronski** [comment]
You need to check if you are executing your script in the browser:
```
if (process.BROWSER_BUILD) { ... }
```

**Comment by smth** [comment]
OK, I think that's the part I'm missing. Which script? Could you elaborate.

**Comment by awronski** [comment]
You are writing some javascript code in which you want to use jquery. Right?
Then the code is executed twice, on the server-side during ssr and then
later in the browser.

In the ssr you don't have to window this is why you need to wrap your code
with the condition.


BTW, Why do you need jquery when you can do everything even easier without
it thanks to the vue directives?

**Comment by smth** [comment]
That's right.

I'm still not sure what to put into `if (process.BROWSER_BUILD) { ... }`.

I have tried
```
if (process.BROWSER_BUILD) {
   const webpack = require('webpack')
}
```
and
```
if (process.BROWSER_BUILD) {
   require('my-file')
}
```
and
```
if (process.BROWSER_BUILD) {
   const webpack = require('webpack')
   plugins: [
     '~assets/js/my-file.js'
   ]
}
```

None of which change the error.

I have also tried variations of 
```
if (process.BROWSER_BUILD) {
   const webpack = require('webpack')
   plugins: [
     '~assets/js/my-file.js'
   ],
   build: {
     plugins: [
       new webpack.ProvidePlugin({
         '$': 'jquery'
       })
     ]
   }
}
```
which give a syntax error.

I'm not familiar enough with Vue directives to know how they can be a replacement for jQuery, but I essentially want to use it to add/remove classes.

**Comment by awronski** [comment]
From your snippet it looks like you want to manipulate DOM from the
external script in the browser.
But you are including jquery plugin to use it in the server generated code.

IMHO This does not make a sense.

About the styles, look at this:
https://vuejs.org/v2/guide/class-and-style.html

**Comment by smth** [comment]
OK, so how should I be including it?

**Comment by awronski** [comment]
you need to register jquery in the nuxt.config.js and of course install it
with npm.

Here are examples: https://github.com/nuxt/nuxt.js/issues/178

**Comment by smth** [comment]
So you can't use jQuery from a CDN?

OK, so now I have 

```
const webpack = require('webpack')

module.exports = {
plugins: [
    '~assets/js/my-file.js'
  ],
build: {
    vendor: ['jquery'],
    plugins: [
      new webpack.ProvidePlugin({
        '$': 'jquery'
      })
    ]
}
```
But this doesn't seem to move things forward. I still get the same `jQuery requires a window with a document` error. And I still have not got anything inside `if (process.BROWSER_BUILD) {}` in the template.

**Comment by KonstantinVlasov** [comment]
Hi, @smth!
did you try this?

in **nuxt.config.js**
```
plugins: [
   '~plugins/my-query-code.js'
]
```
in **plugins/my-query-code.js**
```
if (process.BROWSER_BUILD) {
   const $= require('jquery')
   $(function() {
      console.log('document ready!');
      // do whatever you want with html and jquery
   })
}
```

**Comment by ajcpwnz** [comment]
Here is my scenario how I made jquery work with nuxt. 
1) Install it from npm. 
2) `import` it in component  which requires it. Like `import $ from 'jquery'`
3) Call `$` in all lifecycle hooks after `created()` and it works since document exists by that time. `$` should also work in component `methods`.  

**P.S.**
I tried using jquery to manipulate some classes and stuff in vue app, but it seems now that using vue and vuex features is more convenient. Most jquery usages can be refactored with help of `store` for global things and `props` if you need some data only locally in your components.  Seems more *vue-way* for me.

**Comment by smth** [comment]
I didn't @KonstantinVlasov, but that looks straight-forward and promising. I decided to go for a *more Vue way*, using directives for now. So I gave up on jQuery for the time being, but I'll probably revisit this at some point.

**Comment by SteveVnzk** [comment]
I use  jQuery code in this way
```
<template>
<!-- Body -->
</template>

<script>
import $ from 'jquery'

export default {
  mounted: () => {
    // jQuery code
  }
}

</script>
```

**Comment by davodaslanifakor** [comment]
@alexchopin  i cant understand how solve this problem?

**Comment by davidjor-hpan** [comment]
@smth I fixed that error by adding `window` as prefix ! No need webpack and npm !!!
just

```
window.$
```

**Comment by rlam3** [comment]
Following NuxtJS guidelines. I think we are supposed to install jquery via npm ? And include it via vendor?

https://nuxtjs.org/guide/plugins/

It would be included in all pages. Correct?

**Comment by farhadniaz** [comment]
You can add any external JS libraries in head option:
[](https://nuxtjs.org/faq/)
module.exports = {
  head: {
    script: [
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js' }
    ],
    link: [
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto' }
    ]
  }
}

**Comment by sudhir600** [comment]
Hi @awronski,

I have 10 dymanic form (see img). each form has (-) and (+) button with one text box. i want to increase and decrease when being click respective by button. I am able to achieve this by jquery easly (.parent.find...)

but i am really cluless how to do the same with properly vuejs style. i am using Nuxt.

![image](https://user-images.githubusercontent.com/4952560/39752418-03566dc8-52d9-11e8-980a-fb3169125c02.png)
Any help pls

**Comment by rayGobel** [comment]
@sudhir600 Hi sudhir, you can use data binding in vue js. Supposed you have the following component with button:
```
<template>
    <p>{{ amount }}</p>
    <a class="btn" href="#" v-on:click="increaseAmount()">Plus (+)</a>
    <a class="btn" href="#" v-on:click="decreaseAmount()">Minus (-)</a>
</template>

<script>
export default {
  data () {
    return {
      amount: 0
    }
  },
  methods: {
    increaseAmount () {
      this.amount = this.amount + 1
    },
    decreaseAmount () {
      this.amount = this.amount - 1
    }
  }
}
</script>

```

Then, you should render each product in those image to each different component. See [Component Basics#BaseExample](https://vuejs.org/v2/guide/components.html#Base-Example) on vue.js guide.

**Comment by kaloraat** [comment]
`// /plugins/bootstrap.js
if (process.BROWSER_BUILD) {
	require("bootstrap");
}`

`npm install --save bootstrap jquery popper.js`

`// full code of nuxt.config.js

const webpack = require("webpack");

module.exports = {
  // load bootstrap and jquery
  css: ["./node_modules/bootstrap/dist/css/bootstrap.css"],
  plugins: ["~plugins/bootstrap.js"],
  build: {
    /**
     * add external plugins
     */
    vendor: ["jquery", "bootstrap"],
    plugins: [
      new webpack.ProvidePlugin({
        $: "jquery"
      })
    ],
    /*
    ** Run ESLint on save
    */
    extend(config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          exclude: /(node_modules)/
        });
      }
    }
  }
};`

[Read more](https://kaloraat.com/articles/how-to-use-jquery-in-nuxtjs)
