### ISSUE TITLE
How to avoid packing server-side js into client-side bundle js when use nuxt generate?

### ISSUE THREAD

**Issue by MwumLi** [nuxt/nuxt.js#3568]
### What problem does this feature solve?

Code is below:
```js
  asyncData ({params, env}) {
    let html = '';
    if (process.server) {
      const marked = require('marked');
      const fs = require('fs');
      try {
        let markdown = fs.readFileSync(`./hello.md`, 'utf-8');
        html = marked(markdown);
      } catch(err) {
        console.log("[获取文件内容]:", err)
      }
    }

    return { html`}
  }
```
I hope marked not be packed into client-side bundle when run nuxt generate, but it's in client-side bundle in fact
How to solve it?

### What does the proposed changes look like?

if a package is only used in server side , it should not be packaged into client-side

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7422">#c7422</a>)</em></sub></div>

**Comment by Atinux** [comment]
Well I tried to used your example and I could not reprodue it with `nuxt v1.4.2` and `nuxt-edge`.

`process.server` excludes it from client-side bundle, you can analyze it with `npx nuxt build -a`
