### ISSUE TITLE
Split css build files (one css file for every page)

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#357]
Hi! 

I have over 30 nuxt pages. 

when i run 
`npm run build`

i have 30 js files for every page
and 1 css file 

It is problem. When i will have 300 pages, my css file size will be over 10-15 Mb

How to split css for every page?

**Comment by alexchopin** [comment]
Will be available in the next release. [More info](https://github.com/nuxt/nuxt.js/issues/12)
