### ISSUE TITLE
Allow nuxt build to read production env

### ISSUE THREAD

**Issue by dysol** [nuxt/nuxt.js#3571]
### What problem does this feature solve?

Developers don't have to load production env vars and execute nuxt build. Env vars can be directly read from production.

Right now, when i console.log(process.env) from my production (AWS Elastic Beanstalk), the env returned are all my dev environment.

I had to run nuxt build then upload the entire project to AWS EB.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7427">#c7427</a>)</em></sub></div>

**Comment by gotoin** [comment]
Good idea, i use build(pm2) in the beta environment, but env === production.

**Comment by gotoin** [comment]
i need to set env using pm2

**Comment by aldarund** [comment]
you could use https://github.com/samtgarson/nuxt-env

**Comment by gotoin** [comment]
@aldarund Thanks, but this is not what I need

**Comment by aldarund** [comment]
@gotoin I'm.not sure what u need, but that module do exactly what was asked in initial issue
