### ISSUE TITLE
[edge] [nuxt] Error while initializing app DOMException

### ISSUE THREAD

**Issue by nallown** [nuxt/nuxt.js#3575]
_**Edit:**_ I solved the problem you can find the solution in this comment https://github.com/nuxt/nuxt.js/issues/3575#issuecomment-411246148

### Version

[2](https://github.com/nuxt.js/releases/tag/2)

### Reproduction link

[https://test.twist.moe/a/07-ghost/1](https://test.twist.moe/a/07-ghost/1)

### Steps to reproduce

1. Go to the reproduction link
2. Login with username: `public` and password: `not`
3. Check Dev-Tools console

### What is expected ?

The website should render fine and it should play the video.

### What is actually happening?

It throws an error in the console.

### Additional comments?

I tried to upgrade my nuxt version to 2.0 and I get the following error:
```
[nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

I've updated the Nuxt version to nuxt-edge and I also updated other node modules version to work with nuxt-edge and webpack 4. I freshly installed the node_modules so I removed the folder and ran a fresh `npm i`. When I run the dev version of the build, it works fine. It only fails with the production build. All the unit test pass just like they did before I only started getting this error after the nuxt-edge and webpack 4 upgrade. The website works fine and everything builds without a error, there were no issues until I upgraded my project to nuxt-edge and started the nuxt server in production.

I can give you access to the repository the project is very easy to setup, the dev version of the project works without internet, it uses mock network requests for the API. Just ask and I can give you access. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7430">#c7430</a>)</em></sub></div>

**Comment by manniL** [comment]
Related: #1552

**Comment by nallown** [comment]
It only happens on nuxt-edge for me and not 0.4.0. In 0.4.0 it builds and runs perfectly fine. So something changed in nuxt-edge that broke the code.

**Comment by nallown** [comment]
@kball My code worked fine in 1.4.0 the error happened because I upgraded my project from nuxt 1.4.1 to nuxt-edge (2.0.0). I still checked though and found no `v-if` inside any `v-for`.

**Comment by Atinux** [comment]
I just went to the website and I see no error in the console.

Is it fixed? If so, what did you change?

**Comment by nallown** [comment]
There was a nested `v-if` inside another `v-if` that broke the change so I swapped out the first `v-if` with a `v-show`

```jsx
      <div v-if="message" class="msg-container" :class="message.type">	
        {{ message.text }}	
        <button	
          v-if="message.type === 'error'"		<!-- nested v-if -->
          v-on:click="() => {	
            message = null;	
            media.load();	
            media.play();	
          }">Retry</button>	
       </div>	
```

I changed that into
```jsx
	  <!-- I replaced the top v-if with v-show -->
      <div v-show="message" class="msg-container" :class="message.type">	
        {{ message.text }}	
        <button	
          v-if="message.type === 'error'"	<!-- nested v-if -->
          v-on:click="() => {	
            message = null;	
            media.load();	
            media.play();	
          }">Retry</button>	
       </div>	
```

**Comment by Atinux** [comment]
Thank you @nallown 

Indeed, this issue is really weird but it's due to `vue-server-renderer` that get crazy sometimes with `v-if`.

Closing the issue.

**Comment by Jialufeng** [comment]
V-show doesn't solve my problem.

**Comment by nallown** [comment]
@Jialufeng I can help you fix your problem. Start by identifying where the problem is coming from, remove all `div`s `span`s, all elements and components from your page and check if you still have it. If the error is gone then start adding some of the `div`s `span`s every element bit by bit back, add them one by one back and check if the error comes back. 

Message me when you find when out what part of your page is giving you the error and send me a snippet of the element that has the error. 

These errors are one of those things that you'll automatically master to fix over time, after writing enough Vue code you'll start to automatically memorize the things you should avoid so that you won't ever get the error again.

**Comment by Jialufeng** [comment]
@nallown  It has been solved by a div. thank
