### ISSUE TITLE
Date turns to string in component data between server and client

### ISSUE THREAD

**Issue by samtgarson** [nuxt/nuxt.js#3579]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://ssr-bug-bgifhwojxt.now.sh/](https://ssr-bug-bgifhwojxt.now.sh/)

### Steps to reproduce

_Read additional comments below, this may be a non issue._

The source of the repro deployment is available at https://zeit.co/samtgarson/ssr-bug/bgifhwojxt/source
The logs are available at https://zeit.co/samtgarson/ssr-bug/bgifhwojxt/logs

This app instantiates a Date object in the test page's async data, and has a computed property which reads the date from the data and it is rendered on the page. It also console logs the type of the async data property in the `created` hook.

1. Visit https://ssr-bug-bgifhwojxt.now.sh/
2. Click the button to navigate to the test page
3. Notice the year is rendered, and note that `object` has been printed to the console. This is the type of the `date` property on the page component's data.

4. Refresh the page and notice that an empty object is rendered, and this time `string` has been printed to the console, however that `object` was printed to the logs when the page was rendered on the server.

### What is expected ?

The property on the component data should be of type date on the client side (i.e. the year should be rendered and `object` should be printed to the console in the browser)

### What is actually happening?

As the component's data is passed from server to client, it appears that a Date object is being converted to a string, hence `string` being printed and an error being rendered

### Additional comments?

This may be a non-issue—complex objects cannot be serialised, so would not be expected to survive rehydration. This could be considered more of a question because Dates are native objects in JS. This could equally be an issue with Vue SSR.

Either way, maybe it should be documented somewhere?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7432">#c7432</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @samtgarson 

Thanks for this bug report, indeed, this is a caveat of server-side rendering since the data is serialised so we have no way to give back the good format.

A solution is to use the `created` hook to restore the correct type:

```js
<template>
  <div>
    {{ year }}
  </div>
</template>

<script>
export default {
  asyncData () {
    return {
      date: new Date()
    }
  },
  created () {
    if (typeof this.date === 'string') {
      this.date = new Date(this.date)
    }
  },
  computed: {
    year () {
      return this.date.getFullYear()
    }
  },
}
</script>
```

Another way will be to avoid complex types into `asyncData`.

I will add a "Server-side Caveats" section into the documentation, thank you @samtgarson!
