### ISSUE TITLE
How to unit test js functions in the vue instance

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#358]
I have some functions in the vue component. for eg 

    getKey(param1, param2) {
        return param1+param2
    }

    onUploadComplete() {
        this.uploadCompleted = true;
        this.uploadStarted = false;
        //Need to test the properties in the instance as well
    }

Also some values will be updated in the store. I Couldn't find any examples in the documentation

How can I test this?

**Comment by alexchopin** [comment]
I think this is more related to [Vue](https://vuejs.org/v2/guide/unit-testing.html) instead of Nuxt in this case.
