### ISSUE TITLE
Gitter -> Discord

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#3583]
### What problem does this feature solve?

All vue community is on discord. There even nuxtjs room on vue discord server.
Nuxt have a link to gitter on main page. So it create two separate chats for same thing and divide users, i often see question repeated in both discord and gitter.
Maybe just change gitter to room in official vue discord server? 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7434">#c7434</a>)</em></sub></div>

**Comment by dysol** [comment]
i agree!

**Comment by toadkicker** [comment]
My only complaint about Discord is the lack of threaded conversations (same problem with Gitter too).

**Comment by gustojs** [comment]
On behalf of https://chat.vuejs.org moderators team, I offer all the help that may be required during in the transition.

**Comment by Atinux** [comment]
Thanks @aldarund
