### ISSUE TITLE
NUXT2: fetch method of next route params is called before beforeDestroy/destroyed of current route params

### ISSUE THREAD

**Issue by bochkovyi** [nuxt/nuxt.js#3587]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js#readme](https://github.com/nuxt/nuxt.js#readme)

### Steps to reproduce

Happening in NUXT 2.
folder structure: /pages/category/_slug.vue
Create a page with async fetch() method inside _slug.vue and do some request.
In the same file create a beforeDestroy() lifecycle hook.
console.log from both.

Navigate the page with nuxt-link pointing to some other /category:slug

### What is expected ?

console.log('from beforeDestroy');
console.log('fetch');

### What is actually happening?

console.log('fetch');
console.log('from beforeDestroy');

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7438">#c7438</a>)</em></sub></div>

**Comment by manniL** [comment]
Not sure if this is a bug :thinking:
Could be intended as the data will be loaded first while the current page stays open. After that, the current page will switch (and the components will be destroyed).

**Comment by bochkovyi** [comment]
@manniL I agree, this could be a feature. I just had a frustrating experience with it and thought about mentioning. 

Example: in beforeDestroy we clear current page's data, dispatching vuex action (to free the memory, when user navigates from page to another page and the data are not needed anymore). 
And if user just changes the :slug but stays on the same page type (category page), we do a new fetch.
What happens currently is that fetch() fires first, and beforeDestroy actually removes the data in the newly loaded page. If this confirmed to be not a bug, let's just close the topic.

**Comment by Atinux** [comment]
Hi there,

It's not a bug report but an intended behaviour, we use `router.beforeEach` guard (https://router.vuejs.org/guide/advanced/navigation-guards.html#global-guards) to call `fetch` and `asyncData`.

BTW, I am thinking of an option of "reactive loading" where the order will be the opposite, but this add more complexity like having a global loader or some placeholder for the next page.

Right now, it's not planned before 3.0
