### ISSUE TITLE
Custom route names

### ISSUE THREAD

**Issue by SteveEdson** [nuxt/nuxt.js#3589]
### What problem does this feature solve?

Currently, urls are based on the filename with the pages directory. I'd like to be able to use

```js
export default {
    name: 'custom-page-name',
    ...
};
```

and have it set that as my route name for that page. That way, I can use `<nuxt-link :to="{ name: 'custom-page-name' }">Link</nuxt-link>`, without worrying that if I change my page file name (and therefore the URL) it'll break all my links.

### What does the proposed changes look like?

```js
export default {
    name: 'custom-page-name', // This is already a Vue convention for naming components
    ...
};
```

 `<nuxt-link :to="{ name: 'custom-page-name' }">Link</nuxt-link>`

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7439">#c7439</a>)</em></sub></div>

**Comment by galvez** [comment]
@SteveEdson the team's current position is to maintain the convention for now. For the moment you can use the [router module](https://github.com/nuxt-community/router-module) or [`extendRoutes`](https://nuxtjs.org/api/configuration-router/) in conjunction with `routes.splice(0, routes.length, ...[new routes])`.

**Comment by patrickkh7788** [comment]
`router module` or extendRoutes  is not simple to manage with a lot pages.  
this should be open as feature if the dev team is not plan to implant it soon.

**Comment by manniL** [comment]
@patrickkh7788 If someone wants to submit a PR, we'd be happy to look over it!

**Comment by simllll** [comment]
So is this now implemented? Or why is it closed?

**Comment by manniL** [comment]
@simllll As you can read a few comments above yours, it's not planned to get implemented very soon.

**Comment by manniL** [comment]
Maybe you could use the `meta` object of the routes 🤔

**Comment by traherom** [comment]
I want to add my support to this for an additional reason: transitioning existing Vue apps. Rather than doing find and replace on all route names in existing pages/components, you can simply set the `name` and be more confident that all your existing links work. One less barrier to moving to Nuxt.

**Comment by Atinux** [comment]
Keeping it open since this could be really handy when working with pages, but this has to be well done.

Right now, we have no way to read the page file and get the `name` given in it, and using RegExp is not a good idea since it would lead to more issues.

**Comment by SteveEdson** [comment]
Can we add the `Hacktoberfest` label to this issue please? It'd be great for the additional support. Thanks.

**Comment by amritk** [comment]
Ah, I have been looking to switch to nuxt.js lately, is it possible to do nested named routing?

For example:
```
export default new Router({
    mode: 'history',
    routes: [
        {
            path: '/:locale',
            component: TheRoot,
            props: true,
            children: [
                {
                    path: '/sports/:id',
                    name: 'Sport',
                    component: Sport
                }
            ]
        }
    ]
})
```
Now I would like to be able to simply access this with `:to="{ name: 'Sport', params: { id: 2} }"` without having to figure out what the current locale is all the time with the full path ```:to="`${locale}/sports/2`"```

Is this currently possible? Or are we waiting for this issue to be resolved to do this?

**Comment by aaronransley** [comment]
Bumping this one so `stalebot` doesn't swoop in and ruin our dreams 😢

**Comment by manniL** [comment]
@aaronransley Stale bot isn't closing feature request anymore.

**Comment by pi0** [comment]
[nuxt-router-extras](https://www.npmjs.com/package/nuxt-router-extras) may be related 😊

**Comment by moltar** [comment]
Would be great to be able to define custom names, to keep the code DRY.

I think the custom path name could be a static property of the component.

And then this class can be imported into places where the paths need to be referenced.

**Comment by Atinux** [comment]
The solution for this is to use the [router-extra-module](https://github.com/nuxt-community/router-extras-module).

The documentation will be updated to point this module :)
