### ISSUE TITLE
async await axios not working in current nuxt components

### ISSUE THREAD

**Issue by pulkitnandan** [nuxt/nuxt.js#359]
Hi,

I'm trying to use async await axios in current nuxt components which have stopped working as of now,

Here goes the repo to reproduce https://github.com/pulkitnandan/bugNuxt
and this has happened before @ this https://github.com/nuxt/nuxt.js/issues/84

Please have a look at this.

**Comment by dohomi** [comment]
@pulkitnandan it works in my project without issue.. by the way: did you read the docs of NUXT:
https://nuxtjs.org/guide/async-data
async-data is only available in pages and layouts files
