### ISSUE TITLE
[edge] Npm release?

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#3597]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

Last release of edge on npm 14 days old. Is it intentional or something broken? Previously they was released when a pr commited or smth like this.
I even see a release job on circle ci for release https://circleci.com/gh/nuxt/nuxt.js/3300
although no npm release actually, but also no error in job
Last release on npm
2.0.0-25523369.7c85202 14 days ago

I want to use some recent changes from nuxt but there no published version..

### What is expected ?

publish npm version more often..

### What is actually happening?

last npm version 14 day old

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7444">#c7444</a>)</em></sub></div>

**Comment by manniL** [comment]
Bet the tokens used for it got invalidated after the [security breach](https://status.npmjs.org/incidents/dn7c1fgrr7ng)

cc @clarkdo

**Comment by clarkdo** [comment]
Looking into it @manniL thank you for the information.

**Comment by clarkdo** [comment]
It works now.
