### ISSUE TITLE
Nuxt doesn't pipe console output to pm2

### ISSUE THREAD

**Issue by canyoudev** [nuxt/nuxt.js#3599]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

When starting Nuxt with pm2 and then using `pm2 monit` I expect to see console.log output, but there's none. Why? I want to monitor my app, how to see logs?

### What is expected ?

Logs output

### What is actually happening?

No freaking logs

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7447">#c7447</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I think it not related to nuxt.

When you run  `pm2 monit` the log output frame will log everything in realtime, that mean it will log everything after you run `pm2 monit`.

If you want to check all log included the past, The right command should be `pm2 logs ID`

**Comment by manniL** [comment]
When using `pm2 log NAME` or `pm2 log ID` the console output will be displayed as @kieusonlam said.

**Comment by canyoudev** [comment]
You right, thanks!
