### ISSUE TITLE
[edge] Weird output from builder

### ISSUE THREAD

**Issue by Freakspot** [nuxt/nuxt.js#3600]
### Version

~[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)~
nuxt-edge@latest

### Reproduction link

[https://github.com/Freakspot/nuxt-edge-broken](https://github.com/Freakspot/nuxt-edge-broken)

### Steps to reproduce

Just run `node app.js`.
"Test" will never be seen in the console, only "Test 2" will. Imo console.logs prior to the builder should not be cleared.

Additionally, I sometimes get huge empty chunks of whitespace, which I think sometimes happens after rendering new pages? Definitely not 100% reproducable. Also, when the builder is done doing its magic, I'll have a lot of "Compiling..." in the console which imo also shouldn't happen. See this gif: https://gph.is/2v17gSP

### What is expected ?

Clean output

### What is actually happening?

Unnecessary clutter, whitespace and deletion of console.logs

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7448">#c7448</a>)</em></sub></div>

**Comment by Atinux** [comment]
I've seen this behaviour as well, we will look at it with @clarkdo, thank you @Freakspot

**Comment by manniL** [comment]
Possibly related: https://github.com/nuxt/webpackbar/issues/13

**Comment by clarkdo** [comment]
@Freakspot I suggest you using `consola` which is the default log utility of Nuxt and it's automatically included by Nuxt.

```js
const { Nuxt, Builder } = require('nuxt-edge');
const nuxt = new Nuxt();
const consola = require('consola')

consola.log('Test');

async function build() {
	const builder = new Builder(nuxt);
	await builder.build();
}

build();

consola.log('Test 2');
```

If this doesn't solve your problem, please feel free to ping me, I'll reopen the issue.

**Comment by manniL** [comment]
@clarkdo Unfortunately you can't always control which logger will be used (example:other plugins/modules) :|

**Comment by Freakspot** [comment]
Using consola does indeed solve my problem _in this case_, but I have heard other complaints about this, too, and imo using consola is more of a workaround than an actual solution to this problem, similar to how @manniL stated. (console.log is also included with nuxt. :stuck_out_tongue:) 

Thanks for providing this workaround tho, I really appreciate it!
