### ISSUE TITLE
Scaffold a basic CRUD structure

### ISSUE THREAD

**Issue by toadkicker** [nuxt/nuxt.js#3602]
### What problem does this feature solve?

Offer the ability to scaffold a basic CRUD user interface

### What does the proposed changes look like?

Given a command similar to how Rails solves scaffolding:

`nuxt scaffold widget name:string title:string updated_at:datetime`

Nuxt creates a basic scaffolding for a Vuex store, pages, and a form component.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7453">#c7453</a>)</em></sub></div>

**Comment by toadkicker** [comment]
I'm happy to put this together if there is interest in creating a scaffold generator.

**Comment by toadkicker** [comment]
Something like:

```
|
- components/
|  - WidgetForm.vue
- pages/
|  - widget/
|    index.vue
|    new.vue 
|    - widget_id/
|      edit.vue
|      index.vue
- store/
  widget.js
```

One of the things it would need to do is define this structure as the convention, but offer the ability to use other UI frameworks, like bootstrap-vue, etc.

**Comment by galvez** [comment]
@toadkicker Please find an issue or propose contribution over at [create-nuxt-app](https://github.com/nuxt-community/create-nuxt-app)
