### ISSUE TITLE
Do not remove folder buildDir when building.

### ISSUE THREAD

**Issue by zgayjjf** [nuxt/nuxt.js#3606]
### What problem does this feature solve?

We do not want to remove files under buildDir, as this removal will cause 404 when rebuilding.
It would be great to have a option to configure the behavior here [code](https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/builder.js#L132)

### What does the proposed changes look like?

A option in nuxt.config.js like `config.removeBeforeBuild = false` would be nice.
I can make a pr if someone point a better way.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7461">#c7461</a>)</em></sub></div>

**Comment by manniL** [comment]
Related: #3389

**Comment by Atinux** [comment]
I like this idea actually but I am afraid it may lead to some issues.

We may need some tests to make sure it won't create more issues.

**Comment by daspete** [comment]
You can just make your own node.js task, which calls the nuxt build task, and after the build completes, you have a fresh build directory, now you can rename it to whatever foldername you want (for example "public") you can also rename the old public folder to "public_backup" so you have a backup.

**Comment by galvez** [comment]
@daspete's answer seems to cover this for now. Closing issue.
