### ISSUE TITLE
Use NUXT_HOST and NUXT_PORT environment variables instead of HOST and PORT

### ISSUE THREAD

**Issue by grinnery** [nuxt/nuxt.js#3609]
### What problem does this feature solve?

HOST and PORT names are too generic and often are set by OS/other apps, causing unexpected failures.
They also take precedence over the other configuration options, which is not clearly stated in the [FAQ](https://nuxtjs.org/faq/host-port/).

### What does the proposed changes look like?

1. Use  `NUXT_HOST` and `NUXT_PORT` environment variables instead.
2. Document the order of precedence in the FAQ docs.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7464">#c7464</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @grinnery 

Could you point some similar framework using the same standard like you propose?
