### ISSUE TITLE
Tests don't work out of the box

### ISSUE THREAD

**Issue by nijikokun** [nuxt/nuxt.js#361]
1. Clone repo
2. `npm install`
3. `npm test`

Tests fail out of the box due to mix-match versions of:

- `vue` (2.2.1 installed)
- `vue-server-renderer` (2.2.2 installed)
- `vue-template-compiler` (2.2.2 installed)

Vue 2.2.2 [has been pushed to the Vue repo](https://github.com/vuejs/vue/commit/d0b8dce4a6cbcce1aed1912ab12b20c858edd729) but [not actually released on NPM](http://i.imgur.com/y5gQ9ED.png):

```
npm ERR! No compatible version found: vue@2.2.2
```

Thoughts about specifying the specific versions to prevent this issue from re-occuring?

**Comment by alexchopin** [comment]
Thanks for the report, will be fixed soon 👍
