### ISSUE TITLE
Can't use Nuxt with Vuetify, getting syntax Error

### ISSUE THREAD

**Issue by chanlito** [nuxt/nuxt.js#3611]
### Version

[nuxt-edge](https://github.com/nuxt.js/releases/tag/nuxt-edge)

### Reproduction link

[https://github.com/chanlito/nuxt-vuetify-syntax-error](https://github.com/chanlito/nuxt-vuetify-syntax-error)

### Steps to reproduce

npm i && npm run dev

### What is expected ?

No SyntaxError

### What is actually happening?

Getting SyntaxError

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7466">#c7466</a>)</em></sub></div>

**Comment by igtm** [comment]
same bug in v2.1.0
