### ISSUE TITLE
Update css-loader

### ISSUE THREAD

**Issue by shrpne** [nuxt/nuxt.js#3613]
### What problem does this feature solve?

Please update `css-loader` from 0.28.11 to 1.0.0.
0.28 version has outdated dependencies, such as: `browserslist` 1.7.7 (current is 4.01), `cssnano` 3.10 released 1.5 years ago (current is 4.0.5)

css-loader 1.0.0 has breaking changes, so would be great if it will be updated before nuxt2 release

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7467">#c7467</a>)</em></sub></div>

**Comment by Kuzzy** [comment]
Up ⇈
