### ISSUE TITLE
Can I integrate nuxt to python flask app?

### ISSUE THREAD

**Issue by purrplingcat** [nuxt/nuxt.js#3615]
Hi,

I have a quesrtion about integrating nuxt with python flask app. I have a API backend in python and I want integrate at route **/admin** or otherwise nuxt:render.

```python
@app.route('/')
def nuxt_render():
    # this index.html includes nuxt JS generated files and etc
    return app.send_static_file('index.html')
```

It's it realisable?

**Comment by manniL** [comment]
I'd create two distinct projects and use NGINX/Apache to proxy /admin to your flask app and the rest to the nuxt app.
