### ISSUE TITLE
Optimization Build Version

### ISSUE THREAD

**Issue by samialmorshedi** [nuxt/nuxt.js#3617]
I'm using Nuxtjs and Exprressjs.
I'm looking for an optimization guideline that includes:
- merge all js files (pages js files)
- leverage browser caching 
- cash static contents
- uglify CSS and JS file

There is a bunch of unreliable docs out there but I'm looking for the official package, Can you help me?

**Comment by manniL** [comment]
### Merge all JS Files

With HTTP2, code-splitting and preload/prefetch, this shouldn't be done anymore. It's better to let the user load the most important content (the *app-shell* and the *current page*) first and let him load the other pages with subsequent requests afterwards (if preload/-fetch is enabled).

## Browser Caching

This can be achieved either with Express.js (if you use nuxt only as "renderer") or in the nuxt config itself by changing the [static value](https://nuxtjs.org/api/configuration-render#static).

Example (`nuxt.config.js`):

```js
render: { 
  static: { 
    setHeaders(res, path): {
      if (path.match(/.js$/)) {
        res.setHeader('Cache-Control', 'no-cache')
      }
    }
  }
}
```

Alternatively, you could go for the `PWA` approach and use service-workers for caching. You could use the [`pwa-module`](https://github.com/nuxt-community/pwa-module) for it.


### Uglify CSS and JS

Should be done automatically, but you can push webpack plugins or rules into the config through the `build.extend` function in your `nuxt.config.js`.

Example (adding ESLint rules):

```js
build: {
    extend (config, ctx) {
      if (ctx.isClient) {
        if (ctx.isDev) {
          config.module.rules.push({
            enforce: 'pre',
            test: /\.(js|vue)$/,
            loader: 'eslint-loader',
            exclude: /(node_modules)/
          })
        }
      }
    }
  }
}
