### ISSUE TITLE
Register vuex module inside fetch function

### ISSUE THREAD

**Issue by marco-gattelli** [nuxt/nuxt.js#3619]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://jsfiddle.net/5gfucLd2/1/](https://jsfiddle.net/5gfucLd2/1/)

### Steps to reproduce

register a vuex module inside fetch function.

### What is expected ?

To have the module registered when the page is rendered in the browser.

### What is actually happening?

The module is registered only in the server-side while in the client the Vuex does not have the module.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7470">#c7470</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @marco-gattelli 

`fetch` is only called on server-side when loading the page for the first time. On client-side, it is not aware about the `registerModule` call.

I recommend you to use the `created` hook to register your module since it's called both client-side and server-side.
