### ISSUE TITLE
common chunks plugin

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#362]
Just took a look at my build size and it was large :). First question is, what is big then I asked, is common chunks plugin enabled? So I ask, does nuxt implement common chunks plugin? If not, is it possible to implement through the nuxt.config?

**Comment by pi0** [comment]
@uptownhr common chunks is enabled by default for client bundles (see [client.config.js#L50](https://github.com/nuxt/nuxt.js/blob/master/lib/webpack/client.config.js#L50)) BTW for your first question you can easily use `nuxt analyze` command to analyze what is big

**Comment by uptownhr** [comment]
Thank you

On Thu, Mar 9, 2017, 2:57 AM Pooya Parsa <notifications@github.com> wrote:

@uptownhr <https://github.com/uptownhr> common chunks is enabled by default
for client bundles (see client.config.js#L50
<https://github.com/nuxt/nuxt.js/blob/master/lib/webpack/client.config.js#L50>)
BTW for your first question you can easily use nuxt analyze command to
analyze what is big

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nuxt/nuxt.js/issues/362#issuecomment-285320825>, or mute
the thread
