### ISSUE TITLE
About the error "This page could not be found" in the next() in router.beforeEach()

### ISSUE THREAD

**Issue by xachary** [nuxt/nuxt.js#3621]
### Version

[v1.0.0](https://github.com/nuxt.js/releases/tag/v1.0.0)

### Reproduction link

[https://github.com/xachary/test-beforeeach-next](https://github.com/xachary/test-beforeeach-next)

### Steps to reproduce

See the README.md  about Setup and Run please.

Bug in Nuxt:

0. open http://localhost:3001/
1. click "1", that will stay page "index", because run "next('/one')" in router.beforeEach().
2. click "2", that will go to page "two", because run "next()" in router.beforeEach().
3. click "back" button of the browser, back to page "index".
4. click "3", that will redirect "http://localhost:3001/one", then it will show "This page could not be found" error, also run "next('/one')" in router.beforeEach() by the way(wrong).
5. type "http://localhost:3001/one" in browser, the same as step 4.
![image](http://23.83.248.199/%2Froot%2Fdownload%2Fshare%2Fg%2F2018-08-01%2011.48.49.gif)
![image](https://user-images.githubusercontent.com/16830398/43499907-687cfbec-9580-11e8-8bae-f0faa8221efa.png)

Compare without Nuxt:

0. open http://localhost:7777/
1. click "1", that will stay page "index", because run "next('/one')" in router.beforeEach().
2. click "2", that will go to page "two", because run "next()" in router.beforeEach().
3. click "back" button of the browser, back to page "index".
4. click "3", that will redirect "http://localhost:7777/one", then stay in page "index"(correct).
5. type "http://localhost:3001/one" in browser, the same as step 4.
![image](http://23.83.248.199/%2Froot%2Fdownload%2Fshare%2Fg%2F2018-08-01%2011.50.18.gif)

### What is expected ?

The step 4 and 5 with Nuxt is same as the step 4 and 5 without Nuxt.

### What is actually happening?

 It will show "This page could not be found" error in the step 4 and 5 in with Nuxt.

### Additional comments?

When error, in client.js:424 (case 18:), the router.currentRoute is always '/', not the target route path.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7477">#c7477</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @xachary 

Thank you for the reproduction repo, it helps a lot.

In nuxt.js, we do some special stuff before mounting the app in SPA mode, so some things differs, also, we don't recommend to use `router.beforeEach` and using `next` because of our internal logic with `fetch/asyncData`.

You can do the same behaviour with the [nuxt middleware](https://nuxtjs.org/guide/routing#middleware).

`middleware/redirect.js`:
```js
export default function ({ route, redirect }) {
  if (route.path === '/one') {
    redirect('/')
  }
}
```

`nuxt.config.js`:
```js
// ...
router: {
  middleware: ['redirect']
}
// ...
```

And voila :)
