### ISSUE TITLE
easy way to bring vanilla nuxt app to its knees

### ISSUE THREAD

**Issue by jameshhood** [nuxt/nuxt.js#3627]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://nuxtjs.org/guide/installation](https://nuxtjs.org/guide/installation)

### Steps to reproduce

install app using CLI
cd into directory
run npm install
run npm run dev

at this point the dev sever should be running

open browser tab (i use chrome) and launch app http://localhost:3000
verify that you can see app and its working as intended

launch app in several tabs in quick succession
On a mac using Chrome, you can achieve this by hitting command + l followed by command + enter

### What is expected ?

Able to access several instances of the app concurrently without faults

### What is actually happening?

opening 5-10+ tabs all requesting a new instance of the app will cause the app to fail and not function

### Additional comments?

For a while we were running into heap memory problems so we increased our heap to 8gb and then we ran into 
![image (2).png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/76ffdd90-969a-11e8-a54f-a9b128da645f.png)
we've been using the methods listed in the reproduction steps to simulate several users hitting the system at once to stress test it, but we've never been able to do so. We thought it might be a 3rd party library causing the situation so i created blank cli projects for starters and thats where I found out that nuxt out of the box cant handle this situation very well. Some basic info on what my app is actually using: nuxt 1.4.2, node: 8.11.3, nuxtjs/axios module: 5.3.1, js-cookie: 2.2.0, jwt-decode: 2.2.0, vuetify: 1.1.9

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7484">#c7484</a>)</em></sub></div>

**Comment by manniL** [comment]
Does this happen in production mode (`npm run build && npm run start`) as well? :thinking:

**Comment by jameshhood** [comment]
Does not appear so 🤔

**Comment by manniL** [comment]
Wouldn't see it as a bug then :relaxed:
