### ISSUE TITLE
No documentation of ignorePrefix option

### ISSUE THREAD

**Issue by fzembow** [nuxt/nuxt.js#3631]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://nuxtjs.org/guide/configuration/](https://nuxtjs.org/guide/configuration/)

### Steps to reproduce

In https://github.com/nuxt/nuxt.js/pull/2417, an option `ignorePrefix` was added, to remove files whose filenames begin with that from routing, layout and stores.

But if you go to https://nuxtjs.org/guide/routing/ there is nothing about it. I would also expect something in https://nuxtjs.org/guide/configuration/

### What is expected ?

I would expect a sentence about ignoring pages in the documentation

### What is actually happening?

The configuration option is undocumented and can only be found by googling github

### Additional comments?

FWIW I agree with some of the comments from others about "-" being a poor filename prefix (because in the terminal it is interpreted as a flag) so this may be a good opportunity to revisit that.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7491">#c7491</a>)</em></sub></div>

**Comment by manniL** [comment]
Why not add it to the docs by yourself as you now know about the feature? :relaxed: 

PRs for https://github.com/nuxt/docs/ are always open and happily seen :ok_hand:

**Comment by Atinux** [comment]
A PR would be awesome 🙌

**Comment by fzembow** [comment]
Ah, I see that someone already added documentation to source (https://github.com/nuxt/docs/blob/master/en/api/configuration-ignore.md), it just hasn't deployed yet to [nuxtjs.org/api](https://nuxtjs.org/api)?

Not sure how docs deployment works here, @manniL @Atinux. Closing this out as there's nothing for me to do. Might be good to add meta-documentation to https://github.com/nuxt/nuxtjs.org on how the docs actually get released :)

Anyways, I have the site running locally now so it should be easier to fix things in the future!

**Comment by Atinux** [comment]
Could you add the link into https://github.com/nuxt/docs/blob/master/en/api/menu.json please :) ?

**Comment by fzembow** [comment]
Thanks for the pointer. See https://github.com/nuxt/docs/pull/686 please!
