### ISSUE TITLE
Setting up vue-play/vue-play-cli in nuxt.js project

### ISSUE THREAD

**Issue by LouiseStroeh** [nuxt/nuxt.js#364]
Hi
I am trying to set up vue-play using vue-play-cli in a nuxt.js project, but it is failing, stating that `Module not found: Error: Cannot resolve module 'scss-loader'`. Does anyone has any experience setting vue-play up when using nuxt.js? In the vue-play-cli docs, it says that you can merge your webpack config into the vue-play-cli base config, but where to find this in the nuxt.js project?

**Comment by apertureless** [comment]
Well, have you tried to install the scss-loader 😅  ?

**Comment by LouiseStroeh** [comment]
Yes. But I don't even know if this issue should be posted here, since it seems to be a vue-play/vue-play-cli issue: https://github.com/vue-play/vue-play/issues/37
