### ISSUE TITLE
Add 'Remove "-image" to background' option or remove '-image' suffix to background property to loadingIndicator

### ISSUE THREAD

**Issue by potato4d** [nuxt/nuxt.js#3649]
### What problem does this feature solve?

I would like to use gradient and images as a background of loadingIndicator.
However, the background property of the loadingIndicator template is currently attached with -image suffix and it can not be done.
https://github.com/nuxt/nuxt.js/blob/dev/lib/app/views/loading/circle.html#L3

### What does the proposed changes look like?

I'd like to Implement function and submit a Pull Request.
The function content is to delete the -image suffix, or add the option of `{image: true}` to lodindIndicator.

Is this reasonable?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7512">#c7512</a>)</em></sub></div>

**Comment by manniL** [comment]
@potato4d Do it :relaxed:

**Comment by potato4d** [comment]
@manniL 
If this is reasonable, I will do it myself!

**Comment by potato4d** [comment]
👍

**Comment by potato4d** [comment]
@Atinux 

Thank you for reply.
The `-image` I refer to is the style of loadingIndicator templates.
e.g.) https://github.com/nuxt/nuxt.js/blob/dev/lib/app/views/loading/chasing-dots.html#L3

**Comment by Atinux** [comment]
Oh I see, so I suggest removing `-color` and only keeping `background: <%= options.background %>;`.

This way, you will be able to define `background: image('...')` :)

**Comment by potato4d** [comment]
@Atinux 

It's breaking changes, Can I do it?

**Comment by Atinux** [comment]
It's not a breaking change, you can do `background: blue;`, see https://www.w3schools.com/CSSref/css3_pr_background.asp

![screen shot 2018-08-08 at 18 05 23](https://user-images.githubusercontent.com/904724/43849428-a70218ba-9b35-11e8-9701-e136b3359545.png)

So of course you can make a PR :)

**Comment by potato4d** [comment]
@Atinux 
OK, then I will send it.
Thanks!
