### ISSUE TITLE
How to debug server code  with node --inspect with source map in chrome

### ISSUE THREAD

**Issue by lazycrazy** [nuxt/nuxt.js#365]
Hi,I usually use node-inspector to debug nodejs code.
nuxt.js demo can't work in it.
the source map can't correct load in chrome.
i think the server not provide webpack:///. url parse.
**how to debug server-side code with chrome by source map?**

**Comment by rmartins90** [comment]
Have you find any solution for this @lazycrazy?

**Comment by Atinux** [comment]
In the 0.10 (coming in 1 hour), the source maps is given to the SSR now.
