### ISSUE TITLE
Relative imports in plugin not working properly

### ISSUE THREAD

**Issue by kavalcante** [nuxt/nuxt.js#3659]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/kavalcante/nuxt-import-error](https://github.com/kavalcante/nuxt-import-error)

### Steps to reproduce

Install dependecies and run the project.

When importing a relative path from any dependency, like this:

```js
import component from '`LIB`/`relative path`/`ANY FILE`';
```

The import is not working, but solves when importing like this:

```js
import component from '../node_modules/`LIB`/`relative path`/`ANY FILE`';
```

See a live example just running the project on the reproduce link.

### What is expected ?

Relative import should work like when is doing inside a component.

### What is actually happening?

It's breaks the compilation, already been test with Element UI and Bootstrap Vue, see issues in apollo-module: [#141](https://github.com/nuxt-community/apollo-module/issues/141) and [#140](https://github.com/nuxt-community/apollo-module/issues/140)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7519">#c7519</a>)</em></sub></div>

**Comment by heww** [comment]
why this closed? in nuxt-edge it still exist.

**Comment by galvez** [comment]
@kavalcante this is related to https://github.com/vuejs/vue-style-loader/pull/30 -- I think @clarkdo is already working on a solution for this, can you chime in @clarkdo?
