### ISSUE TITLE
Use lru-cache to save nuxt.render() result?

### ISSUE THREAD

**Issue by chesscai** [nuxt/nuxt.js#3662]
Hello.
I use `lru-cache` to cache nuxt render page.
How can I get the html result of `nuxt.render()` as `renderer.renderToString()` ?

In docs:
```javascript
renderer.renderToString((err, html) => {
    res.end(html)
    if (cacheable) {
      microCache.set(req.url, html)
    }
})
```

```javascript
// It should return a `Promise` but it's `undefined`
nuxt.render(ctx.req, ctx.res)

// some other solvetion of `Promise`
nuxt.render(ctx.req, ctx.res, promise => {
    // Not working here
})
```

**Comment by Atinux** [comment]
`nuxt.render` is the middleware and does not send back the html, you want to use `nuxt.renderRoute(req.url)`.

See https://nuxtjs.org/api/nuxt-render-route
