### ISSUE TITLE
Spinner was not put right place

### ISSUE THREAD

**Issue by TranChiNam** [nuxt/nuxt.js#3665]
### What problem does this feature solve?

Spinner is lie on the right of the screen on IE 11

### What does the proposed changes look like?

change css in .spinner look like:

.spinner {
  /*margin: 100px auto;*/
  width: 50px;
  height: 40px;
  text-align: center;
  font-size: 10px;	
  margin: auto auto;
  position: absolute;
}

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7523">#c7523</a>)</em></sub></div>

**Comment by manniL** [comment]
@TranChiNam Why don't you submit a PR for that? :relaxed:
