### ISSUE TITLE
<no-ssr> when check multiple default slot(no named) children , no tag, no name element counted Illegally.

### ISSUE THREAD

**Issue by GeneralworksInc** [nuxt/nuxt.js#3666]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/GeneralworksInc/nuxt_nossr_error_sample](https://github.com/GeneralworksInc/nuxt_nossr_error_sample)

### Steps to reproduce

ex1.
```
<no-ssr>
   <span id="first" >is default slot. rendered on cliend</span>
   <span id="second" slot="placeholder" class="c-form__txtarea" > placeholder on SSR </span>
</no-ssr>
```

in dev mode,  $slots.default.length is 2, and js error occured ( in no-ssr module).
```
 <no-ssr> You cannot use multiple child components
    at Proxy.render (no-ssr.js:20)
```

ex2.  
```
<no-ssr>
   <span id="first" >is default slot. rendered on cliend</span><span id="second" slot="placeholder" class="c-form__txtarea" > placeholder on SSR </span>
</no-ssr>
```

$slots.default.length is 1, and no error occured.

### What is expected ?

in ex1,
$slots.default.length is 1.

The default property expected to contain any nodes not included in a named slot.
( https://vuejs.org/v2/api/#vm-slots )

### What is actually happening?

in ex1, error occured because  vm.$slots.default.length is 2.

vm.$slots.default has 2 elements(one is "id:first" span tag, and no tag,no text element).

on ex2,  vm.$slots.default.length is 1.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7525">#c7525</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Nuxt is using [vue-no-ssr](https://github.com/egoist/vue-no-ssr#usage) as the no-ssr component, per the document:

> Note that `<no-ssr />` can only contain at most ONE child component/element.

**Comment by clarkdo** [comment]
Thank you for the reminding, I'll add some descriptions in nuxt docs.
