### ISSUE TITLE
What kind of database management system would you recommend?

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#367]
First of all, thank you for your work. You are awesome!

I'm just starting to learn your framework and I'm not quite sure how to use the database. I want to create a simple service with registration and saving some settings individually for each user.

Which DBMS is usually used together with Nukht? And how exactly?

**Comment by BRKsDeadPool** [comment]
What if you use the templates ? like the adonuxt. Adonis is awesome, and database (almost) ready, just choose the driver and download the package, then you can create your api just like any other adonis aplication, with api routes... at least on a simpler project.

Or you can create your own template with your platform or framework of choice using nuxt as a middleware

**sorry my bad english**

**Comment by cawa-93** [comment]
@BRKsDeadPool Thanks! It's almost what I need.
