### ISSUE TITLE
Development instructions

### ISSUE THREAD

**Issue by John0x** [nuxt/nuxt.js#368]
Hey, I'd love to contribute to nuxt.js, adding proper support for typescript etc.

Though I can't seem to get nuxt.js running locally.
I cloned the repository, created a branch at the v0.9.9 tag and linked it to my demo project using ``yarn link`` in the nuxt project and then ``yarn link nuxt`` in the demo project.
The project builds just fine (``nuxt`` command), but it cannot find the plugins at runtime.

It would be great to have a little readme on how to get it running to be able to contribute to the project.

**Comment by sebastianmacias** [comment]
The [starter](https://github.com/nuxt/starter) would help you get started quickly. I haven't tried installing the dependencies with yarn but npm install works fine.

Having typescript support in nuxt.js would be amazing.

**Comment by John0x** [comment]
@sebastianmacias I meant developing nuxt itself, not using it.

**Comment by alexchopin** [comment]
Hi @John0x, that's true we need to add some instructions for contributing. We will work on it. 👍

**Comment by John0x** [comment]
@alexchopin great, thank you :)
Could you give me some direction on getting it running locally?
I couldn't get it to work (see first comment).

**Comment by Atinux** [comment]
@John0x 

Installation:
```bash
git clone https://github.com/nuxt/nuxt.js.git
cd nuxt.js/
yarn
```

When updating nuxt.js:
```bash
npm run build # or npm run watch
```

Launching the tests:
```bash
npm test
```

Testing some examples:
```bash
bin/nuxt examples/hello-world/
```

I will take a look for `npm link`and come back to you.

**Comment by John0x** [comment]
@Atinux thank you :)
Any news regarding the ``npm link`` problem?
I don't really want to setup typescript within the nuxt project itself.

**Comment by johnlindquist** [comment]
@Atinux I'm having the same `yarn link` issue trying to get my nuxt-typescript-starter running...

It led me to this: http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies

but that still didn't fix it...

**Comment by Atinux** [comment]
To use `npm link nuxt`, you need to add an extra step (only while using `npm link`) into your application:

`nuxt.config.js`
```js
module.exports = {
  build: {
    extend (config) {
      config.externals = []
    }
  }
}
```
