### ISSUE TITLE
Relative path 

### ISSUE THREAD

**Issue by medve-dev** [nuxt/nuxt.js#3686]
I can not make paths relative to my url

I really need the paths of static files to be ./

I initially do not know which way will be issued by the server

 router:{
    mode:'hash',
    base:'./'
  },

DONT WORK!

**Comment by medve-dev** [comment]
???

**Comment by paulgv** [comment]
Archiving this duplicate question in favor of https://cmty.app/nuxt/nuxt.js/issues/c7534
