### ISSUE TITLE
When will nuxt 2.0 be released?

### ISSUE THREAD

**Issue by zwl1619** [nuxt/nuxt.js#3689]
When will nuxt 2.0 be released?

**Comment by paulgv** [comment]
The team has delayed the official release to fix some bugs in nuxt-edge: https://twitter.com/nuxt_js/status/1027209607532478466
You can probably expect a release in the coming weeks but you probably won't know the date until it's out.
More info: https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67
