### ISSUE TITLE
How does "precommit" script work in package.json?

### ISSUE THREAD

**Issue by shirohana** [nuxt/nuxt.js#369]
Excuse me.
I'm confused about the "precommit" script in package.json:

    "precommit": "npm run lint",

How can I trigger this script?
Like executing `npm run precommit`? Or add a hook in .git manually?

What is the best practice to do?
And what is your way to trigger this script?

Thanks first ฅ' ω 'ฅ

**Comment by ausir0726** [comment]
for my experience

I had use hook at pre-commit package
like this http://elijahmanor.com/npm-precommit-scripts/
but ,
I think I don't have a good coding style . so ,
sometimes when I commit my code with a little long message ,
but it lint error and reject my commit ... so , I need fixed my code first , and .... 
I forgot my what is my commit message ...
so , Now I will lint first , make sure it ok then commit .

thanks god we had nuxt live eslint , Now, we just only need fix nuxt.config.js  XD
maybe I can lint precommit use hook again...  :D

**Comment by shirohana** [comment]
hello ฅ' ω 'ฅ

If I'm going to make a larger commit, I usually write the commit message with an editor.
The precommit hook will run linter first and open my editor after lint successfully.

so, why your linter reject your commit but allow you present your commit message (´・д・｀)
If you commit with `-m` option, it is easy to get your commit message back, why you lost your commit message (´・ω・｀)

Thanks for your suggestion,
In fact, I've read the article of your link before.
but I don't find the 'pre-commit' package in this project, so I issue this question XD

**Comment by ausir0726** [comment]
for a stupid example :D
I use git commit -am 'bula bula bula ... maybe not to long , but write something'
then ... It reject my commit .
but I have something important than fix my code . when I fixed my code 
maybe 2 or 3 hours later :D ( or 1 day 2 day later ? @@ )
maybe I remember want is major function , but will lose some information than before.
( no live lint project )

by the way 
maybe @alexchopin just add pre-commit for a hint .

**Comment by shirohana** [comment]
I understand XD
maybe you can use multiple panes or windows in your case ฅ' ω 'ฅ

I usually use three window, totally five panes as the same time.
The first one of the windows is use as my main editor,
the second one is splitted into three panes and each one has different usage,
tnd the last one is for a large commit, like squash commits of dev-branch.
