### ISSUE TITLE
li tags don't close with nuxt generate

### ISSUE THREAD

**Issue by ta-run** [nuxt/nuxt.js#3690]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce

Add a ul > li in index.vue (with the basic start kit)

```
<template>
  <section class="container">
    <div>
      <app-logo/>
      <h1 class="title">
        test
      </h1>
      <h2 class="subtitle">
        Nuxt.js project
      </h2>
      <div class="links">
        <a
          href="https://nuxtjs.org/"
          target="_blank"
          class="button--green">Documentation</a>
        <a
          href="https://github.com/nuxt/nuxt.js"
          target="_blank"
          class="button--grey">GitHub</a>
          <ul>
            <li>
              Documentation
            </li>
            <li>Github</li>
          </ul>
      </div>
    </div>
  </section>
</template>
```

When `npm run generate` is executed, the output in dist folder looks like,

```
<div class="links">
  <a class="button--green" href="https://nuxtjs.org/" target="_blank">Documentation</a>
  <a class="button--grey" href="https://github.com/nuxt/nuxt.js" target="_blank">GitHub</a>
  <ul>
    <li>Documentation
    <li>Github</ul>
</div>
```

### What is expected ?

Tags should close correctly

### What is actually happening?

Tags isn't closing properly

### Additional comments?

Issue observed only with ul > li for now. Not sure how I can provide a reproduction link for a nuxt generate example - apologies in advance.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7538">#c7538</a>)</em></sub></div>

**Comment by manniL** [comment]
Can reproduce this with latest `nuxt-edge`

**Comment by manniL** [comment]
This is intended, as HTML is minified (see [the docs](https://nuxtjs.org/api/configuration-generate#minify)). The HTML is also valid, as the `</li>` tag is optional in your case [source](https://stackoverflow.com/questions/20550788/does-the-li-tag-in-html-have-an-ending-tag#20550925).
