### ISSUE TITLE
Configure PORT and HOST in nuxt.config.js

### ISSUE THREAD

**Issue by antfu** [nuxt/nuxt.js#3698]
### What problem does this feature solve?

Currently the [doc](https://nuxtjs.org/faq/host-port#how-to-edit-host-and-port-) says PORT and HOST can be set in `package.json` and npm scripts. Which is hard to change base on environment.

Allowing setting port and host in `nuxt.config.js` can be more flexible since it's javascript.

### What does the proposed changes look like?

Extra fields in `nuxt.config.js` to specify PORT and HOST.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7541">#c7541</a>)</em></sub></div>

**Comment by manniL** [comment]
This sounds like a good first issue! :relaxed: 

I've recently implemented `NUXT_PORT` and `NUXT_HOST` (higher priority then environment variables `PORT` and `HOST`.

Would love to see a PR from you taking on the custom fields.
[This file](https://github.com/nuxt/nuxt.js/blob/ec52104ec1d046af94decdbb83328e18b40cb1c5/bin/common/utils.js#L49) will help you I think :+1:

**Comment by antfu** [comment]
Would love to make a PR!

The `env` option in `nuxt.config.js` will expose to both server and client sides. Which I think, it's not ideal for security propose. Should we have a new option for server config or sever side env?

**Proposal 1**
```js
module.exports = {
  server: {
    // nuxt.js server options ( can be overrided by environment variables )
    port: 8000,
    host: "0.0.0.0",
  },
  env: {
    FOO: "bar"
  },
}
```

**Proposal 2**
```js
module.exports = {
  // only available to server side 
  serverEnv: {
    PORT: 8000,
    HOST: "0.0.0.0",
    FOO1: "bar",
    // other env
  },
  // avaliable to both client and server
  env: {
    FOO2: "bar",
  }
}
```
