### ISSUE TITLE
Dynamic Nested Routes Not Support

### ISSUE THREAD

**Issue by fengyuanzemin** [nuxt/nuxt.js#3702]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[null](null)

### Steps to reproduce

my pages 

![屏幕快照 2018-08-12 18.27.32.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/5f7c7390-9e1a-11e8-aabb-05ebdcd3233f.png)

### What is expected ?

```
routes: [
		{
			path: "/brand/brief/:categoryId/:brandId",
			component: "pages/brand/brief/_category/_brandId/index.vue",
			name: "brand-brief-categoryId-brandId"
		},
],  
```

### What is actually happening?

```
routes: [
		{
			path: "/brand/brief/:categoryId?/:brandId?",
			component: "pages/brand/brief/_category/_brandId/index.vue",
			name: "brand-brief-categoryId-brandId"
		},
],  
```

### Additional comments?

I dont want that '?' , is that a bug?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7543">#c7543</a>)</em></sub></div>

**Comment by manniL** [comment]
This is no bug. :relaxed: 

As you don't have other pages defined yet, the dynamic variables are `optional`, so `brand/brief/`, `/brand/brief/a/` and `/brand/brief/a/b/` will all link to the `index.vue`. As soon as you set these up (f.ex. `pages/brand/brief/_category/index.vue` ) the `?` will vanish from the route and the parameters will become mandatory.

Alternatively, you can set up [route validation](https://nuxtjs.org/guide/routing#validate-route-params)

**Comment by fengyuanzemin** [comment]
OK，thx🤝。 I used the extendRoutes to do this. like that: 

```js
  router: {
    extendRoutes () {
      return [
        {
          path: '/brand/brief/:categoryId/:brandId',
          component: resolve(__dirname, 'pages/brand/brief/index.vue'),
          name: 'brand-brief'
        }
      ]
    }
  },
```
That's another way.
