### ISSUE TITLE
SCSS import from assets

### ISSUE THREAD

**Issue by AlexeyShalik** [nuxt/nuxt.js#3703]
I want to create common scss file with default options, because I want to use options from this file in Vue Components.

Example:

assets/scss/main.scss

$background-color: black;

components/Navbar.vue

<style>
  import 'main.scss';

  .navbar {
    background-color: $background-color;
  }

</style>

None of the options proposed in the issues didn't help me

**Comment by paulgv** [comment]
Make sure your path are correct and that you're using valid SCSS syntax:

```vue
<style lang="scss">
@import "~/assets/scss/main.scss";
.navbar {
  background-color: $background-color;
}
</style>
```

You'll also need to install node-sass and sass-loader if you haven't already:

```sh
yarn add node-sass sass-loader -D
```

**Comment by AlexeyShalik** [comment]
@paulgv, thank you!
