### ISSUE TITLE
nuxt doesn't support right click event

### ISSUE THREAD

**Issue by TonyLuo** [nuxt/nuxt.js#3708]
### What problem does this feature solve?

nuxt doesn't support right click event, it will not fire right click event. the following code works in vue page, but doesn't work in nuxt page
 ```
 <div @click="onSelect(item,index)" class="tab" @click.right.stop.prevent="onRightClick($event,item,index)" >
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7550">#c7550</a>)</em></sub></div>

**Comment by paulgv** [comment]
It does. If it doesn't for you, you might have done an error somewhere else, please share more of your code (ideally the complete Vue file) so we can help you.

**Comment by TonyLuo** [comment]
the code is very simple
```
<template>
    <div @click.right.stop.prevent="onRightClick">
        test right click
    </div>
</template>
<script>
export default {
    methods:{
        onRightClick(){
            console.log('onRightClick')

        }
    }
}
</script>
```

error:
```
ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-5b17f64c","hasScoped":false,"preserveWhitespace":false}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./pages/setting/index.vue
(Emitted value instead of an instance of Error) 
  Error compiling template:
  
  <div @click.right.stop.prevent="onRightClick">
      test right click
  </div>
  
  - Use "contextmenu" instead of "click.right" since right clicks do not actually fire "click" events.

 @ ./pages/setting/index.vue 6:0-245
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js

```

**Comment by paulgv** [comment]
Seems related to these issues:

- https://github.com/vuejs/vue/issues/5330
- https://github.com/vuejs/vue/issues/7020

What version of Nuxt/Vue are you using?

**Comment by TonyLuo** [comment]
thanks for update.
 i just check the version, i use the example-auth0 as template, 
in package.json,  "nuxt": "latest",  it will download the 1.0.0.rc  version.     -_-||.

I just update the nuxt version to be  "nuxt": "^1.4.2",  it works now. 

thanks !!!
