### ISSUE TITLE
cmty error when filing issue

### ISSUE THREAD

**Issue by MichaelJCole** [nuxt/nuxt.js#3710]
See also here:  https://github.com/nuxt/docs/issues/701

The "Version" field is required, but there are no valid options so it doesn't work.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7552">#c7552</a>)</em></sub></div>

**Comment by manniL** [comment]
@MichaelJCole You can insert "any" version you want, even if it isn't suggested.
