### ISSUE TITLE
middleware can't work

### ISSUE THREAD

**Issue by heavenlian** [nuxt/nuxt.js#3712]
nuxt.config.js: 
route:{ middleware : 'index' } 
middleware/index
export defaut function(){
   console.log('U DONE')
  return
}
------------------------------------------
when I jump the route to another，nothing happen。 Just I fresh the browser   ， it can't work.

**Comment by paulgv** [comment]
What behaviour do you expect? When you refresh the page manually, the log should appear in your terminal (server-side), when you navigate from one route to another via `<nuxt-link>`s, logs appear in the browser's console (client-side).

**Comment by heavenlian** [comment]
@paulgv ,  I want to get the req or res no matter from client or server. I don't to want to get the secret-key from the store.

**Comment by heavenlian** [comment]
@paulgv , I want to get the req or res no matter from client or server. I don't  want to get the secret-key from the store.
