### ISSUE TITLE
terminal stuck with no error message

### ISSUE THREAD

**Issue by MarvinXu** [nuxt/nuxt.js#3714]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[http://no-link](http://no-link)

### Steps to reproduce

```js
// nuxt.config.js
module.exports = {
  css: ['~/assets/something-doesnt-exist']
}
```
`npm run dev`

### What is expected ?

show an error in the terminal

### What is actually happening?

terminal stuck with no error message

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7556">#c7556</a>)</em></sub></div>

**Comment by MarvinXu** [comment]
![image](https://user-images.githubusercontent.com/7382357/44032654-665847a4-9f3a-11e8-864b-442b365a942d.png)
It doesn't show an error message until I press `ctrl+c`

**Comment by galvez** [comment]
@clarkdo @manniL @Atinux I'll add a PR similar to the plugins one for this later today.

**Comment by galvez** [comment]
@MarvinXu should be resolved in the upcoming release of Nuxt.

**Comment by Atinux** [comment]
@clarkdo I guess there is something wrong displaying Webpack errors?

**Comment by galvez** [comment]
Nope, the error appears -- it just really hangs. My PR should solve this.

**Comment by clarkdo** [comment]
I think the issue should be that buffer didn't get flushed. I'll have a look

**Comment by clarkdo** [comment]
@MarvinXu Are you using nuxt-edge ? I have tried in my local with nuxt-edge and both mac and windows, it works correctly:
![image](https://user-images.githubusercontent.com/4312154/44084880-dad460c0-9faf-11e8-82e7-7a16f91172f4.png)

**Comment by MarvinXu** [comment]
@clarkdo no, I'm using v1.4.2

**Comment by MarvinXu** [comment]
![image](https://user-images.githubusercontent.com/7382357/44088999-ce0066da-9ff7-11e8-8f25-ffad74266ea6.png)
I just found another hanging situation. Maybe It's not just css file, but any file missing could hang the terminal.
If this won't be a problem in nuxt@2.0, don't bother. I can wait for 2.0.
