### ISSUE TITLE
SSR Sourcemap

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#373]
there are times when errors occur during server side rendering. the output is currently not readable and unless you were just working on something that triggered the issue, it is impossible to tell where the errors are coming from. Is it possible to include sourcemaps on the server side code? 

If this is not possible, what is the right way to debug ssr errors?

**Comment by alexchopin** [comment]
Are you talking about Server issues or Vue SSR issues?

**Comment by Atinux** [comment]
I am actually implementing Vue 2.2 with SSR sourcemaps, so this issue should be fixed with the upcoming release @uptownhr

**Comment by uptownhr** [comment]
awesome!

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋
