### ISSUE TITLE
[edge] Node error when exiting development server via Control+C

### ISSUE THREAD

**Issue by markplewis** [nuxt/nuxt.js#3733]
### Version

~~[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)~~
`nuxt-edge@2.0.0-25572233.1492a13`

### Reproduction link

[http://localhost:3000](http://localhost:3000)

### Steps to reproduce

Running `nuxt-edge@2.0.0-25572233.1492a13` on Node 10.8.0 and NPM 6.2.0:

1. Start the development server via `npm run dev`.
2. Wait for everything to compile and the "Listening on http://localhost:3000" to appear.
3. Stop the development server by typing Control + C.
4. You'll see the following error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! your-project@1.0.0 dev: `nuxt`
npm ERR! Exit status 130
npm ERR!
npm ERR! Failed at the your-project@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### What is expected ?

The development server should exit without throwing an error.

### What is actually happening?

An error is being thrown when the development server exits.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7572">#c7572</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce this locally (using `nuxt-edge 2.0.0-25572329.f9637a1`) on Linux. Could you provide a minimal reproduction/example repo? :relaxed:

**Comment by aldarund** [comment]
http://www.tldp.org/LDP/abs/html/exitcodes.html
130	Script terminated by Control-C	Ctl-C

**Comment by markplewis** [comment]
This no longer seems to be an issue with `nuxt-edge@2.0.0-25581056.bba9e2b` and nobody else is able to reproduce it, so I think we can close this issue.
