### ISSUE TITLE
Update style-resources-loader to 1.2.1

### ISSUE THREAD

**Issue by nathanchase** [nuxt/nuxt.js#3737]
### What problem does this feature solve?

The creator of style-resources-loader added support for .CSS files (for PostCSS variables/mixins/custom media/etc. importing): 
https://github.com/yenshih/style-resources-loader/issues/7

Please update the version in Nuxt so that we can reference PostCSS .css files in the `styleResources` block of `build` configuration as outlined here:
https://nuxtjs.org/api/configuration-build/

### What does the proposed changes look like?

**package.json**

"style-resources-loader": "^1.2.1",

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7576">#c7576</a>)</em></sub></div>

**Comment by manniL** [comment]
@nathanchase Happy to see a PR :wink:

**Comment by nathanchase** [comment]
@manniL Done! 

https://github.com/nuxt/nuxt.js/pull/3738

My first pull request, actually. Hope I did it right!

**Comment by Atinux** [comment]
You rock @nathanchase !
