### ISSUE TITLE
Seperate css files for layouts

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#374]
When using layouts, I'd like to be able to separate out my app js/css files from my www js/css files. Is this possible in nuxt?

**Comment by alexchopin** [comment]
Can you explain more about your issue?

**Comment by uptownhr** [comment]
Ultimately, if I want to have my www, ie landing page and my app, within one nuxt project, am I able to have a separate build entry for www to minimize it's size from the app? I don't want a 500k app.js / css file to add the landing page.

**Comment by alexchopin** [comment]
Related to this #12
