### ISSUE TITLE
[edge] Plugins in coffeescript not found

### ISSUE THREAD

**Issue by chabib** [nuxt/nuxt.js#3742]
### Version

[nuxt-edge 2.0.0-25573542.e9bb9e7](https://github.com/nuxt.js/releases/tag/nuxt-edge 2.0.0-25573542.e9bb9e7)

### Reproduction link

[https://github.com/chabib/nuxt-edge-bug](https://github.com/chabib/nuxt-edge-bug)

### Steps to reproduce

1. Clone repo
2. Install dependencies
3. Run nuxt dev server

### What is expected ?

Build success

### What is actually happening?

Build failed
error Error: Plugin not found: /path/plugins/initApp.js
  at Promise.all.plugins.map (/path/node_modules/nuxt-edge/dist/nuxt.js:3701:15)

### Additional comments?

Downgrading to nuxt-edge@2.0.0-25562603.52780d3 cancel the problem

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7583">#c7583</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Try to add extension: `~/plugins/initApp.coffee`

**Comment by chabib** [comment]
@clarkdo ok, thanks mate
