### ISSUE TITLE
Merge page meta into $route.meta

### ISSUE THREAD

**Issue by SteveEdson** [nuxt/nuxt.js#3751]
### What problem does this feature solve?

By merging:

```js
export default {
    meta: {
        foo: 'bar'
    }
};
```

from **pages** only, into the `$route.meta` data, so that it is available as `$route.meta.foo`, it would solve many problems such as being able to use page level data, outside of the page scope. For example:

```js
export default {
    meta: {
        theme: 'dark'
    }
};
```

The page layout could react to the `$route.meta.theme` value, and change the header and footer styles accordingly. This would also be useful for things like showing and hiding certain page elements such as footer menus, disclaimers etc etc.

### What does the proposed changes look like?

```js
export default {
    meta: {
        ...
    }
};
```

being merged into the existing `$route.meta` property.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7592">#c7592</a>)</em></sub></div>

**Comment by Atinux** [comment]
One thing to note is that a route can have multiple page components, so ˋ$route.meta` will be an array.

Also, I am thinking of moving it to `$nuxt.meta` since bye-router has its own logic: https://router.vuejs.org/guide/advanced/meta.html

**Comment by SteveEdson** [comment]
How can there be multiple page components for a route? Is that when nested routes or multiple router containers are used? If so, could the meta just exist for the scope of that router container?

That being said `$nuxt.meta` would also work. Rather than an array, would an object with the page names as keys be better? Might be easier to traverse, and can still be handled as an array easily with `Object.values`.

**Comment by galvez** [comment]
@Atinux I can see this being useful now, but am concerned about the case you mentioned earlier in Discord:

> Example: meta: [{ needAuth: false }, { needAuth: true }] will become meta: { needAuth: true }

**Comment by Atinux** [comment]
@SteveEdson please take a look at https://github.com/nuxt/nuxt.js/tree/dev/examples/routes-meta

I made an example with themes. I thought about adding `$nuxt.context` but at the end is less clear and does not track new added keys. So Vuex is the best for this and can be debugged with Vue devtools ;)

**Comment by mydesireiscoma** [comment]
Why this issue was closed?
Okay. You found solution for this case, but how about [other](https://github.com/nuxt/nuxt.js/issues/2552)  [cases](https://github.com/nuxt/nuxt.js/issues/1687#issuecomment-331870619)

I want to build breadcrumbs.
I need to access `meta` in `matched` routes.
I have access to `meta` only for current route.
I have no access to `meta` in `matched` routes.

So. What I have to do, to access `meta` in `matched` routes?
Actually, `route` in `matched` routes contains the `meta` property. But it always empty. What is for this empty property ? How I can fill it?

```
{
  "meta": {},
  "path": "/some/:cat?/:parts?",
  "regex": {
    "keys": [
      {
        "name": "cat",
        "prefix": "/",
        "delimiter": "/",
        "optional": true,
        "repeat": false,
        "partial": false,
        "asterisk": false,
        "pattern": "[^\\/]+?"
      },
      {
        "name": "parts",
        "prefix": "/",
        "delimiter": "/",
        "optional": true,
        "repeat": false,
        "partial": false,
        "asterisk": false,
        "pattern": "[^\\/]+?"
      }
    ]
  },
  "components": {},
  "instances": {},
  "name": "trololololo,
  "props": {}
}
```
