### ISSUE TITLE
Throw when plugin is not resolved 

### ISSUE THREAD

**Issue by LostCrew** [nuxt/nuxt.js#3755]
### What problem does this feature solve?

A missing plugin can lead to runtime error after Nuxt initialization.

### What does the proposed changes look like?

When a plugin path points to a missing file, Nuxt should throw an error instead of silently initialize.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7596">#c7596</a>)</em></sub></div>

**Comment by galvez** [comment]
@LostCrew this is fixed in nuxt-edge soon to be Nuxt 2. Stay tuned.
