### ISSUE TITLE
Accessing route properties in layout

### ISSUE THREAD

**Issue by SnappyCroissant** [nuxt/nuxt.js#376]
Is there an API for or best practice way to access route properties from inside layout files?

for example if I had a route structure where the top level route (eg: site.com/[this bit]/otherstuff) would change the tag line next to a logo.

I could make two seperate headers, but it seems a little redundant given how little data is changing and the fact it's only one bit of data. I could pass the value into it across multiple pages but that's a lot of repetition of data as pages grow. It seems to make far more sense to have a context aware header.

Is this possible?

**Comment by rohitpal99** [comment]
I think you can do it via vuex. Can access param from data method if route is configured as regex.

**Comment by SnappyCroissant** [comment]
I wound up just making a router middleware that stored route.mached[0].name in the store. I couldn't find access directly to the route object in the store or data method.

(I could access via page component data methods but not the layout.)

Thanks!

**Comment by tforssander** [comment]
@SnappyCroissant Any chance you could show some example?
