### ISSUE TITLE
Components rendering issues in the Layout

### ISSUE THREAD

**Issue by CoolGoose** [nuxt/nuxt.js#3764]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/CoolGoose/nuxtlayoutdebug](https://github.com/CoolGoose/nuxtlayoutdebug)

### Steps to reproduce

I've added a repo that contains the code.
I've used vuex-flash as an example, but it happened with a custom component as well.

### What is expected ?

Rendering the message in the layout as well

### What is actually happening?

It only renders in the page

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7600">#c7600</a>)</em></sub></div>

**Comment by manniL** [comment]
Result after cloning and running:

![image](https://user-images.githubusercontent.com/640208/44308440-e915f480-a3ad-11e8-97a9-7c9b7b11ac2c.png)

Looks right. Could you provide info what you **exactly** expected? :thinking:

**Comment by CoolGoose** [comment]
@manniL 

Sorry, i dropped the ball and forgot the crucial thing.

1. You need to go to /second
2. You will be redirected back to the homepage

Here's how it shows for me (note my awesome graphic skills)

![capture](https://user-images.githubusercontent.com/51180/44309811-fa262c00-a3d4-11e8-9b27-af3a0c6494b5.PNG)

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/44309857-ce02af00-a3c4-11e8-976b-ab36f2aa3d83.png)

After going to `/second` I see this. Looks still right :thinking:

**Comment by CoolGoose** [comment]
@manniL notice it says **some message 123 321** only on the inner component, not the big layout

**Comment by manniL** [comment]
@CoolGoose Ah! Now it got it :see_no_evil:

**Comment by manniL** [comment]
Can reproduce this in `nuxt-edge`, even if not directly accessing `/second` by typing the URL in.

Looks like the `layout` doesn't reflect changes of the Vuex store as long as the state isn't displayed. :thinking:

**Comment by CoolGoose** [comment]
Bumping for activity (and will try to re reproduce on 2.0)

**Comment by manniL** [comment]
@CoolGoose I'd suggest https://template.nuxtjs.org/ for that ☺️

**Comment by CoolGoose** [comment]
@manniL https://codesandbox.io/s/0qw4vx239n?initialpath=%2Fabout&module=%2Fpages%2Fabout.vue 
go to /about and then you'll notice the error still exists :D (renders fine in the page, not the layout)

**Comment by manniL** [comment]
@CoolGoose Could you try to reproduce it *without that library*?

**Comment by CoolGoose** [comment]
@manniL it seems that committing and displaying manually works. will try a bit later today to see if somehow vuex in single store mode with namespaced calls makes it weird.

**Comment by CoolGoose** [comment]
@manniL finally, I could reproduce it cleanly. 
Please go to https://codesandbox.io/s/0qw4vx239n and click about.

**Comment by manniL** [comment]
@CoolGoose it seems like wrapping it in a computed property will work fine :thinking: (https://codesandbox.io/s/ykxr52rr8x)

**Comment by CoolGoose** [comment]
@manniL 
From my testing simple keys with integers work fine even without computed. The problem is for objects.
Please see https://codesandbox.io/s/r019y31qrm and notice the `{ "info": [ "error" ] } ` message (also made it a computed in that component, but still no luck)

**Comment by manniL** [comment]
@CoolGoose Please check my CSB :relaxed: It works fine with objects as well

**Comment by manniL** [comment]
@CoolGoose Any update? Does it work for you as well now?

**Comment by CoolGoose** [comment]
@manniL I apologize for the delay, was a crazy last week and this weekend we went to an e-commerce connference. Will test these days and get back
