### ISSUE TITLE
Why is port 3000 used?

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#377]
Hello. I'm just starting to learn the nuxt.js, so forgive me for the stupid question:
Why is port 3000 used?
After all, if I build an application on a production server, and I want to make it available to the example.com address, then I need to use port 80. So why is port 3000 used? And how do I configure the application to make it accessible?

I try set env:
```json
"scripts": {
    "serve:dev": "PORT=80 HOST=localhost npm run dev",
    "dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js",
}
```
But in the process of compiling an error occurs:
```
info adonis:framework +0ms serving app on localhost:80
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:80
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at Server._listen2 (net.js:1263:19)
    at listen (net.js:1312:10)
    at doListening (net.js:1427:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by luminarious** [comment]
It's almost never a good idea to expose your web application directly. At the very least, using Nginx as a proxy gives you a cache (and even a 5-second cache means your site is better equipped for a traffic surge). It's also way easier to set up HTTPS this way (terminate HTTPS in proxy, connect to your Node machine or Node cluster via HTTP).

**Comment by cawa-93** [comment]
@luminarious, Thank you. It became much clearer. But it's not clear to me yet:
How do I restart the nuxt server? After all, if I make changes I need run
```
npm run build && npm start
```
But how to do this on a remote machine, if one server instance is already running? How to stop it?

**Comment by alexchopin** [comment]
This is not really an issue about Nuxt, it's more about help on Node.js in this case.
