### ISSUE TITLE
Allow layouts or the error layout to use fetch/asyncData

### ISSUE THREAD

**Issue by luishdz1010** [nuxt/nuxt.js#3776]
### What problem does this feature solve?

My error page lives in a `layout` that needs to pull data for menus/footer, since layouts can't have fetch/asyncData blocks I normally add the fetch logic to the pages that use a specific layout. However this workaround doesn't work for the error page since it is not a page, but a layout.

This can't be done on NuxtServerInit because:

a) requests dispatched in nuxtServerInit are blocking, i.e. nuxt waits until the promise returned from nuxtServerInit is resolved before continuing, which makes things x2 slower when a page has other requests to make (all requests can and should be run in parallel)
b) different layouts have different fetch needs
c) wouldn't work on SPA mode

Do you guys have any workaround for this? Currently, my 404 error pages render with an empty footer and menu.

### What does the proposed changes look like?

Add `fetch` and/or `asyncData` support to layouts, or at least the error layout.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7606">#c7606</a>)</em></sub></div>

**Comment by luishdz1010** [comment]
This is still a problem in v2

**Comment by domi91c** [comment]
Does anyone have a solution for this? I'm trying to get the item count for a shopping cart to put in my navbar.

**Comment by atmar** [comment]
Also looking for a solution for this problem. I have a profile layout that need to reload profile data every time the layout is loaded.

**Comment by Jesus82** [comment]
Hi, I solved my problem this way:
- In the layout page, in mounted(), I dispatch an action
- Then in the Vuex store, this action makes the Api call, and fires the mutation with the response
So, instead of having to wait for several API calls before start loading the page with nuxtServerInit, with this approach, the calls are made after the page has started loading (so loading is much fasters if you have several calls).

**Comment by luishdz1010** [comment]
The solution above doesn't work for SSR

**Comment by hecktarzuli** [comment]
I would say since the docs say to treat error.vue as a page comp, then this is really a bug, not a feature request :) . I have the exact same problem.

**Comment by hecktarzuli** [comment]
@luishdz1010 - Word is on the street that with @pi0 's latest merges the next version of Nuxt should allow fetch() on layout (and hopefully should be resolved with the page fetch in async)

**Comment by hecktarzuli** [comment]
Apparently this is waiting on https://github.com/vuejs/vue/pull/9017 :(

**Comment by jagreehal** [comment]
@manniL vue 2.6 is out now so can the 'waiting for dependency' label be removed?

**Comment by manniL** [comment]
@jagreehal Indeed!

**Comment by luishdz1010** [comment]
Seems to still be a problem in Nuxt 2.5 :(

**Comment by Almusamim** [comment]
> Hi, I solved my problem this way:
> 
> * In the layout page, in mounted(), I dispatch an action
> * Then in the Vuex store, this action makes the Api call, and fires the mutation with the response
>   So, instead of having to wait for several API calls before start loading the page with nuxtServerInit, with this approach, the calls are made after the page has started loading (so loading is much fasters if you have several calls).

Is there any example to see the code for this?

**Comment by snoopy83101** [comment]
https://cmty.app/nuxt/nuxt.js/issues/c8926
Maybe my problem will be solved as a result!

**Comment by JereMiO** [comment]
hi, is there any update on this issue ?

**Comment by starikovm** [comment]
For everyone who is stuck with that issue, you can use `serverPrefetch` of `Vue.js`.
Since Layout is a Vue component it will work.
Check documentation here
https://ssr.vuejs.org/guide/data.html#logic-collocation-with-components

**Comment by w11th** [comment]
I use anonymous middle to fetch data in layout on SPA mode, it worked for me. https://nuxtjs.org/api/pages-middleware#anonymous-middleware

**Comment by ashokpokharel977** [comment]
Have anyone got the solution? 
the fetch works on pages, but not on layouts

**Comment by quangvision** [comment]
Same problem for me here. To dispatch an actions on every pages could be cumbersome rather than doing it once on layout component.
