### ISSUE TITLE
Vuetify theme colors are not rendered properly

### ISSUE THREAD

**Issue by lobo-tuerto** [nuxt/nuxt.js#3777]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/with-vuetify](https://github.com/nuxt/nuxt.js/tree/dev/examples/with-vuetify)

### Steps to reproduce

I cloned the whole Nuxt repo at: https://github.com/nuxt/nuxt.js

Then navigated to: `nuxt.js/examples/with-vuetify`

Then installed dependencies with `yarn install` and ran the server with `yarn dev`.

Then opened `http://localhost:3000` and saw that no colors are being presented. It's all black and white.

If I have something like `<v-btn color="primary">Something</v-btn>` the text is not visible as it is colored white.

### What is expected ?

![Screenshot_2018-08-20 https nuxt-with-vuetify-example surge sh.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/1041e6d0-a4f4-11e8-ab89-c75ecc7c5a98.png)

### What is actually happening?

![Screenshot_2018-08-20 Screenshot.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/142cb590-a4f4-11e8-ab89-c75ecc7c5a98.png)

### Additional comments?

I'm on Linux Manjaro.
Node 10.9.0.
it's the same with Nuxt 1.4.2 or nuxt-edge.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7607">#c7607</a>)</em></sub></div>

**Comment by manniL** [comment]
Can reproduce.
