### ISSUE TITLE
Possibility to set rootDir via cli arg or in nuxt config file

### ISSUE THREAD

**Issue by JkmAS** [nuxt/nuxt.js#3778]
### What problem does this feature solve?

Nuxt.js (nuxt-edge) takes first arg as the rootDir by default `getRootDir = argv => resolve(argv._[0] || '.')` (https://nuxtjs.org/api/configuration-rootdir/).

I am using pm2-runtime process manager because of docker and cluster possibilities. But if I use pm2-runtime via `npm start: pm2-runtime pm2.config.json` in package.json file and I call `/node_modules/nuxt/bin/nuxt-start` script in pm2 config file, the nuxt will always search in `/my-project/pm2.config.json/` folder, because of bad `rootDir`.

The problem isn't there, if I use just one instance in cluster mode, then I can simply call `nuxt start` from pm2 config. In case of using more than one instance, you have to call script directly (via `/node_modules/nuxt/bin/nuxt-start`) in pm2 config to prevent EADDRINUSE error. It solves EADDRINUSE error, but not the rootDir one. Because there is no way to distinguish pm2 config and nuxt rootDir arg.

More info with solution for cluster with just one instance https://github.com/nuxt/nuxt.js/issues/2630

### What does the proposed changes look like?

It will be cool, if I will have an option to define `rootDir` via `--rootDir` arg or set it up in `nuxt config` file, because of pm2-runtime and nuxt args conflict.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7608">#c7608</a>)</em></sub></div>

**Comment by manniL** [comment]
@JkmAS Happy to see a pr for this :relaxed:

**Comment by axetroy** [comment]
Obviously, you can't configure rootDir now.

Caused a lot of problems, such as with PM2 or docker

**Comment by JkmAS** [comment]
@manniL I tried it without success. The problem is still in the `rootDir`.

**Comment by manniL** [comment]
You can already do this via `env variables`.

Example:

`nuxt.config.js`
```js
export default {
  rootDir: process.env.ROOT_DIR || undefined
}
```

Now you can set the env variable properly (`ROOT_DIR=test npm run dev`) and the root dir is set :relaxed:

**Comment by JkmAS** [comment]
Cool, maybe update [this doc](https://nuxtjs.org/api/configuration-rootdir#the-rootdir-property)

**Comment by JkmAS** [comment]
@manniL I am not sure, because this isn't work for me. And If I check the nuxt code, I still see this `resolve(argv._[0] || '.')` in `utils.js`. There is no rootDir

```
const getRootDir = argv => resolve(argv._[0] || '.')
const getNuxtConfigFile = argv => resolve(getRootDir(argv), argv['config-file']);
```

**Comment by manniL** [comment]
@JkmAS Please try it with `nuxt-edge` :relaxed:

**Comment by manniL** [comment]
@JkmAS Sorry that the proposed solution didn't fully solve your problem

**Comment by JkmAS** [comment]
Ok, I could. I suppose this should be enough: 
`utils.js` - `const getRootDir = argv => resolve(process.env.ROOT_DIR || argv._[0] || '.')`

and in pm2 config file something like:
```js
module.exports = {
  apps: [
    {
      name: 'nodeApp',
      script: './node_modules/nuxt-edge/bin/nuxt-start', // script for nuxt start
      exec_mode: 'cluster', 
      watch: false,
      instances: 'max', 
      merge_logs: true, 
      log_type: 'raw',
      cwd: './',
      env: {
        ROOT_DIR: __dirname
      }
    }
  ]
};

```

@manniL what is the current nuxt-edge dev branch?

**Comment by manniL** [comment]
@JkmAS It's `dev` :relaxed:

**Comment by Atinux** [comment]
We could implement this, but I prefer that the `env` is called `NUXT_ROOT_DIR` (https://github.com/nuxt/nuxt.js/blob/dev/bin/common/utils.js#L14), but that should be after `argv._[0]` and you run pm2 without giving the path.

What do you think?

**Comment by manniL** [comment]
@Atinux The problem is that @JkmAS isn't even providing the path. His `pm2.config.json` argument is leaking through as it seems.

**Comment by JkmAS** [comment]
Exactly. This is my package.json `"start": "pm2-runtime pm2.config.js"`. In this case the pm2 config file argument is in conflict with nuxt rootDir arg. http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/#starting-a-configuration-file

**Comment by Atinux** [comment]
@JkmAS Could you setup a simple repo with `pm2-runtime` and Nuxt so I can try multiple things?

**Comment by JkmAS** [comment]
@Atinux I think I tried it. Ok, I could.

**Comment by Atinux** [comment]
Hi @JkmAS 

Ok it seems to work with `exec_mode: "fork"` and `args: "."` but indeed, in `cluster` mode, `pm2.config.js` is given as first arg.

Actually, there is an option to overwrite the rootDir, see https://github.com/nuxt/nuxt.js/blob/dev/bin/common/utils.js#L39. It is to give the `--config-file` or `-c` option.

Take a look at my PR to fix your issue: https://github.com/JkmAS/nuxt-pm2-cluster/pull/1/files

**Comment by JkmAS** [comment]
@Atinux thanks a lot, your fix works.
