### ISSUE TITLE
Meta information missing in nested child page after nuxt generate

### ISSUE THREAD

**Issue by Jones-S** [nuxt/nuxt.js#3783]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://5b7c3352e39e7c4f599340c8--sudpol.netlify.com/](https://5b7c3352e39e7c4f599340c8--sudpol.netlify.com/)

### Steps to reproduce

Check <head> and see that the og:description (for example) is set correctly when you open the page.
But if you use the facebook debugger you won't see any of this.
Also if you open the source code of this link and reload that (to see what the inital code, after nuxt generation, is you can see that og:description is not populated.

Also I have to mention that we use nested nuxt routes.
So the page ,program, has a nested child page (https://nuxtjs.org/examples/nested-routes/)
the nested route contains an actual post. Within the post I use the the method `head ()` (https://nuxtjs.org/api/pages-head/) to generate the meta information.

Unfortunately when generating the pages this head () function does not seem to be executed leaving the meta info empty.

### What is expected ?

I would expect all child routes to execute their head () function when generating the static pages.

### What is actually happening?

If I set a head () meta on the page ,program' (parent) only this meta is written into the generated static page.
If I leave it out, there is no actual meta saved in the generated static html.

### Additional comments?

I hope my problem is understandable.
If I can elaborate more, please give me a hint, what information is needed.
Also if I misunderstood something, I would be very glad to get some help.

Cheers

J

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7612">#c7612</a>)</em></sub></div>

**Comment by Jones-S** [comment]
Update: It has to do with the fact that the data of the post is loaded asynchronously via ajax.
Unfortunately `head ()` does not wait for the data to be loaded and using promises does not help either.

We tried to use `asyncData` which populates `data` before it executes `head ()`. This works, but not if we use `nuxt generate`. Then the ajax call fails, because we can't access the filesystem where our .json files are situated.

I think we can't even execute an ajax call during `nuxt generate` becauase server middleware is not available during asyncData.

Is there a way to require the .json files during asyncData when using `nuxt generate`?

**Comment by galvez** [comment]
@Jones-S you can manually add a file to the build using `build.extend()` or `hooks['build:done']` in `nuxt.config.js`. You can import `fs`'s `readFileSync` and `writeFileSync` for this purpose.

**Comment by Jones-S** [comment]
Thank you!
