### ISSUE TITLE
User env vars to define proxy

### ISSUE THREAD

**Issue by stefandevo** [nuxt/nuxt.js#3784]
Is there a way in `nuxt.config.js` to set the desired proxy address based upon an environment variable?

`npm run dev` should set `proxy`:

'/json': 'http://localhost:5000/'

`npm run beta` should set `proxy`:

'/json': 'http://beta.application.com/'

**Comment by nicoladl** [comment]
Hi @stefandevo 
See this issue https://github.com/nuxt/nuxt.js/issues/2335

**Comment by stefandevo** [comment]
Hi, not exactly. I need the proxy plugin because my vue client is running on localhost :3000 but my server is running (not Express, but .NET CORE) on :5000. So with the proxy this works great because all /json calls are proxied to :5000. 
However, when I want to test the client locally against my beta server, I switch the /json proxy to something on the internet (https://mybeta.application.com). 
It would be great if I can set this by settings some env vars, but the Nuxt Proxy plugin does not resolve the environment variables.

**Comment by stefandevo** [comment]
Ok thanks; you pointed my in the right direction!
I added this on top of the `nuxt.config.js` file:

```
const proxyConfig = () => {
  if (process.env.DEPLOY_ENV === 'local') {
    return {
      '/json': 'http://localhost:5000/'
    }
  } else {
    return {
      '/json': 'https://beta.myapplication.com/'
    }
  }
}
```

and in the settings itself:

```
proxy: proxyConfig(),
```

Works! Thanks

**Comment by nicoladl** [comment]
Glad to help!

@stefandevo can you update the status of the issue as resolved?
