### ISSUE TITLE
Major issue with namespaced Vuex modules

### ISSUE THREAD

**Issue by UltramarineLights** [nuxt/nuxt.js#3790]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://vuex.vuejs.org/guide/modules.html](https://vuex.vuejs.org/guide/modules.html)

### Steps to reproduce

Setup a module mode index.js in the store folder with code 
WORKS
Copy the exact same code in a second-file.js in the store folder
Change all the helpers I'm using to reference the new namespace e.g. mapState(['stateName']) to mapState(['second-file/stateName'])
DOESN'T WORK

### What is expected ?

I'm expecting Nuxt to normally access the module

### What is actually happening?

Nuxt does not recognize any of the properties from the store module

### Additional comments?

I want to highlight that this happens with a clean Nuxt install through Vue CLI and with very simple code in order to exclude mistakes of different nature. The two store files are exactly identical apart from one becoming namespaced due to Nuxt default behavior. The same issue persist if I try to register the modules in the classic Vuex mode, since also in this case Nuxt creates namespaced modules. Is there a way to disable the automatic namespacing and instead merge all the modules properties into the main store?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7619">#c7619</a>)</em></sub></div>

**Comment by pbastowski** [comment]
Have you tried nuxt-edge? I am using namespaced modules without any issues with nuxt-edge.

**Comment by UltramarineLights** [comment]
How do I migrate to nuxt-edge?

**Comment by pbastowski** [comment]
For me it was as simple as:

Uninstall nuxt
Install nuxt-edge

**Comment by UltramarineLights** [comment]
same problem with nuxt-edge, are you using the helpers?

**Comment by UltramarineLights** [comment]
I just tried as last resort to use the vuex namespace helper and now it works:

import { createNamespacedHelpers } from 'vuex'
const { mapState, mapActions } = createNamespacedHelpers('moduleName')

and then just the 'stateName' in the code, while without the namespaced helpers and just 'moduleName/stateName' it doesn't. It's a very strange issue

**Comment by UltramarineLights** [comment]
I kind of find a solution, which still doesn't justify to me why the other method doesn't work.

...mapState(['navigation/pages']) NOT WORKING
...mapState('navigation', ['pages']) WORKING

maybe it's just me not getting the obvious, anyways I'm very happy now that I managed to get it working, I was getting crazy

**Comment by pbastowski** [comment]
@ultramarinelights 
I’m glad to read that you found a solution. 

I do use helpers and they were working when I last checked. Perhaps I was using the second syntax, where you supply the namespace as the first argument. I’ll check when I’m back from vacation.

**Comment by manniL** [comment]
Closed in favor of https://github.com/nuxt/docs/issues/850
