### ISSUE TITLE
Deployment not via `now`

### ISSUE THREAD

**Issue by FrancosLab** [nuxt/nuxt.js#38]
Now is awesome, but how would we go about deploying this on an alternative server?

Is simply running the `start` script enough?

**Comment by declandewet** [comment]
Hi @FrancosLab - to successfully deploy a Nuxt.js app on another server, the process is similar to any other Node.js app.

For example, you can `git push` to your remote server, where you might have a git `post-receive` hook that runs `npm install && npm build && npm start`

**Comment by Atinux** [comment]
In production, you package.json should be like this:
```js
{
  "scripts": {
    "build": "nuxt build",
    "start": "nuxt start"
  }
}
```

And then make sure to call `npm run build` before calling `npm start`.

What hosting/deployment platform are you working with @FrancosLab ? I might show you an example of how to do it (like Heroku for example)

The solution @declandewet describe is a good way to automate your deployment with your git repository 👍

**Comment by dan-gamble** [comment]
I'd love to see an example of how to deploy this to DO. Deployment is something i've always struggled super hard with (Why i'm using Github Pages :D)

**Comment by declandewet** [comment]
DO has a pretty exhaustive list of tutorials for deploying Node.js apps already: https://www.digitalocean.com/community/tags/node-js?type=tutorials

While none of these particularly describe Nuxt.js _specifically_, an app made with Nuxt.js is just a Node.js app running Express and can be deployed in the exact same way (you just have to make sure to run `npm run build` before you `npm start`).

**Comment by dan-gamble** [comment]
Yea maybe what i need is a toddlers version of that, but that isn't Nuxt's problem tbf. Thanks though :)

**Comment by airtonix** [comment]
@dan-gamble recommend you use doku image on digital ocean, once setup you can `git push` just like you do with github pages.

**Comment by dan-gamble** [comment]
Thanks man will check it out, is that tutorial still relevant given it's age?

**Comment by airtonix** [comment]
@dan-gamble from what I can see the guide is doing the same things though
setup as the current dokku recommends.

However the image on digital ocean might be old, do check that.

If it is, the you'd just spin upa recent Ubuntu image and perform the dokku
install as per: http://dokku.viewdocs.io/dokku/getting-started/installation/
