### ISSUE TITLE
Loader error when using vue-bulma-tooltip

### ISSUE THREAD

**Issue by jandauz** [nuxt/nuxt.js#380]
I get the following error when trying to use [vue-bulma-tooltip](https://github.com/vue-bulma/tooltip):

Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~bulma/sass/utilities/functions';
| @import '~bulma/sass/utilities/variables';

I have bulma configured in `nuxt.config.js` similar to the [Global CSS example](https://nuxtjs.org/examples/global-css/#__nuxt).

**Comment by alexchopin** [comment]
Have you install `node-sass` and `sass-loader`?

**Comment by jandauz** [comment]
Please refer to [this sample repo](https://github.com/jandauz/nuxt-vue-bulma-tooltip).

I extended the nuxt.config.js to add rules for processing .sass and .scss files. Compile no longer throws any errors, however, now I am getting following error when navigating to page.

![nuxt-vue-bulma-tooltip](https://cloud.githubusercontent.com/assets/1077395/23902637/37a81b12-0898-11e7-9240-2304a0a64016.PNG)
