### ISSUE TITLE
nuxt generate doesn't render every components

### ISSUE THREAD

**Issue by Agrajak** [nuxt/nuxt.js#3808]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/agrajak/nuxt_text_recruit](https://github.com/agrajak/nuxt_text_recruit)

### Steps to reproduce

nuxt generate.
my static website is hosted in https://agrajak-8d93e.firebaseapp.com/

### What is expected ?

In pages/index.vue, When I see my site with Chrome Developer Tools, Every <font-awesome-icon> should be rendered to <svg ~~~> 

![issue2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/00279da0-aa97-11e8-9b8b-61482bc9945c.png)

### What is actually happening?

some of <font-awesome-icon> are rendered to <svg ~>(in .sticky-nav, you can see it when you scroll down) 
and the others are still rendered to <font-awesome-icon> and also show nothing. (in top component)

![issue1.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/04eb4030-aa97-11e8-9b8b-61482bc9945c.png)

### Additional comments?

Site works pretty well in nuxt start.
I also checked turning off SSR options in nuxt.config.js

    {src: '~plugins/fullpage', ssr: false}
and font-awesome librarys are declared in plugins/fullpage.js

If this issue is not a bug, just let me know how to fix it.
thank you.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7640">#c7640</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Because the `fullpage` plugin is non-ssr, but nuxt generates html by ssr, so actually your plugins wasn't executed in generation, remove `ssr: false` should fix your problem.
