### ISSUE TITLE
SVG filters in Nuxt

### ISSUE THREAD

**Issue by UltramarineLights** [nuxt/nuxt.js#3809]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

https://github.com/UltramarineLights/svg-filter

### Steps to reproduce

SVG file with the filter code
Global CSS file with a class containing the filter property and link to the SVG file
Class applied to an image in <template> in a component

### What is expected ?

SVG filter to be applied to the image

### What is actually happening?

I get a blank filter property in the browser inspector and a -webkit-filter: url([object Object]#FILTERNAME)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7642">#c7642</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Could you provide a reproducible repo ?

**Comment by UltramarineLights** [comment]
Yes! https://github.com/UltramarineLights/svg-filter

**Comment by clarkdo** [comment]
Try:

1. move files under `static` to `assets`
2. change to '~/assets/main.css' `nuxt.config.js`
3. index.vue:

```vue
<template>
  <div>
    <BWFilter/>
    <img src="https://i.imgur.com/PzEm5j2.png" class="bw-filter">
  </div>
</template>

<script>
import BWFilter from '~/assets/bw-filter.svg';
 
export default {
  name: 'index',
  components: {
    BWFilter,
  },
};
</script>
```
