### ISSUE TITLE
Loading Component

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#381]
How to specify a different design, depending on which template is used?
In the documentation this moment is not described

It is necessary that each template has its own design of the component

**Comment by alexchopin** [comment]
You can disable the default Nuxt loading component and implement yours for each template used.

**Comment by wormen** [comment]
@alexchopin I have 2 templates, and for each I need to use my design
And the documentation describes only one common preloader

**Comment by alexchopin** [comment]
You mean 2 layouts?

**Comment by wormen** [comment]
@alexchopin yes

**Comment by alexchopin** [comment]
You can set the default Nuxt loader to false, and add your custom loader in each layout.

**Comment by wormen** [comment]
That's exactly what I want, but it's not clear how to get the data from `$loading` inside the layout

**Comment by krns** [comment]
Would also like to know how to use a custom loading component per layout.
