### ISSUE TITLE
Nuxt build script  could support to be <script nomodule> 

### ISSUE THREAD

**Issue by lennontu** [nuxt/nuxt.js#3810]
### What problem does this feature solve?

May support this. https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7644">#c7644</a>)</em></sub></div>

**Comment by manniL** [comment]
This would be a killer feature! :clap:

**Comment by manniL** [comment]
Related: #3848

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/pull/4231
