### ISSUE TITLE
Nuxt Workbox problem on reload

### ISSUE THREAD

**Issue by Jones-S** [nuxt/nuxt.js#3813]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/wearelucid/lie-detector-ui](https://github.com/wearelucid/lie-detector-ui)

### Steps to reproduce

Clone the repo.
Open it in the terminal and
Start the project:

```
// needs Node version manager
$ nvm use
$ yarn
$ yarn dev
```
Then go to http://localhost:3000 and open the page. Then reload.
In my case the terminal tells me:

```
  nuxt:render Rendering url / +18s
  nuxt:render Data fetching /: 1ms +4s
  nuxt:render Rendering url /sw.js +998ms
  nuxt:render Data fetching /sw.js: 1ms +989ms
  nuxt:render Rendering url /_nuxt/workbox.3de3418b.js +5ms
{ statusCode: 404,
  path: '/_nuxt/workbox.3de3418b.js',
  message: 'This page could not be found' }
```

There must be a problem with the workbox?... 

### What is expected ?

No error message

### What is actually happening?

The rendering of the workbox.js fails because of a 404

### Additional comments?

I found this post:
https://cmty.app/nuxt/modules/issues/c46

But adding: 

```modifyUrlPrefix: {
  '': '/_nuxt/'
}
```

in nuxt.config.js
did not solve it. Either did adding workbox to the package json.

If anyone has a clue why this fails, I would be very happy to get to know it.
Cheers and thanks in advance.

J

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7646">#c7646</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @Jones-S. Are you using `pwa-module`? The reproduction repo can't be accessed

**Comment by Jones-S** [comment]
Yeah I do, and sorry I still had it on private.

**Comment by manniL** [comment]
No problem. For further info and discussion, let's move it to the correct repo (https://github.com/nuxt-community/pwa-module/issues/88)
