### ISSUE TITLE
@ alias conflict bug

### ISSUE THREAD

**Issue by willin** [nuxt/nuxt.js#3817]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/willin](https://github.com/willin)

### Steps to reproduce

```js
{
  plugins: [
     '@npm-group/npm-package'  // not works
  ]
}
```

### What is expected ?

```js
{
  plugins: [
     '@npm-group/npm-package'  // works
  ]
}
```

### What is actually happening?

```js
{
  plugins: [
     '@/node_modules/@npm-group/npm-package'  //  works
  ]
}
```

### Additional comments?

i think this is a bug, 'coz many packages are scoped like `@angular/core`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7649">#c7649</a>)</em></sub></div>

**Comment by manniL** [comment]
`plugins` shouldn't be published directly as NPM modules. Instead, the developer could use a `module` where he adds the plugin programmatically and publish this instead. When using `modules`(eg. `modules: [ '@nuxtjs/redirect-module']`), the `@` alias won't be resolved.
