### ISSUE TITLE
Multiple error pages

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#382]
How to make each template have its own error page. Regardless of what there is default file for such pages

```
error.vue
Template_1 = error_page_1.vue
Template_2 = error_page_2.vue
```

In the documentation and examples you have nothing about this

**Comment by alexchopin** [comment]
Will be fixed in the next release.

**Comment by wormen** [comment]
@alexchopin When is the next release?

**Comment by alexchopin** [comment]
This week
