### ISSUE TITLE
Nuxt js Error: Couldn’t find a pages directory

### ISSUE THREAD

**Issue by bilalmd** [nuxt/nuxt.js#3820]
I changed nuxt js folder structure is here. I am getting Error: Couldn’t find a pages directory in D:\sample. Please create one under the project root how do I access pages
![folder-structure](https://user-images.githubusercontent.com/22346085/44843216-6cb0ca80-ac65-11e8-9c33-c6b5b526663d.PNG)
![error](https://user-images.githubusercontent.com/22346085/44843218-6cb0ca80-ac65-11e8-8855-98c578b83de2.JPG)

**Comment by galvez** [comment]
@bilalmd That is not possible. Nuxt works with a set of predefined conventions that aren't not modifiable, such as the name of the configuration file (`nuxt.config.js`) and standard directories (`pages` for routes, `store` for the Vuex store etc). Check out https://github.com/nuxt-community/router-module though -- I believe it might help you achieve this.
