### ISSUE TITLE
Images not loading in chrome

### ISSUE THREAD

**Issue by CristeaVlad19** [nuxt/nuxt.js#3822]
Hello, so I have an issue regarding some images not loading into chrome, they only appear with the classic image icon, not the image that i want to put there.
Here is the code that i wrote: 
<section id="boxes">
		<div class="container">
			<div class="box">
				<img src=".Coding/website/img/logo_html.png">
				<h3>HTML5 Markup</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mi augue, viverra sit amet ultricies</p>
			</div>
			<div class="box">
				<img src=".Coding/website/img/logo_css.png">
				<h3>CSS3 Styling</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mi augue, viverra sit amet ultricies</p>
			</div>
			<div class="box">
				<img src=".Coding/website/img/logo_brush.png">
				<h3>Graphic Design</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mi augue, viverra sit amet ultricies</p>
			</div>
		</div>
	</section>
I want to note that the file path is correct in fact i checked it 5 times. How do i fix this? This really stops me from wanting to code really.

**Comment by bilalmd** [comment]
configure n call base path from nuxt_config.js might be work out for u
