### ISSUE TITLE
The env Property cannot be set

### ISSUE THREAD

**Issue by willin** [nuxt/nuxt.js#3826]
### Version

Edge 2.0.0

### Reproduction link

[https://nuxtjs.org/api/configuration-env#the-env-property](https://nuxtjs.org/api/configuration-env#the-env-property)

### Steps to reproduce

nuxt.config.js: 

```js
  env: {
    NODE_ENV: process.env.NODE_ENV || 'development'
  }
```

### What is expected ?

can use `process.env`/`context.env`

### What is actually happening?

plugins/test.js console.log

process:

```js
{
  "title": "browser",
  "browser": true,
  "env": {},
  "argv": [],
  "version": "",
  "versions": {}
}
```

context undefined

### p.s.

i notice that: 

https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/client.js#L19

there is a `process.env.VUE_ENV` env property but not in console output...

----

plugin test passed:

```js
import SDK from '@airx/sdk';
// import { api } from '@/config';

console.log(process);
console.log(JSON.stringify(process, null, 2));

export default ({ app, env }, inject) => {
  // env can read out NODE_ENV property
  import(`@/config/_${env.NODE_ENV}`).then(({ api }) => {
    /* eslint-disable no-param-reassign */
    const sdk = new SDK(api);
    app.$sdk = sdk;
    window.app = app;
    inject('sdk', sdk);
  });
};
```

but i want to import from `@/config/index.js` :

```js
// eslint-disable-next-line import/no-dynamic-require
const options = require(`./_${process.env.NODE_ENV || 'development'}`);

module.exports = options;
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7663">#c7663</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce this (latest nuxt-js). As mentioned in the [docs](https://nuxtjs.org/api/configuration-env/#process-env-), `process.env.SOMETHING` will be replaced by webpack so it's not visible in the `process` object. However, I can access `process.env.NODE_ENV` from an imported JS as well.

`nuxt.config.js`
```js
export default {
  mode: 'universal',
  env: {
    NODE_ENV: process.env.NODE_ENV || 'development'
  },
  plugins: [ '~/plugins/example.js' ]
}
```

`plugins/example.js`
```js
export default ({ env }) => {
  console.log(env.NODE_ENV + " is the env. Loading file now")
  import(`@/shared/${env.NODE_ENV}.js`).then(c => c.default())
}
```

`shared/development.js`
```js
export default () => { console.log("HELLO FROM development.js", process.env.NODE_ENV) }
```


Output when opening a page:
```js
development is the env. Loading file now
HELLO FROM development.js development
```

**Comment by willin** [comment]
@manniL 

```js
plugin test passed:

import SDK from '@airx/sdk';
import { api } from '@/config';

export default ({ app }, inject) => {
    const sdk = new SDK(api);
    app.$sdk = sdk;
    inject('sdk', sdk);
};
```

`@/config/index.js` :

```js
// eslint-disable-next-line import/no-dynamic-require
const options = require(`./_${process.env.NODE_ENV || 'development'}`);
// HOW TO IMPLEMENT LIKE THIS?

module.exports = options;
```

**Comment by willin** [comment]
- -
