### ISSUE TITLE
NuxtServerError connect ECONNREFUSED port 443

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt.js#3835]
Hello, i have in last update some troubles with my project!

In my configs productions, port 80 

but in my nuxt config  i use

 env: {
    // use https on prod, http on local
    baseUrl: process.env.NODE_ENV == 'production' ? 'https:

after compile im have next error NuxtServerError  connect ECONNREFUSED host:443 

I have another project , and there fine works with this configuration, but why not work with new server??

**Comment by galvez** [comment]
@andysay HTTPS support should be available in Nuxt 2.0 :)

**Comment by galvez** [comment]
Currently there's nuxt-edge (dev version) available in NPM, but 2.0 should be made available this month.

**Comment by galvez** [comment]
@andysay your other project probably uses another app server with conjunction with Nuxt?

**Comment by andysay** [comment]
@galvez the whole configuration is the same, and there and there use ssl, one works, the other is not. I'm not understand why :P
