### ISSUE TITLE
<Nuxt-link> vs <a> : "Network Error with router" on Devices which is not localhost

### ISSUE THREAD

**Issue by lxx2013** [nuxt/nuxt.js#3843]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/nuxt/nuxt.js/releases/tag/v1.4.2](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.2)

### Steps to reproduce

This problem is main about Dynamic Routes . 
My src is :
![屏幕快照 2018-09-04 下午5.44.17.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2b3ad850-b027-11e8-b084-e5678efd3115.png)
The main code in index.vue is:
![屏幕快照 2018-09-04 下午5.45.53.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/5758f160-b027-11e8-b084-e5678efd3115.png)

Then I try to click these link on my localhost device (with `$npm run dev`) and both on another device(such as my iphone or ubuntu in vmware)

### What is expected ?

It is expected that all link-click will redirect to the right page.

### What is actually happening?

on localhost it success:
![Untitled.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/55d7da30-b028-11e8-b084-e5678efd3115.gif)

But on devices which is not localhost it failded:
![Untitled2.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/a60d9ad0-b028-11e8-b084-e5678efd3115.gif)

### Additional comments?

The most amazing thing is that when I change `<nuxt-link>` to `<a href=''>` , it success !  The code is like :
![屏幕快照 2018-09-04 下午5.57.22.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/fab00460-b028-11e8-b084-e5678efd3115.png)

while it get successed to redirect on ubuntu:
![Untitled4.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/407f1c60-b029-11e8-b084-e5678efd3115.gif)

The only different code is just `<nuxt-link>` and `<a>`(by the way, I tried `<router-link>`and it also failed) , And after searching in google I found that there are many people confused by the `Network Error` , So please at least give more detail infos about `Network Error`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7681">#c7681</a>)</em></sub></div>

**Comment by Atinux** [comment]
@lxx2013 how do you fetch the restaurant data? Could you show us your `asyncData`, I am quite sure that the request does not work to fetch the restaurant data on server side.

**Comment by aldarund** [comment]
in case of failed request urls in address for some reason /selle... not a /restaurant

**Comment by lxx2013** [comment]
I think I almost know where the problem is. All my `asyncData` in each `.vue` is :
```js
async asyncData({ params }) {
    let { data } = await axios.get(`http://localhost:8101/api/seller/${params.restaurant}`);
    return { seller: data ,restaurant:params.restaurant};
  }
```
Sometimes this `axios.get` fetch data from server rendor, and sometimes it runs on client browser(which get network error). Next step I should find out when `asyncData` runs the server-side-rendor.

Thanks you for your replys!

**Comment by lxx2013** [comment]
If someone  have the same problem as mine, I suggest you to write like this in `asyncData` to **debug** and avoid `Network Error`:
```js
 async asyncData({ params}) {
      try {
        console.log(
          `[file_name.vue] asyncData: isClient : ${process.client}, isServer: ${
            process.server
          }`
        );
        let url = process.client
          ? 'http://your_real_server_ip:8101/api/seller/'
          : 'http://localhost:8101/api/seller/'
        console.log(`[file_name.vue ] axios.get(url): ${url}`)
        let { data } = await axios.get(url);
        return { seller: data};
      } catch (err) {
        console.log("[file_name.vue]", err);
      }
    }
```
And then just check that if the logs are printed  
- after **Terminal** of`nuxt start` ,
  or
- in **Chrome debug Console**
