### ISSUE TITLE
Missing merge strategy for head hook method

### ISSUE THREAD

**Issue by adrienbaron** [nuxt/nuxt.js#3846]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/adrienbaron/vuetify-bug-theme-nuxt-i18n](https://github.com/adrienbaron/vuetify-bug-theme-nuxt-i18n)

### Steps to reproduce

- Create a Nuxt + Vuetify project
- Update to Nuxt (1.4.2) and Vuetify 1.2.2
- Add nuxt-i18n (5.2.1) to the project
- Run the sample app

### What is expected ?

- Vuetify theme and Nuxt i18n meta should be added

### What is actually happening?

- Only Nuxt i18n meta is added

### Additional comments?

This is also broken in Nuxt Edge.

I initially thought it was a bug in Vuetify 1.2.x and opened an issue there: https://github.com/vuetifyjs/vuetify/issues/5032.
It turns out that Nuxt is missing a merge strategy for the `head` hook.

Nuxt should probably declare this merge strategy to avoid those kind of conflicts:
```
Vue.config.optionMergeStrategies.head = Vue.config.optionMergeStrategies.data
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7684">#c7684</a>)</em></sub></div>

**Comment by manniL** [comment]
@adrienbaron Could you add a PR for that? :relaxed:

**Comment by adrienbaron** [comment]
Ok, so after trying to get this to work, I noticed that my fix actually breaks some behavior of Vue Meta (thank you unit tests ^^).
I wonder if this fix should not be in Vue Meta, but I just learned about it today so I'm not sure.
From reading their doc, it seems to already deal with merging info, between parent and child components. Maybe they just don't support merging info from mixins?

**Comment by Atinux** [comment]
I think vue-meta does not support merging from mixins indeed, I am open for any help on improving vue-meta @adrienbaron

**Comment by manniL** [comment]
Will be resolved with https://github.com/declandewet/vue-meta/pull/262
