### ISSUE TITLE
Use BabiliPlugin() instead of UglifyJs()

### ISSUE THREAD

**Issue by liyanlong** [nuxt/nuxt.js#385]
**version**
- nuxt 0.9.9
- element-ui 1.2.3

**Error Reason**
```shell
ERROR in 0.console.js from UglifyJs
Unexpected token name «i», expected punc «;» [0.console.js:2128,11]
```
So I look up the source file `0.console.js`, I found the source file is `element-ui/src/utils/merge.js` 
```javascript
export default function(target) {
  for (let i = 1, j = arguments.length; i < j; i++) {
    let source = arguments[i] || {};
    for (let prop in source) {
      if (source.hasOwnProperty(prop)) {
        let value = source[prop];
        if (value !== undefined) {
          target[prop] = value;
        }
      }
    }
  }

  return target;
};
```
I found the `let` keyword.  But `webpack.optimize.UglifyJsPlugin`  unsupport ES6 grammar default.

**My solution**
change UglifyJsPlugin plugin
```javascript
const BabiliPlugin = require('babili-webpack-plugin')
module.exports = {
  build: {
    extend (config, {dev}) {
      if(!dev) {
        config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJsPlugin')
        config.plugins.push(new BabiliPlugin())
      }
    }
  }
}
```
@Atinux Do you have any better ideas? 

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c335">#c335</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @liyanlong 

I will take a look at it, indeed, it's not the first time that UglifyJS create problems.
Even if I think that element-ui should be transpiled to ES2015, I don't want nuxt.js to have errors because of this.

**Comment by liyanlong** [comment]
Thanks @Atinux 

In `development`,  we can ignore  `BabiliPlugin()`

**Comment by apertureless** [comment]
Well isn't this rather related to element-ui and a missing transpiled build?
It's actually kind of weird, because in their package.json they specify 

` "main": "lib/element-ui.common.js",`

as the entry. So it seems they have an transpiled version? But your error points to the `src/` folder. 🤔 

But this would also mean, that element-ui would be unuseable in most `vue cli` scaffolded projects, as the default webpack production config uses uglifyjs.

**Comment by liyanlong** [comment]
@apertureless  

you are right, it has beean compiled in the `element-ui@1.2.5`.

**Comment by lmj0011** [comment]
@liyanlong

Thanks for this solution.

**Comment by derekshull** [comment]
@liyanlong thanks for the solution!  It worked great for my build process in CircleCI.

**Comment by matthew-dean** [comment]
If anyone else comes across this issue, "nuxt build" will fail for many components with an `Unexpected token: name` error. The code above fixed it.

**Comment by liyanlong** [comment]
@matthew-dean  thanks for your advice.

**Comment by christophwolff** [comment]
+1

**Comment by camilodelvasto** [comment]
I ended up using this:
```
    extend (config, ctx) {     
      if (!ctx.dev) {
        const UglifyJSWebpackPlugin = require('uglifyjs-webpack-plugin')
        config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJsPlugin')
        config.plugins.push(new UglifyJSWebpackPlugin())
      }
```
as I was having issues with BabiliPlugin.

**Comment by KyleTryon** [comment]
Would this be a solution for this problem? Could someone explain in more detail?
https://github.com/nuxt/nuxt.js/issues/2468

**Comment by husayt** [comment]
This could be really useful. Last version of uglifyjs 3.3.13 broke a lot of projects, it is less and less reliable. Alternative could be very useful.

**Comment by galvez** [comment]
@Atinux @clarkdo closable?

**Comment by qm3ster** [comment]
How about the so called [**fabiosantoscode/`terser`**](https://github.com/fabiosantoscode/terser) ?
It's a fork of uglify-es that is specifically only interested in ES6+ minification.
Babili is still weaker compression + slower processing than uglify.

**Comment by Atinux** [comment]
Could you open a feature request on CMTY about terser? I am interested to see what the community think of it too

**Comment by clarkdo** [comment]
Currently, `uglifyjs-webpack-plugin` is the default plugin od webpack [`optimization.minimizer`](https://webpack.js.org/configuration/optimization/#optimization-minimizer).

And it supports [`terser`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/README.md#terser) as well, so you can use `build.optimization.minimizer` in `nuxt.config.js` to config `terser`.
