### ISSUE TITLE
[Nuxt-edge] Multi-theme setup

### ISSUE THREAD

**Issue by Legym** [nuxt/nuxt.js#3852]
Our team is using Nuxt for a client and we separate mobile and desktop by using themes. All themes shares the store, mixins, and functions so it makes sense for our business to not duplicate code.

Themes layout:
![screen shot 2018-09-05 at 5 36 06 pm](https://user-images.githubusercontent.com/4462368/45122570-31653e80-b132-11e8-90b9-680ace9d33a9.png)

If I navigate to `http://localhost:3000/m/` (Mobile theme) it ends up loading styles from `http://localhost:3000/d/`(Desktop)

Desktop:
```
<template>
<script>

<style lang="scss">
@import '../assets/d/project.scss'
</style>
```

Mobile:
```
<template>
<script>

<style lang="scss">
@import '../assets/d/project.scss'
</style>
```

My problem is I want a global style (a custom Zurb Foundation) that applies to just that specific Layout component. I do have a work around for the time being by applying CSS via the header

```
export default {
  name: 'Layout',
  head() {
    return {
      link: [
        { rel: 'stylesheet', href: '/d/css/project.css' }
      ],
    }
  }
}
```

However I am unsure how to extend the webpack build to build my scss to css without overriding the defaults. Is there a better work around for this? 

Very similar to this issue.
https://github.com/nuxt/nuxt.js/issues/1801

Thanks!

**Comment by DJafari** [comment]
you current solution is right, but you must does a trick

first you layout styles must be scoped, second you must /deep/ selector to styles of layout

example :

```
<template>
  <div class="mobile-layout">
    <nuxt />
  </div>
</template>

<style lang="scss" scoped>
@import '../assets/d/mobile.scss'
</style>
```

mobile.scss

```css
.mobile-layout {
  /deep/ .input {
  }
  /deep/ .control {
  }
  .
  .
}
```
