### ISSUE TITLE
nuxt web server return truncted vendor js in prod env

### ISSUE THREAD

**Issue by hijason1301** [nuxt/nuxt.js#3859]
### Version

[v1.0.0](https://github.com/nuxt.js/releases/tag/v1.0.0)

### Reproduction link

[http://nr.qqkt.com/login](http://nr.qqkt.com/login)

### Steps to reproduce

it's unstable. Sometimes it works but sometimes not. When it dosen't work , it reports error ": webpackJsonp is not defined". And we checked. 

![manifest.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/3dbfe840-b28d-11e8-8d6c-f9442843bee4.png)

manifest js file or vendor js file is broken. The server return a error  file.  Finally it will get these common js file again after the app.js filei . So  it reports error  "webpackJsonp is not defined".  

it's nothing about proxy. It seems a bug of  nuxt

### What is expected ?

get js file stablely

### What is actually happening?

return truncated file. 

### Additional comments?

it's a serious bug. It's very unstable in prod env

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7702">#c7702</a>)</em></sub></div>

**Comment by hijason1301** [comment]
it has same bug in ver 1.4.1

**Comment by hijason1301** [comment]
![nuxt error](https://user-images.githubusercontent.com/40160936/45222289-b8f3ae80-b2e6-11e8-975b-82c7300af5f6.png)
the content-length is 407 . it's wrong

**Comment by manniL** [comment]
Should be a "repository-related" issue, not a global one. See https://github.com/webpack/webpack/issues/368
