### ISSUE TITLE
Flash of content (foc) when not in dev mode

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#386]
I'm running nuxt using nuxt.renderer behind express with nuxt_config.dev = false. I can confirm that the webpack middleware and no HMR is running. However, I still see that extract css is not getting everything and some style tags are being generated in the head after the js bundles. 

Can someone please help debug or is this the expected behavior? If I wanted to ensure no head styles are generated what can I do?

**Comment by uptownhr** [comment]
Learned a bit more and more info. 

I forgot to mention that I am using sass and I also had ?sourcemaps declared

```
<style lang="sass?sourceMaps">
...
</style>
```

1. Moving styles off of the component and to my main fixed the issue. However, this is not ideal and loose alot of value of what vue-loader provides.
2. I removed ?sourceMaps and that also fixed the problem. Not sure how the ?sourceMaps flag works but removing this made sure that the extractText plugin puts the css in the file and not dynamicly loaded to the head.

**Comment by Atinux** [comment]
Hi @uptownhr 

It's not recommended to use `?sourceMaps` in your `vue` files, you need to use webpack configuration to allow source maps.

In the upcoming release, I won't use extractTextPlugin since Vue 2.2 will inject the required CSS directly in the `<head>`

**Comment by uptownhr** [comment]
@Atinux just to be clear, this will also be done from SSR and not cause FOC.

**Comment by Atinux** [comment]
Exactly @uptownhr
