### ISSUE TITLE
Router middleware does not fire with first render

### ISSUE THREAD

**Issue by zeknoss** [nuxt/nuxt.js#3864]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://codepen.io/](https://codepen.io/)

### Steps to reproduce

* Create a middleware (e.g. middleware/auth-sitemap.js)
* Assign the middleware to route
**middleware/auth-sitemap.js**
```
export default ({ store }) => {
    if (process.server) return

    if (!store.state.user.login) {
        console.log('no login!');
    }
}
```

**nuxt.config.js**
```
module.exports = {
    router: {
        middleware: ['auth-sitemap']
    }
}
```
* Run dev script
* Visit http://localhost:3000

### What is expected ?

When the application is visited for first time by clicking an external link or writing down the url manually, the router middleware should work.

### What is actually happening?

Router middleware works only when the route is changed by a nuxt-link or router-link component. Visiting an url directly does not trigger the middleware.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7708">#c7708</a>)</em></sub></div>

**Comment by aldarund** [comment]
It executes on server first time. Only on server. Middleware execute either on client or server, not on both.
