### ISSUE TITLE
Declaring language in HTML tag

### ISSUE THREAD

**Issue by wushan** [nuxt/nuxt.js#388]
Since we can set some meta tags in the head in nuxtConfig file, how do we declare html lang attribute in HTML tag like this ?

`<html lang="fr" xml:lang="fr" xmlns="http://www.w3.org/1999/xhtml">`

**Comment by ausir0726** [comment]
you can edit in nuxt.config.js

```
module.exports = {
  /**
   * 如果放置的空間在資料夾內請修改 base
   */
  router: {
    base: '/',
  },
  /*
  ** Headers of the page
  */
  head: {
    htmlAttrs: {
      lang: 'zh-Hant',
    },
    title: 'prject',
    meta: [
      { 'http-equiv': 'X-UA-Compatible', content: 'IE=edge' },
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'keyword', name: 'keyword', content: 'yoyo' },
      { hid: 'description', name: 'description', content: 'FINPO project' },
    ]
   .....
```

you can find more setting on vue-meta
https://github.com/declandewet/vue-meta

**Comment by wushan** [comment]
@ausir0726 It works like charm. I really should read vue-meta's document first. Thanks !

**Comment by ErickPetru** [comment]
I came here because of the same "problem". I believe the documentation should include it, maybe here: https://nuxtjs.org/guide/views/#document.

**Comment by hoektoe** [comment]
Would also like to know if can declare via $store.state

**Comment by mattbag** [comment]
head(){} method in the pages can be used with $store.state I believe

**Comment by nicoladl** [comment]
@mattbag you are right

but if you are in 'spa' mode metatag placed in pages are not been see from search engine
