### ISSUE TITLE
typescript for serverMiddleware?

### ISSUE THREAD

**Issue by sweetim** [nuxt/nuxt.js#3890]
How to use typescript for `serverMiddleware`?

I have configured the build to handle `typescript` and it works perfectly for `page` and `component` but not `serverMiddleware`? 

how to resolve this problem?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7742">#c7742</a>)</em></sub></div>

**Comment by JuniperChicago** [comment]
I found setting `"module": "es2015"` in `tsconfig.json` worked. It only compiles once, so in `dev` mode it will not watch for changes and hot-reload, but otherwise is fine.
