### ISSUE TITLE
[edge] Uncaught ReferenceError: require is not defined when using @nuxtjs/apollo 

### ISSUE THREAD

**Issue by Vlaoff** [nuxt/nuxt.js#3892]
### Version

nuxt-edge

### Reproduction link

[https://github.com/Vlaoff/apollonuxt](https://github.com/Vlaoff/apollonuxt)

### Steps to reproduce

I get the error when I launch nuxt and open it in the browser

### What is expected ?

I should not have this error

### What is actually happening?

I think it's a problem with the babel/wepack configuration.

### Additional comments?

It does not occur on nuxt 1.4.2, only on the nuxt-edge 2.0.0-xxx (could not select the correct version on cmty.app)

I don't know if the problem is from @nuxtjs/apollo  or nuxt. But as it does not occur on the nuxt stable branch, I submit it here 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7745">#c7745</a>)</em></sub></div>

**Comment by aldarund** [comment]
@Vlaoff it seems that something off with graphql 0.13.2 . Nuxt edge have mjs support enabled, and it dont play with with graphql 0.13.2. So its dont seem like a nuxt problem.
You could try to set grapqhl to 14.0.2 and it will make the error go away, although there will be complains about not meet requirements and not sure if it wont break anything.
