### ISSUE TITLE
Error in IE 11 using namespaced modules in store

### ISSUE THREAD

**Issue by sindael** [nuxt/nuxt.js#3898]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/sindael/nuxt-IE11-error](https://github.com/sindael/nuxt-IE11-error)

### Steps to reproduce

1. Install dependencies and open http://localhost:3000/cs in IE 11
2. npm run dev
3. The errors should pop-up in the console
4. Remove modules folder from store
5. Stop the dev build and run it again. Open a new window in the browser to assure nothing is cached
6. The errors should not appear this time

### What is expected ?

Page should load without errors as in other browsers.

### What is actually happening?

Page does not load.

### Additional comments?

Additional notes with images of the errors in the attached github link.

I am not 100 % sure this is the minimal structure that still leads to the errors, because they are somewhat elusive. It appeared most of the times with some configuration and later, with identical, it did not. With this structure the error appears every time in IE 11.

When I include `modules` folder in store, it leads to `Syntax error` and `Unable to get property 'call' of undefined or null reference`. When I delete the modules, it works. The weirdest part is that I don't even load the modules in `store/index.js` which confuses me whether this is a Nuxt bug or webpack/babel bug. However I haven't encountered this issue in plain Vue applications.

I use `babel-polyfill` and `event-source-polyfill`, but that didn't help.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7752">#c7752</a>)</em></sub></div>

**Comment by aldarund** [comment]
It is problem with the dependency that u using.
https://github.com/directus/directus-sdk-javascript/issues/32
