### ISSUE TITLE
ServerAction Middleware

### ISSUE THREAD

**Issue by uglow** [nuxt/nuxt.js#3902]
### What problem does this feature solve?

It solves the limitation of `fetch()` only being available on `page` components. My solution is to add a middleware that walks the component tree of a page, looking for components with a `serverActions(context)` method. This means that I don't need to move server-action code explicitly into the `page.fetch()` method, but it can remain with the child-components that wish to make these calls.

### What does the proposed changes look like?

See https://gitlab.mantelgroup.com.au/snippets/1

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7755">#c7755</a>)</em></sub></div>

**Comment by manniL** [comment]
Definitely an interesting approach! :clap:

**Comment by manniL** [comment]
We will have asyncData/fetch everywhere soon ;)
