### ISSUE TITLE
Allow nuxt build command to choice config file

### ISSUE THREAD

**Issue by PierreRambaud** [nuxt/nuxt.js#391]
Hi,

The `nuxt.config.js` file path is written in the code of the `nuxt build` command. But the problem is that this file is not always located at root directory, and it can be cool to allow developers to choice the path of this configuration file.

For example: 
```
.
+-- config
|   +-- general.config.js
|   +-- nuxt.config.js
|   +-- api.config.js
|   +-- styles.config.js
+-- pages
|   +-- index.vue
+-- layouts
|   +-- default.vue
|   +-- post.vue
+-- store
|   +-- index.js
...
```

I want to use
```bash
$ nuxt build -c /path/to/project/config/nuxt.config.js /path/to/project
$ # or 
$ nuxt build --config-file /path/to/project/config/nuxt.config.js /path/to/project
```

Can be useful to automatize deployments :D

**Comment by Atinux** [comment]
Hi @PierreRambaud 

I'd love to see a PR for that 👍

**Comment by PierreRambaud** [comment]
@Atinux Dunno if adding and equivalent of argparse can be a good idea but I can have a look to add this for the future of this project. (NuxtJs and VuejS make me like Javascript o/)

**Comment by Atinux** [comment]
You don't need argparse, take a look at this: https://github.com/nuxt/nuxt.js/blob/master/bin/nuxt-build#L11

**Comment by PierreRambaud** [comment]
Yes, that's what I did for the PR :)

**Comment by PierreRambaud** [comment]
Thanks for merge @Atinux  ;)

**Comment by PierreRambaud** [comment]
This issue maybe should be closed and add to Milestone `0.10` ?

**Comment by Atinux** [comment]
I will close it when the `0.10` will be out @PierreRambaud

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋
