### ISSUE TITLE
Nuxt SSR crashes with 200 response code

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#3914]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/uptownhr/nuxt-issue-3914](https://github.com/uptownhr/nuxt-issue-3914)

### Steps to reproduce

1. clone repo
2. yarn
3. yarn build
4. yarn start
5. ab -c 2 -n 20000

The STR is not straight forward as I'm only able to reproduce this on a live project I have and running `ab -c 2 -n 20000`. It's only once the server has been hit around 10k times where the bug `Maximum Stack` on `VueComponent.mergeDataFn` is triggered. 

Once this error is triggered, I can see on the log `statusCode: 500`, however the web server still responds with 200 and shows an error page.

```
{ RangeError: Maximum call stack size exceeded
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1164:34)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51)
www_1       |     at VueComponent.mergedDataFn (/www/node_modules/vue/dist/vue.runtime.common.js:1166:51) statusCode: 500, name: 'RangeError' }
```

### What is expected ?

When the SSR rendering crashes, the web response should also be a 500. 

Second thing that should probably is happen is also kill the server, so the process manager has a chance to reboot the server.

### What is actually happening?

The server errors and still returns a 200. This causes error monitors not be able to alert. Also because it catches the crash and not actually crash, any process managers listening to restart the server cannot. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7771">#c7771</a>)</em></sub></div>

**Comment by uptownhr** [comment]
sorry, i am still working on a reproducible link.

**Comment by uptownhr** [comment]
added https://github.com/uptownhr/nuxt-issue-3914

**Comment by pimlie** [comment]
Unfortunately I cant get your repro to work. Its too slow and due to your issue or another its just hogging resources until pages take multiple seconds to render.

But what is the idea behind applying a Vue.mixin like you do in your repro? You are not injecting anything in $root or in the context, so why do you export a method? Is it just for the repro or is this taken from the real world?
Because you export an method that means that on every reload the mixins are again loaded with the Vue instance in the SSR context. That should really only be necessary once at server start up.

If you remove the function export like this it should work fine:
```js
import Vue from 'vue'

console.log('mixins')

  console.log(1)
  const mixins = {
    computed: {
      cleavePhoneFormat () {
        return {
          delimiters: ['+1',' ','(',')',' ', '-'],
          blocks: [0, 0, 0, 3, 0, 3, 4]
        }
      },
      availableSalesTimeSlots() {
        return this.$store.state.availableSalesTimeSlots
      }
    }
  }


  for (let x = 0; x < 100; x++) {
    Vue.mixin(mixins)
  }
```

Also unfortunately I cant reproduce that the server returns a 200 status. If I try the following component which also triggers a RangeError during SSR, both nuxt as nuxt-edge return an error page with the RangeError and status 500.
```js
<template>
  <h1>Trigger RangeError: Maximum call stack size exceeded</h1>
  If you see this message the RangeError was not triggered
</template>

<script>
export default {
  async asyncData() {
    const fn = () => {
      setTimeout(fn(), 1)
    }
    fn()
  }
}
</script>
```
Nuxt returns a 500 status if an error was captured somewhere within the Nuxt code or through Vue's global errorHandler. If in your case nuxt returns a 200 status then that probably means you triggered an upstream issue which both Nuxt as Vue cannot capture. Maybe a memory leak in v8? But its actually strange anything is returned at all in that case.

As this bug report is only about the fact that Nuxt returns a 200 status on a RangeError, I cant reproduce that with your repro and my own test seem to work. So if you could try to update your repro we can have another look.

**Comment by manniL** [comment]
Couldn't reproduce it with your repo and 60k request either :(

I've tried it with a simple `const f = fn => fn(fn); f(f)`

```js
 nuxt:render Rendering url / +0ms
{ RangeError: Maximum call stack size exceeded
    at f (server-bundle.js:3437:11)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17)
    at f (server-bundle.js:3437:17) statusCode: 500, name: 'RangeError' }
```

**Comment by uptownhr** [comment]
When you start receiving the status code 500, hit the next app with your
browser. It will return a 200 even though the error in logs shows 500.

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/46903719-b9c4c500-ced0-11e8-9edb-fa3042e4df00.png)
