### ISSUE TITLE
Show error page/clear hint if pages dir is missing

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#3920]
### What problem does this feature solve?

Currently a "default page" is shown when the `pages` directory is missing. This is bad for DX and might lead to confusion. Instead we should either shown an error page or at least a large hint that the directory is missing.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7782">#c7782</a>)</em></sub></div>

**Comment by pimlie** [comment]
+1
Something like `Nuxt was successfully installed, start creating your project by adding pages to ${srcDir || process.env.PWD}/pages/`would probably be nice. Then its also immediately clear where they should create the pages/ folder.

**Comment by felubra** [comment]
Where should we output this hint? In the console during the build process or inside the default page?

**Comment by manniL** [comment]
@felubra I think both sounds suitable :relaxed: 

The default page (if we want one) should be clearly expressing that it's "just a default page"

**Comment by felubra** [comment]
@manniL, thanks for the feedback. I will try to help with this one 😊

**Comment by manniL** [comment]
Awesome :clap:
