### ISSUE TITLE
Add support for nesting nuxt apps

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#3921]
### What problem does this feature solve?

This feature should make it possible to use an external nuxt app within another nuxt app.

The ultimate goal, but that would require more changes than just this one, would be to be able to use Nuxt in an extendible (legacy) app that supports add-ons without the need for regenerating/building nuxt. To explain by example, take a look at https://github.com/nextcloud/server. Quite some nextcloud apps use Vue for rendering the app, see eg accessibiility and oauth2. Currently those apps implement their own Vue/VueRouter instance (and build environment etc), so that means navigating between apps requires a full page reload.

Although this would require some preconditions as same app template and vue-meta config, it would be nice if we could leverage the power of Nuxt's build environment for those add-ons. Thus eg nextcloud/server implements a single Nuxt/Vue/VueRouter instance and the nextcloud apps can extend that instance in a way that for the end-user installing an add-on is still as simple as copying some data and indicating that add-on should be enabled.

### What does the proposed changes look like?

Something like this:

```
/nested-app/
/nested-app/nuxt.config.js
/nested-app/package.json
/nested-app/pages/index.vue
...
/main-app/
/main-app/nuxt.config.js
/main-app/package.json
/main-app/pages/index.vue
...
```

with `/main-app/nuxt.config.js` containing (at the very basic):
```js
import nestedApp from 'nested-app-package'

...
    extendRoutes(routes, resolve) {
      routes.push(
        nestedApp.createNestedApp()
      )
    }
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7784">#c7784</a>)</em></sub></div>

**Comment by manniL** [comment]
Looks a bit like https://github.com/nuxt/nuxt.js/issues/1795

**Comment by pimlie** [comment]
Yes, with the exception that that issue seems more about just the pre-building phase and this is (at least with regards to the ultimate goal) about post-building.
