### ISSUE TITLE
Nuxt Edge : adding/handling babel polyfill?

### ISSUE THREAD

**Issue by valeriosillari** [nuxt/nuxt.js#3924]
I am starting using Nuxt Edge and trying to update a project based on Nuxt 1.4.2.

On Nuxt v1 I've added the babel polyfill for a IE11 compatibility following documentation and info n the forum, and it works.
I've used to install the npm package, and the nuxt config file I added the babel polyfill as vendor.

Now on Nuxt Edge the vendors are gone.
When I run Nuxt, the CLI give me a warning about vendor: "vendor has been deprecated due to webpack4 optimization"

So my question is: how can add on Nuxt Edge Babel Polyfill?

Anyone could give me some tips?
I see articles where people talking about the removal of vendors, but I didn't find anything explaining how to handle the old dependencies using vendor …

thanks :)

**Comment by voronianski** [comment]
I have the same question. My Nuxt@2 website is not working in IE11.

**Comment by hareku** [comment]
Me too.
My nuxt2.2 project is not working in safari 9~10.

How do i fix?

**Comment by tarreislam** [comment]
> I have the same question. My Nuxt@2 website is not working in IE11.

This should fix that

```
head {
 ...
 meta: [
    {'http-equiv': 'X-UA-Compatible', content: 'IE=edge'}
  ]
}
```
