### ISSUE TITLE
Webpack can not use the correct loader's version, if occurs that the loaders have conflict version.

### ISSUE THREAD

**Issue by QS20199** [nuxt/nuxt.js#3929]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/QS20199/nuxt-bug-report-2018-9-21](https://github.com/QS20199/nuxt-bug-report-2018-9-21)

### Steps to reproduce

1.`npm install`
2.`npm run dev`, and it will fail.

### What is expected ?

It can run successfully

### What is actually happening?

It failed to run.

![TIM截图20180921103430.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/e95ac300-bd46-11e8-9cf4-3d288f7438d0.jpg)

### Additional comments?

The repo is building by following steps, and you can see the change log in the repo:

1. run `vue init nuxt-community/starter-template nuxt-bug-report-2018-9-21`
2. run `npm install`
3. run `npm run dev`, and it can run successfully
4. run `npm install --save vue-loader@15`
5. run `npm run dev`, and it will fail.

It will fail because wepack in nuxt is using the uncorrect version.

Webpack in nuxt@1.4.2 is using vue-loader@13, and if I install vue-loader@15 in my repo, webpack will use vue-loader@15 instead of vue-loader@13, and it caused fail in running `npm run dev`.

I found that if adding `context: __dirname` into `.\node_modules\nuxt\lib\builder\webpack\base.config.js`, it can choose the correct vue-loader version, and can run `npm run dev` successfully.

Before:

![20180921104353.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/33bed700-bd48-11e8-9cf4-3d288f7438d0.png)

After:

![TIM截图20180921104447.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/595619b0-bd48-11e8-9cf4-3d288f7438d0.jpg)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7789">#c7789</a>)</em></sub></div>

**Comment by pi0** [comment]
@QS20199 Vue-loader 15 will be only supported with Nuxt >= 2.0 

For now, you can use `nuxt-edge` package.
