### ISSUE TITLE
Nuxt on IISNode

### ISSUE THREAD

**Issue by DevanB** [nuxt/nuxt.js#393]
This is going to be a long shot, I know. However, I am trying to run a Nuxt application on [IISNode](https://github.com/tjanczuk/iisnode). The way IISNode works, from my limited time researching and implementing it, is I need to tell IISNode the entry point Node file to start from. For instance:

```
<configuration>
    <system.webServer>
        <handlers><add name="iisnode" path="hello.js" verb="*" modules="iisnode" /></handlers>
    </system.webServer>
</configuration>
```

This tells IISNode to start at the `hello.js` file. If my `hello.js` file had the following in it:
```
var http = require('http');
http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello, world! [helloworld sample;  node version is ' + process.version + ']');
}).listen(process.env.PORT);  
```
I would see the "Hello, world! [helloworld sample; node version is 6.1.0]" in the browser when I navigate to the site.

I'm trying to understand how to translate running `nuxt build` and `nuxt start` over to this method of running Node apps on IIS. I know running `nuxt start` starts a server listening on 3000. I'm trying to understand if I should be able to set the `<add name="iisnode" path="hello.js" verb="*" modules="iisnode" />` path to a root js file that is ran.

Any discussion, comments, or solution is more than welcome! This could be beneficial for those individuals who are restricted to a windows environment who want to build with nuxt.js! :)

Thanks!

**Comment by alexchopin** [comment]
Hi,
I think you should try with the [nuxt express template](https://github.com/nuxt/express).
You can see how works nuxt with the [server.js file](https://github.com/nuxt/express/blob/master/template/server.js).

**Comment by DevanB** [comment]
@alexchopin I had not seen this yet. Thanks for pointing it out; it should work perfectly!
