### ISSUE TITLE
Webpack is not resolving ~/assets/ for css url

### ISSUE THREAD

**Issue by laSinteZ** [nuxt/nuxt.js#3931]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/laSinteZ/nuxt-assets-url-bug](https://github.com/laSinteZ/nuxt-assets-url-bug)

### Steps to reproduce

`yarn`
`yarn dev` or `yarn generate`

### What is expected ?

You must see red boxes with `~/assets/` and no boxes with `~assets/`

### What is actually happening?

`~/assets/` is not resolved by a webpack for css url(), but `~assets/` is resolved. for img src both options work.

### Additional comments?

https://nuxtjs.org/guide/assets/ states that we should use `~/assets/` to resolve svg modules. However, for <img src.. > both `~/assets/...` and `~assets/...` work, while for css's url() only `~assets/...` works. Additional url with compiled files: https://dist-lxayhipvve.now.sh

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7790">#c7790</a>)</em></sub></div>

**Comment by P4sca1** [comment]
From https://github.com/nuxt/nuxt.js/releases:

> Due to css-loader upgradation, use `~assets` instead of `~/assets` for alias in CSS data type, e.g., `background: url("~assets/banner.svg")`

**Comment by laSinteZ** [comment]
@P4sca1 my bad. I've missed this one :(
