### ISSUE TITLE
nuxtServerInit fires for each static dynamic route generated

### ISSUE THREAD

**Issue by bovas85** [nuxt/nuxt.js#3935]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/bovas85/nunziellasalluce.com](https://github.com/bovas85/nunziellasalluce.com)

### Steps to reproduce

- run `yarn` on the repo, then `yarn generate`

You'll see a log in the server console:
`============= Server Init API calls =============` along with other API calls
(don't worry I'm caching those on wordpress so feel free to try it out)

At the moment I've set the generate `interval` to `2500ms` but feel free to remove it to try the issue out.

Ideally we should improve nuxt generate in order to only call the APIs once and then store in cache or a file.

I've spoken with @Atinux yesterday at VueConf London about this for reference.

(it's Moustache Design)

### What is expected ?

The API calls should be cached and ran once per each nuxt generate (as it's the same code, it should be reused for each page in the app)

### What is actually happening?

nuxtServerInit fires x amount of times as the number of pages in the app generated.

### Additional comments?

Feel free to contact me here or on twitter at @moustachedsign

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7798">#c7798</a>)</em></sub></div>

**Comment by swunderlich** [comment]
Having the same issue. It only happens in dev mode in my case. When I build and start everything is working fine.

**Comment by bovas85** [comment]
this is referred to nuxt generate @swunderlich 
It does not happen in universal mode

**Comment by mattbrailsford** [comment]
Having the same problem. Trying to generate a static site and have `nuxtServerInit` setup to fetch some shared content however the API end point for that shared data is hit once per ever page being generate so the more pages I have to generate, the more times the API will be hit. 

`nuxtServerInit` should be called once at the start and then the Vuex state should be shared by all pages during `generate`

**Comment by bovas85** [comment]
so apparently this is expected @mattbrailsford , as @pi0 said, it's best to deal with this using a LRU cache or axios-extensions. I personally added this plugin and it solved the issue.

`axios.js`
```
import { cacheAdapterEnhancer } from 'axios-extensions'
import LRUCache from 'lru-cache'
const ONE_HOUR = 1000 * 60 * 60

const defaultCache = new LRUCache({ maxAge: ONE_HOUR })

export default function ({ $axios }) {
  const defaults = $axios.defaults
  // https://github.com/kuitos/axios-extensions
  defaults.adapter = cacheAdapterEnhancer(defaults.adapter, {
    enabledByDefault: false,
    cacheFlag: 'useCache',
    defaultCache
  })
}

```

**Comment by bovas85** [comment]
some in nuxtS

**Comment by mattbrailsford** [comment]
Fair enough. Thanks for the code sample, I'll give that a try :+1:
