### ISSUE TITLE
Suggestions for CSS handling in the future.

### ISSUE THREAD

**Issue by johnRivs** [nuxt/nuxt.js#3937]
### What problem does this feature solve?

Limited, not too nuanced CSS insertion options. Currently, you either inline or extract everything.
I'm aware some of the following could be made into 1 or more plugins. I'm not familiar with internals to understand what's able to be implemented in the context of Nuxt.

#### Avoiding requests for small size CSS
When `extractCSS` is set to `true`, CSS files above certain threshold would be `<link>`ed as usual and the ones below it would be inlined. @manniL explains very well in his [PR](https://github.com/webpack-contrib/mini-css-extract-plugin/pull/268#issuecomment-419638536) the problem with `<link>`ing the smaller files.
> I'll have a CSS file per component with a few (say ~5-25) lines of CSS in it, which are even smaller than the HTTP headers of the request to retrieve the file.

Reading about critical CSS, 14kb seems to be the sweet spot, although the number could be configurable. From this [article](https://gomakethings.com/inlining-critical-css-for-better-web-performance/)
> The magic number you should care about is 14kb. That’s (give or take) how much data a server sends per round trip when the browser makes a request for a web page. You want your above-the-fold content—required styles, scripts, markup, everything—to weight 14kb or less so that the browser can start rendering it as soon as that first packet of data is received.

From [Filament Group](https://www.filamentgroup.com/lab/performance-rwd.html)
> It’s helpful to consider some basic information about how our code is transferred during page load. Every request to the remote server takes time, and each response from the server carries a limited quantity of data. In order to aim for the fastest page loading time, we want to try to fit the code required for rendering the top portion of a given page in the first response from the server, which happens to carry around 14kb of compressed code (it’s often less, but 14’s a solid goal to shoot for).

> Basically, we want fit the HTML, CSS, and JavaScript that’s necessary for Start Render in that first 14kb round trip.

I have a CSS file that weighs 20-30kb in disk and is served by Nuxt as a 5.8kb file. I take it that `14kb of compressed code` suggests I should look at 5.8kb when comparing to the threshold. I don't know if figuring out the size of the file after compression but before serving is possible.

#### Allow inlined CSS to be cached
Borrowing from Filament Group's [loadCSS](https://github.com/filamentgroup/loadCSS)'s approach, after all the relevant assets are downloaded, fetch the CSS files below the threshold, i.e. the ones that were inlined. Then, set something in the client side (e.g. a cookie) that will let the server know inlined CSS is no longer required. From this point on, whatever CSS was inlined would now be `<link>`ed, since the browser has downloaded it.

#### Apply some _voodoo_ to inlined CSS
Pass the inlined CSS through PurgeCSS, just like extracted files. I guess this is less PurgeCSS and more of a Webpack thing.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7800">#c7800</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. To just get involved with the discussion, I've to mention that HTTP 2 problem about small requests us almost resolved. We have multiplexed connections as well as Header Compression. Also thanks to HTTP 2 push support it is even more efficient now. For long term caching browser has the ability to cancel accepting some of them if already cached.

Read more: https://http2.github.io/faq

PS: I'm not against anything about inlining small chunks. But tried to mention that there are alternative and much easier workarounds for that. Until tool chain support.

**Comment by manniL** [comment]
I agree that HTTP2 definitely favors smaller files, however, if you only have, say 25 characters of CSS in a component because you have a global CSS file otherwise, the extra request to the extracted file would lead to a worse performance than inlining the CSS would.

**Comment by johnRivs** [comment]
I happen to be using HTTP2 on my server yet I don't think it's widely adopted. At the very least, I'd like to have control over CSS handling.

**Comment by manniL** [comment]
@johnRivs Adoption rate is [pretty good!](https://w3techs.com/technologies/details/ce-http2/all/all) and all people who build SPAs (no matter which framework or SSR/CSR) should adopt it :relaxed:

**Comment by AdsonCicilioti** [comment]
This module ([nux-bulma-slim](https://github.com/mustardamus/nuxt-bulma-slim)) would do this job?
It uses PurgeCSS. But I'd also like to see Nuxt manipulate only the CSS of each page better.
Adopting or not an extra module like the Purge. I'm a little lay, but I always think of building an optimized and modular workflow, loading only what is necessary.

**Comment by AdsonCicilioti** [comment]
My thinking on this journey for css optimization, and how a node.js framework should manage css coming from a famous css library (like bulma, bs4, etc), would look like this:
If on the homepage there is a set of components A + B + C plus the basic structure (html, body, footer, p .. - "css resets") the main <style> tag of the page would be fed only the CSS needed for these components .
Oh not my little friend! ... Just use the CSS purge, it does that job.
But what if an Ajax button loads content from new components that do not yet have their styles in the <style> tag?
What do you suggest or what kind of tool would support this kind of dynamic CSS management?
If the PuergeCSS already does this without previously defining the classes of components that will be loaded by AJAX in its whitelist, how to configure it?

Forgive my humble lack of knowledge in JS. Because I am a Designer trying to expand horizons and trying to collaborate with the more optimized development flow.

**Comment by manniL** [comment]
Small follow-up: PurgeCSS **without extractCSS** is a thing. Easy usage with https://github.com/Developmint/nuxt-purgecss

**Comment by manniL** [comment]
@johnRivs A few things have changed (several caveats with `extractCSS` are gone, the size threshold thing is still present though. `extractCSS: false` is what I currently use bc. it aligns better with CSS in Components IMO, ...)

I'm closing here as we now have https://github.com/nuxt/rfcs. If you still want to have the CSS handling like your described in Nuxt, please create an RFC there :relaxed:
