### ISSUE TITLE
Implementation of nuxtClientInit Action

### ISSUE THREAD

**Issue by potato4d** [nuxt/nuxt.js#3938]
### What problem does this feature solve?

Currently, Nuxt.js does not have a way to create actions to be done only on the client.
It is possible to implement it using plugins and middleware, but it will be implemented with a different interface from nuxtServerInit.

Also, in SPA mode there is no equivalent of nuxtServerInit.

In order to solve this problem, I would like to add nuxtServerInit for clients.

### What does the proposed changes look like?

I implemented it as a module of Nuxt.js. However, I want Nuxt.js core to have nuxtClientInit.

https://github.com/potato4d/nuxt-client-init-module

- - -

Although it was written that it is advancing the implementation before, is there any plan to implement it?

If possible, I would like to collaborate on implementation.

https://github.com/nuxt/nuxt.js/issues/1857#issuecomment-336874401

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7801">#c7801</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @potato4d!
Sure, fire up a PR for it and we'll look into it ☺️

**Comment by potato4d** [comment]
I'm doing it now!

**Comment by manniL** [comment]
@potato4d Any update? ☺️

**Comment by potato4d** [comment]
@manniL 
I am trying hard but I am a bit struggling.
The goal is to submit a pull request next week!

**Comment by manniL** [comment]
@potato4d Take your time and don't hesitate to ask for help if you get stuck ☺️

**Comment by manniL** [comment]
Closing this in favor of the linked PR, (possibly) upcoming RFC and further updates.

**Comment by johanvanwambeke** [comment]
So what is the solution now?

**Comment by manniL** [comment]
@johanvanwambeke 	feel free to use https://github.com/potato4d/nuxt-client-init-module

**Comment by sebmor** [comment]
I really would like to see this as a core functionality of Nuxt. It can be even something like nuxtInit that can works on either SPA or Server. If it's worth to have nuxtServerInit as a core feature then an equivalent for client at the very least should also be worth including.
