### ISSUE TITLE
host and port is not able to configure from nuxt.config.json

### ISSUE THREAD

**Issue by sweetim** [nuxt/nuxt.js#3941]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://gitlab.com/hosweetim/timx-site/blob/master/nuxt.config.js](https://gitlab.com/hosweetim/timx-site/blob/master/nuxt.config.js)

### Steps to reproduce

add the server object

```
server: {
        port: 8080,
        host: '0.0.0.0'
},
```

and run `npm start`

### What is expected ?

The port and host should be configured based on the `nuxt.config.json`

### What is actually happening?

Default value of host and port is used

### Additional comments?

Follow this step to configure host and port
 `Configure in nuxt.config.json` https://nuxtjs.org/faq/host-port

But when I run `npm start`, it is still using the default port and host

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7803">#c7803</a>)</em></sub></div>

**Comment by manniL** [comment]
https://gitlab.com/hosweetim/timx-site/blob/master/package.json#L8

You use PORT and HOST there which override your nuxt config values!

**Comment by manniL** [comment]
The bug is valid anyway :thinking: 

(Thanks to @aldarund)

**Comment by sweetim** [comment]
Sorry @manniL for my sloppiness , dint post a link that reproduce this problem, i tried it locally and dint push it to the cloud, when it is not working!

Thanks @aldarund people like you that makes `Nuxt` community so awesome! ;)
looking forward for it!
