### ISSUE TITLE
Extracted CSS is loaded all together

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#3943]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/manniL/nuxt-extract-css-include-bug/](https://github.com/manniL/nuxt-extract-css-include-bug/)

### Steps to reproduce

1. Clone repo
2. `npm i`
3. `npm run build && npm start`
4. open `localhost:3000/` and `localhost:3000/other`

### What is expected ?

*  `localhost:3000/` -> Green background but no red color 
*  `localhost:3000/other` -> No Green background but no red color 

### What is actually happening?

The CSS of both pages is loaded together.
When using `scoped` styles, the CSS doesn't *overlap* but is still loaded (which harms perf if you have a lot of components/CSS).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7805">#c7805</a>)</em></sub></div>

**Comment by pimlie** [comment]
Does it also happens if you add a [`scoped`](https://vue-loader.vuejs.org/guide/scoped-css.html) tag?

**Comment by manniL** [comment]
@pimlie Good point! Will try :thinking:

**Comment by manniL** [comment]
@pimlie Well, the styles don't interfere then anymore but CSS is still loaded (which was the "main point" here :see_no_evil: )

**Comment by mauxtin** [comment]
I am actually having the same problem :/ Have anyone figured this out?

**Comment by manniL** [comment]
@mauxtin The only workaround are scoped styles or not extracting at the moment.

**Comment by manniL** [comment]
Not stale ⛔️

**Comment by nmfzone** [comment]
Do you have a solution for this issue? @manniL

**Comment by manniL** [comment]
@nmfzone This depends on https://github.com/webpack-contrib/mini-css-extract-plugin as #4219

**Comment by nmfzone** [comment]
So, I think, this is VueServerRenderer problem. Let's take a look https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90#issuecomment-439405759

**Comment by Avcajaraville** [comment]
I can confirm Im having the same problems.

I filled issues on [here](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/307) and [here](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90) but no luck so far :(

This is breaking all our deployments at the moment...

**Comment by manniL** [comment]
@Avcajaraville A workaround would be not using extractCSS for now :|

**Comment by Avcajaraville** [comment]
@manniL and what would you recommend as an alternative?

**Comment by nmfzone** [comment]
![carbon](https://user-images.githubusercontent.com/10361906/48719977-50fc0580-ec51-11e8-9e7c-c648a4d41611.png)
 My configuration right now :|

**Comment by manniL** [comment]
@nmfzone any particular reason you’d need to extract it?

**Comment by Avcajaraville** [comment]
@manniL  I would say probably caching issues is the biggest one.

We dont wanna put all our modules/routes css in a style tag. Depending on the view it can be quite big.

**Comment by manniL** [comment]
@Avcajaraville You can completely cache the component files which include the CSS. If you build it up modularly as well (moving component CSS into component files via `<style>` tags) you'll also only load what's needed.

**Comment by Avcajaraville** [comment]
I don't think I quite understand you. To be honest, I came across this issue from mini css, but not using nuxt.

I found out I can have the css in js, but thats not satisfing for us, as we need CSS independent from JS (so JS is not needed to browse our site). The only solution so far, is to inject all the CSS into a style tag, which is impossible to cache, isn't?

Is there anything Im missing ?

Thanks a lot for your time and answers :)

**Comment by manniL** [comment]
@Avcajaraville Oh, I see, wasn't aware of that :| In this case, you'll likely have to wait for a fix.

**Comment by chentianyuan** [comment]
same issue here

**Comment by jochouen** [comment]
@manniL 
how about remove other link with hooks?
I tried it and did it.
May be not a good idea.

**Comment by manniL** [comment]
@jochouen can you share your code for that?

It might affect perf but it could be a "workaround"

**Comment by jochouen** [comment]
@manniL 
```
hooks: {
 generate: {
  page(generate) {
    const cheerio = require('cheerio'),
          doc = cheerio.load(generate.html); 
          htmlPath = generate.path.replace('.html', '');
    doc('link[rel=stylesheet]').filter(function(index, element) {
       if (doc(this).attr('href').indexOf('pages') > 0 && doc(this).attr('href').indexOf(htmlPath) < 0) {
        doc(this).remove().html();
       }
    })
    generate.html = doc.html();
  }
 }
}
```

before: 
test.html
```
<link rel="stylesheet" href="/_nuxt/css/app.css">
<link rel="stylesheet" href="/_nuxt/css/pages/index.css">
<link rel="stylesheet" href="/_nuxt/css/pages/test.css">
<link rel="stylesheet" href="/_nuxt/css/pages/users/_id.css">
<link rel="stylesheet" href="/_nuxt/css/pages/users/top.css">
```

after:
test.html
```
<link rel="stylesheet" href="/_nuxt/css/app.css">
<link rel="stylesheet" href="/_nuxt/css/pages/test.css">
```

**Comment by fe-shinemo** [comment]
my test, with vue 2.5.19 (2.5.18) released, this bug has been fixed already, @manniL

**Comment by manniL** [comment]
@fe-shinemo Indeed. Updated the example and it's working now
