### ISSUE TITLE
Nuxt checks for serverMiddleware file existence in sources instead of built files

### ISSUE THREAD

**Issue by IGassmann** [nuxt/nuxt.js#3948]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://glitch.com/edit/#!/heady-cheque](https://glitch.com/edit/#!/heady-cheque)

### Steps to reproduce

1. Create a serverMiddleware file: `$ touch ./src/api/index.js`
2. Add it to the config file:
```json
{
    ...
    srcDir: 'src/',
    buildDir: 'dist',
    serverMiddleware: ['~/api/index'],
}
```
3. Run `$ nuxt build`
5. Deploy `dist and `node_modules` directories to server
4. Run `$ nuxt start` on the server (meaning without src/ directory)

### What is expected ?

When Nuxt is started, it shouldn't check for a file existence in the sources, but check for a built one. We shouldn't need to deploy the sources into the server, but only the dependencies and the build directory (`.nuxt` or `dist`).

### What is actually happening?

Nuxt will fail because it won't be able to resolve the middleware file since there isn't any src/ folder in the server.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7809">#c7809</a>)</em></sub></div>

**Comment by manniL** [comment]
So, you are suggesting copying the middleware files to the dist as well?

**Comment by sweetim** [comment]
and any loader registered in the `nuxt.config.js` build will not run for files in `serverMiddleware` 
related to #3890 too

**Comment by IGassmann** [comment]
@manniL yes, if that's not already the case. All files necessary for runtime should ideally be present in the `buildDir`.

**Comment by galvez** [comment]
@IGassmann can you provide that glitch as a git repo or downloadable file? Or grant me access to download over at Glitch itself, of course.

**Comment by galvez** [comment]
@IGassmann thanks, saw it -- I'm pushing a fix soon cc @Atinux

**Comment by fgian1969** [comment]
Please check the  Bug #3955 (Nuxt servermiddleware route /api is ignored when deployed or served on Firebase). It seems a related problem.....

**Comment by IGassmann** [comment]
@galvez have you been able to fix this?

**Comment by luishdz1010** [comment]
Is there any workaround?

**Comment by manniL** [comment]
Moving the `serverMiddleware` in the dist folder would lead to broken relative imports, which is somewhat hard to "prevent"/"avoid".

Instead, the documentation will include which files have to be present on the server soon:tm:.
