### ISSUE TITLE
Google Optimize 360 - hydration problem?

### ISSUE THREAD

**Issue by tonyhtp** [nuxt/nuxt.js#395]
Does anyone have a suggestion on how to solve the problem not being able to use **Google Optimize** due to hydration.

I use SSR and the page comes out just fine to the client (browser), when site administrator conducts some A/B testing using _Google Optimize_  (rewrites parts of the DOM) the rehydration rewrites the DOM back to the original text = AB test can not be conducted.

I would prefer that the server rendered page did not get re-populated by the on page `window.__NUXT__` variable. 

I would like to avoid generating static html-files due to the fact the data comes from CaaS Contentful and we don't want to be forced to generate new static page "manually" every time a new content page is published in Contentful.

Does anyone have a way avoid hydration or in some other way make this work with SSR?

Maybee the **vue-router 2.2** (already out) which supports **router.onReady** could help in some way, isn't there even an ugly solution to this problem?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c348">#c348</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @tonyhtp 

Is it possible to have some code example to reproduce your issue so I can try to help you?

**Comment by tonyhtp** [comment]
Haven't figured out a solution to this yet, see this gif-anim on hos the Optimize 360 A/B test (updates DOM by javascript) is overwritten by the rehydration(I think):
![2017-03-20_13-24-28](https://cloud.githubusercontent.com/assets/5848643/24508074/ab9cb2ea-1562-11e7-82e5-caa51aee6e27.gif)

Some code example of how we place the scripts on the site:

head () {

	return {
		script: [
			// Init datalayer
			{ innerHTML: "..." },
			// Google Optimize 360 code
			{ innerHTML:"..." },

			// Google Tag Manager
			{ innerHTML: "" }
		],
		__dangerouslyDisableSanitizers: ['script']
	}
 }

**Comment by pi0** [comment]
An SSR friendly solution coming soon ;)

**Comment by galvez** [comment]
@pi0 any status on this? :)

**Comment by uptownhr** [comment]
https://www.npmjs.com/package/nuxt-google-optimize

Found this. Will be trying it out amd seeomg how well it functions

**Comment by pi0** [comment]
This is actually the solution that we were working on at Alibaba. (It is being used for production for at least two months)

https://github.com/alibaba-aero/nuxt-google-optimize

Feel free opening issues if having questions.

PS: Don't forget to star it ;)
