### ISSUE TITLE
Transition issue when using redirect in validate

### ISSUE THREAD

**Issue by thariddler** [nuxt/nuxt.js#3954]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/therddlr/transition-issue](https://github.com/therddlr/transition-issue)

### Steps to reproduce

If you navigate to `issue` page you can see that next route instantly appears without waiting page transition to finish. 
The `ok` page is working fine. 
Also, if you comment out `validate` in `issue` page then transition mode is not broken. So this is somehow related with redirect in validate.

### What is expected ?

I expect normal page transition

### What is actually happening?

Transition mode is broken.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7816">#c7816</a>)</em></sub></div>

**Comment by Guizzoni** [comment]
I'm also having this issue. Is there a workaround?

**Comment by therddlr** [comment]
@Guizzoni I ended up with not using `validate` at all.

**Comment by Guizzoni** [comment]
How would you return a 404 error without using validate?

**Comment by thariddler** [comment]
I still would sole to see the fix. How can you close this only if it's not active, if this is a bug?

**Comment by Guizzoni** [comment]
I believe this is related to #4132 which was also closed without a solution.

**Comment by awronski** [comment]
It is discouraging that the error reports with reproduction steps are being closed without any check :(

**Comment by Guizzoni** [comment]
This still happens in the latest nuxt-edge version.
