### ISSUE TITLE
in my style scoped  , '~/assets' won't work

### ISSUE THREAD

**Issue by ZooTopiaGG** [nuxt/nuxt.js#3968]
exp: background-image: url("~/assets/images/1@2x.png");
but result: http://local.tiejin.cn:3601/assets/images/1@2x.png 404 (Not Found)
What is the reason?
and In html, it is available again.

**Comment by po3rin** [comment]
from releases
https://github.com/nuxt/nuxt.js/releases/tag/v2.0.0

Due to css-loader upgradation, use ~assets instead of ~/assets for alias in <url> CSS data type, e.g., background: url("~assets/banner.svg")

I faced same issue. but above solution resoluved this.
