### ISSUE TITLE
Console errors don't disappear after fixing

### ISSUE THREAD

**Issue by romikzo** [nuxt/nuxt.js#3970]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[http://localhost:3000](http://localhost:3000)

### Steps to reproduce

Follow the instructions in nuxt.js repo README.md:
1) `yarn add nuxt`
2) add scripts: {"nuxt": "nuxt"} to package.json
3) add file pages/index.vue with content
```javascript
<script>
export default {
}
</script>
```
4) yarn run nuxt

Then try to remove `}` in pages/index.vue. You will see error in terminal. After return `}` back,  error in terminal not disappear and HMR will cease work.

### What is expected ?

Nuxt should see that i fix error and show success inscription.

### What is actually happening?

Error stay

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7833">#c7833</a>)</em></sub></div>

**Comment by manniL** [comment]
Can not reproduce.

**Comment by manniL** [comment]
![nuxt-cannot-reproduce](https://user-images.githubusercontent.com/640208/46109988-20ac6380-c1da-11e8-81bd-c095c8ebc091.gif)

**Comment by romikzo** [comment]
Error in terminal disappear too?

**Comment by romikzo** [comment]
Look at the console: https://glitch.com/edit/#!/join/bec57521-10a6-419d-9a08-3cc694b58de0

**Comment by manniL** [comment]
Ah, gotcha. The error will stay in console.
This is only a visual bug though as HMR will continue to work (as shown in the GIF)

**Comment by baumannzone** [comment]
Same issue, reported here:  
https://stackoverflow.com/questions/52715349/linter-eslint-keep-errors-after-fix-them-in-nuxt-app

It looks like you can keep working, but for newcomers users it's very confusing

**Comment by gapipro** [comment]
Yea, same issue happens to me also. It's really annoying, because in terminal you normally check if everything is compiled correctly.

**Comment by zlzdp** [comment]
same issue, the last eslint error message not auto remove when I fixed for eslint.

**Comment by manniL** [comment]
There is no screen clearing anymore ;) 
https://github.com/nuxt/webpackbar/releases

**Comment by evry-johber** [comment]
@manniL Can you elaborate how that update affects this issue? I tried using Nuxt 2.32 in spa-mode and get "compiled successfully" regardless of any errors in my files. Do I need to adjust my config?

**Comment by manniL** [comment]
![showcase](https://user-images.githubusercontent.com/640208/48984710-4c26ce00-f0f7-11e8-9e6d-6caa84c8fb1f.gif)


Errors will be clearly shown but there is no screen clear anymore ;)

**Comment by evry-johber** [comment]
@manniL Sure, I'll see what I can do to create a minimal reproducible example

**Comment by evry-johber** [comment]
@manniL Hmm, did a fresh `npx create-nuxt-app`, did the very same change as you did in universal mode, and still no error reported. I'm using Node 10.13 on Windows 10. Should be enough to add eslint in the `create-nuxt-app` wizard, right?

**Comment by manniL** [comment]
@evry-johber That should even work without eslint as a component couldn't be found while building :thinking:

**Comment by manniL** [comment]
Sure. Make your eslint-config more strict ;)

![image](https://user-images.githubusercontent.com/640208/48985654-9f058300-f101-11e8-9797-e3c9cd46ab9e.png)

I'd suggest our setup (https://github.com/nuxt/eslint-config)

**Comment by evry-johber** [comment]
@manniL Aaah, thank you!!
