### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by btmdave** [nuxt/nuxt.js#398]
I'm trying to include [vue2-dragula](https://github.com/kristianmandrup/vue2-dragula), I've setup in plugins `vue2-dragula.js` with:

```
import Vue from 'vue'
import { Vue2Dragula } from 'vue2-dragula'

if (process.BROWSER_BUILD) {
  Vue.use(Vue2Dragula, {
    logging: {
      service: true
    }
  })
}
```

Then included in `nuxt.config` `plugins: ['~plugins/vue2-dragula']`

It seems that `process.BROWSER_BUILD` isn't being factored in?

**Comment by alexchopin** [comment]
Hi, 
You need to import Vue2Dragula inside the condition.
```js
import Vue from 'vue'

if (process.BROWSER_BUILD) {
  const Vue2Dragula = require('vue2-dragula')
  Vue.use(Vue2Dragula, {
    logging: {
      service: true
    }
  })
}
```
