### ISSUE TITLE
Split nuxt configuration

### ISSUE THREAD

**Issue by mahapo** [nuxt/nuxt.js#3985]
### What problem does this feature solve?

On bigger nuxt projects the ```nuxt.config.js``` file gets bigger and confusing. My idea would be to create an extra folder where you can create single configuration files. This would then be merged with the ```nuxt.config.js``` file.

I could also consider creating different config types that can be defined in the main config file.

### What does the proposed changes look like?

*./nuxt.config.js*
```javascript
export default {
  env: {
    var1: "Hello",
    var2: "world"
  }
```

➕

*./config/server.js*
```javascript
export default {
    port: 8000,
    host: '0.0.0.0',
}
```

=

```javascript
export default {
  env: {
    var1: "Hello",
    var2: "world"
  },
server: {
    port: 8000,
    host: '0.0.0.0'
  }
}
```

**With configuration types it would look like this**
*./nuxt.config.js*
```javascript
export default {
  configuration: "dev",
  env: {
    var1: "Hello",
    var2: "world"
  }
```

➕

*./config/server--dev.js* (If this file not exist the *./config/server.js* will be merged)
```javascript
export default {
    port: 3000,
    host: '0.0.0.0',
}
```

=

```javascript
export default {
  env: {
    var1: "Hello",
    var2: "world"
  },
server: {
    port: 3000, // 8000 if file not exist
    host: '0.0.0.0'
  }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7844">#c7844</a>)</em></sub></div>

**Comment by manniL** [comment]
What you *could* do is importing the files "as usual" with `import nuxtConfig from './path/to/config'` and then selectively add/spread it into the object

```js
import nuxtConfigDev from "path/to/dev.js"
import nuxtConfigProd from "path/to/prod.js"

const toInclude = process.env.NODE_ENV === 'production'? nuxtConfigProd : nuxtConfigDev

export default {
    head: '...',
    ...toInclude
}
```

**Comment by mahapo** [comment]
I can do that but this is't the lovely nuxt way :)

**Comment by manniL** [comment]
@mahapo Agreed 😋

**Comment by pi0** [comment]
@mahapo Please hold on. I will submit a Proposal soon.

**Comment by aebrs** [comment]
> @mahapo Please hold on. I will submit a Proposal soon.

Soon means when? Deployment of nuxt projects on server is critical. Some one would take responsibility and provide enough document for those who start using nuxt in hope to upload and benefit from it, Sure not for it's FUN.

**Comment by manniL** [comment]
Further info and discussion in https://github.com/nuxt/rfcs/issues/16
