### ISSUE TITLE
[Feature Request] Allow to specify html minifier config for nuxt.generate

### ISSUE THREAD

**Issue by OEvgeny** [nuxt/nuxt.js#399]
I noticed what whitespaces in generated html were removed, but I wanted them to be. I found what it is because of `html-minify` config passed to `nuxt.generate` [here](https://github.com/nuxt/nuxt.js/blob/master/lib/generate.js#L93-L111).

I think it would be great if we can specify minification config for generation. What do you think?

Thanks for nuxt.

**Comment by OEvgeny** [comment]
I also can start working on pull request for this in case you think it is a good idea.

**Comment by ausir0726** [comment]
I also some problem with HTML minify 
I am try to fix my HTML vue

**Comment by Atinux** [comment]
Sure, a PR is always welcome 👍 

It could be in the `nuxt.config.js` in `generate.minify` which will be an object.

**Comment by Atinux** [comment]
It's implemented in the `0.10` verision, see https://nuxtjs.org/api/configuration-generate#minify

**Comment by OEvgeny** [comment]
@Atinux wow, thank you so much :)

**Comment by jazoom** [comment]
I'm wondering why we can easily adjust the minification config of `generate` but not of any other build? Why is this not applicable to Nuxt in general?
