### ISSUE TITLE
Use initialState instead of state when exporting in modules mode

### ISSUE THREAD

**Issue by simonsmith** [nuxt/nuxt.js#3995]
### What problem does this feature solve?

The issue I've encountered is this:

```js
export const state = () => ({
  someState: 'foo',
});

export const actions = {
  ACTION({ dispatch, commit }) {
    
    // I forgot to destructure state in the function arguments
    // so now I'm accessing the state function by accident

    if (state.something) {
      // .. never true
    }
  }
};
```

### What does the proposed changes look like?

Allow state to be exported as `initialState`:

```js
export const initialState = () => ({
  someState: 'foo',
});

export const actions = {
  ACTION({ dispatch, commit }) {
    
    // Error can now be picked up by ESLint or will 
    // throw an error with state being undefined
  }
};
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7851">#c7851</a>)</em></sub></div>

**Comment by felubra** [comment]
I'd like to help with this issue 😊

**Comment by felubra** [comment]
Question: should we deprecate the old behavior, the export using the 'state' function name? Or should we use both - check for a 'state' function then check for a 'initialState' function?

**Comment by simonsmith** [comment]
Perhaps deprecate the `state` export but support both for now and then remove `state` in a future release to give plenty of time for migration

**Comment by felubra** [comment]
@manniL I would appreciate hearing your opinion on this, thanks!

**Comment by manniL** [comment]
@felubar Sorry, somehow I missed the notifications from that issue 🤔

I would not deprecate **state** because the default VueX initialization structure should still work. It’d be a nice addition to accept `initialState` as well

**Comment by manniL** [comment]
As stated in #4096, this feature won't see the daylight.

Thanks for your efforts @felubra! :pray:
