### ISSUE TITLE
There is a problem with caching in the koa2 template

### ISSUE THREAD

**Issue by warriorBrian** [nuxt/nuxt.js#3999]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

```bash

$ npx create-nuxt-app project

$ koa template

$ npm install

```

### What is expected ?

I want to be able to cache data normally in the koa2 template. As in the express template, I can tell the browser to return the 304 state, but in the koa2 template each refresh is 200 state, and in the express is 304 state.

### What is actually happening?

In the koa2 template, the browser state is 200 state each time, and in the express state is 304 state, I expect koa2 to return the 304 state.

## express template

![20180928124612.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/36186e70-c2da-11e8-ace0-f5a6855e9dd4.png)

## koa2 template

![20180928124618.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/eac17980-c2d9-11e8-ace0-f5a6855e9dd4.png)

### Additional comments?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7856">#c7856</a>)</em></sub></div>

**Comment by aldarund** [comment]
@warriorBrian  Its a repo for nuxt itself. Please submit your bug report into create-nuxt-app project. https://github.com/nuxt/create-nuxt-app/issues
