### ISSUE TITLE
Async data inside nuxt.config.js

### ISSUE THREAD

**Issue by McSneaky** [nuxt/nuxt.js#4005]
### What problem does this feature solve?

Currently there is no nice way how to use async data inside nuxt.config.js. 
For example getting some module configuration from remote server, getting head data, list of plugins that need to be enabled for current build etc.

This would allow to use same Nuxt app for multiple similar sites but with slight difference of configuration that is changeable from remote admin panel.

### What does the proposed changes look like?

Something like this (quite pseudocode) 
```js
// nuxt.config.js

const getHeadConfig = async () => {
  let { data } = await axios.get('/my/head/config/url')
  return {
    ...data,
    title: 'hurrdurr'
  }
}

module.exports = {
  mode: 'universal',

  // Get conf from remote with axios
  loading: axios.get('/my/loading/config/url'),

  // Use some method to get data from remote
  head: getHeadConfig()
}

```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7860">#c7860</a>)</em></sub></div>

**Comment by manniL** [comment]
I think this problem could be tackled as we do it with modules, plugin etc.

If the export of `nuxt.config.js` is a `function`, we should call and `await` it. 🤔
