### ISSUE TITLE
Global components registered with plugins is not loaded on client side

### ISSUE THREAD

**Issue by ycmjason** [nuxt/nuxt.js#4006]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://codesandbox.io/s/o96v4m0k76](https://codesandbox.io/s/o96v4m0k76)

### Steps to reproduce

1. Add `plugins/global.js` and import `Vue` and a component.
2. Register the component with `Vue.component('my-comp', Component)`
3. Add `plugins: [ '@/plugins/global.js' ]`in `nuxt.config.js`
4. Use `<my-comp></my-comp>`

### What is expected ?

Component should be registered with Vue and can be used globally.

### What is actually happening?

Errors shown.

```
- [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content.
- [Vue warn]: Unknown custom element: <my-comp> - did you register the component correctly?
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7863">#c7863</a>)</em></sub></div>

**Comment by manniL** [comment]
Might be related to:

> Remember that global registration must take place before the root Vue instance is created (with new Vue). 
([source](https://vuejs.org/v2/guide/components-registration.html#Automatic-Global-Registration-of-Base-Components))

**Comment by aldarund** [comment]
@ycmjason @manniL  it should and in fact it is working. It would break really 99% of apps if this wont work.  I just forked that codesandbox example and it work right after it without changing anything. Codesandbox bug?

**Comment by manniL** [comment]
No CSB bug.

**Comment by manniL** [comment]
Wrap your component declaration in the default export function:

```js
export default () => {
  Vue.component("myId", {...})
}
```

Example:
https://codesandbox.io/s/62wmr9wjn

**Comment by manniL** [comment]
PS: We should document this somewhere

**Comment by lbogdan** [comment]
@ycmjason Can you maybe join the [CodeSandbox Discord](https://discord.gg/KE3TbEZ) chat to try and get to the bottom of this?
