### ISSUE TITLE
transpile options for build is not working in server side

### ISSUE THREAD

**Issue by axetroy** [nuxt/nuxt.js#4007]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://codesandbox.io/s/5y7lzjq93k](https://codesandbox.io/s/5y7lzjq93k)

### Steps to reproduce

no need.

### What is expected ?

```
  build: {
    transpile: ['vux'],
    ...
  }
```

transpile options should work in client side and server side.

### What is actually happening?

transpile options current only work in client side.

server side still throw error

```
SyntaxError: Unexpected token export
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7866">#c7866</a>)</em></sub></div>

**Comment by aldarund** [comment]
@axetroy your reproduction link https://codesandbox.io/s/5y7lzjq93k show no errors

**Comment by manniL** [comment]
Be aware that `transpile` has been implemented in Nuxt 2 and won't work for Nuxt 1.X
