### ISSUE TITLE
preserveWhitespace=false not work in Nuxt2

### ISSUE THREAD

**Issue by herrdu** [nuxt/nuxt.js#4009]
Yesterday ,I update my project to Nuxt2.0 from Nuxt1.0. 
I found the space between dom element has changed. 
So , I set preserveWhitespace:false to  vue-loader. But it's not working ? 

Does someone konw the reason?
![image](https://user-images.githubusercontent.com/6762269/46240725-781b2100-c3de-11e8-80d1-e837c0c94798.png)

**Comment by UltramarineLights** [comment]
I have the same issue, can't seem to make preserveWhitespace working.
I think an error in your specific code @herrdu  is that in the vue-loader documentation the preserveWhitespace option is under compilerOptions object, which is missing in your case.
But I tried also with compilerOptions and it is still not working.

**Comment by herrdu** [comment]
Thank you @UltramarineLights 

Yes. In the new document , the preserveWhitespace option is under compilerOptions object. So ,I write like this : 
```
    loaders: {
      vue: {
        compilerOptions: {
          preserveWhitespace: false
        }
      }
    }
```

And it worked .
