### ISSUE TITLE
Can’t get nested routes to work with a slug

### ISSUE THREAD

**Issue by EmmanuelBeziat** [nuxt/nuxt.js#401]
Hi,

I’m having troubles to have a nested route working with anything but a number.

I basically used [this exemple](https://nuxtjs.org/examples/nested-routes), and ended up with something like this:

![test1](https://cloud.githubusercontent.com/assets/6781337/24075259/0c204da6-0c18-11e7-9a5f-df491bd2e3f3.jpg)

`blog.vue`
```vue
<template>
	<section class="blog">
		<nuxt-link :to="'/blog/'+post.id">{{ post.name }}</nuxt-link>
	</section>
</template>

<script>
import axios from 'axios'

export default {
	data () {
		return axios.get('http://localhost:3001/posts')
		.then((res) => {
			return { posts: res.data }
		})
	}
}
</script>
```
`_blog/_id.vue`
```vue
<template>
	<article class="post">
		<h1>{{ title }}</h1>
		{{ body }}
	</article>
</template>

<script>
import axios from 'axios'

export default {
	validate ({ params }) {
		return !isNaN(+params.id)
	},

	data ({ params, error }) {
		return axios.get(`http://localhost:3001/posts/${+params.id}`)
		.then((res) => res.data)
		.catch(() => {
			error({ message: 'Post introuvable', statusCode: 404 })
		})
	}
}
</script>
```

In this case, everything works just fine. Clicking on the link get me the right url (`/blog/1`) and when clicking on a link, it’s opening the good page, with proper content.

But the thing is, I don’t wanna have an ID in the url, only a slug. I wanna have something like this: `/blog/my-article-is-wonderful`, so I set up my folder like this:

![test2](https://cloud.githubusercontent.com/assets/6781337/24075312/1a367b30-0c19-11e7-955c-f671af8a72fc.jpg)

`blog.vue`
```vue
<template>
	<section class="blog">
		<nuxt-link :to="'/blog/'+post.slug">{{ post.name }}</nuxt-link>
	</section>
</template>

<script>
import axios from 'axios'

export default {
	data () {
		return axios.get('http://localhost:3001/posts')
		.then((res) => {
			return { posts: res.data }
		})
	}
}
</script>
```
`_blog/_slug.vue`
```vue
<template>
	<article class="post">
		<h1>{{ title }}</h1>
		{{ body }}
	</article>
</template>

<script>
import axios from 'axios'

export default {
	validate ({ params }) {
		return !isNaN(+params.slug)
	},

	data ({ params, error }) {
		return axios.get(`http://localhost:3001/posts/${+params.slug}`)
		.then((res) => res.data)
		.catch(() => {
			error({ message: 'Post introuvable', statusCode: 404 })
		})
	}
}
</script>
```

Now, the link href is properly setup and give the right url to follow, but when clicking I get to my error page with a 404 error; even though the path is good in the url bar.

Nothing special in the console or the shell.

I just can’t get it. I tried with another param, like an userID, and it worked well too. But if I try to get a route with a slug or anything else than a number, it fails.

What am I missing?

Thanks!

**Comment by ausir0726** [comment]
```
axios.get(`http://localhost:3001/posts/${+params.slug}`)
```
why you have a plus in you ${var}
maybe you should try
```
axios.get(`http://localhost:3001/posts/${params.slug}`)
```

**Comment by EmmanuelBeziat** [comment]
Hi,

The + in the var is in the example: https://nuxtjs.org/examples/custom-routes Even though I found it strange, I tried without the + and it wasn’t working at all, even with numbers.

About the _blog folder naming, if I don't put the _ behind, it just need to have an index.vue Inside to work with the blog.vue; but it's working too if I rename this blog.vue as index.vue and put it in the folder with no underscore. I changed to this, it's cleaner.

That being said, the problem remains: It's still not working with slugs, but okay with numbers.

I look at your example, but I can't see what's so different in it, except the fact that you get the datas asynchronously. But I don't think it has anything to do with this, because it don't look like the page is even loaded.

Thanks for your response, though :)

**Comment by ausir0726** [comment]
that so strange
but If you can upload your api on internet
maybe I can try to write a test  :)

**Comment by EmmanuelBeziat** [comment]
Everything is on github : https://github.com/EmmanuelBeziat/emmanuelbeziat/tree/vuejs-static
But the datas come from a local service, so if you wanna test, you’ll have to change the source given to axios.

Thanks

**Comment by ausir0726** [comment]
but I need your api service on Internet .
maybe I will change my api service and test , first .
but if can get data fron your api service will be better .

**Comment by EmmanuelBeziat** [comment]
It's here : https://github.com/EmmanuelBeziat/node-rest

But it's just a simple rest content.

**Comment by ausir0726** [comment]
hi , I think you have a validate
```
validate ({ params }) {
  return !isNaN(+params.slug)
  // need params.slug is a number
},
```
so I remove ! and +
```
validate ({ params }) {
  return isNaN(params.slug)
},
```
and I can get data from local service ..

**Comment by EmmanuelBeziat** [comment]
Holy sh…

Of course. it was checking if it's an integer. How on earth did I not see this ?! So dumb.
That's why there's a + inside the param.

Thanks a lot!

**Comment by ausir0726** [comment]
I didn't seen it either  😆
