### ISSUE TITLE
http2 push headers - should be a function

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#4011]
### What problem does this feature solve?

Now there is no configuration to decide what resources we want to push to the client.
So if it is returning client we are pushing all the resources even if he has it.

If the ```http2: push``` will be a function we could decide if we want to push and what.
It will be huge client optimalization.

Now we have something similar in ```shouldPrefetch``` and ```shouldPreload```

### What does the proposed changes look like?

Besides ```file``` and ```type``` we need ```request``` to check for cookies or some other headers and ```response``` to set some output.

This is just example how we could use new implementation.
(isReturningVisitor is some custom logic that check for client cookies)

```js
render: {
    http2: (req, res, file, type) => {
       return isReturningVisitor(req) === false && type === 'script'
    }
  },
```

Than for example [nginx](https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/) can read the push headers and push the resources.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7870">#c7870</a>)</em></sub></div>

**Comment by awronski** [comment]
Nuxt can do even better out of the box.

New visitor
1. Add push headers to all resources.
2. Set Cookie with resources hashes.

Returning Visitor
1. Read cookie
2. Compare the hashes from cookie.
3. Add push headers only to resources that changes.
4. Update to cookie.


Of course it could be great if developer could overwrite default behavior or disable it.

**Comment by tillkruss** [comment]
This would also allow pushing assets based on user agent 👍🏻

**Comment by manniL** [comment]
@awronski Hey! How is it going? :relaxed:

**Comment by awronski** [comment]
@manniL Still experimenting, need more time. Will give you know.

**Comment by manniL** [comment]
Sounds good! Please make sure to not introduce breaking changes for it (even though it's not documented 🙈)

**Comment by awronski** [comment]
@manniL It is not possible, because `shouldPush` accept only single file and I need to pass req, res and the array of all push assets.

The present signature is:
`shouldPush(fileWithoutQuery, asType)`

I need something like this:
`shouldPush(req, res, publicPath, preloadFiles)`

I can introduce one more option to `http2` to make it backward compatible. 

What do you suggest?

**Comment by clarkdo** [comment]
@awronski Thank you for the good idea.

I want to know a bit further what's the reason for using a batched `shouldPush` instead of current one ?

If it's really necessary, I suggest you add a new method `pushAssets` which is more semantic and won't break the compatibility and may add a `deprecated` log info in `shouldPush`.

**Comment by tillkruss** [comment]
Using the existing shouldPush function wouldn't allow for much flexibility. Passing all assets to a http2.push function would be great and it avoids breaking changes.

**Comment by clarkdo** [comment]
@tillkruss Agree

**Comment by clarkdo** [comment]
> Using the existing `shouldPush` function wouldn't allow for much flexibility. Passing all assets to a `http2.push` function would be great and it avoids breaking changes.

**Comment by awronski** [comment]
@clarkdo Now you can only filter the assets that you want to push but you don't know the user state.

If we add a third parameter, which is a function `pushAssets(req, res, publicPath, preloadFiles)` we can conditionally push assets to the user (based on the cookie value, user type etc)

If the user has already some assets why to push them again. It will make the app faster.

If you agree, I will push the changes. I will leave the `shouldPush` as it is and and new option and document it.
