### ISSUE TITLE
NuxtserverInit and Middleware are being hit on *.css.map requests

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#4016]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Steps to reproduce

I noticed that NuxtserverInit and Middleware are being called on every  *.css.map request. 

Probably, to reprouduce one needs to   set  extractCSS: true,

### What is expected ?

NuxtserverInit should only be called on pages

### What is actually happening?

*.css.map requests should not hit middleware

### Additional comments?

This is causing a serious performance hit

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7871">#c7871</a>)</em></sub></div>

**Comment by aldarund** [comment]
Does it happen on production builds or only when run as dev?

**Comment by manniL** [comment]
Same here. A CSB would be nice :relaxed:

**Comment by pi0** [comment]
Actually, it is a known issue. We are working on [serve-placeholder](https://github.com/nuxt/serve-placeholder) to resolve this exact issue. Thanks for the report I've to add `*.map` placeholder support too. Will open PR soon. Expect it for `2.2.0` :)

**Comment by swunderlich** [comment]
`2.2.0` is out and I still have this issue in. For all `*.map` files. Any updates on this?

**Comment by manniL** [comment]
@swunderlich It's still in progress.

**Comment by aaldrin23** [comment]
Any updates here?
I'm stuck with this issue.
![image](https://user-images.githubusercontent.com/22129997/47965560-c2e62380-e083-11e8-81fb-aa52a6262b15.png)

**Comment by ben-richardson-moneysmart** [comment]
Are you sure the map file exists? I found in Chrome it will have a guess as to where the map files are. If the map file is not found, it will generate a 404 instead which the Nuxt server will serve as a normal page, going though the whole NuxtServerInit/middleware for the 404 page. If a 404 is encountered, then the request will not be shown in the Chrome dev tools, only successful `.map` requests are shown there. Once I have understood this, it all feels like completely normal behaviour. 

To test this, log out the context.route.path of the phantom requests. When the dev tools is open, I get an extra request for `path: '/_nuxt/rocketship_vue.common.js.map'`
