### ISSUE TITLE
generate --spa is broken when a base route is added

### ISSUE THREAD

**Issue by jpoo90** [nuxt/nuxt.js#4019]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/jpoo90/test-nuxt-spa](https://github.com/jpoo90/test-nuxt-spa)

### Steps to reproduce

- `yarn run broken:generate`
- surge dist/

Loading the pages throws an error.

### What is expected ?

The scripts in the generated HTML files should point to the appropriate URL so they can be loaded. 

### What is actually happening?

The script tags generated include the `router.base` path. 

The scripts are stored in `/dist/_nuxt/*.js` but the generated HTML files are trying to load them from `dist/router.base/_nuxt/*.js` 

This is part of the index.html generated

```html
// index.html 

<body>
  <script src="/app/_nuxt/d2a565b1646eab3ce4fb.js" type="text/javascript"></script>
  <script src="/app/_nuxt/00f02e33553c1edbc589.js" type="text/javascript"></script>
  <script src="/app/_nuxt/08991a4e7dbb7c0aec8b.js" type="text/javascript"></script>
</body>
```

```js
// nuxt.config.js

module.exports = {
        ...
        router: {
          base: '/app/',
        },
}
```

When the browser tries to load this, a 404 is returned because the files are not found. 

### Additional comments?

This is not happening when the `router.base` is not modified. If you run `yarn run generate` the file's tree is generated as expected. Let me know if I can clarify/help with anything. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7874">#c7874</a>)</em></sub></div>

**Comment by manniL** [comment]
Please don't run `generate` with `mode: spa`.

**Comment by husayt** [comment]
generate works fine with spa. What is the problem with that?

**Comment by jpoo90** [comment]
> Please don't run generate with mode: spa.

@manniL What's the reason for it ? 

@husayt did you see my example I have used generate with --spa before but for that scenario it didn't work

**Comment by husayt** [comment]
İ will try to help you, can you tell me why do you need /app route?

What is your static servera environment is? Where are you putting  files,
what is going to be root url?

**Comment by husayt** [comment]
That is the correct behaviour. Just rename the dist folder to "app" and place it in the root of your server. That should do it.

Also see this:
https://nuxtjs.org/faq/github-pages

Have a try and let us know, if still a problem. I will need to know your url and the path where the file is located which is supposed to load and also network tab screenshot from devtools.

**Comment by jpoo90** [comment]
Hey @husayt, I tried that and it worked! I updated the config to rename the output directory.
```js
//nuxt.config.js

...
generate: {
    dir: 'app'
  },
```

I wonder which of these options would be better for the community: 

1. The output dir could be renamed automatically.
1. Add documentation to explain that the output directory should be renamed.

**Comment by manniL** [comment]
I am very sorry for my wrong statements above.

`nuxt generate --spa` works the same as `nuxt build --spa` and will deliver an SPA, as expected.

More info: https://github.com/nuxt/nuxt.js/issues/4036#issuecomment-432018140
