### ISSUE TITLE
scrollBehavior not working on first time page load

### ISSUE THREAD

**Issue by flamner** [nuxt/nuxt.js#4024]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[http://swiatvelvet.pl/produkty/papier-toaletowy#line63](http://swiatvelvet.pl/produkty/papier-toaletowy#line63)

### Steps to reproduce

entry to the page from url with anchor link, for eg. myawesomesite.com/product#product_id

### What is expected ?

scroll to element with id = "product_id"

### What is actually happening?

nothing, page load as usual starting on top

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7878">#c7878</a>)</em></sub></div>

**Comment by flamner** [comment]
for now I fixed it by this 

https://stackoverflow.com/questions/45201014/how-to-handle-anchors-bookmarks-with-vue-router/45206192#45206192

**Comment by manniL** [comment]
@flamner What does your `scrollBehavior` look like?

**Comment by flamner** [comment]
@manniL like nuxt default
https://nuxtjs.org/api/configuration-router#scrollbehavior

**Comment by manniL** [comment]
@manniL Weird. I use hashes as well for my navigation on my own page (example: https://lichter.io/#skills) where it works quite well 🤔

**Comment by flamner** [comment]
@manniL You have spa or universal mode?

**Comment by manniL** [comment]
@flamner I use SSR/universal mode.

**Comment by flamner** [comment]
@manniL Ok, I checked it, no differences, my target elements are dynamically generated as a components, maybe there is a problem. I also load data asynchronously, and vue-router can't calculate right position. I have no idea what could be wrong :/

**Comment by manniL** [comment]
@flamner Could this related to https://github.com/nuxt/nuxt.js/issues/3471?

**Comment by flamner** [comment]
@manniL Yes, I have also this issue, this fix https://github.com/nuxt/nuxt.js/issues/3471#issuecomment-406158483 not working for me

**Comment by flamner** [comment]
@mogafk I tried that, no errors, no changes :/

**Comment by adrianoresende** [comment]
I have this bug too.

In first page, worked but after refresh don't work, and when you navigate to back to home or index, don't work too.

With `console.log` inside `scrollBehavior`, log don't is fired.

This is my code:
```
export function createRouter() {
  const router = new Router({
    mode: 'history',
    scrollBehavior(to) {
      console.log("-- scrollbehavior fired? --")
      if (to.hash) {
        return {
          selector: to.hash,
          offset: { x: 0, y: 40 },
        }
      }
    }
  })
  router.addRoutes( ... )
  return router;
}
```

**Comment by Cstrl** [comment]
Same problem here. Any updates?

**Comment by manniL** [comment]
All: can you try it with updated node modules (`npm update`/`yarn upgrade`)? Vue Router had released a new version.

**Comment by aaronransley** [comment]
Running into this same issue. Running Nuxt edge w/ up-to-date `yarn upgrade`. My anchor tags appear as the result of a component render, but the hash isn't honored after a hard reload w/ Cmd+R
