### ISSUE TITLE
NuxtServerError: Cannot stringify a function

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#4025]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/pimlie/nuxt-issues](https://github.com/pimlie/nuxt-issues)

### Steps to reproduce

clone repro & run yarn dev & browse to http://localhost:3000

### What is expected ?

A page that says hello is displayed

### What is actually happening?

An error 'NuxtServerError: Cannot stringify a function' occures

### Additional comments?

This is due to #3913, `serialize` could serialize functions but `devalue` cant. Although I can fix my project to not return a method, this is actually a breaking change.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7880">#c7880</a>)</em></sub></div>

**Comment by aldarund** [comment]
Where now used devalue, there was serialize with isJson which wasnt serializing functions, it was skipping them. And in store there should be only serializable data.

**Comment by pimlie** [comment]
This is not store, but asyncData. Anyway, will regard as a feature then ;)

**Comment by begueradj** [comment]
@pimlie So how did you fix this issue? I am facing the same one

**Comment by pimlie** [comment]
In my case I returned a closure function in asyncData, the solution was to just move that closure definition to data instead. (it was actually some configuration of a graph which had no real use there to begin with).
