### ISSUE TITLE
✖ fatal TypeError: Cannot read property 'minimize' of undefined

### ISSUE THREAD

**Issue by ptsans** [nuxt/nuxt.js#4032]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/ptsans/ptsans-nuxt-coffee](https://github.com/ptsans/ptsans-nuxt-coffee)

### Steps to reproduce

npm i
npm run build

### What is expected ?

Successful use of coffeescript in templates

### What is actually happening?

![Screenshot from 2018-10-02 19-56-14.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/e8776e20-c629-11e8-b9f9-ad3e244c7253.png)

### Additional comments?

If I remove the modules in nuxt.config.js, then
![Screenshot from 2018-10-02 19-58-37.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/dd29f280-c62a-11e8-b9f9-ad3e244c7253.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7884">#c7884</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce it with the [coffeescript-example](https://github.com/nuxt/nuxt.js/tree/dev/examples/coffeescript).

**Comment by manniL** [comment]
Using [the official coffescript module](https://github.com/nuxt/nuxt.js/blob/dev/examples/coffeescript/modules/coffeescript.js) instead of your implementation will work. Tested it with your repo and it builds successfully.

(I'd suggest to use the whole example as template though)
