### ISSUE TITLE
Nuxt generates bad paths in build/generate process

### ISSUE THREAD

**Issue by FilipJedrasik** [nuxt/nuxt.js#4033]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/FilipJedrasik/firebase-nuxt-quiz/tree/gh-pages](https://github.com/FilipJedrasik/firebase-nuxt-quiz/tree/gh-pages)

### Steps to reproduce

Clone repo and run npm run generate.
There you can preview generated pages in action:
https://filipjedrasik.github.io/firebase-nuxt-quiz/

### What is expected ?

Generate static files with proper paths that will work properly on gh-pages.

### What is actually happening?

First thing are bad paths in generated html files. For example:
/firebase-nuxt-quiz/staticmanifest.ab3ac000604ba888eee3.js
Should be:
/firebase-nuxt-quiz/static/manifest.ab3ac000604ba888eee3.js

This problem occurs few times. I changed it manually to proper in each .html file in hope it will work. Unfortunelly, it seems like there are some bad paths in generated js file. 

### Additional comments?

I tried to push dist either from nuxt build or nuxt generate. Both don't work.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7886">#c7886</a>)</em></sub></div>

**Comment by manniL** [comment]
Please follow the [Github Page Deployment tutorial](https://nuxtjs.org/faq/github-pages/) to properly set up your nuxt app with GH pages :relaxed:

**Comment by FilipJedrasik** [comment]
Ahhhh right I didn't update master branch(only gh-pages branch). However I set router base properly. For sure I've just pushed commit. How to fix it?

**Comment by manniL** [comment]
@FilipJedrasik You are missing a trailing slash in your public path. (`/static/` -> `/static/`)
