### ISSUE TITLE
Throw an error when `layout` is no string or fn

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4035]
### What problem does this feature solve?

The `layout` property should only allow strings and function. If you set the layout to an `array` (for example), no error is shown. Only a Warning (coming from Vue directly): 

```
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

(found in <Root>)
```

A decent error message would be great to see here!

To get started, the source code for setting and evaluating the layout is [here](https://github.com/nuxt/nuxt.js/blob/dev/lib/app/App.js#L82)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7888">#c7888</a>)</em></sub></div>

**Comment by KCN8** [comment]
I think I might be able to help out on this one.

**Comment by manniL** [comment]
@KCN8 Please do so! ☺️ 
Looking forward to the PR :)

If you have questions, feel free to drop a message in the Discord or in your PR. Our Contribution Guide can be found [here](https://nuxtjs.org/guide/contribution-guide#reporting-issues)

**Comment by suusan2go** [comment]
Can I take this ?
