### ISSUE TITLE
Throw a warning when using generate with `mode: spa`

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4036]
### What problem does this feature solve?

Using generate with `mode: spa` isn't supported. A~n error~ warning should be thrown in this case to avoid issues.

Related: #4019 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7889">#c7889</a>)</em></sub></div>

**Comment by husayt** [comment]
@manniL did you mean mode: universal? SPA works fine with generate

**Comment by manniL** [comment]
Hey @husayt! 👋 
No, I mean SPA mode. It can produce strange/unexpected results (depending on the setup) when used with `generate`.

**Comment by husayt** [comment]
Strange. I am using that mode extensively and it works very well for me.
Yes, it is very delicate and  took me some time to understand. But it works
and is quite configurable. Obviously generated SPA, has it's limitations,
but that is also its features.

I wouldn't put a notice that it's buggy, to not to discourage people.
Instead, let's try to understand what is wrong they are doing and clarify
its limitations.

**Comment by manniL** [comment]
@husayt Looking into it is definitely not a bad idea, however, showing a warning (similar to "Proceed with caution/on your own risk" 🙈) is important to make clear it's not tested/supported at the moment.

**Comment by manniL** [comment]
There was a misunderstanding here.

`generate --spa` actually does the same as `build --spa` and works "as expected". That's not documented anywhere yet (but will be soon!)
