### ISSUE TITLE
Tree Shaking with any CSS libs - Which way better?

### ISSUE THREAD

**Issue by AdsonCicilioti** [nuxt/nuxt.js#4037]
### What problem does this feature solve?

In SSR development scenario with a CSS library such as Bootstrap or Bulma, where the CSS of various unused components are embedded in the code, what is the best way to configure a tree Shaking solution for the CSS of all pages?
(including for contents and components that will be post loaded)

Forgive my humble lack of knowledge in JS. Because I am a Designer trying to expand horizons and trying to collaborate with the more optimized development flow.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7890">#c7890</a>)</em></sub></div>

**Comment by manniL** [comment]
There is no such thing as *tree shaking* for CSS. What you can do though is **remove unused CSS** in a more simple manner with [`PurgeCss`](https://github.com/FullHuman/purgecss)
