### ISSUE TITLE
terser-webpack-plugin option extend?

### ISSUE THREAD

**Issue by ac88** [nuxt/nuxt.js#4039]
### What problem does this feature solve?

i want to set terser https://github.com/terser-js/terser#compress-options 

drop_console

at nuxt@1.4.2  can set option.uglify

https://github.com/nuxt/nuxt.js/blob/376dd35ba9465e1163a800bd0512654f68436b5f/lib/builder/webpack/client.config.js#L187-L205

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7892">#c7892</a>)</em></sub></div>

**Comment by pi0** [comment]
This is possible with nuxt [2.1.0](https://github.com/nuxt/nuxt.js/releases/tag/v2.1.0) via #4018.

Please refer to the docs: https://nuxtjs.org/api/configuration-build#terser
