### ISSUE TITLE
nuxt fetch and middleware life cycle

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#404]
Does the middleware or fetch run first when entering into a route? It currently appears to fire asynchronously. 

Scenario
1. I have a page route that uses fetch to populate a store. 
2. I have a middleware that uses store state to determine access to the page route

Result currently is that the store state is not populated in time for the middleware to work.

**Comment by Atinux** [comment]
Hi @uptownhr 

The middleware are called before every route, it's like express middleware.

See this schema:

![nuxt-schema](https://cloud.githubusercontent.com/assets/904724/24108683/9898149a-0d8e-11e7-939d-0ceec011593e.png)

You can use `nuxtServerInit` to fill the store for some initial data, or you can use the `context.redirect` method in `fetch` of your page to add some logic for a specific page.
