### ISSUE TITLE
[nuxt] Error while initializing app TypeError: "fs$ReadStream is undefined"

### ISSUE THREAD

**Issue by hichamelkaddioui** [nuxt/nuxt.js#4040]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/hichamelkaddioui/nuxt-fs-bug-report](https://github.com/hichamelkaddioui/nuxt-fs-bug-report)

### Steps to reproduce

1. Clone https://github.com/hichamelkaddioui/nuxt-fs-bug-report
2. Run `npm install`
3. Run `npm start` and visit [http://localhost:3000](http://localhost:3000)
4. Open browser's console

### What is expected ?

No error with packages using `fs`

### What is actually happening?

Console error `[nuxt] Error while initializing app TypeError: "fs$ReadStream is undefined"` (see screenshot)
![Capture d’écran de 2018-10-03 15-14-54.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/773b3a80-c70e-11e8-89a1-fbc5e3f63575.png)

### Additional comments?

Repo is just a minimal nuxt app trying to use `fs-extra`. To first make `fs` work with nuxt, I added extra configuration as mentioned in [#1485](https://github.com/nuxt/nuxt.js/issues/1485).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7897">#c7897</a>)</em></sub></div>

**Comment by aldarund** [comment]
I dont think fs-extra supposed to work in browser, so the error is valid

**Comment by hichamelkaddioui** [comment]
> I dont think fs-extra supposed to work in browser, so the error is valid

True, no `fs` library is supposed to. I realized that what I wanted perform was server-side, not client-side.

I just wrapped my code like so:
```javascript
if (process.server) {
   // do fs stuff
}
```
