### ISSUE TITLE
"this" returns undefined when store module mode is splitted into files

### ISSUE THREAD

**Issue by jericopulvera** [nuxt/nuxt.js#4047]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/myr2r24q28](https://codesandbox.io/s/myr2r24q28)

### Steps to reproduce

check console output

[![Edit codesandbox-nuxt](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/14o4ko6494)

### What is expected ?

can access "this" object on store module files mode.

### What is actually happening?

"this" object returns undefined on module files mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7904">#c7904</a>)</em></sub></div>

**Comment by galvez** [comment]
@jeehyukwon you're using an arrow function -- where `this` is only lexically available. See [this article](https://hackernoon.com/javascript-es6-arrow-functions-and-lexical-this-f2a3e2a5e8c4) for a comprehensive explanation. Change `chat/actions.js` to:

```
export const test = async function({ getters, commit }) {
  console.log("multiple", this);
};
```
And it should work as expected.

**Comment by jericopulvera** [comment]
@galvez thank you! it works as you expected.

Do you think that this should be documented on https://nuxtjs.org/guide/vuex-store/ guide?

**Comment by galvez** [comment]
@jericopulvera yeah I'll reopen and keep it open until one of us adds a note about it.

**Comment by manniL** [comment]
Closed in favor of https://github.com/nuxt/docs/issues/849 ☺️
