### ISSUE TITLE
Head meta title is not loaded

### ISSUE THREAD

**Issue by man-andy** [nuxt/nuxt.js#4052]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues/3300](https://github.com/nuxt/nuxt.js/issues/3300)

### Steps to reproduce

As mentioned in https://github.com/nuxt/nuxt.js/issues/3300
When visiting the page the first time, the meta title is not loaded. After a refresh the title is loaded.

### What is expected ?

meta title should be loaded on first visit

### What is actually happening?

The meta title is not loaded on first visit.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7908">#c7908</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @man-andy! Could you add a reproduction repo or CodeSandBox please?

**Comment by ruslankonev** [comment]
I am for today have the same issue on v.1.4, but community not fix that.
Now I test a production site on v2, and then we'll see how vue-meta works.

**Comment by rafaelmagalhaes** [comment]
I installed vue-meta version is 1.5.5  and it's working fine with nuxt ,both title and description all show on the first load

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
