### ISSUE TITLE
NUXT Store index.js cookie problem

### ISSUE THREAD

**Issue by monkhsaikhan** [nuxt/nuxt.js#4066]
In store/index.js file, I call nuxtServerInit function in actoins like this. 
```
nuxtServerInit({ commit }, { req }) {       
    let auth = null    
    if(req) {      
      if (req.headers && req.headers.cookie) {
        const parsed = cookieparser.parse(req.headers.cookie)
        try {
          auth = JSON.parse(parsed.auth)
        } catch (err) {
          // No valid cookie found
        }
      } 
    }    
    commit('SET_USER', auth)
  },
```

it's working perfect on dev mode. Then I run `npm run generate` command for deployment. It's not working on browser. Because `req` is undefined. How to fix this problem. 

My login function store auth data on cookie like this.

```
async login({ commit }, { email, password }) {
    try {
      const { data } = await axios.post('/login', { email, password })
      commit('SET_USER', data);
      Cookie.set('auth', data);
      return true;
    } catch (error) {
      if (error.response && (error.response.status === 401 || error.response.status === 403)) {
        throw new Error('Bad credentials')
      }
      throw error
    }
},
```

PLEASE HELP ME!!!

**Comment by aldarund** [comment]
You need to use Universal mode, not generate. In generate nuxtServerInit only run once during generate and thats all.

**Comment by monkhsaikhan** [comment]
> You need to use Universal mode, not generate. In generate nuxtServerInit only run once during generate and thats all.

i use universal mode

**Comment by aldarund** [comment]
>Then I run npm run generate

Generate not universal mode. Generate will generate static pages once. And nuxtServerInit will only be run once during generate and there wont be any request or anything.
universal mode is when u deploying your app on node. 
E.g. npm run build, npm run start

**Comment by monkhsaikhan** [comment]
> > Then I run npm run generate
> 
> Generate not universal mode. Generate will generate static pages once. And nuxtServerInit will only be run once during generate and there wont be any request or anything.
> universal mode is when u deploying your app on node.
> E.g. npm run build, npm run start

How to get Cookie on static page. I want store auth data to cookie then i use anyware.

**Comment by aldarund** [comment]
using any cookie library like vue-cookie

**Comment by Lahori-Jawan** [comment]
@aldarund could you help me [here](https://cmty.app/nuxt/nuxt.js/issues/c7922)
