### ISSUE TITLE
The configured head.script.innerHTML is escaped

### ISSUE THREAD

**Issue by xuexb** [nuxt/nuxt.js#4070]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/7432lomjpx](https://codesandbox.io/s/7432lomjpx)

### Steps to reproduce

nuxt.config.js

```js
module.exports = {
    mode: 'universal',

    /*
     ** Headers of the page
     */
    head: {
        script: [
            { innerHTML: 'document.documentElement.classList.add("theme-" + (localStorage.theme || "day"))' },
        ],
    },
    ....
}
```

### What is expected ?

`'` and `"` are displayed correctly

### What is actually happening?

```html
<script data-n-head="true" >document.documentElement.classList.add(&quot;theme-&quot; + (localStorage.theme || &quot;day&quot;))</script>
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7936">#c7936</a>)</em></sub></div>

**Comment by manniL** [comment]
This is an intended feature of `vue-meta`. You can disable it as well if you want. More information in the [vue-meta docs](https://github.com/declandewet/vue-meta#__dangerouslydisablesanitizers-string). In-production example [here](https://github.com/manniL/lichter.io/blob/master/nuxt.config.js#L21)

**Comment by yugasun** [comment]
@xuexb When you want to inject script into template by parameter `head.script` in `nuxt.config.js`, and add `__dangerouslyDisableSanitizers: ['script'],` can solve your problem. But, I think [customizing your template](https://nuxtjs.org/guide/views#document) is a better method. After you do this, you can write any script you want in your HTML document. 
Relative issue https://github.com/nuxt/nuxt.js/issues/2230
