### ISSUE TITLE
Vue jsx v-model fails after upgrading 2.X

### ISSUE THREAD

**Issue by roywuyy** [nuxt/nuxt.js#4075]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/roywuyy/nuxt-test-vue-jsx-v-model/blob/master/pages/test.vue](https://github.com/roywuyy/nuxt-test-vue-jsx-v-model/blob/master/pages/test.vue)

### Steps to reproduce

Install nuxt-test-vue-jsx-v-mode and switch between my master (Nuxt 2.1) and nuxt-142 (Nuxt 1.4.2) branch to see the error.

### What is expected ?

Vue jsx v-model works fine Or is there any temporary solution?

### What is actually happening?

In 2.1.0 v-model is invalid and there is no error.
![1539156115.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2ed620d0-cc5d-11e8-b351-4bd2f9e3656f.jpg)

### Additional comments?

No problem in 1.4.2
![WYHAQP6S(BEU4Z~6DF_[BYC.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/7a2d27b0-cc5b-11e8-b351-4bd2f9e3656f.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7939">#c7939</a>)</em></sub></div>

**Comment by aldarund** [comment]
babel jsx v-model plugin dont work for babel 7.
https://github.com/nickmessing/babel-plugin-jsx-v-model/issues/11

**Comment by roywuyy** [comment]
Okay, thank you. Temporarily use the method of temporary resolution.
