### ISSUE TITLE
Using a component with dynamic DOM element doesn't resolve 'to' automatically and causes the build to fail

### ISSUE THREAD

**Issue by warrebuysse** [nuxt/nuxt.js#4078]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/v8w5qpnk30](https://codesandbox.io/s/v8w5qpnk30)

### Steps to reproduce

None, just see the reproduction link

### What is expected ?

When I pass "nuxt-link" as a tag-name prop, the "to" property should automatically passed to the parent element (like a "href" prop or any other standard attribute) 

### What is actually happening?

The "to" property is not passed to the component, which makes the build fail.

### Additional comments?

Is it possible to fix this without having to set the "to" property in every component when the element is clickable?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7940">#c7940</a>)</em></sub></div>

**Comment by manniL** [comment]
Adding more "hidden behavior" as automatically/implicitly passing props isn't helpful IMO.

With a functional component this is doable in a few lines.

```js
export default {
  name: "doormat",
  functional: true,
  render(h, { props, data, children }) {
    props.tagName = props.tagName || "span";
    data = { ...data, props };
    return h(props.tagName, data, children);
  }
};

```

Example: https://codesandbox.io/s/n7jz3357k0 (`/about`)

**Comment by clarkdo** [comment]
The reason of the error is router-link doesn't receive `to` prop, you can try add `to` on it:

```vue
<template>
  <component 
    :is="tagName" :to='to'>
    <slot />
  </component>
</template>
```

@manniL is correct, in this case, use function render is a better idea.

**Comment by warrebuysse** [comment]
@manniL @clarkdo  I agree it shouldn't work with every attribute, but when working in a Nuxt environment I expect to have support for basic Nuxt bindings like the props for a nuxt-link. 

What is presented above forces me to change every component that can potentially have a nuxt-link. We are building a Vue Design System where there are, as we speak, roughly 50 components that can be used as a navigational component. 

We still have the luxury to be able to change our component, so the above is an option, but what if you work with a Buefy framework or Vue Material?

**Comment by manniL** [comment]
This shouldn't be a Nuxt issue at all:

```js
<doormat tag-name="router-link" to="'/a'">
  I'm a clickable doormat
</doormat>
```

wouldn't work either. (Also, `nuxt-link` is just a "proxy" to `router-link` at the moment)

I see your use case and that it'd come in handy but it's not the way to go for the majority of the projects.
I'm sure you'll find a nice abstraction for it!

**Comment by clarkdo** [comment]
If we don't pass `props (here is 'to')` to dynamic `component`, it cannot know what's the exact value, so it's not Vue or Nuxt issue, it's something like:

```js
let realName
const setRealName = name => {
  realName = name
}
const setName = name => {
    setRealName() // notice here
}

setName('path')
```
If you don't pass parameter to `setRealName`, it cannot get the value.

Hop you can understand my explanation. 😄
