### ISSUE TITLE
External Resources: Load local js file. (eg. Service Worker.js)

### ISSUE THREAD

**Issue by tenjojeremy** [nuxt/nuxt.js#408]
Hello,

I add script: [{
src: 'sw.js'
}]
in the nuxt.config file under head, but i get a 404.

Please help.

**Comment by PierreRambaud** [comment]
Hi,

Can you tell us more ? Where this file is located?

Regards

**Comment by tenjojeremy** [comment]
@PierreRambaud Hello,

I set up with the nuxt-express template.

I am registering the Service worker in the default.vue file. I also created the sw.js file and placed it in the root directory:
Setup:

![example](https://cloud.githubusercontent.com/assets/25231946/24085298/b7d3ec5e-0ccf-11e7-89c9-32a4591d4d7f.PNG)
 
I get this error Error:

![error](https://cloud.githubusercontent.com/assets/25231946/24085313/fc1eb394-0ccf-11e7-8d4f-558ad7c0d816.PNG)

Thank you for your quick response.

**Comment by PierreRambaud** [comment]
Look like you look for the front path.
You must put your frontend scripts into `static` or `assets `directories ;)

### The Static Directory
The static directory contains your static files. Each files inside this directory is mapped to /.
Example: `/static/robots.txt` is mapped as `/robots.txt`
This directory can not be renamed.
[More documentation about Static integration](https://nuxtjs.org/guide/assets#static)

**Comment by tenjojeremy** [comment]
@PierreRambaud 

Thank you so much for your help.

Have a great day!
