### ISSUE TITLE
page does not scrollToTop on route change if the layout is also changing

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#4080]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/o90qv0xl16](https://codesandbox.io/s/o90qv0xl16)

### Steps to reproduce

1. Go to repo link. 
2. Scroll all the way down and click on link. 
3. Notice you are on a new page but at the bottom of the page

### What is expected ?

Should be at the top of the page

### What is actually happening?

You are at the bottom of the page

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7941">#c7941</a>)</em></sub></div>

**Comment by davision** [comment]
Uh, this is a bug since v1. Sad it hasn't been fixed until the recent day..

**Comment by rason560** [comment]
Same to me,  and `scrollToTop: true` is not work too .  the bug sitll exit in nuxt@2.2

**Comment by davision** [comment]
It's a persistent bug. Will probably here for ever ;)

**Comment by mitchellst** [comment]
For folks off google, because i've landed on these issues a few times. My fix is to install [vue-scrollto](https://www.npmjs.com/package/vue-scrollto), then in the page component:
```
mounted(){
      if(process.client){
          this.$scrollTo('#__nuxt', 0, {force: true})
      }
  }
```

**Comment by davision** [comment]
I'm fixing it same way. Which is quite an unpretty hack. But it would need to do.

**Comment by manniL** [comment]
All: can you try it with updated node modules (`npm update`/`yarn upgrade`)? Vue Router had released a new version.

**Comment by davision** [comment]
Finally! Thanks, @pi0!
