### ISSUE TITLE
shouldPrefetch, shouldPreload, regression - missing file names

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#4092]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[not necessary](not necessary)

### Steps to reproduce

add to ```nuxt.config.js```:
```js
render: {
    bundleRenderer: {
      shouldPrefetch: (file, type) => {
        console.log('shouldPrefetch', file, type)
        return true
      },
      shouldPreload: (file, type) => {
        console.log('shouldPreload', file, type)
        return true
      }
    }
  },
```

### What is expected ?

Expected filenames, like in version 1.4

### What is actually happening?

Instead of filenames we get hashcodes. It is not possible to decide what to prefetch/preload.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7953">#c7953</a>)</em></sub></div>

**Comment by manniL** [comment]
This is related to the change to `webpack4`. You can use `build.splitChunks.name` to re-enable names. ([nuxt-docs](https://nuxtjs.org/api/configuration-build#optimization), [webpack-docs](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-name))

Also, the file name structure has been changed a little ([docs](https://nuxtjs.org/api/configuration-build#filenames)). You can adapt it as well to your needs.
