### ISSUE TITLE
Show a warning if extractCSS.allChunks is set

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4094]
### What problem does this feature solve?

Since v2.0.0, `extractCSS` isn't responsible for extracting CSS in **one file**. This was possible before by using `extractCSS: { allChunks: true }`. Now, it has to be done through webpacks `splitChunk` settings.

To make users aware of that we should give them a proper warning if it is still set.

Documenting how to leverage single file css extraction again would be nice too: https://github.com/nuxt/docs/issues/856

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7956">#c7956</a>)</em></sub></div>

**Comment by jamsch** [comment]
I came across this issue too and spent a few hours trying to pinpoint the exact cause. Setting `options.build.parallel: true` with allChunks enabled causes the error: `Cannot read property 'outputOptions' of undefined`
