### ISSUE TITLE
nuxt.i18n: translations do not work using nested roots

### ISSUE THREAD

**Issue by begueradj** [nuxt/nuxt.js#4095]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/begueradj/nuxti18n-with-nested-routes](https://github.com/begueradj/nuxti18n-with-nested-routes)

### Steps to reproduce

Clone my repo and follow the simple steps in the README file

### What is expected ?

I want to launch the server ẁith  `yarn run dev`,  I type on the browser: `http://localhost:3000/1`  and then I click on **Francais**  to see my text translated.

### What is actually happening?

When I launch the server ẁith  `yarn run dev`, and I type on the browser: `http://localhost:3000/1` I click on **Francais** but the text does not get translated at all. 

When I refresh the page, the translation works. But I do not want the user to refresh the page to see the translations working. The translations should work on a simple click.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7957">#c7957</a>)</em></sub></div>

**Comment by manniL** [comment]
Please report it to nuxt-i18n :relaxed: https://cmty.app/nuxt/issues/new?type=bug-report&repo=nuxt-i18n
