### ISSUE TITLE
how to set offline-plugins 

### ISSUE THREAD

**Issue by fxh615** [nuxt/nuxt.js#410]
how to set offline-plugins sometime have the error Module not found: Error: Can't resolve 'fs'

**Comment by Atinux** [comment]
@rohitpal99 might help you on this.

Actually, we don't really supports offline-plugins but it's planned soon https://github.com/nuxt/nuxt.js/pull/372

**Comment by fxh615** [comment]
@Atinux thanks , its a very import function for us
