### ISSUE TITLE
Nuxt support for named views for extendRoutes config

### ISSUE THREAD

**Issue by hashinteractive** [nuxt/nuxt.js#4100]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/jvjm62ll5v](https://codesandbox.io/s/jvjm62ll5v)

### Steps to reproduce

extend route in nuxt.config.js

```
router: {
    extendRoutes (routes, resolve) {
      let index = routes.findIndex(route => route.path == '/')
      const children = [{
        path: 'sidebar',
        components: {
          default: resolve(__dirname, 'components/Sidebar.vue'),
          two: resolve(__dirname, 'components/SidebarTwo.vue')
        }
      }]

      routes[index]['children'] = children 
      console.log(util.inspect(routes, false, null))
    } 
  },
```

add two components:
`/components/Sidebar.vue`
```
<template>
  <div>
    <h3>Sidebar Default</h3>
  </div>
</template>
<script>
```
`/components/SidebarTwo.vue`
```
<template>
  <div>
    <h3>Sidebar Two</h3>
  </div>
</template>
```

Add `<router-view />` and `<router-view name="two" />` to index.vue

```
<template>
  <section class="container">
    <div>
      <h1 class="title">
        Homepage
      </h1>
      <h2 class="subtitle">
        My top-notch Nuxt.js project
      </h2>
      <nuxt-link to="/">Home</nuxt-link>
      <nuxt-link to="/sidebar">Sidebar</nuxt-link>
      <router-view /> 
      <router-view name="two" /> 
    </div>
  </section>
</template>
```

### What is expected ?

When you go to `/sidebar` route it should render both the default `<router-view />` and the named view `<router-view name="two" />`

### What is actually happening?

Cannot read property 'options' of undefined
An error occurred while rendering the page. Check developer tools console for details.

`_nuxt/app.js`
line: 2159

```
if (to.matched.length < 2) {
    // scroll to the top of the page
    position = {
      x: 0,
      y: 0
    };
  } else if (to.matched.some(function (r) {
    return r.components.default.options.scrollToTop;
  })) {
    // if one of the children has scrollToTop option set to true
    position = {
      x: 0,
      y: 0
    };
  } // savedPosition is only available for popstate navigations (back button)
```

### Additional comments?

Can't register named views in extendRoutes in nuxt.config with `components: {}` property only can register children using `component` property

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7958">#c7958</a>)</em></sub></div>

**Comment by hashinteractive** [comment]
Does anyone have any idea on how this implementation would be possible?

**Comment by karakum** [comment]
Have the same problem. Need support of named views in nuxt

**Comment by karakum** [comment]
I've got a workaround by custom template of router.js. Try to make PR..

**Comment by karakum** [comment]
@manniL PR linked!

**Comment by karakum** [comment]
@manniL new PR in dev branch + example added
