### ISSUE TITLE
Can not override environment variables when nuxt start

### ISSUE THREAD

**Issue by axetroy** [nuxt/nuxt.js#4103]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://no.example.com](https://no.example.com)

### Steps to reproduce

```js
// nuxt.config.js
export default {
  env: {
    baseUrl: process.env.BASE_URL || 'http://localhost:3000'
  }
}
```

and I run

```bash
nuxt build

BASE_URL=http://example.com nuxt start
```

### What is expected ?

``process.env.BASE_URL`` in ``client-side`` and ``server-side`` should be ``http://example.com``

### What is actually happening?

``server-side``: http://example.com
``client-side``: http://localhost:3000

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7962">#c7962</a>)</em></sub></div>

**Comment by manniL** [comment]
Please add a CodeSandBox for reproduction: http://template.nuxt.xyz/

**Comment by manniL** [comment]
Solution as explained in comment above: https://codesandbox.io/s/3174k047lp

**Comment by axetroy** [comment]
@manniL 

Thanks for you reply.

But this does not seem to solve my problem.

I have create an repo for this [https://github.com/axetroy/nuxt-env-bug](https://github.com/axetroy/nuxt-env-bug) with forllow command:

```bash
npx create-nuxt-app nuxt-env-bug
...
cd nuxt-env-bug
```

### 1. Edit ``nuxt.config.js``

```
// nuxt.config.js
export default {
  env: {
    API_HOST: process.env.API_HOST || 'http://example.com'
  }
}
```

### 2. Edit ``index.vue``

```vue

<template>
      <h3>
        Current API_HOST {{API_HOST}}
      </h3>
</template>

<script>
export default {
  data () {
    return {
      API_HOST: process.env.API_HOST
    }
  }
}
</script>
```

### 3. Run ``npm run dev``

Show the page 

> Current API_HOST http://example.com

- [x] Is it consistent with expectations?

### 4. Run ``npm run build``

### 5. Run ``npm start``

Show the page 

> Current API_HOST http://example.com

- [x] Is it consistent with expectations?

### 6. Run ``API_HOST=http://my_api.com npm start``

Show the page 

> Current API_HOST http://example.com

- [ ] Is it consistent with expectations?

### Result

It seems that the environment variable depends on the state of the ``nuxt build``, not the ``nuxt start``.

**Comment by manniL** [comment]
By default, all variables have to be set on `build time`. https://github.com/nuxt/nuxt.js/issues/1983. This is **intended**.

There are some workarounds though :thinking: 
https://github.com/nuxt/nuxt.js/issues/2689
