### ISSUE TITLE
Use JSON.stringify when devalue fails

### ISSUE THREAD

**Issue by yukipastelcat** [nuxt/nuxt.js#4105]
### What problem does this feature solve?

JSON.stringify can stringify user classes, while devalue can work only with POJO-s. This can be useful when you want to have an object in your Vuex store, that extends some class, for example:
```
class Item {
    constructor({ id, name }) {
        this.id = id;
        this.name = name;
    }
}

class ItemWithPrice extends Item {
    constructor({ price }) {
        super(...arguments);
        this.price = price;
    }
}
```
And then in fetch:
```
fetch({ store }) {
    let responseData = { id: 1, name: 'Item', price: 12 };
    store.commit('UPDATE_ITEM_WITH_PRICE', responseData);
}
```
And then in store:
```
export const state = () => ({
    itemWithPrice: null
})

export const mutations = {
    UPDATE_ITEM_WITH_PRICE(state, data) {
        state.itemWithPrice = new ItemWithPrice(data)
    }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7964">#c7964</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @yukipastelcat 👋 

This is already handled in https://github.com/nuxt/nuxt.js/pull/4046 (no error anymore).

**Comment by manniL** [comment]
Release will come soon™️. Latest `nuxt-edge` has it already included.
