### ISSUE TITLE
Deprecate process.browser

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4106]
### What problem does this feature solve?

After https://github.com/nuxt/nuxt.js/pull/3910 it'd be convenient to deprecate process.browser and to display a warning on usage (but evaluate it correctly anyway).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7965">#c7965</a>)</em></sub></div>

**Comment by destag** [comment]
Can I  take this one?

**Comment by manniL** [comment]
@destag Sure, go on ☺️
