### ISSUE TITLE
Add HardSourceWebpackPlugin

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4107]
### What problem does this feature solve?

Might be worth a try to improve speed/DX: https://github.com/mzgoddard/hard-source-webpack-plugin

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7966">#c7966</a>)</em></sub></div>

**Comment by aldarund** [comment]
A few points it dont work with latest webpack right now
And afaik it will be implemented in webpack 5 internally
https://github.com/mzgoddard/hard-source-webpack-plugin/pull/444
https://github.com/webpack/webpack/issues/8052

**Comment by benfavre** [comment]
I mean man, I had it working for a few weeks right before 4.19.1 ... now I have to wait 40 secs for every new compile, so sad.

**Comment by manniL** [comment]
@benfavre We have to wait for mzgoddard/hard-source-webpack-plugin#444 or Webpack 5 🤷‍♂️

**Comment by Legym** [comment]
Just want to bring up that mzgoddard/hard-source-webpack-plugin#444 has been merged

**Comment by benfavre** [comment]
I believe in humanity again thanks
