### ISSUE TITLE
Nuxt deployment on server

### ISSUE THREAD

**Issue by aebrs** [nuxt/nuxt.js#4113]
### What problem does this feature solve?

0
down vote
favorite
I want to deploy my nuxt.js project on a windows server, plesk shared web host.

I have done the following steps:

I have build project using 'node_modules/nuxt/bin/nuxt-start'
copy .next folder to httpdocs folder in server
copy 'nuxt.config.js' to httpdocs folder
copy 'package.json' to httpdocs folder
deleted web.config file
In the field Application Startup File you have to put node_modules/nuxt/bin/nuxt-start
installed npm packeges on server
but it does not run on the server and I get the following error:

This site can’t be reached

what is wrong?

What are the correct steps to deploy nuxt project on plesk?

Thank you

### What does the proposed changes look like?

what is wrong?

What are the correct steps to deploy nuxt project on plesk?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7970">#c7970</a>)</em></sub></div>

**Comment by manniL** [comment]
This is no feature request but a question. Furthermore, it's hard to answer without a system to reproduce. 

As you have already posted [your question on StackOverflow](https://stackoverflow.com/questions/52702279/deploy-nuxt-js-project-on-plesk-web-host), I hope you'll find an answer there.
