### ISSUE TITLE
Enable Vue-Test-Utils to work with Nuxt

### ISSUE THREAD

**Issue by ChrisDillinger** [nuxt/nuxt.js#4115]
### What problem does this feature solve?

I cannot find a working solution that let's me use ava or jest to run unit tests that utilize the Vue Test Utils library. Given that both Vue Test Utils and Nuxt appear to hold strong positions within the Vue community, I think it makes sense to ensure that Vue Test Utils can be utilized for both Nuxt universal and Nuxt SPAs

### What does the proposed changes look like?

Nuxt should seamlessly let developers run tests with runners like jest or ava while using Vue-test-utils as well as modern ES features (import statements). Importing .vue SFCs from your test files would work fine, using the import statement would work fine, and utilizing Vue Test Util features like shallowMount would work fine.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7972">#c7972</a>)</em></sub></div>

**Comment by paulgv** [comment]
What have you tried this far? I've been using VTU inside Nuxt projects for a while now.

Here are some code sample you might find useful for your setup:

## .babelrc

```
{
  "env": {
    "test": {
      "presets": ["env", "vue-app"]
    }
  }
}
```

## package.json

```json
{
  "jest": {
    "setupFiles": [
      "<rootDir>/tests/unit/jest.setup.js"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "vue"
    ],
    "moduleNameMapper": {
      "^~/(.*)$": "<rootDir>/client/$1",
      "^~~/(.*)$": "<rootDir>/$1"
    },
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest"
    },
    "snapshotSerializers": [
      "<rootDir>/node_modules/jest-serializer-vue"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "client/components/**/*.vue"
    ]
  },
}
```

## tests/unit/jest.setup.js

```js
import Vue from 'vue';
import VueTestUtils from '@vue/test-utils';

Vue.config.silent = true;

// Mock Nuxt components
VueTestUtils.config.stubs['nuxt-link'] = '<a><slot /></a>';
VueTestUtils.config.stubs['no-ssr'] = '<span><slot /></span>';
```

**Comment by manniL** [comment]
A test example in `/examples` with Jest would be neat! :thinking:

**Comment by ChrisDillinger** [comment]
Ah, I tried using babel-jest and vue-jest transformers during my very first attempt. I need to go back and see if I can get that setup working.

However, in the mean time, I did get an ava + nuxt + vue-test-utils exemplar working: https://github.com/ChrisDillinger/vue2-nuxt-exemplar

**Comment by ChrisDillinger** [comment]
@paulgv Would you be willing to share a repo link with the minimally necessary setup for Nuxt (Universal or SPA) + Jest + Vue Test Utils?

**Comment by paulgv** [comment]
@ChrisDillinger sure, working on it now, I'll make a PR to add it as an example @manniL.

**Comment by aldarund** [comment]
There is also downside. Nuxt specific stuff like fetch/asyncData/middleware wont work

**Comment by paulgv** [comment]
@aldarund True, I actually only test components with VTU usually. Maybe the `index.spec.js` in the PR is confusing and should be removed?

**Comment by manniL** [comment]
Well, you can test asyncData and fetch (separately) with VTU. The functions are available in the `$options` of the component.
