### ISSUE TITLE
Code coverage broken for Nuxt.js modules

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4119]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://codesandbox.io/s/github/nuxt-community/separate-env-module/](https://codesandbox.io/s/github/nuxt-community/separate-env-module/)

### Steps to reproduce

1. Run yarn test
2. See coverage is "unknown"

### What is expected?

Coverage

### What is actually happening?

No coverage

### Additional comments?

All modules that test against `nuxt-edge` (after Nuxt 2 release) or `nuxt` are affected. For example:

* https://github.com/nuxt-community/separate-env-module/
* https://github.com/nuxt-community/nuxt-i18n
* https://github.com/nuxt-community/feed-module

**UPDATE**: Blocked by https://github.com/standard-things/esm/issues/97#issuecomment-427551714

The reason (thanks to @pi0 for explaining to me) is that you don't have an option to tell the coverage tool (instabul/Instrumenter) that ESM syntax is used because Jest doesn't support an `esm` integration (which we use in Nuxt 2).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7975">#c7975</a>)</em></sub></div>

**Comment by manniL** [comment]
Not stale.

**Comment by ricardogobbosouza** [comment]
@manniL  Can we close this now?

**Comment by manniL** [comment]
@ricardogobbosouza yes! (Next time, please add sth. like "Resolves #4956" to the PR 🙊 GH will close it automatically then)
