### ISSUE TITLE
get component options in server side context

### ISSUE THREAD

**Issue by axetroy** [nuxt/nuxt.js#4123]
### What problem does this feature solve?

sometimes, we need to define properties in the component options.

It should useful to share in client-side and server-side

### What does the proposed changes look like?

```vue
<script>
// pages/index.vue
export default {
  title: 'Home Page Title',
  data () {
    // support
    console.log(this.$options.title)
  },
  asyncData ({$options}) {
    // not support
    console.log($options.title)
  },
  fetch ({$options}) {
    // not support
    console.log($options.title)
  }
}
</script>
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7979">#c7979</a>)</em></sub></div>

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/nuxt.js/issues/3682, right?

**Comment by axetroy** [comment]
@manniL 
Yes. I am sorry. I didn't see it.

move discussion and close this.
