### ISSUE TITLE
nuxt.render doesnot work on express

### ISSUE THREAD

**Issue by fewiki** [nuxt/nuxt.js#4126]
After update to v2.2.0,  the example https://nuxtjs.org/api/nuxt-render/ doesnot work on express
But it works ok on nuxt-edge

When "npm run build"，the build folder structure is change, 
![image](https://user-images.githubusercontent.com/13325335/46999590-a2980880-d158-11e8-9b9c-9f0aa1f98415.png)

**Comment by manniL** [comment]
More info needed!
