### ISSUE TITLE
Object.assign can get emitted via serializing the Nuxt State (Serialized Session)

### ISSUE THREAD

**Issue by Ayiga** [nuxt/nuxt.js#4139]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://codesandbox.io/s/vqnjopy7n0](https://codesandbox.io/s/vqnjopy7n0)

### Steps to reproduce

Visit the reproduction link on codesandbox.io.

I have output the inject Nuxt state, and I have bolded any occurrences of `Object.assign`.

### What is expected ?

`window.__NUXT__` should be assigned to via a `JSON`-esque syntax that provides minimum compatibility requirements, or that the output is transpiled before being written to the page.

### What is actually happening?

`Object.assign` is  in the output of this injected serialized state as it doesn't get transpiled.

This breaks compatibility with Older browsers (Specifically Internet Explorer 11)

### Additional comments?

If a plugin exists that will modify the `nuxtState`, then `Object.assign` will be injected into the global Nuxt state via the rendered due to `devalue` or `@nuxtjs/devalue` . 

[This is the line that the serialization gets emitted by](https://github.com/nuxt/nuxt.js/blob/d35fc8f01584c3566d96cd1844413bca177a54a7/lib/core/renderer.js#L365) 

[This is the line that adds to the state in my example](https://github.com/nuxt-community/apollo-module/blob/v4.0.0-rc2.3/lib/templates/plugin.js#L51)

[This is the line in devalue that is emitting Object.assign](https://github.com/nuxt-community/devalue/blob/a5c68341b9a507fb600cdabfb2094143e889fc84/src/index.ts#L128)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7994">#c7994</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment]
Any updates regarding this issue? I tried to use `babel-polyfill` as a plugin to workaround this issue, but it's still has no effect. The only way it can be mitigated right now is by including `https://cdn.polyfill.io/v2/polyfill.min.js` as a blocking script before main js bundle will be loaded

**Comment by manniL** [comment]
The code comes from the original lib. Further discussion on https://github.com/Rich-Harris/devalue/issues/16
