### ISSUE TITLE
error.vue infinite loop

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#4140]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/vvz3072j15](https://codesandbox.io/s/vvz3072j15)

### Steps to reproduce

1. Create custom error.vue that contains an error
2. trigger error.vue
3. notice the infinte error loop

### What is expected ?

something catches the error

### What is actually happening?

catches and attempts to load the error.vue infinitely

### Additional comments?

The main issue is that the API for the `error` prop being passed to the error.vue page has changed. Before 2.x, it was expected that `error.response` was available. Anybody that was using this, ie: `error.response.data` now have this error. There should be a notice to nuxt users so they are aware of this API change.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7995">#c7995</a>)</em></sub></div>

**Comment by manniL** [comment]
Thanks for the issue and the reproduction! :relaxed: 
I can confirm that behavior.

Would you mind sending a PR to the docs?

**Comment by aldarund** [comment]
I guess fallback to default error should happen in this case

**Comment by connecteev** [comment]
Hi, when can we expect a fix for this problem? I've seen it at least twice in the past week...this time I'm completely blocked

**Comment by pi0** [comment]
@connecteev #6217 will land soon to the `nuxt-edge` and next minor release! Stay tuned.

**Comment by connecteev** [comment]
@pi0 thanks!
