### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#415]
I want to use http://element.eleme.io/#/en-US with nuxt, But when I config the loader like:

```
loaders: [
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      },
      {
        test: /\.(eot|svg|ttf|woff|woff2)(\?\S*)?$/,
        loader: 'file-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?\S*)?$/,
        loader: 'file-loader',
        query: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
```

I got the error `ReferenceError: self is not defined`,  mybe conflict with nuxt.

when I remove this custome loaders, I got 
```
Error: Module parse failed: /home/hxh/share/new-awesomes/node_modules/.1.2.5@element-ui/lib/theme-default/index.css Unexpected character '@' (1:0)
```

So this loaders must be added to the config to make element-ui work.  

How I can resovle this error?

**Comment by ausir0726** [comment]
![Uploading Capture.PNG…]()

ElementUI work for my starter project .

`command`
```
yarn add element-ui
```

`index.vue` import Vue ElementUI locale ( I think maybe write a [plugin](https://nuxtjs.org/examples/plugins/) will be better )
```
//in script
import Vue from 'vue'
import ElementUI from 'element-ui'
import locale from 'element-ui/lib/locale/lang/en'

Vue.use(ElementUI, { locale })
```

`nuxt.config.js` add css to global
```
/*
  ** Global CSS
  */
  css: ['~assets/css/main.css','element-ui/lib/theme-default/index.css'],
```

I use nuxt.js default loader .
Is this help you ?

**Comment by bimohxh** [comment]
@ausir0726 thanks, this is work for me. the `'element-ui/lib/theme-default/index.css'` must be included in `nuxt.config.js`

**Comment by ausir0726** [comment]
reference import css or modify loader problem 

SSR use setting global css in nuxt.config.js

https://github.com/nuxt/nuxt.js/issues/97
https://github.com/ElemeFE/element/issues/2142
