### ISSUE TITLE
Sharing environment variables at start time for client and server

### ISSUE THREAD

**Issue by vlajos** [nuxt/nuxt.js#4152]
### What problem does this feature solve?

(Originally I tried to open a github issue which referred to some non-existing links http://cmty.nuxt.xyz/ , but after some googling I arrived here.)

If I understand well nuxt.config.js can be used to share environment variables with the client/server code which is nice, but happens at build time.
So If you want to build a container image what you want to control at startup with Environment variables you cannot do it this way.
You have to move the nuxt build step to the container's start script which causes downtime after the container's start.
Or you have to build different images for your different configurations.

### What does the proposed changes look like?

Ideally it would be nice to be able to configure the application when it is started.
For example with moving the interpretation of the nuxt.config.js from build time to startup time.
(But I guess this is complicated because it is implemented with webpack...)

I wanted to open a question originally, but this interface does not have question types.
Anyway let me know please if I just overlooked something and there is already some solution for this problem.

Thanks!

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8003">#c8003</a>)</em></sub></div>

**Comment by aldarund** [comment]
use nuxt-env module https://www.npmjs.com/package/nuxt-env

**Comment by vlajos** [comment]
Thanks. Based on its description this is exactly what I need.
