### ISSUE TITLE
Missing route.meta in middleware when extendRoutes

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#4154]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://codesandbox.io/s/k3loj4rk7r](https://codesandbox.io/s/k3loj4rk7r)

### Steps to reproduce

1. Open reproduction link
2. Open console
3. Click on "Info" button

### What is expected ?

On console should be:
```
in middleware 
meta ABC
```

### What is actually happening?

On console there is:
```
in middleware 
meta undefined
```

### Additional comments?

nuxt.config.js:
```js
router: {
    middleware: ["mw"],
    extendRoutes(routes, resolve) {
      routes.push({
        name: "info",
        path: "/info",
        component: resolve(__dirname, "pages/about.vue"),
        meta: { test: "ABC" }
      });
    }
  },
```

mw.js:
```js
export default ({ route }) => {
  console.log("in middleware");
  console.log("meta", route.meta.test);
};
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8004">#c8004</a>)</em></sub></div>

**Comment by awronski** [comment]
@clarkdo could you help with it? Thanks!

**Comment by awronski** [comment]
@Atinux Is it a bug or `route.meta` is not implemented?

Thanks!

**Comment by clarkdo** [comment]
@awronski Sorry for the late reply, I'll have a look
