### ISSUE TITLE
Deprecate callback-based middleware, asyncData and friends

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4158]
### What problem does this feature solve?

> A middleware can be asynchronous. To do this, simply return a Promise or use the 2nd callback argument

In times of Promises (supported since Node 4) and async/await (Node 8.something), supporting callback-based middleware doesn't seem necessary to me anymore. Deprecating that feature for `2.3` and remove it in `3.0` seems reasonable from my POV.

Related code: https://github.com/nuxt/nuxt.js/blob/dev/packages/app/template/utils.js#L203

**Update:** We should consider doing this together for *all parts* or not at all. This would include:
* Middleware
* Modules
* asyncData
* fetch
* ... (Did I miss sth?)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8007">#c8007</a>)</em></sub></div>

**Comment by galvez** [comment]
@manniL +1

**Comment by manniL** [comment]
Same applies for asyncData I'd suggest :thinking:

**Comment by manniL** [comment]
I'd love to hear feedback from @pi0, @clarkdo and @Atinux as well :relaxed:

**Comment by pi0** [comment]
@manniL I agree that most of the callback supports should be depreciated in flavor of Promise/async for code cleanup. But Node's http module is still callback based behind the scenes. So it makes sense that we support such legacy connect based middleware too.

**Comment by manniL** [comment]
@pi0 good point for serverMiddleware! Fully agree ☺️

**Comment by Atinux** [comment]
Agree for deprecating it (expect serverMiddleware like @pi0 said), great idea @manniL
