### ISSUE TITLE
 Unexpected token ...

### ISSUE THREAD

**Issue by hjaiim** [nuxt/nuxt.js#4167]
node_modules/nuxt/dist/nuxt.js:3210
        this.builder, config, { loaders: this.loaders, ...this.nuxtEnv }
                                                       ^^^

SyntaxError: Unexpected token ...

**Comment by hjaiim** [comment]
How to solve this problem

**Comment by yxc-gdut** [comment]
I have the same issue

**Comment by aldarund** [comment]
@hjaiim create a reproduction

**Comment by hjaiim** [comment]
@aldarund What do you mean, I don't understand

**Comment by aldarund** [comment]
@hjaiim i mean thats its impossible to say whats wrong and how to fix without actual code that cause this. So you need to provide not working setup either in github repo or https://template.nuxtjs.org

**Comment by hjaiim** [comment]
I was following the official scaffolding, following the official steps, and then opening the local service when this error occurred.

**Comment by serivt** [comment]
https://github.com/nuxt/nuxt.js/issues/2927#issuecomment-369728581
