### ISSUE TITLE
Repeat the package to style after using CSS module.

### ISSUE THREAD

**Issue by su1924** [nuxt/nuxt.js#4173]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://github.com/su1924/nuxt-cssModules](https://github.com/su1924/nuxt-cssModules)

### Steps to reproduce

nuxt2.20
After using cssModules(<style module>) and setting extractCSS: true, CSS packages the files, but it will be repeatedly packaged into style. How do you solve this problem?

### What is expected ?

Package to file only

### What is actually happening?

Packaging to files and pages <style>

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8015">#c8015</a>)</em></sub></div>

**Comment by su1924** [comment]
As shown in the picture

![map](https://user-images.githubusercontent.com/31235906/47344337-ccae7500-d6da-11e8-9d28-701d1a551d3a.jpg)

**Comment by su1924** [comment]
I already know how to configure it.

**Comment by su1924** [comment]
God, can no one solve this problem? Torture me for two weeks.

**Comment by manniL** [comment]
Still present in latest nuxt-edge.

**Comment by su1924** [comment]
In the new version, it should be repeated three times, which is even more serious.

**Comment by clarkdo** [comment]
@su1924 Will be fixed in #4546 😸
