### ISSUE TITLE
[edge] missing loadNuxtConfig export

### ISSUE THREAD

**Issue by sh** [nuxt/nuxt.js#4177]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

Import loadNuxtConfig via const { loadNuxtConfig } = require("nuxt-edge/bin/common/utils") in a custom startup script

### What is expected ?

const { loadNuxtConfig } = require("@nuxt/cli-edge") to return a function

### What is actually happening?

TypeError: loadNuxtConfig is not a function

### Additional comments?

We're using loadNuxtConfig to setup and boot our express app with nuxt.render middleware in dev/production mode, in order to register our own shutdown handlers and process.on(...) handlers for the app

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8021">#c8021</a>)</em></sub></div>

**Comment by sh** [comment]
version is actually dev-branch/2.3.0 but it is not available on cmty yet :)

**Comment by pi0** [comment]
Will be landed with #4160 :)

**Comment by sh** [comment]
thanks! :)

**Comment by manniL** [comment]
Now on Edge 👏
