### ISSUE TITLE
Is nuxt.js as static site generator practical for large site with many pages?

### ISSUE THREAD

**Issue by chuckcharles** [nuxt/nuxt.js#418]
Is it advisable/recommended/practical/efficient to use nuxt.js as a static site generator for a site with many thousands of pages?  I'm asking because this paragraph from vuejs.org seems to imply static site generation may not be a good idea for a large site: 

> If you’re only investigating SSR to improve the SEO of a handful of marketing pages (e.g. /, /about, /contact, etc), then you probably want prerendering instead. Rather than using a web server to compile HTML on-the-fly, prerendering simply generates static HTML files for specific routes at build time. The advantage is setting up prerendering is much simpler and allows you to keep your frontend as a fully static site.

**Comment by ausir0726** [comment]
for my experience

if you have many thousands of pages ( like products page )
that also important for seo
if you want use generate static website , is impossible generate thousands pages when you update one product information , I think you still need prerender service like prerender.io , netlify ( static host provide prerender )
or ,
don't use generate , just push nuxt project to [now.sh](https://zeit.co/now) or heroku
that can get SSR page when client request page , even many thousands of pages .
https://nuxtjs.org/faq/now-deployment

but if your site have many people visit , you maybe need some cache solution 
like, cdn cache ( cloudflare ) , or move your project to express(or others) than write file cache .

for me , I just let SSR no render products page ( many thousands of pages ) and generage project .
`nuxt.config.js`
```
generate: {
    routeParams: {
      '/products/:id': [
        // empty here
      ]
    }
  }
```
then deploy dist to netlify , let netlify handle the prerender .
and direct 404 page to /index.html ( like other spa )
