### ISSUE TITLE
Nuxt modules do not work when Nuxt project is under Lerna package

### ISSUE THREAD

**Issue by zelid** [nuxt/nuxt.js#4184]
There is `nuxt.config.js` file with few modules defined:
```
export const modules = [
  '@nuxtjs/axios',
  '@nuxtjs/auth',
  '@nuxtjs/toast',
  '@nuxtjs/proxy',
  'nuxt-fontawesome',
  '~/modules/typescript.js'
]
```

Everything worked fine when Nuxt project with with config was as a separate project.
I've transformed the project to be a Lerna  package with such `demo/packages/nuxt-demo-lerna/package.json`:

```
{
  "name": "nuxt-demo-lerna",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.6",
    "@fortawesome/vue-fontawesome": "^0.1.1",
    "@nuxtjs/auth": "^4.5.2",
    "@nuxtjs/axios": "^5.3.3",
    "@nuxtjs/toast": "^3.0.1",
    "nuxt": "^2.1.0",
    "nuxt-fontawesome": "^0.3.0",
    "nuxt-property-decorator": "^1.2.0",
    "vuex-class": "^0.3.1",
    "api": "^1.0.0"
  },
  "scripts": {
    "dev": "../../node_modules/.bin/nuxt",
    "build": "../../node_modules/.bin/nuxt build",
    "start": "../../node_modules/.bin/nuxt start",
    "generate": "../../node_modules/.bin/nuxt generate"
  }
}
```

root configs:

`demo/package.json`:
```
{
  "name": "root",
  "private": true,
  "workspaces": ["packages/*"],
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.6",
    "@fortawesome/vue-fontawesome": "^0.1.1",
    "@nuxtjs/auth": "^4.5.2",
    "@nuxtjs/axios": "^5.3.3",
    "@nuxtjs/toast": "^3.0.1"
  },
  "devDependencies": {
    "lerna":"^3.4.3"
  }
}
```

`demo/lerna.json`:
```
{
  "lerna": "3.4.3",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "registry": "https://registry.npmjs.org/"
}

```

 `@nuxtjs/axios` and other modules are installed to `demo/node_modules/@nuxtjs/*`

Running `nuxt dev` gives this error:

```
yarn run dev
yarn run v1.10.1
$ ../../node_modules/.bin/nuxt


 INFO  Building project

× fatal Error: Cannot resolve "@nuxtjs/axios" from "D:\Users\Alex\Workspace\Demo\packages\nuxt-demo-lerna\nuxtjs\axios"
  at Nuxt.resolvePath (D:\Users\Alex\Workspace\Demo\node_modules\nuxt\dist\nuxt.js:2477:11)
  at Nuxt.requireModule (D:\Users\Alex\Workspace\Demo\node_modules\nuxt\dist\nuxt.js:2481:32)
  at ModuleContainer.addModule (D:\Users\Alex\Workspace\Demo\node_modules\nuxt\dist\nuxt.js:601:27)
  at promise.then (D:\Users\Alex\Workspace\Demo\node_modules\nuxt\dist\nuxt.js:151:43)
  at process._tickCallback (internal/process/next_tick.js:43:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
  at startup (internal/bootstrap/node.js:303:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
Nuxt Fatal Error :(
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

How to make Nuxt modules work fine when Nuxt app is a Lerna package?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8028">#c8028</a>)</em></sub></div>

Update 1:

I've modified `nuxt/dist/nuxt.js` method `resolvePath(path$$1) ` to output the `const _path = this.resolveAlias(path$$1);`:

```
  resolvePath(path$$1) {
    const _path = this.resolveAlias(path$$1);

    console.log(_path)

    if (fsExtra.existsSync(_path)) {
      return _path
    }

    for (const ext of this.options.extensions) {
      if (fsExtra.existsSync(_path + '.' + ext)) {
        return _path + '.' + ext
      }
    }

    throw new Error(`Cannot resolve "${path$$1}" from "${_path}"`)
  }
```

When Lerna is used the `_path` variable is:
`D:\Users\Alex\Workspace\Demo\packages\nuxt-demo-lerna\nuxtjs\axios`
On non-Lerna application the correct `_path` was:
`D:\Users\Alex\Workspace\Demo\packages\nuxt-demo-lerna\node_modules\@nuxtjs\axios\index.js`

Update 2:
The issue happens only when you use Lerna with Yarn Workspaces (when packages are stored in "node_modules" of the root Lerna package)

**Comment by galvez** [comment]
cc @pi0

**Comment by pi0** [comment]
Thanks, @galvez for pinging me. Will check it out soon :)

**Comment by kevinmarrec** [comment]
@pi0 I'm not using Lerna but just Yarn workspaces, I'm facing the same issue (see Update 2 of @zelid), making Nuxt not usable as described.

I think it's really important to solve this issue quick if it's possible, cause everyone using Yarn workspaces will be stuck and not being able to use Nuxt at all if they use at least one module from @nuxtjs or community (and a lot of them will probably use the axios one so they will face the issue)

**Comment by kevinmarrec** [comment]
I found this issue https://github.com/nuxt/nuxt.js/issues/2765, referencing this https://github.com/algolia/vue-instantsearch-examples/pull/15/commits.

I tried
```js
import { resolve } from 'path'

export default {
  modulesDir: resolve(__dirname, '../node_modules/'),
  ...
}
```

It makes everything built. I've another issue
![screenshot_4](https://user-images.githubusercontent.com/25272043/48098614-9bc35980-e21d-11e8-9c36-63f86ed96527.png), but I think it's related to something else.

**Comment by Nandiin** [comment]
@kevinmarrec Have you solved the `tsconfig.json` problem? I'm facing same problem and grateful to hear some advice.

**Comment by kevinmarrec** [comment]
@Nandiin No sorry.. I ended up not using lerna and/or yarn workspaces, there're still issues using Nuxt when node_modules are not in the same directory as the Nuxt Project. Maybe it's all about knowing how setup well the `nuxt.config.js` with different options like `modulesDir`. I don't know :/

**Comment by kevinmarrec** [comment]
@Nandiin The error is cause `ts-loader` is not able to find the correct path of `tsconfig.json` with yarn workspaces ? I thought it was something else

Anyway If you're able to setup a Nuxt project with TypeScript and Yarn Workspaces, please share !
