### ISSUE TITLE
ERROR in nuxt.bundle.js from UglifyJs

### ISSUE THREAD

**Issue by sebastianmacias** [nuxt/nuxt.js#419]
When running 'npm run generate'

I am getting the following error:

```shell
ERROR in nuxt.bundle.js from UglifyJs
Unexpected token: name (warn) [nuxt.bundle.js:14320,4]
Webpack build exited with errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the website@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls website
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2017-03-23T04_02_10_609Z-debug.log

```

The contents of the line ( [nuxt.bundle.js:14320]) are:
```javascript
let warn = () => {}
```
Thanks

**Comment by sebastianmacias** [comment]
Found was causing the problem, I was using  [vue-awesome](https://github.com/Justineo/vue-awesome) as a plugin:

file: ~plugins/vue-awesome.js
```javascript
import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon.vue'
require('vue-awesome/icons')

Vue.component('icon', Icon)

```
I removed from the nuxt.config.js and was able to run npm run generate, however it looks like UglifyJs is [causing](https://github.com/nuxt/nuxt.js/issues/259) trouble [lately](https://github.com/nuxt/nuxt.js/issues/216)  

#385 #259

**Comment by lmj0011** [comment]
>**I removed from the nuxt.config.js** and was able to run npm run generate,

Could you give details on how you removed it?

I'm having this issue also, when trying to run my app in `production`

**Comment by sebastianmacias** [comment]
@lmj0011 are you using vue-awesome by any chance? The library doesn't work with SSR. You might have luck importing it for client side only.

```javascript

module.exports = {
  plugins: [
    { src: '~plugins//vue-awesome.js', ssr: false }
  ]
}
```

I'm currently using [vuetify](https://github.com/vuetifyjs/vuetify) for my UIs and everything so far works with SSR/static sites including their icons:

```html
<v-icon>more_vert</v-icon>
```

Vuetify uses the [material icons](https://material.io/icons/) library so everything is pretty much covered.

**Comment by lmj0011** [comment]
@sebastianmacias 

already doing similiar thing:

```js
plugins: [
    // ssr: false to only include it on client-side
    { src: '~plugins/vue-select.js', ssr: false },
    { src: '~plugins/vue-material.js', ssr: false },
    { src: '~plugins/adonis-websocket-client.js', ssr: false },
    { src: '~plugins/rollbar.js', ssr: false }
  ],
```
I didn't look too deeply into it like did, so I ended up going with this solution that worked for me: https://github.com/nuxt/nuxt.js/issues/385
