### ISSUE TITLE
Error page or error layout

### ISSUE THREAD

**Issue by rejifald** [nuxt/nuxt.js#4191]
### What problem does this feature solve?

Error page is nor layout nor page.
Problem of this becomes when you have many different layouts, and error occurs. 
Problem is error page looks different on each layout.
So problem is, that error page that looks same on every layout.

### What does the proposed changes look like?

I believe that we need be able to specify layout of error page, or have truly error layout. 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8031">#c8031</a>)</em></sub></div>

**Comment by manniL** [comment]
As explained in [the docs](https://nuxtjs.org/guide/views#error-page), the "error layout" is actually an **error page**. You can set a layout for it as well. The easiest way would be adding an "empty" layout that just contains `<template><nuxt/></template>` and use that.
