### ISSUE TITLE
Persistent state across server and client rendered pages?

### ISSUE THREAD

**Issue by antcook** [nuxt/nuxt.js#42]
Normally I'd achieve persistent state (state that doesn't expire on refresh) by using Vuex and localstorage, it seems Nuxt doesn't play nice with  localstorage, I assume this is because of it's server rendering features?

Is there currently a method to get persistent state that's accessible both on the client and the server? If not, is this something that could be implemented in the future?

**Comment by Atinux** [comment]
Hi @antcook 

Nuxt cannot access to the localstorage from the server-side point indeed.
What kind of persistent state are you storing? It will help us to know what kind of solution it's better to use.

**Comment by antcook** [comment]
It's a shopping cart, basically I want the the items in the cart to stay present when the browser is refreshed. Normally a thing I would do will localstorage.

Thanks for the quick reply! :)

**Comment by Atinux** [comment]
I see, are you using a session storage on your server, like express-session?

If so, you can create your vuex store with a `store/index.js` file and add a `nuxtServerInit` action where you can fill the state of your store from the `req.session`, this action is called only from the server-side. Take a look at [examples/auth-routes/store/index.js](https://github.com/nuxt/nuxt.js/blob/master/examples/auth-routes/store/index.js#L23)

**Comment by antcook** [comment]
I was able to use express-session to store the cart state, thanks! :)

**Comment by dmiotti** [comment]
Hi there, I want to save the user token on localStorage. The api I use don't have sessions.
However I'm struggling loading the token from localStorage when the application load on the browser. Any idea how to achieve this ?

Thanks
