### ISSUE TITLE
nuxt generate folder can't find for non english params ( folder urlencode )

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxt.js#420]
I have a problem when I use generate with Chinese params .

I define some params with Chinese language .
It work ok on node.js server , but when I generate static website with routeParams config in `nuxt.config.js`
```
generate: {
    routeParams: {
      '/post/:slug': [
        { slug: 'my-first-post' },
        { slug: '我的第一篇文章' }
      ]
    }
  },
```
static website will show 404 when I refresh at Chinese slug page

I open dist folder , I seen the Chinese params parse a url encode format 
so I can't access that page  , so I manually modify that folder back to Chinese .
`/post/%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0/index.html`
to
`/post/我的第一篇文章/index.html`
It works !

is should generate disabled url encode ? or need a option to fix this ?
now , we avoid use Chinese in params , but some customer need use Chinese url ...
hope can fix it .

thanks .

my test video
https://www.youtube.com/watch?v=n51sklBpFUw&feature=youtu.be

and online test link

[error 404]  url encoded folder
http://spurious-balls.surge.sh/

[ok 200] folder modified
http://remarkable-icicle.surge.sh/

**Comment by alexchopin** [comment]
It should be fixed in the next release.

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋ 

Take a look at https://nuxtjs.org/api/configuration-generate#routes
