### ISSUE TITLE
Programmatic usage of nuxt with express serverMiddleware as API doesn't share or update req.session 

### ISSUE THREAD

**Issue by nikkwong** [nuxt/nuxt.js#4203]
### Version

[2.1 ](https://github.com/nuxt.js/releases/tag/2.1 )

### Reproduction link

[https://google.com](https://google.com)

### Steps to reproduce

Hi, I am using nuxt programmatically and using serverMiddleware with it's own express instance which modifies req.user on some api endpoints. 

However, when I navigate to different routes after mutating req.user, nuxt is overriding req.user with one from an earlier state. I believe it is because the serverMiddleware version and nuxt are using different instances of connect under the hood.

Has anyone else experienced this, and how have you dealt with it? 

I can confirm the connect.sid is the same for both the nuxt routes and api routes.

Thank you.

### What is expected ?

req.user being mutated in api and nuxt routes.

### What is actually happening?

req.user is not mutated in nuxt routes.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8046">#c8046</a>)</em></sub></div>

**Comment by nikkwong** [comment]
Here are steps to repro, adding a few route handlers to the auth example:

```
app.get('*', function (req, res,next) {
  req.session.user = "jimmy"
   next()
})
app.get('/mutate', function (req, res) {
  req.session.user = "bob"
  res.send(200)
})
app.get('/user', function (req, res) {
  res.send(req.session.user)
})
```

1. Navigate to a nuxt route, like ```/page/123```. 
2. Navigate to ```/user``` // outputs "jimmy"
3. Navigate to ```/mutate``` // OK
4. Navigate to ```/user``` // outputs "bob" — good! 
5. Navigate to ```/page/123```
5. Navigate to ```/user``` // outputs "jimmy" — ???

So it seems as though nuxt is not picking up the changes to req.session that are happening.

**Comment by manniL** [comment]
@nikkwong Can you add a Codesandbox please (just fork the referred example and add your changes)?
