### ISSUE TITLE
Inconsistent css in dev vs prod

### ISSUE THREAD

**Issue by adi-zz** [nuxt/nuxt.js#4204]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://github.com/adi-zz/nuxt-css-dev-vs-prod](https://github.com/adi-zz/nuxt-css-dev-vs-prod)

### Steps to reproduce

1. git clone https://github.com/adi-zz/nuxt-css-dev-vs-prod
1. cd nuxt-css-dev-vs-prod
1. npm i
    1. npm run dev
    1. npm run build && npm run start
1. open http://localhost:3000/

### What is expected ?

The background color of nuxt logo should be blue in both cases 3.1. and 3.2. (or at least red in both cases).

### What is actually happening?

Background is blue in dev mode (3.1.), and red in prod mode (3.2.)

### Additional comments?

My project was generated using `npx create-nuxt-app test` (choosing all defaults)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8047">#c8047</a>)</em></sub></div>

**Comment by spnc-omz** [comment]
I'm also seeing this. For the time being I've pinned my version to v2.1.0 of nuxt and it works. 

I suspect that this may have something to do with the following commit but have not tested enough to be 100% certain to say yes or no. 
 https://github.com/clarkdo/nuxt.js/commit/ec63cfc83529444189f47c16227d8e31842d4d32#diff-e08c5c9779ed38bdf6e44f502bb1e732

**Comment by manniL** [comment]
@spnc-omz Oh, so it worked with 2.1?

**Comment by spnc-omz** [comment]
This gets even more weird. I think I had a dependency issue. Everything worked for me after I updated my postcss preset ebb to ~6.3.0

**Comment by AndrewBogdanovTSS** [comment]
@spnc-omz which exact module are you referring to? I only see `postcss-env-function` in my node_modules folder

**Comment by clarkdo** [comment]
@AndrewBogdanovTSS 😸 

I understand and I didn't mean that we must use `scoped` here.

Since the injection of css files is asynchronous, so the order of css files are not guaranteed, the root problem is more related to the way how we should organize css. 

My point is that it's not a proper way to prioritize styles depending on the order of selector location in file.

If we want make a selector prior to another, we should use higher priority selector:

```vue
// component
<style>
.VueToNuxtLogo {
  background-color: red;
}
</style>

// index.vue
<style>
.index .VueToNuxtLogo {
  background-color: blue;
}
</style>
```

**Comment by AndrewBogdanovTSS** [comment]
@clarkdo yeah, I also understand that, but you know, people been controlling css priority by defining specific order for years and  practically getting rid of this habit will mean rewriting thousands of already existing css selectors whereas just switching the file order will fix it in a finger snap (you don't even need to be a Thanos to do that)

**Comment by tmorehouse** [comment]
I'm seeing this issue also.

Using the nuxt.config.js `css` option, I am seeing inconsistent CSS load order, which doesn't follow the order specified. in the CSS array

We are using 3rd party CSS libraries, of which we create an override style sheet, which needs to be loaded last, and sometimes it is being loaded first.

**Comment by AndrewBogdanovTSS** [comment]
Wasn't this already been fixed? I had similar issue I logged here https://github.com/nuxt/nuxt.js/issues/4219#issuecomment-437545141
and now it's respecting an order for me

**Comment by AndrewBogdanovTSS** [comment]
@tmorehouse did you try it with Nuxt 2.4.2? Is it working for you?

**Comment by tmorehouse** [comment]
@AndrewBogdanovTSS

The issue appears to have been fixed.

**Comment by manniL** [comment]
Nice!

**Comment by eiva** [comment]
And it happening again for "nuxt": "^2.7.1"
In the inspector window, I see that styles have a different order.
The application was generated using `npx create-nuxt-app test` with vuetify ui.
And I see that `_grid.styl` appears after `_lists.styl` in dev and vice versa in prod.
There a lot of other scuffles as well.
Could this ticket be reopened? Or I need to create new one?

**Comment by clementmas** [comment]
Yes, I'm having the same issue here with inconsistent styling between dev and prod environments.

Here's a link to a reproduction: https://codesandbox.io/s/examplenuxtvuetifycssorder-k4ob0
- Expected: have card title and text on the same line because of CSS `display: inline` inside component (which works well in dev environment)
- Result: card title and text are on 2 different lines because the third-party CSS `display: flex` appears after (only in prod environment)

I thought it might be an issue with `vuetify-loader` but they say it's not: https://github.com/vuetifyjs/vuetify-loader/issues/23

Can this issue be reopen?

**Comment by fbrbovic** [comment]
I am experiencing the problem too.  Also using vuetify-loader

**Comment by AndrewBogdanovTSS** [comment]
@manniL please, reopen! extractCSS is so buggy that I actually gave up on it, it was easier to reduce styles by 10 times than to fix all issues that keep happening with this property 🤦‍♂️

**Comment by manniL** [comment]
Please see #4219

**Comment by mjmnagy** [comment]
Styles are different - not using purgecss or any other plugin accept nuxt defaults

**Comment by DengSihan** [comment]
this issues happened to the css which used on the classname/id/element add by javascript, when you run `npm run prod` ,then nuxt will check which classname/id/element were used, and render these css only, different from `npm run dev` which nuxt will render all the css

**Comment by mjmnagy** [comment]
i am using a combination of <style scoped> and inline css computed by JS. 
No style sheets are imported

**Comment by isenewotheo** [comment]
Based on my experience, there  are 2 reasons that i know of that makes the css of the  built version not consistent with the dev version.
1. using  unscoped style <style> in components
2. using wrong css (i found out i was using "margin: initial 30px" instead of "margin: 0 30px"
