### ISSUE TITLE
Add File Loader to Head Link or Meta Section in Nuxt Config

### ISSUE THREAD

**Issue by jefrydco** [nuxt/nuxt.js#4211]
### What problem does this feature solve?

We can add custom css to nuxt config using `~/assets/style.css`, but currently it cannot add image or another asset using that way in link or meta in head section.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8049">#c8049</a>)</em></sub></div>

**Comment by manniL** [comment]
@jefrydco Could you provide an example what would be possible with this feature?

**Comment by jefrydco** [comment]
@manniL For instance adding apple touch icon or chrome icon, like this

```
link: [
      {
        rel: "apple-touch-icon",
        sizes: "57x57",
        href: "~/assets/img/favicon/apple-touch-icon-57x57.png"
      },
]
```

**Comment by manniL** [comment]
You have a few options there:

* Use something like https://github.com/nuxt-community/pwa-module
* Write your own implementation/module that does that.

As an easy way is already given with the first solution, I'm closing here ☺️
