### ISSUE TITLE
Middleware not invoked correctly

### ISSUE THREAD

**Issue by WangHansen** [nuxt/nuxt.js#4224]
### Version

[2.0.0](https://github.com/nuxt.js/releases/tag/2.0.0)

### Reproduction link

[https://jsfiddle.net/boilerplate/vue](https://jsfiddle.net/boilerplate/vue)

### Steps to reproduce

Middleware not called correctly
I have a middleware named `load-auth` which essentially check the login status of the user by making a call to `/verify` api, which returns true if the user credential is valid

here is the verify action defined in vuex store:
```javascript
// store/auth.js
async verify ({ commit }) {
    let res
    try {
      res = await this.$axios.get('/verify')
    } catch (error) {
      commit('logout')
      throw new Error('Not verified')
    }

    if (!res.data.success) {
      commit('logout')
      throw new Error(res.data.message)
    }

    commit('login')
    commit('setUser', res.data.user)
  }
```

and here is the middleware

```javascript
// load-auth.js
export default function (ctx) {
  return ctx.store.dispatch('auth/verify')
}
```

### What is expected ?

Middleware called and login the user automatically

### What is actually happening?

If I use the above code for middleware, I got 'No response received' and would not be able to display the page

If I try to do the following
```javascript
if (process.server) {
    return ctx.app.$axios.get('/verify').then(res => {
      ctx.store.commit('auth/login')
      ctx.store.commit('auth/setUser', res.data.user)
    })
}
```

It would give me a socket hangup error

How should I save the state of login, my auth is based on cookie, so there is not really a problem for saving the state, I just want to call the `/verify` api when page refreshes to check the login state.
I recently upgraded from 1.4.0 to 2.0.0, this was working in 1.4.0 as the [example](https://github.com/nuxt/example-auth0) given in the doc

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8056">#c8056</a>)</em></sub></div>

**Comment by manniL** [comment]
@WangHansen I don't think HTTPS should be a problem. Do you use `Brotli` compression? That might be a problem

**Comment by WangHansen** [comment]
@manniL I use https and proxy, I think the problem is the axios called at middleware is from server side, which doesn't go through the proxy, so I need to do `$axios.get('https://127.0.0.1/verify')` instead of `$axios.get('/verify')`. Another problem I noticed is that I use self signed cert, so it gets blocked. I need to do `axios.defaults.httpsAgent = new https.Agent({ rejectUnauthorized: false })` for it to work. But if I remove https and change to http, so would not be a problem

**Comment by manniL** [comment]
@WangHansen The middleware will be called from server-side once (on SSR) and then from the client-side, yes.

**Comment by WangHansen** [comment]
@manniL I don't think it will be called from client side anymore since 2.0.0, I tried to console.log but nothing showed up. So I doubt that

**Comment by manniL** [comment]
@WangHansen It will. Please refer to my CSB and look in the terminal/console when navigating from "/" to "/about" https://codesandbox.io/s/l6o20jmw7

**Comment by WangHansen** [comment]
@manniL I see that, but that would be called from server, right? not client. If you try `process.client` or `process.browser`, i dont think it works.

**Comment by manniL** [comment]
```js
export default () => {
  console.log("Test middleware.", process.server);
};
```
If you access `/` (the "entrypoint" for your request), the middleware will be executed on server side

![image](https://user-images.githubusercontent.com/640208/47651720-dd983400-db7b-11e8-8a72-8c037dcf89dd.png)

If you navigate, on client side

![image](https://user-images.githubusercontent.com/640208/47651737-e7219c00-db7b-11e8-8631-5a11bf9dc47f.png)

**Comment by WangHansen** [comment]
I see, I was mainly focused on the reload, because that is where i need to have the middleware running, but when you reload, the middleware is not called from the client side. 
![image](https://user-images.githubusercontent.com/15679461/47651860-bb41ee80-db5a-11e8-9e55-e68291756a60.png)
But you were right, if you navigate, it would work.

**Comment by manniL** [comment]
Exactly, if you do a hard reload your request will be server-side rendered, so the middleware will be called on server-side

**Comment by aldarund** [comment]
@WangHansen middleware called either on client or server. not on both

**Comment by WangHansen** [comment]
@aldarund I see, I guess the documents can be made better about it, I will submit a PR to improve the doc
