### ISSUE TITLE
CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ntvuong1709it** [nuxt/nuxt.js#4225]
### Version

[2](https://github.com/nuxt.js/releases/tag/2)

### Reproduction link

[https://github.com/ntvuong1709it/crawler-nuxt](https://github.com/ntvuong1709it/crawler-nuxt)

### Steps to reproduce

yarn run build

### What is expected ?

Build complete and be able to run using command yarn run start

### What is actually happening?

I received this error as following:
<--- Last few GCs --->

[9428:0000017514B27C20]    70741 ms: Mark-sweep 1377.3 (1467.6) -> 1377.3 (1468.1) MB, 1134.8 / 0.0 ms  allocation failure GC in old space requested
[9428:0000017514B27C20]    71815 ms: Mark-sweep 1377.3 (1468.1) -> 1377.2 (1434.1) MB, 1073.2 / 0.0 ms  last resort GC in old space requested
[9428:0000017514B27C20]    72862 ms: Mark-sweep 1377.2 (1434.1) -> 1377.2 (1434.1) MB, 1046.5 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002521B2257C1 <JSObject>
    0: builtin exit frame: defineProperty(this=000001A2E8319A51 <Object map = 000003413FAF15F1>,0000038B0E00C759 <Object map = 000001FC8BD43E91>,0000033D19816A
F9 <String[5]: 10923>,0000004D3F016009 <Object map = 00000067614D3C41>)

    1: addGetter [My_Directory\node_modules\esm\esm.js:~1] [pc=0000000AC9FB3D64](this=0000004D3F015E59 <bc map = 000003B38C4262D1>,e=0000033D19816
AF9 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArray
 5: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::EnsureCapacity
 6: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::Add
 7: v8::internal::LookupIterator::TransitionToAccessorPair
 8: v8::internal::LookupIterator::TransitionToAccessorProperty
 9: v8::internal::JSReceiver::GetOwnPropertyDescriptor
10: v8::internal::JSReceiver::class_name
11: v8::internal::JSReceiver::class_name
12: v8::internal::JSReceiver::class_name
13: v8_inspector::protocol::Schema::API::Domain::fromJSONString
14: v8_inspector::protocol::Schema::API::Domain::fromJSONString
15: 0000000AC9A06B21
error Command failed with exit code 3.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8057">#c8057</a>)</em></sub></div>

**Comment by ntvuong1709it** [comment]
I created a fresh project(using express as server) and run command:
`yarn run build`
=> successfully
But after adding a serverMiddleware into nuxt.config.js file as following:
module.exports = {
  mode: 'spa',
  ...

  **serverMiddleware: [
    '~/server/index.js'
  ]**
}

and run build again, the Server listening on http://127.0.0.1:3000 like forever and consume my RAM so much

**Comment by aldarund** [comment]
@ntvuong1709it your server middleware doesnt make sense. Inside it you import nuxt config etc. So u get an infinite recursion.
Server middleware should look like this
```
export default function (req, res, next) {
    // req is the Node.js http request object
    console.log(req.path)

    // res is the Node.js http response object

    // next is a function to call to invoke the next middleware
    // Don't forget to call next at the end if your middleware is not an endpoint!
    next()
}
```
https://nuxtjs.org/api/configuration-servermiddleware/

**Comment by manniL** [comment]
Hey @ntvuong1709it :wave: 

You are mixing two things up here. 

If you want to use **Nuxt on top of Express*, you'd have to start the `server.js` (by running `node -r esm server/index.js` in your project root).

If you want to use **Express in Nuxt**, you can easily leverage `serverMiddleware` but not with the generated `server/index.js` For a live example you can look into https://github.com/manniL/thanks.lichter.io/blob/master/nuxt.config.js#L16

Hope that helps.

Another article about using `serverMiddleware` in detail can be found [here](https://blog.lichter.io/posts/sending-emails-through-nuxtjs)

**Comment by ntvuong1709it** [comment]
Thanks @manniL for quick response, I'll have a look into your useful link
