### ISSUE TITLE
nuxt generate error

### ISSUE THREAD

**Issue by flamner** [nuxt/nuxt.js#4226]
### Version

[v1.4.4](https://github.com/nuxt.js/releases/tag/v1.4.4)

### Reproduction link

[http://thisisstupidfield.com](http://thisisstupidfield.com)

### Steps to reproduce

run next generate

### What is expected ?

generating project

### What is actually happening?

get an error, no idea, what is wrong, and how to fix it :/

### Additional comments?

######/node_modules/esm/esm.js:1
const __global__ = this;(function (require, module, __jest__, __shared__) { "use strict";var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,()=>e.a},r.r=function(){},r(r.s=2)})([(function(e,t){var r;t=e.exports=H,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";

Error [ERR_MODULE_RESOLUTION_LEGACY]: ######/nuxt.config.js not found by import in ######. Legacy behavior in require() would have found it at ######/nuxt.config.js
    at el (######/node_modules/esm/esm.js:1:195445)
    at Su (######/node_modules/esm/esm.js:1:215929)
    at qa (######/node_modules/esm/esm.js:1:187511)
    at Eu ######/node_modules/esm/esm.js:1:217149)
    at Module.<anonymous> (/######/node_modules/esm/esm.js:1:250405)
    at o (######/node_modules/esm/esm.js:1:235191)
    at exports.loadNuxtConfig (######/node_modules/nuxt/bin/common/utils.js:45:15)
    at Object.<anonymous> (######/node_modules/nuxt/bin/nuxt-generate:40:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (######/node_modules/nuxt/bin/nuxt:32:1)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8059">#c8059</a>)</em></sub></div>

**Comment by flamner** [comment]
also same error on run next build

**Comment by aldarund** [comment]
create a reproduction example either on https://template.nuxtjs.org or github repo. Otherwise its hard to say

**Comment by flamner** [comment]
I think that the problem is in create-nuxt-app, I make a new project, witch no changes, and try to run nuxt build and... got that same error :/ node version 8.10.0

**Comment by aldarund** [comment]
@flamner upload your created project on https://template.nuxtjs.org/  or github repo. There a lot of diferent setups that can be genereted via create nuxt app

**Comment by flamner** [comment]
https://github.com/flamner/konkurs

**Comment by aldarund** [comment]
@flamner i did build & generate your project and there was no errors

**Comment by flamner** [comment]
npm cache clean --force
remove node modules and install again
npm install -g npm@latest
even tried this: https://www.npmjs.com/package/reinstall

nothing works :(

**Comment by flamner** [comment]
also upgrade node to v8.12.0 :/

**Comment by pimlie** [comment]
Can you try running nuxt directly instead of through npm?
```
$ ./node_modules/.bin/nuxt build
```

The build args in line 10 of your output seem strange, where is that `-c` coming from? Its not in the package.json in your repo
