### ISSUE TITLE
Axios interceptors

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#423]
hey , 
where i should import my interceptors.js file so it will work with all the axios requests, usually i import it in bootstrap.js

there is my file:

![image](https://cloud.githubusercontent.com/assets/19589742/24253593/04705598-0fe1-11e7-918b-252dbd401bb8.png)

**Comment by ausir0726** [comment]
you can write a plugin , and import in `nuxt.config.js`
https://nuxtjs.org/examples/plugins

by the way , import sweetalert2 should give you a window not defined error 
you should use 
```
if(process.BROWSER_BUILD){
  consot swal = require('sweetalert2');
}
```

**Comment by Atinux** [comment]
Like @ausir0726 said, you can create a `plugin/axios.js` file and in your components, instead of `import axios from 'axios'`, use `import axios from '~plugins/axios.js`'
