### ISSUE TITLE
link[rel="preload"] header is always generate as [as="script"]

### ISSUE THREAD

**Issue by hinaloe** [nuxt/nuxt.js#4234]
### Version

[v2.3.0](https://github.com/nuxt.js/releases/tag/v2.3.0)

### Reproduction link

[https://codesandbox.io/s/8y3z57538j](https://codesandbox.io/s/8y3z57538j)

### Steps to reproduce

1. create project
2. set `build.extractCSS: true` on `nuxt.config.js`
3. `nuxt  generate`
4. open generated file (index.html)

### What is expected ?

found `<link rel="preload" href="/_nuxt/csshash.css" as="style">`

### What is actually happening?

found `<link rel="preload" href="/_nuxt/csshash.css" as="script">`

`as` should not be `script`

### Additional comments?

`as="script"` is hardcorded on

https://github.com/nuxt/nuxt.js/blob/39b558f59c0ecb5aa40bf709ca5dff83a151b20b/packages/vue-renderer/src/spa-meta.js#L84

This making duplicate file load.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8064">#c8064</a>)</em></sub></div>

**Comment by hinaloe** [comment]
it should not close

**Comment by manniL** [comment]
Should be resolved with https://github.com/nuxt/nuxt.js/commit/70f0dc38254f1f3745e57f0f41d761484a3256bb#diff-94fe659fbf41671ebea3982b249d2fd3R134

**Comment by manniL** [comment]
@hinaloe You can try it with the latest `nuxt-edge` if you want ☺️
