### ISSUE TITLE
Use vuex helper functions

### ISSUE THREAD

**Issue by rmartins90** [nuxt/nuxt.js#424]
Hi guys, I'm migration my code from vanilla vue.js to nuxt.js. Congrats on this btw.

I'm trying to make use of vuex helper functions like mapActions or mapGetters but I can't access to the methods. Please consider the following code snippet:

    methods: {
      ...mapActions('searchView', {
        searchRequest: actionTypes.SEARCH_REQUEST,
        clearState: actionTypes.SEARCH_CLEAR_STATE,
        setPageSize: actionTypes.SEARCH_PAGE_SIZE_SET
      })
    },

    fetch (context) {
      const requestParams = context.route.query
      this.searchRequest(requestParams)
    },

This returns:

> this.searchRequest is not a function

What am I missing here?

**Comment by rmartins90** [comment]
Actually, this isn't an issue related to mapActions or other vuex helper functions but it's related to the methods not being available on fetch method of a page.

**Comment by Atinux** [comment]
Hi @rmartins90 

This is normal since `fetch` is called from the server-side as well and we cannot give the context (`this`) to the method.

You need to call directly your action like this:

```js
fetch (context) {
  const requestParams = context.route.query
  return context.store.dispatch(`searchView/${actionTypes.SEARCH_REQUEST}`)
}
```

**Comment by rmartins90** [comment]
Thanks for the explanation @Atinux.
