### ISSUE TITLE
Generate valid html

### ISSUE THREAD

**Issue by EmmanuelBeziat** [nuxt/nuxt.js#425]
Hi,

I’d like to generate valid html output when in production… Actually there are 3 problems:

- **html attributes comes without spacing when minified** → This isn’t allowed(http://www.w3.org/TR/html5/syntax.html#start-tags see point 4)
- **n-x attributes are used** → html5 only allow custom attributes if they start by data-*. How can I change this settings? The [html-head](https://nuxtjs.org/guide/views/#html-head) section of the doc show the custom attributes names, but don’t explain if it’s customisable, and how. Besides, there’s also a `n-head-ssr` in the default `app.html`
- **defer in scripts that are not loaded** → a script tag is added at the end of the file, with the attribute defer, but it's only allowed if the attribute src="" is used; not on "containing" script tags. I think this is this in default `app.html`:
```html
 <script type="text/javascript" defer>window.__NUXT__=<%= serialize(context.nuxt, { isJSON: true }) %></script>
```

For the first point, this is a webpack configuration to add, but maybe having simple options to switch in `nuxt.config.js` would be better? And with a default to not remove spaces? Actually, I couldn't find yet how to get this properly with the [extend options](https://nuxtjs.org/faq/extend-webpack).

The third point could be solved by using a [custom Template](https://nuxtjs.org/guide/views/#document), but once again, shouldn't an "out-of-the-box" code be valid in the first time?

Thanks for your help.

**Comment by Atinux** [comment]
Hi @EmmanuelBeziat 

> - html attributes comes without spacing when minified → This isn’t allowed(http://www.w3.org/TR/html5/syntax.html#start-tags see point 4)

This is fixed in the next release, and the `html-minifier` option will be customizable via `generate.minify` in the `nuxt.config.js`

> - defer in scripts that are not loaded → a script tag is added at the end of the file, with the attribute defer, but it's only allowed if the attribute src="" is used; not on "containing" script tags.

Fixed in the upcoming release.

> - n-x attributes are used → html5 only allow custom attributes if they start by data-*. How can I change this settings? The html-head section of the doc show the custom attributes names, but don’t explain if it’s customisable, and how. Besides, there’s also a n-head-ssr in the default app.html

I can change it, but the HTML is still not valid because of the `server-rendered` attribute of vue.js:
![screen shot 2017-03-23 at 22 42 24](https://cloud.githubusercontent.com/assets/904724/24271733/859fb2f6-101a-11e7-9666-5987b0d56a2e.png)

I asked Evan if we can customize this attribute to be able to generate valid HTML markup, I'll keep this thread updated 👍

**Comment by EmmanuelBeziat** [comment]
Yay, awesome. Thanks a lot!

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋ 

I talked to Evan You, he will update the `server-rendered` key to `data-server-rendered` to generate 100% valid HTML.

**Comment by EmmanuelBeziat** [comment]
Excellent! Thanks again!

**Comment by EmmanuelBeziat** [comment]
Hi, me again, sorry!

There’s another issue with vue-meta, as "hid" isn’t valid. Is there a way to change it to something else (like simply "id")? If I change it myself, it’s not replaced in child views.

Thanks!

**Comment by EmmanuelBeziat** [comment]
Hi,
Any update on this?

Thanks!

**Comment by ausir0726** [comment]
@EmmanuelBeziat 

vue 2.3 release
https://github.com/vuejs/vue/releases/tag/v2.3.0

server-rendered -> data-server-rendered

seems we can validate w3c forward a step

- [ ] server-rendered -> data-server-rendered
- [ ] vue-meta  hid

**Comment by EmmanuelBeziat** [comment]
@ausir0726 Hi :)

Yes, the only thing missing is the "hid" — that’s what I was asking news about 😛

**Comment by ausir0726** [comment]
@EmmanuelBeziat 
did you report it on vue-meta ? :D

**Comment by EmmanuelBeziat** [comment]
Don’t really know… I supposed it to be a part of vue-meta.

**Comment by EmmanuelBeziat** [comment]
Hi! Any updates on this? Thanks!

**Comment by Atinux** [comment]
Closing since `rc3` is out :)

**Comment by EmmanuelBeziat** [comment]
Ok, thanks!
