### ISSUE TITLE
Import json file into nuxt.config.js

### ISSUE THREAD

**Issue by bart** [nuxt/nuxt.js#4250]
Hey folks,

I'm trying to import a json file of blog posts into my nuxt.config.js file like this to use it for dynamic route generation:

```
import posts from '~/posts.json'
```

When I run ``npm run generate`` I'm getting ``Cannot find module '~/posts.json``

I'm on the latest nuxtjs version. Think it has something to do with Webpack 4. Do you have any solution for it?

Thanks a lot!

**Comment by fmoessle** [comment]
Try to import post with its relative path like

import posts from './posts.json'

or importing posts from a .js file like this with its relative path

import posts from './posts.js'
