### ISSUE TITLE
Google Cache Links Redirect to /search in Nuxt applications

### ISSUE THREAD

**Issue by laugharn** [nuxt/nuxt.js#4252]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[http://webcache.googleusercontent.com/search?q=cache:https://www.nuxtjs.org](http://webcache.googleusercontent.com/search?q=cache:https://www.nuxtjs.org)

### Steps to reproduce

Do a Google search for a site running on Nuxt.js and use the cached link in the search result.

### What is expected ?

The visitor should see a cached link of the content from the last time Google crawled the URL.

### What is actually happening?

The visitor briefly sees a cached link of the content, but then is redirected to the /search URL on the domain.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8072">#c8072</a>)</em></sub></div>

**Comment by manniL** [comment]
Interesting! Can reproduce this.

**Comment by manniL** [comment]
This is an issue with `vue-router`: https://github.com/vuejs/vue-router/issues/2042

**Comment by iTechSebastianoLaini** [comment]
+1 on our Nuxt 2 app

**Comment by shmidtelson** [comment]
How to fix this problem. I think it is important for positions in Google :100:

**Comment by manniL** [comment]
This is resolved in Nuxt 3 ☺️

**Comment by swatantra7** [comment]
any update on how to resolve this in nuxt2 ?

**Comment by Kolobok12309** [comment]
> any update on how to resolve this in nuxt2 ?

Try check, it have ready fix and info how it works

https://www.npmjs.com/package/vue-router-webcache

**Comment by swatantra7** [comment]
Hi using above package, how to redirect to the cached URL here. plugins options are not working. 

> > any update on how to resolve this in nuxt2 ?
> 
> Try check, it have ready fix and info how it works
> 
> https://www.npmjs.com/package/vue-router-webcache

checking above plugin but the navigational url is not getting replaced by cached url.

**Comment by Kolobok12309** [comment]
> Hi using above package, how to redirect to the cached URL here. plugins options are not working.
> 
> > > any update on how to resolve this in nuxt2 ?
> > 
> > 
> > Try check, it have ready fix and info how it works
> > https://www.npmjs.com/package/vue-router-webcache
> 
> checking above plugin but the navigational url is not getting replaced by cached url.

You want redirect to original url when opened in cache? Or work in cache as normal spa (without change navigation url)?
