### ISSUE TITLE
npm run dev  error

### ISSUE THREAD

**Issue by BH-GeGe** [nuxt/nuxt.js#4255]
![a 08vkjovu5ufbihlcpdy](https://user-images.githubusercontent.com/31873439/47897255-f3736500-deab-11e8-9a1f-a6ee7b4925f6.png)

**Comment by MinosIE** [comment]
我也遇到同样的问题了 把index.vue这个文件 36行开头的空格去掉 就可以了
项目用了 prettier 这个工具做格式校验， https://prettier.io/docs/en/options.html 这边有配置，可以看一下

**Comment by BH-GeGe** [comment]
好像是生成项目的时候下载esLint导致的，我又重新生成一个项目安装的时候没有下载elLint，然后运行就没有报错了。
