### ISSUE TITLE
make opencollective optional when installing nuxt

### ISSUE THREAD

**Issue by makiten** [nuxt/nuxt.js#4260]
### What problem does this feature solve?

This is a request based on [this comment](https://github.com/nuxt/nuxt.js/pull/3836#issuecomment-429046655). Currently, the postinstall script lags when behind a corporate proxy that blocks access to stats from OpenCollective inside the firewall. This stalls nuxt installations and makes it difficult to adopt Nuxt in a corporate/enterprise setting.

Simply displaying a message about donating instead of calling `opencollective` _if_ a user opts to disable `opencollective` would make adopting Nuxt at work much easier.

### What does the proposed changes look like?

Use an environment variable (much like [`opencollective-postinstall`](https://github.com/opencollective/opencollective-postinstall#disabling-this-message)) to determine whether or not to show the open collective message or a static one. i.e.,

```bash
DISABLE_OPENCOLLECTIVE=true npm i nuxt
```

or

```bash
DISABLE_OPENCOLLECTIVE=true npx create-nuxt-app <my-project>
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8074">#c8074</a>)</em></sub></div>

**Comment by manniL** [comment]
This should already work: https://github.com/nuxt-community/opencollective/blob/master/src/utils/misc.js#L23

**Comment by makiten** [comment]
Is there documentation on using that environment variable? I figured there was one, but I had to guess and got it wrong.

**Comment by manniL** [comment]
@makiten There is.

https://github.com/nuxt-community/opencollective#disable-message

**Comment by makiten** [comment]
Thanks. I'll try that when I test my project at work again.
