### ISSUE TITLE
Sass variables that "cascade" down to it's child components

### ISSUE THREAD

**Issue by StefKors** [nuxt/nuxt.js#4262]
### What problem does this feature solve?

This feature would be a way to set / override a Sass variable for a page and all its child components?

You could use this as following:
Set a global $font_color variable in your main.scss file which will be globally available.
Then on one specific page you can set the $font_color variable for every child component in the page, thus making that pages easily theme-able

### What does the proposed changes look like?

It will make specific pages in Nuxt more "theme-able" without having to overwrite the Sass.

global variables
![Screenshot 2018-11-02 at 19.19.52.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/e9ff9a50-decb-11e8-afa1-eb3e20c89cf9.png)

overwritten variables
![Screenshot 2018-11-02 at 19.22.39.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/53556480-decc-11e8-afa1-eb3e20c89cf9.png)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8076">#c8076</a>)</em></sub></div>

**Comment by manniL** [comment]
This might be a better feature request directly for `vue-loader` instead :relaxed:

https://github.com/vuejs/vue-loader/
