### ISSUE TITLE
Code duplication on hot reload

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#4275]
### Version
2.3.0-25689543.1a154e8
[edge](https://github.com/nuxt.js/releases/tag/edge)

### Reproduction link

[https://cmty.app](https://cmty.app)

### Steps to reproduce

During editing of page sometime hot reload fails and produce double imports in generated code
https://gist.github.com/aldarund/033b51b211d4d764fda12e36ed8ad3d0
https://i.imgur.com/Pzv43Se.png

Seems like a race condition somehwere

### What is expected ?

no code dup :)

### What is actually happening?

code dup and fail :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8088">#c8088</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment]
@aldarund your png link doesn't work

**Comment by aldarund** [comment]
@AndrewBogdanovTSS it works.. maybe your isp blocking it.

**Comment by AndrewBogdanovTSS** [comment]
yeah, damn blockers))

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/48057020-efe12600-e1aa-11e8-8ddd-af1d35be3c25.png)
For accessibility ☺️
