### ISSUE TITLE
Can't use Sass Dart in Nuxt config.

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt.js#4284]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

I'm trying to use Sass Dart in my Nuxt project.

1. I added **sass** (Dart version),  [**sass-loader**](https://github.com/webpack-contrib/sass-loader) 7.1.0 and **fibers** dev dependencies.
2. I changed the **nuxt.config.js** file as follows:

```js
import Fiber from 'fibers'

export default {
  build: {
    extend ({ loaders: { sass } }) {
      sass.options = {
        implementation: require("sass"),
        fiber: Fiber
      }
    }
  }
}
```

I'm not sure if it's a loader issue or a integration mistake.

### What is expected ?

My Sass files should compile with the provided Sass Dart.

### What is actually happening?

Error: Cannot find module 'node-sass'.

### Additional comments?

I logged the config.rules and for all the rules that rely on sass-loader, the loader options don't include the ones I provided through loaders.sass.options.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8095">#c8095</a>)</em></sub></div>

**Comment by lucpotage** [comment]
When I log `sass.options` I do have this:

```
{ implementation:
   { run_: { [Function] '___dart__$dart_dartClosure_ZxYxX_0_': [yu] },
     render: { [Function] '___dart__$dart_dartClosure_ZxYxX_0_': [p] },
     renderSync: { [Function] '___dart__$dart_dartClosure_ZxYxX_0_': [p] },
     info:
      'dart-sass\t1.14.3\t(Sass Compiler)\t[Dart]\ndart2js\t2.0.0\t(Dart Compiler)\t[Dart]',
     types:
      { Boolean: [Function],
        Color: [Function],
        List: [Function],
        Map: [Function],
        Null: [Function],
        Number: [Function],
        String: [Function] } },
  fiber:
   { [Function: Fiber]
     yield: [Function],
     current: undefined,
     poolSize: 120,
     fibersCreated: 0 } }
```

**Comment by manniL** [comment]
Solution: https://codesandbox.io/s/kk70v7217

1. `build.extends` has the signature `(config, webpackContext)` while the latter has the `loaders` object
2. `build.extends` is too late to change the behavior, so we must override the default values in the config
3. This is where `build.loaders` comes in handy ☺️
