### ISSUE TITLE
axios plugin

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#429]
Can anyone point the problem here .. axios does not fetch the token in every request like it supposed to do.

there is my plugin/interceptors.js
![image](https://cloud.githubusercontent.com/assets/19589742/24290353/f33cab42-1084-11e7-87c8-3dcdaaa687f1.png)
and there is how i added id in the config file
![image](https://cloud.githubusercontent.com/assets/19589742/24290422/34f73638-1085-11e7-8c1b-2d1deb0f3443.png)

**Comment by Atinux** [comment]
Hi @aymenpeak 

The `interceptors.js` plugin is not called when your `import axios from 'axios'`.

Here an example:
`plugins/axios.js`
```js
import axios from 'axios'
import store from '~store'

let instance = axios.create()

if (process.BROWSER_BUILD) {
  const swal = require('sweetalert2')
  instance.interceptors.request.use(
    (config) => {
      if (store.getters.authToken) {
        config.headers.common['Authorization'] = `Bearer ${store.getters.authToken}`
      }
      return config
    },
    (error) => Promise.reject(error)
  )
  instance.interceptors.response.use(
    response => response,
    (error) => {
      if (error.response.status >= 500) {
        swal({
          type: 'error',
          title: 'Oops...',
          html: 'Something went wrong! Please try again.'
        })
      } else if (error.response.status === 401 && store.getters.authUser) {
        swal({
          title: 'Session Expired!',
          html: 'Please log in again to continue.',
          allowOutsideClick: false
        })
        .then(() => store.dispatch('logout'))
        .catch(swal.noop)
      }
      return Promise.reject(error)
    }
  )
}

export default instance
```

Then, in your components, you need to import axios like this: `import axios from '~plugins/axios'`

Also, think to add `axios` in the `vendor` bundle:

`nuxt.config.js`
```js
module.exports = {
  build: {
    vendor: ['axios']
  }
}
```

**Comment by ausir0726** [comment]
hi , but I can set interceptors without instance .
like this demo a random header Authorization
![axios](https://cloud.githubusercontent.com/assets/7247064/24295011/e4b65c72-10d3-11e7-9e36-1a58fb2d1a72.gif)

but in my production , I also use instance setting interceptors  and collect my http request , just like @Atinux .

**Comment by aymenpeak** [comment]
thanx for answering but my problem is that i get the token from server successfully but when i used in an other action in the store returns undefined.

there is my login function
![image](https://cloud.githubusercontent.com/assets/19589742/24295327/7f656cb6-109a-11e7-9f95-3eca417059ab.png)
the action saveToken works perfectually but inside fetchUser the state.token is undefined knowing that when i log te state.token in the end of saveToken it return my token correctly.
.I think its a matter of synchronization.

Sorry i know its out of nuxt.js but i really need helps ...

**Comment by ausir0726** [comment]
if you can build a simple project with problem you want to resolve on github
( include API server will be better )
that will be easier test or resolve your problem .
thanks.

**Comment by aymenpeak** [comment]
there is my store file

![image](https://cloud.githubusercontent.com/assets/19589742/24297263/6fa2ebb6-10a2-11e7-9552-1cc83bfcd884.png)
![image](https://cloud.githubusercontent.com/assets/19589742/24297273/790786f8-10a2-11e7-93cb-ff2ac3412cb9.png)
and there is the types 
![image](https://cloud.githubusercontent.com/assets/19589742/24297303/95ab1e50-10a2-11e7-8ff5-5a78b2f355c7.png)

**Comment by Atinux** [comment]
You should not use `state` from the variable but directly from your `fetchUser` method:

```js
fetchUser ({ state, commit }) {
  console.log(state)
  // ...
}
```

**Comment by aymenpeak** [comment]
yeah my bad buts there is no change , when i call a getter in my axios plugin its always undefined
![image](https://cloud.githubusercontent.com/assets/19589742/24298652/f6408ee0-10a6-11e7-8a24-3a42444645d1.png)

line 11 
...

**Comment by aymenpeak** [comment]
i solved the problems by adding a test on the cookies.get() in my store file , turn out when she returns undefined that undefined never be overwrited
![image](https://cloud.githubusercontent.com/assets/19589742/24302159/05cd199a-10b2-11e7-93af-32aa5641cab9.png)

**Comment by OrangeXC** [comment]
I use the vuex store Modules, but I can't get 

```
import store from '~store'
```

I have try

```
import store from '~/store/user'
```

but I can't use store's method

I only want get user/token and use dispatch method

what should I do?

**Comment by aymenpeak** [comment]
@OrangeXC this one of the breaking changes in the version 1.0.0-alpha.4 .
now u have access to the store and the router in the middlewares and plugins like this 
```
export default ({app: {router}, store}) => {
// here the store and the router are available
} 
```

**Comment by OrangeXC** [comment]
@aymenpeak Thank you, I solved it, I think "@nuxtjs/axios" is a better way to solve auth problem.

**Comment by lukasborawski** [comment]
@OrangeXC how to deal with 

```
const instance = axios.create({
  baseURL: process.env.baseUrl,
  timeout: 20000
})

instance.interceptors.request.use(config) => {
... 

export default instance
```

where to import store and how?

**Comment by lukasborawski** [comment]
@Atinux how to deal with your first example to pass the store to the new nuxt version, which is `{store}` notation?

**Comment by Caoyiii** [comment]
how to use store state with this  interceptors @Atinux

**Comment by awronski** [comment]
@Caoyiii if you use [axios-module](https://axios.nuxtjs.org/extend.html) you can easly access store from the interceptors:

```js
export default function ({ $axios, app, store }) {
  $axios.onRequest(config => {
    //do something with the store
    console.log(store.state.someValue)
  })
}
```

**Comment by gomezmark** [comment]
Hi,

what should i do?

```
function  verifyCode ({app, commit}, data) {
    let post =  querystring.stringify(data);

    return  this.$axios.$post('/login/otp', post)
                    .then(
                        data => {
                            Cookie.set('token', data.data.user.token);
            
                            console.log(this.$store)
                            this.dispatch('profile/getUserDetails',{},{root: true, credentials : true});
                        },
                    );
}
```

when calling the getUserDetails,
the token from cookie is null.

on the ~/plugis/axios

```
import Cookie from 'js-cookie';
export default function ({ $axios, redirect }) {
    let __token = Cookie.get("token");
    axios.defaults.headers.common.Authorize = __token;

....
```
