### ISSUE TITLE
Modern mode should alter css generation to avoid generating of unneeded vendor prefixes

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/nuxt.js#4304]
### What problem does this feature solve?

Since modern mode was placed on the root level of the config (in Nuxt-edge) and creates a js bundle version that can be used only by the modern browsers it would be logical to also generate CSS that is free from all unneeded stuff such as vendor prefixes for old browser versions.

### What does the proposed changes look like?

No additional external settings should be necessary. Same as current version.

export default {
    modern: true
}

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8113">#c8113</a>)</em></sub></div>

**Comment by manniL** [comment]
Likely related: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/202

**Comment by clarkdo** [comment]
RFC: https://github.com/nuxt/rfcs/issues/7

**Comment by manniL** [comment]
Let's continue there
