### ISSUE TITLE
Hotfix for double escaping static class

### ISSUE THREAD

**Issue by chrisvfritz** [nuxt/nuxt.js#4312]
This [will be fixed](https://github.com/vuejs/vue/pull/8037) in the next release of Vue, but currently, new lines, tabs, and other escape characters are escaped twice by Vue's SSR. The result is this:

```css
<div>
  <div 
    class="
      foo
      bar
    " 
  />
</div>
```

compiles to:

```css
<div>
  <div 
    class="\n
      foo\n
      bar\n
    " 
  />
</div>
```

so the styles for `foo` and `bar` are not applied. 

I just wanted to share that this can be worked around with the following hotfix in Nuxt projects:

```js
build: {
  extend(config, ctx) {
    const vueRule = config.module.rules.find(
      rule => rule.loader === 'vue-loader'
    )
    vueRule.options.compilerOptions = {
      ...vueRule.options.compilerOptions,
      modules: [
        ...((vueRule.options.compilerOptions &&
          vueRule.options.compilerOptions.modules) ||
          []),
        { postTransformNode: staticClassHotfix }
      ]
    }

    function staticClassHotfix(el) {
      el.staticClass = el.staticClass && el.staticClass.replace(/\\[a-z]\b/g, '')
      if (Array.isArray(el.children)) {
        el.children.map(staticClassHotfix)
      }
    }
  }
}
```

It might even be a good idea to build the hotfix into a patch release of Nuxt to fix the issue until the new version of Vue is out.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8122">#c8122</a>)</em></sub></div>

**Comment by Atinux** [comment]
Fixed for the next version of Nuxt.js coming (v2.3.0) :)
