### ISSUE TITLE
Clicking nuxt-link within transition-group triggers page loading error

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#4319]
### Version

[v1.4.4](https://github.com/nuxt.js/releases/tag/v1.4.4)

### Reproduction link

[https://codesandbox.io/s/6x1ww89xon](https://codesandbox.io/s/6x1ww89xon)

### Steps to reproduce

1. Create list of `<nuxt-link>` elements wrapped within `<transition-group>`
2. Click any of the links to navigate to another page

### What is expected ?

For target page to load

### What is actually happening?

Page loading error is thrown

### Additional comments?

Error (`Cannot read property 'length' of undefined`) triggers within TransitionGroup component, in `updated` life cycle.

```js
  updated: function updated () {
    var children = this.prevChildren;
    var moveClass = this.moveClass || ((this.name || 'v') + '-move');
    if (!children.length || !this.hasMove(children[0].elm, moveClass)) {
      return
    }
```

The reason for that is probably due to Nuxt triggering asyncData handler on the page to-be-navigated-to and something is triggering the list update while that happens.

I've also created testcase (https://codesandbox.io/s/kxp0pqnomv) using pure Vue and VueRouter but it doesn't reproduce there. Probably because navigation happens synchronously (there is no async step for fetching data for the-page-to-be-loaded).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8126">#c8126</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @rchl 

I tried your example by downloading it and running it locally and it works perfectly. It may be a bug related to CodeSandBox directly 🤔 

Usually, the error `Cannot read property 'length' of undefined` is when you forget to give the `to` property to `nuxt-link` directly.

**Comment by rchl** [comment]
I'll get back to you shortly because I also can't reproduce in my testcase now but I can locally in my app. So I'm figuring out repro steps now.

**Comment by rchl** [comment]
Please try with new sandbox testcase - https://codesandbox.io/s/6x1ww89xon

To reproduce, I had to add dependency on `nuxt-i18n` with lazy loading of translations. Not sure if there is anything specific about nuxt-i18n that causes this (maybe it triggers some updates at wrong moment) or it's just the fact that it delays loading.

**Comment by rchl** [comment]
> Usually, the error Cannot read property 'length' of undefined is when you forget to give the to property to nuxt-link directly.

In this case it seems that render() of the TransitionGroup is not called for that instance that errors because this.prevChildren is undefined (it's only set from `render`). So maybe it would be enough to just do a null check there.

**Comment by rchl** [comment]
Still valid
