### ISSUE TITLE
Default pre-processor language

### ISSUE THREAD

**Issue by sebmor** [nuxt/nuxt.js#4320]
### What problem does this feature solve?

Currently, if you use a certain pre-processor (cfr. 
https://nuxtjs.org/faq/pre-processors/), you most likely use it predominantly in your app. It would potentially make sense to have the option to declare a default so you don't have to repeat yourself. Of course always possible to be overridden on a per component basis.

For example; I use in every component `<style lang="scss">`. This could be a setting in nuxt.config instead and I could default to `<style>`.

I think of it kind of similar to how currently transition is implemented, there is a default config available in nuxt.config, but you can also set per component transitions. (cfr. https://nuxtjs.org/api/configuration-transition#the-transition-property & https://nuxtjs.org/api/pages-transition#the-transition-property)

### What does the proposed changes look like?

Something along the lines of:

```
module.exports = {
  preprocessors: {
    style: scss
 }
}
```

```
<style scoped>
</style>
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8128">#c8128</a>)</em></sub></div>

**Comment by simonhermann** [comment]
That'd be nice, but how would your text editor know that you use scss?

**Comment by manniL** [comment]
This might be a better issue for `vue-loader` instead :relaxed: (rel: https://github.com/vuejs/vue-loader/pull/500).
