### ISSUE TITLE
Nuxt application(2.0) doesn't work on IE

### ISSUE THREAD

**Issue by ChandruCR** [nuxt/nuxt.js#4326]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://github.com/ChandruCR/nuxt-vueitfy-ie](https://github.com/ChandruCR/nuxt-vueitfy-ie)

### Steps to reproduce

git clone https://github.com/ChandruCR/nuxt-vueitfy-ie
yarn 
yarn dev
open localhost:3000 on Internet explorer

### What is expected ?

Nuxt app to load

### What is actually happening?

Nuxt app doesn't load. Browser console has errors related to polyfill

### Additional comments?

I know this is a polyfill issue.

In older version of nuxt we could add  below code in nuxt.config.js and it would work on IE.
build: {
vendor: ["babel-polyfill", "event-source-polyfill"]
}

Vendor option is deprecated in nuxt 2.0 so what should i do to get this working.

Reproduction link contains simple nuxt app which is created using "yarn create nuxt-app" command.
Only thing i selected from the list of option was vuetify.

I hope to get a response soon.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8132">#c8132</a>)</em></sub></div>

**Comment by aldarund** [comment]
It errors on Array.createRange from vuetify. its not related to nuxt. And creating bug report is not  a way to ask questions :) You an ask questions in discord or cmty
You can just import polyfill in your code e.g. plugins or include polyfill from cdn into head in nuxt config
