### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by axetroy** [nuxt/nuxt.js#4327]
### Version

[v1.4.4](https://github.com/nuxt.js/releases/tag/v1.4.4)

### Reproduction link

[https://no.example.com](https://no.example.com)

### Steps to reproduce

1. run the command

```bash
nuxt dev .
```

2. Change the file and nuxt detect the change and rebuild

3. memory leak and process crash

I am very sorry, I can't reproduce it.

Here is the snapshot for memory usage. It may help.

![屏幕快照 2018-11-13 22.50.31.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/83f1bdc0-e753-11e8-8643-912ce8a1eecc.png)

![屏幕快照 2018-11-13 22.51.38.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/a85ba400-e753-11e8-8643-912ce8a1eecc.png)

![屏幕快照 2018-11-13 22.52.04.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b8d6d930-e753-11e8-8643-912ce8a1eecc.png)

### What is expected ?

It should work OK

### What is actually happening?

run ``nuxt dev .`` start the server.

Once I change the file and nuxt rebuild. Then memory leak.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8133">#c8133</a>)</em></sub></div>

**Comment by aldarund** [comment]
First you need to use latest version of nuxt e.g. 2.2

**Comment by axetroy** [comment]
@aldarund

I hope so.

But history reason. Some library doesn't update for `vue-loader@15`. so they can work in `nuxt@2.x`

I can only use `nuxt@1.x`

**Comment by aldarund** [comment]
well, the issue is that development of 1.4 is stopped and only security fixes can happen to 1.x and its not viable to fix anything other in it, especially with the amount of info you provided. And its likely something in your code that cause it.
