### ISSUE TITLE
Use service and $router.push before html rendering

### ISSUE THREAD

**Issue by vDupindev** [nuxt/nuxt.js#4329]
Hi guys,

It is possible to load data and use it to redirect to another page ?

Example of my page code :

<script>
  import MyService from '../services/my.services'

  export default {
    beforeCreate(){
      MyService.getData().then(res =>{
        this.$router.push({path: "/path/" + res})
      })
    },
    components: {
      MyService,
    }
  }
</script>

I have a problem with this code. Indeed, i can see a html rendering before the redirection with  this.$router.push.

How is it possible to solve this problem ?

Thank you.

**Comment by MrToxy** [comment]
yes, use asyncData with redirect, basically what you'll do is:

async asyncData({redirect,store}){

//get data from store or from api with app.$axios
redirect('/route here')
}

https://nuxtjs.org/api/
