### ISSUE TITLE
Middleware not running when accessing page directly

### ISSUE THREAD

**Issue by hamzehdoostie** [nuxt/nuxt.js#434]
I have a `login` page with some middleware on it:

```
<template>
  <div>
    Hello login <nuxt-link to="/">Home Page</nuxt-link>
  </div>
</template>

<script>
  export default {
    middleware: 'authenticated'
  }
</script>
```

The middleware runs successfully when navigating to the `login` page through a `nuxt-link`.
However if I go directly to the `/login` page, not through a `nuxt-link`, the middleware doesn't run.
This bug invalidates the use of middleware, since it won't run if users access pages directly.

**Comment by Atinux** [comment]
Hi @hamzehdoostie 

I tried again and I can confirm you that the middleware works perfectly on the server-side too.

Can you share your `authenticated` middleware code?

**Comment by WeeHong** [comment]
Hi @Atinux 

I am facing the same issue as @hamzehdoostie did.

The middleware works if the page is redirect from another page but not working when the page is refresh by pressing F5 or direct access to the page.

Just in case, this is how I write my script with a `console.log()`.

```
export default function ({ isServer, req, store }) {
    console.log('axios-header')
    if (isServer && !req) return
    const loggedUser = isServer ? getUserFromCookie(req) : getUserFromLocalStorage()
    if (loggedUser) {
        Axios.defaults.headers.common['authorization'] = `Bearer ${loggedUser}}`
    }
}
```
