### ISSUE TITLE
`boxen` dependency error on install

### ISSUE THREAD

**Issue by bradleyridge** [nuxt/nuxt.js#4349]
### Version

[v2.3.0](https://github.com/nuxt.js/releases/tag/v2.3.0)

### Reproduction link

[https://www.google.com](https://www.google.com)

### Steps to reproduce

`npm install nuxt`

### What is expected ?

"No matching version found for boxen@^2.0.0" error

### What is actually happening?

nuxt 2.3.0 requires a package that is either private, deprecated, or erroneous.

### Additional comments?

great work - I lOVE nuxt. phenomenal.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8155">#c8155</a>)</em></sub></div>

**Comment by scott-joe** [comment]
+1 For whatever reason, npm doesn't like `^` dependencies if the version specified with the `^` _is_ the newest version. I updated npm but it persisted. The offending line is here https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/package.json

**Comment by aldarund** [comment]
What version of node/npm? I cant reproduce it with npm 6.4.1

**Comment by bradleyridge** [comment]
## Additional Information:
_(following further digging)_ I am behind a corporate proxy and also leverage artifactory for private packages. It appears when removing the artifactory .npmrc, it installs fine - indicative of an issue with artifactory, not nuxt.
* npm v6.4.1
