### ISSUE TITLE
Lodash templates no longer have lodash functions

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#4350]
### Version

[v2.3.0](https://github.com/nuxt.js/releases/tag/v2.3.0)

### Reproduction link

[https://codesandbox.io/s/ko1j0qryvv](https://codesandbox.io/s/ko1j0qryvv)

### Steps to reproduce

Create a lodash template using a lodash function to compile a javascript file. The function does not exist. Only _.escape exists.

### What is expected ?

Lodash functions to exist still - this is a breaking change.

### What is actually happening?

The _.forEach function does not exist

### Additional comments?

I'm happy to pop in an alternative workaround if there is one.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8156">#c8156</a>)</em></sub></div>

**Comment by silverbackdan** [comment]
Of course there's a workaround - sorry it's late on Friday - I'll just use regular es6 for/of syntax. I think this still may count as a breaking change though and possibly worth a fix?

**Comment by manniL** [comment]
Likely related to https://github.com/nuxt/nuxt.js/pull/4099

Didn't know that lodash was available there by default :thinking: 

It is kind of a breaking change, though I'm not sure if that behavior is either wanted/planned or documented somewhere :thinking: 

cc @pi0

**Comment by ricardogobbosouza** [comment]
@manniL This can be closed, right?

**Comment by manniL** [comment]
@ricardogobbosouza Right, thanks :relaxed: 

Will be released in next patch.
