### ISSUE TITLE
Modern mode improvements 

### ISSUE THREAD

**Issue by clarkdo** [nuxt/nuxt.js#4356]
### What problem does this feature solve?

1. In `client` modern mode, serve modern assets in http2.push header
1. Auto detect modern mode in nuxt start

Relate to  https://github.com/nuxt/docs/pull/987#issuecomment-439603499

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8163">#c8163</a>)</em></sub></div>

**Comment by manniL** [comment]
Another suggestion: Detect `client`/`server` modern mode when `modern: true`.

**Comment by awronski** [comment]
Hi Guys!

Did you check performance between transpiled and modern version on the new browser like chrome?
Is the es6-modules faster than transpiled one? I know it may depends on the application type but in general?

**Comment by manniL** [comment]
@awronski So, the non-transpiled version *should* be smaller and faster. I haven't done any testing on that but as transpiled code has to "rebuild" natively available functions, it can't be as small and as fast as un-transpiled code for a "general application".

**Comment by awronski** [comment]
@manniL Thanks! I will do some testing

But it would be great to see A/B testing on a real site :)

**Comment by manniL** [comment]
@awronski I'll add that to my list of blog posts to do :relaxed:

**Comment by manniL** [comment]
@husayt Please create a new issue for that as it's clearly not related to that one.

**Comment by AndrewBogdanovTSS** [comment]
@husayt I just upgraded one of our projects to 2.3.2, will let you know how modern mode affected js performance for us

**Comment by husayt** [comment]
@manniL sure I will raise new issue, I thought this is related to item 2 in the description:

> 2) Auto detect modern mode in nuxt start
