### ISSUE TITLE
0.10.0 increases `npm run dev` build time significantly

### ISSUE THREAD

**Issue by corsen2000** [nuxt/nuxt.js#436]
I just upgraded to 0.1.0 and noticed that the build time of `npm run dev` has increased from about 20s to several minutes. For me it hangs on `build [==== ] 86%` for most of the time.

1. Any ideas what changes could have caused this?
1. What can I try to fix or debug this further. Anyway to profile webpack through Nuxt?

`npm run build` takes much less time than `npm run dev`, though I still believe it is longer than it was.

After the dev server starts, changing Vue files causes a quick reload. Changing anything in the API or Nuxt config which restarts the server causes the long wait again though.

This is making is difficult to work on API changes with the new version.

Thanks you for the consideration.

**Comment by Atinux** [comment]
@corsen2000 this is due to the source maps for client-side and server-side for improving the development experience, sadly it has an impact on webpack first build time.

Here what you can do to improve back the performances in your `nuxt.config.js`:
```js
module.exports = {
  build: {
    extend (config) {
      config.devtool = false
    }
  }
}
```

**Comment by corsen2000** [comment]
@Atinux thanks for the information. I'll try this out on Monday and post back if I am still seeing significant slow down in 0.10.X vs. 0.9.X.

**Comment by lemonpigpig** [comment]
@Atinux  my nuxt version  "nuxt": "1.0.0-alpha.5", i add devtool=false, but every i edit the nuxt.config.js  will build again and take too much time,i like nuxt but company think this is not good for development , i want to know there have anyway to solve this
<img width="1016" alt="2017-08-05 7 52 07" src="https://user-images.githubusercontent.com/17818782/28995268-7c34b61e-7a17-11e7-895d-e6a3b62eea63.png">
