### ISSUE TITLE
How do I update to version 0.10?

### ISSUE THREAD

**Issue by tenjojeremy** [nuxt/nuxt.js#437]
I am currently using Express+nuxt with version 0.09 

How do I update to nuxt version 0.10?

Cheers.

**Comment by Atinux** [comment]
If you are using yarn: `yarn upgrade`

Or in your `package.json`:
```js
"dependencies": {
  "nuxt": "^0.10"
}
```

And then:
```bash
rm -rf node_modules/
npm install
```
