### ISSUE TITLE
Dynamic store has undefined state

### ISSUE THREAD

**Issue by aszaffranietz** [nuxt/nuxt.js#4370]
### Version

[v2.3.1](https://github.com/nuxt.js/releases/tag/v2.3.1)

### Reproduction link

[https://codesandbox.io/s/xrkwnonowo](https://codesandbox.io/s/xrkwnonowo)

### Steps to reproduce

- Check out the Reproduction Link
- In `dynamic-store/dynamic.js` is a `console.log(state)`
- On initial page load you will see the state is filled (logged on console)
- Navigate to "About" with the Nuxt-Link and back to the Homepage
- Now the State of the dynamic registered store is `undefined`

### What is expected ?

I would expect that the dynamic registered Vuex Store would be accessible without errors. 

### What is actually happening?

An error is thrown because the state of the dynamic registered store is undefined. 

### Additional comments?

I debugged that locally and the store is registered correctly, but it seems that the watcher on a computed property gets evaluated before the store is ready.

The problem occurred just with Nuxt v2.x
Here is a Sandbox with Nuxt v1.x that works: https://codesandbox.io/s/z3r9zk1y43

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8178">#c8178</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @aszaffranietz
This problem is with a `Vuex` not `nuxt`

**Comment by aszaffranietz** [comment]
but it worked with Nuxt v1.x as I said and even the example shows. And the Vuex version is the same in both examples.

**Comment by manniL** [comment]
@aszaffranietz Pass in ` { preserveState: false }` as third argument when registering the module ☺️ 

https://3rwj436405.sse.codesandbox.io/

**Comment by aszaffranietz** [comment]
Thank you!! That seems to fix my problem. I will test it in more detail tomorrow.

**Comment by manniL** [comment]
@aszaffranietz you are welcome ;)

Closing here, if you still have issues ping back here ☺️

**Comment by aszaffranietz** [comment]
yeah thanks, man. It worked like a charm. :+1:
