### ISSUE TITLE
Chunkhash is not added to the app.js in production mode

### ISSUE THREAD

**Issue by victor192** [nuxt/nuxt.js#4371]
### Version

[v2.3.1](https://github.com/nuxt.js/releases/tag/v2.3.1)

### Reproduction link

[https://www.example.org](https://www.example.org)

### Steps to reproduce

`npm run build`

### What is expected ?

Whats to `app.js` will be added chunkhash

### What is actually happening?

In `nuxt.config.js` I have the following setting of the option `build.filenames`:
```
filenames: {
        app: ({ isDev }) => isDev ? '[name].js' : '[chunkhash].js',
        chunk: ({ isDev }) => isDev ? '[name].js' : '[chunkhash].js',
        css: ({ isDev }) => isDev ? '[name].css' : '[contenthash].css',
        img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[hash:7].[ext]',
        font: ({ isDev }) => isDev ? '[path][name].[ext]' : 'fonts/[hash:7].[ext]',
        video: ({ isDev }) => isDev ? '[path][name].[ext]' : 'videos/[hash:7].[ext]'
},
```
However, in production mode file has name `/_nuxt/app.js`. Why is it called so if it should be added chunkhash?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8180">#c8180</a>)</em></sub></div>

**Comment by victor192** [comment]
How do I reproduce the build? I can give URL where the project will be launched. Is it possible?

**Comment by manniL** [comment]
@victor192 Try https://template.nutxjs.org for reproduction :relaxed:

**Comment by manniL** [comment]
@JasonGaoG Please provide reproduction via CodeSandbox in a new issue
