### ISSUE TITLE
nuxt-start tries to build the project

### ISSUE THREAD

**Issue by husayt** [nuxt/nuxt.js#4383]
### Version

[v2.3.1](https://github.com/nuxt.js/releases/tag/v2.3.1)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

I tried using `nuxt-start 2.3.1` in Google Appengine, as I was using `2.2.0` before without problems. For some reason it tries to do the build. How can `nuxt-start` initiate the build? I switched to `nuxt start` and that worked fine. So there seems to be an isssue with `nuxt-start 2.3.1`

### What is expected ?

expected is to just start the project

### What is actually happening?

it's doing the build, which tries to write to disk, which is a problem with cloud deploys.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8184">#c8184</a>)</em></sub></div>

**Comment by manniL** [comment]
Can reproduce that 🤔 

1. Build project `yarn build`
2. Add dependency `yarn add nuxt-start`
3. Run start `yarn nuxt-start`
4.

![image](https://user-images.githubusercontent.com/640208/48852178-b01e5f00-eda4-11e8-92f0-c2b79f418977.png)

**Comment by husayt** [comment]
@manniL  did you say can or can't reproduce. From the picture I can see that "nuxt-start" is indeed trying to build, which it shouldn't. So this is indeed a bug

**Comment by manniL** [comment]
@husayt Can!
But it's fixed already ☺️

**Comment by husayt** [comment]
please ignore above comment. I didn't see comment about  hotfix from cmty.io.

Thank you very much. @clarkdo and @manniL
