### ISSUE TITLE
Important bug: api will called twice !!! if i do ... 

### ISSUE THREAD

**Issue by OliverVin** [nuxt/nuxt.js#4391]
### Version

[2.2.0](https://github.com/nuxt.js/releases/tag/2.2.0)

### Reproduction link

[https://codepen.io/olivervin/pen/yQKZKJ](https://codepen.io/olivervin/pen/yQKZKJ)

### Steps to reproduce

for seo , i replace some extra data , below :(it produce by server render ,but seo / client no need.)

    sS = '<script>window.__NUXT__'
    eS = ';</script><script src='
    page.html = page.html.substring(0, page.html.indexOf(sS)) + page.html.substring(page.html.indexOf(eS) + eS.length-12)

but , client call api again . I guess nuxt refer to the data whether server rendered . Please switch let me remove this data , for seo , because client no need this data, server have rendered .

### What is expected ?

if can give a switch for remove this extra code , it will be fine .

### What is actually happening?

i need remove extra data, but api produce data again . so api called twice . 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8193">#c8193</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @OliverVin 

I'm afraid I don't understand your bug report :(

**Comment by OliverVin** [comment]
oh,  i want to remove "window.__NUXT__" data . 
![qq20181123-0](https://user-images.githubusercontent.com/20222136/48941062-f61a2500-ef54-11e8-913c-1f5be6b2d887.png)

**Comment by manniL** [comment]
@OliverVin Okay, that is a clear request now 🙊 

However, that's not a good idea at all as `window.__NUXT__` is used to "transfer" data from SSR to the client (called serialization, more info: https://github.com/nuxt/nuxt.js/issues/2083)

**Comment by OliverVin** [comment]
oh, may be not have a good way to avoid. ?!  
I don't hope seprate into a new file,  only  want to remove .

**Comment by manniL** [comment]
@OliverVin Why do you want to avoid that behavior? A way to reduce the amount is explained in https://github.com/nuxt/nuxt.js/issues/2083#issuecomment-343731230

**Comment by OliverVin** [comment]
SEO !!!  if i use isClient , spider can't get full content. Because many spiders don't support JS .

**Comment by manniL** [comment]
@OliverVin Exclamation marks are no pack animals 😝 

It's not relevant for SEO at all as the content there is already included in the SSR'ed HTML.

**Comment by OliverVin** [comment]
ok， i try .

**Comment by OliverVin** [comment]
Don't work . Store data & Server data will write into serialization . I add  isClient, but other store data will still write again.

**Comment by manniL** [comment]
That's what serialization is for.

However, the crawler sees the server-side rendered HTML where that info (eg. store) is **already rendered into**
