### ISSUE TITLE
Multiple dynamic

### ISSUE THREAD

**Issue by EmmanuelBeziat** [nuxt/nuxt.js#440]
Hi,
Sorry it’s me again!

Considering the changes in the [generate routes configuration](https://nuxtjs.org/api/configuration-generate/#function-which-returns-a-promise), I’m stuck because I have more than one dynamic routes to use.

I was using this, and I don’t see how to "translate" it to the new way:

```javascript
routeParams: {
	'/blog/:slug': function () {
		return axios.get('https://rest.emmanuelbeziat.com/posts')
		.then((response) => {
			return response.data.map((post) => {
				return { slug: post.slug }
			})
		})
	},
	'/portfolio/:slug': function () {
		return axios.get('https://rest.emmanuelbeziat.com/portfolio')
		.then((response) => {
			return response.data.map((portfolio) => {
				return { slug: portfolio.slug }
			})
		})
	}
}
```

As the docs suggest to have a return, I don’t know how to pass it multiple routes. I took a look at the docs’s source, but it seems it’s still using the previous version.

Sorry, this one is totally a lack of JS knowledge on my side…

Thanks for your help.

**Comment by ausir0726** [comment]
hi @EmmanuelBeziat  meet you again 

I just tested nuxt 0.10.0 route generate and i18n language folder path .
It's look working perfect  . 👍 👍 👍 

this is my test generate , with 2 kind of dynamic page
http://tasteful-cars.surge.sh/

and this is my test code on github.
https://github.com/ausir0726/nuxt-route-with-params

but just can only provide you a Chinese example @@
hope it can help you .

for your question , you can see `nuxt.config.js` directly .

**Comment by alexchopin** [comment]
@EmmanuelBeziat, this should work in your case:

```js
generate: {
    async routes() {
      const blogs = await axios.get('https://rest.emmanuelbeziat.com/posts');
      const portfolios = await axios.get('https://rest.emmanuelbeziat.com/portfolio');
      const b_slugs = blogs.data.map(post => `/blog/${post.slug}`);
      const p_slugs = portfolios.data.map(portfolio =>`/portfolio/${portfolio.slug}`);
      return [...b_slugs,...p_slugs];
    }
  },
```

**Comment by EmmanuelBeziat** [comment]
Thanks to both of you!

**Comment by ausir0726** [comment]
just a note for someone search problem landing this page.

`note`
use async/await or array function you need compatible node.js version .

async/await >= 7.6

https://github.com/ausir0726/nuxt-route-with-params/issues/1

**Comment by EmmanuelBeziat** [comment]
@ausir0726 Excellent! Thanks
