### ISSUE TITLE
Vuetify and Nuxt production problem

### ISSUE THREAD

**Issue by carmas123** [nuxt/nuxt.js#4401]
### Version

[v2.3.2](https://github.com/nuxt.js/releases/tag/v2.3.2)

### Reproduction link

[https://www.isigest.net/webapp/login](https://www.isigest.net/webapp/login)

### Steps to reproduce

Hi, I'm try to develop an app with NuxtJS and Vuetify, I start all from a nuxt-vuetify template, my app work very well in develop mode, but when I try to run it in production I got many problems.
In develop I use simply http://127.0.0.1:3000/login, on my serve I use apache proxypass to redirect all requests from my path "/webapp" to node process:
ProxyPass https://127.0.0.1:3003
ProxyPassReverse https://127.0.0.1:3003

Into nuxt.config.js I've also added this command to redirect to this path when webpack build:

  build: {
    extend(config, ctx) {
      config.resolve.alias['vue'] = 'vue/dist/vue.common'
      if (!ctx.isDev) {
        config.output.publicPath = '/webapp/_nuxt/'
      }
    }
  }

Please if you visit my url you can check the problem, please help me.

My best regards,
Massimo

### What is expected ?

Vuetify scripts like ripple or others does not work

### What is actually happening?

same

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8199">#c8199</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey :wave: 

1. Please properly format your issue (especially the code part)
2. Use `build.publicPath` to set your extension properly (https://nuxtjs.org/api/configuration-build#publicpath)
3. use `ProxyPass "/webapp" "http://localhost:3003/webapp"` (and same for the reverse)
4. This is not a bug report but a question.

**Comment by carmas123** [comment]
Thank you for your reply, I solved with your help and setting 
```
router: {
    base: process.env.NODE_ENV === 'dev' ? '/' : '/webapp/'
}

```

Regards
