### ISSUE TITLE
Nuxt could check if localhost is free

### ISSUE THREAD

**Issue by samuells** [nuxt/nuxt.js#4421]
### What problem does this feature solve?

If you run nuxt in dev mode and on the localhost is already running another nuxt instance, than you get very strange error. Maybe it will be nice to have cleaner error. Nice to have ;)

### What does the proposed changes look like?

Human readable error

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8207">#c8207</a>)</em></sub></div>

**Comment by aldarund** [comment]
What strange error are u getting?

**Comment by samuells** [comment]
I mean I see there `listen EADDRINUSE 127.0.0.1:3000`, but still took me a time to get the point. :) Especially as I was adding some new packages, so my first thoughts were that problem is somewhere there. ;) Also the link to yarn documentation is misleading...

```
vents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
