### ISSUE TITLE
WARN Cannot stringify a function

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt.js#4424]
### Version

[v2.3.2](https://github.com/nuxt.js/releases/tag/v2.3.2)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

Refresh a page.

### What is expected ?

No warn.

### What is actually happening?

A warn in the console: Cannot stringify a function

### Additional comments?

I used the latest version of Nuxt with some modules (i18n, style resources, analytics). I have got the issue since version 2. How to better debug this kind of warning to detect which part of Nuxt is causing it?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8209">#c8209</a>)</em></sub></div>

**Comment by aldarund** [comment]
It should output function name 
https://github.com/nuxt-community/devalue/blob/master/src/index.ts#L27
Your store/asyncData object shouldnt contain functions, symbols and other non serializable datas

**Comment by lucpotage** [comment]
Thank you for leading me to the right direction!

I tested few things and realized the problem was linked to the nuxt-i18n module. The documentation [suggests](https://nuxt-community.github.io/nuxt-i18n/lazy-load-translations.html) to return an object or a function and in my case, returning a function outputs this warning. I changed all my locale files and now export objects.

**Comment by lucpotage** [comment]
This may interest you @manniL.
