### ISSUE TITLE
[feature request] show listen host/port when clean compiled

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxt.js#443]
upgrade 0.10

nuxt.js will clean the console when Compiled 
```
 DONE  Compiled successfully in 3695ms
```

and some one can't scroll top to find listen port ( like before 0.10 )

if can keep listen host/port , will be easy understanding for new guys who run` npm run dev`
or ...  change start port to others ( like me change to 9000 , because 3000 is running my api server  )

![capture](https://cloud.githubusercontent.com/assets/7247064/24320116/bc346622-1169-11e7-90ab-62fc6d4c8691.PNG)

**Comment by ausir0726** [comment]
If can automatic open browser will be best , I think .
but maybe have a option to disable :D

**Comment by Atinux** [comment]
It will be available in the upcoming release (0.10.3), it should be today.

![screen shot 2017-03-25 at 13 27 58](https://cloud.githubusercontent.com/assets/904724/24322195/effba502-115e-11e7-9eca-f39caa5f94f8.png)

**Comment by ausir0726** [comment]
it looks easier let some one `open box` and `use it`  😸

**Comment by Atinux** [comment]
You can upgrade to the [0.10.3](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.3) @ausir0726

**Comment by ausir0726** [comment]
@Atinux  if I setting custom port 
it will show http://9000:0.0.0.0

![capture](https://cloud.githubusercontent.com/assets/7247064/24324648/34eb8c5c-11c5-11e7-8268-3fd5c4d3a412.PNG)

**Comment by Atinux** [comment]
🤣 

I will fix it, my bad!

**Comment by Atinux** [comment]
It's now fixed in https://github.com/nuxt/nuxt.js/releases/tag/v0.10.4 👍

**Comment by ausir0726** [comment]
thanks !

it's working great  !!

👍
