### ISSUE TITLE
Bug with validate in dynamic routes

### ISSUE THREAD

**Issue by njtnestor** [nuxt/nuxt.js#4431]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://bugnuxt.netlify.com/index.html](https://bugnuxt.netlify.com/index.html)

### Steps to reproduce

Create a new project with this pages directory:

pages/
--| _knifes
-----| index.vue
--| index.vue

Create a validate method in pages/_knifes/index.vue:

      validate ({ params, query, store}) {
        return false
      }

Go to reproduction link: https://bugnuxt.netlify.com/index.html

### What is expected ?

Expect a 404 page like https://bugnuxt.netlify.com/example

### What is actually happening?

validate() method doesn't work with index.html

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8214">#c8214</a>)</em></sub></div>

**Comment by njtnestor** [comment]
> Not clear what the issue. You are saying create validate method in pages/_knifes/index.vue and then access index page. Why would validate method from _knifes/index.vue should be run on access of /index.vue ? Whats inside your /index.vue

This is the repo with the issue: https://github.com/njtnestor/bugNuxt . You can install it and check it the issue. 
In dev mode(npm run dev) the route: localhost:3000/index.html return a correct 404(by validate method) but in netifly(https://bugnuxt.netlify.com/index.html) return 200 because validate method doesn't work with index.html and i dont know the reason.

**Comment by aldarund** [comment]
@njtnestor so you are using generate. When u do generate dynamic routes dont generated at all. See docs https://nuxtjs.org/api/configuration-generate/#routes

**Comment by njtnestor** [comment]
> @njtnestor so you are using generate. When u do generate dynamic routes dont generated at all. See docs https://nuxtjs.org/api/configuration-generate/#routes

@aldarund This is another example: https://knifeproyect.netlify.com/

I am generating dynamic routes from an array as ['cuchillos-jamoneros', 'cuchillos-cocineros', ...] 

So in validate method of _cuchillos/index.vue i check params with that names. 

    export default {
       validate ({ params }) {
           return ...//check params
       }
    }


All of  this routes work perfectly:
https://knifeproyect.netlify.com/cuchillos-jamoneros => 200 correct
https://knifeproyect.netlify.com/cuchillos-cocineros => 200 correct
https://knifeproyect.netlify.com/badparam => 404 correct
....

But when i do https://knifeproyect.netlify.com/index.html , skip the validate method and render the folder:_cuchillos/index.vue 
**The expected result is return a 404 because index.html is not inside of array (['cuchillos-jamoneros', 'cuchillos-cocineros', ...])**  like "badparams" in https://knifeproyect.netlify.com/badparam



I am rly stucked pls, help me
