### ISSUE TITLE
process.isModern or equivalent variable.

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt/nuxt.js#4443]
### What problem does this feature solve?

Hi,

When using modern build with legacy one it would be nice to add custom poly fills to one of them (probably always legacy).

For example I would like to add `custom-event-polyfill` to my project. But I would only like to import it into legacy build.

This feature would help us to support old browsers without making package size bigger for newer one.

### What does the proposed changes look like?

It would look good.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8231">#c8231</a>)</em></sub></div>

**Comment by manniL** [comment]
You can use `req.modernMode` for now (where available):

https://github.com/nuxt/nuxt.js/blob/29c5bb651320f20bc17fea0bdfa4f1d130e83512/packages/server/src/middleware/modern.js#L43
