### ISSUE TITLE
Nuxt tags should accept PascalCase

### ISSUE THREAD

**Issue by IGassmann** [nuxt/nuxt.js#4451]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://notnecessary.io/](https://notnecessary.io/)

### Steps to reproduce

- Rename tags `<nuxt`> and `<nuxt-link> as `<Nuxt>` and `<NuxtLink>`
- Run the app

### What is expected ?

Nuxt custom tags such as `<nuxt`> and `<nuxt-link>` should work when PascalCased.

PascalCase is the recommended Vue.JS naming norm in templates: https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended

Tools that follow the norm, such as Prettier, will automatically rename `<nuxt`> and `<nuxt-link>` tags to PascalCase, and consequently break the app.

### What is actually happening?

`<Nuxt`> and `<NuxtLink>` tags aren't correctly interpreted.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8240">#c8240</a>)</em></sub></div>

**Comment by manniL** [comment]
Already present in latest `nuxt-edge` #4396
