### ISSUE TITLE
Middleware not running on direct access and page refresh

### ISSUE THREAD

**Issue by yuanwei92** [nuxt/nuxt.js#4455]
_Originally posted by @jameshhood in https://github.com/nuxt/nuxt.js/issues/2492#issuecomment-409371889_

I'm experiencing the same issue here, any page access through nuxt-link works fine. Middleware not running when access a page via direct access or <a> tag

**Comment by yuanwei92** [comment]
@aldarund Thanks

**Comment by sudhir600** [comment]
I am facing the same issue. not working on client side while direct access (F5)
https://cmty.app/nuxt/nuxt.js/issues/c8367

Any work Around ?
