### ISSUE TITLE
middleware redirect page, nuxt loading dont finish

### ISSUE THREAD

**Issue by gongzhibin** [nuxt/nuxt.js#4456]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

When using a custom loading component, router to one pageA, start in nuxt loading components excute, but middleware redirect to pageB( eg: login page )

### What is expected ?

pageA: `finish` in nuxt loding components should excute.

### What is actually happening?

pageA:  `finish` in nuxt loding components dont excute.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8247">#c8247</a>)</em></sub></div>

**Comment by aldarund** [comment]
Please create a reproduction

**Comment by gongzhibin** [comment]
Custom nuxtLoading component:
```
<template>
    <div />
</template>

<script>
export default {
    data() {
    },
    methods: {
        start() {
            console.log('nuxt loading start');
        },
        finish() {
            console.log('nuxt loading start');
        }
    }
};
</script>
```

global middleware:
export default (ctx) => {
    ctx.redirect(pageB)
};

when go to pageA, I find nuxtLoading of pageA start but dont finish

**Comment by MauricioHernanCabrera** [comment]
The same thing happens to me, a loop is generated in the middleware

**Comment by manniL** [comment]
@gongzhibin @MauricioHernanCabrera Please create a CSB for reproduction via https://template.nuxtjs.org/

**Comment by MauricioHernanCabrera** [comment]
@manniL I apologize for the inconvenience, it was just a problem with other dependencies of my project

**Comment by manniL** [comment]
Closing this based on @MauricioHernanCabrera's comment :relaxed: 

If the issue persists, please @ me here

**Comment by gongzhibin** [comment]
@manniL https://codesandbox.io/s/yqrm9rwz89
you click button 'to A and redirect B', and open console, you can find loading start and dont finish

**Comment by ijunaid8989** [comment]
```
export default async ({ store, redirect, app }) => {
  /*global $nuxt*/
  if ($nuxt.$route.path == "/v2/cameras/add" && !store.getters.is_admin) {
    redirect("/v2/cameras")
  }
}
```

I am having the same issue and it doesn't stop loading

**Comment by mridulasm** [comment]
when i redirect from any page o home page. the page dosent reload fully. why? if i refresh page then it will reload, why this occurs?
