### ISSUE TITLE
When the titleTemplate is function, pkg is not defined in the titleTemplate .

### ISSUE THREAD

**Issue by YogiLiu** [nuxt/nuxt.js#4457]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

in nuxt.config.js:
```js
const pkg = require('./package')
...
titleTemplate: titleChunk => titleChunk ? `${titleChunk} | ${pkg.name.toUpperCase()}` : pkg.name.toUpperCase(),
...
```
![code](https://i.loli.net/2018/11/30/5c00c3510bf8c.png)
Then execute `yarn run dev`.

### What is expected ?

pkg.name is replaced with the project name.

### What is actually happening?

pkg is not defined.
![error](https://i.loli.net/2018/11/30/5c00c35169744.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8250">#c8250</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't be avoided as the function is bound to the component's context (where it is executed. In this case the root instance).

More in the vue-meta source code.
