### ISSUE TITLE
nuxt generate comment handling

### ISSUE THREAD

**Issue by jochouen** [nuxt/nuxt.js#4458]
### Version

[v2.3.2](https://github.com/nuxt.js/releases/tag/v2.3.2)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

```
minify: {
    removeComments: false;
}
```
```
 terser: {
  extractComments: false
 },
```
1. Write a comment on the page
2. Yarn generate
3. The comment was deleted

### What is expected ?

test.vue
```
<template>
  <div>
    <!-- comment -->
    <h1>test</h1>
  </div>
</template>
```

test.html
```
<body data-n-head="">
    <div data-server-rendered="true" id="__nuxt__">
      ...      
     <!-- comment -->
     ...
  </body>
```

### What is actually happening?

test.html
```
<body data-n-head="">
    <div data-server-rendered="true" id="__nuxt__">
      ...      
     <!---->
     ...
  </body>
```
The comment was deleted

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8251">#c8251</a>)</em></sub></div>

**Comment by CurtisBelt** [comment]
@manniL Any manual intervention someone can do to make this work? A 3rd party integration a client needs actually requires HTML comments for it to work. Thanks!

**Comment by manniL** [comment]
@CurtisBelt This could probably already work with the latest `Vue` version.
