### ISSUE TITLE
Middleware ignored during static generation?

### ISSUE THREAD

**Issue by NateTheGreatt** [nuxt/nuxt.js#446]
I currently have a middleware parsing .md files for the respective route being accessed. This works well in dev mode, however when I run the generate command the pages do not contain the parsed .md data (component data is still there). 

Is this intended? If so, is it possible to run middleware during static generation?

**Comment by pi0** [comment]
@NateTheGreatt I was doing same thing past week, Suggest you using markdown loaders for this.
 [working example](https://bootstrap-vue.github.io). 
[nuxt.config.js](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/build/nuxt.config.js#L131)
[nuxt project src](https://github.com/bootstrap-vue/bootstrap-vue/tree/master/docs)

BTW about your situation i think you are parsing it using a directive or mounted() entry point.

**Comment by NateTheGreatt** [comment]
Thanks for the suggestion @pi0 !

This is my component for display pages:
```
import axios from 'axios'
import marked from 'marked'

var baseUrl = 'http://localhost:3000'

export default function (context, next) {
  var route = context.route
  if (route.name) {
    var url = baseUrl

    if (route.name === 'log') url += '/posts/'
    else url += '/pages/'

    url += `${route.name}.md`

    axios.get(url)
      .then((res) => {
        context.html = marked(res.data)
        next()
      })
      .catch((e) => {
        next()
      })
  } else next()
}
```

context.html is generated by the middleware

**Comment by pi0** [comment]
Would you please also share your middle-ware implementation ?

**Comment by NateTheGreatt** [comment]
Whoops, meant to but while editing accidentally removed it
```
import axios from 'axios'
import marked from 'marked'

var baseUrl = 'http://localhost:3000'

export default function (context, next) {
  var route = context.route
  if (route.name) {
    var url = baseUrl

    if (route.name === 'log') url += '/posts/'
    else url += '/pages/'

    url += `${route.name}.md`

    axios.get(url)
      .then((res) => {
        context.html = marked(res.data)
        next()
      })
      .catch((e) => {
        next()
      })
  } else next()
}

```

**Comment by Atinux** [comment]
Hi @NateTheGreatt 

The middleware is called on the static generation, but you have to know that the server is not listening, so `http://localhost:3000` will be 404.

You should open 2 tabs in your terminal with:
1. `nuxt dev`
2. `nuxt generate`

**Comment by NateTheGreatt** [comment]
Ah, of course -_-. Thanks for pointing that out!
