### ISSUE TITLE
Head serialize logic - regex breaking vue meta innerHTML custom script

### ISSUE THREAD

**Issue by bmains911** [nuxt/nuxt.js#4465]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[http://jsfiddle.net/bmains911/y1kxgo5v/](http://jsfiddle.net/bmains911/y1kxgo5v/)

### Steps to reproduce

1.) Set some minified script in the head via vue-meta innerHTML option. e.g. `function xyz(){};a=false?true:xyz();`

### What is expected ?

When the app is built, the custom script should be intact.  

`function xyz(){};a=false?true:xyz();`

### What is actually happening?

The script is being modified by the head regex in App.js

`function xyz(){};a=false?true:function();`

### Additional comments?

We have to put third party minified code up in the head. Seems like a fairly common scenario.
Could the regex in App.js be a bit heavy-handed? (given I don't know what problems it is solving).
Thanks! (edit: maybe worth noting this a breaking change for us migrating from nuxt v1 to v2 and the workaround is to manually edit the minified code given to us)

ps This breaks css set in the head as well.  e.g. `input:not(.disabled) {...}` -> `input:function(.disabled){...}`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8259">#c8259</a>)</em></sub></div>

**Comment by manniL** [comment]
related: https://github.com/nuxt/nuxt.js/pull/4079

**Comment by manniL** [comment]
Should be fixed with https://github.com/nuxt/nuxt.js/pull/4558
