### ISSUE TITLE
JavaScipt Heap out of Memory while Running Nuxt.js on Development for a Long Time

### ISSUE THREAD

**Issue by jefrydco** [nuxt/nuxt.js#4474]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[-](-)

### Steps to reproduce

Take a look this screencapt:
![1.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d74079c0-f69f-11e8-be62-09748112d9d3.png)
![2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/dae9aba0-f69f-11e8-be62-09748112d9d3.png)
![3.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d09fd9d0-f69f-11e8-be62-09748112d9d3.png)

I'm running nuxt.js in development mode for more than 5 hours, suddenly that error arise.

### What is expected ?

Nuxt.js running in development mode smoothly regarding how long it has ran.

### What is actually happening?

JavaScipt Heap out of Memory error arise.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8264">#c8264</a>)</em></sub></div>

**Comment by manniL** [comment]
@jefrydco Can you try it with latest `nuxt-edge`? Unfortunately there are memory leaks (due to dev middleware, HMR, ...) that can't be easily avoided on our side. 

https://github.com/nuxt/nuxt.js/pull/4439 should mitigate it.

**This does not affect production mode**

**Comment by jefrydco** [comment]
@manniL Oke, gotcha, thanks for explaining. Let me try `nuxt-edge` vesion.

**Comment by clarkdo** [comment]
Should be fixed in #5399
