### ISSUE TITLE
nuxt generate cause connect ECONNREFUSED error

### ISSUE THREAD

**Issue by kamontat** [nuxt/nuxt.js#4480]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/38n4nxkn76](https://codesandbox.io/s/38n4nxkn76)

### Steps to reproduce

1. create nuxt starter
2. use axios to current path (`axios.get("/user.json")`)
3. try to generate static files

### What is expected ?

Complete static files

### What is actually happening?

Error 

```
 ERROR   /                                                                                         23:22:09

Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)


 ERROR  connect ECONNREFUSED 127.0.0.1:3000                                                        23:22:09

  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8266">#c8266</a>)</em></sub></div>

**Comment by manniL** [comment]
While generating your app no server is running (compared to SSR mode).

What you want to do then is either requiring the json manually (which should be fine) or using a mounted hook (but then the info isn't included in the HTML)

Example (would probably move it to assets):

```js
import data from '~/static/data.json'
export default {

  data: () => {
    return {
      ...data,      
      show: true
    }
  },
```

**Comment by OfekA** [comment]
@manniL Wasn't the server running on version 2.1.0 and below?

**Comment by aufalmarom** [comment]
how can you @kamontat  solve and close this issue? cause i have also the same while deployed at cloudflare pages

**Comment by kamontat** [comment]
@aufalmarom Sorry, I didn't use Nuxt anymore.
