### ISSUE TITLE
Dynamic layout not working properly on the page refresh in Nuxt generate

### ISSUE THREAD

**Issue by Sumeshkumar** [nuxt/nuxt.js#4486]
### Version

[2.2.0](https://github.com/nuxt.js/releases/tag/2.2.0)

### Reproduction link

[https://github.com/Sumeshkumar/DL](https://github.com/Sumeshkumar/DL)

### Steps to reproduce

Issue: On mobile devices when refresh page/fist load, the desktop layout is loading instead of mobile.

This project is created from scratch by following below link: https://nuxtjs.org/guide/installation

Note: The deployment is nuxt generate (pre-render)

### What is expected ?

On mobile devices, mobile layout and component should load on page refresh & router changes

### What is actually happening?

Desktop layout is loading on mobile view on page refresh
Desktop component is loading first then mobile component on page refresh

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8271">#c8271</a>)</em></sub></div>

**Comment by Sumeshkumar** [comment]
Please do not close this as I can see this issue still exists.

**Comment by sarfarazengglb** [comment]
same issue.it is not inheriting the layout.
