### ISSUE TITLE
generate with spa mode generates html with no static content

### ISSUE THREAD

**Issue by Magnum5234** [nuxt/nuxt.js#4487]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[generate --spa](generate --spa)

### Steps to reproduce

Run ```generate --spa``` to produce static html files

### What is expected ?

html files with static pre rendered content for seo, bots, etc...

### What is actually happening?

html files generated only contains the minimal basic of javascript files.

### Additional comments?

This is a little confusing to me. And it seems that this is not fully documented. I've seen #4036 #2472. But I'm not really sure what to make of this.

Apparently you need the ssr to generate the html files with static pre rendered content? 
Static html files with static pre rendered content - that for me was the main pitch using nuxt. But that is barred behind the build mode settings without an explanation. Maybe consider adding an option to generate pre rendered content which can then throw an error if used in conjunction with spa mode.

Please clarify :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8272">#c8272</a>)</em></sub></div>

**Comment by xjinza** [comment]
I have the same problem ,when I use the mode 'univesal', the page of js can not worked

**Comment by xjinza** [comment]
I have resolve this problem ,this is my nuxt.config.js 
```
  router: {
    mode: 'hash',
    base: '/dist/'
  },
  mode: 'universal',
```

**Comment by manniL** [comment]
You probably just want `nuxt generate`, don't you? 🤔

**Comment by xjinza** [comment]
yes, ssr consume more server resource，I want prerender html as a skeleton when build app.
but call api in client not server.

**Comment by xjinza** [comment]
right,it works well for me
