### ISSUE TITLE
使用axios网络请求库的时候，如何向后端服务器传递header信息呢？客户端向服务器端发网络请求可以向后端传递header信息，服务端渲如何才能想客户端那样传递header信息

### ISSUE THREAD

**Issue by pingzidong** [nuxt/nuxt.js#4488]

**Comment by pingzidong** [comment]
![image](https://user-images.githubusercontent.com/12740207/49588395-89b21380-f9a1-11e8-8b47-121c2d194520.png)

**Comment by yoyo837** [comment]
改写你的ajax 封装，从context拿header

**Comment by yoyo837** [comment]
浏览器 -> node.js server -> backend server,  第一步浏览器传递的东西都在context里
