### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by Romick2005** [nuxt/nuxt.js#4490]
### What problem does this feature solve?

Hi I spend an hour to discover that I have a problem in nuxt buildDir config. (When I started app from webstorm it works, but when via pm2 it doesn't not say anything just do not work). So I have hard times to debug it. First I discovered there are endless loop in page render `await renderRoute(url, context)` and then finally discover that vue-renderer silently exits here:

@nuxt/vue-renderer/dist/vue-renderer.js

```js
      if (!_fs.existsSync(_path)) {
        // TODO: Enable baack (back) when renderer initialzation was disabled for build only scripts
        // Currently this breaks normal nuxt build for first time
        // if (!this.context.options.dev) {
        //   const invalidSSR = !this.noSSR && key === 'serverBundle'
        //   const invalidSPA = this.noSSR && key === 'spaTemplate'
        //   if (invalidSPA || invalidSSR) {
        //     consola.fatal(`Could not load Nuxt renderer, make sure to build for production: builder.build() with dev option set to false.`)
        //   }
        // }
        console.log("Could not load Nuxt renderer, make sure to build for production: builder.build() with dev option set to false.");// I added this
        return // Resource not exists
      }
```

Can you please add some console message here just to quicker identify the problem OR even better solution could be add else here:

```js
    if (updated.length > 0) {
      this.createRenderer();
    } else {
      console.warning("Erorr empty resourceMap. Please check your build dir etc.");
    }
```

This simple additional logging will help people a lot in finding bugs.

PS Thank you for your awesome work! It is really cool guys!

### What does the proposed changes look like?

Add some minor warning or errors logging.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8276">#c8276</a>)</em></sub></div>

**Comment by pi0** [comment]
@Romick2005 Warning is added in `nuxt-edge`. Will be improved in next release :)

**Comment by Romick2005** [comment]
Thank you @pi0!
