### ISSUE TITLE
Property or method is not defined on the instance but referenced

### ISSUE THREAD

**Issue by webkws** [nuxt/nuxt.js#4499]
An error happened in nuxt.js called nested-components example:
`[Vue warn]: Property or method "title" is not defined on the instance but referenced during render`

Version
`nuxt-edge`

link
https://github.com/nuxt/nuxt.js/tree/dev/examples/nested-components

Steps to reproduce
yarn run dev

What is expected ?
no error

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8284">#c8284</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Really wrong.
Missing `props` option.

I created a PR for this
