### ISSUE TITLE
Nuxt renderer says - renderToString is not a function

### ISSUE THREAD

**Issue by thetutlage** [nuxt/nuxt.js#45]
I have trying to make use of the method called `nuxt.renderRoute` which indeed calls `renderToString` which throws an error saying `TypeError: self.renderToString is not a function`.

All I have able to debug is

1.`renderToString` is a function on vue-server-renderer https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer

2. When calling this method, you pass it the context of `Nuxt` class and `Nuxt` class does not have `renderToString` method.

May be I am missing something?

**Comment by Atinux** [comment]
Hi @thetutlage 

Can you update `nuxt` to use the version `0.8.2` and make sure to use it like this:

```js
const Nuxt = require('nuxt')
const nuxt = new Nuxt()
nuxt.build()
.then(() => {
  // here you can use nuxt.renderRoute() or nuxt.render(req, res)
})
```

You can see an example here: https://gomix.com/#!/project/nuxt-body-params

Can you give us an snippet of your code?

**Comment by thetutlage** [comment]
Closing, since it seems to be working fine 😄
