### ISSUE TITLE
How do I force refresh a component  from a function?

### ISSUE THREAD

**Issue by tenjojeremy** [nuxt/nuxt.js#450]
![error](https://cloud.githubusercontent.com/assets/25231946/24327678/4d5af70c-11a5-11e7-995c-eb867be6876d.PNG)

I tried this 3 methods but they did not work.

Please help,

Thank you

**Comment by ausir0726** [comment]
I suggest you need rewrite your jquery code translate to vue event handler will be easier update state and reset your model form .
https://vuejs.org/v2/guide/events.html#Event-Modifiers

**Comment by tenjojeremy** [comment]
My workaround was crating a page that redirects me to my previous page.

Thank you for your suggestion.  @ausir0726
