### ISSUE TITLE
SCSS sourcemap in 0.10.0 version

### ISSUE THREAD

**Issue by msudgh** [nuxt/nuxt.js#451]
Is there any configuration to enable scss sourcemap in 0.10.0 version of nuxt.js?

**Comment by Atinux** [comment]
Can you give us a code example so we can reproduce what you are expecting @msudgh?

**Comment by Atinux** [comment]
@msudgh @uptownhr can you try this:

`nuxt.config.js`
```js
module.exports = {
  build: {
    extend (config) {
      let vueLoader = config.module.rules.find((rule) => rule.loader === 'vue-loader')
      for (let key in vueLoader.query.loaders) {
        vueLoader.query.loaders[key] = vueLoader.query.loaders[key].replace('css-loader', 'css-loader?sourceMap')
      }
    }
  }
}
```

**Comment by msudgh** [comment]
Thanks, It works but I think the path that was returned isn't nice. [Screenshot]
In the above screenshot It would be great if you return a **relative** path like **`./cynthia-mobile/components/searchbar/index.vue`**.
Is it possible?


![screenshot_20170401_185319](https://cloud.githubusercontent.com/assets/11756815/24579556/1b76a23c-170d-11e7-8dc2-06c173035ec7.png)

**Comment by Atinux** [comment]
This we can't control it since it's related to vue-loader and Chrome.

**Comment by uptownhr** [comment]
@Atinux thank you

**Comment by doriandrn** [comment]
@msudgh +1 for that
@Atinux This way, when building, the sourcemaps also get included in the bundle. Is there a flag one could use to have the sourcemaps loaded for the dev environment only?

**Comment by uptownhr** [comment]
Haven't tried yet but isClient should be available

**Comment by doriandrn** [comment]
@uptownhr That doesn't seem to relate with the dev environment at all, does it? Sourcemaps in this scenario will still be bundled in the client version, right? I want it not to bundle when running 'build' or 'generate' for example.

**Comment by uptownhr** [comment]
Oops. Then you can use the isDev flag.

**Comment by doriandrn** [comment]
@uptownhr Cheers, missed that entirely.
