### ISSUE TITLE
dev mode throws 404 for fonts if build.cache is enabled

### ISSUE THREAD

**Issue by sh** [nuxt/nuxt.js#4513]
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://github.com/sh/nuxt-webpack-dev-cache-bug](https://github.com/sh/nuxt-webpack-dev-cache-bug)

### Steps to reproduce

Version is nuxt-edge@2.4.0-25740740.f0cb654

Set `build.cache` to `true`

1. `yarn install`
2. `yarn dev`
3. open http://localhost:3000 - check icon is shown
4. `ctrl + c ` - stop dev server
5. `yarn dev` - start dev server
4. open http://localhost:3000 - check icon is not shown (disable cache in network dev tools)

### What is expected ?

Restarting with `ctrl + c` + `yarn dev` shows fa-check icon

### What is actually happening?

`http://localhost:3000/_nuxt/assets/fonts/fontawesome-webfont.woff2` returns `404 (Not Found)`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8289">#c8289</a>)</em></sub></div>

**Comment by djune** [comment]
I have the issue too.

**Comment by jiaen188** [comment]
same issue.

**Comment by manniL** [comment]
So, the `cache-loader` picks up the font. Not a webpack expert but will look into it

cache json:
```json
{
  "remainingRequest": "/path/to/project/node_modules/url-loader/dist/cjs.js??ref--12-1!/path/to/project/assets/fonts/fontawesome-webfont.ttf?v=4.7.0",
  "dependencies": [
    {
      "path": "/path/to/project/assets/fonts/fontawesome-webfont.ttf",
      "mtime": 1547288783214
    },
    {
      "path": "/path/to/project/node_modules/cache-loader/dist/cjs.js",
      "mtime": 1546815407403
    },
    {
      "path": "/path/to/project/node_modules/url-loader/dist/cjs.js",
      "mtime": 1542479008617
    }
  ],
  "contextDependencies": [],
  "result": [
    "module.exports = __webpack_public_path__ + \"assets/fonts/fontawesome-webfont.ttf\";"
  ]
}
```

**Comment by stevefan1999-personal** [comment]
Was also seeing the same thing, probably this is why my Element-UI fonts aren't loading.
