### ISSUE TITLE
head script InnerHTML encoded like html escape

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxt.js#452]
I have some issue about `nuxt.config.js` write head.script

I need write some code in head script , like define a object .
so I find how to setting on vue-meta ( use innerHTML )
https://github.com/declandewet/vue-meta#script-object

in my html , I got my code like it escape html .
maybe for some security reason  . 
but , I can't find some information can disable it .
( vue-meta just use single quote in innerHTML )

Would someone know this and give me a reference , thanks. 

![capture](https://cloud.githubusercontent.com/assets/7247064/24330526/8ac73e2c-1252-11e7-93cf-65801a416ad2.PNG)

**Comment by alexchopin** [comment]
Hi @ausir0726,
Have you tried to do it with an `app.html` document?
[Nuxt.js Documentation](https://nuxtjs.org/guide/views#document)

**Comment by ausir0726** [comment]
@alexchopin  I think modify app.html will be work .

but I just don't want modify template .
because vue-meta already provide innerHTML attribute .
It just escaped html . ( but vue-meta doesn't )

just want find some way to resolve this escape situation .

**Comment by ausir0726** [comment]
I tried write template app.html file 
it works for me  .

but if possible let me know how to write innerHTML in `nuxt.config.js` without escape .
thanks !

**Comment by alexchopin** [comment]
@ausir0726, I tried with:
```js
 script: [
   {
     innerHTML: `
     var a = 'abc';
     console.log(a);
     `
   }
 ],
 __dangerouslyDisableSanitizers: ['script']
```
and it works fine.

**Comment by ausir0726** [comment]
sorry @alexchopin  waste for your time .
I also find the answer after your response 
[Where should I put the inline script? #226](https://github.com/nuxt/nuxt.js/issues/226)

add this reference for some one landing this page .
