### ISSUE TITLE
loading a css file from assets in NUXT layout

### ISSUE THREAD

**Issue by xxyyzz2050** [nuxt/nuxt.js#4526]
layouts/default.vue :
```
<script>
export default{
  head: { link: [ { rel: 'stylesheet', href: '~assets/style.css' } ] ,
}
}
</script>
```

the above code generates:
`<link href="~assets/style.css" />`
which is not accessable 

navigating to http://localhost/_nuxt/assets/style.css fail, but http://localhost/_nuxt/assets/photo.jpg success

**Comment by ricardogobbosouza** [comment]
You should use `css` property in` nuxt.config.js`

https://nuxtjs.org/api/configuration-css#the-css-property
