### ISSUE TITLE
How can I get vuex stroe in a noramal js file?

### ISSUE THREAD

**Issue by zhangcanfeng612** [nuxt/nuxt.js#4533]
I am a newbie. I have a problem that has been bothering me for a long time. Trouble can help me answer it. Thanks~ The following is the wrong code, I don't know how to do it.
```
import { state } from '@/store/index.js';
export default {
  getState () {
    console.error(state);
  },
};
```

**Comment by ricardogobbosouza** [comment]
See https://github.com/nuxt/nuxt.js/issues/2005#issuecomment-341306250
