### ISSUE TITLE
ReferenceError: error is not defined

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt.js#4539]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/nuxt/nuxt.js/blob/657a6cc7c99f81b93dcd75f2be5baad0a1e35374/packages/vue-app/template/client.js#L149](https://github.com/nuxt/nuxt.js/blob/657a6cc7c99f81b93dcd75f2be5baad0a1e35374/packages/vue-app/template/client.js#L149)

### Steps to reproduce

Not sure

### What is expected ?

To actually emit a `routeChange` event

### What is actually happening?

A ReferenceError is thrown.

### Additional comments?

`error` should be `err`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8298">#c8298</a>)</em></sub></div>

**Comment by manniL** [comment]
Please add reproduction (template: https://template.nuxtjs.org/)

**Comment by aldarund** [comment]
It was fixed weeks ago, use latest release :)

**Comment by manniL** [comment]
rel: https://github.com/nuxt/nuxt.js/pull/4444

**Comment by luminous8** [comment]
Hello,

I have this issue with Nuxt.js v2.3.4

**Comment by manniL** [comment]
@luminous8 Create a new issue then.
