### ISSUE TITLE
Middleware Ajax Request doesn't send up cookies?

### ISSUE THREAD

**Issue by Tibfib** [nuxt/nuxt.js#454]
Hello everyone! I'm absolutely loving using nuxtjs for my vue app. It's been awesome so far. Thanks for the hard work!

I seem to have run into a bug or maybe I'm misunderstanding how the middlewares should work. The documentation indicates that I can return a promise in a middleware. 

Here's what my middleware looks like. I'm using secure cookies in my app which are not accessible via JavaScript, so, the only way to check if a user is authenticated is by hitting the server. This midleware will check the authentication using my vuex method `getSignedInUser`. 
```javascript
// Middleware
export default function({ store, redirect }) {
    // If the user is not authenticated
    console.log('is authenticated?');
    if (!store.getters.isAuthenticated) {
        if (!store.getters.hasCheckedForAuthentication) {
            return new Promise((resolve, reject) => {
                store
                    .dispatch('getSignedInUser')
                    .then(() => resolve())
                    .catch(() => redirect('/admin/login'));
            });
        } else
            return redirect('/admin/login');
    }
}
```
(yeah, I know I probably don't have to wrap my promise in another promise–was trying to debug)

The ajax request is super simple. I use axios with `withCredentials: true`.

```javascript
// Get Signed in User
function getSignedInUser() {
    console.log('Send up ajax request');
    return axios.get('/api/v1/admin/user');
}
```

In the end, there's no ajax request in Chrome:
![image](https://cloud.githubusercontent.com/assets/290380/24331275/991f0b84-11e5-11e7-85af-fe97c4b57a4e.png)

However, I know it's hitting the server, because the logs are coming through. 
![image](https://cloud.githubusercontent.com/assets/290380/24331302/58b00a7a-11e6-11e7-8641-a2dc9e95abf7.png)

When I run the exact same vuex action from a vue method, it works. 

```javascript
isSignedIn() {
    this.$store.dispatch('getSignedInUser');
 }
```
![image](https://cloud.githubusercontent.com/assets/290380/24331328/a4da525c-11e6-11e7-8b6a-75ed009e8685.png)

So am I missing something? How can I get nuxt.js to send up the actual ajax request with the cookie during the middleware? Or should I change my strategy for authentication? I'd like to continue to use secure cookies (to protect against possible XSS attacks).

Thanks!

UPDATE: I just noticed that this issue ONLY occurs when I directly load the page with the middleware. For example, I run this middleware on the `/admin` page. If I directly go to `localhost:3000/admin`, the issue I spoke of above occurs. However, if I add a `nuxt-link` to my home page, linking to the `/admin` page and go to the page by clicking on the link, this issue doesn't occur.

**Comment by Atinux** [comment]
Where do you use this middleware exactly? nuxt.config.js, layout or page?

**Comment by Atinux** [comment]
On the server side, you need to give the full URL to axios because he doesn't know which host to call.

**Comment by Tibfib** [comment]
Sorry, this is a page middleware. My home page (`/`) does not have any middlewares. If I click on a nuxt-link to `/admin` from the homepage, the middleware runs properly, sending up the request with the cookie. However, if I type in `localhost:3000/admin` into the address bar, the middleware does not run properly (the cookie isn't sent up. it doesn't even seem to be a true ajax request). 

BTW, I am giving the full url to axios. I used the nuxtjs+express template to get started:

```javascript
import axios from 'axios';

let options = {
    withCredentials: true
};
// The server-side needs a full url to work
if (process.SERVER_BUILD) {
    options.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`;
}

export default axios.create(options);
```

**Comment by Tibfib** [comment]
Was a fix for this made? Why was it closed?

**Comment by tonylampada** [comment]
I just ran into this same issue. Thanks @Tibfib for doing such a great job describing the scenario so I don't have to.

@alexchopin care to elaborate why this issue was closed?

@Tibfib did you find a solution for this?

**Comment by Tibfib** [comment]
@tonylampada good to hear that someone else has experienced this! It's a pretty annoying bug. I never found a solution. I had to add some code to my `mounted()` function that simulates the middleware. Ugly, but it kind of works :/...

**Comment by pi0** [comment]
Please consider that for CORS requests, API side should also accept cross origin credentials. [Access-Control-Allow-Credentials Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials)

**Comment by Tibfib** [comment]
@pi0, yeah I don't think this has anything to do with CORS. The issue is that the middleware http request doesn't send up cookies when the page with the middleware is the first one loaded. Running the exact same request outside of a middleware works perfectly. It also works if you load a different page and then navigate to the page with the middleware.

**Comment by Atinux** [comment]
@Tibfib if you go directly to `localhost:3000/admin`, the middleware is **run on the server-side**.

Sadly, no cookies are store on the server so the request is made without cookies in the header. It's a difficult solution when working with SSR.

One solution is to check if the user is connected via `req.session` directly in your middleware if `req` exists, if not, make the Ajax request.

**Comment by Tibfib** [comment]
@Atinux oh, that makes sense. But if I navigate from `localhost:3000` to `localhost:3000/admin` within the app, the middleware is run client-side, right? Is this how it has to be or was it designed that way? That seems confusing :/. Could both not be client-side? or both be server-side? Could it be specified in the middleware?

Thanks for the info!

**Comment by Atinux** [comment]
I believe this schema is the one that represents the better how middleware works in Nuxt.js:

![Nuxt schema](https://nuxtjs.org/nuxt-schema.png)

You can use `context.isServer` to check it the middleware is run from server-side or client-side.

**Comment by tonylampada** [comment]
I found a workaround for this that seems pretty neat to me.

I was trying to use an `auth.js` middleware to save the logged user object in the store.
For that, I make an AJAX call to `/api/whoami` and the backend uses cookies to decide whether the user is logged or not.
So this approach has the issue described by @TibFib (things only work when the middleware is ran on the client)

**middleware/auth.js**

```
import AppApi from '~apijs'

export default function (ctx) {
    return AppApi.whoami().then((response) => {
        if(response.data.authenticated){
            ctx.store.commit('SET_LOGGED_USER', response.data.user);
        } else {
            ctx.store.commit('SET_LOGGED_USER', null);
        }
    });
}
```

Then I tried adding anothe middleware on `nuxt.config.js`, to configure axios to "forward" all headers (including cookies) to the backend:

```
  router: {
    middleware: ['fwdcookies', 'auth'],
  },
```

**middleware/fwdcookies.js**

```
import axios from '~/plugins/axios';

export default function (ctx) {
    if(ctx.isServer){
        Object.keys(ctx.req.headers).map((key)=>{
            axios.defaults.headers.common[key] = ctx.req.headers[key];
        });
    }
}
```

And it freaking works!

@Atinux do you foresee any problems doing that? Do you think that's a good solution?

**Comment by Atinux** [comment]
@tonylampada this is awesome, I don't see any problem right now.

Keep in mind that if you have access to `ctx`, then you can check directly `req.session` and know it the user is connecter or not in your app :)

**Comment by chuckyo** [comment]
@tonylampada your solution is really amazing for me, thanks for save my time. But there was a small revision for my case.

When I try to fetch users' profile using `axios` in the server side I met such error `Error: Request failed with status code 404`, with a lot try I found `unexpected headers param` cause the issue, so I use the below code
```
Object.keys(ctx.req.headers).map((key)=>{
  if (key === 'cookie') {
    axios.defaults.headers.common[key] = ctx.req.headers[key];
  }
});
```

**Comment by acidjazz** [comment]
@tonylampada excellent work, here's my version:

`control/store/index.js`

```js
import Vuex from 'vuex'

const store = () => new Vuex.Store({
  state: {
    user: null
  },
  mutations: {
    SET_USER (state, user) {
      state.user = user || null
    }
  },
  getters: {
    isAuth (state) {
      return !!state.user
    },
    getUser (state) {
      return state.user
    }
  }
})

export default store
```

`control/middleware/cookies.js`

```js

import axios from '~/plugins/axios.js'

export default function (ctx) {
  if (ctx.isServer) {
    axios.defaults.headers.common['cookie'] = ctx.req.headers.cookie
  }
}
```

`control/middleware/auth.js`

```js
import axios from '~/plugins/axios.js'

export default function (ctx) {
  return axios.get('/me').then((response) => {
    if (response.data.data.id) {
      ctx.store.commit('SET_USER', response.data.data)
      return true
    }
    ctx.store.commit('SET_USER', null)
  }).catch((error) => {
    ctx.redirect('/')
  })
}
```

@Atinux Might be pretty helpful to see this kind of example in the documentation or something similar to your auth0 example? I was really at a loss for a while until I stumbled across this issue.

**Comment by Atinux** [comment]
@acidjazz could you try by using [axios-module](https://github.com/nuxt-community/axios-module) without using `middleware/cookies.js`?

This module handle `credentials` and it should not require any specific middleware.

**Comment by acidjazz** [comment]
@Atinux i never knew about this, glad to!

**Comment by tonylampada** [comment]
@Atinux @acidjazz @chuckyo 

**Please BEWARE, there's a serious security problem with my solution above!!!**

I started to notice a strange behaviour in production: **some users were unintentionally impersonating others** - the cause was my "solution" above. I was able to track it down with some additional debug information like so:

**middleware/fwdcookies.js**

```
import axios from '~/plugins/axios';

export default function (ctx) {
    if(ctx.isServer){
        console.log('---------- fwdcookies -------------')
        console.log(axios.defaults.headers.common)
        Object.keys(ctx.req.headers).map((key)=>{
            axios.defaults.headers.common[key] = ctx.req.headers[key];
            console.log(key + ' = ' + ctx.req.headers[key]);
        });
    }
}
```

Then when accessing the app for the first time as an authenticated user, the output from conosle.log is:

```
---------- fwdcookies -------------
{ Accept: 'application/json, text/plain, */*' }
host = evolutio:3000
connection = close
cache-control = max-age=0
upgrade-insecure-requests = 1
user-agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
accept = text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding = gzip, deflate, sdch
accept-language = en-US,en;q=0.8,pt;q=0.6
cookie = A LOT OF COOKIES HERE...;
if-none-match = W/"36022-fEPb7HVUEYdxaznhnuYioP702+s"
```

Then, I open a new incognito browser window (unautheticated), and the output is:

```
---------- fwdcookies -------------
{ Accept: 'application/json, text/plain, */*',
  host: 'evolutio:3000',
  connection: 'close',
  'cache-control': 'max-age=0',
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'accept-encoding': 'gzip, deflate, sdch',
  'accept-language': 'en-US,en;q=0.8,pt;q=0.6',
  cookie: 'A LOT OF COOKIES HERE...'
  'if-none-match': 'W/"36022-fEPb7HVUEYdxaznhnuYioP702+s"' }
host = localhost:3000
connection = keep-alive
upgrade-insecure-requests = 1
user-agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
accept = text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding = gzip, deflate, sdch
accept-language = en-US,en;q=0.8,pt;q=0.6
```

As you can see, the state previously saved on `axios.defaults.headers.common` was preserved between calls of different users. In the unauthenticated browser window I was in fact seeing the application as a logged user (yikes!)

I'm really sorry about that. If you're using the same kind of approach, please check your code if you're vulnerable. I'll be posting a workaround for it very soon.

**Comment by tonylampada** [comment]
So, simply resetting `axios.defaults.headers.common` in the middleware fixes the problem above:


**middleware/fwdcookies.js**
```
import axios from '~/plugins/axios';

export default function (ctx) {
    if(ctx.isServer){
        axios.defaults.headers.common = {}
        Object.keys(ctx.req.headers).map((key)=>{
            axios.defaults.headers.common[key] = ctx.req.headers[key];
        });
    }
}
```

**Comment by pi0** [comment]
> So, simply resetting axios.defaults.headers.common in the middleware fixes the problem above:

@tonylampada This is exactly what was fixed in axios module sience 4.x. Actually there are shared headers more than **common** too. [source](https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.template.js#L110).

So this is why strongly suggested using provided [axios-module](https://github.com/nuxt-community/axios-module) instead of custom implementations. There may be still or future potential leaks like this to be patched for all of users.

**Comment by tonylampada** [comment]
@pi0

Absolutely. Thanks for the info

**Comment by stecapra** [comment]
Hi,
if i have this nuxt.config.js
```
/*
   *  Modules
   */
  modules: [
    '@nuxtjs/axios',
  ],
  /*
  ** Plugins
  */
  plugins: '~/plugins/vendorPlugins/axios',
  /*
  ** Middleware
   */
  router: {
    middleware: ['fwdcookies', 'auth'],
  }
```
Then, `~/plugins/vendorPlugins/axios'` :
```
export default function (ctx) {
}
```
`fwdcookies` middleware like this:
```
export default function ({req, app}) {
  if (process.server) {
    app.$axios.defaults.headers.common = {}
    Object.keys(req.headers).map((key) => {
      app.$axios.defaults.headers.common[key] = req.headers[key];
    });
  }
}
```

My auth middleware is:
```
export default async function ({ req, app, route, redirect, store, $axios }) {
  let response = await app.$axios.$get('http://192.168.1.20:3333/test')
  console.log(response)
}
```
Why am i getting the same error exposed above? (response is always like the user is not logged, but in mounted function is logged)

Thank you very much for your patience
