### ISSUE TITLE
nuxt generate produces really unexpected result when using */index.html URLs

### ISSUE THREAD

**Issue by saintech** [nuxt/nuxt.js#4540]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/nuxt/codesandbox-nuxt](https://github.com/nuxt/codesandbox-nuxt)

### Steps to reproduce

1. `git clone https://github.com/nuxt/codesandbox-nuxt/`
2. `cd codesandbox-nuxt`
3. add code to pages/about.vue component:  `mounted() { console.log('JS CHECK') }`
4. `npm i`
5. `npm run generate`
6. `npm install http-server`
7. `npx http-server dist`
8. open http://localhost:8080/about/index.html

### What is expected ?

Working app or error message.

### What is actually happening?

Nothing!

### Additional comments?

I spent a 1.5 day trying to get a dependency for some dynamic functionality to work. When everything else was working fine, including `npm run dev`. One error message in console would be enough...

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8299">#c8299</a>)</em></sub></div>

**Comment by manniL** [comment]
This is not the case anymore :relaxed:

**Comment by magicka001** [comment]
Is this problem solved？

**Comment by Italic-2012** [comment]
Why js dose not work ？

**Comment by Italic-2012** [comment]
Why js does not work ？

**Comment by saintech** [comment]
> Is this problem solved？

No, absolutely the same behavior. Steps to reproduce from the beginning are actual.
