### ISSUE TITLE
Error when importing node-sass

### ISSUE THREAD

**Issue by fmay** [nuxt/nuxt.js#4541]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/ojwoqvvk69](https://codesandbox.io/s/ojwoqvvk69)

### Steps to reproduce

I need to run node-sass to compile some scss my users enter within the application itself. Initially I got a bunch of unresolved 'fs' errors which I resolved by adding a webpack config.node = { fs: 'empty' } in nuxt.config.js.

### What is expected ?

import sass from 'node-sass' should work

### What is actually happening?

I get the following error

```
WARNING  Compiled with 1 warnings                                                                                     8:01:30 AM
warning  in ./node_modules/node-sass/lib/binding.js
Critical dependency: the request of a dependency is an expression
```

### Additional comments?

The error happening in the codesandbox is not identical but it's the same thing. Ultimately, as long node-sass imports, great! Thanks.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8300">#c8300</a>)</em></sub></div>

**Comment by mrkstwrt** [comment]
node-sass isn't written to work in the browser. Your best bet is probably something like this https://github.com/medialize/sass.js/

**Comment by manniL** [comment]
Closed based on @mrkstwrt's comment
