### ISSUE TITLE
Nuxt router not updating inside docker container when new page is added

### ISSUE THREAD

**Issue by ko1eda** [nuxt/nuxt.js#4543]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/ko1eda/nuxt-issue](https://github.com/ko1eda/nuxt-issue)

### Steps to reproduce

1. Clone the repository
2. Edit the docker-compose volume mount to point to the nuxt application directory on your local machine
3. Run ```docker-compose run --rm vuejs npm install```
+ this will install the node_modules directory in a named volume (this was to avoid issues with npm that I was having -- see here https://github.com/sass/node-sass/issues/252)
4. Run ```docker-compose up```
5. Create a new .vue file inside the pages/ directory
6. Navigate to that newly created page in the browser

### What is expected ?

The router.js should update to contain the newly created route on the fly.

### What is actually happening?

The route is never added to router.js resulting in a page not found. It will only create the new route if the container is rebuilt.

### Additional comments?
Note: i am running docker for windows. 

Also If I run npm run dev on my local machine outside of docker and add a new page to /pages the router is instantly updated. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8301">#c8301</a>)</em></sub></div>

**Comment by aldarund** [comment]
https://github.com/nuxt/nuxt.js/issues/3887

**Comment by lafllamme** [comment]
thank me later guys

add this to nuxt.config.ts

specify your containers host
```
//fix issue for docker not reflecting changes
  vite: {
    server: {
      host: true,
      port: 3000,
      watch: {
        usePolling: true,
      },
    },
  }
```
alternative:
```
 //fix issue for docker not reflecting changes
  vite: {
    server: {
      watch: {
        usePolling: true,
        interval: 100, // Poll files every 100ms
      },
    }
  }
```
