### ISSUE TITLE
Need a way to use static resources with router.base

### ISSUE THREAD

**Issue by Loilo** [nuxt/nuxt.js#4544]
### What problem does this feature solve?

Currently, there's no (documented) way to properly use static assets in sites deployed by Nuxt's `generate` command when the `router.base` coption is set to something other than `/`. Resources requested as `~/path/to/resource` are correctly rewritten to `[router.base]/path/to/resource`. Unfortunately, there's no equivalent to that for static resources requested as `/resource`.

---

The real-world situation is simple:
* We develop a site locally under `http://localhost:3000/`.
* We want to deploy it as a static site to `https://our-site.com/demo`, so in production it gets the `router.base` option set to `/demo`.

Therefore in local development all static resources should point to `/` whereas in production they should point to `/demo/`.

I have created [a minimal repro](https://github.com/Loilo/repro-nuxt-static-base) that explains this by example, much better than I could do here in words.

To kickstart the repro, just run:
```bash
npx github:Loilo/repro-nuxt-static-base
```

---

I believe this is the same issue that has been brought up in #2753.
It has been addressed with the introduction of the `render.static.prefix` option in #2755 which is however completely undocumented and it's unclear to me how it may solve the issue.

### What does the proposed changes look like?

If the `render.static.prefix` option is actually able to solve this (which I think it's meant to be), it should be documented.

Otherwise, an additional `render.static.*` option could be introduced to control rewriting requests to static resources.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8302">#c8302</a>)</em></sub></div>

**Comment by manniL** [comment]
added an issue in the docs repo to document the `render.static.prefix` property.

You can set that one to true to move the `static` contents directly to the `router.base`.

`nuxt.config.js`
```js
export default {
 router: { base: '/t' },
 render: { static: { prefix: true} }
}
```

`/favicon.ico` => `/t/favicon.ico`

**Comment by manniL** [comment]
**Caveat**: `<img src="/a.jpg">` *will not* be rewritten to `/t/a.jpg`

**Comment by manniL** [comment]
@Loilo Thanks for sharing! :+1: 

Small suggestion: You could use `env` to make the static path available in Vue components too so you don't have the "burden" of a global mixin :relaxed:

**Comment by JJCLane** [comment]
Just for reference, I've solved this by accessing the base option through the router like so, which seems to achieve the same thing:

`<img
        :src="$router.options.base + $t('footer.logo.src.desktop')"
        :alt="$t('footer.logo.alt')"
      />`

**Comment by altusgerona** [comment]
Is there a way for dynamic routes to be cleanly handled by `~static`? It's ugly to have to get the base path every time especially if we have to switch from "/" to "/something" back and forth.

**Comment by Kyserbyte** [comment]
Hi,
my solution for the "dynamics URL" was to create a plugin that inject an utility function on every components that is capable to solve the base path.
Like this:

_@/plugins/utils.js_
```
export default ({ app }, inject) => {
    inject('_r', (url) => {
        if (url.charAt(0) === '/') {
            return app.router.options.base + url.substr(1);
        }
        return url;
    });
}
```

adding this as a plugin in you _nuxt.config.js_ like:
```
plugins: [
        ...
        { src: "@/plugins/utils.js" }
    ],
```

and using it in your page/components like:
```
:src="$_r('/img/bg-our-communities.png')"
```

Of course you can rename the injected function as you like. 
It operate only with absolute URL, avoiding changes on relative URL.

@altusgerona it could be useful for you

**Comment by altusgerona** [comment]
Thanks @Kyserbyte. Will look into implementing this on future projects. I still hope that Nuxt can provide a cleaner solution for this.

**Comment by kazomotos** [comment]
Same issue here. My hole app keeps loading because I get a 404 on the _nuxt folder. Is there any solution?

**Comment by yaeru** [comment]
Same problem

**Comment by mrleblanc101** [comment]
@manniL I created a minimal CodeSandbox.
Only 2 things I did in the `nuxt.config.json`.
1) Added `target: "static"`
2) Added `router.base: "/t/"` like in your exemple.

The link to the favicon doesn't get the `router.base` appended even if `render.static.prefix` is true by default.

**Comment by Dtphelan1** [comment]
> @manniL I created a minimal CodeSandbox. https://codesandbox.io/s/stoic-borg-d8t7ck?file=/nuxt.config.js Only 2 things I did in the `nuxt.config.json`.
> 
>     1. Added `target: "static"`
> 
>     2. Added `router.base: "/t/"` like in your exemple.
> 
> 
> The link to the favicon doesn't get the `router.base` appended even if `render.static.prefix` is true by default. ![Capture d’écran, le 2022-06-13 à 19 15 34](https://user-images.githubusercontent.com/17392251/173462766-4b4ae56d-ebe1-416d-9999-6178403afa3e.png)

I was encountering an identical issue, and was able to fix it by **removing the leading slash from the favicon's href**. That is, the head in `nuxt.config.js` should be: 
```
  head: {
    title: "Nuxt.js starter for CSB",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        hid: "description",
        name: "description",
        content: "Official Nuxt.js starter for CodeSandBox"
      }
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "favicon.ico" }] // **Removed the leading slash here**
  },
```
