### ISSUE TITLE
Analyze not generating stats with create-nuxt-app adonis

### ISSUE THREAD

**Issue by blowsie** [nuxt/nuxt.js#4545]
### Reproduction link

[https://github.com/blowsie/nuxt-vuetify-adonis](https://github.com/blowsie/nuxt-vuetify-adonis)

### Steps to reproduce

- create-nuxt-app with adonis and vuetify
- add `analyze: true` to build config

### What is expected ?

to see stats

### What is actually happening?

no stats generated

### Additional comments?

I tried for over an hour to get a reproduction working on codesanbox but i couldnt get it to work
https://codesandbox.io/s/p2rv8l7ky7

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8303">#c8303</a>)</em></sub></div>

**Comment by blowsie** [comment]
The example repo uses nuxt edge, but i have confirmed the same issue is present in     "nuxt": "^2.3.4",

**Comment by manniL** [comment]
Can't reproduce.

Steps I took:

1. Build a fresh app via create-nuxt-app and chose adonis
2. added `build.analyze` to the nuxt config
3. ran yarn build

![image](https://user-images.githubusercontent.com/640208/50734920-61832380-119e-11e9-9365-9e4c47dad9fb.png)

Stats are present.
