### ISSUE TITLE
Default layout always loaded

### ISSUE THREAD

**Issue by kamontat** [nuxt/nuxt.js#4549]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/kamontat/Portfolio/blob/dev/pages/cms/net/index.vue](https://github.com/kamontat/Portfolio/blob/dev/pages/cms/net/index.vue)

### Steps to reproduce

1. Create default layout with some css (called `default.vue`)
2. Create another layout with NO css (called `empty.vue`)
3. Create pages that load `empty` layout
4. inspect the html result

### What is expected ?

no css from default.vue file

### What is actually happening?

It still load css from default.vue file

![Screen Shot 2018-12-13 at 21.33.40.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/7459dd90-ff16-11e8-940f-6971a3833a5e.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8305">#c8305</a>)</em></sub></div>

**Comment by IPRIT** [comment]
Did you try?
```
    splitChunks: {
      layouts: true,
      pages: true,
    },
```

**Comment by kamontat** [comment]
No luck

<img width="505" alt="screen shot 2018-12-15 at 14 40 11" src="https://user-images.githubusercontent.com/14089557/50043596-5fceb000-0077-11e9-9d5f-f0d8ae0a3f60.png">

**Comment by kamontat** [comment]
I think the problem is resolved. but I don't know why.
