### ISSUE TITLE
nuxtServerInit or fetch behaviour with req.vars

### ISSUE THREAD

**Issue by josantana** [nuxt/nuxt.js#455]
I'm using Passport.js for authentication. A variable is set on req, named `req.user`, containing the user data.

As follows, here it is the original `store.js`:

```
const nuxtServerInit = ({ commit }, { req }) => {
    if (req.user) {
        commit('SET_USER', req.user); // I got the user data, as expected
    }
};
```

But I need to get more data on every page. I think the `nuxtServerInit` method is the ideal location for that. So again on `store.js`:

```
const nuxtServerInit = async ({ commit }, { req }) => {
    if (req.user) {
        commit('SET_USER', req.user);
        let { data } = await axios.get('/api/account'); // To get more user related data, from another database table...
    }
};
```

On `server.js`:

```
app.get('/api/account', (req, res) => {
    console.log(req.user); // Just a test...
    res.json({ ok: true });
});
```

I got no user response on the log, when I called it from `nuxtServerInit`. I've also tried to get this user response from fetch method:

```
async fetch ({ store, params, req, res }) {
    console.log('fetch req.user', req.user); // I got the user with success here
    console.log('fetch store.state.user', store.state.user); // I got the user with success here too
    let { data } = await axios.get('/api/account');
},
```

Sadly, the result is the same (none) when I call `req.user` on `/api/test` from `fetch`. But when I try to call `/api/test` from `mounted`...

```
async mounted() {
    let { data } = await axios.get('/api/account');
},
```

...I got the user with success. The problem is that it happens after page rendering and I wanted it before it.

I don't know why `req.user` is passed on mounted, but not passed on `nuxtServerInit` or `fetch` methods. I don't know if it is a bug or if it is an intentional thing. Maybe I'm not thinking clearly. I'll appreciate any help with this question.

**Comment by dohomi** [comment]
@josantana I think this the order/use of the middleware and nuxtServerInit is required in your case. You need to save the user in a cookie, otherwise the data will not be there. Check following example package, it will cover all your requirements: https://github.com/nuxt/example-auth0

**Comment by Atinux** [comment]
You need to give the full URL in a iOS for `nuxtServerInit` (
http://localhost:3000/api/user).

Can you update and tell us if it works now?

**Comment by josantana** [comment]
Hi @Atinux,

I haven't mentioned (sorry about that), but my axios was configured to set the baseURL as follows (on `~plugins/axios.js`):

```
if (process.SERVER_BUILD) {
    options.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`;
}
```

So, that was not the problem.

I've just managed to make it work by passing the session cookies received by `nuxtServerInit` or any middleware's **req**uest, to the api endpoint using axios get headers. Kind similar to what has been done on auth0 example (thanks for your help, @dohomi). ;)

I don't know if the problem is exactly timing, because I'm receiving the user information on `nuxtServerInit`, which is the first lifecycle moment. It is just not automatically sent on every request like it does on `created()`, `mounted()` or on user interaction.

**Comment by Atinux** [comment]
@josantana indeed, on the server-side, you need to give the credentials to axios to make an authenticated request. On the client-side, when doing and XHR request, the cookies are sent automatically by the browser.

This is the dark side of SSR 😄
