### ISSUE TITLE
Middleware does not work on the client on the first load - v0.10.5

### ISSUE THREAD

**Issue by lavsurgut** [nuxt/nuxt.js#457]
For example, 

export default function (context) {
  console.log(context.isClient)
}

All subsequent route changes are executed, but not the first load. This bug invalidates the use of middleware on the client side.

**Comment by Atinux** [comment]
This is normal because the first load is on the server side, so the middleware is called from the server-side. We don't run again the middleware on the client, we simply hydrate the DOM.

**Comment by lavsurgut** [comment]
And why don't you run middleware on the client? You could have some code you want to run on the client. Like modernizr, for example. With modernizr it is not clear where to put it.

**Comment by ausir0726** [comment]
modernizr you can write a plugin .
but , if you want modernizr  or else run under ie9 before plugin
( I tried if use ie8 , you will get error before plugin )

you need put it to `nuxt.config.js` head.script ( but have escape issue )
maybe you should put it in app.html ( template ) 
https://github.com/nuxt/nuxt.js/issues/452
that I want run some code under ie9 or else browser .

**Comment by lavsurgut** [comment]
What I thought of is that Middleware has an access to context and therefore it is convenient to use it and do for example redirect to a certain route. Anyways, for now, I implemented modernizr check on the server side and indeed I use middleware for that. Thanks.

**Comment by rhythnic** [comment]
I second being able to run middleware on the client.  My use case is authentication via `feathers-vuex` which is broken on the server, so I need to exchange a reset-token for an access-token on the client, but I'm unable to run the middleware on the client.

**Comment by MyMediaMagnet** [comment]
I would also like this feature.  It seems like the most logical place for me to place the redirect logic coming from my CMS.

**Comment by christophmayrhofer** [comment]
same issue. I want to use the middleware to fetch data and redirect if I am unauthorized. Right now I have to do it in the  components created() method

**Comment by Jones-S** [comment]
Same issue here: #2186

**Comment by rhythnic** [comment]
I used $router.redirect inside of a try catch inside of the created callback.  $router.redirect throws an error on the server but it succeeds on the client.  Then redirect to another route where you actually do what you need to do.  It sucks having to create another route and it's fragile in that it depends on the server throwing an error on $router.redirect, but it's the only workaround I could figure out.

**Comment by SnirShechter** [comment]
@Atinux @rhythnic @Jones-S @christophmayrhofer @MyMediaMagnet 

Looks like the best way is making an init.js plugin (ssr:false) and doing the initialization logic there.

However, redirect() does not work(router.onReady(redirect) will change page but not layout). seems like this is fixed in nuxt-edge.
