### ISSUE TITLE
nuxt start  sh: /home/nodejs/songEagle/node_modules/.bin/nuxt: Permission denied

### ISSUE THREAD

**Issue by saucxs** [nuxt/nuxt.js#4570]
`[root@izwzz songEagle]# npm start

> songeagle@1.0.0 start /home/nodejs/songEagle
> nuxt start

sh: /home/nodejs/songEagle/node_modules/.bin/nuxt: Permission denied
`

在本地开发环境ok，但是在服务器上运行的时候出现了这个，服务上执行npm start，其实执行的是nuxt start，但是告知这个nuxt没有权限，已经是root权限，这个具体怎么解决？服务器：centos，node：10.14.2，npm：6.4.1

**Comment by luckyscript** [comment]
try this: 
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
