### ISSUE TITLE
Nuxt start accept NODE_ENV externally

### ISSUE THREAD

**Issue by LiangNex** [nuxt/nuxt.js#4576]
### What problem does this feature solve?

I am currently working on a nuxt project which needs to be deployed to multiple environments, such as ```stage```, ```production-location-a```, ```production-location-b```.

Thus I made a function to load varies properties of each environment, and distinguish them via ```process.env.NODE_ENV```.
```
const properties = env => {
  let property = {}
  switch (env) {
    case 'development':
      property = Dev
      break
    case 'productionLocationA':
      property = ProductionLocationA
      break
    case 'productionLocationB':
      property = ProductionLocationB
      break
    case 'stage':
      property = Stage
      break
    default:
      throw new Error(`Invalid NODE_ENV : ${env}.`)
  }
  return property
}
```

And start my project via below command in ```package.json```: 
```
{
  "scripts": {
    "dev": "nodemon --watch ... --exec \"nuxt\"",
    "build": "nuxt build",
    "start": "nuxt build && nuxt start",
    ...
    "START:STAGE": "set NODE_ENV=stage && npm run start",
    "START:PRODUCTIONA": "set NODE_ENV=productionLocationA && npm run start",
    "START:PRODUCTIONB": "set NODE_ENV=productionLocationB && npm run start",
  },
}
```

The ```process.env.NODE_ENV``` does is set to wanted value during building process, however is overwritten to ```production``` after executing ```nuxt start```.

There are several hacking approaches like mentioned in [#2741](https://github.com/nuxt/nuxt.js/issues/2741), or use [nuxt-env](https://github.com/samtgarson/nuxt-env) etc.  But is it possible for nuxt to support this officially ?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8321">#c8321</a>)</em></sub></div>

**Comment by pi0** [comment]
@LiangNex We have to consider that `NODE_ENV` is also internally being used by 3rd party modules (Including Vue.js runtime) to check against `production` value too. (Staging env is usually a production build but not running on official domain/host). So what I suggest you if you are not going to intentionally change the behavior, is simply using another env like `NUXT_ENV` like this:

```js
env:{
  NUXT_ENV: process.env.NUXT_ENV || process.env.NODE_ENV || 'development'
}
```

**Comment by LiangNex** [comment]
👍 thanks a lot for your advice. Really appreciate it.
