### ISSUE TITLE
cannot disable minifying

### ISSUE THREAD

**Issue by achtan** [nuxt/nuxt.js#4590]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

i have following config:
````
  dev: true,

  build: {
    html: {
      minify: {
        collapseBooleanAttributes: false,
        decodeEntities: false,
        minifyCSS: false,
        minifyJS: false,
        processConditionalComments: false,
        removeEmptyAttributes: false,
        removeRedundantAttributes: false,
        trimCustomFragments: false,
        useShortDoctype: false
      }
    }
  },

  optimization: {
    minimize: false,
  },

  generate: {
    minify: false
  },
````

but after running `nuxt generate` js files are still minified...

### What is expected ?

to not minify the generated files

### What is actually happening?

files are minified

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8328">#c8328</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Some parts in generated html is compressed in `vue-ssr` side instead of `generate.minify`, unfortunately Vue hasn't provided a way to serve pretty html in ssr.

https://github.com/nuxt/nuxt.js/issues/2151#issuecomment-345607089

**Comment by achtan** [comment]
'some parts' ? its looks to mi that everything is minified... :/

**Comment by clarkdo** [comment]
If your situation is same as the link in my previous comment, the minified parts in the screenshot are all from vue-ssr

**Comment by amjadkhan896** [comment]
any work on this issue, I also need this functionality. My Seo team also told me regarding this functionality

**Comment by IronLionShawn** [comment]
Webpack is doing the minification when using generate, the `html.minify` options seemingly do nothing.

Disable minification by adding the following to the build property's extend method:
`config.optimization.minimize = false;`
