### ISSUE TITLE
Issue with own Vuex store plugin

### ISSUE THREAD

**Issue by codanator** [nuxt/nuxt.js#4591]
I have setup a store in module mode as described in the documentation.
Now i want to add a Plugin to the store to add WebSocket functionality to the app.
After a long trial and error process i tried the bare minimum setup for a Plugin.
The mutation works correctly but the Plugin never gets called.

Is this a Bug?

Here is my code to reproduce the issue

mystore/index.js
```js
const incrementPlugin = store => {
	store.subscribe((mutation, state) => {
		if (mutation.type === "mystore/UPDATE_DATA") {
			console.log("from plugin");
			state.counter++;
		}
	});
};

export const plugins = [incrementPlugin];

export const state = () => ({
  counter: 0
})
```
mystore/state.js
```js
export default () => ({
	counter: 0,
	fakeText: 'text'
  })
```

THX for your help!

**Comment by victorhsantiago** [comment]
@codanator Were able to solve this issue? I'm having the same problem right now
