### ISSUE TITLE
Add global css  / auth-routes  example 

### ISSUE THREAD

**Issue by jameskid007** [nuxt/nuxt.js#46]
I added the "auth-routes for example" in Global CSS , "NPM run dev" did not respond. But "NPM run build & NPM run start" and "Global CSS" is the perfect addition to it. This is what reason. - love the framework very much.

**Comment by Atinux** [comment]
Hi @jameskid007 

You can see an example with the auth-routes and global-css examples merged here: https://gomix.com/#!/project/nuxt-auth-routes-css

Live demo: https://nuxt-auth-routes-css.gomix.me/

When used programmatically, you have to tell Nuxt.js to look in the `nuxt.config.js` file:
```js
const Nuxt = require('nuxt')
const config = require('./nuxt.config.js')
const nuxt = new Nuxt(config)
// ...
