### ISSUE TITLE
Server middleware isn't hot reloading properly

### ISSUE THREAD

**Issue by henriqemalheiros** [nuxt/nuxt.js#4601]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/henriqemalheiros/bug-report-nuxt-server-middleware-hot-reload](https://github.com/henriqemalheiros/bug-report-nuxt-server-middleware-hot-reload)

### Steps to reproduce

- Run `yarn dev`;
- Open `http://localhost:3000/api` in your browser;
- You'll see "api" appearing on the screen;
- Open `~/api/index.js` in your editor;
- Change the fourth line to `return res.end('api test')`;
- Nuxt will refresh;
- Open or refresh `http://localhost:3000/api` in your browser;
- You'll still see "api" appearing on the screen;
- Stop Nuxt;
- Run `yarn dev` again;
- Open or refresh `http://localhost:3000/api` in your browser;
- You'll see "api test" appearing on the screen.

### What is expected ?

You should see "api test" appearing on the screen without needing to stop Nuxt.

### What is actually happening?

Nuxt is properly watching the files in `~/api` but it's not reloading them.

### Additional comments?

It seems that previously (#258 and #1819) we would use Nuxt alongside nodemon. But since v2.0.0 (#1509 and #3718), server middlewares have watchers support.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8334">#c8334</a>)</em></sub></div>

**Comment by manniL** [comment]
Thanks for the report ☺️ 

See #4301. Will be fixed in a future version (not v2.4 though)

**Comment by francoism90** [comment]
@manniL Just to confirm the same problem here.
What do you mean exactly with not in this version? Will this still be in Nuxtjs v2? :)

Thanks.

**Comment by manniL** [comment]
@francoism90 I meant that the next minor release (v2.4) will likely *not* include a fix for this. I can't give an ETA or similar though. 

Closing to unify the (almost same) issue in #4301

**Comment by poopa-uk** [comment]
This is odd.  Hot reload was working beautifully for me until a few days ago.  Cannot think what I have changed other than my express server middleware growing in complexity, but yeah.  Was working, now it isn't.  Frustrating when working on the api side of things as the dev build needs to get restarted on every change.

I added the following to nuxt.config.js but this just seems to reload nuxt but leave the server middleware as is.

`build: { watch: { 'api' } }`

**Comment by super-kamil** [comment]
Same problem here. nuxt@2.15.8 Have to restart to see changes.

**Comment by torressam333** [comment]
Has anyone solved this? Using nuxt 2.15.8 and HMR still does not work for anything inside of server-middleware.

**Comment by manniL** [comment]
@raf202 Feel free to raise a new issue with a reproduction and link this one in there
