### ISSUE TITLE
Importing image from css global

### ISSUE THREAD

**Issue by RafaelGSS** [nuxt/nuxt.js#4603]
Hello everyone.

I have the follow `nuxt.config.js`:

```
head: {
  ...
  /**
   * Global CSS
   */
  css: [
    '@/assets/css/main.css'
  ]
}
```

In my main.css I have the follow statement:

```
.bg-1 {
    background: url(~assets/images/bg/1.jpg);
}
```

But don't works, 
```
 ERROR  Failed to compile with 19 errors                                                                  friendly-errors 16:03:02

This dependency was not found:                                                                            friendly-errors 16:03:02
                                                                                                          friendly-errors 16:03:02
* assets/images/bg/1.jpg in ./node_modules/css-loader??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/main.css
```

Obs: I try with '/' too.

**Comment by RafaelGSS** [comment]
@clarkdo

**Comment by RafaelGSS** [comment]
Can re-open this issue ?

**Comment by clarkdo** [comment]
The issue was closed since it’s not followed template, could you please raise the issue via cmty?

**Comment by RafaelGSS** [comment]
Okay, is there. Thanks

**Comment by rendergraf** [comment]
@RafaelGSS please try with: ~@

Example:

background-image: url('~@/assets/image.png');

**Comment by RafaelGSS** [comment]
Hello @rendergraf , thanks for your answer.

So... This thread was opened in 2018, I already fixed it. (I don't remember how)

For now... can be close this issue @clarkdo 

Thanks all.
