### ISSUE TITLE
CSP Headers should be generated for static sites like Netlify

### ISSUE THREAD

**Issue by sirtimbly** [nuxt/nuxt.js#4604]
### What problem does this feature solve?

A CSP header of `script-src 'unsafe-inline'` is currently required to get a Nuxt generated site to work when you are setting strict CSP headers. I see that the feature to use CSP headers is available when you're running Nuxt as express middleware, but I'm using Netlify to host my site. 

The feature I want is support for adding a new CSP string to `/static/_headers` every time that `nuxt generate` is run. This would allow me to specify a stricter content security policy and not need to be running express.

### What does the proposed changes look like?

The `cspScriptSrcHashes` returned from the server.render method could be formatted into the proper string and merged with the static `_headers` file during generation and placed in the dist path. I know this is a specific hosting provider feature, I'm not sure which other providers provide means for adding http headers. I think gitlab pages had a .toml file for this. Zeit Now has a now.json file for this purpose. They all could be merged in like this but merging different file formats is a pain. Maybe we put a special `CSPSCRIPTHASHES.NUXTJS.TEST` token in the text file and it will be replaced during generate?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8336">#c8336</a>)</em></sub></div>

**Comment by manniL** [comment]
An easier solution (that's also host-agnostic) would be #2874

**Comment by sirtimbly** [comment]
Huh! I had no idea meta tags were valid for setting CSP. Apparently it can only increase restrictiveness of the CSP set by the header - but that should still work. Great idea.
