### ISSUE TITLE
feat: fully static generated page

### ISSUE THREAD

**Issue by YamenSharaf** [nuxt/nuxt.js#4607]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://zen-turing-c5c7d2.netlify.com/tag/](https://zen-turing-c5c7d2.netlify.com/tag/)

### Steps to reproduce

Go to route that is dynamically generated

### What is expected ?

Page makes a client side Ajax request before navigating to a dynamically generates route, even though navigating directly to route would display static data without unnecesary requests

### What is actually happening?

An Ajax request fires before leaving each page

### Additional comments?

I understand that this might be to get fresh data off the server but I already have a deployment process that generates my site when data changes, also the whole point of static site is fast navigation.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8342">#c8342</a>)</em></sub></div>

**Comment by manniL** [comment]
Closing this in favor of the linked RFC :relaxed:
