### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by tiagofscoelho** [nuxt/nuxt.js#461]
Hi everyone. I'm trying to use karma to make unit testing, using the same configuration as vue-cli webpack template. The problem starts with webpack configuration, since nuxt.config.js `build` key is only an extension of webpack server and client configurations how's supposed to structure the unit testing environment?

Thanks

**Comment by rmartins90** [comment]
Even using AVA it doesn't recognises webpack alias as ~pages. Should be a way to get webpack base configuration to use outside nuxt.js.

**Comment by rmartins90** [comment]
Also, we can't write tests to .vue files without webpack configurations cause, obviously, we don't have vue-loader so we can't import .vue files. We're trying to figure out this.

**Comment by pi0** [comment]
@rmartins90 There is a super useful `extend` config available in `nuxt.config.js` with passes webpack config used to generate client or server bundle. not sure but i may be useful for that case... :))

**Comment by chrisnicola** [comment]
@pi0 is it possible to hoist this `extend` in .eslint.js or other files? Was there another solution to this?

**Comment by wushan** [comment]
is this problem solved ? I am new with karma but ran into the same difficult setting up the test environment, is somebody has success doing the unit test ?

**Comment by nyl-auster** [comment]
Hello ! i'm working on a Drupal 8 + Nuxtjs demo for http://www.contentacms.org/ , would love to set unit test but don't know how to access webpack config to configure karma , any clue  appreciated !

**Comment by nyl-auster** [comment]
@wushan you should look this comment, it mirrors the webpack config , seems to work until we have a solution to access webpack config: https://github.com/nuxt/nuxt.js/issues/200#issuecomment-308452393

**Comment by wushan** [comment]
@nyl-auster I  exactly followed that setting and it works, hope that will be documented in the future releases.

**Comment by nyl-auster** [comment]
this is my current working webpack config for unit tests : 

https://gist.github.com/nyl-auster/ab15106c776a1f14cac3458203e18e19#file-webpack-config-js
( you may inspect this repository to see my test configuration : https://github.com/contentacms/contenta_vue_nuxt/tree/master/test/unit )

**Comment by yacinehmito** [comment]
I believe this issue deserves to be reopened.
Currently there is no way to setup karma on a nuxt project without reproducing by hand the webpack configuration. Ideally, the Nuxt object would expose the webpack configuration that is to be used client-side so we can hook it up to karma.

**Comment by uptownhr** [comment]
A guide would also be awesome once it's figured out.

**Comment by phuochau** [comment]
me too, has same problem with unit testing on ava

**Comment by brantwills** [comment]
standing on the shoulders of giants I cobbled this together
https://github.com/brantwills/nuxt-ts-jest-starter-template

all this started off this thread so i thought i should post back

**Comment by WilliamDASILVA** [comment]
Any news on that?

**Comment by alidcastano** [comment]
Hey guys, 

This was a big pain-point for me as well. So I created a zero-configuration test runner for Nuxt.js using Jest and Pupeteer: https://github.com/studbits/nuxt-jest-puppeteer

Hopefully it helps!

**Comment by marines** [comment]
@alidcastano it has nothing to do with unit tests.

**Comment by alidcastano** [comment]
@marines Jest can be used for unit testing ...

**Comment by wesssel** [comment]
I wrote a small post about how to test in Nuxt using AVA

https://medium.com/@wesselvanderpal/nuxt-unit-snapshot-testing-a3dc7cb79ec1

Github repo

https://github.com/wesssel/nuxt-unit-testing

**Comment by uptownhr** [comment]
@atinux @clarko @pi0 sorry for tafging you all but testing is a concern of mine too and i have not seen an official testing story from the nuxt team. 

I love nuxt and comments like the above should be addressed.

**Comment by TakahiRoyte** [comment]
I do not mind using any of the test runner, Jest, ava, karma etc.
I just want one unit testing solution that works with complete Nuxt application, which includes testing for store and router.
Number of examples are posted but it seems that none has covered the store part...

**Comment by aldarund** [comment]
@TakahiRoute jest+ vue test utils work.fine with nuxt with store and router

**Comment by wahengchang** [comment]
hey, is that a joke ? a framework without unit test ?

i spent a whole day to find a way about writing unit test, which is the most basic requirement for every developers.

**Comment by aldarund** [comment]
@wahenchang you can test it like any other Vue project, for example jest + vue-test-utils. Probably some nuxt specific stuff like asyncData for pages won't work this way, but other thing should be fine
