### ISSUE TITLE
Hook into Nuxt before the headers are completely sent

### ISSUE THREAD

**Issue by BboyKeen** [nuxt/nuxt.js#4614]
### What problem does this feature solve?

Hi guys,

I was looking for a way to remove 'unsafe-inline' from my CSP style-src configuration but didn't find anything about it.
I considered working on a module on my own to be able to do that. Basically, what this module is trying to achieve is just locatiing all `<style ...>xxxx</style>` tags, computing a digest for the content and rewriting style-src CSPs on the fly.

```
import crypto from 'crypto'

export default function CspStyleSrc (moduleOptions) {
    const cspStyleSrcHashes = new Set();
    const _this = this;

  
    this.nuxt.hook('render:route', (url, result, context) => {
        if (!_this.options.render.csp) {
            return;
        }

        const { hashAlgorithm } = _this.options.render.csp; 

        const styleTagRegex = /<style.*>([\s\S]*?)<\/style>/gm;

        let match = null;

        while ((match = styleTagRegex.exec(result.html)) != null) {
            const hash = crypto.createHash(hashAlgorithm);
            hash.update(match[0]);
            cspStyleSrcHashes.add(`'${hashAlgorithm}-${hash.digest('base64')}'`);
        }
    });

    this.nuxt.hook('render:routeDone', (url, result, { res }) => {
        if (!_this.options.render.csp) {
            return;
        }

        const cspHeader = _this.options.render.csp.reportOnly ? 'Content-Security-Policy-Report-Only' : 'Content-Security-Policy';

        const styleCspRegex = /(style-src .*?;)/gm;

        const actualCspString = res.getHeader(cspHeader);

        if (!actualCspString) {
            return;
        }

        const match = styleCspRegex.exec(actualCspString);

        if (!match) {
            return;
        }
        
        const joinedHashes = Array.from(cspStyleSrcHashes).join(' ');

        let newCspString = actualCspString.slice(0, match.index);
        newCspString += `${actualCspString.slice(match.index + match[0].length, actualCspString.length)}; `;
        newCspString += `${match[0].slice(0, -1)} ${joinedHashes};`;

        res.setHeader(cspHeader, newCspString);
    });
}
```

Technically, it works. However, when I try to replace the CSP header, I have an error `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client` which makes perfectly sense as `res.end()` has been called just before calling `render:routeDone` hook.

Having a hook like `render:headersSet`  would help achieve this kind of modifications.

### What does the proposed changes look like?

To solve, the problem I would expose a `render:headersSet` hook just before calling `res.end()` in `https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/middleware/nuxt.js`

This way, we would be able to rewrite the headers easily.

Another use case, I can see, still in the context of CSP would be to be able to rewrite `connect-src` directive to allow the application to execute requests on the backend host.

For example, if you follow DevOps principle `Build once, deploy many`, you would end having some routine to dynamically read the target host to use at runtime. As you can't know at build which host will be used, you can't specify it in the CSP policies in `nuxt.config.js` and you'll need to rely on something of your own to add it to the `connect-src` allowed resources.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8346">#c8346</a>)</em></sub></div>

**Comment by manniL** [comment]
Sounds reasonable so far! Feel free to send in a PR :relaxed:

**Comment by BboyKeen** [comment]
Hi @manniL 
Even if I found a workaround for my case, I will definitely push a PR cause I think overriding headers is pretty common.
However I will need some guidance to implement proper tests for this stack.

**Comment by manniL** [comment]
As discussed in https://github.com/nuxt/nuxt.js/pull/4755 ☺️
