### ISSUE TITLE
when i `npm run dev` i always got a node error message :MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by chaosJS** [nuxt/nuxt.js#4615]
it's a warnning, the whole project' still working ,so may i ask how to fix it ?
`
  nuxt:render Rendering url /ranking/machine +0ms
(node:90820) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added. Use emitter.setMaxListeners() to increase limit
  nuxt:render Data fetching /ranking/machine: 706ms +0ms
`
![image](https://user-images.githubusercontent.com/17522683/50374661-c3834b00-062c-11e9-90fc-bf92bd52d43a.png)

**Comment by gkatsanos** [comment]
Any feedback on that one?
