### ISSUE TITLE
0.10.0 Regression - Can no longer move build artifacts which breaks deployment

### ISSUE THREAD

**Issue by corsen2000** [nuxt/nuxt.js#462]
I am deploying to a service that works by running `nuxt build` in a `/tmp` folder and then moves the project to a new location for hosting. This previously worked when using `0.9.X`, but no longer works with Nuxt `0.10.X`.

This broke because Nuxt started using `vue-ssr-webpack-plugin`, which by default [sets basedir](https://github.com/vuejs/vue-ssr-webpack-plugin/blob/master/index.js#L49) to an absolute path generated at build time. This path is no longer valid at runtime since my deployment system will move the project.

This property can be overridden at runtime using [basedir option](https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#basedir), but [Nuxt does not provide a hook into these options](https://github.com/nuxt/nuxt.js/blob/master/lib/build.js#L466).

I've been considering a few options and would like to get your opinion.

1. Should I actually file an issue with `vue-ssr-webpack-plugin`? [This was a recent change](https://github.com/vuejs/vue-ssr-webpack-plugin/commit/75098c0db10d2d8aafb8d69a1317999e8e0a710d) and I don't understand the motivation.
2. Can Nuxt expose a configuration option so that we can set additional options passed to `createBundleRenderer` such as `baseurl`?

In the short term I believe I can hack around this by running an additional build script after `nuxt build` that simply removes the `basedir` line from `server-bundle.json`. The defaults used by `createBundleRenderer` seem fine for my use case.

I don't think this type of deployment system where the build is run in 1 location and then the project is copied is that uncommon, so others may run into this issue after upgrading.

Thank you!

**Comment by paulstraw** [comment]
Hey @corsen2000, I believe I'm running into a similar issue. Did setting up a post-build script to remove the `basedir` property from `server-bundle.json` end up working for you as a temporary solution?

**Comment by corsen2000** [comment]
@paulstraw I added this to my package.json

```
"fix-absolute": "sed -i '/  .basedir.: /d' .nuxt/dist/server-bundle.json",
```

My build now runs that after the regular Nuxt build.

This appears to have solved my issue for now, though I have not yet done extensive testing.

**Comment by paulstraw** [comment]
Thanks @corsen2000! Can confirm that `sed` command did the trick for my Heroku deployment as well.

**Comment by Atinux** [comment]
Hi @corsen2000 

It seems that the `basedir` has been removed in the new version of [vue-ssr-webpack-plugin](https://github.com/vuejs/vue-ssr-webpack-plugin/blob/master/src/server.js).

I am going to take a deeper look into it. Sorry about that.

**Comment by corsen2000** [comment]
@Atinux no worries, appreciate the work you do for this project.

We may be able to fix this issue by just bumping `vue-ssr-webpack-plugin` dependency to `^1.0.3`, given the fix that was made there. Perhaps there something even better to do from Nuxt.js, but I'm not as familiar with how all this works.

**Comment by Atinux** [comment]
`vue-ssr-webpack-plugin` allow us to add a better debugging experience on the server-side but also to add the CSS styles directly embedded in the HTML document (a big performance issue). 

We are also working with Evan to see how we can implement [this feature](https://github.com/vuejs/vue-ssr-webpack-plugin#client-manifest) to let Nuxt.js generates crazy-fast web application!
