### ISSUE TITLE
Cant use babel-plugin-import to import component style in nuxt

### ISSUE THREAD

**Issue by gongzhibin** [nuxt/nuxt.js#4622]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/9zk7wxllqy](https://codesandbox.io/s/9zk7wxllqy)

### Steps to reproduce

open link: https://9zk7wxllqy.sse.codesandbox.io/

### What is expected ?

 Plugin 'babel-plugin-import' import Popup's style and it has right style

### What is actually happening?

Plugin 'babel-plugin-import' dont import Popup's style

### Additional comments?

I cant use plugin 'babel-plugin-import' to import component style in nuxt but it is no problem in normal vue project

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8351">#c8351</a>)</em></sub></div>

**Comment by aldarund** [comment]
I dont see in you codesadnbox any usage of babel-plugin-import

**Comment by gongzhibin** [comment]
sorry. It is in nuxt.config.js

**Comment by aldarund** [comment]
now you have two build sections in nuxt.config.

**Comment by gongzhibin** [comment]
both in server and client?

**Comment by aldarund** [comment]
there cant be two sections of build. The first one will just be overwritten by second one.

**Comment by gongzhibin** [comment]
sorry, I dont know two build sections

**Comment by aldarund** [comment]
@gongzhibin what you dont know? In your nuxt.config you have build key two times, one at start of file and one at end. Its wrong.  The one at the end will overwrite the one from a start, so you code where u add babel plugin simply not executed at all

**Comment by aldarund** [comment]
It seem to wokr on vant 1.2.1
https://codesandbox.io/s/n08p82qmnl
But dont work on higher versions.
https://github.com/youzan/vant/issues/1748 -> it says it was fixed in 1.3.1 but it dont seem to be true, so it seems like its a problem in vant

**Comment by aldarund** [comment]
closing as seems to be vant bug.

**Comment by gp0320** [comment]
```

  build: {
   // 添加这个是关键，添加后babel才会处理依赖包vant里面的代码
    transpile: [ /vant.*?less/ ], 
   
    babel: {
      plugins: [
        ['import', {
          libraryName: 'vant',
          "style": (name) => {
            return `${name}/style/less.js`
          }
        }, 'vant']
      ],
    },
  }

```
Refer to my article for details：
https://juejin.im/post/5e012778518825127f085da8
