### ISSUE TITLE
Head not recreate html attribute

### ISSUE THREAD

**Issue by kamontat** [nuxt/nuxt.js#4626]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/kcnt-info/website/blob/931006dae7b17ca644d462b6d5f0d20210a93e8f/layouts/default.vue#L36-L54](https://github.com/kcnt-info/website/blob/931006dae7b17ca644d462b6d5f0d20210a93e8f/layouts/default.vue#L36-L54)

### Steps to reproduce

1. Save/Set some value in cookies (via cookie-universal-nuxt)
2. Get cookies value in `head` method in `layout`
3. try to print the value, is should return the newest value
4. BUT the `htmlAttrs` is not updated to be latest value

```
htmlAttrs: {
    class: this.theme,
    theme: this.theme
}
```

### What is expected ?

class of html changes

### What is actually happening?

it became the default value when refresh pages.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8354">#c8354</a>)</em></sub></div>

**Comment by manniL** [comment]
I tried to reproduce the problem in the **most minimal way** (no 3rd party deps or similar) and couldn't find problems.

https://codesandbox.io/s/github/manniL/nuxt-4626/tree/master/

**Comment by kamontat** [comment]
I think the problem occurred because **seo** of `nuxt-i18n` ; ref: nuxt-community/nuxt-i18n#100
