### ISSUE TITLE
Importing css file 

### ISSUE THREAD

**Issue by mlyp** [nuxt/nuxt.js#4638]
**Dear colleages,**

I have problems with importing .css files. In order to solve this issue I use next node modules: css-loader and style-loader

**My nuxt.config.js configuration:**
```
module.exports = {
....
build: {
  extend(config, ctx) {
         config.module.rules.push({
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
         });
      }
}
....
}
```
**This way I try to import styles in my .js file:**
`import pageStyles from '../css/common.rtl.css';`

**In order then to set styles for my template this way:** 
```
export default {
      head() {
         return {
            htmlAttrs: {
               styles: pageStyles
            }
         }
      }
```

Finally, when I build my nuxt application, I get **next error**:

> ERROR in ./node_modules/css-loader/dist/cjs.js?{"sourceMap":false,"minimize":true,"importLoaders":0,"alias":{"/assets":"D://myproject//assets","/static":"D://myproject//static"}}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-c4038718","scoped":false,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./layouts/err.vue
> Module build failed: ValidationError: CSS Loader Invalid Options
> 
> options should NOT have additional properties
> options should NOT have additional properties

**Comment by GRIM4CE** [comment]
@mlyp did you find a solution for this? I'm also facing some trouble similar to this I believe. I'm trying to use CSS-Modules and a computed property to theme styles based on a prop. It works great on vue but when I try to implement it on Nuxt my css import in the js is returning an empty object.
