### ISSUE TITLE
When I manually refresh, Can't find cdn script on source code header.

### ISSUE THREAD

**Issue by yusunglee2074** [nuxt/nuxt.js#4639]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/yusunglee2074/sungyuPageFront/blob/master/pages/posts/_id.vue](https://github.com/yusunglee2074/sungyuPageFront/blob/master/pages/posts/_id.vue)

### Steps to reproduce

I make simple blog

npm install
npm run dev
Click any post title for go detail post page(/page/posts/_id.vue)

Now error occur with can't find cdn variable(showdown).
same with npm run build, npm start

### What is expected ?

Not Occur error

### What is actually happening?

Can't find cdn variable,

### Additional comments?

Simple code(very small code),

If I make any small mistake(with report issue)

Sorry for my issue, this is my first submit 
Please let me know it,
I will fix it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8369">#c8369</a>)</em></sub></div>

**Comment by yusunglee2074** [comment]
Cdn live in nuxt.config
```javascript 
head: {
    title: '성유 페이지입니다.',
    script: [
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.min.js' }
    ],
```

**Comment by manniL** [comment]
As `asyncData` is executed on server-side when you hard-reload the page (in `universal`/`SSR` mode), there is no `showdown` available.
