### ISSUE TITLE
Access current page object within layout

### ISSUE THREAD

**Issue by Darkside73** [nuxt/nuxt.js#464]
For example to show current page title in layout

**Comment by pi0** [comment]
@Darkside73 I haven't tested it but what if you add a ref on nuxt component in layout (`<nuxt ref=page>`) And trying to access it with this.$refs.page? (It will not be available in data only after `mounted()`)

**Comment by Darkside73** [comment]
It's available only in ```mounted``` hook but without data:

Page
```javascript
export default {
  data () {
    return {
      title: 'Page Title'
    }
  }
}
```
Layout
```vue
<template>
  <!-- TypeError: Cannot read property 'title' of undefined -->
  <div>{{$refs.page.title}}</div>
</template>
<script>
export default {
  mounted () {
    console.log(this.$refs.page.title) // undefined
  }
}
</script>
```

**Comment by pi0** [comment]
What about `console.log(this.$refs.page.componentInstance.title)` ? :))

**Comment by Darkside73** [comment]
No success
```TypeError: Cannot read property 'title' of undefined```

**Comment by pi0** [comment]
For data access problem : 
```vue
<template>
  <div>{{pageTitle}}</div>
</template>
<script>
export default {
 data() {
  return { pageTitle: '' }
 }
  mounted () {
   const page  = this.$refs.page.componentInstance;
   this.title=page.title;
  }
}
</script>
```

**Comment by pi0** [comment]
Can you inspect what exactly `this.$refs.page.componentInstance` is using console? I think there is an component inside it

**Comment by pi0** [comment]
Also if you see (https://github.com/nuxt/nuxt.js/blob/master/lib/app/components/nuxt.vue#L17) It seems there are many other ways accessing `<nuxt>` element.

**Comment by pi0** [comment]
`this.$refs.page.nuxtChild` may also help :)) (Brute forcing Nuxt :D)

**Comment by Darkside73** [comment]
Both ```this.$refs.page.componentInstance``` and ```this.$refs.page.nuxtChild``` give me ```undefined```.
And ```this.$nuxt.$refs.page.title``` as well.
Only ```this.$nuxt.$children[0].title``` shows desired results

**Comment by ausir0726** [comment]
I wanna ask if you can catch title you want on mounted function , is SSR will get desired results and print to source html ?
thanks .

**Comment by Darkside73** [comment]
Yes. Works on server side as well

**Comment by Darkside73** [comment]
This approach does not work if route changes: ```this.$nuxt.$children[0]``` never changes on client-side navigation

**Comment by pi0** [comment]
Maybe you can just listen to route changes and update current child : 
```js
import router from '~router'


  router.afterEach((from, to)=>{ 
    // 
  }
```

**Comment by Darkside73** [comment]
How I can get actual child component?

**Comment by pi0** [comment]
Just was an idea, but inside afterEach function we have access to `this` and we can get new value on route change events

**Comment by Darkside73** [comment]
It doesn't work. Even if use ```watch```, child still points to prev component:
```javascript
watch: {
  $route () {
    this.title = this.$nuxt.$children[0].title // outdated title
  }
}
```

**Comment by Darkside73** [comment]
I've accomplish it via vuex:

*store/index.js*

```js
export const state = {
  pageTitle: 'Default Title'
}

export const mutations = {
  SET_PAGE_TITLE (state, title) {
    state.pageTitle = title
  }
}
```

*layouts/default.vue*

```vue
<template>
  <h1>{{$store.state.pageTitle}}</h1>
</template>
```

*pages/index.vue*

```vue
<template>
  <div></div>
</template>

<script>
export default {
  asyncData ({ req }) {
    return {
      title: `Main Page ${req ? 'server' : 'client'}`
    }
  },
  head () {
    return {
      title: this.title
    }
  },
  mounted () {
    this.$store.commit('SET_PAGE_TITLE', this.title)
  }
}
</script>
```
But looking for more concise approach though

**Comment by SimplyCorey** [comment]
I am also looking for a more concise approach than @Darkside73 last comment.  This is the only thing I can get to work currently.

**Comment by sullivanpt** [comment]
Thanks for sharing the 'mounted+store' solution. I'm using a mixin to save typing; although I haven't tried the mixin with a 'head' attribute.
```
export let storeTitle = (title) => ({
  mounted () {
    this.$store.commit('SET_PAGE_TITLE', title)
  },
  destroyed () {
    this.$store.commit('SET_PAGE_TITLE', 'Default Title')
  }
})
```
```
<script>
import { storeTitle } from '~/helpers/mixins'
export default {
  mixins: [setTitle('Main Page')]
}
</script>
```

**Comment by YuraDev** [comment]
head () {
    let sefl = this
    if (process.browser) {
      this.title = document.title
    }
    return {
      changed ({title}) {
        sefl.title = title
      }
    }
  },

**Comment by MtDalPizzol** [comment]
Hi folks... I'm new to Vue and I was facing this issue too. I Iooked it up a bit and  I found [this comment](https://github.com/vuejs/vue/issues/4379#issuecomment-289716688). So, I ended up with this, which uses `vue-meta` for handling the `<title>` on the `head` section and reuse that same title in the layout:

**Page:**
```javascript
<script>
export default {
  head () {
    return {
      title: 'My Page Titlte'
    }
  }
}
</script>
```
**Layout:**
```javascript
<script>
  export default {
    data () {
      return {
        title: document.title
      }
    }
  }
</script>
```
The downside of this approach is that it only works for this simple things. If you need to share complex component data with your layout, I think Vuex is the way to go... But this seems to be a good approach if you have small pieces of data to share with your layout, leaving Vuex free to handle the "real" data of your app.

**Comment by XAHTEP26** [comment]
For title i use computed property:
```javascript
title() {
  return this.$meta().inject().titleChunk;
}
```

**Comment by chrisleyva** [comment]
> 
> 
> ```
>   head () {
>     let sefl = this
>     if (process.browser) {
>       this.title = document.title
>     }
>     return {
>       changed ({title}) {
>         sefl.title = title
>       }
>     }
>   },
> ```

This is what worked for me...and it's pretty clean, too. Thank you!

The `this.$meta().inject().titleChunk` almost worked for me but the title was sometimes outdated (held the previous page's title).

**Comment by akarelas** [comment]
Indeed, @chrisleyva, that solved the problem for me as well. That is the best solution I think.
