### ISSUE TITLE
Generate inital state Bug

### ISSUE THREAD

**Issue by willin** [nuxt/nuxt.js#4642]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/willin/willin.github.io/blob/source/store/index.js](https://github.com/willin/willin.github.io/blob/source/store/index.js)

### Steps to reproduce

```js
const hour = new Date().getHours();

export const state = () => ({
  theme: hour < 7 || hour > 19 ? 'dark' : 'light'
});
```

### What is expected ?

get light or dark theme by time

### What is actually happening?

generated to specific theme, like light.

### Additional comments?

besides when generated, i18n module have some error too.

see: https://github.com/nuxt-community/nuxt-i18n/issues/173

- online: https://willin.guru
- static files: https://dev.tencent.com/u/willin/p/willin.wang/git/tree/master

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8371">#c8371</a>)</em></sub></div>

**Comment by manniL** [comment]
This is not how generate works.

It'll execute the function *once* when generating the page, so the state is *statically set* based on the time when the page is generated.

You could use a Nuxt plugin to modify the state before initializing the root instance.

*plugins/theme.js* (don't forget to register)
```js
export default (ctx) => {
  ctx.store.dispatch('selectThemeBasedOnTime')
}

```

*store*
```js
export const state = () => ({
  theme: 'light'
});

export const mutations = {
  setTheme(s, theme) {
    s.theme = theme 
  },
  toggleTheme(s) {
    s.theme = s.theme === 'dark' ? 'light' : 'dark';
  }
};

export const actions = {
  selectThemeBasedOnTime({ dispatch }) {
    const hour = new Date().getHours();
    const theme = hour < 7 || hour > 19 ? 'dark' : 'light'
    dispatch('setTheme');
  }
};
```

**Comment by willin** [comment]
oh...

thx

**Comment by willin** [comment]
i've tried, but still the same situation...  @manniL 

```js
plugins: [
    { src: '~/plugins/global.js' },
    { src: '~/plugins/toys.js', ssr: false },
    { src: '~/plugins/google.js', ssr: false }
  ],
```

```js
// global.js
export default (ctx) => {
  ctx.store.dispatch('toggleThemeByTime');
};
```

https://github.com/willin/willin.github.io/blob/source/store/index.js
