### ISSUE TITLE
Edge & IE browsers requires Eventsource to work.

### ISSUE THREAD

**Issue by baturali** [nuxt/nuxt.js#4643]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[http://localhost:3000](http://localhost:3000)

### Steps to reproduce

When i run my nuxt project on development mode this error cames on Edge and IE browsers

### What is expected ?

Nuxt project needs to work with IE and Edge browsers.

### What is actually happening?

webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8373">#c8373</a>)</em></sub></div>

**Comment by alanaasmaa** [comment]
This is not Nuxt.js issue.

The issue is related to webpack-hot-middleware.
You can try to use poly fill when you must use Edge.

https://github.com/webpack-contrib/webpack-hot-middleware/issues/11

**Comment by baturali** [comment]
Thanks for answer,
I tried;
babel-polyfill,
eventsource-polyfill

but it doesn't work for now. If i find an answer i'll share.

**Comment by manniL** [comment]
Coming in next Nuxt.js version (or nuxt-edge) by default

See https://github.com/nuxt/nuxt.js/pull/4600
