### ISSUE TITLE
prettier complaining about the generated default.vue layout

### ISSUE THREAD

**Issue by kakulukia** [nuxt/nuxt.js#4644]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://pastebin.com/CaNz3e05](https://pastebin.com/CaNz3e05)

### Steps to reproduce

yarn create nuxt-app <my-project>
in the process choose to activate prettier

### What is expected ?

having a working project

### What is actually happening?

an error is shown that the generated default page has wrong indentation - all script code has +1 indentation

### Additional comments?

Removing 1 indentation level fixes the whole problem - so the fix is pretty easy, but, but the generated project code should be valid and not produce any errors.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8374">#c8374</a>)</em></sub></div>

**Comment by manniL** [comment]
Thanks for the report!

Please send in an issue or PR to https://github.com/nuxt-community/create-nuxt-app :relaxed:
