### ISSUE TITLE
Typescript example is not working

### ISSUE THREAD

**Issue by baocancode** [nuxt/nuxt.js#4646]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/v2.3.4/examples/typescript](https://github.com/nuxt/nuxt.js/tree/v2.3.4/examples/typescript)

### Steps to reproduce

- Check out the source code (at tag v2.3.4)
- Go to examples/typescript
- Run npm install and npm run dev
- Visit page http://localhost:3000/

### What is expected ?

The app should work.

### What is actually happening?

Build error:

NuxtServerError
Module build failed (from ./node_modules/ts-loader/index.js): TypeError: Cannot read property 'ts' of undefined at getLoaderOptions (nuxt.js-2.3.4/examples/typescript/node_modules/ts-loader/dist/index.js:70:44) at Object.loader (nuxt.js-2.3.4/examples/typescript/node_modules/ts-loader/dist/index.js:23:19)

### Additional comments?

The code in dev branch does not work as well.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8376">#c8376</a>)</em></sub></div>

**Comment by manniL** [comment]
cc @kevinmarrec @hartmut-co-uk

**Comment by kevinmarrec** [comment]
@baocancode @manniL Well on 2.3.4 I've no ideas, but the example in dev will be updated to work with the new incoming TS support :)

**Comment by manniL** [comment]
@baocancode As better TS support is coming with v2.4, we'll update the examples for it. :relaxed: 
Thanks for reaching out and for your patience :relaxed:
