### ISSUE TITLE
IISNode hosting

### ISSUE THREAD

**Issue by shaydoc** [nuxt/nuxt.js#465]
Hi,
  I maybe doing something wrong here, but the nuxt route does not seem to work in iisnode.
  using the nuxt/express example i configured it for iisnode, but it is returning a 404 when i browse to the 
  / route
 [Stackoverflow Question](http://stackoverflow.com/questions/43069934/nuxt-js-routes-returning-404-in-iis-with-iisnode)
Thanks
Shay

**Comment by benosman** [comment]
I had some issues getting nuxt to work on Azure, partly due to the iisnode config.

In the end I had to create a stub **`server.js`** file in the repo root that is based on the `node_modules/nuxt/bin/nuxt-start` (just paths are changed, probably possible to refactor)

```js
var fs = require('fs')
var Nuxt = require('nuxt')
var resolve = require('path').resolve

var rootDir = resolve('.')
var nuxtConfigFile = resolve(rootDir, 'nuxt.config.js')

var options = {}
if (fs.existsSync(nuxtConfigFile)) {
  options = require(nuxtConfigFile)
}
if (typeof options.rootDir !== 'string') {
  options.rootDir = rootDir
}
options.dev = false // Force production mode (no webpack middleware called)

var nuxt = new Nuxt(options)

new nuxt.Server(nuxt)
  .listen(
    process.env.PORT || process.env.npm_package_config_nuxt_port,
    process.env.HOST || process.env.npm_package_config_nuxt_host
)
```
Then in **`web.config`** I pointed to that - see the three mentions of server.js in there

```xml

<?xml version="1.0" encoding="utf-8"?>
<!--
     This configuration file is required if iisnode is used to run node processes behind
     IIS or IIS Express.  For more information, visit:

     https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config
-->

<configuration>
  <system.webServer>
    <!-- Visit http://blogs.msdn.com/b/windowsazure/archive/2013/11/14/introduction-to-websockets-on-windows-azure-web-sites.aspx for more information on WebSocket support -->
    <webSocket enabled="false" />
    <handlers>
      <!-- Indicates that the server.js file is a node.js site to be handled by the iisnode module -->
      <add name="iisnode" path="server.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        <!-- Do not interfere with requests for node-inspector debugging -->
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server.js\/debug[\/]?" />
        </rule>

        <!-- <rule name="Redirect to https" stopProcessing="true">
          <match url="(.*)"/>
          <conditions>
            <add input="{HTTPS}" pattern="Off"/>
            <add input="{REQUEST_METHOD}" pattern="^get$|^head$" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}"/>
        </rule> -->

        <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        <!-- All other URLs are mapped to the node.js site entry point -->
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="server.js"/>
        </rule>

      </rules>
    </rewrite>

    <!-- 'bin' directory has no special meaning in node.js and apps can be placed in it -->
    <security>
      <requestFiltering>
        <hiddenSegments>
          <remove segment="bin"/>
        </hiddenSegments>
      </requestFiltering>
    </security>

    <!-- Make sure error responses are left untouched -->
    <httpErrors existingResponse="PassThrough" />

    <!--
      You can control how Node is hosted within IIS using the following options:
        * watchedFiles: semi-colon separated list of files that will be watched for changes to restart the server
        * node_env: will be propagated to node as NODE_ENV environment variable
        * debuggingEnabled - controls whether the built-in debugger is enabled

      See https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config for a full list of options
    -->
    <!--<iisnode watchedFiles="web.config;*.js"/>-->
  </system.webServer>
</configuration>
```

With this setup it works, so there may be something in there for you too.

**Comment by shaydoc** [comment]
hey thanks,
 I was right there behind you... I was just realizing that same thing. Thanks so much for your assistance

Shay

**Comment by shaydoc** [comment]
I believe this is resolved, thanks to @benosman

**Comment by shaydoc** [comment]
While this works for the nuxt starter kit, it still does not quite play well with ExpressJS on Azure

![nuxt-express-azure](https://cloud.githubusercontent.com/assets/1378519/24502616/848273fa-1546-11e7-9749-99f297d6f400.png)

**Comment by shaydoc** [comment]
With this error resolved, I now get all the assets downloaded but I get a : 500 connect EACCES 127.0.0.1:80 error message on Azure

**Comment by benosman** [comment]
what port is express set to run on ? if it's set to 80 that would likely cause issues.

This may be related:
http://stackoverflow.com/questions/36293278/error-listen-eacces-0-0-0-080-node-on-azure-server-windows-server-2012-r2

**Comment by benosman** [comment]
by the way, you said you are building locally and deploying it - is that the case still?

I created a custom post deployment script to build after deployment - details of that here:

https://gist.github.com/benosman/c80653779f90a5d6fb0b95ad2654dc96

**Comment by shaydoc** [comment]
Hi, 
The ExpressJS api's are working perfectly well. All the issues are with the server render of the index.vue page.
Even the subroutes seem to work fine.

**Comment by benosman** [comment]
Hmm, unfortunately i'm not sure what to suggest then - it's the first time for me using windows / azure for a node app.

**Comment by shaydoc** [comment]
likewise

**Comment by shaydoc** [comment]
OK, I have everything aligned correctly now. I can categorically say the error in this is occuring on server renderinf of the /pages/index.vue component. Server side rendering of subroutes works, but the top level routes fail.

So now, I must trace the server rendering for the top level routes to see what is going on and why it cannot locate these bad boys.

**Comment by shaydoc** [comment]
finally got to the bottom of the error: it was the axios.get call in the "index.vue" that was blowing up.
this is because IISNODE uses named pipes for local connections i believe.
This meant during server render the call to express api "/api/users" was failing server side.
The fix is to simply included the fully qualified api location e.g. "http://myazure.website.net/api/users"
and all works.

Worth bearing in mind that iisnode is using a named pipe!

**Comment by pmgower** [comment]
@shaydoc how did you get your iisnode deployment to work?  Can you take a look at the issue I am having described in this [issue](https://github.com/nuxt/nuxt.js/issues/1489)?

**Comment by benmccallum** [comment]
Also worth pointing out that in package.json > scripts, if there is a start task it looks like Azure's kudu is trying to run it, so best just comment that out or rename it.

**Comment by CKGrafico** [comment]
If you need more examples, we have added this too to PWABuilder and is working well (including small changes)
https://github.com/pwa-builder/manifoldjs-site/tree/dev-vue

check:
`web.config`
`package.json (start task)`
`nuxt.config.js`
`server.js`

**Comment by benmccallum** [comment]
Nice @CKGrafico, good to see it's getting easier for folks. 

Any reason for keeping the `start` task? I have mine commented out and I guess Azure just runs `node server.js` by default. Just being explicit?

**Comment by CKGrafico** [comment]
Yes @benmccallum :) 
By the moment I still getting this error `connect EACCES 127.0.0.1:3000` I'm going to search for more info

**Comment by Domitnator** [comment]
Guys, 

Hopfully you can help me out: I have basically have the same setup as @CKGrafico (thanks for that) with a default nuxt cli generated project (just ran "vue init nuxt-community/starter-template CoodNuxt2", didnt changed any code but only updated nuxt to version 1.4.0) . But i keep getting a content decoding error in the webbrowser. 

![image](https://user-images.githubusercontent.com/13468638/39246588-4bdeecd8-4897-11e8-9bbe-2050ebde318e.png)

Any experience with that error?

I also did a request with Fiddler and i cannot discover anything strange. And in fiddler the webview just works:

![image](https://user-images.githubusercontent.com/13468638/39246723-b1aee860-4897-11e8-935e-49e31575f7a0.png)

I dont know where to start debugging this. Is this an issue in IISNode or my Nuxt configuration?

Hopefully someone can point me in the right direction?

**Comment by Eric-Bryan** [comment]
Hello everybody,
I have a sample Nuxt app.
I applied @benosman samples for "web.config" and "node_modules/nuxt/bin/nuxt-start".

1.
I have run "npm run generate" for that app.
And I have created a new web app in IIS 7.5 with iisnode (without Azure) with the directory "\.nuxt\dist" (from my app) called "nuxt" right under "Default Web App".
When I want to go to http://localhost/nuxt I get error 500.

2.
It is the same error (500) when I have run "npm run build" and have created a new app in IIS with the directory "\dist" called "nuxt2".

What have I missed ?
Do you have some advices ?
Thank you very much in advance.

**Comment by benmccallum** [comment]
@Eric-Bryan, you need to point the IIS website to the folder that contains your server.js. That folder should have things like your .nuxt/dist inside it. Does that make sense?

**Comment by Eric-Bryan** [comment]
@benmccallum : thank you for your answer.
Do I have to make the Web App point to the folder '/.nuxt' or '/.nuxt/dist' ?
Because only '/.nuxt' contains server.js.
Anyway, I have created a new Web App that points to '/.nuxt' and I still get error 500.

**Comment by CKGrafico** [comment]
can you use nuxt generate --spa and publish dist folder? like we do at https://github.com/CKGrafico/Frontend-Boilerplates/blob/nuxt-dev/package.json

**Comment by Eric-Bryan** [comment]
@CKGrafico : thank you for your answer.
I have run "nuxt generate --spa" and I added  the web.config from @benosman, but I still get error 500.
How does the package.json in your link fix my issue ?

**Comment by CKGrafico** [comment]
Do you have a repo? can you take a screenshot or something of your wwwroot at kudu? to enter to kudu is easy as for example https://mywebsite.azurewebsites.net ---> https://mywebsite.scm.azurewebsites.net

**Comment by Eric-Bryan** [comment]
@CKGrafico,
Here is my pages\index.vue :
![index vue](https://user-images.githubusercontent.com/39306123/40227997-96b56738-5a7f-11e8-9dfa-db58cf72de38.png)
Here is my project without node_modules folder:
[nux-axios-light.zip](https://github.com/nuxt/nuxt.js/files/2016310/nux-axios-light.zip)
Let me know if you need something else.

**Comment by CKGrafico** [comment]
You're using the 'copy pasted' web.config for node projects.
You don't have any server.js

1. Be sure that wou're publishing dist folder inside the wwwroot folder into your azure appservice (check with KUDU!!)

this will be a better web.config

```
<?xml version="1.0" encoding="utf-8"?>
<!--
     This configuration file is required if iisnode is used to run node processes behind
     IIS or IIS Express.  For more information, visit:

     https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config
-->

<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="SPA Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

Why? Because your site doesn't have backend :)

**Comment by Eric-Bryan** [comment]
@CKGrafico :
I have replaced my web.config by yours and I don't have error 500 but a blank page with an image : a little grey circle in the middle of the page which bounces.
The page source is :


<!DOCTYPE html>
<html data-n-head="">
  <head>
    <meta data-n-head="true" charset="utf-8"><meta data-n-head="true" content="width=device-width,initial-scale=1" name="viewport"><meta data-n-head="true" content="Nuxt.js project" name="description" data-hid="description"><title data-n-head="true">nuxt-axios</title><link href="/favicon.ico" rel="icon" data-n-head="true" type="image/x-icon"><link href="/_nuxt/manifest.11143408c65536d7667b.js" rel="preload" as="script"><link href="/_nuxt/vendor.3ff8556a09b164ff2c2b.js" rel="preload" as="script"><link href="/_nuxt/app.b3fbd67e9ea6bfe851e6.js" rel="preload" as="script"><link href="/_nuxt/pages_posts_index.f3549afb8c4cf675b451.js" rel="prefetch"><link href="/_nuxt/pages_posts__id.d2d8dcc96acd8b67bc09.js" rel="prefetch"><link href="/_nuxt/pages_page_essai_index.b019f3dd3aa0f1edcc8b.js" rel="prefetch"><link href="/_nuxt/pages_index.e68f0c8799f779c7a7f8.js" rel="prefetch"><link href="/_nuxt/layouts_default.e7bfe3a4a42fdabf27d0.js" rel="prefetch">
  </head>
  <body data-n-head="">
    <div id="__nuxt"><style>#__nuxt,body,html{background-color:#fff;width:100%;height:100%;display:flex;justify-content:center;align-items:center;margin:0;padding:0}.spinner{width:40px;height:40px;margin:100px auto;background-color:#dbe1ec;border-radius:100%;-webkit-animation:sk-scaleout 1s infinite ease-in-out;animation:sk-scaleout 1s infinite ease-in-out}@-webkit-keyframes sk-scaleout{0%{-webkit-transform:scale(0)}100%{-webkit-transform:scale(1);opacity:0}}@keyframes sk-scaleout{0%{-webkit-transform:scale(0);transform:scale(0)}100%{-webkit-transform:scale(1);transform:scale(1);opacity:0}}</style><div class="spinner">  <div class="double-bounce1"></div>  <div class="double-bounce2"></div></div></div>
  <script src="/_nuxt/manifest.11143408c65536d7667b.js" type="text/javascript"></script><script src="/_nuxt/vendor.3ff8556a09b164ff2c2b.js" type="text/javascript"></script><script src="/_nuxt/app.b3fbd67e9ea6bfe851e6.js" type="text/javascript"></script>

Any ideas ?
Thanks in advance.

**Comment by Eric-Bryan** [comment]
@CKGrafico :
I have replaced my web.config by yours and I don't have error 500 but a blank page with an image : a little grey circle in the middle of the page which bounces.
The page source is :

`
<!DOCTYPE html>
<html data-n-head="">
  <head>
    <meta data-n-head="true" charset="utf-8"><meta data-n-head="true" content="width=device-width,initial-scale=1" name="viewport"><meta data-n-head="true" content="Nuxt.js project" name="description" data-hid="description"><title data-n-head="true">nuxt-axios</title><link href="/favicon.ico" rel="icon" data-n-head="true" type="image/x-icon"><link href="/_nuxt/manifest.11143408c65536d7667b.js" rel="preload" as="script"><link href="/_nuxt/vendor.3ff8556a09b164ff2c2b.js" rel="preload" as="script"><link href="/_nuxt/app.b3fbd67e9ea6bfe851e6.js" rel="preload" as="script"><link href="/_nuxt/pages_posts_index.f3549afb8c4cf675b451.js" rel="prefetch"><link href="/_nuxt/pages_posts__id.d2d8dcc96acd8b67bc09.js" rel="prefetch"><link href="/_nuxt/pages_page_essai_index.b019f3dd3aa0f1edcc8b.js" rel="prefetch"><link href="/_nuxt/pages_index.e68f0c8799f779c7a7f8.js" rel="prefetch"><link href="/_nuxt/layouts_default.e7bfe3a4a42fdabf27d0.js" rel="prefetch">
  </head>
  <body data-n-head="">
    <div id="__nuxt"><style>#__nuxt,body,html{background-color:#fff;width:100%;height:100%;display:flex;justify-content:center;align-items:center;margin:0;padding:0}.spinner{width:40px;height:40px;margin:100px auto;background-color:#dbe1ec;border-radius:100%;-webkit-animation:sk-scaleout 1s infinite ease-in-out;animation:sk-scaleout 1s infinite ease-in-out}@-webkit-keyframes sk-scaleout{0%{-webkit-transform:scale(0)}100%{-webkit-transform:scale(1);opacity:0}}@keyframes sk-scaleout{0%{-webkit-transform:scale(0);transform:scale(0)}100%{-webkit-transform:scale(1);transform:scale(1);opacity:0}}</style><div class="spinner">  <div class="double-bounce1"></div>  <div class="double-bounce2"></div></div></div>
  <script src="/_nuxt/manifest.11143408c65536d7667b.js" type="text/javascript"></script><script src="/_nuxt/vendor.3ff8556a09b164ff2c2b.js" type="text/javascript"></script><script src="/_nuxt/app.b3fbd67e9ea6bfe851e6.js" type="text/javascript"></script>
`

Any ideas ?
Thanks in advance.

**Comment by Eric-Bryan** [comment]
Sorry I cannot paste the whole page source code, so I send it with an attached file :
[Page1.txt](https://github.com/nuxt/nuxt.js/files/2016968/Page1.txt)

**Comment by CKGrafico** [comment]
Hello I'm not asking for your source

![](https://i.imgur.com/BBrrm4k.png)

**Comment by Eric-Bryan** [comment]
Hello @CKGrafico  :
Sorry for the delay.
In fact, I don't use Azure, I only have IIS 7.5 on my server (localhost for instant).
So I don't use Kudu.
Does it make a difference with the configurations (web.config, ...) you use ?
Does your configurations only work for Azure, and not for IIS on local ?

**Comment by sergeos** [comment]
also interesting, i'm asking same question like **Eric-Bryan** there:
[https://gist.github.com/benmccallum/226ae1b428157b9d5998a5ba27eadf59#gistcomment-2676440](url)

**Comment by CKGrafico** [comment]
Actually in my projects I'm using nuxt only as a generated spa 'nuxt generate --spa' and I have backend with net core.

This was the best way

**Comment by horihiro** [comment]
FYI about this issue.
I published a template of nuxt.js/express for Azure Web Apps.

[horihiro/nuxt-express-azure-webapps](https://github.com/horihiro/nuxt-express-azure-webapps)

Please try this.
