### ISSUE TITLE
Turn off Strict Mode in Vuex Module Mode

### ISSUE THREAD

**Issue by jafri** [nuxt/nuxt.js#4650]
### What problem does this feature solve?

As non-module mode for Vuex is deprecated, users need the ability to turn off strict mode.

### What does the proposed changes look like?

Allow users to turn off strict mode by passing a config in nuxt.config.js

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8378">#c8378</a>)</em></sub></div>

**Comment by manniL** [comment]
I don't see a problem in adding such a configuration file *but* what are the benefits/use-cases?

**Comment by jafri** [comment]
Turning off strict mode in Nuxt currently requires using the deprecated `store/index.js`, look at https://github.com/nuxt/nuxt.js/issues/1521

The benefit and use-cases are typically two-way binding of Vuex stored properties, storing properties managed by outside libraries such as chrome extensions and in general, turning it off in production to not break the page.

**Comment by manniL** [comment]
Indeed, that works! :relaxed: 

https://github.com/nuxt/nuxt.js/blob/39b558f59c0ecb5aa40bf709ca5dff83a151b20b/packages/vue-app/template/store.js#L75-L81

PS: Strict is disabled in prod anyway because it degrades perf.

Closing here :relaxed:
