### ISSUE TITLE
filter illegal style

### ISSUE THREAD

**Issue by tangjinzhou** [nuxt/nuxt.js#4652]
### What problem does this feature solve?

fix inconsistent style in vue vs nuxt.
This template: `<h1 :style="{height: null, color: 'red'}">Welcome!</h1>`
will render in vue: `<h1 style="color: red;">Welcome!</h1>`
But render in nuxt:` <h1 style="height: null; color: red;">Welcome!</h1>`

In fact, in the development environment, after the `js` is rendered again, the filtered html can also be obtained.
Unfortunately, in the production environment we get html that does not filter illegal values.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8381">#c8381</a>)</em></sub></div>

**Comment by manniL** [comment]
Gone in the latest Vue version (`yarn upgrade --latest` should do the trick).
