### ISSUE TITLE
Route meta fields

### ISSUE THREAD

**Issue by samturrell** [nuxt/nuxt.js#466]
Hi there,

Is it possible to define route meta fields as per https://router.vuejs.org/en/advanced/meta.html ?

Cheers.

**Comment by ausir0726** [comment]
I think nuxt.js use the [middleware](https://nuxtjs.org/guide/routing#middleware) for check or do something before route .

you can define middleware in you page vue file 
`index.vue`
```js
export default {
  middleware: 'auth'
}
```
`middleware/auth.js`
```js
export default function ({ store, redirect }) {
  if (store.getters.isAuth) {
    return redirect('/')
  }
}
```

or check this [Auth0 example](https://github.com/nuxt/example-auth0) form nuxt.js

**Comment by samturrell** [comment]
The thing i'm looking for is a per-route config that i can access in my layout, which changes certain things visually based on the route. Before migrating the project to nuxt I achieved this using by setting data on the route as per https://router.vuejs.org/en/advanced/meta.html

**Comment by alexchopin** [comment]
Hi @samturrell , have you tried to use `store` with getters?

**Comment by uptownhr** [comment]
@alexchopin would it be difficult to expose to meta property on a page component? Trying to implement a page crumbs implementation right now and being ability to set the meta property on the page routes would greatly simplify this.

**Comment by Atinux** [comment]
Hi @uptownhr,

I am actually implementing `meta` property in page components and will be available in next release :)

**Comment by uptownhr** [comment]
@Atinux I'm assuming this is a part of 1.0, but no docs yet. Have any info for me to use right now?

**Comment by uptownhr** [comment]
checking out, https://github.com/nuxt/nuxt.js/blob/dev/lib/common/utils.js doesn't look like the router meta is being populated in any way. Are we planning on adding this feature later?

**Comment by Atinux** [comment]
@uptownhr actually it's in `app/utils.js, see https://github.com/nuxt/nuxt.js/blob/dev/lib/app/utils.js#L96

Actually you can play with it easily by adding a `meta` property in your page and ready it in your middlewares (ex: https://github.com/nuxt/nuxt.js/blob/20b548a17523e54d7f24cede4ada358d359e6f78/test/fixtures/basic/middleware/meta.js)

**Comment by uptownhr** [comment]
Oh nice. Let me give it a shot.

**Comment by daiyanze** [comment]
There is a good practice here:
https://github.com/nuxt/nuxt.js/issues/1687#issuecomment-331870619
