### ISSUE TITLE
Dynamic page recreated on param change

### ISSUE THREAD

**Issue by christopheschwyzer** [nuxt/nuxt.js#4663]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/yq22jokp0v](https://codesandbox.io/s/yq22jokp0v)

### Steps to reproduce

- Go to `/foo/1`
- Open console
- Click `Bar 2` link (The link only changes the bar param -> see URL)
- Notice in the console that the page is recreated 

Reproduction repo: https://github.com/christopheschwyzer/nuxt-dynamic-routes-bug
Deployed also here: https://condescending-bhabha-c04b2c.netlify.com/foo/1

### What is expected ?

I understand from the vue-router documentation that the component shouldn't be recreated in such case?

```
Note: If the destination is the same as the current route and only params are changing (e.g. going from one profile to another /users/1 -> /users/2), you will have to use beforeRouteUpdate to react to changes (e.g. fetching the user information).
```

### What is actually happening?

Page is recreated. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8385">#c8385</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Hi @christopheschwyzer , the issue is because the `key` of `RouterView` is different in `/foo/1` and `/foo/2`, for now you can specify `key` to ensure view is same one:

```vue
<script>
export default {
  key: '_bar',
  created() {
    console.log("created");
  }
};
</script>
```

**Comment by christopheschwyzer** [comment]
@clarkdo Thank you, works great!

As I'm not sure what the (default) behavior should be I'll keep the issue open - but feel free to close it.

**Comment by manniL** [comment]
Well, either it has to be well documented or changed ☺️ 

I think such behavior is needed for transitions but I could be wrong.

cc @pi0 (is that behavior intended or even required?)

**Comment by Atinux** [comment]
Hey there 👋 

Indeed, the `key` is made for the transitions to work seamlessly by default. This behaviour will be better documented in the future, thank you for reporting it @christopheschwyzer 

@clarkdo's comment should solve your issue if you don't want any re-creation of the view :)
