### ISSUE TITLE
app.req is undefined when clicking on <nuxt-link>

### ISSUE THREAD

**Issue by xxyyzz2050** [nuxt/nuxt.js#4664]
pages/_.vue :
```
<template>
 <nuxt-link to="/">Go</nuxt-link>
</template>

<script>
 export default {
  async asyncData(app) {
  console.log(app.req)
}
</script>
```

when I click on this link an error occures whitch is app is undefined

how to handle this rout?

**Comment by yann-yinn** [comment]
According to the [documentation](https://nuxtjs.org/guide/async-data#use-code-req-code-code-res-code-objects), "req" and "res" are only available from server side , you have to check if you are on server side first 

```js
export default {
  async asyncData ({ req, res }) {
    // Please check if you are on the server side before
    // using req and res
    if (process.server) {
     return { host: req.headers.host }
    }

    return {}
  }
}
```
