### ISSUE TITLE
Minimum duration of execution for loadingIndicator

### ISSUE THREAD

**Issue by ch3rn1k** [nuxt/nuxt.js#4666]
Hello, any way to set minimum duration for loadingIndicator? Thanks!

P. S. https://nuxtjs.org/api/configuration-loading-indicator

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8389">#c8389</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Hi @ch3rn1k , please try `loading.duration`
Doc: https://nuxtjs.org/api/configuration-loading#customize-the-progress-bar

**Comment by manniL** [comment]
Instead of having a minimum threshold to avoid visual glitches, I'd suggest using the provided settings to completely hide the loadingIndicator if the request finishes fast enough.

**Comment by ch3rn1k** [comment]
Well, I was talking about "The loadingIndicator Property" (https://nuxtjs.org/api/configuration-loading-indicator) in SPA application...

**Comment by clarkdo** [comment]
@ch3rn1k Sorry, for now there is no option for setting duration on internal loading template, you can define custom template and implement what you need, like:

```js
// nuxt.config.js
loadingIndicator: {
  name: '@/view/loading.html'
}
```

**Comment by ch3rn1k** [comment]
Ah, okay, thanks!
