### ISSUE TITLE
generate  middleware error  Cannot load components DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by w550** [nuxt/nuxt.js#468]
https://github.com/nuxt/example-auth0

git clone https://github.com/nuxt/example-auth0.git
cd example-auth0
npm install
npm run generate 

copy dist  in nginx html 

error:
 Cannot load components DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

**Comment by dieguezz** [comment]
I am receiving the same error when loading one of my pages (/todo) from a production build from the server. Its working in dev (even loading from server)

https://github.com/dieguezz/nuxtpoc

**Comment by dieguezz** [comment]
Ok, on my side, it was failing because i had to update node version.

**Comment by Atinux** [comment]
It's not nuxt.js related but I believe from Nginx @w550 

See example-auth0 generated and hosted on a static server: https://nuxt-auth0.surge.sh

Think to upgrade your dependencies to use the latests modules.

**Comment by rvanzon** [comment]
@w550 @dieguezz did you guys fix the problem? I am facing the same :-(
