### ISSUE TITLE
TypeError: Cannot read property 'client' of null

### ISSUE THREAD

**Issue by PeterKnight** [nuxt/nuxt.js#4683]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/nuxt-community/electron-template](https://github.com/nuxt-community/electron-template)

### Steps to reproduce

Install the nuxt-community electron template, upgrade all packages and run it (npm run dev).

### What is expected ?

Window loading without errors

### What is actually happening?

Nuxt crashes on build, on @nuxt\server\dist\server.js:541:31 it produces a type error because `this` is undefined.

### Additional comments?

Downgrading to Nuxt v2.2.0 works

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8400">#c8400</a>)</em></sub></div>

**Comment by Flinn33** [comment]
You need to replace 
```
		const pollServer = () => {
			http.get(_NUXT_URL_, (res) => {
				if (res.statusCode === 200) { win.loadURL(_NUXT_URL_) } else { setTimeout(pollServer, 300) }
			}).on('error', pollServer)
		}
		pollServer()
```
by 
```
  nuxt.hook('build:done', () => {
    win.loadURL(_NUXT_URL_) 
  })
```

**Comment by PeterKnight** [comment]
That works perfectly now, thank you @Flin33!

**Comment by manniL** [comment]
@PeterKnight @Flinn33 feel free to create a PR for the corresponding template
