### ISSUE TITLE
publicPath can cause webpack-hot-middleware matched path fail

### ISSUE THREAD

**Issue by 8-shen** [nuxt/nuxt.js#4685]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/doubi-NO1/egg-nuxt-demo](https://github.com/doubi-NO1/egg-nuxt-demo)

### Steps to reproduce

1. git clone the repo
2. npm install
3. npm run dev

### What is expected ?

__webpack_hmr/client  request can be response

### What is actually happening?

An error at terminal like this:

ERROR 25775 [-/undefined/-/11ms GET /__webpack_hmr/client] nodejs.ECONNRESETError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
headerSent: true
name: "ECONNRESETError"
pid: 25775

### Additional comments?

I found the webpack-hot-middleware can't match the nuxt publicPath,  and the nuxt publicPath has a default value  /_nuxt/

https://github.com/webpack/webpack-dev-middleware/blob/master/lib/util.js#L73

https://github.com/nuxt/nuxt.js/blob/8786ff731767425bb0c1c72af6d8a8895155acf5/packages/config/src/config/build.js#L13

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8403">#c8403</a>)</em></sub></div>

**Comment by manniL** [comment]
@8-shen is this reproducible with the standard `nuxt` package? If so, please add a reproduction for it. :)

**Comment by 8-shen** [comment]
> @8-shen is this reproducible with the standard `nuxt` package? If so, please add a reproduction for it. :)

Thank you for your reply.
This is a nuxt plugin for eggjs, and the plugin's repo is here:
[https://github.com/doubi-NO1/egg-nuxt](https://github.com/doubi-NO1/egg-nuxt)

**Comment by manniL** [comment]
@8-shen Thanks for the info! To make sure it's not cause by the extra library, could you try to reproduce it only with the `nuxt` package anyway? 🙏

**Comment by 8-shen** [comment]
@mattjcowan I found the bug's reason, cause for the eggjs will set the Content-Length with __webpack_hmr/client, remove this header can resolve the problem.
https://github.com/doubi-NO1/egg-nuxt/blob/master/app/middleware/nuxtrender.js#L22
Anyway, thanks for your reply again:)
