### ISSUE TITLE
generate:page hooks not working

### ISSUE THREAD

**Issue by buskerlic** [nuxt/nuxt.js#4688]
Hi, I want to edit a generated index.html file by using hooks configuration in nuxt.config.js.
but it seems not working. My nuxt.config.js is like below

<pre>
module.exports = {
  mode: 'spa',
  generate: {
    fallback: 'index.html'
  },
  render: {
    resourceHints: false
  },
  hooks: {
    generate: {
      page({route, path, html}) {
         console.log('html: ', html);
      },
      done(nuxt, errors) {
         console.log('done');
      }
    },
  },
  ...
};
</pre>

generate:done is working but generate:page is not working. Am i using it wrong?

**Comment by buskerlic** [comment]
Hi, It is working fine. Please close this issue. Thank you.

**Comment by bigoper** [comment]
@sally-belly 
What was the issue? and how did you solve it?

**Comment by antoniopol06** [comment]
@sally-belly  @bigoper how did you solve it? I have the same problem, generate:page hook was not being executed
