### ISSUE TITLE
Inconsistent behavior when using `head` meta property between nuxt.config.js and pages/layouts.

### ISSUE THREAD

**Issue by mattjcowan** [nuxt/nuxt.js#4694]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/jzw6n96vj3](https://codesandbox.io/s/jzw6n96vj3)

### Steps to reproduce

The sample demo just shows a very simple example of the problem. The app is in 'spa' mode.
1. Load jquery as part of `head` in nuxt.config.js, and reference `$` in the mounted event of a page, and it works fine.
2. Load jquery as part of `head` in pages/layouts, and reference `$` in the mounted event of a page, and you get the error: `$ is undefined`

The problem is the inconsistency of using `head` between nuxt.config and pages/layouts. Or at least the difference imo should be documented.

### What is expected ?

`head` should behave the same in both nuxt.config.js and pages/layouts.
In `spa` mode and for `nuxt generate`, I would expect that any link/script loaded from `head` would all get placed at the top of the <head> element in the html.

### What is actually happening?

`head` does not behave the same, depending on where you implement it. Instead, only nuxt.config.js ones do. The ones loaded from pages/layouts are dynamically loaded and get placed AFTER the code that is compiled from the *.vue files.

### Additional comments?

The point of having `head` is to give developers the ability to guarantee loading of scripts and css before anything else in the app or on the page. At least that's how I interpret it. Instead, the expected behavior is only exhibited when using nuxt.config.js, and not pages/layouts as the documentation seems to suggest.

I have an app that uses a variety of layouts (i.e.: frontend, backend, etc..). We don't want to have to put all the scripts for all sections of the site into nuxt.config.js. We also use the `splitChunks.layouts: true feature`, as well as `extractCSS`. We're stuck with themes with JS that aren't available in es6 and are full of IIFEs.  We need to make sure the scripts in each section of the site are loaded and available before in code inside the mounted event fires.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8412">#c8412</a>)</em></sub></div>

**Comment by 8-shen** [comment]
@mattjcowan  I found the bug's reason, cause for the eggjs will set the Content-Length  with __webpack_hmr/client, remove this header can resolve the problem.
[https://github.com/doubi-NO1/egg-nuxt/blob/master/app/middleware/nuxtrender.js#L22](https://github.com/doubi-NO1/egg-nuxt/blob/master/app/middleware/nuxtrender.js#L22)
Anyway, thanks for your reply again:)

**Comment by voxivoid** [comment]
Does it work for you when you set it up on nuxt.config? I tried it with your code and the behavior is the same -> it does not work (check: https://vgy.me/fDTzaS.png) and I've restarted the sandbox after the changes. I'm having the same problem in #4715. I think that there is a problem when the mode is set to `SPA` because it works well when the mode is `universal`

**Comment by mattjcowan** [comment]
@voxivoid yes, when you comment out the `script` in the page, and uncomment the `script` in nuxt.config.js, and restart the app, it works for me .. and i think you're right that this may just be a `spa` mode issue

**Comment by mattjcowan** [comment]
I wonder if the only way to handle this then for `spa` mode is something like https://github.com/nuxt/nuxt.js/issues/1785, with multiple nuxt.config.js files and srcDir/buildDir combinations.
