### ISSUE TITLE
eslint ignore

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#470]
I require a pagination plugin js file ,when I run dev, I got the error from lint.

But I don't want to lint the external js library. So what should I do?

**Comment by ausir0726** [comment]
you can make a `.eslintignore` file in project folder 
and add code like this .. `this for my setting`
 `.eslintignore` 
```
# js vendor file with import/require
vendor/js/**
# static vendor file . use with nuxt.config.js script
static/**
# dependencies
node_modules
# Nuxt build
.nuxt
# Nuxt generate
dist
```

and  if you have use `yarn run lint` please modify to 
`package.json`
```
"lint": "eslint --ext .js,.vue --ignore-path .eslintignore .",
```

**Comment by antoniojtorres** [comment]
Any plans to roll this into a version? Would be useful, linter freaked out when I added a plugin and linted the Tapable library, found errors.
