### ISSUE TITLE
TypeScript type definition resolution issue

### ISSUE THREAD

**Issue by moritzsternemann** [nuxt/nuxt.js#4703]
### Version

[nuxt-ts-edge](https://github.com/nuxt.js/releases/tag/nuxt-ts-edge)

### Reproduction link

[https://github.com/moritzsternemann/nuxt-typescript-cloudkit-problem](https://github.com/moritzsternemann/nuxt-typescript-cloudkit-problem)

### Steps to reproduce

My project uses Apples CloudKit JS library and a type definition file from https://github.com/typescriptlibs/tsl-apple-cloudkit, later referenced as apple-cloudkit.d.ts.

Using any type from apple-cloudkit.d.ts after importing it works as expected, however using a class which makes use of a type from apple-cloudkit.d.ts causes an error. See the reproduction project for a detailed example.

### What is expected ?

The type definition file should be imported and it's declarations should be usable.

### What is actually happening?

An error is thrown:

This relative module was not found:
Module not found: Error: Can't resolve './apple-cloudkit'

### Additional comments?

I don't know if this is a problem with Nuxt.js (or the TypeScript related config), TypeScript or maybe even webpack. Any help and comments are appreciated.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8417">#c8417</a>)</em></sub></div>

**Comment by manniL** [comment]
cc @kevinmarrec @hartmut-co-uk

**Comment by aldarund** [comment]
@manniL  Its not a nuxt releated `problem`. I commented on SO based on kevinmarrec insights.
@moritzsternemann you can come to our discord server and someone might be able to help you.

**Comment by kevinmarrec** [comment]
@moritzsternemann As @aldarund said, please look at the comment on StackOverflow, and as it's not related to Nuxt : if you face any issues using the types of the library you want to use, please open an issue on their repo :)
