### ISSUE TITLE
Unexpected token < - Missing stack frames

### ISSUE THREAD

**Issue by priyeshvadhiya** [nuxt/nuxt.js#4705]

**Comment by siberiadev** [comment]
+1 same issue, when I use ssr mode for nuxt.js i got error on main page:
Unexpected token import (Missing stack frames)
Please anyone help us to solve this problem.
"vue": "^2.5.17",
"nuxt": "^2.3.2",

**Comment by willin** [comment]
npx create a new project and then run `yarn dev` 

```
SyntaxError
Unexpected identifier
vm.js
Missing stack frames
```

**Comment by milgron** [comment]
> 
> 
> npx create a new project and then run `yarn dev`
> 
> ```
> SyntaxError
> Unexpected identifier
> vm.js
> Missing stack frames
> ```

The same here..

**Comment by jdsans** [comment]
Having the same problem for newly created project

**Comment by willin** [comment]
@jdsans its not about bootstrap. 'coz i don't even use it.

**Comment by developius** [comment]
@willin I was having this issue with `vue2-google-maps` and I fixed it by changing my plugin configuration so that it's only loaded client-side:

```js
// plugins/googlemaps.js

import Vue from 'vue'
import * as VueGoogleMaps from 'vue2-google-maps'

Vue.use(VueGoogleMaps, {
  load: {
    key: 'my_key',
    libraries: 'places', 
  }
})
```
```js
// nuxt.config.js
export default {
  // snip
  plugins: [
    { ssr: false, src: '~plugins/googlemaps.js' }
  ]
 // snip
}
```

**Comment by jcsky** [comment]
mode: 'client' is work too
```
// nuxt.config.js
export default {
  plugins: [
    { src: '~plugins/googlemaps.js', mode: 'client' }
  ]
}
```
Note: Since Nuxt.js 2.4, mode has been introduced as option of plugins to specify plugin type, possible value are: client or server. ssr: false will be adapted to mode: 'client' and deprecated in next major release.

**Comment by ruthirlekar92** [comment]
@jcsky 
I am using vue2-google-maps and my nuxt project has nuxt 2.13

I am still getting the same error please help

`plugins: [
    {
      src: "~/plugins/onload.api.js",
      mode: "server"
    },
    {
      src: "~/plugins/onload.component.js",
      mode: "client"
    },
    {
      src: "~/plugins/onload.client.js",
      mode: "client"
    },
    {
      src: "~/plugins/gmap.js",
      mode: "client"
    }
  ]`

**Comment by manniL** [comment]
> 
> 
> @jcsky
> I am using vue2-google-maps and my nuxt project has nuxt 2.13
> 
> I am still getting the same error please help
> 
> `plugins: [ { src: "~/plugins/onload.api.js", mode: "server" }, { src: "~/plugins/onload.component.js", mode: "client" }, { src: "~/plugins/onload.client.js", mode: "client" }, { src: "~/plugins/gmap.js", mode: "client" } ]`

https://github.com/xkjyeah/vue-google-maps/issues/498#issuecomment-429566868

**Comment by ruthirlekar92** [comment]
@manniL 
The problem occurs only when the page is reload.
this is my plugin gmaps.js
`import Vue from "vue";
import * as VueGoogleMaps from "vue2-google-maps";
Vue.use(VueGoogleMaps, {
  load: {
    key: "APIKEY"
  }
});
` 
this the nuxt.config.js
`plugins: [
    {
      src: "~/plugins/gmap.js",
      mode: "client"
    }
  ],
  build: {
        transpile: [/^vue2-google-maps($|\/)/], 
  },
`

**Comment by PLQin** [comment]
我也遇到了这个问题，已经解决。建议：使用二分法进行排查，即注释或还原到正常的代码，然后逐步添加新代码；

I also encountered this problem, which has been solved. Suggestion: use dichotomy to check, that is, comment or restore to normal code, and then gradually add new code;
