### ISSUE TITLE
modern: SafariFix not injected correctly when build modern=client

### ISSUE THREAD

**Issue by Yimiprod** [nuxt/nuxt.js#4707]
### Version

[v2.3.1](https://github.com/nuxt.js/releases/tag/v2.3.1)

### Reproduction link

[https://85lll09l8.sse.codesandbox.io](https://85lll09l8.sse.codesandbox.io)

### Steps to reproduce

Open the url in Safari (or any browser).
Open the sources (pomme+alt+u on Mac)
There's no sign of the [SafariFix](https://github.com/nuxt/nuxt.js/blob/0f104aa58890f7b06837a05fc67718bf7822264a/packages/webpack/src/plugins/vue/modern.js#L108)
You can see the sources of the [sandbox here](https://codesandbox.io/s/85lll09l8)

### What is expected ?

I should have found the [SafariFix](https://github.com/nuxt/nuxt.js/blob/0f104aa58890f7b06837a05fc67718bf7822264a/packages/webpack/src/plugins/vue/modern.js#L108) and thus, fix a problem Safari 10 has with module.

### What is actually happening?

Safari 10 break the website since it can't handle correctly the nomodule attribute and try to execute the old school script anyway.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8423">#c8423</a>)</em></sub></div>

**Comment by manniL** [comment]
@Yimiprod Does it work when using `mode=server`?

cc @clarkdo ☺️

**Comment by Yimiprod** [comment]
Not tested yet in `modern='server'`.

**Comment by manniL** [comment]
@Yimiprod It'd be great if you could do that ☺️

**Comment by clarkdo** [comment]
@Yimiprod Fixed in https://github.com/nuxt/nuxt.js/commit/ecf76d91f1bec8dcab8f2c7715e0e07a19d0b6fe
