### ISSUE TITLE
Root css variable not included in the html

### ISSUE THREAD

**Issue by jessielaf** [nuxt/nuxt.js#4711]
### Version

[v1.4.5](https://github.com/nuxt.js/releases/tag/v1.4.5)

### Reproduction link

[https://app.effe-planning.com/](https://app.effe-planning.com/)

### Steps to reproduce

Add the :root in a css file
![Code_2019-01-08_15-57-35.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/bfb79c20-1355-11e9-86a6-97d75024277c.png)

Add the css file to the css attribute to the nuxt.config.js
  css: [
    '~/assets/style/root.css'
  ]

Check run the nuxt project
Check the browser for the :root selector

### What is expected ?

![chrome_2019-01-08_15-58-24.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/e204e3f0-1355-11e9-86a6-97d75024277c.png)

But then with my variables

### What is actually happening?

![chrome_2019-01-08_15-58-49.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/ed1a1c10-1355-11e9-86a6-97d75024277c.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8427">#c8427</a>)</em></sub></div>

**Comment by manniL** [comment]
Is fixed in nuxt-edge. See https://codesandbox.io/s/github/manniL/nuxt-root-css-custom-properties/tree/master/
