### ISSUE TITLE
nuxt build error exits with code 0

### ISSUE THREAD

**Issue by sh** [nuxt/nuxt.js#4718]
### Version

[edge](https://github.com/nuxt.js/releases/tag/edge)

### Reproduction link

[https://github.com/sh/nuxt-build-error-should-exit](https://github.com/sh/nuxt-build-error-should-exit)

### Steps to reproduce

1. `npm run build` in the sample repo (or any repo that throws a build error)
2. 
```
ERROR  Nuxt Build Error                                                                                                                                                                             09:35:12

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack-edge/dist/webpack.js:5213:15)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

3. `echo $?` returns 0

### What is expected ?

A failing build should exit with status > 0

### What is actually happening?

Build fails, logs error and exits with status code 0

### Additional comments?

We're building a docker image in our CI/CD pipeline, the image was built successfully although the build logged an error but did exit with status 0 (all good)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8433">#c8433</a>)</em></sub></div>

**Comment by manniL** [comment]
Same for generate as it seems
![image](https://user-images.githubusercontent.com/640208/50914162-d9b34880-142d-11e9-9d65-ac80f97786b3.png)

([full deploy log](https://app.netlify.com/sites/developmint/deploys/5c361f99cce0bd000c98885c))
