### ISSUE TITLE
I archive this with [`svg-sprite-loader`](https://github.com/kisenka/svg-sprite-loader) and some nuxt configs.

### ISSUE THREAD

**Issue by yun313350095** [nuxt/nuxt.js#4719]
I archive this with [`svg-sprite-loader`](https://github.com/kisenka/svg-sprite-loader) and some nuxt configs.
1. Create a folder at `assets/svg` and put all your svg files in it.
2. Create custom webpack loader rules in `nuxt.config.js` to handle svg files:

```javascript
build: {
    loaders:[
      {
        test: /\.svg$/,
        include: /assets\/svg/,
        loader: 'svg-sprite-loader?' + JSON.stringify({
          name: '[name]',
          prefixize: false
        })
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'url-loader',
        exclude: /assets\/svg/,
        options: {
          limit: 1000, // 1K limit
          name: 'img/[name].[hash:8].[ext]'
        }
      }
    ]
  }
```
3. Create a plugin js file that handle svg files. The `svg-sprite-loader` will then catch all the imported svg files and insert them at the beginning of document body, and this can only be done at browser enviroment, so we will use `process.BROWSER_BUILD` provided by nuxt to make it run only  in browser enviroment.

```javascript
// plugins/svg-sprite-loader.js
// import only in browser
if (process.BROWSER_BUILD) {
  // import all svgs
  var files = require.context('~assets/svg', false, /\.svg$/)
  files.keys().forEach(files)
}
```

4. Add `plugins/svg-sprite-loader.js` into `nuxt.config.js` to make it work:

```javascript
plugins: [
    '~plugins/svg-sprite-loader'
  ]
```

with all above configs, you can use svgs by its filename such as: `<use xlink:href="#upvote"></use>`

Hope this helps! 😄

_Originally posted by @aprilandjan in https://github.com/nuxt/nuxt.js/issues/156#issuecomment-274330822_

**Comment by bartdominiak** [comment]
You can also check my version here https://github.com/bartdominiak/nuxt-svg-sprite-loader

**Comment by manniL** [comment]
Or probably https://github.com/nuxt-community/svg-sprite-module
