### ISSUE TITLE
Files not from root

### ISSUE THREAD

**Issue by demyan1411** [nuxt/nuxt.js#472]
Hello, I want after generate css js images files, src not from root, not src='/bundle.js', but just like that src='bundle.js' , how can I do it?

**Comment by alexchopin** [comment]
Hi, can you explain more? Are you talking about static generated app ?

**Comment by demyan1411** [comment]
Yes, I talk about static generated app

**Comment by ausir0726** [comment]
@demyan1411  be my guess ...

Do you want deploy generate file to a sub folder on web host ?
if I guess correct , you need setup router.base in `nuxt.config.js`

```js
module.exports = {
  router: {
    base: '/app/'
  }
}
```
for doc reference
https://nuxtjs.org/api/configuration-router/

it you don't have change setting , nuxt will generate all js and asset to _nuxt folder 
if you want change folder name you can use `build.publicPath`

```js
module.exports = {
  build: {
    publicPath: 'https://cdn.nuxtjs.org'
  }
}
```
for doc reference
https://nuxtjs.org/api/configuration-build/#publicpath

hope this two information can help you .

**Comment by demyan1411** [comment]
Thanks!!
