### ISSUE TITLE
Issue with middleware when layout uses Vue.extend

### ISSUE THREAD

**Issue by chanlito** [nuxt/nuxt.js#4724]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/chanlito/nuxt-middleware-bug](https://github.com/chanlito/nuxt-middleware-bug)

### Steps to reproduce

So middleware doesn't seem to work when my layout is written like below:

```vue
<template>
  <div>
    <div>Layout</div>
    <nuxt/>
  </div>
</template>

<script>
import Vue from 'vue';

export default Vue.extend({ // <-- this doesn't
  middleware: 'ok',
});
</script>
```

But this works.

```vue
<template>
  <div>
    <div>Alt Layout</div>
    <nuxt/>
  </div>
</template>

<script>
export default {
  middleware: 'ok',
};
</script>
```

### What is expected ?

Middleware should work fine with layout created with `Vue.extend`

### What is actually happening?

Not working.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8437">#c8437</a>)</em></sub></div>

**Comment by chanlito** [comment]
Weird thing is that it works on pages.

**Comment by Atinux** [comment]
Hey @chanlito 

Thank you very much for this bug report and reproduction link.

This issue should be resolved with https://github.com/nuxt/nuxt.js/commit/521ac20e298b6a7f090cdedce63098f2c234417f and should be available in next version of `nuxt-edge` tonight :)

**Comment by chanlito** [comment]
Seems to be working now.
