### ISSUE TITLE
Lazy loading functional template components fails

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4727]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/github/manniL/nuxt-no-functional-template-components/tree/master/](https://codesandbox.io/s/github/manniL/nuxt-no-functional-template-components/tree/master/)

### Steps to reproduce

1. Open the CodeSandbox
2. Click on the lazyload link
3. See error similar to https://github.com/nuxt/nuxt.js/issues/2565
4. open the direct link
5. see it works
6. open the lazy-load link again
7. as it's cached, you probably see a normal page

## Related issues:

* https://github.com/nuxt/nuxt.js/issues/2565
* https://github.com/nuxt/nuxt.js/issues/2841
* https://github.com/vuejs/vue/pull/7443
* https://github.com/nuxt/nuxt.js/issues/2565
* https://github.com/egoist/svg-to-vue-component/issues/15

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8440">#c8440</a>)</em></sub></div>

**Comment by manniL** [comment]
This is a rare edge case in Vue 2.x 

In Vue 3, perf benefits from `functional` components are close to nothing ([source](https://github.com/egoist/svg-to-vue-component/issues/15#issuecomment-453556835)).

If you read that, just go for a stateful template :see_no_evil:

**Comment by podlebar** [comment]
damn.. i get this now very often..
any chance to do a workaround or is the solution to just not lazyload them?
