### ISSUE TITLE
Dont generate page for file/folder with @ prefix

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt/nuxt.js#4732]
### What problem does this feature solve?

It helps if you want a set of components exclusive available to the page.
The reason you might want this is if the set of @components is in the same directory of the page it reads like the components is exclusively available for the page file.
The exclusive component is mainly used to eliminate the visual noise of the page file.

https://github.com/cknow/nuxt-modular/pull/2

### What does the proposed changes look like?

Typically I do it like this

```
components
  admin
      about
          AboutMainContent.vue
          AboutSidebarContent.vue

pages
  admin
      about
          index.vue
```

With this changes I would be able to do it like this.
```
pages
  admin
      about
          sponsors
              @MainSponsors.vue
              @OtherSponsors
              index.vue
          @MainContent.vue
          @SubContent.vue
          index.vue
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8444">#c8444</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @ricardogobbosouza 

Thank you for this feature request, I like `nuxt-modular` module :)

I am not found of the `@` prefix, and never saw it somewhere as a best practice. Actually, a module can change the default `ignorePrefix` option of Nuxt.js (see https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/config/_common.js#L48)

**Comment by ricardogobbosouza** [comment]
The idea is to use a file that is inside pages as a component without the need to be inside components and the same is not a page, just ignore it as a page.

I often need to separate a page into components that will not be used elsewhere, just for a better view and I will pollute the components folder unnecessarily.

I agree that `.nuxtignore` will solve this.

**Comment by Atinux** [comment]
Actually, you can use the `-` instead of `@` and it will already ignore the files in the `pages/` directory:

```bash
pages
  admin
      about
          sponsors
              -MainSponsors.vue
              -OtherSponsors
              index.vue
          -MainContent.vue
          -SubContent.vue
          index.vue
```

**Comment by manniL** [comment]
or change the ignore prefix :P

As there are "workarounds" to achieve the features purpose, I'll close hear.

It'll be easier with `.nuxtignore` as @Atinux said.
