### ISSUE TITLE
A way to import YAML as a JavaScript object

### ISSUE THREAD

**Issue by davision** [nuxt/nuxt.js#4736]
### What problem does this feature solve?

I've tried to use YAML files as data object, followed an example from Next.js https://github.com/zeit/next.js/issues/3141. So if I use something like this

```js
// pages/index.vue
import data from `~static/data.yml`

export default {
  data () {
    return {
      data
    }
  }
)
```

And then add yaml loader in nuxt.config.js

```js
build: {    
    extend(config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push(
          {
            test: /\.ya?ml$/,
            use: 'js-yaml-loader',
          }
        )
      }
    }
  }
``` 

This works until I refresh the page. Then I got an error: `Module parse failed: Assigning to rvalue (1:2) You may need an appropriate loader to handle this file type.`  And then on next refresh another error: `render function or template not defined in component: anonymous`

Any ideas how to properly use YAML files?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8447">#c8447</a>)</em></sub></div>

**Comment by galvez** [comment]
I think you might need to remove the `isDev` check.

**Comment by davision** [comment]
Ah yes, late night coding not always fruitful :) I've put yaml test outside the condition and everything is good now!

**Comment by manniL** [comment]
Closing here then ☺️

**Comment by IQ-Yuvanshu** [comment]
@davision @TheAlexLichter  hey , i am using typescript in next js same way you posted above i added a loader for yaml file , now i am not getting loader error but as i have more than one yaml files to import , here i am facing a problem is the file that is being imported and used first as import common from "../node-config/common.yaml"; its content is served for each different import despite i am importing from different yaml files do not know why this happening can you please help me in this ?

Example - 

import common from "../node-config/common.yaml";
import anotherConfig from "../node-config/another-config.yaml";

console.log("Common YAML:", common);
console.log("Another Config YAML:", anotherConfig);

here both yaml have different content but it console same for both , this is declaration file i created for type

declare module '*.yaml' {
    const content: { [key: string]: any };
    export default content;
}


i am next js latest version with turbo -

const nextConfig: NextConfig = {
  experimental: {
    turbo: {
      rules: {
        // Add custom rule for `.yml` files
        '*.yaml': {
          loaders: ['js-yaml-loader'], // Use the yaml-loader for .yml files
          as: 'javascript/auto', // Explicitly treat these files as JavaScript for Webpack
        },
      },
    },
  },

  webpack(config, { dev, isServer }) {
    // Enable source maps in development mode
    if (dev && !isServer) {
      config.devtool = 'source-map';
    }

    return config;
  },

  devIndicators: {
    appIsrStatus: false,
  },
}; above is next.config.ts

**Comment by danielroe** [comment]
@IQ-YuvansI this is the repository for nuxt, which is a different framework, so unfortunately won't be as much use to you 

all the best in finding the solution
