### ISSUE TITLE
How to add separate CSS file to webpack config

### ISSUE THREAD

**Issue by benosman** [nuxt/nuxt.js#475]
I wasn't sure whether to start a new issue, or post on a related issue such as https://github.com/nuxt/nuxt.js/issues/471 or https://github.com/nuxt/nuxt.js/issues/333.

Since they are both closed, I decided to go for the new one. 

I want to load a single separate large css file for the entire site, that after the initial development won't change too often.  It's too large for the new embedded css.

So, my question is, how can I add an additional stylesheet entry point to webconfig?

It doesn't need to do anything fancy, just go through a scss file and its imports and create an additional style sheet (minified in production, etc). Styles in components can use the embedded css.

I know how to do this in vanilla webconfig, but I haven't worked out how to do it in nuxt.config.js without messing with the existing entry points.

Any tips appreciated...

**Comment by benosman** [comment]
Just to add, I am currently using the global CSS config option, which currently just adds it as embedded. 

Ideally i'd like there to be a config option on that to specify output to a separate file.

**Comment by cretueusebiu** [comment]
@benosman Have you found any solution for this ?

**Comment by benosman** [comment]
@cretueusebiu not yet...

**Comment by acidjazz** [comment]
I'd like to see how this can happen as well, particularly a vendor.css and an app.css

**Comment by pi0** [comment]
This feature is coming soon back and can be enabled with `build.extractCSS` option :) e148e4b93abf2aecd9bcb53d7f626f07318d3b75 (Well this is much like `vendor/common.css` and minimal `app.css` for each page is being automatically inlined )

**Comment by nigeltiany** [comment]
nice progress but it does not work with the scoped attribute. Setting ```scoped``` or ```scoped="true"``` does not yield expected results @pi0

**Comment by nigeltiany** [comment]
Also, component styles are not prioritized.
Expected
```
component styles should overwrite former stylus
```
Current behavior
```
component styles are overwritten by former styles
```
This means setting the !important attribute a lot

**Comment by Atinux** [comment]
Closing since `rc3` is out :)
