### ISSUE TITLE
Why the Custom Loading Component may not work?

### ISSUE THREAD

**Issue by daaru00** [nuxt/nuxt.js#4751]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/custom-loading?from-embed](https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/custom-loading?from-embed)

### Steps to reproduce

I configured my custom loading component as described in documentation:
```json
  /*
  ** Customize the progress-bar color
  */
  loading: '@/components/Loading.vue',
```
and created my new component
```
<template>
  <div v-if="loading" class="loading-page">
    Loading..
  </div>
</template>

<script>
export default {
  data: () => ({
    loading: false
  }),
  methods: {
    start() {
      this.loading = true
    },
    finish() {
      this.loading = false
    }
  }
}
</script>

<style scoped>
.loading-page {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: 9999;
  background-color: red;
}
</style>
```

### What is expected ?

My custom loading component showed during page load.

### What is actually happening?

Nothing, my custom component and even the default one are never showed up.

### Additional comments?

Related issued closed but not solved:
#1454
#1463

I notice that even the example provided in the documentation is not working, I just notice a little flicker caused by browser load.

I try to modify the template like this:
```
<template>
  <div v-if="true" class="loading-page">
    Loading..
  </div>
</template>
```
and I correctly see the component, so the component have the correct dimension/position/z-index.

I try to add some console log output:
```
export default {
  data: () => ({
    loading: false
  }),
  methods: {
    start() {
      console.log('loading..')
      this.loading = true
    },
    finish() {
      console.log('loaded!')
      this.loading = false
    }
  }
}
```
and I never see that output inside the console, so those methods are never called.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8458">#c8458</a>)</em></sub></div>

**Comment by MahdadGhasemian** [comment]
mounted() {
    this.$nextTick(() => {
      this.$nuxt.$loading.start()
      setTimeout(() => this.$nuxt.$loading.finish(), 2000)
    })
  }

**Comment by morteza-mortezai** [comment]
it does not work for me !!
