### ISSUE TITLE
Page mounted twice on redirect in SPA

### ISSUE THREAD

**Issue by MrWook** [nuxt/nuxt.js#4757]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/40y7x1l0p4](https://codesandbox.io/s/40y7x1l0p4)

### Steps to reproduce

Open reproduction link
Open console
Add /random_string to the codesandbox project url like this https://40y7x1l0p4.sse.codesandbox.io/randome_string

### What is expected ?

Inside the console the String test should only exist once.

### What is actually happening?

The string test will be shown twice.

### Additional comments?

Already opened a bug ticket but it was closed duo to no response from the nuxt team:
https://cmty.app/nuxt/nuxt.js/issues/c8038

[aldarund](https://github.com/nuxt/nuxt.js/issues/4197#issuecomment-438785950) mentioned that asyncadata/fetch will only be triggered once but mounted/created twice. So only the component itself is created twice. This also happens in production mode. 
[goodslav](https://github.com/nuxt/nuxt.js/issues/4197#issuecomment-440202970) mentioned that you can use a workaround to get rid of it 
```
setTimeout(() => redirect()) 
```
But it's still a bug that need to be recognized!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8463">#c8463</a>)</em></sub></div>

**Comment by MrWook** [comment]
I updated the sandbox project to nuxt 2.4.2 and it still occures.

**Comment by Lasim** [comment]
Same issue here.
V: 2.3.4

 Any news?

**Comment by hardikshah91** [comment]
Same issue
V: 2.2.0
Universal mode
https://cmty.app/nuxt/nuxt.js/issues/c8632

**Comment by VulgarnyKarlson** [comment]
bump
Universal mode
V:2.3.4
Sometimes (its really calls like a random) calls mounted, data(rewriting all), created  - calling twice

**Comment by Heziode** [comment]
Related to [#2202](https://github.com/nuxt/nuxt.js/issues/2202).
I've had this *** problem for about a year.
This forces me to access the page with the `a` tag instead of `nuxt-link`.
[I'm also in SPA](https://github.com/FOE-Tools/FOE-Tools.github.io).

**Comment by noe132** [comment]
my minimal reproduction

1. using create-nuxt-app create a **spa** project (other option are none) (current installed nuxt verion 2.4.5)
2. add a router-middleware in `nuxt.config.js` with code `if (ctx.route.path !== '/') ctx.redirect('/')` in a synchronous call
3. add `console.trace('created called')` in index page created hook
4. start the project and enter url `/test`
5. page redirect to `/` and console logs 2 stack trace

here is my call stack trace, the difference between two call stacks are from `(anonymous) client.js:671` and `fixPrepatch client.js:465`
https://github.com/nuxt/nuxt.js/blob/37006f626796af15b8ea83a958b761580d83521b/packages/vue-app/template/client.js#L477
https://github.com/nuxt/nuxt.js/blob/37006f626796af15b8ea83a958b761580d83521b/packages/vue-app/template/client.js#L698
```
first call stack

created                | @ | index.ts?01d8:37
mount                  | @ | client.js:624
(anonymous)            | @ | client.js:671
_callee4$              | @ | client.js:406
Promise.then (async)   |
render                 | @ | app.js:755
_callee3$              | @ | client.js:146

_loadAsyncComponents   | @ | app.js:656
loadAsyncComponents    | @ | app.js:568
(anonymous)            | @ | client.js:671
_next                  | @ | client.js:244
app.context.redirect   | @ | utils.js:161
push../middleware/router-middleware | @ | router-middleware.ts:26

```
```javascript
// client.js:671
    // Push the path and then mount app
    router.push(path, () => mount(), (err) => {
      if (!err) return mount()
      errorHandler(err)
    })
```

```
second call stack

created                | @ | index.ts?01d8:37
Promise.then (async)   |
fixPrepatch            | @ | client.js:465
_callee4$              | @ | client.js:406
Promise.then (async)   | 
render                 | @ | app.js:755
_callee3$              | @ | client.js:146

_loadAsyncComponents   | @ | app.js:656
loadAsyncComponents    | @ | app.js:568
(anonymous)            | @ | client.js:671
_next                  | @ | client.js:244
app.context.redirect   | @ | utils.js:161
push../middleware/router-middleware | @ | router-middleware.ts:26
```
```javascript
// client.js:465
function fixPrepatch(to, ___) {
  if (this._pathChanged === false && this._queryChanged === false) return

  Vue.nextTick(() => {
    const matches = []
    const instances = getMatchedComponentsInstances(to, matches)
    const Components = getMatchedComponents(to, matches)

    instances.forEach((instance, i) => {
      if (!instance) return
      // if (
      //   !this._queryChanged &&
      //   to.matched[matches[i]].path.indexOf(':') === -1 &&
      //   to.matched[matches[i]].path.indexOf('*') === -1
      // ) return // If not a dynamic route, skip
```
Seems like the page first mounted on initial load, then redirect also mounted the page

I think it should be while redirect was called before the page first load, the first load and redirect had some conflict and page mounted twice

Hope this could be some useful infomation
