### ISSUE TITLE
The website can't work normally in IE

### ISSUE THREAD

**Issue by K-Stella** [nuxt/nuxt.js#4758]
I use Nuxt.js to write a website and it's normal in other browser, like Chrome, Firefox, Safari and so on.But just can't work in IE.
The error like this :
![wechatimg3451](https://user-images.githubusercontent.com/23692583/51106479-dac9e880-1826-11e9-96e7-7012bbfd1fec.png)

And I have tried to use babel to transform the code, but it does't work, too. My config like this : 
![wechatimg3453](https://user-images.githubusercontent.com/23692583/51106491-e3baba00-1826-11e9-93bf-39cbeaaddaaa.jpeg)

someone can answer it or get some suggestions for me? Thank you so much!!!

**Comment by zhangwei610** [comment]
I also have this problem. When can you solve it?
