### ISSUE TITLE
Use variables of Webpack definePlugin or 'NUXT_ENV_ ' in scss ?

### ISSUE THREAD

**Issue by nikli2009** [nuxt/nuxt.js#4759]
I'm using Nuxt 2.0
Is there a way to use variables of Webpack definePlugin or 'NUXT_ENV_ ' in scss ?
such like $color : COLOR

Thanks ...

**Comment by PabloLION** [comment]
> Your question is available at https://cmty.app/nuxt/nuxt.js/issues/c8470.

suspicious link
