### ISSUE TITLE
bug？Port cannot be modified

### ISSUE THREAD

**Issue by chenfangyi931** [nuxt/nuxt.js#4762]
Modifying Express Port Client Normal Server has always been the default 3000

**Comment by zhoou** [comment]
In nuxt.config.js file:
```
module.export = {
    ...
    server: {
        port: 8888
    }
    ...
}
```

**Comment by mrleblanc101** [comment]
@danielroe Not sure you linked to the correct issue in the MR and Changelog

**Comment by danielroe** [comment]
Thanks!
