### ISSUE TITLE
Virtual DOM tree not match after a simple request

### ISSUE THREAD

**Issue by fy0** [nuxt/nuxt.js#4765]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/fy0/nuxttest](https://github.com/fy0/nuxttest)

### Steps to reproduce

1. create an empty project with `create-nuxt-app`
2. npm i --save axios
3. write a simple plugin for vue router:
```javascript
import axios from 'axios'

let theData = null

export default ({ app }) => {
    app.router.beforeEach(async function (to, from, next) {
        if (!theData) {
            let ret = await axios.get(`http://localhost:8888/`)
            console.log(111, ret)
            theData = ret
        }
        next()
    })
}
```

4. start the `backend.py` (requires python 3.6, tornado), `npm run dev` and access localhost:3000

5. get the error 
![Snipaste_2019-01-15_23-36-03.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/64b5a0c0-18db-11e9-ae9c-f180449b7423.png)

### What is expected ?

Nothing happened.

### What is actually happening?

```[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.```

### Additional comments?

I want fetch some global data before any page loaded.

Maybe it's not the recommend method, but why i got the error? I just sent a request.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8478">#c8478</a>)</em></sub></div>

**Comment by fy0** [comment]
@manniL Hello, thanks for the CodeSandbox version example.

I'm trying to fetch some global settings from backend, such as api server info, return code table, enable features ...

Now i read examples of nuxt.js document, and use middleware to instead vue-router's guards, now it works without error.

I am just curious about why the request affected renders.

**Comment by shoshi** [comment]
This is still an issue. Using middleware is not an option for our use case as we're hosting statically generated files on S3. Adding _anything_ in `app.router.beforeEach(...)` causes the error above and results in the page not loading. Changing to 'spa' mode also does not fix the issue as it causes all pages to be a 404.

**Comment by fy0** [comment]
@shoshi I thought follow the offical rules is easiest way. My project changed a lot after switch to nuxt, hack solutions are rare and unstable...

**Comment by manniL** [comment]
@shoshi please open a new bug report
