### ISSUE TITLE
runtime env vars

### ISSUE THREAD

**Issue by MartinMuzatko** [nuxt/nuxt.js#4773]
### What problem does this feature solve?

If you have a deployment target dependent API URL to fetch data from during server side render and also during client-mode, it is impossible right now, to define an env var during run time. (`nuxt` vs `nuxt build`).

Right now, the only option is to build for the deployment target.

### What does the proposed changes look like?

It would be nice to have the possibility to define an environment variable, that can be set when running nuxt. That would only work with the nuxt server. `generate` and `--spa` would not work

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8486">#c8486</a>)</em></sub></div>

**Comment by ruudboon** [comment]
👍 I tried https://nuxtjs.org/api/configuration-env/ but didn't realised this only works before build :(

**Comment by manniL** [comment]
related: https://github.com/nuxt/nuxt.js/issues/2689

**Comment by aldarund** [comment]
You can use module https://github.com/samtgarson/nuxt-env

**Comment by MartinMuzatko** [comment]
Just wish that was documented before fiddling with it for hours. Thanks!!

**Comment by rasicoc** [comment]
> You can use module https://github.com/samtgarson/nuxt-env

Unfortunately this does not work in SPA mode. Anyone find a way to do this when in SPA mode.
