### ISSUE TITLE
[wip] CSS & PWA benchmarks

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#478]
Hi. Today [vuejs/pwa](https://github.com/vuejs/pwa) repo is public. Their build steps are including: 

- CSS across all components extracted into a single file and minified with **[cssnano](http://cssnano.co)**.
- All static assets compiled with version hashes for efficient long-term caching, and a production index.html is auto-generated with proper URLs to these generated assets.

Also @addyosmani stated on vuejs/pwa#1 checklist. (He seems not talking about critical path css and only for global stylesheets)

> CSS extraction for production

# Benchmarks (only css analysis)
I started a lighthouse benchmark on a local nuxt 0.10.5 generated version to avoid network latency and server render times. with bootstrap css + some global styles. (serving with a docker nginx webserver)

### Using default nuxt config
(Lighthouse)
![image](https://cloud.githubusercontent.com/assets/5158436/24490287/2fe1a514-1537-11e7-8d14-c9ffefc9ee07.png)

### [WIP]
Trying to build on nuxt using same stack used in vue/pwa configurations. [webpack.prod.conf.js](https://github.com/vuejs/pwa/blob/prototype/template/build/webpack.prod.conf.js)

- [ ] Using cssnano
- [ ] Adding back css generation using extract-text-webpack-plugin
- [ ] [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin)
- [ ] Check performance of SSR (req/second) with both approaches.

**Comment by pi0** [comment]
I cannot find out why !! But trying adding this to same nuxt config : 
```js
build: {
        plugins: [

        ],
        postcss: [

        ]
}
```

Generate report: 

![image](https://cloud.githubusercontent.com/assets/5158436/24492189/ba338004-153f-11e7-8293-91df96cfb391.png)


WTF?? :)) Where is additional 7kb css coming from ?? :)))

**Comment by Atinux** [comment]
The `.error-page` is from `layouts/error.vue`, I am aware about this and I will find a way of not including this CSS when the component is not displayed on the page.

Also: https://twitter.com/youyuxi/status/846731152710787076

**Comment by pi0** [comment]
@Atinux Yep i've seen that tweet would be so nice :)) The second problem i mentioned is not about `.error-page` itself. just compare  bundle sizes with first one. Adding empty `plugins` or `postcss` configs makes that difference and i've tried it more and 2 times to ensure :))
