### ISSUE TITLE
How to prevent nuxt-link jump to another page?

### ISSUE THREAD

**Issue by gai-sama** [nuxt/nuxt.js#4784]
I want to use the tag nuxt-link to display some A tag with attribute href.But one of them need be authorized before jump to another page,maybe show a login dialog.
How can I do it?
I tried the solution below but it didn't work

template:
```html
<nuxt-link :to="{name: 'developer-manage'}" @click.native="checkLogin($event)">test</nuxt-link>
```
script: 
```javascript
checkLogin (e) {
  e.preventDefault()
},
```
Though,I solved the problem with this way:
```html
<a :href="$router.resolve({name: 'developer-manage'}).href" @click="checkLogin($event)">test</a>
```
I hope nuxt-link can provide a better way to do that

**Comment by Tofandel** [comment]
The ghost link is redirecting to ads website

**Comment by JoJk0** [comment]
I'm also struggling to figure out how to prevent `NuxtLink` the official way. It is not documented anywhere.

**Comment by codeflorist** [comment]
Here is a workaround:

```html
<NuxtLink to="/whereever" class="relative">
    <div v-if="isForbidden" class="absolute inset-0 z-50 size-full" @click.stop.prevent="doWhatever()" />
    Foobar
</NuxtLink>
```

Classes are tailwind, but should be self-explainatory.
