### ISSUE TITLE
nuxt:build is not script friendly

### ISSUE THREAD

**Issue by Skriptach** [nuxt/nuxt.js#4789]
Ubuntu 17.04
Node 8.4.0
Nuxt 1.0.0 RC11

> server-bundle.json  739 kB          [emitted]  
  nuxt:build Building done +48s

Building done then it not ending ... so i have to Ctrl+c to exit...

thanks for help.

_Originally posted by @cayaner in https://github.com/nuxt/nuxt.js/issues/1631#issuecomment-328332490_

The bug is still exist. I also want to write a script for pre-build and deploy. But this issue not allows me to do that

**Comment by Skriptach** [comment]
@manniL

**Comment by manniL** [comment]
@Skriptach Please use CMTY to open a new issue :relaxed:
