### ISSUE TITLE
Webpack config

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#479]
Can i edit the webpack config? if yes  , where?

**Comment by pi0** [comment]
@aymenpeak You can customize it using `extend` function. See https://nuxtjs.org/api/configuration-build#extend

**Comment by aymenpeak** [comment]
thanks.

**Comment by aymenpeak** [comment]
@pi0 i'm trying to add this config 
config.node = {
                    console: 'empty',
                    fs: 'empty',
                    net: 'empty',
                    tls: 'empty'
                }

it causes an error 
any propositions?

**Comment by pi0** [comment]
@aymenpeak You may do this only for SSR bundle.
```js
    extend (config, { isServer }) {
      // Extend only webpack config for client-bundle
      if (isServer) {
           // SSR Customizations
      }
    }
```

**Comment by aymenpeak** [comment]
@pi0 that take me back to the first error ...
![image](https://cloud.githubusercontent.com/assets/19589742/24501703/908fc688-1542-11e7-9044-00769a55ffa1.png)
PS: im trying to include the facebook sdk via npm

**Comment by pi0** [comment]
@aymenpeak Try removing at least `net` and `fs` :))

**Comment by aymenpeak** [comment]
@pi0  same

**Comment by pi0** [comment]
what about `config.node = { }` ?? :)) I've no idea about your specific error. You should do a step-by-step diagnostics. (ie adding restrictions one by one)

**Comment by Atinux** [comment]
I think that's because @aymenpeak is requiring `fs` inside a client script right?

Thanks @pi0 for helping us with the issues 🙌

**Comment by aymenpeak** [comment]
@Atinux yes i'm , but i need it for the facebook package 😢

**Comment by KonstantinVlasov** [comment]
Hi, @aymenpeak! 
If you need to use fs, you should do it at server-side. You can create custom express route for fs using [express starter template](https://github.com/nuxt/express) and call it from browser.

**Comment by aymenpeak** [comment]
i solved my problem by using the javascript sdk instead of the npm one.
Thanks anyway guys :peace_symbol:

**Comment by jaubut** [comment]
I got kind of a same error.. I try to implement moltin in my demo project and even with this it keeps telling me that dependencie fs isnt install ... any help ? There is no other way but trought npm to install the v2 sdk 
```
build: {
    extend (config, { isDev, isClient }) {
      node: {
        fs: 'empty'
      }
    },
    vendor: ['axios']
  }
```

**Comment by proko** [comment]
Inside the __extend__ function I assigned new value to config.node and it worked. 
`config.node = {
       fs: 'empty'
   };`

**Comment by jaubut** [comment]
Thanks @proko, i'm not sure in details where you did put that line.. Can you make a bigger screen shot of your config please :)

**Comment by jaubut** [comment]
Thanks @proko  :) 👍  And did you place your moltin.js services in the plugins directory of in a services directory ? There is this vue exemple that I try to get around.. If you want to share your project, I will love to take a look and learn !!!
