### ISSUE TITLE
zero-downtime deployment

### ISSUE THREAD

**Issue by dschewchenko** [nuxt/nuxt.js#4797]
### What problem does this feature solve?

I have many modules and one custom async module for serverMiddleware with db connection. When I make some changes in module it will start server up to 10 seconds. And users see nginx error page.
For zero-downtime deployment in cluster mode we need to notify pm2 about successful start of server

https://pm2.io/doc/en/runtime/best-practices/graceful-shutdown/#graceful-start

### What does the proposed changes look like?

call process.send(‘ready’) when all modules are initialized and server is ready

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8504">#c8504</a>)</em></sub></div>

**Comment by manniL** [comment]
Related: #3078
