### ISSUE TITLE
Nuxtjs and Pixijs load a JSON in to loader Pixi function

### ISSUE THREAD

**Issue by fabsfabs** [nuxt/nuxt.js#4799]
### What problem does this feature solve?

Hi everyone 
I'm quite new with nuxtjs and webpack and I'm facing my first big question about it.
How do I load a JSON spritesheet with loader function of Pixijs in Nuxtjs?

What I try to reach is similar to this example provided by Pixijs https://pixijs.io/examples/#/basics/spritesheet.js

What happen to me is that the spritesheet.json file added to the loader doesn't load actually and few errors are displayed.
![Screen Shot 2019-01-18 at 14.42.44.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/06b80af0-1b27-11e9-8f05-0f77d7739bd3.png)

Here you can find the final result, not in nuxtjs of course
http://fabiobertozzi.it/portfolio/intro.html

The spritesheet animation is this one below (the dissolving grey panel)
![Screen Shot 2019-01-18 at 14.45.41 3.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/94141790-1b27-11e9-8f05-0f77d7739bd3.png)

Certainly I miss some basic knowledge of nuxtjs and webpack.
Anyone can help me?

Many thanks

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8507">#c8507</a>)</em></sub></div>

**Comment by manniL** [comment]
There you go. 
https://codesandbox.io/s/github/manniL/nuxt-pixijs-example/tree/master/

**Comment by fabsfabs** [comment]
Hi @manniL but in which way this should help me? Maybe I don't see the solution.
My problem is to load a JSON file inside the pixi loder, something like this:

`PIXI.loader
.add('spritesheet', require('~/assets/images/sprite/sprites.json'))
.add('sprites', require('~/assets/images/sprite/sprites.png'))
.load(console.log(PIXI.utils.TextureCache));`

the result is this, no trace of sprite.json inside the Texture Cache
![screen shot 2019-01-18 at 20 08 33](https://user-images.githubusercontent.com/3035516/51407698-e423bf80-1b5c-11e9-81b8-8c57d79456e2.png)

Anyone?
Thanks

**Comment by fabsfabs** [comment]
Great @manniL  thanks a lot for your help! It's works!
By the way, is there anyway to include it inside the optimization that webpack does?

**Comment by manniL** [comment]
@fabsfabs Pretty sure that is possible somehow but as I don't know Pixi.js very well you have to do some own research. Further info: https://github.com/pixijs/pixi.js/issues/4223#issuecomment-322070554
