### ISSUE TITLE
IE11 vuex requires a Promise polyfill

### ISSUE THREAD

**Issue by ezhkov** [nuxt/nuxt.js#480]
I got this error when tried to open builded nuxt application in IE 11. I tried to implement babel-polyfill or es6-promise, but with no luck.

How to implement Promise polyfill for IE?

**Comment by vuchl** [comment]
Maybe with this: https://polyfill.io/v2/docs/features/#Promise

**Comment by ezhkov** [comment]
How to properly include it in application?

**Comment by KonstantinVlasov** [comment]
Hi, @ezhkov!

I fix IE11 problems with babel-polyfill:
**nuxt.config.js**
```
build: {
    vendor: [
      'babel-polyfill'
    ]
}
```
don't forget to: npm install babel-polyfill

**Comment by KonstantinVlasov** [comment]
Sorry, don't sure if it resolve promise errors. I'm using it for Symbol.

**Comment by ezhkov** [comment]
Konstantin, great solution. Thanks.
I found another one
```
build: {
        extend(config, { isClient }) {
            if (isClient) {
                config.entry.vendor.push('babel-polyfill')
            }
        }
    }
```
I like yours much more )

**Comment by laterne** [comment]
Would it possible to do feature detection in nuxt and load a built vendor bundle with only the libraries needed?
like:
```javascript
if (!window.fetch && !window.Promise) {
  //load vendor bundle with fetch and promise polyfill included
}
if (!window.Promise) {
  //load vendor bundle with only promise pollyfill included
}
//and so on
```
The vendor builds could be lighter. [yepnope](https://github.com/SlexAxton/yepnope.js#deprecation-notice) suggested this technique in their deprecation notice.

This could be extended to not load any js at all if not supported: [BBC](http://responsivenews.co.uk/post/18948466399/cutting-the-mustard) coined the term Cutting the mustard.

I think this would be great options to extend the already great progressive enhancement functionality of nuxt.

**Comment by KonstantinVlasov** [comment]
Hi, @laterne! I think it's could be a good feature request, but probably you should create a new issue.
