### ISSUE TITLE
Dynamically create event Listeners

### ISSUE THREAD

**Issue by tenjojeremy** [nuxt/nuxt.js#481]
Hello,

When I create an element as such:

![example](https://cloud.githubusercontent.com/assets/25231946/24508456/75014d30-1531-11e7-945b-cf7ce2eba142.PNG)

The click event does not trigger function.

What approach should I take with Nuxt?

Thank you,

**Comment by KonstantinVlasov** [comment]
hi, @tenjojeremy!

Why don't you use Vue way for templates?
Like:
```
<div v-if="!dataTeams || !dataTeams.length">no results warning</div>
<div v-if="dataTeams && dataTeams.length">
  <p class="resultsTitles">Teams:</p>
  <div class="resultBox" v-for="team in dataTeams">
    <p class="resultTitle" @click="resultClick">{{ team.name }}</p>
    <img :src="'teamLogos/' + team.file" alt="user icon" class="resultImg"/>
  </div>
</div>
```

**Comment by tenjojeremy** [comment]
Hi @KonstantinVlasov 

Yes, this method worked magnificently.

Thank you and have a great day!
