### ISSUE TITLE
Client-side only plugin not working

### ISSUE THREAD

**Issue by Nainterceptor** [nuxt/nuxt.js#482]
Hello,

When I try to do a [plugin available only client side](https://nuxtjs.org/guide/plugins/#vue-plugins), it's not working. I have an issue, because nuxt is trying to find `~` as first char of plugin string, but object provided.

Workaround : 

I'm able to include everywhere the plugin then check inside `if (process.browser)`

`npm list | grep nuxt`
-> nuxt@0.9.9

So may be it's a feature of 0.10 but I've not seen that in changelog

Thanks for help & for this amazing lib ;)
Gaël

**Comment by ausir0726** [comment]
@Nainterceptor yes , that feature of 0.10.X ( maybe 3 or 4? )
but no release log yet  :D

**Comment by Nainterceptor** [comment]
OK @ausir0726, thanks, I add a todo in my project & close ticket, thanks !
