### ISSUE TITLE
Pug not working in Nuxt 2.3.4

### ISSUE THREAD

**Issue by NemoAlex** [nuxt/nuxt.js#4822]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/pug](https://github.com/nuxt/nuxt.js/tree/dev/examples/pug)

### Steps to reproduce

Clone https://github.com/nuxt/nuxt.js/tree/dev/examples/pug
npm install
npm run dev

### What is expected ?

Build with no error.

### What is actually happening?

ERROR  Failed to compile with 1 errors
This relative module was not found:
* ./about.vue?vue&type=template&id=0a606064&lang=pug& in ./pages/about.vue

### Additional comments?

https://github.com/nuxt/nuxt.js/issues/3469

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8526">#c8526</a>)</em></sub></div>

**Comment by manniL** [comment]
@NemoAlex Good point! Would you mind sending in a PR with the correct deps or should I do that? ☺️

**Comment by NemoAlex** [comment]
Sadly I'm not familiar with this project. 
And it seams like an old bug occurs again, maybe core team members could do fix job in a better way.

**Comment by manniL** [comment]
@NemoAlex Well, you'd have to add `pug` and `pug-plain-loader` to the deps as the only thing. But sure, I can do it as well ☺️

**Comment by manniL** [comment]
https://github.com/nuxt/nuxt.js/pull/4824

**Comment by paulgeisler** [comment]
It still doesn't work for `2.4.5`.
