### ISSUE TITLE
[nuxt-edge] Promise.prototype.finally is not a function

### ISSUE THREAD

**Issue by borvelt** [nuxt/nuxt.js#4825]
### Version

nuxt-edge: 2.4.0-25799046.dbe40bc1

### Reproduction link

[https://codesandbox.io/s/x7r9zzn69z](https://codesandbox.io/s/x7r9zzn69z)

### Steps to reproduce

Just run code sand box.

### What is expected ?

pass function to finally and do some thing.

### What is actually happening?

store.dispatch(...).catch(...).finally is not a function

### Additional comments?

Nuxt v2.3.4 every thing is OK.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8530">#c8530</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce. Check your node version is >= 10.0.0

![image](https://user-images.githubusercontent.com/640208/51502397-d9239600-1dcd-11e9-82c1-d5508a78e81c.png)

**Comment by borvelt** [comment]
Thanks for your response but I don't have any issue with node v8.15.0 and nuxt v2.3.4
Do you have any idea?

**Comment by manniL** [comment]
@borvelt `Promise.finally` is not supported by node < 10.0 🤔 

(see https://node.green/#ES2018-features-Promise-prototype-finally)

It should throw as well.

**Comment by pi0** [comment]
It may working because babel trabspiled it. Or node version used for build is higher than 8. Anyway it is recommended to use latest node for Nuxt and enjoy native best performance and latest features :)

**Comment by borvelt** [comment]
Yes, It is for babel transpiler. thanks.
