### ISSUE TITLE
Use middleware to throw an error in ie11

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#483]
Browser: ie
version: ie11

use middleware to throw an error  '“Symbol”Not defined'
![image](https://cloud.githubusercontent.com/assets/11555571/24540164/9458f5cc-1624-11e7-95d2-8595b890564e.png)

the code is tracked
![image](https://cloud.githubusercontent.com/assets/11555571/24540179/a80b2a18-1624-11e7-88f2-5776b501c3e4.png)

**Comment by KonstantinVlasov** [comment]
hi, @HadiChen!

You should use babel-polyfill for IE. Check #480

**Comment by HadiChen** [comment]
@KonstantinVlasov Thank you
