### ISSUE TITLE
navigation links gets baffled on a static site generated with "nuxt generate" 

### ISSUE THREAD

**Issue by creatpix103** [nuxt/nuxt.js#4831]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[creatpix.com](http://creatpix.com)

### Steps to reproduce

just navigate to 'Hiring' page and then click on the floating button at the bottom right corner, that'll redirect you to a google form and then if you navigate back to 'Hiring' page and then click on any link the links are baffled in a way that they're no more respecting base URL.  

### What is expected ?

When we've leaved the site's 'Hiring' page and redirected to google form and then navigate back to that 'Hiring' page the links should properly populate the URL using the correct base URL.

i.e. the URL to be populated as expected is 'creatpix.com/hiring' or 'creatpix.com/relative-URL' in general.

### What is actually happening?

What is being populated is 'creatpix.com/hiring/hiring' or 'creatpix.com/hiring/relative-URL' in general. That's resulting in 'This page could not be found' error.

### Additional comments?

I've been through all the relevant documentation and searched through existing issues that'll be addressing this issue but found no help.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8531">#c8531</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey 👋 

That's not a "nuxt problem. Easy example: Navigat to `/hiring/` on your own (or click [here](http://creatpix.com/hiring/)). You'll see all links are "wrong". Likely because they don't start with a leading `/` (`hiring` and not `/hiring`). Without a trailing slash they are handled as relative URLs and will be appended to any URL ending with a Trailing slash.

Solution: Add a leading slash to your nuxt links ☺️

**Comment by creatpix103** [comment]
Hey @manniL

Adding a leading slash in not solving the issue.

**Comment by manniL** [comment]
@creatpix103 changing `to="hiring"` to `to="/hiring"` should do the trick. if not, please either share the source *or* update your website with this suggestion.
