### ISSUE TITLE
Head function not working in component

### ISSUE THREAD

**Issue by victorsolaya** [nuxt/nuxt.js#4836]
I am trying to change the meta tags in an Article.vue component.

Trying to do this, it changes perfectly all the tags in localhost but when I deploy to firebase, it takes the configuration in nuxt.config.js

This is the configuration in Article.vue

    head() {
    return {
      title: 'This',
      meta: [

    {
      hid: `og:description`,
      name: 'og:description',
      content: 'title'
    },
    {
      hid: `og:title`,
      name: 'og:title',
      content: 'title'
    }
      ]
    }

This is the configuration in nuxt.config.js

    head() {
     return { 
     title: 'That',
     meta: [
     {
      hid: `og:description`,
      name: 'og:description',
      content: '3'
    },
    {
      hid: `og:title`,
      name: 'og:title',
      content: '4'
    }
     ]
      }

In localhost, when I load an article in localhost/article?id=1, it loads the meta tag in the top.
When I deploy de configuration to xxx.firebaseapp.com/article?id=1 it loads the meta tag in the nuxt.config.js

Is there any reason or any configuration that I have to change for not breaking this in the deployment?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8532">#c8532</a>)</em></sub></div>

**Comment by victorsolaya** [comment]
@Atinux I don't know if this is an issue with my code or if this is a bug with the head function.

**Comment by ubershmekel** [comment]
FYI the reason this happened to me was because I started using `vue-property-decorator` instead of `nuxt-property-decorator` without knowing that it would break the `head()` method.
