### ISSUE TITLE
Proper use of lazy load

### ISSUE THREAD

**Issue by ezhkov** [nuxt/nuxt.js#484]
How to use [vue-lazyload](https://github.com/hilongjw/vue-lazyload) properly with nuxt? 
Nuxt uses `~assets` syntax or `require('...')` method to implement image urls. This means that these two variants both loading images BEFORE vue-lazyload starting its work. 
After images all are requested and downloaded by browser vue-lazyload know their urls and start to show them lazily. But it is already make no sense((

How to use vue-lazyload with nuxt or how avoid `~assets` or `require(...)`preloading?

**Comment by ausir0726** [comment]
a simple way you can put those image to /static/img  folder 
that will working ...

I tried vue-loader will not require `data-srcset` , even sometimes I want require image background in html template ( css attribute )

another way ....

maybe can make a webpack plugin to change src='imgage.jpg' to data-src='image.jpg' ( or data-srcset ) after vue-loader reqire image ....

obviously I do not understand how to create a plugin ...

so , I put image to static folder ( or CDN ) when I need the pic lazyload ...

**Comment by ezhkov** [comment]
@ausir0726 Thank you. I'll try your way.

**Comment by kodekrendel** [comment]
@ezhkov hi.

I am also trying lazyload and have some issue. Can you please take a look, since you tried it too? https://github.com/nuxt/nuxt.js/issues/522

**Comment by DaxChen** [comment]
There are several advantages when using webpack's `import`/`require` from `~/assets` directory, such as adding hash to the filename to enable long term caching, passing images through custom webpack loaders, etc.

Therefore, I suggest not putting all images in `~/static` directory, and to answer the original question: just use `require` inside v-bind with `data-src`!

For example

```js
use v-bind
<img v-bind:data-src="require('~/assets/images/foo.png')">
or :short-hand
<img :data-src="require('~/assets/images/bar.jpg')">
```

Because of `url-loader`, require will return a url.

**Comment by coolemur** [comment]
Worked for me:

~/plugins/vue-lazyload.js:

```
import Vue from 'vue';
import VueLazyload from 'vue-lazyload';

Vue.use(VueLazyload);
```

nuxt.config.js:
```
...
  plugins: [
    { src: '~/plugins/vue-lazyload', ssr: false }
  ]
...
```

.vue:
```
...
<img v-lazy="imageurl" />
...
```

Where imageurl - bound url from static folder (something like http://domain.com/img.jpg).

**Comment by stavros-liaskos** [comment]
@coolemur I don't understand what do you mean with bound url. Let's say we have the image: `./static/example.png`?  How would you write the `<img>` el exactly? Note that it has to work with both `yarn dev` and `yarn generate` of course

**Comment by DaxChen** [comment]
try this:

```html
<img v-lazy="require('./path/to/img.png')" />
```

this works in both `yarn dev` and `yarn generate`

**Comment by DaxChen** [comment]
@stavros-liaskos 

> It doesn't work for me. I have tried both at assets and static directories.

Because in your example:
```html
<img v-bind:data-src="require('/lucky-barber.png')">
```
You start the require from `/`, which is your **system root!** (super weird isn't it?)

you have to start the path with `./` for current folder; or `../` for the parent folder, etc.

**Comment by stavros-liaskos** [comment]
@DaxChen It worked, now. As you can see on my first post, I have tried that before but I've got no idea why it failed. 
The only thing left to answer from my first post then, is how to do that over a `v-for` loop. Let's say a parent renders children and passes to them`imgUrl: '~/assets/images/example.png'`.
Parent template:
```
<foto-frame v-for="(foto, index) in fotos" v-if="fotos.length" v-bind:imgUrl="foto.imgUrl"/>
```
Foto-frame template:
```html
<!--static works-->
<img v-lazy="require('~/assets/images/example.png')"/>
```
But dynamicly? I've tried [this](https://github.com/nuxt/nuxt.js/issues/448) among others but with no success. 
```
<!--Throws error: Cannot find module '~/assets/images/example.png'. -->
<img v-lazy="require(`${imgUrl}`)"/>
```
