### ISSUE TITLE
Dynamic routes not working with # 

### ISSUE THREAD

**Issue by dannywly** [nuxt/nuxt.js#4847]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://codesandbox.io/s/641wlrk81z](https://codesandbox.io/s/641wlrk81z)

### Steps to reproduce

> [example link](https://codesandbox.io/s/641wlrk81z) 

1. create pages/h5/_campaign/campaign.vue file
2. It's working when visit `https://{domain}/h5/test/campaign`, but is not working when visit  `https://{domain}/h5/#/campaign`

### What is expected ?

Expecting working when visit `https://{domain}/h5/#/campaign`.

### What is actually happening?

Not working at all.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8540">#c8540</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @dannywly,
Parameter with `#` or `?` is not a valid.
I do not know if this is a problem, but if it is, it's with `vue-router`

**Comment by manniL** [comment]
As @ricardogobbosouza said.
