### ISSUE TITLE
Can't request server when on asyncData

### ISSUE THREAD

**Issue by gigioSouza** [nuxt/nuxt.js#4848]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/n3myyo4zoj](https://codesandbox.io/s/n3myyo4zoj)

### Steps to reproduce

Configurations done in `nuxt.config.js`:
```
...
axios: {
  proxy: true,
  proxyHeaders: true
},
proxy: {
  '/api/': {
    target: 'http://localhost:8085',
    pathRewrite: { '^/api': '' }
  }
},
server: {
  port: 4200
},
plugins: [
   '~/plugins/axios'
]
```

The `plugins/axios`:

```
import { getItem } from '~/services/cookies.service';
import { ShowLoader, HideLoader } from 'mylib';

export default function({ req, $axios, redirect }) {
  const token = getItem('my-token', (process.server ? req.headers.cookie : null));

  if (token) {
    $axios.setToken(token, 'Bearer');
  }

  $axios.onRequest(() => ShowLoader());

  $axios.onResponse(() => HideLoader());

  $axios.onResponseError(() => HideLoader());

  $axios.onError(error => {
    if (error.response.status === 401) {
      redirect('/');
    }
  });
}

```

In my component:
```
...
asyncData({ $axios }) {
    return $axios.get('/api/products')
      .then(products => ({ products }));
}
...
```

### What is expected ?

I was expecting to have my request done.

### What is actually happening?

I'm getting `connect ECONNREFUSED 127.0.0.1:3000 `

### Additional comments?

I searched for the `localhost:3000` config as I'm using the nuxt in `localhost:4200` and found in the `.nuxt/axios.js`:
```
// baseURL
  const baseURL = process.browser
      ? '/'
      : (process.env._AXIOS_BASE_URL_ || 'http://localhost:3000/')
```

Then I tried to set the `_AXIOS_BASE_URL_` to `http://localhost:4200` in the `env` objetct in the `nuxt.config.js` but when doing this, I get this error:
![Screen Shot 2019-01-24 at 11.04.10.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/a11cffa0-1fd8-11e9-92b6-cf9ea3751d79.png)
![Screen Shot 2019-01-24 at 11.04.16.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/a9c185e0-1fd8-11e9-92b6-cf9ea3751d79.png)
![Screen Shot 2019-01-24 at 11.04.21.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/ca1b3b10-1fd8-11e9-92b6-cf9ea3751d79.png)
![Screen Shot 2019-01-24 at 11.04.31.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/d5b18a10-1fd8-11e9-92b6-cf9ea3751d79.png)

And this warnings in my terminal:
![Screen Shot 2019-01-24 at 11.08.49.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/3d991e40-1fd9-11e9-92b6-cf9ea3751d79.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8542">#c8542</a>)</em></sub></div>

**Comment by manniL** [comment]
have you tried to set your base url in the axios object? https://axios.nuxtjs.org/options#baseurl

**Comment by gigioSouza** [comment]
@manniL Ow my, I tried it yesterday and didn't worked as I was stressed out already and didn't read it properly, I tried setting it as an env variable in the `env` object. Now I put in the `axios` options and worked! Thank you!

**Comment by manniL** [comment]
No problem ☺️ 
The env var would be `BASE_URL` (as denoted in the linked URL) :)
