### ISSUE TITLE
Specify custom webpack entry points for the client and server

### ISSUE THREAD

**Issue by wagerfield** [nuxt/nuxt.js#4849]
### What problem does this feature solve?

Currently specifying `config.entry` in `build.extend(config)` is ignored.

The **client** entry is assigned without merging the value of `config.entry` that might have been set in `build.extend`:

https://github.com/nuxt/nuxt.js/blob/dcdbaba710c88c2f2b4c848aaa5f881074764556/packages/webpack/src/config/client.js#L178

The **server** `config.entry` is the result of merging a default config—overriding any `config.entry` value passed in `build.extend`:

https://github.com/nuxt/nuxt.js/blob/89f88669c10ce9100b109749aeab445638b851a8/packages/webpack/src/config/server.js#L71

It would be great if custom entry points could be specified in `build.extend` so that custom chunks could be generated independently of the Nuxt app.

Specify a custom entry name of `app` could throw an error notifying the user that this is reserved by Nuxt.

### What does the proposed changes look like?

```js
// nuxt.config.js
import { resolve } from "path"

export default {
  build: {
    extend(config, { isClient }) {
      if (isClient) {
        console.log(config.entry) // { app: [ "path/to/client.js", "eventsource-polyfill", "etc..." ] } (currently undefined)
      } else {
        console.log(config.entry) // { app: [ "path/to/server.js" ] } (currently undefined)
      }
      
       // This is ok
      config.entry.custom = resolve("custom-entry.js")
      
      // Throws error "entry.app is reserved by Nuxt"
      // Could use Object.defineProperty for the
      // config object passed to build.extend to
      // throw an error when attempting to set entry.app
      config.entry.app = resolve("app.js") 
    }
  }
}
```

Running `dev|build|generate` would create another chunk called `custom`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8543">#c8543</a>)</em></sub></div>

**Comment by pi0** [comment]
@wagerfield #5236 should fix it in next release. Please ping to reopen if still can't extend.

**Comment by samburgers** [comment]
ping. I still can't seem to extend... and still get `undefined` from `console.log(config.entry)` as above. any chance of getting a working example? thanks

**Comment by BenesX** [comment]
I still get undefined in v2.9.2.

**Comment by findoff** [comment]
> I still get undefined in v2.9.2.

Yes, but you can just assign new...

```
config.entry = {worker: resolve('./client/lib/worker.ts')}; // work for me (v2.9.2)
```

**Comment by maunier** [comment]
sorry, but i want to know what the default entry is. But when i console config.entry, it's undefined
