### ISSUE TITLE
customise router

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#485]
Hi,
What is the proper way to add the global guards ( beforeEach and afterEach ) to the nuxt router? plz

**Comment by Atinux** [comment]
@aymenpeak create a plugin with nuxt.js

`plugins/router-guards.js`
```js
import router from '~router'

router.afterEach((to, from) => {
  console.log('After each', to.fullPath)
})
```

In your `nuxt.config.js`:
```js
module.exports = {
  plugins: ['~plugins/router-guards']
}
```

**Comment by aymenpeak** [comment]
@Atinux  thanx :)

**Comment by jdinartejesus** [comment]
@Atinux  I'm using  `'~router'` this router on plugins and on production keeps display router as undefined. I'm using this to add google analytics. Any idea?
