### ISSUE TITLE
Nuxt.js crashes when visiting  to a page directly.

### ISSUE THREAD

**Issue by MuhammedKpln** [nuxt/nuxt.js#4859]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/cchoban/web-client/tree/nuxt](https://github.com/cchoban/web-client/tree/nuxt)

### Steps to reproduce

1. Visiting  "https://choban.app/packages/yarn"
2. Nuxt.js does not respond or giving any other response to the user.

### What is expected ?

Should respond to the user without any problem.

### What is actually happening?

When i go to the "https://choban.app/packages/yarn" directly from the browser, nuxtjs does not respond and gives error from the console. 
But when i firts go in to the "https://choban.app/packages/" and then navigating to the page ("https://choban.app/packages/yarn) it does work perfectly.

Same thing happnes on "https://choban.app/packages/all". I guess asyncData is making the problem. 

Tried both nuxt.js and express server but nothing happens. Maybe from 

Console error:
https://paste.laravel.io/5aa8f236-29b7-45e7-8574-6bac88a6e112#2-3

### Additional comments?

Tried on node:11.7-alpine docker image, tested node image also (latest ubuntu image)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8546">#c8546</a>)</em></sub></div>

**Comment by MuhammedKpln** [comment]
Could be same problem as #4848, trying.

**Comment by manniL** [comment]
@MuhammedKpln Probably the request doesn't succeed. You don' wrap a `try/catch` around it.

https://github.com/cchoban/web-client/blob/9b2a75c436d5eb3d761cf181cad6f7b4cbad1b44/pages/packages/_packageName/index.vue#L134-L137

As it seems, this is not a bug related to Nuxt.js itself but to your code.
