### ISSUE TITLE
Can't use JSON within classes while using nuxt/stringify bug

### ISSUE THREAD

**Issue by lukeshiels** [nuxt/nuxt.js#486]
I initially thought that this error was due to the auth0 package i'm using however [they think it's because of nuxt](https://github.com/auth0/auth0.js/issues/407).

I want to make a class wrapper (with ES6) for the Auth0 SDK I use within my app, like the following:

![auth0-e-1](https://cloud.githubusercontent.com/assets/11036001/24556455/4f525efc-162c-11e7-86f1-f1996e8e1cc5.jpeg)

However I'm getting the error:
![auth0-e-2](https://cloud.githubusercontent.com/assets/11036001/24556480/6927143a-162c-11e7-96d1-c4b2a7aaf087.jpeg)

I can make an instance of WebAuth fine, it's just when I define it within the 'this' namespace of my class that this fails.

The Auth0 team think it's how Nuxt [serialises](https://github.com/nuxt/nuxt.js/blob/d576dad069b985711a0eca8d0c10c852c0cacec3/lib/render.js#L109) JSON.

Any ideas/suggestions?

**Comment by lukeshiels** [comment]
Any updates?

**Comment by alexchopin** [comment]
Hi, have you seen our [nuxt auth0 example](https://github.com/nuxt/example-auth0)?
