### ISSUE TITLE
failed to create nested router

### ISSUE THREAD

**Issue by fq-zhang** [nuxt/nuxt.js#4862]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://gitee.com/data-geek/alexzhang](https://gitee.com/data-geek/alexzhang)

### Steps to reproduce

create nested folder structures under pages folder, but in router.js, nothing nested, all routes are direct children of routes.

### What is expected ?

nested routes created based on folder structure just like it in doc.

### What is actually happening?

no nested routes created

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8548">#c8548</a>)</em></sub></div>

**Comment by manniL** [comment]
@fq-zhang Please provide more information and a minimal reproduction. I can't clearly understand what your problem is.
