### ISSUE TITLE
Coffeescript parse failed

### ISSUE THREAD

**Issue by chiboreache** [nuxt/nuxt.js#4863]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://jsfiddle.net/chibo/3bh2szxr/1/](https://jsfiddle.net/chibo/3bh2szxr/1/)

### Steps to reproduce

https://nuxtjs.org/faq/pre-processors

yarn add -D pug pug-plain-loader coffeescript coffee-loader

### What is expected ?

working code?

### What is actually happening?

Module parse failed: Unexpected token (8:19) You may need an appropriate loader to handle this file type

  !*** ./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=coffee& ***!
  \************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

throw new Error("Module parse failed: Unexpected token (8:19)\nYou may need an appropriate loader to handle this file type.\n| \n| \n> export default data: ->\n|   { name: 'World' }\n| ");

/***/ }),

/***/ "./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/pug-plain-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./layouts/default.vue?vue&type=template&id=314f53c6&lang=pug&":
/*!*****************************************************************************************************************************************************************************************************************************************************!*\
  

/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module

### Additional comments?

Arch Linux - everything is bleeding edge

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8549">#c8549</a>)</em></sub></div>

**Comment by manniL** [comment]
There is a working example available at https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/coffeescript :relaxed: 

Please continue from there :+1:

**Comment by chiboreache** [comment]
Yeah that's works, thanks, but

> To be able to use these pre-processors, we need to install their webpack loaders:
> npm install --save-dev pug@2.0.3 pug-plain-loader coffeescript coffee-loader node-sass sass-loader

so, please do not mislead the users, it's not that simple `~_~`

besides `nuxt.config.coffee` - not working for some reason

even after tweaking `nuxt.config.js`

```
require('./modules/coffeescript.js')
import all from './nuxt.config.coffee'
```

**Comment by manniL** [comment]
@chiboreache Feel free to add a PR :relaxed: 

As mentioned in https://github.com/nuxt/docs/issues/996, this section needs a revamp, I agree!

**Comment by chiboreache** [comment]
Got it!

After I came up with steady rock build I'll pulled my first iteration, for shure heh


Everyone should know about coffeescript, that's a real dealbreaker for me _(as well as awesome pug and stylus, just pleasure for eyes)_, so much hate js syntax `;{` and logic overall, but in Vue-repo some people thinks it's situated only for _legacy_, that's a shame.., besides I could not set it up for **splatting objects** in Vue environment _(meanwhile nuxt-coffee works like a charm)_


so yeah, give me some guidance please ;)

**Comment by manniL** [comment]
Unfortunately, I'm not a profound coffeescript user :frowning_face: 

Not sure if `nuxt.config.coffee` will work. Similar to a `nuxt.config.ts`, you'd either need a "precompiler" or an own dist.

**Comment by chiboreache** [comment]
I set this up somehow with vue-cli 2 projects, therefore possible with Nuxt

**Comment by weotch** [comment]
I typically do this in nuxt.config.js:

```js
require('coffeescript/register')
module.exports = require('./nuxt.config.coffee')
```

In other words, I boot up CoffeeScript support for CJS required files, then require my CS config file.
