### ISSUE TITLE
[2.4.0] [npm] nuxt can not be installed

### ISSUE THREAD

**Issue by dweldon** [nuxt/nuxt.js#4870]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[http://www.example.org/](http://www.example.org/)

### Steps to reproduce

npm i "nuxt@latest"

### What is expected ?

Nuxt should install

### What is actually happening?

No matching version found for @nuxt/generator@2.4.0

### Additional comments?

node --version
v11.4.0
npm --version
6.7.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8554">#c8554</a>)</em></sub></div>

**Comment by pi0** [comment]
@dweldon Unfortunately this would be an NPM CDN cache problem. as [package](https://www.npmjs.com/package/@nuxt/generator) seems published. Please try again in few minutes / hour again.

**Comment by dweldon** [comment]
@pi0 Okay cool. Thanks for the fast response. I'll close when I get it installed.

**Comment by mauxtin** [comment]
FWIW I am having the same "problem" with both @nuxt/core and @nuxt/generator. (I will just try again in a couple of hours.)

![image](https://user-images.githubusercontent.com/40521145/51861387-bc92db00-2344-11e9-8527-c2b9372c4703.png)

**Comment by RomainLanz** [comment]
Seems fixed on my side!
