### ISSUE TITLE
CSP violation in modern builds

### ISSUE THREAD

**Issue by samrg472** [nuxt/nuxt.js#4876]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/v271z453](https://codesandbox.io/s/v271z453)

### Steps to reproduce

- Enable modern builds and CSP in the configuration
- Load the webpage
- Check the devtools console for a CSP violation

### What is expected ?

The Content-Security-Policy is expected to be satisfied.

### What is actually happening?

A CSP violation is occurring.
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'sha256-Q8VZ3JY1e/6NFowuA+3pjpynK6AzVNhbH31DIqVDFVM='". Either the 'unsafe-inline' keyword, a hash ('sha256-4RS22DYeB7U14dra4KcQYxmwt5HkOInieXK1NUMBmQI='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Notes

It's better to test locally than in the codesandbox. Codesandbox seems to have additional CSP errors that don't happen in a local environment.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8558">#c8558</a>)</em></sub></div>

**Comment by il-m-yamagishi** [comment]
```
!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
```

the script is appended to body and its hash are `sha256-4RS22DYeB7U14dra4KcQYxmwt5HkOInieXK1NUMBmQI=`.

It is workaround for Safari 10.1 `nomodule` bug. See [Safari 10.1 `nomodule` support](https://gist.github.com/samthor/64b114e4a4f539915a95b91ffd340acc).

in v2.4.3, [here](https://github.com/nuxt/nuxt.js/blob/13e494c0f0013252994eb0de0c4d92bd507b119d/packages/webpack/src/plugins/vue/modern.js#L98) appends the script.

Although we might not modify CSP header in webpack plugin, [renderer](https://github.com/nuxt/nuxt.js/blob/13e494c0f0013252994eb0de0c4d92bd507b119d/packages/vue-renderer/src/renderer.js#L382) appends another CSP script hash. Should we append there?

---

And current workaround is to add hash in nuxt.config.js.

```js
export default {
  render: {
    csp: {
      hashArgorism: 'sha256',
      policies: {
        'script-src': [
          "'sha256-4RS22DYeB7U14dra4KcQYxmwt5HkOInieXK1NUMBmQI='" // this line resolves the violation
        ]
      }
    }
  }
}
```

**Comment by manniL** [comment]
@il-m-yamagishi good catch! Would you like to submit a PR?

**Comment by jovanmaric** [comment]
@il-m-yamagishi any progress on the PR?

Also wouldn't having the option to disable inline-scripts (currently possible in vue-cli https://github.com/vuejs/vue-cli/issues/2570) mitigate this issue and expand on the http2 capabilities of Nuxt?

**Comment by ArmandoHerra** [comment]
I'm also looking into something related to this issue, I'm wanting to hash or nonce the scripts and styles appended to the template so I can get CSP rules to stop blocking resources, how is this going and if there is a way how can I check and edit it?

Thanks!

**Comment by manniL** [comment]
As @il-m-yamagishi said [here](https://github.com/nuxt/nuxt.js/issues/4876#issuecomment-463585416), this is likely related to the safari "nomodule" fix.

**Comment by sustained** [comment]
Adding the hashes doesn't work for me.

**Comment by MicroDreamIT** [comment]
I am having the same trouble, its ruin my life. 

```
18842af40923cd48144b.js:2 Refused to connect to 'https://my-api.com/api/tag/' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

(anonymous) @ 18842af40923cd48144b.js:2
t.exports @ 18842af40923cd48144b.js:2
t.exports @ 18842af40923cd48144b.js:2
Promise.then (async)
h.request @ 18842af40923cd48144b.js:2
h.<computed> @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
fe.<computed> @ 394c51c59fa615d2e03c.js:1
(anonymous) @ 394c51c59fa615d2e03c.js:1
d @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
t.<computed> @ 18842af40923cd48144b.js:2
r @ 18842af40923cd48144b.js:2
l @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
c.GET_STARS @ 394c51c59fa615d2e03c.js:1
(anonymous) @ 18842af40923cd48144b.js:2
h.dispatch @ 18842af40923cd48144b.js:2
dispatch @ 18842af40923cd48144b.js:2
(anonymous) @ 394c51c59fa615d2e03c.js:1
d @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
t.<computed> @ 18842af40923cd48144b.js:2
r @ 18842af40923cd48144b.js:2
l @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
re.methods.fetch @ 394c51c59fa615d2e03c.js:1
created @ 394c51c59fa615d2e03c.js:1
Qt @ 18842af40923cd48144b.js:2
fn @ 18842af40923cd48144b.js:2
t._init @ 18842af40923cd48144b.js:2
f @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
init @ 18842af40923cd48144b.js:2
I @ 18842af40923cd48144b.js:2
I @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
t._update @ 18842af40923cd48144b.js:2
r @ 18842af40923cd48144b.js:2
xn.get @ 18842af40923cd48144b.js:2
xn @ 18842af40923cd48144b.js:2
t @ 18842af40923cd48144b.js:2
In.$mount @ 18842af40923cd48144b.js:2
init @ 18842af40923cd48144b.js:2
I @ 18842af40923cd48144b.js:2
I @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
t._update @ 18842af40923cd48144b.js:2
r @ 18842af40923cd48144b.js:2
xn.get @ 18842af40923cd48144b.js:2
xn @ 18842af40923cd48144b.js:2
t @ 18842af40923cd48144b.js:2
In.$mount @ 18842af40923cd48144b.js:2
l @ 394c51c59fa615d2e03c.js:1
(anonymous) @ 394c51c59fa615d2e03c.js:1
d @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
t.<computed> @ 18842af40923cd48144b.js:2
r @ 18842af40923cd48144b.js:2
l @ 18842af40923cd48144b.js:2
Promise.then (async)
r @ 18842af40923cd48144b.js:2
l @ 18842af40923cd48144b.js:2
Promise.then (async)
r @ 18842af40923cd48144b.js:2
l @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
(anonymous) @ 18842af40923cd48144b.js:2
$ @ 394c51c59fa615d2e03c.js:1
(anonymous) @ 394c51c59fa615d2e03c.js:1
Promise.then (async)
(anonymous) @ 394c51c59fa615d2e03c.js:1
150 @ 394c51c59fa615d2e03c.js:1
f @ c7c30e02844cd6f3c3d5.js:1
149 @ 394c51c59fa615d2e03c.js:1
f @ c7c30e02844cd6f3c3d5.js:1
t @ c7c30e02844cd6f3c3d5.js:1
r @ c7c30e02844cd6f3c3d5.js:1
(anonymous) @ 394c51c59fa615d2e03c.js:1
Show 31 more frames
18842af40923cd48144b.js:2 Uncaught (in promise) Error: Network Error
    at t.exports (18842af40923cd48144b.js:2)
    at XMLHttpRequest.m.onerror (18842af40923cd48144b.js:2)
```

**Comment by RaphaelDDL** [comment]
Using Nuxt 2.10.2, I get the same kind of issue locally. Seems entire `vendors.app.js` are made of `eval()` so probably all will fail:

![image](https://user-images.githubusercontent.com/1087109/67332496-77779000-f4f5-11e9-9e18-c825892d1634.png)

I use Helmet CSP on the server/index.js, and I imagine adding 'unsafe-eval' to script-src would "fix", but then, isn't that a bad thing (adding eval as acceptable)?

**Comment by climberwoodi** [comment]
Is there any progress? Without this being fixed I cannot use a newer version than 2.9.2.

**Comment by HapLifeMan** [comment]
Up! :)

**Comment by clarkdo** [comment]
I suppose it might be related to source map, could you try to use source-map in devtool ?
https://nuxtjs.org/api/configuration-build/#extend

**Comment by clarkdo** [comment]
I just opened a pr a fix, could you please try if it solves your problems ?

**Comment by L422Y** [comment]
> ```js
>       hashArgorism: 'sha256',
> ```

Should this not be "hashAlgorithm"?
