### ISSUE TITLE
The type definition of `$loading` conflicts with Buefy's one

### ISSUE THREAD

**Issue by iwata** [nuxt/nuxt.js#4877]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/iwata/codesandbox-nuxt](https://github.com/iwata/codesandbox-nuxt)

### Steps to reproduce

```sh
$ git clone git@github.com:iwata/codesandbox-nuxt.git
$ yarn install
$ yarn dev
```

### What is expected ?

No type checking errors

### What is actually happening?

It shows this error:

```
ERROR in /Users/iwata/.go/src/github.com/iwata/codesandbox-nuxt/node_modules/@nuxt/vue-app/types/index.d.ts(73,18):
TS2430: Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Property 'open' is missing in type 'NuxtLoading' but required in type '{ open: (params: LoadingConfig) => { close: () => any; }; }'.
```

### Additional comments?

If you import `Buefy` looks like `plugins/buefy.ts`, it declares `$loading` for Vue instance.
https://github.com/buefy/buefy/blob/dev/types/index.d.ts#L10
So `NuxtApp` extends the Vue, therefore `$loading` conflicts.
https://github.com/nuxt/nuxt.js/blob/v2.4.0/packages/vue-app/types/index.d.ts#L73-L74

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8559">#c8559</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
Well, there is the same issue for ElementUI if i'm right.

I don't know what we're supposed to do, both of frameworks are setuping the same variable so 😬

@manniL WDYT ?

The only solution could be to have the `$loading` definition outside of `@nuxt/vue-app` to avoid that but it sounds weird to not have it inside.

**Comment by manniL** [comment]
@kevinmarrec The problem lies even deeper. If ElementUI and Buefy both use `$loading`, will they *override* the Nuxt.js `$loading`. Or will Nuxt override theirs?

We should think about how to properly avoid naming collisions like that.

**Comment by iwata** [comment]
Is it necessary to have a plugin namespace in Vue first?

**Comment by kevinmarrec** [comment]
@manniL I don't know, I guess they override Nuxt as they are Vue plugins (`Vue.use`) and instanciated on top of Nuxt ?

**Comment by kevinmarrec** [comment]
I didn't find a workaround yet, for the simple reason that IMO, UI libraries shouldn't directly non-namespaced add properties to the Vue instance interface.

For example, `Vuetify` uses `this.$vuetify.x`, meanwhile `Buefy` & `ElementUI` directly use `this.x`, which is IMO not good. (`this` being a Vue instance)

The issue is that these 2 UI libraries can't change this behavior without breaking changes.

**Comment by hartmut-co-uk** [comment]
I run into the issue with Element-ui as well.
I guess namespacing sounds like the way to go - but as @kevinmarrec mentioned this will come with breaking changes - so if rolled out as _@deprecated_ via (several / major) releases until _removed_ will take time..
Maybe it would be a good idea to escalate this to the vuejs team directly - to add documentation / guidelines to avoid such clashes going forward and with more frameworks, .. to come.

**Comment by bichikim** [comment]
@iwata may you need to define the $loading type 

```
import {ElLoading} from 'element-ui/types/loading'
import {ElMessage} from 'element-ui/types/message'
import {ElMessageBox} from 'element-ui/types/message-box'
import {ElNotification} from 'element-ui/types/notification'
declare module 'vue/types/vue' {
  interface Vue {
     readonly $loading: typeof ElLoading.service
     // maybe you will use these things also
     readonly $alert: typeof ElMessageBox.alert
     readonly $confirm: typeof ElMessageBox.confirm
     readonly $message: ElMessage
     readonly $msgbox: ElMessageBox
     readonly $notify: ElNotification
     readonly $prompt: typeof ElMessageBox.prompt
  }
}
```

**Comment by manniL** [comment]
@bichikim The issue is that it's a **naming collision** between the `$loading` from nuxt and the one from ElementUI/Buefy.

**Comment by bichikim** [comment]
@manniL Oh i see~ in that case, fix element-ui loading at `element-ui/lib/loading`

**Comment by arambert** [comment]
This error prevents the command `nuxt-ts generate` from working...

In my case, it's conflicting with Buefy.
So as a dirty temporary fix, I've edited `node_modules/@nuxt/vue-app-edge/types/index.d.ts` with:

```
+export interface LoadingConfig {
+}

export interface NuxtLoading extends Vue {
  fail?(): void;
  finish(): void;
  increase?(num: number): void;
  pause?(): void;
  start(): void;
+  open: (params: LoadingConfig) => { close: () => any; };
}
```

**Comment by P-de-Jong** [comment]
For now i added the following to my `tsconfig.json`:
```json
"compilerOptions": {
    "skipLibCheck": true
}
```

**Comment by AshleyCao** [comment]
@P-de-Jong's solution works for me

**Comment by nicbavetta** [comment]
> @P-de-Jong's solution works for me

This also worked for me, however, it seems to be more of a work-around than a solution.

**Comment by manniL** [comment]
We will change it to `$nuxt.$loading` in Nuxt 3 ☺️

**Comment by kevinmarrec** [comment]
@manniL In fact it's already `this.$nuxt.$loading`, and `this.$loading` is **only** a shortcut (AFAIK).
`$nuxt` being a Vue instance, in any case we need to say that `NuxtApp` ($nuxt) extends Vue.

The issue is 100% Buefy fault which is not extending **but overriding** Vue typedefs through https://github.com/buefy/buefy/blob/dev/types/index.d.ts#L10.

By doing this, they force the Vue instance to always have `$loading` property and also forcing it to be of type `LoadingProgrammatic`, which is wrong.
Meanwhile within Nuxt, we only say that `$nuxt` is a Vue instance with a `$loading` property.

Unless we force us to change the name from `$loading` to something else, there won't be workarounds.
Buefy (and ElementUI) should highly initiate a breaking change which namespace their properties.

**Comment by manniL** [comment]
@kevinmarrec 	Whoops. Updated my statement based on the things discused in the last meeting☺️

**Comment by noe132** [comment]
since if `$loading` is only used in `NuxtApp`
this could be a temp workaround
but won't be a perma fix if there is any naming collision in the future
```typescript
interface NuxtAppAnyLoading extends Vue {
  $loading: any
}

export interface NuxtApp extends NuxtAppAnyLoading {
  $loading: NuxtLoading
  isOffline: boolean
  isOnline: boolean
}
```

**Comment by iwata** [comment]
I confirmed fixed issuse with Buefy v0.8.0.

**Comment by georgyfarniev** [comment]
This issue still persists with element-ui

**Comment by coolsam726** [comment]
> This issue still persists with element-ui

For Element-UI, the only work-around that got me out of the mess is to override Nuxt's $loading. I did this by creating a new type file in my app and defining an interface which extends NuxtApp type, where I defined the type of $loading as 'any':

In file ~/types/nuxt.d.ts

```ts
import { NuxtApp } from "@nuxt/vue-app/types/index";

export interface NuxtLoading extends NuxtApp {
  $loading: any
}
```
