### ISSUE TITLE
If router.linkPrefetchedClass is set, the resulting class value is mangled

### ISSUE THREAD

**Issue by phof** [nuxt/nuxt.js#4882]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/lp2m6l80jm](https://codesandbox.io/s/lp2m6l80jm)

### Steps to reproduce

1) `git clone https://github.com/nuxt/nuxt.js.git`
2) `cd nuxt.js/examples/nuxt-prefetch/`
3) Add a class value (i.e.: class="someClass") to all "nuxt-link" items in all vue files in the "pages" folder
4) `yarn dev` to start nuxt
5) Load localhost:3000

### What is expected ?

The prefetched links to have a class value equal to "someClass nuxt-link-prefetched"

### What is actually happening?

The prefetched links have a class value equal to "someClasssomeClass nuxt-link-prefetched"

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8562">#c8562</a>)</em></sub></div>

**Comment by phof** [comment]
https://github.com/nuxt/nuxt.js/blob/fe57a5a929d0ef272f64da6f006f7c809211407e/packages/vue-app/template/components/nuxt-link.client.js#L97

I guess that `+=` should be a `=`?

**Comment by manniL** [comment]
@phof I guess so, yup.
