### ISSUE TITLE
TypeError: Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by romoo** [nuxt/nuxt.js#489]
## Steps to reproduce

```
vue init nuxt/starter demo
cd demo
yarn install
yarn add axios
```

create file `pages/users/_id.vue`

```
<template>
  <h1>{{ name }}</h1>
</template>

<script>
import axios from 'axios'

export default {
  data ({ params }) {
    return axios.get(`https://api.myjson.com/bins/${params.id}`)
    .then((res) => res.data)
  }
}
</script>

```

run `npm run dev`
visit `http://127.0.0.1:3000/users/dgbin`

**Comment by romoo** [comment]
If I edit package.json `"nuxt": "0.9.9"`, 'npm run dev' works fine.

**Comment by sebastianmacias** [comment]
Might be related to this one https://github.com/nuxt/nuxt.js/issues/453

**Comment by alexchopin** [comment]
`data` no longer accept context, you need to replace it by `asyncData`.
https://nuxtjs.org/guide/async-data

**Comment by ausir0726** [comment]
breaking change start from `0.10.0`
https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0
