### ISSUE TITLE
Running npm run dev is not showing component changes

### ISSUE THREAD

**Issue by freshface** [nuxt/nuxt.js#4890]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/wky229q9zl](https://codesandbox.io/s/wky229q9zl)

### Steps to reproduce

I created a new project on v2.4.0 and added a component.
When saving the terminal shows the output that the file is changed and compiled but on the localhost i dont see it.

In production it is ok

### What is expected ?

A change in the browser

### What is actually happening?

It is showing the initial pages/layout

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8566">#c8566</a>)</em></sub></div>

**Comment by CraftingGamerTom** [comment]
this is definitely still an issue.. any word on this?
