### ISSUE TITLE
SCSS path in nuxt.config not resolved

### ISSUE THREAD

**Issue by chiptoma** [nuxt/nuxt.js#4891]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

![2019-01-29 21_13_05-nuxt.config.js - client - Visual Studio Code.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b3f98d60-240a-11e9-b478-49939ef6e5f4.jpg)

### What is expected ?

To import the scss file

### What is actually happening?

![2019-01-29 21_12_26-Cmder.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/a1758fe0-240a-11e9-b478-49939ef6e5f4.jpg)

### Additional comments?

Working fine until 2.4.0
Node-sass and sass-loader installed.
Tried all sort of paths (@/, @, ~/, ~, /) and none of them work.
Removed node_modules and reinstalled them, removed package.lock.json...

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8567">#c8567</a>)</em></sub></div>

**Comment by manniL** [comment]
@chiptoma do you use `extractCSS`?

**Comment by chiptoma** [comment]
> @chiptoma do you use `extractCSS`?
No

**Comment by pi0** [comment]
Please try `@assets/...` @chiptoma

**Comment by chiptoma** [comment]
> Please try `@assets/...` @chiptoma

Tried all possible paths @, @/, ~, ~/,

**Comment by manniL** [comment]
@chiptoma can you show us your whole `nuxt.config.js`?

**Comment by pi0** [comment]
@chiptoma Something else. Please try `npm i node-sass sass-loader` / `yarn add node-sass sass-loader`

**Comment by chiptoma** [comment]
> @chiptoma Something else. Please try `npm i node-sass sass-loader` / `yarn add node-sass sass-loader`

Like I said, node-sass and sass-loader deps are installed locally

**Comment by chiptoma** [comment]
Found it!
Apparently, `sass-resources-loader` dep was missing. I wonder how that happened as `@nuxtjs/style-resources` has it as a dependency.
After installing it manually everything is fine...

**Comment by manniL** [comment]
Yey :clap:

**Comment by Mertakus** [comment]
You say that manually installing the sass-resources-loader did the trick for you, how in the world did you 'manually' install it though. Can someone please explain that to me, been searching for this stupid problem for hours now...

@chiptoma  @manniL

**Comment by christopherarter** [comment]
@Mertakus 

`npm install --save-dev sass-resources-loader`

**Comment by galuhramaditya** [comment]
put this to your nuxt.config:

render: {
    bundleRenderer: {
      shouldPreload: (file, type) => {
        return ['script', 'style', 'font'].includes(type)
      }
    }
  }

references: https://nuxtjs.org/examples/global-css/

**Comment by lsblsb** [comment]
@galuhramaditya: the render declaration seems not be required, if you ensure, that these packages are installed:
sass-resources-loader
sass-loader
node-sass

so the following command should do the trick:
`npm install --save-dev sass-resources-loader sass-loader node-sass`

**Comment by Dushusir** [comment]
step1:  

`npm i -D @nuxtjs/style-resources sass-loader node-sass`

step2:

```
module.exports = {
    // Other nuxt.config.js
    
    modules: ['@nuxtjs/style-resources'],
    styleResources: {
        scss: [
            'assets/scss/file/_path.scss',
            'assets/scss/file/_path-two.scss'
        ]
    }
}
```
work for me!

**Comment by MSkred** [comment]
Same issue for me on `"nuxt": "^2.10.2"` 

```
 ERROR  Failed to compile with 1 errors                                                                                             friendly-errors 08:48:07

This relative module was not found:                                                                                                 friendly-errors 08:48:07
                                                                                                                                    friendly-errors 08:48:07
* ../client/assets/sass/main.scss in ./.nuxt/App.js                                                                                 friendly-errors 08:48:07
ℹ Waiting for file changes                                                                                                                          08:48:07
ℹ Memory usage: 244 MB (RSS: 359 MB) 
```

**Comment by ryscript** [comment]
I don't know what in the world, but I couldn't get it working on my end, already tried all the suggestions above, read Nuxt Globel CSS documentation and still no luck, hmmm

**Comment by MSkred** [comment]
Npm i

**Comment by ktxxt** [comment]
When creating a nuxt app I chose `vuetify` and now I've removed it, and had the same issue.

Following the 2 steps in [this comment](https://github.com/nuxt/nuxt.js/issues/4891#issuecomment-552182022) solved my issue.
