### ISSUE TITLE
Combine asyncData return type with Vue component data type.

### ISSUE THREAD

**Issue by andoshin11** [nuxt/nuxt.js#4896]
### What problem does this feature solve?

While we can access the returned type information of Vue native apis (i.e. data, computed, props, methods), the return type of asyncData function is totally lost from "this" object.

I'm not sure if it's even possible to combine these type information without changes on Vue core types, but I believe it is 'must-have' goal for us to provide safe, correct, efficient type definitions for users.

I've already spent some hours to solve this problem yet I haven't seen a daylight. Hope I can rely on your help.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8568">#c8568</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@andoshin11 I might be wrong but I kind of understood you want to access `this` inside `asyncData` with the right type ? 

```ts
import { Component, Vue } from 'vue-property-decorator'

@Component({
  asyncData (this: MyPage, ctx) {
    return {
      test: this.bar() + this.foo // works & returns `foobar`
    }
  }
})
export default class MyPage extends Vue {
  foo: string = 'bar'
  bar () {
    return 'foo'
  }
}
```

**Comment by kevinmarrec** [comment]
OR If you asked about having autocompletion/typechecking on the return of `asyncData`, I don't think it's possible. Or maybe like this :

```ts
interface Test {
  propertyOne: string
  propertyTwo: string[]
}

@Component({
  asyncData (this: PageIndex, ctx): Test {
    return { // autocompletion/typecheck on the returned object
      propertyOne: 'foo',
      propertyTwo: ['bar', 'foo', 'bar']
    }
  }
})
export default class MyPage extends Vue implements Test {
  propertyOne = ''
  propertyTwo = [] 
}
```

**Comment by kevinmarrec** [comment]
@andoshin11 Any updates around this issue ? I need more info

**Comment by kevinmarrec** [comment]
@andoshin11 Any updates ?
I don't have any clue about what is exactly the request so I'll close the issue if I don't have any more info (issue being pending since almost 4 months without new comments of you)

**Comment by kevinmarrec** [comment]
Closing due to ~5 months inactivity.
