### ISSUE TITLE
how to modify nuxt server start port ,default port is 3000

### ISSUE THREAD

**Issue by leeir** [nuxt/nuxt.js#490]

**Comment by pi0** [comment]
@leeir you have two options: 
Setting `process.env.PORT ` before nuxt start or simply running `PORT=6060 nuxt ...`
Another way is adding config to `package.json` :
```json
"nuxt": {
 "port": 8080
}
```

**Comment by alexchopin** [comment]
https://nuxtjs.org/faq/host-port

**Comment by kaelzhang** [comment]
https://nuxtjs.org/faq/host-port encounters error 525

**Comment by liquidvisual** [comment]
I've tried this but the browser doesn't load anything:

    ERR_CONNECTION_REFUSED

**Comment by Fthi-S3074641** [comment]
From the official site:
`"config": { 

 "nuxt": {
   "host": "0.0.0.0",
   "port": "3333"
 }

},
"scripts": {
 "dev": "nuxt"
}`

**Comment by andriyfm** [comment]
`  Error: connect ECONNREFUSED 127.0.0.1:3000

  - util.js:992 Object._errnoException
    util.js:992:11

  - util.js:1014 _exceptionWithHostPort
    util.js:1014:20

  - net.js:1186 TCPConnectWrap.afterConnect [as oncomplete]
    net.js:1186:14`

**Comment by aebrs** [comment]
> https://nuxtjs.org/faq/host-port encounters error 525

Yes: it has on effect. Completely ignored by nuxt, while package.js config change the local port but there it seems impossible to use process.env.PORT. 
The other problem is that #nuxt  team is also ignoring this problem leaving it unsolved.

**Comment by aebrs** [comment]
> @aebrs There is probably something wrong with your deployment. If I do:
> 
> ```js
> PORT=4000 nuxt dev
> ```
> 
> On an empty directory for instance, I get a Nuxt app running on port 4000.

But I receive this:
 npm run dev

```
> nuxt-i18n-routing@1.0.0 dev F:\Ebrahimi\1397\Site\nuxt
> PORT=4000 nuxt dev

'PORT' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pi0** [comment]
@aebrs This is not a bug with nuxt. As you are using windows, please add [cross-env](https://www.npmjs.com/package/cross-env) dependency and then:

```
cross-env PORT=4000 nuxt dev
```

Also mentioned at docs:
- https://nuxtjs.org/faq/host-port/#with-nuxt_host-and-nuxt_port-env-variables
- https://nuxtjs.org/api/configuration-dev

**Comment by aebrs** [comment]
> @aebrs This is not a bug with nuxt. As you are using windows, please add [cross-env](https://www.npmjs.com/package/cross-env) dependency and then:
> 
> ```
> cross-env PORT=4000 nuxt dev
> ```
> Also mentioned at docs:
> 
> * https://nuxtjs.org/faq/host-port/#with-nuxt_host-and-nuxt_port-env-variables
> * https://nuxtjs.org/api/configuration-dev

Dear Pooya, Thank you for your attention. But there is a miss-understanding. The problem is not with localhost. My problem is when I want to deploy code on server: windows, plesk, Onyx. There is no clear instruction on how to upload and run code on shared servers. Tried to use all type of online codes but the project do not start and site is not seen on line. Mostly it is about getting host and port from server. In Node.js and Vue.js, both, this work fine : 
`const host = process.env.host || "0.0.0.0";
const port = process.env.port || 8080;`
but nuxt.js response is 'undefined'.

**Comment by pi0** [comment]
@aebrs Would you please your current `package.json` and `nuxt.config.js`files?

**Comment by aebrs** [comment]
> @aebrs Would you please your current `package.json` and `nuxt.config.js`files?

package.json:

> {
  "name": "nuxt-i18n-routing",
  "version": "1.0.0",
  "description": "Localized routing with Nuxt.js",
  "scripts": {
    "dev": "node server.js",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node server.js",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "express-session": "^1.15.6",
    "nuxt": "^1.4.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-awesome-swiper": "^3.1.3",
    "vue-i18n": "^7.3.2",
    "vue-smooth-scroll": "^1.0.13",
    "vuetify": "^1.2.6"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-register": "^6.26.0",
    "cross-env": "^5.2.0",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1"
  }
}
and nuxt.config.js:

> const session = require('express-session')
const { generateRoutes } = require('./utils/router')
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'order.iranord.com',
    meta: [
      { charset: 'utf-8' },
      //for mobile friendly website
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Localized routing with Nuxt.js' }
    ],
    link: [
      // icon of wbsite
      { rel: 'icon', type: 'image/x-icon', href: '/Iranord.ico' },
      // for using icons import this font
      { rel:'stylesheet' , href:'https://fonts.googleapis.com/icon?family=Material+Icons'}
    ]
  },
  /**
   * Router configuration
   */
  router: {
    middleware: ['i18n', 'mobile'],
    extendRoutes (routes) {
      const newRoutes = generateRoutes(routes)
      routes.splice(0, routes.length)
      routes.unshift(...newRoutes)
    }
  },

  //import css and styles
  css: ['~/assets/app.styl', '@/style/style-fa.css', 'swiper/dist/css/swiper.css'],

  /*
  ** Customize the progress bar color
  */
  loading: { color: '#ffd100' },
  // /*
  // ** Session ID
  // */
  serverMiddleware: [
    // session middleware
    session({
      secret: 'super-secret-key',
      resave: true,
      saveUninitialized: false,
      cookie: {
        secure: false,
        httpOnly: false ,
        // نامی که کوکی با آن ذخیره میشود
        name: 'iran-order-cookies',
        domain: '.iranord.ir',
        // set Session ID in 8 hours
        maxAge: 480000,
        // دسترسی به یک session در تمام صفحات
        path: '/' 
      }
    }),
  ],
  /*
  ** Build configuration
  */
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      }
    ]
  },
  build: {
    maxChunkSize: 300000,
    vendor: ['axios'],
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  },
  plugins: [
    { src: '~/plugins/global-mixin.js' },
    { src: '~/plugins/vue-i18n.js', injectAs: 'i18n' },
    { src: '~/plugins/vuetify.js' },
    //for using swiper in nuxt we must write [ssr: false]
    { src: '~plugins/vue-awesome-swiper', ssr: false }
  ]
}

**Comment by aebrs** [comment]
> @aebrs This is not a bug with nuxt. As you are using windows, please add [cross-env](https://www.npmjs.com/package/cross-env) dependency and then:
> 
> ```
> cross-env PORT=4000 nuxt dev
> ```
> Also mentioned at docs:
> 
> * https://nuxtjs.org/faq/host-port/#with-nuxt_host-and-nuxt_port-env-variables
> * https://nuxtjs.org/api/configuration-dev

This is what server return, as you can see port is not received from server:

`> nuxt-i18n-routing@1.0.0 start C:\Inetpub\vhosts\lordcms.com\httpdocs
> node server.js

{ ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\lordcmsc\\AppData\\Roaming',
  COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
  'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
  COMMONPROGRAMW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'WIN-THS1C1O0F04',
  COMSPEC: 'C:\\Windows\\system32\\cmd.exe',
  HOME: 'C:\\Users\\lordcmsc',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Inetpub\\vhosts\\lordcms.com',
  INIT_CWD: 'C:\\Inetpub\\vhosts\\lordcms.com\\httpdocs',
  LOCALAPPDATA: 'C:\\Users\\lordcmsc\\AppData\\Local',
  MAILENABLE_PATH: 'C:\\PROGRA~2\\Plesk\\MAILSE~1\\MAILEN~1',
  NODE: 'C:\\Program Files\\nodejs\\node.exe',
  NODE_EXE: 'C:\\Program Files\\nodejs\\\\node.exe',
  NPM_CLI_JS: 'C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js',
  npm_config_access: '',
  npm_config_allow_same_version: '',
  npm_config_also: '',
  npm_config_always_auth: '',
  npm_config_argv: '{"remain":[],"cooked":["run","start"],"original":["run","start"]}',
  npm_config_auth_type: 'legacy',
  npm_config_bin_links: 'true',
  npm_config_browser: '',
  npm_config_ca: '',
  npm_config_cache: 'C:\\Users\\lordcmsc\\AppData\\Roaming\\npm-cache',
  npm_config_cache_lock_retries: '10',
  npm_config_cache_lock_stale: '60000',
  npm_config_cache_lock_wait: '10000',
  npm_config_cache_max: 'Infinity',
  npm_config_cache_min: '10',
  npm_config_cafile: '',
  npm_config_cert: '',
  npm_config_cidr: '',
  npm_config_color: 'true',
  npm_config_commit_hooks: 'true',
  npm_config_depth: 'Infinity',
  npm_config_description: 'true',
  npm_config_dev: '',
  npm_config_dry_run: '',
  npm_config_editor: 'notepad.exe',
  npm_config_engine_strict: '',
  npm_config_fetch_retries: '2',
  npm_config_fetch_retry_factor: '10',
  npm_config_fetch_retry_maxtimeout: '60000',
  npm_config_fetch_retry_mintimeout: '10000',
  npm_config_force: '',
  npm_config_git: 'git',
  npm_config_git_tag_version: 'true',
  npm_config_global: '',
  npm_config_globalconfig: 'C:\\Users\\lordcmsc\\AppData\\Roaming\\npm\\etc\\npmrc',
  npm_config_globalignorefile: 'C:\\Users\\lordcmsc\\AppData\\Roaming\\npm\\etc\\npmignore',
  npm_config_global_style: '',
  npm_config_group: '',
  npm_config_ham_it_up: '',
  npm_config_heading: 'npm',
  npm_config_https_proxy: '',
  npm_config_if_present: '',
  npm_config_ignore_prepublish: '',
  npm_config_ignore_scripts: '',
  npm_config_init_author_email: '',
  npm_config_init_author_name: '',
  npm_config_init_author_url: '',
  npm_config_init_license: 'ISC',
  npm_config_init_module: 'C:\\Users\\lordcmsc\\.npm-init.js',
  npm_config_init_version: '1.0.0',
  npm_config_json: '',
  npm_config_key: '',
  npm_config_legacy_bundling: '',
  npm_config_link: '',
  npm_config_local_address: '',
  npm_config_loglevel: 'notice',
  npm_config_logs_max: '10',
  npm_config_long: '',
  npm_config_maxsockets: '50',
  npm_config_message: '%s',
  npm_config_metrics_registry: 'https://registry.npmjs.org/',
  npm_config_node_gyp: 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
  npm_config_node_options: '',
  npm_config_node_version: '8.11.1',
  npm_config_offline: '',
  npm_config_onload_script: '',
  npm_config_only: '',
  npm_config_optional: 'true',
  npm_config_otp: '',
  npm_config_package_lock: 'true',
  npm_config_package_lock_only: '',
  npm_config_parseable: '',
  npm_config_prefer_offline: '',
  npm_config_prefer_online: '',
  npm_config_prefix: 'C:\\Users\\lordcmsc\\AppData\\Roaming\\npm',
  npm_config_production: '',
  npm_config_progress: 'true',
  npm_config_proxy: '',
  npm_config_read_only: '',
  npm_config_rebuild_bundle: 'true',
  npm_config_registry: 'https://registry.npmjs.org/',
  npm_config_rollback: 'true',
  npm_config_save: 'true',
  npm_config_save_bundle: '',
  npm_config_save_dev: '',
  npm_config_save_exact: '',
  npm_config_save_optional: '',
  npm_config_save_prefix: '^',
  npm_config_save_prod: '',
  npm_config_scope: '',
  npm_config_scripts_prepend_node_path: 'warn-only',
  npm_config_script_shell: '',
  npm_config_searchexclude: '',
  npm_config_searchlimit: '20',
  npm_config_searchopts: '',
  npm_config_searchstaleness: '900',
  npm_config_send_metrics: '',
  npm_config_shell: 'C:\\Windows\\system32\\cmd.exe',
  npm_config_shrinkwrap: 'true',
  npm_config_sign_git_tag: '',
  npm_config_sso_poll_frequency: '500',
  npm_config_sso_type: 'oauth',
  npm_config_strict_ssl: 'true',
  npm_config_tag: 'latest',
  npm_config_tag_version_prefix: 'v',
  npm_config_timing: '',
  npm_config_tmp: 'C:\\Users\\lordcmsc\\AppData\\Local\\Temp',
  npm_config_umask: '0000',
  npm_config_unicode: '',
  npm_config_unsafe_perm: 'true',
  npm_config_usage: '',
  npm_config_user: '',
  npm_config_userconfig: 'C:\\Users\\lordcmsc\\.npmrc',
  npm_config_user_agent: 'npm/5.6.0 node/v8.11.1 win32 x64',
  npm_config_version: '',
  npm_config_versions: '',
  npm_config_viewer: 'browser',
  npm_execpath: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
  npm_lifecycle_event: 'start',
  npm_lifecycle_script: 'node server.js',
  npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe',
  npm_package_dependencies_axios: '^0.18.0',
  npm_package_dependencies_express_session: '^1.15.6',
  npm_package_dependencies_nuxt: '^1.4.2',
  npm_package_dependencies_stylus: '^0.54.5',
  npm_package_dependencies_stylus_loader: '^3.0.2',
  npm_package_dependencies_vue_awesome_swiper: '^3.1.3',
  npm_package_dependencies_vue_i18n: '^7.3.2',
  npm_package_dependencies_vue_smooth_scroll: '^1.0.13',
  npm_package_description: 'Localized routing with Nuxt.js',
  npm_package_devDependencies_babel_eslint: '^7.2.3',
  npm_package_devDependencies_babel_register: '^6.26.0',
  npm_package_devDependencies_eslint: '^4.19.1',
  npm_package_devDependencies_eslint_config_standard: '^10.2.1',
  npm_package_devDependencies_eslint_loader: '^1.9.0',
  npm_package_devDependencies_eslint_plugin_html: '^3.1.1',
  npm_package_devDependencies_eslint_plugin_import: '^2.7.0',
  npm_package_devDependencies_eslint_plugin_node: '^5.1.1',
  npm_package_devDependencies_eslint_plugin_promise: '^3.5.0',
  npm_package_devDependencies_eslint_plugin_standard: '^3.0.1',
  npm_package_name: 'nuxt-i18n-routing',
  npm_package_readmeFilename: 'README.md',
  npm_package_scripts_build: 'nuxt build',
  npm_package_scripts_dev: 'nuxt',
  npm_package_scripts_generate: 'nuxt generate',
  npm_package_scripts_lint: 'eslint --ext .js,.vue --ignore-path .gitignore .',
  npm_package_scripts_precommit: 'npm run lint',
  npm_package_scripts_start: 'node server.js',
  npm_package_version: '1.0.0',
  NPM_PREFIX_NPM_CLI_JS: 'C:\\Users\\lordcmsc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
  NUMBER_OF_PROCESSORS: '16',
  OS: 'Windows_NT',
  PATH: 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;C:\\Inetpub\\vhosts\\lordcms.com\\httpdocs\\node_modules\\.bin;C:\\Program Files (x86)\\Plesk\\Mail Servers\\Mail Enable\\BIN;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Plesk\\ctl;C:\\Program Files (x86)\\Plesk\\Mail Servers\\Mail Enable\\BIN64;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\ManagementStudio\\;C:\\Program Files\\nodejs\\;C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming\\npm;C:\\Users\\lordcmsc\\AppData\\Local\\Microsoft\\WindowsApps',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
  PLESK_BIN: 'C:\\Program Files (x86)\\Plesk\\admin\\bin',
  PLESK_BIN64: 'C:\\Program Files (x86)\\Plesk\\admin\\bin64',
  PLESK_CLI: 'C:\\Program Files (x86)\\Plesk\\bin',
  PLESK_DIR: 'C:\\Program Files (x86)\\Plesk\\',
  PLESK_VHOSTS: 'C:\\Inetpub\\vhosts\\',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD',
  PROCESSOR_LEVEL: '23',
  PROCESSOR_REVISION: '0101',
  PRODUCT_ROOT_D: 'C:\\Program Files (x86)\\Plesk\\',
  PROGRAMDATA: 'C:\\ProgramData',
  PROGRAMFILES: 'C:\\Program Files',
  'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
  PROGRAMW6432: 'C:\\Program Files',
  PROMPT: '$P$G',
  PSMODULEPATH: 'C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\',
  PUBLIC: 'C:\\Users\\Public',
  SYSTEMDRIVE: 'C:',
  SYSTEMROOT: 'C:\\Windows',
  TEMP: 'C:\\Users\\lordcmsc\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\lordcmsc\\AppData\\Local\\Temp',
  USERDOMAIN: 'WIN-THS1C1O0F04',
  USERNAME: 'lordcmsc',
  USERPROFILE: 'C:\\Users\\lordcmsc',
  VUE_ENV: 'server',
  WINDIR: 'C:\\Windows' }
 DONE  Compiled successfully in 17894ms15:08:36

Hash: [1me9a75e76dc5f57f080b0[39m[22m
Version: webpack [1m3.12.0[39m[22m
Time: [1m17894[39m[22mms
                                  [1mAsset[39m[22m       [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m[1mChunk Names[39m[22m
              [1m[32m9.b1105f2236a6f705b32f.js[39m[22m    4.63 kB   [1m9, 11[39m[22m  [1m[32m[emitted][39m[22m  
                [1m[32mimg/Iranord.abc67ec.png[39m[22m    8.46 kB        [1m[39m[22m  [1m[32m[emitted][39m[22m  
[1m[32mlayouts_default.d8d900751a21e72dfd1d.js[39m[22m    26.2 kB       [1m1[39m[22m  [1m[32m[emitted][39m[22m  layouts_default
 [1m[32mlayouts_mobile.180c7cc4e0f047197ac6.js[39m[22m    23.6 kB       [1m2[39m[22m  [1m[32m[emitted][39m[22m  layouts_mobile
              [1m[32m3.b5b609148e56252a2db9.js[39m[22m    13.8 kB       [1m3[39m[22m  [1m[32m[emitted][39m[22m  
              [1m[32m4.617d1ee0db6b7a771dad.js[39m[22m    5.57 kB    [1m4, 6[39m[22m  [1m[32m[emitted][39m[22m  
              [1m[32m5.1e3335b32e05ddba6338.js[39m[22m    9.19 kB       [1m5[39m[22m  [1m[32m[emitted][39m[22m  
              [1m[32m6.33f4a2ef750f04ba027b.js[39m[22m    5.29 kB       [1m6[39m[22m  [1m[32m[emitted][39m[22m  
              [1m[32m7.4852c2276f1b9a51ca33.js[39m[22m    9.78 kB       [1m7[39m[22m  [1m[32m[emitted][39m[22m  
              [1m[32m8.6178d804a740d86c8ab0.js[39m[22m    6.83 kB       [1m8[39m[22m  [1m[32m[emitted][39m[22m  
            [1m[32mapp.2fa802193ca866351564.js[39m[22m    81.9 kB       [1m0[39m[22m  [1m[32m[emitted][39m[22m  app
             [1m[32m10.85c0178273298c79cc5d.js[39m[22m    4.86 kB      [1m10[39m[22m  [1m[32m[emitted][39m[22m  
             [1m[32m11.382d8c2814538982defe.js[39m[22m    4.36 kB      [1m11[39m[22m  [1m[32m[emitted][39m[22m  
             [1m[32m12.b95d0a9871045442c0c5.js[39m[22m    3.44 kB      [1m12[39m[22m  [1m[32m[emitted][39m[22m  
             [1m[32m13.5a3bc939a5533683b199.js[39m[22m    2.01 kB      [1m13[39m[22m  [1m[32m[emitted][39m[22m  
             [1m[32m14.ebbbecc6c3e6e32414cb.js[39m[22m     104 kB      [1m14[39m[22m  [1m[32m[emitted][39m[22m  
         [1m[32mvendor.d7ff0ee5860e7a0e6b19.js[39m[22m     188 kB      [1m15[39m[22m  [1m[32m[emitted][39m[22m  
             [1m[32m16.012425da20a2822ac6ce.js[39m[22m    24.3 kB      [1m16[39m[22m  [1m[32m[emitted][39m[22m  
       [1m[32mmanifest.e9a75e76dc5f57f080b0.js[39m[22m    1.75 kB      [1m17[39m[22m  [1m[32m[emitted][39m[22m  manifest
                               [1m[32mLICENSES[39m[22m  931 bytes        [1m[39m[22m  [1m[32m[emitted][39m[22m  
 + 3 hidden assets
Hash: [1me340a4311684513eb4c6[39m[22m
Version: webpack [1m3.12.0[39m[22m
Time: [1m3235[39m[22mms
             [1mAsset[39m[22m    [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m[1mChunk Names[39m[22m
[1m[32mserver-bundle.json[39m[22m  698 kB        [1m[39m[22m  [1m[32m[emitted][39m[22m  
0.0.0.0
8080
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (C:\Inetpub\vhosts\lordcms.com\httpdocs\node_modules\express\lib\application.js:618:24)
    at start (C:\Inetpub\vhosts\lordcms.com\httpdocs\server.js:29:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-i18n-routing@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nuxt-i18n-routing@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lordcmsc\AppData\Roaming\npm-cache\_logs\2018-10-23T11_38_39_874Z-debug.log
Run`

**Comment by pi0** [comment]
@aebrs Related: https://support.plesk.com/hc/en-us/articles/115003763474-Unable-to-access-website-with-Node-js-application-EADDRINUSE.

**Comment by aebrs** [comment]
> @aebrs Related: https://support.plesk.com/hc/en-us/articles/115003763474-Unable-to-access-website-with-Node-js-application-EADDRINUSE.

Dear Pooya: 
1- I used the same code in node.js for backend server and it receive correct port on server (http://app.lordcms.com return 404 means server works) :
const port = process.env.PORT;
2- The same things is used in Vue.js, I used, and it is working on the same server (order.lordcms.com):
`const HOST = process.env.HOST
const PORT = process.env.PORT && Number(process.env.PORT)`

**So that is why I believe that it is not with PLESK, certainly it is something with NUXT.js**

**Comment by pi0** [comment]
@aebrs I've fully tested Nuxt with Plex Onyx and both development and production builds are working. Please refer to this link: https://github.com/pi0/nuxt-plesk-demo

If you had any further problems, please fork that repo and open a support ticket on [Plesk Help Center](https://support.plesk.com/hc/en-us) about your problem. We can't help anymore investigating about your server setup problems.
