### ISSUE TITLE
Official codesandbox demo doesn't work

### ISSUE THREAD

**Issue by eladcandroid** [nuxt/nuxt.js#4901]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/github/nuxt/codesandbox-nuxt/tree/master](https://codesandbox.io/s/github/nuxt/codesandbox-nuxt/tree/master)

### Steps to reproduce

Open the codesandbox link

### What is expected ?

Working demo

### What is actually happening?

502: Bad Gateway error
![Screen Shot 2019-01-30 at 13.15.02.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/4f625910-2480-11e9-ac9a-e5676ad8d69a.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8575">#c8575</a>)</em></sub></div>

**Comment by manniL** [comment]
Should work again ☺️ 
Thanks for the report!

**Comment by SheKnowsItsAMultipass** [comment]
Just started up from the template and I'm getting the same error as above.

**Comment by thebspin** [comment]
I am currently experiencing the same issue since yesterday evening (about 14 hours ago for me now)

**Comment by manniL** [comment]
Working again.

**Comment by mrcoder98** [comment]
I've same issue again ... 502 bad gateway
