### ISSUE TITLE
Nuxt can be multi-process webpack package?

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#491]
Nuxt can be multi-process webpack package?
Linux project in the project when the file is more time to compile to 91% of the time, will compile for a long time have not yet progress

**Comment by alexchopin** [comment]
You need to be more specific about your question and the context about it.
We cannot help you without this.

**Comment by yuchonghua** [comment]
I look forward to nuxt in the webpack build compile time to be able to configure whether to use multi-process module, and then the webpack can be compiled at the same time more than the process, which is conducive to my rapid build, only in nuxt build and nuxt dev can quickly compile the file

**Comment by yuchonghua** [comment]
Because each time in the compilation to 91% of the time will be compiled very long can be compiled to 100% completed
