### ISSUE TITLE
Documentation: Add docs for debugging nuxt.js

### ISSUE THREAD

**Issue by blowsie** [nuxt/nuxt.js#4911]
### What problem does this feature solve?

Developer experience, also might reduce the number of issues reported if devs knew how to step through the code when required.

### What does the proposed changes look like?

Add simple debugging examples using 
 - VS Code
 - WebStorm
 - Chrome

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8580">#c8580</a>)</em></sub></div>

**Comment by manniL** [comment]
Please send that request to https://github.com/nuxt/docs/ ☺️

**Comment by blowsie** [comment]
no probs, my bad
