### ISSUE TITLE
global.URL is missing

### ISSUE THREAD

**Issue by honeroku** [nuxt/nuxt.js#4914]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/ww5n6p5mll](https://codesandbox.io/s/ww5n6p5mll)

### Steps to reproduce

Accessing URL object like `new URL('http://example.com');` anywhere in server side code.

### What is expected ?

URL object is accessible globally in server side since it is defined as global interface in node.js.
https://nodejs.org/docs/latest-v10.x/api/globals.html#globals_url

### What is actually happening?

Accessing URL object in server side code causes "ReferenceError URL is not defined".

### Additional comments?

It had been accessible before and including v2.3.4.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8582">#c8582</a>)</em></sub></div>

**Comment by honeroku** [comment]
I found reproduction code in codesandbox is misleading since downgrading to nuxt@2.3.x didn't solve this issue.
I suppose codesandbox runs older version of node.js or I'm completely misunderstanding system structure of codesandbox.

Anyway, I could reproduce this issue on my local env with following steps.

- `npx create-nuxt-app url-test` with default settings
- add `new URL('http://example.com');` in beforeCreate in pages/index.vue
- `npm run dev`
- get "URL is not defined" error

then

- downgrade with `npm i nuxt@2.3`
- `npm run dev`
- runs fine

@manniL I have tested several minor versions of node v10 including `10.15.1`, `10.6.0`, `10.5.0`, `10.0.0`.

**Comment by manniL** [comment]
Can't repro.

![image](https://user-images.githubusercontent.com/640208/52063496-b3835300-256a-11e9-8526-c3120e823389.png)

`  beforeCreate(){ const a = new URL('http://example.com'); console.log(a) }`

**Comment by manniL** [comment]
Whoops. Testing with `mode: 'spa'` is not a good idea 😂 

Can repro.

**Comment by honeroku** [comment]
And, `npm run dev` reproduces, while `npm run build && npm start` does not.

**Comment by bosenok** [comment]
confirm

**Comment by ramiroazar** [comment]
Also experiencing this issue. Running `yarn run dev` leads to a `ReferenceError: URL is not defined` error, while running `yarn run generate` does not.

Nuxt `v2.5.1`
Node `v10.15.3`

**Comment by pimlie** [comment]
I looked into this a bit and it seems that eg URL is (and has been) a non-enumerable property on the `global` object. Eg `global.Buffer` can still be used but that is enumerable (for now, it will become non-enumerable in v12 probably).

Not sure where to look further for this, but probably its a babel / core-js issue? As a side note, core-js v3 has a URL polyfill.

**Comment by michaelpumo** [comment]
I'm getting the same issue on Node 10.15.3 (current stable as of this date).

**Comment by chulman444** [comment]
In my case, I'm importing a module that uses URL from the vue file. There are two or three ways to reproduce my case.

* I'm using typescript with Nuxt
* I've tried Url from "url" node module and `URL` dom object
* I've tried with and without `"lib": ["dom"]`
* I've tried with and without `npm i @types/node`

```
import { Url } from "url"
```

and/or

```
import * as url from "url"
const URL = url.Url
```

VSCode throws error that `Url` is a type/interface but it's used as a value in first case. In both cases, they 'work' despite VSCode throwing error, but doesn't work properly. For example:

```
console.log(new Url("http://localhost:3001"))
```

prints a Url instance where all properties are `null`.

Third or second case:

```
console.log(URL)
```

just throws reference error that URL is not defined.

As expected, `URL` works just fine in the vue files.

---

Node version: 10.2.1
Nuxt version: 2.4.0

**Comment by dhritzkiv** [comment]
I am also still getting this, running nuxt@2.7.0, using TypeScript, and after following the instructions on how to include "core-js@3" in my build: when server side rendering, URL is undefined, no matter the form (including many that @chulman444 tried). When accessing URL in the browser, it works fine.

I was able to temporarily get around it by including `import "core-js/modules/web.url";` in my scripts, but this seems unnecessary.

**Comment by palfaro91** [comment]
Any update on this issue? Currently experiencing the same issue. Server side Url is undefined . 
Using node version 12.3.1 and Nuxt 2.8.1

**Comment by pimlie** [comment]
@clarkdo As you are the build grandmaster, do you maybe have an idea how `URL` could not be available?

When I test vanilla Vue ssr (from the vue-meta examples) I cannot reproduce this issue. So it seems to be something in Nuxt?

**Comment by clarkdo** [comment]
This is because we're using `runInNewContext: true` by default in dev mode for avoiding memory leak, but vue does't inject `URL` in sandbox global https://github.com/vuejs/vue/blob/master/src/server/bundle-renderer/create-bundle-runner.js#L9.

You can use `runInNewContext: false`, but it may cause unexpected memory leak in dev mode.

So I created a pr in Vue for adding URL https://github.com/vuejs/vue/pull/10414.

**Comment by ThatGuySam** [comment]
Here's a temporary workaround that pulls from the appropriate place depending on the context. 

```
// ./url.js
import * as url from 'url'

// Create the URL contructor for node or use the existing one for the browser
const urlConstructor = (process.server) ? url.URL : URL

// Create the URLSearchParams contructor for node or use the existing one for the browser
const paramsConstructor = (process.server) ? url.URLSearchParams : URLSearchParams

export { urlConstructor as URL }

export { paramsConstructor as URLSearchParams }
```

And you just pull it in like this
`import { URL, URLSearchParams } from './url'`

**Comment by kms-rscholz** [comment]
Another temporary workaround:

```
if (process.server) {
  const { URLSearchParams } = require('url')
  global.URLSearchParams = URLSearchParams
}
```

**Comment by palfaro91** [comment]
Hi @pi0 this should be fixed in the next release according to your recent merge?

**Comment by nassan** [comment]
Is this in theory fixed in 2.11.0?

**Comment by timmw** [comment]
@nassan it is not. 2.11.0 was released 17th Dec, the fix was merged into the dev branch on 19th Jan.

**Comment by EdwardAckerman** [comment]
I used to have this error, but now I have only Request is not defined with the new 2.11.0
Now in production as well ;-;
