### ISSUE TITLE
Problem with Brython

### ISSUE THREAD

**Issue by chiboreache** [nuxt/nuxt.js#4918]
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://codepen.io/chombor/pen/aXJJZa?editors=1010](https://codepen.io/chombor/pen/aXJJZa?editors=1010)

### Steps to reproduce

1. add cdn script
2. paste  """ python code """ into variable
3. pass it to script tag with v-html on it 

### What is expected ?

worked python code inside Nuxt

### What is actually happening?

not worked python code inside Nuxt

### Additional comments?

Here is static example that works:
https://github.com/chiboreache/strSquarificator/blob/master/docs/index.html

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8585">#c8585</a>)</em></sub></div>

**Comment by manniL** [comment]
Does it work with the traditional Vue template (https://codesandbox.io/s/vue)?

**Comment by chiboreache** [comment]
With Vue it's working fine

here is official example:

```
from browser import document, window
from javascript import this


Vue = window.Vue.new


def reverse_message(ev):
    this().message = ''.join(reversed(this().message))

app5 = Vue({
  'el': '#app-5',
  'data': {
    'message': 'Hello Vue.js!'
  },
  'methods': {
    'reverseMessage': reverse_message
  }
})
```
http://www.brython.info/gallery/test_vue.html

but how to implement it in Nuxt, when everything hidden under the hood!?

**Comment by chiboreache** [comment]
with no luck `~_~`

```
<template lang="pug">
  section
    #app {{ message }}
    script(
      type="text/python"
    ).
      from browser import document, window
      from javascript import this
      Vue = window.Vue.new
      app = Vue({
        'el': '#app',
        'data': {
          'message': 'Hello Brython Vue!'
        }
      })
</template>
<script lang="coffee">
  export default
    head:
      bodyAttrs:
        onload: 'brython(1)'
      script:
        [
          {
            src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython_stdlib.js"
            type="text/javascript"
            body: true
          }
          {
            type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js"
            body: true
          }
        ]
    data: ->
      message: 'Hello Vue.js!'
</script>
```
meh

```
/index.vue?vue&type=script&lang=coffee&:25:14: error: unexpected = src[1;31m=[0m"https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython_stdlib.js" [1;31m ^[0m L24: src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython_stdlib.js" ^ at Object.module.exports 
```

**Comment by manniL** [comment]
If you want to use Nuxt in SPA mode, that shouldn't be a problem.

In SSR mode, Brython would have to run *before* the parser. That might be possible with hooks but would be a bit of work.

All in all: Looks doable but might require a bit of effort.

Closing here as it's a 3rd party lib integration problem and therefore rather a question than a bug report for feature request.

**Comment by chiboreache** [comment]
Got it! Thanks.
