### ISSUE TITLE
Feed store state with async data at application start

### ISSUE THREAD

**Issue by Kylart** [nuxt/nuxt.js#492]
Hey there, 

I am getting started with Vuex and Nuxt (which really is awesome) and I am facing a problem for hours. 

My application is an _Electron_ one. Basically what I want to do is stated in the title. I'll give some code for it to be more clear.

What I want to do is feeding `store.state.randomVariable` with some async data on application start.

My method is a promise. This is what I would like to do.
```javascript
// At start
getLatest().then((items) => {
  store.state.releases = items
}
``` 

As those data would not be hear on page rendering, I should then see them app on my html as if I would do it with basic Vue and without reloading of course with something like this:

```javascript
let vm = new Vue({
  el: '#some-element',
  data: {
    releases: []
  }
})

getLatest().then((items) => {
  vm.releases = items
})
```

I tried working with middleware and some other things but I could not get it working. I would really appreciate a hand on this.

Thank you!

**Comment by Kylart** [comment]
Oh, by the way, this `getLatest()` method needs methods that comes from modules.
Thanks !

**Comment by alexchopin** [comment]
Hi, you can use fetch() instead of asyncData to call the store actions for a page or use nuxtServerInit() for global fetch at the first server load. More info: https://nuxtjs.org/guide/vuex-store

**Comment by Kylart** [comment]
Hi, 

I would like to do this but, as far as i understand this I need to define my method in the store or in my modules in the mutations (actually I'm using the module mode).

The thing is that every time I want to import or require the module(s) I need for my method to work, I get errors like this : 
```
ERROR in ./~/tunnel2/lib/tunnel.js
Module not found: Error: Can't resolve 'tls' in '/Users/Kylart/WebstormProjects/Nuxt_KawAnime/node_modules/tunnel2/lib'
 @ ./~/tunnel2/lib/tunnel.js 4:10-24
 @ ./~/tunnel2/index.js
 @ ./~/req-fast/lib/util.js
 @ ./~/req-fast/lib/req.js
 @ ./~/nyaapi/index.js
 @ ./store/releases.js
 @ ./store nonrecursive ^\.\/.*\.js$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
```  

Maybe I'm doing it wrong ?
```javascript
// store/index.js
export const state = {
  msg: "hello"
}

export const mutations = {
  
}
```
```javascript
// store/releases.js
const malScraper = require('mal-scraper')  // Gets errors
// Or
import * as malScraper from 'mal-scraper'  // Same

export const state = {
  releases: []
}

export const mutations = {
  // I guess my method should be there ? 
}
```

**Comment by ausir0726** [comment]
I tried your package `mal-scraper` 

it seen look like  a server-side package . `use request package`
so that you got tls dependence issue ( tls maybe got fs and net )

so .... maybe you need run your code you want in server-side and prepare data you want .
you can try with 

```js
if ( process.SERVER_SIDE ) {
  const malScraper = require('mal-scraper');
  // fetch data and feed to store you want , but be careful async fetch .
}|
```

**Comment by bratberg** [comment]
This works in my application (fetching and filling the store with employees when the server starts):
```
// store/index.js
import axios from '~plugins/axios'
import {values} from 'lodash'

export const state = {
  employees: []
}

export const mutations = {
  setEmployees (state, employees) {
    state.employees = employees
  }
}

export const actions = {
  async nuxtServerInit ({commit}) {
    let {data} = await axios.get('employees.json')
    commit('setEmployees', values(data))
  }
}
```

**Comment by Kylart** [comment]
@ausir0726 I am using the nuxt/electron starter. Also, I need a method that acts on store at application start (server side) and also callable from client-side.

@bratberg It does work in mine too but the problem seems to come from my package [`mal-scraper`](https://github.com/Kylart/MalScraper) as @ausir0726 said, I don't get why it is causing such troubles tough...

**Comment by ausir0726** [comment]
@Kylart  be my understanding ... ( if Incorrect hope someone help correcting )

all your .vue file or plugin will prepare with vue-loader ...
so if you package use some node.js lib , like fs , net , tls .... 
vue-loader want find the package in your node_modules folder , 
but , those package is in node.js lib , so vue-loader can't find ...
vue-loader want pack those js to your client js , so it show tls can't find .....

I never use electron , just have quick view
maybe it can create a custom route like `api/malScraper/2016/fall`
than that route can use your package fetch data and return the json data 
I don't know electron , maybe you can use this create route
https://github.com/m0n0l0c0/electron-router

or you can make your malScraper micro-service on internet
and in electron call your malScraper with axios
but ... I think that is not a good idea for you ...
that you should bear huge bandwidth ...

**Comment by ausir0726** [comment]
@Kylart 

I clone nuxt/electron repo , I seen it has it own http-server
so, I re-write the route , add custom route I want 
and put you `mal-scraper` package in that route ...

then use `axios` fetch that route .... 
you can checkout my test repo 
https://github.com/ausir0726/nuxt-electron-with-custom-route

it's just for my test example , for your reference .
note: I changed nuxt.js to latest version .

you can check my commit 
https://github.com/ausir0726/nuxt-electron-with-custom-route/commit/bd51aef9374a6ba769f12dedbe0480e039afd1f2

**Comment by Kylart** [comment]
Wow @ausir0726 you have my thanks ! It works perfectly this way. 

As far as I understand your solution, I would need to create a special route every time i want to do some work like this am I right? 

_Yet_ I would like to make it work with the store but I can't manage to get it working with the nuxtServerInit() method. I might doing anything wrong...
```javascript
// store/index.js

import axios from 'axios'

export const state = {
  seasons: []
}

export const mutations = {
  setSeasons: function (state, data) {
    state.seasons = data
    console.log('Seasons set.')
  }
}

export const actions = {
  async nuxtServerInit ({commit}) {
    console.log('[INIT]')

    // Does not even 'commit'
    const { data } = await axios.get(`malScraper.json?year=2016&season=fall`)
    console.log('Got a response from axios')
    commit('setSeasons', values(data))

    // Same results (it is the same thing right ?)
    // return axios.get(`malScraper.json?year=2016&season=fall`).then((response) => {
    //   console.log('Got a response from axios')
    //   const {data} = response
    //   commit('setSeasons', data)
    // })
  }
}
```

```vue
<template>
  <div>
    <h1>Welcome!</h1>
    <nuxt-link to="/about">About page</nuxt-link>
    <ul v-if="seasons.length">
      <li v-for="item in seasons">title : {{item.title}}</li>
    </ul>
    <div v-else>
      <p>mal-scraper is on fetching data... please wait..</p>
    </div>
  </div>
</template>

<script>
export default {
  data() {

  },
  computed: {
    seasons: function () {
      return this.$store.state.seasons
    }
  }
};
</script>
```

Moreover, the '[INIT]' message from nuxtServerinit() seems to be appearing a lot (perhaps every second or so) when I'm running in dev mode. This is really worrying... And my app stays on the "Loading application" screen..

Am I doing anything wrong here ?

Still thank you for your time, I really appreciate it.

**Comment by ausir0726** [comment]
@Kylart  yes , maybe ... 
I think this is just a one way to resolve you problem .
you also can working with vuex store .

but nuxtServerInit only run on SSR ( npm build )
if you want fetch data when open you electron app you should modify

```js
// store/index.js
import Vue from  'vue'
import Vuex from 'vuex'
import axios from 'axios'

Vue.use(Vuex)

const store = new Vuex({
  state : {
    seasons: []
  },
  mutations : {
    setSeasons: function (state, data) {
      state.seasons = data
    }
  },
  actions = {
    async browserInit({commit}) {
      const { data } = await axios.get(`malScraper.json?year=2016&season=fall`)
      commit('setSeasons', data )
    }
  }
})

store.dispatch('browserInit');

export default store ;

```

```vue
<template>
  <div>
    <h1>Welcome!</h1>
    <nuxt-link to="/about">About page</nuxt-link>
    <ul v-if="seasons.length">
      <li v-for="item in $store.state.seasons">title : {{item.title}}</li>
    </ul>
    <div v-else>
      <p>mal-scraper is on fetching data... please wait..</p>
    </div>
  </div>
</template>

<script>
export default {
  data() {
  },
};
</script>
```

I didn't try this code , but it should work ...
seen you almost there ....

**Comment by Kylart** [comment]
@ausir0726 Thank you so much! It works perfectly. I think I can make it work completely from there. 

`browserInit()` was not referenced in the documentation though... Or I did not find it. I'll take a look at `electron-router` since I don't want to overcharge `main.js` and I have multiple routes to make.

I think I could also make my routes in some static files (assets directory).

Anyway, thank you for you help !

**Comment by ausir0726** [comment]
@Kylart 

`browserInit()` just I named and dispatch it after created vuex . 
you can defined yours .

😆

**Comment by Kylart** [comment]
@ausir0726 

Yea I realized afterwards 😊 . That's why I updated 😆 

`browserInit()` is a good name so I might keep it !

**Comment by Kylart** [comment]
Ah I should probably close this issue since it is solved ! 😄

**Comment by aymenpeak** [comment]
@bratberg i did the same as you did 
![image](https://cloud.githubusercontent.com/assets/19589742/24902686/d59437c8-1ea2-11e7-9128-e798a46788a3.
the state changed on the console but in the browser still empty ...

**Comment by agriboz** [comment]
@ausir0726 your code example works quite well
