### ISSUE TITLE
body argument in res.end call is undefined in production build

### ISSUE THREAD

**Issue by nugrahawahyu** [nuxt/nuxt.js#4920]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://jsfiddle.net/wahyunugraha/u946Lasw/3/](https://jsfiddle.net/wahyunugraha/u946Lasw/3/)

### Steps to reproduce

- use the middleware in reproduction link
- run with yarn dev, you will see the value of body argument
- run with yarn build && yarn start, body argument is undefined

### What is expected ?

res.end's body argument is not undefined in the production build

### What is actually happening?

res.end's body argument is undefined in the production build

### Additional comments?

not sure if the issue is from nuxt or express

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8587">#c8587</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't repro (CSB is in prod mode): https://codesandbox.io/s/github/manniL/nuxt-4920/tree/master/
