### ISSUE TITLE
"No SSR build found" situation

### ISSUE THREAD

**Issue by Vinnythetrue** [nuxt/nuxt.js#4921]
Hi,
I am currently experiencing a situation where I'm unable to deploy my NuxtJS application on a shared online server running Node...
So basically my problem is that "nuxt start" results in a "No SSR build found" message and quits. As I'm having problems building directly on the distant server (memory problems...) I thought I could build locally and upload my build, right ?
So I thought the result of the building command (nuxt build) is in the .nuxt/ folder, so I copied this one on the distant server.
But that doesn't change anything, the "nuxt start" command will still fail with the same message... So is it possible to build on one machine then send the build to another one ? What am I missing here ?

Vinny

**Comment by aube** [comment]
Before server start try to use
`npm install`
