### ISSUE TITLE
How to set up Nuxt.js with Nginx

### ISSUE THREAD

**Issue by ald890** [nuxt/nuxt.js#493]
I would like to ask for some tutorial or advice on how to set up Nuxt.js + Express.js (whatever) with Nginx. I have some problems with loading and caching files by Nginx. My public path is wrong.

**Comment by ausir0726** [comment]
run your node server ( npm run start ) on port 3000
and add nginx host proxy_pass 80 to 3000 .

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

is this helpful ?

**Comment by ald890** [comment]
@ausir0726 
Nope, I am run the application and everything looks nice, except console log in chrome.
I have a lot of 404 errors in "public", it looks like I have a bad configuration for public directory.

My conf: https://d3uepj124s5rcx.cloudfront.net/items/362C0z1b0h0I05281m2K/Image%202017-04-02%20at%2012.21.25%20PM.png

**Comment by ausir0726** [comment]
maybe you don't need setting root folder 
just forward 80 to 3000

```conf
server {
    listen 80;
    server_name dev.nuxt;
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**Comment by ausir0726** [comment]
if you just run http://localhost:3000 
is also got public error ?

**Comment by ald890** [comment]
@ausir0726 
I am changed the config in Nginx and server still doesn't working. https://cl.ly/joLi
It's weird because the application is working, although in the console still has errors.
In localhost:3000 without Nginx application works properly and looks like static files are read from public dir.
Localhost: http://localhost:3000/public/vendor.bundle.00f8a7a6911fb6e55d16.js - 304
Nginx: http://dev.nuxt/public/manifest.00f8a7a6911fb6e55d16.js - 404

**Comment by ausir0726** [comment]
@ald890 ummm....

but if you use nuxt/express template .
those file should in _nuxt_ folder ..
do you have change it ?

![capture](https://cloud.githubusercontent.com/assets/7247064/24588081/2b90130a-17f4-11e7-833a-36f54e7bd40a.PNG)

**Comment by ald890** [comment]
@ausir0726 
I solved this error, in nginx conf.
I don't have the "dist" folder with assets.
```
location ~* \.(?:css|js)$ {
                expires 1y;
                access_log off;
                add_header Cache-Control "public";
}
```

To fix this I create bundle with command "nuxt build" and then nuxt create folder
"./nuxt/dist/", before that I was used "npm run build" and this command don't make this folder so nginx wasn't see files. 

But now I have another errors...
"[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. "

I was change my template to simple as possible.

```
<template>
  <div class="xx">
    <p>Hello</p>
   </div>
 </template>
```

And I have still errors.

**Comment by ausir0726** [comment]
@ald890 
do you have used some client-side only package ?
that could make client-side rendered virtual DOM tree is not matching server-rendered content .


If the function to be displayed is normal, I personally ignore it ....

**Comment by ald890** [comment]
@ausir0726 
1. How to fix errors with client-side rendered virtual DOM
In "express-templte" https://github.com/nuxt/express 
commands "nuxt build" doesn't working, but with "npm run build" templates works.

 2. How to fix errors with Nginx caching 
In Nginx conf:
`root /project_path;`
In Nuxt project copy all files from "project_path/./nuxt/dist" to "project_path/_nuxt"
Then Nginx can see static files, I don't think this is the best solution... https://nuxtjs.org/api/configuration-build#publicpath

**Comment by kodekrendel** [comment]
Strange becouse I have everything working out of the box. Few days ago generated Let's Encrypt for nuxt/express, and I just point .public folder in nginx config (for certbot). As for app files in public folder - I can acess them in public folder without any of your nginx config. Try to delete all of this, and start with simple proxy.

**Comment by kodekrendel** [comment]
```
server {

        listen 80;
        listen [::]:80;
        server_name example.top;
        return 301 https://$server_name$request_uri;

}

server {

        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        include snippets/ssl-example.top.conf;
        include snippets/ssl-params.conf;

        location / {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }

        location /.well-known {
                root /home/ubuntu/again/222/static;
        }
}

server {

        listen 80;
        listen [::]:80;
        server_name old.example.top;
        return 301 https://$server_name$request_uri;

}

server {

        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name old.example.top;
        include snippets/ssl-example.top.conf;
        include snippets/ssl-params.conf;

        location / {
                proxy_pass http://localhost:5000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
}
```

**Comment by ald890** [comment]
@kodekrendel 
The reverse proxy works properly from the box. 
I have problems with caching static files, but I solved this problem.

**Comment by kodekrendel** [comment]
@ald890 ok, now I get it. I don't think manual copy files is the best solution. Or you speak about another solution?

```
"[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside

, or missing . Bailing hydration and performing full client-side render. "
```
I think everybody have this error now. Not sure why, but everyone says you can ignore it.

**Comment by ald890** [comment]
@kodekrendel 
I also think about manual copying files is a bad idea but in the docs is explained this topic https://nuxtjs.org/api/configuration-build#publicpath

` The client-side rendered virtual DOM tree...` - this error shows only when I run "nuxt build", but if I run "npm run build" errors are not showing up.

**Comment by ald890** [comment]
@kodekrendel 
Nginx is better for serve and cache static files. 
You can look for results - better results belongs to the Nginx ofc :)
This is a very simple example, but if you have a lot of images this is big difference. 
https://cl.ly/joQ7

**Comment by motia** [comment]
@ald890, look at the configuration below, it serves static files through nginx if available or fall back as a request to express. I believe that is what you want.

```
    /// nuxt.config.js
     ....
      generate: {
        dir: r('./public')
      },
   ...
```


```
            // /etc/nginx/sites-enabled/example.app
            server {
	    listen 80;
	    listen 443 ssl http2;
	    server_name example.app;
	    root "/var/www/example/public";

	    charset utf-8;

	    location / {
		try_files $uri $uri/ @proxy;
	    }

	    location @example {
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_http_version 1.1;
		proxy_pass http://127.0.0.1:3000;
	    }

	    access_log off;
	    error_log  /var/log/nginx/example-error.log error;

	    #ssl_certificate     /etc/nginx/ssl/example.crt;

	    #ssl_certificate_key /etc/nginx/ssl/example.key;
	}
```

**Comment by ktquez** [comment]
For me it worked by only changing publicPath to '/dist/'

*nuxt.config.js*
```javascript
...
build: {
  publicPath: '/dist/'

...
```

And in Nginx I put as path root the directory '.nuxt'
*my-domain.conf*

**Comment by manzurahammed** [comment]
@ausir0726 thanks 
it's works for me
