### ISSUE TITLE
SPA mode not prerendering pages at all

### ISSUE THREAD

**Issue by Dahamugo** [nuxt/nuxt.js#4932]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/Dahamugo/nuxt-spa-bug-reproduction](https://github.com/Dahamugo/nuxt-spa-bug-reproduction)

### Steps to reproduce

Create new app with `yarn create nuxt-app`, selecting "Single Page App" rendering mode and "vuetify" custom UI framework.
Run `yarn build`

### What is expected ?

index.html and inspire/index.html files in dist folder should contain pre-rendered content of their respective pages

### What is actually happening?

index.html and inspire/index.html files in dist folder only contain a loading spinner
![288f182a-e174-4125-a94a-27b01412f481.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/5c714110-276f-11e9-8df4-e758855c41ff.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8595">#c8595</a>)</em></sub></div>

**Comment by manniL** [comment]
What you want is `mode: 'universal'` and `yarn generate` :relaxed: 

Using `mode: 'spa'` will provide a traditional (non-prerendered) SPA :relaxed:

**Comment by codeofsumit** [comment]
@manniL would be great to add this to the documentation:
https://nuxtjs.org/guide#static-generated-pre-rendering-

**Comment by manniL** [comment]
@codeofsumit Fully agree! Feel free to send in a PR to the docs.

The recent PR https://github.com/nuxt/nuxt.js/pull/6556 should also help people who are unaware of the difference.
