### ISSUE TITLE
Coffeescript contribution error: ci/circleci: lint — Your tests failed on CircleCI

### ISSUE THREAD

**Issue by chiboreache** [nuxt/nuxt.js#4938]
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://github.com/chiboreache/pug-stylus-coffee-nuxt](https://github.com/chiboreache/pug-stylus-coffee-nuxt)

### Steps to reproduce

Open pull request for https://github.com/chiboreache/pug-stylus-coffee-nuxt or fork https://github.com/chiboreache/nuxt.js

### What is expected ?

Nice and dandy Coffeescript example in Nuxt repo

### What is actually happening?

js lint attempting to uglificate script section of .vue files

### Additional comments?

Just embarrassing:

```
#!/bin/bash -eo pipefail
yarn test:lint
yarn run v1.13.0
$ yarn lint
$ eslint --ext .js,.mjs,.vue .

/home/circleci/project/examples/pug-stylus-coffee/pages/index.vue
  24:11  error  Parsing error: Unexpected token, expected ","

  5 |   components: { Logo },
  6 |   computed:
> 7 |     message: -> @$store.state.msgComputed
    |            ^
  8 | }
  9 | 

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8599">#c8599</a>)</em></sub></div>

**Comment by chiboreache** [comment]
Yeah, I also noticed that, but even after adding extra ugly markup, it's still give me an error `¯\_(ツ)_/¯`

**Comment by manniL** [comment]
See #4927
