### ISSUE TITLE
nuxt 0.10.5 pages context undefined

### ISSUE THREAD

**Issue by LouisSun1989** [nuxt/nuxt.js#494]
Hello everyone! After I upgrade nuxt to 0.10.5, the data function in the component of pages can not get the context object. I try to print it , it show undefined.But when I rollback the nuxt to  0.9.9, it is ok. I don't know why.

**Comment by ausir0726** [comment]
start 0.10.0 have breaking change
https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0

change you data() {}  to asyncData() {}

**Comment by LouisSun1989** [comment]
@ausir0726 thanks very much.the problem is resolved by using your solution.

**Comment by fxh615** [comment]
@LouisSun1989  
i have the same problem can you tell me the solution?

**Comment by sunsl516** [comment]
@fxh615 update your nuxt version to 0.10.0 or higher

**Comment by sunsl516** [comment]
@fxh615 after 0.10.0 , we should use asyncData()， not data() to deal with the async http
