### ISSUE TITLE
Firebase Hosting

### ISSUE THREAD

**Issue by b02505048** [nuxt/nuxt.js#4940]
Hello there, Nuxt is great and I'm newbie. I don't really understand the way to deploy the Nuxt Project.

When I run `npm run build` , it create a `dist` and inside there's 2 directories, one is `client`, and the other one is `server`.

I `firebase init` the `dist` and it create a new `index.html` . Which is totally not related to what we code.

How to deploy it properly? Am I missing something out there? And is it possible to achieve SSR by simply using firebase hosting(no cloud function)? Thank you!

**Comment by b02505048** [comment]
I did try to ask on  https://otechie.com/nuxt 
but it request me to do a payment. 

It's super duper unfriendly to student. VERY DISAPPOINTED.

**Comment by manniL** [comment]
@b02505048 
![image](https://user-images.githubusercontent.com/640208/52201803-7bc72480-2864-11e9-8928-bdb74303cfcf.png)

1. Please **read** what the bot or the issue template is telling you. You should use CMTY to filean issue (https://bug.nuxtjs.org/). You don't have to use Otechie for that.
2. If you do: Payed consulting means **payed** consulting.

**Comment by Neo-Zhixing** [comment]
To answer your question, you do firebase init in your project root, and set the dist directory as the firebase hosting root. Then, setup the rewrite.

In my case, I used `nuxt generate` and upload the entire dist directory to firebase.

This is how my firebase.json looks like
```json
{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/200.html"
      }
    ],
    "cleanUrls": true
  }
}
```

And I agree that there's nothing to be disappointed about payed consulting. No one is responsible for answering your question, especially for a question that can be easily looked up

**Comment by Neo-Zhixing** [comment]
Oh and `index.html` was automatically generated by Nuxt. And it's generally impossible to achieve SSR with only static hosting, since SSR means `Server Side Rendering`. How do you do server side rendering without a server?

So either deploy a SPA or use `nuxt generate` to generate the entire site.
