### ISSUE TITLE
router.base value with Extended unicode (åäö) fails

### ISSUE THREAD

**Issue by jroxendal** [nuxt/nuxt.js#4948]
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Steps to reproduce

`yarn create nuxt-app test_nuxt && cd test_nuxt` (I selected express and not much else)

Drop ```router: {
    base: "/%C3%B6l/",
  }``` 
intro you nuxt config. start a dev server. go to http://localhost:3000/öl. 

### What is expected ?

I expect the site to load properly from the /öl url. 

### What is actually happening?

you may see the page blink and disappear with a DOM tree mismatch hydration error in the console. mode: 'spa' doesn't work at all (it can't find the page). base addresses without weird characters work fine. 

my live nuxt site running at https://litteraturbanken.se/översättarlexikon/ exhibits another symptom: using the back button at any time throws up the 404 page. cannot reproduce this with a minimal example, however. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8606">#c8606</a>)</em></sub></div>

**Comment by begueradj** [comment]
Use `$router.push(öl)`  when the index component is created or mounted

**Comment by jroxendal** [comment]
@manniL just a ping about this issue, which is still wreaking havoc on my production site. Did anyone have time to look at it yet?

**Comment by manniL** [comment]
@jroxendal Not yet unfortunately. A few things:

* Does it work with `base: '/öl'` by any chance?
* Does it work with a standalone nuxt instance (no server framework)?

**Comment by jroxendal** [comment]
Thanks for getting back to me. Testing with nuxt 2.4.0:

`base: '/öl` gives at `404` at `localhost:3000/`, which is expected. it also gives a `404` at `localhost:3000/öl` and `/öl/`, unfortunately. For `/öl`, the message is:
`Cannot GET /%C3%B6l`. 

`Use a custom server framework: none` when scaffolding with `yarn create nuxt-app`.

**Comment by manniL** [comment]
@jroxendal alright. and using `base: "/%C3%B6l/"` + nuxt standalone (no custom server framework) will net the same results as described in the original issue?

**Comment by jroxendal** [comment]
Yeah, same as original post. Page blinks, screen goes white, hydration error in console when using `base: "/%C3%B6l/"` (no custom framework).

**Comment by manniL** [comment]
Alright.

My guess is that the router base doesn't match the actual URL path because of different en-/decoding :thinking:

**Comment by jroxendal** [comment]
yeah, see me comment from feb 5 about the line 160 in connect/index.js above. there seems to be some issue where `path` and `route` variables do match when base is `/ol` but not when they're `öl`. just going in there and encoding one side or decoding the other wasn't enough, though. 🤷‍♂️

**Comment by manniL** [comment]
I think I found sth.

**Comment by jroxendal** [comment]
short and sweet solution 😀

**Comment by jroxendal** [comment]
Bad news: still getting hydration error from this fix. It is show the page now, no blink then white screen, but hydration error in log. @manniL are we sure the test you wrote actually checks for hydration errors?

**Comment by manniL** [comment]
@jroxendal 	let me test it again :wink:

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/54753385-39be2c00-4be1-11e9-96ae-6ccea8d47f0a.png)
No white screen anymore. But you are right, hydration errors coming up again :thinking:
