### ISSUE TITLE
different versions a main site

### ISSUE THREAD

**Issue by filoret256** [nuxt/nuxt.js#495]
different versions a main site
EN - 0.10.5
RU/CH/JP - 0.9.9
but all them link to one 
https://github.com/nuxt/nuxt.js

**Comment by ausir0726** [comment]
@filoret256 that because muti-language for 0.10.x not ready yet ...
so it only can show 0.9.9 ....

**Comment by alexchopin** [comment]
https://github.com/nuxt/nuxtjs.org/issues/15
