### ISSUE TITLE
Django + Nuxt.js

### ISSUE THREAD

**Issue by SteveVanzuriak** [nuxt/nuxt.js#496]
If it is posible, how I can create it?

**Comment by ausir0726** [comment]
you can write Django restful api server 
and nuxt.js communicate your server with json .

if you want your nuxt.js realtime got SSR page , you can use nuxt/express ( need node.js )
or you can use nuxt generate a static version put on CDN or you Django static folder .

you can design a day or a hour , or every time you modify back-end data then re-generate project and put it to cdn , or any web host you want ....

the solution that my project working with PHP and .NET ....

**Comment by hopkinson** [comment]
excuseme.I want to ask, if i want to put my code built by Nuxt.js in Django static folder ,how to build it??  
Because i met a old Django project that wasn't separate front and rear ends, need me to put Nuxt code in it
