### ISSUE TITLE
Access ctx property that was set by middleware in layout

### ISSUE THREAD

**Issue by Qvatra** [nuxt/nuxt.js#4962]
### What problem does this feature solve?

when I set some property on the ctx using middleware I want to be able to access it in my layout.
The problem is that this property is not yet set when nuxtServerInit is executed so I can not commit it the my vue store..

this is the middleware I use that sets isMobile on ctx:
export default function (ctx) {
  const userAgent = ctx.req ? ctx.req.headers['user-agent'] : navigator.userAgent
  ctx.isMobile = /mobile/i.test(userAgent)
}

and this is how I tried to catch that info:
export const actions = {
  nuxtServerInit ({ dispatch }, ctx) {
    dispatch('app/setIsMobile', ctx.isMobile) // ctx.isMobile here always undefined because middleware was not called yet
  }
}

### What does the proposed changes look like?

maybe allowing fetch with ctx work in layout?

    fetch ({ dispatch }, ctx) {
      dispatch('app/setIsMobile', ctx.isMobile)
    }

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8614">#c8614</a>)</em></sub></div>

**Comment by manniL** [comment]
@Qvatra Any reason you don't dispatch it in your middleware?

**Comment by Qvatra** [comment]
@manniL, mmm, good point. I will try that and let you know if it works. Thank you

**Comment by Qvatra** [comment]
That works, thank you
