### ISSUE TITLE
Cannot read property 'outputOptions' of undefined

### ISSUE THREAD

**Issue by derevandal** [nuxt/nuxt.js#4965]
### Version

[2.4.3](https://github.com/nuxt.js/releases/tag/2.4.3)

### Reproduction link

[https://codesandbox.io/s/30k541yq35](https://codesandbox.io/s/30k541yq35)

### Steps to reproduce

* Create new Nuxt@^2.4.0
* Add `SCSS` support `npm install --save-dev node-sass sass-loader bootstrap bootstrap-vue`
* `Add `.scss` files in `assets/scss/`
* Set `extractCSS` and `parallel` to `true` in the `build` property of `nuxt.config.js`
* Add `~assets/scss/app.scss` in `css` array, for example, in `nuxt.config.js`

### What is expected ?

To work as expected.

### What is actually happening?

Error in console: 
ERROR  in ./assets/scss/app.scss                    friendly-errors 19:20:49

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 9)
Cannot read property 'outputOptions' of undefined

    at Object.pitch (/sandbox/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:67:98)
                                                     friendly-errors 19:20:49
 @ ./.nuxt/App.js 3:0-33
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=modern&path=/__webpack_hmr/modern ./.nuxt/client.js}

And set `parallel` to `false`, CSS file didn't loaded.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8616">#c8616</a>)</em></sub></div>

**Comment by stevefan1999-personal** [comment]
This might not be the fault of Nuxt, but rather [extract-css-chunks-webpack-plugin](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin) itself:
I set a halting trap right over the `publicPath` variable:
```js
if (typeof query.publicPath !== 'string') {
     console.log({ this: this, query })
     while(1);
}
```
(Nope, debugger won't work in this case)

And got this when `query.publicPath` is nowhere to be seen:
```js
{ this:
   { version: 2,
     resolve: [Function: resolve],
     emitWarning: [Function: emitWarning],
     emitError: [Function: emitError],
     exec: [Function: exec],
     options: { context: '/mnt/Projects/nuxt/hw' },
     webpack: true,
     'thread-loader': true,
     sourceMap: false,
     target: 'web',
     minimize: undefined,
     resourceQuery: '?vue&type=style&index=0&lang=css&',
     context: '/mnt/Projects/nuxt/hw/.nuxt/components',
     loaderIndex: 0,
     loaders: [ [Object], [Object], [Object], [Object], [Object] ],
     resourcePath: '/mnt/Projects/nuxt/hw/.nuxt/components/nuxt-loading.vue',
     async: [Function: async],
     callback: [Function],
     cacheable: [Function: cacheable],
     addDependency: [Function: addDependency],
     dependency: [Function: addDependency],
     addContextDependency: [Function: addContextDependency],
     getDependencies: [Function: getDependencies],
     getContextDependencies: [Function: getContextDependencies],
     clearDependencies: [Function: clearDependencies],
     resource: [Getter/Setter],
     request: [Getter],
     remainingRequest: [Getter],
     currentRequest: [Getter],
     previousRequest: [Getter],
     query: [Getter],
     data: [Getter] },
  query: {} }
{ this:
   { version: 2,
     resolve: [Function: resolve],
     emitWarning: [Function: emitWarning],
     emitError: [Function: emitError],
     exec: [Function: exec],
     options: { context: '/mnt/Projects/nuxt/hw' },
     webpack: true,
     'thread-loader': true,
     sourceMap: false,
     target: 'web',
     minimize: undefined,
     resourceQuery: '?vue&type=style&index=0&lang=css&',
     context: '/mnt/Projects/nuxt/hw/.nuxt/components',
     loaderIndex: 0,
     loaders: [ [Object], [Object], [Object], [Object], [Object] ],
     resourcePath: '/mnt/Projects/nuxt/hw/.nuxt/components/nuxt-error.vue',
     async: [Function: async],
     callback: [Function],
     cacheable: [Function: cacheable],
     addDependency: [Function: addDependency],
     dependency: [Function: addDependency],
     addContextDependency: [Function: addContextDependency],
     getDependencies: [Function: getDependencies],
     getContextDependencies: [Function: getContextDependencies],
```
Then obviously `typeof query.publicPath` is going to be `undefined`
