### ISSUE TITLE
why my input type="text" broken?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#497]
Very strange bug. 

Demo - http://normal-minute.surge.sh/
Recreate:

1. Go to Page One. Username input is ok
2. Refresh page. Username input is broken, nuxt take of type="text" attribute.

What the hack is that?

The worst part - this bug appears only after `npm run generate`, so it is IMPOSSIBLE to trace in development. 

Is it because I import this Form from my Form.vue Component to Page One? How to use Components without this bugs? I have the same issue with Google Map few days ago. There was not working when I use them as Components, but work when I just insert Map directly in page. What I can use as components and what I can't?

**Comment by ausir0726** [comment]
hi ,

that because html-minify setting .
you can try on this site ( nuxt.js used )
https://kangax.github.io/html-minifier/

`type="text"` will be remove .

because default that is not necessary .
you can ..

option 1 .
defined your css with `class` 

option 2 .
override html-minify setting , escape remove `type="text"`

**Comment by kodekrendel** [comment]
@ausir0726 thank you! That's make sense.

**Comment by kodekrendel** [comment]
@ausir0726 as for option 2. Can I override just `type="text"` without disabling whole html minify?

**Comment by kodekrendel** [comment]
And where should I edit `minify: {}`? In `nuxt.config.js`?

**Comment by ausir0726** [comment]
@kodekrendel 
maybe try disabled some minify setting will be better ? 
I don't know it can be disable all option . usually I don't have these issue 😆 

in `nuxt.config.js` add
```js
module.exports = {
  // add this generate object
  generate : {
    minify : { 
       //options in here
    }
  },
  // same as old file 
  // ... bula bula ...
}
```

As for form after google map , I can't answer you .

**Comment by kodekrendel** [comment]
@ausir0726 thanks a lot! That's solve my issue

```
  generate: {
    minify: {
      removeRedundantAttributes: false
    }
  }
```
