### ISSUE TITLE
URI malformed

### ISSUE THREAD

**Issue by phof** [nuxt/nuxt.js#4977]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://nuxtjs.org/%c1%81](https://nuxtjs.org/%c1%81)

### Steps to reproduce

1) Load https://nuxtjs.org/%c1%81
2) See console error

### What is expected ?

Trigger 404/500 errors

### What is actually happening?

Execution stops

### Additional comments?

(node:87717) UnhandledPromiseRejectionWarning: URIError: URI malformed
    at decodeURI (<anonymous>)
    at nuxtMiddleware (node_modules/@nuxt/server/dist/server.js:120:15)

Perhaps the decodeURI should be wrapped in the try {} block?
https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/middleware/nuxt.js#L10

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8619">#c8619</a>)</em></sub></div>

**Comment by simonbrent** [comment]
This doesn't look like it's resolved any more - if I go to https://nuxtjs.org/%c1%81 now I see the loading spinner forever, rather than an error page

**Comment by pi0** [comment]
Hi @simonbrent. nuxtjs.org is using using static target. This issue/fix is for server. Would you please create a new issue with codesandbox reproduction?

**Comment by simonbrent** [comment]
Ok (I'm definitely seeing it in a project using nuxt 2.12.2)
