### ISSUE TITLE
Mismatching childNodes vs. VNodes warning.

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#498]
I am trying to layout on one page Google Map and simple HTML form.

When I insert only Map everything works:

```
<template lang="html">
  <section class="viewport content">
    <twitter-head-card></twitter-head-card>
    <open-graph></open-graph>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h2>Test</h2>
        </div>
      </div>
    </div>
    <gmap-map
      :center="{lat:50, lng:30}"
      :zoom="7"
      map-type-id="terrain"
      style="width: auto; height: 300px"
    ></gmap-map>

  </section>
</template>
```

![screenshot from 2017-04-02 14-43-08](https://cloud.githubusercontent.com/assets/26049747/24590016/dedd02d4-17b2-11e7-82ee-c02c9d3800be.png)

But when I add Form under Map, whole page is broken:

```
    <form>
      <input type="text" name="" value="">
    </form>
```
![screenshot from 2017-04-02 14-46-42](https://cloud.githubusercontent.com/assets/26049747/24590040/4cbe6f04-17b3-11e7-8d99-b1713612b3c6.png)

**Comment by kodekrendel** [comment]
OK, by messing around with code I was fortunate to solve this mistery :smile: 

You must you wrapper divs, example:

```
<template lang="html">
  <section class="viewport content">
    <twitter-head-card></twitter-head-card>
    <open-graph></open-graph>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h2>Test</h2>
        </div>
      </div>
    </div>
    <div>
      <gmap-map
       :center="{lat:50, lng:30}"
       :zoom="7"
       map-type-id="terrain"
       style="width: auto; height: 300px"
      ></gmap-map>
    </div>
  </section>
</template>
```

**Comment by nizulzaim** [comment]
It should not mark as close.. This error mean something wrong with nuxt package. i wasted my 2 days to find what exactly the problem when trying to use plugin with nuxtjs. And yeah you are right. wrap it with div fix this issue but it is not good solution for me. I will have extra tag to use UI plugin which is make me need to consider using nuxtjs for now.

**Comment by kodekrendel** [comment]
@nizulzaim it plugins, not Nuxt. they render some conflict html, since I understand the problem. It's something related with Vue SSR process. So basicaly this plugins are poorly work with SSR, that's it. Still, we can use some hacks to make them work.
