### ISSUE TITLE
Vue Packages version mismatch after upgrading to 2.4.3

### ISSUE THREAD

**Issue by papakay** [nuxt/nuxt.js#4987]
FATAL                                                                                                               

Vue packages version mismatch:

- vue@2.5.22
- vue-server-renderer@2.6.3

This may cause things to work incorrectly. Make sure to use the same version for both.

**Comment by mauxtin** [comment]
Try to delete the node_modules folder and the lock and reinstall.
`rm -rf ./node_modules yarn.lock && yarn install `

**Comment by papakay** [comment]
Thanks it worked.
