### ISSUE TITLE
CommonJS module (using `module.exports`) + string.split() ==> Cannot assign to read only property 'exports' of object '#<;Object>'

### ISSUE THREAD

**Issue by akhoury** [nuxt/nuxt.js#4989]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/ml66336kp](https://codesandbox.io/s/ml66336kp)

### Steps to reproduce

Open the dev console to see the Error

### What is expected ?

No error

### What is actually happening?

This is really weird, if I comment out this line in 

api-backend-folder/utils/common.js:13

which is just `return filename.split(".").pop();` no error,
really, if I just remove the `split()` call, I __don't__ see an error 

![Screen Shot 2019-02-08 at 7.23.52 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/f1e22740-2bc6-11e9-b01f-7d518abd84fa.png)

### Additional comments?

I know it's related to using a CommonJS module, as you can notice, `api-backend-folder/utils/common.js` is one, but I need to use this on the server as well, also, this works fine if i just comment out one line? doesn't make a lot of sense to me.

* might be related to https://github.com/nuxt/nuxt.js/issues/3204 but I dont have any references to JSON or to Object :/
* also related to https://cmty.app/nuxt/nuxt.js/issues/c747 but this doesn't really solve the issue, i really don't want to use babel-node

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8627">#c8627</a>)</em></sub></div>

**Comment by akhoury** [comment]
it also happens in `2.4.3`

**Comment by manniL** [comment]
Further read: https://github.com/webpack/webpack/issues/4039, https://twitter.com/adamwathan/status/968652732167995392

Possible solutions:

* Use `node -r esm` for your server to support `ESM` syntax and change the module exports
**or**
* Rewrite the file to ESM syntax (import) and transpile it with babel to CJS syntax (require) (similar to https://github.com/nuxt/nuxt.js/issues/874#issuecomment-308086772)

THere is no better way out of that I suppose :slightly_frowning_face:

**Comment by akhoury** [comment]
@manniL thanks, `node -r esm` def saved the day. I've read through both those links you shared before i filed this ticket, what didn't make sense to me is that i was able to mix `import` and `require` sometimes, but others i can't, depending on some specific lines of code.

Ideally, I was hoping to get to the bottom of this, but `node -r esm` is a quick remedy for now
