### ISSUE TITLE
nuxt-ts ignores srcDir

### ISSUE THREAD

**Issue by ozum** [nuxt/nuxt.js#4993]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/5pp2yx8wx](https://codesandbox.io/s/5pp2yx8wx)

### Steps to reproduce

1. Create a nuxt app using `$ npx create-nuxt-app <project-name>`
2. Create `src` directory using `mkdir src`.
3. Add  `srcDir: "src/"` to `nuxt.config.ts`
4. Move related dirs (pages, components etc.) into `src` dir.

### What is expected ?

Application to start and run without errors.

### What is actually happening?

Application does not run and got warning:

WARN  No `pages` directory found in /sandbox. Using the default built-in page.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8630">#c8630</a>)</em></sub></div>

**Comment by manniL** [comment]
Works fine for me with a `nuxt.config.ts` instead of a `nuxt.config.js`.

**Comment by kevinmarrec** [comment]
`nuxt` default config file is `nuxt.config.js` & `nuxt-ts` default config file is `nuxt.config.ts`.

You need to explictly tell to the CLI you want to use a `nuxt.config.js` if you're using `nuxt-ts`.

@mannil I don't know what's the best way to go, but I highly recommend people sticking with `nuxt.config.ts` as there will be typecheck/autocompletion in configuration soon through this file.

**Comment by manniL** [comment]
@kevinmarrec In this case, we *should* provide some kind of hint/warning/notice when no nuxt.config.ts was found but a nuxt.config.js :relaxed:

**Comment by kevinmarrec** [comment]
@manniL Yes

**Comment by ozum** [comment]
Thanks for the replies.

I created my app using `nuxt-create-app`, uninstalled `nuxt` and installed `nuxt-ts`. I missed `nuxt.config.ts` part.

Is there a guide / tutorial / doc how to start a `nuxt-ts` project and differences between `nuxt` and `nuxt-ts` projects.

Kind regards,

**Comment by kevinmarrec** [comment]
@ozum TypeScript documentation is in progress, but for now the easiest way to get started is probably the 2 TypeScript examples in the `examples` directory of the main `nuxt` repo.

You can also probably find some answers on our Discord `typescript` help channel :)

**Comment by ozum** [comment]
Thanks for the tips.

**Comment by shalldie** [comment]
I missed the `nuxt.config.ts` also, thx ~
