### ISSUE TITLE
404 error on /dist/*.js files after rebuild nuxt (SSR mode)

### ISSUE THREAD

**Issue by siberiadev** [nuxt/nuxt.js#4999]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://test](https://test)

### Steps to reproduce

npm run build

### What is expected ?

Client can access all files of the project

### What is actually happening?

Every time when we rebuild our project on server we got same problem with some of JS files. Actually all files are available in dist/client. But somehow nuxt can't find it. Then after 3-5 hours it comes in normal condition. Maybe it has any cache features I don't?
Thanx for help.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8637">#c8637</a>)</em></sub></div>

**Comment by siberiadev** [comment]
//MY NUXT CONFIG
const webpack = require('webpack');
const axios = require('axios');
module.exports = {
  mode: 'universal',
  head: {
    title: 'KUKKU.RU - маркетплейс нашего города.',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'csrf-token', content: ''},
      { hid: 'description', name: 'description', content: 'KUKKU.RU' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
    ],
    script: [
      
    ],
  },
  css: [
    'element-ui/lib/theme-chalk/index.css',
    '~/assets/scss/styles.scss',
    'swiper/dist/css/swiper.css',
  ],
  plugins: [
    '~/plugins/element-ui',
    '~/plugins/lodash.js',
    '~/plugins/the-mask.js',
    '~/plugins/global.js',
    '~/plugins/vue-jsonp.js',
    { src: '~/plugins/chat-scroll.js', ssr: false },
    { src: '~/plugins/swiper.js', ssr: false },
    { src: '~/plugins/cropper.js', ssr: false },
    { src: '~/plugins/vue-lazyload.js', ssr: false},
    { src: '~/plugins/mixins/no-ssr.js', ssr: false },
    '~/plugins/mixins/filters.js',
    '~/plugins/mixins/directives.js',
    '~/plugins/mixins/ssr.js',
    '~/plugins/mixins/user.js',
  ],
  modules: [
    ['@nuxtjs/style-resources'],
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    'cookie-universal-nuxt',
    'nuxt-user-agent',
    [
      '@nuxtjs/yandex-metrika',
      {
        id: 51314254,
        clickmap: true,
        trackLinks: true,
        accurateTrackBounce: true,
        webvisor: true
      }
    ],
  ],
  styleResources: {
    scss: [
      './assets/scss/global.scss'
      ]
  },
  
  axios: {
    debug: false,
    baseURL: 'https://testtstst.ru/api',
    headers: {},
  },
  auth: {
    strategies: {
      local: {
        endpoints: {
          login: { url: 'login', method: 'post', propertyName: 'access_token' },
          user: { url: 'user', method: 'post', propertyName: 'data' },
          logout: { url: 'logout', method: 'post' }
        }
      }
    },
    redirect: {
      login: '/login',
      logout: '/',
      home: '/',
      callback: '/'
    },
    watchLoggedIn: true,
    fullPathRedirect: true,
  },

 loading: { 
    color: '#67c23a',
    background: 'white',
    height: '4px'
  },
  loadingIndicator: {
    name: 'chasing-dots',
    color: '#9E9E9E',
    background: '#ffffff'
  },

  build: {
    analyze: false,
    vendor: [
        'axios',
        'element-ui',
        'vue-cropperjs',
    ],
    plugins: [
      new webpack.ProvidePlugin({
        '_': 'lodash',
      })
    ],
    extend (config, { isDev }) {
      if (isDev && process.client) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: ['eslint-loader'],
          exclude: /(node_modules)/
        })
      }
    }
  }
}

**Comment by manniL** [comment]
This highly depends on your setup. By default, all files are accessible after the build and start process. Maybe a CDN that caches the files might help? :thinking: 

However, this isn't a Nuxt issue and hard to debug without further information, your setup or even access to the servers.
