### ISSUE TITLE
Vue router and vue2-vreadcrumbs

### ISSUE THREAD

**Issue by believe2013** [nuxt/nuxt.js#500]
How to implement 'breadcrumbs' in nuxt.js c using the vue2-breadcrumbs package? 
Or another implementation.

**Comment by alexchopin** [comment]
Hi, you cannot use `vue-router` meta with nuxt as vue2-breadcrumbs seems to use. The best solution is to use the store and/or a middleware to do the same as vue2-breadcrumbs.

**Comment by Alex-Sokolov** [comment]
@alexchopin but how to do it? Now in `$route.matched` always only one item - current route. Will be any updates in incoming 1.0 release?
