### ISSUE TITLE
Syntax errors when supplying external function to scrollBehavior key in nuxt.config.js router config

### ISSUE THREAD

**Issue by aaronransley** [nuxt/nuxt.js#5001]
### Version

[v2.7.1](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

* CodeSandbox<br>https://codesandbox.io/s/84n4511202?fontsize=14

### Steps to reproduce

**nuxt.config.js**

```js
import { scrollBehavior } from './lib/route-utils'

module.exports = {
  // ...
  router: {
    scrollBehavior
  }
  // ...
}
```

**lib/route-utils.js**

```js
export function scrollBehavior(to, from, savedPos) {
  // ...
}
```

**When running `nuxt dev`**

```js
ERROR  Failed to compile with 1 errors
ERROR  in ./.nuxt/router.js  friendly-errors 22:51:54
Syntax Error: Unexpected token, expected "(" (34:32)
  32 | Vue.use(Router)
  33 | 
> 34 | const scrollBehavior = function function (to, from, savedPos) {
     |                                 ^
  35 |   const isEqual = require('lodash').isEqual
  36 |   let scrollTo = { x: 0, y: 0 }
  37 |
```

### What is expected ?

Ability to use external functions as scrollBehavior handler

### What is actually happening?

Syntax errors listed in steps to repro

### Additional comments?

I have updated to Nuxt v2.7.1 and continue to receive errors when attempting to import my `scrollBehavior` function from an external module.

I tried a `yarn upgrade nuxt`, tried manually incrementing the version in `package.json`, verified the newest Nuxt is installed, and even deleted my node_modules folder & reinstalled.

Not certain that #4884 was fully resolved with in PR #4916

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8638">#c8638</a>)</em></sub></div>

**Comment by aaronransley** [comment]
Added a proper CodeSandbox reproduction using the official template w/ nuxt @ v2.4.5.

https://codesandbox.io/s/84n4511202?fontsize=14

**Comment by gijsroge** [comment]
I don't have much to add other then the fact that I also have the same issue. For what it's worth, I can confirm that the provided sandbox shows the issue very clearly. Not sure whats going on here :/

Thanks for reporting @aaronransley

**Comment by Anaphase** [comment]
This appears to still be happening in 2.8.1 (or reintroduced somewhere in between?)

**Comment by galvez** [comment]
@Anaphase can you provide an example that fails for you?

**Comment by Anaphase** [comment]
Well all I did was add the following to my router config in `nuxt.config.js`:

### After
```javascript
router: {
  scrollBehavior(to, from, savedPosition) {
    console.log(to)
    return { x: 0, y: 0 }
  },
},
```

After tinkering with it a bit, it appears that the syntax errors only happen when I try to use any of the parameters:

![Screen Shot 2019-07-03 at 3 24 22 PM](https://user-images.githubusercontent.com/2358694/60623033-556fcb80-9da7-11e9-80e0-d08fdda05a04.png)

For whatever reason, webpack (or something?) is adding some weird stuff (`_666.g.`) at the start of any line that uses a function parameter (and not just `console.log()` statements.)

**Comment by galvez** [comment]
thanks @Anaphase -- I'll see what's up.
