### ISSUE TITLE
save state on server side

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#501]
Hi guys,
i like to save the auth state (token and user) on the server-side so that when i refresh the page i keep the user logged in?

i tried using nuxtServerInit() like that 

![image](https://cloud.githubusercontent.com/assets/19589742/24607643/b08e7440-186a-11e7-99df-d92166e3041a.png)

but when i refresh on a url that have an auth middleware, i get a redirection to login page.

**Comment by Atinux** [comment]
Hi @aymenpeak 

You need to use sessions on your server and use `req.session`.

You can use the [express](https://github.com/nuxt/express) with the session middleware: https://github.com/expressjs/session

**Comment by Atinux** [comment]
How are you using laravel with nuxt.js exactly?

**Comment by aymenpeak** [comment]
hi @Atinux 
i'm implementing a single web app for streaming videos, i get all the data using laravel api, but the user needs to be authenticated to use some features,
i managed to login and get the token from the laravel server but when i refresh i loose the data saved in nuxt store.

so is there a way to the state saved even when there is a server rendering (refresh)?
thanks for asking by the way because im really strugglin^^

**Comment by Atinux** [comment]
@aymenpeak please take a look at this example: https://github.com/nuxt/example-todomvc

Mainly to this file: https://github.com/nuxt/example-todomvc/blob/master/server.js

In this file I use the express-session middleware to keep the todos for each user, so when he refresh the page the todos are server-rendered (see demo: https://todomvc.nuxtjs.org/)

**Comment by aymenpeak** [comment]
@Atinux  yeah but my problem was that when i refresh my auth middleware redirect me before fetching the user data. So i fixed it by saving the user data in the cookies then retreive them in the req variable.
there is my middleware code 
![image](https://cloud.githubusercontent.com/assets/19589742/24745920/4102fafa-1aaf-11e7-8861-52cbfb52b841.png)

Thanks for helping :)

**Comment by aft3rlife** [comment]
@aymenpeak Could you post an example of your code somewhere? I'm struggling with this as well. I'm using Laravel too and I've seen the auth-0 example but it's not working for me

**Comment by Atinux** [comment]
@aft3rlife I don't have experience in Laravel and last time I coded in PHP was 10 years ago, but it would be awesome to see someone porting Nuxt.js to Laravel!

**Comment by aymenpeak** [comment]
@aft3rlife yeah ofc , first i get rid of some bugs then i will post it :)

**Comment by kodekrendel** [comment]
I will be happy for simple nuxt server authorization, without Auth0 (and Laravel) as well.
