### ISSUE TITLE
Starter is read only

### ISSUE THREAD

**Issue by gustawdaniel** [nuxt/nuxt.js#5010]
I mean:

> https://github.com/nuxt-community/starter-template/issues/80

This repository has been archived by the owner. It is now read-only.

And I do not know if should I start by:

```
vue init nuxt-community/starter-template my-project  
```

or by

```
npx create-nuxt-app <project-name>
```

which docs is official?

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/52628518-c3c2f880-2eaf-11e9-80f8-1602c167a642.png)
