### ISSUE TITLE
Module build failed buble.js, templateLoader.js, Parser.pp$4.raise 

### ISSUE THREAD

**Issue by siberiadev** [nuxt/nuxt.js#5022]
This is not an issue, it's just a big problem, wich I can't resolve by my self. So maybe someone can help me.
When I run dev my nuxt app in ssr mode it give me an error below:

`Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js): SyntaxError: Unexpected token (1:239) at Parser.pp$4.raise (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:2610:13) at Parser.pp.unexpected (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:637:8) at Parser.pp$3.parseParenAndDistinguishExpression (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:2154:49) at Parser.pp$3.parseExprAtom (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:2061:41) at Parser.parseExprAtom (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:4372:24) at Parser.pp$3.parseExprSubscripts (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1955:19) at Parser.pp$3.parseMaybeUnary (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1932:17) at Parser.pp$3.parseExprOps (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1874:19) at Parser.pp$3.parseMaybeConditional (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1857:19) at Parser.pp$3.parseMaybeAssign (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1832:19) at Parser.pp$3.parseMaybeConditional (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1862:28) at Parser.pp$3.parseMaybeAssign (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1832:19) at Parser.pp$3.parseParenAndDistinguishExpression (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:2139:30) at Parser.pp$3.parseExprAtom (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:2061:41) at Parser.parseExprAtom (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:4372:24) at Parser.pp$3.parseExprSubscripts (e:\OSPanel\domains\webfolder\node_modules\vue-template-es2015-compiler\buble.js:1955:19)`

It's also says that my problem in node_modules\vue-template-es2015-compiler\buble.js

When I run dev in spa mode all is good.
Can my .webp extension file effect it?

I checked whole google and nothing can help me.

**Comment by siberiadev** [comment]
What I already done:
1. Check my all js files for any errors
2. Rebuild all node_modules
3. Check google.com for this type of error

**Comment by siberiadev** [comment]
Comand line says after complete compilation^

√ Client
  Compiled successfully in 4.26s

× Server
  Compiled with some errors in 4.62s

**Comment by siberiadev** [comment]
Anyone please

**Comment by hacklover** [comment]
It happened just now to me,
I found out it was an empty <template></template> block.

Panic :|

**Comment by hacklover** [comment]
It happened just now to me,
I found out it was an empty <template></template> block.

Panic :|

**Comment by hacklover** [comment]
It happened just now to me,
I found out it was an empty `<template></template>` block.

Panic :|

**Comment by 2079130211** [comment]
if you are useing vue js 
 v-modal is empty some where 
ex like this v-model="" ,
it should be v-model="property name "

**Comment by nagman** [comment]
For me, it was using optional chaining inside a `<template>`:
```vue
<template>
  <img :src="image?.src" :alt="image?.alt" />
</template>
```
I simply fixed it with a `v-if`:
```vue
<template>
  <img v-if="image" :src="image.src" :alt="image.alt" />
</template>
```

**Comment by mivd7** [comment]
> For me, it was using optional chaining inside a `<template>`:
> 
> ```
> <template>
>   <img :src="image?.src" :alt="image?.alt" />
> </template>
> ```
> 
> I simply fixed it with a `v-if`:
> 
> ```
> <template>
>   <img v-if="image" :src="image.src" :alt="image.alt" />
> </template>
> ```

So this means nuxt doesn't support optional chaining?

**Comment by AmirKakDela** [comment]
I had the same problem because of  "??" expression
