### ISSUE TITLE
@nuxt/babel-preset-app ignores .browserlistrc

### ISSUE THREAD

**Issue by williamchong007** [nuxt/nuxt.js#5026]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/qqwx3175kq](https://codesandbox.io/s/qqwx3175kq)

### Steps to reproduce

create file `.browserslistrc` with valid browserlist query, say `ie 11`

in nuxt.config.js enable babel debug mode
```
      presets: ({ isServer }) => [
        [
          '@nuxt/babel-preset-app',
          {
            debug: true,
          },
        ],
      ],
``` 
to observe babel config

### What is expected ?

babel runs with target "ie 11"

### What is actually happening?

babel run with default config "ie 9"

### Additional comments?

https://github.com/nuxt/nuxt.js/blob/dev/packages/babel-preset-app/src/index.js#L53
probably due to "ie 9" would be used when target is not defined, despite browserlist exists

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8653">#c8653</a>)</em></sub></div>

**Comment by manniL** [comment]
Not sure whether it's intended to respect the a `.browserlistrc` or not.
🤔 

cc @clarkdo

**Comment by clarkdo** [comment]
@williamchong007 
Since nuxt will set `ie9`(client) and `node: current`(server) as default targets, so if you want to use `browserlist`, please try:

Note: `.browserslistrc` under `configPath`

```js
  build: {
    babel: {
      presets: ({ isServer }) => {
        return [[
          '@nuxt/babel-preset-app',
          {
            targets: isServer ? { node: 'current' } : {},
            configPath: __dirname
          }
        ]]
      }
    }
  }
```

**Comment by williamchong007** [comment]
Thanks for the reply
Should I treat this as a temp fix or a long term solution?

**Comment by clarkdo** [comment]
@williamchong007 

Now, You can use it for sure, and I'll just close this issue 😄 

About some more appropriate solution, I'll think about it, if you have any suggestions, feel free to comment here.
