### ISSUE TITLE
How to run a script every time page is loaded?

### ISSUE THREAD

**Issue by abh153k** [nuxt/nuxt.js#5029]
My client sent me an HTML template that heavily relies on jQuery. The app itself runs on nuxt. I have a js file that contains a whole lot of `$(function(){...})`. Now I don't know how to run this file on each page transition.

So far, I have tried:

 1. Creating a `plugin` inside `plugins` dir that looks like:
```
 export default async ({ app }) => {

     app.router.afterEach((to, from) => {
         require('~/static/js/base-init.js');
     })
 }
```
here `base-init.js` has all those jquery code

  2. Adding `mounted` (inside `default.vue` layout) but that doesn't work either.

Does anyone have a clue?

**Comment by joecutter** [comment]
@avks hello did you find the solution to this? having similar issues

**Comment by avks** [comment]
@joecutter see [here](https://www.encode8.com/js/guide-to-integrate-jquery-in-nuxt/)
