### ISSUE TITLE
Middleware for a specific page not working. 

### ISSUE THREAD

**Issue by tenjojeremy** [nuxt/nuxt.js#503]
Hi,

MIddleware does not work when I do the following:
![example](https://cloud.githubusercontent.com/assets/25231946/24617978/89afce8e-1863-11e7-8b0d-0113e893f578.PNG)

Moreover when I add the midleware to the nuxt.config.js file as shown in the docs. the app brakes.

Thank you in advance.

**Comment by Atinux** [comment]
Hi @tenjojeremy 

Where is located your `fixtures.vue`  file?

**Comment by tenjojeremy** [comment]
@Atinux 

It is located inside the components folder.

Oh, so middleware only works on files under pages?

**Comment by Atinux** [comment]
Yes, only for pages components.

**Comment by tenjojeremy** [comment]
Got it.

Thank you! @Atinux
