### ISSUE TITLE
localIdentName didn't change in scss

### ISSUE THREAD

**Issue by kamontat** [nuxt/nuxt.js#5030]
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://gitlab.com/kcnt/resume](https://gitlab.com/kcnt/resume)

### Steps to reproduce

1. Add custom css module name `loaders.cssModules.localIdentName = '__custom_[name]_[local]'` in extend method in nuxt.config.js
2. Get module rules configuration
```js
const index = config.module.rules.findIndex(v =>
    v.test.toString().includes('scss')
)
const scssRule = config.module.rules[index]
```
3. Look in `scssRule.oneOf[0].use[1].options.localIdentName` configuration (you can use console.log)
4. This log will happen several times, but the first one `localIdentName` will be the default which is "[local]_[hash:base64:5]"
5. Another log will be correct, BUT I think css already generated on the first time nuxt.config.js been run

### What is expected ?

output class should be `__custom_index_header2`

### What is actually happening?

actually output class is `index_XXXXXX`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8655">#c8655</a>)</em></sub></div>

**Comment by kamontat** [comment]
??

**Comment by kamontat** [comment]
??

**Comment by thenickname** [comment]
So if you still care for a solution, here is the brute force way. The code basically finds all occurences of localIdentName and changes them all. The **problem** with this approach is, however, every time the nuxt team decides to change its internal config, the code will break. And it did change in the past, without warning. Hence the try/catch. So at least you will see a useful error message in the future.

```js
try {
    // find all rules that contain "oneOf"
    const rulesWithOneOf = config.module.rules.filter( rule => rule.oneOf )

    // extract all "oneOf" arrays
    const oneOfArrs = rulesWithOneOf.reduce( ( result, { oneOf } ) => [
        ...result,
        ...oneOf
    ], [] )

    const optionsWithLocalIdentName = oneOfArrs
        // get array of "use" objects
        .reduce( ( result, { use } ) => [
            ...result,
            ...use
        ], [] )
        // extract "options" from "use" objects
        .map( ( { options } ) => options )
        // keep only those that contain localIdentName
        .filter( opt => opt && opt.localIdentName )

    // change localIdentName
    optionsWithLocalIdentName.forEach( ( opt ) => {
        // eslint-disable-next-line no-param-reassign
        opt.localIdentName = '[name]__[local]__[hash:base64:5]'
    } )

    if( optionsWithLocalIdentName.length === 0 ) {
        throw new Error( 'Could not change localIdentName settings' )
    }
} catch( e ) {
    // eslint-disable-next-line no-console
    console.error( 'Well, the nuxt config changed again and your code broke.', e )
}
```

**Comment by khashayarghajar** [comment]
same
