### ISSUE TITLE
include nestJS as supported backend framework

### ISSUE THREAD

**Issue by cocodrino** [nuxt/nuxt.js#5034]
### What problem does this feature solve?

now that typescript is supported would be great if we would build a full typescript apps (frontend and backend) with nuxtjs and nestjs, which seems the most promising and used framework for typescript

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8660">#c8660</a>)</em></sub></div>

**Comment by manniL** [comment]
You can already use NestJS + Nuxt.js by separating both instances. That's also the recommended way (IMO). See https://blog.lichter.io/posts/my-take-on-using-nuxt-with-an-api

Using it "under the hood" (instead of connect) probably won't happen.

**Comment by begueradj** [comment]
Then why all those Node.js backend options in the Nuxt.js starter template? They mislead me in the beginning. IMO they should be removed from the installation process

**Comment by manniL** [comment]
@begueradj This is indeed planned.

**Comment by jackbravo** [comment]
Maybe it could make sense with some of them? Featherjs for example, can also be used on the frontend, so using it under the hood and also on the frontend could be a good idea. Is it also going to be removed?
