### ISSUE TITLE
Integration vue-apollo

### ISSUE THREAD

**Issue by jvbianchi** [nuxt/nuxt.js#504]
The new version of vue-apollo (https://github.com/Akryum/vue-apollo#create-a-provider) needs to set up a provider:
```js
const apolloProvider = new VueApollo({
  defaultClient: apolloClient,
})

new Vue({
  el: '#app',
  apolloProvider, // <---- provider
  render: h => h(App),
})
```
How can I do this using nuxt?

**Comment by jvbianchi** [comment]
From what I saw in your documentation today this is not possible. Right?

**Comment by evseevnn** [comment]
Hi @jvbianchi 
You can use [lokka](https://github.com/kadirahq/lokka)
i'm already used it with vue + ssr. I think setup it will easy.
Your will need create file where you should describe your GraphQL api, and after your can link this with nuxt via plugin.

**Comment by dohomi** [comment]
@jvbianchi I am adding the provider of vue-apollo currently in a global Vue.mixin and works like this:
```

**Comment by stursby** [comment]
@jvbianchi I just submitted an example with `apollo-client` #553.

**Comment by jvbianchi** [comment]
@stursby That helps thanks

**Comment by Atinux** [comment]
It will be possible soon to use vue-apollo :)

**Comment by dohomi** [comment]
@Atinux it crossed my mind, if the `vue-apollo` package would expose `this.$apollo.query`, then users could use that approach inside of the `asyncData` and it would be ready to use?

**Comment by Atinux** [comment]
I am working with the creator of vue-apollo to find a way of doing it.

**Comment by jvbianchi** [comment]
Using this example: [vue-apollo](https://github.com/nuxt/nuxt.js/blob/master/examples/vue-apollo/middleware/apollo.js)

I'm getting this error:
```
TypeError: Cannot read property '_ready' of undefined
```

**Comment by dohomi** [comment]
@Atinux I was looking at the `vue-apollo` example as well. Two questions so far:
- its really necessary to use a server.js? 
- I don't find see where you inject the `initialState` based on this whitepaper: https://github.com/Akryum/vue-apollo/blob/master/ssr.js

I know its WIP just wanted to chip in and ask if there is anything I could try further

**Comment by dohomi** [comment]
@jvbianchi if you disable the middleware at nuxt.config.js at least you won't have this error any longer. Thus the initial state still won't work correctly but the data will be fetched again

**Comment by tillkolter** [comment]
@Atinux I am currently trying to migrate my Non-Nuxt project (which uses vue-apollo) to Nuxt. I used your example to migrate it, but it seems that I am missing something and I think the provided example is missing something. The apollo middleware method fires every time the call to render is being made, but the result of `apolloClient.collect` is empty. I expected it to contain all apollo queries along the rendering path. Instead, the apollo queries are being executed after the page has been mounted, just like in the Non-Nuxt version. The expected file pages/cars/_id.vue also does not exist.

Unfortunately the white paper referenced in the original SSR example in https://github.com/Akryum/vue-apollo#server-side-rendering also lacks information about the actual rendering and how the __APOLLO_STATE__ is added to the response and I could make my way through the Nuxt implementation to see how to extend the rendering part myself.

The apollo client example https://github.com/nuxt/nuxt.js/tree/master/examples/with-apollo works fine, so I could restructure my code to use plain apollo-client instead of the convenient wrapper vue-apollo, but I would like to avoid restructuring this part of my app.

**Comment by Akryum** [comment]
Work is being done to make vue-apollo more SSR friendly and to make the integration with nuxt easier.

**Comment by tillkolter** [comment]
@akryum Sounds great. Can you estimate how much time it will take until a beta/alpha is ready? I am coming closer to a deadline and I would use the working apollo-client version otherwise and rebuild the vue-apollo part later then. Sorry for pushing :)

**Comment by rnenjoy** [comment]
Wow!! Can't wait!

**Comment by dohomi** [comment]
@Atinux are there any news on this issue? After the release of beta.7 of `vue-apollo` is there another way of making the implementation right? I still struggle to set the `initialState` right. Thanks

**Comment by dohomi** [comment]
@jvbianchi did you find a proper way using vue-apollo yet?

**Comment by jvbianchi** [comment]
just this one: https://github.com/nuxt/nuxt.js/blob/master/examples/vue-apollo/README.md

**Comment by dohomi** [comment]
thanks I've seen that one but there is no info yet

**Comment by Atinux** [comment]
Will try to make the example work soon.

**Comment by RSchwan** [comment]
Any news on this? I really want to use graphql and nuxt together but I can't get it working.

**Comment by tillkolter** [comment]
I could get it running either and ended up using the vanilla apollo client example instead.

**Comment by dohomi** [comment]
Anybody here had success with adding websocket subscription with apollo client?

**Comment by frankspin89** [comment]
@Atinux is there any progress. Really looking forward for a example.

**Comment by BjornMelgaard** [comment]
looking too for example with vue-apollo's `prefetch` and `initialState`, any news? :smile:

**Comment by pi0** [comment]
(Copied from #1088 - Error with with-apollo example)

```
Nuxt.js Error:

TypeError: Cannot read property 'collect' of undefined
    at _callee$ (middleware/apollo.js:3:39)
    at tryCatch (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
    at server-bundle.js:246:14
    at F (F:\dev\nuxt\vue-apollo\node_modules\core-js\library\modules\_export.js:35:28)
    at server-bundle.js:225:12
    at server-bundle.js:1655:18
    at promisify (.nuxt/utils.js:117:14)
    at middlewareSeries (.nuxt/utils.js:97:9)
    at Object._callee$ (.nuxt/server.js:80:27)
    at tryCatch (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
```

**Comment by pi0** [comment]
An update: Sorry everyone for the delay for this integration, we are really intereste in Official Apollo + Nuxt too. But resources including time is limited and currently preparing Docs for sooner 1.x release is a high priority. Then we can even have an official one liner Integration using new Modular system.

**Comment by Nainterceptor** [comment]
Hi guys,

Just submitted a PR, with a working sample, but may be not the right way.
Comments are welcome.

**Comment by Atinux** [comment]
I worked with Akryum (author of vue-apollo), and the example has been updated and fully working: https://github.com/nuxt/nuxt.js/tree/dev/examples/vue-apollo

**Comment by evseevnn** [comment]
@Atinux respect

**Comment by BjornMelgaard** [comment]
From me too, to all team :+1: :100:

**Comment by ImTheDeveloper** [comment]
Seems to not be working for me:

```
This dependency was not found:

* ~/apollo/queries/allCars in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?typ
e=script&index=0!./pages/graph.vue

To install it, you can run: npm install --save ~/apollo/queries/allCars
```

**Comment by Atinux** [comment]
@ImTheDeveloper The `dev` branch is correct, the example is working fine on my end, try to use the last version of Nuxt.js

**Comment by ImTheDeveloper** [comment]
@Atinux Yep you're right I needed to get into nuxt@next. There were some issues around fetch which I've mentioned here: 

https://github.com/nuxt/nuxt.js/issues/1305#issuecomment-321191503
