### ISSUE TITLE
[Help] How to use dynamic CSS files with Nuxt?

### ISSUE THREAD

**Issue by FabioZanchi** [nuxt/nuxt.js#5040]
I'm working in a project that have different users with their logos. Based on the API call I want to load a different CSS with different colour palette.

Now I have a css folder inside assets folder with main.js (with my custom font styles, etc) and another files in there for the custom color palette: <color-name>-palette.css.

In my nuxt.config I'm calling the CSS colour like that:

  `css: [
    ' ~/assets/style/app.styl ',
    ' ~/assets/css/main.css ',
    ' ~/assets/css/orange-palette.css '
  ],`

Is there any way to bind the CSS file depending on the URL path/API call instead of putting the path there?

I'm not sure if I can use it on templates as well, binding the CSS files in there. Is it possible?

Thanks

**Comment by bdrtsky** [comment]
Isn't it's just simpler to use CSS variables or add theme classes to body? \
