### ISSUE TITLE
ERROR head_attrs is not defined

### ISSUE THREAD

**Issue by fewiki** [nuxt/nuxt.js#5046]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/nuxt/nuxt.js/search?q=head_attrs&unscoped_q=head_attrs](https://github.com/nuxt/nuxt.js/search?q=head_attrs&unscoped_q=head_attrs)

### Steps to reproduce

After update to version 2.4.3，when render report error head_attrs is not defined

### What is expected ?

Is this commit fixed?

https://github.com/nuxt/nuxt.js/search?q=head_attrs&unscoped_q=head_attrs

### What is actually happening?

Is this commit fixed?

https://github.com/nuxt/nuxt.js/search?q=head_attrs&unscoped_q=head_attrs

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8669">#c8669</a>)</em></sub></div>

**Comment by manniL** [comment]
Please provide a reproduction repository or codesandbox (https://template.nuxtjs.org)

**Comment by weilaihui** [comment]
npm install 使用的nuxt版本不同导致，最新版本在index.ssr.index中使用 {{ HEAD_ATTRS }} ，而之前的版本没有，使用 npm install --package-lock-only 可能能解决
