### ISSUE TITLE
bootstrap-vue/nuxt do not load bootstrap default css as mentioned in getting started

### ISSUE THREAD

**Issue by jhalmu** [nuxt/nuxt.js#5049]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://bootstrap-vue.js.org/docs/](https://bootstrap-vue.js.org/docs/)

### Steps to reproduce

I don know

### What is expected ?

Add bootstrap-vue/nuxt to modules section of nuxt.config.js.

This will include both boostrap.css and bootstrap-vue.css default CSS.

### What is actually happening?

Have to add them to CSS section manually

### Additional comments?

Thanks

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8674">#c8674</a>)</em></sub></div>

**Comment by vadxq** [comment]
I have the same question in v2.4.3.
And I want use module and plugins to solve it.
https://nuxtjs.org/guide/modules

plugin.js

`import Vue from 'vue'
`import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm'
`
`Vue.use(BootstrapVue)


module.js
`
`import path from 'path'
`
`export default function nuxtBootstrapVue (moduleOptions) {
`  // Register `plugin.js` template
`  this.addPlugin(path.resolve(__dirname, 'plugin.js'))
`}

nuxt.config.js
`
`modules: [
`    './modules/module.js'
`  ],


I found a code very similar to the above code in node_modules/bootstrap-vue/nuxt.

**Comment by willi-dev** [comment]
i also try install nuxt with bootstrap...
but no bootstrap css loaded..

**Comment by manniL** [comment]
@jhalmu That sounds more like a bug with the nuxt module itself instead of Nuxt. Please report it there ☺️ 
Related file: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/nuxt/index.js

cc @pi0

**Comment by Javid-Izadfar** [comment]
I just opened an [issue](https://github.com/bootstrap-vue/bootstrap-vue/issues/2629) at bootstrap-vue

**Comment by solocao** [comment]
how can i do ，这就尴尬了

**Comment by sergiocamillo** [comment]
For me worked when install the bootstrap-vue like a plugin.  Like a bellow: 
For VUE CLI 3
1) Install bootstrap-vue 
npm i bootstrap-vue

2) Create a file in plugins folder -> bootstrap-vue.js
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue)

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

3) Edit nuxt.config.js.

const path = require('path')
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        'bootstrap-components': path.resolve(__dirname, 'node_modules/bootstrap-vue/es/components')
      }
    }
  },
  plugins: [
    '~/plugins/bootstrap-vue'
],
}

**Comment by sergiorivas** [comment]
I did a similar solution but without `webpack` and it works for me.
1. Install `bootstrap-vue`

```bash
npm i bootstrap-vue
```

2. Create the file `plugins/bootstrap-vue.js`

```javascript
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
Vue.use(BootstrapVue)
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

3. Add the plugin to `nuxt.config.js`

```javascript
  ...
  plugins: [
    '@/plugins/vue-bootstrap',
  ],
  ...
```

**Comment by natuanorg** [comment]
Thanks @sergiorivas ! it worked for me

**Comment by ludo1960** [comment]
Not working for me @sergiorivas

**Comment by sergiocamillo** [comment]
@ludo1960 Did you try configuring webpack ? 

For me worked when install the bootstrap-vue like a plugin. Like a bellow:
For VUE CLI 3

**Install bootstrap-vue**
`npm i bootstrap-vue`

**Create a file in plugins folder -> bootstrap-vue.js**
```
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
```

`Vue.use(BootstrapVue)`

```
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

**Edit nuxt.config.js.**
c```
onst path = require('path')
module.exports = {
configureWebpack: {
resolve: {
    alias: {
        'bootstrap-components': path.resolve(__dirname, 'node_modules/bootstrap-vue/es/components')
    }
  }
},
plugins: ['~/plugins/bootstrap-vue'],
}
```

**Comment by asapdotid** [comment]
from @sergiocamillo updated for Nuxt Js 2.9.1 (use webpack 4)

**1. Install Bootstrap-vue.**

> yarn add bootstrap-vue

**2. Create file on plugin folder for setup bootstarp-vue.**

> Example create file: `bootstrap-vue.client.js` (only client process) 

```
plugins: [,
    '~/plugins/bootstrap-vue.client',
  ],
```

> or create file: `bootstrap-vue.js` (mode client) 

```
plugins: [,
    { src: '~/plugins/bootstrap-vue', mode: 'client' }
  ],
```

**_the file_**

```
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue)

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

**3. Modify Nuxt Js Config `nuxt.config.js` for Bootstrap-vue and add alias config webpack 4**

```
export default {
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [,
    '~/plugins/bootstrap-vue.client',
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [,
    'bootstrap-vue/nuxt',
  ],
  /**
   * @var mixed bootstrapVu
   */
  bootstrapVue: {
    bootstrapCSS: false, // here you can disable automatic bootstrapCSS in case you are loading it yourself using sass
    bootstrapVueCSS: false, // CSS that is specific to bootstrapVue components can also be disabled. That way you won't load css for modules that you don't use
    componentPlugins: [], // Here you can specify which components you want to load and use
    directivePlugins: [] // Here you can specify which directives you want to load and use. Look into official docs to get a list of what's available
  },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
      if (ctx.isClient) {
        // BootstrapVue and PortalVue require access to the global Vue reference (via import Vue from 'vue').
        config.resolve.alias['vue$'] = 'vue/dist/vue.esm.js'
      }
    }
  }
}
```
