### ISSUE TITLE
Does it make sense to initialize the store in strict mode?

### ISSUE THREAD

**Issue by ndarilek** [nuxt/nuxt.js#505]
As per [this link](https://vuex.vuejs.org/en/strict.html), if your store isn't in strict mode, then inappropriate state mutations won't be caught. I have, without thinking about it, been inadvertently mutating state via v-model.

Would it make sense to default this to true in development mode, with a configuration setting to explicitly disable it if needed? It was definitely a surprise that the default setup let me do this, and it's probably a best practice to explicitly require opting out of this rather than making it opt-in.

**Comment by qm3ster** [comment]
We just need to add 
```js
storeData.strict = process.env.NODE_ENV !== 'production'
```
to [/lib/app/store.js#L53](https://github.com/nuxt/nuxt.js/blob/d576dad069b985711a0eca8d0c10c852c0cacec3/lib/app/store.js#L53) The only reason I am not making a PR is because I am not sure this is the most correct way of determining dev environment in nuxt.

**Comment by ndarilek** [comment]
That's probably sufficient, maybe AND'd with a config value for cases 
where folks don't want strict mode for some reason. I can give it a shot 
sometime soon, assuming there are no downsides.

**Comment by qm3ster** [comment]
As per link, downside is performance. The bug where it prevented dynamically adding modules has been fixed.

**Comment by Atinux** [comment]
Will be available in rc5 :)

https://github.com/nuxt/nuxt.js/commit/d9796be0bbb668fcb254379989e2e032e46bb110
