### ISSUE TITLE
Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt.js#5056]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/nuxt/nuxt.js/blob/f791d786e0996e4cad2b1ddbe244a747e7e700aa/packages/vue-app/template/client.js#L81](https://github.com/nuxt/nuxt.js/blob/f791d786e0996e4cad2b1ddbe244a747e7e700aa/packages/vue-app/template/client.js#L81)

### Steps to reproduce

Throw a error while mounting Nuxt (client)

### What is expected ?

To adjust the error message

### What is actually happening?

A new error is thrown saying: `Attempted to assign to readonly property.`

### Additional comments?

https://github.com/nuxt/nuxt.js/blob/f791d786e0996e4cad2b1ddbe244a747e7e700aa/packages/vue-app/template/client.js#L81

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8681">#c8681</a>)</em></sub></div>

**Comment by manniL** [comment]
@Timkor Feel free to submit a PR that cover the expected state

**Comment by Timkor** [comment]
This is still a problem.
![image](https://user-images.githubusercontent.com/6882876/54194584-e0594d00-44bc-11e9-8cfe-dc757222ab47.png)

The problem is that the property `message` of `DOMException` is read only. Hence it cannot be adjusted by Nuxt.
