### ISSUE TITLE
Can't get 'router.addRoutes' working from plugins

### ISSUE THREAD

**Issue by antoinerey** [nuxt/nuxt.js#5058]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/2p2jxm6k5y](https://codesandbox.io/s/2p2jxm6k5y)

### Some context

The application exposes three different routes : 

1. Home, defined like normal in the `router.js` file.
2. About, defined from a plugin.
3. Contact, defined from a plugin, with a special `options` property.

### Steps to reproduce

1. [Opening the sandbox displays the home page](https://2p2jxm6k5y.sse.codesandbox.io). Since this page is defined like any regular pages, it does work properly.
2. [Navigating to `/about`](https://2p2jxm6k5y.sse.codesandbox.io/about) shows an error page (`Cannot read property 'layout' of undefined`)
3. [Navigating to `/contact`](https://2p2jxm6k5y.sse.codesandbox.io/contact), the page is shown properly.

### What is expected ?

[Navigating to `/about`](https://2p2jxm6k5y.sse.codesandbox.io/about) or [`/contact`](https://2p2jxm6k5y.sse.codesandbox.io/contact) should work by default, and not need the `options` property.

### What is actually happening?

[Navigating to `/about`](https://2p2jxm6k5y.sse.codesandbox.io/about) shows an error page.

### Additional comments?

It does work properly by adding an empty `options` property. While not being ideal, it can be used to get around this issue.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8683">#c8683</a>)</em></sub></div>

**Comment by manniL** [comment]
Any reason you don't use a `module` or the `nuxt.config.js` to extend your routes, as it is suggested in the docs?

**Comment by antoinerey** [comment]
I may have missed this page from the documentation 😇 

Do you mean calling something like this ?

```js
export default function AboutModule () {
  this.options.router.extendRoutes = (routes, ...args) => {
    // Keep previously registered routes
    this.options.router.extendRoutes(routes, ...args)

    // Add new routes
    routes.push({
      path: '/about',
      component: {
        render: h => <h1>About</h1>
      }
    })
  }
}
```

**Comment by manniL** [comment]
It will be even easier ☺️ 

The module container has a fn built-in for that ☺️ 
Docs: https://nuxtjs.org/api/internals-module-container#extendroutes-fn-

Example:
```js
export default function AboutModule () {
  this.extendRoutes((routes) => {
    // Add new routes
    routes.push({
      path: '/about',
      component: {
        render: h => <h1>About</h1>
      }
    })
  })
}
```

**Comment by antoinerey** [comment]
@manniL Whoa, I completely missed it when reading the documentation. Sorry about that. I let you decide if this issue should be closed since a solution is available.

Thanks !

**Comment by manniL** [comment]
Closing here as I think that this recommended way should cover the necessary cases ☺️
