### ISSUE TITLE
Links pointing to / always receive the nuxt-link-active class

### ISSUE THREAD

**Issue by silvestreh** [nuxt/nuxt.js#506]
For some reason, all `nuxt-link` pointing to `/` will receive the `nuxt-link-active` class regardless they're active or not.

<img width="823" alt="captura de pantalla 2017-04-04 a las 00 16 51" src="https://cloud.githubusercontent.com/assets/1133339/24640264/1c0f36c6-18cc-11e7-8607-0b81887049ed.png">

In the screenshot above, "Novedades" points to `/` and is active when the url path matches `/bio`. The rendered DOM looks like:

<img width="502" alt="captura de pantalla 2017-04-04 a las 00 19 06" src="https://cloud.githubusercontent.com/assets/1133339/24640301/65821f6c-18cc-11e7-9a90-fc304bef11b2.png">

Notice both links have the `navigation__item--active` class.

I'm also able to reproduce it in the [head elements demo](https://head-elements.nuxtjs.org/about).

**Comment by ausir0726** [comment]
https://router.vuejs.org/en/api/router-link.html

please see exact attribute

**Comment by silvestreh** [comment]
@ausir0726 thanks for pointing that out! (and sorry for not RTFM)
