### ISSUE TITLE
https://nuxtjs.org/guide/views/#error-page

### ISSUE THREAD

**Issue by Wulawa** [nuxt/nuxt.js#5060]
https://nuxtjs.org/guide/views/#error-page
> You can customize the error page by adding a layouts/error.vue file.

_Originally posted by @NicoPennec in https://github.com/nuxt/nuxt.js/issues/1614#issuecomment-328034047_

**Comment by manniL** [comment]
https://blog.lichter.io/posts/change-the-nuxtjs-server-error-page might help
