### ISSUE TITLE
custom error middleware is never used when a server side error is thrown

### ISSUE THREAD

**Issue by devomacdee** [nuxt/nuxt.js#5068]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/devomacdee/nuxt-server-error](https://github.com/devomacdee/nuxt-server-error)

### Steps to reproduce

- start app
- repro link is set up to throw server error

### What is expected ?

the custom error middleware should engage when a server side error is thrown printing the error.

### What is actually happening?

Custom error middle ware is never being hit when a server side error is thrown

### Additional comments?

This is tested on 1.4.3 and 2.4.0. Behaviour is the same on both versions. In 1.4.3 when the app is compiling you get a log in the terminal that the hooks have been registered. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8690">#c8690</a>)</em></sub></div>

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/53255059-be8a5880-36bc-11e9-9e1d-d335b14f52b5.png)


Can't repro
