### ISSUE TITLE
Loading is prohibited on the pages

### ISSUE THREAD

**Issue by Wulawa** [nuxt/nuxt.js#5073]
### What problem does this feature solve?

Individual pages do not need to be loading

### What does the proposed changes look like?

Can disable loading on the pages
E.g: 
```
export default {
  loading: false
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8691">#c8691</a>)</em></sub></div>

**Comment by manniL** [comment]
What do you exactly mean with "loading"?

**Comment by Wulawa** [comment]
> What do you exactly mean with "loading"?

Custom Loading Component between the routes

**Comment by Wulawa** [comment]
> What do you exactly mean with "loading"?

Progress bar  between the routes.  Now the requirements have been met through custom components

Thank you

**Comment by manniL** [comment]
This is already a thing: https://nuxtjs.org/api/pages-loading#the-loading-property

**Comment by Wulawa** [comment]
> This is already a thing: https://nuxtjs.org/api/pages-loading#the-loading-property

Thank.  This api only exists in English documents 😂Did not see before
