### ISSUE TITLE
Server side render is significantly slower than the 1 axios call that it's running

### ISSUE THREAD

**Issue by kalenjordan** [nuxt/nuxt.js#5074]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/kalenjordan/nuxt-test/blob/master/pages/home.vue#L93](https://github.com/kalenjordan/nuxt-test/blob/master/pages/home.vue#L93)

### Steps to reproduce

1. Go to https://pros.global/
2. Open up network tab and look at the time for initial page response
![Screen Shot 2019-02-20 at 2.54.21 AM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/366fc960-34ed-11e9-b856-8705a8838ce8.png)

### What is expected ?

The initial page response should be roughly as long as the API call to grab the users for the home page, which is about 130ms - https://api.pros.global/api/v1/saved-searches/home?with_users=1

![Screen Shot 2019-02-20 at 2.56.09 AM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/6587e890-34ed-11e9-b856-8705a8838ce8.png)

### What is actually happening?

The initial page response is much longer than expected: ~1800ms.

Note that in my local development environment this doesn't happen. Only happens in production (digitalocean).

### Additional notes

It seems to be much slower when running in production mode (`npm run start`) vs. dev mode (`npm run dev`) in the production environment. Response time is more like 500ms or 600ms when it's run in dev mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8694">#c8694</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @kalenjordan. I've seen your code. It seems you are not using [axios-module](https://axios.nuxtjs.org). As a best practice, the `baseURL` for SSR renders should be different than `browserBaseURL`. So that backend API calls are over the plain HTTP. Also using LRU cache.

BTW this issue should be investigated more. I suggest doing this:

1. Use `curl` in your DO ssh to test request time to the API
2. Test against a page without requests in `asyncData` to see how it differs. Is bottleneck the SSR phase or requests

**Comment by kalenjordan** [comment]
Thanks for the quick reply @pi0! Hmm I think I am using the axios module?
https://github.com/kalenjordan/nuxt-test/blob/master/nuxt.config.js#L65

Noted on baseURL - that's something I need to look into.

On the `curl` point - that's actually something I was just trying. It is actually significantly faster over curl and also generally on first page view with an incognito browser - there seems to be something happening with a cookie or session to slow things down.

I have tested with asyncData disabled and it's definitely way faster.

**Comment by manniL** [comment]
@kalenjordan You have it in your module list, but you don't *use it*.

```js
 async asyncData(context) {
            if (!process.server) {
                return {homeSavedSearch: {users: []}};
            }
            // You can set the base URL in your nuxt config
            let url = process.env.API_URL + 'saved-searches/home?with_users=1';
            return context.$axios.get(url)
                .then((response) => {
                    return {
                        homeSavedSearch: response.data,
                    }
                })
        },

**Comment by pi0** [comment]
> It is actually significantly faster over curl and also generally on first-page view with an incognito browser. there seems to be something happening with a cookie or session to slow things down.

I think so. The bottleneck may be the authentication middleware for the backend.

**Comment by kalenjordan** [comment]
I updated my nuxt app to use the $axios community module properly. Unfortunately it doesn't seem like I can hit the http API for server side render because the app serving the api is setup to redirect all http requests to https.
