### ISSUE TITLE
Error when importing components without .vue extension in TypeScript

### ISSUE THREAD

**Issue by cretueusebiu** [nuxt/nuxt.js#5075]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/zrl1qrlo3p](https://codesandbox.io/s/zrl1qrlo3p)

### Steps to reproduce

Go to the CodeSandbox reproduction link and open the terminal window.

### What is expected ?

Resolve .vue files without throwing errors in the terminal.

### What is actually happening?

It resolves .vue files but still throws an error in the terminal.

```
ERROR  in ~/pages/index.vue 
Cannot find module '~/components/HelloWorld'.

import HelloWorld from "~/components/HelloWorld";
``` 

![screenshot_1](https://user-images.githubusercontent.com/1517945/53090684-d6c17280-3518-11e9-9937-081994c5d36a.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8696">#c8696</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@cretueusebiu I'm not able to reproduce it, your CSB doesn't seem to throw errors 🤔

**Comment by cretueusebiu** [comment]
@kevinmarrec It will still compile and work in the browser, but in the terminal it will throw an error.
![screenshot_1](https://user-images.githubusercontent.com/1517945/53090684-d6c17280-3518-11e9-9937-081994c5d36a.png)

**Comment by kevinmarrec** [comment]
@cretueusebiu Alright, I indeed have been able to see the error by triggering a change.

Well you need to add `.vue` extension when importing Vue SFC's.
```ts
import HelloWorld from "~/components/HelloWorld.vue"
```

Implicit module imports (not providing extension of the imported module) should (IMO) only be done for `.js` & `.ts` extensions.

**Comment by cretueusebiu** [comment]
What's strange is that everything sill compiles and works fine, it just throws that error in the terminal.

**Comment by kevinmarrec** [comment]
@cretueusebiu It's cause of the TypeChecker which run in seperate process.
See https://github.com/Realytics/fork-ts-checker-webpack-plugin#vue
> To activate TypeScript in your .vue files, you need to ensure your script tag's language attribute is set to ts or tsx (also make sure you include the .vue extension in all your import statements as shown below):
