### ISSUE TITLE
Aliases in the router - why it is worth to reconsider it

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#508]
Please reconsider adding aliases to the router.

*Why?*
- It is very useful when porting old application to nuxt, especially when we want to save the old link structure

*What about seo?*
- Some of the application that we are porting are just for the intranet. So the seo is not a problem.
- For the rest of it we use meta: "noindex, follow"

*Workaround:*
- Now we have to use extendRoutes but we prefer more clean way to do this.

Thanks in advance!

**Comment by sebastianmacias** [comment]
I'm also looking for a clean way to do this.

If I have a project with the following pages/components:

- pages
---- companies
---- inbox
---- calendar

I should be able to have URLs like this:

/companies/{companyID}/inbox
/companies/{companyID}/calendar

without having to put my inbox and calendar pages inside the companies folder. I love the autogenerated routes but it would be very helpful to also be able to define aliases.

**Comment by sebastianmacias** [comment]
In the meantime what I think I would do is have my components outside the pages directory and use symbolic links to build the routes using the schema I need

**Comment by alexchopin** [comment]
@sebastianmacias you can import a page component into another page component if you want to reuse it.

**Comment by Atinux** [comment]
It will be possible to update our router.js template to write your own with the modules system in the upcoming release.

**Comment by Atinux** [comment]
Closing it since `rc3` is out, to see an example: https://github.com/nuxt/nuxt.js/blob/dev/test/fixtures/module/modules/template/index.js

**Comment by epartipilo** [comment]
Hi @Atinux 
How can I use this?
I've looking for a while but cannot find how to implemente it.

Thanks!
