### ISSUE TITLE
Add SCSS includePaths options no longer works 

### ISSUE THREAD

**Issue by ahmadmilzam** [nuxt/nuxt.js#5082]
### Version

[2.4.3](https://github.com/nuxt.js/releases/tag/2.4.3)

### Reproduction link

[https://codesandbox.io/s/ym23lwkojx](https://codesandbox.io/s/ym23lwkojx)

### Steps to reproduce

Add node-sass, sass-loader.
Add unuitcss package from npm
Create global.scss file.
Add global.scss file into nuxt.config.js

### What is expected ?

Global scss successfully import file from node_modules folder, after add scss options includePath on build extend function.

### What is actually happening?

File to import not found or unreadable.

### Additional comments?

It works perfectly on my another project using nuxt@2.3.4, idk why it not work in nuxt@2.4.3
I can't make it work on codesandbox for nuxt@2.3.4, here's my repo for working sample: https://github.com/ahmadmilzam/test-vue-234

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8701">#c8701</a>)</em></sub></div>

**Comment by manniL** [comment]
Suggestion: Use https://github.com/nuxt-community/style-resources-module for adding SCSS/LESS/Stylus variables to all your components

**Comment by ahmadmilzam** [comment]
> https://github.com/nuxt-community/style-resources-module

Thank you, but what I really need is the ability to include `scss` module from `node_modules` folder without adding tremendous path at `@import`

**Comment by manniL** [comment]
@ahmadmilzam Not sure what you mean 🤔 

https://github.com/nuxt-community/style-resources-module/blob/master/test/fixture/sass/nuxt.config.js#L11

**Comment by manniL** [comment]
Regarding the original issue, this works fine with:

```js
build: {
    loaders: {
      scss: {
        includePaths: ["node_modules/inuitcss"]
      }
    }
  }
```

**Comment by ahmadmilzam** [comment]
@manniL what nuxt version do you use to reproduce the bug? i have new fresh install nuxt 2.4.5 and still not working. You mind to share with me your working code?
