### ISSUE TITLE
Generate meta data when running nuxt generate

### ISSUE THREAD

**Issue by mazipan** [nuxt/nuxt.js#5084]
### What problem does this feature solve?

I have Nuxt app that running with mode `spa` with pages

```
/
/a
/b
```

Then in every page I have setup `head ()`, but when I run `nuxt generate` with defining `routes: ["/a", "/b"]` it's not print html with head that I already define in pages file.

It will requested by JavaScript in the client side. 
It very usefull for SEO when using static hosting like Netlify.

### What does the proposed changes look like?

It should generate meta if we define the routes in `generate` in `nuxt.config.js`.

Or we can add routes as Object like: 

```js
generate: {
  routes: {
   path: '/a',
   meta: { 
     // some eta data
   }
  }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8704">#c8704</a>)</em></sub></div>

**Comment by amulecregg** [comment]
This would be awesome.

**Comment by mazipan** [comment]
After looking for many workaround, it because running Dan generate in `spa` mode.
We need to change from spa to universal.
Or it's my bad.

We can follow how nuxt.org repo generate it's static file.
I also create repo with same needed in https://github.com/mazipan/blog-2.0

I will close this issue, since it's already solve when switch mode.

Thanks
