### ISSUE TITLE
NuxtServerError - Request failed with status code 500 - No indication of which API call failed

### ISSUE THREAD

**Issue by kalenjordan** [nuxt/nuxt.js#5089]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/kalenjordan/pros.global](https://github.com/kalenjordan/pros.global)

### Steps to reproduce

I'm not exactly sure how to reproduce, but usually within 2 to 8 hours it happens on my app (https://pros.global). It seems that axios is hitting a 500 error response but I have no indication of what API request failed exactly. 

NuxtServerError
Request failed with status code 500
/home/forge/pros.global/node_modules/axios/lib/core/createError.js in createError at line 16:15
/home/forge/pros.global/node_modules/axios/lib/core/settle.js in settle at line 18:12
/home/forge/pros.global/node_modules/axios/lib/adapters/http.js in IncomingMessage.handleStreamEnd at line 201:11
events.js in IncomingMessage.emit at line 187:15
domain.js in IncomingMessage.EventEmitter.emit at line 459:23
_stream_readable.js in endReadableNT at line 1094:12
internal/process/next_tick.js in process._tickCallback at line 63:19

### What is expected ?

I would expect that I would have some way to know which API call failed in the error log.

### What is actually happening?

There is no indication of which API call failed.

### Additional comments?

Perhaps there is a way within axios to log all API requests that go through so that I could at least correlate the error to that log?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8707">#c8707</a>)</em></sub></div>

**Comment by pimlie** [comment]
If you use the nuxt axios module you can set debug to true so all requests are logged (be aware of disk space issues if you are logging this to file and running for 8 hrs!): https://axios.nuxtjs.org/options#debug
