### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by demyan1411** [nuxt/nuxt.js#509]
Lifesicle hook mounted not working in IE10 http://prntscr.com/esfkb0 , nothing in console...
beforeMount is not working too

**Comment by ausir0726** [comment]
It looks working on me .

Do you have some error on your console panel ?

<img width="1639" alt="2017-04-05 10 12 45" src="https://cloud.githubusercontent.com/assets/7247064/24686782/82118164-19e8-11e7-97e2-2e7688415d2d.png">

**Comment by demyan1411** [comment]
It works in IE EDGE, but not not working in IE10-11 
The Error - 'Symbol' is undefined

![](http://image.prntscr.com/image/3816bac611f4440ebb0a2fb1fd740f60.png)

**Comment by ausir0726** [comment]
through this portal please

https://github.com/nuxt/nuxt.js/issues/483

**Comment by demyan1411** [comment]
I found!! Thanks! =))

this is help me:
build: {
        extend(config, { isClient }) {
            if (isClient) {
                config.entry.vendor.push('babel-polyfill')
            }
        }
    }
