### ISSUE TITLE
Build fails for simple input + v-model example

### ISSUE THREAD

**Issue by dweldon** [nuxt/nuxt.js#5091]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/dweldon/input-error](https://github.com/dweldon/input-error)

### Steps to reproduce

npm i && npm start

### What is expected ?

The app should start

### What is actually happening?

Unexpected token, expected ","

### Additional comments?

This doesn't seem to be an issue with Vue itself, but maybe something with webpack. It only started a few hours ago after doing a clean install.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8709">#c8709</a>)</em></sub></div>

**Comment by mmoulton** [comment]
I ran into the same problem today. Reverting to `2.6.6` of `vue`, `vue-server-renderer`, and `vue-template-compiler` resolved this for me. It seems some regression was introduced with the release of `2.6.7` today.

**Comment by dweldon** [comment]
I did a clean install just now and everything is working again w/o any changes. I guess one or more of my 1739 dependencies changed overnight and... magic. :tophat: :rabbit:
