### ISSUE TITLE
[Bug Report]Config babel-polyfill and IE 10 is also not working

### ISSUE THREAD

**Issue by K-Stella** [nuxt/nuxt.js#5093]
Before I config 'babel-polyfill ', it tips SCRIPT5009: “Set”未定义.And after I config 'babel-polyfill ',it tips me like this pic 👇.

![image](https://user-images.githubusercontent.com/23692583/53227703-fc39b200-36b9-11e9-8f98-973e5788ed34.png)

Someone can get me some suggestion or some methods to solve this ? Thanks so much !

**Comment by busyrat** [comment]
@K-Stella I have the same problem，Can you tell me how to config 'babel-polyfill'
