### ISSUE TITLE
Recognize store usage without index.js

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#5099]
### What problem does this feature solve?

Hey :wave: 

Currently you necessarily need an index.js (even if it's just empty) to load the store. having only a named module, say /store/user.js isn't recognized properly. We should improve that 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8716">#c8716</a>)</em></sub></div>

**Comment by kefranabg** [comment]
Hey 👋

Is this issue still relevant ? I tried to run nuxt  on the `vuex-store` folder from the `examples` folder without `index.js` and named modules seems to be properly recognized by `Vuex`. Am I missing something ?

**Comment by manniL** [comment]
This breaks for me. make sure you restart the server after removing the `index.js` (or start the sever afterwards)
![image](https://user-images.githubusercontent.com/640208/54224121-26340680-44f9-11e9-9d12-4b1774f51d0a.png)

**Comment by kefranabg** [comment]
I did restart the server after changes 😕

Removing `index.js` breaks the index module as expected, but it seems that the store is still properly  instantiated so I will be able to use other modules like Todo module.

Here is what I get when I keep the `index.js` :

![Capture d’écran 2019-03-12 à 20 05 52](https://user-images.githubusercontent.com/9840435/54228370-546a1400-4502-11e9-9598-89ecbdc38373.jpg)

And here is what I get when I remove it :

![Capture d’écran 2019-03-12 à 20 03 50](https://user-images.githubusercontent.com/9840435/54228246-06551080-4502-11e9-8470-bf7b9cdc1603.jpg)


The only difference with the version above is that I do not have the `counter` property from the vuex root module, but vuex still works pretty well.

**Comment by manniL** [comment]
You are right :see_no_evil: 

Thanks for reporting! :+1:
