### ISSUE TITLE
How to refer to data inside export default{}, from outside ?

### ISSUE THREAD

**Issue by MatthieuHPP** [nuxt/nuxt.js#510]
Hello,

I would like to refer to data or methods defined within export default :
[question.txt](https://github.com/nuxt/nuxt.js/files/894332/question.txt)

What shall I use instead of ????

Many thanks for you help

**Comment by Atinux** [comment]
Hi @MatthieuHPP 

You should create a variable and export it, then you can access this variable:

```js
const MyComponent = {
  data () {
    return { foo: 'bar' }
  }
}
let bar = MyComponent.data().foo

export default MyComponent
```

**Comment by MatthieuHPP** [comment]
Many thanks !
