### ISSUE TITLE
Cannot read property 'useragent' of undefined

### ISSUE THREAD

**Issue by msudgh** [nuxt/nuxt.js#511]
I wrote an app that uses **`express-useragent`** as middleware and stores it by **`store`** directory but when I click on the internal links I got **`Cannot read property 'useragent' of undefined`** error.
What's wrong?

middleware/useragent.js:
```js
export default function ({ req, store }) {
  store.commit('update', req.useragent)
}
```

store/index.js
```js
export const store = {
  state: {
    platform: '',
    browser: '',
    suggestible: false,
    isIOS: false,
    isAndroid: false
  }
}

export const mutations = {
  update(state, useragent) {
    state.platform = useragent.platform
    state.browser = useragent.browser
    state.isIOS = useragent.isiPad || useragent.isiPhone ? true : false
    state.isAndroid = useragent.isAndroid
  }
}
```

thanks

**Comment by Atinux** [comment]
@msudgh the middleware are run both on client-side and server-side, so when navigating on client-side, req does not exists and create this error you have.

You should check if `req` exists, see https://github.com/nuxt/nuxt.js/blob/master/examples/middleware/middleware/user-agent.js

**Comment by msudgh** [comment]
Do you have solution for this problem?

**Comment by msudgh** [comment]
You're right, but when i pass user agent to the store I got bellow errors.

`
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
`

**Comment by Atinux** [comment]
This erro is not from the middleware directly since it's from the hydration, it comes from something else.

**Comment by msudgh** [comment]
this is my middleware:

```js
export default function (context) {
  context.userAgent = context.isServer ? context.req.headers['user-agent'] : navigator.userAgent
  store.commit('update', context.userAgent)
}
```

When I uncomment store.commit line, there's not error.
