### ISSUE TITLE
Html page title is not updated when using webpack externals configuration

### ISSUE THREAD

**Issue by ChenZhuoSteve** [nuxt/nuxt.js#5113]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/ChenZhuoSteve/nuxt-meta-issue.git](https://github.com/ChenZhuoSteve/nuxt-meta-issue.git)

### Steps to reproduce

0. set page title
index.vue page
![setTitle1.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/75aff450-3985-11e9-be4b-53f8cd03c4ba.jpg)
about.vue page
![setTitle2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/8ed94cb0-3985-11e9-be4b-53f8cd03c4ba.png)

1. configuration webpack externals
![config.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/bab98ee0-3984-11e9-be4b-53f8cd03c4ba.png)
2. npm run build
3. npm start
4. check page title
![checkTitle1.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2f1b1b50-3985-11e9-be4b-53f8cd03c4ba.jpg)
5. click link, switch route
![checkTitle2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/f8300140-3985-11e9-be4b-53f8cd03c4ba.png)

### What is expected ?

Html title will change

### What is actually happening?

Html title will not change

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8730">#c8730</a>)</em></sub></div>

**Comment by farnabaz** [comment]
@pi0 This happens because `VueMeta` does not register in external Vue, `VueMeta` uses once inside `vue-renderer/src/spa-meta.js`.

https://github.com/nuxt/nuxt.js/blob/a5654876aa203c353c6a34ff856acc4f34bc191f/packages/vue-renderer/src/spa-meta.js#L16-L21

When we use `Vue` as an external library it doesn't have `VueMeta` and breaks meta bindings.

**Comment by ChenZhuoSteve** [comment]
@farnabaz 
Thanks!
I tried to manually register VueMeta, but still no effect.
![image](https://user-images.githubusercontent.com/9547402/54795831-99234700-4c88-11e9-9225-6e2a997d8d7a.png)

**Comment by ChenZhuoSteve** [comment]
2.6.1 version work well.
![image](https://user-images.githubusercontent.com/9547402/55710606-91e89100-5a1d-11e9-89b3-a753c9a5eb46.png)

**Comment by ChenZhuoSteve** [comment]
in production mode, html title is still not updated.😂

**Comment by Atinux** [comment]
Hi @ChenZhuoSteve 

Could you confirm the issue is still happening with latest version of Nuxt.js? (v2.8.1)?
