### ISSUE TITLE
Add ASP.NET Core Web Server Support

### ISSUE THREAD

**Issue by RehanSaeed** [nuxt/nuxt.js#5116]
### What problem does this feature solve?

ASP.NET Core has support for running Node using [JavaScriptServices](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.2). It's also one of the [faster web servers](https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=plaintext) according to the techempower benchmarks being several times quicker than Node at serving plain text. It would be great if we could have an ASP.NET Core + Nuxt option in the create-nuxt-app CLI.

### What does the proposed changes look like?

Adding an ASP.NET Core web server option in the create-nuxt-app CLI.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8732">#c8732</a>)</em></sub></div>

**Comment by ddregalo** [comment]
Yes please, would love to see this happen!

**Comment by manniL** [comment]
@pi0 please move to CNA repo

**Comment by RehanSaeed** [comment]
Moved to https://github.com/nuxt/create-nuxt-app/issues/194
