### ISSUE TITLE
Other device can not connect to computer's IP

### ISSUE THREAD

**Issue by zhengby** [nuxt/nuxt.js#512]
When I run the command
`npm run dev`
and open the browser to localhost:3000, it works well

But if I use other device and type 192.xxx.xxx.xxx:3000 in the browser, it says connection refused

I try other nodejs projects and they all work well through 192.xxx.xxx.xxx:3000 except nuxt.js

any help please ?

**Comment by ausir0726** [comment]
default host is listen 127.0.0.1
please change it to 0.0.0.0
you can

option 1 ( can't use on window )
HOST=0.0.0.0 npm run dev 

option 2
modify package.json
```json
"config": {
    "nuxt": {
      "host": "0.0.0.0",
    }
  },
```

**Comment by zhengby** [comment]
I got it, thinks.

**Comment by zhengby** [comment]
Thank you
