### ISSUE TITLE
asyncData firing twice when visited the app only once

### ISSUE THREAD

**Issue by XEngine** [nuxt/nuxt.js#5121]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/XEngine/nuxt-issue-reproduce](https://github.com/XEngine/nuxt-issue-reproduce)

### Steps to reproduce

- Create nuxtJS application either express template or adonisjs template
- put asyncData method to index.vue file in pages folder.
- console.log something, or console log in the API Endpoint side.
- Visit the 127.0.0.1:3000 with the browser

![53426248-b18ca280-39f7-11e9-92e0-68b3f0c68a5e.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/fa254420-39de-11e9-9273-371463d6e9fd.png)

### What is expected ?

asyncData fires only once

### What is actually happening?

asyncdata fires twice or more

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8737">#c8737</a>)</em></sub></div>

**Comment by manniL** [comment]
@XEngine Please provide a correct reproduction repository or codesandbox (via https://template.nuxtjs.org/)

**Comment by XEngine** [comment]
@manniL Thanks for the kind reply! I've updated the issue with the github repository.

**Comment by XEngine** [comment]
@manniL Accidentally closed the issue, reopening

**Comment by manniL** [comment]
@XEngine Is it reproducible without adonis (e.g. with express) and without *any* server framework?

**Comment by XEngine** [comment]
I didnt try standalone but its reproducible with express too

**Comment by manniL** [comment]
@XEngine Could you provide a *minimal* reproduction repo then?
It's easier for me to reproduce with a minimal express setup than with a huge `adonis` project (even though it's just scaffolded out and filled)

**Comment by captainskippah** [comment]
I am experiencing this one too but the `console.log()` is not fired twice.

![Peek 2019-03-20 23-52](https://user-images.githubusercontent.com/48720999/54701065-2a9e9600-4b6f-11e9-9f32-9e69343870a9.gif)

**Comment by XEngine** [comment]
Sorry I cannot give a full repository for this but even Nuxt standalone gives you the twice firing asyncdata issue. 

In order to not have twice firing I had to remove all custom components in my main page JS file which stops this issue. I don't know how it cause this but weirdly, removing all custom components like custom button components from the main page js files does the trick... which I think is pretty irrelevant.

**Comment by shanlh** [comment]
I also encountered the same problem, but because of my carelessness, I jumped the route and also sent an event to the parent component, causing it to be triggered twice with the nuxt-link.
