### ISSUE TITLE
Default TypeScript linter from TSLint to ESLint

### ISSUE THREAD

**Issue by envision** [nuxt/nuxt.js#5124]
### What problem does this feature solve?

TypeScript ecosystem is moving from TSLint to ESLint. Please update your example / starter templates.

https://eslint.org/blog/2019/01/future-typescript-eslint

https://artsy.github.io/blog/2019/01/29/from-tslint-to-eslint/

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8742">#c8742</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
Hi @envision 

We're aware of the future of TypeScript linting, and are planning to migrate/update our examples to use only ESLint soon.

Thank you for the blog post with nice guidelines !

I'll keep this open till we'll have properly switched to full ESLint for TS examples/starters.
