### ISSUE TITLE
Doesn't work with vue-class-component

### ISSUE THREAD

**Issue by krasevych** [nuxt/nuxt.js#513]
I use Nuxt and I try to use class-component, I installed the plugin:
``` .babelrc
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```
also I tried add in inside `nuxt.config`
```
build: {
      vendor: ['vue-class-component'],
      babel: {
        plugins: [
          'transform-decorators-legacy',
          'transform-class-properties'
        ]
      }
    }
```
but nothing works, What I do incorrect?

**Comment by krasevych** [comment]
When I added `presets: ['stage-0', 'es2015']`:
```
babel: {
      presets: ['stage-0', 'es2015'],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties'
      ]
    }
```
it works but hot reload - stopped working. What should I change for `hot-reload` and `class-component` - work together?

**Comment by Atinux** [comment]
Discussion moved to [vue-class-component#78](https://github.com/vuejs/vue-class-component/issues/78)
