### ISSUE TITLE
vue-app types  , "req" is wrong inside "Context"

### ISSUE THREAD

**Issue by fvigotti** [nuxt/nuxt.js#5130]
I'm quite new to typescript and new to nuxt also.. so I'm not creating a pull request, but just want to report an issue I'm having
during `nuxtServerInit` in axios, the method receive two parameters, the first one seems to be "ActionContext", but the second one every example and tutorials I've seen say that it's a "Context" type, which means :

Context in `@nuxt/vue-app/types/index.d.ts`
which is : 
```ts
export interface Context {
...
req: Request
...
```

I'm pointing to the "req" because It's here that I'm going to extract headers/cookie to perform authentication and it's here that I've seen the problem ..
 this is not of type "Request" but of  type : "IncomingMessage" ( when the context is parsed during ssr type is : `@types/node/http.d.ts` -> `IncomingMessage` )   , forcing typecasting to "fix" on my code seems weird, typescript interfaces should be right at the source, can someone more expert than me confirm that it is an issue with the source code ?

thank you,
Francesco

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8749">#c8749</a>)</em></sub></div>

**Comment by manniL** [comment]
cc @kevinmarrec

**Comment by kevinmarrec** [comment]
Thank for you feedback @fvigotti , but I don't honestly know enough core code to know what's wrong. 

@manniL Do you have any clue ? https://nuxtjs.org/api/context is saying that type is `Request`, but @fvigotti that it could be another type (during SSR only maybe ?)

**Comment by manniL** [comment]
@kevinmarrec The link on the docs redirects to https://nodejs.org/api/http.html#http_class_http_incomingmessage `Class: http.IncomingMessage`.

Feel free to change it.

PS: On client-side, req is not present.

**Comment by kevinmarrec** [comment]
@manniL What was the "link on the docs" you were talking about ?
I'm diving into this again and I was wondering how did we know that the correct type was `http.IncomingMessage`

**Comment by manniL** [comment]
@kevinmarrec https://nuxtjs.org/api/context -> "Request".

**Comment by kevinmarrec** [comment]
@manniL Thanks, I will change `req` & `res` types accordingly.
