### ISSUE TITLE
Increase the Build Speed

### ISSUE THREAD

**Issue by nahtnam** [nuxt/nuxt.js#5131]
### What problem does this feature solve?

Hello,

Recently I've been checking out Next.JS and I've found that it is more than 10-20x faster in the initial server startup time under very similar conditions. I'm not sure what they do exactly but sass compiles almost instantly.

NOTE: This is with Bulma installed (manually)

### What does the proposed changes look like?

Optimizing webpack?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8750">#c8750</a>)</em></sub></div>

**Comment by manniL** [comment]
There are several experimental ways of improving build speed.

https://nuxtjs.org/api/configuration-build#parallel
https://nuxtjs.org/api/configuration-build#cache
https://nuxtjs.org/api/configuration-build#hardsource

We are constantly trying to increase the build speed with updates.

As this issue is quite broad, I'll close it.
If you have any specific ideas, please feel free to open up another issue.

**Comment by nahtnam** [comment]
Wow, those three settings took the initial build times from 1+ minutes to 3 seconds (after the first run). Maybe these settings should be covered in the FAQ or a more accessible location?

**Comment by simplenotezy** [comment]
@nahtnam can you share what your build configuration looked like, after you tweaked it?

**Comment by dan-online** [comment]
After coming here I found builds sped up by 20s using these techniques which was quite helpful although I did run into a bug:
```
   │   The command 'nuxt build' finished but did not exit after 5s                        │
   │   This is most likely not caused by a bug in Nuxt.js                                 │
   │   Make sure to cleanup all timers and listeners you or your plugins/modules start.   │
   │   Nuxt.js will now force exit                                                        │
```

**Comment by torressam333** [comment]
So these 3 did help improve build time

```
hardSource: true,
cache: true,
parallel: true,
```

But I wanted to ask 2 things:

1. Why do they still say experimental? Will they be stable in Nuxt 2.x?
2. Is there any gotcha's that need to be know... i.e. in dev vs prod etc.? Thanks.
