### ISSUE TITLE
Updating to 2.4.5 from 2.3.4 DeprecationWarning: Tapable.plugin

### ISSUE THREAD

**Issue by Resoguy** [nuxt/nuxt.js#5135]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Steps to reproduce

I have updated my app from 2.3.4 to 2.4.5 version of nuxt. And I am taking this error when dev server is building nuxt.client.js.

Complete error text is:
```(node:61302) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead```

It resumes building and completes with a compilation warning which is:
```
chunk pages/product/_id.pages/profile/_id [extract-css-chunks-plugin]

Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-2!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-3!./node_modules/sass-loader/lib/loader.js??ref--9-oneOf-1-4!./node_modules/vue-loader/lib??vue-loader-options!./components/cards/SearchResultProductCard.vue?vue&type=style&index=0&id=08d7c683&scoped=true&lang=scss&
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-2!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-3!./node_modules/sass-loader/lib/loader.js??ref--9-oneOf-1-4!./node_modules/vue-loader/lib??vue-loader-options!./components/modals/ProfileNewListModal.vue?vue&type=style&index=0&id=41f29e2c&scoped=true&lang=scss&
```

After build complete when i enter localhost:3000 i get ```ReferenceError: regeneratorRuntime is not defined```.

### What is expected ?

Expected to build and compile without any errors or warnings.

### Additional comments?

I have updated my plugin names and nuxt.config file as in the official nuxt documentation suggest before update.

I have created a new nuxt app with ```yarn create nuxt-app <app_name>``` command and did not edit anything but still getting the same DeprecationWarning error and when i check the browser after, got this error:

```NuxtServerError: Cannot find module 'pages/index.js' from '...app/folder/nuxt25-test'```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8754">#c8754</a>)</em></sub></div>

**Comment by bandy87** [comment]
Try npm-check-updates 
https://www.npmjs.com/package/npm-check-updates

**Comment by manniL** [comment]
Okay. you are mixing up three errors here.

> `(node:61302) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead`

Have you tried googling it? `nuxt DeprecationWarning` will lead the correct result 🤷‍♂️ 
https://github.com/nuxt-community/pwa-module/issues/120

 > chunk pages/product/_id.pages/profile/_id [extract-css-chunks-plugin] Conflicting order between

Again, google. https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126

> `NuxtServerError: Cannot find module 'pages/index.js' from '...app/folder/nuxt25-test'`

#5132

**Comment by Marszed** [comment]
experiencing the same issue in my Nuxt project

nuxt@2.10.1 dependences extract-css-chunks-webpack-plugin@4.6.0

but extract-css-chunks-webpack-plugin@4.6.0 has error, like this [issues-->extract-css-chunks-webpack-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250), [issues-->Nuxt](https://github.com/nuxt/nuxt.js/issues/5135)

so, you can set nuxt@2.10.1 dependences extract-css-chunks-webpack-plugin@^4.5.2

i use yarn, so i soloved it by change yarn.lock dependences extract-css-chunks-webpack-plugin@^4.5.2
