### ISSUE TITLE
Warning is shown in built bundle (Classic mode for store/ is deprecated and will be removed in Nuxt 3).

### ISSUE THREAD

**Issue by tanakaworld** [nuxt/nuxt.js#5136]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/jjyz70wpm3](https://codesandbox.io/s/jjyz70wpm3)

### Steps to reproduce

N/A

![Pasted_Image_2019_03_01_10_27.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/4c466700-3bc1-11e9-a8a1-cbd2b571b91c.png)

### What is expected ?

No warning in built bundle.

### What is actually happening?

Warning "Classic mode for store/ is deprecated and will be removed in Nuxt 3" is shown for https://nuxtjs.org/guide/vuex-store/#classic-mode.

### Additional comments?

How can I prevent showing this warn?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8756">#c8756</a>)</em></sub></div>

**Comment by SuperRun** [comment]
how to solve this problem

**Comment by manniL** [comment]
See #4912
