### ISSUE TITLE
Change default layout programmatically

### ISSUE THREAD

**Issue by russellsean** [nuxt/nuxt.js#5144]
### What problem does this feature solve?

Role-based applications could load different layouts based on the user's role. Currently, I am utilizing the layout property in every component like:

```
  layout(context) {
    return context.store.state.auth.user.role
  } 
```
my layout folder is structured like:
layout/
- admin.vue
- default.vue
- manager.vue
- norole.vue
- user.vue

Which works great until I create a new component and forget to throw this snippet in.

### What does the proposed changes look like?

I am wondering if having a global method to set the default layout would be a useful feature. In the scenario of programmatically changing the layout based on a user's role, I would image it would be called like:

```
this.$layout.setDefault(this.$auth.user.role + '.vue'); // admin role -> admin.vue
// or maybe even bind it?!
this.$layout = this.$auth.user.role + '.vue';
```

Maybe I am overthinking this. Thanks!

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8764">#c8764</a>)</em></sub></div>

**Comment by Timkor** [comment]
I think that's already possible:
```javascript
$nuxt.setLayout('admin')
```

**Comment by russellsean** [comment]
Thank you! Do you know of any way I can access this.$nuxt from within vuex?

**Comment by manniL** [comment]
@russellsean on client-side: `window.$nuxt`.

**Comment by manniL** [comment]
PS: Closing here as the requested feature is already included.

**Comment by russellsean** [comment]
I noticed this only changes for the current component. If you route to another page it changes back to the default layout. Is there any way to change the default layout for the entire app?

**Comment by altryne** [comment]
Jumping in here, is there a way to use setLayout from inside asyncData? 
All I found is accessing `context.app.methods.setLayout` but it doesn't change the actual layout of the printed page.

**Comment by marko-mlinarevic** [comment]
@russellsean @altryne did you find the solution?

**Comment by russellsean** [comment]
@marko-mlinarevic negative. I took a different approach. I use the same layout for authenticated users, but load components based on their role.

**Comment by marko-mlinarevic** [comment]
@russellsean I did a hacky solution.

when landing on page I do this in fetch

```
          beforeNuxtRender(({ nuxtState }) => {
            nuxtState.layout = store.state.layout;
          })
```
and when changing pages I do this in created

```

    this.$nuxt.setLayout(this.$store.state.layout)

```
It works for now

**Comment by fadonascimento** [comment]
Hi guys the solution on the client works very well, just need a loading to cover the layout changes, but in the `fetch` the solution for the backend works but throws some errors on the console about the Virtual DOM, is there another solution to resolve in the serve side? Because I think is a feature that the dev wanted to them.

**Comment by Chrisimir** [comment]
Maybe my approach can help. 
In default.vue layout I placed the layout change in the data().
You can place the layout switching logic in each layout.
`data() {
        if(this.$auth.loggedIn) {
            this.$nuxt.setLayout('different-layout');
        }
    }`

**Comment by defaye** [comment]
When I try changing the layout e.g. `$nuxt.setLayout('default')` it seems to get overwritten by the current layout almost immediately after the change. `$nuxt.layoutName` does return the layout I change it to though. Does anyone have any ideas?

```

    setLayout (layout) {
      if(layout && typeof layout !== 'string') {
        throw new Error('[nuxt] Avoid using non-string value as layout property.')
      }

      if (!layout || !layouts['_' + layout]) {
        layout = 'default'
      }
      this.layoutName = layout
      this.layout = layouts['_' + layout]
      return this.layout
    },
    loadLayout (layout) {
      if (!layout || !layouts['_' + layout]) {
        layout = 'default'
      }
      return Promise.resolve(layouts['_' + layout])
    },
    
    ```

**Comment by oliwarner** [comment]
`this.$nuxt.setLayout` works beautifully. Like so many things, it'd be nice to be able to find out about it without having to track down a reply to people desperately trying to do the same thing. This should be in the layout documentation. It's not:

![image](https://user-images.githubusercontent.com/113778/150517490-f01aaa83-d903-4ab2-87d8-af3faf73095e.png)

**Comment by jasenmichael** [comment]
I was able to achieve this by editing `layouts/default.vue` to something like this...
```javascript
<template>
  <DefaultLayoutV2 v-if="$config.version === 'v2'" />
  <DefaultLayoutV1 v-else />
</template>

<script>
import DefaultLayoutV1 from './default-v1.vue'
import DefaultLayoutV2 from './default-v2.vue'

export default {
  components: { DefaultLayoutV1, DefaultLayoutV2 }
}
```
