### ISSUE TITLE
Code splitting is not working at all by default in my NUXT app : <version : 2.4.5 >

### ISSUE THREAD

**Issue by shihab1812** [nuxt/nuxt.js#5147]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/shihab1812/nuxt-app-demo](https://github.com/shihab1812/nuxt-app-demo)

### Steps to reproduce

I tried by adding manually the 
splitChunks : {
      
        layouts: false,
        pages: true,
        commons: true
      
    } 
to the build property inside "nuxt.config.js" but no luck. I can easily see that after I build the nuxt app on the home root itself all the non-home rooty bundle chunks are also loading.

Can anyone help me out here ?

### What is expected ?

I tried by adding manually the 
splitChunks : {
      
        layouts: false,
        pages: true,
        commons: true
      
    } 
to the build property inside "nuxt.config.js" but no luck. I can easily see that after I build the nuxt app on the home root itself all the non-home rooty bundle chunks are also loading.

Can anyone help me out here ?

### What is actually happening?

I tried by adding manually the 
splitChunks : {
      
        layouts: false,
        pages: true,
        commons: true
      
    } 
to the build property inside "nuxt.config.js" but no luck. I can easily see that after I build the nuxt app on the home root itself all the non-home rooty bundle chunks are also loading.

Can anyone help me out here ?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8766">#c8766</a>)</em></sub></div>

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/53738579-d8cbef80-3e8f-11e9-9d6a-37f9bb8face7.png)


Can't reproduce. Code-splitting only happens when building the app in prod (`npm run build`).

**Comment by mapsgeek** [comment]
@manniL the code gets split on build but it still load all the chunks on the index page, have y ever ran that build in the browser and inspected it ?
