### ISSUE TITLE
vue-render isReady always get false when use ssr mode

### ISSUE THREAD

**Issue by chenyueyun** [nuxt/nuxt.js#5153]
https://github.com/nuxt/nuxt.js/blob/70047c776a589c7424da05fd9e94e685ba063c6d/packages/vue-renderer/src/renderer.js#L229

When I use ssr mode, `this.render.spa` alway get false, then I can't get isReady() function return  true?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8768">#c8768</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Are you using programmatic? Is this happening for dev or prod?
