### ISSUE TITLE
Unit test with Jest with Object spread syntax fails with SyntaxError

### ISSUE THREAD

**Issue by prashantpalikhe** [nuxt/nuxt.js#5159]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/nuxt/create-nuxt-app](https://github.com/nuxt/create-nuxt-app)

### Steps to reproduce

1. Create a fresh Nuxt project with `npx create-nuxt-app test`
2. Enable Jest
3. Open the sample Logo.spec.js
4. Add a Object spread syntax e.g. const test = { ...{foo: 'bar', baz: 'qux' } }
5. Run the test with `npm run test`

### What is expected ?

Test to run properly 

### What is actually happening?

Test fails with

({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import defineProperty from "./defineProperty";

SyntaxError: Unexpected identifier

### Additional comments?

This is because [Nuxt's babel-preset-app](https://github.com/nuxt/nuxt.js/blob/dev/packages/babel-preset-app/src/index.js) configures @babel/plugin-transform-runtime to [always use ES modules](https://github.com/nuxt/nuxt.js/blob/dev/packages/babel-preset-app/src/index.js#L107). Jest is by default configured to not transform node_modules dependencies. So, while executing the runtime helper like the ObjectSpread helper, Jest runs into ES imports. Which it cannot understand and result in SyntaxError.

Vue Cli tackles this by using [process.env.VUE_CLI_BABEL_TRANSPILE_MODULES](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js#L158) which is [set to true](https://github.com/vuejs/vue-cli/blob/99761b350d37f4546bb2851fbe6f1b7e831f1b2a/packages/%40vue/cli-plugin-unit-jest/index.js#L14) when running test, therefore disabling the use of ES modules for @babel/plugin-transform-runtime.

For now, the easy fix for me was to not use `@nuxt/babel-preset-app` in .babelrc 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8771">#c8771</a>)</em></sub></div>

**Comment by aldarund** [comment]
First its issue with create nuxt app, not nuxt. So please submit to the right repository :)
 Second there a few fixes for it in cna already. e.g. use of jest 24 and remove of nuxt/babel-preset-app
https://github.com/nuxt/create-nuxt-app/pull/193

**Comment by f3ltron** [comment]
rude answer...
