### ISSUE TITLE
scrollToTop not working for `_slug` style routes

### ISSUE THREAD

**Issue by rwwagner90** [nuxt/nuxt.js#5162]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/shipshapecode/website-nuxt](https://github.com/shipshapecode/website-nuxt)

### Steps to reproduce

If you run `yarn dev` and navigate to the `blog` route, then click a blog post, then scroll to the bottom, and click one of the next/previous links, you will notice it will drop you at the same scroll position as the post you navigated from, rather than resetting the scroll position.

You can also see this reproduced, without needing to pull down code if you go to https://shipshape.io/blog/ad-hoc-relationships-with-ember-data/ and click the next/previous links at the bottom.

### What is expected ?

`scrollToTop` should be respected and the scroll position should be reset, when following links, and maintained when using the back button.

### What is actually happening?

The scroll is not reset, and you are put at the same scroll position as the previous post.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8772">#c8772</a>)</em></sub></div>

**Comment by HamidNE** [comment]
Hi brother
add this code in root of `nuxt.config.js` file to fix scroll

```
  router: {
    scrollBehavior: function (to, from, savedPosition) {
      return { x: 0, y: 0 }
    }
  },
```

**Comment by rwwagner90** [comment]
@HamidNE that will always scroll to the top though, right? I want the `savedPosition` to work too. It should work as intended in the browser, and scroll to the top when you navigate to a new route via links, but retain scroll position when using back buttons etc.

**Comment by rwwagner90** [comment]
Either way, this is a bug in Nuxt, and should be addressed, rather than needing a workaround.

**Comment by rwwagner90** [comment]
```js
router: {
    scrollBehavior(to, from, savedPosition) {
      if (savedPosition) {
        return savedPosition;
      }

      return { x: 0, y: 0 };
    }
  },
```

This kind of works, as it will keep the saved position, but it does not correctly do the transition animations.

**Comment by rwwagner90** [comment]
This is still an issue.

**Comment by rwwagner90** [comment]
@manniL does pending mean there is a fix in progress?

**Comment by manniL** [comment]
@rwwagner90 	No, pending means it is an "acknowledge"/"repro-able" bug.

**Comment by arkhamvm** [comment]
I suppose that problem in `window.$nuxt.$once('triggerScroll', triggerScrollCallback)`. Cause `triggerScrollCallback` not even called.

**Comment by arkhamvm** [comment]
Any bugfix pls? 

@siblanco `setTimeout` doesn't related to page load, so in case of long page load, it will be scrolled earlier.

I use `nextTick` now, but it have side effects:
```ts
	return new Promise((resolve) => {
		(window as any).$nuxt.$nextTick(() => {            // first tick for asyncData call
			(window as any).$nuxt.$nextTick(() => {    // second tick for page render
				if (to.hash && document.querySelector(to.hash)) {
					position = {selector: to.hash};
				}
				resolve(position);
			});
		});
	});
```

**Comment by pimlie** [comment]
@rwwagner90 Does this issue still exist for you when you disable your custom scrollBehavior? I cant seem to replicate this anymore on your repo when I remove your custom scrollBehavior

**Comment by arkhamvm** [comment]
> @rwwagner90 Does this issue still exist for you when you disable your custom scrollBehavior? I cant seem to replicate this anymore on your repo when I remove your custom scrollBehavior

Nuxt 2.8.1 issue still exist.

**Comment by pimlie** [comment]
@arkhamvm I am not sure you are experiencing the same issue, can you create a reproduction of your issue?

**Comment by arkhamvm** [comment]
@pimlie 
1. Open page, scroll down
2. Click on `<nuxt-link>`
3. Page doesn't scroll to top `{ x: 0, y: 0 }`
4. Scroll up or down
5. Press "Back" in browser
6. Page doesn't scroll to saved position

**Comment by arkhamvm** [comment]
@pimlie as i say earlier `triggerScrollCallback`  doesn't called.

**Comment by pimlie** [comment]
@arkhamvm which codebase?

**Comment by arkhamvm** [comment]
@pimlie Sorry, i dont understand what you mean. I'm talking about this sample (as sayed it should be run as default): https://nuxtjs.org/api/configuration-router#scrollbehavior

**Comment by pimlie** [comment]
@arkhamvm Please share a working reproduction where `triggerScrollCallback` _doesnt_ work. I tested the behaviour you mentioned and that works for me correctly.

Without a working reproduction of the problem there is no issue thus also no fix necessary.

There was an issue though with scrollBehaviour when navigating on the same pagewith hashes, see here for a fix: https://github.com/nuxt/nuxt.js/pull/6012

**Comment by rwwagner90** [comment]
@pimlie it does appear the scroll issue has been fixed, however, the animations do not trigger from one blog post to another.

**Comment by arkhamvm** [comment]
@pimlie Sorry, it's look like my misunderstood how `<transition>` works. 
If `<nuxt />` is wrapped into `<transitional>`, `triggerScroll` will not called.
Example: https://codesandbox.io/embed/example-custom-routes-x7lvs
Take a look at `layouts/default.vue`

**Comment by pimlie** [comment]
@arkhamvm Thanks. Why do you need to wrap nuxt in a transition? Nuxt already support transitions by default for [layouts](https://nuxtjs.org/api/configuration-transition#the-layouttransition-property) and [pages](https://nuxtjs.org/api/pages-transition#the-pagetransition-property).

What probably happens under the hood is that the transition you added is 'blocking' the transition used in nuxt-child, becuase of that the beforeEnter event is never triggered on nuxt-child thus the triggerScroll event is not fired. See here if you are interested in the code: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-child.js

@rwwagner90 Hmm yes, seems so. Could you please create a new issue for that?

**Comment by rwwagner90** [comment]
@pimlie sure I can make a new issue. Should we close this one?

**Comment by pimlie** [comment]
Yes, sounds like a good idea.

If someone else still has a problem with scrolling please open a new issue :)

**Comment by silvio-e** [comment]
When going to the parent page the `nuxt.$once('triggerScroll', ())` doesn't get set. That could be because some route changes don't trigger a re-render. We can force a re-render with setting a `key` for the `<router-view>`. In a normal vue app we would do:

`<router-view :key="$route.fullPath"></router-view>`

In Nuxt we have two ways like described in the docs: https://nuxtjs.org/docs/features/nuxt-components#the-nuxt-component

1.

```Vue
<template>
  <div>
    <Nuxt :nuxt-child-key="someKey" />
  </div>
</template>
```

or 2.

```js
export default {
  key(route) {
    return route.fullPath
  }
}
```

That did the trick for me. Let me know if it works for you too!

**Comment by Bergrebell** [comment]
removing `overflow-x: hidden` and `overflow-y: auto` from the body did the trick for me.

**Comment by shaghnanii** [comment]
The issue still exists. I am using `"nuxt": "^2.15.8"`
Is there any solution from the offical side?

**Comment by Kurtil** [comment]
I had a special use case that may be related to some of you. I have a menu bar so the body is not scrolled down, it is the element with the custom id `app-content` I added. So in the scroll behaviour I add the following code:

```js
// nuxt.config.js
scrollBehavior (to, from, savedPosition) {
    document.getElementById('app-content').scroll(0, 0)
    return { x: 0, y: 0 }
}
```

And it works.
