### ISSUE TITLE
keep-alive not working, resets data after change tab

### ISSUE THREAD

**Issue by roelmagdaleno** [nuxt/nuxt.js#5166]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/9z8p69427r](https://codesandbox.io/s/9z8p69427r)

### Steps to reproduce

1. Click on ROEL USER button to go to Profile tab, which is an url (/roelmagdaleno/profile)
2. Go to Posts or Payments tab, when the component renders for the first time, it will show you the data.
3. Go back to Profile and then go to posts or payments again.
4. The current data that should kept alive has been reset to the initial values, an empty array.

### What is expected ?

Keep alive the current tab data, so it won't make another API call.

### What is actually happening?

The data is reset when user change the tab and enter again.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8776">#c8776</a>)</em></sub></div>

**Comment by ChenZhuoSteve** [comment]
https://codesandbox.io/s/73lqxj6436
posts.vue
![image](https://user-images.githubusercontent.com/9547402/53861377-0abf8c00-401f-11e9-889d-a9eca2ca82f0.png)
when using keep-alive, data() will be called repeatedly when the component is activated.

**Comment by roelmagdaleno** [comment]
Thank you, that works but I feel it is a little bit hacky.
In Vue.js, I could set the same behaviour without the if condition, weird.

Thanks!

**Comment by ChenZhuoSteve** [comment]
I don't think this issue should be closed. We don't know the root cause of this problem.
I am more inclined to think that this is a bug.

**Comment by roelmagdaleno** [comment]
Sorry, I closed since no one else commented, but you're right. Maybe someone of the core team could decide if it is a bug or not.

**Comment by clarkdo** [comment]
I'll have a look.
