### ISSUE TITLE
How to use data-src=""?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#517]
I am triyng to use Medium-like effect to blur loading of images.

I simply add files from https://github.com/Erichain/blur-image in `nuxt.config.js` and static folder. But When I am trying to use:

```
          <figure name="blur"
                  class="blur-img-container"
                  data-real-width="1800"
                  data-real-height="1199"
                  data-src="/images/sm.jpeg"
                  src="https://cdn-images-1.medium.com/max/1800/1*sg-uLNm73whmdOgKlrQdZA.jpeg"
          ></figure>
```
It throws me an error that it can't see image:

```
ncaught Error: You have't add any photo!
    at blurImg (blur-image.js:33)
    at blur-image.js:65
    at blur-image.js:66
```
I guess, it's mean data-src="/images/sm.jpeg".

How to fix it?

May be there's a better implementations of this feature?

**Comment by ausir0726** [comment]
this package you used have some problem and wrong sample code

please following my step should work .

1. add package
`yarn add blur-image // or npm i blur-image --save`

2. inject css to global
```js
// nuxt.config.js
css: [
    { src: 'blur-image/dist/blur-image.css' },
  ],
```
3. modify package source code 
because this package only query dom once when require 
```js
// node_modules/blur-image/dist/blur-image.js
// you sholud fork repo , and modify your code or just modify and move to asset folder
// line 30 ( should be )
// modify containers = [].concat(_toConsumableArray(containers)); to
containers = [].concat(_toConsumableArray(document.getElementsByName('blur')));
```

4. your vue file template
```
notice : sample code is class: Must be blur-image-container (Of course, you can change this in the css file).
but , it should be blur-img-container ( default css )
```
```html
<template>
<figure name="blur"
                  class="blur-img-container"
                  data-real-width="1800"
                  data-real-height="1199"
                  data-src="/images/sm.jpeg"
                  src="https://cdn-images-1.medium.com/max/1800/1*sg-uLNm73whmdOgKlrQdZA.jpeg"
          ></figure>
</template>
```

5. your vue file script
```js
<script>
if(process.BROWSER_BUILD){
  const blurImg = require('blur-image/dist/blur-image.js');
}
export default {
  mounted () {
    if (process.BROWSER_BUILD) {
      blurImg();
    }
  },
};
</script>
```

this is my generate project 
http://wiry-government.surge.sh/

**Comment by kodekrendel** [comment]
@ausir0726 great, thank you very much!

Just found this - https://github.com/hilongjw/vue-lazyload
Have you tried it?
Seems more apropriate solution for Nuxt. 
Hope it will work.

**Comment by ausir0726** [comment]
I think vue component package will easier than use pure js package :D

**Comment by kodekrendel** [comment]
@ausir0726 it seems far more advanced. Main benefit is that it uses img tag, so it's SEO friendly.

**Comment by kodekrendel** [comment]
Wow. Vue-lazyload awesome! http://many-winter.surge.sh/2/
