### ISSUE TITLE
Errors while creating a fresh Nuxt app

### ISSUE THREAD

**Issue by begueradj** [nuxt/nuxt.js#5175]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

- `yarn create nuxt-app project`
- Choose Linter/Formatter + axios
- Choose Vuetify.js

### What is expected ?

No errors

### What is actually happening?

I get this:

```
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ eslint --ext .js,.vue --ignore-path .gitignore . --fix

/home/begueradj/Development/draft/saya/c/nuxt.config.js
  1:29  error  Unexpected require, please use import instead                 nuxt/no-cjs-in-config
  2:13  error  Unexpected require, please use import instead                 nuxt/no-cjs-in-config
  4:1   error  Unexpected module.exports, please use export default instead  nuxt/no-cjs-in-config

✖ 3 problems (3 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional comments?

Ǹo link provided,
Billal BEGUERADJ

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8781">#c8781</a>)</em></sub></div>

**Comment by aldarund** [comment]
Please report to the right repository. Its about create nuxt app, not nuxt. 
And it was fixed but not released yet 
https://github.com/nuxt/create-nuxt-app/pull/203
