### ISSUE TITLE
router history with middleware

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#518]
hey,

after my auth middleware redirect me to the login page, i want , after i log in , to go to the protected page instead of the index ..

i tried the beforeEach and afterEach hooks , the from parameter always point to the index page (where the link to the protected page exist)

even in the routes change events , there is no trace of the protected page
![image](https://cloud.githubusercontent.com/assets/19589742/24751302/ef4da46e-1ac0-11e7-966c-6541eaaf1ab5.png)

any propositions?

**Comment by alexchopin** [comment]
Have you tried to create an other middleware for your authenticated routes?

**Comment by Etheryte** [comment]
Send the next route as a parameter to the login page when redirecting from auth and then use it from the login page once you're authenticated, very straightforward.

**Comment by aymenpeak** [comment]
@Etheryte how do i pass the next route?
there is my middleware
![image](https://cloud.githubusercontent.com/assets/19589742/24762239/b2879024-1ae5-11e7-99df-bb03fd2ed098.png)

**Comment by aymenpeak** [comment]
@Etheryte  i figure it out :)

thanks for the hint

**Comment by Lacroute** [comment]
Or you can add `beforeRouteEnter` hook in your page and play with the `from` parameter. Check the [In-Component Guards](https://router.vuejs.org/en/advanced/navigation-guards.html) doc from vue-router.
