### ISSUE TITLE
Request failed with status code 422

### ISSUE THREAD

**Issue by totski90** [nuxt/nuxt.js#5181]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/totski90/laravel-nuxt-front-end and the backend https://github.com/totski90/laravel-nux-back-end]

### Steps to reproduce

When form validation failed, it will be redirected to the default error "Request failed with status code 422" instead of the server side validation returned.

### What is expected ?

The expected returned should be the validation coming from the server which I handled on the form rendering if validation fails.

### What is actually happening?

It happened that the returned error was the javascript default error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8787">#c8787</a>)</em></sub></div>

**Comment by manniL** [comment]
Use `try/`catch` around your axios calls and handle the error properly

**Comment by haideritx** [comment]
can not use try catch with nuxt-auth?

```
await this.$auth.loginWith("local",{
                    data: this.form
                });
```

What to do in this case?
