### ISSUE TITLE
Nuxt server access log

### ISSUE THREAD

**Issue by shangxinbo** [nuxt/nuxt.js#5184]
### What problem does this feature solve?

In the production environment, how can I get the access log of the nuxt server, including each route, and the access log of each resource?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8790">#c8790</a>)</em></sub></div>

**Comment by aldarund** [comment]
Please dont open feature request for questions. If you need help you can either open a question on cmty or go to discord  https://discord.gg/nHzfFwe

**Comment by daaru00** [comment]
I think this is not only a question, If there is not "access log" option is a feature request. So, can be added this feature to Nuxt or there is already a suggested module to do that?

I'm also really interested in adding this feature to better monitor application when is live in production :+1:
