### ISSUE TITLE
Nuxt generate adding all styles inline

### ISSUE THREAD

**Issue by roslaneshellanoo** [nuxt/nuxt.js#519]
Everything working fine except stylesheets. 
Nuxt adding all styles inline inside <style> tag in the <head>.

Any help on this one please?

**Comment by kodekrendel** [comment]
Why do you need them separate?

**Comment by kodekrendel** [comment]
@roslaneshellanoo have you read this - https://github.com/nuxt/nuxt.js/issues/12

**Comment by alexchopin** [comment]
#475 #471
