### ISSUE TITLE
Duplicate app style links in head using universal mode and extractCSS

### ISSUE THREAD

**Issue by trentpeterson** [nuxt/nuxt.js#5190]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/y0p726km21](https://codesandbox.io/s/y0p726km21)

### Steps to reproduce

1. Inspect the source on the "Documentation" button in the iframed app and observe that `.button--green` is applied twice, both from line 91 in app.css.
2. Inspect the head and observe that app.css appears twice with `rel="preload"` and twice with `rel="stylesheet"`.
3. Change mode from `universal` to `spa`, refresh the iframed app, and note that app.css now appears once as preload and once as stylesheet and the button now has `.button--green` applied once.

### What is expected ?

Common CSS should only be included once

### What is actually happening?

Common CSS is included twice

### Additional comments?

I think this is what #4360 was trying to refer to, but it didn't follow the bug template and was closed.

#### Universal (unexpected behavior)

<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/8adf32a0-41ff-11e9-b03a-539a77cbad2a.png" width="300">

<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/eeba1830-41ff-11e9-b03a-539a77cbad2a.png" width="300">

#### SPA (expected behavior)
<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/3f0116e0-4200-11e9-b03a-539a77cbad2a.png" width="300">

<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/68a72b10-4200-11e9-b03a-539a77cbad2a.png" width="300">

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8794">#c8794</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Will be fixed in above linked pr which is in next Vue release

**Comment by hassan715** [comment]
The duplicate style links in header still exits even thought using the latest version.
```
<link rel="preload" href="/_nuxt/app.css" as="style">
<link rel="stylesheet" href="/_nuxt/app.css">
```

**Comment by manniL** [comment]
@hassan715 No, that's the preload instruction and not a duplicate 😉 Check https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by hassan715** [comment]
@manniL Yes my fault :relaxed: Thank you.

**Comment by rwwagner90** [comment]
We're still seeing styles duplicated in head and body. Does anyone have any tips?
