### ISSUE TITLE
path.replace is not a function when store folder is a symlink

### ISSUE THREAD

**Issue by Kasheftin** [nuxt/nuxt.js#5192]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/Kasheftin/nuxt-symlink-bug](https://github.com/Kasheftin/nuxt-symlink-bug)

### Steps to reproduce

1. Create the nuxt site using `npx create-nuxt-app` with any options enabled;
2. Write store/index.js file with any content (like this, https://github.com/Kasheftin/nuxt-symlink-bug/blob/master/some-store-dir/index.js);
3. Move store folder anywhere (for example, `mv store some-store-dir`);
4. Make a symlink (e.g. `ln -s some-store-dir store`);
5. Try to run, `npm run dev`;

### What is expected ?

It should work.

### What is actually happening?

It does not work.
The error is 
````
/home/kasheftin/work/tests/nuxt-symlink-bug/node_modules/webpackbar/dist/utils/index.js:58
  return path.replace(cwd, '');
              ^

TypeError: path.replace is not a function
    at shortenPath (/home/kasheftin/work/tests/nuxt-symlink-bug/node_modules/webpackbar/dist/utils/index.js:58:15)
````

### Additional comments?

Some small debug shows that shortenPath receives store's timestamp number instead of string. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8796">#c8796</a>)</em></sub></div>

**Comment by manniL** [comment]
cc @pi0

**Comment by fbrbovic** [comment]
@Kasheftin I have been experiencing this same issue for a while and I believe the issue is with Webpack it self, specifically watchpack. There is a PR for potential fix that has been sitting there: https://github.com/webpack/watchpack/pull/89

**Comment by pi0** [comment]
Webpackbar fix is released.
