### ISSUE TITLE
titleTemplate bug should fix it immediately

### ISSUE THREAD

**Issue by falstack** [nuxt/nuxt.js#5197]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues/5051](https://github.com/nuxt/nuxt.js/issues/5051)

### Steps to reproduce

this issue is fixed and merged

### What is expected ?

we use SSR for SEO, titleTemplate is very useful and important.

This bug has been around for a long time, but it has not been fixed.

I think we should pay more attention to the impact of this bug and release a fix version as soon as possible.

### What is actually happening?

titleTemplate can't work

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8799">#c8799</a>)</em></sub></div>

**Comment by aldarund** [comment]
Why do u create a new issue for already opened one? Im closing this one  unless u can provide how its different from the one you linked
PS and you can use titleTemplate with explicit return as described in issue you linked
