### ISSUE TITLE
ENV BaseUrl dont work

### ISSUE THREAD

**Issue by bitsmakerde** [nuxt/nuxt.js#5199]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://jsfiddle.net/vobx5za8/](https://jsfiddle.net/vobx5za8/)

### Steps to reproduce

npm run dev

### What is expected ?

if I change the env: baseUrl nothing change. If I start next the server is always "http://localhost:3000"

### What is actually happening?

change server to "http://localhost:9000"

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8803">#c8803</a>)</em></sub></div>

**Comment by aldarund** [comment]
baseUrl is nothing build in into nuxt, it just example how u defined env vars in nuxt config
You are looking for server section
https://nuxtjs.org/faq/host-port/#configure-in-code-nuxt-config-js-code-

**Comment by bitsmakerde** [comment]
Ok Thanks.

I try this, but I will set a subdomain and not only a IP. If I set only the ip the start ist crashing. 

Can you say me this is the correct command for this.

**Comment by aldarund** [comment]
subdomain is not a thing that is nuxt responsibility. And this is not a place for help. If u need help with your deployment go to nuxt  discord  https://discord.gg/6c46ekt

**Comment by bitsmakerde** [comment]
Error: Error: listen EADDRNOTAVAIL: address not available 10.11.12.71:8080

Config:

server: {
    port: process.env.PORT || 3000, // default: 3000
    host: appEnv.app.application_uris[0] // default: localhost
  },

**Comment by aldarund** [comment]
Like i said, github bug report this isnt place for help
