### ISSUE TITLE
nuxt build --watch

### ISSUE THREAD

**Issue by cj** [nuxt/nuxt.js#52]
Seems like this should be implemented, just like `webpack --watch`.

**Comment by Atinux** [comment]
`nuxt build` purpose is only to create the build for production.

Otherwise you should use `nuxt` which watch the files and update the build every time + hot reloading.

**Comment by cj** [comment]
@Atinux `nuxt` does not compile the files into `dist` which is what projects like ionic.io/cordova need when building mobile applications.

**Comment by cj** [comment]
@Atinux I'd love for you to re-open this for further discussion.

**Comment by Atinux** [comment]
I re-opened it @cj 

The fact is the `dist` folder is used for the `nuxt generate` already.

And I we are doing like `Next.js` by creating a `.nuxt/` folder.

**Comment by cj** [comment]
Thank you.  Then a `nuxt generate --watch` option, so it automatically rebuilds on changes.

This might be an edge case for people wanting to build for electron.io or ionic.io.  If it's not something you want to add, I understand.  I've created https://github.com/cj/vues, so that nuxt doesn't need to go down that path.

**Comment by Atinux** [comment]
Indeed, the main purpose of Nuxt.js is to build web applications.

I like what you did with `vues`, I'd love to use it to create desktop or mobile application with it :)

**Comment by Atinux** [comment]
I'm closing the issue since your project [vues](https://github.com/cj/vues) goes for mobile and desktop applications.

**Comment by InstanceOfMichael** [comment]
I still want this feature for debugging laravel dusk tests locally (not using an SSR server).
