### ISSUE TITLE
Support Windows OS building

### ISSUE THREAD

**Issue by theCrius** [nuxt/nuxt.js#5201]
### What problem does this feature solve?

Currently the default NPM scripts to build / serve use these scripts:

```
[...]
"dev": "nuxt",
"build:prod": "TARGET=prod nuxt build",
[...]
```

Problem is that Windows based machines will not load the .env file nor will knows what to do with that "TARGET=prod" line.

### What does the proposed changes look like?

The quick & dirty solution I used was to  add cross-env to the small project I was working as devDependency and change the scripts to use it, for example:

```
[...]
"dev": "cross-env TARGET=dev nuxt",
"build:prod": "cross-env TARGET=prod nuxt build",
[...]
```
This solves building for a specific environment but if you have multiple variables to load it would be quite messy.

For my specific purpose (having node env variables available in `nuxt.config.js` ) it would suffice to also have something like [motdotla/dotenv](https://github.com/motdotla/dotenv) library added in the devDependencies and require it at the start of `nuxt.config.js` but I don't know if this would solve other kind of use-cases out there.

The safer solution would definitely be to have `nuxt` be platform agnostic like `ng` is for Angular.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8805">#c8805</a>)</em></sub></div>

**Comment by aldarund** [comment]
@theCrius what do u mean by default npm scripts for nuxt?

**Comment by theCrius** [comment]
You're right, I should have worded it better but it's an hard monday :)

What I meant is that I think it would be "better" if, when we create a clean nuxt project from the CLI, the initial setup is platform agnostic, thus the  npm scripts for example, shouldn't assume I'll be on a unix-based system where `TARGET=prod` would work.

Now, I've seen that the official doc suggest using `cross-env` already so it's no big deal, but I think that for a widespread adoption, a tool should come with platform independence as far as it's possible.

So in short, let's say we add another dependency to nuxt, the default package.json should have already cross-env in devDependencies and the relative scripts should be something like `cross-env TARGET=prod`.
But, as I said, I'm for trying to keep the dependencies to a minimum so eventually the `nuxt` command itself could accept a new attribute, let's say `--target=something` or `--env=something` and knows what to do with it when building. like "build": "nuxt build --env=prod"`.

Now that would solve the `build` script but in case you want to actually use a `.env` file because you pre-process files in a node server that would require another approach, probably the esiest at that point is to include the *dotenv* library I linked before.

Hope it's clearer now, if not, I'll try tomorrow after I got some sleep :)

**Comment by aldarund** [comment]
@theCrius the thing is i have no idea what cli you are talking about. Because this is repo for nuxt itself. Official cli is a create nuxt app https://github.com/nuxt/create-nuxt-app and it already use cross-env which is platform agnostic
https://github.com/nuxt/create-nuxt-app/blob/master/template/_package.json#L10

**Comment by theCrius** [comment]
You're right, the weird thing is that I used `npx create-nuxt-app <project-name>` to create my nuxt project and I just checked back now the initial commit had this package json:

```
{
  "name": "<OMIT>",
  "version": "1.0.0",
  "description": "<OMIT>",
  "author": "<OMIT>",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "nuxt": "^2.3.4",
    "vuetify": "^1.3.14",
    "vuetify-loader": "^1.0.8",
    "@nuxtjs/axios": "^5.3.6"
  },
  "devDependencies": {
    "nodemon": "^1.18.9",
    "@nuxtjs/eslint-config": "^0.0.1",
    "babel-eslint": "^8.2.1",
    "eslint": "^5.0.1",
    "eslint-config-standard": ">=12.0.0",
    "eslint-plugin-import": ">=2.14.0",
    "eslint-plugin-jest": ">=21.24.1",
    "eslint-plugin-node": ">=7.0.1",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-vue": "^5.0.0",
    "eslint-config-prettier": "^3.1.0",
    "eslint-plugin-prettier": "2.6.2",
    "prettier": "1.14.3",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
  }
}
```

Anyway, given it already all in, this was just a silly issue, thanks for the patient to follow me along, this can be closed for me :)
