### ISSUE TITLE
Fetch only called when navigating from another route, not when route params change

### ISSUE THREAD

**Issue by lilianaziolek** [nuxt/nuxt.js#5208]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/wozw05xpqw](https://codesandbox.io/s/wozw05xpqw)

### Steps to reproduce

Navigate to home -> Navigate to any of the categories, e.g. products/lorem/ipsum, from there click on one of the links to navigate to another category, e.g. products/foo/bar.

### What is expected ?

Fetch should be called on both products/lorem/ipsum and products/foo/bar.

### What is actually happening?

Fetch is only called on products/lorem/ipsum, only watch is called when navigating to products/foo/bar
Note that when a user navigates back to index, and then navigates into category (i.e. route changes), then fetch is called again. It's only direct navigation between categories (when only route params change) that is a problem

### Additional comments?

Please clarify if this is expected behaviour - according to comment from @Atinux https://github.com/nuxt/nuxt.js/pull/5118#issuecomment-471930911_ it seems like fetch should be called on params changes, not just route changes.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8811">#c8811</a>)</em></sub></div>

**Comment by Atinux** [comment]
See my comment [here](https://github.com/nuxt/nuxt.js/pull/5118#issuecomment-471991497).

The new fetch is not available yet :)

**Comment by lilianaziolek** [comment]
@Atinux Is the new fetch going to be in Nuxt 3 only, or will it be ported into subsequent Nuxt 2 release as well?

**Comment by manniL** [comment]
@lilianaziolek Won't be backported as it contains breaking changes.

**Comment by lilianaziolek** [comment]
@manniL Thanks for confirming. Looking forward to Nuxt 3!
Should I close this issue, or would you like to keep it open and indicate it's resolved in Nuxt 3 once it's out?

**Comment by manniL** [comment]
I think closing it should be fine :relaxed:
