### ISSUE TITLE
nuxtServerInit working on dev but not production

### ISSUE THREAD

**Issue by FreddyCrugger** [nuxt/nuxt.js#5210]
Hello,

I have installed Nuxt.js v2.4.5 .

I cannot manage to get nuxtServerInit to work on production mode.

Here is my setup
![1](https://user-images.githubusercontent.com/6231274/54202665-d3deef80-44d0-11e9-8dcf-7bd956f37840.png)

In the state.js I have:

```
```
export default () => ({
  accessToken: null,
  rid: null,
  isLoggedIn: false,
  serverError: false
  // isLoading: false,
  // fullPage: true,
});
```

in the actions.js, I have:
```
export default {
  nuxtServerInit({commit}, {req}) {
    if ((this.$cookies.get('isLoggedIn') === true) && (this.$cookies.get('accessToken') !== undefined) && (this.$cookies.get('rid') !== undefined)) {
      commit('isLoggedIn', this.$cookies.get('isLoggedIn'));
      commit('setToken', this.$cookies.get('accessToken'), this.$cookies.get('rid'));
    } else {
      commit('isLoggedIn', false);
      this.$cookies.removeAll();
    }
    if (req) {
      console.log("This is nuxtServerInit " + req)
    }
  },
  },
```
```
When I generate the app via this command "nuxt", I land on my page, login and can refresh the page, the cookies are being read as the  nuxtServerInit  works as expected.

But when I run any of these 2 commands:
nuxt build or nuxt generate

I can login but on refresh the nuxtServerInit does not kick in.

I have been for hours on this, cannot work it out.

Any idea why please?

Thanks

**Comment by FreddyCrugger** [comment]
well my question is, is this a bug as I followed the NUXT website doc.

**Comment by 3tew** [comment]
> This [question](https://cmty.app/nuxt/nuxt.js/issues/c8813) has been resolved by [@aldarund](https://cmty.app/nuxt/aldarund), see [answer](https://cmty.app/nuxt/nuxt.js/issues/c8813#comment-5c87cccef714f1001402aad2).

I can't access the link, it's an error.
