### ISSUE TITLE
example(pug): not working in Nuxt 2.4.5

### ISSUE THREAD

**Issue by paulgeisler** [nuxt/nuxt.js#5212]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/pug](https://github.com/nuxt/nuxt.js/tree/dev/examples/pug)

### Steps to reproduce

```
git clone git@github.com:nuxt/nuxt.js.git
cd examples/pug
yarn install
yarn run dev
```

### What is expected ?

Build with no error.

### What is actually happening?

ERROR Failed to compile with 1 errors
This relative module was not found:

./about.vue?vue&type=template&id=0a606064&lang=pug& in ./pages/about.vue

### Additional comments?

https://github.com/nuxt/nuxt.js/issues/4822

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8814">#c8814</a>)</em></sub></div>

**Comment by paulgeisler** [comment]
I looked at the pull #4824 which should solve the problem and saw the `pug-loader` instead of `pug-plain-loader` wich is required if using `vue-loader` v15.

So the solution here is to use `pug-plain-loader`.

**Comment by manniL** [comment]
@paulgeisler Whoops! Sorry. Would you mind submitting a PR? :relaxed:

**Comment by paulgeisler** [comment]
Sure thing! 😁👍
