### ISSUE TITLE
how to prevent redirect when submit form and get 422

### ISSUE THREAD

**Issue by imsidz** [nuxt/nuxt.js#5213]
i am new in nuxt and can't solve the problem when i try to submit form for getting 422 error should not go anywhere and should show error on console but its redirecting in error page with content

> 'Request failed with status code 422
> An error occurred while rendering the page. Check developer tools console for details.'

how to prevent this

my code very is simple login

```
export default {
data() {
return {
form: {
email: '',
password: ''
}
}
},
methods: {
async submit() {
await this.$auth.login({
data: this.form
})
}
}
}
```

**Comment by imsidz** [comment]
i already posted to your website but no answer from your website 

here is link

[https://cmty.app/nuxt/nuxtjs.org/issues/c156](url)

**Comment by haideritx** [comment]
No solution to this problem.
Facing the same issue here :(

In my case i am using nuxt-auth

```
await this.$auth.loginWith("local",{
                    data: this.form
 });

```

**Comment by almokhtarbr** [comment]
@haideritx i have the same issue but when i use axios it works : 
``
       try {
             await this.$axios.$post('login',{email:this.email,password:this.password})
         } catch(e){
            console.log(e)
         }``

**Comment by victorronnow** [comment]
Any updates on this issue?

**Comment by imsidz** [comment]
yeah i catched the error like this
```
.catch(error => {
      console.log(error.response.data)
})
its working like a charm

<!--cmty_prevent_hook-->

**Comment by hsemanagementsoftware** [comment]
> yeah i catched the error like this
> 
> ```
> .catch(error => {
>       console.log(error.response.data)
> })
> ```
> 
> its working like a charm

worked for me as well. Thank you.

**Comment by muhohokenya** [comment]
its working like a charm. cheers
