### ISSUE TITLE
publicPath not reflect during `nuxt dev`

### ISSUE THREAD

**Issue by fbrbovic** [nuxt/nuxt.js#5216]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/rw6z54yrn?fontsize=14](https://codesandbox.io/s/rw6z54yrn?fontsize=14)

### Steps to reproduce

Provided codesandbox changes the ```build.publicPath``` from default to ```'_nuxt_2'```

Visit the codesandbox url  , open browser devtools and look at the network tab and see all of the 404 errors on ```/_nuxt_2/*``` resources

### What is expected ?

Changing the default ```/_nuxt/``` path for ```build.publicPath``` should deliver all of the build resources from new path. 

### What is actually happening?

While app client code is changed to reference the new path, nuxt server is not delivering those resources, it's resulting in 404 erros.

### Additional comments?

Maybe I am not fully understanding how ```build.publicPath``` should work but from my understanding it , changing it should also be able to deliver the resources from new path. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8816">#c8816</a>)</em></sub></div>

**Comment by manniL** [comment]
The build path works properly in production mode (after building the app with `yarn build`). It seems that it's not reflect during `nuxt dev` though.
