### ISSUE TITLE
vue-lazyload doesn't work properly in Nuxt

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#522]
Here's my example - http://many-winter.surge.sh/

If you go to that link, then go to Page Two, you'll see that all 4 image already loaded on the page. But if you refresh that Page Two, then Lazyload will work properly, and loading images one by one.

I want Nuxt not to preload all that images and not execute lazyload untill I go to Page Two.

How to fix it? Why is that happening?

```
<template>
  <section>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>

  </section>
</template>

<script>
import Vue from 'vue'

if (process.browser) {
  const VueLazyload = require('vue-lazyload')
  Vue.use(VueLazyload, {
    preLoad: 1,
    listenEvents: [ 'scroll' ],
    attempt: 1
  })
}

export default {
  data () {
    return {
      imgObj: {
        src: 'https://cdn-images-1.medium.com/max/1000/1*27_54ufzBoYXilrq_a6ChA.jpeg'
      },
      imgUrl: 'https://cdn-images-1.medium.com/max/1000/1*27_54ufzBoYXilrq_a6ChA.jpeg'
    }
  }
}
</script>

<style lang="scss"scoped>

img[lazy=loaded] {
  -webkit-animation-duration: 2s;
  animation-duration: 2s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
  -webkit-animation-name: fadeIn;
  animation-name: fadeIn;
}
@keyframes fadeIn {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}
</style>

```

**Comment by kodekrendel** [comment]
Just now tried to use `vue-lazyload` as plugin. Nothing changed :cry: 
It's working, but with this issue. With initial page load all image on OTHER pages are loaded too.

**Comment by ausir0726** [comment]
I think you have Misunderstood about lazyload ...
if you listen scroll event , that mean when pic on screen ( or close to ) then load pic ...
so , you need block space let screen keep away picture , and use different photo test .
I checked your source , first , you only loaded 1 pic , so , other pic will be fast show on screen .
and , you don't define img height ( I seen it height:auto ) so , if you don't have height ( or some Text )
that <img> tag will all in first screen and load it .

I tried it working , see this video gif
![lazyload](https://cloud.githubusercontent.com/assets/7247064/24813428/88d4b754-1c00-11e7-9a1f-8d14c8593198.gif)

**Comment by kodekrendel** [comment]
@ausir0726 sorry, but it seems that you doesn't understood what I am talking about. 

lazyload is working fine when I reload page. 

But if i FIRST load OTHER page, and THEN go to page with lazyload, then it ALREADY load ALL images.

**Comment by kodekrendel** [comment]
To understand what I am talking about you must repeat ALL this actions (otherwise you will not see the problem)

1. Go to http://many-winter.surge.sh/

2. Then go to Page Two (not mention to opacity animation, because it apply to ALL images at once, they are NOT lazy load, because they ALREADY on the page, all 4 images!!!). You will see that all images are on the page already (they suposse to load one by one when scroll).

3. But if you then refresh the Page Two, then everything willl work fine. Images will be load one by one.

4. If you want to repeat the process, then you have to start from / again. If you continue visout it you will get the WRONG impression that there is no problem (I guess it was your case). It is because if code bundling. Other words - you must start site navigation from any page beside Page Two (where lazyload are) - then you will see the bug.

**Comment by kodekrendel** [comment]
By the way. In nuxt/express EVERYTHING WORKS FINE. With the same code!

So the problem is with `npm run generate`. 

To be truth I am really tired of all this `generate` issue and just at one step to leave it and not to use this function.

**Comment by kodekrendel** [comment]
@ausir0726 I don't see nothing in your video related to my issue.

**Comment by kodekrendel** [comment]
About placeholder images and width - I know that, but it's not related. 
Repeat - in nuxt/express everything working like it should.

**Comment by ausir0726** [comment]
@kodekrendel  umm....
I think my English is not good for understand clear ...
anyway , I just want say if you use same pic and without height maybe is difficult see lazyload effect .

http://incompetent-smoke.surge.sh/
so , I put my example on surge.sh .

I watch the network console , It only when that pic close to screen then load on ineternet.
I refresh on my about page , then go to index , also have lazy load ...

**Comment by kodekrendel** [comment]
@ausir0726 no, it's my English bad to describe this issue :smile: 
I appreciate you help very much!

I tried different images, problem remains, just like I feel.
I will record video.

**Comment by kodekrendel** [comment]
@ausir0726 

https://www.youtube.com/watch?v=BMOt_7vjJRY

**Comment by kodekrendel** [comment]
@ausir0726 well, you was right (again). I just need to add height. Thank you :+1:

**Comment by ausir0726** [comment]
never mind 😺 

keep going , let nuxt.js amazing your site .

**Comment by kodekrendel** [comment]
@ausir0726 also, adding a fixed height actually don't **lazy**load images. I don't need actual lazyload, but if you need some kind of infinite scroll, then this fix is not working.

**Comment by ausir0726** [comment]
yes , 
but maybe you can give a min-height .
As much as possible don't let image ( close to ) on the screen ...

**Comment by kodekrendel** [comment]
Too bad, but min-height is not helping. I guess, I have to not use vue-lazyload, because it doesn't allow to use responsive image (NONSENSE!)
