### ISSUE TITLE
Strange Store plugin behavior with infinit store instances when console logging

### ISSUE THREAD

**Issue by christophwolff** [nuxt/nuxt.js#5222]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/christophwolff/store-infinit](https://github.com/christophwolff/store-infinit)

### Steps to reproduce

1. Clone the repo
2. npm install
3. npm run dev
4. look at the console
5. look at ~/plugins/infinit.js

Why is this?

![Bildschirmfoto 2019-03-13 um 10.38.58.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b36e8420-4577-11e9-b308-f95c4574340d.png)

### What is expected ?

Dont know for sure, but no infinit loop i think.

### What is actually happening?

An infinit Store instance is happening

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8821">#c8821</a>)</em></sub></div>

**Comment by manniL** [comment]
That's a normal circular reference. :relaxed: 

All `context` values are (if present) accessible in the Vuex store. As `app` is one of them and also contains `store`, the reference is there.

**Comment by christophwolff** [comment]
@manniL Learned something. Thanks!
