### ISSUE TITLE
After the successful launch of the local project, many CSS files JS files and pictures file errors 404

### ISSUE THREAD

**Issue by as236676674** [nuxt/nuxt.js#5229]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues](https://github.com/nuxt/nuxt.js/issues)

### Steps to reproduce

After the successful launch of the local project, many CSS files JS files and pictures file errors 404, the project has been no problem before the sudden like this.

### What is expected ?

Start the project normally. Don't make a mistake all of a sudden.

### What is actually happening?

Many files suddenly fail to find a path Error 404 after the project file is started

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8824">#c8824</a>)</em></sub></div>

**Comment by manniL** [comment]
No reproduction means we can't help you with that issue. This does not happen with a default project.
