### ISSUE TITLE
Native Apps / Integration with Weex

### ISSUE THREAD

**Issue by smyth64** [nuxt/nuxt.js#523]
Hey guys,
I really love the structure of NuxtJS and the Build System.

Is it possible to integrate NuxtJS into Weex or is there any other possibility to simply create native apps with Nuxt?

Weex: https://github.com/apache/incubator-weex/

Best Regards,
Smith

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c451">#c451</a>)</em></sub></div>

**Comment by irthos** [comment]
+1 for this or a better native solution. nuxt is very close to providing a true full-stack solution!

**Comment by smith64fx** [comment]
If Nuxt works with weex / cordova we can finally build ONE application for the web and for native devices! Awesome!

**Comment by pi0** [comment]
When `ssr: false` mode is stable enough `nuxt` + `nuxt generate` apps can be almost deployed to any HTTP-capable environment from embedded devices (Imagine home routers like dddwrt) to native applications :)) About native integration, i think we have two easier and less complex better alternatives: native-script and react-native :)) For both of them vue community made POCs so we may just wait until they become more stable.

**Comment by dohomi** [comment]
@pi0 it would be perfect if `nuxt` could be seen as the base codebase framework and further integrations to NativeScript/Weex/ReactNative would be possible without changing the project structure

**Comment by lukasborawski** [comment]
Any updates in here? Nuxt + NativeScript?

**Comment by smith64fx** [comment]
Vue + NativeScript already works, so let's to to Nuxt + NativeScript!

**Comment by galvez** [comment]
Closing this as there's been no updates over 90 days.

It's definitely on the table for talks.

**Comment by iBobik** [comment]
We are looking for a way how to generate web and mobile apps from one codebase, same components, but different navigation or native code.

NativeScript and Weex (or React Native) does not seems to fit beacuse it does not render HTML (without another layer like React Native Web) so if even possible will be very limiting on web.

For us [Capacitor](https://capacitorjs.com) could work - uses webview (backwards compatible with Cordova) but with native project ownership (Xcode project is in the repo), co can be easilly combined with native code.
