### ISSUE TITLE
Sockets:

### ISSUE THREAD

**Issue by IamTinashe** [nuxt/nuxt.js#5231]
> file:///C:/Project/io/index.js:1
> TypeError: Cannot read property 'renderer' of undefined at Object.<anonymous> (file:///C:/Project/io/index.js:4:44)

Got this error when I tried to use the [Sockets Example Here](https://github.com/nuxt/nuxt.js/tree/master/examples/with-sockets)

Anyone with a solution

**Comment by dikawai** [comment]
i have some issues also, i hope the author/member can fix it and re new documentations:D
