### ISSUE TITLE
Built in support for srcset?

### ISSUE THREAD

**Issue by thedamon** [nuxt/nuxt.js#524]
I notice that srcset doesn't seem to be supported.. if I add a srcset attribute the file will just not load.

Here it looks like this needs to be configured manually: https://github.com/vuejs-templates/webpack/issues/396

Would it make sense to have it supported out of the box since it's a standard?

**Comment by alexchopin** [comment]
Hi,
You can easily add loaders to the config by using `build.loaders` in your `nuxt.config.js` file to use `html-loader` or `vue-html-loader` and set the query parameter.
https://nuxtjs.org/api/configuration-build#loaders

**Comment by thedamon** [comment]
Thanks for the pointer! Though my concern was primarily that shouldn't it
be supported without having to customize config because it is part of HTML?

**Comment by apmontgomery** [comment]
I was also disappointed not to have this out of the box as responsive images are pretty important.  I don't see the documentation for loaders.  Is that gone now?  If so, can someone point me to the right place?

**Comment by iamdubx** [comment]
Jesus Christ please explain how to use `srcset`!!! Why it doesn't work?

**Comment by thedamon** [comment]
I haven't double checked but I think that it will work if you put the images in 'static' rather than assets so they don't get processed.

Is there a way to automatically handle responsive images with no setup though?  [Gatsby.js](https://using-gatsby-image.gatsbyjs.org/) offers this out of the box.
