### ISSUE TITLE
Remove data-test (ids) does not work on client bundle

### ISSUE THREAD

**Issue by iskanderbroere** [nuxt/nuxt.js#5250]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/iskanderbroere/removedatatestids](https://github.com/iskanderbroere/removedatatestids)

### Steps to reproduce

# Steps to reproduce
- npm run build
- compare client and server bundle (search for test `testattribute` in `.nuxt/`)
- data-test attribute is expected to be removed in both, but is only removed in the server bundle
# Reference
- https://forum.vuejs.org/t/how-to-remove-attributes-from-tags-inside-vue-components/24138/11
- https://gist.github.com/LinusBorg/6d9919904ca395b418c8a86648ca656b

### What is expected ?

Data test (id) attribute is removed in client bundle/

### What is actually happening?

The attributes remain on the element.

### Additional comments?

babel extend build preTransformNode

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8842">#c8842</a>)</em></sub></div>

**Comment by manniL** [comment]
No bug but a question :man_shrugging: 


**However**, there u go https://github.com/iskanderbroere/removedatatestids/pull/1

**Comment by iskanderbroere** [comment]
thanks for the explanation! does this mean https://nuxtjs.org/api/configuration-build#loaders-in-extend is incorrect and should be removed?

**Comment by iskanderbroere** [comment]
this issue only happens in nuxt >2.4, when i revert to 2.3.4 it works as i had initially expected it to.
https://github.com/iskanderbroere/removedatatestids/tree/nuxt2.3
can we document this change or fix it?
please re-open @manniL

**Comment by manniL** [comment]
>     * does this mean [nuxtjs.org/api/configuration-build#loaders-in-extend](https://nuxtjs.org/api/configuration-build#loaders-in-extend) is incorrect?

Not necessarily, but it's easier now  via `build.loaders.vue`


cc @clarkdo, maybe you know what's going wrong between v2.3 and v2.4 here :relaxed:

**Comment by clarkdo** [comment]
I’ll  have a look tmr.

**Comment by iskanderbroere** [comment]
Thanks for the effort guys
