### ISSUE TITLE
created() hook is running on server-side AND client-side

### ISSUE THREAD

**Issue by HapLifeMan** [nuxt/nuxt.js#5253]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/HapLifeMan/nuxt-ssr-created-issue](https://github.com/HapLifeMan/nuxt-ssr-created-issue)

### Steps to reproduce

1. Clone and install the repo
2. Run `yarn run dev` and see an error in full page
3. Run `yarn run build && yarn run start` and see that works but throws an error in the console

### What is expected ?

It is expected that the `created` hook is only executed once (from the SSR only) if the page is loaded from the server.

### What is actually happening?

The `created` hook is running on server-side AND client-side when loading a page.
If we mutate a variable in the `created`, the server-side will do it correctly, but when the client-side will do it, as the variable has been already mutated, it will not recognize it and throw an error.

It throws a full-page error in dev environment but only displays an error in the console in prod.

### Additional comments?

Thanks!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8843">#c8843</a>)</em></sub></div>

**Comment by manniL** [comment]
This is intended behavior. `beforeCreate` and `created` are called on server **and** on client side :wink:

Further read:
* https://blog.lichter.io/posts/the-guide-to-write-universal-ssr-ready-vue-compon/
* https://ssr.vuejs.org/guide/universal.html#component-lifecycle-hooks

**Comment by HapLifeMan** [comment]
Hi @manniL, then I will change the way I developed it, thanks for your reply! 😊
