### ISSUE TITLE
Add tests for decodeURI

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#5256]
Add tests for #4977, #5243

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8845">#c8845</a>)</em></sub></div>

**Comment by toshi1127** [comment]
@pi0 
I Added tests for #4977, #5243 .
I hope it makes sense!!

**Comment by clarkdo** [comment]
@toshi1127 Thank you!

@pi0 I closed this issue since @toshi1127 has added test, feel free to reopen it if I'm wrong.
