### ISSUE TITLE
Nuxt-link to dynamic children route not reload asyncData on client

### ISSUE THREAD

**Issue by webspilka** [nuxt/nuxt.js#5257]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/webspilka/nuxt-dynamic-route-bug](https://github.com/webspilka/nuxt-dynamic-route-bug)

### Steps to reproduce

go to /cars
-> cars/page/2 - its works for all pages except 1
-> /cars - nuxt-link not reload page with it data. It change only URL

### What is expected ?

Reload page 1 with load new asyncData, when click at nuxt-link

### What is actually happening?

Сlick at page N in pagination works well except page 1
Сlick at page 1 nuxt-link /car change only URL, but Data not reloads

### Additional comments?

Advise what can be done, otherwise I don’t even know what direction to look.
addition look at https://github.com/webspilka/nuxt-dynamic-route-bug or https://codesandbox.io/s/github/webspilka/nuxt-dynamic-route-bug/tree/master/

![dynamicRoutesBug.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/a9472670-4840-11e9-9865-f9ecd5dffa37.gif)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8846">#c8846</a>)</em></sub></div>

**Comment by webspilka** [comment]
until I found the next solution
replace route with children:
```js
router: {
    extendRoutes(routes, resolve) {
      routes.push({
        name: 'cars-brand',
        path: '/cars/:brandSlug?/:modelOrCitySlug?/:citySlug?',
        component: resolve(__dirname, 'pages/cars/index.vue')
        children: [
          {
            name: 'cars-brand-page',
            path: 'page/:page?',
            component: resolve(__dirname, 'pages/cars/index.vue')
          }
        ]
      })
}
  },
```

to flat route
```js
router: {
    extendRoutes(routes, resolve) {
      routes.push({
        name: 'cars-brand',
        path: '/cars/:brandSlug?/:modelOrCitySlug?/:citySlug?',
        component: resolve(__dirname, 'pages/cars/index.vue')
      })

      routes.push({
        name: 'cars-brand-page',
        path: '/cars/:brandSlug?/:modelOrCitySlug?/:citySlug?page/:page?',
        component: resolve(__dirname, 'pages/cars/index.vue')
      })
    }
  },
```
can someone tell me why children are not working in this case ?

**Comment by SHxKM** [comment]
@webspilka - hey, I'm looking to achieve the exact same things and have been trying without success for two days now. Are you using this with the page based routing, or are you using `router.js` file? For some reason extendRoutes is simply not working in my case.

**Comment by webspilka** [comment]
@SHxKM flat routes works for me

**Comment by Jones-S** [comment]
I think I have a similar problem.
If I understood you correctly you have a page that uses `asyncData` but when changing the route, which changes the slug of a dynamic nuxt-child, the `asyncData` is not triggered anymore...?!

This is what I have in my case.
I have a page, which uses `asyncData` to fetch a post. The post is then passed on as a property to the `nuxt-child`.

Whenever I navigate to another post (the nuxt-child would have to update), the `asyncData` on my parent page is not executed anymore...

Because I'd rather have nuxt handle my routes, I don't want to mess with child and flat routes. Is there not any other solution?
And could this ticket maybe reopened?

**Comment by eyvazoff** [comment]
@Jones-S same problem.

**Comment by SushyDev** [comment]
same problem here

**Comment by irakliShengelia** [comment]
Still facing this

**Comment by MoustaphaDev** [comment]
Still facing this in 2022. The closest I got to make it work was by doing this
```javascript
// [slug].vue

<script setup>
    const slug = computed(() => useRouter().params.slug))
    const {data, refresh} = await useAsyncData("my-post", () => $fetch(`https://example.com/api/posts/${slug.value}`))
    router.afterEach(() => {
      refresh();
    });
</script>


<template> {{data.postContent}} </template>
```

I say "the closest" because, the data refreshed only after two route changes.
It would've been great if we didn't have to worry about that, if it worked just like NextJS does.

**Comment by danielroe** [comment]
@MoustaphaDev you have defined a unique key (`my-post`) which means the data is linked between all dynamic pages.

Two possible solutions:
1. You can update the key to include the slug.
2. You can pass `watch: [slug]` to tell Nuxt to re-fetch the data when the slug updates.
