### ISSUE TITLE
History navigation not working

### ISSUE THREAD

**Issue by begueradj** [nuxt/nuxt.js#5258]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/begueradj/bug-nuxt-hashbang-history](https://github.com/begueradj/bug-nuxt-hashbang-history)

### Steps to reproduce

Call this method on click buttons to scroll down and up the same page:
```javascript
methods: {                                                                                                                                     
    moveToAnchor(hashbang) {                                                                                                                     
      this.$router.push(`#${hashbang}`)                                                                                                          
      this.$vuetify.goTo(`#${hashbang}`)                                                                                                         
      console.log(this.$route.hash)      // this gives me the right thing                                                                                                        
    }                                                                                                                                            
  }   
```

### What is expected ?

Navigating back and forward the browser history should work

### What is actually happening?

Clicking  on the browser's back or forward buttons does not move the page anywhere

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8847">#c8847</a>)</em></sub></div>

**Comment by manniL** [comment]
@begueradj Does it work in pure vue + vue-router? :thinking:

**Comment by begueradj** [comment]
I use only Nuxt.js but I will try it in Vue.js by the end of the day, thank you for the feedback.

**Comment by manniL** [comment]
@begueradj Just to make sure it's not a vue-router bug :relaxed:

**Comment by begueradj** [comment]
@manniL You were right, there is this same issue with Vue.js (vue-router). I will try to understand what is going on before reporting a bug to Vue.js team. Somehow I think `router.push()` expects only routes, not anchors within the same route. Thank you very much for the feedback, handsome and smart boy.

**Comment by manniL** [comment]
@begueradj Glad I could help :relaxed:
