### ISSUE TITLE
Undocumented difference between "universal" and "spa" mode when generating static site

### ISSUE THREAD

**Issue by dominikmontada** [nuxt/nuxt.js#5267]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/nuxt-community/auth-module](https://github.com/nuxt-community/auth-module)

### Steps to reproduce

1. Setup the auth demo
2. Generate static site in "universal" mode
3. Notice that login will not work
4. Generate static site in "spa" mode
5. Notice that login will work correctly now

### What is expected ?

Static site behaves the same, regardless of "universal" or "spa" mode

### What is actually happening?

There is a difference in the generated site when using "universal" mode vs "spa" mode.

### Additional comments?

This issue was originally discovered [here](https://github.com/nuxt-community/auth-module/issues/299). We noticed that the auth module does not work in static mode. The problem was that `$auth.state` always returned false, even after a successful login. We later discovered that this only occurs if the static site was generated with `mode` set to `universal` in `nuxt.config.js`.  When setting the mode to `spa` login worked correctly and `$auth.state` correctly returns the login state.

So somewhere there is a difference in the generated code for the static site. I'm not sure if this is intended behavior or a bug. If this is intended, it needs to be made clear in the documentation.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8852">#c8852</a>)</em></sub></div>

**Comment by dominikmontada** [comment]
Confirmed in `nuxt-edge@2.6.2-25912807.87fcf556`

### Steps to reproduce

1. Setup the auth demo
2. Generate static site in "universal" mode
3. Notice that login will not work
4. Generate static site in "spa" mode
5. Notice that login will work correctly now

**Comment by pi0** [comment]
Using `nuxt generate` in universal mode is not appreciate for _any dynamic content_ including authentication because server response is prerendered. Auth works fine in the standard universal mode using `nuxt start` so it would better idea using a hosting (either VPS or serverless) and running the nuxt server or using SPA mode.

**Comment by dominikmontada** [comment]
@pi0 Thank you for the explanation. The problem is not that auth is not working, it's that there is just a behavioral difference between static sites generated in spa or universal mode. In my opinion this should at least get documented, because as it is right now there are people (me included) who stumble upon this and are left wondering why these two are different. I would even argue that it is counter-intuitive for the generated output to be different depending on which mode was used.

**Comment by pi0** [comment]
@dominikmontada Right. Actually, this should be better to documented about static generate. But it is not either limited to auth or a _bug_ from auth module. I would suggest moving this issue to the docs repo. /cc @manniL

**Comment by codeofsumit** [comment]
I'm also very confused right now about `nuxt generate` in different modes.
E.g., fetching Data from an API and prerendering it does not work in spa mode, only universal mode
On the other hand, if I deploy the site through ZEIT zero config deployments, dynamic pages return a 404 after reload in universal mode. Spa mode works fine.

(I have used the `generate` prop in nuxt.config.js for dynamic route creation).

**Comment by codeofsumit** [comment]
I think there are more differences worth documenting. For example middlewares.

Statically rendered page in 
## Universal Mode:
Middlewares only execute on route navigation, NOT on initial page load.

## SPA Mode
Middlewares execute both, on page load and subsequent navigation
