### ISSUE TITLE
[help wanted] how to make a component compatible nuxt.js SSR

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxt.js#527]
hi , 

I want write a component , publish on npm 
but , even I don't write any thing , I got error 
`[nuxt.js] Cannot load components TypeError: Cannot read property 'toLowerCase' of undefined`

```js
//mycomponent.js
const MyComponent = {
  install: function(Vue, options) { }
};
module.exports = MyComponent;
```
index.vue
```html
import Vue from 'vue';
const mycomponent = require('./mycomponent.js');
Vue.use(mycomponent);
```
If I want compatible nuxt.js SSR , do I need implement what ?
have any one can give some reference ? 
thanks.

**Comment by alexchopin** [comment]
Hi, 
Build a nuxt.js component is the same as a vue.js compenent.
One of the solution in your case is to build your component as UMD bundle.
You can use template like: https://github.com/monterail/vue-component-template

**Comment by ausir0726** [comment]
@alexchopin  thanks. I will try to study .

**Comment by ausir0726** [comment]
@alexchopin  can I ask if I want code only on SSR 
how can I write on component ?
I tried ` if ( window ) `
I got `ReferenceError: window is not defined`

**Comment by ausir0726** [comment]
sorry I find the way out ...
use
```js
if (typeof window !== 'undefined')
```

**Comment by ausir0726** [comment]
@alexchopin  thanks for help
let me made a first component .
and don't have get warning without use process.BROWSER_BUILD
awesome ~

but , that template is use webpack 1 , maybe I need more time to upgrade webpack 2

[vue2-recaptcha-invisible](https://www.npmjs.com/package/@finpo/vue2-recaptcha-invisible)
[demo](https://vue2-recaptcha-invisible.surge.sh/)
