### ISSUE TITLE
window.__NUXT__ text on display

### ISSUE THREAD

**Issue by Berkmann18** [nuxt/nuxt.js#5270]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/Berkmann18/nuxty](https://github.com/Berkmann18/nuxty)

### Steps to reproduce

1. npm run generate
2. Open ./dist/index.html on a live server
3. See what's being shown on the page

### What is expected ?

Page with a title "nuxty" with a "My CMSed Static Nuxt Project" subtitle with blog posts links underneath (although I can't see the blog links on `localhost:3000`).

### What is actually happening?

The page is blank with a `window.__NUXT__={layout:"default",data:[{}],error:null,serverRendered:!0,apollo:{defaultClient:Object.create(null)}}` in the centre ([in staging](https://optimistic-agnesi-3c1c5c.netlify.com/)) and nothing (just a blank page) when running a live server.

### Additional comments?

It might be related to a problem with DatoCMS where https://graphql.datocms.com/ resolves in 401 despite having correctly set the `Bearer ...` token (which works fine on https://graphql.datocms.com/graphiql).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8856">#c8856</a>)</em></sub></div>

**Comment by manniL** [comment]
Please create a minimal reproduction of the issue :relaxed:

**Comment by Berkmann18** [comment]
@manniL I'll get on it ASAP and see if I can reproduce the error.

**Comment by clarkdo** [comment]
@Berkmann18 The wrong generated html is because of apollo auth failed with error `Network error: Response not successful: Received status code 401`

If you comment the `apollo` module, you can see the correct html then, so you can fix the authentication error and test again.

**Comment by Berkmann18** [comment]
@clarkdo I've done that but when I run `npm run dev`, the page renders **expect** the blog part which is due to an error `[Vue warn]: Property or method "allPosts" is not defined on the instance [...]`.
The token and the URL used on Apollo work fine when used in isolation from Nuxt.
I was thinking of testing on `npm run build` as well but I guess I would get the same (or a similar) error>

Am I doing something wrong?

**Comment by Berkmann18** [comment]
@stale[bot] Still happening.

**Comment by clarkdo** [comment]
@dohomi I think this issue is related to apollo module, could you please have a look ?

@Berkmann18 Since this issue is happened in apollo module, if you can open an issue in that repo, it would be better 😃

**Comment by dohomi** [comment]
Hi 

the config is wrong addressed, in case you have a specific token to pass you have to use a file based config like this:
```
// plugins/my-alternative-apollo-config.js
export default function(context){
  return {
    httpEndpoint: 'http://localhost:4000/graphql-alt',
    getAuth:() => 'Bearer my-static-token' // use this method to overwrite functions
  }
}
```
Its described inside of the config section of the apollo module.

**Comment by Berkmann18** [comment]
@dohomi How is using `http://localhost:4000` going to work in production and staging while being connected to the DatoCMS's GraphQL layer (which is in https://graphql.datocms.com)?

And the `https://graphql.datocms.com` `httpEndpoint` with my DatoCMS's bearer token works on GraphiQL as shown below, so I'm unsure what's wrong in my (minimal) repo.

![image](https://user-images.githubusercontent.com/8260834/56725847-8dbeb200-6745-11e9-9e59-fa6b12dfb962.png)

**Comment by dohomi** [comment]
@Berkmann18 this is the hint about the config: https://github.com/nuxt-community/apollo-module#options

https://github.com/Berkmann18/nuxty/pull/1 You'd need to replace endpoints based on which environment/infrastructure you are on.
