### ISSUE TITLE
upgrade nuxt.js from v.1.4.5 to v2.4.5 and the setInterval problem

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt.js#5271]
### What problem does this feature solve?

The purpose of this issue is mostly to document my issue and help people in the future tackle the situation by documentation and/or suggestions.

I had a project on v1.4.5 for a while and tried to upgrade to v2.4.5. Upon doing this my `nuxt generate` hung with the following warning
```
   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ⚠ Nuxt Warning                                                                │
   │                                                                                 │
   │   The command 'nuxt generate' finished but did not exit after 5s                │
   │   This is most likely not caused by a bug in Nuxt.js                            │
   │   Make sure to cleanup all timers and listeners you or your plugins/modules     │
   │   start.                                                                        │
   │   Nuxt.js will now force exit                                                   │
   │                                                                                 │
   │   DeprecationWarning: Starting with Nuxt version 3 this will be a fatal error   │
   │                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────╯
```

Reaching out on discord @SnooHD was able to point out some `setInterval`'s that were not being destroyed properly, and should possibly also be wrapped around stuff like `if (process.browser)`, once those were in place , `yarn generate` was working successfully:

https://github.com/acidjazz/oneconcern/commit/a04cca5519fba5220933cf8611001b7506c86d53

### What does the proposed changes look like?

I'm not quite sure the exact solution, maybe a hint inside this warning, or a documentation update?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8857">#c8857</a>)</em></sub></div>

**Comment by manniL** [comment]
Isn't 

> Make sure to cleanup all timers and listeners you or your plugins/modules start

enough? :thinking:

**Comment by acidjazz** [comment]
@mbajur sure, that works.

**Comment by SnooHD** [comment]
What I would want to add is the fact that when this interval is initiated in `created()` we get this warning. Yet if we initiate the interval in `mounted()`, there is no warning.
Both cases where using a `clearInterval` in `beforeDestroy()`.

**Comment by manniL** [comment]
@SnooHD You better should not do so (as explained in https://blog.lichter.io/posts/the-guide-to-write-universal-ssr-ready-vue-compon/)

**Comment by SnooHD** [comment]
@manniL thanks for sharing that post, that clears things up!

**Comment by acidjazz** [comment]
@manniL @SnooHD great stuff, should this potentially be somewhere in the docs? timers and where they belong?

**Comment by manniL** [comment]
@acidjazz Probably in a new "SSR caveats" section. It's already noted for the next doc version :relaxed:

**Comment by acidjazz** [comment]
@manniL if it's noted elsewhere i'm happy to close this, unless you want to keep it open as a reminder

**Comment by manniL** [comment]
Gonna close this here. @acidjazz 	feel free to open an issue in https://github.com/nuxt/docs/ through CMTY :relaxed:
