### ISSUE TITLE
Nuxt is packaged as an external chain. Is there a configuration you can refer to?

### ISSUE THREAD

**Issue by bigHead-zhu** [nuxt/nuxt.js#5275]
To optimize seo, you need to package pages JS and CSS as external introductions. Is there a way to achieve this? 
![image](https://user-images.githubusercontent.com/30432817/54583548-7e19c280-4a4f-11e9-90e0-c2361ecfd481.png)

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8861">#c8861</a>)</em></sub></div>

**Comment by mauxtin** [comment]
I think you are looking for this https://nuxtjs.org/api/configuration-build/#filenames
