### ISSUE TITLE
The error layout is inconsistent with the general layout structure.

### ISSUE THREAD

**Issue by Abel94** [nuxt/nuxt.js#528]
Error layout:
```vue
<template>
  <section class="warpper">
    // ...
  </section>
</template>
```
Render results
```html
<section class="container">
  <section class="warpper">
     // ...
  </section>
</section >
```

Default layout: 
```vue 
<template>
  <section class="warpper">
    // ...
  </section>
</template>
```

Render results
```html
  <section class="warpper">
     // ...
  </section>
```

**Error layout outer layer more than one container.**

**Comment by alexchopin** [comment]
Hi,
`layouts/error.vue` is a page and `layouts/default.vue` is a layout.
It's a tricky difference, I can understand the misunderstanding due to the layout folder.
https://nuxtjs.org/guide/views#layouts

**Comment by Abel94** [comment]
hi, @alexchopin  Thank you for answering me.
So should the error.vue be moved to the pages folder?

**Because container led to my layout a little problem, how should I customize it?**

**Comment by Abel94** [comment]
Sorry, the second question has been found in the link you provided.
