### ISSUE TITLE
Middleware throws "Cannot set headers after they are sent to client"

### ISSUE THREAD

**Issue by brandonaaskov** [nuxt/nuxt.js#5282]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/j3xp2n8y8v](https://codesandbox.io/s/j3xp2n8y8v)

### Steps to reproduce

1. Create middleware to send a response to the client before the template renders
2. See that, even when not calling `next()`, there's still an error in the console

### What is expected ?

The response would be sent to the client and the middleware chain terminated.

### What is actually happening?

"ERROR  Cannot set headers after they are sent to the client"

### Additional comments?

This came about because I'm trying to return an RSS feed, and I need access to the store to do that. Thus it's in middleware and not serverMiddleware. It's my understanding that returning and not calling `next()` should work, but I get this error every time.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8867">#c8867</a>)</em></sub></div>

**Comment by manniL** [comment]
1. `req` and `res` are only available on server-side. Your middleware would fail on client-side navigation
2. Why do you need the `store` for returning the RSS feed? Can't you use cookies or similar to get whatever you need?
3. I suggest `serverMiddleware` here, or *even better*, an own API proxied to sth. like /feed
4. That's not a Nuxt bug. It's not expected to short circuit / end the response there (see #1).

**Comment by brandonaaskov** [comment]
@manniL I beg to differ on #1, the objects are definitely there, and it definitely renders as expected, it just throws that benign error. It's even provided in the auth0 example, you can see `req` being used right there: https://github.com/nuxt/example-auth0/blob/master/middleware/check-auth.js

And as you can see in the Codesandbox link, using `res.end()` _does_ work, so they're obviously not just available server-side since middleware is used client-side, and [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware/) is used server-side. "Don't confuse it with routes middleware which are called before each route by Vue in Client Side or SSR. Middleware listed in the serverMiddleware property runs server-side before vue-server-renderer and can be used for server specific tasks like handling API requests or serving assets."

So the request and response objects are _definitely_ available. [Here, they're documented as server-only](https://nuxtjs.org/api/context/) but in the auth0 example they're in the routing middleware... so.... which is it?

**Comment by manniL** [comment]
@brandonaaskov Keep in mind that the code in https://github.com/nuxt/example-auth0/blob/master/middleware/check-auth.js is almost 2 years old. Nuxt has changed a lot since then.

I never said that your middleware won't work "at all". On the initial request, everything will go well as shown in your CSB. When you go from /about -> /your-feed-route for example, things will crash as `req` and `res` are not defined.
Middleware is executed on server-side on the **initial request** (similar to asyncData).

Of course you can go the same way as in the auth0 example and use req if defined, otherwise grab stuff from localStorage. But I don't think that you should change the response fundamentally (e.g. no HTML) through a middleware.

**Comment by carbdias** [comment]
hello, how would you defined a new header in the HTTP response in a route middleware (it will be applied only to one specific page) in Nuxt 3 ?
I'm seeing headers can be edited in server middleware but then, there, they are applied to all the resquests and not associated to a specific page.
