### ISSUE TITLE
How to use async/await proposal?

### ISSUE THREAD

**Issue by Darkside73** [nuxt/nuxt.js#529]
I'm aware of webpack config extending but how to actually replace default babel preset with babel-preset-stage-3?

**Comment by alexchopin** [comment]
Nuxt is using [babel-preset-vue-app](https://github.com/vuejs/babel-preset-vue-app) by default and allows you to use async/await in your app.
If you want to change it, please have a look on the documentation: https://nuxtjs.org/api/configuration-build/#babel
