### ISSUE TITLE
asyncData() is not executed after changing route query using $router.push

### ISSUE THREAD

**Issue by togishub** [nuxt/nuxt.js#5295]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/38pzrn9nk1](https://codesandbox.io/s/38pzrn9nk1)

### Steps to reproduce

1. Navigate to https://38pzrn9nk1.sse.codesandbox.io/?page=1
2. Notice "current route path" and "asyncData was excecuted for route" values in page
3. Click button "change route query", which will change route query using this.$router.push({ query: { page: rand_int } })
4. Notice, that the route (page URL) has changed, but asyncData() was not executed for the new page

### What is expected ?

asyncData() should be executed for new route, even if just query param value changes. in this case ?page=

### What is actually happening?

URL changes, but new page load cycle is not started, thus asyncData() is not executed too

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8871">#c8871</a>)</em></sub></div>

**Comment by henriqemalheiros** [comment]
You must enable the `watchQuery ` property on the page component.  You can read about it [here](https://nuxtjs.org/api/pages-watchquery).

**Comment by manniL** [comment]
As @henriqemalheiros said :relaxed:

**Comment by togishub** [comment]
thank you for a quick response! Added watchQuery: ["page"] export default {}, however even in asyncData() seems to be executed, it's results are not returned to page (mount does not happen). Am I missing something else here again?

**Comment by ouyangfan** [comment]
@togishub How can I use the watchQuery property?thank you

**Comment by ouyangfan** [comment]
My problem is that URL changes don't want to update data asynchronously.

**Comment by ouyangfan** [comment]
My problem is that query parameter changes don't want to update data asynchronously.

**Comment by togishub** [comment]
ouyangfan, my example now includes working code with watchQuery property: https://codesandbox.io/s/38pzrn9nk1 

see code at:
`<script>
export default {
  watchQuery: ["page"]

`

can you share you code? I may be able to help you
