### ISSUE TITLE
 WARN  build.extractCSS.allChunks has no effect from v2.0.0. Please use build.optimization.splitChunks settings instead. 

### ISSUE THREAD

**Issue by heshamelmasry77** [nuxt/nuxt.js#5298]
why i am getting this issue !

**Comment by heshamelmasry77** [comment]
> This issue as been imported as [question](https://cmty.app/nuxt/nuxt.js/issues/c8872) since it does not respect [nuxt.js issue template](https://cmty.app/nuxt/issues/new?repo=nuxt.js). Only bug reports and feature requests stays open to reduce maintainers workload.
> If your issue is not a question, please mention the repo admin or moderator to change its type and it will be re-opened automatically.
> Your question is available at https://cmty.app/nuxt/nuxt.js/issues/c8872.

the most shitty bot ever after one year and i am still searching for this bug !

**Comment by Hancoson** [comment]
What is the solution?

**Comment by gabrielsze** [comment]
Bump

**Comment by mrniamster** [comment]
is there any solution to this  yet?
