### ISSUE TITLE
$router Optional query parameters 

### ISSUE THREAD

**Issue by baturali** [nuxt/nuxt.js#5305]
### What problem does this feature solve?

The main problem I am experiencing is the unnecessary query parameters inside `$router.replace()`. Now, assuming I am inserting multiple parameters or a JSON object inside the `query:`, some of the paramters might have null, undefined or empty values. It would be great if we had an option to simply avoid showing these parameters in the URL if they are not wanted.

### What does the proposed changes look like?

As an example I have the below `replace()`
```
const hasBrandQuery = 'brandIds: 5'
const hasProductQuery = null
this.$router.replace({
  query: {
    hasBrandQuery,
    hasProductQuery
  }
})
```
The problem I have with the code above is that I don't want `hasProductQuery` to be shown in my URL, simply because it has no specific value and it should only show `hasBrandQuery`.
I think this would be a good feature if we had an option to enable such a thing.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8879">#c8879</a>)</em></sub></div>

**Comment by manniL** [comment]
Please improve your feature request. I don't fully understand what you want to do :thinking:

**Comment by baturali** [comment]
> Please improve your feature request. I don't fully understand what you want to do 🤔

Hello @manniL, thanks for your prompt response. I have updated my request.

**Comment by manniL** [comment]
Hey @baturali :wave: 	

Thanks for the update! I think that feature request should be added directly to `vue-router` which Nuxt is using under the hood :relaxed: 	

https://github.com/vuejs/vue-router

PS: This is already "resolvable" in userland by looping over the object entries and removing empty ones.
