### ISSUE TITLE
Run dev-debug is not working

### ISSUE THREAD

**Issue by baturali** [nuxt/nuxt.js#5308]
### Version

[v2.5.0](https://github.com/nuxt.js/releases/tag/v2.5.0)

### Reproduction link

[https://github.com/baturali/nuxt-dev-debug](https://github.com/baturali/nuxt-dev-debug)

### Steps to reproduce

Clone the project and run>
yarn
yarn run dev-debug

### What is expected ?

The debugging process should work as expected.

### What is actually happening?

I receive the error below:

$ yarn run dev-debug
yarn run v1.13.0
$ node --inspect node_modules/.bin/nuxt
Debugger listening on ws://127.0.0.1:9229/1a9f338a-2040-4011-84c5-88f7b37e522e
For help, see: https://nodejs.org/en/docs/inspector
C:\Users\user\Desktop\Dev\debug-try\node_modules\.bin\nuxt:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Additional comments?

Any idea why this happens?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8880">#c8880</a>)</em></sub></div>

**Comment by ndan** [comment]
Unable to reproduce it on macOS

**Comment by baturali** [comment]
> Unable to reproduce it on macOS

Its just starter template of Nuxt.js me only added the dev-debug script on package.json.
So you can try to build a new project with following these steps: https://nuxtjs.org/guide/installation and
add that line on package.json file in scripts > "dev-debug": "node --inspect node_modules/.bin/nuxt"

**Comment by Al-Rozhkov** [comment]
I have the same problem on Windows 10.

**Comment by baturali** [comment]
Dev-debug works fine on Mac with v2.5.0 but still not on Windows.

**Comment by noe132** [comment]
Actually, on Windows, the nuxt executable was `./node_modules/.bin/nuxt.cmd`.
On MacOS it's `./node_modules/.bin/nuxt`.
If you take a look the content of these two files, despite lines and syntax which is platform specific, then you'll find out it's executing `./node_modules/nuxt/bin/nuxt.js`.

So, just simply change your dev-debug script to `node --inspect ./node_modules/nuxt/bin/nuxt` then you have no problem debugging your code on both platforms.

**Comment by Manieck** [comment]
I have the same problem on Windows 10.

**Comment by aldarund** [comment]
@Manieck https://github.com/nuxt/nuxt.js/issues/5308#issuecomment-482698759
