### ISSUE TITLE
element.eleme.io tooltip crash head

### ISSUE THREAD

**Issue by SnowSphinx** [nuxt/nuxt.js#532]
I found a bug ( with last nuxt and http://element.eleme.io/#/en-US/component/tooltip tooltip component. 

When y include it on any vue.js page it crash header after reopen it (first open is ok).
F.e. Y open page index next go to about with tooltip and page has no head (f.e. title).

Some elements like tooltip crash nuxt( With clear vue.js all works fine)

**Comment by Atinux** [comment]
This is an issue related to Element-UI directly, please report this bug for SSR on their Github @SnowSphinx

**Comment by ausir0726** [comment]
@SnowSphinx 

this issue also happen on el-table .
already report on element issue ,
maybe you can add your tooltip issue reproduction at that issue 
this link -> https://github.com/ElemeFE/element/issues/4207
