### ISSUE TITLE
更改folder导致js不执行

### ISSUE THREAD

**Issue by jason65** [nuxt/nuxt.js#5329]
npm run generate以后，生成的文件夹重新调整了一下导致js不执行

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8890">#c8890</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@jason65 能否提供一个可以重现问题的仓库?
