### ISSUE TITLE
error core-js

### ISSUE THREAD

**Issue by ALNY-AC** [nuxt/nuxt.js#5336]
![image](https://user-images.githubusercontent.com/20777182/54816178-93e8eb00-4cce-11e9-8901-d24da4628e13.png)
![image](https://user-images.githubusercontent.com/20777182/54816189-9a776280-4cce-11e9-8744-fe41010cf76e.png)

**Comment by ALNY-AC** [comment]
"nuxt": "^2.5.1",
 "vue": "^2.5.17"

**Comment by pi0** [comment]
Hi. Can you please follow these steps:

- Remove `yarn.lock` / `package-lock.json`
- Add `core-js@2`
- Ensure to `.babelrc` or `babel.config.js` or babel config in `nuxt.config` exists

**Comment by ivandata** [comment]
Hello pi0!
This is little bit weird if core-js@2 is dependence of nuxt.js and users will need to add them manually.

**Comment by pi0** [comment]
@ivandata It is a dependency of nuxt indeed! But will be hoisted by yarn/npm if some other dependency requires `core-js@3`. Adding to top-level package.json prevents this.

**Comment by pi0** [comment]
More explained in [2.6.0](https://github.com/nuxt/nuxt.js/releases/tag/v2.6.0) notes.

**Comment by ivandata** [comment]
got it, thank you!

**Comment by aa-ziyi** [comment]
yarn add core-js
如果还不行
删除 node_modules,然后使用 yarn 安装，不要使用 cnpm 安装；

**Comment by Austio** [comment]
@pi0 is the recommendation to still use corejs 2 with it being deprecated?  If so what are the reasons for the strong recommendation in that changelog?

Thanks!
