### ISSUE TITLE
Using @nuxt/typescript overrides any existing tsconfig.json file

### ISSUE THREAD

**Issue by sambowler** [nuxt/nuxt.js#5338]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/0qmykr7wq0](https://codesandbox.io/s/0qmykr7wq0)

### Steps to reproduce

Using the official Nuxt with TypeScript example on CodeSandbox:
- Adjust the `tsconfig.json` in any way
- Restart the sandbox

TS support will be detected again and any modifications to `tsconfig.json` will be overridden.

### What is expected ?

The existing `tsconfig.json` is unmodified.

### What is actually happening?

The `tsconfig.json` content is overridden.

### Additional comments?

I've also noticed that the generation of the `tsconfig.json` doesn't seem to respect the `srcDir` setting in the Nuxt config.

For some background: we have a setup where we use TS for our server-side code and our Nuxt code in the same repo. At present, we have a `tsconfig.json` in the root for our server code and then a separate `tsconfig.json` for our Nuxt setup in a subdirectory (which is ignored by the first config file).

Since 2.5.0 our root `tsconfig.json` is being overridden by the automatically generated one. I don't think this would cause any issues if it respected the `srcDir` config option (i.e. generated it in the subdirectory) although it seems feasible to me that people may want to modify their config and overriding it every time may not be the best option.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8900">#c8900</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
Hi @sambowler, we're gonna switch back to the old behavior which was extending a `tsconfig.json`.

Overriding tsconfig.json was not a good Idea (FYI it doesn't exactly overrided but add missing values in it).

The main issue we have is that we need to take root `tsconfig.json` for runTime support (nuxt.config.ts / serverMiddlewares), and `tsconfig.json` from `srcDir` for webpack related TS files (vue components, plugins).

Thanks for your feedback, it will be closely taken into account. I will refer this issue when I'll open the PR which brings better TS integration.

**Comment by husayt** [comment]
@kevinmarrec 
Since latest it doesn't   like `"extends": "@nuxt/typescript-edge",` line in tsconfig.json. What is the right value for that?

**Comment by kevinmarrec** [comment]
@husayt, just removing it should work

**Comment by Al-un** [comment]
@husayt May it help, I had some custom values to add to `tsconfig.json`. I removed everything and left only an empty JSON: `{}` like in [this example](https://github.com/nuxt/nuxt.js/blob/dev/examples/typescript/tsconfig.json). 

After a build / generate, `tsconfig.json` is populated with some values. I then added my custom values back and it works (the [tsconfig.json link](https://github.com/Al-un/nuxt-ts/blob/master/tsconfig.json) after being populated and updated)
