### ISSUE TITLE
Performance. Adding express-static-gzip for precompressed files

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [nuxt/nuxt.js#534]
Hello and thank you for nuxt!

You recently added [compression](https://github.com/expressjs/compression) for dynamic creation of gzip files for every request that nodejs server receives. Nodejs is already not the most effecient web server and making it to dynamically build gzip files is questionable to enable.

**Comment by OlzhasAlexandrov** [comment]
Had to edit the initial comment, because I suggested incompatible middleware for connect(not express).

How about [adding express-static-gzip to nuxt](https://github.com/tkoenig89/express-static-gzip)?

**Comment by OlzhasAlexandrov** [comment]
Just found out that I personally didn't need this feature, since there is already [publicPath](https://nuxtjs.org/api/configuration-build/#publicpath) which allows to set a folder and serve gzip static files through a reverse-proxy server, like nginx with `gzip_static on;`

On the other hand, if you want to support situations, when nodejs directly serves files, then it might be a good idea to add precompressed file support

**Comment by Atinux** [comment]
Hi @OlzhasAlexandrov 

Thank you for your suggestion but this might be too complicated for most users.

I believe this could be a nuxt plugin in the future like `nuxt-static-gzip` which will run the command `find . -type f ! -name "*.gz" | while read -r x; do gzip -c9 "$x" > "$x.gz"; done` or something similar and then add the [express-static-gzip](https://github.com/tkoenig89/express-static-gzip) middleware to `nuxt.render`.

I add this issue in the Project to keep this idea and close this issue.
