### ISSUE TITLE
nuxt generate removes the dist folder, breaking a (potential) docker mount

### ISSUE THREAD

**Issue by RickvdStaaij** [nuxt/nuxt.js#5344]
### What problem does this feature solve?

Hi, I'm building a static website with Nuxt, and in my docker-compose file I mount the dist folder (generated by `nuxt generate`) directly into a static html docker container. The problem is that when `nuxt generate` runs, it completely removes the `dist` folder and then rebuilds the `dist` folder. This breaks the docker mount and I'm unable to view the contents of the container.

### What does the proposed changes look like?

In [here](https://github.com/nuxt/nuxt.js/blob/2.x/packages/generator/src/generator.js#L162) the `dist` folder is hard removed. It would be nice if there can be a setting in the "generate config" to trash or empty the `dist` folder

`generate.removeDist`: True (default) / false 
- `true`: Removes the dist folder like it does now, making sure everything is gone
- `false`: Empties all the resources in the dist folder, but keeping the dist folder itself alive

Hope this can be done. Thank you for the nice framework!

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8903">#c8903</a>)</em></sub></div>

**Comment by RickvdStaaij** [comment]
Temporary workaround:

`Dockerfile`
```
FROM nstapelbroek/static-webserver:latest

COPY . /opt/work-around-dir

RUN rm -rf /var/www && ln -s /opt/work-around-dir/dist /var/www
```
`.dockerignore`
```
# Ignore everything...
**

# ...but keep files/dirs:
!/dist
```

**Comment by pimlie** [comment]
Although some more flexibility in nuxt dist folders would be nice (especially atomic replacement of dist folder), I do think that this is essentially a problem which should be fixed in the docker container you use and not in nuxt.

Eg if you would set [`generate.dir`](https://nuxtjs.org/api/configuration-generate#dir) to `docker/dist`, bind `./docker` as volume to `/var/www/` and have the nginx vhost point to `/var/www/dist` instead of `/var/www` everything should work as you propose.

**Comment by Ti-webdev** [comment]
The same for `options.buildDir`. 
https://github.com/nuxt/nuxt.js/blob/8907e1553fc35c5d6b8ed869e1f573629ab2d296/packages/builder/src/builder.js#L146

With Docker volume it throws error:
```
[fatal] EBUSY: resource busy or locked, rmdir '/app/.nuxt'
```

**Comment by TimvdEijnden** [comment]
I'd like to fix this
