### ISSUE TITLE
Some advices on making nuxt more programmatic friendly

### ISSUE THREAD

**Issue by mamboer** [nuxt/nuxt.js#536]
Hi, guys,
I'm using `nuxt` programmatically in an express project,  and met some unpleasant experiences.

1.  The `> Open http://127.0.0.1:3000` log is misleading

![image](https://cloud.githubusercontent.com/assets/85879/24836350/46a005d0-1d4c-11e7-85f4-17bc78ac1d70.png)

The server is served by `express` not `nuxt` at `http://localhost:8088` in this case.

Advice No.1: `nuxt` should provide a way to suppress this logs.

2. Event-Oriented Programming but not just `callback`

In order to capture the time when `nuxt` has completed its `webpack` compiling job, currently i've to write a webpack plugin and plug it into the configs of `nuxt`, it's hacked..

```
/**
 * webpack plugin for capturing nuxt's building process
 * https://github.com/webpack/docs/wiki/plugins
 */
class XWebpack extends EventEmitter {
  constructor (opts) {
    super()
    this.opts = opts || {}
  }
  apply (compiler) {
    let timer = null
    compiler.plugin('done', (stats) => {
      clearTimeout(timer)
      timer = setTimeout(() => {
        if (!stats.hasErrors() && !stats.hasWarnings()) {
          // clear the nuxt output
          xconsole.clearConsole()
          this.emit(this.EVENTS.done)
        }
      }, 500)
    })
  }
  get EVENTS () {
    return {
      'done': 'done'
    }
  }
}
```

The ideal usage should look like,

```
var nuxt = new Nuxt(opts)
nuxt.on('compiled', () => {
    // let user rocks here
})
```
Advice No.2 is: Let `nuxt` emit those key events for further programmatic usage.

**Comment by pi0** [comment]
Hi @mamboe. Thanks for your suggestion, indeed Nuxt programmatic API and architecture has been improved a lot in past weeks and we are working on Docs to add new usage info. As a summary:

**For logs**
Now almost every

**Comment by pi0** [comment]
Hi @mamboe. Thanks for your suggestion, indeed Nuxt programmatic API and architecture has been improved a lot in past weeks and we are working on Docs to add new usage info. As a summary:

**New architecture and Tapable Hooks**

Nuxt is splitted into 3 main packages: Builder(builder, generator), Common and Core(renderer, moduleContainer, nuxt). Nuxt is the main glue and all of those classes extend from [tapable](https://github.com/webpack/tapable) so we can make plugins for Nuxt just like webpack and listen to all events during Nuxt lifecycle. Also the preferred to add this hooks is using modules. Some WIP docs for getting started:

- https://github.com/nuxt/docs/blob/1.0/en/guide/modules.md
- https://github.com/nuxt/docs/blob/1.0/en/api/internals-builder.md

**Logs**

Now almost everything about logs is refactored to use [debug](https://github.com/visionmedia/debug) so you can easily disable logs. Also that `OPEN` message just appears only if we call to `nuxt.listen()` which is not normally used for programatic usage.

Hope provided info helps, we are trying to ship docs for more examples soon.
