### ISSUE TITLE
npm start error 【serve/index.js    params promise is undefined】

### ISSUE THREAD

**Issue by zlgb-wow** [nuxt/nuxt.js#5369]
### Version
v2.3.2 (koa)
### Reproduction link
init project 
### Steps to reproduce

1. npx create-nuxt-app nuxt-demo
2. npm install
3.  npm run build
4. npm start
5. Server side reported promise. Then method not found, in the server/index.js print, found the promise parameter is undefined
### What is expected ?
Hope NPM start works properly
### What is actually happening?
`app.use(ctx => {
    ctx.status = 200 
    return new Promise((resolve, reject) => {
      ctx.res.on('close', resolve)
      ctx.res.on('finish', resolve)
      nuxt.render(ctx.req, ctx.res, promise => {
        // **promise is undefied**
        promise.then(resolve).catch(reject)
      })
    })
  })`
### Additional comments?
I hope the authorities can pay attention to it, which leads to difficulties in deployment

**Comment by zlgb-wow** [comment]
> This issue as been imported as [question](https://cmty.app/nuxt/nuxt.js/issues/c8914) since it does not respect [nuxt.js issue template](https://cmty.app/nuxt/issues/new?repo=nuxt.js). Only bug reports and feature requests stays open to reduce maintainers workload.
> If your issue is not a question, please mention the repo admin or moderator to change its type and it will be re-opened automatically.
> Your question is available at https://cmty.app/nuxt/nuxt.js/issues/c8914.

fuck

**Comment by hassan-jahan** [comment]
Same issue here. Could you fix this problem?

**Comment by hassan-jahan** [comment]
I created a new Nuxt project then copied its /server folder to the current project. 

It was fixed now!

**Comment by clarkdo** [comment]
@zlgb-wow 

`nuxt.render` is a reference of [`connect.js`](https://github.com/senchalabs/connect/blob/master/index.js#L51), unfortunately there is no `promise` as a parameter of the callback, so you may try:

```js
app.use((ctx) => {
  ctx.status = 200
  return new Promise((resolve, reject) => {
    ctx.res.on('close', resolve)
    ctx.res.on('finish', resolve)
    nuxt.render(ctx.req, ctx.res, err => err ? resolve() : reject(err))
  })
})
```
