### ISSUE TITLE
Nuxt custom babel plugin not working

### ISSUE THREAD

**Issue by Kleemer** [nuxt/nuxt.js#5373]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/yw0k156zzz](https://codesandbox.io/s/yw0k156zzz)

### Steps to reproduce

I forked this working link : https://codesandbox.io/s/18j0jkn72q then added the plugin `babel-plugin-jsx-remove-data-test-id` from here https://github.com/coderas/babel-plugin-jsx-remove-data-test-id
I also added `data-test-id="test1"` on one of the elements displayed.

### What is expected ?

The plugin should strip out this attribute.

### What is actually happening?

The plugin doesn't actually work.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8918">#c8918</a>)</em></sub></div>

**Comment by manniL** [comment]
@Kleemer 	Happy to see you found my example ☺️ 	

I'm not sure if the babel plugin you mentioned works with normal vue templates. Probably not as it seems.

You might be interested in #5250

Closing here as it's no direct Nuxt issue

**Comment by Kleemer** [comment]
Thank you for the quick answer and the help ! This is what I was looking for.
Keep up the awesome work !! 😄
