### ISSUE TITLE
EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.

### ISSUE THREAD

**Issue by Wang-Yang** [nuxt/nuxt.js#5375]
安装nuxt之后npm run dev, chrome控制台报错：EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.

**Comment by psahni** [comment]
@danielroe 
Any update on this please

**Comment by psahni** [comment]
@Wang-Yang 
Did u able to solve it?
