### ISSUE TITLE
Nuxt 2.5.1: promise is undefined

### ISSUE THREAD

**Issue by l2aelba** [nuxt/nuxt.js#5377]
I am using Nuxt in Firebase hosting, so I do something like

```js
function handleRequest(req, res) {
  res.set('Cache-Control', 'public, max-age=1, s-maxage=1');
  return new Promise((resolve, reject) => {
    nuxt.render(req, res, (promise) => {
      // promise is undefined
      promise.then(resolve).catch(reject);
    });
  });
};
app.get('*', handleRequest);
app.use(handleRequest);
exports.ssr = functions.https.onRequest(app);
```
And I get something like 

![Screenshot 2019-03-25 at 13 28 05](https://user-images.githubusercontent.com/983458/54919733-dc3c1f00-4f01-11e9-83a3-7dd260b809d8.png)

And I debuged so I found ```promise``` is undefined after I upgraded to this version.

I am missing something?

Thanks.

**Comment by pi0** [comment]
If you are using programmatic API, did you added nuxt.ready() to the constructor?

**Comment by l2aelba** [comment]
Any example? @pi0

**Comment by l2aelba** [comment]
@pi0, Hi again. Thanks so much. So I do something like this.

Can you review this is a right way to do?

```
function handleRequest(req, res) {
  res.set('Cache-Control', 'public, max-age=300, s-maxage=600');
  return new Promise((resolve, reject) => {
    nuxt.render(req, res, (promise) => {
      nuxt.ready(() => {
        promise.then(resolve).catch(reject);
      })
    });
  });
};
```

**Comment by pi0** [comment]
This may not directly answer your question. This may be probably because nuxt callbacks are depricated. Anyway, this could work:

```js
function handleRequest(req, res) {
  res.set('Cache-Control', 'public, max-age=1, s-maxage=1');
  return nuxt.render(req, res)
}

app.get('*', handleRequest);
app.use(handleRequest);
exports.ssr = functions.https.onRequest(app);
```

Another version:

```js
async function handleRequest(req, res) {
  res.set('Cache-Control', 'public, max-age=1, s-maxage=1');
  await nuxt.render(req, res)
}
```

`nuxt.render` returns a Promise which could be returned.

**Comment by l2aelba** [comment]
Yeah thanks, But In my case I have to add `nuxt.ready()` after `new Nuxt()`
Like..

```
const nuxt = new Nuxt(config);
nuxt.ready().catch(console.error);

// function handleRequest(req, res) { .... }
```

**Comment by TobiasEmil** [comment]
Hi @l2aelba
I have encountered the same problem after updating some npm packages. 

I have tried the following:

```
const nuxt = new Nuxt(config)

nuxt.ready();

async function handleNuxtRequest(req, res) {
  res.set('Cache-Control', 'public, max-age=1, s-maxage=1');
  await nuxt.render(req, res);
}

app.use(handleNuxtRequest)

exports.httpOnRequest = functions.runWith({
    timeoutSeconds: 300,
    memory: '1GB'
}).https.onRequest(app)
```

However i get an error of
"ERROR SSR renderer is not initialized! Please check ..\functions\nuxt\dist\server existence." even though the folder exists.

I have updated nuxt to "^2.5.1" in the functions folder however i have not jet updated the package in the Nuxt src folder as i get an error when trying to build the nuxt app: "You may need an appropriate loader to handle this file type"
So for this reason the nuxt app itself is version "^2.3.4" for now

How is your project structured? How do your build an serve the nuxt app though Firebase hosting?

**Comment by pi0** [comment]
@TobiasEmil Sorry for this issue. We have pushed some changes to make it even more stable for v2.6.0. You can try `nuxt-edge` to see if it works.

**Comment by l2aelba** [comment]
@pi0 And one more question
I'm using Firebase hosting / functions

Sometimes when there is no visitor a while, I get ```Cannot GET /``` but when reloaded again so it's back.

Seems like Firebase does it warm when no visitor.

Do you have any trick to prevent this?

**Comment by pi0** [comment]
The trick to avoiding `Cannot GET /` during cold start, would be something like [this trick](https://github.com/nuxt/now-builder/blob/master/lib/launcher.js#L37) that I've used for now serverless. Can be something like this:


```js
const nuxt = new Nuxt(config);

let isReady = false
const readyPromise = nuxt.ready().then(() => {
  isReady = true
}).catch(() => {
  process.exit(1)
})

async function handleRequest(req, res) {
  if (!isReady) {
    await readyPromise
  }
  res.set('Cache-Control', 'public, max-age=1, s-maxage=1');
  await nuxt.render(req, res);
}

```
