### ISSUE TITLE
Can I get title and meta dynamically and globally?

### ISSUE THREAD

**Issue by snoopy83101** [nuxt/nuxt.js#5380]
### What problem does this feature solve?

Can I get title and meta dynamically and globally?

And the title and meta are still global defaults (and obtained through axios)

Because asyncData cannot be used in layout, head () can only be static in layout.

You can customize it in pages, but I need the global default

It's global in nuxt. config, but it can't get dynamic data through Axios

How can I do it?

我能否需要动态获取title和meta,而且还是全局?
而且这个title和meta还是全局默认的(而且是通过axios获取到的)

因为在layout中无法使用asyncData, 因此在layout中head()只能是静态的.
在pages中可以自定义,但我需要全局默认
在nuxt.config中是全局的,但是他又不能通过axios获取动态数据

我该如何来做呢?

### What does the proposed changes look like?

Perhaps you can allow asyncData to be used in layout?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8925">#c8925</a>)</em></sub></div>

**Comment by manniL** [comment]
You'd have to do it page-wise then :|

**Comment by snoopy83101** [comment]
@manniL 

Really?  asyncData will be  everywhere?

when?

**Comment by manniL** [comment]
See #5118.
Closing here as it's WIP
