### ISSUE TITLE
Typescript support does not respect the rootDir parameter in nuxt.config.js

### ISSUE THREAD

**Issue by Exeteres** [nuxt/nuxt.js#5381]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/Exeteres/nuxt-issue](https://github.com/Exeteres/nuxt-issue)

### Steps to reproduce

1. restore dependencies and run start task
2. look at tsconfig.json, it should be overridden by nuxt
3. look at terminal, error should be here

### What is expected ?

I want to use two tsconfig.json. One for backend at the root of the project and one for nuxt in src/ui. I expected that nuxt will use rootDir option from nuxt.config.js

### What is actually happening?

Nuxt created tsconfig.json at the root of the project, but uses tsconfig.json from src/ui, which does not exist.
![Screenshot_20190326_084306.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/77960cb0-4f6e-11e9-bf7f-e35f65b0b416.png)

### Additional comments?

I think I found a code fragment, which contains a bug
https://github.com/nuxt/nuxt.js/blob/e5369db2d539cf580e9ce609e895c67bc01c9b3c/packages/cli/src/command.js#L93
![Screenshot_20190326_084618.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/a7a44bb0-4f6e-11e9-bf7f-e35f65b0b416.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8927">#c8927</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@Exeteres 

About `tsconfig.json`, it won't be overridden anymore in #5367 

For the `rootDir` thing, the issue is that if the user is using a `nuxt.config.ts`, we need to register `ts-node` before reading it to successfully read it, and we can't know `rootDir` before reading it, that's why we use the `tsconfig.json` found where `nuxt` is run for now.

I don't have clues for now to handle this, I'll need to take more time to see if a solution really can be found, even if I already spent lot of time looking for one. So if you got any idea I'm all ears :)

**Comment by kevinmarrec** [comment]
@Exeteres , further notes :

Nuxt will always look for the `tsconfig.json` in same folder as `nuxt.config.js` (or `nuxt.config.ts`) to initialize TypeScript support. You can then configure the `forkTsCheckerWebpackPlugin` (which is your current issue) through `build.typescript.typeCheck` following options here : https://github.com/Realytics/fork-ts-checker-webpack-plugin#options

like
```
export default {
  rootDir: './src/ui'
  build: {
    typescript: {
      typeCheck: {
        tsconfig: './src/ui/tsconfig.json'
      }
    }
  }
}
```

But be aware you need to create the full `tsconfig.json` within `./src/ui`, Nuxt won't autogenerate or override it, it only handles root one.

**Comment by Exeteres** [comment]
@kevinmarrec , Thanks for your answer and explanation.

I found simple solution how to isolate nuxt from the other part of the project.
I just moved nuxt.config to src/ui and deleted rootDir option.
It's like a subproject.
![1](https://user-images.githubusercontent.com/29506045/55043867-a4042000-506a-11e9-84fd-a3e4e27ea473.png)
