### ISSUE TITLE
favicon.ico did not show when prod env

### ISSUE THREAD

**Issue by Kylin93CN** [nuxt/nuxt.js#5385]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/Kylin93CN/pieceOfCode/blob/master/nuxt.issue.js](https://github.com/Kylin93CN/pieceOfCode/blob/master/nuxt.issue.js)

### Steps to reproduce

on linux server, i clone the project, then run "yarn run build" and "pm2 start npm --name "cygy-www" --watch  -- run start",
use nginx reverse proxy reflex on port 3000, visti domain， the favicon did not  show

### What is expected ?

the favicon.ico   show

### What is actually happening?

 the favicon did not  show

### Additional comments?

 the favicon.ico   showed on dev env.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8931">#c8931</a>)</em></sub></div>

**Comment by vanpipy** [comment]
Hi, i tried to reproduce and lost the any resources except the index, no matter product or development environment.
But i found an error in `nginx.conf` that `proxy_pass https://internal.ip:port;`. Missing a `/` after the port and everything goes wrong. Fix to `proxy_pass https://internal.ip:port/;`, it's gonna be all right.
So is any possible with nginx?

---
Nuxt  ^2.4.0
Nginx 1.14.0

**Comment by Kylin93CN** [comment]
hello,vanpipy 
i want to know where is favicon.ico after builded, i can't find it in .nuxt/build/client
and my nginx.conf is>

```shell
server {
        listen  80;
        server_name www.ycygy.cn; #绑定域名
        gzip            on;
        gzip_types      text/plain application/xml text/css application/javascript;
        gzip_min_length 1000;
        location / {
            proxy_pass http://127.0.0.1:3000;  ## 指定端口号 3000
        }
                error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```

**Comment by vanpipy** [comment]
I got it, here is the document to explain it. it is [Nuxt static](https://nuxtjs.org/guide/assets#static).

> All included files will be automatically served by Nuxt and are accessible through your project root URL. (static/favicon.ico will be available at localhost:3000/favicon.ico)

Follow this, the `favicon.ico` is still in the directory static.

**Comment by Kylin93CN** [comment]
okay,i  had solved the issue.

on nginx.conf,  i should add
```shell
#Point to the project root directory
root         /home/ycygy/www-ycygy;
```
 then 'https://www.xx.com/favicon.ico'  can be Point nuxtProject/static
