### ISSUE TITLE
<nuxt-link> does not convert to <a> tag in SSR mode

### ISSUE THREAD

**Issue by Art-Mas** [nuxt/nuxt.js#5388]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/kojlj6z65r](https://codesandbox.io/s/kojlj6z65r)

### Steps to reproduce

Paste this piece of code anywhere in the project

```
<div>
    <template v-for="t in [1]">
      <div :key="t">
        <a v-if="false" :href="'/test'" v-html="'<div>bug</div>'"></a>
        <nuxt-link :to="'/test'" v-else>V ELSE</nuxt-link>
      </div>
    </template>
  </div>
```

### What is expected ?

<nuxt-link> will be converted in &lt;a&gt; in SSR mode

### What is actually happening?

<nuxt-link> returns after SSR as is. This raises a warning: _[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside &lt;p&gt;, or missing &lt;tbody&gt;. Bailing hydration and performing full client-side render._

### Additional comments?

If you remove `v-html` from the &lt;a&gt; tag, the error disappears

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8934">#c8934</a>)</em></sub></div>

**Comment by manniL** [comment]
Not sure why you are applying such a complex pattern. `nuxt-link` will be converted to `a` on SSR automatically.

However:

```vue
<template>
  <div>
    <a v-if="check" href="/test" v-html="'<div>bdug</div>'"/>
    <nuxt-link to="test" v-if="!check">V ELSE</nuxt-link>
  </div>
</template>

<script>
export default {
  data() {
    return {
      check: false
    };
  }
};
</script>
```

works

```vue
<template>
  <div>
    <a v-if="check" href="/test" v-html="'<div>bdug</div>'"/>
    <nuxt-link to="test" v-else>V ELSE</nuxt-link>
  </div>
</template>

<script>
export default {
  data() {
    return {
      check: false
    };
  }
};
</script>
```

does not.

Might be a vue-server-renderer bug or similar but not related to Nuxt directly I think

**Comment by michaelpumo** [comment]
As far as I am aware, this is because `v-else` only really works if the prior tag with the `v-if` is of the same element type.

In this case, `a` and `nuxt-link` are not considered the same, even though in the end they will be rendered as such.
