### ISSUE TITLE
Bug when delete page

### ISSUE THREAD

**Issue by orblazer** [nuxt/nuxt.js#5389]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

Not really needed

### Steps to reproduce

1. Create nuxt app with `npx create-nuxt-app <project-name>`
2. Run dev mode
3. Create new page
4. Delete this page

### What is expected ?

This just delete route without an error (this need delete in same time in routes)

### What is actually happening?

This produce an error :
```
 ERROR  Failed to compile with 1 errors                                                                       friendly-errors 14:59:23


 ERROR  in ./src/pages/test.vue                                                                               friendly-errors 14:59:23

Module build failed (from ./node_modules/eslint-loader/index.js):                                             friendly-errors 14:59:23
Error: ENOENT: no such file or directory, open '/home/orblazer/.../pages/test.vue'
                                                                                                              friendly-errors 14:59:23
 @ ./.nuxt/router.js 25:24-27:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8935">#c8935</a>)</em></sub></div>

**Comment by 516310460** [comment]
Whether the project was successfully rerun after deletion
