### ISSUE TITLE
Duplicate call extendRoutes

### ISSUE THREAD

**Issue by orblazer** [nuxt/nuxt.js#5391]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

Not really needed

### Steps to reproduce

1. Create nuxt app with `npx create-nuxt-app <project-name>`
2. Create module like https://pastebin.com/gSkQUiKg
3. Run in dev mode
4. Update `nuxt.config.js`

### What is expected ?

Just call one time the `extendRoutes`

### What is actually happening?

Call multiple time `extendRoutes`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8937">#c8937</a>)</em></sub></div>

**Comment by manniL** [comment]
wrap that in a nuxt hook like `build:before` to control execution more fine-grained.

**Comment by orblazer** [comment]
@manniL I don't know how i can make that, i have tried with just
```js
this.nuxt.hook('buid:before', () => {
  this.extendRoutes(routes => {
    console.log('ok')
  })
})
```

But this is not work.

**Comment by manniL** [comment]
you are missing an `l` in `build`

**Comment by orblazer** [comment]
@manniL yes i have missing only on copy but it is right in the code ;)
