### ISSUE TITLE
Unexpected token export (Arrow function in class)

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt/nuxt.js#5392]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/782yo8n5q](https://codesandbox.io/s/782yo8n5q)

### Steps to reproduce

With the latest update my class stopped working when using short functions.
I assume something broke with core-js revert?

```
export default class Test {
  constructor(data) {
    console.log("Does it work?");
  }
  // These two will crash the whole app. Worked before.
  isUnset = o => typeof o === "undefined" || o === null;
  isSet = o => !this.isUnset(o);
}
```

When converted to this format, it works.

```
  isUnset (o) {
    return typeof o === 'undefined' || o === null
  }
  isSet (o) {
    return !this.isUnset(o)
  }
```

### What is expected ?

App works, or gives better error.

### What is actually happening?

Unexpected token export

### Additional comments?

But the weird part was that when i tried to revert even when i removed package-lock and node-modules folder i couldn't get the old version work either.

Found another one that does not work.
```
  sendBounce = _.debounce((c) => {
    this.send()
  }, 3000)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8940">#c8940</a>)</em></sub></div>

**Comment by manniL** [comment]
The problems aren't the arrow functions but that you are using them in classes. You are using (unintentionally I guess?) private field syntax which is not supported by default. You'd have to add a babel plugin for it.

However, I suggest to write normal functions in classes or using an object :)

---

Not a Nuxt issue ☺️

**Comment by kingda** [comment]
@manniL I got the same error,which babel plugin should i add ?

**Comment by manniL** [comment]
Seems like this is changed behavior. More in #5400
