### ISSUE TITLE
Will you consider separating server-side code from client-side code in the future?

### ISSUE THREAD

**Issue by 651778286** [nuxt/nuxt.js#5398]
### What problem does this feature solve?

Often confusing server-side code and client-side code when use nuxt.
It raises the bar for beginners.
A good framework like nuxt should not have such problems

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8945">#c8945</a>)</em></sub></div>

**Comment by qm3ster** [comment]
lmao

**Comment by manniL** [comment]
Please elaborate your request a little :relaxed:
