### ISSUE TITLE
Async requests on generated output

### ISSUE THREAD

**Issue by danielo515** [nuxt/nuxt.js#540]
Hello,

I'm evaluating nuxt to see if it fits my needs to build my portfolio.
I'm interested on static site generation, because most of the content will be static (my creations, my cv, some blog posts...) but I also want to supercharge it with some SPA capabilities.
This means, that apart from serving the static pages, I want to be able to make requests to external JSON apis, or request static JSON files to my gh-pages.

I'm still fighting agains the static site generations. Seems that `nuxt-link` is not a good fit for static generated sites.For example, If I open the generated index.html file, none of the links works properly.

What I want is the following layout:

```
- INDEX 
-- NavBar
--- content <- changes dinamically
--footer
```

Is this a good idea? Does it make sense? Is nuxt a good fit for it?

Let's imagine that I can live with full page reload when I navigate between pages. Once the page that has some API component is rendered, can I make APi calls  and parts of the page?

Thanks in advance.

**Comment by alexchopin** [comment]
Hi, If you want to use dynamic content in a static page, you should use dynamic component from Vue.
http://vuejs.org/v2/guide/components.html#Dynamic-Components

**Comment by danielo515** [comment]
For now what I'm using is vuex + actions
The thing is that I don't want to wait for user interaction to trigger an apiCall. Dispatching actions on create it's working fine for now.

Regards.
