### ISSUE TITLE
class property does not work in v2.5.1

### ISSUE THREAD

**Issue by ymmooot** [nuxt/nuxt.js#5400]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://not-needed.com](https://not-needed.com)

### Steps to reproduce

```bash
$ npx create-nuxt-app nuxt-app
$ cd nuxt-app
```

Modify  `/pages/index.vue`.

```vue
<template>
  <section class="container">
    {{ name }}
  </section>
</template>

<script>
class Sample {
  static NAME = 'Alice'
}

export default {
  data() {
    return {
      name: Sample.NAME
    }
  }
}
</script>
```

Start Nuxt.js app

```bash
$ npm run dev
```

### What is expected ?

Start the application and create the instance having data: `{name: 'Alice'}`.

### What is actually happening?

Throw an Error: SyntaxError Unexpected token export

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8946">#c8946</a>)</em></sub></div>

**Comment by ymmooot** [comment]
@clarkdo thank you for checking my pull request.
Here is the reproduce repository.

https://github.com/ymmooot/reproduce-5400

**Comment by kiaking** [comment]
FYI、This happens when mode is set to `universal`. Mode `spa` will work just fine.

**Comment by Arnique** [comment]
Having the same problem. App crashes whenever I add properties to my classes.

A simple example here [https://codesandbox.io/s/jv34jj5wl5](https://codesandbox.io/s/jv34jj5wl5)

I don't understand why this was closed since switching to spa is not option for everyone.

**Comment by Arnique** [comment]
So this was closed? I'm a bit lost.

**Comment by kiaking** [comment]
@Arnique The PR to fix this issue was merged but the new version of Nuxt is not out yet. You need to wait until the next release.

**Comment by Arnique** [comment]
> 
> 
> @Arnique The PR to fix this issue was merged but the new version of Nuxt is not out yet. You need to wait until the next release.

Thanks for working on this.

For now I got it to work by installing `babel-plugin-transform-class-properties` and adding it in the config i.e

```
build: {
    babel: {
        plugins: ['babel-plugin-transform-class-properties']
    }
}
```
