### ISSUE TITLE
Nuxt-child is missing error handler from Nuxt component.

### ISSUE THREAD

**Issue by mrcrille** [nuxt/nuxt.js#5409]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/5y4wzx0ox4](https://codesandbox.io/s/5y4wzx0ox4)

### Steps to reproduce

- Go to the url `/article/291`
- Page is created to show an 404 error page. (If you get this error the problem is fixed)
- Page shows article page without showing 404 error page.

### What is expected ?

The page should display the 404 error page called by
asyncData() using the error() function.

### What is actually happening?

It shows the page content and ignores the error() call.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8957">#c8957</a>)</em></sub></div>

**Comment by aldarund** [comment]
Why use nuxt-child in default layout?

**Comment by mrcrille** [comment]
@aldarund That's a good question, I used it because it fixed an error from the UI framework but now when I think about it, this issue explains why it fixed it. 

Also when I take a look at the code of nuxt-child it seems like the nuxt components only reason to exists is to show errors.
