### ISSUE TITLE
Coffeescript Vuex silently stop working on 2.5.1

### ISSUE THREAD

**Issue by chiboreache** [nuxt/nuxt.js#5423]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/coffeescript](https://github.com/nuxt/nuxt.js/tree/dev/examples/coffeescript)

### Steps to reproduce

Build project with `"nuxt":  "2.5.1"`

### What is expected ?

Vuex that works with Coffeescript, just like on 2.4.5

### What is actually happening?

Nothing.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8960">#c8960</a>)</em></sub></div>

**Comment by kyrsquir** [comment]
I would also note that if I enable module store in the [coffeescript example](https://github.com/nuxt/nuxt.js/tree/dev/examples/coffeescript) by adding a file /store/module.coffee
```
export state = ->
  message: 'Hello CoffeeScript Module Store!'
```
and try to reference it in pages/index.vue
```
export default
  components: { Logo }
  computed:
    message: ->
      console.log @$store.state.module.message  
      @$store.state.message
```
I get
```
ERROR  [Vue warn]: Error in render: "TypeError: Cannot read property 'message' of undefined"
```

**Comment by weotch** [comment]
It appears to have broken a little earlier than reported above, I see it broken in 2.5.0

**Comment by weotch** [comment]
I've been digging into the code and I'm not use exactly where it broke, but I've found changing [resolveFiles()](https://github.com/nuxt/nuxt.js/blob/dev/packages/builder/src/builder.js#L293-L298) to this:

```js
  async resolveFiles(dir, cwd = this.options.srcDir) {
    const extensions = this.supportedExtensions.concat(this.nuxt.options.extensions)
    return this.ignore.filter(await glob(`${dir}/**/*.{${extensions.join(',')}}`, {
      cwd,
      ignore: this.options.ignore
    }))
  }
```

fixes the issue; the coffeescript store module gets found.  

The above is a clunky solve not worthy of a PR, but should point out the problem is that `this.nuxt.options.extensions` isn't taken into account when Nuxt looks for store modules.  However, this is the practice described in [the coffeescript example](https://github.com/nuxt/nuxt.js/blob/dev/examples/coffeescript/modules/coffeescript.js#L2-L3).

**Comment by weotch** [comment]
I have a workaround that I published to my CoffeesScript Nuxt module package: https://github.com/BKWLD/nuxt-coffeescript-module/commit/143656e53ffba7b9c2c334a85a0ba8e7f648965b.  This fixes this VueX issue for me but doesn't fix the issue with CoffeeScript local modules #5087

**Comment by chiboreache** [comment]
nah

```sh 
ERROR  Identifier 'STATUS' has already been declared                                 19:10:36

  const STATUS = {
  ^
  
  SyntaxError: Identifier 'STATUS' has already been declared
  at Module._compile (internal/modules/cjs/loader.js:760:23)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
  at Module.load (internal/modules/cjs/loader.js:685:32)
  at Function.Module._load (internal/modules/cjs/loader.js:620:12)
  at Module.require (internal/modules/cjs/loader.js:723:19)
  at require (internal/modules/cjs/helpers.js:14:16)
  at _import (node_modules/@nuxt/cli/dist/cli-chunk.js:49:36)
  at builder (node_modules/@nuxt/cli/dist/cli-chunk.js:62:23)
  at NuxtCommand.getBuilder (node_modules/@nuxt/cli/dist/cli-chunk.js:2672:31)
  at Object._startDev (node_modules/@nuxt/cli/dist/cli-chunk6.js:82:31)
  at processTicksAndRejections (internal/process/task_queues.js:86:5)
 
```


just edited `.../node_modules/@nuxt/builder/dist/builder.js`

My guess extend webpack config via `build: extend = (config, ctx) ->` will be more correct way

**Comment by chiboreache** [comment]
workaround is working like a charm too!

**Comment by manniL** [comment]
Feel free to create a PR for the example to make it work too.

**Comment by weotch** [comment]
I wasn't sure if my workaround _should_ be the right solve for this ... like, ideally, I feel like Nuxt should use the `this.nuxt.options.extensions` for the `builder.supportedExtensions` as well.  It wasn't clear to me where the most elegant way to implement this into the core should be, though.

**Comment by chiboreache** [comment]
@manniL hey did you fixed coffeescript linter issue of your CI ?
