### ISSUE TITLE
can not find : ./node_modules/nuxt/bin/nuxt start

### ISSUE THREAD

**Issue by aebrs** [nuxt/nuxt.js#5424]
Hi, We have updated our nuxt.js version to 2.4.0, it seems that in this version folder ./node_modules/nuxt/bin/nuxt-start and start script is removed, is it true? Then what is replaced? Any help link? Thanks in advance.

**Comment by pi0** [comment]
Hi @aebrs. Please also install `nuxt-start` package.

**Comment by aebrs** [comment]
1- Thanks.
2- I installed it on server and yet can not run my web site.
I am using pm2 like this:
module.exports = {
  apps : [
      {
        name: "nuxt",
        script: "./node_modules/nuxt-start/bin/nuxt-start",
        env: {
            "HOST": "127.0.0.1",
            "PORT": 3000,
            "NODE_ENV": "production",
        }
      }
  ]
}
would it be chaned too?

**Comment by pi0** [comment]
@aebrs If you need to directly set path to `nuxt-start` binary, yes

**Comment by aebrs** [comment]
Any sample on how to use?
In Programmatic Usage there is some code mentioned but there is no sample or help about best place o this sample code. No sample code for using pm2 and so on.
May you give some hand?

**Comment by aebrs** [comment]
should it mixed with server.js : 

const express = require('express');
const { Nuxt, Builder } = require('nuxt');
const config = require('./nuxt.config.js');
const app = express();
app.listen(process.env.PORT || 3000);
config.dev = false;
const nuxt = new Nuxt(config);
app.use(nuxt.render);
new Builder(nuxt).build().catch(err => {
  console.error(err);
  process.exit(1);
});

**Comment by manniL** [comment]
@aebrs 	Please fill out a correct bug report :wink:

**Comment by pi0** [comment]
Call `nuxt.ready()` after `new Nuxt()`

**Comment by aebrs** [comment]
server.js:
`const express = require('express');
const { Builder } = require('nuxt');
const { Nuxt } = require('nuxt-start') 
const config = require('./nuxt.config.js');
const app = express();
app.listen(process.env.PORT || 3000);
config.dev = false;
const nuxt = new Nuxt(config);
nuxt.ready()
app.use(nuxt.render);
new Builder(nuxt).build().catch(err => {
  console.error(err);
  process.exit(1);
});
`
ecosystem.config.js:
`module.exports = {
  apps : [
      {
        name: "nuxt",
        script: "./node_modules/nuxt-start/bin/nuxt-start",
        env: {
            "HOST": "127.0.0.1",
            "PORT": 3000,
            "NODE_ENV": "production",
        }
      }
  ]
}`
Not running yet.

**Comment by aebrs** [comment]
1- it was my fault, pm2 error, so final working script is:
`module.exports = {
  apps : [
      {
        name: "nuxt",
        script: "./node_modules/nuxt-start/bin/nuxt-start.js",
        env: {
            "HOST": "127.0.0.1",
            "PORT": 3000,
            "NODE_ENV": "production",
        }
      }
  ]
}`
I hope it help others too.
Thanks you.

**Comment by jaweii** [comment]
I solved this probolem with following code:

```
  "scripts": {
    "pm2": "pm2 start ./node_modules/nuxt-start/bin/nuxt-start.js --name myApp"
  }
```

**Comment by BiswasSuman** [comment]
@aebrs Thank you for posting your problem and solution.
It helps me to fix the same problem.

**Comment by blowsie** [comment]
@jaweii , just a heads up nuxt-start is not a dev dependancy :)
