### ISSUE TITLE
build.publicPath property causes 404 in dev mode

### ISSUE THREAD

**Issue by floflock** [nuxt/nuxt.js#5427]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://nuxtjs.org/guide/installation](https://nuxtjs.org/guide/installation)

### Steps to reproduce

Set in nuxt.config.js the property build.pubilcPath to value 'frontend', resources are not loaded in Frontend.

Setup: nuxt with express, standard-configuration from npx create-nuxt-app

![Screenshot 2019-03-31 at 13.50.02.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/248ca1a0-53ab-11e9-8ac3-bba2794fcb4c.png)

### What is expected ?

compiled assets should load in frontend with custom publicPath

### What is actually happening?

404 on all resources

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8964">#c8964</a>)</em></sub></div>

**Comment by vanpipy** [comment]
It looks like a feature needed, not a bug. Because no matter version of nuxt tried, a directory name from `build.publicPath` did its work but nothing resources except manifest.

**Comment by pi0** [comment]
The value should be `/fontend/`.

**Comment by vanpipy** [comment]
Yes, it's a webpack configuration, here is the [webpack publicPath](https://github.com/webpack/webpack/blob/7ed1a8f88d8e31c5f62212b5caac82feb93ae599/declarations/WebpackOptions.d.ts#L1137).

**Comment by pi0** [comment]
Closing as in latest versions we also add trailing slash automatically.

**Comment by Dok11** [comment]
@pi0 not quite

Have difference between this configs:
```
export default {
  mode: 'spa',
  generate: {
    dir: '../../www/f/dist'
  },
  build: {
    dir: '../../www/f/dist',
    publicPath: '/f/dist/_nuxt/',
  }
}
```

and:
```
export default {
  mode: 'spa',
  generate: {
    dir: '../../www/f/dist'
  },
  build: {
    dir: '../../www/f/dist',
    extend(config, { isDev }) {
      config.output.publicPath = (isDev) ? '/_nuxt/' : '/f/dist/_nuxt/'
    }
  }
}
```

First config dont broke `nuxt start`, but folders looks like
![image](https://user-images.githubusercontent.com/2697890/61135809-09213b80-a4cb-11e9-82f7-e18e11ef67b5.png)

Second config works corretcly if I want save build in some folder on the server — files put into `/www/f/dist/_nuxt/` and all pathes write correctly in js. I can write `/www/index.php` with links to `/f/dist/` resources and all works fine. But. It broken `nuxt serve`.

So, I would be functionally like in second config, but without broke `nuxt serve`
