### ISSUE TITLE
Route meta property empty in transition callback

### ISSUE THREAD

**Issue by matteo-rigon** [nuxt/nuxt.js#5428]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/embed/20ko08p79p](https://codesandbox.io/embed/20ko08p79p)

### Steps to reproduce

Declare a page component with meta, middleware, and transition properties

```js

export default {
  meta: {
    index: 1
  },

  middleware({ route }) {
    console.log("middleware meta: ", route.meta);
  },

  transition(to, from) {
    console.log("transition meta: ", to.meta);
  }
};
```

### What is expected ?

I'd expect to see the same meta object set in both middleware and transition callback.

### What is actually happening?

Transition callback has an empty meta object, while middleware callback correctly contains the index meta set in the page

### Additional comments?

I'm trying to apply a different transition based on the origin page and the destination page, and route metadata seems the perfect place to store the information needed to apply the logic, but apparently the transition callback does not have access to page meta data 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8965">#c8965</a>)</em></sub></div>

**Comment by pimlie** [comment]
@matteo-rigon By chance I came across this issue while looking for something else, but this issue is related to #5885
