### ISSUE TITLE
TypeError: [nuxt] Error while mounting app: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by QTTQ** [nuxt/nuxt.js#5429]

**Comment by QTTQ** [comment]
TypeError: [nuxt] Error while mounting app: Cannot read property 'indexOf' of undefined #

**Comment by QTTQ** [comment]
Use window.open() this method opens a new page and refreshes the page, and then the problem arises.

**Comment by liaohui1080** [comment]
Has your problem solved?
