### ISSUE TITLE
fetching the store in a middleware

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#543]
HI,
can i do this? i'm trying the fetch data in the store using a middleware

/middleware/loadFromServer.js
![image](https://cloud.githubusercontent.com/assets/19589742/24868397/d2d539f6-1e07-11e7-89ad-136961303553.png)

there is the fetchEpisodes implementation 

![image](https://cloud.githubusercontent.com/assets/19589742/24868537/3cadaa5c-1e08-11e7-9cf6-e52ae35d0e15.png)

**Comment by alexchopin** [comment]
Hi, the `nuxtServerInit`has been created for that case.
https://nuxtjs.org/guide/vuex-store/#the-nuxtserverinit-action

**Comment by aymenpeak** [comment]
@alexchopin hi, yeah i know i tried this one because i had a problem with Async request in 0the nuxtServerInit()

**Comment by aymenpeak** [comment]
![image](https://cloud.githubusercontent.com/assets/19589742/24903223/b55de790-1ea4-11e7-81f1-498d1ca11b45.png)

what im doing wrong?

**Comment by Atinux** [comment]
Make sure the `nuxtServerInit`action is in the `store/index.js` file @aymenpeak

**Comment by aymenpeak** [comment]
@Atinux yeah i did that thanks :)
im using the modules way to organise my store, i added that function in the index.js and all seems to work fine :)
