### ISSUE TITLE
Proper error messages

### ISSUE THREAD

**Issue by DirkStevens** [nuxt/nuxt.js#5431]
### What problem does this feature solve?

This features solves horribly bad error messages.

Nuxt prompts unusable error messages. Here's one I bumped in today...

~~~~
ERROR  'set' on proxy: trap returned falsish for property '_nuxtConfigFile'                                                                                                          19:43:15

  at Object.loadNuxtConfig (node_modules/@nuxt/cli/dist/cli-chunk2.js:2500:29)
  at NuxtCommand.getNuxtConfig (node_modules/@nuxt/cli/dist/cli-chunk.js:198:36)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:160:7)
  at Function.Module.runMain (module.js:703:11)
  at startup (bootstrap_node.js:193:16)
  at bootstrap_node.js:617:3
~~~~

### What does the proposed changes look like?

A proper stack trace of the true error in my project with references to files in my project, not some meta webpack output that refers to some temporary built files or whatnot.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8968">#c8968</a>)</em></sub></div>

**Comment by manniL** [comment]
Usually you get quite nice error messages. Thiss bug was based on an older ESM version and was resolved (https://github.com/standard-things/esm/issues/773)

There is no release yet but you could downgrade to v3.2.20
