### ISSUE TITLE
Unable to use nuxt-property-decorator

### ISSUE THREAD

**Issue by ChenZhuoSteve** [nuxt/nuxt.js#5435]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/xl0kyk4l2z](https://codesandbox.io/s/xl0kyk4l2z)

### Steps to reproduce

1.Rewrite pages/index.vue with nuxt-property-decorator

### What is expected ?

compile success

### What is actually happening?

compile failed

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8971">#c8971</a>)</em></sub></div>

**Comment by MrJmpl3** [comment]
A simple question , why you don't write `script lang="ts"` ?

**Comment by ChenZhuoSteve** [comment]
[nuxt-js-instructions](https://github.com/nuxt-community/nuxt-property-decorator#nuxt-js-instructions)
@MrJmpl3 
Typescript is not required

**Comment by kevinmarrec** [comment]
@ChenZhuoSteve

@MrJmpl3 is right, you're missing `lang="ts"` in script tags.

**Comment by kevinmarrec** [comment]
Also see https://nuxtjs.org/guide/typescript

**Comment by MrJmpl3** [comment]
@ChenZhuoSteve , you tried with only js , i think you need add @nuxt/babel-preset-app in the dependencies

> Currently decorators need the following two Babel plugins to work @babel/plugin-proposal-decorators,"@babel/plugin-proposal-class-properties. Latest Nuxt already adds them for us, the only thing we need is to add loose parameter to @nuxt/babel-preset-app. Just add this to nuxt-config

**Comment by ChenZhuoSteve** [comment]
@MrJmpl3 
I added the babel configuration
https://codesandbox.io/s/xl0kyk4l2z
It still compiles errors
@kevinmarrec 
nuxt-property-decorator is 
>Handy ES / TypeScript decorators for class-style Vue components in Nuxt

I want to use ECMAScript instead of typescript.
In real time, I can use the ECMAScript decorator in the 2.4.X version without introducing a typescript.

**Comment by ChenZhuoSteve** [comment]
I tried creating a project using create-nuxt-app and it works.😂

**Comment by ChenZhuoSteve** [comment]
https://github.com/nuxt-community/nuxt-property-decorator/issues/36
same problem

**Comment by kevinmarrec** [comment]
@ChenZhuoSteve Try to use `vue-property-decorator` instead, you shouldn't have to add `@nuxt/babel-preset-app`. I don't have any clue about "using ECMAScript instead of typescript".

> I tried creating a project using create-nuxt-app and it works.:joy:

Why reopening this issue here then ? Please continue on `nuxt-property-decorator` repo.
