### ISSUE TITLE
v2.6.0 and v3.0.0 error with firebase

### ISSUE THREAD

**Issue by sgmheyhey** [nuxt/nuxt.js#5443]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/sgmheyhey/nuxt-v2.6-beta-testing](https://github.com/sgmheyhey/nuxt-v2.6-beta-testing)

### Steps to reproduce

Have ever tried with firebase? Errors happened newly like `The XMLHttpRequest compatibility library was not found`.

_Originally posted by @sgmheyhey in https://github.com/nuxt/nuxt.js/pull/5352#issuecomment-478909714_

### What is expected ?

Normal screen

### What is actually happening?

Nuxt error message like `The XMLHttpRequest compatibility library was not found`

### Additional comments?

Not v2.5.1 but 2.6.0 or 3.0.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8979">#c8979</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@pi0 The issue may be related to `node-externals`.
In dev mode, webpack will require `@firebase/app/dist/index.esm.js` instead of `@firebase/app/dist/index.node.cjs.js`, and firebase considers that `This is a browser-targeted Firebase bundle but it appears it is being run in a Node environment`

**Comment by pi0** [comment]
@sgmheyhey Thanks for the report I've marked this issue as invalid until we have more details.

Please test against `nuxt-edge@2.6.0-25902733.d8bdd372` and also publish lock file the repo is using ambiguous version.

**Comment by pi0** [comment]
@sgmheyhey The regression fix has been made by @clarkdo in #5446 and new nuxt-edge release publushed. would you please test your project with `^2.6.0-25903509.e155ea43` ?

**Comment by sgmheyhey** [comment]
> @pi0  The error message `TypeError [ERR_INVALID_ARG_TYPE] The "path" argument must be of type string. Received type undefined` is produced. You can test it form the repository that is now including keys.

**Comment by clarkdo** [comment]
@sgmheyhey Try to external firebase and grpc lib:

```js
// nuxt.config.js build.extend
if (ctx.isDev && ctx.isServer) {
  config.externals = [
    'grpc',
    '@firebase/app',
    '@firebase/auth',
    '@firebase/firestore',
    '@firebase/storage',
  ]
}
```
