### ISSUE TITLE
v2.6.0 no-ssr order bug  perhaps

### ISSUE THREAD

**Issue by sgmheyhey** [nuxt/nuxt.js#5449]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/sgmheyhey/nuxt-v2.6-beta-testing](https://github.com/sgmheyhey/nuxt-v2.6-beta-testing)

### Steps to reproduce

Uncomment `vue-particles` and its `<no-ssr>` related things in `layouts/index.vue`.
Run `yarn dev -o`. It should not be a white screen.

### What is expected ?

Normal screen

### What is actually happening?

White screen. After refreshing `F5`, it would be appeared.

### Additional comments?

In v2.6.0, it's not ok. but in v2.3.x, it was ok.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8982">#c8982</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. In the provided example there are problems with firebase integration. A plugin should not expose shared exports from the plugin. Concurrent users may wrongly login as each other and this is a serious security bug. BTW I will try to investigate firebase path issue.

The layout file should be named `layouts/default.vue` not `layouts/index.vue`

If possible can you please create a repo that only contains and demonstrates the problem with this issue? (no-ssr)
