### ISSUE TITLE
Server middleware for after render process

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt.js#5451]
### What problem does this feature solve?

Would be nice to run server middleware after the rendering process. For e.g. pushing data to analytics services or anti fraud systems. The user wouldn't need to wait for that.

### What does the proposed changes look like?

`nuxt.config.js`:
```javascript
{
    serverMiddleware: [
        {
            src: '~/server/middleware/anti-fraud.js',
            after: 'render'
        }
    ]
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8984">#c8984</a>)</em></sub></div>

**Comment by pi0** [comment]
You can use `'render:route` hook (with args `url, result, context`) to intercept result and context which also contains `req` and `res`
