### ISSUE TITLE
Cannot find module 'emitter' when testing v2.6.0-beta 

### ISSUE THREAD

**Issue by mauxtin** [nuxt/nuxt.js#5453]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[http://notyet.com](http://notyet.com)

### Steps to reproduce

I just changed this

```
"nuxt": "^2.4.0",
```
with this
```
    "nuxt-edge": "^2.6.0-25903509.e155ea43",
```

I am not sure I should change something else in order to test it. I also run 
`rm -rf node_modules && yarn install && yarn run dev".

I will try to create reproduction repo soon.

### What is expected ?

Run smoothly.

### What is actually happening?

Cannot find module 'emitter' 

### Additional comments?

Stack

```

internal/modules/cjs/loader.js:581:15
Module._resolveFilename
internal/modules/cjs/loader.js:507:25
Module._load
internal/modules/cjs/loader.js:637:17
Module.require
internal/modules/cjs/helpers.js:20:18
require
node_modules\stream\index.js:22:15
internal/modules/cjs/loader.js:689:30
Module._compile
internal/modules/cjs/loader.js:700:10
Module._extensions..js
internal/modules/cjs/loader.js:599:32
Module.load
internal/modules/cjs/loader.js:538:12
tryModuleLoad
internal/modules/cjs/loader.js:530:3
Module._load
internal/modules/cjs/loader.js:637:17
Module.require
internal/modules/cjs/helpers.js:20:18
require
node_modules\vue-server-renderer\build.dev.js:9295:16
r
webpack:/external "stream":1:
Object.stream
webpack/bootstrap:25:
__webpack_require__
node_modules/node-fetch/lib/index.mjs:1:
Module../node_modules/node-fetch/lib/index.mjs 
```
(I am not sure if there is a cleaner way to copy paste the stacktrace here :( )

![image](https://user-images.githubusercontent.com/40521145/55470366-1eefac80-5610-11e9-914f-219f995709d0.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8985">#c8985</a>)</em></sub></div>

**Comment by mauxtin** [comment]
I was just rechecking the Migration guide and saw the core-js section in https://github.com/nuxt/nuxt.js/pull/5352. Do I need to manually install version 2 if I am sticking with 'default'?

**Comment by pi0** [comment]
@mauxtin installing is not required but recommended to prevent package manager hoisting v3 from another dependency. 

This issue may be due to externals fix. We've reverted it please try updating version to `2.6.0-25904774.3c737017`

**Comment by mauxtin** [comment]
The version you mentioned works great indeed! 🚀

**Comment by lichunshan** [comment]
**I also reported a similar mistake.**
Failed to compile with 6 errors                                                                                                                                                         friendly-errors 17:51:56

These dependencies were not found:                                                                                                                                                              friendly-errors 17:51:56
                                                                                                                                                                                                friendly-errors 17:51:56
* core-js/library/fn/get-iterator in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/get-iterator.js                                                                                 friendly-errors 17:51:56
* core-js/library/fn/is-iterable in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/is-iterable.js                                                                                   friendly-errors 17:51:56
* core-js/library/fn/object/assign in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/assign.js                                                                               friendly-errors 17:51:56
* core-js/library/fn/object/keys in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js                                                                                   friendly-errors 17:51:56
* core-js/library/fn/symbol in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/symbol.js                                                                                             friendly-errors 17:51:56
* core-js/library/fn/symbol/iterator in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/symbol/iterator.js                                                                           friendly-errors 17:51:56
                                                                                                                                                                                                friendly-errors 17:51:56
To install them, you can run: npm install --save core-js/library/fn/get-iterator core-js/library/fn/is-iterable core-js/library/fn/object/assign core-js/library/fn/object/keys core-js/library/fn/symbol core-js/library/fn/symbol/iterator
