### ISSUE TITLE
Slide-enter animations are broken although slide-leave are working well

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/nuxt.js#5456]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/8z6wlok31l](https://codesandbox.io/s/8z6wlok31l)

### Steps to reproduce

- Run example
- Check Panel.vue component
- Click `Open Panel` button to open panel
- Click `Open Panel` button once again to close the panel

### What is expected ?

- Panel opens from the side with animation that lasts 1 second

### What is actually happening?

- Panel opens instantly without animation although animation is present when panel is closing 

### Additional comments?

I noticed this bug after I've updated to Nuxt 2.5.0, not sure if it's related to Nuxt or Vue upgrade. Also reproduced it within Nuxt-Edge 2.6.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8989">#c8989</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment]
Was able to reproduce this issue outside of Nuxt with pure Vue. Guess this one can be closed. Link to new issue: https://github.com/vuejs/vue/issues/9878

**Comment by acidjazz** [comment]
@AndrewBogdanovTSS @pi0 I've been meaning to provide an alternative to this issue but I've been too busy to write up a full example, if you move your logic that shows/hides the animation after the `<transition>` element this should fire just fine.

ex:

```html
<template>
  <transition name="slide-left">
    <div v-if="open" class="generic-panel">
      <slot></slot>
    </div>
  </transition>
</template>```

**Comment by AndrewBogdanovTSS** [comment]
@acidjazz yes, I'm aware of such workaround, but it's not an option in my current architecture. `appear` prop was just what I need
