### ISSUE TITLE
npm install - hangs and does not finish installing

### ISSUE THREAD

**Issue by 7ammer** [nuxt/nuxt.js#546]
```bash
#Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64) served via digitalocean
node -v
v7.8.0 # installed via nvm

npm -v 
v4.2.0 # installed via nvm

cd to-nuxt-project
npm install
#... stuff happens as normal
Killed         ....] / extract:nuxt: sill doParallel extract 664
```
upon installation npm hangs at `Killed         ....] / extract:nuxt: sill doParallel extract 664` and then the process just dies :(

**Comment by pi0** [comment]
@7ammer NPM is very unstable on slow networks, Switch to [yarn](https://yarnpkg.com) and easily run `yarn install` instead of `npm` :)

**Comment by 7ammer** [comment]
```bash
#installed yarn
rm -rf node_modules

yarn install

yarn install v0.22.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 258/719 Killed
```
No luck. It got killed again :'(

**Comment by pi0** [comment]
Seems odd! Is your disk have enough capacity on /home mountpoint? (Check with `df -h`)

**Comment by 7ammer** [comment]
```bash
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G  3.3G   16G  18% /
```
All looks good there.

**Comment by 7ammer** [comment]
Think it was a memory issue.
I stopped a few processes

``` bash
initctl stop my-other-node-site-1
initctl stop my-other-node-site-2
```

..and all installed correctly!

BTW the install gave out a warning:
```bash
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
```
Everything seems to be running ok though.

**Comment by pi0** [comment]
Happy hearing you fixed problem :) About `fsevents` error that is ok :) I see that error everyday on my windows and linux boxes :)) This package seems to be only compatible with mac.

**Comment by 7ammer** [comment]
Good to know! Cheers for helping me out @pi0 :)
