### ISSUE TITLE
[2.5 update] Nuxt Fatal Error : "Missing Template Dependencies"  (conflict with node-fetch dependency)

### ISSUE THREAD

**Issue by ThomasKientz** [nuxt/nuxt.js#5460]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/ThomasKientz/nuxt-issue](https://github.com/ThomasKientz/nuxt-issue)

### Steps to reproduce

Install dependencies with npm.

Run `npm run dev`

### What is expected ?

To build without errors.

### What is actually happening?

An error occures during build. 

> FATAL  Missing Template Dependencies

### Additional comments?

This project depends on :
`"firebase": "^5.9.2"`

It appears that Nuxt dependencies are conflicting with one of `firebase`'s dependecy : `node-fetch`.

This issue only happen after a clean reinstall of the dependencies (by deleting `/node_modules` and `package-lock.json` and running `npm i`), so it depends on how `package-lock.json` is constructed.

I am using `npm 6.9.0`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8991">#c8991</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Can you please try manually adding `node-fetch` to your project?

**Comment by ThomasKientz** [comment]
Works by adding `node_fetch` manually.

**Comment by pi0** [comment]
@ThomasKientz I've added this node to 2.6 release notes.

BTW I really want to have your feedback about current DX. How do you see such an error?

**Comment by ThomasKientz** [comment]
@pi0 nice !

What do you mean by "see such an error" ? 

Are you talking from the console point of vue ?

**Comment by pi0** [comment]
Yes, I mean after "FATAL Missing Template Dependencies" there are also some instructions to resolve the dependency problem. But it made you to finally open an issue. So I'm thinking maybe the message could be better on CLI.

**Comment by ThomasKientz** [comment]
@pi0 Instructions were totally clear, but it felt like a temporary fix (adding a package in *my* `package.json` that I don't use directly). That's why I open the issue to let you know about it, maybe you can improve the way `node-fetch` is required so it will not conflict with other dep (but I am no expert with node dep...).

Also I don't know what is a "Template Dependencies", so the nuxt's message wasn't very clear, but hopefully the instructions above were clear.

**Comment by pi0** [comment]
Thanks, @ThomasKientz for your feedbacks. We will definitely try to make it better.

**Comment by ThomasKientz** [comment]
Thansk @pi0 for the reactivity and the good work. Huge Nuxt fan here ;)
