### ISSUE TITLE
Store rendered by server  A user and B user stores are strung together

### ISSUE THREAD

**Issue by zhengshengchen** [nuxt/nuxt.js#5461]

**Comment by pi0** [comment]
Hi. Please share your store code. There should be no global state

**Comment by zhengshengchen** [comment]
1.   store/index.js
var option = { counter:0 }
export const state = () => (option)
export const mutations = {
       increment(state) {
            state.conter++
      }
}


2. middleware/headers.js
store.commit('increment');

**Comment by rchl** [comment]
You need to return new instance of store from a function, not existing, global object.
```
export const state = () => ({counter: 0})
```

**Comment by zhengshengchen** [comment]
Does the server store only have global settings that are unrelated to pages and users?

**Comment by rchl** [comment]
New instance of store is created for each request so basically store is stateless on the server side. If you want to store per-user data you need to store that data in a cookie, for example, and fill the store using server plugin or middleware.
