### ISSUE TITLE
asyncData called multiple times in nested routes 

### ISSUE THREAD

**Issue by msacar** [nuxt/nuxt.js#5467]
Hello im having problems with nested dynamic routes 
here is a sandbox  example  https://codesandbox.io/embed/w04l29nmm7 
i applied this documentation to sandbox  https://nuxtjs.org/guide/routing#dynamic-nested-routes

pages/
--| _category/
-----| _subCategory/
--------| _id.vue
--------| index.vue
-----| _subCategory.vue
-----| index.vue
--| _category.vue
--| index.vue

for category route asyncData called 2 times
for category/subcategory route asyncData called 3 times

**Comment by DonNicoJs** [comment]
@msacar this is as intended, asyncData if found on a page is called. 
So this includes subpages as well, this allows for example to have such behaviour: 

list-page => call list endpoint
list-page/_id => call detail endpoint on the specific list element

if you need the same data on multiple pages call it only on the parent and pass it down as props or you can use fetch and use vuex
