### ISSUE TITLE
Transpiled dependency not being transpiled during SSR in Universal Mode

### ISSUE THREAD

**Issue by alexgrozav** [nuxt/nuxt.js#5469]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/inkline/inkline.io/tree/nuxt-ssr](https://github.com/inkline/inkline.io/tree/nuxt-ssr)

### Steps to reproduce

- Create nuxt application.
- npm install --save myvueplugin
- Add 'myvueplugin' to build.transpile (see nuxt.config.js)
- Add nuxt plugin for initializing myvueplugin, using myvueplugin/src (see plugins/inkline.js)

### What is expected ?

The installed plugin (myvueplugin) should be transpiled both during Client and Server usage.

### What is actually happening?

You get a SyntaxError saying "Unexpected token export" during SSR.

This means that babel is not transpiling the plugin during SSR.

### Additional comments?

I need to transpile the plugin because I'm developing the front end using that plugin and I need to see the changes in real time. Therefore, after doing the npm install --save myvueplugin, I also use npm link ../myvueplugin, in order to use the development version of the plugin.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9001">#c9001</a>)</em></sub></div>

**Comment by pi0** [comment]
@alexgrozav Can you please test against 2.6.1?

**Comment by alexgrozav** [comment]
@pi0 The new version works as expected. Thank you for the help!
