### ISSUE TITLE
Nuxt v2.6.0 ignores nuxt.config.js 

### ISSUE THREAD

**Issue by wpitallo** [nuxt/nuxt.js#5476]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://cmty.app/nuxt/issues/new?type=bug-report&repo=nuxt.js](https://cmty.app/nuxt/issues/new?type=bug-report&repo=nuxt.js)

### Steps to reproduce

I did an npm install that pulled down v2.6.0 and my app broke. After investigation if appears that the config file is being completely ignored. Rolling back to v2.5.1 fixed it.

### What is expected ?

Read config file

### What is actually happening?

I did an npm install that pulled down v2.6.0 and my app broke. After investigation if appears that the config file is being completely ignored. Rolling back to v2.5.1 fixed it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9004">#c9004</a>)</em></sub></div>

**Comment by manniL** [comment]
Please add a reproduction GitHub repository *or* CodeSandbox ( https://template.nuxtjs.org ).

**Comment by pi0** [comment]
The bug is confirmed. Fixes with #5500
