### ISSUE TITLE
Variable with name "module" throws error when imported in component

### ISSUE THREAD

**Issue by Takitaf** [nuxt/nuxt.js#5477]
### Version

[2.6.1](https://github.com/nuxt.js/releases/tag/2.6.1)

### Reproduction link

[https://codesandbox.io/s/zwvk4z2nl3](https://codesandbox.io/s/zwvk4z2nl3)

### Steps to reproduce

1. Create new nuxt application.
3. Create test.js file in e.g. /store directory with `export const module = {}` line.
4. Add `import {module} from "~/store/test"` line in pages/index.vue
5. npm run dev and open application in browser.

### What is expected ?

Page should be displayed without an error.

### What is actually happening?

"Identifier 'module' has already been declared" error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9005">#c9005</a>)</em></sub></div>

**Comment by Nbsaw** [comment]
It is not a bug. `module` is global object in node .
You can use `module.exports = { variables }` to export `variables` to another module . 
So when you are using `const` to redefine the `module`, it will throw expection .

**Comment by Takitaf** [comment]
Ok, fair enough. That's a little strange however - between Nuxt versions 2.2 to 2.4 it worked flawlessly. Something changed in 2.5 or 2.6 that makes this node's "module" exposed?
