### ISSUE TITLE
Any way to figure out which bundles are used by which all pages

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#548]
From the bundle analyser I could figure out the size of each bundle. But it will be good to have other informations like. which all pages uses this bundle.

**Comment by Atinux** [comment]
Coming in the next release (0.10.7), we use latest feature of Webpack `webpackChunkName`.

See the output of it:
![screen shot 2017-04-17 at 16 13 57](https://cloud.githubusercontent.com/assets/904724/25095358/b08c43b4-239b-11e7-9215-996332858d0e.png)

**Comment by shyamchandranmec** [comment]
@Atinux Thanks. Waiting for it !!
