### ISSUE TITLE
Context parameter that tells on client whether the page was rendered server side

### ISSUE THREAD

**Issue by kstadler** [nuxt/nuxt.js#5481]
### What problem does this feature solve?

For certain situations (e.g. PWA) it would be useful if you couldn't just tell whether you are on client or server but also let the client know whether the site was rendered server-side.

### What does the proposed changes look like?

Add a context parameter isServerSideRendered

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9008">#c9008</a>)</em></sub></div>

**Comment by manniL** [comment]
Not sure what you exactly mean with that.

`process.server` / `process.client` already give you that information if I got you right 🤔

**Comment by kstadler** [comment]
But process.client == true does only tell me that I'm on the client, not whether this is the initial page view that was rendered by the server

**Comment by manniL** [comment]
See https://github.com/nuxt/codesandbox-nuxt/blob/master/pages/about.vue as an example.

**Comment by kstadler** [comment]
Nevermind, I solved the problem using nuxt-client-init-module.
