### ISSUE TITLE
Window.postMessage() doesn't work with Nuxt.js

### ISSUE THREAD

**Issue by mauxtin** [nuxt/nuxt.js#5482]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://codesandbox.io/s/1qvxq4r7zq](https://codesandbox.io/s/1qvxq4r7zq)

### Steps to reproduce

I am trying to communicate between an iframe and the main window.

I added the `window.parent.postMessage("testMessage", "*");` which fires correctly (debugged with a firefox extension: https://addons.mozilla.org/en-US/firefox/addon/messpostage/)

Then added a listener like so
```
mounted() {
    window.onload = function() {
      console.log('Loaded.')
      window.addEventListener(
        "testMessage",
        function() {
          console.log("It worked!");
          alert("YAS");
        },
        false
      );
    };
  }
```

and confirmed the listener is added correctly (see screenshot below).

### What is expected ?

Two-way communication between iframe and main page

### What is actually happening?

No communication between the two
![image](https://user-images.githubusercontent.com/40521145/55687952-bee46780-597b-11e9-9930-44fbc565caf0.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9009">#c9009</a>)</em></sub></div>

**Comment by mauxtin** [comment]
You are right @rchl. However this doesn't work without it either..

**Comment by rchl** [comment]
You have to listen to `message` event, not `testMessage`.
See https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by chrysanthos** [comment]
I feel so stupid right now 😆 

Thanks a lot @rchl! I was under the impression that I need to somehow listen to the first parameter of the `postMessage`. For some reason I thought the first parameter is the name of an event.

Closing!

**Comment by mauxtin** [comment]
I feel so stupid right now 😆

Thanks a lot @rchl! I was under the impression that I need to somehow listen to the first parameter of the postMessage. For some reason I thought the first parameter is the name of an event.

Closing!
