### ISSUE TITLE
_page.json return empty JSON object

### ISSUE THREAD

**Issue by ianfortier** [nuxt/nuxt.js#5483]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://brotli.pro/benefits.json](https://brotli.pro/benefits.json)

### Steps to reproduce

Add .json to any SSR pages

Eg: /apples ---> /apples.json

### What is expected ?

Nothing ¯\_(ツ)_/¯ 
but.. it could be nice to return specific data as JSON object

### What is actually happening?

Return empty JSON Object : {}

### Additional comments?

Bug or maybe a future awesome feature :thinking: 

Shopify do the same with /orders  ----> /orders.json and it's awesome for debugging

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9010">#c9010</a>)</em></sub></div>

**Comment by manniL** [comment]
THanks for reporting! It's not related to pages though but generally to 404 requests (Depending on the extension/data type).

it's a feature of https://github.com/nuxt/serve-placeholder to reduce workload for 404 requests so they don't go through the whole Nuxt SSR cycle, e.g. for robots.txt, json, images and so on.
