### ISSUE TITLE
Optionally disable deletion of .nuxt directory

### ISSUE THREAD

**Issue by Tarik02** [nuxt/nuxt.js#5484]
### What problem does this feature solve?

Technically the same as here: https://github.com/zeit/next.js/issues/4976, but `.nuxt` instead of  `.next`

### What does the proposed changes look like?

Nuxt builder should remove contents of .nuxt directory instead of removing directory and creating it.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9011">#c9011</a>)</em></sub></div>

**Comment by Tarik02** [comment]
P. S. If anyone needs a workaround, you can use this code:
```javascript
// Workaround for: https://github.com/nuxt/nuxt.js/issues/5484
const fs = require('fs')
const fsExtra = require('fs-extra')
const path = require('path')

const old = fsExtra.remove
fsExtra.remove = dir => {
    if (typeof dir === 'string' && dir.endsWith('/.nuxt')) {
        // Remove all files and directories in the folder and then resolve the promise
        return new Promise((resolve, reject) => {
            fs.readdir(dir, (err, files) => {
                if (err) return reject(err)

                Promise.all(
                    files.map(file => old(path.join(dir, file)))
                ).then(resolve, reject)
            })
        })
    }

    return old(dir)
}

```

For example, put the code in file `patch1` and then run `node -r ./patch1 node_modules/.bin/nuxt` instead of just `nuxt`.

**Comment by pimlie** [comment]
What is your use case for this?

**Comment by Tarik02** [comment]
You can see this here: https://github.com/zeit/next.js/issues/4976

**Comment by pimlie** [comment]
Thanks, so its because you use .nuxt as volume in a docker container?

Why not just create a dir `build` in your project, change [`buildDir`](https://nuxtjs.org/api/configuration-builddir#the-builddir-property) to be `build/nuxt` and use the build dir as volume in docker instead of .nuxt

See #5344 for a similar request btw

**Comment by Tarik02** [comment]
This may be a solution.
