### ISSUE TITLE
Modern build still loads "nomodule" scripts

### ISSUE THREAD

**Issue by koresar** [nuxt/nuxt.js#5486]
### Version

[2.6.1](https://github.com/nuxt.js/releases/tag/2.6.1)

### Reproduction link

[http://example.com/sorry_it_is_impossible](http://example.com/sorry_it_is_impossible)

### Steps to reproduce

Have a simple nuxt.js SPA.

`nuxt.config.js`

```js
module.exports = {
    mode: "spa",

    modern: "client",

...
```

Build it:
```sh
NODE_ENV=production ./node_modules/.bin/nuxt generate
```

![modern-nuxt.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/c9e36570-59b0-11e9-98dd-e968263ac75e.png)

### What is expected ?

See the picture. Only the green scripts are expected to be loaded.

### What is actually happening?

The "nomodule" scripts are still loaded.

### Additional comments?

How would I completely drop support of the non-modern browsers?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9013">#c9013</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@koresar 
Could you provide more details about the repo ?

I tried with latest Nuxt, it works fine.

![image](https://user-images.githubusercontent.com/4312154/55724745-f72f8880-5a03-11e9-89a9-67b3288288fc.png)

**Comment by clarkdo** [comment]
@koresar Sorry, just realized that it's `generate`, I'll have a look

**Comment by koresar** [comment]
Woohoo! Amazing fix @clarkdo. Thank you very much
