### ISSUE TITLE
Error: Request failed with status code 429

### ISSUE THREAD

**Issue by kerrsmith** [nuxt/nuxt.js#5487]
When I run npm run generate I keep getting the following error:

Error: Request failed with status code 429

I thought this was due to me having lots of dynamic routes (about 100) that each contacted my API for data so I downloaded the JSON file and used this directly in the nuxt.config.js file.

Now when I do npm run generate no external connection is made to my API but I still get this error roughly every other run for several of the routes.

I am using the following VSCode on Windows 7 64bit:

Version: 1.34.0-insider (user setup)
Commit: 0ab39f4148f242e7b0802330385fc99b4845aa31
Date: 2019-04-08T05:19:58.162Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Comment by kerrsmith** [comment]
Just a quick update.

I have been through my code and found I had missed an API call in the Vuex store, I think this along with the API requests in the nuxt.config.js route generate part must put me over the limit for maximum connections to the API server.

I think each route API request in the config file then causes its own API call in the Vuex store which adds another lot of API calls - this must put me over the max number of requests limit.

Using a JOSN file for the routes seems to almost fix the issue but it is still failing every three or so times even with one API call per route.

**Comment by kerrsmith** [comment]
I have managed to solve the issue (for me) by adding interval: 1200 to the generate part of nuxt.config.js, this slows down the rate at which requests are made to the API server.

This is fine for me as it does not take too long to run for 100 or so routes but if you had more than this the route generation process could take quite a long time.

**Comment by shafayeatt1995** [comment]
Can you share the code "adding interval: 1200 to the generate part of nuxt.config.js". Please Please Please

**Comment by shafayeatt1995** [comment]
> I have managed to solve the issue (for me) by adding interval: 1200 to the generate part of nuxt.config.js, this slows down the rate at which requests are made to the API server.
> 
> This is fine for me as it does not take too long to run for 100 or so routes but if you had more than this the route generation process could take quite a long time.


Can you share the code "adding interval: 1200 to the generate part of nuxt.config.js". Please Please Please
