### ISSUE TITLE
middleware auth.js generate error

### ISSUE THREAD

**Issue by w550** [nuxt/nuxt.js#549]
https://nuxtjs.org/guide/routing/#middleware
```
export default function (context) {
  context.userAgent = context.isServer ? context.req.headers['user-agent'] : navigator.userAgent
}
```
copy this code in you framwork run generate 
context.userAgent is undefined
not work in nginx and  github

**Comment by alexchopin** [comment]
Can you be more specific about you environment? Do you use nuxt for static website?

**Comment by w550** [comment]
@alexchopin
node -v v6.9.3
nuxt -v "version": "0.10.5",
use vue init nuxt/starter myproject
create auth.js in middleware
auth.js
↓
```
export default function (context) {
  context.userAgent = context.isServer ? context.req.headers['user-agent'] : window.navigator.userAgent
}
```
npm install 
npm run generate 
copy dist ./* to  nginx website 
console.log error 
```
[nuxt.js] Cannot load components DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

change auth.js 
↓
```
export default function (context) {
  try {
    context.userAgent = context.isServer ? context.req.headers['user-agent'] : window.navigator.userAgent
  } catch (e) {
    console.log(e)
  }
}
```
no error 
but context.userAgent is undefined

**Comment by Atinux** [comment]
Hi @w550 

You cannot use `nuxt generate` on this since `req` and `res` are not in the context when generating the application.
