### ISSUE TITLE
nuxtServerInit interval called infinitely

### ISSUE THREAD

**Issue by shallwefootball** [nuxt/nuxt.js#5492]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript-vuex](https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript-vuex)

### Steps to reproduce

1. Clone https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript-vuex
2. yarn && yarn dev
3. Visit http://localhost:3000/
4. show terminal console

### What is expected ?

nuxtServerInit call once

### What is actually happening?

interval nuxtServerInit called infinitely.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9020">#c9020</a>)</em></sub></div>

**Comment by shallwefootball** [comment]
my fault.

**Comment by Leskd** [comment]
@shallwefootball how did you fixed it?

**Comment by shallwefootball** [comment]
sorry @Leskd i don't remember that issue.

**Comment by shallwefootball** [comment]
what's your case? same this?
i try to this case right now. but not found that url https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript-vuex

**Comment by Leskd** [comment]
@shallwefootball I can't get access to your repo

**Comment by shallwefootball** [comment]
@Leskd that repo is not mine
