### ISSUE TITLE
Not firing @error event on img element

### ISSUE THREAD

**Issue by rhaldkhein** [nuxt/nuxt.js#5493]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/vy6863v787](https://codesandbox.io/s/vy6863v787)

### Steps to reproduce

1. Create an image element with invalid path (which will produce not found error)
2. Bind a method to @error event

### What is expected ?

The method should run

### What is actually happening?

Not running

### Additional comments?

It's working fine when using Vue directly.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9021">#c9021</a>)</em></sub></div>

**Comment by Nbsaw** [comment]
As @rchl says this behavior cause by the `server-placeholder`.

First i comment out the [code](https://github.com/nuxt/nuxt.js/blob/3b424eb82960682ebd2d424daa8bb8cdbd13e283/packages/server/src/server.js#L135-L150) and start my local nuxt.js cli , the `error` event will be fire . 

And then i cancel comment out the code, add `{ dist: {}, static: { skipUnknown: true }  }` to my `nuxt.config.js`, the `error` event will be fire too.

**Comment by manniL** [comment]
`{ dist: {}, static: { handlers: null } }` should work as described in https://github.com/nuxt/serve-placeholder

**Comment by rhaldkhein** [comment]
Right! It worked after generating static html. I'm not using server on production, so need to set that flag on dev mode. Thanks all.

**Comment by overtrue** [comment]
```
```
