### ISSUE TITLE
Registering global components

### ISSUE THREAD

**Issue by Heydon** [nuxt/nuxt.js#55]
Currently, to import a component to a page, I appear to have to import `Vue` itself, then the component (with `Vue.component`). 

Where do I globally register components and why do I need to import `Vue` itself?

Apologies if these are silly questions.

**Comment by alexchopin** [comment]
Hi,
No worries the documentation isn't ready yet so we understand.
Import a component globally in Nuxt is easy, we call this option "plugins" in the nuxt.config.js.
You can see the configuration on [this example](https://github.com/nuxt/nuxt.js/tree/master/examples/plugins-vendor).

**Comment by Heydon** [comment]
Ah! Thanks, that's handy :-)
