### ISSUE TITLE
Nuxt with Typescript doesn't work with serverless/express after upgrade from nuxt-ts

### ISSUE THREAD

**Issue by lukaVarga** [nuxt/nuxt.js#5502]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://codesandbox.io/s/github/lukaVarga/nuxt-serverless-ts-issue](https://codesandbox.io/s/github/lukaVarga/nuxt-serverless-ts-issue)

### Steps to reproduce

- Edit `serverless.yml` to work with your AWS
- Run `npm run sls:create:staging`
- Visit URL
- Be sad when you get `Cannot GET /` and when you see there's nothing in the logs :( 

### What is expected ?

The app should work as expected, as it works locally and as it worked before the migration from `nuxt-ts`

### What is actually happening?

After migrating from `nuxt-ts` v2.4.5 to `nuxt` + `ts-node` + `@nuxt/typescript`, the app does not work in production on AWS. There are no errors in the logs, we just get a blank page with `Cannot GET /`. Everything works as it should locally.

### Additional comments?

Followup from https://github.com/nuxt/nuxt.js/issues/5408

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9024">#c9024</a>)</em></sub></div>

**Comment by pi0** [comment]
Can we close it as of https://github.com/nuxt/nuxt.js/issues/5408#issuecomment-482488393?

**Comment by lukaVarga** [comment]
Yup, closing it now.
