### ISSUE TITLE
Typescript types bug

### ISSUE THREAD

**Issue by orblazer** [nuxt/nuxt.js#5505]
### Version

[V2.6.1](https://github.com/nuxt.js/releases/tag/V2.6.1)

### Reproduction link

[https://github.com/orblazer/gestion-tmp](https://github.com/orblazer/gestion-tmp)

### Steps to reproduce

1. Clone my version of `vue-toasted` (https://github.com/orblazer/vue-toasted/tree/patch-1) and link that (ex: `yarn link`)
2. Clone my version of `@nuxtjs/toast` (https://github.com/nuxt-community/modules/pull/272) and link that (ex: `yarn link`)
3. Install the reproduction git
4. Try run with `yarn dev`

### What is expected ?

That run perfectly (without error)

### What is actually happening?

This is run with error on nuxt but not have error in Visual Studio Code.

The error : https://imgur.com/DQmlHyP

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9026">#c9026</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@orblazer The error explictly said that `$toast` type is not defined as part of a Vue instance, which doesn't allow you to do `this.$toast`.  If you don't have the error in VSCode, I guess you probably get autocompletion on it ? I think it's a TS configuration issue and not a Nuxt issue but I don't have any clue for now on what's going on, did you have the chance to search further ?

**Comment by orblazer** [comment]
@kevinmarrec Hello, i have fix my problem with `useTypescriptIncrementalApi: true` in `build.typescript.typeCheck`

**Comment by kevinmarrec** [comment]
Alright ! @orblazer, feels free to close your issue then 😃
