### ISSUE TITLE
build css and js files inside static folder

### ISSUE THREAD

**Issue by ahmedfaical** [nuxt/nuxt.js#5506]
Hello i know it's not a bug report or a feature request but i need a help to understand how can i use an external CDN url with nuxt. 
So if i edit nuxt.config.js with publicPath: `${process.env.CDN}/assets/`, after build + start i can't get my js or css files from : https://www.myWebsite.com/assets/d54f5fde97r654.js, I think it's normal because i'm using CDN and i must upload theses files to my CDN. But i don't think that this is a good solution because my CDN upload automaticly resources from myWebsite.com, if '/assets/d54f5fde97r654.js' exist in myWebsite it will be uploaded to CDN with the same path automaticly.

I think if I can copy css and js files or all dest folder content to static folder during the build process, it will resolve my issue.
 Or any suggestion?

**Comment by IYOUR** [comment]
I have same problem and solved by nuxt serverMiddleware to set a static folder
`  serverMiddleware: [
    { path: '/static-example', handler: serveStatic(__dirname + '/.nuxt/dist/client') }
  ]
`
