### ISSUE TITLE
Setting to disable console.logs per generated page

### ISSUE THREAD

**Issue by Frankwarnaar** [nuxt/nuxt.js#5510]
### What problem does this feature solve?

* When generating thousands of pages the build log becomes enormous.
* I'm using Netlify for hosting my static website. They're streaming their build logs to their UI and have a build time limit of 30 minutes. When generating thousands of pages, a delay starts to exist between the log output and the log preview in their UI, causing the build to exceed the build time limit.

### What does the proposed changes look like?

Add an option to the generate options to make logging a line per generated page conditional. Just log something like `Generated 9000 pages`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9030">#c9030</a>)</em></sub></div>

**Comment by seifsay3d** [comment]
Is someone working on this? if not I would like to give it a shot.

**Comment by pi0** [comment]
@seifsay3d It is on progress on #5517

**Comment by Frankwarnaar** [comment]
I still have to write some tests, but don't really have time to do so. So please, feel free to give it a go! I already have a [PR](https://github.com/nuxt/nuxt.js/pull/5517) open.

**Comment by seifsay3d** [comment]
Alright cool, I'm pretty new to OSS, should I just fork your fork ? add tests and docs and to PR against official nuxt?

**Comment by Frankwarnaar** [comment]
Yes, I think that's the easiest way to go. I have to say: I'm pretty new to snapshot testing, so I'm not sure my changes I did in the tests are wanted.

**Comment by pi0** [comment]
Please hold on. As of thread in related PR we may use log levels for disable per-route logs
