### ISSUE TITLE
how to use on dynamic component for multiple parent component in nuxt?

### ISSUE THREAD

**Issue by mortezasabihi** [nuxt/nuxt.js#5518]
how to use one dynamic component for multiple parent component in nuxt?
    
i have many components (pages) in browse directory:
```

|--songs(folder)
|---new.vue
|---popular.vue
|---top.vue
|---podcast.vue
|---playlist.vue

```
and i want to make a dynamic child component for example ```_id.vue``` and use it for all those parent components. is it possible? how to do that?

**Comment by DonNicoJs** [comment]
@mortezasabihi I believe you can achieve that by simply reversing the logic:

```
|--songs(folder)
|---_id(folder)
|---_id(page with nuxt-child)
|----new.vue
|----popular.vue
|----top.vue
|----podcast.vue
|----playlist.vue
```

if this is not acceptable (say that you have a constraint on the route names ) you may check the alisas feature of nuxt-router-extras https://github.com/nuxt-community/router-extras-module 
but I never used that way
