### ISSUE TITLE
loading.throttle doesn't seem to work

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt.js#5519]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/zx50vm1jql](https://codesandbox.io/s/zx50vm1jql)

### Steps to reproduce

Go to link
Slow down network (either delay 10s or change profile to 1k/sec up/down)
notice the second you click About button, the progress bar shows, even though throttle is set to 5000

### What is expected ?

Per documentation, progress bar shouldn't show until throttle is expired

### What is actually happening?

Progress bar is shown right away

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9037">#c9037</a>)</em></sub></div>

**Comment by zhj135** [comment]
in your reproduction link, you should replace 'thottle' to 'throttle'

**Comment by hecktarzuli** [comment]
LOL, I guess it was my turn to be 'that guy' ...  Fixed, problem still remains (yes I restarted the sandbox).. @manniL

**Comment by hecktarzuli** [comment]
ping @manniL

**Comment by manniL** [comment]
Can't repro in Firefox :thinking:

**Comment by hecktarzuli** [comment]
Grr, now I can't repro either in the sandbox.  I'll check local and verify everything is ok now.

**Comment by hecktarzuli** [comment]
Local dev looks fine now too.  I assume this was fixed in a later version or something.

**Comment by gijsroge** [comment]
I can confirm this issue does exist.

@hecktarzuli I forked your sandbox and added a real http request in the fetch so it would do an actual request and take some time to resolve.

As you can see I set the throttle to 1s and it still flashes between navigating.

https://codesandbox.io/s/codesandbox-nuxt-loading-throttle-issue-yhkp3

@manniL could you review again?

**Comment by hecktarzuli** [comment]
Yeah this is weird.   In my local dev, setting throttle to 20s still shows the progress bar immediately.  I don't know how this would be anything other than nuxt's fault.  It's their component that should be abiding by the nuxt.config.js

**Comment by gijsroge** [comment]
@hecktarzuli no the @nuxtjs/axios module [calls the set method](https://github.com/nuxt-community/axios-module/blob/dev/lib/plugin.js#L151) on the loading component that immediately shows the loading bar. This is by design.

The [pull request](nuxt-community/axios-module#247) I referenced is their to discus if the @nuxtjs/axios module should change its behavior so it respects the throttle configuration set by the user.

**Comment by hecktarzuli** [comment]
That abstraction is pretty messy.  IMHO, Nuxt should expose a loading object that webpack, axios and other junk can add and remove stuff from as things are loaded.  Then the only thing the loading component would need to do is decide how to render that abstraction over time. (@manniL)
