### ISSUE TITLE
Consider splitting webpack & related in to a new npm module

### ISSUE THREAD

**Issue by sirlancelot** [nuxt/nuxt.js#552]
When nuxt.js is running in production, it doesn't need `webpack`. However, because it's listed as dependency it will always be installed.

If an npm module were made (I propose `nuxt-dev`) which contains these dependencies, a user of Nuxt would be able to add that module to their devDependencies list. The resulting `package.json` for a Nuxt project would look like this:

```javascript
{
  "name": "my-app",
  "dependencies": {
    "nuxt": "latest"
  },
  "devDependencies": {
    "nuxt-dev": "latest"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start"
  }
}
```

The `nuxt-dev` package could contain everything needed "build" the application, while the `nuxt` package would contain the "runtime" dependencies and any runtime-level code.

**Comment by OlzhasAlexandrov** [comment]
+1,
You would have to build projects locally and upload `.nuxt` to the production server with other files.
On the other hand, the production server would be much cleaner without linters and webpack.

The only drawback is the additional complexity.
I personally think that **it should not be done, replacing the nuxt module** as you proposed with addition of nuxt-dev.
You would have to make nuxt module cleaner and people who got used to what to expect will be frustrated.

**Alternatively, we could create a clean production module.** Thus, it would be just am addition for developers to further improve their production state.
Then, it's the same thing, upload it to the server prebuilt locally, and use another package.json for the clean production module.

**Comment by Atinux** [comment]
What about something like `nuxt-serve` for serving the `.nuxt/dist/` folder in production, and `nuxt start` will simply use `nuxt-serve` (as a peerDependencie)?

So the package.json will look like this for someone who want to optimize the `npm install` in production:
```json
{
  "name": "my-app",
  "dependencies": {
    "nuxt-serve": "latest"
  },
  "devDependencies": {
    "nuxt": "latest"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt-serve"
  }
}
```

And this scenario will still work:
```json
{
  "name": "my-app",
  "dependencies": {
    "nuxt": "latest"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start"
  }
}
```

Or maybe calling the package `nuxt-start`? :smile:

**Comment by OlzhasAlexandrov** [comment]
@Atinux, in the first case you probably wanted  to name the devDependency nuxt-start?
I'd suggest to name them nuxt-dev and nuxt-prod because it's hard to understand what start and serve mean.
Other than that, two new modules are probably the best idea, since it won't break anyone's work.

You know best how to clean the nuxt-serve(or any other name) as much as possible, but if you want decrease your workload, I could try to clean it first and create a nuxt-start.
And then, you could further improve it

**Comment by sirlancelot** [comment]
I like @Atinux's suggestion, but I agree it should probably be named something like `nuxt-prod`, `nuxt-runtime`, or maybe `nuxt-prebuilt`?

**Comment by OlzhasAlexandrov** [comment]
😲😂 I thought I proposed the idea of making the production module, instead of modifications first

**Comment by Atinux** [comment]
Please consider using [nuxt-start](http://npmjs.com/package/nuxt-start) 😄 

Thanks for this idea guys!
