### ISSUE TITLE
got undefined while using env variable

### ISSUE THREAD

**Issue by mortezasabihi** [nuxt/nuxt.js#5520]
i wrote these codes for env:
```
  env: {
    websiteTitle: 'موزیک'
  },
```

but i got undefined value.

```
    created() {
      console.log(process.env.websiteTitle);
    },
```

what is wrong?

**Comment by DonNicoJs** [comment]
@mortezasabihi for me it does work ( https://codesandbox.io/s/xv2wqlpn74 ) 
Which version of nuxtjs? Sometimes is needed to restart the server for the nuxt.config.js changes to take effect

**Comment by mohamadrezahedayati** [comment]
> i wrote these codes for env:
> 
> ```
>   env: {
>     websiteTitle: 'موزیک'
>   },
> ```
> 
> but i got undefined value.
> 
> ```
>     created() {
>       console.log(process.env.websiteTitle);
>     },
> ```
> 
> what is wrong?
> 
> _This question is available on [Nuxt](https://cmty.app/nuxt) community ([#c9038](https://cmty.app/nuxt/nuxt.js/issues/c9038))_



> i wrote these codes for env:
> 
> ```
>   env: {
>     websiteTitle: 'موزیک'
>   },
> ```
> 
> but i got undefined value.
> 
> ```
>     created() {
>       console.log(process.env.websiteTitle);
>     },
> ```
> 
> what is wrong?
> 
> _This question is available on [Nuxt](https://cmty.app/nuxt) community ([#c9038](https://cmty.app/nuxt/nuxt.js/issues/c9038))_

what is type rendering ?

**Comment by mortezasabihi** [comment]
@mohamadrezahedayati 
i think you should restart the server.

**Comment by pi0** [comment]
Hi @mortezasabihi @DonNicoJs. Please take a look at runtimeConfig: https://nuxtjs.org/guide/runtime-config

This would allow you define and change things like title without rebuild and also watching `.env` file
