### ISSUE TITLE
Computed Property this IntelliSense broken

### ISSUE THREAD

**Issue by stefnotch** [nuxt/nuxt.js#5522]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://github.com/stefnotch/temp-nuxt-starter-app](https://github.com/stefnotch/temp-nuxt-starter-app)

### Steps to reproduce

1) Create a new Nuxt project
2) Optionally upgrade nuxt to version v2.6.1
3) Type the following in a component

```
computed: {
    test() {
      return "" + this. // HERE!!
    }
}
```

Alternatively, clone the repo and take a look at [index.vue](https://github.com/stefnotch/temp-nuxt-starter-app/blob/abc7767c2b0be3768c9184ed00790302c070ec4f/pages/index.vue#L24)

### What is expected ?

Various IntelliSense suggestions such as `this.$data`, `this.$emit`, `this.$nuxt` should show up

### What is actually happening?

None of them show up

![Untitled.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d750de60-5d32-11e9-9970-ad51c7b3e3ff.png)

This doesn't work either:
```
    test2: function( ) {
      return "" + this. // HERE!!
    }
```

### Additional comments?

In `methods: { someMethod() {} }`, the IntelliSense for `this` works as expected. 

I also have issues with `this.$router` not showing up in the methods: {}, but that's a different issue.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9039">#c9039</a>)</em></sub></div>

**Comment by stefnotch** [comment]
Adding a `tsconfig.json` might fix it.

**Comment by 0njzy0** [comment]
Have you solved it?

**Comment by stefnotch** [comment]
@0njzy0 I took a look at it again, `npm install vue` seems to solve the issue.

**Comment by manniL** [comment]
@stefnotch vue should be already installed as nuxt needs it 🤔

**Comment by stefnotch** [comment]
@manniL I know. It might be a Vetur bug where Vetur only looks at the `package.json` to figure out which packages have been installed.

**Comment by 0njzy0** [comment]
The auto completion or IntelliSense  works fine when I follow the steps below.

* I need `npm i vue`,so the package.json will have a vue dependency
* The vue file can't contain custom attributes or properties unique to nuxt such as layout,fetch,asyncData...

This is a example that works fine.

[codesandbox](https://codesandbox.io/embed/zqrpo8538l)

**Comment by 0njzy0** [comment]
I extracted the files in @nuxt/vue-app/types and placed them in nuxt.d.ts below the root path of the project. The IntelliSense works fine.

Because I don't know much about typescript, I don't know the specific reason.

[![Edit vetur-test](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zqrpo8538l?fontsize=14)

**Comment by kevinmarrec** [comment]
@stefnotch I think it's Vetur issue which needs `vue` to be in root `package.json`.
Unless you switch to TypeScript, I don't really know what are the workarounds.

**Comment by stefnotch** [comment]
@kevinmarrec Would it be a good idea to open an issue on the [Vetur issue tracker](https://github.com/vuejs/vetur/issues) then?

**Comment by 0njzy0** [comment]
I have opened an issue in Vetur.[In Nuxt project,Auto completion/IntelliSense is not working properly](https://github.com/vuejs/vetur/issues/1161)

**Comment by kevinmarrec** [comment]
I think Vetur is providing Auto completion / IntelliSense without readading Vue typings, it's probably bound to the extension core. So i'm afraid you'll not be able to have everything working with Nuxt.

**Comment by 0njzy0** [comment]
> I think Vetur is providing Auto completion / IntelliSense without readading Vue typings, it's probably bound to the extension core. So i'm afraid you'll not be able to have everything working with Nuxt.
> 
> EDIT : Unless you want tro give a try to TypeScript, you'll also be able to have type checking this way.

I have a question, why when I extract the contents of node_modules/@nuxt/vue-app/types into a separate .d.ts file, the IntelliSense works fine. But the default does not work.

This is my modified, the nuxt.d.ts in root directory is what I extracted from it.Everything working. 

[![Edit vetur-test](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zqrpo8538l?fontsize=14)

**Comment by kevinmarrec** [comment]
@0njzy0 Oh alright I think I got it.

It's cause Vetur is using TypeScript services behind the scenes, and they must somehow tell to look for Vue types by default.

In a Nuxt TypeScript project, we need to explictly tell to look for `@nuxt/vue-app` types through a `tsconfig.json`.

So I guess you might need a `tsconfig.json` anyway so Vetur read it to resolve types, even if you do not use TypeScript.

**Comment by stefnotch** [comment]
1. [Create a new Nuxt app](https://nuxtjs.org/guide/installation/)
2. Switch to [nuxt-edge](https://www.npmjs.com/package/nuxt-edge)
3. Type the following in a component
```javascript
data() {
    return {
      foo: 1
    };
  },
  computed: {
    bar() {
      return this. // Put cursor here
    }
  }
```
4. `CTRL+Space` to open the autocomplete popup.
![image](https://user-images.githubusercontent.com/10220080/57551489-70a2f980-7369-11e9-9786-1c408657354c.png)

**Comment by stefnotch** [comment]
It appears that this issue does not exist anymore. As such, I can close it.
