### ISSUE TITLE
Setting typeCheck to `true` in Nuxt config has no effect

### ISSUE THREAD

**Issue by chanlito** [nuxt/nuxt.js#5528]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://github.com/chanlito/nuxt-typecheck-bug](https://github.com/chanlito/nuxt-typecheck-bug)

### Steps to reproduce

0. Clone https://github.com/chanlito/nuxt-typecheck-bug
1. `npm i`
2. `npm run dev`
3. Make a typescript error, it won't appear in the terminal.

### What is expected ?

Typescript errors to appear in the terminal.

### What is actually happening?

Typescript errors not showing up.

### Additional comments?

Using nuxt without custom server & with `@nuxt/typescript` seems to work fine.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9041">#c9041</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@chanlito So yeah, it's not working for 2 reasons :
1) Current nuxt code is setting a variable to `true` if `@nuxt/typescript` is installed and if it's truthy, it enables the webpack plugin which handles type checkig.
2) This latter plugin, `fork-ts-checker-webpack-plugin`, need to be installed as it's responsible of the type check.

`@nuxt/typescript` is shipping the type checker, and also enables it in Nuxt internals.

We're still thinking about a better implementation, but we're not sure how to handle all use cases gently.

**Comment by kevinmarrec** [comment]
Resolved in https://github.com/nuxt/nuxt.js/issues/5553 (solution in comments)
