### ISSUE TITLE
component data() function called twice on pages when transition mode is empty

### ISSUE THREAD

**Issue by matteo-rigon** [nuxt/nuxt.js#5536]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://codesandbox.io/embed/xpon94z5yz](https://codesandbox.io/embed/xpon94z5yz)

### Steps to reproduce

Create two pages that for simplicity both extend a base component. This base component should set the transition mode property to `null` or `''` to override default "out-in" mode provided by nuxt. Now declare a data function with a dummy property, in our example x = 1, and declare a `created()` lifecycle hook that modifies this property, in our example `this.x = 2`. Now navigate between the two pages and check the value of x. Check browser console log of CBS to easily see the component lifecycle feedback.

### What is expected ?

I'd expect to see x = 2

### What is actually happening?

Instead of having x = 2, x is equal to 1 ( the value declared in the data function ). That happens because data function get called one more time after the created hook and resets x to the initial value:

- data called, x = 1
- created hook fired, x = 2
- data called again, x = 1 ( obviously this should not happen )

 This happens only when transition mode is not "out-in" or "in-out" and does not happen without nuxt

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9046">#c9046</a>)</em></sub></div>

**Comment by manniL** [comment]
related to #3496 ?

**Comment by ricardogobbosouza** [comment]
@manniL yes, the same

**Comment by matteo-rigon** [comment]
@manniL This seems to have been fixed with 2.8, updated the dependency on CSB and everything works as expected
