### ISSUE TITLE
Event Listener / method / watch data not working after Nuxt Generate

### ISSUE THREAD

**Issue by lhaggarty** [nuxt/nuxt.js#5537]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/lhaggarty/hotpotato](https://github.com/lhaggarty/hotpotato)

### Steps to reproduce

Dist folder in repo
![Screen Shot 2019-04-15 at 1.58.16 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/1e6041c0-5fa8-11e9-8754-dfdced2e2008.png)

![Screen Shot 2019-04-15 at 1.58.02 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/1ae80af0-5fa8-11e9-8754-dfdced2e2008.png)
.  The default index.vue page has @click events that call method (changeStep), a data watch listener (step).  These work in dev and production mode, but don't in generate files.  I have  console.log at the start of both the method and watch function.  Neither console.log show up then running /index.html generated page.

### What is expected ?

In my build, the area below the "next" or "previous" button has visual changes within the html elements, or the elements are changed. For example: 
![Screen Shot 2019-04-15 at 2.12.44 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2712bfd0-5faa-11e9-8754-dfdced2e2008.png)

<ExportButtonBar2 v-if="step > 7"></ExportButtonBar2>
    <VideoPlayerAndSidebar v-if="step > 2"></VideoPlayerAndSidebar>

### What is actually happening?

Nothing happens. Methods doesn't seem to trigger, and the watch data value isn't triggered.
![Screen Shot 2019-04-15 at 2.12.55 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2a0b1840-5faa-11e9-8754-dfdced2e2008.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9049">#c9049</a>)</em></sub></div>

**Comment by pimlie** [comment]
Thanks for the report, unfortunately the repro link is not working. Maybe its a private repo?

**Comment by lhaggarty** [comment]
> Thanks for the report, unfortunately the repro link is not working. Maybe its a private repo?
@pimlie ya.  I've now made it public

**Comment by pimlie** [comment]
Thanks, I would appreciate if you could create a _minimal_ reproduction of the problem. Its a lot of code in your reproduction and after creating a codesandbox for it I am not even sure how I get to the screenshots you posted.

**Comment by lhaggarty** [comment]
> pages > index.vue: 
line 24 @click="changeStep(-1)" - this is the previous button
line 30 @click="changeStep(1)" - this is the next button
line 206: changeStep: function() -the function itself
line 212: step: function (value) - this is the step data value watcher

These are compiled in the dist folder in the Nuxt single line js file structure.  
If you run the dist folder in a server setup: MAMP, express js, you should see the problem

**Comment by pimlie** [comment]
Unfortunately the codepen isnt working either, I think because you link to raw githubusercontent which transfers the nuxt build files with a `plain/text` mimetype instead of js.

But again, please try to recreate a _minimal_ reproduction which shows the issue is really with nuxt and not with your code or configuration.

**Comment by ethikz** [comment]
@pimlie I will say I'm experiencing the same issue.  Mine is related to context url.  If I have the project under root all js works fine.  As soon as I put it in a subdirectory and even change router base, none of the js fires.

**Comment by pimlie** [comment]
@ethikz Thanks for the confirmation, could you maybe please create a _minimal reproduction_ for this issue in that case?

**Comment by ethikz** [comment]
@pimlie So as it turned out, I didn't realize it was because the server didn't have proper mapping and I had to manually put `index.html` which of course broke the static site but with no errors.

**Comment by ethikz** [comment]
@lhaggarty Do you have somewhere we can discuss this?  Just running in dev I have noticed some errors in the js.

**Comment by yezongyang** [comment]
@pimlie i had the same issue, when browser url has .html suffix, all javascripts do not work

**Comment by Atinux** [comment]
Hi and thank you for the bug report.

Please provide a reproduction link and feel free to re-open, you can also use https://template.nuxtjs.org as starter.

Thank you 😊

**Comment by jialingWei** [comment]
I also have this problem. When I run "nuxt generate" to generate index.html, @click cannot work
