### ISSUE TITLE
How to import a postcss file with the aliases still working?

### ISSUE THREAD

**Issue by clementprdhomme** [nuxt/nuxt.js#554]
Hi!

Let's say I have the following set up:

_nuxt.config.js_:
```js
module.exports = {
  build: {
    postcss: [
      require('postcss-cssnext')()
    ]
  }
};
```

_assets/settings.css_:
```css
:root {
  --color: red;
}
```

_layouts/default.vue_:
```html
<template>
  <div class="app">
    <h1>Best app ever!</h1>
    <nuxt />
  </div>
</template>

<style lang="postcss">
  @import '~assets/settings.css';

  body {
    color: var(--color);
  }
</style>
```

The idea is to have a global CSS file with some variables I could reuse in my components. I want this file and all the other styles to pass through `postcss-loader`.

The issue I'm having is that the result of this config is the postcss variables not being processed by `postcss-loader` and directly copied to the output:
```css
:root {
  --color: red;
}

body {
  color: var(--color);
}
```

I tried another solution by including `postcss-import`, but in this case, the aliases don't work anymore.

How can I include an external/global postcss file with the aliases still working?

Thank you!

**Comment by alexchopin** [comment]
Works fine with less/scss, you need to add `postcss-loader` loader to your nuxt.config.js file.

**Comment by kodekrendel** [comment]
@alexchopin how to add `postcss-loader` in nuxt.config? When I add this, I got error

```
  build: {
    postcss: [
      require('postcss-cssnext')(),
      require('rucksack-css')({
        fallbacks: true
      }),
      require('lost')(),
      require('postcss-loader')
    ],
```

**Comment by kodekrendel** [comment]
Error on build

```
  build [=======   ] 67%TypeError: Cannot read property 'async' of undefined
```

**Comment by dennerkrans** [comment]
@kodeJ here is my current setup where I load my `main.css`, with all the variables I want to have available to all my components, by adding it as global css  in the `nuxt.config.js`. You also don't need to require the `postcss-loader` in the build config (I think 😊). Hope it helps!

```javascript
// nuxt.config.js
const { join } = require('path')

module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'Starter',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Starter' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  // Magic global css
  css: [join(__dirname, 'assets/css/main.css')],
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  build: {
    postcss: [
      require('postcss-import')(),
      require('postcss-cssnext')(),
      require('cssnano')()
    ]
  }
}
```

```css
// main.css
:root {
  --background-main: papayawhip;
  --color-main: palevioletred;
}
```

**Comment by robbue** [comment]
@dennerkrans Any idea if this works with nuxt@1.0.0-rc11?

The global custom properties does not work for me, even with the same setup as above.

**Comment by dennerkrans** [comment]
@robbue I haven't tried so sadly I don't know.
