### ISSUE TITLE
Rewrite(redirect) route for legacy application migration to Nuxt

### ISSUE THREAD

**Issue by mhf-ir** [nuxt/nuxt.js#5540]
### What problem does this feature solve?

I need to know best way to implements custom 404 handler, but not just render the custom 404 html or style.
I want to check define some regex for rewrite rules for example:

#### Regex Rewrite:
| Legacy Route   | Nuxt new route |
|----------------|----------------|
| /old/product/1 | /new/object/1  |

Also maybe some of old legacy application use slug and non-regex base urls 

#### Check with database
| Legacy Route   | Nuxt new route |
|----------------|----------------|
| /old/page/my-old-slug | /new/content/new-slug  |

request to backend then retrive the `my-old-slug` is `new-slug` then rewrite to new one.

For both problem header 301 must be set for SEO best practices.

How we implement this?

### What does the proposed changes look like?

I think one of the general implementation is using middle ware for whole nuxt handle this. but depend on rewrite rules and may be cost performance issue. think about heavy load website on each request.

What's the best practices for this problem?
And document it.

Thanks

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9053">#c9053</a>)</em></sub></div>

**Comment by dappiu** [comment]
For the "check with database" you can use the Nuxt's asyncData method on incoming request, make your checks and then issue a `redirect(301, '/something/new-slug')`
If you're using SSR, the asyncData method is called from the server only on the first request. After that, the client will have the entire bundle and what you put inside asyncData will be executed from client side (attention with CORS if you're calling an external API) without issuing new requests to the server.
Understand well this https://nuxtjs.org/guide/routing/#dynamic-routes and you might have anything you need.
Take also a look at [@nuxtjs/router-extras](https://github.com/nuxt-community/router-extras-module) that let's you define alias for routes.

**Comment by mhf-ir** [comment]
So we need to call `asyncData` for custom error page.
if regex or back end fails throw the regular 404 page.
I think that's good be part of documentation.

**Comment by mhf-ir** [comment]
Any update for this issue?

**Comment by manniL** [comment]
https://github.com/nuxt-community/redirect-module should solve that issue.
