### ISSUE TITLE
当pages组件中引入components组件，components组件命名和pages组件相同时，out of memory

### ISSUE THREAD

**Issue by nszbf** [nuxt/nuxt.js#5541]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://jsbin.com/nideyumawi/edit?html,output](https://jsbin.com/nideyumawi/edit?html,output)

### Steps to reproduce

当pages组件中引入components组件，components组件命名和pages组件相同时，js会报出 内存不足的错误 Maximum call stack size exceeded,

### What is expected ?

可以命名相同

### What is actually happening?

组件命名和pages相同，报错内存不足

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9054">#c9054</a>)</em></sub></div>

**Comment by dappiu** [comment]
What version of @nuxtjs/devalue you have installed right now? This might be related to #5551

**Comment by nszbf** [comment]
@dappiu   Thank you.sorry, I don't know what you mean by @nuxtjs/devalue, but this is a very simple question(bug). In vue, the parent component can be named the same as the child component, but not in nuxt. You can try this.  [https://jsbin.com/nideyumawi/edit?html,output](https://jsbin.com/nideyumawi/edit?html,output)

**Comment by nszbf** [comment]
@dappiu  thk, [https://codesandbox.io/embed/23v65644on](https://codesandbox.io/embed/23v65644on)   you can try this,in the pages/demo.vue
