### ISSUE TITLE
Can't prevent middle click to open href in new tab

### ISSUE THREAD

**Issue by ambrt** [nuxt/nuxt.js#5547]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.6.1)

### Reproduction link

[https://ykrkz6k081.sse.codesandbox.io/](https://ykrkz6k081.sse.codesandbox.io/)

### Steps to reproduce

```
<template><a href="https://google.com"
        @click.prevent
       @click.middle.prevent.stop="goto" 
        >Should not open with
        middle click</a>

<script>
methiods:{
   goto(e){
      e.preventDefault();
      return false
    }
```

### What is expected ?

should block middle click from opening in new tab

### What is actually happening?

Chrome opens link in new tab.

### Additional comments?

Left click works correctly (is blocking with .prevent). Middle isn't;

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9062">#c9062</a>)</em></sub></div>

**Comment by ambrt** [comment]
Link to editor of codesandbox https://codesandbox.io/s/ykrkz6k081?fontsize=14

**Comment by asg5704** [comment]
Hello @ambrt seems like this is an issue specifically within the Vue.js.  I'll open a PR with the Vue team.  A workaround for this would be to set `@auxclick.prevent.stop='goto'` instead of what you have, I hope this helps you. 😄

**Comment by ambrt** [comment]
@asg5704 Thanks, it works😃  . Btw,is `@auxclick` something internal in Vue? I couldn't find docs about it.

**Comment by asg5704** [comment]
@ambrt, No it is not in the Vue docs.

**Comment by rchl** [comment]
`auxclick` is the name of the event supported by browsers - https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event
It doesn't need to be listed in Vue docs as Vue can handle any arbitrarily named event, this one just being one of them.

**Comment by WORMSS** [comment]
This may want a little note on the vue docs next to where `.middle` is listed.. not because it's a `vue bug` (since it's not) but just because it can save people a headache.

I lost half a day trying to work out how to `.prevent.stop.middle.exact.everything-else-i-could-think-of="justStop"` to prevent middle click on an `<a> anchor` tag..
