### ISSUE TITLE
this

### ISSUE THREAD

**Issue by mazeyarr** [nuxt/nuxt.js#5548]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://jsfiddle.net/abr2nxz7/13/](https://jsfiddle.net/abr2nxz7/13/)

### Steps to reproduce

using "@nuxtjs/axios": "^5.4.1",

I call this function with a ref in the parent component.

```js
async submit() {
const { status, data } = await this.$axios.post(
          `[my api ult]/post/${this.id}`,
          serialize(this.$refs.form)
        )
}
```

### What is expected ?

1 outgoing call to my API

### What is actually happening?

2 outgoing calls and received 2 responses

![Schermafbeelding 2019-04-16 om 23.14.40.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b5429b80-608c-11e9-a098-3d075fd0d3b6.png)
 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9063">#c9063</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. There are probably no duplicate requests. One of them is OPTIONS sent by the browser to check preflight. You can prevent it by setting some headers from API or using [proxy](https://axios.nuxtjs.org/options#proxy) option.

**Comment by pi0** [comment]
If still having problems please open another issue (with details) in [axios-module](https://github.com/nuxt-community/axios-module) repository.
