### ISSUE TITLE
devalue randomly produces "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by dappiu** [nuxt/nuxt.js#5551]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://github.com/nuxt/devalue](https://github.com/nuxt/devalue)

### Steps to reproduce

The error pops out randomly when calling devalue on an Axios error object. I noticed that the error pop out more frequently when the nuxt dev server was launched a while ago and not when is freshly launched, but can't find a way to make it happen everytime.

The error comes out even if the axiosError is the simplest error object returned in requests that produces an early NetworkError during OPTIONS pre-flight requests.

The line causing recursion is this

```
return "{" + Object.keys(thing).map(function (key) { return safeKey(key) + ":" + stringify(thing[key]); }).join(',') + "}";
```

### What is expected ?

devalue() returns a stringified object representation

### What is actually happening?

devalue() raises a "RangeError: Maximum call stack size exceeded"

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9066">#c9066</a>)</em></sub></div>

**Comment by mesut** [comment]
any workaround ?

**Comment by manniL** [comment]
@aldarund can you help out?

**Comment by pi0** [comment]
- Devalue is being used to serialize the state of an SSR rendered page
- "OPTIONS" request only happens browser side, not server-side
- If Error is unhandled an error page should be thrown without SSR
- If an Error object exists in state object, devalue should warn about "non-POJOs"

Without a reproduction repo, it is hard to guess the cause.

**Comment by dappiu** [comment]
I made additional obersavations that could replace the "randomly" I wrote before. But maybe I was using devalue in a wrong way, here's what I did
- I have an axios interceptor installed from a plugin using `ctx.$axios.onError(myFunc)`
- When `myFunc(err)` were triggered, if the error wasn't something expected, it called at the end `ctx.error({statusCode: x, message: y, axiosError: err})`
- On my custom error layout there was a computed property that did `return devalue(this.error.axiosError)`
- If the listener were triggered on server side, the RangeError would come out

But I will build a reproduction repo tomorrow morning and try to verify all that. Sorry for not having investigated better before.

**Comment by pi0** [comment]
@dappiu Thanks for all additional info. original devalue disallows serializing non-pojos. For nuxt, we made a soft warning to prevent breaking changes for users. I highly recommend not serializing entier axiosError object, but picking needed fields from it.

**Comment by dappiu** [comment]
It's exactly what I end up doing at last. You can close the bug report, provided that I was using devalue in an unorthodox way.
Thank you for support.

**Comment by simplenotezy** [comment]
Posted a solution here too https://cmty.app/nuxt/nuxt.js/issues/c10415

**Comment by dappiu** [comment]
> Posted a solution here too https://cmty.app/nuxt/nuxt.js/issues/c10415

Thanks! That was exactly the point ;)
