### ISSUE TITLE
TypeScript type checker is not run when using Builder programmatically

### ISSUE THREAD

**Issue by sambowler** [nuxt/nuxt.js#5553]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://codesandbox.io/s/kwzmy8v1oo](https://codesandbox.io/s/kwzmy8v1oo)

### Steps to reproduce

Run the "dev" command from the code in the provided sandbox, no type checking is run when using the Builder programmatically. It appears to run correctly given the same configuration when directly using the "nuxt" command from the command line instead.

### What is expected ?

![Screenshot 2019-04-17 at 10.24.57.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/c8954a50-60f2-11e9-bd09-e59dc5c6046e.png)

### What is actually happening?

![Screenshot 2019-04-17 at 10.22.40.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/cae750a0-60f2-11e9-bd09-e59dc5c6046e.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9069">#c9069</a>)</em></sub></div>

**Comment by chanlito** [comment]
#5528

**Comment by kevinmarrec** [comment]
@sambowler @chanlito 

For pragmatically usage, you'll need to explicitly tell Builder to enable it through `_typescript.build` hidden config option (which must be not overrided if not using grammatically usage).

Here is how we're doing within our tests to check that the type checker is used :
https://github.com/nuxt/nuxt.js/blob/dev/test/unit/typescript.modern.test.js#L11

Please close your issues if it fixes them :)

**Comment by chanlito** [comment]
Setting the `_typescript` option
<img width="245" alt="Screen Shot 2019-04-18 at 4 56 13 PM" src="https://user-images.githubusercontent.com/15667259/56353156-003a0a00-61fb-11e9-8427-6cd589974c00.png">

Causes this error
<img width="1115" alt="Screen Shot 2019-04-18 at 4 56 05 PM" src="https://user-images.githubusercontent.com/15667259/56353183-0fb95300-61fb-11e9-975d-c9217aa7204a.png">

Which i'm not sure what it means really

**Comment by kevinmarrec** [comment]
@chanlito Well the error is not explicit so yeah hard to know what's going. Can you update your repo with issue or provide new repo with the issue ?

**Comment by chanlito** [comment]
I've found the  **Solution**

```bash
npm install --save-dev fork-ts-checker-webpack-plugin
```

Provide `_typescript` 
```ts
const nuxt = new Nuxt({
  dev,
  _typescript: {
    build: true
  }
});
```

**Comment by kevinmarrec** [comment]
@chanlito Oh yeah sorry, you didn't have this dependency, meanwhile @sambowler has it through `@nuxt/typescript`. You guys hadn't totally similar TypeScript setup ^^.

**Comment by sambowler** [comment]
Awesome, this worked as expected, thanks @kevinmarrec!

Is this functionality documented anywhere? I'm sure other folks would find it handy if they encounter the same issue. 🙂

**Comment by kevinmarrec** [comment]
@sambowler I'll put something in the docs :)
