### ISSUE TITLE
Firebase firestore not working with Nuxt in server side execution.

### ISSUE THREAD

**Issue by ThomasKientz** [nuxt/nuxt.js#5554]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://github.com/ThomasKientz/nuxt-firestore-repro](https://github.com/ThomasKientz/nuxt-firestore-repro)

### Steps to reproduce

npm install

npm run dev

navigate to website.

check the console.

### What is expected ?

The firebase query to execute without any errors.

### What is actually happening?

On server side (from a page reload), the firebase library produces an error. It looks like the firestore js library doesn't recognize objects from the async hook. Maybe nuxt is modifying prototypes or is messing with objects.

### Additional comments?

I am trying to query data by date from Firestore with Nuxt in an Universal App :

```
asyncData() {
    citiesRef
      .where("date", ">", new Date())
      .get()
      .then(() => {
        console.log("ok");
      })
    return {};
  }
```
But I get the error when loading from the server side (not happening in client side) :

> Function Query.where() called with invalid data. Unsupported field value: a custom Date object

Similar error with :

```
asyncData() {
    citiesRef
      .add({
        name: "Tokyo"
      })
      .then(function(docRef) {
        console.log("Document written with ID: ", docRef.id);
      });
    return {};
  }
```
> Function CollectionReference.add() requires its first argument to be of type object, but it was: a custom Object object

It doesn't happen with the client side context.

It's doesn't appear to be a firebase error as I can not reproduce this on a simple node env with the same lib : https://github.com/ThomasKientz/firestore-node-repro 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9071">#c9071</a>)</em></sub></div>

**Comment by 1919yuan** [comment]
```
const firebase = require("firebase/app");
citiesRef
      .where("date", ">", firebase.firestore.Timestamp.fromDate(new Date()))
      .get()
      .then(() => {
        console.log("ok");
      })
    return {};
```

**Comment by Zielgestalt** [comment]
@1919yuan this solution worked for me. Thanks!
