### ISSUE TITLE
Layouts/error.vue Weird transition

### ISSUE THREAD

**Issue by cel533** [nuxt/nuxt.js#5557]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://codesandbox.io/s/3vq7kyowz5](https://codesandbox.io/s/3vq7kyowz5)

### Steps to reproduce

click '404page'

### What is expected ?

like click 'About page'

### What is actually happening?

'404page' flickers/jumps to top

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9075">#c9075</a>)</em></sub></div>

**Comment by asg5704** [comment]
Looks like this is probably because of a CSS quirk.  Throw a border around the container in error.vue. to see why it jumps.

Reference:
https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-error.vue

**Comment by cel533** [comment]
> Looks like this is probably because of a CSS quirk. Throw a border around the container in error.vue. to see why it jumps.
> 
> Reference:
> https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-error.vue

thanks,the root element CSS need 
`position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;`

**Comment by manniL** [comment]
Is the issue resolved? @cel533

**Comment by asg5704** [comment]
@manniL I think we can mark this issue as resolved.
