### ISSUE TITLE
context

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#556]
How to access the context from any component?

**Comment by alexchopin** [comment]
Can you explain more about your need?

**Comment by wormen** [comment]
@alexchopin 
Everything is simple, I need to get from the context a variable created in middleware
Important condition, there may be no vuex in the layout, so the context is used

**Comment by alexchopin** [comment]
Ok, Have you tried to pass the data from the page to a component with `props`?

**Comment by wormen** [comment]
The fact is that such components are far beyond the limits of the page

Because here only 2 options
1) vuex, which may be absent
2) the context

**Comment by alexchopin** [comment]
I need more details to help you, with code snippets for example.

**Comment by wormen** [comment]
The solution of this question
Https://github.com/nuxt/nuxt.js/issues/557

Is closely related to the current

**Comment by Atinux** [comment]
The only solution is to use the store @wormen
