### ISSUE TITLE
SSR Only?

### ISSUE THREAD

**Issue by jamescmartinez** [nuxt/nuxt.js#5561]
Is there a way to configure Nuxt to be SSR-only, not isomorphic/universal? When I look at the [configuration mode documentation](https://nuxtjs.org/api/configuration-mode), I only have an option for `universal` (isomorphic) and `spa`.

The use-case is CORS related. I am unable to consume an API I need to consume client-side so I need to restrict my application to SSR-only.

**Comment by anat** [comment]
reopen it, bot !

**Comment by pi0** [comment]
SSR-only means losing almost all the benefits of a progressive-web application and also no Vue.js on client-side! We once added this feature as an experiment but results were not good at all!

So as a advice (no offense) you may have to rethink about your project architecture that how API calls are made or not using Nuxt.js but a server-side template engine like ejs/laravel.

**Comment by rchl** [comment]
And if the only issue is CORS then you could look into setting up a proxy for your API (see nuxt-axios documentation for example).

**Comment by SHxKM** [comment]
@rchl - can you offer more insight into this? The reason I'm asking is [this question](https://github.com/adamchainz/django-cors-headers/issues/455) I posted in the `django-cors-headers` repository, about why my Nuxt application isn't triggering a preflight when I'm setting a custom-header. Perhaps you know?

**Comment by rchl** [comment]
@SHxKM Check https://axios.nuxtjs.org/options#proxy

**Comment by SHxKM** [comment]
@rchl - yes. I’ve seen that by now. Why does turning this option on solve CORS? I’ve opened a question on the Proxy Module repo.

**Comment by rchl** [comment]
It's a proxy - you are making request to the domain you are on which means there is no CORS kicking in and your backend proxies request to your chosen host. There is no CORS restrictions on the node side.
