### ISSUE TITLE
Cannot deploy with Now

### ISSUE THREAD

**Issue by tchret** [nuxt/nuxt.js#5568]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[http://github.com/tchret/heyme](http://github.com/tchret/heyme)

### Steps to reproduce

now

### What is expected ?

deployment on now.sh

### What is actually happening?

 Nuxt build took: 131980.248521 ms
----------------- Install dependencies -----------------
Error: nuxt >= 2.4.0 is required!
                              at Object.build (/tmp/utils/build-module/node_modules/@nuxtjs/now-builder/lib/build.js:134:11)
                              at <anonymous>

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9084">#c9084</a>)</em></sub></div>

**Comment by pi0** [comment]
This issue is resolved.
