### ISSUE TITLE
Redefinition ~store

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#557]
How to dynamically redefine the variable ~ store, similarly as it is done for layouts?

Such a need arose because
1) I simultaneously use several layouts at once
2) each layout has its own store (vuex)

**Comment by Atinux** [comment]
Hi @wormen 

It is not possible, only 1 store is possible for 1 nuxt.js application.

**Comment by wormen** [comment]
@Atinux 
Earlier and layouts could not be dynamically assigned, now it is possible, oddly enough
Here is a similar situation

**Comment by wormen** [comment]
Store`s the way, the steps are easily reassigned at the layout level, then I need a slightly different solution, which is discussed in the first message
