### ISSUE TITLE
Index page loads all javascript resource files

### ISSUE THREAD

**Issue by Xzillion** [nuxt/nuxt.js#5579]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://nonelink.com](https://nonelink.com)

### Steps to reproduce

When I load the index page the following happens: Index page loads all javascript resource files
For example, my index page name is index, I just want to load index.js ,vendor.js, runtime.js, app.js.
But when I upgraded to version 2.6.2, the index page loads all resource files (page2.js, page3.js, page4.js ….)
This looks like：
![2269a6c0-6463-11e9-8912-59f53a2d1ec2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/3933e030-64b5-11e9-a0f7-2b334568d732.png)

And I disabled preloading：
render: {
resourceHints: false,
bundleRenderer: {
shouldPrefetch: (file, type) => false
}
}

### What is expected ?

I want to know how to disable loading extra files，Thank you all

### What is actually happening?

Index page loads all javascript resource files

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9088">#c9088</a>)</em></sub></div>

**Comment by manniL** [comment]
1. Please attach a reproduction repo or codesandbox
2. Please make sure you tested the behavior in production mode (it doesn't seem to be the case here)

**Comment by rchl** [comment]
It might be link prefetching "fault": https://nuxtjs.org/api/configuration-router#prefetchlinks
