### ISSUE TITLE
Feathers Auk Chat Example with Authentication

### ISSUE THREAD

**Issue by lobosan** [nuxt/nuxt.js#558]
Hi guys thanks for this wonderful project. I'm planning to work with MongoDB, FeathersJS and NuxtJS and I would like to get a solid foundation for my projects. Therefore I started to play with this [example](https://github.com/nuxt/nuxt.js/tree/master/examples/with-feathers) and I was wondering if you could add an updated version since FeathersJS Auk is out with major changes in authentication.

Could you please consider adding an example with the latest version of FeathersJS and maybe create the [chat example](https://docs.feathersjs.com/guides/chat/readme.html) with authentication included and vuex?, that would be super helpful.

Thanks a lot for your great work

**Comment by Atinux** [comment]
We have a lot of work on nuxt.js core right now, so any contribution from the community to update the example is more than welcome :+1:

**Comment by lobosan** [comment]
Sure, I'll let you know once I have it, till then I need to go through the docs and examples. Can't wait for Nuxt 1.0
