### ISSUE TITLE
Define different components for dynamic routes

### ISSUE THREAD

**Issue by Ca4tkin** [nuxt/nuxt.js#559]
Hi! Is there a way to define different components for dynamic routes? 

For example, I want one component for my-app/a, my-app/b, my-app/c routes and another component for my-app/d, my-app/e, my-app/f routes where a, b, c and d, e, f are defined by validate method.

**Comment by alexchopin** [comment]
Hi, you should use vue.js dynamic component in your nuxt.js page component.
http://vuejs.org/v2/guide/components.html#Dynamic-Components
