### ISSUE TITLE
import package can not get the right result

### ISSUE THREAD

**Issue by Xzillion** [nuxt/nuxt.js#5598]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/Xzillion/nuxt-import-bug](https://github.com/Xzillion/nuxt-import-bug)

### Steps to reproduce

1.download the GitHub repo;
2.open the file "pages/index.vue";
3.in the created function, i import a function "isDate" from date-fns , i want to verifya date Object;
4.run dev, and open browser;
5.you can see, the browser console print :
-----------------------------------------------------
   true "custom function"
  true "import date-fns util function"
-----------------------------------------------------
but the server console print:
---------------------------------------------------
 true "custom function"
 false "import date-fns util function"
---------------------------------------------------
so crazy!!

### What is expected ?

import package can not get the right result

### What is actually happening?

when i use a function from import package, i want to get the right result

### Additional comments?

thank you!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9104">#c9104</a>)</em></sub></div>

**Comment by manniL** [comment]
Just a guess but it might be related to https://github.com/nuxt/nuxt.js/pull/4508
