### ISSUE TITLE
If I use proxy-module, cypress-browser coudn't open website

### ISSUE THREAD

**Issue by mcmc4519** [nuxt/nuxt.js#5599]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[http://127.0.0.1:8000](http://127.0.0.1:8000)

### Steps to reproduce

@nuxtjs/proxy into modules (nuxt.config.js)
run cypress open
open site in cypress browser

### What is expected ?

cypress can open site

### What is actually happening?

cypress can't open site
I see error in the cypress browser http://prntscr.com/ngqj5b

But it's error is only in cypress.

In my default browser all is ok

### Additional comments?

"@nuxtjs/proxy": "^1.3.3"

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9105">#c9105</a>)</em></sub></div>

**Comment by mcmc4519** [comment]
have any ideas?

**Comment by pi0** [comment]
@mcmc4519 If possible please create a new issue in [Proxy Module's CMTY](https://cmty.app/nuxt/issues/new?repo=proxy-module) + A simple reproduction repository. Without it, it is hard to trace and provide a solution.
