### ISSUE TITLE
Allow installing Vuex plugins

### ISSUE THREAD

**Issue by ndarilek** [nuxt/nuxt.js#560]
I want to use [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate) in my app. This requires that I inject the plugin like so:

`new Vuex.Store({plugins: ...})`

Maybe nuxt.config.js could have a vuex.plugins option for initializing the store with the specified plugins?

**Comment by Atinux** [comment]
You can do it by using the [Classic Mode](https://nuxtjs.org/guide/vuex-store#classic-mode).

**Comment by ndarilek** [comment]
Any way to do this in non-classic mode?

It also isn't clear how to do it in classic mode, since it looks like 
there's no way to inject parameters into the `new Store(...)` call.

**Comment by Atinux** [comment]
Since in Class Mode you create yourself the store with `new Vuex.Store`, you can inject the plugins manually.

**Comment by sebastianmacias** [comment]
are there any plans to eventually support it in modules mode?

**Comment by Atinux** [comment]
Right now there is now plan for supporting it @sebastianmacias 

We could imagine exporting in the store/index.js a `plugins`array that can be given to the Vuex Store instace.

Any PR is welcome for implementing this :)

**Comment by sebastianmacias** [comment]
I would love to contribute. I short writeup on nuxtjs.org, listing the steps required to setup a development environment for nuxt would be great.

**Comment by bitmage** [comment]
+1... prefer modules, but they seem to fall short in not supporting this...

**Comment by rof20004** [comment]
+1 I with the same problema right now.

**Comment by Atinux** [comment]
It will be supported in the upcoming release (1.0.0-alpha1)

**Comment by rof20004** [comment]
Thanks @Atinux

**Comment by ndarilek** [comment]
So how does this feature work now that the respective alpha is out? I can't see how I'd add the vuex-persistedstate plugin. Tried exporting a `plugins` list in index.js like so:

`export const plugins = [createPersistedState()]`

But I suspect that won't work. What I probably need to do is export a function that initializes the plugins, then have that function's result added to the `plugins` option when the store is created. But that doesn't seem to work either.

**Comment by krasevych** [comment]
Hi guys! I have a problem:
I have store:
```
import Vuex from 'vuex';
import auth from 'src/store/modules/auth';
import createPersistedState from 'vuex-persistedstate';

export const plugins = [
  createPersistedState(),
];

export default new Vuex.Store({
  strict: process.env.NODE_ENV !== 'production',
  modules: {
    auth,
  },
});
```
and I got a error:
```
ReferenceError: window is not defined
    at createPersistedState (D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vuex-persistedstate\dist\vuex-persistedstate.js:54:66)
    at Object.module.exports.Object.defineProperty.value (src/store/index.js:6:2)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at webpackContext (webpack:/src/store ^\.\/.*\.js$:6:0)
    at getModule (.nuxt/store.js:9:13)
    at Object.module.exports.Object.defineProperty.value (.nuxt/store.js:31:19)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at Object.<anonymous> (.nuxt/index.js:6:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at Object.module.exports.Object.defineProperty.value (.nuxt/server.js:10:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at module.exports.$Object (webpack:/webpack/bootstrap 9f07d01ff16351a90719:93:0)
    at Object.<anonymous> (server-bundle.js:98:10)
    at evaluateModule (D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vue-server-renderer\build.js:6967:21)
    at D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vue-server-renderer\build.js:6985:15
    at D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vue-server-renderer\build.js:6983:12
```
what do I do  wrong?

**Comment by Atinux** [comment]
@krasevych you are using a plugin which is not SSR compatible (since it uses `window` directly).

You can try with `spa` mode (`rc5`) but you won't have SSR benefits.

**Comment by sullivanpt** [comment]
@krasevych you might be able to use cookies with 'vuex-persistedstate' using its `getItem`, `setItem`, etc., and being careful to access req.cookies verses document.cookies as in the example [https://github.com/nuxt/nuxt.js/blob/dev/examples/with-cookies/plugins/cookies.js].  Caveat is you'll want to use `filter` to keep the persisted state very small since it will be sent with each server request and be limited 4096 characters.

Let me know how it works out.

**Comment by michaelpumo** [comment]
Ah, such a roadblock for me.

I am trying, like @krasevych to use vuex-persistedstate in my Vuex store.

Nuxt seems to accept the plugin, but I get the same window error.

I don't mind just having vuex-persistedstate on the client-side - is there a way to make that happen at all that anyone knows of? No need for a server-side version.

:(

**Comment by bitmage** [comment]
@michaelpumo You're supposed to be able to do something like this:

```
{
  src: '~plugins/vuex-persistedstate.js',
  ssr: false
},
```

And you could define your own file in the plugins directory that loads the plugin into vuex.  The `{ssr: false}` (I think it stands for server side rendering?) should prevent your loading script and any further files it includes from being included in the server side build.  [I'm trying that with another library though](https://github.com/nuxt/nuxt.js/issues/1598), and it doesn't seem to be working for me.  :-/

**Comment by ndarilek** [comment]
There's a difference between Vue plugins and Vuex plugins, which must be 
created along with the store.

Since I don't know that this is supported in Nuxt, I've instead just 
created the store myself like so:

```
import Vuex from "vuex"
import createPersistedState from "vuex-persistedstate"

import auth from "./auth"

export default () => new Vuex.Store({
   strict: process.env.NODE_ENV !== "production",
   plugins: process.browser ? [createPersistedState()] : [],
   modules: {
     auth
   }
})
```

Not sure if that works yet, but at least it doesn't error.

**Comment by Atinux** [comment]
Please take a look at https://github.com/nuxt/nuxt.js/tree/dev/examples/vuex-persistedstate :)

**Comment by krasevych** [comment]
@Atinux but there are mode 'spa', as I know it spot ssr, only client side rendering, but I need SSR and vuex-persistedstate. Can I use both?

**Comment by mtnptrsn** [comment]
+1 I also use nuxt and I want to use SSR (not mode: 'spa')

**Comment by Atinux** [comment]
@krasevych @mtnptrsn 

You cannot use `vuex-persistedstate` with SSR since it uses localStorage (not accessible on server-side) and this will create a mismatch between server-side & client-side.

Right now, the only possible solution is to use the cookies to store and use it on both client & server.

**Comment by mtnptrsn** [comment]
@Atinux All right. Thanks for the help!

**Comment by krasevych** [comment]
@mtnptrsn I made some trick for it, maybe you are interesting it:
```
function restoreState(store) {
  if (process.browser && store) {
    if (window.__NUXT__ && window.__NUXT__.state) {
      store.replaceState(window.__NUXT__.state);
      delete window.__NUXT__.state;
    }
  }
}

function createPersistedStateWrapper(store) {
  if (process.browser && store) {
    createPersistedState()(store);
  }
}

export default function() {
  return new Vuex.Store({
    strict: process.env.NODE_ENV !== 'production',
    modules: {
  ............
    },
    plugins: [restoreState, createPersistedStateWrapper],
  });
}
```

**Comment by mtnptrsn** [comment]
@krasevych That looks interesting! I'll def give that a try. Thank you very much!!

**Comment by mnishihan** [comment]
I've posted a solution for using `vuex-persistedstate` plugin without using `spa mode` in [issue#972](https://github.com/nuxt/nuxt.js/issues/972#issuecomment-332308183), that works nicely along with `ssr mode`.
