### ISSUE TITLE
Polyfills are not injected to Node.js bundle even when required

### ISSUE THREAD

**Issue by ollisal** [nuxt/nuxt.js#5600]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://github.com/nuxt/nuxt.js/blob/v2.6.3/packages/babel-preset-app/src/index.js#L85](https://github.com/nuxt/nuxt.js/blob/v2.6.3/packages/babel-preset-app/src/index.js#L85)

### Steps to reproduce

1. Use a JS feature which your Node.js version would need a polyfill for in some page (e.g. [].flatMap for Node 10.x)
2. Run nuxt in development mode
3. Visit the page where you used the new JS feature

### What is expected ?

Page is rendered correctly both in SSR and in SPA.

### What is actually happening?

You get an error saying whatever new JS function you called (e.g. flatMap) is undefined.

SPA still works as the client bundle has required polyfills.

### Additional comments?

See https://github.com/nuxt/nuxt.js/blob/v2.6.3/packages/babel-preset-app/src/index.js#L85, all polyfills are just flat out left out in the server bundle.

Note, for the flatMap example specifically you need to use `corejs: 3`, as `core-js@2` doesn't have a `flatMap` polyfill anyway. This is my full `@nuxt/babel-preset-app` config:

```
[
'@nuxt/babel-preset-app',
          {
            buildTarget: isServer ? 'server' : 'client',
            corejs: 3,
            targets: isServer
              ? { node: 'current' }
              : { browsers: '>1%, not ie 11, not ie 10, not dead' }
          }
]
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9106">#c9106</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@ollisal Actually polyfills are not filtered out in `server` bundle since `polyfills` is `[]` as `exclude` of `@babel/preset-env` in server building.

For `core-js@3`, have you installed `core-js@3` in your `package.json` ?

If you could provide a reproducible repo, it would be great.

**Comment by ollisal** [comment]
Yeah I have core-js@3 installed.

This line is inside that `if`:

    plugins.push([require('./polyfills-plugin'), { polyfills }])

Isn't that plugin the one that adds the polyfill imports? Without it, no polyfills will be imported anywhere.

**Comment by clarkdo** [comment]
`polyfills-plugin` is for importing default polyfills like `promise`, `array.iterator`...

Other polyfiless will be imported automatically by `@bebel/preset-env` https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage-experimental

**Comment by ollisal** [comment]
Ahm, in that case my diagnosis about why this fails is not correct, sorry for that.

Anyway, nuxt development mode running on Node 10.x still fails in SSR if `flatMap` is used :/

Oddly, if I nuxt build it first and then nuxt start, everything works perfectly.

I'll see if I can get the time to cook up a repro repo for this soon.

**Comment by clarkdo** [comment]
I suppose it may be related to vue-ssr runInNewContext, I'll look further into it and get back to you asap.

**Comment by ollisal** [comment]
I was trying to use `flatMap` in a `method` of a page component in `pages/`

**Comment by clarkdo** [comment]
@ollisal 

Could you try to turn on `standalone` in `dev` ?

```js
// nuxt.config.js
export default {
  build: {
    extend(config, { isDev }) {
      if (isDev) {
        config.build.standalone = true
      }
    }
  }
}
```

**Comment by FreekVR** [comment]
For anyone reading this, I just had the same issue, and I don't think its a problem with nuxt itself, rather with the polyfill not detecting arrays.

Eg. I had some property coming as the result of an API call and the problem appears to be that babel doesn't know/see that this property is actually and array. I was able to work-around it like this:

Broken:
```
data.entry.theme.flatMap((theme) => {
...
}
```

Working:
```
Array.prototype.flatMap.call(data.entry.theme, (theme) => {
...
}
```
