### ISSUE TITLE
'vue-renderer:spa:templateParams' hook is not working

### ISSUE THREAD

**Issue by Miaoxingren** [nuxt/nuxt.js#5601]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://github.com/nuxt/nuxt.js/blob/v2.6.3/packages/vue-renderer/src/renderer.js#L351](https://github.com/nuxt/nuxt.js/blob/v2.6.3/packages/vue-renderer/src/renderer.js#L351)

### Steps to reproduce

I add a module to modify index.html.

```
const consola = require('consola')
const cheerio = require('cheerio')

export default function template (moduleOptions) {
  this.nuxt.hook('vue-renderer:spa:templateParams', templateParams => {
    const $ = cheerio.load(templateParams.APP)
    const nuxtScript = $('#__nuxt').first()
    nuxtScript.after(moduleOptions.customScript)
    templateParams.APP = $.html()
  })
}

```
then launch command  `npm run build`

### What is expected ?

expect index.html contains customScript.

### What is actually happening?

nothing changed with index.html.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9108">#c9108</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@Miaoxingren 

This hook only works for `spa` mode, are you using `spa` ?

And could you config that if the module is configured and hooks is executed ?

If you could provide a reproducible repo, it would be great.

**Comment by Miaoxingren** [comment]
@clarkdo  Please look at this: https://codesandbox.io/embed/pymmj2r9x7. I'm sure  the module is configured and hooks is executed.
