### ISSUE TITLE
How to remove error page

### ISSUE THREAD

**Issue by panw3i** [nuxt/nuxt.js#5604]
![image](https://user-images.githubusercontent.com/16938611/56785858-7658f500-6829-11e9-9f83-be6fafae5e48.png)

remove the default error page ,this error message only show in console window not redirect to error page

**Comment by northamerican** [comment]
bump

**Comment by dzcpy** [comment]
Any updates?

**Comment by jessielaf** [comment]
Is there an update about this? I am thinking of moving back to plain Vue because of this

**Comment by manniL** [comment]
Feel free to create a new issue @jessielaf

**Comment by codeasashu** [comment]
Sometimes, I really feel downhearted to see people developing bots and their own "systems" to manage issues, while planet's one of biggest organisation is working on best issue tracker possible (i.e. github). 

If your issue-template is limited, it doesn't mean you should develop an entire "state-of-the-art" system to handle new issues. Probably extend your templates (isn't that what templates are meant for?)

So, this issue links to https://cmty.app/nuxt/nuxt.js/issues/c9112 which is giving 500 error. Haha!! Well done guys. You bailed on a working issue tracker in favor of yours, which is giving 500. Good job guys!!

Can we just stop this madness and start working on one singular working issue tracker? If Torvalds can develop and entire kernel one a single issue trackers, aren't you guys exaggerating? 

![image](https://user-images.githubusercontent.com/1492350/91209977-2eeabd80-e72a-11ea-8116-8ef92fc648d4.png)
