### ISSUE TITLE
Nuxt 2.6.3 error  '$' is not defined  no-undef

### ISSUE THREAD

**Issue by jackpi2018** [nuxt/nuxt.js#5607]
This is not working in Nuxt 2.6.3. But in Nuxt 1.4.5 it works
import webpack from 'webpack'

export default {
  build: {
      plugins: [
     new webpack.ProvidePlugin({
       $: "jquery",
       jQuery:"jquery",
       'window.jQuery':"jquery"
     })
   ],
  }
}
Is there any changes in 2.6.3 about this?

**Comment by umrons** [comment]
set
```
env: {
  ...
  jquery: true
},
```
in `.eslintrc.js`

and

```
build: {
  ...
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery'
    })
  ],
}
```
in `nuxt.config.js`
