### ISSUE TITLE
server-side fetching data

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#561]
hi,
i'm trying to fetch the store when there is a SSR so i implemented the ___ in the store.

/store/modules/episodes
![image](https://cloud.githubusercontent.com/assets/19589742/25002651/716784a6-2043-11e7-959e-c7be7ab74e5e.png)

when i debug it ; he get the data, affect it to the state variable but on the browser(Vuejs dev tool) , it still empty...
![image](https://cloud.githubusercontent.com/assets/19589742/25002740/dfad6732-2043-11e7-94e3-dbc61e525720.png)

**Comment by semyenov** [comment]
nuxtServerInit should be at store root

**Comment by aymenpeak** [comment]
tried it already , same result...

**Comment by Cengkaruk** [comment]
I got same problem. Store commit not set at the browser from SSR.

**Comment by Atinux** [comment]
Please create a reproduction by forking this project: https://glitch.com/edit/#!/nuxt-hello-world

When the bug is reproduced I will re-open the Issue, thank you @aymenpeak

**Comment by bdschr** [comment]
Am having same problem on a middleware. 

```
import { getUserFromCookie, getUserFromLocalStorage, feathersApp } from '~/utils/auth'

export default function ({ isServer, store, route, redirect, req }) {
	const loggedUser = isServer ? getUserFromCookie(req) : getUserFromLocalStorage()

	loggedUser.then((data) => {
		return feathersApp.service('users').get(data.userId)
	}).then((user) => {
		// feathersApp.set('user', user)
		store.commit('SET_USER', user)
	}).catch((e) => {
		console.log('Error checking auth:' + e)
		if(route.name !== 'auth-login') {
			return redirect('/auth/login')
		}
	})

}
```

Everything works except the store.commit doesn't commit the data to the vuex store.

**Comment by airtonix** [comment]
Ran into this today... Like the success says...`nuxtServerInit` needs to return a promise like type.
