### ISSUE TITLE
[nuxt] Error while mounting app: HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by mjmnagy** [nuxt/nuxt.js#5612]
Hi, 

I have uploaded my nuxt app to a plesk server.

I ran `build --scripts-prepend-node-path` to create `.nuxt` folder. i then ran `start --scripts-prepend-node-path`

The site "works" but not all the features/events work.

When i open the console. i get the following errors
 
      TypeError: Cannot read property '$scopedSlots' of undefined @ _nuxt/259a4998f26830aa9f74.js:2

this error correlates to the following function

       function te(t, e, n) {
            if (!tt && !et || "undefined" == typeof console)
                throw t;
            console.error(t) //<-- this is the error
        }

Additionally, the following error is included

     Error: [nuxt] Error while mounting app: HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method. @ _nuxt/989b40654fd3805a3347.js:3460

this error correlates to this piece of code (which is part of a larger snippet)

     function L() {
            return (L = Object(n.a)(regeneratorRuntime.mark(function e(o) {
                var t, n, l, d, h;
                return regeneratorRuntime.wrap(function(e) {
                    for (; ; )
                        switch (e.prev = e.next) {
                        case 0:
                            return v = o.app,
                            m = o.router,
                            o.store,
                            e.next = 5,
                            Promise.all(C(m));
                        case 5:
                            return t = e.sent,
                            n = new r.default(v),
                            l = w.layout || "default",
                            e.next = 10,
                            n.loadLayout(l);
                        case 10:
                            if (n.setLayout(l),
                            d = function() {
                                n.$mount("#__nuxt"),
                                m.afterEach(E),
                                m.afterEach(R.bind(n)),
                                r.default.nextTick(function() {
                                    A(n)
                                })
                            }
                            ,
                            n.setTransitions = n.$options.nuxt.setTransitions.bind(n),
                            t.length && (n.setTransitions(k(t, m.currentRoute)),
                            y = m.currentRoute.matched.map(function(e) {
                                return Object(c.b)(e.path)(m.currentRoute.params)
                            })),
                            n.$loading = {},
                            w.error && n.error(w.error),
                            m.beforeEach(_.bind(n)),
                            m.beforeEach(O.bind(n)),
                            !w.serverRendered) {
                                e.next = 21;
                                break
                            }
                            return d(),
                            e.abrupt("return");
                        case 21:
                            h = function() {
                                E(m.currentRoute, m.currentRoute),
                                S.call(n, m.currentRoute),
                                d()
                            }
                            ,
                            O.call(n, m.currentRoute, m.currentRoute, function(path) {
                                if (path) {
                                    var e = m.afterEach(function(o, t) {
                                        e(),
                                        h()
                                    });
                                    m.push(path, void 0, function(e) {
                                        e && x(e)
                                    })
                                } else
                                    h()
                            });
                        case 23:
                        case "end":
                            return e.stop()
                        }
                }, e)
            }))).apply(this, arguments)
        }
        Object(h.b)().then(function(e) {
            return L.apply(this, arguments)
        }).catch(function(e) {
            var o = new Error(e);
            o.message = "[nuxt] Error while mounting app: " + o.message,
            x(o) // <-- ERROR
        })
    
Any help is greatly appreciated

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9121">#c9121</a>)</em></sub></div>

**Comment by mrKorg** [comment]
Hi, do you fix it?
I have the same problem

**Comment by mjmnagy** [comment]
Hi,

I cannot honestly remember what i did.... I know for certain that i was running into problems when i created a directory with the admin user/root user and then uploaded/modified the app root folder structures using a different user i would run into problems. If you like me uploaded the contents of the app using ftp make sure you are using the same user as the owner of the directory

**Comment by mjmnagy** [comment]
i also updated and then reinstalled all my packages

**Comment by shlomy** [comment]
Hi,
I have the same problem after deploying to production.

**Comment by pitapaya** [comment]
Check this thread for solution: https://github.com/nuxt/nuxt.js/issues/5800

**Comment by lematy** [comment]
i recently had this issue, and i was running in SSR, worked fine on local but not in heroku. The issue was i was displaying an iframe but i needed to wrap the iframe with <client-only> tag.
