### ISSUE TITLE
SSR with Now V2

### ISSUE THREAD

**Issue by smth** [nuxt/nuxt.js#5614]
### What problem does this feature solve?

There is no way to deploy SRR apps to Now.sh (V1 is not permitted for new projects).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9123">#c9123</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Please see https://github.com/nuxt/now-builder

**Comment by smth** [comment]
Awesome thanks. That should probably be added to the docs, right? Currently it says:

> You cannot deploy a server-side-rendered Nuxt app with Now V2 right now.

I already created a [related issue here](https://cmty.app/nuxt/docs/issues/c198).

**Comment by begueradj** [comment]
I was scared because I thought you did that in one single day :) @pi0

**Comment by manniL** [comment]
@smth Feel free to create a PR to change the wording ☺️

**Comment by Atinux** [comment]
It’s now possible to deploy to Now V2 thanks to @nuxtjs/now-builder :)

Docs has been updated: https://nuxtjs.org/faq/now-deployment

**Comment by sobolevn** [comment]
Sadly `now-builder` does not support `ts` version.

**Comment by manniL** [comment]
@sobolevn 	feel free to raise an issue there

**Comment by sobolevn** [comment]
It is already there 🙂 
https://github.com/nuxt/now-builder/issues/28
