### ISSUE TITLE
page mounted twice when layouts change

### ISSUE THREAD

**Issue by ImagineZzf** [nuxt/nuxt.js#5615]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Steps to reproduce

when I click home to search，（home is  used layouts/default.vue，and search is used layouts/search.vue）,it will mounted twice in search page, it is a bug?

### What is expected ?

expected : mounted once 

### What is actually happening?

actually happening: mounted twice

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9124">#c9124</a>)</em></sub></div>

**Comment by asg5704** [comment]
Can you provide a sample of the code in codesandbox.io or a repository so we can look at the code?  Thank you.

**Comment by usb248** [comment]
https://codesandbox.io/s/wn7j570y85

**Comment by ricardogobbosouza** [comment]
Same https://github.com/nuxt/nuxt.js/issues/5615

**Comment by pimlie** [comment]
Closing this in favor of #5703 as that has more info
