### ISSUE TITLE
Generate static site in SPA mode

### ISSUE THREAD

**Issue by FelixRe0** [nuxt/nuxt.js#5617]
### What problem does this feature solve?

For many SPAs it would be benefitial to pre-generate a few public sites such as the index.
This would benefit SEO in SPA mode.

### What does the proposed changes look like?

Generating specified files like done with nuxt generate. The rest of the app is served as SPA.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9126">#c9126</a>)</em></sub></div>

**Comment by manniL** [comment]
This is already possible via `generate.exclude` (https://github.com/nuxt/nuxt.js/pull/4754) and `generate.fallback` ☺️
