### ISSUE TITLE
appear property on transition object not working

### ISSUE THREAD

**Issue by max-schu** [nuxt/nuxt.js#562]
i just noticed the appear property on the transition object doesn't seem to work. and is missing in the docs.

is it not implemented or only missing in the docs and i'm doing something wrong and that makes it not work.

```
export default {
  transition: {
      appear: true,
      css: false,
      mode: 'out-in',
      enter (el, done) {
       done()
      }
  }
}
```

**Comment by Atinux** [comment]
It's normal since the appear transition is never called when server-rendered.

See [my comment](https://github.com/nuxt/nuxt.js/issues/34#issuecomment-268063202) about it.

**Comment by max-schu** [comment]
ugh, i missed your comment about that, when going through related issues.

it kind of feels like ssr is holding back some important features for the client side, still hoping for a global ssr: false to avoid these problems.

thank you!

**Comment by Atinux** [comment]
Yes but keep in mind that `ssr: false` will have an "empty" HTML, so no advantage for SEO.

**Comment by max-schu** [comment]
i know, maybe utilizing prerender-spa-plugin when ssr: is set to false is an idea. but that probably kind of opens a box of new issues.

anyway you don't really take advantage of real ssr when using nuxt genereate anyway do you?
– thats my point in that case

**Comment by Atinux** [comment]
When you call `nuxt generate` actually, it generated the pages like server-rendered, so it's perfect for SEO and performances since it can be hosted on a CDN.

If you go to https://nuxtjs.org an look at the source code, the HTML is generated and it uses `nuxt generate` (it's actually hosted on surge.sh)

**Comment by max-schu** [comment]
yeah as long as you're working without alot of js heavy dom manipulation thats great. but as soon as you use a few modules to enhance the ux its becoming a pain in the ass and makes the generate feature which is supposed to be a major asset less valueable.
hope the constructive feedback is ok - some ppl might use nuxt for its generate feature in the first place so we gotta look at it from that perspective in order to make it valueable.

**Comment by Atinux** [comment]
What kind of modules do you use for heavy dom manipulation?

I'm open to constructive feedback :)

**Comment by max-schu** [comment]
well "heavy" might be a rather relative term, and i'm not able to give you a big list of modules causing troubles, since im not a experienced  nuxt.js user yet, but so far I had to look for workarounds for almost every module, which is fine, but kills the advantage you're supposed to get by using nuxt. hope you get my point – theres a solution for everything i'm just feeling ssr causes problems when building with client side and static hosting in mind.

is used to following modules and experienced issues regarding ssr
vue-lory (no workarround yet)
vue-google-maps
smooth-scrolling
vue-sticky

**Comment by gbezyuk** [comment]
@Atinux actually, it would be great to have a possibility to use `appear` even with SSR enabled. I mean, it's probably not about Nuxt but about Vue itself, but nevertheless. One possible solution could be deliberately changing page's `key` attribute in browser only (maybe in nuxt's root element's `mounted` method?).

**Comment by Atinux** [comment]
@gbezyuk indeed it's more a Vue feature directly. But since Vue.js does not change the DOM when the page is server-rendered, it's impossible to call the `appear` transition.

But you can do the appear transition yourself with Nuxt.js 😄

Look at my demo: https://ordinary-glider.glitch.me/
And the code: https://glitch.com/edit/#!/ordinary-glider

**Comment by max-schu** [comment]
hey @Atinux what if you are using javascript hooks? I'm trying to acces the current transition through
`window.$nuxt.nuxt.transitions[0].enter()`
but it's throwing an error saying "done is not a function". Could you tell us please where the transition of the current route is stored, so that we can call enter() of current route onNuxtReady?

**Comment by jkd77** [comment]
Hey Atinux, is there a way to use the appear transition or onNuxtReady() with the transition object and GSAP? I note that transition object options only seem to fire when traversing between pages of the app, and not on initial page load.
