### ISSUE TITLE
Default page

### ISSUE THREAD

**Issue by dietergoetelen** [nuxt/nuxt.js#5621]
### What problem does this feature solve?

Currently I'm extending `nuxt` by adding custom routes. 

```
this.extendRoutes((routes, resolve) => {
   routes.push({
     name: 'index',
     path: '',
     component: resolve(__dirname, 'pages, index.vue')
   });
})
```

The problem is that I have no default `pages` folder within my nuxt solution using this custom module. As a result, nuxt overwrites my default page. I can solve this by adding an empty `pages` folder but it would be cleaner if there was an option to skip the default generate page step.

### What does the proposed changes look like?

I propose to add an option which overwrites the _defaultPage property (https://github.com/nuxt/nuxt.js/blob/dev/packages/builder/src/builder.js#L188)

```
this._defaultPage = this.options.skipDefaultPage || true; 
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9128">#c9128</a>)</em></sub></div>

**Comment by manniL** [comment]
Feel free to create a PR ☺️

**Comment by dietergoetelen** [comment]
Sure, will pick this up!

**Comment by pi0** [comment]
Hi. Please see https://github.com/nuxt-community/router-module/tree/master/lib

**Comment by dietergoetelen** [comment]
> Hi. Please see https://github.com/nuxt-community/router-module

Aha, thanks, exactly what I was looking for. Not sure if it's still necessary to create a pull request? What do you all think?

**Comment by pi0** [comment]
@dietergoetelen No problems :) If it works fine for you i think not. Please report any problems if you encounter.
