### ISSUE TITLE
A typescript compile error occurs when nuxt.config.ts has changed in development mode if noImplicitAny enabled.

### ISSUE THREAD

**Issue by SegaraRai** [nuxt/nuxt.js#5626]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://github.com/SegaraRai/nuxt-ts-issue-multiregister](https://github.com/SegaraRai/nuxt-ts-issue-multiregister)

### Steps to reproduce

1. clone [the repository](https://github.com/SegaraRai/nuxt-ts-issue-multiregister)
2. `npm install`
3. `npm run dev`
4. make some changes to nuxt.config.ts after first compilation finished
   - this will have nuxt rebuild whole app

### What is expected ?

work with no error

### What is actually happening?

A typescript compile error occurs.
```
 ERROR  ⨯ Unable to compile TypeScript:                                                                                  12:43:28
nuxt.config.ts:2:5 - error TS7022: '__importDefault' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

2 var __importDefault = (this && this.__importDefault) || function (mod) {
      ~~~~~~~~~~~~~~~
nuxt.config.ts:2:67 - error TS7006: Parameter 'mod' implicitly has an 'any' type.

2 var __importDefault = (this && this.__importDefault) || function (mod) {
                                                                    ~~~
nuxt.config.ts:5:5 - error TS7022: '__importStar' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

…
```

### Additional comments?

The cause of this issue is that [registerTsNode](https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/utils/typescript.js#L5) is called more than once.  
Because of this, ts-node tries compiling already transpiled .ts code and noImplicitAny error occurs.  
registerTsNode is called everytime in [_startDev](https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/commands/dev.js#L39) via [detectTypeScript](https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/utils/typescript.js#L28) and [getNuxtConfig](https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/command.js#L94).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9133">#c9133</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@SegaraRai I tested your repository it seems the issue only happens with the `package.json` import statement + using it somewhere like in `head.meta`.

Error is fixed with `"noImplicitAny": false,` tsconfig option.

Have you any proofs that `registerTsNode` is called twice ?

/cc @pi0 We don't have guard anymore to prevent multiple register calls along multiple builds ?

**Comment by SegaraRai** [comment]
Thank you for your response.

> it seems the issue only happens with the package.json import statement + using it somewhere like in head.meta.

noImplicitAny error occurs when a variable does not have type information, so if there is code like
```ts
function test(t: string) { console.log(t); }
```
, which will be transpiled into
```js
function test(t) { console.log(t); }
```
, in `nuxt.config.ts`, same error occurs on the second build.

It seems `serverMiddlerware` scripts will also retrasnspiled as with `nust.config.ts`.

---

> Error is fixed with "noImplicitAny": false, tsconfig option.

Yes, but I don't want to set `noImplicitAny` false.

---

> Have you any proofs that registerTsNode is called twice ?

This is a screenshot when I add the code below
```js
console.log('\nregisterTSNode', new Error().stack.replace(/^[^\n]+/, ''));
```
into `async function registerTSNode({ tsConfigPath, options }) {` in `node_modules/@nuxt/cli/dist/cli-chunk.js`

![ss01](https://user-images.githubusercontent.com/29276700/57567670-da79dc80-7417-11e9-83ac-982355add696.png)

**Comment by kevinmarrec** [comment]
@SegaraRai Alright, we had a guard to prevent double subscribtion but with some last refactors it seems there isn't one anymore.

I'm gonna look if we can prevent it again and hopefully it would fix your problem.

**Comment by kevinmarrec** [comment]
@SegaraRai I fixed the double registration and tested it on your repository, it fixes your issue :)
Fix can be found here : https://github.com/nuxt/nuxt.js/pull/5699 and will be shipped in next release very soon.

**Comment by SegaraRai** [comment]
Thank you!
