### ISSUE TITLE
Cannot define both SHA hash and `unsafe-inline` in CSP for best compatibility

### ISSUE THREAD

**Issue by williamchong007** [nuxt/nuxt.js#5627]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://codesandbox.io/s/p91l8w1zzq?module=%2Fnuxt.config.js](https://codesandbox.io/s/p91l8w1zzq?module=%2Fnuxt.config.js)

### Steps to reproduce

Define both `sha256` as hashAlgorithm and  `'unsafe-inline' ` in CSP script-src policy, in nuxt.config.js

### What is expected ?

Both dynamic page SHA hash and  `'unsafe-inline' ` should be present in CSP header

### What is actually happening?

Only  `'unsafe-inline' ` is present in CSP header

### Additional comments?

Follow up on https://github.com/nuxt/nuxt.js/pull/5387#issuecomment-486996379

original comment:

==========

Defining BOTH `unsafe-inline` and hash in CSP is actually a valid use case, it is for backward compatibility of CSPv1. That's why browsers with CSPv2+ support ignore it when hash is present at the same time.

[MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src):

    See unsafe inline script for an example. Specifying nonce makes a modern browser ignore 'unsafe-inline' which could still be set for older browsers without nonce support.

It is also a recommended practice suggested by google
![image](https://user-images.githubusercontent.com/6198816/56798702-e4151900-6849-11e9-93b2-7ec9644c76e7.png)

With this PR in, how can I specify BOTH `unsafe-inline` and SHA hash  for my CSP rule?

==========

Would reverting the PR, and allow a special disable value for `hashAlgorithm` to solve @sambowler 's use case a better idea?

@manniL 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9134">#c9134</a>)</em></sub></div>

**Comment by williamchong007** [comment]
Define both sha256 as hashAlgorithm and 'unsafe-inline' in CSP script-src policy, in nuxt.config.js can still reproduce the issue

**Comment by manniL** [comment]
Sounds like we should revert #5387

cc @pi0

**Comment by williamchong007** [comment]
I am getting spammed with CSP violation report from older browsers (ios9, android4, etc...) daily, will we have a fix or mitigation soon?

**Comment by manniL** [comment]
The problem is that reverting #5387 is:

1. not solving the valid problem that the PR author has
2. a breaking change

There must be a solution in between

**Comment by williamchong007** [comment]
well #5387 itself was a a breaking change for me...
How about a new csp option in nuxt.config to disable the change in #5387 ?
`unsafeInlineCompatiblity` or something shorter

**Comment by manniL** [comment]
So there are two use cases:

1. BW-compat: Have `unsafe-inline` + hash to support CSP v1
2. Use purely `unsafe-inline` and don't append the CSP hashes, because `unsafe-inline` will be ignored otherwise.

I think a flag would be good there, yes. Feel free to create a PR and thanks for the info :relaxed:
