### ISSUE TITLE
Application startup file of Nuxt js on node js cpanel

### ISSUE THREAD

**Issue by marckevinflores** [nuxt/nuxt.js#5630]
I created a setup node js app in the cpanel, I'm using namecheap hosting then I copy my project to the application root /home/marcubcd/my-website.
My question is what will be my application startup file I try to use the nuxt.config.js but is not working here the screenshot I hope that there will be an answer.

![image](https://user-images.githubusercontent.com/25529192/56975434-692e6400-6ba3-11e9-863c-6305af2e364c.png)

I look mydomain.com result
![image](https://user-images.githubusercontent.com/25529192/56975462-78151680-6ba3-11e9-849a-384a5ee148f3.png)

**Comment by paypol-software** [comment]
I have the same issue. I select the startup file ( node_modules/.bin/nuxt ) but also it doesn't work for me. the other hand I upload my project Nuxtjs on AWS Amazon it successfully runs but I don't know why it has an error in cPanel.

**Comment by modernpk** [comment]
Guys, here's the complete and step by step tutorial on how to setup nuxtjs on cpanel https://gist.github.com/modernpk/21eeadeb84a51ada5e626fddd39e9831

**Comment by circlecodesolution** [comment]
same issue please help me

**Comment by alexiej** [comment]
I cannot use SSH (nuxt start).. Your @modernpk answer requires SSH, and running process in the background. Is there any option to run nuxt using CPanel Node.js configuration?

**Comment by modernpk** [comment]
@alexiej CPanel offers terminal in the dashboard (Login to CPanel > Search Terminal). You can run `nuxt start` command from the terminal. If you don't see the Terminal in your CPanel dashboard then ask your hosting provider to enable the feature.

**Comment by alexiej** [comment]
@modernpk 


I notice that I cannot use the terminal or SSH. 

But I figure out how to use it.

1. You must set the file to be `server/index.js`, and before you need to build your app.

![image](https://user-images.githubusercontent.com/12593751/85689671-1e3eac80-b6d3-11ea-9ed1-ecdbcfa8df29.png)

2. Your `.htaccess` file in you APP_FOLDER should look like this.

# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
PassengerAppRoot "/home/XXXX/APP_FOLDER"
PassengerBaseURI "/"
PassengerNodejs "/home/XxXXXX/nodevenv/APP_FOLDER/10/bin/node"
PassengerAppType node
PassengerStartupFile server/index.js
PassengerAppLogFile "/home/XXXXX/logfile.log"
# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END

**Comment by francdore** [comment]
I have an Angular Universal app.

My entry file is main.js in the directory server/main.js.

But when I add server/main.js in the "Application startup file" field, it ignores it and uses the default app.js. It's also correct in the htaccess file but still ignores it.

**Comment by alamamir** [comment]
> @modernpk
> 
> I notice that I cannot use the terminal or SSH.
> 
> But I figure out how to use it.
> 
> 1. You must set the file to be `server/index.js`, and before you need to build your app.
> 
> ![image](https://user-images.githubusercontent.com/12593751/85690576-fef44f00-b6d3-11ea-8a57-79320ac54e39.png)
> 
> 1. Your `.htaccess` file in you APP_FOLDER should look like this.
> 
> ```
> # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
> PassengerAppRoot "/home/XXXX/APP_FOLDER"
> PassengerBaseURI "/"
> PassengerNodejs "/home/XxXXXX/nodevenv/APP_FOLDER/10/bin/node"
> PassengerAppType node
> PassengerStartupFile server/index.js
> PassengerAppLogFile "/home/XXXXX/logfile.log"
> # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END
> ```

hi what is the index.js contains?

**Comment by AP-Porag** [comment]
> @modernpk
> 
> I notice that I cannot use the terminal or SSH.
> 
> But I figure out how to use it.
> 
> 1. You must set the file to be `server/index.js`, and before you need to build your app.
> 
> ![image](https://user-images.githubusercontent.com/12593751/85690576-fef44f00-b6d3-11ea-8a57-79320ac54e39.png)
> 
> 1. Your `.htaccess` file in you APP_FOLDER should look like this.
> 
> ```
> # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
> PassengerAppRoot "/home/XXXX/APP_FOLDER"
> PassengerBaseURI "/"
> PassengerNodejs "/home/XxXXXX/nodevenv/APP_FOLDER/10/bin/node"
> PassengerAppType node
> PassengerStartupFile server/index.js
> PassengerAppLogFile "/home/XXXXX/logfile.log"
> # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END
> ```

What should be the code in server/index.js file

**Comment by anasvillain** [comment]
Please I want to host my nuxt in cpanel too but I dont know how, some one help me and give me steps on how to do it in node js server or another way.
