### ISSUE TITLE
how to use dynamic and nested route in nuxt.js?

### ISSUE THREAD

**Issue by mortezasabihi** [nuxt/nuxt.js#5638]
this is my dynamic routes in nuxt router:
```
{
      path: "/artist/:artist?",
      component: _088d981d,
      children: [{
        path: "",
        component: _284bd1c5,
        name: "artist-artist"
      }, {
        path: "related",
        component: _75d685de,
        name: "artist-artist-related"
      }]
    },
```

when i use /artist/:artist? in nuxt-link, the url doesn't change to dynamic route and its still /artist/:artist? in a tag on browser.

its should be like /artist/cardi-b.

![image](https://user-images.githubusercontent.com/35567646/57069070-c41da380-6ce8-11e9-9503-5e18be65affa.png)

totally my artist single page route should be like this:
/artist/cardi-b
and i want about page for this artist:
/artist/cardi-b/about

in here cardi-b is a artist and its dynamic, about is nested.

what structure i should use?

**Comment by colorfulberry** [comment]
@mortezasabihi 

As i think it should be work like this
![image](https://user-images.githubusercontent.com/8124046/60259891-e0197c00-990a-11e9-81e2-91d8c77ec5da.png)


you can see the dynamic route will be goes to 
`/prefectures/:alphabet`
`/prefectures/:alphabet/a`
`/prefectures/:alphabet/cities/:id`

**Comment by robitwtms** [comment]
@cmty I object. I want this answered.

**Comment by bee2b-haianhnc** [comment]
@colorfulberry 
thanks, i am finding this.
