### ISSUE TITLE
<nuxt-link> page title don't show

### ISSUE THREAD

**Issue by Xiongzhenyu** [nuxt/nuxt.js#564]
![image](https://cloud.githubusercontent.com/assets/5298655/25030358/03b9cc2a-20f7-11e7-91c2-fe7b8a1390c5.png)
when F5 refresh page can show title true.

![qq 20170414094756](https://cloud.githubusercontent.com/assets/5298655/25030428/84b3f49a-20f7-11e7-88ef-46c093e45c8a.png)

**Comment by ausir0726** [comment]
Can you provide more information about your code ?
thanks.

**Comment by Xiongzhenyu** [comment]
index page head:
```javascript
  head: {
    title: 'Buy FIFA Coins, NBA2K MT, Madden Mobile Coins and NBA Live Coins Online',
    titleTemplate: '%s - LOLGA',
    meta: [
      { hid: 'keywords', name: 'keywords', content: 'aaafifa 17 coins, fifa 17 points, cheap NBA 2K17 coins, buy madden 17 coins, NHL 17 coins, cheap fifa coins, buy wow gold, runescape gold, Nhl coins, madden coins, gamecard, cd-key' },
      { hid: 'description', name: 'description', content: 'Lolga™ is absolutely a right place for you to buy Fifa Coin(Aka Fut Coins), cheap fifa 17 points, Wow gold. We Provide with Really cheap price and 24*7 Online Service, Fast Delivery all exist here. What are you waiting for? Trust US!' }      
    ]
  },
  components: {
    Carousel
  }
```


then is checkout page:
```javascript
  head: {
    title: 'One Step Checkout'
  }
```

**Comment by ausir0726** [comment]
it's look no problem . and working on me .
Any error on your browser console or any where?

**Comment by Xiongzhenyu** [comment]
chrome console don't hava any error.
thanks for you

**Comment by ausir0726** [comment]
maybe something error with other reason ...
this is your provide code test on glitch test
https://mica-sociology.glitch.me/

[source](https://glitch.com/edit/#!/mica-sociology)

**Comment by Xiongzhenyu** [comment]
i see.
let me check code again :blush:

**Comment by Xiongzhenyu** [comment]
I found the reason.
because my checkout page import [element](https://github.com/ElemeFE/element) 
when delete element table plugin title is true

**Comment by ausir0726** [comment]
umm..  I guess have some issue with SSR you need fix .
You should close this issue , find the problem from closed issue ( maybe )

thanks.

**Comment by Xiongzhenyu** [comment]
thanks @ausir0726
