### ISSUE TITLE
Nuxt meta tags not set on direct access to page Ask Question

### ISSUE THREAD

**Issue by assemmarwan** [nuxt/nuxt.js#5641]
### Version

[2.5.1](https://github.com/nuxt.js/releases/tag/2.5.1)

### Reproduction link

[https://jsfiddle.net/y4Luh3td/](https://jsfiddle.net/y4Luh3td/)

### Steps to reproduce

I am using Nuxt SSR and utilizing the head function to generate the meta tags in a page (product page) where the meta tags will be dynamic based on the product.

However, the meta tags aren't generated if I access the page directly and testing the page on SEO checkers result in bad scores since there are no meta tags. If I navigate to the page within the website though, the meta tags are generated perfectly. Why is that?

### What is expected ?

Meta tags to be generated in the html if the page is accessed directly.

### What is actually happening?

The meta tags aren't generated in the html if the page is directly accessed. However, it is generated in case the page is accessed using nuxt-link.

### Additional comments?

    const i18nSeo = this.$nuxtI18nSeo();

    //@ts-ignore
    const item: Item = this.item;

    const setHID = (suffix: string): string => item.name + suffix;

    let images = item.__images;
    let image;
    if (images) {
      image =
        images.length !== 0
          ? getImage(images[0].file_url)
          : location.origin + '/favicon.ico';
    }

    return {
      title: item.item_name,
      meta: [
        {
          hid: item.name,
          name: item.item_name,
          content: item.description
        },
        {
          name: 'description',
          content: item.description,
          hid: setHID('description')
        },
        {
          property: 'og:title',
          content: item.item_name,
          hid: setHID('og-title')
        },
        {
          property: 'og:url',
          content: location.href.replace('=', '%3D'),
          hid: setHID('og-url')
        },
        {
          property: 'og:description',
          content: item.description,
          hid: setHID('og-description')
        },
        {
          property: 'og:image',
          content: image,
          hid: setHID('og-image')
        },
        {
          property: 'og:type',
          content: 'article',
          hid: setHID('og-type')
        },
        {
          property: 'og:site_name',
          content: 'Aljanoub',
          hid: setHID('og-site-name')
        },
        ...i18nSeo.meta
      ]
    };

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9144">#c9144</a>)</em></sub></div>

**Comment by Atinux** [comment]
@assemmarwan in order to help you, we need a reproduction link, could you please create one using http://template.nuxtjs.org ?

**Comment by MarkKras** [comment]
The meta tags are generated correctly, but on the first load they are injected before closing <head> tag.

**Comment by assemmarwan** [comment]
What do you mean by before closing tag? And how to fix it?

**Comment by assemmarwan** [comment]
These are the steps to reproduce:
1- List of data is loaded into a Vuex store in `nuxtServerInit`
2- inside asyncData, the "Product's" details, in my case, is saved in a variable called `item`.
3- Inside head, the item is accessed to set different meta tags as shown below:

``` typescript
head() {
    const i18nSeo = this.$nuxtI18nSeo();

    const item: Item = this.item;

    const setHID = (suffix: string): string => item.name + suffix;

    let images = item.__images;
    let image;
    if (images) {
      image =
        images.length !== 0
          ? ref.storage.getUrl(images[0].file_url)
          : location.origin + '/favicon.ico';
    }

    return {
      title: item.item_name,
      meta: [
        {
          hid: item.name,
          name: item.item_name,
          content: item.description
        },
        {
          name: 'description',
          content: item.description,
          hid: setHID('description')
        },
        {
          property: 'og:title',
          content: item.item_name,
          hid: setHID('og-title')
        },
        {
          property: 'og:url',
          content: location.href.replace('=', '%3D'),
          hid: setHID('og-url')
        },
        {
          property: 'og:description',
          content: item.description,
          hid: setHID('og-description')
        },
        {
          property: 'og:image',
          content: image,
          hid: setHID('og-image')
        },
        {
          property: 'og:type',
          content: 'article',
          hid: setHID('og-type')
        },
        {
          property: 'og:site_name',
          content: 'Aljanoub',
          hid: setHID('og-site-name')
        },
        ...i18nSeo.meta
      ]
    };
  },
```

Observations:
1- If the page is refreshed or accessed directly with a url, the meta tags aren't available under `<head>` except for the default set in nuxt.config.
2- However, if navigated to the page using `nuxt-link` it properly renders the meta tags under `<head>`
3- Console logging item object shows its details correctly.


I hope these steps are sufficient to describe the issue :)

**Comment by pimlie** [comment]
@assemmarwan Please create a working but minimal reproduction on codesandbox which shows us the exact issue you are experiencing. Reading your issue I have already 10+ possible questions/issues/solutions that comes to mind, but its quicker and easier for everybody if you just show whats going wrong instead of trying to explain in words whats going wrong. Hope you understand ;)

**Comment by mostafa-raafat** [comment]
@assemmarwan did you find a solution this issue i have the same behavior
