### ISSUE TITLE
head() hook not working for typescript page class

### ISSUE THREAD

**Issue by FreekVR** [nuxt/nuxt.js#5642]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://codesandbox.io/s/9390o40nn4](https://codesandbox.io/s/9390o40nn4)

### Steps to reproduce

I am using nuxt + typescript and am trying to get a dynamic page title to work using the head() function in my class, based on some asyncData I pull from an API. It doesn't seem to be called at all atm. It does work when I put the head() function in my component decorator, but in that case I cannot use the asyncData() using the `this` context

Reproduce in the sandbox at https://9390o40nn4.sse.codesandbox.io/some-page for example

### What is expected ?

The page title will be set

### What is actually happening?

It's not being set ;)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9145">#c9145</a>)</em></sub></div>

**Comment by FreekVR** [comment]
Fixed this myself, but might be good to add this kind of thing as an example to the docs?

You have to pass the `this` scope to the head function and add it to the component decorator.

Like this:

```
// The @Component decorator indicates the class is a Vue component
@Component({
    asyncData({ params, error }): Promise<any> {
        ...
    },

    head(this: MyPageClass): object {
        return {
            title: this.myAsyncData,
            meta: [
                // hid is used as unique identifier. Do not use `vmid` for it as it will not work
                { hid: 'description', name: 'description', content: 'My custom description' }
            ]
        };
    }
})

class MyPageClass extends Vue {
    myAsyncData?: string
...
```

**Comment by clementmas** [comment]
I was also looking for this. I think it should be in the docs.

Either you put it inside the `@Component` declaration or you can create a custom `@Meta` decorator (see this issue: https://github.com/nuxt/vue-meta/issues/181)

**Comment by manniL** [comment]
cc @kevinmarrec
