### ISSUE TITLE
Middleware promise to resolve prior to rendering page

### ISSUE THREAD

**Issue by borisdayma** [nuxt/nuxt.js#5644]
### What problem does this feature solve?

When using a promise within a middleware, we cannot wait for it to be resolved prior rendering the page. It can be an issue when using an auth API based on promises.

### What does the proposed changes look like?

We should be able to use following code.

```
export default function({ route, redirect }) {
  my_API.getAuthenticatedUser() // Promise
    .catch(() => {
      return null
    })
    .then(user => {
      // Anonymous users
      if (!user) redirect('/login')

      // Authenticated users
      if (user) do_something_else()
    })

  // This does not seem to change anything at the moment
  return Promise.resolve
}
```

We should be able to choose whether the middleware promise needs to resolve or not.

With vue-router, we can choose whether the promise needs to be resolved or not depending on where we use  `next()` (in `then` section or after the promise).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9147">#c9147</a>)</em></sub></div>

**Comment by borisdayma** [comment]
Problem solved by doing `return my_API.getAuthenticatedUser()...`
Thanks to @rafal on Discord.

*Note*: page shows a logging screen but parts of it are still executing. For example I still get a console output from protected page (which shows a loading screen) if I include the following code in it:
```
<script>
console.log('THIS SHOULD NOT APPEAR')
[...]
</script>
```
I expected that no code at all from this page would be executed.

**Comment by mikedoan** [comment]
I guess we can close this issue @borisdayma

**Comment by borisdayma** [comment]
I agree, can you just confirm that executing the <script> section from protected page is expected behavior? I wonder if my functions would be executed in async or fetch.

**Comment by Atinux** [comment]
@borisdayma the page bundle is imported anyway, which makes the `console.log` being called.

The middleware is protecting the creating of the page (ie: `new Vue(page)`), so you want to add these console.log in the page hooks (ie: `created`, `mounted`, `asyncData`...).

**Comment by MSkred** [comment]
Hi all,

I use a middleware for check multiple things :

If my route need auth
If my user have a token in his cookie
If his token is valid
a. YES: NO PROB
b. NO: I refresh his token with a refreshtoken and stock result (accesstoken, refreshtoken, expiresin) in cookie
But when I navigate in a route that requires auth and when his token is not valid

I can't await my dispatch from middleware before executing asyncData from my page

Then my token is successfully refreshed but the used token in my dispatch from asyncData use an old token

I want to await the refresh dispatch before execute my dispatch in asyncData

**Comment by KGBemployee** [comment]
I am also encountering problems with this. 
This should be re-opened and an option to have the middleware as blocking should be added.

**Comment by cfofiu** [comment]
I'm being hit by this issue as well! Would like for the middleware promise to resolve prior to rendering page! Or am I missing something?

**Comment by MSkred** [comment]
@Atinux @pi0 can something do that?

**Comment by cfofiu** [comment]
Well I put in a work around where I'm watching the store property (which gets updated form the middleware) and then running the rest of the code, but I'm not a fan of this approach.

**Comment by KGBemployee** [comment]
I managed to make the middleware return the promise by using the suggested change directly in the middleware. Now a page doesn’t load until the promise is resolved. 
The approach is ok but I still think it would have been nice to have a way to do that out of the box.

**Comment by cfofiu** [comment]
@KGBemployee do you mind sharing some code and elaborate more?
