### ISSUE TITLE
TypeError: boxen is not a function  

### ISSUE THREAD

**Issue by herrdu** [nuxt/nuxt.js#5659]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Steps to reproduce

create nuxt-app , then change js to ts, and run ' yarn dev  '.

### What is expected ?

╭───────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                               │
   │   IMPORTANT : Package deprecation                                                             │
   │                                                                                               │
   │   Nuxt TypeScript Support has been refactored to be used with nuxt package.                   │
   │   Which means that nuxt-ts package is now no longer needed and is now tagged as deprecated.   │
   │   We highly recommend to follow the guidelines below :                                        │
   │                                                                                               │
   │   Migration guide (2.5.x)                                                                     │
   │                                                                                               │
   │   Using yarn                                                                                  │
   │   yarn remove nuxt-ts                                                                         │
   │   yarn add nuxt                                                                               │
   │   yarn add -D @nuxt/typescript                                                                │
   │                                                                                               │
   │   Using npm                                                                                   │
   │   npm uninstall nuxt-ts                                                                       │
   │   npm install nuxt                                                                            │
   │   npm install -D @nuxt/typescript                                                             │
   │                                                                                               │
   │    ----- nuxt.config.ts -----                                                                 │
   │   | build: {                 |                                                                │
   │   | -- useForkTsChecker: ... |                                                                │
   │   | ++ typescript : {        |                                                                │
   │   | ++   typeCheck: ...      |                                                                │
   │   | ++ }                     |                                                                │
   │   | }                        |                                                                │
   │    --------------------------                                                                 │
   │                                                                                               │
   │   Find more information in updated docs : https://nuxtjs.org/guide/typescript                 │
   │                                                                                               │
   ╰───────────────────────────────────────────────────────────────────────────────────────────────╯

   ╭─────────────────────────────────────────────╮
   │                                             │
   │   Nuxt.js v2.6.3                            │
   │   Running in development mode (universal)   │
   │   TypeScript support is enabled             │
   │                                             │
   │   Listening on: http://localhost:3000/      │
   │                                             │
   ╰─────────────────────────────────────────────╯

### What is actually happening?

/Users/herrdu/project/4paradigm/zhongbaoyun/ued-front/node_modules/nuxt-ts/bin/nuxt-ts.js:7
  boxen(
  ^

TypeError: boxen is not a function
    at Object.<anonymous> (/Users/herrdu/project/4paradigm/zhongbaoyun/ued-front/node_modules/nuxt-ts/bin/nuxt-ts.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Additional comments?

In nuxt-ts.js file , I found 
```
const boxen = require("boxen").default;

```

If I modify it as beblow :
```
const boxen = require("boxen");

```
It will be correct.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9156">#c9156</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@herrdu Please use new TypeScript behavior https://nuxtjs.org/guide/typescript for now, we intentionally deprecated `nuxt-ts` in `2.5` so it's not intending to be used with `2.6`.

We're planning to bring new changes for TypeScript Support which will bring the `nuxt-ts` binary back, until then I can only highly advice you to use the recommended TypeScript Support setup you can find in the Nuxt documentation.

**Comment by kevinmarrec** [comment]
@herrdu And sorry for the inconvenience that `create-nuxt-app` is not updated with the last TS specs, we're working on it.
