### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#5661]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

Not sure yet unfortunately

### What is expected ?

Nuxt works

### What is actually happening?

An `Object(...) is not a function` error is shown when `setContext` is called in `.nuxt/index.js`

Sometimes during development this error happens. I am not exactly sure yet what triggers it, sometimes it happens once a day and sometimes 10+ times.

What I know about it so far:
- The error is caused because the `.nuxt/utils` import returns an empty object
- The utils file does exist and when executed with `--experimental-modules` node has a 0 exit status (so no syntax errors in the file)
- Deleting the utils module from require.cache did not solve the issue
- Restarting the dev server made the error go away
- It doesnt seem to have to do with a long running dev server, this morning I had it within 20mins of starting work

Although restarting the dev server is a good enough solution,  rebuilding the whole project can take quite a bit of time which can be frustrating.

### Additional comments?

First reported here: https://stackoverflow.com/questions/55949558/how-to-solve-object-is-not-a-function-error-in-nuxt

Screenshot of error: https://i.imgur.com/CEoHxQq.png

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9157">#c9157</a>)</em></sub></div>

**Comment by pi0** [comment]
One i experienced this issue on code-sandbox (no extra integrations - just nuxt) by very first reload.

**Comment by pimlie** [comment]
Its also not unique for `.nuxt/utils`, I just received the error with `.nuxt/server.js` for the `.nuxt/index.js` import (the not a function error was on createApp this time). But because I tried to add some debug logs to that file, the dev server reloaded and now I get:

```
ERROR in ./.nuxt/utils.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /var/project/.nuxt/utils.js: Unterminated string constant (454:27)

  452 |       const token = tokens[i]
  453 | 
> 454 |       if (typeof token === 'st
      |                            ^
    at Object.raise (/var/project/node_modules/@babel/parser/lib/index.js:6322:17)
   ...
```
but if I look inside `.nuxt/utils` it just shows:
```
    for (let i = 0; i < tokens.length; i++) {
      const token = tokens[i]

      if (typeof token === 'string') {
        path += token

        continue
      }
```
So apparently there is either some memory corruptions in the dev server somewhere or an IO issue which doesnt or only partially reads the module file?

**Comment by dschreij** [comment]
I'm having the same error. I'm using Nuxt 2.7.1  After a random amount of time the error occurs, after a hot-reload attempt by the dev server. To solve the error I have to restart the dev server. For me it always occurs in `nuxt/index.js:113:19` in `createApp`.
The traceback that is shown:

```javascript
// ...
  const path = getLocation(router.options.base)
    route = router.resolve(path).route
  }

  // Set context to app.context
  await setContext(app, {
    route,
    next,
    error: app.nuxt.error.bind(app),
    store,
    payload: ssrContext ? ssrContext.payload : undefined,
// ...
```

**Comment by pi0** [comment]
This error seems completely random when generating templates. Webpack tries to read the source when it is not completely written to the disk...

**Comment by EHfive** [comment]
I can confirm this with v2.6.3 on Linux.
But seems it's OK with v2.7.1.

**Comment by BonnieDoug** [comment]
I've also been trouble-free since upgrading 2.7.1

**Comment by pimlie** [comment]
I have not seen the error anymore in my current project after upgrading to time-fix-plugin v2.0.6, but as the error shows so erratically its difficult to say whether the issue really has gone.

@pi0 Maybe a bit far-off, but do you think this issue could be related somehow to #5650 ?

**Comment by dschreij** [comment]
In my case on Linux it hasn't happened yet with 2.7.1, but on Windows 10 it does occur frequently,

**Comment by pimlie** [comment]
Just had the error again on Linux with 2.7.1, but this project still used time-fix-plugin v2.0.5. Will upgrade to 2.0.6. and see what happens

**Comment by pi0** [comment]
Let's hope magically fixed :) (BTW Please report back if still occurs)

**Comment by augnustin** [comment]
+1 here, just had the error with:

```
nuxt@^2.0.0:
  version "2.11.0"
  resolved "https://registry.yarnpkg.com/nuxt/-/nuxt-2.11.0.tgz#654664fe1a95af2014fd55c38ba2c732bfa5edc5"
  integrity sha512-Y7lastjYWIOppja0FaWozPfkvlmJ8uZSqWx0VbK7l5djbHls5jgUGag0iu6GsNNwCFTKpoAtptNHiWOsyMxStA==
  dependencies:
    "@nuxt/builder" "2.11.0"
    "@nuxt/cli" "2.11.0"
    "@nuxt/core" "2.11.0"
    "@nuxt/generator" "2.11.0"
    "@nuxt/loading-screen" "^1.2.0"
    "@nuxt/opencollective" "^0.3.0"
    "@nuxt/webpack" "2.11.0"
```

**Comment by Cally99** [comment]
Bugxt.js. This is the most frustrating error riddin piece of crap framework on the internet. I'm using the most up to date version in 2022 and this is still and issue.

**Comment by Cheaterman** [comment]
I had the issue here, fixed by using Node LTS image on my docker container instead of non-LTS (presumably latest).
