### ISSUE TITLE
context.app's type is a Vue instance

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#5662]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://nuxtjs.org/api/context](https://nuxtjs.org/api/context)

### Steps to reproduce

Type of context.app is defined as `Vue` [1] but it isn't really a Vue instance. It's just an object with root Vue instance *options* and also optionally other stuff injectected manually from plugins or through `inject` function.

[Documentation](https://nuxtjs.org/api/context) is also confused about it. It says `type = Root Vue Instance` but in description it says `The root Vue instance *options* that includes all your plugins.` (emphasis mine).

### What is expected ?

`context.app` doesn't bare `Vue` type but something custom.

### What is actually happening?

`context.app` type is `Vue`.

### Additional comments?

[1] https://github.com/nuxt/nuxt.js/blob/a88e8b60c75da3f8c9d6bd9b32e00e03d6400b9d/packages/vue-app/types/index.d.ts#L17

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9159">#c9159</a>)</em></sub></div>

**Comment by rchl** [comment]
@kevinmarrec in a way this is related to #5589
@manniL I would say this is both typescript and documentation issue

**Comment by rchl** [comment]
In other words, `context.app` is not the same as `this.$root` in context of a component. Latter is actuall instance of `Vue` object, former is just an object with some properties.

**Comment by kevinmarrec** [comment]
@rchl Do you thing having `app` of this type : https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/types/index.d.ts#L84 could be enough ? This type is only used for `this.$nuxt` for now.

In scope of a component, does `context.app` is the same as `this.$nuxt` ? `this.$nuxt` might probably be different from `this.$root`.

**Comment by rchl** [comment]
@kevinmarrec: $nuxt and $root are the same it seems:
```js
this.$nuxt === this.$root
true
```

So app is neither of those and it wouldn't be correct to have it extend `Vue` type IMO.

**Comment by kevinmarrec** [comment]
@rchl Alright, seems we might need an extra `ContextApp` interface then, but dunno what's are really all the properties of `context.app` about. Seems to be Component options

**Comment by rchl** [comment]
Yes, it seems it is an ComponentOptions.

It's:
 - defined at https://github.com/nuxt/nuxt.js/blob/2fd05e0fe3dc26f2f9ec66befb8c56c089affe5b/packages/vue-app/template/App.js#L19
 - extended with more properties in createApp function https://github.com/nuxt/nuxt.js/blob/2fd05e0fe3dc26f2f9ec66befb8c56c089affe5b/packages/vue-app/template/index.js#L46
 - used to instanciate root Vue instance https://github.com/nuxt/nuxt.js/blob/2fd05e0fe3dc26f2f9ec66befb8c56c089affe5b/packages/vue-app/template/client.js#L81-L82

**Comment by kevinmarrec** [comment]
@rchl Yes , so `context.app` type need to be revisited, I'm gonna work on it along other TypeScript changes & refactors really soon.

**Comment by Atinux** [comment]
I should have named it `appOptions` 🤔

**Comment by kevinmarrec** [comment]
@rchl I created a PR to fix the type and this `context.app` confusion https://github.com/nuxt/nuxt.js/pull/5701 ;)
