### ISSUE TITLE
inject: false in bundleRenderer config not work

### ISSUE THREAD

**Issue by maunier** [nuxt/nuxt.js#5664]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://github.com/maunier/nuxt-learning](https://github.com/maunier/nuxt-learning)

### Steps to reproduce

1. npm run dev 
2. visit http://localhost:3000/

### What is expected ?

html shouldn't load any script because I have configed "inject: false" for bundleRenderer in nuxt.config.js

### What is actually happening?

it loads "commons.app.js" "vendors.app.js" and so on.

### Additional comments?

i need a template that automaticly inject all the script at IE10+ otherwise  don't inject any script 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9162">#c9162</a>)</em></sub></div>

**Comment by RafaelGSS** [comment]
Remove your `package-lock.json` and install again, the dependencies installed in `package-lock.json` not match with `package.json`.

**Comment by maunier** [comment]
> Remove your `package-lock.json` and install again, the dependencies installed in `package-lock.json` not match with `package.json`.

I have removed `package-lock.json` and `node_modules` and installed again, but the page still loads all the script.

**Comment by maunier** [comment]
> Remove your `package-lock.json` and install again, the dependencies installed in `package-lock.json` not match with `package.json`.

I'm so sorry to bother you, but could you help me find out the reason why it not worked.

**Comment by RafaelGSS** [comment]
@maunier  Hello!

recently I've been busy, but today I'll try to verify this.
