### ISSUE TITLE
How do i fix Nuxt Warning 'nuxt build finished but did not exit after 5s'?

### ISSUE THREAD

**Issue by highalps** [nuxt/nuxt.js#5669]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

i thinks it happen when migrate to nuxt 2.x version from any version

### What is expected ?

not appearing ⚠ Nuxt Warning

### What is actually happening?

   ╭───────────────────────────╮
   │                                                                                                                │
   │   ⚠ Nuxt Warning                                                                               │
   │                                                                                                                │
   │   The command 'nuxt build' finished but did not exit after 5s      │                      
   │                                                                                                                │ 
   │   This is most likely not caused by a bug in Nuxt.js                        │           
   │                                                                                                                │                                                                                
   │   Make sure to cleanup all timers and listeners you or your          │
   │      plugins/modules start.                                                                  │
   │   Nuxt.js will now force exit                                                                │
   │                                                                                                                 │
   │   DeprecationWarning: Starting with Nuxt version 3 this will .    │
   │     be a fatal error                                                                                  │
   │                                                                                    
   ╰───────────────────────────╯

### Additional comments?

i have no idea from warning message `Make sure to cleanup all timers and listeners you or your plugins/modules start`.

i already check out pluggins and module directory i wrote before, 
but there's no timer/interval expressions.

 how can i found cause of this things?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9167">#c9167</a>)</em></sub></div>

**Comment by highalps** [comment]
@manniL 

i found nuxt warning occuured when `mongose.connect` in serverMiddleware. 

how do i handle it..?


in nuxt.config.js
```
serverMiddleware: [
   '~/serverMiddleware/index.js'
]
```


in `~/serverMiddleware/index.js'

```
const app = express()

mongoose.connect('....') // it is problem

app.use('/api', require('.......')
```

how can i handle it?

**Comment by Atinux** [comment]
The issues comes because we actually import the `serverMiddleware` when running `nuxt build`.

What you can do instead is to create a module for it @highalps 

`~/nuxt.config.js`:
```js
export default {
  modules: ['~/modules/api']
}
```

`~/modules/api/index.js`:
```js
module.exports = function (moduleOptions) {
  // Add middleware only with `nuxt dev` or `nuxt start`
  if (this.options.dev || this.options._start) {
    this.addServerMiddleware('~/api/')
  }
}
```

`~/api/index.js`:
```js
const express = require('express')
const app = express()

mongoose.connect('....') // it is problem

app.use('/', require('.......'))

module.exports = { path: '/api', handler: app }
```

You can learn more on https://nuxtjs.org/guide/modules

We are talking with the core team to work on a solution to avoid includes the serverMiddleware when running `nuxt build`.

But mostly, we will soon have Nuxt services allowing to create your API in your Nuxt app without having to add serverMiddleware (better for perf & memory management + hot reloading).

**Comment by highalps** [comment]
@Atinux thanks a lot!!

**Comment by fatid** [comment]
I'am  building a nuxt & electron & express  application.
Eveverything is ok when  i build & start an application on web.
But when i use electron-builder, it works on developer mode, but not on production.

I think, i need to add a  new parameter, etc:  || this.options.ELECTRON. But what is it ? 

     if (this.options.dev || this.options._start  || etc. this.options.ELECTRON) {
       this.addServerMiddleware('~/server/index.js')
    }

**Comment by AndrewBogdanovTSS** [comment]
I started getting this issue once I enabled `HardSourceWebpackPlugin` in production build

**Comment by AndrewBogdanovTSS** [comment]
I was able to reproduce an issue when running `nuxt build` locally without `HardSourceWebpackPlugin` enabled so I guess it's not related

**Comment by stouch** [comment]
same problem here. I also use recently ```HardSourceWebpackPlugin```

**Comment by fpl1104** [comment]
when i use parallel in build ，i get this issue

**Comment by arnabrahman** [comment]
@fpl1104 Same here. According to nuxt doc, parallel is an ⚠️ Experimental feature i think.

**Comment by AndrewBogdanovTSS** [comment]
Is there any way to fix it by not disabling `parallel` option?

**Comment by fpl1104** [comment]
@arnabrahman Obviously yes, but how can I fix it?

**Comment by AndrewBogdanovTSS** [comment]
@Atinux please, reopen this issue since it can be reproduced with parralel:true and it's still occurring in 2.13.1

**Comment by gitamgadtaula** [comment]
@Atinux Hey Atinux, I am working on a project with Nuxt and I am getting this issue; I am using fully SPA mode with ssr:false and I dont have firebase. My team considers it to be a serious issue and I am figuring hard time figuring out whats wrong. Unfortunately I cannot share my code but could you please give me a general idea of what might be happening. I am using few nuxt modules like 'Auth-next, google-analytics, nuxt-axios, nuxt-speedkit' and few others. I have couple of middlewares too but they are pretty simple and they don't have any timers; neither do any plugins. 

this is my build configuration
```

build: {
    parallel: false,
    cache: true,
    hardSource: true,
    transpile: [/^element-ui/, /^vue2-google-maps($|\/)/],
    // maxChunkSize: 100000,
    babel: {
      compact: true,
    },
    extend(config, { isDev, isClient }) {
      // config.resolve.alias['chart.js'] = 'chart.js/dist/Chart.js'
      if (isClient && !isDev) {
        config.optimization.splitChunks.maxSize = 250000;
        config.performance.hints = false;
        config.devtool = false;
      }
    },
    // analyze: true,
    // parallel: false,
    // cache: true,
    // hardSource: true,
  },
```

Any kind of response is highly highly appreciated.

**Comment by gitamgadtaula** [comment]
> @Atinux Hey Atinux, I am working on a project with Nuxt and I am getting this issue; I am using fully SPA mode with ssr:false and I dont have firebase. My team considers it to be a serious issue and I am finding hard time figuring out whats wrong. Unfortunately I cannot share my code but could you please give me a general idea of what might be happening and why would the issue occur? I am using few nuxt modules like 'Auth-next, google-analytics, nuxt-axios, nuxt-speedkit' and few others. I have couple of middlewares too but they are pretty simple and they don't have any timers; neither do any plugins.
> 
> this is my build configuration
> 
> ```
> 
> build: {
>     parallel: false,
>     cache: true,
>     hardSource: true,
>     transpile: [/^element-ui/, /^vue2-google-maps($|\/)/],
>     // maxChunkSize: 100000,
>     babel: {
>       compact: true,
>     },
>     extend(config, { isDev, isClient }) {
>       // config.resolve.alias['chart.js'] = 'chart.js/dist/Chart.js'
>       if (isClient && !isDev) {
>         config.optimization.splitChunks.maxSize = 250000;
>         config.performance.hints = false;
>         config.devtool = false;
>       }
>     },
>     // analyze: true,
>     // parallel: false,
>     // cache: true,
>     // hardSource: true,
>   },
> ```
> 
> toggling parallel option didn't help either.
> 
> Any kind of response is highly highly appreciated. Thanks.

I found out that the issue is caused is Nuxt-speed-kit. I have found this module pretty useful but I cannot use it with this warning. Is there anyway to work around we can do as that I could get rid of the warning and also use the niceness of the library ?
