### ISSUE TITLE
Pages bundles. How to combine them selectively?

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [nuxt/nuxt.js#567]
Hello,
As I understand nuxt bundles every page by default into a separate bundle(**app**).
How to selectively combine few pages or set not to bundle them separately?

**Comment by Atinux** [comment]
Hi @OlzhasAlexandrov 

Nuxt.js is an opinionated framework and will always code-split every route. This behavior cannot be changed I'm sorry.

I'm thinking of a kind of "expert" mode for avoiding the `pages` directory by creating a `router.js` file, this way you will have full control of the pages you want to code-split or not.

**Comment by OlzhasAlexandrov** [comment]
Thank you for the answer and I'm glad that there is a possibility of adding that feature:)

**Comment by awronski** [comment]
@Atinux Export mode would be great!!

**Comment by rvanzon** [comment]
but for now, is there a hack or something to combine the chunks or reduce the requests? I have 30-requests now on chunks alone, this takes performance down a lot...

**Comment by rvanzon** [comment]
Ok, I think I have a solution, add this to the `build`-section of `nuxt.config.js`

```
plugins: [
    new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 3        
    })
],```

(so above `extend` for example).

Then build your project with `npm run build`. Et voilà, No more than 3 chunks :-)

Have to test some more, maybe fiddle with the maxChunks maybe. For now loading went from 1.2s to 600ms!

**Comment by Atinux** [comment]
It's an elegant solution you found @rvanzon :-)
