### ISSUE TITLE
Server render error RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pathawee** [nuxt/nuxt.js#568]
![screen shot 2560-04-14 at 9 11 18 pm](https://cloud.githubusercontent.com/assets/5134572/25045648/7ba29432-2157-11e7-85a3-db0cf87dbb43.png)

I got this error when I use `v-for` dynamic components on server side render.
If data less then 10 records it's work fine and use client render it's work too.
Error only use server side render. How do I solve?

` <component v-for="element in dataItems" :is="element.name" :key="element.id"></component>`
here is my json data 
```
[
  {
    "id": "1",
    "name": "Layout12"
  },
  {
    "id": "2",
    "name": "Layout12"
  },
  {
    "id": "3",
    "name": "Layout12"
  },
  {
    "name": "Layout12",
    "id": "4"
  },
  {
    "name": "Layout12",
    "id": "5"
  },
  {
    "name": "Layout12",
    "id": "6"
  },
  {
    "name": "Layout12",
    "id": "7"
  },
  {
    "name": "Layout12",
    "id": "8"
  },
  {
    "name": "Layout12",
    "id": "9"
  },
  {
    "name": "Layout12",
    "id": "10"
  }
]
```

**Comment by guillaumechereau** [comment]
Was this issue resolved?  I have the same problem.

**Comment by mvgrimes** [comment]
I ran into this with a couple of `<select>`s with less than 80 `<option>`s each. I was able to work around this by increasing the call stack size:

     node --stack-size=1500 node_modules/.bin/nuxt

This increases the call stack size from the default 984 (on my machine) to 1500. Per [this StackOverflow question](https://stackoverflow.com/questions/20748061/what-is-the-default-stack-size-in-node-js), you can find the default stack size with: 

    node --v8-options | grep -B0 -A1 stack_size

I'm encouraged that such a small increase fixed the issue, but clearly nuxt is doing some pretty deep recursion.
