### ISSUE TITLE
nuxtjs/proxy does not work in generated mode?

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [nuxt/nuxt.js#5680]
![image](https://user-images.githubusercontent.com/23397455/57443109-f34f8a00-727f-11e9-83c9-f288f1a84d4c.png)
我现在想将nuxt项目，静态部署在tomcat上，但是我的后台是springboot端口8081，web端口是8080，请求跨域了。之前是
![image](https://user-images.githubusercontent.com/23397455/57443223-242fbf00-7280-11e9-81ce-dbe5ce3160a9.png)可以请求数据；现在是generate，proxy失效了....有什么好的解决办法么

**Comment by manniL** [comment]
No, it does not.
