### ISSUE TITLE
Add Style for printer

### ISSUE THREAD

**Issue by eseceve** [nuxt/nuxt.js#5683]
### What problem does this feature solve?

I need to add a stylesheet (css/scss/etc) only for printer

### What does the proposed changes look like?

```
// nuxt.config.js
css: [{src: '@/assets/printer.scss', media: 'print'}]
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9177">#c9177</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@eseceve You can use `media-dependent @import`, like:

```js
// nuxt.config.js
css: ['@/assets/main.scss']
```

```scss
@import '@/assets/main.scss' print;
```

Related Doc:
https://developer.mozilla.org/en-US/docs/Web/CSS/@import
https://sass-lang.com/documentation/at-rules/import#plain-css-imports
