### ISSUE TITLE
app.html is rendered incorrectly.

### ISSUE THREAD

**Issue by Miaoxingren** [nuxt/nuxt.js#5685]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://codesandbox.io/embed/pymmj2r9x7](https://codesandbox.io/embed/pymmj2r9x7)

### Steps to reproduce

I add app.html to root dir.
```html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head {{ HEAD_ATTRS }}>
	  <script>window.ts_start=+new Date()</script>
    {{ HEAD }}
    <script>window.ts_head=+new Date()</script>
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}
    <script>window.ts_body=+new Date()</script>
  </body>
</html>
```

### What is expected ?

Expect `<script>window.ts_body=+new Date()</script>`  to be placed before `</body>`

### What is actually happening?

`<script>window.ts_body=+new Date()</script>` is places after bundle scripts.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9178">#c9178</a>)</em></sub></div>

**Comment by Atinux** [comment]
Since most of the scripts are using `defer`, is it really an issue?

**Comment by clarkdo** [comment]
@Atinux is correct, all the `bundle scripts` are also pre-fetched by `prefetch` tag in `head`

The reason why the script is after `bundle scripts` is:

In SPA mode, `bundle files` are injected into `app.html` while webpack building step by `html-webpack-plugin`.

And `html-webpack-plugin` body injection will put all bundles right before `</body>`.

@Miaoxingren If you want to get time of body loaded, you can try DOM events like  `DOMContentLoaded`, `readystatechange` or `load`

**Comment by Miaoxingren** [comment]
@Atinux In SPA mode, scripts of index.html generated are not using defer.

@clarkdo Thanks for the answer. What if I want to get time of head stylesheet loaded? 
like this:
```
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head {{ HEAD_ATTRS }}>
    {{ HEAD }}
    <script>window.ts_start=+new Date()</script>
    {{ HEAD_CSS }}
    <script>window.ts_css=+new Date()</script>
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}
    <script>window.ts_body=+new Date()</script>
   {{ APP_BUNDLE_SCRIPT  }}
    <script>window.ts_script=+new Date()</script>
  </body>
</html>
```

If I change `inject` of `html-webpack-plugin` to false in spa mode and use htmlWebpackPlugin.files to add resources in app.html, will it be harmful?
