### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined 

### ISSUE THREAD

**Issue by divyadave95** [nuxt/nuxt.js#5692]
I encountered this error while run the nuxt project new in this. What this error mean?
How to solve this error?

**Comment by Dahdoul** [comment]
having the same issue on nuxt v2.6.3

**Comment by Ramarti** [comment]
This happened to me when adding nuxt-i18n to the nuxt.config.js
