### ISSUE TITLE
TypeScript: extendRoutes parameter routes possibly should be of type RouteConfig[]

### ISSUE THREAD

**Issue by renestalder** [nuxt/nuxt.js#5693]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/named-views](https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/named-views)

### Steps to reproduce

Te reproduction link is actually the example from the documentation as I really don't find the time to setup a TypeScript project for this. It's also not necessary to reproduce it. Looking at the types of vue-router and the non-TypeScript example should make things clear.

The code example for Nested Views shown in the Nuxt documentation shows how to use `extendRoutes` in the nuxt.config.js to access the `children` attribute of the parameter `routes`.

The parameter `routes` is of type `Route[]`. The type `Route` actually doesn't have a property `children` per typing definition. But the type `RouteConfig`.

https://router.vuejs.org/api/#router-construction-options

My assumption is, the parameter `routes` should be of the type `RouteConfig`.

### What is expected ?

No TypeScript error when accessing `routes[index].children` in the nuxt configuration.

### What is actually happening?

TypeScript error `Property 'children' does not exist on type 'Route'`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9183">#c9183</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@renestalder Thanks for finding this, it should be `RouteConfig[]` instead of `Route[]` here : , right ? https://github.com/nuxt/nuxt.js/blob/dev/packages/config/types/router.d.ts#L12

**Comment by renestalder** [comment]
Yes, that's correct. But now I also found out that you probably extend the route here even further. `chunkNames` also seems missing and this is not an attribute of `RouteConfig` so it might even be a better solution to extend `RouteConfig` with a new type and add `chunkNames` (maybe there are also other additional properties I don't know about).

Example:

```ts
import { RouterOptions, Route } from 'vue-router'

interface NuxtRoute extends RouteConfig {
  chunkNames: {[key: string]: string};
}

export interface NuxtConfigurationRouter extends RouterOptions {
  routeNameSplitter?: string
  extendRoutes?: (routes: NuxtRoute[], resolve: (...pathSegments: string[]) => string) => void
  linkPrefetchedClass?: string
  middleware?: string | string[]
  prefetchLinks?: boolean
}
```

Maybe one would even find a way to property match `chunkNames` and `components` in TypeScript, excluding the `components.default` property, as I assume from the example they require to have matching properties to work.

**Comment by kevinmarrec** [comment]
@renestalder You're right for `chunkNames` (https://github.com/nuxt/nuxt.js/blob/dev/examples/named-views/nuxt.config.js#L12)

Could you open a PR with the changes from your snippet ? (You'll need to replace `Route` by `RouteConfig` in import statement and remove extra semicolon in `NuxtRoute` interface, furthermore I'd suggest `NuxtRouteConfig` instead of `NuxtRoute`). We should be able to bring this for next release (https://github.com/nuxt/nuxt.js/pull/5678)

**Comment by renestalder** [comment]
@kevinmarrec Thank you very much for the quick fix. And also for the co-authoring credit. Very kind. I appreciate that.

Keep up the great work.
