### ISSUE TITLE
Plugin Filename drives mode via addPlugin

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt.js#5694]
### What problem does this feature solve?

With the latest version of nuxt, plugins go to the right build via their filename when they are referenced in nuxt.config.js
  
plugin.server.js > goes to server bundle
plugin.client.js > goes to client bundle
plugin.js > goes to both

This functionality doesn't seem to work when adding plugins via modules using .addPlugin

This forces people to do .addPlugin( src:'...', mode:'something') when I'd expect the 'default' mode to be based off the source filename

https://nuxtjs.org/api/internals-module-container#addplugin-template-

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9184">#c9184</a>)</em></sub></div>

**Comment by pi0** [comment]
@hecktarzuli thanks for this note. Yes, that would be more consistent. However, if we support this feature in a nuxt minor release, your module is only compatible with this version upwards and unsafe to use on older versions.

**Comment by pi0** [comment]
BTW are you sure omitting `mode` does not triggers auto mode detection? `addPlugin` adds to the same array and it will be processed here: https://github.com/nuxt/nuxt.js/blob/dev/packages/builder/src/builder.js#L272

**Comment by pi0** [comment]
Reproduce: https://github.com/pi0/nuxt-module-plugin-mode

Plugin is only included in client side.

**Comment by hecktarzuli** [comment]
Yes, I tried it first omitting mode, assuming it worked as expected.  Then I inspected ./nuxt/index.js and saw the plugin comment said 'all'.

After passing mode, it changed to whatever i passed

**Comment by hecktarzuli** [comment]
![image](https://user-images.githubusercontent.com/2112282/57551960-015ce380-7330-11e9-9b49-cb42b5fc696f.png)

**Comment by hecktarzuli** [comment]
![image](https://user-images.githubusercontent.com/2112282/57551996-189bd100-7330-11e9-8ae2-fe88e7c11a9e.png)

**Comment by pi0** [comment]
@hecktarzuli Right. I got the issue. It is because without providing `fileName` the generated name will be like `mode-test.plugin.client.530b6c6a.js` and regex fails to detect extension. Will open a PR for fix.

**Comment by hecktarzuli** [comment]
👍

**Comment by hecktarzuli** [comment]
@pi0 as Whitney Houston once said, "you are the wind beneath my wings".
