### ISSUE TITLE
Skrollr is not working

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#570]
I create a plugin **skrollr.js**
```
if (process.BROWSER_BUILD) {
  require('skrollr')
}
```
Then in **nuxt.config.js**
```
  plugins: [
    {src: '~plugins/skrollr', ssr: false},
]
```
But data attributes in my **parallax.vue** is not changing. 
There are no errors in console.

**Comment by ausir0726** [comment]
HI ,

I don't what happen , but skrollr.js is working on my test
https://maddening-file.glitch.me/

[source](https://glitch.com/edit/#!/maddening-file)

you can try it on Glitch

**Comment by ausir0726** [comment]
Hi , 

I don't know what happen .
but skrollr.js is working on my test 

https://nuxt-skrollr-test.glitch.me/
[source](https://nuxt-skrollr-test.glitch.me)

you can try it on Glitch .

I have a project been used.

**Comment by kodekrendel** [comment]
@ausir0726 strange...Source?

**Comment by kodekrendel** [comment]
@ausir0726 is that an Express?

**Comment by ausir0726** [comment]
@kodekrendel  sorry , my bad , paste wrong link ....
link fixed .

**Comment by ausir0726** [comment]
@kodekrendel  no , just nuxt starter .

**Comment by kodekrendel** [comment]
@ausir0726 so you basically doesn't use a plugin? Load Skrollr directly in .vue page?

**Comment by ausir0726** [comment]
Yes ,
because skrollr just a front-end visual effect .
so , just require it , and init on element mounted is more easier .
SEO just care about data in html DOM .

on my project just one or two page used , so , just require on that page will get small vendor js size .

becareful , if you don't destroy skrollr , it just can init once .

**Comment by kodekrendel** [comment]
@ausir0726 thanks!

**Comment by ausir0726** [comment]
by the way ,
if you have use some vue component don't support SSR , use plugin ssr false will be better .
be cause you need Vue.use(component) .

that will install plugin when app init .

**Comment by ausir0726** [comment]
@kodekrendel  if you have two or three page used skrollr
just add skrollr in build vendor in `nuxt.config.js`
```js
{
  build: {
    vendor: [ 'skrllor' ],
  }
}
```

**Comment by kodekrendel** [comment]
@ausir0726 but doesn't work in plugin, I tried it first. Or I made wrong?

**Comment by kodekrendel** [comment]
> ```{
  build: {
    vendor: [ 'skrllor' ],
  }
}```
What does it change? I still need to import from .vue?

**Comment by ausir0726** [comment]
@kodekrendel  
if you add skrollr in build.vendor 
when you build/generate , skrollr just require in vendor.js once .
will not add in page bundle js.

**Comment by ausir0726** [comment]
If ...  I mean if ....
you really want write in plugin , it looks like ...

plugins/skrollr.js ( ssr: false )
```javascript
import Vue from 'vue';
import Skrollr from 'skrollr';

Vue.Skrollr = Skrollr;
```

in your pages/skrollr-page.vue
```vue
....
mounted () {
  Vue.Skrollr.init();
}
....
```

decide on you

**Comment by kodekrendel** [comment]
@ausir0726 I am not really sure what I want, because I am not fully understand what does all this differences mean :smiley: 

> vue file always need require

I have vue-lazyload, scrollto, scrollspy. None of them are requare in vue. this is all messy stuff.

**Comment by ausir0726** [comment]
because those all inject your Vue instance ( Vue.use( vue-lazyload ) .. Vue.use( scrollspy ) ... )
some package already run with component or directive ....
so you do't need require it .

but skrollr is pure js package ...
if you want simple you should find some vue-skrollr package ...

**Comment by kodekrendel** [comment]
> vue-skrollr

I wish there where one)) There a literally no parallax packages for Vue. There's a few, but they a buggy and lack of features.

**Comment by ausir0726** [comment]
you have a chance write a one !!

and publish it !!  awesome !

**Comment by kodekrendel** [comment]
I am planning, but other library to simple trigger animate.css on scroll.

Notice bug, when I route from other pages Skrollr doesn't work in some cases. Argh..

**Comment by ausir0726** [comment]
Do you have destroy previous skrollr and init when element mounted ?

**Comment by kodekrendel** [comment]
Seems like that bug appears onlu when I am using Skrollr as plugin. 
So I will stick with your first approach, and require in from .vue. 
Thanks again, very informative!
