### ISSUE TITLE
plugins setting is invalid in nuxt.config.js 

### ISSUE THREAD

**Issue by halower** [nuxt/nuxt.js#5704]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://github.com/halower/nuxt-pdf-test](https://github.com/halower/nuxt-pdf-test)

#### first step: 
 i created a vue component(name pdf.vue)  use the `pdfjs-dist`
#### second step: 
 import the plugin
```
import Vue from 'vue'
import Pdf from '~/components/Pdf.vue'

Vue.component('Pdf', Pdf)
``` 
####  third step:

```
  plugins: [
    {
      src: '~/plugins/pdf',
      ssr: false
    }
  ],

```

### What is expected ?

the pdf component run

### What is actually happening?

```
commons.app.js:9792 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

Uncaught ReferenceError: window is not defined
 
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9189">#c9189</a>)</em></sub></div>

**Comment by Austio** [comment]
I pulled this down, i don't think that this is related to nuxt and is related to the setup of the pdf library inside of an SSR environment

**Comment by Austio** [comment]
When you declare something as client only for the plugin, you also have to make sure to not render the component on the server.
 
```
// In index.vue
<template>
  <section class="container">
    <no-ssr>
      <pdf :src='src'/>
    </no-ssr>
  </section>
</template>
```

**Comment by halower** [comment]
thank you very much, when I test tomorrow, I will give you feedback in time

**Comment by halower** [comment]
maybe it's not a nuxt. js problem, but I modified the file as above, but there's still a problem with Uncaught Reference Error: window is not defined

**Comment by halower** [comment]
who can help me ! @ @Austio @cj @VictorTolbert @matjaz

**Comment by rchl** [comment]
It seems like it will work if you add `no-ssr` wrapper + change `import pdfjsLib from "pdfjs-dist/webpack.js";` to `import pdfjsLib from "pdfjs-dist";` in `Pdf.vue`.

That import change will disable web worker support but it should work. To have it working with worker also, you might need to experiment with registering [worker-loader](https://github.com/webpack-contrib/worker-loader) in nuxt which would hopefully fix the problem with webpack transpiling worker code in an unsupported way.

**Comment by halower** [comment]
i had register `worker-loader`,  but there's still a problem with Uncaught Reference Error: window is not defined, also too
```
build: {
    extend(config, { isClient }) {
      if (isClient) {
        config.module.rules.push({
          test: /\.worker\.js$/,
          use: { loader: 'worker-loader' },
          exclude: /(node_modules)/
        })
      }
    }
  }
```
