### ISSUE TITLE
i18n example is not working

### ISSUE THREAD

**Issue by rspt** [nuxt/nuxt.js#571]
Hello,

After downloading your new i18n example and running it locally, I've got the following error trace:

<img width="553" alt="screen shot 2017-04-15 at 14 17 09" src="https://cloud.githubusercontent.com/assets/3854017/25063514/599f0624-21e6-11e7-968d-aec1bff081fb.png">

Do you have a solution? Can't figure it out...

Thanks!

**Comment by Atinux** [comment]
This example uses the next version of Nuxt, I will release the new version this weekend.

**Comment by rspt** [comment]
Yeah!
