### ISSUE TITLE
Eliminate render-blocking resources

### ISSUE THREAD

**Issue by ahmedfaical** [nuxt/nuxt.js#5714]
**Version**
v2.6.3

**Reproduction link**
https://nuxtjs.org

**Steps to reproduce**
Use extractCSS with google-tag-manager plugin

**What is expected ?**
Nuxt works and all external js files placed after all external css

**What is actually happening?**
extracted CSS is generated and placed at the end of head tag which cause lighthouse and Pagespeed warning : Eliminate render-blocking resources (Resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles. [Learn more.](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources?utm_source=lighthouse&utm_medium=extension))

**Comment by alishahlakhani** [comment]
@ahmedfaical Did you manage to resolve this issue?
