### ISSUE TITLE
webpackPreload/webpackPrefetch comments for dynamic import doesn't work

### ISSUE THREAD

**Issue by crutch12** [nuxt/nuxt.js#5718]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://codesandbox.io/s/x3lz9l1wqw](https://codesandbox.io/s/x3lz9l1wqw)

### Steps to reproduce

plugin: importCss
css file: main.css

Build
Start
Find tag link for main.css (smthg like `<link rel="stylesheet" type="text/css" href="/_nuxt/cf8388ab439f136a42a4.css">`)

### What is expected ?

I write `import(/* webpackPreload: true */ "../assets/main.css")` and expect than webpack will add tag with rel="preload" in production for this css file

### What is actually happening?

Webpack adds only one tag without preload

### Additional comments?

Help :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9204">#c9204</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @crutch12 

Actually your issue is that you setup the plugin to be `mode: 'client'`, so Nuxt.js cannot add it to the preload when doing SSR.

I remove the plugin mode and it works perfectly: https://codesandbox.io/s/codesandboxnuxt-vk4rk
