### ISSUE TITLE
Creating nuxt app will not work: Syntax Error: CssSyntaxError: unknown word

### ISSUE THREAD

**Issue by Jones-S** [nuxt/nuxt.js#5727]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://nuxtjs.org/guide/installation](https://nuxtjs.org/guide/installation)

### Steps to reproduce

Use node version 11 (v11.6.0), then follow the getting started guide:

https://nuxtjs.org/guide/installation

`$ npx create-nuxt-app <project-name>`

I did not install anything additional, no linter no nothig. Using yarn as a package manager.

```
npx create-nuxt-app bug-example
> Generating Nuxt.js project in /Users/****/****/bug-example
? Project name bug-example
? Project description Example to show css loader bug
? Use a custom server framework none
? Choose features to install (Press <space> to select, <a> to toggle all, <i> to invert se
lection)
? Use a custom UI framework none
? Use a custom test framework none
? Choose rendering mode Universal
? Author name Jones
? Choose a package manager yarn

```

Unfortunately after installing all node modules and running `$ yarn dev` I get 5 errors like this:

```
 ERROR  in ./pages/index.vue?vue&type=style&index=0&lang=css&                                                                                                                   friendly-errors 16:51:53

Syntax Error: CssSyntaxError: /Users/****/****/css-loader-bug-example/pages/index.vue:1:1: Unknown word          
```

### What is expected ?

To start up my minimal app.

### What is actually happening?

Something must be wrong with a plugin or a dependency.
I upgraded from the originally installed version 2.4.0 to 2.6.3. Error keeps popping up.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9213">#c9213</a>)</em></sub></div>

**Comment by aldarund** [comment]
I cant repro your error following your steps. Provide a generated source code that is not working for you. Also try to clean node cache
