### ISSUE TITLE
Add `forwardLog` option to NuxtConfiguration

### ISSUE THREAD

**Issue by potato4d** [nuxt/nuxt.js#5728]
### What problem does this feature solve?

in [Nuxt v2.7.0](https://github.com/nuxt/nuxt.js/releases/tag/v2.7.0) or later, `nuxt dev` forwards SSR's console.log to the front end.
However, if you have a large number of logs, you do not necessarily want to forward them to the front end.

To that end, it would be nice to be able to turn it off from nuxt.config.js.

### What does the proposed changes look like?

1. Add a flag (Boolan) whether to transfer to NuxtConfiguration
2. Make a change to make it work properly (I would like to send a Pull Request for it)

thanks.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9214">#c9214</a>)</em></sub></div>

**Comment by potato4d** [comment]
The key name may be better, such as `ignoreDevLogs.ssr`.

**Comment by potato4d** [comment]
I think that there is something like this.
https://github.com/potato4d/nuxt.js/commit/6ea30805375e17184d2d7842232b7dab9abb7c33

Also, is it better to be able to change other logs? (I think that another discussion is necessary)

**Comment by clarkdo** [comment]
@potato4d The SSR log has been put into a group by #5770 , so it can be collapsed now, does it meet your requirement ?

**Comment by potato4d** [comment]
@clarkdo 
I will check it within a few days!
thanks

**Comment by clarkdo** [comment]
@potato4d I proposed a pr for more fine-grained configuration for SSR log
