### ISSUE TITLE
Not support custom router in version 0.10 and upper

### ISSUE THREAD

**Issue by heimuya** [nuxt/nuxt.js#573]
When to use breadcrumb(element-ui) in project, it becomes diffcult to set a route name to fit the breadcrumb name directly. Is that any other way to reach this purpose?

**Comment by Atinux** [comment]
Can you create an example about your problem @heimuya?

**Comment by heimuya** [comment]
Thank you for your reply. Example is following:
```javascript
<section class="breadcrumb-container">
         <strong class="title">{{ $route.name }}</strong>
         <el-breadcrumb separator="/" class="breadcrumb-inner">
             <el-breadcrumb-item v-for="(item, index) in $route.matched" :key="index" :to="{ path: item.path }">
                {{ item.name }}
              </el-breadcrumb-item>
         </el-breadcrumb>
</section>
```
I want to set a navigation breadcrumb, and would show $route.name front-end. However, $route.name becomes diffcult to set customly in version 0.10 and upper.  The default value can not change directly.

**Comment by Atinux** [comment]
Since the routes names are generated, you should create a mapping to display the associated name, example:

```js
methods: {
  routeName (name) {
    var routeNames = {
      index: 'Home',
      about: 'About page'
    }
    return routeNames[name]
  }
}
```

```html
<el-breadcrumb-item v-for="(item, index) in $route.matched" :key="index" :to="{ path: item.path }">
  {{ routeName(item.name) }}
</el-breadcrumb-item>
```

**Comment by heimuya** [comment]
@Atinux when a route has children, it would miss the name property, so we can not get its tranlated name through the name property

**Comment by furyscript** [comment]
@Atinux Name is missing on parent route
