### ISSUE TITLE
Cannot access templateVars.options in templates

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt.js#5730]
### Version

[v2.7.0](https://github.com/nuxt.js/releases/tag/v2.7.0)

### Reproduction link

[https://codesandbox.io/s/946pw7j9k4](https://codesandbox.io/s/946pw7j9k4)

### Steps to reproduce

a) create a module that injects a plugin
b) have plugin use lodash syntax to fill in vars from templateVars
c) notice that even though templateVars.options exists, it's { } in the written template

The problems seems to be with https://github.com/nuxt/nuxt.js/blob/dev/packages/builder/src/builder.js#L515 which merges options with the template, even if options isn't passed. 

### What is expected ?

My assumption is that anything you see in templateVars should be accessible in a template!

### What is actually happening?

options prop is being reset

### Additional comments?

a) could maybe see if options is being passed to the template, then let it override it (which still is kind of crummy)
b) could move either options or templateVars.options into a new prop in templateVars so it's always accessible.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9215">#c9215</a>)</em></sub></div>

**Comment by Atinux** [comment]
Actually, I am wondering why do we have `templateVars.options` initialized with Nuxt options.

An idea @clarkdo?

**Comment by clarkdo** [comment]
@Atinux I'm not sure the initial situation, but I suppose that user may need sth like `options.dev` or other options to do some special process in templates.

@hecktarzuli Thanks for the reporting, I'll propose a fix.

**Comment by hecktarzuli** [comment]
In our case, our system generates 6 websites, and so we have an advanced config system and need config data in our plugins so we can build them using the right settings.  

We are using this for now until this patch is in place.
![image](https://user-images.githubusercontent.com/2112282/58108769-0cc2d100-7bb2-11e9-91c1-2050a92f725f.png)

**Comment by clarkdo** [comment]
@hecktarzuli As @pi0 pointed, merge `options` into template may be a breaking change, so I added `nuxtOptions` as nuxt options in template and keep `options` as template.options, do this make sense for you ?

**Comment by hecktarzuli** [comment]
Sounds good to me.  That's probably the safest course of action.

**Comment by clarkdo** [comment]
@hecktarzuli There are some other libraries are using `tempalte.options` like serializing `template.options`, if we merge options, the serialized object will be huge and contain all nuxt.options.

**Comment by pi0** [comment]
@hecktarzuli Internal modules that really need can leverage it. Indeed we can document it in the future it is a general use case. Not documenting is more because to not encourage using it over explicit templateFile.options.
