### ISSUE TITLE
Autload partial scss files for each component based on location

### ISSUE THREAD

**Issue by VulgarnyKarlson** [nuxt/nuxt.js#5731]
i have component with name "example.vue" in folder "components" so file location will be "client/components/example.vue" i should import like this
<style lang="scss">
@import '../assets/scss/components/example.css';
</style>

Is there possible to autoload scss on each component based on location of component without adding on each component imports ? (layout, page components or just a component which is imported)

ofc its will not crash if file will be not available, as options will be nice if its can be for scoped only or not (maybe if use underscore for scoped type in filename of scss)

like i think that's idea need hook in webpack on component load and add style , but my expirience is very bad in webpack and extending nuxt 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9216">#c9216</a>)</em></sub></div>

**Comment by manniL** [comment]
Not really. you can only add scss to *all* components (see https://github.com/nuxt-community/style-resources-module/ )

**Comment by VulgarnyKarlson** [comment]
> Not really. you can only add scss to _all_ components (see https://github.com/nuxt-community/style-resources-module/ )

yep and forget about chunks in really big project

**Comment by manniL** [comment]
I don't think there is much we can do here though. Either add all variable, mixins etc. you need globally to all components via style-resources-module, or add them one by one :|
It'd probably need a vue-based solution.
