### ISSUE TITLE
Nuxt build returns error: transition is not defined

### ISSUE THREAD

**Issue by gabrielbrrll** [nuxt/nuxt.js#5736]
Whenever I try to build my nuxt app using nuxt build, it throws the error below. Any idea what it means?

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ │
│ ✖ Nuxt Fatal Error │
│ │
│ Error: Could not compile template │
│ C:\Users\wkd\AppData\Roaming\npm\nodemodules\nuxt\nodemodules\@nuxt\vue-app\template\index.js: │
│ transition is not defined │
│ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by cmoeser** [comment]
Had the same issue. Updating from:

"@nuxt/vue-app": "^2.5.1",
to:
"@nuxt/vue-app": "^2.8.1",

Resolved the issue for me.
