### ISSUE TITLE
watchQuery on page re-creates page component

### ISSUE THREAD

**Issue by dhritzkiv** [nuxt/nuxt.js#5738]
### Version

[v2.7.0](https://github.com/nuxt.js/releases/tag/v2.7.0)

### Reproduction link

[https://codesandbox.io/s/pj3jj4884j](https://codesandbox.io/s/pj3jj4884j)

### Steps to reproduce

1. Press the "Bump foo" button
2. Note that this button sets the browser's location bar to the current page with an updated query string

### What is expected ?

Setting/changing the `foo` query string parameter does not recreate the page component. Instead, the page component is re-used

### What is actually happening?

The page component is recreated each time the `foo` query string parameter is changed (as evidenced by the console logging 'created' on each query string parameter changed).

This has performance/usability implications for more complex pages

### Additional comments?

Repro link is for v2.7.x.
Here is a link showing the old, preferred behaviour (v2.6.x): https://codesandbox.io/s/mzl7n86jv9

I believe this to be a breaking change, even if this new behaviour is intended. And if it is intended, what is a work around to achieve the old behaviour (as I'm relying on the page component to be reused)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9223">#c9223</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@dhritzkiv Sorry for the inconvience.

Can you please try to add `key` on page component ?

```js
  key: 'index',
  watchQuery: ["foo"],
```

**Comment by dhritzkiv** [comment]
@clarkdo Either of those `key` options result in a page that only changes once (going from "/" to "/?foo=2"; but "/?foo=2" to "/?foo=3" does not trigger the nuxt page render cycle) and the component is still re-created.

Further, using `key: ({fullPath}) => fullPath,` /does/ trigger the nuxt page render cycle, but the page component is still re-created (by the router-view?) each time.

I can't think of a way to achieve the old behaviour.

**Comment by clarkdo** [comment]
@dhritzkiv It should be the same behaviour as before with functional `key: ({ path }) => path`, because component will have exact same key `this.$route.path` as before and skip the changes introduced by above pr.

**Comment by clarkdo** [comment]
I added the change based on your codesandbox, you can see that `Foo` keep increasing and only 1 `created` log.

![1](https://user-images.githubusercontent.com/4312154/57785584-f2a86f00-7729-11e9-897e-861227523cb8.gif)

**Comment by dhritzkiv** [comment]
Huh! So, for some reason this change works in Firefox, but doesn't work in Safari! (Safari is where I created/updated the codesandbox). In Safari, the updated query string doesn't trigger changes.

(Note: the underlying problem in this issue doesn't work in Firefox, either. And the old behaviour from 2.6.3 worked in Safari just fine)
