### ISSUE TITLE
chunks filename hash

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#574]
Hello. We have recently encounter a serious problem in production. When new app release is published users will loose layout after hydration.

![cache](https://cloud.githubusercontent.com/assets/5158436/25087664/d0662026-2385-11e7-9b55-5a5e5c28da78.gif)

Here is headers response from server. (Application is being directly rendered by nuxt and is under a simply nginx reverse proxy backend without any caching)

```bash
$ curl -I  https://support.aut.ac.ir/assets/7.app.js

HTTP/2 200
server: nginx
date: Mon, 17 Apr 2017 11:22:17 GMT
content-type: application/javascript
content-length: 2990
vary: Accept-Encoding
accept-ranges: bytes
last-modified: Mon, 17 Apr 2017 10:49:05 GMT
etag: W/"bae-15b7b87bce8"
vary: Accept-Encoding
strict-transport-security: max-age=31536000
```

# Remarks
In Firefox only this will happen only once and after a refresh it works normally again

**Comment by Atinux** [comment]
Do you have an error in the console or something which will help us to debug this behavior @pi0 ?

**Comment by pi0** [comment]
@Atinux Actually i had done my best to debug anything before reporting issue :)) Console log is empty. It seems client-side rendered content is different (because it is being rendered with older pre fetched chunks) and Vue tries to fix that by entirely removing layout parts.
And as another update, i made cache header hidden from clients with this nginx config: 
```
proxy_hide_header cache-control;
```
It disables cache for chunks and as a result clients with cleared cache won't encounter this issue anymore on releases. (We still have higher PWA score because of *etags*)

**Comment by pi0** [comment]
Here is what was actually happens:

- Release A:
  Response with SSR(A)
  Manifest loads needed chunks
  (In Parallel) other chunks are loaded and cached for 1 year
  Client Rendered (A)

- Release B
   Response with SSR(B)
   Manifest requests for chunks but they are not invalidated (1.app.js,...)
   Client rendered (A) <--- Here is the conflict
   Only on firefox caches are invalidated for next request 

We may add hash to chunk names too to avoid this conflict and allow real long-term caching possible.

**Comment by pi0** [comment]
Also this [official docs](https://webpack.js.org/guides/caching/#deterministic-hashes) about deterministic hashes.

> To generate identifiers that are preserved over builds, webpack supplies the NamedModulesPlugin (recommended for development) and HashedModuleIdsPlugin (recommended for production).

@Atinux what's your idea about using this plugin for production?

**Comment by pi0** [comment]
It seems problem is with using `nuxt.build.filenames` when using custom names like below chunks are not being hashed anymore:
```js
        filenames : {
                css: 'app.css',
                vendor: 'vendor.js',
                app: 'app.js'
            };
        }
```

Build output:

![image](https://cloud.githubusercontent.com/assets/5158436/25284949/d62fc746-26cd-11e7-99c0-6bae61905095.png)

Without that option chunks are hashed and cache problem won't happen.

**Comment by gangsthub** [comment]
Happening in nuxt@1.4.1 to me with consecutive builds (on CI).
