### ISSUE TITLE
JWT authentication with Nuxt.js

### ISSUE THREAD

**Issue by pkucmus** [nuxt/nuxt.js#575]
Hi.

I'm new to all this JavaScript and above stuff - having troubles making a simple JWT based authentication. After a successful login I receive a JWT from my backend (Django REST framework) and I am authenticated across my Nuxt app until I refresh the page. So I thought - just store the JWT in local storage. But I have no access to `localStorage` in `state/index.js` I guess because of the server-side rendering. 

How can I persist my JWT in the browser?

**Comment by Atinux** [comment]
Hi @pkucmus 

Please take a deep look at https://github.com/nuxt/example-auth0, we store the token in the cookie to be able to fetch it on the server-side.

**Comment by mindbits** [comment]
Unfortunately this example does not work properly. 

If you go to https://nuxt-auth0.surge.sh and sign in, there is a redirect to the main page showing "You are authenticated" and the secret div is displayed.

But then reloading this page results in the unexpected "You're not authenticated yet"?

The only way to make the example work is to manually go to https://nuxt-auth0.surge.sh/secret and start the navigation from there.

**Comment by fwertz** [comment]
@Atinux Is there any plan to support store saturation other than from a session? Forcing session for state persistence really throws a rift in creating static SPAs. Using `nuxt generate` is no longer an option when trying to store something as simple as a single JWT.  Other implications:

- Additional dependencies (express, body parse, express-session, etc)
- Server (previously optional, now _needed_)
- Local APIs needed to CRUD a persisted state requires either multiple axios instances OR adding something like `express-http-proxy` to umbrella local/external API service calls under one clean configuration.

**Comment by kodekrendel** [comment]
@Atinux yeah, but than auth0 example doesn't work after I refresh the page - https://github.com/nuxt/example-auth0/issues/8

**Comment by lobosan** [comment]
Hi @Atinux I had a deep look at https://github.com/nuxt/example-auth0 and the problem I have is that I'm migrating a SPA that checks JWTs, so since I have no access to cookies in the middleware check-auth then I get the error "localStorage is not defined". Is there any way to always have access to localStorage?

**Comment by Atinux** [comment]
@lobosan `localStorage` is only accessible from client-side so it's not possible to always access it.

@fwertz if you don't want any server, you can always use the `mode: 'spa'` option in nuxt.js, but you won't have server-side rendering. About `nuxt generate`, it's not possible since if you store a `JWT`, your page content will probably differ depending of who is requesting your website, so you will need a server if you need server-side rendering.

**Comment by lobosan** [comment]
@Atinux is it possible to access localStorage in the first render?

**Comment by Atinux** [comment]
@lobosan with SSR, the first render if on the server so no it's impossible :(

**Comment by lobosan** [comment]
@Atinux I see, so it means I can only use cookies for authentication? and if I use the flag httpOnly: true to prevent the cookie being accessed from the client and therefore avoid XSS attacks, can I handle the cookie for authentication all in the server?

I guess I just want to make sure that I'm using a secure and production ready authentication and authorization implementation of nuxt ssr

**Comment by Atinux** [comment]
@lobosan Of course you can set `httpOnly`, this is what I use for my projects, you can then set the user session in `nuxtServerInit` action.

You need to add a server middleware to store the cookie also when the user sign-in.

**Comment by Atinux** [comment]
Hi @mytc 

You can take a look at https://github.com/Atinux/nuxt-heroes/blob/master/server-middleware/github-callback.js#L16

The application uses cookies with httpOnly :)

**Comment by mytc** [comment]
@Atinux ,thanks!! This is exactly what I needed.
