### ISSUE TITLE
nuxt-link prefetch throws an exception when it becomes visible

### ISSUE THREAD

**Issue by makweb** [nuxt/nuxt.js#5751]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://codesandbox.io/s/codesandboxnuxt-tnli2?fontsize=14](https://codesandbox.io/s/codesandboxnuxt-tnli2?fontsize=14)

### Steps to reproduce

nuxt.config.js add to build section `splitChunks:{layouts: false, pages: false}`,
scroll down until it becomes visible

### What is expected ?

prefetch route link

### What is actually happening?

exception in console Uncaught `TypeError: Component(...).catch is not a function at VueComponent.prefetch`

### Additional comments?

Help :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9228">#c9228</a>)</em></sub></div>

**Comment by rchl** [comment]
So in that case components can't be preloaded because they are not lazy loaded (are already preloaded). I'll create a fix for catching the error.

**Comment by edum18** [comment]
I ran yarn install, it updated some packages and now I'm having the same error as I load the page

**Comment by rchl** [comment]
@edum18 it's fixed in nuxt 2.7.2

**Comment by siegy22** [comment]
I'm using nuxt 2.10.1 and still run into this issue.

**Comment by manniL** [comment]
@siegy22 please create a new issue with a reproduction repo and a reference to this one

**Comment by siegy22** [comment]
@manniL I'm trying to isolate it, but it's pretty hard as it's not consistent throwing that Error. 🤔
