### ISSUE TITLE
API Requirement of Statically Generated Dynamic Applications

### ISSUE THREAD

**Issue by giray123** [nuxt/nuxt.js#5756]
### What problem does this feature solve?

Users would test their dynamic nuxt applications without the need of a public API of their data.

### What does the proposed changes look like?

When "nuxt generate" command is used with any page component with asyncData that fetches data for page content, although replicates the original application, created static application still needs an API for client side page renderings. I am using generate command from time to time to upload my app to any static host (surge in my case) to show it to my friends. It would be really nice to disable client side routing on nuxt config file in order to have all links on the pages completely server rendered. For now, I need to click "open in new tab" for all pages.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9229">#c9229</a>)</em></sub></div>

**Comment by manniL** [comment]
See https://github.com/nuxt/rfcs/issues/22
