### ISSUE TITLE
Cannot access "this" in `key()` after #5516

### ISSUE THREAD

**Issue by njam** [nuxt/nuxt.js#5759]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

Example showing problem with Nuxt 2.7.1:
[https://codesandbox.io/embed/nuxtkeythis-l5ucy](https://codesandbox.io/embed/nuxtkeythis-l5ucy)

Example showing how it worked with Nuxt 2.6.3:
https://codesandbox.io/embed/nuxtkeythis263-xf4n1

### Steps to reproduce

1. Return some data in a page's `asyncData()`
2. Access that data in the page's `key()` using `this.data()`

### What is expected ?

Page data can be accessed in `key()` using `this.data()`.

### What is actually happening?

Error because `this` is not defined:
>  Cannot read property 'data' of undefined 

### Additional comments?

This is a regression introduced in Nuxt 2.7.0 with https://github.com/nuxt/nuxt.js/pull/5516/files
Previously the function was called as `Component.options.key()`, now just `key()`.

Why is it useful to have access to `this` and "asyncData" in `key()`?
Because it allows to dynamically decide whether a page instance can handle the current route based on _other data_ (e.g. data from the store, that is made available in `asyncData()`). See https://github.com/nuxt/nuxt.js/issues/4663 and related tickets.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9231">#c9231</a>)</em></sub></div>

**Comment by njam** [comment]
ping @utatti

**Comment by utatti** [comment]
This change is actually made by https://github.com/nuxt/nuxt.js/pull/5516#discussion_r281602468 by @clarkdo (https://github.com/nuxt/nuxt.js/pull/5516/commits/70ea46c9dd1463f6715555762fb9e6677595e691).

Actually, I guess that `key` is not designed to work with `this`. You said that calling  `Component.options.key()` enables dynamic decision on components, but it doesn't work like that. When we call `Component.options.key()`, `this` inside the function just refers `Component.options`, not the component instance (thus not dynamic). So `this.data` inside `key()` just refers to the static `data` function, not the dynamic property of each component instance.

After all, `key()` should be called on each route before a component instance is initialized, so I think it's natural not using `this` inside it (just like `asyncData()` or `fetch()`).

By the way, I'm not one of the core members so maintainers may help answering.

**Comment by njam** [comment]
Thanks for the info!

I agree it's probably not designed to work with `this`. Probably more by chance it worked in 2.6.3?
Here's a Codesandbox with accessing `this.data()` in `key()`, on the client side with Nuxt 2.6.3:
https://codesandbox.io/embed/nuxtkeythis263-xf4n1

Let's see what the maintainers say. Maybe I should open a feature request instead?

**Comment by clarkdo** [comment]
You're right, it's a potential breaking change in 2.7, I think it can be fixed in https://github.com/nuxt/nuxt.js/pull/5757

**Comment by utatti** [comment]
Sure, I've added a commit in #5757 (ignore the first 2 commits above).
