### ISSUE TITLE
Best impelentation localStorage

### ISSUE THREAD

**Issue by martinrisseeuw** [nuxt/nuxt.js#576]
I have a survey with 5 different questions, the state of the questions is stored in a vuex store. These questions are used on different pages in the application. When I refresh the page the state is lost and gives an error.

I have been looking at vuex-persistedstate, but it doesn't work together with nuxt as described in the issue below:
https://github.com/robinvdvleuten/vuex-persistedstate/issues/16

My idea is to implement a local storage but unfortunately I did not succeed so far. I found this issue talking about local storage: https://github.com/nuxt/nuxt.js/issues/185 and it says we shouldn't use it. 

Are there any suggestions of keeping the vuex state on refresh without creating a session on server (no login).

**Comment by Atinux** [comment]
Hi @martinrisseeuw 

You don't have the choice since the server don't have access to `localStorage`.

Please see [todomvc example](https://github.com/nuxt/example-todomvc).
There is nothing wrong about creating a session on the server, PHP does that without having to login.

**Comment by PrimozRome** [comment]
@Atinux where do you store then the auth token so if the browser is refreshed  that user is not redirected back to the login page, if the token is still valid? Trying to solve this issue within my app.

**Comment by lyquocnam** [comment]
@PrimozRome i tried use `express-session` to store user and use `nuxtServerInit` to get from `session`.

in server when login:
```javascript
router.post('/login', async (req, res) => {
  const { usernameOrEmail, password, remember  } = req.body;

  if (!usernameOrEmail)
    return res.status(401).json({ message: 'Thông tin đăng nhập không hợp lệ !' });

	const user = await User.find({
		where: {
			$or: [
				{ username: usernameOrEmail  },
				{ email: usernameOrEmail  },
			]
		}
	});

	if (!user)
		return res.status(401).json({ message: 'Không tìm thấy thông tin đăng nhập này trong hệ thống !' });

	if (user.password !== password)
		return res.status(401).json({ message: 'Thông tin đăng nhập không hợp lệ !' });

	if (remember)
		req.session.maxAge = 30*24*60*60*1000; // 30 ngay

	req.session.info.user = user;

	return res.json(user);
});
```

```javascript
export const nuxtServerInit = ({ commit }, { req }) => {

    const info = req.session.info;

    commit('setInfo', {
        siteName: info.siteName,
        siteDescription: info.siteDescription,
    });

    commit('account/setUser', info.user);
};```

my project https://github.com/lyquocnam/nuxt-express
