### ISSUE TITLE
How to using axios.baseUrl in asyncData function

### ISSUE THREAD

**Issue by ndphuong** [nuxt/nuxt.js#5762]
### What problem does this feature solve?

Hi,

I want to call backend api by using relative path by axios.get(relativePath) function
But since we cannot access this.$axios... from asyncData function, so axios.baseURL config cannot working here , right ?

How to do that ?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9237">#c9237</a>)</em></sub></div>

**Comment by rchl** [comment]
You can. asyncData is passed context and axios can be gotten from context.$axios

**Comment by Atinux** [comment]
Documentation: https://axios.nuxtjs.org/usage#component
