### ISSUE TITLE
Probably example from the docs is not working

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [nuxt/nuxt.js#577]
Hello,
Please take a look at the [example from the docs](https://nuxtjs.org/api/configuration-cache/)
It doesn't look to me that it caches. The value is updated right away.

I never used vue caching so I'm not sure whether it's me missing smth, or it is not working.
I tried both production and development modes

**Comment by Atinux** [comment]
You have to look at the source code directly @OlzhasAlexandrov 

I will update the `cache` option since it brings a lot of confusion and will instead cache the page and avoid re-rendering the page on the SSR, it's planned for a future release.

**Comment by ausir0726** [comment]
@Atinux 

Seems like that you talking about will resolve my confusion #550 .
right ?
