### ISSUE TITLE
"collapseWhitespace: true"不生效

### ISSUE THREAD

**Issue by xakxak007** [nuxt/nuxt.js#5772]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Steps to reproduce
```

build: {
        html: {
            minify: {
                collapseWhitespace: true
            }
        },
    },
```

### What is expected ?

template
`
<span>a</span>
<span>bc</span>
`

预期：
 `
<span>a</span>
<span>bc</span>
`

实际：
` <span>a</span> <span>bc</span>`

### What is actually happening?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9243">#c9243</a>)</em></sub></div>

**Comment by manniL** [comment]
you might want to use vue compiler options for that ( in `build` in your nuxt.config.js)

```js
      loaders: {
        vue: {
          compilerOptions: {
            whitespace: 'condense'
          }
        }
      },
```

**Comment by xakxak007** [comment]
> 你可能想要使用vue编译器选项（`build`在你的nuxt.config.js中）
> 
> ```js
>       装载机： {
>         vue ： {
>           compilerOptions ： {
>             空白： '凝聚'
>           }
>         }
>       }，
> ```

谢谢 完美运行~！
