### ISSUE TITLE
Color name in my SCSS is converted to hex in production

### ISSUE THREAD

**Issue by LeoSeyers** [nuxt/nuxt.js#5778]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://github.com/LeoSeyers/leoseyers.com](https://github.com/LeoSeyers/leoseyers.com)

### Steps to reproduce

I use a global SCSS files in my assets folder with the following lines : 

.f-serif {
  font-family: "Crimson Text", sans-serif;
}

The issue happens in production (npm run generate), color name is converted in hex while quotes are used.

The previous line is converted into 
.f-serif {
    font-family: #dc143c Text,sans-serif;
}

### What is expected ?

Color name should stay as strings when into quotes.

### What is actually happening?

Color name, while being into quotes here ("Crimson Text") is actually converted (#dc143c Text)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9246">#c9246</a>)</em></sub></div>

**Comment by pimlie** [comment]
Cant reproduce this in a clean Nuxt project

**Comment by LeoSeyers** [comment]
> Cant reproduce this in a clean Nuxt project

interesting, it's pretty much a clean nuxt project
thanks for having a look

i've tried insering the 'f-serif' class into layout component instead of global scss but it's still got wrongly converted in production version

i'm running out of ideas, so far i've mitigated the issue with inline css (style="font-family:'Crimson Text';) that doesn't get converted, but that still bugs me out

**Comment by pimlie** [comment]
Make sure to fully upgrade all dependencies (thus remove lock file, remove node_modules, update deps with npm-check-updates, run install)
