### ISSUE TITLE
SyntaxError: /.nuxt/nuxt-icons.js: Unexpected token, expected "," (93:1387)

### ISSUE THREAD

**Issue by siberiadev** [nuxt/nuxt.js#5783]
### Version

[2.7.2](https://github.com/nuxt.js/releases/tag/2.7.2)

### Reproduction link

[http://link.re](http://link.re)

### Steps to reproduce

npm run build

### What is expected ?

Normal building

### What is actually happening?

ERROR in ./.nuxt/nuxt-icons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /.nuxt/nuxt-icons.js: Unexpected token, expected "," (93:1387)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9249">#c9249</a>)</em></sub></div>

**Comment by siberiadev** [comment]
I fixed that by change nuxt version in package.json
"nuxt-edge": "latest"
change to 
"nuxt": "^2.7.0"

Why it helps me?
Maybe nuxt core team change nuxt-edge to nuxt repo? What exactly should I use? nuxt or nuxt-edge?
nuxt 2.7.0 === nuxt-edge?

**Comment by pi0** [comment]
Hi. This is a known Issue with latest nuxt edge. (This may happen time to time) will resolve soon.

**Comment by siberiadev** [comment]
Ok, thank you. Are there any differences between nuxt-edge and nuxt? Or
nuxt-edge is just a middle (dev) version of nuxt?

чт, 23 мая 2019 г. в 14:33, Pooya Parsa <notifications@github.com>:
