### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by johnsonjobin** [nuxt/nuxt.js#5786]
I did a fresh install of Nuxt using npx create-nuxt-app <project-name>. 
Added the following libraries - 
Vuetify, Prettier, EsLint, Axios, Jest.
Created a universal app. When i run npm run dev, i get the following error.
I have installed typescript globally.

```ERROR Failed to compile with 1 errors friendly-errors 13:21:37

ERROR in ./plugins/vuetify.js friendly-errors 13:21:37

Module build failed (from ./nodemodules/eslint-loader/index.js): 
friendly-errors 13:21:37 Error: Cannot find module 'typescript' Referenced from: /Users/j787209/Documents/Project/buyingGroup/.eslintrc.js 
  at Function.Module.resolveFilename (internal/modules/cjs/loader.js:580:15)
  at Function.Module.load (internal/modules/cjs/loader.js:506:25)
  at Module.require (internal/modules/cjs/loader.js:636:17)
  at require (internal/modules/cjs/helpers.js:20:18) 
  at Object.<anonymous> /Users/j787209/Documents/Project/buyingGroup/nodemodules/@typescript- 
 eslint/typescript-estree/dist/parser.js:17:25)
  at Module.compile (internal/modules/cjs/loader.js:688:30) 
  at Object.Module.extensions..js (internal/modules/cjs/loader.js:699:10)
  at Module.load (internal/modules/cjs/loader.js:598:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
  at Function.Module.load (internal/modules/cjs/loader.js:529:3) 
  at Module.require (internal/modules/cjs/loader.js:636:17) 
  at require (internal/modules/cjs/helpers.js:20:18) 
  at Object.<anonymous> (/Users/j787209/Documents/Project/buyingGroup/nodemodules/@typescript-eslint/experimental-utils/dist/index.js:18:27)
  at Module.compile (internal/modules/cjs/loader.js:688:30) 
  at Object.Module.extensions..js (internal/modules/cjs/loader.js:699:10)
  at Module.load (internal/modules/cjs/loader.js:598:32)
friendly-errors 13:21:37
@ ./.nuxt/index.js 19:0-72 168:25-53 174:19-47
@ ./.nuxt/client.js
@ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/_webpackhmr/client ./.nuxt/client.js
```

**Comment by lucraraujo** [comment]
I faced the same problem here, and this is the culprit.
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v22.6.2
Since github is currently having a problem with webhooks, we'll have to wait a little bit for the fix.

**Comment by xetra11** [comment]
any update on that?

**Comment by epiphanatic** [comment]
Install typescript as a dependency in the project. I have had several issues with this in different scenarios (eg build pipelines) and it's worked for me.

**Comment by dsm-72** [comment]
@epiphanatic  I tried that and then I got:

```
╭──────────────────────────────────────────────────────────────────────────────╮│                                                                              ││   ✖ Nuxt Fatal Error                                                         ││                                                                              ││   Error: Cannot find module 'typescript'                                     ││   Require stack:                                                             ││   -                                                                          ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/typescri   ││   pt-reporter/TypeScriptReporterConfiguration.js                             ││   -                                                                          ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCh   ││   eckerWebpackPluginConfiguration.js                                         ││   -                                                                          ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCh   ││   eckerWebpackPlugin.js                                                      ││   -                                                                          ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/index.js   ││   - /opt/build/repo/node_modules/@nuxt/typescript-build/dist/index.js        ││   - /opt/build/repo/node_modules/@nuxt/core/dist/core.js                     ││                                                                              │╰──────────────────────────────────────────────────────────────────────────────╯
```
any ideas?

**Comment by yiiman-dev** [comment]
> @epiphanatic I tried that and then I got:
> 
> ```
> ╭──────────────────────────────────────────────────────────────────────────────╮│
>                                                                               
> ││   ✖ Nuxt Fatal Error                                                         ││                                                                              
> ││   Error: Cannot find module 'typescript'                                     
> ││   Require stack:                                                             ││   -                                                                          
> ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/typescri   
> ││   pt-reporter/TypeScriptReporterConfiguration.js                             ││   -                                                                          ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCh   
> ││   eckerWebpackPluginConfiguration.js                                         ││   -                                                                          
> ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCh   
> ││   eckerWebpackPlugin.js                                                      ││   -                                                                          
> ││   /opt/build/repo/node_modules/fork-ts-checker-webpack-plugin/lib/index.js   
> ││   - /opt/build/repo/node_modules/@nuxt/typescript-build/dist/index.js        
> ││   - /opt/build/repo/node_modules/@nuxt/core/dist/core.js                     ││                                                                              │╰──────────────────────────────────────────────────────────────────────────────╯
> ```
> 
> any ideas?

Do you solved this problem 
I have this problem on docker alpine

**Comment by denkravchu** [comment]
The same issue with vercel-builder:(

**Comment by matheuslemke** [comment]
Installing typescript as a dev dependency of the project worked for me.

**Comment by hecong-cac** [comment]
`npm install --save-dev typescript`
worked for me.
