### ISSUE TITLE
Store commit function doesn't execute in directly navigate to the app

### ISSUE THREAD

**Issue by msudgh** [nuxt/nuxt.js#579]
I have a page that in fetch method I POST to API and in response, i got response's data and commit to the vuex store but it doesn't work.

![screenshot_20170417_185900](https://cloud.githubusercontent.com/assets/11756815/25091747/efe474ba-239f-11e7-82f3-55286fcf6f67.png)

**Comment by ausir0726** [comment]
that because if page directly visit , you will get data from SSR  , it will not fetch data again in client side .
your fetch function not wait your request done , and just rendered html and throw to browser .

**Comment by msudgh** [comment]
What's the solution to produce something that i want?

**Comment by ausir0726** [comment]
return your Promise or use async/await 
https://nuxtjs.org/api/pages-fetch/#the-fetch-method

**Comment by msudgh** [comment]
@ausir0726 thanks

**Comment by msudgh** [comment]
I can store the data in vuex but still, I got 404 error.
![screenshot_20170418_100256](https://cloud.githubusercontent.com/assets/11756815/25115876/5865e248-241e-11e7-91a6-d5af8808c37f.png)

**Comment by Atinux** [comment]
Try to replace `axios.all` by `Promise.all` and see if it works @msudgh

**Comment by msudgh** [comment]
No, it doesn't work. Why it should work in file **`/pages/album/index.vue`** and doesn't work in **`/pages/album/_uid.vue`** ?

**Comment by msudgh** [comment]
Apology, the problem was from a middleware that I have to create a new instance instead of using it as middleware
