### ISSUE TITLE
Modify default index.html (dist folder)

### ISSUE THREAD

**Issue by srunicornio** [nuxt/nuxt.js#5798]
### What problem does this feature solve?

I have async middleware. In the first load I wait to load crucial data for the app. 
While is loading data it shows Nuxt default index.html page (white background with spinner). 
It should be customizable. After all I want to decide what show to client while it waiting.

### What does the proposed changes look like?

In nuxt.config.js add:

defaultHtml: 'pathToCustomHtml/index.html'

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9260">#c9260</a>)</em></sub></div>

**Comment by pi0** [comment]
It is possible indeed: https://nuxtjs.org/api/configuration-loading-indicator/

You can also pass to your own `loading.html`. See: https://stackoverflow.com/questions/53194999/how-can-i-create-a-custom-loading-indicator-in-nuxt-js

**Comment by srunicornio** [comment]
@pi0 your right. Sorry I didn't understand properly this property when searching docs. I thought it was related to loading property.

Sorry and thanks!
