### ISSUE TITLE
Not update vuex store values on server

### ISSUE THREAD

**Issue by PetrChalov** [nuxt/nuxt.js#5799]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://codesandbox.io/s/codesandboxnuxt-8qq7o](https://codesandbox.io/s/codesandboxnuxt-8qq7o)

### Steps to reproduce

Changing store not in parent component  - pages/index.vue.
On the server, the values in the component components/SomeComponent.vue are not updated.

### What is expected ?

Updating values in SomeComponent.vue when rendering on the server

### What is actually happening?

Values not updated. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9261">#c9261</a>)</em></sub></div>

**Comment by thearchitect** [comment]
I am experiencing the same problem!

**Comment by rchl** [comment]
I believe this is due to [reactivity not being enabled on the server](https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server).

**Comment by PetrChalov** [comment]
Is it possible to turn it on?

If use `fetch` method, then everything works. But I would like to leave it at `created`

**Comment by PetrChalov** [comment]
> I believe this is due to [reactivity not being enabled on the server](https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server).

Is it possible to turn it on?

If use fetch method, then everything works. But I would like to leave it at created

**Comment by manniL** [comment]
No, it is not AFAIK
