### ISSUE TITLE
Register new route

### ISSUE THREAD

**Issue by Heydon** [nuxt/nuxt.js#58]
I created a page file and linked to it using the `<router-link>` element, but it 404s. 

I see in the `.nuxt` folder there are some routes defined e.g. 

```
const _3cb81d92 = process.BROWSER_BUILD ? () => System.import('/Users/heydonpickering/repositories/project-folder/pages/about.vue') : require('/Users/heydonpickering/repositories/project-folder/pages/about.vue')
```

These are clearly added dynamically on webpack build, but I don't know where to add a new one?

Many thanks.

**Comment by Atinux** [comment]
Hi @Heydon 

If you have theses pages:
```bash
-| pages
---| index.vue
---| about.vue
```

You can link the about page in `index.vue` with `<router-link to="/about">About page</router-link>`

Example: https://gomix.com/#!/project/nuxt-hello-world
Live demo: https://nuxt-hello-world.gomix.me/

**Comment by Heydon** [comment]
Thanks
