### ISSUE TITLE
active class in router doesn't change to custom class

### ISSUE THREAD

**Issue by d0whc3r** [nuxt/nuxt.js#580]
I have tried to change inline `nuxt-link` attribute `active-class`, and also `router.linkActiveClass` propertie in nuxt.config.js but neither works.
It injects `nuxt-link-active` instead of my own defined `active` class (bootstrap active class)

Any one with this same issue?

Example here: https://glitch.com/edit/#!/handy-ostrich

PD: At the first try in "glitch.com" (with nuxt 0.10.3) it worked, but when I updated to 0.10.5 broke, and now, neither with 0.10.3 doesn't works

PD2: I edited the example in glitch.com and now router.linkActiveClass is working but active-class is not working

**Comment by Atinux** [comment]
The `active-class` is a known bug of the last release of vue-router: https://github.com/vuejs/vue-router/pull/1324
