### ISSUE TITLE
Upgrade Tailwind to version 1

### ISSUE THREAD

**Issue by paulwanjohi** [nuxt/nuxt.js#5803]
### What problem does this feature solve?

some of the default configurations is not in sync with tailwind documentation

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9264">#c9264</a>)</em></sub></div>

**Comment by manniL** [comment]
https://github.com/nuxt/create-nuxt-app/pull/237
