### ISSUE TITLE
ScrollTop issue in Safari browser only

### ISSUE THREAD

**Issue by willdante** [nuxt/nuxt.js#5805]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://github.com/willdante/testscroll](https://github.com/willdante/testscroll)

### Steps to reproduce

- Install a new Nuxt app with yarn create nuxt-app (no option)
- Add some content in index.vue to be able to scroll
- Generate a static site with yarn run generate and host it
- Open the index page in Safari browser (I've tried in Mac and iPad)
- Scroll down the page then reload it

### What is expected ?

The scroll position should be kept after reloading the page.

### What is actually happening?

The scroll position is back to the top of the page after reloading it.

### Additional comments?

My tests were made in Safari 12 for Mac and in the latest Safari version for iPad.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9266">#c9266</a>)</em></sub></div>

**Comment by RafaelGSS** [comment]
Scroll down be kept in a static website? 

I don't know it was really expected in a static website... I'll wait for the core team

**Comment by willdante** [comment]
Well, it's the default behavior of any classic website and as it works well in the other major browsers (Chrome, Firefox), I suppose it's a Safari related bug.

Usually, when there is an issue in a website (image not loading or some script not working as expected for example), users may reload the page to solve it.
If I'm in the middle of a page and reload it in order to make an image appear, I want to stay where I was and not to be back at the top ;)

If it can help, the present Nuxt website doesn't have this scroll position issue in Safari.
Maybe older versions of Nuxt don't have the bug.

I've seen many posts with this kind of issue when using some css overflow: hidden in html or body.
This jsfiddle is perfect to make some tests in Safari: 

https://jsfiddle.net/michieldewit/vLbx882u/4/

But in this Nuxt issue, this is not the problem because we don't use overflow: hidden.

**Comment by RafaelGSS** [comment]
Oh, well... Maybe can be `back-forward-cache` in the browser... I'll make some tests here

**Comment by willdante** [comment]
I've just tested one more thing.

If I scroll to the middle of the page, then go to another page and come back to the previous page with the browser back button, the scroll position is saved and I'm back in the middle of the page.

So it's only when reloading a page that there is an issue.

**Comment by RafaelGSS** [comment]
When your reload page cleaning cache (CTRL+SHIFT+R in chrome), the same problems occur? ( In browsers that don't has problem )

**Comment by willdante** [comment]
No problem with hard reload in Chrome and Firefox, the scroll position is saved as expected.
