### ISSUE TITLE
Incorrect script tag reading

### ISSUE THREAD

**Issue by dnc123** [nuxt/nuxt.js#5806]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://jsfiddle.net/n6sxhjt8/1/](https://jsfiddle.net/n6sxhjt8/1/)

### Steps to reproduce

Create a component (in my case I'm using page component) with an empty space in script tag.

<script>
//Error (notice the no space at the start of this line)
</script>

<script>
    //all good
</script>

### What is expected ?

No error

### What is actually happening?

An error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9267">#c9267</a>)</em></sub></div>

**Comment by RafaelGSS** [comment]
Hello. Your example is not using NuxtJs.

**Comment by manniL** [comment]
Hey :wave: 	

If you don't need a `script` tag, then please omit it at all. :relaxed:

**Comment by ricardogobbosouza** [comment]
@manniL 
Think we can close this?
