### ISSUE TITLE
Ability to change 404 page text if validate function returns false 

### ISSUE THREAD

**Issue by karudo** [nuxt/nuxt.js#581]
If function `velidate` returns `false`, default text `'This page could not be found.'` will be rendered.
We need ability to change it, e.g. parametr in nuxt.config

**Comment by vuchl** [comment]
Make a pull request where you change this line [here](https://github.com/nuxt/nuxt.js/blob/b5330a063d0106c5022be834249f6089403741d2/lib/app/server.js#L192) from the `nuxt.config.js` which falls back to the value that is now in there.

**Comment by aymenpeak** [comment]
@karudo  yes you can by creating your own layouts/error.vue then replace {{ error.message }} by your own message depending of {{ error.statusCode}}
