### ISSUE TITLE
Navigate to child page on view

### ISSUE THREAD

**Issue by MartinMuzatko** [nuxt/nuxt.js#5819]
### What problem does this feature solve?

When you have nested pages using `<nuxt-child>`, then you likely have no content for the parent page, if you e.g. categorize your pages into sub-pages.

An example looks like this: 
![nuxtchild.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/ffa82ac0-8079-11e9-8019-0704f5d87525.PNG)

My approach was to check for the route transition in the `created` call. But this does not work.

```
created() {
    if (this.$route.name != 'asssets') return
    this.$router.push('/assets/devices')
}
```

Now the problem is, this works perfectly fine when first visiting the page. but when I am already on the page and click on a nuxt-link that goes to /assets/ then this does not work, since the component/page is already `created`.

### What does the proposed changes look like?

Add a lifecycle hook for page transitions.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9273">#c9273</a>)</em></sub></div>

**Comment by pimlie** [comment]
Cant you use a vue-router navigation guard to do this? Eg add this to your `/assets` page component:

```js
beforeRouteEnter(to, from, next) {
  next('/assets/devices')
}
```

**Comment by MartinMuzatko** [comment]
Didn't know this exists!  Will try this on monday but looks good :)

**Comment by MartinMuzatko** [comment]
I gave it a quick try and it seems to redirect forever. Is it possible that  this does not cleanly work together with nuxt child?

**Comment by MartinMuzatko** [comment]
So I have further investigated and this is the correct way to do it:
```js
beforeRouteEnter(to, from, next) {
    if (to.name == 'assets') return next('/assets/devices')
    next()
}
```

However, nuxt-child seems to have a problem with this, as the matched route is then not available for the context of the nuxt-child components.

![image](https://user-images.githubusercontent.com/2950505/58781357-f407e180-85db-11e9-9ac9-553858f9c410.png)

**Comment by MartinMuzatko** [comment]
I will create another issue

**Comment by MartinMuzatko** [comment]
closing this in favor of #5857
