### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zuley** [nuxt/nuxt.js#582]
[DEMO地址](https://github.com/zuley/Vue-WordPress-API)
大量重复的标签堆叠，会导致这个错误发生。
注：有时候直接编写热重载后页面可以显示，但是刷新后还是会报错。
![qq20170418-235518](https://cloud.githubusercontent.com/assets/3047318/25140453/f77e5e36-2492-11e7-9d8e-3f988fbf82df.png)

**Comment by zuley** [comment]
**补充一点**
空白页面的重复堆叠标签，即使不使用任何外部的资源。也会导致这个错误的发生

**Comment by alexchopin** [comment]
Hi, sorry we don't speak Chinese, can you write the issue in english please?

**Comment by zuley** [comment]
I'm sorry.
I can't speak English, this is I use machine translation.

A large number of repeated label stack, will lead to the error occurred.Such as repeated 600 lines of code

```
// repeated 600 lines of code
<dl>
    <dd>Title</dd>
    <dt>Text ...</dt>
</dl>
```

**Comment by Atinux** [comment]
It works perfectly on my machine.

Make sure to use the last version of Nuxt.js @zuley 

![screenshot_2017-04-20_13-49-07](https://cloud.githubusercontent.com/assets/904724/25229355/341c1b24-25d0-11e7-9fd5-d3353703dfe0.png)

**Comment by zuley** [comment]
Thank you very much for your answer, I have found the cause of the problem.
After all installation package upgrade, already can use.

**Comment by chunge0328** [comment]
@zuley 可以了吗？我的还是不行。。。
@Atinux In production，Wrong：
![image](https://user-images.githubusercontent.com/6309807/28806821-a2f41b6c-76a4-11e7-934d-ac6456c72808.png)
https://dolceviva.com/productlist/53

Why

**Comment by chunge0328** [comment]
F5 error。。。

**Comment by michaelpumo** [comment]
Not sure if it's worth noting, but I had this same error.

I then realised I had an accidental tag, like `<Tail />` in my template. This caused the error. `<Tail />` didn't actually mean anything as it was a find and replace error, when it should have been a div.

This appeared to trip Nuxt up. If anyone's seeing this error, try and check your templates for tags that Nuxt is probably expecting to be a component but isn't.

**Comment by zuley** [comment]
@chunge0328 我当时是升级了所有包，就可以了。
