### ISSUE TITLE
--config-file issue with TypeScript

### ISSUE THREAD

**Issue by wesssel** [nuxt/nuxt.js#5821]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Steps to reproduce

1. Create `nuxt.config.ts` and move it in a folder. Example: `sites/site-1/nuxt.config.ts`
2. Add `/pages/index.vue` in `sites/site-1/`
3. Run `yarn nuxt sites/site-1`. This won't use the `nuxt.config.ts` file
4. Run `yarn nuxt sites/site-1 --config-file=/Absolute/Path/To/Folder/sites/site-1/nuxt.config.ts` throws:

```
 ERROR  Unexpected token import                                                                                                                                                                                                     15:20:42

  (function (exports, require, module, __filename, __dirname) { import {
  ^^^^^^

  SyntaxError: Unexpected token import
  at createScript (vm.js:80:10)
  at Object.runInThisContext (vm.js:139:10)
  at Module._compile (module.js:617:28)
  at Object.Module._extensions..js (module.js:664:10)
  at Module.load (module.js:566:32)
  at tryModuleLoad (module.js:506:12)
  at Function.Module._load (module.js:498:3)
  at Module.require (module.js:597:17)
  at require (internal/module.js:11:18)
  at loadNuxtConfig (node_modules/@nuxt/cli/dist/cli-chunk.js:2458:17)

```

### What is expected ?

Nuxt works with the nuxt config TypeScript file

### What is actually happening?

Throws an error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9274">#c9274</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@wesssel Could you provide repository with your exact configuration please ?
Or at least these files : `package.json`, `tsconfig.json` (and tell me where is `tsconfig.json` located).

**Comment by wesssel** [comment]
By your question, I realized that the `tsconfig.json` wasn't in the right place.

I move it to the `/sites/site-1` and it works after.

Thank you for helping me raising that question, apologies for bothering.

**Comment by kevinmarrec** [comment]
No problem 😃
