### ISSUE TITLE
Offline Plugin not working with nuxt generate

### ISSUE THREAD

**Issue by joshbnntt** [nuxt/nuxt.js#583]
Love Nuxt and am excited about Offline Plugin support!

I'm trying to use it in a project where I use `nuxt generate` feature. I'm basing it off of the [offline plugin demo](https://github.com/nuxt/nuxt.js/tree/master/examples/offline-nuxt).

The problem I'm running into is that I can't get the service worker to be created in the root directory. It instead gets placed in the `_nuxt ` directory. Since the service worker isn't at root, it doesn't correctly work offline as not all of the assets are handled. Only what's in `dist/_nuxt` is handled by the service worker so the offline plugin doesn't really work offline.

I've tried to set various options for the offline plugin, but with no success.

Has anyone gotten an offline plugin example working with `nuxt generate`?

**Comment by Atinux** [comment]
Actually the offline-plugin is in WIP and not ready yet :)

**Comment by joshbnntt** [comment]
Ah, okay. 

Thanks!

**Comment by piyushchauhan2011** [comment]
Is there any way to get around this problem ? @Atinux @joshbnntt  I looked into changing `pubilcPath` and `relativePaths` but they doesn't seem to work if we change in `nuxt.config.js`

**Comment by piyushchauhan2011** [comment]
Also I think for now, we can use `publicPath` option in `build: { }` object and not in `offline: { }` object to generate a `/` root distribution so that Service Worker can be activated. Something like this:

```
build: {
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    },
    extractCSS: true,
    publicPath: '/',
    vendor: ['axios']
  }
```

**Comment by frankspin89** [comment]
When using ```PublicPath: '/' ``` the service worker is loading correctly. Only some references to assets are now containing a double //. Resulting in a 404. 

In my simple example the icon and manifest located in the head are included with href="//".

Any way to fix this?

**Comment by Atinux** [comment]
@frankspin89 do you mind providing a screenshot @frankspin89 ?

**Comment by Atinux** [comment]
Closing it since offline plugin should now be used with module and is not part of the core anymore.
