### ISSUE TITLE
Using timeout in mixins is triggering an "Invalid component name" error

### ISSUE THREAD

**Issue by SDVII** [nuxt/nuxt.js#5831]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://jsfiddle.net/n5ov6db7/](https://jsfiddle.net/n5ov6db7/)

### Steps to reproduce

1) Create a Vue mixin in the plugins folder
2) Add a store variable
3) Set the store's value in the mixin [works fine]
4) Set the store's value inside a timeout in the mixin
5) Error shows up

### What is expected ?

Using timeouts in plugins/mixin should not trigger any issues

### What is actually happening?

An error is showing upon starting the app (or refreshing) after the addition of the timeout

### Additional comments?

While logging out, the user object is erased. However, because some pages might be using the user object before the logging out is finished, I've decided to empty the user object after a redirect. This, however, triggered an unrelated error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9281">#c9281</a>)</em></sub></div>

**Comment by pimlie** [comment]
If you add a mixin you can just use `this.$store`, no need to use the store from the context of the plugin for that. The below should also just work as a plugin without using any context, can you try this?

```js
import Vue from 'vue'
import Cookies from 'js-cookie'

  Vue.mixin({
    methods: {

      logout() {
        Cookies.remove('token')
        Cookies.remove('refresh-token')
        Cookies.remove('u')
        this.$store.commit('SET_TOKEN', null)
//        redirect('/sign-in')
        //This works fine
        //store.commit('SET_USER', null)
        
        //This triggers error:
        //commons.app.js:11911 [Vue warn]: Invalid component name "pages/SignIn.vue". Component names should conform to valid custom element name in html5 specification.
        setTimeout(() => {
          this.$store.commit('SET_USER', null)
        }, 200)

        this.$router.push('/sign-in')
      },
    },
  })

```

**Comment by SDVII** [comment]
Sorry for the late reply.

**Comment by SDVII** [comment]
The issue is still ocurring
