### ISSUE TITLE
NPM Module Dependency Unavailable

### ISSUE THREAD

**Issue by ChildishForces** [nuxt/nuxt.js#5837]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://www.npmjs.com/package/nuxt](https://www.npmjs.com/package/nuxt)

### Steps to reproduce

Pull latest:

npm i nuxt@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nuxt/core@2.8.0

### What is expected ?

To be able to pull

### What is actually happening?

Not able to satisfy dependencies

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9285">#c9285</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. It seems an NPM cache propagation problem. Please wait a few minutes (may take some hours in some conditions)

**Comment by pi0** [comment]
Should be fixed.
