### ISSUE TITLE
Optional Consola

### ISSUE THREAD

**Issue by nh0627** [nuxt/nuxt.js#5842]
### What problem does this feature solve?

Hi, 
I have an issue with the latest Nuxt version(2.8.0), especially with "consola".
Our team is using a custom console style something like this: https://hackernoon.com/styling-logs-in-browser-console-2ec0807dc91a

However, because of wrapConsole(), our team's custom console style is not displayed.
Could you get wrapConsole() optional? 👉 https://github.com/nuxt/nuxt.js/pull/5810/commits/7be2f7805389af7f0388c174b788165efbfca993
something like add an option, devConsola = false, in nuxt.config.js?

I can make a PR if you want (devConsola=false or with some nuxt option property name like this), 
or could you fix it for our team's console log😭? 
or is there any other solution for this situation?

Thanks!

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9289">#c9289</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi, @nh0627. Sure we can make it optional for development mode :)

**Comment by nh0627** [comment]
@pi0 Thank you👏👏👏

**Comment by pi0** [comment]
@nh0627 What do you think if we just don't override `console.log`? (But other console log levels). Also as a workaround for now you can try `console.__log`

**Comment by nh0627** [comment]
Thanks @pi0! 
I think if consola.wrapConsole() doesn't override the default console.log, it would be fine. We just basically need default console.log and customize it. 

> Also as a workaround for now you can try console.__log

BTW, what this means?
I was trying to change our console.log, e.g. console.log("%cHello", "color: blue; font-size: 20px");, to console.__log("%cHello", "color: blue; font-size: 20px");, but still it's broken.

Thank you again!

**Comment by pi0** [comment]
Nuxt no longer override `console.log` in 2.8.1: https://github.com/nuxt/nuxt.js/releases/tag/v2.8.1

**Comment by nh0627** [comment]
@pi0 Grate! Thanks a lot
