### ISSUE TITLE
Babel cacheDirectory property missing on NuxtConfiguration type

### ISSUE THREAD

**Issue by marc1404** [nuxt/nuxt.js#5843]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://github.com/marc1404/nuxt-babel-cacheDirectory](https://github.com/marc1404/nuxt-babel-cacheDirectory)

### Steps to reproduce

1. Clone the repository
2. Install dependencies using npm/yarn
3. Open the project in a JetBrains IDE (e.g. WebStorm)

### What is expected ?

The NuxtConfiguration type should include a boolean property called cacheDirectory on the babel property.

### What is actually happening?

The property is missing from the type and shows as an error in WebStorm.

### Additional comments?

The property is still referenced on the Nuxt documentation:
https://nuxtjs.org/api/configuration-build/#babel

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9290">#c9290</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
It seems that `cacheDirectory` isn't a `babel` option but a `babel-loader` specific option (see https://github.com/babel/babel-loader#options). And they don't provide types for it, so I guess only solution is that we implement our own interface for these missing types.
