### ISSUE TITLE
 SyntaxError : Unexpected identifier with a blank new project.

### ISSUE THREAD

**Issue by milgron** [nuxt/nuxt.js#5845]
Hi there! 

Since Nuxt 2.8.0, when i create a new project, if i create it without dependencies, everythin goes fine. But, when i added some dependencies (like Axios, or Bootstrap) the error appears since the first 'npm run dev' execution.

**Comment by pi0** [comment]
Hi. Related to a known issue (#5822). Next release of BootstrapVue is in few hours.
