### ISSUE TITLE
How to use next.js with sails.js? (is it possible)

### ISSUE THREAD

**Issue by fortil** [nuxt/nuxt.js#585]
Hi guys

I'm very very new with SSR and Nuxt.js, yesterday I read the documentation of Nuxt.js yesterday, it is wonderful.

But, I use Sails.js and I will like to know if is posible use both?.

Thanks

**Comment by Atinux** [comment]
It is possible, I don't use Sails.js but look at the express template, it shock be the same (nuxt as a middleware)
