### ISSUE TITLE
Google tag manager module script on head

### ISSUE THREAD

**Issue by ahmedfaical** [nuxt/nuxt.js#5850]
### What problem does this feature solve?

Hello, i really appreciate what it does google-tag-manager package and i have a question and feature request about it.
Does it have an option to put the gtm script in body (body: true) or we have to modify the package on node_modules directly?
`// Add google tag manager script to head  @nuxtjs/google-tag-manager/index.js line 47
  this.options.head.script.push({
    src: (options.scriptURL || '//www.googletagmanager.com/gtm.js') + '?' + queryString,
    async: true,
    body: true
  })`
It will be nice to add this as an option if it does not exist.
I have another question about script, when I add (body: true) in @ nuxtjs / google-tag-manager / index.js line 47. the script is added at the end of the body scope but the script https: // www. google-analytics.com/analytics.js appears in the head, how can i move it to the body?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9297">#c9297</a>)</em></sub></div>

**Comment by manniL** [comment]
Please open an issue in https://github.com/nuxt-community/modules/ :relaxed:
