### ISSUE TITLE
connect ECONNREFUSED when set middleware.

### ISSUE THREAD

**Issue by estylehq** [nuxt/nuxt.js#5856]
shown ```connect ECONNREFUSED 127.0.0.1:80``` when ```middleware``` in ```nuxt.config.js```

It work remove middleware line in ```nuxt.config.js```.

What I missing?

* nuxt.config.json
```
export default {
  ...
  proxy: {
    '/api/': '{{ TEST API SERVER }}',
  },
  router: {
    middleware: ['session'],
  },
  ...
};
```

* api/index.js
```
import axios from 'axios';

export const METHOD_GET = 'GET';
export const METHOD_POST = 'POST';

axios.defaults.baseURL = '/api/v1';

export function request(config) {
  return axios({
    ...config,
    headers: {
      ...config.headers,
    },
  }).then(response => response.data);
}
```

* ~/api/user/index.js
```
import { METHOD_GET, METHOD_POST, request } from '~/api';

export default {
  login(memId, memPwd) {
    return request({
      url: 'member/login',
      method: METHOD_POST,
      params: { memId, memPwd },
    });
  },
  session() {
    return request({
      url: 'member/session',
      method: METHOD_GET,
    });
  },
};
```

* ~/middleware/session.js
```
import api from '~/api/user';
import { USER_GET_SESSION } from '~/store/mutation-types';

export default async function({ store }) {
  const response = await api.session();
  if (response.error) {
    store.commit(`session/${USER_GET_SESSION}`, null, { root: true });
    return;
  }
  const { ssn } = response;
  store.commit(`session/${USER_GET_SESSION}`, ssn, { root: true });
}
```

<img width="969" alt="Screen Shot 2019-06-03 at 12 09 10 PM" src="https://user-images.githubusercontent.com/37822976/58773618-b6658180-85f8-11e9-9262-24e2cc5609fe.png">

**Comment by estylehq** [comment]
anyone?

**Comment by sionzeecz** [comment]
Same here! 
@estylehq did you found any solution?

**Comment by Kapil-chn7** [comment]
> Same here!
> @estylehq did you found any solution?

@sionzeecz any solution for this?

**Comment by sionzeecz** [comment]
@Kapil-chn7 sorry I have abounded nuxt. it has so many bugs and limitations. I ended doing quick own small solution what works faster and is more flexible for configuration. I have enough experience and Nuxt was more frustrating than enjoyable. I wish you good luck finding your way through.

**Comment by Cally99** [comment]
Nuxt is a pile of crap to be honest. So many bugs.
