### ISSUE TITLE
Fresh install (create-nuxt-app) dev server breaks when old service worker is still around

### ISSUE THREAD

**Issue by moka491** [nuxt/nuxt.js#5859]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://localhost:3000](https://localhost:3000)

### Steps to reproduce

1. Create app using create-nuxt-app, using a server of choice (say koa), and tick all the accessories (pwa, axios etc), and no testing framework.
2. Change up a few component styles or texts, and run a production server (build + start) and a dev server. Stop them.
3. Create a new app like in 1), with the same accessories. I used the same folder for this (if it matters).
4. Start a dev server, see if the website works. If it does, try changing a few things, build+start it, and then go back to 3) to repeat. It's to stack up on service workers with different style changes each to distinguish them.

At some point, it will bug out. It does so very reliably for me now. See this video for how it looks:
https://cdn.discordapp.com/attachments/473406004751499275/585027758426423307/Screen_Recording_2019-06-03_at_10.49.39.mov

Here's the Chrome Dev tools log for what happens there:
https://cdn.discordapp.com/attachments/473406004751499275/585026638283014147/localhost-1559551544703.log

### What is expected ?

A dev server to work and not get glitchy, even if there's an old service worker, or a service worker from another project registered.

### What is actually happening?

When starting the dev server, the site glitches and the dev server crashes after a few seconds due to that. It looks like the served website quickly switches between different cached versions the service worker had (I see all the css changes I did and built before, quickly switching from one to another).

### Additional comments?

This was (quick fixed) by going into Chrome Devtools -> Application -> Clear Storage, because it unregisters existing service workers.
For a quick solution (untested though), we could use different default ports for dev and production, so that production built service workers dont get mixed into dev server environments.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9304">#c9304</a>)</em></sub></div>

**Comment by pi0** [comment]
This is a well known issue with workbox.  Unfortunately no workaround unless using different ports or not starting production mode in same port or unregister sw. I'll close this issue as is related to pwa-module.
