### ISSUE TITLE
There is a problem with the operation of the axios module after updating nuxt 2.8.0. 

### ISSUE THREAD

**Issue by kdydesign** [nuxt/nuxt.js#5861]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[http://localhost:3000](http://localhost:3000)

### Steps to reproduce

No additional options are communicated when using axios.

```
this.$axios.$post('url', parameter, options)
```

### What is expected ?

Since only the nuxt has been updated, there seems to be no problem with the anxios module.

### What is actually happening?

There is a problem with the operation of the Axios module after updating nuxt 2.8.0. 

Axios uses @nuxtjs/axios' version 5.3.6 and does not function normally if options are exceeded when using anxios.

`this.$axios.$post('url', parameter, options)`

The options were normally passed over and used until nuxt 2.7.1, and these options are handled by axios interceptor.

```
$axios.onResponse(response => {
   response.config.options....
})
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9306">#c9306</a>)</em></sub></div>

**Comment by pimlie** [comment]
Please create a reproduction for this issue (eg on codesandbox)

**Comment by kdydesign** [comment]
@pimlie 
Example uploaded to codesandbox.

https://codesandbox.io/s/codesandboxnuxt-j0vdq

I think we can refer to store and axios.js.


The problem is that the options delivered via $axios are no longer working normally.

**Comment by pimlie** [comment]
Thanks but what do I need to do to reproduce the error?

**Comment by kdydesign** [comment]
@pimlie 
No errors are generated. The difference between 2.7.x and 2.8.x works normally, but the difference between 2.7.x and 2.8.x is options in `this.$axios.$post('url'), parameter, options)`. In 2.7.x, you can specify `options` to obtain properties from the interceptor of $axios normally, but in 2.8.x, you cannot receive `options` from the interceptor of $axios. What's different?

**Comment by kdydesign** [comment]
@pimlie 
On second check, the problem appears to have occurred when axios, not the nuxt problem, updated to version 0.18 to 0.19.x.

The third option is not merged with the 'config'.
