### ISSUE TITLE
How can i rename .nuxt directory ?

### ISSUE THREAD

**Issue by rubyless** [nuxt/nuxt.js#587]
Because the .nuxt Is a hidden directory, I need upload this directory.

**Comment by alexchopin** [comment]
package.json
```js
  "scripts": {
    "build": "nuxt build && rm -rf dist_folder && mv .nuxt dist_folder",
  }
```

**Comment by rubyless** [comment]
I use nuxt/express to generate my project, Terminal tell me 'No build files found, please run `nuxt build` before launching `nuxt start`'  if i move .nuxt directory @alexchopin

**Comment by Atinux** [comment]
Why do you need to upload the `.nuxt` directory @rubyless ?

Anyway, it's planned to specify the outpub folder in a future release, see https://github.com/nuxt/nuxt.js/issues/294
