### ISSUE TITLE
Nuxt Strange Behaviour on axios call during form submit

### ISSUE THREAD

**Issue by sagarlava** [nuxt/nuxt.js#5872]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://codesandbox.io/s/codesandboxnuxt-oqk58](https://codesandbox.io/s/codesandboxnuxt-oqk58)

### Steps to reproduce

1) I have asyncData and api is fetched in Servver Side, open URL, open condsandbox preview window as seperate and inspect to see console.
2) now simply reload page, you will get IP address coming
3) now please click submit button, you wlll see console saying 400 erro, but why it became 400, in my local project, API hanges, and says "Socket Hung Up" error

### What is expected ?

I need to see IP address like normal refresh

### What is actually happening?

Nuxt axios is working differently and it is failed to call API?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9310">#c9310</a>)</em></sub></div>

**Comment by pimlie** [comment]
The API request in the CSB fails due to the `Connection: Upgrade` header that is sent with the request. It seems that header is automatically set by codesandbox. So I am not sure whether the issue in the CSB is the same as you are experiencing.
