### ISSUE TITLE
Nuxt Axios Fails on POST to route

### ISSUE THREAD

**Issue by sagarlava** [nuxt/nuxt.js#5873]
While I do form submit to some routes with POST with data from FORM, if that route is consuming server side fetch on asyncData and calls some API via store using axios, response fails, or sometime it hangs and gives "Socket Hung Up" error in node console

Step to produce issue
-----
1) visit https://codesandbox.io/s/codesandboxnuxt-oqk58
2) Open preview window in new window
3) Just reload page from browser, you will see ip address fetched from api
4) But if you click submit button of form, same api fails, and in my project, it hangs, so why this happened and what is this behaviour? What exactly happened there? Looks like nuxt or nuxt/axios issue

**Comment by pi0** [comment]
Thanks for the report. Should be fixed in 5.5.4
