### ISSUE TITLE
0.10.x removed extract-text-webpack-plugin? 

### ISSUE THREAD

**Issue by rubyless** [nuxt/nuxt.js#588]
I edit the nuxt.config.js:

```
build: {
        loaders: [
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract({
                    use: ['vue-style-loader', 'css-loader', 'sass-loader']
                })
            }
    ],
     plugins: [
            new ExtractTextPlugin({
                filename: 'styles.css'
            })
     ]
}
```
but not work

**Comment by alexchopin** [comment]
Can you explain more about what you are trying to do?

**Comment by rubyless** [comment]
After npm run build, The style in components  is built into a .js file

I want to build the style in components into a .css file.

**Comment by alexchopin** [comment]
#471 #478

**Comment by pi0** [comment]
Just found this nice article that shows possible improvements of inlining css :) 
https://www.smashingmagazine.com/2017/04/guide-http2-server-push/

![image](https://cloud.githubusercontent.com/assets/5158436/25423718/f5230be4-2a7a-11e7-8a7a-569f1e3e625f.png)

**Comment by ArnoBuschmann** [comment]
@pi0 Just for a better understanding, the article you mentioned says about inlining CSS: "The poison pill we swallow when we do this, however, is that the inlined content can’t be efficiently cached."

So am I right to assume, that the advantage of inlining is greater than the ability to cache a bigger CSS file like bootstrap for example?
