### ISSUE TITLE
使用 nuxt-link 在进行路由跳转的时候会触发两次mounted

### ISSUE THREAD

**Issue by zrainice** [nuxt/nuxt.js#5880]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://gm.zrain.top:3000](http://gm.zrain.top:3000)

### Steps to reproduce

使用 nuxt-link 在进行路由跳转的时候会触发两次mounted,限制在 process.client 也会触发两次 mounted,且第一次的 this 与 第二次的 this 不是同一个对象

### What is expected ?

使用 nuxt-link 在进行路由跳转的时候会触发两次mounted,限制在 process.client 也会触发两次 mounted,且第一次的 this 与 第二次的 this 不是同一个对象

### What is actually happening?

使用 nuxt-link 在进行路由跳转的时候会触发两次mounted,限制在 process.client 也会触发两次 mounted,且第一次的 this 与 第二次的 this 不是同一个对象

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9316">#c9316</a>)</em></sub></div>

**Comment by zrainice** [comment]
问题主要是登陆页使用了极验的服务,在mounted的时候调用初始化,发现会调用两次出现两个校验,但是刷新没有问题,只有路由跳转过来会有问题, 两次的 this 的指向是不同的,获取 dom 元素也都是空白的,但是append进dom元素会出现两个

**Comment by clarkdo** [comment]
@zrainice 能否提供一下重现问题的详细步骤 ？ 如果可以的话，最好提供一个可以重现问题的最小代码仓库。
