### ISSUE TITLE
Naming a layout "Nuxt" will produce a maximum call stack error

### ISSUE THREAD

**Issue by remarks** [nuxt/nuxt.js#5881]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandboxnuxt-m1cto](https://codesandbox.io/s/codesandboxnuxt-m1cto)

### Steps to reproduce

1) Add a name "Nuxt" to a layout file.

### What is expected ?

Will render

### What is actually happening?

Render properly or produce an error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9317">#c9317</a>)</em></sub></div>

**Comment by pimlie** [comment]
I believe this is a non-issue, you are creating a component and using that same component within itself. Ofcourse that is going to trigger a recursive loop thus a Maximum call stack error. Its exactly the same as this: https://jsfiddle.net/xLuop5rj/
