### ISSUE TITLE
关于在plugins中创建filter时出现的问题

### ISSUE THREAD

**Issue by iamAFengZi** [nuxt/nuxt.js#5882]

**Comment by iamAFengZi** [comment]
按照官方创建plugins的文档说明，我创建了一个filters.js的文件
作用是用来做页面简体与繁体转换的过滤
具体代码是：

import Vue from 'vue';
let Chinese = require('chinese-s2t');

let lang_type = window.localStorage.getItem('lang') || 'zh-cn';

if(process.browser) {
  Vue.filter('lang', (value) => {
    return lang_type === 'zh-cn' ? value : Chinese.s2t(value);
  });
}

filters.js文件本身没有任何问题，只是在项目run dev后，每次刷新页面都会出现构建报错。
终端控制台都会出现以下警告信息：
[Vue warn]: Failed to resolve filter: lang 

错误的个数跟在vue文件中使用lang过滤器的次数相对应。

个人尝试去寻找错误原因，发现每个页面在初始化时，在vue声明钩子前3个阶段都没有发现filters.js
文件中注册过的过滤器'lang'，只有在mounted阶段过滤器才注册完毕。
但是由于nuxt本身框架的原因，在vue前三个钩子阶段就已经渲染了页面，并使用了过滤器‘lang’，而
这时候就报错了。

以上是个人理解，不知道是否是该原因，本人为nuxt初次使用者。
另外，项目能正常在浏览器中运行，过滤器也能生效，只是每次页面刷新切换简繁体效果时会出现闪烁和字体转换过渡的效果（指页面刷新后字体会先显示为简体，再过滤器生效显示为繁体，有个转换过程）

想要解决的问题：
1、想知道是否能解决filter为何在初始阶段没有被注册的问题，或者直白点就是解决报错。
2、想解决页面刷新后，直接显示过滤后的效果，而不是先显示原始文本，再显示过滤文本。

求大神指教。 万分感谢

**Comment by XPLing** [comment]
请问楼主解决了吗？同样遇到这个问题了，但找不到解决方法
