### ISSUE TITLE
Page transition hooks execution scope is "getting lost"

### ISSUE THREAD

**Issue by JacekZakowicz** [nuxt/nuxt.js#5884]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/embed/codesandboxnuxt-46hro](https://codesandbox.io/embed/codesandboxnuxt-46hro)

### Steps to reproduce

In any of the page transition object hooks (enter, leave) try to access the page component. It is impossible, scope is "lost" or undefined.

### What is expected ?

`this` to point the page component instance

### What is actually happening?

`this` is undefined or other unknown

### Additional comments?

This issue is kind of a renewal of: https://github.com/nuxt/nuxt.js/issues/2374 which was closed without the answer. 
I ran into the issue when trying to make JS driven, animated page cover/reveal component. I wanted to delegate the animations from the page component to the mentioned one. Unfortunately there is no way to get access to the page component instance from the page transition hooks.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9319">#c9319</a>)</em></sub></div>

**Comment by pimlie** [comment]
I cant reproduce the error in your CSB, eg `ENTER scope:` always logs with the parent Nuxt component.

**Comment by JacekZakowicz** [comment]
@pimlie what do you mean by saying _parent Nuxt component_? I do not get any logs in the CSB (In the line with: `console.log("ENTER scope:", this);`). I tried Chrome and Firefox.

**Comment by pimlie** [comment]
Like this:
![image](https://user-images.githubusercontent.com/1067403/59046707-c1334700-8882-11e9-918a-8e535719a526.png)

**Comment by JacekZakowicz** [comment]
I have just redone even more simple example and still I do not get `this` in the CBS. But I have noticed that I do get some more logs in the browser console. Will investigate more.

**Comment by JacekZakowicz** [comment]
Alright,
I guess I got confused by the logs issue and the fact that `transition hooks` are executed in the page's parent's scope not as I assumed in the page component scope.
I would say that I can hardly find logic behind it as the hooks are defined in the page component itself. So in my case when I wanted to modify the look/behaviour of the animation&components in the hooked functions it did not work.
  
But I guess this is for other discussion. 
Thank you for your help.

**Comment by pimlie** [comment]
Its because the page-component is placed in a router-view component which is a child of the transition component. All the magic happens here: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-child.js

So we could probably use router-view as context instead of the nuxt parent but the page component itself we cant directly access (as it might not have been loaded yet)

**Comment by JacekZakowicz** [comment]
Understood. Thank you once more.
