### ISSUE TITLE
@nuxt/babel-preset-app causing "SyntaxError" 

### ISSUE THREAD

**Issue by mahapo** [nuxt/nuxt.js#5892]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-0o6ej?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-0o6ej?fontsize=14)

### Steps to reproduce

After updating to 2.8.1 i have this error:
If you use "@nuxt/babel-preset-app" in the nuxt.config.js for example:

```javascript
build: {
 babel: {
      presets: [
        [
          "@nuxt/babel-preset-app",
          {
            modules: "commonjs"
          }
        ]
      ]
    }
  }
```

this shows  "Unexpected token export SyntaxError"

### What is expected ?

Site should not crash

### What is actually happening?

Site is showing "Unexpected token export SyntaxError"

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9326">#c9326</a>)</em></sub></div>

**Comment by pimlie** [comment]
Please have a look at the documentation: https://nuxtjs.org/api/configuration-build#babel

If you need to override default presets (which is _not_ advised), then use the presets function:

```js
  build: {
    babel: {
      presets(ctx, [ preset, options ]) {
        options.modules = 'commonjs'
      }
    }
  }
```

**Comment by mahapo** [comment]
@pimlie Thanks for the tip
Also wrap the preset string with require.resolve fix this issue
`
build: {
 babel: {
      presets: [
        [
          require.resolve('@nuxt/babel-preset-app'),
          {
            modules: "commonjs"
          }
        ]
      ]
    }
  }

`
