### ISSUE TITLE
Wrong purgecss purge with tailwind

### ISSUE THREAD

**Issue by cosimochellini** [nuxt/nuxt.js#5898]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/cosimochellini/LattanaPrimeVideo](https://github.com/cosimochellini/LattanaPrimeVideo)

### Steps to reproduce

- yarn
- yarn dev
- open http://localhost:3000
- click "home" link (http://localhost:3000/home)
- check that the purged css is incorrect 

### What is expected ?

I expect to see the page with the tailwind classes I set
![Annotazione 2019-06-09 120222.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b9355710-8a9d-11e9-a9f4-491b353c3b4e.jpg)

### What is actually happening?

I see my components correctly but with CSS too purged, probably because purgecss only reads the first view of the app, and does not take into account the other
![Annotazione 2019-06-09 120448.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0d6e2960-8a9e-11e9-a9f4-491b353c3b4e.jpg)

### Additional comments?

the strange thing (in my opinion) is that if I go directly to any page via url (eg http: // localhost: 3000 / home) the css is purged correctly and the page is displayed correctly

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9328">#c9328</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey :wave: 	

Feel free to use https://github.com/Developmint/nuxt-purgecss which includes sensible defaults for most nuxt projects ;)
If you use 3rd party packages, you have to add them to the whitelist or the component paths to the purgecss paths.

last but not least, if you use nuxt-purgecss, you don't need to set up purgecss manually, nor you need a postcss.config

Check https://github.com/manniL/lichter.io for a production example :relaxed:
