### ISSUE TITLE
generate of dynamic routes running too quickly: delay needed

### ISSUE THREAD

**Issue by jroxendal** [nuxt/nuxt.js#590]
The backend I'm fetching data from in each page of a dynamic route crashes if queried too frequently. Since I have no control over the server I need some way to force a delay between calls to `renderRoute`.

**Comment by alexchopin** [comment]
Can you post a code snippet about your queries for generate option to help you?

**Comment by jroxendal** [comment]
This is my dynamic route (I have about 400 of them).
```
// pages/articles/_id.vue
async asyncData ({ params, error }) {
     var article = await backend.getArticle(params.id)
     return { article }
}
```

in my nuxt.config.js I have `generate: { routes: function() {/* promise that generates about 400 routes */}`

so when I run `npm run generate` the script slams my backend with 400 calls, causing it to crash. If I could force a delay between each of the 400 calls, of say 100ms, the script would take longer to execute but my server would probably survive. My sysadm is too busy to stabilise the server :(

**Comment by lukasborawski** [comment]
@Atinux @alexchopin Is this features works already? I don't have any delays between generating calls.

**Comment by Atinux** [comment]
You have to use `generate.interval` now (See https://github.com/nuxt/nuxt.js/blob/dev/lib/common/options.js#L122)
