### ISSUE TITLE
nuxt-child use iview an error

### ISSUE THREAD

**Issue by EightDoor** [nuxt/nuxt.js#5905]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://github.com/EightDoor/nuxtChild](https://github.com/EightDoor/nuxtChild)

### Steps to reproduce

RangeError: Maximum call stack size exceeded

### What is expected ?

You can use

### What is actually happening?

Child components

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9333">#c9333</a>)</em></sub></div>

**Comment by EightDoor** [comment]
nuxt-child iview Unable to display

**Comment by pimlie** [comment]
Could you maybe create a minimal reproduction on codesandbox? Your current repro is your full project and I am not sure what to do to get that error.

**Comment by EightDoor** [comment]
> 你可以在codesandbox上创建一个最小的复制品吗？您当前的repro是您的完整项目，我不知道如何处理该错误。

https://codesandbox.io/s/codesandbox-nuxt-teukd?fontsize=14

**Comment by EightDoor** [comment]
@pimlie https://codesandbox.io/s/codesandbox-nuxt-teukd?fontsize=14

**Comment by pimlie** [comment]
The maximum callstack error is probably triggered  in `/index/Card.vue` because you are using the component within itself. See #5881 for a similar issue and the jsfiddle I posted to clearly show the issue at hand

**Comment by EightDoor** [comment]
@pimlie thank you；ant-design-vue  There is no problem；

**Comment by pimlie** [comment]
What exactly do you mean?

**Comment by EightDoor** [comment]
@pimlie The problem I described use ant-design-vue inexistence error,Is it an iview problem

**Comment by pimlie** [comment]
No, it is a _you_ problem ;)

In `pages/index/Card.vue` change:
```
<script>
export default {
  name: "Card"
};
</script>
```
to
```
<script>
export default {
  name: "indexCard"
};
</script>
```

and it works. Or prevent the component from using it self recursively after X levels if you really do need to re-use the Card component

**Comment by EightDoor** [comment]
@pimlie Problem solved. Thank you very much
