### ISSUE TITLE
Computed, mixing plugins, routing is not working anymore for an unknown reason. 

### ISSUE THREAD

**Issue by jeromedupuis-relations** [nuxt/nuxt.js#5907]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://nolinksorry](http://nolinksorry)

### Steps to reproduce

Actually, there is not step to reproduce as I do know it what circumstance this bug appears.

### What is expected ?

No bug expected. 

### What is actually happening?

Global mixins doesn't work anymore.
Computed doesn't work anymore
If I use my own router with @nuxtjs/router, it doesn't work anymore

https://stackoverflow.com/questions/56494179/global-mixins-to-nuxt-v2-4-undefined

About computed data : 
These picture is showing pagination of data.
After clicking on page 2, it should show 4 rows. Nothing changes.
![2019-06-10 18.39.52.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/1b700f30-8b64-11e9-b1ad-5534e61df90e.gif)

![2019-06-10 18.43.07.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/8df5afb0-8b64-11e9-b1ad-5534e61df90e.gif)

About router : 
This picture show what happens if I set "keepDefaultRouter" to false
![2019-06-10 18.47.28.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0856ba10-8b65-11e9-b1ad-5534e61df90e.gif)

Error alert

```
TypeError: Cannot read property 'name' of undefined
    at VueComponent.getRouteBaseName (app.js:3436)
    at VueComponent.switchLocalePath
```

Line that error come up.
```
function getRouteBaseNameFactory(contextRoute) {
  var routeGetter = contextRoute ? function (route) {
    return route || contextRoute;
  } : function (route) {
    return route || this.$route;
  };
  return function getRouteBaseName(route) {
    route = routeGetter.call(this, route);

    if (!route.name) {
      return null;
    }

    return route.name.split(routesNameSeparator)[0];
  };
}
```

### Additional comments?

If I delete my repository, clone again  start my application...It works!
If I change something, or build for deployment. It breaks.

node v8.14.1
yarn 1.15.2
nuxt : 2.8.1
@nuxt/router : 1.3.2

If I delete my @nuxtjs/router , error still show up.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9334">#c9334</a>)</em></sub></div>

**Comment by pimlie** [comment]
Thanks for the report. Although your issue clearly shows there is an issue within your project, it doesnt help us to re-create your environment to reproduce and then debug the issue. So we would appreciate if you could setup a minimal reproduction of the issue. Help us help you :)

**Comment by jeromedupuis-relations** [comment]
Thank you for your reply!!
I will do that as soon as possible

**Comment by jeromedupuis-relations** [comment]
It was a mistake from my side... 
Everything is fine...

my buildDir directory was inside a firebase's functions directory (function/nuxt/ssr) 
There was a conflict between the app's node_modules and the functions's node_modules...

Anyway, thanks for your time:)
