### ISSUE TITLE
Nuxt goes crazy when disabling eslint-module (mixing of generate/start and dev)

### ISSUE THREAD

**Issue by amcsi** [nuxt/nuxt.js#5909]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1) Linux and Windows

### Reproduction link

(Clone this)
[https://github.com/amcsi/nuxt-weirdness](https://github.com/amcsi/nuxt-weirdness)

### Steps to reproduce

1. Run `npm install`.
2. Run `npm run generate && npm run start`.
3. Go to `http://localhost:3000`.
4. Stop the npm start command.
5. Run `npm run dev`.
6. Wait until the  console writes i "Waiting for file changes" and "Memory usage: xy MB (RSS: xy MB)...". Do _not_ do the next step while it's still bundling otherwise you get the "Client bundle" screen, and the issue will not be reproduced.
7. Go to `http://localhost:3000`. You should see the black overlay appearing, telling you about the no-unused-components eslint error.
8. Delete `'@nuxtjs/eslint-module'` from nuxt.config.js, or just checkout to the `origin/remove` branch where this has been done already.
9. Re-run `npm run dev`.
10. Wait like in Step 6.
11. Go to `http://localhost:3000`.

### What is expected ?

I don't get that annoying webpack hot overlay about non-error nitpicks, most notably the one about unused vue components.

### What is actually happening?

The overlay does indeed not show, but I get this in the console, and then from then on it's not possible to refresh the page, nor is the hot update JSON file able to be received:

> Uncaught (in promise) Error: Manifest request to /_nuxt/070b45d3c22c9e85296e.hot-update.json timed out.
>    at XMLHttpRequest.request.onreadystatechange (runtime.js:92)

### Additional comments?

In general, besides the fact that what's happening is buggy, I would really appreciate some advice on what I need to do to not get such minor errors appearing in an overlay during development. I'm happy to fix non-fatal errors before committing, but to show them as an overlay during development.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9338">#c9338</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @amcsi 
I can not reproduce

**Comment by amcsi** [comment]
Thanks for your response, @ricardogobbosouza.

Apparently this is related to service workers; by clearing them, it works like normal then. It's still confusing though; asking around in chat, people had no clue what was causing it based on how I was describing the issue.

Please see the updated "Steps to reproduce" section. An `npm run generate && npm run start` is needed too.

**Comment by ricardogobbosouza** [comment]
Sorry @amcsi , I have not been able to reproduce yet

**Comment by amcsi** [comment]
@ricardogobbosouza I swear this is happening. I just tried on Windows as well on Firefox. Before it was Linux and Chrome.

I have updated the steps again. I noticed that the issue is not reproduced if you load the page while it's still bundling.

**Comment by amcsi** [comment]
I have confirmed this is still an issue on a fresh Nuxt. I have created a new repo and am linking to it.

Basically this issue is about mixing using `generate` and `dev` while also messing around with eslint stuff.

**Comment by amcsi** [comment]
I already updated the steps to reproduce this, but haven't gotten a response yet.

**Comment by amcsi** [comment]
Yes, this is still an issue.

**Comment by amcsi** [comment]
Yes, this is still an issue.

**Comment by nuria-fl** [comment]
I'm having the same issue when removing the eslint module in `nuxt.config.js` and running `npm run dev` (no need to generate in my case). Clearing service workers did not help either, only solution was to enable eslint again. This is not at all desirable, I find the overlay getting in the way all the time during development, and I can handle lint checks via hook or CI.

**Comment by manniL** [comment]
@nuria-fl Just FYI, you can disable the overlay.

Anyway, I'll look into it as soon as there is a **minimal** reproduction repo available.

**Comment by manniL** [comment]
Like @ricardogobbosouza  I cannot reproduce it with the steps mentioned above. :frowning_face: 

It seems like a service worker issue to me though (which might cache the hot update response, thus repeating in an infinite loop). Switching port or clearing the service workers should work.

In case that won't help at all, you can still disable the overlay via https://github.com/nuxt/nuxt.js/pull/4498
