### ISSUE TITLE
Add transition to elements in a page on page-leave and page-enter

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#591]
Hi,
I have a list of tiles. something similar to you tube video tiles. I want to animate each tile on page-leave and page-enter. Something like a zoom-in and zoom-out.

**Comment by alexchopin** [comment]
Can you be more explicit about your issue?

**Comment by shyamchandranmec** [comment]
@alexchopin I have a list of components in a page. For eg: The component shows an image and a text below the image. When moving in and out of the page I want these components to be animated.

**Comment by motia** [comment]
what about adding a css rule to those elements: 
`.page-leave .zoom-out-on-leave {@extends(.zoom-out)}`
If your elements have `.zoom-out-on-leave` the zoom animation should happen at the same time with ".page-leave".

**Comment by shyamchandranmec** [comment]
@motia Will try it out.

**Comment by alexchopin** [comment]
@shyamchandranmec does it work?

**Comment by qm3ster** [comment]
I tried it and it works. 10/10
