### ISSUE TITLE
Prerendered SPA: Vue Router and `nuxt generate`

### ISSUE THREAD

**Issue by mrksbnch** [nuxt/nuxt.js#5912]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/mrksbnch/nuxt-generate-example](https://github.com/mrksbnch/nuxt-generate-example)

### Steps to reproduce

- Generate static files: `npm run generate` 
- Open `index.html` file  in `/dist` 
- Click on subpage link in `index.html`

### What is expected ?

If you click on the link in `index.html` ("Go to subpage"), Vue Router (in history mode) is used to redirect.

### What is actually happening?

If you click on the link in `index.html` ("Go to subpage"), a "hard" reload is performed (Vue Router is not used).

### Additional comments?

In this example, I'm using `<nuxt-router>` and I want a SPA with prerendered HTML files. Is this the expected behavior? If it is, is there any configuration to do a "soft" reload (with Vue Router) instead of a "hard" reload and still have statically generated HTML files for e.g. to be used on GitHub pages?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9340">#c9340</a>)</em></sub></div>

**Comment by pimlie** [comment]
Cannot reproduce the behaviour with the current repro. Do you load the file directly in the browser (`file://` proto) or through a webserver (`http://`)? If the former, make sure all js files are correctly loaded. I only tested through a webserver

**Comment by mrksbnch** [comment]
@pimlie Thanks, I just checked again and it was some configuration issue on my end. Sorry for the inconvenience.
