### ISSUE TITLE
Pass path to nuxt when starting programatically

### ISSUE THREAD

**Issue by MartinMuzatko** [nuxt/nuxt.js#5915]
### What problem does this feature solve?

When starting nuxt programatically, I should be able to pass a path.
As of now, this is not possible, at least not by what is documented.

### What does the proposed changes look like?

Add a second argument, next to the nuxt config to define from where the app is coming.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9341">#c9341</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @MartinMuzatko 

Have you looked at these options?
- [srcDir](https://nuxtjs.org/api/configuration-srcdir)
- [rootDir](https://nuxtjs.org/api/configuration-rootdir)

**Comment by MartinMuzatko** [comment]
Ah you can pass that directly to the nuxt config object! brilliant :)
I will test this.
Thank you a lot ❤️
