### ISSUE TITLE
renderState() not work

### ISSUE THREAD

**Issue by maunier** [nuxt/nuxt.js#5916]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://github.com/maunier/nuxt-learning.git](https://github.com/maunier/nuxt-learning.git)

### Steps to reproduce

npm install
npm run dev
check the source code of the page, you can find that there is no state

### What is expected ?

when i use renderState() in my custom template, i wish the state is injected to the template

### What is actually happening?

there is no state info in the html

### Additional comments?

the code in vue-server-renderer/build.dev.js :

```
TemplateRenderer.prototype.renderState = function renderState (context, options) {
  console.log('state:', context.state); // undefined
  console.log('nuxt.state:', context.nuxt.state); // is ok
  var ref = options || {};
    var contextKey = ref.contextKey; if ( contextKey === void 0 ) contextKey = 'state';
    var windowKey = ref.windowKey; if ( windowKey === void 0 ) windowKey = '__INITIAL_STATE__';
  var state = this.serialize(context[contextKey]);
  var autoRemove = '';
  var nonceAttr = context.nonce ? (" nonce=\"" + (context.nonce) + "\"") : '';
  return context[contextKey]
    ? ("<script" + nonceAttr + ">window." + windowKey + "=" + state + autoRemove + "</script>")
    : ''
};
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9343">#c9343</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @maunier 

Could you tell us what you are trying to achieve with this?

**Comment by maunier** [comment]
> Hi @maunier
> 
> Could you tell us what you are trying to achieve with this?

i wish that my page can run in both ie8+ and ie8-, so i need to customize my template to insert script and state depends on the browser version.

**Comment by Atinux** [comment]
Could you give us a concrete example of before and after the changes you want to make on the state?

**Comment by maunier** [comment]
> Could you give us a concrete example of before and after the changes you want to make on the state?

my nuxt.config.js:
```
render: {
    bundleRenderer: {
      template,
      inject: false
    },
    injectScripts: false
  }
```

my custom template:
```
<!--vue-ssr-outlet-->
    <!--[if (gt IE 9)|!(IE)]><!-->{{{ renderState() }}}{{{ renderScripts() }}}<--<![endif]-->>
```
so in the ie9+, i expect that the html contains both state and script but  in ie9- i want no state and script.

now renderScripts() works correctly, the problem is that renderState() now renders nothing, i need it return right script

now i have used 'render:route' hook to meet my requierment, i will remove states and scripts if it is ie9-, but i think it is better to use renderState(), because it's more costful to remove state and script when nuxt have been rendered done.

**Comment by Atinux** [comment]
Have you tried to use the `app.html` template?

https://nuxtjs.org/guide/views#app-template

**Comment by Atinux** [comment]
Actually Nuxt.js does something else for the rendering the `state` since it adds more than simple Vuex state.

Are you aware that by doing so, any JS interactions won't work (dropdown, tooltip, etc) on IE9- ?

**Comment by maunier** [comment]
> Actually Nuxt.js does something else for the rendering the `state` since it adds more than simple Vuex state.
> 
> Are you aware that by doing so, any JS interactions won't work (dropdown, tooltip, etc) on IE9- ?

in IE9-, i will dynamically insert my own js. my requirement is that i need state and script in ie9+ and remove state and script in ie9-. but now renderState() returns none.

i have debug the source code, in vue-server-renderer/build.dev.js:
```
TemplateRenderer.prototype.renderState = function renderState (context, options) {

/**
    here is the key. vue use context.state to render state, but  in nuxt context,  context.state === undefined, that's why renderState() renders nothing in my custom template.
*/
  console.log('state:', context.state); // undefined
  console.log('nuxt.state:', context.nuxt.state); // is ok


  var ref = options || {};
    var contextKey = ref.contextKey; if ( contextKey === void 0 ) contextKey = 'state';
    var windowKey = ref.windowKey; if ( windowKey === void 0 ) windowKey = '__INITIAL_STATE__';
  var state = this.serialize(context[contextKey]);
  var autoRemove = '';
  var nonceAttr = context.nonce ? (" nonce=\"" + (context.nonce) + "\"") : '';
  return context[contextKey]
    ? ("<script" + nonceAttr + ">window." + windowKey + "=" + state + autoRemove + "</script>")
    : ''
};
```
