### ISSUE TITLE
Problems with hard refresh in mode: universal with  `nuxt generate`

### ISSUE THREAD

**Issue by gtso86** [nuxt/nuxt.js#5921]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://nuxt-ssr.gabrieltadeu.com/](http://nuxt-ssr.gabrieltadeu.com/)

### Steps to reproduce

1. Visit: http://nuxt-ssr.gabrieltadeu.com/
2. Click in any card
3. try to hard refresh the page
4. or visit directly a page generated by dynamic route: http://nuxt-ssr.gabrieltadeu.com/news/3088483/

### What is expected ?

What I expected is when I try to visit any page generated via a dynamic route after run `nuxt generate` is open the right content like when I navigate using nuxt-link

### What is actually happening?

Open index/home content with a JS error

### Additional comments?

Repo with files: https://github.com/gtso86/nuxt-example
Demo (mode: universal): http://nuxt-ssr.gabrieltadeu.com
Demo (mode: spa): http://nuxt-spa.gabrieltadeu.com/

My .htaccess example
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

My route tree example
```
pages/
| - index.vue
| - news/
   | - index.vue
   | - _id.vue
```
---

For now I can't deploy the project using `yarn build && yarn start` because I haven't a node server for my client. Since I'm running the project using an Apache server I tried `nuxt generate` instead with the .htaccess from vuejs doc. The problem is, when I share a link created by a dynamic route, the page doesn't load correctly (open the static index with a JS error). If I share a generated page/home page and navigate using `nuxt-link` the problem doesn't happen.

I tried `yarn build -- --spa` and the problem disappeared but the con is I haven't any generated content in my static files

How I can make `nuxt generate` sites work normally with dynamic routes like a SPA application?
For now the only workaround I've found is migrate to mode: spa instead

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9350">#c9350</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi,

I believe there is a problem in your child page `news/_id.vue`, it may come from a misusage of `asyncData` in it.

Since we cannot see any source code it will be difficult to know where is the issue in your code.

**Comment by gtso86** [comment]
Hi @Atinux you can see the `news/_id.vue` here
https://github.com/gtso86/nuxt-example/blob/master/pages/news/_id.vue

Could you please see if I have any problem with my asyncData?

**Comment by Atinux** [comment]
Well, in fact it's just that you don't generate the correct routes so it fallback to the `index.html` page which is your homepage, then the Vue app is mounted and cannot understand the `asyncData` since it's not the good one.

Please specify `generate.routes` inside your `nuxt.config.js` so Nuxt can generate all the routes of your blog/news: https://nuxtjs.org/api/configuration-generate#routes

**Comment by gtso86** [comment]
Reading the documentation I found how to generate programmatically but even using this method my example have more than 3088504+ posts and counting...

The best way to "fix" this is generate ALL dynamic content?

Since `news/_id.vue` is a dynamic route, Nuxt/Vue should works like a SPA instead? using index.html as entrypoint to render the correct content from the router? Like this example here http://nuxt-spa.gabrieltadeu.com/news/3088504/

I know this solution looks weird but if there a way to use something like that will be the best from the both worlds (prerendered + spa)

**Comment by Atinux** [comment]
Well in this case, you may want to leave `generate.routes` empty and redirect to the `200.html` file instead (see https://nuxtjs.org/api/configuration-generate#fallback)
