### ISSUE TITLE
When I make a web components  , Every image which like this way '~/assets/example.png' is not found

### ISSUE THREAD

**Issue by HappyColour** [nuxt/nuxt.js#5923]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/HappyColour/Monster](https://github.com/HappyColour/Monster)

### Steps to reproduce

Download the zip && yarn && yarn components the problems will show

### What is expected ?

i want to solve the problem which is make a Web Components error in nuxtjs

### What is actually happening?

all the images not found

### Additional comments?

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @nuxt/vue-app:  2.8.1
    @nuxt/vue-renderer:  2.8.1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: ^3.0.0-beta.10 => 3.8.0
    @vue/cli-plugin-eslint: ^3.0.0-beta.10 => 3.8.0
    @vue/cli-service: ^3.8.0 => 3.8.3
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: ^1.0.0-beta.27 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.2.2 => 5.2.2 (4.7.1)
    vue:  2.6.10
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.3
    vue-jest: ^3.0.3 => 3.0.4
    vue-loader:  15.7.0
    vue-meta:  1.6.0
    vue-no-ssr:  1.1.1
    vue-router:  3.0.6
    vue-server-renderer:  2.6.10
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.13 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex:  3.1.1
  npmGlobalPackages:
    @vue/cli: 3.8.2

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9353">#c9353</a>)</em></sub></div>

**Comment by HappyColour** [comment]
Make a Web Components in nuxtjs not only have the images problems but also have the axios api problems and <nuxt-link> tag problems.please help me find a good way to solve this problem in nuxtjs

**Comment by pimlie** [comment]
Why do you believe this is a Nuxt issue? The `yarn components` command does not use Nuxt at all. You just cant expect a specific nuxt feature to also work in an unrelated project like vue-cli-service.

**Comment by HappyColour** [comment]
> Why do you believe this is a Nuxt issue? The `yarn components` command does not use Nuxt at all. You just cant expect a specific nuxt feature to also work in an unrelated project like vue-cli-service.

I think the  nuxt Syntactic sugar is '~/assets/example.png' , vue-cli not discriminate this .
I just want to make a web components in nuxtjs , So I hope who can help me or someone like me .
