### ISSUE TITLE
redirect cause  Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#593]
Hi!

I have ```index.vue``` page like this:
```
<script>
  export default {
    fetch ({ redirect }) {
      return redirect('/catalog/')
    }
  }
</script>
```

When user click http://127.0.0.1/ there is a warning in the logs:
```
(node:7580) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 16): Error: Can't set headers after they are sent.
```

But when access http://127.0.0.1/catalog directly everything is ok.

Am I doing redirect in a incorrect way?

**Comment by alexchopin** [comment]
You should use `asyncData`or even better a `middleware` in that case.

**Comment by Atinux** [comment]
This issue has been resolved with the last version of Nuxt.js @awronski

**Comment by awronski** [comment]
@Atinux Thanks, it is working in 0.10.6

BTW, now the template is mandatory or else I get an error.
It is not a problem, I created empty. Just wanted to let you know.

```
Error: render function or template not defined in component: c:\git\craft\pages\index.vue
    at normalizeRender (c:\git\craft\node_modules\vue-server-renderer\build.js:6631:13)
    at renderComponent (c:\git\craft\node_modules\vue-server-renderer\build.js:6697:3)
    at renderNode (c:\git\craft\node_modules\vue-server-renderer\build.js:6681:7)
```
