### ISSUE TITLE
Could not use asyncData to set properties of complex types

### ISSUE THREAD

**Issue by khataev** [nuxt/nuxt.js#5930]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[CodesandBox demo](https://codesandbox.io/s/codesandbox-nuxt-6wmo3)

[demo repo on github](https://github.com/khataev/async-data-nuxt)

### Steps to reproduce

just load demo and see console log, there will be strings something like that:

2019-06-15T10:42:22.372Z 
2019-06-15T10:42:22.372+00:00

instead of objects

### What is expected ?

I'm expecting to get value of date1 and date2 to be an instances of Moment (moment.js) and DateTime (luxon) class. Also described bug here (https://stackoverflow.com/questions/56585084/strange-coercions-of-properties-in-asyncdata-in-nuxt-js)

### What is actually happening?

But i get strings. It seems to me that some kind of serialization is present, but it is not described in official documentation here (https://nuxtjs.org/guide/async-data) or here (https://nuxtjs.org/api/)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9358">#c9358</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @khataev 
No seu exemplo você não está utilizando nuxt.js
`asyncData` é um método do nuxt.js
You have simply created an application in vue

**Comment by ricardogobbosouza** [comment]
Hi @khataev
In your example you are not using `nuxt.js`
`asyncData` is a method of `nuxt.js`
You have simply created an application in vue

**Comment by ricardogobbosouza** [comment]
And running with `nuxt` worked perfectly

**Comment by khataev** [comment]
@ricardogobbosouza sorry, that was not nuxt, but pure vue. Updated my example - and it still not working ;(

**Comment by ricardogobbosouza** [comment]
@khataev 
Now I understand
But theoretically `asyncData` is not suitable for this

**Comment by ricardogobbosouza** [comment]
But you're right, it looks like `asyncData` is serialized at some point

**Comment by khataev** [comment]
And what's next??

**Comment by manniL** [comment]
It is a serialization issue and I don't think you can do much about that, except returning primitives or plain objects from asyncData.

Do you have a more in-depth use case?
