### ISSUE TITLE
Firefox character encoding issue

### ISSUE THREAD

**Issue by lambda0xff** [nuxt/nuxt.js#5933]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://not.applicable.com](http://not.applicable.com)

### Steps to reproduce

Create a brand new nuxt application with `npx create nuxt-app test`
Cd into directory and `yarn run dev`
Open Firefox at `localhost:3000`

### What is expected ?

A web page should be displayed

### What is actually happening?

A blank page is displayed with the following error message in the console:

"The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature."

### Additional comments?

Works fine on chrome and safari

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9362">#c9362</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't repro :thinking: 	
FF (dev edition) is my default browser, never experienced an issue like that :thinking: 	

![image](https://user-images.githubusercontent.com/640208/59503929-f272cf00-8ea1-11e9-883b-17b7f3c392cf.png)

**Comment by lambda0xff** [comment]
Looked at it again and it worked after clearing all Storage data (cookies, cache, localStorage, etc).
The data was left by another nuxt app.

**Comment by morgaca** [comment]
I've been getting this issue now for a couple of days and tried the above resolution (clearing storage data) as well as the following:

1. Switching Firefox profiles
2. Restarting Firefox
3. Re-installing Firefox
4. Rebooting my machine, as a means of clearing temporary files/storage, all to no avail

I'm getting this issue on `localhost:3000` for a particular Nuxt app but not for others when I run it on the same port number.

Are there any additional potential solutions to this?
