### ISSUE TITLE
0.10.6 break asyncData & this.$router.push

### ISSUE THREAD

**Issue by Nainterceptor** [nuxt/nuxt.js#594]
Hello,

With 0.10.5, in an method, I do this.$router.push() to change route.
After update to 0.10.6, my route is well changed, but template is not refreshed, but asyncData is well played.

Thanks,
Gaël

**Comment by alexchopin** [comment]
Hi, can you post some code snippet and explain more about your issue?

**Comment by sebastianmacias** [comment]
Is the issue only present in the static generated version of the site or also when you run the site with npm? I think it might be related to #531

**Comment by Nainterceptor** [comment]
Mhhhh, I'm trying to reproduce my issue in a fresh project, but... I don't have the issue in this project. I will check if it's a more complicated use case, I guess that I'm not the only one to see this issue, according to the two 👍, so @alidcastano & @isesol-global, can you help me ?

**Comment by mindbits** [comment]
I have the same problem.

It's a search where for example clicking on page 2 the results are requested via axios and the route is pushed to ?page=2 . 

Now what happens then is beyond me and hard to explain. It's like a time machine where everything happens again, just with the store data lost or messed up, so if I had filters set in the store and there were 50 results, after the first axios request, a second one would fire immediately and the search results would jump back to page 1 without filters set. Continuing setting filters also caused a weird mess in the store. So personally I think it has something to do with the store.

After finding this issue and reverting back to 0.10.5 everything works as expected.

**Comment by Atinux** [comment]
I could not reproduce this issue.

Can you create a reproduction ny forking https://glitch.com/edit/#!/nuxt-hello-world please?

Then, I'll re-open this issue.

**Comment by Nainterceptor** [comment]
Maybe like #671, but #671 is not working on 0.10.5

**Comment by Nainterceptor** [comment]
@mindbits : Do you have the last version of vuex ? Is you issue still here on 0.10.7 ? I guess that's issue was linked to an issue on a dependency of nuxt, and may be fixed somewhere.
