### ISSUE TITLE
[nuxt.js] Cannot load components DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by hansinhu** [nuxt/nuxt.js#595]
Refresh webpage ：
[nuxt.js] Cannot load components DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

**Comment by sebastianmacias** [comment]
How did you solve this? I'm having the same issue+

**Comment by wintergithub** [comment]
Same here!

**Comment by hartmut-co-uk** [comment]
Unsure what you're struggling with exactly but I've encountered the same error msg and was able to solve it.

Note: Error occurred only on **refresh** of _static_ generated page (`npm run generate`).
My use case was to hide/show a certain element based on the current page/route. My first approach simply was:

    <button v-if="['index'].indexOf($route.name) === -1" class="toggle-button">☰</button>

which caused the error, while working on dev mode. 

As an alternative way I went via css which works fine for generated SSR page & allows nuxt/vue to init properly after the first static page load...

    <button class="toggle-button" :class="{'hidden': ['index'].indexOf($route.name) !== -1}">☰</button>

Hope that may help anyone running into similar issues.

*mention https://github.com/nuxt/nuxt.js/issues/531

**Comment by colsen1991** [comment]
Came accross this same error while using `generate`. Turned out to be due to a inline comment in the `<template>` markup. This again lead to all `<nuxt-link>`s not working when I loaded the site from the URL containing the comment. 

Just leaving this here in case someone stumbles on the same issue/error :)

**Comment by peterzhanghui** [comment]
我也出现了同样的问题，刷新页面就报错，后来发现是我在构建的时候使用了 NODE_ENV=production，而且只有在production的时候才会报错。虽然我的问题解决了，但是这个问题应该是nuxt有什么特别的封装，而且我没有找到介绍文档。

**Comment by DearAKuan** [comment]
@peterzhanghui  我也碰到了同样的问题 但是构建的时候并没有使用NODE_ENV=production。。。头疼

**Comment by RohitRox** [comment]
`no-ssr` solved this one for me

**Comment by elpeyotl** [comment]
I had the same issue when i was generating my project. Funy it was not always showing an error. I reinstalled the nuxt-cli and it seems to work now!

`npm i nuxt-cli`
