### ISSUE TITLE
Change @nuxt/devalue package license from LIL License

### ISSUE THREAD

**Issue by tvthatsme** [nuxt/nuxt.js#5954]
### What problem does this feature solve?

nuxt has a package 'devalue' forked from Rich Harris. It is licensed under the LIL License but Rich has just changed this to MIT (https://github.com/Rich-Harris/devalue/issues/21). My company requires packages to be of a certain license before they can be used and the LIL License is not on the approved list nor seems supported these days (even the website lillicense.org is down now).

Can @nuxt/devalue's license be changed to reflect this on NPM?

### What does the proposed changes look like?

@nuxt/devalue being published to NPM under the MIT License

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9380">#c9380</a>)</em></sub></div>

**Comment by tvthatsme** [comment]
Hi @pi0, any updates on this? Seems like it should be a simple fix.

**Comment by pi0** [comment]
License changed to MIT in [v1.2.4](https://github.com/nuxt/devalue/releases/tag/v1.2.4) release.
