### ISSUE TITLE
generate done but can't stop

### ISSUE THREAD

**Issue by isesol-global** [nuxt/nuxt.js#596]
![image](https://cloud.githubusercontent.com/assets/25073774/25266988/c65d2f70-26a5-11e7-9cda-79d3b7be1e01.png)

I want to use jenkins publish my code. but the process can't stop itself. the jenkins can't do the things after.

**Comment by Atinux** [comment]
Does it stop on your local machine @isesol-global ?

**Comment by max-schu** [comment]
happens to me too on one project, doesn't happen on another.
Might be related to module incompatibility/ssr – just a educated guess…

**Comment by Atinux** [comment]
Closing the issue until more informations are given.

**Comment by florianwittmann** [comment]
Can confirm this and have a minimal example attached that includes this problem.
I use version 0.10.7 of nuxt and nuxt and nuxt build both work fine. Also the output of nuxt generate is correct. Still it does not terminate aber finishing the generation.

[Nuxt_Generate_Hung.zip](https://github.com/nuxt/nuxt.js/files/991235/Nuxt_Generate_Hung.zip)

**Comment by florianwittmann** [comment]
It seems to be related to Firebase module in my example case.
As written above - Everything still generates and builds fine, it is just not terminating the process.
@Atinux @max-schu @alexchopin
