### ISSUE TITLE
Ability to set build.publicPath at runtime

### ISSUE THREAD

**Issue by timmw** [nuxt/nuxt.js#5960]
### What problem does this feature solve?

This feature relates to apps using `mode: 'universal'`.

Allows for a single build artifact to be used in multiple environments with or without a CDN. 

In fact this used to be possible in Nuxt 2.3 using the following config:

```
  hooks: {
    //Nuxt doesn't allow the publicPath (CDN url) to be overridden at run time - it's baked into the manifest at build time.
    //This hook intercepts the VueRenderer when it has loaded the manifest and updates the publicPath to the current env value.
    render: {
      resourcesLoaded(resources) {
        resources.clientManifest && (resources.clientManifest.publicPath = process.env.PUBLIC_PATH || '/_nuxt/');
      }
    }
  },
```

However this change (https://github.com/nuxt/nuxt.js/commit/0f104aa58890f7b06837a05fc67718bf7822264a#diff-015dff3d45b52153ef5f24ef104e954bL161) in Nuxt 2.4 breaks this as the hook is now called _after_ the the renderer is created.

If anyone knows of a workaround that doesn't require editing the manifest file on disk at run time please let me know.

### What does the proposed changes look like?

`$ CDN_BASE_URL=https://cdn.com/_nuxt/ npm run start`

```
// nuxt.config.js
module.exports = {
  build: {
    publicPath: process.env.CDN_BASE_URL
  }
}
```

This should cause server-rendered script tags to use the URL specified by `CDN_BASE_URL`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9388">#c9388</a>)</em></sub></div>

**Comment by kams2160** [comment]
Hi, I have problem with setting publicPath in build object in my nuxt.config.js at runtime:
```
build: {
    publicPath: process.env.PUBLIC_URL || '/_nuxt/',
}
```
I have to deploy one app to many environments with different publicPath addresses to static files. 
Any ideas? :slight_smile:
It looks like the publicPath is assign at build time and then at runtime the env variable wont be used
I also tried with nuxt-env, but it doesn't help.
Is any different way in nuxt.js to set static files url at runtime?
My nuxt version is 2.10.2.
Thanks :)

**Comment by edwh** [comment]
I came across this useful thread when looking into how to use a CDN.  Thanks.

The resourcesLoaded suggestion from @timmw now works again, presumably because of the commit from @pi0 .

However I only see that get used on the resources which are loaded immediately when I first load the page, i.e. the ones returned from the server during a SSR.  

When later scripts are loaded by the client, that resourcesLoaded hook doesn't seem to get executed.  Does anyone have any ideas?

**Comment by edwh** [comment]
In case anyone else comes across this, I got the client side working using a plugin and __webpack_public_path__ .  

If you set __webpack_public_path__ on the client side, then that will work to pull in dynamic chunks from a CDN.
