### ISSUE TITLE
res.setHeader with multiple value doesn't work with `nuxt dev`, works with `nuxt start`

### ISSUE THREAD

**Issue by duyleekun** [nuxt/nuxt.js#5963]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/duyleekun/NuxtSetHeaderBug](https://github.com/duyleekun/NuxtSetHeaderBug)

## Doesn't work with `yarn dev`

```bash
yarn
yarn dev

# In another terminal
curl http://localhost:3000/ -v
```

## Works with `production`

```bash
yarn
yarn build
yarn start

# In another terminal
curl http://localhost:3000/ -v
```

### What is expected ?

*curl output*

```
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Set-Cookie: a=1
< Set-Cookie: b=2
< ETag: "1289-0kNbl543adKfb4MZdMamsyahsJA"
< Content-Type: text/html; charset=utf-8
< Accept-Ranges: none
< Content-Length: 4745
< Vary: Accept-Encoding
< Date: Fri, 21 Jun 2019 10:44:23 GMT
< Connection: keep-alive
```

### What is actually happening?

*curl output*
 
```
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Set-Cookie: a=1,b=2
< ETag: "19a9-gCeBF1YAwiPDyaIPa5orvZylcVc"
< Content-Type: text/html; charset=utf-8
< Accept-Ranges: none
< Content-Length: 6569
< Date: Fri, 21 Jun 2019 10:41:01 GMT
< Connection: keep-alive
< 
```

### Additional comments?

Note the `Set-Cookie` above.

Node version: v8.16.0
It also broke in my other 2.7 project

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9392">#c9392</a>)</em></sub></div>

**Comment by duyleekun** [comment]
```
const http = require('http')
const server = http.createServer((req, res) => { 
  res.setHeader('Set-Cookie', ['hest2=spam','pony2=spam','a3=4']);
  console.log(res)
  res.end() 
}).listen(8000)
```

This one also works fine with my node version

**Comment by pzhyy** [comment]
I have the same problem, is there any solution?

**Comment by rchl** [comment]
It works fine here using `yarn dev` but I'm running on Node v10.15.3. Are you able to test with Node 10 or 12?

**Comment by rchl** [comment]
Actually I've tested with Node `8.16.0` and I can reproduce there. I wouldn't definitively say that it's not a Nuxt bug still, but if it works in stable Node version (10) then it's probably not a priority to look into.
