### ISSUE TITLE
Implement Logger - Request

### ISSUE THREAD

**Issue by frbuceta** [nuxt/nuxt.js#5965]
Hi, how about everyone?

I wanted to propose a feature, which would be the possibility of implementing a logger such as bunyan, Google error reporting, Google StackDrive, Winston ...

I've looked for ways to do it but I can not find any

Thanks in advance

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9393">#c9393</a>)</em></sub></div>

**Comment by frbuceta** [comment]
@pi0

**Comment by pi0** [comment]
Hi @frbuceta. You can add a custom [consola](https://github.com/nuxt/consola) reporter. All nuxt logs are passed through consola. Please make an issue in that repo if you needed help for implementing a custom logger.

PS: For logging HTTP requests you need to register a [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware/) to catch `req` and logging.

**Comment by manniL** [comment]
(example of a SSR-logger can be found @ https://twitter.com/TheAlexLichter/status/1055737087306199040 )
