### ISSUE TITLE
Nuxt + Vuetify production mode loading css late

### ISSUE THREAD

**Issue by amritk** [nuxt/nuxt.js#5966]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/amritk/vuetify-nuxt-repro](https://github.com/amritk/vuetify-nuxt-repro)

### Steps to reproduce

Grab the repo, build and run in production mode. Make sure to have the network tab open to disable cache. You can see as you refresh that some vuetify styles load late and the elements change.

### What is expected ?

There should be no jump in style as they should be loaded already from nuxt SSR.

### What is actually happening?

The styles seem to be loaded via javascript so you can see the elements jump.

### Additional comments?

I have also tested this with the latest vuetify 2 beta, the problem still occurs. As I wasn't sure if this was a vuetify or nuxt bug I did post it [there](https://github.com/vuetifyjs/nuxt/issues/90) as well.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9394">#c9394</a>)</em></sub></div>

**Comment by amritk** [comment]
![59383094-13a5b500-8d14-11e9-84bc-d27bb0336da9.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/9c38fd80-943c-11e9-8e07-95c85b337374.gif)
 Here is a gif of what happens on my app I'm trying to take to production.

**Comment by amritk** [comment]
As you can see here, there are a few style blocks that are added on the client but are not there on the server. How do I ensure these styles are loaded on the server?

Server:
![2019-06-25:14:52:13](https://user-images.githubusercontent.com/2039539/60136792-0946da80-975a-11e9-9fc8-403b0811eaf8.png)

Client:
![2019-06-25:14:52:28](https://user-images.githubusercontent.com/2039539/60136798-0e0b8e80-975a-11e9-8367-4f1a659c8f00.png)

**Comment by edmundpf** [comment]
I've found a lot of CSS packages only work with nuxt in 'spa' mode that you can edit in the nuxt config, if you can isolate the components in question you can also wrap them in the <no-ssr></no-ssr> tag. This was the case with bootstrap among others

**Comment by amritk** [comment]
hey @edmundpf thats good for when a component is breaking on the server side. My problem however is the opposite: styles are missing server side that should be there. I'm not sure how to configure nuxt to show these styles.

**Comment by amritk** [comment]
Alright its the v-layout styles loading late. Any way I can pre-load them somehow?

**Comment by amritk** [comment]
Closing as this is a vuetify issue
