### ISSUE TITLE
Error: head script dangerouslyDisableSanitizers 

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#597]
Hello

I need insert google tag manager

on my **nuxt.config.js**
```
head: {
  script: [
    //googletagmanager
    { innerHTML: "some script" },
  ],
  __dangerouslyDisableSanitizers: ['script']
}
```

when i change page (this.$router.push())

I have error Exeption

<img width="936" alt="2017-04-21 16 08 19" src="https://cloud.githubusercontent.com/assets/3066246/25278691/d5512b2e-26ac-11e7-8fdc-a6bfedecb452.png">

<img width="527" alt="2017-04-21 16 08 38" src="https://cloud.githubusercontent.com/assets/3066246/25278707/e3bc8118-26ac-11e7-9e42-e545b8966b22.png">

Do you can to help me?

**Comment by Atinux** [comment]
Please report this issue directly to vue-meta repository.

**Comment by juliojerrick** [comment]
I saw this was fixed but I'm still getting the console error. Is vue-meta updated to the latest version in nuxt?
