### ISSUE TITLE
nuxt-child with nuxt-link in child page with relative link

### ISSUE THREAD

**Issue by bluelovers** [nuxt/nuxt.js#5970]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-lg9m4?fontsize=10](https://codesandbox.io/s/codesandbox-nuxt-lg9m4?fontsize=10)

### Steps to reproduce

parent
```
<template>

	<div>

		<ul>
			<li><nuxt-link to="./parent/child">child</nuxt-link></li>
		</ul>

		<nuxt-child />

	</div>

</template>
```

parent/child
```
<template>
	<div>
		<h1>child</h1>
	</div>
</template>
```

when we view `parent/child`

and click link, router will go `parent/parent/child`

then will get a 404

### What is expected ?

auto fix relative link in child

### What is actually happening?

link in chile will go to `parent/parent/child` then get 404

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9398">#c9398</a>)</em></sub></div>

**Comment by pimlie** [comment]
Could you please verify this doesnt happen when you use router-link instead of nuxt-link?

**Comment by PadamSethia** [comment]
Any fixes to this ?
Still getting this error randomly.
