### ISSUE TITLE
_loading/ws error with custom url

### ISSUE THREAD

**Issue by bdrtsky** [nuxt/nuxt.js#5971]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://google.com](https://google.com)

### Steps to reproduce

I use custom local URL in hosts and then nginx. 
![Screenshot from 2019-06-22 15-16-33.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/f8a54e10-94e7-11e9-94c1-37feeddafa23.png)

### What is expected ?

I expect no errors in console.

### What is actually happening?

Errors in console. Previously there where no errors, I assume they related to new loading screen?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9399">#c9399</a>)</em></sub></div>

**Comment by angleneo** [comment]
![image](https://user-images.githubusercontent.com/20380882/67255852-bdf9ca00-f4b6-11e9-9b44-6d01b8c54f1b.png)
the same problem
