### ISSUE TITLE
"Uncaught ReferenceError: window is not defined" using client-side only plugin

### ISSUE THREAD

**Issue by EmmanuelJego** [nuxt/nuxt.js#5972]
Hi!

I first started a project with Vue.js, then I discovered Nuxt.js which seems very nice, so I started to recreate my project with Nuxt.
So I wanted to import the plugins I used in my Vue.js project (especially ['vue-pdf'](https://www.npmjs.com/package/vue-pdf)).

If, in my vue, I try to import it like var `pdfVue = require('vue-pdf')` I got a "Unexpected token <" error. This seems rigth since vue-pdf is a pdf player, so a client-side only component.

I tried to import it as a plugin like so (as it is written in the doc at https://nuxtjs.org/guide/plugins#client-side-only): 

- vue-pdf.js: 
```
import Vue from 'vue'
import VuePdf from 'vue-pdf'

Vue.use(VuePdf)
```

- nuxt.config.js:
```
…
plugins: [
   {src: '~/plugins/vue-pdf.js', ssr: false}
],
build: {
   vendor: [
      'vue-pdf'
   ]
}
…
```

With that, I have a "Uncaught ReferenceError: window is not defined" error.
I also tried `{src: '~/plugins/vue-pdf.js', mode: 'client'}` but that doesn't change anything.

I don't even try to use/import the component in any vue.
I tried it in a brand new project to start from 0, but as soon as I create the plugin, I have the error.

Am I doing something wrong? Or is the plugin not working with Nuxt? 
I'm pretty confused there.

Thanks for your help!

**Comment by zardilior** [comment]
You need to either add .client.js to your filename or { mode: 'client' } in your plugin import as the window is defined only on the browser and thats a client side component! Hope it helped

**Comment by zardilior** [comment]
Check out this working solution https://github.com/FranckFreiburger/vue-pdf/issues/148

**Comment by EmmanuelJego** [comment]
@zardilior This is actually my solution to this particular issue 😂 I shared it in that Github issue after finding the solution.
Thanks for linking the solution btw, I forgot to do it 🙂

**Comment by zardilior** [comment]
lol :P how dumb, anyway leaving it for others who end up here

**Comment by zardilior** [comment]
@EmmanuelJego by any chance you didn't had issues with resizing of the viewport too?

**Comment by EmmanuelJego** [comment]
@zardilior Nop, sorry. What is your issue ?

**Comment by zardilior** [comment]
I figured I has the same component in two v-if therefore it rerendered it, solved it though it was the resizing
