### ISSUE TITLE
Be able to change webpack plugins order and params.

### ISSUE THREAD

**Issue by Miaoxingren** [nuxt/nuxt.js#5974]
### What problem does this feature solve?

I want to inline all css in generated HTML with [html-webpack-inline-source-plugin](https://www.npmjs.com/package/html-webpack-inline-source-plugin), but I can't add `inlineSource: '.(js|css)$'` to `html-webpack-plugin` and place `html-webpack-inline-source-plugin` after `html-webpack-plugin`.

### What does the proposed changes look like?

```
build: {
  plugins: [
    { plugin: new HtmlWebpackInlineSourcePlugin(), enfore: 'post' }
  ],
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9402">#c9402</a>)</em></sub></div>

**Comment by pimlie** [comment]
Have you tried using [`build.extend`](https://nuxtjs.org/api/configuration-build/#extend) in your nuxt.config to do this?
