### ISSUE TITLE
Save the random ports choiced

### ISSUE THREAD

**Issue by MattixNow** [nuxt/nuxt.js#5980]
### What problem does this feature solve?

Hey when the ports 3000 is already in use nuxt use a random ports, but when files are changed the port changed from the build process. When developer debug a site, it 's frustrating to change the current URL

### What does the proposed changes look like?

Save in memory the randomized port

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9408">#c9408</a>)</em></sub></div>

**Comment by pi0** [comment]
Latest version has this. Please upgrade nuxt:)

**Comment by MattixNow** [comment]
Oh sorry.. Thanks for the support 😃

*The development of NuxtJs is super-fast, thank you !*
