### ISSUE TITLE
Nuxt.js is initializing the routes before the store

### ISSUE THREAD

**Issue by tonimota** [nuxt/nuxt.js#5981]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-we77x?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-we77x?fontsize=14)

### Steps to reproduce

Create the new project with create-nuxt-app
Add nuxtjs/router
Create file ~/router.js 
```
import Vue from "vue";
import Router from "vue-router";

import Home from "@/pages/index";
import About from "@/pages/about";

Vue.use(Router);

export function createRouter() {
  const router = new Router({
    mode: "history",
    routes: [
      {
        name: "index",
        path: "/",
        component: Home
      },
      {
        name: "about",
        path: "/about",
        component: About
      }
    ]
  });
  router.beforeEach((to, from, next) => {
    console.log(this.$store);
    next();
  });
  return router;
}
```

Create directory user and file state.js inside user
```
export default () => ({
  count: 0,
  auth: false,
  keycloakInital: false,
  user: {}
});
```

Using beforeEach
Add console.log(this.$store)

### What is expected ?

Accessing user object.

### What is actually happening?

Cannot read property '$store' of undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9409">#c9409</a>)</em></sub></div>

**Comment by pimlie** [comment]
Thanks for the report. This seems to be already discussed in #5405, will close this issue in favor of that issue
