### ISSUE TITLE
Nuxt API missing types

### ISSUE THREAD

**Issue by mtltechtemp** [nuxt/nuxt.js#5985]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://pastebin.com/KLTYmBTS](https://pastebin.com/KLTYmBTS)

### Steps to reproduce

1.) `import { Nuxt, Builder } form 'nuxt';`
That's it.

### What is expected ?

Been able to import `Nuxt`, `Builder` and its definitions.

### What is actually happening?

The module w/ types is not found.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9412">#c9412</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
Duplicated of https://github.com/nuxt/nuxt.js/issues/4998
