### ISSUE TITLE
Nuxt 2.8.1 not woking with IE 11, couldnt transpile vue files

### ISSUE THREAD

**Issue by heanfig** [nuxt/nuxt.js#5993]
### Version
v2.8.1

### Description

When I try to open nuxt in Internet Explorer, the following error appears:
[![N|Solid](https://i.imgur.com/gHvCzsd.png)](https://i.imgur.com/gHvCzsd.png)

The problem that I currently have is a syntax error corresponding to es6, currently it is not transpiling to es5 but to version 1 if it was
[![N|Solid](https://i.imgur.com/o4Xj93m.png)](https://i.imgur.com/o4Xj93m.png)

I have tried several ways, but in no way is it applied correctly (property of transpile, compilation of babel) in the nuxt.config.js, presets

The error seems to be present from version 2 onwards.

### Steps to reproduce
Visit https://localhost:3000 on IE 11

### What is actually happening?
Syntax error con IE (*in nuxt indicator*)

**Comment by cliffordh** [comment]
@heanfig did you figure this out? I'm having similar problems with IE.

**Comment by Lucassifoni** [comment]
@cliffordh , did you manage to fix this ?
Thanks.

**Comment by cliffordh** [comment]
I posted the solution that worked for me to StackOverflow: https://stackoverflow.com/questions/52452501/how-to-add-a-polyfill-to-nuxt-2-0/57538219#57538219

You may need to adjust the polyfills for your specific scenario, and I'm aware that this code causes the bundle to include all of my polyfills, but I'd rather depend on my own hosting than a third party like polyfills.io.

**Comment by cliffordh** [comment]
@Lucassifoni Note also that I got rid of all the "magic" ideas that were floating around on this topic. Here is my build configuration in nuxt.config.js:

  build: {
    transpile: ['vuex-persist']
  },

That's it...

**Comment by Lucassifoni** [comment]
Hey, thanks for your quick answers. I managed to locate my problem better, it seems that the build configuration won't compile my dependencies even if my application code is compiled to es5, hence the crashes under IE at the first arrow function in the vendors bundle. I'll investigate !

**Comment by jainsuneet** [comment]
> ### Version
> v2.8.1
> 
> ### Description
> When I try to open nuxt in Internet Explorer, the following error appears: [![N|Solid](https://camo.githubusercontent.com/fac62c44e26247b12339b9e0a183ede4bc057dd67a8cd419f52497d7bfac8bbb/68747470733a2f2f692e696d6775722e636f6d2f674876437a73642e706e67)](https://i.imgur.com/gHvCzsd.png)
> 
> The problem that I currently have is a syntax error corresponding to es6, currently it is not transpiling to es5 but to version 1 if it was [![N|Solid](https://camo.githubusercontent.com/d58e0b62248997b941a80a9d8e600536ac58b2fd4b59e20b3ac324335151ba88/68747470733a2f2f692e696d6775722e636f6d2f6f34586a39336d2e706e67)](https://i.imgur.com/o4Xj93m.png)
> 
> I have tried several ways, but in no way is it applied correctly (property of transpile, compilation of babel) in the nuxt.config.js, presets
> 
> The error seems to be present from version 2 onwards.
> 
> ### Steps to reproduce
> Visit https://localhost:3000 on IE 11
> 
> ### What is actually happening?
> Syntax error con IE (_in nuxt indicator_)
> 
> _This question is available on [Nuxt](https://cmty.app/nuxt) community ([#c9422](https://cmty.app/nuxt/nuxt.js/issues/c9422))_

Did you find any solution for this? I am also facing the same issue.
