### ISSUE TITLE
latest version of nuxt-edge breaks webpack build (css-loader issue)

### ISSUE THREAD

**Issue by Cl3MM** [nuxt/nuxt.js#5995]
### Latest `nuxt-edge` version breaks webpack build process with a css-loader related issue

This morning, after deploying a fresh docker instance, my production server went south after running the `yarn build` command.

I tracked it down to being an issue with the latest nuxt-edge version (build 2.9.0-26026572.fc5502cd). The bug was introduced somewhere between `v2.9.0-26025132.de526f6d
` and `v2.9.0-26026572.fc5502cd`)

Switching back to `nuxt-edge@2.9.0-26025132.de526f6d` temporaly fix the issue.

It somehow related to a package depending on `css-loader@3.0.0` .
css-loader [introduced breaking changes](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes) in its 3.0 version.

```
FATAL  Nuxt Build Error
ValidationError: CSS Loader Invalid Options
options should NOT have additional properties
```

I made a [very simple repository](https://github.com/Cl3MM/nuxt-css-loader-failure.git) to reproduce the bug:

Clone the repo:
```
git clone https://github.com/Cl3MM/nuxt-css-loader-failure.git
cd nuxt-css-loader-failure
```
Switch to the nuxt-edge branch:
```
git checkout nuxt-edge-2.9.0-26026572.fc5502cd
```
Install packages:
```
yarn
```
Run the build command
```
yarn build
```

Enjoy the errors message XD

```
ERROR in ./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-1!./node_modules/@nuxt/webpack-edge/node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--9-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true&)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/dev/nuxt-css-loader-failure/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/dev/nuxt-css-loader-failure/node_modules/css-loader/dist/index.js:44:28)
 @ ./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true& (./node_modules/vue-style-loader??ref--9-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-1!./node_modules/@nuxt/webpack-edge/node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--9-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true&) 4:14-425
 @ ./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

I originaly though this was caused by the fact I was using SASS, but I also made a version without SASS and the bug persists. You can check out the non SASS version by switching to the following branch:

```
git checkout nuxt-edge-2.9.0-26026572.fc5502cd-no-sass
```

I also made a branch with the latest working version:

```
git checkout nuxt-edge-2.9.0-26023690.de526f6d
```

I'm not very familiar with debuging webpack config issues, so I just though I'd made a repo to reproduce the bug and open an issue here.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9425">#c9425</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks, @Cl3MM for the report. I'll investigate that. 

PS: Please use CMTY to avoid issue auto-close :)

**Comment by manniL** [comment]
Closing in favor of #5996
