### ISSUE TITLE
Nuxt JS 2.8.1 won't work in Internet Explorer 11 (IE11)

### ISSUE THREAD

**Issue by tanhernandez** [nuxt/nuxt.js#5999]
https://cmty.app/nuxt/nuxt.js/issues/c9423

**Comment by Ti-webdev** [comment]
I've created bare nuxt app with store and got the same issue with ie11.

**Comment by tanhernandez** [comment]
@Ti-webdev There is another discussion in here for people who has problems running nuxt in IE 11
https://github.com/nuxt/nuxt.js/issues/4432

I've put my solution in there to get it running and seems that Nuxt has a bug for IE 11 when running dev.

**Comment by clarkdo** [comment]
@tanhernandez Could you verify on nuxt-edge ? If issue is still happening, please provide a reproducible repo, thanks.
