### ISSUE TITLE
Development server crashes if `nuxt.config.js` becomes invalid

### ISSUE THREAD

**Issue by soutokevin** [nuxt/nuxt.js#60]
If the configuration file change during the execution of the development server, it automatically aplies the new configuration, but if the file becomes invalid (a missing comma or semicolon, we all do that sometimes!) the server crashes, needing to be restarted (after fixing the file).

When running a development server, I don't expect it to crash for any reason, no matter what happens the server should only display an error message and wait until things go back normal.

**Comment by Atinux** [comment]
Thank you @soutokevin 

It will be fixed in the new release.

**Comment by Atinux** [comment]
Fixed in [`0.9.0`](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.0) 🔥
