### ISSUE TITLE
Loading external scripts using head property inside component doesn't load the script if server side rendered

### ISSUE THREAD

**Issue by arihantdaga** [nuxt/nuxt.js#6005]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://jsfiddle.net/wbr3gunq/1/](https://jsfiddle.net/wbr3gunq/1/)

### Steps to reproduce

Add external scripts in head() method of the component. 
Come to this page buy navigating from another page using nuxt-link. This will load the scripts. But if you hit Ctrl+R or reload the page, the scripts are not loaded. 

### What is expected ?

It should load external scripts when rendered server side or client side.  

### What is actually happening?

The external script tags are not loaded when page is rendered server side. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9433">#c9433</a>)</em></sub></div>

**Comment by pimlie** [comment]
Could you please create a working reproduction of this issue on codesandbox that we can check?

**Comment by arihantdaga** [comment]
Yes sure. I'll create one and update.

**Comment by TrueCarry** [comment]
Offtopic, but you probably don't want to include scripts in head. You can add them to body inside no-ssr tag.

**Comment by arihantdaga** [comment]
@pimlie https://codesandbox.io/s/codesandbox-nuxt-rg5zj?fontsize=14. 
In this example, i am trying to load an external javascript. So i kept it in the head() method of the component. But it is not loaded when rendered server side, and  loaded only when rendered client side. (i.e - go to about page and then come back to home page). 

@TrueCarry  Thanks, I'll try that also. And i'll have to do the same for external css too i guess.

**Comment by pimlie** [comment]
Do I understand correctly you expect that `temporary.js` would also be loaded when you navigate to `/about`? If you need that then you should put head with temporary.js in the layout, not in de page component of index.

**Comment by arihantdaga** [comment]
@pimlie No. I meant that temporary.js should be loaded in the index page. Not about page. But its not loading in the index page also if you reload the page and if the page is rendered from server side. It is loaded only if the page is rendered client side (i.e - go to any other page and come back on index page using navigation via nuxt-link, then it'll load temporary.js).

**Comment by pimlie** [comment]
Sorry, when I directly load the index of your repro it also loads temporary correctly:

![image](https://user-images.githubusercontent.com/1067403/60799677-dcd88880-a173-11e9-8e7d-afac4e9c350c.png)

**Comment by arihantdaga** [comment]
And explain to you. I checked it again. Its NOT loading. I'll post a screen recording video. Can you also please guide me where to look for the code of nuxtJs related to loading these scripts.
