### ISSUE TITLE
renderAndGetWindow times out when testing with Ava and TypeScript

### ISSUE THREAD

**Issue by JakubKoralewski** [nuxt/nuxt.js#6008]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/JakubKoralewski/mireks/tree/5f609e843a21b1130ef8e8e9770015c8538d4c65](https://github.com/JakubKoralewski/mireks/tree/5f609e843a21b1130ef8e8e9770015c8538d4c65)

### Steps to reproduce

1. Run `npm run test`.
  - first tests should pass
  - when it gets to the second test ("Route / exists and renders HTML with CSS applied") it throws this Error:
```typescript
test("Route / exists and renders HTML with CSS applied", async t => {
	console.log("Rendering window");
	// console.log("nuxt.server: ", nuxt.server);
	const window: Window = await nuxt.server.renderAndGetWindow(url("/"));
//(...)
});
```

### What is expected ?

Maybe allow the user to change the timeout, since it is hardcoded as a default parameter even though it is not used anywhere.

Plus I'd like to actually be able to do some tests.

### What is actually happening?

```
× test » index.ts » Route / exists and renders HTML with CSS applied Rejected promise returned by test

  1 test failed

  test » index.ts » Route / exists and renders HTML with CSS applied

  F:\projects\web\mireks\mireks_next\src\node_modules\@nuxt\utils\dist\utils.js:1849

  Rejected promise returned by test. Reason:

  Error {
    message: 'Components loading in renderAndGetWindow was not completed in 2s',
  }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

### Additional comments?

Here's the `before test` part:

```typescript
test.before("Init Nuxt.js", async t => {
	const rootDir = resolve(__dirname, "..");
	let config: NuxtConfiguration = {};
	config = require(resolve(rootDir, "nuxt.config.ts")).default;
	config.rootDir = rootDir; // project folder
	config.dev = true; // production build
	config._typescript = { build: true };
	nuxt = new Nuxt(config);
	await new Builder(nuxt).build();
	await nuxt.server.listen(4000, "localhost");
});
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9435">#c9435</a>)</em></sub></div>

**Comment by pimlie** [comment]
You can already change the loadingTimeout, [3rd arg of renderAndGetWindow](https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/jsdom.js#L9) is an obj with some nuxt specific configuration

Please check and see if that fixes your issue

**Comment by JakubKoralewski** [comment]
@pimlie By my understanding the actual exposed API is here: https://github.com/nuxt/nuxt.js/blob/32f9df76f39c93f7cdc36502f1ce194e9aaf429d/packages/server/src/server.js#L218

And if you look closely you can see that the exposed API in `server.js` only takes two arguments and the third one in `jsdom.js` actually hardcoded.

I tried setting the third argument anyway like this: `await nuxt.server.renderAndGetWindow(url("/"), undefined, {loadingTimeout: 10000});`, but I got this: 

```
Error {
    message: 'Components loading in renderAndGetWindow was not completed in 2s',
  }
```

which originates here: https://github.com/nuxt/nuxt.js/blob/32f9df76f39c93f7cdc36502f1ce194e9aaf429d/packages/server/src/jsdom.js#L66

Meaning the `loadingTimeout` was not changed from the default :/

**Comment by pimlie** [comment]
@JakubKoralewski Sorry for the late response.  What happens when you add 
```
  globals: {
    loadingTimeout: XXX
  }
```
to your nuxt.config? That should work I think.
