### ISSUE TITLE
Reverse proxy in apache does not work in Nuxt.js

### ISSUE THREAD

**Issue by viniciussvl** [nuxt/nuxt.js#6010]
I'm trying to run Nuxt.js in production on my **Apache server** and I'm not getting it. I created the sites-available and site-enabled folders, I added the site.domain.com.conf file with a virtualhost in my domain site.domain.com to do reverse proxy in a Nuxt node.js application, which is running successfully on l**ocalhost:3000**. I made the following configuration:

```
<VirtualHost *:80>
    ServerName site.domain.com
    ServerAlias www.site.domain.com

    DocumentRoot /var/www/html
    ErrorLog /home/user01/site.domain.com/error.log
    CustomLog /home/user01/site.domain.com/access.log combined

    ProxyRequests off
    <Proxy *>
     Require all granted
    </Proxy>

    ProxyPreserveHost on
    ProxyPass / http://localhost:3000/ retry=1 acquire=3000 timeout=3000 keepalive=off
    ProxyPassReverse / http://localhost:3000/
    ProxyTimeout 3000
    ProxyVia full
</VirtualHost>
```
I also added the following line in the httpd.conf file

`IncludeOptional sites-enabled/*.conf`

And after restarting apache it created the requests.log and access.log files in the folder I configured in the ErrorLog and CustomLog parameters, so the configuration was read by apache.

When accessing the domain site.domain.com it does not point the requests to localhost: 3000, it just displays the directory files in the browser, what am I doing wrong?

Server settings:

- CentOS 6.9
- Apache 2.4.39
- Enabled modules: proxy_module, proxy_http_module, lbmethod_byrequests_module, proxy_balancer_module

This is the result of the **apachectl -S** command:

```
port 80 namevhost site.domain.com (/etc/apache2/conf/httpd.conf:761)
                 alias www.site.domain.com

port 443 namevhost site.domain.com (/etc/apache2/conf/httpd.conf:1881)
                     alias www.site.domain.com

*:80                   site.domain.com (/etc/apache2/sites-enabled/site.domain.com.conf:1)
```
Notice that my virtual host configuration was added to the end, but still shows two other default settings, is it normal?

**Comment by irvv17** [comment]
have you resolved this problem? @viniciussvl

**Comment by a-zog** [comment]
Hi @viniciussvl I'm having a similar issue and I was wondering how you solved yours

**Comment by isat7** [comment]
i think
skip this line    DocumentRoot /var/www/html
 while using proxy
<VirtualHost *:80>
    ServerName site.domain.com
    ServerAlias www.site.domain.com

    ErrorLog /home/user01/site.domain.com/error.log
    CustomLog /home/user01/site.domain.com/access.log combined

    ProxyRequests off
    <Proxy *>
     Require all granted
    </Proxy>

    ProxyPreserveHost on
    ProxyPass / http://localhost:3000/ retry=1 acquire=3000 timeout=3000 keepalive=off
    ProxyPassReverse / http://localhost:3000/
    ProxyTimeout 3000
    ProxyVia full
</VirtualHost>

**Comment by MathieuB1** [comment]
My settings to get it work with docker:

    # NuxtJS Conf
    ProxyPass /_nuxt http://localhost:3000/_nuxt
    ProxyPassReverse /_nuxt http://localhost:3000/_nuxt

    # NuxtJS for Hot Reload in Dev (Websockets)
    ProxyPass /__webpack_hmr/client http://localhost:3000/__webpack_hmr/client
    ProxyPass /_loading/sse http://localhost:3000/_loading/sse

**Comment by qtwf** [comment]
for hot updates + custom ssl:
```conf
<VirtualHost *:443>

    ServerName your.nuxtapp.com
    
    RewriteEngine On
    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /(.*) ws://127.0.0.1:5173/$1  [P,L]

    ProxyPass / http://127.0.0.1:5173/
    ProxyPassReverse / http://127.0.0.1:5173/

    SSLEngine on
    SSLCertificateFile      /etc/ssl/laragon.crt
    SSLCertificateKeyFile   /etc/ssl/laragon.key
 
</VirtualHost>
```
