### ISSUE TITLE
firebase-tools 7.x  cannot correctly handle nuxt.render middleware with its function emulator

### ISSUE THREAD

**Issue by umegaya** [nuxt/nuxt.js#6014]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/umegaya/nuxt-firebase-ssr](https://github.com/umegaya/nuxt-firebase-ssr)

##### install latest (at 2019/7/2) firebase-tools
$ npm install -g firebase-tools@7.0.2

##### clone reproduction link
$ git clone https://github.com/umegaya/nuxt-firebase-ssr.git

##### enter repo
$ cd nuxt-firebase-ssr

##### attach your firebase project with it 
$ firebase use --add 

##### install dependency via npm
$ npm i && npm --prefix functions i 

##### build nuxt 
$ npm run build

##### serve with bundled firebase cli (version should be 6.8.0)
$ npx firebase serve

##### call served functions, please replace $project_name and $region with your firebase  project name and region
$ curl -v http://localhost:5001/$project_name/$region/ssr
$ curl -v http://localhost:5001/$project_name/$region/helloWorld

##### serve with global firebase cli
$ firebase serve

##### call served functions, please replace $project_name and $region with your firebase  project name and region
$ curl -v http://localhost:5001/$project_name/$region/ssr
$ curl -v http://localhost:5001/$project_name/$region/helloWorld

### What is expected ?

for both firebase cli version, all of below commands should get response with status 200

$ curl -v http://localhost:5001/$project_name/$region/ssr
$ curl -v http://localhost:5001/$project_name/$region/helloWorld

### What is actually happening?

for bundled firebase cli (6.8.0), all of commands get response with status 200, but global firebase cli (7.0.2) gets 200 for curl -v http://localhost:5001/$project_name/$region/helloWorld, __404__ for curl -v http://localhost:5001/$project_name/$region/ssr

because helloWorld can return 200 for both version, it does not seem to the bug of firebase cli itself. 

### Additional comments?

latest version of firebase cli 6.x is 6.13.0 but here I use 6.8.0 to avoid another problem for firebase serve command https://github.com/firebase/firebase-tools/issues/1337 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9441">#c9441</a>)</em></sub></div>

**Comment by okamuuu** [comment]
I was in a similar situation and I resolved by using `nuxt.ready()` like the following:

```js
app.use(async (req, res) => {
  await nuxt.ready()
  nuxt.render(req, res)
})
```
