### ISSUE TITLE
TS2339: Property '$vuetify' does not exist on type 'default'

### ISSUE THREAD

**Issue by Mikkou** [nuxt/nuxt.js#6015]
when i use this.$vuetify.goTo()

i use ts

**Comment by TAnas0** [comment]
I am having the same issue with this [Sentry Nuxt plugin](https://github.com/nuxt-community/sentry-module)

```bash
54:12 Property '$sentry' does not exist on type '{ triggerError(): void; }'.
    52 |   methods: {
    53 |     triggerError () {
  > 54 |       this.$sentry.captureException(new Error('Manually triggered exception'))
       |            ^
    55 |     }
    56 |   }
    57 | }
```

How do I let TS know about such top level variables? Is this the relevant [Nuxt Typescript documentation](https://typescript.nuxtjs.org/cookbook/plugins.html#i-inject-into-vue-instances)? If so, where does the TS definitions go?

**Comment by all-lala** [comment]
I have to add this and it's work for me:
```
import { Framework } from 'vuetify'

declare module 'vue/types/vue' {
  // this.$vuetify inside Vue components
  interface Vue {
    $vuetify: Framework
  }
}
```

**Comment by xetra11** [comment]
> import { Framework } from 'vuetify'
> 
> declare module 'vue/types/vue' {
>   // this.$vuetify inside Vue components
>   interface Vue {
>     $vuetify: Framework
>   }
> }

added where?

**Comment by all-lala** [comment]
> > import { Framework } from 'vuetify'
> > declare module 'vue/types/vue' {
> > // this.$vuetify inside Vue components
> > interface Vue {
> > $vuetify: Framework
> > }
> > }
> 
> added where?

in nuxt.config.js
```
  // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [
    { src: '~/plugins/vuetify.ts' }
  ],
```

in plugins/vuetify.ts
```
import { Framework } from 'vuetify'

declare module 'vue/types/vue' {
  interface Vue {
    $vuetify: Framework
  }
}
```

**Comment by rukshn** [comment]
Add `vuetify ` to your `tsconfig.json` file like this 

    "types": [
      "@nuxt/types",
      "@types/node",
      "@nuxtjs/auth-next",
      "vuetify"
    ]

**Comment by JuanCarlosRC** [comment]
> Add `vuetify ` to your `tsconfig.json` file like this
> 
> ```
> "types": [
>   "@nuxt/types",
>   "@types/node",
>   "@nuxtjs/auth-next",
>   "vuetify"
> ]
> ```

![image](https://user-images.githubusercontent.com/67658540/112525042-7abc1e80-8d6e-11eb-8380-af8141caa08b.png)
I did that, still no luck

**Comment by rukshn** [comment]
@JuanCarlosRC Have you tried changing **vuetify** to **$vuetify** and see? That might work.

**Comment by joy91227** [comment]
@JuanCarlosRC 
try declaring types as:
`    "types": [
      "@nuxt/types",
      "@types/node",
      "@nuxtjs/auth-next",
      "@nuxtjs/vuetify",
    ],
`
replacing 'vuetify' with '@nuxtjs/vuetify', or whichever alternative vuetify module for nuxtJS that's installed
---
My understanding of the error is that Typescript is not compiling @nuxtjs/vuetify's type package, either because @nuxtjs/vuetify is not saved in a default folder under node_modules, or because "types" was specified and thus only packages in "types" will be compiled. (ref: https://www.typescriptlang.org/tsconfig#types)

**Comment by Eboubaker** [comment]
All previous attempts did not works. what worked is this

```typescript
// src/shims-vue.ts
import Vue from 'vue'
import {Framework} from "vuetify";
import VueRouter from "vue-router";

interface PluginTypes extends Vue{
  $vuetify: Framework
  $router: VueRouter
}

declare module '*/**.vue' {
  type Vue = PluginTypes
}
declare module '*/**.Vue' {
  type Vue = PluginTypes
}
declare module 'vue/types/vue' {
  type Vue = PluginTypes
}
```

Don't forget to include "vuetify" in tsconfig.json, can omit nuxtjs if not using
```json
"types": [
  "@nuxtjs/vuetify",
  "vuetify"
]
```
