### ISSUE TITLE
Unable to generate source maps

### ISSUE THREAD

**Issue by cliffordh** [nuxt/nuxt.js#6016]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://www.nosuchurl.com//](https://www.nosuchurl.com//)

### Steps to reproduce

Update nuxt.config.js with this build setting:

build: {
    extend(config, { isClient }) {
      // Extend only webpack config for client-bundle
      config.devtool = '#source-map'
    }
  },

Run "npx nuxt generate"

No reproduction link posted as this is a private repo.

### What is expected ?

Source maps should be exported with JavaScript files in dist/_nuxt directory.

### What is actually happening?

● Client █████████████████████████ after chunk asset optimization (93%)  
 

/Users/cliff/Work/vue/2020-checker/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.

### Additional comments?

I was able to use eval-source-map build setting but those are not usable for my purposes. All online research doesn't point to a successful source map. Posting her for assistance.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9443">#c9443</a>)</em></sub></div>

**Comment by blackfox00** [comment]
you are only requesting the isClient variable from arguments, but you need to use too
```
extend(config, {isClient}) {
  if (isClient) {
    config.devtool = process.env.NODE_ENV === 'development' ? '#source-map' : '';
  }
...
}
```

**Comment by aldarund** [comment]
That shouldnt really happen. But its hard to say what wrong without a repro. Please try to create a minimal repo where your issue can be reproduced
