### ISSUE TITLE
doesn't work window.onscroll

### ISSUE THREAD

**Issue by fortil** [nuxt/nuxt.js#602]
Hi guys

I have a problem and don't found the solution. I want to detect the scroll of the user, but when I try doesn't work. 
This is my code.
```
mounted () {
  window.onscroll = e => {
    console.log(e)
  }
}
```
Too I put this code.

```
mounted () {
  window.addEventListener('scroll', e => {
    console.log(e)
  }, false)
}
```
neither with `window` neither `document`

Thanks

**Comment by alexchopin** [comment]
Hi, I can't reproduce your issue. It works fine for me.

**Comment by fortil** [comment]
@alexchopin How to works for you? do you have an example?

because doesn't works to me

**Comment by fortil** [comment]
I found the problem

The problem is the code `/assets/css/main.css` in the template this have a code 
```
html, body
{
  background-color: #fff;
  color: #000;
  letter-spacing: 0.5px;
  font-family: "Source Sans Pro", Arial, sans-serif;
  height: 100vh;
  margin: 0;
}
```
In chrome when you have `height: 100%` or `100hv` doesn't work scrollTo, I don't know why.
