### ISSUE TITLE
Nuxt.js Page Unresponsive

### ISSUE THREAD

**Issue by nxmad** [nuxt/nuxt.js#6022]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://jsfiddle.net/2pbthd1v/](https://jsfiddle.net/2pbthd1v/)

### Steps to reproduce

I don't know what exactly cause this bug, so I don't know how to reproduce or debug it. But looks like it's a known Vue problem – https://github.com/vuejs/vue/issues/6558.

### What is expected ?

-

### What is actually happening?

Browser just freezes after click at any link
![ncty5.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/660550a0-9d11-11e9-a6ec-9f9f41d7aab6.png)

### Additional comments?

I got this bug for the first time after update to Nuxt v2.8.1. Then I started another project and got this bug again. It happens sometimes in different browsers. Sometimes only language-specific versions of the website are affected (probably i18n module cause this bug, but I'm not sure).

Some of my deps:
"@nuxtjs/auth": "^4.7.0",
"@nuxtjs/axios": "^5.5.4",
"@nuxtjs/google-analytics": "^2.0.2",
"@nuxtjs/toast": "^3.2.1",
"nuxt-i18n": "^5.12.7"

Probably something else cause this problem. Looking for any tips. Thanks.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9447">#c9447</a>)</em></sub></div>

**Comment by aldarund** [comment]
Please, create a nuxt repro where this could be seen. Otherwise its impossible to tell what wrong and where..

**Comment by nxmad** [comment]
@aldarund Please try one of this links: https://hackerman.cc or https://ru.hackerman.cc

**Comment by nxmad** [comment]
Thanks God for Chrome step-by-step debug. nuxt-community/nuxt-i18n causes this problem if you use detectBrowserLanguage option. I will copy issue to their repo. Nuxt rocks 💪

**Comment by manniL** [comment]
Closing here then ☺️

**Comment by maziarz** [comment]
@nxmad, do you have a link to the issue? I have the same problem.
