### ISSUE TITLE
SSR - state changes within page are not applied to layout

### ISSUE THREAD

**Issue by DarrenTheDev** [nuxt/nuxt.js#6023]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/embed/nuxt-layout-variation-example-yi53q](https://codesandbox.io/embed/nuxt-layout-variation-example-yi53q)

### Steps to reproduce

Clicking between the home and about page work as expected, that is: transition out -> colour change -> transition in. However if you reload the about page or check SSR generated source the dark theme isn't applied to this page.

### What is expected ?

It is expected that the "dark theme" state change triggered in the beforeChange function of the about page take effect on the generated source.

### What is actually happening?

This state change has no effect and the about page is not displayed in the dark theme.

### Additional comments?

The use case here is applying a variation to the layout based on the page. The demo shows different theme colours but this could be hiding a menu or any other variation. I've tried other methods of accomplishing the same thing, but none of them strike the balance of taking effect in the SSR source and the change occurring after the content is transitioned out in a dynamic page transition. Both the fetch function and watching the route will cause the state change to happen as soon as the link is clicked. There is no other way that I can see to trigger an event at this point of the page transition.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9448">#c9448</a>)</em></sub></div>

**Comment by pimlie** [comment]
This seems to be a reactivity thing? Eg see https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server.

Also you shouldnt use `this` in your templates, just `$store.state.bgColour` should suffice. But probbaly better create a computed bgColour prop and use that.

**Comment by DarrenTheDev** [comment]
Thanks for your response. I get that Vue SSR has some reactivity restrictions and your advice for using the state in the template. 

The use case itself doesn't seem unreasonable though. Is there another approach to this problem that I'm missing?

What seems even stranger from the outside is that if I create a `head` function in the layout I can add a class the `html` element itself that reflects the correct state, but I can't do the same in the layout's template.

**Comment by pimlie** [comment]
I see two things in your repro:
- dark is not set in the source on ssr. This is correct behaviour due to lack of reactivity on ssr
- after page hydration dark is correctly set in Vuex, even though the page still has a white background. This could be related to the use of `this.` in the template

As mentioned, create a computed prop for your state and use that in the template as thats also the recommended approach.
