### ISSUE TITLE
relative vs absolute url path in asyncData

### ISSUE THREAD

**Issue by sangemi** [nuxt/nuxt.js#6024]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[http://localhost](http://localhost)

### Steps to reproduce

in .vue file, I have this code.
````
async asyncData ({ params, req }) {
...
try {
                let res = await axios.get('http://localhost:3000/api/blog/post')
                ...
}catch(err){
   ...
}
````
this is working.

But

                let res = await axios.get('/api/blog/post')

this is not working.
Is this  a bug? if not, why I cannot use "/aaa/bbb" url path?

### What is expected ?

I do not want to use domain name
http://localhost:3000
in my code. But sadly I have to do.

### What is actually happening?

this error is happened

{ Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
 ...

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9449">#c9449</a>)</em></sub></div>

**Comment by manniL** [comment]
You can set the base URL in your nuxt.config.js https://axios.nuxtjs.org/options#baseurl
