### ISSUE TITLE
nuxt.js + Firebase without VueFire - Query

### ISSUE THREAD

**Issue by mkharibalaji** [nuxt/nuxt.js#603]
Hi @Atinux ,
           I am about to start a new project with nuxt.js + Firebase.

With reference to #151.
Is this problem with vuefire or firebase ? .
Is it good to go with firebase and nuxt.js without using vuefire or firebase rest api ?

**Comment by alexchopin** [comment]
@mkharibalaji it was due to vuefire.
You can use firebase directly like the [vue-hackernews](https://github.com/vuejs/vue-hackernews-2.0) example does.
