### ISSUE TITLE
Modern mode doesn’t work on safari 10.1

### ISSUE THREAD

**Issue by paulnta** [nuxt/nuxt.js#6032]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/nuxt-modern-owwky](https://codesandbox.io/s/nuxt-modern-owwky)

### Steps to reproduce

- In `nuxt.config.js`, set the modern property to `client`
- view the app (in development or production mode) with safari 10.1

### What is expected ?

The modern mode (`modern: 'client'`) provides 3 things:
- A modern bundle  `<script type="module">` used by browsers that supports ES2015+ features
- A legacy bundle `<script nomodule>` for older browsers
- A Safari 10.1 fix to support the `nomodule` attribute

We expect Safari 10.1 to load and exectute the modern bundle only (ignoring the legacy one). For this to work correctly, scripts should be injected at the end of the page in the following order: 

> Note the Safari fix placed prior to any `nomodule` scripts

```html
<!-- Modern bundle -->
<script type="module" src="/_nuxt/modern-runtime.js" defer=""></script>
<script type="module" src="/_nuxt/modern-pages/index.js" defer=""></script>
<script type="module" src="/_nuxt/modern-commons.app.js" defer=""></script>
<script type="module" src="/_nuxt/modern-vendors.app.js" defer=""></script>
<script type="module" src="/_nuxt/modern-app.js" defer=""></script>

<!-- Safari 10.1 fix-->
<script>!function(){ /*...*/ }();</script>

<!-- Legacy bundle -->
<script nomodule src="/_nuxt/runtime.js" defer=""></script>
<script nomodule src="/_nuxt/pages/index.js" defer=""></script>
<script nomodule src="/_nuxt/commons.app.js" defer=""></script>
<script nomodule src="/_nuxt/vendors.app.js" defer=""></script>
<script nomodule src="/_nuxt/app.js" defer=""></script>
  
```

### What is actually happening?

Safari 10.1 **loads and executes both, legacy and modern bundle**. This results in unexpected behaviors and a lot of errors in my app.

For a very simple case, a log in `created` would appear twice on the client
```vue
<script>
// pages/index.vue
export default {
  created() {
    console.log("Page created (Should be logged only once)");
  }
};
</script>

```

![nuxt modern safari 10-min.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0ba46240-9e9c-11e9-8915-ad549af8dbc6.png)

### Additional comments?

The fix for Safari is visible in the page but doesn't seem to have any effect. From what I understand, the logic is based on `beforeload` event to prevent `nomodule` scripts to load if `type=module` is already supported. But, because the "fix" script is included at the end, it will miss all `beforeload` events

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9455">#c9455</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Thanks for the reporting, I’ll look into this tmr
