### ISSUE TITLE
'Undefined is not a function error' in IE11 

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt.js#6034]
This is most likely caused by an issue in Babel 7.5.0.

See: https://github.com/babel/babel/issues/10166

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9456">#c9456</a>)</em></sub></div>

**Comment by neonerd** [comment]
This has now been fixed in 7.5.1:

https://github.com/babel/babel/releases/tag/v7.5.1

**Comment by manniL** [comment]
Well, that was fast :relaxed:
