### ISSUE TITLE
Customized pages directory does not take effect after upgrading version 2.8.1

### ISSUE THREAD

**Issue by avaforvr** [nuxt/nuxt.js#6036]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://nuxtjs.org/api/configuration-dir](https://nuxtjs.org/api/configuration-dir)

### Steps to reproduce

There are some unrelated businesses in the project. I built some directories under the pages directory, such as pages/app, pages/ads. Then deploying to different sites through different config files (nuxt --config-file).

Following is my config for app，app.config.js:
module.exports = merge(commonConfig, {
    buildDir: 'dist/app',
    dir: {
        pages: 'pages/app',
    }
})

In version 2.6.3，I can execute the "nuxt --config-file app.config.js" command to compile only the files in the pages/app directory.

But in 2.8.1，when executing the same command, all page file in pages directory is compiled.

### What is expected ?

Repair or provide other solutions as soon as possible

### What is actually happening?

This week.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9458">#c9458</a>)</em></sub></div>

**Comment by pimlie** [comment]
If you are looking for having this solved _this week_, please create an issue for paid support at https://otechie.com/ and you will receive top-notch support from the core-team immediately / directly.

Otherwise, Nuxt is a community effort so please refrain from statements like this week.

**Comment by avaforvr** [comment]
This is my first attempt to ask the development team questions. I don't know what the right way and what to pay attention to. If I did something wrong
, I am sorry.

**Comment by pimlie** [comment]
You did nothing wrong as so much, but as you requested a solution asap thats what the paid support is meant for. Otherwise have a look at [this article](https://medium.com/@teejeetech/etiquette-in-open-source-projects-f302b6e19c38)

**Comment by avaforvr** [comment]
The article is helpful, Thank you very much. I‘m trying to edit now.

**Comment by avaforvr** [comment]
The code in codesandbox is normal:
https://codesandbox.io/s/codesandbox-nuxt-3vi5h

In my project, I import 'commonConfig' with require(). This is the problem:
const commonConfig = require('./common.config.js')

In 2.8.1, The object defined with require() can't be the second parameter in 'merge()'.
But in 2.6.3, it's OK.

**Comment by avaforvr** [comment]
I think it's caused by import and require.
I can't use require in codesandbox, so if you need, you can download here:
https://github.com/avaforvr/testVersion
'common.config.js' is included by require() and there's some 'import' in it. Then merge() can't work.
But in Nuxt 2.6.3, it's OK.
