### ISSUE TITLE
Module not found for background image when build/generate with space in image name

### ISSUE THREAD

**Issue by mu-yu** [nuxt/nuxt.js#6041]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-img-bug-z84um](https://codesandbox.io/s/codesandbox-nuxt-img-bug-z84um)

### Steps to reproduce

I have some style in vue sfc like this
```vue
<style lang="scss">
.some-class {
	background-image: url("~assets/index/ico xxx.png"); // there is a space between ico and xxx
}
</style>
```

There is no problem in `dev`, but `Module not found` error in `build` and `generate`.

### What is expected ?

image build/generate correct

### What is actually happening?

Module not found occured.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9461">#c9461</a>)</em></sub></div>

**Comment by pimlie** [comment]
[`url()` expects a uri](https://drafts.csswg.org/css-values-3/#url)

and an uri should not contain a space, you need to encode it to `%20`: https://tools.ietf.org/html/rfc3986

**Comment by mu-yu** [comment]
I think `dev`, `generate` and `build` should have same behavior.
