### ISSUE TITLE
CSS Flash with stylus but not with CSS (FOUC)

### ISSUE THREAD

**Issue by ShailenNaidoo** [nuxt/nuxt.js#6042]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/ShailenNaidoo/nuxt-fouc-reproduction](https://github.com/ShailenNaidoo/nuxt-fouc-reproduction)

### Steps to reproduce

* Clone repo
* Yarn install
* `npx nuxt build`
* `npx nuxt start` you should see FOUC in browser
* Go to `nuxt.config.js` and comment out the `app.styl` file and then uncomment the `vuetify.css` file
* `npx nuxt build`
* `npx nuxt start` You should see no FOUC

### What is expected ?

There should be no FOUC when using `.styl` files or any pre-processor but when using `.css` files it works perfectly like the following:

![ezgif-5-337d3ed060be.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/6c044380-a15d-11e9-add8-5d4810585b47.gif)

### What is actually happening?

When using `.styl` there is a FOUC, there should not be this using any preprocessor

![ezgif-5-786d1b9aa876.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/888e04f0-a15d-11e9-add8-5d4810585b47.gif)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9462">#c9462</a>)</em></sub></div>

**Comment by pimlie** [comment]
Step 5 of your instructions is not available as there are no css files listed in the nuxt.config

**Comment by ShailenNaidoo** [comment]
> Step 5 of your instructions is not available as there are no CSS files listed in the nuxt.config

@pimlie Sorry about that, I accidentally pushed up the wrong config. Check it out now

**Comment by Vout** [comment]
Seems exactly like the issue i have with scss, https://cmty.app/nuxt/nuxt.js/issues/c10400
