### ISSUE TITLE
Vuetify custom theme ignored by Nuxt

### ISSUE THREAD

**Issue by begueradj** [nuxt/nuxt.js#6043]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues/](https://github.com/nuxt/nuxt.js/issues/)

### Steps to reproduce

I am using Nuxt.js with Vuetify.js where I want to change the default theme colors.

I created a file: **~/plugins/vuetify.js** to change the default primary color to red.

Here is its content:

```
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify, {
  theme: {
    primary: '#ff0000'
  }
})
```
In nuxt.config.js I asked Nuxt.js to use this plugin:

```
export default {
  plugins: ['~/plugins/vuetify']
}
```

### What is expected ?

Calling primary must render the red color

### What is actually happening?

The default primary color `#1976d2`  is displayed

### Additional comments?

This is true maybe in whatever Nuxt.js version you use.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9463">#c9463</a>)</em></sub></div>

**Comment by pimlie** [comment]
Please try with the vuetify module instead of your custom plugin: https://github.com/nuxt-community/vuetify-module/

**Comment by begueradj** [comment]
I resolved the problem, it was not a bug. 
I posted the solution on [StackOverflow](https://stackoverflow.com/questions/56931736/vuetify-custom-theme-ignored-by-nuxt/56933835#56933835)
Hope this can be useful for someone else in the future. 
Thank you

**Comment by masterDoomX** [comment]
@begueradj I also have the same problem what was your solution?

**Comment by Alecell** [comment]
Same here, the solution link is broken.

**Comment by begueradj** [comment]
@Alecell Indeed, sorry ... I noticed in newer Nuxt versions, you can control that in **nuxt.config.js** file which is in the root directory of your project

**Comment by begueradj** [comment]
@masterDoomX  Sorry for the late reply, please just open **nuxt.config.js**, scroll down until you see what you are looking for.

**Comment by cjg9040** [comment]
Try this. I was in the same problem and solved it this one :)

vuetify: {
    theme: {
      themes:{
        light:{
          primary: '#ff9f1a'
        }
      }
    }
  },

**Comment by gomezmark** [comment]
I using @nuxt/vuetify

then on my nuxt.config.js
`
buildModules: [
    '@nuxtjs/vuetify',
  ],
vuetify: {
    customVariables: ['~/assets/variables.scss'],
    theme: {
      dark: false,
      themes: {
        light: {
          primary: '#5398d9',
        }
      }
    }
  }
`

**Comment by begueradj** [comment]
Thank you for sharing @cjg9040

**Comment by BonBonSlick** [comment]
I set  `theme:   disable: true,`
still, default `theme--light `applied

**Comment by vZanchiV** [comment]
> I set `theme: disable: true,`
> still, default `theme--light `applied

same, you have find a soluce ?

**Comment by AllanPinheiroDeLima** [comment]
The docs should have mentioned that you need to envelope the app on <v-app light> tag in the customization section, shouldn't ?

Took me a couple hours to figure out
