### ISSUE TITLE
Vue.component is not support Naming Hump when we use it like this:extends: Vue.component('RouterLink')

### ISSUE THREAD

**Issue by zw1371** [nuxt/nuxt.js#6048]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://zh.nuxtjs.org/api/components-nuxt-link/](https://zh.nuxtjs.org/api/components-nuxt-link/)

### Steps to reproduce

1:use nuxt-lint
2:open prefetch
3:throw a error:this.to is not defined

### What is expected ?

this.to is not defined

### What is actually happening?

this.to is not defined

### Additional comments?

nuxt-link extents router-link,but it is error in Vue.component('RouterLink'),you should use Vue.component('route-lLink')

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9468">#c9468</a>)</em></sub></div>

**Comment by Atinux** [comment]
Please make sure to have the latest version of Nuxt.js and give a correct reproduction link using https://template.nuxtjs.org
