### ISSUE TITLE
Custom HTML element <redoc>

### ISSUE THREAD

**Issue by bat79a** [nuxt/nuxt.js#6050]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-pl3z3](https://codesandbox.io/s/codesandbox-nuxt-pl3z3)

### Steps to reproduce

Insert inside a html page : 
- the spec-url inside the custom tag redoc 
- and import the Redoc CDN 

like the example here : https://github.com/Redocly/redoc

extract example : 
```
<redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>
<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
```

### What is expected ?

Display the redoc tag html

### What is actually happening?

Console display an error : 

custom element: <redoc> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### Additional comments?

We need to put a custom tag HTML for Redoc and Nuxt think that is a custom component I think.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9472">#c9472</a>)</em></sub></div>

**Comment by fengjiel** [comment]
I think:
1.Verify that third-party components are loaded and running
2. Use `v-pre` parsing the label

**Comment by bat79a** [comment]
Hi @fengjiel .
v-pre make the job, I did not see this label.
Thx a lot.

**Comment by bat79a** [comment]
Hi.
v-pre works well, but with this tag I can't use additional dynamic argument like :
v-bind:href="url"

**Comment by fengjiel** [comment]
@bat79a  
try
```
vue: {
    config: {
      ignoredElements :['redoc']
    }
  }
```
in `nuxt.config.js`   and delete `v-pre`

Because the local environment is not perfect the results are not very guaranteed

**Comment by bat79a** [comment]
Hi.

Thx a lot again @fengjiel. It's working. 
Now I have to find why redoc is not loading the element if the user refresh the browser page.

**Comment by fengjiel** [comment]
You can use
```
head() {
    return {
      script: [
        {
          src: "https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js",
          async: true,
          defer: true,
        }
      ]
    };
  },
```

**Comment by bat79a** [comment]
Wow. Thx a lot, it works like a charm ;p
Have a nice day and thank you so much.
