### ISSUE TITLE
Loading of Sass Processing

### ISSUE THREAD

**Issue by dant672** [nuxt/nuxt.js#6053]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

Upgrade a large project to Nuxt 2.0.0.

### What is expected ?

Fast hot reload

### What is actually happening?

30 second plus reload

### Additional comments?

It takes more than 30 seconds to process changes to scss files. I have tried nuxt-sass-resources-loader, @nuxtjs/style-resources, and fast-sass-loader. Nothing has yet to work. What I have deduced is that this seems to be an issue with sass-loader, however, I don't know an alternative.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9474">#c9474</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @dant672

I can only guess based on the info provided. A reproduction would help a lot here. 
However, in `dev`, HMR should be way faster than 30 seconds. Maybe a "wrong import", like loading all of element-ui through nuxt style resources?

**Comment by dant672** [comment]
Thank you so much @manniL for getting back to me. I am sure this is the issue.

Here's my nuxt.config.js
`modules: [
    // provide path to the file with resources
    'bootstrap-vue/nuxt', '@nuxtjs/dotenv', '@nuxtjs/style-resources',
  ],

 styleResources: {
   // your settings here
   scss: ['@/styles.scss'],
 },`

It loads my main stylesheet. And in the main stylesheet I import my sylesheet components:

`/@import 'static/scss/online-store.scss';
@import 'static/scss/treatment-steps.scss';
//@import 'static/scss/video.scss';
@import 'static/scss/philosophy-section.scss';
@import 'static/scss/contact.scss';
@import 'static/scss/faq.scss';
@import 'static/scss/pricing.scss';
@import 'static/scss/credentials.scss';
@import 'static/scss/conditions-treated.scss';
@import 'static/scss/featured-content.scss';
@import 'static/scss/visit-practice.scss';
@import 'static/scss/main.scss';
@import 'static/scss/footer.scss';
@import 'static/scss/hero-home.scss';
@import 'static/scss/header.scss';
@import 'static/scss/blog-center.scss';
@import 'static/scss/subscribe-button.scss';
@import 'static/scss/articles-section.scss';
@import 'static/scss/article.scss';
@import 'static/fonts/tiempos/stylesheet.css';
@import 'static/fonts/avenir/stylesheet.css';`

In the page I load the main stylesheet as follows:

`<style lang="scss">
  @import 'styles.scss';
</style>
`

I am sure I am doing something wrong with how I am structuring the project. Is there anything that sticks out to you?

**Comment by manniL** [comment]
1. Use `css` in `nuxt.config.js` to load your global css
2. Don't load styles via nuxt style resources as described in https://github.com/nuxt-community/style-resources-module/#setup . This has been discussed in several issues like https://github.com/nuxt-community/style-resources-module/issues/39

> Important notice: Do not import actual styles. Use this module only to import variables, mixins, functions (et cetera) as they won't exist in the actual build.
