### ISSUE TITLE
Change worker memory limit

### ISSUE THREAD

**Issue by JILeXanDR** [nuxt/nuxt.js#6054]
When I run `nuxt build` I see `Using 1 worker with 2048MB memory limit`
How to set limit as 512MB? My server has only 1GB RAM and it breaks the server.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9475">#c9475</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@JILeXanDR 

https://nuxtjs.org/api/configuration-build#typescript-typecheck
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#options => `memoryLimit`


```
// nuxt.config.js

export default {
  build: {
    typescript: {
      typeCheck: {
        memoryLimit: 512
      }
    }
  }
}
```

Please close the issue if it went fine for you 😉

**Comment by JILeXanDR** [comment]
@kevinmarrec
