### ISSUE TITLE
transtion is invalid

### ISSUE THREAD

**Issue by zw1371** [nuxt/nuxt.js#6058]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://cmty.app/nuxt/issues/new?type=bug-report&repo=nuxt.js](https://cmty.app/nuxt/issues/new?type=bug-report&repo=nuxt.js)

### Steps to reproduce

i try to use transtion in function mode at nuxt.config.js,but it is invalid,so i have to  write it in *.vue files,

### What is expected ?

transtion  is invalid

### What is actually happening?

transtion  is invalid

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9476">#c9476</a>)</em></sub></div>

**Comment by fengjiel** [comment]
Please post the specific code

**Comment by Atinux** [comment]
Please re-open with a valid reproduction url. You can use https://template.nuxtjs.org as starter.
