### ISSUE TITLE
how can i use less in nuxt?

### ISSUE THREAD

**Issue by zhancheng** [nuxt/nuxt.js#606]
as the title, i hope to use less in nuxt , but when i set lang to less the nuxt tell me that, 

`This dependency was not found:

* !!vue-style-loader!css-loader!../node_modules/._vue-loader@11.3.4@vue-loader/lib/style-compiler/index?{"id":"data-v-b155f86e","scoped":false,"hasInlineConfig":true}!less-loader!../node_modules/._vue-loader@11.3.4@vue-loader/lib/selector?type=styles&index=0!./index.vue in ./pages/index.vue

To install it, you can run: npm install --save !!vue-style-loader!css-loader!../node_modules/._vue-loader@11.3.4@vue-loader/lib/style-compiler/index?{"id":"data-v-b155f86e","scoped":false,"hasInlineConfig":true}!less-loader!../node_modules/._vue-loader@11.3.4@vue-loader/lib/selector?type=styles&index=0!./index.vue
`

but when i install vue-style-load & css-loader , it does not work either, hope to fix it as soon, thanks!

**Comment by stbaer** [comment]
You need to install less-loader and less first
`npm i less less-loader --save-dev`

**Comment by zhancheng** [comment]
thanks @stbaer

**Comment by langgo** [comment]
Should add it to the document ?

**Comment by pi0** [comment]
@langgo I think some notes about sass-loader exists in docs. Would be nice if having both :)

**Comment by YangChunliang** [comment]
> You need to install less-loader and less first
> `npm i less less-loader --save-dev`

thank you very much!

**Comment by Nabellaleen** [comment]
But ... why do use save it as dev dependencies ?

It's not a package "for developers", like a linter, it's a part of the build process, and if you run your project with `NODE_ENV=production npm install` it will fail without these packages
