### ISSUE TITLE
Modern build tries to resolve core-js 3 polyfills

### ISSUE THREAD

**Issue by MDSLKTR** [nuxt/nuxt.js#6061]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-q9d7w](https://codesandbox.io/s/codesandbox-nuxt-q9d7w)

### Steps to reproduce

Run the sandbox and check the webpack output. Also try to delete core-js from package.json and rebuild which will make the client build break and modern succeed.

### What is expected ?

Client and modern build run successfully

### What is actually happening?

Modern build fails, client build works

### Additional comments?

Shouldn't core-js be ignored when building for modern mode? Please not that removing the babel config makes both builds work, however i need it for the client build.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9482">#c9482</a>)</em></sub></div>

**Comment by MDSLKTR** [comment]
The fun thing is if i have installed core-js 3 via package.json, it will break the modern build, if i don't it will break the client build.

**Comment by MDSLKTR** [comment]
Full config

``
import pkg from './package';
import path from 'path';
import fs from 'fs';
import StyleLintPlugin from 'stylelint-webpack-plugin';

export default {
    mode: 'spa',

    //modern: 'client',

    /*
     ** Headers of the page
     */
    head: {
        title: pkg.name,
        meta: [
            { charset: 'utf-8' },
            {
                name: 'viewport',
                content:
                    'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no',
            },
            {
                name: 'apple-mobile-web-app-capable',
                content: 'yes',
            },
            {
                name: 'apple-mobile-web-app-status-bar-style',
                content: 'default',
            },
        ],
    },

    axios: {
        retry: { retries: 3 },
        retryDelay: (retryCount) => {
            return retryCount * 1000;
        },
    },

    workbox: {
        cachingExtensions: '@/plugins/workbox-fetch',
        cleanupOutdatedCaches: true,
        autoRegister: false,
    },

    /*
     ** Customize the progress-bar color
     */
    loading: { color: '#fff' },

    /*
     ** Global CSS
     */
    css: [],

    /*
     ** Plugins to load before mounting the App
     */
    plugins: [
        '~/plugins/polyfills',
        '~/plugins/vee-validate',
        '~/plugins/filters',
        '~/plugins/translator',
        '~/plugins/axios',
        '~/plugins/smoothscroll',
        '~/plugins/touch',
        {
            src: '~/plugins/workbox-hook',
            ssr: false
        },
    ].concat(process.env.NODE_ENV === 'production' ? ['~/plugins/sentry'] : []),

    /*
     ** Nuxt.js modules
     */
    modules: [
        '@nuxtjs/style-resources',
        '@nuxtjs/axios',
        'portal-vue/nuxt',
        '~/modules/filter-routes',
    ].concat(process.env.NODE_ENV === 'production' ? ['@nuxtjs/pwa'] : []),

    styleResources: {
        scss: ['assets/scss/*.scss'],
    },

    transpile: ['vee-validate'],

    server: {
        https: {
            key: fs.readFileSync(path.resolve(__dirname, 'ssl/ssl.key')),
            cert: fs.readFileSync(path.resolve(__dirname, 'ssl/ssl.crt')),
        },
        port: 3000, // default: 3000
        host: '0.0.0.0', // default: localhost,
    },

    env: {
        clientEnv: process.env.NODE_ENV || 'development',
    },

    /*
     ** Build configuration
     */
    build: {
        /*
         ** You can extend webpack config here
         */
        terser: {
            parallel: true,
            cache: false,
            sourceMap: false,
            extractComments: {
                filename: 'LICENSES',
            },
            terserOptions: {
                compress: {
                    drop_console: true,
                },
                mangle: true,
                ecma: 5, // specify one of: 5, 6, 7 or 8
                keep_classnames: false,
                keep_fnames: false,
                ie8: false,
                module: false,
                nameCache: null, // or specify a name cache object
                safari10: false,
                toplevel: false,
                warnings: false,
            },
        },
        extractCSS:
            process.env.NODE_ENV === 'production'
                ? {
                    cssProcessor: require('cssnano'),
                    cssProcessorOptions: {
                        preset: [
                            'default',
                            {
                                discardComments: {
                                    removeAll: true,
                                },
                            },
                        ],
                    },
                }
                : false,
        babel: {
            presets({ isServer }) {
                const targets = isServer
                    ? { node: '10' }
                    : {
                        chrome: '70',
                        edge: '18',
                        firefox: '64',
                        ios: '11.4',
                        safari: '12',
                    };
                return [
                    [
                        require.resolve('@nuxt/babel-preset-app'),
                        {
                            targets,
                            corejs: 3,
                            debug: process.env.NODE_ENV === 'production',
                        },
                    ],
                ];
            },
        },
        quiet: false,
        extend(config, ctx) {
            // Patch SVG Regex
            const urlLoader = config.module.rules.find(
                rule => rule.use && rule.use[0].loader === 'url-loader',
            );
            urlLoader.test = /\.(png|jpe?g|gif)$/;

            // Run ESLint on save
            if (ctx.isDev && ctx.isClient) {
                config.devtool = '#eval-source-map';
                config.module.rules.push({
                    enforce: 'pre',
                    test: /\.(js|vue)$/,
                    loader: 'eslint-loader',
                    exclude: /(node_modules)/,
                });
            }

            config.plugins.push(
                new StyleLintPlugin({
                    syntax: 'scss', // eg. with options if you need SCSS ;-)
                }),
            );

            config.externals = config.externals || {
                // chart.js requires moment which is shit
                moment: 'moment'
            };

            config.module.rules.push({
                test: /\.svg$/,
                use: [
                    {
                        loader: 'raw-loader',
                    },
                    {
                        loader: 'svgo-loader',
                        options: {
                            plugins: [
                                { removeViewBox: false },
                                { cleanupAttrs: true },
                                { removeDoctype: true },
                                { removeXMLProcInst: true },
                                { cleanupEnableBackground: true },
                                { convertStyleToAttrs: true },
                                { convertPathData: true },
                                { cleanupIDs: false },
                                { minifyStyles: true },
                                { removeUselessDefs: true },
                                { convertShapeToPath: true },
                                { removeUnusedNS: true },
                                { removeDimensions: true },
                                { convertTransform: true },
                                { collapseGroups: true },
                                { removeComments: true },
                                { removeEditorsNSData: true },
                                { removeUnknownsAndDefaults: true },
                            ],
                        },
                    },
                ],
            });
        },
    },
};
``

**Comment by MDSLKTR** [comment]
Also core-js 2 works so this has be a bug with the way core-js 3 includes the polyfills

**Comment by clarkdo** [comment]
I’ll look into this shortly.
