### ISSUE TITLE
Allow to map dynamic param to route (without duplicate path)

### ISSUE THREAD

**Issue by SHxKM** [nuxt/nuxt.js#6064]
### What problem does this feature solve?

Being able to map a parameter that is usually passed for dynamic routing to a child-component to the root url of my project.

I originally posted this as a question but after a lot of trying I think what I'm trying to achieve isn't currently possible in Nuxt.js.

---

I'm using Nuxt in SSR mode.

I'm trying to implement pagination (from an API), and what I want to achieve is this:

User goes to `/` - he gets results from `:id=1`
User goes to `/2` - he gets results from `:id=2` 
User goes to `/3` - he gets results from `:id=3`

User goes to `/1` - he gets results from `:id=1` - but content isn't visible at `/1` and he is instead redirected to `/` 
(this is to disallow the same content on two different pages, SEO-wise)

I am getting my paginated results from an API, and I'm saving the `navigation` object, including `navigation.count`, `navigation.next` (the next page), and `navigation.previous`.

I have tried doing this in my `nuxt.config.js`:

```js
  router: {
    mode: 'history',
    middleware: ['user-agent'],
    extendRoutes(routes, resolve) {
      routes.push({
        name: 'index',
        path: '/',
        component: resolve(__dirname, 'pages/_page_num.vue')
      })
    }
  },
```

And have this logic in the `_page_num.vue` file:

```js
async fetch({ store, params }) {
    await store.dispatch('posts/getPosts', { page: params.page_num || 1 })
},
```

But this has two problems:

1) I can no longer navigate using `nuxt-link`:

```vue
The below simply doesn't work anymore, it points to `/` and ignores params
<nuxt-link v-if="pagination.next" :to="{name: '', params: { page_num:pagination.next } }">
      Next
</nuxt-link>
```

2) The page `/1` is still visible and accessible.

If I try to tackle issue 1 by changing nuxt-link to the below, then the data for `/1` is loaded on the root URL `/` but only if an actual refresh happens, not if the `index` link is clicked in the client:
```vue
<nuxt-link v-if="pagination.next" :to="{name: 'page_num', params: { page_num:pagination.next } }">
      Next {{ pagination.next }}
</nuxt-link>
```

I also tried to implement `nuxt-child`, with `pages/index.vue` and `pages/index/_page_num.vue`, but this doesn't work either. Nothing is loaded at `/`.

### What does the proposed changes look like?

The whole problem seems to be that this dynamic needs to live in the root folder.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9487">#c9487</a>)</em></sub></div>

**Comment by fengjiel** [comment]
try to use [watchquery](https://nuxtjs.org/api/pages-watchquery)

**Comment by SHxKM** [comment]
> try to use watchquery

I did. It didn’t work.

**Comment by paulgv** [comment]
You should be able to achieve this by calling `redirect()` from `asyncData` to properly redirect users from `/1` to `/`. Then you just have to make sure `1` is considered the default ID and you should be good to go.

Here's an example in codesandbox: https://codesandbox.io/s/codesandbox-nuxt-jgpx0

**Comment by SHxKM** [comment]
Hey @paulgv, thanks for your help. I ended up doing something different today after banging my head for hours. 

I used the router-module to alias/map `/` to the  `/page/_page_num.vue` component and calling that “realIndex” which I reference everywhere. I also used the redirect module to make sure `/page/1` to `/`. Not really sure which option is better.
