### ISSUE TITLE
Modern build should detect browser compatibility

### ISSUE THREAD

**Issue by koresar** [nuxt/nuxt.js#6068]
### What problem does this feature solve?

* Have a modern build of Nuxt.js app deployed somewhere.
* Open it using iOS Safari 10.0 (not 10.1 or 10.3 !!!)

Problem: The app just crashes, nothing is rendered.

### What does the proposed changes look like?

Expected: the app shows something meaningful, like "Your browser is not supported"

How I resolved the situation currently.
* I have a custom `app.html` with a following line:
```
<script>if(/Trident|MSIE/.test(navigator.userAgent))window.location="/browser_not_supported.html"</script>
```
* I expanded it to detect other older browsers. However, I have no idea which browsers the modern build supports. The docs say:
> Modern bundle: targeting modern browsers that support ES modules

Still can't figure out which browser versions are safe to allow my app running.

I'd love Nuxt.js to handle that for me (somehow, anyhow, I don't care, I'm stupid).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9489">#c9489</a>)</em></sub></div>

**Comment by koresar** [comment]
Btw, this was the stack trace from Safari 10.0

```
TypeError: undefined is not an object (evaluating 'e[r].call')
  at f(/_nuxt/c4fb81ef2bd1bc2df4cd.js:1:533)
  at f([native code])
  at c(/_nuxt/40f3c18f67d9120d5bda.js:2:160220)
  at ? (/_nuxt/40f3c18f67d9120d5bda.js:2:160365)
  at n(/_nuxt/40f3c18f67d9120d5bda.js:2:163195)
```

**Comment by koresar** [comment]
The UCBrowser also can't render with the modern build. 3.6% global browser share though.

```
Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN
```

**Comment by clarkdo** [comment]
Could you please  provide a repo?

**Comment by koresar** [comment]
Let me extract the minimum code for you

**Comment by koresar** [comment]
The bug happens not in the modern build. But in the `nomodule` file:
`<script type="text/javascript" src="/_nuxt/ec7aaf0ab87eb8225e5a.js" nomodule>`

Thank you for your time. I have to close this for now. I'll get back to you when I have more information.
