### ISSUE TITLE
Manually triggering `asyncData`

### ISSUE THREAD

**Issue by pkucmus** [nuxt/nuxt.js#608]
Greetings.

I have a page which content I fetch with `asyncData` and I need to fetch that content again once a sign-in event happens:

```
export default {
  async asyncData ({ params }) {
    const res = await http.get(`/api/workshop/${params.id}/`)
    return {workshop: res.data.response}
  },
  computed: {
    ...mapGetters(['isAuthenticated'])
  },
  watch: {
    isAuthenticated () {
      // trigger asyncData again   <-----------
    }
  },
```

Redirecting to the same page after a successful sign-in would also work for me but something like 

```
this.$router.replace(this.$router.currentRoute.path)
```

also doesn't work for me. 

Can someone guide me what should I do (what am I going wrong) ?

**Comment by KonstantinVlasov** [comment]
Hi, @pkucmus!

You can put your fetch method outside the component logic, like:

```js
function myFetchMethod () {...}

export default {
  async asyncData () {
    return myFetchMethod()
  },
  computed: {
    ...mapGetters(['isAuthenticated'])
  },
  watch: {
    isAuthenticated () {
      myFetchMethod()
    }
  }
}
```

**Comment by pkucmus** [comment]
Thank you very much. I was looking for something fancy like "re-triggering" of some sort of the `asyncData` with all the cool features around it (loading bar to be accurate). This will work, thanks again!

**Comment by krestaino** [comment]
Is there a way to reference Nuxt from that outside function? In @KonstantinVlasov's example `function myFetchMethod () {...}`. I'm using the Nuxt [axios-module](https://github.com/nuxt-community/axios-module) and can't seem to figure out how to reference it.

**Comment by dw72** [comment]
```js
function myFetchMethod (axios) {...}
```
and call it in method
```js
isAuthenticated () {
  myFetchMethod(this.$axios)
}
```
and in asyncData
```js
async asyncData ({app}) {
  return myFetchMethod(app.$axios)
}
```
should work I think.
