### ISSUE TITLE
NUXT dependent packages using vulnerable lodash packages

### ISSUE THREAD

**Issue by Sumeshkumar** [nuxt/nuxt.js#6080]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

https://snyk.io/vuln/SNYK-JS-LODASH-73638

Please find the below packages using vulnerable version of lodash

1. @babel/core - lodash 4.17.11
2. @babel/generator - lodash 4.17.11
3. @babel/helper-define-map - lodash 4.17.11
4. @babel/helper-module-transforms - lodash 4.17.11
5. @babel/helper-regex - lodash 4.17.11
6. @babel/plugin-transform-block-scoping - 4.17.11
7. @babel/traverse - 4.17.11
8. @babel/types - 4.17.11
9. @nuxt/builder - 4.17.11
10. ava - 4.17.11
11. babel-register - 4.17.4
12. babel-template - 4.17.4
13. eslint - 4.17.11
14. eslint-plugin-import - 4.17.11
15. vue-eslint-parser - 4.17.11
16. hard-source-webpack-plugin - 4.15.0
17. html-webpack-plugin - 4.17.3
18. inquirer - 4.17.12
19. last-call-webpack-plugin - 4.17.5
20. request-promise-core - 4.17.11
21. webpack-bundle-analyzer - 4.17.10

Packages using vulnerable version of lodash.template

1. postcss-initial - 4.2.4
2. vue-server-renderer - 4.4.0

Package using vulnerable version of lodash.merge

1. concordance - 4.6.1

### What is expected ?

Update to stable version 

1. lodash  >= 4.17.13
2. lodash.template >= 4.5.0
3.  lodash.merge >= 4.6.2

### What is actually happening?

Vulnerable packages are using in NUXT.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9500">#c9500</a>)</em></sub></div>

**Comment by pi0** [comment]
Recreating/Updating lock file will update lodash to latest.

**Comment by Sumeshkumar** [comment]
@pi0 Deleted lock file, node_modules and installed all the packages. But I can see still older versions of the lodash is getting used in some of the packages.

1. @nuxt/builder - 4.17.11
2. babel-core - 4.17.4

There are many other packages also with older versions. Please see the below screenshots.

![Screen Shot 2019-07-18 at 11 50 03 AM](https://user-images.githubusercontent.com/4470620/61434037-8547d300-a952-11e9-8690-08a6434be9de.png)
![Screen Shot 2019-07-18 at 11 52 34 AM](https://user-images.githubusercontent.com/4470620/61434060-91339500-a952-11e9-87e8-dcd41918b98a.png)

**Comment by pi0** [comment]
^4.17.4 is a semver range that specifies anything newer than this but older than 5.x. Please check lodash entry in lock file :)
