### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by merianos** [nuxt/nuxt.js#6081]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/merianos/nuxt-memory-leak](https://github.com/merianos/nuxt-memory-leak)

### Steps to reproduce

1. Clone the repository
2. `yarn install`
3. `sudo yarn dev-debug` _(you could avoid the `sudo` by replacing the port `80` in the `package.json` with a different port number)_
4. Open your Chrome browser in the address `http://localhost` _(or if you use a different port number open the `http://localhost{:your-port-number}`)_
5. Open the Chrome `Developer Tools` and click the green `NodeJS` button on the top left corner of the `Developer Tools`

![nodejs.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/df1a3230-a865-11e9-843c-4511e466d3ac.png)

6.In the `NodeJS Developer Tools` console that will open, click the `Memory Tab`
7. Then run an `Apache Benchmark` test with high load and concurrency _(me, I use the following `ab -c500 -n1000000 http://localhost/`)_ and while the test is running watch the memory increase in the `NodeJS Developer Tools`.
8. Wait for the test to finish or stop it if the Nuxt consumes more memory than what is available in your system.
9. Observe the memory in the `NodeJS Developer Tools` that now is not getting released.

_(optional)_

10. If you still have free memory and you want to re-run the `Apache Benchmark`, you will see that the new requests will consume even more memory that is never get released. And if you continue running the benchmark, you will find that either the `NodeJS` will stop working, or your computer will be frozen.

### What is expected ?

After high traffic, the memory should be released.

### What is actually happening?

From what I see, when there is high traffic on the site, the memory is not released by new objects/arrays/closures/etc introduced to the memory of the `NoteJs`.

If you see the following picture, I took a snapshot just after I start the application, and one snapshot right after a heavy load, and I compare the two. What you can see, is that in most of the cases, new `system`, `closure`, `array`, `Object`, etc elements are introduced to the application, none of them are `deleted` and the `Delta` is increasing:

![comparison.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0f8baa60-a867-11e9-843c-4511e466d3ac.png)

In addition, it seems, like the issue comes from the NLink. While I am not an expert on memory leak debugging, I cannot assert that this is a true case, but if you see the following video, you will see that many objects/closures/arrays/etc are related somehow to the NLink:

https://youtu.be/dLELKLkM7Ok

### Additional comments?

If you want to see how the memory increases without run the application in your local environment, you could see the following video:

https://www.youtube.com/watch?v=nbCnFKAc7fg

Keep in mind, that I have also tried the version: 2.3.4 and I had the exact same results with the memory consumption. The only thing I didn't was to check the heap snapshot for the objects was inside the memory.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9501">#c9501</a>)</em></sub></div>

**Comment by galvez** [comment]
Just so we're clear, can you confirm you're not running this benchmark in `dev` mode?

**Comment by merianos** [comment]
What I run is in `dev` mode, but the result is the same for production mode too. In case of production, we only have smaller memory increment, but still the memory remains the same.

I will run in production mode too, and I will send more details in a few minutes :)

**Comment by merianos** [comment]
@galvez you are right. I forced the tests to run also in parallel with multiple URL calls and using the `<n-link>` and finally it operates very well. The memory never exceeded the 67MB which is exceptionally good.

Probably in our case, there's is something different that makes the leak.

Just to let you know, that in our case, I have tried both scenarios, `dev` and `prod` environments, and the leak is still there.

I wanted to ask you if you have any really good resource for memory leak debugging as I am working on that case for about 6 to 7 days now and I cannot find any solution.

Also, in our production-ready app, I have kept only a few static pages to reduce the application size to the minimum, as well I have removed the scss and other things that give an extra load to the application but still cannot find what is the source of the problem.

Any idea from where to start?

Thanks in advance!

**Comment by aldarund** [comment]
fyi - to remove mem leak in dev mode you can set build.standalone true and it should do the trick for dev mode.
for debugging mem leak you could try to use https://github.com/pimlie/nuxt-memwatch

**Comment by merianos** [comment]
@aldarund thank you very much for your reply !! :)

I have already seen the `nuxt-memwatch` but it doesn't help a lot :( :/

I mean, It's OK, it showing the heap size and the other useful information, but doesn't really provide any useful information such as a file that may have code leaking memory, or pointing somehow to places that probably a leak exists.

For that kind of debugging is way much better the Chrome DevTools, but again, it's too hard.

Anyway, I really appreciate your answer and your time.

Kind regards

**Comment by aldarund** [comment]
Maybe u have some intervals on ssr?  see https://blog.lichter.io/posts/the-guide-to-write-universal-ssr-ready-vue-compon/#lifecycle-hooks-and-side-effects

**Comment by manniL** [comment]
Closing here as there is no memory leak in a fresh Nuxt application in `production` mode.

**Comment by agcty** [comment]
Is there any documentation on how to find memory leaks in production? More specifically on how to utilize the Node.js inspect feature. I've been trying something like:

package.json
`"start": "nuxt start --inspect"`but this doesn't work, what works flawlessly is  `"dev-debug": "node --inspect node_modules/.bin/nuxt"`. I can't however, find the node command used to start nuxt. Any help would be really appreciated!

**Comment by artlomako** [comment]
@agcty, `node --inspect node_modules/.bin/nuxt-ts` works for me. For Nuxt without TS respectively `node --inspect node_modules/.bin/nuxt`
