### ISSUE TITLE
SPA Build 404 on refresh dynamic route

### ISSUE THREAD

**Issue by packytagliaferro** [nuxt/nuxt.js#6088]
I am new to Nuxt. I have made one static site that turned out great but now making a site with dynamic content (like a blog). I would have a structure like so:

```
->posts/
-->index.vue
-->_slug.vue
```
When running `npm run dev` I can go to `mysite.test/posts/slug-1` and I get the page I want. If I refresh I still get that page I want.

The issue comes when I build it. I use `npm run build --spa` (not generate, I know generate creates static files and I would have to make a static file for each post). Now if I go to `mysite.test/posts/` and click on a post, it navigates to` mysite.test/posts/slug-1` and it works. If I go to the URL directly or refresh, it does not?

The site clearly says SPA mode works with dynamic routes, but it from what I see it only works to navigate to them, not direct link?

**Comment by gcaseres** [comment]
@packytagliaferro Have you found a solution for this issue?
I have the same problem and I can't find documentation for this case.

**Comment by manniL** [comment]
Use `generate.fallback` and point your webserver to that fallback html as a catch all route. https://nuxtjs.org/api/configuration-generate#fallback

**Comment by claudiobonfati** [comment]
You should setup your server to always request your spa's index.html for all routes that are not a file.

**.htaccess** 
`<ifModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule (.*) index.html [QSA,L]
</ifModule>`

_OR_

**nginx.conf**
`  ...
  location / {
      try_files $uri $uri/ /index.html;
  }`

After doing this you can reload any page, static or dynamic.

**Comment by pokrenz** [comment]
this issue still exist on nuxt 3 till now

**Comment by ajaysainii** [comment]
is there any solution for Nuxt 3 apps?
