### ISSUE TITLE
linting config broken

### ISSUE THREAD

**Issue by sandro-git** [nuxt/nuxt.js#6093]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/sandro-git/david-sols-nuxt](https://github.com/sandro-git/david-sols-nuxt)

### Steps to reproduce

just hit save with vscode after changer prettier config a fresh start with create-nuxt-app.

i've a second branch were a go futher with the project and it's just impossible to work with.

### What is expected ?

linting properly

### What is actually happening?

a mess

### Additional comments?

i can figure it out try to remove and add setting and pluggins to eslint config file but can't find the solution

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9511">#c9511</a>)</em></sub></div>

**Comment by manniL** [comment]
Should be fixed with the latest CNA version. If not, please ping here again.
