### ISSUE TITLE
When importing a plugin on client  side, mode: 'client' and ssr: 'false' aren't working

### ISSUE THREAD

**Issue by stirredo** [nuxt/nuxt.js#6096]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce

1. Create a plugin in plugins directory as VueApexCharts.js
In that file:
```
import Vue from 'vue'
import VueApexCharts from 'vue-apexcharts'

Vue.use(VueApexCharts)
```

2. In your nuxt.config.js file:
```
plugins: [
    { src: '~/plugins/VueApexChart.client.js', mode:  'client' },
  ],
```
Or Try:
```
plugins: [
    { src: '~/plugins/VueApexChart.js', ssr:  false },
  ],
```
Or Try:
plugins: [
    { src: '~/plugins/VueApexChart.client.js'},
  ],

None of the methods for disabling ssr for a plugin mentioned in the documentation is working.

When you try to use <no-ssr><vue-apex-charts :options="options"></vue-apex-charts></no-ssr>

### What is expected ?

The plugin should be able to render only on client-side.

### What is actually happening?

It is being rendered on server side as I get the error:
```
Cannot read property 'document' of undefined
```

The exact stack trace:
node_modules/apexcharts/dist/apexcharts.common.js
![Screenshot 2019-07-20 at 12.43.07 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/de5df070-aabd-11e9-a59c-0123a142d272.png)

### Additional comments?

I need to use the plugin vue-apexcharts and I cannot disable ssr on it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9514">#c9514</a>)</em></sub></div>

**Comment by pimlie** [comment]
Thanks for the report. Please create a minimal reproduction on codesandbox that we can easily check.

**Comment by Atinux** [comment]
Please re-open with a repro (https://template.nuxtjs.org)

**Comment by mateuszgachowski** [comment]
same problem here @Atinux 

please see: https://codesandbox.io/s/codesandbox-nuxt-3gndu (it hangs the browser sometimes)

**Comment by mateuszgachowski** [comment]
For anybody trying to avoid this error on SSR:

```
 components: {
    vueApexCharts: () =>
      process.client ? import('vue-apexcharts') : Promise.resolve({ render: (h: any) => h('div') }),
  },

```

**Comment by davoodmood** [comment]
thanks, this solution worked for me. I'm glad with the result.

**Comment by developerKumar** [comment]
> For anybody trying to avoid this error on SSR:
> 
> ```js
> components: {
>     vueApexCharts: () =>
>     process.client ? import('vue-apexcharts') : Promise.resolve({ render: (h: any) => h('div') }),
> },
> ```

Thanks

**Comment by jasonbrookins** [comment]
Is this issue still active?  Or has it gotten an 'official' resolution yet?  I'm getting a `document is not defined` error despite marking the plugin as client-side only:

```
plugins: [
    { src: '~/plugins/vue-password-strength-meter', mode: 'client', ssr: false }
  ]
``` 
(note: redundancy with ssr: false was for testing)

**Comment by Atinux** [comment]
What is the content of your plugin?

**Comment by jasonbrookins** [comment]
#### ~/plugins/vue-password-strength-meter.client.js 
(from https://www.npmjs.com/package/vue-password-strength-meter)
```
import Vue from 'vue'
import VuePasswordStrengthMeter from 'vue-password-strength-meter'

if (process.client) {
  Vue.use(VuePasswordStrengthMeter)
}
```

#### nuxt.config.js
```
plugins: [
    { src: '~/plugins/vue-password-strength-meter.client.js', mode: 'client' }
]
```

#### .vue page
(trying to use the hint from *developerKumar* above)

```
components: {
    Password: () =>
      process.client
        ? import('vue-password-strength-meter')
        : Promise.resolve({ render: h => h('div') })
  }
```

**Comment by Atinux** [comment]
@jasonbrookins actually you can directly wrap the Password component with `<client-only>`:

```vue
<template>
  <div>
    <client-only>
      <password v-model="password"/>
    </client-only>
  </div>
</template>

<script>
import Password from "vue-password-strength-meter";

export default {
  components: {
    Password
  },
  data: () => ({
    password: ""
  })
};
</script>
````

Online demo: https://codesandbox.io/s/silent-dew-vm0fs

**Comment by jasonbrookins** [comment]
> @jasonbrookins actually you can directly wrap the Password component with `<client-only>`:
> 
> ```
> <template>
>   <div>
>     <client-only>
>       <password v-model="password"/>
>     </client-only>
>   </div>
> </template>
> 
> <script>
> import Password from "vue-password-strength-meter";
> 
> export default {
>   components: {
>     Password
>   },
>   data: () => ({
>     password: ""
>   })
> };
> </script>
> ```
> 
> Online demo: https://codesandbox.io/s/silent-dew-vm0fs

Thanks, Sébastien!
