### ISSUE TITLE
Appending scripts and styles to the body not work on initial page load

### ISSUE THREAD

**Issue by robertpiosik** [nuxt/nuxt.js#6097]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/embed/codesandbox-nuxt-rodbc](https://codesandbox.io/embed/codesandbox-nuxt-rodbc)

### Steps to reproduce

Click on the button and then go back. You will see that component inline style and script tags are loaded only on hot reload.

### What is expected ?

Styles and scripts that are defined in head() method should be appended to the body on initial page load & generate.

### What is actually happening?

Styles and scripts that are defined in head() method are appended to the DOM only during SPA navigation.

### Additional comments?

Thank you for resolving the issue.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9515">#c9515</a>)</em></sub></div>

**Comment by pimlie** [comment]
Unfortunately `body: true` is only supported for script elements (both by vue-meta as nuxt), not for style elements. Please create an issue on the vue-meta repo if you think it should be possible to add style's directly to the body on ssr as well.

**Comment by robertpiosik** [comment]
@pimlie [comment](https://github.com/nuxt/vue-meta/issues/244#issuecomment-470884445)

**Comment by robertpiosik** [comment]
@pimlie Ok, I see. I thought it was related to nuxt as you advised adding styles this way [comment](https://github.com/nuxt/vue-meta/issues/244#issuecomment-470884445)

**Comment by pimlie** [comment]
Damn, why you have to slap me with my own words like that :smile:

It seems my remark in that comment was not covering all angles (as in ssr). When updating on the client `body: true` is always respected, but during ssr this is depending on the framework as the framework needs to inject body styles separately in the template. Eg for nuxt an entry for styles should be added here: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L143-L144

**Comment by robertpiosik** [comment]
@pimlie Please forgive me! 

So it sounds like a valid bug-report.

**Comment by pimlie** [comment]
No problem! Actually its probably more a feature request than a bug from Nuxt's point of view.

Please feel free to submit a PR for this if you have the time. Should be rather straight forward :+1:

**Comment by hojas** [comment]
PS.  Set the loading property to `false` in page does not work?
