### ISSUE TITLE
nuxt-link does not have  `.html` suffix  when generate static site

### ISSUE THREAD

**Issue by yezongyang** [nuxt/nuxt.js#6103]
### What problem does this feature solve?

navigate between pages using nuxt-link in static site, just wanna url has `.html` suffix

```html
<a href="https://m.test.com/2019/about"></a>

<a href="https://m.test.com/2019/about.html">about</a>
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9523">#c9523</a>)</em></sub></div>

**Comment by manniL** [comment]
Could you explain what benefit having that `.html` ending gives you?

**Comment by yezongyang** [comment]
In company,  nginx config for SPA project with history route, for example:

```nginx
location / {
    try_files $uri index.html;
}
```

nginx config for MPA static site project,  for example:

```nginx
location / {
    try_files $uri $uri/index.html;
}
```
So the config is different between these projects,  i just wanna visit static pages with same nginx config like SPA project

**Comment by yin-shu** [comment]
.html is required when deploying to ali oss, otherwise this file will not be found
