### ISSUE TITLE
Custom class instances returned by asyncData

### ISSUE THREAD

**Issue by iliyaZelenko** [nuxt/nuxt.js#6107]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-vqzu1](https://codesandbox.io/s/codesandbox-nuxt-vqzu1)

### Steps to reproduce

Open index page with ssr

### What is expected ?

being able to pass class instances somehow and get them on the client

### What is actually happening?

Can't receive passed classes on client.

I also get warnings in the console: https://i.imgur.com/vd3fJRM.png

### Additional comments?

Re: https://github.com/nuxt/nuxt.js/issues/3227

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9526">#c9526</a>)</em></sub></div>

**Comment by aldarund** [comment]
Its not possible to pass custom object with custom methods from server to client. You can see what is possible to properly serialize here https://www.npmjs.com/package/@nuxt/devalue
And see this -> https://github.com/nuxt/nuxt.js/issues/5117
