### ISSUE TITLE
OOM when generating 10000 pages

### ISSUE THREAD

**Issue by Miaoxingren** [nuxt/nuxt.js#6110]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

npm run generate

### What is expected ?

Generate 10000 pages without oom.

### What is actually happening?

OOM occurs.

### Additional comments?

Sorry I don't have a reproduction link. I run top command and I found sometimes there are about 30 node process when runing `generate`, which cause OOM. Why there are so many node process, can i control it by `generate.concurrency`?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9533">#c9533</a>)</em></sub></div>

**Comment by pimlie** [comment]
`nuxt generate` is by default a single process, if you need multiple processes you could try to use `nuxt-generate-cluster`. So unfortunately this sounds like an issue with your project, because its not normal for 30 node processes to be running. Please share a minimal reproduction we can investigate

**Comment by Miaoxingren** [comment]
Take a look at this: [https://codesandbox.io/embed/pymmj2r9x7](https://codesandbox.io/embed/pymmj2r9x7)
I run `top` and `ps -ef | grep node` command after `generate` and I found more than one node process.
```
sandbox@sse-sandbox-pymmj2r9x7:/sandbox$ ps -ef | grep node
root         1     0  0 11:11 ?        00:00:00 /sbin/tini -- node agent
root         8     1  0 11:11 ?        00:00:01 node agent
sandbox     47     8  0 11:11 pts/0    00:00:00 node /opt/yarn-v1.16.0/bin/yarn.js dev
sandbox     71    70  9 11:11 pts/0    00:00:22 /usr/local/bin/node /sandbox/node_modules/.bin/nuxt
sandbox    235     8  0 11:15 pts/4    00:00:00 node /opt/yarn-v1.16.0/bin/yarn.js generate
sandbox    258   257 39 11:15 pts/4    00:00:07 /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    293   258 23 11:15 pts/4    00:00:02 /usr/local/bin/node /sandbox/node_modules/worker-farm/lib/child/index.js /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    300   258 43 11:15 pts/4    00:00:04 /usr/local/bin/node /sandbox/node_modules/worker-farm/lib/child/index.js /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    307   258  4 11:15 pts/4    00:00:00 /usr/local/bin/node /sandbox/node_modules/worker-farm/lib/child/index.js /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    308   258  4 11:15 pts/4    00:00:00 /usr/local/bin/node /sandbox/node_modules/worker-farm/lib/child/index.js /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    320   258  9 11:15 pts/4    00:00:00 /usr/local/bin/node /sandbox/node_modules/worker-farm/lib/child/index.js /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    327   258  3 11:15 pts/4    00:00:00 /usr/local/bin/node /sandbox/node_modules/worker-farm/lib/child/index.js /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    334   258  6 11:15 pts/4    00:00:00 /usr/local/bin/node /sandbox/node_modules/worker-farm/lib/child/index.js /usr/local/bin/node /sandbox/node_modules/.bin/nuxt generate
sandbox    352   213  0 11:15 pts/3    00:00:00 grep node
```

**Comment by pimlie** [comment]
Do you only experience this issue on Codesandbox? Can confirm the issue exists.

It seems csb abstracts the node command and somehow runs the nuxt generate command more than once? Not sure how I can login to a sandbox to debug more, but locally I cannot reproduce this issue.

So I am quite sure this is not a Nuxt issue. Lowering the concurrency to `10` does seem to help, but not sure how/why as the generate command might run more than once anyway.

**Comment by Miaoxingren** [comment]
No, I found this issue both on my server(linux) and local compouter (windows). I also found out there are multiple node process while `generate` command is compiling bundles, and after compiling `√ Generated` log shown and node process minus to 3.

**Comment by pimlie** [comment]
Where do does worker-farm childs come from? What kind of sandbox are you running?

When I locally generate a project I only have one node process during generation and that is not running as a worker-farm child.

**Comment by Miaoxingren** [comment]
Just the Nuxtjs template codesandbox provided on create sandbox.

I created a totally new project by `npx create-nuxt-app test-nuxt`. Then I just add one page `user/_id.vue` in this project and add the following code on `nuxt.config.js`, no other change to this project:
```
generate: {
    routes: function() {
      var i = 0;
      var arr = [];
      while (i++ < 10000) {
        arr.push("/user/" + i);
      }
      return Promise.resolve(arr);
    }
  }
```
1. make sure there is no other node process
![1](https://github.com/Miaoxingren/webpack-issue-8934/blob/master/src/assets/1.png?raw=true)

2. run generate command
![2](https://github.com/Miaoxingren/webpack-issue-8934/blob/master/src/assets/2.png?raw=true)
![3](https://github.com/Miaoxingren/webpack-issue-8934/blob/master/src/assets/3.png?raw=true)

7 node process when compiling and then minus to 2.

3. after all page generated
![4](https://github.com/Miaoxingren/webpack-issue-8934/blob/master/src/assets/4.png?raw=true)

Zero node process after `generate` finished.

**Comment by pimlie** [comment]
Wow, thanks for taking the time to submit all those screenshots!

The worker-farm stuff is just webpack, its expected to see those processes during the (webpack) build phase of generating your project. When Nuxt starts generating all the pages, those worker-farm processes should've disappeared.

Back to your OOM, I cant seem to reproduce that with the csb reproduction you posted. Isnt that just something in your code?

**Comment by Miaoxingren** [comment]
There's no OOM in the codesandbox demo. My OOM was casued by too many node processs (about 30 and my server didn't have that much memory), I was wondering why there are so much node process so I created the csb demo to find out where all those node process come from. Maybe something is wrong with my webpack config.

**Comment by pimlie** [comment]
Could you try to just run `nuxt build` and see what happens? Is your nuxt/webpack config the same as in your repro or is it different? If so please post it as well. Eg have you maybe configured to use [build.parallel](https://nuxtjs.org/api/configuration-build#parallel)?

**Comment by Miaoxingren** [comment]
I got this waring when using `build.parallel`:
```
 WARN  extractCSS cannot work with parallel build due to limited work pool in thread-loader.
```

I noticed that node process increasing with pages/modules to build, I trying to found out an optimization.

**Comment by Miaoxingren** [comment]
I found config option relative to the number of node process.
When I set `build.terser.parallel` to false, there will be only one node process.
According to the [document](https://github.com/webpack-contrib/terser-webpack-plugin#parallel), number of node process is `os.cpus().length - 1`, but actually more than that.

**Comment by Miaoxingren** [comment]
@pimlie Tks for your helps. I found the [solution](https://github.com/webpack-contrib/terser-webpack-plugin/issues/115#issuecomment-520727577).
