### ISSUE TITLE
using @nuxtjs/vuetify module scrollBehavior not working...

### ISSUE THREAD

**Issue by ksbgenius** [nuxt/nuxt.js#6111]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/embed/nuxtjs-vuetify-5enxn](https://codesandbox.io/embed/nuxtjs-vuetify-5enxn)

### Steps to reproduce

npx create-nuxt-app <project-name>

and i select

vuetify, axios, pwa, eslint, ssr

in nuxt.config.js

router: {
    scrollBehavior: function (to, from, savedPosition) {
      console.log(to)
      console.log(from)
      console.log(savedPosition)
      return { x: 0, y: 0 }
    }
  }

console.log show error

and when

yarn dev or yarn build

in .nuxt directory
router.js file
show unknown string in scrollBehavior

check this

### What is expected ?

scrollBehavior

### What is actually happening?

![스크린샷, 2019-07-23 15-46-51.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/acfb2750-ad15-11e9-9b7d-61cf2a83b3e5.png)

in .nuxt/router.js
this is using @nuxtjs/vuetify scrollBehavior
this image show unknown string in scrollBehavior
![1111111.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d0f7c8a0-ad1c-11e9-9b7d-61cf2a83b3e5.png)

in .nuxt/router.js
this is not using @nuxtjs/vuetify scrollBehavior
this image not show unknown string in scrollBehavior
![222222.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2f3bdd20-ad1d-11e9-9b7d-61cf2a83b3e5.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9534">#c9534</a>)</em></sub></div>

**Comment by ksbgenius** [comment]
and
when yarn dev or yarn build

in .nuxt
rotuer.js file scrollBehavior
unknown string show

![1111111.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/ad2dcbe0-ad1c-11e9-9b7d-61cf2a83b3e5.png)

**Comment by manniL** [comment]
Could you track down with which module the issue persists? Is it solely `@nuxtjs/vuetify`?
