### ISSUE TITLE
Vue is not bundled when required by UMD lib on the client side.

### ISSUE THREAD

**Issue by Fnxxxxo** [nuxt/nuxt.js#6112]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/Fnxxxxo/nuxt-client-import-issue.git](https://github.com/Fnxxxxo/nuxt-client-import-issue.git)

### Steps to reproduce

```
yarn install && yarn start
```
Then check console logs.

### What is expected ?

Component is rendered with no errors.

### What is actually happening?

Server-side renders correctly. Client-side fails with calling extend of undefined.

### Additional comments?

The same demo works in the raw Vue-cli project.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9536">#c9536</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@Fnxxxxo Could you provide me the vue-cli repo which works fine ?

**Comment by Fnxxxxo** [comment]
@clarkdo Hi. I update the reproduction repo with a successful Vue-cli demo. Just `yarn install` and `yarn serve`

**Comment by clarkdo** [comment]
Please try, webpack resolves symlinks as relative path instead of node_module path:

```js
  build: {
    /*
    ** You can extend webpack config here
    */
    extend(config) {
      config.resolve.symlinks = false;
    }
  }
```
