### ISSUE TITLE
Cannot read property toLowerCase of undefined

### ISSUE THREAD

**Issue by gotenxds** [nuxt/nuxt.js#6116]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://cmty.app](https://cmty.app)

### Steps to reproduce

Sorry for no repo as I'm not sure what is causing this but I'l do my best to explain what I found out
This issue is caused by the ssr trying to render the page and finding a comment block
![brave_2uQ9VVuJnD.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/46312b20-ada4-11e9-92cb-e7fd3667e54e.png)
![brave_n8Yrq1ABy1.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/9228cce0-ada4-11e9-92cb-e7fd3667e54e.png)
This comment appears under the __nuxt div:
![brave_EerK58t9i3.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/c2c960d0-ada4-11e9-92cb-e7fd3667e54e.png)

I have no idea why is this comment showing up there.

This is a random issue, as removing node modules and package.lock then reinstalling (might) fix this, or it might not, it might cause it, randomly.
Honestly I've been trying to solve this for the last 2 days and I'm about to lose my mind about that comment that just shows up and disappears every time

Please help and dont shun me for not opening a repo I just cant.

### What is expected ?

explained above

### What is actually happening?

explained above

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9537">#c9537</a>)</em></sub></div>

**Comment by Orozco93** [comment]
I have the same issue! Tried multiple workarounds, but I didn't have any luck.

**Comment by bradley-varol** [comment]
I've found that clearing localStorage removes this error so the nuxt@auth module may be responsible...

**Comment by manniL** [comment]
this usually happens when:

* Your HTML is invalid
* You use stateful markup (e.g. authentication state) on server and client side

If you do the latter, you canwrap all your auth checks in your markup in `NoSsr` components for a workaround.

It's a bit difficult to explain, but I'll write a bit up on that later.

**Comment by aldarund** [comment]
Your state should be same on ssr and client. See https://ssr.vuejs.org/guide/hydration.html

**Comment by Phojie** [comment]
Worked for me by wrapping it client-only tags

```
<template>

  <client-only>
           <common-layout class="default-layout">
               <header-component />
           </common-layout>
           <div v-if="SomeCondition">
                <custom-component />
           </div>
  <client-only>

</template>
```

**Comment by Mirjalol9797** [comment]
did not help. I tried wrapping the block with <client-only> </client-only>and <no-ssr></no-ssr> in both cases, nothing changed. Exit the same error

**Comment by SagarVishal** [comment]
> did not help. I tried wrapping the block with and in both cases, nothing changed. Exit the same error

Can show example, how you are trying!!

**Comment by Mirjalol9797** [comment]
[SagarVishal](https://github.com/SagarVishal)
for example, the page https://texnomart.uz/ru/page/vacancy
when refreshing the page or entering through a direct link, it does not work and displays an error

What am I doing

1 try to add client-only tag in 2 options both didn't work
first option
![image](https://user-images.githubusercontent.com/71864430/184879725-38847967-4387-487a-b8c5-bdc173890bd1.png)
second option
![image](https://user-images.githubusercontent.com/71864430/184880088-86b0d98c-a9fd-4233-ae0b-160a78870c9b.png)

used the no-ssr tag in several variants but did not help
1.
![image](https://user-images.githubusercontent.com/71864430/184880960-63455e21-bae9-4dea-8812-5d8fd97cd2e1.png)
2.
![image](https://user-images.githubusercontent.com/71864430/184881022-94f8382d-67d0-4d7b-9d7d-1e071a100993.png)
3.
![image](https://user-images.githubusercontent.com/71864430/184881069-40c51d07-5ad5-46b3-881e-3fe0db3c2682.png)

also tried these options
![image](https://user-images.githubusercontent.com/71864430/184881245-83be7655-7c0d-43ec-9e64-c46e892ddc89.png)
![image](https://user-images.githubusercontent.com/71864430/184881306-9bdaa0da-6710-438b-be47-427509fa854b.png)

but still didn't help
if you need data from the package.json file and nuxt.config.js I can send

**Comment by DiegoPerea** [comment]
Any luck with this issue?

I get it only when I reload the page. 

Tried all solutions above and it doesn't work. The only way I can get my page to work is going to the index page and then start navigating from there and then the page works just fine. But if i reload then i get this error.

Changed $fetch to $asyncData or even methods for fetching, but it doesn't work.

Tried wrapping the component in a v-if, to wait for the data to fetch. Didn't work either.

**Comment by mde4** [comment]
Tried all solutions above and it doesn't work.
Any luck with this issue?
