### ISSUE TITLE
CSS style render differ between SSR and SPA

### ISSUE THREAD

**Issue by Kyoloro** [nuxt/nuxt.js#6119]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/embed/codesandbox-nuxt-riukq](https://codesandbox.io/embed/codesandbox-nuxt-riukq)

### Steps to reproduce

- `npx create-nuxt-app nuxt-demo`

- add `DemoComponent.vue` to `components/`

- `DemoComponent.vue`

```html
<template>
  <div class="red-p"></div>
</template>
<style scoped>
.red-p {
  background-color: red;
  width: 50px;
  height: 50px;
}
</style>
```

- `pages/index.vue`

```html
<template>
  <DemoComponent class="blue-p" />
</template>

<style scoped>
.blue-p {
  background-color: blue;
}
<style/>
```

- open the website

- the first fragment page from SSR
![fragment-ssr.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/44a77c10-addf-11e9-92cb-e7fd3667e54e.png)

- then SPA Hydration
![spa-hydrain.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/486dabd0-addf-11e9-92cb-e7fd3667e54e.png)

### What is expected ?

SSR:
`<DemoComponent>` background-color: blue;

SPA:
`<DemoComponent>` background-color: blue;

### What is actually happening?

SSR:
`<DemoComponent>` background-color: red;

SPA:
`<DemoComponent>` background-color: blue;

### Additional comments?

is this a different render action of style-loader between SSR and SPA ?

thanks all.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9539">#c9539</a>)</em></sub></div>

**Comment by blowsie** [comment]
Possibly related:
https://github.com/nuxt/nuxt.js/issues/6084

**Comment by kevinmarrec** [comment]
@pimlie Could it be somehow related to `vue-meta` ? 🤔

**Comment by pimlie** [comment]
Nope, dont think so. This seems just the normal css flash in dev mode: https://nuxtjs.org/faq/css-flash#why-a-css-flash-appears-

**Comment by blowsie** [comment]
Still an issue i think

**Comment by pimlie** [comment]
@blowsie As mentioned in my previous comment, I dont think this is an issue. If you have proof or more info that there is an issue here then please share it. Otherwise we can close this issue probably

**Comment by lukasjuhas** [comment]
I can confirm this. We have a component library, where each component has it's own scoped styles. They do not work properly on SPA mode, or when using inside `<no-ssr>` block.

 @pimlie You are talking about something different. This is not just the flash, it's persistent.

**Comment by wspringer** [comment]
I'm experiencing the same thing. In my case, some elements do not get the `data-v-[hash]` attribute in SSR mode.
