### ISSUE TITLE
nuxt build  outputs chunk  file structure different in windows, linux and macOS causing Loading chunk {n} failed 

### ISSUE THREAD

**Issue by sudhakarselva** [nuxt/nuxt.js#6128]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### What is expected ?

![normal_output_windows.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/5687bea0-aed3-11e9-b286-f9b8539a5a7d.PNG)

### What is actually happening?

![filestructure_broken_into_folder_structues.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/69d53460-aed8-11e9-b286-f9b8539a5a7d.png)

### Additional comments?

same problem happens in heroku as well.so chunk failed error logging.

Please check screenshots between what is expected? and what is actually happening?.there you can see , In expected file name will be like 
(vendors.pages_admin_settings.pages_admin_users.pages_forgotPassword.pages_login.pages_profile.pages_.669fba28.js)
but in actually happening in mac and linux . it created folder like vendor.pages => admin =>some folder => 
![chunck_correct_name.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/4d0dd840-aed9-11e9-b286-f9b8539a5a7d.PNG)
profile.pages => .669fba28.js

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9551">#c9551</a>)</em></sub></div>

**Solution**:-
### If I name my files inside pages folder in lowercase, that error occurs , so camelcase solves it or ### other casing styles you can try

**Comment by manniL** [comment]
Could you please describe the issue with more words? I roughly see what's going wrong, but a detailed way of how to see which outcome would help.

**Comment by sudhakarselva** [comment]
Sorry.I will try to create codesandbox.
BTW here is whats happening

* when ever i run yarn build , In my system(windows 7) its building perfect (inside **.nuxt/dist/client** folder, files are created as shown in below images)

![1_build_correct](https://user-images.githubusercontent.com/45354048/62029779-2a8b6280-b201-11e9-9d03-26e2d3b13071.PNG)

* But in heroku(Linux) and my colleague(Mac OS), (inside **.nuxt/dist/client** folder **my file names are borken into folder names somehow please refer below image** )

![filestructure_broken_into_folder_structues](https://user-images.githubusercontent.com/45354048/62030185-30ce0e80-b202-11e9-8621-1e6c7d043637.png)

_Actual file name is something like this **vendors.pages_admin_settings.pages_admin_users.pages_forgotPassword.pages_login.pages_profile.pages_.669fba28.js** but it created like **vendors.pages/admin/users.pages/somenested folder /.669fba28.js** which causing chuck error in my college bulid _ 

Not sure why this error occurs , Is it OS related or something else.
FYI
*We have file called profile.js inside pages folder renamed to userProfile ,then it worked once.

**Comment by sudhakarselva** [comment]
Hi quick update on this one,
If I name my files inside pages folder in lowercase, that error occurs , so  camelcase solves it or other casing styles you can try

**Comment by hzpeng57** [comment]
I have a problem.
I run `npm run build` on windows，and upload the packaged file to the server. I can run it successfully. But when I run `npm run build` on MacOS, and upload the packaged file to the server. After I run `npm run start` the page will report an error about lose not finding a js file.
I found that I had succeeded by removing the capital letters from the page file name
