### ISSUE TITLE
Duplicate Data Attributes

### ISSUE THREAD

**Issue by aminnairi** [nuxt/nuxt.js#6129]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/aminnairi/bootstrap-vue-duplicate-data-attributes](https://github.com/aminnairi/bootstrap-vue-duplicate-data-attributes)

### Steps to reproduce

https://github.com/aminnairi/bootstrap-vue-duplicate-data-attributes/blob/master/README.md

### What is expected ?

The source-code should not contain duplicate data attributes when using Bootstrap Vue.

### What is actually happening?

The source-code contains duplicate data attributes when using Bootstrap Vue.

### Additional comments?

See https://github.com/bootstrap-vue/bootstrap-vue/issues/3753 for an upstream of this issue.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9553">#c9553</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @aminnairi i don't know if this is a bug
This occurs when using `<style scoped>`
Without `nuxt` this also happens

**Comment by aminnairi** [comment]
@ricardogobbosouza Thansk for the insight. Does that mean that this is a Vue.js bug?
