### ISSUE TITLE
Why Nuxt make API calls from static generated page?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#613]
I used async-data example, but add parameters in `nuxt.config.js`:

```
  generate: {
    routes: function () {
      return axios.get(`https://jsonplaceholder.typicode.com/posts/`)
      .then((res) => {
        return res.data.map((post) => {
          return '/posts/' + post.id
        })
      })
    }
  }
```
Now Nuxt creating 100 pages with `nuxt generate`, but they still make API calls to https://jsonplaceholder.typicode.com/posts.

How to make Nuxt fetch the data and not depend to external API after generate?

**Comment by Atinux** [comment]
It's not possible @kodekrendel 

The point of generate is to generate the pages to host it on any CDN. But it's still a web application which fetch the data from the API.

I you don't want API call, you can use normal link (`<a>` instead of `<nuxt-link>`), then it will ask the browser to get the corresponding route.

**Comment by kodekrendel** [comment]
Thanks @Atinux 
Hm, then why generated files contain all data from API already? I just checked, all 100 files has fetch data from API.

The point is, I wanted to have my development API and not to expose it in public - just use this API server on `generate` process.

**Comment by Atinux** [comment]
Why don't you want to expose your API in public @kodekrendel ?

**Comment by kodekrendel** [comment]
For example, it's running on local machine. Or I am managing 10 Nuxt sites from 1 API server, and doesn't want for enduser see that it's somehow connected.

**Comment by ausir0726** [comment]
http://nuxtjs.org is generate from local api server ( nuxt doc )
is this you want ?

**Comment by ausir0726** [comment]
oppps ...  sorry 

seems it also have a public doc api server

**Comment by kodekrendel** [comment]
Yes, it still will make calls to local server, although all data is in generated pages.

**Comment by alexchopin** [comment]
The point to generate pages with data inside is to escape the first API call (and SEO benefits of course) when a page is loaded from the server-side.

**Comment by ausir0726** [comment]
@kodekrendel 
see this link https://nuxt-without-client-fetch.surge.sh/

Is this you want ? this demo just fetch data on SSR .
but you will lose SPA advantage ...

**Comment by ausir0726** [comment]
but, I think it also a good use with nuxt.js

It can just generate 100 pages in a minute , host a static website without api server .
If we don't need SPA .

**Comment by kodekrendel** [comment]
@alexchopin now I got it. Then it of cause not worth it. Thanks for clarifying! 

@ausir0726 thanks for cool example! Was it hard to implement? It definitely worth to have in mind that we can use Nuxt this way. It's not what I expected (I love SPA), but still interesting feature.

**Comment by ausir0726** [comment]
@kodekrendel  It's easy .

I push source on my repo https://github.com/ausir0726/nuxt-without-client-fetch

if you need SPA , you need a public API server , even just a json file at your same site .

**Comment by kodekrendel** [comment]
@ausir0726 thank you, very helpful!

**Comment by ausir0726** [comment]
I have another idea resolve you want , and I have used on my project .
( just done about 50% )

you can write a simple tool ( maybe use node.js )
fetch you api server and convert it to js moudle 
like .
```
export defualt [
  { id: 1 },
  { id: 2 }
];
```
and you can import it on your vue file . and use it in data or asyncData .
this way will increase your js file size ...
( that will require that module in you bundle.js ) 

but you don't need a online api server ( even json ) and keep SEO and SPA working fine .

this is our dev project , if someone link this got empty page , that I remove it .
http://dev.finpo.com.tw/nitori.com.tw/
this project I use generate , and without axios . ( but have something like CMS )

**Comment by kodekrendel** [comment]
@ausir0726 nice solution. I need to have this tool on my Nuxt host, right? Since I want Nuxt to fetch the data from external resource and create this module locally. And I need to trigger this process automaticly with `generate`. Seems like an interesting task, will try to implement this in spare time. Thanks for the tip (again)!

**Comment by ausir0726** [comment]
yes , 

whole process like the following

1. trigger your tool ( write a cron or make a api for trigger .. anyway... )
2. fetch api with axios covert to js module ( use fs write to you nuxt.js project )
3. trigger your nuxt generate
4. re-publish your dist folder 

if you can import js data module , that will no need axios on SSR or CSR .
