### ISSUE TITLE
error NuxtServerError: Cannot stringify a function

### ISSUE THREAD

**Issue by WisdomEye** [nuxt/nuxt.js#6132]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

This error is same of:

https://github.com/nuxt/nuxt.js/issues/4026

The link above says its fixed, but seems not...

My setup:

nuxt.config.js

```javascript
const i18n = require('./config/locales');

modules: [
['nuxt-i18n', i18n],
]
```

config/locales/index.js

```javascript
module.exports = {
	locales: [
		{
			code: 'br',
			iso: 'pt-BR',
			name: 'Português Brasil',
			file: 'pt-BR.json'
		},
		{
			code: 'en',
			iso: 'en-US',
			name: 'English',
			file: 'en-US.json'
		}
	],
	defaultLocale: 'br',
	seo: true,
	lazy: true,
	detectBrowserLanguage: {
		cookieKey: 'redirected',
		useCookie: true
	},
	langDir: 'config/locales/',
	parsePages: false,
	pages: {},
	vueI18n: {
		fallbackLocale: 'en'
	}
};
```

config/locales/en-US.json

```javascript
{
	"actions": "Actions",
	"yes": "Yes",
	"no": "No",
	"edit": "Edit",
	"password": "Password",
	"password_confirm": "Confirm Password",
	"login": "Log In",
	"forgot_password": "Forgot Password?",
	"remove": "Remove",
	"destroy_confirm_title": "Please Confirm",
	"destroy_confirm": "Are you sure you want to remove this?",
	"logout": "Log Out",
	"back": "Back",
	"save": "Save",
	"update": "Update",
	"forms": {
		"errors": {
			"required": "Please fill this out.",
				"standard": "A server error occurred."
		}
	},
	"cars": {
	"singular": "car",
		"plural": "cars",
		"new": "New Car",
		"edit": "Edit Car"
	}
}
```

config/locales/pt-BR.json

```javascript
{
	"actions": "Ações",
	"yes": "Sim",
	"no": "Não",
	"edit": "Editar",
	"password": "Senha",
	"password_confirm": "Confirmar Senha",
	"login": "Logar",
	"forgot_password": "Esqueceu sua Senha?",
	"remove": "Remover",
	"destroy_confirm_title": "Por favor Confirme",
	"destroy_confirm": "Você têm certeza que quer remover?",
	"logout": "Log Out",
	"back": "Voltar",
	"save": "Salvar",
	"update": "Atualizar",
	"forms": {
		"errors": {
			"required": "Por favor preencha todos os campos.",
			"standard": "Um erro ocorreu no servidor."
		}
	},
	"cars": {
		"singular": "carro",
		"plural": "carross",
		"new": "Novo Carro",
		"edit": "Editar Carro"
	}
}
```

store/layout/index.js

```javascript
import actions from './actions';
import mutations from './mutations';
import getters from './getters';

export const state = () => ({
	topBar: false,
	topBarID: null,
	navBar: false,
	navBarId: null,
	getters,
	mutations,
	actions
});
```

store/layout/getters.js

```javascript
export default {
	useTopBar(state) {
		return state.topBar;
	}
};
```

### What is expected ?

An update removing the flood of messages on server about:

Cannot stringify a function useTopBar

Or

An step by step how to fix it.

### What is actually happening?

On every page load the server its flooded with a lot of messages:

Cannot stringify a function useTopBar

And many other values on vuex

### Additional comments?

Seems there an fix on this link, but dindt get how to apply:

https://github.com/vuex-orm/vuex-orm/issues/255

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9557">#c9557</a>)</em></sub></div>

**Comment by aldarund** [comment]
You cannot have functions in your state. They cant be serialized. So the solution is not to have any functions or non pojo in your state.
Why do you have actions/getters and mutations inside your state?

**Comment by manniL** [comment]
Could be related to lazy loading i18n languages as well IIRC :thinking:

**Comment by WisdomEye** [comment]
Would be possible get an example how to deal with store without functions?

**Comment by manniL** [comment]
It is **not** related to i18n, but to 

```js
export const state = () => ({
	topBar: false,
	topBarID: null,
	navBar: false,
	navBarId: null,
	getters,
	mutations,
	actions
});
```

What you want is exporting state, getters, actions and mutations separately.

See https://github.com/nuxt/nuxt.js/pull/4923/files as an example :relaxed:

**Comment by WisdomEye** [comment]
If I understand the example correctly, I have did:

store/layout/index.js

```javascript
import actions from './actions';
// import mutations from './mutations';
import getters from './getters';

export const state = () => ({
	topBar: false,
	topBarID: null,
	navBar: false,
	navBarId: null,
	getters,
	// mutations,
	actions
});

export const mutations = {
	setTopBar(state, params) {
		state.topBar = params;
	}
};

```

But the error persist, occour less times this way.

**Comment by manniL** [comment]
Apply the same for getters and actions.

**Comment by WisdomEye** [comment]
Theres nothing on getters and actions, just have posted about them to show the desire skeleton for development.

And the error says about the setTopBar:

Cannot stringify a function setTopBar

Would be the way I set it? I am using on one page:

```javascript
	async fetch ({ store, params }) {
		await store.commit('layout/setTopBar', true);
	},
```

**Comment by WisdomEye** [comment]
Have tested again, this time with empty getters and actions on same file, and the error is gone, example:

```javascript
export const state = () => ({
	topBar: false,
	topBarID: null,
	navBar: false,
	navBarId: null
});

export const actions = {
};


export const mutations = {
	setTopBar(state, params) {
		// newNumber is the payload passed in.
		state.topBar = params;
	}
};

export const getters = {
};

```

I have no idea why works this way since actions and geteers was empty, but, I will work using your solution.

Thank for the help and patience.
