### ISSUE TITLE
How to add the static json file in generate function in order to create the dynamic routes from Json file

### ISSUE THREAD

**Issue by roshandev96** [nuxt/nuxt.js#6136]
`generate: {
    routes: function () {
      return axios.get("./static/subcategories.json")
      .then((res) => {
        return res.data.map((items) => {
          return '/items/' + items.id
        })
      })
    }
  },`

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9560">#c9560</a>)</em></sub></div>

**Comment by galvez** [comment]
Trying using `require()` instead of `axios.get()` for this case, since the file seems to be readily available.

**Comment by roshandev96** [comment]
@galvez Thanks for your response . can you please share the code if possible
