### ISSUE TITLE
Confusing about the generator usage in Nuxt.js

### ISSUE THREAD

**Issue by mamboer** [nuxt/nuxt.js#614]
Hi, guys,

I found that Nuxt.js adopts the es6 generator feature at many places like https://github.com/nuxt/nuxt.js/blob/master/lib/build.js#L112 , 
but i can't figure out why .

Is it appropriate to use generators like that ? Converting them into promises via `co` when they're being called ? Why not just use promises directly and make the code base more readable ?

Any explanations and comments would be appreciated 😀, thanks.

**Comment by tadejstanic** [comment]
Glad to see that someone else has the same questions as I do. 

I really like nuxt and its proposed conventions but comparing source code with the similar project [ream](https://github.com/ream/ream) I found it less readable. For sure this is just my opinion. But I'd also like to hear what are the reasons behind for using generators with `co` and not native promises with async/await?

**Comment by Atinux** [comment]
Actually, I wrote the code using generators before implementing async/await.

If you take a look at [our roadmap](https://github.com/nuxt/nuxt.js/projects/1), we have a todo to refactor the code using async/await.

Glad to see people looking at the source code :smiley:
