### ISSUE TITLE
Form component added directly to layout + Netlify forms not playing well together

### ISSUE THREAD

**Issue by dugajean** [nuxt/nuxt.js#6141]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/dugajean/netlify-bug-reproducer](https://github.com/dugajean/netlify-bug-reproducer)
[https://wonderful-lichterman-bd8127.netlify.com/](https://wonderful-lichterman-bd8127.netlify.com/) (View browser console)

### Steps to reproduce

1. Deploy the provided repository to Netlify
2. Go to the link
3. Watch it crash and burn (Open browser console)

### What is expected ?

Nuxt should work with [Netlify forms](https://www.netlify.com/docs/form-handling/) properly

### What is actually happening?

When adding `data-netlify="true"` to a form, the app crashes. I believe this happens only when using components within layouts. Doesn't happen when components are placed in pages.

### Additional comments?

I'm not sure whose fault this is: Nuxt's or Netlify's. Either way, I'm reporting it here so it can gain some attention.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9564">#c9564</a>)</em></sub></div>

**Comment by pimlie** [comment]
I have seen more issues being reported about netlify forms, maybe you could do a search and see if any of those issues helps.

Could you try to deploy in dev mode to netlify? The current deployment seems to be in production mode and although its ok to see there is an error its a bit difficult to find out a bit more about it.

**Comment by dugajean** [comment]
@pimlie Could you tell me how to deploy in dev mode? I can't find that anywhere.

This seems like a clear bug though, even if it was reported in the past, it means that it was never fixes. I have a very basic environment, can't get simpler than that, and the issue is happening on a clean installation. It definitely needs to be fixed imo. Sorry if I can't be of much help here as I'm not a a proper JS developer.

**Comment by dugajean** [comment]
@pimlie Anything new on this? I'd appreciate some feedback or advice.

**Comment by pimlie** [comment]
See: https://nuxtjs.org/api/configuration-generate#devtools

But as I dont use netlify forms myself I am not too invested in this issue. Please try to debug this yourself a bit more. Happy to help/guide form the sideline though.

**Comment by dugajean** [comment]
Oh well, that's a shame. I'm not interested in fixing this issue either since it wont affect me too much either. It's here though in case the nuxt community strives for a more bug-free framework. Until then, I'll be checking other alternatives.

Thanks for your time.

**Comment by manniL** [comment]
@dugajean Hey :wave: 	it works fine with https://github.com/shortdiv/netlify-nuxt-forms :relaxed:

**Comment by dugajean** [comment]
Hi @manniL It is a framework issue. Because as you can see, I managed to reproduce the bug in a clean installation with minimal code. But yeah, it's your choice whether you want it fixed or not. Not much I can do here. 

I can't respect a community that doesn't take issues seriously.

**Comment by manniL** [comment]
@dugajean You are judging "all of the community" quiet quickly, Dukagjin. Alleging that we "simply don't care" is also not the nicest move, especially as all core team members are trying their best to triage issues, fix bugs, bring out new features and so on.

But sometimes resource management isn't as easy as one would think and support from the bug reporters is always highly appreciated. :man_shrugging:

**Comment by manniL** [comment]
PS: I've tried to reproduce it but it did not work out. Check https://codesandbox.io/s/netlify-nuxt-forms-itzel (or https://csb-itzel.netlify.com/ while it is up)

**Comment by dugajean** [comment]
Thanks for your time.
