### ISSUE TITLE
CSS Modules options do not work except localIdentName

### ISSUE THREAD

**Issue by myparsec** [nuxt/nuxt.js#6143]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://nuxtjs.org/api/configuration-build#loaders-css-and-loaders-cssmodules](https://nuxtjs.org/api/configuration-build#loaders-css-and-loaders-cssmodules)

### Steps to reproduce

Add multiple options to the cssModules loader in nuxt.config.js

```
build: {
    extend (config, ctx) {},
    loaders: {
	cssModules: {
		localIdentName: '[local]_[hash:base64:4]', //Work
		modules: true, //Not work
		hashPrefix: 'my-custom-hash' //Not work
	}
     }
}
```

### What is expected ?

I wanted to get a classname `<div class="my-custom-hash_local_e23d">Element</div>`

### What is actually happening?

Adding and removing all of these options does not affect the result. Except localIdentName.
 `<div class="local_e23d">Element</div>`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9566">#c9566</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Since css-loader v3 has moved cssModule related config to `modules`, so please use:

```js
  loaders: {
    cssModules: {
      modules: {
        localIdentName: '[local]_[hash:base64:4]',
		modules: true,
		hashPrefix: 'my-custom-hash'
      }
    },
  }
```

**Comment by myparsec** [comment]
This not work

**Comment by clarkdo** [comment]
Please provide a reproducible repo.

**Comment by myparsec** [comment]
https://github.com/myparsec/CSS-Modules-not-work

**Comment by clarkdo** [comment]
Hi @myparsec , sorry that `css-loader v3` upgration is still not released yet.

And your first config works fine, I think you may misunderstand the `moudles` and `hashPrefix`.

By default, `css-loader` generates `hash` from the webpack request like `genHash('components/G-TheThemeSwitcher.vue+TheThemeSwitcher__switch')`, `hashPrefix` is for adding a prefix (like salt) for generating more unique hash like `genHash('my-hashcomponents/G-TheThemeSwitcher.vue+TheThemeSwitcher__switch')`.

About the `modules: true`, it will enable localIdent generation, so if your class has been converted to `localIdentName`, it means `modules: true` already works.

**Comment by myparsec** [comment]
Oh, I get it, thanks.
I decided that the hashPrefix is added to the hash in the classname. Thanks again.
