### ISSUE TITLE
serve-placeholder blocks potential routes matches

### ISSUE THREAD

**Issue by Livog** [nuxt/nuxt.js#6148]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://zq95y.sse.codesandbox.io/](https://zq95y.sse.codesandbox.io/)

### Steps to reproduce

Open the codesandbox link and click on "view JSON file" button then refresh the page.

### What is expected ?

Ideally would be to get served the matched route if there is one. Otherwise, check for a file in the static folder, and if that's not the case we would get served a serve placeholder.

### What is actually happening?

If any path ends with any matching serve placeholder(could be `.json`) type we instantly get the placeholder even if there is a matching route.

### Additional comments?

Of course, we could add this to the nuxt.config to solve the problem. But it just deactivates the serve-placeholders. Would be nice to be available to have the serve placeholders AND be available to create routes that can end with .json or .svg.
```
render: {
    fallback: {
      static: { 
        handlers: {
          '.htm': false,
          '.html': false,
          '.json': false,
          '.svg': false
        }
      }
    }
  }
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9570">#c9570</a>)</em></sub></div>

**Comment by pimlie** [comment]
Probably better to create a feature request in the [serve-placeholder repo](https://github.com/nuxt/serve-placeholder) to be able to exclude a certain path. Shouldnt be that difficult to add, so feel free to submit a PR :)

**Comment by pi0** [comment]
It is strange that you are serving an HTML page (vue file `pages/edit/_file.vue`) with `.json` extension as Nuxt's response is HTML anyway. It would be a better idea to use a server middleware or static asset inside `static/`.

---

BTW if for any reason you want routes ending with `.json` but serving HTML, it is possible to simply disable fallback using `nuxt.config.js`: ([docs])(https://nuxtjs.org/api/configuration-render#fallback)

```js
  render: {
    fallback: {
      static: false
    }
  },
```

Or if you want to only allow `.json` for routes: ([docs](https://github.com/nuxt/serve-placeholder#handlers))

```js
  render: {
    fallback: {
      static: {
        handlers: {
          ".json": false
        }
      }
    }
  },
```
