### ISSUE TITLE
Vue route

### ISSUE THREAD

**Issue by murilolivorato** [nuxt/nuxt.js#6152]
Hello , I am new here in Nuxt , this is amazing framework , I have been enjoying working with Nuxt .
congratulation for those who have created this .
well , I just didn like  the fact of dont work with routes , like vue routes .
developers how are used to work with some some frameworks such as Laravel , they miss this features .
Is there any way to implement routes like Vue route , in NUXT ?
like this -
```
  routes: [
    {
      path: '/',
      name: 'introduction',
      component: Introduction
    },
```
I think for large projects , it helps a lot you have a route , It showd have a option to set it , if you what to work with routes or not . 
Thanks

**Comment by SujithJr** [comment]
Hi @murilolivorato , then you are looking for nuxt-community router module https://github.com/nuxt-community/router-module?source=post_page .

**Comment by murilolivorato** [comment]
hello @SujithJr  , perfect .
Thanks
