### ISSUE TITLE
NuxtServerError - Cannot find module ... index.js...

### ISSUE THREAD

**Issue by manastalukdar** [nuxt/nuxt.js#6157]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/manastalukdarpersonalwebsite-qxbek](https://codesandbox.io/s/manastalukdarpersonalwebsite-qxbek)

Git repo for above codesandbox repro if anyone wants to clone locally and try:
https://github.com/manastalukdar/manastalukdar.github.io

Please note that this issue only happens on a Linux machine.

### Steps to reproduce

Run `npm run dev`

### What is expected ?

Website loads without errors.

### What is actually happening?

NuxtServerError
Cannot find module 'src/components/pages/index.js' from '/sandbox'

### Additional comments?

Appears similar to: https://github.com/nuxt/nuxt.js/issues/5132

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9575">#c9575</a>)</em></sub></div>

**Comment by pimlie** [comment]
Thanks for the reproduction link but as it doesnt use the codesandbox template with rate-limiting its not really usable. Could you please create a minimal reproduction using the nuxt template on csb?

In general my question would be, why? Why do you want to differ from the standard nuxt folder structure like you are doing? Whats the benefit except for finding issues like this? ;)

**Comment by manastalukdar** [comment]
@pimlie New repro using the nuxt template on cbs: https://codesandbox.io/s/codesandbox-nuxt-p43g5

You were indeed thinking in the right direction. The issue appears to be due to custom directories. I was able to repro the issue using the standard nuxt template on csb simply by using custom directories. It is strange through that this happens only on a Linux machine. I do not know if it also happens on Mac OS. It definitely does not happen on a Windows machine.
