### ISSUE TITLE
Web Worker Example broken with Nuxt 2.8.1?

### ISSUE THREAD

**Issue by DDevine** [nuxt/nuxt.js#6158]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/DDevine/nuxt-webworker-bug](https://github.com/DDevine/nuxt-webworker-bug)

### Steps to reproduce

Create a nuxt PWA using create-nuxt-app

Follow the official example as shown at: https://github.com/nuxt/nuxt.js/tree/dev/examples/web-worker

Make small code style changes to make the linter pass (example needs updating), and rename the default Logo.vue to AppLogo.vue

run `npm run dev`

### What is expected ?

The client should build and be served (on localhost:3000).

### What is actually happening?

The client builds with the following warning:

 WARN  in ./plugins/inject-ww.js                                                                               friendly-errors 14:45:25

"export 'default' (imported as 'ExampleWorker') was not found in '~/assets/js/Example.worker.js'

And in the browser debugger the following error stops the app from loading:

Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

![bug.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/f39c0bd0-b287-11e9-b44b-2b17a4c8d673.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9576">#c9576</a>)</em></sub></div>

**Comment by sc-laurence** [comment]
Sorry but what is the fix for this?

**Comment by DudaevAR** [comment]
`yarn upgrade --latest` fix this problem

**Comment by luisfrocha** [comment]
I get the same thing right now, but no output in the console, but I'm on Nuxt 2.11.0. After a while or a lot of tinkering, though, it eventually refreshes and loads the content *shrug*
![nuxt not loading](https://user-images.githubusercontent.com/7130389/77675180-970a5d00-6f5a-11ea-8652-2387be91f4c9.png)
