### ISSUE TITLE
problem using axios in Nuxt Js

### ISSUE THREAD

**Issue by whattocode** [nuxt/nuxt.js#6161]
The error said: has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Call in mounted method:
  mounted() {
    axios
      .get('https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=YEQUQKEHjX8&format=json')
      .then(response => (this.info = response))
  },

why? why it cannot access HttpRequest?

**Comment by Alakar-Nallavan** [comment]
![error1.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/c076e4a0-0df4-11ea-900d-3b8b982e6e94.PNG)

i am also face that type of error
