### ISSUE TITLE
Server side 'only' component shows error in development mode

### ISSUE THREAD

**Issue by LEE-WAN** [nuxt/nuxt.js#6163]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Steps to reproduce

```vue
<template>
  <div>
    <div v-if="isServer">
      normal client can not see this
      but BOTs can
    </div>
  </div>
</template>
<script>
export default {
  computed: {
    isServer() {
      return !process.client
    }
  }
}
</script>
```

### What is expected ?

show nothing to normal clients. but Bots (which do not perform javascript activity) can read this component.

### What is actually happening?

Warn in client-side browser

"[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>,or missing <tbody>. Bailing hydration and performing full client-side render."

and ignore them would cause an infinite refresh

### Additional comments?

It is for Search Engine Optimization.

server renders this component, so the bots can read the contents, but normal javascript enabled clients can not see this component.

it works fine in production mode. however, in development mode, it ruins everything.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9580">#c9580</a>)</em></sub></div>

**Comment by manniL** [comment]
Well, this is a bit more complicated than just checking for process.server/process.client

You'd need some counter part to the `ClientOnly` or `NoSSr` component.

PS: Showing content only for bots seems like a trick to deceive search engine crawlers and could be penalized by Google and co.
