### ISSUE TITLE
mini-css-extract-plugin & nuxt = The "path" argument must be of type string

### ISSUE THREAD

**Issue by jeffster9** [nuxt/nuxt.js#6167]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://github.com/jeffster9/test-mini-css-extract-plugin](https://github.com/jeffster9/test-mini-css-extract-plugin)

### Steps to reproduce

`# npx create-nuxt-app mini-css-extract-plugin-test`
? Project name mini-css-extract-plugin-test
? Project description test mini-css-extract-plugin
? Author name author
? Choose the package manager Npm
? Choose UI framework Bootstrap Vue < not sure if this is the issue?
? Choose custom server framework None (Recommended)
? Choose Nuxt.js modules Axios
? Choose linting tools eslint
? Choose test framework None
? Choose rendering mode Universal (SSR)

add mini-css-extract-plugin to nuxt.config.js

`# npm run dev`

### What is expected ?

CSS is extracted into separate files

### What is actually happening?

i Preparing project for development
i Initial build may take a while
√ Builder initialized

ERROR The "path" argument must be of type string. Received type undefined

at validateString (internal/validators.js:125:11)
at Object.extname (path.js:830:5)
at uniqBy_1.options.plugins.map (node_modules@nuxt\builder\dist\builder.js:5671:58)
at Array.map ()
at Builder.normalizePlugins (node_modules@nuxt\builder\dist\builder.js:5667:28)
at Builder.generateRoutesAndFiles (node_modules@nuxt\builder\dist\builder.js:5640:36)
at Builder.build (node_modules@nuxt\builder\dist\builder.js:5575:16)

### Additional comments?

I know this is not exactly a nuxt issue but the mini-css-extract-plugin is the solution proposed by nuxt to extract css into separate files but I cannot get past this error (The "path" argument must be of type string. Received type undefined). 

I have searched and tried various ways to resolve the issue with no success. 

Thanks in advance for your assistance. 

P.S. Loving Nuxt <3

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9584">#c9584</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @jeffster9 	:wave: 	

Have you tried using `extract-css-chunks-webpack-plugin`, which already comes with nuxt out of the box? 
See https://nuxtjs.org/api/configuration-build/#extractcss

**Comment by jeffster9** [comment]
I have now. Here's the gist of my current nuxt.config.js:

https://gist.github.com/jeffster9/2562288df68fbe672933a40258312f5d

However, I am still receiving the same error. 

 Preparing project for development                                                                           12:12:44
i Initial build may take a while                                                                              12:12:44
√ Builder initialized                                                                                         12:12:44

 ERROR  The "path" argument must be of type string. Received type undefined                                   12:12:44

  at validateString (internal/validators.js:125:11)
  at Object.extname (path.js:830:5)
  at uniqBy_1.options.plugins.map (node_modules\@nuxt\builder\dist\builder.js:5671:58)
  at Array.map (<anonymous>)
  at Builder.normalizePlugins (node_modules\@nuxt\builder\dist\builder.js:5667:28)
  at Builder.generateRoutesAndFiles (node_modules\@nuxt\builder\dist\builder.js:5640:36)
  at Builder.build (node_modules\@nuxt\builder\dist\builder.js:5575:16)

When I disable the `extract-css-chunks-webpack-plugin`, the app functions without issue.

**Comment by manniL** [comment]
You are adding the package to the `Nuxt plugin` array, instead of the webpack 'plugin one. See https://nuxtjs.org/faq/webpack-plugins/

**Comment by jeffster9** [comment]
*facepalm* Thank you! I'm still learning. Vue is my first experience w/ Webpack for about a year now. Apparently, I need to read the Nuxt manual again.
