### ISSUE TITLE
ERROR: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by adavie1** [nuxt/nuxt.js#6172]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://localhost](http://localhost)

### Steps to reproduce

Starting nuxt via npm run dev.

### What is expected ?

For the application to start.

### What is actually happening?

Compile errors on the server.

### Additional comments?

I've used 2 projects that rely on the latest version of Nuxt:

https://github.com/fritsvt/laravel-nuxt-authentication

and

https://github.com/cretueusebiu/laravel-nuxt

Both exhibit the same behavour when running Nuxt. Since this is a Nuxt error, I'm reporting here. I've already created in issue for each of these projects as well.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9592">#c9592</a>)</em></sub></div>

**Comment by manniL** [comment]
Not directly related to Nuxt but to your system watcher limits.


Try `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Please check https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for more info.

**Comment by ruslanubaydullayev** [comment]
worked, thanks
