### ISSUE TITLE
App crashing client side, Cannot read property '$scopedSlots' of undefined

### ISSUE THREAD

**Issue by fatlinesofcode** [nuxt/nuxt.js#6185]
Hi, we are encountering a strange issue with our site in production. We dont see this issue locally or in staging. The production site has multiple instances and is load balanced so perhaps related to that. The full error we get is : 

`2dc822786b86a274d024.js:2 TypeError: Cannot read property '$scopedSlots' of undefined
    at 2dc822786b86a274d024.js:2
    at prepatch (2dc822786b86a274d024.js:2)
    at $ (2dc822786b86a274d024.js:2)
    at 2dc822786b86a274d024.js:2
    at $ (2dc822786b86a274d024.js:2)
    at f.__patch__ (2dc822786b86a274d024.js:2)
    at f.t._update (2dc822786b86a274d024.js:2)
    at f.r (2dc822786b86a274d024.js:2)
    at xn.get (2dc822786b86a274d024.js:2)
    at xn.run (2dc822786b86a274d024.js:2)
te @ 2dc822786b86a274d024.js:2
TypeError: Cannot read property 'indexOf' of undefined
    at Ar (2dc822786b86a274d024.js:2)
    at Array.Sr (2dc822786b86a274d024.js:2)
    at x (2dc822786b86a274d024.js:2)
    at P (2dc822786b86a274d024.js:2)
    at P (2dc822786b86a274d024.js:2)
    at f.__patch__ (2dc822786b86a274d024.js:2)
    at f.t._update (2dc822786b86a274d024.js:2)
    at f.r (2dc822786b86a274d024.js:2)
    at xn.get (2dc822786b86a274d024.js:2)
    at new xn (2dc822786b86a274d024.js:2)`

Clicking through the to console the error seems to originate from nuxt/vue-app. Screenshots attached.

Any advise on how to debug this further ?

![Screen Shot 2019-08-05 at 2 34 34 pm](https://user-images.githubusercontent.com/505776/62439788-8cfbda00-b790-11e9-8954-0d33cdbd7885.png)
![Screen Shot 2019-08-05 at 2 31 47 pm](https://user-images.githubusercontent.com/505776/62439790-8cfbda00-b790-11e9-95df-76b01dc7bf7f.png)

**Comment by createlyn** [comment]
Any luck on this issue?

**Comment by fatlinesofcode** [comment]
not directly @createlyn But it looks like an issue with hydration so we'll optimised our JS execution time using techniques such as lazy-hydration and we haven't seen the error occur again.

**Comment by fatlinesofcode** [comment]
actually optimising the hydration did not fix it. We added some debugger logging info via Chrome and found the point at which it crashes.

![Screen Shot 2019-08-09 at 9 48 05 am](https://user-images.githubusercontent.com/505776/62746874-1e22c780-ba95-11e9-853f-a2ad528a1c95.png)

Looks like the IconSprite component is undefined in some scenarios and causes hydration to crash. This is component is a just an svg of shared icons. The root level tag is <svg> though ? I wonder if that is the issue

We have disabled hydration on this component now, so it ssr only. Hopefully that fixes it.

**Comment by jetaix** [comment]
@fatlinesofcode any news about your potential fix ? 🙏🏻

**Comment by fatlinesofcode** [comment]
yes @jetaix from memory i think the issue was a v-html on a script tag e.g.

`
<script type="application/ld+json" v-html="jsonld" />
`

we replaced with a head script
`
head () {
    return {     
      script: [ { innerHTML: this.jsonld, type: 'application/ld+json' } ],
      __dangerouslyDisableSanitizers: ['script']
    }
  }
`

**Comment by jetaix** [comment]
Ok thanks @fatlinesofcode, so no relation with IconSprite ?

**Comment by marko-mlinarevic** [comment]
@jetaix Did you find the solution... I have on a production, I get that error in nuxt console on server. It doesn't crash the app but it's an ugly error. It only appears once or two times a day max

**Comment by LeCoupa** [comment]
@marko-mlinarevic do you have a `v-html` on something other than a div like a `span` or a `script` tag or another element? This error happened to me because I had put it on a `span`. I can't explain why but by switching to a `div`, it fixed it.

**Comment by arg-1138** [comment]
I'm facing the same problem, as suggested @LeCoupa switching from `p` to `div` solved the issue. But still don't know why this happens.

Could be related to [this](https://github.com/nuxt/nuxt.js/issues/1523#issuecomment-325884055)? 

I was trying to nest some `div` inside a `p` (poor aproach).

**Comment by LeCoupa** [comment]
@arg-1138 yes this is what happens when you try to net a `div` inside a `p` element. As a rule of thumb, I only use `v-html` on `div` elements now.

**Comment by warlock1996** [comment]
facing the same , issue did anyone found out the real issue ? what is the reason

**Comment by danielroe** [comment]
@warlock1996 Previous users are reporting this is an issue of hydration, which in some cases is an issue of invalid HTML - you might try using something like https://html-validator.nuxtjs.org/.

**Comment by warlock1996** [comment]
thanks , ill try this
