### ISSUE TITLE
Be able to exclude 3rd lib files from babel-loader.

### ISSUE THREAD

**Issue by Miaoxingren** [nuxt/nuxt.js#6195]
### What problem does this feature solve?

`build.transpile` only exclude files from node_modules, but not files from src code like `src/libs/zepto.js`.

### What does the proposed changes look like?

Maybe `build.babel.exclude`？

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9610">#c9610</a>)</em></sub></div>

**Comment by clarkdo** [comment]
`build.transpile` is for including files from node_modules instead of excluding.

And I think `build.babel.exclude` should work since it will be passed to babel as [exclude](https://babeljs.io/docs/en/options#exclude) option.
