### ISSUE TITLE
ERROR  Renderer is loaded but not all resources are unavailable! Please check /.nuxt/dist/server existence.

### ISSUE THREAD

**Issue by HuangHuanHuan** [nuxt/nuxt.js#6196]
Nuxt+Koa,Local yarn dev, yarn build, yarn start is normal, running on the server will report an error, and there is /.nuxt/dist/server directory

nuxt : 2.8.1
Deployment target - nginx
Custom index.js file

package.json:
`{
  "name": "www.pandahelp.vip-android",
  "version": "1.0.0",
  "description": "My premium Nuxt.js project",
  "author": "huangjianli",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node server/index.js",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "koa": "^2.6.2",
    "nuxt": "^2.0.0"
  },
  "devDependencies": {
    "nodemon": "^1.18.9"
  }
}
`
index.js 
`const Koa = require('koa')
const consola = require('consola')
const { Nuxt, Builder } = require('nuxt')

const app = new Koa()

// Import and Set Nuxt.js options
const config = require('../nuxt.config.js')
console.log('app.env',app.env);

config.dev = app.env !== 'production'

async function start () {
  // Instantiate nuxt.js
  const nuxt = new Nuxt(config)

  const {
    host = process.env.HOST || '127.0.0.1',
    // port = process.env.PORT || 31017
    // port =  31017
  } = nuxt.options.server
  const port = 31017
  console.log('config.dev',config.dev);
  
  // Build in development
  if (config.dev) {
    //开发环境
    const builder = new Builder(nuxt)
    await builder.build()
  } else {
    //生产环境
    await nuxt.ready()
  }

  app.use((ctx) => {
    ctx.status = 200
    ctx.respond = false // Bypass Koa's built-in response handling
    ctx.req.ctx = ctx // This might be useful later on, e.g. in nuxtServerInit or with nuxt-stash
    nuxt.render(ctx.req, ctx.res)
  })

  app.listen(port)
  consola.ready({
    message: `Server listening on http://${host}:${port}`,
    badge: true
  })
}

start()
`
node_modules/nuxt/package.json
`{
  "_from": "nuxt@^2.0.0",
  "_id": "nuxt@2.8.1",
  "_inBundle": false,
  "_integrity": "sha512-y0XsKvusxmtWVsBB4kt+yA7+KoALPnUvkfLBxSy2kV2S1AudGNYAJK0IdUAP4xKd0QJSc9IzSDVat8UZi4FEQA==",
  "_location": "/nuxt",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "nuxt@^2.0.0",
    "name": "nuxt",
    "escapedName": "nuxt",
    "rawSpec": "^2.0.0",
    "saveSpec": null,
    "fetchSpec": "^2.0.0"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/nuxt/-/nuxt-2.8.1.tgz",
  "_shasum": "10a307e51973fa7b55abfeb41b84c76cbdd6f2f6",
  "_spec": "nuxt@^2.0.0",
  "_where": "/Users/huangjianli/www/www.pandahelp.vip-android",
  "bin": {
    "nuxt": "bin/nuxt.js"
  },
  "bugs": {
    "url": "https://github.com/nuxt/nuxt.js/issues"
  },
  "bundleDependencies": false,
  "collective": {
    "url": "https://opencollective.com/nuxtjs",
    "logoUrl": "https://opencollective.com/nuxtjs/logo.txt?reverse=true&variant=variant2"
  },
  "contributors": [
    {
      "name": "Sebastien Chopin",
      "url": "@Atinux"
    },
    {
      "name": "Alexandre Chopin",
      "url": "@alexchopin"
    },
    {
      "name": "Pooya Parsa",
      "url": "@pi0"
    },
    {
      "name": "Clark Du",
      "url": "@clarkdo"
    },
    {
      "name": "Jonas Galvez",
      "url": "@galvez"
    },
    {
      "name": "Alexander Lichter",
      "url": "@manniL"
    },
    {
      "name": "Dmitry Molotkov",
      "url": "@aldarund"
    },
    {
      "name": "Kevin Marrec",
      "url": "@kevinmarrec"
    },
    {
      "name": "Pim",
      "url": "@pimlie"
    }
  ],
  "dependencies": {
    "@nuxt/builder": "2.8.1",
    "@nuxt/cli": "2.8.1",
    "@nuxt/core": "2.8.1",
    "@nuxt/generator": "2.8.1",
    "@nuxt/loading-screen": "^0.5.2",
    "@nuxt/opencollective": "^0.2.2",
    "@nuxt/webpack": "2.8.1"
  },
  "deprecated": false,
  "description": "A minimalistic framework for server-rendered Vue.js applications (inspired by Next.js)",
  "engines": {
    "node": ">=8.0.0",
    "npm": ">=5.0.0"
  },
  "files": [
    "bin",
    "dist"
  ],
  "homepage": "https://github.com/nuxt/nuxt.js#readme",
  "keywords": [
    "nuxt",
    "nuxt.js",
    "nuxtjs",
    "ssr",
    "vue",
    "vue isomorphic",
    "vue server side",
    "vue ssr",
    "vue universal",
    "vue versatile",
    "vue.js",
    "vuejs"
  ],
  "license": "MIT",
  "main": "dist/nuxt.js",
  "name": "nuxt",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/nuxt/nuxt.js.git"
  },
  "scripts": {
    "postinstall": "opencollective || exit 0"
  },
  "version": "2.8.1"
}
`

**Comment by jarekcieslak** [comment]
I had similar issue and in my case it was rootDir in nuxt.config.js which was set to wrong value. Make sure you're pointing to a right folder. The error says that it's unable to locate .nuxt/dist/* files from where you run the command.

**Comment by HuangHuanHuan** [comment]
> I had a similar issue and in my case, it was rootDir in nuxt.config.js which was set to the wrong value. Make sure you're pointing to a right folder. The error says that it's unable to locate .nuxt/dist/* files from where you run the command.

Hello, could you tell me according to which rootDir is configured? Thank you

**Comment by Junwebnew** [comment]
I had a similar issue and in my case,  Did you fix it?

**Comment by noluckjustskill** [comment]
Same problem. How I can fix it?

**Comment by pairmix** [comment]
Same issue

**Comment by weihao** [comment]
Same issue
