### ISSUE TITLE
Key Events blocked / not working reliably

### ISSUE THREAD

**Issue by pju-** [nuxt/nuxt.js#6198]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-eczp4](https://codesandbox.io/s/codesandbox-nuxt-eczp4)

### Steps to reproduce

Open the codesandbox link or run yarn yarn create nuxt-app, create a default app.
Then add a basic `keypress` event handler on a page or component, e.g. like this:

```
  mounted() {
    console.info("mounted");

    window.addEventListener("keypress", e => console.info('keypress', e));
  }
```

Open the app, observe the devtools console output (in Codesandbox I had to open the browser devtools instead of the integrated one for better display).

### What is expected ?

Every keypress should trigger the event and appear in the console.

### What is actually happening?

The first event is triggered just fine, subsequent events are sometimes fired, more often not. Then after a while a whole bunch of console logs is printed at once.

### Additional comments?

The event handler code is fine, if you paste it in the console of a clear browser window it works just fine.
I tested it in the current version of Vue with vue-cli as well, no problem there. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9612">#c9612</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@pju- I tried with your codesandbox link, it seems working fine, could you provide me more details (like a GIF) about how to reproduce it ?

**Comment by pju-** [comment]
@clarkdo Thanks for checking it out. I can confirm that the bug can not currently be reproduced in codesandbox.

The alternative way still works: yarn create nuxt-app (with all options left as default), then add the keypress event handler on index.vue

A GIF would not be useful I think. You would just see that the key event triggers once, then only sporadically.

I did some more testing though: it seems that this is only a problem in dev-mode. If I build the project in any way (spa, generate, SSR) the key events trigger just fine.

**Comment by pimlie** [comment]
Although I can reproduce this issue, please note that the keypress event is [no longer recommended](https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event)

If I add a `keydown` event instead it does work. Actually if I add both keydown as keypress the keypress event keeps working as well.

**Comment by pju-** [comment]
@pimlie I can not confirm this – I'm running into the same problem with all the key events I tested, `keydown`, `kreypress`and `keyup`.

Tested in newest versions of Firefox and Chrome on OsX.

Do you want me to create a demo-repo?

**Comment by pimlie** [comment]
Only if it contains more than just the following basics from your previous repro. I tested with below and that just works:

```js
  mounted() {
    console.info("mounted");

    window.addEventListener("keydown", e => console.info('keydown', e));
    window.addEventListener("keypress", e => console.info('keypress', e));
  }
```

**Comment by pju-** [comment]
No, I'm afraid there would be nothing more in the repo.

I just did some more testing and this gets stranger and stranger (to me).

If I put both events like you did, they work just fine.
If I have only keydown, it won't work:

```js
  mounted() {
    console.info("mounted");

    window.addEventListener("keydown", e => console.info('keydown', e));
  }
```

This produces the unreliable behavior.

But if I do something like this:

```js
data() {
    return {
        content: ''
    };
},
mounted() {
    window.addEventListener("keydown", e => this.content += e.key);
    window.addEventListener("keydown", e => console.info('keydown', e));  
}
```

then the console logging will work only sporadically, but the content is updated on every keystroke regardless.

So I figure it must have something to do with the debug console logging, but as it's very much an edge case, this ticket can probably be closed?

**Comment by pimlie** [comment]
@pi0 Can you confirm that the rate limiting of messages by consola is also done on the client?

Cause when I switch tabs and press a key again it suddenly says `(repeated XX times)`.
