### ISSUE TITLE
auth0 example fails to generate

### ISSUE THREAD

**Issue by mindbits** [nuxt/nuxt.js#620]
I am getting the following error trying to generate the auth0 example from https://github.com/nuxt/example-auth0

TypeError: Cannot read property 'headers' of undefined
    at getUserFromCookie (server-bundle.js:1544:11)
    at module.exports.__webpack_exports__.default (server-bundle.js:2084:124)
    at promisify (server-bundle.js:1214:15)
    at promiseSeries (server-bundle.js:1195:10)
    at server-bundle.js:1840:96

Do Cookies require special build instructions? Or is this caused by something else?

**Comment by mindbits** [comment]
Sorry, I see that somebody already opened an issue at https://github.com/nuxt/example-auth0/issues/7

The steps to reproduce are fairly easy 

```
git clone https://github.com/nuxt/example-auth0.git
cd example-auth0
npm install
npm run build
npm run generate
```

As it's working without problems on https://nuxt-auth0.surge.sh I am wondering if the NUXT version used to generate the surge version was an older one and changes in the new NUXT version breaks it?

**Comment by Atinux** [comment]
Hi @mindbits 

It should work now, indeed, `req` does not exists when we run `nuxt generate`.

See my commit: https://github.com/nuxt/example-auth0/commit/d14b88f01d3c6d5b49c7d65435f93cd75ae1c3a9
