### ISSUE TITLE
How to handle data missing error while looping?

### ISSUE THREAD

**Issue by tomkochi** [nuxt/nuxt.js#6207]
I  fetch restaurant menu that looks like
```
items: [
  {
    iName: 'Item One',
    iDesc: 'This is the description of Item One.',
    prices: [
      {
        size: 'Small',
        price: 8,
      },
      {
        size: 'Medium',
        price: 12,
      }
    ]
  },
  {
    iName: 'Item Two',
    iDesc: 'This is the description of Item Two.',
    prices: [
      {
        size: 'Small',
        price: 8,
      },
      {
        size: 'Medium',
        price: 12,
      },
    ]
  },
  {
    iName: 'Item Two',
    iDesc: 'This is the description of Item Two.',
    prices: []
  }
]
```
And I show item names of the first item in the `prices` array along with price
```
<ul>
  <li v-for="item in items">
      {{ item.iName }} ------- {{ item.prices[0].price }}
  </li>
</ul>
```
Since the third item has empty `prices` array, it shows error
```
Cannot read property 'price' of undefined
```
How can I handle it.
_NB: there could be other missing data too in the api response - I need to track whatever exceptions/errors might occur._

**Comment by khalidzamer** [comment]
> This issue as been imported as [question](https://cmty.app/nuxt/nuxt.js/issues/c9619) since it does not respect [nuxt.js issue template](https://cmty.app/nuxt/issues/new?repo=nuxt.js). Only bug reports and feature requests stays open to reduce maintainers workload. If your issue is not a question, please mention the repo admin or moderator to change its type and it will be re-opened automatically. Your question is available at https://cmty.app/nuxt/nuxt.js/issues/c9619.

Hello, the link is invalid, can you guide on where to find the answer please?
