### ISSUE TITLE
Vue components are mounted multiple times but only on the production server 

### ISSUE THREAD

**Issue by cyanpix** [nuxt/nuxt.js#6208]
Vue components are mounted multiple times(only on the production server).

Hi,
I have this website https://colordesigner.io. I don't know why but components are mounted multiple times but only on the production server.
![obraz](https://user-images.githubusercontent.com/11429236/62821391-55b47100-bb74-11e9-99d5-84e7449e40e0.png)

Everything works correctly on the development server and when I use Browsersync in the dist folder.

On my website, I am using Nginx and Cloudflare. Auto minify for HTML, CSS, JS is disabled.

Do you have any idea?

**Comment by DannyEndert** [comment]
I do have the exact same problem!
