### ISSUE TITLE
Way to minify all bundle js files?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [nuxt/nuxt.js#621]
Hi,

I’m looking for a way to minify all bunfle js files on build. I couldn't figure what I’m missing here.

Here’s an example of what I tried (here with babili):

```javascript
build: {
	extend (config, { isDev, isClient }) {
		if (!isDev) {
			config.devtool = false
			config.plugins.push(
				new BabiliPlugin({
					// options here
				}, {
					comments: false
				})
			)
		}
	}
}
```
The build is correctly made, but has no effect on the bundles files. Another try with uglifyjs:

```javascript
build: {
	extend (config, { isDev, isClient }) {
		if (!isDev) {
			config.devtool = false
			config.plugins.push(
				new webpack.optimize.UglifyJsPlugin({
					parse: {
						strict: true
					},
					compress: {
						unsafe: true,
						warnings: false,
						drop_console:true
					},
					output: {
						comments: false,
						ascii_only: true
					},
					mangle: true
				})
			)
		}
	}
}
```

This is globally the last thing I need to get a good grade on PageSpeed: https://gtmetrix.com/reports/dev.emmanuelbeziat.com/OpP40maF

If anybody has a working example, it would surely help :) Thanks!

**Comment by ausir0726** [comment]
@EmmanuelBeziat  HI , I don't change any setting with nuxt.js default
and seems like my js already minify ...


<img width="1392" alt="latest_performance_report_for__http___dev_finpo_com_tw_nitori_com_tw____gtmetrix" src="https://cloud.githubusercontent.com/assets/7247064/25414995/89810660-2a67-11e7-8d82-6df2e14cc64d.png">

**Comment by EmmanuelBeziat** [comment]
Hi @ausir0726 

Strange thing… Is this because you’re using SSR and I use the static build?

**Comment by ausir0726** [comment]
this link is I am use nuxt generate static site ...

**Comment by ausir0726** [comment]
I'm sure default when nuxt production have UglifyJs ...
why you don't ?

**Comment by EmmanuelBeziat** [comment]
Well, I removed node_modules and reinstalled everything, and updated to nuxt 10.6, and it works now…

Thanks! :)

**Comment by ausir0726** [comment]
double A

so cool .

but , how can let google speed test get 100 point ?! @@ I never can't touch that ...

**Comment by EmmanuelBeziat** [comment]
I only hit 100 when I had a good old WordPress. Now I'm more around 96-99.

Most of time, it's about server configuration; I have a dedicated server that allow me to make the customizations I need.
