### ISSUE TITLE
Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by ouahibAbdou** [nuxt/nuxt.js#6214]
Hi, I'm using NuxtJS I have a problem when I want to go to the home page and I click in a button that uses vue-router to go to another page this problem show up
![image](https://user-images.githubusercontent.com/30089652/62826571-cb8cfc80-bbb5-11e9-8bb0-5b1b3d2348e0.png)

**Comment by gbgb66** [comment]
Hi. I faced the same problem. How did you solve it?

**Comment by jfaq89** [comment]
Me too. Anyone knows how to solve this?

**Comment by gbgb66** [comment]
I've solved this problem. 
It turned out that I used the reserved name "watcher" in the computed properties.

**Comment by wahibAbdou** [comment]
It's a fucking dark error I had to rewrite the code
