### ISSUE TITLE
Executing npm run dev with nuxt-edge running throws a few warnings in the console

### ISSUE THREAD

**Issue by connecteev** [nuxt/nuxt.js#6215]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://www.nourl.com](http://www.nourl.com)

### Steps to reproduce

This happens when you run nuxt-edge only....NOT 2.8.1

Executing ```npm run dev``` with nuxt-edge running throws a few warnings in the console.
THis is merely an annoyance, and not a blocker, but thought I'd be worth reporting.

### What is expected ?

No errors or warnings in the console should be seen.

### What is actually happening?

   See logs attached. Note that no pages are loaded. This is right on a fresh build by calling ```npm run dev```.
 ╭─────────────────────────────────────────────╮
   │                                             │
   │   Nuxt.js v2.9.0-26089340.de7ed24b          │
   │   Running in development mode (universal)   │
   │                                             │
   │   Listening on: http://localhost:3000/      │
   │                                             │
   ╰─────────────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                                               18:43:36
ℹ Initial build may take a while                                                                                                                                                                  18:43:36
✔ Builder initialized                                                                                                                                                                             18:43:36
✔ Nuxt files generated                                                                                                                                                                            18:43:36

✔ Client
  Compiled successfully in 24.39s

✔ Server
  Compiled successfully in 23.48s

 ERROR  (node:69216) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead                                                                                              18:43:41

ℹ Waiting for file changes                                                                                                                                                                        18:44:05
ℹ Memory usage: 308 MB (RSS: 484 MB)                                                                                                                                                              18:44:05

 ERROR  connect ECONNREFUSED 127.0.0.1:8000                                                                                                                                                       18:44:09

  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

 WARN  Cannot stringify a function transformRequest                                                                                                                                               18:44:09

 WARN  Cannot stringify a function transformResponse                                                                                                                                              18:44:09

 WARN  Cannot stringify a function httpAdapter                                                                                                                                                    18:44:09

 WARN  Cannot stringify a function validateStatus                                                                                                                                                 18:44:09

 WARN  Cannot stringify arbitrary non-POJOs Writable                                                                                                                                              18:44:09

 WARN  Cannot stringify a function                                                                                                                                                                18:44:09

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9627">#c9627</a>)</em></sub></div>

**Comment by manniL** [comment]
Looks like your axios request is throwing an error somewhere in `asyncData` or so. Not a framework bug.

**Comment by connecteev** [comment]
@manniL where should I log the bug? nuxt-axios?
Btw, these logs show up on compile "npm run dev", not on loading any specific page.

**Comment by manniL** [comment]
@connecteev 	It should come from your code, not from the nuxt one. Does it happen with a freshly created app via `create-nuxt-app`?

**Comment by connecteev** [comment]
@manniL interesting, doesnt happen when I start afresh and use ```npx create-nuxt-app```, call ```npm install nuxt-edge```, remove the nuxt 2.0 dependency, and then call ```npm install && npm run dev```

That said, how would you go about debugging / fixing the warnings above if it were your app?

**Comment by manniL** [comment]
Well, `ERROR connect ECONNREFUSED 127.0.0.1:8000 18:44:09` usually means that your API url is not accessible. I'd start on any axios call.

**Comment by connecteev** [comment]
Will do, thanks..
