### ISSUE TITLE
url-loader loads urls of css correctly, but it replaced to url on client side

### ISSUE THREAD

**Issue by hedrall** [nuxt/nuxt.js#6224]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/hedrall/nuxt-bug-Reproduction](https://github.com/hedrall/nuxt-bug-Reproduction)

### Steps to reproduce

yarn && yarn dev

### What is expected ?

Url-loader loads urls of css correctly, and we can see base64 encoded url in computed styles in browser.  

### What is actually happening?

In view-source, we can see that urls of css is correctly encoded in base64 like picture bellow.
![スクリーンショット 2019-08-12 1.49.47.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2fb3e270-bd67-11e9-ba73-e137cedee2b6.png)
But checked in computed styles, original url was there. Browser loaded images once more. 
![スクリーンショット 2019-08-12 1.50.13.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/bc4fac50-bd67-11e9-ba73-e137cedee2b6.png)
I think JS replaced base64 to url on client side. Actually, I tried turn on the utility of block JS on browser, and can see base64 urls in computed styles.

Is this some bug? Thank you.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9634">#c9634</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce with the repo and in a production build

![image](https://user-images.githubusercontent.com/640208/63725862-e91bc080-c85b-11e9-984f-403362a1a008.png)
