### ISSUE TITLE
can not bable transfer const to var in android 4.4.x webview 

### ISSUE THREAD

**Issue by Nakiswen** [nuxt/nuxt.js#6225]
### Version

[v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

### Reproduction link

[https://codesandbox.io/s/github/Nakiswen/nuxt-test](https://codesandbox.io/s/github/Nakiswen/nuxt-test)

### Steps to reproduce

1. run nuxt-test project in localhost
2. configure proxy local code using Fiddler or Charles
3. open page in android 4.4.x app's webview
4. check console by using chrome://inspect
5. found error Uncaught SyntaxError: Use of const in strict mode. 

### What is expected ?

nuxt run success, and has no error in console

### What is actually happening?

![issue.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/edca7c30-bd7e-11e9-ba73-e137cedee2b6.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9635">#c9635</a>)</em></sub></div>

**Comment by pimlie** [comment]
You are using `assign-deep` in a page component but by default files from node_modules are not transpiled. You will need to add assign-deep to [build.transpile](https://nuxtjs.org/api/configuration-build/#transpile) to make sure assign-deep is also transpiled

**Comment by Nakiswen** [comment]
thanks a lot. Close the issue.
