### ISSUE TITLE
process.server use paypal sdk, How to jump

### ISSUE THREAD

**Issue by liseipi** [nuxt/nuxt.js#6227]
### What problem does this feature solve?

I want to redirect or store commit, I can't succeed.
How do I get a url and jump?

### What does the proposed changes look like?

```
async asyncData({redirect, store}){
    if(process.server){
        const paypal = require('@paypal/checkout-server-sdk');

        let clientId = "<<PAYPAL-CLIENT-ID>>";
        let clientSecret = "<<PAYPAL-CLIENT-SECRET>>";
        let environment = new paypal.core.SandboxEnvironment(clientId, clientSecret);
        let client = new paypal.core.PayPalHttpClient(environment);
        let request = new paypal.orders.OrdersCreateRequest();
        request.requestBody({
            "intent": "CAPTURE",
                "purchase_units": [
                     {
                      "amount": {
                          "currency_code": "USD",
                          "value": "100.00"
                      }
                  }
              ]
          });
         (async ()=>{
             let response = await client.execute(request);
             let url = response.result.links.find(item => { item.rel === 'approval_url' });

             // I want to redirect or store commit, I can't succeed.
             // redirect(url.href);
             // store.commit('setUrl', url.href);
         })();
    }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9638">#c9638</a>)</em></sub></div>

**Comment by pimlie** [comment]
If you call redirect in asyncData you have to return it: `return redirect(ur.href)` which means in your case you also have to return the IIFE

**Comment by liseipi** [comment]
> If you call redirect in asyncData you have to return it: `return redirect(ur.href)` which means in your case you also have to return the IIFE

In the promise, return redirect cannot be performed

**Comment by pimlie** [comment]
Why not?

**Comment by liseipi** [comment]
> Why not?

 tip: UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
