### ISSUE TITLE
Feature request: typescript example

### ISSUE THREAD

**Issue by sebastianmacias** [nuxt/nuxt.js#623]
A typescript example using vuex and other common features such as asyncData, fetch, and middleware would be a very helpful addition to the [examples](https://github.com/nuxt/nuxt.js/tree/master/examples) folder.

**Comment by sebastianmacias** [comment]
Looks like @johnlindquist is working on a [typescript starter](https://github.com/johnlindquist/nuxt-typescript). 

#121

**Comment by johnlindquist** [comment]
@sebastianmacias fyi, that repo isn't a "starter" (it can't be used with the vue cli). It's just a working example.

**Comment by sebastianmacias** [comment]
@johnlindquist that's right. I meat to say example.

**Comment by johnlindquist** [comment]
https://github.com/johnlindquist/nuxt-typescript-starter

`vue init johnlindquist/nuxt-typescript-starter`

live preview: https://nuxt-typescript-starter.johnlindquist.com/

Please report issues.

**Comment by rwatts3** [comment]
I'm not sure if it's me but  it seems like the example still uses .vue and standard js ? 
Is there a branch I should be looking at ?

**Comment by johnlindquist** [comment]
The TS is inside the .vue files. The nuxt team is working on enabling TS
for store/middleware/etc

**Comment by rwatts3** [comment]
Ah I see.  Once that's done will the project be converted to use .ts ?

**Comment by johnlindquist** [comment]
The starter project will fully convert to TS, yes.

**Comment by rwatts3** [comment]
Awesome thank you

**Comment by antoinerey** [comment]
> The nuxt team is working on enabling TS for store/middleware/etc

Is there more informations about this anywhere ?

**Comment by johnlindquist** [comment]
In the commits, you can see they've added the ts extension to where
store/middleware are loaded.

**Comment by Atinux** [comment]
It's coming soon: https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript

**Comment by Atinux** [comment]
Closing it since rc3 is out
