### ISSUE TITLE
`config.watch` failed at second restart if use wildcard

### ISSUE THREAD

**Issue by TrungRueta** [nuxt/nuxt.js#6232]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://empy](http://empy)

### Steps to reproduce

1. create new project with minimum setup (no add any modules / packages) via `create-nuxt-app`.
2. create new folder at root project named `serverMiddleware`.
3. create new file inside `serverMiddleware` folder, named `test.middleware.js`. add content (see bottom):
4. open `nuxt.config.js`. add into `watch` property : `watch: ['serverMiddleware/test.middleware.js']`. Note: `config.watch` not `config.build.watch`
5. run `yarn dev` to host dev mode, open site in browser and f5 several times. We will see in terminal the console `~this xxx` message.
6. open `test.middleware.js` and edit string from `~ this` to `~ this edited`. save file. We will see in terminal the server auto restarted.
7. After restart done, refresh brower and see message changed. Repeat step 6, 7 to make sure server restart no issue.
8. turn off process (ctrl + c). then open `nuxt.config.js`, edit watch file string from `serverMiddleware/test.middleware.js` to `serverMiddleware/*.js`.
9. start server by `yarn dev`. refresh browser to see message show on.
10. repeat step 6, 7. The watcher will failed with trap 6 nodejs report at second restart.

### test.middleware.js
```js
export default {
  handler: function(req, res, next) {
    // req is the Node.js http request object
    console.log('~ this ', req.path)

    // res is the Node.js http response object

    // next is a function to call to invoke the next middleware
    // Don't forget to call next at the end if your middleware is not an endpoint!
    next()
  }
}
```

### What is expected ?

config.watch with wildcard should work no issue.

### What is actually happening?

config.watch failed when restart second times if watch string contains wildcard syntaxs

### Additional comments?

Ps: also i found that serverMiddleware will cache somewhere outside nuxt processing if in `config.serverMiddlware` property we use string file path.
If we require middleware file use `require()` inside `nuxt.config.js` then import direct to `config.serverMiddleware` and add file path to `config.watch` then project will listen and restart correctly.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9642">#c9642</a>)</em></sub></div>

**Comment by pimlie** [comment]
Please just create a reproduction, its much easier for everybody. Trying to replicate those 10(!) steps  is prone to errors anyway so we end up with a test case thats different from yours.
