### ISSUE TITLE
Strange behaviour of nested pages 

### ISSUE THREAD

**Issue by MaxKostenko** [nuxt/nuxt.js#6235]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/example-hello-world-kw5w9](https://codesandbox.io/s/example-hello-world-kw5w9)

### Steps to reproduce

1. Go to page `test`
2. Open Console. You will see console.log message each time when parent page was triggered
3. Press button 1-1-q. -> No messages. Works correct
4. Press button 1-2 -> Parent page was triggered. Incorrect
5. Press button 2-2 -> No messages. Works correct
6. Press button 2-2-q -> No messages. Works correct
7. Press button 2-2 ->  Parent page was triggered. Incorrect
 

### What is expected ?

Parent page should be triggered only on server side

### What is actually happening?

If you change only `params` or only `query` part of route everything works correct.
If you change `params` and `query` part  of routing simultaneously then parent page component will be triggered

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9645">#c9645</a>)</em></sub></div>

**Comment by pimlie** [comment]
/cc @clarkdo 

The data is [always](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/client.js#L360) refreshed when both path as query have [changed](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/client.js#L133), maybe we should always check `watchQuery` instead?

**Comment by clarkdo** [comment]
I’ll have a look today or tomorrow, sorry for the inconvenience
