### ISSUE TITLE
Add a babel plugin to nuxt-babel options

### ISSUE THREAD

**Issue by thebspin** [nuxt/nuxt.js#6237]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://www.npmjs.com/package/babel-plugin-transform-remove-console](https://www.npmjs.com/package/babel-plugin-transform-remove-console)

### Steps to reproduce

Create nuxt project

In `nuxt.config.js` place:
    ```babel: {
      babelrc: true,
      cacheDirectory: undefined,
      presets: ["@nuxt/babel-preset-app"]
    },```

In `.babelrc` file place:

```{
  "env": {
    "production": {
      "plugins": ["transform-remove-console"]
    }
  }
}```

In terminal/console do: `npm install babel-plugin-transform-remove-console --save`

### What is expected ?

I expect that the babel plugin is loaded and being run, in this case stripping all my console logs

### What is actually happening?

It's not working, it seems like it's not being loaded at all.

<!--cmty--><!--cmty_prevent_hook-->
<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9648">#c9648</a>)</em></sub></div>

**Comment by manniL** [comment]
Any reason it won't work out with `babel.plugins` as shown in https://twitter.com/TheAlexLichter/status/1058296116876320769 ? :thinking:

**Comment by thebspin** [comment]
That work does work out! It is just an option i did not came accross!
I followed whatever was on this page: https://nuxtjs.org/api/configuration-build/ and went by that.
But this is what i needed so thanks for that :)

**Comment by perymimon** [comment]
what was the full solution again?
