### ISSUE TITLE
asyncData without cookies and without params

### ISSUE THREAD

**Issue by ajavaer** [nuxt/nuxt.js#6239]
### Version

[2.0.0](https://github.com/nuxt.js/releases/tag/2.0.0)

### Reproduction link

[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce

![T]JGP8YJZF23EXEBVLU4LN4.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/e31f1dd0-c0bd-11e9-8e14-ff77c02b7c72.png)
![MPG4PHXM%8]8LG5[V@@TEHW.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/daf3e640-c0bd-11e9-8e14-ff77c02b7c72.png)

### What is expected ?

To solve this problem

### What is actually happening?

Just like this console log, I didn't have a loop, but I executed the request three times.And two times you don't carry cookies.，and Another time without parameters

### Additional comments?

Just like this console log, I didn't have a loop, but I executed the request three times.And two times you don't carry cookies.，and Another time without parameters.I didn't write demo, because the code here is on the picture.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9650">#c9650</a>)</em></sub></div>

**Comment by ajavaer** [comment]
who can help me ???

**Comment by ajavaer** [comment]
who can help me ???who can help me ???

**Comment by pimlie** [comment]
Sorry, no idea what the issue is. Please create a reproduction on codesandbox so we can better understand the issue
