### ISSUE TITLE
Is it possible to use webpack require through passing an image into a prop? 

### ISSUE THREAD

**Issue by xdcha** [nuxt/nuxt.js#6242]
Hello. So I used [this post](https://github.com/nuxt/nuxt.js/issues/2946) to try and get require to work with Nuxt. The problem I am having is that I am using props to display the image like so. 

A, 

`  <figure class="c-project-img">
      <img :src="require('projectImg')" :alt="projectImgAlt" />
    </figure>`

B,

`projectImg="~/assets/img/home/webp.jpg"`

When this compiles, however, I get this dependency was not found. This dependency was not found:  * projectImg in ./node_modules/vue-loader/lib/loaders

I wonder how I could possibly make use of webpack through a prop like so?

**Comment by manniL** [comment]
[This post](https://blog.lichter.io/posts/how-to-load-dynamic-images-in-vue-and-nuxt-with-ea) might help there :relaxed:
