### ISSUE TITLE
Use of redirect in SSR middleware runs nuxtServerInit again making it run twice

### ISSUE THREAD

**Issue by Joaoprcf** [nuxt/nuxt.js#6250]
You can reproduce the error with the following code. If you are having problems reproducing (you shouldn't) I can create a repository for you to test it. Don't forget to set the jwt cookie to any value  to test it.
nuxtServerInit:
```
 nuxtServerInit ({ dispatch }, { req }) {
        const cookie = req.headers.cookie
        console.log('start!! (should be called one only)')
        if(cookie) {
            let jwt = cookie
                    .split('; ')
                    .find(c => c.startsWith('jwt='))
            if(jwt) {                
                jwt = jwt.split('=')[1]
                commit('SET_STORE', { jwt: jwt }) //it just sets the jwt to its value
            }
        }
    }
```
This middleware is called on the login page where you shouldn't enter if you are already logged in.
Middleware: 
```
export default function ({store, redirect}) {
    const { state } = store
    if (state.jwt != "") {
        redirect('/inside')
    }
}
```

Calling redirect on nuxtServerInit works just fine, calling redirect in the middleware on ssr does not, as it makes nuxtServerInit trigger twice. This needs to be fixed, it clearly impacts performance and will cause more impact-full consequences in specific use cases when using jwt.

**Comment by EmmanuelVlad** [comment]
Still an issue
