### ISSUE TITLE
Parse failed after update to 2.9.1 (typescript)

### ISSUE THREAD

**Issue by NomNes** [nuxt/nuxt.js#6256]
`Module parse failed: The keyword 'interface' is reserved (22:0)` for interfaces
`Module parse failed: Unexpected character '@' (12:0)` for decorators

And type error: 
```
Error:(9, 9) TS2345: Argument of type '{ fetch({ store }: { store: any; }): void; }' is not assignable to parameter of type 'ComponentOptions<Index, DefaultData<Index>, DefaultMethods<Index>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> & ThisType<Index>'.
  Object literal may only specify known properties, and 'fetch' does not exist in type 'ComponentOptions<Index, DefaultData<Index>, DefaultMethods<Index>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> & ThisType<Index>
```

**Comment by kevcodez** [comment]
Did you find a solution yet?

**Comment by Mikkou** [comment]
i have error  "Unexpected character '@'" too
i use vue-property-decorator

**Comment by Mikkou** [comment]
@NomNes can you show tsconfig.json and nuxt.config.js?

**Comment by NomNes** [comment]
@Mikkou @kevcodez I solved it https://typescript.nuxtjs.org/migration.html

**Comment by pairmix** [comment]
> 
> 
> @Mikkou @kevcodez I solved it https://typescript.nuxtjs.org/migration.html

Hi,
Link is broken,
What is the solution ?
Regards

**Comment by NomNes** [comment]
@pairmix 

# Migration from Nuxt 2.8

TypeScript support has been externalized in dedicated packages and have been removed from core starting Nuxt 2.9. Here are the guidelines to migrate your existing Nuxt TypeScript project to the last specifications.

The following migration guide works for either nuxt or nuxt-edge.

**1. Migrate dependencies**

```
yarn remove @nuxt/typescript
yarn add --dev @nuxt/typescript-build
# OR
npm uninstall @nuxt/typescript
npm install --save-dev @nuxt/typescript-build
```
**2. Add @nuxt/typescript-build module to your nuxt.config.js**
```
// nuxt.config.js
export default {
  buildModules: ['@nuxt/typescript-build']
}
```
**3. Replace @nuxt/vue-app and @nuxt/config by @nuxt/types in your tsconfig.json**
```
// tsconfig.json
"compilerOptions": {
  "types": [
    "@nuxt/types"
  ]
}
```
TIP

If you were importing types from @nuxt/config you need to instead import them from @nuxt/types.

Types imports might have changed a little, you can get familiar with them either by triggering intellisense when importing or watch them live [here](https://github.com/nuxt/typescript/tree/master/packages/types) now.

**4. Move the customized options from build.typescript to module options**
```
// nuxt.config.js
export default {
  typescript: {
    typeCheck: true,
    ignoreNotFoundWarnings: true
  }
}
```
You can also do it this way :
```
// nuxt.config.js
export default {
  buildModules: [
    ['@nuxt/typescript-build', {
      typeCheck: true,
      ignoreNotFoundWarnings: true
    }]
  ]
}
```
**5. TypeScript Runtime (optional)**

If your project is using TypeScript runtime (nuxt.config.ts, local modules or serverMiddlewares), please directly refer to the [Runtime](https://typescript.nuxtjs.org/guide/runtime.html) section.
