### ISSUE TITLE
Documentation for older Nuxt versions

### ISSUE THREAD

**Issue by nkoder** [nuxt/nuxt.js#626]
Is documentation for older Nuxt available anywhere?

My case was that for some intricate reasons I was unable to upgrade from Nuxt 0.9.0 to Nuxt 0.10.x. At the same time documentation for 0.9.0 was replaced with docs for 0.10.0, and newer, and now it's 0.10.6. Happily, after long hours of investigation I was able to fix the issue with PR to another tool ( https://github.com/claudiajs/claudia/pull/118 ), but still... It would be great to provide docs for at least every minor Nuxt version :-)

**Comment by nkoder** [comment]
And if I can help with that somehow... Where should I start?

**Comment by alexchopin** [comment]
Hi, 
Sorry, but we choose to not keep older Nuxt version documentations until the version 1.0.
For now, the only solution is to check the docs repository commits history.

**Comment by nkoder** [comment]
Ah, OK, I think I can understand that before 1.0.0 is not worth to maintain versioned docs, right :-)
