### ISSUE TITLE
nuxt.config.ts is not working?

### ISSUE THREAD

**Issue by tanakaworld** [nuxt/nuxt.js#6261]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[https://github.com/tanakaworld/verify-2.9.1/commit/d78cbc686b66470d236a5ddf6776be3901ca4413](https://github.com/tanakaworld/verify-2.9.1/commit/d78cbc686b66470d236a5ddf6776be3901ca4413)

### Steps to reproduce

For instance, `srcDir` is not working if file name is `nuxt.config.ts`.
ref: https://github.com/tanakaworld/verify-2.9.1/commit/d78cbc686b66470d236a5ddf6776be3901ca4413

![Screen Shot 2019-08-21 at 14.25.42.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2a9435b0-c3d4-11e9-a52e-3386919eea83.png) 
 ![Screen Shot 2019-08-21 at 14.26.06.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/34ad81a0-c3d4-11e9-a52e-3386919eea83.png)

After rename to `nuxt.config.js`, it will work correctlly.

 ![Screen Shot 2019-08-21 at 14.24.55.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0d360d40-c3d4-11e9-a52e-3386919eea83.png)

### What is expected ?

`nuxt.config.ts` should be working.

### What is actually happening?

`nuxt.config.ts` should be working.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9664">#c9664</a>)</em></sub></div>

**Comment by iliyaZelenko** [comment]
I saw that a migration guide appeared, should help: https://typescript.nuxtjs.org/migration.html

**Comment by iliyaZelenko** [comment]
I had the same problem, now everything works.

You can take types for a config from:

```ts
import { Configuration } from '@nuxt/types/config'

const config: Configuration = {
```

If your project is using TypeScript runtime (nuxt.config.ts), then do [this](https://typescript.nuxtjs.org/guide/runtime.html).

**Comment by tanakaworld** [comment]
According to [TypeScript runtime](https://typescript.nuxtjs.org/guide/runtime.html#installation), `nuxt.config.ts` works fine by using `nuxt-ts` instead of `nuxt`.

demo: https://github.com/tanakaworld/verify-2.9.1/commit/263707df776e283e8a388e040b3012ad5091ac51

Thanks!

**Comment by pksorensen** [comment]
I just upgraded and also just changed my nuxt.config.ts to .js to fix compile. 

I consider myself a rather smart guy, but I failed at reading  https://typescript.nuxtjs.org/migration.html and make my config.ts file work as it used to.  

I will try see if anything in this issue helps me get it working.
