### ISSUE TITLE
Don't see the loading / progress bar at the top

### ISSUE THREAD

**Issue by connecteev** [nuxt/nuxt.js#6262]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[http://www.nourl.com](http://www.nourl.com)

### Steps to reproduce

With an installation of nuxt / nuxt-edge, I don't see the loading / progress bar at the top. 

According to this doc, the loading indicator should be enabled by default, but it isn't.
https://nuxtjs.org/api/configuration-loading#disable-the-progress-bar

I also tried this in nuxt.config.js:
```
  loading: { color: "#f00" },

```

### What is expected ?

Loading / progress bar indicator should show up

### What is actually happening?

It does not.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9665">#c9665</a>)</em></sub></div>

**Comment by pimlie** [comment]
Maybe your page just loads very quickly, as in within the throttle time?

If not => reproduction

**Comment by connecteev** [comment]
I see the loading bar (red) flash by quickly when an error page is seen...but not on other pages. I'd like the same to show up, except in blue. Will try to reproduce this again.

**Comment by andreynazarov3** [comment]
same here, loading is not showing

**Comment by andreynazarov3** [comment]
i found what was reason in my case.
i had a plugin which replaced mounted() hook in App.js file, so 
```
mounted() {
this.$loading = this.$refs.loading
}
```
was not triggering

**Comment by pimlie** [comment]
@andreynazarov3 Thanks, interesting reason. How exactly did the plugin replaced the hook? Runtime or in the template? Was it a 3rd party plugin?

**Comment by andreynazarov3** [comment]
@pimlie it was my own plugin to work with cookies on app mount, I was thinking that somehow it will not replace basic mounted hook and just add this additional functionality...
```
export default ({ app, store }) => {
  app.mounted = function() {
    .... some code
  };
};
```

**Comment by Atinux** [comment]
@andreynazarov3 if you want to attach another method to mounted without overwriting the original one, use an array:

```js
// plugins/cookie.js
export default ({ app, store }) => {
  app.mounted = [ app.mounted, function () {
    ... some code
  }];
};
```

**Comment by hwolf0610** [comment]
Thank you
