### ISSUE TITLE
Javascript leave transition hook not showing tween animation

### ISSUE THREAD

**Issue by dacxjo** [nuxt/nuxt.js#6263]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[https://csb-q3db0.netlify.com](https://csb-q3db0.netlify.com)

### Steps to reproduce

Click on the link to go to the about page, and go back to the index page.

The reproduction link is serverd on netlify production mode,

### What is expected ?

Leave transition must be executed and showed 

### What is actually happening?

Leave transitions is not showed , only the enter transitions

### Additional comments?

Also i make a code sandbox where is the code and is  deployed to netlify (The reproduction link) 

https://codesandbox.io/s/codesandbox-nuxt-vpe6g

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9666">#c9666</a>)</em></sub></div>

**Comment by pimlie** [comment]
Does this only happen since `v2.9.1` or also with `v2.8.1`?

What does the leave transition look like, e.g. the console logs `Leave from Design`

**Comment by dacxjo** [comment]
Seems like changing the version to v2.8.1 fix the behavior, here is other codesandbox where i change the version to v2.8.1 and works https://codesandbox.io/s/codesandbox-nuxt-5bzz7

**Comment by pimlie** [comment]
Thanks, caused by #5891 

Seems that caused your done function to be ignored.

**Comment by dacxjo** [comment]
So, im declaring css:false and providing a leave with a done callback , this should work, im using the same layout for both pages, if i remove the css:false, it seems work as expected but is not a good practice using css with javascript animations.

**Comment by pimlie** [comment]
See linked pr

**Comment by pimlie** [comment]
@dacxjo Thanks for providing the clear reproduction btw, made it so much easier to debug this :)

**Comment by dacxjo** [comment]
Thanks to you for all @pimlie , im seeing it now
