### ISSUE TITLE
Can't anymore use nuxt as devDependencies, because nuxt-start is missing vue-client-only

### ISSUE THREAD

**Issue by victor-perez** [nuxt/nuxt.js#6266]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[http://none](http://none)

### Steps to reproduce

add `nuxt`  to the  _devDependencies_ `npm i -D nuxt` 
add `nuxt-start` to the _dependencies_ `npm i nuxt-start`
build the app `npx nuxt build`
run  `npm ci --production` for production dependencies
run nuxt: `npx nuxt-start` 

### What is expected ?

Nuxt to run normally 

### What is actually happening?

```bash
ERROR  Cannot find module 'vue-client-only'

  at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:74:15)
  at node_modules/vue-server-renderer/build.prod.js:1:77711
  at Object.<anonymous> (server.js:1:0)
  at r (server.js:1:0)
  at Module.<anonymous> (server.js:1:0)
  at r (server.js:1:0)
  at Object.<anonymous> (server.js:1:0)
  at r (server.js:1:0)
  at server.js:1:1432
  at Object.<anonymous> (server.js:1:0)
```

### Additional comments?

Before Nuxt 2.9 this was  possible to do this without any problems

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9667">#c9667</a>)</em></sub></div>

**Comment by pimlie** [comment]
Unfortunately I cannot reproduce this with the hello world example, have you tried removing your node_modules dir and package lock?

**Comment by victor-perez** [comment]
@pimlie I think you need to use `<no-ssr>` or the new `<client-only>`  in one of your components
I try to build a example in the mean time

**Comment by pimlie** [comment]
@victor-perez Ah right, never mind. The dep seems to be missing indeed

**Comment by pimlie** [comment]
Thanks for the report!
