### ISSUE TITLE
Nested Routes index without <nuxt-child>

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#627]
Currently, with nested routes, such as in the [example](https://nuxtjs.org/examples/nested-routes/), the `/pages/index/index.vue` gets injected into `/pages/index.vue` this means that I can't  have a different outer page for the `/` route vs `/:id` route.
Imagine instead of putting `Please select an user.` into the right container, I wanted to display a whole different page. The current file api does not allow that.

**Comment by alexchopin** [comment]
Can you be more specific and give more details about what you are trying to do?

**Comment by qm3ster** [comment]
For example, my files are as follows:
```
├── locations/
│   ├── index.vue
│   ├── kz.vue
│   └── so.vue
└── locations.vue
```
```pug
//- locations.vue
locnav
.somecontainer
  nuxt-child
locnav
```
```pug
//- locations/kz.vue
kz-stuff
```
```pug
//-  locations/index.vue
feature(loc="kz")
feature(loc="so")
```
for route `locations/` I want to render `locations/index.vue` as child of layout, without involving `locations.vue`.
After explaining this here now, I see this issue could be generalized to escaping from a parent component at any child route, not necessarily the `index.vue`/`/`. Index just seems like a common case, but there could very well be other ones, such as `all/`.

This is not a serious problem, it can be circumvented by:
- splitting up urls, eg:
```
├── location/
│   ├── kz.vue
│   └── so.vue
└── locations.vue
```
- by not using nested routes, eg: 
```
└── groups/
    ├── index.vue
    └── _id.vue
```
but it is a limitation that should be acknowledged.

**Comment by alexchopin** [comment]
I don't really see this as a limitation.
If you don't need to use nested routes simply don't create it.
