### ISSUE TITLE
Apply .page-leave when same component is used but (dynamic) route changes

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#628]
Not sure how to best handle this, especially keeping in mind nested routing.
My case is that on `/en/test (pages/_lang/test.vue)`, if I do
```js
this.$router.push({params: {lang: 'ru'}})
```
the page content changes without transition.

**Comment by OlzhasAlexandrov** [comment]
As a possible solution, you can add a watcher inside your page component:
```
export default {
    watch: {
        $route() {
            // replicate transition here
        }
    },
}
```
But I hope there is a better way of handling this

**Comment by qm3ster** [comment]
Thank you, I have done that where critical, since css wasn't enough there anyway (numeric 'counter' transition was involved).
Good that you posted that here for others, until this is resolved.

**Comment by kodekrendel** [comment]
So how to solve it? Transitions doesn't work on dynamic routes.

**Comment by kodekrendel** [comment]
@OlzhasAlexandrov how to replicate transition? What does it mean?

**Comment by OlzhasAlexandrov** [comment]
@kodekrendel you can write JS where I left a comment `//` to achieve any transition effect

**Comment by kodekrendel** [comment]
@OlzhasAlexandrov really? Thanks for the tip. I though I need to write Chineese there.

**Comment by OlzhasAlexandrov** [comment]
@kodekrendel it's strange to expect to get a complete solution or examples of finished work. I believe that I left more than enough for anyone to write their own implementations. If you would like to receive a solution, tailored for your project, you are welcome to fill out the form [here](https://alexandrov.co)

**Comment by kodekrendel** [comment]
@OlzhasAlexandrov you are not qualified enough for paid work, ушастик.

**Comment by juliojerrick** [comment]
Lol

**Comment by kodekrendel** [comment]
@OlzhasAlexandrov you should paid Nuxt for placing commercial here. I don't see your name in Backers list. Can you believe this *****?

**Comment by OlzhasAlexandrov** [comment]
@kodekrendel There had been more than 10 times when I personally helped you and you expressed your verbal gratitude, such as [here](https://github.com/nuxt/nuxt.js/issues/105).
Therefore, I ask you to stop being rude after a polite offer of your problem.
Best wishes and good luck with resolving your issue.

**Comment by qm3ster** [comment]
:laughing: :rofl: Thank you for this thread gentlemen.

**Comment by qm3ster** [comment]
@Atinux, closed on what basis? Is this due to a limitation in `vue-router` and so should not be fixed in this project?
