### ISSUE TITLE
on refresh with nuxt child it mounts 3 times

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/nuxt.js#6280]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[https://github.com/debs-obrien](https://github.com/debs-obrien)

### Steps to reproduce

filling out the form of our booking engine we add hotel and then fill our details form and submit to take us to payment page
if we refresh the page
it mounts the child component 3 times so then we cant pay. it only happens on page refresh

### What is expected ?

fill out the form and submit

### What is actually happening?

refresh the page and fill out form and submit it mounts 3 times causing it to create 3 posts to the payment and obviously that just crashes

### Additional comments?

if you need access to repo please contact me directly

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9675">#c9675</a>)</em></sub></div>

**Comment by pimlie** [comment]
Do you use a transition with `css: false`? If so then it could be related to #6263

**Comment by debs-obrien** [comment]
No we have no transitions. We tested it out in every step and in every step on mounted gets loaded 3 times only on refresh

**Comment by pimlie** [comment]
Would appreciate if you could share a minimal reproduction

**Comment by debs-obrien** [comment]
Can do a call tomorrow with you trough discord and show you exactly if that will help 😊

**Comment by aldarund** [comment]
Please, can you try to create a minimal reproduction on CSB so it would be way easier to see what wrong rather than debuggin via calls...

**Comment by debs-obrien** [comment]
Hi, I can't seem to reproduce the error today, at all. which means could have been a server worker issue due to the pwa perhaps. i will keep an eye on it and if it reshows I will let you know. thanks for looking into it. strange but yeah if it fixes on its own then great but weird. lets blame the service workers ;)
