### ISSUE TITLE
Break nuxt.js up into modules

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#629]
## Why?
Currently, the scope of the monolithic nuxt.js package is already too big and is already growing.
Consider the following use cases:
- large scale application (eg social network)
- statically served mostly-offline webapp (firebase)
- electron/cordova app
- Weex app

There's a number of aspects of nuxt each of these won't use.
With growing  functionality, nuxt will be harder and harder to pick up.
Seeing the Issues that get accepted, it is clear the project is moving from "one specific way to make vue ssr applications" to "the best way to develop vue-centric js apps from scratch in most conditions". It's time the project's structure reflects that.

Imo, this will enable easier continued development and use.

## What do?!
I am making a far fetched suggestion that I believe will grant this project easier adoption if implemented before 1.0. It comes in two parts:

### 1. Don't indirect things more than necessary.
- Let the user instantiate their own vue-router or even use a different router, just pass them the output of the pages-file-api feature to give it.
- Leave the webpack configs in the hands of the user. Just giving them an export they can put in their own configs will still allow you to update nuxt version in place, but you won't be reinventing the bicycle by providing apis to override your hidden webpack config.
- Don't deviate from the norm until necessary (`.nuxt-link-active`, `<nuxt-link>` that just returns a `<router-link>` for now.) That's scope and lines of code for nothing.
- `vue-meta` plugin's **metaInfo** component property is renamed to **head**. This (afaik) provides no benefit, unlinks it from `vue-meta` documentation, and makes it unclear that **htmlAttrs** and **bodyAttrs** can still be used.

You have a great ally in vue-cli. Just use that to keep things like vuex, vue-router, vue-loader and webpack (maybe even vue?) in the user repo, and provide a recipe that sets them up out of the box. Small helpers like `plugins: [{injectAs}]` and setting up aliases for webpack can go in the recipe.

### 2. Extract parts of nuxt.js as separate modules
For example:
- **nuxt-dev**:
The only one that has watchers/hmr/bundle-analysis/friendly-errors; Tools for *developing* nuxt *applications* (as radically opposed to developing nuxt)
- **nuxt-build**:
For building the application for nuxt-serve; Minifiers can go here too.
- **nuxt-(serve|start)**:
Serves a built application as a standalone server or programmatically
- **nuxt-generate**:
For generating static site structure.
- **nuxt(-plugin?)-offline**:
The upcoming service-worker/appcache feature

The way I see these, the first 4 should not depend on each other, but should obviously have some common nuxt dependencies.

Could be even more granular; For example, file apis can be extracted.

**Comment by lmj0011** [comment]
>Leave the webpack configs in the hands of the user. 

I couldn't agree more.

**Comment by qm3ster** [comment]
A diagram of what nuxt project currently consists of (pencil on a napkin is fine) would be extremely helpful here.

**Comment by qm3ster** [comment]
I haven't stumbled upon it before, but someone is already trying to do what I described, not as a fork of nuxt but stating from scratch: [`ream/ream`](https://github.com/ream/ream) (It was also mentioned tangentially in #614, so it might be common knowledge.)
### What I have seen so far:
#### Generator  uses `pathToRegexp`:
```js
app.generate({
  routes: {
    '/': true,
    '/user/:name/': [
      { name: 'egoist' },
      { name: 'trump' },
      { name: 'my name' }
    ]
  }
})
```
Currently the big drawback is it doesn't attempt to use the router routes for generation even when there aren't route params.
This could be further improved by passing an object for possible values in general, not just to a specific path (as long as you make sure that you don't reuse param names to mean different data on different routes)

#### File API for `pages/` extracted:

You declare your own router, but they provide [a plugin to populate it from a similar file API](https://ream.github.io/ream/#/plugin/fs-router). This way, the rest of their advancements can be used by people who can't, or don't have a reason to, use the file API.

#### Webpack configuration handled with [`mozilla-neutrino/webpack-chain`](https://github.com/mozilla-neutrino/webpack-chain)
[An example.](https://ream.github.io/ream/#/api?id=extendwebpack)
@lmj0011 does this look like a good middle ground to you?

### What is definitely lacking
- Richness of documentation and examples
- Community

Since these two things that go hand in hand are extremely important, imho nuxt is the more likely project to succeed, but it is a sensible idea to not only copy what they do right, but also communicate with them to indicate that the goals of nuxt going forward aren't  [quite so different](https://github.com/ream/ream/issues/23#issuecomment-299425295) and consolidate the effort.

**Comment by lmj0011** [comment]
>does this look like a good middle ground to you?

sure

**Comment by alexchopin** [comment]
Hi @qm3ster,
Thanks for all your suggestions, we have thought about nuxt-modules for a while now.
However, changes appear often with new Vue versions.
Of course, we would prefer to have contribution directly to Nuxt with PR instead of a new project created on their side. (Isn't the main goal of an open source project?) 
For you last suggestions about the `generate.routes`, I don't see what is the problem with the current functionality we have?

**Comment by qm3ster** [comment]
With regard to `routes`,  nuxt currently has two options:
1. Get static routes from router options (which, in turn, can come only from file API)
2. Submit an array of string urls to statically generate

While the first option is excellent so long as there aren't route parameters, the second option is not DRY at all. It can be automated by the end user, but it's sort of a hack. [(See how coupled to the directory structure `generate` in `nuxtjs.org` is.)](https://github.com/nuxt/nuxtjs.org/blob/master/nuxt.config.js#L31) Nuxt already knows about our route patterns - it supplied it. What doesn't it know? The possible values of the route parameters. So let the user supply just that, without having to manually recreate the routes for which the source of truth can currently only be the file API.

Secondly, and a big request of mine at the moment, would be to expose the config created by the file API to the user before passing it to vue-router. This way, instead of creating extra files *per page* to serve as "links" to the `_lang/` pages in the root in cases such as https://nuxtjs.org/examples/i18n/, one could programmatically give everything in `_lang/` a vue-router `alias` property.

**Comment by qm3ster** [comment]
Added to the issue: 

> `vue-meta` plugin's **metaInfo** component property is renamed to **head**. This (afaik) provides no benefit, unlinks it from `vue-meta` documentation, and makes it unclear that **htmlAttrs** and **bodyAttrs** can still be used.

**Comment by Atinux** [comment]
It's now the case with 1.0 :)

**Comment by qm3ster** [comment]
I noticed [`nuxt-community/router-module`](https://github.com/nuxt-community/router-module) exists.
Wouldn't it make more sense to require a router options object by default, and have the functionality that generates this object be a separate module (not nuxt-specific) similar to [`ream/plugins/fs-router.js`](https://github.com/ream/ream/blob/master/plugins/fs-router.js).
This module can then be consumed by an even tinier (optional) wrapper *nuxt-module* that will emulate the current behavior without increasing boilerplate.

This would be a reasonable way to organize code, create a useful module for all users of vue-router, and allow admixing your own routes to the filesystem-parsed ones (finally removing the `.vue` export import duplicate files in the `vue-i18n` example for the default `/ == /en/` route.)

**Comment by pi0** [comment]
@qm3ster But what benefits this will give us? I mean we have split nuxt into builder and core modules for fewer dependencies and added fully modular architecture. This fs router is something default without any extra code and can be customized to something more advanced by provide a module.
