### ISSUE TITLE
Nuxt link does an unwanted app reload

### ISSUE THREAD

**Issue by federicovezzoli** [nuxt/nuxt.js#6307]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://ledimorediviaarena.netlify.com/appartamenti](https://ledimorediviaarena.netlify.com/appartamenti)

### Steps to reproduce

Just click on "scopri", the app gets reloaded

### What is expected ?

the app to load the page correctly

### What is actually happening?

the app gets an unwanted reload.

### Additional comments?

It seems the problem is somewhere around the fact that the link is inside a transition, never happened before though, no logs or any kind of error.
If I place the same link out of the transition everything works as expected.
Tried 2.9.1, same problem.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9685">#c9685</a>)</em></sub></div>

**Comment by pimlie** [comment]
Thanks for the report, could you please provide a small reproduction on codesandbox for us to test?

**Comment by federicovezzoli** [comment]
Here it is:
https://codesandbox.io/s/github/federicovezzoli/test

https://e057j.sse.codesandbox.io/appartamenti

**Comment by manniL** [comment]
@federicovezzoli could you please add a note about how you solved the issue for people coming along?

**Comment by federicovezzoli** [comment]
Yes sorry. The problem was a GSAP animation that I was doing on that link.
I was splitting the letters and reverting them back at the end, the reverting process caused vue to lost the click handler.

I solved it by avoiding the reverting on the text splitting since I was not needing it.
