### ISSUE TITLE
Hot update memory overflow

### ISSUE THREAD

**Issue by iDerekLi** [nuxt/nuxt.js#6308]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[https://github.com/iDerekLi/hot-update-memory-overflow](https://github.com/iDerekLi/hot-update-memory-overflow)

### Steps to reproduce

index.vue
```vue.js
<template>
  <h1>{{ num }}</h1>
</template>

<script>
export default {
  data() {
    return {
      num: 0
    }
  },
  mounted() {
    window.setTimeout(() => {
      this.num = 1 // Edit file triggers hot update.
      alert(this._uid) // R: Repeated triggering
    }, 500)
  }
}
</script>
```

# steps
1. Quickly try to edit `this.num` value.
2. Waiting for page compilation to finish.
3. Refresh your phone's browser page.

### What is expected ?

Consistent with the PC browser code execution structure.

### What is actually happening?

The refresh page in the iPhone browser prints the component data information retained in memory multiple times and responds to the page, and has a 50% probability to trigger an infinite refresh page. This is not the case with PC browsers.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9688">#c9688</a>)</em></sub></div>

**Comment by fmoessle** [comment]
I also get an infinite refresh page within my project. I can only confirm this in Chrome 76, but I did not test this with another browser yet.

**Comment by jessielaf** [comment]
I also have the infinite refresh problem and the memory overload. On chrome 76 and firefox 68.0.2

**Comment by kezek** [comment]
+1. It's not 100% repro , but sometimes it happens.

I'm on 2.9.2.
