### ISSUE TITLE
How can I run 2 nuxt project in same nginx 

### ISSUE THREAD

**Issue by akirawinz** [nuxt/nuxt.js#6309]
Here is my structure folder

var

www

html

backoffice

frontend

My projects are in backoffice and frontend

Im using pm2 to start my server port 3000, 3100

location / {
    proxy_pass http://localhost:3000;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection 'upgrade';
     proxy_set_header Host $host;
     proxy_cache_bypass $http_upgrade;
}

location /admin {
     proxy_pass http://localhost:3001/admin;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection 'upgrade';
     proxy_set_header Host $host;
     proxy_cache_bypass $http_upgrade;
}
the path / is fine . The problem is in my /admin It's turn into white screen

In nuxt when I npm run build It will compile into .nuxt folder

the problem are here when I run /admin path It run at port 3001

I try to debug by inspect element my js path

/_nuxt/921cc8ac0d041c1ae8a6.js
and when I click into link It's

/* script not found */
the problem are here I think It's run port 3000 in stead of 3100 that's why It cant read any Css in /admin or 3001 port

**Comment by ikristher** [comment]
Hi we are running the same setup, make sure you have base option in your router in nuxt.config.js

<pre>
 router: {
    middleware: ['auth'],
    base: '/admin/',
}
</pre>
