### ISSUE TITLE
cannot match vue@2.3.0 with vue-*-*@<2.3.0

### ISSUE THREAD

**Issue by kevinaskin** [nuxt/nuxt.js#631]
use [latest] tag can not pull the right version so users can not do everything even 'yarn start'

**Comment by pi0** [comment]
@kevinaskin This is a known issue.Because yarn prefers to keep using exact dependencies of nuxt if not explicitly added (even semver/minor) and this makes problems is you also directly/indirectly using different Vue version. As a workaround you can add all of this dependencies to package.json: 
```js
"vue": "^2.2.6",
"vue-server-renderer": "^2.2.6",
"vue-template-compiler": "^2.2.6",
```
