### ISSUE TITLE
Custom error page not working with Typescript

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#6319]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-mzpsr](https://codesandbox.io/s/codesandbox-nuxt-mzpsr)

### Steps to reproduce

When using class API to create the error.vue file some properties do not work at all. E.g. you cannot set the layout property, or use the asyncData method.

Just open the codesandbox, and open a non existing url in the "browser". e.g. just append /asdf.
You see a error page with the text "custom error page". Now open layouts/error.vue,
comment out the <script lang=ts> part and comment in the regular <script> part above it. Now let the server recompile and reload the page. The page looks similar, but now layout B is used, you can see this by the additional text  "LAYOUT B custom error page".

### What is expected ?

Typescript version should work the same as the non-typescript version.

### What is actually happening?

The typescript version does not work with layout, asyncData and other properties. It seems they only work either with the "old" option style API or not with typescript (or both ? ;)).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9694">#c9694</a>)</em></sub></div>

**Comment by simllll** [comment]
It's still an issue in the latest version,just tried to debug it last weekend. Unfortunately some more background is needed to tackle this I guess ;)

**Comment by simllll** [comment]
Ping, issue still exists

**Comment by xxRockOnxx** [comment]
I solved it by moving your layout property from the decorator the class itself. I dont think the `@Component` decorator allows non-vue properties.

See: https://codesandbox.io/s/codesandbox-nuxt-viupg

**Comment by Kronhyx** [comment]
@xxRockOnxx very very interesting.... thanks!!

**Comment by simllll** [comment]
I was just re reading the Vue class component documentation, something I like to try is the custom hooks registration. Maybe this one solvea it too? https://github.com/vuejs/vue-class-component#adding-custom-hooks 

But thanks for figuring this out and give the right hint!

**Comment by simllll** [comment]
One thing to point out here:
It does work with regular pages like expected, only the error/ (within layout folder) page behaves differently, still think this is kind of a bug.

**Comment by webcoderkz** [comment]
This bug are still present in 2.10 version with TS 3.7. @xxRockOnxx trick does work with error page. If it's not the error page (layout), then using `layout: 'name'` in a component decorator does work.

**Comment by aldarund** [comment]
layout was fixed in https://github.com/nuxt/nuxt.js/pull/6650

**Comment by webcoderkz** [comment]
@aldarund in a next release we would see this fixed?

**Comment by aldarund** [comment]
@webcoderkz yes

**Comment by kevinmarrec** [comment]
@aldarund Should this issue be closed OR make it be closed by #6733 ?
