### ISSUE TITLE
Layout change transition

### ISSUE THREAD

**Issue by phr3nzy** [nuxt/nuxt.js#6321]
### What problem does this feature solve?

When changing a layout, the second layout appears almost instantly and without a transition.

### What does the proposed changes look like?

Add a layout-transition property to nuxt config.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9696">#c9696</a>)</em></sub></div>

**Comment by manniL** [comment]
Already there. https://nuxtjs.org/api/configuration-transition/
