### ISSUE TITLE
download attribute on link

### ISSUE THREAD

**Issue by webravenz** [nuxt/nuxt.js#6324]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-ssg9l?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-ssg9l?fontsize=14)

### Steps to reproduce

Click on "Download a file" button, it should download the file and not browse to its url. The HTML "a" tag has a "download" attribute

### What is expected ?

Download the file when "a" HTML tag has "download" attribute

### What is actually happening?

Browse to file url when clicking on the link

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9697">#c9697</a>)</em></sub></div>

**Comment by manniL** [comment]
Your example can't work.

> This attribute only works for same-origin URLs, but never for file: URIs.
[[Source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes)]

If you replace the url in your example with sth. like `/favicon.ico`, it works. So make sure you use URLs from the same origin.
