### ISSUE TITLE
nuxtServerInit on nuxt generate fallback

### ISSUE THREAD

**Issue by matthieudou** [nuxt/nuxt.js#6328]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/matthieudou/nuxtServerInitReproduction](https://github.com/matthieudou/nuxtServerInitReproduction)

### Steps to reproduce

Go to https://nuxtserverinit.netlify.com/

navigating between the pages should work as expected. but if you go to the other page and hit refresh, the data isn't there anymore.

### What is expected ?

Data should be there

### What is actually happening?

the nuxtServerInit function is not used on the fallback 200.html file 

### Additional comments?

Hi,

First of all, thank you for nuxt, it's an awesome framework and I enjoy working with it.

On an application I'm working, I make use of the nuxtServerInit method to fetch some initial data. 
I don't need some routes to be generated so I'm doing a fallback on the 200.html file on netlify. The problem is that I'm relying on some data that is fetched in the nuxtServerInit method and the method is not runned on the 200 file unlike fetch or asyncData.

Wouldn't it be good to run nuxtServerInit on the 200 file too ? 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9702">#c9702</a>)</em></sub></div>

**Comment by matthieudou** [comment]
Some additional tryings. When I manually add the generated nuxt script to the 200 page, something like this
```
<script>window.__NUXT__={layout:"default",data:[{}],error:null,state:{preFetchedString:"quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"},serverRendered:!0}</script>
```

It works fine

**Comment by manniL** [comment]
It's not used because the fallback is an spa-mode fallback. Only client-side code is triggered there, so no `nuxtServerInit` as there is no server part :yum:.

What you could do is to use a Nuxt plugin with the `client.js` suffix and do a check if the necessary data is loaded and if that's not the case, trigger the actions to load it.

**Comment by matthieudou** [comment]
Hey,

Thanks for the quick reply. I understand that the fallback file is spa mode and I know that `nuxtServerInit` is only triggered on the server side. I would find it normal to have this method runned for this file too.

The client plugin is a good workaround that I din't thought of. Thanks for the tip. This will work fine.
