### ISSUE TITLE
core-js dependency breaks when using nuxt in monorepo with another package that's using newer core-js

### ISSUE THREAD

**Issue by kabalage** [nuxt/nuxt.js#6336]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/kabalage/nuxt-core-js-problem](https://github.com/kabalage/nuxt-core-js-problem)

### Steps to reproduce

```
> yarn install
> cd ui/landing
> yarn run dev
```

### What is expected ?

I expect that `@nuxt/babel-preset-app` would use the `core-js` version it needed. (`node_modules/@nuxt/babel-preset-app/node_modules/core-js`)

### What is actually happening?

It resolves to the `core-js` version installed by other packages. (`node_modules/core-js`)

This results in errors like:

```
These dependencies were not found:

* core-js/modules/es6.array.find in ./.nuxt/client.js
* core-js/modules/es6.array.iterator in ./.nuxt/client.js
* core-js/modules/es6.date.to-string in ./.nuxt/utils.js
* core-js/modules/es6.function.name in ./.nuxt/client.js
...
```

### Additional comments?

We have multiple ui projects for one app and others are using the newer `3.x.x` version of `core-js`. We implemented our landing page using nuxt because it supports static site generation but have run into this problem when trying replace the old landing page implementation in our monorepo managed by yarn workspaces.

I'm not sure what is happening in `nuxt`, I would like some insight if it is something fixable with configuration.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9710">#c9710</a>)</em></sub></div>

**Comment by pimlie** [comment]
If you search on https://nuxtjs.org for core-js you will find these tips about core-js from the release log of `v2.6.0`: https://nuxtjs.org/guide/release-notes#core-js

**Comment by pi0** [comment]
Unfortunately, we can't do anything for this issue for supporting multiple core-js versions. The reason is that it is not `@nuxt/vue-app` picking `core-js` but webpack which prefers main `node_modules`... We tried using aliases but it was not fully functional as core-js 2/3 structures are different...

BTW OH! I just thought about a newer idea to make webpack searching for `@nuxt/vue-app/node_modules` first! Will try to see how it works.

For now as @pimlie mentioned it would be better to follow core-js instructions and upgrading to 3.

**Comment by kabalage** [comment]
Thank you for your responses. I could solve the core-js issue using @pimlie 's suggestion but unfortunately I encountered webpack loader problems afterwards which similarly may have been caused by the different package versions used by the new nuxt app and the rest. It could not load `./.nuxt/components/nuxt-error.vue` in `./.nuxt/index.vue` or something similar. (I'm writing this from memory, sorry...) If you're interested in the details, I could check again.

I ended up [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/)-ing the nuxt app package so `yarn install` will install all its dependencies locally under its own directory which completely solved the dependency issues. Maybe using hoisting for every package is not worth the hassle and I understand [why these kinds of problems can't always be fixed](https://yarnpkg.com/blog/2018/02/15/nohoist/#why-cant-they-be-fixed).

**Comment by sebaveg** [comment]
Same problem. I did what he said @kabalage. 
`rm -rf node_modules && yarn`
This worked for me.

**Comment by nonlinearcom** [comment]
I have the same problem but `rm -rf node_modules && npm i` didn't work for me. Is there any other workaround for this?

**Comment by vinayakkulkarni** [comment]
> I have the same problem but `rm -rf node_modules && npm i` didn't work for me. Is there any other workaround for this?

Do this:
```
rm -rf node_modules && yarn
rm -rf yarn.lock
npm run dev
```

It is caused due to [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) being done by npm

**Comment by chrisleyva** [comment]
> > I have the same problem but `rm -rf node_modules && npm i` didn't work for me. Is there any other workaround for this?
> 
> Do this:
> 
> ```
> rm -rf node_modules && yarn
> rm -rf yarn.lock
> npm run dev
> ```
> 
> It is caused due to [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) being done by npm

I'm sorry, this didn't work for me.
