### ISSUE TITLE
Auth0 JWT example not working on reload

### ISSUE THREAD

**Issue by mindbits** [nuxt/nuxt.js#634]
Unfortunately the example does not work properly if generated.

If you go to https://nuxt-auth0.surge.sh and sign in, there is a redirect to the main page showing "You are authenticated" and the secret div is displayed.

But then reloading this page results in the unexpected "You're not authenticated yet"?

The only way to make the example work after a reload is to manually go to https://nuxt-auth0.surge.sh/secret and start the navigation from there.

**Comment by kodekrendel** [comment]
You should create this in that example page.

**Comment by kodekrendel** [comment]
If you bother to check that page, you'll find that it already have that issue - https://github.com/nuxt/example-auth0/issues/8
