### ISSUE TITLE
Proper production deploy with pm2 configuration

### ISSUE THREAD

**Issue by Revel109** [nuxt/nuxt.js#6346]
When i do `npm run dev` in pm2 config, it can get process.env configurations(backend api) but when i do `npm run start` it can't get process.env.

How can i configure it properly? What is the solution? 

Any example?

**Comment by ManUtopiK** [comment]
I do that:
`pm2 start 'npm run build && npm start'`

**Comment by Revel109** [comment]
That's not the issue. I can run that. But i did set my production backendApi url in pm2 configs environment.

I can't get execute that.

**Comment by xhfHIT** [comment]
Try like this:
`pm2 start npm --name 'demo' -- run start`

**Comment by Revel109** [comment]
Nuxt is running but can't access the backendApiUrl after pm2 restart.
