### ISSUE TITLE
Incorrect work with external package after using Back browser button.

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#635]
Hi.

Often I am expecting issues with packages after I **route** in Nuxt app. I mean, they working, but until I begin to route through Nuxt site. 

For example, I have an issue with this.

1. Go to http://messy-straw.surge.sh/images/ Wait till images load. 
2. Then go to Main Page.
3. And then return to previous page with **Back browser button**. Images doesn't lazyload again. 
4. In all other use cases code is working fine, bug appears **only when using Back** 

Can you please point me how to handle this bug? I am using https://github.com/ccforward/progressive-image as a plugin in this example.

**Comment by alexchopin** [comment]
@kodekrendel your link doesn't work and you needed more code snippets to help you.

**Comment by kodekrendel** [comment]
I was waiting a wekk for reply and yesterday delete this example. Will do another one.

**Comment by kodekrendel** [comment]
Don't know why, but now everything working not like before. Even worst. Before it very nicely blur in images (and the issue was ONLY with Back button), now it's do nothing at all. http://furry-spring.surge.sh

plugin

```
import Vue from 'vue'
import progressive from 'progressive-image/dist/vue'

Vue.use(progressive, {
  removePreview: true,
  scale: true
})
```
ssr false

template
```
<template>
  <div class="">
    <div v-for="item in imgs">

      <div class="progressive">
        <img class="preview lazy" v-progressive="item.src" :src="item.preview" />
      </div>
    </div>
  </div>
</template>

<script>

export default {
  data () {
    return {
      imgs: [
        {
          src: 'http://7xiblh.com1.z0.glb.clouddn.com/progressive/2.jpg',
          preview: 'http://7xiblh.com1.z0.glb.clouddn.com/progressive/r2.jpg'
        },
        {
          src: 'http://7xiblh.com1.z0.glb.clouddn.com/progressive/3.jpg',
          preview: 'http://7xiblh.com1.z0.glb.clouddn.com/progressive/r3.jpg'
        }
      ]
    }
  }
}
</script>
```

**Comment by alexchopin** [comment]
There is an error with the library option `removePreview: true`.
`DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
`

**Comment by kodekrendel** [comment]
Removing removePreview: true doesn't change anything.

What error are you reffering to @alexchopin

**Comment by kodekrendel** [comment]
Problem remains. This is best package with progressive loading I found, and it doesn't work with Nuxt :cry:

**Comment by Atinux** [comment]
Hi @kodekrendel 

It works perfectly fine with Nuxt.js, just use it as a plugin and set `ssr: false`.

See my example: https://glitch.com/edit/#!/nuxt-progressive-image

Demo: https://nuxt-progressive-image.glitch.me/

**Comment by Atinux** [comment]
For the issue of the `back` button, I believe that it's because of the `progressive-image` library which has a bug and don't see that the image has to be loaded again.

**Comment by kodekrendel** [comment]
Yes, it's working but without Back button. My guess is that we could somehow use $route here to trigger it again, but I can't make it @Atinux
