### ISSUE TITLE
nuxtServerInit function is not called on production but works fine on localhost

### ISSUE THREAD

**Issue by mavinemvento** [nuxt/nuxt.js#6355]
I am using nuxt with cloude firebase. Im using nuxtServerInit function to get auth user from cookies. Function works fine on localhost but is not executed on production
 
In store/index.js 
`export const actions = {

  async nuxtServerInit({ commit }, { req }) {
    const user = getUserFromCookie(req)
    if (user) {
      await commit('users/setCurrentUser', {
        uid: user.user_id,
        email: user.email,
        displayName: user.name,
      });
    }
  }
}`

Please Help

**Comment by thefigman** [comment]
I'm having the same problem. Are you able to resolve this one @mavinemvento?

**Comment by dumptyd** [comment]
This fixed it for my static app https://github.com/nuxt/nuxt.js/issues/7051#issuecomment-604914461. Might be worth a try.
