### ISSUE TITLE
Vue 2.3.x broke middleware in dev

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#636]
After upgrading (which the caret dependencies allow) middleware runs multiple times with different contexts.
As an example try the official i18n demo, it is completely broken... but only in dev.
Build+start work fine.
```sh
yarn upgrade vue-template-compiler@~2.2.6 vue-server-renderer@~2.2.6 vue-template-compiler@~2.2.6 vue@~2.2.6
```
fixed mine.

**Comment by IncSW** [comment]
Same problem when page has asyncData and dev mode.

**Comment by Atinux** [comment]
Will be fixed in upcoming release.
