### ISSUE TITLE
ava e2e tests don't work with nuxt

### ISSUE THREAD

**Issue by alexarsh** [nuxt/nuxt.js#6360]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://github.com/cosmicjs/nuxtjs-website-boilerplate](https://github.com/cosmicjs/nuxtjs-website-boilerplate)

### Steps to reproduce

1.) Clone the repo
2.) Run: npm install
3.) Run: npm install jsdom ava
4.) Copy index.test.js from https://nuxtjs.org/examples/testing/ like written in documentation (into test dir)
5.) Run: ava --serial --verbose

### What is expected ?

The tests are expected to fail because it won't find 'Hello world!' on the page

### What is actually happening?

nuxt.server is failing to initialize and the the tests are failing with the following error:

✖ before hook Rejected promise returned by test
  ✖ 2 tests remaining in test/index.test.js

  1 hook failed

  before hook

  /Users/alex/nuxtjs-website-boilerplate/test/index.test.js:18

   17:   await new Builder(nuxt).build()
   18:   await nuxt.server.listen(4000, 'localhost')
   19: }, 30000)

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'Cannot read property \'listen\' of undefined',
  }

### Additional comments?

I also opened similar bug here: https://stackoverflow.com/questions/57760338/how-to-run-nuxt-ava-e2e-tests
The difference is that I use Vuex in my project and there is a little more details in the exception, but it fails exactly on the same place

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9727">#c9727</a>)</em></sub></div>

**Comment by TimSusa** [comment]
I investigated a couple of hours today and I also did not succeed to get the example running.

**Comment by pimlie** [comment]
Maybe you could try `request-promise-native` + eg `cheerio` instead of nuxt's `renderAndGetWindow`. Have experienced issues with the latter myself as well, possibly related to modern mode.

**Comment by alexarsh** [comment]
Thanks for the investigation, @TimSusa.
All the idea is that the tests should run their server. (My purpose is to integrate the tests in my circleCI)
And in any case, the nuxt documentation should be fixed with some working example...

**Comment by TimSusa** [comment]
Hey, @pimlie and @alexarsh 

thank you for your quick answers. For today we found a way to get that stuff running, due to yielding window from new JSDOM(html). Maybe you could use that for your example:

``` 
import { resolve } from 'path';
import test from 'ava';
import { Nuxt, Builder } from 'nuxt';
import { JSDOM } from 'jsdom';

// Do not forget about your ENV
require('dotenv').config();

// TODO: Try to use context instead of global vars
let nuxt = null;

// Init Nuxt.js and start listening on localhost:4000
test.before('Init Nuxt.js', async t => {
  const rootDir = resolve(__dirname, '../../');

  let config = {};

  config = require(resolve(rootDir, 'nuxt.config.js'));

  config.rootDir = rootDir; // project folder
  config.dev = false; // production build
  config.plugins = []; // remove the plugins

  nuxt = new Nuxt(config);
  await new Builder(nuxt).build();
  await nuxt.server.listen(4000, 'localhost');
});

// Example of testing only generated html
test('Route /something exits and render HTML', async t => {
  const context = {};

  const object = await nuxt.server.renderRoute(
    '/something',
    context
  );

  // We grab the window due to JSDOM 
  const { window } = new JSDOM(object.html).window;

  t.truthy(window.document.title);
});

test.after('Closing server', t => {
  nuxt.close();
});
```

**Comment by TimSusa** [comment]
> Maybe you could try `request-promise-native` + eg `cheerio` instead of nuxt's `renderAndGetWindow`. Have experienced issues with the latter myself as well, possibly related to modern mode.

-> Sounds very interesting. We should keep your approach in mind.

**Comment by TimSusa** [comment]
Another question would be, if we could just use jest for the example or just offer two examples?

**Comment by alexarsh** [comment]
@TimSusa, tried to follow your example, but it still fails on the same line:
`await nuxt.server.listen(4000, 'localhost');`
with the same error:
`TypeError {
    message: 'Cannot read property \'listen\' of undefined',
  }`

**Comment by TimSusa** [comment]
At a first shot, I would claim your server is undefined.

**Comment by alexarsh** [comment]
@TimSusa, my server is not running, because the before hook should run it. And according to documentation it should work....

**Comment by alexarsh** [comment]
Hi, Any news about this one?

**Comment by mcauto** [comment]
> Hi, Any news about this one?

I solved it with reference to this.

https://github.com/vinayakkulkarni/nuxt-ava-e2e-unit-testing

**Comment by Emiller88** [comment]
This is still not working out of the box. I'll post a solution if I find one.

**Comment by Emiller88** [comment]
Quick update. It has to do with the `ava.setup.js`. I tried this one instead https://github.com/vinayakkulkarni/nuxt-ava-e2e-unit-testing/blob/master/test/_setup.js and the tests passed.
