### ISSUE TITLE
Failed to execute 'write' on 'Document'

### ISSUE THREAD

**Issue by liaohui1080** [nuxt/nuxt.js#6369]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[http://www.tianliaohui.com:8010/app](http://www.tianliaohui.com:8010/app)

### Steps to reproduce

In china Uses chinaunicom Access http://www.tianliaohui.com:8010/app sees the following tips,and the chrome browser refreshes

Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

### What is expected ?

Reason

### What is actually happening?

Reason

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9736">#c9736</a>)</em></sub></div>

**Comment by pimlie** [comment]
I am not sure what the issue is, could you please create a reproduction of the error on codesandbox?
