### ISSUE TITLE
Nuxt build problem

### ISSUE THREAD

**Issue by Invictorp** [nuxt/nuxt.js#6377]
Build successfully, but sass files doesnt included in production, while in dev everything working ok.

nuxt confing
`export default {
  mode: 'universal',

  head: {
    title: pkg.name,
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: pkg.description }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  loading: { color: '#ff674d' },

  css: [
    '@/assets/scss/editor.scss',
    'vue-plyr/dist/vue-plyr.css',
    'vuesax/dist/vuesax.css',
    '~/assets/css/iconfont.css',
    '~/assets/scss/main.scss', 
  ],

  plugins: [
    '@/plugins/globals',
    '@/plugins/axios',
    '@/plugins/themeConfig',
    '@/plugins/perfectScrolBar.client.js',
    '@/plugins/feathersIcons.js',
    '@/plugins/bus'
  ],

  buildModules: [
    '@nuxtjs/tailwindcss',
  ],

  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/svg-sprite',
    '@nuxtjs/style-resources',
    'nuxt-purgecss'
  ],

  axios: {
    baseURL: process.env.BASE_URL || 'http://localhost:8000',
    credentials: false,
    proxyHeaders: true,
  },

  build: {
    extractCSS: true,
    extend(config, ctx) {
    }
  }
}
`

**Comment by joelbqz** [comment]
Any update on this?
