### ISSUE TITLE
set custom Environment on nuxt build

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#638]
Hello. I want set custom custom Environment

`set NODE_ENV=test && nuxt build`

in my code 

` console.log('NODE_ENV', process.env.NODE_ENV) => production`

Any ideas? How set Environment?

**Comment by mheppner** [comment]
If you're using bash or something similar, just set the variable directly and run your command. [`set`](http://linuxcommand.org/lc3_man_pages/seth.html) does not do what you think it does. Use `NODE_ENV=test nuxt build` to set the variable once for that command, or set it for the duration of your shell with `export NODE_ENV=test`. If you want to set it permanently, add the export line to your `.bashrc` file.

**Comment by awronski** [comment]
use https://www.npmjs.com/package/cross-env


```cross-env NODE_ENV=production nuxt build```

**Comment by wargt** [comment]
not working (

I have Error Uglifyjs library

```
ERROR in 0.app-98916286995361.js from UglifyJs
Unexpected token punc «(», expected punc «:» [0.app-98916286995361.js:415,21]
```

**Comment by alexchopin** [comment]
@wargt we need more details and code snippets to help you.
What template are you using for example?

**Comment by Atinux** [comment]
Why do you want to set custom env variables for the build process @wargt ?

For production, you need to give environements variables when launching `npm start`.

**Comment by wargt** [comment]
I have - test server

On the test server - a need use one config file

i have - production server  

On the priduction server - a need use other config file

const config = {
apiHost: process.env.NODE_ENV == 'test' ? 'http://test-url': 'http://production-url'
}

**Comment by JeremieLapert** [comment]
Hi @wargt 
have you found a solution for your problem?
Thank you in advance for your answer!

**Comment by chovy** [comment]
I also don't know how to change api url based on NODE_ENV. Can someone give example?
