### ISSUE TITLE
Recursive component don't render in prod mode (typescript)

### ISSUE THREAD

**Issue by NomNes** [nuxt/nuxt.js#6385]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/NomNes/Nuxt-ts-recursive-bug](https://github.com/NomNes/Nuxt-ts-recursive-bug)

### Steps to reproduce

`npm run build`
`npm run start`
open http://localhost:3000

### What is expected ?

```
<ul>
  <li>
    item 1
    <!---->
  </li>
  <li>
    item 2
    <!---->
  </li>
  <li>
    item 3
    <ul>
      <li>
        children 1
        <!---->
      </li>
      <li>
        children 2
        <!---->
      </li>
    </ul>
  </li>
</ul>
```

### What is actually happening?

```
<ul>
  <li>
    item 1
    <!---->
  </li>
  <li>
    item 2
    <!---->
  </li>
  <li>
    item 3
    <tree items="[object Object],[object Object]"></tree>
  </li>
</ul>
```

### Additional comments?

If run `npm run dev` - all ok

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9745">#c9745</a>)</em></sub></div>

**Comment by NomNes** [comment]
hack it with:
```
const components: any = {}
@Component({
  components
})
export default class Tree extends Vue {}
components.Tree = Tree
```
:)

**Comment by pimlie** [comment]
Not sure about ts, but in js you cant just use a component recursively within itself (or within a child of itself). You need to add the component dynamically otherwise it wont work:
```
  // tree.vue
  components: {
    Tree: () => import('tree.vue')
  }
```

If i remember correctly this is a webpack issue (dont have a link ready unfortunately) but I guess something similar is at play here.

**Comment by NomNes** [comment]
@pimlie to use a component recursively, you do not need to import it (and you cannot, because it is recursive). It's about using a component within itself.
I repeated all the same without typescript - there is no this bug. It seems this is true only for `nuxt-ts` (`@nuxt/typescript-runtime`)

**Comment by NomNes** [comment]
I can't find it in the documentation right now, but I do remember wording like "to use a component recursively, a name must be defined." I have been using it for a long time, but typescript I use recently and only in it faced such a problem. If necessary, I can add a repository without ts where everything is normal

**Comment by pimlie** [comment]
Ah yes, ofc thanks. So what I said only applies to using a recursive component within a child of itself, which is different from what youre doing here. Cant help you with ts unfortunately.
