### ISSUE TITLE
How to rename the layout id '__layout'

### ISSUE THREAD

**Issue by ffey** [nuxt/nuxt.js#6388]
### What problem does this feature solve?

I want rename the layout div's id name , but I can't find solution from nuxt.js docs site.

### What does the proposed changes look like?

maybe can in nuxt.config.js setting 
globals: [
  layoutId: 'customId'
]

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9749">#c9749</a>)</em></sub></div>

**Comment by manniL** [comment]
What would be the purpose of that feature?

**Comment by j-o-sh** [comment]
Hi,

Would you bother reopening this? Being able rename actually ALL of the basic ids serves the purpose of playing nice within a greater landscape.

We are having this problem in an application that is built upon the SCS paradigm, where the rendered HTML of our Nuxt application may be completely serverside inncluded into the page of another application. So to be able to not polute the 'global' id namespace and to be able to exist alongside other nuxt apps or other frameworks, we need to be able to rename basically EVERY static id generated from Nuxt.

Kind Regards,
Josh

**Comment by manniL** [comment]
@j-o-sh this is mostly the case already (via globalName). For the layout id, we plan to make it dynamically based on the layout used (see #6806)

**Comment by j-o-sh** [comment]
@manniL About #6806 I know about that and I am looking foward to it. :) thx.

Until then however, this plain ID still lingers in the code and prevents us from using Nuxt productively in an SCS context.

I've had a quick look over the code and didn't find the `__layout` Id used by nuxt for anything, except setting it.  Am I correct in assuming that, if I were to remove the id after the fact in a self-written hack, I wouldn't break anything?

**Comment by manniL** [comment]
> Am I correct in assuming that, if I were to remove the id after the fact in a self-written hack, I wouldn't break anything?

I'd say so, yes.

**Comment by j-o-sh** [comment]
Argh,

Sorry for bothering. But I yust wrote a middleware, using the `route:render` hook to remove the id from the generated html, but it seems that this will get overrwritten again in the client, as soon as Nuxt is initialized there again. :(

Any idea, where there might be a better place to implement that?

**Comment by manniL** [comment]
The easiest way would be to override `/template/App.js` by creating a `/app/App.js` file in your source root and copy the content from the original [`App.js`](https://github.com/nuxt/nuxt.js/blob/e8aca9eb117851047e82e94948ff8b4bcb464b1a/packages/vue-app/template/App.js) but remove the `domProps: {
        id: '__layout'
      }` part.
