### ISSUE TITLE
when i use nuxt in ie9 , i find  it useless to set var in asyncData function

### ISSUE THREAD

**Issue by zhancheng** [nuxt/nuxt.js#639]
for example

i write 
`asyncData(context){
        return {
            keyword: context.query.q
        }
    }
`
then
`
mounted(){
     console.log(this.keyword)
}
`
it works fine in chrome but  undefined in ie9 , should it does not surport ie9？

**Comment by zhancheng** [comment]
@alexchopin  i find the problem just cause by this issue [#640](https://github.com/nuxt/nuxt.js/issues/640#event-1062035902)

**Comment by alexchopin** [comment]
IE9 do not support HTML5 History API, so vue-router switch to hash mode automatically. It's not related to Nuxt.
