### ISSUE TITLE
Change banner color

### ISSUE THREAD

**Issue by Exeteres** [nuxt/nuxt.js#6397]
### What problem does this feature solve?

Perhaps this is the strangest feature request in this repository...<br/>
I think we should update the banner color of `nuxt-ts` to match the color scheme :D

### Nuxt JavaScript

<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/d7aed320-d4a2-11e9-9fd9-c50b8b6d1e7c.png" height="150"/>
<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/fc54d800-d4a2-11e9-9fd9-c50b8b6d1e7c.png" height="150"/>

### Nuxt TypeScript

<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/db3d02f0-d4a2-11e9-9fd9-c50b8b6d1e7c.png" height="150"/>
<img src="https://cmty.s3.eu-west-1.amazonaws.com/71995937/ffd7e440-d4a2-11e9-9fd9-c50b8b6d1e7c.png" height="152"/>

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9760">#c9760</a>)</em></sub></div>

**Comment by Atinux** [comment]
OMG I love it 😍

**Comment by manniL** [comment]
Do it! 🙌
