### ISSUE TITLE
i find in ie 9 , when i visit a url such as 'http://www.b.com' it will auto add '#' to the end

### ISSUE THREAD

**Issue by zhancheng** [nuxt/nuxt.js#640]
i find in ie 9 , when i visit a url such as 'http://www.b.com' it will auto add '#' to the end 

so it  becomes 'http://www.b.com/#/'

it cause that if i visit a page not index such as 'http://www.b.com/search'

it will becomes 'http://www.b.com/#/search' , the content after # wont commit to the server,  take a fill problem.

**Comment by alexchopin** [comment]
It's not related to Nuxt.
IE9 do not support HTML5 History API.
