### ISSUE TITLE
Duplicate data-v-* attribute with render function scopedSlot and scoped styles

### ISSUE THREAD

**Issue by raWINce** [nuxt/nuxt.js#6401]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/raWINce/nuxt-duplicate-data-v-attribute](https://github.com/raWINce/nuxt-duplicate-data-v-attribute)

### Steps to reproduce

Reload the page

### What is expected ?

Correct html without duplicate attributes that is valid according to https://validator.w3.org

### What is actually happening?

The `div` rendered inside the slot has a dupplicate `data-v-*` attribute. The html provided by the nuxt server is thus no valid html according to https://validator.w3.org

![duplicate-data-v-attribute.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/fb32c920-d545-11e9-9fd9-c50b8b6d1e7c.png)

This behaviour only occurs, when
- the parent of the component with the render function has scoped styles
- the `render` function directly returns the slot: `return this.$scopedSlots.default()`
- the child component has scoped styles and a slot

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9763">#c9763</a>)</em></sub></div>

**Comment by pimlie** [comment]
I think its more likely this will turn out to be a [vue-loader](https://github.com/vuejs/vue-loader) issue then nuxt. Therefore I'd advise you to create an issue in their repo as vue-loader is responsible for adding the `data-v-*` tags for scoped css

**Comment by raWINce** [comment]
The issue is still open; see [vue-loader-issue](https://github.com/vuejs/vue-loader/issues/1590)
