### ISSUE TITLE
Generate 404.html with global _.vue

### ISSUE THREAD

**Issue by mxrlkn** [nuxt/nuxt.js#6402]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-txjzy](https://codesandbox.io/s/codesandbox-nuxt-txjzy)

### Steps to reproduce

Run the generate script

### What is expected ?

that a proper 404.html page is generated.

### What is actually happening?

a 404.html is generated with `fallback: "404.html"` but it's not correct. it doesn't say the statuscode or the message. 

### Additional comments?

if i add `/404` to my routes array in generate.routes, the 404.html gets generated correctly, the problem is that I want to run generate with `--fail-on-error` so I don't deploy any errors, but that fails on /404.html.

Then I tried fallback: "404.html" and fallback: true, but those don't generate a proper 404.html page.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9764">#c9764</a>)</em></sub></div>

**Comment by manniL** [comment]
My first guess is that the problem lies in the `_.vue`.

**Comment by manniL** [comment]
Nvm, can't reproduce with the setup you've provided (without 404.html in the routes array).

![image](https://user-images.githubusercontent.com/640208/65821517-ec2d1680-e236-11e9-8da4-57a082d58457.png)

**Comment by mxrlkn** [comment]
the _.vue file does manage error handling:

```
async asyncData({ route, error }) {
  const api = {
    "/": { title: "home" }
  };

  // fetch data
  const data = api[route.path];

  if (!data) {
    error({ statusCode: 404, message: "no page" });
  }

  return { data };
}
```

I can't figure out why it uses the fallback even though I'm calling the error function.

**Comment by mxrlkn** [comment]
Okay so there is currently no way to generate an error page with _.vue and --fail-on-error?

**Comment by manniL** [comment]
It is, as seen on the screen attached above.  It also works as intended (showing “no page”)

**Comment by mxrlkn** [comment]
Okay I see. I thought that the fallback 404 error page was more of a wrongly generated one. I guess my real problem is with the fallback error page + error layout then.

So I've added an error.vue layout to the sandbox, which I assumed would be used with the fallback option. But it doesn't use my error layout. I guess because the fallback is just a static one included in nuxt.

So I can't use a custom error layout for the 404 page while generating with _.vue and --fail-on-error?
