### ISSUE TITLE
Client hydration fails with async components and breakpoint dependent html

### ISSUE THREAD

**Issue by raWINce** [nuxt/nuxt.js#6403]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/raWINce/nuxt-async-loading-client-side-hydration](https://github.com/raWINce/nuxt-async-loading-client-side-hydration)

### Steps to reproduce

- in a component render html that depends on the viewport (e.g. using [`vue-mq`](https://github.com/AlexandreBonaventure/vue-mq) with `v-if="$mq === 'lg'"`)
- include those components as an [async component](https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components)
- reload the page on a different viewport

### What is expected ?

Do not throw warning/errors after reloading the page (during client hydration).

The client hydration should work with async components, too, when using e.g. [nuxt-mq](https://www.npmjs.com/package/nuxt-mq)-dependent html.

### What is actually happening?

After reloading, the client hydration fails and throws `[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`.

In a more complicated setup this leads to an error that crashes the entire app (i.e. all components that are rendered later in the DOM do not work). I did not have time to make an example for this case, though

### Additional comments?

- Wrapping the component within `no-ssr` solves the issue. This, however,  is not a solution for me because I need the html to be rendered on the server, which is the reason for choosing nuxt in the first place
- including the component without dynamic import also solves the issue. 
    - this makes me think that viewport dependent html can work with nuxt
    - hence, this is probably not a `nuxt-mq` issue

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9765">#c9765</a>)</em></sub></div>

**Comment by pimlie** [comment]
Isnt this just because with an async component `$mq` is already been updated to the correct value once the dynamic component chunk is loaded? I.e. does hydration also fail if you load the page on the same `$mq` that was used for ssr?

You could try to add a [`webpackPreload:true` magic comment](https://webpack.js.org/api/module-methods/#magic-comments) so Vue doesnt has to wait for the component to download on hydration.

But in general I dont think there is anything that Nuxt.js can do about this.
