### ISSUE TITLE
Docs misleading about extending routes

### ISSUE THREAD

**Issue by nkoder** [nuxt/nuxt.js#641]
Hi

I was trying to extend routes with `router. extendRoutes` in `nuxt.config.js`. In documentation https://nuxtjs.org/api/configuration-router/#extendroutes there is written, that:
> The schema of the route should respect the vue-router schema.

So I've tried to use some vou-router magic, eg. define redirect in form of `{ path: '/a', redirect: '/b' }` as described here https://router.vuejs.org/en/essentials/redirect-and-alias.html or pass props as described here https://router.vuejs.org/en/essentials/passing-props.html

Then it appeared that some part of vue-router schema are not passed to `.nuxt/router.js` at all! It looks like only some explicitely defined properties are passed, as you can see here: https://github.com/nuxt/nuxt.js/blob/v0.10.6/lib/app/router.js#L15

In my opinion either documentation should not suggest vue-router schema support (or `.nuxt/router.js` should consists all routes' properties provided by User, even custom ones :-) )

**Comment by alexchopin** [comment]
@nkoder `redirect`, `alias` and `meta` are not available with nuxt. We'll update the documentation. I move this issue to the correct repo.

**Comment by nkoder** [comment]
Thanks. By the way, do you think would it be OK to support more routes' stuff in `extendRoutes`? For example my case would be to replace `component` ant to pass `props` to it. I've even started writing a change in Nuxt code to achieve that, but then I realized that I have to understand child routes better first.

**Comment by papertokyo** [comment]
Will redirect be available in a future release? I'd prefer to keep routing defined within the app settings rather than doing it at the server level. (Unless there's a sound reason not to.)

**Comment by Coletrane** [comment]
This still seems to be an issue as the docs say `extendRoutes` should respect the vue-router schema. I'm with @papertokyo I want this in a future release.

**Comment by feryardiant** [comment]
Agreed with @nkoder

I've tried anything to _customize_ my `route.meta` thru `extendRoutes` but nothing's working. As @Atinux [said](https://github.com/nuxt/nuxt.js/issues/466#issuecomment-337836944)

> I am actually implementing `meta` property in page components and will be available in next release :)

now @alexchopin said

> `redirect`, `alias` and `meta` are not available with nuxt.

So which one is actually correct here?

**Comment by Atinux** [comment]
Please take a look at https://github.com/nuxt/nuxt.js/blob/dev/lib/app/router.js#L7-L15 to know the answer directly.

`meta` is directly from Page components.
`redirect` has been implemented.
`alias` is not available.

**Comment by feryardiant** [comment]
Thanks for reply @Atinux 

Yes, I can confirm that `meta` inside page components is working, but it's only accessible from `plugins` and `middlewares` as an array of page's metas. Even It couldn't be accessible from the page component it self. That's mean we have to `store` them to be able to access to from `pages` and `layouts` components.

Is that actually a desired behaviour?

_note: sorry for my poor english_

**Comment by Atinux** [comment]
@feryardiant We will improve the `meta` property to give it directly into `$route.meta` so it would be accessible from anywhere.

**Comment by feryardiant** [comment]
Really glad to hear that @Atinux

**Comment by javialon26** [comment]
@Atinux is possible this functionality?, see #3134 Thank you!

**Comment by awronski** [comment]
@Atinux Could you look at it?

https://cmty.app/nuxt/nuxt.js/issues/c8004
