### ISSUE TITLE
webvisor does not work in yandex.metrika

### ISSUE THREAD

**Issue by inweid** [nuxt/nuxt.js#6413]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[http://nothing](http://nothing)

### Steps to reproduce

include to the project https://github.com/nuxt-community/modules/tree/master/packages/yandex-metrika

### What is expected ?

webvisor is vorked

### What is actually happening?

webvisor is not vorked

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9775">#c9775</a>)</em></sub></div>

**Comment by aldarund** [comment]
Its not issue with nuxt itself. please create issue in proper project e.g.  https://github.com/nuxt-community/modules
