### ISSUE TITLE
Allow nuxt-child routes that are NOT the same name as the parent

### ISSUE THREAD

**Issue by connecteev** [nuxt/nuxt.js#6418]
### What problem does this feature solve?

Is it possible to have nuxt-child routes that are NOT the same name as the parent? They all look 99% the same, save for a small section of content. 
I want my home page / to be the parent
And:
/top/week
/top/month
/top/year
to all inherit from and be children of the home page. I believe that the [current naming convention](https://nuxtjs.org/api/components-nuxt-child/) would not allow setting these up as children of the homepage. Is there a way around this?

### What does the proposed changes look like?

Allow nuxt-child routes that are NOT the same name as the parent

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9778">#c9778</a>)</em></sub></div>

**Comment by pimlie** [comment]
Yes, use extendRoutes

The use of a naming convention like Nuxt.js does for creating routes is designed to easily work in `95+%` of all cases. Your requirement is unfortunately not included in that number ;)

**Comment by connecteev** [comment]
@pimlie thanks for clarifying...turns out you dont need an extendRoutes config for this.
I just created an index.vue file and an index/top/_slug.vue and everything works fine!

**Comment by pimlie** [comment]
Interesting, didnt expect that to work because of the extra `top` level.
