### ISSUE TITLE
Route meta fields with TypeScript

### ISSUE THREAD

**Issue by nargesmomenyan** [nuxt/nuxt.js#6419]
### What problem does this feature solve?

set permission key in ts scripts in pages as route meta and check the permission in the middleware

### What does the proposed changes look like?

in js scripts this works:   
meta: {
        authorization: ['Actions/List']
  },

And, in the middleware the permission could be checked like this:
let authorization: Array<IAuthorization> = [];
        route.meta.forEach(item => {
        if (item.authorization && typeof item.authorization !== undefined) {
            authorization = item.authorization;
            result = false;
        }
    });

However, the meta does not work in ts vue files.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9780">#c9780</a>)</em></sub></div>

**Comment by Niputi** [comment]
@nargesmomenyan definition "meta" key was added recently https://github.com/nuxt/typescript/pull/89

**Comment by NMathar** [comment]
Nice this works very well

```
    @Component({
        middleware: 'authenticated',
        meta: {
            authorization: ['Group/test']
        }
    })
```

**Comment by manniL** [comment]
Closing here then.
