### ISSUE TITLE
Sass Loader

### ISSUE THREAD

**Issue by luciferavada** [nuxt/nuxt.js#6421]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://jsfiddle.net/zutw43rx/](https://jsfiddle.net/zutw43rx/)

### Steps to reproduce

Add lang="sass" to any component's style.

### What is expected ?

The module should be loaded with the sass-loader.

### What is actually happening?

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'indentedSyntax'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/six/Code/scratch/test-nuxt/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/six/Code/scratch/test-nuxt/node_modules/sass-loader/dist/index.js:36:28)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9782">#c9782</a>)</em></sub></div>

**Comment by pimlie** [comment]
Its a known issue due to config option change in sass-loader. Dont know the exact version numbers by head, but you should probably use this version:

`<the major version you currently have installed which causes the error> - 1`

**Comment by Anima-t3d** [comment]
Changelog: https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#800-2019-08-29

**Comment by manniL** [comment]
Resolved in #6460

Workaround is to apply the changes manually until the next release, downgrading **or** using nuxt-edge
