### ISSUE TITLE
Transition function doesn't have access to data object variables

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/nuxt.js#6422]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codesandbox.io/embed/codesandbox-nuxt-vlqcy](https://codesandbox.io/embed/codesandbox-nuxt-vlqcy)

### Steps to reproduce

1. Load up the sandbox URL.
2. Get it to build the project with the settings and transition property.
3. See that the transition property function is unable to access `hasSwipeSpeed`

### What is expected ?

I should be able to access the variables within data from the transition property somehow.

### What is actually happening?

I get an error, and am unable to access the variables within data from the transition property function.

### Additional comments?

Not entirely sure of the best way to access my variables, I need to be able to access them as I'm using Vuex in my project and update these variables dynamically:

```
transition(to, from) {
    if (from) {
      return to.params.id < from.params.id
        ? `slide-left-${this.hasSwipeSpeed}`
        : `slide-right-${this.hasSwipeSpeed}`;
    } else {
      return `slide-left-${this.hasSwipeSpeed}`;
    }
  }
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9784">#c9784</a>)</em></sub></div>

**Comment by Limonische** [comment]
Experiencing the same problem right now. I need to be able to choose the direction of transition without the query parameters, which is imposible without accessing data or vuex.

**Comment by xyllu** [comment]
I am not experiencing this problem in dev mode, but in production mode, I certainly am experiencing relevant problems and that transitions are not working at all in production mode. Earlier versions, the transition works in production mode, but not in the latest version.

**Comment by manniL** [comment]
Possibly related to #6466 ?

**Comment by Limonische** [comment]
> Possibly related to #6466 ?

No it happens with regular functions as well.

**Comment by Limonische** [comment]
I have found a workaround for people experiencing the same problem. You could use css variables to set a direction for animation.
`\:root
    --pageslide-enter: translateX(-100%)
    --pageslide-leave: translateX(100%)

.pageslide
    &-enter-active, &-leave-active
        +transition(transform, .5s)
    &-enter
        transform: var(--pageslide-enter)
    &-leave-to
        transform: var(--pageslide-leave)`

And then change variables with js before changing route.

`
const { style } = document.documentElement
style.setProperty('--pageslide-enter', 'translateX(100%)')
style.setProperty('--pageslide-leave', 'translateX(-100%)')
`
