### ISSUE TITLE
Scoped slots together with async component breaks SSR

### ISSUE THREAD

**Issue by bdrtsky** [nuxt/nuxt.js#6423]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/bdrtsky/scoped-slots-ssr-issue](https://github.com/bdrtsky/scoped-slots-ssr-issue)

### Steps to reproduce

If you use scoped slot and it's child, that is async imported, then child content doesn't gets SSR'd.

if you remove scoped slot component OR use scoped slot with regular component import then it's SSR'd just fine.

### What is expected ?

Expect server rendered content.

### What is actually happening?

Content is not server rendered.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9783">#c9783</a>)</em></sub></div>

**Comment by bdrtsky** [comment]
If you insert any html element along with async component in scoped slot, then this component is SSR'd fine:

```
<damned-scoped-slot :items="[content]">
      <template v-slot="{ lazyItems: lazyArticles }">
          <span>ssr hack</span>
          <async-comp />
      </template>
</damned-scoped-slot>

```

**Comment by manniL** [comment]
Does that also happen with the pure `vue-server-renderer`?

**Comment by bdrtsky** [comment]
Not sure I can reproduce it with `vue-server-renderer`...
You think it could be `vue-server-renderer` issue?

**Comment by haozewu** [comment]
I also have this problem when using tables in element-ui!

I write the following in \<template\>

```
    <el-table v-loading="loading" :data="tableData" style="width: 100%" highlight-current-row
      @current-change="selectNovel">
      <el-table-column prop="name" label="col_1">
      </el-table-column>
      <el-table-column prop="author" label="col_2">
      </el-table-column>
    </el-table>
```

and get tableData in asyncData function like this

```
  asyncData(context) {
    return axios.get("http://localhost:2816/api/data?source=0")
      .then((res) => {
        let {
          data
        } = res.data
        return {
          tableData: data
        };
      })
  },
```
it works well when I allow js in chrome. But when I turn javascript off, the table component cannot be render.

However, when I use {{tableData}} in \<template\>, the page really get the data.

**Comment by manniL** [comment]
@bdrtsky Yes, this could be. A newcomer-friendly way to get started with the pure vue-server-render can be found @ https://ssr.vuejs.org/guide/#installation

**Comment by bdrtsky** [comment]
Ok, I will try to reproduce with Vue SSR

**Comment by bdrtsky** [comment]
Hey bot, I can still reproduce this, but didn't had time to try it with Vue SSR yet. Will do next weekend, I hope.

**Comment by manniL** [comment]
probably related: https://github.com/vuejs/vue/issues/10391
