### ISSUE TITLE
Wrong scrollBehavior with nested pages

### ISSUE THREAD

**Issue by MaxKostenko** [nuxt/nuxt.js#6425]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codesandbox.io/s/example-hello-world-84145](https://codesandbox.io/s/example-hello-world-84145)

### Steps to reproduce

1. Click Check Example
2. Scroll to page bottom
3. Click link "Click Me"
4. Next page won't be scrolled to top - Wrong
5. Click "Most interesting situation"
6. You will be navigated to page with other parent page, but still page will not be scrolled to top - Wrong

### What is expected ?

Page  definitely should be scroll to top if you go to other page 

### What is actually happening?

Scrolling not happening

### Additional comments?

Solution:
Add rule to router.scrollBehavior.js

if (
    Pages.length < 2 &&
    Pages.every(Page => Page.options.scrollToTop !== false)
  ) {

..........

  } else if(to.name !== from.name) {
       position = { x: 0, y: 0 };
  }

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9786">#c9786</a>)</em></sub></div>

**Comment by pimlie** [comment]
The docs explicitly state the original behaviour:
```
By default, Nuxt.js scrolls to the top when you go to another page, but with children routes, Nuxt.js keeps the scroll position. If you want to tell Nuxt.js to scroll to the top when rendering your child route, set scrollToTop to true:
```
From: https://nuxtjs.org/api/pages-scrolltotop#the-scrolltotop-property
