### ISSUE TITLE
Uncaught (in promise) ReferenceError: mapboxgl is not defined

### ISSUE THREAD

**Issue by MSkred** [nuxt/nuxt.js#6427]
### Version

[2.9.2](https://github.com/nuxt.js/releases/tag/2.9.2)

### Reproduction link

[https://delibe.staging.letsgocity.be/commune/54/conseil/1843/point/11741](https://delibe.staging.letsgocity.be/commune/54/conseil/1843/point/11741)

### Steps to reproduce

my nuxt.config.js

```
  build: {
    publicPath: `/${require('./secrets.json').NODE_ENV}/_nuxt/`, // <= add the path to the cached files
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      })
    ],
    extend (config, ctx) {
      config.node = {
        fs: 'empty'
      }
    },
  },

```

### What is expected ?

use mapboxgl in my project

### What is actually happening?

mapboxgl is undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9789">#c9789</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @MSkred 

I don't see any error in your reproduction link 🤔

**Comment by manniL** [comment]
Please provide a minimal reproduction with CodeSandbox or an accessible GH repo.

**Comment by talebi1** [comment]
try in a private window (no extension), most probably caused by ublock origin?
