### ISSUE TITLE
titleTemplate is not working properly and repeats itself multiple times

### ISSUE THREAD

**Issue by matobeno1** [nuxt/nuxt.js#6428]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://gitlab.com/matobeno1/nuxt-title-issue/](https://gitlab.com/matobeno1/nuxt-title-issue/)

### Steps to reproduce

- start the dev server
- open any link in the new tab and watch the site title
- go to the opened tab and try reloading (alternatively hard reloading)

### What is expected ?

The site title for each route should be the way it is defined in the `nuxt.config.js`

```
head: {
    titleTemplate: '%s - MyApp',
    title: 'TheTitle',
    // ...
}
```

So the site title should be e.g. `TheTitle - MyApp`

### What is actually happening?

After several reloads the "- MyApp"  is appended so the final look
of the site title is e.g.

`TheTitle - MyApp - MyApp`

or even

`TheTitle - MyApp - MyApp - MyApp - MyApp - MyApp - MyApp` (multiple times repeated based on how many times I reload)

### Additional comments?

I don't really know how exactly to reproduce this, there is a GIF image in the Reproduction link repo, sometimes you might
need to reload several times, try opening several routes and reloading / hard reloading the site, clicking on route-links and reloading. After a while you should see that the site title is repeating itself. It happens in the production build and development build as well.
Tried to reproduce on Firefox Dev, Edge, Chrome, happens on all of those. 
Any help appreciated

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9768">#c9768</a>)</em></sub></div>

**Comment by pimlie** [comment]
Transferred the issue back to nuxt.js, cause I realized its a Nuxt issue.

**Comment by pi0** [comment]
Fix willl be available in next release (and also latest nuxt-edge)
