### ISSUE TITLE
date type is not serialized properly

### ISSUE THREAD

**Issue by pandada8** [nuxt/nuxt.js#643]
currently when date is stored on store, the date is directly `JSON.stringify` and loss the type info, require special care (like manually cast before using the variable) in every related function.

Could the date being properly serialized before sending to client ? or let user provide a serialize/deserialize function, and make storing custom type be possible ?

**Comment by alexchopin** [comment]
The store data is serialized by [Vue-ssr](http://ssr.vuejs.org/en/data.html), I don't think it's related to Nuxt.

**Comment by pandada8** [comment]
But not only store data is affected. :/
https://github.com/nuxt/nuxt.js/blob/333e3cf13aeaa76b5c6d28e3994820ae0fd0fd64/lib/render.js#L109
Here the data is serialize by `serialize(..., { isJSON: true })` which just acts like [JSON.stringify()](https://github.com/yahoo/serialize-javascript/blob/master/index.js#L72). which means $data is not properly serialized.

And currently there is no way I can do some transform work before Nuxt.js bootstrap itself. (so I can serialized and unserialized date properly and then give it to nuxt.js)

I think there maybe two solution to this problem:

1. replace `serialize-javascript` with some libs handling date right 
2. provide a hook function and let user do the transform (make sure the required lib is loaded before the bootstrap.)

The first should be easy, the latter is more extensive and make it possible to store some different types of data.

**Comment by pandada8** [comment]
https://github.com/nuxt/nuxt.js/blob/f317b70fd5be57924195efd028610621cc0eb9bb/lib/core/renderer.js#L343
@alexchopin Could you please provide a method to toggle `isJSON` when serialize, or read the value from the nuxt.config.js ? it seems need this need least change and can fix current problem.
