### ISSUE TITLE
nuxtServerInit not fill store to frontend

### ISSUE THREAD

**Issue by ShaneXie** [nuxt/nuxt.js#6431]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-wr3k7](https://codesandbox.io/s/codesandbox-nuxt-wr3k7)

### Steps to reproduce

you can clearly see the store in not filled in frontend in the UI
you can also check it in vue devtool, the post list is empty.

### What is expected ?

store is filled to frontend

### What is actually happening?

store is empty 

### Additional comments?

seems like this bug is not in old version of nuxt (tested on nuxt 2.5 in that codesandbox)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9790">#c9790</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @ShaneXie 

I don't understand you issue, the store is filled:
![Screenshot 2019-09-18 at 10 16 41](https://user-images.githubusercontent.com/904724/65130319-74244c80-d9fd-11e9-9164-cce58e24e3da.png)

**Comment by ShaneXie** [comment]
Hi @Atinux , the store is filled during ssr at server side, but not send the filled store to client side. In the demo, I expect the posts list shows when I click on that button, but in fact nothing show.

**Comment by aldarund** [comment]
@ShaneXie it show exactly what is filled. https://i.imgur.com/bdBoQ1g.png

**Comment by ShaneXie** [comment]
hmm looks like i cant reproduce it atm, prob it's a bug in vue devtool? close it for now.
