### ISSUE TITLE
How to get current domain at SPA mode

### ISSUE THREAD

**Issue by ndphuong** [nuxt/nuxt.js#6436]
### What problem does this feature solve?

I want to get current domain of website at SPA mode. Example: localhost:3000

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9792">#c9792</a>)</em></sub></div>

**Comment by pimlie** [comment]
client side or server side?

**Comment by ndphuong** [comment]
@pimlie I want to get in client side

**Comment by ndphuong** [comment]
> client side or server side?

I want to get domain in client side

**Comment by mornir** [comment]
Not sure if I understood your question correctly, but you can just use vanilla JS:
```
// make sure code is not executed server-side
if(!process.server) {
  console.log(window.location.hostname)
}

```

**Comment by manniL** [comment]
As @mornir said.

Also: https://stackoverflow.com/questions/6941533/get-protocol-domain-and-port-from-url

**Comment by manniL** [comment]
> How would one do this for serveride?

You can get the info from the req object (inside the context)
