### ISSUE TITLE
 can't access static html file under NUXT

### ISSUE THREAD

**Issue by jiandian** [nuxt/nuxt.js#6437]
The Vue.js project converts to a Nuxt.js project and displays 404 when accessing static resource HTML files. How do I parse static HTML files under static?
![image](https://user-images.githubusercontent.com/15643807/65210978-ba49e080-dacf-11e9-93f9-31ecf2515a6f.png)
![image](https://user-images.githubusercontent.com/15643807/65211118-32180b00-dad0-11e9-91b9-403b8ed61c71.png)

**Comment by McKlatch** [comment]
Did you find a solution to this @jiandian ?

Trying to verify ownership of a website to some advertisers, but their system demands a HTML Verification File.

No idea how to place it. A simpler website would only need it in the root folder.

**Comment by jiandian** [comment]
> Did you find a solution to this @jiandian ?
> 
> Trying to verify ownership of a website to some advertisers, but their system demands a HTML Verification File.
> 
> No idea how to place it. A simpler website would only need it in the root folder.

It has been proposed that the Nginx intercept and the back-end handle the static HTML file redirection.
