### ISSUE TITLE
chunkhash / contenthash not work，每次build生成的hash都不一样

### ISSUE THREAD

**Issue by javaLuo** [nuxt/nuxt.js#6439]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://jsfiddle.net/jf5aphb8/](https://jsfiddle.net/jf5aphb8/)

### Steps to reproduce

yarn build

### What is expected ?

在文件没有改变的情况下，每次build生成的文件hash名应该是不变的

### What is actually happening?

而现在每次build后，生成的文件名都不一样，即使我没有做任何更改。
2.8.x 都是OK的

### Additional comments?

即使我设置了以下代码，仍然没用
```
export default {
  build:{
    filenames: {
      app: ({ isDev }) => (isDev ? '[name].js' : '[contenthash].js'),
      chunk: ({ isDev }) => (isDev ? '[name].js' : '[contenthash].js'),
    },
  }
}
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9795">#c9795</a>)</em></sub></div>

**Comment by clarkdo** [comment]
能提供一个可重现问题的库么？

**Comment by javaLuo** [comment]
> 能提供一个可重现问题的库么？我本地验证了一下，并没有描述的问题，因此可能是你项目某些设置或功能导致的。

我发现只要我在`nuxt.config.js`中设置了
```
build:{
  extractCSS: { allChunks: true },
}
```
就会出现这样的问题，不是全部hash都变了，是有一部分变了
但2.8.x就没有这样的问题

我创建了一个DEMO：[demo](https://github.com/javaLuo/nuxt-test-demo)

我为什么在意这个问题：
 我提交完代码后，运维工程师会部署到不同的服务器中，源代码会被编译很多次，做CDN。
结果用户访问的时候有时能访问到某个JS，有时404，因为不同服务器上的JS hash不一样。
（实际上我可以本地编译好了，让运维直接运行，额，反正2.9.x就是有这个问题，2.8.x is ok）

**Comment by clarkdo** [comment]
好的，谢谢提供的信息，我会跟进这个问题

**Comment by wfq1095745112** [comment]
我这边没配置，也会导致这个情况
build:{
  extractCSS: { allChunks: true },
}

**Comment by wfq1095745112** [comment]
export default {
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: "腾讯SSV",
    htmlAttrs: {
      lang: "en",
    },
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { hid: "description", name: "description", content: "" },
      { name: "format-detection", content: "telephone=no" },
      { name: "renderer", content: "webkit" },
      { name: "force-rendering", content: "webkit" },
      { "http-quiv": "X-UA-Compatible", content: "IE=Edge,chrome=1" },
    ],
    
    link: [
      { rel: 'icon', type: 'image/x-icon', href: 'https://xx/images/favicon.ico' }

    //   {
    //     rel: "icon",
    //     type: "image/x-icon",
    //     href:
    //       process.env.NODE_ENV === "production"
    //         ? "./mobile/favicon.ico"
    //         : "/favicon.ico",
    //   },
    //   {
    //     rel: "icon",
    //     type: "image/x-icon",
    //     href:
    //       process.env.NODE_ENV === "production"
    //         ? "../../mobile/favicon.ico"
    //         : "/favicon.ico",
    //   },
    ],
    script: [
      {
        src: "https://xx.js",
      },
    ],
  },
  server: {
    port: 3000, // default: 3000
    host: "0.0.0.0", // default: localhost
  },
  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    "assets/styles/app.less",
    "assets/styles/public.less",
    "assets/font/font.css",
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    "@/plugins/es.js",
    "@/plugins/core",
    { src: "~/plugins/swiper.js", ssr: false },
    { src: "@/plugins/poly", ssr: true },
    "~plugins/t-design/t-design.js",
    "~plugins/utils.js",
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    "@nuxtjs/axios",
    [
      "nuxt-winston-log",
      {
        logPath: "./logs",
        logName: `${process.env.npm_package_name}.log`,
      },
    ],
  ],

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    transpile: [/^t-design/, "installComponents", /^swiper/],
  },
  env: {
    VUE_APP_URL_BASE: process.env.VUE_APP_URL_BASE,
    VUE_APP_URL_BASE_OTHER: process.env.VUE_APP_URL_BASE_OTHER,
    VUE_APP_IMG_BASE: process.env.VUE_APP_IMG_BASE,
  },
  // router: {
  //   base: process.env.NODE_ENV === 'production' ? './' : '/',
  //   redirect: "/",
  // }
};

**Comment by wfq1095745112** [comment]
"dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@tencent/tdesign-vue": "file:tdesign-vue-0.23.5.tgz",
    "babel-polyfill": "^6.26.0",
    "babel-preset-stage-3": "^6.24.1",
    "core-js": "^2.6.12",
    "cross-env": "^7.0.3",
    "less": "^3.12.2",
    "less-loader": "^7.1.0",
    "nuxt": "^2.15.8",
    "nuxt-winston-log": "^1.2.0",
    "vue": "^2.6.14",
    "vue-awesome-swiper": "^3.1.3",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^4.46.0"
  }
