### ISSUE TITLE
after ssr

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#644]
After rendering the page, I observe the variable `window.__NUXT__= { ... }` in HTML code

1) Is it possible to somehow remove it from HTML?
2) If it is impossible to comply with paragraph 1, can it be better to apply obfuscation? So that the data is not available in explicit form (for some projects, this is a critical point)

**Comment by lmj0011** [comment]
Yea, I've noticed `.env` get stored there

**Comment by wormen** [comment]
@lmj0011 There is stored not only .env, but most of the generated data on the server

**Comment by alexchopin** [comment]
Hi, we can't remove it from HTML.
This part is used by Vue for the [Server Data Fetching](http://ssr.vuejs.org/en/data.html)
