### ISSUE TITLE
.nuxtignore doesn't handle patterns if srcDir is specified

### ISSUE THREAD

**Issue by dyakovk** [nuxt/nuxt.js#6459]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codesandbox.io/s/nuxtignore-w8o79?fontsize=14](https://codesandbox.io/s/nuxtignore-w8o79?fontsize=14)

### Steps to reproduce

I need the source directory not to be in the root (which defaults to `rootDir`) but in the `src/` directory or in any other, does not matter.

```js
// nuxt.config.js

export default {
  srcDir: 'src/'
}
```

Second, I need to ignore some `*.vue` files in the pages directory. I specified these files in the `.nuxtignore` in the project root.

```gitignore
# .nuxtignore

src/pages/about.vue
pages/about.vue
```

None of the patterns work.

### What is expected ?

The patterns that I defined should work if the `srcDir` is specified,  other than `rooDir` 

### What is actually happening?

`.nuxtignore` doesn't handle patterns if `srcDir` is specified in the `nuxt.config.js`

### Additional comments?

You can see this result in the attached link to CodeSandbox

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9818">#c9818</a>)</em></sub></div>

**Comment by jardakotesovec** [comment]
Same issue here. Can we reopen it? @manniL

**Comment by Chippd** [comment]
None of the other answers here worked for me. What finally did was adding an ignore array [as per the docs](https://nuxt.com/docs/api/configuration/nuxt-config#ignore) to the nuxt.config.ts file. I was getting typescript errors when using some of the other solutions here.

For reference currently running Nuxi 3.0.0-rc.12
Nuxt 3.0.0-rc.12 with Nitro 0.6.1

// nuxt.config.ts:
...
ignore: [
  "path/to/ignore/**"
],
...
