### ISSUE TITLE
I don't have vm in data on the server

### ISSUE THREAD

**Issue by artemautomatic** [nuxt/nuxt.js#6466]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Steps to reproduce

VM is undefined in data when use arrow function.
data: vm => ({ fullName: vm.$store.state.profile.fullName })

Cannot read property '$store' of undefined

https://codesandbox.io/s/codesandbox-nuxt-ceg8b

### What is expected ?

I have vm on the server

### What is actually happening?

vm is undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9823">#c9823</a>)</em></sub></div>

**Comment by manniL** [comment]
Please add a reproduction (ideally via https://template.nuxtjs.org/).

**Comment by artemautomatic** [comment]
@manniL Yes, sure, https://codesandbox.io/s/codesandbox-nuxt-nhn03
