### ISSUE TITLE
nuxtServerInit with nuxt-i18n

### ISSUE THREAD

**Issue by swearwalker** [nuxt/nuxt.js#6469]
When i use nuxtServerInit with nuxt-i18n:
```
nuxtServerInit({ dispatch }, { app }) {
    dispatch('getHomeData', app.i18n.locale)
}
```
I call action:
```
async getHomeData({ commit }, currentLang) {
    const home = await this.$axios.$get(process.env.BASE_API + currentLang + '/v1/home')
    commit('setHomeData', home)
}
```
And after that mutation:
```
setHomeData(state, data) {
    state.home = data
}
```
All good, but after when i change language to other, store updated successfuly, but data in content stay with old language.
How i can fix that?

**Comment by rchl** [comment]
You can run that code in a plugin instead and also add onLocaleChanged listener from which you can update your data.

**Comment by mrleblanc101** [comment]
Is that really the official way ? Seems odd

**Comment by rchl** [comment]
The use case is rather specific so not sure there needs to be anything "official" for it.

But I don't see anything odd about relying on the provided listener to update some custom data that relies on the locale.

Though `$i18n.locale` should be reactive so if you prefer you could make a mixin without relying on the listener.

**Comment by mrleblanc101** [comment]
Does not seem very specific to me. Seems pretty basic to use nuxtServerInit to have some global data in the store before render

**Comment by rchl** [comment]
I don't agree.

Even more so because `nuxtServerInit` by definition is not reactive since it's only for initializing the data on the server.

**Comment by mrleblanc101** [comment]
Not sure what you are talking about... nuxtServerInit is perfectly reactive. NuxtServerInit hydrate the client store with the initialData, then any mutation will be reactive.

**Comment by rchl** [comment]
Well, semantics. vuex is reactive but `nuxtServerInit` is for initializing on the server. Then you have to update data on the client from some other place. That's what I meant.

It's better to just create a plugin that handles the initial use case from the same place.
