### ISSUE TITLE
How to pass data to layout from index.vue?

### ISSUE THREAD

**Issue by jarrro** [nuxt/nuxt.js#647]
i have in layout/main.vue:
```
...
<navbar :somedata="somedata"/>
<nuxt/>
...
import navbar from '~components/navbar.vue';
...
```
I want to send to navbar data from the index.vue:
```
data() {
    return: {
        somedata: 'sometext'
    }
}
```
and in components/navbar.vue:
```
props: ['somedata']
```

but i get: `[Vue warn]: Property or method "somedata" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.`
How to do?

**Comment by ausir0726** [comment]
the only way is use Vuex .

**Comment by alexmoreno** [comment]
Is it explicit somewhere? I stumbled on same problem.

**Comment by alexchopin** [comment]
Have you tried to use the store?

**Comment by alexmoreno** [comment]
@alexchopin  after reading this thread, yes, and it works, specially using `nuxtServerInit`.
