### ISSUE TITLE
nuxtState undefined in production for universal mode

### ISSUE THREAD

**Issue by igorjacauna** [nuxt/nuxt.js#6470]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://codesandbox.io/embed/env-plugin-6bn6y](https://codesandbox.io/embed/env-plugin-6bn6y)

### Steps to reproduce

Use a plugin to populate nuxtState to pass environment variables from server to client.

The plugin code  is:

```
export default ({ beforeNuxtRender, nuxtState, env }, inject) => {
  if (process.server) {
    beforeNuxtRender(({ nuxtState }) => {
      nuxtState.env = nuxtState.env || {}
      Object.keys(env).forEach(key => {
        if (process.env[key]) {
          nuxtState.env[key] = process.env[key]
        }
      })
    })
  } else {
    Object.keys(nuxtState.env).forEach(key => {
       inject('env', nuxtState.env)
    })
  }
}
```

### What is expected ?

this.$env has environment variables in pages/components

### What is actually happening?

Error: TypeError: Cannot read property 'env' of undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9827">#c9827</a>)</em></sub></div>

**Comment by pimlie** [comment]
You also have to inject the env key on the server, currently in your repro you only do that client side but that means that the computed property in `index.vue` returns undefined

In your repro this should work (you cant run the inject within beforeNuxtRender, that runs too late):
```js
  if (process.server) {
    const env = { VALUE: 'Hello World' }
    beforeNuxtRender(({ nuxtState }) => {
      nuxtState.env = nuxtState.env || env;
    })
    inject("env", env)
  }
```

**Comment by igorjacauna** [comment]
It not worked. Stil getting undefined nuxtState in client side.

Example; https://codesandbox.io/embed/env-plugin-6bn6y

**Comment by pimlie** [comment]
If you compare the code I posted and your repro closely you will see for sure why it doesnt work ;)

**Comment by igorjacauna** [comment]
You right, but for some reason, in code sandbox working but in my docker container not working... For some reason, even if I use some code like this: 
`const env  = { VALUE: process.VALUE || "Hello World!" };`

Where I set a default value, I got undefined for `this.$env` I try to reproduce in code sandbox, but no success. I create exactly code and build a docker image, but when run the container, I got undefined.

**Comment by igorjacauna** [comment]
Now I faced that when is running behind a nginx proxy. NuxtState come empty in fact. But if I access directly to docker container, everything worked fine. I don't know where is the problem
