### ISSUE TITLE
Access response to set cookie on server-side

### ISSUE THREAD

**Issue by hyurtseven81** [nuxt/nuxt.js#649]
Hi

I'm trying to implement a jwt refresh mechanism but i need to set cookie. 
Is there a way to access response object to set server side cookies in middleware?

Thank you

**Comment by alexchopin** [comment]
You have access to the context with `req` and `res` in your middleware function.
https://nuxtjs.org/api/pages-middleware

**Comment by hyurtseven81** [comment]
Thank you very much for your quick response as always
