### ISSUE TITLE
improve build time on CI ( cache )

### ISSUE THREAD

**Issue by mathroc** [nuxt/nuxt.js#6493]
Hi,

I'm trying to improve build time on CI. I'm building docker images with nuxt in universal mode prebuilt.

the main parts of the Dockerfile looks like this:

```Dockerfile
# syntax=docker/dockerfile:experimental
FROM node:12.10-alpine

RUN mkdir /scripts

WORKDIR /scripts

ADD package.json yarn.lock /scripts

RUN --mount=type=cache,id=yarn,target=/usr/local/share/.cache/yarn \
	yarn install --frozen-lockfile --no-progress --non-interactive

ADD . /scripts/

ENV NODE_ENV=production

RUN --mount=type=cache,id=yarn-$APP,target=/usr/local/share/.cache/yarn \
	yarn build
```

this allows me to use the docker cache and not run yarn install each time (and even when it yarn.lock is updated it uses the yarn cache). but the build step is not cached at all. I've added `cache: true` and `hardSource: true` and it does wonder on our local env but it's not useful in this Dockerfile (it's probably even worst because it's building the cache and never using it)

so I'd like to use the docker cache for the build too but I'm not sure which folder or folders should be cached ?

**Comment by TheNoim** [comment]
This is sad. Why is the url https://cmty.app/nuxt/nuxt.js/issues/c9845 not working? I really like to know the response to this.
