### ISSUE TITLE
You broke it!

### ISSUE THREAD

**Issue by Orbitax** [nuxt/nuxt.js#6497]
V2.10.0 wont build on any project thanks boys!

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9847">#c9847</a>)</em></sub></div>

**Comment by CurtisBelt** [comment]
A proper bug report would be more productive don't you think?
