### ISSUE TITLE
Window is not defined when store is activated

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [nuxt/nuxt.js#650]
Since window is not defined when store is activated, I don't see a way to refill the store from localStorage before any of the page components get loaded.
Tried:
- Creating store from a plugin and middleware
- Directly writing to `window.__NUXT__.state` from a plugin
- Waiting for window to load inside `store/index.js`

So, I ended up refilling the store from localStorage on mounted of one of the `~components/`
Are there any ways of doing it?

**Comment by alexchopin** [comment]
The best way is to call the store action from the `mounted` method.
The layout component is the best place for global action call once the client is loaded.

**Comment by OlzhasAlexandrov** [comment]
What you have described is not the best way of doing it.
mounted() of default layout is called after all its components are loaded.

A better way of resolving the issue is:
if anyone would come up with a better way of refilling store after page update from a localStorage, please let me know.
This is how I do it now
```
// ~plugins/global-components.js
import storeRefill from '~components/desktop/StoreRefill'
Vue.component('store-refill', storeRefill);
```

```
// nuxt.config.js
plugins: [
    '~plugins/global-components',
],
```
```
// ~layouts/default.vue
<template lang='pug'>
// beginning of the template
div
    store-refill
</template>
```
```
// ~components/desktop/StoreRefill.vue
<template></template>
<script>
export default {
    mounted() {
        // filling store here
    },
}
</script>
```

This way, it is going to be refilled with the first component to load.
But the issue is still not resolved, it will be called after mounted() of a page component.
