### ISSUE TITLE
router.trailingSlash: false "This page could not be found"

### ISSUE THREAD

**Issue by CurtisBelt** [nuxt/nuxt.js#6501]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/CurtisBelt/nuxtjs-template](https://github.com/CurtisBelt/nuxtjs-template)

### Steps to reproduce

```
yarn dev
```

or 

```
yarn build
yarn start
```

### What is expected ?

![2019-10-02_09-44.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/24847f70-e523-11e9-8d25-214efa15b4f1.png)

### What is actually happening?

![2019-10-02_09-43.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/1a4ada40-e523-11e9-8d25-214efa15b4f1.png)

### Additional comments?

Removing `router.trailingSlash` or setting it to true prevents the error, but my preference is for no trailing slash.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9851">#c9851</a>)</em></sub></div>

**Comment by manniL** [comment]
Will check after vacation. Might be a good first issue. Resolution would be checking if it’s the index route and preserving the trailing slash. Related PR: #6331
