### ISSUE TITLE
Nuxt not working with vueifity 2 on IE11

### ISSUE THREAD

**Issue by daniel-payne** [nuxt/nuxt.js#6503]
My nuxt app fails using vuetify 2 on IE11  

the error in IE11 does not show an obvious cause

![image](https://user-images.githubusercontent.com/7932740/66036788-03edee80-e506-11e9-8d90-2a6d2675daa0.png)

This is the workaround I use: **the build needs to transpile the vuetify package**
Is it possible to document this somewhere so future developers can find it  

BTW vuetify is not the only package in the list on my nuxt.config.js 
For my project, my transpile list includes  'ansi-regex', 'lru-cache', 'yallist'

```
  /*
   ** Build configuration
   */
  build: {
    /*
     ** Configuration to ensure it works on IE
     */
    babel: {
      babelrc: false,
      presets({ isServer }) {
        const targets = isServer
          ? { node: '12' }
          : {
              ie: '11',
              edge: '38',
              browsers: ['> 1%', 'last 1 versions', 'ie >= 11']
            }
        const modules = isServer ? 'auto' : 'commonjs'

        return [[require.resolve('@nuxt/babel-preset-app'), { targets, modules }]]
      }
    },
    transpile: ['vuetify'],
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9853">#c9853</a>)</em></sub></div>

**Comment by MSkred** [comment]
Same issue
