### ISSUE TITLE
npm run build - Show 'renderRoute' error

### ISSUE THREAD

**Issue by cscan** [nuxt/nuxt.js#6509]
I try to use nuxt by using the npx create-nuxt-app to create the app. I can npm run dev to activate the application. But when I execute the command npm run build, it shows the following error:

TypeError: Cannot read property 'renderRoute' of undefined
    at Generator.generateRoute (/home/dds/app/oltapp/node_modules/@nuxt/generator/dist/generator.js:222:42)
    at Promise.all.routes.splice.map (/home/dds/app/oltapp/node_modules/@nuxt/generator/dist/generator.js:120:24)

 FATAL  Cannot read property 'renderRoute' of undefined                                                                   
  at Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:168:43)

   │   ✖ Nuxt Fatal Error                                           │
   │   TypeError: Cannot read property 'renderRoute' of undefined   │

Any step I missed?

**Comment by jjhesk** [comment]
i have the same issue as well. Just install 2.10.0 and the problem started act.

**Comment by jjhesk** [comment]
i think that was related to https://github.com/nuxt-community/proxy-module/issues/58

**Comment by kajcula** [comment]
Instead 'npm run build' use 'npm run generate' - for me works fine

**Comment by cscan** [comment]
I found that if I choose SPA, the error will exist. If I choose SSR, then no error. But indeed I have to go for SPA .... any idea?
