### ISSUE TITLE
Debugging nuxtjs .vue Files On the Server in Docker

### ISSUE THREAD

**Issue by ssinno28** [nuxt/nuxt.js#6518]
I currently have a nuxt app setup as a univeral app in which I'm hosting using Docker. I've got pretty much everything working, the debugger attaches and finds local variables just fine when walking through middleware and api calls, but when debugging the `asyncData` method in the `.vue` file I can't see any of the local variables and my breakpoint keeps moving to the `.catch` line: 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/vCoi9.png

I also get a bunch of other random things in the current context, which in this case is "Module"?? 

I've added this line to my `nuxt.config.js` file as well to make sure it uses the correct source maps:

 

         /*
      ** Build configuration
      */
      build: {
        /*
        ** You can extend webpack config here
        */
        extend(config, ctx) {
          console.log(`IsClient: ${ctx.isClient}`);
          console.log(`isDev: ${ctx.isDev}`);
          if (ctx.isDev) { 
            config.devtool = ctx.isClient ? 'source-map' : 'inline-source-map'
          }
        }
      }

Also here is my `.vscode` config:

    {
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Docker: Attach to Node",
                "type": "node",
                "request": "attach",
                "remoteRoot": "/usr/share/nginx/app",
                "port": 9229,
                "address": "localhost",
                "localRoot": "${workspaceFolder}/app",
                "protocol": "inspector",
                "restart": true,
                "sourceMaps": true
            }
        ]
    }

Also, here is the command I use to start the container:

```
 node --inspect=0.0.0.0:9229 \
            ./node_modules/.bin/nuxt \
            & nginx -g "daemon off;" \
```

I've tried a lot of different things including using babel-register and starting it with babel-node since its transpiled, but none of those methods worked. 

Is there anything I'm missing here? Can we just not debug `.vue` files on the server when creating a universal app?

**Comment by AveryBibeau** [comment]
@ssinno28 I believe you are missing the `sourceMapPathOverrides` which is what I needed to make debugging work for server side code in VS Code. I'm able to add breakpoints to `asyncData` with auto detected Local/Block variables. You might have to adjust the file paths to work with your app container.

`.vscode/launch.json`
```
{
  "configurations": [
    {
      "name": "Attach app",
      "type": "node",
      "request": "attach",
      "cwd": "${workspaceRoot}",
      "sourceMapPathOverrides": {
        "webpack:///*": "${workspaceRoot}/*",
        "webpack:///./*": "${workspaceRoot}/*"
      },
      "sourceMaps": true
    }
  ]
}
```

![Screen Shot 2019-12-06 at 9 11 20 AM](https://user-images.githubusercontent.com/2278938/70342231-75e5fb00-1809-11ea-96c2-7a2ff4785c0d.png)

**Comment by ssinno28** [comment]
I tried that, didn't work for me...

**Comment by ssinno28** [comment]
Also an FYI for anyone else running into this problem, I got the debugging working in WebStorm

**Comment by gkatsanos** [comment]
Apparently step debugging isn't so popular with the community. I'm trying to set it up, but in my case I don't even get a breakpoint in asyncData() , at all.. I can only break adding a breakpoint in Client-Side code within Chrome Dev Tools.
here's my launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "server: node",
      "runtimeExecutable": "yarn",
      "runtimeArgs": ["run", "dev:debug"],
      "port": 3000
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to node",
      "address": "localhost",
      "sourceMapPathOverrides": {
        "webpack:///*": "${workspaceRoot}/*",
        "webpack:///./*": "${workspaceRoot}/*"
      },
      "port": 9229
    }
  ]
}
```

**Comment by ssinno28** [comment]
I was able to get it to work while using webstorm, not sure why it works there and not VS: https://stackoverflow.com/questions/57548696/debugging-nuxtjs-vue-files-on-the-server-in-docker
