### ISSUE TITLE
Make context available on $nuxt

### ISSUE THREAD

**Issue by buhrmi** [nuxt/nuxt.js#652]
Nuxt is picking up and some vue plugins (mine for example) would like to know if they're being run inside nuxt and change their behavior accordingly. Since the context object provides necessary info (headers, request params) usually taken from the browser, it would be nice to have the context object available as `vm.$nuxt.context`

**Comment by Atinux** [comment]
Hi @buhrmi 

I thought about it a lot but it's not a viable solution `req` and `res` are only accessible on server-side and then you can't use them afterwards.

I recommend you to use the middleware or the `nuxtServerInit` action to store the data you need from the context and set it in the state of the store.
