### ISSUE TITLE
`js$` hard-coded in store.js so can't create `store.ts` for TypeScript

### ISSUE THREAD

**Issue by johnlindquist** [nuxt/nuxt.js#653]
https://github.com/nuxt/nuxt.js/blob/master/lib/app/store.js#L5

^Would it be possible to move the file-type into the config?

**Comment by johnlindquist** [comment]
To clarify, if you want to use TypeScript and Vuex, using the `.ts` file-type like `store/index.ts` fails due to `.nuxt/store.js` having hard-coded lookup for `store/index.js`.

**Comment by Atinux** [comment]
Same problem for middleware as well: https://github.com/nuxt/nuxt.js/blob/master/lib/app/middleware.js#L2

I'll take a look at it to make Nuxt.js works with TypeScript as well :)
