### ISSUE TITLE
css missing when generate

### ISSUE THREAD

**Issue by imhazige** [nuxt/nuxt.js#6530]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/imhazige/nuxt-issue](https://github.com/imhazige/nuxt-issue)

### Steps to reproduce

- download the source code, 
- npm install
- npm run static

go to url http://localhost:8080/mobile/

you will see the class worked fine in dev mode not work after generate static files.

it is very wired.

for following scss definition.

.cls1 {
    color: #36c512;
  }

  .onthercls {
    color: #d71e74;
  }

  .misscls {
    color: #c2cb12;
  }

  .somecolor {
    color: #981c1c;
  }

  .cls2 {
    color: #d28e60;
  }

the  cls2,onthercls, are not included in the generated html file.
 

### What is expected ?

all class should included in the generated file

### What is actually happening?

with the same syntax, some one included, some one miss. very wired.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9875">#c9875</a>)</em></sub></div>

**Comment by manniL** [comment]
As you are using tailwind + purgecss, it is likely purged by the plugin, as it doesn't look in the `componentsM` folder.

Please check https://www.purgecss.com/, https://github.com/Developmint/nuxt-purgecss and https://github.com/nuxt-community/nuxt-tailwindcss :relaxed:

**Comment by imhazige** [comment]
Hi, @manniL 

It is using tailwind, but not set up purgecss. I think purgecss is set up by default, right?

**Comment by manniL** [comment]
> TailwindCSS module for Nuxt.js with nuxt-purgecss + modern css zap
https://github.com/nuxt-community/nuxt-tailwindcss

**Comment by imhazige** [comment]
@manniL 


You save our life, thank you so much.

after move componentM to components folder, all works like a charm.
