### ISSUE TITLE
Can't access this.nuxt.renderer inside module when build in production

### ISSUE THREAD

**Issue by cron13** [nuxt/nuxt.js#6532]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-i2s9l](https://codesandbox.io/s/codesandbox-nuxt-i2s9l)

### Steps to reproduce

1. Open /modules/bug/main.js
2. Open terminal with yarn start, than refrash browser panel
dev build work great - you will got right console.log(data) in terminal

3. Open another terminal and type yarn run build
got TypeError: Cannot read property 'renderRoute' of undefined

### What is expected ?

Working function renderRoute 

### What is actually happening?

TypeError: Cannot read property 'renderRoute' of undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9877">#c9877</a>)</em></sub></div>

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/nuxt.js/issues/6519

**Comment by cron13** [comment]
but in #6519 @aldarund say it`s different issue

**Comment by manniL** [comment]
@cron13 whoops, sorry.

**Comment by aldarund** [comment]
@cron13 you need to check if renderer exist or not, its not available during build anymore
