### ISSUE TITLE
Client-side fetch store state is not reactive

### ISSUE THREAD

**Issue by philBrown** [nuxt/nuxt.js#6535]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/BarryJamez/not-so-reactive-app.git](https://github.com/BarryJamez/not-so-reactive-app.git)

### Steps to reproduce

Issue raised on StackOverflow here ~ https://stackoverflow.com/questions/58278144/vuex-state-not-reactive-without-page-reload

### Client-side data loading (not reactive)

1. Run app
2. Navigate to "Tasks" page using "View Tasks" button
3. Click a task button to change status. This commits a change to the store
4. Note that nothing changes

### Server-side data loading (reactive)

This is included just to show the contrast

1. Run app
2. Navigate to "Tasks" page using "View Tasks" button
3. Reload page
5. Click a task button to change status. This commits a change to the store
6. Note that changes are reflected in the UI

### What is expected ?

Client-side loaded data in the store should be reactive

### What is actually happening?

Client-side loaded data in the store is not reactive

### Additional comments?

In contrast to what is explained in the [_Data Reactivity on the Server_ documentation](https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server), data loaded by a server-side `fetch` (Nuxt API) **is** reactive but data loaded by a client-side `fetch` is not.

A solution is to use `Vue.set` to force reactivity but this seems like it should not be required.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9880">#c9880</a>)</em></sub></div>

**Comment by aldarund** [comment]
Its not a bug in nuxt. You are not defining state in your task store.
In store/tasks.js
```
export const store = () => ({
  myTasks: []
})
```
while it should be 
```
export const state = () => ({
  myTasks: []
})
```

**Comment by philBrown** [comment]
Thanks @aldarund, it's always something simple like that.
