### ISSUE TITLE
GraphQL Server inside Nuxt.js

### ISSUE THREAD

**Issue by rwatts3** [nuxt/nuxt.js#654]
Is it possible to configure a graphql server rather than just the client inside nuxt.js ? 
So if I wanted to create an endpoint as well as my client side application under the same nuxt application. 

If so could you please point me to an example or a brief pointer to get started. 

Thank you, 

Ryan

**Comment by rwatts3** [comment]
I'm happy to try to get an example going. 
Looks like the `with-apollo` example may be a good base to pick from. 

Maybe this question could help me get going in the right direction. 
Is there a way to add an endpoint directly to the nuxt server ? 

Nuxt-Express would work but I'd like to provide a way to leverage graphql/apollo directly with Nuxt rather than adding it through the Express example.

**Comment by alexchopin** [comment]
Hi @rwatts3,
Have you tried to use [vue-apollo](https://github.com/Akryum/vue-apollo#server-side-rendering) with Nuxt?

**Comment by rwatts3** [comment]
No does that allow me to create an apollo server inside nuxt?

**Comment by stephan281094** [comment]
No, vue-apollo is a wrapper around the Apollo GraphQL client.
In order to create an Apollo server inside Nuxt, you can use Nuxt [programmatically](https://github.com/nuxt/nuxt.js#using-nuxtjs-programmatically) and then add the [apollo server](https://github.com/apollographql/graphql-server) manually. However, it's advisable to run the Apollo server on a different node process.

**Comment by rwatts3** [comment]
Yeah I figured it was.

**Comment by rwatts3** [comment]
Just adding a note for future readers. 
After digging around and doing some research it is probably best to keep the DAL separate from the application. It could potentially be configured as a node module that is instantiated as a separate process when starting a nuxt application. However the actual server / service itself should be separate.

**Comment by pi0** [comment]
@rwatts3 Speaking from experience of months of production with Nuxt (Recently we are experimenting apollo server with HAPI too ) : Separate the whole API/Web concerns into separated repositories and processes. You can then serve them into a unified URL using solutions like [remux](https://github.com/banianhost/remux) or similar nginx configuration to avoid CORS problems :)

**Comment by StasB93R** [comment]
can anyone upload a very simple repo example on how to configure appollo graphql in nuxt.js? please... :)
