### ISSUE TITLE
generate:done fails if action on hook takes more than 5 seconds

### ISSUE THREAD

**Issue by avernali** [nuxt/nuxt.js#6544]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://codepen.io/avernali/pen/rNNVbrO](https://codepen.io/avernali/pen/rNNVbrO)

### Steps to reproduce

run method (in my case is zipping the content of the generated dist folder) that takes more than 5 seconds on a  hook on generate:done within a module file

### What is expected ?

The process (zipping file using webpack archiver) should not be interrupted after 5 seconds

### What is actually happening?

If the content to be zipped is small enough and the action takes less than 5 seconds it will work.
If the content is larger and the zipping process takes more than 5 seconds the following error appears

  ⚠ Nuxt Warning                                                                     │
   │                                                                                      │
   │   The command 'nuxt generate' finished but did not exit after 5s                     │
   │   This is most likely not caused by a bug in Nuxt.js                                 │
   │   Make sure to cleanup all timers and listeners you or your plugins/modules start.   │
   │   Nuxt.js will now force exit                                                        │
   │                                                                                      │
   │   DeprecationWarning: Starting with Nuxt version 3 this will be a fatal error

### Additional comments?

it is possible that I may be doing something wrong there but the documentation about generate hooks does not say much about what can be done and what cannot be done so looks like a bug to me. Especially because the behavior is different if the action takes less than 5 seconds (by chance). 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9885">#c9885</a>)</em></sub></div>

**Comment by xxRockOnxx** [comment]
can you create a codesandbox that has something that would take 5 seconds for the zipping?

**Comment by pimlie** [comment]
@avernali you are not returning / awaiting the zipDirectory promise in the nuxt hook, so nuxt doesnt know it has to wait for it

**Comment by avernali** [comment]
@xxRockOnxx thank you for your answer.

I was about to do that but then I've seen 
@pimlie reply...and yes it was as simple as that! At some point in time I have lost (or maybe never wrote) the "await" so it was timing out. 
Thank you very much!

**Comment by avernali** [comment]
Closing as there is no issue. 
Thank you again @pimlie !
