### ISSUE TITLE
@nuxtjs/font-awesome needs to be updated to version 5

### ISSUE THREAD

**Issue by moonshine31** [nuxt/nuxt.js#6546]
### What problem does this feature solve?

Icons are shown as square when using the nuxtjs/font-awesome package and font-awesome version 5.

E.g. 
i class="fas fa-arrow-alt-right" 

### What does the proposed changes look like?

Use latest version of font-awesome (version 5)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9886">#c9886</a>)</em></sub></div>

**Comment by aldarund** [comment]
Please open issue in a proper project. This is for nuxt itself, while your issue is for module that located in https://github.com/nuxt-community/modules/tree/master/packages/font-awesome
