### ISSUE TITLE
Add info about mode when generating page via `nuxt generate`

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#6554]
### What problem does this feature solve?

To make sure the user doesn't accidentally generates an SPA while he wants a pre-rendered page, it might be worth to write a short sentence about the mode of the project while generating

### What does the proposed changes look like?

Current status: "Generating pages" is logged, which is quite general.

![image](https://user-images.githubusercontent.com/640208/66699127-4c669280-ece4-11e9-84be-e6d937834973.png)

Maybe we can alter the messages a little:

* SSR: "Generating pages for your...." (Haven't had a good idea here :D)
* SPA: "Generating pages for your SPA"

Related tweet: https://twitter.com/TheAlexLichter/status/1182941455049998336

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9895">#c9895</a>)</em></sub></div>

**Comment by patrixxn** [comment]
I'll take this one.

**Comment by patrixxn** [comment]
I'll try this one

**Comment by manniL** [comment]
@patrixxn there is already a corresponding PR open (#6556)

**Comment by TimvdEijnden** [comment]
Since #6556 has not been touched since Oct 12, 2019 I've created a new PR

**Comment by manniL** [comment]
Fixed by https://github.com/nuxt/nuxt.js/pull/6159
