### ISSUE TITLE
error for middleware

### ISSUE THREAD

**Issue by zhancheng** [nuxt/nuxt.js#656]
```
export default function(context) {
    var bs = require('bowser');
    var userAgent = context.isServer ? context.req.headers['user-agent'] :
        navigator.userAgent;
    var bowser = bs._detect(userAgent);
    if (bowser.msie && bowser.version < 9) {
        return context.redirect('/unsuport')
    } else {
        // do nothing else,  i think it should be continued
    }
}

```

such as the upon code , i think if i visit  the browser which is not ie9 below, it should do nothing in middleware and going on response me the page , but the page keeps always loading , cant stop.

i did not find any case in nuxt project,   am i wrong?  ps. i use nuxt in koa

**Comment by zhancheng** [comment]
i guess if  i cant use the nuxt middleware in koa project?

**Comment by alexchopin** [comment]
@zhancheng you can use a koa middleware with a specific route `/unsuport` where user are redirected before using `nuxt.render` or to use [css conditional](https://nuxtjs.org/guide/views#document)

**Comment by zhancheng** [comment]
@alexchopin  ok, thats what i did, thanks!
