### ISSUE TITLE
render.compressor does nothing

### ISSUE THREAD

**Issue by ChromaticMind** [nuxt/nuxt.js#6561]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

Update render.compressor from threshold: 0 to any higher number supported - text compression for .js/.css/.html files still does not take place whether it is a prod/dev build

### What is expected ?

.js/.css/.html files should be compressed

### What is actually happening?

No compression is taking place

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9901">#c9901</a>)</em></sub></div>

**Comment by aldarund** [comment]
Please, provide a proper reproduction
