### ISSUE TITLE
SSR Encoding Error in Attributes of HTML

### ISSUE THREAD

**Issue by myparsec** [nuxt/nuxt.js#6572]
### Version

[v2.10.1](https://github.com/nuxt.js/releases/tag/v2.10.1)

### Reproduction link

[https://vue-meta.nuxtjs.org/api/#headattrs](https://vue-meta.nuxtjs.org/api/#headattrs)

### Steps to reproduce

Add lang: 'ru' in nuxt.config.js

```
manifest: {
  lang: 'ru',
}
```
Add a body classname in layouts/default.vue

```
<script>
export default {
 head() {
  return {
   bodyAttrs: {
    lass: 'light'
   }
  }
 }
}
</script>
```
### What is expected ?

```
<html lang="ru">
  <body class="light"></body>
</html>
```
### What is actually happening?

```
<html lang="ru" data-n-head="%7B%22lang%22:%7B%22ssr%22:%22ru%22%7D%7D">
  <body class="light" data-n-head="%7B%22class%22:%7B%22ssr%22:%22light%22%7D%7D"></body>
</html>
```

![Аннотация 2019-10-15 215004](https://user-images.githubusercontent.com/38665904/66861538-e1dd7d00-ef97-11e9-9210-eab78c0a9399.jpg)

**Comment by mmorainville** [comment]
I have this issue as well on Nuxt 2.12.2...

**Comment by DRBragg** [comment]
I'm also having this issue in 2.13

**Comment by CavalcanteLeo** [comment]
im facing this issue too.

What is it?

**Comment by danielroe** [comment]
@CavalcanteLeo See https://github.com/nuxt/nuxt.js/issues/8315#issuecomment-727530493
