### ISSUE TITLE
Server-side directives aren't applied on custom components

### ISSUE THREAD

**Issue by samburgers** [nuxt/nuxt.js#6575]
### Version

[v2.10.1](https://github.com/nuxt.js/releases/tag/v2.10.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-dyu6u](https://codesandbox.io/s/codesandbox-nuxt-dyu6u)

### Steps to reproduce

Strange one... Nuxt Custom Directives don't seem to register on imported Components (but do work when added to regular template HTML)

```
  <section>
    <div v-custom1="`this works`">Hello</div>
    <HelloWorld v-custom1="`this doesnt work`"/>
  </section>
```

```
  render: {
    bundleRenderer: {
      directives: {
        custom1(el, dir) {
          console.log("custom1", dir);
        }
      }
    }
  },
```

Reproduction:

https://codesandbox.io/s/codesandbox-nuxt-dyu6u

### What is expected ?

Should log both custom directives 

### What is actually happening?

Only logs the first custom directive. Adding a custom directive to a custom component doesnt register.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9915">#c9915</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey :wave: 

Looks like a vue-server-renderer bug to me. Will investigate.

Anyway, you are registering "only" server-side directives here. If you want the typical (client-side) one, you can use a Nuxt plugin to register them globally or use the `directives` attribute on a specific component or page.

Further read on server-side directives in [my blog post](https://blog.lichter.io/posts/universal-ssr-vue-component-guide/#directives)

**Comment by manniL** [comment]
Closing here as it is a vue server renderer bug indeed. Further info in https://github.com/vuejs/vue/issues/10733

**Comment by manniL** [comment]
Resolved via https://github.com/vuejs/vue/pull/12661 (v2.7.9 and up)
