### ISSUE TITLE
Please update core-js to 3.x

### ISSUE THREAD

**Issue by georgyfarniev** [nuxt/nuxt.js#6579]
### What problem does this feature solve?

Hello, vue-cli 4 just updated to core-js 3.x, please update nuxt as well if it possible. It will help to maintain monorepository cleaner. Thank you.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9919">#c9919</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment]
@manniL what's the reason for staying on v.2 by default?

**Comment by manniL** [comment]
For now - breaking changes. Might be a candidate for the next major.

**Comment by zefexdeveloper** [comment]
@manniL Does that mean I can just ignore the warning? I a pull request that was added on the `next` branch but I don't know if it's the branch for the next release. I'm kinda confused.

**Comment by pi0** [comment]
@zefexdeveloper Sorry for confusing. Indeed as it can be a breaking change (vue-cli also did upgrade in a major version) it is merged to `next` branch. You can use `nuxt-edge@next` (which is daily build of nuxt3) to try it :)

**Comment by zefexdeveloper** [comment]
@pi0 Thank you, I will stick with the v2 for now until v3 is officially released. Keep up the good work, you guys rock.
