### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fxh615** [nuxt/nuxt.js#658]
when use loadtest -n 2000 http://localhost:8080/        test the node server (run by  pm2 start npm -i max --name "nuxt" -- start),

i find Memory leak,  by the static resource have worked on  nginx server , 

for more time the node server droped. omg^^^^^^^

**Comment by yi-ge** [comment]
I have the same problem.

**Comment by fxh615** [comment]
haha but closed by @alexchopin  node server render hardly when by loadtest. may be a surely problem.

**Comment by Atinux** [comment]
@fxh615 @yi-ge can you confirm this behaviour on a simple nuxt.js application?

**Comment by yi-ge** [comment]
@Atinux Yes, I sure. This phenomenon has been repeated for two days in v0.10.7 Nuxt in CentOS 7.3. I set up the `Docker` automatically restart. NUXT loaded with Docker memory is increasing and is terminated, reboot.

**Comment by Atinux** [comment]
I just tried with nuxt/starter with pm2 & loadtest -n 2000 and no memory leaks found.

Are you using any external modules that can lead to memory leaks?

**Comment by yi-ge** [comment]
@Atinux You may be able to test in CentOS 7.3, It's normal for me to run in MAC. About an hour will be stained 500M.

**Comment by Atinux** [comment]
@yi-ge it works fine on Linux, I cannot test on CentOS sadly. Even the memory did not go up.

Are you making external API call from you home page?

**Comment by yi-ge** [comment]
@Atinux Yes, I'm sure. I use Microservice development. The program uses only the default NUXT.Problem only in new version.

**Comment by yi-ge** [comment]
@Atinux I conducted an analysis and found that the `lodash` module is a problem in server. 
<img width="1284" alt="wx20170505-141336 2x" src="https://cloud.githubusercontent.com/assets/6657330/25735324/1f5306d4-319d-11e7-8e7d-03f66827f5f2.png">

**Comment by yi-ge** [comment]
@Atinux I got this file, but I don't know how to analyze it.

**Comment by yi-ge** [comment]
@Atinux https://www.dropbox.com/s/pu6xpg0usu95nup/heapdump-98575194.706200.heapsnapshot?dl=0

**Comment by yi-ge** [comment]
@Atinux 我研究了好久没能解决，拜托您帮忙看看。

**Comment by pi0** [comment]
Please see #805 if still having problem and wish to help others resoling memory leaks :)

**Comment by nwa2018** [comment]
@ac88 我今天刚找到问题，不知道跟你的是不是一样，闭包造成的内存泄漏，created,beforeCreated,asynData,head,fetch....这样子的函数都可以检查下
