### ISSUE TITLE
nuxt IE9 

### ISSUE THREAD

**Issue by aa-ziyi** [nuxt/nuxt.js#6581]
Version
v2.3.1 - v2.10.1

Steps to reproduce
nuxt.config.js 中配置mode: 'spa'

What is expected ?
IE9 页面正常打开，显示正常；

What is actually happening?
1、未打开浏览器开发者模式的情况下，IE9 浏览器下不管是生产环境还是开发环境页面都空白
2、生产环境还是开发环境，只要打开开发者模式刷新页面，页面正常打开
注：所有的console信息都已经去除

Additional comments?
v2.0.0 v2.2.0 没有以上问题

**Comment by huhaoGitHub** [comment]
原因为: IE9对console方法支持不好，只有在打开F12的情况下才会在window下面挂载console方法。
在JS里面提前初始化console方法即可
