### ISSUE TITLE
asyncData unexpectedly recovers initial value of data

### ISSUE THREAD

**Issue by SilentDepth** [nuxt/nuxt.js#6585]
### Version

[v2.10.1](https://github.com/nuxt.js/releases/tag/v2.10.1)

### Reproduction link

[https://codesandbox.io/embed/nuxt-asyncdata-issue-xgqtu](https://codesandbox.io/embed/nuxt-asyncdata-issue-xgqtu)

### Steps to reproduce

1. Open the repro CodeSandbox
2. Click the "Navigate" button (navigate to a random url)
3. Check if the message below the `<hr>` is changed to "Updated message"

### What is expected ?

The message should be changed to "Updated message".

### What is actually happening?

The message doesn't change.

### Additional comments?

The whole project is a simple Nuxt app with a nested view (`pages/index/_timestamp.vue`). The "Navigate" button is only to change the URL and fire the watcher event to update the `msg` data. Click the button again, the nested view instance stays alive (no destroy-and-create).

In a normal Vue app, these codes work just fine. But when using Nuxt, `asyncData` gets called every time the URL changed, while the page component itself never being unloaded. More unexpectedly, no `asyncData` is defined in the page component and the initial value of `data` is being applied every time. As a result, the update to `msg` in the watcher handler never works. If watching `msg`, it is updated and then re-assigned to initial value.

I was expecting that `asyncData` only gets called once the page component is created, even when the page is reused during navigation. Please correct me if I misunderstand this feature.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9925">#c9925</a>)</em></sub></div>

**Comment by pimlie** [comment]
There is no asyncData in your repro.

What you are experiencing is most likely caused by transitions, what probably happens is something like this:

- route change
- async leave transition
- timestamp watcher triggered
- leave transition finished
- navigation to new component which only sets initial message because watcher was already triggered

If using `v2.10` you can try to set `features.transitions = false` in your nuxt.config to confirm its the transition. A solution for you could be to use a combination of mounted and updated Vue lifecycle hooks instead of a watcher on the route param.

**Comment by SilentDepth** [comment]
I might not explain my case clearly. I'm asking two possibly related questions.

**Q1: Why asyncData is called when only a route param is changed?**

Yes, there is no asyncData in my repro. But if I add it to my page component I can see it gets called once the route param changed, which is not what I expected. The documentation says "asyncData is called every time before loading the page component", so it should be called only once (since the page component is created only once).

**Q2: Why my component state is recovered when a route param is changed?**

If I serve the same codes (without asyncData) directly by Vue (not Nuxt), everything works as expected. The route param changed, the component local state (data) remained. If using Nuxt, the local state gets recovered. If I add asyncData and return a different value, the local state gets recovered to that value every time. This is why I guess the issue is something about asyncData.

And where should I set the `features.transitions`? I can't find anything like that from the documentation.

**Comment by manniL** [comment]
> The documentation says "asyncData is called every time before loading the page component", so it should be called only once (since the page component is created only once).

Nope, it isn't reused unless you set the internal `key` value.

See https://github.com/nuxt/nuxt.js/issues/4663

**Comment by SilentDepth** [comment]
I see. So `destroyed` lifecycle hook not being called is also intentional?
