### ISSUE TITLE
Support case-sensitive patterns in .nuxtignore

### ISSUE THREAD

**Issue by chriscalo** [nuxt/nuxt.js#6588]
### What problem does this feature solve?

In the `pages` directory, I would like to intermingle `.vue` files that are pages and `.vue` files that are just components.

(I'm aware of the convention to put components in the `components` directory, I just don't agree with it in all situations. There are plenty of situations when a page component becomes quite complex and it's useful to break parts of it into separate components, but those components will never be reused. In those situations, it's best for others trying to understand the codebase to have the component colocated right next to the page that uses it.)

I tried renaming all `.vue` files that are pages to `name.page.vue`, but that makes the URL to access them `name.page` when I want it to be just `name`.

Then I renamed all supporting components using the convention `name.component.vue`, but that resulted in quite verbose file names. Alternatively, the abbreviation `name.cmpt.vue` felt non-obvious, so I didn't love that.

The convention I liked most was to name all page components in lowercase (`name.vue`) to match the all-lowercase convention in URLs and capitalize all supporting components (`LoginForm.vue`) as a nod to the convention of capitalizing classes (another construct that produces instances from a kind of template or blueprint).

So I tried the following:

``` gitignore
pages/**/[A-Z]*.vue
```

Unfortunately, that pattern seemed to match all `.vue` files that started with a letter, so it seems that `.nuxtignore` files are case-insensitive.

### What does the proposed changes look like?

I would love to use the following case-sensitive pattern in `.nuxtignore`:

``` gitignore
# ignore all capitalized .vue files in the pages directory
pages/**/[A-Z]*.vue
```

However, because the `[A-Z]` pattern is case-insensitive, this essentially means any `.vue` file that starts with a letter, which doesn't work as expected.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9927">#c9927</a>)</em></sub></div>

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/pull/6597 has been merged and will be published in  next release
