### ISSUE TITLE
nuxt: Permission denied

### ISSUE THREAD

**Issue by nozreh** [nuxt/nuxt.js#659]
Followed the instruction yet having the nuxt: permission denied error.

**Comment by nozreh** [comment]
Running Ubuntu 14.04 using Vagrant.

`sh: 1: nuxt: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! nuxt@1.0.0 start: `nuxt`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the nuxt@1.0.0 start script 'nuxt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nuxt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nuxt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nuxt
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-05-05T10_02_57_234Z-debug.log`

**Comment by Atinux** [comment]
@nozreh you may listen on a port that is not authorized @nozreh

**Comment by EndevelCZ** [comment]
I encountered same issue - setting permissions for all files in project directory to 770 solved the problem
