### ISSUE TITLE
Async data failed

### ISSUE THREAD

**Issue by wintergithub** [nuxt/nuxt.js#660]
Hi, I got an error when use async data
_pages/.../\_id.vue_
```
<template>
    <input type="text" v-model="template.name">
</template>
<script>
import axios from 'axios'
export default {
    data () {
        return axios.get('https://api.myjson.com/bins/j6ob1')
        .then((res) => {
            console.log(res.data)
            return res.data
        })
    }
}
</script>
```
The browser:
![image](https://cloud.githubusercontent.com/assets/2382425/25688988/3e51c8a0-30b6-11e7-9c4c-eea84f490510.png)
The console:
![image](https://cloud.githubusercontent.com/assets/2382425/25689026/947eb742-30b6-11e7-84c3-f827a9c3c52c.png)

**Comment by yi-ge** [comment]
I have the same problem, but the authors suggest using asyncData instead of data.

**Comment by yi-ge** [comment]
You can see this: https://nuxtjs.org/api/

But can not be used async in the data, I am also very troubled. And `data` may be executed on the server side

**Comment by wintergithub** [comment]
Thanks @yi-ge, replace to `asyncData()` worked !

**Comment by wintergithub** [comment]
Hi @yi-ge, when i replace the url to local path, it throw an error like this:
![image](https://cloud.githubusercontent.com/assets/2382425/25689723/5b4eea44-30bd-11e7-8d32-d0b8577c3824.png)
The code:
```
asyncData (context) {
            return axios.get('/api/v1/templates/' + context.params.id)
            .then((res) => {
                return res.data
            })
}
```
I think it is an axios' error. Did u ever come into this?

**Comment by Atinux** [comment]
You need to write the full URL even on localhost, see Nuxt/express example
to see how we configure axios for working on localhost.

**Comment by wintergithub** [comment]
Thanks @Atinux I added config, then work well !

**Comment by wintergithub** [comment]
hi @Atinux , I got another error when using axios.all:
![image](https://cloud.githubusercontent.com/assets/2382425/25734394/e328a3a6-3194-11e7-9d03-59f39da1d21c.png)
My code:
```
asyncData (context) {
    return axios.get('/api/xxx/1').then((res) => {
        // some logic
        return axios.all([
            axios.get('/api/xxx/2'),
            axios.get('/api/xxx/3')
        ]).then(axios.spread((res) => {
            console.log(res)
        }))
    })
}
```
Then I read issue #579 , and changed the code to:
```
asyncData (context) {
    return axios.get('/api/xxx/1').then((res) => {
        // some logic
        return Promise.all([
            axios.get('/api/xxx/2'),
            axios.get('/api/xxx/3')
        ]).then((res) => {
            console.log(res)
        })
    })
}
```
But throw another error:
![image](https://cloud.githubusercontent.com/assets/2382425/25734506/4d0f7d84-3196-11e7-8ba7-18080cc995cf.png)

how to solve this problem ?
>

**Comment by Atinux** [comment]
It seems that you are calling a HTTPS server with a bad certificate.

**Comment by wintergithub** [comment]
Yes I changed the url and the problem fixed.
Thanks for all your reply @Atinux :)

**Comment by wintergithub** [comment]
hi @Atinux, sry to bother u again. I used SSR in dev-env and generate static files in prod-env. It works fine in dev-env, but when I run "npm run generate", it throw the "127.0.0.1:80" error again. TT

**Comment by wintergithub** [comment]
Hi @Atinux sry to bother u again, I saw that "npm run generate" will bring the dev-env async data to static html files.
The fact is, when I refresh the browser, the dev-env async data will display, but when I click the nuxt-link, the backend will display.
How this happend & if I just want to display backend data, how to do?

**Comment by pi0** [comment]
@wintergithub If you are using static generated method, One possible  solution is that you can avoid fetching data in `asyncData` (Returning minimum data) and then filling that on `mounted()` method.

**Comment by wintergithub** [comment]
Thanks @pi0 !

**Comment by bovas85** [comment]
I'm having a similar problem.
Fetch data from AsnycData but it's fine on normal load.

When in development mode I do a change on the .vue page file but when hot module reloading kicks in and rebuils I lose all the asyncData and thus the page returns undefined on the data it's expecting.

**Comment by heyarviind** [comment]
Did anyone find the solution?

My app was working fine but suddenly i got this error and i am unable to find the solution
