### ISSUE TITLE
Sass directive @debug not printing anything when used. Nor does @warn.

### ISSUE THREAD

**Issue by martinmethod** [nuxt/nuxt.js#6605]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[/](/)

### Steps to reproduce

1. Configure the Sass pre-processor.
2. Write in a used .scss file: `@debug 'I love Nuxt'`
3. Look for an output in the terminal.

### What is expected ?

To see 'I love Nuxt' printed out in the Terminal.

### What is actually happening?

Nothing shows.

### Additional comments?

The same goes for @warn directive.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9934">#c9934</a>)</em></sub></div>

**Comment by IvanGatsinski** [comment]
This issue is still going on. I am unable to use @debug and other notification functions in nuxt

**Comment by Anton-Evstigneev** [comment]
Confirm, unable to debug anything.

**Comment by JDIZM** [comment]
Bumped into this issue trying to use @debug, no output provided.

**Comment by Aamirpare** [comment]
I have the same error and couldn't fix the beast even after wandering in web jangle.

$primary-color: #1919f9;
@debug $primary-color;

There is no output show of the above code.
