### ISSUE TITLE
How to get url in nuxtServerInit?

### ISSUE THREAD

**Issue by fahamidev** [nuxt/nuxt.js#6607]
Hi everyone.

Actually i have a dynamic website. So i don't have any static domain in my website. Really i want to get URL but i can't.
I mean, when i use from `req.headers.referer` or `req.headers.referrer`, they may not respond. And finally i can't detect the URL.

My nuxt project version:

```
"@nuxtjs/axios": "^5.6.0",
"nuxt": "^2.0.0",
"nuxt-i18n": "^6.2.1",
```
I spent a lot of time on my website and i'm very tired about it.
In what way can I use to get an URL_-(for example: http://www.example.com)-_ in Side Server mode?

**Comment by leosantoscunha** [comment]
Hi, I have a project like yours... 
I'm doing like this.

`  async nuxtServerInit({ commit }, { req }) {
    if (process.server) {
      if (req.headers !== undefined) {
        let host = _.split(req.headers.host, ":");
        await axios
          .get(`http://my-domain-api/config/${host[0]}`)
          .then(response => {
            let config = response.data;
            commit("setConfig", config);
          });
      }
    }
  }`

How do you are change route dynamically?

**Comment by fahamidev** [comment]
@leosantoscunha Thanks for your guidance. 

We use `IIS` webServer and alos use *reverse proxy*.
We run nuxtjs project in `localhost:3000` with `npm run  start`. And After each request I want to know which domain was requested. Because I don't have the domains. And by Reverse Proxy in IIS webServer  I redirect requested url on `localhost:3000`
