### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by yi-ge** [nuxt/nuxt.js#661]
I have the same problem : https://github.com/nuxt/nuxt.js/issues/658

I use

```
docker run --name wyrme --link yidata:yidatahost -itd -m 512m -v /root/site/wyrme:/root/site/wyrme -w /root/site/wyrme node:7.9.0 npm run production
```

but use memory over 2G.

**Comment by yi-ge** [comment]
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS  
b3cbca28bdf1        0.00%               `511.9 MiB` / 512 MiB     99.98%              10.6 MB / 19.2 MB   149 MB / 304 MB     28

**Comment by fxh615** [comment]
ye may be the same problem.

**Comment by Atinux** [comment]
Duplicate of #658

**Comment by pi0** [comment]
Please see #805 if still having problem and wish to help others resoling memory leaks :)
