### ISSUE TITLE
How can i set the default child route to show when navigating to the root url of a nested route when using nuxt-i18n

### ISSUE THREAD

**Issue by kgrosvenor** [nuxt/nuxt.js#6616]
### What problem does this feature solve?

I have no way of setting a default route for a set of nested children, for eg /account > should go to /account/details, however because i am using nuxt-i18n it's very difficult to detect the route...

### What does the proposed changes look like?

A way to set the default child within account/index.vue using a meta property of some kind.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9943">#c9943</a>)</em></sub></div>

**Comment by manniL** [comment]
There are a couple of ways:

1. Use `extendRoutes` to add a redirect
2. Use the [router-extras-module](https://github.com/nuxt-community/router-extras-module#readme) to do the same
3. redirect via webserver and internally link to /account/details aways (instead of /acount)
