### ISSUE TITLE
SPA mode seems to generate STATIC app

### ISSUE THREAD

**Issue by noerK** [nuxt/nuxt.js#6617]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/noerK/spa-demo](https://github.com/noerK/spa-demo)

### Steps to reproduce

Just run 'yarn build' in the provided repo or create a project on your own with 'spa' mode enabled in your nuxt.config.

I tried also adding the flag --spa, but it seems that nuxt always just generates a static application instead of a classic SPA application.

If you then run nginx or something similar to host your application its working fine BUT for direct links/reloads of dynamic routes (just as in static applications) - which makes sense if you take a look in the dist folder.

### What is expected ?

As descibed here: https://nuxtjs.org/guide/commands/

Nuxt should build a SPA application

### What is actually happening?

Nuxt is generating a static application

### Additional comments?

i really enjoy using nuxt and im hoping someone can help me solving this issue :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9944">#c9944</a>)</em></sub></div>

**Comment by aldarund** [comment]
I dont understand what you mean by static. Can you describe exactly what you expecting and what is happening.

**Comment by noerK** [comment]
With static i mean "Static Generated Deployment (Pre-rendered)" from  https://nuxtjs.org/guide/commands/. Where all your available routes get generated as folders + html files.

My application is just a frontend for an existing backend behind a login gateway so no SEO required. 
Whats not working are direct links to dynamic routes as /devices/123 (or page reloads).
If you navigate via nuxt router links it works perfectly fine.

**Comment by pi0** [comment]
@noerK I think your misunderstanding is because even with SPA mode, nuxt generates an HTML per route. But if you look at their source code, they are all the same and SPA.  The reason is that not all static hostings support SPA fallback. I assure you SPA dist is SPA :)

**Comment by noerK** [comment]
@pi0 ok 1 problem solved then :D. Thanks for clarification.
Im currently using nginx with default config. Am i missing something maybe?
Any idea why dynamic routes dont work on reloads/direct links? (in the real project im using no special slugs or anything - just params.id and _id files).

**Comment by manniL** [comment]
@noerK you need to redirect all traffic to that index.html (including errors).

**Comment by noerK** [comment]
@manniL this kinda feels really painful now... thank you all very much.
ofc the whole thing is working with pushState() 🤦‍♂ 

It's still somehow confusing that all routes get generated. Also a small hint in the documentation might be helpful - for other people like me :D

for anyone out there: i solved it with (nginx):
```
location / {
    try_files /index.html =404;
}
```
