### ISSUE TITLE
The async component cannot SSR in a named slot

### ISSUE THREAD

**Issue by klwfwdk** [nuxt/nuxt.js#6622]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/klwfwdk/nuxt_async_issue](https://github.com/klwfwdk/nuxt_async_issue)

### Steps to reproduce

1. clone the repositories
2.yarn install and start it by yarn dev or nom run dev
3.curl http://localhost:3000

### What is expected ?

the component import through "() => import('......')" can be SSR 

### What is actually happening?

This component does not appear in the results returned by SSR.
This component is rendered in the browser by javascript

### Additional comments?

in the reproduction , I imported three identical components except for the text through different ways. The last two components are import as async components.
the container components has 3 slots, the first two are named slots , the last one is default sold.
when I put three components into 3 sorts. the async component with default slots and the sync component with named slots are rendered and returned by the server. But the async with named slot does not appear in the result of the server rendering. 
In production mode(build and start),the first return is same as dev mode. but the fallowing return include the async component with named slot.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9950">#c9950</a>)</em></sub></div>

**Comment by klwfwdk** [comment]
The latest version does not resolve the issue

**Comment by manniL** [comment]
see #6844
