### ISSUE TITLE
nuxt-links containing "adver" in destination path triggers chunkload error

### ISSUE THREAD

**Issue by SunooBertsch** [nuxt/nuxt.js#6627]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/SunooBertsch/nuxt-chunk-err](https://github.com/SunooBertsch/nuxt-chunk-err)

### Steps to reproduce

- Run app in dev mode. 
- Click "To Advertising" link and view dev console. Chunkload error will appear.

### What is expected ?

Clicking link should take user to advertising page

### What is actually happening?

Clicking link triggers chunkload error

### Additional comments?

This only seems to happen when route contains the string "adver". Given this, it is impossible to link to the base URL + "/advertising". Nested routes containing "adver" seem to work as intended.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9954">#c9954</a>)</em></sub></div>

**Comment by SunooBertsch** [comment]
The issue seems to encompass additional route names. "ads" also triggers the abnormal behavior, and I'm assuming others do as well. I can confirm the bug with "ads", "advert", "advertising", etc.

**Comment by manniL** [comment]
Related to your adblocker I guesS?

**Comment by SunooBertsch** [comment]
@manniL You sir, are a genius. Thanks!
