### ISSUE TITLE
Set `process.server` and `process.client` in `nuxt.config.js`

### ISSUE THREAD

**Issue by chriscalo** [nuxt/nuxt.js#6629]
### What problem does this feature solve?

Right now, to support different configuration values for server and client contexts, entries in `nuxt.config.js` must expose options that are specific to the server or client. For example, in the `@nuxtjs/axios` module:

``` js
export default {
  modules: [
    "@nuxtjs/axios",
  ],
  axios: {
    baseURL: "http://localhost:8000/",
    browserBaseURL: "/",
  },
};
```

Unfortunately, not all configuration options are designed this way, so there's often no good mechanism for providing a different configuration value on the server and on the client.

An example is described in [this issue for the `@nuxtjs/apollo` module](https://github.com/nuxt-community/apollo-module/issues/272). The Apollo module only exposes a single `httpEndpoint` option, which means you can't provide a different value for the server and the client. This module assumes the GraphQL server is running on a different URL, making impossible to run GraphQL on the same server as Nuxt by setting the `httpEndpoint` to `http://localhost:8000/graphql` on the server and just `/graphql` on the client.

### What does the proposed changes look like?

By setting `process.server = true` when generating the server config and `process.client = true` when generating the client config, these issues go away, and they also might simplify Nuxt module implementations because they don't need to internally handle different config options:

``` js
export default {
  modules: [
    "@nuxtjs/apollo",
  ],
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint:
          process.server ? "http://localhost:8000/graphql" : "/graphql",
      },
    },
  },
};
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9956">#c9956</a>)</em></sub></div>

**Comment by pSnehanshu** [comment]
I would love to have this feature

**Comment by pi0** [comment]
@pSnehanshu If you follow the discussion of nuxt-community/apollo-module#272, it is not really a solution. `process.server` and `process.client` are provided via **webpack** during build time but nuxt config is loaded with node.js require. It means if we want to do this, have to inject into `process` and require `nuxt.config` each time twice by clearing require cache.

For the apollo-module, the same as the axios module now there is a new `browserHttpEndpoint` option that allows easily can clearely separately provide different values.
