### ISSUE TITLE
SSR of textarea value incorrectly stringifying null and undefined v-model bound values

### ISSUE THREAD

**Issue by perezd** [nuxt/nuxt.js#6639]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-vdcv8](https://codesandbox.io/s/codesandbox-nuxt-vdcv8)

### Steps to reproduce

bind a null/undefined value to v-textarea using v-model and observe the SSR HTML + screen flashing behavior.

### What is expected ?

there should be no value for null/undefined v-model bound values <textarea></textarea>

### What is actually happening?

The tag is ultimately being handed the string null or undefined as the innerText of the textarea.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9963">#c9963</a>)</em></sub></div>

**Comment by aldarund** [comment]
Its not a nuxt problem. Its how vuetify text field render null as value on SSR.
https://codesandbox.io/s/codesandbox-nuxt-1hqj7 see here i ouput value near textfield. And it only appears in textfield, but not directly. And you can check same in html.
Please open issue in vuetify instead

**Comment by KaelWD** [comment]
Issa vue bug https://github.com/vuejs/vue/issues/10803

**Comment by aldarund** [comment]
@KaelWD thanks for pinpointing issue :)
