### ISSUE TITLE
install nuxt_webpack@2.10.2 tip Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by williamren8118** [nuxt/nuxt.js#6644]
I npm install auto upgrade to nuxt_webpack@2.10.2,and I  npm run dev than tip error Cannot convert undefined or null to object,does any one meat this error?
![image](https://user-images.githubusercontent.com/31033240/68009639-75fc5380-fcbd-11e9-8600-a3d72719760b.png)

**Comment by javaLuo** [comment]
你解决了吗兄戴？

**Comment by zc0414** [comment]
有解决么?
