### ISSUE TITLE
[UNIVERSAL MODE] Nuxtjs fetches 2x on async created

### ISSUE THREAD

**Issue by ram231** [nuxt/nuxt.js#6646]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/ram231/INFORM.ED](https://github.com/ram231/INFORM.ED)

### Steps to reproduce

I'm using strapi for API prototyping. then I found out that whenever I reload the page, the logger prints 2 HTTP methods per request, if I'm navigating to other routes, it only fetches 1 request. 

```
async beforeCreate(){
    try {
     // using @nuxt/axios plugin.
     await this.$axios.get('url') // dummy url. but you get the point.
    } catch (error) {
      console.log(error)
    }
}
```

### What is expected ?

Single requests
[2019-11-01T14:51:20.019Z] debug GET \API(68 ms) 200

### What is actually happening?

2 Request on loading the page(SSR + CSR).
[2019-11-01T14:51:20.019Z] debug GET \API(68 ms) 200
[2019-11-01T14:51:21.486Z] debug GET \API(17 ms) 200

### Additional comments?

Although, using asyncData will only fetch the data once. putting in to other methods(such as created/mounted/beforeMount/beforeCreate) will have 2 requests instead of 1

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9975">#c9975</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. You have to use either [fetch](https://nuxtjs.org/api/pages-fetch/) or [asyncData](https://nuxtjs.org/api/). If you want to fetch data only on client side, then [mounted](https://vuejs.org/v2/api/#mounted) hook. Don't use `created` or `beforeCreate` for data fetching and async operations.

**Comment by ram231** [comment]
Thanks. If I want to fetch data that is not in the page component. I'll be likely to use mounted instead of other methods.
