### ISSUE TITLE
CLI accepts custom nuxt.config.js file as argument.

### ISSUE THREAD

**Issue by f15gdsy** [nuxt/nuxt.js#665]
Hi,
I think it makes sense to have the cli to accept custom nuxt.config.js as argument.

One scenario is that for test purposes,
I need to deploy the site to a CDN for purposes, whose address might look like this:

```
http://cdn.my-domain.com/test/app-bar/
```

So in nuxt.config.js, I need to set

```javascript
router: {
    base: '/test/app-bar/'
},

build: {
    publicPath: 'http://cdn.my-domain.com/test/app-bar/'
}
```

However, when I need to deploy to the production server,
I need to change the nuxt.config.js again.

**Comment by stephan281094** [comment]
You can use system environment variables for this use case:

```js
build: {
  publicPath: process.env.PUBLIC_PATH || 'http://cdn.my-domain.com/test/app-bar/'
}
```

Also, have a look at https://nuxtjs.org/api/configuration-env/#the-env-property.

**Comment by f15gdsy** [comment]
@stephan281094 Thank you very much! It solves my problem perfectly.

**Comment by alexmoreno** [comment]
You can also use `--config-file` param. Just use `nuxt build --config-file custom.nuxt.config.js`.
