### ISSUE TITLE
Proxy api call not working on netlify

### ISSUE THREAD

**Issue by amarmanhala** [nuxt/nuxt.js#6654]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/amarmanhala/weatherapp/](https://github.com/amarmanhala/weatherapp/)

### Steps to reproduce

I have made the weather app in nuxtjs. its working fine in development, but when I hosted on netlify darksky api is not calling. 
![issue.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/c4c21ef0-feb6-11e9-8f0a-e35343d830e6.png)

i have used proxy package to secure api key in nuxt.config

proxy: {
    '/api': {
      target: 'https: i removed url
      pathRewrite: {
        '^/api' : '/'
        }
      }

### What is expected ?

not working?

### What is actually happening?

![issue.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/3aad3190-feb7-11e9-8f0a-e35343d830e6.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9981">#c9981</a>)</em></sub></div>

**Comment by manniL** [comment]
The `proxy` module does not work with `nuxt generate` as documented. Set up the redirects via Netlify itself :relaxed:

**Comment by iabukai** [comment]
For more info : 
https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file
https://docs.netlify.com/routing/redirects/rewrites-proxies/

**Comment by brankosimic** [comment]
1. In static folder create a Netlify file named exactly like this: _redirects
2. Write a redirect line like this: `/api/*  https://api.example.com/:splat  200`

**Comment by manniL** [comment]
@brankosimic I'd suggest to take a look at https://github.com/nuxt-community/netlify-files-module/ as well 😋
