### ISSUE TITLE
IOS Splash screens not working

### ISSUE THREAD

**Issue by just-tom** [nuxt/nuxt.js#6655]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/just-tom/more-pwa-tes](https://github.com/just-tom/more-pwa-tes)

### Steps to reproduce

- Pull repo
- npm run build
- npm start

View on IOS device in broswer.

Alternatively
Head to the reproduction URL on a mobile IOS device. https://master-7rqtwti-3wuo2xdkxutcm.eu-4.platformsh.site/

### What is expected ?

A big orange splash screen to show when the app is opened on IOS deviced

### What is actually happening?

The standard black and then white screens shown whilst app is loading.

### Additional comments?

Google didn't turn up anything different to what I have tried. 
Also Whenever I try to run a lighthouse audit, its consistently failing basically saying that the App isn't PWA at all - anyone know why?

Thanks
Tom

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9987">#c9987</a>)</em></sub></div>

**Comment by aldarund** [comment]
you repo is 404, and it seems like it has nothing to do with nuxt itself, if u have problems with setup please ask in discord or if u have particular problem with pwa create bug in nuxt/pwa repo
