### ISSUE TITLE
Nuxt generate publicPath wrongly appended to build path

### ISSUE THREAD

**Issue by augnustin** [nuxt/nuxt.js#6656]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/augnustin/nuxt-example](https://github.com/augnustin/nuxt-example)

### Steps to reproduce

1. Run `nuxt generate` with the following config:

```
  build: {
    publicPath: '/youpi/_nuxt/',
  },
  generate: {
    dir: './youpi',
  },
```

2. HTML files are built in `./youpi` but assets are in `./youpi/youpi/_nuxt`
3. In HTML files, path to assets is `/youpi/_nuxt`

There is no solution: Either one statically serves `./youpi` but one doesn't have assets, or `./youpi/youpi` but `index.html` is not available then.

### What is expected ?

Assets should be in `./youpi/_nuxt`.

### What is actually happening?

Assets are in `./youpi/youpi/_nuxt`.

### Additional comments?

Question originally asked on SO: https://stackoverflow.com/questions/58713168/nuxt-generate-publicpath-wrongly-appended-to-build-path

In the build options, in addition to `publicPath`, which should only concern the **public** part of the path, hence in the HTML built, there should be a `assetsPath`, which defaults to `_nuxt`.

PS: I know why you do that, but making the Reproduction link mandatory is a pain...

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9989">#c9989</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @augnustin 

Actually it's the intented behaviour, since your have to publish the `dist/` (default `generate.dir`) to the static hosting, then you will have to upload the `./youpi` directory for you.

The `publicPath` is meant for the JS bundles, if you prefix it with `/youpi/`, it means that you host your Nuxt app it on something like http://example.com/youpi/

**Comment by augnustin** [comment]
Thanks for getting back @Atinux 

I'm not 100% sure to understand why this is intended, all those config directories kind of confused me. Having single purpose `publicPath` config felt like simplification to me, but it may not.

Anyway, regarding my case, I actually sorted it out by setting 

```
  router: {
    base: '/youpi'
  },
```

and it works without further config at http://example.com/youpi/

Please feel free to close if you are fine that there is no bug.

Cheers
