### ISSUE TITLE
Nuxt is throwing `Uncaught ReferenceError: exports is not defined` on transpiling an es6 library

### ISSUE THREAD

**Issue by SDVII** [nuxt/nuxt.js#6659]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-typescript-ch8jz?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-typescript-ch8jz?fontsize=14)

### Steps to reproduce

1. Setup a Nuxt project.
2. Install and import the `bip39` library.
3. Add the library to the `transpile` array in the `build` section of `nuxt.config.js`.

### What is expected ?

For the library to transpile correctly

### What is actually happening?

`Uncaught ReferenceError: exports is not defined` error is being thrown at  `Object.defineProperty(exports, "__esModule", { value: true });`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9991">#c9991</a>)</em></sub></div>

**Comment by aldarund** [comment]
Because its not es module but a commonjs.

**Comment by SDVII** [comment]
I think it is, due to the fact that it would through a syntax error on IE when it's not transpiled.

I even contacted the developers of the package and they said that it requires transpiling in order to work on IE. You can also check the package, there are arrow functions (IE usually breaks around there).

**Comment by aldarund** [comment]
see https://github.com/babel/babel/issues/9187

**Comment by SDVII** [comment]
I'll look into it, thanks for the reply.

**Comment by SDVII** [comment]
@aldarund Thanks, managed to fix the issue. For those who encounter a similar problem, this is my implementation:
```js
build: {
    babel: {
      sourceType: 'unambiguous',
      presets({ isServer }) {
        const targets = isServer ? { node: 'current' } : { ie: 11 };
        return [[require.resolve('@nuxt/babel-preset-app'), { targets }]];
      },
    },
    transpile: ['bip39'],
  },
```

**Comment by gcarpi** [comment]
@SDVII Thanks dude, you helped me a lot! I no longer knew what to do, deeply thankful.
