### ISSUE TITLE
JavaScript heap out of memory when saving css file

### ISSUE THREAD

**Issue by stigvanbrabant** [nuxt/nuxt.js#6662]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://jsfiddle.net/bmthrqf3/](https://jsfiddle.net/bmthrqf3/)

### Steps to reproduce

First time it builds correctly but when saving a css file after that the loader stays on 0% and eventually throws the javascript heap out of memory error.

### What is expected ?

To correctly rebuild after saving a css file

### What is actually happening?

The loader stays on 0% and eventually throws the javascript heap out of memory error.

### Additional comments?

I'm using tailwindcss.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9993">#c9993</a>)</em></sub></div>

**Comment by aldarund** [comment]
Provide a minimal full working repo where your error can be reproduced please

**Comment by stigvanbrabant** [comment]
https://github.com/stigvanbrabant/issue-repo, i noticed that it might be the variants that get registered. after i added those the tailwind compilation was taking a very long time.

**Comment by stigvanbrabant** [comment]
When optimizing my tailwind config file by applying tips from https://tailwindcss.com/docs/controlling-file-size, the issue seems to be resolved.
