### ISSUE TITLE
process.env.X not overrided by my Env variable.

### ISSUE THREAD

**Issue by bat79a** [nuxt/nuxt.js#6664]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

Hi.

I can't find why I'm not able to display env variable in a page or use it in a fetch method ?
I override the default env variable with kubernetes secrets.

The oauth package env are well overrided by my kubernetes secrets environment variables (oauthHost, oauthClientID and oauthClientSecret) !

But when I try to display the variables, default variable are shown...

Here is my dependencies in package.json :
```
  "dependencies": {
    "@fortawesome/free-regular-svg-icons": "5.11.2",
    "@fortawesome/free-solid-svg-icons": "5.11.2",
    "@nuxtjs/axios": "5.8.0",
    "@nuxtjs/dotenv": "1.4.1",
    "@nuxtjs/pwa": "^3.0.0-0",
    "@riophae/vue-treeselect": "0.4.0",
    "body-parser": "1.19.0",
    "bootstrap": "4.3.1",
    "bootstrap-vue": "2.0.4",
    "consola": "2.10.1",
    "jquery": "3.4.1",
    "nuxt": "2.10.2",
    "nuxt-fontawesome": "0.4.0",
    "nuxt-i18n": "6.3.0",
    "nuxt-oauth": "2.2.0",
    "nuxt-webfontloader": "1.1.0",
    "sass": "1.23.3"
  },
```

Here is my nuxt.config.js for catch the env variable from kuberetes secrets
```
export default {
  mode: 'universal',
  /*
  ** Environment variables in .env
  */
  env: {
    versionTag: process.env.TAG,  // env variable from .env file
    oauthApiHost: process.env.OAUTH_API_HOST || 'https://api.oauth.io/',
    oauthApiUser: process.env.OAUTH_API_USER || 'oauth-user',
    oauthApiPassword: process.env.OAUTH_API_PASSWORD || 'default_password',
    oauthID: process.env.OAUTH_CLIENT_ID || 'abc'
  },
...
buildModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    // '@nuxtjs/eslint-module'
    ['@nuxtjs/eslint-module', {
      'vue/html-self-closing': ['error', {
        'html': {
          'void': 'always',
          'normal': 'never'
        }
      }]
    }],
    ['@nuxtjs/dotenv', { systemvars: true }]
  ],
...
oauth: {
    sessionName: 'Manage',
    secretKey: process.env.SECRET_KEY || 'key-manage',
    oauthHost: process.env.OAUTH_HOST || 'https://api.oauth.io/oauth2/',
    oauthClientID: process.env.OAUTH_CLIENT_ID || 'abc',
    oauthClientSecret: process.env.OAUTH_CLIENT_SECRET || '123',
    scopes: ['openid', 'profile'],
  },
```

And my index.vue :
```
<template>
  <div>
        <p>
          - OAuthId : {{ oauthId }} => Display : abc
          - OAuthPass : {{ oauthPass }} = > Display : default_password
        </p>
  </div>
</template>

export default {
  data () {
    return {
      oauthPass: process.env.oauthApiPassword,
      oauthId: process.env.oauthID,
}
````

For the test I display the oauthClientID in a template and it display the default value set in my config. But the auth module works well and use the kubernetes secret value ???

Thx a lot.

### What is expected ?

Display the overrided env variables

### What is actually happening?

Display the default variables set in the nuxt.config.js

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9995">#c9995</a>)</em></sub></div>

**Comment by aldarund** [comment]
env variables are build time. So the ones that are set when you build your app is the one that beeing used, not the ones  that youj are using to start app

**Comment by bat79a** [comment]
Hummm.
If I understand, env variable injected are use only for the build time and after forgotten ?

It's not really that I understand when I read the doc : https://fr.nuxtjs.org/api/configuration-env/

If the variables are forgotten do you know the best solution and the more secure one (because it's secrets) for record some variables injected in the start app and reuse this variables in pages and fetch function ?

I want to be able like in my django app to inject kubernetes secrets variables that I catch in my settings.py (VERSION = os.getenv('VERSION') and get back in my views (version = settings.VERSION) for sending them to the template.

Thx a lot again for your help.

**Comment by aldarund** [comment]
Not sure what you mean by forgotten. Basically it will replace process.env.VAR in your code with actual var value at build time. And it will work the way you described, but it only set during build time not runtime. 
see https://github.com/samtgarson/nuxt-env for runtime env vars

**Comment by bat79a** [comment]
I will Check this lib.

Thx a lot :)

**Comment by bat79a** [comment]
The lib works well for common env vars, but i not able to catch my secret variable (variable with the parameter secret: true).

I have posted an issue in the github code project.
