### ISSUE TITLE
npm run start后，3000端口一直被占用，无法释放

### ISSUE THREAD

**Issue by Jam1zhu** [nuxt/nuxt.js#6667]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Steps to reproduce

使用脚手架初始化项目。文件打包后，执行`npm run start`，项目正常启动。
1、`ctrl+c`退出，访问`http://localhost:3000`，项目仍在运行。
2、关闭了node所有进程 / taskkill关闭了3000端口相关进程，访问localhost:3000，项目仍在运行。
3、重启电脑，访问localhost:3000，项目仍在运行。 

已清空缓存。window10系统，公司电脑，没有最高权限，难道是有进程我没权限看？有遇到过这个问题的大神吗？SOS

### What is expected ?

正常关闭进程

### What is actually happening?

进程无法关闭，想电脑病毒

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10000">#c10000</a>)</em></sub></div>

**Comment by yoyo837** [comment]
我想你肯定是哪里弄错了。没有任何其他人有类似问题。

**Comment by Jam1zhu** [comment]
@yoyo837 
重启电脑访问3000，还是能访问。有点无奈。。。有什么直接点的方式彻底关闭吗

**Comment by Jam1zhu** [comment]
![31a442a0-7a08-4778-ba70-17be59ad8119](https://user-images.githubusercontent.com/21252750/68555091-dbdb9e80-0466-11ea-8596-1bc33a5687c1.gif)
@yoyo837 重启电脑，直接访问localhost:3000 清除缓存刷新，先显示【无法访问】，然后浏览器自动刷新页面，加载了之前的页面内容。

**Comment by Dshufeng** [comment]
进程都关了还能看到,不可能吧.不然试着换个端口.看看还会发生吗

**Comment by runhuaxue** [comment]
我也遇到了这个问题，3000端口一直刷不出来 ;(
请参照：https://github.com/nuxt/nuxt.js/issues/6442
我是按照提示，更新了我的node，
“Just a heads up: Node.js v12.11.0 fixes the Node.js bug mentioned above. Please give that a try in case you are using Node.js v12.x.”

**Comment by Overcase** [comment]
问题的原因是因为开启了 pwd, chrome  中注册了 Service Workers， 用 chrome dev tool 的 Application 选项中的 Service Worker 卸载即可。

**Comment by TiuBen** [comment]
net stop hns
