### ISSUE TITLE
Webpack doesn't resolve from node_modules inner structure

### ISSUE THREAD

**Issue by toxamiz** [nuxt/nuxt.js#6672]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/toxamiz/nuxt-temp](https://github.com/toxamiz/nuxt-temp)

### Steps to reproduce

npm i
npm run dev

### What is expected ?

Module imported and logged into console

### What is actually happening?

SyntaxError - Unexpected token import

### Additional comments?

Base webpack config have no issue with such import.
If import path change to full relative path, then works fine.
```js
import {LightProbeGenerator} from '~/node_modules/three/examples/jsm/lights/LightProbeGenerator'
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10005">#c10005</a>)</em></sub></div>

**Comment by aldarund** [comment]
Nuxt dont transpile files that are comes from node modules, so there shouldnt be import/export in that files. If you want it to be transpiled you need to specify it manually in config
https://nuxtjs.org/api/configuration-build/#transpile
