### ISSUE TITLE
 after  generate，the  layout   Failure

### ISSUE THREAD

**Issue by zhangsaihui** [nuxt/nuxt.js#6680]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[http:baidu.com](http:baidu.com)

### Steps to reproduce

more layouts, used not default ,  nuxt  generate,   use nginx power zhe dist file  ,bug layout lost

### What is expected ?

 after  generate，the  layout should work 

### What is actually happening?

more layouts, used not default ,  nuxt  generate,   use nginx power zhe dist file  ,bug layout lost

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10014">#c10014</a>)</em></sub></div>

**Comment by zhangsaihui** [comment]
has no url ,

**Comment by manniL** [comment]
Please provide more info. I don't understand the problem.

**Comment by zhangsaihui** [comment]
> Please provide more info. I don't understand the problem.

sorry ， my nginx config have a error。

**Comment by manniL** [comment]
Unfortunately we can't help you with your NGINX config here.
