### ISSUE TITLE
Generating an SPA with the index page only

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#6682]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://sorry.no-example.given](https://sorry.no-example.given)

### Steps to reproduce

1. Create a nuxt app via `create-nuxt-app`
2. Choose SPA (and not universal)
3. Make sure that multiple pages exist (e.g. index.vue & about.vue)
4. Run `nuxt generate`

### What is expected ?

To have just one index.html for the SPA as that'd be enough

### What is actually happening?

HTML files are generated for each pages and are (almost?) identical.

### Additional comments?

Generating only the index.html will reduce generation time for larger SPA projects by sacrificing little.

### Current workaround

One could use [`generate.excludes`](https://github.com/nuxt/nuxt.js/pull/4754) ([Docs](https://nuxtjs.org/api/configuration-generate#exclude)) to exclude all routes beside the index route.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10017">#c10017</a>)</em></sub></div>

**Comment by geongeorge** [comment]
Single Page Application means an application with a single page.
Nuxt seems to be generating multiple HTML pages for each non-dynamic route.
