### ISSUE TITLE
Status Code - 404 Template

### ISSUE THREAD

**Issue by aloiki** [nuxt/nuxt.js#6684]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[localhost:3000/does-not-exists](localhost:3000/does-not-exists)

### Steps to reproduce

Run your nuxt application in spa-mode and navigate to a route that does not exist in your routing. 
The nuxt-error template is rendered but the status code for the document is not correct. It returns a 200 as status code.

I tried to add the following code in my nuxt.config.js:

  generate: {
    fallback: true, // if you want to use '404.html' instead of the default '200.html'
  },

but the status code does not change.

![Bildschirmfoto 2019-11-11 um 16.21.29.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/14f4ecf0-0497-11ea-8d24-251f39f49bb3.png)

### What is expected ?

The document should return a 404 as a status code.

### What is actually happening?

It returns a 200 as status code.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10020">#c10020</a>)</em></sub></div>

**Comment by manniL** [comment]
You can't avoid that when using SPA mode as there is no way to detect if a route was "found" or not. Everything is served via the `index.html` with a 200 status code.

It is possible with pre-rendering or SSR though.

**Comment by aloiki** [comment]
That makes sense for me now... but is there even no way to configure the right status code with nginx?

**Comment by manniL** [comment]
As you can't distinguish between an "error page" and a "valid page" without SSR/static generation, no.

**Comment by acamenhas** [comment]
In SPA mode, it's possible in my middleware to raise an 404 error?

if(...) {
   //raise an 404 error
}
