### ISSUE TITLE
ERROR EINVAL: invalid argument mkdir .well-known

### ISSUE THREAD

**Issue by nelsonlarocca** [nuxt/nuxt.js#6687]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://nolink.com](https://nolink.com)

### Steps to reproduce

compiling using Nuxt ver 2.10.2, universal mode / dev / nodejs ver 12.13.0
(update here)

**TO REPLICATE** just add nuxt-twa-module to nuxt.config.js

 ERROR  EINVAL: invalid argument, mkdir 'C:\Projects\NUXT\myprojectC:\Projects\NUXT\myproject.nuxt\dist\client\.well-known'     

Any help about that ?
Thanks

### What is expected ?

fix it

### What is actually happening?

displaying that error in the console but continues running

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10021">#c10021</a>)</em></sub></div>

**Comment by aldarund** [comment]
Make sure you have a permessions and provide a reproduction please

**Comment by nelsonlarocca** [comment]
I've just found that module is not from Nuxt and that also has been archived so feel free to remove this post from the queue if you like to.

Thanks

**Comment by nelsonlarocca** [comment]
found a FIX

setting at nuxt.config.js

```
 [
      'nuxt-twa-module',
      {
       ...
        distFolder: '/.nuxt/dist/client',
       ...      
       }
],
```

**Comment by manniL** [comment]
Thanks for the info. Closing here.
