### ISSUE TITLE
vue packages version mismatch is not an Error

### ISSUE THREAD

**Issue by tonyrewin** [nuxt/nuxt.js#669]
Now many reusable components fail like that
```
Error: 

Vue packages version mismatch:

- vue@2.3.2
- vue-server-renderer@2.2.6
```
maybe there is a way to use them replacing this Error with Warning?

**Comment by pi0** [comment]
@tonyrewin As a best practice avoid adding `vue`, `vue-server-renderer` or `vue-template-compiler` dependencies directly into `package.json` when using Nuxt.js. (If you REALLY need newer version, you should provide 3 of them not just one)

**Comment by tonyrewin** [comment]
It does not help. Steps to reproduce: 
```
yarn add vue2-medium-editor vue@latest vue-template-compiler@latest vue@server-renderer@latest
nuxt build
```

**Comment by pi0** [comment]
If entirely removing vue-* dependencies (and then yarn again) also not working. I think we need to wait for next nuxt release. Seems some other dependency requires vue 2.3 which is currently semver incompatible with nuxt's vue requirement constraints.

**Comment by tonyrewin** [comment]
with-vuetify example does not work too

**Comment by GergelyLakatos** [comment]
same here...

**Comment by bimohxh** [comment]
also the same error, my app is now stop

**Comment by yanghuayi** [comment]
I also encountered the same problem, hope to solve as soon as possible, my project is now stop

**Comment by pi0** [comment]
Did you explicity set `vue` `vue-server-renderer` and `vue-template-compiler` in your package.json ? (They should be exactly 2.2.6 for now)

**Comment by bimohxh** [comment]
I have two module relation with `vue-`

```
"vue-i18n": "^6.1.1",
"vue-svg-icon": "^1.2.9"
```

**Comment by pi0** [comment]
@bimohxh Show *explicitly* add them to 'dependencies' section :))

**Comment by bimohxh** [comment]
@pi0
"vue-i18n": "^6.1.1":

```
.....
"vue": "^2.2.0"
```

"vue-svg-icon": "^1.2.9"

```
....
"vue-loader": "^10.0.0",
"vue-template-compiler": "^2.1.0",
"vue": "^2.0.1"
```

**Comment by pi0** [comment]
Both vue-i18n and vue-svg-icon are semver compatible with 2.2.6 :)) I'll open a PR into your repo for fix

**Comment by pi0** [comment]
Steps to fix:
```
yarn add vue@2.2.6 vue-template-compiler@2.2.6 vue-server-renderer@2.2.6
```

Exact problem:
`element-ui@1.3.1` which was depending on `vue@^2.3.0` as a peer dependency.

**Comment by bimohxh** [comment]
@pi0 Thanks very much! It works now. 

so this caused by `element-ui@1.3.1` ?

**Comment by pi0** [comment]
Yes. we may add some peer dependencies in next release to avoid (or at least get npm warning) in this conditions.
