### ISSUE TITLE
API interface error when generating, how to prevent the errored page from continuing to generate

### ISSUE THREAD

**Issue by Maple13** [nuxt/nuxt.js#6690]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Steps to reproduce

yarn run generate

### What is expected ?

When an error is generated API interface, specify the page does not generate entity .html file

### What is actually happening?

Page generated as "Server Exception" or entity file "404" content

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10023">#c10023</a>)</em></sub></div>

**Comment by manniL** [comment]
Could you provide more details? I don't understand the issue :|

**Comment by Maple13** [comment]
@manniL 
sorry my English is not good.
My page will be generated periodically.
When generate, when the index page triggers an error due to an API request, can it prevent the index from continuing to execute the generate process?
If you can't prevent the index page from continuing to generate, then I'll get an html with the content 404 or server exception hint.
And I don't want the user to see that the index page is full of 404 or server exception prompts, preferring the user to see the html that was last normal.

**Comment by manniL** [comment]
You can fail the whole build on a page error via `yarn generate --fail-on-page-error` :relaxed:

Besides that you could build the logic yourself (e.g. use a cached API response instead or so).
