### ISSUE TITLE
serverMiddleware not being triggered by asyncData when SSR 

### ISSUE THREAD

**Issue by colwilson-mo** [nuxt/nuxt.js#6692]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/colwilson/bug-report-nuxt-ssr-1](https://github.com/colwilson/bug-report-nuxt-ssr-1)

### Steps to reproduce

> nuxt.config.js
```
  serverMiddleware: [{
    path: '/api',
    handler: '@/serverMiddleware/api'
  }],
```
> serverMiddleware/api.js 
```
export default function (req, res, next) {
  console.log(req.path)
  const data = {
    data: 'data'
  }
  res.setHeader("Content-Type", "application/json")
  res.end(JSON.stringify(data))
  next()
}
```
> pages/index.vue
```
<template>
  <div class="index">
    index
  </div>
</template>

<script>
export default {
  name: 'index',
  async asyncData({ params, env, $axios }) {
    console.log("client?", process.client)
    const url = '/api'
    try {
      const response = await $axios.get(url);
      const data = response.data
      return {
        data
      };
    } catch (error) {
      console.log(error.message);
    }
  }
}
</script>

```

### What is expected ?

On loading the page for first time or hitting F5 the url path should appear in the console.

### What is actually happening?

console displays "Request failed with status code 503 "

### Additional comments?

I can't believe I can be the only one seeing this so I assume my code is incorrect, but I have tried for a day to get it to work without success.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10025">#c10025</a>)</em></sub></div>

**Comment by manniL** [comment]
Updated your example a little: https://codesandbox.io/s/bug-report-nuxt-ssr-1-6uqzp

Works fine on server side but not on the client side because you did not define your axios base URL. On client side, it still tries to access localhost:3000 as shown below.

Not a Nuxt bug -> closing here.


![image](https://user-images.githubusercontent.com/640208/69324684-346e2100-0c49-11ea-87c8-1751fafc933d.png)
