### ISSUE TITLE
Nuxt hot reload recompile too many times

### ISSUE THREAD

**Issue by asterd** [nuxt/nuxt.js#6693]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://jsfiddle.net/d8yugmsn/](https://jsfiddle.net/d8yugmsn/)

### Steps to reproduce

edit any file and the cli and save

### What is expected ?

The hot reload start one compilation of the project

### What is actually happening?

The hot reload start one compilation and then, when it has done, start another compilation due to a modification of a file in node_modules/.cache/babel-loader folder. It recompiles another time if there is a change in the .idea folder (eg workspace.xml)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10026">#c10026</a>)</em></sub></div>

**Comment by aldarund** [comment]
Provide a full reproduction, not just nuxt config.
