### ISSUE TITLE
query parser is different between asyncData(or fetch) and $route.query

### ISSUE THREAD

**Issue by shalldie** [nuxt/nuxt.js#6698]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/shalldie/nuxt-query-server-client](https://github.com/shalldie/nuxt-query-server-client)

### Steps to reproduce

1. $ npm install
2. $ npm run dev
3. $ open "http://localhost:3000/?name=%250a"

I think query is { name: '%0a' } , but the query seems to be decoded twice in ssr.

### What is expected ?

Query in asyncData(or fetch) is same with $route.query.

### What is actually happening?

Query in asyncData(fetch) seems to be decoded twice, which make itself different with $route.query.

### Additional comments?

Please see https://github.com/shalldie/nuxt-query-server-client

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10029">#c10029</a>)</em></sub></div>

**Comment by shalldie** [comment]
any progress ?

**Comment by shalldie** [comment]
any progress by now 0.0 ?

**Comment by shalldie** [comment]
one month passed

**Comment by talebi1** [comment]
packages/server/src/middleware/nuxt.js  (line 12)

https://github.com/nuxt/nuxt.js/blob/68cb23109422b104cde4d92094030c0362b83ea9/packages/server/src/middleware/nuxt.js#L12

should remove the decodeURI call --> const url = req.url;

**Comment by Kolobok12309** [comment]
[Reproduce link](https://codesandbox.io/s/nuxtjs-query-string-parse-error-md7fu)

**Comment by Cilo-8080** [comment]
same question, still remaining. It seems the asyncData decode the url twice
