### ISSUE TITLE
Cannot deploy on an alternative server

### ISSUE THREAD

**Issue by altcointrading** [nuxt/nuxt.js#670]
I am trying to deploy on a VPS, it needs to be that particular VPS because of server location so I cannot use Cosmic JS or heroku. 

I am not able to set up a post-receive hook yet [(all advices from here failed](https://github.com/nuxt/nuxt.js/issues/38)) so I am looking for an alternative way. 

I have been trying to start the application directly from the DocumentRoot as well but `npm start` keeps crashing although I've got the dependencies all right

```
[xxxxx public_html]$ npm start

> @ start /var/www/xxxxxxxxx/public_html
> nuxt start

sh: nuxt: command not found

npm ERR! Linux 2.6.32-042stab123.1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `nuxt start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ start script 'nuxt start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls

�
{
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/xxxxxxx.net/public_html/npm-debug.log
```

I also understand I cannot use `nuxt generate` to get a static deployment into /dist/ because I would have to manually declare the permalinks for dynamically generated sites https://nuxtjs.org/api/configuration-generate/

Is there a documented step by step way to deploy nuxt app to a server manually?

**Comment by alexchopin** [comment]
Have you run `npm install` or `yarn`?
It seems that you haven't nuxt installed on the machine.

**Comment by altcointrading** [comment]
Yes ofc, `npm install` first.

**Comment by kodekrendel** [comment]
@altcointrading in which directory you execute command?

**Comment by altcointrading** [comment]
@kodekrendel In the directory that has a clone of the whole project. I started a clean project on a clean server and got this part working.

```
npm install
npm build
npm start
```

which works with an nginx config like this

```
server {
    listen 80;
    server_name example.com;
    location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         http://127.0.0.1:3000;
    }
}
```

However, I don't know how to run it in the background. I tried to create a script that only contains `npm run build && npm start` so that I can use PM2 `pm2 start run.js` which shows it as success ("app online") but the homepage is not there (502 bad gateway).

Do you know how to do it with PM2?

**Comment by kodekrendel** [comment]
@altcointrading what is `run.js`?

**Comment by kodekrendel** [comment]
@altcointrading I just tried `pm2 start npm --name "nuxt" -- start` and it works.

**Comment by kodekrendel** [comment]
Also I am able to start with just `pm2 start nuxt`.

**Comment by uptownhr** [comment]
can you please share your package.json

**Comment by vinaybedre** [comment]
Check your node version. Nuxt needs node >=6.11

If you do npm install with older release of node, we dont get any error and one will be in assumption everything went well.
