### ISSUE TITLE
Force parent page to refresh

### ISSUE THREAD

**Issue by Nainterceptor** [nuxt/nuxt.js#671]
Hello,

How can I force, a page to refresh data when nuxt-child change ? If it should be automatic, we've an issue here, but I guess that's for optimization purpose. But in this cas, when I'm on SSR I have a content mismatch.

You can see my problem here : https://glitch.com/edit/#!/nuxt-issue-671

Thanks for your help,
Gaël

**Comment by alexchopin** [comment]
Hi, there is no issue in your example. All data are good.

**Comment by Nainterceptor** [comment]
Hello,

On my side, when I follow "To parent", I have "Hi from parent"
Then, I click on "To about", and the parent page is not refreshed, So I have "Hi from parent" (Async data of the parent is not called)
Then, I refresh my page (to get server rendering) and now I have "Hi from parent-about".

So I've a mismatch between client & server rendering. Is it normal ?
