### ISSUE TITLE
srcDir instruction in production bundle's uses wrong static directory

### ISSUE THREAD

**Issue by Ghalnas** [nuxt/nuxt.js#6714]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/Ghalnas/nuxt-typescript-vuetify/tree/srcdir](https://github.com/Ghalnas/nuxt-typescript-vuetify/tree/srcdir)

### Steps to reproduce

Clone repository, checkout `srcdir` branch.

Running `npm run dev` will not show any issue.
Running `npm run build` then `npm start` shows the issue.

### What is expected ?

Production build to use `src/static` directory, showing nuxt's logo on
`localhost:3000/favicon.ico`

### What is actually happening?

Production build uses root `static` directory, showing stackoverflow's favicon on `localhost:3000/favicon.ico`.
Might need a hard refresh of browser to show non-cached version.

This is happening with everything put in the `src/static` directory, so for instance, `localhost:3000/sw.js` leads to a 404.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10046">#c10046</a>)</em></sub></div>

**Comment by petergaal91** [comment]
Same issue here.

If I change the srcDir option in nuxt.config.js file everything is fine, but If I rename that file to nuxt.config.ts:
`No pages directory found in [cwd-dir-path]. Using the default built-in page.`

So it's seems to be a typescript compiler issue.

**Comment by Ghalnas** [comment]
Woopsie, I forgot to use `nuxt-ts` in start script, everything works fine with that.
@petergaal91 have you checked if unlike me, you set up nuxt typescript runtime correctly ? 😅
