### ISSUE TITLE
router.trailingSlash cause problems on nested routes

### ISSUE THREAD

**Issue by vicu-retargeting** [nuxt/nuxt.js#6715]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-drxmn?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/codesandbox-nuxt-drxmn?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

nuxt.config.js

```
export default {
  ...,
  router: {
    trailingSlash: true,
    extendRoutes(routes, resolve) {
      console.log(routes);
    }
  },
  ...
};
```

pages structure:
```
-- pages
---- test.vue
------ test/index.vue
```

### What is expected ?

expected generated routes:

```
[
  {
    path: '/test/',
    component: '/sandbox/pages/test.vue',
    chunkName: 'pages/test',
    pathToRegexpOptions: {
      strict: true
    },
    children: [
      [Object]
    ]
  },
  {
    name: 'index',
    path: '/',
    component: '/sandbox/pages/index.vue',
    chunkName: 'pages/index',
    pathToRegexpOptions: {
      strict: true
    }
  }
]
```

### What is actually happening?

generated routes:
```
[
  {
    name: 'test',
    path: '/test/',
    component: '/sandbox/pages/test.vue',
    chunkName: 'pages/test',
    pathToRegexpOptions: {
      strict: true
    },
    children: [
      [Object]
    ]
  },
  {
    name: 'index',
    path: '/',
    component: '/sandbox/pages/index.vue',
    chunkName: 'pages/index',
    pathToRegexpOptions: {
      strict: true
    }
  }
]
```

### Additional comments?

And of course we got the following warning message in console:

 WARN  [vue-router] Named Route 'test' has a default child route. When navigating to this namedroute (:to="{name: 'test'"), the default child route will not be rendered. Remove the name fromthis route and use the name of the default child route for named links instead.

 WARN  [vue-router] Duplicate named routes definition: { name: "test", path: "/test/" }

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10047">#c10047</a>)</em></sub></div>

**Comment by cain** [comment]
Is this related #6783
