### ISSUE TITLE
Extending Nuxt routes and URI encoding

### ISSUE THREAD

**Issue by begueradj** [nuxt/nuxt.js#6727]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

In **nuxt.config.js** I extend the routes this way:

```javascript
extendRoutes(routes, resolve) {
  routes.push({
    path: '/*/' + 'foo/' + '(:[0-9].*)?/',
    component: resolve(__dirname, 'path/to/sonme/component')
  })
})
```

### What is expected ?

I expect when my application point to a URL like this one for example:
**http://127.0.0.1/shirts/shirt:2/shirtedition**
my application should not crash

### What is actually happening?

The application crashes and I receive this error message:

>Expected "1" to match "\:[0-9].*", but received "%3A2"

### Additional comments?

I tried to encode the **:** with:
 - `path: '/*/' + 'foo/' + encodeURIComponent('(:[0-9].*)?/'),`
 - `path: '/*/' + 'foo/' + '('+encodeURIComponent(':')+'[0-9].*)?/',`
 - `path: encodeURI('/*/' + 'foo/' + '(:[0-9].*)?/'),`

But none of them worked even if the error disappeared but I did not land to my component in question (`component: resolve(__dirname, 'path/to/sonme/component')`)

I did not reproduce the bug, hopefully the information is enough

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10057">#c10057</a>)</em></sub></div>

**Comment by m7rlin** [comment]
Same thing with @ character.
