### ISSUE TITLE
Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by mhajder** [nuxt/nuxt.js#6728]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[I can provide a repository but in private](I can provide a repository but in private)

### Steps to reproduce

Node production

```
>nuxt build
>nuxt start
```
When I try to open the page I get such an error.
![error](https://user-images.githubusercontent.com/6783135/69613935-ab812c00-1032-11ea-9a92-97ae4d622e07.png)

Console:
```
 ERROR  Cannot read property 'protocol' of undefined

  at t.exports (server.js:1:26310)
  at d (server.js:1:23078)
  at Object.<anonymous> (server.js:1:4386)
  at r (server.js:1:194)
  at Module.<anonymous> (server.js:1:70037)
  at r (server.js:1:194)
  at Object.<anonymous> (server.js:1:23665)
  at r (server.js:1:194)
  at server.js:1:1309
  at Object.<anonymous> (server.js:1:1319)
```

In node development, everything is ok.

### What is expected ?

Launching the application without problems.

### What is actually happening?

The application won't start.

### Additional comments?

Building is successful. It makes no difference whether I run the project via my own server.js file or the nuxt command.

package.json
```
{
	"name": "nuxt-socketio",
	"scripts": {
		"dev": "nodemon -w server.js -w nuxt.config.js server.js",
		"build": "nuxt build",
		"start": "node server.js",
		"heroku-postbuild": "npm run build",
		"test": "jest --runInBand --watchAll"
	},
	"dependencies": {
		"@nuxtjs/google-analytics": "^2.2.0",
		"array-move": "^1.0.0",
		"axios": "^0.19.0",
		"dotenv": "^8.0.0",
		"express": "^4.17.1",
		"jsonwebtoken": "^8.3.0",
		"moment": "^2.22.2",
		"mongodb": "^3.1.13",
		"nuxt": "^2.10.2",
		"nuxt-dropzone": "^0.2.8",
		"socket.io": "^1.7.2",
		"socket.io-client": "^1.7.2",
		"vue-awesome-swiper": "^3.1.3",
		"vue-events": "^3.1.0",
		"vue-multiselect": "^2.1.3",
		"vue-toasted": "^1.1.25",
		"vue2-dropzone": "^3.5.2"
	},
	"devDependencies": {
		"node-sass": "^4.13.0",
		"sass-loader": "^7.3.1"
	}
}
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10058">#c10058</a>)</em></sub></div>

**Comment by aldarund** [comment]
Its probably a bug in your code. E.g. you dont set some env variable during build that is needed for app to run

**Comment by mhajder** [comment]
> Its probably a bug in your code. E.g. you dont set some env variable during build that is needed for app to run

Only this is almost the default code from nuxt.js. That is why I wonder what may be missing.

**Comment by lengjing** [comment]
I had this problem too in nuxt@2.8.1 and solved it by this
```
if(process.server && req){
  // req.protocol
}
```

**Comment by aldarund** [comment]
@mhajder keep in mind that env variables are set during build time, not runtime. So if u build without them and only set it when u start the app - it wont work

**Comment by mhajder** [comment]
> @mhajder keep in mind that env variables are set during build time, not runtime. So if u build without them and only set it when u start the app - it wont work

Yes I know it, Environment variables are set correctly.

**Comment by aldarund** [comment]
show your server.js . ANd why you are launching it via server.js not via nuxt dev ?
