### ISSUE TITLE
nuxt webpack not compatible with corejs 3.0

### ISSUE THREAD

**Issue by fengerzh** [nuxt/nuxt.js#6734]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://www.google.com](https://www.google.com)

### Steps to reproduce

When yarn install nuxt project, report the warning:

```
warning nuxt > @nuxt/webpack > @nuxt/babel-preset-app > core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

### What is expected ?

No warning when install.

### What is actually happening?

The warning shows.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10061">#c10061</a>)</em></sub></div>

**Comment by manniL** [comment]
PR open at https://github.com/nuxt/nuxt.js/pull/6721#issuecomment-558847960

**Comment by manniL** [comment]
Closing here as https://github.com/nuxt/nuxt.js/pull/6721#issuecomment-558847960 landed ☺️
