### ISSUE TITLE
google tag manager example

### ISSUE THREAD

**Issue by cayaner** [nuxt/nuxt.js#674]
it's almost the most developer friendly technology ever,, in my opinion .. keep moving forward.

**Steps to reproduce**
i'v tryed to add [https://tagmanager.google.com](url) to my nuxt app,
followed this example [https://nuxtjs.org/faq/google-analytics](url) here and it works fine for just google analytics,,
unlike analytics .. google tag manager requires two steps to include it in your app the first is a head `script` tag, the other is a `noscript` tag needs to be placed immediately after `body` opening tag.
this is the script tag included as explaned in the analytics example:
![screenshot from 2017-05-06 21-15-12](https://cloud.githubusercontent.com/assets/19613212/25774894/ee64959e-3244-11e7-9f05-0a9ca5d19dd2.png)

this the included `noscript` tag:
```
<noscript>
    <iframe src="//www.googletagmanager.com/ns.html?id=GTM-XXXXXX" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
```
it works but with no effect `router.afterEach()` 
and it causes this error
![screenshot from 2017-05-06 21-08-54](https://cloud.githubusercontent.com/assets/19613212/25774851/0e9d80b0-3244-11e7-9e1f-5f7611bc19e7.png)

thanks in advance ...

**Comment by t0ker** [comment]
Would love to see this as well :)

**Comment by juliojerrick** [comment]
Same

**Comment by juliojerrick** [comment]
@cayaner I'm pretty sure you.shouldnt be inject the script on every route change

**Comment by juliojerrick** [comment]
Try maybe modfying the default template app.html and put it right into the head. All you would have to do is make sure on every route change you either push a virtual page event or hope Google tag manager handles it

**Comment by cayaner** [comment]
it works fine but for the first load or when reload ,, we need to rerun the `googletagmanager` script or whatever.
the problem is to tell `googletagmanager` when the route changes to act like the whole page reloaded.

@juliojerrick i know that .. but i'm trying to find a way to rerun the script after each route change.

**Comment by juliojerrick** [comment]
@cayaner Why would you rerun the script on every route change? Just include the the two parts of the script statically and then push virtual page view events on the route changes.  If pushing the page view doesn't work then it could be that you the reference to the script object isn't available in that scope.

**Comment by cayaner** [comment]
@juliojerrick  how can i  push virtual page view events on the route changes?

**Comment by juliojerrick** [comment]
@cayaner here's an guide on doing virtual page views with gtm.

https://www.webmethod.co.uk/blog/2015/06/tracking-virtual-pageviews-in-google-tag-manager-google-analytics/


you'll basically push data onto the datalayer object which should exist. If it you get an undefined or something then it's possible that route function scope can't access the scope it needs or  because it's server side?  If it is able to access it then you'll have no issues.

<script type="text/javascript">
   dataLayer.push({
      'event':'VirtualPageview',
      'virtualPageURL':'/subscribe/lightbox-impression/ecommerce-strategy',
      'virtualPageTitle':'Want To Get Ahead In ECommerce Strategy'
});
</script>

**Comment by uptownhr** [comment]
I don't use google tag manager but use segment.io. Here's my implementation, should be very similar for tag manager.

```
import bam from '../lib/bam'
import store from '~store'

if (process.BROWSER_BUILD) {
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load(process.env.segment);
  }}();

  var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+`cdn.optimizely.com/js/${process.env.optimize}.js`;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)

  window.onNuxtReady((app) => {
    bam.identify(store.state.current_user)
    analytics.page();
    app.$nuxt.$on('routeChanged', (to, from) => {
      analytics.page(to.name, { path: to.fullPath, referrer: `${window.location.origin}${from.fullPath}`} )
    })
  })
}
```

**Comment by Camzilla** [comment]
For the error you get in the console: Was having the same issue caused by the iframe in the noscript tag, had to solve it like this:

```
<template>
  <noscript v-html="gtm"></noscript>
</template>
<script>
  export default {
    data () {
      return {
        gtm: '<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-55GFMS" height="0" width="0" style="display:none;visibility:hidden"></iframe>',
      };
    }
  }
</script>
```

Not sure if its a bug or not that the iframe was being interpreted as a string without this

**Comment by shyamchandranmec** [comment]
@Camzilla The iframe gets rendered inside double quotes. I found that v-html works only with span or div. When I add a div with v-html it again shows the same error.

@Atinux Please help..
