### ISSUE TITLE
Memory leak when using context.app in Nuxt plugin

### ISSUE THREAD

**Issue by artlomako** [nuxt/nuxt.js#6749]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/artlomako/nuxt-memleak-repro](https://github.com/artlomako/nuxt-memleak-repro)

### Steps to reproduce

* clone repository
* follow README instructions

### What is expected ?

Application should run normally and Garbage Collector should remove unused references

### What is actually happening?

Application crashes with Out of memory error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10069">#c10069</a>)</em></sub></div>

**Comment by hamideslami32** [comment]
same issue

**Comment by invisor** [comment]
The same issue

**Comment by manniL** [comment]
Hey 👋 
Thanks for the detailed reproduction.

These are two excellent examples for introducing a memory leak.
I *think* the reason is because of duplicate registrations (per request) of the mixin, which creates the leak. You can use a flag to prevent this behavior.

Example:

```js
import Vue from "vue";

const directivesPlugin = ctx => {
  if(Vue.__hasMountedHeadDirective__) {
    return
  }

  Vue.__hasMountedHeadDirective__ = true
  Vue.mixin({
    mounted() {
      if (ctx.app.head.title) {
      }
    }
  });
};
export default directivesPlugin;

Related: https://github.com/vuejs/vue/issues/5089
