### ISSUE TITLE
Help needed: Nuxt and vue-dropzone

### ISSUE THREAD

**Issue by MarcMagnin** [nuxt/nuxt.js#675]
Hi,

Thanks for that awesome framework.
I would like to use it with nuxt but within my current setup build is ok but I got nothing rendered for the dropzone (size 0x0 even if I set a size).
I'm pretty new to nuxtjs (and Vue).
Here is my setup:

`nuxt.config.js:`
```javascript 
module.exports = {
  head: {
    title: 'test',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto' },
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/icon?family=Material+Icons' }
    ]
  },
  plugins: [
    { src: '~plugins/vue-dropzone.js', ssr: false },
  ]
 }
```

`plugins/vue-dropzone.js`
```javascript 
import Dropzone from 'vue2-dropzone'
import Vue from 'vue'

Vue.use(Dropzone)
```

`pages/index.vue`
```javascript 
<template>
  <div id="app">
    <p>Welcome to your Vue.js app!</p>

    <dropzone id="myVueDropzone"  width="200px" height="80px" url="https://httpbin.org/post" v-on:vdropzone-success="showSuccess">
        <!-- Optional parameters if any! -->
        <input type="hidden" name="token" value="xxx">
    </dropzone>

  </div>
</template>

<script>
 

  export default {
    name: 'MainApp',
    methods: {
      'showSuccess': function (file) {
        console.log('A file was successfully uploaded')
      }
    },
  }
</script>
```

Thanks for the help!

**Comment by Atinux** [comment]
Hi @MarcMagnin 

Sorry for the late answer.

Actually this module is not SSR compatible, which is problematic to make it work, even with `ssr: false` it's problematic.

**Comment by finalight** [comment]
does this issue still persist? if so, are there any other libraries for file upload?

**Comment by pi0** [comment]
@finalight You may check https://github.com/bootstrap-vue/bootstrap-vue/blob/master/lib/components/form-file.vue from bootstrap-vue which is supporting drag and drop too for your implementation's reference :)
