### ISSUE TITLE
Nuxt PageSpeed Insignts too low on mobile

### ISSUE THREAD

**Issue by biyongniels** [nuxt/nuxt.js#6751]
Hello, 
I have some nuxt.configuration.js optimization issues. My pagespeed is to low on mobile (28) against desktop (75). For the record the mobile scrore was at 0 at the beginning 
I try all the recommendation by 

- lazy loading images
- code splitting components
- preconnect thrid-party ...

Nothing in the end can some one help me by taking a look on my file ?

`const pkg = require("./package")
import webpack from 'webpack'
import { version } from './package.json'
import shrinkRay from 'shrink-ray-current'

const HtmlWebpackPlugin = require('html-webpack-plugin')
const HtmlWebpackPreconnectPlugin = require('html-webpack-preconnect-plugin')
const InlineSourcePlugin = require('html-webpack-inline-source-plugin')
const {GenerateSW} = require('workbox-webpack-plugin')
const ClosurePlugin = require('closure-webpack-plugin')
const ManifestPlugin = require('webpack-manifest-plugin')

const isDev = (process.env.NODE_ENV !== 'production')

require('dotenv').config()

module.exports = {
	mode: 'spa',
	dev: isDev,
	entry: {
		home: './src/Home/index.js'
	},
	loading: '~/components/loading.vue',
	head: {
		title: 'Estimation de votre véhicule avec Renault – Vente de voiture – Côte & Inspection gratuite',
		meta: [
			{ charset: 'utf-8' },
			{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
			{ hid: 'description', name: 'description', content: pkg.description }
		],
		link: [
			{ rel: 'icon', type: 'image/x-icon', href: '/favicon.png' },
			{ rel: 'preconnect', href: '//www.googletagmanager.com', crossorigin: 'crossorigin' },
			{ rel: 'preconnect', href: '//bat.bing.com', crossorigin: 'crossorigin' },
			{ rel: 'preconnect', href: '//8sdeuiavcr-1.algolianet.com', crossorigin: 'crossorigin' },
			{ rel: 'preconnect', href: '//renault-sellyourcar-536324.c.cdn77.org', crossorigin: 'crossorigin' }

		]
	},
	render: {
		compressor: shrinkRay()
	},
	modules: [
		[
			"nuxt-compress",
			{
				gzip: {
					cache: true
				},
				brotli: {
					threshold: 10240
				}
			}
		],
		'@nuxtjs/axios',
		[
			'nuxt-vuex-localstorage',
			{
				sessionStorage: ['customer', 'vehicle', 'inspector', 'quotation', 'deliveries', 'warranties', 'transactionBuyer', 'credit']
			}
		],
		[
			'@nuxtjs/moment',
			{
				locales: ['fr'],
				defaultLocale: 'fr'
			}
		],
	    [
	      '@nuxtjs/dotenv',
		    {
			    filename: '.env'
		    }
	    ],
		['@nuxtjs/component-cache', {
			max: 10000,
			maxAge: 1000 * 60 * 60
		}],
		'bootstrap-vue/nuxt',
		'vue-scrollto/nuxt'
	],
	optimization: {
		nodeEnv: 'production',
		minimize: true,
		minimizer: [
			new ClosurePlugin({mode: 'STANDARD'}, {
				debug: isDev,
				// compiler flags here
				//
				// for debuging help, try these:
				//
				// formatting: 'PRETTY_PRINT'
				// renaming: false
			})
		],
		runtimeChunk: true,
		concatenateModules: !isDev,
		splitChunks: {
			chunks: 'all'
		}
	},

	plugins: [
	  '~plugins/vue-instantsearch',
		'~/plugins/google-maps',
		'~/plugins/google-tag-manager',
		'~plugins/autocomplete',
		'~plugins/dataLayer',
	  {
	  	src: '~plugins/vee-validate.js',
		  ssr: false
	  },
	  {
	  	src: '~plugins/vue-lazyload.js',
		  ssr: false
	  },
	  {
	  	src: '~plugins/vue-lazyload-video.js',
		  ssr: false
	  }
	],
	router: {
		middleware: 'redirect'
	},
	build: {
		cache: !isDev,
		devtools: isDev,
		hardSource: !isDev,
		parallel: true,
		terser: true,
		filenames: {
			index: ({ isDev }) => isDev ? '[name].js' : 'index/[chunkhash].js',
			appraisal: ({ isDev }) => isDev ? '[name].js' : 'appraisal/[chunkhash].js',
			cancel: ({ isDev }) => isDev ? '[name].js' : 'cancel/[chunkhash].js',
			error: ({ isDev }) => isDev ? '[name].js' : 'error/[chunkhash].js',
			informations: ({ isDev }) => isDev ? '[name].js' : 'informations/[chunkhash].js',
			reservation: ({ isDev }) => isDev ? '[name].js' : 'resume/[chunkhash].js',
			resume: ({ isDev }) => isDev ? '[name].js' : 'valuation/[chunkhash].js',
			valuation: ({ isDev }) => isDev ? '[name].js' : '[chunkhash].js',
			css: ({ isDev }) => isDev ? '[name].css' : '[contenthash].css',
			img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[hash:7].[ext]',
			font: ({ isDev }) => isDev ? '[path][name].[ext]' : 'fonts/[hash:7].[ext]',
			video: ({ isDev }) => isDev ? '[path][name].[ext]' : 'videos/[hash:7].[ext]',
			chunk: ({ isDev }) => isDev ? '[name].js' : '[id].[chunkhash].js'
		},
		html: {
			minify: {
				collapseBooleanAttributes: true,
				decodeEntities: true,
				minifyCSS: true,
				minifyJS: true,
				processConditionalComments: true,
				removeEmptyAttributes: true,
				removeRedundantAttributes: true,
				trimCustomFragments: true,
				useShortDoctype: true
			}
		},
		//publicPath: process.env.CDN_PATH,
		splitChunks: {
			layouts: false,
			pages: true,
			commons: true
		},
		transpile: [/^vue2-google-maps($|\/)/, 'nuxt-vuex-localstorage'],
		plugins: [
			new webpack.DefinePlugin({
				'process.VERSION': version
			}),
			new webpack.ProvidePlugin({
				'$': 'jquery',
				'jQuery': 'jquery',
			}),
			new HtmlWebpackPlugin({
				// Inline all files which names start with “runtime~” and end with “.js”.
				// That’s the default naming of runtime chunks
				inlineSource: 'runtime~.+\\.js',
			}),
			// This plugin enables the “inlineSource” option
			new InlineSourcePlugin(),
			new HtmlWebpackPreconnectPlugin(),
			new GenerateSW(),
			new ManifestPlugin()
		],
		extend(config, { isDev, isClient }) {
			
			if (isDev) {
				config.devtool = '#source-map';
			}
			if (isDev && isClient) {
				config.module.rules.push({
					enforce: 'pre',
					test: /\.(js|vue)$/,
					loader: 'eslint-loader',
					exclude: /(node_modules)/,
				});
			}
			if (config.optimization.splitChunks && typeof config.optimization.splitChunks === 'object') {
				config.optimization.splitChunks.maxSize = 200000;
			}
			const vueLoader = config.module.rules.find(rule => rule.loader === 'vue-loader')
			vueLoader.options.transformAssetUrls = {
				video: ['src', 'poster'],
				source: 'src',
				img: 'src',
				image: 'xlink:href',
				link: 'href',
				use: ['xlink:href', 'href'],
				'v-lazy-image': ['src', 'srcset'],
				'LazyVideo': ['src', 'poster']
			}
			config.module.rules.forEach(rule => {
				if (String(rule.test) === String(/\.(png|jpe?g|gif|svg|webp)$/)) {
					// add a second loader when loading images
					rule.use.push({
						loader: 'image-webpack-loader',
						// This will apply the loader before the other ones
						enforce: 'pre'
					})
				}
				if (String(rule.test) === String(/\.css$/)) {
					// add a second loader when loading images
					rule.use.push({
						loader: 'style-loader',
						options: {
							minimize: true
						}
					})
				}
				if (String(rule.test) === String(/\.(jpe?g|png|gif)$/)) {
					// add a second loader when loading images
					rule.use.push({
						loader: 'url-loader',
						options: {
							// Inline files smaller than 10 kB (10240 bytes)
							limit: 10 * 1024,
						}
					})
				}
				if (String(rule.test) === String(/\.svg$/)) {
					// add a second loader when loading images
					rule.use.push({
						loader: 'svg-url-loader',
						options: {
							// Inline files smaller than 10 kB (10240 bytes)
							limit: 10 * 1024,
							// Remove the quotes from the url
							// (they’re unnecessary in most cases)
							noquotes: true,
						}
					})
				}
			})
	    }
	}
};
`

**Comment by JuanxCursed** [comment]
+1 same problem here, it's have been really hard to get good results in pagespeed

**Comment by Shinseiten** [comment]
+1
would like to follow the issue

**Comment by everyx** [comment]
+1, Do we have best practices for this?

**Comment by jetaix** [comment]
+1 🙏🏻

**Comment by rnenjoy** [comment]
+1

**Comment by LOG-TAG** [comment]
Is any fix available?

**Comment by torgheh** [comment]
I have the same issue and I spent hours and hours on better practices but my website still has a very low score, which I am guessing is caused mostly by the long "Script Evaluation".

**Comment by moneymc** [comment]
Same issue after pagespeed updating.

**Comment by pmartin-webimpacto** [comment]
+1

**Comment by redahead** [comment]
Since loading times (especially on mobile devices) have a very high priority nowadays, it is an absolute must!

**Comment by denis-ilchishin** [comment]
+1

**Comment by sergeypavlenko** [comment]
+!

**Comment by kc980602** [comment]
<><
Do you think AMP is your solution?

**Comment by JuanxCursed** [comment]
> Do you think AMP is your solution?

If your project can have, sure is a good replacement, in my case must is has not features enough =/

**Comment by sergeypavlenko** [comment]
Hi

Maybe best way is fix this problem ? I think for desktop, page not collect from JS, but for mobile ( even I using SSR ), page everytime collect from JS.

**Comment by VadimCeretean** [comment]
so do you solved this problem?

**Comment by filipwronski** [comment]
+1

**Comment by rlalak** [comment]
+1

**Comment by wusongliang** [comment]
?+1

**Comment by stanlystark** [comment]
+1

**Comment by riderx** [comment]
👍

**Comment by Sletheren** [comment]
+1

**Comment by StephanGerbeth** [comment]
Perhaps this module will help you to improve your performance issues.

https://github.com/GrabarzUndPartner/nuxt-speedkit

**Features**

- dynamic loading of viewport based page resources like fonts (subselectors, media queries), components, pictures
- optional loading prevention of resources at low bandwidth or weak hardware
- prevents the loading of unnecessary resources (including components) that are outside the current viewport.
- optional info layer concept to inform users about a reduced UX when bandwidth or hardware is compromised.

**Result**

- delivery of the minimum required resources based on the current viewport.
- lighthouse performance score of 100/100 (also on larger pages)

We are looking forward to the feedback.

**Comment by vinamgithub** [comment]
What is the solution for this issue???
Is this speed kit helps???

**Comment by StephanGerbeth** [comment]
Try nuxt-speedkit. 
https://github.com/GrabarzUndPartner/nuxt-speedkit

We have written a complete documentation and in the demos and examples you can see that the optimizations works correctly. On our own sites we get best performance values (demos)

**Comment by StephanGerbeth** [comment]
The FCP value is still quite high. Do you deliver your website via HTTP2? Normally the FCP should show a value of max. 1 second.

Regarding LCP: If values cannot be determined, e.g. because your website is initially white, you can generate such errors. 

A more detailed analysis is not possible via screenshot ;)

**Comment by StephanGerbeth** [comment]
Try not to trigger the animation by javascript. We prevent loading javascript on weak hardware (e.g. Moto 4g) because it is not sensibel to load the full javascript package when there are not enough hardware resources to execute it in a performant way.

**Comment by elcferreira** [comment]
> Try not to trigger the animation by javascript. We prevent loading javascript on weak hardware (e.g. Moto 4g) because it is not sensibel to load the full javascript package when there are not enough hardware resources to execute it in a performant way.

Thank you for this insight, I will refactor these animations to no being triggered by javascript.

😃

**Comment by baolong0204** [comment]
> Try nuxt-speedkit. https://github.com/GrabarzUndPartner/nuxt-speedkit
> 
> We have written a complete documentation and in the demos and examples you can see that the optimizations works correctly. On our own sites we get best performance values (demos)

Hi, I'm currently using nuxt-speedkit module in my project, but it doesn't work and somehow make the Lighthouse performance worse(it's already low to begin with). I followed the docs and wonder if I had done something wrong?

![image_2022-08-08_103725917](https://user-images.githubusercontent.com/71957156/183333501-958b56c7-6486-4a20-9485-cff4df2a0a38.png)

**Comment by StephanGerbeth** [comment]
Hi @baolong0204,

I can't judge that from the Lighthouse screenshot. Your low score may be due to a very slow server or you are loading extremely large javascript libraries in the base template that nuxt-speedkit does not manage.

Can you record the performance in Google Chrome and share the recording here?

PS: You don't measure the performance of your dev environment? Because this would give such values.
