### ISSUE TITLE
nuxt generate: CSS not included in head

### ISSUE THREAD

**Issue by lights0123** [nuxt/nuxt.js#6753]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/lights0123/nuxt-css-issue](https://github.com/lights0123/nuxt-css-issue)

### Steps to reproduce

`yarn && yarn run generate`

Then view `dist/index.html`, such as via `npx serve dist`

### What is expected ?

The included CSS, `assets/test.css`, should be inlined into the page as a `<style>` element when generated into a static page, instead of being added by JS later.

### What is actually happening?

Only CSS defined in a local `<style>` element is inlined. If Javascript is disabled, then this CSS never gets loaded, as it requires JS to include in the page. As per https://nuxtjs.org/faq/css-flash,

> the CSS is separated and put in the header so this flash of unstyled content does not appear anymore

**However**, repeating this in a layout (i.e. putting `import '~/assets/test.css';` in `layouts/default.vue`) works successfully, and the CSS is included in the generated HTML file.

### Additional comments?

I remember this working fine a few months ago in a project I was working on. I changed a few things around, though, and this bug appeared.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10072">#c10072</a>)</em></sub></div>

**Comment by lights0123** [comment]
This issue still exists in Nuxt 2.11.0.

**Comment by mathieutu** [comment]
Have the same problem...

**Comment by wargt** [comment]
I have this problem!! please help

**Comment by harvanchik** [comment]
Same problem.  Anyone here find a fix?

**Comment by laurensV** [comment]
This also causes an annoying flash of unstyled css before the css gets loaded in by javascript, hope this gets fixed soon, problem is still there with version rc12
