### ISSUE TITLE
core-js is added to moddern bundle

### ISSUE THREAD

**Issue by filrak** [nuxt/nuxt.js#6758]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/divanteltd/next](https://github.com/divanteltd/next)

### Steps to reproduce

1. Install deps with yarn 
2. Build lerna deps with yarn build:ct:tools
3. Build nuxt with analyzer cd packages/commercetools/theme && npx nuxt build -a -m

### What is expected ?

core-js is not in modern bundle

### What is actually happening?

core-js is in modern bundle

### Additional comments?

I need to add corejs manually, otherwise my client build fails ( https://github.com/nuxt/nuxt.js/issues/5287 )

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10079">#c10079</a>)</em></sub></div>

**Comment by thebspin** [comment]
Having the same issue on my deployment server..., even adding core-js manually won't work for me.
