### ISSUE TITLE
SSR only serves static page, never hydrates in IE11.

### ISSUE THREAD

**Issue by peitalin** [nuxt/nuxt.js#676]
I'm running a basic nuxt.js website, works perfect on Chrome, Safari, Firefox and Edge.
One issue:
On IE11, it seems to only serve the static page, and the javascript bundle never hydrates the static page.

Any insight into how I might get around this issue?
Should I look into generating a static site or???

**Comment by sebastianmacias** [comment]
How did you solve the issue?

**Comment by peitalin** [comment]
I convinced my boss that we didn't have to support ie11.

**Comment by peitalin** [comment]
I don't think this is a SSR issue.
The reason is because I tried generating a static bundle and serving the site with a koa server.
The same thing happened: index.html loads on IE11, but the javascript bundles were not being loaded.
My guess is that there is something in the _nuxt/nuxt.bundle.js files that IE11 doesn't like.

**Comment by nathanchase** [comment]
Maybe IE is in need of a polyfill? Probably [Map/WeakMap](https://github.com/zloirock/core-js), [MutationObserver](https://www.npmjs.com/package/mutationobserver-shim), [requestAnimationFrame](https://github.com/chrisdickinson/raf), or [Promises](https://github.com/zloirock/core-js).

I know when I was trying to get Aurelia building/executing in various permutations of IE, those were the culprits, so I imagine it might be the same in Vue.

**Comment by max-schu** [comment]
i reckon you use babel-polyfill together with useBuiltIns option in babel preset – it's not a nuxt issue.

**Comment by NicoPennec** [comment]
Vuex need a polyfill for Promises on IE11...

Check the following IE11 trace error, on <nuxt-link> click:

![nuxtjs-vuex-error-ie-11](https://cloud.githubusercontent.com/assets/493223/26034160/85baa9be-38b8-11e7-8d67-2839b5a62dfa.jpg)

**Comment by peitalin** [comment]
Yes, it was a polyfill issue. Adding in:
```
  build: {
    vendor: [
      'babel-polyfill'
    ],
    babel: {
      plugins: [
          ...
      ]
    },
  },
``` 
to my `nuxt.config.js` file, and adding `require("babel-polyfill");` to layout/default.vue resolves this issue.
