### ISSUE TITLE
Nuxt is removing the content created with a script inside an html string passed with v-html

### ISSUE THREAD

**Issue by yekta** [nuxt/nuxt.js#6763]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://appditto/blog/automate-your-flutter-workflow](https://appditto/blog/automate-your-flutter-workflow)

### Steps to reproduce

You can visit the link I provided, go to the "Contents of flutter_build.sh:" part, reload the page. You will see the GitHub gist appearing there for a split second, then it'll disappear. I'm using Ghost CMS, getting an html in string form from their api, passing it to a Nuxt component with v-html directive. Everything else works properly, but the <script> tags don't get executed properly, not for long anyways. The content created with those scripts disappear after a split second.

### What is expected ?

I expect the GitHub gist, or any other embed created with a script (Twitter, Instagram etc.) to display properly without disappearing.

### What is actually happening?

The GitHub gist disappears after about 0.3-0.5 seconds from the initial load of the page.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10090">#c10090</a>)</em></sub></div>

**Comment by aldarund** [comment]
It work as expected, not a bug. You cant execute script via v-html after page is loaded, because browser blocks it https://stackoverflow.com/a/44596352/239354
And it happens during rehydrating, so nothing will be ouput

**Comment by goldfire** [comment]
@yekta Did you find a solution that allowed you to have these embeds? I'm running into the same issue and not seeing any good options to get that working.
