### ISSUE TITLE
Why does the _uid is diff from 'for' attribute _uid value in label  in the same component when reload the window?

### ISSUE THREAD

**Issue by akenhu4444** [nuxt/nuxt.js#6766]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codesandbox.io/s/youthful-hofstadter-5is4o?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/youthful-hofstadter-5is4o?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

- reload window

### What is expected ?

get same _uid in input ID and label 'for' attribute value

### What is actually happening?

label 'for' attribute value is different with _uid in this component when  i reload window

### Additional comments?

index.vue

```
<template>
  <div class="container">
    <Test></Test>
  </div>
</template>

<script>
import Test from "~/components/Test.vue";
export default {
  components: {
    Test: Test
  }
};
</script>
```

---

Test.vue

```
<template>
  <div>
    <style>
      div {
        text-align: left;
        margin: 8px 0;
      }
    </style>
    <div id="a">
      <label :for="uuid">label_uuid: {{_uid}}</label>
      <input type="radio" :id="uuid" :value="_uid">
      <br>
      <span><</span>
      label for="{{label_uuid_for_value}}"
      <span>/></span>
    </div>
    <hr>
    <div id="b">
      <label :for="random">label_random: {{random}}</label>
      <input type="radio" :id="random" :value="random">
      <br>
      <span><</span>
      label for="{{label_random_for_value}}"
      <span>/></span>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      random: "",
      uuid: "",
      label_uuid_for_value: "",
      label_random_for_value: ""
    };
  },
  created() {
    this.uuid = this._uid;
    this.random = this.$random(10000, 99999);
  },
  mounted() {
    this.label_uuid_for_value = document
      .querySelector("#a label")
      .getAttribute("for");
    this.label_random_for_value = document
      .querySelector("#b label")
      .getAttribute("for");
  },
  methods: {
    $random(min, max) {
      return Math.floor(Math.random() * (max - min)) + min;
    }
  }
};
</script>
```

---

layout

```
<div>
 <div id="a">
    <label for="59">label_uuid: 9</label>
    <input type="radio" id="9" value="9"> 
    <br> 
   <span>&lt;</span> label for="59"<span>/&gt;</span>
</div> 
<hr> 
<div id="b">
   <label for="64275">label_random: 44530</label>
    <input type="radio" id="44530" value="44530">
    <br> 
   <span>&lt;</span>label for="64275"<span>/&gt;</span>
</div>
</div>
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10094">#c10094</a>)</em></sub></div>

**Comment by aldarund** [comment]
Your value should be same on client and server e.g. the values that are generated in mounted. In your case they are different and that will lead to such behaviour. If u want to use random values change them in mounted, not created

**Comment by akenhu4444** [comment]
Thanks, mounted is works! !! But only the tag "for" attribute has a problem, that's weird.

If this's done only in mounted, will it affect SEO?

**Comment by aldarund** [comment]
if its done in mounted it will be changed only on client so it wont be in server generated html
