### ISSUE TITLE
beforeDestroy is not called when ssr

### ISSUE THREAD

**Issue by IncSW** [nuxt/nuxt.js#677]

**Comment by Atinux** [comment]
@IncSW please fork this example https://glitch.com/edit/#!/project/nuxt-hello-world and produce a reproduction so we can work on this.

**Comment by IncSW** [comment]
https://glitch.com/edit/#!/flawless-thief

**Comment by Atinux** [comment]
Hi @IncSW 

I will take a look at it thank you.

**Comment by Atinux** [comment]
For now I think it’s necessary to avoid doing this kind of “lingering side effects” in created hooks during SSR. Logically this kind of stuff should only happen on the client anyway, so check `this.$isServer` before doing this @IncSW 

Or use the beforeMount hook @IncSW
