### ISSUE TITLE
production build does not fail with JS or CSS error

### ISSUE THREAD

**Issue by andreynazarov3** [nuxt/nuxt.js#6774]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/andreynazarov3/nuxt-build-bug](https://github.com/andreynazarov3/nuxt-build-bug)

### Steps to reproduce

Add some JS error to vue file, like unused variable to one of component.
Config to fail on build is there in nuxt.config as this:
```
[
      '@nuxtjs/eslint-module',
      {
        failOnWarning: true,
        failOnError: true,
        emitError: true
      }
    ],
```
Try to build and see that build is successfull.

### What is expected ?

Build expected to fail showing eslint error.

### What is actually happening?

Build is successfull.

The same thing is also for stylelint errors.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10103">#c10103</a>)</em></sub></div>

**Comment by aldarund** [comment]
Open issue in eslint module repo, not here https://github.com/nuxt-community/eslint-module/issues
