### ISSUE TITLE
Nuxt-link to index path "/" not working on error.vue page when already on index page

### ISSUE THREAD

**Issue by AdamBD** [nuxt/nuxt.js#6778]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[http://www.test.com](http://www.test.com)

### Steps to reproduce

1. Create an Axios call which takes place on the index page, and ensure this call returns any code in the 400/500 range.
2. Use the sample error.vue page provided in the nuxt documentation, which has the default nuxt-link back to the index page "/"
3. When the axios call returns with a http code in the 400/500 range the error.vue page will be loaded. 
4. When you try to use the nuxt-link however to 'reload' the index page component, it wont load, presumably because you're already on the "/" path. But this is weird behavior. It should be able to reload the index page component

### What is expected ?

That the index page component would reload 

### What is actually happening?

The index page component simply doesnt reload

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10105">#c10105</a>)</em></sub></div>

**Comment by ocBruno** [comment]
As a temporary workaround you can use @click="$router.go()" to reload the page, I have a reproducible branch of this issue if anyone wants to try to look better into this.

https://github.com/ocBruno/nuxt.js/tree/fix/reload-error

**Comment by ankitarora05** [comment]
https://gamecom.app/

I created a website on nuxt and server render. Any thoughts?

FYI you have to login to enjoy the feed :-p

**Comment by AdamBD** [comment]
This is still an issue. Has anyone from the core team reviewed this report yet?
