### ISSUE TITLE
Memory leak still exists

### ISSUE THREAD

**Issue by yi-ge** [nuxt/nuxt.js#678]
@Atinux Please have a look. https://github.com/nuxt/nuxt.js/issues/658

**Comment by ausir0726** [comment]
I am interested why you closed it.
thanks

**Comment by yi-ge** [comment]
@ausir0726 I decided to solve the problem by myself.I may be PR.

**Comment by yi-ge** [comment]
Studied for a long time, could not solve.

**Comment by Atinux** [comment]
We will see with the upcoming release if this issue is still open.

**Comment by yajam** [comment]
On Ubuntu VM on GCP with PM2 memory leak exists leading to application crash. Is this being addressed?

**Comment by pi0** [comment]
Please see #805 if still having problem and wish to help others resoling memory leaks :)
