### ISSUE TITLE
新建nuxt2.0模板，引入@nuxt/axios 执行 docker 报错

### ISSUE THREAD

**Issue by ddyh0826** [nuxt/nuxt.js#6785]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://xxx.com](https://xxx.com)

### Steps to reproduce

新建nuxt2.0模板，引入nuxt.config.js  modules: ['@nuxt/axios'] 执行 docker 报错

### What is expected ?

如下

### What is actually happening?

 FATAL  Cannot find module '@nuxtjs/axios'
Require stack:
- /app/node_modules/@nuxt/core/dist/core.js
- /app/node_modules/@nuxt/cli/dist/cli-command.js
- /app/node_modules/@nuxt/cli/dist/cli.js
- /app/node_modules/nuxt/bin/nuxt.js

### Additional comments?

Dockerfile

FROM node:10.15.3
MAINTAINER walker
ENV NODE_ENV=production
ENV HOST 0.0.0.0
RUN mkdir -p /app
COPY . /app
WORKDIR /app
EXPOSE 3000
RUN npm config set registry https://registry.npm.taobao.org
RUN npm install
RUN npm run build
CMD ["npm", "start"]

_________________________________ Error  ___________________________________

> web_mobile@1.0.0 build /app
> nuxt build

 FATAL  Cannot find module '@nuxtjs/axios'
Require stack:
- /app/node_modules/@nuxt/core/dist/core.js
- /app/node_modules/@nuxt/cli/dist/cli-command.js
- /app/node_modules/@nuxt/cli/dist/cli.js
- /app/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module '@nuxtjs/axios'
  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-command.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:569:31)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:164:36)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1802:43)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)

tput: No value for $TERM and no -T specified

   ╭───────────────────────────────────────────────────────╮
   │                                                       │
   │   ✖ Nuxt Fatal Error                                  │
   │                                                       │
   │   Error: Cannot find module '@nuxtjs/axios'           │
   │   Require stack:                                      │
   │   - /app/node_modules/@nuxt/core/dist/core.js         │
   │   - /app/node_modules/@nuxt/cli/dist/cli-command.js   │
   │   - /app/node_modules/@nuxt/cli/dist/cli.js           │
   │   - /app/node_modules/nuxt/bin/nuxt.js                │
   │                                                       │
   ╰───────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web_mobile@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web_mobile@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10119">#c10119</a>)</em></sub></div>

**Comment by yasminzy** [comment]
What is the solution? I have a similar issue -> cannot find module 'vuex/package.json' with require stack list like that.
