### ISSUE TITLE
Adding content to head programmatically leads to duplicates after each request

### ISSUE THREAD

**Issue by sowinski** [nuxt/nuxt.js#6786]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/sowinski/nuxtheadbug](https://github.com/sowinski/nuxtheadbug)

### Steps to reproduce

I already described the problem here: https://stackoverflow.com/questions/59300315/nuxt-how-to-add-content-scripts-to-the-head-dynamically-on-server-side

You can see this behavior only in production mode. In Development it is not happening!

I also tried to build this problem within a codesendbox, but unfortunately it is not visible there.

### What is expected ?

For each request the content of the head should be rested and not stored.

### What is actually happening?

The content of the head area is stored on server side. Each request just adds the new content to the head and also keep the last one.

=> memory leak

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10120">#c10120</a>)</em></sub></div>

**Comment by Atinux** [comment]
I can confirm the issue, PR to fix it: https://github.com/nuxt/nuxt.js/pull/6807

Thank you for the reproduction @sowinski
