### ISSUE TITLE
Changing image bundle filenames doesn't work

### ISSUE THREAD

**Issue by wiadev** [nuxt/nuxt.js#6787]
### Version

[2.9.2](https://github.com/nuxt.js/releases/tag/2.9.2)

### Reproduction link

[https://nuxtjs.org/api/configuration-build/#filenames](https://nuxtjs.org/api/configuration-build/#filenames)

### Steps to reproduce

https://nuxtjs.org/api/configuration-build/[#c59](https://cmty.app/nuxt/nuxt.js/issues/c59 "nuxt.js - Dash in layout filenames") 

filenames: {
      chunk: ({ isDev }) => isDev ? '[name].js' : '[id].[chunkhash].js',
      img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[name].[ext]'
 },

chunk file names as updated but not img file names.

Thanks.

### What is expected ?

The img bundle filenames should be updated

### What is actually happening?

It's not updated

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10121">#c10121</a>)</em></sub></div>

**Comment by pimlie** [comment]
Please upgrade to nuxt 2.11 and create a reproduction if it still doesnt work.

Was just working with this yesterday and it worked perfectly fine for me :)
