### ISSUE TITLE
Idea/Suggestion: Nuxt CLI command for generating pages/components

### ISSUE THREAD

**Issue by samtgarson** [nuxt/nuxt.js#679]
This is just an idea to see what the team behind Nuxt think (not sure if this is the best place for it):

It could be really convenient to add an extra command to the `nuxt` cli tool to generate new pages/components? I find myself doing this a lot and at the moment it's basically copying and pasting the `script`, `template` and `style` tags from another file and emptying it out. It could also take preferences about languages (pug, sass, etc), and even layouts and store modules, etc. E.g.:

```bash
nuxt create component my-component-name
nuxt create page my-page-name --sass
```

Would you be open to reviewing a PR to implement this, or do you think it's not appropriate to go into this project?

**Comment by qm3ster** [comment]
It looks like a job for the editor.  For example https://atom.io/packages/language-vue
allows inserting this snippet:
```vue
<template lang="html">
  
</template>

<script>
export default {
}
</script>

<style lang="css">
</style>
```
when the grammar is vue. The snippet selects 'html' so you can replace it.
https://github.com/hedefalk/atom-vue/blob/master/snippets/vue.cson

**Comment by ausir0726** [comment]
I also think it just need write a snippet ...

**Comment by samtgarson** [comment]
Fair enough. I thought there could be a chance to implement something more powerful and useful than what snippets usually gives you, but you're probably right.

**Comment by Atinux** [comment]
Since `nuxt`module should not be installed globally, we cannot add this feature.

But if someone wants to add a plugin for Atom/Visual Studio/SublimeText for Nuxt, it would be awesome!

**Comment by samtgarson** [comment]
@Atinux noticed you've begun work on this https://github.com/nuxt/nuxt-cli 😊 Please let me know if you need any extra hands on that, I'd love to help create a top notch CLI experience for nuxt

**Comment by qm3ster** [comment]
Yay, modules are getting broken out :dark_sunglasses:

**Comment by pi0** [comment]
@samtgarson Thanks for your interest. We love adding `nuxt page <cmd>` and other creators to Nuxt-CLI too. Also it would be also possible extending global nuxt-cli per project basis by using modules. Some approach like Laravel's [Artisan](https://github.com/laravel/laravel/blob/master/artisan). Entry js (Either global or local) detects project root, boots up nuxt kernel and waits for modules ready to possibly provide more commands :)
