### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by arthuribik** [nuxt/nuxt.js#6794]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[http://jsfiddle.org](http://jsfiddle.org)

### Steps to reproduce

I have a working nuxt project that is runs on version ^2.7.1 and when I migrated same project that was working fine to a new server, it pulled version ^2.10.2. 

I started debugging my entire large project thinking that maybe the new version does not support window object. I pulled a fresh v2.10.2 and tried transferring component, feature and module one at a time.

I got to some point I received same error message and for 2 days I couldn't debug the problem.

Today I decided to downgrade to v2.9.2 and everything worked as expected.

### What is expected ?

Nuxt.js v2.10.2 
Running in production mode (universal)  
Memory usage: 20.3 MB (RSS: 75.3 MB)
Listening on: http://localhost:3000/

### What is actually happening?

ERROR  window is not defined                                                                                                                    14:42:58

  at Bt (server.js:2:751747)
  at bi (server.js:2:767776)
  at async e.default (server.js:2:768783)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10127">#c10127</a>)</em></sub></div>

**Comment by Atinux** [comment]
Could you reproduce this issue with Nuxt `v2.11.0`?

**Comment by aldarund** [comment]
Its really impossible to tell anything without reproduction :(  Does it happen in dev mode? or only in production build? any page or specific? Try to remove all code till problem gone and add back once its reproduced

**Comment by ankitarora05** [comment]
https://gamecom.app/

I created a website on nuxt and server render. Any thoughts?

FYI you have to login to enjoy the feed :-p

**Comment by arthuribik** [comment]
I fixed this issues by renaming `file_name.js` to `file_name.client.js` in the plugins directory.
