### ISSUE TITLE
Vue needs update.

### ISSUE THREAD

**Issue by qodehub-nanadjei** [nuxt/nuxt.js#6796]
new update of vue-server-renderer from 2.6.10 to 2.6.11. 

Now getting error:
`UnhandledPromiseRejectionWarning:   Error: Vue packages version mismatch:
  - vue@2.6.10
  - vue-server-renderer@2.6.11`

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10128">#c10128</a>)</em></sub></div>

**Comment by gramlin** [comment]
Got the same problem.

**Comment by connecteev** [comment]
Ditto

**Comment by connecteev** [comment]
This fixed it for me:
Try deleting package-lock.json, run npm update and npm run dev again.

**Comment by craigharman** [comment]
> This fixed it for me:
> Try deleting package-lock.json, run npm update and npm run dev again.

I also had to delete node_modules folder and npm install.
