### ISSUE TITLE
Provide context Object in extendRoutes

### ISSUE THREAD

**Issue by sugoidesune** [nuxt/nuxt.js#6798]
### What problem does this feature solve?

The context Object provides many helping methods like: params, pathMatch, query. Allowing for more flexibility when redirecting.

### What does the proposed changes look like?

Simple language rerouting.
![Capture.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/5dbaba90-2081-11ea-8b97-01d0edbb55d2.PNG)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10129">#c10129</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @sugoidesune 

Sadly this is not possible since `extendRoutes` is called on nuxt runtime and not during the vue execution.

**Comment by sugoidesune** [comment]
I understand, could there be any other way to access routing properties like `pathMatch`?
