### ISSUE TITLE
Prefetch plugin data

### ISSUE THREAD

**Issue by vadimsg** [nuxt/nuxt.js#68]
I created my custom translation plugin in which I extend Vue.
```javascript
// Trans class here...

const translations = {}; // Need to fetch this json obj from server here

Vue.prototype._ = (key, params = {}) => {
  return trans.get(key, params);
};
```
How can I prefetch it so Vue can use it?
Thanks!

**Comment by Atinux** [comment]
Hi @vadimsg 

What you can do is:
```js
const translations = require('./path-to-default-lang.json');
```

This way, Webpack will put your translation object directly in your bundle.js and the `translations` variable will be filled and ready to use with Vue.

**Comment by Atinux** [comment]
Otherwise, I think the `middleware` option that will come in an upcoming release will let you fill the `translations` object from the server-side (but also from the client-side if the user change the langage).

**Comment by vadimsg** [comment]
In my situation I need to fetch it from api. 

Thanks, waiting for the release!

**Comment by Atinux** [comment]
The middleware feature is out with the [0.9.8 release](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.8).

See the example with [i18n](https://github.com/nuxt/nuxt.js/tree/master/examples/i18n).
Demo: http://i18n.nuxtjs.org/
