### ISSUE TITLE
Nuxt ignoring NODE_ENV = production?

### ISSUE THREAD

**Issue by jimmyat** [nuxt/nuxt.js#6802]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/jimmyat/nuxt-demo](https://github.com/jimmyat/nuxt-demo)

### Steps to reproduce

I'm trying to run Nuxt with Passenger on cPanel, in universal mode. Passenger takes a directive, PassengerStartupFile, which I point to `node_modules/nuxt/bin/nuxt.js`.

However, despite setting NODE_ENV to 'production', nuxt starts the development environment, not production.

I would ordinarily start the production server via CLI using `npm run start`.

Is there a way to get nuxt started in production mode using Passenger? Am i perhaps using the wrong StartupFile?

### What is expected ?

Nuxt starts server in production mode, similar to `npm run start` (nuxt start)

### What is actually happening?

Nuxt starts server in dev mode

### Additional comments?

There's some discussion about running nuxt with passenger but nothing conclusive here:

https://github.com/nuxt/nuxt.js/issues/5382
https://github.com/nuxt/nuxt.js/issues/210

The PassengerStartupFile directive reference can be found here:

https://www.phusionpassenger.com/library/config/apache/reference/#passengerstartupfile

There doesn't seem to be a way to make it take a command, or other arguments, just a file.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10133">#c10133</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @jimmyat 

You can create a `start.js` file next to your `package.json`:

```js
// start.js
require('@nuxt/cli').run(['start'])
```

And then in your `PassengerStartupFile` point to this file.
