### ISSUE TITLE
CSS variables aren't properly polyfilled

### ISSUE THREAD

**Issue by hgl** [nuxt/nuxt.js#6805]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Steps to reproduce

Use this config
 ```
export default {
  mode: 'universal',
  loading: false,
  css: [
    '~/styles/base.css'
  ],
  build: {
    extractCSS: true,
    postcss: {
      preset: {
        stage: 1,
      },
    },
  },
}
```
content of `styles/base.css`
```
:root {
  --font-size: 16px;
}

body {
  font-size: var(--font-size);
}
```

content of `pages/index.vue`
```
<template>
  <h1>Hello world</h1>
</template>

<style scoped>
h1 {
  font-size: var(--font-size);
}
</style>
```

run `npm run generate`

### What is expected ?

component css should be something like
```
h1[data-v-04b21c3c]{font-size: 16px;font-size:var(--font-size)}
```

### What is actually happening?

component css is
```
h1[data-v-04b21c3c]{font-size:var(--font-size)}
```
notice the actual value isn't inlined.

### Additional comments?

The base.css file correctly has actual values inlined.

My guess is that the component css passed through postcss without letting it see the variable definitions.

I'd like to send a PR if someone could shred some light on how to make postcss see files imported by the `css` options.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10135">#c10135</a>)</em></sub></div>

**Comment by hgl** [comment]
I have checked the source code, `options.css` files are imported in vue-app's App.js, and component css is imported with vue-loader, so they are separated. I don't think it's easy to make postcss see the variables this way?

I also tried importing base.css directly in the component
```
<template>
  <h1>Hello world</h1>
</template>

<style scoped>
@import "~/styles/base.css"
h1 {
  font-size: var(--font-size);
}
</style>
```

The problem is that `:root` will be prepend with css module id.

I also tried importing it as a global style:

```
<style>
@import "~/styles/base.css"
</style>
<style scoped>
h1 {
  font-size: var(--font-size);
}
</style>
```
But then they're separated again, and postcss couldn't polyfill correctly.

**Comment by pimlie** [comment]
Please add a working minimal reproduction on codesandbox

**Comment by hgl** [comment]
Here you go, check the style differences between body and h1

https://codesandbox.io/s/fragrant-lake-ekeco?fontsize=14&hidenavigation=1&theme=dark

**Comment by Infineight** [comment]
This same issue is discussed over at https://github.com/nuxt/nuxt.js/issues/6534

**Comment by hgl** [comment]
thanks, moving the discussion to that issue.
