### ISSUE TITLE
esm() breaks console.*() functions in esm-styled nuxt.config.js 

### ISSUE THREAD

**Issue by mpyw** [nuxt/nuxt.js#6808]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Steps to reproduce

1.Create `nuxt.config.js` like the following:

```js
export default {
  vue: {
    config: {
      errorHandler(error) {
        console.error(error);
      },
    },
  },
}
```

2.Check the compiled file: `.nuxt/client.js`

### What is expected ?

```js
Object.assign(Vue.config, {"errorHandler":function(error) {
        console.error(error);
      },"silent":false,"performance":true})
```

It should work correctly.

### What is actually happening?

```js
Object.assign(Vue.config, {"errorHandler":function(error) {
        _xxx.g.console.error(error);
      },"silent":false,"performance":true})
```

Reference error occurs at `_xxx`. It seems that the prefix originally exists as `_.g` and has been transformed into `_xxx.g` by `webpack`.

### Additional comments?

[nuxt.js/config.js at 5fa768373da1adfd8c76145b2ec95b7824af93b4 · nuxt/nuxt.js](https://github.com/nuxt/nuxt.js/blob/5fa768373da1adfd8c76145b2ec95b7824af93b4/packages/cli/src/utils/config.js#L27)

```js
options = esm(module)(nuxtConfigFile) || {}
```

I guess that the usage of `esm()` is wrong. Also there are the test that confirms prefixing global `console` and `reflect`.

[esm/compiler-tests.mjs at a3b8290074ccd2a708ed9b985a2f89d4f4cdd026 · standard-things/esm](https://github.com/standard-things/esm/blob/a3b8290074ccd2a708ed9b985a2f89d4f4cdd026/test/compiler-tests.mjs#L464-L504)

```js
it("should transform `console` references and calls with identifier arguments", () => {
  const lines = [
    "console",
    "console.a(b)",
    'console.a("b", c)',
    'console["a"](b)',
    "new console.Console(a)",
    "class C extends console.Console {}",
    "const a = { console }",
    "const a = { [console]: console }",
    "const a = { console() { console } }",
    "const a = () => console"
  ]

  const compiled = [
    "_.g.console",
    "_.g.console.a(b)",
    '_.g.console.a("b", c)',
    '_.g.console["a"](b)',
    "new _.g.console.Console(a)",
    "class C extends _.g.console.Console {}",
    "const a = { console:_.g.console }",
    "const a = { [_.g.console]: _.g.console }",
    "const a = { console() { _.g.console } }",
    "const a = () => _.g.console"
  ]

  lines.forEach((line, index) => {
    const code = [
      'import a from "a"',
      line
    ].join("\n")

    for (const sourceType of modernTypes) {
      const result = Compiler.compile(code, { sourceType })
      const actual = result.code.split("\n").pop()

      assert.strictEqual(actual, compiled[index])
    }
  })
})
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10136">#c10136</a>)</em></sub></div>

**Comment by pimlie** [comment]
This looks like an issue in `esm`. If I remove all imports from my nuxt.config it generates correctly.

Minimal reproduction:
```js
// config.es.js
import path from 'path'

export default {
  errorHandler(error) {
    console.error(error);
  }
}

// load.cjs
#!/usr/bin/env node

const esm = require('esm')

const config = require.resolve('./config.js')

console.log(esm(module)(config).default.errorHandler.toString())
```

**Comment by mpyw** [comment]
@pimlie 

> This looks like an issue in `esm`.

Did you see my explanation?

>  Also there are the test that confirms prefixing global `console` and `reflect`.

**Comment by pimlie** [comment]
@mpyw Did you see and try my reproduction?

**Comment by mpyw** [comment]
@pimlie Sure. What do you think about the tests on `esm()` repository?

**Comment by pimlie** [comment]
@mpyw How are we using `esm()` wrong according to you?

**Comment by mpyw** [comment]
It seems that we need to provide original global variables on namespace `_.g.`

**Comment by pimlie** [comment]
The esm docs doesnt seem to mention this at all? Did you find anything in the docs? Can you show that? Or is proving global vars only given in by looking at those tests?

**Comment by mpyw** [comment]
No. There is no such document anywhere. But as far as considering the tests, it's obvious that we need to do so. `esm` looks preventing global variables (undefined variables in each file) from making collisions. ...Yes, the `esm` document is so unkind for developers.

**Comment by pimlie** [comment]
Ah right, thanks now I understand.

I think the issue is that the prefix just doesnt exist after the Nuxt build. What happens is:
- load nuxt.config, esm adds global prefix
- build nuxt.js
  - esm global prefix is available
  - but nuxt [serializes](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/client.js#L46) the errorReporting function prefix into the Nuxt vue-app template
- after nuxt has been build, it executes the errorReporting method that was added to the vue-app template which still uses that esm global prefix. But as we are now running in a complete new context without esm, that prefix just doesnt exists anymore

**Comment by mpyw** [comment]
@pimlie So nice explanation, thanks!
