### ISSUE TITLE
Google Cache Links in Nuxt applications got replaceState Error and Block the Client-side Rendering

### ISSUE THREAD

**Issue by maulshh** [nuxt/nuxt.js#6812]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[http://webcache.googleusercontent.com/search?q=cache:https://www.nuxtjs.org](http://webcache.googleusercontent.com/search?q=cache:https://www.nuxtjs.org)

### Steps to reproduce

Search for cached page on google webcache which used Nuxt. Got the error and all client-side rendering got blocked. Maybe not all but API calls and stuffs regarding store will not be loaded

### What is expected ?

Page built in nuxt should be fully loaded in google webcache

### What is actually happening?

Client-side rendering is not done and got blocked by an Error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10139">#c10139</a>)</em></sub></div>

**Comment by aldarund** [comment]
Its error because it reference js file that are no longer exist. New deploy == new js files. And google cached version not the recent ones so it reference old js files that are lready delete. Nothing we could do here

**Comment by manniL** [comment]
Also, https://github.com/vuejs/vue-router/issues/2042 might be related.

**Comment by iTechSebastianoLaini** [comment]
+1 on our Nuxt 2 app
