### ISSUE TITLE
ssr-only element …perhaps

### ISSUE THREAD

**Issue by mkstix6** [nuxt/nuxt.js#6815]
### What problem does this feature solve?

Is it feasible to have a new component  `<ssr-only>` …thinking as the opposite of `<client-only>`.

A simple way to show HTML/Components on page for SEO purposes but instantly hide them when the client side hydrates (preferably faster than the user could see it).

Reason being, simple scenario:

I have a table of data that we paginate to make it a nice experience for the user. Also there is an image in each line that I don't need to present to Google.
However I'd like for Google bots to see all the text data…
…but the paginated table component doesn't construct HTML for anything after the first 25 rows.

So I could have code like:

```
<client-only>
    <FancyPaginatedTableComponent />
</client-only>
<ssr-only>
   <table>…just a regular table with data…</table>
</ssr-only>
```

Perhaps there's already a super simple way to achieve this that I haven't stumbled across in the docs yet; if so, sorry.
Or perhaps this is just a bad idea for some other reasons.

Part of me wonders if a component like this encourages bad behaviour and SEO manipulation.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10143">#c10143</a>)</em></sub></div>

**Comment by aldarund** [comment]
You can do it yourself in code. E.g. have flag mounted that will be set in mounted hook ( which is executed only on client ) and render thing based on value of mounted. Something like this
```
<div v-if="mounted">
    <FancyPaginatedTableComponent />
</div>
<div v-else>
   <table>…just a regular table with data…</table>
</div>

mounted() {
 this.mounted = trued
}
```

**Comment by mkstix6** [comment]
Thanks very much 👍. 
Will approach it the way you advise.
