### ISSUE TITLE
*.html files are not compressed when using compression-webpack-plugin with nuxt generate

### ISSUE THREAD

**Issue by mseele** [nuxt/nuxt.js#6817]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/webpack-contrib/compression-webpack-plugin/issues/142](https://github.com/webpack-contrib/compression-webpack-plugin/issues/142)

### Steps to reproduce

This is how my build section of the nuxt.config.js file looks like:

import CompressionPlugin from 'compression-webpack-plugin'

export default {
// ...
  build: {
    plugins: [
      new CompressionPlugin({
        filename: '[path].gz[query]',
        algorithm: 'gzip',
        minRatio: 1,
        test: /\.(js|css|html|svg)$/
      }),
      new CompressionPlugin({
        filename: '[path].br[query]',
        algorithm: 'brotliCompress',
        test: /\.(js|css|html|svg)$/,
        minRatio: 1,
        compressionOptions: { level: 11 }
      })
    ]
  }
}

create a helloworld nuxtjs application via https://nuxtjs.org/guide/installation/#using-code-create-nuxt-app-code- , execute npm install compression-webpack-plugin --save-dev and add the above code into nuxt.config.js.
Then run npm run generate und look what has been created in the dist folder.

For us, everything except the *.html files has been compressed as *.gz & *.br archives.

I've also opened an issue here: https://github.com/webpack-contrib/compression-webpack-plugin/issues/142
But they told me to open an issue at nuxtjs.

### What is expected ?

*.html files should be compressed in nuxt generate process with compression-webpack-plugin

### What is actually happening?

No compressed version of the *.html files is generated when running "nuxt generate". Only *.js, *.css & *.svg files in folder _nuxt are compressed. Anything outside of folder _nuxt (this is where the html files are) is not compressed.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10144">#c10144</a>)</em></sub></div>

**Comment by pimlie** [comment]
This is because the Nuxt Generator doesnt use webpack (the Nuxt Builder does). Generator uses vue-server-renderer which uses the webpack artifacts created by the Nuxt Builder (read more [here](https://ssr.vuejs.org/guide/bundle-renderer.html))

You can either use a generate hook to compress the html file after its generated or add a `postgenerate` command in your pck.json with something like `find <your-dist-folder> -type f -iname *.html -exec gzip {} \;`
