### ISSUE TITLE
Invalid head property "links" works client-side only

### ISSUE THREAD

**Issue by sergkhl** [nuxt/nuxt.js#6818]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/objective-snyder-ctbp2](https://codesandbox.io/s/objective-snyder-ctbp2)

### Steps to reproduce

Add "links" property ("link" in docs) to the head config
```
head: 
    links: [
      {
        rel: "links-prop-test",
        href: "works-clientside-only"
      }
    ]
};
```

### What is expected ?

It should not work at all or work both client and SSR as alias.

### What is actually happening?

It works on client.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10145">#c10145</a>)</em></sub></div>

**Comment by aldarund** [comment]
What do u mean by works on client? There no property links, only link. So your links dont do anything, neither on client, nor on server. 
https://i.imgur.com/gn78zq9.png
