### ISSUE TITLE
Error on generate (fn is not a function)

### ISSUE THREAD

**Issue by MattixNow** [nuxt/nuxt.js#6820]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/MattixNow/mattaio-website/tree/caea07a28f9e68f12509598bc1d558dc022f7294](https://github.com/MattixNow/mattaio-website/tree/caea07a28f9e68f12509598bc1d558dc022f7294)

### Steps to reproduce

```
yarn
yarn generate
```

### What is expected ?

Normally generate working fine

### What is actually happening?

![image_1.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/223e1e10-243e-11ea-8db4-973a0b681cc4.png)

```
 ERROR  Could not resolve routes                                                                                                                                                22:56:04  


 FATAL  fn is not a function                                                                                                                                                    22:56:04  

  at Object.promisifyRoute (node_modules\@nuxt\utils\dist\utils.js:1739:17)
  at Generator.initRoutes (node_modules\@nuxt\generator\dist\generator.js:84:38)
  at Generator.generate (node_modules\@nuxt\generator\dist\generator.js:44:31)


   ╭─────────────────────────────────────╮
   │                                     │
   │   ✖ Nuxt Fatal Error                │
   │                                     │
   │   TypeError: fn is not a function   │
   │                                     │
   ╰─────────────────────────────────────╯

error Command failed with exit code 1.
```

### Additional comments?

Maybe about routes generation, i don't found any similar issue

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10147">#c10147</a>)</em></sub></div>

**Comment by manniL** [comment]
https://github.com/MattixNow/mattaio-website/blob/caea07a28f9e68f12509598bc1d558dc022f7294/nuxt.config.js#L200-L204

This is not valid JavaScript and likely causing the error.
