### ISSUE TITLE
Nuxt generate FATAL error with netlify

### ISSUE THREAD

**Issue by MattixNow** [nuxt/nuxt.js#6821]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/MattixNow/mattaio-website/tree/5ee1335a398c3f63b2054647133fbc5b2effa8cf](https://github.com/MattixNow/mattaio-website/tree/5ee1335a398c3f63b2054647133fbc5b2effa8cf)

### Steps to reproduce

![image_3.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/79a0fba0-2448-11ea-8db4-973a0b681cc4.png)
Deploy to netlify

### What is expected ?

Working

### What is actually happening?

![image_2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/4a387280-2448-11ea-8db4-973a0b681cc4.png)
```
12:11:24 AM: ERROR in ./pages/about/index.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--3-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/about/index.vue?vue&type=script&lang=js&)
12:11:24 AM: Module not found: Error: Can't resolve '~/components/MiniHero.vue' in '/opt/build/repo/pages/about'
12:11:24 AM:  @ ./pages/about/index.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--3-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/about/index.vue?vue&type=script&lang=js&) 34:0-49 40:14-22
12:11:24 AM:  @ ./pages/about/index.vue?vue&type=script&lang=js&
12:11:24 AM:  @ ./pages/about/index.vue
12:11:24 AM:  @ ./.nuxt/router.js
12:11:24 AM:  @ ./.nuxt/index.js
12:11:24 AM:  @ ./.nuxt/client.js
12:11:24 AM:  @ multi ./.nuxt/client.js
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10148">#c10148</a>)</em></sub></div>

**Comment by manniL** [comment]
The casing of you component does not match (`minihero.vue` vs. `MiniHero.vue`)
