### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by phillipstemann** [nuxt/nuxt.js#6823]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://iDontHaveItOnline.com](https://iDontHaveItOnline.com)

### Steps to reproduce

I updated to the newest version of Nuxt.js and now I get this error.

Vue packages version mismatch:

- vue@2.6.10
- vue-server-renderer@2.6.11

This may cause things to work incorrectly. Make sure to use the same version for both.

  
  Vue packages version mismatch:
  
  - vue@2.6.10
  - vue-server-renderer@2.6.11
  
  This may cause things to work incorrectly. Make sure to use the same version for both.
  
  at Object.<anonymous> (node_modules/vue-server-renderer/index.js:8:9)
  at Module._compile (internal/modules/cjs/loader.js:778:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  at Module.load (internal/modules/cjs/loader.js:653:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  at Module.require (internal/modules/cjs/loader.js:692:17)
  at require (internal/modules/cjs/helpers.js:25:18)
  at Object.<anonymous> (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:20:27)
  at Module._compile (internal/modules/cjs/loader.js:778:30)

   ╭────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                            │
   │   ✖ Nuxt Fatal Error                                                                       │
   │                                                                                            │
   │   Error:                                                                                   │
   │                                                                                            │
   │   Vue packages version mismatch:                                                           │
   │                                                                                            │
   │   - vue@2.6.10                                                                             │
   │   - vue-server-renderer@2.6.11                                                             │
   │                                                                                            │
   │   This may cause things to work incorrectly. Make sure to use the same version for both.   │
   │                                                                                            │
   │                                                                                            │

### What is expected ?

It is expected to compile the code.

### What is actually happening?

But instead it crashes with a fatal error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10151">#c10151</a>)</em></sub></div>

**Comment by manniL** [comment]
That's a typical userland error.

There are various solutions: `yarn upgrade` / `npm update` / remove lock files + `yarn` or `npm i`

**Comment by daniplaninc** [comment]
The thing that works for me is:
- remove the lock file (package-lock.json)
- delete the node_modules folder (this is a mandatory step for me)
- run npm i

I am using Windows and Node 12.14.0

**Comment by jasperf** [comment]
Have the same issue:

```
Error: 
Vue packages version mismatch:
- vue@2.6.10
- vue-server-renderer@2.6.11
```

But the _package-lock.json_ is loading 2.6.10 for Vue and the Vue Server Renderer

```
...
"vue": "^2.6.10",
 "vue-loader": "^15.7.1",
"vue-router": "^3.1.3",
"vue-server-renderer": "^2.6.10",
"vue-template-compiler": "^2.6.10",
..
```
 So how would this be possible?

**Comment by ugurcanalyuz** [comment]
```
  Error:                                                                                   
   │                                                                                            
   │   Vue packages version mismatch:                                                           
   │                                                                                            
   │   - vue@2.6.14                                                                             
   │   - vue-server-renderer@2.7.1                                                              
   │                                                                                          
   │   This may cause things to work incorrectly. Make sure to use the same version for both. 
```

FIX: npm i vue-server-rendereer@2.6.14

**Comment by volcanioo** [comment]
> The solution is to run **npm update** after an **npm audit fix**

This worked for me! 🎉

**Comment by JHerwig** [comment]
I have found another solution. 
It seems as would package dependencies install the latest version. In my case `vue-debounce@4.0.0` installed `vue@3.2.37`. I have installed `vue@2.7.5` manually and this ` Vue packages version mismatch` error is gone.

**Comment by gtm-agency** [comment]
Hello, same here but nothing worked

Vue packages version mismatch:

- vue@2.6.14
- vue-server-renderer@2.7.5

This may cause things to work incorrectly. Make sure to use the same version for both.



  Vue packages version mismatch:

  - vue@2.6.14
  - vue-server-renderer@2.7.5

**Comment by Chitzi** [comment]
Solved it with
```
  "overrides": {
    "vue": "2.7.6",
    "vue-server-renderer": "2.7.6"
  }
```
in package.json

**Comment by amitleuva1987** [comment]
> npm i vue-server-renderer@2.6.14

This worked for me

**Comment by deannabosschert** [comment]
`npm update` or `npm audit fix` didn't do anything for me either, same with deleting/reinstalling package-lock and node_modules.

howeverrr, running the following two commands worked for me!
```bash
npm i vue-template-compiler@2.6.14
```

```bash
npm i vue-server-renderer@2.6.14
```

**Comment by mbarsil** [comment]
Hey all, after trying **ALL** the solutions proposed here, the only thing that worked for me was to manually reinstall the specific version that I had troubles with, both for `vue-server-renderer` and `vue-template-compiler`:

![image](https://user-images.githubusercontent.com/9843903/190898292-35e0ffd6-6265-4693-b43f-0a19541078fb.png)
![image](https://user-images.githubusercontent.com/9843903/190898294-8e69a818-c895-4f68-8aca-d0ed74b351a5.png)

In this case I ran:

```
npm i --save vue-server-renderer@2.6.14
npm i --save vue-template-compiler@2.6.14
```

Hope this might help the ones still having the issue

**Comment by tdebenne** [comment]
I have exacly the same issue but on Nuxt3-rc12:  
```
Error: Failed to load function definition from source: Failed to generate manifest from function source: Error: 

Vue packages version mismatch:

- vue@3.2.41
- vue-server-renderer@2.7.13
```

None of the mentioned solutions worked for me.

**Comment by danielroe** [comment]
@tdebenne You are likely using a dependency that is still using Vue 2. It's not the same as this issue. Also, Nuxt 3 issues can be reported at https://github.com/nuxt/framework.
