### ISSUE TITLE
[IE11] SPA in Production mode does not works

### ISSUE THREAD

**Issue by amesas** [nuxt/nuxt.js#6826]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://nuxt-ie11-bug.netlify.com](https://nuxt-ie11-bug.netlify.com)

### Steps to reproduce

yarn create nuxt-app ie11
yarn build --spa
yarn start --spa

### What is expected ?

App should display default nuxt template.

### What is actually happening?

Loading screen without any error con IE11 console.

### Additional comments?

Universal mode works.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10156">#c10156</a>)</em></sub></div>

**Comment by aldarund** [comment]
Your url dont have any errors in ie11. https://i.imgur.com/iFZyFBt.png
