### ISSUE TITLE
route list command

### ISSUE THREAD

**Issue by quarkmarino** [nuxt/nuxt.js#6830]
### What problem does this feature solve?

Hi, I'm coming from laravel, and there we have a route:list command, that generates a list that show all the routes that the application is available to respond to, is there a way to get something similar for the nuxt cli, in a way that we don't have to inspect the pages folder nor to manage a routes file in the project, or maybe I'm asking for something that already exists but couldnt find it, 

### What does the proposed changes look like?

* pages
    * posts
        * _id.vue
        * index.vue
* index.vue

I would like to be able something like 

```
nuxt routes
```
and get shown something like

```
PATH
/
/posts
/posts/{id}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10163">#c10163</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @quarkmarino 

I like this idea, right now you can get them with the [Vue Devtools](https://github.com/vuejs/vue-devtools) in the Routes section:

<img width="1171" alt="Screenshot 2019-12-30 at 00 45 44" src="https://user-images.githubusercontent.com/904724/71564251-d2050d80-2a9d-11ea-8ada-324cb468ea52.png">

**Comment by quarkmarino** [comment]
Thank you!

**Comment by aldarund** [comment]
and you can also look into generated router.js file in .nuxt folder

**Comment by quarkmarino** [comment]
Nice, it would be interesting if you implement it, but so far, your suggestions work for me, Thank you.
