### ISSUE TITLE
Memory leak when running "npm run build"

### ISSUE THREAD

**Issue by luismt** [nuxt/nuxt.js#6832]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/luismt/nuxt_app](https://github.com/luismt/nuxt_app)

### Steps to reproduce

Install node dependencies via "npm install" and run "npm run build".
![Imagen 27-12-19 a las 12.23.JPG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/17f0f080-28d6-11ea-868d-b3dff04737b6.JPG)

### What is expected ?

Webpack generates build stack for production in order to run "npm run start".

### What is actually happening?

"npm run build" crashes as a result from "Memory Leak".

### Additional comments?

I have seen reports of developers running into the same problem when running the development server "npm run dev".  However this is not an issue I am experiencing in development mode.  The app is pretty straight forward and I have tried some of the fixes for production.  Still I can't get around this problem. I have committed the report file into the repo for further auditing

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10166">#c10166</a>)</em></sub></div>

**Comment by aldarund** [comment]
Not a memory leak. Its because
```
  styleResources: {
    scss: [
      '~/assets/variables.scss',
```
where in your variables.scss you import whole vuetify css. So basically you inject WHOLE vuetify css into each scss file. And so you probably running into infinite loop or just large enough mem usage.
There even warning in nuxt style resource module for this.

> Do not import actual styles. Use this module only to import variables, mixins, functions (et cetera) as they won't exist in the actual build. Importing actual styles will include them in every component and will also make your build/HMR magnitudes slower. Do not do this!
