### ISSUE TITLE
Fetching data only once per app, not every time per page component

### ISSUE THREAD

**Issue by mitar** [nuxt/nuxt.js#6834]
### What problem does this feature solve?

I have some data which I would like to load the first time the page component is loaded, but if user navigates back to the same component, data should not be loaded again. Currently, I have to resolve this manually through a global variable.

### What does the proposed changes look like?

There could be also `asyncGlobalData` which would, if provided, be run only once per app, for that component, the first time it is needed.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10168">#c10168</a>)</em></sub></div>

**Comment by regenrek** [comment]
You could solve this behaviour with a plugin or use some state system like vuex or vue.observable

regards

**Comment by mitar** [comment]
Sure. I am writing that having some nice out-of-box API here would be cool to have.

**Comment by pimlie** [comment]
Sounds like you just need to use some state management lib like vuex or vue-stator or a custom implementation like you do with a global var?

I dont think it would be useful to add an API for this, as it can already easily be resolved in userland and we wouldnt then need to support all use-cases like _run asyncGlobalData once unless user comes back from Save page then run it again_ ;)

**Comment by mitar** [comment]
Sounds good.
