### ISSUE TITLE
Disable client side completely for just some routes (SSR only)

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt.js#6835]
### What problem does this feature solve?

We use Nuxt to render part of our application like invoices, reports and emails. This is then loaded into headless Chrome to convert it to PDF. The clientside part of Nuxt is completely redundant here. It only slows down the process and uses unnecessary resources on our server. Besides this makes it easy to introduce bugs to tracking tools like Google Analytics.

### What does the proposed changes look like?

Add a property to a page, e.g. `ssrOnly: true`. This will prevent injecting any JavaScript.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10169">#c10169</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @Timkor 

Actually, you can disable rendering the scripts for the whole Nuxt application by using `render.injectScripts` in your `nuxt.config.js`:

```js
render: {
  injectScripts: false
}
```

See demo: https://codesandbox.io/s/nuxt-no-scripts-hx8j4

**Comment by Timkor** [comment]
@Atinux 
Hi Atinux, 
That is helpful for a lot of situations I can think of. However I would like to disable it just for some routes. Do you think there is some way to handle this?

**Comment by HoraceKeung** [comment]
@Timkor Found this today when I was researching about SSR https://blog.lichter.io/posts/nuxt-dynamic-ssr-spa-handling/, not sure if it helps.

**Comment by Atinux** [comment]
@Timkor you can also use Nuxt hooks and remove the scripts with a Regexp, see this example: https://github.com/nuxt/nuxt.js/blob/dev/examples/with-amp/nuxt.config.js#L29-L37

You have access to the `route` in the `render:route` hook BTW :)

**Comment by Timkor** [comment]
@Atinux 
That will solve my issue. Thanks!
