### ISSUE TITLE
Custom server and routing

### ISSUE THREAD

**Issue by fadonascimento** [nuxt/nuxt.js#6838]
### What problem does this feature solve?

Hi guys, first of all I would like to congratulate you on your great work with Nuxt.
I would like to know how can I create a dynamic route based on a small request or how can I change which component should be rendering for example, because I use Drupal as a content delivered and the route must be controlled by Drupal like: ```Drupal based routing```, so when user access an route I need to get some information about this route from drupal, that returns which page component must be rendering, I used this example to use the async component injection  (https://github.com/nuxt/nuxt.js/blob/dev/examples/async-component-injection/pages/_slug.vue) but with this aproach I lost the power of component page, with the special methods like: asyncData, layout, etc ... 

### What does the proposed changes look like?

Create a way to change which page component will be rendering.
In the next I found this example:

https://github.com/zeit/next.js/#custom-server-and-routing
https://nextjs.org/docs/routing/imperatively

The example using the Drupal + Next:
http://next-on-drupal.surge.sh/reference/routing#drupal-based-routing

This is a great feature to Drupal dev users to connect Drupal community with Nuxt

Drupal <3 Nuxt

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10174">#c10174</a>)</em></sub></div>

**Comment by pimlie** [comment]
Could you use serverMiddleware's and middleware's to resolve this? Or use the vue-router _beforeRouteEnter_ in-component guard to catch all unknown routes and redirect them to your specific page component.

Dont exactly understand how Drupal works or what you need need though unfortunately

**Comment by fadonascimento** [comment]
Sorry for delay @pimlie, for now I can solve the issue using this aproach (https://github.com/nuxt/nuxt.js/blob/dev/examples/async-component-injection/pages/_slug.vue), and the new fetch api will solve the problem to retrieve data on server side
