### ISSUE TITLE
Context redirect function sanitizes double slashes in URL components

### ISSUE THREAD

**Issue by Soviut** [nuxt/nuxt.js#6841]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://jsfiddle.net/Soviut/wm37anqx/](https://jsfiddle.net/Soviut/wm37anqx/)

### Steps to reproduce

- Create a Nuxt middleware.
- Import `{ redirect }`
- call redirect `redirect('http://example.com?redirect_url=http://localhost:3000')`
- notice the URL it produces now has a single slash on the redirect_url component `http://example.com?redirect_url=http:/localhost:3000`

### What is expected ?

Components shouldn't be sanitized, only the main URL.

### What is actually happening?

Components are being sanitized and double forward slashes are being converted to single forward slashes.

### Additional comments?

I realize this can be solved with encodeURIComponent() but it's obviously not intended behavior.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10176">#c10176</a>)</em></sub></div>

**Comment by ankitarora05** [comment]
https://gamecom.app/

I created a website on nuxt and server render. Any thoughts?

FYI you have to login to enjoy the feed :-p

**Comment by EHfive** [comment]
https://github.com/nuxt/nuxt.js/blob/701f2d033bbc421f85f888f9bf9100b176aac818/packages/vue-app/template/utils.js#L578-L581

Seems the root cause come from here.

But it's because you have passed a wrong syntax URL, using `encodeURIComponent` is the "right" behavior.

**Comment by Soviut** [comment]
I understand. It might be worth documenting.
