### ISSUE TITLE
change the __nuxt id

### ISSUE THREAD

**Issue by songsChen** [nuxt/nuxt.js#6850]
### What problem does this feature solve?

I have learned that the team has the idea to delete the layout. I hope that I can modify the id name of the element __nuxt or add an option to set the id name.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10187">#c10187</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @songsChen 

It's already possible, see https://nuxtjs.org/api/configuration-global-name
