### ISSUE TITLE
NUXT and Vuetify. Difference in styles after running prod and dev

### ISSUE THREAD

**Issue by iLLia12** [nuxt/nuxt.js#6858]
### Environment:

- nodejs v10.15.0

- npm 6.7.0

- ubuntu 18.04

- Google chrome

app generated by **npx create-nuxt-app**

<hr>

### Issue:
After running npm run build && npm run start on the screen with small sizes i have different colors for some elements and v-navigation-drawer doesn't work, but everything works well after npm run dev
<hr>

### Steps to reproduce:

- git clone https://github.com/iLLia12/test-app.git

- npm i && npm run build && npm run start

- go to localhost:3000

- open dev tools, toggle device toolbar and  make screen width less than 600

- reload page with screen width less than 600 

- after make screen > 600 , reload and compare the result

<hr>

### Video links:
**npm run build && npm run start:** 
https://drive.google.com/open?id=1dIDMxD2s3Boy_tzsUV2gNq3nwi3qxTWO 
**npm run dev**:
https://drive.google.com/open?id=1zAbgOcnKIKxTXgJdBdG3ydGE54fXjdhg

<hr>

**nuxt.config.js**
https://github.com/iLLia12/test-app/blob/master/nuxt.config.js

**package.json**
`
{
  "name": "test-app",
  "version": "1.0.0",
  "description": "My fabulous Nuxt.js project",
  "author": "author",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "nuxt": "^2.0.0",
    "nuxt-sass-resources-loader": "^2.0.5"
  },
  "devDependencies": {
    "@nuxtjs/vuetify": "^1.0.0",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "vue-jest": "^4.0.0-0"
  }
}
`

**Comment by chuoke** [comment]
+1

I am newbie. It seems caused by purgecss.
