### ISSUE TITLE
Error page does not work in production mode

### ISSUE THREAD

**Issue by lhsazevedo** [nuxt/nuxt.js#6869]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/lhsazevedo/nuxt-missing-error-page-demo](https://github.com/lhsazevedo/nuxt-missing-error-page-demo)

### Steps to reproduce

- Clone reproduction repository, install dependencies
- npm run build
- npm run start
- Click on "Throw error" button

### What is expected ?

The exception should be caught by the Nuxt main error handler which displays a nice error page, as it happens when running in dev mode (npm run dev).

### What is actually happening?

Main error handler is ignored and exception ends up logged to console.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10202">#c10202</a>)</em></sub></div>

**Comment by talebi1** [comment]
you can have the error page back with debug:true, in nuxt.config.js. but you wouldn't want to do that in production.

I would suggest you catch the error, then call this.$nuxt.error({ message: "Boom" })

**Comment by antoineabbou** [comment]
Hello @lhsazevedo ! 

Same problem for me, did you manage to get around this problem ?

**Comment by lhsazevedo** [comment]
@talebi1 Now I see that this is a debug handler for developers (even mentions dev tools console), thank you.

@antoineabbou Yeah, I've created an [Error Boundary](https://medium.com/@dillonchanis/handling-errors-in-vue-with-error-boundaries-91f6ead0093b) component that wraps my default Layout content. It renders the default slot until an error is captured, and then switches to a simple 'Oops' page (simple v-if/v-else). Gist demo [here](https://gist.github.com/lhsazevedo/51da0c283e80fc6c7fd9651b439edb67).
