### ISSUE TITLE
Incorrect resolving path in less files

### ISSUE THREAD

**Issue by Marcelinka** [nuxt/nuxt.js#6874]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/github/nuxt/codesandbox-nuxt](https://codesandbox.io/s/github/nuxt/codesandbox-nuxt)

### Steps to reproduce

I cannot paste a reproduction link, cause I cannot move package.json into another folder (but I need it to show you situation)

0. You need some files in assets folder that you get in less (or css) files with url('~assets/some-file.svg')
1. Move all files to folder src in a root of project
2. In console move to folder src
3. Try to run project

### What is expected ?

I see all my icons

### What is actually happening?

I don't see icons that I use in background-image: url('~assets/some-file.svg'). In browser I can see background-image: url([object Object]);

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10204">#c10204</a>)</em></sub></div>

**Comment by talebi1** [comment]
step 1. is not very clear, what do you mean by "all" files? 
what files have you moved to the src folder? 
can you provide a screenshot of your browser console with the error?

**Comment by aldarund** [comment]
Create a proper reproduction with your steps 0 1 2 done.
