### ISSUE TITLE
trying to run latest from master

### ISSUE THREAD

**Issue by irobayna** [nuxt/nuxt.js#688]
getting the following error:

```
Error: Cannot find module './dist/nuxt.js'
```

have tried: ```yarn build```, ```yarn start``` and ```yarn dev``` all give me back same error.

Any ideas as to what should I do to get beyond this error?

Note:  trying to run the latest on master 

```
"nuxt": "https://github.com/nuxt/nuxt.js.git",
```

Thank you

**Comment by pi0** [comment]
@irobayna You have to invoke build command inside nuxt project not your own! (cd into node_modules/nuxt and then running `yarn install` `yarn build`)

**Comment by irobayna** [comment]
@pi0 Thank you!

**Comment by pi0** [comment]
UPDATE: https://github.com/nuxt/nuxt.js/issues/2142#issuecomment-347193288
