### ISSUE TITLE
Not able to show client side error page when SS rendering error occurs (after successful fetch/asyncData)

### ISSUE THREAD

**Issue by lluishi93** [nuxt/nuxt.js#6883]
Hi,

We have a problem. We use `fetch` to call our backend and fill data in the store, and that is Ok.

But if, for some reason, when the code starts rendering and something happens (for instance, a variable is `undefined` and the code tries to access some property in that variable), Nuxt automatically throws the SS error page.

While this is somehow the "logic behaviour", we would like to show the Client side error page (`layouts/error.vue`) instead of that one. 

Is there a way to do this?

Thank you

**Comment by gangsthub** [comment]
SS error page is the one using Universal mode and on DEV environment, right? I think, you'd get the error layout on a client side navigation. but if there's a JS error, the whole thing might break SS, therefore JS in unable to continue executing.

Some code examples or repo could help answering this ;)
