### ISSUE TITLE
How to configure Logs on Production?

### ISSUE THREAD

**Issue by sontd-0882** [nuxt/nuxt.js#6891]
### What problem does this feature solve?

Currently, the [ssrLog](https://nuxtjs.org/api/configuration-render#ssrlog) is only available in development. Is there a way to config the log in production mode? Or how to debug on production mode?

Thanks a lot!

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10217">#c10217</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @sontd-0882 

Actually the `ssrLog` option is made to forward SSR logs to the client for easier debugging in development, it is not recommend at all in production to avoid leaking sensitive information to the browser.

Most providers (Heroku, Zeit, etc) actually keep the logs for you to debug what's happening on the server-side.

You can also use a Nuxt module like [nuxt-winston-log](https://github.com/aaronransley/nuxt-winston-log) to send the logs to some external providers.
