### ISSUE TITLE
Typescript linting issue

### ISSUE THREAD

**Issue by Rakesh-webdeveloper** [nuxt/nuxt.js#6894]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/Rakesh-webdeveloper/nuxt-app](https://github.com/Rakesh-webdeveloper/nuxt-app)

### Steps to reproduce

- Clone the repository and npm install
- Run npm command to start
```
npm run dev

```

You will see the issue

### What is expected ?

I add the typescript for the nuxt app  using the doc.
But I still get the typescript issue.
https://typescript.nuxtjs.org/cookbook/components/[#c9215](https://cmty.app/nuxt/nuxt.js/issues/c9215 "nuxt.js - Cannot access templateVars.options in templates") 
I added this template to my pages folder file name **testPage.vue**

It is showing the typescript as the linting issue

Expected: should not show any typescript error

any help wold be appreciated..
I try 5-6 time I couldn't figure it out

### What is actually happening?

 Preparing project for development                                                                                                                                                                    12:54:59
ℹ Initial build may take a while                                                                                                                                                                       12:54:59
✔ Builder initialized                                                                                                                                                                                  12:54:59
✔ Nuxt files generated                                                                                                                                                                                 12:54:59

✖ Client
  Compiled with some errors in 9.03s

✔ Server
  Compiled successfully in 6.28s

ℹ Starting type checking service...                                                                                                                                                    nuxt:typescript 12:54:59
ℹ Using 1 worker with 2048MB memory limit                                                                                                                                              nuxt:typescript 12:54:59
ℹ Type checking in progress...                                                                                                                                                         nuxt:typescript 12:55:08

 ERROR  Failed to compile with 1 errors                                                                                                                                                friendly-errors 12:55:08

 ERROR  in ./pages/testPage.vue                                                                                                                                                        friendly-errors 12:55:08

Module Error (from ./node_modules/eslint-loader/dist/cjs.js):                                                                                                                          friendly-errors 12:55:08

/var/www/html/nuxt/nuxt-app-1/pages/testPage.vue
  20:6  error  Parsing error: Unexpected token, expected ","

  11 |       type: Object,
  12 |       required: true
> 13 |     } as PropOptions<User>
     |       ^
  14 |   },
  15 | 
  16 |   data () {

✖ 1 problem (1 error, 0 warnings)

 @ ./.nuxt/router.js 13:24-15:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
                                                                                                                                                                                   08
ℹ Waiting for file changes                                                                                                                                                                             12:55:08
ℹ Memory usage: 1.04 GB (RSS: 1.19 GB)                                                                                                                                                                 12:55:08

 ERROR  ERROR in /var/www/html/nuxt/nuxt-app-1/pages/testPage.vue(20,10):                                                                                                              nuxt:typescript 12:55:10
20:10 Cannot find name 'PropOptions'.
    18 |       type: Object,
    19 |       required: true
  > 20 |     } as PropOptions<User>
       |          ^
    21 |   },
    22 | 
    23 |   data () {

 ERROR  ERROR in /var/www/html/nuxt/nuxt-app-1/pages/testPage.vue(31,17):                                                                                                              nuxt:typescript 12:55:10
31:17 Object is of type 'unknown'.
    29 |   computed: {
    30 |     fullName (): string {
  > 31 |       return `${this.user.firstName} ${this.user.lastName}`
       |                 ^
    32 |     }
    33 |   }
    34 | });

 ERROR  ERROR in /var/www/html/nuxt/nuxt-app-1/pages/testPage.vue(31,40):                                                                                                              nuxt:typescript 12:55:10
31:40 Object is of type 'unknown'.
    29 |   computed: {
    30 |     fullName (): string {
  > 31 |       return `${this.user.firstName} ${this.user.lastName}`
       |                                        ^
    32 |     }
    33 |   }
    34 | });

ℹ Version: typescript 3.7.5                                                                                                                                                            nuxt:typescript 12:55:10
ℹ Time: 10999ms  

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10219">#c10219</a>)</em></sub></div>

**Comment by NickBolles** [comment]
https://github.com/Rakesh-webdeveloper/nuxt-app/blob/master/pages/testPage.vue#L17-L20

AFAIK That is not valid typescript syntax.

You can pull the user prop definition out into a constant and use that in your component options. Here's a working (ish) example:
https://codesandbox.io/s/musing-curie-0juco

Your second issue is that your trying to pass props to a page. This probably isn't what you want to be doing (unless maybe your passing them to the <nuxt /> component in the layout?, but that didn't work for me in my quick attempt). I just added a default to the prop in that codesandbox to illustrate the syntax issue.
