### ISSUE TITLE
Nuxt CLI banner is not displayed after build process is done but before

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#6899]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Description

To improve the UX, the user should have all (dev) app information available "at the end". If he wants to click on the link to open the app (instead of using -o), he has to scroll to the top of the output at the moment.

### Steps to reproduce

1. Create a project
2. Run yarn dev (or npm dev)

![2020-01-21 11 27 54](https://user-images.githubusercontent.com/640208/72797558-a0690780-3c41-11ea-85ab-176edaa12e4e.gif)

### What is expected ?

See the compilation process and then the nuxt banner with a link to the app

### What is actually happening?

See the Nuxt banner which will move out of screen quickly due to the compilation / build step

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10221">#c10221</a>)</em></sub></div>

**Comment by Atinux** [comment]
Actually it's intented to show it at the beginning since it can already go to the link and see the [loading-screen](https://github.com/nuxt/loading-screen) without having to wait for the console to end.

As an improvement, we can add a link when the first build is done to the url.

**Comment by manniL** [comment]
Sure, that makes sense (and is usually what I do). But probably many ppl aren't used to that and wait for the "typical" banner at the end.

So yeah, maybe printing it twice (at the start and the end) would satisfy both parties? 🤔

**Comment by pi0** [comment]
I agree with @Atinux idea to show an info with URL(s) after first build (like mem usage message). So would suggest escalating to a PR.

---

Kinda related: This is how it looks like on standard minimum terminal size (80x25):

![image](https://user-images.githubusercontent.com/5158436/72897527-763b4680-3d22-11ea-9e52-87c9b95fb413.png)

Maybe root cause is we are too verbose with worker pool logs.

**Comment by jamesgeorge007** [comment]
Can I take this up?

**Comment by manniL** [comment]
> Maybe root cause is we are too verbose with worker pool logs.

Probably because the "compilation successful" message isn't cleared but repeated every time you change something 🤔 

> Can I take this up?

Sure ☺️

**Comment by jamesgeorge007** [comment]
@manniL it would be great if you could give me a better picture regarding what needs to be done specifically :clap:

**Comment by Atinux** [comment]
@jamesgeorge007 I believe adding something like this at this line https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/commands/dev.js#L85 should be good enough 😄 

```js
 // Display server urls after the build
for (const listener of nuxt.server.listeners) {
  consola.info('Listening on: ' + listener.url)
}
```
