### ISSUE TITLE
nuxt connecting to graphql apollo client

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#69]
Hello,
Is there a way to fetch data on each reload from a graphql apollo client and render its content based on the data it is fetching? Would be very interested in an example.
Thanks

**Comment by Atinux** [comment]
Hi @dohomi 

First, to make the `apollo-client` works on the server-side, you need to polyfill `fetch`, you can do it by installing the [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) module.

Then, you need the `apollo-client` and `graphql-tag` module. you can add them in your `nuxt.config.js` file in the `build.vendor` section.

I created an example for you so you can see how it works: https://gomix.com/#!/project/nuxt-apollo-client
Live demo: https://nuxt-apollo-client.gomix.me/

I created the `~plugins/apolloClient.js` to create the connection and re-use it in every pages components.

**Comment by dohomi** [comment]
Great stuff, thanks @Atinux

**Comment by thes01** [comment]
There is this plugin https://github.com/nuxt-community/apollo-module which you can use.
