### ISSUE TITLE
show up collective information after package installation

### ISSUE THREAD

**Issue by jamesgeorge007** [nuxt/nuxt.js#6903]
### What problem does this feature solve?

Prompts users to donate to the collective via a postinstall message.

### What does the proposed changes look like?

We can onboard [opencollective-postinstall](https://github.com/opencollective/opencollective-postinstall) for the purpose.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10226">#c10226</a>)</em></sub></div>

**Comment by jamesgeorge007** [comment]
I would love shoot a PR if you guys're willing to have it :+1:

**Comment by manniL** [comment]
Hey @jamesgeorge007 👋 

We already use https://github.com/nuxt/opencollective (which I rewrote based on opencollective-postinstall for various reasons). When using yarn, the message is not displayed because yarn blocks such post-install messages.
