### ISSUE TITLE
README.md file incorrect

### ISSUE THREAD

**Issue by ngblaylock** [nuxt/nuxt.js#6905]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/ngblaylock/nuxt-sandbox](https://github.com/ngblaylock/nuxt-sandbox)

### Steps to reproduce

This is my first time submitting any issues, so please excuse me for any inconsistencies in your workflow. 

When I run `npx create-nuxt-app <project name>` it automatically creates the README.md file. On the first set of instructions, it says to run `$ npm run install`. From my research, and after much trial and error, I found that it should be `npm install` (remove run). 
![Annotation 2020-01-23 123631.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b40667b0-3e17-11ea-aaab-0790a603407d.png)

### What is expected ?

It should install dependencies when cloning a repo from GitHub.

### What is actually happening?

It gives me an error saying that it is not a valid command.

### Additional comments?

If I am missing anything, please let me know. I am still a newbie, especially to GitHub collaboration.

Thanks for making Nuxt. It is awesome!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10228">#c10228</a>)</em></sub></div>

**Comment by manniL** [comment]
fixed via https://github.com/nuxt/create-nuxt-app/pull/401
