### ISSUE TITLE
Inline JavaScript Added Using Vue Meta Runs Twice

### ISSUE THREAD

**Issue by saulhardman** [nuxt/nuxt.js#6906]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/saulhardman/nuxt-inline-scripts](https://github.com/saulhardman/nuxt-inline-scripts)

### Steps to reproduce

1. Navigate to the [live reproduction](https://nuxt-inline-scripts.netlify.com/).
2. Open DevTools console and see that `Hello World!` was logged.
3. Navigate to the 'Test' page using the 3rd link in the list.
4. See `Hello World!` logged once again.
5. Navigate back and forth to see no further logs being made.

### What is expected ?

JavaScript that is inlined into the `<head>` via the `head.script` array in `nuxt.config.js` with the special attribute `once` set to `true` should only be parsed and executed once.

### What is actually happening?

The inlined scripts are being ran for a 2nd time when navigating away from the page that was initially loaded.

### Additional comments?

The site is being statically built using `yarn generate`. The issue only arises when the layout, pages, or components have a `head()` method defined.

I've worked around the issue by declaring the inline scripts within the `~/layouts/default.vue` file's `head()` method, only `if (process.server)`. For convenience and code reusability it would be better to do it via the `nuxt.config.js`. Unsure if this is an issue with Nuxt's usage of Vue Meta or an issue with the package itself.

Additionally, if I create a `{ mode: 'server' }` plugin and update the config via `ctx.app.head` this doesn't happen.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10229">#c10229</a>)</em></sub></div>

**Comment by isneezy** [comment]
@saulhardman your reproduction link is not available

**Comment by saulhardman** [comment]
@ilyatab thanks for the heads-up – the GitHub repository is now public 👍🤦‍♂️

**Comment by saulhardman** [comment]
On installing `"nuxt-edge": "2.12.0-26325618.a375a6c3"` and repeating the reproduction steps above this bug is no longer present. Unsure if it has been addressed directly or if it has resolved itself as a result of dependencies being updated, but either way it looks like it'll be resolved in the next release 👍
