### ISSUE TITLE
Launch nuxt.generate() from nuxt server ignore config

### ISSUE THREAD

**Issue by exebetche** [nuxt/nuxt.js#6917]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/exebetche/nuxt-generate-test](https://github.com/exebetche/nuxt-generate-test)

### Steps to reproduce

1) Create a server middleware on nuxt SSR server, which import Nuxt, Builder, Generator and nuxt.config.js file
2) Call the middleware with the appropriate request and in the response, instantiate Nuxt with the config then call Builder.build() and Generator.generate()

### What is expected ?

The new nuxt instance should build and generate the static files for the project according to the data in nuxt.config.js.

### What is actually happening?

The config data in nuxt.config.js are ignored and the new nuxt instance use a default config, ignoring routes, buildDir and all data in nuxt.config.js. The call to generate result to an error: ERROR  ENOENT: no such file or directory, stat '/my_project/.nuxt/dist/client'

### Additional comments?

'nuxt generate' from console works fine.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10237">#c10237</a>)</em></sub></div>

**Comment by funyaliga** [comment]
Same problem。😥
