### ISSUE TITLE
Nuxt.js throws 404 error when redirecting inside beforeEach() navigation guard

### ISSUE THREAD

**Issue by mzenz** [nuxt/nuxt.js#6918]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/github/mzenz/nuxt-nav-guard-issue](https://codesandbox.io/s/github/mzenz/nuxt-nav-guard-issue)

### Steps to reproduce

- Open code sandbox
- Upon home page loading click on "Private" link.

### What is expected ?

Vue router's beforeEach() guard prevents navigation to '/private' and redirects to '/' which looks to the user like no navigation took place.

### What is actually happening?

Nuxt throws a 404 error page.

### Additional comments?

Please note that the exact same navigation guard code works correctly on a vanilla Vue app (i.e. without Nuxt):

https://codesandbox.io/s/github/mzenz/vue-nav-guard

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10238">#c10238</a>)</em></sub></div>

**Comment by btkostner** [comment]
I can confirm that this issue still exists using nuxt `2.13.3`. Using the following auth plugin will result in a 404 page with the correct url showing. After a page refresh, the correct page shows.

```js
export default (ctx) => {
  const { getters } = ctx.store

  ctx.app.router.beforeEach((to, from, next) => {
    switch (true) {
      // auth required but not logged in
      case (routeOption(to, 'auth', 'admin') && !getters['auth/isLoggedIn']):
      case (routeOption(to, 'auth', 'user') && !getters['auth/isLoggedIn']):
        console.log("redirecting here now!")
        return next({ path: '/auth/login', replace: true })

      default:
        return next()
    }
  })
}
```

I'm going to see what I can do about debugging (and hopefully fixing) this.
