### ISSUE TITLE
Nuxt + Socket IO Example Not Exposing on Port 3000

### ISSUE THREAD

**Issue by AllanOricil** [nuxt/nuxt.js#6928]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://bitbucket.org/allanoricil/nuxt-socket-io/src/master/](https://bitbucket.org/allanoricil/nuxt-socket-io/src/master/)

### Steps to reproduce

Build the App using npm run dev
You will notice that the app is not exposed on port 3000 anymore.
Also we don't see the message http://localhost:3000 as usual
The image below shows what is happening.
![terminal.JPG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/563a7c60-4228-11ea-a204-91cdcc006f28.JPG)

### What is expected ?

To have the App exposed on port 3000. I followed this example: https://github.com/nuxt/nuxt.js/tree/dev/examples/with-sockets

### What is actually happening?

The app is not exposed on port 3000

### Additional comments?

The only difference from the example and what I did is that in the IO/index.js Im also importing redis adapter for socket.io. But even removing it, the result is the same.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10244">#c10244</a>)</em></sub></div>

**Comment by jjelev** [comment]
can you debug the part of `port || 3000` ? Your port may be set to something else.

**Comment by AllanOricil** [comment]
I just copied and pasted the example. Without this IO/index.js the app starts normally on Port 3000.
But I will debug the value of port inside the method that sets the port. But why I can't even see the "https://localhost:PORT" message after starting the anymore? This seems weird

**Comment by AllanOricil** [comment]
The port and host are undefined. But because the example is using that || shouldn't it be resolved to 3000 and localhost?

To "fix" the issue I just hardcoded 3000 and localhost 

```javascript
server.listen(3000, 'localhost', resolve)
```

**Comment by AllanOricil** [comment]
I thought that if I declare port and host like below in the nuxt.config.js. The io/index.js would get these values from there. 

inside my nuxt.config.js
```javascript

server:{
     port: 4000,
     host: '0.0.0.0'
}

```

Could you explain how am I suppose to pass port and host to the method below? The example seems to be not injecting anything there. Maybe there is a way of doing it but it is no clear.

inside io/index.js
```javascript
this.nuxt.server.listen = (port, host) =>
      new Promise((resolve) => {
        server.listen(port || 3000, host || 'localhost', resolve)
      })
```


Thank you. I hope you can help me.

**Comment by pdlima** [comment]
To anybody else is still struggling with this: the easy solution is to set ENV variables as usual and make this change:

`this.nuxt.server.listen = (port, host) =>
      new Promise(resolve =>
        server.listen(
          process.env.PORT || 3000,
          process.env.HOST || "0.0.0.0",
          resolve
        )
      );`

**Comment by AllanOricil** [comment]
> To anybody else is still struggling with this: the easy solution is to set ENV variables as usual and make this change:
> 
> `this.nuxt.server.listen = (port, host) => new Promise(resolve => server.listen( process.env.PORT || 3000, process.env.HOST || "0.0.0.0", resolve ) );`

Few months later I learned that. But thanks for sharing it!

**Comment by jakubsuplicki** [comment]
If someone is still struggling to make it work in production with the example above, all you might need to change is the url in your plugin file - `plugins/socket.io.js`.
So instead of defining the `endPoint`, let it be default like: `const socket = io()`
