### ISSUE TITLE
[Bug] serverMiddleware don't work with eslint and alias config

### ISSUE THREAD

**Issue by KytoSai** [nuxt/nuxt.js#6934]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/KytoSai/nuxt-issue_eslint](https://github.com/KytoSai/nuxt-issue_eslint)

### Steps to reproduce

- I create app with crreate-nuxt-app
- I check with `eslint` option
- Setup serverMiddleware in `api/index.js` 
- I try test alias, eslint but it don't work

### What is expected ?

I want to eslint, alias config work with serverMiddleware

### What is actually happening?

Eslint, alias config don't work with nuxtjs

Demo:

![](https://i.imgur.com/PJezvVU.jpg)

### Additional comments?

I really want to find solutions so that eslint and alias can work in serverMiddleware

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10254">#c10254</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @KytoSai 

Actually, aliases are used in Webpack and serverMiddleware are run outside Webpack, so you cannot use aliases there.

**Comment by manniL** [comment]
See #4580
