### ISSUE TITLE
Using fuse-box instead of webpack?

### ISSUE THREAD

**Issue by hason** [nuxt/nuxt.js#694]
I ran across fuse-box and was really impressed how fast the browser would hot reload the page.

fuse-box has some other nice features, and it feels like it would pair really well with nuxt.js.

https://github.com/fuse-box/fuse-box

**Comment by stephan281094** [comment]
FuseBox looks promising, but I don't think it's possible to implement it into Nuxt at this point. It would introduce a lot of breaking changes, both in the core and in projects built with Nuxt. It would require users to migrate from Webpack to FuseBox, which might not even be possible in some cases.

**Comment by Atinux** [comment]
I agree with @stephan281094 

Even if Fuse-Box is an incredible project, most Vue.js users know Webpack and we don't want to add a learning curve to use nuxt.js.

**Comment by uptownhr** [comment]
I have to say though, the 10x improvement on build speed is very enticing!

**Comment by benfavre** [comment]
Maybe reconsider ?
