### ISSUE TITLE
Nuxt crashes when navigating to "//"

### ISSUE THREAD

**Issue by mzenz** [nuxt/nuxt.js#6948]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/github/mzenz/nuxt-double-slash-issue](https://codesandbox.io/s/github/mzenz/nuxt-double-slash-issue)

### Steps to reproduce

- Go to sandbox https://codesandbox.io/s/github/mzenz/nuxt-double-slash-issue.
- Go to sanbox's address bar and navigate to `https://wpkhp.sse.codesandbox.io//` (i.e. add an extra `/` to root url).
- Observe console's error being thrown.

### What is expected ?

Same behavior as plain Vue app, which sanitizes url and doesn't crash.

### What is actually happening?

Nuxt app crashes throwing the following error:

```
> replaceState@https://sse.codesandbox.io/client-hook-2.js:1:22351
setupScroll@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1694:18
HTML5History@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2365:7
VueRouter@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2705:22
createRouter@webpack-internal:///./.nuxt/router.js:43:10
_callee2$@webpack-internal:///./.nuxt/index.js:107:84
tryCatch@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:45:40
invoke@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:271:30
defineIteratorMethods/</prototype[method]@webpack-internal:///./node_modules/regenerator-runtime/runtime.js:97:21
asyncGeneratorStep@webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:5:24
_next@webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:27
_asyncToGenerator/</<@webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:34:12
_asyncToGenerator/<@webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:23:12
_createApp@webpack-internal:///./.nuxt/index.js:241:21
createApp@webpack-internal:///./.nuxt/index.js:94:21
@webpack-internal:///./.nuxt/client.js:145:61
@webpack-internal:///./.nuxt/client.js:1154:30
./.nuxt/client.js@https://wpkhp.sse.codesandbox.io/_nuxt/app.js:23:1
__webpack_require__@https://wpkhp.sse.codesandbox.io/_nuxt/runtime.js:791:30
fn@https://wpkhp.sse.codesandbox.io/_nuxt/runtime.js:151:20
0@https://wpkhp.sse.codesandbox.io/_nuxt/app.js:460:18
__webpack_require__@https://wpkhp.sse.codesandbox.io/_nuxt/runtime.js:791:30
checkDeferredModules@https://wpkhp.sse.codesandbox.io/_nuxt/runtime.js:46:23
webpackJsonpCallback@https://wpkhp.sse.codesandbox.io/_nuxt/runtime.js:33:19
@https://wpkhp.sse.codesandbox.io/_nuxt/app.js:1:57
```
![nuxt-bug.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/37e6c690-4a0e-11ea-a054-39def0439bff.jpg)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10266">#c10266</a>)</em></sub></div>

**Comment by manniL** [comment]
As a workaround, this can be resolved through the overlaying web server or, if it's a generated page, hosting provider.

**Comment by AndrewSavetchuk** [comment]
Could you elaborate more on this, please? I have an error in console when I'm trying to open website with double or more slashes at the end of the URL:
`DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https:' cannot be created in a document with origin 'https://example.com' and URL 'https://example.com///'.`
