### ISSUE TITLE
$router.push/replace do not return promise

### ISSUE THREAD

**Issue by snapwich** [nuxt/nuxt.js#6951]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/muddy-butterfly-oxbul](https://codesandbox.io/s/muddy-butterfly-oxbul)

### Steps to reproduce

Click links, exception will be thrown because return result of `push` is not then-able.

### What is expected ?

result of $router.push("link") to be a promise

### What is actually happening?

it is not a promise

### Additional comments?

Nuxt v2.11 has vue-router v3.1.5 and vue-router 3.1.0+ should return Promise if callback is omitted: https://router.vuejs.org/guide/essentials/navigation.html#router-push-location-oncomplete-onabort

I think the nuxt router is wrapped in way that is causing the vue-router to not behave properly.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10269">#c10269</a>)</em></sub></div>

**Comment by darkylmnx** [comment]
Why is this issue closed? This bug is still going on and making third-party libs like vue-auth having bugs as they expect the router to return a promise.
