### ISSUE TITLE
Error page causes layout components mount twice

### ISSUE THREAD

**Issue by gerasimvol** [nuxt/nuxt.js#6961]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/mounted-twice-error-page-f2qvy](https://codesandbox.io/s/mounted-twice-error-page-f2qvy)

### Steps to reproduce

1. watch Console and see 'LOGO MOUNTED IN LAYOUT' from ~/components/Logo.vue used in ~/layouts/default.vue
2. click on 'error' link
3. observe 'LOGO MOUNTED IN LAYOUT' from Logo.vue again
4. navigate to any links and see no more messages

### What is expected ?

'LOGO MOUNTED IN LAYOUT' message only once in console, because layout is not changing

### What is actually happening?

'LOGO MOUNTED IN LAYOUT' message is shown twice, when visiting error page

### Additional comments?

similar to #5703

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10277">#c10277</a>)</em></sub></div>

**Comment by gerasimvol** [comment]
reproduces only in dev mode
ok on production

**Comment by Atinux** [comment]
Sorry for the delay @gerasimvol 

When I go to https://f2qvy.sse.codesandbox.io/asdasdasd, I only see the log once in the console.

**Comment by gerasimvol** [comment]
@Atinux very strange that bug disappeared in codesandbox, but still occurs in dev mode 🤔
please export example as ZIP and run locally (npm run dev)

**Comment by gerasimvol** [comment]
bug is still present, even in v2.12.0
issue description is relevant

**Comment by gerasimvol** [comment]
similar to https://github.com/nuxt/nuxt.js/issues/5703

**Comment by Atinux** [comment]
Workaround found: https://github.com/nuxt/nuxt.js/issues/5703#issuecomment-603969605

Fixed sandbox (until next release of Nuxt): https://codesandbox.io/s/mounted-twice-error-page-qt672

**Comment by Atinux** [comment]
Nuxt V2.12.1 is released with the fix 🤟
