### ISSUE TITLE
Can't require a local js file in the nuxt.config.js

### ISSUE THREAD

**Issue by hadelnasr** [nuxt/nuxt.js#6962]
### Version

[2.12](https://github.com/nuxt.js/releases/tag/2.12)

### Reproduction link

[http://www.google.com](http://www.google.com)

### Steps to reproduce

add a locale js file in the assets directory
add this blog in the nuxt.config.js
script: [
            {
                src: '~assets/js/script.js'
            }
        ],

### What is expected ?

to load that js file 

### What is actually happening?

can't load the file

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10279">#c10279</a>)</em></sub></div>

**Comment by Atinux** [comment]
Please provide a reproduction, see https://template.nuxtjs.org and reopen this issue
