### ISSUE TITLE
Failed to load plugin 'unicorn'

### ISSUE THREAD

**Issue by jasonlav** [nuxt/nuxt.js#6963]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://jsfiddle.net/6rhqk2jz/](https://jsfiddle.net/6rhqk2jz/)

### Steps to reproduce

1. Create a Nuxt project using the `npx create-nuxt-app`.
2. Choose ESlint under linting tools
3. Fails on initial build.

### What is expected ?

ESLint is an option in Nuxt project creation; should work without errors.

### What is actually happening?

Fails on compile.

```
SyntaxError: Failed to load plugin 'unicorn' declared in '.eslintrc.js » @nuxtjs/eslint-config': Invalid regular expression: /(?<before>(?:^|[^\\])(?:\\\\)*)\\(?<data>x[\da-f]{2}|u[\da-f]{4}|u{[\da-f]+})/: Invalid group
    at Object.<anonymous> (/Users/user/nuxt-lint-error/node_modules/eslint-plugin-unicorn/rules/escape-case.js:10:29)
    at Module._compile (/Users/user/nuxt-lint-error/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/Users/user/nuxt-lint-error/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at module.exports (/Users/user/nuxt-lint-error/node_modules/import-modules/index.js:47:29)
    at Object.<anonymous> (/Users/user/nuxt-lint-error/node_modules/eslint-plugin-unicorn/index.js:6:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nuxt-lint-error@1.0.0 lint: `eslint --ext .js,.vue --ignore-path .gitignore . "--fix"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nuxt-lint-error@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-02-12T22_40_57_944Z-debug.log
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10281">#c10281</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce on my end 🤔

Which node version are you using?

**Comment by san4io** [comment]
> Can't reproduce on my end 
> 
> Which node version are you using?

10.16

**Comment by manniL** [comment]
Weird! Just installed a sample application generate via `npx create-nuxt-app` and changed node version but can't reproduce that issue at all w/ the latest Node 10.X. Maybe another/an older node version is used?

Upgrading Node should help.

Related issue: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/557

**Comment by san4io** [comment]
Ok, found solution.

It's IDE error if you're using JetBrains.

**You need to manually set ESLint configuration node interpreter to 10+**

![image](https://user-images.githubusercontent.com/12079341/74596053-6c231400-5052-11ea-94eb-dff4e6740c19.png)

**Comment by jasonlav** [comment]
Was using node 8.12.0; switched to 10.16.0 and issue appears to be resolved.

Appreciate the PHPStorm tip as well.

**Comment by Valentin-Seehausen** [comment]
Downgrading from node version ^13 to ^10 solved it for me.

**Comment by seth100** [comment]
Still same issue for me! I'm using `yarn v1.22.17`, `node v14.18.0` and `npm v8.5.1`.
From my `.eslintrc.js`:
```js
extends: [
    'eslint:recommended',
    'plugin:vue/recommended',
    '@nuxtjs',
  ],
```
What I discovered is:

- if I use `"version": "1.1.0",` in `package.json` I get no errors and everything works!
- if I use another version I get Error: Failed to load plugin 'unicorn' declared in '.eslintrc.js » @nuxtjs/eslint-config': Invalid version: "[THE_VERSION_I_USED]"

**Comment by ThiloHettmer** [comment]
@gaetansenn could you fix it?

**Comment by devzom** [comment]
Try with this package:
npm install eslint-plugin-node --save-dev
