### ISSUE TITLE
reference assets to backend public laravel in parent folder (uploaded user)

### ISSUE THREAD

**Issue by mryassera** [nuxt/nuxt.js#6965]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/mryassera/issue-nuxt-reference-to-public-laravel/blob/master/imageLoad.vue](https://github.com/mryassera/issue-nuxt-reference-to-public-laravel/blob/master/imageLoad.vue)

### Steps to reproduce
Images is working with dev but for production, if user upload new image, the new image disappear until do "npm run build" again.

Structure project:
![full-Project.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/9a81e490-4dfd-11ea-9d8a-a310fb93a532.jpg)

Client (Nuxt SSR directory) 
![client.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/ea004270-4e05-11ea-9d8a-a310fb93a532.jpg)

Public directory (Assets in laravel)
![public.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/ac855150-4e06-11ea-abf6-4d37d4548d72.jpg)

src call function
![src.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/dda79330-4e18-11ea-abf6-4d37d4548d72.jpg)

imageLoad() method to render image from public folder
![imageLoadFun.jpg](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b7f3f970-4e19-11ea-abf6-4d37d4548d72.jpg)

### What is expected ?

I want reference assets to public folder without bundle images by webpack (keep all assets in "public" folder and reference to it)

### What is actually happening?

For production "npm run build" all images copy to (dist) directory

Issue with dashboard : 
If user upload images into "public" folder, then images disappear until run "npm run build" again to copy new images uploaded to (dist) directory !!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10283">#c10283</a>)</em></sub></div>

**Comment by manniL** [comment]
This is how it works. assets are compiled at build time. You could place truly static assets in /static and refer to them based on /, *or* separate your Laravel & Nuxt application
