### ISSUE TITLE
production mode, cpu and memory can't be release

### ISSUE THREAD

**Issue by RookiEzz** [nuxt/nuxt.js#6966]
### Version

[1.4.0](https://github.com/nuxt.js/releases/tag/1.4.0)

### Reproduction link

[https://ex.arworld.ai/](https://ex.arworld.ai/)

### Steps to reproduce

refresh and refresh

### What is expected ?

cpu, memory is ok

### What is actually happening?

cpu and memory will be higher and higher

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10284">#c10284</a>)</em></sub></div>

**Comment by manniL** [comment]
A classic memory leak, usually from userland code. Hard to investigate w/o source code.

PS: The page already dies on the first load for me 🤔
