### ISSUE TITLE
Example with JWT authorization?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#697]
Can somebody provide tips, or example?
I didn't find in /examples folder nothing related. Is there any? example-todomvc is helpful, but still I'm struggling. Will appreciate any help.

**Comment by pi0** [comment]
@kodekrendel How would you like to use JWT? Password based auth?

**Comment by kodekrendel** [comment]
@pi0 yes, password based auth, with email authentification.

**Comment by pi0** [comment]
Suggest taking a look at [store.js](https://github.com/nuxt/nuxt-modules/blob/master/modules/auth/store.js) example here. We are currently using same implemention for JWT Token based auth. (token is being stored in browser cookie)

**Comment by kodekrendel** [comment]
@pi0 seems too complicated, expecting to use some middleware.

**Comment by pi0** [comment]
Don't think ~100 Lines of code for auth is so complicated 😁🤔 We are currently working on nuxt modules system so like middleware you mentioned we *may* provide such thing but it would be *framework specific* something like *laravel-auth* or ...

**Comment by QtMobile** [comment]
Here is a ready working example
https://github.com/QtMobile/nuxt-stack

**Comment by yi-ge** [comment]
I've tried a lot of times. JWT Can only run in browser.

**Comment by pi0** [comment]
Just to be clear the term [JWT](https://jwt.io) is just a kind of *API Token* which encodes/signs some json data that may be used for **API** *authorization*. So i think we are talking about **Authentication Flow** (password based/oauth/onetime ...) and **How we keep tokens**. Keeping tokens can be done  by using browser cookies that in server side should be accessible using `global.__VUE_SSR_CONTEXT__.req.headers.cookie` (subject to change) and in browser using `document.cookie` and then parsed by libraries like `cookie`.

**Comment by kodekrendel** [comment]
@Kin-Dza-Dza thanks, but authorization in demo is not working.

**Comment by Kin-Dza-Dza** [comment]
@kodekrendel 
 
Menu Item Auth - for example (inside code write it)
Registration and Login - working

**Comment by kodekrendel** [comment]
@Kin-Dza-Dza it does not work after refresh.

**Comment by Kin-Dza-Dza** [comment]
@kodekrendel What does not work there? I just checked, the code is completely working.

**Comment by kodekrendel** [comment]
@Kin-Dza-Dza I already told. You log out after refresh the page.

**Comment by kodekrendel** [comment]
@Kin-Dza-Dza go to secret page and refresh the page, to be specific.

**Comment by kodekrendel** [comment]
@Kin-Dza-Dza do you use this? https://github.com/nuxt/express/blob/master/protected-ssr-api.md

**Comment by Kin-Dza-Dza** [comment]
@kodekrendel  https://nuxtstack.herokuapp.com/registration Fully all works

**Comment by kodekrendel** [comment]
Seems like you don't read my posts.

**Comment by kodekrendel** [comment]
@Kin-Dza-Dza https://nuxtstack.herokuapp.com/secret doesn't work after refresh

**Comment by Kin-Dza-Dza** [comment]
@kodekrendel Try it !!!

**Comment by kodekrendel** [comment]
@Kin-Dza-Dza you made changes? All remains the same. After refresh I got 403

**Comment by Kin-Dza-Dza** [comment]
@kodekrendel )) And it is right!!!

**Comment by Kin-Dza-Dza** [comment]
@kodekrendel If you want the secret page to be displayed and after rebooting the page, try using the method nuxtServerInit() by initializing it in the store. More in detail here - https://nuxtjs.org/guide/vuex-store/
Today I will add such functionality to the stack
