### ISSUE TITLE
Changes inside vuex mutation doesn't reflect on real vuex state

### ISSUE THREAD

**Issue by leonardoEbert** [nuxt/nuxt.js#6974]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://jsfiddle.net/65s4nLk9/](https://jsfiddle.net/65s4nLk9/)

### Steps to reproduce

1. It is a vuex module, the getShopAddress action is called inside nuxtServerInit on index.js file.
2. When the action is called it make a HTTP request to my backend server and return data.
After fetching data from backend, a mutation is called and it change the state, because on the first console.log the state is printed empty, but on the second the state has te changes that was expected

### What is expected ?

Changes made inside mutation to reflect the changes to the 'real' vuex state

### What is actually happening?

The Vuex state doesn't change

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10292">#c10292</a>)</em></sub></div>

**Comment by matteo-rigon** [comment]
`getShopAddress` is a getter and not an action in your fiddle, so i guess you mean `getAddress` is being called by `nuxtServerInit`.
Anyway you need to return a promise in the action and use `await` on `nuxtServerInit` or it won't know it should wait until the request is done.

in `store/index.js`
```
export const actions = {
    async nuxtServerInit({ dispatch }) {
        await dispatch('<your module>/getAddress')
    }
}
```

In your module
```
getAddress({ commit }) {
        return this.$axios
            .get('/general/address')
            .then((response) => {
                commit('setShopAddress', response.data)
            })
            .catch((e) => console.error(e))
 },
```

or even better 
```
async getAddress({ commit }) {
    try {
        const { data } = await this.$axios.get('/general/address')
        commit('setShopAddress', data)
    } catch (e) {
        console.error(e)
    }
 },
```

**Comment by leonardoEbert** [comment]
It worked for me, thank you so much @matteo-rigon
