### ISSUE TITLE
Module not found -- only on server

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt.js#6976]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Steps to reproduce

I installed this package: https://github.com/brtjkzl/vue-float-label
After a while, I decided to delete it again. I removed it from package.json. I installed another library. Now I decided to stick with: https://github.com/brtjkzl/vue-float-label (I know - confusing right).

Anyhow, when I install it now, I get error: Cannot find module 'vue-float-label/components/FloatLabel' from '/Users/user/Projects/jwr-nuxt'

It ONLY happens if I visit the site directly, where server should render. If I go to another page, and then click myself into the page where FloatLabels should be, I get no error.

I didnt' commit anything.  So I tried all over by using git stash, then adding the library again, exactly as I did before where it worked, but I still get that error.

I have also tried running yarn upgrade and yarn remove to re-install the plugin, but I still get the error.

![screen.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/6e02e400-50b4-11ea-8be4-33583f3a4100.png)

### What is expected ?

No error should happen, as the module exists, and it is also loaded fine if I go to the page manually, without server side rendering.

### What is actually happening?

The serverside rendering cannot find the module

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10294">#c10294</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't investigate without reproduction
