### ISSUE TITLE
Error: Path variable [contenthash:7] not implemented in this context: fonts/[contenthash:7].eot

### ISSUE THREAD

**Issue by mikemarsian** [nuxt/nuxt.js#6979]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/mikemarsian/daily-fashion](https://github.com/mikemarsian/daily-fashion)

### Steps to reproduce

1) Build for production: npm run production
2) See the error

### What is expected ?

Build for production should succeed

### What is actually happening?

/home/mike/job/daily-fashion/node_modules/@nuxt/webpack/node_modules/webpack/lib/TemplatedPathPlugin.js:45
				throw new Error(
				^

Error: Path variable [contenthash:7] not implemented in this context: fonts/[contenthash:7].eot
    at fn (/home/mike/job/daily-fashion/node_modules/@nuxt/webpack/node_modules/webpack/lib/TemplatedPathPlugin.js:45:11)
    at fn (/home/mike/job/daily-fashion/node_modules/@nuxt/webpack/node_modules/webpack/lib/TemplatedPathPlugin.js:33:16)

### Additional comments?

The conversation in this ticket https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/763 suggests that downgrading webpack to a version pre 4.3 could help. But given it's an internal dependency of nuxt.js, I'm not sure how to do achieve that, as an workaround. I've added this question on StackOverflow about this: https://stackoverflow.com/questions/60267756/how-to-downgrade-the-webpack-version-used-by-nuxt-js

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10295">#c10295</a>)</em></sub></div>

**Comment by danielroe** [comment]
@mikemarsian Does it make a difference if you change the font filename? (See https://nuxtjs.org/api/configuration-build/#filenames).

**Comment by mikemarsian** [comment]
I managed to fix the error by forcing upgrade on all the libraries in package.json
