### ISSUE TITLE
extractCss build option doesn't preload the extracted styles

### ISSUE THREAD

**Issue by mfrascati** [nuxt/nuxt.js#6980]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[http://localhost](http://localhost)

### Steps to reproduce

Setting the option
  build: { extractCSS: true }
in the rendered html we have
<link type="stylesheet" href="...">

Since it's meant to be use as an alternative to cpu consuming js bundled scripts, I suppose the css should be preloaded, but the generated tag is missing the rel="preload" as="style" attributes.

This way we can only choose between high js parsing time and late loaded css, which are both a problem for seo!

Did I miss how to fix it or is an issue?

### What is expected ?

<link type="preload" as="style" href="...">

### What is actually happening?

<link type="stylesheet" href="...">

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10296">#c10296</a>)</em></sub></div>

**Comment by delrueba** [comment]
### Alternative reproduction link
https://verwerkingsregisterqa.stad.gent/ 

### Repository
https://github.com/StadGent/nuxt_site_verwerkingsregister

**Comment by JohnMica** [comment]
strange thing indeed 
if I use `shouldPreload` nothing happens
if i use `shouldPrefetch` all defined resources are prefetched (style, script, font)
```
  render: {
    bundleRenderer: {
      shouldPreload: (file, type) => {
        return ['script', 'font', 'style'].includes(type)
      },
      shouldPrefetch: (file, type) => {
        return ['style', 'font'].includes(type)
      }
    },
```

i've tried also with no render prop (using nuxt default) but is has the same behaviour = no preload on any css / js chunks.

**Comment by Mohib834** [comment]
Hey, do we have the fix ? I am too stuck on the same thing.

**Comment by JohnMica** [comment]
Vuetify would need to update the way they play with the CSS in order to fix this, or you specify treeShaking- false and load the full CSS to the page (kind of a bloated solution) but nothing we can do about it yet. 
It’s CSS-in-JS magic ...

**Comment by Mohib834** [comment]
@JohnMica, I don't think setting treeShaking to false is a good option as I am overriding a lot of vuetify variables. Guess we have to wait for its solution.

**Comment by nachogarcia** [comment]
Same thing is happening to me using bootstrap-vue and extractCss.

Some styles that I have in a component and have nothing to do with any library are being extracted and included in a link with no prefetch, alongside many others. So I'm not sure is bootstrap-vue's fault.

Disclaimer.vue:
```
...
<style lang="scss" scoped>
#cookie-disclaimer {
...
```

`<link rel="stylesheet" href="/_nuxt/14bf0016ef0c11e18016.css">` :
```
#cookie-disclaimer[data-v-66268938]{background-color:#f7f7f7}@media (min-width:576px){#cookie-disclaimer .row[data-v-66268938]{margin:2rem}}#cookie-disclaimer .text[data-v-66268938]{font-size:13px;color:#3a3a3a}#cookie-disclaimer[data-v-66268938] .enableCookies .btn{border-color:#000;width:190px}@media (max-width:991.98px){#cookie-disclaimer[data-v-66268938] .btn.md{padding-right:0;margin-right:-20px}}@media (max-width:991.98px){#cookie-disclaimer .cta-container[data-v-66268938]{display:flex;justify-content:center}}.cookies-message[data-v-66268938] *{color:#3a3a3a}.cookies-message[data-v-66268938] a{text-decoration:underline}.cookies-message[data-v-66268938] p{margin-bottom:0}
```

**Comment by urbgimtam** [comment]
Any news on this matter? It's becoming slightly more important due to the web-vital metrics used by Google.
It appears as a recommended suggestion on the LightHouse report.
