### ISSUE TITLE
asyncData not working/not called in page component

### ISSUE THREAD

**Issue by payalord** [nuxt/nuxt.js#6981]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/asyncdata-not-working-cr51b](https://codesandbox.io/s/asyncdata-not-working-cr51b)

### Steps to reproduce

asyncData not working/not called in page component:
```
export default {
  data: function () {
    return {
      url: 'test'
    }
  },
  methods: {
    async asyncData ({ params, req }) {
      console.log('Test')
      if (process.server) {
        return { url: 'https://' + req.headers.host + '/' + params.slug }
      } else {
        return { url: 'https://' + window.location.host.split(':')[0] + '/' + params.slug }
      }
    }
}}
```

### What is expected ?

asyncData will be called on page load each time, client and server (refresh same page included, not only navigate to page through nuxt-link)

### What is actually happening?

url data value isn't changed at all. no console.log message at all too. So i suppose it's just not called at all might be.

### Additional comments?

Or am I got it wrong and asyncData works only on server side?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10298">#c10298</a>)</em></sub></div>

**Comment by fadonascimento** [comment]
Try to use like this:
```
export default {
  async asyncData ({ params, req }) {
    console.log('Test')
    if (process.server) {
      return { url: 'https://' + req.headers.host + '/' + params.slug }
    } else {
      return { url: 'https://' + window.location.host.split(':')[0] + '/' + params.slug }
    }
  }
  data: function () {
    return {
      url: 'test'
    }
  }
}```

See More: https://nuxtjs.org/guide/async-data/

**Comment by payalord** [comment]
@fadonascimento my bad lol, i put it into the methods. While it is just a part of component property. Thanks for helping.
