### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by rust-rs** [nuxt/nuxt.js#6984]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[localhost:3000](localhost:3000)

### Steps to reproduce

$ npm run dev

### What is expected ?

Server to run as expected

### What is actually happening?

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x37e1698b1dd9 <Object map = 0x37e146d34e61>
    0: builtin exit frame: defineProperty(this=0x37e16989cdf9 <Object map = 0x37e146d30221>,0x37e177764411 <Object map = 0x37e146d32981>,0x37e17ae87921 <String[#4]: size>,0x37e1777640c1 <SafeMap map = 0x37e146d37391>,0x37e16989cdf9 <Object map = 0x37e146d30221>)

    1: copyProps(aka copyProps) [0x37e177763f91] [internal/per_context/primordials.js:32] [bytecode=0x37e1698b5371 ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200219.160016.3168.0.001.json
Node.js report completed
 1: 0x10007e9b3 node::Abort() [/usr/local/bin/node]
 2: 0x10007eb37 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x100176337 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1001762d3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1002fa485 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x1002fbb54 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 7: 0x1002f8a27 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x1002f6a0d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100302124 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10030219f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1002d6c33 v8::internal::Factory::NewDescriptorArray(int, int, v8::internal::AllocationType) [/usr/local/bin/node]
12: 0x1004f2a8b v8::internal::DescriptorArray::CopyUpToAddAttributes(v8::internal::Isolate*, v8::internal::Handle<v8::internal::DescriptorArray>, int, v8::internal::PropertyAttributes, int) [/usr/local/bin/node]
13: 0x1004ca702 v8::internal::Map::CopyAddDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [/usr/local/bin/node]
14: 0x1004d1440 v8::internal::Map::TransitionToAccessorProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, int, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [/usr/local/bin/node]
15: 0x1004c443b v8::internal::LookupIterator::TransitionToAccessorProperty(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [/usr/local/bin/node]
16: 0x1004a524b v8::internal::JSObject::DefineAccessor(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [/usr/local/bin/node]
17: 0x1004a4dbd v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor(v8::internal::Isolate*, v8::internal::LookupIterator*, bool, v8::internal::PropertyDescriptor*, v8::internal::PropertyDescriptor*, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::Handle<v8::internal::Name>) [/usr/local/bin/node]
18: 0x1004a41fd v8::internal::JSReceiver::OrdinaryDefineOwnProperty(v8::internal::LookupIterator*, v8::internal::PropertyDescriptor*, v8::Maybe<v8::internal::ShouldThrow>) [/usr/local/bin/node]
19: 0x1004a3e57 v8::internal::JSReceiver::OrdinaryDefineOwnProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDescriptor*, v8::Maybe<v8::internal::ShouldThrow>) [/usr/local/bin/node]
20: 0x10021f165 v8::internal::Builtin_Impl_ReflectDefineProperty(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
21: 0x100930d99 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
22: 0x1008b12e4 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
23: 0x1008b12e4 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[1]    3166 abort      npm run dev

### Additional comments?

Node.js version : 12.13.1

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10301">#c10301</a>)</em></sub></div>

**Comment by lihbr** [comment]
Hi @rust-rs ,

According to your error it looks like your system does not have enough memory to run the Node server (I'm just guessing).

By default on a 64-bit OS Node assumes that you have at least 1.5GB available for it to run. If you have less then you should try running the `nuxt` command this way (found [here](https://stackoverflow.com/a/55547893)):
```bash
# `1024` is the amount of memory allocated...
$ node --max-old-space-size=1024 node_modules/nuxt/bin/nuxt.js
```

(For the sake of testing I also want to let you know that I did try to reproduce your issue on Node.js `12.13.1` using Nuxt `2.11.0` but I did not encountered any error, running Windows 10 w/ 16GB memory)

**Comment by rust-rs** [comment]
Hi @lihbr 

Thank you for your reply, I solved the memory issue, but there's still the "ECONNREFUSED 127.0.0.1:8000" error. (See screenshot) can't figure out why. 


<img width="1201" alt="Screenshot 2020-02-21 at 11 27 52" src="https://user-images.githubusercontent.com/10800660/75026498-5d4ac000-549d-11ea-9035-7ff58d1f0e38.png">

**Comment by lihbr** [comment]
Well, that could be due to quite a lot of things, perhaps you can share more context about it? (OS, nuxt.config.js, env variables, etc.)

Also have you tried accessing the dev server though other hosts? On _some_ OS `localhost` is not really equal to `127.0.0.1`, you can also try using your private IPV4 to connect to the server.
