### ISSUE TITLE
Router tree generation different between OSs (Ubuntu/macOS)

### ISSUE THREAD

**Issue by victorgarciaesgi** [nuxt/nuxt.js#6991]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/zealous-ardinghelli-2610p](https://codesandbox.io/s/zealous-ardinghelli-2610p)

### Steps to reproduce

I have this file structure: 
![bug nuxt.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/92eb6570-54ac-11ea-b377-297ef0b732e8.png)

When building a production bundle localy on macOS 10.15.3, the generated `router.js` is fine and as expected

```js
{
      path: "",
      component: _07db9c7c,
      name: "index"
    }, {
      path: "communication",
      component: _0f75dec6,
      name: "index-communication"
    }, {
      path: "content",
      component: _17fb9be9,
      name: "index-content"
    }, {
      path: "statistics",
      component: _1256e1e3,
      children: [{
        path: "",
        component: _60459bb4,
        name: "index-statistics"
      }, {
        path: "analytics",
        component: _0591ecda,
        name: "index-statistics-analytics"
      }]
    }, {
      path: "users",
      component: _417c0bf8,
      name: "index-users"
    }
```

This is the content of `statistics.vue` file, with a tab component to swich between childs

```vue
<template>
  <div class="flex column w100">
    <Container class="h-center p-5 p-w-10 nowrap nogrow w-between">
      <h2>{{ selectedTab ? selectedTab.label : '' }}</h2>
      <Tabs :tabs="tabs" :selected.sync="selectedTab" />
    </Container>
    <div class="flex column">
      <transition name="page" mode="out-in">
        <NuxtChild />
      </transition>
    </div>
  </div>
</template>
```

### What is expected ?

When I do a nuxt build on Ubuntu, I want the router tree to be the same as it is locally, with children correctly generated

### What is actually happening?

This is the the generated ouput of `router.js` on an Ubuntu machine after a nuxt build

```js
{
      path: "",
      component: _5feafe74,
      name: "index"
    }, {
      path: "Communication",
      component: _b3c7cd50,
      name: "index-communication"
    }, {
      path: "Content",
      component: _4c3dabfb,
      name: "index-Content"
    }, {
      path: "statistics",
      component: _035c3b98,
      name: "index-statistics"
    }, {
      path: "Statistics",
      component: _66230091,
      name: "index-Statistics"
    }, {
      path: "Users",
      component: _1cc6f88a,
      name: "index-Users"
    }, {
      path: "statistics/analytics",
      component: _ea183430,
      name: "index-statistics-analytics"
    }
```

The children routes are removed are replaced by single routes, breaking the app ,all links and structure

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10305">#c10305</a>)</em></sub></div>

**Comment by matteo-rigon** [comment]
The Ubuntu output has capitalized path names, which is quite strange and most likely also the cause of the problem. Netlify uses Ubuntu 16.04 for builds and they work fine, so it must be something in your project or on your server.

**Comment by victorgarciaesgi** [comment]
@matteo-rigon It was a really frustrating bug, it somehow fixed itself when I changed the name of the parent route...
