### ISSUE TITLE
Asset Path not resolved using <object>

### ISSUE THREAD

**Issue by virtualbjorn** [nuxt/nuxt.js#6993]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

Add an svg to assets dir e.g '@/assets/svg/sample.svg' 
Use it like this
<object type="image/svg+xml" data="@/assets/svg/sample.svg"></object>

### What is expected ?

It is expected to be compiled and resolved like img:src

### What is actually happening?

It retains '@/assets/svg/sample.svg' 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10306">#c10306</a>)</em></sub></div>

**Comment by manniL** [comment]
Please provide more info and ideally a CodeSandbox or GH repo as preorudction
