### ISSUE TITLE
Allow dynamic routes based on filename

### ISSUE THREAD

**Issue by sqram** [nuxt/nuxt.js#6996]
### What problem does this feature solve?

Allows users to place dynamic pages where they want.
Removed the need to set up nginx (or any server) aliases and creating extended routes
in nuxt.config

Take the following code that generates dynamic routes
```
for (let model of models) {
  routes.push({
    route: `/groups/products/chairs/${model.name}`,
    payload: { model: modelJSON }   
  });
}
```

From the page structure:
```
pages/
  groups/
     products/
        chairs/
           _.vue
```

`nuxt generate` will output this to `dist/groups/products/chairs/silverchair/index.html`,
and we'd be able to access it by going to 
`http://example.com/groups/products/chairs/silverchair/`

However, if the site wants to alias that url so it's accessible   via `http://example.com/silverchair/`,
the page won't work because that page's route doesn't match the url. (and route aliases in Nuxt are not supported)

An elegant and flexible approach would be to let us which file to specify for the path when generating the routes, like so
```
{
    route: `/${model.name}`,
    file: '/_chairs.vue',
    payload: { model: modelJSON }   
  }
```

outputting:

```
dist/
     silverchair/
       index.html
     lawnchair/
        index.html
```

### What does the proposed changes look like?

Changes to the generate api:

```
{
    route: `/${model.name}`,
    file: '/_chairs.vue',
    payload: { model: modelJSON }   
  }
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10308">#c10308</a>)</em></sub></div>

**Comment by pimlie** [comment]
Couldnt you use the [router-extras-modules](https://github.com/nuxt-community/router-extras-module) to support this already?

**Comment by sqram** [comment]
@pimlie  yes, thank you. wasn't aware of the module. feel free to close this.

**Comment by sqram** [comment]
@pimlie 
Reopening because I don't think router-extras-modules works well for dynamic generated pages.

minimal example: [https://github.com/sqram/router-extended-example](https://github.com/sqram/router-extended-example)

**Comment by sqram** [comment]
Yep. Didn't even know such module existed.
