### ISSUE TITLE
npm run generate and dynamic routes

### ISSUE THREAD

**Issue by askeyt** [nuxt/nuxt.js#701]
Hi there,

I can't get dynamic routes to work with nuxt generate.. I must be missing something?

 - create the starter project (vue init nuxt/starter <project-name>)
 - add the folder/file "pages/posts/_id.vue"
 - npm run generate

the docs tell me I should get an error (Could not generate the dynamic route /posts/:id, please add the mapping params in nuxt.config.js (generate.routeParams).) 

But i don't get this error, its simply ignored and there is no file in the dist folder. Even if I do add the mapping params it is still ignored?

"npm run dev" works as expected

Thanks

**Comment by Atinux** [comment]
Hi, you may be looking an outdated documentation.

Please refer to https://nuxtjs.org/api/configuration-generate/#routes
