### ISSUE TITLE
Static Website v-on:click Doesn't Work

### ISSUE THREAD

**Issue by nicklenihan** [nuxt/nuxt.js#7026]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/nicklenihan/nuxt-vue-quiz](https://github.com/nicklenihan/nuxt-vue-quiz)

### Steps to reproduce

Generate a static website:

$ npm run generate
Upload contents of dist folder to Amazon S3 w/Cloudfront CDN in the root.

Navigate to:

https://yourdomain.com/quiz/index.html
Click on either the "YES" or "NO" button.

### What is expected ?

It is expected that clicking on either the "YES" or "NO" button leads to the next question in the quiz (there are 3 questions in total).

This expected behavior works perfectly on localhost:3000/quiz.

### What is actually happening?

When the "YES" or "NO" buttons are clicked nothing happens. There are no errors in the console and all .js files are loading from the server.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10330">#c10330</a>)</em></sub></div>

**Comment by matteo-rigon** [comment]
Mind providing a URL with the broken app? It really seems strange as it's just a counter

**Comment by nicklenihan** [comment]
Here is the webpage on Amazon S3 hosting:

https://allow-to-access.com/quiz/index.html

**Comment by matteo-rigon** [comment]
@nicklenihan The problem is that you are accessing `/quiz/index.html` instead of `/quiz/`.
While the latter works correctly, the former does not because `/quiz/index.html` does not correspond to any route available, so VueRouter does not know which component to load. Create a rewrite rule to always use urls without `/index.html`

**Comment by nicklenihan** [comment]
Wow. That totally works. I don't think a rewrite rule is needed, as just removing ```index.html``` seems to fix the problem and the page loads fine on Amazon.
