### ISSUE TITLE
Vue-Meta Doesn't Encode HTML Characters In 'generate'

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt.js#7027]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/hecktarzuli/vue-meta-generate-bug](https://github.com/hecktarzuli/vue-meta-generate-bug)

### Steps to reproduce

Clone repo
do a 'yarn generate'
View the home page source, notice the meta description still has the < > in the field.

Do a yarn build
yarn start
View the home page source, notice the meta description is properly encoded.

### What is expected ?

That fields are encoded the same using generate or build.

### What is actually happening?

Only 'build' encodes them.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10331">#c10331</a>)</em></sub></div>

**Comment by matteo-rigon** [comment]
It's because of the HTML minifier options. You can fix it with 
``` 
html: {
    minify: {
      collapseBooleanAttributes: true,
      decodeEntities: false, // <----------- Disable this option, Nuxt enables it by default
      minifyCSS: true,
      minifyJS: true,
      processConditionalComments: true,
      removeEmptyAttributes: true,
      removeRedundantAttributes: true,
      trimCustomFragments: true,
      useShortDoctype: true
    }
  },
```

**Comment by hecktarzuli** [comment]
@matteo-rigon I will give that a try, thank you!

**Comment by hecktarzuli** [comment]
That works as advertised, thanks!
