### ISSUE TITLE
<nuxt-link> not working with bootstrap-vue

### ISSUE THREAD

**Issue by yuruyuri16** [nuxt/nuxt.js#7030]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/embed/shy-resonance-q20q5?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/shy-resonance-q20q5?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

Start clicking in the Home and About nav items.

### What is expected ?

Change routes

### What is actually happening?

Nothing happens

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10336">#c10336</a>)</em></sub></div>

**Comment by matteo-rigon** [comment]
If you inspect your html, you can see

```html
<ul class="navbar-nav">
  <a href="/" class="nuxt-link-exact-active nuxt-link-active">
    <li class="nav-item">
      <a target="_self" href="#" class="nav-link">Home</a>
    </li>
  </a>
  <a href="/about" class="">
    <li class="nav-item">
      <a target="_self" href="#" class="nav-link">About</a>
    </li>
  </a>
</ul>
```

`<b-nav-item>` component already creates a link, and if using Nuxt creates a `<nuxt-link>` instead of a `<router-link>`. Your navbar can just be
```
<b-navbar-nav>
  <b-nav-item to="/">Home</b-nav-item>
  <b-nav-item to="/about">About</b-nav-item>
</b-navbar-nav>
```

**Comment by yuruyuri16** [comment]
Thank you so much.
