### ISSUE TITLE
mounted not working with pagination watchQuery: ['page']

### ISSUE THREAD

**Issue by alsemany** [nuxt/nuxt.js#7035]
### What problem does this feature solve?

How to let mounted scripts run after renderring the page with pagination or Query ? 
this is my codes like

`````
 mounted() {
    scripts_run_after_page_mounted()
  },
  watchQuery: ['page'],
`````

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10339">#c10339</a>)</em></sub></div>

**Comment by pimlie** [comment]
See https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram, you should be able to use the `updated` lifecycle hook

**Comment by alsemany** [comment]
thank you worked perfect by using `updated `
