### ISSUE TITLE
add name to generated files: name.hash.ext

### ISSUE THREAD

**Issue by titouandk** [nuxt/nuxt.js#7036]
### What problem does this feature solve?

It would be nice to be able to identify compiled files.

Files generated by nuxt looks like 9cdea4daa3ce167d5d79.js

It would be great if the filename contained also the chunk name (given by the cli with the `generate` command).

Examples of file names:

app.9cdea4daa3ce167d5d79.js
commons.app.10495323254f5f20727d.js
...

(Vuejs cli does this, except that they use "-" instead of "." in the filenames: chunk-vendors.62d72de1.js)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10342">#c10342</a>)</em></sub></div>

**Comment by pimlie** [comment]
You can customize the filenames by setting the `build.filenames` config option: https://nuxtjs.org/api/configuration-build/#filenames

**Comment by titouandk** [comment]
Thank you!

I think that this would be a good default setting tho, if it does not break anything.

**Comment by pi0** [comment]
In previous versions we were doing this but removed the name from chunk name for two reasons:

- Not invalidate caches if only a page rename (thus chunk name change) happens for maximum caching leverage
- Don't expose project internals to public deployments for maximum code confidentially

Indeed there are also enough reasons to add a name for perf and debug audit of production deployments and understand what each chunk does. There is a trade-off between "longer-term cache  + confidentially of code" vs "best DX for prod deployments". Personally I'm biased about this. Feel free closing or continue discussion :)

**Comment by titouandk** [comment]
Thank you, those are very interesting considerations ;)
