### ISSUE TITLE
axios drops `baseURL` when invoked via `fetch()`

### ISSUE THREAD

**Issue by selfagency** [nuxt/nuxt.js#7044]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://gitlab.com/musiciansbass/musiciansbass-app](https://gitlab.com/musiciansbass/musiciansbass-app)

### Steps to reproduce

I'm trying to use `fetch` in my component, but it never fires the dispatcher. If I put a `console` statement in there, it runs. But the dispatcher never goes.

```js
  async fetch({ store }) {
    try {
      await store.dispatch('content/getPage', 'home')
    } catch (err) {
      console.error(err)
    }
  }
```

This is my action:

```js
export const actions = {
  async getPage({ commit }, slug) {
    try {
      load(commit, true)
      const content = (await this.$axios.get(`Pages?slug=${slug}`)).data[0]
      commit('ADD_CONTENT', { slug, content })
      load(commit, false)
    } catch (err) {
      load(commit, false)
      return err
    }
  }
}
```

I've tried it with and without a `return` statement in the action. I've tried it with and without `{ root: true }` in the dispatch call. But I get nada. This, however, works just fine:

```js
  async mounted() {
    await this.$store.dispatch('content/getPage', 'home')
  }
```

What am I doing wrong, or is this a bug?

### What is expected ?

I expect the action to be dispatched

### What is actually happening?

Nothing, and there are no errors being thrown in either the browser or the terminal

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10347">#c10347</a>)</em></sub></div>

**Comment by zacharytyhacz** [comment]
Hello, I was looking into a similar problem, I found this related: https://github.com/nuxt/nuxt.js/issues/1693

Have you tried changing
```javascript
await store.dispatch('content/getPage', 'home')
```
to 
```javascript
// notice 'content/' is gone
await store.dispatch('getPage', 'home');
```
? 
Not sure why it would remove the name the 'path' of the store action but in that related issue the guy said it fixed his similar issue.

**Comment by selfagency** [comment]
That results in the error `[vuex] unknown action type: getPage`.

More oddly, if I just discovered that if I save the component with the original code above, it runs once via HMR, but once the page is refreshed, it never runs again.

**Comment by selfagency** [comment]
After doing some more debugging, it appears `fetch()` *is* dispatching my action, however, my call to `this.$axios.$get()` never comes back. If I call the same action from `mounted()` it works, but not `fetch()`. When I output `this` inside my action, however, `$axios` is there with its full object scope. So I'm at a loss for how to proceed.

**Comment by selfagency** [comment]
Ok, narrowed it down some more: I finally was able to catch what was happening. Axios was throwing a 404 error, but it was never publicly displaying the error despite my try/catch block. Now that I see what's happening, it appears that when dispatched via `fetch()` rather than `mounted()`, Axios no longer sees the `baseURL` in the Axios configuration, despite being there. The config URL is correct, but the URL it actually goes to `GET` has no `baseURL` prefixed. The final error is, `Invalid host: pages`, which is the name of my API route.

```
  response:
   { status: 404,
     statusText: 'Invalid host',
     headers:
      { 'access-control-allow-origin': '*',
        'access-control-expose-headers': 'access-control-allow-origin',
        date: 'Wed, 04 Mar 2020 19:31:59 GMT',
        connection: 'keep-alive',
        'transfer-encoding': 'chunked' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        baseURL: 'http://localhost:1337/',
        url: 'http://localhost:1337/Pages?slug=home',
        data: undefined },
     request:
      ClientRequest {
        domain: [Domain],
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'GET /Pages?slug=home HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nconnection: keep-alive\r\npragma: no-cache\r\ncache-control: no-cache\r\nupgrade-insecure-requests: 1\r\nuser-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1\r\naccept-encoding: gzip, deflate\r\naccept-language: en-US,en;q=0.9\r\ncookie: i18n_redirected=en; i18n_mb=en\r\nHost: localhost:1337\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/Pages?slug=home',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data: 'Invalid host: pages' } }
```

**Comment by selfagency** [comment]
I thought that the issue might be the way I had my environment variables configured. I had `API_URL` set to `http://localhost:1337`. So I split it up into `API_HOST` and `API_PORT` but got the same result. 😔

**Comment by selfagency** [comment]
Yeesh, even if I erase my env vars and manually specify my API endpoint URL in each call, it's *still* stripping out the host and port.

<img width="1103" alt="Screenshot 2020-03-04 15 14 40" src="https://user-images.githubusercontent.com/2541728/75919072-e31a2400-5e2a-11ea-893e-a238b1974ad2.png">

**Comment by selfagency** [comment]
If I try using `@nuxt/proxy`, same deal. It drops the endpoint from the API URL.
<img width="1083" alt="Screenshot 2020-03-04 15 36 01" src="https://user-images.githubusercontent.com/2541728/75920689-dcd97700-5e2d-11ea-90a6-135728b3e80d.png">

**Comment by zacharytyhacz** [comment]
Hmm, ok I see. In my projects, I can't use the `this.$axios` nuxtjs module in my `store/` files so I made an axios variable like this:
```javascript
// e.g. store/user.js
import axios from 'axios';

var $axios = axios.create({
	baseURL: process.env.API_HOST,
	withCredentials: true,
	headers: {
		'API-Key' : process.env.API_KEY,
		'Content-Type' : "application/json"
	},
});
```

I was still able to use my environmental variables by making sure they are set in the `nuxt.config.js`:

```javascript
env : {
	ADMIN_EMAIL: process.env.ADMIN_EMAIL,
	API_HOST: process.env.API_URL,
	API_KEY : process.env.VOXICARD_API_KEY,
}
```

Then I can use my created `$axios` variable in my store's functionality:
```javascript
// e.g. store/user.js
export const actions = {
    logout : function(state){
	    state.commit('authenicate',false);
    	    return $axios.get("/Logout/");
    }
};
```

**However,** if I have to use axios in multiple `store/` files, I have to do the same axios variable creation on each file. ( Haven't tried adding the `var $axios = axios.create()` in `store/index.js`

**Comment by selfagency** [comment]
I'm closing this ticket and have reopened it in the `nuxt-community/axios-module` repo [here](https://github.com/nuxt-community/axios-module/issues/340).

**Comment by selfagency** [comment]
Thanks @zacharytyhacz. Unfortunately, the problem doesn't seem to have anything to do with environment variables, as it's reproducible with FQDNs.
