### ISSUE TITLE
Single page application static resource fetching(absolute path instead of relative path) issue in scorm cloud

### ISSUE THREAD

**Issue by sudhakarselva** [nuxt/nuxt.js#7047]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/spa](https://github.com/nuxt/nuxt.js/tree/dev/examples/spa)

### Steps to reproduce

Build single page app and upload it to scorm cloud which there serve using uploaded dist folder index.html / 200.html so url will 
 
https://cloud.scorm.com/sandbox/content/courses/PN2CJ7YF2K/sc28f58e4bf-c89d-4f48-acd8-9aeb4a1dabea/0/200.html

but application is not loading since its trying to fetch resource from https://cloud.scorm.com/_nuxt/*.js . please refer below image
![static404.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/c84c78e0-5d16-11ea-a7ca-3d3edca6bb8b.png)

but if i change paths from index.html from /_nuxt to _nuxt its fetching files https://cloud.scorm.com/sandbox/content/courses/PN2CJ7YF2K/sc28f58e4bf-c89d-4f48-acd8-9aeb4a1dabea/0/_nuxt/*.js

as show in below image. is it related to some relative path issues ?

![path resolved.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/82efdc50-5d17-11ea-a7ca-3d3edca6bb8b.png)
![fetch correct.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/8a474920-5d17-11ea-a7ca-3d3edca6bb8b.png)

### What is expected ?

fetch resourses from https://cloud.scorm.com/sandbox/content/courses/PN2CJ7YF2K/sc28f58e4bf-c89d-4f48-acd8-9aeb4a1dabea/0/_nuxt/*.js instead of this https://cloud.scorm.com/_nuxt/*.js . bcuz my file is hosted inside 0/ folder

### What is actually happening?

resourses are fetching from https://cloud.scorm.com/_nuxt/*.js instead of folder where it is hosted  (inside 0 named folder )https://cloud.scorm.com/sandbox/content/courses/PN2CJ7YF2K/sc28f58e4bf-c89d-4f48-acd8-9aeb4a1dabea/0/_nuxt/*.js

### Additional comments?

reproduction url is nuxt single page app example from nuxt but create nuxt app with spa mode with latest version also same problem

tried publicPath but  url is dynamic (autogenerate by scorm so not way of knowing early) https://cloud.scorm.com/sandbox/content/courses/PN2CJ7YF2K/sc28f58e4bf-c89d-4f48-acd8-9aeb4a1dabea/0/

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10350">#c10350</a>)</em></sub></div>

**Comment by sudhakarselva** [comment]
temporily fixed by setting base router path to 'app/' and then created new app folder and moved _nuxt to app folder . inside generate index.html src look like this <script type="text/javascript" src="app/_nuxt/67621d882ab63209123a.js"></script>

**Comment by sinayra** [comment]
Besides doing what @sudhakarselva has said, I've also modified the publicPath to consider relative links, as #2892 explained.
This is my next.config.js in the end of the day
```
build: {
    extend(config, { isDev, isClient }) {
      if (!isDev) {
        // relative links, please.
        config.output.publicPath = './_nuxt/'
      }
      return config
    },
  },
  router: {
    base: 'app/'
  },
```
