### ISSUE TITLE
Nuxt+Vuetify testing: "multiple instances of Vuetify"

### ISSUE THREAD

**Issue by garyo** [nuxt/nuxt.js#7058]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/garyo/nuxt-jest-bug-001](https://github.com/garyo/nuxt-jest-bug-001)

### Steps to reproduce

* check out bug report repo
* cd nuxt-jest-bug-001
* yarn install
* yarn test

... then you should see several pages of errors, starting with: 
```
   console.error node_modules/vuetify/dist/vuetify.js:40260
      [Vuetify] Multiple instances of Vue detected
      See https://github.com/vuetifyjs/vuetify/issues/4068

      If you're seeing "$attrs is readonly", it's caused by this
    console.error node_modules/vue/dist/vue.common.dev.js:630
      [Vue warn]: Error in beforeCreate hook: "Error: Vuetify is not properly initialized, see https://vuetifyjs.com/getting-started/quick-start#bootstrapping-the-vuetify-object"

      found in

      ---> <VApp>
             <DefaultLayout>
               <Anonymous>
                 <Root>
    console.error node_modules/vue/dist/vue.common.dev.js:1893
      Error: Vuetify is not properly initialized, see https://vuetifyjs.com/getting-started/quick-start#bootstrapping-the-vuetify-object
```

### What is expected ?

Test should run and pass

### What is actually happening?

Test gives many pages of errors

### Additional comments?

The app is a straight Nuxt app, just created. Using latest versions of everything. I added a build + render test in `tests/pages.spec.js`, and that is what is failing. I used a variant of the test setup in https://nuxtjs.org/examples/testing -- the only difference is I load the actual Nuxt config rather than a plain default config.

The app works fine normally, both when built and deployed, and when run with `yarn dev`. It's only the test that fails.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10366">#c10366</a>)</em></sub></div>

**Comment by andriyudatama** [comment]
i alse experienced the same issue. 
After following this tutorial to deploy to firebase:
https://dev.to/kiritchoukc/deploy-nuxt-on-firebase-4ad8

I was able to build and deploy, but if I run yarn dev it shows error

**Comment by devpascoe** [comment]
> i alse experienced the same issue.
> After following this tutorial to deploy to firebase:
> https://dev.to/kiritchoukc/deploy-nuxt-on-firebase-4ad8
> 
> I was able to build and deploy, but if I run yarn dev it shows error

lol same. hmmm

**Comment by dylan-moore** [comment]
I have this issue as well. I opened an issue in the @nuxtjs/vuetify repo but I believe it to be an issue in nuxt rather than vuetify or the nuxt plugin for it.

This happens even when I use vuetify as a vue plugin (rather than the nuxt config route)
