### ISSUE TITLE
Regular Expression Denial of Service vulnerability

### ISSUE THREAD

**Issue by ram-you** [nuxt/nuxt.js#7061]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://www.npmjs.com/advisories/1488](https://www.npmjs.com/advisories/1488)

### Steps to reproduce

npm install

### What is expected ?

No vulnerabilities

### What is actually happening?

found 2 moderate severity vulnerabilities in  Path =  nuxt > @nuxt/webpack > webpack-bundle-analyzer > acorn 

### Additional comments?

Upgrade acorn to version 7.1.1 or later.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10368">#c10368</a>)</em></sub></div>

**Comment by ram-you** [comment]
Issue about that on webpack-bundle-analyzer:
https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/337

**Comment by manniL** [comment]
This code won't be shipped in your application, so no worries! ☺️

Quote from https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/337

> As webpack-bundle-analyzer is a development-only tool, a denial of service security vulnerability is not relevant for us.

Please follow the mentioned issue for further updates. We will bump the dependency as soon as it's resolved (and you probably can also on your own if it's a minor or patch update via you package manager ☺️)
