### ISSUE TITLE
Codesandbox fails to build - using default template

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt.js#7064]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/stoic-sanderson-lotbj?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/stoic-sanderson-lotbj?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

The code sandbox fails to build. If I run the default codesandbox, and save a file, so it will recompile, it fails:

    Cannot find module 'vue-client-only' from '/sandbox'

    ERROR in ./node_modules/vue-client-only/dist/vue-client-only.common.js
Module build failed: Error: ENOENT: no such file or directory, open '/sandbox/node_modules/vue-client-only/dist/vue-client-only.common.js'
   
   ERROR in ./node_modules/vue-meta/dist/vue-meta.esm.browser.js
Module build failed: Error: ENOENT: no such file or directory, open '/sandbox/node_modules/vue-meta/dist/vue-meta.esm.browser.js'

Not sure why.

### What is expected ?

Build should run

### What is actually happening?

Build fails

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10371">#c10371</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't reproduce
<img width="660" alt="image" src="https://user-images.githubusercontent.com/640208/78784272-54f30980-79a5-11ea-9788-6e6bf25d6b15.png">
