### ISSUE TITLE
在 build 中添加了 filenames 希望在上线后的js文件引用后添加  ?[contenthash]

### ISSUE THREAD

**Issue by baymax2** [nuxt/nuxt.js#7068]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Steps to reproduce

1.在`nuxt.config.js` 添加
```
export default  {
	...
	build: {
		...
		filenames: {
		  app: ({ isDev }) => isDev ? '[name].js' : '[name].js?[contenthash]',
		  chunk: ({ isDev }) => isDev ? '[name].js' : '[name].js?[contenthash]',
		  css: ({ isDev }) => isDev ? '[name].css' : '[name].css?[contenthash]'
		},
		...
	}
}
```
![WeChat0a96543c4a344e1579fdaa8fbeeb789f.png](http://ww1.sinaimg.cn/large/006pfdsdly1gcovvckuqxj313y0lmte5.jpg)
2.保存并执行 `npm run build`
3.执行 `npm run start`
4.发现只有 `css`文件在引入时添加了 `?[contenthash]`
![WX20200310-155620.png](http://ww1.sinaimg.cn/large/006pfdsdly1gcovz45himj30ep0bbwg1.jpg)
5.js文件未能在引入时添加 `?[contenthash]`
![WX20200310-155753.png](http://ww1.sinaimg.cn/large/006pfdsdly1gcow0r955vj30ek0cldh9.jpg)

### What is expected ?

js文件在引入时添加 `?[contenthash]`

### What is actually happening?

js文件未能在引入时添加 `?[contenthash]`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10372">#c10372</a>)</em></sub></div>

**Comment by umrons** [comment]
try `analyze: false`

**Comment by baymax2** [comment]
Thanks for your help, I tried to change `` analyze "to" false "and it works fine
