### ISSUE TITLE
i18n should not be like this?

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#707]
As mentioned in the i18n example https://github.com/nuxt/nuxt.js/blob/master/examples/i18n/middleware/i18n.js

```
...
const locale = params.lang || 'en'
...
```
So the lang is in url params like `http://xxxx/en/xxxxxx`

But I think the lang should be identified from the client browser, not as a param.

So  I change this to:
```
const locale = (window.navigator.language || window.navigator.browserLanguage).toLowerCase() || 'en'
```
But I got error `window is not defiend`, because this code is run in server.

So what should I do to get the lang from user's client? thanks!

**Comment by bimohxh** [comment]
I try to change this to 

```
let locale = req.headers['accept-language'].split(',')[0].toLocaleLowerCase() || 'en'
```
It works!

**Comment by alexchopin** [comment]
In this example, we use i18n with route params, but you can use your example if you want to handle i18n without route params.

**Comment by sudhir600** [comment]
I have the same problem. My app have two languages. for switching the language i am proving a drop-down list, whatever selected, lang code like 'en' is being saved in local storage. 
And after that i am getting this `const locale = (localStorage.getItem('locale)) || 'en'`
but i am getting same error-  `localStorage is not defiend`
also i am trying to refresh page with this.$router.push('/') but i am gettign error like this -

**Comment by clarkdo** [comment]
You need wrap `localStorage ` with `process.client` because that there is not `localStorage ` in server side.

```js
if (process.client) {
  locale = (localStorage.getItem('locale)) || 'en'
}
```

**Comment by sudhir600** [comment]
I @clarkdo, Thank you so much. its working fine now. But got another issue.  
once i change the locale, its need to refresh the page so that new locale can take effect.
I have 2 concern.
1. is it possible to change the locale (using` i18n`) without page refresh
2. if not how to refresh. i am using the `$route.push('/') `but its don't work.

**Comment by clarkdo** [comment]
You can have a look at my demo repo which is using request.header['language'] to differ locale:

https://github.com/clarkdo/hare/blob/dev/client/plugins/i18n.js

And also https://github.com/nuxt/nuxt.js/tree/master/examples/i18n which is using different routes to differ.

**Comment by rlataguerra** [comment]
Just a hint to help people : You can acces accept-language header with

app.context.req.headers['accept-language']
