### ISSUE TITLE
Middleware with `undefined` second argument causes deployment version of app to hang

### ISSUE THREAD

**Issue by jaysaurus** [nuxt/nuxt.js#7076]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/jaysaurus/nuxt-middleware-issue](https://github.com/jaysaurus/nuxt-middleware-issue)

### Steps to reproduce

create a normal nuxt project.
add a .js in middleware with a second argument as below

```javascript
export default function (ctx, test) {
  test = 123
  console.log('some middleware output:', test)
}
```

set the middleware property on the active layout to the given middleware

run `npm run build`
run `npm start`

navigate to the localhost address in your browser.

### What is expected ?

you should be able to see the landing page of the website at the address.  you should also see the output of the middleware's console.log in the respective shell that is running the programme/development bar of your browser

### What is actually happening?

the page hangs with no warning or explanation (the console message is displayed however)

### Additional comments?

The same behaviour doesn't seem to happen if the test argument is defined with a value:

```javascript
export default function (ctx, test = 123) {
  console.log('some middleware output:', test)
}
```

but is also present if you explicity supply `undefined` as below:

```javascript
export default function (ctx, test = undefined) {
  test = 123
  console.log('some middleware output:', test)
}
```

I have an instance in another project that sprung this issue on me by surprise. I'm using an argument as a shorthand for a variable declaration, I like to mark it as `= undefined` so other developers know I'm going to do something with it in the function.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10380">#c10380</a>)</em></sub></div>

**Comment by Geminii** [comment]
Hi 😀
I will try to reproduce and fix it if needed to purpose a PR 😉 
Thanks for the reproduction 😀
