### ISSUE TITLE
Custom publicPath breaks href

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#708]
I saw this issue https://github.com/nuxt/nuxt.js/issues/612 , but due to it's closed I guess nobody see my response there. 

When I set `publicPath: 'ss'` then my links (prefetch)  to .js files breaks like this, and page doesn't renders correct:

![issue](https://cloud.githubusercontent.com/assets/26049747/25994903/e276345c-36dd-11e7-95e7-75d615246de4.png)

"nuxt": "^0.10.7"

**Comment by hendrysadrak** [comment]
try `publicPath: 'ss/' `

**Comment by kodekrendel** [comment]
@hendrysadrak thanks, it's worked.

**Comment by kodekrendel** [comment]
I reopen this issue, since I found out that adding slash is only help when I use `generate`. When I `buld` and `start` the path is broken again!

**Comment by Atinux** [comment]
Use `publicPath: '/ss/'` @kodekrendel
