### ISSUE TITLE
can’t establish a connection to the server in dev mode

### ISSUE THREAD

**Issue by madnadyka** [nuxt/nuxt.js#7080]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/private_project](https://github.com/private_project)

### Steps to reproduce

I use nuxt.js in server with docker and have problems in dev mode.

I refresh page and sometimes have error.

### What is expected ?

Page is loading

### What is actually happening?

I have error in browser "can’t establish a connection to the server", but nuxt is working. After I wait ~30-60 sec and refresh again the page is loading. Then after sometime this issue happens again.

Nuxt is not restarted during this, problem in any browser, restart doesn't fix the problem.

### Additional comments?

Dockerfile:

FROM node:10
RUN mkdir /config
RUN mkdir /web
WORKDIR /web
RUN mkdir src
COPY ./package*.json .
COPY ./nuxt.config.js .
RUN npm i -g npm && npm i -g --force yarn
RUN yarn install

CMD [ "yarn", "dev" ]

package.json:
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "author": "Nadezhda Karpova <nadyka@bitaps.com>",
   "license": "ISC",
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "prod": "yarn build && yarn start"
  },
  "dependencies": {
    "nuxt": "2.11.0",
    "@nuxtjs/dotenv": "1.4.1",
    "@nuxtjs/axios": "5.9.5",
    "cookie-parser": "1.4.4",
    "cookieparser": "0.1.0",
    "@nuxtjs/proxy": "1.3.3",
    "body-parser": "1.19.0",
    "canvas": "2.6.1",
    "highcharts":"8.0.0",
    "highcharts-vue":"1.3.5",
    "vue":"2.6.11"
  }
}

And screenshot of project structure in attach:
![Снимок экрана 2020-03-13 в 19.10.05.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/c2e1c300-653c-11ea-8543-eb00a34e11e3.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10384">#c10384</a>)</em></sub></div>

**Comment by manniL** [comment]
We need more info to help you, e.g. a repository.

**Comment by madnadyka** [comment]
Hello!

Please see the example of repository!
https://github.com/hugguh/test_nuxt <https://github.com/hugguh/test_nuxt>


I have found that the problem not only of dev mode, in prod mode I have it too. Also I have found that the problem because of nginx (without it everything is working good) - when I refresh page 3-5 times I have msg that browser can’t establish a connection to the server.

Please see nginx config file in repository, I have changed it according the instruction https://nuxtjs.org/faq/nginx-proxy/ <https://nuxtjs.org/faq/nginx-proxy/> , but it doesn’t solve the problem.

**Comment by madnadyka** [comment]
The problem was fixed after I updated nginx version to latest!

Thank you!
