### ISSUE TITLE
IOS error to upload input file when captured from mobile camera on nuxt js 2.11.0

### ISSUE THREAD

**Issue by natashagp** [nuxt/nuxt.js#7081]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/not-working-prxd5](https://codesandbox.io/s/not-working-prxd5)

### Steps to reproduce

Click to select a file to upload, and with an IOS phone, take a picture with the camera and click submit.
If the nuxt js version is 2.0.0 is works correctly.
But with the newest version 2.11.0, it doesn't work, it gives a cors error when i try to use fetch and if i try to use axios to make the upload it gives a network error, but on both cases it doesn't show an error on the server.

### What is expected ?

It's expected that when the user takes a picture with his phone (IOS), the file gets uploaded to my server, which happens on Desktop and Android.

### What is actually happening?

If the nuxt js version is 2.0.0 is works correctly.
But with the newest version 2.11.0, it doesn't work, it gives a cors error when i try to use fetch and if i try to use axios to make the upload it gives a network error, but on both cases it doesn't show an error on the server.
It only happens on IOS devices.
I'm using an Iphone 7 to test, but i also tested on an Iphone X.

![fetch_error2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0d86b090-653e-11ea-8543-eb00a34e11e3.png)
![axios_error2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0b0d4c20-653e-11ea-8543-eb00a34e11e3.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10385">#c10385</a>)</em></sub></div>

**Comment by enoter** [comment]
This is not a problem in iOS and maybe in NuxtJS, because I checked it on my MacBook and Android, but I get the same error.

Does your server set the Access-Control-Allow-Origin header?

**Comment by natashagp** [comment]
Yes, I even tried setting Access-Control-Allow-Origin to '*', but I get the same error (Origin is not allowed by Access-Control-Allow-Origin).

**Comment by natashagp** [comment]
It was an error with nginx.
It's working now, thanks for the help.

**Comment by MamatovUmar** [comment]
what exactly was the error? I also have this error
