### ISSUE TITLE
page`s loading:false not work

### ISSUE THREAD

**Issue by Mrchen128** [nuxt/nuxt.js#7083]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://segmentfault.com/q/1010000019957375](https://segmentfault.com/q/1010000019957375)

### Steps to reproduce

Setting false for the page loading property does not take effect ,The loadbar still appears and does not disappear

### What is expected ?

Loading can disappear during page jump

### What is actually happening?

The loading bar appears and never disappears

### Additional comments?

thanks

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10390">#c10390</a>)</em></sub></div>

**Comment by Geminii** [comment]
Hi 😀
Could you add a reproduction link like github repository or sandbox please ? 
I will try to reproduce and purpose a PR if needed 👍 

Thanks 😀

**Comment by faaktap** [comment]
This is still a problem, but solution is 
  <v-progress-linear    v-show="loading"
      indeterminate       color="grey darken-2"
    ></v-progress-linear>
and mark this.loading as true or false to show info to user
newnuxt@1.0.1 E:\NodeModules\real\freshNuxt
+-- @nuxtjs/composition-api@0.31.0
| `-- nuxt@2.15.8 deduped
+-- nuxt-use-sound@1.0.8
| `-- @nuxtjs/composition-api@0.20.2
|   `-- nuxt@2.15.8 deduped
`-- nuxt@2.15.8
