### ISSUE TITLE
How enable Hubspot form in SSR production build ?

### ISSUE THREAD

**Issue by fabien-f** [nuxt/nuxt.js#7087]
Hi,

I try to use the hubspot form script in my website but it dont't show up when i use `nuxt build` and `nuxt start` commands in universal mod. When i use the `nuxt` it's ok.

I load the script in nuxt.config.js file :

```
script: [
      {src: 'https://js.hsforms.net/forms/v2.js'},
    ]
```

and I put the form's script in <client-only> tag :

```
            <client-only>
              <script>
                hbspt.forms.create({
                  portalId: "1234",
                  formId: "1234"
                });
              </script>
            </client-only>
```

I don't know what is the difference between production and development mod that create this bug. I tried to disable the optimization too but that not resolved the problem…

Thanks for your help !

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10396">#c10396</a>)</em></sub></div>

**Comment by AntonMoskalchenko** [comment]
I have this bug too

**Comment by Soviut** [comment]
I solved this by using the `target` property passed to `hbspt.forms.create()` based on a solution I found [here](https://community.hubspot.com/t5/APIs-Integrations/Customise-selected-option-in-a-form-embed-based-on-previous-page/m-p/372224#M36630).

First, in my template I set

```html
  <div id="embedded-form" />
```
Then in the code for that page

```javascript
  mounted() {
    window.hbspt.forms.create({
      portalId: '...',
      formId: '...',
      target: '#embedded-form', // notice we target the div id
    })
  },
```

You'll need to prefix the call to `hbspt.forms.create()` with `window` since `hbspt` does not exist within the context of `mounted()`.

**Comment by sintj** [comment]
> I solved this by using the `target` property passed to `hbspt.forms.create()` based on a solution I found [here](https://community.hubspot.com/t5/APIs-Integrations/Customise-selected-option-in-a-form-embed-based-on-previous-page/m-p/372224#M36630).
> 
> First, in my template I set
> 
> ```
>   <div id="embedded-form" />
> ```
> 
> Then in the code for that page
> 
> ```js
>   mounted() {
>     window.hbspt.forms.create({
>       portalId: '...',
>       formId: '...',
>       target: '#embedded-form', // notice we target the div id
>     })
>   },
> ```
> 
> You'll need to prefix the call to `hbspt.forms.create()` with `window` since `hbspt` does not exist within the context of `mounted()`.

Hi, i tried to implement your solution but it in my window object there's no `hbspt`. Did you import the script bundle in nuxt config in any particular way?
