### ISSUE TITLE
Separate Builder#supportedExtensions

### ISSUE THREAD

**Issue by kissge** [nuxt/nuxt.js#7091]
### What problem does this feature solve?

`Builder`#`supportedExtensions` is used in three different things, namely: resolving middlewares, resolving layouts, and routing.
I wanted to remove 'js' entry in this variable so that I can exclude .js files under `pages` directory, but still wanted to use js files in middlewares.
However, with current implementation, this is not possible.

### What does the proposed changes look like?

Separate supportedExtensions into four:
```js
defaultSupportedExtensions = ['vue', 'js', ...]
middlewareSupportedExtensions = defaultSupportedExtensions
layoutSupportedExtensions = defaultSupportedExtensions
routeSupportedExtensions = defaultSupportedExtensions
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10401">#c10401</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. You can create a `.nuxtignore` file in the project and add `pages/*.js` to ignore `.js` extension files from there. Alternatively, you can use `ignore` option from `nuxt.config`:

```js
export default {
  ignore: [
    'pages/*.js'
  ]
}
```

Docs: https://nuxtjs.org/api/configuration-ignore/

**Comment by kissge** [comment]
Looks nicer! Thanks.
