### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by MLDMoritz** [nuxt/nuxt.js#7095]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[http://example.com](http://example.com)

### Steps to reproduce

npm install

### What is expected ?

npm install working fine

### What is actually happening?

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nuxt/builder@2.12.0

### Additional comments?

I changed nothing, CI fails with this error since the 2.12.0 version.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10402">#c10402</a>)</em></sub></div>

**Comment by gerasimvol** [comment]
same

**Comment by arctouch-lenonbottameli** [comment]
Same here, done nothing, just the building failing

**Comment by buglavecz** [comment]
Now is working fine.

**Comment by gerasimvol** [comment]
indeed, it's working now

**Comment by pi0** [comment]
NPM global CDN propagation problem as always :)
