### ISSUE TITLE
Issues with new fetch

### ISSUE THREAD

**Issue by MLDMoritz** [nuxt/nuxt.js#7096]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[http://example.com](http://example.com)

### Steps to reproduce

fetch.client.js throws this error:

Cannot read property 'nbFetching' of undefined

this is caused by this:

```
async function $fetch() {
  this.$nuxt.nbFetching++
}
```

This doesn't work when globalName in `nuxt.config.js` is changed to whatever.

### What is expected ?

Should be something like this[this.config.globalName].nbFetching++

### What is actually happening?

calling this.$nuxt directly

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10403">#c10403</a>)</em></sub></div>

**Comment by MLDMoritz** [comment]
As a workaround I created a plugin which does:

`Vue.prototype.$nuxt = Vue.prototype.$vehicl`

**Comment by pi0** [comment]
Hi. This will be fixed in next patch release ASAP
