### ISSUE TITLE
New Fetch is Not Executed for Modified Watched Queries

### ISSUE THREAD

**Issue by Viscid** [nuxt/nuxt.js#7099]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://github.com/Viscid/NewFetchRepro](https://github.com/Viscid/NewFetchRepro)

### Steps to reproduce

Install.
Navigate to /oldFetch to see old fetch behaviour, with query string changes that are watched executing the fetch component method. 
Navigate to /newFetch, where the only change is not providing a context argument (thus utilizing the new fetch method.) Changes to the query string do not execute (console.logging 'Fetching!')

### What is expected ?

For query strings that are watched with WatchQuery, the fetch method should execute upon change.

### What is actually happening?

Fetch is not executing when query strings watched by WatchQuery are changed. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10405">#c10405</a>)</em></sub></div>

**Comment by MLDMoritz** [comment]
https://nuxtjs.org/api/pages-fetch/#listening-to-query-string-changes
