### ISSUE TITLE
Data cannot be requested without "/ api" following the real API address

### ISSUE THREAD

**Issue by 2015-lizaiyang** [nuxt/nuxt.js#7102]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://codesandbox.io/s/eager-pond-ds13u](https://codesandbox.io/s/eager-pond-ds13u)

### Steps to reproduce

1. Wrap axios
2. Configure the proxy in nuxt.config.js
2. Demo1 variable = request data using this.$axios.get()
3. Demo2 variable = use encapsulated axios to request data

### What is expected ?

I want the demo2 variable to request data

### What is actually happening?

In fact, the demo2 variable did not request data
![ECB3380B-FCFA-4612-B4F6-A98290893888](https://user-images.githubusercontent.com/21666293/76946239-b3950c80-693e-11ea-9ada-e762673d5a7b.png)

### Additional comments?

This happens only if there is no/API behind the real API address.
Data can be requested if the real API address is followed by/API.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10407">#c10407</a>)</em></sub></div>

**Comment by manniL** [comment]
Because in your 2nd way of calling the api, you don't prepend `/api` at all.

Either use `/api` as [`global prefix`](https://axios.nuxtjs.org/options#prefix-host-and-port) or append it manually. ☺️

**Comment by manniL** [comment]
`data` is undefined in the 2nd way because you use `$get` and don't need to acces `.data` (as when you use `get`). See https://axios.nuxtjs.org/helpers#fetch-style-requests for the differences 😋

**Comment by 2015-lizaiyang** [comment]
thank
