### ISSUE TITLE
When the website is opened from Safari Favorites page, the title on the browser tab won't change while switching between pages

### ISSUE THREAD

**Issue by Reedo0910** [nuxt/nuxt.js#7105]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

1. Add a site which is built with nuxt to Favorites in Safari on Mac
2. Click on the shortcut (added in Step 1) on Safari Favorites page to open the website
3. Click on a nuxt-link on the page to switch to a new page
4. The website title on the Safari tab remains the same

### What is expected ?

The website title on the Safari tab will change while switching between pages

### What is actually happening?

The website title on the Safari tab remains the same

### Additional comments?

Safari version: 13.0.5 (15608.5.11)
macOS version: 10.15.3

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10412">#c10412</a>)</em></sub></div>

**Comment by MLDMoritz** [comment]
Safari is the new Internet-Explorer. Better get with apple support because they probably cook their own soup.
