### ISSUE TITLE
html miss <base> when router.base just only have a slash 

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxt.js#712]
When I just setting router.base with "/"
the html element can't find `<base>` element 
It should have a`<base href="/">`

I tried use a simple project test vue-meta 
I just set `base.href = '/'` html work fine .
![screenshot_12](https://cloud.githubusercontent.com/assets/7247064/26012587/976eb3d0-3787-11e7-9475-1e4be01c689d.png)

so , I thinks this belong nuxt.js issue .
I tried find problem in nuxt.js source but can't find ....

I propose this issus that because I have a project , in dev test is need a sub folder .
but production don't , so , my image url is like `./img/image.jpg`
so , if html miss base in head , that will break the image .

for now , if I change router.base to `'/'` , I need add `<base href="/">` in app.html template front `{{ HEAD }}` everytime ... ummm... even I already write it in my CI/CD ...

maybe if can fix this issue will be best .
thanks .

**Comment by ausir0726** [comment]
my personal cognition

setting router.base = '/' and without setting router.base is different .

but seems it the same on nuxt.js at this moment .

**Comment by alexchopin** [comment]
Hi @ausir0726,
This is the vue-router base option: https://router.vuejs.org/en/api/options.html.
If you need to add head tag `base`, you need to create it like you did with the head option in nuxt.config.js.

**Comment by Atinux** [comment]
Hi @ausir0726 

It's here in the code https://github.com/nuxt/nuxt.js/blob/master/lib/render.js#L105

The base '/' creates problem in some cases if it exists, that's why we don't create directly.

**Comment by ausir0726** [comment]
@Atinux can we add the base element when we define router.base clear ? thanks  .

if not , I will choose respect.

**Comment by ausir0726** [comment]
@Atinux update my opinion .

Sorry for waste you valuable time .

**Comment by Atinux** [comment]
You're right @ausir0726, when base is defined in `nuxt.config.js`, we should add `<base href="/">`.

Will update it for the next version.

**Comment by ausir0726** [comment]
@alexchopin @Atinux 
thanks you brothers understanding  .
![ed3b3d25d801a279673e36ae808534d4](https://cloud.githubusercontent.com/assets/7247064/26119129/d0407bd4-3a9e-11e7-9bb2-80288f968268.jpg)

**Comment by Atinux** [comment]
Thanks to you @ausir0726 for your precious help!
