### ISSUE TITLE
when instance returns form server side, it can't be checked for instanceof in props type

### ISSUE THREAD

**Issue by uncleGena** [nuxt/nuxt.js#7120]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://github.com/uncleGena/nuxt-instanceof](https://github.com/uncleGena/nuxt-instanceof)

### Steps to reproduce

return data from asyncData with object instantiated from some class (MyInstance). And pass it as prop to other component, check that object int type (type: MyInstane) and it will error in console. 'Invalid prop: type check failed for prop "inst". Expected MyInstance, got Object'

### What is expected ?

check for instance as it should

### What is actually happening?

return simple object, not instance of class

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10431">#c10431</a>)</em></sub></div>

**Comment by manniL** [comment]
This is due to serialization. We can't "store" properties like the instance when transferring values from server to the client.
