### ISSUE TITLE
Loading indicator customization not working for default loader

### ISSUE THREAD

**Issue by FelixRe0** [nuxt/nuxt.js#7123]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://codesandbox.io/s/wild-fast-ptg64?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/wild-fast-ptg64?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

Set the following nuxt config:

export default {
  mode: "spa",
  loadingIndicator: {
    name: "default",
    color: "#f39151",
    background: "#033641"
  }
};

### What is expected ?

Nuxt loadingindicator uses the background and color values for the loading view. 

### What is actually happening?

The default.html loaded does not use the color/background values set in nuxt config. Additionally "circle" is not the default value for loadingIndicator.name as stated by the documentation.

### Additional comments?

The documentation is wrong, by stating the default value is circle (It actually is "default") : https://nuxtjs.org/api/configuration-loading-indicator#__layout

link to docs: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/views/loading/default.html

Removing visibility and opacity and adding the background property should enable customizing the default loading indicators background:

#nuxt-loading {
  background: <%= options.background %>;
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  animation: nuxtLoadingIn 10s ease;
  -webkit-animation: nuxtLoadingIn 10s ease;
  animation-fill-mode: forwards;
  overflow: hidden;
}

Currently it also uses options.loading to style the animation which should be changed to the loading indicator color.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10433">#c10433</a>)</em></sub></div>

**Comment by Geminii** [comment]
Hi @FelixRe0 
I reproduced your bug. It seems it missing `background` into the default template of loading indicator. 
However, there is no effect to remove visibility and opacity ;) 

I will purpose a PR as soon as possible and give you feedbacks about it.
