### ISSUE TITLE
Nuxt runs in higher version than expected

### ISSUE THREAD

**Issue by Turajek** [nuxt/nuxt.js#7124]
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

I'm running 'npm run start' or 'npm run dev'
![bug.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/71fb1020-6dc7-11ea-a5ef-258e759396d0.png)

### What is expected ?

I expect Nuxt in version 2.4.1

### What is actually happening?

I have Nuxt in version 2.12.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10434">#c10434</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @Turajek. Actually, it is not a bug but normal behavior how semver with npm/yarn works.

- `"nuxt": "^2.4.0"`: means any nuxt version higher than 2.4.0 which is available but less than 3.0.0
- `"nuxt": "~2.4.0"`: means any nuxt version higher than 2.4.0 which is available but less than 2.5.0
- `"nuxt": "2.4.0"`: means exactly version `2.4.0` <== This is what you should set in package.json

BTW why you need to pin version to 2.4.0 and not using the latest?
