### ISSUE TITLE
webpack打包nuxtjs后无法运行

### ISSUE THREAD

**Issue by xvivx** [nuxt/nuxt.js#7127]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://www.no.com](https://www.no.com)

### Steps to reproduce

入口js：

```js
const express = require('express');
const { Nuxt } = require('@nuxt/core');

const app = express();

async function start() {
  const config = require('../nuxt.config.js');

  config.dev = false;

  const nuxt = new Nuxt(config);

  await nuxt.ready();

  app.use(nuxt.render);
}


 start().then(() => {
    app.listen(3000);
  });
```

webpack:

```js
import path from 'path';
import webpack from 'webpack';

export default {
  target: `node`,
  mode: `production`,
  context: path.resolve(''),
  entry: {
    server: [`./server/ali-fc.js`], // 入口js，上面的文件
  },
  output: {
    path: path.resolve(`server`),
    filename: `[name].js`,
    libraryTarget: 'commonjs',
    chunkFilename: 'chunks/[name].[chunkhash:5].js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              presets: ['@vue/app']
            }
          }
        ]
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    })
  ],
  externals: {
    canvas: `canvas`,
    jsdom: `jsdom`
  },
  node: {
    __dirname: false,
    global: false,
    fs: false,
    path: false,
  }
};
```

### What is expected ?

能正常运行

### What is actually happening?

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number

### Additional comments?

为什么要这样打包nuxtjs，因为使用了阿里云的函数计算服务，代码托管在函数计算里，函数计算要求上传的包不能超过50M，所以需要打包后上传，但是打包后无法运行。

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10436">#c10436</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @xvivx from the description this is not clear why you need a webpack config file but error getting is related to this line: 

>   context : path . resolve ( '' ) , 

Please create a new issue with more details. Feel free opening in Chinese if easier :)
