### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by tenjojeremy** [nuxt/nuxt.js#713]
After I run npm build and open the html file in the dist folder i get the following:

![example](https://cloud.githubusercontent.com/assets/25231946/26021660/5667c768-3760-11e7-8827-f49b3db08bda.PNG)

Am I missing a step?

Thank you in advance.

**Comment by ausir0726** [comment]
if you deploy to static hosting   you should use npm generate . and upload file include dist

**Comment by ausir0726** [comment]
as I know firebase hosting is static hosting .

**Comment by tenjojeremy** [comment]
Hi @ausir0726,

npm run generate did the trick. 

Thank you.
