### ISSUE TITLE
Base href not set in SPA mode

### ISSUE THREAD

**Issue by arildm** [nuxt/nuxt.js#7134]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://codesandbox.io/s/spa-base-href-2761c](https://codesandbox.io/s/spa-base-href-2761c)

### Steps to reproduce

1. Click the link to the subpage `/foo/bar`.

### What is expected ?

The page should have `<base href="/">` in `<head>` and the image should load correctly on both pages.

### What is actually happening?

There's no `<base>` tag and the image on `/foo/bar` is not loaded.

### Additional comments?

The base tag is only added if the mode is set to universal.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10443">#c10443</a>)</em></sub></div>

**Comment by Geminii** [comment]
Hi @arildm ! 
I saw on the code that `<base href=""> meta` is only available into ssr mode but not in SPA. 
So the `base` attribute isn't insert into `<head>` section. 

It's not indicate into the official documentation (https://fr.nuxtjs.org/api/configuration-router#base). 
I will purpose a PR :)

**Comment by Geminii** [comment]
PR has been accepted and it will be available on next release 😉
