### ISSUE TITLE
When routing is switched, the component will be rendered two times

### ISSUE THREAD

**Issue by jo0ger** [nuxt/nuxt.js#714]
Nuxt version: latest(0.10.7)

Some of my project structures are like this：

![image](https://cloud.githubusercontent.com/assets/16385416/26026588/9f9a7090-3830-11e7-9529-97ec978595ce.png)

layout1:

``` vue
<div>
    <nuxt :key="$route.path"/>
  </div>
```

layout2:

``` vue
<div>
    <nuxt />
  </div>
```

page1:

``` js
export default {
   layout: 'layout1'
}
```

page2:

``` js
export default {
  layout: 'layout2',
  created () {
    console.log('Page2 is created')
  },
  mounted () {
    console.log('Page2 is mounted')
  }
}
```

If I switch from route page1 to page2, the page2 will be rendered two times

![image](https://cloud.githubusercontent.com/assets/16385416/26026649/d8be4fda-3831-11e7-8088-a95721be1340.png)

I guess the key in page1 caused this problem

If I remove the key from page1, the render becomes normal

**Comment by alexchopin** [comment]
Hi, yes it's due to the key. `<nuxt/>` doesn't allow props.
