### ISSUE TITLE
Bug when using property decorators

### ISSUE THREAD

**Issue by jonthemiller** [nuxt/nuxt.js#7143]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/jonthemiller/nuxt-ts-array-deserialize](https://github.com/jonthemiller/nuxt-ts-array-deserialize)

### Steps to reproduce

Clone the repo, `npm install` then `npm run dev`. Visit http://localhost:3000 to see the exception.

### What is expected ?

Within the `asyncData` function, an instance of `Obj` should be returned from the `JsonConvert.deserializeObject` call. It should have items populated and each should be an instance of the `Item` class.

### What is actually happening?

An exception is thrown because the property decorators are not compiled/served correctly. 

### Additional comments?

This was originally opened as a bug to nuxt/typescript: https://github.com/nuxt/typescript/issues/274. After working with Kevin Marrec in that thread though, it appears to be a webpack issue within Nuxt.

I have another branch on that repo that reproduces the bug without any TS - just using the decorators on plain JS objects: https://github.com/jonthemiller/nuxt-ts-array-deserialize/tree/no-ts

I have also tried running the logic on `mounted` instead of `asyncData` and it works as expected. When done within `created` or `asyncData` is when the code fails.

Lastly I put the code in a vue-cli project and it works as expected as well: https://github.com/jonthemiller/vue-cli-json2typescript

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10448">#c10448</a>)</em></sub></div>

**Comment by jonthemiller** [comment]
This still happens on the latest release of Nuxt - 2.12.2

**Comment by manniL** [comment]
cc @kevinmarrec

**Comment by kevinmarrec** [comment]
@manniL No idea what's going on, I've already put time into the issue. Me and @jonthemiller figured out it was not working even without TypeScript. It has to do with how `asyncData` is handled. Maybe @Atinux could help 🤷‍♀️

**Comment by Atinux** [comment]
Well the issue here is that we serialize the data from asyncData with `devalue`, you should not use classe instances right inside `asyncData` but instead keep raw js object and create their instances in `beforeMount`

**Comment by jonthemiller** [comment]
I get that behavior for the things returned from `asycData`, but this is also happening for objects/services/etc. called from within `asyncData`.

In the example repo, the error gets thrown when trying to instantiate the object, which happens well before returning the object from the function (where it would get serialized into a raw js object). Do you have an idea for why the code works fine within `mounted` but not within `created` or `asyncData`?
