### ISSUE TITLE
HTML comment between text nodes causes DOM rendering error

### ISSUE THREAD

**Issue by SimBioT1954** [nuxt/nuxt.js#7150]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/s/brave-shockley-1js8l](https://codesandbox.io/s/brave-shockley-1js8l)

### Steps to reproduce

Just type HTML comment between any text nodes:
```
<div>
text1 <!- comment --> text2
</div>
```

### What is expected ?

Nothing at all

### What is actually happening?

Error:

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside < p >, or missing < tbody >. Bailing hydration and performing full client-side render.

If the HTML comment is located in some component then other components on the same Page might be duplicated without any reason! It means double mounted() calls in those components.

### Additional comments?

Spent 3 days to find the bug!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10454">#c10454</a>)</em></sub></div>

**Comment by zhangchen915** [comment]
You can add `comments`  attribute to `template` tag, like this `<template comments>`.The reason for this problem is that vue resolves to two vnodes when it meets a comment.
