### ISSUE TITLE
Nuxt lazy loads all the layouts (with resourceHints: false and prefetchLinks: false)

### ISSUE THREAD

**Issue by Guito** [nuxt/nuxt.js#7154]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://github.com/Guito/nuxt-lazy-loading-layout](https://github.com/Guito/nuxt-lazy-loading-layout)

### Steps to reproduce

Yarn dev
Open the website
Open developer tools
Check that the scripts and css of lazy-layout.vue are loaded (for example .text-style { color:red }

### What is expected ?

Layouts should not be prefetched

### What is actually happening?

Layouts are being prefetched

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10456">#c10456</a>)</em></sub></div>

**Comment by Atinux** [comment]
You need to use [build.splitChunks](https://nuxtjs.org/api/configuration-build#splitchunks) in your `nuxt.config.js` to lazy load your layouts, Nuxt does not do it by default.

```js
build: {
  splitChunks: {
    layouts: true
  }
}
```
