### ISSUE TITLE
splitChunks throws error in 2.12.1

### ISSUE THREAD

**Issue by sqram** [nuxt/nuxt.js#7159]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/s/ecstatic-meninsky-t134j](https://codesandbox.io/s/ecstatic-meninsky-t134j)

### Steps to reproduce

Create a fresh Nuxt app:

1. yarn create nuxt-app foo
2. Add the following to build section of  `nuxt.config.js`

splitChunks: {
      layouts: true
    },

### What is expected ?

Split layout chunks. 

### What is actually happening?

Console throws the error:
![2020-03-30-182431_885x123_scrot.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/44ebdc50-72d5-11ea-9781-812e4aa8afce.png)

Browser shows error:
Cannot read property 'props' of undefined

![2020-03-30-181536_943x223_scrot.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/00106890-72d4-11ea-9781-812e4aa8afce.png)

Note the chunck name in the console error `_6f6c098b` is shown in the stack trace.

### Additional comments?

I did not try this in 2.12.0
Only in 2.12.1

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10461">#c10461</a>)</em></sub></div>

**Comment by Atinux** [comment]
This is fixed by https://github.com/nuxt/nuxt.js/pull/7139

Could you confirm by using [nuxt-edge](https://www.npmjs.com/package/nuxt-edge) ?

**Comment by pi0** [comment]
Hi! This is dup of #7133. Should be resolved by [v2.12.2](https://github.com/nuxt/nuxt.js/releases/tag/v2.12.2)
