### ISSUE TITLE
How to generate profile.json

### ISSUE THREAD

**Issue by guumaster** [nuxt/nuxt.js#716]
I'd like to pass `webpack-bundle-analyzer` but I'm not sure how to change build step with `webpack` to output profile info into `profile.json`, needed to see pass the analyzer. Any clue?

**Comment by pi0** [comment]
What about using [webpack-stats-plugin](https://github.com/FormidableLabs/webpack-stats-plugin) (By adding plugin within build.extend function in nuxt config ?

**Comment by guumaster** [comment]
Thanks! Adding the plugin works great. But for a single step, I used `webpack-bundle-analyzer` directly. Like this: 

```
// nuxt.config.js
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin

module.exports = {
...
  build: {
    plugins: [
      new BundleAnalyzerPlugin({
        analyzerMode: 'static',
        generateStatsFile: true,
        openAnalyzer: false,
        logLevel: 'info'
      })
    ],
...
``` 

Also, anyway I've tried, i get a console warning `Could't find any javascript bundles in provided stats file` but the report and stats file are generated anyway.
