### ISSUE TITLE
Use new fetch() hook with component cache cause hydration error

### ISSUE THREAD

**Issue by cron13** [nuxt/nuxt.js#7161]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/modest-blackwell-uvtxt](https://codesandbox.io/s/modest-blackwell-uvtxt)

### Steps to reproduce

go to https://codesandbox.io/s/modest-blackwell-uvtxt and refresh browser

### What is expected ?

cache works properly

### What is actually happening?

got error Mismatching childNodes vs. VNodes

### Additional comments?

I am trying to get data in a component using a new fetch() hook.
The DOM of the component is cached normally, but the data received with fetch() does not put into the cache, hence there is a problem with hydration

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10467">#c10467</a>)</em></sub></div>

**Comment by aaronransley** [comment]
Running into the same issue. Using @nuxtjs/component-cache module along with `serverCacheKey` method on a given component causes client-side hydration errors.

The SSR appears to run fine and returned source is correctly cached, but client-side hydration considers the markup out of sync and forces a re-run of the `fetch` method, thus invalidating the purpose of the caching.

**Comment by cron13** [comment]
As far as I was able to deal with the problem - the problem is not related to nuxt. vuejs just does not cache the state of variables, I don’t think that it can be easily fixed, at least you need to fix vuejs code, but not nuxt

**Comment by aaronransley** [comment]
@cron13 Did you implement any workarounds for this issue? I'm playing around with the `serverPrefetch` method provided by Vue at this point, but it feels like stumbling in the dark.

**Comment by cron13** [comment]
No, it seems to that it is impossible to implement a simple hack, Need to edit the vuejs library

**Comment by cron13** [comment]
The guys from vuejs said that this is not a bug, they are advised to write to them to discord or stackoverfow :-(

**Comment by ding-js** [comment]
Will this issue be resolved by vue 3 & nuxt 3?
