### ISSUE TITLE
Pass `renderContext` to `vue-renderer:ssr:templateParams` hook

### ISSUE THREAD

**Issue by eunjae-lee** [nuxt/nuxt.js#7163]
### What problem does this feature solve?

Currently only `templateParams` is passed to `vue-renderer:ssr:templateParams` hook.
What if we also pass `renderContext` to it?

My `nuxt.config.js` looks like this:

```js
hooks: {
  "vue-renderer": {
    context(renderContext) {
      renderContext.rendered = (context) => {
        context.myState = { this: { is: { my: "state" } } };
      };
    },
  }
}
```

I need to inject something to context at the time when `renderContext.rendered()` is called.
FYI, renderContext.rendered() is called [here](https://github.com/eunjae-lee/vue/blob/ssr-async-context-rendered/packages/vue-server-renderer/build.dev.js#L9188).
It's
- AFTER the component tree is rendered (including serverPrefetch)
- and BEFORE actually rendering the component tree into HTML.

So let's say I injected `myState` into the renderContext. Then later I want to do like the following:

```js
hooks: {
  "vue-renderer": {
    context(renderContext) {
      renderContext.rendered = (context) => {
        context.myState = { this: { is: { my: "state" } } };
      };
    },
    ssr: {
      templateParams(templateParams, renderContext) {
        templateParams.APP += `window.__MY_STATE__  = ${JSON.stringify(renderContext.myState)};`;
      }
    }
  }
}
```

Does it make sense?
I tried to think of other ways to achieve this, but IMO this is the proper way.

### What does the proposed changes look like?

At here: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L213:L213

We just need to replace
```js
await this.serverContext.nuxt.callHook('vue-renderer:ssr:templateParams', templateParams)
```
with
```js
await this.serverContext.nuxt.callHook('vue-renderer:ssr:templateParams', templateParams, renderContext)
```

Please let me know if you agree with this change. I can send a PR for this 🙂
Thank you and have a nice day.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10469">#c10469</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi, @eunjae-lee thanks for the proper explanation.

I think it it totally makes sense to make context available for template params and should be harmless :)

Please go on for making PR :+1:
