### ISSUE TITLE
ERROR  Renderer resources are not loaded

### ISSUE THREAD

**Issue by weihao** [nuxt/nuxt.js#7165]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/](https://codesandbox.io/)

### Steps to reproduce

yarn build
yarn start

### What is expected ?

> cross-env NODE_ENV=production ts-node -T -P tsconfig.server.json server/index.ts

 READY  Server listening on http://localhost:8081

### What is actually happening?

> cross-env NODE_ENV=production ts-node -T -P tsconfig.server.json server/index.ts

 ERROR  Renderer resources are not loaded! Please check possible console errors and ensure dist (/var/app/current/.nuxt/dist/server) exists.

  at VueRenderer.renderRoute (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4440:17)
  at VueRenderer.renderRoute (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4428:21)
  at nuxtMiddleware (node_modules/@nuxt/server/dist/server.js:140:20)

### Additional comments?

I don't know how to use https://codesandbox.io/

My app is working fine locally, but this error blocked me from deploying my nuxt application to Elastic Beanstalk.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10471">#c10471</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @weihao. As log shows, this is most likely a deployment error. Can you somehow ensure `/var/app/current/.nuxt/dist/server` exists in production server with ssr js files?

**Comment by weihao** [comment]
> Hi @weihao. As log shows, this is most likely a deployment error. Can you somehow ensure `/var/app/current/.nuxt/dist/server` exists in production server with ssr js files?

<img width="700" alt="Screen Shot 2020-04-01 at 7 33 56 PM" src="https://user-images.githubusercontent.com/31719556/78196240-c71c9900-744f-11ea-84ed-12d22148d219.png">
@pi0  Hi Pooya, I pulled the failed deployment from beanstalk and it seems all the js files are there.

**Comment by pi0** [comment]
@weihao Would you please also possiblity share server/index.ts?🙈

**Comment by weihao** [comment]
> @weihao Would you please also possiblity share server/index.ts?🙈
Sure😄 
```
import { AkadiaServer } from './defined'
import consola from 'consola'

const { Nuxt, Builder } = require('nuxt')
const nuxtConfig = require('../nuxt.config')

const isHeroku = process.env.npm_lifecycle_event === 'start-heroku'
const isProduction = process.env.NODE_ENV === 'production'
nuxtConfig.dev = !isProduction

const nuxt = new Nuxt(nuxtConfig)
let { host, port } = nuxt.options.server

if (isHeroku) {
  nuxt.options.server.host = host = '0.0.0.0'
  nuxt.options.server.port = port = process.env.PORT || port
}
process.env.HOST = host
process.env.PORT = port
process.env.BASE_URL = port === '80' || port === '443'
  ? `${port === '443' ? 'https' : 'http'}://${host}`
  : `http://${host}:${port}`

nuxt.ready(consola)
  .then(() => nuxtConfig.dev ? new Builder(nuxt).build() : Promise.resolve())
  .then(() => require('./app').start(nuxt))
  .then((akadia: AkadiaServer) => {
    akadia.express.use(nuxt.render)
    akadia.express.listen(port, host)
    consola.ready({
      message: `Server listening on ${process.env.BASE_URL}`,
      badge: true
    })
  })
  .catch(console.error)
```

**Comment by pi0** [comment]
@weihao Can you try this:

```js
import path from 'path'
import { loadNuxt, build } from 'nuxt'

const isHeroku = process.env.npm_lifecycle_event === 'start-heroku'
const isProduction = process.env.NODE_ENV === 'production'
const isDev = !isProduction
const rootDir = path.resolve(__dirname, '..')

const port = process.env.PORT || 3000
const host = (isHeroku || isProduction) ? '0.0.0.0' : '127.0.0.1'

process.env.HOST = host
process.env.PORT = port
process.env.BASE_URL = `${port === '443' ? 'https' : 'http'}://${host}`

getNuxt().then(nuxt => startServer(nuxt)).catch(error => {
  console.error(error)
  process.exit(1)
})

async function startServer(nuxt) {
  const app = await import('./app')
  const akadia = await app.start(nuxt)
  akadia.express.use(nuxt.render)
  akadia.express.listen(port, host)
  consola.ready({
    message: `Server listening on ${process.env.BASE_URL}`,
    badge: true
  })
}

async function getNuxt() {
  if (isDev) {
    const nuxt = await loadNuxt({ for: 'dev', rootDir })
    await build(nuxt)
    return nuxt
  }

  const nuxt = await loadNuxt({ for: 'start', rootDir })
  return nuxt
}
```

**Comment by weihao** [comment]
> @weihao Can you try this: (untested maybe need some changes)
> 
> Main points:
> 
> * Using new programmatic API (2.12.0)
> * Explicitly pass `rootDir` relative to serer.js which seems to be in a directory inside rootDir
> 
> ```js
> import path from 'path'
> import { loadNuxt, build } from 'nuxt'
> 
> const isHeroku = process.env.npm_lifecycle_event === 'start-heroku'
> const isProduction = process.env.NODE_ENV === 'production'
> const isDev = !isProduction
> const rootDir = path.resolve(__dirname, '..')
> 
> const port = process.env.PORT || 3000
> const host = (isHeroku || isProduction) ? '0.0.0.0' : '127.0.0.1'
> 
> process.env.HOST = host
> process.env.PORT = port
> process.env.BASE_URL = `${port === '443' ? 'https' : 'http'}://${host}`
> 
> getNuxt().then(nuxt => startServer(nuxt)).catch(error => {
>   console.error(error)
>   process.exit(1)
> })
> 
> async function startServer(nuxt) {
>   const app = await import('./app')
>   const akadia = await app.start(nuxt)
>   akadia.express.use(nuxt.render)
>   akadia.express.listen(port, host)
>   consola.ready({
>     message: `Server listening on ${process.env.BASE_URL}`,
>     badge: true
>   })
> }
> 
> async function getNuxt() {
>   if (isDev) {
>     const nuxt = await loadNuxt({ for: 'dev', rootDir })
>     await build(nuxt)
>     return nuxt
>   }
> 
>   const nuxt = await loadNuxt({ for: 'start', rootDir })
>   return nuxt
> }
> ```

After some tweaking and testing, nuxt app is up and running :) 

Thanks, closing the issue since it is not related to nuxt but a configuration error.

**Comment by yoyo837** [comment]
I deleted `@babel/core` from `package.json` and it worked again.

![image](https://user-images.githubusercontent.com/6134547/81369103-2727ee80-9124-11ea-9e50-23dc0751ef7e.png)
