### ISSUE TITLE
Can't import bootstrap javascript modules. Issue with jQuery 

### ISSUE THREAD

**Issue by fdouchant** [nuxt/nuxt.js#7169]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/fdouchant/nuxt-bootstrap-issue](https://github.com/fdouchant/nuxt-bootstrap-issue)

### Steps to reproduce

- Get my source (bare project) from github.
- start server
- Error will be shown in terminal and navigator

### What is expected ?

To import bootstrap module : 

import Modal from 'bootstrap/js/dist/modal'

I tried to do the same with a vue-cli bare project and it works just fine...

### What is actually happening?

Cannot read property 'jquery' of undefined
...
var version = $.fn.jquery.split(' ')[0].split('.');

### Additional comments?

I don't wanna use bootstrap-vue for such a small feature... I tried importing using a plugin, using nuxt.config.js, nothing will do... Any one as the same issue ?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10474">#c10474</a>)</em></sub></div>

**Comment by fdouchant** [comment]
![EPrSu.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/de278580-7510-11ea-8c00-097da850d77d.png)

**Comment by fdouchant** [comment]
Found the solution... after couple of days struggling  :-|

Seems like bootstrap can't be loaded server-side... therefore I have to import the package in the mounted function of the component juste like that :

```
mounted() {
    const Modal = require('bootstrap/js/dist/modal')
    this.modal = new Modal(this.$el)
  },
```

Tough one (for a beginer like I am :-P)

**Comment by manniL** [comment]
Hey @fdouchant 👋🏻

A few suggestions:

1. I highly suggest to *not* use jQuery with Vue. It's not necessary at all and clutters your final build 😋
2. If you want to use Bootstrap and Vue, there is https://bootstrap-vue.js.org/ - a component library, that has almost all Bootstrap-Features in component form

Hope that helps as well!
