### ISSUE TITLE
 Mixin being executed multiple times in the server side if using Vue.mixin.

### ISSUE THREAD

**Issue by shivgarg5676** [nuxt/nuxt.js#7171]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/shivgarg5676/vue-jss](https://github.com/shivgarg5676/vue-jss)

### Steps to reproduce

Just boot up the server and run localhost:3000 and refresh the page for 3-4 times.

exact stets
1. npm install
2. npm run dev
3. run localhost:3000
4. refresh the page for 2-3 times and check server logs.

### What is expected ?

Code in plugins/jss/plugin.js should execute once per component i.e created hook should execute once per component. 

### What is actually happening?

Code in plugins/jss/plugin.js is executing n times for nth request to the server. i.e created hook is being triggered once for 1st request for each component, twice for each component for the second request and thrice for each component for the third request and so on.

### Additional comments?

1. I am using Vue.mixin in the plugins/jss/plugin.js  file.
2. The issue is present in the dev builds only. Issue not present in the prod build.
3. Node version v13.12.0

Is there any possibility that nuxt uses same Vue instance for the consecutive requests.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10478">#c10478</a>)</em></sub></div>

**Comment by manniL** [comment]
Likely related to [runInNewContext](https://ssr.vuejs.org/api/#runinnewcontext) which is different in prod and dev mode (related PR if I got it right: https://github.com/nuxt/nuxt.js/pull/4508).

**Comment by shivgarg5676** [comment]
@manniL  Can you specify how to override this option from nuxt.config.js. or give me some reference material. I tried few things but

**Comment by shivgarg5676** [comment]
Got it working by adding following config to nuxt.config.js

```
render:{
    bundleRenderer: {
      runInNewContext: false
    }
  }
```
The issue gets solved as well if I use the above config. I think then there is some issue with the runInNewContext only.
@manniL @pi0
