### ISSUE TITLE
Pages 404 on page refresh using Github Pages

### ISSUE THREAD

**Issue by jbratcher** [nuxt/nuxt.js#7172]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/jbratcher/nuxt-gh-pages-404-reproduction](https://github.com/jbratcher/nuxt-gh-pages-404-reproduction)

### Steps to reproduce

[Demo Link](https://jbratcher.github.io/nuxt-gh-pages-404-reproduction/)
1. Navigate to About Page
2. Refresh Page

### What is expected ?

Page is refreshed

### What is actually happening?

Page give 404 error

### Additional comments?

I have a project using Nuxt and Github Pages and noticed when I refreshed static pages other than the home route, they would give a 404 error.

A similar but not exactly the same issue may be #2240

This issue can be fixed by setting generate.fallback to true.  However, I'm really not sure why/how this works.  As I understand it, generate.fallback is used to control what is rendered when the page isn't found.

In `nuxt.config.js`
```javascript
export default {
  generate: {
    fallback: true
  },
}
```

The `fix` branch contains this code for the fix.

Any guidance on what is happening here?  Thanks!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10479">#c10479</a>)</em></sub></div>

**Comment by manniL** [comment]
This is intended. When generating pages, you have to tell your platform/web server (GitHub pages in your case) in case you want to handle 404 errors "through your own application". This is usually not wanted when building non-SPAs but highly recommended for SPAs (to avoid the mentioend reload - 404 - issue).

When enabled, `generate.fallback` creates a `404.html` which is essentially an SPA fallback page. GitHub pages picks it up automatically and redirects all "not found URLs" there.

However, generated URLs (with `mode: universal`) should not need a redirect. In your case, the capitalization of `About.vue` is giving troubles here. Lowercasing it and it should work fine 👍🏻

For the future, it might be an idea to unify pages, no matter how they are capitalized (e.g. `About.vue` should behave the same like `about.vue` or `aBoUt.vue`, as long as no drawbacks are present (cc @pi0).

Closing here 😋
