### ISSUE TITLE
Nuxt.js contains a GPL licensed library

### ISSUE THREAD

**Issue by dora-gt** [nuxt/nuxt.js#7173]
### What problem does this feature solve?

We should not use GPL licensed libraries as it makes Nuxt.js also GPL. Currently, we have `webpack-external-import@1.1.3` @ `GPL-3.0-only` which makes Nuxt.js GPL. This sounds annoying because users also have to make their products GPL.

### What does the proposed changes look like?

Update `extract-css-chunks-webpack-plugin` not to use GPL licensed versions of `webpack-external-import`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10481">#c10481</a>)</em></sub></div>

**Comment by dora-gt** [comment]
I apologize if the library is only **"used"** when we build webpacks **"locally"** and the library is not shipped in it. In that case, the library _might_ not make Nuxt.js GPL though I'm not so sure because I'm not a lawyer.

**Comment by CJxD** [comment]
+1. My project is closed-source, so this matters to me. I've noticed this for some time, but realised it's only used when build, so unless the production environment runs a webpack build, it's ok to use.

To be safe, I'd really want to separate the code required to run Nuxt and code required to build Nuxt into the `dependencies` and `devDependencies` sections of my package.json file respectively. This way, I can prove that I am not using this GPL license in production, and only for development.

My proposed solution is instead of simply specifying `nuxt` in your package.json, be able to split it into `nuxt-runtime` and `nuxt-compiletime` dependencies:

```
{
  "name": "my-project",
  "version": "1.0.0",
  ...
  "dependencies": {
    "nuxt-runtime": "^2.11.0",
    ...
  },
  "devDependencies": {
    "nuxt-compiletime": "^2.11.0",
    ...
  }
}
```

This effect may already be possible, as the affected code is all within the `@nuxt/webpack` sub-dependency, but not sure that it will work correctly if I list only these `@nuxt` sub-dependencies manually:

```
{
  "name": "my-project",
  "version": "1.0.0",
  ...
  "dependencies": {
    "@nuxt/cli": "2.11.0",
    "@nuxt/core": "2.11.0",
    "@nuxt/opencollective": "^0.3.0",
    ....
  },
  "devDependencies": {
    "@nuxt/builder": "2.11.0",
    "@nuxt/generator": "2.11.0",
    "@nuxt/loading-screen": "^1.2.0",
    "@nuxt/webpack": "2.11.0",
    ....
  }
}
```

Please confirm whether the method I have proposed would actually work?

**Comment by dora-gt** [comment]
Thank you for the suggestion. Although I had to tweak `package.json` like this:

```diff
-    "dev": "nuxt",
-    "build": "nuxt build",
-    "start": "nuxt start",
-    "generate": "nuxt generate",
+    "dev": "nuxt-cli",
+    "build": "nuxt-cli build",
+    "start": "nuxt-cli start",
+    "generate": "nuxt-cli generate",
```

I think it's working because `license-checker --production --summary` doesn't output any GPLs.

Also I think it is better for the community to split the packages into `nuxt-runtime` and `nuxt-compiletime`.

**Comment by CJxD** [comment]
It actually worked? Lol

**Comment by dora-gt** [comment]
I tried `dev`, `build`, `start` and it seemed to work. haha

**Comment by pi0** [comment]
Hi :)

Actually package name is [nuxt-start](https://www.npmjs.com/package/nuxt-start) which you can put in `dependencies` and `nuxt` to `devDependencies`. (see appendix)

Also, nuxt extracts all client bundle library licenses into `/_nuxt/LICENSES` file ([src](https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/base.js#L215))

I'm not a lawyer but Generally speaking, GPL is all about code ownership. If a library used for server-side rendering or build phase and only HTML result coming out to the client, it is not subject to GPL unless you, for example, want to publish/distribute the entire nuxt application in a docker image or that library is also used for client-side which means "A GPL code that is running on your system but source is not available". Anyway, it is a confusing issue with GPL. Dear Richard never liked [SaaS](https://www.gnu.org/philosophy/who-does-that-server-really-serve.en.html)

---

Appendix: Current `nuxt-start` licenses:

```
├─ @nuxt/cli@2.12.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/nuxt/nuxt.js
│  └─ path: nuxt-start/node_modules/@nuxt/cli
├─ @nuxt/config@2.12.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/nuxt/nuxt.js
│  └─ path: nuxt-start/node_modules/@nuxt/cli/node_modules/@nuxt/config
├─ @nuxt/core@2.12.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/nuxt/nuxt.js
│  └─ path: nuxt-start/node_modules/@nuxt/core
├─ @nuxt/server@2.12.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/nuxt/nuxt.js
│  └─ path: nuxt-start/node_modules/@nuxt/core/node_modules/@nuxt/server
├─ @nuxt/utils@2.12.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/nuxt/nuxt.js
│  └─ path: nuxt-start/node_modules/@nuxt/cli/node_modules/@nuxt/utils
├─ @nuxt/vue-renderer@2.12.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/nuxt/nuxt.js
│  └─ path: nuxt-start/node_modules/@nuxt/core/node_modules/@nuxt/vue-renderer
├─ chalk@3.0.0
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/chalk/chalk
│  ├─ path: nuxt-start/node_modules/@nuxt/cli/node_modules/chalk
│  └─ licenseFile: nuxt-start/node_modules/@nuxt/cli/node_modules/chalk/license
├─ debug@4.1.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/visionmedia/debug
│  ├─ publisher: TJ Holowaychuk
│  ├─ email: tj@vision-media.ca
│  ├─ path: nuxt-start/node_modules/@nuxt/core/node_modules/debug
│  └─ licenseFile: nuxt-start/node_modules/@nuxt/core/node_modules/debug/LICENSE
├─ hash-sum@2.0.0
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/bevacqua/hash-sum
│  ├─ path: nuxt-start/node_modules/@nuxt/cli/node_modules/@nuxt/utils/node_modules/hash-sum
│  └─ licenseFile: nuxt-start/node_modules/@nuxt/cli/node_modules/@nuxt/utils/node_modules/hash-sum/license
├─ nuxt-start@2.12.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/nuxt/nuxt.js
│  ├─ path: nuxt-start
│  └─ licenseFile: nuxt-start/LICENSE
└─ semver@7.3.2
   ├─ licenses: ISC
   ├─ repository: https://github.com/npm/node-semver
   ├─ path: nuxt-start/node_modules/@nuxt/cli/node_modules/@nuxt/utils/node_modules/semver
   └─ licenseFile: nuxt-start/node_modules/@nuxt/cli/node_modules/@nuxt/utils/node_modules/semver/LICENSE
```
