### ISSUE TITLE
Add pre-commit hook with Husky

### ISSUE THREAD

**Issue by Dragoon1010** [nuxt/nuxt.js#7174]
### What problem does this feature solve?

This feature adds pre-commit hooks. This will avoid the pull-request/push not respecting the conventional-commit at first.

Then we can also add a check of the name of the branch, and linting.

### What does the proposed changes look like?

I suggest adding the Husky library, which allows for pre-commit hooks and which checks the names of the commits.

We also add a script that checks the branch name, and we will have our own system for pull-requests.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10484">#c10484</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi, @Dragoon1010 thanks for PR. Actually it was already in discussion in #6861. Other than DX issues mentioned there, all PRs are validated to not only follow conventional-commit but also having a valid scope, message, and type (which cannot be automated by nature)

**Comment by Dragoon1010** [comment]
Hi @pi0 !

Ho, I see, thank you for this answer. I understand the choice after reading the ticket you cited ;)
