### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bosens-China** [nuxt/nuxt.js#7175]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://none](https://none)

## IconFont.vue
``` html
<template>
  <span class="icons-list">
    <icon-font :type="type" />
  </span>
</template>

<script>
import { Icon } from 'ant-design-vue'

const IconFont = Icon.createFromIconfontCN({
  scriptUrl: 'http://at.alicdn.com/t/font_1734167_5tkl3n0lw7s.js'
})

export default {
  name: 'IconFont',
  components: {
    IconFont
  },
  props: {
    type: {
      type: String,
      required: true
    }
  }
}
</script>

<style lang="less" scoped>
.icons-list /deep/ .anticon {
  margin-right: 6px;
  font-size: 24px;
}
</style>
```

## Use
``` html
             <client-only>
                <icon-font :type="item.ico"></icon-font>
              </client-only>
```

### What is expected ?

Display icons correctly

### What is actually happening?

 Maximum call stack size exceeded

### Additional comments?

I don't know if it's right. Obviously, JS files are loaded asynchronously. I can't let them be rendered on the server. However, I don't know why this error occurs in the browser

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10485">#c10485</a>)</em></sub></div>

**Comment by MinaroShikuchi** [comment]
I had this problem when i didn't fill my .env file, I don't know if it's related...

**Comment by bosens-China** [comment]
I don't feel right. I'll make a mini demo at night

**Comment by gengchen528** [comment]
> I don't feel right. I'll make a mini demo at night

i have same problem. when i import `iconfont.js`.  build was not going in 30%.
have you resolve this problem
![image](https://user-images.githubusercontent.com/20028566/83248796-31e01b80-a1d8-11ea-8a04-e74c2382f690.png)
