### ISSUE TITLE
How to get CORS Cookies on server side?

### ISSUE THREAD

**Issue by hookszhang** [nuxt/nuxt.js#718]
I use axios http client on client and server side. Cross domain i use CORS to solve.

My problem is: on client side i don't get cookies use javascript. so middleware is invalid.
What should i do?

**Comment by falstack** [comment]
@hookszhang hi, how do you resolve it?

**Comment by hookszhang** [comment]
sorry it's to late.

### The nuxtServerInit Action

https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action

> If the action nuxtServerInit is defined in the store, Nuxt.js will call it with the context (only from the server-side). It's useful when we have some data on the server we want to give directly to the client-side.

So i put cookie to `process.__COOKIE__` variable.

```
nuxtServerInit({ commit }, { req }) {
  process.__COOKIE__ = req.headers.cookie
}
```

Then set cookie in axios request interceptor when server build.

```
axios.interceptors.request.use(function (config) {
   store.dispatch('GLOBAL_LOADING')
   if (process.SERVER_BUILD) {
    if (process.__COOKIE__) {
        config.headers.common['Cookie'] = process.__COOKIE__
    }
  }
  return config
})
```
