### ISSUE TITLE
run dev fail && run build fail && develop break

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#719]
`npm run dev` error: https://github.com/nuxt/nuxt.js/issues/669
`npm run build` error : https://github.com/nuxt/nuxt.js/issues/686 

I think this is caused by nuxt it self, now I can't continue develop my app and run my app and build my app. I believe that many other developers meet these error.

so I hope you can give priority to this `!important` error! 

thanks!!

**Comment by alexchopin** [comment]
We are working on it, it will be fixed in the next release.
Please don't open duplicate issue.
