### ISSUE TITLE
FYI: missed link in this question !

### ISSUE THREAD

**Issue by nelsonlarocca** [nuxt/nuxt.js#7190]
Hi @ckken 

Please take a look at [examples/global-css](https://github.com/nuxt/nuxt.js/tree/master/examples/global-css).

Thank you

_Originally posted by @Atinux in https://github.com/nuxt/nuxt.js/issues/22#issuecomment-263527604_

**Comment by pi0** [comment]
Here you are mate ;)  https://github.com/nuxt/nuxt.js/tree/dev/examples/global-css
