### ISSUE TITLE
Nuxt page deployed only updating with hard reload or clearing cache

### ISSUE THREAD

**Issue by aconchatorres** [nuxt/nuxt.js#7193]
### Version

[v2.9.0](https://github.com/nuxt.js/releases/tag/v2.9.0)

### Reproduction link

[https://www.nolink.com/NA](https://www.nolink.com/NA)

### Steps to reproduce

Create a project with the nuxt CLI, create some code, use this nuxt documentation to deploy the project in AWS S3 and Cloudfront for Static Site Hosting:
https://nuxtjs.org/faq/deployment-aws-s3-cloudfront/
Run the ./deploy.sh script for uploading.

### What is expected ?

The script finishes successfully as shown in the documentation and the site updates completely between 3 - 10 minutes while the Cloudfront invalidation is processed.

### What is actually happening?

The script finishes successfully as shown in the documentation and the site does not updates completely. CSS, HTML or Javascript changes does not update and the user has to hard reload the page or clear its browser cache to get the changes.

### Current solution?
Add a hard reload in the login so whenever the user enters it gets the latest changes (works but should not be used).

### Additional comments?

It seems that only when new files/folders are created or modified a lot, the project updates with no problem. But for small changes like hot fixes the page does not update.

I've used another Nuxt documentation for running the commands for the Single Page Application Deployment (SPA): 
https://nuxtjs.org/guide/commands/
The value of mode: 'spa' in the nuxt.config.js has been made. 
Also the AWS and Cloudfront values where checked and there is no problem with them. Even the TTL values where decreased to 0  but the issue persists.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10495">#c10495</a>)</em></sub></div>

**Comment by cuciurean-constantin** [comment]
This is still happening.... 
We used the "2.15.8" nuxt version and before each build we change the version into package.json file.
Will these config fixing up the error???
_build: {
        watch: ['~/package.json']
    }_
