### ISSUE TITLE
purgeCSS ignores tailwind classes in nuxt.config.js (bodyAttr, htmlAttrs)

### ISSUE THREAD

**Issue by MZanggl** [nuxt/nuxt.js#7197]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/MZanggl/nuxt-tailwind-config-purge-bug](https://github.com/MZanggl/nuxt-tailwind-config-purge-bug)

### Steps to reproduce

Running `npm run dev` you will see the page displaying a blue background. This is because I added 

```
bodyAttrs: {
      class: 'bg-blue-200'
}
```

in `nuxt.config.js`.

Running `npm run generate` and opening the generated files just returns the default white background.

### What is expected ?

classes inside nuxt.config.js get detected by purgeCSS.

### What is actually happening?

purgeCSS does not take class names in nuxt.config.js into consideration so it accidentally purges these classes.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10502">#c10502</a>)</em></sub></div>

**Comment by manniL** [comment]
Please open this issue as a feature request in https://github.com/Developmint/nuxt-purgecss

You can configure purgeCSS to take the nuxt config into account, so feel free to do so
