### ISSUE TITLE
nuxt link front end routing doesn't work in production

### ISSUE THREAD

**Issue by ErnieBernie10** [nuxt/nuxt.js#7198]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/ErnieBernie10/Blog](https://github.com/ErnieBernie10/Blog)

### Steps to reproduce

- Clone github repo
- ``npm install``
- ``npm run build``
- set ``NODE_ENV=production``
- ``npm run start:prod``
- ``navigate to localhost:5000``
- click on a link

### What is expected ?

The link brings brings you to the right page.

### What is actually happening?

nuxt routes you to the page but the view doesn't change.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10505">#c10505</a>)</em></sub></div>

**Comment by manniL** [comment]
Please provide a minimal repo and not your full app.

**Comment by ErnieBernie10** [comment]
I don't know what's causing the issue so I don't know how to reduce it. The only relevant code is my nuxt app in the client directory and the server/controllers/nuxt.controller.ts file which handles programmatically rendering nuxt.
