### ISSUE TITLE
SEO HTML Head not being set in generated static files

### ISSUE THREAD

**Issue by tunecino** [nuxt/nuxt.js#7201]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/tunecino/nuxt-seo](https://github.com/tunecino/nuxt-seo)

### Steps to reproduce

- Create a new project
- Go inside /pages/index.vue
- Add `head() { return { title: "xyz"} }` inside page local settings as mentioned in docs.
- Run `yarn generate`

### What is expected ?

I expected to find `<title>xyz</title>` inside the generated file (`/dist/index.html`)

### What is actually happening?

Found `<title>example</title>` instead. Which is my project name.

### Additional comments?

The web page works fine in a browser, as far as javascript is enabled as it replaces the title tag correctly at certain point.
But if you disable javascript and reload the page, local settings are omitted and it shows the wrong title.
Even Lighthouse extension, which shows a great SEO score, if reports are expanded, you'll notice it parsed the wrong title.

I thought static pages won't require search engine bots to run any javascript. Is it a bug or did I miss something?

Thanks.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10508">#c10508</a>)</em></sub></div>

**Comment by manniL** [comment]
Because you are using `mode: 'spa'` (instead of `'universal'`)

https://github.com/tunecino/nuxt-seo/blob/master/nuxt.config.js#L3

**Comment by tunecino** [comment]
Oh! My bad. That was what I did miss. Thank you @manniL
