### ISSUE TITLE
'ignoredElements' doesn't work

### ISSUE THREAD

**Issue by takezawahiroshi** [nuxt/nuxt.js#7204]
### What problem does this feature solve?

I want to ignore "another mustache tag" when nuxt generate
For example, using ignoredElements
But that doesn't work

---
I uploaded my "nuxt generated file" on my company server,
I have to use "another mustache tag" on legacy server ...

mustache: https: //mustache.github.io/#demo
---

```
<template>
    <div class="example">
        {{# user }}
            <p>user information</p>
        {{/ user }}

        {{^ user }}
            <button>login</button>
        {{/ user }}
    </div>
</template>
```
```
// nuxt.config.js
export default {
    mode: 'universal',
    vue: {
      config: {
        ignoredElements: [
          '{{# user}}',
          '{{/ user}}',
          '{{^ user}}'
        ]
      }
    }
}
```

### What does the proposed changes look like?

ignoredElements works for mustache

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10511">#c10511</a>)</em></sub></div>

**Comment by leopiccionia** [comment]
Vue's `ignoredElements` just check tag names, not arbitrary expressions.

You can try using `v-pre`, if you're not using Vue inside Mustache ([see docs](https://vuejs.org/v2/api/#v-pre)).

**Comment by takezawahiroshi** [comment]
Thank you.
I have tried using v-pre
But,

- I have tried 

```
<template>
    <div class="example">
        <span v-pre>{{# user }}</span>
            <p>user information</p>
        <span v-pre>{{/ user }}</span>

        <span v-pre>{{^ user }}</span>
            <button>login</button>
        <span v-pre>{{/ user }}</span>
    </div>
</template>
```

```
// nuxt generate
<template>
    <div class="example">
        <span>{{# user }}</span>
            <p>user information</p>
        <span>{{/ user }}</span>

        <span>{{^ user }}</span>
            <button>login</button>
        <span>{{/ user }}</span>
    </div>
</template>
```

- Behavior I expect

```
<template>
    <div class="example">
        {{# user }}
            <p>user information</p>
        {{/ user }}

        {{^ user }}
            <button>login</button>
        {{/ user }}
    </div>
</template>
```

As a last resort,
when I run 'nuxt generate' and edit the file directly
I get an error.
It seems that the DOM is different from the file when I generated nuxt generate

```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

In conclusion,
'nuxt generate' doesn't seem to be usable as a legacy serverside templete

**Comment by takezawahiroshi** [comment]
I understand it is not appropriate to use Nuxt.js as a legacy template
I closed this issue
