### ISSUE TITLE
Function in data is called twice

### ISSUE THREAD

**Issue by LukaHarambasic** [nuxt/nuxt.js#7206]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://codesandbox.io/s/solitary-haze-3xkww?file=/pages/index.vue](https://codesandbox.io/s/solitary-haze-3xkww?file=/pages/index.vue)

### Steps to reproduce

Refresh page multiple times

### What is expected ?

The organizations should be in a different order every time, also the logo should match the title in the tile.

### What is actually happening?

Sometimes the wrong logo is shown for an organization but only in the tiles if you click on a tile it will open the modal with the correct data.

### Additional comments?

I think it's because the client and the server both call the shuffle function. Maybe I'm just understanding some concepts wrong but it's an unexpected behavior.
I had to use vuex in this project so I'm doing the shuffle in the store and everything works fine.

PS: Thanks for Nuxt <3

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10513">#c10513</a>)</em></sub></div>

**Comment by usb248** [comment]
Same here : https://codesandbox.io/s/cool-haibt-qkpm5?file=/pages/index.vue:95-164

**Comment by Atinux** [comment]
Hi there,

It is actually the Vue.js behaviour when doing server-side rendering, `data` is called both on server and on client to by able to hydrate itself.

With Nuxt.js, you can use `asyncData` (that will store in `window.__NUXT__`) and won't be called on client-side.
If you need to access the Vue instance, you can use `fetch` (version >= 2.12): https://codesandbox.io/s/laughing-kapitsa-m4p60?file=/pages/index.vue
