### ISSUE TITLE
When using global mixin in plugin, performance degradation occurs due to increased requests.

### ISSUE THREAD

**Issue by hoiheart** [nuxt/nuxt.js#7207]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/hoiheart/nuxt-issue-demo](https://github.com/hoiheart/nuxt-issue-demo)

### Steps to reproduce

https://github.com/hoiheart/nuxt-issue-demo/blob/master/plugins/demo.js
using global mixin in plugin

1. Confirm the response time for the first time
2. Generates hundreds or thousands of requests
3. Check the response time afterwards

### What is expected ?

Has a response time that is similar to the first

### What is actually happening?

The response time is getting slower

First response time
![before.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d89a11f0-7d21-11ea-962b-a190a1f87121.png)

Response time after 1000 request
![after.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/fc04b0a0-7d21-11ea-962b-a190a1f87121.png)

### Additional comments?

If the mixin declaration is in export, it will also be affected by production.
In dev mode, it is affected regardless of the position of the mixin declaration.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10515">#c10515</a>)</em></sub></div>

**Comment by SasanFarrokh** [comment]
We encountered this error long time ago, 
This has a memory leak, cause Vue instance on server side is a single object. exported function calls for each user request. after too many requests, heap memory max size will reach and cause an app crash.

Use mixin outside exported function, and if you want to use nuxt context, (req, modules, ...) store it in a local variable like this:

```javascript

let user;

Vue.mixin({
   mounted () {
      console.log(user)
  }
})

export default function (ctx, inject) {
  user = ctx.req.user // example
}
```

**Comment by hoiheart** [comment]
@SasanFarrokh
Thank you for your reply.
In addition, Should I use outside export when calling a Vue instance?

```
// Can't I install the plug-in like this?
export default ({ app, store }) => {
  Vue.use(myPlugin, { app, store })
}
```

**Comment by SasanFarrokh** [comment]
> @SasanFarrokh
> Thank you for your reply.
> In addition, Should I use outside export function when calling all Vue instance?
> 
> ```js
> // Can't I install the plug-in like this?
> export default ({ app, store }) => {
>   Vue.use(myPlugin, { app, store })
> }
> ```

Yes, of course.
Vue global functions (use, mixin, component, ...)  should all be outside export function.

**Comment by Atinux** [comment]
Actually you should never add a global mixins when doing SSR without checking if it has been registered before!

```js
// my-mixin-plugin.js
if (!Vue.__my_mixin__) {
  Vue.mixin({
    ...
   })
   // Avoid registering again the mixin and other calls from SSR
   Vue.__my_mixin__ = true
}
```

This case also applies for un-names plugins, components.
