### ISSUE TITLE
How to get rid of trailing forward slashes after nuxt generate?

### ISSUE THREAD

**Issue by sbefort** [nuxt/nuxt.js#721]
When I use nuxt generate, dynamic links with an index.vue in the route's last folder creates a link like this:

https://mydomain.com/mypath/index.html

After deploying to S3, there is a redirect if the trailing forward slash is missing after mypath/.  So https://mydomain.com/mypath redirects to https://mydomain.com/mypath/.

Is there any way around this, or is this a necessary evil of static sites?  Thanks.

**Comment by sebastianmacias** [comment]
I believe this is outside the scope of nuxt and directly depends on the configuration of the static host you are using. In your case AWS S3. Check out this: https://forums.aws.amazon.com/thread.jspa?threadID=168000
