### ISSUE TITLE
<script> tag will be deleted execute npm run build 

### ISSUE THREAD

**Issue by wangdakanga** [nuxt/nuxt.js#7215]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/serene-minsky-66vzv?file=/pages/index.vue](https://codesandbox.io/s/serene-minsky-66vzv?file=/pages/index.vue)

### Steps to reproduce

1. add <script> tag to <tempate> tag in vue page  file
2. execute "npm run dev",when view the browser ，the <script> tag showing on the page
3. execute "npm run build && npm run start",<script> tag was removed

### What is expected ?

execute "npm run build && npm run start",the <script> tag showing on the page

### What is actually happening?

<script> tag was removed

### Additional comments?

In version 2.9.1, the tag was not removed
I hope my poor English does not bother you

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10519">#c10519</a>)</em></sub></div>

**Comment by Atinux** [comment]
Please use the [head](https://nuxtjs.org/api/pages-head) property to add external scripts (related: https://vue-meta.nuxtjs.org/api/#script)
