### ISSUE TITLE
Property for Layouts

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#722]
I have simple default Layout:
```html
<template>
  <div class="simple">
    <h1 class="page-title">{{title}}</h1>
    <nuxt/>
  </div>
</template>
```
How to pass the value of the variable `title` from a certain page into a layout?

**Comment by Atinux** [comment]
@cawa-93 do you mean the title property comes from a page?

If so, you should use the vuex store for that.

**Comment by cawa-93** [comment]
@Atinux, You do not recommend using [your example](https://github.com/nuxt/nuxt.js/issues/720#issuecomment-301563039) to pass a value from a page to a layouts? Somthing like this:

`layouts/default.vue`
```vue
<template>
<h1>{{title}}</h1>
</nuxt>
</template>

<script>
export default {
  computed: {
    title () {
      return this.$route.matched.map((r) => {
        return (r.components.default.options ? r.components.default.options.pageTitle : r.components.default.pageTitle)
      })[0]
    },
  },
}
</script>
```
`pages/somePage.vue`
```javascript
export default {
  pageTitle: 'Title for H1 tag'
}
```

**Comment by Atinux** [comment]
Sure, you can do this too :+1:
