### ISSUE TITLE
Strange effects when using keep-alive and watch route with new fetch feature

### ISSUE THREAD

**Issue by henrik377** [nuxt/nuxt.js#7229]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/s/mutable-dream-zg5mv?file=/components/blocks/ArticleBlock.vue:2313-2355](https://codesandbox.io/s/mutable-dream-zg5mv?file=/components/blocks/ArticleBlock.vue:2313-2355)

### Steps to reproduce

Hi!

The only thing I did compared to the original example from the nuxt blog is that I added a watch for route. Then strange things happen.

Click on the first article, this shows the skeleton-ui and then the article when finished loading.
Click back to the list.
Click the same article as you did the first time, the skeletion-ui is showing again and even though the article was to be cached it isn't.
Click back to the list. It is now starting to take time to click on the lists (new and top). Seems like every page that is now supposed to be handled with keep-alive now actually reloads a fetch in the background.

### What is expected ?

Expect to have the component/page cached and not fetched again the second time I click on it.
Expect to only see calls to fetch what I have clicked on.

### What is actually happening?

The component/page isn't cached. Always fetched.
All pages that are supposed to be handled with keep-alive seems to be listening to something in the background so they load when clicking on other pages/components. You end up with lots of http-calls in the background that you don't want to be seeing.

### Additional comments?

I tried this in a closed project of mine and when I remove the watch then everything works as expected.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10530">#c10530</a>)</em></sub></div>

**Comment by MLDMoritz** [comment]
duplicate #7156
