### ISSUE TITLE
New fetch problem hydrate with store

### ISSUE THREAD

**Issue by javiercno** [nuxt/nuxt.js#7232]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/nuxt-fetch-store-5rbyp](https://codesandbox.io/s/nuxt-fetch-store-5rbyp)

### Steps to reproduce

Show console and view error.

### What is expected ?

Nuxt correct renderer changes in vuex

### What is actually happening?

Nuxtjs does not render changes to vuex used outside component in SSR

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10533">#c10533</a>)</em></sub></div>

**Comment by UnderTheMoonspell** [comment]
Having the same problem in a normal component (so not layout). 

`async fetch () {
      await this.$store.dispatch('statics/fetchFooterPageTextIfNeeded', {
        apiFilter: this.apiFilter,
        stateRef: this.stateRef,
      })
}
`

I have the old fetch working as expected in pages with similar code

**Comment by javiercno** [comment]
The issue with actual new fetch, depending on Vue 2 serverPrefetch is that you cannot update the parent nodes of the component using fetch on SSR.

@Atinux not advice to use the store when using fetch.

**Comment by UnderTheMoonspell** [comment]
Actually my problem differs a little bit. Even if I dont use the store I still get a lot of errors if I use it on the server side:

```
async fetch () {
   if (!process.client) { this.footerPageText = await api.getFooterPageText({ apiFilter: this.apiFilter }) }
}
```
Results in the following

![image](https://user-images.githubusercontent.com/10156878/80612578-0da3ea00-8a34-11ea-9e77-a50a37f8c228.png)

**Comment by Atinux** [comment]
You cannot use fetch() only on server-side since it will be inconsistent when doing client-side navigation.

**Comment by Atinux** [comment]
Because of current limitations of Vue2/serverPrefetch. You cannot update parent nodes from fetch() when doing SSR. Most of the time using the store is made outside the current component. So I advice not using the store or to be careful when using the new fetch()

You can use an [anonymous middleware](https://nuxtjs.org/api/pages-middleware#anonymous-middleware) at the page level to mimic the old fetch behavior.

**Comment by AluisioASG** [comment]
@Atinux Should the [advice on the store guide](https://nuxtjs.org/guide/vuex-store#the-fetch-method) be updated then?

**Comment by UnderTheMoonspell** [comment]
@Atinux that process.client was just for testing, it's also not working without that if. So in my case at least, doesn't seem to be a store-only problem

**Comment by Atinux** [comment]
@AluisioASG Indeed nice found, could you open a PR on the docs for it? (Edit this page on GitHub at the bottom) 🙏
