### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by apguerrera** [nuxt/nuxt.js#7236]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/apguerrera/PetylVentureStudio](https://github.com/apguerrera/PetylVentureStudio)

### Steps to reproduce

yarn add web3

import Web3 from "web3";

yarn build

### What is expected ?

Build Success

### What is actually happening?

WARNING in ./node_modules/any-promise/register.js 24:14-37
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/any-promise/index.js
 @ ./node_modules/web3-eth-accounts/src/index.js
 @ ./node_modules/web3-eth/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./app/helpers/web3Functions.js
 @ ./app/store/web3.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js

WARNING in ./node_modules/@web3-js/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/Release/bufferutil' in '/Users/adrian/Documents/GitHub/PetylVentureStudio/node_modules/@web3-js/websocket/lib'
 @ ./node_modules/@web3-js/websocket/lib/BufferUtil.js
 @ ./node_modules/@web3-js/websocket/lib/WebSocketFrame.js
 @ ./node_modules/@web3-js/websocket/lib/websocket.js
 @ ./node_modules/@web3-js/websocket/index.js
 @ ./node_modules/web3-providers-ws/src/index.js
 @ ./node_modules/web3-core-requestmanager/src/index.js
 @ ./node_modules/web3-core/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./app/helpers/web3Functions.js
 @ ./app/store/web3.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js

WARNING in ./node_modules/@web3-js/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/Release/validation' in '/Users/adrian/Documents/GitHub/PetylVentureStudio/node_modules/@web3-js/websocket/lib'
 @ ./node_modules/@web3-js/websocket/lib/Validation.js
 @ ./node_modules/@web3-js/websocket/lib/WebSocketConnection.js
 @ ./node_modules/@web3-js/websocket/lib/websocket.js
 @ ./node_modules/@web3-js/websocket/index.js
 @ ./node_modules/web3-providers-ws/src/index.js
 @ ./node_modules/web3-core-requestmanager/src/index.js
 @ ./node_modules/web3-core/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./app/helpers/web3Functions.js
 @ ./app/store/web3.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js

WARNING in ./node_modules/@web3-js/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/default/bufferutil' in '/Users/adrian/Documents/GitHub/PetylVentureStudio/node_modules/@web3-js/websocket/lib'
 @ ./node_modules/@web3-js/websocket/lib/BufferUtil.js
 @ ./node_modules/@web3-js/websocket/lib/WebSocketFrame.js
 @ ./node_modules/@web3-js/websocket/lib/websocket.js
 @ ./node_modules/@web3-js/websocket/index.js
 @ ./node_modules/web3-providers-ws/src/index.js
 @ ./node_modules/web3-core-requestmanager/src/index.js
 @ ./node_modules/web3-core/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./app/helpers/web3Functions.js
 @ ./app/store/web3.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js

WARNING in ./node_modules/@web3-js/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/default/validation' in '/Users/adrian/Documents/GitHub/PetylVentureStudio/node_modules/@web3-js/websocket/lib'
 @ ./node_modules/@web3-js/websocket/lib/Validation.js
 @ ./node_modules/@web3-js/websocket/lib/WebSocketConnection.js
 @ ./node_modules/@web3-js/websocket/lib/websocket.js
 @ ./node_modules/@web3-js/websocket/index.js
 @ ./node_modules/web3-providers-ws/src/index.js
 @ ./node_modules/web3-core-requestmanager/src/index.js
 @ ./node_modules/web3-core/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./app/helpers/web3Functions.js
 @ ./app/store/web3.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js

WARNING in ./node_modules/@web3-js/scrypt-shim/src/index.js
Module not found: Error: Can't resolve 'scrypt' in '/Users/adrian/Documents/GitHub/PetylVentureStudio/node_modules/@web3-js/scrypt-shim/src'
 @ ./node_modules/@web3-js/scrypt-shim/src/index.js
 @ ./node_modules/web3-eth-accounts/src/index.js
 @ ./node_modules/web3-eth/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./app/helpers/web3Functions.js
 @ ./app/store/web3.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js

ERROR in ./node_modules/swarm-js/node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in '/Users/adrian/Documents/GitHub/PetylVentureStudio/node_modules/swarm-js/node_modules/got'
 @ ./node_modules/swarm-js/node_modules/got/index.js 45:20-39
 @ ./node_modules/swarm-js/lib/files.js
 @ ./node_modules/swarm-js/lib/api-node.js
 @ ./node_modules/web3-bzz/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./app/helpers/web3Functions.js
 @ ./app/store/web3.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js

   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

### Additional comments?

It works in dev, just cannot build :'(

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10536">#c10536</a>)</em></sub></div>

**Comment by pimlie** [comment]
It is quite unlikely this is a bug with Nuxt.js, dependency issues are often an issue from userland code.

Please add a reproduction with steps you already tried to debug yourself when you are somewhat certain this is a Nuxt issue.
