### ISSUE TITLE
Fetch on client only

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt.js#7237]
### What problem does this feature solve?

The new fetch feature is awesome. But there is still something to gain here. If one would have an caching layer (e.g. CloudFlare) between the Nuxt instance and the user, it would be great to have an option to fetch some pages at server side and others just at client side only.

For instance:
https://example.com/product/msi-laptop could be fetched on the server, and is preferred this way for SEO.

But:
https://example.com/order/123 could be fetched client side only. This page is not indexed and not important for SEO, if CloudFlare could cache all `/order/xxx` pages they won't hit the Nuxt server.

### What does the proposed changes look like?

Have some option on a page component to make sure the fetching is done at serverside or clientside:

```
export default {
  fetchMode: 'client'
}
````

Could default to `'server'`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10537">#c10537</a>)</em></sub></div>

**Comment by DenzoNL** [comment]
+1, would be very useful for user pages that require authentication.

**Comment by pimlie** [comment]
You should already be able to use [`fetchOnServer`](https://nuxtjs.org/api/pages-fetch#options) for this, it also accepts a function so you implement your own logic

**Comment by Timkor** [comment]
@pimlie Awesome, missed that! Thanks.
