### ISSUE TITLE
Duplicate CSS and JS Links using Nuxt and Vuetify

### ISSUE THREAD

**Issue by CoreyT355** [nuxt/nuxt.js#7245]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/CoreyT355/nuxt-vuetify-duplicate-css](https://github.com/CoreyT355/nuxt-vuetify-duplicate-css)

### Steps to reproduce

Open terminal
Run, npx create-nuxt-app whatever
Select Javascript, Vuetify, No Server, Jest, Prettier, ESLint, and the jsconfig options when they are presented
Once the generator completes run, npm i nuxt to update to 2.12.2 version of Nuxt
Edit the nuxt.config.js file by adding the extractCSS: true option to the build section
When the install completes start your dev server, npm run dev
Visit the site in Chrome
Open the Chrome dev tool
Look at the Elements tab
Expand the head tag

### What is expected ?

A single CSS link for each generated CSS file with a preload attribute
A single link to each generated JS file.

### What is actually happening?

There are 2 links to each JS and CSS file. 

For CSS there will be one with a preload and one without. 

With the JS files there will be a link in the head tag and a defer script tag before the closing body tag.
See attached screenshot

![nuxt.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/cae80730-8369-11ea-98e5-b9b26d3146fb.PNG)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10544">#c10544</a>)</em></sub></div>

**Comment by manniL** [comment]
It's perfectly fine to have `preload` links together with the *actual* resource links (stylesheets/scripts).

Feel free to check the [MDN entry](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content).

**Comment by CoreyT355** [comment]
It fails in lighthouse tests for having a CSS link without a preload tag.
