### ISSUE TITLE
Direct access to a page generated with `yarn generate` shows the home page

### ISSUE THREAD

**Issue by samupl** [nuxt/nuxt.js#7247]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[http://nuxt-reproduction.samu.pl/](http://nuxt-reproduction.samu.pl/)

### Steps to reproduce

Repository URL: https://github.com/samupl/nuxt-direct-access-bug-reproduction
(Fresh nuxtjs app in universal mode with one dynamic route)

Build steps:

Use `yarn generate`

Reproduction steps:

* Go to the home page (http://nuxt-reproduction.samu.pl/)
* Click on the "Click me" link
* You should be redirected to http://nuxt-reproduction.samu.pl/test/a/b
* Observe that you see the content of the page ("HELLO, I'm a sub-page!")
* Click refresh (simulate "direct access" to the sub-page URL
* Observe the page you see

### What is expected ?

Eventhough it's a dynamic route, I would expect the page to load anyway. 

### What is actually happening?

I see the home page.

### Additional comments?

A static version of the page is not expected. But the dynamic version should load as soon as nuxt loads. Looks like the router is not initialized properly when accessing a route for a dynamic page.

This works as intended in SPA mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10546">#c10546</a>)</em></sub></div>

**Comment by manniL** [comment]
Sounds like a deployment problem.

Is your NGINX pointing to the `200.html` in the `/dist` folder, (especially) for "unknown routes" (where no corresponding HTML file is available)?

**Comment by samupl** [comment]
Right, I wasn't aware that you need to point nginx to `200.html`, I assumed it has to be pointed to `index.html`. Seems like pointing it to `200.html` makes it work as expected.

**Comment by manniL** [comment]
> Right, I wasn't aware that you need to point nginx to `200.html`, I assumed it has to be pointed to `index.html`. Seems like pointing it to `200.html` makes it work as expected.

That's why you got your index page on reload 😋

Glad it works now!
