### ISSUE TITLE
nuxt.config.js 里設置router.base后，對static下的文件引用出錯

### ISSUE THREAD

**Issue by abelshare** [nuxt/nuxt.js#7250]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codepen.io/lixh/pen/ExVgMXm](https://codepen.io/lixh/pen/ExVgMXm)

### Steps to reproduce

step1  在static下建立test.js文件
step2  在nuxt.config.js里設置router.base值為‘test’，在head.script里設置引用test.js
step3 npm run dev
step4  chrome console 查看test.js的引用，報404，路徑為host/test.js 而不是host/test/test.js

### What is expected ?

正確引用test.js

### What is actually happening?

test.js引用路徑錯誤

### Additional comments?

step1  在static下建立test.js文件
step2  在nuxt.config.js里設置router.base值為‘test’，在head.script里設置引用test.js
step3 npm run dev
step4  chrome console 查看test.js的引用，報404，路徑為host/test.js 而不是host/test/test.js

https://codesandbox.io/s/stupefied-kowalevski-zcmwh?file=/nuxt.config.js

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10547">#c10547</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@pimlie This issue is about why `script` in `head` does't respect `router.base` as base url:

If `router.base: 'test'`, but `head: <script src="/foo.js" />` is not using `/test/foo.js`, I think you have better understanding in vue-meta 😃

**Comment by pimlie** [comment]
Please see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
> If either of the following attributes are specified, this element must come before other elements with attributes whose values are URLs, such as <link>’s href attribute

In the reproduction the base tag is added _after_ the tags added by vue-meta. That would mean that [this](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L132) line should be moved before [this](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L117) line

Strange we didnt detect this earlier...
