### ISSUE TITLE
nuxt + bootstrap: .container min-width

### ISSUE THREAD

**Issue by hktr92** [nuxt/nuxt.js#7251]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://00297.sse.codesandbox.io/](https://00297.sse.codesandbox.io/)

### Steps to reproduce

First of all: unable to reproduce in CodeSandbox.

I've created the app via `yarn create nuxt-app` with following config: https://imgur.com/y2PqBDc
![y2PqBDc.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/599f1380-83b8-11ea-828f-5fb75bca9643.png)

### What is expected ?

CSS to be the as provided in CodeSandbox

### What is actually happening?

The `.container` class has an additional 'min-width: 100vh' property that pulls my header and footer to be at least 100vh without having any control over it nor any cause of it.

### Additional comments?

- browser: firefox
- caching: disabled

browser inspection says it's source is 'inline:2', but I don't understand what is putting it there.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10549">#c10549</a>)</em></sub></div>

**Comment by hktr92** [comment]
oh nvm, the `pages/index.vue` style wasn't scoped *by default* and that caused the mixture of classes. :)

**Comment by manniL** [comment]
Closing here then ☺️
