### ISSUE TITLE
Nuxt production build not including Global and Module CSS

### ISSUE THREAD

**Issue by gvnttdata** [nuxt/nuxt.js#7254]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/modest-shaw-3j0tm](https://codesandbox.io/s/modest-shaw-3j0tm)

### Steps to reproduce

1.) Install vue-chartist via npm `npm install vue-chartist`
2.) Add Chartist css file to assets/css/
3.) Create vue-chartist plugin:

import Vue from 'vue'
import VueChartist from 'vue-chartist'

Vue.use(VueChartist)

4.) Update nuxt.config.js
      - css: ['~/assets/css/chartist.css'],
      -  plugins: ['~/plugins/vue-chartist'],

5.) "npm run dev" command will show that the chart is working in dev with a chart that is properly styled:

![ss-codesandbox.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/abc0ac80-83e2-11ea-828f-5fb75bca9643.PNG)

6.) "npm run build" command to build project
7.) Serving the /dist folder will show a chart that is missing styling and looks broken:

![ss-broken-styling.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d40b7670-83e2-11ea-828f-5fb75bca9643.PNG)

### What is expected ?

Chart should look the same in dev as in production build

### What is actually happening?

Production build seems to be missing global css from nuxt config leading to a chart that is there but missing styling/looks broken.

### Additional comments?

From as best as I can tell I have been following the docs for including plugins and styling and I love Nuxt so I would 100% hope this is just me misunderstanding something in the docs rather than an actual bug but I can't see where I have gone wrong.

In addition the 'Font-Awesome'  module seems to be broken as well as I can see the icons on my project page when I load up the dist folder for a split second and then they disappear. Just like the Chartist charts they work fine in dev. I would assume there is some connection between the two not working but that is loaded via the 'modules' option in nuxt.config so I'm focusing on one thing at a time.

Thanks for any and all assistance!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10551">#c10551</a>)</em></sub></div>

**Comment by smoooty** [comment]
I think purge css omits computed classnames from the build so you might need to add the `'nuxt-purgecss'` plugin and then add whitelist entries to include the classes you need.

**Comment by gvnttdata** [comment]
That would make sense except I usually use tailwind and I don't think I have had any problems with the those computed classes. And actually chartist.css is just plain css, so I do not think it has any compiled styling anywhere.

**Comment by smoooty** [comment]
Check this out https://github.com/FullHuman/purgecss/issues/74

I ran into a similar issue recently with styling discrepancies between dev/prod and whitelisting certain classes from purgecss ended up resolving it.

**Comment by philipdanielhayton** [comment]
+1 I'm also having the same issue with my build. I'm using fullpage.js, works fine on dev, but most of the styles are missing when running a production build.

**Comment by kkukelka** [comment]
try adding 'nuxt-purgecss' to your buildModules in your nuxt.config
then add any pattern involving 'ct-' to your whitelist 
```typescript
export default {
  purgeCSS: {
    whitelistPatterns: [
      /ct-.*/
    ],
}
```

**Comment by nttdataxd** [comment]
Just wanted to state that updating the Nuxt Config file and whitelisting purgeCss with 
"purgeCSS: {
    whitelistPatterns: [/^ct/]
  },"
and I seem to be good to go.

Thanks for all the help!

**Comment by Atinux** [comment]
Like @nttdataxd you need to whitelist your classes if you use `@nuxtjs/tailwindcss` < 2.0
