### ISSUE TITLE
Vue nuxt js Hot code reloading not working 

### ISSUE THREAD

**Issue by channasmcs** [nuxt/nuxt.js#726]
hello guys i generate vue cli and nuxt.js applicaiton in my vagrant machine. but in that project dosent listing Hot code reload. this problem was appear with vue application. but it solved after add below code In build/dev-server.js:21

=====
`var devMiddleware = require('webpack-dev-middleware')(compiler, {
publicPath: webpackConfig.output.publicPath,
stats: {
colors: true,
chunks: false
},
watchOptions: {
aggregateTimeout: 300,
poll: 1000
}
})`

======

but how update vue nuxt file ?????? where location

**Comment by Atinux** [comment]
It's seems to be more an issue related to webpack-dev-middleware & vagrant directly sorry.

**Comment by sant123** [comment]
Any advance on this? It stays loading until request is canceled.

![image](https://user-images.githubusercontent.com/7959437/32955467-1320f278-cb84-11e7-80f0-ae561199f71d.png)
