### ISSUE TITLE
Global mixin memory leak leading to RangeError Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DKhalil** [nuxt/nuxt.js#7261]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/DKhalil/dayjs-locale-memory-leak-repro](https://github.com/DKhalil/dayjs-locale-memory-leak-repro)

### Steps to reproduce

```
$ yarn install
$ yarn build && yarn start
$ artillery run stress.yml
```

### What is expected ?

A normal execution of requests.

### What is actually happening?

The first thing you'll see is the requests getting slower and slower, after some point it'll crash with a Maximum call stack size exceeded error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10561">#c10561</a>)</em></sub></div>

**Comment by DKhalil** [comment]
Playing around with it further, I came to the conclusion that it was this piece of code that led to the leak:

```export default () => {
  Vue.mixin({
    methods: {
      doTheLeakyThing () {
        return ''
      }
    }
  })
}```

Changing it to

```Vue.mixin({
  methods: {
    doTheLeakyThing () {
      return ''
    }
  }
})```

fixes it.

**Comment by manniL** [comment]
See https://github.com/nuxt/nuxt.js/issues/7207
