### ISSUE TITLE
OOM upgrading Nuxt from 2.10 to 2.12

### ISSUE THREAD

**Issue by buremba** [nuxt/nuxt.js#7262]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

Our app is private but the mode is `spa` and we have more than 150 components in total.

### Steps to reproduce

We upgraded our app from 2.10.0 to 2.12.2 and the builds started to fail with the following exception:
```
nuxt build --spa

<--- Last few GCs --->

[236:0x3ca4090]    94279 ms: Scavenge 1285.1 (1416.2) -> 1284.2 (1416.7) MB, 2.5 / 0.0 ms  (average mu = 0.209, current mu = 0.179) allocation failure 
[236:0x3ca4090]    94284 ms: Scavenge 1285.1 (1416.7) -> 1284.3 (1417.2) MB, 2.3 / 0.0 ms  (average mu = 0.209, current mu = 0.179) allocation failure 
[236:0x3ca4090]    94291 ms: Scavenge 1285.2 (1417.2) -> 1284.3 (1417.7) MB, 3.6 / 0.0 ms  (average mu = 0.209, current mu = 0.179) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13b26be5be1d]
Security context: 0x2d10f3d9e6e9 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x3cd8a0e58d79] [/pipeline/source/node_modules/terser/dist/bundle.min.js:~1] [pc=0x13b26c8ed299](this=0x05dd0e5826f1 <undefined>,e=0x22dc915c3549 <AST_Number map = 0xd6f4a8e2919>,t=0x2636ed42c739 <Object map = 0x2f485b302621>)
    2: /* anonymous */ [0x1376af30c8d1] [/pipeline/source/node_modules/terser/dist/bundl...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [/usr/bin/node]
 2: 0x8dc55c  [/usr/bin/node]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xec7bf2  [/usr/bin/node]
 6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/bin/node]
 7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0xea07f4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/bin/node]
11: 0x114018e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
12: 0x13b26be5be1d 

<--- Last few GCs --->

[250:0x29d0090]    75148 ms: Scavenge 1319.5 (1415.5) -> 1318.6 (1416.0) MB, 2.0 / 0.0 ms  (average mu = 0.118, current mu = 0.082) allocation failure 
[250:0x29d0090]    75152 ms: Scavenge 1319.6 (1416.0) -> 1318.7 (1416.5) MB, 2.0 / 0.0 ms  (average mu = 0.118, current mu = 0.082) allocation failure 
[250:0x29d0090]    75156 ms: Scavenge 1319.6 (1416.5) -> 1318.7 (1417.0) MB, 2.1 / 0.0 ms  (average mu = 0.118, current mu = 0.082) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xc852025be1d]
    1: StubFrame [pc: 0xc8520254051]
Security context: 0x359abab9e6e9 <JSObject>
    2: split [0x359abab906c9](this=0x2958b1160ad1 <String[1]: )>,0x3a47ac50c0e1 <JSRegExp <String[5]: \r?\n>>)
    3: w(aka w) [0x818e8ae3f1] [/pipeline/source/node_modules/terser/dist/bundle.min.js:~1] [pc=0xc8521132aa9](this=0x2787dc7826f1 <undefined>,t=0x2958b1160ad1 <String[1]: )>)
    4: with_parens [0x818e8ae649] [/p...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [/usr/bin/node]
 2: 0x8dc55c  [/usr/bin/node]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xec7bf2  [/usr/bin/node]
 6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/bin/node]
 7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0xea07f4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/bin/node]
11: 0x114018e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
12: 0xc852025be1d
```

After adding `export NODE_OPTIONS='--max_old_space_size=4096'` it started working again but now the build time is around ~20 minutes, it's 2x of the average build time for the same project with 2.10. 

### What is expected ?

Memory usage should be stable

### What is actually happening?

nuxt build command fails

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10562">#c10562</a>)</em></sub></div>

**Comment by buremba** [comment]
Also see https://github.com/nuxt/nuxt.js/issues/5931 and https://github.com/nuxt-community/auth-module/issues/286#issuecomment-618445726

**Comment by pimlie** [comment]
Without reproduction we will never be able to look into this. I understand your project is private, but that means its really up to you to help us by creating a minimal reproduction which shows the same OOM.

OOM's can happen for many reasons, maybe its nuxt-auth maybe its not. You could try to add https://github.com/pimlie/nuxt-memwatch and see if this helps you with debugging

**Comment by buremba** [comment]
@pimlie I understand your point but this error occurs when you have more than 100 components so it's not possible to reproduce the bug in a jsfiddle. If you see other people complaining about the same issue in my previous message, there are many people who suffer from the same issue.

My point is that Nuxt doesn't perform efficiently on big projects especially on the latest builds, the issue resolves when we add `export NODE_OPTIONS='--max_old_space_size=4096'` but it takes 20 minutes for Nuxt to be compiled while it was 10 minutes on Nuxt 2.10.

**Comment by pimlie** [comment]
@buremba Within that linked auth issue people are already reporting different causes/solutions.

You can use https://codesandbox.io/ to show a full Nuxt project as reproduction. I know creating reproductions are difficult and can take a lot of time, but one of us will probably have to spent that time and honestly that really needs to be you as I dont have a project that shows this behavior. So for me it would be searching a needle in the haystack while you can compare the repro with your production project.

**Comment by buremba** [comment]
Considering `max_old_space_size` just increase the heap and I'm able to run `nuxt build --spa` with increased `max_old_space_size`, I can profile this command with [v8-profiler](https://github.com/node-inspector/v8-profiler) and share the dump with you so that we can see the slow execution paths and see where Nuxt is spending the time. (Here is an example I found: https://medium.com/@petar.koretic/profiling-slow-node-js-apps-using-v8-profiler-5d44c07bf09f)

I don't think that there is a specific bug so profiling may help to debug the performance. WDYT @pimlie ?

**Comment by pimlie** [comment]
Unfortunately debugging OOMs often isnt as simple as that. So please help us to help you and try to create that reproduction so we can both get our hands dirty while debugging the OOM.

**Comment by buremba** [comment]
OK, thanks for the clarification @pimlie. I will try to create pseudo components and reproduce the issue on Codesandbox.
