### ISSUE TITLE
Component duplication after bailing hidration on layout

### ISSUE THREAD

**Issue by arnaugiralt** [nuxt/nuxt.js#7264]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/nuxt-mismatching-child-nodes-vs-vnodes-layout-bug-nj8e9?file=/layouts/default.vue](https://codesandbox.io/s/nuxt-mismatching-child-nodes-vs-vnodes-layout-bug-nj8e9?file=/layouts/default.vue)

### Steps to reproduce

Just open the codeSandbox link, or:

Force a state mismatch between server and client in a layout.
Print on console:
```javaScript
function findDuplicatedComponents (root, str) {
  const found = [];
  const _str = str.toLowerCase();

  function findRecursive (node) {
    if (node.$children && node.$children.length) {
      for (const child of node.$children) {
        if (child._name.toLowerCase().includes(str)) {
          found.push(child);
        }
        findRecursive(child);
      }
    }
  }

  findRecursive(root);
  return found.length > 1 ? found : [];
}
var results = findDuplicatedComponents($nuxt, YOUR_COMPONENT_NAME_FULL_OR_PARTIAL);
results.forEach((result, idx) => {
  console.groupCollapsed(`INSTANCE ${idx}`);
  console.log('Name: ', result._name);
  console.log('Element: ', result.$el);
  console.log('VNode: ', result.$vnode);
  console.log('ID: ', result._uid);
  console.log('Parent: ', result.$parent);
  console.log('Parent: ', result.$parent);
  console.groupCollapsed('The instance itself:');
  console.log(result);
  console.groupEnd();
  console.groupEnd();
});
```

See that at least two instances show up on the console.

### What is expected ?

The usual warnings/errors that show when bailing hydration because of a difference in the state at the moment of rendering the template.

### What is actually happening?

Besides showing those errors, it appears that every component rendered in the view is created two times when bailing hydration.
This means that every nested component will be duplicated.

### Additional comments?

It is obvious that if anyone encounters an hydration error, the mismatch should be fixed, as it is an error, but I felt like this might be some bug somewhere deep inside.

I do not know if this is an issue only related to nuxt or if it is related to the vue ssr itself.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10563">#c10563</a>)</em></sub></div>

**Comment by arnaugiralt** [comment]
Might be related to #7232 , as the mismatch is happening on the layout as well

**Comment by pimlie** [comment]
I cannot reproduce this (anymore?) after forking your repro: https://codesandbox.io/s/nuxt-mismatching-child-nodes-vs-vnodes-layout-bug-v3e2x?file=/pages/about.vue

Its still showing the hydration error but no components from `printDuplicatedComponents` are logged when browsing to either `/` or `/about`

**Comment by arnaugiralt** [comment]
I was able to reproduce it again, forking your repro: https://codesandbox.io/s/nuxt-mismatching-child-nodes-vs-vnodes-layout-bug-9dvj2?file=/layouts/default.vue and just moving the `p` tag in `layouts/default.vue` from above to below the `<Nuxt />` component.

If you need more repro I'll try to set up a repo so we can have a proper diff to debug
