### ISSUE TITLE
npm version of @nuxt/babel-preset-app is not up to date

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#7268]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://www.npmjs.com/package/@nuxt/babel-preset-app](https://www.npmjs.com/package/@nuxt/babel-preset-app)

### Steps to reproduce

check out npm version of @nuxt/babel-preset-app

first the version there is higher than the one in master (2.12.2 vs. 2.12.1)
second the "bugfixes" option is not present in the docs (and also not in the source).

### What is expected ?

correct version / source of babel-preset-app

### What is actually happening?

old version is packed and published

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10566">#c10566</a>)</em></sub></div>

**Comment by manniL** [comment]
cc @clarkdo

**Comment by clarkdo** [comment]
@pi0 It looks like there is an unexpected 2.12.2 packages, do you have any idea why they are published  ?

**Comment by clarkdo** [comment]
@simllll The releases seem right, the release branch is 2.x not dev, we'll merge 2.x back to dev after release.

As `bugfixs` is a new feature, so it will be released 2.13.0.

**Comment by simllll** [comment]
Ah alright, wasn't aware of that. Thanks, looking forward to 2.13.0 then ;-)

**Comment by pi0** [comment]
Hi, @simllll release are correct. `2.12.1` and `2.12.2` released as hotfix to 2.x branch. For `nuxt` (stable) code reference, you should refer to [2.x](https://github.com/nuxt/nuxt.js/commits/2.x) branch not development.

New bugfixes option (#7144) added after 2.12.0 and will be available in `nuxt@2.13.0` (also currently `nuxt-edge`)
