### ISSUE TITLE
Nuxt generate suddenly serving wrong files while developing locally.

### ISSUE THREAD

**Issue by BhanuD19** [nuxt/nuxt.js#7272]
First of all I love working with Nuxt. 
But in my recent project I am facing a peculiar difficulty. I have a nuxt project which was working fine, but suddenly i ran npm run dev and the site served locally had totally wrong markup. 
The layout was displaying two header components, the pages were working but the displayed page was an older version of the pages and the pages themselves had gone through many changes after.
I am not able to solve this problem and I am not sure if this problem is in my local machine only.
Please help I need it for an upcoming client project which I have to finish fast.

i am using nuxt 2.12.2. The project is a universal app and is running in development mode.

[nuxt-config.pdf](https://github.com/nuxt/nuxt.js/files/4530295/nuxt-config.pdf)
![Screenshot 2020-04-24 at 10 25 51 PM](https://user-images.githubusercontent.com/26822704/80237890-16cf3880-867b-11ea-999a-15cd9b79e266.png)
![Screenshot 2020-04-24 at 10 25 38 PM](https://user-images.githubusercontent.com/26822704/80237904-1b93ec80-867b-11ea-985d-084baf3f4ab2.png)
![Screenshot 2020-04-24 at 10 25 21 PM](https://user-images.githubusercontent.com/26822704/80237911-1e8edd00-867b-11ea-9b6d-e05ea4ab93ac.png)

**Comment by lihbr** [comment]
See #7273
