### ISSUE TITLE
Nuxt generates wrong files while locally developing.

### ISSUE THREAD

**Issue by BhanuD19** [nuxt/nuxt.js#7273]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://www.github.com/BhanuD19/sugaardProject.git](https://www.github.com/BhanuD19/sugaardProject.git)

### Steps to reproduce

When we run npm run dev. The files served to local development will show the issue.

### What is expected ?

The files served should have the markup as dictated in the pages.

### What is actually happening?

The files served are having different markup than the actual files.
When run locally the page is served with two headers while there is only one header-outlet in layout. 
The video embedded should be displayed directly in jumbotron container as the markup says, but it is folded inside a cards component.
![Screenshot 2020-04-24 at 10.25.21 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/aac6e230-865e-11ea-93db-6946fcca484c.png)
![Screenshot 2020-04-24 at 10.25.38 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d7030a90-865e-11ea-93db-6946fcca484c.png)

### Additional comments?

I was thrown into this problem unexpectedly. The app was working fine and suddenly after changing some properties it started giving the wrong pages. I don't know if this is happening only in my machine, but I tried to serve the video which was first being served from the assets folder, from static folder by moving it there. After that, the app started behaving like this and the pages it served had the markup that would be generated from the previous version of the home/index.vue file which was edited a lot after that.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10570">#c10570</a>)</em></sub></div>

**Comment by BhanuD19** [comment]
PLEASE help me with this issue as I love working with nuxt and this is the first time I am encountering such problem. I have to prepare the project for a client so prompt reply would be appreciated.

**Comment by lihbr** [comment]
Hi @BhanuD19,

First of all header is displayed twice because you have it both on your [layout component](https://github.com/BhanuD19/sugaardProject/blob/devBranch1/layouts/default.vue) and on your [index page](https://github.com/BhanuD19/sugaardProject/blob/devBranch1/pages/index.vue). You can find more information about how layouts work wiht Nuxt here: https://nuxtjs.org/guide/views

As for the video component being wrapped in a `card` component its actually what's written on your code: https://github.com/BhanuD19/sugaardProject/blob/devBranch1/pages/index.vue#L8

But I noticed you were looking at the wrong file in your editor which is not available at `localhost:3000/` but at `localhost:3000/Home/` given your current project structure, so well... 😉 More information about Nuxt routing here: https://nuxtjs.org/guide/routing

Anyway this is definitely not a bug, also if you're looking for quick help regaring small mistakes like that you can join [Nuxt's discord](https://discord.nuxtjs.org)~

**Comment by BhanuD19** [comment]
Yes. I got to figure that part out about the index page and not the home/index. Also in home/index are my scss classes wrong.?Because my application keeps breaking on changing the scss.I tried resizing the video-section but instead got my whole video-section gone. I mean... Height was 0 but it was still rendered.Any help on that?On 25 Apr 2020 01:14, lihbr <notifications@github.com> wrote:

Hi @BhanuD19,

First of all header is displayed twice because you have it both on your layout component and on your index page. You can find more information about how layouts work wiht Nuxt here: https://nuxtjs.org/guide/views

As for the video component being wrapped in a card component its actually what's written on your code: https://github.com/BhanuD19/sugaardProject/blob/devBranch1/pages/index.vue#L8

But I noticed you were looking at the wrong file in your editor which is not available at localhost:3000/ but at localhost:3000/Home/ given your current project structure, so well... 😉 More information about Nuxt routing here: https://nuxtjs.org/guide/routing

Anyway this is definitely not a bug, also if you're looking for quick help regaring small mistakes like that you can join Nuxt's discord~

**Comment by BhanuD19** [comment]
Also, thank you so much for the quick reply. 🤗I'm glad that you helped me out with such a simple thing. 😅Also, I'll be looking out for that kind of mistakes in future. On 25 Apr 2020 02:07, vaibhav.dounde1996@hotmail.com wrote:Yes. I got to figure that part out about the index page and not the home/index. Also in home/index are my scss classes wrong.?Because my application keeps breaking on changing the scss.I tried resizing the video-section but instead got my whole video-section gone. I mean... Height was 0 but it was still rendered.Any help on that?On 25 Apr 2020 01:14, lihbr <notifications@github.com> wrote:

Hi @BhanuD19,

First of all header is displayed twice because you have it both on your layout component and on your index page. You can find more information about how layouts work wiht Nuxt here: https://nuxtjs.org/guide/views

As for the video component being wrapped in a card component its actually what's written on your code: https://github.com/BhanuD19/sugaardProject/blob/devBranch1/pages/index.vue#L8

But I noticed you were looking at the wrong file in your editor which is not available at localhost:3000/ but at localhost:3000/Home/ given your current project structure, so well... 😉 More information about Nuxt routing here: https://nuxtjs.org/guide/routing

Anyway this is definitely not a bug, also if you're looking for quick help regaring small mistakes like that you can join Nuxt's discord~
