### ISSUE TITLE
The new fetch syntax ignores watchQuery

### ISSUE THREAD

**Issue by andysleigh** [nuxt/nuxt.js#7281]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/youthful-minsky-pg6p6?file=/pages/index.vue](https://codesandbox.io/s/youthful-minsky-pg6p6?file=/pages/index.vue)

### Steps to reproduce

I've set up a simple CodeSandbox to demonstrate the issue. The index page has a fetch() method that just logs to the console, watchQuery is true, and there is a link which keeps amending the query. From the console logs you can see that fetch does not get called when the query changes. If you amend fetch to the old syntax (with a context parameter) then fetch gets called as expected - there's a separate page in the sandbox to demonstrate this.

### What is expected ?

When watchQuery is true and the query changes, fetch() should be called again.

### What is actually happening?

fetch() is not being called when the query changes.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10577">#c10577</a>)</em></sub></div>

**Comment by imzedi** [comment]
Same problem facing

**Comment by pimlie** [comment]
Please see the docs: https://nuxtjs.org/api/pages-fetch#listening-to-query-string-changes

**Comment by andysleigh** [comment]
In that case may I suggest that the documentation on watchquery (https://nuxtjs.org/api/pages-watchquery/) needs to be updated to match to avoid confusion, specifically the line below:

>Use the watchQuery key to set up a watcher for query strings. If the defined strings change, **all component methods** (asyncData, **fetch**, validate, layout, ...) will be called.

**Comment by pimlie** [comment]
@andysleigh We would love if you could help with that!

In the footer of that page there is a link that says `Edit this page on GitHub!`, feel free to update the documentation in a way that you feel is a clear description :)

**Comment by andysleigh** [comment]
@pimlie Thanks, I wasn't aware of that, I will give it a go :)
