### ISSUE TITLE
Index with optional param

### ISSUE THREAD

**Issue by JFGHT** [nuxt/nuxt.js#7282]
### What problem does this feature solve?

The use case is like this:

I want to have an index, which is in the root, with an optional param. I don't want this page to be ignored by nuxt generate since the index without param is fully known by Nuxt and fully workable.

The only approach I come with is duplicating the index.vue code into _id.vue but this is not how it should be.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10579">#c10579</a>)</em></sub></div>

**Comment by lihbr** [comment]
Hi @JFGHT ,

I can understand that duplicating the `index.vue` code into a `_id.vue` file might sound clunky though have you thought about juste importing / exporting this index components the `_id.vue` file? Something like that:

```vue
<script>
import Index from "~/pages/.../index.vue";
export default Index;
</script>
```

Then in your `asyncData` hook you could bring the logic to get the content you need with or without an id parameter?

**Comment by JFGHT** [comment]
That's a workaround, I guess.

I'm trying it now and when I go to the /param (`_id.vue`), the server says 404. Is it normal that Nuxt doesn't handle the routing and I have to do it myself server-side?
