### ISSUE TITLE
this.$nuxt.context.error inside the new fetch() hook does not work on SSR

### ISSUE THREAD

**Issue by FreekVR** [nuxt/nuxt.js#7285]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/hardcore-ganguly-485l1?file=/pages/index.vue](https://codesandbox.io/s/hardcore-ganguly-485l1?file=/pages/index.vue)

### Steps to reproduce

Try and catch an error using `this.$nuxt.error()` inside the new fetch() hook. Eg.

```
  async fetch() {
    try {
      throw new Error("something went wrong!");
    } catch (error) {
      this.$nuxt.context.error({
        status: 500,
        message: "Just a demo error message using $nuxt.context.error"
      });
    }
  }
```

Check the console.log in the repro, it shows:
```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

Inspecting the frame source there will show the server-rendered version as being the output of  `pages/index.vue` instead of the error layout.

### What is expected ?

The error layout is rendered, and is the same in server- and client.

### What is actually happening?

The server-rendered version of the page contains the page component output instead of the error layout. The client-rendered version of the page contains the correct output as in the error layout.

### Additional comments?

I wanted to use the nuxt error function similarly to how asyncData() allows us to do this, but inside the new fetch hook. This works fine client side, but SSR results in the original page output instead of using the error layout.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10585">#c10585</a>)</em></sub></div>

**Comment by javiercno** [comment]
#7232

**Comment by Atinux** [comment]
Please take a look at https://nuxtjs.org/blog/understanding-how-fetch-works-in-nuxt-2-12/#error-handling

**Comment by FreekVR** [comment]
Hey @Atinux ,

Alright, thanks for clarifying. I thought it'd be nice to share a common error layout, but I guess I could work around it with a custom `<error>` component in my app which I re-use both in the error layout and when using fetch :)

**Comment by Atinux** [comment]
Using an error component that you can re-use is a good idea :)

**Comment by whitewaterdesign** [comment]
Have built this based on info from: https://nuxtjs.org/docs/components-glossary/fetch/

It seems to avoid the hydration error issue. 

```
if (process.server) {
    this.$nuxt.context.res.statusCode = 404
    this.$fetchState.error = new Error('Post not found')
} else {
    this.$nuxt.error({ statusCode: 404, message: 'Page not found' })
}
```

**Comment by imzedi** [comment]
I did this workaround to fix the issue for now (for nuxt2).

If there is an error in the fetch hook, by doing this
- I can send a 404 from serverside (SEO)
- Switching an error layout on mounted

Page-level component

```
<template>
  <loading-skeleton v-if="$fetchState.pending" />
  <item-preview v-else-if="item" :item="item" />
  <to-error-layout v-else />
</template>

<script>
import ToErrorLayout from '@/components/Error.vue'

export default {
  components: {
    ToErrorLayout,
  },

  data() {
    return {
      item: null,
    }
  },

  async fetch() {
    try {
      const response = await this.$axios.get('/abc/xyz')
      this.item = response.data.item
    } catch (e) {
      if (process.server) {
        this.$nuxt.context.res.statusCode = 404 // Modify status code if needed
      }
    }
  },
}
</script>


```

Error.vue

```
<template>
  <div></div>
</template>

<script>
export default {
  mounted() {
    this.$root.error({ statusCode: 404, message: 'No results found' })
  },
}
</script>
```

**Comment by sinneren** [comment]
Is  `this.$nuxt.context.res.statusCode` similar to composition api `const { res } = useContext(); res.statusCode` ?
Cause I do this:
```
 const { error, res } = useContext();

  const handleErrorRequest = (err, fetchState) => {
    captureException(err?.data ? err.data : err);

    const statusCode = err?.status === 404 ? err.status : 500;

    if (process.server) {
      res.statusCode = statusCode;

      fetchState.error = new Error(`${statusCode} ${err?.message ?? ''}`);
    } else {
      error({ statusCode });
    }
  };
```
And it doesn't work with SSR.
