### ISSUE TITLE
Manually set loading page transition?

### ISSUE THREAD

**Issue by sbefort** [nuxt/nuxt.js#729]
Is there a way to manually set the loading page transition to use the same animation in other cases that are not route changes?

**Comment by pi0** [comment]
You can use something like this:

```js
            async login() {

                this.$root.$loading.start();

                try {
                    // ...
                } catch (e) {
                    console.log(e.message);
                }

                this.$root.$loading.finish();
            }
```

**Comment by sbefort** [comment]
Thanks that works awesome.

**Comment by sbefort** [comment]
This works on the client side in the `mounted` life cycle method.  But when I refresh the page, I get `Vue warn]: Error in mounted hook: "TypeError: this.$root.$loading.start is not a function"` in my client-side console.  Is my component being mounted before that function is available?  Is there any way around this?  Thanks!

**Comment by DaxChen** [comment]
Did you try to use

```js
if (process.browser) {
  // code to run only in browser
}
```

(or `process.BROWSER_BUILD` if version < 1.0.0-rc3)

**Comment by pi0** [comment]
@sbefort  please create a reproduction example or using [glitch](https://glitch.com/edit/#!/nuxt-hello-world)

**Comment by sbefort** [comment]
Here is a glitch:
https://sturdy-wave.glitch.me/

https://glitch.com/edit/#!/sturdy-wave

**Comment by dohomi** [comment]
I have a similar issue at the moment using the apollo-module. As I want the animation/loading spinner to wait till my graph-ql query is finished I would like to throttle the animation. Is there any way doing this?

**Comment by alexchopin** [comment]
Will be fixed in the next release. I'm closing it, but feel free to comment it in the future.

**Comment by javialon26** [comment]
@alexchopin same here with window.$nuxt.$root.$loading.start() or this.$root.$loading.start(). Will it be fixed in version 1? thank you!!!!

**Comment by unlockr** [comment]
I also have the problem in the "mounted"

**Comment by ruslankonev** [comment]
also need manual trigging loading actions

**Comment by jkd77** [comment]
I've noted that the code in [https://glitch.com/edit/#!/sturdy-wave](https://glitch.com/edit/#!/sturdy-wave) is still giving the "this.$root.$loading.start is not a function" error. Was this resolved?

nextTick doesn't seem to work for me. I get two errors: 
unknown action type: orders/fetchOrders 
and
TypeError: Cannot read property 'then' of undefined

Help?

**Comment by jkd77** [comment]
Hey Team - has there been any movement on this issue? Would really appreciate getting an update on current status.

**Comment by manniL** [comment]
@jkd77 Use `this.$nuxt.$loading` (docs: https://nuxtjs.org/api/configuration-loading#the-loading-property). If you still have issues, please create a new one.
