### ISSUE TITLE
Web Archive support - for better 

### ISSUE THREAD

**Issue by Triloworld** [nuxt/nuxt.js#7293]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://web.archive.org/web/20191224085425/https://www.webo.agency/](https://web.archive.org/web/20191224085425/https://www.webo.agency/)

### Steps to reproduce

Go to ANY Nuxt page that is generated
Save to WebArchiwe
Look on link - no JS/CSS visible

### What is expected ?

Full nice page ;)

### What is actually happening?

Broken static website

### Additional comments?

This will add possible for WebArchive to save in time websites. Even if domain won't be extend then we can have history of what Nuxt start and what sites used It in time

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10594">#c10594</a>)</em></sub></div>

**Comment by manniL** [comment]
Can't repro with https://web.archive.org/web/20191213071428/https://www.lichter.io/timeline/

**Comment by Triloworld** [comment]
Your "window.__NUXT__={layout:"default",data:[],error:null,serverRendered:!0}"
My is blown up. How it is that in generate mode?
Your source use different version as this isn't visible in main in script: "nomodule"
Can you check with my open source code before complain that is work ? :)

https://github.com/webo-agency/webo-frontend

**Comment by Triloworld** [comment]
Ok, I check your version vs my:

Your: https://github.com/manniL/lichter.io/blob/master/package.json
My:  https://github.com/webo-agency/webo-frontend/blob/main/package.json

This version isn't as my:
"nuxt-edge": "^2.11.1-26362097.b71eaee",

What is "nuxt generate --fail-on-error " different than normal generate when used in CLI enviroment? It won't fail normally?

You use:
" modern: !utils.isDev && 'client',"
I use "Legacy bundle" so it is different ;/

Sorry If I sound bad on reply, I will help If I can find clue what is going on :) This is not some "error" in console. It show "404" and my "window.NUXT is different". I have even "window.__WEBO__" so this "__" appear different even

**Comment by manniL** [comment]
Feel free to provide a **minimal version** of the problem (e.g. a stripped-down repo). I can't take the time to dive into full-blown projects as there are many more issue waiting 🙁.

> Your "window.NUXT={layout:"default",data:[],error:null,serverRendered:!0}"
My is blown up. How it is that in generate mode?

Because asyncData results are stored there for serialization.

> This version isn't as my:
> "nuxt-edge": "^2.11.1-26362097.b71eaee",
Shouldn't make a difference.

> What is "nuxt generate --fail-on-error " different than normal generate when used in CLI enviroment? It won't fail normally?

This will exit the build cmd when a site returns an error during generation, yes.

> You use:
> " modern: !utils.isDev && 'client',"
> I use "Legacy bundle" so it is different ;/

Modern mode should not influence the capabilities of loading

**Comment by Triloworld** [comment]
@manniL Hello. This error is gone in new Nuxt 2.13 with Full Static Page Cache. As no "window.__nuxt__" exist.
It is by proper serialization. I'am 100% sure that is error on filtering inputs. I try hard to ad many <client-only> and disable minify html or terser. Once was and once no error was give and sometimes show different place where start leak on footer. Bear in mind: this was half simple string cut. Maybe request was to heavy so in memory it was cut or some timing show up.
Thank you for giving so much time in this project. 

Issue is solve by updating to latest version.

**Comment by Triloworld** [comment]
Pleas remove staled tag as this was resolved :)
