### ISSUE TITLE
iOS 9: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt.js#7294]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://v2.thejewelleryroom.com](https://v2.thejewelleryroom.com)

### Steps to reproduce

1. Go to website on iPad on iOS 9.3.5
2. See console: "Unexpected keyword 'const'. Const declarations are not supported in strict mode."

### What is expected ?

No error should be thrown; should be handled by babel

### What is actually happening?

An error is being thrown: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10595">#c10595</a>)</em></sub></div>

**Comment by manniL** [comment]
You can always change your babel targets in your `nuxt.config.js` to match your needs. https://github.com/nuxt/nuxt.js/tree/dev/packages/babel-preset-app#example-1-change-targets-for-server-and-client-respectively
