### ISSUE TITLE
 Development WATCH (build to dist on changes) without local server or hot reloading.

### ISSUE THREAD

**Issue by RickKukiela** [nuxt/nuxt.js#7296]
### What problem does this feature solve?

My back end runs in PHP. The NUXT "hot loading" server running at localhost:3000 does not run a PHP compiler so I run my back end code an different host. This creates all kinds of headaches for me because of CORS and deployement ends up being different than development because in production all the files live together on the same host. This is a problem for me. I cant believe I'm the only one.

### What does the proposed changes look like?

All I want, is a command like "npx nuxt-watch" that would do something like "npm nuxt-generate" but instead of terminating at the end, it would stay running and update the required files in the dist folder on change.

From what I can tell there is no way to do this currently and that's really depressing me because I really want to use Nuxt and now I'm really regretting my choice to start this project with your framework :(

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10597">#c10597</a>)</em></sub></div>

**Comment by jleskovar-tyro** [comment]
+1

**Comment by pi0** [comment]
Hi! A new `nuxt serve` command is being added by #6159 but to avoid CORS issues, I would suggest to simply use [axios](https://axios.nuxtjs.org/options.html#proxy) or [http](https://http.nuxtjs.org/api/#proxy) modules to proxy API backend during development. 

Pro tip: You can also use [npm-run-all](https://www.npmjs.com/package/npm-run-all) or [PM2](https://pm2.keymetrics.io/) to run both backend and nuxt with a single command.

**Comment by RickKukiela** [comment]
I'll have to look into using proxies I had never needed them before so I wasnt sure on how to set that up. I'm glad to know there is as serve command being added that will address this issue though!

I was able to work around my issue by finally getting my global axios config working via an axios plugin. I was having trouble getting "withCredentials" and my qs.stringify working globally for my transformRequest (onRequest intercepteptor). I finally did get it working with this plugin code (in case anyone else has problems with this in the future):

~/plugins/axios.js
```
import { stringify } from 'qs'

export default function ({ $axios }) {
    $axios.onRequest(config => {

        // fix post data so I can pass JS object and have it converted properly
        config.transformRequest = function(data) {
            return stringify(data);
        }

        // force with credentials to bypass CORS problems
        config.withCredentials = true;

        // Override url based on development or live (auto - prefix request url - optional)
        config.url = "http://hostname.local/" + config.url;
    });
}
```
