### ISSUE TITLE
Upgrade Vuex to latest version

### ISSUE THREAD

**Issue by StummeJ** [nuxt/nuxt.js#7301]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://na.com](https://na.com)

### Steps to reproduce

Write a test the uses local vue and use vuex with it.  The store is not defined in the component.

### What is expected ?

Using the latest version of vuex (3.3.0) and allow localvue to work

### What is actually happening?

You need to add vuex to the global vue, which has been deemed to be bad... like for a good while now :roll_eyes: 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10601">#c10601</a>)</em></sub></div>

**Comment by manniL** [comment]
As usual with minor version updates, you can already do that on your own by using `yarn upgrade` for example, as `3.3.0` fits the constraint of `^3.x.y`. As a proof - a newly created nuxt project which will always have the latest minor/patch version of dependencies unless pinned.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/640208/80861058-665dc780-8c6c-11ea-81f9-d7ac27c70906.png">
