### ISSUE TITLE
Aliases not working because jsconfig.json is missing

### ISSUE THREAD

**Issue by RecuencoJones** [nuxt/nuxt.js#7303]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/ainochu/nuxt-photo-blog/tree/0253b4411caf183774a4e4b93cb3a47758417099](https://github.com/ainochu/nuxt-photo-blog/tree/0253b4411caf183774a4e4b93cb3a47758417099)

### Steps to reproduce

For repo:
- Clone
- npm install
- npm run dev

Without repo:
- Create a new nuxt project from scratch as per https://nuxtjs.org/guide/installation/#starting-from-scratch
- Create a `data.json` file within assets directory
- Create `index.vue` under pages directory
- Attempt to load the json file in asyncData using `await require('~/assets/data.json')`

Run `npx nuxt`

An error will be raised: "This dependency was not found"

### What is expected ?

Everything is fine

### What is actually happening?

The project will fail to compile because jsconfig.json is missing!

I think it would be worth mentioning that in https://nuxtjs.org/guide/directory-structure#aliases

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10603">#c10603</a>)</em></sub></div>

**Comment by pimlie** [comment]
require doesnt return a promise so adding await isnt needed and may cause an issue.

On a higher level, why are you requiring in asyncData? I would be surprised if this has any (performance) benefit above just using an import and use/return that import in asyncData.

**Comment by RecuencoJones** [comment]
Hi @pimlie!

You are right, require is blocking and will return contents directly, so await is not necessary.
There was a use case for require in asyncData to load different blog entries based on params:

https://github.com/ainochu/nuxt-photo-blog/blob/0253b4411caf183774a4e4b93cb3a47758417099/pages/blog/_blog.vue#L14

Indeed, I've just tested locally and dynamic import works just fine.

```
export default {
  async asyncData({ params }) {
    return import(`~/assets/content/blog/${params.blog}.json`).then((data) => ({
      blogPost: data.default
    }));
  }
};
```

Also, I cannot reproduce the problem with `~` alias in my machine, so will once more review the setup with @ainochu 

Thanks!
