### ISSUE TITLE
Is the generated site not for static hosting?

### ISSUE THREAD

**Issue by irrg** [nuxt/nuxt.js#731]
I might be crazy, but I figured I'd ask.

I've started a new blank project based on https://github.com/nuxt/starter 
After verifying that `yarn run dev` works, I tried `yarn run generate` and put the resulting code from `.nuxt/dist/` on a static localhosted site. There are still handlebar tags in the generated index.html and while the JS doesn't error, nothing is rendered.

Example that I put up real quick: http://eargang.com/

Can you tell me if I'm misunderstanding that I can `generate` a working nuxt (vue) site that can be hosted on any static site or on `gh-pages`? Is the index.html that's being generated wrong for this purpose?

**Comment by jsonberry** [comment]
@irrg 
Ah, yeap! Wrong folder.
Do not use: `project/.nuxt/*`
Use: `project/dist`

**Comment by irrg** [comment]
Okay, awkward. Thanks for pointing that out! I'm sure this was my poor reading skills, but it could be more clear in the docs!

**Comment by jzucadi** [comment]
This doesn't work still. The files in the dist folder still don't work due to bad links. I've never been able to generate any static sites without having to manually fix the links afterwards
