### ISSUE TITLE
Parameter should be required but is generated as optional.

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#7310]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/youthful-kalam-ldsjs?file=/pages/nested/_slug/index.vue](https://codesandbox.io/s/youthful-kalam-ldsjs?file=/pages/nested/_slug/index.vue)

### Steps to reproduce

In the reproduction link, open a new terminal and inspect `.nuxt/router.js` (`cat .nuxt/router.js`)

Additionally I have the following page structure (it is required to have the root `index.vue` page to reproduce.
```
pages/
    index.vue
    toolkits/
        workforce/
            _category/
                index.vue
```

Possibly Related: #7298

I have gone back to version 2.6.x where this issue was still happening. Looks like it's an bug that was introduced a long time ago.

### What is expected ?

A required argument/parameter
```
{
    path: "/toolkits/workforce/:category",
    component: _10f10a5c,
    name: "toolkits-workforce-category"
}
```

### What is actually happening?

An optional parameter
```
{
    path: "/toolkits/workforce/:category?",
    component: _10f10a5c,
    name: "toolkits-workforce-category"
}
```

### Additional comments?

For anyone else coming across this problem, my only solution is to use the `extendRoutes` option in `nuxt.config.js`. I find and remove the route now I renamed the index page to `/home.vue` and re-add it with the `/` path.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10606">#c10606</a>)</em></sub></div>

**Comment by pimlie** [comment]
`_category/index.vue` is treated the same as `_category.vue`. The docs indeed specify to create a index.vue if you want a required param, but that should be on the same level as `_category`.

So this should work:
```
pages/
    index.vue
    toolkits/
        workforce/
            _category.vue
            index.vue
```

**Comment by silverbackdan** [comment]
Thank you for taking a look into this for me @pimlie ! In the solution you've posted, there is an additional page which isn't needed `toolkits/workforce/index.vue` I only need `toolkits/workforce/_category/index.vue` and the home page and the routes are generated like this. Sorry if I'm missing something in this answer.

**Comment by pimlie** [comment]
Unfortunately using the file system to define your app routes comes at a cost, this is unfortunately one of them.

You can always 'hack' your way around the generates routes object yourself, either by using the [router-extras-module](https://github.com/nuxt-community/router-extras-module) or by manually manipulating the routes through [extendRoutes](https://nuxtjs.org/api/configuration-router#extendroutes)

**Comment by silverbackdan** [comment]
The router-extras-module is an interesting one I hadn't seen, probably a nicer hack that what I have done with the `extendRoutes` option. It's also an interesting point about the structure you've shown and how that ends up making the parameter required. Possibly worth rethinking to make sure there is a path for every sub-level, even if it's just a redirect.

Thank you again! ❤️
