### ISSUE TITLE
extract css broken when using "srcDir" (dev mode only)

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#7315]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://hokify-data.s3.eu-central-1.amazonaws.com/nuxt-src-dir-bug.zip](https://hokify-data.s3.eu-central-1.amazonaws.com/nuxt-src-dir-bug.zip)

### Steps to reproduce

It's a typical monday it seems, another weird bug I just discovered: When using a srcDir, extractCss: true and a webpack plugin (like eslint-loader) the css in dev mode is broken when loaded via SSR only (no JS enabled).

Therefore it looks like this (I disabled JS in chrome developer console, if you don't you will see a flickering, but css is loaded as soon as client hydration kicks in):
![image](https://user-images.githubusercontent.com/5757263/81009545-27d73100-8e55-11ea-9ba0-0bf7bbdf13a5.png)

When I now remove the srcDir option in the nuxt.config.js (For easy testing I've added all files twice  in the zip package, once in the src dir and once in the root), the css starts working again. As a funny side effect, if I remove the "eslint-loader" which is only included in the CLIENT build, it also starts working? How is this even related?! 
![image](https://user-images.githubusercontent.com/5757263/81009616-42110f00-8e55-11ea-870a-1beaa77ee002.png)
(working with no srcDir set or remove eslint-loader plugin from webpack client build.)

### What is expected ?

CSS should work in dev mode on SSR

### What is actually happening?

No page CSS is loaded, only via JS when the page is initialised.

### Additional comments?

I can overcome this in the dev mode for now with disabling extractCSS, but it just seems super strange and would like to know what is going on here.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10610">#c10610</a>)</em></sub></div>

**Comment by pimlie** [comment]
Out of curiosity, why do you develop with JS disabled? This seems like a super low prio issue to me at least, but I might be missing what you are trying to do

**Comment by simllll** [comment]
Thanks @pmlie for looking into it, it's just a demo to narrow down the issue. You are right, usually I do not have JS disabled, but to demonstrae the bug, it's easier ;).

The real problem here is, that on SSR side the css is not extracted correctly.

And this seems to be a weird side effect of somethign else. We experience this on our main app for different components, which are missing CSS then. Especially because we are using "lazy hydration" heavily, which delays the hydration of the component to some later time, makes this even worse, because the initial CSS is not applied correclty and the compnoent is therefore broken. But also for regular use cases this breaks web performance, as the css is "changed" or applied only on client rendering. Which means the website "flickers" and performance benachmarks are going down.

Therefore I don't think this is low prio as this affects:
* a lot of different websites
* breaks crawling (SEO)
* slows down the perceived performance for the user

**Comment by pimlie** [comment]
Thanks for the detailed response, really appreciate when people take the time to explain the issue thoroughly.

If it only affects dev mode, isnt this just because of https://nuxtjs.org/faq/css-flash#__layout ?

**Comment by simllll** [comment]
Thanks, indeed, this seems at least related. Somehow I haven't seen this link yet, thanks for pointing it out! Weird is thing is, this only happens with "extractCSS: true" though.

I couldn't really figure out what's causing it, but it looked like a bug as it was different with some settings which shouldn't be related at all (e,g, disabling eslint-loader made it work with extractCSS enabled). Therefore it looked like a side effect to me and I assumed this must be a bug. 

After this new information, I'm not sure if it's intended behaviour and/or the documentation is missing some details (e.g. FOUC is only happening for extractCSS in some cases, which would "some" sense and would also describe my behaviour) or it's still a bug.
