### ISSUE TITLE
[FOUC] Imported CSS  in page not included during ssr

### ISSUE THREAD

**Issue by mathieutu** [nuxt/nuxt.js#7320]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/lights0123/nuxt-css-issue](https://github.com/lights0123/nuxt-css-issue)

### Steps to reproduce

When we import some css directly in script, or js files from a page, the css will not be included in the server side rendered head.

It will only be injected at runtime.

It's the same with the extractCss property, the extracted css files are **not** included via link balises.

Surprisingly, it works well in layout!

We can see that well with generate build and by disabling javascript on the page.

### What is expected ?

The included CSS, assets/test.css, should be inlined into the page as a <style>  or <link> element when generated into a static page, instead of being added by JS later.

### What is actually happening?

Only CSS defined in a local <style> element is inlined. If Javascript is disabled, then this CSS never gets loaded, as it requires JS to include in the page.

### Additional comments?

Actually this is a duplicate of https://github.com/nuxt/nuxt.js/issues/6753, which was closed without any comment.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10616">#c10616</a>)</em></sub></div>

**Comment by mathieutu** [comment]
I'm just realizing: maybe is it because of the chunk spliting of pages? 🤔

I'll investigate in that way and let you know.

**Comment by simllll** [comment]
Importing css like this is actually a "side effect" - import, speaking from some own troubles with this, I strongly suggest not doing something like this. Try just using a regular style tag.

e.g. instead of
` import '~/assets/test.css';` inside script you could just add 

`<style src="~/assets/test.css"></style>`

in the template

**Comment by mathieutu** [comment]
Actually I have no choice of it 😕, the css import is done in a file in node_module, I personally import a js file.

**Comment by simllll** [comment]
Ah, can you check the side effect property of the node modules package.json file.

See also https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free.
You need to ensure that sideeffects is NOT set to false or at least it contains an exception for Vue and css files.

**Comment by mathieutu** [comment]
Ok thanks.

In my particular case the side effect seems to be set properly : https://github.com/vueComponent/ant-design-vue/blob/master/package.json
Actually this is a feature of them, with a babel plugin. When you import the component, it import the JS, and the css file: https://www.antdv.com/docs/vue/introduce#Use-modularized-antd

But this issue is quite general in fact, imo importing css directly in js via webpack is a common usage, isn't it?

**Comment by simllll** [comment]
Right,
maybe you can find a workaround when looking at other libraries (e.g. vuetify has a similar issue).
See for a workaround solution: https://github.com/vuetifyjs/vuetify-loader/pull/126

Regards

**Comment by mathieutu** [comment]
Thanks I'll take a look at this one!

Noob speaking again, the ideal would be a nuxt solution, so libraries dont need to all implement the same things.

Thank you anyway for your help on this issue!
