### ISSUE TITLE
Nuxt app behind nginx proxy loading multiple pages at once

### ISSUE THREAD

**Issue by imfaisalkh** [nuxt/nuxt.js#7322]
I've a nuxt.js app behind nginx reverse proxy. The nginx conf file looks like this:

```
  server {
    listen 80;
    # Match *.lvh.me
    server_name  ~^(?<user>.+)\.lvh\.me$;

    location / {
      proxy_pass http://localhost:8080/sites/$user$uri$is_args$args;
    }

    location ~* \.(?:js|css|jpg|jpeg|gif|png|ico|cur|svg)$ {
      proxy_pass http://localhost:8080;
    }

  }
```
As you can see I'm mapping all my site subdomains to a specific path on my site and it is working fine. I'm also mapping all assets to be loaded from the root (because otherwise it throws a 404 error).

The only issue I'm facing is the whenever I visit a subdomain e.g subdomain.lvh.me it loads two pages on top of each other, the original page from subdomain root (which is expected) but also the page from the main domain root i.e. lvh.me (which is not expected).

Can you please checkout my conf file to see if I'm doing anything wrong here? Or is it a bug with nuxt?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10619">#c10619</a>)</em></sub></div>

**Comment by fparaggio** [comment]
did you solve?

**Comment by imfaisalkh** [comment]
> 
> 
> did you solve?

No, I ended up creating a separate nuxt app specifically for my subdomain pages.
