### ISSUE TITLE
Jest coverage problem, 50% of non-existing branch is not tested

### ISSUE THREAD

**Issue by Uzwername** [nuxt/nuxt.js#7323]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/Uzwername/jest-coverage-problem-reproduction](https://github.com/Uzwername/jest-coverage-problem-reproduction)

### Steps to reproduce

1. Clone repository (see reproduction link).
2. Install node_modules
3. Run `npx jest --coverage`
4. Go to coverage->lcov-report folder & open index.html in a browser.
5. Check report for file "TheDesktopNavigation.vue"
6. See the first line with `<template>` tag highlighted with yellow.
7. Try to comment out all export's content in script tag of `TheDesktopNavigation.vue`.
8. Repeat steps from 3 to 6 (the issue will persist). 

### What is expected ?

Report should show 100% coverage

### What is actually happening?

The `<template>` tag is highlighted with yellow (which means uncovered branch) while there's only 5 lines of JS with 0 logical branches in the file.

### Additional comments?

As a side note, other very similar components that follow the same folder/test structure work ok & show 100% coverage.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10620">#c10620</a>)</em></sub></div>

**Comment by TimvdEijnden** [comment]
@Uzwername When replacing your contents within `<template>` with

`<FaIcon :icon="faCaretRight" />` 

I does show 100% coverage, also for branches.

![Screenshot 2020-05-13 at 10 35 08](https://user-images.githubusercontent.com/951290/81790302-852e4a80-9505-11ea-997d-f87b1c7173d0.png)

It seems you have to double check the contents of the `<template>`
