### ISSUE TITLE
Nuxt-child rendered multiple times in nested route with component

### ISSUE THREAD

**Issue by jillztom** [nuxt/nuxt.js#7324]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/romantic-browser-nih1p](https://codesandbox.io/s/romantic-browser-nih1p)

### Steps to reproduce

1. Open the CodeSandBox reproduction link
2. Navigate to the `posts/1/view` route. 
3. Observe the 'Go back' link appearing multiple times
4. Check the network tab
5. The api call from the fetch() hook is triggered multiple times.

### What is expected ?

Expected to see the body of the `post/1` with a 'Go Back' button. 

### What is actually happening?

The page component `view.vue` file is being rendered multiple times infinitely. If an API call is present in the `fetch()`, will be called infinite times. 

### Additional comments?

I noticed this behaviour occurs only in the following condition: 

The nested route is using a component with the same name as the page component. In this case, the file `pages/posts/_id/view.vue` file is using a component from `components/Contents/Post/View.vue` and is exported as `<PostView>`. The component name for the page is also given as `PostView`. If I change this name to something else, this behaviour does not happen. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10621">#c10621</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @jillztom 

I am not sure to understand why you use `<nuxt-child/>` in https://codesandbox.io/s/romantic-browser-nih1p?file=/pages/posts/_id/view.vue

**Comment by jillztom** [comment]
Hi @Atinux 
Ignore that `<nuxt-child />` inside the `view.vue` file, that was a mistake. The loop still exists without that.

**Comment by Atinux** [comment]
Ok that is weird, will look at it :)

**Comment by Atinux** [comment]
Alright, this is not related to `fetch`, if you `console.log` in `created` hook it will also logs infinitely.

This is because you use the same `name` for the page component as the `PostView` component you are importing...

Removing the `name` fixes it in [pages/posts/_id/view.vue](https://codesandbox.io/s/romantic-browser-nih1p?file=/pages/posts/_id/view.vue):
```js
import PostView from "~/components/Contents/Post/View";

export default {
  // name: "PostView",
  components: {
    PostView
  },
  async fetch() {
    this.post = await this.$axios.$get(
      "https://jsonplaceholder.typicode.com/posts/1"
    );
  },
  data() {
    return {
      post: null
    };
  }
};
```
