### ISSUE TITLE
CSS in HTML head AND in JS chunk

### ISSUE THREAD

**Issue by danielkellyio** [nuxt/nuxt.js#7325]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/danielkellyio/duplicated-css-example/tree/master/dist/_nuxt](https://github.com/danielkellyio/duplicated-css-example/tree/master/dist/_nuxt)

### Steps to reproduce

The repo provided is a fresh install of nuxt using the npx command. All that's need to reproduce is:
1. Create a new project with `npx create-nuxt-app <project-name>`
2. Run `npm run generate`

### What is expected ?

I would expect the css styles to only be downloaded to the browser once (through a single avenue, probably the html). 

### What is actually happening?

The styles are included in both the html and in one of the javascript chunks. (See `dist/index.html` and `dist/_nuxt/9f82b813f89f07691fc9.js`)

I would think this is a pretty big performance issue, loading the exact same styles twice (especially since I'm using the Bulma library for my styles which is decent in size).

### Additional comments?

Was trying to optimize the performance of my Nuxt site and noticed one my JS chunks was quite large. Much of it ended up being Bulma styles. This being a statically generated site, one of my goals is to squeeze every last bit of performance out of it as I can.

I'm loving Nuxt! Thanks for all the hard work that has been put into this awesome framework!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10622">#c10622</a>)</em></sub></div>

**Comment by pimlie** [comment]
You could probably prevent this by setting [`build.extractCSS: true`](https://nuxtjs.org/api/configuration-build#extractcss)

The css in `index.html` is there because you generated your site which mean index.html contains your fully pre-rendered vue-app for the `/` route. The css is included in the chunk because when you would have a second page `about.html` then that would only include the css for `/about` and not `/`. When you would then navigate to `/` you are navigating _within_ `about.html` so the css for `/` needs to come from somewhere.

**Comment by danielkellyio** [comment]
I'm not sure I want to extract css from all the components and serve them individually, I think that would be unnecessary extra server calls. I think for now just having the main styles load in via html and js is my best option (just my gut instinct, no testing on this).

I think there could still be some optimizing done on this in nuxt core. Most websites have a base set of styles that are required on every page and don't need to be hydrated on navigation to a new page because it's always the same. Perhaps this is a feature that could be added. 

If that sounds like something worth pursuing, let me know and I'd be happy to poke around a bit and attempt a PR for it. And if that's the case a hint on where to start looking would be much appreciated

Thanks!
