### ISSUE TITLE
Applying route.render to a specific route in express causes problems

### ISSUE THREAD

**Issue by hoiheart** [nuxt/nuxt.js#7329]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/hoiheart/nuxt-issue-demo/tree/express-route](https://github.com/hoiheart/nuxt-issue-demo/tree/express-route)

### Steps to reproduce

applying nuxt only to specific routes in express

```javascript
app.use(['/hello/', '/:lang/hello/'], nuxt.render)
```

### What is expected ?

Same behavior as nuxt dev server

### What is actually happening?

Routing errors and publicPath errors occur

![1.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/9e0ba450-90a8-11ea-9ad5-fb2911357d58.png)

### Additional comments?

- I am trying to call several nuxt apps by route in express. (Would you give me any additional advice on this way?)
- The router base option is not available for using i18n.
- The actual publicPath path exists in the same location as the route path.
```
http://localhost:3000/hello/_nuxt/runtime.js
http://localhost:3000/:lang/hello/_nuxt/runtime.js
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10627">#c10627</a>)</em></sub></div>

**Comment by NuclleaR** [comment]
trying the same but with Koa, seems like doesn't work for me as well

**Comment by hoiheart** [comment]
I actually use fastify and the same issue occurs in it.

**Comment by Atinux** [comment]
Hi :wave:

Actually Nuxt uses `req.url` to determine the path to display the page (see [packages/server/src/middleware/nuxt.js#L12](https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/middleware/nuxt.js#L12))

When you use `app.use(['/hello'], nuxt.render)` and navigating to `/hello`, `req.url` will be equal to `/` so Nuxt will try to display the `index.vue` page.

To fix this, you need to set `req.url = req.originalUrl` before calling `nuxt.render`:

```js
app.use(['/hello', '/:lang/hello/'], (req, res) => {
  req.url = req.originalUrl
  nuxt.render(req, res)
})
```

Now going to http://localhost:3000/hello/ will work 😊

**Comment by hoiheart** [comment]
@Atinux 
Thank you very much!!
I'll try it 😃

**Comment by hoiheart** [comment]
@Atinux 
The problem has been resolved, but the HMR path cannot be called.
![Untitled-1](https://user-images.githubusercontent.com/25652218/82006160-2225ea80-96a2-11ea-9274-0f5381f7a338.jpg)

**Comment by hoiheart** [comment]
Several manual settings are needed to implement it.
Finally, the setup I wanted was completed.

1. Matching routes path
```javascript
/* Add in nuxt.config.js */

extendRoutes (routes) {
  routes.map(route => {
    route.path = `/hello${route.path}`
  })
}
```

2. Modify webpack publicPath & HMR
```javascript
/* index.js */

const express = require('express')
const { Nuxt, Builder } = require('nuxt')
const app = express()

// Import and Set Nuxt.js options
const config = require('./nuxt/nuxt.config.js')
config.dev = process.env.NODE_ENV !== 'production'
config.rootDir = './nuxt'
config.build = {
  ...config.build,
  publicPath: '/hello/_nuxt/'
}

// Modify webpack HMR
if (config.dev) {
  config.build = {
    ...config.build,
    hotMiddleware: {
      path: '/hello/__webpack_hmr/client'
    }
  }
  config.hooks = {
    ...config.hooks,
    'webpack:config': (webpackConfigs) => {
      return webpackConfigs.map(option => {
        if (option.name === 'client') {
          option.entry.app = option.entry.app.map(item => {
            return item.replace('path=', 'path=/hello') // &path=/hello/__webpack_hmr/client
          })
        }
        return option
      })
    }
  }
}

async function start () {
  // Init Nuxt.js
  const nuxt = new Nuxt(config)

  const { host, port } = nuxt.options.server

  await nuxt.ready()
  // Build only in dev mode
  if (config.dev) {
    const builder = new Builder(nuxt)
    await builder.build()
  }

  // Give nuxt middleware to express
  app.use(['/hello', '/:lang/hello/'], (req, res) => {
    req.url = req.originalUrl
    nuxt.render(req, res)
  })

  // Listen the server
  app.listen(port, host)
}

start()
```
