### ISSUE TITLE
Deployment failed in Azure 

### ISSUE THREAD

**Issue by chenmingjia** [nuxt/nuxt.js#733]
I wrote the basic code by using express and nuxt, as followed ：

./package.json:
```
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start"
  },

```
./pages/index.vue:
```
<template>
  <p>Hello world</p>
</template>

<script>
export default {
  data: () => {
    return { name: 'world' }
  }
}
</script>
```

./server.js:
```
// Import and Set Nuxt.js options
let config = require('../nuxt.config.js')
config.dev = !(process.env.NODE_ENV === 'production')

// Init Nuxt.js
const nuxt = new Nuxt(config)
app.use(nuxt.render)

```

**!!!! The development environment is working normally 。 However, the deployment environment cannot be started properly  !!!!!  `**`

------------------------------------

Total 3 (delta 2), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '38570f0049'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling node.js deployment.
remote: KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
remote: Copying file: 'package.json'
remote: Looking for app.js/server.js under site root.
remote: Using start-up script server.js
remote: Generated web.config.
remote: The package.json file does not specify node.js engine version constraints.
remote: The node.js application will run with the default node.js version 6.9.1.
remote: Selected npm version 3.10.8
remote: Invalid start-up command "nuxt start" in package.json. Please use the format "node <script relative path>".
remote: ..................
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
remote: npm WARN nodejs-web-app@0.0.0 No repository field.
remote: npm WARN nodejs-web-app@0.0.0 No license field.
remote: Finished successfully.
remote: Running post deployment command(s)...
remote: Deployment successful.

**Comment by pi0** [comment]
@chenmingjia Please check this package.json modifications:
```json
"scripts": {
"dev": "node ./node_modules/nuxt/bin/nuxt dev",
"build": "node ./node_modules/nuxt/bin/nuxt build",
"start": "node ./node_modules/nuxt/bin/nuxt start"
}
```

**Comment by chenmingjia** [comment]
The page was successfully deployed, but the home page cannot load,
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

------------
remote: .................
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
remote: npm WARN nodejs-web-app@0.0.0 No repository field.
remote: npm WARN nodejs-web-app@0.0.0 No license field.
remote: Finished successfully.
remote: Running post deployment command(s)...
remote: Deployment successful.

**Comment by chenmingjia** [comment]
Also, this example I can't open properly after deployment in Azure
https://github.com/nuxt/express

**Comment by pi0** [comment]
That warnings seem normal (fsevents is only supported on mac) Are you sure `npm run build` is triggered on azure? [Check here](https://www.visualstudio.com/en-us/docs/build/apps/node/nodejs-to-azure#add-the-build-steps)

**Comment by chenmingjia** [comment]
I'm not sure whether `npm run build` has been successfully triggered, I used to think it would trigger automatically，I'll look at the documentation again. Thank you

**Comment by chenmingjia** [comment]
I command ‘npm run build ’  on the local git project，then git push to Azure，but it still doesn't work

**Comment by pi0** [comment]
I think azure should ignore `.gitignore` dirs including `.nuxt` and build should run on azure :)) (Unfortunately i have no azure account to do tests myself so just giving advises here!)

**Comment by chenmingjia** [comment]
I know why it went wrong，nuxt is also `Ready on http://127.0.0.1:3000 `，but 
Cloud platform has its own dynamic port by environment variable , such as process.env.LEANCLOUD_APP_PORT


I want to know how nuxt binds port based on environment variables

**Comment by pi0** [comment]
Currently you can do this by something like this:

(nuxt.config.js)
```js
// Set nuxt port
process.env.PORT = process.env.PORT || process.env.LEANCLOUD_APP_PORT

module.exports = {


}

**Comment by horihiro** [comment]
Hi @chenmingjia ,
Did you use Azure WebApps on Windows?

I found some problems for working on Azure WebApps.
I wrote about the problems in [this](https://cmty.app/nuxt/express-template/issues/c109).

I hope that this helps you to solves your problem.
