### ISSUE TITLE
NuxtJS child dynamic pages not being navigated to/rendering with nuxt-link

### ISSUE THREAD

**Issue by jasonday** [nuxt/nuxt.js#7330]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://stackoverflow.com/questions/61668854/nuxtjs-child-dynamic-pages-not-being-navigated-to-rendering-with-nuxt-link](https://stackoverflow.com/questions/61668854/nuxtjs-child-dynamic-pages-not-being-navigated-to-rendering-with-nuxt-link)

### Steps to reproduce

If my file structure is:
```
- pages
-- catrules.vue
-- catrules/
---- _id.vue
```

The child page does not render (but the url updates and the page stays on the parent):
`<nuxt-link :to="'/catrules/' + catrule.slug">{{ catrule.ruleid }}</nuxt-link>`

If I change the name of the the directory `catrules` to `catrule`, then everything works as expected:
```
- pages
-- catrules.vue
-- catrule/
---- _id.vue
```
`<nuxt-link :to="'/catrule/' + catrule.slug">{{ catrule.ruleid }}</nuxt-link>`

### What is expected ?

That child pages will render when using nuxt-link

### What is actually happening?

Child pages are not rendering. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10628">#c10628</a>)</em></sub></div>

**Comment by TimvdEijnden** [comment]
@jasonday  Your question is already answered on SO
https://stackoverflow.com/a/61689956/519820
