### ISSUE TITLE
Development Server Crashing on Selecting Ant Design UI Framework

### ISSUE THREAD

**Issue by bacon-delight** [nuxt/nuxt.js#7333]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/bacon-delight/nuxt-error-report](https://github.com/bacon-delight/nuxt-error-report)

### Steps to reproduce

npm run dev - Development server fails to start and crashes

What I did:
- npx create-nuxt-app cares
- Selected Ant Design and other options
- cd cares
- npm run dev

### What is expected ?

Development server should run

### What is actually happening?

Development server is crashing
![Screenshot 2020-05-08 at 5.52.15 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/8aefb9e0-9127-11ea-a913-f1326830a1d1.png)

### Additional comments?

I just created a nuxt app and couldn't even start the development server for once.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10632">#c10632</a>)</em></sub></div>

**Comment by seifsay3d** [comment]
Hello, I took a look at this one.

It is because of a missing file in ant-design-vue.

please upgrade to `"ant-design-vue": "1.5.4",`


Here is a[ link for the issue](https://github.com/vueComponent/ant-design-vue/issues/2219) on ant-design-vue for more information

**Comment by Atinux** [comment]
Thank you @seifsay3d for looking at it 🙌
