### ISSUE TITLE
Loads the current page and the page that starts navigation

### ISSUE THREAD

**Issue by MauricioHernanCabrera** [nuxt/nuxt.js#7337]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/MauricioHernanCabrera/bug-nuxt/](https://github.com/MauricioHernanCabrera/bug-nuxt/)

### Steps to reproduce

1. init the navigation in /
2. navigate to /hello
3. navigate to /world
4. see the server console 
    index
    index
    index

---------------------------------------------------------

1. init the navigation in /hello
2. navigate to /
3. navigate to /world
4. see the server console 
    hello
    hello
    hello

### What is expected ?

Load current page when navigating between pages

### What is actually happening?

Loads the current page and the page that starts navigation

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10633">#c10633</a>)</em></sub></div>

**Comment by seifsay3d** [comment]
Hi, I couldn't reproduce this, it seems that it works as expected. Could anyone else reproduce it?

**Comment by Atinux** [comment]
Could not reproduce this issue and from what I see in the code, it's a normal Nuxt app.

Make sure you don't have 3 opens tabs on a browser that may reload your app when you do a change, making 3 hard-refresh = 3 server logs ;)
