### ISSUE TITLE
Cannot set multiple 'Set-Cookie'

### ISSUE THREAD

**Issue by maicong** [nuxt/nuxt.js#734]
Version:

```
macOS 10.12.5
Chrome 60.0.3100.0

yarn 0.24.5
node v7.10.0

cookie 0.3.1
nuxt 0.10.7
```

Code example:

```js
import Cookie from 'cookie'
export default {
  // ...
  async asyncData ({ res }) {
    // ...
    res.setHeader('Set-Cookie', [
      Cookie.serialize('__test_cookie1', 'cookie1', {
        maxAge: 60 * 60 * 24 * 7,
        path: '/'
      }),
      Cookie.serialize('__test_cookie2', 'cookie2', {
        maxAge: 60 * 60 * 24 * 7,
        path: '/'
      })
    ])
  }
}
```

Response header:

```
HTTP/1.1 200 OK
Set-Cookie: __test_cookie1=cookie1; Max-Age=604800; Path=/,__test_cookie2=cookie2; Max-Age=604800; Path=/
Content-Type: text/html; charset=utf-8
Content-Length: 29020
Date: Thu, 18 May 2017 08:41:32 GMT
Connection: keep-alive
```

Now i use `document.cookie`:

```
__test_cookie1=cookie1
```

Why the `__test_cookie2` is not generated ?

**Comment by motia** [comment]
Look closely, both of the cookies are generated at the same headers.
`__test_cookie1=cookie1; Max-Age=604800; Path=/,__test_cookie2=cookie2; Max-Age=604800; Path=/`
I think you should call `res.setHeader` for each cookie alone
`    res.setHeader('Set-Cookie', serialize('__test_cookie1', 'cookie1', {
        maxAge: 60 * 60 * 24 * 7,
        path: '/'}
`

**Comment by maicong** [comment]
@motia I tried, but it still does not work. `Set-Cookie` will be replaced by the last.

**Comment by motia** [comment]
@maicong , I tried your first code and it gives two separate headers. However, I just checked [this question](http://stackoverflow.com/questions/36439308/parse-duplicate-http-headers-from-request-in-node) and learnt that proxy servers can combine headers with same name. If you are using one you should check out its settings.

**Comment by Atinux** [comment]
@maicong your example will work with the next release coming.

**Comment by maicong** [comment]
@motia @Atinux Thanks for your answer.

Up to now, I still could not solve this problem.

Online test:

https://glitch.com/edit/#!/rambunctious-parrot -> https://rambunctious-parrot.glitch.me/

![11111](https://cloud.githubusercontent.com/assets/6924891/26244273/9bfc0774-3cc1-11e7-8578-429c7b8c483f.png)

Local test: 
![22222](https://cloud.githubusercontent.com/assets/6924891/26244288/b0e00e60-3cc1-11e7-86cc-c5d0a09c812b.png)

I need help. ☹️

**Comment by Atinux** [comment]
@maicong finally it works perfectly.

This is normal that `document.cookie` is not parsed, you need to use a function to parse it, take a look at the answer: http://stackoverflow.com/questions/5639346/what-is-the-shortest-function-for-reading-a-cookie-by-name-in-javascript

Take a look at your example updated: https://glitch.com/edit/#!/warm-geese?path=pages/index.vue:1:0

Demo: https://warm-geese.glitch.me/ (look at the console)
