### ISSUE TITLE
pm2 don't work in nuxt application

### ISSUE THREAD

**Issue by b01110011** [nuxt/nuxt.js#7341]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)
windows 10
node v12.16.0
pm2 v4.4.0

### Reproduction link

[http://example.com](http://example.com)

### Steps to reproduce

pm2 start npm -- start

### What is expected ?

running application

### What is actually happening?

[PM2] Starting C:\PROGRAM FILES\NODEJS\NPM.CMD in fork_mode (1 instance)
[PM2] Done.
[PM2][ERROR] Script not found: D:\site.loc\client\start

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10636">#c10636</a>)</em></sub></div>

**Comment by isuke01** [comment]
Actually same issue I just had

**Comment by kelvin2go** [comment]
pm2 work with nuxtjs, from my project I add this in package.json script, 
```json
    "ypm2": "pm2 start --name 'web' 'yarn start' ",
```

**Comment by b01110011** [comment]
I solved it like this

`npm i nuxt-start`

ecosystem.config.js
```
module.exports =
{
    apps:
    [
        {
            name: "client",
            script: "node_modules/nuxt-start/bin/nuxt-start.js",
            cwd: "/home/site/client",
            args: "start -p 80 -H 0.0.0.0"
        }
    ]
}
```
`pm2 start ecosystem.config.js`

**Comment by hendisantika** [comment]
I solved it like this:
```
mv ecosystem.config.js ecosystem.config.cjs
pm2 ecosystem.config.cjs
```


DONE.
