### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by ingf** [nuxt/nuxt.js#7342]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codepen.io/](https://codepen.io/)

### Steps to reproduce

![WX20200510-180640@2x.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0073ffd0-92a6-11ea-ab70-8313b5661f4f.png)

executed the asyncData method on the browser

### What is expected ?

donot executed the asyncData method on the browser

### What is actually happening?

executed the asyncData method on the browser

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10637">#c10637</a>)</em></sub></div>

**Comment by Atinux** [comment]
You don't have access to `req` on client-side, learn more on https://nuxtjs.org/api/context
