### ISSUE TITLE
Is nuxt.js support Vue3

### ISSUE THREAD

**Issue by saumya2512** [nuxt/nuxt.js#7346]
### What problem does this feature solve?

In your document, I saw it support Vue 2. I m working on VueJs 3 and my project has a requirement to create a  Vuejs Application Without Node, WebPack, or Any Other Build Process using Vue, Router, Vuetify, and Axios.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10640">#c10640</a>)</em></sub></div>

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/nuxt.js/issues/5708
