### ISSUE TITLE
Static can not use srcDir settings

### ISSUE THREAD

**Issue by NightCatSama** [nuxt/nuxt.js#735]
Will set `srcDir: '/admin/'`, `static` did not use the configuration.

Is there any way to solve it?

Thanks.

**Comment by pi0** [comment]
Hi @NightCatSama. Meanwhile can you test with absolute path like this? `srcDir: __dirname+'/admin/'`

**Comment by NightCatSama** [comment]
Is it because my routing configuration problem?

app.js
`app.use('/admin/', nuxt.render)`

nuxt.config.js
`srcDir: __dirname + '/admin/'`

The resulting path is like that
`/_nuxt/img/logo.a04e995.png`

But the correct path
`/admin/_nuxt/img/logo.a04e995.png`

Do you know where the problem is?

Thank you for your answer

**Comment by pi0** [comment]
If you want to prefix paths with `/admin/` you have to use this config: 
```js
    router: {base: '/admin/'},
```

**Comment by NightCatSama** [comment]
Although the path becomes "correct".

But still can not find the file.

Because I have two projects, so I can not use the root path in the route `app.use(nuxt.render)`.

**Comment by pi0** [comment]
@NightCatSama Can you please provide your project structure? (Maybe you can use rootDir instead)

**Comment by NightCatSama** [comment]
of course. [this is my project](https://github.com/NightCatSama/NightCat)

The main part:
```
 - admin/
 - routes/admin.js
 - app.js
 - nuex.config.js
```

**Comment by NightCatSama** [comment]
In fact, I am currently only one problem, is add a root path in front of all resources.

I tried a lot, only this is relatively close.
```
module.exports = {
  build: {
    extend (config, ctx) {
      if (ctx.isServer) {
        config.output.publicPath = '/admin/_nuxt/'
      }
    }
  }
}
```

But only the picture and other resources are properly loaded, the script is still not added `/admin/...`

**Comment by NightCatSama** [comment]
I would like to know why only the picture resources have changed in modify the `publicPath` after , and the scripe tag src is still not added. Do you have any opinion?

Thank you

**Comment by Atinux** [comment]
Hi @NightCatSama 

I tried your project, and it works fine on `http://localhost:3000/admin/`, I'm not sure to understand your problem.

**Comment by NightCatSama** [comment]
In fact, this time I try out at noon, but there are still problems.

1. The console has a warning
```
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
```

2. Can not be used `http://localhost:3000/admin`.
