### ISSUE TITLE
Support keep-alive with different layout

### ISSUE THREAD

**Issue by bluedarker** [nuxt/nuxt.js#7351]
### What problem does this feature solve?

Keep-alive not working on switch pages that use different layout

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10644">#c10644</a>)</em></sub></div>

**Comment by Atinux** [comment]
It is not possible for Nuxt 2.X but will be considered for Nuxt 3.0 with upcoming `App.vue`
