### ISSUE TITLE
Allow server middleware to export an unload/destroy method

### ISSUE THREAD

**Issue by itslukej** [nuxt/nuxt.js#7355]
### What problem does this feature solve?

In my application, I am using server middleware to serve an API - My API uses setInterval for some frequent background tasks. When in dev mode and I make some changes, the API reloads yet the old intervals stay alive, creating more each time I reload. A unload/destroy method would allow for properly closing the server middleware.

### What does the proposed changes look like?

```js
const interval = setInterval(() => console.log('This is my interval'), 30 * 1000);

module.exports = {
  path: '/api',
  handler: /* express */,
  unload() {
    clearInterval(interval);
  }
};

```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10646">#c10646</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @itslukej 

Thank you for the feature request, I just made a PR to support `unload` method: https://github.com/nuxt/nuxt.js/pull/7358

Still need the tests + documentation update.
