### ISSUE TITLE
 Cannot use import statement outside a module

### ISSUE THREAD

**Issue by KIMDara** [nuxt/nuxt.js#7356]
### Version

[v2.15.0](https://github.com/nuxt.js/releases/tag/v2.15.0)

### What is actually happening?

I want to import firebase in nuxt.config.js to get data from firestore for genereting dynamic route. but it show error :
SyntaxError: Cannot use import statement outside a module

### Additional comments?

here is my code and error :
![Screen Shot 2020-05-12 at 7.57.20 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/21828d80-9450-11ea-8b86-93cb1002732b.png)

this is for generating dynamic route:
![Screen Shot 2020-05-12 at 7.55.21 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d9636b00-944f-11ea-8b86-93cb1002732b.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10647">#c10647</a>)</em></sub></div>

**Comment by Atinux** [comment]
Please use `export default` instead of `module.exports` if you want to use the `import` statement.

**Comment by KIMDara** [comment]
@Atinux Sorry Sir. but it still does not work with me. 
<img width="1680" alt="Screen Shot 2020-05-13 at 4 22 37 AM" src="https://user-images.githubusercontent.com/42166658/81746885-63b36b80-94d1-11ea-9c73-421b16abbdc0.png">
i am importing firebase from plugins.
<img width="343" alt="Screen Shot 2020-05-13 at 4 30 20 AM" src="https://user-images.githubusercontent.com/42166658/81747539-77130680-94d2-11ea-8435-426c9d98871f.png">

**Comment by Atinux** [comment]
I see you use server/index.js

So you need to use const { db } = require(‘../plugins/firebase’) and use module.exports

**Comment by KIMDara** [comment]
after i use  const { db } = require(‘../plugins/firebase’) and module.exports , it shows me this error.

![Screen Shot 2020-05-13 at 5.19.35 AM.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b0db09f0-949e-11ea-8b86-93cb1002732b.png)
