### ISSUE TITLE
Simple static redirecting /a to /b

### ISSUE THREAD

**Issue by michaeljakob** [nuxt/nuxt.js#7367]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://nuxtjs.org/api/configuration-router/](https://nuxtjs.org/api/configuration-router/)

### Steps to reproduce

I want to statically redirect my root path '/' to '/US5949181045/870747/MSFT/Microsoft'. However, this seems to be impossible at the current version. I have tried the following code, but no redirect is happening:

nuxt.config.js:
```
router: {
    extendRoutes(routes, resolve) {
      routes.push({
        path: '/',
        redirect: '/US5949181045/870747/MSFT/Microsoft'
      })
    }
  },
```

In a similar fashion, I have about 10'000 links as '/US5949181045' that I also want to automatically redirect to '/US5949181045/other/symbol/company-name'. Where can I plug in that static url-redirect mapping? That later page is existing as part of my NuxtJS-project, as I use /:isin/:wkn/:symbol/:companyname

This should be SEO-optimized, so the actual path of '/' is never actually called.

### What is expected ?

Instantly navigate to /US5949181045/870747/MSFT/Microsoft

### What is actually happening?

User stays at /

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10660">#c10660</a>)</em></sub></div>

**Comment by pimlie** [comment]
Please dont skip the reproduction part.

Without looking into your specific situation, please be aware there is a [router-extras](https://github.com/nuxt-community/router-extras-module/issues) module that provides more configurability then the default Nuxt.js filesystem based routing will ever be able to provide
