### ISSUE TITLE
Force the reload of the page with a nuxt-link

### ISSUE THREAD

**Issue by noook** [nuxt/nuxt.js#7369]
### What problem does this feature solve?

I would like to use the `<nuxt-link>` component to benefit from the classes such as `.nuxt-link-exact-active`, but need to reload the window to reset a hidden incheckbox input value.

I need to make it work even with javacript disabled. Basically, to make that work I'd use a simple `<a>` element, it will reload the page, but not have the active link classes.

### What does the proposed changes look like?

<nuxt-link reload>This link will benefit from the classes, but will reload the window !</nuxt-link>

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10663">#c10663</a>)</em></sub></div>

**Comment by noook** [comment]
Nevermind, altough I found an alternative to my problem, I don't know if there are other use cases to this options.

As I said, I wanted it to work without javascript, then I remembered that without javascript, `<nuxt-link>` is just an anchor element, and that without javascript it will by default reload the page. To uncheck my input I used a `@click` event listener. Letting this open as maybe it might help others

**Comment by pimlie** [comment]
Thanks for updating the request, closing it to cleanup our backlog

**Comment by danpad01** [comment]
> I just replaced `<nuxt-link>` or`<button @click="">` with a simple `<a href="/">` and works like a charm :)

For the record: This doesn't work on production when router.base is different from "/"

**Comment by fnacarellidev** [comment]
This would be a good adition on a very specific case i'm dealing with, I'm sending the user to a i18n route, so I can't use in a simple `<a>` tag, and the reason that I need to perform the reload is to deal with Google Tag Manager properly, I'm trying to trigger an action once the url is loaded, since it doesn't reload the event is not triggered.
