### ISSUE TITLE
Nuxtjs + firebase (again)

### ISSUE THREAD

**Issue by guillaumechereau** [nuxt/nuxt.js#737]
I know there as been a few related questions already, but none of them solve my problem.

I am working on a website with a firebase backend, and I would like to create a form for users to update the database.  Vuefire allows to do this in a very neat way, as seen in the vuejs page example: https://vuejs.org/v2/examples/firebase.html

With nuxt, I am not quite sure how to do that.  The with-firebase example only show how to read data using the rest api.  Is there a way to use vuefire in nuxtjs, or at least to achieve something similar?

**Comment by uptownhr** [comment]
veufire looks pretty straight forward. Should work if you create a vuefire plugin to call `Vue.use(Vuefire)`

**Comment by Atinux** [comment]
@guillaumechereau actually it's more complicated without using the REST API since we don't know when the data is available to render the HTML from the server-side.

It might be possible but will require to make a bridge between vuefire & nuxt.

**Comment by guillaumechereau** [comment]
@Atinux thanks for the answer, sorry to keep coming about this issue, but I think I wasn't very clear.  In my case I am only interested in the client side part, the server should just serve an html page with a vuejs div, that will then be populated by vufire.  Is that impossible with nuxt?  I have no problem doing this in a simple html file.

**Comment by ausir0726** [comment]
@guillaumechereau I think it's possible , but you will lose SEO advantage on SSR .
you just need require vuefire ssr false , if vuefire have SSR issue , you can write a one , or fix it make a PR for vuefire .

**Comment by jsappme** [comment]
+1

**Comment by brokyo** [comment]
@guillaumechereau did you ever find a solution on this? I have a similar situation and while I believe I've read everything here I just can't find the solution that seems to exist? (also alluded to here: https://github.com/vuejs/vuefire/issues/124) Just stumped :/

**Comment by guillaumechereau** [comment]
@brokyo sorry I stopped working on this project at the moment.  At the time I unfortunately couldn't find any satisfactory solution.
