### ISSUE TITLE
ERROR (node:1380) [DEP0005] DeprecationWarning when deploying Universal build to Vercel (Now.sh) with build -> cache: true

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/nuxt.js#7371]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://nuxt-zeit.now.sh/](https://nuxt-zeit.now.sh/)

### Steps to reproduce

- Go to https://vercel.com/import/nuxtjs
- Spin up a new Nuxt project
- Clone created repository locally
- Go to nuxt.config.js and change mode from 'spa' to 'universal'
- Add now.json as specified in the docs: https://nuxtjs.org/faq/now-deployment/
- Go to nuxt.config.js build section and specify `cache: true`
- Push and deploy

### What is expected ?

No errors during a build process

### What is actually happening?

ERROR (node:1380) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10665">#c10665</a>)</em></sub></div>

**Comment by pimlie** [comment]
I dont think Nuxt is using Buffer itself, but there are quite some dependencies using it if I do a grep

**Comment by AndrewBogdanovTSS** [comment]
Yes, I think it's some dependency that is activated with enabling build caching, maybe it can be updated or replaced

**Comment by pimlie** [comment]
@AndrewBogdanovTSS We would love your help with finding which dependency this is and if we can help update it or replace it
