### ISSUE TITLE
nuxt cli build command can't find config file

### ISSUE THREAD

**Issue by vedmant** [nuxt/nuxt.js#7386]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://na.na](https://na.na)

### Steps to reproduce

Place nuxt.config.js into some subfolder, try to run `nuxt -c somefolder/another/nuxt.config.js build` it responds with "Config file not found: somefolder/another/nuxt.config.js", however just nuxt command works properly `nuxt -c somefolder/another/nuxt.config.js` 

### What is expected ?

Both 
`nuxt -c somefolder/another/nuxt.config.js`
and 
`nuxt -c somefolder/another/nuxt.config.js build`
to work

### What is actually happening?

This works:
`nuxt -c somefolder/another/nuxt.config.js`
but this doesn't:
`nuxt -c somefolder/another/nuxt.config.js build`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10674">#c10674</a>)</em></sub></div>

**Comment by zachjharris** [comment]
Did you try `nuxt build -c somefolder/another/nuxt.config.js`?

**Comment by vedmant** [comment]
@zachjharris yeah `nuxt build -c resources/admin/nuxt.config.js` that's weird, in most cli commands options go before actual command in cli, not after. This might be better to fix as I might be not alone to try putting options like this.

**Comment by zachjharris** [comment]
I've seen it both ways, this is typically how I see it with node. The [documentation](https://nuxtjs.org/guide/commands) has a few examples that show commands being used at the end.
