### ISSUE TITLE
Remove asyncData for full static export

### ISSUE THREAD

**Issue by J05HI** [nuxt/nuxt.js#7388]
### Version

[nuxt-edge](https://github.com/nuxt.js/releases/tag/nuxt-edge)

### Reproduction link

[Any nuxt project](Any nuxt project)

### Steps to reproduce

- Switch to nuxt-edge on any nuxt project
- Enable target: static
- Build and export it

### What is expected ?

Nuxt should export the static site with asyncData removed. It isn't needed for static export (payload.js is used instead) => unnecessary data for the user to download.

### What is actually happening?

Nuxt keeps asyncData.

![chrome_2020-05-19_17-31-46.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/099a0cc0-99e6-11ea-8afd-f37871b7daf5.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10677">#c10677</a>)</em></sub></div>

**Comment by manniL** [comment]
It is still necessary for the following situations:

* In case the payload can't be fetched
* When using SPA fallback (no payload in this case)
* When using preview mode

**Comment by J05HI** [comment]
Hello @manniL 

thank you for your reply! I've some questions.

> In case the payload can't be fetched

When can't the payload be fetched? If the user lacks of network access? The API would be unavailable, too.

> When using SPA fallback (no payload in this case)

Isn't the full static export a static site which hydrates to a SPA without API requests? => we don't need asyncData.

> When using preview mode

What do you mean with "preview mode"? Running Nuxt in dev?

**Comment by manniL** [comment]
> When can't the payload be fetched? If the user lacks of network access? The API would be unavailable, too.

The most common situation I can think of is when using the SPA fallback (as there won't be a payload). But there might be other scenarios where this comes in handy instead of letting the site break.

> > When using SPA fallback (no payload in this case)
> Isn't the full static export a static site which hydrates to a SPA without API requests? => we don't need asyncData.

Yes, this is correct so far. But you can exclude routes from being generated (e.g. everything behind authentication). Those have no payload but can still be accessed "normally" and will load as "SPA" (no generated HTML)

> > When using preview mode 
> What do you mean with "preview mode"? Running Nuxt in dev?

See https://github.com/nuxt/nuxt.js/pull/6159#issuecomment-631608962

**Comment by J05HI** [comment]
@manniL 
Thank you very much for answering my questions! It's clear now 😉
