### ISSUE TITLE
Static Components

### ISSUE THREAD

**Issue by MartinMalinda** [nuxt/nuxt.js#7393]
### What problem does this feature solve?

There's a component that only presents data. It's not interactive at all. It would be nice if it could be set to `static: true` which would mean that...

- setup() is skipped on client side
- component completely reuses HTML from the SSR, not even hydration process is needed to run

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10684">#c10684</a>)</em></sub></div>

**Comment by manniL** [comment]
That's more a Vue than a Nuxt.js issue. But Vue 3 will come with lots of nice improvements for SSR. https://twitter.com/youyuxi/status/1261398082136109057
