### ISSUE TITLE
 Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by sean-hill** [nuxt/nuxt.js#74]
After following the getting started guide, I get the following build errors when running `npm start`:

    $ npm start

    > nuxt@1.0.0 start 
    > nuxt

    nuxt:build App root:  +0ms
    nuxt:build Generating .nuxt/ files... +2ms
    nuxt:build Generating routes... +8ms
    nuxt:build Generating files... +5ms
    nuxt:build Adding webpack middlewares... +15ms
    Ready on http://localhost:3000
    ./.nuxt/server.js
    Module build failed: Error: Couldn't find preset "es2015" relative to directory 
        at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19

Running npm `v3.10.8` and node `v4.5.0`.

**Comment by Atinux** [comment]
Hi @sean-hill 

I tried with node `v4.5.0` and the latest version of npm and it works, could you try this?

```bash
rm -rf node_modules/
npm install -g npm
npm
npm start
```
