### ISSUE TITLE
Does nuxt.js support Vue Material ?

### ISSUE THREAD

**Issue by thecodr** [nuxt/nuxt.js#740]
It can be helpful if there is an example for different component library integrations. For example, does nuxt.js support [vue material](https://vuematerial.github.io/#/) ?

**Comment by Atinux** [comment]
Hi @thecodr 

It works but not with SSR, which brings the warning in the console by Vue.js, see https://glitch.com/edit/#!/quill-breath, demo: https://quill-breath.glitch.me/

But you can use [Vuetify](https://github.com/vuetifyjs/vuetify) instead.

See my example: https://glitch.com/edit/#!/vigorous-kite, demo: https://vigorous-kite.glitch.me/

**Comment by thecodr** [comment]
Thank you very much for the pointer @Atinux
