### ISSUE TITLE
React: Debug error overlay

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#741]
Recently react released their updated Create React App CLI. They are finally catching up a little to what nuxt offers out of the box and IMO still ways away. However, one item really stuck out - the `Error Debug Overlay` https://facebook.github.io/react/blog/2017/05/18/whats-new-in-create-react-app.html#runtime-error-overlay

Nuxt does provide something of an overlay but can definitely be improved. Now I suspect this is not an easy feature to develop but I wanted to bring it up to the community as I believe it would bring immense value. 

Debugging experiences differ a lot between languages and stack. When I first hand experienced `better errors` from Ruby's padrino stack, I was blown away. REPL loads on uncaught errors and you can debug live.

**Comment by Atinux** [comment]
Hi @uptownhr 

We are only bringing up Vue.js errors, it's not related to Nuxt.js directly.

We also use FriendlyErrors webpack plugin (see https://github.com/nuxt/nuxt.js/blob/master/lib/webpack/client.config.js#L91)

I believe this is more an improvement to make on Vue.js side directly.
