### ISSUE TITLE
"nuxt generate" incorrectly converts <nuxt-link to="./page/"> to <a href="/page/">

### ISSUE THREAD

**Issue by AlanLynn** [nuxt/nuxt.js#7415]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/relative-link-bug-1g1f5?file=/README.md](https://codesandbox.io/s/relative-link-bug-1g1f5?file=/README.md)

### Steps to reproduce

1. Create a new Nuxt app with mode set to 'universal'.
2. Make a page "index.vue" containing `<nuxt-link to="./page/">Link</nuxt-link>`.
3. Run `nuxt generate`.
4. Open "index.html" and find the <a> link that was pre-rendered.

### What is expected ?

`<nuxt-link to="./page/">` converts to `<a href="./page/">`

### What is actually happening?

`<nuxt-link to="./page/">` converts to `<a href="/page/">`

#### Similar problems I have noticed:

* `<nuxt-link to="page/">` is converted to `<a href="/page/">`
* `<nuxt-link to="../">` is converted to `<a href="/">`

#### Notes on the reproduction link:

The reproduction link I have included demonstrates how this bug can produce a broken link, where "./page/" and "/page/" do not go to the same location.

For example, a link on page "/depth-1/" to "./depth-2/" will lead to "/depth-1/depth-2/". But if the link on page "/depth-1/" is changed to "/depth-2/", it instead leads to "/depth-2/".

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10701">#c10701</a>)</em></sub></div>

**Comment by AlanLynn** [comment]
I made an uninformed attempt to track down this bug. I think it starts here, in the render method of [nuxt.js/packages/vue-renderer/src/renderers/ssr.js](nuxt.js/packages/vue-renderer/src/renderers/ssr.js):

```js
let APP = await this.vueRenderer.renderToString(renderContext)
```

which comes from:

```js
this.vueRenderer = this.createRenderer()
```

which is defined as:

```js
createRenderer () {
  // Create bundle renderer for SSR
  return createBundleRenderer(
    this.serverContext.resources.serverManifest,
    this.rendererOptions
  )
}
```

which is imported from:

```js
import { createBundleRenderer } from 'vue-server-renderer'
```

This suggests to me that the bug is actually in the [vue-server-renderer](https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#readme) package. Is that true?

**Comment by AlanLynn** [comment]
I cannot figure out how or where <nuxt-link> gets converted to <a>, so somebody who knows more Nuxt and Vue will have to look at this.

**Comment by danielroe** [comment]
@AlanLynn The behaviour of `NuxtLink` that you are describing comes from `vue-router` and in particular from `RouterLink` which `NuxtLink`extends - see [more here](https://router.vuejs.org/api/#router-link).

Tell me a bit more about your use case. Is there a reason you need relative URLs?

**Comment by danielroe** [comment]
@AlanLynn The behaviour of `NuxtLink` that you are describing comes from `vue-router` and in particular from `RouterLink` which `NuxtLink`extends - see [more here](https://router.vuejs.org/api/#router-link).

I can't reproduce any bug though, even with your reproduction. NuxtLink resolves the link you pass to it using the router - which may account for the fact that `./page` turns into `/page`.

**Comment by AlanLynn** [comment]
Thanks for taking a look at this. To clarify, when you attempted to reproduce the bug, did you open the pre-rendered HTML file in a browser, or in a text editor?

For me, everything works correctly in the browser (once the JavaScript loads), but if you open the HTML file in a text editor (or view the page source), then you see the incorrect links.

**Comment by Atinux** [comment]
It is not an issue actually but actual browser behavior, if you do not start with a /, it will append to the current url.

Also it is normal that nuxt-link are converted to a tag for better SEO and accessibility.

You may want to directly see with vue-router if you think this behavior is not correct (cc @posva)

**Comment by posva** [comment]
Relative links using `.` are not supported on vue router because the logic is not supported in all supported browser. Only directly relative links like `page` work: current url `/document/options`, `page` will go to `/documents/page` (like `.`)

**Comment by AlanLynn** [comment]
> It is not an issue actually but actual browser behavior, if you do not start with a /, it will append to the current url.
> 
> Also it is normal that nuxt-link are converted to a tag for better SEO and accessibility.

@Atinux: You seem to have misunderstood me. It *was* my intent to append to the current URL, and in the browser, everything behaves exactly as I expect. The problem is that when `nuxt generate` converts `<nuxt-link>` to `<a>`, it actually alters some URLs, making them invalid, thus showing search engines a broken URL that makes for bad SEO. Therefore I believe this issue should be reopened.

**Comment by AlanLynn** [comment]
@posva: On a plain HTML page, if you are on the page `/depth-1`, then a link to either `"depth-2"` or `"./depth-2"` will both take you to `/depth-1/depth-2`. That is the expected behavior.

But if `nuxt generate` converts `<nuxt-link to="depth-2">` to `<a href="/depth-2">`, that leads somewhere different: `/depth-2`

> Relative links using `.` are not supported on vue router because the logic is not supported in all supported browser. Only directly relative links like `page` work: current url `/document/options`, `page` will go to `/documents/page` (like `.`)

I don't entirely understand what you're saying here, but if certain links are not supported, why doesn't `nuxt generate` show a warning/error if it finds an unsupported link?
