### ISSUE TITLE
broken require server side

### ISSUE THREAD

**Issue by mromanuk** [nuxt/nuxt.js#743]
I need to use a node module `recaptcha2` server side only, which depends in `fs`.
How to reproduce the bug:
1. `clone` `vue init nuxt/express test-nuxt-express`
2. `npm install --save recaptcha2`
3.  add this code to `pages/index.vue`
```
if (process.server) {
  const recaptcha2 = require('recaptcha2')
}
```

Now a dependency is not found:
```
This dependency was not found:

* fs in ./~/request/lib/har.js
``` 
I think there is some issue with webpack server side

**Comment by ausir0726** [comment]
@mromanuk 

that you wrote `process.server` is mean use when SSR , not mean api server .
if you just want use on server side , you should use it on server folder ( api side )

**Comment by mromanuk** [comment]
thanks @ausir0726,  is there any documentation about that? not sure how to do it

**Comment by Atinux** [comment]
@ausir0726 is right, this module should not be used directly inside nuxt.js project but in your external API to verify the captcha.

For example, if you look at [nuxt/express](https://github.com/nuxt/express) starer, the usage of recaptcha2 will be used in the `server` directory.
