### ISSUE TITLE
Ability to prevents page generation in `generate:page`

### ISSUE THREAD

**Issue by farnabaz** [nuxt/nuxt.js#7440]
### What problem does this feature solve?

What if we can add a single boolean to the `page` variable to conditionally control page generation?

https://github.com/nuxt/nuxt.js/blob/c14471681c7134a6a08a69f9eabdb7d213feb2f0/packages/generator/src/generator.js#L361-L373

### What does the proposed changes look like?

```js
// Call hook to let user update the path & html
    const page = { route, path: fileName, html, generate: true }
    await this.nuxt.callHook('generate:page', { page, errors: pageErrors })
    await this.nuxt.callHook('export:page', { page })
  
    if (page.generate) {
        page.path = path.join(this.distPath, page.path)
        ...
    }

    return page.generate

```

Or for being fully backward compatible we could use `export:page` hook:
```js
    const page = { route, path: fileName, html, generate: true }
...
    await this.nuxt.callHook('export:page', { page, errors: pageErrors })
  
    if (page.generate) {
...
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10713">#c10713</a>)</em></sub></div>

**Comment by simplenotezy** [comment]
You mean to generate a single page? I'm not sure I understand your request.

**Comment by manniL** [comment]
> 
> 
> You mean to generate a single page? I'm not sure I understand your request.

The idea is to exclude pages from generation "on the fly" by using the return value of a nuxt hook instead of using `generate.excludes`

**Comment by pi0** [comment]
I think it would be a nice idea to leverage `export:page` hook for excluding page generation (maybe also being able to set ssr/spa? :see_no_evil: Use case: Marking any route matching `/checkout/` SPA even with crawler)

**Comment by noname202** [comment]
> I think it would be a nice idea to leverage `export:page` hook for excluding page generation (maybe also being able to set ssr/spa? 🙈 Use case: Marking any route matching `/checkout/` SPA even with crawler)

Would this allow mixing static and SSR pages?  Should be quiet useful, if you want some pages (e.g. your blog) to be static and the rest of your site to be dynamically rendered by the server.

**Comment by manniL** [comment]
> 
> 
> > I think it would be a nice idea to leverage `export:page` hook for excluding page generation (maybe also being able to set ssr/spa? 🙈 Use case: Marking any route matching `/checkout/` SPA even with crawler)
> 
> Would this allow mixing static and SSR pages? Should be quiet useful, if you want some pages (e.g. your blog) to be static and the rest of your site to be dynamically rendered by the server.

Nope, that's not the scope of this feature.
