### ISSUE TITLE
Page mounts twice causing huge performance issues

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt.js#7441]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/nuxt-vuetify-0xz91](https://codesandbox.io/s/nuxt-vuetify-0xz91)

### Steps to reproduce

1) Add a new layout
2) Create a new page and assign this new layout
3) Change from the "default" layout to the page with the new layout
4) See that mounted() and created() is fired twice

### What is expected ?

Page should only be created/mounted once

### What is actually happening?

Page mounts itself twice

### Additional comments?

It writes "I have been mounted" twice in the console, see here: https://codesandbox.io/s/nuxt-vuetify-0xz91. I even tried to give a name to the layout file.

When switching to the about page:

```
i have been created. Layout: default 
i have been mounted. Layout: default 
i have been created. Layout: other 
i have been mounted. Layout: other 
```

It's also weird it calls the layout "other" when I call `this.$nuxt.layoutName`, because I explicitly set the name to be `otherlayout`.

I believe it causes page switches to take extra long time - we just launched our production site: https://thejewelleryroom.com and when switching pages to a page that has been cached by Cloudflare, and the response time is 50-100ms, it still takes 1-2 seconds for the page to switch. Perhaps it is because it mounts the page twice?

Related issue: https://github.com/nuxt/nuxt.js/issues/5703

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10715">#c10715</a>)</em></sub></div>

**Comment by pi0** [comment]
Closing as confirmed to be fixed https://github.com/nuxt/nuxt.js/pull/7442#issuecomment-641908054
