### ISSUE TITLE
Generating static html always renders loading state when nuxt mode is SPA

### ISSUE THREAD

**Issue by elmccd** [nuxt/nuxt.js#7444]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[http://couldnt-reproduce-online](http://couldnt-reproduce-online)

### Steps to reproduce

Create a new app with "npx create-nuxt-app my-app"
Pick all default options, except of SPA mode question. Select SPA.
Enter project and run: "npm run generate"

### What is expected ?

Generated dist/index.html file should contain HTML for vue welcome screen including "My transcendent Nuxt.js project".

### What is actually happening?

Generated HTML has a loading component instead of actual HTML:
<div id="nuxt-loading" aria-live="polite" role="status">
    <div>Loading...</div>
  </div>

### Additional comments?

After changing mode to universal and running "npm run generate" HTML content contains actual pages HTML as expected.

When generating HTML for multiple static pages, all of them have the same content with loading element.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10716">#c10716</a>)</em></sub></div>

**Comment by elmccd** [comment]
@danielroe 
Ok, so I as understand using `npm run generate` with mode SPA will generate those files to replace URL rewrites on backend to index.html.
That makes sense, but probably user will need those rewrites anyway for any dynamic routes.

What really confuses me is that if I want use static pregenerated sites that will act as SPA on the client side, all being 100% static, without any SSR done in production then I have to pick "universal" mode which claims to create "Isomorphic application (server-side rendering + client-side navigation)"

Having the above stated in the doc, or having this setup as additional mode would made it more obvious:

Quoting https://nuxtjs.org/api/configuration-mode
> 'spa': No server-side rendering (only client-side navigation)
> 'universal': Isomorphic application (server-side rendering + client-side navigation)
> ***'static-spa': No server side rendering, (generated static pages + client-side navigation)***

Or having `npm run generate` with mode `spa` act as it acts now with `universal` mode.
Current `npm run generate` in `spa` mode makes little sense IMO.

**Comment by danielroe** [comment]
@elmccd Documentation pull requests are welcome at https://github.com/nuxt/docs/ 🙂

(In case you're wondering, a key benefit of generating in SPA mode (if fully-rendered pages don't suit your needs) is that instead of loading a white screen and then waiting until hydration for a loader, you get the loader instantly, which is a better user experience.)

**Comment by elmccd** [comment]
@danielroe I will try to word it and submit a PR :)

Indeed, still an index.html with the loader and correct URL rewrites (if possible in given environment) would work the same, right? And that would avoid us multiple files with identical content.

Thanks for explaining, from my end all clear here :)
