### ISSUE TITLE
How to import modules from raw typescript files?

### ISSUE THREAD

**Issue by nidin** [nuxt/nuxt.js#745]
**some-classes.ts**
```typescript
export class SomeClass {
    someNumber:number = 911;
    someString:string = "This is a string";
}
```
**index.vue**
```html
<template></template>
<script lang="ts">
import Vue from "vue";
import Component from "nuxt-class-component"
import {SomeClass} from "./some-classes"

@Component({})
export default class extends Vue {
      some:SomeClass = new SomeClass();
}
</script>
```
This trigger Module not found: Error: Can't resolve "./some-classes"

**Comment by Atinux** [comment]
TypeScript support will be supported in the 1.0.0-alpha1 release (coming very soon).

**Comment by Atinux** [comment]
But in the meantime you can add [ts-loader](https://github.com/TypeStrong/ts-loader) into `build.extend` of your `nuxt.config.js`

**Comment by nidin** [comment]
@Atinux I am using following config
```javascript
config.module.rules.push({
    test: /\.(ts)$/,
    loader: "ts-loader",
    exclude: /(node_modules)/
});
```
but how do I tell webpack to use default import extension as `.ts`
with this configuration i need to add  `.ts` at the end of the import.
`import {SomeClass} from "./some-classes.ts"`
I need to use same ts files in node.js which will trigger error since typescript compiler not expecting .ts at the end.

**Comment by nidin** [comment]
@Atinux I am testing with 1.0.0-alpha1. What are the configuration to enable full typescript support?

**Comment by nidin** [comment]
@Atinux Never mind i figured it out.

**Comment by piyushchauhan2011** [comment]
I think the current example of Typescript is really good resource. The imports work perfectly https://github.com/nuxt/nuxt.js/tree/v1.0.0-alpha2/examples/typescript
