### ISSUE TITLE
Computed class bindings don't work in production mode

### ISSUE THREAD

**Issue by ReubenMathew** [nuxt/nuxt.js#7456]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/github/ReubenMathew/vercel-components](https://codesandbox.io/s/github/ReubenMathew/vercel-components)

### Steps to reproduce

1. Run "npx nuxt build && npx nuxt start"
2. Navigate to localhost:3000

### What is expected ?

2 Red and 2 Orange buttons as well as a black and white badge should appear.

### What is actually happening?

The buttons and badge have no color and do not have hover states.

### Additional comments?

I am using TailwindCSS to make some components and I am trying to make them dynamic by passing props which modify their color and styles. In development mode everything works fine however when built for production the computed class bindings do not render.

For example I have a computed class binding that changes the color of a badge...

```javascript
        styling() {
            const mappings = {
                primary: ["black","white"],
                secondary: ["white","black","black"],
                success: ["success","white"],
                error: ["error","white"],
                warning: ["warning"],
                default: ["black"],
            };
            const background = mappings[this.type][0] || mappings.default[0];
            const text = mappings[this.type][1] || mappings.default[1];
            const border = mappings[this.type][2];

            return 'bg-'+background+' text-'+text + " border-"+border
        }
```

HTML:
```html
<span :class="styling"></span>
```

In development mode it renders the color however in production mode it does not.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10726">#c10726</a>)</em></sub></div>

**Comment by danielroe** [comment]
@ReubenMathew This is because PurgeCSS can't tell you're using these classes and it removes them from the available tailwind classes. You'll need to add them to [the whitelist](https://tailwindcss.com/docs/controlling-file-size/#purgecss-options).

**Comment by ReubenMathew** [comment]
So do I need to manually list

**Comment by danielroe** [comment]
@ReubenMathew I'm afraid so. Or you can turn PurgeCSS off - more details in the Tailwind docs.

**Comment by slecorvaisier** [comment]
In your situation, you can use `whitelistPatterns`, so you can add more items in your mappings without updating the purgeCSS config:

```js
whitelistPatterns: [
  /^bg-.*$/,
  /^text-.*$/,
  /^border-.*$/,
]
```

It can be simplified with a single regex, but you get the idea.

**Comment by manniL** [comment]
Not a nuxt issue as explained above.

PS: Using full class names would work either.
