### ISSUE TITLE
Pattern that would allow including Components within pages

### ISSUE THREAD

**Issue by HunderlineK** [nuxt/nuxt.js#7459]
### What problem does this feature solve?

It'll make creating and finding Components that are used within a single page more straightforward. In React, it's easy to include multiple components within the same file; however, in Vue, it's not that straightforward, so I find myself creating multiple Component files for the same page, but they are all within a different directory. It would be nice if they could be in the same directory.

### What does the proposed changes look like?

e.g. files starting ending with .component.vue could be ignored from the pages routes

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10727">#c10727</a>)</em></sub></div>

**Comment by danielroe** [comment]
@HunderlineK You can [use `router.extendRoutes`](https://nuxtjs.org/api/configuration-router/) to add additional routes for the same page component.

**Comment by HunderlineK** [comment]
@danielroe Thanks for the link. In my case, I want to 'exclude' certain routes; is there a way to perhaps completely replace the routing identification mechanism so I can write my own regexp for what's the accepted routes?

**Comment by danielroe** [comment]
@HunderlineK Yes, there is 😃 Try [`@nuxtjs/router`](https://github.com/nuxt-community/router-module).

**Comment by HunderlineK** [comment]
@danielroe Well, of course there would be one >~< Thanks a lot!!
