### ISSUE TITLE
globalName does not work

### ISSUE THREAD

**Issue by psdon** [nuxt/nuxt.js#7466]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://pastebin.com/KTkTNTPD](https://pastebin.com/KTkTNTPD)

### Steps to reproduce

`npx create-nuxt-app test-project`

add `globalName: 'alpha'` in your nuxt.config.js

`npm run dev`

### What is expected ?

changed `_nuxt` to `_customname`

### What is actually happening?

Upon checking the rendered page source code, you can still find _nuxt instead of your assigned globalName

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10732">#c10732</a>)</em></sub></div>

**Comment by danielroe** [comment]
@psdon I think you're looking for the [publicPath] config option - [see docs](https://nuxtjs.org/api/configuration-build/#publicpath). `globalName` affects [these global names](https://nuxtjs.org/api/configuration-global-name#the-globals-property).
