### ISSUE TITLE
Add data and/or content folder for static generated part of application

### ISSUE THREAD

**Issue by alidcastano** [nuxt/nuxt.js#747]
I plan on using `nuxt generate` to create static sites and blogs. Other alternates, obviously, are Jekyll, Hexo, Hugo, etc. 

Currently, like the mentioned alternatives, nuxt provides:

- layouts or templates
- components or partials
- dynamic urls or routing
- assets (css, images, etc.) 

However, the main features it does not provide:
 
- Data files for reusable information that can be used inside pre-compiled files (this can be done inside HTML templates locally with the `data` component property, but there is no global data configurations that can be used inside markdown files before they are compiled as vue components)

- Front-matter/metadata that facilitates content organization (e.g. by date, title, category etc.)

Before I go off and try to incorporate these features on my own, my question is: would it make any sense to incorporate these features into Nuxt?

**Comment by alexchopin** [comment]
Hi,
Nuxt-Modules will be available in the next release and will give you the opportunity to add such functionality to Nuxt.
