### ISSUE TITLE
localStorage isn't used until refresh, which also adds a / to the URL

### ISSUE THREAD

**Issue by dhust** [nuxt/nuxt.js#7488]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://minecraftdungeons.gg](https://minecraftdungeons.gg)

### Steps to reproduce

Go to minecraftdungeons.gg
Click on Melee (Notice that the URL doesn't end with a slash)
Press the refresh button on your browser (Notice that the URL now has a slash at the end)
Click on the "Common" switch to turn it off
Close the tab

Go to minecraftdungeons.gg
Click on Melee (Notice the the Common switch is on and it should be off)
Press the refresh button on your browser
(Notice that the Common switch is now off)

### What is expected ?

localStorage should update the switches

### What is actually happening?

The switches aren't updating until the refresh button on the browser is pressed

### Additional comments?

If I type in minecraftdungeons.gg/gear/melee or minecraftdungeons.gg/gear/melee/ then it loads minecraftdungeons.gg/gear/melee/ and everything is good.

It's interesting that if I click on the Ranged button, after the refresh, it takes me to minecraftdungeons.gg/gear/ranged <-- (no slash), and everything works as expected. It's like it needs an initial slash at the end of one of the pages to get things going, unless I type the full URL.

Also, I don't have this issue with local development.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10749">#c10749</a>)</em></sub></div>

**Comment by Kolobok12309** [comment]
@dhust , tried to reproduce your steps and on second visit of /melee, common switch is turned off

**Comment by dhust** [comment]
For some reason it didn't work as expected for about 30 minutes after deployment. Then after that it was all good.
