### ISSUE TITLE
Generating pages without client side js added

### ISSUE THREAD

**Issue by guillaumechereau** [nuxt/nuxt.js#749]
Is it possible to generate pages without client side javascript code added (specially the 'window.__NUXT__ = ...' at the end)?  I am working on a website where most pages don't have any user interaction, but still use complex server side rendering involving a lot of data.  My served html pages get a lot bigger than they should because of the data added at the end in the `__NUXT__` variable.

I wish there was a flag that would somehow tell nuxtjs that some pages should only use server side rendering.  This would also make nuxtjs a nice alternative to jekyll, thanks to the generate command.

**Comment by xalioth** [comment]
What about https://nuxtjs.org/guide/vuex-store/#the-nuxtserverinit-action ?

**Comment by guillaumechereau** [comment]
@xalioth: no, that is the same: the data put in the store ends up in the html `window.__NUXT__` variable.

**Comment by jbmoelker** [comment]
@alexchopin why is this issue closed? I think it's a relevant question. If the answer is NO that is also understandable I think. However, maybe you or someone has a workaround in that case?

**Comment by ashersaupingomez** [comment]
+1

Is it possible to have a completely JS-less page with nuxt?

**Comment by Xowap** [comment]
Yup I'm also wondering?

**Comment by AndrewGrachov** [comment]
upvote

**Comment by peckomingo** [comment]
I also have a project with a lot of static pages generated with nuxt. But none of this pages has JS functionality in some way, so I wondered the same thing, if it is possible to generate without the JS overhead added to the page? I just want this flexibility to use Nuxt at the one hand, but have more control over JS injected.

**Comment by qm3ster** [comment]
It's not overhead, it's underhead, @peckomingo.

**Comment by AndrewGrachov** [comment]
we managed to fork out nuxt and add a simple parameter.. Looks like a hack, as it is, actually.

https://github.com/crello/nuxt.js/commit/93ea141ba563356c58e9b2c572dbe280021f164e

**Comment by qm3ster** [comment]
The only thing worse than an abundance of options is scope creep
