### ISSUE TITLE
Reading JSON file into vuex store not reactively changing

### ISSUE THREAD

**Issue by thely** [nuxt/nuxt.js#7499]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/naughty-hermann-tjs86?file=/static/json/forum-1.json](https://codesandbox.io/s/naughty-hermann-tjs86?file=/static/json/forum-1.json)

### Steps to reproduce

The codesandbox link has it set up already, just look at the order of events in the server console.

### What is expected ?

The loadForums action should read in the JSON file, process the commit, and the state.forums value should reactively update with the new data read in from JSON.

### What is actually happening?

The "forums" value is undefined when it's accessed before Vuex is finished reading in the JSON file, but it's never updated. Basically I'm dealing with a race condition, which I thought couldn't happen with Vuex.

### Additional comments?

The `forum-x.json` files get updated based on an API in serverMiddleware. This happens between `nuxt build`s, i.e. I expect the data to change more than I'd rebuild the nuxt app. So I can't use `require()`, because require caches the file, and I can't use `$content.fetch()` (these were originally in a content/ folder), because it seems to only pull the JSON file as it was when the app was built. So I *need* to be able to read the file in with `fs` as far as I'm aware, but the store seems to not reactively update when I commit changes to its state based on data read through `fs`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10761">#c10761</a>)</em></sub></div>

**Comment by manniL** [comment]
Have you tried using a regular HTTP call via axios or similar instead (as the JSON is exposed anyway)? You can't really use `fs` on the client side.

**Comment by thely** [comment]
I hadn't yet. I was convinced it would be easier to load an already local file rather than AJAXing for it, but clearly my needs didn't correlate with the standard ways that would be easy to work with. I switched to axios, and that fixed my problem. Thanks!
