### ISSUE TITLE
Explicitly define dynamic path in 0.9.0?

### ISSUE THREAD

**Issue by Kentoss** [nuxt/nuxt.js#75]
Hello, I have been using Nuxt to rapidly prototype ideas and I've been really enjoying the simplicity of it. However as of the breaking change to routes in 0.9.0 I am unsure if I can explicitly define my desired path anymore and I fear the simplicity has become somewhat of a limitation without the option for more fine-tuned control.

The examples provided indicate that pages prefixed with an underscore are directly transformed into the path, but what if I wish to have a more complex path regex? Prior to 0.9.0 I had a path along the lines of `/(watch|play)/:id`, this wouldn't work using the folder structure.

Have I missed some information on this or is this simply no longer possible?

**Comment by alexchopin** [comment]
Hi @Kentoss 

Thank you for spotting this issue, indeed we did not think of this possibility.

We want to make Nuxt.js as simply as possible but without removing any feature. Anyone looking at a Nuxt project `pages/` directory should be able to understand quickly the routes of the project.

Actually, we can translate `/(watch|play)/` as `watch or play`, this could be translated to a directory named `watch_OR_play`.

So for `/(watch|play)/:id` it will be this file tree:
```bash
pages/
--| watch_OR_play/
-----| _id.vue
```

Can you let me know what do you think of this idea?

**Comment by Kentoss** [comment]
Thinking about this more, it seems rather difficult to come up with a compromise. I understand the goal of this change, but I would honestly find it marginally more frustrating to browse through the pages directory and have to pick apart what the regex for a folder is supposed to represent. I would also wonder how to determine the intention, whether the folder should be translated as regex or literally. For instance as an edge case, what if my path was supposed to be `/bot_or_not/`, how could I signal that it's literal?

Personally I would prefer not to always have the directory structure literally translated one to one as the endpoints for my site. It's very convenient for simple setups, but my intuition wants me to sort related pages into their own labelled folder and define the path separately when I need more complex dynamic routing.

I was content when the underscore prefix simply prevented the page from being accessed directly because it allowed me to provide my own logic for how it should be accessed. It would be nice to be able to control a page's router path from within as part of the export, but I can see how that might conflict with having an easy to read structure.

**Comment by Atinux** [comment]
Hi @Kentoss 

After talking with my brother, we agreed on the fact that the `_OR_` in the filename is not a solution and also can add confusion as well.

For you Regexp `(watch|play)`, I think it's a special case and the best way to do it is with this file tree:
```bash
pages/
--| watch/
-----| _id.vue
--| play/
-----| _id.vue
```

Furthermore, it will be also more lisible to understand your routing this way.

If you need to re-use components between the same route, your can add them in the `components` folder and import them in your `_id.vue` files.

It's not easy to make this kind of choices for nuxt but we believe it will be easier for everyone to follow this convention when writing or managing nuxt projects.
