### ISSUE TITLE
[2.13] Issue when using nuxt generate --no-build

### ISSUE THREAD

**Issue by RyanCasas** [nuxt/nuxt.js#7507]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://gitlab.com/jryancasas/nuxtjs-2.13-issue-with-nuxt-generate](https://gitlab.com/jryancasas/nuxtjs-2.13-issue-with-nuxt-generate)

### Steps to reproduce

Create a new nuxt project, either using `nuxt-edge@2.13`, or by cloning the repo provided. Then:
```bash
# install dependencies
$ yarn install

# build for production (target: server by default)
$ yarn nuxt build

# Try to nuxt generate without rebuilding
$ yarn nuxt generate --no-build --port 7777
```

### What is expected ?

Nuxt should be able to generate the website as it does on 2.12

### What is actually happening?

```bash
i Modern bundles are detected. Modern mode (server) is enabled now.                                                                                                                  19:30:33

 FATAL  In order to use nuxt export, you need to run nuxt build --target static                                                                                                      19:30:34  

  at Generator.initiate (node_modules\@nuxt\generator-edge\dist\generator.js:160:15)


   ╭────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                        │
   │   ✖ Nuxt Fatal Error                                                                   │
   │                                                                                        │
   │   Error: In order to use `nuxt export`, you need to run `nuxt build --target static`   │
   │                                                                                        │
   ╰────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10766">#c10766</a>)</em></sub></div>

**Comment by RyanCasas** [comment]
CC @Atinux @pi0

**Comment by pi0** [comment]
Hi :) This should be fixed by #7509

**Comment by Atinux** [comment]
This PR should fix it: https://github.com/nuxt/nuxt.js/pull/7523

**Comment by Atinux** [comment]
@RyanCasas can you confirm with lastest `nuxt-edge`?

**Comment by RyanCasas** [comment]
> @RyanCasas can you confirm with lastest `nuxt-edge`?

It does work with the provided example @Atinux, I still have to try it on more complex scenarios tho. I'll open another issue if that's the case. 

Thank you all for your work :)
