### ISSUE TITLE
[2.13.0] Script not called when refresh or page from direct link

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt/nuxt.js#7513]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/mathieunicolas/site-perso/blob/master/components/mastotest.vue](https://github.com/mathieunicolas/site-perso/blob/master/components/mastotest.vue)

### Steps to reproduce

I use nuxt-edge, with `target: static`. This bug appears mostly when `dist` directory is uploaded into netlify. There's no problem when I use `npm run serve` after `npm run generate` (which is build && generate).

When you go to https://musing-ardinghelli-337c44.netlify.app/ then click on "Mastodon c'est cool", the comments appear. If you reload, they don't.
When you go to https://musing-ardinghelli-337c44.netlify.app/foss/mastodon, the comments don't appear. The mount script is not called. 

I spend HOURS on this problem, I don't know why this behaviour.
I've tried so many things... Fetching from a page component, using middlewares, methods, inline calls, mounted, created, method called from the page...

The code of the component : 
```
<template>
  <div class="mastotest" v-if="disp">
    <h3>Commentaires à cet article :</h3>
    <p>
      <em
        ><a :href="`https://diaspodon.fr/web/statuses/${statid}`"
          >(Commenter sur mastodon)</a
        ></em
      >
    </p>
    <mastocom
      v-for="com in data.descendants"
      :com="com"
      :key="com.id.toString()"
      class="comms"
    ></mastocom>
  </div>
</template>

<script>
export default {
  props: ["statid"],
  async mounted() {
    console.log("yo le mounted diou");
    this.data = await fetch(
      `https://diaspodon.fr/api/v1/statuses/${this.statid}/context`
    ).then(res => res.json());
  },
  data() {
    return { data: null };
  },
  computed: {
    disp: function() {
      if (this.data && this.data.descendants.length > 0) return true;
      else return false;
    }
  }
};
</script>
```

It's in the `mastotest` component, called in `/pages/_dir/_slug.vue`
Do you why ? And how I can fetch mastodon comments each time the page is reloaded/called/displayed from direct link, no matter from where it's called ?

Thanks !

### What is expected ?

Comments in pages reloaded each time the page is displayed/reloaded/accessed from direct link

### What is actually happening?

Comments don't appear when reloading the page, accessing it from a direct link.

### Additional comments?

Please help meeeee I'm clueless and I think I've tried everything !

Thanks !

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10769">#c10769</a>)</em></sub></div>

**Comment by mathieunicolas** [comment]
Small and shy up, because I definitely don't understand what's going on with this one and I don't know where to look...
thanks guys !

**Comment by manniL** [comment]
The console says `DOMException: Node.appendChild: Cannot add children to a Text`. Might be an issue related to hydration, e.g. to https://github.com/nuxt/nuxt.js/issues/1552

**Comment by mathieunicolas** [comment]
> The console says `DOMException: Node.appendChild: Cannot add children to a Text`. Might be a userland issue related to hydration, e.g. to #1552

damn your reply rang a bell. This error comes from netlify forms, and I noticed the form still works so I didn't pay attention to it anymore.
But the fact is, this error was apparently linked to my issue : I deleted the netlify form, and it worked like a charm.

Thanks for you intervention, I feel perfectly good now !

**Comment by yoyo837** [comment]
Nuxt generated some js files named starting with .(dot), but the browser request will be 404
