### ISSUE TITLE
need update on jsdom ? 

### ISSUE THREAD

**Issue by Kylart** [nuxt/nuxt.js#752]
Hi,

When writing my tests scripts lately, I encountered a problem with jsdom when following the [official guide](https://nuxtjs.org/guide/development-tools#end-to-end-testing). 
Problem is: `TypeError: jsdom.createVirutalConsole() is not a function.`

Indeed, `jsdom` does not have a method named `createVirtualConsole`. I guess it was renamed `VirtualConsole` as one can see [here](https://github.com/tmpvar/jsdom#virtual-consoles). So I tried and changed that but then I encountered another error: `[TypeError: jsdom.env is not a function]`.

Maybe nuxt needs an update on this? 
 
If so, I think I could do it but it would take some time since I do not completely understand jsdom and I would need to dive into nuxt code.

**Comment by pi0** [comment]
@Kylart Are you calling `createVirtualConsole` directly in your tests? If possible please provide your tests code.
Also consider that we are using [old api](https://github.com/tmpvar/jsdom/blob/master/lib/old-api.md) with latest version as newer api has still some limitations.

**Comment by Kylart** [comment]
I don't. My code is the following:
```javascript
test('Route /downloader', async t => {
  const window = await nuxt.renderAndGetWindow(`${uri}/downloader`)
  const element = window.document.querySelector('div.form-container')
  t.not(element, null)
})
```
<img width="708" alt="screen shot 2017-05-23 at 12 09 24" src="https://cloud.githubusercontent.com/assets/18316666/26349675/bce07bb8-3fb0-11e7-9327-a3dbd0358a26.png">

I checked and my jsdom version is 10.1 which is the one used by nuxt. `old-api.js` is also present.

**Comment by natecox** [comment]
I'm also getting this same error, with my test nearly verbatim from the docs [here](https://nuxtjs.org/guide/development-tools#end-to-end-testing). 

If I use the `await nuxt.renderRoute('/', context)` version everything is fine, but if I use the dom checking example it fails with the above error.

**Comment by natecox** [comment]
Downgrading `jsdom` to `9.12.0` seems to fix the issue.

**Comment by Atinux** [comment]
`jsdom` usage has been updated, will be good for the `alpha3` :)

See https://github.com/nuxt/nuxt.js/commit/488010bf78854d8017a79e28ac4cc644e5ac98cc

**Comment by Atinux** [comment]
The alpha3 is out :)
