### ISSUE TITLE
nuxt start complains about local module missing.

### ISSUE THREAD

**Issue by lromor** [nuxt/nuxt.js#7524]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Steps to reproduce

I am using, as suggested in the documentation, a local folder ./modules to store a custom private module.
The module properly runs and during build copies the dependencies inside the .nuxt folder.

When running nuxt build and nuxt start having only the minimum required folders
(static, .nuxt, nuxt.config.js)  the modules are still parsed and searched even though they should be technically already inside the .nuxt folder.

### What is expected ?

Nuxt shouldn't complain about missing modules after running
the build and then the start command.

### What is actually happening?

Returns an error that the module is missing.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10776">#c10776</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @lromor. It is intended (however not perfect). If module is only hooking for build/dev, you can list it in `buildModules` instead of `modules` inside `nuxt.config`. Otherwise, if needed for runtime (adding a middleware, hooking into renderer, etc) needs to be kept same as required forlders.

**Comment by lromor** [comment]
I see, thank you for making it more defined. My module indeed defines a middleware, so I guess my only possibility is to add the module in node_modules or in the root of my project.

**Comment by lromor** [comment]
@pi0 , What I did was making an env variable that would disable the module in the nuxt.config.json
since all the content (the middleware as well) is already included in the build.
Do you think it makes sense?

**Comment by pi0** [comment]
Hi @lromor yet it makes sense (just i meant serverMiddleware not nuxt middleware). Would be nice to also share code usage :)

**Comment by lromor** [comment]
Yeah, 
so, for reference:

```
  modules: [
    // Doc: https://buefy.github.io/#/documentation
    'nuxt-buefy',
    // My custom auth module
    ...((process.env.NUXT_START) ? [] : ['./modules/auth/index']),
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/proxy'
  ],

```
and then `NUXT_START=1 nuxt start`

**Comment by pi0** [comment]
@lromor You don't need that if using `buildModules` option. They are disabled for `nuxt start`. Docs: https://nuxtjs.org/guide/modules/#build-only-modules
