### ISSUE TITLE
1.0.0-alpha1 Nuxt with Koa

### ISSUE THREAD

**Issue by clarkdo** [nuxt/nuxt.js#753]
According to the Nuxt.js codes of 1.0.0-alpha1, initialization of nuxt has been changed into asynchronous.
So how can we use koa in server side codes, should I wrap all koa app.use inside  nuxt.then ?

```javascript
const nuxt = new Nuxt(config)
nuxt.then((nuxt) => {
  nuxt.build()
  app.use(async (ctx, next) => {
    // ...
    await next()
    // ...
  })
  app.use(async (ctx, next) => {
    // ...
    await next()
    // ...
  })
})
```

**Comment by Atinux** [comment]
The [nxut/koa](https://github.com/nuxt/ko) starter has been updated :+1:
