### ISSUE TITLE
Issue search in cmty.app leads to 404

### ISSUE THREAD

**Issue by dword-design** [nuxt/nuxt.js#7546]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://cmty.app/nuxt/nuxt.js/issues?q=breaks](https://cmty.app/nuxt/nuxt.js/issues?q=breaks)

### Steps to reproduce

Open the reproduction link

### What is expected ?

See results with the word 'breaks'

### What is actually happening?

See a 404

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10788">#c10788</a>)</em></sub></div>

**Comment by Atinux** [comment]
We plan to remove CMTY pretty soon, in the meantime you can use the GitHub search. Sorry about this!
