### ISSUE TITLE
$router.back() not change layout

### ISSUE THREAD

**Issue by hoquangthaiholy** [nuxt/nuxt.js#7554]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://jsbin.com/kotehayoda](https://jsbin.com/kotehayoda)

### Steps to reproduce

Try to come the error Page not found and back to the previous page

### What is expected ?

$router.back should change the layout

### What is actually happening?

the layout not change

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10796">#c10796</a>)</em></sub></div>

**Comment by usb248** [comment]
+1

**Comment by Atinux** [comment]
Please provide a minimal reproduction by forking https://template.nuxtjs.org

**Comment by hoquangthaiholy** [comment]
My problem is the same with @usb248
