### ISSUE TITLE
Strip comments from produced code in production mode.

### ISSUE THREAD

**Issue by lukeshiels** [nuxt/nuxt.js#756]
When my website is finished - it's all good and Nuxt works great.

However, there's lots of comments that add like 20% extra to my payload size.

![nuxtissue](https://cloud.githubusercontent.com/assets/11036001/26301926/82621bbc-3eda-11e7-8755-8b8379c3dcfe.jpeg)

I think you could strip comments out of the final code and have it as an option under the performance options of Nuxt.

I'll attempt a pull request but I've never even looked at Nuxt's code so I don't think I'll be able to implement it.

**Comment by stephan281094** [comment]
I don't think you're legally allowed to strip the copyright comments. To quote the MIT license:
>The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by pi0** [comment]
Related to webpack/webpack#1205 topic.  For css loader there is a hack:
```
loaders: [{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract('style-loader', 'css-loader?' + JSON.stringify({discardComments: {removeAll: true}}))
}]
```

But as @stephan281094 I think it is an intentional behaviour for legal reasons .

**Comment by Atinux** [comment]
Exactly, these comments are not so much weight and give credits to the developers who worked on these libraries.

Since Nuxt.js is also open-source with an MIT license, we encourage to keep these comments in the code.

You can use @pi0 solution if you want but it won't be implemented into nuxt.js core.
