### ISSUE TITLE
Can't disable telemetry with config or .env

### ISSUE THREAD

**Issue by tamerkalieh** [nuxt/nuxt.js#7564]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://github.com/nuxt/telemetry](https://github.com/nuxt/telemetry)

### Steps to reproduce

I've cloned the project. I've tried:

`telemetry: false,` to the nuxt-config.js file (just above mode: 'universal') 
and
`NUXT_TELEMETRY_DISABLED=1` in my .env 

To check if it is disabled: 
`npx nuxt telemetry status`

Both ways are not working for me. telemetry is still enabled. I only can disable it with: 

`npx nuxt telemetry disable`

But I don't want that extra .nuxtrc file, just to disable it.

### What is expected ?

ℹ Nuxt telemetry is disabled on current project   

### What is actually happening?

ℹ Nuxt telemetry is enabled on current project   

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10808">#c10808</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @tamerkalieh. Setting `telemetry: false` to `nuxt.config` should be enough. `status` cannot check it with the current version. To ensure it is disabled, you can try `NUXT_TELEMTRY_DEBUG` if any event is sent it will show it.

**Comment by MSkred** [comment]
I'm on nuxt 2.12.2 and when I deploy on SSR with lambda I've some telemetry error .... then an internal server error

**Comment by MSkred** [comment]
Cloud Watch logs 

```

2020-06-25T15:54:42.573+02:00 | FATAL ENOENT: no such file or directory, open '/home/sbx_user1051/.nuxtrc'
-- | --
  | 2020-06-25T15:54:42.573+02:00 | at Object.openSync (fs.js:443:3)
  | 2020-06-25T15:54:42.573+02:00 | at Object.writeFileSync (fs.js:1194:35)
  | 2020-06-25T15:54:42.573+02:00 | at write (node_modules/rc9/dist/index.js:87:6)
  | 2020-06-25T15:54:42.573+02:00 | at update (node_modules/rc9/dist/index.js:106:3)
  | 2020-06-25T15:54:42.573+02:00 | at Object.updateUser (node_modules/rc9/dist/index.js:112:10)
  | 2020-06-25T15:54:42.573+02:00 | at updateUserNuxtRc (node_modules/@nuxt/telemetry/dist/module.js:30:6)
  | 2020-06-25T15:54:42.573+02:00 | at ModuleContainer.telemetryModule (node_modules/@nuxt/telemetry/dist/module.js:511:5)
```

**Comment by michael42** [comment]
In our project, the recent telemetry (when updating from 2.12.2 to 2.13.1) also breaks service startup:

```
 FATAL  EACCES: permission denied, open '/.nuxtrc'

  at Object.openSync (fs.js:458:3)
  at Object.writeFileSync (fs.js:1355:35)
  at write (node_modules/rc9/dist/index.js:87:6)
  at update (node_modules/rc9/dist/index.js:106:3)
  at Object.updateUser (node_modules/rc9/dist/index.js:112:10)
  at updateUserNuxtRc (node_modules/@nuxt/telemetry/dist/module.js:30:6)
  at ModuleContainer.telemetryModule (node_modules/@nuxt/telemetry/dist/module.js:511:5)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:223:20)

^[[53;157R
   ╭───────────────────────────────────────────────────────╮
   │                                                       │
   │   ✖ Nuxt Fatal Error                                  │
   │                                                       │
   │   Error: EACCES: permission denied, open '/.nuxtrc'   │
   │                                                       │
   ╰───────────────────────────────────────────────────────╯

```

Apparently, it requires write permissions to `/.nuxtrc`, which it doesn't (and should not) have.

**Comment by michael42** [comment]
Putting a `.nuxtrc` with `telemetry.enabled=false` in the project root (and docker container) fixed it, `telemetry: false` isn't even [documented](https://nuxtjs.org/guide/configuration/).

**Comment by pi0** [comment]
Hi. Sorry for the inconvenience. Opt-in/out is documented in [nuxt/telemetry](https://github.com/nuxt/telemetry#opting-out) docs.

Also, permission denied error should be gone with 1.2.0 (you can use `yarn upgrade nuxt` to get the update). (It was happening because telemetry generates a random seed used for hash calculation.)

I'm closing issue as should be resolved. Please create new issue on [nuxt/telemetry](https://github.com/nuxt/telemetry/issues/new) if there was still issues.
