### ISSUE TITLE
'nuxt build' failed on Netlify, success on local

### ISSUE THREAD

**Issue by ballonura** [nuxt/nuxt.js#7570]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Steps to reproduce

![Capture.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/0cb51f10-b2b6-11ea-b089-39ca1f6ad22d.PNG)

### What is expected ?

Build should work, this the package.json build script (name: generate):
generate: npm run build && npm run export && npm run build:netlify-functions
nuxt.config.js: mode: "universal", target: "static"

### What is actually happening?

Build failed with error:

8:19:16 AM: ┌─────────────────────────────┐
8:19:16 AM: │   "build.command" failed    │
8:19:16 AM: └─────────────────────────────┘
8:19:16 AM: ​
8:19:16 AM:   Error message
8:19:16 AM:   Command failed with exit code 1: npm run generate
8:19:16 AM: ​
8:19:16 AM:   Error location
8:19:16 AM:   In build.command from netlify.toml:
8:19:16 AM:   npm run generate

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10816">#c10816</a>)</em></sub></div>

**Comment by lucpotage** [comment]
Hello @ballonura, do you have the same issue when using the command line `npm run build && npm run export` and defining `target: 'static'` in the config file?

**Comment by ballonura** [comment]
Yes, my settings: 
mode: "universal"
target: "static"

Thx.

**Comment by ballonura** [comment]
**Problem solved**: Netlify using old node version 8.x.x.

**Comment by manniL** [comment]
> **Problem solved**: Netlify using old node version 8.x.x.

You can set the node version via your `netlify.toml` btw 😋 

Closing here 👍
