### ISSUE TITLE
npm link packageName does not work when using nuxt

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#758]
Hi,
I am using `vuetify`and trying to do some local development inside of my current nuxt project. But `npm link vuetify` does not work as expected. The resources is never being updated. Any idea what prevents reloading of the current linked npm package? The renderer seems being triggered without a change in the build.
Thanks

**Comment by pi0** [comment]
Hi @dohomi Are you using plugins for component registration? Also what is your nuxt version?

**Comment by dohomi** [comment]
@pi0 yes I am using it. I run on the latest NUXT version 0.10.7, I add the linked package inside of the nuxt.config.js as follow:
```
  build: {
    extend (config, {dev}) {
      config.module.rules.push({
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader'
      })
    },
    vendor: [
     (...)
      'vuetify'
    ]
  },
  plugins: [
    '~plugins/vuetify', 
(...)
  ],
```

**Comment by pi0** [comment]
(Sorry for delay i went asleep last night :D)
If you want to use npm/link for testing 3rd party libs, you have to enable special `--preserve-systemlinks` node flag. There are two ways:
- Update package.json nuxt start script to something like this: `node --preserve-systemlinks ./node_modules/nuxt/bin/nuxt start`
- Or easily set `NODE_PRESERVE_SYMLINKS=1` environment variable in anyway you prefer. (Needs node 7.1+)

**Comment by dohomi** [comment]
@pi0 thanks, I went offline as well :) I will try the options and see if it solves my issue, I'm running on 7.7.x

**Comment by dohomi** [comment]
seems to be tricky.. don't work building the sources now: ```
ERROR in ../vuetify/dist/vuetify.js
Module build failed: Error: Couldn't find preset "vue-app" relative to directory "/data/vuejs/vuetify/dist"
```

**Comment by mamboer** [comment]
Same `Couldn't find preset "vue-app" relative to directory` issue in one of my nuxt project, it's weird.

**Comment by homerjam** [comment]
+1

**Comment by jimliang** [comment]
+2

**Comment by buhrmi** [comment]
Same error after running `npm link linked-package` in my nuxt project

In `store/index.js`:

```
import linkedPackage from 'linked-package'

export default function() { return {} }
```

results in `Module build failed: Error: Couldn't find preset "vue-app" relative to directory "/home/buhrmi/linked-package"

Tried to add the `NODE_PRESERVE_SYMLINKS=1` env var but it doesn't help ...

Any clues?

**Comment by buhrmi** [comment]
Small discovery: When running `npm install --save-dev babel-preset-vue-app` in the LINKED package, it starts working. I guess there is some trouble with symlinks. Hope it helps.

**Comment by pi0** [comment]
Most problems with linked usage and npx are resolved and more are going to be fixed with `rc5`. Feel free reopening this if there was problems anymore. Also a new option `modulesDir` is added so we can explicitly define root of `node_modules`.
