### ISSUE TITLE
Missed crawler field definition in NuxtOptionsGenerate

### ISSUE THREAD

**Issue by is-blackhole** [nuxt/nuxt.js#7585]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://jsfiddle.net/z0sLajyw/](https://jsfiddle.net/z0sLajyw/)

### Steps to reproduce

according to docs https://nuxtjs.org/api/configuration-generate#crawler generate definition can have crawler, but its missed in NuxtOptionsGenerate

### What is expected ?

no errors

### What is actually happening?

Type '{ crawler: false; }' is not assignable to type 'NuxtOptionsGenerate'.
  Object literal may only specify known properties, and 'crawler' does not exist in type 'NuxtOptionsGenerate'.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10829">#c10829</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks for report @is-blackhole. Fix is avilable with `nuxt-edge` and will be published ASAP with next patch release.

**Comment by pi0** [comment]
Hi! This should be fixed with [v2.13.1](https://github.com/nuxt/nuxt.js/releases/tag/v2.13.1).
