### ISSUE TITLE
vue-loader issues since v2.13.0 - compiler options changed?!

### ISSUE THREAD

**Issue by MrParano1d** [nuxt/nuxt.js#7588]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://codesandbox.io/s/green-waterfall-yyldo?file=/package.json](https://codesandbox.io/s/green-waterfall-yyldo?file=/package.json)

### Steps to reproduce

1. write vue component with custom-blocks like `<docs>`
2. start nuxt
3. get errors

### What is expected ?

render a simple vue component

### What is actually happening?

The vue-loader trys to parse my custom <docs> block which contains markdown.

### Additional comments?

I upgraded our software UI from v2.12.2 to v2.13.0 and suddenly every dev-start failed because the vue-loader tried to parse our custom <docs> blocks in our UI-Components.

After a wild hour of debugging I realized that the compiler options for the vue loader plugin changed from v2.12.2 to v2.13.0 but I couldn't see in the release commits which part you guys changed.

My question is: How do I configure nuxt to NOT parse the <docs> custom block?

For now I switch back to v2.12.2 but I really would like to know what changed in the build process.

The error can be seen in this codesandbox: https://yyldo-3000.sse.codesandbox.io/

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10832">#c10832</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @MrParano1d. It seems issue is from [`@nuxt/components`](https://github.com/nuxt/components). Would you please try `components: false` from `nuxt.config`? We will meanwhile work on the fix on components module.

**Comment by MrParano1d** [comment]
I didn't install that module in the codesandbox or is it installed by default now?

Anyway, I added `components: false` to `nuxt.config` and still get the error in the codesandbox.

**Comment by Tanchiky** [comment]
I've encountered a bug similar to this one.
It happened after I upgraded my version from `v2.12.2` to `v2.13.1`.

I'm getting the following errors in the terminal
```Bash
ERROR in /Users/tanchiky/test_prj/node_modules/@nuxt/types/config/build.d.ts(16,34):
16:34 Cannot find module 'vue-loader'.
    14 | import { Options as PugOptions } from 'pug'
    15 | import { TerserPluginOptions } from 'terser-webpack-plugin'
  > 16 | import { VueLoaderOptions } from 'vue-loader'
       |                                  ^
    17 | import {
    18 |   Configuration as WebpackConfiguration,
    19 |   Loader as WebpackLoader,
```

What do you know about this?

I hope this information helps someone else.
thanks:)

**Comment by gabrielrobert** [comment]
@Tanchiky I got the same problem. My temporary fix was to execute `yarn add vue-loader@15.7.0 --dev`.

**Comment by pi0** [comment]
Would you please try recreating `yarn.lock`? It may both fix `vue-loader` issue and also `components: false` (fixed with `@nuxt/components` v1.0.5)

**Comment by MrParano1d** [comment]
I updated the sandbox to `nuxt.js` v2.13.1 and reinstalled all packages. Everything is back to normal now. Thank you :)
`@nuxt/components` v1.0.5 is fixing it.

**Comment by gabrielrobert** [comment]
It worked @pi0, many thanks. Keep up the good work! :)
