### ISSUE TITLE
Missing $config type in Context

### ISSUE THREAD

**Issue by WTDuck** [nuxt/nuxt.js#7596]
### Version

[v2.13.1](https://github.com/nuxt.js/releases/tag/v2.13.1)

### Reproduction link

[https://github.com/nuxt/nuxt.js/blob/40ceb61fabd682846b234059724d894e3f3127ea/packages/types/app/index.d.ts](https://github.com/nuxt/nuxt.js/blob/40ceb61fabd682846b234059724d894e3f3127ea/packages/types/app/index.d.ts)

### Steps to reproduce

Nothing much actually.
Inside a Typescript environment, "$config" type doesn't exist inside the Context parameter.

### What is expected ?

Context interface should expect a "$config" field

### What is actually happening?

Type Error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10839">#c10839</a>)</em></sub></div>

**Comment by WTDuck** [comment]
For people interested in a workaround :
```typescript
declare module 'vue/types/vue' {
  interface Vue {
    $config: any
  }
}

declare module '@nuxt/types' {
  interface Context {
    $config: any
  }
}
```

**Comment by pi0** [comment]
Hi @WTDuck. Types are provided i think you just need to add `@nuxt/types@2.13.0` (the one shipped with `@nuxt/typescript` is`0.x` and will be removed soon).

Please reopen if upgrading didn't resolve the issue.

**Comment by WTDuck** [comment]
I believe you got me wrong.
NuxtJS package already provides type definition for TypeScript and it's awesome (aka @nuxt/types)

I'm just pointing a missing key inside those definitions about the new context feature : $config

```typescript
export interface Context {
  app: NuxtAppOptions
  base: string
  ...
  // missing $config
  }
```

**Comment by WTDuck** [comment]
Related issue : https://github.com/nuxt/typescript/issues/386

**Comment by webcoderkz** [comment]
@pi0 

![image](https://user-images.githubusercontent.com/5739191/85916305-5b40a580-b871-11ea-9c41-5fb5900a18cb.png)

I guess, you need to update `@nuxt/typescript-build` package with updated `@nuxt/types` package.
