### ISSUE TITLE
random port for full static generate

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/nuxt.js#7597]
### Version

[v2.13.1](https://github.com/nuxt.js/releases/tag/v2.13.1)

### Reproduction link

[https://github.com/nuxt/nuxtjs.org/tree/dev](https://github.com/nuxt/nuxtjs.org/tree/dev)

### Steps to reproduce

Open any nuxt project and run dev. This will then use port of 3000. Then open a project that uses v2.13 and run generate which will use nuxt build and nuxt export. As port 3000 is already taken you cannot generate your site unless you close the other port.

### What is expected ?

should generate a random port if port is in use

### What is actually happening?

Nuxt Fatal error
![Screenshot 2020-06-24 at 12.41.36.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/18507ea0-b60d-11ea-9564-4302e37760d1.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10840">#c10840</a>)</em></sub></div>

**Comment by manniL** [comment]
cc @hecktarzuli

**Comment by pi0** [comment]
Fixed with [v2.13.2](https://github.com/nuxt/nuxt.js/releases/tag/v2.13.2)

**Comment by andre-brdoch** [comment]
How can the random port be retrieved?

**Comment by pi0** [comment]
Hi @andre-brdoch You may use both `nuxt.server.listeners` or use `nuxt.hook('listen', (server, listener) => {})` 

If wanted more details would be appreciated making a new issue with usage example :)
