### ISSUE TITLE
nuxt generate assets path

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#760]
For exapmle, my page is: `pages/test/index.vue`, when I run `nuxt generate` I got a file in `dist/test/index.html`

If I run a static server at `dist`  folder and visit `XXXX/test/index.html` erverything works well.

But now, I just need to open `dist/test/index.html` directly, not through static server, I will got error!

I found that the js file path in `dist/test/index.html` is like `/_nuxt/nuxt.bundle.fa064f5ae51836ff9840.js` .

So how can I  generate the file that can directly run in broswer with right js path?

**Comment by bimohxh** [comment]
I try to change all of the js files path in `dist/test/index.html`  to like  `../_nuxt/nuxt.bundle.fa064f5ae51836ff9840.js`  manually, but sitll have some js file's path is error, maybe some where else?

**Comment by ausir0726** [comment]
seems like base alway will be set `'/'`
that will be let your .js begin `/_nuxt/bundle.js`
maybe you can try setting in `nuxt.config.js`
```
router : {
  base : ''
}
``` 
I don't know the result ...

**Comment by bimohxh** [comment]
@ausir0726 thanks,  this is not work!

**Comment by bimohxh** [comment]
If I want to deploy the static site on an oss cloud(for example: GitHub page), this is impossible

**Comment by ausir0726** [comment]
@bimohxh 我不太明瞭，如果要 deploy 一般的靜態託管，不是應該是正常的 generate 步驟即可嗎？

**Comment by bimohxh** [comment]
@ausir0726 是这样的，官方所谓的generate 后靜態託管，是需要启一个静态服务器的，所以里面的js文件路径没有问题。

而现在我是需要直接打开dist目录下面的html文件，js文件的路径就出问题了

**Comment by ausir0726** [comment]
對，就像我說的，他的預設 base 都鎖定在 /
所以你如果直接打開 file 就會無法正確對應到 js 位置 
你需要起一個 static hosting 才可以正確瀏覽網頁
這個情況也會發生在包裝 phonegap ，因為封裝後瀏覽都是用 file://folder/index.html
也不可以設定 `<base>`

但如果發佈在網路上的話應該都用標準的 generate 流程即可...

所以你測試現在沒問題了？

**Comment by bimohxh** [comment]
@ausir0726  你说的对，我目前的问题还存在，官方是不支持直接打开 html 文件的。

**Comment by ausir0726** [comment]
@bimohxh 
我個人看法是如果沒有 `/` 是否會影響到 SSR 的功能
如果官方可以支持 phonegap 的話應該就可以解決你的問題
（ 或是說解決你的問題就可以解決 phonegap 的問題 😆  )

**Comment by ausir0726** [comment]
follow this

https://github.com/nuxt/nuxt.js/issues/168

seems like it not resolve yet .

**Comment by bimohxh** [comment]
@ausir0726 谢了，其实我是想要一个纯静态的站点，不需要 SSR 的功能。

官方目前肯定是不支持的，不知道以后会不会支持，我只能考虑在 winform 中启一个静态服务器了

**Comment by ausir0726** [comment]
@bimohxh 

I also want nuxt.js can working on cordova / phonegap .

**Comment by bimohxh** [comment]
@ausir0726 That would be best!
