### ISSUE TITLE
Reloading the page does not load the assets

### ISSUE THREAD

**Issue by dev-mood** [nuxt/nuxt.js#7616]
### Version

[v2.13.1](https://github.com/nuxt.js/releases/tag/v2.13.1)

### Reproduction link

[https://5ef604edab4e7892c3ca11f0--brave-shockley-f8afe2.netlify.app/nuestra-carta/](https://5ef604edab4e7892c3ca11f0--brave-shockley-f8afe2.netlify.app/nuestra-carta/)

### Steps to reproduce

Clicking F5 or button to reload the page

### What is expected ?

It is expected to load all assets (css, js, etc)

### What is actually happening?

Does not load javascript or CSS files

### Additional comments?

![Captura.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/315fbf60-b7ba-11ea-b266-dbc169d911b6.PNG)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10850">#c10850</a>)</em></sub></div>

**Comment by manniL** [comment]
Reproduction is gone.
