### ISSUE TITLE
Build indicator is gone

### ISSUE THREAD

**Issue by janswist** [nuxt/nuxt.js#7619]
### Version

[v2.13.1](https://github.com/nuxt.js/releases/tag/v2.13.1)

### Reproduction link

[https://has-no-reproduction.com](https://has-no-reproduction.com)

### Steps to reproduce

Make a change in template and save. 

### What is expected ?

To show build indicator.

### What is actually happening?

No build indicator is shown.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10853">#c10853</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. This was a temporary issue. Please use `yarn nuxt upgrade` to get the latest version of `@nuxt/loading-screen`

**Comment by janswist** [comment]
Good to know, thanks! It really helps when loading gets longer to see if anything is actually going on. I use `npm` and I see that on repository it's still 2.13.1 - when it should be available there?

**Comment by pi0** [comment]
@janswist You can maybe try remove `package.lock.json`? (npm upgrade should also work but never tested so..)

**Comment by janswist** [comment]
@pi0 doesn't seem to be working, although I updated all the other packages. I think I can wait for official release (probably over the weekend or couple of days). Anyway, now I know at least where it's at. Thanks!

**Comment by pi0** [comment]
Just for you :) https://github.com/nuxt/nuxt.js/releases/tag/v2.13.2
