### ISSUE TITLE
How to set up proxy with nuxt.config.js

### ISSUE THREAD

**Issue by chunge0328** [nuxt/nuxt.js#762]
```js
 dev: {
    env: require('./dev.env'),
    port: 8888,
    autoOpenBrowser: true,
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    proxyTable: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      },
      '/local': {
        target: 'http://localhost:3000',
        changeOrigin: true,
        pathRewrite: {
          '^/local': ''
        }
      }
    }
```
thanks

**Comment by piyushchauhan2011** [comment]
I tried to define `proxy` under 'build/extend' section in `nuxt.config.js` like this:

```javascript
build: {
    extend (config, ctx) {
      const proxy = {
        proxy: {
          '/api': 'http://127.0.0.1:5000'
        }
      }
      config.devServer = Object.create({}, config.devServer, proxy)
    },
  },
```

But, I still get no-access @chunge0328 @alexchopin

**Comment by piyushchauhan2011** [comment]
I created a demo on glitch here https://slash-crocodile.glitch.me/about which requests `jsonplaceholder` api for posts. Code is here: https://glitch.com/edit/#!/slash-crocodile?path=pages/about.vue:20:1

**Comment by pi0** [comment]
Proxy Module Coming Soon :)

**Comment by piyushchauhan2011** [comment]
Waiting eagerly for it 😍

**Comment by piyushchauhan2011** [comment]
For now who are struggling to get it working they can use Nuxt+Express setup with `http-proxy-middleware` which just proxy request to desired api.
https://github.com/chimurai/http-proxy-middleware

Just a drop in for now ;)

**Comment by pi0** [comment]
@piyushchauhan2011 I'm exactly using http-proxy-middleware for that module :) `proxy` module just adds support to internal nuxt server without express.

**Comment by piyushchauhan2011** [comment]
Yup that would be clean and easy to setup, just a drop-in  ;)

**Comment by pi0** [comment]
[proxy module](https://github.com/nuxt/modules/tree/master/modules/proxy) is available now! Currently as an internal limitation it only works with nuxt internal server, Also express support is coming soon in next Nuxt alpha releases.

**Comment by SinisaG** [comment]
So this modules are available for version `1+`, that is currently in alpha? Is there a way to setup proxy for previous versions? I am struggling with the same issues as comments above.

**Comment by c4milo** [comment]
proxy module seems useful but it would be very convenient to also use Webpack's internal dev server.

**Comment by c4milo** [comment]
@pi0 how can I provide a custom matching function as context to the nuxt proxy module?

**Comment by levy9527** [comment]
look at this 
[https://www.npmjs.com/package/@nuxtjs/proxy](url)
