### ISSUE TITLE
Generate static page access full path'payload' failed to load

### ISSUE THREAD

**Issue by lxzgg** [nuxt/nuxt.js#7622]
### Version

[v2.13.2](https://github.com/nuxt.js/releases/tag/v2.13.2)

### Steps to reproduce

Visit after generating static page -> http://dist.lssss.cn/about/index.html

### What is expected ?

Load payload.js correct path

http://dist.lssss.cn/_nuxt/static/1593206460/about/payload.js

### What is actually happening?

No filter index.html

http://dist.lssss.cn/_nuxt/static/1593206460/about/index.html/payload.js

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10857">#c10857</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @lxzgg. I'm getting 404 on all pages. Maybe it is a deployment issue? Otherwise is it possible to somehome make a simpler reproduction to share?
