### ISSUE TITLE
Why SCSS classes is not applied/compiled in Nuxt when pushed to production (AWS)?

### ISSUE THREAD

**Issue by yashwp** [nuxt/nuxt.js#7624]
### Version

[2.0.0](https://github.com/nuxt.js/releases/tag/2.0.0)

### Reproduction link

[https://stackoverflow.com/questions/62606204/why-scss-classes-is-not-applied-compiled-in-nuxt-when-pushed-to-production-aws](https://stackoverflow.com/questions/62606204/why-scss-classes-is-not-applied-compiled-in-nuxt-when-pushed-to-production-aws)

### Steps to reproduce

I'm developing a website in Nuxt.js. Locally when the application is served, the SCSS compiled perfectly and applied it on the pages. In my index.vue and other components, the styles(SCSS) are scoped.

### What is expected ?

Should work without removing scope

### What is actually happening?

When I'm deploying the site to production, suddenly none of the styles (scoped) seem working! But if I remove the scope, it is working on prod as well. But this doesn't feel the right way, it totally violated the concept of scoping the styles.

### Additional comments?

https://stackoverflow.com/questions/62606204/why-scss-classes-is-not-applied-compiled-in-nuxt-when-pushed-to-production-aws

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10859">#c10859</a>)</em></sub></div>

**Comment by manniL** [comment]
Looks like purgeCSS is stripping most of your classes. Not an issue with Nuxt itself.
