### ISSUE TITLE
Dynamic routing broken with AWS API Gateway

### ISSUE THREAD

**Issue by aaronhuisinga** [nuxt/nuxt.js#7625]
### Version

[v2.13.2](https://github.com/nuxt.js/releases/tag/v2.13.2)

### Reproduction link

(Not possible without AWS setup using API Gateway)

### Steps to reproduce

1. Setup Nuxt app running behind AWS API Gateway
2. Create dynamic route
3. Click link to dynamic route

### What is expected ?

Router navigates to page defined in dynamic route

### What is actually happening?

400 error when trying to fetch `/_nuxt/pages/resource/[_]id.js`

### Additional comments?

AWS API Gateway does not allow square brackets "[" and "]" in URLs. Nuxt uses these square brackets in the file names for the compiled JS for dynamic routes. Any time that a request is made to load this file, API Gateway returns a 400 error. The recommended fix for this is encoding the URL before making the request, which is what Next.js did to fix this same issue (https://github.com/vercel/next.js/issues/8013). Another possible fix could be adding a configuration option for changing the name of the generated files for dynamic routes, and giving users the ability to replace the square brackets with something else.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10860">#c10860</a>)</em></sub></div>

**Comment by cmorbitzer** [comment]
Also experiencing this issue. Seems to be introduced by #7603

**Comment by pi0** [comment]
Hi! Should be fixed by #7639 (you can early test using `nuxt-edge`)

**Comment by aaronhuisinga** [comment]
Thanks @pi0! I can confirm this PR fixes the issue. Just tested using `nuxt-edge` and routing works as expected.
