### ISSUE TITLE
vuex 3.5.0 logger.d.ts wrong location

### ISSUE THREAD

**Issue by olamedia** [nuxt/nuxt.js#7636]
### Version

[v2.13.2](https://github.com/nuxt.js/releases/tag/v2.13.2)

### Reproduction link

[https://codesandbox.io/s/solitary-surf-s268j](https://codesandbox.io/s/solitary-surf-s268j)

### Steps to reproduce

`yarn create nuxt-app <project-name>`

### What is expected ?

logger.d.ts located at vuex/types

### What is actually happening?

logger.d.ts located at vuex/dist
```
ERROR in ....... vuex/types/index.d.ts(10,15):                                                                                                                nuxt:typescript 20:26:48
10:15 Cannot find module './logger'.
```

### Additional comments?

fixed in vuex 3.5.1 https://github.com/vuejs/vuex/issues/1790

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10870">#c10870</a>)</em></sub></div>

**Comment by olamedia** [comment]
Also I see vuex@^3.4.0 requirement at vue-app

**Comment by pi0** [comment]
Hi ☺️ Should be fixed with https://github.com/vuejs/vuex/releases/tag/v3.5.1 thanks to @kiaking ❤️

**Comment by kiaking** [comment]
Yap! It's fixed in 3.5.1 👍 Sorry for the confusion 😅

**Comment by olamedia** [comment]
The issue is opened about `@nuxt/vue-app` because of dependency on old version

**Comment by pi0** [comment]
Hi @olamedia. Actually, the dependency constraint is [^3.4.0](https://github.com/nuxt/nuxt.js/blob/v2.13.2/packages/vue-app/package.json#L23) which means any version higher than 3.4.0 and less than 4.0.0 so doing a fresh install or `yarn upgrade nuxt` should bump from `3.5.0` to `3.5.1`.

**Comment by olamedia** [comment]
Hmm... it looks I created project few hours before 3.5.1 release, since the same `yarn create` installs 3.5.1 now
```
$ yarn create nuxt-app nuxt-test2
$ cd nuxt-test2
$ yarn list | grep vuex
│  └─ vuex@^3.4.0
├─ vuex@3.5.1
```
