### ISSUE TITLE
0.10.7 ie11 Promise error

### ISSUE THREAD

**Issue by w550** [nuxt/nuxt.js#764]
```
 vendor: ['vue-lazyload','babel-polyfill', 'axios'],
    babel: {
      'presets': ['es2015', 'stage-0']
    }
```
```
  "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
```
![qq 20170523170833](https://cloud.githubusercontent.com/assets/11831434/26346932/6ecbc44e-3fda-11e7-8fbb-e0c03cde458c.png)

**Comment by pi0** [comment]
Hello @w550, What about adding `babel-polyfill` as first item in the array? 
```js
 vendor: ['babel-polyfill','vue-lazyload', 'axios']
```

**Comment by awronski** [comment]
depends on the ie version you need ```eventsource-polyfill``` too

**Comment by w550** [comment]
@pi0 
babel-polyfill as first item  still errror

**Comment by E-GreeHe** [comment]
@w550  您好，请问你这个兼容问题解决了吗。我也遇见同样的问题。
