### ISSUE TITLE
npm run dev wont work after npm run build && npm run export

### ISSUE THREAD

**Issue by Barbieroalex** [nuxt/nuxt.js#7643]
### Versions

- nuxt:  ex: v2.13.0 
- node:  ex: v14.2.0 

#### Install nuxt with options
? Project name: app
? Programming language: TypeScript
? Package manager: Npm
? UI framework: Tailwind CSS
? Nuxt.js modules: Axios, Content
? Linting tools: ESLint, Prettier, Lint staged files, StyleLint
? Testing framework: Jest
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Static (Static/JAMStack hosting)

### What is Expected?

start a normal npm run dev

### What is actually happening?

<details close>
<summary>Cli Output</summary

 FATAL  Unexpected token 'export'

  export default {
  ^^^^^^

 SyntaxError: Unexpected token 'export'
 at Object.compileFunction (vm.js:344:18)
 at Generator.next (<anonymous>)
 Nuxt Fatal Error
 SyntaxError: Unexpected token 'export' 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
</details>

<details close>
<summary>Logs</summary>
0 info it worked if it ends with ok

1 verbose cli [

1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',

1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',

1 verbose cli   'run',

1 verbose cli   'dev'

1 verbose cli ]

2 info using npm@6.14.4

3 info using node@v14.2.0

4 verbose run-script [ 'predev', 'dev', 'postdev' ]

5 info lifecycle apps@1.0.0~predev: apps@1.0.0

6 info lifecycle apps@1.0.0~dev: apps@1.0.0

7 verbose lifecycle apps@1.0.0~dev: unsafe-perm in lifecycle true

9 verbose lifecycle apps@1.0.0~dev: CWD: C:\js\w2

10 silly lifecycle apps@1.0.0~dev: Args: [ '/d /s /c', 'nuxt' ]

11 silly lifecycle apps@1.0.0~dev: Returned: code: 1  signal: null

12 info lifecycle apps@1.0.0~dev: Failed to exec dev script

13 verbose stack Error: apps@1.0.0 dev: `nuxt`

13 verbose stack Exit status 1

13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)

13 verbose stack     at EventEmitter.emit (events.js:315:20)

13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)

13 verbose stack     at ChildProcess.emit (events.js:315:20)

13 verbose stack     at maybeClose (internal/child_process.js:1051:16)

13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

14 verbose pkgid apps@1.0.0

15 verbose cwd C:\js\w2

16 verbose Windows_NT 10.0.18362

17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"

18 verbose node v14.2.0

19 verbose npm  v6.14.4

20 error code ELIFECYCLE

21 error errno 1

22 error apps@1.0.0 dev: `nuxt`

22 error Exit status 1

23 error Failed at the apps@1.0.0 dev script.

23 error This is probably not a problem with npm. There is likely additional logging output above.

24 verbose exit [ 1, true ]

</details>

**Comment by mceachen** [comment]
FWIW, running `yarn nuxt-ts dev .` is a workaround.

**Comment by Barbieroalex** [comment]
> FWIW, running `yarn nuxt-ts dev .` is a workaround.

Great, tvm! it works perfectly 🤍
