### ISSUE TITLE
Error page custom layout not being always respected and loaded.

### ISSUE THREAD

**Issue by axeldomingues** [nuxt/nuxt.js#7658]
### Versions

- nuxt: 2.13.2 
- node: 10.16.0 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

https://codesandbox.io/s/nuxt-error-layout-not-change-7z60q?file=/pages/index.vue
</details>

### Steps to reproduce

https://codesandbox.io/s/nuxt-error-layout-not-change-7z60q?file=/pages/index.vue

You can use the sandbox above and you will quickly understand and reproduce the issue even setting the lastest version of nuxt. You will be able to reproduce the case where the error page custom layout is not respected.

### What is Expected?

As mentioned in the documentation and as in previous versions we should be able to set a custom layout for the error page.

### What is actually happening?

Unfortunately, this has stopped working in the last version and it seems that it was not working on version 2.12.0 too.

**Comment by Atinux** [comment]
We released 2.13.3 that should fix your issue. Please try again and confirm that it's fixed please.

**Comment by barfi** [comment]
Nuxt v. 2.13.3 same issue. Error page with custom layout option works only for requests where error handled on the server side. After that all is fine, client routing works as expected. In other cases error page uses default layout =\

**Comment by axeldomingues** [comment]
Yes, I can confirm what @barfi said is the reality. It is not working as expected even in  2.13.3.

**Comment by Feaman** [comment]
Spent many hours on this. As I could undestand, if an error occures outside the default layout (for example, 404 error), so there is no current page to use some layout, then error page uses it's own layout (set in the error component `layout: 'blog'`). But when an error rises from the some defined page (with default layout), then error page uses this default layout, not it's own one.

**Comment by bmkubia** [comment]
I am having a similar issue where I will trigger the error page by any means and then any route navigated to after that has its layout overridden by the error pages current set layout. Not sure if 100% related though.

For example:

- error "layout" uses a layout called "layoutforerrors"
- home page uses a layout called "home"
- go to home page -> error page -> home page
- home page will then still be using "layoutforerrors" and the layout will not switch back

**Comment by Kolobok12309** [comment]
+1 for this issue

**Comment by pi0** [comment]
Should be resolved with [v2.14.5](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.5)
