### ISSUE TITLE
Customize naming of window.__NUXT variables

### ISSUE THREAD

**Issue by Zekfad** [nuxt/nuxt.js#7661]
### Is your feature request related to a problem? Please describe.

Allow to change naming of `__NUXT_JSONP__`, `__NUXT_JSONP_CACHE__`, `__NUXT_IMPORT__`, `__NUXT_STATIC__` used by full static generation, because they are hardcoded and makes it hard to embed two nuxt application into one page.

### Describe the solution you'd like

Add option into [globals](https://nuxtjs.org/api/configuration-global-name), e.g. `jsonpHandler`, `jsonpCache`, `jsonpImport`, `static`.

### Additional context

It would be awesome to make nuxt application exposed variables customizable, so it could potentially run multiple instances within single page.
Related parts:
https://github.com/nuxt/nuxt.js/blob/9aff6ef6dbefd81733f808bba90e9d22be699694/packages/vue-app/template/App.js#L308-L309
https://github.com/nuxt/nuxt.js/blob/9aff6ef6dbefd81733f808bba90e9d22be699694/packages/vue-app/template/jsonp.js#L78-L80
https://github.com/nuxt/nuxt.js/blob/9aff6ef6dbefd81733f808bba90e9d22be699694/packages/vue-renderer/src/renderers/spa.js#L154-L155
https://github.com/nuxt/nuxt.js/blob/9aff6ef6dbefd81733f808bba90e9d22be699694/packages/vue-renderer/src/renderers/ssr.js#L169
https://github.com/nuxt/nuxt.js/blob/9aff6ef6dbefd81733f808bba90e9d22be699694/packages/vue-renderer/src/renderers/ssr.js#L188

**Comment by Zekfad** [comment]
That was a little ago, as far as I can remember I was about to make a unite main site, and in private area mount admin panel into protected page, so no private client js code would be accessible from public.

**Comment by danielroe** [comment]
Great - understood. We are planning to make multi app possible - see https://github.com/nuxt/rfcs/issues/30

I'll close this issue in favour of that 👍

**Comment by Zekfad** [comment]
Sure, if this is related enough, as this issue (variables) are also addresses technology hiding, meant obfuscation and so on.
