### ISSUE TITLE
NuxtLink isActive slot with dynamic class

### ISSUE THREAD

**Issue by Larsklopstra** [nuxt/nuxt.js#7662]
### Versions

- nuxt: v2.13.0
- node: v12.5.0
- nuxt-composition-api: 0.10.3

### Reproduction

```
<template>
    <li>                                                 <!-- Property or method "isActive" is not defined -->
        <NuxtLink v-slot="{ isActive }" :class="[baseClasses, isActive ? activeClasses : inactiveClasses]" :to="to">
            <slot></slot>
            {{ isActive }} <!-- shows true/false -->
        </NuxtLink>
    </li>
</template>
```

### Steps to reproduce

Decontruct `isActive` from the `nuxt-link` component and use it within the `:class` binding.

### What is Expected?

`isActive` should either return `true` or `false` and render the classes.

### What is actually happening?

The app is crashing because of `Property or method "isActive" is not defined` but when I print `isActive` it'll show `true` or `false` correctly.

**Comment by posva** [comment]
This is expected behavior in Vue. Remember it's the same as doing:

```vue
<NuxtLink :class="[baseClasses, isActive ? activeClasses : inactiveClasses]" :to="to">
  <template  v-slot="{ isActive }">
            <slot></slot>
            {{ isActive }} <!-- shows true/false -->
  </template>
        </NuxtLink>
```

Which should help you understand why `isActive` is not defined 🙂 
You need to pass the `class` attribute inside (https://router.vuejs.org/api/#v-slot-api-3-1-0)

**Comment by Larsklopstra** [comment]
Ah, I see. Would it be possible to make a feature request for an `inactive` attribute?

**Comment by posva** [comment]
Search that exact term on the issues 😉
