### ISSUE TITLE
Status Code - 404

### ISSUE THREAD

**Issue by axelerod12** [nuxt/nuxt.js#7663]
**Version** 
2.13.2

**Reproduction link**
localhost:3000/a-url-that-doesnt-exist

The application is fully static with these settings in nuxt.config.js
```
ssr: true,
target: 'static',
generate: {
     fallback: '404.html',
}
```

The nuxt-error template is rendered but the status code for the document is not correct. It returns a 200 as status code.

Using Nginx and the configuration was taken from here: https://nuxtjs.org/faq/nginx-proxy/

**What is expected?**
The page should return a 404 as a status code.

**What is actually happening?**
It returns a 200 as status code.

**Comment by amerkay** [comment]
I'm having the same issue with v2.14.4. `fallback: '404.html'` in `generate` full static mode return code 200. I guess that's true for 200.html, but looks like a bug for the 404.html template. Any workarounds?

**Comment by danielroe** [comment]
As I read it, it looks like this is about how to configure nginx and Apache (though it possibly should be included in the deployment guide).

For nginx you might want to add something like:
```
error_page 404 /404.html;
```

Apache uses this syntax:
```
ErrorDocument 404 /404.html
```

More info can be found by consulting the documentation of your web server.

**Comment by amerkay** [comment]
I did that. Instead of nginx, setup 404 on Cloudfront. My problem is with my _slug. Once the /404 route is loaded, the _slug.vue kicks in and errors out. @Atinux is helping out with it. Will post possible `middleware` solution when we figure it out.
