### ISSUE TITLE
output of nuxt export is not reproducible

### ISSUE THREAD

**Issue by tamalsaha** [nuxt/nuxt.js#7664]
### Versions

- nuxt: v2.12.1
- node: v10.19.0

### Reproduction

https://github.com/tamalsaha/nuxt-static/commit/19b284c9f5f43dfe15afb3b2e357119f2f650bce

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
npm run export

### What is Expected?
I did not make any change to any file. I expected the dist folder to not change.

### What is actually happening?
The payload.js file changes location every time I run `npm run export`. See here: https://github.com/tamalsaha/nuxt-static/commit/19b284c9f5f43dfe15afb3b2e357119f2f650bce

**Comment by farnabaz** [comment]
Nuxt generate random version for each static generation and this cause changes in `dist` directory. You can provide custom version to static assets to prevent dynamic version generation.
Provide `staticAssets` in `nuxt.config.js`

```js
...
  generate: {
    staticAssets: {
      version: 'cutom-version',
    }
  }
...
```

**Comment by tamalsaha** [comment]
Thanks, @farnabaz ! Is there a way to tell nuxt to generate this version based on content?

**Comment by farnabaz** [comment]
For now there isn't any way to change version based on content, but you can use project version, and use auto versioning tools.

```js
const pkg = require('package.json')

export default {
  generate: {
    staticAssets: {
      version: pkg.version,
    }
  }
}
```
