### ISSUE TITLE
SSR not working on export.exclude routes

### ISSUE THREAD

**Issue by ballonura** [nuxt/nuxt.js#7669]
### Versions
- nuxt:  v2.13.3
- node: v12.14.0

<details open>
<summary>Additional Details</summary>
I am missing something about export.fallback ?

nuxt.config.js:
```
mode: 'universal',
target: 'static',
export: {
    exclude: [
      /^\/admin/, // path starts with /admin
    ],
}
```

index route return : `<html data-n-head-ssr>`
/admin route return : `<html>`

[dist folder](https://ibb.co/p3K5R9D)
</details>

### What is Expected?
www.website.com/admin will serve fully html content (SSR not SSG because route excluded from be pre-generated)

### What is actually happening?
looks like www.website.com/admin serve SPA version of the file:
```
<div id="nuxt-loading" aria-live="polite" role="status">
    <div>Loading...</div>
</div>
```

**Comment by ballonura** [comment]
Please?

**Comment by danielroe** [comment]
@ballonura How are you serving your website? If you are just serving the dist folder, then there is no server to respond with a fully rendered admin page.

**Comment by ballonura** [comment]
Serving the dist folder. thx.

**Comment by danielroe** [comment]
@ballonura Because you are serving static html, there is no server to render a response for that route.

**Comment by ballonura** [comment]
So i need to config node.js (express) server to render and serve those routes.
