### ISSUE TITLE
1.0.0-alpha1: Vue chrome development tools not available

### ISSUE THREAD

**Issue by hookszhang** [nuxt/nuxt.js#767]
I have to upgrade to the nuxt 1.0.0-alpha1 release. When i ready develop, i found that cannot be found in the vue development tools vuex data. All vuex data is empty, but my project works.

**Comment by Atinux** [comment]
It works fine on my end, but try tro refresh the page while the dev tools is open.

**Comment by hookszhang** [comment]
I'm sure all vuex data is empty

macOS Sierra 10.12.4
Chrome 58.0.3029.110 (64-bit)
Vue.js devtools 3.1.2

**Comment by cafe4it** [comment]
Me too!
Xubuntu 16.10
Chrome Version 59.0.3071.109 (Official Build) (64-bit) 
Vue-devtools 3.1.6

**Comment by hookszhang** [comment]
@cafe4it Because i error code logic: repeat create vue store.

I want get vue store instance in `~plugins/axios.js` and used wrong code.
Delete bellow code in my project is works fine
```
import { createStore } from '~store'
const VueStore = createStore()
``` 

The correct code:
```
export default ({ store }) => {
  // store is vue store, injected by nuxt
}
```

You whether there is the same problem with me？
