### ISSUE TITLE
WARN  Module @nuxtjs/stylelint-module not found. Please ensure @nuxtjs/stylelint-module is in devDependencies and installed. HINT: During build step, for npm/yarn, NODE_ENV=production or --production should NOT be used.

### ISSUE THREAD

**Issue by Hulkmaster** [nuxt/nuxt.js#7675]
### Versions

- nuxt: v2.13.1
- node: v12.14.0

### Reproduction

any nuxt cli project with @nuxtjs/stylelint-module

### Steps to reproduce

`npm ci`
`npm run build`
build docker image
`rm -rf node_modules`
`npm ci --only=production`
`npm run start`

### What is Expected?

everything should run perfectly fine

### What is actually happening?

An error.

### Comment

So thats what we do: we build nuxt, then remove node_modules and install only runtime dependencies (in order to lower image size)

And i think error message should be at least corrected
Its still possible to install runtime modules in runtime deps (`dependencies`), and leave build-time deps in `devDependencies`

So i would suggest intead of prohibiting people from installing in `production` mode, just suggest to add to `dependencies`

```
WARN  Module @nuxtjs/stylelint-module not found. @nuxtjs/stylelint-module is a runtime dependency, please ensure @nuxtjs/stylelint-module is in dependencies and installed.
```

**Comment by Hulkmaster** [comment]
can still reproduce

**Comment by danielroe** [comment]
@Hulkmaster So am I right to understand that you have the module installed in your dependencies even though it is a build time only module? If so, could you explain your use case for that?

**Comment by Hulkmaster** [comment]
so our case is actually already explained in my initial message :)

not sure if its not clear, or you want me to add something to it?

**Comment by danielroe** [comment]
@Hulkmaster It's not clear. If you could share the relevant portions of your nuxt config and package json, that would help.

**Comment by Hulkmaster** [comment]
error happens in runtime

okay, then i'll try to explain again

so we have nuxt application in docker container
during docker image build we build nuxt application `npm run build`
so at that point we expect all build dependencies to be already inside server/client bundle
so we remove node_modules inside image (so we will not have any unnecessary packages, and later)
then we install only runtime dependencies
after that we have docker image built with only runtime dependencies

than, after that, during `docker run` we expect that everything would work, because build-time deps were during build time, and we left only runtime dependencies inside the image
so it should run perfectly fine


but then during runtime we receive an error, which i wrote above

**Comment by danielroe** [comment]
@Hulkmaster understood - that's very helpful. Can you tell me whether the Nuxt stylelint module is in your devDependencies or in your dependencies?

**Comment by Hulkmaster** [comment]
it was it devDeps

basically you can try the same thing with nuxt cli and wrap it into docker

you should have same warning

**Comment by Hulkmaster** [comment]
okay, now when i actually thought about it - you don't need docker to test it :D

**Comment by Hulkmaster** [comment]
Still reproducable

**Comment by danielroe** [comment]
@Hulkmaster Could you provide a reproduction?

**Comment by pi0** [comment]
@Hulkmaster Docker flow seems fine to remove devDependencies from final image. But you should add `@nuxtjs/stylelint-module` to `buildModules` not `modules` in `nuxt.config`.  If still think it is wrong behavior, please open new issue providing also `nuxt.config` and `Dockerfile`.

**Comment by Hulkmaster** [comment]
yeah, seems to be working, thanks!
