### ISSUE TITLE
Nuxt + Lambda universal : How optimized first loading

### ISSUE THREAD

**Issue by MSkred** [nuxt/nuxt.js#7676]
<img width="1440" alt="Capture d’écran 2020-07-06 à 16 36 35" src="https://user-images.githubusercontent.com/17643602/86605332-dd824580-bfa6-11ea-9744-266abd1ae79c.png">

How can I reduce this time … 14.35 seconds

**Comment by xerosanyam** [comment]
By Lamda Universal, you mean AWS Lambda?
If yes, I am sure there isn't much nuxt community could do
Because serverless functions are not optimized for serving HTML pages

Why?
- they suffer from cold-start (probably the biggest chunk of that 14.35s)
- browsers have trouble caching stuff received from lambda (in comparison to ec2/appengine)

**Comment by xerosanyam** [comment]
To find an alternative to lambda, you can choose one from the following:
![image](https://user-images.githubusercontent.com/3167278/86718401-aeb8ad80-c040-11ea-8b48-9d12b1b98175.png)

https://nuxtjs.org/faq/appengine-deployment

**Comment by MSkred** [comment]
@xerosanyam Hi, thank you for your reply. I tested the Google application solution and after deployment, I see a slight improvement, but as you can see that the first loading is still as long

**Google app first load**
![Capture d’écran 2020-07-10 à 09 17 42](https://user-images.githubusercontent.com/17643602/87127695-9d64e080-c28e-11ea-974c-8deb04936e8d.png)
_**Google app page reload = 2800ms**_



**Lambda first load**
![Capture d’écran 2020-07-10 à 09 17 47](https://user-images.githubusercontent.com/17643602/87127720-ab1a6600-c28e-11ea-8fd3-e50edf5aac7b.png)
_**Lambda page reload = 4550ms**_

**Comment by xerosanyam** [comment]
hi, 2800ms in comparison with 4550ms is a great improvement! you cut load time by ~50%. this is great, congratulations 🎉 

The performance of a web app depends on a number of factors, as you might be aware of... Number of external libraries, caching, etc

you could test your links on https://www.webpagetest.org/ & compare results
this would also give you insight on where you could improve next.
