### ISSUE TITLE
Full Static not generating dynamic route if linked from a component in the layout

### ISSUE THREAD

**Issue by cfofiu** [nuxt/nuxt.js#7677]
### Versions

- nuxt: v2.13.0
- node: v12.18.1

### Reproduction

```
<template>
	<div>
		<Navigation />
		<nuxt />
		<Footer />
	</div>
</template>

<script>
import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'

export default {
	components: { Navigation, Footer }
}
</script>
```

### Steps to reproduce
Add a navigation component to layout. Link to a page that is using a dynamic route to generate. For example `/mvp` using a dynamic route page `_pageUID.vue`.

### What is Expected?
Generate `/mvp` folder along with the other static routes.

### What is actually happening?
On `nuxt build && nuxt export` the `/mvp` folder does not get generated. If I add the link anywhere else on another page (not a component that is used only in the Navigation) the `/mvp` folder does actually get generated.

**Comment by farnabaz** [comment]
Nuxt has no problem in finding links in subcomponents. I just tested this to make sure of it.  
Could you provide a reproduction sample on codesandbox?
Also what is content of `Navigation` component?
