### ISSUE TITLE
Prevent Recompiling entire system when making changes to Express Routes

### ISSUE THREAD

**Issue by JordashTalon** [nuxt/nuxt.js#7680]
I created the Nuxt app with ExpressJS as the backend, it works great, however everytime I make a change to server/index.js it recompiles the entire system usually taking 5-7seconds, this really hurts the workflow as a typical express app with Nodemon takes less than 500milliseconds.

Is there a way to only restart the server and not recompile if you are working on any files in the server directory?

I've been trying to work with waiting 5-7 seconds between saves in the server directory but it adds a lot of unnecessary development time and headache.  Also tried setting up a separate Express app but then I need 2 servers which creates unnecessary extra complexity and setup issues.

![fzA03](https://user-images.githubusercontent.com/957100/86806660-4ebd0980-c036-11ea-9054-e2e7d66b89d7.png)

**Comment by JordashTalon** [comment]
I found a solution for this that I documented here:

https://stackoverflow.com/questions/62452822/in-nuxt-w-express-how-to-prevent-re-compilation-when-saving-server/62943879#62943879

Hopefully there is a better way, but in the meantime that is my approach.

**Comment by pi0** [comment]
(something coming soon 👀)
