### ISSUE TITLE
关于client页面通过浏览器返回到ssr页面  asyncData 不执行  

### ISSUE THREAD

**Issue by hj009** [nuxt/nuxt.js#7682]
问题描述：
       使用nuxt运行一个首页需要ssr的项目，asyncData中提前获取到首页需要渲染的数据。通过浏览器前进或后退按键返回到首页的时候，报错了，首页需要渲染的数据没拿到。是因为asyncData没执行吗？  有没有办法解决

**Comment by burning-papaya** [comment]
Are you fetching data through axios? If yes do you use it in `proxy` mode? I have the same problem when trying to fetch data in server-side hooks like `fetch()`, `created()` and `asyncData()`. Getting `connect ECONNREFUSED 127.0.0.1:80`.

There is already an issue [issue] but it is closed (https://github.com/nuxt/nuxt.js/issues/1832)

**Comment by hj009** [comment]
get it
