### ISSUE TITLE
nuxt 引ant-design-vue后  国际化配置的问题

### ISSUE THREAD

**Issue by hj009** [nuxt/nuxt.js#7684]
问题描述：
    VUE-CLI中 ant-design-vue 配置中文 是在App.vue中（如下）。nuxt引了ant-design-vue ，没有App.vue入口了，该在哪做配置？
<template>
  <a-locale-provider :locale="zh_CN">
    <App />
  </a-locale-provider>
</template>
<script>
  import zh_CN from 'ant-design-vue/lib/locale-provider/zh_CN';
  import moment from 'moment';
  import 'moment/locale/zh-cn';

  moment.locale('zh-cn');
  export default {
    data() {
      return {
        zh_CN,
      };
    },
  };
</script>

**Comment by shinjidotme** [comment]
layouts/default.vue

**Comment by ihavecoke** [comment]
you can create plugin 'antd.js' then use `ant-design-vue` like this

```javascript
import Vue from 'vue'
import Antd, { message } from 'ant-design-vue'
Vue.use(Antd)

export default ({ app }, inject) => {
  inject('message', message)
}
```

**Comment by wuyouhuaz** [comment]
layotus/default.vue文件下
<template>
    <a-config-provider :locale="locale">
        <div>
            <a-row>
                <a-col :span="24">
                    <ul>
                        <li>
                            <NuxtLink to="/">{{ $t('home.title') }}</NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/about">{{ $t('about.title') }}</NuxtLink>
                        </li>
                    </ul>
                    <button v-if="$i18n.local != 'zh'" @click="changeLang('zhCN')">中文</button>
                    <button v-if="$i18n.local != 'en'" @click="changeLang('enUS')">英文</button>
                </a-col>
            </a-row>
            <div>
                <a-pagination :default-current="1" :total="50" show-size-changer />
                <Nuxt />
            </div>
        </div>
    </a-config-provider>
</template>
<script>
import zhCN from 'ant-design-vue/es/locale/zh_CN'
import enUS from 'ant-design-vue/es/locale/en_US'

export default {
    data() {
        return {
            locale: zhCN,
            zhCN,
            enUS
        }
    },
    methods: {
        changeLang(lang) {
             this.locale = this.$i18n.locale = lang
            // 此时语言就会显示为切换的语言
        }
    }
}
</script>
