### ISSUE TITLE
Mounted Trigger 2 times

### ISSUE THREAD

**Issue by ademyalcin27** [nuxt/nuxt.js#7685]
### Versions

- nuxt: v2.9.2
- node: v12.14.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Hi, 
I have really interesting problem with nuxt render.  When we add CookiePolicy  to Layout. Our views's mounted hook trigger 2 times and same layout. 

```
//Mobile Layout
<template>
  <div>
    <Covid class="covid--mobile" />
    <Header />
    <nuxt />
    <Footer />
    <CookiePolicy />
  </div>
</template>

<script>
import Header from '@/mobile/components/Common/Header.vue';
import Footer from '@/mobile/components/Common/Footer.vue';

export default {
  components: {
    Header,
    Footer,
    Covid: () => import('@/components/Common/Covid.vue'),
    CookiePolicy: () => import('@/components/Common/CookiePolicy.vue'),
  },
};
</script>
```

```
CookiePolicy.vue Component
<template>
  <div v-if="active" class="cookie-policy">
    
   ....
  </div>
</template>

<script>
import cookies from 'js-cookie';

export default {
  data() {
    return {
      active: false,
      cookieName: 'cookie_policy',
      cookieExpires: 30,
    };
  },
  mounted() {
    if (!cookies.get(this.cookieName)) {
      this.active = true;
    }

    this.setCookie();
  },
  methods: {
    setCookie() {
      cookies.set(this.cookieName, true, { expires: this.cookieExpires });
    },
  },
};
</script>
```

### What is actually happening?

**// Mobile Home view Mounted**

![86769612-13cbcd80-c058-11ea-97a9-449013b5ffbb](https://user-images.githubusercontent.com/5026172/86947197-20cde700-c154-11ea-8d3e-0600f22bc38d.png)

**Comment by crutch12** [comment]
I'm not sure that problem is this, but:
You can't use v-if directive on root tag of template section
```
<template>
  <div v-if="active" class="cookie-policy">
  </div>
</template>
```
Use wrapper div tag or add tag with v-else directive

**Comment by crutch12** [comment]
https://vuejs.org/v2/guide/components.html#A-Single-Root-Element

**Comment by ademyalcin27** [comment]
> I'm not sure that problem is this, but:
> You can't use v-if directive on root tag of template section
> 
> ```
> <template>
>   <div v-if="active" class="cookie-policy">
>   </div>
> </template>
> ```
> 
> Use wrapper div tag or add tag with v-else directive

If you right then Why I can't get error on the desktop layout. There is the same thing in Layout. It's more interesting

**Comment by crutch12** [comment]
Need reproduction link

**Comment by ademyalcin27** [comment]
> reproduction

I cant share but I can add one more thing. there is setCookie method we call in mounted. So if we remove this in mounted everything working very well.

**Comment by crutch12** [comment]
You won't resolve your issue this way. Try to reproduce it in a clean environment and share here.

**Comment by ademyalcin27** [comment]
> You won't resolve your issue this way. Try to reproduce it in a clean environment and share here.

Hi I have  discovery about this issue, If I import CookiePolicy like that there isnt problem. But Its coming some question with this; 

 ```    
  import CookiePolicy from @/components/Common/CookiePolicy.vue';
 ```

1- Why it's working well on desktop layout? 
2- Why it's working  Covid component  both side(desktop and mobile layout)?
