### ISSUE TITLE
HMR for the style nestedly imported 

### ISSUE THREAD

**Issue by jsnick** [nuxt/nuxt.js#769]
Is there any way to watch nestedly imported files ? 

For example,
I have `styles/` for custom global mixin and css.

1. common-mixin.css 
```
@import 'styles/mixin/color';
@import 'styles/mixin/media';
..
..
```

2. global-class.css (this css is injected to `css` in nuxt.config.js )
```
@import 'styles/global/container';
@import 'styles/global/button';
..
..
```

If I change a imported file in common-mixin.css or global-class.css (e.g. styles/global/button.css or styles/mixin/color.css), HMR do not work even I refresh the page! 
It finally works when I restart the server.

How can I apply it without restarting server or refreshing the page ?
Should I change the way to import `stylesheet` ? (flatten import style..)

For reference, I use postcss, postcss-import (which has path options), postcss-cssnext.

**Comment by alexchopin** [comment]
Hi, 
Have you tried to import `global-class.css` in your `layouts/default.vue` file?

**Comment by KonstantinVlasov** [comment]
Hi, @jsnick, I faced with the same problem. You have to import your styles like mention above, then styles will be watched.

**Comment by jsnick** [comment]
Thank you for answering.

I don't know why,
But..!
It works after I upgrade nuxt to 1.0.0-alpha version.
