### ISSUE TITLE
Help wanted: incompatibility with modal component – vue-js-modal

### ISSUE THREAD

**Issue by hmaesta** [nuxt/nuxt.js#7690]
[vue-js-modal](https://github.com/euvl/vue-js-modal/) is the **most popular** modal package for Vue – with **3,400+ stars** and used by **5,000+ projects.**

It works great on Vue, but we can't solve a problem with the SSR version. 
Unfortunately **no contributor has experience with Nuxt.** 

Can some one give a little help? 🥺
→ **https://github.com/euvl/vue-js-modal/issues/561**

---

_I know it's not the best 'feature request' issue, but modal windows are heavily popular and this is the best place to ask for help. I am sorry if this is inappropriate._

**Comment by pi0** [comment]
Hi @hmaesta. This feature should be implement by compoents itself. I've subscribed to issue but please use discord for ping or asking questions (link on website)
