### ISSUE TITLE
start development server error Cannot find module 'consola'

### ISSUE THREAD

**Issue by faysal146** [nuxt/nuxt.js#7694]
when I start the server with "yarn dev" it will give me this error 
note I'm using typescript also.

![nuxt-ts-error](https://user-images.githubusercontent.com/47469289/87122875-854d8b00-c2a7-11ea-925b-11f54e4598a3.png)

**Comment by pi0** [comment]
Hi @faysal146 Please properly fill [issue template](https://github.com/nuxt/nuxt.js/issues/new?assignees=&labels=bug-report&template=bug-report.md&title) use use [discord](https://discord.nuxtjs.org/) to ask questions.

Issue seems local. Cleaning `node_modules` and `yarn.lock` may help.
