### ISSUE TITLE
nuxt-telemetry make nuxt start blocked

### ISSUE THREAD

**Issue by chuoke** [nuxt/nuxt.js#7695]
### Versions

- nuxt: v2.13.2

### Steps to reproduce
 I deploy nuxt with docker. 
A few days ago, I upgrade nuxt.js. Everything is ok as usual. The container is upped successfully, but I can't visit the site, only got 502. At the moment, I'm very confused.  I found the nuxt isn't started.
 What I see in the command line is just like this:
```bash
yarn run v1.22.4
$ nuxt start
``` 
It's in that state all the time.

 By comparison in local without docker, I realized that reason is the `nuxt-telemetry`:
```bash 
ℹ NuxtJS collects completely anonymous data about usage.                                                                                                                                                                               09:10:29
  This will help us improving Nuxt developer experience over the time.
  Read more on https://git.io/nuxt-telemetry

? Are you interested in participation? 
```
I can't respond to it in docker. So it Has been waiting.

This way is really too should not. it is strange and weird. 

### What is Expected?
I found can jump over it by config `telemetry: false`. But I hope the operation like it should be skipped in production.  

### What is actually happening? 

nuxt-telemetry make nuxt start blocked

**Comment by pi0** [comment]
Hi @chuoke thanks for the report. Should be fixed with [1.2.2](https://github.com/nuxt/telemetry/releases/tag/v1.2.2) using [is-docker](https://github.com/sindresorhus/is-docker).

You can get the patch using `yarn upgrade nuxt`
