### ISSUE TITLE
Import custom (UI) component from node_modules on pages

### ISSUE THREAD

**Issue by vivian-nigri** [nuxt/nuxt.js#7699]
I have a private NPM library that I need to access on and tags. How can I import those components from node_modules on my pages directly?

Example: 
```javascript
// custom scoped package
import MyPackage from '@my/package';
```

I am getting error "Module not found @my/package...".

**Comment by imaxsof** [comment]
Use `import MyPackage from '~~/node_modules/@my/package'`

**Comment by aldarund** [comment]
import MyPackage from '@my/package';

should work as it is. something wrong with your package/modules

**Comment by vivian-nigri** [comment]
Hi to all!

Thanks for the replies, but I manager to find the solution.

I added my module to the build transpile array on nuxt.config

```javascript
build: {
    transpile: ['@my'],
    extend(config, { isDev, isClient }) {
      if (isClient && isDev) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        });
        config.resolve.symlinks = false; 
      }
    },
  },
```

**Comment by aldarund** [comment]
Ah, if u want to use not process yes, you need to use transpile. It wasn't clear from question
https://nuxtjs.org/api/configuration-build/#transpile
