### ISSUE TITLE
Allow redirect to absolute URL

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt.js#770]
Feature request: Allow redirects to absolute URLs, SSR and client-side.

We have an app (https://domainr.com) with several legacy URLs, some of which redirect to other websites. We’re exploring using Nuxt/Vue for our new website and would like to preserve this behavior.

## Snippet to reproduce

`~/pages/_domain/iana.vue`

```javascript
<script>
export default {
  fetch ({ params, redirect }) {
    redirect(301, `https://www.iana.org/domains/root/db/${params.domain}.html`)
  }
}
</script>
```

## Steps to reproduce

Navigate to `/com/iana`

## Expected

Redirect to `https://www.iana.org/domains/root/db/com.html`

(Click here to see expected behavior: https://domainr.com/com/iana)

## What actually happens

Redirect to `/https:/www.iana.org/domains/root/db/com.html` (local URL)

## Background

Nuxt only allows local redirects to a path, which is prepended with `router.base` here: https://github.com/nuxt/nuxt.js/blob/dev/lib/app/server.js#L39

**Comment by ydnar** [comment]
I was able to hack a workaround using middleware, but it throws errors on the client and server side. It throws errors and adds an HTML5 history entry for the redirect. Is there a way to stop processing the request process in middleware, hook into vue-router at a lower-level, or use normal [vue-router redirects](https://router.vuejs.org/en/essentials/redirect-and-alias.html)?

https://gist.github.com/ydnar/afd2fdfa90f9579a8188f0bfe418493d

**Comment by ydnar** [comment]
Refined the hack (workaround?) a bit. It now works on server and client side, redirecting to an absolute URL. It overrides the `Location` header and sets the HTTP response code by [ab]using the `error` function: `error({ statusCode: 301, ... })`.

```js
function fixRedirect (ctx) {
  const _redirect = ctx.redirect
  ctx.redirect = function (status, path, query) {
    // If only 1 or 2 arguments: redirect('/') or redirect('/', { foo: 'bar' })
    if (typeof status === 'string' && (typeof path === 'undefined' || typeof path === 'object')) {
      query = path || {}
      path = status
      status = 302
    }
    path = addQuery(path, query)
    if (!isAbsolute(path)) {
      _redirect(status, path)
    } else if (ctx.isServer && ctx.res) {
      ctx.res.setHeader('Location', path)
      ctx.error({ statusCode: status, message: `Redirecting to ${path}` })
    } else if (ctx.isClient && window && window.location) {
      window.location = path
      ctx.error({ statusCode: status, message: `Redirecting to ${path}` })
    }
  }
}
```

**Comment by Atinux** [comment]
I'm adding it for Nuxt 1.0 @ydnar :)

**Comment by ronenteva** [comment]
Estimation when will it be released?

**Comment by ydnar** [comment]
Thanks for fixing!

I found a bug in the 1.x.x implementation: the client-side redirect adds an additional history item. Our internal workaround uses `window.location.replace(path)` instead of `window.location = path`.

Should I file a new bug?

**Comment by harryhazza77** [comment]
seems to happen to me too.

**Comment by MRZMUH001** [comment]
Any ETA on this bug fix?
