### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by Dinath** [nuxt/nuxt.js#7700]
### Versions

- nuxt: 2.13.3
- node: v8.10.0

### Reproduction

https://fr.nuxtjs.org/guide/installation

Simply follow the installation guide.

* mkdir project
* npm install --save nuxt

When running `npm run dev` or `nuxt` command, it returns `SyntaxError: Unexpected token {`.

![unexpected-token](https://user-images.githubusercontent.com/8973343/87203189-5b758200-c302-11ea-8a51-a6a82d003628.png)

### Logs

<pre>
$ npm install --save nuxt
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> core-js@2.6.11 postinstall /home/alex/projects/front-cycling-stats/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> ejs@2.7.4 postinstall /home/alex/projects/front-cycling-stats/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> nuxt@2.13.3 postinstall /home/alex/projects/front-cycling-stats/node_modules/nuxt
> opencollective || exit 0

                                                                         
                                                 :-:                     
                                               .==-+:                    
                                              .==. :+- .-=-              
                                             .==.   :==++-+=.            
                                            :==.     -**: :+=.           
                                           :+-      :*+++. .++.          
                                          :+-      -*= .++: .=+.         
                                         -+:      =*-   .+*: .=+:        
                                        -+:     .=*-     .=*-  =+:       
                                      .==:     .+*:        -*-  -+-      
                                     .=+:.....:+*-.........:=*=..=*-     
                                     .-=------=++============++====:     
                                                     
                                     Thanks for installing nuxtjs 🙏
                             Please consider donating to our open collective
                                    to help us maintain this package.
                                                     
                                       Number of contributors: 229
                                          Number of backers: 339
                                        Annual budget: 68 539 $US
                                       Current balance: 25 768 $US
                                                     
                       👉  Donate: https://opencollective.com/nuxtjs/donate
</pre>

#### NPM logs

<pre>
$ cat /home/alex/.npm/_logs/2020-07-11T07_54_22_811Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.6
3 info using node@v8.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle front-cycling-stats@1.0.0~predev: front-cycling-stats@1.0.0
6 info lifecycle front-cycling-stats@1.0.0~dev: front-cycling-stats@1.0.0
7 verbose lifecycle front-cycling-stats@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle front-cycling-stats@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/alex/projects/front-cycling-stats/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
9 verbose lifecycle front-cycling-stats@1.0.0~dev: CWD: /home/alex/projects/front-cycling-stats
10 silly lifecycle front-cycling-stats@1.0.0~dev: Args: [ '-c', 'nuxt' ]
11 silly lifecycle front-cycling-stats@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle front-cycling-stats@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: front-cycling-stats@1.0.0 dev: `nuxt`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid front-cycling-stats@1.0.0
15 verbose cwd /home/alex/projects/front-cycling-stats
16 verbose Linux 5.3.0-62-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v8.10.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error front-cycling-stats@1.0.0 dev: `nuxt`
22 error Exit status 1
23 error Failed at the front-cycling-stats@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
</pre>

Merci :)

**Comment by Dinath** [comment]
Upgrading to node v12 solved the issue.

I did not find any "requirement page" with minimal versions needed on nuxtjs' website.

We might need it :)

**Comment by mornir** [comment]
Hey!
The Node.js 8.x Maintenance LTS cycle expired on December 31, 2019 . I think it's reasonable to not expect the latest Nuxt version to work on unmaintained Node releases.

**Comment by mornir** [comment]
But you're right that a better error message could be displayed in the terminal. Something like "Your current Node version is not supported. Please upgrade". I wonder if this could be specified in package.json.

**Comment by Dinath** [comment]
> Hey!
> The Node.js 8.x Maintenance LTS cycle expired on December 31, 2019 . I think it's reasonable to not expect the latest Nuxt version to work on unmaintained Node releases.

I think too!

But to be honest I was not thinking I was using outdated Node version since this is the latest one for Ubuntu 18.04: https://packages.ubuntu.com/bionic/nodejs.

A message would be nice :)

**Comment by manniL** [comment]
> 
> 
> > Hey!
> > The Node.js 8.x Maintenance LTS cycle expired on December 31, 2019 . I think it's reasonable to not expect the latest Nuxt version to work on unmaintained Node releases.
> 
> I think too!
> 
> But to be honest I was not thinking I was using outdated Node version since this is the latest one for Ubuntu 18.04: [packages.ubuntu.com/bionic/nodejs](https://packages.ubuntu.com/bionic/nodejs).
> 
> A message would be nice :)

We will show the minimum Node version in the upcoming documentation rework 👍	

Also keep in mind that Ubuntu packages are frozen, so updating things like node should ideally happen outside of those packages, e.g. via the node installer or node version manager.
