### ISSUE TITLE
(non-axios) nuxtServerInit fires for each static dynamic route generated

### ISSUE THREAD

**Issue by gabrielsze** [nuxt/nuxt.js#7702]
Hi there, I'm having the exact same issue as the one mentioned here

https://github.com/nuxt/nuxt.js/issues/3935

I'm just wondering if there is any other workarounds without using an axios call. I'm making an API call to firebase `db.collection("test").doc("test").get() ...` so I'm looking for a non-axios solution to this issue! Really much appreciated.

**Comment by farnabaz** [comment]
@gabrielsze ِYou can use any caching solution. Look at [lru-cache](https://www.npmjs.com/package/lru-cache)
