### ISSUE TITLE
Component isn't behaving like in vue

### ISSUE THREAD

**Issue by KingSora** [nuxt/nuxt.js#7706]
### Versions

- nuxt: v2.13.3
- node: 

### Reproduction

I have created two sandboxes:
Vue: https://codesandbox.io/s/jolly-glade-xtnog
Nuxt: https://codesandbox.io/s/goofy-bhaskara-r9mn7

As you can see, both are essentially the same, except they'll change if you click on the "update" button. 
The color of the text changes, because in the `nuxt` example the added classes gets removed after component updates, but why?
Am I doing something wrong? (Please be aware that the way the classes gets added e.g. via vanilla javascript is simulating a 3rd party library)

### Steps to reproduce
Go to Sandboxes, press the "update" button. Both sandboxes despite similar code behave differently.

### What is Expected?
The behavior for both components should be the same.

**Comment by farnabaz** [comment]
This happens because you are using Nuxt in `universal` mode, change `mode` in `nuxt.config.js` to `spa` and you will get exact same behavior as Vue.
```
mode: "spa",
```

**Comment by KingSora** [comment]
@farnabaz thank you for your answer! 

That might solve the problem but it also means that SSR is gone, right? Is there a soltion where SSR is still working? Also I would like to understand the reason behind the problem. So I can improve in the future and write SSR enabled Vue components with 3rd party libraries.

**Comment by farnabaz** [comment]
This happens because server rendered version of Dom is different from manipulated version(by 3rd party lib) in browser.
Look at [ssr directives](https://nuxtjs.org/api/configuration-render#bundleRenderer) and #898 this may help you to write ssr directive for library.

I close this issue, Feel free to reopen issue or create new one anytime.
