### ISSUE TITLE
Nuxtjs external link dynamic redirect with params - router customization

### ISSUE THREAD

**Issue by nav064** [nuxt/nuxt.js#7708]
I'm implementing a login module. 
The login page UI is provided by the cloud service provider
From my page, I need my nuxt app to redirect to an external URL provided by the external service provider with params. 

**VueJs Option 1:**
VueJs seems to have a way of supporting it using a modification in the [router](https://stackoverflow.com/a/50633229/2477612)
```
{
     path: '/myownpath',
     beforeEnter() {location.href = 'http://example.com'}
}
```

Have been trying to use _**this.$router.push**_

```
this.$router.push({
      path: '/myownpath',
      beforeEnter(){
        window.location.href = APP_HOST_URL
      },
      params: {
        'response_type': "code",
        'client_id': APP_CLIENT_ID,
        'redirect_uri': APP_REDIRECT,
        'state': 'random'
      }
    })
```

But this only redirects me to http://localhost:3000/APP_HOST_URL

**VueJs Option 2:** 
Another workaround seems to be using a meta attribute like [here](https://github.com/vuejs/vue-router/issues/2354#issuecomment-417497122).

I think nuxt will need a simpler way of expressing this case. 

Something in the lines of

```
{
     path: 'http://example.com/myownpath',
     absolutePath: true,
     params: {
        'response_type': "code",
        'client_id': APP_CLIENT_ID,
        'redirect_uri': APP_REDIRECT,
        'state': 'random'
     }
}
```

Or probably a config setting in nuxt.config.js on _[router / router-extras / extendRoutes](https://nuxtjs.org/guide/routing/#extending-the-router)_

`allowAbsolutePath: true`

**Comment by farnabaz** [comment]
Just create a simple page and redirect to `APP_HOST_URL` inside `asyncData`
```js
export default {
  asyncData (ctx) {
    ctx.redirect('APP_HOST_URL')
    return {}
  }
}
```

**Comment by nav064** [comment]
Thanks for looking into this @farnabaz 
I just added this section onto an empty page. 

Now **login.vue** has

```
asyncData (context) {
    context.redirect('/signup')
    return {}
  },
```
Redirecting to another active route '/signup' for checking if internal redirect works first. 

Strangely, I'm seeing a server startup issue
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined `

**Comment by farnabaz** [comment]
I believe this issue is not related to `asyncData`, take a look at [this example](https://codesandbox.io/s/pensive-leakey-skhr6?file=/pages/login.vue)

**Comment by nav064** [comment]
Thanks for the example. Your example works even for external redirects.
You know what, @farnabaz? I was using nuxt express-template! That was why it was not working. Trying a way out.

**Comment by nav064** [comment]
Even with nuxt express template, **context.redirect** works fine according to the example. 
It was a misconfiguration from my end. Thanks again.
