### ISSUE TITLE
Build "extractCSS" is error when use require function get image file

### ISSUE THREAD

**Issue by ReginnaChao** [nuxt/nuxt.js#7710]
### Versions

- nuxt: v2.13.0
- node: v10.15.1

### Reproduction

I use `extractCSS` and require image file, but CSS file is incorrect after `build` script.

This my project tree:
```
Project
│  nuxt.config.js
│  
├─assets
│  │  
│  ├─img
│  │      test.png
│  │              
│  └─sass
│      │  app.sass
│      │  
│      ├─layout
│      │      _main_style.scss
│      │      _mixin.sass
│      │      
│      └─vendor
│              _normalize.scss
│                   
└─pages
        index.vue
```

```
// nuxt.config.js
export default {
  css: [
    // Global CSS
    { src: '~assets/sass/app.sass', lang: 'sass' },
  ],
  modules: [
    '@nuxtjs/style-resources'
  ],
  styleResources: {
    // Set global sass mixin and variable
    scss: './assets/sass/layout/_main_style.scss',
    sass: './assets/sass/layout/_main_style.scss'
  },
  build: {
    extractCSS: process.env.NODE_ENV === 'production',
    optimization: {
      splitChunks: {
        cacheGroups: {
          styles: {
            name: 'styles',
            test: /\.(css|vue)$/,
            chunks: 'all',
            enforce: true
          }
        }
      }
    }
  }
}
```

Global Style: `assets/sass/app.sass`
![image](https://user-images.githubusercontent.com/19789757/87287982-534d5a80-c52d-11ea-8e0b-d09d5b9055e6.png)

Global SASS mixin file: `assets/sass/layout/_main_style.scss`
![image](https://user-images.githubusercontent.com/19789757/87288236-a9ba9900-c52d-11ea-9748-8ab0e979b708.png)

When I get image source by require function with data, like this: 
![image](https://user-images.githubusercontent.com/19789757/87288806-66acf580-c52e-11ea-866d-4c039bb7da89.png)

Building Result:
Global Style: `app.css`
![image](https://user-images.githubusercontent.com/19789757/87289269-010d3900-c52f-11ea-8b55-3f068797da6c.png)

Page Style: `index.css`
It was get app.css file import file.
![image](https://user-images.githubusercontent.com/19789757/87289336-197d5380-c52f-11ea-9147-f3345a566dae.png)

### What is Expected?
1. Use require function get assets image file.
2. Use global mixin for each component.
3. Build common style and page style. Like this:
index page use: app.css and index.css
about page use: app.css and about.css

How to solve this problem? Is my setting wrong?

**Comment by aldarund** [comment]
Please provide a minimal reproduction example in codesandbox or github
