### ISSUE TITLE
我后面发现出现热跟新失败的原因 (I found out the reason for the failure of hot and new)

### ISSUE THREAD

**Issue by Slowhalfframe** [nuxt/nuxt.js#7715]
> 我后面发现出现热跟新失败的原因
> 
> 我猜测是因为和电脑cpu只有两个内核, 当我开第三个网页的时候就会出现热更新失败的现象, 一直保持两个页面就不会出现这种现象
> 这只是我的猜测

确实是这个问题。。。但是我电脑是8核的。。。也是开三个就热更卡死

I found out the reason for the failure of hot and new

I guess it is because there are only two cores with the computer cpu. When I open the third web page, the hot update failure will occur. This phenomenon will not occur if I keep two pages.
This is just my guess

This is indeed the problem. . . But my computer has 8 cores. . . It’s even more stuck if you drive three

_Originally posted by @liasica in https://github.com/nuxt/nuxt.js/issues/6202#issuecomment-622657926_

**Comment by aldarund** [comment]
its because of limit of connections in chrome and other browsers https://stackoverflow.com/a/30064610/239354

and its somehow a dupe/similar of #https://github.com/nuxt/nuxt.js/issues/6442
