### ISSUE TITLE
> 我后面发现出现热跟新失败的原因

### ISSUE THREAD

**Issue by Slowhalfframe** [nuxt/nuxt.js#7716]
> 我后面发现出现热跟新失败的原因
> 
> 我猜测是因为和电脑cpu只有两个内核, 当我开第三个网页的时候就会出现热更新失败的现象, 一直保持两个页面就不会出现这种现象
> 这只是我的猜测

确实是这个问题。。。但是我电脑是8核的。。。也是开三个就热更卡死

_Originally posted by @liasica in https://github.com/nuxt/nuxt.js/issues/6202#issuecomment-622657926_

开两个以上网页卡顿是因为在开发环境下套接字不够，这是浏览器的限制。生产环境没问题的。（网上查的）

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/nuxt.js/issues/7716
