### ISSUE TITLE
Set headers (meta) with context.req

### ISSUE THREAD

**Issue by ThomasKientz** [nuxt/nuxt.js#7724]
### Is your feature request related to a problem? Please describe.

Our app is served from multiple domains and we want to customize the headers (favicon, title, etc..) from the domain. I suppose I can get the origin domain (host) from the `context.req` but I need to dynamically set the headers.

### Describe the solution you'd like

An api tp call in a serverMiddleware or other to dynamically set the metas.

```
export default function ({ app, req }) {
  if (req.headers.referer == 'myDomain.com') app.meta.set({title: 'my custom title'})
}
```

But I don't find any apis to dynamically set the headers apart from [the head method 
](https://nuxtjs.org/api/pages-head) which doesn't take the context in parameters. And I want to set it once far all the pages.

**Comment by farnabaz** [comment]
Yes `head` function does not take `context` in parameters but `asyncData` take the context. Inside `asyncData` you can read requested host and then use it in `head` function.
```js
  asyncData({ req }) {
    const host = req ? req.headers.host : location.host;
    return {
      host: req.headers.host
    };
  },
  head() {
    // this.host is  ready to use
    return {};
  },
```

**Comment by danielroe** [comment]
@ThomasKientz You should be able to do this with Nuxt as-is. See https://codesandbox.io/s/wizardly-hermann-sl9my?file=/pages/index.vue for a minimal example.
