### ISSUE TITLE
ChunkLoadError: Loading chunk {n} failed.

### ISSUE THREAD

**Issue by lopermo** [nuxt/nuxt.js#7725]
### Versions

- nuxt: v2.13.3
- node: v11.12.0

### Reproduction
I receive the following errors after building full-static spa page (nuxt build && nuxt export):
```
Failed to load resource: the server responded with a status of 404 (Not Found)  http://localhost:3000/_nuxt/pages/contact.pages/index.pages/portfolio.pages/project/hotailors.pages/project/mtank.pages/project/.40117ef1.cba329a.js
```
```
ChunkLoadError: Loading chunk 1 failed.
(error: http://localhost:3000/_nuxt/pages/contact.pages/index.pages/portfolio.pages/project/hotailors.pages/project/mtank.pages/project/.40117ef1.cba329a.js)
```

``nuxt dev`` works fine, the whole site works without problems.

```
mode: 'spa',
target: 'static',
modules: [
    '@bazzite/nuxt-optimized-images',
    '@nuxtjs/axios',
    '@nuxtjs/eslint-module',
    '@nuxtjs/robots',
    '@nuxtjs/redirect-module',
    'qonfucius-nuxt-fontawesome',
    '@nuxt/content',
    '@nuxt/components',
    '@nuxtjs/device',
    'vue-scrollto/nuxt',
    'bootstrap-vue/nuxt',
    ['@nuxtjs/dotenv', { filename: '.env' }],
    [
      '@nuxtjs/google-analytics',
      {
        id: '..',
        dev: false
      }
    ],
    [
      'nuxt-i18n',
      {
        rootRedirect: 'es',
        strategy: 'prefix',
        locales: [
          {
            code: 'en',
            iso: 'en-US',
            name: 'English',
            flag: '🇬🇧',
            file: 'en.js'
          },
          {
            code: 'es',
            iso: 'es-ES',
            name: 'Español',
            flag: '🇪🇸',
            file: 'es.js'
          }
        ],
        defaultLocale: 'es',
        lazy: true,
        seo: false,
        langDir: 'lang/',
        detectBrowserLanguage: {
          useCookie: true,
          cookieKey: 'language_cookie',
          // If no locale for the browsers locale is a match, use this one as a fallback
          fallbackLocale: 'es'
        }
      }
    ],
    '@nuxtjs/sitemap'
  ]
```

### Steps to reproduce
``nuxt build && nuxt export``
When loading any page of the website, the loader spinner will keep spinning forever and you can read the errors on the console.

If I serve the website locally with a simple python HTTP server, it works even though the error's still there. ``nuxt serve`` or netlify will always fail (keep the loader spinning and error in console).

### What is Expected?
Normal navigation through the website just as during development.
It works if I build it with ``mode: 'universal'``

### What is actually happening?
The website doesn't work. Console's output after ``nuxt build && nuxt export`` is weird chunks like this:
```
pages/index.pages/portfolio.pages/project/hotailors.pages/project/mtank.pages/project/numadoo.pages/.11bb9524.81514e9.js (345 KiB)
pages/project/hotailors.pages/project/mtank.pages/project/numadoo.d7c8c70.js (282 KiB)
```

**Comment by danielroe** [comment]
Should be fixed by https://github.com/nuxt/nuxt.js/pull/7667

**Comment by lopermo** [comment]
> Should be fixed by #7667

Is there any way to fix it before v2.14 is released? I can't update my webpage because of it.
I assume then that the error is nuxt's, there's nothing I can do to fix it?

**Comment by danielroe** [comment]
@lopermo This workaround should solve it: https://github.com/nuxt/nuxt.js/issues/7665#issuecomment-655586904

**Comment by pitpit** [comment]
Commenting for dummies like me that are facing this issue.

On _Brave_ browser in dev mode, I have this error `ChunkLoadError: Loading chunk pages/mypage/_id failed.` on routes with  params generated from pages/

I discovered the adblocker was blocking the chunk to be loaded.
 
So disable and it will work like a charm...
