### ISSUE TITLE
nuxt generate: CSS not included in head

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#7726]
**Version**
v2.13.3

**Reproduction link**
https://github.com/lights0123/nuxt-css-issue

**Steps to reproduce**
yarn && yarn run generate

Then view dist/index.html, such as via npx serve dist

**What is expected ?**
The included CSS, assets/test.css, should be inlined into the page as a <style> element when generated into a static page, instead of being added by JS later.

**What is actually happening?**
Only CSS defined in a local <style> element is inlined. If Javascript is disabled, then this CSS never gets loaded, as it requires JS to include in the page. As per https://nuxtjs.org/faq/css-flash,

the CSS is separated and put in the header so this flash of unstyled content does not appear anymore

However, repeating this in a layout (i.e. putting import '~/assets/test.css'; in layouts/default.vue) works successfully, and the CSS is included in the generated HTML file.

Additional comments?
I remember this working fine a few months ago in a project I was working on. I changed a few things around, though, and this bug appeared.

**Comment by Edmund1645** [comment]
Thanks for opening this @wargt I thought this was an issue from the plugin/library I was using. it seems that any CSS i create in `~/assets/css/` and register globally in `nuxt.config.js`:

```js
export default {
  css: [ '~/assets/css/assets.css']
}
```

is not added in a `<style>` tag in `<head>`.

I've been racking my head trying to figure it out. 

@wargt what part of the layout do you import the CSS? `<script>`? I probably have to use that technique for the time being.

**Comment by Edmund1645** [comment]
I just imported to the `<script>`,  it works just like before in development (my local machine). But the CSS is still not added to `<head>` when I deploy.

**Comment by Edmund1645** [comment]
https://github.com/shakee93/vue-toasted/issues/168#issue-656775054

**Comment by wargt** [comment]
@Edmund1645  Yes, I enable css in the <script> tag. Everything works fine in dev mode. But when I do `npm run generate` - css is missing in the <head> tag.

**Comment by wargt** [comment]
up

**Comment by Edmund1645** [comment]
I have found a fix for my problem, it was with purgeCSS for me. It removed classes that we're not in use at that time during build. All i had to do was place purgeCSS ignore comment where I needed it to ignore.

**Comment by wargt** [comment]
Good! But i have other problem. (

**Comment by wargt** [comment]
@VictorTolbert help

**Comment by wargt** [comment]
up

**Comment by wargt** [comment]
up

**Comment by wargt** [comment]
op

**Comment by wargt** [comment]
help

**Comment by wargt** [comment]
hello

**Comment by wargt** [comment]
(

**Comment by danielroe** [comment]
@wargt In your repro you have imported the CSS into your `<script>` tag - which is why it isn't inlined in the page but rather injected via JS when the page hydrates. 

If, instead, you were to import it in a `<style>` tag - it would behave as you expect, as vue-style-loader will take care of injecting it correctly.
```vue
<style>
@import '~/assets/test.css';
</style>
```

Another option is listing it in your `nuxt.config` file under the `css` array.

**Comment by harvanchik** [comment]
I am deploying the app on GitHub Pages using Nuxt's suggested GitHub Actions scripts.  The CSS is not being included in the `<head>` tag and I don't know why.  Here's my [repository](https://github.com/harvanchik/songuessr).

**Comment by cco3** [comment]
@harvanchik did you ever figure this out?
