### ISSUE TITLE
this.$nuxt.error() causes error.vue to render incorrectly (using fetch >= 2.12)

### ISSUE THREAD

**Issue by rmirabelle** [nuxt/nuxt.js#7727]
I'm still trying to wrap my head around the nearly insurmountably confusing usage of `fetch()` and its impact on `error.vue`

My current understanding is that `error.vue` is **always** rendered as either a `Component` or a `Page`, but never a `Layout`. 
Already confusing.

**Old `fetch` and `throw new Error` act like they're supposed to**:

If I call the 'old' (< 2.12) version of `fetch`, with a `context` argument, then call `context.error('whatever')`, **OR** if I simply `throw new Error('whatever')`, `error.vue` is rendered as expected - a `Page`, whose `layout` property is properly respected.

**New `fetch` does what??**

If I call the new (>= 2.12) version of `fetch()` with no arguments, then call `this.$nuxt.error('whatever')`, `error.vue` appears to be forcibly rendered **INLINE** as a `Component` that _completely ignores_ its own `layout` property and renders inside the current layout instead.

I assume this is a bug in `this.$nuxt.error()`?  

Surely, this can't be the expected behavior, i.e. completely changing the way `error.vue` is rendered based solely on the `this` context that new `fetch` provides?

**Comment by andrei-scripcaru** [comment]
This was reported in #7567 is supposed to be fixed by #7654, but I still encounter a similar scenario.

**Comment by minawalphonce** [comment]
Not fixed in 2.13.3 related #7743

**Comment by bpeab** [comment]
Still an issue, the stalebot shouldn't close it.
