### ISSUE TITLE
Fetch and mounted execution order is inconsistent between dev and production modes

### ISSUE THREAD

**Issue by MarkSonn** [nuxt/nuxt.js#7729]
I'm using fetch on Nuxt >= 2.12 for my static site (`target: 'static'`). 

In production mode fetch is called before mounted. I know this is the case because fetch changes values in data which can then be used in mounted.

I noticed, however, that the opposite is true in dev mode. This makes it hard to simulate what my production app will look like without running `nuxt build && nuxt export && nuxt serve` every time I want to make a change.

Is it possible please to introduce consistent behaviour and updated documentation with regard to the ordering of execution for fetch and mounted?

At the very least can someone please let me know how I can execute code after fetch has completed?

Thanks for all your good work Nuxt team :)

**Comment by danielroe** [comment]
@MarkSonn This is because, as an async function, fetch takes time to run, and so in dev mode, might finish running after mounted. But after export, it is inlined in page so takes a negligible amount of time.

If you need to run code after fetch, you could set up a one-time watcher.

**Comment by MarkSonn** [comment]
Yeah makes sense...this is what I assumed. I think the dev mode should be designed to simulate production as closely as possible. Yeah I'll mess around with watchers, but just a bit of a waste of time and added complexity just to make things work in dev mode.
