### ISSUE TITLE
Custom code-splitting for page bundles?

### ISSUE THREAD

**Issue by milestonebooks** [nuxt/nuxt.js#773]
I noticed, [per issue #567](https://github.com/nuxt/nuxt.js/issues/567) that Nuxt.js currently does not provide customization of the code-splitting functionality.

My situation is the opposite of @OlzhasAlexandrov: I have only 2 routes, but one of them is a dynamic nested route. The top level serves half a dozen pages, and the second level breaks out into a total of about 100 pages, and the bundle ends up being more than 1 MB. I would dearly love to find an elegant solution for splitting the bundles by actual page rendered.

I'm a newbie to webpack, so although @rvanson's [gist](https://gist.github.com/rvanzon/6028e884f6735c41125fb2d140143102) sheds some light, I'm not sure where to look for a solution.

**Comment by kodekrendel** [comment]
@milestonebooks so have you tried @rvanzon gist?

**Comment by milestonebooks** [comment]
@kodekrendel That gist doesn't answer my need, because I'm not trying to limit the **number** of chunks, I'm trying to limit the **size** of the bundle (which would increase the number of chunks) produced by my dynamic nested route:
```
pages/texts/_book/_chapter.vue
```
The one other webpack variation I tried just now was [AggressiveSplittingPlugin](https://github.com/webpack/webpack/tree/master/examples/http2-aggressive-splitting), but Nuxt choked on it, and the documentation didn't give any hope of it being a real solution for my problem anyway.

I tried loading each chapter's data asynchronously, which completely eliminated the bundle size problem, but then of course the SSR failed to generate the code necessary for static hosting.

Although I haven't tried it yet, I'm guessing I could achieve my optimization goal by destructuring the route into the 100 or so individual pages, but that seems like an awful waste of duplicate code, violating DRY. Also, that option doesn't bode well for a much larger project in the works. Sure, I could use a preprocessor to build out my .vue route tree before running Nuxt, but it would seem so much simpler if I didn't have to.

**Comment by milestonebooks** [comment]
Success!

> I tried loading each chapter's data asynchronously, which completely eliminated the bundle size problem, but then of course the SSR failed to generate the code necessary for static hosting.

It turns out I was using an outdated method of [generating the dynamic routes](https://nuxtjs.org/api/configuration-generate#routes), so none of those routes were being rendered, causing the site to break when accessing those pages statically.

Now bundles sizes are nice and small, and data quietly loads asynchronously as it should. :-)

**Comment by kodekrendel** [comment]
@milestonebooks nice. What do you mean by 'outdated'? How did you end up?

**Comment by milestonebooks** [comment]
@kodekrendel When I jumped on board Nuxt in February, the way to generate dynamic routes [was with the `routeParams` property](https://github.com/nuxt/docs/blob/cd80de09cf4dca51f8299341b8ffacfa2744134f/en/api/configuration-generate.md).

Just recently I updated to 0.10.7, and was blissfully unaware of the change to the `routes` property. I'm glad the API is nearing stability. ;-)
