### ISSUE TITLE
Pages with the same route load slowly when multiple new windows are opened

### ISSUE THREAD

**Issue by ZhuHQ** [nuxt/nuxt.js#7730]
Pages with the same route load slowly when multiple new windows are opened

**Comment by ZhuHQ** [comment]
- [ ] `<template>
  <div class="container">
    <div>
      <Logo />

      <h1 class="title">
        test-demo1
      </h1>
      <div>
        <nuxt-link target="_blank" to="/">
          new window
        </nuxt-link>
      </div>
      <div class="links">
        <a
          href="https://nuxtjs.org/"
          target="_blank"
          rel="noopener noreferrer"
          class="button--green"
        >
          Documentation
        </a>
        <a
          href="https://github.com/nuxt/nuxt.js"
          target="_blank"
          rel="noopener noreferrer"
          class="button--grey"
        >
          GitHub
        </a>
      </div>
    </div>
  </div>
</template>`

**Comment by aldarund** [comment]
not quite clear what you mean. Do you dev mode with multiple pages opened?
