### ISSUE TITLE
Access Vue router in a component's ambient/global context

### ISSUE THREAD

**Issue by Haroenv** [nuxt/nuxt.js#7733]
### Is your feature request related to a problem? Please describe.

I have an API which requires to read from the URL as well as writing to it. In general this is done with the history API, but when using Vue Router, people prefer that being used.

The problem is that my API for server-side rendering, to provide serverPrefetch, is done via a mixin, and the arguments to the mixin get evaluated before the component’s code. Because the Vue Router instance lives on the component instance (on this), it’s not accessible from the mixin.

### Describe the solution you'd like

Maybe there's already a way, but I'd like to be able to read Vue Router from a different place than `this`, e.g. global. This should happen before the component mounts.

### Describe alternatives you've considered

For now what I've done is twofold

1. in `beforeCreate`, save `this.$nuxt.$router` to some global variable

When writing the URL later, use that new global variable

2. in the arguments to the mixin, I've used `global.__VUE_SSR_CONTEXT__.req.url` and `global.location.search`

This is for `read` before `beforeCreate` happens.

Normally you should be able to use Vue Router for both of these

### Additional context

A sandbox of the workaround I have now: https://codesandbox.io/s/recursing-mountain-k8umi?file=/pages/search.vue

**Comment by farnabaz** [comment]
Hey @Haroenv,
By looking at `createServerRootMixin` implementation you'll see that it just provide `instantsearch` in data.
Instead of using `createServerRootMixin` in mixins you can call it inside your page's `data` and use its results, and yes inside `data` you have access to `router`

```js
...
  data() {
    const mixin = createServerRootMixin({
      searchClient,
      indexName: 'instant_search',
      routing: {
        router: nuxtRouter(this.$nuxt.$router),
      },
    });
    return {
      ...mixin.data()
    }
  },
  provide() {
    return {
      $_ais_ssrInstantSearchInstance: this.instantsearch,
    };
  },
...
```

**Comment by Haroenv** [comment]
That's very interesting, thanks! I will change the documentation to use this method instead.
