### ISSUE TITLE
Usage of aws-amplify in nuxt universal mode

### ISSUE THREAD

**Issue by malmil** [nuxt/nuxt.js#7738]
### Versions

- nuxt: v2.13.3
- node: v11.2.0

### Reproduction

This codesandbox will not work for other reasons like that I haven't added awsconfig, but it showes the structure of my app and the same error as I'm getting locally.
https://codesandbox.io/s/nuxtawsdocumentnotdefined-2qg3r?file=/pages/index.vue

`plugins: [
    {
        src: '~plugins/aws.js',
        mode: 'client',
        ssr: false
    }
  ],`

aws.js 
```import Vue from "vue";
import Amplify, * as AmplifyModules from "aws-amplify";
import AWSAppSyncClient from "aws-appsync";
import { AmplifyPlugin } from "aws-amplify-vue";

const awsconfig = {
  aws_project_region: "eu-central-1"
  // deleted my other keys
};

let client;

// added if (process.client) after some suggested that
if (process.client) {
  Amplify.configure(awsconfig);
  Vue.use(AmplifyPlugin, AmplifyModules);

  client = new AWSAppSyncClient({
    url: awsconfig.aws_appsync_graphqlEndpoint,
    region: awsconfig.aws_appsync_region,
    auth: {
      type: awsconfig.aws_appsync_authenticationType, //AWS_IAM
      credentials: () => AmplifyModules.Auth.currentCredentials()
    }
  });
}
```

### Steps to reproduce

Changed from `mode: 'spa'` to `mode: 'universal'`

### What is Expected?

Expected to be able to go from 'spa' to 'universal' and not get errors.
Expected to be able to use "aws-amplify" and "aws-amplify-vue" with nuxt

### What is actually happening?

This is really similar to this issue https://github.com/nuxt/nuxt.js/issues/6096 , but I'm not able to fix this by using:
- mode: 'client' or 'server' in the import of the plugin
- using `<client-only placeholder="Loading...">` in the component
- using `if (process.client) or if (process.server) in the plugin`

Also asked same question on [Stackoverflow](https://stackoverflow.com/questions/62910381/changing-from-spa-to-universal-in-nuxt-but-i-only-get-document-is-not-defi) before coming here

**Comment by farnabaz** [comment]
The problem is not your plugin, take a look and `middleware/auth`, you are importing `aws-amplify-vue` on server side, put this import inside `if(process.client)` condition.

```js
if (process.client) {
    const { AmplifyEventBus } = require("aws-amplify-vue");
    AmplifyEventBus.$on("authState", info => {
      if (info === "signedIn") {
        signedIn = true;
      } else {
        signedIn = false;
      }
    });
  }
```

**Comment by malmil** [comment]
Thanks @farnabaz 

Is there any way around having conditional imports when using `mode: 'universal'`?
Turns out "document not defined" is only the tip of the iceberg of undefined objects. Applying your solution made me first get "Cannot read property 'get' of null" from VueLocalStorage. And then moving on to Cannot read property 'install' of null from node_modules/vue/dist/vue.runtime.common.dev.js which I'm not sure how to fix.

Fork of previous codepen: https://codesandbox.io/s/nuxtawsdocumentnotdefinedfork-y1uu6?file=/store/user.js

Am I doing something fundamentally wrong here? 😕

**Comment by farnabaz** [comment]
The problem is using `VueLocalStorage` inside `store.js`, Instead of using `VueLocalStorage` you can use [@nuxtjs/universal-storage](https://github.com/nuxt-community/universal-storage-module) to store and retrieve states, it supports Vuex, localstorage and cookies.

**Comment by malmil** [comment]
Hey, I think I closed this issue too early. After some more days of trying and frustration I don't feel like this issue is solved. However I'm not sure if this is a Nuxt bug, because (to me) it seems like a vulnerability of using dynamic pages in Nuxt and AWS-Amplify together.

My motivation for switching from SPA to SSR was to have dynamic routes. I need this in order to be able to have Urls like blogpost/fa64521c-1ff1-4e67-adc5-a6538492454e. These are auto generated and in order to being able to post new blogposts I can't hardcode them in like:
```
module.exports = {
  generate: {
    routes: [
      '/users/1',
      '/users/2',
      '/users/3'
    ]
  }
}
```

Even though the code over made the "document not defined" go away. I would get "TypeError: Cannot read property 'Logger' of undefined" and the Amplify component would not show in the browser. (`<amplify-sign-out />` & `<amplify-authenticator />`)

So after finding no way out of that I went back to using SPA since I found out it's possible to do a call inside generate routes and make the dynamic routes based on that.
After writing this not so pretty code:
```
generate: {
    routes: function () {
      if (process.client) {
        const { fetchUser } = require('./middleware/auth')
        fetchUser().then(() => {
          const { listBlogPosts } = require('./src/graphql/queries')
          const { API, graphqlOperation } = require('aws-amplify')
          API.graphql(graphqlOperation(listBlogPosts)).then((response) => {
            if (response) {
              let blogPost = response.items.map((blogPost) => {
                  return {
                    route: '/blogPost/' + blogPost.id,
                    payload: user
                  }
              })
            }
          })
        })
      }
     }
}
```
I had high hopes that this could be a solution, but the code over, specifically the `fetchUser` (see component in codesandbox or comment over) causes "Cannot read property 'forEach' of undefined" when building application. 
...And I feel like I'm at the very same place as when I started on this.

**Comment by malmil** [comment]
Figured out how to solve the problem. I went over on SPA.
This solution gives me a warning on "The command 'nuxt build' finished but did not exit after 5s ". So I guess the call with the graphqlOperation is to slow for Nuxt's liking. 

```
generate: {
    routes: async function () {
      const AmplifyCore = require('aws-amplify')
      const Amplify = require('aws-amplify').default
      const { API } = Amplify
      const { graphqlOperation } = AmplifyCore
      const awsconfig = { // secrets }
      Amplify.configure(awsconfig)
      const { listBlogPosts } = require('./src/graphql/queries')

      const list = await API.graphql(graphqlOperation(listBlogPosts));
      if (list) {
        return list.data.listBlogPosts.items.map((blogPost) => '/blogPost/' + blogPost.id)
      }
      return []
    }
  },
```
