### ISSUE TITLE
nuxt types not working

### ISSUE THREAD

**Issue by hanh-dev** [nuxt/nuxt.js#7744]
My project using
- @nuxt/types: ^2.13.3
- @nuxt/typescript-build: ^2.0.0

seems vue and vue-property-decorator packages are missing

**Comment by hanh-dev** [comment]
my webstorm not detecting type definitions 
![image](https://user-images.githubusercontent.com/20147479/88016514-bd798700-cb4d-11ea-92af-e9b30e47362c.png)

i need install packages manually and it works
![image](https://user-images.githubusercontent.com/20147479/88016672-2234e180-cb4e-11ea-8beb-769b9d7d0d00.png)
![image](https://user-images.githubusercontent.com/20147479/88016694-2cef7680-cb4e-11ea-8180-c3713070c353.png)

**Comment by danielroe** [comment]
@hanh-dev What version of Webstorm are you using? See [this announcement](https://blog.jetbrains.com/webstorm/2020/07/webstorm-2020-2-beta-2/).

You can also get type hinting like this:
```ts
import Vue from 'vue'

export default Vue.extend({
  ...
})
```

**Comment by hanh-dev** [comment]
version of webstorm i using is 
![image](https://user-images.githubusercontent.com/20147479/88026891-b8720300-cb60-11ea-8df3-75139a95fa09.png)

that is same with Vue.extend
![image](https://user-images.githubusercontent.com/20147479/88027129-07b83380-cb61-11ea-8b87-1f93fba4e5cc.png)

it only works again when i install missing packages for my project
![image](https://user-images.githubusercontent.com/20147479/88027790-f6bbf200-cb61-11ea-9e2f-26883efd86e3.png)
![image](https://user-images.githubusercontent.com/20147479/88028420-d8a2c180-cb62-11ea-856b-7dea8dd211a2.png)

**Comment by hanh-dev** [comment]
many other packages not installed in @nuxt/types
![image](https://user-images.githubusercontent.com/20147479/88028761-45b65700-cb63-11ea-9962-d2788d898e54.png)

**Comment by danielroe** [comment]
This is not an issue with Nuxt. But the good news is that it appears that the next version of Webstorm will have full support for Nuxt. 👍

**Comment by kevinmarrec** [comment]
Installing `vue-property-decorator` to fix it doesn't make sense, it has nothing to do with it.

I don't have Webstorm experience but it seems it's Webstorm issue that can't find `vue` when it's not in `dependencies`/`peerDependencies` of a package present in root `package.json`.

Also, I don't know how Webstorm handles `tsconfig.json` but please check your file is correctly set (See https://typescript.nuxtjs.org/guide/setup.html#configuration)

In any case you need to use `Vue.extend` to properly have type inference.

**Comment by hanh-dev** [comment]
Yes, it seems webstorm can't find `vue` on `dependencies/peerDependencies` of @nuxt/types.
![image](https://user-images.githubusercontent.com/20147479/88037952-c24f3280-cb6f-11ea-900f-285c7b3d2852.png)

Also, that problem not appears on @nuxt/typescript-build <= 1.0.3

**Comment by hanh-dev** [comment]
this is my tsconfig
![image](https://user-images.githubusercontent.com/20147479/88038609-ac8e3d00-cb70-11ea-821f-4e06c9fba112.png)

**Comment by kevinmarrec** [comment]
@hanh-dev Maybe it's Webstorm not compatible with TypeScript 3.9 installed by `@nuxt/typescript-build@2.0`

**Comment by hanh-dev** [comment]
it problem not appears on@nuxt/typescript-build <= 1.0.3, because webstorm find vue dependencies in package.json of fork-ts-checker-webpack-plugin

it problem will be simpler by add missing dependencies to package.json present of @nuxt/types
