### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wlinglinux** [nuxt/nuxt.js#7745]
### Versions

- nuxt:  v2.13.3 
- node:  v8.11.2

### Reproduction

<details open>
<summary>Additional Details</summary>
Deploy error reporting in Linux
![error-0](https://user-images.githubusercontent.com/286261/88021640-7943b200-cb60-11ea-8605-6fddbb20e405.png)
![error-1](https://user-images.githubusercontent.com/286261/88021648-7cd73900-cb60-11ea-9cb2-0e997b40f2be.png)

<br>

</details>

**Comment by wlinglinux** [comment]
![error-0](https://user-images.githubusercontent.com/286261/88021686-8c568200-cb60-11ea-8d6d-ba875ae22b64.png)

**Comment by wlinglinux** [comment]
![error-1](https://user-images.githubusercontent.com/286261/88021739-9ed0bb80-cb60-11ea-9f57-af7f6e43ae46.png)

**Comment by manniL** [comment]
Please provide a proper reproduction.

**Comment by hm496** [comment]
The dependence fs-extra@9.0.1 of @nuxt/telemetry only supports nodejs >= 10.0.0,
please replace one to support nodejs 8.x.x

https://github.com/nuxt/telemetry/issues/26
