### ISSUE TITLE
Cannot find module ". . . . .jpg"

### ISSUE THREAD

**Issue by sobhanweb** [nuxt/nuxt.js#7749]
### Versions

- nuxt: ^2.13.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

![image](https://user-images.githubusercontent.com/60367363/88050328-da24b780-cb6b-11ea-9a45-ad34bd0f5b05.png)

* assets/img/customer-first.jpg in ./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=style&index=0&lang=scss&

![image](https://user-images.githubusercontent.com/60367363/88050349-e9a40080-cb6b-11ea-944f-0fb4ac86ed5d.png)

When I url a new image in my default.scss file this happens.

![image](https://user-images.githubusercontent.com/60367363/88050416-08a29280-cb6c-11ea-95cb-b938c51daf7b.png)

![image](https://user-images.githubusercontent.com/60367363/88050433-16581800-cb6c-11ea-95a8-b9dc4637a67b.png)

I've installed the node-sass and sass-loader webpack loaders.

**Comment by aldarund** [comment]
Is this file exist? Its impossible to provide any feedback from this issue. Create a proper reproduction on codesandbox or github

**Comment by sobhanweb** [comment]
Of course it does 
![image](https://user-images.githubusercontent.com/60367363/88052971-528d7780-cb70-11ea-95e7-e2bf43e594e4.png)

**Comment by aldarund** [comment]
like i said create a reproduction, its not possible to help without it

**Comment by aldarund** [comment]
actually you file called customerS-first.jpg while u are referring to customer-first.jpg without S. In future create a proper reports with reproductions
