### ISSUE TITLE
"New version available - Reload" feature for SPA

### ISSUE THREAD

**Issue by Darkside73** [nuxt/nuxt.js#775]
Is nuxt suggests any mechanism to notify SPA about new version available and therefore page should be reloaded (like Google Inbox does for example)?

**Comment by pi0** [comment]
Hi! Nice idea. It may be achieved​ by priodically checking manifest.js with a service worker. We are working on new nuxt modules witch can bring many functionalies like this to nuxt.

**Comment by Darkside73** [comment]
Is it planned for 1.0 release?

**Comment by pi0** [comment]
Modules are external npm packages which extend core api. And yep modules support already added to alpha1. (Spoiled :D) You may keep track of progress there. https://github.com/nuxt/modules

**Comment by Darkside73** [comment]
Good news indeed, thanks. Hope it will be shipped soon. It's quite critical for production

**Comment by jvandenaardweg** [comment]
Awesome!

**Comment by Atinux** [comment]
Closing it since `rc3` is out
