### ISSUE TITLE
nuxt.config.js引入scss文件成功，但组件使用@mixin方法报错

### ISSUE THREAD

**Issue by wzj19930304** [nuxt/nuxt.js#7756]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is actually happening?
nuxt.config.js引入scss文件成功，但组件使用@mixin声明的方法报错。
在组件单独引入scss文件并使用@mixin声明的方法成功

**Comment by farnabaz** [comment]
Please provide a reproduction sample for the issue.

**Comment by wzj19930304** [comment]
nuxt.config.js里的css引入'~/assets/css/mixin.scss'，
报错：Module build failed (from ./node_modules/_sass-loader@9.0.2@sass-loader/dist/cjs.js): SassError: no mixin named flex-center on line 74 of components/TopBar.vue >> @include flex-center; -----------^****

在index.vue style 里引入 @import "@/assets/css/mixin.scss"; 

就不报错

**Comment by farnabaz** [comment]
Obviously it cannot find `flex-center` in your project. Do you have any mixin named `flex-center` inside `'~/assets/css/mixin.scss'`?

**Comment by wzj19930304** [comment]
yes,I have.In /assets/css/mixin.scss.
When I use @import to import mixin.scss,it has no issue

**Comment by farnabaz** [comment]
Could you create a project on [codesandbox.com](https://codesandbox.com) to reproduce the issue?

**Comment by farnabaz** [comment]
Now I understand your issue. Styles that defined in `css` section in `nuxt.config` are not a baseline for all styles of project, they just compile to pure css and injects in page. What you want to achieve is provide by [style-resources-module](https://github.com/nuxt-community/style-resources-module)

**Comment by wzj19930304** [comment]
Wow, you are so responsible.Thank you so much!!!!!!!!!

**Comment by yj-1** [comment]
nuxt2.15.1识别不了scss语法
 24:2   ✖  Unexpected unknown at-rule "@mixin"                      at-rule-no-unknown
 29:3   ✖  Unexpected unknown at-rule "@include"                    at-rule-no-unknown
