### ISSUE TITLE
Incorrect routes order when using static and dynamic ones on the same level

### ISSUE THREAD

**Issue by mattersj** [nuxt/nuxt.js#7757]
### Versions

- nuxt: **2.13.0**
- node: **14.2.0**

### Reproduction

Here is a demo: https://codesandbox.io/s/routes-order-issue-kfo9i

### Steps to reproduce

1. Create **news/index.vue** page.
2. Create dynamic page **news/index/_id/index.vue**.
3. Create any static page in news directory e.g. **categories.vue** (it's expected that this route has to be independent i.e. not a part of children routes of the **news** page).

### What is Expected?

**news/categories** page should has higher priority than dynamic **news/_id**.

### What is actually happening?

**news/categories** page has lower priority than **news/id** and we have to manually push this route to the start of route list using extendRoutes.

**Comment by farnabaz** [comment]
You are doing it wrong, You have created `news/index/_id/index.vue`. Just remove `index` directory in the middle and you will see everything is ok.
You have mistakenly created child routes, You can read more about child routes in [official docs](https://nuxtjs.org/api/components-nuxt-child/)

**Comment by mattersj** [comment]
@farnabaz If I remove `index` directory then `_id` route will no longer be a child route of `news` and that's not what I wanted. For example, I want to show some info about my news in modal window so I need to show both `news` and `news/_id` at the same time. Therefore, `_id` route **must** be a child of `news` so `index` directory is important here.
Next, I want to have completely separate route with following url: `news/categories` i.e. this route should **not** be rendered as a child of `news`).
I think current structure of pages is the only way to do what I want.

**Comment by mattersj** [comment]
For the sake of clarity I'll show the structure I need:
First of all, I need `news` route and the child `_id`.
![image](https://user-images.githubusercontent.com/28510814/88395252-71d31180-cdc9-11ea-866c-7acd96406c48.png)
Further, I need separate `news/categories` route with its own children (create, edit, delete etc.).
![image](https://user-images.githubusercontent.com/28510814/88395543-eb6aff80-cdc9-11ea-961c-7ecd712017f5.png)
In this case I'm using extendRoutes and just pushing `news/categories` to the top to get right priority.

**Comment by farnabaz** [comment]
With current processing order of routes in Nuxt, this is not supported.
The solution is using `extendRoutes` to reorder routes or using [router-extras](https://github.com/nuxt-community/router-extras-module) module

**Comment by mattersj** [comment]
I got it, thank you for your reply.
