### ISSUE TITLE
nuxt-link does not pass tabindex attribute to wrapped anchor element

### ISSUE THREAD

**Issue by lee-leonardo** [nuxt/nuxt.js#7758]
# Versions

- nuxt: 1.4.5
- node: v10.20.1

### Reproduction

- https://github.com/pwa-builder/PWABuilder/tree/issue839

- after cloning: `npm run dev`
- default server is at localhost:3000

<details open>
<summary>Additional Details</summary>
<br>
Link to the line with the usage:
https://github.com/pwa-builder/PWABuilder/blob/issue839/pages/_lang/generate.vue#L499

This is essentially just a property that is not being passed from nuxt-link to route-link.
</details>

### Steps to reproduce

1. Navigate to the manifest page, click on the images tab.
2. Open the uploads. Instead of interacting with the UI, just tab.
3. Notice that the nuxt-link receives focus and that the generated anchor tag lacks the tabindex html attribute

### What is Expected?

The anchor tag should have the tabindex attribute,

### What is actually happening?

This attribute is not being passed down from the nuxt-link wrapper of route-link.

**Comment by farnabaz** [comment]
Try updating Nuxt to version 2.x, Its will solve the problem.
Nuxt 1.x is not developing and we only push critical bug fixes.
