### ISSUE TITLE
asyncData/fetch + v-html bind performance issue on firefox

### ISSUE THREAD

**Issue by willin** [nuxt/nuxt.js#7759]
### Versions

- nuxt: v2.13.3 
- node: v14.5.0 

### Desc

- asyncData or fetch method to request dynamic data
- render data html using `v-html` tag
- it works well on chrome (within 1s)
- load too slow on firefox (more than 6s usually)

### Reproduction

at first i think this sth related with vue.

vue v2.6.11 v-html bind test: https://jsfiddle.net/willin/nmqp3xty/

<img width="2417" alt="1" src="https://user-images.githubusercontent.com/1890238/88249048-c5fcc980-ccd5-11ea-98ec-9baa5b13497c.png">

---

nuxt demo page:

```js
<template>
  <div>
    Demo Page
    {{ slug }}

    <h1>{{ title }}</h1>
    <div v-html="html"></div>
  </div>
</template>

<script>
export default {
  async fetch() {
    try {
      const { title, html } = await import(`~/assets/posts/${this.slug}.json`);
      this.tiele = title;
      this.html = html;
    } catch (e) {
      // ignore
    }
  },
  data() {
    return {
      slug: this.$route.params.slug,
      title: '',
      html: ''
    };
  }
};
</script>
```

<img width="2486" alt="2" src="https://user-images.githubusercontent.com/1890238/88249131-0eb48280-ccd6-11ea-9520-3af3b4a38781.png">

<img width="2262" alt="3" src="https://user-images.githubusercontent.com/1890238/88249144-18d68100-ccd6-11ea-950e-f6a5d77df9fa.png">

### What is Expected?

like chrome 

<img width="2488" alt="4" src="https://user-images.githubusercontent.com/1890238/88249188-4de2d380-ccd6-11ea-88e3-c0ff50805042.png">

**Comment by aldarund** [comment]
Please provide a minimal working repro in nuxt on CSB or github not just page code

**Comment by willin** [comment]
sure, wait for a while.

**Comment by willin** [comment]
@aldarund 

source code project: https://github.com/wshow/nuxt-render-perfomance


firefox profile:  https://raw.githubusercontent.com/wshow/nuxt-render-perfomance/master/firefox-profile.json

**Comment by aldarund** [comment]
@willin so here it is on CSB https://codesandbox.io/s/github/wshow/nuxt-render-perfomance
How to repro in FF? 
I tried to open directly https://87j4b.sse.codesandbox.io/post/test or navigate from index page . Both work withing 1s on FF 79

**Comment by willin** [comment]
chrome profile: [chrome-profile.txt](https://github.com/nuxt/nuxt.js/files/4971338/chrome-profile.txt)


i run locally this demo,  filrefox about 1.5s+, chrome within 50ms.

<img width="375" alt="QQ20200724-180333@2x" src="https://user-images.githubusercontent.com/1890238/88380935-093f6100-cdd8-11ea-891b-deacb6c667d5.png">

**Comment by willin** [comment]
Firefox: `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:79.0) Gecko/20100101 Firefox/79.0"`

Chrome: `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4209.3 Safari/537.36"`

**Comment by aldarund** [comment]
in my ff its also 50ms
https://i.imgur.com/dOQ40AD.png

Maybe you have some addon in FF? Or try to do in incognito tab

**Comment by willin** [comment]
emmmm i've disabled all extentions and try, still 1400ms around.

[firefox-profile.txt](https://github.com/nuxt/nuxt.js/files/4971460/firefox-profile.txt)

**Comment by aldarund** [comment]
Certainly didnt happen to me... Maybe its firefox on mac specific

[profile.txt](https://github.com/nuxt/nuxt.js/files/4971484/profile.txt)

**Comment by FearwareX** [comment]
[firefox-profile.txt](https://github.com/nuxt/nuxt.js/files/4971489/firefox-profile.txt)


"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:78.0) Gecko/20100101 Firefox/78.0"


2s+ on macbook pro (previous iMac)

**Comment by willin** [comment]
i've tried window firefox. 33ms.

... i wonder why

**Comment by aldarund** [comment]
Ye, i tried on win. So its mac specific..
Probably something that is used implemented slow on mac FF. Like dynamic import of  json maybe. Try to experiment and timelog what take most time e.g. import itself maybe?

**Comment by willin** [comment]
```js
  async fetch() {
    // const { title, html } = await import(`~/assets/posts/${this.slug}.json`);
    const { title, html } = await this.$http.$get(`/posts/${this.slug}.json`);
    this.title = title;
    this.html = html;
  }
```

still 1400ms without `dynamic import`.

**Comment by willin** [comment]
?
