### ISSUE TITLE
Can't Set Root Route Path Other Than '/'

### ISSUE THREAD

**Issue by RezaZR** [nuxt/nuxt.js#7762]
### Versions

- nuxt: ^2.13.0
- node: 12.18.2

### Reproduction
So let's say I have 3 different versions in one nuxt project
version 1 has root route '/'
version 2 has root route '/v2/'
and version 3 has root route '/v3/'

I created v1, v2, and v3 folder on Pages, I created children folders too on each of those 3 versions.

### What is Expected?
I want to make the root route / or /v2/ or /v3/ based on the api response.

### What is actually happening?
The root route always / and I can't achieve what I want, or am I missing something from the documentation? 

I can't seem find it in the Github issue as well as Stackoverflow. Can anyone help me? 
Thank you

**Comment by farnabaz** [comment]
You can simply achieve your goal. Just create three versions `/v1`, `/v2`, `/v3/` of home page then call your API on `asyncData` hook in `index.vue`, and redirect user based on API response

**Comment by RezaZR** [comment]
@farnabaz yes I did that already, the problem is when I tried to access the sub page like /camera it always refer to /camera not /v2/camera or /v3/camera.

oh ya, I'm using nuxt-i18n so the nuxt-link is ```:to="localePath('/camera')"``` is there any wrong with localePath?

**Comment by manniL** [comment]
Given you are on `example.com/v1/`.

`to="/camera"` will always link to `example.com/camera` because of the leading slash,
while `to="camera"` will take the current URL into account and link to `example.com/v1/camera` in the given case.

**Comment by RezaZR** [comment]
@manniL hmm it doesnt work :/ it still redirect to /camera not /v2/camera

ok, so I found this documentation https://nuxtjs.org/api/configuration-hooks#redirect-to-router-base-when-not-on-root 
then I copy all of it then I use process.env.BASE_ROUTE from dotenv, set router.base in nuxt.config.js to process.env.BASE_ROUTE, restart server and solved.

thank you @farnabaz @manniL
