### ISSUE TITLE
[2.13][Full Static Mode] Better handle asyncData/fetch with local files in dev mode

### ISSUE THREAD

**Issue by kiuKisas** [nuxt/nuxt.js#7764]
## Context
Using `asyncData` with the new full static mode, I have several payloads already saved in local, this way, I can be graphql/axios free in my generated website. To load these payloads, I do as following:
```
  async asyncData({ app }) {
    const path = 'payloads/pages/' + app.i18n.locale + 'index.json'
    return JSON.parse(require('fs').readFileSync(path, 'utf8'))
  }

```
A sample readFileSync to load my payload as I also need dynamic path based on the language.

## Problem
It working great for generation (with `nuxt build && nuxt export`), It work also when I first load a page in dev mode (with `nuxt` cmdline), but it's broken when I switch to an other page because it can't access to the required `fs` lib. I got the following error:
```
{"message":"__webpack_require__(...).readFileSync is not a function","statusCode":500}
```
I have to reload the page to show the content which is a bit annoying especially to test page transitions.

## Solution
It could be nice to have a way, maybe an other dev mode, to replace `asyncData` and `fetch` with the preloaded data as in generated mode and keeping hot-loading for the rest of the app.
What do you think about that ?

## Other Solutions
As I can see in #123, I probably can go with two others solutions:
```
  if (process.server) {
    data.authors = JSON.parse(require('fs').readFileSync('../static/data.json', 'utf8'))
  } else {
    data.authors = await axios.get('/data.json').then(res => res.data)
  }
```
which will call axios and I'm afraid I have to included it in my bundle, something I don't want to

OR

I can load my payloads with webpack as the following:
```
import authors from '~/static/data.json'

export default {
  asyncData ({ params }) {
    return { authors }
  }
}
```
But I'm not sure if I can import dynamic path with this solution ? Probably need to dig more into that

Beside of that,  thank's for your hard work 💚

**Comment by manniL** [comment]
Hey 👋 

You can use `fetch` instead of axios to get your JSON files without adding something to the bundle ☺️ 

```js
if (process.server) {
    data.authors = JSON.parse(require('fs').readFileSync('../static/data.json', 'utf8'))
  } else {
    data.authors = await fetch('/data.json').then(res => res.json())
  }
```


Another alternative would be a dynamic `import` (or `require.context`) which works with dynamic paths as well.

As this can be solved in userland, I'm closing here ☺️
