### ISSUE TITLE
Nuxt build time and display time image improvements

### ISSUE THREAD

**Issue by srchulo** [nuxt/nuxt.js#7771]
### Is your feature request related to a problem? Please describe.

It would be great if Nuxt had a built-in, efficient way to optimize and display images.

### Describe the solution you'd like

I think a great is example is the way that [Gridsome](https://gridsome.org/docs/images/) handles images, but here are some ideas that I think would be great:

- Optimize images to make them more efficient for size (i.e. pass Lighthouse reports)
- Convert to and use webp/better formats when possible
- Lazy load a srcset of generated srcset images, and then load the best one based on screen size
- Have a blurred placeholder while lazy loading
- Load with intersect observer coming into view, or at least after everything in view has loaded and page is done rendering/executing JS
- Would be very cool if it could somehow work with blogs when rendering markdown that has images (like with @nuxtjs/markdownit), or when using `v-html`.
- Would be great to have a way to do something similar with background images on elements like divs.

### Describe alternatives you've considered

I've spent a lot of time looking for Nuxt plugins/existing solutions for this, but haven't been able to find any that does all that I want to do. I made a solution using [nuxt-lazy-load](https://www.npmjs.com/package/nuxt-lazy-load/v/latest) and [nuxt-responsive-loader](https://www.npmjs.com/package/nuxt-responsive-loader). My solution isn't the best and doesn't do all of the things on the above list, and you need to use require when using it:

```
        <lazy-image
          :src="require('~/assets/images/file.jpg')"
          width="350"
          height="350"
        />
```

There's a [LazyImage](https://github.com/srchulo/nuxt-lazy-images/blob/master/components/LazyImage.vue) component, and my attempt at a [LazyWrapper](https://github.com/srchulo/nuxt-lazy-images/blob/master/components/LazyWrapper.vue) to serve as a generic HTML element that can have a lazy background. LazyWrapper also has issues, because the `background-image` src is set before the image downloads, so it flashes and the blurred preview goes away.

Here's my repository:

https://github.com/srchulo/nuxt-lazy-images

And here's a live demo of the repository:

https://objective-kilby-cec1bf.netlify.app/

### Additional context

I couldn't find any existing feature requests for something like this, but I think it would be very cool if something like this was this easy in Nuxt!

**Comment by Azurewarth0920** [comment]
@srchulo 

I think the [lazyload attribute](https://caniuse.com/#feat=loading-lazy-attr) for img tag will help you.

**Comment by danielroe** [comment]
Off the top of my head, there are a number of packages you might consider, and I think there are others too:
* https://gitlab.com/broj42/nuxt-lazy-load
* https://github.com/regenrek/nuxt-lazyimage
* https://github.com/juliomrqz/nuxt-optimized-images
* https://github.com/geeogi/nuxt-responsive-loader

**Comment by srchulo** [comment]
@danielroe thanks! I looked at all of those (in fact my solution above that I put together uses two of those), but I found that it took me a lot of time/reading to set up and get right, some of them don't work together at all, some were not easy to install and get right, and no one of those provided what I think would be the complete optimized image handling experience. I feel that I had to do a lot of research on what that would be and then try to combine them to get it.

It was challenging, took a lot of time, and I don't think that I did a great job :) This is why I think it would be really great if smart people working on Nuxt who are really familiar with web technologies thought about this, took care of edge cases, and made it really simple for people using Nuxt to get a great experience out of the box.

**Comment by srchulo** [comment]
I just used [this article](https://dev.to/ignore_you/minify-generate-webp-and-lazyload-images-in-your-vue-nuxt-application-1ilm) along with this [nuxt-lazysizes-aspect-ratio-blur](https://github.com/regenrek/nuxt-lazysizes-aspect-ratio-blur) repository to get a little closer to what I want (a component that takes care of most of the optimized image work for you), and I still made a [fork and some changes](https://github.com/srchulo/nuxt-lazysizes-aspect-ratio-blur/commit/848a703b22634515d58e957c77a477b588ef90f9) to get the image component to be a little better. It would be nice if Nuxt had an official solution, as it's a lot of work to combine these, and probably still not ideal unless you know what you're doing (I don't!) :)
