### ISSUE TITLE
`nuxt-edge` doesn't respect targets in generation

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.js#7774]
### Versions

- nuxt: v2.14.0-26582020.6ab65fbf
- node: v12.18.1

### Reproduction

https://github.com/danielroe/nuxt-edge-preset

### Steps to reproduce
1. `yarn nuxt generate`
2. `cd dist && grep -RH '=>'`

### What is expected?

No arrow functions should be present in `dist/_nuxt` JS files.

### What is actually happening?

Non-transpiled content is present - and if terser is disabled (as a debugging step) this can be seen in great detail.

**Comment by danielroe** [comment]
Regression introduced in c5a446557297b735103f322b83df74efc189734d.

**Comment by pi0** [comment]
Thanks @danielroe. I can confirm the bug it is happening because we moved .nuxt to node_modules which is ignored by default.

**Comment by danielroe** [comment]
@pi0 👍 Want a PR or are you on it?
