### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by benemohamed** [nuxt/nuxt.js#7777]
### Versions

- nuxt: v2.13.3
- node: v10.22.0

![Screenshot from 2020-07-26 15-55-05](https://user-images.githubusercontent.com/49129795/88482356-9f01fa00-cf58-11ea-9ea8-ff8682514524.png)

### Steps to reproduce

An upgrade  from v2.0.0 to v2.13.3 leads to this error !.

It crashed in the
```javascript
if (Component.options && Component._Ctor === Component) {
```
.nuxt/App.js

```javascript
const layouts = { "_BasicLayout": sanitizeComponent(_c174f1bc),"_default": sanitizeComponent(_6f6c098b),"_menu": sanitizeComponent(_2d26b655),"_PageHeaderLayout": sanitizeComponent(_666f685c),"_UserLayout": sanitizeComponent(_2494092a) }

```
### What is Expected?

Working like version v2.0.0

### What is actually happening?

TypeError

**Comment by aldarund** [comment]
Its impossible to tell without a reproduction.
Try to delete your lock file and node_modules and reinstall

**Comment by benemohamed** [comment]
@aldarund  :+1: :+1:
