### ISSUE TITLE
Nuxt hook not called

### ISSUE THREAD

**Issue by usb248** [nuxt/nuxt.js#7778]
### Versions

- nuxt: latest
- node: v12.18.2

### Steps to reproduce
Just create a module :
```javascript
export default function ShutdownGracefully (moduleOptions) {
  	this.nuxt.hook('close', async (nuxt) => {
	  console.log('closed !')
	})

	this.nuxt.hook('ready', async (nuxt) => {
	  console.log('ready !')
	})
}
```

### What is Expected?
`ready` (when i lauch the app) & `close`(when i kill the app : SIGINT signal) hook should be called

### What is actually happening?
only `ready` is called and not `close` hook (i shutdown my app obviously to test)
`App [app:0] exited with code [1] via signal [SIGINT]`

**Comment by wusongliang** [comment]
+1

How to close the nuxt instance process normally? CTRL + C or kill -9?
