### ISSUE TITLE
asyncData query params always empty

### ISSUE THREAD

**Issue by haykokalipsis** [nuxt/nuxt.js#7779]
So, i'm using static mode with nuxt content. I have asyncData to catch query param of page and load my paginated content, but query params are always an empty object. For example localhost:3000/articles?page=3 

```javascript

async asyncData($nuxt) {
    console.log($nuxt.query) // always an empty object
}
```

**Comment by danielroe** [comment]
@haykokalipsis This is intentional behaviour. See https://nuxtjs.org/blog/going-full-static/#new-config-option-code-target-code-

**Comment by colorfulberry** [comment]
![image](https://user-images.githubusercontent.com/8124046/89368335-d9fcee00-d70d-11ea-9a24-47feb3af2729.png)
change target to server.
