### ISSUE TITLE
Nuxt.js cannot trigger event on some chinese mobile browser (like QQ browser) 

### ISSUE THREAD

**Issue by Knovour** [nuxt/nuxt.js#778]
> All of them are tested by QQ mobile browser through ngrok.

#### index.html
```html
<div id="app"></div>
<script src="https://unpkg.com/vue"></script>
<script>
  new Vue({
    el: '#app',
    template: '<section class="container"><div><button @click="count = count + 1">+</button><span>{{ count }}</span><button @click="count = count - 1">-</button></div></section>',
    data: {
      count: 0
    }
  })
</script>

```
![vue_native_cut](https://cloud.githubusercontent.com/assets/893846/26396037/8958ecc2-40a4-11e7-9ca3-83efcc826e70.gif)

### Use Webpack
`vue init webpack webpack-test`

#### src/App.vue
```vue
<template>
  <section class="container">
    <div>
      <button @click="count = count + 1">+</button>
      <span>{{ count }}</span>
      <button @click="count = count - 1">-</button>
    </div>
  </section>
</template>

<script>
  export default {
    data() {
      return {
        count: 0
      }
    }  
  }
</script>
```
![vue_webpack_cut](https://cloud.githubusercontent.com/assets/893846/26396041/8b1ccaec-40a4-11e7-8d12-fed240485099.gif)

### Nuxt
`vue init nuxt/starter nuxt-test`

#### pages/index.vue

Same code as previous one.

![nuxt_cut](https://cloud.githubusercontent.com/assets/893846/26396042/8cb72d84-40a4-11e7-97c9-a1e326aec363.gif)

**Comment by pi0** [comment]
@Knovour It seems JS bundle is broken and not loaded at all! (similar to #463) 
Please try adding `babel-polyfill` to vendors array.

**Comment by Knovour** [comment]
Already tried, nothing happened.

**Comment by Knovour** [comment]
That tested code seems working now.
But my own project still no luck.

Thank you anyway.

**Comment by ausir0726** [comment]
@Knovour  

I just download QQ browser v9 and init a new nuxt/starter and paste your code .
It's work . ( nuxt 1.0.0-alpha1 )

![qq](https://cloud.githubusercontent.com/assets/7247064/26407211/112da4da-40cd-11e7-9fdf-52cda430a507.gif)

**Comment by Knovour** [comment]
@ausir0726 

I mean mobile browser, not desktop. They are not the same chromium core version.
It is working in test code now (nuxt 1.0.0 alpha 1)
But not working in my project (nuxt 0.10.7)

Both of them have `babel-polyfill` already.

**Comment by ausir0726** [comment]
@Knovour 

I tried download QQ on my S8+ ( android 7 )
downgrade to nuxt.js 0.10.7
without and polyfill

but it's also can work ...

seems like have some issue with android version ?..

![screenshot_20170524-223454](https://cloud.githubusercontent.com/assets/7247064/26408889/91b0e6ae-40d1-11e7-8086-59fa8948f5c6.png)

**Comment by Knovour** [comment]
Same Android version (HTC)
Well, if 0.10.7 working, then it seems it is not an issue in here anymore.

**Comment by ausir0726** [comment]
my personal test on browserstack

nuxt.js without polyfill , minimum is ios >= 8 , android >= 5 .

**Comment by Knovour** [comment]
My project has over 30 bundles, I'm not sure that is the problem or not.

**Comment by ausir0726** [comment]
@Knovour 

I also have 30 bundles , It's use nuxt 0.10.7
I tried on my QQ browser , it have CSS rwd issue , but can work on your issue .
https://nitori.demo.finpo.com.tw/test

can  you try this ?

**Comment by Knovour** [comment]
Looks good.
Seems I have to do a heavy refactor now.

Thank you anyway.

**Comment by Knovour** [comment]
I use `Intl.NumberFormat` to format number to dollar string, but QQ mobile browser doesn't support this function. And [polyfill.io](https://polyfill.io) cannot recognize what browser is this, so it send an empty polyfill to the browser.

Now I use [accounting.js](http://openexchangerates.github.io/accounting.js/) instead, and it goes well this time.

Sorry for bothering.
