### ISSUE TITLE
Module from npm written in ES6

### ISSUE THREAD

**Issue by dodas** [nuxt/nuxt.js#779]
When I import an module from npm (node_modules) which is written in ES6 (and has .es6 file extension), this module is probably not transpiled by babel. This works OK in dev mode, but when I run `yarn build`, UglifyJS throws an error, probably because it does not understand non-transpiled es6 syntax. Should I somehow modify configuration so babel does transpile .es6 files in node_modules?

thanks.

**Comment by egoist** [comment]
Maybe you're looking for https://nuxtjs.org/api/configuration-build#extend

**Comment by dodas** [comment]
@egoist Thanks, I know about this option and I actually tried to use it like this:
```
extend (config, ctx) {
  config.module.rules.push({
    test: /\.es6$/,
    loader: 'babel-loader'
  })
}
```

but it doesn't seem to have any effect.

**Comment by muhajirframe** [comment]
Having the same problem. did you fix this @dodas ?

**Comment by Atinux** [comment]
@dodas what node module are you using which is using .es6 files?

**Comment by dodas** [comment]
@muhajirframe No, I did not.
@Atinux this one: https://www.npmjs.com/package/googlemaps-js-rich-marker

**Comment by Atinux** [comment]
I believe my answer there could help you @dodas https://github.com/nuxt/nuxt.js/issues/924#issuecomment-309417199

You can update the babel-loader to add also `.es6` with `.js` and add exlude googlemaps-js-rich-marker into the exclude regexp.

**Comment by dodas** [comment]
@Atinux could you help me with writing such regex?
I tried this: `babelLoader.exclude = /node_modules\/.+?\/.+?\.js$/`
(exclude files ending with .js from node_modules)
with no success.

thanks.

**Comment by muhajirframe** [comment]
Hi @dodas ,
like @atinux said you can try to modifier snippet mentioned #924 
Maybe this one will work, not sure.
```javascript
...
  build: {
    extend: function (config) {
      const babelLoader = config.module.rules.find((rule) => rule.loader === 'babel-loader')
      babelLoader.exclude = /node_modules\/(?![googlemaps-js-rich-marker])/
      babelLoader.test = /\.(js|es6)$/
    }
  },
...
}
```

**Comment by dodas** [comment]
@muhajirframe thanks, but no, this does not work. I don't understand why Atinux has put "get-urls" inside character class (square brackets). When I replace "get-urls" with "googlemaps-js-rich-marker", node quits with error saying `Invalid regular expression: /node_modules\/(?![googlemaps-js-rich-marker])/: Range out of order in character class`.

Also, I would like to universally transpile every .es6 module from node_modules, not just `googlemaps-js-rich-marker`.

**Comment by muhajirframe** [comment]
Yeah, in my case it's not [get-urls] too, it's (get-urls) after researching a little bit about regex.

**Comment by dodas** [comment]
Ah yes, that would work.
This is what I ended up doing to transpile all files with .es6 extension:

```
{
  build: {
    extend: function (config) {
      const babelLoader = config.module.rules.find(rule => rule.loader === 'babel-loader')
      const babelLoaderEs6 = Object.assign({}, babelLoader, { exclude: undefined, test: /\.es6$/ })
      config.module.rules.push(babelLoaderEs6)
    }
  },
}
```

**Comment by homerjam** [comment]
I'm trying to use @dodas snippet above but getting an error: `Unexpected token import`

The targets should cause the `.es6` file to be transpiled correctly but it doesn't seem to be happening for some reason. Any ideas where I'm going wrong? (Assuming it's something obvious)
