### ISSUE TITLE
[SEO Optimization] Huge LCP(Largest Content Paint) on Full Static rendering html with v-html

### ISSUE THREAD

**Issue by ricardobt** [nuxt/nuxt.js#7794]
### Versions

- nuxt: v2.13.0
- node: v12.18.0
- target: static
- mode: universal

### Reproduction

We've created a blank rep with different ways to render the html to showcase the problem. IMO this is critical because it's super hard to optimize websites on mobile and get a rating over 90.

Sandbox: https://admiring-cray-777be5.netlify.app/
Rep: https://github.com/made2web/dummy

<details open>
<summary>Additional Details</summary>
<br>

https://admiring-cray-777be5.netlify.app/ -> Simple component
https://admiring-cray-777be5.netlify.app/functional/ -> Functional component
https://admiring-cray-777be5.netlify.app/static -> With the html directly on the component (this is not a solution)
https://admiring-cray-777be5.netlify.app/content/ -> Using nuxt-content component
https://admiring-cray-777be5.netlify.app/lazy/ -> Using lazy-component
https://admiring-cray-777be5.netlify.app/static-render/ -> Using [Nuxt Static Render Package](https://www.npmjs.com/package/nuxt-static-render) (we lose the nuxt-link ability)

</details>

### Steps to reproduce
Main issue is that when we try render a bigger html node or multiple nodes when the payload takes action it's counting like a new writting.
We've managed to get better results with nuxt static render package, but then the nuxt-link function doesn't work.

Using [Page Speed Insights](https://developers.google.com/speed/pagespeed/insights) (mobile) and Performance on Dev Tools you can see that despite the content is there from the beggining, both tools consider that the LCP is way latter than it really is.

### What is Expected?
No content as changed, so we don't need to hydration/write again. Payload should understand that, specially on the above the fold content.

### What is actually happening?
Payload is writting again the content. It's taking 2/3 times longer than it should. 

Simple Component
Page Speed Insights: https://mrkr.io/s/5f1ff6b9711cd17c08c51a73/0
Dev Tools: https://mrkr.io/s/5f1ff8fae713a45033ee018a/0

Functional Component
Page Speed Insights: https://mrkr.io/s/5f1ff744d4c6e47c65975be9/0
Dev Tools: https://mrkr.io/s/5f1ff8bd123b4b7c52b2ee9b/0

Static Component (no v-html)
Page Speed Insights:  https://mrkr.io/s/5f1ff753123b4b7c52b2ee93/0
Dev Tools: https://mrkr.io/s/5f1ff8cad4c6e47c65975bed/0

Nuxt Content Component
Page Speed Insights: https://mrkr.io/s/5f1ff7662e67e07c07fb35d6/0
Dev Tools: https://mrkr.io/s/5f1ff8d7d4c6e47c65975bee/0

Lazy Component
Page Speed Insights: https://mrkr.io/s/5f1ff7cbb418f75038d81a7e/0
Dev Tools: https://mrkr.io/s/5f1ff8cadcdbf37b8d71b41c/0

Static Render
Page Speed Insights: https://mrkr.io/s/5f1ff7d7e713a45033ee0183/0
Dev Tools: https://mrkr.io/s/5f1ff8ca711cd17c08c51a7d/0

Thanks in advance and congrats for the amazing work!

**Comment by danielroe** [comment]
The reflow is caused by the fact that the CSS styles for container, title, subtitle and links are not being injected into the HTML on `/content`.

**Comment by ricardobt** [comment]
@danielroe i've updated the rep and removing all the css made nuxt-content work like expected!

But still, shouldn't v-html achive the same result? If we want to use an external API like Strapi or Directus we can't use in an easy way the nuxt-content, because we would need to generate a lot of json and md files.
