### ISSUE TITLE
router guard error causes SSR request to never complete

### ISSUE THREAD

**Issue by matthieusieben** [nuxt/nuxt.js#7798]
### Versions

- nuxt: v2.14.0
- node: v14.5.0

### Reproduction

https://codesandbox.io/s/inspiring-nash-hknkc?file=/plugins/router-error.js

According to `vue-router` [navigation guards documentation](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards), the `next()` function can be called with an error.

However, calling `next()` with either an `error` or `false` during SSR will cause the server never to respond.

Here are the attempts I made:

<details>
<summary>Using `next(err)`</summary>

```js
export default function plugin({ app, error }, inject) {
  app.router.beforeEach(async (to, from, next) => {
    try {
      await someAsyncTask()
      next()
    } catch (err) {
      next(err) // Will cause the server to hang indefinitely
    }
  })
}
```
</details>
<details>
<summary>Using `onError`</summary>

```js
export default function plugin({ app, error }, inject) {
  app.router.onError(error) // Will cause the server to hang indefinitely
}
```
</details>

<details>
<summary>Using `next(false)`</summary>

```js
export default function plugin({ app, error }, inject) {
  app.router.beforeEach(async (to, from, next) => {
    try {
      await someAsyncTask()
      next()
    } catch (err) {
      next(false) // Will cause the server to hang indefinitely
      error(err) // Does nothing
    }
  })
}
```
</details>

<details>
<summary>Workaround</summary>

```js
export default function plugin({ app, error }, inject) {
  app.router.beforeEach(async (to, from, next) => {
    try {
      await someAsyncTask()
    } catch (err) {
      error(err)
    } finally {
      next() // The route will still be loaded, but never shown...
    }
  })
}
```
</details>

### Steps to reproduce
```js
export default function plugin({ app, error }, inject) {
  app.router.beforeEach(async (to, from, next) => {
    next(new Error("Some async error"));
  });
}
```

### What is Expected?
Nuxt should handle vue-router navigation errors (esp. during SSR)

### What is actually happening?
Nuxt does not handle router errors, causing the requests to hang indefinitely

**Comment by pi0** [comment]
Should be fixed with [v2.14.1](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.1)
