### ISSUE TITLE
[2.14.0] Static Payload not applying to <nuxt-child> children components in some cases

### ISSUE THREAD

**Issue by FreekVR** [nuxt/nuxt.js#7799]
May be related to #7791

Nuxt payloads do not always apply correct in generated apps with `target: static`, if `nuxt-child` is used, and both a child component of the higher-level component, and one of the children of `nuxt-child` implement `fetch()` (see diagram below)
### Versions

- nuxt: 2.14.0
- node: 10.23.0

### Reproduction
Source: https://github.com/FreekVR/nuxt-static-repro/tree/nested-fetch-issues

Demo: https://wonderful-ardinghelli-e41a6b.netlify.app/magazine/category/bar/

This will have correctly generated data on first (hard) load, but clicking the link-links present on the page will show that in SPA mode, the payload data is not applying afterwards.

This seems to be caused by the fetch() in [this component](https://github.com/FreekVR/nuxt-static-repro/blob/nested-fetch-issues/components/sidebar.vue), which is included in the nuxt-child parent component.

### Steps to reproduce
Have an application implementing a structure like below (see repro source for practical implementation)

![image](https://user-images.githubusercontent.com/417416/88689764-2edfa980-d0fb-11ea-8e58-51949be04a53.png)

### What is Expected?
Data is correctly applied from the payload when navigating through SPA links

### What is actually happening?
Data is not applied / lost

**Comment by f3ltron** [comment]
Same error here

**Comment by honzabilek4** [comment]
I can confirm the issue, same behaviour as stated in description. 
The page is generated correctly, even the payload data exist, but when navigating using `<nuxt-link>` the nested fetch hook is not being invoked.

**Comment by elisiondan** [comment]
Until this issue is resolved, we've opted for calling `fetch` in `beforeMounted` hook which seems to work properly with the static target.
```
  async fetch () {
    // fetching data
  },
  async beforeMount () {
    await this.$fetch();
  }
```

**Comment by FreekVR** [comment]
I can confirm that this issue still persists with the latest release, unfortunately.

**Comment by agursoy** [comment]
I also faced this bug. Is there any update?

**Comment by FreekVR** [comment]
Issue is still occurring with the latest versions, unfortunately.

**Comment by JustinRvt** [comment]
I'm so much following this as I'm experiencing the same issues.

For me, it appears that some variables are fetched, like {{article.name}} but if want to more in depth like {{article.image.formats.large.url}} I'll get a undefined on formats unless it as a parameter. Which works until I refresh and break everything to an apollo error 400.

Kind of annoying :/

**Comment by danielroe** [comment]
Closed in https://github.com/nuxt/nuxt.js/pull/8466. Would appreciate testing via `nuxt-edge` to confirm fix.
