### ISSUE TITLE
Dash in layout filenames

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#78]
If layout component file name contains special characters, this leads to incorrect `App.vue`  generation:
as an example: (`layouts/docs-components.vue`)
```js
let layouts = {
  _docs-components: process.BROWSER_BUILD ? () => System.import('...docs-components.vue') : require('...docs-components.vue'),
}
```

This throws syntax errors. keys can be easily quated to avoid this problem.

**Comment by Atinux** [comment]
It's now fixed in the [`v0.9.4`](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.4).

Thank you for your contribution @pi0
