### ISSUE TITLE
Reverse proxying into nuxt app sub-path

### ISSUE THREAD

**Issue by imfaisalkh** [nuxt/nuxt.js#7804]
I'm trying to serve nuxt behind [Caddy](https://caddyserver.com/). This is my `Caddyfile`:

```
app.lvh.me {
    encode gzip
    reverse_proxy 127.0.0.1:80
}

dashboard.lvh.me {
    encode gzip
    rewrite * /private{uri}
    reverse_proxy 127.0.0.1:80
}
```

When I visit `app.lvh.me` it works fine, when I visit `app.lvh.me/private` it still works fine (thus the path is valid). But when i visit `dashboard.lvh.me` (which is essentially being proxied to the same path e.g. `/private` above) it does not work.

In this case the HTML is being loaded but the page resources like JS are throwing 404 error and the page shows a loading animation continuously. (see images below)

https://imgur.com/2VCOKE4 (HTML is loaded, loading icon spinning)
https://imgur.com/KVHQUtw (JS files are not being loaded)

Proxying to a sub-path like this works with other apps like `express` but is not working for `nuxt` app. I wonder if there is some issue.

**Comment by imfaisalkh** [comment]
@pi0 Can you please look into this issue?

**Comment by farnabaz** [comment]
It is expected behavior since you are rewriting URLs to `/private{uri}`, You are changing URLs of static files too and it ends with 404.
For example `app.js` is located in `_nuxt/static/[some-random]/app.js` but after your rewrite Caddy will request `private/_nuxt/static/[some-random]/app.js` from Nuxt. This file does not exists and it leads to 404

Remove `/private` prefix from URLs with `_nuxt` prefix and all static files(png, jpg, gif, ...).

**Comment by imfaisalkh** [comment]
@farnabaz Thanks very much for getting back to me. I've a hard time figuring out this issue. As per your advice I've added another rewrite rule specifically for `'/_nuxt/` folder but it does not seem to work either. JS files are still throwing 404 error. My `Caddyfile` now looks like this:

```
dashboard.lvh.me {
    encode gzip
    rewrite * /private/{uri}
    rewrite /_nuxt/ /{uri}
    reverse_proxy my_app:80
}
```

**Comment by imfaisalkh** [comment]
So, I've had help from `caddy` team and I've modifed my `Caddyfile` as following:

```
http://dashboard.lvh.me {
    encode gzip
    @not_nuxt not path /_nuxt*
    rewrite @not_nuxt /private{uri}
    reverse_proxy 127.0.0.1:80
}
```

This now works partially, in a sense that JS files are now loading just fine. However, instead of loading the `/private` path as expected, it is loading the `/` path (see image: https://ibb.co/v3HMs1N)

Can you please tell me what else could be the issue here? @farnabaz
