### ISSUE TITLE
Runtime config is not used for <head> in nuxt.config.js

### ISSUE THREAD

**Issue by ceilfors** [nuxt/nuxt.js#7817]
### Versions

- nuxt: v2.14.0
- node: 12.18.0

### Reproduction

1. Create a new nuxt.config.js
2. Update nuxt.config.js to have `head` attribute that is trying to use runtime config

```js
export default {
  mode: "universal",
  target: "static",
  publicRuntimeConfig: {
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
  },
  head: {
    script: [
      {
        src: `https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAPS_API_KEY}&libraries=places`,
        defer: true,
      },
    ],
  },
```

<details open>
<summary>Additional Details</summary>
<br>
We're encountering this issue as we're trying to adopt the new runtime configuration. There is a long discussion in #5100 about how many `nuxt.config.js` should be able to be built once as a context.

There is also a similar problem in the `auth` module which can be found at nuxt-community/auth-module#713, but I felt that `<head>` should be supported by Nuxt out of the box.
</details>

### Steps to reproduce

1. Set GOOGLE_MAPS_API_KEY environment variable to `ABC` (from .env file, or by bash `export`)
2. `nuxt generate`
3. Set GOOGLE_MAPS_API_KEY environment variable to `XYZ` (from .env file, or by bash `export`)
4. `nuxt generate`

### What is Expected?

In step number 4:
- Nuxt will detect that the build has been created before, so it will proceed with static pages generation
- Generated static page should have `XYZ` API key

### What is actually happening?

In step number 4:
- Generated static page stays as `ABC`

**Comment by hojas** [comment]
+1

**Comment by rlalak** [comment]
+1

**Comment by rlalak** [comment]
+1

**Comment by alessandroniciforo** [comment]
+1 Same use case here

**Comment by fabioscmelo** [comment]
+1

**Comment by dbarjs** [comment]
+1

**Comment by bagaskarala** [comment]
+1
is there any workaround to load runtime config env to head property?

**Comment by bagaskarala** [comment]
+1
no workaround yet?

**Comment by nmackey** [comment]
+1

This would make builds much easier as many different assets are used across different deployments.
