### ISSUE TITLE
Set title dynamically

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#782]
As we always see, notifications can be show in title,  so when I get the unread notifications  count form API, I want to show this count in title , like:

`(2)page title`

But the nuxt title is configured, I didn't find the proper way to set it dynamically.

How can I resolve this?

**Comment by motia** [comment]
Hi @bimohxh , you can try this in the top component that shows notifications number.
```
  head () {
    return {
      titleTemplate: `(${this.$store.notificationNumber}) %s`
    }
  },
```

**Comment by bimohxh** [comment]
@motia Thanks! this works, just put this to `layouts/default.vue`

**Comment by ATUL1995** [comment]
what about the description can we update that dynamically.
Dynamically means on each search meta title and description will update.
