### ISSUE TITLE
Bundle/page size much larger in production than in development

### ISSUE THREAD

**Issue by marcoschwartz** [nuxt/nuxt.js#7824]
I just started to use Nuxt for my app (switching over from a pure HTML frontend), and I am seeing a much larger page/bundle size in production compared to on my local computer in dev mode (1.26 MB vs 176 kb). 

I am using DigitalOcean behind CloudFlare + PM2. I am trying with the same page in the app, same data, etc. I am not sure if it is a bug or something I did wrong, but it seems strange that the page size is nearly 10x larger in production. Thanks!

**Comment by danielroe** [comment]
@marcoschwartz First check you are comparing a local production build and not just the dev server. You can run `yarn build --analyze` to get a breakdown. If you are still encountering an issue, it would be great if you could provide a minimal code reproduction.
