### ISSUE TITLE
Babel Errors in nuxt generate 2.14

### ISSUE THREAD

**Issue by minyou9** [nuxt/nuxt.js#7826]
When I used nuxt generate for my project, I got this error when building:

`[BABEL] Note: The code generator has deoptimised the styling of  \node_modules\bootstrap-vue\src\icons\icons.js as it exceeds the max of 500KB.`

Anyone has any insights of this?

**Comment by danielroe** [comment]
@minyou9 This isn't an error as such, but it's letting your know that you're including a huge amount in your bundle and should consider optimising what you import into your project.

**Comment by minyou9** [comment]
> @minyou9 This isn't an error as such, but it's letting your know that you're including a huge amount in your bundle and should consider optimising what you import into your project.

**Comment by minyou9** [comment]
@danielroe thank you for your suggestion. This warning error has been resolved
