### ISSUE TITLE
Issue in adding `pages/app.vue` file.

### ISSUE THREAD

**Issue by ooookai** [nuxt/nuxt.js#7829]
### Versions

- nuxt: v2.14.0
- node: v10.21.0

### Reproduction

- A GitHub repository that can reproduce the bug
https://github.com/ooookai/nuxt-app-_-

### Steps to reproduce
1. run `yarn install`.
2. add an `app.vue` file in the `/pages/`.
3. run `yarn dev`, it works.
4. run `yarn generate`, everything looks good in the terminal.
5. run `yarn start`, the page is always in loading status.
6. and then you open the `/dist/index.html`, you can't see any .js file there.
7. if you remove the file `app.vue`. it works again.

**Comment by pi0** [comment]
Hi @ooookai. This issue should be fixed with `2.14.1` you can try with `nuxt-edge` before release

**Comment by farnabaz** [comment]
@ooookai as Pooya said this is fixed. I've tested your repo with `2.14.1` and it works.
