### ISSUE TITLE
Cannot read property 'public' of undefined

### ISSUE THREAD

**Issue by MiKr13** [nuxt/nuxt.js#7834]
# Cannot read property 'public' of undefined

### Versions
- nuxt: v2.14.0

### Reproduction
- npm run start

### What is Expected?
Server is running but on navigating to website getting this error:
![image](https://user-images.githubusercontent.com/34394719/89118198-34553f00-d4c1-11ea-8166-439e07d7ab50.png)
No page is opening

The corresponding line number has this code: 
![image](https://user-images.githubusercontent.com/34394719/89118222-623a8380-d4c1-11ea-9196-d32c1b487083.png)

### What is actually happening?
Getting error.

**Comment by farnabaz** [comment]
Could you create a reproduction sample?

**Comment by earthaYan** [comment]
This happened to me too，is there any solution?
After I ran the command, different file server.js  were generated between my fiend and me ,

**Comment by ThreeFiveSevenWords** [comment]
I also had this situation，There is no problem for others to pack and deploy，Should be related to local environment，I haven't found a reason yet，Do you have any solving experience？

**Comment by ThreeFiveSevenWords** [comment]
I solved it,I compared dependence，Too high version of nuxt results in

**Comment by MiKr13** [comment]
@ThreeFiveSevenWords can you please describe how you solved it again? Will be helpful to me. Thanks in advance
