### ISSUE TITLE
Middleware loop

### ISSUE THREAD

**Issue by JanisPocis** [nuxt/nuxt.js#7840]
Got problem with nuxt middleware, tryd to reproduce it on sandbox, but it just crashed
Link to example - https://codesandbox.io/s/nervous-tree-zivu8?file=/pages/index.vue
Problem is when index page trigger profile button, middleware start infinite loop.

**Comment by rchl** [comment]
You are redirecting from `/profile` to `/profile` in a constant loop. What else do you expect to happen?

**Comment by JanisPocis** [comment]
Why does it loop, but don't stop when redirect to profile?
Do i need to manually check it?

**Comment by rchl** [comment]
middlewares run on navigation and you are triggering navigation with `redirect` call.
