### ISSUE TITLE
When I Nuxt build, it contains ES6 code in vendors.js！

### ISSUE THREAD

**Issue by lingliMr** [nuxt/nuxt.js#7847]
### Versions

- nuxt: v2.13.0
- node: v12.4.0

### Reproduction

![image](https://user-images.githubusercontent.com/25763495/89292686-53a1c700-d68f-11ea-967b-603c5e358f09.png)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
in nuxt@1.0+ is normal
Other documents are normal ，only vendors.js contains ES6.

### What is Expected?
no es6

**Comment by pi0** [comment]
Hi @lingliMr. This is expected behavior since vendors from `node_modules` are ignored for babel transpile. You can whitelist the ones that need transpilation: https://nuxtjs.org/api/configuration-build/#transpile

**Comment by pi0** [comment]
Update: From screenshot i guess it is `query-string package` thus this should do the trick:

```js
  build: {
    transpile: [ 'query-string' ]
  }
}
```
