### ISSUE TITLE
CSP from nuxt.config.js return only empty string in meta tag

### ISSUE THREAD

**Issue by sangdth** [nuxt/nuxt.js#7852]
### Versions

- nuxt: v2.14.0
- node: v12.16.3

### Reproduction

<details open>
<summary>Additional Details</summary>
My nuxt.config.js
<br>

https://codesandbox.io/s/flamboyant-meadow-henmm?file=/nuxt.config.js

</details>

### Steps to reproduce
1. I follow this guide: https://nuxtjs.org/guides/configuration-glossary/configuration-render#csp
2. Initiate Nuxt.
3. Edit nuxt.config.js with:
```
render:
    csp: {
      addMeta: true,
      policies: {
        // ..... a lot config
      },
    },
},
```

3. Go to the link and see problem: 
https://henmm.sse.codesandbox.io/
```
Refused to load the script 'https://sse-0.codesandbox.io/client-hook-3.js' because it violates the following Content Security Policy directive: "script-src ". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
### What is Expected?
Completed Content security policy string will be injected into meta tag.

### What is actually happening?
Only a white space added into the tag.
`<meta http-equiv="Content-Security-Policy" content="script-src ">`

**Comment by farnabaz** [comment]
> Note that CSP hashes will not be added if `script-src` policy contains `'unsafe-inline'`. This is due to browser ignore 'unsafe-inline' if hashes are present. Set option `unsafeInlineCompatibility` to true if you want both hashes and 'unsafe-inline' for CSPv1 compatibility.

Based on [docs](https://nuxtjs.org/guides/configuration-glossary/configuration-render#csp) if you want to support CSPv1 update `csp` object and add  `unsafeInlineCompatibility: true`
```js
render:
    csp: {
      addMeta: true,
      unsafeInlineCompatibility: true,
      policies: {
        // ..... a lot config
      },
    },
},
```


PS. I close the issue, feel free to reopen the issue or ask any question

**Comment by sangdth** [comment]
I have tried EVERY COMBINATION of those options, turn on/off every single one and check before I opened this issue. It does not change the problem.

Please.

**Comment by bepsvpt** [comment]
It seems `addMeta` only adds `script-src` to `Content-Security-Policy` `meta` tag.

https://github.com/nuxt/nuxt.js/blob/v2.14.3/packages/vue-renderer/src/renderers/ssr.js#L235-L238
