### ISSUE TITLE
Install and running nuxt with yarn 2 results in a "Fatal Error"

### ISSUE THREAD

**Issue by zoford** [nuxt/nuxt.js#7857]
### Versions

- nuxt: v2.14.1
- node: v14.5.0

### Reproduction

[**Nuxt-yarn2-bug**](https://github.com/zoford/nuxt-yarn2-bug)

### Steps to reproduce
1. Install yarn by following by following [this](https://yarnpkg.com/getting-started/install) guide.
2. Install nuxt with `yarn add nuxt`.
3. Run nuxt in dev mode with `yarn nuxt` or by adding `"dev": "nuxt"` under scripts in the package.json.

### What is Expected?
The nuxt application runs on http://localhost:3000.

### What is actually happening?
The command returns:
```
Nuxt Fatal Error
Error: Cannot import module '@nuxt/core'
```

**Comment by pi0** [comment]
Hi @zoford. the current version of nuxt is not supporting yarn2 because it needed multiple internal changes that could cause breaking change. Nuxt3 will have proper support for cherry :)

**Comment by zoford** [comment]
That's what I thought. Thanks!
