### ISSUE TITLE
Render function or template not defined in component

### ISSUE THREAD

**Issue by kamran-12** [nuxt/nuxt.js#7858]
I have seen many people with this error online, but they are making mistakes I don't do (I think), such as importing plugin inside .vue file, or using multiple root tags in template. This is possibly an error from my side, but even then, I'd say there is a nuxt bug there too, because it cannot explain to me what mistake I made.

### Steps to reproduce
extract the archive: [fr.zip](https://github.com/nuxt/nuxt.js/files/5028512/fr.zip)
npm install
npm run dev
open localhost:3000

### What is expected?
See the webpage I partially designed

### What is actually happening?
error: "render function or template not defined in component: MainLayout"
it was giving other components' names instead "MainLayout" in previous, very similar versions.
I am not sure but what I am remembering is that it all started after I deleted node_modules folder and re-installed it.

**Comment by farnabaz** [comment]
Do not use `require` to load components. It is recommended to use `import`.  
But if you want to use `require` you should use `default` property to access components. For example inside `index.vue`

```js
export default {
    components: {
		MainLayout: require('../layout/main').default // <--- default is important
    }
}
```

I close the issue, feel free to reopen it or ask any questions
