### ISSUE TITLE
Nuxt adding vuetify-theme-stylesheet on page with vuetifymodule.

### ISSUE THREAD

**Issue by artmarydotir** [nuxt/nuxt.js#7859]
### Versions

- nuxt:  v2.14.1
- node: v12.18.3

### Reproduction
![style tag here](https://user-images.githubusercontent.com/11363931/89415214-cdde5400-d740-11ea-87b5-f0adae281092.png)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Hi, im using **nuxt v2.14.1** and **nuxt-vuetify-module v1.11.2"** 
im getting this extra style tag everywhere.
i saw this as an issue before in past year, but all the issues are closed now, and some of them said its fixed, i saw the merge file too.
this a merged file link: [merged](https://github.com/vuetifyjs/vuetify/pull/7443/files/1d28d72e6a476431135d0c72a525f2cf2fb1cd91)
but this wasnt fixed and i found this link too: [jousepo thinks find the bug source](https://github.com/vuetifyjs/vuetify/pull/7443#issuecomment-508480537)

these are all i found, and im not sure where to open the issue.
and still having this problem.
will you please guide me to fix my problem?
tnx.
 
### What is Expected?
expected a clean html , no extra style tag.

### What is actually happening?
adding a large style tag to every page.

**Comment by AllanChain** [comment]
Though the large style block is annoying, I don't think this is a bug.

Vuetify renders this stylesheet by design (vuetifyjs/vuetify/issues/3329, vuetifyjs/vuetify/pull/2486). The mentioned PR is about **duplicated** theme stylesheet id.

**Comment by yanivduke** [comment]
hi, 
I'm getting the same "extra style tag" - EST problem.
extractCSS on build works fine! 
the EST in my case includes only v-application classes.
An interesting phenomenon is that the EST is not consistent - 
after fast double or triple refresh, the EST was not rendered.

**Comment by yanivduke** [comment]
![applyVueMeta23](https://user-images.githubusercontent.com/29441261/99148560-03c09c00-2691-11eb-91b4-2808079862a6.png)
my workaround for the problem is to comment the applyVueMeta23() call -> after build update .nuxt/dist/server/server.js

**Comment by 1alireza32109** [comment]
Well, you have access to take action yourself to make a rendering, and if
you don't have access, please say to open access to the action thank you.

در تاریخ شنبه ۱۴ نوامبر ۲۰۲۰،‏ ۱۷:۲۴ Yaniv Dukhan <notifications@github.com>
نوشت:

**Comment by danielroe** [comment]
This seems to be an issue that should be raised directly with https://github.com/vuetifyjs/vuetify..
