### ISSUE TITLE
how to trigger error.vue (from layouts) with self made error ?

### ISSUE THREAD

**Issue by MatthieuHPP** [nuxt/nuxt.js#786]
hi,

The error.vue page (layouts directory) is triggered to errors coming from the back or front-end.

I am trying to trigger this error.vue page to an Error that I throw myself from the store. Here is the code extracted from the action I am testing :

```
// One action of the Store
new_error_message({error_message}){
function NewError(error_message) {
      this.name = 'NewError'
      this.message = error_message || 'Error happened'
      this.stack = (new Error()).stack
    }
    NewError.prototype = Object.create(Error.prototype)
    NewError.prototype.constructor = NewError

 throw new NewError()
}
```
Once thrown, this Error is seen in the console but it does not trigger the error.vue page.   
What should I do to trigger these self made errors ?

Help will be much appreciated :-)

Matthieu

**Comment by motia** [comment]
Hello @MatthieuHPP , You can use `this.$nuxt.error` or `this.$root.error` :)

**Comment by MatthieuHPP** [comment]
Many thanks Motia. So simple that it should work ! I will test this in a few hours

**Comment by MatthieuHPP** [comment]
@motia. 2 min to make it works from a page :-)
 I did not manage to make make it works in store, nuxt or root are undefined. But the way to handle error in Nuxt is not verbose so the need of the store is this case does not seem relevant.
Many thanks !

**Comment by motia** [comment]
Glad I could help :)
