### ISSUE TITLE
Placing development directories in production should be configurable

### ISSUE THREAD

**Issue by YnkDK** [nuxt/nuxt.js#7861]
### Is your feature request related to a problem? Please describe.

When running `nuxt generate` a file placed in `dist/_nuxt/node_modules/commons.[hash].js` is created. When deploying to Cloudflare Workers Site any directory and it's sub-content in [`node_modules` is ignored](https://developers.cloudflare.com/workers/tooling/wrangler/configuration/). Including it into Cloudflare breaks the application, so the only work-around I have found is to manually move `commons.[hash].js` out of the `node_module` directory and refactor all references to that file. This is error-prone and cumbersome work to do every time.

### Describe the solution you'd like

Either being able to control where `commons.[hash].js` should be placed or have a property flag placing it directly inside the `_nuxt` directory. This could be configurable as a property to `generate` inside `nuxt.config.js`.

### Describe alternatives you've considered

Writing a PowerShell (or similar) script that can be run before deploying to Cloudflare Workers Site that does the moving and replacement.

### Additional context

After this has been implemented it should be fairly straight forward to contribute to your documentation of how to deploy to Cloudflare Workers Site.

**Comment by maximilianschmid** [comment]
Same on netlify.com. dist/_nuxt/node_modules/commons.[hash].js is generated, but ignored by netlify CDN.

**Comment by donatelloraphael** [comment]
Same problem with Firebase and NuxtJS v2.14.1 with `nuxt build`. Downgraded to NuxtJS v2.14.0 and there is no node_modules folder in the build folder and everything works again.

**Comment by dwsmart** [comment]
Same issue if you use app,yml to push to a google app engine, the node_modules/ files in dist are ignored.

**Comment by dwsmart** [comment]
As a quick note, editing your `.gloudignore` file and changing:

```
# Node.js dependencies:
node_modules/
```
to:
```
# Node.js dependencies:
/node_modules/
```
Does address this. Naturally node_module folders in anything other than the root would be uploaded, but that's probably not a big concern for most?

**Comment by rclement** [comment]
Can confirm the same issue on Vercel (static deployment) using full static mode.
The file `dist/_nuxt/node_modules/common.[hash].js` is ignored, thus breaking all client-side dynamic behavior.
Adding `!_nuxt/node_modules/` in `.vercelignore` does not fix the issue.

Issue since Nuxt.js 2.14.1. Reverting to Nuxt.js 2.14.0 fixes the issue.

**Comment by rclement** [comment]
FYI, updating to Nuxt.js [2.14.2](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.2) (and 2.14.3) fixed this issue by reverting placing `common.js` to `vendor` directory instead of `node_modules`.

Main issue is #7901
