### ISSUE TITLE
Wrong routes generated for trailingSlash=true case

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#7864]
### Versions

- nuxt: v2.14.1 (regression in this version)
- node: v12.18.2

### Reproduction

https://codesandbox.io/s/nuxt-trailingslash-true-and-child-routes-1xw40?file=/nuxt.config.js

<details>
<summary>Nuxt configuration</summary>

```
  router: {
    trailingSlash: true
  },
```

</details>

<details>
<summary>Routes configuration</summary>

```
  routes: [{
    path: "/posts/",
    component: _ad4aa402,
    pathToRegexpOptions: {"strict":true},
    name: "posts",
    children: [{
      path: "",
      component: _19067942,
      pathToRegexpOptions: {"strict":true},
      name: "posts"
    }, {
      path: ":slug/",
      component: _174fd7fa,
      pathToRegexpOptions: {"strict":true},
      name: "posts-slug"
    }]
  }, {
    path: "/",
    component: _00cac37e,
    pathToRegexpOptions: {"strict":true},
    name: "index"
  }],

  fallback: false
}
```

</details>

Directory structure:
![Screenshot 2020-07-31 at 13 40 45](https://user-images.githubusercontent.com/153197/89031783-76507a80-d333-11ea-93ba-4ede0340b5b9.png)

### Steps to reproduce

Do a SSR request to /posts/

### What is Expected?

- the child `index` route is rendered
- there are no VueRouter warnings in the console

### What is actually happening?

 - Navigating to `/posts/` loads the `:slug` child route.
 - There are VueRouter warnings triggered in the console:

```
[vue-router] Named Route 'posts' has a default child route. When navigating to this named route (:to="{name: 'posts'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead. 
[vue-router] Duplicate named routes definition: { name: "posts", path: "/posts/" } 
```

@manniL @farnabaz @pi0

**Comment by rchl** [comment]
Related case for trailingSlash=false: #7823

**Comment by farnabaz** [comment]
I believe warnings are very clear. You have created a duplicate route. Let's list pages and routes  

```
- index.vue    ---> /
- posts.vue    ---> /posts/
- posts
  - _slug.vue  ---> /posts/:slug/
  - index.vue  ---> /posts/
```
It isn't right to create both `posts.vue` and `posts/index.vue` when `trailingSlash = true`

**Comment by rchl** [comment]
I'm not sure about that because the routes in the `posts` directory are child routes and rendered through `router-view` element.

Try https://codesandbox.io/s/nuxt-trailingslash-true-and-child-routes-2-t4rq4?file=/pages/posts/_slug.vue where I've added:
```js
  router: {
    trailingSlash: true,
    extendRoutes(routes) {
      for (const route of routes) {
        if (route.children && route.name) {
          delete route.name;
        }
      }
    }
  },
```
to fixup routes (remove `name` from the parent route).
It works fine to open `/posts/` path in that one and there is no warning.

**Comment by farnabaz** [comment]
> to remove `name` from the parent route. It works fine to open `/posts/` (it loads child `index.vue` route) path in that one and there is no warning.

You're right, the duplicate error is related to route name, this line https://github.com/nuxt/nuxt.js/pull/6594/files#diff-1288a325a940f45fdc5707e5485c442aR75 is the reason.  
see https://github.com/nuxt/nuxt.js/issues/7823#issuecomment-669857733

**Comment by rchl** [comment]
That line is for the `trailingSlash=false` case though.

**Comment by farnabaz** [comment]
Look at line https://github.com/nuxt/nuxt.js/pull/6594/files#diff-1288a325a940f45fdc5707e5485c442aR71, 
```js
const indexRoutePath = trailingSlash === false ? '' : '/';
const defaultChildRoute = route.children.find(child => child.path === indexRoutePath);
const routeName = route.name;
if (defaultChildRoute) {
  if (trailingSlash === false) {
    defaultChildRoute.name = route.name;
  }
  delete route.name;
}
```
By changing `false` into `true` value of `defaultChildRoute` becomes truthy and `route.name` will delete.  

@manniL What do you think?

**Comment by vanling** [comment]
Just encountered the same issue here, everything was fine before, now a lot of warnings on all nuxt-child component routes since i've turned on  trailing slashes.

**Comment by rchl** [comment]
keep it open

**Comment by rchl** [comment]
It is fixed. Thanks!
