### ISSUE TITLE
jsx nested elements not render

### ISSUE THREAD

**Issue by Hamidrezana** [nuxt/nuxt.js#7865]
I try using typescript and I want to use render method to be able using jsx, but it is not working with nested elements:

Here `p` is not rendered.
```
import { Vue, Component, Prop } from "vue-property-decorator";

@Component
export default class MyComponent extends Vue {
	@Prop({ default: "TypeScript!" }) readonly name!: string;
	message: string = "Hello, ";
	render(h: Vue.CreateElement): Vue.VNode {
		return (
			<div>
				<p>{this.message}</p>
			</div>
		);
	}
}
```

Here `p` rendered.

```
import { Vue, Component, Prop } from "vue-property-decorator";

@Component
export default class MyComponent extends Vue {
	@Prop({ default: "TypeScript!" }) readonly name!: string;
	message: string = "Hello, ";
	render(h: Vue.CreateElement): Vue.VNode {
		return (
		  <p>{this.message}</p>
		);
	}
}
```

### Versions

- nuxt: 2.13.0
- node: 12.17.0

**Comment by farnabaz** [comment]
Please provide a reproduction sample on codesandbox

**Comment by Hamidrezana** [comment]
@farnabaz I've create my project with typescript-nuxt and I'm not good with webpack to configure it manually to work with decorators.

**Comment by Hamidrezana** [comment]
I add `"jsx": "preserve",` to `tsconfig.json` and problem solved.
