### ISSUE TITLE
`Reference Error` when customize the `router.parseQuery` in nuxt.config

### ISSUE THREAD

**Issue by dum3ng** [nuxt/nuxt.js#7866]
### Versions

- nuxt: v2.14.1 
- node: v12.17.0 

### Reproduction

https://codesandbox.io/s/quirky-raman-db0i0?file=/nuxt.config.js

</details>

### Steps to reproduce

Run the project in above link.

### What is Expected?

```js
import qs from 'query-string'

export  default {
  router: {
    parseQuery(q) { return qs.parse(q) }
}
}
```

Customized `parseQuery` should work.

### What is actually happening?

The console output that the `qs` is not defined, 
and on my local dev machine, this cause an error and the page just can not load.

**Comment by manniL** [comment]
You have to require `qs` directly in the function, e.g. `parseQuery(q) { return require('qs').parse(q) }` to make it work.

**Comment by dum3ng** [comment]
> You have to require `qs` directly in the function, e.g. `parseQuery(q) { return require('qs').parse(q) }` to make it work.

OK, that work.

Seems that nuxt just drop the content into generated `router.js` file, and the import statement outside does not work.
