### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@vue%2fbabel-preset-jsx - Not found

### ISSUE THREAD

**Issue by epsy-me** [nuxt/nuxt.js#7869]
npm install

![image](https://user-images.githubusercontent.com/67442521/89521750-c2466800-d7e8-11ea-94fb-81ea704fe888.png)

What could be the problem?

### Versions

- nuxt: v2.14.0

**Comment by danielroe** [comment]
@epsy-me This is not a Nuxt issue. There are currently issues accessing npmjs.com and installing scoped packages.

https://status.npmjs.org/incidents/cksjqc1w11v5?u=yjqzk11ky282
