### ISSUE TITLE
Error: store/index.js should export a method which returns a Vuex instance

### ISSUE THREAD

**Issue by FuchsbergerTbs** [nuxt/nuxt.js#787]
When I activate the Vuex store as it is shown on the official website I get an error that the index.js file within the store folder should export a method which returns a Vuex instance.

<img width="940" alt="bildschirmfoto 2017-05-25 um 20 04 00" src="https://cloud.githubusercontent.com/assets/23220690/26463892/1c99428e-4186-11e7-975e-2c337ec1e67d.png">
<img width="800" alt="bildschirmfoto 2017-05-25 um 20 04 41" src="https://cloud.githubusercontent.com/assets/23220690/26463895/1eabf698-4186-11e7-93cd-e4da27c59d21.png">
<img width="838" alt="bildschirmfoto 2017-05-25 um 20 05 25" src="https://cloud.githubusercontent.com/assets/23220690/26463901/224d4ef0-4186-11e7-8bf8-187c58ab775f.png">

**Comment by pi0** [comment]
Please see #754 for 1.0.0 breaking changes :)

**Comment by pi0** [comment]
@FuchsbergerTbs What's your IDE ? :D It looks beautiful :))

**Comment by FuchsbergerTbs** [comment]
Oh, I see, well thank you :D

I'm basically using Atom with the core theme One Light as the UI Theme as well as for the Syntax Theme and for the font I switched to Heimat Mono. I've also installed the file-icons package for the nice file extension icons (as a designer I'm a little obsessed with good looking interfaces haha ;D )

**Comment by acidjazz** [comment]
https://github.com/nuxt/docs/pull/145
