### ISSUE TITLE
@nuxtjs/markdownit should use nuxt-link for relative links

### ISSUE THREAD

**Issue by srchulo** [nuxt/nuxt.js#7875]
I think it would be great if `@nuxtjs/markdownit` used `<nuxt-link>` for relative links, maybe like how [nuxt/markdown](urhttps://github.com/nuxt/markdown/blob/5e5a9806b75a5cf5e6682418a1eeeb25f68c1baa/src/handlers/link.jsl) does it.

**Comment by srchulo** [comment]
Ah, maybe this explains it:

https://github.com/nuxt-community/modules/issues/185

But all of the links posted here no longer work. Would be nice if this was handled automatically.

**Comment by danielroe** [comment]
@srchulo Could you raise an issue there instead, if https://github.com/daliborgogic/nuxt-interpolation doesn't solve the issue for you?

**Comment by srchulo** [comment]
@danielroe that did it, thank you!
