### ISSUE TITLE
Multiple Layout Directories

### ISSUE THREAD

**Issue by kaldenswart** [nuxt/nuxt.js#7879]
At the moment it is possible to override what directory nuxtjs looks for layout components in as demonstrated below:
```js
//nuxt.config.js

export default {
    ...,
    dir: {
        layouts: 'custom_dir/layouts'
    }
}
```

It would be useful in some scenarios to be able to specify multiple directories, for example:
```js
//nuxt.config.js

export default {
    ...,
    dir: {
        layouts: [
            'custom_dir/layouts',
            'other_custom_dir/layouts'
        ]
    }
}
```

Then when specifying a layout in a page component, it should check the first directory for the layout and if it can't be found it will check the next directory.

This could also be useful for having layouts in both the application itself as well as from other modules. Alternatively, a method of creating additional layouts that could be loaded from modules could be useful.

**Comment by pi0** [comment]
Hi @kaldenswart actually it will be supported natively by nuxt3 for all auto scanned directories (see rfc: https://github.com/nuxt/nuxt.js/pull/5818/files)

Meanwhile you might use `this.addLayout` with a nuxt module or symlink from different directories.

**Comment by kaguya3222** [comment]
@pi0 Hello! I'm sorry for directly tagging you, but can you provide a short example of how to add layout using `this.addLayout` ?

**Comment by AlexanderBuzz** [comment]
> @pi0 Hello! I'm sorry for directly tagging you, but can you provide a short example of how to add layout using `this.addLayout` ?

This may be old, but whoever stumbles upon this, might mage use of the following snippet:

```javascript
import { Module } from '@nuxt/types';
import path from 'node:path';

const nuxtModule : Module = function myModule() {

  const moduleDir = path.dirname(url.fileURLToPath(import.meta.url));

  this.addLayout({
    src: path.resolve(moduleDir, 'layouts/plain.vue'),
    name: 'plain'
  })

};
export default nuxtModule;
```
