### ISSUE TITLE
asyncData doesn't binding the model

### ISSUE THREAD

**Issue by fortil** [nuxt/nuxt.js#788]
Hi guys

I have the next enviroment:
```
/pages/
-------/_slug
-------------/index.vue
-------------/_slug.vue
-------/search
---------------/_slug.vue
```
I have a _menubar_ in layout `default.vue` that searches the entries. When I search any word I make a `this.$router.push('/search/' + words)` in the code, next, in `/search/_slug.vue` I get the slug as `params.slug` in `asyncData `and search in store entries related with these words.

```
<template>
  <div>
    <strong class="display-1">Buscando.... {{slug}}</strong>
    <v-divider class="my-2 indigo" style="height: 3px"></v-divider>
    <Entradas :entradas="entries" />
  </div>
</template>
<script>
:
:
async asyncData ({params, store}) {
    let entradas = await store.dispatch('entries/searchEntries', params.slug)
    console.log(entradas)
    return {
      slug: params.slug,
      entries: entradas
    }
  },
```
But at the first time, it shows me all entries that match with the _store_, but when I continue writing more words (searching), the slug of the navigator keep changing (`params.slug`), `entradas` also change, but `entries`or `this.entries` in the model stay the same, it happens also with `this.slug`, they doesn't change the template. `asyncData `  isn't reactive.

How can I make reactive these vars?

**Comment by fortil** [comment]
I already resolved it

**Comment by chunge0328** [comment]
How to solve

**Comment by fortil** [comment]
With a computed property. you can get the first data but next step is to use a computed property.
For example:
```
async asyncData () {
  let { data } = axios.get('someurl')
  return {
   data,
   search: '',
  }
},
computed: {
  items () {
    return this.data.filter(e => e.value === this.search)
  }
}
```
And in the template you use `items`. btw, it's by my issue
