### ISSUE TITLE
[2.14.1] vendors~[name].[hash].js files are not generated anymore 

### ISSUE THREAD

**Issue by patrickxchong** [nuxt/nuxt.js#7882]
### Versions

- nuxt: v2.14.1
- node: 

### Reproduction
https://github.com/patrickxchong/nuxt-vuetify-purgecss 

<details open>
<summary>Additional Details</summary>
<br>
Webpack Bundle Analyzer reports can be found here:<br>

- https://github.com/patrickxchong/nuxt-vuetify-purgecss/blob/master/2.14.0-client.html

- https://github.com/patrickxchong/nuxt-vuetify-purgecss/blob/master/2.14.1-client.html

Comparison of build results between v.2.14.0 and v.2.14.1 (portions to note are highlighted in red)
![image](https://user-images.githubusercontent.com/20418855/89751090-4d816f80-db01-11ea-9061-e6c2e5778428.png)
</details>

### Steps to reproduce
Upgrade from nuxt@2.14.0 to nuxt@2.14.1, then run `nuxt build --analyze`

### What is Expected?
Build process code splits vendor files to vendors~[name].[hash].js files (eg. vendors~app.a4ec49a.js)

### What is actually happening?
All vendor modules are clumped into app.[hash].js. 

I suspect that this might have to do with the recent changes to this file: 
https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/client.js

**Comment by patrickxchong** [comment]
I'm a little weirded out why no one else is talking about this problem. Do people not receive warnings that the bundle size is too huge when using Vuetify with Nuxt > 2.14.1? I tested with nuxt@2.14.4 but the problem is still there.

**Comment by pi0** [comment]
Hi @patrickxchong. This regression should be resolved with [v2.14.5](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.5).
