### ISSUE TITLE
Nuxt + Apollo, not possible to have client fetch

### ISSUE THREAD

**Issue by tcastelly** [nuxt/nuxt.js#7883]
### Versions

- nuxt: v2.14.1
- node: v12.18.0

### Reproduction

Use `@vue/apollo-composable` to fetch GraphQL queries. By default the query is emit from Nuxt, without trouble. I would want to emit the query only from the client side by using the `prefetch` option. But I have an infinite pending:
```javascript
const { result } = useQuery(TestQuery, {}, {
  prefetch: false,
});
```

If I replace `prefetch` by `fetchPolicy: 'no-cache'`, a client query is emitted but there is still a query from the server.

### Steps to reproduce
I created a repo to reproduce the problem:
https://github.com/shenron/vue-nuxt-tsx

### What is Expected?
Emit a query from the client part only

### What is actually happening?
Infinite query in pending.

I'm wondering if it's not linked to the '@vue/composition-api` watch lazy by default.

By the way it's seems to not be linked to the [nuxt/composition-api](https://github.com/nuxt-community/composition-api/issues/177), and I have no news from [@vue/apollo-composable](https://github.com/vuejs/vue-apollo/issues/1022)

Thank you for your help.

**Comment by tcastelly** [comment]
By updating to nuxt-edege, it's not working either.

**Comment by tcastelly** [comment]
Same behavior :(

**Comment by danielroe** [comment]
Looks like this is in hand in https://github.com/vuejs/vue-apollo/issues/1022 :slightly_smiling_face:

**Comment by tcastelly** [comment]
Yes :slightly_smiling_face:, I hope ...
It's not really a workaround, but for now I switched to "native" Vue 3 SSR.
