### ISSUE TITLE
Nuxt doesn't work with `spa` mode and `static` target

### ISSUE THREAD

**Issue by munjalpatel** [nuxt/nuxt.js#7886]
**Describe the bug**
When I configure `nuxt` with `typescript` and `spa` with `static` target, app does not load and keeps showing the loading indicator. There are no errors in the console or terminal.

**To Reproduce**
1. `git clone git@github.com:munjalpatel/nuxt-typescript-spa-test.git`
2. `cd nuxt-typescript-spa-test`
3. `npm i && npm run dev`
4. Observe the issue

**Expected behavior**
The `Index` page should properly be displayed.

**Video**
https://www.dropbox.com/s/jh1yl5erswhs9p3/Components%20_%20Nuxt%20TypeScript.mp4?dl=0

**Comment by nekdolan** [comment]
I spent three days trying to debug why my static generated site did not work properly. It almost works so you won't have an issue if you are running yarn dev, but the generated files will be generally incorrect.
None of the official tutorials say anything about this. I have been tearing my hair out. To me it seemed logical that static was closer to a spa and not to a universal app which in my mind was for SSR which requires a server to render it.
