### ISSUE TITLE
Error while deploying static web app 

### ISSUE THREAD

**Issue by ZTF666** [nuxt/nuxt.js#7889]
### issue

So while deploying my app on firebase hosting service , i encountered this error that blocked my app from loading .
the error :  
Loading failed for the <script> with source “https://MYWEBSITE.web.app/_nuxt/node_modules/commons.XXXXXX.js”.

### Versions

- nuxt:  v2.14.0 
- node: v14.6.0 

### Reproduction

Here's a reproduction of the problem in a video : 

https://youtu.be/by4OZxvJWh4

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Create a simple nuxt app 
 mode: 'spa',
  target: 'static',

generate the files then deploy

### What is Expected?
The web app to run normally in production as it is working in dev

### What is actually happening?
Page stuck in loading and error indicating that a certain file failed to load

**Comment by ZTF666** [comment]
How i fixed it : copied the node_modules folder from a working project into the one with the error , generated the app and boom it works .
i just don't know yet what caused the issue in the first place .

**Comment by zerokry** [comment]
Hello @ZTF666 , 
Are you saying you copied your `node_modules` folder into your dist directory?
