### ISSUE TITLE
Error in server with mode develop

### ISSUE THREAD

**Issue by fortil** [nuxt/nuxt.js#789]
Hi guys
In another issue [36](https://github.com/nuxt/express/issues/36), I commented that doesn't work or i don't know how to do for work on mode production.

But now I try run my app in the server on mode develop and doesn't work too. In my PC it works of beautiful.

The error is:
```
* ~/components/index/entradas in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./pages/noticias/index.vue, ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./pages/noticias/tag/_slug.vue and 2 others

To install it, you can run: npm install --save ~/components/index/entradas
```
![image](https://cloud.githubusercontent.com/assets/6068654/26482181/86ea8ede-41ab-11e7-9ec7-c5c91a9ea51b.png)

Thanks

**Comment by alexchopin** [comment]
Hi, `babel` is not installed as production dependencies.
