### ISSUE TITLE
Create New App using Yarn create nuxt-app works in dev mode but fail after being published to firebase hosting

### ISSUE THREAD

**Issue by andyfensham** [nuxt/nuxt.js#7892]
### Versions

- nuxt: v 2.14.1

### Reproduction

Github Repository
https://github.com/andyfensham/NuxtTest214

<details open>
<summary>Template App created using yarn create nuxt-app and npx fails to run in production</summary>

</details>

### Steps to reproduce
Please see all steps to reproduce.
![Snag_11557b1](https://user-images.githubusercontent.com/5065306/89897079-c7d3f180-dbde-11ea-93ce-6e146422f307.png)
![Snag_1158847](https://user-images.githubusercontent.com/5065306/89897095-cf939600-dbde-11ea-8387-cfedaa4653d1.png)
![Snag_115bb7c](https://user-images.githubusercontent.com/5065306/89897118-d8846780-dbde-11ea-9748-19869ca2f462.png)
![Snag_11603b1](https://user-images.githubusercontent.com/5065306/89897142-e1753900-dbde-11ea-9bca-8f4e4a777718.png)
![Snag_11629c7](https://user-images.githubusercontent.com/5065306/89897166-e76b1a00-dbde-11ea-9967-9f8f7994fdef.png)
The demo site created is : https://scadfirebase214.web.app/

### What is Expected?

Site worked in Dev but does not work once uploaded

### What is actually happening?
You can not navigate and the following error appears in the console.
![Snag_1173e82](https://user-images.githubusercontent.com/5065306/89897277-11244100-dbdf-11ea-8498-d898303278fc.png)

**Comment by andyfensham** [comment]
I have managed to isolate the package causing the issue.  It is the "nuxt": "2.14.1", package.  Updating to 2.14.0 resolves the issue.  Not sure what the bug is though.

**Comment by danieledler** [comment]
Thanks, I also got this problem yesterday after updating to 2.14.1, but only on surge.sh so I just filed an [issue](https://github.com/sintaxi/surge/issues/420) there. Good to know that it is not unique to surge.sh.

It works on all other servers I tried (netlify.com, commons.host and a couple of local servers).

**Comment by ZTF666** [comment]
Duude this bug almost drove me crazy , i've been trying to fight it for the past 3 days , opened a  [TICKET](https://github.com/nuxt/nuxt.js/issues/7889) then closed it because i thought it was coming from me ... i fixed it by copying old nuxt project node_modules folder in the new one but that was a temporary fix ..
i can confirm that setting the version of nuxt to  "nuxt": "2.14.0" does fix it

**Comment by lance-anderson** [comment]
I suspect this might be related:
https://github.com/nuxt/nuxt.js/issues/7901

**Comment by ZTF666** [comment]
> 
> 
> I suspect this might be related:
> #7901

that's exactly it !
