### ISSUE TITLE
Problem in production 

### ISSUE THREAD

**Issue by potapovnikita** [nuxt/nuxt.js#7896]
When I’m opening the page on no root route, I’m getting the error “The operation would yield an incorrect node tree.”
![84803109-B086-4038-8CD8-9FA479ECBD3B](https://user-images.githubusercontent.com/20072877/89989544-83a62700-dc9a-11ea-8817-64e080001f85.jpeg)

**Comment by danielroe** [comment]
@potapovnikita I'd need more information, or a code reproduction. That error isn't being generated by Nuxt but by some other code you are using. You might find [this issue](https://github.com/nuxt/nuxt.js/issues/141) helpful, though I realise it's quite specific.

**Comment by potapovnikita** [comment]
i'm can't reproduce it
