### ISSUE TITLE
Runtime config undefined in typescript classes

### ISSUE THREAD

**Issue by nc-guek** [nuxt/nuxt.js#7897]
We are currently trying to get run time config working in our production builds, but are having some issues with getting a hold of the runtime configuration.

### Versions
"dependencies": {
        "@babel/polyfill": "7.8.7",
        "@babel/runtime": "7.9.2",
        "@nuxt/types": "2.14.1",
        "@nuxt/typescript-runtime": "^1.0.0",
        "@nuxtjs/auth": "4.9.0",
        "@nuxtjs/axios": "5.9.7",
        "@types/node-forge": "0.9.3",
        "axios": "0.19.2",
        "bootstrap-vue": "2.10.1",
        "chart.js": "2.9.3",
        "child_process": "1.0.2",
        "convert-array-to-csv": "2.0.0",
        "core-js": "3.6.5",
        "cross-env": "7.0.2",
        "datejs": "1.0.0-rc3",
        "dkfds": "5.3.0",
        "dkfds-plugins": "5.3.0",
        "dotenv-config": "^0.1.1",
        "elasticsearch": "16.6.0",
        "file-saver": "2.0.2",
        "fs": "0.0.1-security",
        "jquery": "3.5.1",
        "js-bbcode-parser": "2.0.2",
        "js-cookie": "2.2.1",
        "jspdf": "1.4.1",
        "jspdf-autotable": "3.5.3",
        "jwt-decode": "2.2.0",
        "module": "1.2.5",
        "node-forge": "0.9.1",
        "nuxt": "2.14.0",
        "nuxt-babel": "1.0.1",
        "nuxt-property-decorator": "2.7.2",
        "pm2": "4.4.0",
        "select-woo": "1.0.1",
        "ts-loader": "6.2.1",
        "ts-throwable": "0.0.7",
        "typescript": "3.8.3",
        "uuid": "8.1.0",
        "vue": "2.6.11",
        "vue-cookies": "1.7.0",
        "vue-fragment": "1.5.1",
        "vue-i18n": "8.15.5",
        "vue-multiselect": "2.1.6",
        "vue-property-decorator": "9.0.0"
    },
    "devDependencies": {
        "@babel/core": "7.9.0",
        "@babel/plugin-proposal-export-namespace-from": "7.8.3",
        "@babel/preset-env": "7.9.5",
        "@nuxt/typescript-build": "0.6.5",
        "@nuxtjs/eslint-config": "2.0.2",
        "@nuxtjs/eslint-config-typescript": "1.0.2",
        "@nuxtjs/eslint-module": "1.1.0",
        "@types/file-saver": "2.0.1",
        "@types/jest": "25.1.4",
        "@types/jquery": "3.3.35",
        "@types/jspdf": "1.3.3",
        "@types/nuxtjs__auth": "4.8.4",
        "@vue/cli-plugin-unit-jest": "4.3.0",
        "@vue/cli-service": "4.3.0",
        "@vue/test-utils": "1.0.0-beta.32",
        "babel-eslint": "10.1.0",
        "babel-jest": "25.2.6",
        "eslint": "6.8.0",
        "eslint-config-prettier": "6.10.1",
        "eslint-friendly-formatter": "4.0.1",
        "eslint-plugin-nuxt": "0.5.2",
        "eslint-plugin-prettier": "3.1.2",
        "eslint-plugin-prettier-vue": "2.1.0",
        "eslint-plugin-vue": "6.2.2",
        "eslint-plugin-vue-a11y": "0.0.31",
        "eslint-plugin-vuejs-accessibility": "0.1.3",
        "husky": "4.2.3",
        "jest": "25.2.7",
        "jest-sonar-reporter": "2.0.0",
        "miragejs": "0.1.35",
        "node-sass": "4.13.1",
        "npm-force-resolutions": "0.0.3",
        "null-loader": "3.0.0",
        "package": "1.0.1",
        "prettier": "1.19.1",
        "requirejs": "2.3.6",
        "sass-loader": "8.0.2",
        "ts-jest": "25.3.1",
        "vue-jest": "3.0.5",
        "vuex-module-decorators": "0.16.1"
    }

### Reproduction
`export SYSTEM_URL="http://test-url.com"`

nuxt.config.js:
`publicRuntimeConfig: { SYSTEM_URL: process.env.SYSTEM_URL }`

test.ts:
```
@Component
export class testEnvPath extends Vue {
     get systemRegistryBaseUrl() {
         if (this.$config !== undefined && this.$config.SYSTEM_URL !== undefined) {
             console.log("Config env")
             console.log(this.$config.SYSTEM_URL)
         }
         throw new Error("SYSTEM_URL is undefined in PATH.");
     }
 }
```

### Steps to reproduce

nuxt build

cross-env NODE_ENV=production nuxt start

### What is Expected?

That we are able to read the environment variable defined in the run time config.

### What is actually happening?
The variable is undefined in the config.

**Comment by aseidma** [comment]
Also encountering this issue currently, did anybody find a workaround? Otherwise, I don't see why this issue is closed.
