### ISSUE TITLE
Optimized @nuxt npm size package 

### ISSUE THREAD

**Issue by MSkred** [nuxt/nuxt.js#7898]
For nuxt 2.13.1 : 3,5M    ./node_modules/@nuxt

For nuxt 2.13.3 :  38M    ./node_modules/@nuxt

Then now I can't deploy my project on AWS Lambda because the zip is too high ... @pi0 @Atinux

**Comment by pi0** [comment]
Hi @MSkred. Actually it would be much better if you directly depend on `@nuxt/core` for lambda deployment. Here is an example: https://github.com/nuxt/vercel-builder/blob/master/src/launcher.ts#L16

According to [package-phobia](https://packagephobia.com/result?p=@nuxt/core] we only had 2MB increases from 2.12 (7.88MB) to 2.13 (9MB) which is lodash dependency i guess (previously partially was being bundled but was afecting startup time with shared deps) t

**Comment by danielroe** [comment]
I have seen no difference in lambda sizes from Nuxt 2.13.1 through to 2.14.1.

**Comment by danielroe** [comment]
I'm closing this as I can't reproduce it, but please feel free to come back.
