### ISSUE TITLE
TypeScript breaks when the Nuxt application is placed in a sub-folder

### ISSUE THREAD

**Issue by jonasolesen** [nuxt/nuxt.js#7899]
### Versions
- nuxt: 2.14.1
- node: 13.x
- typescript: 3.9.5

### Reproduction
The issue can be reproduced simply by creating a new Nuxt application inside a sub-folder of a project. In this case, a Nuxt application has been created inside the _packages/nuxt_ folder as seen in monorepos. A reproduction repository can be found [here](https://github.com/jonasolesen/nuxt-package).

### Steps to reproduce
After setting up a new TypeScript-based Nuxt application or using the provided reproduction repository, the issue becomes apparent when importing a component through an alias or using a property or type unique to Nuxt such as asyncData. Both issues can be reproduced by pasting the code snippet below into a page like index.vue:

```
<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  components: {
    Logo: () => import('@/components/Logo.vue')
  },
  asyncData(ctx) {
    console.log(ctx)
  }
})
</script>
```

### What is Expected?
The aliased module resolution and types are expected to work properly regardless of where the Nuxt application is placed.

### What is actually happening?
Both of the aforementioned break in Webstorm as well as Visual Studio Code. TypeScript throws an error saying that the imported module or its corresponding type declarations cannot be found, and that asyncData does not exist in the ComponentOptions type provided by Vue. The issues only appear in the IDE, however, and the application builds without problems. The issues can also be mitigated by opening the Nuxt application folder directly rather than the top-level project, but this workaround is not ideal in a monorepo when working on multiple packages.

I apologize if this is not directly a Nuxt issue, but the same thing has been tested with a TypeScript-based Vue application generated through the vue-cli without problems. Also, if anyone has successfully set up a TypeScript-based Nuxt application inside a monorepo, I would really appreciate your suggestions!

**Comment by danielroe** [comment]
@jonasolesen There are a couple of things to try. First, make sure that you have correct paths set in your `tsconfig.json` or TS can't resolve imports. Second, as I recall, VS Code has a weird quirk whereby it only properly understands imports in the *first* project in a workspace.

**Comment by jonasolesen** [comment]
@danielroe Thank you for your reply!

I have not changed the paths from what is provided by default:
```
"baseUrl": ".",
"paths": {
  "~/*": [
    "./*"
  ],
  "@/*": [
    "./*"
  ]
}
```
Despite showing an error of not being able to find the module, the IDE (or at least Webstorm) seems to resolve it correctly as seen below:

![image](https://user-images.githubusercontent.com/9108523/90023813-75650480-dcb4-11ea-9a6f-a3afc207d276.png)

Also, the behaviour does not seem to be influenced by shims-vue.d.ts.

I don't know too much about the behaviour of VS Code as I'm mostly using Webstorm. I just checked with VS Code to ensure it wasn't specifically a Webstorm issue. :slightly_smiling_face:

**Comment by danielroe** [comment]
@jonasolesen I don't think this is a Nuxt issue. For VSCode, you need to create a workspace for this to work: https://code.visualstudio.com/docs/editor/multi-root-workspaces. I'm not sure what Webstorm requires but I think it's an editor integration. The fact that there is no type issue when it compiles is revealing...

**Comment by jonasolesen** [comment]
@danielroe You are correct - it is indeed an integration issue. After further testing, it seems like the issue has been introduced in both WebStorm and PhpStorm alongside the [support for Nuxt](https://blog.jetbrains.com/webstorm/2020/07/webstorm-2020-2-beta-2/). When opening the project with an older version of either IDE, everything works as expected. For anyone curious, it can be mitigated by having the Nuxt project as the only project root, which is somehow similar to VS Code workspaces like you suggested. The moment I add an additional project root, the module resolution and declaration merging breaks again.

Thank you for your time, Daniel 🙂 I'm closing the issue.
