### ISSUE TITLE
Multi-srcDir support with same router

### ISSUE THREAD

**Issue by slevp** [nuxt/nuxt.js#790]
I want to create two srcDir for PC and mobile site because i must use same routes(distinguish  by use-agent)，but I don't know how to config my project, so is Nuxt.js support that? thanks.

**Comment by pi0** [comment]
Hi @slevp . Multi `srcDir` is not supported But you may take a look at [dynamic-layouts](https://github.com/nuxt/nuxt.js/tree/dev/examples/dynamic-layouts) example which is designed exactly for such use cases :)
