### ISSUE TITLE
Version 2.14.1 generates common.js inside of dist/_nuxt/node_modules

### ISSUE THREAD

**Issue by lance-anderson** [nuxt/nuxt.js#7901]
### Versions

- nuxt: v2.14.1
- node: v12.18.3

### Steps to reproduce
1. Upgrade a Nuxt project to latest 2.14.1
2. Run `yarn generate`

### What is Expected?
In v2.14.0, the "commons" javascript file was generated in `dist/_nuxt/commons/`

![image](https://user-images.githubusercontent.com/3789349/90080220-e9a4a580-dcbe-11ea-9c3d-99258ebecc0b.png)

### What is actually happening?
In v2.14.1, the "commons" javascript file is generated in `dist/_nuxt/node_modules/`

![image](https://user-images.githubusercontent.com/3789349/90080262-050fb080-dcbf-11ea-9b30-334da652b166.png)

### The Problem
Generating the commons file inside of `node_modules` conflicts with Nuxt's default `.gitignore` rules which includes: `node_modules`. This is problematic when deploying a static site relies on committing the `dist` folder to a git repo. The end result is a deployed site that is missing the commons file.

### Resolution
This can be resolved by changing the .gitignore rule from: `node_modules` to `/node_modules`. Alternatively, it can be resolve by downgrading to Nuxt v2.14.0. Perhaps it would be ideal if the commons file wasn't placed inside of a folder named "node_modules".

**Comment by pkpowell** [comment]
Changing .gitignore doesn't help if you're deploying to netlify via cli. `netlify deploy` ignores all `node_module` dirs

**Comment by hojas** [comment]
+1

**Comment by mehtaanshul** [comment]
I found the issue, can i pick this @pi0 ?

**Comment by pi0** [comment]
Hi. parent directories (`.nuxt` and `dist`) are also already gitignored. Would you please point to a example netlify deployment (logs and or url) which this issue is happening?

**Comment by pkpowell** [comment]
I inquired about this on the netlify forum.
I got this reply from **fool**, Director of Support 

> It’s not a gitignore, it’s an intentional ignoring benefitting people who (would) accidentally deploy tens of thousands of files in node_modules and slow down their deployment by many minutes while we upload all those accidental files.
I think this is not your situation - you’re doing it with intention, and with a smaller installation, but there is no workaround for the behavior. Our system (when uploading from our CI) optimizes those away for you. Can you use a different pathname than literally node_modules to hold the files?

**Comment by pi0** [comment]
@pkpowell Super thanks for clarification with support :+1: Seems no way other than changing back to `vendors` :no_good:

**Comment by kendalled** [comment]
@pi0 Can you expand on this? Currently facing this same issue and is messing up my builds.

**Comment by kendalled** [comment]
Or at least when is this getting fixed?

**Comment by pi0** [comment]
Fix merged and available with `nuxt-edge` (`2.14.2-26624049.44471ec9`). Releasing 2.14.2 soon.
