### ISSUE TITLE
Please change dependencies vuex in @nuxt/vue-app, @nuxt/vue-app-edge

### ISSUE THREAD

**Issue by hmmhmmhm** [nuxt/nuxt.js#7907]
In some environments with nuxt , there may be
other use of state modules other than vuex.

In my case, I have created and managed a module called [vue-state-store](https://github.com/AhaOfficial/vue-state-store).
Many default modules in nuxt doesn't specified vuex dependencies.

But only exist in @nuxt/vue-app, @nuxt/vue-app-edge,
Currently, the webpack setting of nuxt continues to force vuex into the bundle.

Please change vuex to at least devDependencies.

**Comment by danielroe** [comment]
@hmmhmmhm If you want to avoid `vuex` being in the bundle, simply disable `features.store` and it won't be included.

```js
export default {
  features: {
    store: false
  }
}
```

More info at https://github.com/nuxt/nuxt.js/pull/6287
