### ISSUE TITLE
no response while uploading file with proxy

### ISSUE THREAD

**Issue by aoi-umi** [nuxt/nuxt.js#7911]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
```js
proxy: {
    "/prod": {
      target: config.env.prodHost,
      changeOrigin: true,
      pathRewrite: { "^/prod": "/" }
    }
  },
```
### What is Expected?
upload success and response

### What is actually happening?
waiting until timeout

**Comment by farnabaz** [comment]
Please provide a reproduction project on codesandbox or as a GitHub repo.
