### ISSUE TITLE
Nuxt memory leak universal mode

### ISSUE THREAD

**Issue by WilliamDASILVA** [nuxt/nuxt.js#7915]
### Versions

- nuxt: 2.14.1
- node: 10.16.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

nuxt.config
```js
module.exports = {
  mode: 'universal',
  srcDir: './src',
  server,
  head: {
    title: pkg.name,
    noscript: [{ innerHTML: 'This website requires JavaScript to run properly.' }],
    htmlAttrs: {
      dir: 'ltr'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  css: [
    { src: '@/assets/scss/style.scss', lang: 'scss' }
  ],
  plugins: [
    '~/plugins/vee-validate.js'
  ],
  modules: [
    'nuxt-stripe-module',
    '@nuxtjs/style-resources',
    '@nuxtjs/axios',
    '@nuxtjs/sitemap',
    '@nuxtjs/sentry',
    '@nuxtjs/robots',
    ['vue-wait/nuxt', { useVuex: true }],
    ['@nuxtjs/google-analytics', {
      id: 'UA-TEST'
    }]
  ],
  stripe: {
    publishableKey: process.env.STRIPE_PUBLISHABLE_KEY || ''
  },
  sentry: {
    dsn: process.env.SENTRY_DSN || ''
  },
  sitemap: {
    path: '/sitemap.xml'
  },
  styleResources: {
    scss: [
      'assets/scss/_variables.scss',
      'assets/scss/_mixins.scss'
    ]
  },
  build: {
    transpile: [
      'vee-validate/dist/rules'
    ]
  },
  env: {
    appUrl: process.env.VUE_APP_APP_URL
  },
  axios: {
    baseURL: process.env.API_BASE_URL,
    browserBaseURL: process.env.API_BROWSER_BASE_URL
  },
  tailwindcss: {
    cssPath: '~/assets/css/tailwind.css'
  },
  buildModules: [
    '@nuxtjs/pwa',
    '@nuxtjs/tailwindcss'
  ]
}
```

store.js
```js
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const store = new Vuex.Store({
  state: () => ({}),
  actions: {},
  mutations: {},
  getters: {}
})

export default () => store
```
</details>

### Steps to reproduce

I've build my Nuxt app that uses Vuex, then I sent a certain amount of requests to it, the memory usage keeps growing without coming down. At some point (approx. 4-6 hours in a normal usage, less than a minute during a stress-test), the server crashes because it runs out of memory.

![Capture d’écran 2020-08-13 à 23 05 14](https://user-images.githubusercontent.com/2766008/90187507-2bfedd00-ddba-11ea-9c1c-0d3f7c87405d.png)

> In this screenshot, you can see 2 snapshots. The first one is just after the server started. The second is after a 1 minute stress-test right after

By removing the lines in the `.nuxt/index` and `.nuxt/dist/server/server.js`:

```js
  const registerModule = store.registerModule
  store.registerModule = (path, rawModule, options) => registerModule.call(store, path, rawModule, Object.assign({ preserveState: process.client }, options))
```
Then restarting the server and doing the same stress-test, ***I'm not getting the huge memory leak spike.***

### What is Expected?

I expect the server to live longer than some hours in production, in a real usage. I don't want to restart it everytime it crashes with a balancer to have a good uptime.

### What is actually happening?

I'm getting a huge memory usage and the server keeps crashing.

**Comment by galvez** [comment]
What is the value of `NODE_ENV` on your production environment?

**Comment by WilliamDASILVA** [comment]
@galvez My `NODE_ENV` is `production`. Even if I change the `NODE_ENV` to something else than production, I'm getting the same results.

```
"start:inspect": "NODE_ENV=production node --inspect=0.0.0.0 ./node_modules/nuxt/bin/nuxt.js start"
```

My quick-dirty-bandaid fix/workaround was to remove the usage of the `registerModule` by adding a new plugin that would delete that function, since I'm quite sure I'm not using it anywhere.

```js
/**
 * Bandaid to resolve the issue with store.registerModule
 * since we're not using registerModule anywhere.
 */
export default ({ store }) => {
  delete store.registerModule
}
```

The same test with my workaround:

![Capture d’écran 2020-08-14 à 02 12 33](https://user-images.githubusercontent.com/2766008/90199091-febf2880-ddd3-11ea-8aff-b4a49c76e468.png)

**Comment by galvez** [comment]
@WilliamDASILVA should be fixed in latest Nuxt release.
