### ISSUE TITLE
Build stuck when work on ubuntu

### ISSUE THREAD

**Issue by nothinggift** [nuxt/nuxt.js#793]
Nuxt.js version 0.10.7
Node.js version 7.10
I used koa templete to build app, It's works well on windows, When i deploy the project to the server and run build, It's always stuck in 91%, No error message, And dev mode works well, How can i debug this?

**Comment by pi0** [comment]
@nothinggift You may have to await on nuxt constructor if upgraded to 1.0.0-alpha . (#754)

**Comment by nothinggift** [comment]
Well...

**Comment by pi0** [comment]
@nothinggift Is your problem resolved?

**Comment by nothinggift** [comment]
Yes, I downgrade Node.js to 6.10 and reinstall all dependencies, And then work properly.
But it's also stuck in 91% for a long time.

**Comment by chengwudji** [comment]
@nothinggift  I have the same problem,  Is your problem resolved?  My nuxt.js version 0.10.6

**Comment by nothinggift** [comment]
@chengwudji 已经确认了问题，是因为服务器剩余内存不足。

**Comment by chengwudji** [comment]
@nothinggift  我也在查，发现服务器4g内存 刚不住
