### ISSUE TITLE
FATAL  Nuxt build error: 1:10 Module '"../../../@types/globby"' has no exported member 'GlobbyOptions'.

### ISSUE THREAD

**Issue by guoxiangke** [nuxt/nuxt.js#7931]
All works on local, but when building in docker for production

### Versions

"nuxt": "^2.14.3",
 node: 10

[package.json](https://github.com/guoxiangke/wechaty-nuxt/blob/master/package.json)
[Dockerfile](https://github.com/guoxiangke/wechaty-nuxt/blob/master/Dockerfile)

### Reproduction
docker-compose up --build

### What is actually happening?
An error occurs at npm run build : 

![image](https://user-images.githubusercontent.com/1160703/90346318-7acaa200-e05a-11ea-94f6-f2e203b95540.png)

```
ERROR in /usr/src/app/node_modules/@nuxt/types/config/generate.d.ts
ERROR in /usr/src/app/node_modules/@nuxt/types/config/generate.d.ts(1,10):
1:10 Module '"../../../@types/globby"' has no exported member 'GlobbyOptions'.
  > 1 | import { GlobbyOptions } from 'globby'
      |          ^
    2 |
    3 | /**
    4 |  * NuxtOptionsGenerate

 FATAL  Nuxt build error

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5544:21)
  at process._tickCallback (internal/process/next_tick.js:68:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯
```

**Comment by pi0** [comment]
Hi @guoxiangke i guess you are using an outdated version of [@nuxt/types](https://github.com/nuxt/nuxt.js/blob/dev/packages/types/config/generate.d.ts#L1) (latest is `2.14.0` similar to `nuxt` version). Some setup steps are also updated please see here https://typescript.nuxtjs.org/guide/setup.html

**Comment by BobGneu** [comment]
I am seeing the same issue. I can confirm that the versions of `nuxt` and `@nuxt/types` are equal to `^2.14.3` and when running `generate` I receive the same message, as above. 

I am also seeing it when I just start the dev server, but it does not block the build. 

> As I have looked deeper, it seems that globby includes its own types and the file up on the @types listing is a stub to redirect back to source.

**Comment by pi0** [comment]
Hi @BobGneu I'm trying to find any references to obsolete `@types/globby` but out of luck (at least for above reproduction). Would you please recursively search for `@types/globby` (posix  with `grep -r "@types/globby" .`)

**Comment by BobGneu** [comment]
g'day! 

I see now that I am dealing with a slightly different issue - implicit any. Gonna try to press forward on the problem and may revisit later if I run aground. 

Can confirm I do not have the `@types/globby` referenced anywhere in my tree, but globby is there through Storybook and 3 times through nuxt: 

```
> npm ls globby
test-project@1.0.0 F:\test-project
+-- @storybook/vue@6.0.16
| `-- @storybook/core@6.0.16
|   `-- react-dev-utils@10.2.1
|     `-- globby@8.0.2
`-- nuxt@2.14.3
  +-- @nuxt/cli@2.14.3
  | `-- globby@11.0.1
  +-- @nuxt/components@1.1.0
  | `-- globby@11.0.1
  `-- @nuxt/static@1.0.0
    `-- globby@11.0.1
```

**Comment by BobGneu** [comment]
Just to circle back on this, It looks like that storybook reference was the root of the problem, the older reference to globby was clobbering and explicitly pulling in v11.0.1 appears to have addressed my issue.
