### ISSUE TITLE
params not matching with route

### ISSUE THREAD

**Issue by miteyema** [nuxt/nuxt.js#7935]
### Versions

- nuxt: v2.14.3
- node: v12.16.1

### Reproduction

when using the following directory structure
```
dir: blog/
dir: blog/_country/
dir: blog/_country/_year
file: blog/_country/_year/index.vue
file: blog/_country/_year/_slug.vue
```

and the following content of file `blog/_country/_year/index.vue`

```js
async asyncData({ params }) {
    console.log(params)
}
```

### Steps to reproduce
go to `http://localhost:3000/blog/new-zealand`

### What is Expected?
```
{
  country: 'new-zealand',
  year: undefined,
}
```

### What is actually happening?
```
{
  country: undefined,
  year: 'new-zealand',
}
```

params are not correctly matched with `_params` in folders/files

**Comment by miteyema** [comment]
FYI: this works as expected in `nuxt@2.13.3` and `nuxt@2.14.0` but has stopped working from `2.14.1` onwards

**Comment by farnabaz** [comment]
I believe this is the correct behavior based on your directory structure. 

### Explanations: 
With your structure router will create two routes.
 - `/blog/:country?/:year`
 - `/blog/:country?/:year?/:slug`

On the page `/blog/new-zealand` router matches with first route. As you see `:year` params is required and `:country` is optional, so router use `new-zealand` and `:year` and left `:country` empty

You should create file `blog/_country/index.vue` to handle `/blog/new-zealand` as you expected.

**Comment by miteyema** [comment]
@farnabaz Thanks for that clear explanation.
