### ISSUE TITLE
fetch lifecycle and vue hydration does not work parallely.

### ISSUE THREAD

**Issue by MUMUKSHMEGHWAL** [nuxt/nuxt.js#7936]
### Versions

- "nuxt": "^2.14.0",
- node: Latest

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

1) create any page in nuxt app 
2) Use mode: Universal
3) Create a page as below template 

```
<template>
    <Loader v-if="$fetchState.pending"/>
    <MyPage v-else :pageData="pageData" />
</template> 
```
and Use fetch hook to call api and use below code to render whats coming from API.

Now run build for it. Use npm run dev and when server starts, just refresh the page you will see difference in client side and server side html.
You ca put debugger in vue.runtime.esm.js and check also.

if you wrap  you html code like below: 
```
<template>
  <div>
    <Loader v-if="$fetchState.pending"/>
    <MyPage v-else :pageData="pageData" />
  </div>
</template> 
```

It will solve issue.

### What is Expected?
IT should behave same with or without extra *div*.

### What is actually happening?
It is giving client and serve side html difference which eventually us to append child issue (https://github.com/nuxt/nuxt.js/issues/5800) and this one is hard to debug.

**Comment by farnabaz** [comment]
Please provide a reproduction example on [codesandbox.com](//codesandbox.com)
