### ISSUE TITLE
Layout does not update on page-switch

### ISSUE THREAD

**Issue by l9cgv** [nuxt/nuxt.js#7937]
Hello,
i just discovered an issue I had for a quite long time now for which I couldn't find any solutions.

When I have multiple layouts (e.g. layout1 & layout2) and switch from page1 (with layout1) to page2 (with layout2) with nuxt-link the layouts seems to merge with each other.

Example:

layout1 has background: green on body and layout2 has background: red on body
page1 uses layout1 and page2 uses layout2

when I visit page1 first the background is green
when I visit page2 with nuxt link the background is red
but when I visit page1 with nuxt link from page2 the background keeps red

Is there a way to avoid this issue?

**Comment by danielroe** [comment]
@l9cgv The issue is your CSS is applying to the global context (`body`) so it's 'leaking'. Try applying it just to a class that is only present in the layout you mean to target.

**Comment by l9cgv** [comment]
> @l9cgv The issue is your CSS is applying to the global context (`body`) so it's 'leaking'. Try applying it just to a class that is only present in the layout you mean to target.

oh that makes sense.... well... thank you 😅
