### ISSUE TITLE
Create new FAQ topic

### ISSUE THREAD

**Issue by queses** [nuxt/nuxt.js#794]
Hi!
Now I'm working at commercial project with NuxtJS and I have met a very unhandy issue: site crashes at iOS Safari. I have spent several days trying to resolve this problem, and finally I have found the thing that broked down the whole site - it was a small phone number in the footer. What a suprise, mobile Safari turns all phone numbers it found into a link, like `+7 (982) 536-50-77` renders into `<a href="+7 (982) 536-50-77">+7 (982) 536-50-77</a>`.

I even create an small and useless gist with componet for super lazy coders:
https://gist.github.com/queses/8b008a8b6f7b470cb0a8c5e1788d8c63

I believe it would be great, if you will create the FAQ topic with explanation of this very unoblivious problem.

With best regards!
Maxim Kobozev

**Comment by pi0** [comment]
@queses Which iOS version are you using? I can't reproduce this problem. But if it really exists, we may track/fix original problem in Vue SSR engine.

Also thanks for reporting :)
