### ISSUE TITLE
Dynamic Route always required

### ISSUE THREAD

**Issue by JoseJuan81** [nuxt/nuxt.js#7944]
### Versions

- nuxt: 2.12.2
- node: v10

### Reproduction
these are my routes and `_buscando` is a dynamic one. The problem is that I need to be **no-required** and ***nuxt*** is creating it required.
![Captura de Pantalla 2020-08-19 a la(s) 12 33 04](https://user-images.githubusercontent.com/21971589/90669996-25d48a80-e218-11ea-9c47-7961076b3bc1.png)

### What is Expected?
I expect this result
![Captura de Pantalla 2020-08-19 a la(s) 12 35 14](https://user-images.githubusercontent.com/21971589/90670191-74822480-e218-11ea-8213-c9db4d8149d2.png)

### What is actually happening?
This is what is happening
![Captura de Pantalla 2020-08-19 a la(s) 12 35 02](https://user-images.githubusercontent.com/21971589/90670219-7fd55000-e218-11ea-9422-c15f237d9b72.png)

Note:
is the optional path only posible inside a directory?
![Captura de Pantalla 2020-08-19 a la(s) 12 42 16](https://user-images.githubusercontent.com/21971589/90670853-6ed90e80-e219-11ea-9c29-a1e0778aa821.png)

https://nuxtjs.org/guides/features/file-system-routing#dynamic-routes

**Comment by farnabaz** [comment]
Try again by upgrading nuxt to latest version, 2.14.3.

**Comment by JoseJuan81** [comment]
@farnabaz Hi!, I updated my nuxt version to 2.14.3 but now I have errors when I make `npm run dev`
![Captura de Pantalla 2020-08-24 a la(s) 17 46 18](https://user-images.githubusercontent.com/21971589/91103731-d33d0900-e631-11ea-8aa6-00f1a3c4549e.png)
I don't understand why the error is about status code 401...I'm using axios ^5.3.6, do I need to update this too?

**Comment by farnabaz** [comment]
This might solve by removing `node_modules` in installing deps again.  
Do you have any http call inside nuxt

**Comment by JoseJuan81** [comment]
Yes, I have HTTP calls inside my nuxt config...
![Captura de Pantalla 2020-08-25 a la(s) 10 15 24](https://user-images.githubusercontent.com/21971589/91193179-6b7fd000-e6bc-11ea-8255-615e62c7f994.png)
The last three modules make HTTP calls and the last two are for page dynamic generating.

I removed `node_modules` and install again but the error persist.

**Comment by JoseJuan81** [comment]
@farnabaz for some kind of reason I have troubles width one global variable in my `.env`
My .env variable es kind of `$3y$104$tNJmuXZKGwi0l38A.other-stuff` but then inside my HTTP call modules the value is `undefinedundefined.other-stuff`. I made some test and realise the special character $ is the problematic one.
I don't know if this problem is my error or because the new nuxt version the I just updated
![Captura de Pantalla 2020-08-25 a la(s) 11 25 36](https://user-images.githubusercontent.com/21971589/91201149-b6eaac00-e6c5-11ea-9835-390fd0ab0485.png)
![Captura de Pantalla 2020-08-25 a la(s) 11 26 16](https://user-images.githubusercontent.com/21971589/91201251-d550a780-e6c5-11ea-9376-ea708682b2ea.png)

**Comment by JoseJuan81** [comment]
@felubra updating to nuxt 2.14.3 works. Now the dynamic route is not required like I described in this bug but what is happening with globals variables from `.env` must be solve. I'll create a new bug report for that. I'll close this bug report. Thanks.
