### ISSUE TITLE
 Cannot read property '_isDestroyed' of undefined

### ISSUE THREAD

**Issue by meiqinLiu** [nuxt/nuxt.js#7945]
### Versions

- nuxt:  "^2.0.0",
- node:  “v12.16.2”

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Refresh sub page, page blank

### What is Expected?
It is hoped that the refresh sub page can load normally

### What is actually happening?
Refresh sub page did not load out, and the prompt error
![image](https://user-images.githubusercontent.com/38028974/90714463-4cf39080-e2da-11ea-9f6c-de39f2166548.png)

**Comment by sandra0503** [comment]
Hello @meiqinLiu , we have the same problem in our Nuxt website (SSR). Which plugins are you using?

**Comment by manniL** [comment]
Please provide a proper way to reproduce the bug.

**Comment by pseudo-god** [comment]
I have the same problem

**Comment by danielroe** [comment]
@pseudo-god in that case, would you provide a reproduction? (for example on https://template.nuxtjs.org/)

**Comment by sing-song333** [comment]
me too

**Comment by qxwei** [comment]
did some one fixe it?

**Comment by Tehsurfer** [comment]
Anyone have any more details on this issue?

**Comment by taowenfan** [comment]
It may be the issue in incorrect server config, I change the nginx config that the problem fix.
Before I fix this problem, there are two situation in my project.

1. some page will output `Cannot read property '_isDestroyed' of undefined` in the console and the page content show some error information(may be it is a error page) after I refresh the page
2. it will display the root page in the flash when i jump into other page

and this is the exampel for my nginx config:
```
server {
    listen      80;
    server_name www.xxxx.com;
    root        /data/www/xxxxxxxxxxxxxxxx
    index index.html;

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
        if (-f $request_filename) {
            expires 365d;
            access_log off;
        }
        try_files $uri /app.php$is_args$args;
    }

    location ~ .*\.(js|css)?$ {
        expires 7d;
        access_log off;
    }
}
```
I hope it is useful to those who have this problem

**Comment by niubaobaozsy** [comment]
> It may be the issue in incorrect server config, I change the nginx config that the problem fix. Before I fix this problem, there are two situation in my project.
> 
> 1. some page will output `Cannot read property '_isDestroyed' of undefined` in the console and the page content show some error information(may be it is a error page) after I refresh the page
> 2. it will display the root page in the flash when i jump into other page
> 
> and this is the exampel for my nginx config after I fixed the problem:
> 
> ```
> server {
>     listen      80;
>     server_name www.xxxx.com;
>     root        /data/www/xxxxxxxxxxxxxxxx
>     index index.html;
> 
>     location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
>         if (-f $request_filename) {
>             expires 365d;
>             access_log off;
>         }
>         try_files $uri /app.php$is_args$args;
>     }
> 
>     location ~ .*\.(js|css)?$ {
>         expires 7d;
>         access_log off;
>     }
> }
> ```
> 
> I hope it is useful to those who have this problem
I would like to ask what is the configuration of the core to solve this problem?

**Comment by taowenfan** [comment]
> > It may be the issue in incorrect server config, I change the nginx config that the problem fix. Before I fix this problem, there are two situation in my project.
> > 
> > 1. some page will output `Cannot read property '_isDestroyed' of undefined` in the console and the page content show some error information(may be it is a error page) after I refresh the page
> > 2. it will display the root page in the flash when i jump into other page
> > 
> > and this is the exampel for my nginx config after I fixed the problem:
> > ```
> > server {
> >     listen      80;
> >     server_name www.xxxx.com;
> >     root        /data/www/xxxxxxxxxxxxxxxx
> >     index index.html;
> > 
> >     location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
> >         if (-f $request_filename) {
> >             expires 365d;
> >             access_log off;
> >         }
> >         try_files $uri /app.php$is_args$args;
> >     }
> > 
> >     location ~ .*\.(js|css)?$ {
> >         expires 7d;
> >         access_log off;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope it is useful to those who have this problem
> > I would like to ask what is the configuration of the core to solve this problem?
兄弟，说中文吧，英语不太好，有点看不懂你说啥，我是让运维同事把这段代码配置到nginx就解决了，具体这段代码的意思，我嘚研究一下

**Comment by niubaobaozsy** [comment]
> 
你的问题是必现还是偶现，想知道这些配置是那一段关键逻辑修复了这个问题

**Comment by niubaobaozsy** [comment]
> 你的问题是必现还是偶现，想知道这些配置是那一段关键逻辑修复了这个问题



> > > It may be the issue in incorrect server config, I change the nginx config that the problem fix. Before I fix this problem, there are two situation in my project.
> > > 
> > > 1. some page will output `Cannot read property '_isDestroyed' of undefined` in the console and the page content show some error information(may be it is a error page) after I refresh the page
> > > 2. it will display the root page in the flash when i jump into other page
> > > 
> > > and this is the exampel for my nginx config after I fixed the problem:
> > > ```
> > > server {
> > >     listen      80;
> > >     server_name www.xxxx.com;
> > >     root        /data/www/xxxxxxxxxxxxxxxx
> > >     index index.html;
> > > 
> > >     location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
> > >         if (-f $request_filename) {
> > >             expires 365d;
> > >             access_log off;
> > >         }
> > >         try_files $uri /app.php$is_args$args;
> > >     }
> > > 
> > >     location ~ .*\.(js|css)?$ {
> > >         expires 7d;
> > >         access_log off;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I hope it is useful to those who have this problem
> > > I would like to ask what is the configuration of the core to solve this problem?
> > > 兄弟，说中文吧，英语不太好，有点看不懂你说啥，我是让运维同事把这段代码配置到nginx就解决了，具体这段代码的意思，我嘚研究一下

你的问题是必现还是偶现，想知道这些配置是那一段关键逻辑修复了这个问题

**Comment by taowenfan** [comment]
> > 你的问题是必现还是偶现，想知道这些配置是那一段关键逻辑修复了这个问题
> 
> > > > It may be the issue in incorrect server config, I change the nginx config that the problem fix. Before I fix this problem, there are two situation in my project.
> > > > 
> > > > 1. some page will output `Cannot read property '_isDestroyed' of undefined` in the console and the page content show some error information(may be it is a error page) after I refresh the page
> > > > 2. it will display the root page in the flash when i jump into other page
> > > > 
> > > > and this is the exampel for my nginx config after I fixed the problem:
> > > > ```
> > > > server {
> > > >     listen      80;
> > > >     server_name www.xxxx.com;
> > > >     root        /data/www/xxxxxxxxxxxxxxxx
> > > >     index index.html;
> > > > 
> > > >     location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
> > > >         if (-f $request_filename) {
> > > >             expires 365d;
> > > >             access_log off;
> > > >         }
> > > >         try_files $uri /app.php$is_args$args;
> > > >     }
> > > > 
> > > >     location ~ .*\.(js|css)?$ {
> > > >         expires 7d;
> > > >         access_log off;
> > > >     }
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I hope it is useful to those who have this problem
> > > > I would like to ask what is the configuration of the core to solve this problem?
> > > > 兄弟，说中文吧，英语不太好，有点看不懂你说啥，我是让运维同事把这段代码配置到nginx就解决了，具体这段代码的意思，我嘚研究一下
> 
> 你的问题是必现还是偶现，想知道这些配置是那一段关键逻辑修复了这个问题

请问是很急吗，我现在周末没空，要周一才有空看，不能马上解答你的问题，非常抱歉

**Comment by taowenfan** [comment]
> > 你的问题是必现还是偶现，想知道这些配置是那一段关键逻辑修复了这个问题
> 
> > > > It may be the issue in incorrect server config, I change the nginx config that the problem fix. Before I fix this problem, there are two situation in my project.
> > > > 
> > > > 1. some page will output `Cannot read property '_isDestroyed' of undefined` in the console and the page content show some error information(may be it is a error page) after I refresh the page
> > > > 2. it will display the root page in the flash when i jump into other page
> > > > 
> > > > and this is the exampel for my nginx config after I fixed the problem:
> > > > ```
> > > > server {
> > > >     listen      80;
> > > >     server_name www.xxxx.com;
> > > >     root        /data/www/xxxxxxxxxxxxxxxx
> > > >     index index.html;
> > > > 
> > > >     location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
> > > >         if (-f $request_filename) {
> > > >             expires 365d;
> > > >             access_log off;
> > > >         }
> > > >         try_files $uri /app.php$is_args$args;
> > > >     }
> > > > 
> > > >     location ~ .*\.(js|css)?$ {
> > > >         expires 7d;
> > > >         access_log off;
> > > >     }
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I hope it is useful to those who have this problem
> > > > I would like to ask what is the configuration of the core to solve this problem?
> > > > 兄弟，说中文吧，英语不太好，有点看不懂你说啥，我是让运维同事把这段代码配置到nginx就解决了，具体这段代码的意思，我嘚研究一下
> 
> 你的问题是必现还是偶现，想知道这些配置是那一段关键逻辑修复了这个问题

请问是不是很急，现在周末，暂时没空解答你的问题，只能周一再看，毕竟差不多是半年前的问题，非常抱歉！
