### ISSUE TITLE
Parameter 'fail-on-error' does not work in full static mode.

### ISSUE THREAD

**Issue by sho-zy** [nuxt/nuxt.js#7947]
### Versions

- nuxt: 2.14.3
- node: v12.13.1

### Reproduction

https://github.com/sho-zy/fail-in-full-static

### Steps to reproduce
1. Run $ yarn generate --fail-on-error

### What is Expected?
Command failed with exit code 1.

### What is actually happening?
Command completed normally.
<img width="666" alt=" 2020-08-20 21 11 19" src="https://user-images.githubusercontent.com/12936567/90768536-d5e5e880-e329-11ea-9942-dcd75c90e749.png">

**Comment by pi0** [comment]
fixed by [v2.14.4](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.4)

**Comment by andre-brdoch** [comment]
hey, if an error is thrown in fetch, the build will still succeed: https://github.com/nuxt/nuxt.js/issues/7742

atinux pointed out that it might take some time to fix, but I thought it would be relevant to this issue
