### ISSUE TITLE
TS : Should we publish Types ? 

### ISSUE THREAD

**Issue by rwatts3** [nuxt/nuxt.js#795]
Should we publish index.d.ts to `@types` so others can include it in their package.json dev dependencies ? 

https://github.com/nuxt/nuxt.js/blob/dev/examples/typescript/index.d.ts

**Comment by Atinux** [comment]
Actually I'm not 100% sure about it, maybe @johnlindquist can give us a hint about it.

**Comment by johnlindquist** [comment]
I would follow Vue's lead and include types in the actual project:
https://github.com/vuejs/vue/blob/dev/types/index.d.ts

Even if they only using JS, the types file helps tooling (like VS Code) with hints/navigation/etc.

**Comment by 0pt1m1z3r** [comment]
@Atinux after https://github.com/nuxt/nuxt.js/commit/96cf4a0ec4db0e4a4e4471cf8ba7eb14338eca10 you forgot to add `index.d.js` in package.json "files".

**Comment by Atinux** [comment]
Nice catch @0pt1m1z3r :+1:

**Comment by rwatts3** [comment]
hmm why `index..d.js` ? and not ` index.d.ts`

**Comment by Atinux** [comment]
@rwatts3 fixed, thanks (https://github.com/nuxt/nuxt.js/commit/e967191167665c49bd7221799fded2d8e5d9541a)

**Comment by AndrewBogdanovTSS** [comment]
@Atinux does index.d.ts still present in Nuxt 2? I've installed nuxt-edge 2.0.0-25500158.1b46a95 and I don't see it anywhere in the project

**Comment by Atinux** [comment]
It seems that it disappeared, we could add it back after Nuxt 2 release (or if you feel for a PR, that would be great!)

**Comment by AndrewBogdanovTSS** [comment]
@Atinux I'm ok with waiting till it will be added back in Nuxt 2. Btw, is there any time estimate when Nuxt 2 is going to be released?

**Comment by Atinux** [comment]
Next week @AndrewBogdanovTSS :)

**Comment by AndrewBogdanovTSS** [comment]
Wow! That's awesome! I will open champagne when this happens! 😄

**Comment by dkushner** [comment]
The release date referenced in this thread has come and gone, but it appears that nuxt-edge still does not have TypeScript types available. Is there any chance we can include these as part of a preview, in keeping with the example set by the Vue team?

**Comment by kevinmarrec** [comment]
@Atinux 
> It seems that it disappeared, we could add it back after Nuxt 2 release (or if you feel for a PR, that would be great!)

Any updates on this ? Is it on the RoadMap ?
I created a Feature Request Issue some days ago with a short preview of a proposal to be able to use Nuxt related things like `layout` / `head` around TypeScript @Component Decorator provided by `vue-class-coponent`. #4050 

I didn't have feedback yet so I didn't build a PR yet.

Worth mentionning that my proposal is only for ComponentOptions definitions for now.
