### ISSUE TITLE
Scroll behavior bug

### ISSUE THREAD

**Issue by popescuandrei9mai** [nuxt/nuxt.js#7952]
### Versions

- nuxt: v2.14.3
- node: v12.13.0 

### Reproduction

https://codesandbox.io/s/weathered-sunset-gy8f2

### Steps to reproduce

1) On root route, scroll down to the middle of the page. 
2) Press one of the "render child" links
3) Press "Go back"
4) Scroll the page a bit more
5) Press one of the "render child" links again

### What is Expected?

On the second "render child press, the scroll position on body remains the same when you press a "render child" link the second time

### What is actually happening?

On the second "render child press, the scroll position on body jumps to the location it was when the "render child" link was pressed the first time

**Comment by lttr** [comment]
This is an issue. The main problem is, that the default scroll behavior in Nuxt (and unfortunately in other frontend frameworks) is not the same as if you create a bunch of linked HTML files. Things like custom scroll behavior code are nice, but the defaults should be the same as the web have always been.
