### ISSUE TITLE
Crossorigin on styles not getting set

### ISSUE THREAD

**Issue by perljusback** [nuxt/nuxt.js#7953]
Error on credentials on preload for stylesheets in Chrome 84

![image](https://user-images.githubusercontent.com/3188312/90870339-be464880-e399-11ea-9198-6aeabc73fc19.png)

### Versions

- nuxt: 2.14.3
  Mode: Universal
  Target: Server
- node: 14.6.0

### Reproduction
when using these render settings:
```js
  render: {
    compressor: false,
    crossorigin: 'anonymous',
    http2: {
      push: true
    },
    resourceHints: true
  },
```
crossorigin gets set to the link header and to the preload link in the html:
![image](https://user-images.githubusercontent.com/3188312/90869760-f7ca8400-e398-11ea-93aa-f08a7ec0f405.png)

![image](https://user-images.githubusercontent.com/3188312/90870202-88a15f80-e399-11ea-9a9c-41db17bd658f.png)

but the stylesheet itself doesn't get the crossorigin markup:
![image](https://user-images.githubusercontent.com/3188312/90869871-22b4d800-e399-11ea-966e-e042df5221e5.png)

Looking through the code it seems a replace is done for all the scripts:
https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L23

```js
  renderScripts (renderContext) {
    const scripts = renderContext.renderScripts()
    const { render: { crossorigin } } = this.options
    if (!crossorigin) {
      return scripts
    }
    return scripts.replace(
      /<script/g,
      `<script crossorigin="${crossorigin}"`
    )
  }
```

and if we add a similar one for Styles
```js
  renderStyles (renderContext) {
    const styles = renderContext.renderStyles();
    const { render: { crossorigin } } = this.options;
    if (!crossorigin) {
      return styles
    }
    return styles.replace(
      /<link/g,
      `<link crossorigin="${crossorigin}"`
    )
  }
```
and change:
https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L147
```js
    // Inject styles
    HEAD += renderContext.renderStyles()
```
into
```js
    // Inject styles
    HEAD += this.renderStyles(renderContext);
```
The error goes away

Thanks for all the great work.

**Comment by pi0** [comment]
fixed by [v2.14.4](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.4)
