### ISSUE TITLE
nuxt.js yarn create package not work

### ISSUE THREAD

**Issue by TechComet** [nuxt/nuxt.js#7959]
Hi,

yarn create nuxt-app test12366
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "mongoui > mongoskin@2.0.3" has incorrect peer dependency "mongodb@~2.0".
[4/4] Building fresh packages...
success Installed "create-nuxt-app@3.2.0" with binaries:
      - create-nuxt-app
error Cannot create "/usr/local/bin/create-nuxt-app" due to insufficient permissions.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Comment by sebmellen** [comment]
This is an issue with your folder permissions in linux, not an issue with Nuxt. See [linux.com/training-tutorials/how-manage-file-and-folder-permissions-linux/](https://www.linux.com/training-tutorials/how-manage-file-and-folder-permissions-linux/) for more.

Try creating a new directory like this: `mkdir /home/git/nuxt-project`, then cd into that directory with `cd /home/git/nuxt-project`, and run `chmod 750 .`.

Then run `sudo yarn create nuxt-app test123456`, and it should work. Let me know if you have issues.

**Comment by TechComet** [comment]
It does not need `sudo` to work
I'm sorry
I'm forgot to install nuxt-app .. `yarn global add nuxt-app`

now it's work
`yarn create nuxt-app test123456`

Thank you

**Comment by sebmellen** [comment]
Can you close the issue? Thanks.
