### ISSUE TITLE
Gitter : Contributors Channel/Room

### ISSUE THREAD

**Issue by rwatts3** [nuxt/nuxt.js#796]
Greetings, 

Suggestion for making a nuxtjs/contributors room, for internal discussions and dialog about contributoring to the framework, more like a slack chat for core. I noticed most discussions in the nuxt.js room are related to working with the framework more so than contributing to the framework. 

This would be a good place to keep discussions, so that questions relating to pull requests/ framework related ideas will not bloat the main room.

**Comment by alexchopin** [comment]
Nice idea 👍  https://gitter.im/nuxt/contributors
