### ISSUE TITLE
New Relic Browser Implementation

### ISSUE THREAD

**Issue by jess-ika** [nuxt/nuxt.js#7960]
Hello !

I am trying to implement new relic browser in nuxt, but can't seem to find the right way to do so.

In the new relic docs : [Browser monitoring and the Node.js agent](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/browser-monitoring-nodejs-agent), it is said to call the newrelic server side and put the contents of `newrelic.getBrowserTimingHeader()` in the head of the page.

First I tried to include the script inline in `nuxt.config.js`file in the head property : 
```javascript// nuxt.config.js
import newrelic from 'newrelic'
...

head: {
  script: [{
    innerHTML: newrelic.getBrowserTimingHeader(),
    type: "text/javascript"
  }],
}
```
However, new relic returns an empty script. After searching through new relic docs, the script needs to be inserted in a [transaction](https://discuss.newrelic.com/t/getting-nreum-1-when-using-getbrowsertimingheader/35198/8) (when the client sends a request and the server serves the request)

So, I tried using a plugin : 

```javascript
// nuxt.config.js
...
plugins: [
    { src: '~/plugins/newrelic-browser.js', mode: 'server'}, // server mode because importing newrelic causes error client side
],
```

```javascript
// plugins/newrelic-browser.js
import newrelic from 'newrelic';

export default function (context, inject) {
  let newrelicscript = newrelic.getBrowserTimingHeader();
  
  // returns correctly generated script : 
  // <script type="text/javascript"> new relic script.....</script>
  console.log({ newrelicscript })


  inject('newrelicscript', newrelicscript); // correctly injected, accessible server-side in the context object
}
```

Now I'm trying to access $newrelicscript client side so that i can insert the script manually from my vue components, but can't find it.

I'm trying to access it via `asyncData` method : 

```javascript
asyncData(ctx) {
  console.log({ nr: ctx.app.$newrelicscript }) // undefined
  return {
    nr: ctx.app.$newrelicscript,
  };
}
```

Tried to inject in a middleware and stripping the the script tag : 

```javascript
// middleware/newrelic-browser.js
export default function (ctx) {
  const { app } = ctx;
  if (process.server) {
    console.log({ r: app.$newrelicscript });
    app.head.script.push({
      innerHTML: app.$newrelicscript.replace("<script type='text/javascript'>", '').replace.('</script>', ''), // don`t like this one
      type: 'text/javascript',
    });
    console.log({ head: app.head.script }); // correctly added to the array, but not added in the html page
  }

  /* if (process.client) {
    console.log('client', ctx);
  }*/
}

```

How can I insert the script in a transaction ?
Any help will be greatly appreciated !
Thank you

**Comment by mchagas90** [comment]
any progress?

**Comment by alexeybondarenko** [comment]
@jess-ika I've configured newrelic in nuxtServerInit action, it works fine.

```
async nuxtServerInit(_, context: any) {
    if (context.$config.newRelicLicenseKey) { // used privateRuntimeConfig
      const newrelic = await import('newrelic')
      const cheerio = await import('cheerio')
      newrelic.setTransactionName(context.route.matched[0].path.slice(1))  // use page router pattern as transaction name

      // inject newrelic browser script
      const newrelicScript: string = newrelic.getBrowserTimingHeader()
      const script$: any = cheerio.load(newrelicScript)
      context.app.head.script.push({
        innerHTML: script$('script').html(), // don`t like this one
        type: 'text/javascript',
      })
    }
  },
```

**Comment by danielroe** [comment]
Great 😊

**Comment by JoshKeegan** [comment]
For anyone else that comes accross this, to add to the implementation from @alexeybondarenko, I also needed to prevent the script from being sanitized, which changes the `context.app.head.script.push` at the end to now be:
```js
 _context.app.head.script.push({
  hid: "newrelic",
  innerHTML: innerNrBrowserHtml,
  type: "text/javascript",
});

if (!_context.app.head.__dangerouslyDisableSanitizersByTagID) {
  _context.app.head.__dangerouslyDisableSanitizersByTagID = {};
}
_context.app.head.__dangerouslyDisableSanitizersByTagID.newrelic = ["innerHTML"];
```

**Comment by gedhean** [comment]
I manged to get it working with the following code on `nuxtServerInit`:

```js
// set newrelic on process
let innerNrBrowserHtml = process.newrelic.getBrowserTimingHeader()
const scriptTagRegexp = /(<script.*?>)|(<\/script>)/g
const links = innerNrBrowserHtml.matchAll(scriptTagRegexp)

for (const match of links) {
  innerNrBrowserHtml = innerNrBrowserHtml.replace(match?.[0], '')
}

ctx.app.head.script.push({
  hid: 'newrelic',
  innerHTML: innerNrBrowserHtml,
  type: 'text/javascript',
})

if (!ctx.app.head.__dangerouslyDisableSanitizersByTagID) {
  ctx.app.head.__dangerouslyDisableSanitizersByTagID = {}
}
ctx.app.head.__dangerouslyDisableSanitizersByTagID.newrelic = [
  'innerHTML',
]
```

**Comment by rwaness** [comment]
/* eslint-disable no-param-reassign, no-underscore-dangle */
import newrelic from 'newrelic';

// https://discuss.newrelic.com/t/new-relic-for-nuxt-vue-with-ssr-and-spa/160295/2
export default ({ app, route }) => {
    newrelic.setTransactionName(route.path);

    // newrelic.getBrowserTimingHeader() returns a script with surrounding <script> tag HTML
    const scriptHTML = newrelic.getBrowserTimingHeader();
    if (scriptHTML) {
        const hid = 'newrelic';

        // We must extract the JS source
        const innerHTML = scriptHTML
            .replace(/^<script( [^>]+)*>/, '') // Remove opening tag
            .replace(/<\/script>$/, ''); // Remove closing tag

        // Insert in first position in head
        app.head.script.unshift({ hid, type: 'text/javascript', innerHTML });

        // Disable Escaping for this script
        // https://vue-meta.nuxtjs.org/api/#dangerouslydisablesanitizersbytagid
        app.head.__dangerouslyDisableSanitizersByTagID = {
            ...(app.head.__dangerouslyDisableSanitizersByTagID ?? {}),
            [hid]: ['innerHTML'],
        };
    }
};
