### ISSUE TITLE
Build failed because different versions of vue & vue-server-renderer

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#7963]
*@nuxt/vue-renderer@2.14.3* when Nuxt installed has different versions 
`npm cache clear --force` and `rm package-lock.json` is not help

```
─┬ nuxt@2.14.3
  ├─┬ @nuxt/builder@2.14.3
  │ └─┬ @nuxt/vue-app@2.14.3
  │   └── vue@2.6.11
  └─┬ @nuxt/core@2.14.3
    └─┬ @nuxt/vue-renderer@2.14.3
      ├── vue@2.6.11  deduped
      └── vue-server-renderer@2.6.12
```

### Versions

- nuxt: last 2.14.3
- node: 14.3

### Reproduction

![image](https://user-images.githubusercontent.com/2588730/91161927-1485f500-e6d4-11ea-9473-418c04621b0b.png)

![image](https://user-images.githubusercontent.com/2588730/91162057-40a17600-e6d4-11ea-9252-682c37e10653.png)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is Expected?

Successful build

### What is actually happening?

Build failed

**Comment by ruslankonev** [comment]
Issue on our side

**Comment by SkyHolder** [comment]
Как ты исправил эту ошибку, у меня то же самое, ни как не пойму что не так

**Comment by SkyHolder** [comment]
rm -rf node_modules/ // Removes node_modules folder
rm -rf package-lock.json && npm cache clean --force //Removes package-lock file and cleans cache forcefully (npm v5+)
npm install // do a fresh install

помогло
