### ISSUE TITLE
Universal mode, target static application state.js and payload.js files do not reference the Webpack publicPath

### ISSUE THREAD

**Issue by TetHat** [nuxt/nuxt.js#7968]
We just upgraded to Nuxt v2.14.3 to take advantage of the full static target mode. However, our application's Webpack publicPath needs to be different in production and staging based on how the actual URL entered in the browser directs to our app. It appears due to this, our site breaks when utilizing full static mode because the new state.js and payload.js files needed in full static mode do not prepend with our modified publicPath value.

Inside our `build.extend` attribute in nuxt.config.js we have the following for when it goes into staging and production. 

```javascript
if (process.env.ENVIRONMENT !== 'dev') {
    config.output.publicPath = '/folderExample/_nuxt/';
}
```

Users will enter the site at `domain.com/folderExample/`. Upon entering our `_nuxt` files are hosted at the root level of our S3 bucket, so the `domain.com/folderExample/` proxies over to our site, `newdomain.com` and accesses the `_nuxt` files at the root level (e.g. `newdomain.com/_nuxt/`). This works perfectly fine for the standard files and assets, but it is not working for the state.js and payload.js files in static mode. 

Those files are referenced as if untouched by the Webpack config change we've made (e.g. `/_nuxt/static/1598381568/d/home/state.js` instead of `/folderExample/_nuxt/...`), causing the site to not have any of the state or payload due to 404ing on these requests. 

### Versions

- nuxt: v2.14.3
- node: v11.12.0

### Steps to reproduce

- Spin up Nuxt.js site
- Set the mode to `universal` and the target to `static`
- In `build.extend` of nuxt.config.js change the `config.output.publicPath` to be something other than the default `/_nuxt/` (e.g. `/testing/_nuxt/`)
- Run `nuxt generate`
- Open generated HTML file in `dist/` folder
- Look at the `src` attribute on all of the referenced `_nuxt` JS files. 
- Compare that to the `src` attribute on the state.js and payload.js files. 

### What is Expected?
state.js and payload.js would get the `/folderExample/_nuxt/` prepended to their src URLs so when the application is loaded from `domain.com/folderExmaple/` it's able to be loaded just like the rest of the `_nuxt` JS files.

### What is actually happening?
state.js and payload.js are not getting the `/folderExample/_nuxt/` prepended to their src URLs.

**Comment by pi0** [comment]
Hi @TetHat. Have you tried this:

```js
export default {
  build: {
    publicPath:  process.env.ENVIRONMENT === 'dev' : '/dev/_nuxt/' ? '/prod/_nuxt/'
  }
}

**Comment by TetHat** [comment]
Hi @pi0 , thanks for the suggestion. I did try that, but with that setting on generate the `_nuxt` folder was then stored inside of a `/dev/` or `/prod/` folder. In our case that would then throw 404s for all JS files in the `_nuxt` folder, not just the state.js or payload.js files. 

`domain.com/prod/_nuxt/` proxies over to `cloudfrontdomain.com/_nuxt/`, which with the above setting that folder no longer exists. Using the `config.output.publicPath` allows the folder to be stored in the correct location (at the root of the `dist/` folder) we need while still changing the src paths (except for the state.js and payload.js in this case).
