### ISSUE TITLE
Scorpius : An admin solution built on top of Nuxt. 

### ISSUE THREAD

**Issue by rwatts3** [nuxt/nuxt.js#797]
**Overview**
Transitioning to Nuxt.js from Meteor.js I must say that Nuxt is an amazing framework and I come to appreciate it everyday. With that said , I have a great deal of Meteor.js developers that have followed `Scorpius` since it's fork from the previous admin framework `Orion`. If succesful , Scorpius could potentialy bring other great devs from the Meteor community into the Vue/Nuxt ecosystem. 

I have a few preliminary questions that I need to sort out before this dream can become a reality. 

1. What is the best way to contribute fragments of a Nuxt application via an npm package? 
For instance is there a config option to set, that would allow a user to merge two directories. 
EX: All code for the admin solution would live under a directory called scorpius or admin. Scorpius Core will contain all components , logic, and pages relative to the admin panel. 
Behavior : Consumer should have the ability to install the package set or define settings either via a Vue Plugin , and/or Nuxt config, then consume the service in their pages directory. This may be better with a Vue Plugin, that accepts options, but then I would need to know what can be passed to the Package and sent back to the Nuxt runtime. Potentially introduce `mergeDirectory`  config setting that would merge two directories together such as a directory in the consumers project and the directory in the Scorpius package. 

2. Would 1. be better if everything is maintained as a Vue plugin , and Vue components, so `<scorpius></scorpius>` component would include the entire admin logic with other components such as `<scorpius-auth></scorpius-auth>` and `<scorpius-collection></scorpius-collection>` and many others managing the business logic for the admin solution. 

As i'm still learning the internals of Nuxt, and researching the best solution to make a distributed approach to extending a consumers Nuxt application. I would like any advice or pointers that could get me going in the right direction. 

Thank you, 

Ryan.

P.s. this post is not a bug or issue it is only meant to open a dialog with Nuxt devs to get better insights on what is currently possible and what contributions could be made to make other features possible.

**Comment by kodekrendel** [comment]
What's the features you see in that admin panel @rwatts3

**Comment by rwatts3** [comment]
@kodekrendel I see it being a modularized CMS, that can run your Nuxt Application, such as creating pages, managing collections of different types, etc. But the biggest thing is I wanted to make it pluggable, so that it can be dropped in a nuxt application with a few configurations, and minimal configuration from the end user.

@pi0 I noticed an issue and repo relating to nuxt modules. is there documentation anywhere about how this works and the expected behavior. This may be what i'm looking for

**Comment by rwatts3** [comment]
in fact i'm almost certain modules is what i'm looking for, this is great. I see it says documentation is coming soon, but Having the admin solution dropped in as a module would be fantastic.

**Comment by kodekrendel** [comment]
@rwatts3 I never heard about Scorpius before, to tell the truth.

If I am not mistaken, @alexchopin and @Atinux are launching some kind of CMS, and I guess it will be suited with Nuxt. Personally I am interested in GraphQL or Markdown solutions for content management.  

If you from Meteor community, then why not Apollo?

**Comment by pi0** [comment]
@rwatts3 Hi. Sorry for responding late. Idea of a Modular CMS on top of Nuxt for would be so great. I think the most challenging part is that we need to provide a more customized router module as well. 
About docs, they will be available in official docs soon. Meanwhile you may get a VIP support from me on gitter of needed to provide more details ;) Also issues for proposal are so welcomed and helps community inspect and provide us ideas even more ideas.

/cc @alexchopin @Atinux

**Comment by rwatts3** [comment]
Thank you @pi0 ,

I am still in the very early phase of planning things, and I agree with your advice on the proposal. I think This discussion might be best in the modules repo so I will close this issue, unless you feel this one should stay open. With that said, I will submit a proposal to the modules repo, once I have laid some ground work. 

The idea would be something similar to this, for those that are wondering. 


```js
{
    modules : [
        {
            src: '@scorpiusjs/core',
            options: {
                schema: {}, // custom db schema such as blogs, articles, widgets collections etc. 
                auth: {}, // authentication model.
                db: {
                    uri : 'mongodb://foo.bar:27017/foobarious'
                },
                themeSettings: {}// potential to load different styles to format and control the admin panel.
            }
        }
    ]
}
```

**Comment by sebastianmacias** [comment]
@rwatts3 first of all Scorpius sounds amazing! 

by looking at the modules conf example you posted, I noticed 'mongodb'... I would recommend you look into graph databases, specifically [dgraph](https://github.com/dgraph-io/dgraph) it has amazing performance and since it's developed in [go](https://github.com/golang/go), deployment is super easy, just upload a single binary, run and you are done. No dependencies 

I would also recommend building the backend in go, I understand why you might want to do it in js/node js but I assure you, after the learning curve (if you don't already know golang) you will be glad you chose go over node (typed language, concurrency, significantly faster than nodejs, less resource intensive, single binary distribution and deployment, etc). 

I would definitely be willing to contribute to the Scorpius project if you take the golang route, please let me know if you would like to discus this further
