### ISSUE TITLE
Improve error messages?

### ISSUE THREAD

**Issue by koteezy** [nuxt/nuxt.js#7972]
Hello!

When i run nuxt in production mode, i got strange error, and status 500 ([pic](https://i.imgur.com/vNEaotP.png)):
```
 ERROR  Cannot redefine property: styles                                                                                                                                                  15:15:04

  at Function.defineProperty (<anonymous>)
  at node_modules/vue-server-renderer/build.prod.js:1:78555
  at new Promise (<anonymous>)
  at node_modules/vue-server-renderer/build.prod.js:1:78108
  at Object.renderToString (node_modules/vue-server-renderer/build.prod.js:1:81643)
  at SSRRenderer.render (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:3812:38)
```

But when i run debug mode, via: npm run dev, i got clear error ([pic](https://i.imgur.com/MvLl3aj.png))
```
ReferenceError
$t is not defined
```

### Versions

- nuxt: v2.14.1 
- node: v14.7.0

### Steps to reproduce
Run nuxt in production mode

### What is Expected?
An error message that clearly lets you know what the error was.

### What is actually happening?
An obscure error that is unrelated to the original error as a whole.

**Comment by manniL** [comment]
Please provide a reproduction

**Comment by pi0** [comment]
> ReferenceError
> $t is not defined

From error only seems i18n module not installed or properly used

**Comment by koteezy** [comment]
Oh, i cannot reproduce this on blank project. it seems that one of the plugins is to blame. I'll close it for now.
