### ISSUE TITLE
nuxt-svg: Unexpected '.svg' rule in the webpack configuration

### ISSUE THREAD

**Issue by jwv** [nuxt/nuxt.js#7977]
### Versions

- nuxt: v2.14.4
- node: v14.8.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
{
  mode: 'universal',
  target: 'static',
modules: [
    '@nuxtjs/svg'
  ]
}
</details>

### Steps to reproduce
Run command nuxt dev or nuxt generate

### What is Expected?
Success

### What is actually happening?
ERROR  nuxt-svg: Unexpected '.svg' rule in the webpack configuration

**Comment by juliandreas** [comment]
![nuxt](https://user-images.githubusercontent.com/27690759/91487209-b14fba80-e8ad-11ea-8327-a1c5305384cd.jpg)

Same issue after updating from 2.14.3 to 2.14.4.
I've seen others mentioning the same problem in the Nuxt discord as well.

**Comment by danielroe** [comment]
See fix here: https://github.com/nuxt-community/svg-module/pull/57
