### ISSUE TITLE
nuxt项目部署后，运行一段时间之后会特别的卡顿，渲染很慢，重启以后就很快

### ISSUE THREAD

**Issue by luotingv1** [nuxt/nuxt.js#7979]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by thunderwin** [comment]
你服务器内存不够吧

**Comment by pi0** [comment]
> en: 
> After the project is deployed, it will be particularly stuck after running for a period of time, rendering is very slow, and it will be very fast after restarting
> Your server has insufficient memory, right

Hi @thunderwin. This seems to be a memory leak issue with your project but without having access to source-code to analyze heap dump it is not easily traceable to find the root cause. maybe @clarkdo can help.

**Comment by AshenBird** [comment]
@luotingv1 我遇到了类似的问题，我在 plugins 里面使用了 mixins，而且没有使用官方提供的手段避免mixin的反复调用。如果你也是类似情况，你可以参考[官方文档中 mixin 的使用](https://nuxtjs.org/docs/directory-structure/plugins#global-mixins)。

**Comment by censujiang** [comment]
内存泄漏了吧，nodejs没有自动gc，这个样子只能做定时重启
