### ISSUE TITLE
Document is not defined in Vue mixin? (help wanted)

### ISSUE THREAD

**Issue by andrisole92** [nuxt/nuxt.js#798]
I have a problem with setting a cookie from the mixin.
I have a mixin with `methods` `setCookie` and `getCookie`, and when used in methods, then they work fine, but when I try to render them in template e.g 
```<temlate>
<div>
<p>{{this.getCookie('test')}}</p>
...
```
it says document is undefined. I have also tried using `computed`

As I understand it is because of SSR, and I have found some publications on how to make plugins work without SSR, but nothing about mixins and cookies. Does anyone can help.
Can anyone help please?

**Comment by pi0** [comment]
Hello. Please see https://nuxtjs.org/faq/window-document-undefined

**Comment by andrisole92** [comment]
Hi, I have seen it many times today, still can't get it.
I am using import instead of require, so should it be:
```
if (process.BROWSER_BUILD) {
    import cookieMixin from '../lib/cookies'
}
```
and
```
vendor: ['axios', '/lib/cookies'],

```

???

**Comment by pi0** [comment]
`/lib/cookies` this one should be omitted. Also if you are calling `import` within plugin, you may remove guard and use `ssr: false` option when declaring plugin.

**Comment by andrisole92** [comment]
Wait, it is not a plugin, and it is not in the plugin directory. It is a mixin and I have it in a separate directory called lib.

**Comment by andrisole92** [comment]
And what do you mean by the guard? is it 
```
if (process.BROWSER_BUILD) {
    import cookieMixin from '../lib/cookies'
}
```

**Comment by pi0** [comment]
plugins may not be necessarily in plugins dir! You also can register directives inside them. Also `vender` is used to exclude external node_modules. You don't need to exclude you our codes.

**Comment by andrisole92** [comment]
Do you suggest me to use a mixin as a Plugin?

**Comment by pi0** [comment]
Oops sorry i was asleep thinking you are talking about directives :D

**Comment by andrisole92** [comment]
No, I need a mixin, lol. Probably I just need to get a cookie. And it can't find the document.

**Comment by pi0** [comment]
@andrisole92 [here](https://github.com/nuxt/modules/blob/master/modules/auth/store.js#L67) is a working store implementation that uses cookies. Something like this:
```js
      // Try to extract token from cookies
      const cookieStr = inBrowser ? document.cookie : SSR.req.headers.cookie
      const cookies = Cookie.parse(cookieStr || '') || {}
      const token = cookies.token
```
