### ISSUE TITLE
Can't install older version of nuxt (v2.3.1)

### ISSUE THREAD

**Issue by saint777** [nuxt/nuxt.js#7986]
whats done:

deleted **node_modules** folder, **package-lock**

put inside package.json

"dependencies": {
"nuxt": "2.3.1"
},

after npm install, i run npm run dev

terminal says Nuxt v2.14.4

and also inside node_modues/@nuxt/builder is getting installed with version 2.14.4

**Comment by danielroe** [comment]
Looks like a consequence of the way the dependencies were specified in that version. (They are no longer specified in that way.) See https://unpkg.com/browse/nuxt@2.3.1/package.json

That can't be changed as the package is immutable but you could specify your own version of each of the packages depended on by the Nuxt parent package, and that should prevent a newer version from being installed.

**Comment by saint777** [comment]
> Looks like a consequence of the way the dependencies were specified in that version. (They are no longer specified in that way.) See https://unpkg.com/browse/nuxt@2.3.1/package.json
> 
> That can't be changed as the package is immutable but you could specify your own version of each of the packages depended on by the Nuxt parent package, and that should prevent a newer version from being installed.

Thank you for reply, that helped to figure out my problem.

**_Holy moly i'm lucky with this one_** 😒
