### ISSUE TITLE
problemas with root 

### ISSUE THREAD

**Issue by davidnotplay** [nuxt/nuxt.js#799]
Hi.

I have this pages tree directory.

![captura de pantalla de 2017-05-28 00-50-45](https://cloud.githubusercontent.com/assets/2668489/26524790/c354cd54-433f-11e7-9eeb-27157ce141f0.png)

and the router code

```javascript
 routes: [
  		{
			path: "/blog-admin",
			component: _0d24c77e,
			name: "blog-admin"
		},
		{
			path: "/categorias",
			component: _df637d06,
			name: "categorias"
		},
		{
			path: "/blog-admin/entradas",
			component: _316be920,
			name: "blog-admin-entradas"
		},
		{
			path: "/busqueda/:page?",
			component: _a1f49812,
			name: "busqueda-page"
		},
		{
			path: "/entrada/:id?/:entry?",
			component: _7cd36a0c,
			name: "entrada-id-entry"
		},
		{
			path: "/categoria/:name?/:page?",
			component: _3df4f37a,
			name: "categoria-name-page"
		},
		{
			path: "/:page",
			component: _39302f84,
			name: "page"
		}
    ]
  
```

the page `_page.vue` should be optional right? But nuxt doesn't generate the route correctly. Its a bug? or is a bad configuration?

thx

**Comment by alexchopin** [comment]
Do you have the `index.vue` file in the `pages` directory?

**Comment by davidnotplay** [comment]
> Do you have the index.vue file in the pages directory?

Nop.

Finally, Investigating, if I remove the `blog-admin` directory the page component `_page` is optional. If I add the directory again, the component isn't optional.

I solved my problem using this directory structure.
![captura de pantalla de 2017-05-28 12-45-37](https://cloud.githubusercontent.com/assets/2668489/26528115/928751ba-43a3-11e7-841a-f46b42829762.png)

Now I have one `blog-admin` component in the root and a `blog-admin` directory. With this structure, my routes are corrects.

I see which can be complicated make routes correctly with this system. In a future, Nuxt maybe should allows configure ours routing manually.

**Comment by pi0** [comment]
@davidnotplay We may improve directory route generator, also fully custme routers are coming soon 😎
