### ISSUE TITLE
using custom server.js have an Unexpected token 'export'

### ISSUE THREAD

**Issue by f3ltron** [nuxt/nuxt.js#7991]
### Versions

- nuxt: 2.14.0
- node: 12.18.3

### Reproduction

I want to benefit of full clustering node to deploy on server.

- Clone https://github.com/f3ltron/azure-nuxt-ssr
- `npm run build`
- `npm start`

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

- Clone https://github.com/f3ltron/azure-nuxt-ssr
- `npm run build`
- `npm start`

### What is Expected?

It should work

### What is actually happening?

It makes sense that is doesn't work but if I try to change for module.exports for `nuxt.config.js` i have another error that i don't have for this simple reproducing project. I will come back for this part with more infos

**Comment by danielroe** [comment]
@f3ltron Your custom server implementation isn't being processed by Nuxt and therefore will probably need to be written in JavaScript that can be run directly by node (e.g. CJS). Alternatives include using something like `jiti` or a transpilation step.

**Comment by f3ltron** [comment]
I decide to go with common js and module exports yeah. Now it's working thanks Daniel

**Comment by pi0** [comment]
Hi @f3ltron. Looking at repo [directly require config](https://github.com/f3ltron/azure-nuxt-ssr/blob/4ca5026ee2bc2f17662c5d3e2e01886dd2d2653c/cluster.js#L83) and [`new Nuxt()`](https://github.com/f3ltron/azure-nuxt-ssr/blob/master/cluster.js#L91) are not recommanded. There is new [`loadNuxt`](https://nuxtjs.org/api/nuxt/#nuxt-constructor) utility to automatically load nuxt.config and create nuxt instance for programmatic usage. It not only adds esm support, but also ensure other internal flags set properly and less risk of regressions with nuxt releases.

**Comment by f3ltron** [comment]
Ok i will test about it and close the issue if all is good

**Comment by f3ltron** [comment]
It looks it now working well with export default too. Thank's @pi0
