### ISSUE TITLE
Wont clean up socket on shutdown leading to "Address is already in use." error on next start.

### ISSUE THREAD

**Issue by h0m3us3r** [nuxt/nuxt.js#7992]
### Versions

- nuxt: 2.14.0
- node: 14.9.0

### Steps to reproduce
1. Use nuxt configured with socket endpoint:
```
server: {
  socket: '/tmp/nuxt.socket'
}
```
2. Start nuxt (either `nuxt` or `nuxt start`);
3. Close nuxt;
4. Start nuxt again;

### What is Expected?
Nuxt starts.

### What is actually happening?
```
   ╭───────────────────────────────────────────────────────────────────╮
   │                                                                   │
   │   ✖ Nuxt Fatal Error                                              │
   │                                                                   │
   │   Error: Address `$redacted$` is already in use.                  │
   │                                                                   │
   ╰───────────────────────────────────────────────────────────────────╯
```

**Comment by h0m3us3r** [comment]
Ok, it expects the socket to be in `/tmp` and to be cleaned up by the os.

**Comment by janswist** [comment]
@h0m3us3r how did you managed to solve this? Every time I restart Nuxt I have to do `kill -9 <process_id>` which is annoying

**Comment by shawn-p-m** [comment]
Pretty sure you can just go to your Linux root, find /tmp, then just delete nuxt.socket from there.
