### ISSUE TITLE
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by f3ltron** [nuxt/nuxt.js#7997]
### Versions

- nuxt: 2.14
- node: 12.18.3

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
https://azgateway.azurefd.net/en-ca/women

If you don't have images open console and you will see the error.
If you have images open console delete application storage and refresh

### What is Expected?
I am working with azure front door. That gave you the ability to cache your assets. But when I activate it ii have this error. When I disable it I don't have this error as I am not caching anything anymore.

I saw there was a lot of issues about hydration. But I am not sure it's my case here. If you have any idea

**Comment by manniL** [comment]
Receiving a 500 on the test site

![](https://user-images.githubusercontent.com/640208/91825659-d7be7e80-ec3c-11ea-9db6-978b2bca5efd.png)

**Comment by f3ltron** [comment]
I unchecked their dynamic compressing. I will continue to read thanks for the info @manniL . Normally you should not have err500

**Comment by f3ltron** [comment]
In my case it was azure front door that did some weird compression on my HTML i close the issue thank's @manniL  for your time !
