### ISSUE TITLE
Store generation

### ISSUE THREAD

**Issue by Granipouss** [nuxt/nuxt.js#80]
Hi ! And merry christmas to you all !

I've discovered Nuxt quite recently and I must admit I find it quite revolutionary and awesome. Thanks for bringing it to us.
For my vue projects, I use to generate the router and the store by reading directories in a way that is similar to the way to  create pages. So I wonder if you'd be interested in doing the same for the store ?
I mean that each file of the store directory would contain all data and methods for a module, an example can be found in [vue-electron](https://github.com/SimulatedGREG/electron-vue/tree/master/template/app/src/vuex/modules) or in my (quite recent) [fork](https://github.com/Granipouss/nuxt.js/tree/master/examples/vuex-store/store) I made of nuxt.

I know that this is not an important feature for the version 1.0 you are planning to release soon, so I am not excepting any anwser soon.

Keep up the good work !

**Comment by Atinux** [comment]
Hi @Granipouss and thank you for your kind words!

I understand your idea and it makes sense.

The actual problem I see is that it will remove the possibility of having the official vuex directory structure: http://vuex.vuejs.org/en/structure.html

**Comment by Granipouss** [comment]
Indeed that's an issue.
Maybe check if there is an index.js and if it returns a valid store, if not, nuxt generates the proper store. Or do according to the configuration file

**Comment by Granipouss** [comment]
Indeed that's an issue.
Maybe check if there is an index.js and if it returns a valid store, if not, nuxt generates the proper store. Or do according to the configuration file

**Comment by Atinux** [comment]
It might be a solution indeed and let the users create easily a store with Nuxt.js, I keep it open 👍

**Comment by Granipouss** [comment]
Nice, I'll work on that and make a proposition soon

**Comment by Granipouss** [comment]
So here is the thing:
https://github.com/Granipouss/nuxt.js/blob/master/lib/app/store.js
and the example that goes with it:
https://github.com/Granipouss/nuxt.js/tree/master/examples/vuex-store-2

I hope tat the coding style suit you. Shall I do a pull request ?

**Comment by Atinux** [comment]
Sure, great work 👏

**Comment by Atinux** [comment]
Will be available in the next release 🎊

**Comment by Atinux** [comment]
It's now available in the [0.9.6](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.6)!
