### ISSUE TITLE
serverMiddleware and root path

### ISSUE THREAD

**Issue by kgrigorian** [nuxt/nuxt.js#8000]
### Versions

- nuxt: v2.14.4
- node: v14.4.0

### Reproduction

Trying to map '/' path to serve static landing page html.

 serverMiddleware: [
    { path: '/', handler: serveStatic(`${__dirname}/landing.html`) }
  ],
and it does not work. But specifying any other path like '/landing' works fine. Is there any workaround for this issue?

### Steps to reproduce

create serverMiddleware with '/' path
it wont fire

### What is Expected?

Path would override Nuxt's native routing

### What is actually happening?

serverMiddleware is ignored

**Comment by farnabaz** [comment]
A URL that ends with `/` are specific static URLs, When you want to load `/`, `static-serve` tries to find `index.html` file in your `${__dirname}/landing.html` path. (well finding `index.html` inside another file seems crazy, right?)  

Create `static-pages` directory in your project and move `landing.html` into this directory and name it `index.html`. And update your server middleware. 
```js
serverMiddleware: [
	{ path: '/', handler: serveStatic(${__dirname}/static-pages) }
],
```

**Comment by farnabaz** [comment]
I close this issue but feel free to reopen it or ask any questions 🙂
