### ISSUE TITLE
Full static and preview mode on static hosting

### ISSUE THREAD

**Issue by ColinPeyrat** [nuxt/nuxt.js#8001]
### Is your feature request related to a problem? Please describe.

I love the full static mode, and the new [preview mode](https://nuxtjs.org/guides/features/live-preview/) is great to avoid waiting and generating all the website after each update of the CMS. The only issue I had with it is that it works great in local, but I would love to have it in staging environnement on a static hosting. For example, I use [netlify ](https://www.netlify.com/) and since I can't run `nuxt start` on this hosting the preview mode doesn't work..

For example if I go to my page `/my-page?preview` true netlify redirect me to `/my-page/?preview=true` and the preview failed.

### Describe the solution you'd like

I'd love to live preview mode work without to run nuxt start so it can work on static hosting like Vercel. Netlify, etc.

### Describe alternatives you've considered

I've considered to run into spa mode, but a lot of thing don't work anymore since nuxtServerInit is not called

**Comment by manniL** [comment]
IIRC, preview mode should work fine with static hosting like Vercel or Netlify. Could you provide a minimal example where it doesn't?

**Comment by lihbr** [comment]
^ I can confirm that preview mode is working on Netlify on my side, it'll be useful to share a minimal repro Colin 🙂

Are you sure you're enabling it inside a plugin?

**Comment by ColinPeyrat** [comment]
I am sorry for that !

I've made this example that you can see live on netlify here : [https://heuristic-goldwasser-5eeeea.netlify.app/test/](https://heuristic-goldwasser-5eeeea.netlify.app/test/)
and you can see the repo here : [https://github.com/ColinPeyrat/nuxt-live-preveiw](https://github.com/ColinPeyrat/nuxt-live-preveiw)

the goal here is to log something in the console when asyncData is called on the client side. And you're right : it just works ! So I think I've failed on upgrading nuxt in my project...

**Comment by manniL** [comment]
Glad to hear it works now 👍🏻

**Comment by gerbenqikker** [comment]
@manniL, sorry to hijack this, but I'm running into a similar situation. When building locally and running npm run start it all works as expected, but not on my nginx powered staging environment.

I can confirm that previewMode is enabled properly (im logging that in the browser), and my data is also being fetched properly (im also logging that, and I can see the XHR request, and response with correct data). The generate.fallback key is also set to true. 

So far all good, but for me the UI is not being rendered at all (im getting the 404 page), even though the rest of the behaviour above seems correct. What can cause this? I have tried returning true in the validate hook on the page, that has made no difference. 

On the nginx side I am pointing to 404.html in case the prerendered page does not exist, this is correct right?

Thanks a lot!
