### ISSUE TITLE
.scss files can not use cssModules

### ISSUE THREAD

**Issue by ccforeverd** [nuxt/nuxt.js#8007]
### Is your feature request related to a problem? Please describe.

When I use scss to write styles I like to use css-modules in my components.

I tried `import style from './style.scss'` and `import style from './style.module.scss'` and then `console.log(style)` but I got `{}` in the console board.

### Describe the solution you'd like

I can use css-modules in `.scss` files.

### Describe alternatives you've considered

I can use css-modules in `.module.scss` files.

### Additional context

There is my temporary solution in `nuxt.config.js`:

``` js

  build: {
    extend (config) {
      // 配置scss中使用cssModules
      const scssRule = config.module.rules.find((item) => {
        return String(item.test) === '/\\.scss$/i'
      })
      scssRule.oneOf = [] // 去掉老的
      scssRule.use = [ // 替换成新的
        'vue-style-loader',
        {
          loader: 'css-loader',
          options: { modules: true }
        },
        'sass-loader'
      ]
    }
  }

```

Maybe it is helpful to people who has the same problem with me.

**Comment by ccforeverd** [comment]
hello `test` `test`

**Comment by websitevirtuoso** [comment]
Waiting Upgrading. Tried to upgrade sass to 10 version got an error

**Comment by ccforeverd** [comment]
> Is this still true for you? See [reproduction sandbox](https://codesandbox.io/s/jovial-sun-1r4lm?file=/pages/index.vue).

Thank you!
