### ISSUE TITLE
Scroll Behavior doesn't work on SPA mode

### ISSUE THREAD

**Issue by vostokwork** [nuxt/nuxt.js#8017]
### Versions

- nuxt: 
- node: 

### What is actually happening?

I was working on my working project (in spa mode from the beginning) and noticed that after reloading the page, my scroll did not return to the same place, as it happens everywhere on the Internet.

And scrolling to anchors does not work either!

Through testing I have learned that it depends on whether the spa mod is enabled or not.

I figured it out when I created a new empty project and tried this.

How do I get the recovery back after reloading the page when the application is built in spa mode?

My test config:

![image](https://user-images.githubusercontent.com/37534401/92151472-d900ce80-ee29-11ea-8673-3acae38f322d.png)

**Comment by TravisKut** [comment]
i have the same issues

check this out https://nuxtjs.org/api/configuration-router#scrollBehavior

**Comment by VostokWork** [comment]
> i have the same issues
> 
> check this out https://nuxtjs.org/api/configuration-router#scrollBehavior

I tried to create a file and override the scroll behavior but it only works correctly when the spa is off

```js
export default function (to, from, savedPosition) {
  return { x: 0, y: 200 }
}
```

**Comment by jankulma-turbine** [comment]
@vostokwork did you manage to solve it?

**Comment by vostokwork** [comment]
> @vostokwork did you manage to solve it?

I haven't solved it in any way

**Comment by bnping** [comment]
the pb is always here
