### ISSUE TITLE
Nuxt generate hangs after completion

### ISSUE THREAD

**Issue by peitalin** [nuxt/nuxt.js#802]
I'm running into the issue where nuxt will hang after running `yarn generate` on a small site:

```
  nuxt:generate Destination folder cleaned +30s
  nuxt:generate Static & build files copied +29ms
  nuxt:render Rendering url / +3ms
  nuxt:render Rendering url /terms +53ms
  nuxt:render Rendering url /privacy +9ms
  nuxt:generate Generate file: /index.html +590ms
  nuxt:generate Generate file: /terms/index.html +78ms
  nuxt:generate Generate file: /privacy/index.html +40ms
  nuxt:generate HTML Files generated in 31.1s +4ms
[nuxt] Generate done
```
Nuxt hangs, so if i wanted to run something like `yarn generate; yarn serve`, `yarn serve` is never run.

Any ideas what may be causing this?

**Comment by piyushchauhan2011** [comment]
Shouldn't it be && @peitalin

**Comment by florianwittmann** [comment]
@peitalin Are you using something like Firebase or similar that is opening a socket which keeps open?

**Comment by piyushchauhan2011** [comment]
Hmm, or maybe because of watchers ? https://nuxtjs.org/api/configuration-watchers/#the-watchers-property @florianwittmann

**Comment by florianwittmann** [comment]
Maybe we need a generateDone event/hook to be able to provide some function in nuxt.config.js for socket closing and other cleanup stuff?

**Comment by peitalin** [comment]
I'm not using anything with sockets at the moment; the sites a a landing page with basic JavaScript functionality.

**Comment by florianwittmann** [comment]
Please attach some code example, so we can reproduce it @peitalin

**Comment by anishkny** [comment]
Check out this glitch:

https://glitch.com/edit/#!/nuxtjs

Its asyncData code is:
```
  asyncData: function(context, callback) {
    firebase.database().ref('/').once('value').then(function(snap) {
      console.log("Data from Firebase: " + JSON.stringify(snap.val(), null, 2));
      callback(null, snap.val());
    });
  }
```

and runs: ```nuxt generate; ls -lht dist; echo Done```

But "Done" never shows up!

**Comment by peitalin** [comment]
I did a clean git clone, yarn install, yarn generate of my repo and the issue is no longer there.
