### ISSUE TITLE
当开发模式为production时且mode:universal时，刷新页面会The client-side rendered virtual DOM tree is not matching server-rendered content.

### ISSUE THREAD

**Issue by 2292912322** [nuxt/nuxt.js#8020]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by 2292912322** [comment]
[
![7c8f71b6f3f71aa29f3ebace6be8632](https://user-images.githubusercontent.com/41560476/92242205-07e27780-eef2-11ea-92e2-3352b2c54ef6.png)
](url)

**Comment by 2292912322** [comment]
# 当开发模式为production时且mode:universal时，刷新页面会The client-side rendered virtual DOM tree is not matching server-rendered content.
### 当我使用了<nuxt-child />去渲染路由时，正常跳转时没有问题的，但当我刷新页面的时候，总是触发vue的警告 The client-side rendered virtual DOM tree is not matching server-rendered content.
![91a7b10d83257e8f786b7bcd756e6c0](https://user-images.githubusercontent.com/41560476/92295095-cd172880-ef5f-11ea-8e1d-2eacf65e5df9.png)
![e75072e2436beafe50e77e8760534c8](https://user-images.githubusercontent.com/41560476/92295298-fe8ff400-ef5f-11ea-9474-fb2b90c70cb3.png)
当看页面结构的时候发现总会自动生成一个注释标签
![35f0c83d52c2872e3114e5b3336c635](https://user-images.githubusercontent.com/41560476/92295499-35660a00-ef60-11ea-8c1f-fe4081bf011d.png)

**Comment by 2292912322** [comment]
### 这个注释标签仿佛是nuxt自动生成的，我的代码里面没有添加这个标签，在我检测代码的过程中，感觉就是这个注释标签导致了报错，但我无法找到注释标签的位置并删除它

**Comment by danielroe** [comment]
@2292912322 It's a hydration issue, and is most probably caused by your code, HTML or a library you are using rather than by Nuxt.

[This article](https://blog.lichter.io/posts/vue-hydration-error/) should be helpful in identifying the issue. Without knowing more, I wonder if the cause is the `v-xy-moving-btn` directive. Is it possible it produces different code on server vs client?

**Comment by 2292912322** [comment]
> @ 2292912322这是一个水化问题，很可能是由您使用的代码，HTML或库而不是Nuxt引起的。
> 
> [本文](https://blog.lichter.io/posts/vue-hydration-error/)应有助于识别问题。不知道更多，我想知道原因是否是`v-xy-moving-btn`指令。是否有可能在服务器端和客户端上产生不同的代码？

我已经尝试过了将v-xy-moving-btn指令去掉，一样会产生这个问题，关键代码在nuxt-child 如果我加上<no-ssr><nuxt-child /></no-ssr>就不会出现这种情况。但我就是为了更好Seo如果我加上no-ssr，那我服务端渲染的目的就实去了。我反复检查了代码，发现会自动生成这个注释标签，但实际上我的代码并没有这个标签，因为我create-nuxt-app 一个新项目，使用nuxt-child去渲染组件，发现一刷新也是会报一样的错误。而且我看了vue的源码似乎只会在开发环境去检测这个错误

**Comment by danielroe** [comment]
@2292912322 Vue may only warn you in development, but it will still be a problem in production.

I hadn't spotted your use of `<nuxt-child>` earlier. Could you provide a reproduction so I can see how you are using it?

**Comment by 2292912322** [comment]
> @ 2292912322 Vue可能只会在开发中警告您，但在生产中仍然会出现问题。
> 
> 我没有发现您`<nuxt-child>`较早的使用。您能否提供复制品，以便我能看到您的使用方式？

![dc10311518821105db7dc9e1dd3139e](https://user-images.githubusercontent.com/41560476/92318999-746e8b00-f046-11ea-853e-c13968b94c34.png)
就像这样我的目录结构，当我去访问localhose:3000/#/home，home.vue的内容会渲染在nuxt-child里面，正常的访问是没有问题的，但当我刷新浏览器的时候就是报错，我也通过create-nuxt-app去初始化一个全新的项目，在没有引用如何插件就是官方提供的初始代码的情况下，一样遇到了报错，所以我就排除了是我自己引用的插件或者某部分的代码导致了这个错误

**Comment by danielroe** [comment]
I can't replicate. See [here](https://codesandbox.io/s/icy-monad-y2rbi?file=/pages/index.vue) for example.

Could you create a code reproduction, perhaps using https://template.nuxtjs.org/ ?

**Comment by 2292912322** [comment]
> I can't replicate. See [here](https://codesandbox.io/s/icy-monad-y2rbi?file=/pages/index.vue) for example.
> 
> Could you create a code reproduction, perhaps using https://template.nuxtjs.org/ ?
我看了你的代码，现在的关键是如何去访问你的about.vue，然后去刷新你的页面看是否会和我一样报错，我看你的index.vue没有跳转到about，你的nuxt-child并没有渲染出about的内容。

**Comment by 2292912322** [comment]
> I can't replicate. See [here](https://codesandbox.io/s/icy-monad-y2rbi?file=/pages/index.vue) for example.
> 
> Could you create a code reproduction, perhaps using https://template.nuxtjs.org/ ?

 你可以看看这个例子[](https://codesandbox.io/s/musing-morning-zinib?file=/pages/index.vue)

**Comment by 2292912322** [comment]
> 你可以看看这个例子

[https://codesandbox.io/s/musing-morning-zinib?file=/pages/index.vue](url)

**Comment by danielroe** [comment]
@2292912322 The problem is caused - as you can see, because you had to add it to `nuxt.config` in order to reproduce the problem - by adding the following to your Nuxt config:
```js
export default {
  router: {
    mode: 'hash'
  }
}
```

It is [not recommended](https://nuxtjs.org/api/configuration-router/#mode) to mix hash-based routing with server-side rendering. Why is that? Browsers do not send the hash part of the URL to a server - so `/#/my-url` only makes the following request to the server: `/` - which means the server is unable to render the page you really want.

In your case, if you request the page `/about`, on load the hash-based routing kicks in and redirects to `/about#/` (which is actually the address of the base route `/`). That doesn't match the rendered HTML and so there is a mismatch.

Or, if you request `/#/about` note that the rendered HTML is for the route `/` instead.

**Comment by 2292912322** [comment]
> @2292912322 The problem is caused - as you can see, because you had to add it to `nuxt.config` in order to reproduce the problem - by adding the following to your Nuxt config:
> 
> ```js
> export default {
>   router: {
>     mode: 'hash'
>   }
> }
> ```
> 
> It is [not recommended](https://nuxtjs.org/api/configuration-router/#mode) to mix hash-based routing with server-side rendering. Why is that? Browsers do not send the hash part of the URL to a server - so `/#/my-url` only makes the following request to the server: `/` - which means the server is unable to render the page you really want.
> 
> In your case, if you request the page `/about`, on load the hash-based routing kicks in and redirects to `/about#/` (which is actually the address of the base route `/`). That doesn't match the rendered HTML and so there is a mismatch.
> 
> Or, if you request `/#/about` note that the rendered HTML is for the route `/` instead.

非常感谢，我明白了，那是否在开启universal时就不支持采用hash模式呢？

**Comment by danielroe** [comment]
Exactly; you shouldn't mix `universal` mode and hash-based routing.

**Comment by 2292912322** [comment]
> Exactly; you shouldn't mix `universal` mode and hash-based routing.

明白了，非常感谢你
