### ISSUE TITLE
in pages/somefile.tsx files, asyncData is not invoked.

### ISSUE THREAD

**Issue by ccforeverd** [nuxt/nuxt.js#8024]
### Versions

- nuxt: 2.14.4
- node: 12.14.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

from `pages/index.vue`

``` vue
<template>
  <main>
    <bar />
    <banner />
  </main>
</template>

<script lang="ts">
import Vue from 'vue'
import Bar from '~/components/pc/Bar'
import Banner from '~/components/pc/Banner'

export default Vue.extend({
  components: {
    Bar,
    Banner
  },
  async asyncData ({ $content, store: { commit } }) {
    const homepageData: ContentJson = await $content('database/homepage').fetch()
    commit('database/homepage', homepageData.data)
  }
})
</script>

<style lang="scss">
// reset
a {
  color: inherit;
  text-decoration: none;
}
</style>
```

I modified it to `pages/index.tsx`

``` tsx
// asyncData 方法在 .tsx 中没有执行

import { Vue, Component } from 'vue-property-decorator'
import Bar from '~/components/pc/Bar'
import Banner from '~/components/pc/Banner'

@Component
export default class PageIndex extends Vue {
  async asyncData({ $content, store: { commit } }) {
    console.log(123123123123)
    const homepageData: ContentJson = await $content('database/homepage').fetch()
    commit('database/homepage', homepageData.data)
  }

  render() {
    return (
      <main>
        <Bar />
        <Banner />
      </main>
    )
  }
}

```

then I opened it in browser, the `asyncData` function is not invoked but in `.vue` file.

</details>

### Steps to reproduce

see up

### What is Expected?

The `asyncData` function can be normal invoked in `.tsx` file in `pages` dir.

### What is actually happening?

The `asyncData` function is invoked in `.vue` file but not in `.tsx` file

**Comment by loyep** [comment]
Maybe, you need [nuxt-property-decorator ](https://github.com/nuxt-community/nuxt-property-decorator)

**Comment by ccforeverd** [comment]
> Maybe, you need [nuxt-property-decorator ](https://github.com/nuxt-community/nuxt-property-decorator).

resolved, thank you so much
