### ISSUE TITLE
process.env in component always {}

### ISSUE THREAD

**Issue by hak11** [nuxt/nuxt.js#8028]
### Versions

- nuxt: ^2.14.0
- node: 12.18.3

-----------------

i want to create global variable.
and i read this documentation https://id.nuxtjs.org/api/configuration-env/ and https://nuxtjs.org/guide/runtime-config/

// .env
```js
LANDING_PAGE_URL=http://localhost:8070
```

// nuxt.config
```js
  env: {
    LANDING_PAGE_URL: process.env.LANDING_PAGE_URL ||  'http://localhost:3000',
  },
  publicRuntimeConfig: {
    LANDING_PAGE_TEST: '123',
  },
```

but in my component only show {}
```js
  mounted () {
    this.$store.dispatch('template/getListTemplate');
    console.log('check env : ', process.env);
  },
```
![Screenshot from 2020-09-08 00-05-52](https://user-images.githubusercontent.com/14852163/92408256-1a191b80-f167-11ea-906b-b29e50a9a7d8.png)

i don't know is this ticket the same? 
- https://github.com/nuxt/nuxt.js/issues/7990
- https://github.com/nuxt/nuxt.js/issues/8023

because my .env variable doesn't have any special characters

**Comment by manniL** [comment]
This behavior is explained in the docs: https://nuxtjs.org/api/configuration-env/#processenv--

**Comment by danielroe** [comment]
@hak11 Hopefully this should explain why: https://id.nuxtjs.org/api/configuration-env/#processenv--

For accessing values off `publicRuntimeConfig`, you access them from the `$config` object. See https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config for more info.

**Comment by hak11** [comment]
thanks @manniL & @danielroe. I tried again as in the documentation

with:

// .env
BASE_URL=http://localhost:8050

// nuxt.config.js
```js
  env: {,
    baseUrl: process.env.BASE_URL || 'http://localhost:3050',
  },
```

//mycomponent.vue
```js
  mounted () {
    console.log('check env 123 : ', process.env);
  },
```

it remains empty object {}

but if i call with this

//mycomponent.vue

```js
  mounted () {
    console.log('check env 123 : ', process.env.baseUrl);
  },
```

appears what I want
//  check env 123 :  http://localhost:8080
