### ISSUE TITLE
Dynamic webpack_public_path working but not on dynamic routes

### ISSUE THREAD

**Issue by digitalfuel** [nuxt/nuxt.js#8033]
### Versions

- nuxt: v2.14.4 
- node: v13.12.0 

### Steps to reproduce

Add global variable __webpack_public_path__ and documented. https://webpack.js.org/guides/public-path/#on-the-fly.
Run NUXT Generate

directory eg
```
-| pages/
---| users/
-----| _id.vue
-----| index.vue
```

nuxt.config.js
```
plugins: [{ src: "~/plugins/cdn", mode: "client" }],
```

cdn.js
```
export default async ({ store }) => {
  const cdn = store.state["globals"].cdn;
  __webpack_public_path__ = cdn + "/_nuxt/";
};
```

### What is Expected?
Dynamic publicPath for different CDN on different instances.

### What is actually happening?
This works for standard routes on entry and navigation. 

For dynamic routes it works for navigation but on entry(refresh) it reverts to the publicPath default or defined.

In the webpack doc it says _'Be aware that if you use ES6 module imports in your entry file the __webpack_public_path__ assignment will be done after the imports. In such cases, you'll have to move the public path assignment to its own dedicated module and then import it on top of your entry.js:'_

So it maybe an issue with the __webpack_public_path__ not running early enough. I have tried everything I can think of but I cannot get it to work for dynamic routes. 

The chunk is loaded correctly using the dynamic __webpack_public_path__ for standard routes and when navigating to the dynamic route but not when the page is refreshed for the dynamic route. Also it is only the chunk of the dynamic route that fails and reverts to the build.publicPath all the other chunks on the dynamics routes page use __webpack_public_path__ correctly.

Is there anyway to get this fixed working for dynamic routes with generate.

**Comment by rotemrevivo91** [comment]
any luck? this is a bit ridiculous tbh. nuxt is perfect for development but trash for production

**Comment by danielroe** [comment]
I think this feature request is probably what you want: https://github.com/nuxt/nuxt.js/issues/8229
