### ISSUE TITLE
How to change the slug of a specific Page file

### ISSUE THREAD

**Issue by smzapp** [nuxt/nuxt.js#8034]
As of now, the slug is based on the filename inside the page. Of course, we can customize it dynamically:
https://nuxtjs.org/guide/routing/

Is there such a thing like these:

`page/custom.vue`
`export default {
   slug: 'my-custom-slug', //this is what I am thinking
}`

`page/another.vue`
`export default {
  slug: 'another-changed-slug', //this way
}`

**Comment by farnabaz** [comment]
According to docs:

> There are multiple ways to extend the routing with Nuxt:
    - [router-extras-module](https://github.com/nuxt-community/router-extras-module) to customize the route parameters in the page component
    - [@nuxtjs/router](https://github.com/nuxt-community/router-module) to overwrite the Nuxt router and write your own router.js file
    - Use the [router.extendRoutes](https://nuxtjs.org/api/configuration-router#extendroutes) property in your nuxt.config.js

I do suggest to use [router-extras-module](https://github.com/nuxt-community/router-extras-module). Take a look to [an example](https://github.com/nuxt-community/router-extras-module/blob/master/example/pages/languages/auto-detect-js.vue)

**Comment by smzapp** [comment]
Thank you. :D

**Comment by farnabaz** [comment]
👍 I close this issue, if you have any question feel free to ask
