### ISSUE TITLE
The environment variable passed in by nuxt start cannot replace the environment variable passed in during nuxt build?

### ISSUE THREAD

**Issue by jsbay** [nuxt/nuxt.js#8036]
### Versions

- nuxt: v2.14.4 
- node: v14.5.0

### Reproduction

1.  `yarn create nuxt-app nuxt-env-test`
2. change `nuxt-env-test/package.json`
```json
{
  "name": "nuxt-env-test",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "NUXT_ENV_BASE_URL=http://dev.myapi.com nuxt",
    "build": "NUXT_ENV_BASE_URL=http://build.myapi.com nuxt build",
    "start": "NUXT_ENV_BASE_URL=http://start.myapi.com nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "nuxt": "^2.14.0"
  },
  "devDependencies": {}
}
```
3. change `nuxt-env-test/pages/index.vue`
```html
<template>
  <div class="container">
   ....
  </div>
</template>

<script>
export default {
 // add
  created () {
    console.log(process.env.NUXT_ENV_BASE_URL); 
  }
}
</script>
```

### Steps to reproduce
- Case 1: OK
   - `yarn dev` (Equivalent to: `NUXT_ENV_BASE_URL=http://dev.myapi.com nuxt`)
   - open `http://localhost:3000` && open console
   - get `http://dev.myapi.com`
- Case 2: OK
   - `yarn build`(Equivalent to: `NUXT_ENV_BASE_URL=http://build.myapi.com nuxt`)
   - `yarn nuxt start` (Equivalent to: `nuxt start`)
   - open `http://localhost:3000` && open console
   - get `http://build.myapi.com`
- Case 3: Not OK
   - `yarn build` (Equivalent to: `NUXT_ENV_BASE_URL=http://build.myapi.com nuxt`)
   - `yarn start` (Equivalent to: `NUXT_ENV_BASE_URL=http://start.myapi.com nuxt`)
   - open `http://localhost:3000` && open console
   - get `http://build.myapi.com`
### What is Expected?
In Case 3: i've changed `package.json` as:
```json
{
   "scripts": {
     "start": "NUXT_ENV_BASE_URL=http://start.myapi.com nuxt start",
   }
}
```
I think I should get `http://start.myapi.com` but `http://build.myapi.com`. 
Is something wrong? 
And what should I do to get `http://start.myapi.com` when I run `yarn start`?

**Comment by pi0** [comment]
Hi @jsbay. It is intended behavior when using env (or `NUXT_ENV_`) that they are only during build-time and replaced in runtime bundle. You have to use `publicRuntimeConfig` instead:

```js
// nuxt.config
export default {
  publicRuntimeConfig: {
     strapiBase: 'STRAPI_BASE' // or 'NUXT_ENV_ENV_URL' 
  }
}

```vue
<template>
  <div class="container">
   ....
  </div>
</template>

<script>
export default {
 // add
  created () {
    console.log(this.config.strapiBase); 
  }
}
</script>
```

Read more: https://nuxtjs.org/guide/runtime-config
