### ISSUE TITLE
extendRoutes does not support async functions correctly

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#8037]
### Versions

- nuxt: v2.14.0
- node: ex: v12.18.2

### Reproduction

https://github.com/rchl/nuxt-issue-extendRoutes-async

### Steps to reproduce

1. Have two modules using `this.extendRoutes`
2. Have earlier module call it with an async function

### What is Expected?

The second module receives a list of extended routes.

### What is actually happening?

Error: `routes.push is not a function`.
The second module crashes on trying to modify routes as it receives a promise rather than an array.

### Additional info

[chainFn](https://github.com/nuxt/nuxt.js/blob/5e9d759d7bee6a3d32e16ef05eef988e882c600a/packages/utils/src/task.js#L12-L36) used by `extendRoutes` doesn't resolve chained functions so if one of the modules uses async function then it will pass unresolved promise to the next module.

It happens to work if there is only one module using `extendRoutes` and passing async function to it as then it's awaited by the code that triggers chained functions in the first place.

**Comment by pi0** [comment]
Hi @rchl. Should be resolved with [v2.14.5](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.5) please tell if wasn't properly working for your use case

**Comment by rchl** [comment]
Thanks.

I have a workaround for `nuxt-i18n` (using CommonJS `require` rather than ESImports) and I won't be switching back to the old way as that wouldn't be compatible with older versions.

**Comment by pi0** [comment]
Indeed making sense for backward compatibility :)
