### ISSUE TITLE
i have exclude node_modules,but not exclude vendor 

### ISSUE THREAD

**Issue by lemonpigpig** [nuxt/nuxt.js#804]
i had set the nuxt.config.js like this
<img width="490" alt="2017-05-29 1 02 10" src="https://cloud.githubusercontent.com/assets/17818782/26537091/01d85ae8-446f-11e7-82ed-bef4ab42e1d9.png">
but when i run build ,i got the error that 
ERROR in vendor.bundle.6cf639c819d39b419cb8.js from UglifyJs
Unexpected token: name (swiperPlugins) [./~/gz-vue/src/components/gz-swiper/index.js:5,0][vendor.bundle.6cf639c819d39b419cb8.js:12668,4]
i know the reason that components/gz-swiper have the syntax es6,but i am confused the config of nuxt i only set axios in the vendor,why my components are still be builted in vendor.bundle, how to config nuxt.config.js.
please tell my why, i am crazy now ,my god

**Comment by pi0** [comment]
@lemonpigpig Apologizes for any inconvenience. Are you using latest (1.0.0-alpha) version of nuxt.js? I think problem is either some `.babelrc` file exists in `gz-vue` directory hierarchy or somewhere  `gz-swiper` is directly importing a vendor. (You may confirm this by checking `vendor.bundle.xxxx.js:yy` what line is not being transformed.
