### ISSUE TITLE
Analyze possible memory leaks

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#805]
As of some users are reporting memory leaks in their production environment, I've opened this issue trying to help investigate (possible?) memory leaks causing from Nuxt or SSR engine of vue.js. We may resolve problems before stable 1.0.0 release, but it needs users contribution to help testing different conditions and providing reports & heap dumps. (Related to #678 #661 #658)

# Testing Environment
It may be better to create a new and clean repository to prevent side-effects of using third party plugins such as lodash. (they may have memory leaks too)

- **[Important]** Using **latest** nuxt.js (`1.0.0-alpha`) because it is using `runInNewContext:false` SSR options.
- Using latest stable node.js release, either `6.10.3 LTS` or `7.10.3` (recommended)
- Recommended to use docker isolated containers to prevent side effects of other processes.
- **[Important]** Use `nuxt build`, `nuxt start` and not `nuxt dev`. We are analyzing production environments.
- Recommended to use `yarn` instead of npm to ensure exact dependencies are installed.

# Testing Procedure
The article [finding-a-memory-leak-in-node-js](https://blog.risingstack.com/finding-a-memory-leak-in-node-js) may help a lot to take offline heap snapshots. Below is a suggested approach for that. If you are using nuxt programically (in express for example) you may take another approach.

In `nuxt.config.js` before `module.exports`:
- Add `heapdump = require('heapdump');` 
- Add a `setInterval` to periodically (~15min) take snapshots

You can use tools like `ab` to emulate **light** request traffic on web server.

Meanwhile you may also track memory allocation using any tool you want.  It is recommended to keep server running for more than 1 hour.

**Important** Please notice about *garbage collection*. Don't try to emulate high memory usage by applying heavy load on SSR engine it may give false positive memory leaks and performance downsides. If actually memory leak exists it may happen even with *normal* amount of requests/load. (See excellent article by eran hammer [performance-at-rest](https://hueniverse.com/performance-at-rest-75bb8fff143).

# Reports
After tests done, you may personally analyze and compare heap dumps using chrome dev tools. Also providing a report in this thread would be so nice. Please at least include following details:

- Source code repository to reproduce
- Mention [If any] used third party plugin or framework
- Testing environment specs
   - OS
   - Server Resources
   - Exact version of running nuxt and node.js 
- Heap dump analyze results / raw files. (2 files maximum)
- Screenshots of memory usage over time
- Other special notes
- Possible leak source

**Comment by fxh615** [comment]
mark to watch.

**Comment by fxh615** [comment]
i will update the version of nuxt and node to test it .

**Comment by fxh615** [comment]
axios  was used. some user remand that axios has memory leak .

**Comment by fxh615** [comment]
[Tue Jun 06 2017 16:22:45 GMT+0800 (中国标准时间)] INFO Requests: 477 (24%), requests per second: 2, mean latency: 494.3 ms
[Tue Jun 06 2017 16:22:50 GMT+0800 (中国标准时间)] INFO Requests: 486 (24%), requests per second: 2, mean latency: 594.4 ms
[Tue Jun 06 2017 16:22:55 GMT+0800 (中国标准时间)] INFO Requests: 492 (25%), requests per second: 1, mean latency: 746.9 ms
[Tue Jun 06 2017 16:23:00 GMT+0800 (中国标准时间)] INFO Requests: 497 (25%), requests per second: 1, mean latency: 1202.1 ms
[Tue Jun 06 2017 16:23:05 GMT+0800 (中国标准时间)] INFO Requests: 500 (25%), requests per second: 1, mean latency: 1106.6 ms
[Tue Jun 06 2017 16:23:10 GMT+0800 (中国标准时间)] INFO Requests: 502 (25%), requests per second: 0, mean latency: 2400.1 ms
[Tue Jun 06 2017 16:23:15 GMT+0800 (中国标准时间)] INFO Requests: 505 (25%), requests per second: 1, mean latency: 1949.1 ms
[Tue Jun 06 2017 16:23:20 GMT+0800 (中国标准时间)] INFO Requests: 507 (25%), requests per second: 0, mean latency: 2281.7 ms
[Tue Jun 06 2017 16:23:25 GMT+0800 (中国标准时间)] INFO Requests: 509 (25%), requests per second: 0, mean latency: 2230.1 ms
[Tue Jun 06 2017 16:23:30 GMT+0800 (中国标准时间)] INFO Requests: 512 (26%), requests per second: 1, mean latency: 2241.1 ms
[Tue Jun 06 2017 16:23:35 GMT+0800 (中国标准时间)] INFO Requests: 514 (26%), requests per second: 0, mean latency: 2346.1 ms
[Tue Jun 06 2017 16:23:40 GMT+0800 (中国标准时间)] INFO Requests: 516 (26%), requests per second: 0, mean latency: 2276.3 ms
[Tue Jun 06 2017 16:23:45 GMT+0800 (中国标准时间)] INFO Requests: 518 (26%), requests per second: 0, mean latency: 2402.1 ms
[Tue Jun 06 2017 16:23:50 GMT+0800 (中国标准时间)] INFO Requests: 519 (26%), requests per second: 0, mean latency: 3511.2 ms
[Tue Jun 06 2017 16:23:55 GMT+0800 (中国标准时间)] INFO Requests: 521 (26%), requests per second: 0, mean latency: 3618.2 ms
[Tue Jun 06 2017 16:24:00 GMT+0800 (中国标准时间)] INFO Requests: 523 (26%), requests per second: 0, mean latency: 2303 ms
[Tue Jun 06 2017 16:24:05 GMT+0800 (中国标准时间)] INFO Requests: 525 (26%), requests per second: 0, mean latency: 2300.3 ms
[Tue Jun 06 2017 16:24:10 GMT+0800 (中国标准时间)] INFO Requests: 527 (26%), requests per second: 0, mean latency: 2319.3 ms
[Tue Jun 06 2017 16:24:15 GMT+0800 (中国标准时间)] INFO Requests: 530 (27%), requests per second: 1, mean latency: 1793.5 ms
[Tue Jun 06 2017 16:24:20 GMT+0800 (中国标准时间)] INFO Requests: 531 (27%), requests per second: 0, mean latency: 4102.2 ms
[Tue Jun 06 2017 16:24:25 GMT+0800 (中国标准时间)] INFO Requests: 534 (27%), requests per second: 1, mean latency: 1855.8 ms

**Comment by pi0** [comment]
@fxh615 Thanks for investigating. If possible please provide more details. Also if would be so nice if you use [axios module](https://github.com/nuxt/modules/tree/master/modules/axios) so we can have more consistent tests on axios integration :)

**Comment by fxh615** [comment]
@pi0  if prosibble i will provide the code.

**Comment by zczhangchao51** [comment]
I solved my problem by update nuxt from **0.10.6** to **1.0.0-alpha3**, And I think **runInNewContext:false** is the key to solving the problem.

**Comment by fxh615** [comment]
no help

**Comment by gary149** [comment]
Are you guys investigating ? Cannot find anything related in the roadmap. thanks

**Comment by yi-ge** [comment]
@fxh615 @zczhangchao51 @pi0 The latest version fix it, bug koa middleware is still exists error...

**Comment by AndruxaSazonov** [comment]
What is a known issue with asyncData? Didn't find...
Have done some debug sessions on memory leaks: tried a page with and without asyncData using next benchmark
`ab -n50000 -c256 -t10 http://localhost:3000/`
Launched pm2 for running two instances. Without asyncData there are no leaks, but with asyncData both instances (even when benchmark has finished) continue to use more and more memory (~50 Mb / sec).

When I deleted for testing purposes in node_modules/nuxt [this line, no idea what it does exactly](https://github.com/nuxt/nuxt.js/blob/45b6c9320b33ff346a142d03b023d790ce741282/lib/app/utils.js#L24), memory usage increases, but stops after load testing.

Maybe my investigations will be helpful.

**Comment by pi0** [comment]
@AndruxaSazonov You are pointing to the right line about asyncData but memory leaks was supposed to be fixed. Are you using rc11?

**Comment by abellion** [comment]
Tested a few days ago with rc11, we also had a huge memory leaks.
As a workaround we generated the website (using `nuxt generate`) and re-implemented the middleware logic in a node server.

**Comment by pi0** [comment]
@AndruxaSazonov @abellion This problem would be with a special usage or 3rd party lib inside `asyncData`. If possible, please open a new issue with minimum reproduction and log details  and we would be happy helping this bug (if any) ASAP.

**Comment by AndruxaSazonov** [comment]
@abellion, @pi0 
It seems that i have figured out when the leaks occur. 
Consider asyncData as async and more than one request inside:
```
async asyncData ({ app }) {
  const r1 = await app.$axios.get('/request1')
  const r2 = await app.$axios.get('/request2')
  return { d1: r1.data, d2: r2.data }
}
```

My case is that leaks (on rc11) even there are no rejected promises.
Next code uses a huge amount of memory (needed to limit with node arguments, by default AFAIK it can use 1.5Gb by default without any doubts), but works without leaks:
```
asyncData ({ app }) {
  return Promise.all([app.$axios.get('/request1'), app.$axios.get('/request2')]).then(([r1, r2]) => { return {d1: r1.data, d2: r2.data} })
}
```

Maybe this is not the new issue (its likely misusage), so I post my case here.

**Comment by jdm85kor** [comment]
@pi0 hi! I'm trying to install heapdump for take a snapshot. 
But, I couln't use heapdump after upgrade node version to 8.x.x.
and..I saw below message so many times.

> ERROR in ./node_modules/heapdump/lib/main.js
Module not found: Error: Can't resolve '../build/Debug/addon' in '/project_dir/node_modules/heapdump/lib'
 @ ./node_modules/heapdump/lib/main.js 19:14-45

bnoordhuis, node-heapdump's owner, said "You probably built the add-on for the wrong arch or node version. If you use the latest version, you'll get a better error message." on 20 Jul 2017.
 
I need your help! could you talk to me how to take snapshot in these days.
