### ISSUE TITLE
middleware not rendered on the client

### ISSUE THREAD

**Issue by agoalofalife** [nuxt/nuxt.js#806]
I had a situation when middleware which must be called for all the routes, is called only on the server side
example in nuxt.config.js router: { middleware: 'check-auth' }... how in example-auth0
in file check-auth some code and contecxt isServer always returns true in the console from the server
maybe you have any ideas)

**Comment by agoalofalife** [comment]
I want like in the example example-auth0 get info from localStorage, but code run only server side

**Comment by alexchopin** [comment]
#763
