### ISSUE TITLE
路由后面含有特殊字符,%出现server error

### ISSUE THREAD

**Issue by xiuxiumomo** [nuxt/nuxt.js#8063]
### Versions

- nuxt: 
- node: 

<details open>
路由中含有特殊字符如: % localhost:3000?a=%这种，在开发环境中会出现
URIError
URI malformed
在正式环境中直接出现server error
</details>

**Comment by danielroe** [comment]
@xiuxiumomo Special characters need to be encoded. So, within your app if you are using query variables you should encode them like so:
```js
encodeURIComponent('这种')
// returns "%E8%BF%99%E7%A7%8D"
```

I hope that helps 🙂

**Comment by xiuxiumomo** [comment]
如果是自己定义的url，那就可以用你这个方法，但是如果是百度蜘蛛spider，路由是随机的，刚好含有特殊字符，会导致项目的node进程挂掉了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Daniel Roe <notifications@github.com&gt;
发送时间: 2020年9月13日 16:02
收件人: nuxt/nuxt.js <nuxt.js@noreply.github.com&gt;
抄送: xiuxiumomo <2331396362@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[nuxt/nuxt.js] 路由后面含有特殊字符,%出现server error (#8063)

**Comment by farnabaz** [comment]
@xiuxiumomo I'm not very familiar with Baidu, but for sure Baidu's spider crawls your website and uses your links. If you encode links inside your website Baidu will fetch encoded links and uses them.

**Comment by xiuxiumomo** [comment]
> @xiuxiumomo I'm not very familiar with Baidu, but for sure Baidu's spider crawls your website and uses your links. If you encode links inside your website Baidu will fetch encoded links and uses them.

thanks,I think I know what to do

**Comment by xiuxiumomo** [comment]
thanks，i know what &nbsp;to do，thanks。^_^



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ahad Birang <notifications@github.com&gt;
发送时间: 2020年9月18日 08:03
收件人: nuxt/nuxt.js <nuxt.js@noreply.github.com&gt;
抄送: xiuxiumomo <2331396362@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[nuxt/nuxt.js] 路由后面含有特殊字符,%出现server error (#8063)
