### ISSUE TITLE
I18n label data string change failed in layouts dir.

### ISSUE THREAD

**Issue by Akimyou** [nuxt/nuxt.js#8071]
I18n label data string change failed in layouts dir.

### Versions

- nuxt: latest
- node: v12.18.3

### Reproduction

https://github.com/Akimyou/test-nuxt

### Steps to reproduce

```
npm i && npm run dev
```

Click nav button to change language then U can see that:

![企业微信截图_fd000c7c-bdc0-4ac3-8abd-9da35fc87c52](https://user-images.githubusercontent.com/14974790/93037694-98008980-f675-11ea-9c91-85811d21285f.png)

### What is Expected?

All i18n text change as normal.

### What is actually happening?

The unchanged i18n label defined in `layouts` dir:

// layouts
```vue
<template>
        <h1 class="Header__Title">
          Nuxt i18n / {{ $t('test-i18n') }} / {{ testI18n }}
        </h1>
</template>

<script>
export default {
  data () {
    return {
      testI18n: this.$t('test-i18n'),
    }
  }
}
</script>
```

Why this `{{ testI18n }}` i18n label data string change failed in layouts dir. If we use it on pages dir, it is fine.

**Comment by farnabaz** [comment]
component `data` does not recompute on language change. You should use `$t` function inside template or use `computed` 
```vue
<script>
export default {
  computed: {
    testI18n() {
      return this.$t("test-i18n");
    }
  }
}
```

**Comment by Akimyou** [comment]
But this one can update, why?
https://github.com/Akimyou/test-nuxt/blob/master/pages/_lang/about.vue

**Comment by farnabaz** [comment]
On the URL change, page components are re-initiate and mount again.  
Layouts do not re-initiate if two pages are using the same layout
