### ISSUE TITLE
404 on a universal + static build

### ISSUE THREAD

**Issue by adamchipperfield** [nuxt/nuxt.js#8075]
**Current set up**
- Mode: `universal`
- Target: `static`
- General / Fallback: `false`
- Routes a generated at build time
- Hosted on Netlify

**The issue**

What we would like is if a page is a true 404 then we show the custom 404 page in Nuxt (Which I believe is managed through error.vue) However, it will only throw the Netlify 404 page.

I understand that turning Generate / Fallback to `true` will solve this, but it results in 404 paths being rehydrated on the client side when we would really like to show the 404 page instead of rehydrating. Is this possible?

**Comment by farnabaz** [comment]
Create `404.vue` inside your pages directory and implement your custom 404 page. This will generate `404.html` and netlify will use this page for 404 pages.

**Comment by azrikahar** [comment]
@farnabaz is correct here. The Nuxt.js official site at [nuxtjs.org](https://nuxtjs.org/) is doing this as well.

### Proof that it is hosted on Netlify:
![chrome_fMSKqrq2ZU](https://user-images.githubusercontent.com/42867097/93582903-b77d1680-f9d5-11ea-9919-1923dd4c3632.png)

### The error page is shown when I go to an invalid URL
![chrome_IdpvWdLAvU](https://user-images.githubusercontent.com/42867097/93582941-c4016f00-f9d5-11ea-8b5d-2498d837fd12.png)

### Here is their `404.vue` page inside the pages directory: https://github.com/nuxt/nuxtjs.org/blob/master/pages/404.vue
