### ISSUE TITLE
all requests return a html file

### ISSUE THREAD

**Issue by mizutorikunn** [nuxt/nuxt.js#8078]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
use axios to request data 

my axios config
![image](https://user-images.githubusercontent.com/14901731/93278359-028d0300-f7f7-11ea-800d-3f6e4ba40ee2.png)

my mockjs config
![image](https://user-images.githubusercontent.com/14901731/93278386-15073c80-f7f7-11ea-89b0-ca5144d8fcba.png)

the way i use axios
![image](https://user-images.githubusercontent.com/14901731/93279035-cfe40a00-f7f8-11ea-8bf7-154ee99dff15.png)

### What is Expected?
correct data

### What is actually happening?
all method of request are return a html file. but not i want
i try to change axios configs, disabled mockjs , build a new project ,but also not work.  i copy the same code to the project that created by vue cli4 not nuxt.js  is work. 
![image](https://user-images.githubusercontent.com/14901731/93178497-eb9ed000-f766-11ea-842c-a0198b481cab.png)
![image](https://user-images.githubusercontent.com/14901731/93178515-efcaed80-f766-11ea-804d-10f35b973868.png)

**Comment by climba03003** [comment]
What is your setup of nuxt? How you start the nuxt project?
If you start it by ```nuxt start``` and do not set the proxy setting to proxy the api request.
You can not contact to the api endpoint from nuxt.

**Comment by mizutorikunn** [comment]
> What is your setup of nuxt? How you start the nuxt project?
> If you start it by `nuxt start` and do not set the proxy setting to proxy the api request.
> You can not contact to the api endpoint from nuxt.
> 
> You can refer to the document here.
> https://axios.nuxtjs.org/options#proxy

i setup the project use `npx create-nuxt-app `   and i start the nuxt project use `yarn dev` or `npm run dev`.
now  i had  uploaded my axios config and mockjs config.
i use mockjs to handle the request so i think i don't need to config the proxy. right?

**Comment by climba03003** [comment]
You need ```proxy``` in NuxtJS. The main reason is that all the route is handled by NuxtJS server. NuxtJS server do not know which route should be the api and which route should be the pages, so it handle all route as page. ```proxy``` setting let NuxtJS to know that this route should be passed to others to handle.

**Comment by mizutorikunn** [comment]
> You need to use `proxy` if you want to use `@nuxtjs/axios` plugin. `@nuxtjs/axios` is a wraper of `axios` which redirect all the route to the NuxtJS server.
> 
> Solution 1:
> Create a separate API server and use `proxy` setting to proxy the route.
> 
> Solution 2:
> Create you own `axios` instance instead of using `@nuxtjs/axios` plugin.
> 
> ##### **`plugins/axios.js`**
> ```js
> import axios from "axios";
> 
> export default function(_, inject) {
>   // Inject to context as $axios
>   inject("axios", axios);
> }
> ```
> 
> ##### **`nuxt.config.js`**
> ```js
> {
>   ...,
>   plugins: ['@/plugins/axios'],
>   ...
> }
> ```

use the `axios` to replace `@nuxtjs/axios` is work! thanks 👍 
if i use `axios`, can i use `@nuxtjs/proxy` to setting the proxy? i try to config the `axios` and `proxy` in the `nuxt.config.js `  , but not work

**Comment by climba03003** [comment]
You can use ```@nuxtjs/proxy``` without having ```@nuxtjs/axios```. Just follow the [README.md](https://github.com/nuxt-community/proxy-module) of ```@nuxtjs/proxy```
