### ISSUE TITLE
Question: how to make route parameter required?

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#808]
Hi!

I want to create a route like this:
```path: "/article/:slug"```

Where the slug is required. My directory structure is:
```
/pages
---/article
------/_slug.vue
```
and the nuxt generates:
```path: "/article/:slug?"```

For every situation like this I create a workaround with index.vue inside ```pages/article``` with content:
```
<script>
  export default {
    fetch ({error}) {
      error({statusCode: 404})
    }
  }
</script>
```

Could I do this easier without creating error index?

And how about a path like this?
```/search/:page/:query```

Thanks!

**Comment by alexchopin** [comment]
Hi @awronski,
You can use `validate` props in your `articles/_slug.vue` file to check if `route.params.slug` exists.
https://nuxtjs.org/api/pages-validate
About `/search/:page/:query`:
```
/pages
---/search
------/_page
---------/_query.vue
```

**Comment by awronski** [comment]
@alexchopin 

I know about a validation. But I do not want to write extra code, this is what nuxt is all about.
Could we add a path syntax for required parameters, like '@'.

Now
```/pages/search/_page/_query.vue``` generates ```path: "/search/:page?/:query?"```

New, required params:
```/pages/search/@page/@query.vue```  would generate ```path: "/search/:page/:query"```



As a extra thing new directory convention would show what params are required without reading the source code.

**Comment by Atinux** [comment]
HI @awronski 

Actually the `_` does not make it always optional, futhermore, the @ is not authorized as a filename.

The `validate` method does the job.

Keep in mind that you can `extendRoutes`  to update the regexp associated to each route :+1:

**Comment by awronski** [comment]
@Atinux 
So how is it working? When _ is making optional and when is not.
For me the generated route.js is always optional (if there is no index file)

Yes, I know I can extended routes I am using it right now. I just wan to make a nuxt cleaner.

I know that you have more important things on your mind but generating flexible routes is really, really useful. If I make a PR would you accept it for this functionality? I can set any character as a mark as you like :)
