### ISSUE TITLE
Amcharts4 - NuxtJS - Internet explorer

### ISSUE THREAD

**Issue by Toni-hr98** [nuxt/nuxt.js#8081]
Greetings,
I am having problems with amcharts4 in a nuxtJS project on IE. The error I get is: SCRIPT1002: syntax error.
![Schermafbeelding 2020-09-15 om 10 45 17](https://user-images.githubusercontent.com/56109782/93212149-7cbf7800-f762-11ea-9d9d-7ccfd96a1a73.png)

I tried to transpile amcharts like this:
transpile: [
({isLegacy}) => isLegacy && '@amcharts',
]

But that did not work. I also tried to put: import "core-js"; at the top of the nuxt.config.js file. But that also didnt do the job.

Can someone help me?

**My files:**

**nuxt.config.js**
plugins: [
{src: '~plugins/amcharts.js', mode: 'client'},
]

**amcharts.js:**
import * as am4core from "@amcharts/amcharts4/core";
import * as am4maps from "@amcharts/amcharts4/maps";
import am4geodata_continents from "@amcharts/amcharts4-geodata/continentsLow";
import am4geodata_middleEast from "@amcharts/amcharts4-geodata/region/world/worldRegionsLow";

import Vue from "vue";

Vue.prototype.$am4core = () => {
return {
am4core,
am4maps,
am4geodata_continents,
am4geodata_middleEast
}
}

**package.json**
"dependencies": {
"@amcharts/amcharts4": "^4.10.2",
"@amcharts/amcharts4-geodata": "^4.1.17",
"nuxt": "^2.14.4",
}

**Comment by Spreizu** [comment]
If transpiling the amcharts package does not help, it probably means that one or more of the amcharts package dependencies need to be transpiled instead.

**Comment by Toni-hr98** [comment]
**Solution:**

https://github.com/amcharts/amcharts4/issues/2907#issuecomment-712285831
