### ISSUE TITLE
Custom routes with i18n

### ISSUE THREAD

**Issue by bdebever** [nuxt/nuxt.js#809]
Hi there, 

I would like to add routes to my application with data coming from a json file, and on my application using the i18n example . 

On the root page, my code looks like this : 
```vue
<nuxt-link :to="element.id" class="work" >
  <div class="desc">
    <h3>{{ element.name }}</h3>
     <span>{{ element.description }}</span>
  </div>
</nuxt-link>
```
```js
data() {
  return {
     portfolioElements: this.$i18n.t('portfolio')
  }
}
```

And, on my `_id.vue` page, the code looks like this 
```js
async asyncData ({ params }) {
  return {
    portfolioElements: this.$i18n.t('portfolio')[0]
  }
}
```

I know this should be wrong, but I'm not sure how to implement routes using the `_lang` attribute as well! 
Any help would be appreciated

Thanks

**Comment by alexchopin** [comment]
Hi, you can access to `_lang` value with `params.lang` in the asyncData function.
