### ISSUE TITLE
Throwing error from new fetch does not redirect to custom error page

### ISSUE THREAD

**Issue by hypervillain** [nuxt/nuxt.js#8092]
Hi! It seems that calling `$nuxt.error` from inside the new `fetch` function does not properly redirect to the error layout, like `asyncData` does. It seems that prefetching the layout on server-side does not work properly as the returned HTML contains an empty comment rather than the actual content.

### Versions

- nuxt: 2.14.5
- node: 14.4.0

### Reproduction

https://nuxt-fetch-error.netlify.app/ (Thanks @lihbr 👋)

### Steps to reproduce

Create a `layouts/error.vue` page. Call fetch from inside a component and throw an error.

### What is Expected?

A proper redirection to the error page when Nuxt throws from inside fetch.

Thanks!

**Comment by drewbaker** [comment]
Can you include the source code for that netlify site?

**Comment by hypervillain** [comment]
Sure: https://github.com/hypervillain/nuxt-custom-error-repro

**Comment by drewbaker** [comment]
You can’t use $nuxt.error in fetch() unfortunately. 

It’s explained why here: https://nuxtjs.org/blog/build-dev-to-clone-with-nuxt-new-fetch/#error-handling

**Comment by hypervillain** [comment]
Thanks for the link, it definitely clears things up.

Do you know how I could let users pass their custom error template then? I'm working on a components library that fetches data in behalf of users so I can't display the error message like the example does. I managed to do it by registering a global page-not-found component and rendering it inside my template but I'm curious if more elegant solutions exists. You can find my fetch component [here](https://github.com/prismicio/slice-machine/blob/master/packages/vue-slicezone/PageFetch.vue) if that matters.

Thanks for your help!

**Comment by drewbaker** [comment]
So the idea with fetch() is that it is component level data. So I'd say it's a good idea to have components show local UI if there is a an error (or perhaps a toast style popup). I think it makes more sense for a page level fetch() to handle redirecting to a custom error page, which it will if you throw that error like in the dev-to-clone example.

**Comment by DreaMinder** [comment]
I have a similar issue: some pages have a component with dynamic content inside, it's not convenient to use asyncData in my case. So every time I run `nuxt generate`, I'd like the component to fail the entire build if its fetch-request is failed. But the only solution I found is to use unsafe variables in a component template, so the build will fail because of `Cannot read property of undefined` error.
