### ISSUE TITLE
Upgrade from 2.12.2 to 2.14.5 caused build to stop generating _nuxt/commons/.*****.js

### ISSUE THREAD

**Issue by Rezendestroyer** [nuxt/nuxt.js#8094]
### Versions

- nuxt: 2.14.5
- node: 12.16.3

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

The app is 7 months old and is delivered via CI/CD pipelines to run in Kubernetes.

[nuxt.config.js.txt](https://github.com/nuxt/nuxt.js/files/5247930/nuxt.config.js.txt)

### Steps to reproduce
Using an application with Nuxt at 2.12.2 version
Update to version 2.14.5  (we tried to update to 2.13.3 and the problem was the same)
Build the app (with no errors)

### What is Expected?
`npm run build / npm run start` starts the app and all Nuxt supporting JS code is available from webserver.

### What is actually happening?
Run the app and a 404 statusCode is got from URL "host/_nuxt/commons/.*****.js"

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/45406211/93640170-83532700-f9d0-11ea-9916-80a4babe7c96.png)

**Comment by pi0** [comment]
Using named chunks is disabled by default for nuxt 2.x so this issue should be fixed by upgrading to latest :)
