### ISSUE TITLE
too many pages and components will effect initial page load time?

### ISSUE THREAD

**Issue by thunderwin** [nuxt/nuxt.js#8095]
guys I m being using nuxt for a while ,  for small project it's perfect!

now I have a big project with a  lots of pages, components, so many features, Its SAAS platform.

I wanna use Nuxt to finished the whole project.   include the admin area. the user center, control panel 

I wanna know it's the right way to do?   or should I split it to 2 front-end projects?

real thanks for the suggestions..

**Comment by raphaelarias** [comment]
I believe routes are imported as needed. By being careful with what you import in your pages and what you add as global you should be fine.

**Comment by yeahalrightcoolswo** [comment]
Anyone been having trouble with error code -8509

SWO INDUSTRIES
________________________________

**Comment by thunderwin** [comment]
@raphaelarias   Thank you, When you say "routes", do you mean I need custom routes ?   I shouldn't relay on the default nuxt route system right?

I kind of don't know which specific doc I need looking at..  someone give a guide ?

**Comment by raphaelarias** [comment]
@thunderwin You can and probably should relay on the default routing system, it will do everything for you. :)
