### ISSUE TITLE
nuxt-link 无法显示完整路径

### ISSUE THREAD

**Issue by 2292912322** [nuxt/nuxt.js#8098]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
为了seo，我使用nuxt-link做页面跳转，但发现跳转路径只是显示类似 /goods/detail，无法加上域名，方便可以录入完整的路径

**Comment by farnabaz** [comment]
`nuxt-link` is designed to handle internal URLs in order to improve performance and simplify navigation between internal pages. If you want to create an external link consider using `<a>` tag.  
read more in [official docs](https://nuxtjs.org/guides/features/nuxt-components#the-nuxtlink-component)
