### ISSUE TITLE
1.0 about when it can be released? Thank you

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#81]
1.0 about when it can be released? Thank you

**Comment by Atinux** [comment]
Hi @yuchonghua 

The `1.0` will be released around the end of January 2017.

You can take a look at our roadmap to see what's left before the 1.0: https://github.com/nuxt/nuxt.js/projects/1

**Comment by yuchonghua** [comment]
Thank you very much, I developed a ddv, but is still in the debugging stage, the time do not know whether they can get nuxt support is ddv is a type of management tool pm2, but ddv more inclined to multi-site, but ddv is not very Perfect, can only run on ubuntu, the other system is further support, hope to get nuxt support, ddv is a multi-site management module that provides the http-server interface
