### ISSUE TITLE
The command 'nuxt build' finished but did not exit after 5s

### ISSUE THREAD

**Issue by gera2ld** [nuxt/nuxt.js#8104]
I cannot find an open issue for this problem but it still exists, **even in a newly created nuxt project,** so there is little chance that it's caused by timers or something else in my components:

```
⚠ Nuxt Warning                                                                     │
   │                                                                                      │
   │   The command 'nuxt build' finished but did not exit after 5s                        │
   │   This is most likely not caused by a bug in Nuxt.js                                 │
   │   Make sure to cleanup all timers and listeners you or your plugins/modules start.   │
   │   Nuxt.js will now force exit                                                        │
   │                                                                                      │
   │   DeprecationWarning: Starting with Nuxt version 3 this will be a fatal error
```

### Versions

- nuxt: ^2.14.6 latest
- node: 14.9.0

### Reproduction

Follow [the guide](https://nuxtjs.org/guides/get-started/installation/) to create a minimal project.
I've created one here: <https://github.com/gera2ld/nuxt-bug>

### Steps to reproduce

- Create a minimal nuxt project according to the guide or clone my minimal project: <https://github.com/gera2ld/nuxt-bug>
- `yarn`
- `yarn build`

### What is Expected?

The build process should exit after finishing and should not show the warning.

### What is actually happening?

The build process hangs and shows the warning above.

**Comment by gera2ld** [comment]
Something really weird happens, everything works now without any change to the code.
I guess there might be something wrong with the Internet for some time, sockets hung and prevented the process from exiting.

**Comment by gmRr7** [comment]
R
