### ISSUE TITLE
Setting trailingSlash to false will not render default child of nested route

### ISSUE THREAD

**Issue by defusevenue** [nuxt/nuxt.js#8108]
### Versions

- nuxt: 2.12.2
- node: 2.12.2

### Reproduction
Sandbox: https://codesandbox.io/s/crazy-mclean-lrwno

### Steps to reproduce
1. On index.vue click the link "Click here to go to user"
2. Click the link "Click here to go to nested route" (Notice that you are redirected to `/user/test/` not `/user/test`)
3. Navigate directly to `/user/test` (Default child is not rendered)

### What is Expected?
1. When navigating directly to `/user/test` the default child `pages/user/_id/index.vue` should be rendered
2. When navigating using `nuxt-link` should be redirected to `/user/test`

### What is actually happening?
1. At `/user/test` the default child `pages/user/_id/index.vue` is not rendered
2. When navigating `nuxt-link` the user is redirected to `/user/test/`

It seems like this issue is the same as https://github.com/nuxt/nuxt.js/issues/6593 but it hasn't been fixed in the latest version. The current workaround is to not set `trailingSlash: false` and manually remove the trialing slash. It is my understanding from the documentation that setting `trailingSlash: false` will automatically remove trailing slashes all routes and Nuxt will redirect users in accordance to this policy.

**Comment by manniL** [comment]
Related: #7823
