### ISSUE TITLE
Default nuxtjs app with vuetify / Cannot GET

### ISSUE THREAD

**Issue by Salman-Kashfy** [nuxt/nuxt.js#8112]
Hello,

I have default installation of nuxt / vuetify app . It is served on plesk with ngix. But it gives error of cannot GET on first load, on page refresh, it works ok. What could be the error. Here is the link of site http://test.saiyaara.tk/

Also, I have followed this repo to make use of server.js file for ngix
https://github.com/pi0/nuxt-plesk-example

**Comment by pruthvi2103** [comment]
Hey There @Salman-Kashfy  I tried it seems to work fine, even tried in incognito mode

**Comment by Salman-Kashfy** [comment]
> Hey There @Salman-Kashfy I tried it seems to work fine, even tried in incognito mode


https://user-images.githubusercontent.com/28507426/103377931-92369300-4b02-11eb-816c-951524d14c7e.mp4


Sorry for late response. Above is a 20sec video recording of the error, its recorded @ 31st Dec 2020.
On first attempt, the site does'nt work, after attempt it works well for all devices. It seems first url request activates the nginx server and its keeps activated for a time, then deactivates after few days. I dont know whats the problem. I am using PM2.

P.S its a plesk server with ubuntu OS
