### ISSUE TITLE
Broken i18n example

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt.js#812]
@Atinux I tried to run the i18n example without success. I used the one in the dev branch that corresponds to Nuxt 1.0.0. Unfortunately, I need to manually reload the page to switch the locale.

It seems `route.path` always returns `/` in **plugins/i18n.js**.

Moreover, **vue-i18n** has a new version 7.0.0 since May 29.

**Comment by Atinux** [comment]
It seems to happen only in development mode, from the hot-reload part.

I'll investigate this issue.

**Comment by Atinux** [comment]
The example will now work for the next release (alpha3)

**Comment by Atinux** [comment]
Fix with https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-alpha.3
