### ISSUE TITLE
<unix-socket> is already in use

### ISSUE THREAD

**Issue by ishanjain28** [nuxt/nuxt.js#8121]
### Versions

- nuxt:  @nuxt/cli v2.14.5
- node:  v14.12.0

### Steps to reproduce

1. Start any nuxt project like `npx nuxt start --unix-socket /var/run/tomato.socket`

2. Stop nuxt by pressing Ctrl + C. 

3. Try to start the project again with, `npx nuxt start --unix-socket /var/run/tomato.socket`. 

### What is Expected?

It should start the app successfully like it did the first time it was started.

### What is actually happening?

It fails with this error

```
 FATAL  Address /var/run/tomato.socket is already in use.                                                                                08:49:51

  at Server.setupListenHandle [as _listen2] (net.js:1300:21)
  at listenInCluster (net.js:1365:12)
  at Server.listen (net.js:1462:5)
  at server (node_modules/@nuxt/server/dist/server.js:494:32)
  at new Promise (<anonymous>)
  at Listener.listen (node_modules/@nuxt/server/dist/server.js:492:27)
  at Server.listen (node_modules/@nuxt/server/dist/server.js:931:20)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-start.js:123:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2810:7)


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │   ✖ Nuxt Fatal Error                                           │
   │                                                                │
   │   Error: Address `/var/run/tomato.socket` is already in use.   │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯
```

The issue here is, Nuxt is not `unlink`-ing the unix socket before trying to `bind` to that unix socket.

**Comment by janswist** [comment]
I have the same problem

**Comment by KStenK** [comment]
Any updates or alternatives on how to reconnect to the existing unix-socket?

**Comment by KStenK** [comment]
I'm not sure if that workaround works for you, but I'm using docker and I wrote this **entrypoint.sh** bash script to fix that problem for my case.

```
#!/bin/bash

SOCKET=/tmp/frontend/nuxt.${TASK_ID}.sock

# remove old socket if that exists (nuxt do not rebind to the existing socket)
if test -S "$SOCKET"; then
  rm "$SOCKET"
fi

# turn on bash's job control
set -m

# start nuxt production server and put it on the background
node node_modules/nuxt/bin/nuxt.js start --unix-socket "$SOCKET" &

# wait for the new UNIX socket file to appear
while ! test -S "$SOCKET"; do
  sleep 1
done

# chmod new UNIX socket file
chmod 777 "$SOCKET"

# foreground node server from the background
fg %1
```

**Comment by ishanjain28** [comment]
Another solution is to simply `unlink` it manually after exiting from `nuxt`. 

There are few ways to do this. 

1. catch `sigstop`/`sigkill`/`sigterm` signals and run, `/usr/bin/unlink <path-to-unix-socket>`. 
2. In shell scripts, run the same command after exiting from `nuxt`.

**Comment by lostangelwangyang** [comment]
I have the same problem. I use supervisor but found no way to remove the socket file automatically. Any suggestion?
