### ISSUE TITLE
How to get the publicRuntimeConfig in outside function/hooks?

### ISSUE THREAD

**Issue by liaoliaojun** [nuxt/nuxt.js#8123]
### Is your feature request related to a problem? Please describe.
I don't know where to get PublicRuntimeConfig in  `no nuxt instances`,  as if  function/hooks，help PublicRuntimeConfig be the global config，

### Describe the solution you'd like
example set axios-baseURL
```
import runtime from './client/static/runtime-args.json'
export default {
  publicRuntimeConfig: {
    apiBase: runtime.NUXT_ENV_HTTP_API || '/',
  },
  ...

axios.js: 
axios.defaults.baseURL = nuxt.$config.NUXT_ENV_HTTP_API || '/'
```

**Comment by danielroe** [comment]
@liaoliaojun The ideal place to do this would be in a plugin. So for example:

`~/plugins/myplugin.js`
```js
import axios from 'axios'

export default ({ $config }) => {
  axios.defaults.baseURL = $config.NUXT_ENV_HTTP_API || '/'
}
```

You can find out more in the [plugins documentation](https://nuxtjs.org/guide/plugins/).
