### ISSUE TITLE
Use pnpm as package manager too

### ISSUE THREAD

**Issue by danysz** [nuxt/nuxt.js#8124]
### Is your feature request related to a problem? Please describe.
I prefer to use pnpm as my package manager instead of npm. It's saving a lot of space and also the compilation process is faster.

### Describe the solution you'd like

Provide the pnpm as an option when a new app is created.

### Describe alternatives you've considered

Another solution is that after all the files and the structure is created not to run the npm install. Just stop and each user will decide if to continue and how.

**Comment by bodrych** [comment]
https://github.com/nuxt/create-nuxt-app/issues/367

**Comment by danielroe** [comment]
Closing in favour of nuxt/create-nuxt-app#367
