### ISSUE TITLE
ERROR  inject('content', value) has no value provided

### ISSUE THREAD

**Issue by febrihidayan** [nuxt/nuxt.js#8129]
### Versions

- nuxt: v2.14
- node: v12.18.3

When I do nuxt production and run it locally it runs smoothly. However, when I upload it to hosting and do some configuration and then run it a server error occurs. Did the error occur because I am using the @nuxt/content module, Before I used it everything looks fine.

file server.js
```js
const { Nuxt, Builder } = require('nuxt')
const path = require('path')
const app = require('express')()
const config = path.join(__dirname, './nuxt.config.js')

// We instantiate nuxt.js with the options
config.dev = (process.env.NODE_ENV === 'production')
const nuxt = new Nuxt(config)

async function start() {
    await nuxt.ready();
    
    // Render every route with Nuxt.js
    app.use(nuxt.render)
    
    // Listen the server
    app.listen()
}

start()
```

file stderr.log
```log
ERROR  inject('content', value) has no value provided

  at inject (.nuxt/index.js:159:0)
  at plugin_server (.nuxt/content/plugin.server.js:9:0)
  at createApp (.nuxt/index.js:231:0)
  at async module.exports.__webpack_exports__.default (.nuxt/server.js:81:0)
```

**Comment by febrihidayan** [comment]
Close [Does this work in SPA mode??](https://github.com/nuxt/content/issues/144#issuecomment-700744308)

**Comment by nph278** [comment]
I am having this problem, how did you get it to work?

**Comment by febrihidayan** [comment]
@nph278 I managed to do it by following the configuration on the following link https://nuxtjs.org/docs/2.x/internals-glossary/nuxt-render

**Comment by leku451** [comment]
I am having this same issue as well, unable to proceed.
