### ISSUE TITLE
Disable 'namespaced' in vuex when a module separated into files (actions.js, state.js and so on)

### ISSUE THREAD

**Issue by Lindar90** [nuxt/nuxt.js#8130]
### Versions

- nuxt: 2.14.5
- node: v12.18.3

### Reproduction

There is no possibility to disable 'namespaced' for a module when the module is broken down into separate files: state.js, actions.js, mutations.js and getters.js.

The following works only for single file modules:
```
export const namespaced = false
```

### Link to reproduce:

https://codesandbox.io/s/codesandbox-nuxt-forked-3p7ok?file=/store/moduleNotNamespaced/getters.js

### What is Expected?

`namespaced: false` is set for a module

### What is actually happening?

`namespaced: true` is set for a module

**Comment by mikheeff** [comment]
I also reproduced this issue. Any activity here or info?

**Comment by Lindar90** [comment]
I confirm that it's still reproducible on v2.15.3. As far as I can see from autogenerated store.js file, 'namespaced' is strictly set/hardcoded here:
![image](https://user-images.githubusercontent.com/3606473/111364878-da496880-86a2-11eb-9d37-7397fc67d0e4.png)

CC: @danielroe

**Comment by TakCastel** [comment]
Please reopen, this is still an issue for me.
