### ISSUE TITLE
When using `redirect`, `async nuxtServerInit` is not being executed

### ISSUE THREAD

**Issue by sandoche** [nuxt/nuxt.js#8135]
### Versions

- nuxt: 2.14.0
- node: v12.18.3

### Reproduction

Run async code in `async nuxtServerInit` that loads data to vuex.
Use `redirect` to a middleware

### What is Expected?

The data loaded into `async nuxtServerInit` should be present after the redirect.

### What is actually happening?

I get an error because the data is not loaded.
I had to move the code from `nuxtServerInit` to `asyncData` of all my pages to solve the issue.

**Comment by gryphonmyers** [comment]
To clarify repro (at least for me): 

1. Load any page configured to use a middleware that redirects to another route utilizing data fetched during nuxtServerInit
2. Note that upon loading the redirected route, any data from nuxtServerInit will be missing
3. Refresh the page to see the nuxtServerInit data appear

**Comment by bissolli** [comment]
Did you guys find a solution for that? I am also facing the issue.

**Comment by thiagodelgado111** [comment]
I think I have the same problem :/

**Comment by danielroe** [comment]
@thiagodelgado111 Would you provide a reproduction? 🙏

**Comment by thiagodelgado111** [comment]
Let me try to put something together @danielroe

**Comment by thiagodelgado111** [comment]
This is what I have for now. I think rather than a bug I'm actually doing something stupid :sweat_smile: 
https://github.com/thiagodelgado111/nuxt-8135

**Comment by NIO-ADR** [comment]
NYSE 


Sent from the all new AOL app for iOS


On Sunday, May 23, 2021, 5:16 PM, Daniel Roe ***@***.***> wrote:




@thiagodelgado111 I can't get your reproduction to run as it relies on various tokens and you've not said what you expect to happen or what isn't working for you.

However, in case it's helpful, when you perform a redirect on the server side, the Nuxt server returns a 302 redirect and the browser then makes a new/fresh request to the new URL. There is no way to 'persist' data across these two requests unless you do it with cookies.

However, for each of these two requests, asyncData will be executed. Sample reproduction.
