### ISSUE TITLE
runtimeConfig with programmatic usage

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#8136]
Reported by @crutch12 (https://github.com/nuxt/nuxt.js/pull/6868#issuecomment-701369740)

### Reproduction

**server.js**
```js
const { Nuxt, Builder } = require('nuxt');
const nuxt = new Nuxt(config);
await nuxt.ready();
```

**nuxt.config.js**
```js
export default {
    publicRuntimeConfig: ($env) => {
      return {
        NODE_ENV: $env.NODE_ENV,
        wtf: 'WTF',
      };
    },
}
```

The resulting **script**
```
<script>window.__NUXT__={config:{},staticAssetsBase:void 0}</script>
```
instead of
```
<script>window.__NUXT__={config:{NODE_ENV:"development",wtf:"WTF"},staticAssetsBase:void 0}</script>
```

### What is Expected?

We should expose a utlity to support runtimeConfig with programmatic usage

**Comment by crutch12** [comment]
It works correctly with `loadNuxt`/`build`  [methods](https://nuxtjs.org/api/nuxt/) and doesn't work with legacy methods (like in issue description)

**Comment by pi0** [comment]
Hi @crutch12 sorry then i think got you wrong. If working with `loadNuxt` there is no reason to backport it for legacy usage because all of the env integration magic is done by new programmatic [loadNuxtConfig](https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/load.js#L15). Moving it to `Nuxt` class requires a bigger refactor...

**Comment by crutch12** [comment]
@pi0 as I wrote in [#6868 (comment)](https://github.com/nuxt/nuxt.js/pull/6868#issuecomment-701369740) :D
> It would be great to deprecate legacy syntax or add support for runtimeConfig

Just show **DEPRECATED** warning when someone uses old syntax and it will solve issue. I spent about 1 hour to get it out :)

**Comment by pi0** [comment]
@crutch12 I see. Actually we may detect legacy programmatic using `_cli` and `_start`/`_build` flags but it is error prone and also many users are still using that syntax with `dotenv` / `@nuxtjs/dotenv` so it is also not easy to deprecate at all for nuxt2. Maybe we can add a note in documentation?

**Comment by crutch12** [comment]
@pi0 If adding a note in documentation is the simplest way - ok, fine.

Do I have to create PR for this or you want add note by it yourself?

**Comment by pi0** [comment]
@crutch12 That would be fantastic if want to contribute :heart: (PS: don't forget https://hacktoberfest.digitalocean.com)
