### ISSUE TITLE
n-link external link handling

### ISSUE THREAD

**Issue by adamchipperfield** [nuxt/nuxt.js#8138]
Is there a way to handle external links when using the `n-link` component?

Currently an external link passed is treated as a relative link. Is there a way I can jump in and extend that functionality to work with external links?

**Comment by adamchipperfield** [comment]
Biggest use case for this is when you don't know if the given URL is going to be internal or external.

**Comment by danielroe** [comment]
@adamchipperfield I'd suggest a functional component that either renders a normal `<a>` or a `<NuxtLink>` based on what is passed in.

**Comment by drewbaker** [comment]
This is how we handle that: https://github.com/funkhaus/fuxt/blob/master/components/WpLink.vue
