### ISSUE TITLE
child_process & fs module not found 

### ISSUE THREAD

**Issue by aamodpisat** [nuxt/nuxt.js#814]
Hi Team,
We are using our library to fetch the data. Using this library in nuxt, we are getting an issue of child_proccess and fs modules not found while webpack build. But when we add the `target: node ` into your nuxt file, nuxt.js, this error doesn't occur. So, is there any better way or any alternative solution. ?

**Comment by piyushchauhan2011** [comment]
Switching to `axios` could be worth ? @aamodpisat https://github.com/mzabriskie/axios

**Comment by Atinux** [comment]
Make sure that you library works also on client-side @aamodpisat 

https://github.com/mzabriskie/axios is the right library to make ajax and http request for isomorphic applications.
