### ISSUE TITLE
use nodejs package ?

### ISSUE THREAD

**Issue by titoff002** [nuxt/nuxt.js#8144]
Hello, 

is it possible to include and use an npm / package made for nodejs in nuxt? 

I was wondering if I could use this "https://github.com/keycloak/keycloak-nodejs-connect" package in nuxt?

Thank you.

**Comment by danielroe** [comment]
@titoff002 Yes, you can, but only in the server side. You will probably want to wrap any code that references this module in `if (process.server) {}`
