### ISSUE TITLE
Multiple pages and layout directories, for modules and monorepos

### ISSUE THREAD

**Issue by duurland** [nuxt/nuxt.js#8145]
### Is your feature request related to a problem? Please describe.

I'd like to decouple certain parts of my app into their own modules and go for a monorepo approach, while still making use of nuxt's file tree structure for pages and layouts. 

For example:

```app/
 ├─ client/
 │   ├─ pages/
 │   ├─ layouts/
 │   ├─ (other nuxt folders...)
 │   └─ nuxt.config.js
 └─ packages/
     └─ nuxt-module-admin-dashboard/ 
        ├─ pages/
        │   └─ dashboard/
	│       └─ index.vue // { name: 'dashboard', path: '/dashboard', ... }
        ├─ module.js
        ├─ server-middleware.js
        └─ package.json
```

### Describe the solution you'd like

Support for multiple `pages`/`layouts`-directories (could be extended to other dirs too, `assets`, `static`, etc). 

Examples:

#### Module
```js
export default function () {
  this.addPages(path.resolve(__dirname, 'pages'))
}
```
#### nuxt.config.js
```js
dir: {
  pages: [   // array support
    './pages',
    '../packages/nuxt-module-admin-dashboard/pages',
    '../packages/*/pages'   // glob support?
  ]
}
```
___
Related issues: https://github.com/nuxt/nuxt.js/issues/2522, https://github.com/nuxt/nuxt.js/issues/7879 and https://github.com/nuxt-community/modules/issues/148

Thoughts or ideas?

**Comment by joriewong** [comment]
WIP #8188

**Comment by joriewong** [comment]
@duurland you can use [create-routes](https://www.npmjs.com/package/create-routes) temporarily.

**Comment by pi0** [comment]
Multi app will be natively supported with nuxt3. Please see https://github.com/nuxt/rfcs/issues/30 for context.

**Comment by Rigo-m** [comment]
> @duurland you can use [create-routes](https://www.npmjs.com/package/create-routes) temporarily.

@joriewong could you please open source the create routes package? It's useful but it has some bugs, I need to fork it if possible.
