### ISSUE TITLE
Route wrong generated

### ISSUE THREAD

**Issue by djcheeky** [nuxt/nuxt.js#8148]
I have a .vue file in a subdirectory of the pages folder. When I generate the project this Route gets generate as BGA/ not BGA. When I visit the page on BGA I get the "Page not found" Error when I visit the page on BGA/ the page could be found but the images cannot be loaded because the get the path of "items/BGA/images/BGA.png" instead of "items/images/BGA.png"

Thanks for the Help

**Comment by JoanMbela** [comment]
can i see the part of the code where the img tag is. this might be caused by the fact that you use absolute paths.
try to use relative ones.
