### ISSUE TITLE
Issue: Inline `window.__NUXT__` script

### ISSUE THREAD

**Issue by sjoerdloeve** [nuxt/nuxt.js#8149]
When I generate my project, it always contains a little piece of inline script:
![Schermafbeelding 2020-10-05 om 16 16 22](https://user-images.githubusercontent.com/25615119/95091958-5e2c1b80-0727-11eb-885d-0b605ccd8c70.png)

How can I get this to a separate file to match my CSP settings?

### Versions

- nuxt: v2.14.3
- node:v 12.1.0
- yarn: 1.22.4

### Reproduction

1. Create project
2. nuxt generate
3. Check the source code (at the bottom)

### What is Expected?

Seperate file with this JS code in it

### What is actually happening?

It stays in the source code and the browser is reporting an error:

`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' appears in neither the script-src directive nor the default-src directive of the Content Security Policy.`

**Comment by adam-gipril** [comment]
Would love to see resolution to this — seems important!

**Comment by phongvuhyuet** [comment]
any progress on this? I can't config csp
