### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined when "npm run generate"

### ISSUE THREAD

**Issue by linghx** [nuxt/nuxt.js#815]
'then' method is so used :

    this.$store.dispatch('getOwnerDeptment')
        .then((response) => {
            let result = response.data;
            if (result.code === 0) {
                this.deptList = result.data;
             }
        })

**Comment by Atinux** [comment]
@linghx Make sure that you return a `Promise` in `getOwnerDeptment` action.

**Comment by linghx** [comment]
@Atinux 
in my action:
export const getOwnerDeptment = function ({commit, state}, preload) {
  return axios.get(process.env.baseUrl + '/department/getOwnerDept', {
    params: preload || {}
  })
};
