### ISSUE TITLE
async fetch() breaks v-for in child component

### ISSUE THREAD

**Issue by samlfair** [nuxt/nuxt.js#8150]
### Versions

- nuxt: ^2.14.6
- node: 14.7.0

### Reproduction

`~/layouts/default.vue` contains an `async fetch()` to fetch content from Prismic.

`~/pages/portfolio/index.vue` contains a component `~/components/slices/Featured.vue` (a post list), which contains a `v-for` loop that cycles through a list of posts and renders them with another component, `~/components/FeaturedPost.vue`. `~/components/FeaturedPost.vue` makes an API call to get the title and image for the post.

When the `async fetch()` method is included in the layout, the API data for FeaturedPost[n] gets applied to FeaturedPost[n+1]. FeaturedPost[0] is empty.

Does not happen when `/portfolio` is the first page loaded — only when it is navigated to subsequently.

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

To reproduce, download this branch:

https://github.com/samlfair/claire-v4/tree/async-vfor

Run `npm run generate` and then `npm run start`. Start at any page, and then navigate to `/portfolio`. You should see the missing post. To fix the error, open `~/layouts/default.vue`, and comment out the `async fetch()` method and uncomment the `config` data, lines 38-70 (to prevent breaking errors).

The post list is rendered with this component: https://github.com/samlfair/claire-v4/blob/async-vfor/components/slices/Featured.vue

Each item in the list is rendered with this component: https://github.com/samlfair/claire-v4/blob/async-vfor/components/FeaturedPost.vue

### What is Expected?

Posts should render in order.

### What is actually happening?

First post is blank, then posts are rendered in order.

**Comment by lihbr** [comment]
I had a look with Sam this afternoon at this issue and inspected bundle output `payload.js` for the portfolio page.

I think the fetch resolver for static payload is struggling at matching payload with components here and not sure it's either a legit bug or a stupid error somewhere we failed at figuring out 🤔
