### ISSUE TITLE
Dynamic Import Routes

### ISSUE THREAD

**Issue by RailgunWinjoy** [nuxt/nuxt.js#8154]
How to dynamic import route 

route.js

`
 const Home = () => import('@/pages/index.vue'); 
 export default [{
        path: '/',
        name: 'home',
        component: Home
    },
 `

nuxt.config.js
`   
  router: {
        middleware: 'authenticated',
        extendRoutes(nuxtRoutes, resolve) {
            nuxtRoutes.splice(0, nuxtRoutes.length, ...routes.map((route) => {
                return {...route, component: route.component }
            }))
        }
    }`

It throws error :   `args[0].includes is not a function`

**Comment by danielroe** [comment]
@RailgunWinjoy Nuxt code-splits page routes by default (see [docs](https://nuxtjs.org/guides/features/file-system-routing)).

If that doesn't solve things for you, I'd appreciate seeing a reproduction - just post it here and I'll happily comment on it :grinning:
