### ISSUE TITLE
Same code but building failed on Linux server

### ISSUE THREAD

**Issue by RailgunWinjoy** [nuxt/nuxt.js#8158]
I finished developing my project on Windows 10 and i tried  to find a way to deploy it
And i ended up copy the code on my Ubuntu server. But when i run npm i , npm start . ANd the below errors throw
` 
 
 ERROR  Failed to compile with 5 errors                                                                                              friendly-errors 04:49:23

This dependency was not found:                                                                                                       friendly-errors 04:49:24
                                                                                                                                     friendly-errors 04:49:24
* @/graphql/mutations/pagestatus in ./base/pageStatusMixin.js                                                                        friendly-errors 04:49:24
                                                                                                                                     friendly-errors 04:49:24
To install it, you can run: npm install --save @/graphql/mutations/pagestatus                                                        friendly-errors 04:49:24
                                                                                                                                     friendly-errors 04:49:24
                                                                                                                                     friendly-errors 04:49:24
These relative modules were not found:                                                                                               friendly-errors 04:49:24
                                                                                                                                     friendly-errors 04:49:24
* ../../base/watchStatusMixin in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/Auth/Overview.vue?vue&type      =script&lang=js&
* ../base/watchStatusMixin in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/OverviewCard.vue?vue&typ      e=script&lang=js&, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/Episode.vue?vue&type=script&lang=js&

`

**Comment by RailgunWinjoy** [comment]
I finically solved this !
Because of the file name is case sensitive  in Linux compared to Windows

**Comment by danielroe** [comment]
Great! :slightly_smiling_face:
