### ISSUE TITLE
Different bundles for different pages

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#816]
Hi,
My application has two categories of pages. One set uses a specific set of  js and css. Other pages has a totally different js and css files. How can I create two different bundles.
For eg: mydomain.com/foo - This has carousel and some other theme files and css.
 mydomain.com/bar - This has our own custom js and css which is not needed in /foo

I don't want the css from /bar to be included in /foo because it will affect the styles.

How to achieve this?
Thanks for the help.

**Comment by piyushchauhan2011** [comment]
Why aren't we using scoped css ? @shyamchandranmec  I think if you stick to scoped css it will probably be better as nuxt.js can figure out code splitting automatically based on pages.

**Comment by shyamchandranmec** [comment]
@piyushchauhan2011 
We have developed a bootstrap like framework for all our in-app pages. So there are some global styles for inputs and radio buttons. I can fix this by adding custom classes. But even if I do that I don't want those un used css and js to get downloaded in the other pages.

The other pages are basically build out of a theme which we bought from themeforest. So they will have their own global styles. And these styles are not needed in the in-app pages.

**Comment by Atinux** [comment]
@shyamchandranmec Use the layouts instead and include the corresponding CSS for each layout.

For you example, you can have `layouts/bar.vue` and `layouts/foo.vue`, the layouts are code-splitted so the CSS won't be included in the global CSS :+1:

**Comment by shyamchandranmec** [comment]
@Atinux Thanks for the suggestion

**Comment by anthonygore** [comment]
Can someone clarify 

> @shyamchandranmec Use the layouts instead and include the corresponding CSS for each layout.
> 
> For you example, you can have `layouts/bar.vue` and `layouts/foo.vue`, the layouts are code-splitted so the CSS won't be included in the global CSS 👍

Does this no longer work in Nuxt 2?

I'm importing separate Sass files into my layouts but all CSS is loaded for every route regardless. I can only get it to work if I import into pages, not layouts, which is not ideal.

**Comment by galvez** [comment]
hey @anthonygore! Have you checked out [nuxt-sass-resources-loader](https://github.com/anteriovieira/nuxt-sass-resources-loader)?

In `nuxt.config.js`:

```
    ['nuxt-sass-resources-loader', [
      path.resolve(__dirname, 'src/styles/main.scss'),
      path.resolve(__dirname, 'src/styles/layout/base.scss')
    ]],
```

This is what I use to solve this problem.

**Comment by anthonygore** [comment]
Hey Jonas, how does that work in this scenario? To clarify, I'm trying to do the same thing as OP i.e. have an independent CSS bundles for different layouts.
