### ISSUE TITLE
Dynamic import not working!!

### ISSUE THREAD

**Issue by RailgunWinjoy** [nuxt/nuxt.js#8160]
`    

    methods: {

          async loadModal() {

             console.log('loadModal.....')

             if (!this.$modal) {
   
                 return await
                 import ('vue-js-modal').then(module => {
                     const VModal = module.default;
                    Vue.use(VModal)
                    this.modalLoaded = true;
                    return
                })
            } else {
                this.modalLoaded = true;
                return true
            }
        },
    }
   `

And whenever i need the modal to show up i call this:
` 
     async showModal() {
      await this.loadModal();
      this.$modal.show("youtube-modal");
    },
`

I just remove my whole pages folder to test the bundle.
And the result shows it bundle everything as long as the name appears in the project

![image](https://user-images.githubusercontent.com/28724907/95318423-1f35cb80-08c9-11eb-865d-f3bb4f41c950.png)

Because the same code was working perfectly when i use Meteor.

**Comment by danielroe** [comment]
@RailgunWinjoy The fact that webpack has produced a chunk doesn't mean that that chunk will ever be loaded. In fact, the way dynamic imports work, webpack will always bundle them for you - but only load that chunk when necessary.

You could use something like https://github.com/aholachek/bundle-wizard (with source maps enabled) to confirm whether that chunk is loaded on a given page.

If you feel there is a bug here, please provide a reproduction and I'll check it out.
