### ISSUE TITLE
setHeader Content-Type

### ISSUE THREAD

**Issue by andig89** [nuxt/nuxt.js#8161]
### Versions

- nuxt: latest 2.14.6
- node: v10.21.0 (default for codesandbox.io)

### Reproduction

https://codesandbox.io/s/setheader-in-nuxt-391mj?file=/nuxt.config.js

### What is Expected?
Set Content-Type in res header to for example 'application/xhtml+xml'.

### What is actually happening?
Content-Type is always set to 'text/html; charset=utf-8'.

**Comment by drewbaker** [comment]
Could use use the head() method of vue-meta to do this?

**Comment by andig89** [comment]
> Could use use the head() method of vue-meta to do this?

Head only sets by HTML so it can't set express response header. I tried anyway
```
 head: {
        'Content-Type': 'application/vnd.hbbtv.xhtml+xml; charset=utf-8',
        title: name_app,
        meta: [
            {
                'http-equiv': 'Content-Type',
                content: 'application/vnd.hbbtv.xhtml+xml;',
                charset: 'utf-8',
            },
```
and nope, it doesn't work.

**Comment by andig89** [comment]
I found a solution :D!
Check it on https://codesandbox.io/s/setheader-in-nuxt-391mj?file=/nuxt.config.js.

beforeResponse - it's not in docs, but it's listed on changelog (https://nuxtjs.org/docs/release-notes#v2.13.0) :P.
Bonus tip for parse HTML to XHTML :).
