### ISSUE TITLE
publicRuntimeConfig casts String to Number

### ISSUE THREAD

**Issue by o11an** [nuxt/nuxt.js#8162]
### Versions

- nuxt: v2.14.4
- node: v10.15.1 (local) and v10.21.0 (in codesandbox)

### Reproduction

[Code Sandbox reproduction](https://codesandbox.io/s/publicruntimeconfig-type-change-6yzo8)

### Steps to reproduce

1. Set a String variable that consists of numbers (e.g. '1234567890') in your publicRuntimeConfig
2. Check the type in runtime, it is now a Number (if you check the terminal in the reproduction the type is a String before set in publicRuntimeConfig)
3. Try to use .toString() while setting the variable
4. It will still be a Number

### What is Expected?

I expect the output to be a String

### What is actually happening?

The output is a Number

**Comment by pi0** [comment]
Hi. This is intended behavior indeed to use native values since values passed to runtimeConfig are usually originating from `process.env`. If you really want to preserve type, can use `"123"`.

**Comment by o11an** [comment]
Hi! Thanks for your quick response 😄 

I can for sure see the point of it working this way intendibly, and that using double quotes would be a good way of solving it... but I simply cannot get it to work.

I have tried this solution before, to have my variables in .env like so: `VARIABLE="123456"` but with type still not being preserved after they are passed to runtimeConfig. Updated my [Code Sandbox reproduction](https://codesandbox.io/s/publicruntimeconfig-type-change-6yzo8) to also use double quotes around the variable but without type being preserved.

I can for sure solve this by telling my api-developers to use letters in our String api-key or just to expect a Number, but it could also probably be useful to be able to preserve type from .env through runtimeConfig in some way 😄

**Comment by ryaposov** [comment]
> Having the same issue with ENV values casted to a Number. In my case it's a API key that's coming from a 3rd-party service. Wrapping it in double quotes doesn't help. Wondering what is the best way to solve this and why this issue was closed.

Sorry, found error in our system, nevermind!
