### ISSUE TITLE
yarn run generate, error:Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by chanyying** [nuxt/nuxt.js#817]
yarn run generate

error:
```
  nuxt:generate Generate file: /product/index.html +138ms
TypeError: Cannot read property 'split' of undefined
    at asyncData (0.server-bundle.js:500:37)
    at promisify (server-bundle.js:1538:15)
    at server-bundle.js:2088:103
    at Array.map (native)
    at server-bundle.js:2085:149
```
directory：
![image](https://cloud.githubusercontent.com/assets/8544506/26626909/42d1c512-462b-11e7-85d5-2e2020aa15ef.png)
config:
![image](https://cloud.githubusercontent.com/assets/8544506/26626967/66b1ac54-462b-11e7-8950-997af435e9d9.png)

@cj @VictorTolbert @johnlindquist @sirlancelot

**Comment by Atinux** [comment]
What version of nuxt.js are you using?

Do you have a reproduction repository @chanyying?

**Comment by chanyying** [comment]
@Atinux 
This is my dependencies
![image](https://cloud.githubusercontent.com/assets/8544506/26628539/0b35fb40-4631-11e7-8cb4-b9ca54c5d287.png)

installation
vue init nuxt/starter <project-name>

**Comment by sirlancelot** [comment]
What does your file `0.server-bundle.js` look like around line 500, column 37? Show some context.

**Comment by piyushchauhan2011** [comment]
@sirlancelot  Yeah suspicious, I believe something is wrong at `index.vue` or `default.vue` related to `asyncData` .

**Comment by chanyying** [comment]
@Atinux @sirlancelot @piyushchauhan2011 
According to the problem tracking, Due to Dynamic Routes caused
Thank！
