### ISSUE TITLE
enablePreview not triggering component fetch

### ISSUE THREAD

**Issue by lluishi93** [nuxt/nuxt.js#8172]
### Versions

- nuxt: 2.14.6 
- node: 12.18.2 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
1. Create some component
2. Add the `fetch` method to it
3. Add some condition to call `enablePreview` (using a plugin + query param for instance)
4. Statically generate the page using `nuxt generate`
5. Trigger `enablePreview` using the query param/method of your choosing

### What is Expected?
Component `fetch` gets triggered when preview is enabled

### What is actually happening?
`enablePreview` triggers `nuxtServetInit`, `asyncData` and pages `fetch`, but not `fetch` on components

**Comment by mornir** [comment]
Hi!
I just did a quick test in a repo. In my case, the fetch hook in component is working as expected:
https://github.com/mornir/movies-web/blob/fetch-component-preview/components/FetchPreview.vue#L8
https://fetch-component-preview--nuxt-sanity-movies.netlify.app/screenings/?preview=true
