### ISSUE TITLE
TypeError: link.__prefetch is not a function.

### ISSUE THREAD

**Issue by eljass** [nuxt/nuxt.js#8173]
### Versions

- nuxt: "^2.14.6"
- node: 14.11.0

### What is actually happening?
I get an error `TypeError: link.__prefetch is not a function. (In 'link.__prefetch()', 'link.__prefetch' is undefined)` in Sentry from Safari from `nuxt-link` prefetching.

This happens mostly on mobile Safari but there are also cases in desktop version too:
![Näyttökuva 2020-10-9 kello 16 02 09](https://user-images.githubusercontent.com/7661970/95586363-40252a80-0a49-11eb-8716-95c0a4406874.png)

Here is stacktrace for this error Sentry offers:
![Näyttökuva 2020-10-9 kello 16 02 58](https://user-images.githubusercontent.com/7661970/95586449-5af79f00-0a49-11eb-9403-52121c1fdb54.png)

Do you have any suggestions why this might happen and how to tackle this?

I do also include IntersectionObserver polyfill by using [nuxt-polyfill](https://github.com/Timkor/nuxt-polyfill) module with this config in my nuxt.config.js:
```
...
/**
   * Polyfills module configuration
   * @see https://github.com/Timkor/nuxt-polyfill
   */
  polyfill: {
    features: [
      {
        require: 'whatwg-fetch', // https://github.com/github/fetch
        detect: () => 'fetch' in window
      },
      {
        require: 'promise-polyfill', // https://github.com/taylorhakes/promise-polyfill
        detect: () => 'Promise' in window
      },
      {
        require: 'intersection-observer', // https://github.com/w3c/IntersectionObserver
        detect: () => 'IntersectionObserver' in window
      },
      {
        require: 'smoothscroll-polyfill', // https://github.com/iamdustan/smoothscroll
        detect: () =>
          'scrollBehavior' in document.documentElement.style &&
          window.__forceSmoothScrollPolyfill__ !== true,
        install: (smoothscroll) => smoothscroll.polyfill()
      }
    ]
  },
...
```

**Comment by dneeleman** [comment]
@eljass Have you found the solution yet? I'm encountering the same problems.

**Comment by eljass** [comment]
@dneeleman 
I did not found any solutions to this. It still occurs but fairly rarely. Only 24 times in the past 15 days.
These 24 errors in our end happened only on iOS (Facebook browser and Mobile Safari). I haven't been able to reproduce this by myself but will try to dig deeper on this.

**Comment by dneeleman** [comment]
@Elevista Thanks for the reply! I can confirm the error is not very common, it resurfaced this morning and found this issue but found it closed and marked stale. For us it also occurs for only Facebook browser and Mobile Safari, just like you mentioned.
