### ISSUE TITLE
Preload tag still added with injectScripts:false & resourceHints:false

### ISSUE THREAD

**Issue by sylvinus** [nuxt/nuxt.js#8178]
Hello!

Using Nuxt v2.14.6, I want to generate a fully JavaScript-less static website. I have this in my nuxt.config.js:

```
render: {
    injectScripts: false,
    resourceHints: false,
}
```
This does remove most of the script & preload tags, but I have one left (from my `/projects/` page for instance):
```
<link rel="preload" href="/_nuxt/static/1602283754/projects/payload.js" as="script">
```

How to remove this last one? It probably shouldn't be there, as there is no client-side runtime that will use it anyway :)

Another smaller issue is that I still have a `<script>window.__NUXT__=[...]</script>` tag inserted, even though with `injectScripts:false` it will be rendered useless as well.

Thanks!

**Comment by sylvinus** [comment]
For others that may have this issue and be looking for a short-term hack, here is how I'm cleaning HTML output for now:
```
  hooks: {
    'generate:page': page => {
      const $ = require("cheerio")
      const doc = $.load(page.html);

      // https://github.com/nuxt/nuxt.js/issues/8178
      doc("link[rel=preload]").remove();
      doc("html script").remove();

      // Clean Vue attributes because we don't have client-side JS
      doc("*").each((i, node) => {
        Object.keys(node.attribs).forEach((attr) => {
          if (["data-n-head-ssr", "data-n-head", "data-hid"].indexOf(attr) >= 0 || attr.startsWith("data-v")) {
            $(node).removeAttr(attr)
          }
        })
      })

      // Remove comments
      doc("*")
        .contents()
        .filter(function() { return this.type === 'comment'; })
        .remove();

      page.html = doc.html();
    },
  },
```

**Comment by NeFx** [comment]
thanks，it is work well

**Comment by crawlem** [comment]
Thank you, I faced the same issue (Nuxt 2.14.6) and your fix did the job!

**Comment by alhirzel** [comment]
@sylvinus  - thank you for providing that snippet! I am trying to mangle some code around so that it delivers perfectly on an embedded platform, and this is just the "back door" I needed to see!
