### ISSUE TITLE
You should use `css` property in` nuxt.config.js`

### ISSUE THREAD

**Issue by jonalxh** [nuxt/nuxt.js#8179]
In another issue they say : 
You should use `css` property in` nuxt.config.js`

https://nuxtjs.org/api/configuration-css#the-css-property

_Originally posted by @ricardogobbosouza in https://github.com/nuxt/nuxt.js/issues/4526#issuecomment-446545960_

What if I want to use it locally in all pages with same layout?

**Comment by danielroe** [comment]
@jonalxh in that case you can import the CSS file in the layout. For example:
```vue
<style lang="scss">
@import '~assets/css/layout1';
</style>
```

**Comment by jonalxh** [comment]
I've tried and it keeps scoped.

**Comment by danielroe** [comment]
@jonalxh What do you mean?

**Comment by jonalxh** [comment]
If I import the CSS file as you told me, the CSS properties only affect the layout file instead of all the children files. Is it clear?

**Comment by danielroe** [comment]
@jonalxh would you share your code in that case? I assume you are not using `<style scoped>`

**Comment by jonalxh** [comment]
Hi @danielroe I've found that it works with native elements, but I need it to work with deep elements and it doesn't work for me.

I have two style instances, the first is scoped, the second is where I import my global SCSS file:

`dashboard.vue` (layout file)
```
<style lang="scss" scoped>
    ... Styles for current layout content
</style>

<style lang="scss">
    @import '~assets/css/dashboard';
</style>
```

`dashboard.scss` (global css for all layout children)
```
/deep/ .form-control {
    color: silver !important;
}
/* A lot of code */
```

The styles work if I set it in my files independently.

**Comment by jonalxh** [comment]
I've found that the implemented code on previous comment affects all the project and not only layout children.
