### ISSUE TITLE
Array list from AsyncData/fetch rendered by v-for throw: The client-side rendered virtual DOM tree is not matching server-rendered

### ISSUE THREAD

**Issue by lazyseals** [nuxt/nuxt.js#8189]
### Versions

- nuxt: 2.14.6
- node: 12.13.1

### Reproduction

A basic example of what I try to accomplish:

```
<template>
  <div
    class="place-card"
    :key="place._id"
    v-for="place in places"
  >
    <nuxt-link
      :to="{
        name: 'places-title',
        params: { title: place.title }
      }"
    >
      <PlaceCard :place="place" />
    </nuxt-link>
  </div>
</template>

<script>
export default {
  asyncData() {
    // Fetch places with axios
    return { places: [{...}, ..., {...}] }
  }
}
</script>
```

### Steps to reproduce

1. Take the code from above return an array from `asyncData` (e.g. `places`)
2. Use the array from `asyncData` and render it with `v-for` in the template. **Important:** Inside `v-for` use `nuxt-link` or `<a href="#"></a>`
3. Run the code with `npm run dev`
4. Open the browser console and see the following Error: 
```
The client-side rendered virtual DOM tree is not matching server-rendered content. 
This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. 
Bailing hydration and performing full client-side render.
```

### What is Expected?
In one of my pages I use `AsyncData` to asynchronously fetch an array of data objects from my Api, which I render in my template using `v-for`. This is working fine when I don't use `nuxt-link` or `<a href=".."></a>` inside the `v-for`. As soon as I include `nuxt-link` or `<a href=".."></a>` inside my `v-for`, I get the following error:
```
The client-side rendered virtual DOM tree is not matching server-rendered content. 
This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. 
Bailing hydration and performing full client-side render.
```
I was able to get it working, when I wrap the whole `v-for` part into `<client-only>...</client-only>` as described [here](https://stackoverflow.com/questions/47862591/vuejs-error-the-client-side-rendered-virtual-dom-tree-is-not-matching-server-re/61375490#61375490) in @Mohsens answer as well as [here](https://stackoverflow.com/questions/59948635/vue-warn-the-client-side-rendered-virtual-dom-tree-is-not-matching-server-render). 

Unfortunately, `<client-only></client-only>` prevents server-side-rendering of the async data. However, I do need pre-fetching my data on the server-side, because of SEO.

I tried to find a solution in the issues, but couldn't find something promising. Therefore, is this intended behaviour and what can I do about it?

**Comment by drewbaker** [comment]
You’re template can only have 1 root element. Your v-for will render multiple root elements in that template. That’s your problem I think. 

Try putting a containing element around the v-for div.

**Comment by lazyseals** [comment]
In my original code, I do have a containing element around the v-for div. Unfortunately, this cannot be the problem.

**Comment by manniL** [comment]
Please share the code of your PlaceCard component.

**Comment by lazyseals** [comment]
I figured it out. According to [here](https://stackoverflow.com/questions/58251532/nuxt-js-error-the-client-side-rendered-virtual-dom-tree-is-not-matching-server/58259464#58259464) and [here](https://github.com/nuxt/nuxt.js/issues/1815), I had a nested link, the one inside my v-for div and another inside my PlaceCard component, which isn't allowed.
