### ISSUE TITLE
Site loads indefinitely / extremely slowly, when having multiple tabs open in localhost

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt.js#8190]
### Versions

- nuxt: latest
- node: v12.18.3

### Steps to reproduce

1. Open your localhost in one tab
2. Open another window in another tab
3. Try navigation your site, on one of the tabs. Sometimes the site will hang, and it will only "finish loading" if you close the other tab that's open on localhost.

### What is Expected?
Site should not hang no matter how many tabs you have open

### What is actually happening?
Site hangs when more than one tab is open.

See video:
![nuxt issue when having multiple windows open](https://user-images.githubusercontent.com/3786627/95678331-4b549380-0bcc-11eb-871e-aedb27265966.gif)

It will just keep pending. Nothing happens for X seconds. When I close the other tab that also has localhost:3000 open, it loads instantly.

![image](https://user-images.githubusercontent.com/3786627/95678445-efd6d580-0bcc-11eb-8b89-27b7da3577a8.png)

**Comment by francois2metz** [comment]
It seems that you have reached the maximum number of concurrent connections per host. You should either keep less tabs open or increase the number of connection in your browser. On firefox, you can tweak the preference `network.http.max-persistent-connections-per-server` in the `about:config` page.

**Comment by simplenotezy** [comment]
@francois2metz unfortunately there is no such setting in Chrome. Bear in mind, that this bug also happens when I have a single tab open, and I open a second one.

![image](https://user-images.githubusercontent.com/3786627/95992026-c5d01e00-0e2d-11eb-83d4-f51389f15208.png)

**Comment by manniL** [comment]
See https://github.com/nuxt/nuxt.js/issues/6442#issuecomment-541209443
