### ISSUE TITLE
Why does Vue CLI starter project have a static folder and an assets folder?

### ISSUE THREAD

**Issue by antcook** [nuxt/nuxt.js#82]
In the Vue CLI starter project for Nuxt, the favicon is found in it's own folder called static but there is also an assets folder for other static resources like images/css ect. 

Is there a reason why we have both of these folders, can the favicon be stored in the assets folder (or images, css in the static folder), thus removing the need for an extra folder?

Thanks, and Merry Christmas! :)

**Comment by alexchopin** [comment]
Hi, thanks and Merry Christmas also! :)

Currently it's more to show an example of the difference between resource load with and without webpack and also to show that the static directory content is copied during nuxt generate for static hosted application. 

It should be erase in the future when the documentation website will be complete.
Or perhaps, we should add all directories like (store, plugins, etc) but with only a README.md inside to explain what kind of content should be inside. 
_Not sure about the last solution yet_ ;)
