### ISSUE TITLE
Nuxt-link and router-link don't create href attribute

### ISSUE THREAD

**Issue by SergeiPleshkov** [nuxt/nuxt.js#8204]
### Versions

- nuxt: 2.12
- node: 13.7

### Reproduction

https://github.com/SergeiPleshkov/create-nuxt-app

<details open>
<summary>Additional Details</summary>
Href attribute is not attached to '<a>' tag during SSR if 'href' was passed as not defined prop.
<br>

</details>

### Steps to reproduce
Serve reproduction repo, inspect the source code.

![image](https://user-images.githubusercontent.com/29925191/95989736-55c49680-0e33-11eb-959b-bb39625e24f7.png)

source code from devtools' network tab
![image](https://user-images.githubusercontent.com/29925191/95989883-8278ae00-0e33-11eb-8c4b-dd5940c365d9.png)

document ready
![image](https://user-images.githubusercontent.com/29925191/95989982-a1774000-0e33-11eb-9057-39a8ba700b8f.png)

### What is Expected?

Passing not defined dynamic prop to '<n-link>'  should not cause href loss in SSR mode.

### What is actually happening?

Href attribute appears after browser render.

**Comment by manniL** [comment]
You should not need to set the `href` as `NuxtLink` will transform to an `a` tag on the server side automatically.
[Example](https://www.lichter.io/)

![grafik](https://user-images.githubusercontent.com/640208/96010368-00dc4c80-0e42-11eb-884c-ead50c1cb94a.png)
https://github.com/manniL/lichter.io/blob/main/components/Navbar.vue#L36-L40

**Comment by SergeiPleshkov** [comment]
I know how to handle it to make it work, but i think this behavior is inconsistent. When you create dynamic component like this
```html
  <component
    :is="tag"
    :href="href"
    :target="target"
    :to="to">
  </component>
```
that can be either `<a>` or `<n-link>`, so there should be all props. Once again, i know how to make it work using `v-bind` or   separate template, i created an issue because i think this is a bug.

**Comment by manniL** [comment]
Okay, so to clarify that:
The behavior you are *expecting* is that `NuxtLink` should use a set `href` prop (if provided)?

**Comment by SergeiPleshkov** [comment]
No, i expect the behavior of `:href="undefined"` and no href prop at all to be equal.

**Comment by manniL** [comment]
Got it!

As you mentioned, the same issue appears with `RouterLink` too, right?

**Comment by SergeiPleshkov** [comment]
Yes, the same behaviour.

**Comment by manniL** [comment]
Then https://github.com/vuejs/vue-router might be a better place for this issue. `<NuxtLink>` inherits `<RouterLink>` behavior ☺️
