### ISSUE TITLE
Error failing to load CSS/JS chunk after every new deployment.

### ISSUE THREAD

**Issue by simondib** [nuxt/nuxt.js#8208]
### Versions

- nuxt: v2.14.1
- node: 12

### Reproduction

<details open>
<summary>Additional Details</summary>

This is related to https://github.com/nuxt/nuxt.js/issues/6982 which was marked resolved, however other users appear to still be experiencing similar issues after the supposed fix in 2.12.2

Unable to provide repro site due to commercial sensitivity. 

The bulk of our Sentry logs suggest this might be a Safari/iOS issue, although there are a few Windows 10/IE Edge instances.

**nuxt.config.js** 

```export default {
  mode: 'spa',
  srcDir: 'src/',

  head: {
    titleTemplate: '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'title', content: '' },
      { name: 'og:title', content: '' },
      { name: 'og:site_name', content: '' },
      { name: 'apple-mobile-web-app-title', content: '' },
      {
        hid: 'description',
        name: 'description',
        content:
          ""
      }
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }]
  },
  typescript: {
    typeCheck: {
      eslint: true
    }
  },
  pwa: {
    manifest: {
      name: '',
      short_name: '',
      description: ""
    }
  },

  customProperties: true,

  css: ['@/assets/scss/main.scss'],

  plugins: [
    { src: '~/plugins/localStorage', ssr: false }
  ],

  buildModules: [
    '@nuxt/typescript-build',
    'nuxt-typed-vuex',
    '@nuxtjs/google-analytics',
    '@aceforth/nuxt-optimized-images',
    '@nuxtjs/pwa',
    'nuxt-babel',
    '@nuxtjs/style-resources'
  ],

  modules: ['@nuxtjs/sentry'],

  router: {
    middleware: 'router'
  },

  optimizedImages: {
    handleImages: ['jpeg', 'png', 'svg', 'webp', 'gif'],
    optimizeImages: true,
    optimizeImagesInDev: false // disable in dev to reduce compile time
  },

  styleResources: {
    scss: [
      '~/assets/scss/_settings.typography.scss',
      '~/assets/scss/_settings.breakpoints.scss',
      '~/assets/scss/_settings.buttons.scss',
      '~/assets/scss/_tools.mixins.scss'
    ]
  },

  build: {
    extractCSS: process.env.NODE_ENV === 'production', 
    extend(config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }

      config.module.rules.use = {
        loader: 'url-loader',
        options: {
          limit: 8192
        }
      }
    },

    transpile: [/typed-vuex/],

    plugins: [
      new BundleAnalyzerPlugin({
        analyzerMode: 'static',
        openAnalyzer: false,
        defaultSizes: 'gzip',
        reportFilename: 'webpackBundleReport.html'
      })
    ]
  }
}
```

</details>

### Steps to reproduce

1. Deploy production build
2. User goes to page and sees an infinite loading spinner on the page (only hard refresh fixes)

### What is Expected?

App functions without interruption after a deployment.

### What is actually happening?

An infinite page spinner appears and remains even after a page refresh. A hard cache clear fixes the issue. Problem reoccurs after the next deployment.

Browser console errors (not necessarily appearing at the same time):

``
ChunkLoadError
Loading chunk 19 failed.
(timeout: /_nuxt/pages/index.23e1e4a.js)
``
``
Loading CSS chunk 19 failed.
(/_nuxt/pages/index.633102b.css)
``

![image](https://user-images.githubusercontent.com/7483506/96083778-9bec2980-0f09-11eb-957e-1b1b381a75c0.png)

**Comment by Icesofty** [comment]
Same issue when deploying on Digital Ocean with App Plateform.

**Comment by mattdocumatt** [comment]
I have also very hard times with the "infinity spinner" problem after updating from Nuxt 2.0.0 to 2.14.6.

Spinner only browsers I found:
- all version iOS, Safari and FF all versions
- W10, Firefox 77 and older. 77 shows me in console `SyntaxError: invalid regexp group` in file beginning with `window.webpackJsonp`
- W10, IE 11

Other strange issues I encounter after updating to the latest Nuxt:
- latest Chrome and FF crashes to an error page saying "Uncaught (in promise) TypeError: Cannot read property 'store' of undefined".

Both are critical bugs!

**Comment by mattdocumatt** [comment]
It has something to do with invalid regexs. Both FF and Chrome crash on regex errors. For example, the first working Firefox is 78 that adds ["New RegExp engine in SpiderMonkey, adding support for the dotAll flag, Unicode escape sequences, lookbehind references, and named captures."](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78)

**Comment by simondib** [comment]
> I have also very hard times with the "infinity spinner" problem after updating from Nuxt 2.0.0 to 2.14.6.
> 
> Browsers that suffer infinite spinner:
> 
> * all version iOS, Safari and FF all versions
>   ![image](https://user-images.githubusercontent.com/383059/99898323-dc755a80-2ca0-11eb-9361-55ffd84384dc.png)
> * Firefox 77 and older. 77 shows me in console `SyntaxError: invalid regexp group` in file beginning with `window.webpackJsonp`
>   ![image](https://user-images.githubusercontent.com/383059/99887432-adc99680-2c44-11eb-93f2-a55398fa7d2e.png)
>   ![image](https://user-images.githubusercontent.com/383059/99887433-b02bf080-2c44-11eb-8649-049f10a1e475.png)
> * Chrome 61 and older
>   ![image](https://user-images.githubusercontent.com/383059/99887410-72c76300-2c44-11eb-9390-572863be2f59.png)
> * IE 11 (console shows nothing)
>   ![image](https://user-images.githubusercontent.com/383059/99887413-7eb32500-2c44-11eb-88ba-1a57177ea925.png)
> 
> Beside this, latest Nuxt suffer another serious bug. It somehow break JS and and in my case on latest Chrome and FF causes crashing to an error page saying "Uncaught (in promise) TypeError: Cannot read property 'store' of undefined".
> 
> ![image](https://user-images.githubusercontent.com/383059/99887446-d05baf80-2c44-11eb-8186-06df2c41a731.png)
> ![image](https://user-images.githubusercontent.com/383059/99887449-d3ef3680-2c44-11eb-8d14-f20f6c822d5e.png)
> ![image](https://user-images.githubusercontent.com/383059/99887453-d94c8100-2c44-11eb-96f6-bac98f4e05d0.png)
> 
> Both are critical bugs!
> 
> You can see it in action on https://snippets.documatt.com. But only for a short time, because I will downgrade to old Nuxt.

This looks like a related, but separate issue to the original issue documented.

**Comment by mattdocumatt** [comment]
Yes, they are related. However, I'm not skilled enough to say something valuable. If you are, I created a minimal demo that suffers both errors ("SyntaxError: invalid regexp group" and "ChunkLoadError: Loading chunk 2 failed.") because I'm going to downgrade the website https://snippets.documatt.com where I discover these bugs back to old Nuxt where everything worked perfectly.

The crashing Nuxt is at https://gitlab.com/mattdocumatt/nuxt-infinite-spinner-bug-demo. Keep in mind you have to visit it with few months old browser versions to see the bugs.

**Comment by mattdocumatt** [comment]
One more detail: now I discovered it works in anonymous mode! Can anybody explain this mess?!

**Comment by Icesofty** [comment]
> One more detail: now I discovered it works in anonymous mode! Can anybody explain this mess?! @Atinux?

Because in Anonymous mode, it automatically clears your cache.

**Comment by mattdocumatt** [comment]
> > One more detail: now I discovered it works in anonymous mode! Can anybody explain this mess?! @Atinux?
> 
> Because in Anonymous mode, it automatically clears your cache.

What does it mean? What is causing these errors?

**Comment by mattdocumatt** [comment]
Is anybody from the core team interested that, under certain and unknown conditions, Nuxt doesn't work in the majority of browsers and devices? This is a show-stopper error. I can't do more than only urge @Atinux @alexchopin @pi0 @bdrtsky... :-(

**Comment by danielroe** [comment]
@mattdocumatt From what you've said, I would investigate your service worker setup.

**Comment by mattdocumatt** [comment]
> @mattdocumatt From what you've said, I would investigate your service worker setup.

I have only a brief understanding of service workers. In Chrome on page chrome://serviceworker-internals/ I don't see snippets.documatt.com listed, i.e. my web didn't register a service worker. Is that correct or not? Actually, I don't touch any single line in files generated by `npx create-nuxt-app` except adding few new dependencies.
