### ISSUE TITLE
Grammar error in Nuxt Generate Warning

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt.js#8217]
### Versions
- nuxt: 2.14.7

### Steps to reproduce

Have no nuxt.config.js file, run `yarn generate`.  In this warning `your` should be `you`

![image](https://user-images.githubusercontent.com/2112282/96373885-e8677d00-1134-11eb-91a1-86519e3f788c.png)

### What is Expected?
`you have to set`

### What is actually happening?
`your have to set`

**Comment by steveperkins** [comment]
I've fixed this in and one other error in #8219.
