### ISSUE TITLE
How to set lang="postcss" in styles?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#822]
Hi. I have issues with highlighting PostCSS code in Vue, so have recommendation to set lang="postcss". But if I do that I got an error that loader is missing. I thought Nuxt already has all PostCSS stuff, but tried to install postcss-loader anyway. It didn't help. Any suggestions?

**Comment by stephan281094** [comment]
Nuxt uses [vue-loader](http://vue-loader.vuejs.org/en/) to transpile `.vue` files with the following loaders:
https://github.com/nuxt/nuxt.js/blob/dev/lib/webpack/vue-loader.config.js#L17-L23.

Since `postcss` is not a syntax and no loader has been defined for it, it throws an error when using `lang="postcss"`. Instead you might consider installing a 'vue' syntax highlighting package for your editor.

**Comment by kodekrendel** [comment]
@stephan281094 I installed official Vue.js highlighter for Sublime, but it highlight PostCSS properly ONLY if I set `lang="postcss"` - that's the whole point!

**Comment by piyushchauhan2011** [comment]
Hmm, I thought in the documentation they mentioned about `postcss`. Search for `postcss` here https://nuxtjs.org/api/configuration-build/ @kodekrendel

**Comment by kodekrendel** [comment]
@piyushchauhan2011 it's about setting up PostCSS processing, plugins etc. But setting `lang="postcss"` not working, everything crashes (although the PostCSS code is working obviously).

**Comment by piyushchauhan2011** [comment]
Hmm, right  yeah ide + .vue files a bit of pain. I definitely think that breaking up the .vue file into individual files is better so we get to utilise the normal ide without a plugin etc. @kodekrendel

**Comment by kodekrendel** [comment]
@stephan281094 looking into vue-loader repo, I see people using PostCSS in it - https://github.com/vuejs/vue-loader/issues?utf8=%E2%9C%93&q=postcss

**Comment by stephan281094** [comment]
@kodekrendel I know PostCSS is being used in vue-loader. It is, however, _not_ being registered as a loader to be used with `lang="postcss"`.

**Comment by kodekrendel** [comment]
@stephan281094 ok, now I got this. Thanks for clarifying. Well, then this is definitely not Nuxt issue. But I appreciate if someone know how to hack it and share it :simple_smile:

**Comment by kodekrendel** [comment]
Oh, wait, so the question is to pass loader to Nuxt? We can do that, right?

**Comment by stephan281094** [comment]
You can configure loaders in your `nuxt.config.js`. Have a look at https://nuxtjs.org/api/configuration-build#loaders.

**Comment by kodekrendel** [comment]
After 

```
    loaders: [
      {
        test: /\.css$/,
        loader: ['style-loader', 'postcss-loader']
      }
    ],
```
it doesnt load my css from Assets

**Comment by piyushchauhan2011** [comment]
@kodekrendel `css-loader` is missing in above ?

**Comment by kodekrendel** [comment]
@piyushchauhan2011 have no idea how to use this. Nuxt needs Search in FAQ.

**Comment by Atinux** [comment]
Related to https://github.com/nuxt/nuxt.js/issues/827

Demo: https://nuxt-postcss-global.glitch.me/
Code: https://glitch.com/edit/#!/nuxt-postcss-global

**Comment by kodeJ** [comment]
@Atinux thanks Atinux. Seems like it's working, but if I set lang="postcss" I got a SourceMap warning

```
(Emitted value instead of an instance of Error) 

 ⚠️  PostCSS Loader

Previous source map found, but options.sourceMap isn't set.
In this case the loader will discard the source map enterily for performance reasons.
See https://github.com/postcss/postcss-loader#sourcemap for more information.



 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-08ffc1ac","scoped":false,"hasInlineConfig":true}!./~/postcss-loader/lib!./~/vue-loader/lib/selector.js?type=styles&index=0!./pages/index.vue 4:14-330 13:3-17:5 14:22-338
```

**Comment by cliffrowley** [comment]
I'm also having this issue, though I am poking around to try to understand why.
