### ISSUE TITLE
dynamic publicPath

### ISSUE THREAD

**Issue by rstormsf** [nuxt/nuxt.js#8229]
I have a following problem:
When I build the app, it should be working on my primary domain and also as ipfs hash
example: `ipfs.myapp.com` OR `ipfs.io/ipfs/myappcom`

the problem is with generating the nuxt build. For main domain, the default works just fine
```
build: { publicPath: '/_nuxt/' } 
```
but if I need to generate it for ipfs.io/ipfs/xxx, it has to be 
```
build: { publicPath: './_nuxt/' } 
```

is there a way to make a function that will try to fetch `/_nuxt/` folder by defining how.
example:
```js
publicPath: (resolve) => {
    let pathToNuxt = await resolve('/_nuxt/')
    if(pathToNuxt.failed) {
        pathToNuxt = await resolve('./_nuxt/')
    }
    return pathToNuxt
}
```
something like this

P.S.
`build: { publicPath: './_nuxt/' } ` still not ideal cause it breaks the app if it's not accessed from the root path. But it's better than nothing

If there is any other way to archive this goal, please let me know

**Comment by jpsc** [comment]
I think you can pass a [variable from your CI](https://nuxtjs.org/api/configuration-env#automatic-injection-of-environment-variables) to you `nuxt.config.js` for this.

`NUXT_ENV_PUBLIC_PATH="./nuxt/" nuxt build`

**Comment by rstormsf** [comment]
> I think you can pass a [variable from your CI](https://nuxtjs.org/api/configuration-env#automatic-injection-of-environment-variables) to you `nuxt.config.js` for this.
> 
> `NUXT_ENV_PUBLIC_PATH="./nuxt/" nuxt build`

That won't work because when I deploy to IPFS, my link of `ipfs.mydomain.com` is using ipfs-hash to load the content and some users should also be allowed to access it from `ipfs.io/ipfs/mydomain.com` so I can't have 2 builds, 1 build should work for all.

**Comment by rstormsf** [comment]
bump :-(

**Comment by rotemrevivo91** [comment]
joining on the request

**Comment by pi0** [comment]
Thanks for making issue @rstormsf. It is indeed a must have feature. I'm closing in favor of #8509 to track.
