### ISSUE TITLE
About assets size limit

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#823]
I try to `npm run build` on my production server, but I got the warning:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
This can impact web performance.
Assets:
  nuxt.bundle.fd4ef5d105dfb612b8bb.js (634 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recomm                             ended limit (300 kB). This can impact web performance.
Entrypoints:
  app (742 kB)
      manifest.a9503655cbefafecdb90.js
      vendor.bundle.a9503655cbefafecdb90.js
      nuxt.bundle.fd4ef5d105dfb612b8bb.js
```

and when I visit the site,I found that some js files is too big to  impact the performance.

what should I do to make the files smaller, or can I push this files to cdn, this will be faster than my server

**Comment by bimohxh** [comment]
The source code is https://github.com/awesomes-cn/news

**Comment by piyushchauhan2011** [comment]
👍  for the project @bimohxh . Nice to see something real project, Cheers!

**Comment by bimohxh** [comment]
@piyushchauhan2011 I really glad to apply nuxt in my production, but some problems must be solved

**Comment by bimohxh** [comment]
@piyushchauhan2011  This is the url http://news.awesomes.cn/  . I just use this small app to test nuxt. you can see the effect here

**Comment by ausir0726** [comment]
@piyushchauhan2011  
https://nuxtjs.org/ is already a real project there  😆 

@bimohxh 
I have a similar warning like you .
but when my server open http2 and gzip , 300kb reduce to 100kb .
so , I don't have get huge impact . 

I guess that because url-loader will combine small file to base64 image
if you use many small image in asset , that will make your js big .
https://nuxtjs.org/guide/assets/#__nuxt
```
url-loader allows you to conditionally inline a file as base-64 data URL if they are smaller than a given threshold. This can reduce a number of HTTP requests for trivial files. If the file is larger than the threshold, it automatically falls back to file-loader.
```
maybe you can try set limit: 1000 to 5000 ? or ... I don't know ...


![screenshot_1](https://cloud.githubusercontent.com/assets/7247064/26684643/144e2bb4-471a-11e7-9018-c6f9fcc163fb.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/7247064/26684650/1825ee48-471a-11e7-965c-a52fdfd9be9d.png)

**Comment by bimohxh** [comment]
@ausir0726 Thanks, I will try http2, but I don't thinks this is a good solution, 100kb is still a impact  for me 囧

**Comment by ausir0726** [comment]
@bimohxh 
http2 只是併發下載，並不會真正讓檔案變小，變小的是 gzip . 我覺得你可以先試試看把 url-load 的 limit 調整大一點，看他是不是把圖片都做成 base64 合併到你的 bundle file 去了...

**Comment by bimohxh** [comment]
@ausir0726  好的 我试试，不过我整站只有一张 logo 图片呢，剩下的就是 svg了

**Comment by ausir0726** [comment]
@bimohxh  svg 小於 1kb 都會被他轉 base64 喔
你看他的預設值 包含 png jpg gif svg
```js
[
  {
    test: /\.(png|jpe?g|gif|svg)$/,
    loader: 'url-loader',
    query: {
      limit: 1000, // 1KO
      name: 'img/[name].[hash:7].[ext]'
    }
  },
  {
    test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
    loader: 'url-loader',
    query: {
      limit: 1000, // 1 KO
      name: 'fonts/[name].[hash:7].[ext]'
    }
  }
]
```

**Comment by stephan281094** [comment]
You might also consider registering a service worker to precache static assets (with [sw-precache-webpack-plugin](https://www.npmjs.com/package/sw-precache-webpack-plugin)). This will improve the performance considerately after visiting the site one time.

**Comment by bimohxh** [comment]
@stephan281094 Thanks, I will try this later

**Comment by ausir0726** [comment]
@bimohxh 
I see your repo , you have many svg file less then 1kb , maybe that all svg transfer to base64 and pack to your bundle.js.

**Comment by ausir0726** [comment]
@bimohxh  更正，數字應該要調小，而不是調大...

**Comment by bimohxh** [comment]
@ausir0726 好的

**Comment by bimohxh** [comment]
@ausir0726 我删除了大部分没用的 svg， 结果 `nuxt.bundle.2324868fdab3dc9bc3c5.js` 从 183kb 下降到了  161kb

**Comment by ausir0726** [comment]
但你那是 gzip 過的 size 嗎 ? 可能還是要看一下 bundle.js 裡面到底夾了甚麼~

**Comment by bimohxh** [comment]
@ausir0726 我目前是开启了 gzip 的，所有请求都是压缩过的

**Comment by ausir0726** [comment]
剛看你本來的 nuxt.bundle.fd4ef5d105dfb612b8bb.js (634 kB)
你是否把這個打開看看，裡面到底包了什麼程式，還是還有其他的 base64 被打包在裡面

**Comment by bimohxh** [comment]
我之前引用了一个 bootstrap.css 发现有100多kb，于是怀疑是不是因为这个文件打包进来了，于是后面把它去掉了，发现 `nuxt.bundle.xxxx.js`  降到了 142 KB，并非由多大的差距，看来webpack并非把整个bootstrap打包进去了么

**Comment by bimohxh** [comment]
@ausir0726  I have push the build data to https://github.com/awesomes-cn/news/tree/master/testdata  please help me to analysis, Thanks

**Comment by ausir0726** [comment]
我把你的 repo 抓回來測了一下 我下面寫的 SIZE 為 未gzip 前
首先是 bootstrap 整包大概用掉了 ~100KB
569KB -> 443KB 
建議如果沒有全部使用上的話，可以只掛載需要的區塊

接下來另外一個瓶緊是 editor ~200KB
443KB -> 242KB 
這個就用蠻兇了，因為你在你的 component 用到了 jquery + codemirror
看起來似乎沒辦法避免....

然後主要是因為你把它放到 plugins 引用了
所以他就會綁到  nuxt.bundle.js 去
我建議把這隻拆出來，不要讓他塞到 Vue.component 
讓他在你要用到的頁面在使用，這樣可以應該就可以達到你的要求了...

**Comment by bimohxh** [comment]
@ausir0726   非常感谢，我把这一块提出来

**Comment by ausir0726** [comment]
如果這兩個可以修正的話 app 進入點應該可以降低到 242KB
gzip 後應該 80kb 左右吧，我猜

![image](https://cloud.githubusercontent.com/assets/7247064/26687867/8d6fa712-4723-11e7-8c3c-188bae58fda4.png)

**Comment by ausir0726** [comment]
至於 bootstrap 你可以參考我的 starter
我用 BS4 只有拿 grid ，所以我是直接引用 BS4 的 SCSS 到我的 SCSS
https://github.com/finpo/nuxt/blob/master/template/assets/css/bs4.scss
然後再到 nuxt.config.js 掛載我用的 bs4.scss
https://github.com/finpo/nuxt/blob/master/template/nuxt.config.js#L32

這樣一來可以獲得最小且最大彈性的 BS4

**Comment by bimohxh** [comment]
@ausir0726 谢谢 我参考一下

**Comment by ausir0726** [comment]
translate discuss to English ,

this case package full BS4 css and Jquery , codemirror to nuxt.bundle.js
that why nuxt.bundle.js is so big ( 600kb )

If can just use mini BS4 CSS , can reduce 80-100kb ( maybe )
if remove editor plugin ( jquery , codemirror ) can reduce 200kb

that can reduce app 742kb to ~300kb .

**Comment by pi0** [comment]
If your bundle size is getting bigger and bigger for common css files, you may try enabling `build.extractCSS` option to externalize css parts too :)

**Comment by bimohxh** [comment]
@pi0 Has demo or doc about  `build.extractCSS` ?

**Comment by bimohxh** [comment]
@ausir0726  haha , I put the big assets to cdn and replace the  assets path in `index.html` https://github.com/awesomes-cn/news/blob/master/tools/build.js

**Comment by Atinux** [comment]
@bimohxh nice project :)

If you upload the assets on a CDN, you can use https://nuxtjs.org/api/configuration-build#publicpath to set the URL, it will be renamed directly in `dist/index.html` on `nuxt build`

**Comment by bimohxh** [comment]
@Atinux It's awesome, I will use `publicpath` to replace my own tool

**Comment by ausir0726** [comment]
@bimohxh 建議你還是可以修正一下你的 bs4 跟 editor
因為太大的 bundle.js 會造成慢速網路下載卡住，你的 JS 可能會沒有反應，直到下載完...

**Comment by bimohxh** [comment]
@ausir0726 bootstrap 已经按照你说的方式处理了，codemirror 目前是没办法，官方也没有提供自定义的构建方式

**Comment by ausir0726** [comment]
我的意思是說，你不要把它放到 plugins 裡面去，因為你首頁進入的時候即便是沒有用到 editor ，他也被整個封裝到 bundle.js 裡面了，你是否可以讓有需要用到 editor 的頁面在載入? 如果確實每一頁都要用到，或許也可以額外拆出來一個 js ，因為 vendor , manifest , bundle 這三隻如果太大的話，有可能會造成你的畫面在進入的時候，慢速網路整個 hang  住... 必須要等這三隻載入完成...

**Comment by bimohxh** [comment]
@ausir0726 是这样的，nuxt 对于使用到 jQuery的插件必须要放到全局 plguin 下面去，而且得加上 `ssr: false` 的参数，否则就会报 window is undefined的错误，我也是没办法，只能放到 plguin 里面去了

**Comment by ausir0726** [comment]
放到 plugin => ssr: false 是一種解法
但是在使用到的 vue 上判斷 process.BROWSER_BUILD 也不見得就不好
我覺得還是要看你要怎麼解決這個問題~

如果你在 你的 page/xxx.vue 才判斷 if ( process.BROWSER_BUILD ) 才使用你的 code mirror
那 code mirror 就會只在那隻 bundle 才會引用...

**Comment by ausir0726** [comment]
不過我剛剛看了原始碼，editor 被引用在 header ，然後 header 被引用到 layout ，也就是表示每一個頁面都會存在這個 codemirror ，所以似乎如果分割的話，就會造成 header 錯誤...

**Comment by pi0** [comment]
لطفا به زبان انگلیسی صحبت کنید :P

**Comment by ausir0726** [comment]
@pi0 
sorry , I just want use Chinese tell how to resolve will be clear .
If you are offended please forgive me

**Comment by pi0** [comment]
@ausir0726 That's OK bro if is more clear :) I was just translating entire topic if i/others can help more :)

**Comment by ausir0726** [comment]
translate English

@bimohxh used jquery/codemirror , and set it to plugins with SSR : false 
it package about 300kb to bundle.js
I suggest he don't write in plugin , seems like it will package to bundle .
600kb will let slow network user hang with first visit . ( like mobile network users )

and , I checked the repo , the editor.vue used in header.vue , and used in default layout .
seems like it need package to bundle.js , because every pages need it .

so ... don't know how to resolve .

**Comment by pi0** [comment]
[Here](https://gist.github.com/pi0/5ee90656e0fc1a3d3ec97cc5ecce44c6) is a working CKEditor component for Nuxt.js that requires dependency from inside component so bundle size remains small. If it can help.
For syntax highlighting only i suggest using special babel loader, so that no runtime JS is required at all. [Here](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/build/nuxt.config.js#L31) and [Here](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/docs/nuxt/pages/docs/index.vue#L7) is an implementation example for nuxt :)

**Comment by ausir0726** [comment]
my personal suggest

maybe can make editor.vue to dynamic component with lazy load .
if some one need use the editor , then dynamic load this component with ajax 
and mount editor component ...

**Comment by ausir0726** [comment]
another solution ( more easier )

Obviously , not everyone need editor ..
maybe move editor from header to single page . ( jquery/codemirror will bundle this page )
if user need commit then redirect to editor page .

but dynamic component is the better solution , but more advanced usage .

**Comment by bimohxh** [comment]
@ausir0726 dynamic component seems to be the best solution, I can't sure if I can apply dynamic component into nuxt

**Comment by ausir0726** [comment]
@bimohxh here is my dynamic load component , that can resolve your problem totally .

First , I create a project similar yours , especially copy your editor.vue ( include jquery / code mirror )
when nxut build , nuxt.bundle.js is 364kB
![screenshot_4](https://cloud.githubusercontent.com/assets/7247064/26736252/e3991bd0-47f7-11e7-8764-50c02c3bb1ea.png)

Second , I remove plugin ssr:false in nuxt.config.js , and add condition in header.vue 
https://github.com/ausir0726/nuxt-dynamic-component/commit/cbfa48deda28fee721fc45ecbd7ddc74ec1459c6
nuxt.bundle.js is reduce to 76kb  . 0.nuxt.bundle is 290kB 
![screenshot_7](https://cloud.githubusercontent.com/assets/7247064/26736363/44483c5e-47f8-11e7-91d2-3891eab90d9b.png)

but , it's have problem if user not login , it's no necessary send to user ~290kB ...

so , Third , make editor dynamic load .
https://github.com/ausir0726/nuxt-dynamic-component/commit/69d7f0d45f1aec64111b28ea682fa5bf763cd055

`Voilà` , now 0.nuxt.bundle reduce to 9.49kb , 4.nuxt.bundle is 288kB
you can just import your editor.vue when user after login.
![screenshot_8](https://cloud.githubusercontent.com/assets/7247064/26736478/c8c04cba-47f8-11e7-8ddb-3e81d79c4dc1.png)

last , I add a editor loading message , and give a counter see when nuxt.js beforeMount that counter will trigger , and stop when editor mount . ( you can change chrome network speed for test this )
https://github.com/ausir0726/nuxt-dynamic-component/commit/382c5a9b1b29c17112418701b4416b34b3a214c5
![screenshot_9](https://cloud.githubusercontent.com/assets/7247064/26736552/361ed344-47f9-11e7-8d8e-b5efd80d0d64.png)

online test `please change network speed to 3G`
nuxt-dynamic-component.surge.sh

repo: https://github.com/ausir0726/nuxt-dynamic-component

**Comment by bimohxh** [comment]
@ausir0726 wow, You are a good man, I love you. haha I will try this right now!

**Comment by bimohxh** [comment]
@ausir0726 我试了一下，实际结果是， `nuxt.bundle.xxxx.js`  被分割出去了一部分代码 `19.nuxt.bundle.xxx.js`（应该就是editor的），但是在页面加载的时候仍然把这部分代码加载过来了，只是降低了  `nuxt.bundle.xxxx.js`  的大小，多了一个请求，我的理解正确吗？或者更好的结果是，当我点击按钮，展示editor的时候再去加载 `19.nuxt.bundle.xxx.js`?

**Comment by ausir0726** [comment]
hi @bimohxh ,

please write English 🙇 

yes , you are right , you can load your editor after user login .
or load when user want report .

that package is 300Kb ( minified ) , you can't reduce it anymore .
you just can load it when user really need it . 
if only 5% need that package , You should not send other 95% users.

and ... that will let your main js finish early , that can avoid your application stuck with user when download main js.

**Comment by ausir0726** [comment]
maybe ,

when user click [ leave message ] then you load your editor component is best practice

**Comment by bimohxh** [comment]
@ausir0726 Yes, I just  really want to know how can I realize when I click a button load the component. Because the current code will load the editor component firstly

**Comment by ausir0726** [comment]
```
export default {
  method : {
    async showMessage () {
      await import('editor.vue')
      // like this ...
    }
  }
}
```

**Comment by bimohxh** [comment]
@ausir0726  Awesome, seems it works!

my code change like:

```
div.pub-news(v-show="isShowPub")
  editor(...)

button.pub-btn(@click="showPub") Submit
```
And the  `showPub` method is :
```
showPub: async function () {
        this.isShowPub = true
        const editor = await import('~components/editor.vue')
        Vue.component('editor', editor)
      }
```

**Comment by bimohxh** [comment]
@ausir0726  But has a strange thing, if I change `showPub'  to:
 
```
showPub: async function () {
       this.isShowPub = true
        const editor = await import('~components/editor.vue')
        Vue.component('editor', editor)
      }
```

The editor js will be loaded, but the editor will not show in the page.

Or, if I let `div.pub-news`  always show,  but the editor will not show. why?

**Comment by ausir0726** [comment]
@bimohxh  


use `v-if` on editor will be better .
and write `v-else` div when loading text .
```pug
div.editor
  editor(v-if="isShowPub")
  div(v-else) editor loading...
```

```
showPub: async function () {
       
        const editor = await import('~components/editor.vue')
        Vue.component('editor', editor)
        this.isShowPub = true // after load componet change to true
      }
```
`v-if` will trigger component rerender . 
but `v-show` just a css display none ...

**Comment by bimohxh** [comment]
@ausir0726 Thanks, I have apply your code.

**Comment by ausir0726** [comment]
Is it work ?

**Comment by bimohxh** [comment]
@ausir0726 Yes  it work now !

**Comment by ausir0726** [comment]
awesome
