### ISSUE TITLE
serverMiddleware doesn't work when running with static target in production

### ISSUE THREAD

**Issue by Fyroman** [nuxt/nuxt.js#8230]
When using this.addServerMiddleware from module, it works in dev mode, but doesn't work in production mode. Same thing when placing it normally in nuxt.config.js.

**Comment by danielroe** [comment]
@Fyroman This is intended, because the the static target is intended for [static hosting](https://nuxtjs.org/docs/2.x/features/deployment-targets/#static-hosting). You should make your own arrangements for hosting your `serverMiddleware` on a separate server (or as serverless endpoints).
