### ISSUE TITLE
errorCaptured not catching error throwed in fetch hook

### ISSUE THREAD

**Issue by drocha87** [nuxt/nuxt.js#8231]
### Versions

- nuxt: ^2.14.1
- node: 14.12 

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Setup `errorCaptured` hook on default layout.
```typescript
errorCaptured(err: Error, _vm: Vue, _info: string): boolean {
   console.log(err.message);
    return false;
  }
```

throw an error from `fetch` hook, with or without `fetchOnServer: false`

### What is Expected?
`errorCaptured` to catch the error and handle it

### What is actually happening?
The error is not being catched by errorCaptured.

**Comment by Kolobok12309** [comment]
Fetch hook place error to `$fetchState.error`, you can use
```
watch: {
  '$fetchState.error'(err) {
    throw err;
  }
}
```
But agree, mb property which describe how need catching error need
