### ISSUE TITLE
scrollToTop throws `Page.options is undefined`

### ISSUE THREAD

**Issue by masterada** [nuxt/nuxt.js#8234]
### Versions

- nuxt: v2.14.6
- node: v12.18.3

### Reproduction

Not sure how to reproduce.

### Issue

This line: `Pages.some(Page => Page.options.scrollToTop)` in router.scrollBehaviour sometimes throws an error: `Page.options is undefined`. This prevents the page from loading properly. Not sure how this can happen. Consol error is shown both in dev mode and prod mode, but only breaks the page in dev mode.

**Comment by danielroe** [comment]
@masterada Would you be able to attempt a reproduction, or share some more information about what kind of nested routes you have in your app, and what kind of scrolling you would expect to see across those pages?

**Comment by danielroe** [comment]
This can be seen in https://github.com/nuxt/nuxt.js/blob/b4d3ebf472a8b51b3c8b3f0c0162891987105d8d/test%2Ffixtures%2Fspa-base
