### ISSUE TITLE
Cant get jest to cover some .vue files when using --coverage

### ISSUE THREAD

**Issue by franciscouemura** [nuxt/nuxt.js#8236]
Hi everybody!
I'm using nuxt to develop a dashboard on the company I work for. Unfortunetly I'm struggling with jest when I run the all tests with the coverage option it doesn't show all of my .vue files. I have the following file structure:

├── base-components
│   ├── AppBar.vue
│   ├── buttons
│   │   ├── IconBackButton.vue
│   │   ├── PrimaryButton.vue
│   │   ├── PrimaryTextButton.vue
│   │   ├── SendEmailButton.vue
│   │   └── __tests__
│   │       ├── IconBackButton.spec.js
│   │       ├── PrimaryButton.spec.js
│   │       ├── PrimaryTextButton.spec.js
│   │       └── SendEmailButton.spec.js
│   ├── cards
│   │   └── PrimaryCardTitle.vue
│   ├── data-table
│   │   ├── DataTableMenuItem.vue
│   │   ├── DataTableMenu.vue
│   │   ├── DataTable.vue
│   │   ├── index.js
│   │   ├── NoDataAlert.vue
│   │   └── Searchbar.vue
│   ├── dialogs
│   │   ├── BaseDialog.vue
│   │   └── ConfirmDialog.vue
│   ├── FooterComponent.vue
│   ├── inputs
│   │   ├── BaseSelect.vue
│   │   ├── DateSelect.vue
│   │   ├── EmailField.vue
│   │   ├── PasswordConfirmField.vue
│   │   └── PasswordField.vue
│   ├── Loading.vue
│   ├── NavigationDrawer.vue
│   ├── Notification.vue
│   ├── NuxtContent.vue
│   └── toolbars
│       ├── PrimaryToolbar.vue
│       ├── __tests__
│       │   └── ToolbarIconButton.spec.js
│       ├── ToolbarIconButton.vue
│       ├── ToolbarItem.vue
│       └── ToolbarTitle.vue
├── login
│   ├── LoginButton.vue
│   ├── LoginCard.vue
│   └── LoginForm.vue
├── README.md
├── recover
│   └── RecoverCardText.vue
├── reset-password
│   ├── ResetPasswordCard.vue
│   └── ResetPasswordForm.vue
└── __tests__
    ├── Loading.spec.js
    └── Notification.spec.js

**but on the coverage report I only get the following:**

File                                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------------------------|---------|----------|---------|---------|-------------------
All files                              |   14.02 |        0 |   16.13 |   14.02 |                   
 components/base-components            |   57.89 |      100 |   46.15 |   57.89 |                   
  AppBar.vue                           |       0 |      100 |       0 |       0 | 22                
  Loading.vue                          |   71.43 |      100 |      75 |   71.43 | 47-48             
  NavigationDrawer.vue                 |       0 |      100 |       0 |       0 | 31-51             
  Notification.vue                     |   85.71 |      100 |      75 |   85.71 | 15                
 components/base-components/buttons    |     100 |      100 |     100 |     100 |                   
  IconBackButton.vue                   |     100 |      100 |     100 |     100 |                   
  PrimaryButton.vue                    |     100 |      100 |     100 |     100 |                   
  PrimaryTextButton.vue                |     100 |      100 |     100 |     100 |                   
  SendEmailButton.vue                  |     100 |      100 |     100 |     100 |                   
 components/base-components/data-table |       0 |        0 |       0 |       0 |                   
  DataTable.vue                        |       0 |      100 |       0 |       0 | 26-63             
  Searchbar.vue                        |       0 |        0 |       0 |       0 | 19-89             
 components/base-components/dialogs    |       0 |      100 |       0 |       0 |                   
  BaseDialog.vue                       |       0 |      100 |     100 |       0 | 26                
  ConfirmDialog.vue                    |       0 |      100 |       0 |       0 | 22-41             
 components/base-components/inputs     |       0 |      100 |       0 |       0 |                   
  BaseSelect.vue                       |       0 |      100 |       0 |       0 | 53-103            
  DateSelect.vue                       |       0 |      100 |       0 |       0 | 30-59             
  EmailField.vue                       |       0 |      100 |       0 |       0 | 25                
  PasswordConfirmField.vue             |       0 |      100 |       0 |       0 | 20                
  PasswordField.vue                    |       0 |      100 |       0 |       0 | 20                
 components/base-components/toolbars   |       0 |      100 |     100 |       0 |                   
  PrimaryToolbar.vue                   |       0 |      100 |     100 |       0 | 13-14             
 components/login                      |       0 |      100 |       0 |       0 |                   
  LoginButton.vue                      |       0 |      100 |       0 |       0 | 10                
  LoginCard.vue                        |       0 |      100 |     100 |       0 | 8-9               
  LoginForm.vue                        |       0 |      100 |       0 |       0 | 20-43             
 components/recover                    |       0 |      100 |       0 |       0 |                   
  RecoverCardText.vue                  |       0 |      100 |       0 |       0 | 15-32             
 components/reset-password             |       0 |      100 |       0 |       0 |                   
  ResetPasswordCard.vue                |       0 |      100 |     100 |       0 | 8-9               
  ResetPasswordForm.vue                |       0 |      100 |       0 |       0 | 20-33             
 pages                                 |       0 |        0 |       0 |       0 |                   
  index.vue                            |       0 |      100 |     100 |       0 | 7                 
  login.vue                            |       0 |      100 |     100 |       0 | 12                
  recover.vue                          |       0 |        0 |       0 |       0 | 16-44             
  reset-password.vue                   |       0 |      100 |     100 |       0 | 12                
 store/base-store                      |       0 |      100 |       0 |       0 |                   
  actions.js                           |       0 |        0 |       0 |       0 |                   
  getters.js                           |       0 |        0 |       0 |       0 |                   
  index.js                             |       0 |        0 |       0 |       0 |                   
  mutations.js                         |       0 |        0 |       0 |       0 |                   
  state.js                             |       0 |      100 |       0 |       0 | 1            

I have some solutions. the last one was the one of https://github.com/vuejs/vue-jest/issues/217
had no luck.
I'm sending attached to the configs of the project. If somebody could give it a try would be of great value.
Thank you all.     

[files.zip](https://github.com/nuxt/nuxt.js/files/5418739/files.zip)

**Comment by Geminii** [comment]
Hi @franciscouemura 
Can you tell us the vue files which doesn't appear into your coverage ? 
And maybe purpose a quick archive to reproduce it ? 

Here is a part of my Jest configuration : 
```js
  modulePaths: [
    '<rootDir>'
  ],
  moduleDirectories: [
    'node_modules'
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)(\\?inline)?$': 'jest-transform-stub',
    '^~/(.*)$': 'vue-jest'
  }
````
