### ISSUE TITLE
issue with the offline plugin with CDN

### ISSUE THREAD

**Issue by dyaa** [nuxt/nuxt.js#824]
Hello, 

I'm facing a problem with the offline plugin while hosting my assets in a CDN it's giving me this error.

> Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://cdn.domain.com') does not match the current origin ('https://domain.com').

How can i fix that should we host the **sw.js** in the **/static** folder if so can we do that automatically ?

**Comment by Atinux** [comment]
@dyaa we are currently working on refactoring the offline module to make it external of Nuxt.js.

When ready, we'll be able to help you :)

**Comment by pi0** [comment]
Hi @dyaa . We are working a new generation service worker from chrome team, [workbox](https://github.com/nuxt/modules/tree/master/modules/workbox). Will be so nice if hear your feedbacks on it.  Basically it should support CDN as well. Also about `sw.js` yes it is automatically copied to `static` dir by this module.

**Comment by dyaa** [comment]
Thanks @pi0 i'll try in now :+1: ...

**Comment by dyaa** [comment]
It got score of `100` on lighthouse tests.
