### ISSUE TITLE
query string changes and keep-alive doesn't work correctly

### ISSUE THREAD

**Issue by baermathias** [nuxt/nuxt.js#8240]
### Versions

- nuxt: 2.14.7
- node: 12.18.2

### Reproduction

https://codesandbox.io/s/fervent-gates-8oqig
watch the console.log output

### Steps to reproduce

I use `<nuxt keep-alive/>` inside `layouts/default.vue`. And I use `watch: { '$route.query': this.$fetch() }` inside of a UI component. If I move from one page to another, `this.$fetch()` is triggered all the time, even if the UI component (which whatches the route) is not inside the page. It doesn't has to do with `$fetch()`, I could also call a method instead. It is an issue with `watch` and `keep-alive`. The question is why is this happening?

Also the docs are kinda misleading:
https://nuxtjs.org/api/pages-fetch#listening-to-query-string-changes
https://nuxtjs.org/api/pages-fetch#caching

Because they state:

>You can use keep-alive directive in `<nuxt/>` and `<nuxt-child/>` component to save fetch calls on pages you already visited.

But exactly the opposite happens. If I remove `keep-alive` from `<nuxt/>`, then `$fetch()` is only triggered if I am on the page, which contains the UI component (which watches `$route.query`) and this way I actually save fetch calls on pages. If I do it like its stated in the docs `fetch()` is called all the time.

### What is Expected?
What is written in the docs

### What is actually happening?
The opposite

**Comment by baermathias** [comment]
Any feedback on this?

**Comment by Atinux** [comment]
Actually this is same issue as #7156

See my comment: https://github.com/nuxt/nuxt.js/issues/7156#issuecomment-627439286
