### ISSUE TITLE
Add `async`  attribute to webpack scripts

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt.js#8242]
### Is your feature request related to a problem? Please describe.

Webpack seems to have fixed the issue when using `async`.

### Describe the solution you'd like

Add `defer` **and** `async`  to webpack scripts.

### Additional context

I tested on nuxtjs.org using hooks in `nuxt.config.js`:

```js
export default {
  hooks: {
    'render:route': function (url, result, context) {
      result.html = result.html.replace(/ defer>/g, ' defer async>')
    },
    'generate:page': (page) => {
      page.html = page.html.replace(/ defer>/g, ' defer async>')
    }
  }
}
```

An it works perfectly :)

**Comment by Timkor** [comment]
I think this is causing major performance issues because of the injected render blocking scripts (before document load). Any ETA when this will be released?

**Comment by danielroe** [comment]
@Timkor For now, you can simply use the workaround mentioned above within `nuxt.config`.

**Comment by Timkor** [comment]
@danielroe What about the scripts injected by those scripts?

**Comment by danielroe** [comment]
It replaces it at the HTML level so all scripts in the head should be affected.

**Comment by Timkor** [comment]
@danielroe True, but apparently, those scripts add more script tags to the head during execution, which do not have any async nor defer attributes:
![image](https://user-images.githubusercontent.com/6882876/100615455-edb10d80-3317-11eb-9c73-2c3c56fffbdf.png)

And this is injected before document load delaying FCP and LCP. Any idea's?
