### ISSUE TITLE
Layout is not applied

### ISSUE THREAD

**Issue by jappyjan** [nuxt/nuxt.js#8243]
### Versions

- nuxt: 
- node: 

### Reproduction

could not reproduce it anywhere else so far...

### Steps to reproduce

create another layout
set the "layout" data property in any page to the newly created layout

### What is Expected?

the new layout should be used for that page

### What is actually happening?

the "default" layout is beeing used.
if no default.vue layout exists it renders a <.nuxtLayoutsDefault.vue> component/layout but still not the new layout...

codesplitting for layouts is active (also not working if deactivated)

**Comment by Atinux** [comment]
I am sorry but this is not a valid bug report. Please create a reproduction with template.nuxtjs.org
