### ISSUE TITLE
Using eslint-webpack-plugin instead of eslint-loader (deprecated) results in very slow server compiling on update

### ISSUE THREAD

**Issue by jirkae** [nuxt/nuxt.js#8244]
### Versions

- nuxt: 2.14.7
- node: 14.14

### Reproduction

Because of eslint-loader is deprecated, I`ve tried to use eslint-webpack-plugin. Results were pretty promissing for the first sign, but when I editted file, it took 4s for compiling server - compiling client was OK (100ms)

Init compilation took only 6s instead of 20s with eslint-webpack-plugin

### Steps to reproduce

Replace 
```
config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        })
```
with
```
import ESLintPlugin from 'eslint-webpack-plugin'

config.plugins.push(new ESLintPlugin())
``` 
in nuxt.config.js

### What is Expected?

Simmilar compiling time on file update as with eslint-loader

**Comment by pi0** [comment]
Hi @jirkae! Good news is that this is already done by `@nuxtjs/eslint` [v3.0.0](https://github.com/nuxt-community/eslint-module/blob/master/CHANGELOG.md#300-2020-10-07)
