### ISSUE TITLE
Support Webpack 5

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt.js#8252]
I know that you are developing Nuxt 3 now, and I'm sure it will support Webpack 5, but will you add support of it in 2.x? If so, do you have any deadline for that?

**Comment by shadow81627** [comment]
Here is the pull request link for webpack 5 support: https://github.com/nuxt/nuxt.js/pull/4616

**Comment by manniL** [comment]
I personally don't think WP5 will land on Nuxt 2.x as it will introduce breaking changes. If not internally, at least to modules + custom configs of the user. As a breaking change usually means a major version, you likely have to wait for Nuxt 3 which will be based on WP5.
