### ISSUE TITLE
What is missing so that the build process does not exceed 1 minute with "responsive-loader" ?

### ISSUE THREAD

**Issue by johan-Rm** [nuxt/nuxt.js#8253]
With my nuxt js project, in my "assets" folder I have 150 images for a weight of 122M, I use the "responsive-loader", but when I run the "build" command the process is too long. How can I debug?
why does it take so long to load 150 images? I will need to load 1500 images in the future ...

Moreover the images that I have already optimized with "jpegoptim -quality 20" still exceed the recommended size, how do you do?

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  img/activities-img-golf.daadaee.jpeg (856 KiB)
```

Can you tell me the best practice?

**Comment by danielroe** [comment]
@johan-Rm This is more a question for [`responsive-loader`](https://github.com/dazuaz/responsive-loader) than Nuxt. You can also consult a search engine for reasonable settings for `jpegoptim`.

However, to answer your question, it takes time to run image optimisation. That's unavoidable if you are doing your image optimisation on every build. Personally I would optimise my images before committing them to my repo, or use a CDN/image processing service that does the optimisation for you per-request.
