### ISSUE TITLE
Router Navigation Inside asyncData Is Buggy

### ISSUE THREAD

**Issue by XiNiHa** [nuxt/nuxt.js#8256]
### Versions

- nuxt: v2.14.6
- node: v12.16.1

### Reproduction

```typescript
Vue.extend({
  async asyncData ({ app }) {
    app.router?.push('/somewhere') // or any kind of router navigation
  }
})
```
When performing router navigation inside `asyncData()`, it becomes very buggy
First I found that navigating to a page with different layout doesn't work properly (the layout doesn't change initially, and suddenly changes when I click the address bar, etc.)
And while creating a small reproduction case, I had some issues that the navigation goes to the target page then immediately go back to the previous one. After experiecing all of these things, it seems like it's not a supported behavior at all.

### What is Expected?
Router navigation works as expected.

### What is actually happening?
Not working as intended

**Comment by pmoralesp** [comment]
What about using `redirect`?

```js
Vue.extend({
  async asyncData ({ redirect }) {
    redirect('/somewhere')
  }
})
```

**Comment by XiNiHa** [comment]
It could be a solution in some cases. However, the feature of `redirect` is limited compared to standalone router features.
