### ISSUE TITLE
Routing jump rendering problem

### ISSUE THREAD

**Issue by foreinbug** [nuxt/nuxt.js#8259]
### What is Expected?
The source of the page renders the content, but does not display the content, and the DOM is replaced with
``` html
<!-- function(e,n,r,i){return Pt(t,e,n,r,i,!0)} -->
```
The rendered DOM is captured at the moment of the route jump and is immediately replaced with the content above
But the source code for the browser view contains the rendered content, and it will display properly when refreshed

### What is actually happening?

Nuxt-link to enter the page does not need to refresh, can normally display the source content

**Comment by danielroe** [comment]
@foreinbug Could you provide a reproduction at https://template.nuxtjs.org ?
