### ISSUE TITLE
How to process files from Assets with PostCSS?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#827]
Hi. Seems like if I put PostCSS in Assets (for example @custom-media) and then use it files doesn't processs through PostCSS, since nothings working. Tried `nuxt.config` and @import. Any workaround?

**Comment by cliffrowley** [comment]
Having the same issues here, can't seem to "turn on" postcss, despite being able to prod it by messing around with the config (try adding an autoprefixer, and nuxt complains that two are present).  Not really sure what's going on, but I think I'm just going to go back to SASS for the time being as it's the path of least resistance (and it doesn't seem like postcss is a first class citizen in nuxt in the same way stylus/sass is - at least, they seem to work out of the box with very little poking).

**Comment by Atinux** [comment]
Hi @kodekrendel ,

Can you reproduce the issue by forking https://glitch.com/edit/#!/nuxt-1-hello-world?

it will be easier to help you.

**Comment by kodekrendel** [comment]
@Atinux here's example - https://glitch.com/edit/#!/zippy-airplane

**Comment by Atinux** [comment]
Hi @kodekrendel 

Thank you for the reproduction, it's easier to help you with it.

Indeed, postcss is handled by vue-loader directly, so you need to tell Nuxt to use the `postcss-loader` when loading CSS files.

`nuxt.config.js`:

```js
extend (config) {
  // Add postcss loader for CSS files
  const cssLoader = config.module.rules.find((loader) => loader.test.toString() === '/\\.css$/')
  cssLoader.use.push('postcss-loader')
}
```

Then you need to add `postcss.config.js` file:
```js
module.exports = {
  plugins: {
    'postcss-cssnext': true
  }
}
```

This way, vue-loader will also use this config file directly :)

Demo: https://nuxt-postcss-global.glitch.me/
Code: https://glitch.com/edit/#!/nuxt-postcss-global

**Comment by cliffrowley** [comment]
I ended up going a sightly different route because I just couldn't get things to work properly going through Nuxt.  The relevant part of my `nuxt.config.js` looks like this:

```
  build: {
    extend (config, ctx) {
      if (ctx.isClient) {
        // eslint
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
        // stylelint
        config.plugins.push(require('stylelint-webpack-plugin')({
          configFile: '.stylelintrc',
          context: 'client',
          files: '**/*.css',
          failOnError: false,
          quiet: true
        }))
        // Handle stylelint errors properly
        config.plugins.forEach(p => {
          if (p.constructor.name === 'FriendlyErrorsWebpackPlugin') {
            p.transformers.push(friendlyErrorTransformer)
            p.formatters.push(friendlyErrorFormatter)
          }
        })
      }
    },
    postcss: [],
    loaders: [
      {
        test: /\.css$/,
        loader: 'postcss-loader'
      }
```

Now everything is driven by `postcss.config.js` and I don't need to mess around with the nuxt config to configure postcss (and my editor can now pick up the configuration too).
