### ISSUE TITLE
Documentation: Async Data Guide missing

### ISSUE THREAD

**Issue by pi43r** [nuxt/nuxt.js#8270]
Many sites are linking to the following, which seems to be completely gone:

[https://nuxtjs.org/guide/async-data](https://nuxtjs.org/guide/async-data)

Sometimes the documentation page renders `Guides(beta)` and `Guide` in the menu.
If I click Guide (no s) there it was able to fetch the corresponding data, so it seems to be a redirect issue.

Please fix as the documentation seems faulty that way.

**Comment by danielroe** [comment]
@pi43r Thanks for the report - really helpful. ❤️ There is also a repo for the website, FYI: https://github.com/nuxt/nuxtjs.org/

(See https://github.com/nuxt/nuxtjs.org/issues/908)

**Comment by danielroe** [comment]
Hopefully this is now fixed. Thanks for reporting!
