### ISSUE TITLE
Nuxt Firebase Config results in bunch of errors

### ISSUE THREAD

**Issue by bacon-delight** [nuxt/nuxt.js#8271]
I've followed instructions from https://firebase.nuxtjs.org/guide/getting-started on getting started and setting up a nuxt project with firebase. After doing everything as recommended, it results in a bunch of errors and warnings and crashes the main JS thread. This is likely a problem with Nuxt's official Firebase library.

Repository for reproduction: https://github.com/bacon-delight/nuxt-firebase-errors

### Versions

- nuxt: 2.14.6
- node: 12.18.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
`npm run dev` > Check console

### What is Expected?
Project should run normally without any errors or warnings

### What is actually happening?
Bunch of errors and warnings, most likely main JS thread crashing due to some issues in nuxt-firebase

**Comment by danielroe** [comment]
@bacon-delight I appreciate the time you've taken to make this report. Is there any chance you could make it over at https://github.com/nuxt-community/firebase-module instead?
