### ISSUE TITLE
All doc links are dead. 404. Right from Google searches. 

### ISSUE THREAD

**Issue by timothymarois** [nuxt/nuxt.js#8272]
Hey guys, looks like no google results go to real pages anymore. they are all 404. 

At least setup a redirect from old to new location. 

<img width="1148" alt="Screen Shot 2020-10-30 at 9 42 52 PM" src="https://user-images.githubusercontent.com/2489333/97768363-e4563a80-1af8-11eb-91ff-5532bdb10624.png">

These I found from google: 
https://nuxtjs.org/guide/routing/
https://nuxtjs.org/api/configuration-router/
https://nuxtjs.org/api/pages-middleware/
https://nuxtjs.org/api/nuxt-render-route/

Literally every single page on google is down, I do a search, most of the results are nuxt, but they are all dead. 

<img width="630" alt="Screen Shot 2020-10-30 at 9 45 19 PM" src="https://user-images.githubusercontent.com/2489333/97768421-52026680-1af9-11eb-84f8-b96ec5d7b716.png">

**Comment by danielroe** [comment]
@timothymarois Thanks for the report - great catches. ❤️ There is also a repo for the website, FYI: https://github.com/nuxt/nuxtjs.org/

(See https://github.com/nuxt/nuxtjs.org/issues/908)

**Comment by danielroe** [comment]
Hopefully this is now fixed. Thanks for reporting!
