### ISSUE TITLE
nuxtjs.org website broken

### ISSUE THREAD

**Issue by baermathias** [nuxt/nuxt.js#8273]
There are several things, which don't work on your website, it looks a little bit neglected:

![Screenshot from 2020-10-31 08-46-53](https://user-images.githubusercontent.com/45003352/97774140-ca971080-1b55-11eb-889e-cc09715a901c.png)
![Screenshot from 2020-10-31 08-45-48](https://user-images.githubusercontent.com/45003352/97774142-cbc83d80-1b55-11eb-9284-92ae6929ef39.png)
![Screenshot from 2020-10-31 08-45-30](https://user-images.githubusercontent.com/45003352/97774143-cbc83d80-1b55-11eb-88a5-533265f024f3.png)

Every second menu point can't be found???

![Screenshot from 2020-10-31 08-50-56](https://user-images.githubusercontent.com/45003352/97774217-4c873980-1b56-11eb-9d4b-14b2cc669ae5.png)
![Screenshot from 2020-10-31 08-50-42](https://user-images.githubusercontent.com/45003352/97774219-4d1fd000-1b56-11eb-9096-2f5beb6a6504.png)
![Screenshot from 2020-10-31 08-50-31](https://user-images.githubusercontent.com/45003352/97774220-4d1fd000-1b56-11eb-98d3-bd3cecdfe1d3.png)

**Comment by danielroe** [comment]
@baermathias Thanks for the report. ❤️ Next time, this would be better made against the website repo https://github.com/nuxt/nuxtjs.org/

We'll definitely look at the 404 links, but the missing home page images are probably the result of an ad blocker.

(See https://github.com/nuxt/nuxtjs.org/issues/908)

**Comment by Geminii** [comment]
@baermathias The team is already on it :) 
The new guides has been deployed and moove to new link. It will be fixed this Monday ;)
