### ISSUE TITLE
Invalid CSS asset filenames generated, breaks site operation

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/nuxt.js#8274]
### Versions

- nuxt: 2.14.17
- node: 10.15.3

### Reproduction

https://github.com/IlyaSemenov/nuxt-css-invalid-filename-reproduction

### Steps to reproduce

Using Node 10.15.3 and yarn 1.22.5:

```
yarn
yarn nuxt build
```

(See README in the reproduction repo.)

### What is Expected?

Build completes successfully. All generated filenames are valid.

### What is actually happening?

Build completes successfully, however one of the filenames is invalid: `pages/123456789_123456789_123456789_123456789_/pages/test1/test/pages/test2/pages/test2/index/pages//6c0ffc7c.c67c3ba.css`. Note the double slash near the end (`pages//6c0ffc7c.c67c3ba.css`).

This invalid filename goes to the manifest. When these static assets are deployed onto certain CDNs (such as Amazon S3 compatible storages), they wouldn't load, for example:

[schools//8be984b7.6b1ee97.css](https://hb.bizmrg.com/eg11-static/pages/user/_role/coverage/pages/user/_role/dashboard/pages/user/_role/operators/_operatorId/schools//8be984b7.6b1ee97.css) -> 403 Access Denied
[schools/8be984b7.6b1ee97.css](https://hb.bizmrg.com/eg11-static/pages/user/_role/coverage/pages/user/_role/dashboard/pages/user/_role/operators/_operatorId/schools/8be984b7.6b1ee97.css) -> 200 OK

Moreover, this broken chunk completely breaks `<nuxt-link>`'s pointing to the affected page! (Not included in the minimal reproduction, although it's not hard to add.)

### Additional context

This is a regression introduced with https://github.com/nuxt/nuxt.js/pull/7463 where the css/images/video URLs were changed to include `[name]`.

Also, the [documentation](https://github.com/nuxt/nuxtjs.org/blob/f36f50ca3555162a1a98933cb705f02ecff3214b/content/en/guides/configuration-glossary/configuration-build.md#filenames) misleadingly lists the old defaults:

```
css: ({ isDev }) => isDev ? '[name].css' : '[contenthash].css'
```

which is not true anymore.

**Comment by Geminii** [comment]
Hi @IlyaSemenov, 
I reproduced your problem but it seems due to your file named : `123456789_123456789_123456789_123456789_.vue`
The `underscore` at the end of your file cause this side effect about filenames. 

If you want to keep the name with `_` at the end, you can use : 
```
build: {
   extractCSS:true,
   filenames: {
      css: ({ isDev }) => (isDev ? '[name].css' : '[id].[contenthash].css')
   }
}
```

Hope this help you :)

**Comment by IlyaSemenov** [comment]
> The underscore at the end of your file cause this side effect about filenames.

Of course this it not true. I updated the reproduction repository to demonstrate that (simply renamed the file to `123456789_123456789_123456789_123456789x.vue`, the problem persisted).

And of course it doesn't have anything to do with the file name being 40 symbols length either. I am experiencing the same problem in my real project with 'normal' file names. In the reproduction repo, I was simply creating randomly named files until I managed to reproduce the bug. 

> If you want to keep the name with _ at the end, you can use :

Thank you, I understand how it works. Please consider this a bug report, not a support request.

**Comment by IlyaSemenov** [comment]
1. The problem repeats on the latest nuxt-edge@2.15.0-26788356.847d4ae0
2. The steps to reproduce are outlined in the reproduction repository (https://github.com/IlyaSemenov/nuxt-css-invalid-filename-reproduction): `yarn && yarn nuxt build`

**Comment by markkarimov** [comment]
I have a similar issue with loading a chunk, it tries to retrieve `_nuxt/vendors/pages/campaigns/_id/contributors/pages/campaigns/_id/index/pages/campaigns/_id/transactions//a030a1aa.3261ee4.js` (note the double forward slash before the js file), and that breaks the loading of the page.

**Comment by IlyaSemenov** [comment]
1. The problem repeats on the latest nuxt-edge@2.15.0-26870440.3b02beb0
2. The steps to reproduce are outlined in the reproduction repository (https://github.com/IlyaSemenov/nuxt-css-invalid-filename-reproduction): `yarn && yarn nuxt build`

**Comment by sfausto** [comment]
Same here. I cant find a pattern on when this happens

**Comment by claudiolcastro** [comment]
Its seems that the issue was resolved just for the css files case. I'm having the same problem here with app and chunk files names.
`//475b6968.b5e6a74.js`
