### ISSUE TITLE
Bundle with "esbuild" instead of "webpack" and "rollup"

### ISSUE THREAD

**Issue by doriandrn** [nuxt/nuxt.js#8276]
### Is your feature request related to a problem? Please describe.

Not really a major problem but compile and build times in (large) projects do take a while as of right now;

### Describe the solution you'd like

Use the [esbuild lib](https://esbuild.github.io/) instead of webpack and rollup. Esbuild does a way better job these days apparently and this could be a really nice improvement for Nuxt!

### Describe alternatives you've considered

- None

### Additional context

I have looked over the code myself through time as a long time Nuxt user and seems to me that esbuild got everything it needs right now to work for Nuxt;

**Comment by manniL** [comment]
Check out [this module](https://github.com/galvez/nuxt-esbuild-module) from @galvez that uses the esbuild-loader.

**Comment by doriandrn** [comment]
@manniL Thank you, I totally missed on this one!

**Comment by pi0** [comment]
BTW esbuild is also default loader for nuxt3 dev :)
