### ISSUE TITLE
template import modules use absolute path

### ISSUE THREAD

**Issue by laotan** [nuxt/nuxt.js#828]
in my situation，I prebuild nuxt app with CI tools like Jenkins

result:

```
//.nuxt/router.js
const _24c434bb = () => import('/foo/bar/pages/xxx.vue' )
```
then, my build task would transport all files to production environment, which directory structure is different with build env,  so my app can not run correctly

what i expected is relative path
```
//.nuxt/router.js
const _24c434bb = () => import('../pages/xxx.vue' )
```

influenced files:  

- components/nuxt.vue
- App.vue
- index.js
- router.js

**Comment by Atinux** [comment]
Closing it since `rc3` is out
