### ISSUE TITLE
nuxt中关于router-link跳转和$router.push造成的页面阻塞

### ISSUE THREAD

**Issue by hj009** [nuxt/nuxt.js#8287]
使用 $router.push 进行当前页面的内同切换，是正常的。

使用router-link 第一次跳到新的页面，正常，不关闭该页面，重新再跳一次，页面会一直loading，页面部分内容缺失。继续跳第三次，整个页面loading，完全阻塞。   

config.js是否需要做配置

**Comment by danielroe** [comment]
@hj009 Could you provide a reproduction?
