### ISSUE TITLE
v1.0 plugins: window.onNuxtReady is undefined

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#829]
Plugins written in the pre 1.0 style - without the exported function runs before `window.onNuxtReady` is set. Causing `onNuxtReady` is not a function error messages. 

Not sure if this is a design decision but it should be noted as a breaking change. 

Works
```
export default function () {

  if (process.BROWSER_BUILD) {
    console.log(window)
    console.log('onnuxtready defined', window.onNuxtReady)
  }

}
```

Does not work
```
if (process.BROWSER_BUILD) {
    console.log(window)
    console.log('onnuxtready not defined', window.onNuxtReady)
  }
```

**Comment by Atinux** [comment]
Hi @uptownhr 

Nice catch, will be fixed for next release (See https://github.com/nuxt/nuxt.js/commit/ea03d76e852cad1f614ed810ce8476eca664f574)

**Comment by Atinux** [comment]
It's now fixed with the alpha3
