### ISSUE TITLE
Dynamic routes with '@' in id, return 404 when generated as static site

### ISSUE THREAD

**Issue by syntheticgoo** [nuxt/nuxt.js#8290]
### Versions

- nuxt: v2.14.7
- node: v12.18.3

### Steps to reproduce

1. Create a dynamic route such as test/_id.vue
2. Set target: 'static', in nuxt.config.js
3. "nuxt generate"
4. "nuxt serve"
5. navigating to http://localhost:8000/test/adsfasd is fine (cut & paste)
6. navigating to http://localhost:8000/test/adsfasd@adfads.com results in a 404 error (cut & paste in browser, route linking works fine)

### What is Expected?
According to [RFC 1738](https://www.ietf.org/rfc/rfc3986.txt), '@' is a valid URL character, but considered a reserved delimiter. When serving the page using `target: 'server'` in nuxt.config.js, the page renders as expected. The 404 error only happens when using `target: 'static'`.

Can someone clairfy if this is a valid bug, and why the discrepancy when using different 'target' configs?

**Comment by danielroe** [comment]
@ syntheticgoo This seems to be a shortcoming of the `serve-static` server we use for previewing a static distribution with `nuxt start`. You can confirm this by testing with a different server:
```bash
npx http-server -p 3000 dist
```
