### ISSUE TITLE
IE10 syntax error, const not transpiled in ES5

### ISSUE THREAD

**Issue by maksimyurkov** [nuxt/nuxt.js#8292]
### Versions

- nuxt v2.14.7
- node v14.15.0
- npm 6.14.8
- IE10 (emulator in IE11)
- Windows 10 (x64)

### Reproduction

Default Nuxt application

`npx create-nuxt-app my-app`

Options
- NPM
- Single Page App
- Static
- Other options = Default

### Steps to reproduce

`npm run dev`

### What is Expected?

Correct work in Internet Explorer 10

### What is actually happening?

Page not working. Syntax Error, 'const' not transpiled.
Мy colleagues (with other system configurations) have the same problem.

![image](https://user-images.githubusercontent.com/17424327/98010574-e9243280-1e07-11eb-92f3-b6a3b1f9e19a.png)

P.S. In nuxt.config.js when i set "components": false, all working.

**Comment by danielroe** [comment]
@maksimyurkov Thanks for reporting! ❤️ Could you open an issue at https://github.com/nuxt/components/issues instead?

**Comment by maksimyurkov** [comment]
@danielroe Done!

https://github.com/nuxt/components/issues/109

**Comment by michaelpumo** [comment]
Are you using a dependency that might need transpiling? If so, have you set the transpile option in `nuxt.config.js`?

e.g.

```
build: {
  transpile: ['gsap', 'swiper', 'dom7']
}
```

**Comment by maksimyurkov** [comment]
> Are you using a dependency that might need transpiling? If so, have you set the transpile option in `nuxt.config.js`?
> 
> e.g.
> 
> ```
> build: {
>   transpile: ['gsap', 'swiper', 'dom7']
> }
> ```

not using, here are my dependencies (after `npx create-nuxt-app my-app`):

```
{
"dependencies": {
    "core-js": "^3.6.5",
    "nuxt": "^2.14.6"
  },
  "devDependencies": {}
}
```
