### ISSUE TITLE
Head scripts fire twice on initial page load

### ISSUE THREAD

**Issue by HMilbradt** [nuxt/nuxt.js#8293]
I also found this: https://github.com/nuxt/nuxt.js/issues/6906.  However, it was resolved with Nuxt-edge which I tried, and it's also a much older version of nuxt.  It's also a slightly different problem, where that bug was triggering scripts on the initial page load and then on the first navigation to another page.

### Versions

- nuxt: ^2.14.6
- node: v10.23.0

- Also tried Nuxt-edge ^2.14.8-26735067.baf94d31

### Reproduction

Repo
https://github.com/HMilbradt/nuxt-spa-bug

Live Link
https://musing-bassi-aca35b.netlify.app

Uses:
```
  ssr: false,
  target: "static",
```

Hosted on Netlify, **without** any redirect rules like the following.  However, on our main project we have tried this and still see the same issue.

```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

### Steps to reproduce

- Open the console
- Reload the page
- View the console output

### What is Expected?

Only a single "Firing script" log should be shown in the console. 

### What is actually happening?

Two "Firing script"'s are shown in the console.  The head scripts are being triggered twice on the first page load.  As expected, the head scripts are not fired while navigating within Nuxt.  It's just the initial page load.

Just to note, occasionally it only fires once.  If you continue to reload the page, eventually it will be only fired by the browser reading the initial script, and not by Nuxt.

It's causing a number of issues with our analytics and other log/metric collection scripts, such as initializing twice or firing twice.  

Here's a screenshot from Google chrome.  which shows that one looks to be triggered by the browser reading the HTML returned, and one seems to be Nuxt taking over and firing it again.

![Screen Shot 2020-11-03 at 10 02 33 AM](https://user-images.githubusercontent.com/22685915/98023389-b81e1080-1dbb-11eb-92cb-d24d12bfcfb2.png)

**Comment by Markiz9999** [comment]
I have the same problem with version 2.14.7.

**Comment by simondib** [comment]
This is still an issue on Nuxt v2.15.6 - noticed this behaviour with @nuxtjs/google-analytics
