### ISSUE TITLE
Dependency error while deploying on Netlify

### ISSUE THREAD

**Issue by RubenVanEldik** [nuxt/nuxt.js#8295]
## Versions

- nuxt: v2.13.0
- node: v12.18.0

### Reproduction
Create a new Nuxt.js project with only ESLint as linting tool. (https://github.com/RubenVanEldik/test3)

### Steps to reproduce
1. Deploy new Nuxt.js project to netlify
2. Add the .env variable: NODE_ENV=production

### What is Expected?
Succesful deployment.

### What is actually happening?
The deployment crashes when it tries to access @nuxtjs/eslint-module. 

I don't know a lot about the inner workings of Nuxt.js, but it looks like the package is not installed since it is in the devDepencies, which are not installed when the site is in production mode. It might have something to do with this issue, but I'm not sure: https://github.com/nuxt/eslint-plugin-nuxt/issues/87.

```
11:27:59 PM:    │   ✖ Nuxt Fatal Error                                           │
11:27:59 PM:    │                                                                │
11:27:59 PM:    │   Error: Cannot find module '@nuxtjs/eslint-module'            │
11:27:59 PM:    │   Require stack:                                               │
11:27:59 PM:    │   - /opt/build/repo/node_modules/@nuxt/core/dist/core.js       │
11:27:59 PM:    │   - /opt/build/repo/node_modules/@nuxt/cli/dist/cli-index.js   │
11:27:59 PM:    │   - /opt/build/repo/node_modules/@nuxt/cli/dist/cli.js         │
11:27:59 PM:    │   - /opt/build/repo/node_modules/nuxt/bin/nuxt.js 
```

**Comment by manniL** [comment]
> I don't know a lot about the inner workings of Nuxt.js, but it looks like the package is not installed since it is in the devDepencies, which are not installed when the site is in production mode. It might have something to do with this issue, but I'm not sure: nuxt/eslint-plugin-nuxt#87.

You are right. This happens because `@nuxtjs/eslint-module` is added to the `devDependencies` and will not be installed on Netlify when setting the node env to production. Either add the module to `buildModules` only when `NODE_ENV` is not production *or* add the module to the dependencies. I'd suggest the former.

Not an issue with Nuxt per se.

**Comment by RubenVanEldik** [comment]
Thank you for your response!

Is it common to have a depencency install only during development? I have never seen it before.

What would be the expected syntax, something like this?

```
process.env.BACKEND_URL !== 'production' && '@nuxtjs/eslint-module',
```

**Comment by manniL** [comment]
Definitely, e.g. testing libs, proxy (when using nuxt generate) or linters.

I do it that way: https://github.com/Developmint/developmint.de/blob/master/nuxt.config.js#L154-L161

Simplified:
```js
modules: [
    // Some modules here
  ].concat(process.env.NODE_ENV === 'production' ? '@nuxtjs/proxy' : []),
