### ISSUE TITLE
add Context type for ssr.

### ISSUE THREAD

**Issue by stmtk1** [nuxt/nuxt.js#8296]
### add Context for ssr.

Context type is used in asyncData, so this type does not have ssrContext attribute.
But this type is used in middleware function, so I can't use ssrAttribute in middleware function. I think these types should be different type.

### Describe the solution you'd like
Context should devide 2 types, ServerContext and ClientContext. but ClientContext may used in Server because of ssr. So ClientContext may be bad name.

``` javascript
// asyncData is used in Client Side, So this type is ClientContext
asyncData(context: ClientContext) {
   console.log(context);
}
```

``` middleware/hoge.js
// middleware/hoge.js
// middleware function is never used in client side. So this type should be ServerContext
export default function(context: ServerContext) {
      console.log(context);
}
```

**Comment by manniL** [comment]
Both, `asyncData` and `middleware` can be executed on server (initial request) *or* client-side (e.g. after/during navigation).

**Comment by stmtk1** [comment]
Oh, I took a mistake. sorry. You are right.
