### ISSUE TITLE
How to activate postcss-cssnext?

### ISSUE THREAD

**Issue by demetriusnunes** [nuxt/nuxt.js#83]
How can I configure the vue loader to enable postcss-cssnext?

**Comment by alexchopin** [comment]
Already answer on [#14](https://github.com/nuxt/nuxt.js/issues/14)

nuxt.config.js
```javascript
module.exports = {
  build: {
    postcss: [
      require('postcss-cssnext')()
    ]
  }
}
```

**Comment by demetriusnunes** [comment]
Thanks!

**Comment by nucamoz** [comment]
Why there is no 'build'? https://github.com/nuxt/nuxt.js/releases/tag/v0.6.7
Should I put 'build' or not?

**Comment by Atinux** [comment]
Nice catch @nucamoz it's updated.
