### ISSUE TITLE
Suggested way to integrate Cerebral as alternative store in Nuxt

### ISSUE THREAD

**Issue by ArnoBuschmann** [nuxt/nuxt.js#830]
I am trying to integrate Cerebral (http://www.cerebraljs.com) as alternative store in Nuxt.
The way how to combine Cerebral with Vue ist described here (bottom of the page):
http://cerebraljs.com/docs/introduction/view_type.html

I changed /layouts/default.vue in Nuxt as described below. The goal is to wrap the nuxt element with the cerebral container element.

```
<template>
  <div>
    <container>
      <nuxt/>
    </container>
  </div>
</template>

<script>

import {Controller} from 'cerebral'
import {Container} from 'cerebral/vue'

const controller = Controller({
  state: {
    foo: 'bar',
    mylist: [{ bird: 'eagle' }, { bird: 'owl' }, { bird: 'falcon' }]
  }
})

export default {
  name: 'default',
  components: {
    container: Container(controller)
  }
}
</script>
```
Obviously this is not working, because I can't export a default element on a nuxt layout page, just a template.

So I wonder, if someone can give me a pointer on how to do this the right way in Nuxt?

**Comment by piyushchauhan2011** [comment]
@ArnoBuschmann Does it work on pages or individual components ?

**Comment by ArnoBuschmann** [comment]
@piyushchauhan2011 I haven't worked with Nuxt yet, so I am not sure, but I'd say it should work on individual components.

Best would be if it wraps a Vue component at the highest root level at the app element:

```
<div id="app">
  <cerebral-container>
    <my-vue-component></my-vue-component>
  </cerebral-container>
</div>
```

**Comment by piyushchauhan2011** [comment]
Hmm, I believe Nuxt currently haven't abstracted `vuex` functionality to modules and when we define `index.js` file in store, it automagically detects everything which I think, because of tight integration with Vuex. It would be nice to see changeable `state` management solution that can be done by users through `nuxt-modules` @ArnoBuschmann

**Comment by alexchopin** [comment]
@piyushchauhan2011 the `store` folder is not required.
If you want to use another store you can add it in another folder or with a plugin.

**Comment by piyushchauhan2011** [comment]
@alexchopin aiye right, I'll try that. Cool +1

**Comment by piyushchauhan2011** [comment]
Hmm, even if we create a folder `cerebral-store/index.js` with following:

```javascript
import {Controller} from 'cerebral'

export default Controller({
  state: {
    foo: 'bar'
  }
})
```

and in our component instantiate the `store` like this

```javascript
import {Container} from 'cerebral/vue'
import controller from '../cerebral-store'

export default {
  components: {
    container: Container(controller)
  }
}
```

On creation of `<container><h1>Hey</h1></container>` Container it gives us this error related to server-side rendering

```javascript
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Container>
       <Default> at /Users/piyushchauhan/Documents/testcodes/nuxt-component/layouts/default.vue
         <Root>
warn @ vue.runtime.esm.js:430
mountComponent @ vue.runtime.esm.js:2398
Vue$3.$mount @ vue.runtime.esm.js:7105
init @ vue.runtime.esm.js:3354
hydrate @ vue.runtime.esm.js:5228
hydrate @ vue.runtime.esm.js:5244
patch @ vue.runtime.esm.js:5318
Vue._update @ vue.runtime.esm.js:2312
updateComponent @ vue.runtime.esm.js:2435
get @ vue.runtime.esm.js:2774
Watcher @ vue.runtime.esm.js:2757
mountComponent @ vue.runtime.esm.js:2439
Vue$3.$mount @ vue.runtime.esm.js:7105
init @ vue.runtime.esm.js:3354
hydrate @ vue.runtime.esm.js:5228
hydrate @ vue.runtime.esm.js:5244
patch @ vue.runtime.esm.js:5318
Vue._update @ vue.runtime.esm.js:2312
updateComponent @ vue.runtime.esm.js:2435
get @ vue.runtime.esm.js:2774
Watcher @ vue.runtime.esm.js:2757
mountComponent @ vue.runtime.esm.js:2439
Vue$3.$mount @ vue.runtime.esm.js:7105
mountApp @ client.js:369
_callee2$ @ client.js:392
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
vue.runtime.esm.js:430 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Comment by ArnoBuschmann** [comment]
@piyushchauhan2011 Yes, that's exactly where I got the same problem as well and found no solution yet. Maybe anyone else has an idea how to fix this? :)

**Comment by piyushchauhan2011** [comment]
Here is the repo for reference: https://github.com/piyushchauhan2011/nuxt-component/tree/master/cerebral-store

**Comment by alexchopin** [comment]
It seems that this library is not compatible for SSR.

**Comment by VsevolodTrofimov** [comment]
This is a react example
But it suggest that cerebral is compatible with SSR, including rehydration
https://www.jsblog.io/articles/christianalfoni/cerebral_in_depth_ssr
