### ISSUE TITLE
All methods mounted on the prototype have an error!!!

### ISSUE THREAD

**Issue by pseudo-god** [nuxt/nuxt.js#8301]
### Versions

- nuxt:  2.14.7
- node:  12.14.0

### Reproduction
```
//All methods mounted on the prototype have an error.
Vue.prototype.FUNCTION


```

<details open>
<summary>Additional Details</summary>
<br>

[Exception: TypeError: Cannot read property '_route' of undefined at Object.get (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1289:52) at Object.o (<anonymous>:1:83)]

</details>

### What is Expected?
The prototype method can be used normally

**Comment by danielroe** [comment]
@pseudo-god Could you provide a reproduction via https://template.nuxtjs.org/ ?
