### ISSUE TITLE
$router.push doesn't work correctly with two dynamic parameters

### ISSUE THREAD

**Issue by omm2** [nuxt/nuxt.js#8304]
### Versions

- nuxt: v2.14.7
- node: v12.14.0

### Reproduction
Sandbox link:
https://codesandbox.io/s/beautiful-ellis-6l1y5?file=/pages/_lang/order/_id/index.vue

### Steps to reproduce
1. Run a sandbox project
2. Go to the order page (the URL has two dynamic params): https://6l1y5.sse.codesandbox.io/en/order/1111
3. Click the "Success" button
4. The following method is called:
`      this.$router.push({
        name: "lang-order-id-success",
      });`

### What is Expected?
1. To go to Sucess URL with both dynamic params: https://6l1y5.sse.codesandbox.io/en/order/1111/success

### What is actually happening?
1. The actual URL is: https://6l1y5.sse.codesandbox.io/en/order/success -> `id` param in URL is missing

Note: started to get reproduced after the upgrade from "2.12.2" to "2.14.17"

**Comment by danielroe** [comment]
@omm2 Your reproduction doesn't reproduce the issue for me.

![Screen Recording 2020-11-05 at 15 39 12](https://user-images.githubusercontent.com/28706372/98262239-4beb0a80-1f7d-11eb-9ef1-b9e2aa19ca8a.gif)

**Comment by pulsarpoint** [comment]
This issue is reproducible on firefox. In the chrome, routing works fine.

**Comment by danielroe** [comment]
@pulsarpoint I was using Firefox too, when I couldn't reproduce the bug.

**Comment by pulsarpoint** [comment]
@danielroe Sorry, you're right. I just check once again and works fine in ff too.

**Comment by omm2** [comment]
Hello, thank you for your quick reply!

Apparently, the issue is only reproduced with the parameter being optional. I re-wrote the example a little bit, so that `:id` is now `:id?`

Steps to reproduce:
1. Go to sandbox example: https://6l1y5.sse.codesandbox.io/
2. Click the "Payment" page, the URL changes to https://6l1y5.sse.codesandbox.io/en/order/1111/payment
3. Click "Success" button, the URL changes to https://6l1y5.sse.codesandbox.io/en/order/success

Expected: URL to change to https://6l1y5.sse.codesandbox.io/en/order/1111/success

![Example](https://lh3.googleusercontent.com/fife/ABSRlIom8X04eP7Gw-SMe-QMGIAYbPTKDxN_8PkTrKYr_qCDIKZo0_GsU5SZlQxi4rA15yNbBfURMY5TzfNav8VFU7q10k_Hgl3dDuZ1oS67_AelB1shK5giX8MrGt3eOiqJ4_qKCzr5Gd9J48s-q4szi22f13-vYSkYurpOC2Tgmtj1sqPm12GuPFS_wx_X8gTRlANWHay2IeAPJAjcdxKDNv5OrTMxbPprcp2E3C5tGPoiv4XQbPVtdqCybwl04kciZNhpWWatGaJLof-_HDUO5jUDn4LFtJ4xKlOK8R723Uzsb1OUuICxyAOXHr8YlV6sv-NBakWEepHI3xGwHTOrMJ3BhKYuNk1GW2u4zA92tosH-K7nKEQzj51vPl9CyJzMOFeLClab9tZEpEczwfutfuNKvQp5J3FKWrWroGvyF_FRycN_un4W2LRYg4L8TnERSm2FAB8_porHAUPaCZH2AZHNhbrGj3Q1N6kz5i8q9udcDFBPlusf18oPrZJItoY9DzHknhVCteevhffwlblAvE9nKYwK5rpPtjtPzBOgihd_Y9xo0NwP3QezQtKbLWG-D77ZKceSKG6wk6ccDYM0ycSV-LnU8qf9CneHm8S0-tarasl-jL7Ojb8vU7_pRyiDKcrCTtVohrfF31oav4bAf8c3T3TgAFYugeEJgBj9vBo_5DvYvwzCOTvbho9f9zv5v-O8XDoxx_HsRVph5JMJ5PbSD4Jno6EGNg=w3360-h1664-ft)
