### ISSUE TITLE
WatchQuery not working in static deployed site

### ISSUE THREAD

**Issue by dacxjo** [nuxt/nuxt.js#8305]
### Versions

- nuxt:  v2.14.0
- node:  v12.14.0

### Reproduction

I'm using the **watchQuery** attribute, to watch changes on the query params from my web to show the products filtered by a category:

`<n-link to="{path:'/',query:{category: cat.slug }">Category a</n-link>`

Ex: **example.com?category=category-a** , it will filter the products to all from the category a.

And then in my **asyncData** method i have:

    watchQuery: true,

    async asyncData({ $content, store, query }) {

    let products, allProducts;

    allProducts = await $content('productos').fetch()

    if (query.category) {
      products = await $content('productos')
        .where({ category: query.category })
        .fetch()
    } else {
      products = await $content('productos').fetch()
    }

    return {
      products,
     }
    }

With The netlify CLI command "**ntl dev**" **it works**, my products are filtered by the category query parameter, but when the page is deployed to Netlify it **doesn't work** anymore.

**There are no errors in the console.**

Is this the correct behavior or i'm doing something wrong?

**Comment by andreavigani** [comment]
Same problem here. I'm using this with blog pagination.
It works in dev and It was working fine in the previous nuxt version.

**Comment by dacxjo** [comment]
Hi @andreavigani, i have asked to the nuxt team, and they told me that this is expected, because in production static mode nuxt is not using SSR like in dev mode.

For me, a way to fix this issue in my project was to forget about query params, and go to a structure of category page instead, like example.com/category/category-a.

I'm aware that the nuxt team is working on a serverless mode that will allow this kind of stuff in future versions. We'll have to wait, i think.

**Comment by dacxjo** [comment]
I leave this open, to see answers and others approach proposals.

**Comment by aweber1** [comment]
I ran into this issue also and was able to resolve it by removing the usage of `watchQuery` and replacing it with the suggestion buried here:
https://nuxtjs.org/docs/2.x/features/data-fetching#listening-to-query-string-changes

For my use case, the resulting code looked like this:
```
watch: {
  '$route.query'() {
    this.myMethod();
  },
},
methods: {
  myMethod() {
    // do something awesome here
  }
}
```
