### ISSUE TITLE
建议将_NUXT_放入到localStorage中

### ISSUE THREAD

**Issue by aokihu** [nuxt/nuxt.js#8306]
window._NUXT_这个数据暴露出来实在是太危险了，建议可以放入到localStorage中，至少不会直接暴露出来

**Comment by sugoidesune** [comment]
Translation:
window._NUXT_ This data is too dangerous to be exposed. It is recommended to put it in localStorage, at least not directly exposed

**Comment by danielroe** [comment]
Could you explain a little more about your concern?

However, do note that `window.__NUXT__` is passed from the server to the client and therefore is visible in the rendered HTML.

**Comment by aokihu** [comment]
For example, when a visitor is browsing his own user profile page, if sensitive data is not filtered out, it may be directly exposed to the visitor. When a web crawler violently crawls these pages, it may These sensitive data were stolen.
If the developer did not notice the data window._NUXT_, then it is possible to put the data of the entire website into this data field. I made such a mistake when I first contacted NUXT.
At the same time window._NUXT_ data increases the amount of data.
So my suggestion is to put window._NUXT_ into sessionStorage or localStorage, which can load data asynchronously, and it can also play a role in data protection for web crawlers.

**Comment by danielroe** [comment]
@aokihu The data you are referring to needs to be passed to the client side somehow and therefore will be accessible in the HTML to crawlers, no matter what happens subsequently to the data (whether stored on the Window object or in localStorage).

It is your responsibility to ensure that sensitive information isn't returned to non authenticated requests.
