### ISSUE TITLE
子页面中，无法用watch监听到$route的变化

### ISSUE THREAD

**Issue by tjh19971228** [nuxt/nuxt.js#8308]
### Versions

- nuxt: 2.14.7
- node:12.14.1

### Reproduction
在新版的nuxt中，在子页面中无法用watch去监听到$route的变化，但旧版本(2.10.2)中和父页面(default.vue)中可以监听到该变化，

### Steps to reproduce
**子页面中**
watch: {
    "$nuxt.$route"(to, from) {
      console.log(to,from)        //路由变化时，没有执行
      if (to.name == "xxx") {
        //do something
      }
      if (from.name == "xxx") {
        // do something
      }
    }
  },
**跳转的方式**
$nuxt.$router.push(`/xxx`);
**父页面的定义**
<Nuxt keep-alive />
### What is Expected?
希望新版本的子页面中可以通过watch监听到相应的$route变化
### What is actually happening?
新版本中，无法通过watch监听$route的变化

**Comment by sugoidesune** [comment]
**In the subpage, the change of $route cannot be monitored by watch**

Translation:
Versions
nuxt: 2.14.7
node:12.14.1
Reproduction
In the new version of nuxt, watch can not be used to monitor the change of $route in the child page, but the change can be monitored in the old version (2.10.2) and the parent page (default.vue).

Steps to reproduce
In the subpage
watch: {
"$nuxt.$route"(to, from) {
console.log(to,from) //When routing changes,
if (to.name == "xxx") {
//do something
}
if (from.name == "xxx") {
// do something
}
}
},
the way to jump
$nuxt.$router.push( /xxx);
the definition of the parent page
What is Expected?
I hope that the new version of the sub-page can monitor the corresponding $route changes through watch

What is actually happening?
In the new version, the changes of $route cannot be monitored through watch
