### ISSUE TITLE
sass-loader ^10.0.4

### ISSUE THREAD

**Issue by teleyinex** [nuxt/nuxt.js#8312]
### Versions

- nuxt: v2.14.7
- node: v12.5.0

### Reproduction

Install the last version of nuxtjs
Add the sass-loader
Try to build it with this command: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js"

The build fails with the following message:

ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }

### What is Expected?

To build successfully.

### What is actually happening?

Build fails.

## Fix

By downgrading sass-loader to version 8.0.2 it works without problems.

**Comment by danielroe** [comment]
@teleyinex Could you provide a reproduction?

**Comment by danielroe** [comment]
This doesn't reproduce using the steps you've provided. I think it most likely you have a module or dependency installed that depends on an old version of sass-loader, such as (possibly?) [vuetify](https://github.com/nuxt-community/vuetify-module/blob/master/src/sass.ts#L23). @kevinmarrec Have I misread the module?

**Comment by JohnMica** [comment]
it could be that sass-loader has breaking changes in their API ? 
seems like they have changed `prependData` to `additionalData` perhaps ?

**Comment by danielroe** [comment]
Agreed. It sounds like you're using Vuetify so I think this is just an issue there rather than with Nuxt - tell me if that isn't the case I'll reopen.
