### ISSUE TITLE
SSR Encoding Error in Attributes of HTML

### ISSUE THREAD

**Issue by iserejatoje** [nuxt/nuxt.js#8315]
Hi NuxtJS! When installing via create-nuxt-app I am having a problem with the `html` tag:

### NuxtJS v2.14.5.
`<html lang="ru" data-n-head="%7B%22lang%22:%7B%22ssr%22:%22ru%22%7D%7D">`

I see a lot of Nuxt sites that don't have this problem. This bug continues since v2.10.1. (https://github.com/nuxt/nuxt.js/issues/6572)

This probably does not affect the performance of the application (I just started learning Nuxt), but I think it is not working properly.
How can this bug be fixed? Why does he appear, does anyone know?

**Comment by ninie1205** [comment]
HI, I have the same issue:

`<body class="" data-n-head="%7B%22class%22:%7B%22ssr%22:%22%22%7D%7D" cz-shortcut-listen="true">`

My head object is looking like this:

`head: {
      bodyAttrs: {
         class: 'portfolio'
      },
      script: [
         {
            src: 'http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js'
         }
      ]
   },`

**Comment by danielroe** [comment]
@iserejatoje As fat as I can tell, what you are describing isn't a bug - it is an encoded attribute to tell `vue-meta` it doesn't need to rerender on client side. (See [the docs](https://vue-meta.nuxtjs.org/faq/prevent-initial.html#how-to-prevent-update-on-page-load).)

I'm going to close this issue, but If you are indeed experiencing a bug, please feel free to comment again with more details.
