### ISSUE TITLE
Does nuxtServerInit run on every request?

### ISSUE THREAD

**Issue by bratberg** [nuxt/nuxt.js#832]
I'm building an application where I want to fetch a bunch of data from different external sources, but I only want to do this once (when the server is started). I might have misunderstood how `nuxtServerInit` is supposed to work (or I might be doing something wrong), but I have not been able to make it run only once. 

See https://glitch.com/edit/#!/excited-wish for a quick demo of the issue.
(Click on 'logs' to see the console log on the server and 'show' to view the rendered page. Every time you refresh the rendered page, the server is initialized again).

Any pointers?

**Comment by kodekrendel** [comment]
I see only `Nope, server has not been initialized yet`

**Comment by bratberg** [comment]
@kodekrende That´s because I try to set `serverInitialized` in `store/index.js` (just a property in my store state object) when `nuxtServerIniit` is ran - just for debugging purposes :)

**Comment by alexchopin** [comment]
Hi @bratberg, the `nuxtServerInit` action is called everytime you refresh the page.
The action name can be confusing because it doesn't restart the server but it's more like "nuxt store initialization from the server"

**Comment by bratberg** [comment]
@alexchopin Ah, that makes sense! So there is no way of running some code only when the server starts up?

**Comment by pi0** [comment]
@bratberg You may use modules to do some stuff on server start.
