### ISSUE TITLE
Prevent prefetching missing payload.js for paths in generate.exclude

### ISSUE THREAD

**Issue by arildm** [nuxt/nuxt.js#8321]
### Versions

- nuxt: v2.14.7
- node: v10.20.1

### Reproduction

https://codesandbox.io/s/optimistic-leftpad-m98ij (open browser's network log)

<details open>
<summary>Additional Details</summary>

This is all that was changed in the CodeSandbox template:

nuxt.config.js:

```js
  mode: "universal",
  target: "static",
  generate: {
    exclude: ["/about"]
  },
```

package.json:

```js
  "scripts": {
    "dev": "MINIMAL=1 CSB=1 nuxt generate && nuxt start",
```
</details>

### Steps to reproduce

1. Add some route, e.g. `/about`, to `generate.exclude`
2. Generate the site
3. Visit a page that contains a nuxt-link to the excluded route

### What is Expected?

No error message in network log.

### What is actually happening?

A 404 message about `/_nuxt/static/{timestamp}/about/payload.js`

**Comment by ferry77** [comment]
you might want to try below on those targeting excluded pages

<NuxtLink to="/about" :prefetch="false">About page not pre-fetched</NuxtLink>

https://nuxtjs.org/docs/2.x/features/nuxt-components#disable-prefetching-for-specific-links

**Comment by ffx0s** [comment]
+1 have the same problem

**Comment by arildm** [comment]
Thanks @ferry77 for the pointer! The `no-prefetch` prop was a good solution in my case.

I'm leaving the issue open, as I still think it could make sense to automatically skip prefetching routes that are covered by `generate.exclude`.

**Comment by kreba** [comment]
Thank you for your suggestion. We provide payloads for all our pages with the ambition that the statically generated pages never have to ask our API for data, not even when navigating in the hydrated app. We do this by listing all routes (and their various internationalized variants) in `generate.routes`. At the same time we need to `generate.exclude` *everything* so nuxt does not generate duplicated pages that are missing a payload.

So we heavily depend on payload.js for excluded routes. And therefore disabling payload.js across the board for all excluded routes would be bad for us. If such a feature were to be added, it should leave payload.js enabled for all explicitly added routes.

Of course if Nuxt wouldn't generate duplicates of routes that are explicitly defined in `generate.routes`, then we wouldn't have to exclude them, and there would be no conflict with your proposal.
