### ISSUE TITLE
Overwriting nuxt.server.listen() function, prevents accessing its port and host parameters.

### ISSUE THREAD

**Issue by dalexhd** [nuxt/nuxt.js#8322]
### Versions

- nuxt: `v2.14.7`
- node: `v13.14.0`
- npm: `v6.14.4`

### Inspired by one of your GitHub examples guides:
https://github.com/nuxt/nuxt.js/tree/dev/examples/with-sockets

### Reproduction

https://codesandbox.io/s/jolly-cdn-kr76o?file=/io/index.js

<details open>
<summary>Additional Details</summary>
<br>

```javascript
export default {
  /*
   ** Headers of the page
   ** Doc: https://vue-meta.nuxtjs.org/api/#metainfo-properties
   */
  head: {
    title: "Nuxt.js starter for CSB",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        hid: "description",
        name: "description",
        content: "Official Nuxt.js starter for CodeSandBox"
      }
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }]
  },

  /*
   ** Global CSS
   ** Doc: https://nuxtjs.org/api/configuration-css
   */
  css: [],

  /*
   ** Plugins to load before mounting the App
   ** Doc: https://nuxtjs.org/guide/plugins
   */
  plugins: [],

  /*
   ** Nuxt.js modules
   ** Doc: https://nuxtjs.org/guide/modules
   */
  modules: [
    // Doc: https://http.nuxtjs.org
    "@nuxt/http",
    // TODO: Remove it if you want to eject from codeSandbox
    "./codesandbox",
    // Guide from https://github.com/nuxt/nuxt.js/tree/dev/examples/with-sockets
    "~/io"
  ],

  // Server Configuration (https://nuxtjs.org/faq/host-port)
  server: {
    port: 4000,
    host: "localhost"
  },

  /*
   ** HTTP module configuration
   */
  http: {
    // See https://http.nuxtjs.org/api/#options
  },

  /*
   ** Build configuration
   ** Doc: https://nuxtjs.org/api/configuration-build
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {}
  }
};
```
</details>

### Steps to reproduce

1. Change nuxt.config.js server object properties, like: 
```javascript
export default {
//...
  server: {
    port: 4000,
    host: "localhost"
  },
//...
}
```
2. Run `npm start` command.
1. Server starts at `localhost:3000`

### What is Expected?
Server should start at `localhost:4000`

### What is actually happening?
Server starts at `localhost:3000`

**Comment by dalexhd** [comment]
Any updates here?

**Comment by farnabaz** [comment]
The `port` argument of the `listen` function is not what you want. Use `this.nuxt.options.server.port` to get port from `nuxt-config`

```js
server.listen(port || this.nuxt.options.server.port || 3000, host || 'localhost', resolve)
```

**Comment by dalexhd** [comment]
@farnabaz Okay. Does it happen the same with the host variable?

Also, does this really make sense? I mean, why the first port parameter doesn't have the `this.nuxt.options.server.port` optional value?

**Comment by farnabaz** [comment]
>  Does it happen the same with the host variable?

Yes

> Also, does this really make sense?

It does the first argument's goal is to override the port when developers call `server.listen`. This is hos nuxt calculate port and host when you call the original `server.listen`
```js
port: isNaN(parseInt(port)) ? this.options.server.port : port,
host: host || this.options.server.host,
```

**Comment by dalexhd** [comment]
Okay. It does make sanse 👍 

Thanks for support 😄
