### ISSUE TITLE
Pages are created twice when SSR is false and splitChunks layouts is true

### ISSUE THREAD

**Issue by imfaber** [nuxt/nuxt.js#8328]
### Versions

- nuxt: v2.14.5, v2.14.6, v2.14.7
- node: v12.x.x

### Reproduction

The bug can be reproduced at the following codesandbox:
https://codesandbox.io/s/cool-water-vpncu?file=/nuxt.config.js

<details open>
<summary>Additional Details</summary>
<br>

`nuxt.config.js`:

```javascript
export default {
  ssr: false,

  build: {
    splitChunks: {
      layouts: true
    }
  }
};

```
</details>

### Steps to reproduce
1. Configure nuxt as shown in the details above 
2. Log something in the `created` lifecycle hook of any page.
3. Open the console and reload the page

### What is Expected?
The page component is created only once and only one message should be logged in the console.

### What is actually happening?
The page is created twice and 2 logs are printed

### Observations
Not sure if it's of any help but the first time the page is created `this.$nuxt.layoutName` is an empty string.

**Comment by ragnaroks** [comment]
same problem,but i don't know the reason,and you let me know,thanks

**Comment by nakaumin** [comment]
I have same problem, does anyone know how to fix it?
