### ISSUE TITLE
Support using specific dotenv file according to environment

### ISSUE THREAD

**Issue by fralonra** [nuxt/nuxt.js#8331]
### Is your feature request related to a problem? Please describe.

Currently it seems that we can use only one dotenv file (.env, see [load.js](https://github.com/nuxt/nuxt.js/blob/92a06615d01155b2db3abe5ea8629ae03ee3cb2a/packages/config/src/load.js#L41)) in the project. But sometimes we need to have different dotenv in one project and can use them for different environment.

### Describe the solution you'd like

Load dotenv file according to current environment.
eg. `.env.dev` or `.env.development` for *development*, and `.env.prod` or `.env.production` for *production*, and `.env` for default.

**Comment by danielroe** [comment]
@fralonra FYI, with the new runtimeConfig, you can specify the `.env` file to load on the command line: see original documentation at https://github.com/nuxt/nuxtjs.org/blob/61a15846bc4cfebb812f7acba07c54f2959d474d/content/en/_archives/guide/runtime-config.md#env-support

**Comment by nirazul** [comment]
Currently, this doesn't seem to work with Nuxt 3 (rc8)

**Comment by daviddomain** [comment]
> No luck as well. Using nuxt/bridge-edge `nuxi dev --dotenv .env.whatever` does not load the correct environment variables.

**Comment by nidmidhalf** [comment]
@danielroe Any update on this? nuxt.config.ts is always picking the environment variables from .env instead of .env.development inspite of mentioning the --dotenv .env.development in package.json

**Comment by danielroe** [comment]
Feel free to create an issue with a reproduction 🙏

**Comment by rwlaschin** [comment]
That's pretty snarky to ask for a repro when the dev posted the file that is supposed to be reading from the .env and is missing the commands.  

Maybe, just maybe you can try it and see if this works for you and when it doesn't.  Fix it.
