### ISSUE TITLE
Nuxt.js website stops responding after a while

### ISSUE THREAD

**Issue by drtobbyas** [nuxt/nuxt.js#8332]
The https://i18n.nuxtjs.org/ and https://nuxtjs.org/ website stops responding after a while. Clicking on any link or button will change the URL but the content of the page is not updated

### Reproduction

Open https://i18n.nuxtjs.org/ or https://nuxtjs.org/ and navigate to docs page, interact with a few links. Then leave it for some time ( probably like 1 hour) while you work on other things (tabs). When you finally come back to the tab, clicking on the links will not update the content of the page.

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
1. Open https://i18n.nuxtjs.org/ or https://nuxtjs.org/  and navigate to docs page, interact with a few links
2. Then leave it for some time ( probably like 1 hour) while you work on other things (tabs). 
3. Return back the https://nuxtjs.org/ and click on any link to navigate. 

### What is Expected?
Clicking on the link should navigate to the corresponding content/page

### What is actually happening?

The content of the website is not getting updated as the links and button are being clicked
![screencast-nimbus-capture-2020 11 11-12_39_32](https://user-images.githubusercontent.com/40923477/98811649-775c7200-2421-11eb-9526-da95aca2cf6a.gif)

**Comment by danielroe** [comment]
@drtobbyas Thanks for reporting! Could you raise this as an issue [there](https://github.com/nuxt/nuxtjs.org/issues/)?
