### ISSUE TITLE
Enable generated static sites to have dynamic elements

### ISSUE THREAD

**Issue by davydnorris** [nuxt/nuxt.js#8334]
### Is your feature request related to a problem? Please describe.

I have built my company web site with nuxt and nuxt/content and have used static site generation, and it's fantastic. I have it deployed using a static web server and it's very fast and SEO friendly. I use nuxt/content for the blog/news/announcements and it's very simple to just push the new static content.

As with many company web sites, almost the entire site is static and really doesn't change - I might add a blog or news item every few weeks but that's static too, so a static site is appropriate. I have a couple of places where there are moving parts and I have implemented an API with some serverless functions:
 - people can ask questions by filling in a form and I use an API call to send the information back to me
 - people can sign up to a mailing list, and once again I use an API call to send the details into a simple database list

All these are simple and work well, mainly because there's no change to the web page content with these calls. However, the blog is a different story:
 - I have set up Google Analytics to track the number of times the blog content is read
 - I have set up Google Analytics events to track users when they 'star/unstar' blog articles and I use browser local storage to show the user's individual starred articles as well as the total number of stars, as a way of showing top articles
 - I have a commenting system on the blog and store the comment thread in a database

For each of these I have also set up an API with serverless functions, and they work fine when in dev mode or when I use Nuxt in SSR mode, but they don't work when I use static generation, as the generator caches all the data returned from the API calls during generate time, which means my views/likes/comments all show up but are all from when the site was last generated.

### Describe the solution you'd like

I would love the ability to somehow specify that certain parts of the code (like what's been set up in the Vuex store maybe) need to be generated as uncached dynamic data with client side code. This would mean
 - you can still deploy via CDN or a static server
 - the pages are still SEO friendly
 - you can dynamically update the parts that need it

### Describe alternatives you've considered

Right now I am looking at using the Vue lifecycle hooks that remain in the code after generation, such as beforeCreate(), created() etc. and manually creating a simplified Vuex store with API calls in these hooks. While I know this will work, it seems silly when there's already a Vuex store capability there that's being cached out.

**Comment by michaelpumo** [comment]
Have you thought about simply re-generating the static site by sending a webhook to your server?

For example, I have many static sites that also use a CMS. Once the client saves a page in the CMS (Prismic) this fires a webhook to Netlify (where it's hosted) and this triggers the command to rebuild the site.

Whilst the workflow isn't perfect, it means it can have a somewhat dynamic feel by being able to update as and when it needs to.

**Comment by davydnorris** [comment]
I don't use a back end CMS, I use nuxt/content and I do regenerate the site each time I post content. I have it set up to automatically generate on each commit, so I simply write my blog entry in markup and commit it to Git.

But this is not a question of content as such, it's about dynamically displaying page views, likes and comments, and these can and do all change on a daily basis. These elements are best handled with some form of external storage and an API call

**Comment by danielroe** [comment]
@davydnorris Have you tried `fetchOnServer: false` in conjunction with `fetch()`?

**Comment by davydnorris** [comment]
@danielroe fetchOnServer has no effect when doing a full static generate.

The fetch() function is called during the static render phase of the generate process in order to create the HTML - the function doesn't end up in the generated page content.

It's next to impossible to create a codePen reproduction because you're doing a static generate. The simplest way to see the problem is to 
 - create the default nuxt skeleton project
 - add all the Nuxt and Vue lifecycle hook functions to the main page with a console.log call in them
 - do something similar to a Vuex store too if you like
 - do a full static generate

You will see all the console.log statements output in the expected order during static render. If you use fetchOnServer: false, you'll see the expected changes to when the fetch console.log statement prints out, but it still prints out during the static render.

Once you've generated the static site, then use nuxt start to run the sample. You will see that there are no Nuxt lifecycle hooks log entries in your browser console, and no Vuex store log entries, you only get the Vue hooks called. If you want any sort of working script in the generated site, it's got to be called from inside one of the Vue hooks or custom methods.

**Comment by danielroe** [comment]
@davydnorris You can still produce a code repository that reproduces an issue.

In this case, I cannot replicate what you are experiencing. Please see https://github.com/danielroe/fetch-on-server - run `yarn && yarn generate && yarn start`. You will see in the generated HTML that the fetch has not been performed at generate-time, but that when it is loaded in the browser, the fetch is **then** performed.

**Comment by davydnorris** [comment]
@danielroe many thanks for that - I had added fetchOnServer to my nuxt.config.js, not the individual page

I now get the same behaviour as you and I think this will do what I need. I'll close this feature request and have a play

**Comment by lewebsimple** [comment]
I'm experiencing a problem related to this, don't know if I should create a new issue or if I'm missing something so I'm posting here.

I have a generic catch-all `pages/_.vue` for displaying Page / Post / Category components based on the graphql `__typename` in the asyncData request.

Inside the Category component, I have an `async fetch()` for retrieving the list of posts from that category and displaying links to these posts.

When generating the app, the crawler properly generates the posts found on the category page (which is linked from the front page), but when serving this generated app I get the following behaviour:
- When I load the front page and navigate to the category page, the posts are not listed
- When I load the category page directly (or refresh the page once in that category) the posts are listed just fine

Am I missing something or is this normal behaviour?

**Comment by lewebsimple** [comment]
Ok I’ll create an issue when I get a repro working.

the strange thing is the page where the problem occurs gets generated just fine (it gets listed by the generate command)

**Comment by lewebsimple** [comment]
@danielroe see #8990 for reproduction and additional details.

**Comment by B-starboy** [comment]
> I'm experiencing a problem related to this, don't know if I should create a new issue or if I'm missing something so I'm posting here.
> 
> 
> 
> I have a generic catch-all `pages/_.vue` for displaying Page / Post / Category components based on the graphql `__typename` in the asyncData request.
> 
> 
> 
> Inside the Category component, I have an `async fetch()` for retrieving the list of posts from that category and displaying links to these posts.
> 
> 
> 
> When generating the app, the crawler properly generates the posts found on the category page (which is linked from the front page), but when serving this generated app I get the following behaviour:
> 
> - When I load the front page and navigate to the category page, the posts are not listed
> 
> - When I load the category page directly (or refresh the page once in that category) the posts are listed just fine
> 
> 
> 
> Am I missing something or is this normal behaviour?
> 
> 
> 
> edit: There's also an issue with crawling the links if only the catch-all `pages/_.vue` is present without `pages/index.vue` (which can be a copy of the catch-all component).
