### ISSUE TITLE
Import a local module, this module cannot be found in online deployment

### ISSUE THREAD

**Issue by LeachZhou** [nuxt/nuxt.js#8335]
### Versions

- nuxt: v2.0.0
- node: v14.15.0 

There is no problem with local development and debugging, but the module cannot be found after the project is deployed. The introduction of the npm package nuxt-ssr-cache is successful. I download and modify the nuxt-ssr-cache and there will be problems，please help!

![image](https://user-images.githubusercontent.com/18715564/98901421-ba384b80-24ee-11eb-8a20-7b36ab862a67.png)

![image](https://user-images.githubusercontent.com/18715564/98901288-852bf900-24ee-11eb-83b8-d03ec2591b03.png)

**Comment by danielroe** [comment]
@LeachZhou Could you provide a reproduction? (Just based on those screenshots, it looks like you are declaring a plugin at the location `~/plugins/nuxt-ssr-cache/middleware` yet the file is `~/modules/nuxt-ssr-cache/middleware` - but in that case I would not expect it to work in development either.)

**Comment by LeachZhou** [comment]
> @LeachZhou Could you provide a reproduction? (Just based on those screenshots, it looks like you are declaring a plugin at the location `~/plugins/nuxt-ssr-cache/middleware` yet the file is `~/modules/nuxt-ssr-cache/middleware` - but in that case I would not expect it to work in development either.)
Thank you for taking the time to reply to me, originally put the module in the plugins folder, but later I thought that the module must be placed in the modules folder, so I modified the location, reproduction is not easy to extract, can you guess what the problem is?

**Comment by danielroe** [comment]
@LeachZhou I'm more than happy to look if you provide a reproduction. 😊
