### ISSUE TITLE
Nuxt and Nuxt-i18n modules give unexpected SEO performance

### ISSUE THREAD

**Issue by Matthieurpe** [nuxt/nuxt.js#8336]
Hello everyone,

I have an issue with Nuxt, Nuxt-i18n and SEO performances.

I'm creating a portfolio website in static mode (only client), generated and then pushed on Netlify.

I'm trying to improve my SEO performance with guides and tutorials but it doesn't change anything.

The problem is about headers and metadata that are not recognized but meta title are rendered on the deployed netlify website.

I followed the nuxt-i18n module tutorial for SEO
https://i18n.nuxtjs.org/seo/

I set the detectBrowserLanguage to false for nuxt-i18n according to this issue
https://stackoverflow.com/questions/63359724/nuxt-and-i18n-google-showing-mixed-language-results

And all my pages have h1 tags (see configurations section for screenshots).

It's been some days that i try to improve everything but i'm out of ideas and solutions now.

Here's the website if necessary:
https://coded-coffee.com
(for french version: https://coded-coffee.fr)

Thanks in advance for your help ! 👍

Matthieu

### Versions

- nuxt: ^2.14.6
- node: 12.16.2
- nuxt-i18n: ^6.15.1

### What is Expected?

I expect SEO crawlers and robots to find h1 headers and meta data like title and descriptions

### What is actually happening?

SEO crawlers do not find any of h1 tags or meta data 

https://freetools.seobility.net/en/seocheck/coded-coffee.fr

![image](https://user-images.githubusercontent.com/74357505/98937577-df28c080-24e6-11eb-83d4-2c1d3f3632db.png)

### Configurations

nuxt.config.js
![image](https://user-images.githubusercontent.com/74357505/98938189-d1c00600-24e7-11eb-92a5-b9836acf7a01.png)

nuxt-i18n configuration
![image](https://user-images.githubusercontent.com/74357505/98938240-e3091280-24e7-11eb-97bc-cb4ee65634a1.png)

default layout head
![image](https://user-images.githubusercontent.com/74357505/98938309-f5834c00-24e7-11eb-9b99-15430940dd40.png)

page example head
![image](https://user-images.githubusercontent.com/74357505/98939018-14cea900-24e9-11eb-8479-ccdeaa7e87af.png)

H1 example
![image](https://user-images.githubusercontent.com/74357505/98939239-66773380-24e9-11eb-91e4-c8db33c93e47.png)

**Comment by manniL** [comment]
You have to deploy with `ssr: true`. At the moment, your page is a classic SPA and no data is in the actual content coming from Netlify.

**Comment by Matthieurpe** [comment]
But i'm creating a static website that doesn't need a server side and dynamic rendering. So do i really need to put `ssr: true` or can i activate SEO as static nuxt app ?

**Comment by danielroe** [comment]
@mathieutu Yes, you do. That means the server rendering you want for SEO will happen - although it will be at build time given that you have a static generated app.

**Comment by mathieutu** [comment]
Sorry @danielroe but I'm not the good Mat(t)hieu here! 😅 

Ping @Matthieurpe.

**Comment by danielroe** [comment]
Apologies! 🤦‍♂️

**Comment by Matthieurpe** [comment]
Hey guys, thanks for your answers ! I set the ssr mode to true but i've got some rendering error
"The client-side rendered virtual DOM tree is not matching server-rendered content." that i have to fix haha.

I do not understand why i need to render my app with ssr as it is a static website that doesnt need a server to work ... can someone please explain me ? ^^'

**Comment by davydnorris** [comment]
It's one of the little quirks of nuxt. Basically when you choose to generate a static site, it actually builds the dynamic one, and then it serves up your site and crawls every page, running any ssr and API calls etc. and caches the pages and payloads as static files.

So you have to set up your site as if you were going to run it dynamically, and then let the generate command crawl and cache the pages

**Comment by Matthieurpe** [comment]
@davydnorris Thank you for the explanation. So I do not understand one thing, in which scenario do you build your website in `ssr: false` mode if to generate a static website, you need to let ssr mode to true and let the generate command crawl and cache the pages ?

**Comment by danielroe** [comment]
@Matthieurpe Yes, you will (almost) never want to set `{ ssr: false }` to build a static website. The error you're getting is a hydration issue and is because your server and client state don't match. See https://blog.lichter.io/posts/vue-hydration-error/ and https://html-validator.nuxtjs.org/ - which may help - and feel free to pop into the Nuxt Discord if you have any questions...
