### ISSUE TITLE
Selectors should not contain IDs because these rules are too tightly coupled with the HTML.

### ISSUE THREAD

**Issue by mattiapontonio** [nuxt/nuxt.js#8339]
```
<element id="nuxt-loading">
Selector Specificity: (1, 0, 0)

Selectors should not contain IDs because these rules are too tightly coupled with the HTML.css(idSelector)
```
# Versions

- nuxt: ^2.14.7
- node: v12.19.0

### Reproduction
- `nuxt generate`
- open `dist/index.html` 

### What is Expected?
No warning in VS code

### What is actually happening?
No warning in VS code

**Comment by mattiapontonio** [comment]
Not really a problem but creates the red warning when opened...

**Comment by danielroe** [comment]
@mattiapontonio In general that is good advice, but in this case you may just ignore your IDE's warning.
