### ISSUE TITLE
Timeout and killed process when running `nuxt build` on node 8 / npm 5

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#834]
Hopefully you'll be able to reproduce, seems to only work 1/10 of the time, every other time the process is killed.

**Comment by pi0** [comment]
@jaredreich We have recently added node 8 to build matrix and no notable timeouts are observed so far. Would you please check your system available resources? (free mem / hdd) Also are you using latest `1.x` releases?

**Comment by piyushchauhan2011** [comment]
I upgraded my project to `alpha3` and have node 8.0.x and npm 5.0.x working perfectly. Shouldn't be a problem I suppose

**Comment by jaredreich** [comment]
Thanks very much for confirming, I haven't been using 1.x releases but will try. Closing for now.

**Comment by github1586** [comment]
@jaredreich Has the problem been solved? I've had the same problem. What caused it?

**Comment by jaredreich** [comment]
The issue was on my end, unrelated to Nuxt

**Comment by jaredreich** [comment]
The issue was my linux server's memory maxed out while building, causing it to stop. It was fixed by adding swap swage (2GB) to my server.
