### ISSUE TITLE
 Cannot find module 'vue' from '/vagrant' 

### ISSUE THREAD

**Issue by zznull** [nuxt/nuxt.js#8340]
### Versions

- nuxt: 2.14.7
- node: v14.15.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Create a new nuxt app using:
`create-nuxt-app app1`

`npm run dev`

Nuxt loads with the default index page

`npm --save-dev install sass sass-loader fibers`

`npm run dev`

`npm --save-dev remove sass sass-loader fibers`

`npm run dev`

### What is Expected?
Defaultl index page to be shown

### What is actually happening?
An error message appears:

`Cannot find module 'vue' from '/vagrant' `

**Comment by danielroe** [comment]
@zznull have you tried deleting your `package-lock.json` and regenerating it? This doesn't look like a Nuxt error.

**Comment by zznull** [comment]
@danielroe yes, I have done that. Also deleting the node_modules directory and reinstalling. It's weird that it works fine at first, but after I install something (and even remove it later) it starts showing this error.

If it's not a Nuxt error, where should I post the bug report, because it doesn't seem to be dependent on what modules I'm installng.

**Comment by danielroe** [comment]
@zznull Perhaps you could provide a code reproduction? That is often very helpful in identifying where the issue lies.

**Comment by zznull** [comment]
@danielroe sure, here it is: https://github.com/zznull/nuxt-module-bug

**Comment by danielroe** [comment]
@zznull Yep - that replicates the issue! My current theory is that it's an issue with specifying `chokidar` separately (it's included with Nuxt so you don't need to do so). You can try removing it from `package.json`, deleting `node_modules` and reinstalling - which worked for me. Or you could try using `yarn` instead - which also worked - and tends to prevent this kind of annoying hard-to-replicate error.

**NB:** Note that the issue is with how `npm` is installing package dependencies - not with Nuxt. If you fire up an interactive terminal, this is what you'd get:
```bash
❯ node
Welcome to Node.js v14.15.0.
Type ".help" for more information.

> const v = require('vue')
Uncaught Error: Cannot find module 'vue'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND',  requireStack: [ '<repl>' ]}
```

**Comment by zznull** [comment]
@danielroe thanks for helping out :)

**Comment by danielroe** [comment]
@zznull No problem - and feel free to pop into the Nuxt Discord if you have any troubleshooting questions 😊

**Comment by zznull** [comment]
@danielroe I tried installing sass packages and the same bug showed up. See updated example: https://github.com/zznull/nuxt-module-bug
