### ISSUE TITLE
nuxtServerInit calling twice

### ISSUE THREAD

**Issue by Komar12124** [nuxt/nuxt.js#8341]
I know that this issue is well known. But in road map i dont see in which step resolving this problem.

### Versions

- nuxt: v2.14.0
- node: v14.12.0

### Steps to reproduce

Open chrome dev tools and refresh a page

### What is Expected?

nuxtServerInit will be called twice

**Comment by Justin1128** [comment]
Hi，
Is the problem solved?

**Comment by danielroe** [comment]
Could you provide a code reproduction?

**Comment by Komar12124** [comment]
@danielpost

Just create **store/index.js** and put any code to **nuxtServerInit**

```
export const actions = {
    async nuxtServerInit ({ dispatch }, { res }) {
        await this.$axios.get('test/any/request');
    },
}
```

**Comment by Komar12124** [comment]
@danielroe Maybe my bad, maybe bad explanation.

This issue happens while creating on local machine with vue devtools and opened chrome dev tools.
While dev mode `npm run dev`, in production mode everything works fine.
