### ISSUE TITLE
Invalid regular expression in ExtendRoutes

### ISSUE THREAD

**Issue by Sletheren** [nuxt/nuxt.js#8342]
Hello guys,
Playing around with Nuxt and tried to implement a specific business need that requires an infinite dynamic levels nesting and seems that Nuxt can't allow this,

The need is accepting this format of URL `/smtng/smtng2/abc-def-TAG-123abc-NUM-12345`
I added this regex: `/:level*/(^[a-z0-9]+(?:-[a-z0-9]+)*TAG-([a-z0-9]+)-NUM-(\\d+)`  hoping it can catch this url structure and then serving the appropriate page, something like this:

> router: {
>     extendRoutes(routes, resolve) {
>       routes.push({
>         name: 'post',
>         path: '/:level*/(^[a-z0-9]+(?:-[a-z0-9]+)*TAG-([a-z0-9]+)-NUM-(\\d+)',
>         component: resolve(__dirname, 'pages/posts/_post.vue')
>       })
>     }
>   },

But I get an error:
`
Invalid regular expression: /^(?:\/((?:[^\/]+?)(?:\/(?:[^\/]+?))*))?\/\[a-z0-9\]\+(?:((?:?\:-[a-z0-9]+)(?:(?:?\:-[a-z0-9]+))*))?(?:\/(?=$))?$/: Nothing to repeat
`

I checked the library `path-to-regexp` as well, but nothing seems to fix it,
Am I doing something wrong?
Thanks

### Versions

- nuxt: "^2.14.6"
- node: "v12.14.0"

**Comment by danielroe** [comment]
@Sletheren is there a need to be so specific with your regexp? I would seriously consider replacing that with just a catchall route (`{ path: '*' }`).

But as far as your error, it looks like you have missed a closing parenthesis.
