### ISSUE TITLE
Dynamically define components in a single file component

### ISSUE THREAD

**Issue by ArunSivagnanam** [nuxt/nuxt.js#835]
This is just some quick test code to illustrate my point

  let components = {};

`fetch({ store, route, error }) {

      return Promise.all([
        store.dispatch('page/fetchPage', route.path),
        store.dispatch('products/fetchInitialProducts'),
      ]).catch(() => error({ statusCode: 404, message: 'Page not found' }))
        .then(() => {
          System.import('~components/ProductSlider').then((comp) => {
            components['product-slider'] = comp;
          });
        });
    },
    beforeCreate() {
      console.log(components);
      this.$options.components = components;
    },`
I have a map, where i like to store my asynch loaded modules.

In my template i have this 
  `<component v-for="(item, index) in getPage(path).modules" :is="item.name" :index="index" key="index"></component>`

But the problem is i right now have a static import of all posible modules that can end up in my dynamic component. This will end up as a huge bundle. I want to dynamically import the component modules defined for a page that we get from our cms system. Can this be done somehow?

i get this error: 
Error: render function or template not defined in component: product-slider
    at normalizeRender (/home/arun/vscodeProjects/flowr/node_modules/vue-server-renderer/build.js:6631:13)
    at renderComponent (/home/arun/vscodeProjects/flowr/node_modules/vue-server-renderer/build.js:6697:3)
    at RenderContext.renderNode (/home/arun/vscodeProjects/flowr/node_modules/vue-server-renderer/build.js:6681:7)
    at RenderContext.next (/home/arun/vscodeProjects/flowr/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/home/arun/vscodeProjects/flowr/node_modules/vue-server-renderer/build.js:30:9)

**Comment by piyushchauhan2011** [comment]
I wonder how this patter works with general `vue-webpack` template @ArunSivagnanam . Have you tried the above with the SPA Vuejs app ?

**Comment by ArunSivagnanam** [comment]
Thanks for youre reply. I have not tried this with the normal vue.js SPA setup. Maybe i should try that. But we cant take that path. We need a server side rendered page, that is hooked up with a headless cms.

Right now i use a general _.vue page component that cathes all routes, and uses the route path to grap a page and module defenitions from the cms. It all works ok, but just the import part that dossent seam to work. I will do some more experiments and write when i find out more. I think its becouse the vue-loader is not triggered when loading productslider single file component.

**Comment by ArunSivagnanam** [comment]
i found the error i think. I can use require syntax to dynamically load a vue singlefile component.
fx 
components: {
      ProductSlider: require('~components/ProductSlider/ProductSlider.vue'),
      OccasionSlider,
    },
works fine. But when i do   ProductSlider: require('~components/ProductSlider'),
i get an error. the folder ProductSlider contains a index.js file with the following lines

import ProductSlider from './ProductSlider';
export default ProductSlider;
I seems like i need to do some configuration on the vue loading part. Can anyone point me in a direction? 

Thanks Arun

**Comment by uptownhr** [comment]
shouldn't `import ProductSlider from './ProductSlider';` be `import ProductSlider from './ProductSlider.vue'`?

**Comment by ArunSivagnanam** [comment]
Hi, thanks. i tried that as well, also require.enusure with require.context. But found the problem to be in my setup. I dont think what i want is posible. 

 i tried to move to another strategy.

**components middleware**
export default function (context) {
  let map = {};
  let components = { ProductSlider, OccasionSlider, ProductPage };
  return context.store.dispatch('page/fetchPage', context.route.path).then((modules) => {
    modules.forEach((m) => {
      map[m.fileName] = components[m.fileName];
    });
    context.modules = map;
  });
}

**and my _.vue file that catches all routes**
<template>
  <div v-if="getPage(path)">
    <component v-for="(item, index) in getPage(path).modules" :is="item.name" :index="index" key="index"></component>
  </div>
</template>
<script>
  /* eslint-disable */
  import { mapGetters } from 'vuex';
  import ProductSlider from '~components/ProductSlider';
  import OccasionSlider from '~components/OccasionSlider';
  import ProductPage from '~components/ProductPage';

  let tempModules;

  export default {
    name: 'home-page',
    computed: {
      ...mapGetters({
        getPage: 'page/getPage',
      }),
      path() {
        return this.$route.path;
      },
    },
    fetch({ store, route, error, components, modules }) {
      this.components = modules;
      store.state.m = modules;
      return Promise.all([
        store.dispatch('products/fetchInitialProducts'),
      ]).catch(() => error({ statusCode: 404, message: 'Page not found' }));
    },
    beforeCreate() {
      this.$options.components = this.$store.state.m;
    },
  };

this setup works serverside. But the client cant render the components in the browser. get an hydration error.
It could be nice to have a new feature where it was posible to supercharge og dynamically define components in a page module

**Comment by alexchopin** [comment]
This feature will be available in the next release.
It's called dynamic component injection.
