### ISSUE TITLE
Nuxt static (generate) does not show image using v-img

### ISSUE THREAD

**Issue by timothymarois** [nuxt/nuxt.js#8356]
So ran a test today on my recent build, and using npm run dev to view locally is working just fine, of course that uses server in the preview, but when I run a build or generate static html files, the images in static are moved over to the dist directory just fine (and I can access them in the public location) however, nuxt decides to not include the image.

I am using VuetifyJS and that is working just fine with images, but nuxt for some reason isnt processing this right on the static html build.

No other plugins are being used or installed aside from a very bare-bones setup. 

```
<v-img
      src="images/myimage.png"
      contain
       height="70" 
       width="120"
/>
```

I have also tried other path variations. 

`./images/myimage.png` and `/images/myimage.png`

No luck with any of these. 

I have however, tried to load the image using html <img src=""> and that seemed to work, so its obviously something to do with loading through v-img where nuxt is not processing the image correctly, the image div does load on page, but it does not include the image in the "background" css. Again, this is only when using static html, SPA and rendering local dev works just fine. 

Also, I am using <v-img> on other elements with linking to images off site (working perfectly), so it is clearly related to static images 

If I can find the time to create a reproduction URL I will, but as of right now wanted to get this out there in case anyone else is noting this issue.

**Comment by timothymarois** [comment]
So between a few other projects which have worked just fine in static mode, I looked at the build and the previous project says `Target: full static` while this one says `Target: static` (during builds), Though they have the same nuxt configurations. Could be nothing, but I find this odd. The current project when building does say `Generating pages with full static mode ` so that seems correct.

**Comment by timothymarois** [comment]
The current project says 
```
ℹ Full static generation activated          
ℹ Generating output directory: dist/     
ℹ Generating pages with full static mode  
```

While the previous project only saying: 
```
ℹ Generating output directory: dist/     
ℹ Generating pages with full static mode
```

Again, this part could be nothing, I just find it odd they are slightly different but use the same configurations

**Comment by timothymarois** [comment]
Still trying to trace down the roots of this, I am able to get the image to work sometimes, looks related to loading the page via SPA style pages, but the moment I do a hard reboot it disappears and I do see a node/nuxt error which seems to be related to the issue at hand. `DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`

**Comment by davydnorris** [comment]
I use static generation too, but have always used `:img="require('@/assets/Common/OGIT_B1.svg')"` whenever I load images. Never had a problem.

Using require explicitly triggers webpack and the build to rewrite the path

**Comment by henon** [comment]
@danielroe thanks, you saved me from pulling my hair!
