### ISSUE TITLE
Cannot access nuxt plugin and `$nuxt` in new Vue() instance

### ISSUE THREAD

**Issue by erraX** [nuxt/nuxt.js#8359]
### Versions

- nuxt:  v2.14.7
- node: v10.21.0

### Reproduction
https://codesandbox.io/s/loving-forest-mynl6?file=/pages/index.vue

### Steps to reproduce
```javascaript
import Vue from "vue";
export default {
  created() {
    console.log("root $nuxt", this.$nuxt);
    console.log("root $foo", this.$foo);
  },

  methods: {
    handleClick() {
      const vm = new Vue({
        created() {
            console.log("new Vue instance $nuxt", this.$nuxt);
            console.log("new Vue instance $foo", this.$foo);
        },
      });
    },
  },
};
```
**Logging `$nuxt` and `$foo`(custom plugin) when App created.**
```javascript
console.log("root $nuxt", this.$nuxt);  // {...}
console.log("root $foo", this.$foo); // 'foo'
```
Click `create vue instance` button

**Not logging `$nuxt` and `$foo` (custom plugin) in new Vue instance.**
```javascript
console.log("root $nuxt", this.$nuxt);  // undefined
console.log("root $foo", this.$foo); // undefined
```
![image](https://user-images.githubusercontent.com/10571798/99354327-382a9700-28e1-11eb-942e-659f60ec7357.png)
all nuxt plugins are undefined.

### What is Expected?
$root and arbitrary vue instance can access $nuxt and plugins

**Comment by danielroe** [comment]
Likely a consequence of https://github.com/nuxt/nuxt.js/pull/8170

**Comment by erraX** [comment]
> Likely a consequence of #8170. You can add these properties to the Vue prototype yourself if you are comfortable with the implications.

thanks for the reply.

There are still some problems：
1. could set custom property to Vue.prototype, but `$nuxt, $route, $router...`
2. couldn't redefine Vue.prototype property because when calling `inject`, `inject` already define a non-configurable property.

eg.
**in inject function:**
```javascript
  function inject(key, value) {
    // ...

    // Call Vue.use() to install the plugin into vm
    Vue.use(() => {
      if (!Object.prototype.hasOwnProperty.call(Vue.prototype, key)) {
      // non-configurable  `$api`
      Object.defineProperty(Vue.prototype, key, {
          get () {
            return this.$root.$options[key]
          }
        })
      }
    })
  }
```
** in custom nuxt plugin **
```javascript
export default function (context, inject) {
  context.$api = $api;
  inject('api', $api);
  // cannot redefine `$api`
  Object.defineProperty(Vue.prototype, '$api', {
    get () {
      return $api;
    }
  });

  // workaround: define another key
  Object.defineProperty(Vue.prototype, '$api2', {
    get () {
      return $api;
    }
  });
}
```

**Comment by PayelKarmakar06** [comment]
@erraX how did you solve this issue?

**Comment by PayelKarmakar06** [comment]
@danielroe so how to resolve it, instead of just going for the workaround?

**Comment by danielroe** [comment]
@PayelKarmakar06 Without seeing a reproduction from you it's difficult to advise.

**Comment by erraX** [comment]
> @erraX how did you solve this issue?
I polyfill related properties to new `Vue` instance.

eg.
```javascript
const vm = new Vue();

// parentVm has all $options

// polyfill `$axios`, `$nuxt`, ...
vm.$root = parentVm.$root;

// polyfill vue-router
vm._routerRoot = parentVm._routerRoot;
vm._router = parentVm._router;

// polyfill vuex
vm.$store = parentVm.$store;
```

**Comment by PayelKarmakar06** [comment]
@danielroe I am not sure if this is the exact repro env - [](https://codesandbox.io/s/focused-lewin-ri9yh?file=/src/pages/index.vue)
