### ISSUE TITLE
fetchOnServer true on deploy not working

### ISSUE THREAD

**Issue by soroka41** [nuxt/nuxt.js#8361]
async fetch() {
    if(this.$store.getters['products/GET_PRODUCT_POPULAR'].length === 0) {
      await this.$store.dispatch('products/ACT_PRODUCT_POPULAR')
    }
  },
  fetchOnServer: false,

When fetchOnServer = true && ssr: true app nuxt not dounload 504 Gateway Time-out

When fetchOnServer = false && ssr: true it is good

When fetchOnServer = true && ssr: false --- good

**Comment by danielroe** [comment]
@soroka41 Would you provide a code reproduction? It looks to me like the HTTP call you are making is not possible from the server but works from the client - likely an issue with your API rather than Nuxt.
