### ISSUE TITLE
support $XDG_CONFIG_HOME for `.nuxtrc`

### ISSUE THREAD

**Issue by Siilwyn** [nuxt/nuxt.js#8364]
It would be great if Nuxt.js follows the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Instead of placing the file `.nuxtrc` in the home directory it should be placed in the OS specific appropriate directory. Getting the correct directory is easy with a module like [env-paths](https://github.com/sindresorhus/env-paths).

This, among other things, allows a user to specify a directory in which they want all applications to look for their user configurable setting files and keep their home directory clean. Though I'm not sure if this is really a config file, the telemetry seed is not something to expect in a dotfile... Perhaps it's appropriate in the cache directory.

### What is Expected?
The `.nuxtrc` file is saved in the appropriate OS directory.

### What is actually happening?
The `.nuxtrc` file is saved in home.

**Comment by pi0** [comment]
Hi @Siilwyn. You can track issue here: https://github.com/nuxt-contrib/rc9/issues/1 (Also PR welcome)

**Comment by pi0** [comment]
Hi. support added in [1.2.0](https://github.com/nuxt-contrib/rc9/blob/master/CHANGELOG.md#120-2020-11-25) you may use `npm up rc9` or `yarn upgrade rc9` to quickly get latest version .

**Comment by winston0410** [comment]
`nuxt` is still generating this file in my `$HOME`. any update on this?
