### ISSUE TITLE
error when I go up with pm2 start axios code 502

### ISSUE THREAD

**Issue by vitorhugosg** [nuxt/nuxt.js#8367]
### Is your feature request related to a problem? Please describe.

I just uploaded my application with pm2, I tested everything right API is working normally on the server, however when I give "pm2 start" file the axios returns me an error.

Follow:

![image](https://user-images.githubusercontent.com/17458174/99571486-22d16d80-29b2-11eb-8e37-686d42acf8da.png)

has anyone got a similar error?

![image](https://user-images.githubusercontent.com/17458174/99571641-53190c00-29b2-11eb-9b44-a3944edf5438.png)

### Describe the solution you'd like

I would like to debug because here in development I'm putting the same URL as the API and even so it doesn't work :(

**Comment by danielroe** [comment]
@vitorhugosg Would you provide a reproduction?

**Comment by vitorhugosg** [comment]
I downloaded a repository called gegocart


In dev reproduction:
![image](https://user-images.githubusercontent.com/17458174/99575831-ee60b000-29b7-11eb-843c-8601a2ea1871.png)

I deployed an API, put it to run on dev on my computer it worked perfectly, now when I went up, it gave this problem :(

I tried to start with pm2 run dev to be able to debug the problem anyway without success.

I don't understand what's going on, because the API route is the same:

Here is an example of API

https://hmg-ventosulmkt.levantelab.com.br/api/products

In dev

![image](https://user-images.githubusercontent.com/17458174/99576209-72b33300-29b8-11eb-8051-127c8a3bd703.png)
