### ISSUE TITLE
When there is a lot of traffic to the Nuxt. js server, the whole site is very slow to visit

### ISSUE THREAD

**Issue by 948911908** [nuxt/nuxt.js#8370]
The speed of our website is ok when the traffic is small, but when the traffic is large, the overall speed will be very, very slow，Usually a file loads for 30 or more
### Versions

- nuxt: 2.14.0
- node: 14.15.0

### What is Expected?
Not so slow

**Comment by 948911908** [comment]
All indexes of the server are normal

**Comment by danielroe** [comment]
@948911908 Can you provide any more info? For example, how do you deploy your site? Are you running the Nuxt built-in server? Is it behind an nginx reverse proxy? Are you setting cache headers? (Is your content cacheable?) Are you performing requests to an external API on your server?

**Comment by 948911908** [comment]
@danielroe Thank you very much for your answer, this project is only running on the server using PM2. The address is m.xhj.com

**Comment by aungzanbaw** [comment]
If you're using pm2 then utilize all of your cpu by 
`pm2 reload all -i max`
after that you might want to restart your nginx too.

**Comment by danielroe** [comment]
@948911908 Looking at your payload, I think you might be performing requests to an external API on SSR, which might increase server response. Apart from that, without more information I think it's likely to be a combination of server configuration and doing too much per-request on SSR. You can mitigate the latter issue with caching, both within Nuxt using component cache and also at the server level (implemented with nginx reverse proxy, for example).
