### ISSUE TITLE
asyncData rename

### ISSUE THREAD

**Issue by ilijanovic** [nuxt/nuxt.js#8371]
In my opinion the name `asyncData` is confusing especially for beginners. They think about `async / await` if they read it but it has nothing to do with it.

I would rather call it `prePopulate()` or `preFetch()` it sounds more understandable what it does.

**Comment by danielroe** [comment]
@ilijanovic Thanks for the thoughtful feedback. You can find out more about what is planned for data fetching in Nuxt 3 at http://nuxtjs.slides.com/atinux/state-of-nuxt-2020 - which I think addresses your concerns with the name.

For Nuxt 2, however, we won't be changing the name as it would be a breaking change.
