### ISSUE TITLE
nuxtServerInit class-transformer reflection issue?

### ISSUE THREAD

**Issue by Jake13f** [nuxt/nuxt.js#8372]
### Versions

- nuxt: v2.14.7
- node: v14.15.1
- class-validator: v0.12.2
- class-transformer: v0.3.1
- class-transformer-validator: v0.9.1
- vuex-module-decorators: v1.0.1 (Not sure if this matters)
- reflect-metadata: v0.1.13

### Reproduction

```ts
@MutationAction({ root: true, mutate: ["user"] })
private async nuxtServerInit({ req }: any) {
    const user = (req as any).user;

    return Promise.resolve({
        user: user
            ? await transformAndValidate(UserModel, JSON.parse(JSON.stringify(user)), {
                    validator: { skipMissingProperties: false, whitelist: true, forbidUnknownValues: true },
                })
            : null,
    });
}
```

### Steps to reproduce

1. Create a plugin for reflect-metadata & add it to the `nuxt.config.js`

```ts
import "reflect-metadata";
```

2. In the `UserModel` class make use of `class-transformer` by converting a type.

```ts
export class UserModel {
  @IsNumber()
  @Type(() => Number) // This is the important part.
  id: number;
}
```

3. In the Vuex store, create a `nuxtServerInit` function and transform and validate. You can do this with or without `vuex-module-decorators`.

```ts
export const actions = {
  async nuxtServerInit() {
    const user = await transformAndValidate(
      UserModel,
      { id: "1" },
      {
        validator: {
          skipMissingProperties: false,
          whitelist: true,
          forbidUnknownValues: true,
        },
      }
    );

    console.log("User:", user);
    console.log("Id type:", typeof user.id);
  },
};
```

4. Add the following to the top of the `nuxt.config.js` or a `serverMiddleware` to load `reflect-metadata` on the server. (It seems as though the plugin importing it isn't sufficient for the server side of things even though its not marked as client-only.)

```ts
import "reflect-metadata";

// ... rest of nuxt config below.
```

### What is Expected?

- The user variable to be set in the `nuxtServerInit()` function.
- The console log to print in the server logs since we are in the serverInit the user object.
- The type of the `id` property to be `Number` since we performed a `@Type(() => Number)` transformation on it.

### What is actually happening?

- After step `3.` you will see the following
  ![Screenshot from 2020-11-18 16-46-43](https://user-images.githubusercontent.com/14061733/99592322-1226f480-29be-11eb-92fd-0a41c7c697c2.png)

- After step `4.` you will see an error in both the server logs and the browser logs...

#### SERVER
> Note: notice that the `id` field hasn't been transformed to a `number` and is still quoted as a `string`.  Something really weird is going on here with reflection or something because this works outside of the `nuxtServerInit` or even if you `transformAndValidate` in the `serverMiddleware`.
```
ERROR  Could not perform action nuxtServerInit

ERROR  [
  ValidationError {
    target: UserModel {
      id: '1'
    },
    value: '1',
    property: 'id',
    children: [],
    constraints: {
      isNumber: 'id must be a number conforming to the specified constraints'
    }
  }
]
```
#### CLIENT
```
Uncaught TypeError: $context is null
    showFrameContext http://localhost/v3/:788
    <anonymous> http://localhost/v3/:826
    ready https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    ready https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    init https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    r https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    <anonymous> http://localhost/v3/:765
v3:788:11
    showFrameContext http://localhost/v3/:788
    <anonymous> http://localhost/v3/:826
    ready https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    (Async: EventListener.handleEvent)
    ready https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    init https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    r https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js:2
    <anonymous> http://localhost/v3/:765
```

**Comment by danielroe** [comment]
@Jake13f I'm closing this but if you can produce a reproduction using https://template.nuxtjs.org I'll happily take a look.
