### ISSUE TITLE
$router.push doesn't return a Promise

### ISSUE THREAD

**Issue by winktim** [nuxt/nuxt.js#8374]
### Version

    nuxt: v2.14.7
    node: v14.15.1

### Reproduction link

[https://codesandbox.io/s/vigilant-booth-27tv8?file=/pages/index.vue](https://codesandbox.io/s/vigilant-booth-27tv8?file=/pages/index.vue)

### Steps to reproduce

    Run a sandbox project
    Call this.$router.push("/about"); in the component
    Watch the returned value

### What is expected ?

push should return a Promise if it is not given an onComplete and onAbort parameter and Promises are supported.

From https://router.vuejs.org/guide/essentials/navigation.html

> In 3.1.0+, you can omit the 2nd and 3rd parameter and router.push/router.replace will return a promise instead if Promises are supported.

### What is actually happening?

push is returning undefined.

### Additional comments?

Here is the incriminated line that for some reason replaces the push function and uses a default parameter for onComplete, which prevents the original function from ever returning a Promise.

https://github.com/nuxt/nuxt.js/blob/e8aca9eb117851047e82e94948ff8b4bcb464b1a/packages/vue-app/template/router.js#L89

New Here. I first tried posting the bug through cmty, but there isn't a way to select core Nuxt.JS there. So I am also posting it here.
Link on Nuxt Community in case: https://cmty.app/nuxt/router-module/issues/c67

**Comment by danielroe** [comment]
@winktim - Much appreciated. See https://github.com/nuxt/nuxt.js/issues/6951 - it's deliberate backward compatibility that will be removed for Nuxt 3.

**Comment by winktim** [comment]
Hey,
Sorry for the duplicate. I looked around if the issue was already reported and didn't find it.
I'll patch the file in my node_modules in the meantime then. There really isn't a better option.
