### ISSUE TITLE
redirect fail with Chinese characters

### ISSUE THREAD

**Issue by githubalin** [nuxt/nuxt.js#8376]
### Versions

- nuxt: 
2.14.6
- node: 
12.19.0

### Reproduction

![image](https://user-images.githubusercontent.com/25549859/99767199-9e135a80-2b3d-11eb-8668-e8fe20d9324a.png)

### Steps to reproduce
just redirect to the about page in asyncData.
the redirect URL includes Chinese characters.

### What is Expected?
redirect to about page

### What is actually happening?
got error 'Invalid character in header content ["Location"] '

**Comment by pi0** [comment]
Hi @githubalin this sure is a bug but meanwhile you may use `redirect(encodeURI(...))`

**Comment by githubalin** [comment]
> Hi @githubalin this sure is a bug but meanwhile you may use `redirect(encodeURI(...))`

Thanks for your reply and I encode by myself

**Comment by 1alireza32109** [comment]
Hi you are very good and great. If it is possible for you to make the code
and take action to be fixed, thank you very much dear friend.

Your sincerely, Sheikh Ali


سلام شما خیلی خوب و بزرگ هستید. اگر برای شما مقدور است کد را شما درست کنید
و اقدام کنید تا درست شود .خیلی متشکرم از شما دوست عزیزم
ارادتمند شما شیخعلی

در تاریخ دوشنبه ۲۳ نوامبر ۲۰۲۰،‏ ۱۱:۵۴ alin <notifications@github.com> نوشت:
