### ISSUE TITLE
Scss partials are not importing to the page

### ISSUE THREAD

**Issue by dhara15101991** [nuxt/nuxt.js#8378]
I am new to scss in Nuxtjs. I have added all the css to assets folder. and also modified nuxt.config.js as below.

```
`assets/
  sass/
   project/
      element/
      _input.scss
      _tables.scss
      _model.scss
      mixins/
      _buttons.scss
      _lables.scss
      _navbar.scss
      _table-row.scss
    _cards.scss
    _inputs.scss
    _tables.scss
    _pages.scss
    _variables.scss
    _mixins.scss
  main.css`
```

My main css file

```
`@import "project/variables";
@import "project/mixins";

@import "project/element/input";
@import "project/element/tables";
@import "project/element/model";

@import "project/mixins/buttons";
@import "project/mixins/lables";
@import "project/mixins/navbar";
@import "project/mixins/table-row";

@import "project/cards";
@import "project/inputs";
@import "project/tables";
@import "project/pages";`
```

![image](https://user-images.githubusercontent.com/14217908/99783656-b0db5e80-2b40-11eb-8919-e62bcae5a35d.png)

I have done this to my nuxt.config.js.
```
styleResources: {
      scss: [
          __dirname +  '/assets/sass/project.scss',
      ]
  },
```
But I don't understand what is wrong with the scss. I get basic layouts but I cannot get partials on a page. Is there anything with the pages/components folder structure to load imports? Please help me. I am struggling for the last 2 days.

**Comment by danielroe** [comment]
@dhara15101991 You probably want something like https://github.com/nuxt-community/style-resources-module for sharing mixins and variables.

**Comment by danielroe** [comment]
You probably want something like https://github.com/nuxt-community/style-resources-module for your mixins and variables. I see you have added a configuration key for it, but you will need to add it as a module.

I'm going to close this as I don't think there's a bug here, but please do drop into https://discord.nuxtjs.org for support - we'd love to help.

**Comment by dhara15101991** [comment]
I have already installed this module.

![image](https://user-images.githubusercontent.com/14217908/99785170-cbaed280-2b42-11eb-930c-9fac8ab4023f.png)

**Comment by danielroe** [comment]
@dhara15101991 if you provide a code reproduction on https://template. nuxtjs.org, I'll happily take a look 😊
