### ISSUE TITLE
Markdown table not applying

### ISSUE THREAD

**Issue by kissu** [nuxt/nuxt.js#8380]
### Steps to reproduce
On production !

### What is actually happening?
I do like to have a markdown formatter to have properly formatted markdown tables while I code.
![image](https://user-images.githubusercontent.com/5133074/99807981-84274700-2b40-11eb-878e-8e4b6f887d65.png)

Below is the result in my VScode markdown preview. Looking great !
![image](https://user-images.githubusercontent.com/5133074/99807794-49251380-2b40-11eb-959b-d7cfc6589908.png)

My did my PR thinking that everything will work great but I stumbled upon that specific page and realized that it does not render properly... Below is the the [french documentation page](https://fr.nuxtjs.org/docs/2.x/configuration-glossary/configuration-loading/#utiliser-un-composant-de-chargement-personnalis%C3%A9) on production.
![image](https://user-images.githubusercontent.com/5133074/99810406-f77e8800-2b43-11eb-9dec-03180ef3a01d.png)

I thought that I may rather remove that useful feature of mine and keep the usual `---` header separator but, then I realized that the same is happening on production on the other pages too.
Below is the same one but in basic 🇬🇧, located [here](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-loading#using-a-custom-loading-component).
![image](https://user-images.githubusercontent.com/5133074/99808199-cc466980-2b40-11eb-99ba-bbef19fb0c24.png)

This is how it looks in dev environment.
![image](https://user-images.githubusercontent.com/5133074/99811397-70321400-2b45-11eb-9cce-bee7c3bb78d8.png)

### What is Expected?
The same behavior as while developing in local w/ `NUXT_LOCALE=fr yarn dev`. Yeah, it's work locally. 👌🏻 

PS: I do use [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#github-flavored-markdown) plugin btw. Not sure if it may be a good practice to have it for the whole project or not. Increases readability with bigger tables.

**Comment by danielroe** [comment]
This should be transferred to

**Comment by kissu** [comment]
Yeah sorry ! 😅
