### ISSUE TITLE
Async fetch assigning a value to component's data isn't working

### ISSUE THREAD

**Issue by mas-iota** [nuxt/nuxt.js#8381]
### Versions

- nuxt: ^2.14.6
- node: v12.19.0

### Steps to reproduce
1- Define a random page/component
2- Use async fetch
3- Assign a value to this
4- Try to use the new value in mounted or template

### What is Expected?
Using/accessing the newly assigned value

### What is actually happening?
The new value remains empty
```

    async fetch({ req, $config: { appHostName }, store, $axios, params }) {
      this.menu = await store.dispatch('menu/fetchMenu', 14)
      console.log('in fetch: ', this.menu) // correct value
    },
    data() {
      return {
        menu: {}
      }
    },
    mounted() {
      console.log('menu: ', this.menu) // {}
      setTimeout(()=> console.log('menu setTimeout: ', this.menu), 2000) // {}
    },
```

**Comment by danielroe** [comment]
@mas-iota If you want to use new fetch (with this) you should not take any arguments for your function. If you do, Nuxt will treat it as an old style fetch. More in the docs: https://nuxtjs.org/docs/2.x/components-glossary/pages-fetch

**Comment by mas-iota** [comment]
@danielroe Thanks for mentioning that! I've read the docs over and over and I couldn't find anything point out this behaviour nor in the link you shared

**Comment by danielroe** [comment]
@mas-iota Glad that helped! Sorry, I should have linked to https://nuxtjs.org/docs/2.x/features/data-fetching instead.
