### ISSUE TITLE
/_nuxt/ path showing up in search engine despite being ignored by robots.txt

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/nuxt.js#8382]
### Versions

- nuxt: v2.14.4
- node: v10.15.3

### Reproduction

Not needed for this other than to see the contents of my `robots.txt` file which is:

```txt
# My Site XML Robots.txt

# Sitemap:
Sitemap: https://example.com/sitemap.xml

# All crawlers welcome:
User-agent: *
Disallow: /_nuxt/
```

And my mode...

```javascript
export default {
  /*
  ** Nuxt rendering mode
  ** See https://nuxtjs.org/api/configuration-mode
  */
  mode: 'universal',
  /*
  ** Nuxt target
  ** See https://nuxtjs.org/api/configuration-target
  */
  target: 'static',
}
```

### Steps to reproduce

- Deploy a site with `npm run build && npm run generate`
- Generates to a `dist` directory

### What is Expected?

`/_nuxt/` shouldn't show up in a search engine.

### What is actually happening?

When the sitemap is submitted to Google Webmaster Tools and indexed, `/_nuxt/` path is showing up in the search engine despite being excluded/ignored via the `robots.txt` file.

**Comment by simllll** [comment]
robots.txt just prevents google from indexing the page content, not the url itself. If the file is placed correctly, I would say this is a normal behaviour and has nothing todo with nuxt itself?

There are several reason for google to discover this url, e.g. if someone links to it.
To ensure everything is set up correclty, you could use the robots.txt tester from google search console: https://www.google.com/webmasters/tools/robots-testing-tool

**Comment by danielroe** [comment]
Yes, this is not a Nuxt issue. Feel free to pop into the Discord if it would be helpful to discuss with others 😊

https://discord.nuxtjs.org

**Comment by martijnbeets** [comment]
Hi, I have some SEO experts asking me to remove `Disallow: /_nuxt/` from the robots.txt because of this article: https://yoast.com/dont-block-css-and-js-files/. 
But I'm certain _nuxt is disallowed for a good reason, but I can't find anything about that reason. I only stumbled upon this closed bug-report.

**Comment by danielroe** [comment]
@martijnbeets Personally I can't see why it should be disallowed.
