### ISSUE TITLE
CSS Logical Properties are not working well in Nuxt

### ISSUE THREAD

**Issue by talkor** [nuxt/nuxt.js#8387]
### Versions

- nuxt: v2.12.2
- node: v10 (Codesandbox), v14

### Reproduction

https://codesandbox.io/s/inspiring-minsky-l2e3s?file=/pages/index.vue

### Steps to reproduce

1. Add CSS Logical properties to any element, in the reproduction, for example, to `.title` (line 40-43):
```
 padding-inline-start: 100px;
 padding-inline-end: 100px;
 padding-block-start: 100px;
 padding-block-end: 100px;
```

### What is Expected?

The element should get all properties as written above.

### What is actually happening?

```
 padding-inline-start: 100px; /* this is NOT working, won't appear on the element */
 padding-inline-end: 100px; /* this is NOT working,  won't appear on the element */
 padding-block-start: 100px; /* this is working but converted to padding-top */
 padding-block-end: 100px; /* this is working but converted to padding-bottom */
```

**Comment by farnabaz** [comment]
This happens because Nuxt uses [PostCSS](https://postcss.org/). You can edit postcss config in `nuxt.config`:  
```js
export default {
	build: {
		postcss: {
        	// ....
		}
    }
}
```
or disable it 
```js
export default {
	build: {
		postcss: false
    }
}
```

**Comment by talkor** [comment]
Thanks @farnabaz ! I didn't know such setting exists

**Comment by mnr73** [comment]
i disabled postcss but still logical properties deleted

**Comment by belvederef** [comment]
Changing PostCSS default stage from 2 to 3 in the `nuxt.config` file allows CSS logical properties to be included in the final bundled CSS. E.g.
 ```ts
  build: {
    postcss: {
      preset: {
        stage: 3,
      },
    },
  }
  ```
