### ISSUE TITLE
Dynamic routes give `/_dynamic/child` routes 

### ISSUE THREAD

**Issue by PestoP** [nuxt/nuxt.js#8388]
First of all, I want to thank every contributors for this awesome project that is nuxt :)
Secondly, I hope this is a bug and I don't disturb you for nothing :grimacing: 
### Versions

- nuxt: v2.14.6
- node: 1.16.1

### Reproduction
You can find here a tiny example: https://github.com/PestoP/nuxt-dynamic-routes-issue

### Steps to reproduce

I have this directory tree:

index.vue
--/countries
--/index.vue
--/_countryName
----/index.vue
----/firstCountry
------/index.vue
----/secondCountry
------/index.vue

### What is Expected?

I'm expecting to have dynamic routes such as `countries/firstCountry` and `countries/secondCountry`

### What is actually happening?

So it's an easy example, I don't know what I am missing but I don't have dynamic routes. Instead, I got those routes:
`countries/_countryName/firstCountry`
`countries/_countryName/secondCountry`

Am I doing something wrong ? Even `yarn generate` doesn't seem to work

**Comment by danielroe** [comment]
@PestoP You just need `~/pages/countries/_country.vue` and it will handle whatever country is passed in the URL at that point.

See https://nuxtjs.org/docs/2.x/directory-structure/pages/#dynamic-pages
