### ISSUE TITLE
How can I use async/await within my components?

### ISSUE THREAD

**Issue by demetriusnunes** [nuxt/nuxt.js#84]
How can we use async/await in components and in Vuex actions?

When I try to use it right now, I get an error.

**Comment by Atinux** [comment]
Hi @demetriusnunes 

You add the babel plugins to transform you async functions:
`nuxt.config.js`
```js
module.exports = {
  build: {
    babel: {
      plugins: [
        'transform-async-to-generator',
        'transform-runtime'
      ]
    }
  }
}

```

And then you can use async function in your components:
`pages/index.vue`
```html
<template>
  <pre>{{ $data }}</pre>
</template>

<script>
import axios from 'axios'

export default {
  async data () {
    let res = await axios.get('https://api.myjson.com/bins/18pdl3')
    return res.data
  }
}
</script>
``` 

Example: https://gomix.com/#!/project/nuxt-await
Demo: https://nuxt-await.gomix.me/

But I am now wondering if I should include this feature in Nuxt.js directly?

Ping @pi0 @antcook @johnlindquist @declandewet

**Comment by Atinux** [comment]
Finally, `transform-async-to-generator` and `transform-runtime` will add the polyfills only when `async/await` is used, so I included it in the core and will be available in the next release `0.9.5` 🔥

**Comment by Atinux** [comment]
@demetriusnunes you can upgrade to the [`0.9.5`](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.5) it should work without any modification of your code 😃

**Comment by demetriusnunes** [comment]
You guys rock! Thanks! This is shaping up to be the best web framework I've seen in a long time!
