### ISSUE TITLE
Code coverage using nyc and ava guide

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#840]
Hey @alexchopin , I'm trying to configure `nyc` and `ava` to get the code coverage report but currently it just outputs a `100%` coverage for the files `.eslintrc`,`.nuxt.config.js` and `modules` directory. I searched but couldn't find a way to get the coverage for `.vue` files using `nyc ava`. Vue.js documentation currently uses `karma` etc.

NYC config:
```json
"nyc": {
    "exclude": [
      "modules",
      "plugins",
      "static",
      "assets",
      "**/*.test.js",
      ".eslintrc.js",
      "nuxt.config.js"
    ],
    "extension": [
      ".js",
      ".vue"
    ]
  }
```

Test commands:
```json
"test": "./node_modules/.bin/nyc ava",
"report": "./node_modules/.bin/nyc report --reporter=html",
"codecov": "./node_modules/.bin/nyc report --reporter=lcov > coverage.lcov && codecov"
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c719">#c719</a>)</em></sub></div>

**Comment by piyushchauhan2011** [comment]
Maybe we should have guides for `karma` testing as the default `vue-loader` has documentation for `karma` coverage and testing https://vue-loader.vuejs.org/en/workflow/testing.html

**Comment by piyushchauhan2011** [comment]
Tried using this as a reference as the coverage works on this project https://github.com/eddyerburgh/avoriaz-ava-example/issues/8. Using this config makes server running infinitely not sure why though

**Comment by piyushchauhan2011** [comment]
Couldn't make it work not sure why coverage is just blank 😞

**Comment by piyushchauhan2011** [comment]
@eddyerburgh I was thinking if there are any thoughts about integration with Nuxt ?

**Comment by Atinux** [comment]
Hi @piyushchauhan2011 

It's planned but only after 1.0 release

**Comment by piyushchauhan2011** [comment]
@Atinux cool, no worries ;)

**Comment by clarkdo** [comment]
+1

**Comment by acidjazz** [comment]
+1

**Comment by jonnyparris** [comment]
+1

**Comment by carasel** [comment]
+1

**Comment by ismatim** [comment]
What about this ? Any good news ?  I got same result in version nuxt@1.4.0

**Comment by galvez** [comment]
Closing as there's been no updates over 90 days.
