### ISSUE TITLE
Can't access the cookies in middleware on first page load of static app

### ISSUE THREAD

**Issue by pmrotule** [nuxt/nuxt.js#8406]
I'm running a static app with Nuxt and I tried to use a middleware to check if the user is logged in or not. I use Apollo with `@nuxtjs/apollo` and I used the same middleware example provided in the [documentation](https://www.npmjs.com/package/@nuxtjs/apollo#gettoken). After trying it, I realized that getting the token from the cookies with `app.$apolloHelpers.getToken()` was not working on the first page load, but working on the next page loads made with the SPA. This is because a middleware is processed in the backend on the first page load and the `req` is undefined because it's a static website and no actual request is made and therefore, `ctx.req.cookies` will be undefined as well.

I thought of opening an issue in the apollo module instead, but actually, it has nothing to do with Apollo. In my opinion, it doesn't make sense that a middleware is executed on the backend when using a static website since there is no backend on production. Using a middleware to check if the user is authenticated is quite a common use case but it's currently not possible to do it with a static website because you won't have access to the cookies or localStorage on the first execution of your middleware.

### Versions

- nuxt: 2.14.6
- node: 12.18.3

### Reproduction

```js
// ~/node_modules/@nuxtjs/apollo/lib/templates/plugin.js

getToken: (tokenName = AUTH_TOKEN_NAME) => {
  console.log(cookies)
  return cookies.get(tokenName)
}
```
will log this in my terminal when reloading the page
```
Cookies {
  changeListeners: [],
  HAS_DOCUMENT_COOKIE: false,
  cookies: {}
}
```
</details>

### Steps to reproduce

- Create a global middleware and log the `req`

```js
export default function ({ req }) {
  console.log(req && req.cookies)
}
```

- Reload the page and `undefined` should be logged in your terminal

### What is Expected?

- The middleware should always be executed client-side even on the first page load

### What is actually happening?

- The middleware is executed server-side on the first page load without being able to access the cookies

**Comment by danielroe** [comment]
@pmrotule This is because in a static app, `req` will never be populated (first load or not) - see [docs](https://nuxtjs.org/docs/2.x/features/deployment-targets/#static-hosting). The `req` object is never available on client side in a Nuxt app - and it can't be accessed on server-side at runtime in a staticly rendered app - and it doesn't make sense to check a cookie at generate-time.

Note also that depending on how you have set the cookie, it might not be accessible in any case on first load (an unexpected consequence of `SameSite=Strict`).

**Comment by pmrotule** [comment]
Yes, I'm aware of `req` being undefined for static site. That's what I was saying. With that in mind, how come a middleware is executed on the backend on the first page load for static apps? That's the issue I was raising, not the fact that `req` is undefined.

In my opinion, the fact that the middleware can't access the cookies nor the localeStorage doesn't make sense and if it was executed on the client-side on the first page load as well as the next navigation with the SPA, everything would work as expected.

I was able to make it work using a plugin adding a `router.beforeEach`, but still, it's not as clean as a middleware since I can't hook it in the page component.
