### ISSUE TITLE
fetch causes to call watcher for object data

### ISSUE THREAD

**Issue by AliRezaBeitari** [nuxt/nuxt.js#8410]
### Versions

- nuxt: v2.14.7
- node: v12.19.0

### Reproduction
https://codesandbox.io/s/jolly-chaplygin-vkfps?file=/pages/index.vue

### What is Expected?
The `abc` watcher should not be called.

### What is actually happening?
The `abc` is called after the page is loaded.

**Comment by danielroe** [comment]
@AliRezaBeitari The way `fetch` is currently implemented is that the *entire* state of the component is stringified and applied on client side, which is why watch is triggering here.

**Comment by AliRezaBeitari** [comment]
@danielroe Thanks for your helpful information. I didn't know that!
Well, in the watcher I actually change the query parameters by `this.$router.push({ query: abc })` and because `abc` is wrong, the query parameters will get the wrong values.

**Comment by UngererFabien** [comment]
> @AliRezaBeitari The way `fetch` is currently implemented is that the _entire_ state of the component is stringified and applied on client side, which is why watch is triggering here.
> 
> Is there a reason this is a problem for you? You could consider, for example, programmatically instantiating a watcher on `abc` after the fetch hydration.

Hello, the fact that `fetch` trigger a stringify will also create a call stack issue if anything is not able to be stringified in `data`. Could be interesting to add in a warning in the documentation.
