### ISSUE TITLE
The page introduces the third-party component of JSX syntax, which makes the project unable to run

### ISSUE THREAD

**Issue by wanlixi** [nuxt/nuxt.js#8411]
It is no problem to write a page directly using JSX syntax, but a third-party component that references JSX syntax in the page will report an error

nuxt.config.js
```
  {
    ...
    ssr: true,
  }
```

**Comment by wanlixi** [comment]
mode: "universal"

**Comment by wanlixi** [comment]
notice
ssr: true

**Comment by danielroe** [comment]
@wanlixi Would you prepare a reproduction using https://template.nuxtjs.org? :pray:
