### ISSUE TITLE
Redirection in middleware in static site

### ISSUE THREAD

**Issue by Hartaxfr** [nuxt/nuxt.js#8413]
### Versions

- nuxt: v2.14.0
- node: v10.19.0

### Reproduction

!!!!!!!! target: "static" !!!!!!!!!!!
minimal project with 3 pages, index.vue, account.vue, login.vue

index with nuxt-link to account

account empty page with anonymous middleware that redirect to "/login"

Not able to make codesandbox working sorry ... 

### What is Expected?

redirect to "/login"

### What is actually happening?

still on "/account", and get a white empty page

**Comment by Geminii** [comment]
Hi @Hartaxfr 

Reproduction will really help to get the same state to avoid this behavior. 
No code, and missing too many information about middleware. 
Try to create a codesandbox, it's really quick to do ;)
