### ISSUE TITLE
Build fails on code only used in development

### ISSUE THREAD

**Issue by chrissyast** [nuxt/nuxt.js#8414]
I have some code which I only use locally in development. I have content on a CMS and rather than calling the API every time to retrieve the content I store it locally on a file and retrieve it that way.

Even if I surround the code in `try/catch` AND `if(false)` the build still complains `Error: Can't resolve './translations/index.json'`. I don't really want to commit the json as it's only needed when running locally.

```js
export default async function loadTranslations() {
  if (false) { 
  try {
  const translations = await import(
  `./translations/index.json`)
  } catch (error) {
    console.log("foo")
  }
  }
}
```
How can I get the build to ignore this error?

**Comment by danielroe** [comment]
@chrissyast You should be able to get that to work with require rather than import.

**Comment by chrissyast** [comment]
@danielroe thanks!  `require` worked. I used `await import` based on some code I'd seen on another project, not quite sure why it was used and how it didn't fail but don't really care as this works for me!

**Comment by chrissyast** [comment]
Actually no, it worked because I had the file present at the time 🤦
