### ISSUE TITLE
this in nuxt.config.js different

### ISSUE THREAD

**Issue by 0pt1m1z3r** [nuxt/nuxt.js#842]
I want to use `this.srcDir` in `extend` function in build section of nuxt.config.js. But `this` sometimes different. When ctx.isServer is true `this` does not contain `srcDir`.
Is it a bug?

**Comment by alexchopin** [comment]
It's not a bug, you need to write srcDir again or not using it if its the default value.

**Comment by 0pt1m1z3r** [comment]
@alexchopin You did not understand me.
in my `nuxt.config.js` `srcDir` is `app /`. I insert `console.log(this.srcDir);` in `build extend`.
`npm run dev` show this:
```
  nuxt:build Generating files... +53ms
  nuxt:build Generating routes... +9ms
  nuxt:build Adding webpack middleware... +61ms
this.srcDir: /Users/***/***/***/app
  build [=         ] 10%this.srcDir: undefined
```
There are two console.log calls. With different results.
