### ISSUE TITLE
Custom routes not working after upgrading to v2.14.8

### ISSUE THREAD

**Issue by zabavnikov** [nuxt/nuxt.js#8420]
### Versions
nuxt: v2.14.8
node: v12.18.3

**Routes:**
![image](https://user-images.githubusercontent.com/8766240/100742768-e409d180-340d-11eb-8699-f9510996e167.png)

**Error:**
![image](https://user-images.githubusercontent.com/8766240/100742901-11ef1600-340e-11eb-8a0e-dc9bf668f8ee.png)

**Comment by croftman** [comment]
Same here

**Comment by pi0** [comment]
Released as hotfix [v2.14.9](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.9) (please reopen if still having issues)
