### ISSUE TITLE
trailingSlash=true and child routes generates a VueRouter warning

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#8422]
### Versions

- nuxt: 2.14.8
- node: v12.19.0

### Reproduction

```js
  router: {
    trailingSlash: true
  },
```

Directory structure:
![Screenshot 2020-07-31 at 13 40 45](https://user-images.githubusercontent.com/153197/89031783-76507a80-d333-11ea-93ba-4ede0340b5b9.png)

Repo: https://codesandbox.io/s/nuxt-trailingslash-true-and-child-routes-zp5tt (best to download and try locally).

### Steps to reproduce

Visit the root route.

### What is Expected?

No warning in the console

### What is actually happening?

With a directory structure like above and `router.trailingSlash` set to `true` the generated routes in `.nuxt/router.js` look like this:

```js
{
    path: "/posts/",
    component: _17b9cb62,
    pathToRegexpOptions: {"strict":true},
    name: "posts",
    children: [{
      path: "",
      component: _e4367f36,
      pathToRegexpOptions: {"strict":true},
      name: "posts"
    }, {
      path: ":slug/",
      component: _e7a3c1c6,
      pathToRegexpOptions: {"strict":true},
      name: "posts-slug"
    }]
  }, {
    path: "/",
    component: _6f29e0e1,
    pathToRegexpOptions: {"strict":true},
    name: "index"
  }
```

and visiting the root route triggers a VueRouter warning:

> WARN  [vue-router] Named Route 'posts' has a default child route. When navigating to this named route (:to="{name: 'posts'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.
> WARN  [vue-router] Duplicate named routes definition: { name: "posts", path: "/posts/" }

I believe this is due to `name` being duplicated on two routes.

**Comment by pi0** [comment]
Thanks for clean repro @rchl. Trying to fix on #8423
