### ISSUE TITLE
Query string parameters are not URI-decoded in route.query

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt.js#8429]
### Versions

- nuxt: v2.14.8 and v2.14.9
- node: v15.3.0

### Reproduction

Since updating to nuxt v2.14.8, query string parameters with encoded characters are passed un-decoded in `route.query` in `context` to `asyncData`. The v2.14.9 hotfix did not fix this issue.

<details>
<summary>Additional Details</summary>

```js

  async asyncData ({ app, route, error }) {
    let data = {
      search: {
        query: route.query.q,
        location: route.query.gl,
        registrar: route.query.r,
        terms: route.query.t,
        defaults: route.query.d,
        results: []
      },
      metadata: {
        domain: route.params.domain
      }
    }

    // BUG: data.search.terms == 'coffee%2Cfood' instead of 'coffee,food'

    // ...

    return data
  }
```
</details>

### Steps to reproduce

- Visit `/?t=coffee,food`
- In `asyncData`, extract the `t` query string parameter

### What is Expected?

`route.query.t == 'coffee,food'`

### What is actually happening?

`route.query.t == 'coffee%2Cfood'`

**Comment by pi0** [comment]
I tried to reproduce code above on codesandbox but seems query parameters are properly decoded: https://codesandbox.io/s/objective-bassi-5oxri

@ydnar  Is it happening for `nuxt dev` too or nuxt generate?

**Comment by gulien** [comment]
I'm encountering the same issue on nuxt v2.14.9 (`dev` script, i.e., `yarn dev`).

**Comment by ydnar** [comment]
@pi0 I don’t know how to get that sandbox to run modified code, but if you change the link to use URI-encoded commas, it should break:

`/?t=coffee%2Cfood%2C`

**Comment by ydnar** [comment]
https://codesandbox.io/s/objective-burnell-xd9z5?file=/pages/index.vue

**Comment by pi0** [comment]
I see. This regression is also reproducible with `nuxt@2.14.7` and `vue-router@3.4.9` (latest). Investigating more for workaround...

**Comment by ydnar** [comment]
Whew. Glad it wasn’t our monkeypatching of the `vue-router` internals.

**Comment by pi0** [comment]
Hi. Issue should be fixed by [2.14.10](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.10)

---

@ydnar please also see foot-note in #8430 about `encodeURIComponent` you may improve your implementation :)

**Comment by gulien** [comment]
Problem solved on my app 🎉 thank you @pi0

**Comment by case** [comment]
Thank you @pi0! Much appreciated.
