### ISSUE TITLE
Doesn't charge script in page

### ISSUE THREAD

**Issue by fortil** [nuxt/nuxt.js#843]
Hi guys

I need to charge a external link (script) in the head of one page, not in all. Because I'm using Froala editor, [url integration](https://www.froala.com/wysiwyg-editor/docs/framework-plugins/vue)
nuxt.config.js
 ```
 plugins: [
    '~plugins/vuetify',
    { src: '~plugins/socket-client', ssr: false },
    { src: '~plugins/froala', ssr: false }, 
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    })
  ],
```
file.vue
```
<script>
export default {
  data () {
    return {
      config: {
        events: {
          'froalaEditor.initialized': function () {
            console.log('initialized')
          }
        }
      },
      model: 'Edit Your Content Here!'
    }
  },
  head () {
    return {
      script: [
        { src: '//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js', type: 'text/javascript' }
      ]
    }
  }
}
</script>
```
when I enter in the page the link doesn't appear.

What can i do?

thanks

**Comment by piyushchauhan2011** [comment]
Hmm, @fortil can you make a minimal demo of injecting `script` tag on different pages by remixing this glitch https://glitch.com/edit/#!/nuxt-hello-world?path=README.md:1:0

**Comment by fortil** [comment]
I have was reading about vue-meta and solved the problem, but I have a question, I use froala, but this library need jQuery global so as ready i can put script in the head, do you know somehow to put $ global into the layout or page?

thanks

**Comment by PhilAndrew** [comment]
@fortil How can I use Froala in Nuxt.js? I tried and failed :(
