### ISSUE TITLE
nuxt-link small freeze beetween _slug and page

### ISSUE THREAD

**Issue by shioridotdev** [nuxt/nuxt.js#8433]
Hello,

I got a small issue on my app.  
When using nuxt-link everything work smoothly beetween page but whenever I go from a \_slug.vue page to the index for exemple I got a small freeze before page is loading.

Here is a link exemple on my navbar component .vue

```  
<li>  
  <nuxt-link to="/" :class="[currentPage === '/' ? activeClass : '', '']">  
<i class="fas fa-stream"></i>  
  </nuxt-link>  
</li>
``` 

here the link to a single post  
```
<nuxt-link :to="{ name: 'reports-id', params: { id: report._id } }">READ MORE</nuxt-link>  
```

my folder are like this
```
index.vue
--reports
----_id.vue
----index.vue
--works
----_id.vue
----index.vue
```

**Comment by danielroe** [comment]
Would you provide a sample reproduction via https://template.nuxtjs.org ?

**Comment by shioridotdev** [comment]
> Would you provide a sample reproduction via https://template.nuxtjs.org ?

As you ask I done the codesandbox. But I past exactly the same code as mine (expect css), with my api and it work.
https://codesandbox.io/s/purple-haze-puztt

But on my site here: https://shiori.dev/reports/ you can see that there is a small freeze when you go from a report (https://shiori.dev/reports/5fc88339e12512e25f14a002) to another page.
