### ISSUE TITLE
Nuxt config htmlAttr, not Working

### ISSUE THREAD

**Issue by MilesWuCode** [nuxt/nuxt.js#8435]
Nuxt config htmlAttrs, not Working

- nuxt: v2.14.7
- node: v15.2.1

```
  ssr: false,

  // Global page headers (https://go.nuxtjs.dev/config-head)
  htmlAttrs: {
    lang: 'zh-TW',
  },
```

**Comment by danielroe** [comment]
@MilesWuCode Check the docs link you posted for examples - it should be within`head`.

**Comment by MilesWuCode** [comment]
> @MilesWuCode Check the docs link you posted for examples - it should be within `head`.
> 
> E.g. https://github.com/nuxt/nuxtjs.org/blob/4603b7060529211f52f5fb071eea065755ab353e/nuxt.config.js#L6

i found ...@nuxtjs/pwa

```js
  modules: [
   .....
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
```
if i setting

```js
  pwa: {
    manifest: {
      name: 'My Awesome App',
      lang: 'zh-TW',
      useWebmanifestExtension: false,
    },
  },
```

will be working

**Comment by danielroe** [comment]
@MilesWuCode yes, that is another way to do it.
