### ISSUE TITLE
What puzzles me is that the value of axios hostname in nuxt is always 10809?

### ISSUE THREAD

**Issue by hycreeze** [nuxt/nuxt.js#8437]
### version
 - windows:  64-bit Professional
 - nuxt：v2.14.6
 - node：v14.15.1

### Reproduction
I have opened a django api service localhost, but I cannot access it correctly in nuxt.js. The following is the content of my files
-  pages/index.vue
```vue
<script>
    export default {
      async asyncData({ context, $axios }) {
        try {
          const { data } = await $axios.$get('/demo');
        } catch (err) {
          console.log(err);
        }
      },
    }
</script>
    
```
- nuxt.config.js
```vuejs
export dafault {
  modules: [
    '@nuxtjs/axios',
  ],

  axios: {
    baseURL: 'http://localhost:8000'
  },
}
```

### What actually happened?
>Tips:  My Api service is running well,
http://localhost:8000/demo is a test interface that returns a json string, the following is a screenshot of my request to the api service using postman
```json
{
    "code": 200,
    "msg": "Test Api Service"
}
```

But when I used Nuxt to build and visit, he got the following error:
```json
Error:
    getaddrinfo ENOTFOUND 10809
    dns.js:
      Missing stack frames
    
    GetAddrInfoReqWrap.onlookup[as.oncomplete]@66:26

```
The exception caught by the console is as follows：
![微信图片_20201203171658](https://user-images.githubusercontent.com/59901933/100989187-8602f880-358b-11eb-850a-5b4e2c3082a7.png)

You can see that the `hostname` item in the figure is `10809`. This is where I am very confused. The `baseurl` I configured in `nuxt.config.js` is obviously `localhost:8000`, but the value here is fixed `10809`,And I have added localhost `127.0.0.1` in the `host` file

### In addition, I also tried the following
- Reinstall the nuxt project
- Modify the `baseurl` configuration information of the `axios` item in `nuxt.config.js`
- Modify the value of the `baseURL` constant in the `axios.js` file under the generated `.nuxt` folder
- Switch network
- Search globally in the project ```10809```
- And so on...

But no matter what I do, the error is always 
```
getaddrinfo ENOTFOUND 10809.
```
I am curious how it works internally. Why is the ```hostname``` item always ```10809```?

### Write at the end
This problem has troubled me for two days and I am eager to get your guidance!!!

**Comment by shioridotdev** [comment]
Can you try again with disabling explicitly the proxy on axios option
```
  axios: {
    baseURL: 'http://localhost:8000',
    proxy: false
  },
```

**Comment by hycreeze** [comment]
> 您可以重试禁用axios选项上的代理吗？
> 
> ```
>   axios: {
>     baseURL: 'http://localhost:8000',
>     proxy: false
>   },
> ```

Thank you. This option is false by default

**Comment by danielroe** [comment]
@hycreeze Would you be able to provide a reproduction, and raise an issue at https://github.com/nuxt-community/axios-module/ ?

**Comment by liupan-hi** [comment]
i have the problem too. So confused
