### ISSUE TITLE
nuxt环境中 引入jsencrypt 会报错 navigator is not defined

### ISSUE THREAD

**Issue by 15836673175** [nuxt/nuxt.js#8438]
### Versions

- nuxt: 2.14.6
- node: v14.14.0 
   vue: 2.6+
  系统: osx 10.15
![image](https://user-images.githubusercontent.com/31263663/100996265-d1210980-3593-11eb-963b-b37253d0c8ac.png)

按照网上说加上 // global.navigator = {appName:'node.js'};
// global.window = {}; 之后 又会有 一些其他报错 而且莫名卡死 求求帮忙解决下

**Comment by danielroe** [comment]
@15836673175 It looks like that dependency is not compatible with a node environment - you can follow the example here: https://nuxtjs.org/docs/2.x/directory-structure/plugins#client-or-server-side-only
