### ISSUE TITLE
Context query is empty in router middleware

### ISSUE THREAD

**Issue by PaulBouisset** [nuxt/nuxt.js#8439]
I am not sure if I do something wrong but when using a router middleware I can't get the route query on the first page load. When switching page the context.query is correct but not on first page load. 
I assume this is because on first load the process is "server" but I am not sure how to solve this.

### Versions

- nuxt: 2.14.5

mode: universal
target: static

### Steps to reproduce
[https://codesandbox.io/s/intelligent-dream-lgo6e?file=/middleware/query.js
](https://codesandbox.io/s/intelligent-dream-lgo6e?file=/middleware/query.js
)

Try to add a query to the url like "?v=1" and reload the page

### What is Expected?
When loading the page with a query in the url the  context.query object should show the correct query.

### What is actually happening?
The context.query object is empty

**Comment by shioridotdev** [comment]
It as something to do with server side rendering.
With ssr set to true its working as you want.

For ssr I made it working by using serverMiddleware in nuxt config

`serverMiddleware: ["~/middleware/query"]`

Then I edit the query.js as follow
```
export default function (req) {
  console.log(req._parsedOriginalUrl.query);
}
```
https://codesandbox.io/s/admiring-varahamihira-49
There is maybe a better way to access this without using parsedOriginalUrl etc...
