### ISSUE TITLE
Routing with special characters broken

### ISSUE THREAD

**Issue by chamburr** [nuxt/nuxt.js#8442]
Routing with special characters in the path is broken after a Nuxt upgrade from 2.14.7 to 2.14.9. Instead of properly displaying the page as it does in the previous version, a page not found error is returned.

I am unable to provide a code sandbox link because it does not accept special characters in file names.

### Versions

- nuxt: 2.14.9
- node: 15.3.0

### Steps to reproduce

1. Download the [code sandbox template](https://github.com/nuxt/codesandbox-nuxt).
2. Upgrade the Nuxt dependency to `2.14.9`.
3. Rename `about.vue` to `@about.vue`.
4. Run `yarn dev` to start the server.
5. Visit http://localhost:3000/@about in a browser.

### What is expected?

The about page should properly show up.

### What is actually happening?

A page not found error is returned.

**Comment by pi0** [comment]
Hi. Issue should be fixed by [2.14.10](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.10)

**Comment by ydnar** [comment]
Thanks!
