### ISSUE TITLE
Nuxt deploy doesn't work properly in github pages (Images + Js broken)

### ISSUE THREAD

**Issue by zarub2k** [nuxt/nuxt.js#8443]
### Versions

- nuxt: @nuxt/content@1.11.1
- node: v12.19.0

### Steps to reproduce
npm run generate
npm run serve

This works fine and I am able to see all the resources (js + images loded properly)

### What is Expected?
Images and javascript should be loaded properly which are available inside my project

### What is actually happening?
npm run deploy

After the application is deployed into my github pages, I am not able to see any of the images.
But actually the images and javascripts are available in the gh-pages. But it is not rendered properly 

https://zarub2k.github.io/tham/blog/

**Comment by danielroe** [comment]
@zarub2k Have you followed the instructions on https://nuxtjs.org/faq/github-pages/ ?

**Comment by zarub2k** [comment]
Yes I referred the mentioned page. Instead of `push-dir` module I have used `gh-pages` module to deploy. Other than that I just followed the steps mentioned. 

My deployment is working fine and I am able to see my home page without any problem. When I click my blog link my blog content is also rendered but the image is not rendered. It is showing me 404 error message in my browser's developer console.

You can refer the source code under https://github.com/zarub2k/tham
and
my deployment under https://github.com/zarub2k/tham/tree/gh-pages

**Comment by danielroe** [comment]
@zarub2k Looks like you need a `.nojekyll` file - see https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

Nuxt generates this file for you for exactly this purpose. With the `gh-pages` module you need to pass an option to enable this file to be pushed to the branch - see options: https://github.com/tschaub/gh-pages#optionsdotfiles

**Comment by zarub2k** [comment]
@danielroe 
Now I am able to see the images loaded and I have included with --dotfiles options in my gh-pages. But I am still seeing some Javascript loading error with 404 https://zarub2k.github.io/tham/_nuxt/a6c8b1b.js

I am not sure how to fix this?

**Comment by danielroe** [comment]
@zarub2k I am not experiencing any JS 404 errors on your page.

I'd suggest you join the Nuxt Discord server on https://discord.nuxtjs.org where there are lots of us who would be happy to help. (But this isn't an issue with Nuxt :slightly_smiling_face: )
