### ISSUE TITLE
Vuex's registerModule only works server-side

### ISSUE THREAD

**Issue by klausXR** [nuxt/nuxt.js#8445]
### Versions

- nuxt: v12.12.2
- node: 13.14.0

### Reproduction

https://codesandbox.io/s/wizardly-allen-xyc6f

<details open>
<summary>Additional Details</summary>
<br>

The method only works if it runs on the server. If it is called from one of the client-side hooks, it appears to work, but the module is not registered properly ( its value is `undefined` ).
</details>

### Steps to reproduce

 Open up the repo and open the `about.vue` page. There are two methods there - created, mounted. 

Navigate to the `about` page and watch the console. It should log the module, but it logs undefined.

If you comment out `mounted`, and remove the comments of `created`, it works properly if you refresh on the `about` page, but not if you navigate to it.

### What is Expected?
When the `mounted` lifecycle hook runs and registers the module, it should be properly defined.

### What is actually happening?
The module is registering properly only if the hook runs server-side.

**Comment by Timkor** [comment]
You will need to set the `preserveState` option correctly (while hydrating):
https://vuex.vuejs.org/api/#registermodule

**Comment by klausXR** [comment]
> You will need to set the `preserveState` option correctly (while hydrating):
> https://vuex.vuejs.org/api/#registermodule
> 
> Also, I am not sure you can use `async` on the `created` hook. And I am wondering why you are using Vuex modules this way, instead of the build in method of Nuxt.

As far as I can see, it doesn't work even with this option.

I'm not really sure what you mean by "Using Vuex modules this way". 

My application provides additional functionalities to some of the users, which are build on top of Vuex. Lets say regular users can only read some of the data, they don't need the additional module. But the ones that can perform mutations on it, do require the additional module, and this issue prevents me from being able to lazily load it, as it depends on being called server-side for it to work properly. If the user is visiting the page client-side, it doesn't work.

**Comment by Timkor** [comment]
I can see why you would want to do this now. The preserveState option should fix it if set correctly.

The overhead to register an empty unused store is not that much IMO, just make sure not to fill and fetch the data when it won't be required. As for the blog post example, I wouldn't load then at all in the store (if you are able to fetch them using a capable API).

**Comment by klausXR** [comment]
The overhead comes not from dispatching actions prematurely, but by code being loaded at all. You might have a Vuex module with hundreds of lines of code. Repeat this a few time for larger applications and you'd be able to spot the problem.

These modules can depend on third-party libraries themselves, like lodash/moment or similar and it quickly gets out of hand. The modules that I can conditionally load exceed 50kb's when gzipped and they can only grow larger.

Thank you for the tips, I will try it out when I'm at work.

Should I set the value of `preserveState` to `process.client`? Would that be the correct approach? Some of these modules will not be registered on the server at all, and I don't really care to preserve any state between `registerModule/unregisterModule` calls.

**Comment by Timkor** [comment]
@klausXR 
You should set the preserveState like this:
```
store.registerModule(moduleName, { ... }, { preserveState: !!store.state[moduleName] });
```
This way it will work both on serverside render and client side navigation.

I can see where you are coming from when your store modules get that large. This will indeed be an option to make sure these chunks are loaded async, although personally I would try to lift the heavy work from the store to an (async) plugin or API.
