### ISSUE TITLE
Infinite redirect loop on double forward slash when custom error layout is defined

### ISSUE THREAD

**Issue by atlesque** [nuxt/nuxt.js#8446]
### Versions

- nuxt: v2.14.9
- node: v12.18.0

### Reproduction

Codesandbox (in browser): [https://codesandbox.io/s/fervent-galois-fwhqu](https://codesandbox.io/s/fervent-galois-fwhqu)

Repository (manual reproduction): [https://github.com/atlesque/nuxt-bug-custom-error-page](https://github.com/atlesque/nuxt-bug-custom-error-page)

#### Additional Details

This repository was created using `npx create-nuxt-app`. The only change is in the [latest commit ](https://github.com/atlesque/nuxt-bug-custom-error-page/commit/4b2da6f3cfd4b2ffa0036fa98e14e553339e96c6), which is a snippet coming from the [official docs on creating a custom error page](https://nuxtjs.org/docs/2.x/concepts/views#error-page).

### Steps to reproduce

- Create a new Nuxt project:  `npx create-nuxt-app` or [clone this repository](https://github.com/atlesque/nuxt-bug-custom-error-page)
- If you haven't cloned the repository but started a fresh project, first create a new layout: `layouts/error.vue`
- Copy and paste [the code from the official docs](https://nuxtjs.org/docs/2.x/concepts/views#error-page):
```vue
<template>
  <div>
    <h1 v-if="error.statusCode === 404">Page not found</h1>
    <h1 v-else>An error occurred</h1>
    <NuxtLink to="/">Home page</NuxtLink>
  </div>
</template>

<script>
  export default {
    props: ['error'],
    layout: 'error' // you can set a custom layout for the error page
  }
</script>
```
- Start the dev server: `npm run dev`
- Go to `http://localhost:3000//` (note the double forward slash at the end)

### What is Expected?

See the custom 404 error page.

### What is actually happening?

The browser gets stuck in an infinite redirect loop.

### Additional comments?

Note that this does not seem to be a standard 301 redirect, but something happening in the code (vue-router, or something else). When you do a CURL to the same URL, you will get a 404. The redirect seems to happen later, through Javascript.

One way to (partially) fix this is by using the router `extendRoutes` property and creating a custom 404 page like `pages/404.vue`, as described in [the official documentation on the router config](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes). This seems to be the right way of implementing a custom 404 page, but in that case, the views documentation needs to be updated. Also, vue-router will still throw an exception about `replaceState` and if your 404 page has a `<NuxtLink>` it will also break. Not sure if this is a Nuxt or a vue-router bug because of this?

**Comment by atlesque** [comment]
This is a workaround which fixes the problem:

- Create a middleware `middleware/remove-double-slash.js`:
```
export default function ({ route, redirect }) {
  if (route.path.includes("//") === true) {
    return redirect("/");
  }
}
```
- Define the middleware in `nuxt.config.js`, along with a custom 404 page:
```
router: {
    extendRoutes(routes, resolve) {
      routes.push({
        name: "custom",
        path: "*",
        component: resolve(__dirname, "pages/404.vue"),
      });
    },
    middleware: "remove-double-slash",
  },
```

Whenever there's a path that includes two subsequent forward slashes, the router will redirect to home.

Note you can also use a `layouts/404.vue` as defined in the documentation, but I personally find this unintuitive. A 404 page should be a page, not a layout. And by using an actual page, you get the benefit of being able to use custom layouts for it.

Still not sure why the initial bug is happening, but hope it helps someone!

**Comment by mschoeffmann** [comment]
i can also confirm this.
node 14.16.0
nuxt 2.15.2
in "spa mode" with htm5 history (ssr: false)

**Comment by atlesque** [comment]
Verified the issue is still present on v2.15.7. Same steps apply.

**Comment by shumiarrow** [comment]
I also confirm this.
node 14.17.2
nuxt 2.15.2

**Comment by mschoeffmann** [comment]
Still an issue.
Reproduced with Nuxt 2.15.8
