### ISSUE TITLE
v12.14.10 is breaking existing projects

### ISSUE THREAD

**Issue by jankal** [nuxt/nuxt.js#8452]
There seems to be problem with TypeScript & @nuxt/types.

### Versions

- nuxt: v12.14.10
- node: v12 / v14

### Reproduction

https://github.com/jankal/jankal.dev/pull/20

See different failing checks (building application) in the pull-request.

### Steps to reproduce
Upgrade TypeScript project from nuxt@12.14.9 to nuxt@12.14.10

### What is Expected?
Application builds like usual.

### What is actually happening?
TypeScript issues a type-error concerning nuxt's `Context` not having properties merged in via declaration merging.

I've not yet finished investigation. But I think that the `Context` type broke somehow.

Ping @pi0: This might be a problem with some upstream dependency upgraded by renovate.

**Comment by jankal** [comment]
TS errors:
```
TS2339: Property '$content' does not exist on type 'Context'.
```
```
Type 'import("/app/node_modules/@nuxt/content/node_modules/@nuxt/types/app/index").Context' is not assignable to type 'import("/app/node_modules/@nuxt/types/app/index").Context'.
```
```
Type 'Context' is missing the following properties from type 'Context': $colorMode, $axios
```

**Comment by jankal** [comment]
I don't know why... but my investigations showed that renovate did build a corrupted dependency tree.

**Comment by pi0** [comment]
Hi. It was probably NPM cdn propagation.
