### ISSUE TITLE
$http in asyncData causes page to not be generated

### ISSUE THREAD

**Issue by pat-lego** [nuxt/nuxt.js#8453]
### Versions

-  "nuxt": "^2.14.9"
- node: v12.16.3

### Reproduction
https://github.com/pat-lego/io.github.vm.patlego.website/tree/feature/http
The generation of /profile/blogs fails since it cannot find $http within the asyncData function.

### Steps to reproduce
Run 
cd io.github.vm.patlego.website/website/website.ui/src/main/resources/website.ui
npm install
npm run generate

### What is Expected?

The /profile/blogs page has not been generated due to an issue with the asyncData function not being able to find some parameters in $http.

The profile/blogs page should of been generated.

### What is actually happening?

The page should be built but the page is skipped due to the following error:

**Comment by danielroe** [comment]
This is probably a question to raise at https://github.com/nuxt/http/issues instead. Just a note - your steps to reproduce don't work (missing files in your repo?) so I was unable to test.
