### ISSUE TITLE
Fallback Routes do not evaluate @click bindings

### ISSUE THREAD

**Issue by lcanizzo** [nuxt/nuxt.js#8455]
### Versions

- nuxt: 2.14.7 
- node: 12.18.3

### Reproduction
clone [This Repo](https://github.com/lcanizzo/nuxt-starter__generate-fallback-issue)
Run: 
```
npm install
npm run generate && npm run serve
```

### Steps to reproduce
Once viewing the generated example, go to the `/404` route and click the external link. Note the console log.
Navigate via the url to a route that does not exist, ex `/hey`. The 404 page is used as a fallback. Click the same external link and note the @click handler is not evaluated.

### What is Expected?
Fallback pages should behave the same as the page they fall back to.

### What is actually happening?
Fallback pages are not binding click events

**Comment by climba03003** [comment]
You should use ```@click.native``` instead of ```@click.prevent```.
The main reason is that the event emited from ```<a>``` is a native event. ```@click.prevent``` will not work with the native event.

More info on [here](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components)

**Comment by lcanizzo** [comment]
Using `@click.native` or `@click.native.prevent` results in failure to call the handler on the 404 page itself or the fallback version of the page.

I don't believe .native is necessary on a generic html element (non-component). My understanding is that .native means “apply to the element (a link) the component creates.”

**Comment by lcanizzo** [comment]
**For Clarification**
The issue is that when running generate with `fallback: true`, the page instance is not binding event handlers _when it is an undefined route_ (as opposed to going directly to the `/404` page as mentioned in the description).
