### ISSUE TITLE
Missing BigInt support in nuxt.config.publicRuntimeConfig

### ISSUE THREAD

**Issue by martijnsmitt** [nuxt/nuxt.js#8456]
### Versions

- nuxt: v2.14.10
- node: v12.19.0

### Reproduction
Code sandbox: https://codesandbox.io/s/bigint-hdtjk

<details open>
<summary>No bigint support</summary>
<br>

I'm trying to retrieve an environment variable from a .env file and use it in a custom plugin. But everytime I use a big number the number gets altered and the plugin works different than expected. What is the correct way to set a config var in a Nuxt application when dealing with such big numbers?
```javascript
  publicRuntimeConfig: {
    TEST_ID_ONE: 1139716611917917221, // converts to small int
    TEST_ID_TWO: "1139716611917917221",
    TEST_ID_THREE: 1139716611917917221n, // works in console.log, but not after render?
    TEST_ID_FOUR: "1139716611917917221n", // returns string ending with `n`
    TEST_ID_FIVE: process.env.TEST_ID,
    TEST_ID_SIX: process.env.TEST_ID_STRING
  }
```

Extra information provided bij VScode: Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers.ts(80008)
But unfortunately this didn't help in my case.
</details>

### Steps to reproduce
Check the codesandbox: https://codesandbox.io/s/bigint-hdtjk

### What is Expected?
That BigInts are supported in the config file and remain the same value

### What is actually happening?
The number variable gets altered to a different number.

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt.js/issues/8317#issuecomment-723557482 for a workaround.
