### ISSUE TITLE
V2.14.10, statically generated router.base root path error.

### ISSUE THREAD

**Issue by xldsdr124** [nuxt/nuxt.js#8457]
### Versions

- nuxt: v2.14.10
- node: v14.15.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
 this is part of my configuration:
`{
    ssr: false,
    router: {
        mode: "hash",
        base: "./"
    },
}`

Next execute "yarn run build"

### What is Expected?
The root path of the dist/index.html script should point to router.base.

### What is actually happening?
Upgrade from 2.14.9 to 2.14.10, build output static website, dist/index.html script root path always points to "/".

**Comment by pi0** [comment]
Hi. Thanks for report. This should be resolved with [v2.14.11](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.11).

**Comment by xldsdr124** [comment]
> Hi. Thanks for report. This should be resolved with [v2.14.11](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.11).

I confirm that this problem still exists in 2.14.11.

**Comment by maximilianschmid** [comment]
Problem still exists in 2.14.11

**Comment by fuxianwei** [comment]
Problem still exists in 2.14.11

**Comment by pi0** [comment]
Would you please try [v2.14.12](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.12)?

**Comment by maximilianschmid** [comment]
v2.14.12 works, all my tests green again. THX!
