### ISSUE TITLE
v2.14.10 relative nuxt-link goes always to root /

### ISSUE THREAD

**Issue by silvio-e** [nuxt/nuxt.js#8459]
### Versions

- nuxt: v2.14.10
- node: v12.19.1

### Steps to reproduce

Create a relative link on a sub page like `<nuxt-link to="test">To test page</nuxt-link>`

### What is Expected?

The link should go to `/subpage/test`

### What is actually happening?

it goes to `/`

I guess related to #8457

**Comment by evanlegamer** [comment]
same when we are on /subpage

 `<nuxt-link to="?page=1">To test page</nuxt-link>`

it goes to /?page=1 instead of /subpage/?page=1

however  this `<nuxt-link  :to="{ query: { page: 1 } }"> To test page</nuxt-link>`
**Works** as expected

**Comment by pi0** [comment]
Hi. Thanks for report. This should be resolved with [v2.14.11](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.11).

**Comment by silvio-e** [comment]
Can confirm that this IS resolved! Thanks! :)
