### ISSUE TITLE
Disabling Strict Mode in Dev Does Not Work

### ISSUE THREAD

**Issue by brandonaaskov** [nuxt/nuxt.js#8461]
### Versions

- nuxt: latest
- node: LTS

### Reproduction

I have a basic store file, and an action mapped on the homepage. Here's the relevant snippets:

```js
// store/index.js
const state = () => ({ items: [] })

const actions = {
  async showStrictModeProblem ({ state }) {
    state.items = ['this should not throw an error']
  }
}

export const strict = false
export default { state, actions, mutations: {}, getters: {} }
```

```js
// pages/index.js
import { mapActions } from 'vuex'

export default {
  methods: {
    ...mapActions({ showStrictModeProblem: 'showStrictModeProblem' })
  },
  mounted () {
    this.showStrictModeProblem()
  }
}
```

You can see the bug clear as day here: https://codesandbox.io/s/nuxt-strict-mode-bug-gzeqh?file=/store/index.js

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Follow the instructions in the docs: https://nuxtjs.org/docs/2.x/directory-structure/store#vuex-strict-mode

### What is Expected?
I should be able to change state in a store without running a mutation.

### What is actually happening?
Nuxt/Vuex throws an error saying "do not mutate vuex store state outside mutation handlers."

**Comment by brandonaaskov** [comment]
@danielroe nowhere in the docs does it specify that you need to export each part of the store separately for that to work. I don't understand why that's the case either, but ideally that could be in the docs so some pour soul in the future doesn't have to find this issue response.

**Comment by danielroe** [comment]
@brandonaaskov PRs are welcome :heart:

**Comment by brandonaaskov** [comment]
Lol I definitely saw that coming. I'm nearing the end of a long work day but I promise I'll do this soon. This shall remain a tab in Chrome until it's done (so many tabs).
