### ISSUE TITLE
Custom API endpoint, Unable to build

### ISSUE THREAD

**Issue by MilesWuCode** [nuxt/nuxt.js#8464]
I followed the document to build

https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-servermiddleware#custom-api-endpoint
"A server middleware can also extend Express. This allows the creation of REST endpoints."
Cannot use express, 

![截圖 2020-12-10 下午9 19 00](https://user-images.githubusercontent.com/1192835/101777390-604a9600-3b2d-11eb-857a-edc3851ce1bc.png)

**Comment by danielroe** [comment]
@MilesWuCode Would you share your code? You can create a minimal reproduction at https://template.nuxtjs.org/

**Comment by MilesWuCode** [comment]
> @MilesWuCode Would you share your code? You can create a minimal reproduction at https://template.nuxtjs.org/

https://codesandbox.io/s/fancy-water-5nly6?file=/middleware/rest.js

![Uploading 截圖 2020-12-10 下午9.40.14.png…]()
