### ISSUE TITLE
Are getters supported in modules mode?

### ISSUE THREAD

**Issue by briangonzalez** [nuxt/nuxt.js#848]
I don't see them mentioned here. Any advice would be much appreciated.

**Comment by alexchopin** [comment]
Yes they are supported, we don't mention them because it's like `mutations` or `actions` cases.
```js
export const getters = {}
```

**Comment by briangonzalez** [comment]
I guess they're a little awkward to interact with from within `store/index.js`

```js
export const getters = {
  foo: state => {
    return 'bar'
  }
}

export const actions = {
  async DO_STUFF ({ dispatch, commit }) {
    console.log(`Doing stuff with: ${getters.foo()}`) // odd that this is called as a function
  }
}
```

Thanks.

**Comment by Lacroute** [comment]
You can access to your module getters through `state.getters['the_module/the_getter']`, ie: `state.getters['user/isAuthenticated']`.
