### ISSUE TITLE
how can I config in nuxt.config.js such app.disable('x-powered-by') or other like this (app.use()) or require('some-middleware-which-need-to-call-with-app-param')(app);

### ISSUE THREAD

**Issue by Mitch-i** [nuxt/nuxt.js#8481]
how can I fully configure express app in nuxt.config.js such moments like
app.disable('x-powered-by') 
app.use()
or require('some-middleware-which-need-to-call-with-app-param')(app);

To be possible to fully config, import modules in nuxt.js.config file (all what we write in app.js of standard express for example app).

Fully config, import modules in nuxt.js.config file (all what we write in app.js of standard express for example app).

**Comment by danielroe** [comment]
@
