### ISSUE TITLE
Event handling in different components ($emit and $on)

### ISSUE THREAD

**Issue by thecodr** [nuxt/nuxt.js#849]
I have a very simple use case.
Emit an event in one component and listen to that event in another component.
In component1's `methods` block, I am using this piece of code
```
this.$emit('deletedchip')
```
In component2's `mounted` block, I am using this piece of code
``` 
this.$on('deletedchip', function(){
//Do something
}) 
```
Event is being emitted but the listener part in component2 is not working. Is there any specific way of dealing this in nuxtjs ?

**Comment by SharadKumar** [comment]
You can use a EventHub to listen these events.

--
Sharad

On Jun 7, 2017, at 5:03 AM, thecodr <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a very simple use case.
Emit an event in one component and listen to that event in another component.
In component1's methods block, I am using this piece of code
this.$emit('deletedchip')
In component2's mounted block, I am using this piece of code
this.$on('deletedchip', function(){ //Do something })
Event is being emitted but the listener part in component2 is not working. Is there any specific way of dealing this in nuxtjs ?

**Comment by piyushchauhan2011** [comment]
Are the two components - `component1` and `component2` are defined under `pages` directory ? @thecodr

**Comment by thecodr** [comment]
@piyushchauhan2011 Yes. Both the components are defined under `pages` directory. 
@SharadKumar Do you have any reference to EventHub usage in nuxtjs please ? That would really help. At the moment I could find [EventHub npm package](https://www.npmjs.com/package/EventHub) but I am not sure if we were talking about the same eventhub.

**Comment by tforssander** [comment]
@thecodr Check out [Understanding Components Communication in Vue 2.0](http://taha-sh.com/blog/understanding-components-communication-in-vue-20) on how to create an eventHub that @SharadKumar is talking about.

**Comment by thecodr** [comment]
I followed that tutorial and here is my code 
I created a plugin
** Event Hub Plugin **
```
import Vue from 'vue'
export default new Vue()
```
**Component 1**
```
import eventHub from '~plugins/event-hub'
export default {
  methods: {
    inputChanged () {
        eventHub.$emit('removeposition', { something: 'yes' })
      }
    }
  }
}
```
**Component 2** 
```
import eventHub from '~plugins/event-hub'
export default {
  props: ['filter'],
  data () {
    return {
      position: {
        value: 100
      }
    }
  },

  mounted () {
    eventHub.$on('removeposition', function (filter) {
      console.log('I am listening : ', filter, this.position.value)
    })
  },

  }
}
```
I am not able to access `this.position.value` in the component. The following error is thrown
`Uncaught TypeError: Cannot read property 'value' of undefined`

Am I missing something here ?

**Comment by pi0** [comment]
@thecodr The problem is that you may have to bind filter function to `this` instance:
```js
   eventHub.$on('removeposition', (function (filter) {
      console.log('I am listening : ', filter, this.position.value)
    }).bind(this))
```
Or simply use arrow functions to keep context:
```js
   eventHub.$on('removeposition', filter => {
      console.log('I am listening : ', filter, this.position.value)
    })
```

**Comment by pi0** [comment]
Also about hub pattern, there won't even needed an extra plugin thing, (i i remind) somewhere in Vue docs it is adviced to simply use top most component as eventhub :) Like this: 
```js
// Input changed
`this.$root.$emit('removeposition', { something: 'yes' })`

// Component 2
`eventHub.$on('removeposition', filter => { })`

**Comment by thecodr** [comment]
@pi0 That solved my problem. @SharadKumar @piyushchauhan2011 @tforssander Thanks all for your help.
