### ISSUE TITLE
both nuxtServerInit and asyncData was called twice

### ISSUE THREAD

**Issue by bahung1221** [nuxt/nuxt.js#8491]
Hi, I just realized that `asyncData` and `nuxtServerInit` was called twice (two time for asyncData and two time for nuxtServerInit).
I tried on nuxt v2.14.6 and nuxt 2.14.11 (latest) but no luck.
I was successful to reproduce this behaviour on new `create nuxt app` created by command `npx create-nuxt-app new-nuxt`.
You can check it on my reproduce repository below.

**Additional**: I tried both dev run and production build.

### Versions

- nuxt: tried 2.14.6 and 2.14.11 
- node: v12.14.0

### Reproduction
Reproduce repo: https://github.com/bahung1221/nuxt-bug-reproduce

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
- `npx create-nuxt-app new-nuxt`.
- Add asyncData to `pages/index.vue`.
- Try to console log anything.

### What is Expected?
`nuxtServerInit` should be called only one for each request, I normally get user data from API server through nuxtServerInit so it doesn't necessary to get the same data two times for each page load.

### What is actually happening?
`nuxtServerInit` and `asyncData` was called twice.

**Comment by danielroe** [comment]
@bahung1221 Thank you for putting the effort in to create a reproduction. However, I'm not able to reproduce what you describe: see https://codesandbox.io/s/github/bahung1221/nuxt-bug-reproduce?file=/pages/index.vue

**Comment by bahung1221** [comment]
Hi @danielroe , thanks for your check, I don't know why it doesn't occur on sandbox, but it really occurred in my environment. Can you please help to clone my reproduce repository and check it again?
Additionally, I'm using macOs 11.0.1 with node v12.14.0 (nvm).

![Screen-Recording-2020-12-15-at-1](https://user-images.githubusercontent.com/27690861/102210950-724d7f80-3f05-11eb-90a3-0bf67972c555.gif)

**Comment by bahung1221** [comment]
I found that my `rss chrome extension` did that call with the same request URL, it even doesn't show any request log in network tab, just disable it and everything is ok now.

I'm so sorry for wasted your time,
Thanks.
