### ISSUE TITLE
Having "https:/" in my url causes internal NodeJS error

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt.js#8493]
Hey folks, whenever there's a `https:/` in my URL, I get this error (instead of my 404 page):
Invalid URL: /https:/

```
next@183:5
internal/url.js:258:9
onParseError
internal/url.js:334:5
new URL
node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:2106:15
parseURL
node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:2110:56
normalizeURL
node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4436:25
VueRenderer.renderRoute
node_modules/@nuxt/server/dist/server.js:918:38
Server.renderRoute
node_modules/@nuxt/server/dist/server.js:158:26
nuxtMiddleware
node_modules/connect/index.js:239:7
call
node_modules/connect/index.js:183:5
next
node_modules/serve-placeholder/src/index.js:29:16
servePlaceholderMiddleware
node_modules/connect/index.js:239:7
call
```

**Comment by gkatsanos** [comment]
Thank you @danielroe. I struggled thinking it's coming from our app but I realized it's something from core. By the way any part of the URL will have the same result, even as a part of a query (as redirect query for example)

**Comment by pi0** [comment]
Hi @gkatsanos thanks for reporting. Would you please try [v2.14.12](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.12)?

**Comment by gkatsanos** [comment]
Thanks guys! amazing speed !
