### ISSUE TITLE
Failed to construct URL

### ISSUE THREAD

**Issue by mfrascati** [nuxt/nuxt.js#8497]
### Versions

- nuxt: 2.14.11 (but I suppose every version > 2.14.8 is affected)

### Reproduction

I have a return URL from Google oAuth redirect like the following:

`https://mydomain.com/oauth/google#state=RHo0uoakf_VDi&access_token=ya29.a-CUT-2E2wlw&token_type=Bearer&expires_in=3598&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&prompt=none`

### What is actually happening?

<img width="485" alt="Schermata 2020-12-16 alle 10 03 44" src="https://user-images.githubusercontent.com/2734747/102331468-2fce8600-3f8b-11eb-8bf6-9660203fb98b.png">

Downgrading to 2.14.8 solved the issue. I see there was a lot going on with routing in the last 3 minor releases, maybe this is an unhandled case, or hashes related?

**Comment by pi0** [comment]
Hi @mfrascati thanks for reporting. Would you please try [v2.14.12](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.12)?

**Comment by mfrascati** [comment]
@pi0 yep, now it works as expected, thanks!
