### ISSUE TITLE
FATAL  Package subpath './package.json' is not defined by "exports" Error

### ISSUE THREAD

**Issue by GerhardArya** [nuxt/nuxt.js#8498]
I suddenly start receiving this error starting several minutes ago while deploying on Openshift. Before, everything was perfectly fine. The only difference between the build that worked several minutes prior and current build are some minor layout changes and added two functions that had console.log in them, so I'm pretty sure it is not my fault but something with Nuxt, especially the ufo module.

FATAL  Package subpath './package.json' is not defined by "exports" in /usr/src/flipit-frontend/node_modules/@nuxt/ufo/package.json
  |  
  | at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
  | at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
  | at resolveExports (internal/modules/cjs/loader.js:424:36)
  | at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
  | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
  | at Function.Module._load (internal/modules/cjs/loader.js:667:27)
  | at Module.require (internal/modules/cjs/loader.js:887:19)
  | at require (internal/modules/cjs/helpers.js:74:18)
  | at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:618:26)
  | at Builder.validateTemplate (node_modules/@nuxt/builder/dist/builder.js:5674:38)
  | at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5602:12)
  | at async Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:171:7)
  | at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:133:5)
  | at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:105:7)
  | at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2803:7)
  |  

Was there a new version or a change or something a couple minutes ago that could've caused this? Thanks in advance for the help!

**Comment by GerhardArya** [comment]
This is with Nuxt 2.14.12. Since I set my package.json to "^2.0.0"

**Comment by andorfermichael** [comment]
I can confirm this.

**Comment by oiluis** [comment]
Same here!!

**Comment by pi0** [comment]
`yarn upgrade nuxt` or `npm up nuxt` should fix regression.

**Comment by GerhardArya** [comment]
It's works now, thanks @pi0 and team!

**Comment by oiluis** [comment]
Thanks guys !

**Comment by refoxdev** [comment]
"dependencies": {
    "@nuxt/content": "^1.9.0",
    "@nuxtjs/axios": "^5.12.2",
    "@nuxtjs/pwa": "^3.0.2",
    "core-js": "^3.6.5",
    "nuxt": "^2.14.12"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^3.4.0"
  }

Getting this error!!

> ERROR  ServerMiddleware Error: Cannot use import statement outside a module                                                         02:32:04
> 
>   (function (exports, require, module, __filename, __dirname) { import { withoutTrailingSlash, withTrailingSlash } from '@nuxt/ufo'
>   ^^^^^^
>   
>   SyntaxError: Cannot use import statement outside a module
>   at new Script (vm.js:99:7)
>   at createScript (vm.js:249:10)
>   at Object.runInThisContext (vm.js:297:10)
>   at wrapSafe (internal/modules/cjs/loader.js:1027:15)
>   at Module._compile (internal/modules/cjs/loader.js:1087:27)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
>   at Module.load (internal/modules/cjs/loader.js:972:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:872:14)
>   at Module.require (internal/modules/cjs/loader.js:1012:19)
>   at require (internal/modules/cjs/helpers.js:72:18)
>   at Resolver.requireModule (node_modules\@nuxt\core\dist\core.js:618:26)
>   at Server._requireMiddleware (node_modules\@nuxt\server\dist\server.js:826:39)
>   at Server._normalizeMiddleware (node_modules\@nuxt\server\dist\server.js:795:38)
>   at Server.resolveMiddleware (node_modules\@nuxt\server\dist\server.js:846:23)
>   at Server.useMiddleware (node_modules\@nuxt\server\dist\server.js:871:36)
>   at Server.setupMiddleware (node_modules\@nuxt\server\dist\server.js:710:12)

**Comment by reslear** [comment]
> "dependencies": {
> "@nuxt/content": "^1.9.0",
> "@nuxtjs/axios": "^5.12.2",
> "@nuxtjs/pwa": "^3.0.2",
> "core-js": "^3.6.5",
> "nuxt": "^2.14.12"
> },
> "devDependencies": {
> "@nuxtjs/tailwindcss": "^3.4.0"
> }
> @pi0
> Getting this error!!
> 
> > ERROR  ServerMiddleware Error: Cannot use import statement outside a module                                                         02:32:04
> > (function (exports, require, module, __filename, __dirname) { import { withoutTrailingSlash, withTrailingSlash } from '@nuxt/ufo'
> > ^^^^^^
> > SyntaxError: Cannot use import statement outside a module
> > at new Script (vm.js:99:7)
> > at createScript (vm.js:249:10)
> > at Object.runInThisContext (vm.js:297:10)
> > at wrapSafe (internal/modules/cjs/loader.js:1027:15)
> > at Module._compile (internal/modules/cjs/loader.js:1087:27)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
> > at Module.load (internal/modules/cjs/loader.js:972:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:872:14)
> > at Module.require (internal/modules/cjs/loader.js:1012:19)
> > at require (internal/modules/cjs/helpers.js:72:18)
> > at Resolver.requireModule (node_modules@nuxt\core\dist\core.js:618:26)
> > at Server._requireMiddleware (node_modules@nuxt\server\dist\server.js:826:39)
> > at Server._normalizeMiddleware (node_modules@nuxt\server\dist\server.js:795:38)
> > at Server.resolveMiddleware (node_modules@nuxt\server\dist\server.js:846:23)
> > at Server.useMiddleware (node_modules@nuxt\server\dist\server.js:871:36)
> > at Server.setupMiddleware (node_modules@nuxt\server\dist\server.js:710:12)

ping respected @pi0 look here please, thx)
