### ISSUE TITLE
Server HTML generate without style

### ISSUE THREAD

**Issue by lwswnnscrm** [nuxt/nuxt.js#8502]
Hi, when i go to my website and look in network doc, i see html without style. Can i get there page with style? 
Build config:
 ```
{
  optimizeCss: true,
  extractCSS: true,
  minimize: true,
  parallel: true,
  ...(!isDev && {
    extractCSS: {
      ignoreOrder: true,
    },
  }),
  ...(!isDev && {
    html: {
      minify: {
        collapseBooleanAttributes: true,
        decodeEntities: true,
        minifyCSS: true,
        minifyJS: true,
        processConditionalComments: true,
        removeEmptyAttributes: true,
        removeRedundantAttributes: true,
        trimCustomFragments: true,
        useShortDoctype: true,
      },
    },
  }),
  splitChunks: {
    layouts: true,
    pages: true,
    commons: true,
  },
  optimization: {
    minimize: !isDev,
    splitChunks: {
      chunks: 'all',
      automaticNameDelimiter: '.',
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.(css|vue)$/,
          chunks: 'all',
          enforce: true,
        },
      },
    },
  },
  publicPath: 'https://test-cdn.com/ss-front',
  ...(!isDev && {
    vendor: [
      'bootstrap-vue/nuxt',
      '@nuxtjs/axios',
      '@nuxtjs/pwa',
      '@nuxtjs/device',
      'cookie-universal-nuxt',
      'nuxt-i18n',
      'nuxt-gmaps',
    ],
  }),
  transpile: ['vee-validate/dist/rules'],
  filenames: {
    app: ({ isDev }) => isDev ? '[name].js' : '[name].[contenthash].js',
    chunk: ({ isDev }) => isDev ? '[name].js' : '[name].[contenthash].js',
    css: ({ isDev }) => isDev ? '[name].css' : '[name].[contenthash].css',
  },
```
mode: universe. 

### Versions

- nuxt: 2.14.11
- node: local - 14.15.1, server - 13.1, has this prooblem in booth env.

In index.ssr.html after build 
```
<!doctype html>
<html {{ html_attrs }}>
  <head {{ head_attrs }}>
    {{ HEAD }}
  </head>
  <body {{ body_attrs }}>
    {{ APP }}
  </body>
</html>
```

Can i have in doc page with style?

**Comment by lwswnnscrm** [comment]
https://codesandbox.io/s/heuristic-waterfall-8ybke?file=/nuxt.config.js
Adn in github - https://github.com/lwswnnscrm/test-nuxt-style-bug
if you build this project and start you can see in network doc this: 
![image](https://user-images.githubusercontent.com/22519996/102471269-13534c00-4066-11eb-91e9-3ff744dcabba.png) , but in browser it look goog https://monosnap.com/file/tOT1SMmSTONYUNCGEolxsLACeMQ97J

**Comment by lwswnnscrm** [comment]
@Atinux

**Comment by Atinux** [comment]
Did you run nuxt generate with target: 'static'?

All the generated files will be in the dist/ directory

**Comment by lwswnnscrm** [comment]
Yes, i use nuxt generate with target: static: https://monosnap.com/file/SK9CJCOf1aqWrnNxg2UZh8aT6WKUeV . And with dynamic project have same problem.

**Comment by lwswnnscrm** [comment]
In my work project you can see same problem: https://ssfront-dev.ssyii.com/

**Comment by lwswnnscrm** [comment]
@Atinux update information, when i use lighthouse test in chrome, and start test 2g connect to site, i see page without style. Link to page: https://ssfront-dev.ssyii.com/

**Comment by lwswnnscrm** [comment]
@danielroe you mean i can't have separate css files and style in load doc in network, right?
