### ISSUE TITLE
FATAL A lock with id 'build' already exists on {{siteurl}}/.nuxt

### ISSUE THREAD

**Issue by Skylercrane23** [nuxt/nuxt.js#8504]
### Versions
nuxt- ^2.14.11
node -14.1.0

### Reproduction
Using Laravel forge as our deploy tool since we use Laravel as an api. Deploying recently has caused this error to appear. Looked into Nuxt docs and can't find anything, have tried deleting node modules and package.lock and redeploying. Still nothing. Have tried deleting the site and starting fresh and still same thing. Locally I can build and our server versions of Nuxt, npm, and node all match. Building local `npm run build-dev` works fine, only when deploying I get the FATAL error. Can't find where this lock with id 'build' exists or if this is even a Nuxt error or more a Laravel Forge error. Any info greatly appreciated. 

### What is Expected?
Should deploy with no errors

### What is actually happening?
deploys with `FATAL A lock with id 'build' already exists on {{siteurl}}/.nuxt`

**Comment by Skylercrane23** [comment]
> @Skylercrane23 The lockfile lives in `<rootDir>/node_modules/.cache/nuxt` - just delete that folder and you should be good to go. More info [here](https://github.com/nuxt/nuxt.js/blob/a2495a68736f9af96cd25209a948beb1ca665d4d/packages%2Futils%2Fsrc%2Flocking.js#L19-L23).

Do you know what causes this issue?

**Comment by Skylercrane23** [comment]
Hmmm, yeah that looks like it wasn't the issue. Still running into the same thing. Looks like Laravel Forge is showing it being deployed 3 times in a row. @danielroe anything within nuxt that would cause a build to be triggered several times?

**Comment by danielroe** [comment]
@Skylercrane23  I would recommend reading through your deploy logs to find out why three are being triggered at once - that's not Nuxt's doing.

I think it is likely an issue with your deployment configuration (or Forge's). I'd recommend joining the Nuxt Discord at https://discord.nuxtjs.org - and ask in #deployments.

**Comment by beigiz** [comment]
I just deleted the .nuxt  folder and that solved the problem

**Comment by danielroe** [comment]
I'm going to close this as it's unclear that this is a Nuxt issue rather than an issue with the deployment. But if you find any more info please feel free to post and I'll happily reopen.

**Comment by PeteJStewart** [comment]
I had the same issue, and can confirm removing `<rootDir>/node_modules/.cache/nuxt` and `<rootDir>/.nuxt` resolved the issue.
I feel this is more a deployment / forge issue, rather than a Nuxt issue though.
I believe my deployment had failed for some other reason, and then it had not cleared up properly, and therefore left these files behind.

None of my deployment config had changed, so I suspect it was just an unusual error such as a network failure that caused the initial issue.
