### ISSUE TITLE
Build error with nuxt-edge 2.14.13 - Can't resolve a CSS @font-face url.

### ISSUE THREAD

**Issue by drewbaker** [nuxt/nuxt.js#8508]
Using `"nuxt-edge": "^2.14.13-26803446.5318172",` my build fails with the below error. Was working fine with latest `nuxt` version previously. 

My nuxt config has this:

```
    css: [
        "~/styles/css-variables.scss",
        "~/styles/global.scss",
        "~/styles/transitions.scss",
        "~/styles/fonts.css",
    ],
```

```

 ERROR  in ./styles/fonts.css                                                               friendly-errors 13:37:43


Module build failed (from ./node_modules/css-loader/dist/cjs.js):                           friendly-errors 13:37:43
Error: Can't resolve '/fonts/AVENIRNEXTLTPRO-CN.eot' in '/Users/drew/Sites/loganindustry-frontend/styles'
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/drew/Sites/loganindustry-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:1
0), <anonymous>:15:1)
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/drew/Sites/loganindustry-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:1
0), <anonymous>:15:1)
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/drew/Sites/loganindustry-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:1
0), <anonymous>:27:1)
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/drew/Sites/loganindustry-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:1
0), <anonymous>:16:1)
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/drew/Sites/loganindustry-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:1
0), <anonymous>:16:1)
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/drew/Sites/loganindustry-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:1
0), <anonymous>:16:1)
    at /Users/drew/Sites/loganindustry-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
                                                                                            friendly-errors 13:37:43
 @ ./styles/fonts.css 4:14-157 14:3-18:5 15:22-165
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=
%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

It's my first time using `nuxt-edge` so I'm not sure if I'm doing it right, but here is my package dependencies if that helps:

```
"dependencies": {
        "@nuxtjs/dotenv": "^1.4.1",
        "@vimeo/player": "^2.14.1",
        "cheerio": "^1.0.0-rc.3",
        "core-js": "^3.6.5",
        "intrinsic-scale": "^3.0.4",
        "lodash": "^4.17.20",
        "nuxt-edge": "^2.14.13-26803446.5318172",
        "youtube-player": "^5.5.2"
    },
    "devDependencies": {
        "@babel/plugin-proposal-object-rest-spread": "^7.11.0",
        "@nuxtjs/sitemap": "^2.4.0",
        "@nuxtjs/storybook": "^2.2.1",
        "@nuxtjs/style-resources": "^1.0.0",
        "eslint": "^7.9.0",
        "eslint-plugin-vue": "^6.2.2",
        "graphql": "^15.3.0",
        "graphql-tag": "^2.11.0",
        "node-sass": "^4.14.1",
        "nodemon": "^2.0.4",
        "nuxt-graphql-request": "^3.1.1",
        "prettier": "^2.1.2",
        "prettier-eslint": "^11.0.0",
        "sass-loader": "^9.0.3",
        "vue-svg-loader": "^0.16.0",
        "vue-template-compiler": "^2.6.12",
        "webfontloader": "^1.6.28"
    }
```

**Comment by pi0** [comment]
Hi @drewbaker. I think correctly installed nuxt-edge (to ensure can also remove `node_modules` and lock files) but this seems a regression with node10 dependency updates (#8346). /cc @clarkdo

**Comment by drewbaker** [comment]
OK, so just update my Node version? Will try that now.

**Comment by clarkdo** [comment]
I think so, it looks css loader doesn’t resolve the font file path, @drewbaker can you provide the font url in your css file and file path in you project?

**Comment by drewbaker** [comment]
OK, so I just tried updated my node engine in my `package.json`:

```
{
    "engines": {
        "node": "15.4.0"
    },
}
```

Then deleted `package-lock.json` and my `node_modules` folder, and then `npm install`. Still getting same error.

`fonts.css` is at `~/styles/fonts.css` and font files live at `~/static/fonts/{filename}.{ext}`. This works fine with production `nuxt`.

Also see screenshot for folder and file paths.

<img width="1049" alt="Screen Shot 2020-12-17 at 2 14 52 PM" src="https://user-images.githubusercontent.com/475015/102492622-3dab0680-4072-11eb-831d-ee090b36b91d.png">

**Comment by drewbaker** [comment]
FYI also tried changing font URL's to this `src: url("~/fonts/AVENIRNEXTLTPRO-CN.eot");` and same error.

**Comment by drewbaker** [comment]
OK, got it to work like this: `src: url("~/static/fonts/AVENIRNEXTLTPRO-CNIT.eot");` 

That goes against what is described in docs though right? Or are you changing that so we should use `/static` now?

**Comment by clarkdo** [comment]
I think using relative path would be better, I’ll take a look if there’s anyway to cover this breaking change from css-loader.

**Comment by clarkdo** [comment]
As css-loader won’t resolve absolute path, so your original should work, I’ll check it, can you try if it works in prod mode with build and start?

**Comment by drewbaker** [comment]
OK going with aliases path is more consistent with the rest of Nuxt anyway. I will do that for all new sites.

Can't find the docs I was thinking about anymore. But it would be worth mentioning it here: https://nuxtjs.org/docs/2.x/directory-structure/static

Noticed that this says to put fonts into `assets`. That was not what I would have expected. Font file can be multiple megabytes, wouldn't this result in big webpack bundles? Or am I not understanding what `/assets` does?
https://nuxtjs.org/docs/2.x/directory-structure/assets#webpacked

Love that you guys clarified the use of `~` and `@`. That was always confusing.
https://nuxtjs.org/docs/2.x/directory-structure/assets#aliases

**Comment by clarkdo** [comment]
Re the bundle size, font file will only be bundled if it’s smaller than a specific size which is good for reducing http requests amount for small files.

We’ll definitely keep improving the doc, thanks for the suggestion and issue report.

**Comment by drewbaker** [comment]
Noticed that `~/assets/image.png` doesn't work in CSS, you have to do `~assets/image.png`. Not sure if this is by design?

**Comment by danielroe** [comment]
@drewbaker Yes, that is how it works. See:
- https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules
- https://nuxtjs.org/docs/2.x/directory-structure/assets#webpack

**Comment by drewbaker** [comment]
OK thanks. That is admittedly not very intuitive, but good to know.
