### ISSUE TITLE
supporting runtime baseURL/publicPath

### ISSUE THREAD

**Issue by rotemrevivo91** [nuxt/nuxt.js#8509]
### Description

Nuxt doesn't allow the publicPath (CDN url) to be overridden at run time - it's baked into the manifest at
build time.  This hook intercepts the VueRenderer when it has loaded the manifest and updates the publicPath
to the current env value.

The problem is that i have a single build (i.e 1 docker image) that is used on multiple environments. Each user should be able to specify their own router base as an .env variable and just run the container without the need to rebuild the image.
Nuxt resources are then can't be found (nuxt .js files).

When building and running for the first time (nuxt build && nuxt start) everything works normally. Then changing the BASE value in the .env file breaks the app.

### Solution description

Setting the baseURL anew on runtime

### Describe alternatives you've considered
.env:
```
BASE=\rotem\
```
nuxt.config.js:
```
  publicRuntimeConfig: {
    baseURLSubDirectory: process.env.BASE_URL_SUB_DIRECTORY,
  },
  router: {
    base: process.env.BASE_URL_SUB_DIRECTORY
  },
  plugins: [
    {
      src: '@/plugins/cdn.js',
      ssr: false
    },
  ],
  hooks: {
    /* Nuxt doesn't allow the publicPath (CDN url) to be overridden at run time - it's baked into the manifest at
    ** build time.  This hook intercepts the VueRenderer when it has loaded the manifest and updates the publicPath
    */ to the current env value.
    render: {
      resourcesLoaded(resources) {
        const path = `${process.env.BASE_URL_SUB_DIRECTORY}_nuxt/`
        resources.clientManifest && (resources.clientManifest.publicPath = path)
        resources.modernManifest && (resources.modernManifest.publicPath = path)
        resources.serverManifest && (resources.serverManifest.publicPath = path)
      }
    }
  }
```
plugins\cdn.js:
```
export default function({$config}) {
  if (process.client) {
    __webpack_public_path__ = `${$config.baseURLSubDirectory}_nuxt/`
  }
}
```
Build nuxt for production and then change .env:
```
BASE=\xrotem\
```
Then run the nuxt app.
The code replaces all resources on run-time! which is important but still i get a 404 page even though nuxt is able to find all the needed resources.

**Comment by pi0** [comment]
Thanks for making issue @rotemrevivo91. It is indeed an important feature that we can have with runtimeConfig. Workaround seems good but it can be easily broken by internal changes of either vue or vue-bundle-renderer... 

Still some modes like static target cannot support as we directly use inside templates.

**Comment by rstormsf** [comment]
here is how we got it: 
1. write redirect.js file in `/static` folder and include it in `nuxt.config.js` in `head`
```js

function addScript(src) {
  const s = document.createElement('script')
  s.setAttribute('src', src)
  document.body.appendChild(s)
}

setTimeout(() => {
  const ipfsPathRegExp = /^(\/(?:ipfs|ipns)\/[^/]+)/
  const ipfsPathPrefix = (window.location.pathname.match(ipfsPathRegExp) || [])[1] || ''
  if (ipfsPathPrefix) {
    const scripts = [...document.getElementsByTagName('script')]

    for (let i = 0; i < scripts.length; i++) {
      if (scripts[i].src) {
        const source = new URL(scripts[i].src)
        if (source.pathname.includes('redirect.js')) {
          console.log('skip redirect')
          continue
        }
        console.log('Loading', source.pathname)
        const newSource = window.location.href.slice(0, -1) + source.pathname
        addScript(newSource)
      }
    }
    console.log('Finished')
  }
}, 10000)
```
this will rewrite all script tags to load from different path

2. turn off chunks: 
```js
  build: {
   splitChunks: {
      layouts: false,
      pages: false,
      commons: false
    }
}
```
3. enable plugin
```js
/* eslint-disable camelcase, no-undef */
export default (context, inject) => {
  const ipfsPathRegExp = /^(\/(?:ipfs|ipns)\/[^/]+)/
  const ipfsPathPrefix = (window.location.pathname.match(ipfsPathRegExp) || [])[1] || ''

  console.log('plugin __webpack_public_path__', __webpack_public_path__)

  if (ipfsPathPrefix) {
    __webpack_public_path__ = ipfsPathPrefix + '/_nuxt/'

    if (typeof window !== 'undefined') {
      context.app.router.history.base = ipfsPathPrefix || window.location.host
    }
  }

  console.log('plugin __webpack_public_path__', __webpack_public_path__)
}
```


with this our app works fine in root domain + ipfs url
because 
1. it finds the correct `_nuxt` path
2. rewrites js chunks with `__webpack_public_path__` 
3. we had to turn of splitChunks because otherwise generated js file couldn't properly load since it contained incorrect `_nuxt` path in it.

**Comment by rotemrevivo91** [comment]
@rstormsf I can confirm that adding:
```
    if (typeof window !== 'undefined') {
      context.app.router.history.base = $config.baseURLSubDirectory || window.location.host
    }
```
fixed the issue i had!
But all the other steps were not necessary as using nuxt hooks i was able to achieve the same goal, as long as nuxt ssr is set to true:
```
 ssr: true,
 hooks: {
    /* Nuxt doesn't allow the publicPath (CDN url) to be overridden at run time - it's baked into the manifest at
    ** build time.  This hook intercepts the VueRenderer when it has loaded the manifest and updates the publicPath
    ** to the current env value.
    */ 
    render: {
      resourcesLoaded(resources) {
        const path = `${process.env.BASE_URL_SUB_DIRECTORY}_nuxt/`
        resources.clientManifest && (resources.clientManifest.publicPath = path)
        resources.modernManifest && (resources.modernManifest.publicPath = path)
        resources.serverManifest && (resources.serverManifest.publicPath = path)
      }
    }
  }
```
Now i can build the app once and change the the prefix through my .env file as i wish :)
One error that happens (only on page load) but has no real effect as far as i could see is:
```
TypeError: e.options is undefined
NuxtJS 22
        scrollBehavior
        scrollBehavior
        mt
        ue
        ie
        promise callback*ee
        ue
        $nextTick
        mt
        r
        r
        transitionTo
        confirmTransition
        r
        r
        kt
        confirmTransition
        r
        r
        x
        d
        Ut
```
it occurs in one of the chunks.

**Comment by pi0** [comment]
@rstormsf @rstormsf Thanks for sharing solutions. I had to hide them since even if working it is not suggested using workarounds. Thanks for patience 🙏

**Comment by YutaMoriJP** [comment]
@pi0 Hi, so what's the solution for this? 

I am trying to deploy to different environments like `${baseURL}/_00/`, `${baseURL}/_01/`, etc. and it breaks when the URL is dynamic like (_00) but works just fine in plain domains like `${baseURL}`.
