### ISSUE TITLE
Can't manage keep-alive key per page

### ISSUE THREAD

**Issue by paulogr** [nuxt/nuxt.js#8510]
The docs says I can add a key property on my page component to manage the router view key but it doesn't work.

https://nuxtjs.org/docs/2.x/features/nuxt-components#the-nuxt-component

I added a keep-alive on Nuxt component and trying to manage the key per page, because different pages has different keys.

```
export default {
  key(route) {
    return 'my-custom-key-per-page'
  }
}
```

Anyone can help me?
Thanks!

### Versions

- nuxt: v2.14.7
- node: v14.7.0

**Comment by gangsthub** [comment]
My 2 cents: If the component had a `nuxtChildKey` prop, then the `option.key` is not reached, AFAICT:

https://github.com/nuxt/nuxt.js/blob/79440f3ce5b90b39fc1fa68fe1736cac6edae491/packages/vue-app/template/components/nuxt.js#L47-L70
