### ISSUE TITLE
Full static mode 404 error manifest.js on first route change

### ISSUE THREAD

**Issue by jeerbl** [nuxt/nuxt.js#8511]
### Versions

- nuxt: v2.14.8
- node: v12.13.1

### Reproduction

Reproduction: https://www.trackinsight.com/en/, click any SPA link and Chrome console displays:
```
Uncaught SyntaxError: Unexpected token '<'   manifest.js:1
```

`manifest.js` doesn't exist and path returns a 404.

<details open>
<summary>Additional Details</summary>
<br>
Nuxt Config:

    const Fs = require('fs');
    const Path = require('path');
    const Util = require('util');

    const Webpack = require('webpack');
    const FaviconsWebpackPlugin = require('favicons-webpack-plugin');

    const readFile = Util.promisify(Fs.readFile);

    function getPresetName () {
      let preset = process.env.npm_config_preset;         // npm run build --preset=<target>
      preset = preset ||  process.env.BUILD_PRESET || 'local';
      return preset;
    }

    function getServerURL () {
      let serverURL = process.env.npm_config_server_url;  // npm run build --server_url=<server url>
      serverURL = serverURL ||  process.env.SERVER_URL || null;
      if (serverURL) process.stderr.write(`Setting serverURL to '${serverURL}'\n`);
      return serverURL;
    }

    function getBuildPresets (target) {
      process.stderr.write(`Loading presets for ${target}\n`);
      return require(`./presets/${target}.js`);
    }

    export default async function ({ dev, command }) {
      const appRoutes = require('./nuxt.routes').default;
      const languages = require('./src/l10n/languages').map((lang) => lang.path);

      const buildId = new Date().getTime();

      const presetName = getPresetName();
      let presets = getBuildPresets(presetName);

      let serverURL = getServerURL();

      // proxy configuration to bypass CORS when running in local server
      let proxy = {};
      if (presets.useProxy) {
        process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
        presets = {
          ...presets
        };
        serverURL = serverURL || 'https://localhost:8080';
      }

      const config = {
        ssr: !dev,
        srcDir: 'src/',
        loading: false,

        head: {
          title: 'TrackInsight',
          meta: [
            { charset: 'utf-8' },
            { name: 'viewport', content: 'width=device-width, user-scalable=no' }
          ],
          script: [
            // Polyfills
            { src: 'https://polyfill.io/v3/polyfill.min.js?features=es2015%2Ces2016%2Ces2017%2Ces2018%2Ces2019%2Cconsole%2CmatchMedia%2CElement' }
          ],
          link: [
            { rel: 'preconnect', href: 'https://use.typekit.net' },
            { rel: 'preconnect', href: 'https://www.googletagservices.com' }
          ]
        },

        /**
         * Environement variables accessible to the code through process.env.xxx
         */
        env: {
          ...presets,
          serverURL: serverURL
        },

        modules: [
          'nuxt-vuex-router-sync',
          '@nuxtjs/proxy',
          '@nuxtjs/robots'
        ],

        buildModules: [
          '@nuxtjs/axios'
        ],

        hooks: {
          generate: {
            done (generator) {
              if (generator.nuxt.options.generate && generator.nuxt.options.generate.dir) {
                Fs.writeFileSync(Path.join(generator.nuxt.options.generate.dir, 'buildId.json'), JSON.stringify(buildId));
              }
            }
          }
        },

        /**
         * Build configuration
         */
        build: {
          // additional webpack plugins
          plugins: [
            new Webpack.ContextReplacementPlugin(/moment[/\\]locale$/, new RegExp(`(${languages.join('|')})$`))
          ],

          // webpack loaders overrides
          loaders: {
            imgUrl: { esModule: false }
          },
          // additional webpack loaders
          extend (config, { isClient }) {
            if (!dev && !isClient) {
              // minify is disabled by default on the server which is not optimal with lambda
              delete config.optimization;
            }

            config.module.rules.push({
              test: /\.font\.json/,
              type: 'javascript/auto',
              use: [
                'vue-style-loader',
                'css-loader',
                'webfonts-loader'
              ]
            });

            // FaviconsWebpackPlugin must be after HtmlWebpackPlugin
            config.plugins.unshift(
              new FaviconsWebpackPlugin({
                logo: './src/favicon.png',
                inject: true,
                prefix: '[hash].',
                favicons: {
                  appName: 'TrackInsight',
                  icons: {
                    android: false,
                    appleIcon: false,
                    appleStartup: false,
                    coast: false,
                    favicons: true,
                    firefox: false,
                    yandex: false,
                    windows: false
                  }
                }
              })
            );
          },
          postcss: {
            plugins: {
              autoprefixer: {}
            }
          }
        },

        /**
         * robots.txt
         */
        robots: {
          ...presets.robots
        },

        /**
         * Development web server configuration
         */
        server: {
          host: '0.0.0.0',
          port: 8080,
          https: {
            key: await readFile(Path.resolve(__dirname, 'certs/localhost.key')),
            cert: await readFile(Path.resolve(__dirname, 'certs/localhost.crt'))
          }
        },
        proxy: proxy,

        router: {
          extendRoutes (routes, resolve) {
            // remove all the routes infered by nuxt
            routes.splice(0, routes.length);
            // add the ones specified in nuxt.routes.js
            for (var i = 0; i < appRoutes.length; i++) {
              routes.push(appRoutes[i]);
            }
          },

          prefetchLinks: false
        },

        generate: {
          fallback: 'index.html',
          crawler: false,
          routes: []
        },

        storybook: {
          components: true,
          port: 4000,
          stories: [
            '~/components/**/*.stories.js',
            '~/components/**/*.stories.ts',
            '~/components/**/*.stories.mdx'
          ],
          addons: [
            '@storybook/addon-knobs',
            '@storybook/addon-docs'
          ]
        }
      };

      return config;
    }

</details>

### Steps to reproduce
Click any `nuxt-link` and when route changes, app tries to download `manifest.js`.

### What is actually happening?
Error in browser console

**Comment by Timkor** [comment]
Looks like there is not manifest.js and the SPA fallback loads.

**Comment by Atinux** [comment]
@jeerbl can you confirm that a `manifest.js` is generated in your `dist/` directory?

**Comment by jeerbl** [comment]
@Atinux I can confirm that there is none. Just rebuilt and no `manifest.js` is in the `dist/` directory.

**Comment by jeerbl** [comment]
Just did, still no `manifest.js`. Before I was buildind using `nuxt build --target=static` which I believe did the same?

**Comment by jeerbl** [comment]
Actually, let me share my `build` npm goal: `nuxt build --target=static --standalone && nuxt generate --no-build`

**Comment by jeerbl** [comment]
I did make the suggested changes and indeed, the error is not here anymore, no call to `manifest.js` is attempted. This is what we want, right? Or did we want a `manifest.js` generated instead?
