### ISSUE TITLE
Component remounting and refetching data on client side in case of usage async components import

### ISSUE THREAD

**Issue by ikoshele** [nuxt/nuxt.js#8513]
### Versions

- v2.14.6

### Reproduction

https://codesandbox.io/s/crazy-browser-fw1wo?file=/components/ArchiveFetcher.vue

### Steps to reproduce

``` 
data() {
    return {
      fetchedPosts: [],
    };
  },
  components: {
    //CountriesList,
    CountriesList: () => import("~/components/CountriesList"),
  },
  async fetch() {
    if (process.server) {
      let url = "https://jsonplaceholder.typicode.com/posts";
      console.warn(url, "Archive fetching");
      try {
        this.fetchedPosts = await this.$axios.$get(url);
      } catch (err) {
        return this.$nuxt.error({ statusCode: 404, message: err.message });
      }
      console.log(this.fetchedPosts); - return array of posts
    }
  },
  mounted() {
    console.warn(this.fetchedPosts); - return [];
  }, 
```

Async import component and try to use it with server-side data.

### What is Expected?
Expected the same behavior as default components import, without remounting\refetching on the client.

### What is actually happening?
When we use such construction (async components import) - the component is filling with data on the server-side, but then it looks like remounting on the client without any data and trying to fetch it again.
When I import a component in the default way, it works as expected, without losing data on the client.

I hope I describe the issue clearly enough, but let me know if you need any additional info.

**Comment by arikw** [comment]
+1
I'm seeing the exact bug on v2.14.12

**Comment by ilearnjs** [comment]
+1
It seems like imported component should used as root component in the template
@ikoshele as temp solution you can try to wrap countriesList in to div

```
<tempalte>
  <div>
    <countries-list>
      ...
```
