### ISSUE TITLE
Failed to compile (nuxt@1.0.0-alpha4)

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#852]
I use [adonuxt](https://github.com/nuxt/adonuxt). After update nuxt from 0.10.7 to 1.0.0-alpha4 try build.

```
ERROR  Failed to compile with 1 errors                                                                                                                                         15:29:11

This dependency was not found:

* !!vue-style-loader?sourceMap!css-loader?sourceMap!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-54a40582","scoped":false,"hasInlineConfig":true}!sass-loader?sourceMap!../../node_modules/vue-loader/lib/selector?type=styles&index=0!./default.vue in ./resources/layouts/default.vue

To install it, you can run: npm install --save !!vue-style-loader?sourceMap!css-loader?sourceMap!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-54a40582","scoped":false,"hasInlineConfig":true}!sass-loader?sourceMap!../../node_modules/vue-loader/lib/selector?type=styles&index=0!./default.vue
```

**Comment by lucpotage** [comment]
Please install Node Sass and the corresponding Webpack loader:

`npm install --save node-sass sass-loader`

or

`yarn add node-sass sass-loader`

**Comment by cawa-93** [comment]
If the nuxt is dependent on the node-sass and sass-loader, why not include them in dependencies so that they are installed automatically?

**Comment by lucpotage** [comment]
I don't think Nuxt is dependent on node-sass and sass-loader. This message prompts when you have a `lang="scss"` in one of your Vue files (component, layout or page). Is it your case?

**Comment by cawa-93** [comment]
Yes you are right. In one of the files accidentally left `<style lang="scss"></style>`. Thanks
