### ISSUE TITLE
A document must not include more than one “meta” element with a “charset” attribute.

### ISSUE THREAD

**Issue by trollepierre** [nuxt/nuxt.js#8526]
### Versions

- nuxt: "nuxt": "2.14.12", => problem
- node: v12.20.0 -->

 "nuxt": "2.14.5", => no problem
### Reproduction

I think the minimum scenario to reproduce is:
- use last version of nuxt
- nuxt generate (reproduced in static generated app)
- inspect <meta charset='utf-8'> they should be 2 of them. 

<img width="446" alt="Capture d’écran 2020-12-20 à 16 13 51" src="https://user-images.githubusercontent.com/8363334/102716964-84e9ff00-42df-11eb-868f-a613e56387b2.png">

it's needed, my repo: https://github.com/trollepierre/recontact_travel_blog/tree/dev/front

https://github.com/trollepierre/recontact_travel_blog/blob/dev/front/nuxt.config.js

### Steps to reproduce
I think the minimum scenario to reproduce is:
- use last version of nuxt
- nuxt (reproduce in yarn dev, and in static generated app)
- inspect <meta charset='utf-8'> they should be 2 of them. 

### What is Expected?
I expect to see only one meta charset and no html5-validator error

### What is actually happening?
there are 2 meta charset div in my html

this one needs to be removed:
  <meta data-n-head="ssr" data-hid="charset" charset="utf-8">

**Comment by trollepierre** [comment]
ok! thanks you solved my issue!

**Comment by jasonkhanlar** [comment]
Rather than creating a new bug report, in Nuxt3 I am experiencing similarly two instances of meta charset appearing in ./pages/index.vue

See discord server message starting at https://discord.com/channels/473401852243869706/897487139888062506/955710568453521428

In Nuxt3's nuxt.config.ts, with contents:
```
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
  meta: {
    meta: [
      { charset: 'latin-1' } // not utf-8, but better shows which one is added from the script
    ]
  },
})
```
then the html source appears as:
```
<meta charset="utf-8"><meta charset="latin-1">
```
apparently Nuxt3 is injecting utf-8 always from somewhere else.

**Comment by jasonkhanlar** [comment]
Oh, I just noticed this report is closed, and I can't find a way to open it. Oh well.

**Comment by danielroe** [comment]
@jasonkhanlar Issues for Nuxt 3 should be raised at https://github.com/nuxt/framework.

This particular issue comes from upstream: see https://github.com/vueuse/head/issues/32.
