### ISSUE TITLE
config is not giving privateRuntimeConfig() with SSG

### ISSUE THREAD

**Issue by zarub2k** [nuxt/nuxt.js#8535]
### Versions

- "nuxt": "^2.14.6",
- node: v12.19.0

### Reproduction

I am referring https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config to setup config (.env). All the configuration is working fine. My application is SSG (target: 'static'). When I run my application I am able to access the variables configured in publicRuntimeConfig() but privateRuntimeConfig() variables are not accessible to me. Am I doing anything wrong here?

My usecase is very simple. I am building a simple personal profile website. My use case is to provide a subscribers functionality. This will talk to my Airtable API. Now I would like to safely provide my Airtable API token through privateRuntimeConfig functionality. 

Can you provide me some tip to fix the problem?

**Comment by danielroe** [comment]
@zarub2k Would you be able to create a code reproduction?

**Comment by zarub2k** [comment]
@danielroe 
nuxt.config.js:
export default {
  publicRuntimeConfig: {
    baseURL: ''
  },
  privateRuntimeConfig: {
    airtableKey: process.env.AIRTABLE_KEY
  },
}

In my vue component:
console.log('Private key: ' + this.$config.airtableKey)

You can refer the code in https://github.com/zarub2k/tham

**Comment by danielroe** [comment]
@zarub2k Looking at your code, you appear to be trying to use that key in client side code. But privateRuntimeConfig is only available on the server, by design.

**Comment by zarub2k** [comment]
@danielroe Thanks for the clarification. In such simple use-case for static web, how to safely share my API key? Is there any possibility in Nuxt framework?

**Comment by danielroe** [comment]
@zarub2k I would recommend a serverless endpoint for the most idiomatic approach.

**Comment by zarub2k** [comment]
@danielroe Would you be little more specific? I believe you are suggesting me something like google cloud function. Would you share some more details? Thanks in advance?

**Comment by danielroe** [comment]
@zarub2k Here's a walkthrough: https://roe.dev/blog/serverless-functions-nuxt-zeit-now

Hope this helps 🙃

Feel free to check out https://discord.nuxtjs.org in #deployments for support.
