### ISSUE TITLE
function hook to cleanup after generate is done

### ISSUE THREAD

**Issue by florianwittmann** [nuxt/nuxt.js#855]
Currently when running nuxt generate it can happen that nuxt freezes at end of the process because open websockets exist. For example when using Firebase, the websocket won't ever stop. Therefore nuxt just prints 
`[nuxt] Generate done`
and does not stop afterwards. I attached a minimal hanging example:
[Nuxt_Generate_Hung.zip](https://github.com/nuxt/nuxt.js/files/1059029/Nuxt_Generate_Hung.zip)

I wish there would be a callback when the generation is done where I can cleanup stuff and call
`firebase.database().goOffline()`
 for my example.

**Comment by piyushchauhan2011** [comment]
This would be good use-case for making a websocket nuxt module @pi0 or maybe Firebase module ?

**Comment by Atinux** [comment]
Will be fixed in next release with https://github.com/nuxt/nuxt.js/pull/879#issuecomment-307861654

**Comment by Atinux** [comment]
Closing it since `rc3` is out
