### ISSUE TITLE
Start receiving ENOSPC error

### ISSUE THREAD

**Issue by kodeJ** [nuxt/nuxt.js#856]
Hi again. I started receiving node error 

```
Unhandled 'error' event
Error: watch /home/nman/PROJECTS/nxt-clean/store ENOSPC
```
First I thought I messed up  with my PC https://github.com/nuxt/nuxt.js/issues/820
But after I reinstall Ubuntu I started receiving this again.

I guess it something related to new npm/Node, since I have never expect any this kind of errors with Nuxt before. My space on hard drive is ok, so ENOSPC doesn't make any sense...

**Comment by pi0** [comment]
Hi. From https://stackoverflow.com/questions/22475849 & https://github.com/npm/npm/issues/2461 :

> ENOSPC means that there is no space on the drive.

> Perhaps /tmp is full? You can configure npm to use a different temp folder by setting npm config set tmp /path/to/some/other/dir, or maybe delete everything out of the /tmp folder.

**Comment by kodeJ** [comment]
Yeah I read this. This is clean version of OS. Space is OK. Other Node apps are running fine.

**Comment by kodeJ** [comment]
This command will help, but why it appears anyway? What changed, I don't understand? And I don't like to messing with kernel, last time I wasn't able to load Graphical Interface after this - `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by kodeJ** [comment]
> setting npm config set tmp /path/to/some/other/dir

How to do that?

**Comment by pi0** [comment]
> How to do that?
Using `npm config set tmp` But you said increasing max watchers resolves this problem ? :))

**Comment by kodeJ** [comment]
increasing max watchers kills my OS last time.

`npm config set tmp` seems like not working.

**Comment by pi0** [comment]
Hmm problem seems from webpack/chokidar watchers on your OS which are set during dev mode of Nuxt.  Just catch two related issues paulmillr/chokidar#294 & coryhouse/react-slingshot#6

**Comment by pi0** [comment]
Maybe we can reduce watchers by setting something like this in nuxt config
```js
watchers: {
  webpack: {

  },
  chokidar: {
     usePolling: true
  }
}

**Comment by kodeJ** [comment]
Cleaning /tmp did not help. Pretty nasty stuff.

**Comment by kodeJ** [comment]
```
  watchers: {
    webpack: {},
    chokidar: {
      usePolling: true
    }
  },
```
That helped! Cool. Thanks @pi0 
I need `webpack: {}` for something?

**Comment by pi0** [comment]
No I've just added it for testing placeholder. If you got issues again, you may also reduce webpack watchers :)

**Comment by kodeJ** [comment]
Yeah, I got issues already. My custom url from hosts stopped working with this fix. I ran my app on http://nuxt.starter, but now it refuses to connect. Nasty.

**Comment by kodeJ** [comment]
Oh, wait, my bad. It working! It's my nginx error. Strange, I guess I some system error.

**Comment by kodeJ** [comment]
Unfortunately, I doesn't refresh code when I edit. I have to reload server so changes take effect.
