### ISSUE TITLE
Overwriting/Disabling errorMiddleware with a hook/another type of implementation

### ISSUE THREAD

**Issue by bashovski** [nuxt/nuxt.js#8564]
Hello,

I am using Nuxt in production and I am planning to swap the error page with a modal inside the same page where the error occurred. Unfortunately it's not possible as Nuxt "handles" the error before the custom plugin.

What should I do in this case?
Thanks in advance.

**Comment by bashovski** [comment]
I have temporarily added ```errorCaptured``` hook on a couple of layouts as a temporary solution. It's not ideal at all.

**Comment by victorgarciaesgi** [comment]
I would like that a lot too, it's not DX at all to replace the whole app with a Error page, at least put an option to disable it and handle it ourselves

**Comment by victorgarciaesgi** [comment]
@bashovski I've added `errorCaptured` too but with no results. I have still this Error page shown when I'm doing an simple fetch

```ts
async fetch() {
    try {
      await apiCall();
    } catch (e) {
      console.log('INTERCEPTED'); // not logged
    }
  }
```

**Comment by bashovski** [comment]
@victorgarciaesgi You'll need to return false at the end of the errorCaptured hook.
