### ISSUE TITLE
Global styles are included in the bundle

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt.js#8569]
### Versions

- nuxt: v2.14.12
- 
### Steps to reproduce

Add some globals styles using the `css` config option.

### What is Expected?
That the global styles are included in the critical CSS style tag in the head.

There is no need to include it in the bundle once it's already in the head.

### What is actually happening?
It's included in the bundle.
![image](https://user-images.githubusercontent.com/6882876/103278575-19cdb600-49cc-11eb-90e3-63b9bd8f48e0.png)

**Comment by ivanuz** [comment]
Same problem
![image](https://user-images.githubusercontent.com/9349808/105464290-5e363400-5ca2-11eb-9360-0d276fc2999a.png)

Nuxt.config.js
`css: ['@/assets/stylus/app.styl', 'vue-multiselect/dist/vue-multiselect.min.css'],`

More than 300kb in app bundle
Production build has inlined css

**Comment by peektoseen** [comment]
Same thing with bootstrap-vue module. 
Step to reproduce:

1.  
 ```$ mkdir nuxttest
$ cd nuxttest
$ yarn create nuxt-app test
$ cd test/
$ yarn add bootstrap-vue
```

2.  edit /nuxt.config.js, add bootstrap-vue/nuxt :
```
  modules: [
    "bootstrap-vue/nuxt"
  ],
```

3. Build and run:
```
$ yarn build
$ yarn start
```

**What I expect**:
Bootsrap styles included like `<link href='...'>`

**What happened**:
Bootsrap styles included like `<style>......</style>`

**Comment by ms-fadaei** [comment]
@danielpost 

I tested [@nuxt/critters](https://github.com/nuxt-community/critters-module/) but it has some downsides:
1. process during SSR takes too much time ( in a real project, without it 100ms and with it 300ms) and increases TTFB.
2. Rerendered the page after loading external CSS

In theory, it is good enough to use it but in the field, the result was different from theory!

**Comment by reinoldus** [comment]
A temporary workaround could be to configure webpack to simply ignore the styles:

```
build: {
  extend(config, { isClient, isServer }) {
        if (isClient) {
          const webpack = require('webpack')
          config.plugins.push(
            new webpack.IgnorePlugin({
              checkResource(resource, context) {
                if (resource.includes('../assets/sass/style.scss')) {
                  console.log(resource, context) //helpful to see if we are removing something that shouldn't be removed
                  return true
                }
                return false
              },
            })
          )
        }
  }
}
```

It seems to work so far

**Comment by reinoldus** [comment]
I apologize for the notification spam but reducing bundle size makes me overly excited:

I think this version works:

```
build: {
  extend(config, { isClient, isServer }) {
        if (isClient) {
          const webpack = require('webpack')
          config.plugins.push(
            new webpack.NormalModuleReplacementPlugin(
              /\.\.\/assets\/sass\/style\.scss/,
              '../assets/sass/fake.scss'
            )
          )
        }
  }
}
```

We basically swap out the global styles with an empty "fake.scss" during build. It's pretty dirty but it seems to work, can't find anything broken so far.

**Comment by hvitis** [comment]
+1
