### ISSUE TITLE
ssr mode.   merge common.js runtime.js app.js

### ISSUE THREAD

**Issue by andyyanlang** [nuxt/nuxt.js#8571]
use 'npm run build', my project ouput common.js runtime.js app.js. i want to reduce http request counts. is these any way to merge these js?

**Comment by pi0** [comment]
Hi. Actually you can disable chunk splitting ([docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#splitchunks) and [docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#optimization)) but you shouldn't normally do this as default code splitting ensures having long term caching (ie when updating a page, common.js doesn't needs to be downloaded again).
