### ISSUE TITLE
Client-only content doesn't render in component's slot

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt.js#8579]
### Versions

- nuxt: 2.14.12
- node: 14.15.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

1. Create Vue.js component with a named slot of your choice
2. Use created component and provide the content for the slot (wrap everything in `<client-only>` tag); example below:
```
<Stepper
    :steps="[$t('steps.one'), $t('steps.two'), $t('steps.three')]"
>
    <template slot="step-1">
        <div>
            <client-only placeholder="Loading...">
                <!-- Neither a span tag nor v-calendar plugin works (tested one by one)  -->
                <span>Test</span>
                <div>
                    <v-date-picker
                        v-model="dates"
                        is-expanded
                        trim-weeks
                    />
                </div>
            </client-only>
        </div>
    </template>
</Stepper>
```
The placeholder remains with no content replaced as shown below:
![image](https://user-images.githubusercontent.com/48835293/103462396-3435c580-4d25-11eb-87ed-3fbc0a27a8c8.png)

### What is Expected?
Content inside `<client-only>` tag should get rendered instead of getting stuck on the placeholder (or blank state if placeholder not provided).

### What is actually happening?
`<client-only>` tag does not render its content when the tag is placed inside a component slot, as shown in the provided example. It does render when placed outside of the slot.

**Comment by DamianGlowala** [comment]
I needed to refresh what the problem was and despite skipping an important step in the description above to reproduce it, here it is! :) Notice the slot within a slot which was the key to reproduce the issue.

[codesandbox](https://codesandbox.io/s/determined-gareth-pcebk?file=/pages/index.vue)

**Comment by danielroe** [comment]
@DamianGlowala Interesting indeed. In the interim, note that the source of `<ClientOnly>` is https://github.com/egoist/vue-client-only - so it may be worth raising an issue there directly.

**Comment by MarineLB** [comment]
Did you ever find a solution for this ?
