### ISSUE TITLE
Importing nuxt.config.js in component

### ISSUE THREAD

**Issue by briangonzalez** [nuxt/nuxt.js#858]
In version [1.0.0 of gustavo](https://github.com/eggplanetio/gustavo/tree/1.0.0), I am trying to import `nuxt.config.js` into a component.

If I uncomment [this line](https://github.com/eggplanetio/gustavo/pull/15/files#diff-5f62385c8e8e2dc1b687c9f1f50c73a0R7), the build breaks. See screenshot below.

<img width="963" alt="screen shot 2017-06-08 at 00 03 10" src="https://user-images.githubusercontent.com/659829/26916775-76740ea6-4be0-11e7-972e-48d94fc46f0e.png">

**Comment by alexchopin** [comment]
Hi @briangonzalez, why do you need to import nuxt.config.js file into a component?

**Comment by pi0** [comment]
@briangonzalez You may use also use modules for inferring config and setting meta tags. For this case please take a look at [meta](https://github.com/nuxt/modules/tree/master/modules/meta) module.

**Comment by briangonzalez** [comment]
@pi0 @alexchopin I am looking to store a user's google analytics ID in the nuxt config then reference it in a component.

**Comment by pi0** [comment]
@briangonzalez You can leverage `env` option in nuxt config and then access env variables using `process.env.GOOGLE_ANALYTICS`.  However we already have [google-analytics](https://github.com/nuxt/modules/tree/master/modules/google-analytics) module ready to use and i strongly recommend adapting to new modules system for your CMS. You will have our VIP support for migration ;)

**Comment by briangonzalez** [comment]
This should most certainly work, thanks @pi0 @alexchopin !
