### ISSUE TITLE
`data-fetch-key` makes no distinction between parent and child components if parent's first child is also a fetch-enabled component

### ISSUE THREAD

**Issue by tabjy** [nuxt/nuxt.js#8581]
Not sure if I've properly phrased the title, so please bear with me:

### Versions

- nuxt:  v2.14.6
- node:  v14.15.3

### Reproduction

https://codesandbox.io/s/sharp-sea-ox94h

<details open>
<summary>Additional Details</summary>
<br>

See codesandbox link for `nuxt.config` and dependencies.

### Steps to reproduce

As in issue title, the essential condition to trigger the bug is having a fetch-enabled child component (so a `data-fetch-key` is added) being the first child of its parent component which is also fetch-enabled (adding another `data-fetch-key`). However, ultimately, the two `data-fetch-key` would add to the same HTML element and one would overwrite the other.

```vue
// Parent.vue
<template>
  <child :foo="foo" />
</template>

<script>
  ...
  async fetch() {
    this.foo = await Promise.resolve("foo");
  }
  ...
</script>

// Child.vue
<template>
  <p>{{ foo }} {{ bar }}</p>
</template>

<script>
  ... 
  async fetch() {
    this.bar = await Promise.resolve("bar");
  }
  ... 
</script>
```
</details>

### What is Expected?

The page shows "**foo bar**" after client hydration.

### What is actually happening?

The page shows "**foo (unset)**" after client hydration.

The SSR result is correct, however, while the client app instance is mounted and hydrated, both components' `data-fetch-key` point to the same fetch data in `window._NUXT_`:
```html
<p data-fetch-key="0">foo bar</p>
```

A client warning is raised, caused by adding a data property from `window._NUXT_.fetch[0]` that is not defined in the child component.
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option.
```
---

I have to admit it's a problem only in niche use cases.

**Comment by tabjy** [comment]
Sorry I've clicked on submit by mistake. I'm adding details right now. Will update in a minute.

**Comment by merijnponzo** [comment]
Hi any updates on this one?

```
Vue warn]: Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option. 2 vue.runtime.esm.js:619
[Vue warn]: Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option.
```

I have the same error log and it's driving me mad

```
<template>
  <section class="my-32 container mx-auto min-h-512 ds:min-h-screen">
    <p v-if="$fetchState.pending">
      Fetching posts...
    </p>
    <p v-else-if="$fetchState.error">
      Error while fetching posts
    </p>
    <ul v-else>
      …
    </ul>
    </div>
  </section>
</template>
<script>
export default {
  name: 'LatestKennels',
  async fetch () {
    const data = await this.$axios.$get(
      `${process.env.strapi.endpoint}/latest/kennels`
    )
    console.log(data)
  },
  fetchKey: 'latest-kennels',
  data () {
    return {
      kennels: []
    }
  }
}
</script>
```

**Comment by jaap3** [comment]
I ran into this today using nuxt 2.15.8, had to debug for a long time before figuring out what the issue was. I ended up "solving" it by wrapping the component with a div so the `data-fetch-key` attribute is applied to a different element.

Not sure if this will re-open the ticket, but it is still an issue with the most recent release of Nuxt.js v2.
