### ISSUE TITLE
Nuxt does not properly livereload when using multiple tabs or multiple devices

### ISSUE THREAD

**Issue by 0x4139** [nuxt/nuxt.js#8583]
### Versions

- nuxt: 2.14.6
- node: v15.3.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

Create any nuxt.js app using npx yarn or npm, and open multiple tabs or use a program like sizzy/responsivelyApp or open a second device
### What is Expected?
Live reload should work on all tabs
### What is actually happening?
Live reload either stops working or works only on one tab.

**Comment by manniL** [comment]
Hey! See https://github.com/nuxt/nuxt.js/issues/6007 ☺️

**Comment by 0x4139** [comment]
> Hey! See #6007 ☺️

i kind of thought about that, do you have any clue if there is a switch for polling to websockets or something in the livereload server?
