### ISSUE TITLE
bug: [HMR] serverMiddleware breaks when `router.base` is set

### ISSUE THREAD

**Issue by lkho** [nuxt/nuxt.js#8584]
when `router.base` is set, HMR won't work for serverMiddleware, since the prefix is repeatedly added to route, which breaks.
https://github.com/nuxt/nuxt.js/blob/8edafbeb44c432614fe69a6aa49ab39928d7407c/packages/server/src/server.js#L315-L316

when `replaceMiddleware` is called, the `middleware.route` is modified _again_, e.g. suppose with the following config:
```javascript
  router: {
    base: '/path/',
  },
  serverMiddleware: [
    { route: '/api', handler: '~/api/index.ts' },
  ],
```
when `~/api/index.ts` changed, the HMR logged route becomes:
`i [HMR] /path/path/api (C:\...\api\index.ts)   `
and changed once again:
`i [HMR] /path/path/path/api (C:\...\api\index.ts)    `

**Comment by pi0** [comment]
Hi @lkho. I can confirm the bug without reproduction. Would be nice if can make a PR for fix otherwise will try to work on it...

**Comment by lkho** [comment]
any updates?
