### ISSUE TITLE
Integration with Nightwatch and CircleCI using Nuxt module

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#859]
Any help related to setting up with Nightwatch would be awesome. Currently, we use ava + jsdom which is mentioned in Nuxt docs. I found these docs as initial starting point but think that will it be good use case for extracting it out to Nuxt modules ?

1. https://vuejs-templates.github.io/webpack/e2e.html
2. https://www.browserstack.com/automate/nightwatch
3. https://www.browserstack.com/automate/nightwatch-integration

**Comment by Atinux** [comment]
Hi @piyushchauhan2011 

Actually jsdom is only a first solution for testing with Nuxt.js, I did not try with others frameworks.

We planned after 1.0 stable to work on a way of testing Nuxt.js application them most efficient way possible :+1:

**Comment by Kylart** [comment]
I have no clue if that can help but I managed to get nightwatch working on my project which you can find [here](https://github.com/Kylart/KawAnime).

_Don't mind the electron part, it is just a wrapper to have a desktop app. It works in the browser just like a normal web project too._

**Comment by piyushchauhan2011** [comment]
Hey @Kylart Awesome job at doing an integration of electron + nightwatch + nuxtjs app . I looked at the coverage by running `npm run test:server`.

It outputs something like this:
![screen shot 2017-06-15 at 7 03 21 pm](https://user-images.githubusercontent.com/693487/27178582-5e5c7182-51fd-11e7-8636-4b1d52c6e836.png)

If we `cd coverage` it remains empty after running `npm run coverage`. I was looking for test coverage related to store and UI `.vue` components.

In the other project, which is here https://github.com/eddyerburgh/avoriaz-ava-example 
if we run `npm test` we can see the coverage includes the `.vue` files.

Maybe I'm missing something @Kylart

**Comment by piyushchauhan2011** [comment]
The example of `KawAnime` solves the Nightwatch problem hence seems a good idea to close the issue. Cheers @Kylart

**Comment by Kylart** [comment]
Glad I could help! @piyushchauhan2011 

Yes, nyc is not ran on the nightwatch tests since I don't want to get the coverage on my vue components for now.

The output you see is the output of my api tests hence there are only js files.
