### ISSUE TITLE
Vue directive

### ISSUE THREAD

**Issue by SzHeJason** [nuxt/nuxt.js#860]
Hello!! 
how to use directive in nuxt.js?

`
plugins: ['~plugins/filters.js','~plugins/directive.js'];
`

`
Vue.directive('nferror', {
  bind: function() {
    console.log("bind")
  },
  update: function() {
  },
  unbind: function() {
  }
});
`

`<p class="font-count" nferror :class="isError"></p>`
  

It's not working

**Comment by Atinux** [comment]
Hi @SzHeJason 

it works, please read [Vue.js documentation](http://vuejs.org/v2/guide/custom-directive.html#Intro) to know how it works.

You need to use `v-` in front of your custom directive:

```html
<p v-nferror></p>
```

Demo: https://standing-spot.glitch.me/ (look at the console)
Code: https://glitch.com/edit/#!/standing-spot?path=pages/index.vue:3:11
