### ISSUE TITLE
"nuxt build --standalone" does not generate a self-contained bundle runnable by nuxt-start

### ISSUE THREAD

**Issue by dtoch** [nuxt/nuxt.js#8602]
### Versions

- nuxt: 2.14.12
- node: 12.20.0

### Reproduction

Included a small NuxtJS application configured in SSR mode with : 

-  a page pages/index.vue in which the module morgan is imported and logged
-  a middleware API api/app.js in which the API endpoint /api/test logs the imported module "morgan"

Test case source code : 

- package.json :

```
{
  "name": "testbug",
  "version": "0.0.0",
  "description": "testbug",
  "private": true,
  "dependencies": {
    "morgan": "1.10.0",
    "nuxt": "2.14.12",
    "nuxt-start": "2.14.12"
  }
}
```

- nuxt.config.js : 

```
module.exports = {
  ssr: true,
  serverMiddleware: [
    '~/api/app.js',
  ],
}
```

- Dockerfile :

```
FROM node:12-alpine

COPY ./.nuxt ./.nuxt
COPY ./api ./api
COPY ./nuxt.config.js .
COPY ./package.json .
COPY ./package-lock.json .

RUN npm install nuxt-start
CMD [ "node_modules/.bin/nuxt-start", "-H", "0.0.0.0" ]
```

- .dockerignore : 

```
node_modules
npm-debug.log
pages
layouts
Dockerfile
```

- api/app.js : 

```
const express = require('express')
const morgan = require('morgan')
const app = express()

app.get('/test', (req, res) => {
  res.status = 200
  console.log('morgan = ' + morgan)
  return res.send("TEST")
})

module.exports = {
  path: '/api',
  handler: app,
}
```

- layouts/default.vue : 

```
<template>
  <layout-basic>
    <nuxt />
  </layout-basic>
</template>

<script>
export default {
}
</script>
```

- pages/index.vue : 

```
<template>
  <div>
    <v-main>
      <v-container>
        HELLO
      </v-container>
    </v-main>
  </div>
</template>

<script>
const morgan = require('morgan')
console.log(morgan)
export default {
}
</script>
```

### Do the following steps : 

A. Build standalone bundle

A.1. npm install
A.2. node_modules/.bin/nuxt build --standalone

B. Test outside Docker context

B.1. node_modules/.bin/nuxt-start
B.2. perform http://localhost:3000/ and http://localhost:3000/api/test : instance of "morgan" is imported and logged (OK).

C. Test in Docker context

C.1. docker build -t testbug .
C.2. docker run -it -p 3000:3000 testbug
C.3. perform http://localhost:3000/ and http://localhost:3000/api/test : instance of "morgan" is imported and logged (OK).

Now C.3 worked because in Dockerfile : 

a. the files package.json and package-lock.json were copied in the docker build context before running npm install nuxt-start
b. the source file api/app.js was copied in the docker build context so it's available for nuxt-start

If a. and b. are not performed, then you will get errors running nuxt-start in Docker because it can't find the morgan/express dependency and neither the api/app.js source file.

I would have expected that a. and b. should not be needed because isn't the whole point of "nuxt build --standalone" (step A.2) to make a self-contained bundle in .nuxt with all dependencies in it and that can be run directly by nuxt-start ?

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

See previous section.

### What is Expected?

The bundle generated by nuxt build --standalone should be self-contained and should be directly runnable by nuxt-start.

### What is actually happening?

The bundle generated by nuxt build --standalone is not self-contained and can not be directly run by nuxt-start.

**Comment by pi0** [comment]
Hi @dtoch & thanks for detailed issue. Actually it is an intended behavior when standalone flag is set. It only adds SSR dependencies to server bundle. (nuxt config, server middleware and modules are not included)

Nuxt3 engine is rewritten (project sigma) in a way to make this possible and is also backported to nuxt2. Sourcecode is private but you can see [demo](https://github.com/nuxt/sigma-demo) and try it on your project by adding `@nuxt/sigma`. `nuxt build` will generate standalone `.output/server`....
