### ISSUE TITLE
Updating meta tags with generate payload and Asyncdata comes in too late. Crawlers are not picking up on the updated metadata

### ISSUE THREAD

**Issue by Louvki** [nuxt/nuxt.js#8605]
I am running a statically generated site which is hosted on S3. I have a set up where we generate multiple dynamic pages which are supposed to be SEO optimized.  However all the work is brought to naught. The metatag information which i pass through the payload has a delay before it's applied which confuses the crawlers. The delay is especially visible on the first navigation into the website.

When I check my website using something like https://www.heymeta.com/ the meta title and meta desc appear as the default ones I have set in nuxt.config.js (and I have set the hid properties so i know they are getting replaced properly. So far this has only been an issue with the pages generated using the payload)

![w](https://user-images.githubusercontent.com/24243356/103900215-d542c880-50f7-11eb-8ca3-b676a2f38530.gif)
  
```
// nuxt.config.js
mode: 'universal',  
generate: {
    routes () {
      return axios.get(`https://${LF_CDN}/payload.json?v=${Date.now()}`)
        .then((res) => {
          const routesToGenerate = [];
          for (const payload of res.data) {
            routesToGenerate.push({ route: payload.url, payload });
          }
          return routesToGenerate;
        }).catch((e) => {
          throw e;
        });
    }
},
```
```
// dynamic page
 asyncData ({ payload }) {
    return { payload };
  },
  head () {
    const i18nSeo = this.$nuxtI18nSeo();
    // I do some merging with the suggested SEO stuff from nuxti18n module. Though it should matter
    return this.payload.metadata;
  }
```

### Versions
- nuxt: 2.14.7
- node: 14.15.1

### Steps to reproduce
- Have default metatags set up in nuxt.config.js
- Have dynamic pages generated
- Pass in payload to each page through the generate function. Payload contains meta information
- Use the data from the payload in the dynamic page to generate the metatags using the head() method.

### What is Expected?
Considering all the page are pre generated I expect the correct metatags to be displayed from the get go instead of getting injected at runtime

### What is actually happening?
The default metatags are getting displayed only to be replaced by the correct ones afterwards. 
Causes issues for crawlers when checking metatags.

**Comment by valeriu9** [comment]
+1

**Comment by KarolinaZapolskyte** [comment]
+1

**Comment by iandrei250** [comment]
+1

**Comment by danielroe** [comment]
@Louvki Would you be able to create a minimal reproduction of the issue, perhaps using https://template.nuxtjs.org?

**Comment by Louvki** [comment]
Ok nevermind I am clossing this as I suffer from an extreme case of not smartness. 
I had an error in the head method that was silently swalloved by a try catch, thus breaking the execution. Sorry for the bother!

**Comment by Louvki** [comment]
During my debugging I also noticed another issue which some people might be having. 

The head method will not run if the page you are generating is using a layout that surrounds it by **<client-only>**

! This will not execute the head() method
```
<template>
  <div>
    <client-only>
      <nuxt />
    </client-only>
  </div>
</template>
```

**Comment by manchumahara** [comment]
> client-only

this saved us hours, thank you so much.

**Comment by aliparlatti** [comment]
Thank

> During my debugging I also noticed another issue which some people might be having.
> 
> The head method will not run if the page you are generating is using a layout that surrounds it by `<client-only></client-only>`
> 
> ! This will not execute the head() method
> 
> ```
> <template>
>   <div>
>     <client-only>
>       <nuxt />
>     </client-only>
>   </div>
> </template>
> ```

successful, thank you very much
