### ISSUE TITLE
Difference between targets when SSR is off

### ISSUE THREAD

**Issue by laspinacristian** [nuxt/nuxt.js#8606]
### Versions

- nuxt: v2.14.12
- node: v14.15.0

### What is the Issue?
Understand the difference in `nuxt.config.js` between
```
target: static
ssr: off
```
and
```
target: server,
ssr: off
```

The latter is something that doesn't make sense semantically.
How can target be server if the ssr is off? anyway it does compile to an SPA

The former also compile to an SPA but from the network calls in chrome we can see there is one more file request so there seems to be a component split out

**What is the real difference between the two combinations?**

### Reproduction

```
git clone https://github.com/laspinacristian/nuxt-targetStatic-noSsr
npm install
npm run generate
npm run start
```

```
git clone https://github.com/laspinacristian/nuxt-targetServer-noSsr
npm install
npm run build
npm run start
```

**Comment by manniL** [comment]
`ssr: false` means that no server-side rendering itself is happening, no matter which `target` is set so the HTML will never contain actual content but only a few lines as well as the JS for the SPA to load.

There are situations where it would still make sense to have a Node.js server running and "only" delivering an SPA: `serverMiddleware` would still work, modules like the `proxy`-module are enabled (and so on).
Situations where those are mandatory but SSR is not needed are the only ones I can imagine when I'd choose `target: 'server'` + `ssr: false`.

But I'd love to hear more comments on that (cc @pi0)

**Comment by pi0** [comment]
Actually you don't need to specify `target: 'server'` since it is default behavior. When target is set to `static`, we make few changes to build including mocking asyncData and disabling query from SSR context which only makes sense for SSR generated pages.

There is not necessarily a direct relation between this two flags. As @manniL mentioned, one may use `nuxt start` with serverMiddleware and runtime config and without server-side rendering.  

Generally you need to set target to static for spa/ssr deployments (building with `nuxt generate`)

**Comment by naderghanbari** [comment]
Sorry for commenting on a closed issue but I'm in the same situation and what I see in the logs is confusing me.

According to `npm run build` logs, target is `static` regardless of the value in the config file.

First case:

```json
{
  "ssr": false,
  "target": "static",
}
```

```
ℹ Production build    
ℹ Bundling only for client side 
ℹ Target: static 
```

Second case:


```json
{
  "ssr": false,
  "target": "server",
}
```

```
ℹ Production build    
ℹ Bundling only for client side 
ℹ Target: static 
```

Sholdn't the logs show `server` as the target in this case?

**Comment by helderhernandez** [comment]
I recommend reading the following [article](https://kontent.ai/blog/demystify-nuxt-target-mode-and-ssr-properties)

**Comment by marioesuc** [comment]
> Sorry for commenting on a closed issue but I'm in the same situation and what I see in the logs is confusing me. I'm on Nuxt version `2.15.1`.
> 
> 
> 
> According to `npm run build` logs, target is `static` regardless of the set `target` in the config file.
> 
> 
> 
> First case:
> 
> 
> 
> ```json
> 
> {
> 
>   "ssr": false,
> 
>   "target": "static",
> 
> }
> 
> ```
> 
> 
> 
> ```
> 
> > npm run build
> 
> 
> 
> ℹ Production build    
> 
> ℹ Bundling only for client side 
> 
> ℹ Target: static 
> 
> ```
> 
> 
> 
> Second case:
> 
> 
> 
> 
> 
> ```json
> 
> {
> 
>   "ssr": false,
> 
>   "target": "server",
> 
> }
> 
> ```
> 
> 
> 
> ```
> 
> > npm run build
> 
> 
> 
> ℹ Production build    
> 
> ℹ Bundling only for client side 
> 
> ℹ Target: static 
> 
> ```
> 
> 
> 
> Sholdn't the logs show `server` as the target in this case?
> 
> 
> 
> If fairness to Nuxt, later when running `npm start` (with `target` set to `server`), it shows
> 
> 
> 
> ```
> 
> > npm start
> 
> 
> 
> Nuxt @ v2.15.1 
> 
>    │                                          
> 
>    │   ▸ Environment: production              
> 
>    │   ▸ Rendering:   client-side
> 
>    │   ▸ Target:      server   
> 
> ```

Having this exact situation and same question. I read the article mentioned above but didn't clarify why this happens.
