### ISSUE TITLE
Problem in functional components '_vm._ssrEscape is not a function'

### ISSUE THREAD

**Issue by jairoblatt** [nuxt/nuxt.js#8607]
### Versions

- nuxt: ^2.14.7
- node: 14.15
### What is the Issue?
When I try to use a functional component with ssr nuxt shows this error
```sh
_vm._ssrEscape is not a function
```

### Reproduction
This is the component that is having problems
```sh
<template functional>
    <div class="answer-seed-question">
      <p>{{ props.question }}</p>
    </div>
</template>
```
### 
### Unconventional solution
One solution I found was to use <client-only>, but I need ssr.
```sh
<template functional>
  <client-only>
    <div class="answer-seed-question">
      <p>{{ props.question }}</p>
    </div>
  </client-only>
</template>
```

is there another solution to this problem, or is it a nuxt bug?

**Comment by AndrewBogdanovTSS** [comment]
I have same issue
```
<template functional>
  <div>
    <h3 v-if="props.module.title">{{ props.module.title }}</h3>
    <div v-if="props.module.description" class="text-14" v-html="props.module.description" />
    <p v-else-if="props.module.descriptionPlain" class="text-14 pt-4">{{ props.module.descriptionPlain }}</p>
  </div>
</template>

<script>
  export default {
    name: 'Module15',
    props: ['module']
  }
</script>
```
![image](https://user-images.githubusercontent.com/2766448/106158902-4a546b80-6195-11eb-879d-e4be867f71c6.png)

Nuxt v.2.14.12

**Comment by jairoblatt** [comment]
I had version 3.6 of corejs, I upgrade to 3.8, now I'm getting another error.
``
Now "_vm._ssrNode is not a function"

![image](https://user-images.githubusercontent.com/45108346/107932715-a1f82280-6f5c-11eb-808f-05bdbb1439ac.png)

**Comment by AndrewBogdanovTSS** [comment]
@danielroe I'm already using core-js@3 in the project

**Comment by kms-rscholz** [comment]
Encountering the same issue with node v14.15.1 and nuxt 2.15.3

**Comment by pi0** [comment]
If using components discovery, issue should be fixed in [components@2.1.4](https://github.com/nuxt/components/releases/tag/v2.1.4). To have update you need `nuxt >= 2.15.0` and recreating lock-file. Please ping if issue is not solved.

**Comment by vaspadi** [comment]
nuxt version: 2.15.7

I create functional component and lazy load it. There are no errors when loading the page. But it appears after reloading the page.

_vm._ssrEscape is not a function

**Comment by AlexKFU** [comment]
have same problem

**Comment by randompch** [comment]
Hi there ! I've got the same problem here with Nuxt 2.15.8.
Though, I only get the `_vm._ssrEscape` error in production mode. 🤔 

I need SSR but I'm forced to use `<ClientOnly>` for now.

@pi0 any clue ? 😊
