### ISSUE TITLE
inline css is not included after update to 1.0.0-alpha2

### ISSUE THREAD

**Issue by ArunSivagnanam** [nuxt/nuxt.js#861]
If i disable javascript in dev tools, to take a look at the html structure i can see our css is gone.
Before we did the update it was included like this.

<head> 
<style data-vue-ssr-id="fweoi545y7897h34ht5h......."></style>
</head>

This results in a flash when we load the page :( 
The css  looks ok after hydration. I have looked at https://github.com/nuxt/nuxt.js/issues/754

Nothing is mentioned about css changes. Can someone help?
Thanks

Arun

**Comment by LouiseStroeh** [comment]
I have the same problem. Please look at this.

**Comment by alexchopin** [comment]
Hi, have you tried with the 1.0.0-alpha4 ?

**Comment by ArunSivagnanam** [comment]
It works fine in alpha 4. Thanks!! :)
