### ISSUE TITLE
Cloud nuxt generate all article info static html?

### ISSUE THREAD

**Issue by bi-kai** [nuxt/nuxt.js#8610]
Traditional CMS cloud gentrate article
Cloud nuxt generate all artices and list page info static html by template and data in DB, this will help
to deploy site into CDN.

Does Nuxtjs has a similar feature?

**Comment by bi-kai** [comment]
@danielroe thx, I have a blog site with vue, I want to solve seo problem with nuxt, and full static without server and DB for CDN.
so I want to turn all blog articles into static files.

**Comment by danielroe** [comment]
Great - sounds like what you need.


Feel free to drop into https://discord.nuxtjs.org if you have any questions.
