### ISSUE TITLE
When 'nuxt build nuxt start'  ,some browsers open pages that are garbled.

### ISSUE THREAD

**Issue by gg343917542** [nuxt/nuxt.js#862]
The content of the page is in Chinese,but this is not the case in the development environment.How to solve?
ps:
  Browers ver:Chrome/50.0.2661.102.
  nuxt ver:1.0.0-alpha.3

**Comment by ausir0726** [comment]
hi @gg343917542 

Can you provide your repo or simple error example ?

thanks.

I don't have this issue in Chinese .
