### ISSUE TITLE
Can't resolve 'fs' in server side middleware

### ISSUE THREAD

**Issue by do-web** [nuxt/nuxt.js#8626]
Look at #4148 i have the same problem, please fix it!

**Comment by pi0** [comment]
Hi @do-web. Actually there is a different between [nuxt middleware](https://nuxtjs.org/docs/2.x/directory-structure/middleware/) and [nuxt serverMiddleware](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-servermiddleware). Middleware, are bundled by webpack into production bundle and running on beforeRouteEnter. serverMiddleware can be used to write an API endpoint for example with express.

You should avoid importing node internals in nuxt middleware (it is totally fine for serverMiddleware)

If you need more assistance, please share use-case or reproduction.

**Comment by do-web** [comment]
Hi, i have created a serverMiddleware, so the error apears in the serverMiddleware file.

**Comment by pi0** [comment]
@do-web Kindly please fork [this sandbox](https://codesandbox.io/s/github/nuxt/codesandbox-nuxt/tree/master/) to reproduce error or share repository.

**Comment by do-web** [comment]
Thanks this should be mentioned in the docs.

**Comment by pi0** [comment]
No worries @do-web and agreed. Made https://github.com/nuxt/nuxtjs.org/issues/1143 to improve docs
