### ISSUE TITLE
Nuxt head() hook with defineComponent() does not work correctly

### ISSUE THREAD

**Issue by nobody-dev** [nuxt/nuxt.js#8632]
### Versions
nuxt: "^2.0.0",
node: v12.18.3.
"@nuxtjs/composition-api": "^0.13.0",
"@nuxtjs/dotenv": "^1.4.0",
"@nuxtjs/pwa": "^3.0.0-0",

### What is Expected?

Method/hook **head()** can access data, asyncData and other properties of the component at the moment of the call

### What is actually happening?

Method/hook **head()** cannot access the properties of the component at the time of calling the method, when the component is wrapped in a defineComponent from the compositionApi. If we remove this component wrapper, everything works fine.

**Comment by danielroe** [comment]
@nobody-dev Would you mind creating an issue at https://github.com/nuxt-community/composition-api (and ideally with a reproduction 🙏 )?
