### ISSUE TITLE
target: 'static' doesn't load the layout when accessed directly through the browser url in production

### ISSUE THREAD

**Issue by CavalcanteLeo** [nuxt/nuxt.js#8647]
It runs perfectly in dev mode, but when I build to production, the layout does not load.
But it loads on production if I leave the page and click on any <nuxt-link> that opens back that page

using;
nuxt: 2.14.12,
@nuxtjs/vuetify: 1.11.2,

in my nuxt.config:
```js
export default {
  target: 'static',
  .... 
}
```

in my page.vue:
```js

export default {
  name: 'Laudador',
  components: {
    ...
  },
  layout: 'laudador',
}
```

on my layout (laudador.vue):
```vue
<template>
  <v-app class="laudador-editor">
    <nuxt class="laudador-screen" />

    <notifications
      group="laudador-notifications-top-center"
      position="top center"
      width="400px"
      :pause-on-hover="true"
    />
    <notifications
      group="laudador-notifications-top-right"
      position="top right"
      :pause-on-hover="true"
    />
  </v-app>
</template>

<script>
const listener = function alert(e) {
  const confirmationMessage =
    'Tem certeza que deseja sair? \nAo sair o laudo será perdido'
  ;(e || window.event).returnValue = confirmationMessage // Gecko + IE
  return confirmationMessage // Webkit, Safari, Chrome
}

export default {
  data() {
    return { model: false }
  },
  head() {
    return {
      meta: [
        {
          name: 'theme-color',
          content: '#272727',
        },
      ],
    }
  },
  beforeDestroy() {
    window.removeEventListener('beforeunload', listener, false)
  },
  mounted() {
    window.addEventListener('beforeunload', listener)
    const root = document.getElementsByTagName('html')[0] // '0' to assign the first (and only `HTML` tag)
    root.setAttribute('class', 'prevent-scroll')
  },
  methods: {},
}
</script>
```

you can see the difference of the HTML from accessing directly and by clicking on a <nuxt-link>

And since laudador layout was not loaded, my v-app from vuetify was not set, then all my layout is broken (you can notice even the checkbox field on the middle panel is with a different color, but this is the smallest of my problems)

By now i set the target to server, and it is working fine. It will be server until i figure it out if it was a thing i've done wrong or if it's really a bug

<img width="1440" alt="Captura de Tela 2021-01-14 às 14 46 33" src="https://user-images.githubusercontent.com/1735944/104628851-80fb9380-5677-11eb-89b6-bba8b31b8d18.png">

<img width="1440" alt="Captura de Tela 2021-01-14 às 14 47 07" src="https://user-images.githubusercontent.com/1735944/104628864-848f1a80-5677-11eb-90d8-4a2cd9deebfd.png">

buid: (I also tried to build without config)
```js
  vue: {
    config: {
      productionTip: isProd,
      devtools: !isProd,
    },
  },
  build: {
    optimizeCSS: true,
    extractCSS: true,
    optimization: {
      splitChunks: {
        cacheGroups: {
          styles: {
            name: 'styles',
            test: /\.(css|vue)$/,
            chunks: 'all',
            enforce: true,
          },
        },
      },
    },
    splitChunks: {
      layouts: true,
    },
    html: {
      minify: {
        collapseWhitespace: true,
      },
    },
    terser: {
      terserOptions: {
        compress: {
          drop_console: true,
          pure_funcs: ['console.info', 'console.debug', 'console.warn'],
        },
      },
    },
    extend(config, ctx) {
      if (ctx.isDev) {
        config.devtool = ctx.isClient ? 'source-map' : 'inline-source-map'
        config.plugins.push(
          new webpack.DefinePlugin({
            'process.env.LOGGER_LEVEL': JSON.stringify('info'),
          })
        )
      }
      if (ctx.isClient) {
        config.module.rules.push({
          test: /\.worker\.js$/i,
          use: [
            {
              loader: 'comlink-loader',
              options: {
                singleton: true,
              },
            },
          ],
          exclude: /(node_modules)/,
        })
      }
      // nuxt.config.js, build.extend
      if (isProd && config.plugins) {
        const WebpackObfuscator = require('webpack-obfuscator')
        config.plugins.push(
          new WebpackObfuscator(
            {
              rotateStringArray: true,
              compact: true,
            },
            []
          )
        )
      }
    },
  },

```

**Comment by danielroe** [comment]
@CavalcanteLeo Would you be able to create a reproduction at https://template.nuxtjs.org ?

**Comment by CavalcanteLeo** [comment]
if you want, i can add you to the github project @danielroe

**Comment by knkbga** [comment]
Similar Issue encountered. 
I am not using `target: 'static'`.
And I am guessing I sometimes get two footers instead of one (with images in footer missing) is because of the same reason.
And I am regularly getting this error for one page as described in the issue.

**Comment by disjointed** [comment]
@CavalcanteLeo @knkbga Hi, were you able to fix this in your project? I'm having the exact same problem and can't find anything about it on the internet, except in this issue.

**Comment by steffo93** [comment]
I don't know if it helps, but I solved a similar problem with static building with **ssr: false** in nuxt.config.
