### ISSUE TITLE
How Nuxt.js nuxtServerInit handles cookies. Bug?

### ISSUE THREAD

**Issue by chaos-zhu** [nuxt/nuxt.js#8649]
### Versions

- nuxt: ^2.1.4
- node: v12.18.4

 When I log in with my account and password in the browser, a cookie SESSION will be generated, and then I refresh the page. At this time, the server rendering starts. I send a request for the same domain in nuxtServerInit. Not configure any cookie in Axios Headers, why this request carries a cookie, and the identity of the user it recognizes.

#### nuxtServerInit
```js
export const actions = {
  async nuxtServerInit({ commit }, { $api, $config, req }) {
    console.log(req.headers.cookie) // get cookie
    try {
      let { data: userInfo } = await $axios.getUserLoginState()
      // console.log(userInfo)
    }
  }
}
```

#### axios configure 
```js
  $axios.interceptors.request.use((config) => {
    // console.log($cookies.getAll())
    // config.headers['Cookie'] = $cookies.get('SESSION') || ''
    return config
  })
```

### What is expected ?

when i send request in nuxtServerInit，Theoretically it doesn't get a cookie; $api.getUserLoginState() should return 401 and prompt the user to log in

**Comment by chaos-zhu** [comment]
I haven't loaded any cookies plugins, I haven't looked up anything about this in Google, I don't understand how it works. help me，please.thanks.

**Comment by chaos-zhu** [comment]
sorry, I'm learning Nuxt.js, I think I get it.

**Comment by danielroe** [comment]
@chaos-zhu We've got a great Discord server that might be useful if you come across other questions.

https://discord.nuxtjs.org

**Comment by 0721Betty** [comment]
Hello，I encountered the same problem, how did you solve it?
