### ISSUE TITLE
after run npm update i got this error 

### ISSUE THREAD

**Issue by YallaDealz** [nuxt/nuxt.js#8655]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: node-sass@5.0.0
npm ERR! node_modules/node-sass
npm ERR!   node-sass@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional node-sass@"^4.0.0" from sass-loader@8.0.2
npm ERR! node_modules/sass-loader
npm ERR!   sass-loader@"^8.0.2" from the root project
npm ERR!   sass-loader@"^8.0.2" from @nuxtjs/vuetify@1.11.2
npm ERR!   node_modules/@nuxtjs/vuetify
npm ERR!     dev @nuxtjs/vuetify@"^1.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-17T14_17_14_577Z-debug.log

**Comment by clarkdo** [comment]
Looks you’re still in sass-loader v8 which should be v10 in latest nuxt, I think it may be because you haven’t upgraded or implicitly package hoisting, can you please update or add sass-loader v10 ?

**Comment by clarkdo** [comment]
BTW, latest has recommended upgrading from node-sass to sass(dart-sass) package, https://github.com/webpack-contrib/sass-loader#implementation

**Comment by clarkdo** [comment]
It seemed nuxt vuetify modules has a dependency of old sass-loader which may cause the wrong version loader package installed, we’ll update module ASAP

**Comment by YallaDealz** [comment]
Im already upgraded to sass loader v10
So problem is solving but vuetify is not working well with sass v10

**Comment by clarkdo** [comment]
Thanks, we'll look into the issue.

**Comment by clarkdo** [comment]
@YallaDealz What's your npm version ?

**Comment by YallaDealz** [comment]
Npm v7
Nodejs 15.6

yes i removed node modules and pakcgrjson lock 
After that i installed npm all again but nothing happen

**Comment by clarkdo** [comment]
Sorry, what do you mean by nothing happen ?

**Comment by YallaDealz** [comment]
I mean the problem still persist

**Comment by clarkdo** [comment]
We've published `@nuxtjs/vuetify@1.11.3`, can you try it ?

**Comment by YallaDealz** [comment]
Ok sure i will update it and back to you woth feedback
Thanks

**Comment by YallaDealz** [comment]
problem solved after your published updates 

thanks for all and especially for @clarkdo
