### ISSUE TITLE
Ability to hide client_id and client_secret and debug server side requests

### ISSUE THREAD

**Issue by patron** [nuxt/nuxt.js#8658]
Hi Everyone! I've read many workarounds but still gave no clue how to hide client_id and client_secret on server side, and how to proxify POST request and put two fields (client_id and client_secret respectively) to it. I know that I need to use serverMiddleware or @nuxt/proxy or something else. But how I can change POST request's body and resubmit request with credentials? How can I debug server side middleware or anything else server-side using console.logs? Thanks a lot

**Comment by danielroe** [comment]
You'd be welcome to ask for support on https://discord.nuxtjs.org - or alternatively open a GitHub discussion.

(I'm closing this as it's not a feature request.)
