### ISSUE TITLE
Autonomous Custom Elements for Nuxt

### ISSUE THREAD

**Issue by ptkdev** [nuxt/nuxt.js#8666]
### Versions

- nuxt: 2.14.12
- node: v12.14.0

### Reproduction

I add native webcomponent ([custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements)) to template:

```html
<template>
  <div>
    {{ message }}
    <instagram-widget username="@ptkdev" grid="3x3"></instagram-widget> <!-- this is html5 custom element -->
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import '@ptkdev/webcomponent-instagram-widget'; // available on npm

export default Vue.extend({

  data () {
    const message: string = 'This is a message'

    return {
      message
    }
  }
})
</script>

```

Nuxtjs go to loop and don't load the page on localhost. I see docs of vue and i need (imho) [Autonomous Custom Elements](https://v3.vuejs.org/guide/migration/custom-elements-interop.html#autonomous-custom-elements) but how i can add my custom element to ignoredElements? Where i find `ignoredElements` on nuxtjs?

### Steps to reproduce
- Install `npm install @ptkdev/webcomponent-instagram-widget --save`
- Import custom element javascript
- Add html tag ` <instagram-widget username="@ptkdev" grid="3x3"></instagram-widget> ` to nuxtjs template

### What is Expected?
See html5 custom element

### What is actually happening?
Nuxtjs refresh page and stop working

**Comment by danielroe** [comment]
@ptkdev you can do that via this config property: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-vue-config

**Comment by ptkdev** [comment]
Thank's, work!
