### ISSUE TITLE
Passing props to page / layout using nuxt-link and props: true 

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt.js#8669]
Would adding `props: true` in the routes.js , pass props to the layout or page, using <nuxt-link> like in Vue.js apps?

https://router.vuejs.org/guide/essentials/passing-props.html#boolean-mode
> #Boolean mode
> When props is set to true, the route.params will be set as the component props.

```html
    <nuxt-link target="_blank" :to="websitePreviewUrl" :company="company">{{ text }}</nuxt-link>
```
```js
// routes.js
  {
    name: PATH_KEYS.WEBSITE_PREVIEW,
    component: () => import('@/pages/website-preview').then((m) => m.default || m),
    meta: { pageType: PAGE_TYPES.WEBSITE_PREVIEW },
    props: true,
  },
```

```js
// in the layout / page
  props: {
    company: {
      type: Object,
      required: true,
      default: () => {},
    },
  },
```

Currently the prop is undefined..

**Comment by manniL** [comment]
You have to use the https://github.com/nuxt-community/router-extras-module to pass props this way.

**Comment by manniL** [comment]
You cannot pass route params by setting these at the `<nuxt-link>` component (e.g. `<nuxt-link :company="company">`). This wouldn't work in pure Vue either.

Instead, you could pass the serialized object as query string, as [parameter](https://stackoverflow.com/a/52640870/3975480), save it in Vuex or similar.

Also give https://github.com/nuxt-community/router-extras-module a read (which e.g. covers predefined props)

**Comment by gkatsanos** [comment]
> You cannot pass route params by setting these at the `<nuxt-link>` component (e.g. `<nuxt-link :company="company">`). This wouldn't work in pure Vue either.
> 
> Instead, you could pass the serialized object as query string, as [parameter](https://stackoverflow.com/a/52640870/3975480), save it in Vuex or similar.
> 
> Also give https://github.com/nuxt-community/router-extras-module a read (which e.g. covers predefined props)

Thank you ! Indeed, Serializing the object and passing it as a param would be I guess the way to go (but we re filtering out params and a serialized object won't pass our regex match). 

Because of target="_blank" Vuex unfortunately wouldn't be an option (the store is empty in the new tab), unless we persisted it in localStorage (which we don't). 

What I was looking for is passing params as props which works fine it seems with `nuxt-link`.

**Comment by gkatsanos** [comment]
Yep, understood! I think my main question (which is covered) was if router-link and nuxt-link work the same way / have the same API and apparently they do :)

**Comment by FrazeColder** [comment]
Any news here? I would like to pass my product object to my product.vue card, so the user does not have to fetch the data again as they are already present.

**Comment by manniL** [comment]
> This issue was closed 3 years ago. Please consider opening a [new issue](https://github.com/nuxt/nuxt/issues/new/choose) instead of leaving a comment here.
