### ISSUE TITLE
importing router instance using alias not working properly

### ISSUE THREAD

**Issue by zzhjerry** [nuxt/nuxt.js#867]
I'm using the example ga implementation from the nuxt official website

when I use `import router from '~router'` and define `router.afterEach`, I get this error:

`[nuxt.js] Cannot load components TypeError: Cannot read property 'afterEach' of undefined`

when I use `const router = require('~router')`, I get this error:

`[nuxt.js] Cannot load components TypeError: __webpack_require__(...) is not a function`

Question: how to properly import router instance to get google analytics working?

**Comment by pi0** [comment]
Hi @zzhjerry . Because of new changes to Vue SSR engine, there is no longer a good way using singleton and globals. For GA, you may try [google-analytics](https://github.com/nuxt/modules/tree/master/modules/google-analytics) module which is compatible with `1.x` too.

**Comment by zzhjerry** [comment]
Hi @pi0 it worked! thanks!
