### ISSUE TITLE
Payload is undefined in full static with dynamic routes

### ISSUE THREAD

**Issue by loicmarie** [nuxt/nuxt.js#8676]
### Versions

- nuxt: v2.14.12
- node: v12.15.0

### Reproduction

https://github.com/loicmarie/nuxt-payload-issue

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
- `yarn create nuxt-app nuxt-debug`
- create pages `todos.vue` with only `<NuxtChild />` and `todos/_id.vue` with `asyncData` method running `console.log(payload)`
- in the `nuxt.config.js`, set:
```js
generate: {
  routes: [
      {
        route: '/',
        payload: { test: 'home' }
      },
      {
        route: '/todos',
        payload: { test: 'todos' }
      },
      {
        route: '/todos/test-id',
        payload: { test: 'todos-id' }
      }
    ]
}
```
- run `yarn generate && yarn start`
  

### What is Expected?
When generating, payload is outputted with good value (`{ test: 'todos-id' }`)
When navigating to `/todos/test-id`, payload should be printed with same value

### What is actually happening?
When navigating to `/todos/test-id`, payload is undefined in web console

**Comment by loicmarie** [comment]
I wrote a sidestep 100% in Docker image `node:12.15-alpine` just to be sure it wasn't a misconfig on my host, and I get the exact same result.
Am I missing something ?

- `docker run -it -p 3000:3000 node:12.15-alpine sh`
- `yarn create nuxt-app nuxt-issue`
- Let all default options except target static :
```
? Project name: nuxt-issue
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: None
? Nuxt.js modules:
? Linting tools:
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Static (Static/JAMStack hosting)
? Development tools:
? What is your GitHub username? 
? Version control system: None
```
- `cd nuxt-issue`

In `pages/todos.vue`:
```html
<template>
  <NuxtChild />
</template>
```
In `pages/todos/_id.vue`:
```html
<template>
  <div>{{ test }}</div>
</template>

<script>
export default {
  async asyncData ({ payload }) {
    console.log(payload)
    return payload
  }
}
</script>
```
In `nuxt.config.js`:
```js
export default {
  target: 'static',
  head: {
    title: 'nuxt-debug',
    htmlAttrs: {
      lang: 'en'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  css: [],
  plugins: [],
  components: true,
  buildModules: [],
  modules: [],
  build: {},

  generate: {
    routes: [
      {
        route: '/',
        payload: { test: 'home' }
      },
      {
        route: '/todos',
        payload: { test: 'todos' }
      },
      {
        route: '/todos/test-id',
        payload: { test: 'todos-id' }
      }
    ]
  }
}
```
and finally, `yarn generate && yarn start -H 0.0.0.0`

When navigating to localhost:3000, you can see that:
- `asyncData` output payload as `undefined` in the web console
- and so `test` is not printed in template
- payload is not loaded in resources at all, with no error, as if I was in server mode

**Comment by loicmarie** [comment]
I just made it work by using another HTTP server (like `cd dist && python3 -m http.server 3000`) instead of `nuxt start`...
This is quite strange, at this point I am not sure how to properly debug this

**Comment by danielroe** [comment]
@loicmarie The issue is likely `serve-static` behaviour which is used to preview a static deployment - and which does not serve the generated page unless a `trailingSlash` is in the URL.

**Comment by loicmarie** [comment]
Wow ok ! I have been using Nuxt static for a while and I never heard about it ! Just adding a trailing slash fixed it...
Before I close this, is there a way to avoid this strange behavior ? I am pretty sure I'll run into it again in a few months.
Thank you for your help

**Comment by danielroe** [comment]
You can set `router: { trailingSlash: true } }` to force `serve-static` to redirect to the version with the trailing slash.

**Comment by loicmarie** [comment]
Don't know why but when I set this, payload content show up for some milliseconds and then disappear.
But it should probably be another issue.
Thanks !

**Comment by centogram** [comment]
> Don't know why but when I set this, payload content show up for some milliseconds and then disappear.
> But it should probably be another issue.
> Thanks !

@loicmarie I have the same problem that the payload content appears for a second and then seems to disappear during hydration.

**Comment by SebbeJohansson** [comment]
Hi. I can still not get payload to work with nuxt-ts. Ive tried every way I can come up with to get the payload to show up on my pages.
Here is the repo: https://github.com/SebbeJohansson/sebbejohansson-front

Does anyone have any ideas what I can do or if I'm doing anything wrong?

nuxt.config.ts - https://github.com/SebbeJohansson/sebbejohansson-front/blob/main/nuxt.config.ts
page that has payload - https://github.com/SebbeJohansson/sebbejohansson-front/blob/main/pages/portfolio/_slug.vue
