### ISSUE TITLE
Error Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by Jlaird** [nuxt/nuxt.js#8677]
I am trying to have an endpoint return JSON after an email is sent. I have the basic example below. res.end() closes the connection but continues I believe to the next() function which at the end tries to set headers. Is there any way around this? 

Any help with be great!

```<script>
export default {
  layout: 'BlankLayout',
  fetch({ req, res }) {
    const body = JSON.stringify({ ok: true });
    res.setHeader('Content-Length', Buffer.byteLength(body));
    res.end(body);
  },
};
</script>
```
![image](https://user-images.githubusercontent.com/3812216/105408156-38525600-5bf4-11eb-9fa8-2c228cd58b65.png)

**Comment by danielroe** [comment]
@Jlaird You should use serverMiddleware for this rather than a Vue component.
