### ISSUE TITLE
encoded url causing error when accessing via static mode

### ISSUE THREAD

**Issue by c53hzn** [nuxt/nuxt.js#8679]
### Versions

- nuxt: 2.14.12
- node: 15.6.0

### Reproduction
https://github.com/c53hzn/c53hzn.github.io/tree/master/_nuxt/static/1611255759/blog/language
This is how the generated paths look like
![image](https://user-images.githubusercontent.com/30020736/105445875-f684e680-5cab-11eb-9908-737f902e96f1.png)
And the encoded format will cause error when relevant pages try to extract data from the payload.

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
if I go to a page with Chinese characters in path, the payloads generated won't work because the paths generated for payloads with encoded characters need to be encoded again before the payloads can be accessed
eg:
If I want to access the payloads generated for this path: 
c53hzn.github.io/blog/language/中文

The payload is stored in this path:
c53hzn.github.io/_nuxt/static/1611321880/blog/language/%E4%B8%AD%E6%96%87/payload.js
Here "%E4%B8%AD%E6%96%87" is the encoded Chinese character "中文"

But in order to access this payload, the actual URL should be
c53hzn.github.io/_nuxt/static/1611321880/blog/language/%25E4%25B8%25AD%25E6%2596%2587/payload.js

### What is Expected?
Static mode should generate payload path as is, rather than generate encoded paths.

### What is actually happening?
Encoded paths cause errors when fetching data.

I think it's the same issue as this one [https://github.com/nuxt/nuxt.js/issues/8680](https://github.com/nuxt/nuxt.js/issues/8680), and I followed @pi0 's advice and updated Nuxt, but the issue remains.

**Comment by pi0** [comment]
Hi @c53hzn actually it is not related to `URI malformed` error in linked issue but it makes sense to use non-encoded path when writing static assets.

**Comment by c53hzn** [comment]
Hi @pi0 
Thank you for your reply! Look forward to new changes 😃

**Comment by c53hzn** [comment]
Hi, I'm sorry to bother you guys again on this issue.
I updated Nuxt to the latest version, now the paths for storing the payloads seem to be OK, but the pages are still having trouble retrieving data. This only happens to full static mode, and I really don't know how to fix it.

eg: 
For my blog tag page, I set data attributes as blog_by_year, tagName, ui_en, ui_zh, then I have a computed attribute ui_str
This is the page that works
https://www.houzhenni.com/blog/tag/vlookup
I can find the data attributes in the Vue instance
![image](https://user-images.githubusercontent.com/30020736/112503217-b33b1700-8dc5-11eb-99f3-2178cb98a31b.png)

This is the page that doesn't work
https://www.houzhenni.com/blog/tag/面包屑导航
You can see that data attributes are no where to be found, but the computed attribute is here.
![image](https://user-images.githubusercontent.com/30020736/112503561-fb5a3980-8dc5-11eb-8172-dda8eaa3487b.png)

Can anyone help me on this?

**Comment by nexus-uw** [comment]
@c53hzn, where you able to resolve your issue? i am seeing the same issue when my path includes a space

**Comment by yshlin** [comment]
I have Chinese URLs encountering the same problem.
And I found that the encoding problem can be fixed by using `decodeURI(route)` here:
https://github.com/nuxt/nuxt.js/blob/v2.14.6/packages/vue-app/template/App.js#L308
I'm using v2.14.6 (haven't had time to upgrade to the latest version tho).

**Comment by weotch** [comment]
I think this was fixed in #9494
