### ISSUE TITLE
In the nuxt I need the server database related operations, I was in the plugins, or in the middleware?

### ISSUE THREAD

**Issue by wuchuguang** [nuxt/nuxt.js#868]
In the nuxt , I need the server database related operations, I was in the plugins, or in the middleware?
PS: I want use nuxt/koa ，Server logic write koa .  thx

**Comment by Atinux** [comment]
Hi @wuchuguang 

As described in the documentation, the main scope of nuxt.js is UI rendering while abstracting away the client/server distribution.

If you need to make database related operations, you need to create a REST API in your server (Koa for example) and then call it from your middlewares/pages with [axiox](https://github.com/mzabriskie/axios).
