### ISSUE TITLE
form validator gets wrong value when fetch method exists

### ISSUE THREAD

**Issue by aoping** [nuxt/nuxt.js#8685]
### Versions

- nuxt: 2.14.12
- node: v12.18.2

### Reproduction

https://codesandbox.io/s/happy-cartwright-3b2qr?file=/pages/index.vue

### Steps to reproduce

when fetch() exist, the rule validator gets  empty object

![image](https://user-images.githubusercontent.com/12975084/105629767-ea518280-5e7f-11eb-8804-244a65fe43b1.png)

![image](https://user-images.githubusercontent.com/12975084/105629772-fa696200-5e7f-11eb-9fc6-6cc3b8d5032d.png)

### What is Expected?

the rule validator gets right value

### What is actually happening?

validator gets empty object

**Comment by nothinginterested** [comment]
I meet the same problem

**Comment by danielroe** [comment]
If you use fetch, it will stringify everything on the data property and rehydrate on client side. But this isn't possible to do with an array of objects which contain functions. You will either need to define your validator differently, perhaps using a computed property, or not use fetch for this component.
