### ISSUE TITLE
loading screen not working correctly when using nuxt-edge

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/nuxt.js#8691]
### Versions

- nuxt: 2.15 (nuxt-edge)
- node: 12.14

### Reproduction
https://github.com/nuxt/nuxtjs.org
https://github.com/debs-obrien/debbie.codes

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
clone and run dev command

### What is Expected?
should show loading screen

### What is actually happening?
Both of these sites acting differently using nuxt-edge. For nuxtjs.org the site shows no loading message at all and for debbie.codes I get a minimal loading message but not server / client bundle image like before.

<img width="458" alt="Screenshot 2021-01-25 at 12 06 06" src="https://user-images.githubusercontent.com/13063165/105698847-c1c09b80-5f06-11eb-8b8b-e9a93e8ca91c.png">

**Comment by pi0** [comment]
Hi @debs-obrien are you still experiencing this issue?

**Comment by debs-obrien** [comment]
yes @pi0  on nuxtjs.org it is still behaving weird. you can clone that repo and see it. remove nuxt-edge and adding nuxt and loading screen comes back
