### ISSUE TITLE
'%20' caractere turning into '%2b'

### ISSUE THREAD

**Issue by pedrolages-hotmart** [nuxt/nuxt.js#8692]
### Versions

- nuxt: v2.14.12
- node: v15.2.0

### Reproduction

https://7yf7h.sse.codesandbox.io/?email=some%20aemail.com

### What is Expected?

output: some aemail.com

### What is actually happening?

output: some+aemail.com

**Comment by pi0** [comment]
Hi @pedrolages-hotmart. I can confirm this bug. Since we use same encoding of vue-router (plus as space) but i guess we need to also do decoding with respect to it currently it uses `decodeURI`

**Comment by Astlvk** [comment]
> Hi @pedrolages-hotmart. I can confirm this bug. Since we use same encoding of vue-router (plus as space) but i guess we need to also do decoding with respect to it currently it uses `decodeURI`

@pi0 hello, I also encountered a related problem #8690

**Comment by shailee-m-argus** [comment]
@danielroe I am able to see this in nuxt v2.16.3. Under which version shall I expect this fix? If not yet released, is there a workaround I could use?

**Comment by danielroe** [comment]
It should have been fixed in 2.15.0. If you are still experiencing an issue, feel free to open a new issue with a reproduction.
