### ISSUE TITLE
Programmatically smart prefetch

### ISSUE THREAD

**Issue by LeoSeyers** [nuxt/nuxt.js#8693]
Hello hello,

### Is your feature request related to a problem? Please describe.

I'm working on a portfolio website where each project page is showcased with a slider component.
In the last slider, user is able to continue visiting the next project page by clicking the nuxt-link component .  ~~Page is prefetched when link is hovered.~~
**EDIT**: see @Atinux 's answer and the docs, pages should be prefetched with intersection observer if you use nuxt-link

Alternatively user is able to navigate through the project using controls such as keyboard arrows.
To do so, I'm listening to keyboard event and using `$route.push()` methods. ~~In such case the next route will not be prefetched.~~

Prefetching routes is critical in order to make seamless and instant transitions between views.

### Describe the solution you'd like

I'd like to have a method similar to the smart prefetching feature in non-traditional scenarios where :
- user is expected to visit a specific route
- user can visit this specific route without clicking on the nuxt-link component

~~In my case I'd trigger a route prefetch as soon as user reach the last slide but you could image any other kind of route prefetching when you reach a specific segment on your website (e.g. intersection observer based route prefetching).~~

~~I'd love to be using `$route.push('/next-route')` with hypothetical `$route.prefetch('/next-route')` method.~~
See maybe `fetchPayload `method

### Describe alternatives you've considered

I know that smart prefetching is a nuxt-link component feature tied to Vue router but I failed to find relevant documentations to my specific issue.

~~I searched for <nuxt-component> source code in order to learn and experiment with prefetching but could not find the actual source code (any hint would be appreciated in that regard)~~
https://github.com/nuxt/nuxt.js/blob/3bba4c6a7fd086aaa434e0abf92bdc9480fd3f4e/packages/vue-app/template/components/nuxt-link.client.js

### Additional context

See original SPA-like project that I'd like to port to Nuxt : https://victorpattyn.com/

**Comment by LeoSeyers** [comment]
Apparently, nuxt-link component is using `fetchPayload `method (https://github.com/nuxt/nuxt.js/blob/3bba4c6a7fd086aaa434e0abf92bdc9480fd3f4e/packages/vue-app/template/components/nuxt-link.client.js)

**Comment by LeoSeyers** [comment]
> Hi @LeoSeyers
> 
> Actually, the prefetch is done once the nuxt-link is visible in the viewport, not on hovering, so it should work without any tricks as long as you display a nuxt-link to the target page.

@Atinux  Thank you for the clarification. Just reread the docs and that's indeed what it's said.
I will edit my OP to reflect that.

Out of curiosity, could I use `fetchPayload `in cases where there is no nuxt-link?

**Comment by Atinux** [comment]
I think so, never tried 😅
