### ISSUE TITLE
Link font not preload with extractCSS

### ISSUE THREAD

**Issue by javiercno** [nuxt/nuxt.js#8695]
### Versions

- nuxt: v2.14.12 
- node: 14.15.4

### Reproduction

Hello, if enable extractCSS in one file, fonts not preload in html. 

If i remove block "optimization", it's work perfect

```
extractCSS: true,
optimization: {
  splitChunks: {
    cacheGroups: {
      styles: {
        name: 'styles',
        test: /\.(css|vue)$/,
        chunks: 'all',
        enforce: true
     }
  }
},
//
render: {
  bundleRenderer: {
    shouldPreload: (file, type) => {
      return ['script', 'style', 'font'].includes(type)
      }
    }
 },
```

### What is actually happening?

Preload links are not being created

**Comment by Atinux** [comment]
Do you mind creating a reproduction by forking https://template.nuxtjs.org ?

**Comment by javiercno** [comment]
Sorry, the problem is https://github.com/nuxt-community/tailwindcss-module

If remove module, nuxt append preloads links correct

**Comment by javiercno** [comment]
Excuse me, 

The error its in optimization config whith use scss

```
test: /\.(css|vue)$/,  (documentation)
```

to 

```
test: /\.(scss|css|vue)$/,
```

🙏 Sorry
