### ISSUE TITLE
Global JavaScript

### ISSUE THREAD

**Issue by OrangeXC** [nuxt/nuxt.js#87]
Hi, How to insert the global javascript in `nuxt.config.js`

like

```
css: [
  'video.js/dist/video-js.min.css'
]
```

Or other methods？

**Comment by rubyless** [comment]
https://github.com/nuxt/nuxt.js/blob/master/examples/plugins-vendor/README.md

**Comment by OrangeXC** [comment]
Thank you!  @rubyless
