### ISSUE TITLE
Content flashes then vanishes under HTTPS

### ISSUE THREAD

**Issue by justin-nodeboy** [nuxt/nuxt.js#870]
Hi

I am deploying to Heroku, and using HTTPS. I have a custom server file, with the following middleware function 

```
const forceSsl = (req, res, next) => {
    if (req.headers['x-forwarded-proto'] !== 'https') {
        return res.redirect(['https://', req.get('Host'), req.url].join(''));
    }
    return next();
};

if (process.env.NODE_ENV === 'production'){
    app.use(forceSsl);
}
```

For some reason, the content displays for a split second then vanishes and I am just left with the footer.

Any ideas?
<img width="2560" alt="screen shot 2017-06-10 at 17 48 47" src="https://user-images.githubusercontent.com/12255135/27004680-342916c8-4e05-11e7-80ce-1c2761848b69.png">

The domain is https://www.agencyadvice.co.uk

**Comment by pi0** [comment]
Hi @justin-nodeboy. 
Possibly two problems. First if you look at console log there seems an uncought error:
```
www.agencyadvice.co.uk/:38 Uncaught SyntaxError: Unexpected token &
```

Also it may be hydration problem. Try setting NODE_ENV to dev in `nuxt.config.js` so that your production builds also includes errors. (Should be temporary and removed later for performance)
```js
{
  env: {
    NODE_ENV: 'dev'
  }
}
```

**Comment by pi0** [comment]
Also here is a pure nuxt middleware for https redirect: https://github.com/nuxt/hackernews/blob/master/middleware/https.js

**Comment by justin-nodeboy** [comment]
Thanks @pi0 the uncaught error is from the privacy policy link (they have some dodgy script which I need to remove) but I'll have a try without it.

Good shout on the dev mode, I'll try it out and will let you know

Thanks mate

**Comment by justin-nodeboy** [comment]
@pi0 That did the job, it was the privacy policy script I was injecting. Took that out and it works fine.
I'll just make up a page for that I think.

Everything else is spot on :)

**Comment by zzhjerry** [comment]
hi @pi0, in the example you gave there's a `redirect` statement. Is it able to redirect with an absolute url? What I got is the absolute url is appended as path to my origin

I'm using `alpha.4` version

**Comment by pi0** [comment]
@zzhjerry Do you wnt SSL redirection?

**Comment by zzhjerry** [comment]
yes @pi0, is it possible to be done in the app itself?

**Comment by pi0** [comment]
Yes, it could be possible. But we have a restriction from `vue-router` which redirects can't be any absolute URL. So the workaround for client-side redirects is using `window.location`.

**Comment by zzhjerry** [comment]
Thanks for providing a solution @pi0. But I think to be able to do the redirection with 301 code from server side is more reliable. Using `window.location` will make `http` and `https` sites to be treated as two sites by google when they are actually one. Maybe in this case we can't do anything here and it's a better idea to go back to config from the domain provider.

**Comment by pi0** [comment]
Yes certainly SSR redirects are the right direction. That just was an explanation as you asked doing that inside "app". For a more standard way i suggest using [nuxt-community/redirect-ssl](https://github.com/nuxt-community/redirect-ssl) using `serverMiddleware`.

**nuxt.config.js**

```js
{
   serverMiddleware: [ 
     'redirect-ssl' // Disable me on dev!
  ]
}
```
