### ISSUE TITLE
Layout 失效的问题

### ISSUE THREAD

**Issue by MickeyMouse623** [nuxt/nuxt.js#8702]
## 目录结构
![image](https://user-images.githubusercontent.com/18524460/105960239-e60faa00-60b7-11eb-9580-a9ea6eca8767.png)

## 首页
首页使用的模板是 `layout/container.vue`
![image](https://user-images.githubusercontent.com/18524460/105959963-8b764e00-60b7-11eb-8abf-b81762bfc3ab.png)

## 错误页面
错误页面使用的模板是 `layout/default.vue`
![image](https://user-images.githubusercontent.com/18524460/105960142-c4162780-60b7-11eb-86f9-117567bc6422.png)

## 过程描述
1、在首页中通过 `NuxtLink` 跳转到 `error`
2、在错误页面中点击 `<NuxtLink  to="/">首页</NuxtLink>`
3、返回首页后却发现，首页使用的模板却是`layout/default.vue`

![image](https://user-images.githubusercontent.com/18524460/105960768-a3020680-60b8-11eb-9daf-3040555bde8b.png)

**Comment by danielroe** [comment]
@MickeyMouse623 Would you provide a reproduction, via https://template.nuxtjs.org - thank you 😊
