### ISSUE TITLE
Vendor Error in IE11

### ISSUE THREAD

**Issue by AhmedHadjTaieb** [nuxt/nuxt.js#8708]
### Versions

- nuxt: 2.11.0
- node: 12.18.4

### What is Expected?
My site running in IE11.

### What is actually happening?
My site isn't running in IE11. 
I have only the nuxt loader and an error in vendor generate with nuxt, I tried many solutions to solve this error but no one of these solutions can fixed.

#### Package.json
 ```
{
  "name": "front",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest",
    "lint": "eslint --ext .js,.vue --ignore-path ../.gitignore .",
    "lintfix": "eslint --fix --ext .js,.vue --ignore-path ../.gitignore ."
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.9.5",
    "babel-eslint": "^10.0.3",
    "bootstrap": "^4.5.3",
    "bootstrap-vue": "^2.19.0",
    "cookie-universal-nuxt": "^2.1.4",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-html": "^6.0.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jest": "^23.8.0",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^6.2.1",
    "node-sass": "^4.13.1",
    "nuxt": "2.11.0",
    "nuxt-moment": "^1.0.4",
    "prettier": "^1.19.1",
    "sass-loader": "^10.1.0",
    "v-tooltip": "^2.0.3",
    "vue": "^2.6.11",
    "vue-i18n": "^8.17.1",
    "vue-meta": "^2.3.3",
    "vue-outside-events": "^1.1.3",
    "vue-scrollto": "^2.18.1",
    "vue-zoomer": "^0.3.9",
    "vue2-touch-events": "^2.3.2"
  },
  "devDependencies": {
    "@nuxtjs/style-resources": "^1.0.0",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-jest": "^24.1.0",
    "jest": "24.9.0",
    "vue-jest": "4.0.0-beta.2"
  }
}
```
#### Babel.rc
```
{
  "env": {
    "test": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "targets": {
              "node": "current"
            }
          }
        ]
      ]
    }
  }
}
```

### First try:
change babel.rc:
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      },
      "@nuxt/babel-preset-app"
    ]
  ]
}
```

### Second try:
Add polyfill to nuxt config in script:
`      { src: 'https://polyfill.io/v3/polyfill.js', body: true },`

### Third try:
Add babel in build config of nuxt.config:
```
babel: {
      presets ({ envName }) {
        return [
          [
            '@nuxt/babel-preset-app',
            {
              corejs: { version: 3 }
            }
          ]
        ];
      }
    }
```

### Four Try:
I try to generate dist with all of the recent version between  2.14.8 =>  2.14.12

# But Still not working..

<img width="1022" alt="Capture d’écran 2021-01-27 à 18 31 03" src="https://user-images.githubusercontent.com/22799068/106043589-ef603d00-60de-11eb-92be-f361e824ac4c.png">

<img width="1025" alt="Capture d’écran 2021-01-27 à 18 22 01" src="https://user-images.githubusercontent.com/22799068/106043615-f9823b80-60de-11eb-876c-1afa7b9a5784.png">

<img width="400" alt="Capture d’écran 2021-01-27 à 18 32 05" src="https://user-images.githubusercontent.com/22799068/106043577-eb341f80-60de-11eb-9fa7-32ea7883e279.png">

**Comment by danielroe** [comment]
@AhmedHadjTaieb You will need to identify the code that is failing. (Looks like an arrow function that's the issue.) And then add to your `build.transpile` array.
