### ISSUE TITLE
Dynamic modules import on client, but server side rendered imidiatly 

### ISSUE THREAD

**Issue by ArunSivagnanam** [nuxt/nuxt.js#871]
I'm looking for something like this. This is really powerful!! 
Is it something you will consider implementing? 

https://zeit.co/blog/next3-preview

**Comment by pi0** [comment]
Static Exports seem already inspired by [nuxt generate](https://nuxtjs.org/guide#static-generated)  Also Nuxt is powered by Vue.js which supports [async components](https://vuejs.org/v2/guide/components.html#Async-Components) out-of-the box ;) (pages are currently actually using async components too)

**Comment by lucpotage** [comment]
Merci !
Spark by Readdle

**Comment by ArunSivagnanam** [comment]
But is it possible to use asynchronous components in next, but then render them imidiatly on server but asynchronous on client? I've tried this but could not get it to work.  Can anyone help with this?

**Comment by ArunSivagnanam** [comment]
I meant nuxt

**Comment by Atinux** [comment]
Hi @ArunSivagnanam 

The main port of dynamic import is to no load them on server-side and then load them only on client-side.

Actually, the next version of Vue 2.4 will implement this functionality (actually, there is some bugs with SSR), when Vue 2.4 will be out, Nuxt.js will be able to handle async component on the fly :)

**Comment by ArunSivagnanam** [comment]
Hi @Atinux , yes i understand. But in my current project we have a dynamic component that renders different components depending on data we get from our cms. In our problem right now is, that a lot of components are statically imported making the bundles size big. We only have one page component that catches all routes (_.vue). So i thought. I read that asynch components are only resolved when they actually need to be rendered. So i thought this was a way to escape the big bundle size problem, so i want the server to render the needed components, and then when the page is loaded i want the client to grab the necessary bundles and boom.. Do you get my point? 

i tried to set somthing up like this. https://github.com/nuxt/nuxt.js/issues/835
But my strategy dossent work. I think the only way i can solve this is by using async components.

Can you point me in a direction? And do you understand the problem?

Im really thankful for you're reply's 
Arun

**Comment by piyushchauhan2011** [comment]
This will be coming in next release maybe `alpha.5` @ArunSivagnanam @Atinux  👍

**Comment by andyhu** [comment]
@Atinux Vue 2.4 is out, when do you think Nuxt.js can upgrade to 2.4?

**Comment by pi0** [comment]
@andyhu It was! (Just 2 hours after release ;))

**Comment by Atinux** [comment]
@andyhu actually we were already working with the `dev` branch of Vue.js and were waiting for the release :)

**Comment by ArunSivagnanam** [comment]
Can see that alpha.5 still includes   "vue": "~2.3.3", witch version of nuxt uses vue 2.4? I cant wait to try this asynch components on the server side :)

**Comment by piyushchauhan2011** [comment]
I'm eagerly waiting for next release and inclusion of above :eager:
