### ISSUE TITLE
Nuxt SSR request are slower than the client side

### ISSUE THREAD

**Issue by joffreyBerrier** [nuxt/nuxt.js#8710]
### Versions

- nuxt: 2.14.12
- node: 14.15.4

### Reproduction

I made a sample app : https://gist.github.com/joffreyBerrier/bc756ff38c6118e161dc61c3b052ed6f

<details open>
<summary>Additional Details</summary>
<br>
modules: [
  '@nuxtjs/axios',
]

</details>

### Steps to reproduce
- `yarn create nuxt-app latency-ssr`
-- Programming language: **JavaScript**
-- Package manager: **Yarn**
-- UI framework: **None**
-- Nuxt.js modules: **Axios - Promise based HTTP client**
-- Testing framework: **None**
-- Rendering mode: **Universal (SSR / SSG)**
-- Deployment target: **Server (Node.js hosting)**
- Copy / paste my gist on the page index.vue
- Yarn run dev
- Refresh the page and looked the SSR Lantecy

### What is Expected?
The ssr-latency equal to the client-latency

### What is actually happening?
<img width="207" alt="ssrLantencyVsClientLatency" src="https://user-images.githubusercontent.com/26119557/106045728-9fcf4080-60e1-11eb-81d9-221fc4b86822.png">

**Comment by pi0** [comment]
Hi @joffreyBerrier. Testing with a sandbox with nuxt@v2.14.12 and @nuxtjs/axios, times are almost identical for making http request. https://jyh8i.sse.codesandbox.io/

High SSR latency is usually because of server's internal networking. You can use a http baseURL for server (and https browserBaseURL) to reduce latency.

**Comment by joffreyBerrier** [comment]
Hi @pi0 thank's for the answer but I'm not sure to understand your solution, do you have a concrete example

**Comment by pi0** [comment]
For axios:

```js
export default {
  axios: {
    baseURL: 'http://[ip]:[api port]',
    // or
    // baseURL: 'http://myapi.com',
    browserBaseURL: 'https://api.foo.bar',
  }
}
```

You can also use `Promise.all` if having more than one request per SSR.

If non of above methods work, i would suggest diagnosict server (for example `curl -v [baseURL]`) and if it it a serverless deployment, ensuring lambda for ssr and api are in same region.

**Comment by joffreyBerrier** [comment]
I am using baseUrl for the api url and Promise.all on all requests. I am not sure about browserBaseURL, what is it supposed to be?
For production api url we do that :
```
// nuxt-config.js
axios: {
  proxy: false,
  https: true
},

// config-api.js
const setAxiosUrl = ($axios, app, env) => {
  let baseUrl = `http://`
  if (process.env.node_env === 'production') {
    baseUrl = `https://`
  }
  const url = `${baseUrl}${env.api_host}:${env.api_port}/${app.i18n.locale}${
    env.api_prefix
  }`
  $axios.setBaseURL(url)
}
```
How I am suppose to use browserBaseURL ?

**Comment by pi0** [comment]
- `browserBaseURL` can be used to override `baseURL` value for browser (so backend uses a different one)
- In case of using a plugin to programmatically call `setBaseURL`, you should apply same idea there to use a direct link to API for server (using `if (process.server)`)

**Comment by joffreyBerrier** [comment]
Hi @pi0
Sorry, I don't understand why it's necessary to use two different urls for xhr and ssr. I have only one endpoint which I use for XHR and SSR request.

**Comment by pi0** [comment]
Hi @joffreyBerrier It is not necessary :) But can potentially help to speed up `Server <---> Endpoint` latency specially if you have a reverse-proxy like nginx or cloudflare in between.

**Comment by Mitch-i** [comment]
nuxtjs is slower than next and other.
