### ISSUE TITLE
Consola default log object doesnt contain message property

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt.js#8712]
reproduction link : https://repl.it/@gkatsans/Consola#index.js

The consola contrib repository doesnt seem to have a lot of activity in the issue tracker hence my posting here.

**Comment by gkatsanos** [comment]
I don't know how to open an issue in their repo. It's not possible. It sends you to a platform which only creates a support question.

**Comment by danielroe** [comment]
@gkatsanos Apologies for that - that's a pain. Leave it with me. In the meantime could you share more info about the issue - what the issue is and what you would expect to happen instead?

**Comment by gkatsanos** [comment]
So, the documentation/ Readme in consola mentions:
https://github.com/nuxt-contrib/consola#logobject
```markdown
logObject
The logObject is a free-to-extend object which will be passed to reporters.

Standard fields:

**message**
additional
args
date
tag
Extra fields:

badge
```

But: 
```js
const consola = require('consola')
consola.setReporters([
  {
    log: (e) => {
      process.stdout.write(JSON.stringify(e) + "\n");
    }
  }
]);

consola.log({ lala: 1, lolo: 2 });
```

```json
{"date":"2021-01-31T15:51:46.109Z","args":[{"lala":1,"lolo":2}],"type":"log","level":2,"tag":""}
```
There's no 'message' property.

**Comment by gkatsanos** [comment]
@danielroe I'm sorry, I don't understand. 
Is `message` a property of the object passed to the `log` method? (doesnt seem like it)
What do you mean "that consola will handle properly"? 
I think my bottom line question would be 'how can I make sure there's a message property in the logging output?' This is a convention from our logging platform/ infra team.. I'm assuming I need to write my own reporter?
In any case IMHO the documentation is a little confusing/poor..

**Comment by gkatsanos** [comment]
> I believe this issue should be moved to `consola` anyway. We are actively looking at all issues across all our organisations.

it's not possible to create an issue in the `consola` repo.
