### ISSUE TITLE
Error including a .png file as image src. alpha v 3/4

### ISSUE THREAD

**Issue by insanetisane** [nuxt/nuxt.js#872]
```
<template lang="html">
  <div>
    <h1>Hello world!</h1>
    <img src="~assets/img/logo.png" alt="">
  </div>
</template>
```

```
Nuxt.js Error:

Error: Module parse failed: [...]/assets/img/logo.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
[...]
```

Tested this with a clean install of version 1.0.0 alpha 3 and 4.
node v8.0.0
npm v5.0.3

**Comment by zipme** [comment]
Maybe it's caused by this 

> When the loaders are defined in the nuxt.config.js, the default loaders will be overwritten.

**Comment by bayssmekanique** [comment]
I did eventually find that the error went away when I included a `build` object in the `nuxt.config.js` export.  I literally just added `build: {}` to the config object and it resolved the url-loader issue I was having.

**Comment by Atinux** [comment]
Closing it since `rc3` is out
