### ISSUE TITLE
Generate routes in dist directory without asyncData

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/nuxt.js#8731]
### Versions

- nuxt: v2.14.12
- node: v12.8.2
- @nuxt/content: v1.11.1

### Reproduction

- https://codesandbox.io/s/blissful-mendel-j3p1z
- https://domain-monitor.io/blog

### What is Expected?

I should expect to find my generated blog page routes listed inside of the `dist` directory when running `npm run generate`

### What is actually happening?

I'm trying to create blog pagination for my website's blog. I've achieved this quite nicely by moving the contents of my `asyncData` function into a method, however, this now means that when running `npm run generate` I don't get the generated files/folders of individual blogs within my `dist` directory which is absolutely essential for SEO.

Likewise, if I revert back to not having pagination and using the `asyncData` mrthod I'm unable to access the `data` object or methods.

How can I get each blog route to be generated as per my `blog/index.vue` page?

**Comment by sts-ryan-holton** [comment]
@danielroe It seems that `pageNumber` still says `1` on page load despite `this.$route.query.page ? this.$route.query.page : 1` being passed? Does `async fetch` not have access to this initially then?

It means I can't for instance send someone a link to page 5 of my blog because it'll show page 1 initially for them?

**Comment by sts-ryan-holton** [comment]
If I set `fetchOnServer` to `false` then it's able to read my initial value, but equally, doesn't generate my routes, if I set it to `true`, it'll generate some routes but won't read my initial values

**Comment by danielroe** [comment]
@sts-ryan-holton If you are using pagination with a static site, you should use route params rather than queries as the latter are not enabled in full static mode.

**Comment by sts-ryan-holton** [comment]
Could you provide an integration example for my code sandbox? I'd prefer to use a query but if that's absolutely not possible, then ok
