### ISSUE TITLE
Cannot find module when dynamically require images

### ISSUE THREAD

**Issue by alexsoin** [nuxt/nuxt.js#8735]
### Versions

- nuxt: 2.14.6
- node: v12.20.1

### Reproduction

I don't know if it's a bug or a feature, but when I want to dynamically load images stored in assets I get the error "**Cannot find module...**" =) 

![изображение](https://user-images.githubusercontent.com/3787132/106427081-2ab49000-6480-11eb-9e21-14969da3897c.png)

As far as I understand, when I load an image, everything in the string is taken. To confirm this theory I created a project in assets which has 2 files: _README.md_ and _icon.png_. 

![изображение](https://user-images.githubusercontent.com/3787132/106427103-34d68e80-6480-11eb-93ee-b594471de100.png)

If you connect the _icon.png_ by string then everything works correctly:

![изображение](https://user-images.githubusercontent.com/3787132/106427118-3a33d900-6480-11eb-80ac-ae8a41915479.png)

But if the _icon.png_ is placed in a variable, then everything in assets is loaded, because there is a string value _'~/assets/'_ in require and _README.md_ connection error is displayed.

![изображение](https://user-images.githubusercontent.com/3787132/106427134-4324aa80-6480-11eb-9195-1e89351991fb.png)

![изображение](https://user-images.githubusercontent.com/3787132/106427141-47e95e80-6480-11eb-9993-376e8f80624e.png)

The problem is that even if I use the variant from the documentation:

![изображение](https://user-images.githubusercontent.com/3787132/106427342-a282ba80-6480-11eb-9460-74d6bef51577.png)

 it still loads all the _.jpg_ images recursively located in _'~/assets/img/'_. But I have a lot of images in **subfolder** _img_ which I don't need to load and waste time optimizing them. What's the best way to do this?

**Comment by manniL** [comment]
> As far as I understand, when I load an image, everything in the string is taken. To confirm this theory I created a project in assets which has 2 files: README.md and icon.png.

This is correct. Webpack takes every possible file into account that **could match the expression**. This is the reason why you have to be a strict as possible (e.g. `assets/img/some/subfolder/${image}.jpg` instead of `assets/img/${image}`. Those are in your bundle but might not necessarily be loaded all together.

Further read: [How to load dynamic images in Vue and Nuxt with ease](https://blog.lichter.io/posts/dynamic-images-vue-nuxt/)
