### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by abellion** [nuxt/nuxt.js#875]
The amount of memory consumed by the `nuxt start` process never goes down.
The RAM moves upward indefinitely as long as the server receives the requests.

On startup : 
- 116.9 MiB

After 100 requests : 
- 233.0 Mib

Configuration used : 
- `uname -a` : `Linux ab7b196a8fc4 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 GNU/Linux`
- `node -v` : `v7.7.1`
- nuxt version : `nuxt@1.0.0-alpha.3`

**Comment by pi0** [comment]
Hi @abellion . Thanks for report. Please take a look at #805 :)
