### ISSUE TITLE
Using $axios.post() in asyncData, the data received by the server(Django) is always empty.(Only dev mode) / 在asynsData中使用$axios.post(), 后端接收到的数据永远为空.(只在开发模式下)

### ISSUE THREAD

**Issue by BillEliot** [nuxt/nuxt.js#8761]
When I develop with my MacBook, this bug appears, and it only appears in dev mode.  
当我用macbook开发的时候，这个bug就会出现，而且只出现在dev模式下。

### Versions

- Platform: macOS Big Sur 11.2
- nuxt: 2.14.12
- node: 14.15.4

### Reproduction

[Github Reproduction](https://github.com/BillEliot/Nuxtjs_Bug_Reproduction_TestApp)

* TestApp - Nuxt.js(2.14.12)
* Server - Django(3.6.1) with Python 3.9.1

<details open>
<summary>
Only in dev mode, "npm run build & npm start" is normal.  
只在dev模式下，npm run build & npm start是正常的。
</summary>
<br>
</details>

### Steps to reproduce

1.  cd TestApp & npm run dev
2. cd Server & python3 manage.py runserver
3. http://localhost:3000

### What is Expected?

When I enter or refresh the page, the server will receive "<QueryDict: {name ': ['111']}>".
当我进入或者刷新页面的时候，Server会接收到<QueryDict: {'name': ['111']}>。

### What is actually happening?

Server received <QueryDict: {}>. The strange thing is that when I modify something in index.vue and save it, the server will receive <QueryDict: {'name': ['111']}> after the hot update of nuxtjs, which is not what I want .
Server接收到<QueryDict: {}>。奇怪的是，当我在index.vue中修改点什么，然后保存，nuxtjs热更新后服务器会接收到<QueryDict: {'name': ['111']}>，而这并不是我想要的。

**Comment by BillEliot** [comment]
I tried the same operation on a new windows 10 computer, and the result is the same. It seems to be a bug

**Comment by BillEliot** [comment]
You misunderstood what I meant. When the button is clicked, it is indeed successful, but when the page is first entered, the data received by the server is indeed empty.

**Comment by danielroe** [comment]
@BillEliot If you hard-refresh the page in the example above, you will see it is successful then too.

**Comment by jackzer666** [comment]
我也遇到这个问题了，在dev环境中，如果是在启动nuxt服务后第一次进入页面，服务端发出post请求可以获取到数据，但是在强制刷新后，我通过打印发现，重复触发了两次axios的拦截器，第一次post是发出了参数，第二次没有参数。当我再次刷新页面时，可以发现触发了3次拦截器，同样的也是只有第一次有参数。这种情况看起来像是之前的请求被缓存了，我不明白为什么会这样。 @BillEliot 兄弟，你怎么解决这个问题的？

**Comment by wufan123** [comment]
misconfiguration, see @danielroe [Here is an example with everything working fine](https://codesandbox.io/s/optimistic-moon-229yw?file=/pages/index.vue),

**Comment by BillEliot** [comment]
> 

时间太久了，我也忘记了当时那个项目是什么情况了，抱歉！
