### ISSUE TITLE
@nuxt/types vue config have to pass all Vue config properties, otherwise Typescript throws an error

### ISSUE THREAD

**Issue by tomasdziovenas** [nuxt/nuxt.js#8766]
### Versions

- nuxt: 2.14.12

### Reproduction
Creating nuxt.config.ts (typescripted file) with '@nuxt/types' NuxtConfig type and using vue.config property to change vue global configs and only passing one property we get Typescript error, to use them all.

### Steps to reproduce
Just add at least one property to nuxt.config.ts -> vue -> config

### What is Expected?
Allowing to provide any number of properties, and not passing them all.

### What is actually happening?
Typescript asks to use all properties of the NuxtOptionsVueConfiguration typescript type.

And looking at the docs of nuxt we see:
```
export default {
  vue: {
    config: {
      productionTip: true,
      devtools: false
    }
  }
}
```

which is impossible to achieve while using the types as we get:
```
Type '{ ignoredElements: string[]; }' is missing the following properties from type 'VueConfiguration': silent, optionMergeStrategies, devtools, productionTip, and 5 more.ts(2740)
```

### Solution
As I do not have much time right now, but I believe that the options should be Partial<VueConfiguration> and not just VueConfiguration.

```nuxt.js/packages/types/config/index.d.ts```

```
  router: NuxtOptionsRouter
  server: NuxtOptionsServer
  serverMiddleware: NuxtOptionsServerMiddleware[]
  srcDir: string
  transition: Transition
  vue: {
    config?: NuxtOptionsVueConfiguration       <-- this one I believe should be Partial<NuxtOptionsVueConfiguration>
  }
  watch: string[]
  watchers: NuxtOptionsWatchers
}
```

**Comment by danielroe** [comment]
Good spot. Thanks. :heart:

**Comment by tomasdziovenas** [comment]
> Good spot. Thanks. ❤️

No problem, thanks for replying so quickly! <3
