### ISSUE TITLE
sass-loader >11 compatibility

### ISSUE THREAD

**Issue by thefoxie** [nuxt/nuxt.js#8771]
### Versions

- nuxt: 2.14.12
- node: 15

### Reproduction
Update sass-loader to latest release (11.0.0). 

It's happening because it's compatible only with webpack 5. 
https://github.com/webpack-contrib/sass-loader/releases/tag/v11.0.0

### What is Expected?
Build project.

### What is actually happening?
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader
```

**Comment by YallaDealz** [comment]
so did you mean to revert to saas loader v10 to solve this issue ? or upgrade webpack ?

**Comment by YallaDealz** [comment]
ok, good 
but could i upgrade my webpack to v5 ?

**Comment by YallaDealz** [comment]
my packgejson 


{
  "name": "Admin-Portal",
  "version": "2.0.0",
  "private": true,
  "description": "Yalla Dealz Admin Portal",
  "author": "Yalla Dealz Inc",
  "scripts": {
    "build": "nuxt-ts build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "dev": "nuxt-ts",
    "generate": "nuxt-ts generate",
    "lintfix": "eslint --fix --ext .js,.vue --ignore-path .gitignore .",
    "sass": "sass --watch assets/scss/custom.scss:assets/css/bootstrap.css assets/scss/main-style.scss:assets/css/main-style.css",
    "start": "nuxt-ts start",
    "test": "jest",
    "release": "release-it"
  },
  "dependencies": {
    "@babel/preset-env": "^7.12.7",
    "@johmun/vue-tags-input": "^2.1.0",
    "@nuxt/typescript-runtime": "^2.0.0",
    "@nuxtjs/axios": "^5.12.3",
    "@vue/test-utils": "^1.1.1",
    "babel-jest": "^26.6.3",
    "body-parser": "^1.19.0",
    "bootstrap-vue": "^2.20.1",
    "chartist": "^0.11.4",
    "fibers": "^5.0.0",
    "form-data": "^3.0.0",
    "js-cookie": "^2.2.1",
    "node-sass": "^5.0.0",
    "nuxt": "^2.14.10",
    "nuxt-ctk-date-time-picker": "^2.1.1",
    "nuxt-property-decorator": "^2.8.8",
    "sass-loader": "^10.1.1",
    "vue": "^2.6.12",
    "vue-analytics": "^5.22.1",
    "vue-class-component": "^7.2.6",
    "vue-cookie": "^1.1.4",
    "vue-css-donut-chart": "^1.3.0",
    "vue-jest": "^3.0.7",
    "vue-property-decorator": "^9.1.2",
    "vue-qrcode": "^0.3.5",
    "vue-server-renderer": "^2.6.12",
    "vue2-editor": "^2.10.2",
    "vue2-google-maps": "^0.10.7",
    "vuelidate": "^0.7.6",
    "vuetify-datetime-picker": "^2.1.1",
    "vuetify-google-autocomplete": "^2.0.4",
    "vuex-module-decorators": "^1.0.0"
  },
  "release-it": {
    "git": {
      "changelog": "git log --pretty=format:\"* %s (%h)\" ${from}...${to}",
      "requireCleanWorkingDir": false,
      "requireBranch": false,
      "requireUpstream": true,
      "requireCommits": false,
      "addUntrackedFiles": false,
      "commit": true,
      "commitMessage": "Release ${version}",
      "commitArgs": [],
      "tag": true,
      "tagName": null,
      "tagAnnotation": "Release ${version}",
      "tagArgs": [],
      "push": true,
      "pushArgs": [
        "--follow-tags"
      ],
      "pushRepo": ""
    }
  },
  "devDependencies": {
    "@nuxt/types": "^2.14.12",
    "@nuxt/typescript-build": "^2.0.3",
    "@nuxtjs/eslint-config": "^5.0.0",
    "@nuxtjs/vuetify": "^1.11.3",
    "@types/vuelidate": "^0.7.13",
    "@types/webpack-env": "^1.16.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.15.0",
    "jest": "^26.6.3",
    "release-it": "^14.0.0",
    "vue-browser-geolocation": "^1.8.0",
    "vue-template-compiler": "^2.6.12"
  }
}

**Comment by danielroe** [comment]
> ok, good 
> but could i upgrade my webpack to v5 ? 

No. Nuxt 2 is not currently compatible with Webpack 5.

**Comment by YallaDealz** [comment]
ok, so should wait for nuxt 3 , right ?

**Comment by pi0** [comment]
Yes @YallaDealz :) If any important feature introduces in feature releases of sass-loader, we might fork it but at the moment using latest possible for nuxt2 (which is v10)

**Comment by YallaDealz** [comment]
thanks

**Comment by zweeen** [comment]
Thanks @danielroe & @pi0 
Dowgraded sass-loader to version [10.1.1](https://github.com/webpack-contrib/sass-loader/releases/tag/v10.1.1) fix it

`npm uninstall --save-dev sass-loader && npm install --save-dev sass-loader@10.1.1`

**Comment by akarelas** [comment]
Maybe the nuxt documentation page (which says we should install sass-loader by typing `npm install sass-loader`) could be updated, to aid all the sass-using developers?

**Comment by isuke01** [comment]
This is still an issue ;/ 
So now the only wat to use SCSS/SASS in the NUXT is downgrade `sass-loader` ?

**Comment by hippiechick60** [comment]
Thank you so much

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 31, 2021 at 5:13, Daniel ***@***.***> wrote:   


@isuke01 Yes, as indicated above, Nuxt currently requires ***@***.*** rather than ***@***.***

**Comment by mrleblanc101** [comment]
It's confusing because the doc mention to `yarn add sass-loader` not `yarn add sass-loader@10` which lead to a broken projet. The doc should be more explicit now until Nuxt support Webpack 5 and sass-loader@11

**Comment by danielroe** [comment]
@mrleblanc101 Could you give me an example of where the docs say that?

**Comment by mrleblanc101** [comment]
Interesting, can't find it again. But the main pre-processor page is updated since February so you can disregard what I said. If I find the page again I'll update my comment

**Comment by Tarrah102** [comment]
> @mrleblanc101 Could you give me an example of where the docs say that?
https://nuxtjs.org/docs/2.x/features/configuration
"In case you want to use sass make sure that you have installed the sass and sass-loader packages."

It's clarified below this. But there is your example.

**Comment by harapeko** [comment]
it works
`$ npm i -D sass sass-loader@10.1.1 fibers`

```
  "devDependencies": {
    "fibers": "^5.0.0",
    "sass": "^1.36.0",
    "sass-loader": "^10.1.1"
  }
```

not works
`$ npm i -D sass sass-loader@10 fibers`

```
  "devDependencies": {
    "fibers": "^5.0.0",
    "sass": "^1.36.0",
    "sass-loader": "^10.2.0"
  }
```

thx👍

**Comment by FarhanKhalid** [comment]
In webpack there is a configuration that let's you turn off the sass-loaders dependency on fibers, which has been deprecated as of node 16. You can see the config related information here:
https://webpack.js.org/loaders/sass-loader/#sassoptions

Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.
From here: https://github.com/laverdet/node-fibers

I added
sassOptions: {
      fiber: false,
},
To my nuxt build options, and it works again with node 16 after removing fibers from my package.json file.
I hope this helps someone.

**Comment by Jones-S** [comment]
@FarhanKhalid 
Sorry to step in here, but how did you actually add the sassOptions to the nuxt.config?

```
// nuxt.config.js
export default {
// ...
  build: {
    loaders: {
      scss: {
        sassOptions: {
          fiber: false
        }
      }
    }
  },

```
Because this does not have an effect for me.
Or am I doing something wrong?

Thanks in advance.

**Comment by FarhanKhalid** [comment]
@Jones-S I did it like this:

`build: {
    ....
    sassOptions: {
      fiber: false,
    },
 }`

It's not under the loaders attribute.
