### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by gekkedev** [nuxt/nuxt.js#8773]
### Is your feature request related to a problem? Please describe.
In my case, I'm trying to combine Nuxt+Autoimport+Storybook+Typescript. See my elaboration on a specific package below. This would not be a problem if the update interval hadn't changed so drastically. In December, there have been almost biweekly releases, but not this year so far.

### Describe the solution you'd like

Please consider updating a few dependencies, especially the ones maintained by the Nuxt team and the Nuxt community. I. e. I'm hoping for `nuxt/components` to be updated. This package has several released bugfixes which I'd love to see as a dependency update included in Nuxt.

### Describe alternatives you've considered

Manually installing the dependencies + enforcing the new version to be chosen:  
That's a huge mess; difficult when doing it for the first time, just to download a bugfix.

**Comment by pi0** [comment]
Hi @gekkedev. Actually `nuxt` has a range dependency on `@nuxt/components` (as ^1.2.2) and we separated features like components for exactly same reason for faster independent versioning.

You can always get latest semver-minor/patchs by using `yarn upgrade nuxt` or `npm up nuxt` or recreating lock-file :) 

PS: 2.15 has major changes that got pending until now and will be released as stable as soon as possible.

**Comment by gekkedev** [comment]
thanks, that worked :see_no_evil: :bowing_man: looking forward to the update
