### ISSUE TITLE
Nuxt.js hot reloading doesn't work.

### ISSUE THREAD

**Issue by onurusluca** [nuxt/nuxt.js#8776]
"create-nuxt-app" project won't hot-reload.  Looked at these: [this](https://github.com/nuxt/nuxt.js/issues/5550), [this](https://github.com/nuxt/nuxt.js/issues/3061), [this](https://stackoverflow.com/questions/56620999/nuxt-hot-reloading-for-new-components-is-not-working).

Clean nuxt app, nothing added, pc is newly formatted, no other packages or any external code other than pure create-nuxt-app.

Tried:
- Try different browsers
- Change directory
- Update npm packages
- Install WSL 2 with ubuntu(Just in case
- Make a new project without changing anything.
- Try ssr, static, server, content, jamstack etc options while creating the app

### Versions

- nuxt:  2.14.12
- npm: 6.14.10
- node: 14.15.4
- windows 10: 10.0.19042 Build 19042
- vscode: 1.53.0

### Reproduction
No need for reproduction as you only need pure nuxt project without any code or extensions.

### Steps to reproduce
npx create-nuxt-app <project-name>
npm run start

### What is Expected?
Need to reload automatically.

### What is actually happening?
Won't reload. No errors or anything.

**Comment by onurusluca** [comment]
Couldn't find what was the problem but I reinstalled Node.js deleted AppData/Roaming/npm&npmcache.

Would still love to know the problem.

**Comment by onurusluca** [comment]
@danielroe Thanks a lot for the reply. Is it written in the official docs? If not it should be. I didn't know this.

**Comment by danielroe** [comment]
You can find out more at https://nuxtjs.org/docs/2.x/get-started/installation and https://nuxtjs.org/docs/2.x/get-started/commands

I hope this helps.

**Comment by onurusluca** [comment]
Entirely my bad. I didn't pay enough attention. Thanks a lot!
