### ISSUE TITLE
Client App  is not hydrated

### ISSUE THREAD

**Issue by loicgeek** [nuxt/nuxt.js#8793]
### Versions

- nuxt: 2.4.12
- node: 14.12.1

### Reproduction
I could not provide a reproduction code  but here is the screenshot: https://pasteboard.co/JNpteTp.png

<details open>
<summary>Additional Details</summary>
<br>
export default {
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'tile',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content: ,
      },
      {
        name: 'og:site_name',
        content: 'chairwatch.com',
      },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/icon.png' }],
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    '~/assets/css/style.css',
    '@sum.cumo/vue-datepicker/dist/Datepicker.css',
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    { src: '~/plugins/vue-star-rating.js', mode: 'client' },
    { src: '~/plugins/vue-datepicker.js', mode: 'client' },
    { src: '~/plugins/persisted-state.client.js', mode: 'client' },
    { src: '~/plugins/fireauth.js', mode: 'client' },
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    ['@nuxtjs/pwa', { icon: false }],
    '@nuxtjs/toast',
    [
      'nuxt-fontawesome',
      {
        imports: [
          {
            set: '@fortawesome/free-solid-svg-icons',
            icons: ['fas'],
          },
          {
            set: '@fortawesome/free-brands-svg-icons',
            icons: ['fab'],
          },
        ],
      },
    ],
    'nuxtjs-stripe',
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {
    baseURL: '',
  },

  // PWA module configuration: https://go.nuxtjs.dev/pwa
  pwa: {
    manifest: {
      lang: 'en',
    },
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {},
  toast: {
    position: 'top-center',
    register: [
      // Register custom toasts
      {
        name: 'app-error',
        message: (payload) => {
          if (!payload) {
            return 'Oops...Something went wrong'
          }
          return 'Oops...' + payload
        },
        options: {
          type: 'error',
        },
        action: {
          text: 'Close',
          onClick: (e, toastObject) => {
            toastObject.goAway(0)
          },
        },
      },
    ],
  },
  vue: {
    config: {
      productionTip: false,
      devtools: true,
    },
  },
  stripe: {
    /* module options */
    publishableKey: '',
    version: 'v3', // Default
    defer: true, // Default
    async: true, // Default
  },
}

</details>

**Comment by danielroe** [comment]
@loicgeek Without a reproduction, it's not clear that this is a Nuxt issue. You might find [this article](https://blog.lichter.io/posts/vue-hydration-error/) helpful, or feel free to join https://discord.nuxtjs.org to get support.
