### ISSUE TITLE
How can i change this path with `loadNuxt` ?

### ISSUE THREAD

**Issue by zouhangwithsweet** [nuxt/nuxt.js#8797]
When I run a nuxt app with express, I found the server always use this path for distPath. So can I change this path with `config` or programnal code.
https://github.com/nuxt/nuxt.js/blob/da318a5e1a2b191e5b5cb16ab248bd339099b8db/packages/vue-renderer/src/renderer.js#L59

**Comment by pi0** [comment]
Hi @zouhangwithsweet. You may use a nuxt module to replace via `this.nuxt.server.renderer.distPath` but consider that it is an internal prop and `{buildDir}/dist/server` is hardcoded in several places and there is no guarantee.

I would recommend for production pipeline, either exclude the rest of `.nuxt` (with Docker for example adding `.nuxt/dist/server`) or preserve directory structure of `.nuxt` (buildDir)

**Comment by zouhangwithsweet** [comment]
> Hi @zouhangwithsweet. You may use a nuxt module to replace via `this.nuxt.server.renderer.distPath` but consider that it is an internal prop and `{buildDir}/dist/server` is hardcoded in several places and there is no guarantee.
> 
> I would recommend for production pipeline, either exclude the rest of `.nuxt` (with Docker for example adding `.nuxt/dist/server`) or preserve directory structure of `.nuxt` (buildDir)

Yes, I just copy the `.nuxt` into Docker folder. Thanks :)
