### ISSUE TITLE
incorrect links

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#880]
I deduce an array of elements, I register links so `:to="{path: T.link}"`
But after rendering, I see that it is output not at all what I expected, at the beginning of the links some more links are added, as a result of the link, this type of `href="/news/https://site.ru/"`

How can I turn off this append at the beginning of the link?
In the documentation did not find any mention of this

**Comment by alexchopin** [comment]
That's weird, do you use `base` option?

**Comment by wormen** [comment]
@alexchopin 
Tested using `base`, and without it
The result is the same

**Comment by alexchopin** [comment]
Do you use Nuxt server rendered or static generated?

**Comment by wormen** [comment]
use with express

**Comment by wormen** [comment]
When to expect corrections?

**Comment by alexchopin** [comment]
I can not reproduce this issue, can you share a repo to help you?
