### ISSUE TITLE
Setting custom store folder in dir.store breaks the context passed to plugins

### ISSUE THREAD

**Issue by mathieuartu** [nuxt/nuxt.js#8807]
### Versions

- nuxt: v2.12.2
- node: v14.9.0

### Problem

When using a custom store folder, context.store is undefined when instantiating a plugin

### Reproduction

With a simple store/index.ts file as 

    export const state = () => {}
    
    export const actions = {
        nuxtServerInit() {
        },
    }

Logging the store in the context when creating a plugin works as expected :

    export default someNuxtPlugin = ({ store }, inject) => {
        console.log(store) // Logs the store in the context
    }

But if I move `store/index.ts` to a custom folder, let's say `custom_store/index.ts`
And set in `nuxt.config.ts` the option `dir: { store: 'custom_store' }`

The console.log in the plugin above will log `undefined` (everything else in the context object works but the store)

Is there something in the pattern I don't see, or is this a bug?

**Comment by danielroe** [comment]
Does this happen if the files are.js instead?

**Comment by mathieuartu** [comment]
> Does this happen if the files are.js instead?

Yes unfortunately, just tried this very instant 😢

**Comment by mathieuartu** [comment]
I tried to repro on codesandbox with nuxt-ts and it worked, so... 😅
Thanks for clocking the time to try to reproduce it!
It's much likely a problem with an additional dependency in our project then, I think I can close this one.
