### ISSUE TITLE
cpu above 100% 

### ISSUE THREAD

**Issue by fxh615** [nuxt/nuxt.js#881]
is there someone have the same problem on nuxt.

**Comment by pi0** [comment]
Is this problem happening in production? How much server resources do you have and what's amount of requests incoming to SSR engine?

**Comment by fxh615** [comment]
production   ssr  element-ui  axios

**Comment by fxh615** [comment]
1568 root      20   0 2478136 1.461g  12692 R _135.3%_  9.4   3:08.17 node

**Comment by fxh615** [comment]
run top result

**Comment by cesasol** [comment]
I can confirm this is not happening on a production app i'm working on. _Pretty bad coded._

The environment is a plesk box from mediatemple: `Linux dv.dinamo.mx 3.10.0-042stab120.11 #1 SMP Wed Nov 16 12:05:45 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vhtml** [comment]
@fxh615 I have the same problem in production when a page is frequent refresh.

**Comment by vhtml** [comment]
After an analysis of heapdump, it's due to the problem about  'tough-cookie' package. For example, you are using the 'request' package.

**Comment by fxh615** [comment]
@vhtml  is axios problem . on the server side you can del the axios.interceptors and it work well .
