### ISSUE TITLE
nuxtServerInit + serverMiddleware's API = connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by gigioSouza** [nuxt/nuxt.js#8817]
### Versions

- nuxt: 2.14.12
- node: v14.15.4

### Reproduction

https://github.com/gigioSouza/wallet-bugsample

I added an express [API in the serverMiddleware](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-servermiddleware#custom-api-endpoint) and I'm trying to access the API in [`nuxtServerInit` action](https://nuxtjs.org/docs/2.x/directory-structure/store#the-nuxtserverinit-action) and I'm getting an error, but when accessing from client-side it works.

Besides the default generated `nuxt.config.js`, I added this extra configurations:
```js
  ...
  serverMiddleware: [
    '~/api'
  ],
  server: {
    port: 3000
  },
  mode: 'universal'
};
```

The `nuxtServerInit` is:
```js
async function nuxtServerInit({ dispatch }) {
  await dispatch('ping');
  await dispatch('configs/fetchIncomeTypes');
  await dispatch('configs/fetchExpenseTypes');
}
```
The only route that will return 200 ok is the one called by `await dispatch('ping');` the other ones will return 500 due the lack of database connection.

### Steps to reproduce

Install dependencies `npm install` or `yarn`

Run `npm run dev` or `yarn dev`

By simply opening the application in the browser the errors will be visible in the terminal.

### What is Expected?
Access the serverMiddleware API from `nuxtServerInit`

### What is actually happening?
Getting an error while accessing the API in `nuxtServerInit`

```
connect ECONNREFUSED 127.0.0.1:80                                                                                                                                                                                        00:20:56

  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

**Comment by danielroe** [comment]
@gigioSouza From what you've said this doesn't sound like an issue with serverMiddleware but a problem connecting to your database. Is MONGO_URL correctly defined?

**Comment by gigioSouza** [comment]
@danielroe no, that's not the issue.
I did the connection correctly and tested it. As I said, calling the API outside the nuxtServerInit works perfectly fine.

Even if that was the issue, I'd get an HTTP error, not an `ECONNREFUSED`

You can remove those calls and see the error only with the `/api/ping` call

store/index.js:
```js
async function nuxtServerInit({ dispatch }) {
  await dispatch('ping');
//  await dispatch('configs/fetchIncomeTypes');
//  await dispatch('configs/fetchExpenseTypes');
}
```

api/index.js:
```js
import express from 'express';
import cors from 'cors';
import IncomeTypes from './income-types';
import ExpenseTypes from './expense-types';

const app = express();
app.use(express.json());
app.use(cors());

app.get('/ping', (req, res) => {
  res.send('pong');
});

// IncomeTypes(app);
// ExpenseTypes(app);

export default {
  path: '/api',
  handle: app
}

```

**Comment by gigioSouza** [comment]
Thank you @danielroe!
The issue was really it, should have read the [nuxtjs axios module](https://axios.nuxtjs.org/) before.

**Comment by Abdalla-Hiekal** [comment]
The solution is not very clear to me...
I tried to use Axios/Nuxt, but it's not working.
here is the code of the test example.
this is the main module for the store (index.js)
`export const actions = {
  
  async getHim({ commit }) {
    let res = await this.$axios.$get('/api/user/')
    commit('authentication/setData', res.data)
  },
  async nuxtServerInit({ dispatch }) {
    await dispatch('getHim')
  }
  
}`
and this nust.config.js
`  modules: ['@nuxtjs/axios'],

  publicRuntimeConfig: {
    axios: {
      browserBaseURL: process.env.BROWSER_BASE_URL
    }
  },

  privateRuntimeConfig: {
    axios: {
      baseURL: process.env.BASE_URL
    }
  },`
