### ISSUE TITLE
Problems with Nuxt project and jsencrypt package

### ISSUE THREAD

**Issue by dforce2055** [nuxt/nuxt.js#8818]
### Versions

- nuxt: Nuxt @ v2.14.12
- node: v10.16.3

Hi everyone, I have a problem with npm package **jsencrypt** in my nuxt proyect.
https://www.npmjs.com/package/jsencrypt

I need to encrypt the passwords to be able to login to the API.
this library works fine with my project in VUE, but with the need for SSR, I am migrating my application to nuxt, but this library is causing me an error. 
I tried with a clean nuxt project without any dependencies, with npx, npm and yarn package manager. The result it's the same.

These are my steps:
### Steps to reproduce
1- npm install --save jsencrypt
2- import JSEncrypt from 'jsencrypt'  /store/user.js
3- The server updates

### What is Expected?
I Expect to encrypt the passwords strings with a method in my store

### What is actually happening?
The server goes down

![image](https://user-images.githubusercontent.com/7773845/107771947-49d1de00-6d1a-11eb-92ff-0de88afa179a.png)
[message.txt](https://github.com/nuxt/nuxt.js/files/5971941/message.txt)

**Comment by danielroe** [comment]
@dforce2055 Try adding `jsencrypt` to your `build.transpile` array.

**Comment by dforce2055** [comment]
> @dforce2055 Try adding `jsencrypt` to your `build.transpile` array.

Hi danielroe, yes I'm tried, but still not working.
![image](https://user-images.githubusercontent.com/7773845/107779341-f82e5100-6d23-11eb-97da-2d5be55d72bd.png)
![image](https://user-images.githubusercontent.com/7773845/107779582-53604380-6d24-11eb-9988-02525b6d46d5.png)
