### ISSUE TITLE
it has one error in IE 10：object is not defined find 

### ISSUE THREAD

**Issue by webKity** [nuxt/nuxt.js#882]
it has one error in IE 10：object is not defined find
![image](https://user-images.githubusercontent.com/8474916/27065138-2d9c4d40-502e-11e7-843a-62c0556cfa19.png)

**Comment by webKity** [comment]
steps:
1. vue init nuxt/starter test
2. cd test
3. npm install
4. npm run dev
5. open http://127.0.0.1:3000/ in IE10
and the error will come up

**Comment by clarkdo** [comment]
@webKity 
Array.prototype.find is not possibly to statically transpile. You need polyfill. https://babeljs.io/docs/usage/polyfill/
You may do sth like below:
1. cd test
2. npm install --save babel-polyfill
3. bundle polyfiil into vender
    ```json
    build: {
      vendor: ['babel-polyfill']
    }
    ```

**Comment by webKity** [comment]
I tried it and it works，think you very much
