### ISSUE TITLE
Nuxt@2.15.0 component prefix changes

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt.js#8827]
Some of the custom components (with auto-import feature enabled) are no longer found and the standard message is thrown:
`Unknown custom element: <LanguageSwitcher> - did you register the component correctly?`.

What I found is that `<language-switcher>` works, whether the syntax I used before 2.15.0 (`<LanguageSwitcher>`) doesn't, as from what I noticed it most likely resolves to `<languageswitcher>`.

**Comment by polymer-coder** [comment]
Same on my end

**Comment by pi0** [comment]
Hi @DamianGlowala. Would you mind sharing generated `.nuxt/components/plugin.js` file?

**Comment by DamianGlowala** [comment]
Hi @pi0. I've only tried the local dev mode and stopped at this stage, but will try to build the project and provide you with the plugin.js file within an hour or so as I'm temporarily away from my laptop (unless one of you guys having the same issue could drop it there) 👍

**Comment by DamianGlowala** [comment]
@pi0 here you are:

[plugin.js](https://drive.google.com/file/d/1Sfu2LGF7RlU1dZjhaqVNcZIeVvHub0tj/view?usp=sharing)

**Comment by pi0** [comment]
Thanks for sharing @DamianGlowala. If you notice in generated file, component name is changed to `PagesIndexLanguageSwitcher` since with 2.15, we use full-path to prefix component names (`components/pages/index/LanguageSwitcher.vue`). This is to avoid two components with same name conflicting. You need to either use new name or update `nuxt.config` as below to explicitly allow old behavior:

```js
// nuxt.config.js
export default {
  components: [
    '~/components',
   '~/components/pages/index`
  ]
}
```

 - [components migration guide](https://github.com/nuxt/components#migration-guide)
 - [2.15 release notes[https://github.com/nuxt/nuxt.js/releases/tag/v2.15.0]

**Comment by DamianGlowala** [comment]
Thank you for the clear explanation of what has changed between these versions in regards to component naming and the possible alternative of allowing old behaviour. 

Closing the issue :)

**Comment by simeon9696** [comment]
> Thanks for sharing @DamianGlowala. If you notice in generated file, component name is changed to `PagesIndexLanguageSwitcher` since with 2.15, we use full-path to prefix component names (`components/pages/index/LanguageSwitcher.vue` => `PagesIndexLanguageSwitcher` ). This is to avoid two components with same name conflicting. You need to either use new name or update `nuxt.config` as below to explicitly allow old behavior:
> 
> ```js
> // nuxt.config.js
> export default {
>   components: [
>     '~/components',
>    '~/components/pages/index`
>   ]
> }
> ```
> 
> * [Components migration guide](https://github.com/nuxt/components#migration-guide)
> * [2.15 release notes](https://github.com/nuxt/nuxt.js/releases/tag/v2.15.0)

This did help a lot but just a note.  The end component only capitalizes the first letter of each folder name. 

Example ```components/pages/newindex/LanguageSwitcher.vue => PagesNewindexLanguageSwitcher NOT PagesNewIndexLanguageSwitcher```

If you want the end component name to be `PagesNewIndexLanguageSwitcher` you'd have to name the folder to suit `components/pages/newIndex/LanguageSwitcher.vue `
