### ISSUE TITLE
Async Data fails when reload page (server-side rendering)

### ISSUE THREAD

**Issue by ysds** [nuxt/nuxt.js#883]
I got an error in [Async Data example](https://nuxtjs.org/examples/async-data), when I open the http://localhost:3000/posts directly or reload the page.

![error](https://user-images.githubusercontent.com/4065765/27080599-a1c8556c-5077-11e7-84ea-51a96be500cf.png)

How can i solve this problem?

**Comment by piyushchauhan2011** [comment]
Is it the same code as in `asyncData` ? @ysds

**Comment by ysds** [comment]
@piyushchauhan2011  Yes, I just did the following:
```bash
git clone https://github.com/nuxt/nuxt.js.git
cd nuxt.js/examples/async-data
npm i
npm run dev
```
Then I get the above error when trying to access the http://localhost:3000/posts.

My enviroment is:
- Windows 7 64bit
- Node v6.9.0
- npm 4.1.2
- Chrome 59

**Comment by piyushchauhan2011** [comment]
Hmm, @ysds  maybe something related to windows ? Also I'm running Node 8.x currently. I cloned the repo before this and ran above steps, did hard refresh on http://localhost:3000/posts. Works perfectly.

My enviroment is:

- OSX 10.12.5
- Node v8.1.2
- npm 5.0.3
- Chrome 59

**Comment by ysds** [comment]
Sorry, I noticed the problem was caused by my internet environment (proxy).
