### ISSUE TITLE
Error: Expected identifier, string or number (Nuxt 12.15.0)

### ISSUE THREAD

**Issue by Sendoo** [nuxt/nuxt.js#8839]
### Versions

- nuxt: v2.15.0
- node: v14.15.4
- OS : Windows 10 20H2
- browser: Edge 18

### Reproduction

`Expected identifier, string or number`

After upgrading Nuxt to version 2.15.0 in Edge 18 and IE 11, I got an error like this which blocks the application 

![изображение](https://user-images.githubusercontent.com/46229254/108105570-762c8800-7095-11eb-9974-e7c17cb1a3f2.png)

**Comment by danielroe** [comment]
@Sendoo Would you try adding `'ufo'` to `build.transpile`?

**Comment by Sendoo** [comment]
> 
> 
> @Sendoo Would you try adding `'ufo'` to `build.transpile`?

It helped, thanks.
There is no more error.
Will this be fixed in future releases? 🙂

**Comment by radum** [comment]
This is just a temporary fix, I am getting other errors after fixing UFO. The promise polyfill is not added anymore.
