### ISSUE TITLE
Option to disable build progress bars in CLI even when TTY is enabled

### ISSUE THREAD

**Issue by Soviut** [nuxt/nuxt.js#8844]
### Is your feature request related to a problem? Please describe.

I use Docker and wanted to enable TTY so I could see colours in Docker Compose logs. However, enabling TTY also renders the webpack progress bars during builds. The bars work but have some rendering issues, most likely due to Docker Compose prefixing each log line with with the container name.

For example, the Client and Server bars render twice for each update.

![image](https://user-images.githubusercontent.com/226882/108170832-a6d9e500-70c8-11eb-9e77-7bcdaa59a3b2.png)

### Describe the solution you'd like

A top level option, or documentation, on how to disable the progress bars in the CLI, even in a development environment would be very useful. I'd be able to keep TTY enabled without the rendering issues.

Ideally this would not disable the progress bars displayed in the browser during build.

Basically, I'd like the result I get with TTY disabled, but with colours.

![image](https://user-images.githubusercontent.com/226882/108171189-28317780-70c9-11eb-8624-7d3e0e110977.png)

and during an update...

![image](https://user-images.githubusercontent.com/226882/108172173-7dba5400-70ca-11eb-9a35-6e1b9387fc8e.png)

### Describe alternatives you've considered

For now, I run with TTY disabled in Docker Compose, however, I lose colours.

I tried configuring the plugin in the nuxt.config.js build `extend()` function but couldn't seem to get any options to override.

I tried removing the progress bar plugin from the `config.plugins` list in `extend(config)` but that broke a bunch of things Nuxt or webpack was relying on.

I could also cut a bug ticket on the https://github.com/nuxt-contrib/webpackbar repo to see if the rendering can be fixed inside a docker TTY with the line prefixing.

**Comment by Soviut** [comment]
Naturally, as soon as I posted this, I decided to try one last configuration that targeted the progress bar reporters.

// nuxt.config.js
```javascript
export default {
  // ...
  
  build: {
    extend: (config) => {
      const bar = config.plugins.find((p) => p.constructor.name === 'WebpackBarPlugin')
      bar.reporters = bar.reporters.filter((r) => r.constructor.name !== 'FancyReporter')
    }
  }
}
```

This worked!

By removing the `FancyReporter` from the `WebpackBarPlugin`'s array of reporters it disabled the progress bars in the CLI but kept the progress bars in the browser.

It would appear that changing the `WebpackBarPlugin.options.fancy = false` doesn't work because the plugin already populated the `reporters` array based on that config (and environment) during setup.

I'll leave this here and keep the issue open since it may still be a good idea to streamline this process.

**Comment by Soviut** [comment]
Some further investigation found that the previous example wasn't fully doing what I needed. It was removing the anonymous reporter that renders the progress bars in the browser. So instead of simply removing the `FancyReporter`, I wound up having to "clone" the `WebpackBarPlugin`, include the `basic` reporter and exclude the `FancyReporter`.

So here's the masterpiece

```javascript
import isDocker from 'is-docker'

export default {
  build: {
    extend(config) {
      // hide the build progress bars in the CLI (but not the browser)
      // since they do not render correctly in docker-compose logs
      if (isDocker()) {
        const i = config.plugins.findIndex(
          (p) => p.constructor.name === 'WebpackBarPlugin'
        )
        const plugin = config.plugins[i]

        // replace existing bar plugins with clones that exclude the 'fancy'
        // reporter and include a 'basic' reporter
        config.plugins.splice(
          i,
          1,
          new WebpackBarPlugin({
            name: plugin.options.name,
            reporters: [
              'basic', // include reporter as string because we cannot import
              ...plugin.reporters.filter(
                (p) => p.constructor.name !== 'FancyReporter'
              ),
            ],
          })
        )
      }
    }
  }
}
```

**Comment by Soviut** [comment]
For future me, it looks like here is where you'd have to start to implement this as a nuxt option

https://github.com/nuxt/nuxt.js/blob/ba44b0f9ca8955ddb884744f34192c831b2d1d16/packages/webpack/src/config/base.js#L445

**Comment by pi0** [comment]
Hi @Soviut. Have you tried `MINIMAL=1` environment variable?

**Comment by Soviut** [comment]
@pi0 I didn't know that was available but it seems to do the same thing. Is that environment variable controlling `std-env` to make `env.minimalCLI`?

**Comment by pi0** [comment]
>  Is that environment variable controlling std-env to make env.minimalCLI?
Yes :)

**Comment by Soviut** [comment]
Thanks. I cut a ticket on the std-env repo to update the README with the environment variables. I'll see if I can contribute that documentation soon after. 

https://github.com/nuxt-contrib/std-env/issues/9
