### ISSUE TITLE
 Error [ERR_REQUIRE_ESM]: Must use import to load ES Module (v2.15.0) 

### ISSUE THREAD

**Issue by Phara0h** [nuxt/nuxt.js#8857]
### Versions

- nuxt: v2.15.0
- node: v12.16.1

### Reproduction

importing an esm inside your nuxt.config.js.

```js
import Test  from './assets/js/test.mjs';
module.exports = {

}
```
assets/js/test.mjs
```js
export class Test {
  constructor() {}
}
export default Test;

```

### Steps to reproduce

1. set up your nuxt.config.js like above
2. run ```nuxt build```

### What is Expected?

Not to fail 

### What is actually happening?

Seems you removed "jakejs" and that change or maybe something else caused a bunch of problems regarding dependencies. Everything was working just fine in v2.14.6

**Comment by Phara0h** [comment]
Any updates on this?

**Comment by theprivileges** [comment]
I'm experiencing the same issue: 

- nuxt: v2.15.2
- node: v14.15.4

**Comment by pi0** [comment]
Hi. Pardon me for late response. Issue with `.mjs` extension is fixed in jiti@1.5.0. Best way to get update is to recreate `yarn.lock`/`package.lock.json`

**Comment by kauhat** [comment]
Fixed for me after updating my lockfile. Appreciate the help, thanks!

**Comment by linqFR** [comment]
yes same here! thanks!

**Comment by kukosek** [comment]
Fixed for me by upgrading nuxt js
