### ISSUE TITLE
Custom publicPath not working with electron

### ISSUE THREAD

**Issue by tmtk75** [nuxt/nuxt.js#8863]
**Error message**: v2.15.0 ChunkLoadError: Loading chunk 2 failed. (works with v2.14)

### Versions
- nuxt: v2.15.0
- electron: v11.2.3

It works with nuxt-v2.14.12.

### Reproduction
I made a minimum code to reproduce.
https://github.com/tmtk75/nuxt-2-15-reproduce

### Steps to reproduce
You can reproduce with https://github.com/tmtk75/nuxt-2-15-reproduce.
```
yarn && yarn clean && yarn build && yarn start
```

### What is Expected?
It works even with v2.15 as v2.14.
Otherwise, there is another way or a workaround with v2.15.

### What is actually happening?
I can see `ChunkLoadError: Loading chunk 2 failed.` on DevTools when application is launching.

<img width="77%" alt="screenshot" src="https://user-images.githubusercontent.com/425100/108579501-7022f980-736a-11eb-98f6-d67d7cfaad31.png">

**Comment by maximilianschmid** [comment]
Same here, worked on 2.14.12, broken on 2.15.0 and on 2.15.1

**Comment by tmtk75** [comment]
I checked `index.html` generated by 2.15.0 and 2.14.12.
```
  <link rel="preload" href="/_nuxt/a1afa35.js" as="script">
  <link rel="preload" href="/_nuxt/04b3a65.js" as="script">
  <link rel="preload" href="/_nuxt/71c6f38.js" as="script">
  <link rel="preload" href="/_nuxt/5c38671.js" as="script">
```
Paths for script are like this for 2.15.0. They start with `/_nuxt/`.
2.14.12 generates paths start with `./_nuxt`.

Also I found this code in `a1afa35.js` by 2.15.0. `l.p` is `/_nuxt/` when I check it with `console.log`. For 2.14.12 there is similar code and it's `./_nuxt/`.
```
  return l.p + "" + { 2: "181c29f" }[e] + ".js";
```

> What do you expect to happen with a relative publicPath like this one?

My expectation is that `./_nuxt/` given with `publicPath` is used for script paths but not `/_nuxt/`.

Actually it's not only for electron but also for usual browser.

----
I attached two tarballs.
* [dist-2.15.tar.gz](https://github.com/nuxt/nuxt.js/files/6015122/dist-2.15.tar.gz)
* [dist-2.14.tar.gz](https://github.com/nuxt/nuxt.js/files/6015126/dist-2.14.tar.gz)

Each one was generated with https://github.com/tmtk75/nuxt-2-15-reproduce.

Please extract `dist-2.1[45].tar.gz` and take a look at index.html inside.

**Comment by danielroe** [comment]
@tmtk75 I can reproduce the issue. I'm just asking what you expect to happen if a relative path is used without hash routing.

**Comment by tmtk75** [comment]
@danielroe 
If router.mode is history, it totally doesn't work for the both 2.15.0 and 2.14.12 for me.
"Doesn't work" mean that I cannot open index.html properly even with 2.14.12 if router.mode is history.
Then I'm using `hash` mode.

2.14.12 & router.mode is `history`.
<img width="33%" alt="スクリーンショット 2021-02-20 23 43 34" src="https://user-images.githubusercontent.com/425100/108599644-c1b49e00-73d5-11eb-9690-55168f923d89.png">

2.14.12 & router.mode is `hash`.
<img width="33%" alt="スクリーンショット 2021-02-20 23 43 43" src="https://user-images.githubusercontent.com/425100/108599646-c2e5cb00-73d5-11eb-8853-eccf85713855.png">

I attached additional two tarballs that router.mode is history.
* [dist-2.15-history.tar.gz](https://github.com/nuxt/nuxt.js/files/6015186/dist-2.15-history.tar.gz)
* [dist-2.14-history.tar.gz](https://github.com/nuxt/nuxt.js/files/6015188/dist-2.14-history.tar.gz)

Regarding the generated script paths, they seem to be similarly generated as hash mode. For 2.15, it's `/_nuxt/`, For 2.14, it's `./_nuxt/`.

Does this make sense for you? I hope this helps you.

**Comment by maximilianschmid** [comment]
> My expectation is that ./_nuxt/ given with publicPath is used for script paths but not /_nuxt/.

We are running a nuxt app via file:/// protocol, and we would expect static hashmode to generate relative urls  ./_nuxt/  as it did in 2.14.  Relative path ./_nuxt/  ist the right behaviour for a static app.

**Comment by maximilianschmid** [comment]
@danielroe any updates on this issue. For us this is a blocking bug which prevents us from upgrading to 2.15.x from 2.14.x.
You wrote that you have a fix in place. Could you provide this patch so I could test the patch if you want to.

**Comment by maximilianschmid** [comment]
@danielroe Tested 2.15.3, now relative public paths works like a charm in hash bang mode SPA. Thank you for fixing this so quick.

**Comment by tmtk75** [comment]
It sounds good for you, @maximilianschmid 

Unfortunately, as for me, it still doesn't work using https://github.com/tmtk75/nuxt-2-15-reproduce.
I upgraded nuxt and fix nuxt.config.ts for the repository but I still get the same error even with 2.15.3.
Am I missing something?
I'm seeing generated path in script tags like `src="/_nuxt/dce7daf.js"`.

<img width="77%" alt="スクリーンショット 2021-03-11 17 17 28" src="https://user-images.githubusercontent.com/425100/110756557-b5fa2000-828d-11eb-8af8-f1f90935dcea.png">

**Comment by tmtk75** [comment]
Here is a generated `dist/index.html` with 2.15.3 for me.
It's relative path for href of link tag in head, but path starts with `/` in script tags.
This doesn't work with `file://` like `file:///private/tmp/nuxt-2-15-reproduce/dist/index.html#/`.

They were relative path before 2.15.3.
@danielroe is it possible to be relative path for both href of link tag and src of script tag?

```
main:nuxt-2-15-reproduce$ cat dist/index.html
<!doctype html>
<html>
  <head>
    <link rel="preload" href="./_nuxt/7f7bc16.js" as="script"><link rel="preload" href="./_nuxt/cc4530b.js" as="script"><link rel="preload" href="./_nuxt/a305519.js" as="script"><link rel="preload" href="./_nuxt/5302637.js" as="script">
  </head>
  <body>
    <div id="__nuxt"><style>#nuxt-loading{background:#fff;visibility:hidden;opacity:0;position:absolute;left:0;right:0;top:0;bottom:0;display:flex;justify-content:center;align-items:center;flex-direction:column;animation:nuxtLoadingIn 10s ease;-webkit-animation:nuxtLoadingIn 10s ease;animation-fill-mode:forwards;overflow:hidden}@keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}@-webkit-keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}#nuxt-loading>div,#nuxt-loading>div:after{border-radius:50%;width:5rem;height:5rem}#nuxt-loading>div{font-size:10px;position:relative;text-indent:-9999em;border:.5rem solid #f5f5f5;border-left:.5rem solid #000;-webkit-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);-webkit-animation:nuxtLoading 1.1s infinite linear;animation:nuxtLoading 1.1s infinite linear}#nuxt-loading.error>div{border-left:.5rem solid #ff4500;animation-duration:5s}@-webkit-keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}</style><script>window.addEventListener("error",function(){var e=document.getElementById("nuxt-loading");e&&(e.className+=" error")})</script><div id="nuxt-loading" aria-live="polite" role="status"><div>Loading...</div></div></div><script>window.__NUXT__={config:{app:{basePath:"/",assetsPath:"./_nuxt/",cdnURL:null}}}</script>
  <script src="/_nuxt/7f7bc16.js"></script><script src="/_nuxt/cc4530b.js"></script><script src="/_nuxt/a305519.js"></script><script src="/_nuxt/5302637.js"></script></body>
</html>
```

**Comment by nasangw** [comment]
This is a question I've been wondering too.
I would like to find an answer to this question, but does anyone know?
I can't find in the official documentation what to do in nuxt.config.js.
