### ISSUE TITLE
Page transitions on dynamic pages not working

### ISSUE THREAD

**Issue by nomadoda** [nuxt/nuxt.js#8867]
I have tried following documentation on how to generate page transitions for dynamic page routes here: https://nuxtjs.org/docs/2.x/features/nuxt-components#the-nuxt-component

I've implemented the NuxtChildKey property, and can confirm keys are unique. Page transition from pages/index.vue to pages/_slug.vue works, but I'm unable to get transitions between pages/_slug.vue routes working.

### Versions
- nuxt: v2.14.8
- node: v12.20.0

### Reproduction
It's a small project:
https://github.com/zodiapps/restaurang-stora-holm/tree/nuxt-transition-bug

### Steps to reproduce
1) Run `yarn dev` and navigate to a _slug route.
2) Notice page transition works
3) Navigate from one _slug route to another _slug route

### What is Expected?
Page transition

### What is actually happening?
No page transition

**Comment by hanneskuettner** [comment]
After having looked at your code it seems like you need only provide a transition function (or key) in your `pages/index.vue`. 

However also you need to provide a transition key (or function) to your `_slug` page if you want to have transitions between them.

**Comment by nomadoda** [comment]
Thank you so much for taking a look! It surely helped adding a transition function to the _slug.page! I got stuck on this part of the documentation:

> The <Nuxt> component can take the prop of nuxt-child-key. This prop will be passed to <RouterView> so that your transitions will work correctly inside dynamic pages.
