### ISSUE TITLE
when i use `this.$router.push({path: name})` link to page , the page head title and meta can't change,

### ISSUE THREAD

**Issue by murongg** [nuxt/nuxt.js#8873]
### Versions

- nuxt: 2.14.7
- node: v12.16.3

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

when i use `this.$router.push({path: name})` link to page , the page head title and meta can't change,
error code:
```
this.$router.push({
  path: `/project`
})
```
success code:
```
window.location.href = '/project'
```
project page code:
```
<script>
export default {
  head() {
    return {
      title: 'project',
      meta: [
        {
          hid: 'description',
          name: 'description',
          content: '.......',
        },
        { hid: 'keywords', name: 'keywords', content: '.......' },
      ],
    }
  },
}
</script>
```
### What is Expected?
when i use `this.$router.push({path: name})` link to page, the page head title and meta can change,

**Comment by Luxuriagk** [comment]
I just found out a page with asyncData will display the page head title & meta correctly but this is not the proper solution.
Hope they solve this as soon as possible.
```
asyncData()
{
    let p = new Promise((resolve) =>
    {
        setTimeout(() =>
        {
            resolve();
        }, 10);
    });
    return p.then(() => { return {}; });
}
```

**Comment by danielroe** [comment]
@Luxuriagk Would you provide a reproduction via https://template.nuxtjs.org/ ?
