### ISSUE TITLE
How to diable auto formatting the code

### ISSUE THREAD

**Issue by dhara15101991** [nuxt/nuxt.js#8876]
### Versions

- nuxt: ^2.15.0
- node: v12.18.3

I am facing an issue because of auto-formatting done by Nuxt. Is it possible to disable autoformatting some vue files or for the whole project? 

I am using VueSlickCarousel plugin for the slick slider. There I need to pass some options. When I try to pass "asNavFor" this option is converted to "as-nav-for" automatically. I need to stop there. 

Can anyone please tell me how to disable it?

**Comment by dhara15101991** [comment]
First I was using it on Visual code and Vetur extension. To check, I moved to the NetBeans where no plugin installed for formatting. and it's still happening. That means it's not an extension but something else causing this issue. Let me check with eslint because I haven't used prettier.

**Comment by danielroe** [comment]
@dhara15101991 Yes, it can 😊

**Comment by dhara15101991** [comment]
Thanks, @danielroe for your hint. It was the issue of the editor. solve it
