### ISSUE TITLE
 The problem of Using the nuxt + iview framework 

### ISSUE THREAD

**Issue by heiyeliuying** [nuxt/nuxt.js#888]
Everything is ok when i coding in dev environment.
then i run the next step 
`npm run generate`
and deploy the code in dist to http-server .
access it .it is ok ,
but A lot of style completely messed up .
can you tell me how to fix this ?

**Comment by PierreRambaud** [comment]
Hi, I'm interesting about how you integrate `iview` with `nuxt`, 
I have the following error:

```
Nuxt.js Error:

ReferenceError: window is not defined
```

I add `view` in build/vendor and create the plugin:

```
import Vue from 'vue';
import iview from 'iview';

Vue.use(iview);
```

Regards

**Comment by prestanesia** [comment]
in nuxt.config.js, set the iview plugin with ssr option to false:

`plugins: [ { src: '~plugins/iview', ssr: false } ],`

**Comment by PierreRambaud** [comment]
Yes that what i did, but iview say they support ssr, that's why it's weird.

**Comment by prestanesia** [comment]
@heiyeliuying are you deploying to a sub folder or root ? hows running:

`serve dist/ --cache 0`

is the style still messed up ?

**Comment by StasB93R** [comment]
i have it all working but it keeps giving me [Vue-warn] 

`
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
`

**Comment by StasB93R** [comment]
you forgot to do this `import 'iview/dist/styles/iview.css'; `
it has to be in your iview.js in plugin folder
