### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by pazfelipe** [nuxt/nuxt.js#8884]
**Versions**

    nuxt: 2.15.1
    node: 15.8.0

**Reproduction**
Make a new project and try to run it as dev mode.

**Steps to reproduce**
See above

**What is Expected?**
It should start an application from scratch without any kind of errors.

**What is actually happening?**
I've got followed all possible tips that I've found here on github. I've already installed `babel-plugin-transform-regenerator` but even so this error does not disappear. I've started a new application from scratch using `yarn create nuxt-app ...` and nothing works. I'm using Fedora 33, Node v15.8.0 and nuxt v2.15.1 (I've removed nuxt from package.json and reinstalled again).

![image](https://user-images.githubusercontent.com/19727571/108803684-0711d080-757a-11eb-8906-8e53ea469eb3.png)

**Comment by clixmat** [comment]
Also here :(

**Comment by prabodhana** [comment]
Also here :(

**Comment by lipengzhou** [comment]
1. Install dependencies

```shell
npm i -D @babel/preset-env
npm i @babel/plugin-transform-runtime
npm i @babel/runtime
```

2. Nuxt config file

```js
// nuxt.config.js
export default {
  ...

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    babel: {
      presets(env, [preset, options]) {
        return [["@babel/preset-env", {}]];
      },
      plugins: [
        [
          "@babel/plugin-transform-runtime",
          {
            regenerator: true
          }
        ]
      ]
    }
  }
};

```

3. Re run Nuxt app

```shell
npm run dev
```

**Comment by pi0** [comment]
Hi. Would you please try with 2.15.2 if regenerator error still happens? (working good with FF@85.0.2)

**Comment by pazfelipe** [comment]
> 2.15.2

I've installed version `2.15.2` and everything is working as expected. Thanks @pi0
