### ISSUE TITLE
nuxt generate ERROR connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by LolitaSquad** [nuxt/nuxt.js#8892]
![2021-02-23 20 11 29](https://user-images.githubusercontent.com/72801242/108842424-3a08a280-7614-11eb-8cf1-b461b9596b34.png)
![2021-02-23 20 12 09](https://user-images.githubusercontent.com/72801242/108842461-455bce00-7614-11eb-851d-bf2a58adc110.png)

Error message：

>  ERROR  connect ECONNREFUSED 127.0.0.1:3000                                                                                 
> 
>   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
> 
> 
>  ERROR  connect ECONNREFUSED 127.0.0.1:3000                                                                                   
> 
>   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
> 
> 
>  ERROR  connect ECONNREFUSED 127.0.0.1:3000                                                                                  
> 
>   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
> 

Error when yarn generate

**Comment by 0721Betty** [comment]
I am facing the same problem now, how did you solve it

**Comment by Ouldev** [comment]
I have this problem too. On Netlify . It appeared after putting a simple asyncdata function like :

`async asyncData({$axios}) {
			return {areas: await $axios.$get('/aires-therapeutiques')};
	}`

When i generate my project in local, no problem. But in netlify i have this problem. Someone ? Thanks 👍

**Comment by Ouldev** [comment]
OKay ! I just forgot to put my environment variables on netlify, 👎 :facepalm: . Maybe it was the same problem for you too. Have a nice day
