### ISSUE TITLE
(Nuxt 2.15) Jiti not supporting optional chaining with Typescript

### ISSUE THREAD

**Issue by victorgarciaesgi** [nuxt/nuxt.js#8893]
### Versions

- nuxt: 
- node: 
- typescript: 

### Reproduction

I upgraded the nuxt version from 2.14.x on a big Typescript project with no errors until I bumped the Nuxt version to 2.15

Now right after I fire up the dev build, I have an error coming from Jiti on all the places where I have Optional Chaining

![image](https://user-images.githubusercontent.com/15092120/108843896-9b604f80-75db-11eb-82c0-22556e8a95f2.png)

I'm in SPA mode, and my `tsconfig.json` targets `ES2018`

### What is Expected?

It is expected that optional chaining is supported

### What is actually happening?

Build is failing

**Comment by hanabi1224** [comment]
I got same error :(

**Comment by victorgarciaesgi** [comment]
@hanabi1224 Upgrading to node 14 did the trick! Thanks!

**Comment by pi0** [comment]
Optional chaining and nullish-operator are natively supported with node >= 14 and it is best to upgrade Node.js version.

With jiti 1.4.0, we detect legacy (node < 14) environment to do transform if syntax used. You can get latest update by recreating lock file.
