### ISSUE TITLE
WARN in ./.nuxt/utils.js (v2.15.2)

### ISSUE THREAD

**Issue by Redemption198** [nuxt/nuxt.js#8898]
Hi, I'm having some trouble in my nuxt application after upgrading to 2.15.2, everytime I run a build or a production server I get this warning: WARN in ./.nuxt/utils.js "export 'isSamePath' (imported as '_isSamePath') was not found in 'ufo'

I've already tried refreshing my lockfile as suggested in #8833 and deleting the node_modules folder

My project setup:
Nuxt: 2.15.2
Node: 14.16.0

**Comment by Redemption198** [comment]
I installed it manually using `npm i ufo` and the warning disappeared, I don't know if this is the correct solution

**Comment by VincentHardouin** [comment]
Same problem

**Comment by Redemption198** [comment]
> Same problem
Is 'ufo' inside your package.json? If not, install it manually, it fixed my warnings

**Comment by VincentHardouin** [comment]
No, I don't have `ufo` in my `package.json` but I don't understand why I need this because it is in my `node_modules` directory and I can see it in many package dependencies in my `package-lock.json`.

**Comment by Redemption198** [comment]
[ufo](https://github.com/un-js/ufo) is an utility library for solving/managing urls, in 2.15 they did some refactoring related to ufo which caused some problems. Even if it was already being used i had to install it manually via npm and got my app running fine again.

**Comment by AdrianoCahete** [comment]
I have the same problem after upgrade from 2.14.12  to 2.15.3.

Why do I need to add a dependency to my project instead of this be a nuxt dependency @Atinux @DanielRuf?

**Comment by danielroe** [comment]
@AdrianoCahete You do not need to add a dependency, just upgrade it in your lockfile. Adding it as a dependency forces this upgrade, but so would running `yarn upgrade ufo` or `npm up ufo`.

**Comment by AdrianoCahete** [comment]
Removed `package.lock` and node_modules folder, but nothing. :(

Install `ufo` as dev dependency works, but isn't really my project's dependency.

**Comment by DanielRuf** [comment]
@AdrianoCahete I doubt that I have anything to do with nuxt, ufo or any other comment here.

**Comment by DanielRuf** [comment]
Besides this, why not add this dependency to the project and pin the version?

**Comment by DanielRuf** [comment]
0.x versions should be pinned imo

https://github.com/nuxt/nuxt.js/blob/dev/packages/utils/package.json#L22

https://github.com/nuxt/nuxt.js/blob/dev/packages/utils/package.json#L21

@pi0 @danielroe

**Comment by AdrianoCahete** [comment]
Wrong Daniel, sorry hahahaha
![image](https://user-images.githubusercontent.com/37474/111001517-ae587b00-8362-11eb-9a10-37b9314d1ac6.png)

**Comment by DanielRuf** [comment]
No problem. Pinning should prevent such surprises in the future.

**Comment by baermathias** [comment]
Same problem.
@danielroe Why is this issue closed? Is there a commit, which fixes it?

**Comment by danielroe** [comment]
@baermathias This isn't a bug, as such. It's just that your package lockfile is outdated. The latest Nuxt version depends on a newer version of ufo than you have installed. The solution is just to bump that version, in any number of different ways.

**Comment by Redemption198** [comment]
I tried again to delete the package-lock and removing ufo as a dependency (and npm install and ufo up) but it keeps showing the same warning even on 2.15.3.
Having ufo as a dependency, seems to fix the issue.

**Comment by DanielRuf** [comment]
You should be able to see the installed versions with `npm ls`.

The function was added there: https://github.com/unjs/ufo/commit/3e55aa91ca8a666ef7a24fb3314d13a116c331c9#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351

**Comment by Redemption198** [comment]
I run the command and apparently the only package that has an outdated version of ufo is [Nuxt Strapi](https://github.com/nuxt-community/strapi-module)

**Comment by Redemption198** [comment]
Thank you
