### ISSUE TITLE
Static build does not work, assets not found 404

### ISSUE THREAD

**Issue by jzucadi** [nuxt/nuxt.js#890]
So I built my project, and hit npm run build. The files appear in my dist folder, all bundled up. However, it doesn't work. When I try and upload the files to a server I get a bunch of 404 errors that none of the bundled files can be found.

I don't understand if this has something to do with dynamic routes. For my project, all I did was make a new .vue file for each page. I don't think these are dynamic routes. I don't understand the documentation. You have to make a .vue file to define dynamic routes? or you put them in nuxt.config.js?

**Comment by alexchopin** [comment]
Hi @jzucadi,
If you want to create a static web app, you need to use the [generate command](https://nuxtjs.org/guide/commands/#static-generated-deployment).
For dynamic routes, what do you not understand in the [documentation](https://nuxtjs.org/guide/routing#dynamic-routes) example?

**Comment by rap2hpoutre** [comment]
@alexchopin It seems it only works if the site is in root folder. In other words, it works for http://example.org but not for http://example.org/my-site. Non working example here: https://rap2hpoutre.github.io/nuxt-news/ (you can see 404 for each js file)

**Comment by rap2hpoutre** [comment]
I think it's because links are created like this `/_nuxt/vendor.bundle.72592248950c00528b87.js`. Is there a workaround?

**Comment by alexchopin** [comment]
Have you tried [router.base](https://nuxtjs.org/api/configuration-router#base) option?

**Comment by rap2hpoutre** [comment]
@alexchopin Great! Fixed! (and sorry, I did not see that)

**Comment by jzucadi** [comment]
OK, I think my first mistake was that I was using the adonuxt template which does not have a generate command.  As far as the documentation, here is what I am trying to figure out: do I need to do something extra regarding defining page routes to get them to work? If I just made some pages (each in a standalone .vue file) is the routing that nuxt does automatically enough?

**Comment by alexchopin** [comment]
@jzucadi yes nuxt does it automatically, you only need to define dynamic route for the generate command to let nuxt knows the routes params values.

**Comment by jzucadi** [comment]
ok thank you. Sorry, need to go through documentation again.

**Comment by jzucadi** [comment]
Hey sorry I know you closed this but I still can't get it work following the router.base suggestion and I'm trying to avoid rebuilding everything in the starter template. In the adonuxt template, everything is in /resources/. So I added `module.exports = {
  router: {
    base: '/resources/'
  }
}`

to nuxt.js file. However, after I build everything and upload it to a server I still get 404 errors. Help?
