### ISSUE TITLE
Vuetify is not properly initialized

### ISSUE THREAD

**Issue by prabodhana** [nuxt/nuxt.js#8900]
### Versions

- nuxt: ^2.14.12
- node: v15.9.0

### What is Expected?
Compile with  out error

### What is actually happening?

Today I'm create a fresh nuxt project.I'm using Vuetifyjs form UI framework. Its works correctly after install it and complie. But after add below code to nuxt.config.js it give me 'Vuetify is not properly initialized, see https://vuetifyjs.com/getting-started/quick-start#bootstrapping-the-vuetify-object '

```
  build: {
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          exclude: /(node_modules)/,
          options: {
            fix: true
          }
        });
      }
    }
  },
```

**Comment by danielroe** [comment]
@prabodhana Could you provide a reproduction on https://template.nuxtjs.org ?
