### ISSUE TITLE
Absolute publicPaths in development

### ISSUE THREAD

**Issue by beneditomauro** [nuxt/nuxt.js#8906]
### Versions

- nuxt: v2.15.2
- node: 12.12.0

### Reproduction
https://codesandbox.io/s/angry-goldberg-g03ku?file=/pages/index.vue

<details open>
<summary>Additional Details</summary>
Only happens in the latest release (v2.15.2)
<br>

</details>

### Steps to reproduce

- Use the latest version (2.15.2)

- Set publicPath to an absolute path (example: https://www.google.com/)

### What is Expected?

- Public path to be: https://www.google.com/_nuxt_/

### What is actually happening?

- The publicPath defaults to "`/_nuxt/`"

**Comment by Benedito0** [comment]
@danielroe that way will produce the same result in the latest version

**Comment by Benedito0** [comment]
reproduction : https://codesandbox.io/s/angry-goldberg-g03ku?file=/pages/index.vue

**Comment by prd-hop-duong** [comment]
Same problem on my end when upgrading nuxt from v2.14.12 to v2.15.2

**Comment by bdekok** [comment]
Just want to report that this does work for me (also the reproduction). One thing that might not be obvious from the documentation is that this feature doesn't work on a dev build.

**Comment by Benedito0** [comment]
@danielroe just to know, are this issue still considered to be "pending repro"?

**Comment by danielroe** [comment]
@Benedito0 Yes, as stated above this setting is not applicable in development.

**Comment by prd-hop-duong** [comment]
@danielroe So how do I use custom publicPath in development in lastest version?
This is my nuxt.config.js
```
build: {
    extend(config, { isDev }) {
      config.output.publicPath = isDev ? `${appConfig.staticUrl}/_nuxt/` : appConfig.staticUrl
   }
}
```
It's ok with version 14, as the result below
![image](https://user-images.githubusercontent.com/63763868/109586797-85e9a900-7b38-11eb-952e-e5dcbd2d792f.png)

But when upgrading to version 15, the custom publicPath is removed from the link, `src="/_nuxt/runtime.js"`

**Comment by armadillo-dev** [comment]
same here 👀

**Comment by beneditomauro** [comment]
In the case of rendering a template that will be used in an email

**Comment by gcandal** [comment]
@danielroe this happens both in development and production. Regardless of that, using a Nuxt-powered app to act as a rendering service (for generating emails, pdfs, etc) requires having absolute paths, as the HTML is served from sources other than the Nuxt server.

Even if an absolute `publicPath` worked just in production - which at the moment doesn't seem to be the case - I believe it would still make sense to allow it in development as it is the only way to have a smooth development experience in the use case mentioned above.

**Comment by gcandal** [comment]
As far as I recall, I was using `build.publicPath`, but I might be mixing things up so will have to take a look at it again.

I see your point, and having it not working in development would be ok, even if slightly confusing.

**Comment by prd-hop-duong** [comment]
@danielroe In my case, I run the custom node server in a different port, so I need to custom the path. For now, I need to proxy the request to make it works.
