### ISSUE TITLE
Module Warning: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by mythshuazi** [nuxt/nuxt.js#8907]
### Versions

- nuxt: 2.14.12
- node: 14.15.0

### warnings:
`
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):                                                                                                                      friendly-errors 11:41:50
Cannot read property 'value' of null
Occurred while linting D:\persenalpro\act\pages\actCreate.vue:73
`

### code:
`
const cmp = () => import(`@/components/${cm.name}/${cm.name}.vue`)
`

It look's like need to upgrade babel-eslint? How can i fix it

**Comment by daltonrooney** [comment]
Did you try 'const cmp = () => import(@/components/' + cm.name + '/' + cm.name + '.vue)'

Sometimes babel has a problem with interpolation. 🤔

**Comment by sh0ber** [comment]
Had the same problem using "@nuxtjs/eslint-module": "^3.0.2", "nuxt": "^2.15.3".  The issue is indeed with string literal interpolation as suggested by daltonrooney, and was solved by replacing with single quotes.

**Comment by mythshuazi** [comment]
@daltonrooney It's work for me. Thanks a lot
