### ISSUE TITLE
Hot reloading is not working with express + typescript as middleware

### ISSUE THREAD

**Issue by Elvincth** [nuxt/nuxt.js#8908]
### Versions

- nuxt: v2.15.2
- node: 14.16.0

### Reproduction

GitHub repository that can reproduce the bug:
https://github.com/Elvincth/nuxt-express-hotreload

<details open>
<summary>Additional Details</summary>
<br>
Run yarn dev <br>
And go to /api/test for testing
</details>

### Steps to reproduce
1.  Create index.ts and test.ts as express middleware files
2. Register the /test route `app.use('/test', test);`
3. Register the middleware in serverMiddleware
`  serverMiddleware: [
    {
      path: "/api",
      handler: "~/server/index.ts"
    }
  ],`

### What is Expected?

1. Change the respond text in test.ts from 'Test!' to 'Tests!'
2. Go to localhost:3000/api/test should see the text changed from 'Test!' to 'Tests!' without restarting the nuxt server

### What is actually happening?
The text didn't change from Test!' to 'Tests!' as expected, that mean the hot reloading is not working properly.
But after restarting the server the text did change to 'Tests!'.

https://user-images.githubusercontent.com/6602723/109271164-17f86580-784a-11eb-94bf-8a5a2e3dcbdf.mp4

**Comment by jtandiyo** [comment]
I'm experiencing the same issue. It first appeared when I updated to v2.15.0.

**Comment by Elvincth** [comment]
> Was it working for Nuxt 2.14 @Elvincth @jtandiyo ?
> 
> The HMR for server middleware is not stable on current Nuxt and will be fixes once we release Nuxt Nitro (see https://docs.google.com/presentation/d/1cWxCe9IZVRzM2W4OqvA4PtBr9_GLcF3n7VJEUoBLjg8/edit#slide=id.gbe7ff63d62_0_1545)

Yes tested, did work in 2.14 but not 2.15.

**Comment by jtandiyo** [comment]
> 
> 
> Was it working for Nuxt 2.14 @Elvincth @jtandiyo ?
> 
> The HMR for server middleware is not stable on current Nuxt and will be fixes once we release Nuxt Nitro (see https://docs.google.com/presentation/d/1cWxCe9IZVRzM2W4OqvA4PtBr9_GLcF3n7VJEUoBLjg8/edit#slide=id.gbe7ff63d62_0_1545)

Yes, it was working for me on 2.14 as well. Currently it seems the only way to get changes to stick is to restart it with `npm run dev` every time.

**Comment by qianqian05723** [comment]
Hello, I have the similar problem when Nuxt upgrade to 2.15.2。Additional， There is an error in Browser ,
![image](https://user-images.githubusercontent.com/17306867/109636510-a17ba080-7b86-11eb-92a2-96ca5a9acbd4.png)
![image](https://user-images.githubusercontent.com/17306867/109636669-d1c33f00-7b86-11eb-9b20-1fb73dd4a324.png)

**Comment by jtandiyo** [comment]
Hot reloading seems to be working for me on 2.14.12 again.

Even though the console's progress bar only shows the client being recompiled, changes made on serverMiddleware files seem to be sticking without having to restart the entire dev server.
