### ISSUE TITLE
Force a specific component to render only on client ?

### ISSUE THREAD

**Issue by thecodr** [nuxt/nuxt.js#891]
**Help wanted !**
I searched through nuxt.js documentation but had no luck on this. Is there someway of forcing a specific component of a page to render only on client ?
I have a component which uses browser specific attributes. But unfortunately, it fails on the server side. Any pointers will be greatly helpful :)

**Comment by piyushchauhan2011** [comment]
I feel like this is the same question as this one https://github.com/nuxt/nuxt.js/issues/839 @thecodr

**Comment by piyushchauhan2011** [comment]
Here you go this is better @thecodr https://github.com/nuxt/nuxt.js/issues/728

**Comment by motia** [comment]
@thecodr , You may want to to use https://github.com/egoist/vue-no-ssr.

**Comment by thecodr** [comment]
Thanks a lot @piyushchauhan2011 and @motia 
I tried both the approaches and  https://github.com/egoist/vue-no-ssr is more cleaner in terms of flexibility and extendability. I am closing this issue now.
