### ISSUE TITLE
Error on loading nuxt config due to browserlist config

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#8916]
### Versions

- nuxt: 2.15.2
- node: 14.15.4

### Reproduction

1. Clone https://github.com/rchl/nuxt-jiti-bug
2. `yarn && yarn dev`

### Steps to reproduce

1. Install a browserlist configuration package (I found some random one on the internet)
2. Include a browserlist configuration in your `package.json`:
```
  "browserslist": [
    "extends @gracious/browserslist-config-graciousstudios"
  ]
```

### What is Expected?

Nuxt starts with not errors

### What is actually happening?

Error on start

```
 FATAL  MODULE_NOT_FOUND: Cannot find module '@gracious/browserslist-config-graciousstudios'                                                                                22:06:27
 /Users/me/workspace/temp/nuxt-jiti/nuxt.config.js:0:0

  nuxt.config.js:0:0
  at Object.loadNuxtConfig (node_modules/@nuxt/config/dist/config.js:1054:15)
  at loadNuxtConfig (node_modules/@nuxt/cli/dist/cli-index.js:338:32)
  at NuxtCommand.getNuxtConfig (node_modules/@nuxt/cli/dist/cli-index.js:463:26)
  at Object._listenDev (node_modules/@nuxt/cli/dist/cli-dev.js:75:30)
  at Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:58:25)
  at Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:52:16)
  at NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:22)
```

**Comment by rchl** [comment]
Note that once you get the error, it will show up even after removing the `browserlist` configuration from `package.json` as Jiti caches the result.

Can use `JITI_CACHE=false yarn dev` to invalidate the cache.

**Comment by pi0** [comment]
Hi @rchl. Issue should be fixed in [jiti@1.5.0](https://github.com/nuxt-contrib/jiti/commit/8a7f8813e21586160530b99a43c36e3dcfc76e64). Best way to upgrade would be recreating `yarn.lock`/package-lock.json`

**Comment by rchl** [comment]
The issue with loading browserlist config should be fixed? My project is now using `1.6.0` (checked in the lock file) but I still seem to be getting the same error.

**Comment by pi0** [comment]
@rchl Can you please check with JITI_DEBUG?

**Comment by rchl** [comment]
![Screenshot 2021-03-04 at 08 40 26](https://user-images.githubusercontent.com/153197/109928030-4bf9dd80-7cc5-11eb-84ee-5766f482a714.png)

(I've refreshed the lock file in the test repo)

**Comment by rchl** [comment]
Note that browserlist configuration most likely doesn't make sense for the server-side transpilation. I guess previously, with esm, it wasn't respected either. So there might be two aspect to this:
 - ignore it when running through jiti
 - fix the crash

**Comment by rchl** [comment]
@pi0 should this be re-opened? Are you not able to reproduce with my repo anymore?

**Comment by pi0** [comment]
browserslist is will be ignored with jiti@1.6.1

**Comment by rchl** [comment]
Looks good now. Thank you. 👍
