### ISSUE TITLE
<nuxt-link> is ignored when html-minify

### ISSUE THREAD

**Issue by NguyenThanh1995** [nuxt/nuxt.js#8923]
Hello @nuxtjs
I found out that <nuxt-link> will be ignored while html-minify works. The spaces in the nuxt-link remain the same. How can I fix this

**Comment by danielroe** [comment]
@NguyenThanh1995 Could you provide a reproduction using https://template.nuxtjs.org ? 🙏

**Comment by NguyenThanh1995** [comment]
I create a new project with default options using yarn create-nuxt-app and the option build.html.minify is suggested on the nuxtjs homepage.  it does not have any other libraries.  If you include spaces in <nuxt-link> it will not be removed by minify html even in production.

**Comment by danielroe** [comment]
@NguyenThanh1995 Would you please create a reproduction? I do not understand the issue from your description.
