### ISSUE TITLE
Error: Unsupported MIME type: image/x-icon 

### ISSUE THREAD

**Issue by 277584579** [nuxt/nuxt.js#8928]
### Versions

- nuxt:  2.13.0
- node: 14.15.4

### Reproduction

When I re installed the windows system, I found that I couldn't start the "NPM" project. I have deleted the node_ Modules "NPM install" again, I can't find the reason
<details open>
Error: Unsupported MIME type: image/x-icon
    at Jimp.throwError (F:\develop\syman\marketing-cloud-pc\node_modules\jimp-compact\dist\jimp.js:1:833)    
    at Jimp.parseBitmap (F:\develop\syman\marketing-cloud-pc\node_modules\jimp-compact\dist\jimp.js:1:125733)
    at Jimp.parseBitmap (F:\develop\syman\marketing-cloud-pc\node_modules\jimp-compact\dist\jimp.js:1:8514)  
    at F:\develop\syman\marketing-cloud-pc\node_modules\jimp-compact\dist\jimp.js:1:7613
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}

**Comment by 277584579** [comment]
[![6A1ucj.png](https://s3.ax1x.com/2021/03/03/6A1ucj.png)](https://imgtu.com/i/6A1ucj)

**Comment by 277584579** [comment]
[![6A1ucj.png](https://s3.ax1x.com/2021/03/03/6A1ucj.png)](https://imgtu.com/i/6A1ucj)

**Comment by 277584579** [comment]
[![6ADqu6.png](https://s3.ax1x.com/2021/03/03/6ADqu6.png)](https://imgtu.com/i/6ADqu6)

**Comment by 277584579** [comment]
> 您可以通过https://template.nuxtjs.org提供复制品吗？

**Comment by 277584579** [comment]
> Could you provide a reproduction via https://template.nuxtjs.org ?

I tried to breed, but it failed. I can provide my GitHub address  https://github.com/277584579/nuxt-test
![Uploading 432.png…]()

**Comment by 277584579** [comment]
> Could you provide a reproduction via https://template.nuxtjs.org ?

I tried to copy it,
![432](https://user-images.githubusercontent.com/22782505/109918207-88dbc980-7cf1-11eb-9a6c-58a3529ab6d7.png)
 but it failed. I can provide my GitHub address https://github.com/277584579/nuxt-test

**Comment by danielroe** [comment]
@277584579 Would you update the repo so only the code required to create the issue is present? 🙏

**Comment by 277584579** [comment]
> @277584579 Would you update the repo so only the code required to create the issue is present? 🙏

@danielroe  The main branch and the master branch have this problem, which is also the latest. The code is the same https://github.com/277584579/nuxt-test

**Comment by 277584579** [comment]
Thank you. I found the reason nuxt.config It's the PWA plug-in problem. I tried to delete it. Now it's OK

**Comment by senthil-magendiran** [comment]
@277584579 I'm facing the same issue. can you please tell me how you have fixed this issue?
