### ISSUE TITLE
Typescript : Typed props are cast to Object instead of keeping orignal class instance (Only ssr, spa works fine)

### ISSUE THREAD

**Issue by azpery** [nuxt/nuxt.js#8933]
### Steps to reproduce
Running with nuxt typescript ans ssr enabled. 

Create a component with Prop input 
` export default class CarouselListItem extends Vue {
      @Prop({ type: Film, required: true }) film!: Film
}`
--> film is type Film -> On SPA only this works fine. The Film is well passed

### What is Expected?
Input is instance of Film.

### What is actually happening?
When running nuxt dev with ssr enabled, the prop is cast to Object. 

Then I can't manipulate the Film object. I have to recast it into a new Film object.

**Comment by azpery** [comment]
Ok I'm sorry I didn't see you replied. 

I'm managed reproducing my problem. Which I don't know if it is a bug but is at least annoying. 

So : https://codesandbox.io/s/fervent-snowflake-9dlgt?file=/pages/index.vue 

As you can see, arrays of Test are cast to Array of Object. Then I can't use Test(s) methods and functions.

SSR : Is Array of Test
Client: is Array of Object

![Capture d’écran 2021-05-04 à 15 18 13](https://user-images.githubusercontent.com/9019431/117009375-f4d7af80-aceb-11eb-9e6f-6cefe205920c.png)

Is it because of the serialization of objects ?

**Comment by danielroe** [comment]
@azpery Yes, that's right. You won't be able to deserialise a stringified class and get out an instance - of the same class, out of the box. You would have to normalise it yourself (perhaps using a computed property?).

**Comment by azpery** [comment]
@danielroe thanks a lot for replying and for your time. 
I think the hybrid system client/server is awesome but this only brings weird bugs when integrating Nuxt. I don't if I'm the only developper manipulating custom objects but as Nuxt supports Typescript and types in general, do you know if this feature is planned? 
At the end I think for the moment we can manage using Objects.

**Comment by UsmanJavedAttari** [comment]
> @azpery Yes, that's right. You won't be able to deserialise a stringified class and get out an instance - of the same class, out of the box. You would have to normalise it yourself (perhaps using a computed property?).

Any example on YOUR computed property?
