### ISSUE TITLE
'Generating pages with full static mode ' means that page js will not working?

### ISSUE THREAD

**Issue by chenPengXu** [nuxt/nuxt.js#8937]
### Versions

- nuxt:  v2.15.2
- node: v12.10.0

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
1. creat app with cli
2. modify pages/index.vue   with
`
export default {
    name: 'TDemo',
    data() {
      return {
        a: 'hello a',
      }
    },
    mounted() {
      console.log('------mounted hello-----')
    },
    methods: {
      onTest() {
	      this.a = 'change a'
      }
    }
  }
`

3. run build and generate  (with target: 'static'  in config)
4. push the dist to my server

### What is Expected?
1. console should show the log '------mounted hello-----'
2. click button 'change', text will change

### What is actually happening?
1. log not show
2. click not working

So, in full static mode, pages generated will not working with life circle and methods ?

**Comment by danielroe** [comment]
@chenPengXu Would you provide a reproduction please?

**Comment by chenPengXu** [comment]
> @chenPengXu Would you provide a reproduction please?
index.vue as follow;
and nuxt.config.js : target is 'static' and mode is 'universal'

![1615027640564](https://user-images.githubusercontent.com/12268452/110204141-7a85dd00-7eac-11eb-822c-0d1ef1f26485.jpg)

**Comment by danielroe** [comment]
@chenPengXu When I say a reproduction, I mean a codesandbox via https://template.nuxtjs.org or a repository with all (but only) the code needed to reproduce the issue.

**Comment by chenPengXu** [comment]
> @chenPengXu When I say a reproduction, I mean a codesandbox via https://template.nuxtjs.org or a repository with all (but only) the code needed to reproduce the issue.

codesandbox code :  https://codesandbox.io/s/sleepy-spence-uqwq6?file=/pages/index.vue
and my code online : https://www.visgoods.com/dist/index.html

**Comment by chenPengXu** [comment]
> The location you're hosting your files doesn't match the expectation of your Nuxt app. If you want to host them in `dist` then you can do so by setting [a custom `router.base`](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router/#base). And you shouldn't access them via `index.html` but just the directory - e.g. `/dist/`.
> 
> See [a working CodeSandbox](https://codesandbox.io/s/gallant-andras-dbojn?file=/package.json) with generate + start.
> 
> There are some good deployment examples [here](https://nuxtjs.org/docs/2.x/deployment/deployment-amazon-web-services) if that is helpful - or do join our Discord for support.

Thank you
So,  target: 'static' means exactly full static mode , and means dist resource may be used but just  be as static resource and has no javascript dynamic interaction ?  
I have try next, it's generated resource can be work independently。
I  think there should be some performance differences in  'generate && nuxt start' ( serviceing by node) and resouce  independently(nginx).   
And thank you again , your reply settled my doubts

**Comment by danielroe** [comment]
@chenPengXu You're very welcome.

> so, target: 'static' means exactly full static mode , and means dist resource may be used but just be as static resource and has no javascript dynamic interaction ?
No, that's not what it means. It is a full JavaScript application, but you need to ensure that the URL matches the Nuxt route. So `/dist/index.html` doesn't match `/` so it's not able to hydrate it properly. You can specify a custom directory as I mentioned previously.
