### ISSUE TITLE
Add <server-only> component

### ISSUE THREAD

**Issue by akarelas** [nuxt/nuxt.js#8947]
My site would benefit from a <server-only> component, that would work similarly to the already existing `<client-only>` component.

There is a component that relies on WebSockets (to keep the data updated at all times), which I wrap in a `<client-only>` tag. However I'd like search engines to render some text in its place (which won't be updated in real-time). For this, I would like my component to be able to have a `<client-only>` and a `<server-only>` part.

I haven't found an alternative way to achieve this effect.

**Comment by hanneskuettner** [comment]
If I understood you correctly you already be able to solve your problem with just the `client-only` component. 
You can provide the component with an optional placeholder slot (see the second example [here](https://nuxtjs.org/docs/2.x/features/nuxt-components/#the-client-only-component)) which is only rendered server side.

So having a server only part should be achievable like this

```html
<client-only>
      <!-- empty default slot -->
      
      
      <!-- only rendered on server side-->
      <service-only slot="placeholder" />
</client-only>
```

**Comment by hanneskuettner** [comment]
If I understood you correctly you already be able to solve your problem with just the client-only component.
You can provide the component with an optional placeholder slot (see the second example here) which is only rendered server side.

So having a server only part should be achievable like this

```html
<client-only>
      <!-- empty default slot -->
      
      
      <!-- only rendered on server side-->
      <service-only slot="placeholder" />
</client-only>
```

**Comment by akarelas** [comment]
Indeed, it works. That you very much for your attention and your solution. I think I should close this issue.
