### ISSUE TITLE
Programmatically render error pages

### ISSUE THREAD

**Issue by stephan281094** [nuxt/nuxt.js#895]
Hi there. I'm currently working on a project that uses Nuxt programmatically. On the server, I've created a custom (Express) route that handles user authentication. In this route I throw an exception when something goes wrong. At the moment it's simply returning JSON, but I want to return a Nuxt error page instead.

How can I accomplish this? Is there like a function I can call or can I set a statusCode/ message on the `response` object?

Thanks in advance.

**Comment by alexchopin** [comment]
Hi @stephan281094,
Do you use Nuxt middleware to call this route and check if the user is authenticated?

**Comment by stephan281094** [comment]
No. I created a custom Express route that redirects to Github for OAuth. Github then redirects back to a callback route I defined. In this callback I throw an exception when something is incorrect.

I know that Nuxt middleware gives you access to the context object, which contains an 'error' function you can call. That's what I'm looking for, but I don't think it's available outside of `nuxt.render`. Another option is to simply use Nuxt middleware instead of defining a custom route, but I only need that middleware to be used on specific serverside-only routes.

As a workaround I could probably create a new empty page that only registers the middleware, but this seems like a hack.

**Comment by Atinux** [comment]
Hi @stephan281094 

1. Create an `pages/error.vue` page
2. In you express route, if there is an error when back from Github OAuth, put the error in `req.error` for example and call `nuxt.renderRoute('/error', { req, res })`.
3. In your `pages/error.vue`

```vue
<template></template>

<script>
export default {
  asyncData ({ error, req, redirect }) {
    if (req && req.error) {
      return error({ message: req.error.message, statusCode: req.error.status })
    }
    redirect('/')
  }
}
</script>
```

**Comment by stephan281094** [comment]
I'll give that a try later today, thanks!
