### ISSUE TITLE
it is not clear which version of nuxt is installed

### ISSUE THREAD

**Issue by deni5n** [nuxt/nuxt.js#8957]
### Versions

- nuxt: ???
- node: <14.15.1>

### Steps to reproduce

1. install Nuxt version 2.14.11 
2. update nuxt in package.json to 2.15.2
3. run "npm run dev" - show version 2.15.2
4. undo nuxt version to 2.14.11
5. run "npm run dev" - show version 2.15.2 there are no errors during the assembly process 

### What is Expected?

in the step 5 show version 2.14.11

### what was done?
i reproduced this several times. tried to remove node_modules, .nuxt, package-lock.json. all unsuccessfully. i can not return nuxt version to 2.14.11. my site is not worked (((

**Comment by pengyouxian** [comment]
HI,Have you solved the problem?
