### ISSUE TITLE
Nuxt doesn't generate the nested routes example correctly 

### ISSUE THREAD

**Issue by progressman** [nuxt/nuxt.js#896]
I download nested routes example from https://nuxtjs.org/examples/nested-routes. 
Add generate: {routes: ['/1','/2','/3','/4','/5','/6']} to nuxt.config.js and run next generate.

And here is the problem with nuxt@1.0.0-alpha.4
In all generated static files there is the same pre-rendered player - Kyrie Irving (id:6)

At the same time nuxt-link-active and all javascript data was defined correctly.
Live demo also works like it should. And with nuxt@0.10.6 it also works as expected.

**Comment by progressman** [comment]
Static page generation is broken in 1.0.0-alpha
Have checked once again with nuxt@1.0.0-alpha.2

**Comment by Atinux** [comment]
We'll work on it, thank you for reporting it @progressman

**Comment by Atinux** [comment]
Closing it since `rc3` is out
