### ISSUE TITLE
Lazy loading script not attribute crossorigin

### ISSUE THREAD

**Issue by vell174** [nuxt/nuxt.js#8975]
### Versions

- nuxt: v2.15.2
- node: v12.18.2

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Preload the js file example

`() => import('dayjs/locale/de')`

nuxt.config in render 

```
 render: {
    crossorigin: 'anonymous',
}
```

### What is Expected?
The script is loaded with the attribute crossorigin: 'anonymous',

### What is actually happening?

Script without attribute
![image](https://user-images.githubusercontent.com/67749799/110807111-87d40a80-82a4-11eb-9f19-90f36466775a.png)

**Comment by vell174** [comment]
temporary solution
nuxt.config 
```
head: {
...
    script: [
      { src: (process.env.APP_BASE_URL || '/') + 'js/hack_pwa.js' }
    ]
}
```
hack_pwa,js
```
try {
  const realAppend = document.head.appendChild;
  document.head.appendChild = function (e) {
    if (e?.src.includes('_pwa.js')) {
      e.setAttribute('crossorigin', 'anonymous');
    }
    realAppend.apply(this, arguments);
  };
} catch (e) {
  console.log(e);
}
```

**Comment by danielroe** [comment]
@vell174 Would you be able to provide a reproduction? 🙏
