### ISSUE TITLE
ExtendRoutes/webpack/jiti do not process Vuex route.redirect...

### ISSUE THREAD

**Issue by linqFR** [nuxt/nuxt.js#8979]
### Versions

- nuxt: 2.15.3

### Steps to reproduce
```
	router:{
		trailingSlash:false,
		extendRoutes(routes,resolve){
			routes.unshift({
				name:'login',
				path:'/login',
				redirect(to,...a){
					return {name:'loginelse'}
				}
			})
		}
	}
```
is processed in .nuxt /router.js to:
```
export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,
  routes: [{
    path: "/login",
    redirect: undefined,
    name: "login"
  }, {
    path: "/",
    component: _4ad08996,
    pathToRegexpOptions: {"strict":true},
    name: "index"
  }],
  fallback: false
}
```

### What is Expected?
as described in docs : [https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes):
`The schema of the route should respect the vue-router schema.` ([vue-router schema](https://router.vuejs.org/en/))

### What is actually happening?
redirect is not processed by webpack and/or jiti...

**Comment by zavvla** [comment]
I have this problem too... just ignore redirect... 
`extendRoutes(routes, resolve) {         
            routes.push({
                path: "/registration",
                redirect: "/registration/step-1",
            });
        }`

**Comment by linqFR** [comment]
> I have this problem too... just ignore redirect...
> `extendRoutes(routes, resolve) { routes.push({ path: "/registration", redirect: "/registration/step-1", }); } `
> 
> UPD I changed "routes.push" -> "routes.unshift", add "sortRoutes" and it worked.

redirect as a string works fine, but according to vue-router documentation, redirect could be a function either!

**Comment by linqFR** [comment]
> @linqFR Thanks for the issue. I've put a fix in but I would recommend using https://github.com/nuxt-community/router-extras-module or https://github.com/nuxt-community/router-module instead if you want to take over more control of how the router behaves in a Nuxt context.

actually i m using http-proxy(-middleware) options : options.pathRewrite and options.onProxyReq
