### ISSUE TITLE
ssr custom directive

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#898]
Hello my custom directive not working on server side!

directive
```
Vue.directive('mydirective', {
  bind (el, binding) {
    el.innerHTML = 'mydirective worked';
  }
});
```

html template
`<div v-mydirective="{foo: 'bar'}">initial text</div>`

This code worked only browser - not working on server side ((
How fix this problem??

Thanks, really very need this.

**PS.**
How worked directive 

> v-html

This worked on server side and client side.

**Comment by pi0** [comment]
Hi @wargt. SSR directives should be implemented different than client side ones. If you need them please take a look at [here](https://ssr.vuejs.org/en/api.html#directives) for SSR directive. For registration you can do this in `nuxt.config.js`: 
```js
module.exports = {
  build: {
    ssr: {
      directives: {
        example (vnode, directiveMeta) {
           // transform vnode based on directive binding metadata
        }
      }
}
}
```

**Comment by wargt** [comment]
nuxt.config.js

```
build: {
		ssr: {
			directives: {
				example: function (vnode, directiveMeta) {
					console.log('test directive')
					vnode.data.style.display = 'none' 
				}
			},
		},
```

`<div v-example="{foo: 'bar'}">initial text</div>`

not working ((

nuxtjs version 0.10.7

**Comment by pi0** [comment]
@wargt You have to upgrade nuxt `1.x` version. Unfortunately this feature was only available since Vue 2.3 SSR engine.

**Comment by wargt** [comment]
nuxt 1.x version not working 

```
performance: {
 prefetch: false
},
```

((

**Comment by pi0** [comment]
Closing this in flavor of #899 :)

**Comment by wargt** [comment]
why closed ?

**Comment by pi0** [comment]
Here is working example based on vue examples:
https://glitch.com/edit/#!/storm-glade?path=nuxt.config.js:10:38

```js
module.exports = {
  build:{
    ssr: {
      shouldPreload: () => false,
      	directives: {
          example (vnode, directiveMeta) {
            console.log('test directive')
            if (!directiveMeta.value) {
                const style = vnode.data.style || (vnode.data.style = {})
                style.display = 'none'
            }
          }
			},
    }
  }
}
```

**Comment by wargt** [comment]
```
ssr: {
  shouldPreload: () => false,
  shouldPrefetch: () => false,
}
```

this not worked (

**Comment by DaxChen** [comment]
for future readers, custom directive registration is documented here:
https://nuxtjs.org/api/configuration-render#bundleRenderer
