### ISSUE TITLE
[types] Options accessed from module not extendable

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#8985]
The `Module` type has an `options` property whose type is `NuxtOptions`:

https://github.com/nuxt/nuxt.js/blob/f08f4efcde7bc174fd9b68a2a5a785d504659391/packages/types/config/module.d.ts#L24

Since it's `NuxtOptions` and not `NuxtConfig`, if a module extends `NuxtConfig` with an extra property, that won't be accessible type-wise from the module. For example:

```ts
declare module '@nuxt/types' {
  interface NuxtConfig {
    i18n?: Options
  }
}
```

```js
/** @type {import('@nuxt/types').Module} */
export default function () {
  const moduleOptions = this.options.i18n  // `this.options.i18n` has type `any` here
}
```

### Versions

- nuxt: v2.15.2

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt.js/pull/9058#discussion_r602730487. In short, extend `NuxtOptions` and not `NuxtConfig` and you should be fine.

**Comment by kevinmarrec** [comment]
@danielroe @pi0 I've read #9058 and I haven't succeed to correctly understand what's going on 🙈

As far as I remember, modules need to extend `NuxtOptions` and not `NuxtConfig`.

And if I'm right, there was even a moment where `NuxtConfig` was a type and not an interface, and couldn't be extended.

The proper way is exactly what @danielroe mentioned in last comment, `NuxtOptions` should be extended.
Which will result on accessing `this.options.foo` through module definition but also have config key `foo` correctly typed.

Please point me out if there's something still wrong in types that I didn't get and should be fixed :)

**Comment by rchl** [comment]
I'd also say that the way to go is to extend `NuxtOptions` from the module's perspective.

`NuxtConfig` is still necessary and useful because it's needed if someone wants to annotate the config object in `nuxt.config.js` but I don't see why it should be recommended to extend `NuxtConfig` instead of `NuxtOptions`.

**Comment by danielroe** [comment]
@kevinmarrec I agree. I think extending `NuxtOptions` is what we should be encouraging module authors to do (note: we should update the template which currently defaults to `NuxtConfig`).

**Comment by pi0** [comment]
Initially, we only had `Configuration` interface which was not considering options get normalized. This was leading to issue that internal typings was wrong because all `nuxt.options` keys was optional. Then we introduced `NuxtOptions` for internals (normalized by `options.js`) and `NuxtConfig` for `nuxt.config` interface with backward compatibility for `Configuration` interface.

Nuxt does not touches input options for custom keys and modules since modules are responsible to merge it with defaults and should not solely depend on `this.options.moduleName` without normalizing. In other words `nuxt.options.i18n` is not a trusted source without explicitly normalized by module into a new variable. 

What I meant in https://github.com/nuxt/nuxt.js/pull/9058#discussion_r602729461 when sharing options is desired (like module A normalizing it's config back into `nuxt.options` for module B)

Nuxt kit will hopefully help on making it easier for defining modules and normalizing options but for time being, otherwise above is the case, please extend **`NuxtConfig`** for modules and not `NuxtOptions` otherwise it makes situation even harder to support all legacy cases.

I've reopened this issue to clarify this :)

**Comment by rchl** [comment]
Again, would like to talk about `this.options.i18n` rather than `this.nuxt.options.i18n`. Those are the same objects anyway, as you said, but `this.options` have proper types so it's clearer to reason about.

> In other words `nuxt.options.i18n` is not a trusted source without explicitly normalized by module into a new variable.

I either don't understand what you are saying or I just don't agree with it.

I'll describe the obvious stuff that we all already know, just so that we are on the same page:

The module can get passed options in two ways (typically):
- `modules: [ ['nuxt-i18n', { /* options */ }] ]`
- `i18n: { /* options */ }`

In the first case, the module receives options through the argument passed to the default export.
In the second case, the module has to access them through `this.options.i18n`.
In both cases the `i18n` options are unresolved.

Now, in the second case the `i18n` types are missing because `this.options` is `NuxtOptions` and not `NuxtConfig`.
I agree that it should be `NuxtOptions` because the Nuxt options themselves are resolved but then the module must extend `NuxtOptions` or else the types its types won't be available **to itself**.

If you don't agree with that then please say what's the plan to address that going forward?
I guess you must have some idea since you have a strong opinion that the modules should only extend `NuxtConfig` but haven't mentioned any alternative that would solve the aforementioned problem.

**Comment by pi0** [comment]
> Those are the same objects anyway, as you said, but this.options have proper types so it's clearer to reason about.

The reason is that nuxt typing are incomplete. `Nuxt` is not typed at all.

> I agree that it should be NuxtOptions because the Nuxt options themselves are resolved but then the module must extend NuxtOptions or else its types won't be available to itself

The module should internally resolve options from input key(s) and inline options. It is not reliable outside the context of the module itself. Here is a proper usage:

```ts
interface I18nOptions {
 example: string
}

declare module '@nuxt/types' {
  interface Configuration {
    i18n?: Partial<I18nOptions>
  }
}

export default function (inlineOptions) {
  const moduleOptions: I18nOptions = defu(inlineOptions, this.options.i18n, {
    example: 'default'
  })

  // moduleOptions is properly typed and normalized
}
```

Or using jsdocs:

```js
export default function (inlineOptions) {
  /** @type {import('../types').I18nOptions } */
  const moduleOptions:= defu(inlineOptions, this.options.i18n, {
    example: 'default'
  })
}
```

**Comment by rchl** [comment]
This is how it's done already.

My point was only about `this.options.i18n` missing types.

Your suggestion is now to extend the `Configuration` interface which yes, will work, but `Configuration` is deprecated so I want to be a good citizen and not use it anymore. Which leaves me with no proper way to do it if I'm not to extend `NuxtOptions`.

**Comment by pi0** [comment]
@rchl Updated reply (sorry it was a typo). indeed configuration is deprecated. And i18n not being available in nuxt.options is intended because it is not a nuxt option. What I'm trying to say is that module options should be resolved and typed internally.

**Comment by rchl** [comment]
That doesn't change the fact that:
 - `this.options.i18n` types are missing
 - the unresolved options are there

You can hide the fact that the types are missing by using `defu` or `deepMerge` or something, as it will accept `any` but technically the options are there but the types are not.

I'm not sure why you are saying that we shouldn't extend `NuxtOptions` in this case. Is it because of the compatibility problems associated with that? Would it be OK if we would somehow magically forget all the legacy types?

(Sorry about going on with that for so long. Maybe there is a bit of a language barrier or maybe I'm not communicating well enough...)
