### ISSUE TITLE
nuxt 1.x version not working  performance: {  prefetch: false }

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#899]
Hello! Why not working?

nuxt 1.x version not working

```
performance: {
 prefetch: false
},
```

**Comment by pi0** [comment]
You have to use SSR for this:
```js
module.exports = {
  build:{
    ssr: {
      shouldPreload: () => false,
    }
  }
}
```

**Comment by wargt** [comment]
Not worked (( 

`<link rel="prefetch" href="/_nuxt/13.nuxt.bundle.dace679158194ffdf6c6.js" as="script"><link rel="prefetch" href="/_nuxt/1.nuxt.bundle.37a2b33ab46c85bdfa27.js" as="script"><link rel="prefetch" href="/_nuxt/2.nuxt.bundle.8255a6e8b1282beaa4ff.js" as="script"><link rel="prefetch" href="/_nuxt/4.nuxt.bundle.e1dfa8953d7e6afdd13f.js" as="script"><link rel="prefetch" href="/_nuxt/5.nuxt.bundle.d7d6586f9b8ad3167175.js" as="script"><link rel="prefetch" href="/_nuxt/6.nuxt.bundle.3c41b487598404709322.js" as="script"><link rel="prefetch" href="/_nuxt/7.nuxt.bundle.42387fc048a3a3412ac2.js" as="script"><link rel="prefetch" href="/_nuxt/8.nuxt.bundle.c34b3fa330fb6fb1ada7.js" as="script"><link rel="prefetch" href="/_nuxt/9.nuxt.bundle.cd647358ab3350764f02.js" as="script"><link rel="prefetch" href="/_nuxt/10.nuxt.bundle.ea00a535ec13bbb3538c.js" as="script"><link rel="prefetch" href="/_nuxt/12.nuxt.bundle.874818ed5643ab3a6b07.js" as="script"><link rel="prefetch" href="/_nuxt/14.nuxt.bundle.9cd5fbcf046bd3da4e9c.js" as="script"><link rel="prefetch" href="/_nuxt/15.nuxt.bundle.1418292940ac5570f392.js" as="script"><link rel="prefetch" href="/_nuxt/16.nuxt.bundle.d9933225471d3236ff5a.js" as="script"><link rel="prefetch" href="/_nuxt/17.nuxt.bundle.924494221cde167b2fe5.js" as="script">`

**Comment by pi0** [comment]
@wargt Currently seems `prefetch` cannot be disabled ( And actually not a good practice disabling for performance reasons). Option will be available soon :)

**Comment by wargt** [comment]
my project have 300 and more pages! It s not good for me (( How i can fix it - plz help me (

**Comment by pi0** [comment]
In next release you can disable resource hints using this config:
```js
{
 render: {
    resourceHints: false
  }
}
```

**Comment by wargt** [comment]
ok! Thanks. Please write me when released this taks

**Comment by Atinux** [comment]
Closing it since `rc3` is out
