### ISSUE TITLE
Nuxt app is not recompiling in Docker container on Windows in dev mode

### ISSUE THREAD

**Issue by dschonholtz** [nuxt/nuxt.js#8999]
### Versions

- nuxt: ex: v2.15.3 
- node: lts-alpine docker image (Currently Node 14.16)

### Reproduction
Code is here: https://github.com/dschonholtz/NuxtPersonalWebsite
It is a pretty simple version of the blog with nuxt example, based on the nuxt content example.
https://nuxtjs.org/blog/creating-blog-with-nuxt-content/
The only differences really should be some upgraded versions, my own amateurish styling, and content.

I took that I added a Dockerfile, Dockerfile.dev and docker-compose.yml all of which are pretty simple and work great on my linux desktop.

When it try to do development on my windows laptop and run docker-compose up and I go into the associated container. I can see file changes propagate properly so the volumes are working.

However, when I change a file, the app is not recompiled despite the change happening in the docker container.
This leads to no hot-reload which means the only way to test changes on my windows environment is to run node and everything else outside of the docker container (Which is not something I am particularly interested in)

There are a couple of issues dealing with similar problems:
#2481 - Hot Reloading doesn't work in docker container on windows.
Which recommends that you put a watchers element in the top level of the nuxt.config.js https://github.com/nuxt/nuxt.js/issues/2481

I tried all of the variants described their and read the associated nuxt and webpack documentation and didn't get any closer to a working solution.

Another thread that seemed relevant was https://github.com/nuxt/nuxt.js/issues/5550
However, their the app was recompiling just not refreshing the page so I believe it is different.

<details open>
<summary>Additional Details</summary>
<br>
[Nuxt Config](https://github.com/dschonholtz/NuxtPersonalWebsite/blob/main/nuxt.config.js)
[Dockerfile.dev](https://github.com/dschonholtz/NuxtPersonalWebsite/blob/main/Dockerfile.dev)
</details>

### Steps to reproduce

1. On a windows machine with docker installed
2. git clone https://github.com/dschonholtz/NuxtPersonalWebsite
3. docker build -t volume_tester -f Dockerfile.dev .
4. run `run --rm -it -p 3000:3000 -v ${pwd}:/app volume_tester`
5. Change a file locally
6. Go into the dockerfile and verify the file changed
7. Cry deeply on observing the page not updating

### What is Expected?

The change should cause the app to recompile and hot reload neither of which happens

### What is actually happening?
The app should recompile and hot reload.

Finally, thank you so much for reading.

I am trying to follow the instructions to the letter since I'm new to the community and a relative novice with Docker and Nuxt.

So if I am making any obvious mistakes please let me know. I would greatly appreciate any help and I hope it helps someone else!

**Comment by wbrowar** [comment]
I'm running into the same exact issue, but I'm using DDEV and running Docker on a macOS (10.15). If I run `dev` within the Docker environment it doesn't recompile or HMR, but when I run it from the OS, it works just fine.

**Comment by dschonholtz** [comment]
I'm pretty sure I had tried that fix and it hadn't worked for me. Regardless, I have been doing all of my dev on a linux box recently so I haven't been hitting this. Thanks for the follow up.

**Comment by JuanxCursed** [comment]
Same issue here, Windows too

**Comment by sg552** [comment]
same problem, in windows, docker and nuxt. 

windows: win10
docker: Docker Desktop 4.4.4
docker image: nodejs: 16.15.0 , nuxt: 2.15.8

**Comment by marceloamp2** [comment]
Same problem, in Ubuntu, docker and nuxt.

**Comment by Faber-smythe** [comment]
Same issue, in WSL2 Ubuntu, docker and nuxt.

**Comment by RizaHKhan** [comment]
+1

**Comment by lafllamme** [comment]
thank me later guys

add this to nuxt.config.ts

```
 //fix issue for docker not reflecting changes
  vite: {
    server: {
      watch: {
        usePolling: true,
        interval: 100, // Poll files every 100ms
      },
    }
  }
```

**Comment by majadul1989** [comment]
@lafllamme thanks its working fine for me :)
