### ISSUE TITLE
TypeError: validateOptions is not a function

### ISSUE THREAD

**Issue by NathanWijayasekara** [nuxt/nuxt.js#9006]
Well, I have a git hub repo you can check to reproduce the error.
[todoappnuxt](https://github.com/NathanWijayasekara/nuxt-todoapp)

Well, when you try to run the project it says that there's a TypeError with something called validateOptions and I don't even know what that means could anyone help me with this problem.

**Comment by danielroe** [comment]
@NathanWijayasekara Did you solve this issue?
