### ISSUE TITLE
360 browser compatibility mode auto redirect

### ISSUE THREAD

**Issue by wuwei-margin** [nuxt/nuxt.js#901]
When I using 360 browser compatibility(the kernel is using IE9) vist the nuxt.org，
and visit `https://zh.nuxtjs.org/guide/installation/`
it will jump to
`https://zh.nuxtjs.org/#/guide/installation/`

The same thing happened in my own project，why?

**Comment by egoist** [comment]
Hmm because ie9 does not support History API.
