### ISSUE TITLE
Payload broken (?) for non-ascii dynamic route

### ISSUE THREAD

**Issue by arildm** [nuxt/nuxt.js#9011]
### Versions

- nuxt: 2.15.3 (and 2.15.1, 2.15.2)
- node: 12.10.0

### Reproduction

https://github.com/arildm/nuxt-path-encoding

Significant code:

- `pages/_slug.vue`
- A nuxt-link on `pages/index.vue` links to the slug page with a non-ascii slug

### Steps to reproduce

1. `yarn generate`
2. Serve `dist` folder: `http-server dist`
3. Visit `/`, click the link, it loads fine
4. Refresh on the slug page

### What is Expected?

The page content (a h1 heading) will show

### What is actually happening?

The page content flashes but disappears. No error in console.

- /_nuxt/static/.../anv%C3%A4ndarhandledning/state.js:

   `window.__NUXT__=(function(a){return {staticAssetsBase:"\u002F_nuxt\u002Fstatic\u002F1616063786",layout:"default",error:a,serverRendered:true,routePath:"\u002Fanv%C3%A4ndarhandledning",config:{app:{basePath:"\u002F",assetsPath:"\u002F_nuxt\u002F",cdnURL:a}}}}(null));`

- /_nuxt/static/.../anv%C3%A4ndarhandledning/payload.js:

   `__NUXT_JSONP__("/anv%C3%A4ndarhandledning", {data:[{slug:"användarhandledning"}],fetch:{},mutations:void 0});`

**Comment by aekirgil** [comment]
Hi,
 is there any solutions? +1

**Comment by pi0** [comment]
Possibly related:
- #9400
- #9425
- 9297
