### ISSUE TITLE
share components

### ISSUE THREAD

**Issue by wormen** [nuxt/nuxt.js#902]
There is a directory structure
```
- project_1
- project_2
- share_components
```
It is necessary that `project_1` and `project_2` used components from `share_components`
At the moment, the components of `share_components` are ignored

For components from `share_components` used an alias

What are the variants so that `nuxt` does not ignore the files from the directory `share_components`?

**Comment by cawa-93** [comment]
Have you tried importing a component directly?
```js
import Component from '/share_components/component'
```

**Comment by wormen** [comment]
@cawa-93 No, I wrote that I used `alias`

**Comment by alexchopin** [comment]
@wormen Have you tried to import those component globally in a plugin with `vue.component()`?

**Comment by wormen** [comment]
@alexchopin This option does not fit
You need exactly the option that is described

**Comment by alexchopin** [comment]
This issue is not really related to Nuxt source code. I'm closing it but you can still add comment on it.
