### ISSUE TITLE
SSR - Only 100 requests per second with express-template-master example which is without database connection. 702 from 10 000 failed

### ISSUE THREAD

**Issue by nuxtdev** [nuxt/nuxt.js#9022]
### Versions

- nuxt: 
- node: 

### Reproduction

That is result of an example without database (with database I think will be like my app 10-20 req per sec)
https://github.com/nuxt-community/express-template

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /users
Document Length:        4092 bytes

Concurrency Level:      1000
Time taken for tests:   99.588 seconds
Complete requests:      10000
Failed requests:        702
   (Connect: 0, Receive: 234, Length: 234, Exceptions: 234)
Total transferred:      42130524 bytes
HTML transferred:       39962472 bytes
Requests per second:    100.41 [#/sec] (mean)
Time per request:       9958.825 [ms] (mean)
Time per request:       9.959 [ms] (mean, across all concurrent requests)
Transfer rate:          413.13 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  709 3122.9      2   65266
Processing:  2977 8186 13729.1   5560   93361
Waiting:        0 5373 3869.4   4922   49591
Total:       3015 8895 14332.6   5845   94407

Percentage of the requests served within a certain time (ms)
  50%   5845
  66%   6477
  75%   6968
  80%   7360
  90%   8455
  95%  13528
  98%  94389
  99%  94400
 100%  94407 (longest request)

Second 

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /users
Document Length:        4092 bytes

Concurrency Level:      1000
Time taken for tests:   108.360 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      43140000 bytes
HTML transferred:       40920000 bytes
Requests per second:    92.28 [#/sec] (mean)
Time per request:       10836.010 [ms] (mean)
Time per request:       10.836 [ms] (mean, across all concurrent requests)
Transfer rate:          388.79 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  781 2895.2      2   31442
Processing:  2805 9416 6771.8   7782   68919
Waiting:     1846 8482 6731.1   6981   68087
Total:       2813 10197 7551.3   8335   71966

Percentage of the requests served within a certain time (ms)
  50%   8335
  66%   9700
  75%  10624
  80%  11338
  90%  14449
  95%  21578
  98%  42033
  99%  43440
 100%  71966 (longest request)

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by danielroe** [comment]
@nuxtdev Do read through the advice posted in response to [your previous issue](https://github.com/nuxt/nuxt.js/issues/9001).

For support I'd recommend joining [our Discord server](https://discord.nuxtjs.org) and the channel to start with is #how-to-get-help. 🙃

**Comment by nuxtdev** [comment]
> @nuxtdev Do read through the advice posted in response to [your previous issue](https://github.com/nuxt/nuxt.js/issues/9001).
> 
> For support I'd recommend joining [our Discord server](https://discord.nuxtjs.org) and the channel to start with is #how-to-get-help.

I was on Discord and ask other questions but no body respond to it :)
