### ISSUE TITLE
How to add a new favicon

### ISSUE THREAD

**Issue by shyamchandranmec** [nuxt/nuxt.js#903]
I tried adding new favicon in static directory. But it still holds the old favicon. How to add a new one

**Comment by cawa-93** [comment]
Try add this in `config.js`
```js
    link: [
      {
        rel: 'icon',
        type: 'image/x-icon',
        href: 'favicon.ico',
      },
    ],
```

**Comment by shyamchandranmec** [comment]
@cawa-93 Its already there. Where should I place the favicon.ico file

**Comment by pi0** [comment]
Into `static` dir. Are you sure older favicon is not cached in browser?

**Comment by shyamchandranmec** [comment]
@pi0 I tried in incognito window.. Still it shows the old image.

**Comment by Kylart** [comment]
Perhaps try nuking the `.nuxt` directory and build again ? I had kind of the same problem and this solved it.

**Comment by ausir0726** [comment]
I put favicon.ico on static folder , and refresh browser few times , it updated new ico image.

**Comment by shyamchandranmec** [comment]
Fixed! . Removed the .nuxt directory and re-build the app again. Thanks @Kylart

**Comment by kelleysy** [comment]
thanks @pi0 :tada:

**Comment by mesqueeb** [comment]
I have the same problem with my build function. `favicon.ico` get's added nowhere to built directories.
Even if I delete everything.
This way my Firebase upload fails to include my favicon...

**Comment by McSneaky** [comment]
Just found out same bug / feature. Nothing in static folder is ever touched by Nuxt

**Comment by mesqueeb** [comment]
PS: I'm using "nuxt": "1.0.0-rc11" in order to have compatibility with Firebase. And I followed their [YouTube video](https://www.youtube.com/watch?v=ZYUWsjUxxUQ) how to do the build process.

It seems that you need to use `generate` in order for nuxt to copy over the static files? But the firebase tutorial doesn't use the generate command, only the `build` command.

**Comment by McSneaky** [comment]
As I thought it was my own stupidity. Had `RUN rm -rf assets components layouts middleware pages plugins store static` in Dockerfile
All works fine, but **static** folder should not be deleted. It needs to be deployed to production too
