### ISSUE TITLE
How can one log and catch all uncaught Nuxt errors?

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt.js#9031]
I'm a little lost with error handling and Nuxt, between 
- errorMiddleware
- errorCapture
- Vue.config.errorHandler

The description on the docs is rather...`cryptic`. 
```
Before adding Nuxt error middleware, useful to add your own middleware before using Nuxt's. See the Sentry module for more info.
```
(sentences don't usually start with "before")

Do you mind adding a short explanation on the 3 error handling hooks/handlers and for which case each one should be used for Nuxt?

Additionally, looking at the Sentry module? https://github.com/nuxt-community/sentry-module/blob/v4.0.3/lib/module.js 
 - there's plenty of stuff happening there - what exactly are we looking for?

In my specific case, my stdout is caught by Datadog, so I would only need to log in the right format the error - alongside with the trace. I tried doing that but nothing was logged. (the error was a JS template error)

**Comment by MentalGear** [comment]
Hi @gkatsanos, Did you find a way to handle/log errors in nuxt at a global level and could you share it?
