### ISSUE TITLE
Allow (.) dot in route

### ISSUE THREAD

**Issue by PUYUP** [nuxt/nuxt.js#9040]
I try make route with _.vue to accept path notation (/). All work but if route has dot (.) return not found.

Work -> **/best/framework/ssr**
Not found -> **/best/framework.ssr**

Any suggestions?

**Comment by Cpaczek** [comment]
I don't believe you are not allowed to have a . within a path at least it's not recommended because it's reserved for file extensions. ie. `google.com/robots.txt` would be confusing for a renderer is .txt supposed to be a page or an extension.
