### ISSUE TITLE
why not css-prefix

### ISSUE THREAD

**Issue by 86driver** [nuxt/nuxt.js#9041]
### Versions

- nuxt: v2.13.0
- node: latest

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
i import scss in nuxt.config.js where i write transition css,  when i open i website and f12, i cant see -webkit- -o- prefix

### What is Expected?
should auto add css prefix in style,  like vue 

### What is actually happening?
none css prefix in style

**Comment by 86driver** [comment]
> @86driver Nuxt uses [autoprefixer](https://github.com/postcss/autoprefixer) to automatically add the appropriate prefixes for the browsers you need to support. See [here](https://github.com/postcss/autoprefixer#browsers) for how to specify the browsers you want to target. You can also customise the options you pass to autoprefixer [using `build.postcss`](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#postcss).
> 
> In your case, `transition` is quite widely supported and generally doesn't need prefixing. But [here](https://codesandbox.io/s/quiet-bird-h6ccl?file=/assets/main.scss:72-76) is a code sandbox with `::placeholder` which _does_ need prefixing - which you can see in the generated HTML.

i have solute the problem, autoprefixer  must effect with browserslist, i forgot it

**Comment by 86driver** [comment]
but if i dont add browserslist in my package.json ,  create-nuxt-app will not add any css prefix. 
i think create-nuxt-app should add default browserslist  in  package.json.

by the way, when nuxt support vue3?

**Comment by Marvinrr155q** [comment]
Ohh well
