### ISSUE TITLE
Feature request: Force vuex activation even when no module has been found in /store

### ISSUE THREAD

**Issue by UltraCakeBakery** [nuxt/nuxt.js#9046]
### Is your feature request related to a problem? Please describe.
We register most of our vuex modules through plugins. These plugins are shared between multiple repositories. On of our projects has no store module on its own, but our custom `auth` plugin does. The plugin tries to register the module through `app.store.registerModule` but this fails because the store is not active (because there is no other module in /store)

### Describe the solution you'd like
An option in nuxt.config.js to force vuex to be active even without a file in store or /store folder at all. 

### Describe alternatives you've considered
Have a placeholder file in the store folder :/

**Comment by Soviut** [comment]
Are you wanting the create-nuxt-app to generate an empty index file? I thought it already did that.

Is there an issue leaving (or adding) an empty index file?

**Comment by manniL** [comment]
IIRC you can set `store: true` as top-level key in the `nuxt.config.js`.

https://github.com/nuxt/nuxt.js/blob/8b1a70476a7d757e94b56c0fd898229b9d21071f/packages/builder/src/builder.js#L401-L403

**Comment by UltraCakeBakery** [comment]
> IIRC you can set `store: true` as top-level key in the `nuxt.config.js`.
> 
> https://github.com/nuxt/nuxt.js/blob/8b1a70476a7d757e94b56c0fd898229b9d21071f/packages/builder/src/builder.js#L401-L403

This works! Thank you! 

Maybe it is worth adding a little note to the docs?
https://nuxtjs.org/docs/2.x/directory-structure/store#activate-the-store

**Comment by manniL** [comment]
Sure! PR welcome :)
