### ISSUE TITLE
Router.Base gets ignored in ssr production deployment

### ISSUE THREAD

**Issue by maatini** [nuxt/nuxt.js#9056]
### Versions

- nuxt: v2.15.3

### Reproduction

Generate a nuxt-ssr-app with nuxt cli.
Define router.base in nuxt.config.js eg 
router; {
   base: '/apps/demo'
}

Build app and deploy artifacts 
- .nuxt
- package.json and package-lock.json

Open app in Browser and look at the browser-console. If you reload the app you should see that the app tries to fetch js-scripts without the defined router.base which results in 404 status-codes.

Workaround: also deploy nuxt.config.js in deployment-directory.

**Comment by timelytree** [comment]
@danielroe would you be able to provide an example as to how to set `router.base` and `build.publicPath` at runtime? My assumption was to pass a function into each of these properties but it looks like they only accept strings. Should I use a `hook`?

**Comment by timelytree** [comment]
@danielpost ah that's what I thought - my issue is identical to #8229 (CC @rstormsf) — running in `target: static` using `generate` to build the static site and deploying to IPFS via Fleek.

> When I build the app, it should be working on the primary domain and also as ipfs hash
> example: `ipfs.myapp.com` OR `ipfs.io/ipfs/myappcom`

Do you have any insight as to how #8229 could be solved? In my testing I found that there are 3 places where paths are generated:

1. Assets (such as images)
2. Nuxt files (such as `payload.js` and `manifest.js`)
3. Routes

There are a variety of workarounds I've managed to implement to get 1 and 2 working well but getting all 3 has proven fairly difficult and hacky.
