### ISSUE TITLE
Accessing the meta fields in extendedRoutes defined in nuxt config

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#906]
I've been trying to get access to the `meta` field in `this.$route` in the `404.vue` page component. I copied the extendedRoutes example from [here](https://github.com/nuxt/docs/blob/master/en/api/configuration-router.md) and appended `meta` like below:

```javascript
module.exports = {
  router: {
    extendRoutes (routes, resolve) {
      routes.push({
        name: 'custom',
        path: '*',
        component: resolve(__dirname, 'pages/404.vue'),
        meta: { name: 'Pumpkin', age: 19 }
      })
    }
  }
}
```

I'm getting undefined when we access the above `name` variable using meta property. Although, the vue-router documentation says we can access it correctly [here](https://router.vuejs.org/en/advanced/meta.html)

**Comment by alexchopin** [comment]
Hi, 
meta property is not available in Nuxt.
https://github.com/nuxt/nuxt.js/issues/641

**Comment by yassipad** [comment]
I ran into the same issue and eventually the only way I found was to add this into "node_modules/nuxt/lib/app/router.js":

`res += tab + '\tcomponent: ' + route._name
    **res += (route.meta) ? ',\n\t' + tab + 'meta: ' + JSON.stringify(route.meta, null, tab + '\t\t').replace(/\"([^(\")"]+)\":/g,"$1:").replace(/}$/, tab + '\t}') : ''**
    res += (route.name) ? ',\n\t' + tab + 'name: ' + JSON.stringify(route.name) : ''`

It's not very clean and I hope this will get fixed but so far everything works as expected when adding meta fields through extendRoutes in nuxt.config as shown in the doc.
