### ISSUE TITLE
Head method doesn't work when using class decorators

### ISSUE THREAD

**Issue by kukosek** [nuxt/nuxt.js#9060]
I am trying to set a title for a specific page. I want it to be server rendered, so I don't want to set document.title in mounted() function.

### Versions

- nuxt: 2.15.3
- node: v15.11.0

### Steps to reproduce
1. Create a page
2. Make a typescript script in it and use Vue Class Component decorators
3.  Try defining a head function or a head object with a title set in it
I tried: `private head = {title: "My new title" } ` , `public head = {title: "My new title" } ` ,
```
head() {
    return {title: "My new title" } 
}
```
and
```
get head() {
    return {title: "My new title" } 
}
```
### What is Expected?
The title should be applied when the page is displayed

### What is actually happening?
Nothing, the title stays the way i set it in nuxt.config.js, in the head property (global page headers)

**Comment by danielroe** [comment]
@kukosek You can either:
1. Register the head hook yourself: https://class-component.vuejs.org/guide/additional-hooks.html
2. Pass the head method into `@Component({})`
3. Use `nuxt-property-decorator` (https://github.com/nuxt-community/nuxt-property-decorator)

**Comment by kukosek** [comment]
Thanks.  So I registered `head` as you said it before the component class definition, and in the class definition i have normal function like this:
```
head() {
    return {title: "My new title"}
}
```
