### ISSUE TITLE
Please add virtual host to nuxt.js

### ISSUE THREAD

**Issue by Rasool-deldar** [nuxt/nuxt.js#9062]
Please add virtual host to nuxt.js for dev and start

Is there a way I can use this feature now? Can you help?

**Comment by danielroe** [comment]
@Rasool-deldar could you explain more about what you mean?

**Comment by Rasool-deldar** [comment]
> @Rasool-deldar could you explain more about what you mean?

This means using http://local.me/ instead of http: // localhost: 3000 /

**Comment by manniL** [comment]
I personally think this is out of scope for Nuxt itself. You can move it behind NGINX or a similar proxy to achieve this without much extra work 😋
