### ISSUE TITLE
Can't override default webpack loader config

### ISSUE THREAD

**Issue by jdozierezell** [nuxt/nuxt.js#907]
I'm trying to override the default webpack config for the url-loader using the instructions found at https://nuxtjs.org/api/configuration-build/#loaders. Not having any luck though. Despite changing the folder name to dist/foo and changing the hash length, I'm still seeing images appear in the dist/img folder with a 7 character hash. Ultimately, I'm hoping to do something a little more complex with image-webpack-loader, but right now, not even this is working. Any idea what I'm doing wrong here? Thanks!

```
loaders: [
    {
      test: /\.(png|jpe?g|gif|svg)$/,
      loader: 'url-loader',
      query: {
        limit: 1000, // 1KO
        name: 'foo/[name].[hash:2].[ext]'
      }
    }
  ]
```

**Comment by pi0** [comment]
Hi @jdozierezell! Loaders will be simplified in next release. Will come with a more complete answer :)

**Comment by Atinux** [comment]
Hi @jdozierezell 

The `loaders` property will be removed, please use `build.extend` method to update the options of the `url-loader`.

**Comment by jdozierezell** [comment]
Thanks @Atinux. Is that something I can do now or will it need to wait until the next release?

**Comment by Atinux** [comment]
Closing it since `rc3` is out
