### ISSUE TITLE
TypeError undefined is not an object (evaluating 'f.fetch[this._fetchKey]') 

### ISSUE THREAD

**Issue by jonpreececm** [nuxt/nuxt.js#9071]
### Versions

- nuxt: 2.14.7
- node: 12.16.1

### Steps to reproduce

Bug is intermittent, I personally cannot reproduce on an emulated device.

1. Site is built with `ssr: true` and `target: 'static'`
2. `fetchKey` is not set
3. `fetchOnServer: true`
4. `fetch` is a function that returns a Promise

Only occurs on [this page](https://www.carbmanager.com) and only on Safari `14.0.1` or higher (seeing 87% of occurrences on `14.0.3`).  Seeing on iOS 14.4 mostly.

### What is Expected?
The error not to occur

### What is actually happening?
An error is thrown during hydration

```
TypeError undefined is not an object (evaluating 'f.fetch[this._fetchKey]') 
    https://www.carbmanager.com/_nuxt/f7c09ed.js:2:904036 d
    https://www.carbmanager.com/_nuxt/6413c5a.js:2:14962 Vt
    https://www.carbmanager.com/_nuxt/6413c5a.js:2:28812 Qe
```

**Comment by jonpreececm** [comment]
@danielroe still happens after upgrade to 2.15.5.  I don't have a replication unfortunately.  What information can I provide to you to help you diagnose the issue?

**Comment by jpcarpenter** [comment]
Hey @jonpreececm, did you ever find a solution for this?
