### ISSUE TITLE
Hydration of components with fetchHook in the layout scope will fail

### ISSUE THREAD

**Issue by juicejs** [nuxt/nuxt.js#9073]
Thank for the good work guys. We really enjoy using Nuxt In a lot of our web projects.

Short description:
If components are used outside of the page scope (i.e. inside a layout) a component with a fetch method will miss it's data-fetch-key attribute in html coming from the server-side. That's why the client-side hydration will fail, resulting in an error. We are using some asynchronously fetched content inside the `<header>` of the page. This `<header>` is used inside the layout, not the page. This bug occurs only after updating from Nuxt 2.14.6 to 2.15.3! Everything was working fine before that. The exact error that we get is:
**The client-side rendered virtual DOM tree is not matching server-rendered content.**

The error is caused because the VNodes are not matching some NodeList elements. These Nodes are generated based on asynchronously fetched data not the server side. The client doesn't receive this data. In the raw html markup the "data-fetch-key" is missing on the component that did the fetch. SO it triggers the fetch again on the client side, resulting in the same markup as coming from the server, but breaking the hydration.

Some example code to (hopefully) reproduce the issue:

**layouts/default.vue**
```
<template>
	<main>
		<FhHeader />
		<Nuxt />
		<FhFooter />
	</main>
</template>
...
```

**components/FhHeader.vue**
```
<template>
	<header>
          	...
		<FhSnippetMenu name="mainmenu"/>
         	 ...
	</header>
</template>
...
```

**components/FhSnippetMenu.vue**
This is the component that fetches the data asynchronously
```
<template>
	<FhContent :items="items"></FhContent>
</template>

<script>
	export default {
		name: 'FhSnippetMenu',
		props: ["name"],
		
		data () {
			return {
				items: []
			}
		},

		async fetch() {
			this.items = (await this.$wagtail.menus.$name(this.name)).items;
		},
		...
```

**components/FhContent.vue**
It uses this component to render the list of content
```
<template>
	<div class="fh-streamfield">
		<template v-for="(item, index) in items">
			<span> item.title</span>
		</template>
	</div>
</template>
<script>
	export default {
		name: 'FhContent',
		props: ["items"]
	}
</script>
...
```

### What is Expected?

The HTML markup that is rendered server side is looking correct. The component is populated with the dynamic content. Surprisingly when I move the `<FhHeader/>` BELOW the `<Nuxt />` Component, everything is working fine! However, when I remove the `<Nuxt/>` component entirely from the default layout, the error occurs again. 

Another thing I noticed is that when I wrap the `<FhContent>` inside the FhSnippetMenu.vue component inside another wrapper div things are working fine and as expected! But this can obviously not be the proper solution...

**components/FhSnippetMenu.vue**
This would work fine...
```
<template>
	<div>
		<FhContent :items="items"></FhContent>
	</div>
</template>
```

Any help would be much appreciated because I am dealing with this issue for 3 days now... Thank you in advance!

**Comment by juicejs** [comment]
> @juicejs For this very reason we recently added a feature (#8466) that allows you to set a custom `fetchKey`. I'd recommend setting it on all the fetch-enabled components within your layout (e.g. not within your page/route). You can find more info on how to use it in the PR or [the docs](https://nuxtjs.org/docs/2.x/components-glossary/pages-fetch).

Unfortunately this doesn't fix it. I have created a simple sandbox to reproduce the above issue.
https://codesandbox.io/s/practical-lake-z2bfz

Please have a look, it's a very bare bone project and I can't see that I have done anything wrong.

**Comment by danielroe** [comment]
@juicejs It's working in the CodeSandbox. Or perhaps I've misunderstood what you expect to happen.

**Comment by juicejs** [comment]
Hi @danielroe 

I have tested your sandbox. You are using the `nuxt generate && nuxt start` command. I am using the dev mode with the `nuxt` command. The fetch-key seems to be added in production, but why is this bug occurring in dev mode than?

It seems like the fetchKey has influence on the outcome. The hydration still doesn't seem to work...

**Comment by danielroe** [comment]
@juicejs The sandbox works fine in dev mode too. Or if not, could you please fork it and share it?

**Comment by juicejs** [comment]
Hib @danielroe 

Check this out: It's a fork of your project I just changed the script to the dev script. I get the hydration error in the console. Trust me, this error exists.

<img width="684" alt="Screenshot 2021-03-30 at 20 16 24" src="https://user-images.githubusercontent.com/48195761/113036592-cf0f3600-9194-11eb-98dd-c3fe85b0ccc3.png">

https://codesandbox.io/s/z2bfz?file=/components/FhSnippetMenu.vue

**Comment by juicejs** [comment]
Ah ok great, that's actually a pretty good explanation. 😄 You made my day with that answer, thanks buddy! 🤙🏼
