### ISSUE TITLE
CDN configuration challenges when using domain

### ISSUE THREAD

**Issue by SharadKumar** [nuxt/nuxt.js#908]
Ok, after spending few frustrating hrs with CDN engineers (MaxCDN) and hosting engineers (`zeit now`) too... I need help setup my site.

In nuxt.config:
```
  build: {
    publicPath: 'https://xxx.netdna-ssl.com/_nuxt',
    ...
```
Once deployed on `now`, I get my SSR render JS with path, for example...
```
<link rel="prefetch" href="https://xxx.netdna-ssl.com/_nuxt/6.nuxt.bundle.9abd8a19419e6d87b4cd.js" as="script">
```
Above domain points to SSL endpoint at MaxCDN. They cache the file when requested, back from my hosted domain. But here is the issue since when this file is requested it returns my web page with 404 instead of JS! If I remove CDN, JS is properly returned.

Whats wrong here? Any help is really appreciated.

**Comment by pi0** [comment]
Hey @SharadKumar! Would you please provide us some live demo or more information about build/deployment process?

**Comment by SharadKumar** [comment]
Sure @pi0 please see this:
https://auctionomy.website/ view source and try one of the bundle JS.

**Comment by SharadKumar** [comment]
I notice:
https://github.com/nuxt/nuxt.js/blob/0468c7997e80280eba823ee634f384baf7937e5c/lib/nuxt.js#L102-L105

Comments say that only serve static if not url.

**Comment by SharadKumar** [comment]
![image](https://user-images.githubusercontent.com/5488144/27228814-77410916-52ec-11e7-88ed-3c8f797c8bb5.png)

**Comment by pi0** [comment]
Yep nice catch. that's because nuxt has no data how to match CDN requests for serve `static` dir. (See [here](https://github.com/nuxt/nuxt.js/blob/0468c7997e80280eba823ee634f384baf7937e5c/lib/render.js#L49)). We could do some trick removing publicPath from baseURL too if it is URL.

**Comment by SharadKumar** [comment]
Static folder is served fine (if I were to serve via CDN but I am not at the moment)..
https://auctionomy-website-kalpasolutions.netdna-ssl.com/images/boys.png

Nuxt static resources is where the issue is.

**Comment by pi0** [comment]
Another Idea is providing a CDN module helper for better handling conditions like this. I will talk to @Atinux for that!

**Comment by Atinux** [comment]
Will be fixed in next release!

**Comment by Atinux** [comment]
Closing it since `rc3` is out
