### ISSUE TITLE
Code splitting broken with latest nuxt version

### ISSUE THREAD

**Issue by reinoldus** [nuxt/nuxt.js#9084]
### Versions

- nuxt: latest
- node: as in sandbox

### Reproduction

This sandbox has various webpack analyze "dumps" in /static -> this is the working one https://7fggl.sse.codesandbox.io/dump6.html

If you run yarn build -a you should find the analyze as in dump6

Once you run yarn upgrade nuxt in this sandbox:

https://codesandbox.io/s/holy-architecture-7fggl

you get a nice all in one bundle.

### What is Expected?

Proper code splitting like here:
![image](https://user-images.githubusercontent.com/2091290/113131482-f4985000-9225-11eb-88c1-94237f50ea92.png)

You'll see that "BModal" suddenly appears in the app-chunk and not in the foo/bar chunk anymore. The same for the error component.

### What is actually happening?

Pretty much no code splitting at all:
![image](https://user-images.githubusercontent.com/2091290/113130092-548df700-9224-11eb-9092-dd922e99c121.png)

**Comment by reinoldus** [comment]
This is was just a reproducible example my bundle looks like this:
![image](https://user-images.githubusercontent.com/2091290/113141260-26afaf00-9232-11eb-9d04-476b383ffd69.png)

There is definitely something wrong.

**Comment by reinoldus** [comment]
@danielroe I see the confusion. I just chose a very poor name for my test-component.

I added tiptap to sandbox:
![image](https://user-images.githubusercontent.com/2091290/113146222-14d10a80-9238-11eb-867c-b08a2f045a38.png)


I am importing the editor component in the page test.vue
And in the editor component I import tip tap.

https://codesandbox.io/s/holy-architecture-7fggl?file=/pages/foo/test.vue

**Comment by reinoldus** [comment]
I checked against the latest update: 2.15.4 and the issue still occurs: https://3b0ek.sse.codesandbox.io/dump10.html

![image](https://user-images.githubusercontent.com/2091290/113310200-a6ac4680-9310-11eb-9568-c2134d22c1f1.png)

**Comment by jonasdumas** [comment]
We got same problem here. Before nuxt@2.15 the code splitting was working perfectly. Since migration to nuxt 2.15 (wich force nuxt/component to V2), we have all our components in vendor and in app. Which create a huge size for the entrypoint from 1.3Mo to 4.2Mo. All config tested didn't change the behaviour decribed here.

**Comment by jonasdumas** [comment]
Any update on this ?

**Comment by pi0** [comment]
Hi @jamesgeorge007. Would you please recreate lock file to get latest update? Regression should be fixed.

**Comment by fatihsolhan** [comment]
I can confirm this is fixed 🎉 💯 

Thank you @pi0

**Comment by reinoldus** [comment]
same here, I will close the issue then! Thank you!

**Comment by qifei** [comment]
I start my project this month, use the latest Nuxt, but my app.js is 9MB, just a simple site.
I delete the lock file, and use `npm i --package-lock-only` to recreate it. but still.
What should I do? thanks

**Comment by danielroe** [comment]
@qifei I would suggest you [open a GitHub Discussion](https://github.com/nuxt/nuxt.js/discussions/new) - though note that it will be difficult for people to help without seeing your code/site.
