### ISSUE TITLE
[security] Check for privateRuntimeConfig Leaks

### ISSUE THREAD

**Issue by MentalGear** [nuxt/nuxt.js#9087]
### Is your feature request related to a problem? Please describe.
Leaking of API keys and other sensitive information.

It's essential to keep secret information hidden from the client. The addition of privateRuntimeConfig is a good step forward, but the feature is somewhat incomplete, since it is [not trivial to know what code runs on client or server in nuxt](https://github.com/nuxt/nuxt.js/issues/2033), and it is [even noted in the guide](https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#privateruntimeconfig
) that

> Your private config could be exposed if you use $config outside of a server-only context (for example, if you use $config in fetch, asyncData or directly inside your template).

Read: only using privateRuntimeConfig can't be relied upon - however that's what most people would expect from its name and most of the guide's description. Also, in actual development many people work on a code base and not many will look at stuff in a guide, especially if it comes with safe sounding names like this.

### Describe the solution you'd like
I would propose to add a function to check if the mentioned places (fetch, asyncData, template) contain the privateRuntimeConfig during dev/build/generate stages and display an error if it is detected.

That would bring developer peace of mind. Otherwise, if as devs we can't be sure that what we put into privateRuntimeConfig also stays private, it somewhat defeats its purpose.

### Describe alternatives you've considered
Different arch/labeling for nuxt that makes it clearer where functions run. 

### Additional context
https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#privateruntimeconfig

**Comment by MentalGear** [comment]
I'm reopening this issue, since the other issue @danielroe referred seems not moving forward, e.g. the proposed solution @nuxt/audit doesn't seem to exist and @pi0 is not responsive when asked about it.

I reiterate that privateRuntimeConfig could be a great single-source-of-truth security feature, but that in its current form it defeats that purpose as we can't rely on it. (if env. vars are used in other parts of nuxt like async which would leak them!)

I would like to help with/work on this issue, but would need some guidance. I would also propose to add this "env leak" check in the nuxt generate command and throw an error or warning, if env.vars are used anywhere but private/public runtimeConfig.

**Comment by pi0** [comment]
Using privateConfig is sometimes necessary in server side and places like data fetching to append private token. But it is never exposed to client unless you are explicitly doing (like {{ $config.token }}). Audit project is likely to merged with new nuxt cli service to check if a private config value existing in html output.

**Comment by MentalGear** [comment]
HI @pi0 Thanks for your reply! As mentioned in the original description (1st entry above), I'm concerned that, when working with people on a codebase (or when going back to old projects), not everyone might respect/remember/know about  private config and simply use $config. or env. vars where ever they find it useful.

Happy to hear that Audit is moving along! Let me know if I can help. Cheers :)
