### ISSUE TITLE
chore(deps): update dependency webpack 

### ISSUE THREAD

**Issue by harol-rodriguez** [nuxt/nuxt.js#9089]
Package | Change
-- | -- |
webpack | ^4.46.0 -> ^5.28.0

└─ webpack@4.46.0
   └─ ssri@6.0.1
![image (3)](https://user-images.githubusercontent.com/27013294/113208062-fd455200-9236-11eb-9474-34494e633c7b.png)

**Comment by danielroe** [comment]
@harol-rodriguez Thank you for the report. However, from the description, it looks like this is unlikely to be an issue for most users as webpack is a development dependency.

**Comment by FloydLegendary92** [comment]
Connect telegram... Chatt
