### ISSUE TITLE
"nuxt build" executes server middleware code when ssr : false.

### ISSUE THREAD

**Issue by dtoch** [nuxt/nuxt.js#9090]
### Versions

- nuxt: 2.15.3
- node: 12.20.2

### Reproduction

- package.json : 

```
{
  "name": "testbug",
  "version": "0.0.1",
  "dependencies": {
    "nuxt": "^2.15.3"
  }
}
```

- nuxt.config.js : 

```
module.exports = {

  ssr: false,

  serverMiddleware: [
    "~/api/app.js"
  ],

};
```

- api/app.js : 

```
console.log("call me on server!");
```

### Steps to reproduce

npm install
node_modules/.bin/nuxt build

### What is Expected?

nuxt build only creates the client and server bundles without running it.

### What is actually happening?

The console.log statement of api/app.js is executed, indicating that the serverMiddleware code is run during build which does not make sense in my opinion.

### Workaround

Workaround is to set ssr: true but then we need to reconfigure the dependencies to avoid errors like "ERROR  Cannot find module 'node-fetch' ..." because a part of the client code that we want to run on client side is now running in SSR mode on server-side.

**Comment by niksolaz** [comment]
I don't know if my solution is correct but you can insert a condition 'if' in  that check if ssr is true or false.

- api / app.js:

```
import config from '../nuxt.config.js'
if(config['ssr']) {
  console.log("CALL ME ON SERVER!!!");
}
```
I hope I have helped you.
If solution is not correct, please help me to understand why.
