### ISSUE TITLE
css-loader breaking change - compileType option no longer valid

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#9094]
### Versions

- nuxt: ^2.15
- node: 12.18.0

### Reproduction

css-loader latest version dependency has a new breaking change

### Steps to reproduce

Use latest css-loader version

### What is Expected?

Successful build

### What is actually happening?

Build errors:
```
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
  ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
  - options.modules has an unknown property 'compileType'. These properties are valid:
  object { auto?, mode?, exportGlobals?, localIdentName?, localIdentRegExp?, context?, hashPrefix?, getLocalIdent? }
```

**Comment by silverbackdan** [comment]
my apologies, I think that I had an old css-loader version and compileType is a newer option.

**Comment by Petercopter** [comment]
Nevermind! Found the problem. I had `@nuxt/tailwindcss 3.x`, and upgrading to `4.x` brought in a different version of `postcss`. What a twisted web we weave...

**Comment by barticus** [comment]
I had this same issue, according to my yarn.lock file, the vue-cli-tools wanted css-loader v3.6 but nuxt wanted >4.2 so i needed to add a resolution to resolve:
```
  "resolutions": {
    "css-loader": "^4.3.0"
  }
```

**Comment by InstanceOfMichael** [comment]
`css-loader@^4` and `css-loader@^3` and `css-loader@^5` seem to just be swapping whether the error message is `compileType` or `minimize`.

**Comment by InstanceOfMichael** [comment]
`yarn remove vue-loader` fixed it, there was a rogue `yarn add vue-loader` that was ran in the past, likely unnecessarily.

**Comment by harapeko** [comment]
this worked for me
```json
  "resolutions": {
    "css-loader": "^5.2.7"
  }
```

>css-loader v6.0.0
>the modules.compileType option was removed in favor the modules.mode option with icss value, also the modules option can have icss string value
https://github.com/webpack-contrib/css-loader/releases#:~:text=the%20modules.compileType%20option%20was%20removed%20in%20favor%20the%20modules.mode%20option%20with%20icss%20value%2C%20also%20the%20modules%20option%20can%20have%20icss%20string%20value
