### ISSUE TITLE
decorators in server-middleware does not work

### ISSUE THREAD

**Issue by topolar** [nuxt/nuxt.js#9096]
### Versions

- nuxt: v2.15.4 
- node: v14

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
Can't use decorators in server typescript middleware
</details>

### Steps to reproduce
Add to any typescript in serverMiddleware the property decorator

### What is Expected?
It should work

### What is actually happening?
Displayed error during build:
Support for the experimental syntax 'decorators-legacy' isn't currently enabled

**Comment by alkihis** [comment]
Hello, Jiti dependency has been updated and current version (1.9.1) now contains the proposed fix :smile:

**Comment by pi0** [comment]
To get update recreate lockfile || `yarn upgrade nuxt` || `npm up nuxt`

**Comment by YankeeTube** [comment]
same issue
