### ISSUE TITLE
In production environment, use ‘nuxt generate ’，images subdirectories are not compiled into CSS，it shows 404.

### ISSUE THREAD

**Issue by jurieo** [nuxt/nuxt.js#9098]
I'm Chinese.Forgive me for my poor English .haha
### Versions

- nuxt:  v2.15.3
- node: v14.7.0 

### Reproduction
I use ' nuxt generate  ' to build a static webside and the webside is not web root directory.The JavaScript can visit but used in backgroundImage is not work，it shows 404.

### Steps to reproduce

```
// nuxt.config
router: {
    base: "/test-static/",
  },

// index.vue - css
background: url("/images/nuxt.png");
``` 
 Use command  ‘nuxt generate ’ to generate it and deploy it that is not the root directory. 

dev is OK but prod is 404.
Thanks

### What is Expected?
![1](https://user-images.githubusercontent.com/18009286/113377546-2e449480-93a7-11eb-9a67-02a27270328e.png)
![3](https://user-images.githubusercontent.com/18009286/113377548-2f75c180-93a7-11eb-99b9-db231ed966e2.png)
![nuxtconfig](https://user-images.githubusercontent.com/18009286/113377552-30a6ee80-93a7-11eb-9976-0f0fcab3cce2.png)

dev env
![4](https://user-images.githubusercontent.com/18009286/113377549-300e5800-93a7-11eb-9f44-e2c331e83d0f.png)

prod env
![5](https://user-images.githubusercontent.com/18009286/113377550-30a6ee80-93a7-11eb-9769-f645103d8791.png)

### What is actually happening?
In production environment, use ‘nuxt generate ’，images  subdirectories are not compiled into CSS，it shows 404.

**Comment by danielroe** [comment]
@jurieo normally you'd want to include that in your webpack build (e.g. `background: url('~assets/banner.svg');`) - more info [in the docs](https://nuxtjs.org/docs/2.x/directory-structure/assets#images).

**Comment by jurieo** [comment]
> @jurieo normally you'd want to include that in your webpack build (e.g. `background: url('~assets/banner.svg');`) - more info [in the docs](https://nuxtjs.org/docs/2.x/directory-structure/assets#images).

Thanks for reply. sorry, Maybe I'm not making myself clear,I have a lot of big pictures in my project，I'll put them in the `static` folder,so in the production environment , the sever cann't find them, How should I configure it, thanks.

**Comment by danielroe** [comment]
Check out https://github.com/nuxt/nuxt.js/issues/4544 for some solutions.

**Comment by jurieo** [comment]
> Check out #4544 for some solutions.

Thanks, I just checked it carefully,and used in my project.But it still not work in css .
In addition,`<img src="~static/a.jpg">`  It will still compile in prod env. like this:
![01](https://user-images.githubusercontent.com/18009286/113401905-c017c600-93d6-11eb-8fdf-043578063c15.png)
![00](https://user-images.githubusercontent.com/18009286/113401800-9199eb00-93d6-11eb-817a-da59deed072b.png)

**Comment by jurieo** [comment]
`/favicon.ico` exists but still not work. please help me ，Thanks!
#### config
```
// nuxt.config.js 
// version:2.15.3
router: {
    base: "/test-static",
  },
```
![image](https://user-images.githubusercontent.com/18009286/113653506-8beb2080-96c8-11eb-9462-c3d6eea02092.png)
![image](https://user-images.githubusercontent.com/18009286/113652356-357ce280-96c6-11eb-85d5-f6889b93bddf.png)

**Comment by pervaizdattoo** [comment]
@jurieo Were you able to solve the issue?
