### ISSUE TITLE
$fetchState undefined with official example from documentation

### ISSUE THREAD

**Issue by mklueh** [nuxt/nuxt.js#9102]
I´m new to Nuxt.js and trying to get the $fetchState according to the documentation, but it is always undefined:

[https://nuxtjs.org/docs/2.x/features/data-fetching#the-fetch-hook](https://nuxtjs.org/docs/2.x/features/data-fetching#the-fetch-hook)

```
<template>
  <p v-if="$fetchState.pending">Fetching mountains...</p>
  <p v-else-if="$fetchState.error">An error occurred :(</p>
  <div v-else>
    <h1>Nuxt Mountains</h1>
    <ul>
      <li v-for="mountain of mountains">{{ mountain.title }}</li>
    </ul>
    <button @click="$fetch">Refresh</button>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        mountains: []
      }
    },
    async fetch() {
      this.mountains = await fetch(
        'https://api.nuxtjs.dev/mountains'
      ).then(res => res.json())
    }
  }
</script>
```

I´ve found a "workaround" on stackoverflow by using the old API approach

```
  async fetch() {
    const { store, error } = this.$nuxt.context

    try {
      await store.dispatch('home/fetchContent')
    } catch (e) {
      error({
        statusCode: 503,
        message: 'Unable to fetch'
      })
    }
  },
```

[https://stackoverflow.com/a/61774248/2324388](https://stackoverflow.com/a/61774248/2324388)

Why is the **official example** from the documentation **not working**? 
Am I doing something special so I´m running into an edge case?
Is this a bug of the new fetch API?

It´s very confusing...

**Comment by Arnique** [comment]
I'm facing the same problem. Seems $fetchState is not available in latest versions.

**Comment by danielroe** [comment]
@Arnique Would you be able to provide a reproduction?

**Comment by mirkofisic** [comment]
I have the same problem in version Nuxt @ v2.16.0-26938120.9247190c. If try to print console.log(this) I got:

`{
  components: Object <Object <Object <Complex prototype>>> {
    Subscribers: {
      props: [Object],
      data: [Function: data],
      watch: [Object],
      computed: {},
      methods: [Object],
      render: [Function],
      staticRenderFns: [],
      _compiled: true,
      _ssrRegister: [Function: hook],
      beforeCreate: [Array],
      __file: 'components/Subscribers.vue'
    },
    Translation: {
      props: [Array],
      data: [Function: data],
      render: [Function],
      staticRenderFns: [],
      _compiled: true,
      _ssrRegister: [Function: hook],
      beforeCreate: [Array],
      __file: 'components/Translation.vue'
    }
  },
  directives: Object <Object <Object <Complex prototype>>> {},
  filters: Object <Object <Object <Complex prototype>>> {},
  _base: [Function: Vue] {
    util: {
      warn: [Function: warn],
      extend: [Function: extend],
      mergeOptions: [Function: mergeOptions],
      defineReactive: [Function: defineReactive$$1]
    },
    set: [Function: set],
    delete: [Function: del],
    nextTick: [Function: nextTick],
    observable: [Function],
    options: {
      components: Object <Complex prototype> {},
      directives: Object <Complex prototype> {},
      filters: Object <Complex prototype> {},
      _base: [Circular],
      beforeCreate: [Array],
      destroyed: [Array],
      beforeMount: [Array],
      mounted: [Array],
      beforeDestroy: [Array],
      created: [Array],
      methods: [Object: null prototype]
    },
    use: [Function],
    mixin: [Function],
    cid: 0,
    extend: [Function],
    component: [Function],
    directive: [Function],
    filter: [Function],
    version: '2.6.12',
    _installedPlugins: [
      [Function],
      [Object],
      [Function],
      [Function],
      [Object],
      [Object],
      [Object]
    ],
    '$_vuetify_installed': true,
    __vuemeta_installed: true,
    __nuxt__fetch__mixin__: true,
    __original_use__: [Function],
    __install_times__: 2,
    '__nuxt_$config_installed__': true,
    '__nuxt_$icon_installed__': true,
    '__nuxt_$axios_installed__': true,
    '__nuxt_$auth_installed__': true,
    '__nuxt_$date_installed__': true,
    '__nuxt_$wallet_installed__': true
  },
  beforeCreate: [
    [Function: beforeCreate],
    [Function: vuexInit],
    [Function: beforeCreate],
    [Function: beforeCreate],
    [Function: beforeCreate],
    [Function: hook]
  ],
  destroyed: [ [Function: destroyed] ],
  beforeMount: [ [Function: beforeMount], [Function: beforeMount] ],
  mounted: [ [Function: mounted], [Function: mounted] ],
  beforeDestroy: [ [Function: beforeDestroy] ],
  created: [ [Function: created] ],
  methods: [Object: null prototype] {
    localePath: [Function],
    localeRoute: [Function],
    switchLocalePath: [Function],
    getRouteBaseName: [Function],
    closedSubscribers: [AsyncFunction: closedSubscribers],
    save: [AsyncFunction: save]
  },
  layout: 'manager',
  data: [Function: data],
  computed: { data: [Function: data] },
  fetch: [AsyncFunction: fetch],
  render: [Function: render] { _withStripped: true },
  staticRenderFns: [],
  _compiled: true,
  _ssrRegister: [Function: hook],
  __file: 'pages/manager/trainings/_id.vue',
  _Ctor: {
    '0': [Function: VueComponent] {
      cid: 660,
      options: [Circular],
      super: [Function],
      extend: [Function],
      mixin: [Function],
      use: [Function],
      component: [Function],
      directive: [Function],
      filter: [Function],
      superOptions: [Object],
      extendOptions: [Object],
      sealedOptions: [Object],
      _Ctor: [Circular]
    }
  },
  name: 'pages/manager/trainings/_id.vue'
}`

however I cannot populate any property within the data. console.log(this.training) is undefined, any data I want to acess is undefined, in the new version there are actually a lot of problems

**Comment by erny** [comment]
Using Nuxt @ v2.15.6 with node v14.17.0 on MacOS (10.14.6)

What I found a bit annoying is that if you use  `context` as argument of `fetch`, as stated [here](https://nuxtjs.org/docs/2.x/internals-glossary/context) :
> The context provides additional objects/params from Nuxt to Vue components and is available in special nuxt lifecycle areas like asyncData, **fetch**, plugins, middleware and nuxtServerInit.

e.g. to access URLs parameters using `context.params`, **`this` seems to be redefined and  `$fetchState` isn't available anymore**. I was able to access the URL params using  `this.$nuxt.context` as stated [here](https://nuxtjs.org/docs/2.x/components-glossary/pages-fetch):
> ...
> You can access the Nuxt context within the fetch hook using **`this.$nuxt.context`**
> ...

So, instead of doing this in `pages/items/_id.vue`:

    <template>
       ...
    </template>
    <script>
    data () {
      return {
        item: {}
      }
    },
    async fetch (context) {
        const url = 'http://...' + context.params.id
        const res = await fetch(url)
        ...
        this.item = await res.json()
    },
    ...

I had to do this:

    <template>
       ...
    </template>
    <script>
    data () {
      return {
        item: {}
      }
    },
    async fetch () {
        const url = 'http://...' + this.$nuxt.context.params.id
        const res = await fetch(url)
        ...
        this.item = await res.json()
    },
    ...

**Comment by danielroe** [comment]
@erny There are two kinds of `fetch()`:

1. `fetch(ctx)` - this only works on pages and cannot access `this` (also known as 'old-style' fetch - this is deprecated)
2. `fetch()` - this works in any component - only works in 2.12+

See [the docs](https://nuxtjs.org/docs/2.x/features/data-fetching) for more info - and note that we're planning to improve the docs on this further: https://github.com/nuxt/nuxtjs.org/pull/1363.

**Comment by erny** [comment]
@danielroe Thanks for your feedback. Sorry, I'm a new-comer. If you use 'old-style' `fetch(ctx)` in a page as I did, how to you set data (if you can't use `this`)?

**Comment by danielroe** [comment]
@erny You wouldn't use that hook if you wanted to set data. You could use asyncData instead.

**Comment by mattd233** [comment]
I get the same error my macOS Ventura running v16.16.0 in arm64 using the example code, the repo can be found here: https://github.com/mattd233/nuxt3-fetch-test (Sandbox doesn't seem to be working for me atm).
The error message I get is:
```
Cannot read properties of undefined (reading 'pending')

at Proxy._sfc_render (http://localhost:3000/_nuxt/app.js:24:23)
at renderComponentRoot (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:1941:39)
at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:5627:46)
at ReactiveEffect.run (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:388:19)
at instance.update (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:5723:52)
at setupRenderEffect (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:5731:5)
at mountComponent (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:5556:5)
at processComponent (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:5521:9)
at patch (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:5239:11)
at mountSuspense (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=3aa92c87:2173:3)
```
However, in my case, I think `fetch()` is not running at all as even if I get rid of `$fetchState`, it's still not working.
Can you let me know if you can recreate it or I just made a terribly stupid mistake.
