### ISSUE TITLE
Can I bypass `Consola` and avoid my logs being wrapped by it?

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt.js#9103]
Can I use a logging library (bunyan, paperplane etc) without these logs being wrapped by Nuxt's logging middleware `consola`?
I'd like to avoid having to configure a new Reporter and go through this

**Comment by pi0** [comment]
You can do this by calling `restoreAll`:

nuxt.config:

```
import consola from 'consola'

console.restoreAll()

export default {}
```

The alternative is using nuxt with [programmatic usage](https://nuxtjs.org/docs/2.x/internals-glossary/nuxt/) to bypass cli setup step.

**Comment by gkatsanos** [comment]
as a side-question : in order for my new logger middleware to be accessible throughout the nuxt project (server side / client side) would I need a module or a plugin?

**Comment by pi0** [comment]
A plugin :)

**Comment by gkatsanos** [comment]
@pi0 does consola wrap all `console` logs or will it also wrap other loggers, for example `pino` or others? (or does it wrap everything from process.stdout/sterr ?)
I was wondering if I dont have to use `restoreAll()` if I use another library to log
