### ISSUE TITLE
Problems with the Nuxt Composition API & Accessing Ref Json Content

### ISSUE THREAD

**Issue by Cpaczek** [nuxt/nuxt.js#9105]
Hi, I am using Nuxt and Strapi right now and I am having some trouble with getting data to render
Here is my setup() function
```
  setup() {
    const homepage = ref();
    useFetch(async ({$strapi}) => {
        homepage.value = await $strapi.find("home")
    })

    onMounted(()=>{
      console.log(homepage)
    })
    return {getStrapiMediaUri, homepage}
  },
```
and here is the console output and html
```
<h2 class="hero-h2 text-white">{{ homepage.sub_title }}</h2>
```

![](https://i.gyazo.com/6acfeac7aaefa67a2e96dcea9fe818dd.png)

I'm not sure why I can't access the ref data within the template however when I do
```
<h2 class="hero-h2 text-white">{{ homepage }}</h2>
```
It prints the json that I need

![](https://i.gyazo.com/3470ce2322ce36e9c8b462a03f132295.png)
I can make this work the the Options API and Vue however I want to try and use the composition api.

Also `{{ homepage.value.sub_title }}` does not work (value is undefined)

**Comment by Cpaczek** [comment]
Fixed it. Turns out JSON is case sensitive. Also it should be `ref()` not `ref({})`

**Comment by Marvinrr155q** [comment]
_fuck that_
