### ISSUE TITLE
Callback on rendered to disconnect socket

### ISSUE THREAD

**Issue by far4599** [nuxt/nuxt.js#911]
Hi guys,

I have tried your socket.io example and found out that each rendering creates new presistent socket conection to the server. To reproduce it you shall change io.on in server.js as follows:

```javascript
io.on('connection', (socket) => {
  socket.on('last-messages', function (fn) {
    fn(messages.slice(-50))
  });
  socket.on('send-message', function (message) {
    messages.push(message)
    socket.broadcast.emit('new-message', message)
  });
  console.log(Object.keys(io.sockets.clients().connected)); <-- new code
});
```

In the console you will see, that open connections list is growing on each page rendering. 

I would like to ask if there is a way to listen to event when rendering is finished and run callback to close sockets connection?

The current solution i see is to use setTimeout(callback, 60*1000) for example.

**Comment by pi0** [comment]
Hi @far4599. Are you using latest 1.x versions of Nuxt? It is using a global and not isolated SSR engine so this should not normally happen.

**Comment by far4599** [comment]
Ok. That works correct now with 1.x. But what does changed?
