### ISSUE TITLE
Initial route appears twice in browser history

### ISSUE THREAD

**Issue by Cpaczek** [nuxt/nuxt.js#9111]
### Versions

- nuxt: 2.15.4
- node: 12.18.3

### Reproduction

use `npm init nuxt-app my-app-name` to create a new app and leave everything defaults except change yarn to npm.

run `npm run dev`

go to `google.com`

paste in `localhost:3000`

It requires 2 clicks of the back button in order to get to google.com. 

### What is actually happening?

Because of how html5 [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) works I believe (not entirely sure) nuxt is loading the index.html (which pushes once to history) then changes the route to the /newpage and pushes another entry to the session history. This causes you to have to use back twice to get to the original page.

### What is Expected?

This is to be expected behavior when using  history mode however I think the default mode should be changed from 'history' to 'abstract'

This is really up to the core team to decide if they want to change the default mode. Currently, in the [docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router/#mode) it says that you should not change this mode due to server-side rendering however on the [vue documentation](https://router.vuejs.org/api/#mode) it says abstract mode should be used for server-side rendering (and is the default). 

I don't know exactly how `abstract` differs from `history` but from my limited testing, I don't see any downside. 

If the default does not get changed then I think that this solution should be somewhere more prominent in the docs.

**Comment by edisoft00** [comment]
My project is also having this problem in production also happens to me, I have been waiting for a solution for weeks.

**Comment by qinxuanxin** [comment]
me too.    HELP  HELP HELP

**Comment by Cpaczek** [comment]
@qinxuanxin is there a reason you can't use abstract mode. From my experience they function almost identically.

**Comment by qinxuanxin** [comment]
> @qinxuanxin is there a reason you can't use abstract mode. From my experience they function almost identically.
Thank you,I have solved the problem by using a lower version of Nuxt.
Most of the old code will operate the URL on the browser,so if i change to abstract mode, it will cost me.

**Comment by Cpaczek** [comment]
I have narrow this down to #9010 as reverting this 1 line of code will fix the double history push issue. As I am fairly new to nuxt I am not sure how to implement a fix to issue #9009 without breaking changes while still preventing a double history push. Thought this might be helpful.

**Comment by enwin** [comment]
Hi @Cpaczek. Thanks for narrowing it down. The linked PR should fix your issue. If you can test it I'd like your feedback on it.
