### ISSUE TITLE
Dynamic route /users/:id/billing

### ISSUE THREAD

**Issue by bjunc** [nuxt/nuxt.js#912]
I've seen the dynamic nested route example (eg. `pages/_category/_subCategory/index.vue`), but I haven't seen one that represents one similar to the example in the issue title.  I've tried `users-id-billing`, but that doesn't seem to work (`'regex' of undefined` error).  I'm not sure I even know what the folder structure would look like.  The docs seem to be lacking an example like this (static-dynamic, static-dynamic-static).

You'd need to be able to load the user's index component (so it's not a dynamic folder), and also load the billing component when navigated to.

Also, since in this case `billing` uses the parent user's data, is there a way to load the data at in the user's component, and pass that data down to the billing component?

Is this beyond the scope of server-side routing (basically, SSR stops at `/users/:id/` and the browser handles `/billing`)?  If so, how would one differentiate between routes handled by the server, and ones handled by browser?  Lastly, if there are browser-only routes, how do we prevent a 404?

Thanks!

**Comment by bjunc** [comment]
I was able to figure this out.  I think this is a pretty useful (ie. common) route, so I'm leaving it here for others (might be useful as part of the docs as well).

```
pages/
--| users
----| _user
----| _user.vue
-------| billing
---------| index.vue
```
> There are other folders/components you could add to this tree that would be useful, but I left them out as they might clutter the example, and don't speak directly to my original post.

The tree above will yield route names (among others):
```
users-user
users-user-billing
```

The `_user.vue` component will act as the parent to the `billing/index.vue` component.  You can load the user data with `asyncData` in the `_user.vue` component, then pass that data down to the nested `billing/index.vue` with `<nuxt-child :user="userData" />`.

I was able to piece this together from notes sprinkled around the routing guide.  Notably:

* Dynamic route requires the underscore.
* To get children views, the component name must match the folder name (eg. `_user` and `_user.vue`)
* Treating `billing` as a folder, not a component, then using `index.vue` as the default for that folder.

After figuring this out, it seems a little obvious looking back over the docs.  However, I think the examples could use a little better wording to make it easier to apply the examples in different situations.  Anyway, hope this helps the next guy (or gal).

**Comment by PrimozRome** [comment]
Thanks for this, helps a lot!

The nested route example is not even working and the documentation on this is also poor.
