### ISSUE TITLE
Wrong Warning when plugin that has a sourcemap is used from node_modules

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/nuxt.js#9121]
### Versions

- nuxt: v2.15.4
- node: v15.8.0

### Reproduction

1. Install latest version of nuxt
2. Install any npm package that has a `xx.js` and a `xx.js.map` in the same folder. (For example, I used `focus-visible` package)
2. Create a `nuxt.config.js` with the following `plugins:` definition:
```js
{
  plugins: [
    { src: './node_modules/focus-visible/dist/focus-visible.min.js', mode: 'client' },
  ]
}
```

### What is Expected?

That there are no warnings, since nuxt already has found the script and embeds it perfectly well-working in my app.

### What is actually happening?

A warning is being spitted out:
```
WARN  Found 2 plugins that match the configuration, suggest to specify extension: 
- /myproject/node_modules/focus-visible/dist/focus-visible.min.js
- /myproject/node_modules/focus-visible/dist/focus-visible.min.js.map
```

saying that I have to specify the extension. Which I did. I guess nuxt thinks because there is another file in this folder called the same, but with `.map` on the end, that I didn't specified the extension. 

This is happening to all packages with this file structure, so it's not related to the one I used. 

I found this issue, which has some similarities, and was already fixed a while ago: https://github.com/nuxt/nuxt.js/issues/4713

**I made a workaround**, by creating a new file in `plugins/focus-visible.js` which just does the following:
```js
import focusVisible from 'focus-visible/dist/focus-visible.min.js'

export default focusVisible 
```

and then telling nuxt to import this as
```js
{ src: '@/plugins/focusVisible.js', mode: 'client' },
```
This works, but it's obviously not great a kind of unneeded hack.

<br>
Thanks for looking into it!

**Comment by pervaizdattoo** [comment]
+1

**Comment by rifton007** [comment]
+1
