### ISSUE TITLE
Axios doesn't send cookies in requests from a middleware

### ISSUE THREAD

**Issue by Jacks349** [nuxt/nuxt.js#9126]
I'm using Nuxt (SSR Mode) for the frontend of an app that uses Django as the backend. I tried to create a very simple middleware that should send a request to Django to check if the user is authenticated (i'm using the standard Django Session Auth), but the problem is that the user is always logged out according to Django because the backend doesn't receive any cookie from the middleware. Note that the same code doesn't work from the middleware, while it works from a simple page:

```
import axios from 'axios'
axios.defaults.withCredentials = true;

export default function (context) {
  return axios({
        method: 'get',
        url: 'http://127.0.0.1:8000/checkAuth',
        withCredentials: true,
      }).then(function (response) {
        //handle success
      }).catch(function (error) {
        //handle error
      });
}
```

Here the cookie is not sent. If i try the exact same code from a page, instead, i will be a logged in user. 
I'm using nuxt@2.15.3 and the latest version of Nuxt/Axios, i even tried to downgrade Nuxt/Axios to various versions but nothing worked. 

I'm not sure if the problem is on my side because i keep getting it only from the middleware, so i wanted to report it. Keep up the awesome work on Nuxt!

**Comment by Jacks349** [comment]
Cookies are not sent because the middleware runs from server side, my bad!

**Comment by danielroe** [comment]
@Jacks349 Yes, that's as expected. You could use https://github.com/microcipcip/cookie-universal/tree/master/packages/cookie-universal-nuxt to read cookies in an isomorphic fashion and add them manually.

**Comment by Jacks349** [comment]
Thank you a lot @danielroe! I think the problem is that even when i set the cookies with the package you mentioned, Nuxt won't send the cookies when the middleware is executed from server side.

I'm sending the request from a  middleware to a Django backend, and when i try to print the Cookies of the request from Django, it will print an empty string `{}`, whereas when the middleware is executed from client side Django will receive the cookies.

Here is what i'm trying from the middleware:

```
app.$cookiz.set('somecookie', 'somevalue')

return axios({
  method: 'post',
  url: 'http://127.0.0.1:8000/checkAuth',
  withCredentials: true,
  headers: {}
}).then(function (response) {
  console.log(response)
}).catch(function (error) {
  console.log(error)
});

```

This in theory should set the cookie but Nuxt won't send it along with the request to Django when the request is fired from the server side middleware. If, instead i try exactly the same from a client side middleware, Django will see the cookie as expected.
Is it possible that there is something wrong with Axios? Or maybe am i missing something?

**Comment by Jacks349** [comment]
Solved by submitting the Cookies in the headers like this: `headers: {'COOKIES': 'my-cookies'`}
