### ISSUE TITLE
disabling scrolling doesn't work

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt.js#913]
added this to my nuxt.config.js

```js
  router: {
    scrollBehavior: function (to, from, savedPosition) {
      return savedPosition
    }
  },
```
and it still scrolls to the top 

here is the code https://github.com/acidjazz/waa/blob/master/nuxt.config.js#L92-L101

and here is a live URL of it not working
http://waa.256.io/data/state/georgia

scroll down and click NATIONAL, or any metro or district, and still scrolls back to the top

**Comment by Atinux** [comment]
Hi @acidjazz 

The documentation of vue-router (https://router.vuejs.org/en/advanced/scroll-behavior.html) says:

1. Returning the savedPosition will result in a native-like behavior when navigating with back/forward buttons
2. If a falsy value or an empty object is returned, no scrolling will happen.

You should return `false` into your `scrollBehavior` method.

Example: https://glitch.com/edit/#!/garrulous-wrench?path=pages/about.vue:4:20
Demo: https://garrulous-wrench.glitch.me/
