### ISSUE TITLE
i want to make code obfuscation, but i don't know how to do about it, please give a demo, thanks

### ISSUE THREAD

**Issue by PatrickKing-code** [nuxt/nuxt.js#9131]

**Comment by ranulf10** [comment]
Bueno mi papá murió hace unos días en México y no estuve presente ahorita
mi hermana está en el hospital hicieron una cirugía y ya se me acabó el
dinero ya así trabajando en los negocios ya no tengo cómo mover y no puedo
sacar a mi hermana al hospital porque estoy no tengo el resto me faltan
$1000 yo se lo pido un préstamo pero seguir trabajando y dile a mi hermana
no No pido que me los regalen sólo que me lo preste y también un poco más
para seguir trabajando negocio ya vendí mi computadora ya no tengo nada
para seguir trabajando gracias
