### ISSUE TITLE
刷新页面时使用fetch调用接口发现vuex存的内容没有重置为初始值

### ISSUE THREAD

**Issue by guoyucloud** [nuxt/nuxt.js#9136]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
同一个页面组件第一次使用fetch调用接口时存入一个vuex中。再次刷新页面发现vuex中依然有上一次存入的数据，并没有因为刷新页面清空vuex中的数据。

### What is Expected?
我希望刷新页面时可以重置vuex的数据。
但我不知道这到底是不是一个BUG，如果就是这么设计的，麻烦请回复一下其中的原因。谢谢。

### What is actually happening?
该问题导致每次使用vuex时需要将vuex重置为默认的值。

**Comment by cluyun** [comment]
定义vuex数据的代码贴出来看一下

**Comment by guoyucloud** [comment]
export const state = {
	orgiBBQ: 'yes'
};

export const getters = {
};

export const mutations = {
	SET_BBQ (state, value) {
		state.orgiBBQ = value;
	}
};
export const actions = {
};

**Comment by guoyucloud** [comment]
如果设置过这个值之后，再次刷新页面在fetch中获取该值会发现这个值没有因刷新而重新初始化。

**Comment by danielroe** [comment]
@cluyun Make sure to use a factory function for defining your state. (See [the docs](https://nuxtjs.org/docs/2.x/directory-structure/store)).

**Comment by cluyun** [comment]
> export const state = {
> orgiBBQ: 'yes'
> };
> 
> export const getters = {
> };
> 
> export const mutations = {
> SET_BBQ (state, value) {
> state.orgiBBQ = value;
> }
> };
> export const actions = {
> };

你没看官方文档吗，state要用箭头函数定义export const state => {}

**Comment by guoyucloud** [comment]
确实没注意到，想想很有道理，我去尝试一下，谢谢提醒。

**Comment by cluyun** [comment]
> 确实没注意到，想想很有道理，我去尝试一下，谢谢提醒。

解决了吗？解决了记得关issues啊

**Comment by guoyucloud** [comment]
已经解决了 非常感谢各位的解答 。
