### ISSUE TITLE
Netlify static build makes a change to all files on each build

### ISSUE THREAD

**Issue by adamchipperfield** [nuxt/nuxt.js#9138]
I have a Nuxt app set up with Netlify. It's statically generated with dynamic paths coming from Contentful.

Each time a build occurs Netlify reports over 900 changes to files, even if there was a minor content or code change. Why is this and how can we avoid this to reduce build times?

![image](https://user-images.githubusercontent.com/4995166/114184207-7847f000-993c-11eb-84a1-3fdc531793da.png)

**Comment by pervaizdattoo** [comment]
+1
