### ISSUE TITLE
yarn/npm audit found vulnerable package with severity as critical

### ISSUE THREAD

**Issue by beginner789** [nuxt/nuxt.js#9151]
### Versions

- nuxt: v2.14.12
- node: v14.15.4

### Reproduction

<details open>
<summary>Run yarn/npm audit from command line</summary>
<br>

</details>

### Steps to reproduce
yarn audit

### What is Expected?
None

### What is actually happening?
<img width="366" alt="Screen Shot 2021-04-14 at 23 15 07" src="https://user-images.githubusercontent.com/5079588/114743844-42a96980-9d77-11eb-95f2-d26414297cec.png">

**Comment by pi0** [comment]
Hi @beginner789. Last version of axios module ([5.13.1](https://unpkg.com/browse/@nuxtjs/axios@5.13.1/package.json)) has dependency on axios@0.21.1. You need to update lock file and dependencies.
