### ISSUE TITLE
Why click NuxtLink is very slow when some <img> is loading?

### ISSUE THREAD

**Issue by yunyuyuan** [nuxt/nuxt.js#9156]
### Versions

- nuxt: 2.15.4

A simple question,I think it's not even a bug.

I found that `<NuxtLink>` is very slow then `<a>` when the page have some `<img>` is loading.Seems that Nuxt must await all assets been loaded,then the `NuxtLink` just working.

Is there some config can fix this?

**Comment by yunyuyuan** [comment]
@danielroe 
Checked `Network`,when I click a `<NuxtLink to="/article"/>`,then **article** is pending but still 0B, until `img` loaded which before it.
You can try it easily,just need a `loading slow` img.
If I change this link to `<a href="/article" />`,the page will load immediately.But it will not been generated automatic in `npm run generate`.
If there has a prop like `<NuxtLink :immediate="true">`,it will been fine

**Comment by yunyuyuan** [comment]
@danielroe Well,I don't know why,and it's seems to be the problem of `router-link`,not `NuxtLink`

**Comment by wangkui1991** [comment]
Generated projects that require images to be loaded first and then js to be loaded when accessed, resulting in initial page lag

![image](https://user-images.githubusercontent.com/19390707/166841268-0f9d4579-d300-4ce9-b5b3-1251a2086584.png)
