### ISSUE TITLE
Server middleware is not included in .nuxt production folder

### ISSUE THREAD

**Issue by jozef-rzadkosz** [nuxt/nuxt.js#9158]
### Versions

- nuxt: 2.14.12
- node: 14.15.1

### Reproduction

Nuxt build server-middleware is not included in .nuxt build folder. I have one server-middleware with one express endpoint like: /contact/send and inside of it I am just sending simply post request and send an email from it by external email provider (SendGrid). Everything is working good but on dev mode, on production I am getting 404 and I cannot target my /contact/send endpoint anymore.

Here's a question in stackoverflow
https://stackoverflow.com/questions/67111986/nuxt-server-middleware-not-working-on-production/67113206?noredirect=1#comment118629365_67113206

### Steps to reproduce

1. create simply server-middleware
2. Build app and host it anywhere
3. Try to request it with httpie or postman etc.

If you cannot host this write this:

app.get('/test', (req,res) => {
   res.send('test');
})

After that try to find this in your production folder "test" and you will get no matching

### What is Expected?

When I write some endpoint to target I need to have it also in production mode after build.

### What is actually happening?

Server middleware function are not included in .nuxt folder and we cannot target them in production mode

**Comment by bhumit070** [comment]
but when i run  npm run build ; npm run start it shows in console that db connected , which I have console logged from server's js file so why is that

**Comment by bhumit070** [comment]
I am asking the server middleware works on dev build but at deploy time if i run the same command npm run build and npm run serve 

why my server middleware is not working

**Comment by bhumit070** [comment]
how could that be possible i am deploying to github and then it is connected to azure account which deploys automatically

**Comment by SergiuPlesco** [comment]
> @jozef-rzadkosz This is correct - server middleware aren't compiled or part of your webpack build and so you should make sure to copy them separately into production. (As well as making sure that any dependencies they have are installed in production.)
> 
> (Note that this will change with Nuxt 3 - you'll be able to have a single built server that includes your server middleware.)

Hi, I am new to nuxt. 
Can you point to a source how to do copying of the serverMiddleware into .nuxt on production. I am confused.

Thanks

**Comment by danielroe** [comment]
@SergiuPlesco That is only true for Nuxt 2. You can ignore this issue.

**Comment by SergiuPlesco** [comment]
> @SergiuPlesco That is only true for Nuxt 2. You can ignore this issue.

Thanks for your reply. The project i am working on is Next 2.
It simple one. The only functionality it has is sending emails with mailjet when a form is submited. And it uses a serverMiddleware. 
Will upgrading to next 3 solve the issue or copying will l? 

Thanks

**Comment by danielroe** [comment]
I would advise upgrading to Nuxt 3.
