### ISSUE TITLE
Preload <link> in `dist/index.html` are not rendered correctly when setting `router.base` from module

### ISSUE THREAD

**Issue by rarief** [nuxt/nuxt.js#9159]
I am setting the `router.base` config from a nuxt module for SPA nuxt apps. Starting from `v2.15.0`, the `index.html` file in the resulting `dist/` directory seems to be built incorrectly. More specifically, it seems the `href` in the `<link rel="preload" href="..." as="script">` contains incorrect URL as it does not include the value of the `router.base` config. See below for more details.

### Versions

- nuxt: `v2.15.4`
- node: `v15.0.1`

### Reproduction

Repo: [https://github.com/rarief/nuxt-router-base-issue](https://github.com/rarief/nuxt-router-base-issue)

**modules/test-module/index.js**
```javascript
const { resolve } = require("path");

export default function () {
  const { nuxt } = this;

  nuxt.options.router.base = '/app/' // <-- setting router base config here

  console.log(nuxt.options.router.base);
}
```

**nuxt.config.js**
```javascript
export default {
  ssr: false,

  ...

  modules: [
    '~/modules/test-module'
  ],
}
```

### What is Expected?

**dist/index.html**

```javascript
  ...
  <link rel="preload" href="/app/_nuxt/92dd6da.js" as="script">
  <link rel="preload" href="/app/_nuxt/36dabdf.js" as="script">
  <link rel="preload" href="/app/_nuxt/5c3a9b2.js" as="script">
  ...
  <script src="/app/_nuxt/92dd6da.js"></script>
  <script src="/app/_nuxt/36dabdf.js"></script>
  <script src="/app/_nuxt/5c3a9b2.js"></script>
  ...
```

### What is actually happening?

**dist/index.html**

```javascript
  ...
  <link rel="preload" href="/_nuxt/92dd6da.js" as="script">
  <link rel="preload" href="/_nuxt/36dabdf.js" as="script">
  <link rel="preload" href="/_nuxt/5c3a9b2.js" as="script">
  ...
  <script src="/app/_nuxt/92dd6da.js"></script>
  <script src="/app/_nuxt/36dabdf.js"></script>
  <script src="/app/_nuxt/5c3a9b2.js"></script>
  ...
```

Some more details:
- In `v2.15.0 - v2.15.4`, this issue does not happen when the `router.base` configuration is done directly in the `nuxt.config.js` file
- The issue does not happen in `v2.14.12`

**Comment by xixilalaha** [comment]
have u solve this problem?

**Comment by rarief** [comment]
@xixilalaha not yet, I am holding out to Nuxt `v2.14.12` for now.

**Comment by xixilalaha** [comment]
@rarief I am also on Nuxt v2.14.12, but it's not useful for me . I add the base as your way,it's just show me 404!

**Comment by rarief** [comment]
@xixilalaha could you please elaborate a bit more how did you get the `404` error when using `v2.14.12`?

**Comment by 1isten** [comment]
Same issue `v2.15.6`.

**Comment by AndrewFeeney** [comment]
I have just experienced this in nuxt `v2.15.7`

**Comment by jtc42** [comment]
I'm seeing this too. It's causing us real grief around managing our runtime configuration.
