### ISSUE TITLE
server-bundle.json is available from the browser

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#916]
I can access ```http://127.0.0.1:3000/_nuxt/server-bundle.json```

Shouldn't it be inaccessible because it can contain sensitive information?

**Comment by pi0** [comment]
@awronski  Nice catch! Will fix for next release.

**Comment by awronski** [comment]
Thank you!

**Comment by Atinux** [comment]
Closing it since `rc3` is out
