### ISSUE TITLE
when set height: 100% or 100hv 'scrollToTop' not working

### ISSUE THREAD

**Issue by IsidroMar95** [nuxt/nuxt.js#9162]
### Versions

- nuxt: 2.15.4 
- node: 14.16.1  

### Reproduction
When navigating between the pages it seems to always maintain the same position as before. I've set 'scrollToTop: true' for all pages (even though that is done by default). i am using the tailwind class `h-screen` and the scrollToTop does not work, when remove the class the scrollToTop work as expected

**Comment by danielroe** [comment]
@IsidroMar95 Does running `window.scrollTo(0, 0)` in the browser devtools do anything? If not, it's likely you'd have to write [your own scroll behaviour](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#scrollbehavior) to handle your setup. On the other hand, if it does, then could you provide a reproduction?

**Comment by IsidroMar95** [comment]
this is a reproduction link.
https://codesandbox.io/s/bug-scrolltotopnuxt-qbswh
try to go to the about page clicking the link at the bottom of the page then try to go back with the bottom button.

**Comment by apithy-isidro-martinez** [comment]
@danielroe could you please provide an example solution? i can't figure out how solve this issue
