### ISSUE TITLE
Nuxt pushes intial route twice to browser history

### ISSUE THREAD

**Issue by medokin** [nuxt/nuxt.js#9183]
### Versions

- nuxt: v2.14.0/v2.15.0
- node: v14 LTS

### Reproduction

Hitting the browser back button does not work if you just navigated to your nuxt application.

### Steps to reproduce

- Start your project
- Navigate to it on the browser
- Refresh the page
- Hit back Button

### What is Expected?

You get back to the last page.

### What is actually happening?

Nothing. You have to click again.

### Related
https://github.com/nuxt/nuxt.js/issues/9111

**Comment by danielroe** [comment]
closing in favour of #9111
