### ISSUE TITLE
nuxt@2.15.4 $router.back not work as expected

### ISSUE THREAD

**Issue by Jogiter** [nuxt/nuxt.js#9192]
### Versions

- nuxt: V2.15.4
- node: v14.15.1

### Reproduction

https://codesandbox.io/s/nuxt2154-routerback-error-7s1p8

[online demo](https://csb-7s1p8-pdrk39wuz-jogiter.vercel.app/#/)

```nuxt.config.ts
module.export.default = {
 // Disable server-side rendering: https://go.nuxtjs.dev/ssr-mode
  ssr: false,

  // Target: https://go.nuxtjs.dev/config-target
  target: "static",

  router: {
    mode: "hash"
  },

 // default ...
}
```

### Steps to reproduce

1. navigate from home to about 
2. refresh about 3 times
3. click a button to call `$router.back()`, the page is still about
4. after i clicked the back button 4 times, it navigate to home 

### What is Expected?

after the back-button once, it`ll back to home

**Comment by Jogiter** [comment]
the same config with nuxt@2.15.1 [demo](https://codesandbox.io/s/nuxt2151-routerback-j1pwq?file=/nuxt.config.js)

$router.back() work as expected.

**Comment by kozo002** [comment]
The same bug happens in https://nuxtjs.org/
