### ISSUE TITLE
after upgrading my nuxt app to latest release I got an error when navigating to any page in SSR

### ISSUE THREAD

**Issue by fahdaddi** [nuxt/nuxt.js#9196]
Hey @pi0, after upgrading my nuxt app to latest release I got an error when navigating to any page different than the home page, it shows the error: `This page could not be found`! while it was working perfectly in the nuxt@2.15

example of my pages config: 
```
export default {
  home: {
    frFR: '/:amp?',
    frBE: '/:amp?',
    itIT: '/:amp?'
  },
  'about-us/legal-terms': {
    frFR: '/a-propos/mentions-legales/:amp?',
    frBE: '/a-propos/mentions-legales/:amp?',
    itIT: '/a-propos/mentions-legales/:amp?'
  },
}
```

_Originally posted by @fahdaddi in https://github.com/nuxt/nuxt.js/issues/9010#issuecomment-826785251_

**Comment by dewita97** [comment]
Hey, I also encountered this issue. 

In my case, I have the _nuxt-trailingslash-module_ in my buildModules that removes '/' at the end of an url. By removing this package from my modules, the app runs as it needs to be. 

Try to investigate in your modules which one might not be compatible with the current version of Nuxt. 

Regards :)

**Comment by pi0** [comment]
https://github.com/nuxt/nuxt.js/issues/8274#issuecomment-839146055
