### ISSUE TITLE
Mounted hook not being called in components on production?

### ISSUE THREAD

**Issue by rabbitfufu** [nuxt/nuxt.js#9204]
Hello!

I have a component that is included on a page in Nuxt.

This component has a mounted hook:

```
<script>
export default {
	name: 'MyComponent',
	mounted() { alert('oh hai!') }
}
</script>
```

This works fine in development.  However when I export the site full static (nuxt generate) the code in the mounted hook appears not to run -- the alert never appears when the page is loaded.

I feel like I must be missing something obvious, but I can't figure it out.  Do the created/mounted lifecycle hooks get called on the components if they are used on full static sites?  If not, what is the recommended way to initialize the code that is used to control a component?

**Comment by rabbitfufu** [comment]
After a bit more testing, the mounted hook only gets called for me if it is placed in a layout, or in a component that is placed directly in a layout.  Any mounted hooks that are placed in page do not get called.  

For example...

In components/test.vue

```
<script>
export default {
	name: 'Test',
	mounted() { console.log('Test called') }
 }
</script>
```

In pages/home.vue

```
<template>
<div>
	<Test />
</div>
</template>

<script>
export default {
	name: 'Home',
	mounted() { console.log('Home called') }
}
</script>
```

In layouts/default.vue

```
<template>
<div>
	<Nuxt />
</div>
</template>

<script>
export default {
	name: 'Layout',
	mounted() { console.log('Layout called') }
}
</script>
```

In development this works as expected.
In production this results in pages being rendered but only "Layout called" is logged to the console.
The mounted hooks in the page and the component are not called.

However, if I change the above code to the following...

In components/test.vue

```
<script>
export default {
	name: 'Test',
	mounted() { console.log('Test called') }
 }
</script>
```

In pages/home.vue

```
<template>
<div />
</template>
```

In layouts/default.vue

```
<template>
<div>
	<Test />
</div>
</template>

<script>
export default {
	name: 'Layout',
	mounted() { console.log('Layout called') }
}
</script>
```

Now in production in the console I see "Layout called" and "Test called".  So it looks like there is something specifically about the page that is causing the mounted hook there not to execute.

There are no errors in the console in development, so I am at a bit of a loss as to where the issue might lie.  Any advice would be much appreciated.  Thanks!

**Comment by spire-phil** [comment]
I am seeing the same behavior, but am also new to Nuxt so have also wondered if I'm missing something fundamental.  

Just wanted to chime in since this seems like a strange/big issue if it is real 🙃

**Comment by spire-phil** [comment]
Thank you @danielroe for offering some help here!

I don't see any errors in production or in development mode in the console or in the build process.  Are there other places where I might be able to see such errors aside from the browser console or the cli where node is run from?

**Comment by spire-phil** [comment]
Also, js continues to be active and work (for example page interaction that depend on js on the client side).

**Comment by slavanossar** [comment]
Just encountered this seemingly out of nowhere, luckily it was only affecting a staging environment. Not entirely sure what was going on, no JS or hydration errors were showing.

Was affecting `2.15.4`, upgrading to latest version seems to have fixed it though.

**Comment by aih8** [comment]
nuxtjs: 2.15.8
node: 14.17.5
meet this problem again
config: ssr: true, target: static
script: npm run generate
mounted can not trigger in pages or the components used in pages
mounted can trigger in layouts or the components used in layouts 

@danielroe

**Comment by rabbitfufu** [comment]
@aih8  - Check that the files in your layouts, pages and components folders are named differently.

In my case I had...

pages/Home.vue
components/Home.vue

...with the Home.vue page importing the Home.vue component inside of it.
When I renamed things to...

pages/Home.vue
components/HomeComponent.vue

...the mounted hook magically started working again.

**Comment by aih8** [comment]
> > @rabbitfufu find out
> > I have page/index.vue in my project (SSG)
> > when I server folder dist, and open 'http://127.0.0.1:5500/', mounted will trigger in pages and components used in pages,
> > but mounted will not trigger when open 'http://127.0.0.1:5500/index.html'
> 
> Me too！ Is there any idea to deal with this？
> 
> node： 14.17.0 nuxt： 2.15.8

nginx 301

**Comment by tallroids** [comment]
I am seeing the same on out static builds where the mounted() hook only gets called on the initial page load, and subsequent visits do not trigger mounted. v2.15.8
- Visit page A, mounted() triggers
- Visit page B, mounted() triggers
- Visit page A, mounted() does not trigger

**Comment by schirrel** [comment]
I am facing the same issue, and m code has no error or exception

**Comment by paddotk** [comment]
Unless I'm missing something, I don't think you're supposed to put `~/index.html` in the URL. This doesn't load the Vue app, but the plain static html file that Vue loads into.

**Comment by mohamad68** [comment]
i have this problem too

**Comment by LuizPelegrini** [comment]
The issue is still present in Nuxt ^2.15.7. `mounted()` `created()`  hooks are not called inside a Statically Generated page (`nuxt build && nuxt generate`)

It only works when the hooks are inside the layout component, as mentioned by our peers above.

**Comment by danielroe** [comment]
If you can provide a minimal reproduction I'll happily reopen this.

**Comment by srchulo** [comment]
running into this as well with 2.15.8

**Comment by srchulo** [comment]
upgraded to 2.17.1 and still see the issue

**Comment by danielroe** [comment]
As I said above, if you can provide a minimal reproduction I'll happily reopen this.

**Comment by sholohov** [comment]
Is there any answer why this happens?

**Comment by silgon** [comment]
Encountering the same issue.

**Comment by silgon** [comment]
Anyway, I took a couple of minutes to recreate the issue in a new environment. @danielroe , could you take a look into it? https://github.com/silgon/nuxt_issue_9204 
The repo was created with `yarn create nuxt-app nuxt_issue_9204` with `javascript` and `vuetify.js`. I modified the file `NuxtLogo.vue` and included the following lines:
```html
<script>
 export default {
   mounted(){
     if(process.server){
       console.log("in server")
     }
     if(process.client){
       console.log("in client")
     }
       console.log("in both")
   }
 }
</script>
This recreates the problem on my side. Thanks in advance.
```

**Comment by danielroe** [comment]
@silgon this is a 3-year-old issue. Please raise a new one in future rather than commenting on old issues.

`mounted()` is a hook that only runs on the client, so it will never be called on the server. See https://vuejs.org/api/options-lifecycle.html#mounted.

**Comment by silgon** [comment]
sorry, my mistake. I was trying to create a d3 figure and I realized the svg was not being generated (since i cannot grab any component on the create hook to generate the svg), therefore there was a layout shift which I wanted to avoid. In any case, never mind, if I cannot do it with nuxt I'll use a placeholder. Thanks for the clarification @danielroe

**Comment by sholohov** [comment]
@danielroe the problem is that the hook works differently in different environments

**Comment by danielroe** [comment]
@sholohov I am replying to someone who has an unrelated issue. If you are experiencing this, please create a new issue with a reproduction 🙏
