### ISSUE TITLE
Is it possible to setup test cases with zuul for nuxt project?

### ISSUE THREAD

**Issue by zzhjerry** [nuxt/nuxt.js#922]
Basically I wonder how to properly create tests for browser compatibility. I looked at zuul but no doc said zuul works with ava test runner. I also think if it's possible to setup karma for testing with nuxt, it might work with zuul. Is this a valid idea?

**Comment by Atinux** [comment]
Hi @zzhjerry 

I never tried zuul but I guess it could work with Nuxt.js yes, you can try and come back to us :)
