### ISSUE TITLE
Error: "Must use import to load ES Module", but I'm already using `import`!

### ISSUE THREAD

**Issue by AaronBeaudoin** [nuxt/nuxt.js#9223]
### Versions

- nuxt: v2.15.4 
- node: v14 

### Reproduction

https://codesandbox.io/s/wizardly-rgb-8jpy8?file=/plugins/test.js

### Steps to reproduce

1. Create a new Nuxt project.
2. `npm i hast-util-select` to install the particular library I'm having trouble with (which by the way is part of a widely used ecosystem and work fine outside of Nuxt, so I'm pretty confident it's not the problem here).
3. Create a file `~/plugins/test.js` with the following code:

```js
import { select } from "hast-util-select";

console.log("test", select("p", {
  type: "element",
  tagName: "p",
  properties: {},
  children: [],
}));
```

4. Add the plugin to `nuxt.config.js`.

### What is Expected?

The project runs without errors.

### What is actually happening?

The error...

```
Must use import to load ES Module: /sandbox/node_modules/hast-util-select/index.js require() of ES modules is not supported. require() of /sandbox/node_modules/hast-util-select/index.js from /sandbox/node_modules/vue-server-renderer/build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /sandbox/node_modules/hast-util-select/package.json.
```

...is shown on the front-end.

**Comment by AaronBeaudoin** [comment]
Does anyone have time to look into why this is happening?

**Comment by syncopated** [comment]
Hey @AaronBeaudoin I ran into this today and was able to solve it by updating my nuxt.config.js build config to have it transpile the ESM packages like so:
```
// nuxt.config.js
  build: {
    transpile: [
      '@sindresorhus/slugify',
      '@sindresorhus/transliterate',
      'hast-util-select',
    ],
  }
```

**Comment by AaronBeaudoin** [comment]
> Hey @AaronBeaudoin I ran into this today and was able to solve it by updating my nuxt.config.js build config to have it transpile the ESM packages like so:
> 
> ```
> // nuxt.config.js
>   build: {
>     transpile: [
>       '@sindresorhus/slugify',
>       '@sindresorhus/transliterate',
>       'hast-util-select',
>     ],
>   }
> ```

This didn't have any effect for me. If you open up the CodeSandbox above and try it there, you'll see it makes no difference. Perhaps there's something else in your setup which is resolving the issue?

**Comment by syncopated** [comment]
@AaronBeaudoin I took a look and was able to get it working by adding all of the various esm packages to the transpile block of the nuxt config: [take a look at my fork of your code sandbox](https://codesandbox.io/s/floral-paper-kfele?file=/nuxt.config.js)

**Comment by syncopated** [comment]
Initially I was adding them as dependencies but that might not be necessary.

**Comment by AaronBeaudoin** [comment]
I originally only transpiled the `hast-util-select` package itself and not its dependencies. Thanks for clarifying!

I wonder however, if this workaround should be necessary at all, but that might be another issue.

**Comment by pi0** [comment]
Adding esmodule dependencies (and their dependnecies) to `build.transpile` is a good idea.

Alternatively, you can use `build.standalone: true` in `nuxt.config` file. (see [sandbox fork](https://codesandbox.io/s/vigilant-wildflower-wupcw?file=/nuxt.config.js))

With either workaround, way avoid [externalizing server bundle dependencies](https://github.com/nuxt/nuxt.js/blob/a53fd32d6bbdc0c2125426f36db720b5d23cdcf0/packages/webpack/src/config/server.js#L136) (nuxt2 uses CommonJS for building server and by default externalizes all `node_modules`. Which is broken with new type of packages that are (sadly) esm only.)

Since this kind of packages are getting more common in npm ecosystem, I think we might make a fork of webpack-node-externals that has continuous of package exports type, automatically inlining esmodules.

**Comment by existe-deja** [comment]
:+1: for the `build.standalone: true` solution.
I experienced this issue with d3 dependencies. Because d3 packages are using other d3 package as dependencies I would have to transpile every dependency.

**Comment by pmrotule** [comment]
Would be great that [`build.transpile`](https://nuxtjs.org/docs/configuration-glossary/configuration-build/#transpile) function receives the module path or even better, the resolved path in order to return `true` for any file ending with `.esm.js` or `.mjs`. Something like:

```js
build: {
  transpile: [
    ({ filePath }) => /(\.esm\.js|\.mjs)$/.test(filePath),
  ],
},
```

**Comment by toddpadwick** [comment]
I had this same issue but with `lodash-es`. To fix it, I added this to the nuxt.config.js build object:
```
   build: {
      transpile: [
          'lodash-es'
       ],
   }
```

So if you add the packages to the transpile array hopefully it should work.

**Comment by yussan** [comment]
> Hey @AaronBeaudoin I ran into this today and was able to solve it by updating my nuxt.config.js build config to have it transpile the ESM packages like so:
> 
> ```
> // nuxt.config.js
>   build: {
>     transpile: [
>       '@sindresorhus/slugify',
>       '@sindresorhus/transliterate',
>       'hast-util-select',
>     ],
>   }
> ```

waw thanks, this solving my same problem on import axios for ssr nuxtjs

**Comment by ChloeQQQ** [comment]
@pi0  thank u so much !!! it was solved it ~~~~i spent 3 hours !!!
