### ISSUE TITLE
Allow prefix in route directory structure

### ISSUE THREAD

**Issue by Caceresenzo** [nuxt/nuxt.js#9227]
### Is your feature request related to a problem? Please describe.

There should be a way to declare a prefixed routes directly with the directory structure.

Things like `/@:username` not seems to be possible without using the [router-extras-module](https://github.com/nuxt-community/router-extras-module).

### Describe the solution you'd like

Naming file like: `/pages/@_id/index.vue` could work?
But with something like this, someone will want the suffix version too. So I am not sure :/

### Describe alternatives you've considered

Using the [router-extras-module](https://github.com/nuxt-community/router-extras-module) with:
```vue
<router>
  {
    path: '/@:username'
  }
</router>
```

<details>
  <summary>(full dummy file)</summary>
  
```vue
<template>
  <h1>{{ username }}</h1>
</template>

<script>
export default {
  asyncData({ params }) {
    const { username } = params

    return { username }
  },
}
</script>

<router>
  {
    path: '/@:username'
  }
</router>
```
</details>

### Additional context

none

**Comment by danielroe** [comment]
@Caceresenzo Depending on the reason behind what you're asking, you might be able to achieve what you want by using [the `validate()` hook](https://nuxtjs.org/docs/2.x/components-glossary/pages-validate/). Example:

`~/pages/_username.vue`
```js
export default {
  validate({ route }) {
    return route.path.startsWith('/@')
  }
}
```

Failing that, the [router-extras-module](https://github.com/nuxt-community/router-extras-module) is probably the best solution.

**Comment by Caceresenzo** [comment]
@danielroe will this leave the `@` in the params?

**Comment by danielroe** [comment]
@Caceresenzo Yes.

**Comment by Caceresenzo** [comment]
@danielroe thanks for your time.
Its a little bit hacky, but should do the trick :)
