### ISSUE TITLE
Enter transitions not working

### ISSUE THREAD

**Issue by silveltman** [nuxt/nuxt.js#9229]
### Versions

- nuxt: 2.15.3
- node: v14.16.1

### Reproduction
For the reproduction I used yarn create nuxt-app to create a blank project. I chose javascript, yarn and universal > static.  I did not select anything else. 

I exactly copied the vue 3 transition example on their page on the index.vue (https://v3.vuejs.org/guide/transitions-enterleave.html#transitioning-single-elements-components)

Reproduction github repo:
[https://github.com/silveltman/nuxt-transitions-test](url)

### Steps to reproduce
Clone the reproduction repository
Install node modules
Yarn dev
Look if the enter transition is working

### What is Expected?
The text 'hello' should fade in and out. So a working enter and leave transition. 

### What is actually happening?
Just the leave transition is working, the enter transition is not.

**Comment by hanneskuettner** [comment]
nuxt is based on Vue 2 for the time being and [transition class naming has been changed from Vue 2 to Vue 3](https://v3.vuejs.org/guide/migration/transition.html#_2-x-syntax). 

If you change your `.fade-enter-from` to the `.fade-enter` class it will work.

**Comment by silveltman** [comment]
Okay thanks, didn't know that. So no composition API and stuff either? Or is it just the transisions that are based on vue2

**Comment by hanneskuettner** [comment]
No Vue 3 specific functionality, no.

There is however [the composition API package](https://composition-api.nuxtjs.org/) that aids with using some of the Vue 3 awesomeness. 
Nuxt 3 which has been announced will be fully Vue 3 compatible.
