### ISSUE TITLE
Hydration error with fetch() and @nuxtjs/component-cache module 

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt.js#9242]
### Versions

- @nuxtjs/component-cache: v1.1.6
- nuxt: v2.15.4
- node: v10.24.1

### Reproduction

https://codesandbox.io/s/runtime-paper-n0yom

The same issue described in this ticket - https://github.com/nuxt/nuxt.js/issues/7161, but it was closed.

### Steps to reproduce

Open the page, than refresh it.

### What is Expected?

Page should render the `links` and show no errors in the console.

### What is actually happening?

No `links` rendered and hydration error in the console - ```Mismatching childNodes vs. VNodes```.

**Comment by enkot** [comment]
@danielroe Thanks for the clarification!

**Comment by kchjxxgh** [comment]
If no fetch(), what do you want to cache? It doesn't make sense.

**Comment by kchjxxgh** [comment]
> @enkot The component cache should not be used if there are side-effects on the global context - which there are with `fetch()`. (See [docs](https://ssr.vuejs.org/guide/caching.html#component-level-caching).)
> 
> Specifically, the side effect is that `fetch()` injects updated component state into the rendered HTML. If you're interested, you can see that the first request to your sandbox _works_ because this state _is_ injected - but subsequent requests fail because the cached component state is used (without the injected HTML, which was the side-effect).

If no fetch(), what do you want to cache? It doesn't make sense. Cache pure static html?
