### ISSUE TITLE
I have to reset server when i create new pages

### ISSUE THREAD

**Issue by ghostlexly** [nuxt/nuxt.js#9249]
### Versions

- nuxt: v2.14.7
- node: v12.20.1

### Reproduction

- Main OS: Windows 10 
- Working on: Debian virtual server with virtualbox and shared folders
- Dockerized node

### Steps to reproduce

Create a new nuxt project
Add new page called for example: "new.vue"
Check .nuxt/routes.json and server console, the new page is not added to routes.json and you can't access the page on localhost/new

### What is Expected?

The routes.json file should refresh automatically.

### What is actually happening?

The routes.json keep the old configuration. I have to restart my docker to make the new page work.
It's probably due to shared folders. The new file creation is not detected.

**Comment by danielroe** [comment]
@ghostlexly Check out https://github.com/nuxt/nuxt.js/issues/2481#issuecomment-356074552 and let me know if that solves things for you.

**Comment by ghostlexly** [comment]
Still not working, there is the configs i tryed in nuxt.config.js file :

`
  watchers: {
    webpack: {
      aggregateTimeout: 300,
      poll: true,
    }
  },
`

`
  watchers: {
    webpack: {
      aggregateTimeout: 1000,
      poll: 1000,
    }
  },
`
