### ISSUE TITLE
Trying to use Nuxt on top of a CMS API

### ISSUE THREAD

**Issue by dan-gamble** [nuxt/nuxt.js#925]
I'm trying to build an API on top of our current CMS which could then use Nuxt on the frontend.

One of the problems i'm facing the API returns all of the pages as an array like so:

```json
pages: [
  {
    ...
    "content_type": "content:",
  },
  {
    ...
    "content_type": "people:",
  },
]
```

This is on top of Django currently so we have tie this up with `content.html` and `people.html` then serve the relevant data.

What i'm trying to do with nuxt is something like:

```
- pages
  - content
    - index.vue
  - people
    - index.vue
    - _id.vue
```

Where it will match the folder based on the `content_type` from the API.

How would i best achieve this? In middleware, with custom routes?

Sorry for the vague question / issue i'm not that great of a problem solver when it comes to this kind of complexity :)

**Comment by Atinux** [comment]
Hi @dan-gamble 

Does your API have a route to give the `content_type` and the `id`? Something like `/api/:content_type/:id` which give back the page for the given `content_type` & `id`?

**Comment by dan-gamble** [comment]
Currently it's just `/api/pages/` which gives [this response](https://gist.github.com/dan-gamble/685d0608e710ea083c0e21cf99d670e0)

Pages would be built like `domain.com/about-us/people/` which should ideally point to `pages/people/index.vue` then `domain.com/about-us/people/john-doe/` which points to `pages/people/_slug.vue`

**Comment by Atinux** [comment]
You need to do 2 things:
1. Get all the pages `content_type`, `url` and `absolute_url` into your store `nuxtServerInit` to know all your pages of your application
2. Inside your `pages/people/_slug.vue`, you need to call your store action to know if this slug is a valid content page, then fetch your API to get the content and display it in your page.

**Comment by dan-gamble** [comment]
Thanks!

I was giving this a bit of thought as well.

Is it possible to generate `nuxt.config.router.extendRoutes` dynamically? That way i could create the `routes` object in my backend which would return:

```json
"routes": [
  {
    "path": "/"
]
```

**Comment by Atinux** [comment]
You can do it by using nuxt modules system, you might want to wait a little bit for us to release it :)

In the meantime your can add the logic into your `*.vue` pages to fetch and list the pages from your API

**Comment by jamestowers** [comment]
> You can do it by using nuxt modules system, you might want to wait a little bit for us to release it :)

@Atinux Which module are you referring to? Has it been released yet? This is exactly what i'm trying to do :)

**Comment by jamestowers** [comment]
Ah, [this one](https://github.com/nuxt-community/router-module) ? 

Is it possible to fetch `router.js` from an api call to the CMS's database?
