### ISSUE TITLE
Project building stops on 90% because of TypeScript and ESLint settings in "nuxt.config.ts"

### ISSUE THREAD

**Issue by TokugawaTakeshi** [nuxt/nuxt.js#9250]
Although this problem is similar to [#2921](https://github.com/nuxt/nuxt.js/issues/2921), I investigated that now the cause is different. The client side building stops on 90%:

![image](https://user-images.githubusercontent.com/41653501/117424041-556d2380-af5c-11eb-8f9e-57cac91537f7.png)

If we comment out or delete typescript and eslint settings in `nuxt.config.ts` (below listing), the application building became normal. But it's unacceptable to stop to use ESLint.

```
typescript: {
    typeCheck: {
      eslint: {
        files: "./**/*.{ts,js,vue}"
      }
    }
  }
```

### Versions

- nuxt: 2.15.4 (newest)
- node: 14.16.1 (LTS)

### Reproduction

[Repository](https://github.com/TokugawaTakesi/Nuxt-Reproduction-0507)

### Steps to reproduce

1. After retrieving of above repository, run `npm install` as usual.
2. Run "nuxt"
3. In my computer, the project building stops on 90%:

![image](https://user-images.githubusercontent.com/41653501/117423566-d24bcd80-af5b-11eb-8518-2b1fe5fa0484.png)

If in your computer project has been build successfully, this issue is environment-dependent which means it will be hard to find the cause.

4. Comment out lines 36-42 of `nuxt.config.ts` and run `nuxt` again. In my computer, it's cures the project building but could not be the solution.

**Comment by TianbinTobin** [comment]
@TokugawaTakeshi 

add  .eslintignore
```
dist/*
.nuxt/*
node_modules/*
```

**Comment by TokugawaTakeshi** [comment]
@TianbinTobin Thank you for the answer.
Unfortunately, it did not solve the problem...
