### ISSUE TITLE
issue with redirect in fetch

### ISSUE THREAD

**Issue by ziaadini** [nuxt/nuxt.js#9259]
### Versions

- nuxt: ^2.15.3

hello i'm using fetch and i have an issue with status code here is my code when process is on the server : 

` this.$nuxt.context.redirect(302, {
          path:'my path',
          query: this.$route.query
        }) `

### What is Expected?
set status code to 302 when requesting with postman

### What is actually happening?
redirect work fine in the browser but status code dos not set as expected

**Comment by luaz** [comment]
In `nuxt.config.js`
- If `target: static`, the redirect would happen on client side without proper status code (on dev)
- If `target: server`, the redirect would happen with proper status code (I assume status code could only be set for SSR)

**Comment by danielroe** [comment]
In general, redirect should not be used within new-style `fetch()`. It happens too late in the server-side request lifecycle (in the `serverPrefetch` hook).
