### ISSUE TITLE
Support Plugins in TypeScript

### ISSUE THREAD

**Issue by johnlindquist** [nuxt/nuxt.js#926]
Something with the way Nuxt.js tries to load/require TypeScript-based plugins (like `axios.ts`) causes builds to fail. 

Maybe https://github.com/nuxt/nuxt.js/blob/dev/lib/app/index.js#L25 is skipping the ts-loader in my nuxt.config.js? Or is the nuxt.config.js not loaded yet?

**Comment by jvbianchi** [comment]
It might be related with https://github.com/nuxt/nuxt.js/pull/914

**Comment by chymz** [comment]
Hi @johnlindquist , i've same problem here, but found a little workaround :

In `nuxt.config.js` :
```js
plugins: [
    '~/plugins/ts-plugins'
],
```

In `plugins/ts-plugins.js`
```js
import Vue from 'vue';
import { MyPlugin } from './my-plugin';

export default async ({ store }) => {
  Vue.use(MyPlugin, { store });
};
```

And finally my **typescript** plugin `plugins/my-plugin.ts` :
```ts
export class MyPlugin {
  static install (Vue, options) {
    // Some code
  }
}

**Comment by BruceHem** [comment]
It would be nice to be able to use ts everywhere.

**Comment by husayt** [comment]
This seems to be resolved now. Closing.
See https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript

**Comment by chanlito** [comment]
In the example plugins still written in js

**Comment by 0pt1m1z3r** [comment]
@Atinux @pi0 @clarkdo Guys, plugins still not support TypeScript
