### ISSUE TITLE
LightHouse: How to Remove Unused Javascript?

### ISSUE THREAD

**Issue by rosnaib11** [nuxt/nuxt.js#9265]
In next.js they got package called [`next-unused`](https://www.npmjs.com/package/next-unused)

![image](https://user-images.githubusercontent.com/26837762/117624173-357d7000-b1a7-11eb-953c-8a384f6a9077.png)

**Comment by danielroe** [comment]
closing in favour of https://github.com/nuxt/nuxt.js/discussions/8849 unless there's a specific feature request you had in mind.
