### ISSUE TITLE
If an async component with client-only run error on server-side, it will lead memory leak.

### ISSUE THREAD

**Issue by HuberTRoy** [nuxt/nuxt.js#9279]
### Versions

- nuxt:  v2.15.4
- node: v14.16.1

### Reproduction
Create a page with async component:

pages/index.vue:

```javascript
<template>
  <div class="container">
      <client-only>
        <test />
      </client-only>
  </div>
</template>

<script>
export default {
    components: {
        test: () => import('@/components/xx.vue')
    }
}
</script>
```
components/xx.vue:

```javascript
<template>
    <div>
        456789
    </div>
</template>

<script>
const test = testGlobal

export default {
    data() {
        return {
            a: new Array(10000).fill('1111')
        }
    },
    mounted() {
        this.log()
    },
    methods: {
        log() {
            console.log('it is a global var', test)
        }
    }
}
</script>
```
I declare a variable `test` that is an alias from outer:

app.html

```html
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head {{ HEAD_ATTRS }}>
    {{ HEAD }}
    <script>
        var testGlobal = {}
    </script>
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}
  </body>
</html>
```

therefore the `xx.vue` will run error on server-side but run good on client-side and beacuse I import it with `import()` and use `client-only` to wrap it, then build and start, get the page, the memory will rise until crash.

I know how to fix it in code but I have two question for this, it is some werid for me.

1. Why a `client-only` component will run on server-side?
2. Why the error will lead memory leak? 

Thanks.

### What is Expected?
Don't run `client-only` component on server-side or dont lead memory leak.

### What is actually happening?

`client-only` component run on server-side and lead memory leak.

**Comment by HuberTRoy** [comment]
@danielroe 
Thanks. I slove it by using `process.client` to get what import on both side: `process.client ? import('xxx') : Promise.resolve({ render: (h) => h('div') })`.

Actually, the question that bothers me is other member download a third party library by npm and lead a memory leak, and when I debug it the console give me an error on server-side in dev but I ignored it beacuse I am sure the code use `clinet-only` to wrap and works fine in production(except memory leak) and dev. 

I dont know this will lead memory leak so I debug again and again= = and finally I took a few hours to found the problem. The [doc at client-only](https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component) dont make me know it will load on server-side and if it goes error will lead memory leak.

Should we give a warning in doc to ask developers know this? It's hard to reproduce but if it has, will hard to debug.

**Comment by HuberTRoy** [comment]
@danielroe 
Yes, it's better than a warning.

**Comment by iurisilvio** [comment]
The client-only directive with dynamic import still leaks.

My empty component is a simple `<template><div>.</div></template>`.

## Leak

The dynamic component import with a function leaks.

```vue
<template>
  <div>
    <client-only>
      <empty />
    </client-only>
  </div>
</template>

<script>
 export default {
   components: {
     Empty: () => {
       // DO NOT DO THIS: MEMORY LEAK!!!
       if (process.client) {
         return import('~/components/empty.vue')
       }
     }
   }
 }
</script>
```

## Alternatives

You can lazy set the component var and it doesn't leak.

```vue
<template>
  <div>
    <client-only>
      <empty />
    </client-only>
  </div>
</template>

<script>
// Lazy initialization works. No leak here.
let Empty
if (process.client) {
  Empty = require('~/components/empty.vue')
}
export default {
  components: {
    Empty
  }
}
</script>
```

Another option is using `client-only`, dynamic import and a flag to not load the module server side.

```vue
<template>
  <div>
    <client-only v-if="clientMounted">
      <empty />
    </client-only>
  </div>
</template>

<script>
export default {
   components: {
     Empty: () => {
       // It works because of the clientMounted flag.
       if (process.client) {
         return import('~/components/empty.vue')
       }
     }
  },
  data () {
    clientMounted: false
  },
  mounted () {
    this.clientMounted = true
  }
}
</script>
```
