### ISSUE TITLE
Invalid handler for event "click": got undefined

### ISSUE THREAD

**Issue by UsmanJavedAttari** [nuxt/nuxt.js#9294]
### Versions

- nuxt: ^2.15.3
- node: 14.16.0

### Reproduction
https://codesandbox.io/s/admiring-borg-5i1l4

### Steps to reproduce
- Make a simple project (JS, or TS).
- Make a page
- Make a component which receives a prop (prop must be a class)
- Make a class and export it
- import the class in page and assign in data like `product: new Product()`
- Pass `product` to the component. .e.g., `<product :product="product" />`
- Now you need to bind any method of the class from the component (.e.g., bind `@click="class.method"`)
- Everything will work.
- now add `fetch()` into the page or component.
- Make sure you refresh the page.
- Now you will see `WARN  Cannot stringify arbitrary non-POJOs ProductModel` on terminal.
- And on browser console you will see: `[Vue warn]: Invalid handler for event "click": got undefined`.

### What is Expected?
The handler must be bind without any error.

### What is actually happening?
You can visit the link above, the issue is due to the class instance I think.

<summary>Additional Details</summary>

I also tried putting `toJSON` method in the class, you can see it under product model class, I have commented it. Someone suggested to put `toJSON() { return {} }`, but that didn't work, so you can see the current `toJSON` method in the class, if you will uncomment it, it will give you a circular dependency.

**Comment by UsmanJavedAttari** [comment]
Real project is built-on TypeScript, and I am having different models in my project. I am initializing them in class component, and getting this: (only if I add `fetch`):

![image](https://user-images.githubusercontent.com/38417879/118136688-3c7bcc80-b3b9-11eb-9e3d-b67f1bbb8ef9.png)

And on the console:
![image](https://user-images.githubusercontent.com/38417879/118136749-4bfb1580-b3b9-11eb-964b-2799799b37f4.png)

**Comment by UsmanJavedAttari** [comment]
Just simply say `fetch` is useless in TypeScript based projects, nothing else.

**Comment by voracious** [comment]
I had a similar issue where regular function names could not be bound in the SSR context. To fix it, I just had to update the function name to an expression that Vue recognized.

#### Before

```vue
<SomeElement @some-event="onSomeEvent" />
```

#### After

Note the added parenthesis.

```vue
<SomeElement @some-event="onSomeEvent()" />
```

or

```vue
<SomeElement @some-event="() => onSomeEvent()" />
```
