### ISSUE TITLE
Generate dynamic routes with accent marks impossible to get it working

### ISSUE THREAD

**Issue by jgrandar** [nuxt/nuxt.js#9297]
### Versions
- nuxt: v2.15.5
- node: v14.16.1

### Reproduction
https://codesandbox.io/s/codesandbox-nuxt-2h2md
https://github.com/jgrandar/codesandbox-nuxt/tree/master/

<details open>
<summary>I would like to get a full static site without a API backend so all API calls should be done on the generate proccess, it work fine as soon as you don't use accent marks on the URL.

- Route and API URL with accent marks: nuxt generate produce errors and these pages will default to SPA.
- Route with accent marks and id for API URL: nuxt generate doesn't produce errors but fallback to SPA requesting the API when page is loaded. This method would not be valid on other situations as is not possible to get the id if user try to access directly typing the ULR on the browser bar or if the page is refreshed but as I am using nuxt generate the page should be available with the data thanks to the nuxt crawler at compilation time.
</summary>
</details>

### Steps to reproduce
Go to the codesandbox or clolne locally the repo.
Make sure you choose the right axios urls on pages/productos/index.vue and pages/productos/_slug/index.vue files:
Uncomment the "api/..." line if working locally or "https://2h2md.sse.codesandbox.io/api/..." if testing on codesandbox. 
Try to run "yarn nuxt generate" switching on file pages/productos/_slug/index.vue the axios URL "id" and "slug".

### What is Expected?
Routes with accent marks should be generated with no SPA fallback or generate errors and no API calls should be done once generated.

### What is actually happening?
nuxt generate produce errors if you use id to retrieve the data from backend (seems like only allow to use the dynamic parameter used to generate the route for the asyncData() method in order to get the crawler working).
![2021-05-16_01-35](https://user-images.githubusercontent.com/9372396/118381347-4fc1ae80-b5ea-11eb-9208-161c6edea0a0.png)
You can navigate any dynamic route but will request data from the backend.

nuxt generate will fallback to SPA if route contain accent marks and you use the route slug as parameter on the asyncData() method (note how you can navigate to "productos/auriculares" without backend request but it will if you navigate to "productos/teléfonos-inalámbricos").
![imagen](https://user-images.githubusercontent.com/9372396/118381602-afb95480-b5ec-11eb-947e-6446192e5930.png)

**Comment by meinenieuwland** [comment]
I had a similar problem with accent marks, but I think it's any special character which get encoded. The thing I noticed is that the payload's are generated properly for these routes. But can't be resolved on the client for some reason.

This is the generated payload:
![image](https://user-images.githubusercontent.com/3862658/122562499-6b81ff80-d043-11eb-95eb-c5045e10dcba.png)

When I changed the path manually with the special characters, it worked again.
![image](https://user-images.githubusercontent.com/3862658/122562509-6fae1d00-d043-11eb-8f17-2406bced6b25.png)

We had to change all our url's not using specials characters to fix this :(
