### ISSUE TITLE
Vue provide/inject functionality returns different instances of the object if fetch method provided

### ISSUE THREAD

**Issue by ilearnjs** [nuxt/nuxt.js#9304]
### Versions

- nuxt: 2.15.0
- node: 14.16.1

### Reproduction
https://codesandbox.io/s/nuxt-providefetch-ic3w2

#### Details
Parent
```javascript
fetch() {}, // the problem after adding this
data() {
  return {
    obj: {
      val: 0,
    },
  };
},
provide() {
  return {
    obj: this.obj,
  };
},
```

Child
```javascript
<div>Same instance: {{ obj === $parent.obj }}</div> <!-- false with fetch, true w/o -->
...
export default {
  inject: ["obj"],
};
```

### Steps to reproduce
1 Open codesandbox project
2 Go to `Page 1`

### What is Expected?
Provided `$parent.obj` and injected `obj` are the same object (check `Page 2` for expected result)

### What is actually happening?
Provided `$parent.obj` and injected `obj` are different objects

**Comment by Otaku-gsf** [comment]
i have the same problem
