### ISSUE TITLE
How do we pass props to a page?

### ISSUE THREAD

**Issue by patchthecode** [nuxt/nuxt.js#9305]
In regular VueJS in the route file we can do this:   `props: true`

```
const router = new VueRouter({
  routes: [
    { path: '/user', component: User, props: true }
  ]
})
```

This means that if i did this 
```
this.$router.push({name: 'user', params: {
  myKey: 'my value'
})
```

then inside the index page i have this

```
props: {
   myKey: {
      type: Object,
      default() { return {} }
   }
}
```

Then when ever i do a push to this route, i will be able to access my props inside my `user` page.
Since in Nuxt the route file is autogenerated by Nuxt, how are we able to pass props to a page like in Vue above?

**Comment by patchthecode** [comment]
I have already checked this page for reference https://github.com/nuxt/nuxt.js/issues/8669
But it doesnt seem to answer the question

**Comment by nort3x** [comment]
hi @patchthecode why did you close this?
did you manage to make this work?

i don't want to show user data in url and i don't want to monkey patch it with store/state what is the solution @danielroe?

**Comment by patchthecode** [comment]
@nort3x i dumped nuxt and went back to vue3.
Nuxt is good, but for me i had many places i needed specialized control, and Nuxt is a magic black box where everything is done for you.

I wish nuxt stays like this BUT ALSO allows for custom configuration where needed. But since it was hard for me i dumped it.
