### ISSUE TITLE
Is it possible to use Nuxt without SSR?

### ISSUE THREAD

**Issue by alekbarszczewski** [nuxt/nuxt.js#931]
I would like to use Nuxt without SSR. I am not talking about `nuxt generate` because it does not support dynamic params in routes (I know it's possible to fetch params dynamically on build time but I need `real` dynamic params). I would like to serve application like normal SPA app: for each path serve same index.html with router that takes care of routing on client side. Is it possible?

**Comment by alexchopin** [comment]
https://github.com/nuxt/nuxt.js/issues/499
