### ISSUE TITLE
Some corejs modules are imported regardless of target browsers

### ISSUE THREAD

**Issue by Solant** [nuxt/nuxt.js#9315]
### Versions

- nuxt: 2.15.6
- node: 16.1.0

### Reproduction

https://github.com/Solant/nuxt-corejs-issue

This is fresh `yarn create nuxt-app` with some config changes:

<details open>
<summary>nuxt.config.js changes</summary>
<p>

```js
  build: {
      corejs: 3,
      babel: {
        presets({ isModern }, [preset, options]) {
            if (isModern) {
                options.targets = 'last 1 Chrome versions';
            }
        },
      },
  },
    modern: 'client',
```

</p>
</details>

### Steps to reproduce
Run `yarn build -a`, check `modern.html` output

### What is Expected?
`core-js` modules like `web.url`, `es.promise` should not be included in build (as per compat data https://github.com/zloirock/core-js/blob/master/packages/core-js-compat/src/data.js#L1580)

### What is actually happening?
core-js modules are still there
![image](https://user-images.githubusercontent.com/5971578/118954535-87bc4f00-b966-11eb-9234-a6708e697c32.png)

**Comment by AndrewBogdanovTSS** [comment]
@Solant are those the only modules that shouldn't be included for modern build? I suspect there should be more

**Comment by Solant** [comment]
@AndrewBogdanovTSS yep, there are a lot of smaller modules, like replaceAll and so on. 
Those two are the largest ones that I noticed
