### ISSUE TITLE
[edge] Nullish operator available with node 14 only

### ISSUE THREAD

**Issue by mercs600** [nuxt/nuxt.js#9321]
I think issue is related with that change: 
https://github.com/nuxt/nuxt.js/commit/186df335d926b56f8eec5249d6330363622390b3#diff-cba57dce8689b0b15bac4cd779357605a9c6ce76da7d424eedf8c4eb385b75d8R92 

I think it should be transpilled, but is not, because I get an error:

```bash
/Users/merc/Projects/OpenSource/mymodule/node_modules/@nuxt/config-edge/dist/config.js:1119
  const dev = configOverrides.dev ?? options.dev ?? configContext.dev;
                                   ^

SyntaxError: Unexpected token '?'
```

Or should we use node 14 ? But I don't think so it is required at the moment. 

### Versions

- nuxt: edge 
- node: 12.20 

### Reproduction

just run nuxt-edge on node 12.20

**Comment by rlam3** [comment]
@mercs600 were you able to find a workaround?

**Comment by mercs600** [comment]
@rlam3 just downgrade :-)

**Comment by pi0** [comment]
You can also upgrade to `nuxt-edge@2.16.0-27031305.f4a6b384` or later :)

**Comment by daniluk4000** [comment]
Still doesn't work for me tho. 
![изображение](https://user-images.githubusercontent.com/10450717/150127195-183f6403-7bed-4ef2-91ac-9e5a29faa1eb.png)

My babel config:
![изображение](https://user-images.githubusercontent.com/10450717/150127262-08dfd802-d882-4416-a7af-56ede843c258.png)

Node version: 16.13.2
