### ISSUE TITLE
Static Site Generation Issue: CSS Styles Applied Differently Depending on Site Navigation

### ISSUE THREAD

**Issue by LloydThinks** [nuxt/nuxt.js#9325]
### Versions

- nuxt: v2.15.3
- node: v16.0.0

### Reproduction

No code, I have a question that is hopefully just a misunderstanding about NuxtJS.

### Steps to reproduce

Working Example
1. Go to https://lloydm.io
2. Scroll and notice the CSS styling around the headers
3. Click the menu in the top right, go to "Publications"
4. Click my head to go back to the main page. Everything works fine.

Broken Example
1. Go directly to https://lloydm.io/career/research/publications
2. Now click my head in the top left to go back to the home page
3. Notice the styling is no longer correct
4. Refresh the page, styling is fixed

### What is Expected?

I expect that the styling applied to each independent of how you got there. However, it appears that the styling is only properly applied if the user arrives at my site directly to the home page.

### What is actually happening?

Styling is not always applied correctly.

### Additional Notes

- I arrived at this current issue originally when my pages were not rending at all. It appeared to be some issue with fetch not being called in components. Issues #7799 and #7791 seem to discuss this, but the issue persists. I fixed that problem by moving all requests (to the Nuxt Content API) to asyncData methods in the pages above those components (not ideal, but works). However, now I still have this persistent css styling issue.
- I am using TailwindCSS for the majority of my styling. Most of the time inline in the HTML, but also using `@apply` in the style tags of Vue. This could be the issue but due to the complexity of the Nuxt static site generator, I have no idea how to start looking into this.

Any and all help is appreciated. I know I have not posted code or configs, but I think I am misunderstanding something basic about how NuxtJS works, and therefore hoping the issue can be resolve with a couple comments. Otherwise, I can look into making my code public in some way.

Lloyd

**Comment by LloydThinks** [comment]
Hi @danielroe thank you for the advice. I have been hacking away at this issue for the past 3 hours and I've narrowed it down to the use of `@apply` for TailwindCSS styling. You are right that the ordering is the issue, however, what is not clear is why the server-rendered version works fine, but the statically generated site does not. Is it the case that CSS @apply 's do not work when using SSG?

So again perhaps I can get some clarity: what is different when using the SSG? Can I not expect certain things to work?

I'm currently trying to work around this issue by writing my own CSS override mixin, but this is very laborious and perhaps not possible.

Lloyd

**Comment by LloydThinks** [comment]
I have addressed the issue by removing all `@apply` usage and instead applying the TailwindCSS classes directly in the html `class` elements.

Essentially, `@apply`ing TailwindCSS classes is powerful because it will override TailwindCSS classes defined in child components, thus allowing you to define default classes in components, and overriding those classes with `@apply` in parent classes. This doesn't appear to work when using NuxtJS SSG and navigating in certain cases (_I still don't know why this, and I maintain that this is a bug_).

So, without this `@apply` functionality, I instead define the TailwindCSS classes in the child component that are default and cannot be overridden. Anytime I need to override a default, I remove it from the child component, and manually list the values I want in all of the parents that use that component. This is of course not very elegant, readable, or extendable, but it works.

Lloyd

**Comment by danielroe** [comment]
@LloydThinks If you think there is a bug, would you be able to provide a minimal reproduction via https://template.nuxtjs.org ? That would be very helpful, as it is difficult to evaluate without one.

**Comment by LloydThinks** [comment]
Are you able to run `npm run generage` and `npm run start`? If so, I would give it a try.

**Comment by danielroe** [comment]
Yes. Just update your `dev` script in the codesandbxo `package.json` accordingly.

**Comment by LloydThinks** [comment]
I had to restart the server to force the command to run. Even reloading the webpage did not work. I will keep working at it.

**Comment by LloydThinks** [comment]
Alright well I got it to run the `nuxt generate && nuxt start` commands by going to the "server control panel" and selecting "restart sandbox". However, it doesn't appear to be actually generating files in the `/dist` folder. Additionally, the browser on the left doesn't appear to loading the static files (since there are none in the `/dist` folder, yet the browser renders the same page).

Am I missing something?

**Comment by danielroe** [comment]
You may not see the dist folder but it will exist.

**Comment by LloydThinks** [comment]
Alright well I wasn't able to get all the way to producing the bug I wanted, but the sandbox actually get stuck up on another bug.

When the static site generator is used, the `@apply bg-blue-100;` style in the index.vue is not applied. If you switch the package.json back to `MINIMAL=1 nuxt` it does apply that style. My issue I wanted to report is the same bug, but only when switching routes from another loaded page.

https://codesandbox.io/s/sweet-saha-gibo6

Lloyd

**Comment by LloydThinks** [comment]
Hi @danielroe,

> It's normal that dev/production have different orderings of CSS.

I think I have a lot more to learn about CSS then. This was unknown to me. I will do some research into the specificity of CSS to improve my laying.

Thank you for all your help!
Lloyd
