### ISSUE TITLE
Static deployment not working with custom error and preview pages

### ISSUE THREAD

**Issue by JonathanDoelan** [nuxt/nuxt.js#9347]
I’m deploying a static site with `target: 'static', ssr: true` to a hosting service. In my app I’ve configured custom error pages layouts/error.vue as well as “live preview” for pages that aren't generated yet (nuxtjs.org/docs/2.x/features/live-preview).
In my local environment, everything works fine — when I run `yarn generate` and `yarn start`.

I’ve tried to achieve the same behaviour with hosting providers (I’ve tried all "static" services), but with no success.

My idea was to define a “Rewrite-Rule” like …
```
/* --> /index.html
```
But then weird things are happening and it does not work.
Shouldn’t that preview as well as error-fallback features work with every static service, as long as urls are rewritten?

**Comment by drewbaker** [comment]
I suspect you only need `target: 'static'` and not the SSR part. That's how we have it on Netlify and it works.

**Comment by JonathanDoelan** [comment]
@drewbaker Thx! The problem is that we want `ssr` to be `true`, because we need to pre-render every page/route. As mentioned it works in my local environment …

**Comment by pi0** [comment]
Hi @JonathanDoelan. Is it possible providing a reproduction? (deployment link might also help for a quick guess what can be wrong)

**Comment by drewbaker** [comment]
> @drewbaker Thx! The problem is that we want `ssr` to be `true`, because we need to pre-render every page/route. As mentioned it works in my local environment …

Yeah we do the same with npm run generate. Just remove the SSR part. Although I suspect it defaults to true so this probably doesn’t matter. 

We have custom error layout working fine with Netlify here if the reference helps: https://github.com/funkhaus/fuxt

**Comment by JonathanDoelan** [comment]
@pi0 Thank you.

I’ve created a repo for a very simple nuxt app [https://github.com/JonathanDoelan/nuxt-static-preview-test](https://github.com/JonathanDoelan/nuxt-static-preview-test)

If you install it locally you should see all 5 pages — screenshots below.

When you install it on a hosting provider like render.com (static sites are for free) (setup should only take a minute or two). And it won’t work there anymore: The last two pages won’t work, because they don’t exist physically. So I guess, we need to set up Rewrite rules, but a rule like `/* => /index.html` will break everything!

Because it works on local environments, I think there should be kind of a guide on how to deploy a `ssr:true; target:'static'` app!

-----

Reference pictures:
![nuxt-test-a](https://user-images.githubusercontent.com/2291224/119999859-7ca29800-bfd2-11eb-94a1-fe4bbbbaaddc.png)
![nuxt-test-b](https://user-images.githubusercontent.com/2291224/119999868-7e6c5b80-bfd2-11eb-8ab6-36cb7f869c80.png)
![nuxt-test-c](https://user-images.githubusercontent.com/2291224/119999874-7f9d8880-bfd2-11eb-8f4f-da756fd25d3f.png)
![nuxt-test-d](https://user-images.githubusercontent.com/2291224/119999879-80ceb580-bfd2-11eb-9dab-39830f633cb6.png)
![nuxt-test-e](https://user-images.githubusercontent.com/2291224/119999882-81674c00-bfd2-11eb-914a-c332029276fb.png)
(Firefox with Chrome skin haha)

**Comment by JonathanDoelan** [comment]
> Hi @JonathanDoelan. Is it possible providing a reproduction? (deployment link might also help for a quick guess what can be wrong). Fallback should go to `/200.html` ([docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-generate#fallback)) not `/index.html` (an already rendered page)

I’ve found a solution. @pi0 You were right — **200.html**.
The mistake was to set the rewrite rule to `/* --> /index.html`.

The correct rewrite rule should be:
```
Source: /*
Destination: /200.html
```

**Comment by NIO-ADR** [comment]
Io$


Sent from the all new AOL app for iOS


On Sunday, May 30, 2021, 7:04 AM, Daniel Roe ***@***.***> wrote:




@JonathanDoelan As mentioned above, you need to create the rewrite rule like /* => /200.html, not to /index.html....

**Comment by JonathanDoelan** [comment]
@pi0 @danielroe Thanks! You are right!

Solution:
```
/* => /200.html
```
In words: all routes should point to `/200.html`. If a path exists on the server this rule must not apply!
