### ISSUE TITLE
How does one add routes from the plugin?

### ISSUE THREAD

**Issue by lavsurgut** [nuxt/nuxt.js#936]
Hello. So, if I want to add some new routes from the plugin using
router.addRoutes. It works, but it does not recognize the route on the first load (say for example I added /login and then load the page mysite.com/login). How do I do this properly if I want to maintain a plugin?

**Comment by Atinux** [comment]
Hi @lavsurgut 

How does look like your plugin which add the route?

**Comment by lavsurgut** [comment]
I need to mention I'm playing with nuxt@1.0.0-alpha.4. So, I have a couple of routes like /login and /register, but I want to keep them in a plugin. Here in ~plugins/plugin.js
```javascript
export default ({ app: {router} }) => {

  Vue.use(MyPlugin, router)
}
```

Then in the plugin, I have: 


```javascript
function install(Vue, router, options = {}) {

  Vue.component('MyComponent',MyComponent)

  router.addRoutes([
    {
      path: '/login',
      name: 'login',
      component: MyComponent
    }
 ])
}
```

**Comment by alexchopin** [comment]
https://github.com/nuxt-community/router-module
