### ISSUE TITLE
global\BaseAlert.vue The `bg-orange-100` class does not exist. If `bg-orange-100` is a custom class, make sure it is defined within a `@layer` directive.

### ISSUE THREAD

**Issue by JackingHuang** [nuxt/nuxt.js#9361]
npm run build in window 10, error with "global\BaseAlert.vue The `bg-orange-100` class does not exist. If `bg-orange-100` is a custom class, make sure it is defined within a `@layer` directive."

**Comment by NIO-ADR** [comment]
Noincoin 




Sent from the all new AOL app for iOS


On Tuesday, June 1, 2021, 4:28 AM, JackingHuang ***@***.***> wrote:




npm run build in window 10, error with "global\BaseAlert.vue The bg-orange-100 class does not exist. If bg-orange-100 is a custom class, make sure it is defined within a @layer directive."

**Comment by JackingHuang** [comment]
I clone the project from https://github.com/nuxt/nuxt.js.git，run command by step：
npm i
npm run build
I guess some libraries are missing in node_modules.

**Comment by JackingHuang** [comment]
Sure enough, the library was missing, and it was fine to retry.
