### ISSUE TITLE
Dynamic Unknown route showing 404 on static deployment. 

### ISSUE THREAD

**Issue by jahidanowar** [nuxt/nuxt.js#9370]
### Versions

- nuxt: v2.6.12
- node: v15

### Reproduction
The page: [https://github.com/jahidanowar/jahid.dev/blob/master/pages/go/_slug.vue](https://github.com/jahidanowar/jahid.dev/blob/master/pages/go/_slug.vue)

The Project: [https://github.com/jahidanowar/jahid.dev](https://github.com/jahidanowar/jahid.dev)

### Steps to reproduce
Goto route `/go/yt` will work but it shows 404 in the browser's network tab

### What is Expected?
The dynamic route is always showing 404 in the browser network tab. 
When I go to /go/:slug it should fall back to SPA and give me a 200 status code something like Vue telescope.
In view telescope when you go to https://vuetelescope.com/explore/:slug it falls back to the spa. I want similar behavior.

### What is actually happening?
It's a URL Shorter project it's hosted on **Netlify** whenever I hit `go/:slug` it throws a 404 response but it does work I mean it does an API call and retrieves data but why does it show 404?

**Comment by danielroe** [comment]
closing in favour of https://github.com/nuxt/nuxt.js/discussions/9371
