### ISSUE TITLE
ie11 has a error

### ISSUE THREAD

**Issue by github1586** [nuxt/nuxt.js#938]
How should filesnames.find (ie11) solve store.js when it is reported wrong?

**Comment by Atinux** [comment]
Hi @github1586 

Please provide steps to reproduce this error, without it, the community cannot help you.

**Comment by github1586** [comment]
I have solved it, thank you

**Comment by caiyuncheng** [comment]
@github1586 How to solve it?

**Comment by Norbz** [comment]
I have the same error under iOS 8. 
@github1586  Can you please provide information on how you solved it ?

**Comment by github1586** [comment]
@caiyuncheng @Norbz  

 build: {
    vendor: ['babel-polyfill'],
    /*
    ** Run ESLINT on save
    */
    extend(config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        });
      }
    },
  },
