### ISSUE TITLE
App is not rendering layout components on server

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#939]
I'm building my app locally and everything is fine. When i'm trying to reach it on server i have empty layout without any rendered components.

This is markup from server:

![zrzut ekranu 2017-06-20 o 16 52 56](https://user-images.githubusercontent.com/1003999/27341075-855a7d82-55dc-11e7-9ef3-25b81b510d41.png)

As you can see there is no other scrips then this tiny one with `__NUXT` notation.

This is default layout:

```
<template>
  <main>
    <app-header></app-header>
    <div class="g-content box-grid-vertical_align_middle">
      <div class="shift-padding_6-vertical box-full_width-grid">
        <div class="column-width_2"></div>
        <div class="column-width_8 shift-padding_6-horizontal">
          <nuxt></nuxt>
        </div>
        <div class="column-width_2"></div>
      </div>
    </div>
  </main>
</template>
```

I'm using latest version of nuxt and `2.5.3` version of vue router.

**Comment by Atinux** [comment]
Hi @lukasborawski 

Could you provide us a repository to help you debug your application?

**Comment by lukasborawski** [comment]
@Atinux sorry but the code/project is confidential, how can i provide more details?

**Comment by Kylart** [comment]
This makes me think of an naming error, may I ask if you can provide the name of the file and the folder your layout file is in ?

**Comment by lukasborawski** [comment]
@Kylart 

layouts
--- default.vue

![zrzut ekranu 2017-06-21 o 15 14 54](https://user-images.githubusercontent.com/1003999/27386286-9b1b30f8-5695-11e7-9b07-286af2ed21a7.png)

**Comment by lukasborawski** [comment]
@Atinux i guess this is a problem with new vue-router version, how to force nuxt to install previous version of dependency? `"vue-router": "2.5.3"`
