### ISSUE TITLE
css-what Denial of Service high vulnerability 

### ISSUE THREAD

**Issue by infinity899** [nuxt/nuxt.js#9404]
### Versions

- nuxt: 2.15.6
- node: 14.17

### Reproduction

Opon npm install we're prompted with High vulnerability of css-what Nuxt dependency. 
npm list | grap shows us that Nuxt 2.15.6 is dependent on  ` ├── css-what@3.4.2 ` and it needs to be upgraded to 5.0.1

### Steps to reproduce
npm install

![image](https://user-images.githubusercontent.com/27764573/121154408-a1f39980-c84f-11eb-81c5-676454479e01.png)

### What is Expected?
no high vulnerabilities 

### What is actually happening?
high vulnerabilities for css-what

**Comment by danielroe** [comment]
I've updated #9284 with details on this.
