### ISSUE TITLE
Where to the pass render function for Vue instance?

### ISSUE THREAD

**Issue by wiinci** [nuxt/nuxt.js#941]
I’m trying to get a static site to generate from a set of markdown docs like https://github.com/ElemeFE. I have included `vue-markdown-loader` as part of my package.

I have set up components in the global scope through a `global.js` plugin. I am not sure where/how to define the render function for the Vue instance so that all Vue components coded inside the Markdown files can be rendered like so:
https://github.com/ElemeFE/element/blob/dev/examples/entry.js#L40

Button example:
https://github.com/ElemeFE/element/blob/dev/examples/docs/en-US/button.md

And site:
http://element.eleme.io/#/en-US/component/button

Thanks!

**Comment by wiinci** [comment]
Forgot to mention, I’m also using Nuxt!

**Comment by wiinci** [comment]
`layouts/default.vue`:

```html
<template>
    <main class="mcds">
        <nav class="mcds_nav">
            <ul>
                <li><nuxt-link to="/">Home</nuxt-link></li>
                <li><nuxt-link to="/button">Button</nuxt-link></li>
            </ul>
        </nav>
            <nuxt />
    </main>
</template>
```

`plugins/global.js`:

```js
import Vue from 'vue';
import ComponentView from '~components/ComponentView.vue';
import Button from '~components/button/Button.vue';
import store from '../store/index.js';

Vue.use(store)

Vue.component('component-view', ComponentView);
Vue.component('mcds-button', Button);
```


`components/ComponentView.vue`

```html
<template>
    <div class="component-view">
        <slot name="component"></slot>
        <div class="meta">
            <div class="description">
                <slot></slot>
            </div>
            <slot name="code"></slot>
        </div>
    </div>
</template>

<script>
export default {
    name: 'component-view'
}
</script>
```

`pages/button.vue`

```html
<template>
<div class="page" :id="page.id">
    <h1 class="title">{{ page.title }}</h1>
</div>
</template>

<script>
import Vue from 'vue'
import Readme from '~components/button/readme.md'

export default {
    computed: {
        page () {
            return this.$store.state.pages.button
        }
    },
}

var vm = new Vue({        // <-- This works but throws a Vue warning
    el: '.mcds',
    render: h => h(Readme)
})
</script>
```

Vue warning: `[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

The hacky fix also replaces the entire page since `.mcds` is my top-level wrapper.

**Comment by uptownhr** [comment]
@wiinci i haven't tried jsx in vue but for the button component, is var vm = new Vue required?
```
var vm = new Vue({        // <-- This works but throws a Vue warning
    el: '.mcds',
    render: h => h(Readme)
})
```
I don't see the purpose in this? Why aren't you able to register the Readme component into the page component and use on the template?

I am not following the example above. Can you show the button/readme code as well?
