### ISSUE TITLE
Nuxt Generate and AWS S3

### ISSUE THREAD

**Issue by royscheeren** [nuxt/nuxt.js#942]
Hi,

I've read in the GitHub issues that it's supposed to be possible to use `npm run generate` to create a static site that runs on GH pages or AWS S3. 

I've done this and uploaded the files to the bucket. All files are being found/loaded properly after I set the router.base in the config, the json file to populate the page is being loaded as well but none of the interactions are going: 

https://s3-eu-west-1.amazonaws.com/thuisverpleging-vlaanderen/index.html  

Is this not supposed to work?

**Comment by mpatino117** [comment]
You are having the same issue that I am having, which is a routing issue look at your URL. Your URL went to index.html. https://s3-eu-west-1.amazonaws.com/thuisverpleging-vlaanderen/index.html for the interactions . You are having same issues no interactivity and CSS breaking

**Comment by mpatino117** [comment]
You are having the same issue that I am having, which is a routing issue look at your URL. Your URL went to index.html. https://s3-eu-west-1.amazonaws.com/thuisverpleging-vlaanderen/index.html for the interactions . You are having same issues no interactivity and CSS breaking.

 This is post about this situation #940
