### ISSUE TITLE
Can I have Nuxt ignore a path?

### ISSUE THREAD

**Issue by ndarilek** [nuxt/nuxt.js#943]
I'm trying to use GraphQL's subscriptions-transport-ws with Nuxt. It appears to return a plain `HTTP.Server`, not Connect middleware, and it's mounted by setting the path attribute when constructing. So IOW I can't use `app.use("/subscriptions", ...)` to mount the server.

I think I'm creating it correctly, but I think `nuxt.render` is intercepting all routes, and since I can't use this server as middleware, I can't insert it into the chain before Nuxt grabs everything.

Is there any way to tell `nuxt.render` to pass through routes at a certain path?

One way I thought to do this was to set up middleware to intercept paths starting with /subscriptions. I then thought that perhaps I could tell Nuxt to stop processing the request altogether and not even return its error page, but I couldn't see a way to do this. Maybe the Connect middleware's `next()` function can be attached to the context on the server? I matched the path, but couldn't halt processing by Nuxt.

**Comment by pi0** [comment]
@ndarilek I think you should better adding nuxt middle-ware as last one. Also in next release (~tomorrow) nuxt will expose connect app instance for `nuxt.render` :)

**Comment by ndarilek** [comment]
The thing I'm trying to add isn't middleware, so I don't think the 
middleware matching rules apply.

**Comment by pi0** [comment]
So would you please explain more about your use case are you using that inside express?

**Comment by ndarilek** [comment]
Here are the docs:

http://dev.apollodata.com/tools/graphql-subscriptions/express.html

Note that `new SubscriptionServer(...)` isn't being mounted like 
middleware, presumably it is consuming the HTTP.Server created from the 
Express app and intercepting everything sent to /subscriptions. Nothing 
I do can get this working with my Nuxt server, so I think I need a way 
to tell Nuxt to ignore /subscriptions even though it is intercepting all 
other routes.

**Comment by alexchopin** [comment]
What template are you using with Nuxt?

**Comment by alexchopin** [comment]
#504

**Comment by ndarilek** [comment]
What does this have to do with this issue?

I'm frustrated that this issue has been closed twice now without 
resolution. If there is no intention of letting me tell the Nuxt 
middleware to ignore a path, then can someone please say so so I can 
rewrite my app to not use Nuxt? Otherwise, please don't close this just 
because I'm using Apollo and Vue-apollo uses Apollo.

Thanks. If I've missed how this issue is resolved by the link then I do 
apologize. This issue has *nothing* to do with making Vue-apollo work, 
which I already have achieved on several projects.

**Comment by ndarilek** [comment]
Thanks for re-opening.

I'd really like to see a fix for this and am willing to try implementing 
it, especially as I don't even know for certain whether it will make the 
Apollo subscription server accessible. I just need a bit of guidance.

There are two ways I can imagine implementing this. One would be this in 
nuxt.config.js:

```
   ignorePaths: [
     "/subscriptions"
   ]
```

This would tell Nuxt's server to ignore the list of paths and simply 
call `next()` as soon as they're matched.

Another option would be middleware like the following:

middleware/apollo-subscriptions.js:
```
export default ({route, next}) => {
     if(route.path.startsWith("/subscriptions"))
     next()
}
```

This would involve modifying contexts to contain the Connect `next()` 
function and expose it to middleware. It may also be necessary to expose 
a function which, when called, tells the Nuxt middleware that processing 
should be stopped. Maybe the original `next()` function can be wrapped 
to do this.

Open to any thoughts on these solutions, or to any others I may have 
missed. If I successfully implement something and it doesn't let me 
connect to a Nuxt-hosted Apollo subscription server then I'll close this 
issue and keep debugging.

**Comment by alexchopin** [comment]
Have you tried to use Nuxt programmatically with the [express-template](https://github.com/nuxt-community/express-template)?
By using Nuxt programmatically, we will be able to create some routes trigger before `nuxt.render` or even better to use `nuxt.renderRoute` in your [routing](https://nuxtjs.org/api/nuxt-render-route) file.

**Comment by dohomi** [comment]
@ndarilek here another approach without vue-apollo: https://gist.github.com/dohomi/e101dea40cb4483b1d6e0dd81f9ce788 please follow the link to the original project by Pier. I used this pure apollo-client approach combined with vuex.. the subscription works already but only on client side yet..

**Comment by ImTheDeveloper** [comment]
@dohomi is there a write up anywhere related to implementing this? I'm new to nuxt and just starting out on using graph.cool. There seems to be so many bits of examples floating around right now, it's becoming impossible to know which one to follow :/

**Comment by dohomi** [comment]
@ImTheDeveloper its basically up to you. If you follow the link check out the project of Pier. Otherwise with the most recent rc3 Nuxt has an example to use it with vue-apollo:
https://github.com/nuxt/nuxt.js/tree/dev/examples/vue-apollo

**Comment by ImTheDeveloper** [comment]
Thanks @dohomi I assume sticking with the official examples might at least provide something common to cling on to.
