### ISSUE TITLE
The following object does not support the "find" property or method

### ISSUE THREAD

**Issue by github1586** [nuxt/nuxt.js#944]
@pi0 
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

// Recursive find files in ~/store
const files = require.context('~/store', true, /^\.\/.*\.(js|ts)$/)
const filenames = files.keys()

// Store
let storeData = {}

// Check if store/index.js exists     

//The following object does not support the "find" property or method  （in IE）
----------------------------------------------------------------------------------------------------------
const indexFilename = filenames.find((filename) => filename.includes('./index.'))
----------------------------------------------------------------------------------------------------------
if (indexFilename) {
  storeData = getModule(indexFilename)
}

**Comment by github1586** [comment]
@pi0

**Comment by ausir0726** [comment]
you need add `babel-polyfill`

and add to `nuxt.config.js` build > vendor

```
....
  build: {
    vendor: ['babel-polyfill'],
    /*
    ** Run ESLINT on save
    */
    extend(config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        });
      }
    },
  },
....
```

**Comment by github1586** [comment]
thank tou very much for the settlement

**Comment by github1586** [comment]
thank you very much for the settlement
