### ISSUE TITLE
Removing trailing slash

### ISSUE THREAD

**Issue by Sendoo** [nuxt/nuxt.js#9442]
### Versions

- nuxt: v2.15.7
- node: v14.17.0 LTS

### Problem
Hi 👋

I have a problem, the trailing slash is simply removed from the url on the first load.
With further routing, the trailing slash is not removed.

Before load page: 
`http://localhost:3000/help/`

After load page:
`http://localhost:3000/help`

Problem appeared after updating to version 2.15.7.
Version 2.15.6 does not have this problem.

I suspect this may be related to this [PR](https://github.com/nuxt/nuxt.js/pull/9431)

**Comment by rahulkumarsingh73690** [comment]
Same error

**Comment by rahulkumarsingh73690** [comment]
Please fix this issue :(

**Comment by pi0** [comment]
Released in [v2.15.8](https://github.com/nuxt/nuxt.js/releases/tag/v2.15.8)
