### ISSUE TITLE
nuxt-link params refresh page params undefined.

### ISSUE THREAD

**Issue by Xiongzhenyu** [nuxt/nuxt.js#945]
/news/index.vue
```
<div>
    Posted in News By
    <nuxt-link :to="{ name: 'news-author-name', params: { name: post.author_name, id: post.author_id } }" append>
        {{ post.author_name }}
    </nuxt-link>
</div>
```

/news/author/_name.vue
```
export default {
    async asyncData ({ req, params }) {
        return axios.get(`${process.env.API_URL}/api/tags/${params.id}/posts`)
            .then((res) => {
                return { posts: res.data }
            })
    }
}
```
browser url is : domain/news/author/admin
first time run is ok, when i refresh page show Nuxt.js Error: 500. because params undefined.

How should I fix it?

**Comment by BenoitRanque** [comment]
Check if params are set before making the request
Also you might want to use query instead of params

**Comment by Xiongzhenyu** [comment]
I know query is solution ，
but for url beautiful , query is not the best solution

**Comment by BenoitRanque** [comment]
If you want the param to stay the same upon page reload, you need state. Use vuex.

**Comment by alexchopin** [comment]
Hi @Xiongzhenyu,
It seems that your route doesn't have an id params.
This file `/news/author/_name.vue` is transformed by Nuxt into `/news/author/:name`.
There is no `params.id` available.
