### ISSUE TITLE
ServerMiddleware hot reload is faulty

### ISSUE THREAD

**Issue by AregGhazaryan** [nuxt/nuxt.js#9456]
### Versions

- nuxt: 2.15.3
- node: 14.16.0

### Reproduction
https://github.com/AregGhazaryan/nuxt-mongoose-server-middleware-reprod

### Steps to reproduce
1. npm i
2. npm run dev
3. go to /api/index.js and hit save
4. voila error

### What is Expected?
Server middleware should reload with latest changes without throwing errors.

### What is actually happening?
The entire server middleware re-instantiates including, classes, functions and other resources. I can assure you that issue is not only mongoose related, because once i even had a telegram bot connected to my application which threw similar errors, like two instances are being run instead of just one.

**Comment by AregGhazaryan** [comment]
Here's also the telegram bot error when saving server middleware

![image](https://user-images.githubusercontent.com/38076644/122646003-3b635b00-d12e-11eb-98d2-d28f251fd5d9.png)

**Comment by AregGhazaryan** [comment]
No, bad bot

**Comment by Susccy** [comment]
I have the same problem currently and it makes developing a Mongoose backend very unpleasant. I have to manually exit and restart Nuxt everytime I make a change in any server file.
Neither the supposed fix in release [v2.14.4](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.4) nor the workaround using `require()` suggested by @pi0 in #7917 solved it for me.

**Comment by TomBell95** [comment]
Hi, I am now experiencing the same problem as mentioned by @Susccy & @AregGhazaryan - I have tried the workaround in #7917 which has not worked as well as upgrading to Nuxt 2.15.8.

@Susccy Did you manage to fix this? I am also having to manually refresh my Mongoose backend everytime.

Is there any update on this please? Thanks.

**Comment by Susccy** [comment]
@TomBell95 The following workaround makes hot reloading possible in my current mongoose project. Keep in mind you'll have to restart the app every time you make changes to the model.

```js
// movie.model.js

import { Schema, models, model } from "mongoose"

const movieSchema = new Schema({
  // ...
})

// Try to use the existing model if it's been created before.
// Used to suppress a mongoose error on nuxt hot reload.
export default models.Movie || model("Movie", movieSchema)
```

**Comment by TomBell95** [comment]
@Susccy Brilliants, thanks.
