### ISSUE TITLE
SSR asyncData issue: rendering on client instead of server

### ISSUE THREAD

**Issue by RomeroGaliza** [nuxt/nuxt.js#9474]
### Versions

- nuxt: 2.15.3
- node: v14.15.4
- nuxt/http: 0.6.4

### Reproduction

I have a "frontend" application (Nuxt) running on http://localhost:80 that needs to render all requests towards an internal "backend" rest api (running on http://localhost:8080). 

In order to do so, I am trying to take advantage of SSR, since the backend is internal and cannot be exposed.
To do so, I used `asyncData`, following exactly what the documentation suggests: https://nuxtjs.org/docs/2.x/features/data-fetching/#async-data

Below is an oversimplified example of what I have setup so far:

**pages/index.vue**
```
<template>
  <span>{{ module }}</span>
</template>

<script>
export default {
  name: 'Module',
  async asyncData ({ params, $http }) {
    const module = await $http.$get('http://localhost:8080/modules/' + params.module)
    return { currentModule }
  }
}
</script>
```

**nuxt.config.js**
```
export default {
  head: {
    title: 'my-app',
  },
  ssr: true,
  target: 'server',
  modules: [
    '@nuxtjs/axios',
    '@nuxt/http'
  ]
}
```

### What is Expected? What is actually happening?

I would expect that once built (`npm run build` + `npm run start`) all requests from `asyncData` would be rendered on the server side on that particular page, however, when inspecting the browser's network traffic, I see the initial calls being made to http://localhost:8080 (suggesting client side rendering, which seems unexpected considering the documentation), only when I "refresh" the page in the browser the request seems to be rendered on the server (goes to http://localhost). 

Since I followed the documentation I'm opening this as a bug. But I'm glad to take suggestions on how to improve this scenario.

**Comment by RomeroGaliza** [comment]
@danielroe Thanks for your reply, that could have indeed be the case, however I have changed my **nuxt.config.js** to:

```
export default {
  head: {
    title: 'my-app',
  },
  ssr: true,
  target: 'static',
  modules: [
    '@nuxtjs/axios',
    '@nuxt/http'
  ]
}
```

and I still end up with the exact same behaviour, all requests inside `asyncData` as sent on the client side, as an additional request to my backend, which is a bit puzzling.

**Comment by danielroe** [comment]
@RomeroGaliza Could you provide a reproduction? Can I confirm you're generating your site first rather than just running in dev mode?

**Comment by RomeroGaliza** [comment]
@danielroe yes, I'm generating (`npm run generate` + `npm run start`), yet I see no change in behaviour :(

Here is the exact same source code: https://github.com/RomeroGaliza/issues-9474

I'm wondering if navigation plays a role in this?

**Comment by RomeroGaliza** [comment]
So I have replaced all that with something like: 
```
<nuxt-link :to="{ name: 'modules', params: { module: name } }" >
```
and I still don't get the `asyncData` calls to be placed on the server side. Maybe I should mention that by querying a backend I expect data I'm query to be very dynamic, I can't imagine setting `target: 'static'` being a valid approach, this is the reason I came to Next.js, so I could progress these requests on the server side returning only the rendered view.

**Comment by mauro-rocha** [comment]
Same problem here
