### ISSUE TITLE
Nuxt is deployed in the Intranet environment. When using the Internet springboard to access, the page loads 404. How can I solve this problem

### ISSUE THREAD

**Issue by AbyssWang** [nuxt/nuxt.js#9478]
### Discussed in https://github.com/nuxt/nuxt.js/discussions/9477

<div type='discussions-op-text'>

<sup>Originally posted by **AbyssWang** June 24, 2021</sup>
Background:

According to the requirements of Party A, nuxt needs to be deployed in the Intranet environment, and can not directly communicate with the Internet. External network access needs to be forwarded through an Internet connection to the intranet

Current status:

1. Two servers, one Internet server and one intranet server have been configured for Unicom through nginx forwarding

2. Two HTTPS domain names, one for the browser to access the front-end page, the other for the front-end access interface address

3. The intranet server deploys the spring boot back-end service, which is used to interact with the front-end, obtain the database data and return it to the front-end

4. The host is set in the intranet server to map the domain name to the intranet IP to access the local interface. The domain name interface can be debugged through curl

Problem Description:

1. In the case of using the domain name access interface, you can access through using the HTTPS + domain name access platform, but you will report 404 error when loading the page

Console output error message:

GET https:/xxxx.xxx.com/ 404 (OK)

Uncaught SyntaxError: Unexpected token '<'

Network reported an Error 404 when accessing the first domain name, but the subsequent JS, PNG and other resources loaded normally

2. Configure the domain name access interface, use HTTP + intranet server IP access to access the Internet, but call the interface to report CORS cross domain error

3. Modify the configuration, use the local IP direct access interface, and use the HTTPS + domain name access platform to access Tong. However, as in problem 1, 404 error will be reported when loading the page

4. Modify the configuration, use the local IP direct access interface, use HTTP + intranet server IP access, everything is normal!

The biggest problem at present:

Why can I open a page by using the domain name access interface, but I report 404 error when loading. What is the reason for this error? How to solve it?

The project will go online at the end of June, and now it's not a few days. I sincerely ask all the gods to help me come up with ideas. I've searched all the relevant content on the Internet, and I haven't encountered any similar cases. I hope there is a God who can solve this problem here!

情况背景：
应甲方需求，nuxt需要部署在内网环境，不能直接与互联网互通，外网访问需要通过一台互联网连接内网进行转发
目前状况：
1.两台服务器，一台互联网服务器，一台内网服务器，均已经通过Nginx转发配置联通
2.两个https域名，一个用于浏览器访问前端页面，另一个用于前端访问接口地址
3.内网服务器部署spring boot后端服务，用于与前端交互，获取数据库数据返回给前端
4.内网服务器设置了host，将域名映射到内网ip访问本机接口，通过curl调试域名接口，可以调通
问题描述：
1.配置使用域名访问接口的情况下，使用https+域名访问平台可以访问通，但是会在加载页面的时候报404错误
控制台输出报错信息：
GET https:/xxxx.xxx.com/ 404 (OK)
Uncaught SyntaxError: Unexpected token '<'
Network在第一个域名访问的时候报错404，但是后续js、png等资源加载正常
2.配置使用域名访问接口，使用http+内网服务器ip访问可以访问通，但是调用接口时报cors跨域错误
3.修改配置使用本机ip直接访问接口，使用https+域名访问平台可以访问通，但是同问题1一样，会在加载页面的时候报404错误
4.修改配置使用本机ip直接访问接口，使用http+内网服务器ip访问一切正常！

目前最大的问题：
使用域名访问接口，为何会可以打开页面，但是加载的时候报404错误，这个错误产生的原因是什么？如何解决？

项目6月底要上线，现在没几天了，恳请各路大神帮我出出主意，我找遍了网上所有相关的内容，没有遇到和我类似的案例，希望在这里有能解决这个难题的大神！</div>

**Comment by TimSusa** [comment]
Is this a Problem, which nuxt is supposed to take care about? Sounds like infrastructural problem to me.

**Comment by AbyssWang** [comment]
> Is this a Problem, which nuxt is supposed to take care about? Sounds like infrastructural problem to me.

Because I am not familiar with nuxt, I received the task of deploying the nuxt project, and because of the requirements of the customer for the deployment environment, I encountered the above problems, which could not be solved by many attempts, so I would like to ask

The main thing I want to know is whether multiple forwarding through nginx will affect the deployment of nuxt and cause access exceptions

**Comment by danielroe** [comment]
I'm closing this in favour of [the GitHub discussion](https://github.com/nuxt/nuxt.js/discussions/9477) as it's not a Nuxt bug or feature request.
