### ISSUE TITLE
`nuxt generate` with v-on:click

### ISSUE THREAD

**Issue by Alexpintu** [nuxt/nuxt.js#948]
I was generating a simple project from nuxjs website. It works fine but when i added a button with v-on:click event.,in the generated one, the button doesn't work. It works with npm run dev.
Please help me out. Thanks
Below is my index.vue

```
<template>
  <section class="container">
    <div>
      <logo/>
      <h1 class="title">
        NUXT
      </h1>
      <h2 class="subtitle">
        Universal Vue.js Application
      </h2>
      <div class="links">
        <a href="https://nuxtjs.org/" target="_blank" class="button--green">Documentation</a>
        <a href="https://github.com/nuxt/nuxt.js" target="_blank" class="button--grey">Github</a>
      </div>
      <button @click="test('1231')"> testButton </button>
    </div>
  </section>
</template>

<script>
import Logo from '~components/Logo.vue'

export default {
  components: {
    Logo
  },
  methods: {
    test: function (val) {
      console.log(val)
    }
  }
}
```

**Comment by mpatino117** [comment]
Can you please provide your nuxt.config set up to see your routing setup? also, could you paste your URL that you get on that page when you run it as a static project ?

**Comment by Alexpintu** [comment]
Thanks for your reply. Actually it's a simple project from nuxt website. You can find it here:
https://nuxtjs.org/guide/installation/
I added a button to check v-on:click event. It always works with npm run dev but when generating to static web app, the event doesn't. 
Below is my nuxt config 
```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'starter',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', content: "Nuxt.js project" }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: 'favicon.ico' }
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#3B8070' },
  build: {
    /*
    ** Run ESLINT on save
    */
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}

```

**Comment by mpatino117** [comment]
Try this out and add router section to your config. I am having trouble to with static generator project as it breaks when I refresh.



```
    router: {
        extendRoutes(routes, resolve) {
            routes.push({
                    name: 'index',
                    path: '/',
                    component: resolve(__dirname, 'pages/index.vue')
                })
                // torch.white(routes)
        }
    },
```

**Comment by Alexpintu** [comment]
The problem is that the event listener stop working. 
When I click this button 
`  <button @click="test('1231')"> testButton </button>`

it's supposed to print out 1231 in console. 
```
  methods: {
    test: function (val) {
      console.log(val)
    }
  }
```

**Comment by mpatino117** [comment]
I think your problem is your routing as your files are not being imported so your button does not work as it is not connecting with the method. Watch the network tab, and check the box that preserves the history between page loads... look for 302's from the server if you don't see any, maybe something is funny with your router setup?

**Comment by phuocnt0612** [comment]
I have the same issue  when i combine nuxt static files with Laravel. I have checked the network and source tab, and found out that the specific javascript file `0.nuxt.bundle.791a78988e6f96c20239.js` for that page does not downloaded while the other js file such as: `vendor.bundle.2674222896dda8bf2dd4.js`, `1.nuxt.bundle.70d54a85ce6b1584c5cc.js` . I dont know why?

**Comment by phuocnt0612** [comment]
I have find out why. Because the route handle by server and the route of nuxt is not match. Since I fix them to match together, it works fine.
More detail: 
- I try to access to `mysite.dev/test-nuxt` then the server will handle to return the index.html file in dist folder. This way will lead to the javascript file for this page will not being downloaded. I still don't know why.
- Then, I change my route to `mysite.dev` will return the index.html file. Weird, it works

**Comment by didiself** [comment]
@Alexpintu  @alexchopin 
Is it solved?? I got the same problem .
I'm sure all js files are 200.

**@click** work with 'npm run dev',
doesn't work with 'npm run generate', no any error.

**Comment by didiself** [comment]
LOL, I did some interesting test.

Clone nuxtjs.org.
change layouts/default.vue
```
<template>
  <div>
    <navbar></navbar>
      <nuxt/>
  </div>
</template>

<script>
import Navbar from '~components/HeaderNavMenuDropdown.vue'

export default {
  components: {
    Navbar
  }
}
</script>
```
add pages/test.vue
```
<template>
  <div class="test">
    <button @click="show = !show" :class="{'Dropdown__Title--mobile': show}">123</button>
    <nuxt-header-nav-menu-dropdown/>
  </div>
</template>

<script>
import NuxtHeaderNavMenuDropdown from '~components/HeaderNavMenuDropdown.vue'

export default {
  components: {
    NuxtHeaderNavMenuDropdown
  },
  data() {
    return {
      show: false
    }
  }
}
</script>

<style>
.test {
  margin-top: 100px;
}
</style>
```

npm run generate

![image](https://user-images.githubusercontent.com/14201030/28513308-2f528abc-7088-11e7-8354-4062e599a782.png)

just click the first 'Ecosystem' can change class content.

It's look like just binding function by layouts.

**Comment by Alexpintu** [comment]
@didiself : no, it's not solved 
According to this https://github.com/nuxt/nuxt.js/issues/959
This issue cannot be solved :(. we should wait for the newer version.

**Comment by didiself** [comment]
@Alexpintu  OMG....

**Comment by sarikatandale** [comment]
Any solutions for this problem  ?

**Comment by cdoneshot** [comment]
i have the same problem.and i find out why.

i use use **extendRoutes** custom the router config and then the click method not work.
it works when i remove custom router config.

**Comment by Jonarod** [comment]
Just FYI this is how I managed to solve this issue:

in `nuxt.config.js`, I had to set both `generate.subFolders` and `router.base`  : 
```
module.exports = {
  generate: {
    subFolders: true
  },
  router: {
    base: '/'
  } 
}
```

For whatever reason, without this exact setup all `v-on:click` properties could not work except when on homepage '/'.
