### ISSUE TITLE
What is the reason for this_ Resource file missing in _nuxt dir?  请问什么原因会导致发布后_nuxt下资源文件丢失？

### ISSUE THREAD

**Issue by AbyssWang** [nuxt/nuxt.js#9489]
### Discussed in https://github.com/nuxt/nuxt.js/discussions/9488

<div type='discussions-op-text'>

<sup>Originally posted by **AbyssWang** June 27, 2021</sup>
It's like this:

At present, I have two servers, one can directly connect to the Internet, the other intranet server can not directly connect to the Internet, so I need to forward through the Internet server for Internet connection access.

My project is deployed on the Internet server and can be accessed normally by using the domain name. When my project is deployed on the intranet server, the access is abnormal. I use the chrome developer panel to view the sources of the two and find that the_ All the resource folders in the “_nuxt" directory are lost, without fonts and img folder

---------------------------------------------------------------------------------------------------------------

情况是这样子的：
目前我有两台服务器，一台可以直接连接互联网，另一台内网服务器无法直接连接互联网，需要通过互联网服务器转发来进行互联网连接访问。
我的项目部署在互联网服务器上，使用域名可以正常访问，而当我的项目部署在内网服务器上的时候，访问异常，我使用Chrome开发者面板查看二者的Sources，发现内网服务器的"_nuxt"目录下的资源文件夹全部丢失，没有fonts，没有img，请问这个可能是什么原因造成的？
</div>

**Comment by danielroe** [comment]
Closing in favour of [the discussion](https://github.com/nuxt/nuxt.js/discussions/9488).
