### ISSUE TITLE
express midleware on v1.0.0-alpha.4

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#949]
Hello i use middleware express before nuxt

```
const Nuxt = require('nuxt')
const express = require('express')
const app = express()
const nuxt = new Nuxt(config)
let config = require('./nuxt.config.js')
config.dev = false;

app.use(function (req, res, next) {
        nuxt.renderRoute(req.url)
        .then(data => res.end(data.html ? data.html : 'empty render'))
        .catch(error => res.end('This page error render!!!!!'))
    });
```

I have result 

`This page error render!!!!!`

for every page (((

how i can fix it ?

Thanks

**Comment by awronski** [comment]
I user express midleware with alpha4 and it is working ok.

The help you please tell us what is the error exactly.
Change code like this:
```
[...]
.catch(error => res.end(error))
[...]
```

**Comment by awronski** [comment]
I user express middleware with alpha4 and it is working ok.

The help you please tell us what is the error exactly.
Change code like this:
```
[...]
.catch(error => res.end(error))
[...]
```

**Comment by riteable** [comment]
Similar issue here. Just updated from alpha 2 to alpha 4 and it broke the middleware usage in Express.

```
const nuxt = new Nuxt(nuxtConfig)
app.use(nuxt.render)
```
Error:
`TypeError: app.use() requires middleware functions`

**Comment by uptownhr** [comment]
@wargt did you install using yarn? Make sure alpha4 of nuxt is being used.

**Comment by alexchopin** [comment]
Should be related to express-template.
I'm closing the issue but feel free to reply if the bug still exist.
