### ISSUE TITLE
Injected plugin is not defined on the client when called from a store module

### ISSUE THREAD

**Issue by proup24** [nuxt/nuxt.js#9491]
### Versions

- nuxt: 2.15.3
- node: 14.7.0

### Reproduction
I have a Nuxt app that makes requests to an Express API.
I use Nuxt middlwares to fetch data from the server, with the help of a plugin function I injected in Nuxt context.

```js
// plugins/apiService.js
export default function ({ $axios }, inject) {
  const fetchAddress = async ({ targetCountryIso, targetCityName }) => {
    const res = await $axios.$get(`/api/address/generate/${targetCountryIso}/${targetCityName}`)
    if (!res.success) throw new Error(res.error)
    return res.data
  }
  inject('apiService', { fetchAddress })
}
```

`apiService` injects api helper functions, `fetchAddress` gets called from a store module. This plugin should be defined on both the server and the client.

```js
// store/address.js
const actions = {
  async GET_ADDRESS({ commit, dispatch }, region) {
    try {
      const address = await this.$apiService.fetchAddress(region)
      commit('SET_ADDRESS', address)
    } catch (error) {
      dispatch('error/HANDLE_ERROR', error, { root: true })
    }
  }
}
```
`GET_ADDRESS` action gets dispatched by `/address` route middleware as shown below.

```js
// middleware/getAddress.js
export default async function ({ store, params }) {
  const targetCountryIso = params.countryIso?.toLowerCase()
  const targetCityName = params.cityName?.toLowerCase()
  await store.dispatch('address/GET_ADDRESS', { targetCountryIso, targetCityName })
}
```

### Nuxt Configuration
In my nuxt.config.js SSR is on with static target and the plugin is properly registered .

```js
export default {
  // ...
  ssr: true,
  plugins: ['~/plugins/apiService.js'],
  target: 'static'
}
```

### What is Expected?
`apiService` plugin to be defined on both client and server side.

### What is actually happening?
Now, when the route is called directly all works fine but when its navigated I get an error `_this.$apiService is not a function`. That's the case because middlewares are called from the client side when navigation the page. In other words, the injected plugin is only available on the server.

### Note
It's important to notice that the plugin is called from a store module not directly from `store/index.js`, otherwise everything would've worked as expected.

**Comment by razukc** [comment]
How did you solve this issue? I'm having exact same issue. Looked for several ways but nothing solved it.
