### ISSUE TITLE
App (global) non-page-related component?

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#95]
Is there any way to wrap an entire nuxt.js application/site with a "non-page" related component, being a perfect place to add global components, like navbar, sidebar, etc..., and to do global "on-every-page-load" logic like user auth, etc...?

Hopefully my question makes sense.

Thanks!

**Comment by Atinux** [comment]
I think the middlewares (next release) and the layout are the answer for you :)

Happy new year BTW 🎉

**Comment by jaredreich** [comment]
Right on!

Happy new year to you as well!

**Comment by jaredreich** [comment]
Wow, the layout logic works very well so far. Nice work!

**Comment by Itagiba** [comment]
Any updates on this? I am trying to add more cosmic items to my app i.e. posts, nav, footer etc. but can't find a way to interpolate the code with vue.js and nuxt i.e.

```
    {{# cosmic.object.nav-items.metafields }}
      <li>
        <nuxt-link v-bind:href="value " exact>{{ title }}</nuxt-link>
      </li>
    {{#/ cosmic.object.nav-items.metafields }}

```
(error)

Thanks!

**Comment by Atinux** [comment]
I will start to work on the middleware pretty soon.

You can already use the [nuxtServerInit action](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action) with the store to fill global data related to the nav-bar/footer for example.

**Comment by Atinux** [comment]
The middleware feature is out with the [0.9.8 release](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.8) 🍾
