### ISSUE TITLE
Occurs in the IE browser: objects do not support the find property or method

### ISSUE THREAD

**Issue by caiyuncheng** [nuxt/nuxt.js#951]
![0](https://user-images.githubusercontent.com/28284861/27417339-3145c47a-5746-11e7-858e-4e2f3ede408b.png)

### Error method replication

Parent component：a.vue 

Subcomponents：ab.vue

ab.vue

>this.$emit('increment')  

a.vue

><ab @increment='incrementTotal'></ab>  
>methods: {  
    &ensp;&ensp;incrementTotal: function () {  
      &ensp;&ensp;this.total += 1  
    }  
  >}

**Comment by halas** [comment]
I guess you are not using vuex? I have similar issue, but I don't use $emit only vuex to handle state, and from some initial research have hypothesis that this is vome .find method in vuex used (while it it is not supported in any IE - see browser compatibility here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find

But hadn't fund direct culprit yet.

**Comment by halas** [comment]
Ok, @akmur suggested working solution.
You need to add polyfill for the array methods. It can be done via script tag (that is the solution I tested now and works for me), but it should be also possible as a plugin via webpack.
Just add 
```
module.exports = {
  head: {
        script: [
          { src: 'https://cdn.polyfill.io/v2/polyfill.min.jsfeatures=default,Array.prototype.find,Array.prototype.findIndex' }
         ],
  }
}
```
to your `nuxt.config.js`

After I fixed this issue, I encountered Explorer errors about some other array methods, so I will probably go for some general polyfill, but maybe this solution will be enough for you.

**Comment by halas** [comment]
Ok, just tried clean starter app, then run `npm run generate` (just adding custom router base in `nuxt.config.js`) and in IE 12 and below there is this error in console:
`Object doesn't support property or method 'find'`
Tested in BrowserStack
See yourself at: [http://hadora.xyz/test-nuxt/](http://hadora.xyz/test-nuxt/ )
