### ISSUE TITLE
How to use bootstrap with nuxt.js.

### ISSUE THREAD

**Issue by binler** [nuxt/nuxt.js#953]
Hi, I wan't use bootstrap or bootstrap-vue.
https://bootstrap-vue.github.io
Please tell me.!!!!!! #

**Comment by pi0** [comment]
Hi! It's already ready. See https://github.com/nuxt-community/modules/tree/master/modules/bootstrap-vue (requires nuxt 1.x)

**Comment by binler** [comment]
I use adonuxt (https://github.com/nuxt-community/adonuxt-template)
I try https://github.com/nuxt-community/modules/tree/master/modules/bootstrap-vue but not working

**Comment by Tabrizian** [comment]
I have published a blog post about it see here 
https://imantabrizian.me/blog/using-nuxt-modules/ @binler
