### ISSUE TITLE
Non vue.js javascript in .vue templates (for a client side)

### ISSUE THREAD

**Issue by Winns** [nuxt/nuxt.js#954]
Hello, first of all thanks for such a promising framework.
I'm just started to learn nuxt.js and want to know how flexible it is for a non vue.js javascript.

---
Here is a tasks that I'm trying to solve right now. I know there was already a few question about this, but I'm still does not found an answer.
## I want to know how to use non vue.js javascript in ```.vue``` templates (for a client side).

For example

```html
/pages/contacts.vue

<template>
    <!-- html -->
</template>

<script>
    /*
    For a client side(browser) of that page i want to include next js files:

    some external files:

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

    and a few local files:

    - assets/js/a.js 
    - assets/js/b.js 
    - assets/js/c.js

    better as a bundle (make a single js file)
    also i want to leave a config for this scripts

    window.pageContacts = {
        // some data
    };

    and i need some callback or global event when all .vue templates are mounted, 
    like jquery ready, i need to know when it is safe to use generated markup.
    */
</script>
```

---
Currently i have this solution in my mind, but maybe there is better way to solve this trivial task?
```html
/pages/contacts.vue

<template>
    <!-- html -->
</template>

<script>
export default {
    head: {
        // Include external js files
        script: [
            { type: 'text/javascript', src: '//maps.googleapis.com/maps/api/js?v=3.exp' },
        ]
    },
    mounted: function() {

        if (process.BROWSER_BUILD) {

            // Leave a config
            window.pageContacts = {
                // some data
            };

            // Include local js files, not a bundle but better than nothing =(
            some_helper_that_will_add_script_files_to_document(
                ['assets/js/a.js', 'assets/js/b.js' 'assets/js/c.js']
            );

            /* 
                Still dont know how to trigger event when ALL .vue templates are ready to use
                maybe @ /layouts/default.vue at mounted event ?
            */
        }

    }
}
</script>
```

p.s. Sorry for a possible mistakes in english language.

**Comment by racksen** [comment]
Have you given a thought about using "plugin" feature? You can load required third party or custom js files as a plugin and configure it in nuxt.config as a plugin. https://nuxtjs.org/api/configuration-plugins

**Comment by Winns** [comment]
Thanks for reply **racksen**, but i dont think plugins will solve this task. As i understand they are for global things, plugin will be included at every page. What if i want to limit this to just few pages, or to certain users (available only to admins or registered users).

**Comment by ausir0726** [comment]
@Winns 

maybe you can try `import() function`

something like
```
mounted: function () {
  const a = await import('assets/js/a.js')
  a.whatever()
}
```

**Comment by cesasol** [comment]
simply by importing the file as a module inside de script tag does de work, only load the script inside that component/page:

```
<script>
import customscript from '~custom/customscript'
```

**Comment by binggg** [comment]
@ausir0726 

How to using webpack to import a external cdn script?

**Comment by budden** [comment]
I am sorry, where is "head" described? I'm unable to find anything but https://github.com/ktquez/vue-head

**Comment by awronski** [comment]
@budden https://nuxtjs.org/api/configuration-head/
