### ISSUE TITLE
Why the layout function is executed before the named middleware?

### ISSUE THREAD

**Issue by lautiamkok** [nuxt/nuxt.js#9541]
### Versions

- nuxt: 2.15.7
- node: v12.14.0

### Reproduction

The `layout` property function is called before the middleware and is called twice

### Steps to reproduce

1. Create a middleware:

    ```
    // middleware/layout.js
    export default async (context) => {
      console.log('layout middleware')
    }
    ```

2. Create an "About" page:

    ```
    // pages/about.vue
    export default {
      middleware: ['layout'],
      layout (context) {
        console.log('layout function')
      }
    }
    ```

### What is Expected?

```
layout middleware
layout function
```

The middleware should be executed first before the `layout` function and this `layout` function should be called once only.

### What is actually happening?

The layout function is called before the middleware and is called **twice** when the app runs like a SPA:

   
    layout function
    layout middleware
    layout function
    

The layout function is called before the middleware and is called once when refreshing the browser:

    
    ** Nuxt SSR**
    layout function
    layout middleware
    

Then it is called again on the client side:

    
    layout function
    

Is this intended? What is the logic to call it twice and calling it before the middleware? It seems counterintuitive as we know that middleware should be called first before any following logic.

Or is it a bug? The `layout` function should just be called once logically.

**Comment by lustremedia** [comment]
_layout is a type 2 middleware_ as can be seen in the lifecycle here: https://nuxtjs.org/docs/2.x/concepts/nuxt-lifecycle

So what is happening?  I assume: Layout middleware is being called before page middleware, which is correct.

**Comment by Romainpetit** [comment]
Agreed with @lustremedia:

`nuxt.config.js`
```js
  router: {
    middleware: 'layout'
  }
 ```

`pages/about.vue`
```js
export default {
  layout (context) {
    console.log('layout function')
  }
}
```

`console`
```bash 
layout middleware
layout function
 ```
