### ISSUE TITLE
Nuxt not generating static content on yarn generate

### ISSUE THREAD

**Issue by ltroya-as** [nuxt/nuxt.js#9547]
### Versions

- nuxt: 2.15.3
- node: 14.16.1

### Reproduction
https://github.com/ltroya-as/nuxt-ssg

<details open>
<summary>Details</summary>
<br>
Nuxt is not generating SSG when I run `yarn generate`. I expect to see static content on the generated files. (`dist/index` or `dist/users/index`)
</details>

### Steps to reproduce
- Clone the repository: `https://github.com/ltroya-as/nuxt-ssg`
- Run `yarn generate`
- Inspect the `dist/index` or `dist/users/index` to check that there is not static content

### What is Expected?
Static content on the files with the HTTP response

### What is actually happening?
A file that is using javascript to work even if the target is `static`

Routes:
`/`: HTTP request using `nuxt-apollo`
`/users`: HTTP request using `fetch` and `axios`
`/users2`: HTTP request using `asyncData` and `axios`

I haven't found any documentation related to this, is there something I am missing, or am I looking at the wrong place? 

Thanks in advance

**Comment by manniL** [comment]
Hey 👋🏻

I've followed the steps.
I see static content in the files, as well as no HTTP request to APIs, only to payload files.

![Screenshot 2021-07-12 at 21 34 44](https://user-images.githubusercontent.com/640208/125345651-1773ed80-e359-11eb-8e67-5c2133c1d397.png)

![image](https://user-images.githubusercontent.com/640208/125345681-2064bf00-e359-11eb-9e97-f7a7e23934bb.png)

**Comment by ltroya-as** [comment]
Hey @manniL, thanks for the quick response.

Is that ok to have the response in a js file instead of the HTML? I was hoping to get something like this: https://gist.github.com/ltroya-as/a933f35017696d891b1aa9a4eced5826

As you can see, there is an `h1` and `p` related to the response:
https://github.com/ltroya-as/nuxt-ssg/blob/7c3ad0b640f792f01380bf707202ad84e130999a/pages/job.vue#L3-L4

Looks like the output of the generated files is different depending on the `fetch` response. The `/` route returns an array while the `/job` returns an object.

Is this the expected behavior?

**Comment by manniL** [comment]
> Is that ok to have the response in a js file instead of the HTML?

The result of `fetch` or `asyncData` are saved in the `payload.js`. This is intended. See e.g. [this article](https://nuxtjs.org/blog/going-full-static).

> I was hoping to get something like this: [gist.github.com/ltroya-as/a933f35017696d891b1aa9a4eced5826](https://gist.github.com/ltroya-as/a933f35017696d891b1aa9a4eced5826)
> As you can see, there is an `h1` and `p` related to the response:
> [ltroya-as/nuxt-ssg@`7c3ad0b`/pages/job.vue#L3-L4](https://github.com/ltroya-as/nuxt-ssg/blob/7c3ad0b640f792f01380bf707202ad84e130999a/pages/job.vue#L3-L4)

Right now the component is being rendered as intended. Both, the title and the slug are rendered in the HTML correctly.

<details>
<summary>Output of the HTML file</summary>
WILL EDIT IN HERE IN A SECOND


</details>

> Looks like the output of the generated files is different depending on the `fetch` response. The `/` uses an array on its template while the `/job` uses an object.
> 
> Is this the expected behavior?

I'm not sure if I get your question. What will be rendered in the HTML entirely depends on the **template of your page components**. If you add a list of jobs there, they'll be rendered. If you add just a title and a slug, only these things will be visible

**Comment by ltroya-as** [comment]
Hey @manniL, This is my last question:

Does that behavior of using `payload.js` affect the SEO of the page? I have been researching about this but I am not 100% sure

**Comment by manniL** [comment]
> Hey @manniL, This is my last question:
> 
> Does that behavior of using `payload.js` affect the SEO of the page? I have been researching about this but I am not 100% sure

As the content isn't used for SSR no (besides it'll be still requested by Google by default, so that's the only point that could impact crawl budget for example)

**Comment by kovan** [comment]
Is there a way to do this?. I am also surprised that "nuxt generate" is not fully prerendering the pages, and delegates some rendering to the browser (I am referring to the payload.js files and all that mechanism).
