### ISSUE TITLE
Assets path resolution not working for tags different than <img>

### ISSUE THREAD

**Issue by ErickPetru** [nuxt/nuxt.js#956]
I created a new Nuxt project and put files named `campus.jpg` and `campus.mp4` inside the assets folder.
Then in my `index.vue` I just wrote:

```
<template>
  <div>
    <video autoplay muted loop poster="~assets/campus.jpg">
      <source src="~assets/campus.webm" type="video/webm">
      <source src="~assets/campus.mp4" type="video/mp4">
    </video>
  </div>
</template>
```

The generated code stays with the same path (i.e. `http://localhost:3000/~assets/campus.jpg`), so just 404 happens. The same path with `<img src="~assets/campus.jpg">` works as expected.

**Comment by alexchopin** [comment]
Hi, you need to extend the [webpack config](https://nuxtjs.org/faq/extend-webpack) to add these extensions to url-loader.

**Comment by ErickPetru** [comment]
@alexchopin, I don't believe the problem is just about the different file types, since the attribute `poster="~assets/campus.jpg"` stays this way in the `<video>` tag but works as expected with the `<img>` tag.

**Comment by pi0** [comment]
Hi. We need to extend vue-loader's [transform-require](https://github.com/vuejs/vue-loader/blob/master/lib/template-compiler/modules/transform-require.js) to support `video:poster` attrs. Here is a working nuxt.config:

```js
module.exports = {
  
  build: {
    extend(config, {isServer}) {
      const vueLoader = config.module.rules.find(r => r.loader === 'vue-loader')
      vueLoader.query.transformToRequire = {
        video: 'poster'
      }
    }
  }
  
}
```

**Comment by ubershmekel** [comment]
For some reason the solution proposed by @pi0 did not work for me. This did:

```
module.exports = {
    build: {
        extend(config, {isServer}) {
            const vueLoader = config.module.rules.find(r => r.loader === 'vue-loader');
            vueLoader.options.transformToRequire = {
                video: 'poster',
                source: 'src',
            };
        }
    }
};
```

**Comment by tetreault** [comment]
I'm not sure if my use case is related to this but if I have a video tag like this for example, it works fine: 

```
    <video 
      v-if="currentIndex === 3"  
      playsinline 
      loop  
      class="background-video__source"
    > 
      <source src="~/assets/img/placeholder/placeholder-4.mp4" type="video/mp4">
    </video>
```

If I have something like this however, I get a 404 on the MP4 file: 

```
    <video playsinline loop v-reload="currentIndex">
      <source :src="sources[currentIndex]" type="video/mp4" media="all"> 
      <p>Sorry, there's a problem playing this video. Please try using a modern browser.</p>
    </video>
```

```
  directives: {
    reload(el, binding) {
      if (binding.oldValue !== binding.value) {
        el.load();
      }
    }
  },
```

Just for curiosity I tried the two methods above, @pi0 yours resulted in an error on `npm run dev` but @ubershmekel yours did not (but I still get 404 assets).

**Comment by tetreault** [comment]
working though with MP4 assets placed in `static` though
