### ISSUE TITLE
Cannot access Nuxt's context with `$fetchState.pending`

### ISSUE THREAD

**Issue by kissu** [nuxt/nuxt.js#9564]
### Versions

- nuxt: `2.15.7`
- node: `14.15.0`

### Reproduction

This code is working great
```html
<template>
  <div>
    <template v-if="!this.$fetchState.pending">fetched data!</template>
    <div v-else>fetching still....</div>
  </div>
</template>

<script>
export default {
  async fetch() {
    const call = await fetch('https://jsonplaceholder.typicode.com/todos/1')
    const res = await call.json()
    console.log('res', res)
  },
  computed: {
    isFetchingStillPending() {
      return !this.$fetchState?.pending
    }
  },
}
</script>
```

But if I try to test `isDev` and edit it to the following (no reference of `isDev` in the `template`, just here)
```js
async fetch({ isDev }) {
  console.log('is dev', isDev)
  ...
},
```

It will throw the following error

![image](https://user-images.githubusercontent.com/5133074/125435051-57f6eb9b-4c8d-4642-b0c4-c2db55d44a8d.png)

This is coming from `v-if="!$fetchState.pending"`, replacing it by a computed like this
```js
computed: {
  isFetchingStillPending() {
    return !this.$fetchState?.pending
  }
},
```
Is working great and not crashing anymore.

### Steps to reproduce

You can either use the above code in a new project, or follow this [codesandbox link](https://codesandbox.io/s/hopeful-keller-mdy2p?file=/pages/index.vue).

### What is Expected?

We should be able to use Nuxt's context and having access to the `fetch()` hook at the same time.
Here, I do not even use `isDev` in my template.

### What is actually happening?

Crashing like having both `$fetchState.pending` and `isDev` is not possible.

**Comment by danielroe** [comment]
You can access that with `process.dev` instead (and the whole context should be accessible via `this`).

(The issue is that if your fetch takes an argument it reverts to legacy fetch behaviour - more info in the docs.)

**Comment by kissu** [comment]
If you pass a param to it, it is actually using the older version of the `fetch` hook.
Totally forgot about this one! That explains the _bug_.
More details about the differences are available here: https://nuxtjs.org/blog/understanding-how-fetch-works-in-nuxt-2-12#1-call-order-of-fetch-hook

And to have access to the context, we can to use something like this
```js
fetch() {
  console.log('isDev?', this.$nuxt.context.isDev)
},
```

Thanks Daniel! 🙏🏼
