### ISSUE TITLE
app/router.scrollBehavior.js does not work on Android

### ISSUE THREAD

**Issue by axel-verse** [nuxt/nuxt.js#9566]
I've created `app/router.scrollBehavior.js` as it described in [documentation](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#scrollbehavior) and faced a bug on my Redmi Note 9 Pro (Android 10). When route changes, screen position not changes to x: 0, y: 0.

Desktop browsers work fine.

Also this bug appears in desktop versions of Google Chrome and Firefox in Developer mode with mobile view enabled.

### Versions

- nuxt: 2.15.6
- node: 16.4.2

### Steps to reproduce

1. Create two pages and link them together with `nuxt-link`. Make sure both of them is long enough (two screens of mobile device is enough)
2. Create `app/router.scrollBehavior.js` as it described in [documentation](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#scrollbehavior)
3. Scroll to bottom page 1, then follow link to page 2

### What is Expected?

You should see page 2 scrolled to top

### What is actually happening?

Page 2 opened on same position as page 1 was

**Comment by danielroe** [comment]
What are the contents of your custom scroll behaviour?

**Comment by axel-verse** [comment]
As it is written in documentation:

```javascript
export default function (to, from, savedPosition) {
  return { x: 0, y: 0 }
}
```

**Comment by axel-verse** [comment]
Reproduction at codesandbox: [https://codesandbox.io/s/pedantic-engelbart-ucylh](https://codesandbox.io/s/pedantic-engelbart-ucylh)

**Comment by axel-verse** [comment]
Solution found.

I forgot that the app wrapper has 'overflow: auto' style, so after I've added `document.getElementById('layout-default').scrollTo(0, 0)` to function that handles sidebar links click, everything works.

My bad.

Sorry
