### ISSUE TITLE
Using vueuse but npm requires me to npm install --save @vue/composition-api/dist/vue-composition-api.esm.js

### ISSUE THREAD

**Issue by TonyPythoneer** [nuxt/nuxt.js#9567]
### Versions

- nuxt: 2.15.7
- node: v14.17.3

### Reproduction

repo: https://gitlab.com/tonypythoneer/nuxt-bug

When I try to use Vueuse in my code and `npm run dev`, it will give this error log:

https://gitlab.com/tonypythoneer/nuxt-bug/-/blob/main/pages/index.vue#L27

```sh
✖ Client
  Compiled with some errors in 9.32s


 ERROR  Failed to compile with 1 errors

This dependency was not found:

* @vue/composition-api/dist/vue-composition-api.esm.js in ./node_modules/vue-demi/lib/index.mjs

To install it, you can run: npm install --save @vue/composition-api/dist/vue-composition-api.esm.js
```

When I don't use any function from `vueuse`, nuxt won't shoot errors.
https://gitlab.com/tonypythoneer/nuxt-bug/-/blob/main/pages/index.vue#L57-L59

```vue
onMounted(()=> {
  set(domReady, true);
});
```

I feel confused about why using `vueuse`  will cause `nuxt` to break.

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by antfu** [comment]
Related https://github.com/vueuse/vue-demi/issues/76
