### ISSUE TITLE
Changing ScrollToTop behavior stoped working.

### ISSUE THREAD

**Issue by jerakode** [nuxt/nuxt.js#957]
I used this fix

~plugins/scrolltotop.js

```
import router from '~router'

router.afterEach((to, from) => {
  // set timeout time to time of your transition
  setTimeout(() => {
    // dunno why but conditional helps to speed up build time despite ssr: false…
    if (document) document.body.scrollTop = 0
  }, 500)
})
```
nuxt.config.js

```
router: {
    scrollBehavior: function (to, from, savedPosition) {
      return { x: false, y: false }
    }
},

plugins: [
    {
      src: '~plugins/router-guards',
      ssr: false
    },
]
```
Now it throwing me error

```
 warning  in ./plugins/scrolltotop.js

3:0-6 "export 'default' (imported as 'router') was not found in '~router'
```
And transitions stoped working.

I see @Atinux removed this issue from Roadmap. Will it be implemented from the box or not? This hack is pretty ugly.

**Comment by max-schu** [comment]
it's because there is no ~router alias in the webpack config of the current version anymore, so you have to define your own extending the webpack config – correct me if im wrong…

**Comment by jerakode** [comment]
As I understood - it should be fixed in next release?

**Comment by iamdubx** [comment]
Any fix of this behavior?
