### ISSUE TITLE
alpine causing segmen fault on build

### ISSUE THREAD

**Issue by appinteractive** [nuxt/nuxt.js#958]
when trying to build nuxt (1.0 beta) on alpine, I am always getting a "segment fault". Any idea?

```bash
nuxt:build Building files...
Segmentation fault
ERROR: Service 'api' failed to build: The command '/bin/sh -c ./node_modules/.bin/nuxt build' returned a non-zero code: 139
```

**Comment by pi0** [comment]
Hi. Nuxt is now working fine in alpine and you can use [docker-nuxt](https://github.com/mrsunshine/docker-nuxt) as a reference to get started. We are working on official and production ready docker images too.

Please reopen if the issue still exists.
