### ISSUE TITLE
Accessing process.env.<any-custom-key> inside nuxt.config.js

### ISSUE THREAD

**Issue by jappyjan** [nuxt/nuxt.js#9580]
### Versions

- nuxt: v2.14.7
- node: v12.18.3

### Reproduction

add the following section to nuxt.config.js to configure oneSignal plugin

```
oneSignal: {
    init: {
      appId: process.env.NUXT_ONESIGNAL_APP_ID,
      safari_web_id: process.env.NUXT_ONESIGNAL_SAFARI_WEB_ID
    }
  },
```

set both environment variables in the current terminal session and run nuxt generate (this is a static/spa running on client side only) and then serving the generated files via nuxt start or any file server.

### What is Expected?

oneSignal get initialised with the appId and safari web id configured inside the process.env variables

### What is actually happening?

both (any) process.env variable is undefined and so the intialisation fails

**Comment by tranghaviet** [comment]
I also get env variable undefined only on SSR mode
