### ISSUE TITLE
[nuxt.config.js] How to get host from request?

### ISSUE THREAD

**Issue by workingxx92** [nuxt/nuxt.js#9582]
Hi.
I need to get a host from request. How to do it?
 sitemaps: [
      {
        path: '/products-1.xml',
        exclude: ['/**'],
        routes: async () => {
          let host = request.header.host. // How to get host
          const { data } = await axios.get(`${process.env.API_URL}/sitemap/home`)
          return data.map((user) => `/users/${user.link}`)
        }
      }
    ]

**Comment by manniL** [comment]
There is no host during the build step so fetching it won't be possible at this point of the Nuxt lifecycle
