### ISSUE TITLE
Can not run Static Generated Web without Webpack Middleware

### ISSUE THREAD

**Issue by trungntbk** [nuxt/nuxt.js#959]
I generated my web app to a static web application (by running: nuxt generate).

I want to run it locally by openning **_index.html_** in the **_dist_** folder, but these functions of the app don't work because the app run without **_Webpack middleware_**.

Anyone knows how to resolve it?

Thank you.

**Comment by halas** [comment]
Working on a similar problem now - see the discussion on gitter. 
It helps partially if before running `npm run generate` you set up subdirectory in `nuxt.config.js`:
```
module.exports = {
router: {
base: '/preview/'
}
}
```
and then place the folder in the root directory of your file system (all assets are then mapped to `/preview`)

This was advice I got from @BenoitRanque 
For me it worked partially, I am now setting up experimental small repo to duplicate the error.

**Comment by trungntbk** [comment]
My issue here is: I want to deploy my app in DVD version, but the app can not run without Webpack middleware. So right now, I am looking for something that can simulate Webpack middleware.

**Comment by pi0** [comment]
@trungntbk Dists without ssr and webpack are in our roadmap for 1.x and will come soon. Currently you can use [generate](https://nuxtjs.org/guide#static-generated) functionality for your DVD version :)
