### ISSUE TITLE
Fetch hook breaking during client side routing

### ISSUE THREAD

**Issue by Diizzayy** [nuxt/nuxt.js#9593]
### Versions

- nuxt: v2.15.7
- node: v14.17.3

### Steps to reproduce

Within a newly created barebones Nuxt project:

1. Set the target property in nuxt.config.js to 'static'.
2. Within the components folder, create a new component called States.vue
```
components/States.vue

<template>
  <ul>
    <li v-for="(v, i) of states" :key="i">
      <span>{{ v }}</span>
    </li>
  </ul>
</template>

<script>
export default {
  data() {
    return {
      states: ["New York", "Florida"],
    };
  },

  fetch() {
    // leave as is, showing that this bug occurs even if the hook is unused
    // this.states = [...this.states, "California (from fetch)"];
  },
};
</script>
```
3. Modify the default layout as follows
```
layouts/default.vue

<template>
  <div>
    <nav>
      <ul style="display: flex; gap: 1em; list-style: none">
        <li><n-link to="/">Home</n-link></li>
        <li><n-link to="/proof">Proof</n-link></li>
      </ul>
    </nav>

    <hr />
    <States />
    <hr />

    <nuxt />
  </div>
</template>
```
4. Create a new page called proof.vue
```
pages/proof.vue

<template>
  <div>
    <h1>Proof</h1>
    <p>info: {{ info }}</p>
  </div>
</template>

<script>
export default {
  data() {
    return {
      info: "",
    };
  },

  fetch() {
    this.info = "PROOF PAGE";
  },
};
</script>
```
5. Generate and run production build
```
yarn generate ; yarn start   
```

### What is Expected?

When the 'Proof' link is clicked, the proof page should be loaded and populated with the info from its fetch hook.

### What is actually happening?

The fetch hook in the Proof page fails to run during client side rendering.

However though, when the proof page is loaded directly it's fetch hook is initially triggered until you leave and return to the proof page when the fetch hook then breaks during client side routing.

### **My Observations**

When the fetch hook in the States.vue component is completely commented out, the app then runs as expected.

<details open>
<summary>components/States.vue</summary>
<br>

```
  // fetch() {
  // leave as is, showing that this bug occurs even if the hook is unused
  // this.states = [...this.states, "California (from fetch)"];
  // },
```

</details>

This bug appears to occur either when a layout loads a component that uses the fetch hook _or_ if the fetch hook is used directly within a layout at all.

**Comment by danielroe** [comment]
@Diizzayy If you are using fetch in  fetch-enabled components within layouts, parent routes, or components that are conditionally rendered, then you will likely need to set a custom `fetchKey` - see the [PR](https://github.com/nuxt/nuxt.js/pull/8466). You can find more info on how to use it in the PR or [the docs](https://nuxtjs.org/docs/2.x/components-glossary/pages-fetch).
