### ISSUE TITLE
Use fetch for dynamic route generation

### ISSUE THREAD

**Issue by simeon9696** [nuxt/nuxt.js#9595]
### Discussed in https://github.com/nuxt/nuxt.js/discussions/9459

<div type='discussions-op-text'>

<sup>Originally posted by **simeon9696** June 20, 2021</sup>
Apologies for this question but I'm a bit lost how on to do a full static site generation with dynamic routes using fetch().

Usually, in `nuxt.config.js` I'd pass an array of routes and payloads via `generate.routes` and access the payload in the page component in `asyncData`. But how would I do the the same using the fetch hook? Should the fetch hook be used in this case? 

Just for some context it's an e-commerce site and I just have to generate pages for the different products and I'm using firebase.</div>

Just moving this from discussions to issues since it's been awhile since any activity. My main issue is that I don't know how to use fetch to do route generation.

**Comment by Diizzayy** [comment]
Within the fetch hook, you're able to access the Nuxt context via ```this.$nuxt.context```

so the payload can be accessed as shown below
```
  fetch() {
    const payload = this.$nuxt.context.payload
  }
```

**Comment by simeon9696** [comment]
@Diizzayy thanks! For anyone else looking, this is my full fetch function in a file called `_id.vue`: 

  ```
data(){
 return{
   product: {},
 }
},
async fetch() {
    
    const payload = this.$nuxt.context.payload

    if(payload)
      return this.product = {...payload} //this would evaluate to true in generate but not during development

     //to cater for development, get the data as you usually would in the created or mounted hooks
     const { id } = this.$nuxt.context.params
    try {
      const p = await this.getProductFromDbWithLinkName(id);
      this.product = {...p}
    } catch (error) {
      console.error(error)
    }
  },
```
