### ISSUE TITLE
custom-routes example - links in error.vue page

### ISSUE THREAD

**Issue by mikekidder** [nuxt/nuxt.js#96]
If you type a url (ex. http://localhost:3000/users/3bogus) that causes the optional **validate** to return _false_, it shows the 404 error page as expected.
However, nuxt-links in error page is currently throwing exceptions (see console log).

For simple dynamic pages, it transitions despite Vue warn messages in console.
For dynamic pages with objects, transition does not happen, as you get undefined property errors.

**Comment by Atinux** [comment]
This should be fixed in the next release, we are aware about it :)

**Comment by Atinux** [comment]
It's now fixed in the latest release `0.9.7`
