### ISSUE TITLE
can't read  property 'split' of undefined

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#960]
a few people visit https://www.awesomes.cn/mem/1887/pubs/comments meet this error 

![](https://ws2.sinaimg.cn/large/6115ac8fgy1fgri007wowj20v60csdig.jpg)

But I can vist this url ok, so what happend?

**Comment by pi0** [comment]
Better source maps support in next release would help you a lot finding exact problem in production :)
