### ISSUE TITLE
NuxtLink doesn't add trailing slash for URL params

### ISSUE THREAD

**Issue by Nik96i** [nuxt/nuxt.js#9622]
Hi, I'm using Nuxt 2.15.7, I enabled strailing slashes in my static project and using this block of code for redirecting from non-trailing slash URL to trailing slash URL:

`{ from: '^(\\/[^\\?]*[^\\/])(\\?.*)?$', to: '$1/$2', }`

now, everything is fine, but when I'm using NuxtLink like that:

`<NuxtLink :to="{ params: { page: 2 } }">Page 2</NuxtLink>`

it must be something like this:

`/shop/page/2/`

but it doesn't add a trailing slash at the end until I refresh the page. I know maybe this is not a bug but there is no way I can tell this component to add a trailing slash for me! I have to do this with path replacing way.

**Comment by manniL** [comment]
You can use [`router.trailingSlash`](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#trailingslash) ☺️

**Comment by Abdulsametileri** [comment]
I think I have a same problem. 

When I go to 
http://localhost:8080/search/?q=foo
nuxt changes url
http://localhost:8080/search?q=foo

it removes slash, I have to keep this. /?q=foo

I tried trailingSlash but no success at all. Any idea?
