### ISSUE TITLE
Navigating back causes the scroll position to be reset to the top, in safari mobile

### ISSUE THREAD

**Issue by patrioticcow** [nuxt/nuxt.js#9623]
### Versions
- nuxt: 2.15.7

### Steps to reproduce

Here is a [sample sandbox ](https://codesandbox.io/s/codesandbox-nuxt-forked-4wfkl?file=/layouts/default.vue)

1. Open an iOS emulator and fo to this url [https://4wfkl.sse.codesandbox.io/](https://4wfkl.sse.codesandbox.io/)
2. Scroll down the page a bit and click on the `About page` link
3. On the About page, tap the emulator back button

### What is Expected?

On the previous page, the scroll position should be where the  clicked link was

### What is actually happening?

The page scroll to the top

### See it working

To see the fix, uncomment `// window.history.scrollRestoration = "auto";` in the `default.vue` layout, and try the steps again.

In `router.scrollBehavior.js` the scroll position is set on `beforeunload` but safari seems not to like that, but `pagehide` seems to work. Tho, I'm not sure this is the right fix.

Ideas?

**Comment by vicky-wd** [comment]
the same question +1

**Comment by gabrielsze** [comment]
noticed the same behaviour still +1
