### ISSUE TITLE
Nuxt 2.15.7: Trailing slash in window.location.href disappears after page load

### ISSUE THREAD

**Issue by arkhamvm** [nuxt/nuxt.js#9624]
### Versions

- nuxt: v2.15.**7**
- node: v14.16.1

### Repro Repo
https://codesandbox.io/s/beautiful-taussig-hlw8i?file=/pages/index.vue

### Steps to reproduce
Click on "about" button or directly: https://hlw8i.sse.codesandbox.io/about/
![nuxt_slash_1](https://user-images.githubusercontent.com/9816112/127970010-6d8d845c-1010-404f-bd61-1178eb15d7d6.png)

Wait for page load
![nuxt_slash_2](https://user-images.githubusercontent.com/9816112/127970034-9ad4257d-8b1a-41d0-80ee-7b647d136e8e.png)

### What is Expected?
Trailing slash stays.
Works fine with v2.15.**6**.

### What is actually happening?
![gone](https://user-images.githubusercontent.com/9816112/127970046-99a3c2e7-0d10-4f81-bf98-e30c0cafc7ad.gif)

**Comment by danielroe** [comment]
This should be resolved by https://github.com/nuxt/nuxt.js/pull/9460 in the next release.
