### ISSUE TITLE
Result not fully static

### ISSUE THREAD

**Issue by cambea** [nuxt/nuxt.js#9626]
### Versions

- nuxt: v2.15.7
- node: v14.17.4
 
### Query Example

```js
export default {
    async asyncData({$strapi}) {
    const pages = await $strapi.$pages.find();
    return { pages }
    },
    computed: {
        pageML() {
            return this.pages.filter(pages => pages.slug === 'page_ML')
        },
    }
}
```

### What is Expected?

My website is supposed to use payload and not fetch my strapi server.

### What is actually happening?
I generated my project as static. I deployed it to Netlify. But when I navigate on my pages it's fetching data from my CMS. [https://silly-sinoussi-0007bd.netlify.app](https://silly-sinoussi-0007bd.netlify.app)

**Comment by hmaesta** [comment]
You must set `target: static` and `ssr: true`.

https://nuxtjs.org/blog/going-full-static

**Comment by manniL** [comment]
Stale - closing here. If the issue persists, please provide a reproduction ☺️
