### ISSUE TITLE
third party library, lazy loading, dev server complains, static build is fine

### ISSUE THREAD

**Issue by yacoob** [nuxt/nuxt.js#9641]
### Discussed in https://github.com/nuxt/nuxt.js/discussions/9601

<div type='discussions-op-text'>

<sup>Originally posted by **yacoob** July 26, 2021</sup>
**tl;dr**: I get a dynamic component resolution problem in dev server only despite lazy loading and I can't figure out why.

I'm making a nuxt version of my website. I want to continue using [lightgallery](https://www.lightgalleryjs.com/) for the images. It has an official vue wrapper, but only for vue3. Regardless of the vue version, that library accesses `window` during import, and as such causes problems with ssr enabled. The author admits as much, and recommends dynamic loading (eg. [here](https://github.com/sachinchoolur/lightGallery/issues/1024#issuecomment-849460171)). 

Now, I wrote my own simple vue 2 component for lightgallery. I've wrapped the instantiation of that component in `<client-only>` and prefixed the name of the component with `lazy` as seen [here](https://github.com/yacoob/gcu/blob/8cd5c3f213cd3e35129b7b8eddf8bbbbd7d5ed4f/pages/_grade/_kit.vue#L10-L16). To my surprise, this still resulted in following error produced on both the terminal and browser's console when I visited a page using that component on the dev server:

```
20:17:56.265 [Vue warn]: Failed to resolve async component: () => __webpack_require__.e(/*! import() | components/gallery-controller */ "components/gallery-controller").then(__webpack_require__.bind(null, /*! ../../components/GalleryController.vue */ "./components/GalleryController.vue")).then(c => Object(_utils__WEBPACK_IMPORTED_MODULE_1__["wrapFunctional"])(c.default || c))
Reason: ReferenceError: window is not defined client.js:56
    NuxtJS 11
        <anonymous>
        <anonymous>
        <anonymous>
        js
        __webpack_require__
        fn
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
```
The gallery works more or less fine from what I can tell, despite this error. I had some hiccups when I initially wrote this question, but I think I can chalk it up to browser misbehaving on my end. What's most perplexing to me, the site works fine once generated for static serving - that is, `yarn generate`. This fact really makes me think this tickles some weird bug in nuxt that is specific to the dev server.

My project's code at the version displaying this behaviour is [here](https://github.com/yacoob/gcu/tree/8cd5c3f213cd3e35129b7b8eddf8bbbbd7d5ed4f) and [here](https://60fef90407f81b0008922c7c--gcu.netlify.app/hg/moon) is a matching netlify build. I don't have any experience with modern webdev and webpack - so tracing this down takes a lot of time and effort. I'd be grateful for some sort of diagnosis here :D

Thanks!</div>

**Comment by yacoob** [comment]
I understand that everyone is probably working on the upcoming nuxt3 release, but I'd really appreciate some sort of commentary on what is the reason behind this failure. :(

**Comment by yacoob** [comment]
Latest commit at which this behavior is still manifesting is [here](https://github.com/yacoob/gcu/tree/2290fd95be6b4fa8ec62951faeb25a7da2ddbbe3) and the matching deploy is [here](https://610ed7d9c75c590009cb1b8c--gcu.netlify.app/).

As an extra datapoint: with that error present, every now and then Firefox starts being unable to finish loading the page - starting from timing out on the last webpack chunk containing the lazyloaded script to not being able to complete the initial load. Once triggered, problem persists through devserver restarts. I'm guessing it's a combination of a race condition on the devserver side and... something on the browser side, no idea what. Curiously enough, Chrome doesn't trigger this kind of page loading problem while still seeing the "failed to resolve" message. The dev server runs in a container under win10, if that's relevant here.

**Comment by manniL** [comment]
Hey 👋 
This is not a Nuxt issue itself so let's keep using GitHub Discussions ☺️
