### ISSUE TITLE
layout/default.vue not working.

### ISSUE THREAD

**Issue by Isidorev215** [nuxt/nuxt.js#9643]
I added `layouts/default.vue` to create a default layout, nothing happens.
I looked into `.nuxt/app.js` and I found this: `import _6f6c098b from '.\\layouts\\default.vue'` instead of` import _6f6c098b from '..\\layouts\\default.vue' `
I edited the line and added the missing `.` and it worked. However, I have been told that editing files in `.nuxt` is only recommended for debugging and will not actually fix the problem.

I am using `"nuxt": "^2.15.7"`

**Comment by danielroe** [comment]
@Isidorev215 Would you provide a reproduction using https://template.nuxtjs.org ? 🙏
