### ISSUE TITLE
"Though the loose option was set to false" error on fresh nuxt install.

### ISSUE THREAD

**Issue by onurusluca** [nuxt/nuxt.js#9651]
### Versions

- nuxt: v2.15.7 
- node:  v16.5.0 
- Windows 10 Home Fully Updated

### Reproduction

Create a new nuxt app.

### Steps to reproduce

Project name: my-brand-new-project
? Programming language: **JavaScript** 
? Package manager: **Npm**
? UI framework: **None**
? Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert selection) _(Axios)_
? Linting tools: (Press <space> to select, <a> to toggle all, <i> to invert selection) _(Prettier)_
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)

### What is Expected?
Start normally after npm run dev

### What is actually happening?
Having this error.

`Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.`

**Comment by chadwickellis** [comment]
This will be fixed in [#9631](https://github.com/nuxt/nuxt.js/pull/9631).
