### ISSUE TITLE
"Though the loose option was set to false" error on fresh nuxt install. Reopen!

### ISSUE THREAD

**Issue by Intevel** [nuxt/nuxt.js#9653]
I just set up a new NuxtJS project and a problem what came in another version again. [Issue#9651](https://github.com/nuxt/nuxt.js/issues/9651).

I copied the text from the old issue. The [Merge/Fix ](https://github.com/nuxt/nuxt.js/pull/9631) was deleted!

Reproduction
Create a new nuxt app.

Steps to reproduce
Project name: my-brand-new-project
? Programming language: JavaScript
? Package manager: Npm
? UI framework: None
? Nuxt.js modules: (Press to select, to toggle all, to invert selection) (Axios)
? Linting tools: (Press to select, to toggle all, to invert selection) (Prettier)
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)

What is Expected?
Start normally after npm run dev

What is actually happening?
Having this error.

Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods. The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding ["@babel/plugin-proposal-private-property-in-object", { "loose": true }] to the "plugins" section of your Babel config.

**Comment by danielroe** [comment]
@Intevel The fix you linked has been merged but not yet released.

You can substitute `nuxt-edge` for `nuxt` in your `package.json` to confirm that the fix works.
