### ISSUE TITLE
Generate a static 404 page

### ISSUE THREAD

**Issue by ishitatsuyuki** [nuxt/nuxt.js#966]
Most static hosting providers provides an option for custom error page, and it should be possible to prerender the error template too.

**Comment by cesasol** [comment]
there is, just read the docs https://nuxtjs.org/guide/views/#error-page

**Comment by ishitatsuyuki** [comment]
I'm not sure if you understood the issue correctly. I'm aware of the error template, but it is not generated for a static site made with `nuxt generate`.

**Comment by cesasol** [comment]
Maybe, adding 404 to the routes in the nuxt.config.js

```
generate: {
  routes: ['404']
}
``` 
and if that does not work try creating a `pages/404/index.vue`

**Comment by ishitatsuyuki** [comment]
Sure, it works, but it generates a suboptimal path: `dist/404/index.html`

**Comment by cesasol** [comment]
if that does not work out of the box with your server, try adding this to your .htaccess
`ErrorDocument 404 /404/index.html`

**Comment by stefanjudis** [comment]
@alexchopin Hey. 👋 

I'm looking for the same option, due to netlify's nature I have to generate a `dist/404.html`. May I ask how you would approach this. I'd love to have a look into nuxt. :)

**Comment by alexchopin** [comment]
The problem is that a `404.html` page is not generated by default.
I usually do this for a static 404 page:

- Add a route `path: '/404'` into the generate option of nuxt.config.js.
- Rename `dist/404/index.html` into `dist/404.html`.
- Copy the `dist/404.html` into `static` to save it for the future.

I can add a generate option for a 404 page but not 100% sure if everyone need it?

**Comment by ishitatsuyuki** [comment]
I would prefer it, with the following reasons:
- it's the default of a lot of static hosting services, including GitHub Pages, Netlify, Firebase Hosting, (that's all services I have used).
- it generates without a verbose console log of error.

**Comment by cesasol** [comment]
I also would prefer this functionality out of the box, and even for more than a 404 error, any kind of standard error like 400, 500. And manually creating the content with asyncData and conditionals for   each code anyone wants to support

**Comment by ishitatsuyuki** [comment]
Most of the status code won't happen on static websites. 401 and 403 do happen, so at most those could be sensible.

**Comment by alexchopin** [comment]
For static website, only a 404 page is needed.
The others status code should be handled by a server.
The functionality with the condition below will be available to the next release:
If a `/404` route exist, the `/404/index.html` is renamed as `/404.html`, that is managed by most of static hosting services.

**Comment by ishitatsuyuki** [comment]
Sounds good. By the way, is it possible to remove the verbose error message too?

**Comment by alexchopin** [comment]
The message about files generated?

**Comment by ishitatsuyuki** [comment]
I mean this one:

```
==== Error report ====
Route: '404' thrown an error:
{"statusCode":404,"message":"This page could not be found."}
[nuxt] Generate done
```

**Comment by iamdubx** [comment]
I have the same issue. How to use 404 with `npm run generate`?

**Comment by Katarzina** [comment]
I've checked...All right, 
1. add to  nuxt.config.js 
generate: {
  routes: ['404']
}
2. it's generate /404/index.html
3. then add .htaccess
  ErrorDocument 404 /404/index.html

**Comment by iamdubx** [comment]
@Katarzina so this is webserver issue? I am using nginx. I tried some 404 nginx settings, but still not working. Any tips about nginx?

**Comment by Katarzina** [comment]
I've checked...All right, 
1. add to  nuxt.config.js 
generate: {
  routes: ['404']
}
2. it's generate /404/index.html
3. then add .htaccess
  ErrorDocument 404 /404/index.html

**Comment by Katarzina** [comment]
I made experiment with my nginx local server
nginx:
I add:
error_page
 `404 /404/index.html;
    location = /404/index.html {
            internal;
   }`
If any way will have error..look on error.log and explore more this section:
  ` location / {
        root /var/www/kp.cz/dist;        
        index index.html index.htm;    
    }`
  kp.cz - my name server

**Comment by iamdubx** [comment]
@Katarzina thank you, I will try tomorrow!

**Comment by iamdubx** [comment]
So, at last I tried that. All I need is just one line in nginx config `error_page 404 /404.html;`

**Comment by FabianEllenberger** [comment]
Hi @alexchopin, is there a kownway to have this automatic 404 generation for multiple 404.html files, in different languages? Like: 404.html and 404_en.html?

**Comment by toyflish** [comment]
I have a static generated site with page/404/index.vue  generated to /404.html.
Requesting Apache to /not-existant-url.html  it serves the 404.html static-generated page but after milliseconds nuxt.js get's loaded into my 404 and tries to load the "not-existand-url" route and makes it a blank page.
How do you avoid nuxt from kicking in on the 404 page?

**Comment by gijo-varghese** [comment]
```
generate: {
    fallback: "404.html"
},
```
this seems to generate 404.html page in the root without any problems. Also working fine with Firebase
