### ISSUE TITLE
Problems with asyncData in Express.js + SSL

### ISSUE THREAD

**Issue by ald890** [nuxt/nuxt.js#967]
I am change the server configuration to SSL and application is running normally,
but on startup asyncData functions do not working, others synchronous requests like onClick GET works.

`var server = https.createServer(options, app).listen(port, function(){
    console.log("Express server listening on port " + port);
  });`

`
async asyncData ({ store, params }) {
  console.log(1) // not working
} 
`

**Comment by Atinux** [comment]
Please create a repository to reproduce this issue, I am not sure to understand what you mean.

Also you can look at the express template we have.

**Comment by ald890** [comment]
Meh nuxt has soo many bugs... thanks for help!
