### ISSUE TITLE
Does nuxt support named view routes?

### ISSUE THREAD

**Issue by lavsurgut** [nuxt/nuxt.js#968]
I can't find how I could, for example, extend routes with something like this:
```javascript
routes: [
    {
      path: '/',
      components: {
        default: Foo,
        a: Bar,
        b: Baz
      }
    }
]
```

And then use named views like this on the page:
```html
<router-view class="view one"></router-view>
<router-view class="view two" name="a"></router-view>
<router-view class="view three" name="b"></router-view>
```

When I use extendRoutes function it keeps giving me an error that it could not find module dependency 
```bash
./.nuxt/route.js
```

**Comment by Atinux** [comment]
Hi @lavsurgut

Because of the FS router Nuxt does not support this feature of vue-router, but you can easily do it with dynamic component (<component :is="a"/>)

**Comment by lavsurgut** [comment]
Is it possible to have asyncData or fetch inside dynamic component?
