### ISSUE TITLE
Environment variables not detected when used in config file from an imported source

### ISSUE THREAD

**Issue by dvlden** [nuxt/nuxt.js#9688]
### Versions

- nuxt: v2.15.7
- node: v16.7.0

### Reproduction

https://github.com/dvlden/nuxt-generate-bug

### Steps to reproduce

- clone reproduction repository
- install dependencies
- `yarn run generate`
- check `dist/index.html`, the custom meta tag will contain value of `APP_SPECIAL` env. variable, which is `holy.sh`
- edit contents of `.env` file by changing `APP_SPECIAL` to something else
- `yarn run generate`
- check `dist/index.html`, the custom meta tag will remain untouched, the meta content will be what it was initially
- `rm -rf dist .nuxt`
- `yarn run generate`
- still old value, it doesn't detect the change

### What is Expected?

All `process.env` variables should exist so that their change can be tracked. This isn't the case when something is imported inside `nuxt.config.js` and used for configuration.

### What is actually happening?

It seems that nuxt doesn't pick up env. variables that appear to be unused?

If you inspect `@nuxt/cli/dist/cli-generate.js` and log the `currentBuild`, you'll notice that `process.env` only contains `APP_SOMETHING` which is used in `nuxt.config.js` directly, through the constant. 

However, `APP_SPECIAL` is non-existent within `process.env`, but it's being imported from a file and used in example to create contents of a meta tag. I assume we could've use the imported constant for some other purpose too and it wouldn't detect a change.

This problem is happening for all `nuxt` scripts, not just `generate`.

**Comment by dvlden** [comment]
@danielpost That's works, but slows down the repeated process, as it doesn't cache anything.

_"To avoid rebuilding when an unimportant env variable changes, Nuxt checks your nuxt.config for usage."_ 
Yes I noticed that, but how come it doesn't check for env variables that were used in other files and were imported in config and used for some part of config? That bit kind of makes no sense. I just used a single file to cleanup nuxt config file and extract some utilities there, that happen to use env variables... Is there a way to at least tell it Nuxt, to also check some other files for important env variable changes?

**Comment by pi0** [comment]
A new `ignoreEnv` option is coming with 2.16 (https://github.com/nuxt/nuxt.js/pull/8955) which you can try by using `nuxt-edge` or using the workaround mentioned by @danielroe to explicitly add used envs.

/note: For nuxi/nuxt3 we should try a proxy-based implementation to track `process.env` accessing

**Comment by dvlden** [comment]
Perfect! 
Thank you @danielpost for that workaround and thank you @pi0 for useful information about a new upcoming feature.
