### ISSUE TITLE
Can't use properties inside meta-head method with vue-class-components

### ISSUE THREAD

**Issue by Faber-smythe** [nuxt/nuxt.js#9689]
- Nuxt version : 2.15.3
- Node version : 14.16.0

I'm trying to set a dynamic page title in a class component.
```
import { Component, Vue } from 'nuxt-property-decorator'

@Component({
  head() {
    return {
      title: this.name
    }
  }
})
class Index extends Vue {
  name: string =  'Index'
}
export default Index
```

This has been discussed in #684 and the code above seemed to work, however today I'm unable to build because of the following error :

**"Property 'name' does not exist on type 'Vue'."**

Does anyone have clue ? The point of the *head ( )* method is to set dynamic page titles, right ? But why can't we access the component's properties then ?

EDIT : I'm using Typescript, but I don't know if it matters

**Comment by ArnoldPMolenaar** [comment]
I have the same issue. 
When doing a `console.log(this);` in the head function I get a undefined on server-side.
client-side works fine. the head option is completely broken from version 2.15.*

Test it out by starting empty project and implement the above code.

**Comment by danielroe** [comment]
That isn't a nuxt issue, as you can see: https://codesandbox.io/s/jolly-faraday-ozzbzq?file=/pages/index.vue. If it's not working in `vue-class-component` then I suggest you raise an issue in that repository.

**Comment by ArnoldPMolenaar** [comment]
I

> That isn't a nuxt issue, as you can see: https://codesandbox.io/s/jolly-faraday-ozzbzq?file=/pages/index.vue. If it's not working in `vue-class-component` then I suggest you raise an issue in that repository.

That is a javascript build, this is a Typescript issue.
Also without decorators this is not working.
```
<template>
  <Tutorial/>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'IndexPage',
  head: () => {
    console.log(process.server);
    console.log(Object.keys(this)); // <--- this is undefined
    return {};
  }
})
</script>

```

**Comment by danielroe** [comment]
@ArnoldPMolenaar The issue is you are using an arrow function which has no access to `this`.
