### ISSUE TITLE
alpha.4 resolving to alpha2 with yarn

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#969]
Really not sure why this is happening but when I run `yarn` with nuxt package.json set to alpha.4 it resolves to alpha2. 

```
nuxt@^1.0.0-alpha.4:
  version "1.0.0-alpha2"
  resolved "https://registry.yarnpkg.com/nuxt/-/nuxt-1.0.0-alpha2.tgz#03366dd8384406b26b1eeff06f7f2b12a6f40c00"
```

**Comment by pi0** [comment]
@uptownhr Yep a known problem because alpha tagging convention changed from aplha2. Sorry for that inconvenience. Please remove .yarn.lock and make sure nuxt in package.json is like `"nuxt": "1.0.0-alpha.4"` then running `yarn` command again.
