### ISSUE TITLE
import css bug?

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#97]
>* Install the template

```shell

vue init ddvs/nuxt testeui&&cd testeui&&npm i

```

>* Enter debug mode

```shell

npm run dev

```

This time we can normally open http://127.0.0.1:3000/admin

Because css is the introduction of such

![image](https://cloud.githubusercontent.com/assets/17898715/21580556/dfb8a646-d03a-11e6-976e-829588d18789.png)

But when I recommend the introduction of being given the wrong way
[element-ui init doc](http://element.eleme.io/#/en-US/component/quickstart)

![image](https://cloud.githubusercontent.com/assets/17898715/21580562/30503c36-d03b-11e6-87e7-f64401be8f7a.png)

This is the [element-ui the bugs](https://github.com/ElemeFE/element/issues/2142)? Or my own allocation of the problem

**Comment by Atinux** [comment]
Hi @yuchonghua 

Nuxt.js uses Vue files so you should not import css in the `<script>` block.

Add in your `layouts/admin.vue` file:
```html
<style src="element-ui/lib/theme-default/index.css"></style>
```

This will do the work.

**Comment by yuchonghua** [comment]
thank you very much for your reply
