### ISSUE TITLE
Code of methods that aren't awaited in fetch is lost

### ISSUE THREAD

**Issue by kaguya3222** [nuxt/nuxt.js#9712]
### Versions

- nuxt: 2.5.18
- node: 14.15.1

### Reproduction

[Codesandbox](https://codesandbox.io/s/nuxt-fetch-bug-bx02e?file=/pages/index.vue)

<details open>
In the demo on codesandbox, we have two async methods: `first` and `second` that are called in `fetch` option. `first` is not used with `await`, because we don't want to wait for the result, but `second` is used with `await`. If we reload the page, so that fetch method will run on server side, code in `first` method is strangely lost, so we won't see 'first end' message in the browser console and our template won't be updated, but nuxt will log it into a terminal.
</details>

### Steps to reproduce
Refresh index page so that fetch will work on the server-side.

### What is Expected?
These logs are expected in the browser console: 
first start
second start
second end
first end

This is expected on page content: 
first loading: false
second loading: false

### What is actually happening?
These logs are actually being logged in the browser console:
first start
second start
second end

This is shown on page content:
first loading: true
second loading: false

**Comment by MichealPearce** [comment]
I am experiencing a similar issue with fetch. However, the console results of the codesandbox differ from what you list has happening.

![image](https://user-images.githubusercontent.com/8726457/131408872-7ab8fb7f-dcd2-46bd-a9f5-5bfc2a54f1d1.png)

**Comment by danielroe** [comment]
@kaguya3222 Yes, you need to await all methods in `fetch()` that need to complete before the server-side response is sent back to the client. Otherwise, Nuxt has no way to know that it should wait longer.

(The reason the second `first end` is logged is that the code still runs - but it completes after the Vue render has finished so it's not included in the server response.)
