### ISSUE TITLE
Server state restore is executed after Vuex plugins

### ISSUE THREAD

**Issue by ishitatsuyuki** [nuxt/nuxt.js#972]
In [index.js](https://github.com/nuxt/nuxt.js/blob/6a562e1fe73e897a009b9b00cc3a19950892b382/lib/app/index.js), createState() is called first (and plugins are initialized), then the server state is restored.

This effectively disables plugins using Local Storage to persist state (client side data is overriden with SSR data every time). A brief code example is attached below for easier understanding.

I propose to inject a SSR restore plugin at the first of Vuex `plugins` constructor parameter. This way, SSR restore happens before other plugins.

Code:
```
import createPersistedState from 'vuex-persistedstate'

export const state = () => ({
  // ... defaults ...
})

export const plugins = [
  createPersistedState()
]

```

**Comment by dts** [comment]
This is an interesting conundrum.  Keep in mind that the following code breaks SSR, because the server doesn't know about the local persisted state, but you can prepend this function to the plugins list, like so:

```js
function restoreState(store) {
  if (process.browser) {
    if (store) {
      // Replace store state before calling plugins
      if (window.__NUXT__ && window.__NUXT__.state) {
        store.replaceState(window.__NUXT__.state)
        delete window.__NUXT__.state;
      }
    }
  }
}

export const plugins = [restoreState, createPersistedState()];
```

A quick explanation: the internal version of the NUXT state restore does a check to see if __NUXT__.state exists, so we use it up, delete it, and then rehydrate the state from localStorage.  When the internal version carefully checks if __NUXT__.state exists, it finds that it does not, and doesn't overwrite state.

**Comment by ishitatsuyuki** [comment]
That's a cool solution.

I think documenting this is enough (making this change global is hard and breaks things). @alexchopin how do you think?

**Comment by ishitatsuyuki** [comment]
Uh oh, although it's something by design, this will generate a warning:

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Comment by dts** [comment]
Agreed, how do you do this?

**Comment by vijaythecoder** [comment]
I am also looking for a solution, I am trying to build a shopping cart and need persisted vuex data. 
as @ishitatsuyuki says @dts example gives warning

**Comment by dts** [comment]
Yeah - we need to execute something on client-side only - so that's probably the `fetch()` command

**Comment by Torpexx** [comment]
Any progress on this? I have the same problem :/

**Comment by pi0** [comment]
With next release (rc6) store state rehydration will be done **after** plugins. So we have a chance to change it. Also official `vue-persistedstate` for nuxt:

https://github.com/nuxt/nuxt.js/tree/dev/examples/vuex-persistedstate

**Comment by ishitatsuyuki** [comment]
Well, I think you meant **before**. Anyway, this is basically bringing the same functionality as @dts showed, and the client-only rehydration problem will never resolve due to the architecture.

**Comment by pi0** [comment]
@ishitatsuyuki Unfortunately yes as SSR rendering anyway needs the same state of client side for a matching DOM tree and we may need some advanced workarounds like store all state in cookie for server-side working too. This is why [spa mode](https://github.com/nuxt/nuxt.js/blob/dev/examples/vuex-persistedstate/nuxt.config.js#L5) was used in the mentioned example. Any workaround for this from the community would be appreciated.

**Comment by mnishihan** [comment]
After playing around a bit, I've come up with a solution to use [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate) plugin without setting the `spa mode`. 

What I had to do is:

1. Create the plugin function with a `getState` option, that does nothing and pushed that into the `plugins` array only when `process.browser` is `true` and used that `plugins` array while creating `Vuex.Store` instance.

```
import Vuex from 'vuex'
const plugins = []

if (process.browser) {
  plugins.push(createPersistedState({
    getState: (key, storage) => {}
  }))
}

export default () => {
  return new Vuex.Store({
  ...
  plugins,
  ...
  })
}
```

2. Then I've to create a nuxt plugin with following code that utilises `onNuxtReady` handler and register that plugin with `ssr: false` in nuxt.config.js

```
const getState = (key, storage) => {
  const value = storage.getItem(key)
  try {
    return value && value !== 'undefined' ? JSON.parse(value) : undefined
  } catch (err) {
    return undefined
  }
}

import merge from 'lodash.merge' // already available via installation of vuex-persistedstate

if (process.browser) {
  window.onNuxtReady((nuxt) => {
    const store = nuxt.$store
    const savedState = getState('vuex', window.localStorage)
    if (typeof savedState === 'object') {
      store.replaceState(merge({}, store.state, savedState))
    }
  })
}
```

Sharing with hope, that someone will find this trick helpful as well.

**Note**: The code of above `nuxt plugin` is mostly borrowed from the source of [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate) without much reinvention. So, all credit goes to the author actually. :-)

**Comment by PrimozRome** [comment]
@mnishihan how did you get this working in ssr mode? I get `window is not defined` at this line:

plugins/vuex-persistance.js
```
  window.onNuxtReady((nuxt) => {
    createPersistedState()(store) // vuex plugins can be connected to store, even after creation
  })
}
``

**Comment by mnishihan** [comment]
@PrimozRome There are two ways to fix this `window is undefined` error for non `spa mode`:

1. Recommended way: use `ssr: false` while registering the plugin in `nuxt.config.js` as below:

```
plugins: [
  { src: '~plugins/persistedstate.js', ssr: false }
]
```

2. Alternate way: use `isClient` or `isServer` from the context to conditionally run `window.onNuxtReady()` in your plugin like below:

```
import createPersistedState from 'vuex-persistedstate'

export default ({store, isHMR, isServer, isClient}) => {
  // In case of HMR, mutation occurs before nuxReady, so previously saved state
  // gets replaced with original state received from server. So, we've to skip HMR.
  // Also nuxtReady event fires for HMR as well, which results multiple registration of
  // vuex-persistedstate plugin
  if (isHMR) return

  if (isClient) {
    window.onNuxtReady((nuxt) => {
      createPersistedState()(store) // vuex plugins can be connected to store, even after creation
    })
  }
}
```

**Comment by PrimozRome** [comment]
@mnishihan yes I get this... I was able to figure out the `ssr: false` flag.

But I want to read the local storare from when I come into the app from refresh in browser... When I do refresh entire app is server from server side and I can't read the local storage there because `ssr: false` coms into effect right?

**Comment by mnishihan** [comment]
@primozrome In my app this is working fine. You might want to try several things to get it working:

1. Upgrade nuxt package (I'm using latest rc11)
2. Register the plugin after all plugins that might mutate your vuex store and before any plugin that depends on the persisted state of vuex store.
3. Restart your dev server and try again after deleting vuex entry from your local storage.

**Comment by PrimozRome** [comment]
Nothing works. Looks like middleware is not even executed in the client on browser refresh...

**Comment by mnishihan** [comment]
I'm being totally confused. Why are your calling this as middleware? This
should be registered as a plugin, not a route middleware. Can you share
your nuxt.config.js file?

**Comment by PrimozRome** [comment]
@mnishihan I am not I have this setup in the plugins as you explained above. nothing wrong here this works as expected.

But then I have auth.js middleware where I check the local storage for auth-token. If auth-token exist and is valid I would like to automatically log in user on refresh, otherwise redirect him to the login page. Also this auth middleware commits some store mutations. 

But when I press refresh the middleware is never executed in isClient=true context so I would be able to read auth token and automatically log in user. So for every refresh app takes me back to the login page which is not something of a good UIX experience.

**Comment by mnishihan** [comment]
Now I got it. Server side middleware doesn't know anything about client
side persisted state and client side middleware doesn't execute in page
refresh or first load.

To overcome this, write your middleware code in onNuxReady event handler
(if you want to set the logic globally) or in fetch() method of layout/page
conditionally when isClient is true or even better in mounted() method (as
it only executes at client side).

To understand what I mean, read the discussion above and also see the
official example of auth routes in nuxt guide.

**Comment by PrimozRome** [comment]
@mnishihan uff thanks a lot on this. So the client side middleware is not executed on page refresh. Damn that's what I did not know. Spent days figuring this out 👎 .

> To overcome this, write your middleware code in onNuxReady event handler

Where exactly is this defined?

**Comment by mnishihan** [comment]
onNuxtReady event handler is the place where you're already calling
createPersistedState()(store) in your plugin. Just add any code, after that
line, that depends on the restored client side persisted state and you want
to execute that code globally once after each page reload. Remember like
all nuxt plugin, this code will execute only once, after page reload. So,
if you want to validate auth & redirect, the place would be to write the
redirection logic in layout's/page's fetch() or monuted() method.

**Comment by nikugogoi** [comment]
for anyone needing a workaround to persist state across server and client together
*plugins/persistedstate.js*
```
import createPersistedState from 'vuex-persistedstate'
import * as Cookies from 'js-cookie'
import cookie from 'cookie'

export default ({store, req, isDev}) => {
  createPersistedState({
      key: 'your_key',
      paths: ['state1', 'state2',...so_on],
      storage: {
        getItem: (key) => process.client ? Cookies.getJSON(key) : cookie.parse(req.headers.cookie||'')[key],
        setItem: (key, value) => Cookies.set(key, value, { expires: 365, secure: !isDev }),
        removeItem: (key) => Cookies.remove(key)
      }
  })(store)
}
```
*nuxt.config.js*
```
plugins: [
  { src: '~plugins/persistedstate.js' }
]
```

**Comment by busheezy** [comment]
@nikugogoi Thanks so much. I'm not sure if this is the best way but it looks pretty straight forward. It does exactly what I want.

**Comment by nikugogoi** [comment]
@busheezy keep in mind that you are storing data in the cookie which is tranferred along with server calls from client to server. More the data, more the expense in data transfer. So you should be careful about how much state you persist using `paths`. So, this solution has kind of a performance caveat one might say.

**Comment by Oliboy50** [comment]
@nikugogoi thanks for your solution which seems to work like a charm

but could you explain why you're setting `secure: !isDev`?

Because I tried to set `secure: true` and it doesn't work anymore with `npm run dev`... so I wanted to know, in which case this would work in production env?

**Comment by furyscript** [comment]
@nikugogoi 
It works but not 100%. If you redirect from `fetch` or `asyncData` into a sections that have middleware, store get modify by mutators and after was restore to the previous value.

@Oliboy50 `secure` is to check if you are in `https` or not.

**Comment by nikugogoi** [comment]
@furyscript redirect from `fetch` or `asyncData` server side?? because in client side `redirect()` performs a simple `window.location.replace(path)`
