### ISSUE TITLE
Exits with Assertion failed: (thread_id_key != 0x7777) when trying install scss and style-resouces.

### ISSUE THREAD

**Issue by plutach** [nuxt/nuxt.js#9722]
### Versions

- nuxt: v2.15.8 
- node: v16.8.0
- sass: v1.38.1,
- sass-loader: v10.2.0,

### Steps to reproduce
1.  npm init nuxt-app <project-name>
2.  add `lang="scss"` inside style tag of the pages/index.vue
3. npm install --save-dev sass sass-loader@10 fibers
4.  npm install --save-dev @nuxtjs/style-resources
5.  add `assests/scss/main.scss` file to src.
6.  modify nuxt.config.js
     `export default { 
      css: [ '@/assets/scss/main.scss'],
      modules: [ '@nuxtjs/style-resources'],
      styleResources: {
              scss: ['./assets/scss/*.scss']
     },
}`
7. npm run dev

### What is Expected?
Normal compilation and be able to listen at  http://localhost:3000/

### What is actually happening?
Exits with the following error after compilation.
`Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
[1]    61885 abort      npm run dev`

**Comment by plutach** [comment]
I was able to fix this issue by downgrading the node version to LTS v14.17.5

**Comment by MichealPearce** [comment]
Can confirm, is a issue with node v16. Had the same issue & fix

**Comment by carlos00027** [comment]
+1

**Comment by OssiPesonen** [comment]
> Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.

`node-fibers` development has stopped and won't support 16.x versions of node.js. The `sass-loader` package depends on `fibers`, if you wish to use synchronous compilation.

> Note that when using sass (Dart Sass), synchronous compilation is twice as fast as asynchronous compilation by default, due to the overhead of asynchronous callbacks. To avoid this overhead, you can use the fibers package to call asynchronous importers from the synchronous code path.

You can disable `fibers` by injecting a Webpack rule to disable it for the `sass-loader`, but compilation will take twice as long. This is currently the only method (in theory) that I've worked out to make Node.js 16.x (LTS) working with Nuxt. However, I still haven't been able to tweak the rule to work with inline scss etc. This is a bit of a pickle, really.

**Comment by vinhnguyentran** [comment]
This error i see when use mac
