### ISSUE TITLE
How to use `nuxtServerInit` with `nuxt generate`?

### ISSUE THREAD

**Issue by askhat** [nuxt/nuxt.js#973]
[Subject repo](https://github.com/askhat/askhat.github.io/tree/init)

I'm trying build my homepage, and, obviously, I've chosen Nuxt.js as my application framework. Also I'm trying to use Contentful as my content deliverer.

I didn't like `contentful` npm package, as Contentful interface, so I decided to create own, with Vuex store.

Contentful doesn't provide _static_ content types, it allows to create an arbitrary type, and associate content with it.

At this point I need to hold data only, and since I don't know data type from semantics point of view, I need just an empty state. So I didn't create any properties on `state` object like so:

```javascript
contentful = {
  state: {}
}
```

Then I made a `mutation` which should define new property with specific name:

```javascript
mutations: {
  defineEntryType: (state, payload) {
    state[pluralize(payload.name.toLowerCase())] = payload
  }
}
```

Also I needed to push actual entries somehow:

```javascript
mutations: {
  pushEntries: (state, payload) {
    const typeName = pluralize(payload.type.name.toLowerCase())
    state[typeName].items = state[typeName].items || []
    state[typeName].items.push(payload.item)
  }
}
}
```

Next thing I need to actually use this crafty mutations, so I made a huge method and placed it in `nuxtServerInit`:

```javascript
actions: {
  nuxtServerInit ({ commit }) {
    axios.get(TYPES_ENDPOINT).then(res => {
      res.data.items.map(type => {
        commit('defineEntryType', type)
        axios.get(ENTRIES_ENDPOINT, {params:
          {content_type: type.id}
        }).then(res => {
          res.data.items.map(item => {
            commit('pushEntries', {type: type, item: item})
          }
        }
      }
    }
  }
}
```

Lastly I needed some getters in order to access `state` in a convenient way:

```javascript
getters: {
  getEntriesByTypeName: state => type => state[type].items,
  getEntryBySlugName: state => type, slug => state[type].items.find(item => item.slug === slug)
}
```

And this is where fun begun.

Since I'd like to host my page on GitHub Pages, I'd like my page to be completely ready to delivery, so I use `nuxt generate`. It works, periodically. When does not work, it yanks an error `TypeError: Cannot read property 'items' of undefined`. Obviously, my property definer wasn't able to pull its job.

Even more fun when `nuxt generate` reports successful built, but the same error gets to the browser console.

__So, my question is: how to use `nuxtServerInit` action for statically generated sites?__

PS: I started to notice that on `dev`, store also misbehaves. Firstly it won't even create itself, then, after page reload, it ready and even with dynamically defined properties, but without prop `items` on 'em, and after the second reload content entries are pushed to target `items` array.

PPS: Sorry, if this issue doesn't comply with your rules. Even though I really need help, so if it is inappropriate, point me where and I cooperate.

Any input appreciated, thank you in advance!

**Comment by Atinux** [comment]
Hi,

Just to make sure, can you make sure to use ˋreturn` evertime you use ˋaxios` in your nuxtServerInit action to make sure that Nuxt knows it has to wait for the end of the promise to be resolved and try again?

**Comment by jsonberry** [comment]
@askhat 

Maybe try something like this:
```javascript
actions: {
    async nuxtServerInit ({ commit }) {
        try {
            const types = await axios.get(TYPES_ENDPOINT)

            while (types.data.items.length) {
                try {
                    const type = types.data.items.shift()
                    commit('defineEntryType', type)
                    
                    const entries = await axios.get(ENTRIES_ENDPOINT, { params: { content_type: type.id } })
                    
                    while (entries.data.items.length) {
                        const item = entries.data.items.shift()
                        commit('pushEntries', { type: type, item: item })
                    }
                } catch (e) {
                    throw e
                }
            }
        } catch (e) {
            console.log(e)
        }
    }
}
```

**Comment by askhat** [comment]
_Sorry for long coming response wasn't able to pay enough attention to this issue till the weekend._

So, first time I took @Atinux's suggestion. And since I cannot `return` two times, I divided `nuxtServerInit` on to two actions: `getTypes` and `getEntries`. It didn't help. So, I guess the problem is in my shitty logic, rather than `nuxtServerInit` itself. I only made it better from a composition point of view.

For the second time, I tried @jsonberry's approach, and, a huge spoiler: approach was not successful. But now I encountered infinite loop somewhere and a consequent memory leak. I didn't any memory analysis, but I'm pretty sure 'cause my laptop fans went crazy.

I guess one of two things gonna happen: I either start to like Contentful's npm package or will switch to Jekyll or Middleman.

Nevertheless, I have a couple pet projects in which Nuxt is already deeply ingrained, and, so I can resolve this issue, I will use Contentful in them.

Thanks, everyone, I guess this thread may be closed, 'cause there is no issue with using `nuxtServerInit` with statically generated sites unless you trying to dynamically define properties on the `state`.

**Comment by jsonberry** [comment]
@askhat 
Yeah one of the issues we've seen is that `nuxtServerInit` is called any time a page is generated or if you're in the dev environment and just routing around; we didn't expect that behavior, but now have come to understand it. 

We ended up caching results in memory and checking for the cache so that `nuxtServerInit` didn't continue to hammer an external API, and we also leveraged the `interval` property.

...That being said, what I wrote _may_ have worked but I might have missed a piece somewhere :) It was just off the top of my head, not tested 👍 

@askhat To lessen the amount of calls you have to make you could try setting up microservices with Now and Micro :man_shrugging:

**Comment by Atinux** [comment]
@askhat how many pages do you have? Also, how many `items` do you have in your TYPES_ENDPOINT result?

I will add a `generate.concurrency` option to allow the generate X page at a time, actually `500`.

Also, you may not need to feel your store with all this data if it's not required for every page.

**Comment by askhat** [comment]
@jsonberry well, to be honest with you I'm seeing this `try catch`/`async await` construction for the first time, so I can't predict its behavior either.

@Atinux I have 3 entries types: articles, authors, and categories. 3 articles, 1 author, and 0 categories. That given, I have only 4 entries (which brought to me with axios) at all.

With all that given, I am still pretty sure the issue in my logic, rather than yours.

**Comment by Atinux** [comment]
`async / await` is a powerful way to abstract Promise, see https://blog.risingstack.com/mastering-async-await-in-nodejs/

But anyway, this should work without any problems:
```js
actions: {
  nuxtServerInit ({ commit }) {
    return axios.get(TYPES_ENDPOINT)
    .then(res => {
      const promises = res.data.items.map(type => {
        commit('defineEntryType', type)
        return axios.get(ENTRIES_ENDPOINT, {
          params: { content_type: type.id }
        })
        .then(res => {
          res.data.items.forEach((item) => {
            commit('pushEntries', { type: type, item: item })
          })
        })
      })
      return Promise.all(promises)
    })
  }
}
```
