### ISSUE TITLE
yarn generate   Error: ENOENT: no such file or directory, mkdir

### ISSUE THREAD

**Issue by Jialufeng** [nuxt/nuxt.js#9731]
nuxt版本：2.15.8

implement   yarn generate 

Nuxt Fatal Error
Error: ENOENT: no such file or directory, mkdir

![image](https://user-images.githubusercontent.com/16443142/131295524-3b3b4262-1e79-45fc-bb83-ab9fc65b26a1.png)

**Comment by Jialufeng** [comment]
> @Jialufeng你能提供一个代码复制/存储库吗？

https://github.com/Jialufeng/nuxt-test.git

Thanks for the trouble。

**Comment by Jialufeng** [comment]
@danielroe I tried sudo yarn generate to solve the problem. Thank you

**Comment by Jialufeng** [comment]
@danielroe Does nuxt separate third-party packages like webpack externals? I use elementui and JS memory of 1M。
![image](https://user-images.githubusercontent.com/16443142/131493186-f7da4de9-36d9-4180-b9f7-f9e7aef89c9d.png)

**Comment by danielroe** [comment]
@Jialufeng You can find out more about what packages are making up your webpack bundle by running `nuxt build --analyze`.

**Comment by danielroe** [comment]
I'm closing this issue as you were able to resolve your issue - glad to hear it 🎉
