### ISSUE TITLE
No possible way to create a paginated and categorised single page listing without duplicating page components

### ISSUE THREAD

**Issue by toddpadwick** [nuxt/nuxt.js#9732]
### Discussed in https://github.com/nuxt/nuxt.js/discussions/9560

<div type='discussions-op-text'>

<sup>Originally posted by **toddpadwick** July 14, 2021</sup>
I have a blog listing page which I need to paginate, and included optional params. The category should also be in the blog article URL as well. so any one of the following URLs could be possible:

`/blog` - would show the first page of blog articles
`/blog/p2` - would show the second page of blog articles
`/blog/news` - would show the first page of blog articles filtered by the 'news' category
`/blog/news/p2` - would show the second page of blog articles filtered by the 'news' category
`/blog/news/checkout-our-new-website` - would show an article page itself

Any directory structure I try causes any one of the following issues:

- The page param gets confused with the article slug or category slug so rather than showing a page number, it tries to load the article template
- I have to repeat the index.vue file for both `/blog` and `/blog/_category`

So I can't find a way to make this possible. I'm sure it's a very common scenario for blogs so I'm sure there must be an easy solution for this. Can anyone help?

**Caveats:**
- We cannot create multiple index.vue components for `blog`, `blog/p2` and `blog/news` etc (even if we call a single component into them) because that would result In a full page re-mount rather than a smooth transition of just the listed articles. When a new category is added, or when next page is clicked, we only want the list of articles to update, not the whole page. our solution must allow for a single index.vue called for all three scenarios.
</div>

**Comment by scottyzen** [comment]
I had a similar issue recently. You can use the extendRoutes function to easily get around it. Here's an example of how I used it.
```js
extendRoutes(routes, resolve) {
    const projectArchive = resolve(__dirname, 'pages/projectArchive')
    const postArchive = resolve(__dirname, 'pages/postArchive')

    // BLOG POSTS
    routes.push({ path: '/blog', component: postArchive })
    routes.push({ path: '/blog/page/:num', component: postArchive })
    routes.push({ path: '/blog/category/:categorySlug', component: postArchive })
    routes.push({ path: '/blog/category/:categorySlug/page/:num', component: postArchive })
    routes.push({ path: '/blog/:slug', component: singlePost })
},
```

 More info here [The router Property](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router)

**Comment by toddpadwick** [comment]
That worked. I was struggling to get my head around extending routes. The docs don't go into much detail but seeing this example really helped. Thanks @scottyzen
