### ISSUE TITLE
Certificate has expired??

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#974]
Hi guys! Please tell me, what's this mean? I have a valid ssl certificate from Let's encrypt, and first time I have this error. And why Nuxt error, if I use express. If remove nuxt-render middleware, express was correct accept all connections.

![image](https://user-images.githubusercontent.com/2588730/27564345-a2ec958a-5adf-11e7-9387-bef23b9a31b6.png)

**Comment by ruslankonev** [comment]
I find. It is wrong config in axios API url

**Comment by waghanza** [comment]
You were using https://www.paulirish.com/2010/the-protocol-relative-url/ no ?
