### ISSUE TITLE
Add ability to set node property server.keepAliveTimeout 

### ISSUE THREAD

**Issue by Noodlewitt** [nuxt/nuxt.js#9740]
### Is your feature request related to a problem? Please describe.

We have seemingly random 502's appearing on our nuxt frontend systems. The root cause seems to be related to our AWS LoadBalancer setup and a parameter `server.keepAliveTimeout` within nodejs.

The LoadBalancer idle time seemingly needs to be set to a value lower than the node parameter `server.keepAlivetimeout`, otherwise we see these 502s appearing. The default value within nuxt seems to be 5 seconds which is too small a value for some of our longer running more complicated pages to load.

### Describe the solution you'd like

I'd like the ability to customize additional server parameters when we run a nuxt start. Most importantly

```
server.keepAliveTimeout
and 
server.headersTimeout
```
see [https://nodejs.org/api/http.html#http_server_keepalivetimeout](https://nodejs.org/api/http.html#http_server_keepalivetimeout) for details

It makes sense to me as a nuxt user to set these in the server object in the `nuxt.config.js` file:

```
...
 server: {
    port: 3000,
    host: 'localhost',
    keepAliveTimeout: 35000,
    headersTimeout: 36000,
  },
...
```

### Describe alternatives you've considered

I've attempted to set this value on node start:
```
# doesn't seem to work
nuxt start --keepAliveTimeout=35000
```

### Additional context
explanations of the issue in a node/express envirnment can be seen here:
https://ngchiwa.medium.com/aws-alb-express-502-ramdom-daaabaafb7cf

**Comment by Noodlewitt** [comment]
fantastic - thank you so much. This looks like it'll work!

**Comment by EaxMov** [comment]
how to set in nuxt3? help lpz

**Comment by nandita121189** [comment]
Any update on the above? Was this feature implemented in Nuxt 3?

**Comment by beshur** [comment]
Thank you!
Posting it here for the history (in case that condesandbox ever goes down):

nuxt.config.js:
```
export default {
  modules: ["./codesandbox"],
  hooks: {
    listen(server) {
      server.keepAliveTimeout = 35000;
      server.headersTimeout = 36000;
      console.log(
        Object.fromEntries(
          Object.entries(server).filter(([key]) => key.includes("Timeout"))
        )
      );
    }
  }
};
```
