### ISSUE TITLE
vue-grid-layout: document is not defined

### ISSUE THREAD

**Issue by navmed** [nuxt/nuxt.js#975]
I'm trying to use this: https://github.com/jbaysolutions/vue-grid-layout. I do have {src: '~plugins/vue-grid-layout', ssr: false} in nuxt.config, but I still get the document is not defined. Any help would be greatly appreciated.

**Comment by pi0** [comment]
Hey @navmed . I've prepared a working example for `vue-grid-layout`. The fact is that unfortunately this library is not desinged for SSR usage. If you still get `document` related errors, you are likely importing `vue-grid-layout` somewhere outside of plugin file.  I've also added [vue-no-ssr](https://github.com/egoist/vue-no-ssr) wrapper to resolve hydration problems.

Demo: https://vue-grid.glitch.me
Code: https://glitch.com/edit/#!/vue-grid

**Comment by navmed** [comment]
Thank you! Your code really helped me.
