### ISSUE TITLE
Build Complete takes too long time on M1 chip Machine

### ISSUE THREAD

**Issue by kohey** [nuxt/nuxt.js#9758]
Hi, as shown in title, If I try to compile nuxt project on my M1 chip Machine, it takes several hours to compile Client and Server.

### Versions
- nuxt: 2.12.1
- node: 12.9.0
- OS: macOS Big Sur 11.5.2
- M1 chip

### Reproduction
It's hard to address problem because It even happens minimum project.
e.g.: https://github.com/kohey/nuxt-on-m1
(Of course,  projects including 3rd party modules(e.g. axios) do behave as the same as above)

### Steps to reproduce
On the versions above,
1. `npx create-nuxt-app sample`
2. `yarn install`
3.  `yarn dev`
4. => this takes hours to complete compiling Client and Server modules

<details open>
<summary>Options to create Project</summary>
<br>
- package manager => Yarn <br>
- UI Framework -> none <br>
- module -> axios <br>
- linting tools -> prittier <br>
- testing frameworks -> none <br>
- rendering mode -> ssr <br>
- deployment target -> server <br>
- deployment tools -> jsconfig.json<br>
</details>

### What is Expected?
compiles smoothly, as on Intel chip.

**Comment by danielroe** [comment]
@kohey If this is happening with a minimal project, there is something desperately wrong and I can only think there is some significant issue with your node setup. 

Perhaps you could share some info about how you set up your dev environment, and confirm whether node is running in Rosetta mode or natively. If you have a reproduction, I'll happily test it on an M1.

**Comment by kohey** [comment]
@danielroe

**Comment by kohey** [comment]
I solved this problem. As you indicated, this problem occurred from node setup.

This environment works perfectly for me.
Compile time changed from 1 hour to 20seconds.

```
- use node version 16.0.0
- remove `node-sass`, instated, install `sass` and `node-loader@7.1.0`
- yarn install && yarn dev
```
