### ISSUE TITLE
server-side fetching data problem

### ISSUE THREAD

**Issue by ummo** [nuxt/nuxt.js#976]
I want to fetch data from the server side, my code is like this:

![image](https://user-images.githubusercontent.com/4112019/27569019-d9005b46-5b27-11e7-8072-505805ae482d.png)

The problem is when I visit the page first time, there is no data injected(I check the webpage source code), and I try the second time which is good, then I can always get data normally. 
here is the CLI log:

![image](https://user-images.githubusercontent.com/4112019/27569202-d5eb7764-5b28-11e7-8303-641178ac5e15.png)

I notice that the blue number first time is too large than the second time visiting(maybe cause by cache), my question is why nuxt doesn‘t wait until fetching data completely? how can I fix that problem?

**Comment by dohomi** [comment]
@ummo not sure how your dispatch function looks like, maybe you forgot to return a promise?

**Comment by alexchopin** [comment]
Hi,
You should use async/await like this:
```js
async fetch() {
  await store.dispatch('templateList', ...)
  return store.dispatch('categoryList', ...)
}
```

**Comment by ummo** [comment]
@dohomi solved my problem, thanks
