### ISSUE TITLE
nuxtServerInit is not called in production built

### ISSUE THREAD

**Issue by Abdalla-Hiekal** [nuxt/nuxt.js#9766]
I'm using "nuxtServerInit" function for authentication
The function works well in development, but it doesn't call in production
I want to inform you that I'm using Azure service to deploy my web app

This is my main module (store/index.js)

```
export const state = () => ({
  counter: 0
})

export const mutations = {
  increment(state) {
    state.counter++
  }
}

export const actions = {

  async getUser({ commit }) {
    const https = require("https");
    const agent = new https.Agent({
      rejectUnauthorized: false
    })
    const data = await this.$http.$get('/api/user/', { agent })
    commit('authentication/setData',data)
  },
      
  async nuxtServerInit({ dispatch }) {
    await dispatch('getUser')
  }
  
}
```

**Comment by dumptyd** [comment]
I ran into this issue when serving the production bundle of my static-target app. This is what fixed it for me.

https://github.com/nuxt/nuxt.js/issues/7051#issuecomment-604914461
