### ISSUE TITLE
latest update bug

### ISSUE THREAD

**Issue by aymenpeak** [nuxt/nuxt.js#977]
hey,
my project was working just fine until i updated my nuxt version yesterday, now i receive this error 
![image](https://user-images.githubusercontent.com/19589742/27578527-a9c9fcc2-5b24-11e7-985c-de74a88b7b49.png)

any ideas?

**Comment by alexchopin** [comment]
By what we can read, the issue seems to be in vue-awesome.
Can you show more code snippets?

**Comment by aymenpeak** [comment]
i solved it by changing the import from 
```
import 'vue-awesome/icons'
import Icon from 'vue-awesome/components/Icon'
```
To

`var Icon = require('vue-awesome/components/Icon.vue')`
(it was working with nuxt 0.9.7 by the way)
thanx.
