### ISSUE TITLE
How to send multiple requests in asyncData

### ISSUE THREAD

**Issue by justyeh** [nuxt/nuxt.js#978]
Sorry, I'm not good at english!
This is my asyncData method :
```
export default {
  async asyncData({ query, error }) {
    return axios.all([
      axios.get('/api/post/page/0'),
      axios.get('/api/post/count/published')
    ]).then(axios.spread((pageRes, countRes) => {
      return {
        posts: pageRes.data.list,
        total: countRes.data.result
      }
    })).catch((err) => {
      error({ statusCode: 404, message: err.message })
    })
  }
}
```
I want to send multiple requests in asyncData，but it doesn't work，here is error information:
```
(node:9360) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: __WEBPACK_IMPORTED_MODULE_2__plugins_axios__.a.all is not a function
```

**Comment by alexchopin** [comment]
```js
export default {
  async asyncData({ query, error }) {
    let pageRes = await axios.get('/api/post/page/0')
    let countRes = await axios.get('/api/post/count/published')
    return {
       posts: pageRes.data.list,
       total: countRes.data.result
    }
  }
}
```

**Comment by cawa-93** [comment]
In @alexchopin example Requests will be sent one by one.
If you want to run both requests in parallel:
```js
export default {
  async asyncData({ query, error }) {
    let [pageRes, countRes] = await Promise.all([
      axios.get('/api/post/page/0'),
      axios.get('/api/post/count/published'),
    ])
    return {
       posts: pageRes.data.list,
       total: countRes.data.result
    }
  }
}
```

**Comment by marcosleonel** [comment]
@cawa-93 @alexchopin Nice. Could you help me to know how to display these two requests inside the <template>? Do I must use {{ posts.[property] }}?

**Comment by cawa-93** [comment]
@marcosleonel What do you mean?

**Comment by marcosleonel** [comment]
@cawa-93 For instance, in [this tutorial ](https://www.superawesomegood.com/2017/10/23/building-a-blog-with-wp-api-nuxt/) I have just one request:

`<template>
  <section class="container">
    <div>
      <PostList :posts="posts" />
    </div>
  </section>
</template>

<script>
import PostList from '~/components/posts/PostList.vue'
import wp from '~/lib/wp'
export default {
  async asyncData ({ params }) {
    return wp.posts()
  },
  components: {
    PostList
  }
}
</script>`

If I add one more request according to your tip, I have this:

`export default {
  async asyncData ({ params }) {
    let wpPost = wp.posts();
    let wpAnything = wp.anything();
    return {
        posts: wpPost.posts,
        anything: wpAnything.something
    }
  },
  components: {
    PostList
  }
}`

(The Axios get method is called through wp.posts() and wp.anything from [another file](https://github.com/6stringbeliever/nuxt_wp/blob/v1.0/lib/wp.js)).

Then if I keep the same template code... 

`
<template>
  <section class="container">
    <div>
      <PostList :posts="posts" />
    </div>
  </section>
</template>`

...nothing is displayed in the app. 

What must change to this work well?

**Comment by cawa-93** [comment]
It seems to me that in your example there are several mistakes
```js
export default {
  async asyncData ({ params }) {
    let wpPost = await wp.posts();
    let wpAnything = await wp.anything();
    return {
        posts: wpPost.posts,
        anything: wpAnything.something
    }
  },
  components: {
    PostList
  }
}
```
