### ISSUE TITLE
Nuxt + Vuetify  Class="col-4" only works in npm run dev and not in npm run start

### ISSUE THREAD

**Issue by 23brewert** [nuxt/nuxt.js#9782]
### Versions

- nuxt: v2.15.7
- node: v16.2.0
- chrome v93.0.4577.63 (Official Build) (64-bit)

### Reproduction

<details open>
<summary>Additional Details</summary>
<be>
Packages:
`{
  "name": "prism",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/auth-next": "^5.0.0-1624817847.21691f1",
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/recaptcha": "^1.0.4",
    "core-js": "^3.15.1",
    "nuxt": "^2.15.7",
    "vee-validate": "^3.4.12",
    "vuetify": "^2.5.5"
  },
  "devDependencies": {
    "@nuxtjs/vuetify": "^1.12.1"
  }
}
`
</details>

### Steps to reproduce

npx create-nuxt-app app
>JavaScript
>Vuetify
>EsLint
>All Default options related to ssr and Visual Studio Code

+Add a test vue page
+ Make a test card:  <v-card class="col-4">Hello!!</v-card> 
+ Save the file and run `npm run dev`
+ Go to the page that you created in chrome.
+ You will see that it will not expand to the whole page like if you were to remove the col-4
+ Then go back and end the process by pressing CTRL+C
+ Now build the app for production using `npm run build`.
+ When finished starting the production app by using `npm run start`.

### What is Expected?

The Card should stay 4 columns in both environments.

### What is actually happening?

The Card will only resize to 4 columns in dev mode and will be the width of the page in production.

**Comment by danielroe** [comment]
@23brewert would you provide a reproduction repository or [codesandbox](https://template.nuxtjs.org)?

**Comment by KareemDa** [comment]
I've cloned the project and It's working with no problems.

I used `npm run dev` then `npm start` and this is the result

![image](https://user-images.githubusercontent.com/42810389/147781058-ee48831a-4f44-43ed-a3e8-79f2d0379cb3.png)
