### ISSUE TITLE
Is it possible to use file-system packages inside nuxtServerInit?

### ISSUE THREAD

**Issue by lukaszkups** [nuxt/nuxt.js#979]
I've put my `posts` folder with markdown-based article files inside `static` directory. 

I would like to list these files inside my post list template without using express/other server-side framework - is it possible? 

Adding `file-system` packages (or similar) causes errors because I think nuxt executes them somehow on client side anyway.

**Comment by pi0** [comment]
Would please explain more / providing code snippets for usage ? We can add some condition like this to do requires only on server side:
```js
if (!process.BROWSER) {
  require('some-package')
}
```

**Comment by lukaszkups** [comment]
I wanted to use file-system to enhance capabilities my nuxt website as a static-site generator with some custom file listing and/or file uploading (e.g. images that are inserted in textarea are moved into proper nuxt folder to use them in the blog post) - but after generation page that is used as a article editor won't be generated etc.
