### ISSUE TITLE
keywords if/then/else require v5 option

### ISSUE THREAD

**Issue by gregbenner** [nuxt/nuxt.js#98]
`keywords if/then/else require v5 option` error on a fresh install of nuxt, not sure where in the library this is being generated from.

**Comment by Atinux** [comment]
Hi @gregbenner 

This is from webpack, it's fixed in the latest release of webpack `v2.2.0-rc3`.

It will be fixed in the next upcoming release.

**Comment by gregbenner** [comment]
Sweet, thanks!
