### ISSUE TITLE
Changing file/folder in static

### ISSUE THREAD

**Issue by bartdominiak** [nuxt/nuxt.js#980]
I'm trying to change Static genereted .html files from `nuxt generate`

For example - my folder structure looks like this:
```
-| pages/
----| home
------| home.vue
----| about
------| about.vue
...
```

Output:
```
-| dist/
----| home
------| home
--------| index.html
----| about
------| about
--------| index.html
...
```

I would like to achive something like this below:
```
-| dist/
----| home
------| home.html
----| about
------| about.html
...
```

**Comment by alexchopin** [comment]
Nuxt generate only `index.html` file, due to static routing.
So the best solution in your case is:
```
-| dist/
----| home
------| index.html
----| about
------| index.html
...
```
Can you explain me more about why you need this kind of result? Thanks
