### ISSUE TITLE
Re-Rendering bug or smth...

### ISSUE THREAD

**Issue by numfin** [nuxt/nuxt.js#981]
I dont know whats happening... Nuxt just fetch data, pushes it to the store and then i can see the data for 0.1s in my browser and then it dissapear. Can someone explain me pls what im doing wrong? Please.

[here is the code](https://gist.github.com/numfin/f0cda1d40c0003b9f67d2be0516dffa7)

[here is the video. Pls lower the audio, because i forgot to mute it](https://firebasestorage.googleapis.com/v0/b/ffmpegod.appspot.com/o/2017-06-27%2023-17-13.mp4?alt=media&token=b3d84ba0-29a5-4a79-a87c-82e0ea3f896d)

**Comment by numfin** [comment]
seems like its not working at all
[screenshot](http://prntscr.com/foykqd)

**Comment by numfin** [comment]
not even like [this](http://prntscr.com/foypcn)

**Comment by KonstantinVlasov** [comment]
hi, @numfin!
I have had this problem. The reason was the browser extension that uses react. Try to turn off extensions and check again.

**Comment by numfin** [comment]
@KonstantinVlasov  nope. its not the solve of the problem.

**Comment by numfin** [comment]
The solution of this problem is just use asyncData for async store data. So this is the solution:
![screenshot_1](https://user-images.githubusercontent.com/8134947/27635031-42e06c22-5c0e-11e7-8a15-7c2d3e352041.png)
