### ISSUE TITLE
Transition on Error page doesn't work.

### ISSUE THREAD

**Issue by jerakode** [nuxt/nuxt.js#982]
I tried to add `transition(name="page", mode="out-in")` (pug) on both - Error and Default layout, but it doesn't help.

**Comment by alexchopin** [comment]
Can you explain more with some code snippets or example?
It should work by default, have you tried to create a [css class](https://nuxtjs.org/examples/routes-transitions/#__nuxt)?

**Comment by jerakode** [comment]
@alexchopin of course CSS class is cretaed, all transitions are working, except when route to 404.

**Comment by jerakode** [comment]
Why did you close this issue? Is it fixed already? Or may be it's not important?

**Comment by alexchopin** [comment]
I closed it because it should be fixed in the next release. I was a know bug.

**Comment by alexchopin** [comment]
Should be fixed now with the rc3.

**Comment by iamdubx** [comment]
@alexchopin it's still doesn't work.

**Comment by ram-you** [comment]
@alexchopin still not working.
