### ISSUE TITLE
some pages in docs not showing

### ISSUE THREAD

**Issue by ousszizou** [nuxt/nuxt.js#9828]
Hello,

there are some pages when I visited them not display correctly ( md files not found ).

pages are: 
- https://nuxtjs.org/docs/features/rendering-modes
- https://nuxtjs.org/docs/features/file-system-routing
- https://nuxtjs.org/docs/features/data-fetching
- https://nuxtjs.org/docs/features/meta-tags-seo
- https://nuxtjs.org/docs/features/configuration
- https://nuxtjs.org/docs/features/loading
- https://nuxtjs.org/docs/features/component-discovery
- https://nuxtjs.org/docs/features/transitions

when visit one of them it will display 404 page with that error : 
`(/_nuxt/_docus/410d5d83/content:en:docs:3.features:5.meta-tags-seo.md.json)`

and this is an image that show what I mean

[![screencapture-nuxtjs-org-docs-features-meta-tags-seo-2021-09-21-16-31-13.png](https://i.postimg.cc/5tv5bsdN/screencapture-nuxtjs-org-docs-features-meta-tags-seo-2021-09-21-16-31-13.png)](https://postimg.cc/jWxnhQSG)

**Comment by Intevel** [comment]
The bug does not occur for me.
![image](https://user-images.githubusercontent.com/59223342/134215471-cfe55485-efce-4339-9e7d-102655cb9f6d.png)
