### ISSUE TITLE
<nuxt-child/>

### ISSUE THREAD

**Issue by github1586** [nuxt/nuxt.js#985]
Use nested routing father routing in <nuxt-child/>if the parent route for routing for a/b/a child now access/a/b why the HTML component a and component b are not replace @Atinux

**Comment by alexchopin** [comment]
Sorry, but can you try to explain more?

**Comment by github1586** [comment]
I want to make a single page but the coexisting HTML and parent routing HTML of the subways are not the same as the HTML that replaces the parent route @alexchopin

**Comment by github1586** [comment]
The subways are also clickable and you can go to the subpath by not replacing the HTML @alexchopin

**Comment by github1586** [comment]
I also added <nuxt-child/> in the parent route

**Comment by github1586** [comment]
I also added <nuxt-child/> in the parent route

**Comment by github1586** [comment]
I also added "<nuxt-child/>" in the parent route

**Comment by github1586** [comment]
I also added `<nuxt-child/>` in the parent route

**Comment by github1586** [comment]
I also added <nuxt-child/> in the parent route as .vue file

**Comment by uptownhr** [comment]
@github1586 will you be able to provide some samples of what you mean?

**Comment by github1586** [comment]
--pages/
  --test/
    testlist.vue
  -test.vue
*******************************************************************
I would like to page test.vue and sub routing testlist.vue single page switching @uptownhr

**Comment by github1586** [comment]
--pages/
  --test/
 `-testlist.vue
-test.vue`

*******************************************
I would like to page test.vue and sub routing testlist.vue single page switching @uptownhr

**Comment by alexchopin** [comment]
Like this?
```
pages/
- test/
-- testlist.vue
```

If you don't need to use child route, don't create the parent file.

**Comment by github1586** [comment]
thank you ~
