### ISSUE TITLE
Incorrect return type for $fetch in TypeScript

### ISSUE THREAD

**Issue by ThibaultVlacich** [nuxt/nuxt.js#9853]
Shouldn't the [return type of $fetch](https://github.com/nuxt/nuxt.js/blob/dev/packages/types/app/vue.d.ts#L108) be `Promise<void>` instead of just `void` (or at least `void | Promise<void>`), based [on this](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/mixins/fetch.client.js#L104)?

I'll make a PR to fix it if it's indeed an error.

**Comment by danielroe** [comment]
@ThibaultVlacich You're quite right!
