### ISSUE TITLE
head method can't use on Client nuxt-link

### ISSUE THREAD

**Issue by CV-souryu** [nuxt/nuxt.js#9867]
when i used router on Client, the head method on last page is did't work,it can't reset <title> and <mate>,
but on last page use F5 to reload page the head method is worked.
how can the head method work on Client router，not use  mounted
nuxt^2.15.7

**Comment by CV-souryu** [comment]
> 
> 
> @CV-souryu Would you provide a reproduction? 🙏

thanks,
i don't use cdn(vue,vue-router,vuex) to solve this problem

```
nuxt.config.js
  head: {
    script: [
      ...[
        // process.env.NODE_ENV == 'development' ? 'https://unpkg.zhimg.com/vue' : 'https://unpkg.com/vue@2.6.14/dist/vue.min.js',
        // 'https://unpkg.zhimg.com/vue-router@3.5.1/dist/vue-router.js',
        // 'https://unpkg.zhimg.com/vuex@3.6.2',
        'https://unpkg.zhimg.com/element-ui@2.13.2/lib/index.js',
        'https://unpkg.zhimg.com/highcharts@9.2.2',
        'https://unpkg.zhimg.com/highcharts@9.2.2/highcharts-more',
        'https://unpkg.zhimg.com/highcharts-vue@1.4.0'
      ].map(item => { return { src: item } })
    ]
  }
  ...,
  build:{
  ...,
  extend(config, ctx) {
      ...
      if (ctx.isClient) {
        config.externals = {
          // 'vue': 'Vue',
          // 'vue-router': 'VueRouter',
          // 'vuex': 'Vuex',
          'element-ui': 'ELEMENT',
          'highcharts': 'Highcharts',
          'highcharts-vue': 'HighchartsVue'
        }
      }
    },
  }
```

**Comment by CV-souryu** [comment]
> 
> 
> @CV-souryu Would you create the reproduction with https://template.nuxtjs.org/ ?

like this ? [https://github.com/CV-souryu/nuxt-20211001problem](url)

**Comment by danielroe** [comment]
Nuxt includes vue, vue-router, and vuex in the bundle. So no need to include them separately in the head as standalone scripts. When removed, your reproduction works fine: https://codesandbox.io/s/bold-tdd-z0fnn?file=/nuxt.config.js.
