### ISSUE TITLE
unit testing with v1.x

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt.js#987]
I believe that since v1.x nuxt now returns a promise, would this then be an acceptable way to run tests against it? And if not how? and should/can we update the documentation?

```javascript


import test from 'ava'
import Nuxt from 'nuxt'
import { resolve } from 'path'

let nuxt = null
let server = null

const rootDir = resolve(__dirname, '..')
let config = {}
try { config = require(resolve(rootDir, 'nuxt.config.js')) } catch (e) {}
config.rootDir = rootDir // project folder
config.dev = false // production build

nuxt = new Nuxt(config).then(nuxt => {

  test.before('Initializing Nuxt.js', async t => {
    await nuxt.build()
    server = new nuxt.Server(nuxt)
    server.listen(4000, 'localhost')
  })

  test('Route / exits and renders HTML', async t => {
    let context = {}
    const { html } = await nuxt.renderRoute('/', context)
    t.true(html.includes('<div class="page home">'))
  })

  test.after('Closing the server and nuxt.js', t => {
    server.close()
    nuxt.close()
  })

})

```

**Comment by uptownhr** [comment]
@acidjazz i believe the returning of the promise was reverted in alpha3.

**Comment by acidjazz** [comment]
@uptownhr really? i'm running this code in alpha4 and it's working

![image](https://user-images.githubusercontent.com/967369/27757439-7017d50a-5db6-11e7-999a-53819983812c.png)

**Comment by acidjazz** [comment]
I've upgraded to `alpha.4` and confirmed the Promise has been removed as @uptownhr suggested, this question is invalid now that v1.x runs the test specified in the documentation
