### ISSUE TITLE
Can't use nest as server middlevare 

### ISSUE THREAD

**Issue by n4an** [nuxt/nuxt.js#9880]
ERROR [ExceptionsHandler] Cannot read property 'findOne' of undefined TypeError: Cannot read property 'findOne' of undefined

[Nest] 16671 - 09/21/2021, 5:00:55 PM ERROR [ExceptionsHandler] Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform.

### Versions

- nuxt: latest
- node: latest

### Reproduction
https://github.com/Mitch-i/nuxt_nest

open some api path like /api/users

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by Mitch-i** [comment]
it work if use compiled nest app and not work with uncompiled. But nuxt say You're using Nuxt 2.15.8, which includes built-in TypeScript runtime support. 

It importing a typescript file in a javascript file?
