### ISSUE TITLE
additional watch files added through watch in nuxt.config do not trigger HMR

### ISSUE THREAD

**Issue by CircleCode** [nuxt/nuxt.js#9891]
### Versions

- nuxt: v2.15.8
- node: v14.17.6

### Steps to reproduce

- in nuxt.config.js, add
  ```js
  watch: [
    'node_modules/my/custom/module/*.js'
  ]
  ```
- run `yarn run dev`
- modify a file in  `node_modules/my/custom/module/*.js`

### What is Expected?

- a new build is triggered
- the page is reloaded

### What is actually happening?

- a new build is triggered
- the page is __NOT__ reloaded

**Comment by Szymon-dziewonski** [comment]
@CircleCode any news on that, did you maybe managed to make this work?

**Comment by FoxRLY** [comment]
Still now working
