### ISSUE TITLE
Use with vue-auth. Need access to router

### ISSUE THREAD

**Issue by scottgrayson** [nuxt/nuxt.js#99]
I would like to use vue-auth together with nuxt js.  But i need to configure vue-auth after vue router is set.

vue-auth setup code from https://github.com/websanova/vue-auth#install-2x
```
Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    ...
    rolesVar: 'type'
    ...
});
```

I tried doing this in the `~/plugins` directory and i get a vue-auth error:
` Error (@websanova/vue-auth): vue-router.2.x.js : Vue.router must be set. `

**Comment by Atinux** [comment]
Hi @scottgrayson 

Sadly, nuxt.js is not compatible with `vue-auth`, but using JWT with Nuxt.js and the upcoming middleware feature will be really easy to do.

**Comment by scottgrayson** [comment]
@Atinux Awesome! Can't wait to see the docs!

**Comment by Atinux** [comment]
The documentation should be release today, think about checking [our Twitter](https://twitter.com/nuxt_js) for the announcement :)

**Comment by davoudrafati** [comment]
there is no middleware yet, what's the play we need JWT auth
