### ISSUE TITLE
Pass options to Nuxt Plugins 

### ISSUE THREAD

**Issue by alidcastano** [nuxt/nuxt.js#991]
Rather than just requiring a string, would it also be possible to pass options to the plugin upon install? Or at the least, passing a function or object, instead of a string path, as a Nuxt plugin.

for example: 

```
// module.js
this.addPlugin({ src: 'somePath', options: { msg: 'hello' } })

// plugin.js
export default (ctx, opts) => {
   opts.msg   // hello
}
```
Or: 

```
this.addPlugin((ctx) => {
   ....
})
```

Modules are useful to configure the Nuxt build, but plugins give access to the Nuxt instance. Except without the ability to pass options, they're only useful for hooking simple Vue plugins to Nuxt.

**Comment by pi0** [comment]
Passing options to plugins via template needs serialization of them so losing access to references. (Like how scrollTo config works) I think currently you can use `end` to set global run-time options too.
