### ISSUE TITLE
running container of nuxt app docker image built using github actions fails (heap memory size exceeded)

### ISSUE THREAD

**Issue by hamzamogni** [nuxt/nuxt.js#9916]
### Versions

- nuxt: v2.14.7
- node: node:alpine image

### Reproduction
Using a Dockerfile similar to the one provided by Nuxt.js documentation (I changed node:lts to node:alpine), and setupping GitHub actions workflow to automatically build and push docker image to the registry.

This is my [Dockerfile](https://pastebin.com/qdZUiYmk), 

and this is my [github action workflow file](https://pastebin.com/ZWTKaFV4)

when I build the image locally on my machine it works normally, but when I pull the one built on GitHub actions and run it fails to serve my app (infinite loading), and the process keeps eating up machine memory until getting killed by SIGABRT; The following error is logged.

> <--- Last few GCs --->

> [28:0x7f75bc1ae310] 730417 ms: Mark-sweep (reduce) 2040.7 (2083.0) -> 2039.5 (2083.2) MB, 4274.1 / 0.5 ms (average mu = 0.200, current mu = 0.163) allocation failure scavenge might not succeed [28:0x7f75bc1ae310] 734992 ms: Mark-sweep (reduce) 2040.6 (2083.2) -> 2039.7 (2083.2) MB, 4549.0 / 0.5 ms (average mu = 0.112, current mu = 0.006) allocation failure scavenge might not succeed

> <--- JS stacktrace -->

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. error Command failed with signal "SIGABRT".

### What is Expected?
The image built on GitHub actions should un normally as the one built locally on my machine 

### What is actually happening?
It fails to serve the application and keeps consuming memory until killed by system

**Comment by BlowAlone** [comment]
@hamzamogni Have you found any solution to this problem? I had the same "heap out of memory" and "infinite loops" with `nuxtjs/axios` and gitlab ci with `--max-old-space-size=8192`

**Comment by hamzamogni** [comment]
I fixed it by writing baseUrl directly in nuxt.conf.js instead of loading it from .env file.
