### ISSUE TITLE
cookie del error  

### ISSUE THREAD

**Issue by fxh615** [nuxt/nuxt.js#992]
on the middleware i use 
 res.setHeader('Set-Cookie', 'token=abc' , {
      path: '/'
  });

token :abc is work but the path set not work.
and can not clear the cookie key token sometime have two cookie which have the same key "token" and have the deff path name. OMG .

**Comment by alexchopin** [comment]
Can you explain more, I'm not sure to understand you question.

**Comment by fxh615** [comment]
have fixed .
