### ISSUE TITLE
Lib vue-picture-input not working with SSR

### ISSUE THREAD

**Issue by alexisohayon** [nuxt/nuxt.js#995]
Hi,

I have a problem when I load a page directly from the server (not encountered when dynamically loaded) : 
```
Nuxt.js Error:
ReferenceError: File is not defined
    at Object.237 (PictureInput.vue:89:0)
```

from this component: https://github.com/alessiomaffeis/vue-picture-input/blob/master/PictureInput.vue

It seems that SSR is causing this, how to make an exception so it doesnt load it before the page is mounted?

Thanks!

**Comment by alexchopin** [comment]
You can use option `ssr:false`, [documentation](https://nuxtjs.org/api/configuration-plugins/#the-plugins-property).

**Comment by alexisohayon** [comment]
@alexchopin Thanks for the quick answer :)
But am I forced to use plugins for this?

(I'm pretty new to vue.js and nuxt, amazing work btw 👍 )

**Comment by alexisohayon** [comment]
Besides, this component doesnt require a Vue.use and seem to cause other bugs when using it this way : 
```
Nuxt.js Error:

node_modules/vue-picture-input/PictureInput.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <
```

I'm not sure of the way to use the ssr:false option in this use case :/

**Comment by alexchopin** [comment]
My bad, the error is due to the props type at line 89.
The type is File, but Vue doesn't recognize this type: [Vue.js Documentation](https://vuejs.org/v2/guide/components.html#Prop-Validation)

**Comment by farin** [comment]
easy patch to make it working with Nuxt SSR:

change
```
prefill: {
  type: [String, File],
  default: ''
},
```

to
```
prefill: {
  type: process.server ? [String] : [String, File],
  default: ''
},
```

**Comment by galvez** [comment]
@farin nice! Would you be so kind to open an issue or PR with that fix over at [vue-picture-input(https://github.com/alessiomaffeis/vue-picture-input)?

**Comment by farin** [comment]
@galvez Yes, I am going to open it tomorrow. Today is too late, goint to be ;-)

**Comment by farin** [comment]
+ I think general patch working both in browser and node must be made little bit more sophisticated (I am afraid that process is not defined eg. when vue-picture-input use unpkg)

Proper solution will be rather test nonexistence of File. But for nuxt project my patch is good enough.

**Comment by duythang** [comment]
@farin: After applying your change, do you know how can i integrate ```vue-picture-input``` into ```Nuxt```? 
Thank you

**Comment by godheaper** [comment]
I tried changing the PictureInput library file with @farin 's answer

> easy patch to make it working with Nuxt SSR:
> 
> change
> 
> ```
> prefill: {
>   type: [String, File],
>   default: ''
> },
> ```
> to
> 
> ```
> prefill: {
>   type: process.server ? [String] : [String, File],
>   default: ''
> },
> ```

And also by changing the way nuxt js import the external libraries, like with vue-picture-input

in nuxt.config.js :
`const nodeExternals = require('webpack-node-externals');

module.exports = {
   ...
  extend(config, { isServer }) {
    if (isServer) {
      config.externals = [
        nodeExternals({
          whitelist: [/\.(?!(?:js|json)$).{1,5}$/i, /^vue-picture-input/]
        })
      ]
    }
  },
  ...
}`

This works for me for the time being. Please correct me if there's a better way

**Comment by duythang** [comment]
@godheaper: did you add vue-picture-input by creating plugin file in the plugins folder ?
