### ISSUE TITLE
I'm writing height below display: inline-block, why does the style change like this?

### ISSUE THREAD

**Issue by github1586** [nuxt/nuxt.js#998]
I'm writing height below display: inline-block, why does the style change like this?
![image](https://user-images.githubusercontent.com/24525964/27723912-edb36c5a-5da1-11e7-9c3b-b5f2484f9236.png)

**Comment by github1586** [comment]
![image](https://user-images.githubusercontent.com/24525964/27724026-6a3458e8-5da2-11e7-932f-abbdc691e829.png)

**Comment by github1586** [comment]
@VictorTolbert

**Comment by uptownhr** [comment]
what is the problem?

**Comment by github1586** [comment]
I'm writing height below display: inline-block, why does the style change like this?
image

**Comment by lucpotage** [comment]
It's more a CSS issue than a Nuxt issue. It seems the property is overriden. It's impossible to help you with just a screenshot of your code… 😉
