### ISSUE TITLE
Express error handling not working in serverMiddleware

### ISSUE THREAD

**Issue by DaDoBaag** [nuxt/nuxt.js#9985]
### Versions

- nuxt: v2.15.7
- node: v14.15.1
- express: v4.17.1

### Reproduction

Couldn't get a backend to work on Codesandbox so this code snippet has to suffice for now.

```js
// /serverMiddleware/index.js

import express from "express"

class HTTPError extends Error {
  constructor (status) {
    super()
    this.status = status
  }
}

class BadRequestError extends HTTPError {
  constructor () {
    super(400)
  }
}

const app = express()

app.get("/", async (req, res, next) => {
  try {
    // validate req
    if (typeof req.query.foo !== "string") throw new BadRequestError()

    res.sendStatus(200)
  } catch (error) {
    next(error)
  }
})

export default app
```

Relevant quote from the [Express docs](https://expressjs.com/en/guide/error-handling.html) about error handling:
> If you pass an error to `next()` and you do not handle it in a custom error handler, it will be handled by the built-in error handler; the error will be written to the client with the stack trace. The stack trace is not included in the production environment.
> 
> When an error is written, the following information is added to the response:
> 
> * The `res.statusCode` is set from `err.status` (or `err.statusCode`). If this value is outside the 4xx or 5xx range, it will be set to 500.

### Steps to reproduce
- create nuxt app
- at project root add /serverMiddleware/index.js file from the code snippet above
- in nuxt.config.js add `serverMiddleware: { "api": "./serverMiddleware/index.js" }`
- run dev build
- make request to `http://localhost:3000/api`

### What is Expected?
- `GET http://localhost:3000/api?foo=hello` responds with `200 OK`
- `GET http://localhost:3000/api` responds with `400 Bad Request`

### What is actually happening?
- `GET http://localhost:3000/api?foo=hello` responds with `200 OK` -> as expected
- `GET http://localhost:3000/api` responds with `500 Runtime Error` with an appended stack trace pointing to the line where BadRequestError is thrown -> wrong

**When running this exact same code with `app.listen(...)` instead of `export default app` in an isolated Express-only project without Nuxt.js I get the 400 Bad Request as expected, meaning this is clearly a Nuxt issue.**

**Comment by silvesterwali** [comment]
hi @DaDoBaag  in this case my  `nuxt.config.js` look like below
```js
 serverMiddleware: [{ path: '/api', handler: '~/api/index.js' }],
```

and in api/index.js
```js

const express = require('express')
const app = express()

app.get('/',(req,res)=>{
   res.json({message:"hello there"})
})

module.exports = app
````

**Comment by DaDoBaag** [comment]
@silvesterwali ok what is that supposed to tell me?

**Comment by silvesterwali** [comment]
from official docs, I found at https://nuxtjs.org/docs/configuration-glossary/configuration-servermiddleware and in your nuxt config I see the difference:
this is your config:
```js
serverMiddleware: { "api": "./serverMiddleware/index.js" }
```
according to the docs
```js
serverMiddleware: { path:"api",  handler: "./serverMiddleware/index.js" }
```
but I don't know if nuxt accepts the config as you write in your nuxt.config.js . that is why I try to help with my code.
