### ISSUE TITLE
Vuex module mutation-type bug

### ISSUE THREAD

**Issue by OrangeXC** [nuxt/nuxt.js#999]
When I use `store.commit` in middleware it's work, like this

```
import { getUserFromCookie, getUserFromLocalStorage } from '~/utils/auth'

export default function ({ isServer, store, req }) {
  // If nuxt generate, pass this middleware
  if (isServer && !req) return
  const loggedUser = isServer ? getUserFromCookie(req) : getUserFromLocalStorage()
  if (loggedUser) {
    store.commit('user/SET_TOKEN', loggedUser)
    store.$axios.setToken(loggedUser.token)
  }
}
```

I have use `user/SET_TOKEN` mutation-type, the token is set in my user module state

But in my vuex `country` module I want `commit('select/REMOVE_SELECTED')` in action

throw error

```
[vuex] unknown local mutation type: select/REMOVE_SELECTED, global type: country/select/REMOVE_SELECTED
```

So, how to commit mutation-type cross module

**Comment by alexchopin** [comment]
Hi,
You need to set the third parameter to `{ root: true }`like this:
```js
commit('someMutation', null, { root: true }) // -> 'someMutation
```
[Official Vuex Documentation](https://vuex.vuejs.org/en/modules.html)
